### ISSUE TITLE
Enable libcurl cookie engine

### ISSUE THREAD

**Issue by idixon** [OSGeo/gdal#1000]
We would like libcurl in gdal to enable the cookie engine. The files we are trying to access with /vsicurl/ have a redirect auth in front of them. Without the cookie engine enabled the auth cookie is never forwarded and the requests fail.

We confirmed this is possible by adding:

**curl_easy_setopt(http_handle, CURLOPT_COOKIEFILE, "");**

to cpl_http.cpp in version 2.3.2.

As an additional feature it would be great to have the COOKIEFILE and COOKIEJAR options exposed to the user.

**Comment by asjohnston-asf** [comment]
Fulfilling this enhancement request would allow vsicurl requests against files protected by single-sign-on authentication.  In particular, NASA's earth science mission data are hosted behind authentication administered by https://urs.earthdata.nasa.gov .  vsicurl already supports redirects and netrc credentials, but also needs libcurl's cookie engine enabled to support the single-sign-on workflow.  Enabling the cookie engine internally, or allowing users to override the CURLOPT_COOKIEFILE and CURLOPT_COOKIEJAR libcurl options at runtime, would allow gdal users to interact with these data sets directly over the web.

NASA Earth Observation Data - https://earthdata.nasa.gov/earth-observation-data
NASA Earthdata Login SSO - https://earthdata.nasa.gov/about/science-system-description/eosdis-components/earthdata-login

**Comment by scottyhq** [comment]
This would be great to get into the next release since it just seems to require a few environment variables and will open up a lot of useful archived datasets! I'll follow up with a pull request.
