### ISSUE TITLE
osgeo NameError when running `gnm` python tests

### ISSUE THREAD

**Issue by craigds** [OSGeo/gdal#1001]
( upgraded from my comment at #975 )

## Expected behavior and actual behavior.

The `osgeo` import is no longer defined in some of the tests, causing a `NameError` when you run or import the `gnm` module. I believe this was introduced in #975.

## Steps to reproduce the problem.

```bash

vagrant@gdal-vagrant:~/gnumake-build-gcc4.8$ PYTHONPATH=swig/python/build/lib.linux-x86_64-2.7/ autotest/run_all.py gnm
... failed to load gnm_test.py ... skipping.
Traceback (most recent call last):
  File "pymod/gdaltest.py", line 296, in run_all
    exec("import " + module)
  File "<string>", line 1, in <module>
  File "./gnm_test.py", line 43, in <module>
  File "/home/vagrant/gnumake-build-gcc4.8/swig/python/build/lib.linux-x86_64-2.7/osgeo/gnm.py", line 133, in <module>
    class Network(osgeo.ogr.MajorObject):
NameError: name 'osgeo' is not defined

Succeeded: 0
Failed:    0 (0 blew exceptions)
Skipped:   0
Expected fail:0
Duration:  0.01s

Found libgdal we are running against : /usr/lib/libgdal.so.2.4.0
```

## Operating system

Ubuntu 14.04 64 bit

## GDAL version and provenance

master @ 26116b3d1c0216dbe86c2d39d0599ea19a815c5a

**Comment by rouault** [comment]
@miurahr Any idea ?

**Comment by miurahr** [comment]
@rouault It is exactly a tthing happend by a reason @craigds pointed out.

**Comment by miurahr** [comment]
I added a sed hack to replace osgeo.ogr.MajorObject in PR #1002.
