### ISSUE TITLE
Very easy to report exactly which argument caused the failure

### ISSUE THREAD

**Issue by jidanni** [OSGeo/gdal#10011]
### Feature description

```
$ gdal_grid -l 0 -a nearest -txe -1200 200 \
  -tye -1200 200 -tr 100 -oo X_POSSIBLE_NAMES=field_1 \
  -oo Y_POSSIBLE_NAMES=field_2 -zfield field_3 CSV:0.locations 0.tif
ERROR 1: Too few arguments
Usage: gdal_grid [--hel...
```
Since it knows what argument it stopped parsing at, it could easily instead say:
> ERROR 1: -tr: Too few arguments

or at least
> -tr: Too few arguments
> ERROR 1: Too few arguments

The user will then be able to find the problem up to 10 times faster in this case, depending on which argument they began examining. GDAL 3.9.

**Comment by jratike80** [comment]
With GDAL 3.9.0 I get this:

```
gdal_grid -l 0 -a nearest -txe -1200 200 -tye -1200 200 -tr 100 -oo X_POSSIBLE_NAMES=field_1   -oo Y_POSSIBLE_NAMES=field_2 -zfield field_3 CSV:0.locations 0.tif
ERROR 5: Wrong value for -tr parameters.
```

**Comment by jidanni** [comment]
Well then you are lucky.
```
$ gdal_grid -l 0 -a nearest -txe -1200 200 -tye -1200 200 \                                                       
-tr 100 -oo X_POSSIBLE_NAMES=field_1 -oo Y_POSSIBLE_NAMES=field_2 \                                               
-zfield field_3 CSV:0.locations 0.tif
ERROR 1: Too few arguments
Usage: gdal_grid [--help] [--long-usage] [--help-general]
$ gdal_grid --version
GDAL 3.9.0, released 2024/05/07
```

**Comment by jratike80** [comment]
Could you share the source CSV so we can test with the same file?
And IMHO it would be better to keep the command on a single line. Yes, it is more readable with linebreaks that it meand that the command does not work with copy-paste on Windows.

**Comment by jidanni** [comment]
```
$ mkdir /tmp/x
$ cd /tmp/x
$ gdal_grid -l 0 -a nearest -txe -1200 200 -tye -1200 200 -tr 100 -oo X_POSSIBLE_NAMES=field_1 -oo Y_POSSIBLE_NAMES=field_2 -zfield field_3 CSV:0.locations 0.tif
ERROR 1: Too few arguments
Usage: gdal_grid [--help] ...
```

**Comment by jratike80** [comment]
Ok, I get the same error than you with GDAL 3.10.0dev-5dfa73a9c8, released 2024/04/27 (OSGeo4W).
Version GDAL 3.9.0dev-466915e012, released 2024/04/15 (gisinternals.com) prints "ERROR 5: Wrong value for -tr parameters."

Must be a side effect of starting the use an argument parser library.

**Comment by jidanni** [comment]
```
$ gdal_grid 0.csv 0.tif -l 0 -txe -1200 200 -tye -1200 200 -tr 100 -zfield field_3 2>&1 | head -n 1
ERROR 1: Too few arguments
$ gdal_grid 0.csv 0.tif -l 0 -txe -1200 200 -tye -1200 200 -tr 100 2>&1 | head -n 1
ERROR 1: Too few arguments for '-tr'.
```
