### ISSUE TITLE
gdal1.8.1+vs2010 x86 32bits build error

### ISSUE THREAD

**Issue by mercury20160104** [OSGeo/gdal#10041]
### What is the bug?

 正在创建库 gdal_translate.lib 和对象 gdal_translate.exp
gdal_translate.obj : error LNK2019: 无法解析的外部符号 _GDALAllRegister@0，该符号在函数 "int __cdecl ProxyMain(int,char * *)" (?ProxyMain@@YAHHPAPAD@Z) 中被引用
gdal_translate.exe : fatal error LNK1120: 1 个无法解析的外部命令
NMAKE : fatal error U1077: “"c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN\cl.EXE"”: 返回代码“0x2”
Stop.
NMAKE : fatal error U1077: “"c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN\nmake.EXE"”: 返回代码“0x2”
Stop.

### Steps to reproduce the issue

1.install visual studio 2010 prefession
2.nmake /f makefile.vc MSVC_VER=1600
3.building failed

### Versions and provenance

...

### Additional context

...

**Comment by rouault** [comment]
We no longer support GDAL 1.8 since ... more than 10 years maybe. Please update to the latest version
