### ISSUE TITLE
Make the download procedure less retarded

### ISSUE THREAD

**Issue by jdcjnsddfd** [OSGeo/gdal#10043]
### Feature description

Conda install doesn't work
Can't find the wheel anywhere
pip install doesn't work
errors for literally everything not being found

Shit is so tiring just create something that is simple and easy to use. Every time I decide to get back into GIS I want to jump out the window, develop something that is less shit for the user please

**Comment by rouault** [comment]
Insults are not accepted here. Any further message with such tone will result in blocking you. Closing you
