### ISSUE TITLE
ESRIJSON: export to PostGIS fails with esriFieldTypeDate 

### ISSUE THREAD

**Issue by jratike80** [OSGeo/gdal#10049]
### What is the bug?

See https://gis.stackexchange.com/questions/481910/gdal-ogr2ogr-esrijson-to-pg-date-formatting

One feature can be fetched from the referenced service with:
https://services6.arcgis.com/eMd5K6XXEvJETxfQ/arcgis/rest/services/prd_whc_sites_dossiers_elements_view/FeatureServer/1/query?where=element_state+%3D+%27United+Kingdom+of+Great+Britain+and+Northern+Ireland%27&outFields=EditDate&resultRecordCount=1&f=pjson

Also attached as zipped.
[esrijsondate.zip](https://github.com/OSGeo/gdal/files/15474726/esrijsondate.zip)

The json file contains timestamp data. The field is defined this way:
```
"fields" : [
    {
      "name" : "EditDate", 
      "type" : "esriFieldTypeDate", 
      "alias" : "EditDate", 
      "sqlType" : "sqlTypeOther", 
      "length" : 8, 
      "domain" : null, 
      "defaultValue" : null
    }, 
```
In the JSON data the field looks like
`  "EditDate" : 1714213354016`
ogrinfo shows this field as
` EditDate (DateTime) = 2024/04/27 10:22:34.016+00`

The issue is that ogr2ogr into PostGIS fails with an error:
`ERROR:  invalid input syntax for type timestamp with time zone: "2024/04/"`

Conversion can be done by going through GeoJSON. GDAL writes the ESRI DateTime into GeoJSON as
`EditDate": "2024-04-27T10:22:34.016Z"`
This GeoJSON file can be exported into PostGIS without errors.

A workaround of asking the ESRI REST server to send GeoJSON instead of ESRI JSON does not work, because timestamp is still encoded as Unix date and the GDAL GeoJSON driver does not understand that
`"properties":{"EditDate":1714213354016`

### Steps to reproduce the issue

Try to save the test data into PostGIS

`ogr2ogr PG:"host=localhost port=5432 dbname=db user=user password=pw" esrijsondate.json -nln esrijson -overwrite --debug on`

### Versions and provenance

GDAL 3.10.0dev (OSGeo4W) on Windows, PostGIS 3.4.1

**Comment by rouault** [comment]
Fixed per d9e48f9e862bc60ed6c1392a5e3528ffa3445c3d (master) and f03f4bb481642bfb3f8636eeb54a7afec52e52a1 (3.9)
