### ISSUE TITLE
Revise: "For the full list see Programs and note the ones that end in .py." 

### ISSUE THREAD

**Issue by jidanni** [OSGeo/gdal#10054]
### Feature description

https://gdal.org/user/gdal_python_utilities.html says

> Commonly used utilities include:
> 
> gdal_merge
> 
> gdal_edit
> 
> gdal_calc
> 
> ogrmerge
>
> For the full list see Programs and note the ones that end in .py.

But that final line is no longer valid, and needs to be replaced by e.g.,

>For the current list, use gdadinfo --utilities

which could run
```
$ (cd /usr/lib/python*/dist-packages/osgeo_utils/ && ls *.py)
__init__.py    gdal_edit.py        gdal_polygonize.py  gdalattachpct.py      ogrmerge.py
gdal2tiles.py  gdal_fillnodata.py  gdal_proximity.py   gdalcompare.py        pct2rgb.py
gdal2xyz.py    gdal_merge.py       gdal_retile.py      gdalmove.py           rgb2pct.py
gdal_calc.py   gdal_pansharpen.py  gdal_sieve.py       ogr_layer_algebra.py
```

In fact maybe just say "look in ... directory". No need to add new --functions.

**Comment by rouault** [comment]
I've just dropped the note
