### ISSUE TITLE
build_driver_summary.py not syncing properly

### ISSUE THREAD

**Issue by jidanni** [OSGeo/gdal#10057]
### Feature description

https://github.com/OSGeo/gdal/blob/master/doc/source/build_driver_summary.py
is somehow not syncing properly.

E.g.,
https://gdal.org/drivers/raster/index.html says
> XYZ ASCII Gridded XYZ No Yes Yes

But according to `gdalinfo --formats`, it should be
> XYZ ASCII Gridded XYZ **Yes** Yes Yes

**Comment by rouault** [comment]
The information is accurate. "Creation" means the Create() call. "Copy" means CreateCopy()

**Comment by rouault** [comment]
Footpage note added to explain the difference
