### ISSUE TITLE
GDAL_HTTP_RETRY_CODES dosn't work?

### ISSUE THREAD

**Issue by trufanov-nok** [OSGeo/gdal#10051]
### What is the bug?

I'm trying to force `gdal_translate` to do 50 attempts to download the given URL that returns 403 error. With use of `GDAL_HTTP_MAX_RETRY` and `GDAL_HTTP_RETRY_CODES`. But it does only one attmpt to get URL

### Steps to reproduce the issue

Execute:
```
gdal_translate --debug on --config GDAL_HTTP_COOKIEFILE /tmp/t --config GDAL_HTTP_COOKIEFILE /tmp/t  --config GDAL_HTTP_COOKIEJAR /tmp/t --config GDAL_DISABLE_READDIR_ON_OPEN ON --config CPL_VSIL_CURL_ALLOWED_EXTENSIONS TIF --config GDAL_HTTP_MAX_RETRY 50 --config GDAL_HTTP_RETRY_CODES ALL --config GDAL_HTTP_UNSAFESSL YES "https://d1nklfio7vscoe.cloudfront.net/head-2d2df3a34830d5223d1e9547cd713408/lp-prod-protected.s3.us-west-2.amazonaws.com/HLSS30.020/HLS.S30.T39UWA.2018020T080231.v2.0/HLS.S30.T39UWA.2018020T080231.v2.0.B04.tif"  /tmp/output.tif
```

The output is:
```
HTTP: Fetch(https://d1nklfio7vscoe.cloudfront.net/head-2d2df3a34830d5223d1e9547cd713408/lp-prod-protected.s3.us-west-2.amazonaws.com/HLSS30.020/HLS.S30.T39UWA.2018020T080231.v2.0/HLS.S30.T39UWA.2018020T080231.v2.0.B04.tif)
HTTP: libcurl/8.5.0 OpenSSL/3.0.13 zlib/1.3 brotli/1.1.0 zstd/1.5.5 libidn2/2.3.7 libpsl/0.21.2 (+libidn2/2.3.7) libssh/0.10.6/openssl/zlib nghttp2/1.59.0 librtmp/2.3 OpenLDAP/2.6.7
ERROR 1: HTTP error code : 403
```

Only one attempt to get file is made althogh `GDAL_HTTP_RETRY_CODES ALL `  is passed.

### Versions and provenance

$ gdalinfo --version
GDAL 3.8.4, released 2024/02/08

$ curl --version
curl 8.5.0 (x86_64-pc-linux-gnu) libcurl/8.5.0 OpenSSL/3.0.13 zlib/1.3 brotli/1.1.0 zstd/1.5.5 libidn2/2.3.7 libpsl/0.21.2 (+libidn2/2.3.7) libssh/0.10.6/openssl/zlib nghttp2/1.59.0 librtmp/2.3 OpenLDAP/2.6.7
Release-Date: 2023-12-06, security patched: 8.5.0-2ubuntu10.1
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM PSL SPNEGO SSL threadsafe TLS-SRP UnixSockets zstd

Operating System: Kubuntu 24.04
KDE Plasma Version: 5.27.11
KDE Frameworks Version: 5.115.0
Qt Version: 5.15.13
Kernel Version: 6.8.0-31-generic (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-3632QM CPU @ 2.20GHz
Memory: 15.5 ГиБ of RAM
Graphics Processor: Mesa Intel® HD Graphics 4000
Manufacturer: LENOVO
Product Name: Lenovo G780
System Version: Lenovo G780

**Comment by rouault** [comment]
https://gdal.org/user/configoptions.html#config-GDAL_HTTP_RETRY_CODES mentions "GDAL >= 3.10" (which is the development version, to be released in November 2024)
