### ISSUE TITLE
ESRI FileGDB Driver 3.9.0-1 errors

### ISSUE THREAD

**Issue by amgiss** [OSGeo/gdal#10071]
### What is the bug?

FileGDB Driver 3.9.0-1 throws "Failed at creating table for layer \layer name" and "Terminating translation prematurely" errors when converting from GPKG to File GDB. Multiple GPKG that would previously convert without errors using 3.8.5-1 will now throw errors and cannot be converted to FileGDB using the 3.9.0-1 driver.

### Steps to reproduce the issue

Upgrade File GDB driver from 3.8.5-1 to 3.9.0-1 under OSGeo4W.

### Versions and provenance

Windows 10
GDAL 3.9.0, released 2024/05/07
OSGeo4W

**Comment by jratike80** [comment]
Could you prepare some small GeoPackage that can be used for re-producing the error?

**Comment by amgiss** [comment]
This GPKG will fail with "Failed at creating table for layer \layer_styles" error even though there are no styles in it.

[Test.zip](https://github.com/user-attachments/files/15506800/Test.zip)
