### ISSUE TITLE
Misleading error message when using expired credentials to open a /vsis3 file

### ISSUE THREAD

**Issue by sgillies** [OSGeo/gdal#1007]
If I use expired credentials (access_key, secret_key, token) and try to open a /vsis3 file, I get the following GDAL error message: `A filesystem error with code 5 occurred`. It looks like this is because we fall through all the cases to the default at https://github.com/OSGeo/gdal/blob/d5f6bb89b0e0db0a06489419050d432e8f58ff47/gdal/port/cpl_vsi_error.cpp#L305.

Now, I've looked in the verbose curl output and AWS doesn't give us much to go on here, just a "400" error message and no details. But I think `400 Bad Request: GET /rasterio/shade.tif HTTP/1.1, Host: mapbox.s3.amazonaws.com` would be more useful than `A filesystem error with code 5 occurred`.

Is the lack of details from the AWS XML error documents due to lack of support in GDAL for chunked transfer encoding @rouault ?

**Comment by rouault** [comment]
I've pushed 340ad0d that should at least avoid the generic 'A filesystem error with code 5 occurred' since 5 == VSIE_AWSError

> Is the lack of details from the AWS XML error documents due to lack of support in GDAL for chunked transfer encoding @rouault ?

Hum, why do you mention the 'lack of support in GDAL for chunked transfer encoding' ? I'd thought that CURL would handle that transparently on the GET side.

**Comment by sgillies** [comment]
Great! This should help a lot!

I have a vague memory of seeing XML in the body of these 400 bad request responses before I was speculating that a change of transfer encoding might have thrown the software off. But if all of this is being handled by curl, then that's where any issue would be.

**Comment by sgillies** [comment]
@rouault I'm going to close this one because 340ad0d gives me everything I need. Thanks!

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/sean/code/rasterio/rasterio/env.py", line 402, in wrapper
    return f(*args, **kwds)
  File "/Users/sean/code/rasterio/rasterio/__init__.py", line 217, in open
    s = DatasetReader(path, driver=driver, **kwargs)
  File "rasterio/_base.pyx", line 199, in rasterio._base.DatasetBase.__init__
    self._hds = open_dataset(filename, flags, driver, kwargs, None)
  File "rasterio/_shim.pyx", line 64, in rasterio._shim.open_dataset
    return exc_wrap_pointer(hds)
  File "rasterio/_err.pyx", line 188, in rasterio._err.exc_wrap_pointer
    raise exc
rasterio._err.CPLE_BaseError: The provided token has expired.
```
