### ISSUE TITLE
GDALRPCTransform unable to obtain accurate latitude and longitude coordinates

### ISSUE THREAD

**Issue by hello-willy** [OSGeo/gdal#10083]
### What is the bug?

my code as follow:
```
char** papszRPC = this->mGDALDataset->GetMetadata("RPC");
GDALRPCInfo oInfo;
GDALExtractRPCInfo(papszRPC, &oInfo);
void* transform = GDALCreateRPCTransformer(&oInfo, FALSE, 0, 0);

double px[] = { 114 };
double py[] = { 34 };
int success[] = { FALSE };
GDALRPCTransform(transform, TRUE, 1, px, py, 0, success);
```
the RPC model data as follow:
![image](https://github.com/OSGeo/gdal/assets/9379589/0eab9b91-67d2-4116-be21-f96849cab38c)

but, GDALRPCTransform return px=-48788.794198743861 and py=57731.972798211769, success is TRUE
i think the px and py is not latitude and longitude, why? may i take a mistake? plz help me, thank you.

### Steps to reproduce the issue

as above.

### Versions and provenance

gdal3.7.1

**Comment by rouault** [comment]
> GDALRPCTransform(transform, TRUE, 1, px, py, 0, success);

you likely need to change the bDstToSrc=TRUE to bDstToSrc=FALSE. The forward direction of the RPC transformer (for GDALRPCTransform, and when created as you did with GDALCreateRPCTransformer(  , bReversed, = FALSE,  )    ) is from pixel/line to long/lat

**Comment by hello-willy** [comment]
> > GDALRPCTransform(transform, TRUE, 1, px, py, 0, success);
> 
> you likely need to change the bDstToSrc=TRUE to bDstToSrc=FALSE. The forward direction of the RPC transformer (for GDALRPCTransform, and when created as you did with GDALCreateRPCTransformer( , bReversed, = FALSE, ) ) is from pixel/line to long/lat

![image](https://github.com/OSGeo/gdal/assets/9379589/966d2de2-b72f-4e52-adaf-0aeb1ca141bb)

**Comment by rouault** [comment]
> but, GDALRPCTransform return px=-48788.794198743861 and py=57731.972798211769, success is TRUE

actually I was confused. What you initially asked is to transform longitude=114 and latitude=34 to pixel/line . Given the value of the RPC metadata, column=-48788.794198743861 and line=57731.972798211769 are plausible values. If you try as input the value of dfLONG_OFF, dfLAT_OFF, you should get as output dfSAMP_OFF, dfLINE_OFF

**Comment by hello-willy** [comment]
> > but, GDALRPCTransform return px=-48788.794198743861 and py=57731.972798211769, success is TRUE
> 
> actually I was confused. What you initially asked is to transform longitude=114 and latitude=34 to pixel/line . Given the value of the RPC metadata, column=-48788.794198743861 and line=57731.972798211769 are plausible values. If you try as input the value of dfLONG_OFF, dfLAT_OFF, you should get as output dfSAMP_OFF, dfLINE_OFF

emm, sorry about it, px=114, py=34 is pixel/line, i want to transoform to lat/long, but i can't get the accurate lat and long.

**Comment by hello-willy** [comment]
> > > but, GDALRPCTransform return px=-48788.794198743861 and py=57731.972798211769, success is TRUE
> > 
> > 
> > actually I was confused. What you initially asked is to transform longitude=114 and latitude=34 to pixel/line . Given the value of the RPC metadata, column=-48788.794198743861 and line=57731.972798211769 are plausible values. If you try as input the value of dfLONG_OFF, dfLAT_OFF, you should get as output dfSAMP_OFF, dfLINE_OFF
> 
> emm, sorry about it, px=114, py=34 is pixel/line, i want to transoform to lat/long, but i can't get the accurate lat and long.

or plz help me， how can I do it correctly, thank you

**Comment by hello-willy** [comment]
> > but, GDALRPCTransform return px=-48788.794198743861 and py=57731.972798211769, success is TRUE
> 
> actually I was confused. What you initially asked is to transform longitude=114 and latitude=34 to pixel/line . Given the value of the RPC metadata, column=-48788.794198743861 and line=57731.972798211769 are plausible values. If you try as input the value of dfLONG_OFF, dfLAT_OFF, you should get as output dfSAMP_OFF, dfLINE_OFF

it worked! the input of padfZ must not be null and bDstToSrc must be FALSE. thank you very mush.

if bReserved=FALSE, it means the normal pixel/line to lat/long, but bDstToSrc must be FALSE, it confused me. anyway it worked, thank you!!!
