### ISSUE TITLE
org2ogr ESRIJSON Feature Paging

### ISSUE THREAD

**Issue by trodaway** [OSGeo/gdal#10094]
### What is the bug?

'm trying to load some data from an Esri Feature Server URL into PostGIS, using ogr2ogr, but it doesn't seem to do any feature paging despite the open option being set to enable it (`-oo FEATURE_SERVER_PAGING=YES`). It's only loading up to the `maxRecordCount`. I've checked multiple datasets and this isn't isolated to a single layer or organisation (it would however appear they're all using ArcGIS Online opposed to ArcGIS Enterprise, given the URLs, in case that's important)

### Steps to reproduce the issue

The below code should in theory load all the Statutory Main Rivers from the UK's Environment Agency into PostgreSQL.

```
ogr2ogr -f PostgreSQL PG:"[connection string]" ESRIJSON:"https://services1.arcgis.com/JZM7qJpmv7vJ0Hzx/arcgis/rest/services/Statutory_Main_River_Map/FeatureServer/0/query?where=1%3D1&outFields=*&f=pjson" -oo FEATURE_SERVER_PAGING=YES -nlt MULTILINESTRING -nln test_stat_rivers
```

It however only loads up to its  `maxRecordCount` (4,000 records) despite having `supportsPagination` set to true.

### Versions and provenance

Tested on both `GDAL 3.9.0, released 2024/05/07` and `GDAL 3.8.4, released 2024/02/08`. 
Both coming from OSGeo4W.
Running Windows 10 Enterprise.

### Additional context

Also posted on https://gis.stackexchange.com/questions/482023/gdal-org2ogr-esrijson-feature-paging however would appear to be a bug.

**Comment by jratike80** [comment]
Test case with geopackage. I think that even `-oo FEATURE_SERVER_PAGING=YES` is unnecessary.

`ogr2ogr -f gpkg esrijson.gpkg ESRIJSON:"https://services1.arcgis.com/JZM7qJpmv7vJ0Hzx/arcgis/rest/services/Statutory_Main_River_Map/FeatureServer/0/query?where=1%3D1&outFields=*&f=pjson" -nlt MULTILINESTRING -nln test_stat_rivers`

I do not know how it can be confirmed from the API that the server supports paging.

**Comment by rouault** [comment]
I'm on it. The workaround is to replace ``f=pjson`` with ``f=json``

**Comment by trodaway** [comment]
> I'm on it. The workaround is to replace `f=pjson` with `f=json`

Thanks for fixing so quickly - yes, that workaround does the job fantastically!
