### ISSUE TITLE
Clarify gdal_create -burn

### ISSUE THREAD

**Issue by jidanni** [OSGeo/gdal#10090]
### Feature description

Today I started to edit `gdal_create`, confident I could improve this sentence:

>       -burn <value>
>              A fixed value to burn into a band for all  objects.   A  list  of
>              -burn options can be supplied, one per band being written to.

But after 40 minites I still got nowhere.

Please clarify if

> -burn 2 5 6

will put 2 into band 1, 5 into band 2, and 6 into band 3.

Or if one should use
> -burn 2 -burn 5 -burn 6

to accomplish that, or perhaps both are OK.

Also I notice neither produce errors.

And mention how one might only put a value in band 2, not touching band 1.

**Comment by jratike80** [comment]
The actual behavior is against the documentation. As a very experienced reader of GDAL utility manuals and man context help I am surprised that you did not discover that `-burn 2 3 4` should not work.

```
gdal_create --help
...
  [-burn <value>]...
```

So, single value after -burn, the whole section can be repeated. But gdal_create seems to accept also `-burn 100 200 250` and act in the same way than with `-burn 100 -burn 200 -burn 250`. But when the utility is used in the documentated way with repeated -burn parameters the result is correct so no real problem for users.

But this sentense, copy-pasted from https://gdal.org/programs/gdal_rasterize.html, does not make sense in this context:

> A fixed value to burn into a band for all objects.

I think I would understand right "A fixed value to burn into all bands".

> And mention how one might only put a value in band 2, not touching band 1.

Not possible. The intention is that a full list of burn values for all the bands is provided. How would you clarify "A list of [-burn] options can be supplied, one per band being written to"?

**Comment by jratike80** [comment]
Hey, this is `gdal_create`. Objects and Z values do not have any role.

**Comment by rouault** [comment]
> Hey, this is `gdal_create`. Objects and Z values do not have any role.

ah, ok, I thought this was about gdal_rasterize. So the option description has been copied from there
