### ISSUE TITLE
Can't visualize netcdf-file

### ISSUE THREAD

**Issue by rawedler** [OSGeo/gdal#1012]
Dear all,

the instruction below runs very fine and the output netcdf-file just as well. But when I try to visualize the result for example with QGIS, QGIS stops directly and close the application. Where is the problem? Have anybody an idea? The input-file and the output-file are attached.

[sat_gs_de_tw_20181011.nc.gz](https://github.com/OSGeo/gdal/files/2479096/sat_gs_de_tw_20181011.nc.gz)
[sat_gs_de_tw_gauss_20181011.nc.gz](https://github.com/OSGeo/gdal/files/2479098/sat_gs_de_tw_gauss_20181011.nc.gz)

gdalwarp -of netCDF -s_srs '+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs' -t_srs '+proj=tmerc +lat_0=0 +lon_0=9 +k=1 +x_0=3500000 +y_0=0 +ellps=bessel +datm=potsdam +units=m +no_defs' -te 3280415 5236500 3934415 6102500 -tr 1000 1000 -overwrite -dstnodata -9999 sat_gs_de_tw_20181011.nc  sat_gs_de_tw_gauss_20181011.nc

**Comment by rouault** [comment]
sat_gs_de_tw_gauss_20181011.nc displays just fine for me with QGIS 2.8 or QGIS master against GDAL master
Works fine too with QGIS 2.8 against GDAL 1.11.3

Tested on Ubuntu 16.04
So I suspect this might have something to do with the particular binary build you are using

**Comment by rawedler** [comment]
I used ncview and the result is fine. I will try it with QGIS master in the next days.
