### ISSUE TITLE
LIBKML Hangs on closing

### ISSUE THREAD

**Issue by jeff-bradley** [OSGeo/gdal#10138]
### What is the bug?

ogr2ogr just hangs when using libkml it works fine for just kml 

### Steps to reproduce the issue

**run command** 
`ogr2ogr -f "LIBKML" output.kml cities.TAB --debug ON -progress`

**Output from DEBUG**
_GDAL: Auto register C:\Program Files\GDAL\gdalplugins\gdal_BAG.dll using GDALRegister_BAG.
GDAL: Auto register C:\Program Files\GDAL\gdalplugins\gdal_FITS.dll using GDALRegister_FITS.
GDAL: Auto register C:\Program Files\GDAL\gdalplugins\gdal_GMT.dll using GDALRegister_GMT.
GDAL: Auto register C:\Program Files\GDAL\gdalplugins\gdal_HDF4.dll using GDALRegister_HDF4.
GDAL: Auto register C:\Program Files\GDAL\gdalplugins\gdal_HDF4Image.dll using GDALRegister_HDF4Image.
GDAL: Auto register C:\Program Files\GDAL\gdalplugins\gdal_HDF5.dll using GDALRegister_HDF5.
GDAL: Auto register C:\Program Files\GDAL\gdalplugins\gdal_HDF5Image.dll using GDALRegister_HDF5Image.
GDAL: Auto register C:\Program Files\GDAL\gdalplugins\gdal_KEA.dll using GDALRegister_KEA.
GDAL: Auto register C:\Program Files\GDAL\gdalplugins\gdal_netCDF.dll using GDALRegister_netCDF.
OGR: Restored 5 field indexes for layer cities from --unknown-- on cities.IND.
GDAL: GDALOpen(cities.TAB, this=0000020AE13695B0) succeeds as MapInfo File.
GDAL: GDALDriver::Create(LIBKML,output.kml,0,0,0,Unknown,0000000000000000)
LIBKML: Attempt to create: output.kml
0...10...20...30...40...50...60...70...80...90...100 - done.
GDALVectorTranslate: 40956 features written in layer 'cities'
GDAL: GDALClose(cities.TAB, this=0000020AE13695B0)_

The KML never seems to close and is not written, the command line just pauses. If I hit ctrl c then I get this line
_GDAL: Force close of output.kml (0000020AE1371330) in GDALDriverManager cleanup._

Setting the LIBKML_USE_SIMPLEFIELD=NO seems to work and have the command complete and save the file

### Versions and provenance

Windows 11 and tried on Ubuntu 20 WSL
GDAL 3.4.3  on Windows and Linux WSL same issue

**Comment by rouault** [comment]
Please attach the input dataset

**Comment by jeff-bradley** [comment]
[cities.zip](https://github.com/user-attachments/files/15596085/cities.zip)

**Comment by jratike80** [comment]
I can reproduce with GDAL 

```
LIBKML: Attempt to create: output.kml
0...10...20...30...40...50...60...70...80...90...100 - done.
GDALVectorTranslate: 40956 features written in layer 'cities'
```
GDAL stops here, Ctrl-C prints two more lines:
```
GDAL: In GDALDestroy - unloading GDAL shared library.
GDAL: Force close of output.kml (0000024A04CBA0C0) in GDALDriverManager cleanup.
```
GDAL stops then here and I had to kill the process. The process used 15% of CPU all the time.

**Comment by jeff-bradley** [comment]
I have only tested with the docker releases of ubuntu:latest, alpine-small-latest and alpine-normal-3.9.0 but still cant get the process to complete.

**Comment by rouault** [comment]
> I have only tested with the docker releases of ubuntu:latest, alpine-small-latest and alpine-normal-3.9.0 but still cant get the process to complete.

none of them have been refreshed yet with the fix
