### ISSUE TITLE
gdal-2.3.2 crashes with ECW 3.3 sdk

### ISSUE THREAD

**Issue by AvzPeter** [OSGeo/gdal#1013]
## Expected behavior and actual behavior.
I built the gdal-2.3.2 linking against the ECW SDK 3.3 on PC platform. I expected to write ECW files using 'gdal_translate.exe', but I got a crash at the end of the writing process. 

## Steps to reproduce the problem.
(1) build gdal-2.3.2 from source code and make gdal to link against ECW 3.3 libs for ECW format
(2) try to translate a tiff to a ecw file by running command 'gdal_translate.exe -of ECW hills.tif hills.ecw'
(3) gdal crashes at the end of the writing process.
(4) the visual studio debugger shows that the crash happens in the function  'GDALECWCompressor::CloseDown()' due to memory currption in gdal

## Operating system

Windows 10 Pro, 64 bit

## GDAL version and provenance

gdal 2.3.2 source code

**Comment by rouault** [comment]
Perhaps an issue with your build ? The ECW SDK 3.3 is under deep rotting...
Anyway you might try one of the builds at http://gisinternals.com/stable.php . They offer the ECW SDK 3.3 plugin as an option

**Comment by rouault** [comment]
No feedback. Closing
