### ISSUE TITLE
Support metadata creation with FlatGeobuf driver

### ISSUE THREAD

**Issue by StefanBrand** [OSGeo/gdal#10183]
### Feature description

I would like to use the `-mo` switch to write the [`metadata`](https://github.com/flatgeobuf/flatgeobuf/blob/ee7c8f5f45c67dd4a84a51fef518dfebc3e19d0a/src/fbs/header.fbs#L55) property of a FlatGeobuf Header.

### Additional context

I'm currently working on a FlatGeobuf endcoding for fiboa (Field Boundaries for Agriculture) and would like to embed the fiboa specification into the Header section of the FlatGeobuf file. See https://github.com/fiboa/specification/issues/24 for further information.

**Comment by rouault** [comment]
This has been added in GDAL 3.9:
```
$ ogr2ogr -mo FOO=BAR test.fgb autotest/ogr/data/poly.shp
$ ogrinfo test.fgb -al -so | grep FOO
  FOO=BAR
```

**Comment by StefanBrand** [comment]
Sory, my bad, I have GDAL 3.5.3.
