### ISSUE TITLE
Link to Spack installation docs is broken

### ISSUE THREAD

**Issue by codeananda** [OSGeo/gdal#10189]
### What is the bug?

In `doc/source/download.rst` the link to Spack docs if followed leads to a 404 error.

https://spack.readthedocs.io/en/latest/package_list.html#gdal

I've tried searching spack readthedocs manually but couldn't find any reference to gdal. 

Plus, this is probably unrelated, but I just tried to install gdal using spack on AWS Linux EC2 (with arm architecture). It seemed to work from the logs but hasn't made `gdal` or `gdal-config` available as commands. Is there something else I need to do?

### Steps to reproduce the issue

Read the docs

### Versions and provenance

.

**Comment by jratike80** [comment]
The link seems to be https://packages.spack.io/package.html?name=gdal

**Comment by rouault** [comment]
> Plus, this is probably unrelated, but I just tried to install gdal using spack on AWS Linux EC2 (with arm architecture). It seemed to work from the logs but hasn't made `gdal` or `gdal-config` available as commands. Is there something else I need to do?

perhaps @adamjstewart can provide some hints

**Comment by adamjstewart** [comment]
Yes, sorry about that. We moved the package documentation because we had too many packages. That new link is correct, thanks for the fix!

**Comment by codeananda** [comment]
> Plus, this is probably unrelated, but I just tried to install gdal using spack on AWS Linux EC2 (with arm architecture). It seemed to work from the logs but hasn't made gdal or gdal-config available as commands. Is there something else I need to do?

@adamjstewart any idea about this?

**Comment by jratike80** [comment]
> but hasn't made gdal or gdal-config available as commands.

There is no command "gdal" but gdal-config seems to exist for Linux https://gdal.org/programs/gdal-config.html.

For testing if you have gdal use  `gdalinfo --version`.

**Comment by adamjstewart** [comment]
You need to use `spack load gdal` to add it to your `PATH`.

**Comment by codeananda** [comment]
> You need to use spack load gdal to add it to your PATH.

Ahh ok. This would be good to add to the [spack install steps](https://github.com/OSGeo/gdal/blob/5481008668c818303c2b429b53860a2d787c189b/doc/source/download.rst?plain=1#L416-L418)

> For testing if you have gdal use gdalinfo --version.

Also would be helpful to add somewhere

**Comment by jratike80** [comment]
> Also would be helpful to add somewhere

https://gdal.org/programs/index.html
https://gdal.org/programs/raster_common_options.html#raster-common-options
