### ISSUE TITLE
ogr2ogr segfaults in 3.9.0 but not 3.8.5 (GeoPackage/GeoParquet to PMTiles)

### ISSUE THREAD

**Issue by cboettig** [OSGeo/gdal#10199]
### What is the bug?

The following example works fine in GDAL 3.8.5 (on Ubuntu 22.04) but segfaults in gdal 3.9.0:

```
ogr2ogr out.pmtiles /vsicurl/https://huggingface.co/datasets/boettiger-lab/pad-us-3/resolve/main/pad-stats.parquet
```

throws:

```
Segmentation fault (core dumped)
```

This error doesn't occur on all ogr2ogr conversions or all pmtiles creation, but does on this example. apologies I'm not able to debug further.  

### Steps to reproduce the issue

```
ogr2ogr out.pmtiles /vsicurl/https://huggingface.co/datasets/boettiger-lab/pad-us-3/resolve/main/pad-stats.parquet
```

### Versions and provenance

GDAL 3.9.0, released 2024/05/07

**Comment by rouault** [comment]
Fix committed. A workaround is to add ``--config OGR2OGR_USE_ARROW_API=NO`` to the ogr2ogr command line

**Comment by cboettig** [comment]
wow, thanks for both the workaround and the rapid fix. lovely!
