### ISSUE TITLE
ReadAsArray() ends with SIGSEGV

### ISSUE THREAD

**Issue by digital-idiot** [OSGeo/gdal#1020]
## Expected behavior and actual behavior.

I expected to be able to read a **TIFF** into a <`numpy.ndarray`> using the usual gdal function `ReadAsArray()`. But it exits with **`exit code 139 (interrupted by signal 11: SIGSEGV)`**. I tried with different tiff file, also tried the same with `python2` and ended up with the same exit code in all the cases. Stack Exchange post about same issue in the Mac OS: [Stack Exchange Post](https://gis.stackexchange.com/questions/234744/exit-code-139-while-using-readasarray-in-os-x)

## Steps to reproduce the problem.
Below is the code to reproduce the problem

```
import numpy as np
import gdal
band1 = gdal.Open("liss3_poanta.tif").GetRasterBand(1)
b1 = band1.ReadAsArray() # This is where SIGSEGV occurs
```

## Operating system

Linux hell-fire 4.19.0-1-MANJARO SMP PREEMPT x86_64 GNU/Linux

## GDAL version and provenance

GDAL 2.3.2, released 2018/09/21, installed from community repository

**Comment by rouault** [comment]
You need to keep a reference to the dataset. So
```
ds = gdal.Open("liss3_poanta.tif")
band1 = ds.GetRasterBand(1)
b1 = band1.ReadAsArray() # This is where SIGSEGV occurs
```

See https://trac.osgeo.org/gdal/wiki/PythonGotchas
