### ISSUE TITLE
VSICURL Error: Range downloading not supported by this server

### ISSUE THREAD

**Issue by cxcandid** [OSGeo/gdal#10210]
### What is the bug?

I'm trying to fetch data from OpenStreetMap Nominatim service using VSICURL and I get several range downloading errors.
Is there any GDAL/VSICURL setting to prevent range downloads?

Interestingly, it works with OGR VRT:
```
ogrinfo "nominatim.ovf" nominatim
```

nominatim.ovf:
```xml
<OGRVRTDataSource>
    <OGRVRTLayer name="nominatim">
        <SrcDataSource>https://nominatim.openstreetmap.org/lookup?osm_ids=r2145268&amp;format=geojson&amp;polygon_geojson=1</SrcDataSource>
        <SrcLayer>OGRGeoJSON</SrcLayer>
    </OGRVRTLayer>
</OGRVRTDataSource>
```

### Steps to reproduce the issue

```
ogrinfo "/vsicurl/https://nominatim.openstreetmap.org/lookup?osm_ids=r2145268&format=geojson&polygon_geojson=1"

ERROR 1: Range downloading not supported by this server!
ERROR 1: Range downloading not supported by this server!
ogrinfo failed - unable to open '/vsicurl/https://nominatim.openstreetmap.org/lookup?osm_ids=r2145268&format=geojson&polygon_geojson=1'.
```

Another request, where the JSON response is small, works like expected:
```
ogrinfo "/vsicurl/https://nominatim.openstreetmap.org/lookup?osm_ids=r90685&format=geojson&polygon_geojson=1"

INFO: Open of `/vsicurl/https://nominatim.openstreetmap.org/lookup?osm_ids=r90685&format=geojson&polygon_geojson=1'
      using driver `GeoJSON' successful.
1: lookup?osm_ids=r90685&format=geojson&polygon_geojson=1 (Polygon) 
```

### Versions and provenance

GDAL 3.9.0 Windows 64

libcurl/8.6.0 OpenSSL/3.0.13 zlib/1.3.1 WinIDN

**Comment by rouault** [comment]
> Is there any GDAL/VSICURL setting to prevent range downloads?

no, using range downloads is the very principle of /vsicurl/
Here, you can use instead /vsicurl_streaming/ . Or just setting the URL, the later will fully download the file into memory
