### ISSUE TITLE
Unable to convert EPSG:3857 to XML

### ISSUE THREAD

**Issue by mmomtchev** [OSGeo/gdal#10216]
### What is the bug?

This used to work in 3.8 but now I get

```
ERROR 6: Unhandled projection method Mercator_1SP
```

### Steps to reproduce the issue

```cpp
#include <gdal.h>
#include <ogr_spatialref.h>

int main() {
  auto *srs = new OGRSpatialReference();
  srs->importFromEPSG(3857);
  char *xml;
  OGRErr err = srs->exportToXML(&xml);
  if (err != OGRERR_NONE) {
    printf("Error: %s\n", CPLGetLastErrorMsg());
    return 1;
  }
  printf("XML: %s\n", xml);
  return 0;
}
```

### Versions and provenance

GDAL 3.9.0, built from source on Linux, default options

**Comment by rouault** [comment]
> This used to work in 3.8 but now I get

not really... It also emitted that message, but just as a warning, but the output was erroneous, and could not be imported back. GDAL 3.9 just acknowledge that limitation

**Comment by mmomtchev** [comment]
Yes, indeed

**Comment by rouault** [comment]
out of curiosity, what's the use case for exporting EPSG:3857 to GML ?
AFAIK, the SRS GML exporter had been historically developed for the needs of GMLJP2, for custom CRS.
