### ISSUE TITLE
Importing NAS file results in empty or omitted "istBestandTeilVon" - Field

### ISSUE THREAD

**Issue by CreaTechJulius** [OSGeo/gdal#10212]
### What is the bug?

When importing a NAS file (german cadastre file type), the attribute "istBestandteilVon" is not appearing in the attribute table.

### Steps to reproduce the issue

import geopandas as gpd
PATH_ALKIS = *any nas .xml file*
buchungsstelle = gpd.read_file(PATH_ALKIS, layer='AX_Buchungsstelle')
print(buchungsstelle.istBestandteilVon)

---------------------------
GDAL 3.6.2 OUTPUT
0       DEBYvAAAAAB04m3E
1       DEBYvAAAAAAYaDhe
2       DEBYvAAAAAAYaDhi
3       DEBYvAAAAABdFYDI
4       DEBYvAAAAAAYaDcO
              ...
3792    DEBYvAAAAABHKCnm
3793    DEBYvAAAAABHKAZf
3794    DEBYvAAAAABHJ8Eq
3795    DEBYvAAAAABHJ8Eq
3796    DEBYvAAAAABHJ8Eq

---------------------------
GDAL >= 3.8 OUTPUT
0       None
1       None
2       None
3       None
4       None
        ...
3792    None
3793    None
3794    None
3795    None
3796    None

-----------------
When i open the nas file in qgis 3.22 (GDAL 3.6.2), the field is there, in greater versions of QGIS, the field is omitted completely.

### Versions and provenance

GDAL 3.8.4, released 2024/02/08

**Comment by rouault** [comment]
CC @jef-n

**Comment by jef-n** [comment]
You need to set `NAS_GFS_TEMPLATE` (since GDAL 3.7; see https://gdal.org/drivers/vector/nas.html)

**Comment by CreaTechJulius** [comment]
Thanks for the quick answer, but unfortunatly that didnt work for me. The attributes in "IstBestandTeilVon" field are still empty.

the xml looks like this:

```html
<istBestandteilVon xlink:href="urn:adv:oid: [some gml id]"/>
