### ISSUE TITLE
gdal_calc.py -A "C:\Users\VP\Desktop\ETOPO_2022_v1_60s_N90W180_bed.tif" --outfile="C:\Users\VP\Desktop\result.tif" --calc="A*logical_and(A>34)" worked once on my Gdal and now refuses too work again, how to fix? 

### ISSUE THREAD

**Issue by 1PecuTheGreat** [OSGeo/gdal#10221]
### What is the bug?

so I am trying to change the value on a TIFF using this code `gdal_calc.py -A "C:\Users\VP\Desktop\ETOPO_2022_v1_60s_N90W180_bed.tif" --outfile="C:\Users\VP\Desktop\result.tif" --calc="A*logical_and(A>34)" ` it worked once but after that it refused to work, no error message either it just moves to the next line like. How do I fix it?.

### Steps to reproduce the issue

gdal_calc.py -A "C:\Users\VP\Desktop\ETOPO_2022_v1_60s_N90W180_bed.tif" --outfile="C:\Users\VP\Desktop\result.tif" --calc="A*logical_and(A>34)" 

### Versions and provenance

Windows 10, GDAL 3.8.5, released 2024/04/02, from OSGeo4W.

**Comment by rouault** [comment]
> it worked once but after that it refused to work, no error message either it just moves to the next line like

I don't understand what you mean. Can you be more explicit about the action you tried after the one that worked?

**Comment by gregorywaynepower** [comment]
@rouault Here's some more information @1PecuTheGreat from [the following reddit post](https://www.reddit.com/r/QGIS/comments/1dg4mrz/how_to_write_a_gdal_code_to_changeclip_the/):

![how-to-write-a-gdal-code-to-change-clip-the-default-sea-v0-sbjeh93qon6d1](https://github.com/OSGeo/gdal/assets/31050507/444dc661-6dbc-4782-807e-9c9f1e6bd0cf)

It appears that their command was silently failing and that the [--debug](https://gdal.org/programs/gdal_calc.html#cmdoption-debug) flag wasn't providing much in the line of information. But they may just be missing the behavior that the resulting file [is being updated in place](https://gdal.org/programs/gdal_calc.html#cmdoption-overwrite).

**Comment by rouault** [comment]
Closing due to lack of feedback
