### ISSUE TITLE
'istBestandteilVon' field empty in NAS File (ALKIS)

### ISSUE THREAD

**Issue by CreaTechJulius** [OSGeo/gdal#10226]
### What is the bug?

As mentioned in #10212 , the attributes values in 'istBestandTeilVon' field are all empty. And since there is no alkis-beziehungen layer anymore, i cant join the layers on this field.

this should result in a feature with istBestandTeilVon = urn:adv:oid:DESNALK0F3000Pu8 but its an emty string.
```html
          <istBestandteilVon xlink:href="urn:adv:oid:DESNALK0F3000Pu8"/>
``` 
![Unbenannt](https://github.com/OSGeo/gdal/assets/135850499/7d789d3a-3490-463a-ad85-347e64ab9503)

### Steps to reproduce the issue

I downloaded an xml file from saxonian geodataportal (https://www.geodaten.sachsen.de/downloadbereich-alkis-4176.html) and tried opening it in qgis and geopandas.

### Versions and provenance

gdal 3.8.4

**Comment by jef-n** [comment]
Works for me after sett NAS_GFS_TEMPLATE (see #10212)

```
D:\…\144728.xml>ogrinfo --version
GDAL 3.9.0, released 2024/05/07
D:\…\144728.xml>set NAS_GFS_TEMPLATE=%OSGEO4W_ROOT%\apps\alkis-import-gid7\alkis-schema.gfs
D:\…\144728.xml>ogrinfo -limit 1 144728.xml AX_Buchungsstelle
INFO: Open of `144728.xml'
      using driver `NAS' successful.

Layer name: ax_buchungsstelle
Geometry: None
Feature Count: 50
Layer SRS WKT:
(unknown)
gml_id: String (16.0)
anlass: StringList (0.0)
…
istbestandteilvon: String (0.0)
…
OGRFeature(ax_buchungsstelle):1
  gml_id (String) = DESNALK0Fb003uVY
  beginnt (String) = 2014-02-08T22:55:43Z
  advstandardmodell (StringList) = (1:DLKM)
  buchungsart (Integer) = 1100
  laufendenummer (String) = 1
  istbestandteilvon (String) = DESNALK0Fb004LSB
D:\…\144728.xml>type pd.py
import fiona
fiona.drvsupport.supported_drivers['NAS'] = 'r'
import geopandas as gpd
buchungsstelle = gpd.read_file("144728.xml", layer='AX_Buchungsstelle')
print(buchungsstelle.istbestandteilvon)
D:\…\144728.xml>python3 pd.py
0     DESNALK0Fb004LSB
…
49    DESNALK0Fb004LJn
Name: istbestandteilvon, dtype: object
D:\…\144728.xml>qgis
```

![grafik](https://github.com/OSGeo/gdal/assets/238070/2c607a18-d129-4374-b6fb-e499dd2b5e77)

**Comment by CreaTechJulius** [comment]
Thanks so much!
