### ISSUE TITLE
gdal 3.9.0 build for android failed

### ISSUE THREAD

**Issue by lcf001** [OSGeo/gdal#10222]
### What is the bug?

This file contains any messages produced by compilers while
running configure, to aid debugging if configure makes a mistake.

It was created by sqlite configure 3.37.2, which was
generated by GNU Autoconf 2.69.  Invocation command line was

  $ ./configure --prefix=/tmp/install --host=aarch64-linux-android24

## --------- ##

hostname = lichunfeng-ubuntu
uname -m = aarch64
uname -r = 5.15.0-112-generic
uname -s = Linux
uname -v = #122-Ubuntu SMP Thu May 23 07:51:32 UTC 2024

/usr/bin/uname -p = aarch64
/bin/uname -X     = unknown

/bin/arch              = aarch64
/usr/bin/arch -k       = unknown
/usr/convex/getsysinfo = unknown
/usr/bin/hostinfo      = unknown
/bin/machine           = unknown
/usr/bin/oslevel       = unknown
/bin/universe          = unknown

PATH: /home/lichunfeng/Downloads/gdal/.github/workflows/android_cmake/cmake-3.22.3-linux-x86_64/bin
PATH: /usr/local/sbin
PATH: /usr/local/bin
PATH: /usr/sbin
PATH: /usr/bin
PATH: /sbin
PATH: /bin
PATH: /snap/bin

## ----------- ##

configure:2353: checking for a BSD-compatible install
configure:2421: result: /usr/bin/install -c
configure:2432: checking whether build environment is sane
configure:2487: result: yes
configure:2546: checking for aarch64-linux-android24-strip
configure:2576: result: no
configure:2586: checking for strip
configure:2602: found /usr/bin/strip
configure:2613: result: strip
configure:2638: checking for a thread-safe mkdir -p
configure:2677: result: /usr/bin/mkdir -p
configure:2684: checking for gawk
configure:2700: found /usr/bin/gawk
configure:2711: result: gawk
configure:2722: checking whether make sets $(MAKE)
configure:2744: result: yes
configure:2773: checking whether make supports nested variables
configure:2790: result: yes
configure:2929: checking for style of include used by make
configure:2957: result: GNU
configure:2988: checking for aarch64-linux-android24-gcc
configure:3015: result: ccache /home/lichunfeng/Downloads/gdal/.github/workflows/android_cmake/android-ndk-r23b/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android24-clang
configure:3284: checking for C compiler version
configure:3293: ccache /home/lichunfeng/Downloads/gdal/.github/workflows/android_cmake/android-ndk-r23b/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android24-clang --version >&5
/home/lichunfeng/Downloads/gdal/.github/workflows/android_cmake/android-ndk-r23b/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android24-clang: line 3: /home/lichunfeng/Downloads/gdal/.github/workflows/android_cmake/android-ndk-r23b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang: cannot execute binary file: Exec format error
configure:3304: $? = 126
configure:3293: ccache /home/lichunfeng/Downloads/gdal/.github/workflows/android_cmake/android-ndk-r23b/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android24-clang -v >&5
/home/lichunfeng/Downloads/gdal/.github/workflows/android_cmake/android-ndk-r23b/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android24-clang: line 3: /home/lichunfeng/Downloads/gdal/.github/workflows/android_cmake/android-ndk-r23b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang: cannot execute binary file: Exec format error
configure:3304: $? = 126
configure:3293: ccache /home/lichunfeng/Downloads/gdal/.github/workflows/android_cmake/android-ndk-r23b/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android24-clang -V >&5
/home/lichunfeng/Downloads/gdal/.github/workflows/android_cmake/android-ndk-r23b/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android24-clang: line 3: /home/lichunfeng/Downloads/gdal/.github/workflows/android_cmake/android-ndk-r23b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang: cannot execute binary file: Exec format error
configure:3304: $? = 126
configure:3293: ccache /home/lichunfeng/Downloads/gdal/.github/workflows/android_cmake/android-ndk-r23b/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android24-clang -qversion >&5
/home/lichunfeng/Downloads/gdal/.github/workflows/android_cmake/android-ndk-r23b/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android24-clang: line 3: /home/lichunfeng/Downloads/gdal/.github/workflows/android_cmake/android-ndk-r23b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang: cannot execute binary file: Exec format error
configure:3304: $? = 126
configure:3324: checking whether the C compiler works
configure:3346: ccache /home/lichunfeng/Downloads/gdal/.github/workflows/android_cmake/android-ndk-r23b/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android24-clang    conftest.c  >&5
/home/lichunfeng/Downloads/gdal/.github/workflows/android_cmake/android-ndk-r23b/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android24-clang: line 3: /home/lichunfeng/Downloads/gdal/.github/workflows/android_cmake/android-ndk-r23b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang: cannot execute binary file: Exec format error
configure:3350: $? = 126
configure:3388: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "sqlite"
| #define PACKAGE_TARNAME "sqlite"
| #define PACKAGE_VERSION "3.37.2"
| #define PACKAGE_STRING "sqlite 3.37.2"
| #define PACKAGE_BUGREPORT "http://www.sqlite.org"
| #define PACKAGE_URL ""
| #define PACKAGE "sqlite"
| #define VERSION "3.37.2"
| /* end confdefs.h.  */
| 
| int
| main ()
| {
| 
|   ;
|   return 0;
| }
configure:3393: error: in `/home/lichunfeng/Downloads/gdal/.github/workflows/android_cmake/sqlite-autoconf-3370200':
configure:3395: error: C compiler cannot create executables
See `config.log' for more details

## ---------------- ##

ac_cv_env_CC_set=set
ac_cv_env_CC_value='ccache /home/lichunfeng/Downloads/gdal/.github/workflows/android_cmake/android-ndk-r23b/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android24-clang'
ac_cv_env_CFLAGS_set=
ac_cv_env_CFLAGS_value=
ac_cv_env_CPPFLAGS_set=
ac_cv_env_CPPFLAGS_value=
ac_cv_env_CPP_set=
ac_cv_env_CPP_value=
ac_cv_env_LDFLAGS_set=
ac_cv_env_LDFLAGS_value=
ac_cv_env_LIBS_set=
ac_cv_env_LIBS_value=
ac_cv_env_LT_SYS_LIBRARY_PATH_set=
ac_cv_env_LT_SYS_LIBRARY_PATH_value=
ac_cv_env_build_alias_set=
ac_cv_env_build_alias_value=
ac_cv_env_host_alias_set=set
ac_cv_env_host_alias_value=aarch64-linux-android24
ac_cv_env_target_alias_set=
ac_cv_env_target_alias_value=
ac_cv_path_install='/usr/bin/install -c'
ac_cv_path_mkdir=/usr/bin/mkdir
ac_cv_prog_AWK=gawk
ac_cv_prog_CC='ccache /home/lichunfeng/Downloads/gdal/.github/workflows/android_cmake/android-ndk-r23b/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android24-clang'
ac_cv_prog_ac_ct_STRIP=strip
ac_cv_prog_make_make_set=yes
am_cv_make_support_nested_variables=yes

## ----------------- ##

ACLOCAL='${SHELL} /home/lichunfeng/Downloads/gdal/.github/workflows/android_cmake/sqlite-autoconf-3370200/missing aclocal-1.15'
AMDEPBACKSLASH='\'
AMDEP_FALSE='#'
AMDEP_TRUE=''
AMTAR='$${TAR-tar}'
AM_BACKSLASH='\'
AM_DEFAULT_V='$(AM_DEFAULT_VERBOSITY)'
AM_DEFAULT_VERBOSITY='1'
AM_V='$(V)'
AR=''
AUTOCONF='${SHELL} /home/lichunfeng/Downloads/gdal/.github/workflows/android_cmake/sqlite-autoconf-3370200/missing autoconf'
AUTOHEADER='${SHELL} /home/lichunfeng/Downloads/gdal/.github/workflows/android_cmake/sqlite-autoconf-3370200/missing autoheader'
AUTOMAKE='${SHELL} /home/lichunfeng/Downloads/gdal/.github/workflows/android_cmake/sqlite-autoconf-3370200/missing automake-1.15'
AWK='gawk'
BUILD_CFLAGS=''
CC='ccache /home/lichunfeng/Downloads/gdal/.github/workflows/android_cmake/android-ndk-r23b/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android24-clang'
CCDEPMODE=''
CFLAGS=''
CPP=''
CPPFLAGS=''
CYGPATH_W='echo'
DEFS=''
DEPDIR='.deps'
DLLTOOL=''
DSYMUTIL=''
DUMPBIN=''
ECHO_C=''
ECHO_N='-n'
ECHO_T=''
EGREP=''
EXEEXT=''
EXTRA_SHELL_OBJ=''
FGREP=''
GREP=''
INSTALL_DATA='${INSTALL} -m 644'
INSTALL_PROGRAM='${INSTALL}'
INSTALL_SCRIPT='${INSTALL}'
INSTALL_STRIP_PROGRAM='$(install_sh) -c -s'
LD=''
LDFLAGS=''
LIBOBJS=''
LIBS=''
LIBTOOL=''
LIPO=''
LN_S=''
LTLIBOBJS=''
LT_SYS_LIBRARY_PATH=''
MAKEINFO='${SHELL} /home/lichunfeng/Downloads/gdal/.github/workflows/android_cmake/sqlite-autoconf-3370200/missing makeinfo'
MANIFEST_TOOL=''
MKDIR_P='/usr/bin/mkdir -p'
NM=''
NMEDIT=''
OBJDUMP=''
OBJEXT=''
OTOOL64=''
OTOOL=''
PACKAGE='sqlite'
PACKAGE_BUGREPORT='http://www.sqlite.org'
PACKAGE_NAME='sqlite'
PACKAGE_STRING='sqlite 3.37.2'
PACKAGE_TARNAME='sqlite'
PACKAGE_URL=''
PACKAGE_VERSION='3.37.2'
PATH_SEPARATOR=':'
RANLIB=''
READLINE_LIBS=''
SED=''
SET_MAKE=''
SHELL='/bin/bash'
SHELL_CFLAGS=''
STRIP='strip'
VERSION='3.37.2'
ac_ct_AR=''
ac_ct_CC=''
ac_ct_DUMPBIN=''
am__EXEEXT_FALSE=''
am__EXEEXT_TRUE=''
am__fastdepCC_FALSE=''
am__fastdepCC_TRUE=''
am__include='include'
am__isrc=''
am__leading_dot='.'
am__nodep='_no'
am__quote=''
am__tar='$${TAR-tar} chof - "$$tardir"'
am__untar='$${TAR-tar} xf -'
bindir='${exec_prefix}/bin'
build=''
build_alias=''
build_cpu=''
build_os=''
build_vendor=''
datadir='${datarootdir}'
datarootdir='${prefix}/share'
docdir='${datarootdir}/doc/${PACKAGE_TARNAME}'
dvidir='${docdir}'
exec_prefix='NONE'
host='aarch64-linux-android24'
host_alias='aarch64-linux-android24'
host_cpu=''
host_os=''
host_vendor=''
htmldir='${docdir}'
includedir='${prefix}/include'
infodir='${datarootdir}/info'
install_sh='${SHELL} /home/lichunfeng/Downloads/gdal/.github/workflows/android_cmake/sqlite-autoconf-3370200/install-sh'
libdir='${exec_prefix}/lib'
libexecdir='${exec_prefix}/libexec'
localedir='${datarootdir}/locale'
localstatedir='${prefix}/var'
mandir='${datarootdir}/man'
mkdir_p='$(MKDIR_P)'
oldincludedir='/usr/include'
pdfdir='${docdir}'
prefix='/tmp/install'
program_transform_name='s,x,x,'
psdir='${docdir}'
runstatedir='${localstatedir}/run'
sbindir='${exec_prefix}/sbin'
sharedstatedir='${prefix}/com'
sysconfdir='${prefix}/etc'
target_alias=''

## ----------- ##

/* confdefs.h */
#define PACKAGE_NAME "sqlite"
#define PACKAGE_TARNAME "sqlite"
#define PACKAGE_VERSION "3.37.2"
#define PACKAGE_STRING "sqlite 3.37.2"
#define PACKAGE_BUGREPORT "http://www.sqlite.org"
#define PACKAGE_URL ""
#define PACKAGE "sqlite"
#define VERSION "3.37.2"

configure: exit 77

### Steps to reproduce the issue

sudo ./start.sh

### Versions and provenance

Linux Ubuntu 22.04

**Comment by rouault** [comment]
It seems you tried to use the CI Android build recipee we use. android_cmake.yml uses a Ubuntu 20.04 as a host. Not sure if that makes a difference. In any case, the error in your setup is before even reaching building GDAL itself.
