### ISSUE TITLE
Allow ogr_layer_algebra -input_lyr ALL

### ISSUE THREAD

**Issue by jidanni** [OSGeo/gdal#10273]
### Feature description

In #10270
> Input datasource has more than just a single layer, so you should specify which layer with -input_lyr

OK, but there should also be a way to say "use all layers".

Else e.g., we have a map of the 50 states, but are restricted to only being able to use a single state.

**Comment by rouault** [comment]
nah, too complicated. Compose utilities and use ogrmerge before
