### ISSUE TITLE
Some GitHub action jobs are "in progress" for more than a year

### ISSUE THREAD

**Issue by echoix** [OSGeo/gdal#10276]
### What is the bug?

The last 6 workflow jobs are in progress for the last year. It doesn't really have an impact, except that they are always there when trying to count or see active jobs.

### Steps to reproduce the issue

See https://github.com/OSGeo/gdal/actions?query=is%3Ain_progress

### Versions and provenance

GitHub Actions

### Additional context

Usually a job times out after 6 hours. It is clearly impossible, and even the job logs aren't available anymore.

Maybe trying to delete these 6 workflow logs might take them off the list?

**Comment by rouault** [comment]
Workflows deleted

**Comment by echoix** [comment]
> Workflows deleted

*workflow runs


Thanks!
