### ISSUE TITLE
gdal_edit.py replacing Metadata rather than appending/editing

### ISSUE THREAD

**Issue by taylorday** [OSGeo/gdal#1027]
## Expected behavior and actual behavior.

I ran the `gdal_edit.py` script with the `-mo` option enabled to edit an existing metadata tag in my .tif file. It successfully edited the existing tag but also removed the rest of the metadata tags that belonged to that image. 

The code appears to overwrite the metadata rather than editing the current metadata and appending new tags. 

## Steps to reproduce the problem.

`gdal_edit.py -mo metadata_tag=10`

This removes all existing metadata tags and just adds what is specified in the above command.

## Operating system

For example: Ubuntu 16.04 64 bit

## GDAL version and provenance

3.0.8 from `conda install gdal`

**Comment by rouault** [comment]
I can't reproduce the overwriting. This works fine for me. Please provide an input image and the exact gdal_edit.py invokations you did on it.

**Comment by taylorday** [comment]
Appears to have been an old gdal_edit.py script lurking around. Appears to be working for the latest version.
