### ISSUE TITLE
DXF: When blocks are exploded, entities do not hold the blocks visible state

### ISSUE THREAD

**Issue by donnyv** [OSGeo/gdal#1028]
When using ogr2ogr version 2.4.0-42075 to export dxf to geojson. The block entities that are being exploded are not respecting the block layer visibility state by setting the color to be transparent.
`ogr2ogr.exe"" -f GeoJSON  "0901_010--dxf-WebMercator.geojson" -s_srs "EPSG:3424" -t_srs "EPSG:4326" "0901_010.dxf" -sql "SELECT SubClasses, Layer, Text, Linetype, ogr_style, PaperSpace FROM entities WHERE 1 = 1 "`
http://gis.civilsolutions.biz/downloads/0901_010.dxf

**Comment by rouault** [comment]
CC @atlight

**Comment by atlight** [comment]
Should be fixed by f722e742a6963701692ad111819225355a14a3c6.
