### ISSUE TITLE
ogrinfo: input file should be optional

### ISSUE THREAD

**Issue by jidanni** [OSGeo/gdal#10296]
### Feature description

Here the user is forced to include an irrelevant input file, when all the user is trying to do is get the result of a fully self-contained SELECT statement.
```
$ ogrinfo a.csv -dialect SQLITE -sql \
"SELECT ST_Buffer(ST_GeomFromText('POLYGON ((120.81313 24.18337...
```
So perhaps `ogrinfo` should simply have input files be optional.

(Or, on the man page have a "how to fake the input file" section.
("Just create a file.csv with the following lines.") Yes, simple, but ugly.)

**Comment by rouault** [comment]
You can use the ":memory:" input file which is a in-memory empty SQLite file

ogrinfo :memory: -sql "SELECT ST_Buffer(ST_GeomFromText('POINT(0 0)'), 1)"

**Comment by jratike80** [comment]
Why it does not work in this order:

```
ogrinfo -sql "SELECT ST_Buffer(ST_GeomFromText('POINT(0 0)'), 1)" :memory
ERROR 4: :memory: No such file or directory
```
I have been using on-the-fly generated data a lot when answering users questions. I had not thought about using the SQLite memory db. I was now considering to have some reserved datasource name like "virtualSQL". Somehow I was remembering the dummy "DUAL" table in Oracle https://www.w3resource.com/sql/sql-dual-table.php. I remember that DUAL was quite handy when I used Oracle a long time ago.

**Comment by rouault** [comment]
> Why it does not work in this order:

it does for me. Perhaps you need to surround :memory: with double quotes

**Comment by jratike80** [comment]
The error message, that itself contains colons, just fooled me and I did not notice that the ending colon was missing from `:memory:`. I used `:memory` and the error was
`ERROR 4: :memory: No such file or directory`

**Comment by jidanni** [comment]
Got an idea: If ogrinfo doesn't find an input file, then it should just plug :memory: into itself internally.
