### ISSUE TITLE
MySQL-Support in gdal on Mac missing

### ISSUE THREAD

**Issue by a2-c-martin** [OSGeo/gdal#10298]
### What is the bug?

When using ogr2ogr no MySQL driver is available

### Steps to reproduce the issue

installing gdal using brew or installing QGIS leads to a non MySQL-installation

### Versions and provenance

any version, the last one I tried: GDAL 3.10.0dev-1015b1c320-dirty, released 2024/06/24

**Comment by rouault** [comment]
This is a binary distribution issue, not a GDAL upstream one
