### ISSUE TITLE
Add dataset creation options for GML driver to place geometry field after attribute fields

### ISSUE THREAD

**Issue by ttruefix14** [OSGeo/gdal#10305]
### Feature description

Dataset creation option for GML driver:
**GEOMETRY_FIELD_PLACEMENT=[FIRST/LAST]**
Defaults to **FIRST**. Specify order of geometry field relative to attribute fields.

### Additional context

Problem:
When we have **sequence** of fields in  Xml Schema Definition (XSD) fields should go in strict order. GML driver always places geometry field on the first place so if geometry field goes after attribute fields in XSD we'll have validation error.

**Comment by jratike80** [comment]
Do you mean that the .xsd schema file that GDAL creates does not match with the GML data, and validation fails therefore?

https://gdal.org/drivers/vector/gml.html#dataset-creation-options

**Comment by ttruefix14** [comment]
> Do you mean that the .xsd schema file that GDAL creates does not match with the GML data, and validation fails therefore?
> 
> https://gdal.org/drivers/vector/gml.html#dataset-creation-options

No, some gis services require spatial data in GML format but before importing they validate GML using their own external XSD scheme. And gdal has good functionality to create GML files, but if geometry field in xsd sequence goes after attribute field (if it is like that in external XSD) validation will fail. As i see we can reorder attribute fields and geometry fields, but we cant decide in which order geometry fields goes relative to attribute fields

**Comment by ttruefix14** [comment]
For example:
I have complex type in XSD:
```xsd	
<xs:complexType name="LandUse_Type">
    <xs:complexContent>
        <xs:extension base="gml:AbstractFeatureType">
            <xs:sequence>
                <xs:element name="GLOBALID" type="fgistp:UUID" />
                <xs:element name="CLASSID" type="fgistp:LandUse_CLASSID" />
                <xs:element name="STATUS" type="fgistp:STATUS_PR_Type" />
                <xs:choice>
                    <xs:element ref="gml:MultiSurface" />
                </xs:choice>
            </xs:sequence>
        </xs:extension>
    </xs:complexContent>
</xs:complexType>
```

Ogr will create something like this:
```xml
<ogr:featureMember>
    <ogr:LandUse_Polygon gml:id="LandUse_Polygon.1">
        <ogr:geometryProperty>
            <gml:MultiSurface srsName="urn:ogc:def:crs:EPSG::3857">
                <gml:surfaceMember>
                    <gml:Polygon>
                        <gml:exterior>
                            <gml:LinearRing>
                                <gml:posList>4422323.71368237 5566423.53649862 4422718.53817656
                                    5566650.07919054 4422718.54113752 5566650.07782426
                                    4422323.71368074 5566423.53649762 4422323.71368237
                                    5566423.53649862</gml:posList>
                            </gml:LinearRing>
                        </gml:exterior>
                    </gml:Polygon>
                </gml:surfaceMember>
            </gml:MultiSurface>
        </ogr:geometryProperty>
        <ogr:GLOBALID>{1C6AC86F-2394-4398-BD51-038D248827F4}</ogr:GLOBALID>
        <ogr:CLASSID>702010200</ogr:CLASSID>
        <ogr:STATUS>1</ogr:STATUS>
    </ogr:LandUse_Polygon>
</ogr:featureMember>
```
But XSD schema requires like this:
```xml
<ogr:featureMember>
    <ogr:LandUse_Polygon gml:id="LandUse_Polygon.1">
        <ogr:GLOBALID>{1C6AC86F-2394-4398-BD51-038D248827F4}</ogr:GLOBALID>
        <ogr:CLASSID>702010200</ogr:CLASSID>
        <ogr:STATUS>1</ogr:STATUS>
        <ogr:geometryProperty>
            <gml:MultiSurface srsName="urn:ogc:def:crs:EPSG::3857">
                <gml:surfaceMember>
                    <gml:Polygon>
                        <gml:exterior>
                            <gml:LinearRing>
                                <gml:posList>4422323.71368237 5566423.53649862 4422718.53817656
                                    5566650.07919054 4422718.54113752 5566650.07782426
                                    4422323.71368074 5566423.53649762 4422323.71368237
                                    5566423.53649862</gml:posList>
                            </gml:LinearRing>
                        </gml:exterior>
                    </gml:Polygon>
                </gml:surfaceMember>
            </gml:MultiSurface>
        </ogr:geometryProperty>
    </ogr:LandUse_Polygon>
</ogr:featureMember>
```

In this example XSD schema although needs geometry data without tag "geometryProperty", but that is different problem)

**Comment by jratike80** [comment]
Do you mean that you have an existing XSD schema and you would like GDAL to write data that is matching with that XSD? An option to let GDAL write both GML and a matching XSD file is not good for you?

I think that the GEOMETRY_FIELD_PLACEMENT=[FIRST/LAST] selection is not the solution. What if the geometry field is the second one in the sequence?

Maybe the GMLAS driver https://gdal.org/drivers/vector/gmlas.html could do what you want. At least it seems to have a datastore creation option for INPUT_XSD.

**Comment by jratike80** [comment]
I tried this:

`ogr2ogr -f gml -dialect sqlite -sql "select orig_label,unit_link,geometry from SGMC_Geology limit 2" out2.gml SGMC_Geology.shp`

but the geometry is really placed first into GML even I selected it last.

**Comment by ttruefix14** [comment]
> Do you mean that you have an existing XSD schema and you would like GDAL to write data that is matching with that XSD? An option to let GDAL write both GML and a matching XSD file is not good for you?
> 
> I think that the GEOMETRY_FIELD_PLACEMENT=[FIRST/LAST] selection is not the solution. What if the geometry field is the second one in the sequence?
> 
> Maybe the GMLAS driver https://gdal.org/drivers/vector/gmlas.html could do what you want. At least it seems to have a datastore creation option for INPUT_XSD.



> Do you mean that you have an existing XSD schema and you would like GDAL to write data that is matching with that XSD? An option to let GDAL write both GML and a matching XSD file is not good for you?
> 
> I think that the GEOMETRY_FIELD_PLACEMENT=[FIRST/LAST] selection is not the solution. What if the geometry field is the second one in the sequence?
> 
> Maybe the GMLAS driver https://gdal.org/drivers/vector/gmlas.html could do what you want. At least it seems to have a datastore creation option for INPUT_XSD.

For me it have no sense to validate order of fields, but the problem with external xsd validation is exists.
You're right that geometry field can be second in sequence, but to implement something like this in gml driver is really have no sense, but just to allow placing geometry fields at first or last place will be good)
I'll try to GMLAS driver to see if can resolve this problem, thank you for suggestion

**Comment by ttruefix14** [comment]
GMLAS really allows to specify geometry field placement.
Although it can't create geometry without additional field like "geometryProperty", with example above it gives me two geometry fields with geometry inside, it is not valid because xsd choice should contain only one from its elements)
But it is different problem so i'm closing issue
