### ISSUE TITLE
OSM Toner doesn't work in gdal2tiles

### ISSUE THREAD

**Issue by kadyb** [OSGeo/gdal#10304]
### What is the bug?

https://github.com/OSGeo/gdal/blob/f160dfd68e518d14149aed751662065515bb065b/swig/python/gdal-utils/osgeo_utils/gdal2tiles.py#L3987-L3988

It seems that the service address has changed and no longer works.

Now the link looks like this: `https://tiles.stadiamaps.com/tiles/stamen_toner/16/10516/25320.png`, but requires registration (https://docs.stadiamaps.com/authentication).

I guess the best solution would be to remove this service?

### Steps to reproduce the issue

For example, the following link doesn't work:

```
https://b.tile.stamen.com/toner/7/70/42.png
#> NS_ERROR_UNKNOWN_HOST
```

### Versions and provenance

Windows 11

**Comment by rouault** [comment]
> I guess the best solution would be to remove this service?


yes
