### ISSUE TITLE
Tiff color table component values seem wrong (minus one from what they should be)

### ISSUE THREAD

**Issue by slesim** [OSGeo/gdal#10310]
### What is the bug?

Using gdalinfo on an 8bits indexed tiff file. RGB component values returned (different from 0) have a minus one shift from what they should be : 
```
0: 0,0,0,255 
1: 0,0,0,255 
2: 0,0,0,255 
3: 0,0,0,255 
4: 0,0,0,255 
5: 0,0,0,255 
6: 0,0,0,255 
7: 0,0,0,255 
8: 0,0,0,255 
9: 0,0,0,255 
10: 0,0,0,255 
11: 169,239,239,255 
12: 0,0,0,255 
13: 0,0,0,255 
14: 254,254,99,255 
15: 0,0,0,255 
16: 0,0,0,255 
17: 0,0,0,255 
18: 0,0,0,255 
19: 0,0,0,255 
20: 219,239,99,255 
```
Using other library like python tifffile, or .NET BitMiracle.LibTiff.Net : 
```
0 : 0 0 0       
1 : 0 0 0       
2 : 0 0 0       
3 : 0 0 0       
4 : 0 0 0       
5 : 0 0 0       
6 : 0 0 0       
7 : 0 0 0       
8 : 0 0 0       
9 : 0 0 0       
10 : 0 0 0      
11 : 170 240 240
12 : 0 0 0      
13 : 0 0 0      
14 : 255 255 100
15 : 0 0 0      
16 : 0 0 0      
17 : 0 0 0      
18 : 0 0 0      
19 : 0 0 0      
20 : 220 240 100
```

### Steps to reproduce the issue

Sample code to compare it with python tifffile : 
```
from tifffile import TiffFile

with TiffFile('sample.tif', mode='r+') as tif:
    tag = tif.pages[0].tags['ColorMap']
    r, g, b = tag.value[0], tag.value[1], tag.value[2]
    for i in range(len(r)):
        print("%d : %d %d %d" % (i, int.from_bytes(r[i]), int.from_bytes(g[i]), int.from_bytes(b[i])))
```

### Versions and provenance

Confirmed with 3.8.5, 3.7.2, 3.4.2. I don't have checked but we don't have noticed this issue in older version of our software using 1.9.2.

**Comment by cgohlke** [comment]
Tifffile does not do any conversion or remapping. `tif.pages[0].tags['ColorMap'].value` is a numpy array of dtype `uint16`. 

The conversion in the example code is `int.from_bytes(r[i])`, which is wrong in general but happens to give expected results for multiples of 256.

**Comment by slesim** [comment]
Thanks for your answers, it helps my understanding.
Here is a sample file :
[rugoIndex.zip](https://github.com/user-attachments/files/16011226/rugoIndex.zip)
