### ISSUE TITLE
ESRI FileGDB Driver 3.9.1 ERROR 1

### ISSUE THREAD

**Issue by amgiss** [OSGeo/gdal#10345]
### What is the bug?

FileGDB Driver 3.9.1 throws "ERROR 1: Cannot find filename for layer ..." errors for some layers only when converting from GPKG to File GDB. The errors appear are misleading as the layers are created successfully in the output File GDB.

### Steps to reproduce the issue

Upgrade File GDB driver from to 3.9.1 under OSGeo4W.

### Versions and provenance

Windows 10
GDAL 3.9.1, released 2024/06/22
OSGeo4W

### Additional context

These errors also occur with 3.8.5, but I don't think they always occurred in earlier versions.

**Comment by rouault** [comment]
@amgiss Please attach an input dataset that reproduces the issue
