### ISSUE TITLE
Can it be used in the dotnet core?

### ISSUE THREAD

**Issue by ycyiyue** [OSGeo/gdal#1034]
i want know that Can it be used in the dotnet core? Are there specific documents and tutorials?

**Comment by rouault** [comment]
Reiterating what is in the issue template:
 "
Questions should go to the gdal-dev mailing list (https://lists.osgeo.org/mailman/listinfo/gdal-dev)
or other support forums. GitHub issues are for bug reports and suggestions
for new features."
