### ISSUE TITLE
ERROR: column s.consrc does not exist

### ISSUE THREAD

**Issue by gautam-kirtania** [OSGeo/gdal#10359]
### What is the bug?

Thanks in advance.

I'm using ogr2ogr to move data from a shapefile to a postgres table.

This is the command I'm using.
`ogr2ogr -f PostgreSQL "PG:dbname=<dbname> user=<dbuser> password=<dbpassword> host=<dbhost>" -nln tmp_sample -nlt PROMOTE_TO_MULTI sample.shp -select  -skipfailures`

This is the error I'm getting
```
LINE 1: ...nrelid = c.oid AND a.attnum = ANY (s.conkey) AND (s.consrc L...
                                                             ^
HINT:  Perhaps you meant to reference the column "s.conkey" or the column "s.conbin".

ERROR 1: ERROR:  column s.consrc does not exist
LINE 1: ...nrelid = c.oid AND a.attnum = ANY (s.conkey) AND (s.consrc L...
                                                             ^
HINT:  Perhaps you meant to reference the column "s.conkey" or the column "s.conbin".

ERROR 1: ERROR:  current transaction is aborted, commands ignored until end of transaction block

ERROR 1: ERROR:  current transaction is aborted, commands ignored until end of transaction block

ERROR 1: ERROR:  current transaction is aborted, commands ignored until end of transaction block

ERROR 1: ERROR:  current transaction is aborted, commands ignored until end of transaction block

ERROR 1: ERROR:  current transaction is aborted, commands ignored until end of transaction block
```

### Steps to reproduce the issue

Try with any shapefile

I have the following extension files for a particular shapefile.
> .shp
> .shx
> .dbf
> .sbx
> .sbn
> .cpg
> .prj
> .xml

### Versions and provenance

My system config looks like this:
> OS - ubuntu:18.04
> Python - 3.8
> GDAL - 2.4.2
> Postgres - 16

**Comment by jratike80** [comment]
Do you have dots in the field names of your shapefile? What does this show for you:

`ogrinfo sample.shp -al -so`

**Comment by gautam-kirtania** [comment]
This is the output
```
INFO: Open of sample.shp
      using driver ESRI Shapefile' successful.

Layer name: sample
Metadata:
  DBF_DATE_LAST_UPDATE=2015-09-01
Geometry: Polygon
Feature Count: 86884
Extent: (70227.065400, 300295.397183) - (107015.816714, 333612.953894)
Layer SRS WKT:
PROJCRS["Transverse_Mercator",
    BASEGEOGCRS["WGS 84",
        DATUM["unknown",
            ELLIPSOID["WGS84",6378137,298.257223563,
                LENGTHUNIT["metre",1,
                    ID["EPSG",9001]]]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["Degree",0.0174532925199433]]],
    CONVERSION["unnamed",
        METHOD["Transverse Mercator",
            ID["EPSG",9807]],
        PARAMETER["Latitude of natural origin",24,
            ANGLEUNIT["Degree",0.0174532925199433],
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",78.416,
            ANGLEUNIT["Degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["Scale factor at natural origin",0.999444,
            SCALEUNIT["unity",1],
            ID["EPSG",8805]],
        PARAMETER["False easting",500000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",500000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["(E)",east,
            ORDER[1],
            LENGTHUNIT["metre",1,
                ID["EPSG",9001]]],
        AXIS["(N)",north,
            ORDER[2],
            LENGTHUNIT["metre",1,
                ID["EPSG",9001]]]]
Data axis to CRS axis mapping: 1,2
ccode91: String (254.0)
ccode01: String (254.0)
bhucode: String (254.0)
ccode11: String (6.0)
accode: String (254.0)
districtc: String (254.0)
tehsilcode: String (254.0)
blockcode: String (254.0)
gpcode: String (254.0)
lgdgpcode: String (254.0)
villageh: String (254.0)
villagee: String (254.0)
khasranum: String (50.0)
```

**Comment by msmitherdc** [comment]
I think the issue is that you have -select -skipfailures. Remove the -select part, it’s trying to select columns and you haven’t provided any. Michael SmithOn Jul 4, 2024, at 12:10 PM, Gautam Kirtania ***@***.***> wrote:﻿
This is the output
INFO: Open of sample.shp
      using driver ESRI Shapefile' successful.

Layer name: sample
Metadata:
  DBF_DATE_LAST_UPDATE=2015-09-01
Geometry: Polygon
Feature Count: 86884
Extent: (70227.065400, 300295.397183) - (107015.816714, 333612.953894)
Layer SRS WKT:
PROJCRS["Transverse_Mercator",
    BASEGEOGCRS["WGS 84",
        DATUM["unknown",
            ELLIPSOID["WGS84",6378137,298.257223563,
                LENGTHUNIT["metre",1,
                    ID["EPSG",9001]]]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["Degree",0.0174532925199433]]],
    CONVERSION["unnamed",
        METHOD["Transverse Mercator",
            ID["EPSG",9807]],
        PARAMETER["Latitude of natural origin",24,
            ANGLEUNIT["Degree",0.0174532925199433],
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",78.416,
            ANGLEUNIT["Degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["Scale factor at natural origin",0.999444,
            SCALEUNIT["unity",1],
            ID["EPSG",8805]],
        PARAMETER["False easting",500000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",500000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["(E)",east,
            ORDER[1],
            LENGTHUNIT["metre",1,
                ID["EPSG",9001]]],
        AXIS["(N)",north,
            ORDER[2],
            LENGTHUNIT["metre",1,
                ID["EPSG",9001]]]]
Data axis to CRS axis mapping: 1,2
ccode91: String (254.0)
ccode01: String (254.0)
bhucode: String (254.0)
ccode11: String (6.0)
accode: String (254.0)
districtc: String (254.0)
tehsilcode: String (254.0)
blockcode: String (254.0)
gpcode: String (254.0)
lgdgpcode: String (254.0)
villageh: String (254.0)
villagee: String (254.0)
khasranum: String (50.0)

**Comment by rouault** [comment]
The issue is that you are using a quite antiquated GDAL version with a pretty new versions of PostgreSQL.
Support for PostgreSQL >= 12 was added per 0ee2ee219b3b55b6568e5dc43fd817a3bbf908e9 in GDAL 3.1. You need to update your GDAL version at least to that
