### ISSUE TITLE
How to read a s3 object and put the trasnlate result  to  s3 bucket too

### ISSUE THREAD

**Issue by zaviazhou** [OSGeo/gdal#1037]
## Expected behavior and actual behavior.

For example: I expected to be able to open this raster file (with a link to
the raster file, or it as an attachment) and it returns an error message
instead.

## Steps to reproduce the problem.

For example: "gdalinfo myfile"

## Operating system

For example: Ubuntu 16.04 64 bit

## GDAL version and provenance

For example: the 2.2.3 version from ubuntugis-unstable PPA

**Comment by rouault** [comment]
github issues are not for question . Please do not abuse project maintainer time
