### ISSUE TITLE
Can not delete or copy a file in s3 bucket by using gdal_rm.py and gdal_cp.py

### ISSUE THREAD

**Issue by zaviazhou** [OSGeo/gdal#1038]
##  problem1.
try to remove tif files,
local files a still there::
[root@quantum-gdal-wjl-test ~]# ll small_world_rgb.tif 
-rwxrwxrwx 1 root root 41653 Oct 20 17:00 small_world_rgb.tif
[root@quantum-gdal-wjl-test ~]# /usr/bin/python gdal_rm.py -r small_world_rgb.tif 
[root@quantum-gdal-wjl-test ~]# ls
anaconda-ks.cfg  gdal_rm.py           small_world_rgb.tif  test1.svg
gdal_cp.py       small_world_pct.tif  test                 wjl

##  problem2.
try to remove a file in s3bucket  or copy a local file to s3bucket, the objetcts in bucket did not changed.:
[root@quantum-gdal-wjl-test ~]# /usr/bin/python gdal_cp.py test1.svg /vsis3/https://obs-zhouyuanyua
n.obs.cn-north-1.myhwclouds.com/earth_date/
[root@quantum-gdal-wjl-test ~]# /usr/bin/python gdal_cp.py -r test1.svg /vsis3/https://obs-zhouyuanwclouds.com/test
yuan.obs.cn-north-1.myhwclouds.com/earth_date/
[root@quantum-gdal-wjl-test ~]# /usr/bin/python gdal_rm.py /vsis3/https://obs-zhouyuanyuan.obs.cn-n
orth-1.myhwclouds.com/earth_date/small_world_pct.tif

##

**Comment by rouault** [comment]
Both local and /vsis3/ file removal work for me.
And you are not using the right syntax for /vsis3/ bucket (you should use bucket_name/object, and not https://) . Consult the doc at https://gdal.org/gdal_virtual_file_systems.html#gdal_virtual_file_systems_vsis3 .
