### ISSUE TITLE
Option to set CRS of an OGR Layer

### ISSUE THREAD

**Issue by digital-idiot** [OSGeo/gdal#10380]
### Feature description

Currently an OGR Layer object has no option to set it SRS.

### Additional context

In many cases the data source and more specifically a layer may have no SRS set. It would be useful to have an option for specifying SRS of a layer object. One example use case is as follows:

```python
with gdal.OpenEx(path_to_gml, gdal.OF_VECTOR) as src_ds:
    query_layer = src_ds.ExecuteSQL(...)  # 'query_layer' layer has no SRS set
    with dst_driver.Create(
        str(dst_path), 0, 0, 0, gdal.GDT_Unknown, dst_options
    ) as dst_ds:
        dst_ds.CopyLayer(
            query_layer,
            layer_name
        )  # No option to set SRS here either!

```

I am aware that it is possible to use `CreateLayer` specifying SRS instead of `CopyLayer` and then copy features using loop is an workaround but loops in python are slow which adds up for a large dataset.

**Comment by rouault** [comment]
For your use case, I would suggest using ``gdal.VectorTranslate(dst_filename, src_filename, format='output_driver', SQLStatement='...', dstSRS='WKT string or EPSG:XXXX', reproject=False)``
