### ISSUE TITLE
Warning 1: PROJ: proj_create_from_database: C:\Program Files\GDAL\projlib\proj.db contains DATABASE.LAY OUT.VERSION.MINOR = 2 whereas a number >= 3 is expected. It comes from another PROJ installation.

### ISSUE THREAD

**Issue by milansoliya4210** [OSGeo/gdal#10381]
### What is the bug?

Give me bug with GDAL 3.9.1Warning 1: PROJ: proj_create_from_database: C:\Program Files\GDAL\projlib\proj.db contains DATABASE.LAY
OUT.VERSION.MINOR = 2 whereas a number >= 3 is expected. It comes from another PROJ installation.

### Steps to reproduce the issue

While setup with Windows11 give me this error and i have set all environment variable still it is give me this error  

### Versions and provenance

Windows 11
GDAL 3.9.1

**Comment by szekerest** [comment]
@milansoliya4210 Which package produces that warning?

**Comment by rouault** [comment]
This is not a GDAL upstream issue, but rather a mixed-up installation with possibly the PROJ_LIB or PROJ_DATA environment variable incorrectly set
