### ISSUE TITLE
PGDump not honouring PG_USE_COPY

### ISSUE THREAD

**Issue by rhysallister** [OSGeo/gdal#1039]
Using PG_USE_COPY doesn't consistently use the COPY command. 

Initially a few tables are 'COPY'd but then the other tables are populated with INSERT statements.

See https://youtu.be/H-Gg3iVDmds for example

### OS info
```
Linux victorious-wanyamaha 4.15.0-36-generic #39-Ubuntu SMP Mon Sep 24 16:19:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
### GDAL/OGR info
```
GDAL 2.2.3, released 2017/11/20
```

**Comment by rouault** [comment]
It is not always possible to use COPY. In particular if the input layer has columns with a DEFAULT value specified and that the feature has no value set for that given field, the driver will default to INSERT.

**Comment by rhysallister** [comment]
In this case, I'm using an ESRI FileGeodatabase, so I'm not sure if they have default columns. Further, when using the Postgresql driver on the same dataset the PG_USE_COPY flag works as expected.

**Comment by rouault** [comment]
>  I'm not sure if they have default columns

They can! Look at the output of ogrinfo on the filegeodatabase.

> when using the Postgresql driver on the same dataset the PG_USE_COPY flag works as expected.

Hum weird. can you point to a input dataset to reproduce the issue ?

**Comment by rouault** [comment]
Closing due to lack of feedback

**Comment by lorenzogrv** [comment]
> > where can I contribute documentation to explain this fact? It could be useful for others, maybe at driver docs, i.e. https://gdal.org/en/stable/drivers/vector/pgdump.html#environment-variables
> 
> yes, you can use the "Edit on github" button on the top right

🤦 embarrasing, didn't see it. Thanks!
