### ISSUE TITLE
gdalwarp and vertical transform with Nodata in the transform grid

### ISSUE THREAD

**Issue by barry-gallagher** [OSGeo/gdal#10395]
### What is the bug?

We are building some proj transformation grids.  When we use gdalwarp with them we get a zero or no-op at positions where the transform grid has a nodata value.  For example our proj transform(38.09655,-76.36924,10) = (inf, inf, inf) but our raster point at that position would return (38.09655,-76.36924,10).  Other cells that have data in the transform grid will perform a vertical shift as expected.

### Steps to reproduce the issue

We can supply a proj.db and our grids if needed

### Versions and provenance

Windows 10/11, python 3.11, gdal 3.8.4

**Comment by rouault** [comment]
Please provide input dataset and exact gdalwarp command line used

**Comment by barry-gallagher** [comment]
Sorry for the delay.  We had originally done our tests from python, in reproducing the behavior on the command line I found our code was making a copy of the input data and using GA_UPDATE on that copy as the output.  Is it correct that gdalwarp should not insert nodata values when updating a file in place?  Is there an override switch to make the grid transform's nodata replace the output file value?  

Below are the commands and data files and images of the output.  Notice we make a data copy before the second warp call. The last image shows that in an area which has a nodata value in the transform area that is nodata when a new file is made but not when updating a file in place.


`gdalwarp -vshift -ct "+proj=pipeline +step +proj=axisswap +order=2,1  +step +proj=unitconvert +xy_in=deg +xy_out=rad +step +inv +proj=vgridshift +grids=us_noaa_nos_ITRF2014_MLLW_LMSL_(DEdelches02_vdatum_4.4_20220315_1983-2001).tif +step +proj=unitconvert +xy_in=rad +xy_out=deg +step +proj=axisswap +order=2,1" VA_input.tif VA_output_new.tif`

`copy VA_input.tif VA_output_copy.tif`

`gdalwarp -vshift -ct "+proj=pipeline +step +proj=axisswap +order=2,1  +step +proj=unitconvert +xy_in=deg +xy_out=rad +step +inv +proj=vgridshift +grids=us_noaa_nos_ITRF2014_MLLW_LMSL_(DEdelches02_vdatum_4.4_20220315_1983-2001).tif +step +proj=unitconvert +xy_in=rad +xy_out=deg +step +proj=axisswap +order=2,1" VA_input.tif VA_output_copy.tif
`

[MLLW transform grid](https://noaa-ocs-nationalbathymetry-pds.s3.amazonaws.com/Test-and-Evaluation/NOAA_NOS_Vertical_Datum_Register/non-GTG/us_noaa_nos_ITRF2014_MLLW_LMSL_(DEdelches02_vdatum_4.4_20220315_1983-2001).tif)

[VA input and output data.zip](https://github.com/user-attachments/files/16183288/data.zip)

The MLLW transform area
![transform_area](https://github.com/user-attachments/assets/c231f151-b51e-46b3-97a3-97cee0d82aa9)
The VA_Input data
![Input_area](https://github.com/user-attachments/assets/7c3822aa-5655-4388-8a43-755e1ffd4294)
gdalwarp output when creating a new file (as expected)
![new_output](https://github.com/user-attachments/assets/f3a5547d-795f-4f1f-8096-602b1f0b1094)
gdalwarp updating an existing file
![copy_output](https://github.com/user-attachments/assets/18cac96e-6761-441a-9748-d835ea342d3a)
values show in QGIS for the layers showing the ouput_copy still has a value when nodata would be preferred.
![nodata_area](https://github.com/user-attachments/assets/5ad3acd5-d1a9-4ff4-9c35-e7f0c0cc8c11)

**Comment by rouault** [comment]
> Is it correct that gdalwarp should not insert nodata values when updating a file in place?

yes, when updating in place, if gdalwarp doesn't manage to find the source pixel for a target pixel, it won't update the target pixel value.

> Is there an override switch to make the grid transform's nodata replace the output file value?

no.

In that situation, you could potentially use "gdal_create -if VA_input.tif out.tif", to create an empty output file with the same characteristics as the input file

**Comment by barry-gallagher** [comment]
Thanks for clearing up our misunderstanding.
