### ISSUE TITLE
SpatialReference.EPSGTreatsAsNorthingEasting missing from Java bindings

### ISSUE THREAD

**Issue by Achifaifa** [OSGeo/gdal#10409]
### What is the bug?

I'm trying to use EPSGTreatsAsNorthingEasting() in the java bindings, but it seems to be missing. 

EPSGTreatsAsLatLong is there (Even if it returns 0 or 1 instead of true or false as specified in the docs), but there is no trace of EPSGTreatsAsNorthingEasting. I'm not clear if the function is misplaced in the [documentation](https://gdal.org/java/org/gdal/osr/SpatialReference.html#EPSGTreatsAsNorthingEasting()) or missing in the class, or something else entirely..

I've been looking into the way the bindings are generated for a while and I'm not sure if this is something I can fix myself in a reasonable timeframe. I'd really appreciate any hints about where to go from here, because I'm a bit lost.

### Steps to reproduce the issue

1) Create a SpatialReference object
2) Try to use SpatialReference.EPSGTreatsAsNorthingEasting()

### Versions and provenance

Windows 11, GDAL Native Library 3.2.1 obtained from Maven Central.

**Comment by rouault** [comment]
> 2. Try to use SpatialReference.EPSGTreatsAsNorthingEasting()

The function is in the Java bindings doc, so it is definitely there. You just have to use it. It just lacks documentation. The one of the C++ method applies: https://gdal.org/api/ogrspatialref.html#_CPPv4NK19OGRSpatialReference27EPSGTreatsAsNorthingEastingEv

**Comment by Achifaifa** [comment]
Hi rouault, thanks for the reply.

I'm attaching a screenshot of the situation, just in case I misinterpreted the error. Since the docs are autogenerated I was assuming that the function would be there, but I've found no way of accessing it.

![Untitled](https://github.com/user-attachments/assets/6d5ac5bc-59e1-40d4-bf69-e3ef1b789336)

**Comment by rouault** [comment]
> Since the docs are autogenerated

not quite. C++ documentation must be manually ported to the Java bindings, hence the lack of text for some methods in the Javadoc. But if their prototype appears, they are available.

I've added a test in https://github.com/OSGeo/gdal/pull/10411 to test it.

**Comment by Achifaifa** [comment]
Hi rouault

Thanks for the quick fix, I'll try compiling the bindings with the changes you applied once they go through.

**Comment by rouault** [comment]
> Thanks for the quick fix, I'll try compiling the bindings with the changes you applied once they go through.

that won't change anything. This is just about documentation. The method should already be there and usable
