### ISSUE TITLE
Issue with construction of server path on the OAPIF driver

### ISSUE THREAD

**Issue by doublebyte1** [OSGeo/gdal#10410]
### What is the bug?

`ogrinfo OAPIF:https://maps.gnosis.earth/ogcapi/collections/Daraa:HydrographySrf/` triggers this error: 

```
ERROR 1: HTTP error code : 400
ERROR 1: <h1>GNOSIS Map Server (OGCAPI) - 400 Bad Request</h1><h3>Unsupported or malformed request</h3>
```

The same request works for urls that do not contain relative links, like `https://ogc-api.nrw.de/inspire-us-feuerwehr` or `https://emotional.byteroad.net/collections/hex350_grid_cardio_1920`

As pointed out by @jerstlouis, according to RFC 8288 / RFC 3986 Relative links should be resolved properly :
 
https://docs.ogc.org/is/19-072/19-072.html#_11b9b4f7-42fc-413a-b63a-e7fb060b5e4b
 
https://datatracker.ietf.org/doc/html/rfc8288#section-3.1

https://datatracker.ietf.org/doc/html/rfc3986#section-5

### Steps to reproduce the issue

`ogrinfo OAPIF:https://maps.gnosis.earth/ogcapi/collections/Daraa:HydrographySrf/`

### Versions and provenance

Ubuntu 22.04.4 LTS
GDAL - built from master branch on 11/07/2024

**Comment by rouault** [comment]
@doublebyte1 @jerstlouis  The driver actually tries to resolve relative links, but it is confused, thinking the base URI is https://maps.gnosis.earth/ogcapi, and then concatenating to it values like "/ogcapi/api?f=json" returned from "https://maps.gnosis.earth/ogcapi"
Reading https://datatracker.ietf.org/doc/html/rfc3986#section-5 is far from being crystal clear to me what is supposed to be the base URI.
I assume that it should be the {root } described at "Figure 2 — Example URI and Components" of https://docs.ogc.org/is/19-072/19-072.html#_6805d238-a16a-4b2c-9cfa-d0551bf25587 ?
Some clarification could be welcome

**Comment by doublebyte1** [comment]
@rouault we created a PR that partially addresses this: https://github.com/OSGeo/gdal/pull/10412

**Comment by jerstlouis** [comment]
@rouault Essentially I believe it should behave exactly like an HTML page with a `<a href='...'>` link.

My understanding is that a URL staring with:
- `/` goes back to the root of the domain
- `./` keep the link's context and adds the rest
- `../` removes the last URL path part and adds the rest
- `../../` removes two URL path parts up to the root of the domain and adds the rest
