### ISSUE TITLE
Raster blocks are shifted after warping

### ISSUE THREAD

**Issue by drnextgis** [OSGeo/gdal#1044]
I try to transform raster from EPSG:32721 to EPSG:3857 with gdalwarp:

```
gdalwarp -t_srs epsg:3857 T21JVF_20171225T135059_B02.jp2 output.tif
```
If open original image and transformed one in QGIS you can see that blocks of transformed raster are shifted:

![peek 2018-10-23 13-18](https://user-images.githubusercontent.com/866124/47357091-20fb2a00-d6c6-11e8-8e18-3cc55bd64a93.gif)

Is it expected behavior?

If open original raster in QGIS and enable on the fly transformation to Web Mercator then I don't see such artifacts.

**Comment by rouault** [comment]
This might be due to nearest resampling. Try with -r cubic

**Comment by drnextgis** [comment]
With `cubic` I don't see these artifacts as in the first image but raster became more smoother.
![peek 2018-10-23 18-00](https://user-images.githubusercontent.com/866124/47374294-e311fc00-d6ed-11e8-90e4-66d142d59b16.gif)

I'm wondering if it is possible to get the same result as with QGIS OTF.

**Comment by rouault** [comment]
Try other resampling kernels. Perhaps -r average or -r bilinear
