### ISSUE TITLE
`gdaladdo -clean` doesn't remove bitmasks

### ISSUE THREAD

**Issue by normanb** [OSGeo/gdal#1047]
## Expected behavior and actual behavior.

I expect to be able to add overviews to a file with a bitmask and then when `cleaning` the same file for the overviews and the overview bitmasks to be removed. The overviews are removed but the bitmasks remain.

I might get to this, just making a note of the issue.

## Steps to reproduce the problem.

Use this file locally - https://github.com/OSGeo/gdal/blob/master/autotest/gcore/data/ycbcr_with_mask.tif

Add overviews

`gdaladdo ycbcr_with_mask.tif`

Remove the overviews;

`gdaladdo -clean ycbcr_with_mask.tif`

Confirm with `gdalinfo` that the file no longer has overviews.

However using `tiffinfo` the additional overview bitmasks image file directories are still there. The overview data IFD has been removed

```
TIFF Directory at offset 0x82ce (33486)
  Image Width: 467 Image Length: 331
  Tile Width: 256 Tile Length: 256
  Bits/Sample: 8
  Sample Format: unsigned integer
  Compression Scheme: JPEG
  Photometric Interpretation: YCbCr
  Samples/Pixel: 3
  Planar Configuration: single image plane
  Tag 33550: 42323.193236,42323.193236,0.000000
  Tag 33922: 0.000000,0.000000,0.000000,-9906393.656047,4582094.717002,0.000000
  Tag 34735: 1,1,0,19,1024,0,1,1,1025,0,1,1,1026,34737,8,0,2048,0,1,32767,2049,34737,72,8,2050,0,1,32767,2054,0,1,9102,2056,0,1,32767,2057,34736,1,4,2059,34736,1,5,2061,34736,1,6,3072,0,1,32767,3074,0,1,32767,3075,0,1,12,3076,0,1,9001,3082,34736,1,2,3083,34736,1,3,3088,34736,1,1,3089,34736,1,0,0,0,0,0
  Tag 34736: 49.000000,2.000000,0.000000,0.000000,6378137.000000,298.257224,0.000000
  Tag 34737: unnamed|GCS Name = WGS 84|Datum = unknown|Ellipsoid = WGS84|Primem = Greenwich||
  JPEG Tables: (574 bytes)
TIFF Directory at offset 0x280 (640)
  Subfile Type: transparency mask (4 = 0x4)
  Image Width: 467 Image Length: 331
  Tile Width: 256 Tile Length: 256
  Bits/Sample: 1
  Sample Format: unsigned integer
  Compression Scheme: Deflate
  Photometric Interpretation: transparency mask
  Samples/Pixel: 1
  Planar Configuration: single image plane
TIFF Directory at offset 0x900a (36874)
  Subfile Type: reduced-resolution image/transparency mask (5 = 0x5)
  Image Width: 234 Image Length: 166
  Tile Width: 128 Tile Length: 128
  Bits/Sample: 1
  Sample Format: unsigned integer
  Compression Scheme: AdobeDeflate
  Photometric Interpretation: transparency mask
  Samples/Pixel: 1
  Planar Configuration: single image plane
  Predictor: none 1 (0x1)
```
## Operating system

Mac

## GDAL version and provenance

Master

**Comment by jratike80** [comment]
That is undirectly documented in https://www.gdal.org/gdaladdo.html

> For internal GeoTIFF overviews (or external overviews in GeoTIFF format), note that -clean does not shrink the file. A later run of gdaladdo with overview levels will cause the file to be expanded, rather than reusing the space of the previously deleted overviews. If you just want to change the resampling method on a file that already has overviews computed, you don't need to clean the existing overviews.

**Comment by rouault** [comment]
@jratike80 : @normanb was talking about 'logically' deleting the mask overviews (ie to remove the link to them in the TIFF chaining of IFD), which is not done currently. Physically deleting and recovering the space is another (much more involved) topic.
