### ISSUE TITLE
gdal.VectorTranslate: "No such file or directory" when converting from PostgreSQL

### ISSUE THREAD

**Issue by johntruckenbrodt** [OSGeo/gdal#10470]
### What is the bug?

Hello,  
With GDAL 3.9.1 I cannot extract PostgreSQL tables using `gdal.VectorTranslate`. I get the following error:
```python
Traceback (most recent call last):
    gdal.VectorTranslate(destNameOrDestDS=dst, srcDS=src,
  File "site-packages\osgeo\gdal.py", line 1552, in VectorTranslate
    srcDS = OpenEx(srcDS, gdalconst.OF_VECTOR)
  File "site-packages\osgeo\gdal.py", line 8856, in OpenEx
    return _gdal.OpenEx(*args, **kwargs)
RuntimeError: PG:host=localhost user=postgres dbname=test password=XXXXXXX No such file or directory
```

This works fine with GDAL 3.8.5 and the `ogr2ogr` command line tool in GDAL 3.9.1.  
Sorry if I missed that something has changed in the usage. I can't find anything in the release notes.

#### create a new PostgreSQL table

```python
db_host = 'localhost'
db_name = 'test'
db_user = 'postgres'
db_password = 'pgpass'

conn = psycopg2.connect(
    host=db_host,
    database=db_name,
    user=db_user,
    password=db_password
)
cur = conn.cursor()

ring = ogr.Geometry(ogr.wkbLinearRing)
ring.AddPoint(0.0, 0.0)
ring.AddPoint(1.0, 0.0)
ring.AddPoint(1.0, 1.0)
ring.AddPoint(0.0, 1.0)
ring.AddPoint(0.0, 0.0)

polygon = ogr.Geometry(ogr.wkbPolygon)
polygon.AddGeometry(ring)
polygon.FlattenTo2D()

polygon_wkt = polygon.ExportToWkt()

cur.execute("""
    CREATE TABLE IF NOT EXISTS polygons (
        id SERIAL PRIMARY KEY,
        geom GEOMETRY(POLYGON, 4326)
    )
""")

cur.execute("""
    INSERT INTO polygons (geom)
    VALUES (ST_GeomFromText(%s, 4326))
""", (polygon_wkt,))

conn.commit()
cur.close()
conn.close()
```

#### convert the table to GPKG:
```python
src = f'PG:host={db_host} dbname={db_name} user={db_user} password={db_password}'
dst = 'polygon.gpkg'
gdal.VectorTranslate(destNameOrDestDS=dst, srcDS=src,
                     format='GPKG',
                     SQLStatement='SELECT * FROM polygons')
```

#### ogr2ogr call tried:
```bash
ogr2ogr -f "GPKG" polygon.gpkg PG:"host=localhost \
user=postgres dbname=test password=pgpass" "polygons"
```

### Versions and provenance

Windows 10  
GDAL 3.9.1

**Comment by rouault** [comment]
I cannot reproduce
```python
>>> from osgeo import gdal
>>> gdal.VectorTranslate(destNameOrDestDS='out.gpkg', srcDS='PG:dbname=autotest', format='GPKG', SQLStatement='SELECT * FROM polygons')
/home/even/gdal/gdal/build_cmake/swig/python/osgeo/gdal.py:311: FutureWarning: Neither gdal.UseExceptions() nor gdal.DontUseExceptions() has been explicitly called. In GDAL 4.0, exceptions will be enabled by default.
  warnings.warn(
<osgeo.gdal.Dataset; proxy of <Swig Object of type 'GDALDatasetShadow *' at 0x7f662caa7240> >
>>> 
```

Are you sure your the GDAL used by your GDAL Python bindings has the PostgreSQL driver enabled?
Check the output of ``ogr.GetDriverByName("PostgreSQL")``

**Comment by johntruckenbrodt** [comment]
Hi @rouault thanks for looking into this so quickly.  
Yes, the driver is present (I installed GDAL using mamba).  
Also, I got the same error on GitHub Actions running Ubuntu:  
https://github.com/johntruckenbrodt/pyroSAR/actions/runs/10042910042/job/27754409685#step:10:161
For GDAL <3.9 the CI build and local tests (Windows) succeed.

**Comment by rouault** [comment]
> I installed GDAL using mamba:

aaah ! There have been packaging changes very recently on the GDAL conda forge package. See https://gdal.org/download.html#conda  . 
The ``gdal`` package (python bindings) for >= 3.9.1 now just depends on ``libgdal-core``, whereas in previous versions it depended on ``libgdal``
So in addition to ``gdal``, you need to install either ``libgdal-pg`` (only for >= 3.9.1),  or ``libgdal`` to work with any GDAL version and get all optional drivers

**Comment by johntruckenbrodt** [comment]
This fixes it. Sorry for not providing the installation way from the very start and missing the packaging changes.  
Thank you so much.

**Comment by hobu** [comment]
Following up on this, Quansight made a detailed blog post on the efforts to break apart the GDAL @conda-forge packages https://quansight.com/post/introducing-lightweight-versions-of-gdal-and-pdal/

**Comment by johntruckenbrodt** [comment]
Awesome! Thanks a lot @hobu.
