### ISSUE TITLE
gdalwarp gives lots of wrong empty data when transforming to a coarser resolution

### ISSUE THREAD

**Issue by asaberui1** [OSGeo/gdal#10485]
### What is the bug?

Hello, I found a bug when I transform a SMAP soil moisture data to a coordinate system which is desired. A picture of the original data is attached below, and we can find out that every land pixel is filled with data. 
![original data](https://github.com/user-attachments/assets/fc17ca2e-6d44-457a-801a-bc68230728c3)
However, when I used the gdalwarp command from a Linux shell, the result is not what I wanted (pls see below).
![unexpected data](https://github.com/user-attachments/assets/7957a89b-d2fc-4701-84f0-56dde8f09503)
I am trying to transform the current coordinate system into a north pole stereographic coordinate system, so it shouldn't be missing values everywhere around the center. I would appreciate for your help.   

### Steps to reproduce the issue

Dear developer, you can download the TIFF data from this link.

https://drive.google.com/file/d/1btselfLUDamB5_jmmAUzxUzdXTU0dd0F/view?usp=drive_link

The command specifically I used:
```
gdalwarp -overwrite -t_srs "+proj=stere +lat_0=90.0 +lon_0=-98.0 +lat_ts=45.0 +R=6370000.0" -te -10746000.0 -10746000.0 10746000.0 10746000.0 -tr 108000.0 108000.0 -r average -wo NUM_THREADS=6 -ot Float32 -of netCDF $input temp
```

### Versions and provenance

Operating system info:
```
$ lsb_release -a

LSB Version:    :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.4.1708 (Core)
Release:        7.4.1708
Codename:       Core
```

**Comment by rouault** [comment]
> https://drive.google.com/file/d/1btselfLUDamB5_jmmAUzxUzdXTU0dd0F/view?usp=drive_link

@asaberui1 It lacks access permissions

**Comment by asaberui1** [comment]
> > https://drive.google.com/file/d/1btselfLUDamB5_jmmAUzxUzdXTU0dd0F/view?usp=drive_link
> 
> @asaberui1 It lacks access permissions

https://drive.google.com/file/d/1btselfLUDamB5_jmmAUzxUzdXTU0dd0F/view?usp=sharing

Sorry, I have changed it to public available status. Pls check if you can download them.

**Comment by rouault** [comment]
@asaberui1  What is your GDAL version ? (this is asked in the issue template...). With GDAL 3.9, I get the following result which looks correct to me:

gdalwarp -overwrite -t_srs "+proj=stere +lat_0=90.0 +lon_0=-98.0 +lat_ts=45.0 +R=6370000.0" -te -10746000.0 -10746000.0 10746000.0 10746000.0 -tr 108000.0 108000.0 -r average -wo NUM_THREADS=6 -ot Float32 SMAP_L4_SM_gph_20190301T013000_Vv7032_001_Geophysical_Data.tif out.tif

[out.tif.zip](https://github.com/user-attachments/files/16361943/out.tif.zip)

PNG version with:
gdal_translate out.tif out.png -scale -ot byte

![out](https://github.com/user-attachments/assets/9d91bb78-7a15-4173-b509-0f6ca0399188)

**Comment by asaberui1** [comment]
> @asaberui1 What is your GDAL version ? (this is asked in the issue template...). With GDAL 3.9, I get the following result which looks correct to me:
> 
> gdalwarp -overwrite -t_srs "+proj=stere +lat_0=90.0 +lon_0=-98.0 +lat_ts=45.0 +R=6370000.0" -te -10746000.0 -10746000.0 10746000.0 10746000.0 -tr 108000.0 108000.0 -r average -wo NUM_THREADS=6 -ot Float32 SMAP_L4_SM_gph_20190301T013000_Vv7032_001_Geophysical_Data.tif out.tif
> 
> [out.tif.zip](https://github.com/user-attachments/files/16361943/out.tif.zip)
> 
> PNG version with: gdal_translate out.tif out.png -scale -ot byte
> 
> ![out](https://private-user-images.githubusercontent.com/1192433/351708925-9d91bb78-7a15-4173-b509-0f6ca0399188.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MjM4MTksIm5iZiI6MTcyMTgyMzUxOSwicGF0aCI6Ii8xMTkyNDMzLzM1MTcwODkyNS05ZDkxYmI3OC03YTE1LTQxNzMtYjUwOS0wZjZjYTAzOTkxODgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjRUMTIxODM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzJkODVjZjhkM2Y1NjgyYzJmZTFjZjAyZjI1N2Q0NmQ0ZTgzZWQ3NDNiZGM2MTg2OGFjNDVmMTQ4MDhjYTA0NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Dc_WA_iJxMEYxHI9VT84yp24DX0j9uJwVsh5rD3qTig)

Sorry, sir. I must have missed it before. I am running GDAL with version 3.5.2. Because I'm running it on an online server which I do not have root, I cannot update it myself. Is there anything I can do to fix it? Apology again for the inconvenience caused and thank you for your help.

**Comment by rouault** [comment]
> I cannot update it myself.

perhaps use Docker images (might require root though), or Conda packages (https://gdal.org/download.html#conda) which do not require root access

**Comment by asaberui1** [comment]
Thanks again, sir. I'll try with Conda.
