### ISSUE TITLE
Zarr does not auto-release groups when multidimensional datasets are closed

### ISSUE THREAD

**Issue by eschnett** [OSGeo/gdal#10481]
### What is the bug?

I am creating a Zarr multidimensional dataset that contains a group which contains an mdarray. I find that this dataset is missing the mdarray unless I explicitly release the group, even when I close the dataset. This is not what I expect.

My expectation comes from HDF5 or netCDF: When I close such a file, all data are written, all references pointing to objects in that file become invalid, and no further data can be written to that file. GDAL's netCDF driver seems to behave this way as well.

I also find that I can close the Zarr dataset, and release the group later, and the mdarray contained in that group is only then written into the (already closed) dataset.

### Steps to reproduce the issue

If this behaviour is expected then it should be documented, e.g. near https://gdal.org/user/multidim_raster_data_model.html . If it is unexpected and indeed a bug then I can submit code to reproduce this. (My current code is written in Julia.)

### Versions and provenance

GDAL 3.9.1, released 2024/06/23, distributed as GDAL_jll.jl for Julia

**Comment by rouault** [comment]
> If this behaviour is expected

it is indeed. In the multidim API, underlying files are closed only when all objects potentially pointing to them (groups, arrays, attributes, dimensions) have been released. Their lifetime is not connected with the one of the GDALDataset.
 Agreed that it should be made explicit in the docs

**Comment by rouault** [comment]
Doc addition in https://github.com/OSGeo/gdal/pull/10490

> Is there a way to flush a dataset, i.e. to ensure all its data are written out even when some objects pointing into it have not yet been released?

no, and that wouldn't be likely easy to implement at that point
