### ISSUE TITLE
OGRPgDatasource: Databases with geometry type OID  not representable as  int32 (>2147483647) not supported

### ISSUE THREAD

**Issue by giorgiomugnaini1974** [OSGeo/gdal#10486]
### What is the bug?

When a Postgres database has a geometry type withy OID> 2147483647, OGRFeature::GetGeometryRef() always returns NULL.

The reason is  the line:
   **nGeometryOID = atoi(pszOid);**
in the following piece of code in ogrdatasource.cpp https://github.com/OSGeo/gdal/blob/31228577df01394c844b09612ca3aa842c72570a/ogr/ogrsf_frmts/pg/ogrpgdatasource.cpp#L823

```  
 if( hResult && PQresultStatus(hResult) == PGRES_TUPLES_OK
        && PQntuples(hResult) > 0  && CPLTestBool(CPLGetConfigOption("PG_USE_POSTGIS", "YES")))
    {
        for( int iRecord = 0; iRecord < PQntuples(hResult); iRecord++ )
        {
            const char *pszOid = PQgetvalue(hResult, iRecord, 0);
            const char *pszTypname = PQgetvalue(hResult, iRecord, 1);
            if( EQUAL(pszTypname, "geometry") )
            {
                bHavePostGIS = TRUE;
                nGeometryOID = atoi(pszOid);
            }
            else if( CPLTestBool(CPLGetConfigOption("PG_USE_GEOGRAPHY", "YES")) )
            {
                bHaveGeography = TRUE;
                nGeographyOID = atoi(pszOid);
            }
        }
    }
```

Indeed, when oid > INT_MAX the behaviour of atoi() is undefined. 
In particular, for Win32 in this case atoi() returns INT_MAX.
This fact causes the failure of this test in ogrpglayer.cpp ,https://github.com/OSGeo/gdal/blob/31228577df01394c844b09612ca3aa842c72570a/ogr/ogrsf_frmts/pg/ogrpglayer.cpp#L2182

```  
      else if( (iGeomFuncPrefix =
                    OGRPGIsKnownGeomFuncPrefix(oField.GetNameRef())) >= 0 ||
                 nTypeOID == poDS->GetGeometryOID()  ||
                 nTypeOID == poDS->GetGeographyOID()  )
        {
            OGRPGGeomFieldDefn* poGeomFieldDefn =
                new OGRPGGeomFieldDefn(this, oField.GetNameRef());
```

### 

### Steps to reproduce the issue

A server with a Db having OID of geometry type > 2147483647 = 2^31-1 WHICH IS LEGAL, being < 2^32-1, the max allowed OID in postgres.

### Versions and provenance

Windows,  any GDAL version?

**Comment by rouault** [comment]
> A server with a Db having OID of geometry type > 2147483647

@giorgiomugnaini1974  what is the value on your server ? From what I can see, OID is limited to be a 32 bit unsigned integer, so values up to 4294967295

**Comment by giorgiomugnaini1974** [comment]
> > A server with a Db having OID of geometry type > 2147483647
> 
> @giorgiomugnaini1974 what is the value on your server ? From what I can see, OID is limited to be a 32 bit unsigned integer, so values up to 4294967295

we observe:

next_oid=2555619139
