### ISSUE TITLE
Check for invalid Well-known text representation of geometry

### ISSUE THREAD

**Issue by jidanni** [OSGeo/gdal#10496]
### Feature description

Maybe these should produce error messages.
```
WKT,Name
"POINT (1)",1
"POINT (1 2 3)","3 need POINT Z"
"POINT (1 2 3 4)",4
"POINT (1 2 3 4 5)",5
"LINESTRING (1 2, 3 4 5 6, 7 8)",A

### Additional context

LIBKML makes odd KML from them.

**Comment by rouault** [comment]
> LIBKML makes odd KML from them.

can you be more explict about what's odd? The only thing that could/should be improve is an error message on "POINT (1)".
For the rest things behave as expected, as KML requires x,y,z and drops the M (4th) component

**Comment by jidanni** [comment]
All I know is if in https://en.wikipedia.org/wiki/Well-known_text_representation_of_geometry
a comma went missing,

> LINESTRING (30 10, 10 30, 40 40, ...)

became

> LINESTRING (30 10, 10 30 40 40, ...)

Then there is/was no way to catch it...
