### ISSUE TITLE
STRMHGT driver: Add higher resolution(s)

### ISSUE THREAD

**Issue by SaschaTrowitzsch** [OSGeo/gdal#10514]
### Feature description

When using the SRTMHGT driver for transforming/warping/... then the output is limited to 3601 rows/cols.
Ref.: https://github.com/OSGeo/gdal/blob/d4fd6215fc9652fe39aa2a64ccd1b0978079d48a/frmts/srtmhgt/srtmhgtdataset.cpp#L429
Although this is related to the SRTM standards I'd like this to be extended to 7201*7201 for a 0.5" grid resolution.
Any reason why this should not be implemented?

**Comment by rouault** [comment]
> Any reason why this should not be implemented?

why extend the SRTM driver for something "not official" (if I understand well your need), and not use a general purpose format like GeoTIFF or whatever? The SRTM driver is just to read public products that are found widely in the wild.

**Comment by SaschaTrowitzsch** [comment]
> why extend the SRTM driver for something "not official" (if I understand well your need), and not use a general purpose format like GeoTIFF or whatever? The SRTM driver is just to read public products that are found widely in the wild.

OK, takes a bit longer to explain: There are many applications that just download SRTM data to e.g. calculate the elevations of tracks. One I am involved to is [RouteConverter](https://www.routeconverter.com/). It only reads HGT files and recent also those with a 0.5° resolutuion. A big and wellknown source for them are [Sonnys files](https://sonny.4lima.de/) who assembles and converts them from several open national and regional providers. (Actually only Austria is covered with this 0.5° files.)
I'd like to do this conversion myself as more and more institutions provide high res LIDAR based DEMs. (See IGN RGE ALTI for france.)
But it's a pain to realize that as most GIS apps like QGIS or GlobalMapper rely on GDAL under the hood - and so are not able to save higher resolutions than STRM1. 
So gdaltransform would be the easiest way if it supported 7601^2 grids.

**Comment by rouault** [comment]
can you provide a link to such a 0.5 deg file ?

**Comment by SaschaTrowitzsch** [comment]
A link to the the 0.5 hgt files?
Would be Sonnys folder at [https://bit.ly/dtm-austria-05s-v2](https://bit.ly/dtm-austria-05s-v2)
or also hosted at [https://static.routeconverter.com/sonny/dtm-0.5s/](https://static.routeconverter.com/sonny/dtm-0.5s/)
(I will remove the last link in some days as the downloads are reserved for _RouteConverter_ only.)
