### ISSUE TITLE
COG Driver Regression: Artifacts at tiff border when generating JPEG compressed COG file with Lanczos resampling

### ISSUE THREAD

**Issue by lukas-juschka-pix4d** [OSGeo/gdal#10536]
### What is the bug?

When generating a COG file from a GeoTiff that has no overviews, while using Lanczos resampling and JPEG compression, GDAL produces artifacts at the border of the tiff. Only the generated overviews are affected, the base layer shows no artifacts. The artifacts are more clearly visible the more overview levels are generated. The tested GeoTiffs have an alpha band.

Examples zoomed in on the affected overviews:
From the attached examples:
![image](https://github.com/user-attachments/assets/be9af231-1a47-480b-9139-536fdbfc1eab)
Stronger artifacts from a larger tiff:
![image](https://github.com/user-attachments/assets/ee79f2f5-a50f-4f0c-9e86-58bbb2c10f2f)

### Steps to reproduce the issue

* Decompress the attached ZIP
* Run ```gdal_translate -of COG -co COMPRESS=JPEG -co RESAMPLING=LANCZOS initialFile.tiff cog.tiff```
[files.zip](https://github.com/user-attachments/files/16458796/files.zip)

### Versions and provenance

Linux Ubuntu 22.04

Affected versions:
* 3.8.5 (conda)
* 3.9.1 (conda)

Unaffected versions:
* 3.4.1 (Packaged in Ubuntu)

**Comment by scottstanie** [comment]
I'm also seeing artifacts when trying to apply the Lanczos resampling on complex data, but only starting with GDAL 3.5:
Here's an image resulting from `gdal.Translate(..., resampleAlg="lanczos")` on gdal 3.4.3, installed from conda, compared to version 3.5.1.

(the colorbar here is the `np.angle` of the complex data):

![image](https://github.com/user-attachments/assets/67064e8b-092f-49b9-9c9a-d4d680d80a72)

![image](https://github.com/user-attachments/assets/7f811d10-2028-4009-b851-7773c8c925ab)

I also saw this in version 3.6 and 3.7

**Comment by jjimenezshaw** [comment]
@scottstanie Is it happening only with JPEG compression?

**Comment by scottstanie** [comment]
I am not using JPEG, just DEFLATE for CFloat32 data. For me I'm pretty sure it's the Lanczos resampling in gdal translate. Changing that to nearest made the artifacts go away, and in the final zoom there are several checkerboard-like artifacts which look like they're related to a resampling kernel.

**Comment by jjimenezshaw** [comment]
@scottstanie Could you write the full command you run `gdal.Translate(...`? gdal.Translate is doing many things. That could help to narrow the study.

**Comment by jratike80** [comment]
Please, with test data.

**Comment by scottstanie** [comment]
[cropped.tif.zip](https://github.com/user-attachments/files/16512199/cropped.tif.zip)

Let me know if I should make this into a separate issue, since now I'm realizing that 1. there's not JPEG here, and 2. i'm not actually making a COG, just a GTiff:

```python
from osgeo import gdal

# # Actual bounds of the test raster:
# projWin = [708780.0, 3492220.0, 716780.0, 3484220.0]

projWin2 = [708790.0, 3492210.0, 716780.0, 3484220.0]

out_ds_lan = gdal.Translate(
    "translated.tif",
    "cropped.tif",
    projWin=projWin2,
    resampleAlg="lanczos",
)

import numpy as np
import matplotlib.pyplot as plt

fig, ax = plt.subplots()
arr_lan = out_ds_lan.ReadAsArray()
ax.imshow(np.angle(arr_lan), cmap="twilight", interpolation="none")
```


Test raster:
<img width="418" alt="image" src="https://github.com/user-attachments/assets/2de04ae4-7d28-45bc-bd39-4bdf4f0d86b9">

Lanczos translated version:
<img width="418" alt="image" src="https://github.com/user-attachments/assets/fd8a4799-87c4-4b24-8201-f78e4a0bba38">

**Comment by rouault** [comment]
> Let me know if I should make this into a separate issue

@scottstanie Please indeed open a separate issue as it isn't related to the first issue reported in this ticket
