### ISSUE TITLE
Lanczos resampling on complex data causes artifacts after GDAL 3.4

### ISSUE THREAD

**Issue by scottstanie** [OSGeo/gdal#10559]
### What is the bug?

Moved from https://github.com/OSGeo/gdal/issues/10536#issuecomment-2269786210 and https://github.com/OSGeo/gdal/issues/10536#issuecomment-2271535074 

Running `gdal_translate` with `resampleAlg="lanczos"` produces speckle-y artifacts.

### Steps to reproduce the issue

https://github.com/user-attachments/files/16512199/cropped.tif.zip

```python
from osgeo import gdal

# # Actual bounds of the test raster:
# projWin = [708780.0, 3492220.0, 716780.0, 3484220.0]

projWin2 = [708790.0, 3492210.0, 716780.0, 3484220.0]

out_ds_lan = gdal.Translate(
    "translated.tif",
    "cropped.tif",
    projWin=projWin2,
    resampleAlg="lanczos",
)

import numpy as np
import matplotlib.pyplot as plt

fig, ax = plt.subplots()
arr_lan = out_ds_lan.ReadAsArray()
ax.imshow(np.angle(arr_lan), cmap="twilight", interpolation="none")
```

### Versions and provenance

First notied on 3.8.5, installed from conda-forge:
```python
$ gdalinfo --version
GDAL 3.8.5, released 2024/04/02
```

Other versions also installed from conda-forge

### Additional context

First images are linked in the other issue.

I also just tested more resampling algorithms to see which ones look bad when plotting the phase of the complex raster after resampling (again, this it plotting `np.angle` of the CFloat32 raster):

<img width="941" alt="image" src="https://github.com/user-attachments/assets/cbc3eed6-e0ef-420a-b600-d46c2ebf17c9">
(the RMS is expected to be different here, as this is not the right resampling for this type of raster)

Oddly, it looks even worse if I specify the target resolution to be the same as the original image (adding `-tr 40 40`):
![image](https://github.com/user-attachments/assets/91672a9d-af45-4cf8-a924-1e1d570355db)

**Comment by rouault** [comment]
@scottstanie Are you sure there's a regression between 3.4 and following versions?

I've modified your script as below and I get exactly the same file with 3.4 and master:
```python
from osgeo import gdal

# # Actual bounds of the test raster:
# projWin = [708780.0, 3492220.0, 716780.0, 3484220.0]

projWin2 = [708790.0, 3492210.0, 716780.0, 3484220.0]

out_ds_lan = gdal.Translate(
    "translated.tif",
    "cropped.tif",
    projWin=projWin2,
    resampleAlg="lanczos",
)

import numpy as np

arr_lan = out_ds_lan.ReadAsArray()

out_ds = gdal.GetDriverByName("GTiff").Create("out.tif", out_ds_lan.RasterXSize, out_ds_lan.RasterYSize, 1, gdal.GDT_Float32)
out_ds.WriteArray(np.angle(arr_lan))
```

**Comment by scottstanie** [comment]
Hmm I think you're right, I must have had a different test before that didn't show the speckles when I tried GDAL 3.4... I'm seeing the same speckles on GDAL 3.8, 3.4, and 3.3.

Was this already a know issue when attempting Lanczos on complex data? If so I can close this and figure out some other way to do a sinc resample; otherwise, I can remove "Gdal 3.4" from the title

**Comment by piyushrpt** [comment]
Here is a unit-testish test for the resampler that you could try on the same environment that produced the cleaner image. I don't see any regression - tested it from 3.3 onwards.

```
import numpy as np
from osgeo import gdal
import matplotlib.pyplot as plt

# # Actual bounds of the test raster:
# projWin = [708780.0, 3492220.0, 716780.0, 3484220.0]
# copied.tif is a copy of cropped.tif

in_ds = gdal.Open("copied.tif", gdal.GA_Update)
in_arr = in_ds.ReadAsArray()
in_arr.imag = 0
in_arr.real = np.arange(in_ds.RasterYSize)[:, None] *\
          np.ones((1, in_ds.RasterXSize))
# in_arr.real = np.ones((in_ds.RasterYSize, 1)) *\
#     np.arange(in_ds.RasterXSize)[None, :]
in_ds.GetRasterBand(1).WriteArray(in_arr)
in_ds = None


# projWin_qtr = [708790.0, 3492210.0, 716780.0, 3484220.0]
# projWin_same = [708780.0, 3492220.0, 716780.0, 3484220.0]
# projWin_half = [708800.0, 3492200.0, 716780.0, 3484220.0]
# projWin_tenth = [708784.0, 3492224.0, 716780.0, 3484220.0]

src_projWin =  [708780.0, 3492220.0, 716780.0, 3484220.0]
shifts = np.linspace(0., 1.0, 41)
est_shifts = np.zeros(shifts.shape)


for ind, shift in enumerate(shifts):
    delta = shift * 40
    projWin = [x + delta for x in src_projWin]

    out_ds_lan = gdal.Translate(
        "translated.tif",
        "copied.tif",
        projWin=projWin,
        xRes=40.0,
        yRes=40.0,
        resampleAlg="lanczos",
    )

    arr_lan = out_ds_lan.ReadAsArray()

    est_shifts[ind] = np.median(in_arr.real[95:105, 95:105]
                                - arr_lan.real[95:105, 95:105])
    print(shifts[ind], est_shifts[ind])


    # To test one
    # fig, ax = plt.subplots()
    # im = ax.imshow(in_arr.real - arr_lan.real, cmap="jet", interpolation="none")
    # fig.colorbar(im)
    # plt.show()

plt.figure()
plt.scatter(shifts, est_shifts)
plt.plot([0, 1], [0, 1])
plt.xlabel("Theoretical shifts")
plt.ylabel("Observed shifts")
plt.show()
```

**Comment by piyushrpt** [comment]
Also you have nodata set to `0` on the sample data.  A raster with real values set to zero, will be treated as nodata even if its imaginary values contain valid data.

**Comment by scottstanie** [comment]
> Also you have nodata set to `0` on the sample data. A raster with real values set to zero, will be treated as nodata even if its imaginary values contain valid data.

thanks for the heads up 👍  i did a check changing the nodata to `nan`, and it looks the same for the complex data

Just checking- that unit-ish test is showing that lanczos is working for real data, not complex, right?

**Comment by piyushrpt** [comment]
It works for both real and complex data. Meant to say, there hasn't been a change in behavior in the different versions of GDAL. Feel free to switch real to imag but just remember not to set real value to nodata for the tests.

**Comment by scottstanie** [comment]
I agree that I'm not seeing a change in behavior between GDAL versions, but just making sure that we're on the same page that there is something wrong with the Lanczos translated versions above.

Update- I think this may be an overflow issue: If you load the original `cropped.tif` into numpy, then `np.abs(data).mean()` is 3187.7793. So I tried resetting the amplitudes to 1 with `np.exp( 1j * np.angle(data))`:

```
gdal_calc.py -A cropped.tif --outfile cropped-unit-mag.tif --calc "exp(1j * angle(A))"
gdal_translate -projwin 708790.0 3492210.0 716780.0 3484220.0 -tr 40 40 -r lanczos cropped-unit-mag.tif.tif translated-unit-mag.tif
```

<img width="1451" alt="image" src="https://github.com/user-attachments/assets/426960f0-2b12-490f-a364-eb04e05e595e">
, and the resulting `gdal_translate` (on the right) looks normal and not speckle-y.

**Comment by piyushrpt** [comment]
I'm not noticing significant differences in the translate call you had and 

```
out_ds_lan = gdal.Warp(
    "translated2.tif",
    "cropped.tif",
    dstSRS="EPSG:32613",
    workingType=gdal.GDT_CFloat64,
    resampleAlg="lanczos",
    outputBounds=bnds,
)
```

There are some isolated values but none of a magnitude that stand out

**Comment by scottstanie** [comment]
you're right, "overflow" was wrong and not the reason. As far as I can tell, the GDAL lanczos kernel is matching other similar libraries interpolating the array, and the problem might be my own input data and what I've done to it upstream of the `gdal_translate` call. I'll close the issue unless I find something more concrete that is GDAL-specific
