### ISSUE TITLE
Clean internal overviews but file size not change

### ISSUE THREAD

**Issue by ningfc** [OSGeo/gdal#10551]
### What is the bug?

File size not change after remove internal overviews with command `gdaladdo -clean filename.tif`

### Steps to reproduce the issue

1. Run `gdaladdo -clean filename.tif` from command
2. Check file size , not change. 
3. Then run `gdaladdo filename.tif `
4. Check file size , increased
5. Repeat 1-4, file size will increase every time, but not decrease.

### Versions and provenance

v3.8.3

**Comment by ningfc** [comment]
Oh, thanks. I got it. But do you feel it's weird? 
I think, Allowing to shrink the file size is better.  So I guess gdaladdo doesn't shrink file size, maybe had considered it for some reason. I have an idea, we can add a new command config like -purge to shrink file size.
Now if I want to shrink the file size, I use gdal_translate to export a new file. but it takes expend long time if the file is large.

**Comment by tbonfort** [comment]
if your geotiff is tiled, you should be able to use github.com/airbusgeo/cogger for a very fast rewrite reclaiming space. (the output will be a cog, but a geotiff also nonetheless)

**Comment by jratike80** [comment]
> Oh, thanks. I got it. But do you feel it's weird?

I guess that `gdaladdo -purge` would be as slow as gdal_translate because it would also need to rewrite all the data. As far as I know "clean" just updates the offsets of the image file directories of the overviews.
If you need to remove overviews frequently for example when testing resampling methods, use external overviews.

**Comment by tbonfort** [comment]
I have opened airbusgeo/cogger#13 in order to further support geotiff cleaning with cogger. If you have any other ideas you can add them over there.
