### ISSUE TITLE
Creation options are not propagated with `gdalmdimtranslate`

### ISSUE THREAD

**Issue by normanb** [OSGeo/gdal#10564]
### What is the bug?

As there are over many variables in a multi-dimensional dataset I would expect the creation options to propagate. I am not seeing how I can use through the `arrayspec` parameter - https://gdal.org/programs/gdalmdimtranslate.html#gdalmdimtranslate

### Steps to reproduce the issue

```
gdalmdimtranslate -OF TileDB -CO COMPRESSION=ZSTD -CO COMPRESSION_LEVEL=7 -CO BLOCKXSIZE=1024 -CO BLOCKYSIZE=1024 -CO TILEDB_TIMESTAMP=100 data.grb grib_array
Warning 6: driver TileDB does not support creation option COMPRESSION
Warning 6: driver TileDB does not support creation option COMPRESSION_LEVEL
Warning 6: driver TileDB does not support creation option BLOCKXSIZE
Warning 6: driver TileDB does not support creation option BLOCKYSIZE```


### Versions and provenance

Linux Ubuntu 22.04, GDAL 3.9.0dev-820140b70d

### Additional context

_No response_

**Comment by normanb** [comment]
I reviewed the test suite - https://github.com/OSGeo/gdal/blob/master/autotest/gdrivers/tiledb_multidim.py#L393 but when I check the block sizes were not 1024 but the default 256 and the compression was not set.

**Comment by rouault** [comment]
This is just a usage issue. The -co values accepted by gdalmdimtranslate must be in the MultiDimDatasetCreationOptionList group reported by "gdalinfo --format tiledb", not CreationOptionList which is for the 2D/classic raster size of the driver.

The -co swich of gdalmdimtranslate accepts to pass array creation options (the ones in MultiDimArrayCreationOptionList), if they are prefixed by ``ARRAY:``. And for block size related options, as they depend on the dimensionality of the array, you need to use the ``IF(DIM=2):`` qualifier.

So:

``-of TileDB -co ARRAY:COMPRESSION=ZSTD -co ARRAY:COMPRESSION_LEVEL=7 -co "ARRAY:IF(DIM=2):BLOCKSIZE=1024,1024" -co TILEDB_TIMESTAMP=100``
