### ISSUE TITLE
GDAL Ignores GCPs During Orthorectification with RPC and DEM

### ISSUE THREAD

**Issue by nookaraji** [OSGeo/gdal#10567]
### What is the bug?

When performing orthorectification using GDAL with RPC and DEM, the software does not seem to take into account the Ground Control Points (GCPs) specified. The output does not align with the expected georeferencing based on the provided GCPs. I expected the GCPs to be used to adjust the orthorectified output, but the resulting image appears to be only influenced by the RPC and DEM without any apparent correction based on the GCPs

### Steps to reproduce the issue

1. Prepare an input image with RPC and DEM data.
2. Create a set of GCPs for the input image.
3. Use GDAL to perform orthorectification with the RPC and DEM, including the GCPs in the process.
4. Compare the resulting orthorectified image with the expected result based on the GCPs.

### Versions and provenance

GDAL Version: 3.8.4
Operating System: Windows 10, 64-bit
Software Used: GDAL command-line tools, Python bindings

**Comment by jratike80** [comment]
By reading https://gdal.org/development/rfc/rfc22_rpc.html#rfc-22 I think it is possible to select to use GCPs or to use RPC, but not a combined option "GCP enhanced RPC" (or "RPC enhanced GCP").

I do not know this area well, but I have a feeling that this tutorial https://up42.com/blog/how-to-perform-orthorectification-a-practical-guide is suggesting to use the accurate GCPs for adjusting the RPC.

**Comment by rouault** [comment]
If both RPCs and GCPs are available, RPC is used by default, and GCPs are ignored. You can use the -tps or -order parameters to use GCPs (RPCs will then be ignored)
