### ISSUE TITLE
ogr sqlite driver does not honour -lco LAUNDER=NO

### ISSUE THREAD

**Issue by aledonati** [OSGeo/gdal#1060]
## Expected behavior and actual behavior.
When converting a S57 file to a spatialite db using ogr2ogr and the -lco LAUNDER=NO option, layer names are correctly stored in sqlite_master with the same casing they have in the source data (ex: "LNDARE").
After that, when layers are being read, upon finding a spatialite db, OGRSQLiteDataSource::Open reads layer names from geometry_columns.f_table_name, where names appear to have been laundered, i.e. "LNDARE" has become "lndare". This could be a problem for applications expecting case-sensitive layer names. That's the point of LAUNDER=NO if I get it correctly.

My suggestion for an improvement is to change queries which discover the db schema in OGRSQLiteDataSource::Open, to something like this:

`SELECT sm.name, f_geometry_column,
geometry_type, coord_dimension, srid,
spatial_index_enabled FROM geometry_columns gc
JOIN sqlite_master sm ON LOWER(gc.f_table_name)=LOWER(sm.name)
LIMIT 10000
`
so that the name is returned as it was originally recorded in sqlite_master.
I have not investigated deeply to understand why names are lowercase in geometry_columns regardless the LAUNDER option, which could be the source of the "problem", but probably it's because insertion into geometry_columns is done by the spatialite library itself.

## Steps to reproduce the problem.

Using ogr2ogr and the -lco LAUNDER=NO, convert from a format that has mixed case layer names to spatialite and then read the layers back using ogrinfo -so. The layer names have been made lowercase

## Operating system

Windows 7 SP1 64-bit

## GDAL version and provenance

GDAL 2.2.4 built from source

**Comment by jratike80** [comment]
The geometry_columns table in Spatialite has a trigger
```

CREATE TRIGGER geometry_columns_f_geometry_column_insert
BEFORE INSERT ON 'geometry_columns'
FOR EACH ROW BEGIN
SELECT RAISE(ABORT,'insert on geometry_columns violates constraint: f_geometry_column value must not contain a single quote')
WHERE NEW.f_geometry_column LIKE ('%''%');
SELECT RAISE(ABORT,'insert on geometry_columns violates constraint: 
f_geometry_column value must not contain a double quote')
WHERE NEW.f_geometry_column LIKE ('%"%');
SELECT RAISE(ABORT,'insert on geometry_columns violates constraint: f_geometry_column value must be lower case')
WHERE NEW.f_geometry_column <> lower(NEW.f_geometry_column);
END
```

I believe that the trigger is there for a reason. SQLite itself is rather case-insensitive when it comes to table and column names. For example it is not possible to add column "lndare" if "LNDARE" already exists. Appications using SQLite based data sources (GeoPackage, SpatiaLite, FDO, MBTiles) should not expect that names are case-sensitive.
