### ISSUE TITLE
Add clip_values option to gdal_translate

### ISSUE THREAD

**Issue by j-musial** [OSGeo/gdal#10609]
### Feature description

After gdal_translate -unscale it would be useful to truncate values to a user-specified range per band analogically to the [numpy clip](https://numpy.org/doc/stable/reference/generated/numpy.clip.html) function.

**Comment by rouault** [comment]
We appreciate the suggestion, but this can be done as post processing using gdal_calc using numpy.clip() as mentioned. So I'm going to close this as gdal_translate has already (too) many options

**Comment by j-musial** [comment]
@rouault regarding "... gdal_translate has already (too) many options":

that's why it is like a swiss knife - powerful and capable of doing many things at once. I don't see why many options are bad (see some linux utilities like parallel, jq, sed, awk etc.). Creating intermediate rasters just to clip values using the gdal_calc is not optimal. Especially that gdal_calc requires Python and using only C as in gdal_translate would be much faster.
