### ISSUE TITLE
Support YCbCr in JP2KAK

### ISSUE THREAD

**Issue by IdanAviv89** [OSGeo/gdal#10623]
### Feature description

Hi, 
Is there a way to add the ability to use gdal translate for a raster using the jp2kak driver, using the YCbCr color space ?

**Comment by rouault** [comment]
> Is there a way to add the ability to use gdal translate for a raster using the jp2kak driver, using the YCbCr color space ?

no, enhancement queued for master branch in https://github.com/OSGeo/gdal/pull/10625

**Comment by IdanAviv89** [comment]
Hi, 
Is there a way in gdalinfo to know if YUV/YCbCr was used ?

**Comment by IdanAviv89** [comment]
Great! 
It might be good to consider adding this parameter into the gdalinfo. I think it will make it simpler and more accessible.
