### ISSUE TITLE
galdwarp not populating the COMPOUNDCRS and VERTCRS fields after vertical datum transformation

### ISSUE THREAD

**Issue by XGallagher-NRCan** [OSGeo/gdal#10620]
### What is the bug?

Converting a DTM raster from CGDV28 to CGVD2013 using geoidgrids  results in COMPOUNDCRS , PROJCRS, VERTCRS and VDATUM as "unknown" . Howerver, when comparing the output elevation values with a geodetic tool (GPS-H from Natural Resources Canada), they were properly transformed. In addition, this problem did not appeared when using the URN, which results in  proper information stored in the COMPOUNDCRS , PROJCRS, VERTCRS and VDATUM fields. 

The issue was also observed when using both local and CDN hosted grids by switching the environment variable PROJ_NETWORK =ON/OFF, and making sure that the geoidgrids where located in the correct PROJ_DATA environment variable folder. 

### Steps to reproduce the issue

# Accessible raster in CGVD28 

https://diffusion.mffp.gouv.qc.ca/Diffusion/DonneeGratuite/Foret/IMAGERIE/Produits_derives_LiDAR/31I/31I06NO/MNT_31I06NO.tif
# gdalwarp command

gdalwarp path/to/rasters/CGVD28/MNT_31I06NO.tif ^
path/to/rasters/transform_CGVD2013/MNT_31I06NO_cgvd2013.tif  ^
-s_srs "+init=EPSG:2950 +geoidgrids=ca_nrc_HT2_1997.tif" ^
-t_srs "+init=EPSG:2950 +geoidgrids=ca_nrc_CGG2013an83.tif"

# gdalinfo output

Size is 19239, 13931
Coordinate System is:
COMPOUNDCRS["unknown",
    PROJCRS["unknown",
        BASEGEOGCRS["unknown",
            DATUM["Unknown based on GRS 1980 ellipsoid",
                ELLIPSOID["GRS 1980",6378137,298.257222101004,
                    LENGTHUNIT["metre",1],
                    ID["EPSG",7019]]],
            PRIMEM["Greenwich",0,
                ANGLEUNIT["degree",0.0174532925199433,
                    ID["EPSG",9122]]]],
        CONVERSION["unnamed",
            METHOD["Transverse Mercator",
                ID["EPSG",9807]],
            PARAMETER["Latitude of natural origin",0,
                ANGLEUNIT["degree",0.0174532925199433],
                ID["EPSG",8801]],
            PARAMETER["Longitude of natural origin",-79.5,
                ANGLEUNIT["degree",0.0174532925199433],
                ID["EPSG",8802]],
            PARAMETER["Scale factor at natural origin",0.9999,
                SCALEUNIT["unity",1],
                ID["EPSG",8805]],
            PARAMETER["False easting",304800,
                LENGTHUNIT["metre",1],
                ID["EPSG",8806]],
            PARAMETER["False northing",0,
                LENGTHUNIT["metre",1],
                ID["EPSG",8807]]],
        CS[Cartesian,2],
            AXIS["easting",east,
                ORDER[1],
                LENGTHUNIT["metre",1,
                    ID["EPSG",9001]]],
            AXIS["northing",north,
                ORDER[2],
                LENGTHUNIT["metre",1,
                    ID["EPSG",9001]]]],
    VERTCRS["unknown",
        VDATUM["Unknown_height_system_(Intl_feet)"],
        CS[vertical,1],
            AXIS["up",up,
                LENGTHUNIT["metre",1,
                    ID["EPSG",9001]]]]]
Data axis to CRS axis mapping: 1,2,3
Origin = (304797.000000000000000,5151182.000000000000000)
Pixel Size = (1.000000000000000,-1.000000000000000)
Metadata:
  AREA_OR_POINT=Area
Image Structure Metadata:
  INTERLEAVE=BAND
Corner Coordinates:
Upper Left  (  304797.000, 5151182.000) ( 79d30' 0.14"W, 46d30' 1.07"N)
Lower Left  (  304797.000, 5137251.000) ( 79d30' 0.14"W, 46d22'29.86"N)
Upper Right (  324036.000, 5151182.000) ( 79d14'57.78"W, 46d30' 0.08"N)
Lower Right (  324036.000, 5137251.000) ( 79d14'59.85"W, 46d22'28.88"N)
Center      (  314416.500, 5144216.500) ( 79d22'29.48"W, 46d26'15.22"N)
Band 1 Block=19239x1 Type=Float32, ColorInterp=Gray
  Description = MNS
  NoData Value=-9999
  Unit Type: metre

# With URN
# reprojection to UTM zone 18 CGVD2013
gdalwarp path/to/raster/CGVD28/MNT_31I06NO.tif ^
path/to/rasters/transform_CGVD2013/MNT_31I06NO_cgvd2013_URN.tif ^
-s_srs "urn:ogc:def:coordinateMetadata:NRCAN::NAD83_CSRS_1997_MTM8_HT2_1997" ^
-t_srs "urn:ogc:def:coordinateMetadata:NRCAN::NAD83_CSRS_1997_UTM18 _CGVD2013_1997"

# gdalinfo output
Size is 19500, 14293
Coordinate System is:
COMPOUNDCRS["NAD83(CSRS)v7 / UTM zone 18 + CGVD2013a(1997) height",
    PROJCRS["NAD83(CSRS)v7 / UTM zone 18 + CGVD2013a(1997) height",
        BASEGEOGCRS["NAD83(CSRS)v7",
            DATUM["North American Datum of 1983 (CSRS) version 7",
                ELLIPSOID["GRS 1980",6378137,298.257222101,
                    LENGTHUNIT["metre",1]],
                ID["EPSG",1198]],
            PRIMEM["Greenwich",0,
                ANGLEUNIT["degree",0.0174532925199433,
                    ID["EPSG",9122]]]],
        CONVERSION["UTM zone 18N",
            METHOD["Transverse Mercator",
                ID["EPSG",9807]],
            PARAMETER["Latitude of natural origin",0,
                ANGLEUNIT["degree",0.0174532925199433],
                ID["EPSG",8801]],
            PARAMETER["Longitude of natural origin",-75,
                ANGLEUNIT["degree",0.0174532925199433],
                ID["EPSG",8802]],
            PARAMETER["Scale factor at natural origin",0.9996,
                SCALEUNIT["unity",1],
                ID["EPSG",8805]],
            PARAMETER["False easting",500000,
                LENGTHUNIT["metre",1],
                ID["EPSG",8806]],
            PARAMETER["False northing",0,
                LENGTHUNIT["metre",1],
                ID["EPSG",8807]],
            ID["EPSG",16018]],
        CS[Cartesian,2],
            AXIS["easting",east,
                ORDER[1],
                LENGTHUNIT["metre",1,
                    ID["EPSG",9001]]],
            AXIS["northing",north,
                ORDER[2],
                LENGTHUNIT["metre",1,
                    ID["EPSG",9001]]]],
    VERTCRS["CGVD2013a(1997) height",
        VDATUM["Canadian Geodetic Vertical Datum of 2013 (CGG2013a) epoch 1997"],
        CS[vertical,1],
            AXIS["gravity-related height",up,
                LENGTHUNIT["metre",1]],
        ID["EPSG",20035]]]
Data axis to CRS axis mapping: 1,2,3
Coordinate epoch: 1997.
Origin = (615093.534277777886018,5151094.761579223908484)
Pixel Size = (0.999890443843813,-0.999890443843813)
Metadata:
  DataType=Generic
  AREA_OR_POINT=Area
Image Structure Metadata:
  INTERLEAVE=BAND
Corner Coordinates:
Upper Left  (  615093.534, 5151094.762) ( 73d29'59.82"W, 46d30'12.91"N)
Lower Left  (  615093.534, 5136803.327) ( 73d30'12.51"W, 46d22'30.04"N)
Upper Right (  634591.398, 5151094.762) ( 73d14'45.38"W, 46d29'59.89"N)
Lower Right (  634591.398, 5136803.327) ( 73d15' 0.22"W, 46d22'17.09"N)
Center      (  624842.466, 5143949.045) ( 73d22'29.47"W, 46d26'15.24"N)
Band 1 Block=19500x1 Type=Float32, ColorInterp=Gray
  NoData Value=-9999
  Unit Type: metre
  Metadata:
    RepresentationType=ATHEMATIC

### Versions and provenance

Windows 10

python                 3.12.4         h889d299_0_cpython    conda-forge
gdal                     3.9.0           py312h7090a6d_7    conda-forge (GDAL 3.9.0, released 2024/05/07)
proj                      9.4.1           hd9569ee_0    conda-forge

**Comment by jsmoreau** [comment]
I also have the same issue..
@rouault Is this format (+init=EPSG:2950 +geoidgrids=ca_nrc_HT2_1997.tif) deprecated in recent versions of GDAL/PROJ? Could that explain the result?

**Comment by rouault** [comment]
> Is this format (+init=EPSG:2950 +geoidgrids=ca_nrc_HT2_1997.tif) deprecated in recent versions of GDAL/PROJ?

yes, but more fundamentally adding a modifier such as +geoidgrids is enough for PROJ to consider that the original CRS (EPSG:2950) might be modified.
Here the best thing to do is to use "gdal_edit -a_srs EPSG:2950 out.tif" to set the SRS to what you want
