### ISSUE TITLE
Bug with method GetStyleString()

### ISSUE THREAD

**Issue by neophammdc** [OSGeo/gdal#10630]
### What is the bug?

Bug with method GetStyleString()

### Steps to reproduce the issue

I use GDAL 3.9.2 with JAVA to read DGN v7 data, but get error when calling org.gdal.ogr.Feature.GetStyleString() function due to CHARSET WINDOW-1252 encoding.
I think maybe need to add function like org.gdal.ogr.Feature.GetStyleAsBinary()
Is this possible? Thanks a lot

### Versions and provenance

Build on Ubuntu 22.04 with GDAL 3.9.2

### Additional context

Java Android

**Comment by rouault** [comment]
@neophammdc Please attach such DGN file (in a .zip)

**Comment by neophammdc** [comment]
Hi @rouault, please attach DGN v7 sample file
[DGN_v7_Sample.zip](https://github.com/user-attachments/files/16743745/DGN_v7_Sample.zip)
