### ISSUE TITLE
PDFium since chromium/6618 has renamed headers

### ISSUE THREAD

**Issue by dotysan** [OSGeo/gdal#10632]
### What is the bug?

For example in [here](https://pdfium.googlesource.com/pdfium/+/e74e4307f7b822f6e99f985c3bae326457d7b5dc) `core/fxge/agg/fx_agg_driver.h` was renamed to `core/fxge/agg/cfx_agg_devicedriver.h`.

But gdal is still looking for the [old file](https://github.com/dotysan/gdal/blob/30eaea39c5ac180e4d9bc23b727c1040613c035f/frmts/pdf/pdfsdk_headers_pdfium.h#L77).

### Steps to reproduce the issue

Run `cmake -DGDAL_USE_PDFIUM=ON` against any build after that change.

### Versions and provenance

master

**Comment by pjonsson** [comment]
@rouault I'm hitting this build error when standing in `docker/` on latest master and running `ubuntu-full/build.sh --release --gdal v3.9.2 --proj master --platform linux/amd64 --tag 3.9.2`. I don't think it's my computer/environment, I can build the small image just fine with the same command. Does the fix need to be backported into 3.9.3 as well?

**Comment by rouault** [comment]
The GDAL 3.9 branch must be built against https://github.com/rouault/pdfium_build_gdal_3_9/
If you want to build it against https://github.com/rouault/pdfium_build_gdal_3_10, you'll have to backport changes in the PDF driver itself, but I won't do that myself
