### ISSUE TITLE
`BAND_NAMES` creation option of `netcdf` driver works with `Create()` interface only, and not with `CreateCopy()`

### ISSUE THREAD

**Issue by arkanoid87** [OSGeo/gdal#10646]
### What is the bug?

I found that `BAND_NAMES` option is not working when passed to `gdal_translate`.
Received help from community showing that it does work with `gdalwarp` so it seems a `Create()` vs `CreateCopy()` issue.

### Steps to reproduce the issue

gdal_translate -co BAND_NAMES=foo,bar input.tif outout.nc

### Versions and provenance

GDAL 3.9.1, released 2024/06/23
self-built

**Comment by jratike80** [comment]
Confirmed with GDAL 3.10

```
gdal_translate -of NetCDF -co band_names=foo,bar,baz p4433h.tif p4433h.nc
  SUBDATASET_1_NAME=NETCDF:"p4433h.nc":Band1
```

```
gdalwarp -of NetCDF -co band_names=foo,bar,baz p4433h.tif p4433h2.nc
  SUBDATASET_1_NAME=NETCDF:"p4433h2.nc":foo
```
