### ISSUE TITLE
GDAL.NET: GDALTranslateOptions Unknown option name -srcwin

### ISSUE THREAD

**Issue by CarstenL** [OSGeo/gdal#1066]
## Expected behavior and actual behavior.
I have a huge GeoTiff file, which i have to split in smaller tiles (10000 x 10000 pixel).
I tried it with gdal_translate and the -srcwin paramter via commandline and it works fine.
But when i tried it via GDAL.NET nuget package, i get this exception:
'Unknown option name '-srcwin''

## Steps to reproduce the problem.

Commandline:
`gdal_translate -of GTiff -srcwin 0 0 10000 10000 "D:\Temp\input.tif" "D:\Temp\output_0_0.tif"`

C# code:
var inputFile = @"D:\Temp\input.tif";
var outputPath = @"D:\Temp\";
var tileSizeX = 10000;
var tileSizeY = 10000;

var ds = Gdal.Open(inputFile, Access.GA_ReadOnly);
var band = ds.GetRasterBand(1);
//get raster size
var xSize = band.XSize;
var ySize = band.YSize;
int counterX = 0, counterY = 0;
for (int i = 0; i <= xSize; i = i + tileSizeX)
{
	counterY = 0;
	for (int j = 0; j <= ySize; j = j + tileSizeY)
	{
		var opt = new string[] {
			"-of", "GTiff",
			"-srcwin", $"{i} {j} {tileSizeX} {tileSizeY}"
		};

		var options = new GDALTranslateOptions(opt); //this line generate the exception!
		var outputDS = Gdal.wrapper_GDALTranslate(Path.Combine(outputPath, $"RAS_IMG_{counterX.ToString()}_{counterY.ToString()}.tif"), ds, options, (Gdal.GDALProgressFuncDelegate)progressDelegate, "Raster Tiler");
		outputDS.FlushCache();
		outputDS.Dispose();

		counterY++;
	}
	counterX++;
}

## Operating system

Windows 10 64bit

## GDAL version and provenance

2.3.1 x64 for commandline
[https://www.nuget.org/packages/GDAL.NET/2.3.1](https://www.nuget.org/packages/GDAL.NET/2.3.1) for C#

Or is there a similar way to generate small tiles by pixel?

**Comment by nenukonta** [comment]
Oh my God.. I just received an email and I have no idea of what is being discussed here.

**Comment by Gigas002** [comment]
This should be an answer to your question. The thing is to pass each variable for stcwin in separate quotes.

var opt = new string[] {
“-of”, “GTiff”, “-srcwin”, $”{i}”, $”j”, $”{tileSizeX}”, $”tileSizeY” };

**Comment by CarstenL** [comment]
> This should be an answer to your question. The thing is to pass each variable for srcwin in separate quotes.
> 
> ```
> var opt = new string[] {
> “-of”, “GTiff”, “-srcwin”, $”{i}”, $”{j}”, $”{tileSizeX}”, $”{tileSizeY}” };
> ```

Oh my god, the mistake was too easy to see it myself.
The error message may be confusing.
Thanks Gigas!
