### ISSUE TITLE
ogrmerge doesn't like special chars in filename (OSGeo4W)

### ISSUE THREAD

**Issue by tobwen** [OSGeo/gdal#1067]
## Expected behavior and actual behavior.
I expected to be able to merge any geospatial file with a filename supported by my OS and filesystem using ogrmerge, but ogrmerge/python returns with an error message instead.

```G:\>ogrmerge.bat -o demo.gpkg *.geojson
Traceback (most recent call last):
  File "C:\OSGEO4~1\bin\ogrmerge.py", line 596, in <module>
    sys.exit(main())
  File "C:\OSGEO4~1\bin\ogrmerge.py", line 592, in main
    return process(argv[1:])
  File "C:\OSGEO4~1\bin\ogrmerge.py", line 534, in process
    attrs={'name': layer_name})
  File "C:\OSGEO4~1\bin\ogrmerge.py", line 167, in open_element
    _VSIFPrintfL(self.f, '%s<%s%s>\n' % (self._indent(), name, xml_attrs))
  File "C:\OSGEO4~1\bin\ogrmerge.py", line 120, in _VSIFPrintfL
    gdal.VSIFWriteL(s, 1, len(s), f)
  File "C:\OSGEO4~1\apps\Python27\lib\site-packages\osgeo\gdal.py", line 1478, in VSIFWriteL
    return _gdal.VSIFWriteL(*args)
TypeError: not a string
Warning 1: Memory file /vsimem/_ogrmerge_.vrt deleted with 1 references.
```

## Steps to reproduce the problem.

1.  create some GeoJSONs with some special chars in filename, f.e. German umlauts: "ä, ö, ü": ```hörde.geojson, allgäu.geojson, düsseldorf.geojson```
2.  try to merge them ```ogrmerge.bat -o demo.gpkg *.geojson```

## Operating system
Windows 7 Pro, 64-bit
Windows 10 Pro, 64-bit

## GDAL version and provenance
GDAL 2.3.2, released 2018/09/21 from OSGeo4W

**Comment by rouault** [comment]
Can you try the just updated https://github.com/OSGeo/gdal/blob/master/gdal/swig/python/scripts/ogrmerge.py ?

**Comment by tobwen** [comment]
Tried it, but it got worse:

```Traceback (most recent call last):
  File "./ogrmerge.py", line 611, in <module>
    sys.exit(main())
  File "./ogrmerge.py", line 607, in main
    return process(argv[1:])
  File "./ogrmerge.py", line 499, in process
    src_lyr_name = src_lyr_name.decode('utf-8')
  File "C:\OSGEO4~1\apps\Python27\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xf6 in position 1: invalid start byte
```

**Comment by tobwen** [comment]
Remember, Windows uses UTF-16 little-endian.

**Comment by rouault** [comment]
> Remember, Windows uses UTF-16 little-endian.

That should be irrelevant for Python. And OGR uses utf-8 internally

After "src_lyr_name = src_lyr.GetName()" at line 497, can you insert a new line
```                print(src_lyr_name, type(src_lyr_name))```

**Comment by tobwen** [comment]
```
('h\xf6rde', <type 'str'>)
Traceback (most recent call last):
  File "./ogrmerge.py", line 612, in <module>
    sys.exit(main())
  File "./ogrmerge.py", line 608, in main
    return process(argv[1:])
  File "./ogrmerge.py", line 500, in process
    src_lyr_name = src_lyr_name.decode('utf-8')
  File "C:\OSGEO4~1\apps\Python27\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xf6 in position 1: invalid start byte
```

**Comment by tobwen** [comment]
```
import locale
os_encoding = locale.getpreferredencoding()
print(os_encoding)
```
tells me, my shell is on ```cp1252```, so decoding seems the wrong way around?

**Comment by tobwen** [comment]
I got it working! Gonna release a PR soon.

**Comment by tobwen** [comment]
@rouault Seems like _GeneralCmdLineProcessor_ does some modifications to argv, which makes it impossible to parse single files.

**Comment by tobwen** [comment]
Finally, here is the solution:
```
line 291: src_datasets = [unicode(x, sys.getfilesystemencoding()) for x in glob.glob(arg)]
line 604: args = [unicode(x, sys.getfilesystemencoding()) for x in sys.argv]
```

**Comment by rouault** [comment]
@tobwen Was also going to that conclusion. See https://github.com/OSGeo/gdal/commit/81816bf316a03f75fba348d84daac1416f7c218d that is also Py3 proof

**Comment by tobwen** [comment]
Aren't you missing a ```else:``` in line 610?

It stopped working here with your last patches. Sorry for all the trouble with geoprocessing on Windows.

**Comment by tobwen** [comment]
I think, I'll write my own VRT creating tool in a Perl oder PHP. Python seems too wacky for this.

**Comment by rouault** [comment]
> Aren't you missing a `else:` in line 610?

Why ? In the python 3 case, we should get unicode strings without doing anything

> It stopped working here with your last patches

Is it with Python 2 or Python 3 ? How to reproduce ?

**Comment by tobwen** [comment]
> Is it with Python 2 or Python 3 ?

Python 2, is OSGeo4W's default. 

> How to reproduce ?

I'll create some demo files soon. Need to finish some Leaflet.js work first.

> `writer.write_element_value('SrcLayer', src_lyr.GetName())`

Oh look again ! That's a new problem. This doesn't have to do with the actual filenames, seems like the layer name makes trouble when containing "special chars".
