### ISSUE TITLE
Doc: Move version selection to nagivation bar

### ISSUE THREAD

**Issue by dbaston** [OSGeo/gdal#10680]
### Feature description

Make it easier to notice the version selector by placing it at the bottom of the navigation bar, as is done with the PROJ docs:

![image](https://github.com/user-attachments/assets/56601fd1-75ae-4bc0-8b83-40785206b63e)

**Comment by rouault** [comment]
There have been changes related to that with sphinx-rtd-theme==3.0.0
Cf https://github.com/OSGeo/gdal/pull/10954

**Comment by rouault** [comment]
This issue is solved by setting "flyout_display": "attached" in conf.py (https://github.com/OSGeo/gdal/pull/10959/commits/0bf19955546948de991bcc13024fd372f288b2c4) and by unchecking "Flyout enabled in https://app.readthedocs.org/dashboard/gdal/addons/edit/
