### ISSUE TITLE
gdal docker image of alpine-normal has no pip

### ISSUE THREAD

**Issue by yougistech** [OSGeo/gdal#10715]
### What is the bug?

From the Dockerfile of alpine-normal, i found py3-pip, but when i pull docker images of alpine-normal，the full name of images is [**ghcr.io/osgeo/gdal:alpine-normal-latest**] , and run it, i found there is no pip or pip3, but gdal and python is correct.
is there something wrong? please tell me if i operate not correctly!
If there is no pip surely, can you add it or tell me how to add it.
thank you.

### Steps to reproduce the issue

step1. pull images, ghcr.io/osgeo/gdal:alpine-normal-latest;
step2. run it, docker run -it --rm ghcr.io/osgeo/gdal:alpine-normal-latest;
step3, test python gdal and pip, below is the result:
![image](https://github.com/user-attachments/assets/a21da5c3-b4e4-475b-b823-b19e74d242f2)

### Versions and provenance

CentOS Linux release 7.9.2009 (Core)
GDAL Version：GDAL 3.10.0dev-d1efd4e8b238d3c76d62dd66e65673d3a15c4ee2, released 2024/08/28

### Additional context

i hope get you help， thank you

**Comment by rouault** [comment]
pip is not needed to build the images, so it is not included. You can install it with "apk add py3-pip"
