### ISSUE TITLE
vrt nodata problem with float32 raster

### ISSUE THREAD

**Issue by kyngchaos** [OSGeo/gdal#1071]
## Expected behavior and actual behavior.

When a vrt contains float32 rasters with nodata values (at or near the largest negative float32 value), the nodata overrides any other rasters in the vrt instead of passing through to find valid data in another raster in the vrt.  This is noticeable when the rasters are projected from a latlong tile, so there are slivers of nodata at the edges of each raster tile.

This works correctly in GDAL 2.2.

## Steps to reproduce the problem.

Example: project 2 SRTM tiles to UTM, pick ones near the edge of a UTM zone for exaggeration of the issue, init to and set nodata to -3.4028234663852886e+38. (I got this value from an Esri binary grid, where I first noticed the problem)

gdalwarp options: -ot Float32 -wo "INIT_DEST=-3.4028234663852886e+38" -dstnodata -3.4028234663852886e+38

create a vrt from those projected rasters

convert to geotiff

the geotiff has nodata slivers between the tiles, instead of data values from the adjacent tile for a seamless raster

If the tiles are projected with a nodata value of -32768 (or probably other small negative values), it works correctly.  I tied -3.4028e+38 and that did work, so there appears to be something wrong with -3.4028234663852886e+38 being too close to the max negative value of float32.

## Operating system

macOS 10.12

## GDAL version and provenance

GDAL 2.3.2 compiled from source

**Comment by rouault** [comment]
Can you attach a VRT + sources to easily reproduce the issue ? (presumably that subsetting the sources should be sufficient to demonstrate)

**Comment by kyngchaos** [comment]
[N35E138_UTM54_float.tif.zip](https://github.com/OSGeo/gdal/files/2543512/N35E138_UTM54_float.tif.zip)
[N35E139_UTM54_float.tif.zip](https://github.com/OSGeo/gdal/files/2543514/N35E139_UTM54_float.tif.zip)
[test_float.vrt.zip](https://github.com/OSGeo/gdal/files/2543515/test_float.vrt.zip)

**Comment by kyngchaos** [comment]
[test_float.tif.zip](https://github.com/OSGeo/gdal/files/2543524/test_float.tif.zip)

**Comment by rouault** [comment]
Neither the VRT nor the sources declare nodata value, so it is expected that the VRT cannot detect the nodata slivers

**Comment by kyngchaos** [comment]
[N35E138_UTM54_float.tif.zip](https://github.com/OSGeo/gdal/files/2543901/N35E138_UTM54_float.tif.zip)
[N35E139_UTM54_float.tif.zip](https://github.com/OSGeo/gdal/files/2543902/N35E139_UTM54_float.tif.zip)
[test_float.vrt.zip](https://github.com/OSGeo/gdal/files/2543903/test_float.vrt.zip)
[test_float.tif.zip](https://github.com/OSGeo/gdal/files/2543904/test_float.tif.zip)

Argh, I was trying many possibilities, and uploaded the wrong one.  This should have the problem, checked it before uploading.
