### ISSUE TITLE
ogr2ogr misses some objects in dump from ESRI REST API

### ISSUE THREAD

**Issue by hdrs** [OSGeo/gdal#1073]
## Expected behavior and actual behavior.
I am extracting features from an ESRI REST API and ogr2ogr seems to miss some sometimes. 

If it turns out  I am not doing something very stupid here, this  might be deemed a bug.

## Steps to reproduce the problem.

`APIurl="https://gis.bisclient.com/maps03/rest/services/YoungWeb/MapServer/0"`

This API is a good example.   This curl cmd is a small polygon query that gives a few results:

`curl "$APIurl/query?f=json&where=&returnGeometry=true&spatialRel=esriSpatialRelIntersects&geometry=%7B%22rings%22%3A%5B%5B%5B-10995141.46509607%2C3919279.528139719%5D%2C%5B-10995141.46509607%2C3920027.1778226527%5D%2C%5B-10993156.491017736%2C3920027.1778226527%5D%2C%5B-10993156.491017736%2C3919279.528139719%5D%2C%5B-10995141.46509607%2C3919279.528139719%5D%5D%5D%2C%22spatialReference%22%3A%7B%22wkid%22%3A102100%7D%7D&geometryType=esriGeometryPolygon&inSR=102100&outFields=*&outSR=102100" > resp.json`

Now look for a certain object in there:

`cat  resp.json  | jq '.'  |   fgrep YoungCad.DBO.Parcels.PROP_ID  | fgrep 40023`
`        "YoungCad.DBO.Parcels.PROP_ID": 40023,`

OK, an object exists in that layer with  YoungCad.DBO.Parcels.PROP_ID=40023

Now dump the whole layer with ogr2ogr

`ogr2ogr -f GeoJSON dump_1.json  "$APIurl/query?where=objectid+%3D+objectid&outfields=*&f=json" OGRGeoJSON`

I get lots of objects with field YoungCad.DBO.Parcels.PROP_ID  present, 

`cat dump_1.json   |  jq   '.' |  fgrep YoungCad.DBO.Parcels.PROP_ID  |  wc -l`
`13649`

Now look for PROP_ID=40023 from above. 

`cat dump_1.json   |  jq   '.' |  fgrep YoungCad.DBO.Parcels.PROP_ID  | fgrep 40023 `

Nothing. 

In case the weird extension of OBJECTID they use is messing things up I will try with theirs

`ogr2ogr -f GeoJSON dump_2.json  "$APIurl/query?where=YoungCad.DBO.Parcels.OBJECTID+%3D+YoungCad.DBO.Parcels.OBJECTID&outfields=*&f=json" OGRGeoJSON`

`md5sum  dump_*`
`1c183f894d046167ec9489a45a7dba75  dump_1.json`
`1c183f894d046167ec9489a45a7dba75  dump_2.json`

So that is not the issue. 

The object in question seems valid and fine when I inspect it. No funny characters, clean geometry.

## Operating system

Ubuntu 18.04.1 LTS

## GDAL version and provenance

GDAL 2.2.3  from ubuntu package manager.

**Comment by jratike80** [comment]
I tried this command

`ogr2ogr -f sqlite -dsco spatialite=yes resp_all2.sqlite "https://gis.bisclient.com/maps03/rest/services/YoungWeb/MapServer/0/query?where=objectid+%3D+objectid&outfields=*&f=json" -nlt geometry --config gdal_http_unsafessl true --debug on`

I got 14196 rows into the table but I did not get the feature "YoungCad.DBO.Parcels.PROP_ID":=40023 into SpatiaLite either. It might give some light to read each page of 1000 rows one by one and check the results.

**Comment by rouault** [comment]
OK, the issue is that when using paged requests, the server doesn't return features in a consistent order. So you have to explicitly specified an ordering clause, typically with the objectID, by adding
```&orderByFields=YoungCad.DBO.Parcels.OBJECTID+asc```
