### ISSUE TITLE
gdal2tiles does not allow max zoom >= 19 with leaflet

### ISSUE THREAD

**Issue by mjstevens777** [OSGeo/gdal#1074]
## Expected behavior and actual behavior.

After running gdal2tiles.py with the leaflet viewer, the map does not render at zoom level 19 or above, and just turns grey instead.

## Steps to reproduce the problem.

`gdal2tiles.py -w leaflet -z 15-20 myfile.tif`

The issue is the same as https://github.com/Leaflet/Leaflet/issues/5289. The max zoom level needs to be passed to the `tileLayer`, not just the `map`. I can submit a PR if that would be helpful.

The line in question:
https://github.com/OSGeo/gdal/blob/b6fd449f8a8f3ec96180eb81ded783e0e8309361/gdal/swig/python/scripts/gdal2tiles.py#L2370

## Operating system

Ubuntu 18.04 64 bit

## GDAL version and provenance

2.2.3 version from the built in apt repository

**Comment by rouault** [comment]
Pull request welcome
