### ISSUE TITLE
GDALDataset::CopyLayer does not copy the GeoPackage geometry column name

### ISSUE THREAD

**Issue by kb173** [OSGeo/gdal#10769]
### What is the bug?

We construct new features based on the OGRFeatureDefn of an existing GeoPackage vector layer. We then want to create these features not only in the original layer, but also in a copy of that layer created using `CopyLayer`. This works fine on Linux, but on Windows it fails with:

```
ERROR 1: failed to prepare SQL: UPDATE "our_gis_table" SET "geometry"=? WHERE "fid" = ?
ERROR 1: failed to prepare SQL: INSERT INTO "our_gis_table" ( "fid", "geometry") VALUES (?, ?) - table our_gis_table has no column named geometry
```

It seems to expect the geometry table to be named `geometry`, which is the case in the original layer, but not in the copied layer, where it is named `geom`. Presumably, the column is said to be `geometry` in the feature's OGRFeatureDefn (which we got from the original layer), but this is no longer applicable on the copied layer.

We were able to fix the problem by specifying the geometry column name when calling `CopyLayer`:

```
auto options = CPLStringList();
options.AddString("GEOMETRY_NAME=geometry");
OGRLayer *out_layer = out_dataset->CopyLayer(layer, layer->GetName(), options);
```
(See https://github.com/boku-ilen/geodot-plugin/commit/136211161e35a98482ec3c41428dff7cfa0c2310)

However, this seems like a bug to us: Why is it trying to use the wrong geometry column name? Shouldn't CopyLayer also name the geometry column appropriately?

### Steps to reproduce the issue

This code should be all that's relevant for reproducing the bug. Note that `layer` is a GeoPackage vector layer.

```
OGRFeature *new_feature = new OGRFeature(layer->GetLayerDefn());

GDALDriver *out_driver = (GDALDriver *)GDALGetDriverByName("GPKG");
GDALDataset *out_dataset = out_driver->Create(path.c_str(), 0, 0, 0, GDT_Unknown, nullptr);
OGRLayer *out_layer = out_dataset->CopyLayer(layer, layer->GetName());

out_layer->CreateFeature(new_feature);
```

### Versions and provenance

We encountered the problem on Windows 11 with GDAL 3.8.5, but not Arch Linux with GDAL 3.9.1.

So it could either be caused by the OS or by the GDAL version.

**Comment by rouault** [comment]
I presume this working in GDAL 3.9 is a side-effect of commit 0c92a7fc29b90bd0658e92b9bd5cc206358cf9f7

Closing as fixed in GDAL 3.9
