### ISSUE TITLE
Docs: incorrect display of long lines (using Chrome on Windows 10)

### ISSUE THREAD

**Issue by agiudiceandrea** [OSGeo/gdal#10778]
### What is the bug?

Using Google Chrome 128.0.6613.138 on Windows 10:

![image](https://github.com/user-attachments/assets/5f6c7b3d-6b81-46e7-adcf-3da0cfea2773)

The horizontal scrolling bar is not available.

### Steps to reproduce the issue

Open https://gdal.org/en/latest/drivers/vector/filegdb.html using Google Chrome on Windows 10.

### Versions and provenance

Windows 10 Home 1903 64-bit 10.0.18362 Build 18362.778

**Comment by rouault** [comment]
FWIW, I don't have a horizontal scroll bar on Firefox 130 on Linux, but it does insert line breaks.

**Comment by jratike80** [comment]
The "configuration_keyword" is a single long word. Firefox is splitting the word at `/` and `[` characters but Chrome and Edge only at `[`. This is from Firefox

<img width="309" alt="image" src="https://github.com/user-attachments/assets/f46ba4a0-38b3-45c8-9a7d-be381b63a2a8">

This shows that Edge does split at [ 

<img width="295" alt="image" src="https://github.com/user-attachments/assets/f4d00a46-b925-4786-802e-baa1ab208185">

Could it be possible to configure a list of possible linesplit characters for Chrome?
