### ISSUE TITLE
FileGDB diver: CreateDataSource capability is False but it can actually create datasets and then CreateDataSource becomes True

### ISSUE THREAD

**Issue by agiudiceandrea** [OSGeo/gdal#10783]
### What is the bug?

On Windows 10, GDAL/OGR 3.9.2 (OSGeo4W) with installed the OGR FileGDB driver.

- in the OSGeo4W Shell:
```
ogrinfo --formats | find /I "filegdb"
  OpenFileGDB -raster,vector- (rw+v): ESRI FileGDB (*.gdb)
  FileGDB -vector- (rw+): ESRI FileGDB (*.gdb)
```
- in the Python interpreter (either in the OSGeo4W Shell or the QGIS Python console):
"CreateDataSource" is initially False
```Python
from osgeo import ogr
dr = ogr.GetDriverByName("FileGDB")
print(dr.name, dr.TestCapability("CreateDataSource")) # -> FileGDB False
```
but the FileGDB driver can actually create a DataSource and subsequently "CreateDataSource" becomes True:
```Python
ds = dr.CreateDataSource("C:\\path\\testfgdb.gdb") # the DataSource is actually created
del ds
print(dr.name, dr.TestCapability("CreateDataSource")) # -> FileGDB True
```

I've spotted the issue using QGIS 3.38 / 3.34, since the FileGDB driver is initially not available in the "Save Vector Layer as..." dialog window even if it is installed and enabled in Settings -> Options -> Data Sources -> GDAL -> Vector Drivers (with the "OpenFileGDB" driver disabled)

![image](https://github.com/user-attachments/assets/0cade4d5-c3fd-408d-9169-787917e7d3e2)

but it becomes available if I create a DataSource using Python of using the Browser panel

![image](https://github.com/user-attachments/assets/9573f9a8-3c2a-4a77-a451-e558aa213c7c)

In fact, QGIS uses OGR_Dr_TestCapability( drv, "CreateDataSource" ) in QgsVectorFileWriter::ogrDriverList to create the list of drivers which will populate the "Format" combobox in the ""Save Vector Layer as..." dialog window https://github.com/qgis/QGIS/blob/d4245f074045dba1344b7d085ccfc22692ae0b96/src/core/qgsvectorfilewriter.cpp#L4086

QgsVectorFileWriter::ogrDriverList

### Steps to reproduce the issue

In the description.

### Versions and provenance

GDAL/OGR 3.9.2 OSGeo4W on Windows 10

**Comment by rouault** [comment]
Fixed per https://github.com/OSGeo/gdal/pull/10786 . The issue is related to building the FileGDB driver as a plugin, with the GDAL 3.9 defered driver loading capability

> In fact, QGIS uses OGR_Dr_TestCapability( drv, "CreateDataSource" )

Side nodte: QGIS should migrate away from those OGR_Dr_* legacy API. Maybe we should deprecate them and remove them completely for GDAL 4
