### ISSUE TITLE
RFC73 should be revisited.

### ISSUE THREAD

**Issue by tgis-top** [OSGeo/gdal#10811]
### Feature description

It should be noted that there are naturally two axis orders, they are data axis order and API axis order. Data axis order represents the sequence of fields in the storage where the East, North and the Height coordinates are stored, while API axis order clarifies the exactly API to get the coordinates of East, North and the Height. 

The SDK to access Geographic Data must aware of the Data axis order in order to let the APIs return right value. Since the beginning, X (method getX() , field X and the first coordinate parameter) represents East, Y represents North, and Z represents Height. 

Previously, OGRSpatialReference only defined the coordinate reference systems, that is, the mapping relationship between coordinate values and a point on the earth. OGRSpatialReference did not reflect the data axis order or the API axis order. 

Now we've introduced SRS axis order to OGRSpatialReference. It is therefore important to clarify what it for to do so, to reflect the data axis order or to make API axis order flexible. API axis order is only human-made decision. It doesn't make any difference whether getX() returns the coordinate of the east or the north. It also doesn't make any difference whether the first coordinate parameter represents east or north. Thus, to make API axis order flexible is totally of no use, it just breaks backward compatibility. Unfortunately, at the moment the introduction of SRS axis order only partly make API axis order flexible, that is, the meaning of the parameters of Transform method of OGRCoordinateTransformation are depend on SRS axis order. 

Actually, it was only necessary to make SRS axis order reflect the data axis order. If the SRS contained in the data  do not represent the actual data axis order, providing SetDataAxisMapping() to set the mapping relationship between the sequence of fields in the storage and the East, North and the Height coordinates. And, all APIs about coordinate should be remain untouched.

### Additional context

[RFC73](https://gdal.org/en/latest/development/rfc/rfc73_proj6_wkt2_srsbarn.html)

**Comment by tgis-top** [comment]
SRS axis order should not change any API of GDAL. That's what I'm trying to say.

1. x parameter  can always represent the coordinate in west to east direction
`OGRCoordinateTransformation::Transform (size_t nCount, double *x, double *y, double *z=nullptr, int *pabSuccess=nullptr)`

2. `OGRPoint::getX()` can always return the coordinate in west to east direction

**Comment by tgis-top** [comment]
> I'm sorry. I'm having a hard time to understand what you mean and what you expect...
SRS axis order should not change the behavior any API of GDAL. That's what I'm trying to say.

1. x parameter  can always represent the coordinate in west to east direction
`OGRCoordinateTransformation::Transform (size_t nCount, double *x, double *y, double *z=nullptr, int *pabSuccess=nullptr)`

2. `OGRPoint::getX()` can always return the coordinate in west to east direction

**Comment by rouault** [comment]
Returning by default the axis order of the CRS coming from the authority defining the CRS is a *design* choice taken in the GDAL 3 development process, and detailed in https://gdal.org/en/latest/development/rfc/rfc73_proj6_wkt2_srsbarn.html#axis-order-issues. We won't revisit that. It is too late now, and exposing always 1st axis = easting/longitude, 2nd axis = northing/latitude has drawbacks in some situations

We offer the possibility to always use 1st axis = easting/longitude, 2nd axis = northing/latitude by calling the SetAxisMappingStrategy( OAMS_TRADITIONAL_GIS_ORDER) method.

**Comment by tgis-top** [comment]
>The SDK to access Geographic Data must aware of the Data axis order in order to let the APIs return right value. Since the beginning, X (method getX() , field X and the first coordinate parameter) represents East, Y represents North, and Z represents Height.

For the latitude and longitude coordinate sequence [30,150], we know that the first is latitude and the second is longitude; For  [30,50], it is not possible to determine which one is latitude and which one is longitude.  That's where SRS axis order makes the difference, to determine whether longitude or latitude comes first.

**Comment by rouault** [comment]
> That's where SRS axis order makes the difference, to determine whether longitude or latitude comes first.

I agree... You can get the semantics of the axis of a CRS with https://gdal.org/en/latest/api/ogrspatialref.html#_CPPv4NK19OGRSpatialReference7GetAxisEPKciP18OGRAxisOrientationPd
RFC 73 offers a consistent way of dealing with that topic. This is now "battle tested" after the many years it is in place. Admittedly this is an always confusing topic, whatever design choices we make, but all functionality needed to correctly process coordinates is there.

**Comment by tgis-top** [comment]
> Returning by default the axis order of the CRS coming from the authority defining the CRS is a _design_ choice taken in the GDAL 3 development process, and detailed in https://gdal.org/en/latest/development/rfc/rfc73_proj6_wkt2_srsbarn.html#axis-order-issues. We won't revisit that. It is too late now, and exposing always 1st axis = easting/longitude, 2nd axis = northing/latitude has drawbacks in some situations
> 
> We offer the possibility to always use 1st axis = easting/longitude, 2nd axis = northing/latitude by calling the SetAxisMappingStrategy( OAMS_TRADITIONAL_GIS_ORDER) method.

Now, the seems only `OGRCoordinateTransformation::Transform (size_t nCount, double *x, double *y, double *z=nullptr, int *pabSuccess=nullptr)` is affected by SRS axis order. Will OGRPoint::getX() always return the coordinate in west to east direction?

**Comment by rouault** [comment]
> Will OGRPoint::getX() always return the coordinate in west to east direction?

This will depend on what the driver has done with the DataAxisToSRSAxisMapping.
In the situation of let's say a shapefile or GeoPackage with a SRS = EPSG:4326, which has normally latitude, longitude axis order, those drivers will use SetAxisMappingStrategy( OAMS_TRADITIONAL_GIS_ORDER), so that the data axis to SRS axis mapping array = [2, 1], meaning that the first value of a geometry is a longitude, and the second one a latitude.
All vector drivers should normally do that, as this is the "tradition". You'd get only the CRS native axis order with the GML driver if you explicitly specify the SWAP_COORDINATES=NO open option (cf https://gdal.org/en/latest/drivers/vector/gml.html)
