### ISSUE TITLE
OGR_G_MakeValidEx() does not return a clone of a valid MultiPolygon (multi only because promoted) when using METHOD=STRUCTURE

### ISSUE THREAD

**Issue by ctoney** [OSGeo/gdal#10819]
### What is the bug?

`OGRGeometry::MakeValid()` says "Already-valid geometries are cloned without further intervention". With a valid MultiPolygon, that is only multi because it has been promoted, `MakeValid()` returns instead the Polygon representation when option `"METHOD=STRUCTURE"` is given. If the default  `"METHOD=LINEWORK"` is used, the valid MultiPolygon is returned unaltered as expected.

### Steps to reproduce the issue

```python
from osgeo import ogr

g1 = ogr.CreateGeometryFromWkt("MULTIPOLYGON (((0 0, 1 0, 1 1, 0 1, 0 0)))")
g1.IsValid()  # True

g2 = g1.MakeValid(["METHOD=STRUCTURE"])
g2.ExportToWkt()  # 'POLYGON ((0 0,0 1,1 1,1 0,0 0))'
g2.Equals(g1)  # False

g3 = g1.MakeValid()
g3.ExportToWkt()  # 'MULTIPOLYGON (((0 0,1 0,1 1,0 1,0 0)))'
g3.Equals(g1)  # True

g4 = g1.Clone()
g4.ExportToWkt()  # 'MULTIPOLYGON (((0 0,1 0,1 1,0 1,0 0)))'
```

### Versions and provenance

Linux Ubuntu 22.04, GDAL 3.8.4, GEOS 3.12.1

**Comment by jratike80** [comment]
I read https://postgis.net/docs/ST_MakeValid.html and made as a comparison a test with PostGIS 3.4 (with GEOS 3.12.1), and it keeps the multipolygon

```
select st_astext(
st_makevalid('MULTIPOLYGON (((0 0, 1 0, 1 1, 0 1, 0 0)))','method=structure'));
"MULTIPOLYGON(((0 0,1 0,1 1,0 1,0 0)))"
```
I had not read this interesting blog before https://www.crunchydata.com/blog/waiting-for-postgis-3.2-st_makevalid.

**Comment by rouault** [comment]
Doc and code changes in https://github.com/OSGeo/gdal/pull/10823

**Comment by ctoney** [comment]
Thanks!
