### ISSUE TITLE
/vsitar not working for multiple compression levels

### ISSUE THREAD

**Issue by nstrahl** [OSGeo/gdal#10821]
### What is the bug?

I have downloaded some ascii files from the German Weather Services (DWD) FTP server. The .asc raster files are compressed two or maybe three times. For example: YW2017.002_200101_asc.tar\YW2017.002_20010131_asc.tar.gz\YW_2017.002_20010131_2005.asc
One folder is a .tar and the folder below is a tar.gz folder.

When I run gdalinfo on the .asc file I get the following error:
`ERROR 4: `/vsitar/C:\Downloads\YW2017.002_200101_asc.tar\YW2017.002_20010131_asc.tar.gz\YW_2017.002_20010131_2005.asc' does not exist in the file system, and is not recognized as a supported dataset name.
gdalinfo failed - unable to open '/vsitar/C:\Downloads\YW2017.002_200101_asc.tar\YW2017.002_20010131_asc.tar.gz\YW_2017.002_20010131_2005.asc'`

I also tried chaining two vsitar prefixes. In such case, I get a different error:
`ERROR 1: Only read-only mode is supported for /vsitar
gdalinfo failed - unable to open '/vsitar/vsitar/C:\Downloads\YW2017.002_200101_asc.tar\YW2017.002_20010131_asc.tar.gz\YW_2017.002_20010131_2005.asc'.`

It seems like maybe the tool is trying to modify the first or the second tar file.
I tried extracting the first .tar and in such case gdalinfo then works correctly:
`gdalinfo.exe /vsitar/C:\Downloads\YW2017.002_200101_asc\YW2017.002_20010131_asc.tar.gz\YW_2017.002_20010131_2005.asc`
which produces the following correct output:
`Size is 900, 1100
Origin = (-443462.000000000000000,-3658645.000000000000000)
Pixel Size = (1000.000000000000000,-1000.000000000000000)
Corner Coordinates:
Upper Left  ( -443462.000,-3658645.000)
Lower Left  ( -443462.000,-4758645.000)
Upper Right (  456538.000,-3658645.000)
Lower Right (  456538.000,-4758645.000)
Center      (    6538.000,-4208645.000)
Band 1 Block=900x1 Type=Float32, ColorInterp=Undefined NoData Value=-9`

Is there a way to maybe fix this behavior in GDAL?
If not, is there a better way to access these doubly compressed files (for example by using the VSI or Curl API
to extract the first folder)?

### Steps to reproduce the issue

Download YW2017.002_200101_asc.tar from https://opendata.dwd.de/climate_environment/CDC/grids_germany/5_minutes/radolan/reproc/2017_002/asc/2001/

Run gdalinfo:
`gdalinfo.exe /vsitar/vsitar/C:\Downloads\YW2017.002_200101_asc.tar\YW2017.002_20010131_asc.tar.gz\YW_2017.002_20010131_2005.asc`

### Versions and provenance

GDAL 3.8.5, released 2024/04/02

**Comment by rouault** [comment]
Fix in https://github.com/OSGeo/gdal/pull/10824

In addition to the fix, it might also be prudent to use what is mentionned in https://gdal.org/en/latest/user/virtual_file_systems.html#vsitar-tar-tgz-archives : "an alternate syntax is available so as to enable chaining and not being dependent on .tar extension, e.g.: /vsitar/{/path/to/the/archive}/path/inside/the/tar/file. Note that /path/to/the/archive may also itself use this alternate syntax."

With the fix:
```
$ gdalinfo "/vsitar/{/vsitar/{/vsicurl/https://opendata.dwd.de/climate_environment/CDC/grids_germany/5_minutes/radolan/reproc/2017_002/asc/2001/YW2017.002_200101_asc.tar}/YW2017.002_20010131_asc.tar.gz}/YW_2017.002_20010131_2005.asc"
Driver: AAIGrid/Arc/Info ASCII Grid
Files: /vsitar/{/vsitar/{/vsicurl/https://opendata.dwd.de/climate_environment/CDC/grids_germany/5_minutes/radolan/reproc/2017_002/asc/2001/YW2017.002_200101_asc.tar}/YW2017.002_20010131_asc.tar.gz}/YW_2017.002_20010131_2005.asc
Size is 900, 1100
Origin = (-443462.000000000000000,-3658645.000000000000000)
Pixel Size = (1000.000000000000000,-1000.000000000000000)
Corner Coordinates:
Upper Left  ( -443462.000,-3658645.000) 
Lower Left  ( -443462.000,-4758645.000) 
Upper Right (  456538.000,-3658645.000) 
Lower Right (  456538.000,-4758645.000) 
Center      (    6538.000,-4208645.000) 
Band 1 Block=900x1 Type=Float32, ColorInterp=Undefined
  NoData Value=-9
```
