### ISSUE TITLE
Say which polygon had the problem

### ISSUE THREAD

**Issue by jidanni** [OSGeo/gdal#10829]
### Feature description

Say which polygon had the problem, not just where the problem occured.

### Additional context

>Warning 1: Self-intersection at or near point 120.86613015662651 24.181914020080345
>ERROR 6: Invalid polygon

That's simple to investigate...
assuming the user has only one polygon!

Because there might be many polygons at or near that point, the only way to figure out which one is to test them one by one.

Therefore the program could be made more helpful, if it simply also printed the offending polygon, in e.g., WKT format. Or at least some further information about which polygon it was of the many polygons in the input.

(Also do please quit with an error to the shell, (perhaps already fixed.))

**Comment by rouault** [comment]
> (Also do please quit with an error to the shell, (perhaps already fixed.))

@jidanni  with which utility? Please provide command line and input file to reproduce

**Comment by rouault** [comment]
I figured out this was the LIBKML driver...
