### ISSUE TITLE
abort with gdalwarp and bad (too coarse) resolution

### ISSUE THREAD

**Issue by mdsumner** [OSGeo/gdal#10827]
### What is the bug?

I see an abort with a target resolution that is entirely inappropriate for the target. I found it by going from entirely automated targets and tweaking the resolution from suitable (0.0006)  to coarse (1.0). 

### Steps to reproduce the issue

```bash
gdal_create /tmp/test_mds11.tif -ot Float32 -outsize 256 256 -burn 0 -a_srs EPSG:3857 -a_ullr 20017940 -1976356 20037508 -1995924

gdalwarp /tmp/test_mds11.tif -t_srs "EPSG:4326" /tmp/test_mds12.tif -tr 1 1
# corrupted size vs. prev_size
#Aborted
```

### Versions and provenance

Ubuntu 22.04.4 LTS 

GDAL 3.10.0dev-262ffc2002, released 2024/09/17

### Additional context

Originally in a different context in R I saw this and I will check again after feedback here. 

```
# malloc_consolidate(): invalid chunk size
# Aborted
```

**Comment by rouault** [comment]
Weird! Two persons reporting independently the same issue (dating back to 3.8) the same day. Fix already queued in #10822 a few hours ago

**Comment by mdsumner** [comment]
Oh, sorry for not searching well enough!!  Will do a few checks

**Comment by mdsumner** [comment]
Confirmed fixed, thanks!!
