### ISSUE TITLE
Allow inverse -gcps without rewriting each one

### ISSUE THREAD

**Issue by jidanni** [OSGeo/gdal#10828]
### Feature description

Perhaps add an option to ogr2ogr, to allow the reverse operation when using gcps.

### Additional context

> ogr2ogr -reverse_gcps \\
> -gcp 0 0 120.866141 24.181634 -gcp 5 0 120.866191 24.181634 -gcp 0 9 120.866141 24.181709

would be the same as
> ogr2ogr -gcp 120.866141 24.181634 0 0 -gcp 120.866191 24.181634 5 0 -gcp 120.866141 24.181709 0 9

but without needing to manually rewrite each and every gcp!

**Comment by jratike80** [comment]
Feels like a user error but maybe you have been using the QGIS georeferencer and have now a .points file that you want to utilize with some scripts.

If that is not the context, why would any user want to write GCPs in a wrong order?

**Comment by rouault** [comment]
Given the number of existing ogr2ogr options, we are going to be very picky to add new ones, and I feel what is suggested here has not enough value to clutter ogr2ogr with that.

The user could very well maintain its GCPs in a .csv file and with some little scripting generate the -gcps switches, for example with the following:

```
$ cat gcps.csv
x1,y1,x2,y2
1,2,3,4
5,6,7,8
9,10,11,12

$ ogr2ogr -f CSV /vsistdout/ gcps.csv -sql "select concat('-gcps ', x2, ' ', y2, ' ', x1, ' ', y1, ' \\') from gcps" | tail -n +2
-gcps 3 4 1 2 \
-gcps 7 8 5 6 \
-gcps 11 12 9 10 \
```

**Comment by jidanni** [comment]
(@jratike80 my house is
POLYGON ((0 0, 0 5, 5 9, ...))
but my garage is
POLYGON ((120.888 24.1666, ...))
usually I want to make the house the same system as the garage,
in order to put it on the map. But sometimes I want to go the other
way, to get the garage in the same simple coordinates as the house.)
