### ISSUE TITLE
`ERROR 6: Cannot find coordinate operations from {..., "type": "EngineeringCRS",   "name": "RGF93 v1 / Lambert-93", ...} to 'EPSG:2514'`

### ISSUE THREAD

**Issue by MathiasBaumgartinger** [OSGeo/gdal#10820]
### Feature description

I am currently working with the [FLAIR dataset](https://ignf.github.io/FLAIR/), more precisely a [small subset for "toying"](https://storage.gra.cloud.ovh.net/v1/AUTH_366279ce616242ebb14161b7991a8461/defi-ia/flair_data_2/flair_2_toy_dataset.zip). 

The aerial images have projected coordinate system, while the labels (masks) are in a local engineering coordinate system based on the projected coordinate system. I need to bring them into a common geo-format for further processing, i.e. want to apply a `gdalwarp` which errors with:

```
$ gdalwarp -t_srs EPSG:2514 flair_2_toy_labels_test/D029_2021/Z1_UA/msk/MSK_017541.tif /warped.tif

`ERROR 6: Cannot find coordinate operations from `{
  "$schema": "https://proj.org/schemas/v0.7/projjson.schema.json",
  "type": "EngineeringCRS",
  "name": "RGF93 v1 / Lambert-93",
  "datum": {
    "name": "Unknown engineering datum"
  },
  "coordinate_system": {
    "subtype": "Cartesian",
    "axis": [
      {
        "name": "Easting",
        "abbreviation": "E",
        "direction": "east",
        "unit": "metre"
      },
      {
        "name": "Northing",
        "abbreviation": "N",
        "direction": "north",
        "unit": "metre"
      }
    ]
  }
}' to `EPSG:2514'
```

### Additional context

Tested versions:
- GDAL 3.9.1, PROJ 9.4.1
- GDAL 3.9.2, PROJ 9.4.1

Refs: https://github.com/rasterio/rasterio/discussions/3178

**Comment by jratike80** [comment]
I believe that is is and will be impossible to convert data from a system that has unknown parameters.

You wrote that the system is "local engineering coordinate system based on the projected coordinate system". Could you find a place in the FLAIR documentation that describes how those systems are correlated?

**Comment by jratike80** [comment]
I attached the CRS of the main image (EPSG:2154) to the mask tif

`gdal_edit MSK_006512.tif -a_srs epsg:2154`

and the result looks perfect to me.

The image:
<img width="120" alt="image" src="https://github.com/user-attachments/assets/e342c859-8897-4ef4-b453-9179c8ae1aa3">

The image and mask in EPSG:2154
<img width="115" alt="image" src="https://github.com/user-attachments/assets/b4c94072-3ebd-4808-b5ba-1953a5a24cbc">

What remains is to ask from the data provider why they do not use EPSG:2154 for the mask, and that is done intentionally.

**Comment by MathiasBaumgartinger** [comment]
> I believe that is is and will be impossible to convert data from a system that has unknown parameters.
> 
> You wrote that the system is "local engineering coordinate system based on the projected coordinate system". Could you find a place in the FLAIR documentation that describes how those systems are correlated?

Sadly, the data paper mentions nothing of the use of this engineering system. The choice seems rather arbitrary to me.
I am by no means an expert, but could you elaborate what you mean by unknown parameters? I would like to understand *why* it is impossible.
A simple `gdalinfo` does provide some information on the dataset:
```
Driver: GTiff/GeoTIFF
Files: MSK_001876.tif
Size is 512, 512
Coordinate System is:
ENGCRS["RGF93 v1 / Lambert-93",
    EDATUM["Unknown engineering datum"],
    CS[Cartesian,2],
        AXIS["(E)",east,
            ORDER[1],
            LENGTHUNIT["metre",1,
                ID["EPSG",9001]]],
        AXIS["(N)",north,
            ORDER[2],
            LENGTHUNIT["metre",1,
                ID["EPSG",9001]]]]
Data axis to CRS axis mapping: 1,2
Origin = (1053184.000000000000000,6345215.999999999068677)
Pixel Size = (0.200000000000017,-0.200000000000017)
Metadata:
  AREA_OR_POINT=Area
Image Structure Metadata:
  COMPRESSION=LZW
  INTERLEAVE=BAND
Corner Coordinates:
Upper Left  ( 1053184.000, 6345216.000)
Lower Left  ( 1053184.000, 6345113.600)
Upper Right ( 1053286.400, 6345216.000)
Lower Right ( 1053286.400, 6345113.600)
Center      ( 1053235.200, 6345164.800)
Band 1 Block=512x16 Type=Byte, ColorInterp=Gray
```

Thanks for putting me in the direction of using `gdal_edit MSK_006512.tif -a_srs epsg:2154`. Might do it for now.

I mailed the maintainers asking for a specific reason for use of the local engineering coordinate system.

**Comment by jratike80** [comment]
Coordinate transformations are like currency exchange. It is easy to buy some dollars with euros because the exchange rate is know. But if you have 100 units of coins in some unknown currency nobody can tell  their value in dollars.

Engineering CRS is by definition:

> Contextually local coordinate reference system associated with an engineering datum.
> 
> It is applied either to activities on or near the surface of the Earth without geodetic corrections, or on moving platforms such as road vehicles, vessels, aircraft or spacecraft, or as the internal CRS  of an image.

What we know by the WKT of the engineering crs used in the FLAIR mask image is:
- the coordinates present eastings and northings
- the lenght unit is meter

What we do not know is for example where is the starting point (0 0). It could be a pole that the surveyor put in the backyard or some hight tower in Paris or whatever because the WKT does not tell it.

Compare with the WKT of EPSG:2154 that gives all the information that is needed for making a conversion into other coordinate systems.

```
PROJCRS["RGF93 v1 / Lambert-93",
    BASEGEOGCRS["RGF93 v1",
        DATUM["Reseau Geodesique Francais 1993 v1",
            ELLIPSOID["GRS 1980",6378137,298.257222101,
                LENGTHUNIT["metre",1]]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433]],
        ID["EPSG",4171]],
    CONVERSION["Lambert-93",
        METHOD["Lambert Conic Conformal (2SP)",
            ID["EPSG",9802]],
        PARAMETER["Latitude of false origin",46.5,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8821]],
        PARAMETER["Longitude of false origin",3,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8822]],
        PARAMETER["Latitude of 1st standard parallel",49,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8823]],
        PARAMETER["Latitude of 2nd standard parallel",44,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8824]],
        PARAMETER["Easting at false origin",700000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8826]],
        PARAMETER["Northing at false origin",6600000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8827]]],
    CS[Cartesian,2],
        AXIS["easting (X)",east,
            ORDER[1],
            LENGTHUNIT["metre",1]],
        AXIS["northing (Y)",north,
            ORDER[2],
            LENGTHUNIT["metre",1]],
    USAGE[
        SCOPE["Engineering survey, topographic mapping."],
        AREA["France - onshore and offshore, mainland and Corsica (France m├®tropolitaine including Corsica)."],
        BBOX[41.15,-9.86,51.56,10.38]],
    ID["EPSG",2154]]
```

**Comment by MathiasBaumgartinger** [comment]
I sincerely appreciate you taking the time to explain. Thanks!

**Comment by sgillies** [comment]
@MathiasBaumgartinger I scanned the FLAIR paper and only see this about the MSK creation

> The supervision data (MSK) is based on photointerpretation of the ORTHO HR® aerial imagery and has been manually produced by experts following a call for tenders from IGN.

There's no mention of the tooling. It could be different from the tools that produce the IMG files.

The paper mentions PyTorch. I think it's likely that they are using the data in pipelines that are not geo-aware and are unaware of the defects in georeferencing.

**Comment by rouault** [comment]
This is not a GDAL bug. The MSK_017541.tif file has an incorrect SRS specification. It uses very poorly/underspecified specified GeoTIFF keys:
```
   Keyed_Information:
      GTRasterTypeGeoKey (Short,1): RasterPixelIsArea
      GTCitationGeoKey (Ascii,22): "RGF93 v1 / Lambert-93"
      ProjLinearUnitsGeoKey (Short,1): Linear_Meter
      End_Of_Keys.
   End_Of_Geotiff.
```

There are 2 major defects:
- it lacks the GTModelTypeGeoKey=ModelTypeProjected key to indicate the nature of the CRS
- and it lacks either a EPSG code defining the CRS (which would be ProjectedCSTypeGeoKey = 2154) or a fully definition of the projected CRS

GDAL would at least need the following:
```
   Keyed_Information:
      GTModelTypeGeoKey (Short,1): ModelTypeProjected
      GTRasterTypeGeoKey (Short,1): RasterPixelIsArea
      ProjectedCSTypeGeoKey (Short,1): Code-2154 (RGF93 v1 / Lambert-93)
      End_Of_Keys.
```

(in theory, we could add support for such an ill-defined CRS given that the citation "RGF93 v1 / Lambert-93" exactly matches an entry in the EPSG database, but I would only do that if that would be really really needed. I would anticipate such GeoTIFF to not be properly handled by all other GeoTIFF capable software)

**Comment by agarioud** [comment]
@MathiasBaumgartinger

There was indeed a problem during the export of MSK files. We are not sure if it is related to a library version or an error in the CRS definition (we usually copy the input CRS for the export). In any case, the projection of the MSK files is the same as the IMG files, which is EPSG:2154. The transforms of the MSK files are correct.

We will try to correct the GeoTIFF headers of the MSK files.

Sorry for the inconvenience.

**Comment by MathiasBaumgartinger** [comment]
This is why we love open source and open data communities! Thanks everybody 👍
