### ISSUE TITLE
ERROR 1: SAMP_OFF out of range when chipping a NITF file using gdal_translate and -srcwin

### ISSUE THREAD

**Issue by chuck1987** [OSGeo/gdal#10841]
### What is the bug?

When attempting to chip a NITF with RPC information using gdal_translate and -srcwin, it appears you can not chip using a pixel value after the SAME_OFF value.

Size is 9216, 7168
GCP Projection = 
GEOGCRS["WGS 84",
    DATUM["World Geodetic System 1984",
        ELLIPSOID["WGS 84",6378137,298.257223563,
            LENGTHUNIT["metre",1]]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["degree",0.0174532925199433]],
    CS[ellipsoidal,2],
        AXIS["geodetic latitude (Lat)",north,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433]],
        AXIS["geodetic longitude (Lon)",east,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433]],
    ID["EPSG",4326]]
Data axis to CRS axis mapping: 2,1
GCP[  0]: Id=UpperLeft, Info=
          (0.5,0.5) -> (140.844722222222,38.3494444444444,0)
GCP[  1]: Id=UpperRight, Info=
          (9215.5,0.5) -> (141.105833333333,38.3608333333333,0)
GCP[  2]: Id=LowerRight, Info=
          (9215.5,7167.5) -> (141.105277777778,38.2225,0)
GCP[  3]: Id=LowerLeft, Info=
          (0.5,7167.5) -> (140.843888888889,38.2116666666667,0)
Metadata:

RPC Metadata:
  HEIGHT_OFF=120
  HEIGHT_SCALE=500
  LAT_OFF=38.2904
  LAT_SCALE=0.0699
  LINE_DEN_COEFF=1 0.001164202 -0.0002991435 -0.0001327615 -3.462403e-05 6.366756e-08 1.454738e-06 -3.239952e-05 0.0001251273 -4.54929e-05 -5.157354e-07 -1.853804e-07 -4.264692e-05 -8.384562000000001e-08 3.603439e-06 0.0002014268 -5.340322e-08 2.861433e-08 3.61855e-06 8.319265e-08 
  LINE_NUM_COEFF=7.792986e-05 0.08181827999999999 -1.075395 -0.006816589 0.001013332 1.589634e-05 -0.0001210954 -0.0009822915999999999 -0.0002320339 -2.558215e-07 2.478112e-08 -2.027624e-06 -2.681627e-05 -3.721689e-06 3.932334e-05 0.000173545 4.885594e-05 1.263504e-07 2.259709e-06 3.393022e-07 
  LINE_OFF=3352
  LINE_SCALE=3377
  LONG_OFF=140.9688
  LONG_SCALE=0.1253
  MAX_LAT=38.32535
  MAX_LONG=141.03145
  MIN_LAT=38.25545
  MIN_LONG=140.90615
  SAMP_DEN_COEFF=1 0.0006486077 -0.0001838932 -0.0002831983 -9.176697e-06 1.820683e-06 -8.022981e-07 3.729996e-07 -5.151338e-06 -2.339475e-06 -1.57023e-08 1.176267e-07 -2.634591e-08 -1.723833e-08 1.899421e-07 2.762669e-07 -1.305197e-08 -3.603238e-08 0 0 
  SAMP_NUM_COEFF=0.005481671 0.9767569 -0.002878145 0.02622883 0.0002059241 0.0001423826 -6.559756e-05 -0.006148734 -0.0001431416 5.296923e-06 1.201674e-06 2.94228e-05 2.649767e-06 -2.218461e-06 6.624773e-06 -7.207680999999999e-05 -2.932752e-08 -2.788738e-06 -1.318961e-06 -5.511363e-08 
  SAMP_OFF=4411
  SAMP_SCALE=4529
Corner Coordinates:
Upper Left  (    0.0,    0.0)
Lower Left  (    0.0, 7168.0)
Upper Right ( 9216.0,    0.0)
Lower Right ( 9216.0, 7168.0)
Center      ( 4608.0, 3584.0)

### Steps to reproduce the issue

Here is a successful chip. GCP coordinates are lost, but that is not my issue.

**gdal_translate Japan.ntf JapanChipped.ntf -srcwin 4411 2000 100 100**

Input file size is 9216, 7168
0...10...20...30...40...50...60...70...80...90...100 - done.
ERROR 6: The 4 GCPs image coordinates must be exactly at the *center* of the 4 corners of the image ( (0.5, 0.5), (99.5 0.5), (99.5 99.5), (99.5 0.5) ).

And then the unsuccessful chip

**gdal_translate apan.ntf JapanChipped.ntf -srcwin 4412 2000 100 100**
Input file size is 9216, 7168
ERROR 1: SAMP_OFF out of range.
Warning 6: Cannot format a valid RPC00B TRE from the RPC metadata
0...10...20...30...40...50...60...70...80...90...100 - done.
ERROR 6: The 4 GCPs image coordinates must be exactly at the *center* of the 4 corners of the image ( (0.5, 0.5), (99.5 0.5), (99.5 99.5), (99.5 0.5) ).

NOTE: GDAL does return an image in the relatively correct srcwin , however because of the errors the RPC and TRE metadata are all missing.

### Versions and provenance

3.10 (Windows/Ubuntu)

**Comment by rouault** [comment]
Subsetting a dataset with RPC involves shifting the SAMP_OFF/LINE_OFF items by the amount of the (inverted) offset expressed in -srcwin . But the NITF format has a limitation in that the SAMP_OFF/LINE_OFF fields must be in the [0, 9999] range.
In your first case, SAMP_OFF=4411 . With a -srcwin 4411 x x x, the new SAMP_OFF value is 4411-4411=0
In your second case, it would be -1.
For NITF, the only solution would be to create the shifted RPC in a (GDAL specific) auxiliary .ntf.aux.xml file, to avoid losing it completely
You may workaround the issue by translating to GeoTIFF instead of NITF

**Comment by rouault** [comment]
> For NITF, the only solution would be to create the shifted RPC in a (GDAL specific) auxiliary .ntf.aux.xml file, to avoid losing it completely

Actually I do see this is already the case.
So, there isn't anything to do. GDAL behaves at the best as it can for that situation.
