### ISSUE TITLE
gdal.Warp different result for v2.1.0 and v2.3.2

### ISSUE THREAD

**Issue by vinichenko-mr** [OSGeo/gdal#1085]
## Expected behavior and actual behavior.

I upgraded GDAL version from 2.1.0 to 2.3.2. Both versions I built from source with Python bindings. PROJ version - 5.2.0. 

**Expected behavior**

gdal.Warp() returns the same result as in 2.1.0

**Actual behavior**

gdal.Warp() returns result with some changes in raster array.

## Steps to reproduce the problem.
The archive contains *source.tiff*.
[rasters.zip](https://github.com/OSGeo/gdal/files/2566147/rasters.zip)

I have the code:

```import hashlib
from osgeo import gdal


source_filename = "source.tiff"
gdal_version = gdal.__version__
warp_options = '-of GTiff -r cubic -te_srs "+proj=longlat +datum=WGS84 +no_defs " -te 49.21875 -14.5197800463 49.306640625 -14.4346802153 -t_srs "+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs" -ts 256 256 -dstalpha -srcnodata 0 -wo UNIFIED_SRC_NODATA=YES'


def create_output_filename():
    return "processed_{v}.tiff".format(v=gdal_version)


def warp():
    output_filename = create_output_filename()
    gdal.Warp(output_filename, source_filename, options=warp_options)


warp()
```

I run it on GDAL 2.1.0 and GDAL 2.3.2.
The results are two .tiff files - *processed_2.1.0.tiff* and *processed_2.3.2.tiff*
The archive contains results, too. 

How to check diff:
1. gdalinfo.

`gdalinfo processed_2.1.0.tiff -stats`

```
...
Band 1 Block=256x8 Type=UInt16, ColorInterp=Gray
  Minimum=5841.000, Maximum=26698.000, Mean=7100.601, StdDev=1761.655
  NoData Value=0
  Metadata:
    STATISTICS_MAXIMUM=26698
    STATISTICS_MEAN=7100.6005859375
    STATISTICS_MINIMUM=5841
    STATISTICS_STDDEV=1761.6546349845
Band 2 Block=256x8 Type=UInt16, ColorInterp=Alpha
  Minimum=255.000, Maximum=255.000, Mean=255.000, StdDev=0.000
  NoData Value=0
  Metadata:
    STATISTICS_MAXIMUM=255
    STATISTICS_MEAN=255
    STATISTICS_MINIMUM=255
    STATISTICS_STDDEV=0
```
`gdalinfo processed_2.3.2.tiff -stats`
```
...
Band 1 Block=256x8 Type=UInt16, ColorInterp=Gray
  Minimum=5841.000, Maximum=26699.000, Mean=7100.600, StdDev=1761.724
  Metadata:
    STATISTICS_MAXIMUM=26699
    STATISTICS_MEAN=7100.5995788574
    STATISTICS_MINIMUM=5841
    STATISTICS_STDDEV=1761.7243529314
Band 2 Block=256x8 Type=UInt16, ColorInterp=Alpha
  Minimum=65535.000, Maximum=65535.000, Mean=65535.000, StdDev=0.000
  Metadata:
    STATISTICS_MAXIMUM=65535
    STATISTICS_MEAN=65535
    STATISTICS_MINIMUM=65535
    STATISTICS_STDDEV=0
```

2. check raster arrays

2.1.0:
![2 1 0](https://user-images.githubusercontent.com/44899363/48270668-4072b080-e443-11e8-9a92-29b593f314b3.jpg)

2.3.2
![2 3 2](https://user-images.githubusercontent.com/44899363/48270693-51232680-e443-11e8-9077-ccf7b11697e6.jpg)

## Operating system

Ubuntu 16.04 64 bit

## GDAL version and provenance
2.1.0 and 2.3.2, built from source

**Comment by rouault** [comment]
This is expected. There have been several changes of behaviour between the 2 versions. The main difference is now that the alpha channel is returned on 16 bit unless 8 bit (unless you specify -wo DST_ALPHA_MAX=255 , see https://www.gdal.org/structGDALWarpOptions.html#a0ed77f9917bb96c7a9aabd73d4d06e08 ) . And the cubic resampler itself has been improved / optimized in ways that subtely change values.

**Comment by vinichenko-mr** [comment]
@rouault, thank you!
