### ISSUE TITLE
gdal_contour behavior change between 3.8.4 and 3.9.0

### ISSUE THREAD

**Issue by madsvlad2** [OSGeo/gdal#10854]
### What is the bug?

It appears `gdal_contour` behavior has changed somewhere between 3.8.4 and 3.9.0.  I am generating hillshade polygons from hillshade raster images generated by `gdaldem`. In my application, the world is cut into tiles and it is important that the hillshade polygons match across tile boundaries. To accomplish this, the hillshade raster image for a tile overlaps with its neighbor tile images by 8 pixels to ensure continuity (that's a total of 16 overlapping pixels between any two neighbors).

This all worked fine until I upgraded to GDAL 3.9.0. The images below illustrate the differences:

Here is the output of `gdal_contour` with version 3.8.4 near the boundary between two tiles where tile A is north of tile B:
### Tile A
![90488694-highlight-gdal-3 7 2](https://github.com/user-attachments/assets/d383c438-574f-4205-9077-e371ca83bc3c)
### Tile B
![90488692-highlight-gdal-3 7 2](https://github.com/user-attachments/assets/286861b9-1bfb-4706-904a-97200d454141)
You can see that the polgons generated in the overlapping border areas between the tiles are identical

Here is the output of `gdal_contour` with version 3.9.0 in the same region:
### Tile A
![90488694-highlight-gdal-3 9 0](https://github.com/user-attachments/assets/711a6b58-23b5-4df6-bff3-c88d94fe2849)
### Tile B
![90488692-highlight-gdal-3 9 0](https://github.com/user-attachments/assets/cdd52a67-ecef-4bdc-8b7b-3dcfea0b66b5)

Here Tile A polygons are different. Note that the small polygon (gold in Tile B) is generated, but is classified to a different level than in Tile B.

In the images above, the two white dots represent points along the edge between the tiles where they will eventually be cut.

Both sets of data were generated off the same two hillshade raster images:
![90488692-90488694-hillshade-raster-overlap](https://github.com/user-attachments/assets/08a50e12-64fa-46aa-94e1-a3799544e4ad)

You can see in the image above, that there is overlap between the neighboring hillshade raster images. In the picture one of the images was turned red and made slightly transparent. I have verified that the images are pixel-for-pixel equal in the overlap region.

### Steps to reproduce the issue

Attached is a zip file containing a bash script, the two source hillshade raster images and the generated hillshade polygons from each GDAL version. You should be able to modify the bash script to point to where the different GDAL binary versions are located on your computer to run the script. The script also illustrates how `gdal_contour` is being called.

[gdal_contour_issue.zip](https://github.com/user-attachments/files/17081339/gdal_contour_issue.zip)

### Versions and provenance

Ubuntu 24.04
GDAL version 3.9.0

**Comment by elpaso** [comment]
I can reproduce the issue, I noticed another difference between master (which I am testing) and 3.8, the level of 3.8.4 at the clicked coordinates (outside the 239 and 245 polys) is 0, while it is 198 in 3.9 and master

![immagine](https://github.com/user-attachments/assets/7feff700-9c3d-4fd2-905f-abaab20e2203)

**Comment by elpaso** [comment]
The issue appeared after https://github.com/OSGeo/gdal/commit/bbb989d7162a1c40d6fa70dca185efeaf59e3709
