### ISSUE TITLE
gdalinfo --formats -json

### ISSUE THREAD

**Issue by hobu** [OSGeo/gdal#10878]
### Feature description

`gdalinfo --formats -json` and `ogrinfo --formats -json` would be very useful for verification of packaging configuration. Including the answered extensions, capabilities, and descriptions in nodes would also be helpful.

**Comment by rouault** [comment]
Prabably the first step is to have "gdalinfo --format {name} --json" to work, and then applying that to --formats is just making an array.
Which brings the question: do we want to JSON'ify (I mean just in gdalinfo --format[s] --json !) the XML creation/open/etc. option lists ?
That should/could probably be made available as a ``char* GDALDriverGetCapabilitiesAsJSON(GDALDriverH hDr)`` function to be re-used by applications. Or am I over-engineering stuff?

**Comment by hobu** [comment]
> Or am I over-engineering stuff?

Umm...

**Comment by rouault** [comment]
went for the non-over-engineered way in https://github.com/OSGeo/gdal/pull/10881
