### ISSUE TITLE
warp: resample 'average' (sometimes) results in 0 for shape (1,1) 

### ISSUE THREAD

**Issue by mdsumner** [OSGeo/gdal#10892]
### What is the bug?

I'm motivated to use the warper to get a singleton aggregate value, such as the mean elevation from this GEBCO overview. But with width and height set to 1, I get "0". Translate shows the correct value. 

### Steps to reproduce the issue

```python
from osgeo import gdal
gdal.UseExceptions()
dsn = "vrt:///vsicurl/https://gebco2023.s3.valeria.science/gebco_2023_land_cog.tif?ovr=6"

resampleAlg = "average"

w = gdal.Warp("/vsimem/ovr6.tif", dsn, width = 1, height = 1,  resampleAlg = resampleAlg)
w.GetRasterBand(1).ReadAsArray()
# array([[0]], dtype=int16)

t = gdal.Translate("/vsimem/ovr6.tif", dsn, width = 1, height = 1,  resampleAlg = resampleAlg)
t.GetRasterBand(1).ReadAsArray()
# array([[-1899]], dtype=int16)

```

I've explored this by taking rasters filled with '1' from sizes 1,1 and up. I think the minimum size at which the problem occurs is ~9 but I haven't been able to pin that exactly due to other problems. 

Create a `x: 10, y: 9` raster filled with zeros, then compare warp to translate with resample 'average'. 

```python3
from osgeo import gdal
gdal.UseExceptions()

import numpy as np
width = 10
height = 9
driver = gdal.GetDriverByName("MEM")
ds = driver.Create("", width, height, 1, gdal.GDT_Int16)
ds.SetGeoTransform([0, 1, 0, 0, 0, -1])
ds.SetProjection("EPSG:4326")

band = ds.GetRasterBand(1)
data = np.full((height, width), 1, np.int16)
band.WriteArray(data)
resampleAlg = "average"

w = gdal.Warp("", ds, width = 1, height = 1, resampleAlg = resampleAlg, format = "MEM")
w.GetRasterBand(1).ReadAsArray()
#array([[0]], dtype=int16)

t = gdal.Translate("", ds, width = 1, height = 1, resampleAlg = resampleAlg, format = "MEM")
t.GetRasterBand(1).ReadAsArray()
# array([[1]], dtype=int16)

```

(I talk of minimum size because at `x: 9 y:8` warp gets the correct value. )

### Versions and provenance

```
gdalinfo --version
GDAL 3.10.0dev-082d0e78c54dd544a14947ac216fdcca8080595c, released 2024/06/20
```

### Additional context

I appreciate that Translate is the better choice in this situation, but I thought this might uncover potential other stuff, in the past I had used a target of 2x2 which I then took the average of those values to make this work. 

It's taken me a while to pin this down this far because of other issues, the above was run using the ubuntu small image

**Comment by rouault** [comment]
Fix in https://github.com/OSGeo/gdal/pull/10894 . You know what @mdsumner . This is entirely your fault ;-) Just kidding because it actually turns out that my initial fix for https://github.com/OSGeo/gdal/issues/6478 you reported was a bit too aggressive. Dealing with projection discontinuities is a nightmare. And I don't know the ultimate answer to that. We keep adding heuristics but that's fragile. Paradoxically the core of the warper knows absolutely nothing about CRS (which is probably one of its greatest strength too...). It justs maps target image space to source image space, and obviously discontinuities are not welcome properties.

**Comment by rouault** [comment]
Ah yes, so given I've restricted the initial heuristics, you would be welcome to check that cases that were fixed by it are still fixed (well, the unit tests I added still pass, but that just tells about it, not necessarily about real life situations)

**Comment by mdsumner** [comment]
Thanks Even, I did have an odd feeling that it was somehow my fault... 😁 I'll check 👌

**Comment by mdsumner** [comment]
Fwiw I feel #6582 is related in the sense of needing to know the geography at the lowest level, or would it be safe to always wrap in a geolocation arrays context?
