### ISSUE TITLE
Feature request: Create SQL Script option to ogr2ogr

### ISSUE THREAD

**Issue by YoshiakiYamasaki** [OSGeo/gdal#1090]
If ogr2ogr has option to create SQL script when import shape file(using -f option), it is very convenient to customize and avoid some error.

For example)
When following error occurred, I can use "-skipfailures" option to import shape file except error record. After that, I customize SQL script to import error record.

ogr2ogr with MySQL 8 (Shape file import error) #1089

## Expected behavior and actual behavior.
N/A

## Steps to reproduce the problem.
N/A

## Operating system
N/A

## GDAL version and provenance
N/A

**Comment by jratike80** [comment]
Do you mean a new driver like the PGDump driver https://www.gdal.org/drv_pgdump.html but for MySQL?

**Comment by YoshiakiYamasaki** [comment]
Yes. I want to make SQL script to import shape file for MySQL.

**Comment by rouault** [comment]
I'm not sure we want a 'MySQLDump' driver. Seems to be low priority

**Comment by jratike80** [comment]
I believe that this is too low priority for keeping the issue open.
