### ISSUE TITLE
Postgres Laundering Incorrectly Truncates 64 Character Names

### ISSUE THREAD

**Issue by gavlt** [OSGeo/gdal#10907]
### What is the bug?

https://github.com/OSGeo/gdal/pull/10555 introduced truncation with md5 hashing to the Postgres name laundering. The hashing ensures uniqueness of column names. This works very well, when the column name is 65+ characters, but seems to misbehave when the column name is 64, where it will be incorrectly(?) truncated to 63 characters, without any md5 hash.

### Steps to reproduce the issue

Have a column 64 characters, i.e:
```
test_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX_long_name
```
See that the column is truncated to 63 characters with no hash:
```
test_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx_long_nam
```
Expect it to be truncated with a md5 hash, i.e:
```
test_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx_bc8b2e3f
```

### Versions and provenance

3.9.2 onwards (as per the introduction of https://github.com/OSGeo/gdal/pull/10555)

### Additional context

The logic works fine for 65+ characters, i.e:
```
test_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX_long_name
```
correctly becomes:
```
test_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx_d1acff69
```

I'd expect columns of 64 characters to be truncated with a md5 hash, i.e:
```
test_XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX_long_name
```
becomes
```
test_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx_bc8b2e3f
```
The above would probably make for a sensible test case in [autotest/ogr/ogr_pg.py:test_ogr_pg_long_identifiers](https://github.com/rouault/gdal/blob/7076c1db6e49e841933755563d6c31f6a0327d56/autotest/ogr/ogr_pg.py#L5887).

The issue seems to be that for names of 64 characters, when the code [hits the hashing if statement](https://github.com/OSGeo/gdal/blob/1571b1bea26f32df98b2136a2f6de63dc2febbaa/ogr/ogrsf_frmts/pgdump/ogrpgdumpdatasource.cpp#L153-L154) `i == OGR_PG_NAMEDATALEN - 1 && pszSafeName[i] != '\0' && pszSafeName[i + 1] != '\0'` doesn't eval true because:
- `i` is `63`
- `pszSafeName[i]` is `e`
- `pszSafeName[i + 1]` would be `\0`

I don't quite understand why `pszSafeName[i + 1]` is being checked, as the `i == OGR_PG_NAMEDATALEN - 1` should sufficiently bound the check?

**Comment by rouault** [comment]
@gavlt Thanks for the detailed analysis. Fix in https://github.com/OSGeo/gdal/pull/10912

**Comment by gavlt** [comment]
Impressively fast turnaround. I don't believe there's anything further I can do to help? I look forward to seeing it in a future release, thanks and well done @rouault!
