### ISSUE TITLE
trying to set transformerOptions as dictionary in Python binding gdal.WarpOptions raises UnboundLocalError

### ISSUE THREAD

**Issue by ebaudrez** [OSGeo/gdal#10919]
## Python code

```
from osgeo import gdal
options = gdal.WarpOptions(transformerOptions={"SRC_METHOD": "GEOLOC_ARRAY"})
```

## Observed behaviour

Raises exception `UnboundLocalError: local variable 'opt' referenced before assignment`

## Expected behaviour

Should not raise an exception. Similar code

```
options = gdal.WarpOptions(creationOptions={"COMPRESS": "DEFLATE"})
```

does not raise an exception.

### Steps to reproduce the issue

Running the following Python code

```{python}
from osgeo import gdal
options = gdal.WarpOptions(transformerOptions={"SRC_METHOD": "GEOLOC_ARRAY"})
```

raises an exception `UnboundLocalError: local variable 'opt' referenced before assignment`

### Versions and provenance

GDAL coming from Conda, version 3.9.1

### Additional context

Relevant code in `gdal.py` (around line 1070):
```
        if transformerOptions is not None:
            if isinstance(transformerOptions, dict):
                for k, v in transformerOptions.items():
                    # exception is raised in next line
                    new_options += ['-to', opt]
            else:
                for opt in transformerOptions:
                    new_options += ['-to', opt]
```

The appearance of the first `opt` is likely a typo or copy-paste error. Similar code for `creationOptions` (around line 1050) is:

```
        if creationOptions is not None:
            if isinstance(creationOptions, dict):
                for k, v in creationOptions.items():
                    new_options += ['-co', f'{k}={v}']
            else:
                for opt in creationOptions:
                    new_options += ['-co', opt]
```

**Comment by rouault** [comment]
Thanks for the report and diagnosis. Fixed per https://github.com/OSGeo/gdal/pull/10921
