### ISSUE TITLE
Improve accuracy warning when types does not match

### ISSUE THREAD

**Issue by latot** [OSGeo/gdal#10915]
### What is the bug?

Hi, actually when we tranform/import/export some data with GDAL, it handles the conversion types, in cases where the selected output type (by the user or default gdal) does not match, we can get messages like:

```Warning 1: Integer overflow occurred when trying to set 32bit field.```

If the output is PG with the Varchar type, it could cause a similar issue for long strings.

The warning is great, is just that with it we can't know which column is triggering this, in case we want to change the column type to keep precision on the data.

Would be nice have something like this:

```Warning 1: Integer overflow occurred when trying to set 32bit field on column 'col_1'.```

This is not only for PG/Sqlite, is in general, the complex part is for some files, SQLite has Tables->Columns, PG has Schema->Table->Columns, the idea is get the needed info to reach the column that triggers this.

Other formats could also need other aspects to reach that column.

Thx!

### Steps to reproduce the issue

Any SQLite file with a row that has a value of the max possible integer, which will overflow PG Int32.

ogr2ogr PG:"dbname='postgres' host='127.0.0.1' port='5432' user='postgres' password='postgres'" some.sqlite
```Warning 1: Integer overflow occurred when trying to set 32bit field.```

### Versions and provenance

GDAL 3.9.1, released 2024/06/22

**Comment by rouault** [comment]
Addressed in #10945
