### ISSUE TITLE
Ogr2ogr is throwing "ERROR 1: ERROR:  permission denied to create event trigger "ogr_system_tables_event_trigger_for_metadata"

### ISSUE THREAD

**Issue by rduivenvoorde** [OSGeo/gdal#10925]
### What is the bug?

Downloading https://bodemdata.nl/files/download/LBK_BKNSN_2023.zip

And loading it via  

```
ogr2ogr  -overwrite -f PostgreSQL PG:"schemas=source_bodemkaart" /vsizip//home/richard/source_downloads/202410/source_bodemkaart_bknsn_202403.zip/LBK_BKNSN_2023/BKNSN_2023.shp -nln bksns_2023
```

While succesfully running my scripts some months ago (probably 3.8 ?)
I now end up apparently the data loaded, but an ERROR on the end (and 1 as return):
```
ERROR 1: ERROR:  permission denied to create event trigger "ogr_system_tables_event_trigger_for_metadata
HINT:  Must be superuser to create an event trigger.
```

Probably because I'm not superuser here. I'm loading the data in a schema (of which the PG user owner is), but apparently you need to be superuser to write some metadata tables?

Ah... from https://gdal.org/en/latest/drivers/vector/pg.html 

```
OGR_PG_ENABLE_METADATA=[YES​/​NO]: (GDAL >= 3.9) Defaults to YES. If set to "YES" (the default), the driver will try to use (and potentially create) the ogr_system_tables.metadata table to retrieve and store layer metadata.
```

While I agree that it is probably best to default to YES, I wonder if GDAL should raise an error for this?

Would'nt a warning like "You've enabled writing metadata, but you lack permission for this" be nicer, also because upgrading from 3.8 to 3.9 now breaks scripts?

Please close if this is already discussed :-)
(also creating this issue because I hit this, and was googling for it and nothing was returned)

### Steps to reproduce the issue

-

### Versions and provenance

```
$ ogr2ogr --version
GDAL 3.9.2, released 2024/08/13

$ cat /etc/debian_version 
trixie/sid

```

**Comment by rouault** [comment]
@rduivenvoorde Thanks for raising that. PostgreSQL permissions have been giving me headaches related to that. Should be fixed per https://github.com/OSGeo/gdal/pull/10926 which will check that the user has appropriate rights to avoid hard-failing
