### ISSUE TITLE
Missing CSEXRB Data

### ISSUE THREAD

**Issue by dukesook** [OSGeo/gdal#10939]
### What is the bug?

gdalinfo doesn't output the CSEXRB data from a NITF

### Steps to reproduce the issue

Run ```$ gdainfo -mdd file.ntf``` on one of the [SNIP RIP NITF files](https://nsgreg.nga.mil/doc/view?i=5523) files. The output include lots of information, but is missing the CSEXRB TRE.

### Versions and provenance

Operating System: WSL
Binary: Built from source

**Comment by rouault** [comment]
@dukesook Please provide a direct link to an image that cause troubles. The NITF driver is supposed to be able to read the CSEXRB TRE. There is a regression test suite checking it: https://github.com/OSGeo/gdal/blob/f1f750e1b25cfe22f2b2ce4795ee459beb3fa8d8/autotest/gdrivers/nitf.py#L4009

**Comment by dukesook** [comment]
I took [07APR2005_Hyperion_331406N0442000E_SWIR172_1p2A_L1R-BIB.ntf](https://nsgreg.nga.mil/doc/view?i=5522&month=10&day=5&year=2024) and ran:

```$ gdalinfo  -mdd all  1p2A_L1R-BIB.ntf  >  1p2A_L1R-BIB.txt```

The resulting output file is here: 
[1p2A_L1R-BIB.txt](https://github.com/user-attachments/files/17264830/1p2A_L1R-BIB.txt)

If you repeat the process and get the CSEXRB data in your output, could you please attach it so I can see?

**Comment by rouault** [comment]
The CSEXRB data is in the 2nd subdataset (of index 1), not in the 1st one (of index 0):
```
$ gdalinfo NITF_IM:1:07APR2005_Hyperion_331406N0442000E_SWIR172_1p2A_L1R-BIB.ntf -mdd all | grep CSEXRB
Warning 1: Invalid loop construct in CSCSDB DES in XML resource : invalid 'counter' SAMPLE_DIMENSION
  NITF_CSEXRB_ALONG_SCAN_GSD=0000001200.2
[...]```

**Comment by rouault** [comment]
Fix for CSCSDB DES warning in https://github.com/OSGeo/gdal/pull/10942
