### ISSUE TITLE
Issue with opening shapefile

### ISSUE THREAD

**Issue by gauyikang** [OSGeo/gdal#1096]
Usually when I reading a shapefile. The code is as follow
#### the code opening a shapefile#####
driver = ogr.GetDriverByName('ESRI Shapefile')
dataSource = driver.Open(daShapefile, 0) 
print dataSource.
#### end ####

shapefile must contains .shp,.shx and .dbf file. But  when opening a shapefile, It seems not checking whether the dbf is missing or corrupt. For Example , I delete the .dbf file. the datasource should return None, but actually it doesn't.
    

## GDAL version and provenance
For example: the 2.2.4 version

**Comment by rouault** [comment]
The shapefile driver accepts either .shp + shx, or .dbf, or 3 together. So this is working as expected
