### ISSUE TITLE
Error opening ESRI Personal GeoDatabase with non ASCII chars in file path \ name on Windows

### ISSUE THREAD

**Issue by agiudiceandrea** [OSGeo/gdal#10960]
### What is the bug?

It is not possible to open an ESRI Personal GeoDatabase file containing non ASCII chars in the file path \ name on Windows 10 64-bit.

Using ogrinfo in the OSGeo4W Shell (GDAL/OGR 3.9.2, GDAL/OGR 3.10.0dev-d0eb0a996a)
```
ogrinfo C:\test\samplè.mdb --debug ON
GDAL: Proxy driver FileGDB *not* registered due to ogr_FileGDB.dll not being found
GDAL: Proxy driver HANA *not* registered due to ogr_HANA.dll not being found
GDAL: Proxy driver KEA *not* registered due to gdal_KEA.dll not being found
GDAL: Proxy driver MSSQLSpatial *not* registered due to ogr_MSSQLSpatial.dll not being found
ODBC: EstablishSession(DRIVER=Microsoft Access Driver (*.mdb, *.accdb);DBQ=C:\test\sampl├¿.mdb)
ODBC: SQLDriverConnect(DRIVER=Microsoft Access Driver (*.mdb, *.accdb);DBQ=C:\test\sampl├¿.mdb)
ODBC: ... failed:
ODBC: SQLDisconnect()
ODBC: EstablishSession(DRIVER=Microsoft Access Driver (*.mdb, *.accdb);DBQ="C:\test\sampl├¿.mdb")
ODBC: SQLDriverConnect(DRIVER=Microsoft Access Driver (*.mdb, *.accdb);DBQ="C:\test\sampl├¿.mdb")
ODBC: ... failed:
ODBC: SQLDisconnect()
ODBC: EstablishSession(DRIVER=Microsoft Access Driver (*.mdb);DBQ=C:\test\sampl├¿.mdb)
ODBC: SQLDriverConnect(DRIVER=Microsoft Access Driver (*.mdb);DBQ=C:\test\sampl├¿.mdb)
ODBC: ... failed:
ODBC: SQLDisconnect()
ODBC: EstablishSession(DRIVER=Microsoft Access Driver (*.mdb);DBQ="C:\test\sampl├¿.mdb")
ODBC: SQLDriverConnect(DRIVER=Microsoft Access Driver (*.mdb);DBQ="C:\test\sampl├¿.mdb")
ODBC: ... failed:
ODBC: SQLDisconnect()
ODBC: EstablishSession(DRIVER=Microsoft Access Driver (*.mdb, *.accdb);DBQ=C:\test\sampl├¿.mdb)
ODBC: SQLDriverConnect(DRIVER=Microsoft Access Driver (*.mdb, *.accdb);DBQ=C:\test\sampl├¿.mdb)
ODBC: ... failed:
ODBC: SQLDisconnect()
ODBC: EstablishSession(DRIVER=Microsoft Access Driver (*.mdb, *.accdb);DBQ="C:\test\sampl├¿.mdb")
ODBC: SQLDriverConnect(DRIVER=Microsoft Access Driver (*.mdb, *.accdb);DBQ="C:\test\sampl├¿.mdb")
ODBC: ... failed:
ODBC: SQLDisconnect()
ODBC: EstablishSession(DRIVER=Microsoft Access Driver (*.mdb);DBQ=C:\test\sampl├¿.mdb)
ODBC: SQLDriverConnect(DRIVER=Microsoft Access Driver (*.mdb);DBQ=C:\test\sampl├¿.mdb)
ODBC: ... failed:
ODBC: SQLDisconnect()
ODBC: EstablishSession(DRIVER=Microsoft Access Driver (*.mdb);DBQ="C:\test\sampl├¿.mdb")
ODBC: SQLDriverConnect(DRIVER=Microsoft Access Driver (*.mdb);DBQ="C:\test\sampl├¿.mdb")
ODBC: ... failed:
ODBC: SQLDisconnect()
ERROR 1: Unable to initialize ODBC connection to DSN for C:\test\sampl├¿.mdb,

ogrinfo failed - unable to open 'C:\test\sampl├¿.mdb'.
```

Using ogr from osgeo Python module (GDAL/OGR 3.9.2) in the QGIS Python console

```python
from osgeo import ogr
ds = ogr.Open("C:/test/samplè.mdb")
print(ds) # -> None
```

Using QGIS with GDAL/OGR 3.9.2: see https://github.com/qgis/QGIS/issues/58980.

### Steps to reproduce the issue

1. download https://github.com/OSGeo/gdal/blob/master/autotest/ogr/data/pgeo/sample.mdb and rename it `samplè.mdb`
2. try to open / import it

### Versions and provenance

3.9.2 and 3.10.0dev-d0eb0a996a from OSGeo4W on Windows 10

### Additional context

On the system is installed the Microsoft Access Database Engine 64-bit.

The same ESRI Personal GeoDatabase file, but without non ASCII chars in the path / name, can be opened on the same system:

```
ogrinfo C:\test\sample.mdb --debug ON
GDAL: Proxy driver FileGDB *not* registered due to ogr_FileGDB.dll not being found
GDAL: Proxy driver HANA *not* registered due to ogr_HANA.dll not being found
GDAL: Proxy driver KEA *not* registered due to gdal_KEA.dll not being found
GDAL: Proxy driver MSSQLSpatial *not* registered due to ogr_MSSQLSpatial.dll not being found
ODBC: EstablishSession(DRIVER=Microsoft Access Driver (*.mdb, *.accdb);DBQ=C:\test\sample.mdb)
ODBC: SQLDriverConnect(DRIVER=Microsoft Access Driver (*.mdb, *.accdb);DBQ=C:\test\sample.mdb)
ODBC: CatalogNameL: (null)
Schema name: (null)
ODBC: SQLDisconnect()
ODBC: EstablishSession(DRIVER=Microsoft Access Driver (*.mdb, *.accdb);DBQ=C:\test\sample.mdb)
ODBC: SQLDriverConnect(DRIVER=Microsoft Access Driver (*.mdb, *.accdb);DBQ=C:\test\sample.mdb)
ODBC: CatalogNameL: (null)
Schema name: (null)
PGeo: lines: no primary key
PGeo: points: no primary key
PGeo: polys: no primary key
PGeo: non_spatial: no primary key
ODBC: SQLDisconnect()
ODBC: EstablishSession(DRIVER=Microsoft Access Driver (*.mdb, *.accdb);DBQ=C:\test\sample.mdb)
ODBC: SQLDriverConnect(DRIVER=Microsoft Access Driver (*.mdb, *.accdb);DBQ=C:\test\sample.mdb)
ODBC: CatalogNameL: (null)
Schema name: (null)
ODBC: SQLDisconnect()
ODBC: EstablishSession(DRIVER=Microsoft Access Driver (*.mdb, *.accdb);DBQ=C:\test\sample.mdb)
ODBC: SQLDriverConnect(DRIVER=Microsoft Access Driver (*.mdb, *.accdb);DBQ=C:\test\sample.mdb)
ODBC: CatalogNameL: (null)
Schema name: (null)
PGeo: lines: no primary key
PGeo: points: no primary key
PGeo: polys: no primary key
PGeo: non_spatial: no primary key
GDAL: GDALOpen(C:\test\sample.mdb, this=000001B37B24E970) succeeds as PGeo.
INFO: Open of `C:\test\sample.mdb'
      using driver `PGeo' successful.
OGR: GetLayerCount() = 4

1: lines (Multi Line String)
2: points (Point)
3: polys (Multi Polygon)
4: non_spatial (None)
ODBC: SQLDisconnect()
GDAL: GDALClose(C:\test\sample.mdb, this=000001B37B24E970)
```

```python
from osgeo import ogr
ds = ogr.Open("C:/test/sample.mdb")
print(ds) # -> <osgeo.ogr.DataSource; proxy of <Swig Object of type 'OGRDataSourceShadow *' at 0x000002664DB92220> >
print([l.GetName() for l in ds]) # -> ['lines', 'points', 'polys', 'non_spatial']
```

**Comment by rouault** [comment]
Maybe this requires the user to force UTF-8 encoding in Windows settings? See https://stackoverflow.com/a/52186432/23076275

**Comment by rouault** [comment]
Trying a fix in https://github.com/OSGeo/gdal/pull/10961 (I don't have a way of locally checking)

**Comment by agiudiceandrea** [comment]
Thanks! I'll try the workaround described at https://stackoverflow.com/a/52186432/23076275 and the fix in https://github.com/OSGeo/gdal/pull/10961 when it will be merged (it only allows non ASCII chars that are part of the Windows system ANSI codepage, not all the UTF-8 chars. Doesn't it?)
For reference, it looks like ArcMap 9.3.1 can open ESRI Personal GeoDatabase with non ASCII chars, in the file path / name, that can be mapped to the Windows system ANSI codepage.

**Comment by rouault** [comment]
@agiudiceandrea I don't know how practical this would be for you, but we generate a Conda package for each pull request. So potentially you can download https://github.com/rouault/gdal/actions/runs/11224868703/artifacts/2026749578 , uncompress it, uncompress the win-64/libgdal-core-3.9.2-h042995d_2112.tar.bz2 file in it, and then go to the Library/bin directory and run ogrinfo from it...

**Comment by jratike80** [comment]
Have you tried to set the codepage `CHCP 65001` in the command window before running ogrinfo/ogr2ogr? Or does the ODBC driver require system wide setting?

Anyway, it is good to remember  `CHCP 65001`  if there is a need to use non-ascii characters in command line, or if you just want to see the expected characters on the screen. With the default codepage 850 ogrinfo prints some Finnish municipality names ffom GeoPackage, that is always UTF-8, like

```
OGRFeature(SELECT):306
  text1 (String) = Yl├Âj├ñrvi
OGRFeature(SELECT):307
  text1 (String) = Yp├ñj├ñ
OGRFeature(SELECT):308
  text1 (String) = ├äht├ñri
OGRFeature(SELECT):309
  text1 (String) = ├ä├ñnekoski
```

**Comment by rouault** [comment]
> Have you tried to set the codepage `CHCP 65001` in the command window before running ogrinfo/ogr2ogr? Or does the ODBC driver require system wide setting?

I'm not sure that would be sufficient. GDAL command line utilities get their command line arguments as Unicode string on Windows, whatever the code page of the Windows terminal. My assumption is that the ODBC API on Windows expects a string in the current ANSI page of the system, hence the pull request doing a recode from UTF-8 to the current ANSI page. No idea how that is supposed to work with languages that use non-ANSI characters...

**Comment by agiudiceandrea** [comment]
@jratike80 setting `CHCP 65001` in the Windows Command Prompt or in the OSGeo4W shell is only useful in order to correctly display non ASCII chars in the output text of the command.
Consider that ogrinfo can correctly handle non ASCII chars in file path / name for other layers format like ESRI File GeoDatabase or Shapefile or GeoPackage.
