### ISSUE TITLE
[MSVC] Failed to build GDAL on windows with msvc due to "error LNK2019: unresolved external symbol libiconv_open referenced in function main"

### ISSUE THREAD

**Issue by Zhaojun-Liu** [OSGeo/gdal#10970]
### What is the bug?

I built GDAL on Windows with MSVC, it failed to build due to below errors, can you take a look? Thanks.
```
character_set_conv_table_generator.obj : error LNK2019: unresolved external symbol libiconv_open referenced in function main [C:\gitP\OSGeo\gdal\build_amd64\port\character_set_conv_table_generator.vcxproj]
character_set_conv_table_generator.obj : error LNK2019: unresolved external symbol libiconv referenced in function main [C:\gitP\OSGeo\gdal\build_amd64\port\character_set_conv_table_generator.vcxproj]
character_set_conv_table_generator.obj : error LNK2019: unresolved external symbol libiconv_close referenced in function main [C:\gitP\OSGeo\gdal\build_amd64\port\character_set_conv_table_generator.vcxproj]
C:\gitP\OSGeo\gdal\build_amd64\port\Release\character_set_conv_table_generator.exe : fatal error LNK1120: 3 unresolved externals [C:\gitP\OSGeo\gdal\build_amd64\port\character_set_conv_table_generator.vcxproj]
character_set_conv_table_generator.obj : error LNK2019: unresolved external symbol libiconv_open referenced in function main [C:\gitP\OSGeo\gdal\build_amd64\port\character_set_conv_table_generator.vcxproj]
character_set_conv_table_generator.obj : error LNK2019: unresolved external symbol libiconv referenced in function main [C:\gitP\OSGeo\gdal\build_amd64\port\character_set_conv_table_generator.vcxproj]
character_set_conv_table_generator.obj : error LNK2019: unresolved external symbol libiconv_close referenced in function main [C:\gitP\OSGeo\gdal\build_amd64\port\character_set_conv_table_generator.vcxproj]
C:\gitP\OSGeo\gdal\build_amd64\port\Release\character_set_conv_table_generator.exe : fatal error LNK1120: 3 unresolved externals [C:\gitP\OSGeo\gdal\build_amd64\port\character_set_conv_table_generator.vcxproj]
```

### Steps to reproduce the issue

1. git clone https://github.com/OSGeo/gdal C:\gitP\OSGeo\gdal
2.  vcpkg install --recurse **proj libiconv** --triplet x64-windows
3. mkdir C:\gitP\OSGeo\gdal\build_amd64 and cd C:\gitP\OSGeo\gdal\build_amd64
4. cmake -G "Visual Studio 17 2022" -A x64 -DCMAKE_SYSTEM_VERSION=10.0.22621.0 -DGDAL_BUILD_OPTIONAL_DRIVERS=OFF -DOGR_BUILD_OPTIONAL_DRIVERS=OFF -DCMAKE_CXX_COMPILER_LAUNCHER="clcache" -DCMAKE_UNITY_BUILD=OFF -DBUILD_TESTING=OFF -DCMAKE_TOOLCHAIN_FILE=C:\gitP\Microsoft\vcpkg\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows ..
5. set include=C:\gitP\Microsoft\vcpkg/installed/x64-windows/include;%include%
6. set libpath=C:\gitP\Microsoft\vcpkg/installed/x64-windows/debug/lib;%libpath%
7. msbuild /m /p:Platform=x64 /p:Configuration=Release gdal.sln /t:Rebuild /p:useenv=true

### Versions and provenance

OS: Windows Server 2022 21H2
GDAL: the latest commit 9c27570

### Additional context

[Build.log](https://github.com/user-attachments/files/17304956/Build.log)
[Setup.log](https://github.com/user-attachments/files/17304957/Setup.log)

**Comment by rouault** [comment]
@Zhaojun-Liu Can you give a try to https://github.com/OSGeo/gdal/pull/10971 ?

**Comment by Zhaojun-Liu** [comment]
> @Zhaojun-Liu Can you give a try to #10971 ?

I tried the #10971, it worked. Thanks.
