### ISSUE TITLE
Gdalwarp producing multiple copies of input image at incorrect positions

### ISSUE THREAD

**Issue by bch4132** [OSGeo/gdal#10975]
### What is the bug?

Gdalwarp is producing artifacts in output when using -te arguments larger than bounds of the input

### Steps to reproduce the issue

[repro.zip](https://github.com/user-attachments/files/17311441/repro.zip)
Inside the zip attached there is tiff file used as input. When running this through gdal with the following arguments:
`-t_srs "+proj=longlat +datum=WGS84 +ellps=WGS84 +no_defs +type=crs" -of GTiff -co "TILED=YES" -co "BLOCKXSIZE=1024" -co "BLOCKYSIZE=1024" -co "BIGTIFF=YES" -wm 500 -wo "NUM_THREADS=ALL_CPUS" -multi -co "COMPRESS=ZSTD" -co "NUM_THREADS=ALL_CPUS"  -dstnodata -32767.0 -ot Float32 -te -81.500000000000 28.500000000000 -81.000000000000 29.000000000000 -r near "n4.tif" "Repro_hgt.tif"`
There are copies of the input produced on the left and right side of where the actual input should be on the resulting image.

Input image: 
![image](https://github.com/user-attachments/assets/e7fbf922-7aac-4601-863c-3ac9c8d727a5)
Resulting output:
![image](https://github.com/user-attachments/assets/2e281d8f-753f-4689-8f04-1c2f58e76aa6)

### Versions and provenance

I have tested with multiple versions, including 3.6.2, 3.9.2 (from QGIS install), as well as 3.10.0dev-d04e73dfbd from a source build all with the same result.

**Comment by jratike80** [comment]
I could re-produce on Windows with GDAL 3.9.1. Without `-te` the output is good and corner coordinates are:

Corner Coordinates:
```
Upper Left  ( -81.1762512,  28.6631436) ( 81d10'34.50"W, 28d39'47.32"N)
Lower Left  ( -81.1762512,  28.6354970) ( 81d10'34.50"W, 28d38' 7.79"N)
Upper Right ( -81.1317603,  28.6631436) ( 81d 7'54.34"W, 28d39'47.32"N)
Lower Right ( -81.1317603,  28.6354970) ( 81d 7'54.34"W, 28d38' 7.79"N)
Center      ( -81.1540058,  28.6493203) ( 81d 9'14.42"W, 28d38'57.55"N)
```

**Comment by jratike80** [comment]
I think that the issue must have something to do with those arc-seconds. If I first warp the image into EPSG:4326 without any parameters, and then this interim image into the target extent, then the result looks good.

I have removed all parameters which I thought are not essential.

`gdalwarp -t_srs epsg:4326 -te -81.500000000000 28.500000000000 -81.000000000000 29.000000000000 "repro_interim_4326.tif" "Repro_4.tif"`

**Comment by rouault** [comment]
> I think that the issue must have something to do with those arc-seconds.

Exactly. Fix in https://github.com/OSGeo/gdal/pull/10988
