### ISSUE TITLE
GDAL reporting incorrect BlockSize for JPEG2000 NITF bands and possible other types

### ISSUE THREAD

**Issue by chuck1987** [OSGeo/gdal#10978]
### What is the bug?

When converting to NITF with JPEG200 compression I expect the bands to default to **BLOCKXSIZE=BLOCKYSIZE=1024**.
However, I noticed through **gdal_info**, and through the bindings **test.GetRasterBand(1).GetBlockYSize()** I get a value of 256.

Even when setting the creation options BLOCKXSIZE/BLOCKYSIZE explicitly, the result always says its 256.

### Steps to reproduce the issue

.\gdal_translate.exe .\input.ntf .\output.ntf -co IC=C8 -co JPEG2000_DRIVER=JP2OpenJPEG **-> BlockSize reported as 256**
.\gdal_translate.exe .\input.ntf .\output.ntf -co IC=C8 -co JPEG2000_DRIVER=JP2OpenJPEG -co BLOCKXSIZE=1024 -co BLOCKYSIZE=1024 **-> BlockSize reported as 256**

**NOTE:**

When running **gdalinfo**  command against these files for **GDAL 3.0.4** the expected result is returned, making be believe that the translation actually sets the correct blocksize, but it is not reported correctly.

### Versions and provenance

Windows/Linux
3.10

**Comment by chuck1987** [comment]
I am noticing now that this is a result of me creating the JPEG2000 file with OpenJPEG2 , yet GDAL attempting to read the content with JP2ECW.

Once I disabled the JP2ECW plugin completely, I got the correct block size returned through gdal_info and the bindings.

**Comment by jratike80** [comment]
It is nowadays enough to tell what driver to use:

`gdalinfo -if jp2openjpeg block1024.jp2`

**Comment by chuck1987** [comment]
Yea, we can probably close this issue. I assume the JP2ECW driver should still return the correct blocksize, but this is no longer an issue.

**Comment by jratike80** [comment]
Can you try with some other software that is using the same version of the EWC SDK? If that has the same issue with reporting the tile size then the bug is in the SDK and only Hexagon can fix it.

**Comment by chuck1987** [comment]
tmpfilename = "/vsimem/nitf_28_jp2ecw.ntf"
        src_ds = gdal.GetDriverByName("MEM").Create("", 1025, 1025)
        gdal.GetDriverByName("NITF").CreateCopy(tmpfilename, src_ds, options=["IC=C8"])
        ds = gdal.Open(tmpfilename)
        blockxsize, blockysize = ds.GetRasterBand(1).GetBlockSize()
        ds = None
        gdal.Unlink(tmpfilename)
        assert (blockxsize, blockysize) == (
            256,
            256,
        )   # 256 since this is hardcoded as such in the ECW driver


I see this in the nitf python test file. Seems to indicate that blocksize 256 is hardcoded in the ECW driver.

**Comment by NeoLaurens** [comment]
Could it be the case this is the cause of the errors I am getting?
I can no longer read ECW from S3🤔 When reading a patch from rasterio, I get a segmentation fault.
Similarly; when opening the ECW from QGIS I get: 

Windows fatal exception: access violation

However; when I load it at the minimum zoomlevel; it seems to do fine, and likewise, if I zoom in all the way; then load the ECW, it seems ok for a bit but also crashes sometimes.

QGIS uses GDAL 3.10.2; but I get the same error on older GDAL versions.

I can imagine an incorrect blocksize could cause segmentation errors? maybe?
I also only get this over S3, for different machines; different ECW's, all the same error.
The same file locally loads perfectly well.
