### ISSUE TITLE
Parse ogcapi TileMatrixSet crs object

### ISSUE THREAD

**Issue by kudlav** [OSGeo/gdal#10989]
### What's the bug?

The `crs` property of the OGC API tileMatrixSet can be a string and also one of the following objects:

```json
"crs": { "uri": "http://www.opengis.net/def/crs/EPSG/0/3857" }
# `ERROR 1: Cannot parse CRS { "uri": "http:\/\/www.opengis.net\/def\/crs\/EPSG\/0\/3857" }`
```

```json
"crs": { "wkt": "PROJCS[\"WGS 84 / Pseudo-Mercator\",GEOGCS[\"WGS 84\",DATUM[\"WGS_1984\",SPHEROID[\"WGS 84\",6378137,298.257223563,AUTHORITY[\"EPSG\",\"7030\"]],AUTHORITY[\"EPSG\",\"6326\"]],PRIMEM[\"Greenwich\",0,AUTHORITY[\"EPSG\",\"8901\"]],UNIT[\"degree\",0.0174532925199433,AUTHORITY[\"EPSG\",\"9122\"]],AUTHORITY[\"EPSG\",\"4326\"]],PROJECTION[\"Mercator_1SP\"],PARAMETER[\"central_meridian\",0],PARAMETER[\"scale_factor\",1],PARAMETER[\"false_easting\",0],PARAMETER[\"false_northing\",0],UNIT[\"metre\",1,AUTHORITY[\"EPSG\",\"9001\"]],AXIS[\"Easting\",EAST],AXIS[\"Northing\",NORTH],EXTENSION[\"PROJ4\",\"+proj=merc +a=6378137 +b=6378137 +lat_ts=0 +lon_0=0 +x_0=0 +y_0=0 +k=1 +units=m +nadgrids=@null +wktext +no_defs\"],AUTHORITY[\"EPSG\",\"3857\"]]" }
# ERROR 1: PROJ: proj_create: [json.exception.parse_error.101] parse error at line 1, column 698: syntax error while parsing value - invalid string: missing closing quote; last read: '"PROJCS[\"WGS 84 \/ Pseudo-Mercator\",GEOGCS[\"WGS 84\",DATUM[\"WGS_1984\",SPHEROID[\"WGS 84\",6378137,298.257223563,AUTHORITY[\"EPSG\",\"7030\"]],AUTHORITY[\"EPSG\",\"6326\"]],PRIMEM[\"Greenwich\",0,AUTHORITY[\"EPSG\",\"8901\"]],UNIT[\"degree\",0.0174532925199433,AUTHORITY[\"EPSG\",\"9122\"]],AUTHORITY[\"EPSG\",\"4326\"]],PROJECTION[\"Mercator_1SP\"],PARAMETER[\"central_meridian\",0],PARAMETER[\"scale_factor\",1],PARAMETER[\"false_easting\",0],PARAMETER[\"false_northing\",0],UNIT[\"metre\",1,AUTHORITY[\"EPSG\",\"9001\"]],AXIS[\"Easting\",EAST],AXIS[\"Northing\",NORTH],EXTENSION[\"PROJ4\",\"+proj=merc +a=6378137 +b=6378137 +lat_ts=0 +lon_0=0 +x_0=0 +y_0=0 +k=1 +units=m +nadgrids='
# ERROR 1: Cannot parse CRS { "wkt": "PROJCS[\"WGS 84 \/ Pseudo-Mercator\",GEOGCS[\"WGS 84\",DATUM[\"WGS_1984\",SPHEROID[\"WGS 84\",6378137,298.257223563,AUTHORITY[\"EPSG\",\"7030\"]],AUTHORITY[\"EPSG\",\"6326\"]],PRIMEM[\"Greenwich\",0,AUTHORITY[\"EPSG\",\"8901\"]],UNIT[\"degree\",0.0174532925199433,AUTHORITY[\"EPSG\",\"9122\"]],AUTHORITY[\"EPSG\",\"4326\"]],PROJECTION[\"Mercator_1SP\"],PARAMETER[\"central_meridian\",0],PARAMETER[\"scale_factor\",1],PARAMETER[\"false_easting\",0],PARAMETER[\"false_northing\",0],UNIT[\"metre\",1,AUTHORITY[\"EPSG\",\"9001\"]],AXIS[\"Easting\",EAST],AXIS[\"Northing\",NORTH],EXTENSION[\"PROJ4\",\"+proj=merc +a=6378137 +b=6378137 +lat_ts=0 +lon_0=0 +x_0=0 +y_0=0 +k=1 +units=m +nadgrids=@null +wktext +no_defs\"],AUTHORITY[\"EPSG\",\"3857\"]]" }
```

But QGIS can handle only a string value:

```json
"crs": "http://www.opengis.net/def/crs/EPSG/0/3857"
```

See: [schema](https://github.com/opengeospatial/ogcapi-tiles/blob/1.0.0/openapi/schemas/common-geodata/crs.yaml), [swagger](https://petstore.swagger.io/?url=https://raw.githubusercontent.com/opengeospatial/ogcapi-tiles/master/openapi/ogcapi-tiles-1.bundled.json#/Vector%20Tiles/.dataset.style.vector.getTileSet)

### Proposed solution

`OGCAPIDataset::InitWithTilesAPI` uses `gdal::TileMatrixSet::parse`

https://github.com/OSGeo/gdal/blob/7060762f169cabc6a40ee1111f17b5be925e4c83/frmts/ogcapi/gdalogcapidataset.cpp#L1914

where GDAL expects only a string value 

https://github.com/OSGeo/gdal/blob/7060762f169cabc6a40ee1111f17b5be925e4c83/gcore/tilematrixset.cpp#L220-L225

GDAL IS ABLE to parse the values of `crs.uri` and `crs.wkt`:

```
❌ "crs": { "wkt": "PROJCS[WKTSTRINGHERE]" }
✅ "crs": "PROJCS[WKTSTRINGHERE]"
```

```
❌ "crs": { "uri": "http://www.opengis.net/def/crs/EPSG/0/3857" }
✅ "crs": "http://www.opengis.net/def/crs/EPSG/0/3857"
```

The solution is to detect whether the `crs` is a object or `string`.
1. if it's an object and it contains `uri` property; then `mCrs = crs.uri.c_str()`
2. else if it's an object and it contains `wkt` property; then `mCrs = crs.wkt.c_str()`
3. else `mCrs = crs.c_str()`

This change would fix the above issue, keep it backwards compatible and bring it closer to the OGC API standard.

### Steps to reproduce the issue

minimal JSON endpoints https://gist.github.com/kudlav/965e71731e75ae6e53c4f42055e607ca#file-tilematrixset-json

### Versions and provenance

- Windows 11 (23H2)
- GDAL 3.9.2, released 2024/08/13
- from OSGeo4W

### Additional context

![obrazek](https://github.com/user-attachments/assets/d80f6870-308f-4c59-82b5-8a651f091571)

**Comment by jratike80** [comment]
The standard https://docs.ogc.org/is/17-083r4/17-083r4.html#table4 seems to support 3 alternatives:
- uri
- wkt
- reference system (ISO 19115)

I did not read the standard carefully so I can't say if all 3 alternatives must be supported. The default is uri. If I understand right, `"crs": "http://www.opengis.net/def/crs/EPSG/0/32631"` is uri in JSON encoding. In XML encoding it is expressed as

```
<tmsc:CRS>
      <tmsc:URI>http://www.opengis.net/def/crs/EPSG/0/32631</tmsc:URI>
</tmsc:CRS>
```
I think that `"crs": { "uri": "http://www.opengis.net/def/crs/EPSG/0/3857" }` is nothing, standard does not define that. The standard does define WKT but I understand it in another way than you.

> The WKT encoding for JSON is an object representing a JSON encoding of the WKT for CRS 2.0 defined by https://proj.org/specifications/projjson.html

So it is not like ` "crs": {"wkt": "PROJCS[\"WGS 84 / Pseudo-Mercator\",...` but the WKT content is json as for example projinfo gives it:

```
projinfo epsg:3857 -o projjson
PROJJSON:
{
  "$schema": "https://proj.org/schemas/v0.7/projjson.schema.json",
  "type": "ProjectedCRS",
  "name": "WGS 84 / Pseudo-Mercator",
  "base_crs": {
    "name": "WGS 84",
    "datum_ensemble": {
      "name": "World Geodetic System 1984 ensemble",
      "members": [
        {
          "name": "World Geodetic System 1984 (Transit)",
          "id": {
            "authority": "EPSG",
            "code": 1166
          }
        },
        {
          "name": "World Geodetic System 1984 (G730)",
          "id": {
            "authority": "EPSG",
            "code": 1152
          }
        },
        {
          "name": "World Geodetic System 1984 (G873)",
          "id": {
            "authority": "EPSG",
            "code": 1153
          }
        },
        {
          "name": "World Geodetic System 1984 (G1150)",
          "id": {
            "authority": "EPSG",
            "code": 1154
          }
        },
        {
          "name": "World Geodetic System 1984 (G1674)",
          "id": {
            "authority": "EPSG",
            "code": 1155
          }
        },
        {
          "name": "World Geodetic System 1984 (G1762)",
          "id": {
            "authority": "EPSG",
            "code": 1156
          }
        },
        {
          "name": "World Geodetic System 1984 (G2139)",
          "id": {
            "authority": "EPSG",
            "code": 1309
          }
        }
      ],
      "ellipsoid": {
        "name": "WGS 84",
        "semi_major_axis": 6378137,
        "inverse_flattening": 298.257223563
      },
      "accuracy": "2.0",
      "id": {
        "authority": "EPSG",
        "code": 6326
      }
    },
    "coordinate_system": {
      "subtype": "ellipsoidal",
      "axis": [
        {
          "name": "Geodetic latitude",
          "abbreviation": "Lat",
          "direction": "north",
          "unit": "degree"
        },
        {
          "name": "Geodetic longitude",
          "abbreviation": "Lon",
          "direction": "east",
          "unit": "degree"
        }
      ]
    },
    "id": {
      "authority": "EPSG",
      "code": 4326
    }
  },
  "conversion": {
    "name": "Popular Visualisation Pseudo-Mercator",
    "method": {
      "name": "Popular Visualisation Pseudo Mercator",
      "id": {
        "authority": "EPSG",
        "code": 1024
      }
    },
    "parameters": [
      {
        "name": "Latitude of natural origin",
        "value": 0,
        "unit": "degree",
        "id": {
          "authority": "EPSG",
          "code": 8801
        }
      },
      {
        "name": "Longitude of natural origin",
        "value": 0,
        "unit": "degree",
        "id": {
          "authority": "EPSG",
          "code": 8802
        }
      },
      {
        "name": "False easting",
        "value": 0,
        "unit": "metre",
        "id": {
          "authority": "EPSG",
          "code": 8806
        }
      },
      {
        "name": "False northing",
        "value": 0,
        "unit": "metre",
        "id": {
          "authority": "EPSG",
          "code": 8807
        }
      }
    ]
  },
  "coordinate_system": {
    "subtype": "Cartesian",
    "axis": [
      {
        "name": "Easting",
        "abbreviation": "X",
        "direction": "east",
        "unit": "metre"
      },
      {
        "name": "Northing",
        "abbreviation": "Y",
        "direction": "north",
        "unit": "metre"
      }
    ]
  },
  "scope": "Web mapping and visualisation.",
  "area": "World between 85.06┬░S and 85.06┬░N.",
  "bbox": {
    "south_latitude": -85.06,
    "west_longitude": -180,
    "north_latitude": 85.06,
    "east_longitude": 180
  },
  "id": {
    "authority": "EPSG",
    "code": 3857
  }
}
```
I do not know how the ISO "MD_ReferenceSystem" is supposed to be expressed. There are no usage examples about that in the "OGC Two Dimensional Tile Matrix Set and Tile Set Metadata" standard and I have no access to the ISO standard.

**Comment by kudlav** [comment]
Hi, thanks for the quick response.

There are 4 options how the `crs` can be defined, see:
https://github.com/opengeospatial/ogcapi-tiles/blob/1.0.0/openapi/schemas/common-geodata/crs.yaml

I'm not saying GDAL must implement the whole standard. This change is just improving the current implementation.

It doesn't really matter whether the `crs.wkt` is defined by the OGC standard as a WKT string or JSON object because GDAL is able to load both cases correctly if it reads `crs.wkt` as a string (as proposed above). The GDAL doesn't need to parse it or validate it, it can handle it just as a string value. The following example also works:

```json
"crs": {
  "$schema": "https://proj.org/schemas/v0.7/projjson.schema.json",
  "type": "ProjectedCRS",
  "name": "WGS 84 / Pseudo-Mercator",
  "base_crs": {
    "name": "WGS 84",
    "datum_ensemble": {

```

**Comment by jratike80** [comment]
Right, I did not notice that there were two nested oneOfs. So 4 alternatives.

What do you mean by "It doesn't really matter whether the crs.wkt is defined by the OGC standard as a WKT string or JSON object"? If it is not defined in the standard it should never exist. But I am not so good at writing that standard, perhaps both alternatives are OK.

**Comment by kudlav** [comment]
It was my mistake and you are right. `crs.wkt` is JSON in this standard.
But QGIS still cannot read JSON `crs.wkt`. With this modification, it'd be able to read it.
QGIS can just detect if it's object with `wkt` or `uri` and if so, then try to read it.
