### ISSUE TITLE
gdalrasterize is returning a 3x3 matrix when options request a 2x3

### ISSUE THREAD

**Issue by joa-quim** [OSGeo/gdal#10981]
### What is the bug?

Somehow this commit
```
SHA-1: 462285a9e8101e630bb52a0c7651ce7247d06de7

* Merge pull request #10742 from rouault/netcdf_identify_hdf4_hdf5

netCDF driver: simplify identification logic by just checking runtime  availability of HDF4/HDF5 drivers
```

breaks the GMT Julia wrapper when it calls a `gdalrasterize` wrapper function.

Don't know how best to help but before this commit these options 
["-of", "MEM", "-ts", "3", "2", "-burn", "1", "-ot", "Byte"]
made it return a 2x3 matrix, as required, and after that commit it returns a 3x3 matrix.

In case it helps, the code in question is in https://github.com/GenericMappingTools/GMT.jl/blob/master/src/rasterpolygonfuns.jl#L254  and the input (shapes[4]) is this matrix
```
1.6  2.6
1.6  4.4
4.4  4.4
4.4  2.6
1.6  2.6
```

### Steps to reproduce the issue

Must run the julia code to reproduce it.

```
using GMT

D = mat2ds([1.6 2.6; 1.6 4.4; 4.4 4.4; 4.4 2.6; 1.6 2.6]); im = mat2img(UInt8.(GMT.magic(9)));
colorzones!(D, img=im)
```

### Versions and provenance

Windows 11 and MSVC build

**Comment by joa-quim** [comment]
And it works up to
```
gdalinfo --version
GDAL 3.10.0dev-e78d91e529, released 2024/09/06
```
but not after.

**Comment by rouault** [comment]
> Note that, the [462285a](https://github.com/OSGeo/gdal/commit/462285a9e8101e630bb52a0c7651ce7247d06de7) also changed `gdal_rasterize_bin|lib.cpp`

@joa-quim  No it doesn't. This touches only the netCDF driver only. You must be making a confusion with another commit

**Comment by joa-quim** [comment]
Well, I'm just saying that because my Turtoise GUI shows me this

![image](https://github.com/user-attachments/assets/5754c704-161f-40ba-b4c5-dce288d19ea4)

**Comment by rouault** [comment]
@joa-quim Thanks for reporting. will be fixed per https://github.com/OSGeo/gdal/pull/10983
(Actually the offending commit was 8d9ceabc12c . What you reported was probably the commit at which you had updated, not the one that caused the issue. anyway that's just nit-picking)

**Comment by joa-quim** [comment]
Hmm, the problem is solved as now it return the 2x3 matrix that the Julia test expected, but oddly, on CLI, this still fails

```
C:\v>gdal_rasterize -ts 3 2 -burn 1 -ot Byte D.gpkg D.tiff
Usage: gdal_rasterize [--help] [--help-general]
       [-b <band>]... [-i] [-at]
       [-oo <NAME>=<VALUE>]...
       {[-burn <value>]... | [-a <attribute_name>] | [-3d]} [-add]
       [-l <layername>]... [-where <expression>] [-sql <select_statement>|@<filename>]
       [-dialect <dialect>] [-of <format>] [-a_srs <srs_def>] [-to <NAME>=<VALUE>]...
       [-co <NAME>=<VALUE>]... [-a_nodata <value>] [-init <value>]...
       [-te <xmin> <ymin> <xmax> <ymax>] [-tr <xres> <yres>] [-tap] [-ts <width> <height>]
       [-ot {Byte/Int8/Int16/UInt16/UInt32/Int32/UInt64/Int64/Float32/Float64/
             CInt16/CInt32/CFloat32/CFloat64}] [-optim {AUTO|VECTOR|RASTER}] [-q]
       <src_datasource> <dst_filename>

FAILURE: No output file specified.
```

**Comment by jratike80** [comment]
Do you mean the `FAILURE: No output file specified.` error? I was wondering where did you get it. I didn't, and the error means that somehow the command line arguments are not parsed correctly. The command did work for me by copy-paste, so I guess that there are no invisible/odd characters in the command. I would still rewrite the command carefully with a keyboard.

**Comment by joa-quim** [comment]
Yes, the online synopsis and that error. Note, for me this error started to occur in the same commit (did not check this thoroughly) that broke the file size. I mean, it worked before, but no longer.

**Comment by jratike80** [comment]
Odd. With OSGeo4W

```
gdalinfo --version
GDAL 3.10.0dev-4e28921731, released 2024/10/07
gdal_rasterize -ts 3 2 -burn 1 -ot Byte D.gpkg F.tiff
0...10...20...30...40...50...60...70...80...90...100 - done.
```

**Comment by joa-quim** [comment]
Indeed, very strange. It does work with a somewhat older OSGeo4W build

```
c:\v>gdalinfo --version
GDAL 3.9.1, released 2024/06/22
```

**Comment by jratike80** [comment]
Are you sure that the new version that you have is really new? The argument parser that was added lately gives different and more readable errors, like
```
gdal_rasterize -ts 3 2 -burn 1 -ot Byte D.gpkg
ERROR 1: dst_filename: 1 argument(s) expected. 0 provided.
Usage: gdal_rasterize [--help] [--long-usage] [--help-general]
...
```

**Comment by jratike80** [comment]
And what with a proper command?
`gdal_rasterize -ts 3 2 -burn 1 -ot Byte D.dpkg out.tif`

**Comment by rouault** [comment]
> Yes, I get the same parsing message :)

actually, not, yours lack the "[--long-usage]". There's something particular in your setup that we are missing. Aren't you mixing the "gdal_rasterize" binary from one build with the libgdal.dll from another build, or something like that?

**Comment by joa-quim** [comment]
> actually, not, yours lack the "[--long-usage]".

Because I trimmed it

```
gdal_rasterize -ts 3 2 -burn 1 -ot Byte D.dpkg
ERROR 1: dst_filename: 1 argument(s) expected. 0 provided.
Usage: gdal_rasterize [--help] [--help-general]
       [-b <band>]... [-i] [-at]
       [-oo <NAME>=<VALUE>]...
       {[-burn <value>]... | [-a <attribute_name>] | [-3d]} [-add]
       [-l <layername>]... [-where <expression>] [-sql <select_statement>|@<filename>]
       [-dialect <dialect>] [-of <format>] [-a_srs <srs_def>] [-to <NAME>=<VALUE>]...
       [-co <NAME>=<VALUE>]... [-a_nodata <value>] [-init <value>]...
       [-te <xmin> <ymin> <xmax> <ymax>] [-tr <xres> <yres>] [-tap] [-ts <width> <height>]
       [-ot {Byte/Int8/Int16/UInt16/UInt32/Int32/UInt64/Int64/Float32/Float64/
             CInt16/CInt32/CFloat32/CFloat64}] [-optim {AUTO|VECTOR|RASTER}] [-q]
       <src_datasource> <dst_filename>
```

**Comment by joa-quim** [comment]
> And what with a proper command?
gdal_rasterize -ts 3 2 -burn 1 -ot Byte D.dpkg out.tif

That's what I reported several times above. It fails and prints the synopsis

**Comment by jratike80** [comment]
Now have a cup of coffee and open your eyes. This line is different for me (thank Even for noticing):

Usage: gdal_rasterize [--help] **[--long-usage]** [--help-general]

```
gdal_rasterize -ts 3 2 -burn 1 -ot Byte D.gpkg
ERROR 1: dst_filename: 1 argument(s) expected. 0 provided.
Usage: gdal_rasterize [--help] [--long-usage] [--help-general]
                      [-b <band>]... [-i] [-at]
                      [[-burn <value>]...|[-a <attribute_name>]|[-3d]]
                      [-add]
                      [[-l <layer_name>]...|[-sql <sql_statement>]]
                      [-where <expression>] [-dialect <sql_dialect>] [-a_nodata <value>] [-init <value>]...
                      [-a_srs <srs_def>] [-to <NAME>=<VALUE>]... [-te <xmin> <ymin> <xmax> <ymax>]
                      [[-tr <xres> <yres>]|[-ts <width> <height>]]
                      [-tap] [-optim AUTO|VECTOR|RASTER] [-co <NAME>=<VALUE>]...
                      [-ot Byte|Int8|[U]Int{16|32|64}|CInt{16|32}|[C]Float{32|64}] [-of <output_format>]
                      [-oo <NAME>=<VALUE>]... [--quiet]
                      <src_datasource> <dst_filename>
```

**Comment by rouault** [comment]
> Because I trimmed it

no! That's just not the help message of gdal_rasterize from master. This is the one from GDAL 3.9 (or from an older GDAL master prior to the conversion of gdal_rasterize to using argparser). You're definitely mixing GDAL versions here

**Comment by joa-quim** [comment]
OK, I'll investigate more. I should not be the gdal.dll because, being aware of these problems, I maintain only one of it (with a unique name) that I symlink from a unique location. But yes, something fishy is going one here. Weird that it worked for older master versions.

**Comment by joa-quim** [comment]
Shouldn't it be possible to download the binaries that are created for the CI tests?

I found the why for the difference between the help messages. While I'm very careful with the dll because of the conflicts. I'm more loose with the binaries and indeed I was using an older  `gdal_rasterize` binary. I now get

```
gdal_rasterize -ts 3 2 -burn 1 -ot Byte D.dpkg
ERROR 1: dst_filename: 1 argument(s) expected. 0 provided.
Usage: gdal_rasterize [--help] [--long-usage] [--help-general]
                      [-b <band>]... [-i] [-at]
                      [[-burn <value>]...|[-a <attribute_name>]|[-3d]]
                      [-add]
                      [[-l <layer_name>]...|[-sql <sql_statement>]]
                      [-where <expression>] [-dialect <sql_dialect>] [-a_nodata <value>] [-init <value>]...
                      [-a_srs <srs_def>] [-to <NAME>=<VALUE>]... [-te <xmin> <ymin> <xmax> <ymax>]
                      [[-tr <xres> <yres>]|[-ts <width> <height>]]
                      [-tap] [-optim AUTO|VECTOR|RASTER] [-co <NAME>=<VALUE>]...
                      [-ot Byte|Int8|[U]Int{16|32|64}|CInt{16|32}|[C]Float{32|64}] [-of <output_format>]
                      [-oo <NAME>=<VALUE>]... [--quiet]
                      <src_datasource> <dst_filename>


... but

C:\v>gdal_rasterize -ts 3 2 -burn 1 -ot Byte D.dpkg D.tiff
ERROR 4: D.dpkg: No such file or directory
```

**Comment by rouault** [comment]
> Shouldn't it be possible to download the binaries that are created for the CI tests?

Cf "GDAL master Conda builds": https://gdal.org/en/latest/download.html#gdal-master-conda-builds

**Comment by joa-quim** [comment]
NOT A COFFEE, MAYBE A SLIP (night here)

It helps when one uses the right file name

```
C:\v>gdal_rasterize -ts 3 2 -burn 1 -ot Byte D.gpkg D.tiff
0...10...20...30...40...50...60...70...80...90...100 - done.
```

it's **.gpkg**, not **.dpkg**
