### ISSUE TITLE
MVT: files don't get written to directories [master]

### ISSUE THREAD

**Issue by tobwen** [OSGeo/gdal#1099]
### Expected behavior
PBF files should be written in DIRECTORY. This means that tiles are written in a hierarchy like out_dir/{z}/{x}/{y}.pbf
### Actual behavior
Only default file for TEMPORARY_DB gets written, first subdirectory also gets created, but without any content inside.

## Steps to reproduce the problem.
```ogr2ogr -progress --config GDAL_NUM_THREADS 8 -f MVT buildings "stock_buildings.shp" -dsco NAME="buildings" -dsco DESCRIPTION="stock of buildings" -dsco TYPE=overlay -dsco FORMAT=DIRECTORY -dsco MAXZOOM=22```

## Operating system
Microsoft Windows 7 Pro (x64), Microsoft Windows 10 Pro (x64)

## GDAL version and provenance
- doesn't work for GDAL 2.4.0dev, released 2018/99/99 from OSGeo4W (updated 2018-11-13)
- works for GDAL 2.3.2, released 2018/09/21 from OSGeo4W (updated 2018-11-13)

**Comment by tobwen** [comment]
Yep, your testcase works. I wonder, why the shapefile works on stable GDAL. Does some debug output help you?

**Comment by rouault** [comment]
Access to the shapefile would be easier. But before check with ogrinfo that the SRS is properly recognized

**Comment by tobwen** [comment]
> Access to the shapefile would be easier. But before check with ogrinfo that the SRS is properly recognized

The points in there are under copyright. But ogrinfo gets them right (here is master):

```
Metadata:
  DBF_DATE_LAST_UPDATE=2018-11-13
Geometry: Point
Feature Count: 20209
Extent: (292243.000000, 5576969.000000) - (529590.000000, 5960925.000000)
Layer SRS WKT:
PROJCS["ETRS89 / UTM zone 32N",
    GEOGCS["ETRS89",
        DATUM["European_Terrestrial_Reference_System_1989",
            SPHEROID["GRS 1980",6378137,298.257222101,
                AUTHORITY["EPSG","7019"]],
            TOWGS84[0,0,0,0,0,0,0],
            AUTHORITY["EPSG","6258"]],
        PRIMEM["Greenwich",0,
            AUTHORITY["EPSG","8901"]],
        UNIT["degree",0.0174532925199433,
            AUTHORITY["EPSG","9122"]],
        AUTHORITY["EPSG","4258"]],
    PROJECTION["Transverse_Mercator"],
    PARAMETER["latitude_of_origin",0],
    PARAMETER["central_meridian",9],
    PARAMETER["scale_factor",0.9996],
    PARAMETER["false_easting",500000],
    PARAMETER["false_northing",0],
    UNIT["metre",1,
        AUTHORITY["EPSG","9001"]],
    AXIS["Easting",EAST],
    AXIS["Northing",NORTH],
    AUTHORITY["EPSG","25832"]]
buildings: Real (24.15)
x_25832: Integer64 (10.0)
y_25832: Integer64 (10.0)
```

**Comment by rouault** [comment]
create a strip down version of the shapefile with ogr2ogr -limit 1 and try with that

**Comment by tobwen** [comment]
It also doesn't work with `-limit 1`, but when trying to create a standalone file for you, I got this error: `ERROR 1: Failed to create field name 'Geb´┐¢ude-': cannot convert to ISO-8859-1`. Seems like the encoding is wrong.

While I'm trying to fix this: I wonder, why it works in _stable_, but not in _master_.

**Comment by rouault** [comment]
@tobwen Did you get a chance of checking this was fixed ?

**Comment by tobwen** [comment]
It works, but there's no difference in processing time and usage between `--GDAL_NUM_THREADS 1` and  `--GDAL_NUM_THREADS 8` anymore. I think that's due my files being too small.

What do you think about parallel processing of a queue, like `< list xargs -P8 -I {} zip {}`?

**Comment by rouault** [comment]
> What do you think about parallel processing of a queue

The driver internally generates creates one job per tile to create and dispach them among thread. I guess this is only effective if you have sufficiently dense / big tiles

**Comment by rouault** [comment]
Actually more than the size of the tiles themselves, that's when you have complexity of geometry clipping operations that multi threading will shine. Otherwise you'll get other contention points: writing in th temporary database, or generally I/O. When testing with complex enough datasets, I remember multithreading helped.

**Comment by tobwen** [comment]
Sure, I've got 22k points only. But better a slow process than a non-working process :)

Good work!
