### ISSUE TITLE
ZARR:  ZARR_V2 created from PNG compression problem with (relatively) small blocks

### ISSUE THREAD

**Issue by mdsumner** [OSGeo/gdal#11016]
### What is the bug?

When creating a ZARR from PNG 20x20x4 (RGBA) and I use compression for ZARR_V2 with small block sizes, I get an error. 

It seems to be about the relative size of the blocks compared to the source, but I didn't detect the pattern. 

### Steps to reproduce the issue

```
gdal_translate gdrivers/data/png/rgba16.png lz4.zarr -of ZARR -co FORMAT=ZARR_V2 -co BLOCKSIZE=4,5,6 -co COMPRESS=LZ4  -co INTERLEAVE=BAND

Input file size is 20, 20
0...10...20...30...40...50ERROR 1: Decompressed tile lz4.zarr/lz4/0.1.2 has not expected size after filters
```

It's fine with COMPRESS=NONE, but other compression-on options error also. 

With larger block sizes it's seemingly ok

```
gdal_translate gdrivers/data/png/rgba16.png lz4.zarr -of ZARR -co FORMAT=ZARR_V2 -co BLOCKSIZE=4,25,26 -co COMPRESS=LZ4  -co INTERLEAVE=BAND

Input file size is 20, 20
0...10...20...30...40...50...60...70...80...90...100 - done.
```

### Versions and provenance

GDAL 3.10.0dev-e3aaf5d09b-dirty, released 2024/10/15

Linux, ubuntu 22.04

### Additional context

Originally reported here with example below: https://lists.osgeo.org/pipermail/gdal-dev/2024-October/059625.html

```
gdal_translate "/vsicurl/https://github.com/cran/png/blob/master/inst/img/Rlogo.png?raw=true" lz4.zarr -of ZARR -co FORMAT=ZARR_V2 -co BLOCKSIZE=4,25,26 -co COMPRESS=LZ4 -co INTERLEAVE=BAND

Input file size is 100, 76
0ERROR 1: Decompressed tile lz4.zarr/lz4/0.0.0 has not expected size after
filters
```

**Comment by rouault** [comment]
Doh, I can't believe such a stupid & obvious bug has stayed for so long: using the compressor instead of the decompressor.... It's there since the beginning of the driver!
