### ISSUE TITLE
GDALRasterizeOptionsNew() returns nullptr for an apparently valid set of arguments (GDAL 3.10.0dev)

### ISSUE THREAD

**Issue by ctoney** [OSGeo/gdal#11028]
### What is the bug?

This is in response to the call for testing GDAL 3.10.0 beta1. The test suite for the R package `gdalraster` shows an error in its wrapper of GDALRasterize(). GDALRasterizeOptionsNew() returns `nullptr` with input arguments that look like:
`-l <layer> -where <where clause> -burn 1 -te <xmin ymin xmax ymax> -ts <xsize ysize> -ot <datatype> -init <value> -of GTiff -co TILED=YES -co COMPRESS=LZW -q`

The error does not appear with GDAL <= 3.9.0.

### Steps to reproduce the issue

Error from the `gdalraster` test suite:
```r
-- Error (test-gdalraster_proc.R:421:5): rasterize runs without error ----------
<Rcpp::exception/C++Error/error/condition>
Error: rasterize failed (could not create options struct)
Backtrace:
    x
 1. \-gdalraster::rasterize(...) at test-gdalraster_proc.R:421:5
 2.   \-gdalraster:::.rasterize(src_dsn, dstfile, argv, quiet)
```
`nullptr` is returned from GDALRasterizeOptionsNew() at line 1892 in:
https://github.com/USDAForestService/gdalraster/blob/9ad48ee644ffce396ee3e516f22b30968a01ab91/src/gdal_exp.cpp#L1892
when passed args like above.

### Versions and provenance

ghcr.io/osgeo/gdal:ubuntu-full-latest
GDAL 3.10.0dev-892f3ecc8d3c6b99004c1575f49fc04ddee9b90a, released 2024/10/13

**Comment by rouault** [comment]
CC @elpaso

**Comment by elpaso** [comment]
I think that the `-q` argument is not accepted (AFAIK it only makes sense for binary but you are passing `nullptr` as binary options GDALRasterizeOptionsForBinary).

@rouault I see it's a regression but it seems to me that this is the correct behavior.

**Comment by rouault** [comment]
@elpaso

In other utilities, gdal_translate namely, we do this:
```
    // Written that way so that in library mode, users can still use the -q
    // switch, even if it has no effect
    argParser->add_quiet_argument(
        psOptionsForBinary ? &(psOptionsForBinary->bQuiet) : nullptr);
```
Perhaps we should ensure we do that consistently for all utilities
