### ISSUE TITLE
no gdalalljni in java.library.path

### ISSUE THREAD

**Issue by Changgf** [OSGeo/gdal#11021]
### What is the bug?

@SpringBootTest
class ColocationApiApplicationTests {

	@Test
	void contextLoads() {
		gdal.AllRegister();
	}

}

no gdalalljni in java.library.path

### Steps to reproduce the issue

brew install gdal

### Versions and provenance

<dependency>
			<groupId>org.gdal</groupId>
			<artifactId>gdal</artifactId>
			<version>3.9.0</version>
		</dependency>

### Additional context

Mac OS Sequoia 15.0.1

**Comment by Changgf** [comment]
java.lang.UnsatisfiedLinkError: 'void org.gdal.gdal.gdalJNI.AllRegister()'

	at org.gdal.gdal.gdalJNI.AllRegister(Native Method)
	at org.gdal.gdal.gdal.AllRegister(gdal.java:719)

**Comment by rouault** [comment]
Much likely the native gdalalljni library and/or libgdal itself are not in a location where they can be found. See https://gdal.org/en/latest/api/java/index.html#how-to-use-the-bindings which covers this
