### ISSUE TITLE
NGSGEOID: incorrect SRS applied to .bin file (none should be applied)

### ISSUE THREAD

**Issue by riveryeti** [OSGeo/gdal#1103]
## Expected behavior and actual behavior.

if I run gdalinfo on a *.bin [downloaded from NGS](https://www.ngs.noaa.gov/PC_PROD/GEOID12B/Format_pc/g2012bu5.bin), I should get no information on SRS (since there isn't any). Instead I get this:

`F:\GIS\GEOIDS\12B>gdalinfo g2012bu1.bin
Driver: NGSGEOID/NOAA NGS Geoid Height Grids
Files: g2012bu1.bin
Size is 1141, 1081
Coordinate System is:
GEOGCS["WGS 84",
    DATUM["WGS_1984",
        SPHEROID["WGS 84",6378137,298.257223563,
            AUTHORITY["EPSG","7030"]],
        AUTHORITY["EPSG","6326"]],
    PRIMEM["Greenwich",0,
        AUTHORITY["EPSG","8901"]],
    UNIT["degree",0.0174532925199433,
        AUTHORITY["EPSG","9122"]],
    AUTHORITY["EPSG","4326"]]
Origin = (229.991666666666674,58.008333333336942)
Pixel Size = (0.016666666666670,-0.016666666666670)
Corner Coordinates:
Upper Left  (     229.992,      58.008) (229d59'30.00"E, 58d 0'30.00"N)
Lower Left  (     229.992,      39.992) (229d59'30.00"E, 39d59'30.00"N)
Upper Right (     249.008,      58.008) (249d 0'30.00"E, 58d 0'30.00"N)
Lower Right (     249.008,      39.992) (249d 0'30.00"E, 39d59'30.00"N)
Center      (     239.500,      49.000) (239d30' 0.00"E, 49d 0' 0.00"N)
Band 1 Block=1141x1 Type=Float32, ColorInterp=Undefined
  Unit Type: m`

The [NGS FAQ](https://www.ngs.noaa.gov/GEOID/GEOID12B/GEOID12B_FAQ.shtml) explicitly defines the .bin format, and no SRS info is given.

 If a SRS is applied, it should be the GRS-80 ellipsoid not WGS84, per [this README](https://www.ngs.noaa.gov/GEOID/GEOID12B/g2012Brme.txt). But since the .bin could be at least NAD 83 or IGS08/GRS-80, it seems like letting the user explicitly assign one and leaving it undefined until then might make sense.

## Steps to reproduce the problem.

1. download a .bin file from NGS like [this one](https://www.ngs.noaa.gov/PC_PROD/GEOID12B/Format_pc/g2012bu5.bin)

2. run gdalinfo g2012bu5.bin

## Operating system

Win10 64 bit

## GDAL version and provenance

GDAL 2.2.4 OSGeo4W

**Comment by rouault** [comment]
Given the pixel size of the datasets being 1 arc-second, ie ~ 1850m, and the difference between NAD83 or IGS08 vs WGS84 being on the order of the metre, I don't think the current approximation would cause much issues in practice, but I've tried to improve that.
