### ISSUE TITLE
vector PDF wrongly recognized as raster-only and not processed

### ISSUE THREAD

**Issue by mbudaj** [OSGeo/gdal#11034]
### What is the bug?

Vector PDFs (e.g. [this minimal example](https://github.com/user-attachments/files/17399792/data.pdf)) containing data in the XObject forms are recognized as raster-only by `ogr2ogr` and therefore not processed at all.

### Steps to reproduce the issue

``` 
> ogr2ogr data.shp data.pdf --debug on
...
PDF: Skipping unknown object /Fm3 at line 3
PDF: ParseContent(): reached line 4
PDF: ParseContent(): reached line 16
PDF: This is a raster-only PDF dataset, but it has been opened in vector-only mode
ERROR 1: Unable to open datasource `data.pdf' with the following drivers.
```

On the other hand, this works fine: 
```
gdal_translate data.pdf data.tiff
```

### Versions and provenance

GDAL 3.9.2, released 2024/08/13 on Debian Trixie.

### Additional context

I presume that XObject forms containing actual data are ignored (see [this line in the code](https://github.com/OSGeo/gdal/blob/5033ea25568aa9e0c7901eeae8b4a5f529bf3325/frmts/pdf/pdfreadvectors.cpp#L1322) and the error message `PDF: Skipping unknown object /Fm3 at line 3`), therefore the program assumes there is no vector data in the file and so it contains just raster data.

**Comment by mbudaj** [comment]
Thanks for creating the fix. 

However, there is another simple file, not using /OC at all, where the fixed ogr2ogr fails: [data2.pdf](https://github.com/user-attachments/files/17438606/data2.pdf)

Could you please look also into this? Should I try to export more complex files perhaps revealing some other border cases?

**Comment by rouault** [comment]
> Could you please look also into this? Should I try to export more complex files perhaps revealing some other border cases?

Well to be honest dealing with PDF is a nightmare, so I'm not particularly looking for headaches for the sake of headaches. Please make use of my time with care ;-)

**Comment by rouault** [comment]
> However, there is another simple file, not using /OC at all, where the fixed ogr2ogr fails: [data2.pdf](https://github.com/user-attachments/files/17438606/data2.pdf)

ok, I've pushed an enhancement so you can get a hint in the debug output;

```
$ ogrinfo data2.pdf --debug PDF -ro
[... snip ...]
PDF: No structured content nor PDF layers detected, hence vector content detection is disabled. You may force vector content detection by setting the OGR_PDF_READ_NON_STRUCTURED configuration option to YES
```

```
$ ogrinfo data2.pdf --config OGR_PDF_READ_NON_STRUCTURED YES -al -q
Metadata:
  NEATLINE=POLYGON ((210703.086326801 5340484.9417464,210703.052955675 5340565.68952771,210892.009246639 5340565.4708787,210892.066729348 5340485.14709807,210703.086326801 5340484.9417464))
  CREATOR=Therion 6.2.1+db1319f+dev (2024-10-16), MetaPost, TeX
  PRODUCER=pdfTeX-1.40.26
  CREATION_DATE=D:20241016173248+02'00'

Layer name: content
OGRFeature(content):0
  Style = PEN(c:#000000);BRUSH(fc:#FFFFFF)
  POLYGON ((210701.049043444 5340482.99032855,210894.105629301 5340482.98353605,210894.057882252 5340567.63259534,210701.001296395 5340567.63938785,210701.049043444 5340482.99032855))

OGRFeature(content):1
  Style = PEN(c:#000000)
  LINESTRING (210719.044079199 5340565.58196092,210703.077661677 5340510.89851925)

OGRFeature(content):2
  Style = PEN(c:#000000)
  LINESTRING (210703.077661677 5340510.89851925,210892.061273409 5340485.04090587)

OGRFeature(content):3
  Style = PEN(c:#000000)
  LINESTRING (210703.077661677 5340510.89851925,210719.044079199 5340565.58196092)

OGRFeature(content):4
  Style = PEN(c:#000000)
  LINESTRING (210892.061273409 5340485.04090587,210703.077661677 5340510.89851925)
```
