### ISSUE TITLE
Add VSIGetMemFileBuffer to C# / .NET bindings

### ISSUE THREAD

**Issue by EmilRybergAkson** [OSGeo/gdal#11032]
### Feature description

Currently there are no way to read out the in-memory bytes of an in memory dataset with the .NET bindings, as far as i know. It would be nice if the VSIGetMemFileBuffer was added to the .NET bindings (and i guess the other ones as well). Currently we are working around this by using P/Invoke directly on the gdal library file, but this of course means we are missing out on exception handling etc.

**Comment by rouault** [comment]
FYI there's nobody currently in the current core maintainter team with C# knowledge, so this is left as an opportunity for contribution to others

**Comment by EmilRybergAkson** [comment]
> FYI there's nobody currently in the current core maintainter team with C# knowledge, so this is left as an opportunity for contribution to others

I have updated the SWIG interface for C# to include this in the bindings. How do i go about creating a PR? I have done it on the 3.9.3 tag locally. Which branch should i target for PR, release/3.9 or release/3.10?

**Comment by rouault** [comment]
> Which branch should i target for PR

master first. We can then decide to backport to the stable branch (that will be release/3.10 now) if appropriate

**Comment by sendreams** [comment]
这个接口非常重要，特别是对于web开发，非常期待也能加入到java binding中。
