### ISSUE TITLE
gdaladdo cannot allocate X bytes

### ISSUE THREAD

**Issue by Kcok** [OSGeo/gdal#11040]
### What is the bug?

The creation of the overviews in a GeoPackage results in error for lower zoom levels, even if less information is need.
`ERROR 2: D:\src\osgeo4w\src\gdal\gdal-3.9.2\gcore\overview.cpp, 5427: cannot allocate 244576154592 bytes`
I am using uncompressed overviews, as per [https://trac.osgeo.org/gdal/ticket/6619](url) suggested, as they suppose to use less memory, as well as starting from a working overview level, but it didn't work either.
Limiting the memory usage (GDAL_CACHE_MAX) does not make any difference.
My GeoPackage is 262000 x 131000 pixels.
I am using GDAL 3.9.2.

### Steps to reproduce the issue

Data set is available: [https://www.dropbox.com/scl/fi/smsfnwkn7u6feuv4wmeg0/Sidney_17ZL.gpkg?rlkey=xqiee5xrzod67auo47j8excn3&st=t2khk74x&dl=0](url)
Zoom levels from 1 to 6 are missing. (from 17)
`gdaladdo Sidney_17ZL.gpkg -r average --config USE_RRD YES 1024 2048 4096 8192 16384 32768 65536`

### Versions and provenance

Windows 10 Enterprise
Processor: Intel(R) Xeon(R) Gold 5317 CPU @ 3.00GHz   2.99 GHz (2 Prozessoren)
RAM: 16Gb
GDAL: 3.9.2

### Additional context

Is there any reliable way to compute all overviews without coming into this problem? My logic tells me to compute the lower level overviews from the already "light-wheighted" calculated overviews. Gdaladdo seams to, on the contrary, load into memory all the data to calculate the low resolution overviews, in which all the image is calculated into 1 tile, instead of loading only the previous tiled overviews.

**Comment by rouault** [comment]
This has been fixed in 3.9.3 per https://github.com/OSGeo/gdal/pull/10720
