### ISSUE TITLE
Missing NITF SPCDF information

### ISSUE THREAD

**Issue by dukesook** [OSGeo/gdal#11045]
### What is the bug?

Despite being listed in nitf_spec.xml, gdalinfo fails to parse out SPDCF information including:
 - SPDCF_ID
 - SPDCF_P
 - SPDCF_FAM
 - SPDCF_WEIGHT
 

### Steps to reproduce the issue

When running gdalinfo on any of the [SNIP RIP NITF files](https://nsgreg.nga.mil/doc/view?i=5523): 

```$ gdalinfo  NITF_IM:1:1p2B_L1R-BSQ.ntf  -mdd all```

The output contains ```BASIC_SR_SPDCF``` and ```POST_SR_SPDCF```, but none of the other SPDCF information.

### Versions and provenance

WSL on Windows 11

**Comment by rouault** [comment]
I do get them using master or 3.9.3
```
          <group index="1">
            <field name="SPDCF_ID" value="02" />
            <field name="SPDCF_P" value="01" />
            <repeated name="CONSTITUENT" number="1">
              <group index="0">
                <field name="SPDCF_FAM" value="0" />
                <field name="SPDCF_WEIGHT" value="1.000" />
                <field name="FP_A" value="1.000000" />
                <field name="FP_ALPHA" value="0.000000" />
                <field name="FP_BETA" value="00.000000" />
                <field name="FP_T" value="+5.00000000000000E+02" />
              </group>
            </repeated>
          </group>
```
I presume this has been fixed per ad3c3d17bba850a0bec2b70354b07f3192e14c12
