### ISSUE TITLE
 Y-axis is reversed when creating (or reading?) multi-dimensional zarr stores

### ISSUE THREAD

**Issue by alistaireverett** [OSGeo/gdal#11041]
### What is the bug?

I originally posted this here: https://github.com/pydata/xarray/issues/8742 but I wonder now if it is rather something to do with gdal.

The issue is that when converting to zarr the y axis is for some reason being flipped (or apparently flipped, according to gdalinfo and gdalbuildvrt which complains about a positive NS resolution). I initially found this issue when creating zarr stores in xarray, but @scottyhq pointed out that it also occurs with gdalmdimtranslate. I've now found out that this works fine with gdal_translate, so I'm a bit confused!

I can see plenty of differences between the files gdal_translate and gdalmdimtranslate produce, but I can't pin down what is causing the apparent flipping of the y-axis. Does anyone have any ideas? Is it that gdal is not reading the projection correctly, or is it something to do with how the zarr store is created?

### Steps to reproduce the issue

With this file: https://github.com/pydata/xarray/files/14266922/in.nc.zip

Gdalinfo on the original file:
```
gdalinfo NETCDF:"in.nc":air_temperature_2m

# Origin = (-1061334.000000000000000,1338732.125000000000000)
# Pixel Size = (2500.000000000000000,-2500.000000000000000)
```

Using gdal_translate (negative, correct):
```
gdal_translate -of ZARR in.nc out-gdal.zarr 
gdalinfo ZARR:"out-gdal.zarr":/air_temperature_2m

# Origin = (-1061334.000000000000000,1338732.125000000000000)
# Pixel Size = (2500.000000000000000,-2500.000000000000000)
```

While using gdalmdimtranslate (positive, incorrect):
```
gdalmdimtranslate -of ZARR in.nc out-gdal.zarr 
gdalinfo ZARR:"out-gdal.zarr":/air_temperature_2m

# Origin = (-1061334.000000000000000,-1333767.875000000000000)
# Pixel Size = (2500.000000000000000,2500.000000000000000)
```

### Versions and provenance

Linux Ubuntu 22.04
GDAL 3.9.2, released 2024/08/13

**Comment by rouault** [comment]
Actually everything is fine. This is just a matter of convention on where the origin is
The netCDF "classic raster" driver tries to present datasets as images, that is with the northern-most line being the line of row=0. So to do that it tweaks the geotransform so that is origin is the norther-most western-most corner, and with a negative yres to reflect the top-to-bottom direction.
The netCDF "multidim raster" driver doesn't do that trick, so you get the "raw" representtion when going through gdalmdimtranslate.
But if you display both datasets in QGIS they perfectly overlap.

**Comment by alistaireverett** [comment]
Thanks for clarifying, the issue for me is there are a number of downstream tools which require a negative y-axis, so it would probably be good if you could choose what convention to use. But at least now I understand the issue. For anyone else who ends up here, a way to get around this I've found is to override the origin of the zarr dataset using a VRT connection string:

```
gdalinfo vrt://ZARR:"out-gdal.zarr":/air_temperature_2m?a_ullr=-1061334.000,1338732.125,1311166.000,-1333767.875
```

**Comment by rouault** [comment]
Overriding the geotransform is a very bad idea. This will only correct the geotransform but to get consistent you would also need to flip the pixel values along the Y axis.
The correct tool for that is gdalwarp
