### ISSUE TITLE
bug when processing landsat 7

### ISSUE THREAD

**Issue by lff5985** [OSGeo/gdal#1106]
## Expected behavior and actual behavior.

For example: I expected to be able to open this raster file (with a link to
the raster file, or it as an attachment) and it returns an error message
instead.

## Steps to reproduce the problem.

For example: "gdalinfo myfile"

## Operating system

For example: Ubuntu 16.04 64 bit

## GDAL version and provenance

For example: the 2.2.3 version from ubuntugis-unstable PPA

**Comment by jratike80** [comment]
The gdal-dev mailing list is the place to ask questions. Before you send mail there improve your question. Consider adding links to some Landsat 8 and Landsat 7 images that could be used for testing, add the complete gdal_pansharpen.py command that you used and mention the GDAL and Python versions. Links to small screenshots which immediately demonstrate what is the right outcome and what is wrong would also be very useful, as also gdalinfo reports (gdalinfo -stats) about the both outputs.
