### ISSUE TITLE
OpenFileGDB: wrong long driver name

### ISSUE THREAD

**Issue by jratike80** [OSGeo/gdal#11079]
### What is the bug?

GDAL shows "ESRI FileGDB" as a long name for the OpenFileGDB driver.

### Steps to reproduce the issue

```
ogrinfo --format OpenFileGDB
Format Details:
  Short Name: OpenFileGDB
  Long Name: ESRI FileGDB
```

### Versions and provenance

GDAL 3.10.0dev-b6edb5191e, released 2024/10/07

**Comment by rouault** [comment]
What would you suggest as long name ?

**Comment by jratike80** [comment]
Can't imagine anything better than "OpenFileGDB".  Now the long name "ESRI FileGDB" makes me think it means https://gdal.org/en/latest/drivers/vector/filegdb.html which has a long name "ESRI File Geodatabase (FileGDB)".

**Comment by rouault** [comment]
what about 'ESRI FileGeodatabase (using OpenFileGDB)' : https://github.com/OSGeo/gdal/pull/11122 ?
