### ISSUE TITLE
Add some create options to JPEGXL Driver to set distances for all extra channels

### ISSUE THREAD

**Issue by lidq92** [OSGeo/gdal#11095]
### Feature description

Is your feature request related to a problem? Please describe.
A bad behavior is found when applying lossy compression of multispectral images using JPEG XL.
This may be caused by the default distance for extra channels (e.g., 0 for lossless compression?).

Describe the solution you'd like
Add some options to set distances for all extra channels.

Describe alternatives you've considered
Set the default distance for extra channels the same as the main channels (first three or RGB).

### Additional context

https://gis.stackexchange.com/questions/487069/gdals-jpegxl-driver-shows-bad-behaviours-for-lossy-compression-of-multispectral

**Comment by jratike80** [comment]
Getting test data from https://github.com/boazarad/ARAD_1K requires registration. Can you suggest anything else?

**Comment by jratike80** [comment]
Ok, I have now a local 96 band image "coffee" from https://github.com/hacarus/hsi-open-dataset/tree/master. That has a "Creative Commons Attribution-NonCommercial 4.0 International License" so OK for testing but not suitable for the GDAL test set, if such need will arise later.
Please test if you can reproduce your issue with the coffee dataset.

You can combine a 96 band tiff with these commands
```
gdalbuildvrt -separate coffee.vrt coffee*.png
gdal_translate coffee.vrt coffee.tif
```

**Comment by jratike80** [comment]
I think that I am using GDAL in a right way, and for me the lossy compression with the highest recommended distance=3 leads to  a  **bigger** file size than the lossless version:

```
gdal_translate -of JPEGXL -co EFFORT=7 -co lossless=yes coffee96.tif coffee96_lossless.jxl
file size: 986076
gdal_translate -of JPEGXL -co EFFORT=7 -co distance=3 coffee96.tif coffee96_lossy3.jxl
file size:  1016334
```
I do not know if the "coffee" image is too small for reasonable tests:
`Size is 192, 256`

**Comment by lidq92** [comment]
> I found that by default the QUALITY/DISTANCE setting only applied to the R,G,B channels, and extra ones were encoded as lossless. Fixe per PR #11099

Thank you! I will have a try based on your branch.

**Comment by lidq92** [comment]
@rouault After updating libheif to a version >= 1.18.0-rc1 (actually I used master 1.19.0), I successfully ran the code based on [rouault/gdal/fix_11095](https://github.com/rouault/gdal/tree/fix_11095).

I have two further questions:
1. It seems `heif_compression_VVC` and some others updated in [commit 122261487950f818df432e853967a7d0adcb0edc](https://github.com/OSGeo/gdal/commit/122261487950f818df432e853967a7d0adcb0edc#diff-50def72c0349b456f1946c49ca32d3c9b7718be3390c194a338a1d7eae0188fb) require `LIBHEIF_NUMERIC_VERSION >= BUILD_LIBHEIF_VERSION(1, 18, 0)`.
2. The libjxl supports d in [0.01, 0.1], but in GDAL, min(d) is 0.1. The result is that the highest lossy point (d=0.1) in GDAL's JPEG XL Driver can only reach a much lower PSNR value than the one can be reached by using cjxl with d=0.01. I also have a question about whether we can remove the clamp function to the distance to allow 0<d<0.1 in [GDAL's jpegxl.cpp](https://github.com/OSGeo/gdal/blob/master/frmts/jpegxl/jpegxl.cpp) or d < 0.01 in libjxl? I also have [a question about the mapping from quality to distance](https://github.com/libjxl/libjxl/discussions/3492#discussioncomment-10771776) since this mapping results in a d value larger than 0.1.

**Comment by lidq92** [comment]
> @rouault After updating libheif to a version >= 1.18.0-rc1 (actually I used master 1.19.0), I successfully ran the code based on [rouault/gdal/fix_11095](https://github.com/rouault/gdal/tree/fix_11095).
> 
> I have two further questions:
> 
> 1. It seems `heif_compression_VVC` and some others updated in [commit 122261487950f818df432e853967a7d0adcb0edc](https://github.com/OSGeo/gdal/commit/122261487950f818df432e853967a7d0adcb0edc#diff-50def72c0349b456f1946c49ca32d3c9b7718be3390c194a338a1d7eae0188fb) require `LIBHEIF_NUMERIC_VERSION >= BUILD_LIBHEIF_VERSION(1, 18, 0)`.
> 2. The libjxl supports d in [0.01, 0.1], but in GDAL, min(d) is 0.1. The result is that the highest lossy point (d=0.1) in GDAL's JPEG XL Driver can only reach a much lower PSNR value than the one can be reached by using cjxl with d=0.01. I also have a question about whether we can remove the clamp function to the distance to allow 0<d<0.1 in [GDAL's jpegxl.cpp](https://github.com/OSGeo/gdal/blob/master/frmts/jpegxl/jpegxl.cpp) or d < 0.01 in libjxl? I also have [a question about the mapping from quality to distance](https://github.com/libjxl/libjxl/discussions/3492#discussioncomment-10771776) since this mapping results in a d value larger than 0.1.

About my second question, I got some helps from libjxl:
https://github.com/libjxl/libjxl/issues/1763
https://github.com/libjxl/libjxl/pull/3622
https://github.com/libjxl/libjxl/pull/3611

**Comment by rouault** [comment]
> 1. It seems `heif_compression_VVC` and some others updated in [commit 122261487950f818df432e853967a7d0adcb0edc](https://github.com/OSGeo/gdal/commit/122261487950f818df432e853967a7d0adcb0edc#diff-50def72c0349b456f1946c49ca32d3c9b7718be3390c194a338a1d7eae0188fb) require `LIBHEIF_NUMERIC_VERSION >= BUILD_LIBHEIF_VERSION(1, 18, 0)`.

@bradh can you have a look at that?

**Comment by bradh** [comment]
> > 1. It seems `heif_compression_VVC` and some others updated in [commit 122261487950f818df432e853967a7d0adcb0edc](https://github.com/OSGeo/gdal/commit/122261487950f818df432e853967a7d0adcb0edc#diff-50def72c0349b456f1946c49ca32d3c9b7718be3390c194a338a1d7eae0188fb) require `LIBHEIF_NUMERIC_VERSION >= BUILD_LIBHEIF_VERSION(1, 18, 0)`.
> 
> @bradh can you have a look at that?

Had a look. I can see it'll need to be more recent than 1.12, but I'm not sure where the 1.18 requirement is coming from. The history suggests 1.15.0, for both VVC and JPEG2000, based on this commit: https://github.com/strukturag/libheif/commit/266441bae67d800564d64d5a2314dc23aba7e743

I'll submit a PR.

@lidq92 why do you say `LIBHEIF_NUMERIC_VERSION >= BUILD_LIBHEIF_VERSION(1, 18, 0)` ? Just what you tested, or something that didn't work in 1.17?

**Comment by bradh** [comment]
#11106 is the fixes. Further digging identified later versions (up to and including 1.18, for HT-J2K) may be required.

**Comment by lidq92** [comment]
@bradh I searched `heif_compression_VVC` in `libheif` and found it appeared in 1.18.0-rc1 but not in 1.17 and the versions before. Maybe it is not a core file, and I did not remember the file name. Yes, it'll need to be more recent than 1.12. But I am not sure the minimum version required, based on your info, maybe 1.15 is ok.

**Comment by jratike80** [comment]
Is there a need to open a new issue about libheif? Discussion within this issue does not serve well the community.
