### ISSUE TITLE
Inconsistent handling of Nan and Infinity with Geojson driver

### ISSUE THREAD

**Issue by rbuffat** [OSGeo/gdal#1109]
## Expected behavior and actual behavior.

According to the json specification (https://tools.ietf.org/html/rfc8259#section-6) nan and infinity are not permitted:

`Numeric values that cannot be represented in the grammar below (such as Infinity and NaN) are not permitted.`

The Geojson driver (Gdal version 2020300) allows to create Geojson files including these values: https://github.com/OSGeo/gdal/blob/master/gdal/ogr/ogrsf_frmts/geojson/ogrgeojsonwriter.cpp#L1513-L1521
https://github.com/Toblerity/Fiona/issues/684
However such files can not be read again by ogr. 

Expected behavior: the geojson driver should either reject nan, +inf, or -inf or read files containing these values.

## Steps to reproduce the problem.

The following code:

```
from osgeo import ogr
import os

# Input data
pointCoord = -124.4577,48.0135

# the value we test for
vals = [float('nan'), float('inf'), float('-inf')]

outSHPfn = 'test.json'

# Create the output shapefile
shpDriver = ogr.GetDriverByName("GeoJSON")
if os.path.exists(outSHPfn):
    shpDriver.DeleteDataSource(outSHPfn)

outDataSource = shpDriver.CreateDataSource(outSHPfn)
outLayer = outDataSource.CreateLayer(outSHPfn, geom_type=ogr.wkbPoint )

#create point geometry
point = ogr.Geometry(ogr.wkbPoint)
point.AddPoint(pointCoord[0],pointCoord[1])

# create a field
for val in vals:
    fieldName = 'test_{}'.format(str(val))
    fieldType = ogr.OFSTFloat32
    idField = ogr.FieldDefn(fieldName, fieldType)
    outLayer.CreateField(idField)

# Create the feature and set values
featureDefn = outLayer.GetLayerDefn()
outFeature = ogr.Feature(featureDefn)
outFeature.SetGeometry(point)

for val in vals:
    fieldName = 'test_{}'.format(str(val))
    outFeature.SetField(fieldName, val)
outLayer.CreateFeature(outFeature)
outFeature = None
```

Produces the following Geojson file:

```
{
"type": "FeatureCollection",
"name": "test.json",
"features": [
{ "type": "Feature", "properties": { "test_nan": [ NaN ], "test_inf": [ Infinity ], "test_-inf": [ -Infinity ] }, "geometry": { "type": "Point", "coordinates": [ -124.4577, 48.0135, 0.0 ] } }
]
}

```

Which cannot be read again by ogr:
```
ogrinfo -al -ro test.json 
ERROR 1: JSON parsing error: unexpected character (at offset 166)
ERROR 4: Failed to read GeoJSON data
FAILURE:
Unable to open datasource `test.json' with the following drivers.
```

## Operating system

Ubuntu 18.04 64 bit

## GDAL version and provenance

Gdal 2.2.3 version from ubuntugis-unstable PPA

**Comment by jratike80** [comment]
Adding as link for readers like me who wonder why to allow to write NaN and +/- Infinity by using a layer creation option WRITE_NON_FINITE_VALUES=YES if the result is invalid JSON:
https://stackoverflow.com/questions/1423081/json-left-out-infinity-and-nan-json-status-in-ecmascript

The answer, I guess, is that otherwise GeoJSON in some situations would be a lossy data transfer format because it could not fully represent IEEE754 floating point numbers and one must select either to be compliant or to lose some information.

**Comment by rbuffat** [comment]
@rouault I'm impressed with how fast this was implemented, thanks!
