### ISSUE TITLE
GEOSMakeValidWithParams_r undefined symbol in libgdal.so.30

### ISSUE THREAD

**Issue by Cruzker** [OSGeo/gdal#11116]
### What is the bug?

I am getting a shared library error where apparently the library that is installed/gets compiled does not have the symbol GEOSMakeValidWithParams_r. I tried to search through github to see what version of gdal has this function but I could not find it.

### Steps to reproduce the issue

Use code that assumes this function exits and try to link to libgdal.so.30

### Versions and provenance

Ubuntu 22.04

**Comment by rouault** [comment]
Highly unlikely to be a GDAL upstream issue. You are most certainly mixing GEOS versions in your setup.

**Comment by Cruzker** [comment]
How would I track this down? Are we saying there is a GEOS shared library which isnt the correct version?

**Comment by rouault** [comment]
> How would I track this down?

check that you aren't mixing up different APT repositories, etc. There are probably resources out there in the Internet to help you guide through the specifics of your situation
