### ISSUE TITLE
Do not call `warnings.simplefilter` in library code 

### ISSUE THREAD

**Issue by vnmabus** [OSGeo/gdal#11140]
### What is the bug?

In https://github.com/OSGeo/gdal/blob/master/swig/python/osgeo/__init__.py `warnings.simplefilter` is called to always display deprecation warnings. This changes the global warnings configuration, which is bad to do inside a library.

In our case, this happened when using an older Python version and the newest GDAL that still supported it (which triggers a message saying that newer GDAL versions will drop support for that Python version). Due to the `warnings.simplefilter` change, a lot of deprecation warnings from other modules flooded our logs.

We are going to patch our GDAL version suppressing calls to `warnings.simplefilter`. However, as this is still happening in master I wanted to open an issue for it to be fixed in the future.

### Steps to reproduce the issue

Just execute the newest GDAL which still has support for an older Python version.

### Versions and provenance

GDAL 3.2.3 and Python 2.7 (but it will happen again when you drop support for another Python version).

**Comment by rouault** [comment]
@idanmiara Any though about that? I see you added that in 339a600e569

**Comment by idanmiara** [comment]
I frankly don't remember why I set `simplefilter('always', DeprecationWarning)` there, but as @vnmabus suggests it also makes sense to me to remove both calls to `simplefilter`.

**Comment by rouault** [comment]
thanks, will be fixed per https://github.com/OSGeo/gdal/pull/11141
