### ISSUE TITLE
POLYGON EMPTY with a single ring having no coordinates

### ISSUE THREAD

**Issue by edzer** [OSGeo/gdal#11161]
### What is the bug?

If OGR is asked to read

{"type":"Polygon","coordinates":[[]]}

rather than

{"type":"Polygon","coordinates":[]}

it returns a polygon with a single ring having zero coordinates, which has a different WKB encoding from the polygon with zero rings (POLYGON EMPTY). Nevertheless it (and also GEOS) treats it as a POLYGON EMPTY, but the WKB representations are different:

> st_as_binary(st_geometry(x))
[[1]]
 [1] 01 03 00 00 00 01 00 00 00 00 00 00 00

attr(,"class")
[1] "WKB"
> st_as_binary(st_as_sfc("POLYGON EMPTY"))
[[1]]
[1] 01 03 00 00 00 00 00 00 00

I would expect (and suggest) GDAL/OGR to return a single, unique WKB for all POLYGON EMPTY (and other *** EMPTY), rather than leaving this to downstream software.

### Steps to reproduce the issue

This came up here: https://github.com/r-spatial/sf/issues/2463

### Versions and provenance

Linux 22.04, GEOS 3.13.0, GDAL 3.9.2, PROJ 9.5.0, but reproduced with GEOS 3.13.0, GDAL 3.10.0beta1, PROJ 9.4.1

**Comment by rouault** [comment]
We could discuss at length about what is the correct thing to do in that situation, but I don't see anything particularly wrong in the current GDAL behavior. This is mostly a matter of taste. If we'd change the behavior to what you suggest, then someone importing a WKB with a polygon with an empty ring wouldn't get it back and would claim that GDAL doesn't round trip it correctly.

**Comment by jratike80** [comment]
> That said, I'm not even sure if empty rings in Simple Features are allowed.

Just made a test with PostGIS. It denies to read `select st_isempty(st_geomfromtext('LINESTRING ()'))`.
The GeoJSON specification says

> GeoJSON processors MAY interpret Geometry objects with empty "coordinates" arrays as null objects.

**Comment by rouault** [comment]
> It denies to read `select st_isempty(st_geomfromtext('LINESTRING ()'))`.

That's technically not a ring. I was here specifically writing about an empty ring inside a polygon.

**Comment by jratike80** [comment]
I used linestring as an example. In the simple features standard all definitions are like
```
<Point Text> := EMPTY | ( <Point> )
<Point> := <x> <y>
```
So either there is EMPTY or there are real coordinates. At least I read that `<Point> := <x> <y>` means that x and y must exist.

**Comment by edzer** [comment]
AFAIR, the SFA spec is pretty clear about WKB of all `*** EMPTY`, except for `POINT EMPTY` which it failed to specify. I think respecting that is a more useful goal than the ability to roundtrip GeoJSON's with arbitrarily deeply nested empty lists, and not against the GeoJSON spec.

**Comment by edzer** [comment]
Having said that, I must admit that in https://github.com/r-spatial/sf/issues/2441 we are benefiting from OGR and GEOS not tripping on rings with too few nodes, when effectively `POLYGON((0 -90,0 -90))` is used to indicate a `POLYGON FULL` (the entire Earth).

**Comment by jratike80** [comment]
Does the GeoJSON spec define *** EMPTY at all when it says "GeoJSON processors MAY interpret Geometry objects with
      empty "coordinates" arrays as null objects.", or were the authors just not devoted to the difference between null and different kind of empty geometries?

**Comment by jratike80** [comment]
So what did you do? The worms may still escape one day and it would be nice if we are already weaponed.

**Comment by edzer** [comment]
> So what did you do? 

https://github.com/r-spatial/sf/commit/90980f72150b2e211c60227ee6e749c17c58266a : in addition to geometries with zero elements, we now consider geometries that have one or more elements but whose first element has size zero also as empty geometry (with the exception that empty points found by having NA values). This however still fails for GeoJSON
```
{"type":"MultiPolygon","coordinates":[[[]]]}
```
for which I'll have to go one level deeper...

**Comment by rouault** [comment]
> for which I'll have to go one level deeper...

if you work on OGRGeometry you can use OGR_G_IsEmpty(). It will consider a polygon with an empty ring as empty
```python
>>> from osgeo import ogr
>>> g = ogr.Geometry(ogr.wkbPolygon)
>>> g.AddGeometry(ogr.Geometry(ogr.wkbLinearRing))
>>> g.IsEmpty()
True
```

**Comment by rouault** [comment]
Closing as won't fix
