### ISSUE TITLE
generate_vcxproj.bat unable to execute.

### ISSUE THREAD

**Issue by jkae** [OSGeo/gdal#1116]
Specific issue: `)) was unexpected at this time.` error causes batch exit.

Reference [this commit](https://github.com/OSGeo/gdal/commit/5bd506d5691e5c68da5bb7ab451fa0e99b5e91cf#diff-41cede2baa5d519dbefb067ff7059ba8L64) removing support for previous Visual Studio versions.

[This line](https://github.com/OSGeo/gdal/blob/02b80647937d999cd5830bb898eb5fd2df74cc15/gdal/generate_vcxproj.bat#L67) should be edited to correctly remove parentheses.

**Comment by joyerf** [comment]
generate_vcxproj.bat line:67
delete ))
if "%_vcver_%"=="15.0" (
	set _clver_=1910
	set _vstoolset_=v141
) else if "%_vcver_%"=="14.0" (
	set _clver_=1900
	set _vstoolset_=v140
) else ( if "%_vcver_%"=="12.0" (
	set _clver_=1800
	set _vstoolset_=v120
) else (
    echo Wrong value for parameter 1. See usage:
	goto :usage
))
