### ISSUE TITLE
can't build mrsid

### ISSUE THREAD

**Issue by donharter** [OSGeo/gdal#11195]
### What is the bug?

driver mrsid won't build.  This happens when it reaches this point:
"Linking CXX shared library libgdal.so"
It fails because it tries to link one of the mrsid paths as an object file.  Everything else on the command line is an object file to link into libgdal.so
/usr/bin/cmake -E cmake_link_script CMakeFiles/GDAL.dir/link.txt --verbose=1
/bin/c++ -fPIC  -fvisibility=hidden  -Wl,--no-undefined -shared -Wl,-soname,libgdal.so.36 -o libgdal.so.36.3.11.0 @CMakeFiles/GDAL.dir/objects1  -Wl,-rpath,/usr/lib/x86_64-linux-gnu/hdf5/serial:  ...............

I get this message:
"/bin/ld: cannot find /home/drh/src/MrSID_DSDK-9.5.5.5244-rhel9.x86-64.gcc1131/Raster_DSDK/lib: file format not recognized
collect2: error: ld returned 1 exit status
gmake[2]: *** [CMakeFiles/GDAL.dir/build.make:2834: libgdal.so.36.3.11.0] Error 1
gmake[2]: Leaving directory '/home/drh/src/gdal_git/gdal/build'
gmake[1]: *** [CMakeFiles/Makefile2:4803: CMakeFiles/GDAL.dir/all] Error 2
gmake[1]: Leaving directory '/home/drh/src/gdal_git/gdal/build'
gmake: *** [Makefile:146: all] Error 2"

The above can be found it is a directory and not an object file.

### Steps to reproduce the issue

just try to buidl it with cmake --build . command

### Versions and provenance

linux mint bookworm

**Comment by donharter** [comment]
So it seems it is a problem with the cmake build configuration.

**Comment by donharter** [comment]
gcc --version
gcc (Debian 12.2.0-14) 12.2.0

**Comment by rouault** [comment]
What is your CMake command line ? For reference a working configuration at https://github.com/OSGeo/gdal/blob/master/.github/workflows/ubuntu_20.04/Dockerfile.ci#L145 and https://github.com/OSGeo/gdal/blob/master/.github/workflows/ubuntu_20.04/build.sh#L15

**Comment by donharter** [comment]
cmake --build .
[CMakeCache.txt](https://github.com/user-attachments/files/17604892/CMakeCache.txt)

**Comment by rouault** [comment]
I mean how you *configured* with cmake , before trying to build it

But looking at your CMakeCache.txt, I see what is wrong:
MRSID_LIBRARY:FILEPATH=/home/drh/src/MrSID_DSDK-9.5.5.5244-rhel9.x86-64.gcc1131/Raster_DSDK/lib

You should point at the libltidsdk.so file instead
so
MRSID_LIBRARY:FILEPATH=/home/drh/src/MrSID_DSDK-9.5.5.5244-rhel9.x86-64.gcc1131/Raster_DSDK/lib/libltidsdk.so

**Comment by donharter** [comment]
I was running "cmake .. " and "ccmake ." without a script.
It says "FILEPATH" and not "DIR".  I made that change.  That partially fixed it.  But then it complained about the other library in that directory.  So I put 2 paths to each library in the variable separated by a space.  Then I got this error:
make[2]: *** No rule to make target '/home/drh/src/MrSID_DSDK-9.5.5.5244-rhel9.x86-64.gcc1131/Raster_DSDK/lib/libltidsdk.so /home/drh/src/MrSID_DSDK-9.5.5.5244-rhel9.x86-64.gcc1131/Raster_DSDK/lib/libtbb.so', needed by 'libgdal.so.36.3.11.0'.  Stop.
gmake[2]: Leaving directory '/home/drh/src/gdal_git/gdal/build'
gmake[1]: *** [CMakeFiles/Makefile2:4803: CMakeFiles/GDAL.dir/all] Error 2"
[CMakeCache.txt](https://github.com/user-attachments/files/17605042/CMakeCache.txt)

**Comment by donharter** [comment]
I was using this procedure to build it.  https://gdal.org/en/latest/development/building_from_source.html#selection-of-drivers

**Comment by rouault** [comment]
no you probably just have to do ``export LD_LIBRARY_PATH=/home/drh/src/MrSID_DSDK-9.5.5.5244-rhel9.x86-64.gcc1131/Raster_DSDK/lib``  . My recommandation: do like in the scripts I showed you and install in /usr/local so that libraries get found.

I'm closing this, since at this point this is just "standard" software building and you've pretty much all needed details.

**Comment by donharter** [comment]
With just one library listed.  I get this:
[ 90%] Linking CXX executable gdaladdo
cd /home/drh/src/gdal_git/gdal/build/apps && /usr/bin/cmake -E cmake_link_script CMakeFiles/gdaladdo.dir/link.txt --verbose=1
/bin/c++  -fvisibility=hidden CMakeFiles/gdaladdo.dir/gdaladdo.cpp.o CMakeFiles/utils_common.dir/gdalargumentparser.cpp.o -o gdaladdo  -Wl,-rpath,/home/drh/src/gdal_git/gdal/build:/usr/lib/x86_64-linux-gnu/hdf5/serial: ../libgdal.so.36.3.11.0 -Wl,-rpath-link,/usr/lib/x86_64-linux-gnu/hdf5/serial 
/bin/ld: warning: libtbb.so.2, needed by /home/drh/src/MrSID_DSDK-9.5.5.5244-rhel9.x86-64.gcc1131/Raster_DSDK/lib/libltidsdk.so, not found (try using -rpath or -rpath-link)
/bin/ld: /home/drh/src/MrSID_DSDK-9.5.5.5244-rhel9.x86-64.gcc1131/Raster_DSDK/lib/libltidsdk.so: undefined reference to `tbb::pipeline::~pipeline()'
/bin/ld: /home/drh/src/MrSID_DSDK-9.5.5.5244-rhel9.x86-64.gcc1131/Raster_DSDK/lib/libltidsdk.so: undefined reference to `tbb::task_scheduler_init::default_num_threads()'
/bin/ld: /home/drh/src/MrSID_DSDK-9.5.5.5244-rhel9.x86-64.gcc1131/Raster_DSDK/lib/libltidsdk.so: undefined reference to `tbb::filter::~filter()'
/bin/ld: /home/drh/src/MrSID_DSDK-9.5.5.5244-rhel9.x86-64.gcc1131/Raster_DSDK/lib/libltidsdk.so: undefined reference to `tbb::pipeline::add_filter(tbb::filter&)'
/bin/ld: /home/drh/src/MrSID_DSDK-9.5.5.5244-rhel9.x86-64.gcc1131/Raster_DSDK/lib/libltidsdk.so: undefined reference to `tbb::pipeline::pipeline()'
/bin/ld: /home/drh/src/MrSID_DSDK-9.5.5.5244-rhel9.x86-64.gcc1131/Raster_DSDK/lib/libltidsdk.so: undefined reference to `typeinfo for tbb::filter'
/bin/ld: /home/drh/src/MrSID_DSDK-9.5.5.5244-rhel9.x86-64.gcc1131/Raster_DSDK/lib/libltidsdk.so: undefined reference to `tbb::pipeline::run(unsigned long)'
collect2: error: ld returned 1 exit status
gmake[2]: *** [apps/CMakeFiles/gdaladdo.dir/build.make:100: apps/gdaladdo] Error 1

**Comment by donharter** [comment]
Perhaps I need a -L link flag to the mrsid library directory.

**Comment by rouault** [comment]
> Perhaps I need a -L link flag to the mrsid library directory.

no, this is indirect linking. GDAL can't link directly to this libtbb.so . See my above LD_LIBRARY_PATH hint, or add this path in your ld.so.conf  or move the SDK to a directory like /usr/local

**Comment by donharter** [comment]
LD_LIBRARY_PATH  did not work.  It seemed to get reset to null.  I did get a 100% which showed MrSID as a driver.  I will attach the config that worked. 
[CMakeCache.txt](https://github.com/user-attachments/files/17605102/CMakeCache.txt)
