### ISSUE TITLE
GPKG driver creates empty-named column and throws error

### ISSUE THREAD

**Issue by JorgeMartinezG** [OSGeo/gdal#11206]
### What is the bug?

Greetings. First of all I want to give thanks for supporting this tool.

I am currently facing an error when creating a geopackage file from scratch. For example, in the following code I create a FeatureDefn _feature_defn_ and add the id field as integer. Then, I create a feature using the previously created _feature_defn_ and add sample values for field and geometry.

```python
# Create feature
feature_defn = ogr.FeatureDefn()
field = ogr.FieldDefn("id", ogr.OFTInteger)
feature_defn.AddFieldDefn(field)

wkt = "POINT (1120351.5712494177 741921.4223245403)"
geometry = ogr.CreateGeometryFromWkt(wkt)

point_feature = ogr.Feature(feature_defn)
point_feature.SetField("id", 2)
point_feature.SetGeometry(geometry)
```
The problem appears when saving the created feature into a geopackage file.

```python
driver = ogr.GetDriverByName("GPKG")
with driver.CreateDataSource("output.gpkg") as ds:
    layer = ds.CreateLayer("points", geom_type=ogr.wkbPoint)
    layer.CreateField(field)

    layer.CreateFeature(point_feature)
```

The error displays a new column with no name and unknown value.

```
ERROR 1: failed to prepare SQL: INSERT INTO "points" ( "", "id") VALUES (?, ?) - table points has no column named 
```

I was able to fix this issue by previously creating the layer, adding the required fields and then read the Feature definition from the layer. Like the below code

```python
driver = ogr.GetDriverByName("GPKG")
with driver.CreateDataSource("output.gpkg") as ds:
    layer = ds.CreateLayer("points", geom_type=ogr.wkbPoint)
    layer.CreateField(field)
    
    feature_defn_from_layer = layer.GetLayerDefn()

    point_feature = ogr.Feature(feature_defn_from_layer)
    point_feature.SetField("id", 1)
    point_feature.SetGeometry(geometry)
```

I can confirm that this issue appears using the GPKG driver. Switching to Flatgeobuf or ESRI Shapefile the error does not appear.

### Steps to reproduce the issue

Using GDAL binaries installed from Homebrew.

1. Create python virtualenv

```sh
python3.12 -m env gdal/
source gdal/bin/activate
```

2. Install the library matching the binary version
```sh
pip install GDAL==`gdal-config --version`
```

3. Run the sample codes displayed within the **bug description** section of this issue.

### Versions and provenance

MAC OS Ventura 13.3
GDAL==3.9.3
Python 3.12.7

**Comment by rouault** [comment]
> ```python
> feature_defn.AddFieldDefn(field)
> ```

you can't do that on a feature_defn attached to a layer. You should use CreateField() as document in https://gdal.org/en/latest/api/python/vector_api.html#osgeo.ogr.FeatureDefn.AddFieldDefn: "To add a new field definition to a layer definition, do not use this function directly, but use [Layer.CreateField()](https://gdal.org/en/latest/api/python/vector_api.html#osgeo.ogr.Layer.CreateField) instead."
