### ISSUE TITLE
GDAL import of _gdal_array broken in Python 2.7

### ISSUE THREAD

**Issue by scollis** [OSGeo/gdal#1120]
## Expected behavior and actual behavior.

Our toolkit uses GDAL for Geotiff generation. Our CI caught an issue testing against Python 2.7 on Travis CI. Note: it works with all Py3.x fine

https://travis-ci.org/ARM-DOE/pyart/jobs/460466036

## Steps to reproduce the problem.
```
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
pyart/io/output_to_geotiff.py:154: in write_grid_geotiff
    dst_ds.GetRasterBand(1).WriteArray(data[::-1, :])
../../../miniconda3/envs/testenv/lib/python2.7/site-packages/osgeo/gdal.py:1101: in WriteArray
    import gdalnumeric
../../../miniconda3/envs/testenv/lib/python2.7/site-packages/osgeo/gdalnumeric.py:1: in <module>
    from gdal_array import *
../../../miniconda3/envs/testenv/lib/python2.7/site-packages/osgeo/gdal_array.py:25: in <module>
    _gdal_array = swig_import_helper()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_gdal_array', [dirname(__file__)])
        except ImportError:
>           import _gdal_array
E           ImportError: No module named _gdal_array
```

here is the miniconda env file:
https://github.com/ARM-DOE/pyart/blob/master/continuous_integration/environment-2.7.yml

GDAL is not referenced specifically 

test
https://github.com/ARM-DOE/pyart/blob/master/pyart/io/tests/test_output_to_geotiff.py

code
https://github.com/ARM-DOE/pyart/blob/master/pyart/io/output_to_geotiff.py

*I need to track down where we are picking up gdal from*

## Operating system

Travis Linux
## GDAL version and provenance
*Tracking down*

**This issue is more to see if you are dropping 2.7 support... if this is the case we will no longer test our geotiff export for 2.7** we are dropping 2.7 soon anyway

**Comment by scollis** [comment]
Ping @zssherman

**Comment by rouault** [comment]
It is likely that you have built the GDAL Python bindings without installing numpy-devel first.

**Comment by scollis** [comment]
Thanks @rouault 
Is this something that has changed in the last week? Our tests were working before that.

**Comment by rouault** [comment]
No, there hasn't been changes touching that area recently. Do you build the GDAL Python bindings yourself or do you install them from other source (if so, then that should be seen with the source in question)

**Comment by scollis** [comment]
Other source (conda-forge) I am following that path now. This can be closed as if nothing has been touched recently it should work. I will re-open if needed.
