### ISSUE TITLE
How to compile Android library files on Ubuntu

### ISSUE THREAD

**Issue by lanzhu1993** [OSGeo/gdal#11218]
### Feature description

I built it on Ubuntu 24.10 based on the code of the master branch and referenced start.sh. When executed
### Build GDAL
```
mkdir build_android_cmake
cd build_android_cmake
```

An error message appears here, indicating
CMake Error: The source directory "/home/josh/gdalSpace/gdal/.github/workflows/android_cmake" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GU，

Help, I'm not very familiar with Cmake, thank you

**Comment by rouault** [comment]
cf https://gdal.org/en/latest/download.html#android
