### ISSUE TITLE
Following the instructions in the document, it is still not possible to generate the AAR file,Help!

### ISSUE THREAD

**Issue by lanzhu1993** [OSGeo/gdal#11223]
### Feature description

Following the instructions in the document, it is still not possible to generate the AAR file,  [Issues11218](https://github.com/OSGeo/gdal/issues/11218) but there is one more issue, which is executing commands through vcpkg
`./vcpkg install gdal:arm64-android`

Successfully compiled, generated many files on Windows, but did not synthesize AAR. How to handle the final generation of AAR files? The generated directory files are as follows:

PS F:\gdalSpace\vcpkg\installed\arm64-android> ls

 `   目录: F:\gdalSpace\vcpkg\installed\arm64-android`

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         2024/11/8     13:00                debug
d-----         2024/11/8     13:00                etc
d-----         2024/11/8     15:22                include
d-----         2024/11/8     15:22                lib
d-----         2024/11/8     15:22                share
d-----         2024/11/8     15:04                tools

PS F:\gdalSpace\vcpkg\installed\arm64-android> cd lib
PS F:\gdalSpace\vcpkg\installed\arm64-android\lib> ls

`    目录: F:\gdalSpace\vcpkg\installed\arm64-android\lib`

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         2024/11/8     15:22                gdalplugins
d-----         2024/11/8     15:22                pkgconfig
-a----         2024/11/8     13:29           7600 libcharset.a
-a----         2024/11/8     15:01          30610 libcpufeatures-webp.a
-a----         2024/11/8     13:00       39663318 libcrypto.a
-a----         2024/11/8     13:05       11527842 libcurl.a
-a----         2024/11/8     14:20         605116 libecpg.a
-a----         2024/11/8     14:20          85788 libecpg_compat.a
-a----         2024/11/8     13:06        1043102 libexpat.a
-a----         2024/11/8     13:39         480152 libfreexl.a
-a----         2024/11/8     15:21      468248266 libgdal.a
-a----         2024/11/8     13:44      145432116 libgeos.a
-a----         2024/11/8     13:44        4999744 libgeos_c.a
-a----         2024/11/8     13:56         939752 libgeotiff.a
-a----         2024/11/8     13:45         288842 libgif.a
-a----         2024/11/8     13:29        2204550 libiconv.a
-a----         2024/11/8     13:50        6652826 libjpeg.a
-a----         2024/11/8     13:46         502442 libjson-c.a
-a----         2024/11/8     13:58        2805650 libkmlbase.a
-a----         2024/11/8     13:58        3589022 libkmlconvenience.a
-a----         2024/11/8     13:58       17516012 libkmldom.a
-a----         2024/11/8     13:58        8147938 libkmlengine.a
-a----         2024/11/8     13:58        1021806 libkmlregionator.a
-a----         2024/11/8     13:58        2656648 libkmlxsd.a
-a----         2024/11/8     13:47        9025678 libLerc.a
-a----         2024/11/8     13:59        1686794 liblz4.a
-a----         2024/11/8     13:51        1949336 liblzma.a
-a----         2024/11/8     13:29         336642 libminizip.a
-a----         2024/11/8     15:02        2612912 libopenjp2.a
-a----         2024/11/8     15:03        7568666 libpcre2-16.a
-a----         2024/11/8     15:04        7202250 libpcre2-32.a
-a----         2024/11/8     15:03        8323386 libpcre2-8.a
-a----         2024/11/8     15:03          28246 libpcre2-posix.a
-a----         2024/11/8     14:20        1038246 libpgcommon.a
-a----         2024/11/8     14:20         409526 libpgport.a
-a----         2024/11/8     14:20         418228 libpgtypes.a
-a----         2024/11/8     13:59        1931648 libpng.a
-a----         2024/11/8     13:59        1931648 libpng16.a
-a----         2024/11/8     14:20        1508268 libpq.a
-a----         2024/11/8     13:56       92532540 libproj.a
-a----         2024/11/8     15:04        4955412 libqhullcpp.a
-a----         2024/11/8     15:04        2339322 libqhullstatic.a
-a----         2024/11/8     15:04        2697316 libqhullstatic_r.a
-a----         2024/11/8     15:01         182532 libsharpyuv.a
-a----         2024/11/8     14:59       41832848 libspatialite.a
-a----         2024/11/8     13:48       12496856 libsqlite3.a
-a----         2024/11/8     13:00       10753940 libssl.a
-a----         2024/11/8     13:53        3532052 libtiff.a
-a----         2024/11/8     13:50        8142060 libturbojpeg.a
-a----         2024/11/8     13:57         761326 liburiparser.a
-a----         2024/11/8     15:01        5263562 libwebp.a
-a----         2024/11/8     15:01        2940360 libwebpdecoder.a
-a----         2024/11/8     15:01         129882 libwebpdemux.a
-a----         2024/11/8     15:01         390568 libwebpmux.a
-a----         2024/11/8     14:21       11608480 libxml2.a
-a----         2024/11/8     13:00         561556 libz.a
-a----         2024/11/8     15:05        9894320 libzstd.a
-a----         2024/11/8     14:59       41883934 mod_spatialite.a`

**Comment by rouault** [comment]
This is out of the scope of the GDAL project. Consult generic Android specific documentation
