### ISSUE TITLE
Add dstalpha support to gdal_translate

### ISSUE THREAD

**Issue by vilhelmen** [OSGeo/gdal#11231]
### Feature description

Currently (3.10.0), warp is able to create a new alpha band while translate cannot. If an alpha band exists, translate will respect it and update it accordingly but if one does not exist there is no clean way to create one, **especially** for ungeoreferenced imagery.

A VRT with addalpha can't be used as it rejects ungeoreferenced imagery, which means the only solutions seem to be adding a full alpha band before window cutting, which is going to be a wasteful operation creating full temp copies of my data, or using rasterize after the srcwin translate to burn an alpha channel into a copied band, which is vulnerable to me having to do coordinate math correctly.

To be fair, I don't really understand how translate's mask flag works, but I was unable to produce the desired results experimenting with it. I feel like this may be a simple add since warp has the existing functionality and translate already has alpha processing logic, but I could be wrong. Recalling #8002, there may need to be some extra creation option settings.

**Comment by rouault** [comment]
==> ``gdal_translate rgb.tif rgba.tif -b 1 -b 2 -b 3 -b mask -co ALPHA=YES``

**Comment by vilhelmen** [comment]
Embarrassing! That does it and it even produces 255 on an 11-bit image.

**Comment by rouault** [comment]
I see this is even one of the examples of https://gdal.org/en/latest/programs/gdal_translate.html#examples . I believe we can close this ticket, right?

**Comment by vilhelmen** [comment]
For sure. Thank you for the time.

**Comment by vilhelmen** [comment]
As a note, doing this in python emits a warning when the image bands aren't 8-bit, something I missed during testing on squashed data:
`Warning 1: translated.tif: Unable to export GeoTIFF file with different datatypes per different bands. All bands should have the same types in TIFF.`

Layer is still 0/255, which is great, and the datatype matches the rest of the raster, so things seem fine.

**Comment by vilhelmen** [comment]
@rouault Actually, I'm experiencing some strange issue with the colorinterp on the new alpha band (at least) via python. It appears to be related to extra bands in some way. I've managed to generate a test on my Mac using 3.10.0.

Create two images, one RGB, one BGRN (but the N is never labeled right and reads as 0/undefined):
```shell
gdal_create -ot Uint16 -of nitf -bands 3 -burn 99 -outsize 200 200 working.ntf
gdal_edit -colorinterp_1 red -colorinterp_2 green  -colorinterp_3 blue  working.ntf

gdal_create -ot Uint16 -of nitf -bands 4 -burn 99  -outsize 200 200 broken.ntf

gdal_edit -colorinterp_1 blue -colorinterp_2 green  -colorinterp_3 red  -colorinterp_4 undefined broken.ntf
```
Side note, band 4 is being marked Gray and not Undefined? I'm also unable to set it via python as well. Is this a NTF issue? My imagery is marked Undefined.

Running them through this code will have the first image get the colorinterp set to 6 but the second will be set to 0.
```python3
from osgeo import gdal
gdal.UseExceptions()
src_ds = gdal.Open('TESTFILE', gdal.GA_ReadOnly)
options = dict(
    format='GTiff',
    srcWin=[0,0,100,100],
    nogcp=True,
    stats=True,
    resampleAlg='cubic',
    overviewLevel='NONE',
    bandList=[x for x in range(1, src_ds.RasterCount + 1)] + ['mask'],
    creationOptions=dict(
        ALPHA='YES',
        NBITS='11'
    )
)
work_ds = gdal.Translate('/vsimem/translated.tif', src_ds, options=gdal.TranslateOptions(**options))
work_ds.GetRasterBand(work_ds.RasterCount).GetColorInterpretation()
```

**Comment by rouault** [comment]
> I'm also unable to set it via python as well. Is this a NTF issue? My imagery is marked Undefined.

a "feature" rather. One should understand that while GDAL API offers many possibilities, it is severely constrained by the actual capabilities of the underlying format. NITF doesn't support Alpha. Gray vs Undefined is often used interchangeably by formats with loose typing of the color interpretation.

**Comment by vilhelmen** [comment]
Makes sense. Is it expected behavior that a gray/fourth brand would stop the new alpha from being marked as such? Even including the tif conversion?

**Comment by rouault** [comment]
> Even including the tif conversion?

The behavior of the ALPHA creation option is a bit subtle and historical. Bottom rule is that it only works to mark the 4th band of a 4 band dataset as alpha. You can solve the issue by specifying the ``colorInterpretation=["red","green","blue","undefined","alpha"]`` option (for GTiff)

**Comment by vilhelmen** [comment]
I'm not seeing `colorInterpretation` in the list for `TranslateOptions` and I get an exception when providing it. It also doesn't appear to be in the GTiff driver as a `creationOption` setting. I'm fine setting it post-translate, but I want to make sure I'm not missing something.

Another interesting quirk of alpha creation, I have to sidestep an arcgis issue reading gray/alpha as a very broken RGB by creating a fake RGBA via `bandList=[1,1,1,'mask']` and it sets band 2 as alpha.

**Comment by rouault** [comment]
> I'm not seeing `colorInterpretation` in the list for `TranslateOptions`

ah, that was a short coming. Will be repaired per https://github.com/OSGeo/gdal/pull/11250 . The workaround is to use the generic options to provide it as you would do on gdal_translate command line: ``options="-colorinterp red,green,blue,undefined,alpha"``

> Another interesting quirk of alpha creation, I have to sidestep an arcgis issue reading gray/alpha as a very broken RGB by creating a fake RGBA via bandList=[1,1,1,'mask'] and it sets band 2 as alpha.

not totally sure to understand. Here's my experiment:

$ gdalinfo greyalpha.tif 
Driver: GTiff/GeoTIFF
Files: greyalpha.tif
Size is 162, 150
Image Structure Metadata:
  INTERLEAVE=PIXEL
Corner Coordinates:
Upper Left  (    0.0,    0.0)
Lower Left  (    0.0,  150.0)
Upper Right (  162.0,    0.0)
Lower Right (  162.0,  150.0)
Center      (   81.0,   75.0)
Band 1 Block=162x25 Type=Byte, ColorInterp=Gray
  Mask Flags: PER_DATASET ALPHA 
Band 2 Block=162x25 Type=Byte, ColorInterp=Alpha

$ gdal_translate greyalpha.tif out.tif -b 1 -b 1 -b 1 -b mask

$ gdalinfo out.tif
Driver: GTiff/GeoTIFF
Files: out.tif
Size is 162, 150
Image Structure Metadata:
  INTERLEAVE=PIXEL
Corner Coordinates:
Upper Left  (    0.0,    0.0)
Lower Left  (    0.0,  150.0)
Upper Right (  162.0,    0.0)
Lower Right (  162.0,  150.0)
Center      (   81.0,   75.0)
Band 1 Block=162x12 Type=Byte, ColorInterp=Gray
Band 2 Block=162x12 Type=Byte, ColorInterp=Gray
Band 3 Block=162x12 Type=Byte, ColorInterp=Gray
Band 4 Block=162x12 Type=Byte, ColorInterp=Undefined

$ gdal_translate greyalpha.tif out.tif -b 1 -b 1 -b 1 -b mask -colorinterp gray,gray,gray,alpha

$ gdalinfo out.tif
Driver: GTiff/GeoTIFF
Files: out.tif
Size is 162, 150
Image Structure Metadata:
  INTERLEAVE=PIXEL
Corner Coordinates:
Upper Left  (    0.0,    0.0)
Lower Left  (    0.0,  150.0)
Upper Right (  162.0,    0.0)
Lower Right (  162.0,  150.0)
Center      (   81.0,   75.0)
Band 1 Block=162x12 Type=Byte, ColorInterp=Gray
  Mask Flags: PER_DATASET ALPHA 
Band 2 Block=162x12 Type=Byte, ColorInterp=Gray
  Mask Flags: PER_DATASET ALPHA 
Band 3 Block=162x12 Type=Byte, ColorInterp=Gray
  Mask Flags: PER_DATASET ALPHA 
Band 4 Block=162x12 Type=Byte, ColorInterp=Alpha

**Comment by vilhelmen** [comment]
Thank you for the patch :)

It works in the cli but not in python, so I think something is subtly off (at least for me).

```python
ds = gdal.Open('../17JUL13120016-P1BS-200004020692_01_P001.NTF', gdal.GA_ReadOnly)

for i in range(1, ds.RasterCount+1):
    print(i, gdal.GetColorInterpretationName(ds.GetRasterBand(i).GetColorInterpretation())) 
# 1 Gray

options = dict(
        format='GTiff',
        srcWin=[0,0,500,500],
        stats=True,
        resampleAlg='cubic',
        overviewLevel='NONE',
        bandList=[1,1,1,'mask'],
        creationOptions=dict(
            ALPHA='YES',
            NBITS='11'
        )
    )

work_ds = gdal.Translate('/vsimem/translated.tif', ds, options=gdal.TranslateOptions(**options))
# Warning 1: translated.tif: Unable to export GeoTIFF file with different datatypes per different bands. All bands should have the same types in TIFF.
for i in range(1, work_ds.RasterCount+1):
    print(i, gdal.GetColorInterpretationName(work_ds.GetRasterBand(i).GetColorInterpretation()))
# 1 Gray
# 2 Alpha
# 3 Undefined
# 4 Undefined
```

Tried to do the exact same in the cli and it comes out correct?
```shell
$ gdal_translate -srcwin 0 0 500 500 -b 1 -b 1 -b 1  -b 'mask' -stats -r cubic -ovr NONE -of gtiff -co 'NBITS=11' -co 'ALPHA=YES' 17JUL13120016-P1BS-200004020692_01_P001.NTF gauu.tif
Input file size is 37516, 38840
Warning 1: gauu.tif: Unable to export GeoTIFF file with different datatypes per different bands. All bands should have the same types in TIFF.
0...10...20...30...40...50...60...70...80...90...100 - done.

$ gdalinfo gauu.tif | fgrep Band 
Band 1 Block=500x2 Type=UInt16, ColorInterp=Gray
Band 2 Block=500x2 Type=UInt16, ColorInterp=Gray
Band 3 Block=500x2 Type=UInt16, ColorInterp=Gray
Band 4 Block=500x2 Type=UInt16, ColorInterp=Undefined
```

**Comment by vilhelmen** [comment]
Realized my test ntf wasn't 16-bit. Increasing the bit depth causes the python code to label the bands GAUU, so it may be related to that.
