### ISSUE TITLE
I am not able to make static library for iOS

### ISSUE THREAD

**Issue by santu1990** [OSGeo/gdal#11245]
### What is the bug?

Hi,
I am trying to build using the ios-make tool, but I am not able to generate a static library for it.

### Steps to reproduce the issue

- Build for iOS target

### Versions and provenance

Latest

**Comment by santu1990** [comment]
Can you share working sample for gdal, shared linked doesn't work

**Comment by rouault** [comment]
Static linking a full stack of C++ software isn't directly a GDAL specific issue. Closing
