### ISSUE TITLE
ogr2ogr does not work with ElasticSearch6

### ISSUE THREAD

**Issue by realslimjd** [OSGeo/gdal#1125]
### Expected
Insert a shapefile into ElasticSearch 6 using ogr2ogr.

### Actual
Unable to insert shapefile due to the ogr2ogr using the wrong `Content-Type` header.
```
{"error":"Content-Type header [application/x-javascript; charset=UTF-8] is not supported","status":406}
```

### Suggested Fix
[ElasticSearch v6+ requires](https://www.elastic.co/blog/strict-content-type-checking-for-elasticsearch-rest-requests) the `Content-Type` header to be `application/json` for any requests using JSON.

## Steps to reproduce the problem.

* Install ElasticSearch 6+
* `ogr2ogr -progress --config ES_META map.txt -f "ElasticSearch" http://localhost:9200 example.shp`

### Example files
[map.txt](https://github.com/OSGeo/gdal/files/2630174/map.txt)
Unzip for example.shp: [example.shp.zip](https://github.com/OSGeo/gdal/files/2630179/example.shp.zip)

## Operating system

macOS 10.14.1

## GDAL version and provenance

GDAL 2.3.1 from pip

**Comment by nickpeihl** [comment]
Looks like this was resolved in GDAL 2.4.0.
