### ISSUE TITLE
3.10.0 crash while open tiff file on windows10

### ISSUE THREAD

**Issue by sendreams** [OSGeo/gdal#11261]
### What is the bug?

I tried compiling the latest version 3.10.0 on Windows 10 (follow the [document](https://gdal.org/development/building_from_source.html)). After the compilation was completed, there were very few files generated. When I called it using Java and tried to open a TIFF file, it crashed immediately.

However, when I use the files downloaded from https://www.gisinternals.com/release.php, everything works fine. The issue is that the latest version cannot be downloaded from this website.

```
 驱动器 C 中的卷没有标签。
 卷的序列号是 BE8E-6933

 C:\Apps\dev\gdal\release-x64-3-10-0 的目录

2024/11/13  11:07    <DIR>          .
2024/11/12  14:56    <DIR>          ..
2024/11/13  11:08                 0 file.txt
2024/11/12  14:13        18,960,384 gdal.dll
2024/11/12  14:13         1,606,624 gdal.exp
2024/11/12  14:13         2,622,770 gdal.lib
2024/11/12  14:14           667,648 gdalalljni.dll
2024/11/04  14:47           678,912 jpeg62.dll
2024/11/04  14:46           588,800 libcurl.dll
2024/11/04  14:47           186,880 liblzma.dll
2024/11/04  14:49         3,400,704 proj_9.dll
2024/11/04  14:47         1,116,160 sqlite3.dll
2024/11/04  14:47           467,456 tiff.dll
2024/11/04  14:46            90,624 zlib1.dll

 C:\Apps\dev\gdal\release-x64-3-10-0 的目录

              12 个文件     30,386,962 字节
               2 个目录 345,935,228,928 可用字节
```

### Steps to reproduce the issue

[hs_err_pid15428.log](https://github.com/user-attachments/files/17725611/hs_err_pid15428.log)
the complete crash log.

```
private void buildVrt(String tiffFile) throws IOException {
        String string = Paths.get(tiffFile).getParent().toString();
        String name = FilenameUtils.getBaseName(tiffFile);
        File vrtFile = Paths.get(string, name + ".vrt").toFile();
        if (!vrtFile.exists()) {  // create vrt
            Dataset tiffDataset = gdal.Open(tiffFile);    // crash here
            this.dataset = gdal.GetDriverByName("VRT").CreateCopy(vrtFile.toString(), tiffDataset);
        }
        else {
            this.dataset = gdal.Open(vrtFile.toString());
        }
    }
```

### Versions and provenance

version: 3.10.0

**Comment by jratike80** [comment]
> The issue is that the latest version cannot be downloaded from this website.

Newer version is available from here https://www.gisinternals.com/development.php.

**Comment by sendreams** [comment]
> > The issue is that the latest version cannot be downloaded from this website.
> 
> Newer version is available from here https://www.gisinternals.com/development.php.

hi, thanks, do you know how to build the source in windows? i have tested in centos, after building have so many file.
<img width="230" alt="gdal3 10 0_linux" src="https://github.com/user-attachments/assets/846b2a07-490f-4f65-b2b2-4b317255d99b">

**Comment by jratike80** [comment]
I am a person who knows nothing about building GDAL, despite that is seems to be difficult especially on Windows. However, I think that the whole successful build system used by Gisinternals is in Github https://github.com/gisinternals/buildsystem

**Comment by rouault** [comment]
I suspect something specific to your build, but no idea what

**Comment by rouault** [comment]
Closing. I don't see anything actionable on our side on this
