### ISSUE TITLE
union multi dem file is too slow

### ISSUE THREAD

**Issue by sendreams** [OSGeo/gdal#11262]
### Feature description

In the actual data processing workflow, we wanted to merge multiple DEM TIF files into a single TIF file. After testing, we found that the merging process was very slow. We tried two methods:

Processing all files at once.
Continuously merging files two by two until the final file is generated.
Regardless of the method, the speed was very slow. We also tried using QGIS (which also uses GDAL) with similar results.

In the end, we used ArcGIS Pro to perform the merge. The merging process in ArcGIS Pro was clear and efficient. For the same dataset (30 TIF files, approximately 180 GB), the merging and creation of a pyramid took about 2 hours in total. However, GDAL took over a day and still did not finish.

Here is my code, using version 3.8.5.
```
public class DemUnion {

    static {
        gdal.AllRegister();
        ogr.RegisterAll();
    }

    public void union(List<Path> files, Path resultDemfile) {
        Dataset[] inputDatasets = new Dataset[files.size()];
        for (int i = 0; i < files.size(); i++) {
            inputDatasets[i] = gdal.Open(files.get(i).toString(), gdalconstConstants.GA_ReadOnly);
            if (inputDatasets[i] == null) {
                return; 
            }
        }
        Vector<String> params = buildParams();
        
        ProgressCallback progressCallback = new ProgressCallback() {
            @Override
            public int run(double dfComplete, String pszMessage) {
                if (StringUtils.isNotBlank(pszMessage)){
                    System.out.println(pszMessage);
                }
                System.out.printf("%.2f%n",dfComplete*100);
                return 1;
            }
        };

        Dataset dstDataset = gdal.Warp(resultDemfile.toString(), inputDatasets, new WarpOptions(params));
        if (dstDataset != null) {
            dstDataset.delete();
        }
        for (Dataset srcDataset : inputDatasets) {
            if (srcDataset != null) {
                srcDataset.delete();
            }
        }
    }

    protected Vector<String> buildParams() {
        Vector<String> params = new Vector<>();
        params.add("-of");  // 设置输出格式
        params.add("GTiff");
        params.add("-co");  // 设置压缩模式
        params.add("COMPRESS=LZW");
        params.add("-wo");  // 多线程支持
        params.add("NUM_THREADS=ALL_CPUS");
        params.add("-multi");
        return params;
    }
}
```

**Comment by jratike80** [comment]
Did you test the speed with these two command line utilities:

```
gdalbuildvrt merged.vrt *-tif
gdal_translate [reasonable tiff creation options] merged.vrt output.tif
```

**Comment by sendreams** [comment]
> Did you test the speed with these two command line utilities:
> 
> ```
> gdalbuildvrt merged.vrt *-tif
> gdal_translate [reasonable tiff creation options] merged.vrt output.tif
> ```

<img width="821" alt="gdal_translate" src="https://github.com/user-attachments/assets/0577d975-a331-4505-888e-a53ac18cda15">
finally, i found the version 3.6.4 can working now.
the speed is better now. thanks

```
gdalbuildvrt merged.vrt *.tif
gdal_translate -co COMPRESS=LZW -of GTiff merged.vrt output.tif
```

**Comment by jratike80** [comment]
Writing inefficient code it not a GDAL bug. Nice that you know now that you can do better.

**Comment by rouault** [comment]
you need to add ``-co TILED=YES`` when translating to TIFF to get decent performance
