### ISSUE TITLE
AAIGrid: deal with embedded nul

### ISSUE THREAD

**Issue by mdsumner** [OSGeo/gdal#11272]
### Feature description

AAIGrid .asc files with leading chars can't be read, GDAL could potentially detect this and ignore the leading characters. 

This RAR archive contains two .asc files that are otherwise readable but contain ' \xff\xfen' on the first row: 

https://www.modestr.es/sweb/downloads/database/Topographic%20heterogeneity.rar

### Additional context

Seems like a very very obscure situation, but these files are out there and other than rewriting I can't find an alternative workaround.

**Comment by rouault** [comment]
Unless there's a massive amount of data using that crazy AAIGRID variant, with UTF-16 little-endian encoding, I'm not super enthusiastic to complicate GDAL with that weirdness.
Easy workaround: ``iconv -f UTF16LE -t UTF8 < Topographic\ heterogeneity24.asc | tail -c +4 > out.asc``  (the tail part is to strip-off the leading UTF-8 byte-order marker, translated from the initial UTF16LE byte-order marker)

**Comment by rouault** [comment]
To be clear the issue is not just the leading characters: all characters are 2-bytes UTF-16.

**Comment by mdsumner** [comment]
ah ok, I knew I didn't understand exactly what the problem was

thanks for the workaround
