### ISSUE TITLE
Failure to open converted DXF file in AutoCAD after converting from GeoJSON using GDAL.Native 3.9.1 while ogr2ogr converted file opens fine

### ISSUE THREAD

**Issue by mumumi** [OSGeo/gdal#11299]
### What is the bug?

I'm encountering an issue when trying to convert a GeoJSON file to DXF format. I'm using GDAL.Native version 3.9.1 for the conversion. The conversion process itself appears to be successful as it generates a DXF file without any obvious errors during the conversion stage.

However, when I attempt to open the resulting DXF file in AutoCAD, it fails to load. Oddly enough, when I use ogr2ogr (also in version 3.9.1) to perform the same conversion from GeoJSON to DXF, the generated DXF file can be opened in AutoCAD without any issues.

Here is the example geojson content:
{"type":"FeatureCollection","features":[{"type":"Feature","id":0,"properties":{"SubClasses":"AcDbEntity : AcDbLwPolyline","Layer":"mylayer","EntityHandle":"12E0"},"geometry":{"type":"Polygon","coordinates":[[[1,1],[1,2],[2,2],[2,1],[1,1]]]}}]}

### Steps to reproduce the issue

C# codes:
```
GdalConfiguration.ConfigureOgr();
using var iSrc = Ogr.Open("data.json", (int)Access.GA_ReadOnly);
if (iSrc == null) return;

using var driver = Ogr.GetDriverByName("DXF");
using var oSrc = driver.CreateDataSource("data-dotnet.dxf", null);
for (var idx = 0; idx < iSrc.GetLayerCount(); idx++)
{
    using var iLyr = iSrc.GetLayerByIndex(idx);
    if (iLyr == null) continue;

    var layerName = iLyr.GetName();
    using var oLyr = oSrc.CopyLayer(iLyr, layerName, null);
}
```

ogr2ogr command:
`ogr2ogr -f "DXF" data-ogr2ogr.dxf data.json`

### Versions and provenance

Windows 11
Gdal.Native 3.9.1
Gdal binary 3.9.1

### Additional context

[geojson-dxf.zip](https://github.com/user-attachments/files/17811750/geojson-dxf.zip)

data.json
data-dotnet.dxf
data-ogr2ogr.dxf

**Comment by mumumi** [comment]
@rouault Failure to open converted DXF file in AutoCAD again after converting from GeoJSON using GDAL.Native 3.9.2

**Comment by jratike80** [comment]
GDAL 3.9.x is already old and not maintained. The change in https://github.com/OSGeo/gdal/pull/11304 is applied into GDAL 
 master, that is the development version 3.11.

**Comment by mumumi** [comment]
> GDAL 3.9.x is already old and not maintained. The change in #11304 is applied into GDAL master, that is the development version 3.11.

The latest version of [GDAL.Native](https://www.nuget.org/packages/GDAL.Native/) is 3.9.3.

**Comment by jratike80** [comment]
The GDAL project maintains only one branch of GDAL. The release version is at the moment 3.10 and it gets some bug fixes. New development goes into the development branch that is at the moment 3.11.0dev.  It seems that the fix https://github.com/OSGeo/gdal/pull/11304 is not backported into 3.10 branch so it will be available in GDAL version 3.11 when it will be released. If the newest GDAL.Native version is 3.9.3 it is sure that it does not have newest bug fixes and new features. The GDAL team does not make nuget packages so we cannot help with that.

Ogr2ogr is also using the same GDAL libraries that you are using, so if your own code yields bad result it may be that the code is missing something that is present in ogr2ogr. Can you try GDALVectorTranslate instead https://gdal.org/en/latest/api/gdal_utils.html#_CPPv419GDALVectorTranslatePKc12GDALDatasetHiP12GDALDatasetHPK26GDALVectorTranslateOptionsPi?

Actually what happens is explained in https://github.com/OSGeo/gdal/pull/11304#issuecomment-2487206989

> ogr2ogr by default doesn't set the FID of the new feature from the FID of the source feature, when the target driver has no layer FID creation option. It lets its to OGRUnsetFID == -1.
> Whereas GDALDataset::CopyLayer() always set the FID of the new feature from the source one.

So until you can use a GDAL version that has the fix you should either do the same thing that ogr2ogr does with the FID, or use GDALVectorTranslate.  I apologize if my answer does not help, I am not a programmer myself and certainly cannot tell you how to "let it to OGRUnsetFID == -1".

**Comment by rouault** [comment]
> it seems that the fix #11304 is not backported into 3.10 branch

thanks for noticing. Was an oversight. 3.10 backport queued in https://github.com/OSGeo/gdal/pull/11393

**Comment by mumumi** [comment]
@rouault dxfLayer.CreateFeature(featWithoutLayerField) would throw "invalid index -1" exception

**Comment by rouault** [comment]
> dxfLayer.CreateFeature(featWithoutLayerField) would throw "invalid index -1" exception

@mumumi  you need to provide more context. I don't reproduce with the below:
``` python
from osgeo import ogr
ogr.UseExceptions()
ds = ogr.GetDriverByName("DXF").CreateDataSource("test.dxf")
lyr = ds.CreateLayer("test")
f = ogr.Feature(lyr.GetLayerDefn())
f.SetGeometry(ogr.CreateGeometryFromWkt('POINT (1 2)'))
lyr.CreateFeature(f)
ds = None
```

**Comment by mumumi** [comment]
> > dxfLayer.CreateFeature(featWithoutLayerField) would throw "invalid index -1" exception
> 
> @mumumi you need to provide more context. I don't reproduce with the below:
> 
> ```python
> from osgeo import ogr
> ogr.UseExceptions()
> ds = ogr.GetDriverByName("DXF").CreateDataSource("test.dxf")
> lyr = ds.CreateLayer("test")
> f = ogr.Feature(lyr.GetLayerDefn())
> f.SetGeometry(ogr.CreateGeometryFromWkt('POINT (1 2)'))
> lyr.CreateFeature(f)
> ds = None
> ```

```csharp
GdalConfiguration.ConfigureOgr();
using var iSrc = Ogr.Open("data.json", (int)Access.GA_ReadOnly);
if (iSrc == null) return;

using var driver = Ogr.GetDriverByName("DXF");
using var oSrc = driver.CreateDataSource("data-dotnet.dxf", null);
for (var idx = 0; idx < iSrc.GetLayerCount(); idx++)
{
    using var iLyr = iSrc.GetLayerByIndex(idx);
    if (iLyr == null) continue;

    var layerName = iLyr.GetName();
    using var oLyr = oSrc.CreateLayer(layerName, iLyr.GetSpatialRef(), iLyr.GetGeomType(),
        outputLayerOptions);
    var fid = 80;
    while (iLyr.GetNextFeature() is { } feature)
    {
        feature.SetFID(fid++);
        // error: {"Invalid index : -1"}
        // feature without a field named 'Layer'
        oLyr.CreateFeature(feature);
        feature.Dispose();
    }
}
```

**Comment by mumumi** [comment]
> > ```cs
> > oLyr.CreateFeature(feature);
> > ```
> 
> That is not legal. You can only call CreateFeature() with a Feature that has been created with the layer definition of the oLyr. You can't directly use a feature comping from iLyr. You could use Feature.SetFrom(Feature) to translate the source feature into a target feature

@rouault Thanks. Helps a lot!
