### ISSUE TITLE
SetAttributeFilter / ApplicationException

### ISSUE THREAD

**Issue by dcasalino** [OSGeo/gdal#11295]
### What is the bug?

Dear all,

i'm opening a GeoDB file ad on a layer would like to set a AttributeFilter but i obtain this applicationException

![error](https://github.com/user-attachments/assets/43d90fbc-e3f3-4568-85c3-a44cfabddb6a)

What i'm doing wrong ?

Thanks in advance

### Steps to reproduce the issue

Try to set AttributeFilter

### Versions and provenance

Windows

**Comment by rouault** [comment]
Please attached the zipped FileGeodatabase

**Comment by dcasalino** [comment]
Sorry but I can't attach, but if i look the code, there is this check

https://github.com/OSGeo/gdal/blob/957c178ecba2f5ac04b3c642dec6b03f7ea4cd6a/ogr/ogrsf_frmts/openfilegdb/filegdbtable.cpp#L2568

_returnErrorAndCleanupIf(nColNameCarCount > 1024, VSIFree(pabyIdx));_

Maybe in my geodb the number of the charactes of all column of this layer is > 1024.
It's possibile to by-pass this check ?

**Comment by rouault** [comment]
> It's possibile to by-pass this check ?

if you change the source code yes, otherwise no. This was meant as a sanity check. How come the name of your columns is so long... ?

**Comment by dcasalino** [comment]
The total length of all column of layer in my geodb is 2167 chars. This was not my choose.
If i set filter on field OBJECTID i have no errors.

**Comment by rouault** [comment]
> The total length of all column of layer in my geodb is 2167 chars

the total length of all columns is not much of an issue, here it fails because the expression of *one* column is larger than 1024 characters. Can you just attach the files ending with .gdbindexes ? They are the ones relevant here and they don't contain any information other than the column names.

**Comment by dcasalino** [comment]
Here we go

https://1drv.ms/u/c/968a95dc557962c5/EQ5oyp85mRtDuVXIWi07WdIBTNTJ1_yDwwCnU82Miw2W7A?e=Avp9q4

**Comment by jratike80** [comment]
> Some news ?

You can see that the GDAL developers have been very busy with implementing things which have high value for lots of users
https://github.com/OSGeo/gdal/commits/
Have you already tried to compile GDAL yourself with `returnErrorAndCleanupIf(nColNameCarCount > 10000,`?

**Comment by rouault** [comment]
> Have you already tried to compile GDAL yourself with `returnErrorAndCleanupIf(nColNameCarCount > 10000,`?

That would be a bad idea. Upon investigation, those .gdbindexes files have entries with a corrupted/weird/not_fully_understood structure. Fix/workaround in https://github.com/OSGeo/gdal/pull/11372 to skip them

**Comment by jratike80** [comment]
Is it ArcGIS that writes such geodatabases @dcasalino ?
