### ISSUE TITLE
Unknown argument `-ot` using `gdaltindex` in GDAL 3.10

### ISSUE THREAD

**Issue by 1papaya** [OSGeo/gdal#11300]
### What is the bug?

In the documentation for [`gdaltindex`](https://gdal.org/en/latest/programs/gdaltindex.html#cmdoption-gdaltindex-ot) there appears an option `-ot <datatype>`.

However, running the command for example `gdaltindex -ot Float32 data.gti.fgb data/` results in `ERROR 1: Unknown argument: -ot` and the `-ot` argument is not listed in `gdaltindex --help`

### Steps to reproduce the issue

- Install GDAL 3.10
- Run Command `gdaltindex -ot Float32 data.gti.fgb data/`
- Command will error with `ERROR 1: Unknown argument: -ot`

### Versions and provenance

OS: `Ubuntu 20.04`
GDAL: `GDAL 3.10.0, released 2024/11/01 (debug build)` (built from source)

**Comment by jratike80** [comment]
Fixed already https://github.com/OSGeo/gdal/pull/11268.
