### ISSUE TITLE
Poor performance with VRT background layer when using resampling

### ISSUE THREAD

**Issue by sgillies** [OSGeo/gdal#1135]
## Expected behavior and actual behavior.

I've tried to use a VRT layer to implement background fill for "boundless" reads in Rasterio as Frank suggested at https://trac.osgeo.org/gdal/ticket/3327#comment:5 but find the performance poor when passing any advanced resampling argument to GDALRasterIO. Presumably because the background layer is needlessly resampled (it's a small number of pixels and all the same value). Nearest neighbor sampling would suffice for the background layer. There's a little more background at https://github.com/mapbox/rasterio/issues/1499. 

@rouault would you be willing to revisit the VRT background option you write about in that old ticket, or perhaps add an option to force nearest neighbor sampling on a simple source no matter what resampling we pass to GDALRasterIO? I find the HideNoData implementation baffling and hard to use.

## Operating system

Ubuntu 18.04 64 bit

## GDAL version and provenance

GDAL master

**Comment by rouault** [comment]
You can create a <VRTComplexSource> that has <ScaleOffset>background_value</ScaleOffset> and <ScaleRatio>0</ScaleRatio>. In which case VRTComplexSource::RasterIO() has an optimization to avoid actually reading the underlying file (and doing any resampling)
```
<VRTDataset rasterXSize="20" rasterYSize="20">
  <VRTRasterBand dataType="Byte" band="1">
    <ComplexSource>
      <ScaleRatio>0</ScaleRatio>
      <ScaleOffset>255</ScaleOffset>
      <SourceFilename relativeToVRT="1">dummy.tif</SourceFilename>
      <SourceBand>1</SourceBand>
      <SourceProperties RasterXSize="1" RasterYSize="1" DataType="Byte" BlockXSize="1" BlockYSize="1" />
      <SrcRect xOff="0" yOff="0" xSize="1" ySize="1" />
      <DstRect xOff="0" yOff="0" xSize="20" ySize="20" />
    </ComplexSource>
  </VRTRasterBand>
</VRTDataset>
```

**Comment by sgillies** [comment]
@rouault what a great tip! This seems to work perfectly.
