### ISSUE TITLE
LVBAG driver skips features

### ISSUE THREAD

**Issue by 01000011-01000010** [OSGeo/gdal#11354]
### What is the bug?

I use the LVBAG driver for ogrinfo to get the feature count, and for ogr2ogr to import files into PostgreSQL. It seems to skip features, since the feature count results in 0, even through there are features inside (when compared with xmlstarlet). 

Driver: https://gdal.org/en/latest/drivers/vector/lvbag.html
The entire dataset can be downloaded here: https://service.pdok.nl/lv/bag/atom/downloads/lvbag-extract-nl.zip

### Steps to reproduce the issue

*9999InOnderzoek08112024/9999IOLIG08112024/9999IOLIG08112024-000001.xml*
```
ogrinfo -ro -al -so "9999InOnderzoek08112024/9999IOLIG08112024/9999IOLIG08112024-000001.xml" | grep Feature
Feature Count: 0

xmlstarlet select -t -v "count(//sl:stand)" -n "9999InOnderzoek08112024/9999IOLIG08112024/9999IOLIG08112024-000001.xml"
4173
```

*9999InOnderzoek08112024/9999IONUM08112024/9999IONUM08112024-000001.xml*
```
ogrinfo -ro -al -so "9999InOnderzoek08112024/9999IONUM08112024/9999IONUM08112024-000001.xml" | grep Feature
Feature Count: 0

xmlstarlet select -t -v "count(//sl:stand)" -n "9999InOnderzoek08112024/9999IONUM08112024/9999IONUM08112024-000001.xml"
10000
```

*9999InOnderzoek08112024/9999IOPND08112024/9999IOPND08112024-000001.xml*
```
ogrinfo -ro -al -so "9999InOnderzoek08112024/9999IOPND08112024/9999IOPND08112024-000001.xml" | grep Feature
Feature Count: 0

xmlstarlet select -t -v "count(//sl:stand)" -n "9999InOnderzoek08112024/9999IOPND08112024/9999IOPND08112024-000001.xml"
10000
```

*9999InOnderzoek08112024/9999IOVBO08112024/9999IOVBO08112024-000001.xml*
```
ogrinfo -ro -al -so "9999InOnderzoek08112024/9999IOVBO08112024/9999IOVBO08112024-000001.xml" | grep Feature
Feature Count: 0

xmlstarlet select -t -v "count(//sl:stand)" -n "9999InOnderzoek08112024/9999IOVBO08112024/9999IOVBO08112024-000001.xml"
10000
```

As you can see, there are features inside but ogrinfo results in Feature Count: 0
I've attached the mentioned XML files to this issue. 

### Versions and provenance

`GDAL 3.8.4, released 2024/02/08`
Installed on Ubuntu using `apt install gdal-bin` on Ubuntu 24.04.1 LTS

### Additional context

Mentioned XML files in ZIP-file: [bugreport.zip](https://github.com/user-attachments/files/17903464/bugreport.zip)

**Comment by yorickdewid** [comment]
I'll have a look

**Comment by yorickdewid** [comment]
@01000011-01000010 I'm not sure the "InOnderzoek" was ever supported. I can't remember if is was part of the original BAG dumps or not. I can confirm that the latest GDAL build does *not* list any features in theses files.

How much testing are you willing to do to figure out the differences between the 'active' and 'in onderzoek' dumps?

**Comment by yorickdewid** [comment]
@rouault To clarify, there are files in the BAG export containing historic data. These files are similar to the active data but slightly different by adding some historic markers. I found no easy way to detect historic files from the active ones. One possibility might be to select the dataset based on a parameter passed when opening the layer.
