### ISSUE TITLE
Issue with COG Driver Not Recognized in ghcr.io/osgeo/gdal:ubuntu-full-3.10.0

### ISSUE THREAD

**Issue by Mingliang-Liu** [OSGeo/gdal#11350]
### What is the bug?

Description:
I am using the Docker image ghcr.io/osgeo/gdal:ubuntu-full-3.10.0, and I encountered an issue where the COG (Cloud Optimized GeoTIFF) driver is not recognized when running gdal_translate.

The command I used is:
``
docker run --rm -v $(pwd):/data ghcr.io/osgeo/gdal:ubuntu-full-3.10.0 \
gdal_translate /data/world.tif /data/world_webmerc_cog.tif -of COG -co TILING_SCHEME=GoogleMapsCompatible -co COMPRESS=JPEG
``
Error Message:
``
Output driver `COG` not recognised.
``

### Steps to reproduce the issue

1.Pull the image:
``
docker pull ghcr.io/osgeo/gdal:ubuntu-full-3.10.0
``
2.Run the gdal_translate command with the COG output format.
3.Observe the error: Output driver 'COG' not recognised.

### Versions and provenance

Docker image: ghcr.io/osgeo/gdal:ubuntu-full-3.10.0
Host OS: ubuntu18.04LTS
GDAL version: 3.10.0 (as reported by gdalinfo --version)

### Additional context

``
docker run -it ghcr.io/osgeo/gdal:ubuntu-full-3.10.0 gdalinfo --formats | grep COG
``
Result: COG driver is listed.

Request for Help:

Could you confirm if the COG driver is supported in this image?
If not, is there an alternative image that includes support for COG?
Any additional steps I can take to enable the driver?

**Comment by rouault** [comment]
I don't confirm any issue. The following works fine for me on a Ubuntu 20.04 host:
```
docker run --rm -v $(pwd):/data ghcr.io/osgeo/gdal:ubuntu-full-3.10.0  gdal_translate /data/byte.tif /data/out.tif  -of COG -co TILING_SCHEME=GoogleMapsCompatible -co COMPRESS=JPEG
Input file size is 20, 20
0...10...20...30...40...50...60...70...80...90...100 - done.

$ docker run --rm -it ghcr.io/osgeo/gdal:ubuntu-full-3.10.0 gdalinfo --formats | grep COG
  COG -raster- (wv): Cloud optimized GeoTIFF generator (*.tif, *.tiff)
```

Your host is quite ancient by today's standard, but it would be weird that this is the reason. I don't have any explanation.

**Comment by rouault** [comment]
Can you try adding ``--config GDAL_SKIP netCDF`` toward the end of your command line ? Might be a Linux syscall that Ubuntu 18.04 doesn't like.  Or alternatively add ``--priviledged`` just afer ``docker``

**Comment by rouault** [comment]
Good luck. I'm not super keen on spending more time supporting this, as Ubuntu 18.04 is end of life and doesn't receive any more updates: https://ubuntu.com/blog/18-04-end-of-standard-support
