### ISSUE TITLE
SQL Server data source: geometry column not identified by ogr2ogr

### ISSUE THREAD

**Issue by PhilAnzel** [OSGeo/gdal#1136]
## Expected behavior and actual behavior.

Expected: Using SQL Server "native" driver the geometry column of a retrieved data set would be written to GeoJSON output as geometry data.

Actual: The geometry column of a retrieved data set is treated as a binary data column.

## Steps to reproduce the problem.

(see "Preparation *" sections below for data and driver setup)

Demonstrate successful use of old driver:

  cd (to folder with ogr2ogr.exe and all required DLLs and CSV files)

  set q=SELECT TGEO, TID FROM T where TID=42
  set d=SQL Server
  ogr2ogr 	-sql "%q%" ^
    -f "GeoJSON" ^
	-a_srs EPSG:4326 ^
	old.txt ^
	"MSSQL:driver=%d%;server=pcName\MSSQLSERVER2016;database=PhilTest;Trusted_Connection=Yes;"

See the attached file "old.txt". Note that the expected geometry is presented as WKT.
[old.txt](https://github.com/OSGeo/gdal/files/2655050/old.txt)

Failure case 1: Use new driver with "MSSQL" 

  set q=SELECT TGEO, TID FROM T where TID=42
  set d=ODBC Driver 17 for SQL Server
  ogr2ogr 	-sql "%q%" ^
    -f "GeoJSON" ^
	-a_srs EPSG:4326 ^
	new1.txt ^
	"MSSQL:driver=%d%;server=pcName\MSSQLSERVER2016;database=PhilTest;Trusted_Connection=Yes;"

  Warning 1: The output driver does not natively support Binary 
  type for field TGEO. Misconversion can happen. -mapFieldType 
  can be used to control field type conversion.

See attached file "new1.txt" and observe that the geometry data is not presented as WKT.
[new1.txt](https://github.com/OSGeo/gdal/files/2655051/new1.txt)

Failure case 2: Use new driver with "ODBC" 
	
  set q=SELECT TGEO, TID FROM T where TID=42
  set d=ODBC Driver 17 for SQL Server
  ogr2ogr 	-sql "%q%" ^
    -f "GeoJSON" ^
	-a_srs EPSG:4326 ^
	new2.txt ^
	"ODBC:driver=%d%;server=pcName\MSSQLSERVER2016;database=PhilTest;Trusted_Connection=Yes;"

  Warning 1: The output driver does not natively support Binary 
  type for field TGEO. Misconversion can happen. -mapFieldType 
  can be used to control field type conversion.

See attached file "new2.txt" and observe that the geometry data is not presented as WKT.
[new2.txt](https://github.com/OSGeo/gdal/files/2655068/new2.txt)

## Operating system etc.

Windows 10, x64, with SQL Server 2016 for testing with a local data source.

## GDAL version and provenance

GDAL 2.3.2 (part of Mapserver 7.2.1 Windows x64 distribution, downloaded from http://download.gisinternals.com/sdk/downloads/release-1911-x64-gdal-2-3-2-mapserver-7-2-1.zip). 

## Preparation: OGR files

The folder containing ogr2ogr.exe should contain all needed DLLs, all needed CSV files, and the ogr_MSSQLSpatial.dll plugin.

All command shell commands should be executed in that folder. For example, if the environment variable "pkgroot" points to the folder that holds the Unzipped Mapserver distribution and environment variable "libdir" points to the foler where all DLLs etc. will be copied, use:
  copy %pkgroot%\bin\*.dll %libdir%
  copy %pkgroot%\bin\gdal\csharp\*.dll %libdir%
  copy %pkgroot%\bin\gdal\plugins-optional\ogr_MSSQLSpatial.dll %libdir%
  copy %pkgroot%\bin\gdal\apps\ogr2ogr.exe  %libdir%
  copy %pkgroot%\bin\gdal\apps\ogrinfo.exe  %libdir%
  copy %pkgroot%\bin\ms\csharp\*.dll %libdir%
  copy %pkgroot%\bin\ms\csharp\*.exe %libdir% 
  copy %pkgroot%\bin\gdal-data\*.csv %libdir%
This is much more than you really need, but guarantees that all referenced files are available.

## Preparation: SQL Server drivers

The Microsoft SQL Server ODBC drivers on the computer must include the following (shown via the "Drivers" tab of C:\Windows\System32\odbcad32.exe):

  Name: 	SQL Server
  Version: 	10.00.16299.15
  Company: 	Microsoft Corporation
  File: 	SQLSVR32.DLL
  Date: 	9/29/2017 

  Name: 	ODBC Driver 17 for SQL Server
  Version: 	2017.172.00.01
  Company: 	Microsoft Corporation
  File: 	MSODBCSQL17.DLL
  Date: 	6/22/2018

The first driver provides "MDAC" support for SQL Server 2008, it is now obsolete but is used to demonstrate desired behavior of ogr22ogr.

The second driver, the current Microsoft ODBC driver for SQL Server, may be downloaded from "Microsoft® ODBC Driver 17 for SQL Server® - Windows, Linux, & macOS", https://www.microsoft.com/en-us/download/details.aspx?id=56567 - click on "Download", then select "en-US\msodbcsql_17.2.0.1_x64.msi" and click "Next". The downloaded file, msodbcsql_17.2.0.1_x64.msi, must be installed folloing normal Windows 10 protocol.

## Preparation: Database and data preparation

Use a local SQL Server 2016 instance (in this example named "pcName\MSSQLSERVER2016"), creation of the spatial data is handled through "SQL Server Management Studio" queries.

-- Prepare and populate tables as needed.

use PhilTest;	-- Change database name as appropriate

-- Create a spatial_ref_sys table if needed and populate with SRID=4326
CREATE TABLE [dbo].[spatial_ref_sys](
	[srid] [int] NOT NULL,
	[auth_name] [varchar](256) NULL,
	[auth_srid] [int] NULL,
	[srtext] [varchar](2048) NULL,
	[proj4text] [varchar](2048) NULL,
PRIMARY KEY CLUSTERED ([srid] ASC)
);
go

insert into spatial_ref_sys
(srid, auth_name, auth_srid, srtext, proj4text)
values
(4326, 'EPSG', 4326,
'GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.01745329251994328,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4326"]]',
'+proj=longlat +datum=WGS84 +no_defs ');

GO

-- Create a Geometry_Columns table if needed, add a reference to table "T"
CREATE TABLE [dbo].[geometry_columns](
	[f_table_catalog] [varchar](128) NOT NULL,
	[f_table_schema] [varchar](128) NOT NULL,
	[f_table_name] [varchar](256) NOT NULL,
	[f_geometry_column] [varchar](256) NOT NULL,
	[coord_dimension] [int] NOT NULL,
	[srid] [int] NOT NULL,
	[geometry_type] [varchar](30) NOT NULL,
 CONSTRAINT [geometry_columns_pk] PRIMARY KEY CLUSTERED 
(
	[f_table_catalog] ASC,
	[f_table_schema] ASC,
	[f_table_name] ASC,
	[f_geometry_column] ASC
)
);
go

insert into geometry_columns
(f_table_catalog, f_table_schema, f_table_name, f_geometry_column,
 coord_dimension, srid, geometry_type)
values
('', 'dbo', 'T', 'TGEO', '2', '4326', 'Polygon');
go

-- Create test table "T" in database "PhilTest"
CREATE TABLE [dbo].[T]([TID] [int] NOT NULL, [TGEO] [geometry] NULL);
go

-- Define spatial data for use in test
declare @wkt varchar(100) = 'POLYGON((-104.79 40.15,-104.79 40.17,-104.76 40.17,-104.76 40.15,-104.79 40.15))';
declare @g geometry = geometry::STPolyFromText(@wkt,4326);
select @g;
-- This geometry value is displayed as: (newlines added)
-- 0xE6100000010405000000C3F5285C8F325AC03333333333134440C3F5285C8F325AC0F6285C
-- 8FC2154440713D0AD7A3305AC0F6285C8FC2154440713D0AD7A3305AC03333333333134440C3
-- F5285C8F325AC0333333333313444001000000020000000001000000FFFFFFFF0000000003

insert into T (TID, TGEO) values (42, @g);

## Notes

Note 1:
The same "second driver" behavior occurs in other tested SQL Server 2016 instances (both local and across a network), in other tables, with other projections and use of databse username and password.

Note 2:
The first driver "SQL Server" (SQLSVR32.DLL) is obsolete and does not support TLS1.2, a critical requirement when accessing remote SQL Server instances.
  
Note 3:
If the output is to "ESRI Shapefile" the same warning is presented, the shapefile is corrupt. For example
  set q=SELECT TGEO, TID FROM T where TID=42
  set d=ODBC Driver 17 for SQL Server
  ogr2ogr 	-sql "%q%" ^
    -f "ESRI Shapefile" ^
	-a_srs EPSG:4326 ^
	t42 ^
	"MSSQL:driver=%d%;server=pcName\MSSQLSERVER2016;database=PhilTest;Trusted_Connection=Yes;"
yields:
Warning 1: The output driver does not natively support Binary type for field TGEO. Misconversion can happen. -mapFieldType can be used to control field type conversion.
ERROR 6: Can't create fields of type Binary on shapefile layers.

Note 3:
The same warnings, incorrect GeoJSON file and incorrect Shapefile is also generated by use of earlier Microsoft "native" and "ODBC" drivers.

Note 4:
The same pattern of failures occurred with GDAL 1.11.4.

**Comment by szekerest** [comment]
@PhilAnzel I've created the table as described above, but I couldn't reproduce the problem, however the support for the MSODBC driver haven't been added to the OGR/MSSQL driver yet. I've just committed a fix for this. See nmake.opt for the details how to enable Microsoft ODBC Driver 17 for SQL Server.

You should definitely recompile the driver as a plugin if you need support for either the MSODBCSQL or the native client driver. The GDAL installer from GISInternals supports the plugin for the native client 11 driver as an optional feature.
I've also tested the BCP option with MSSQL ODBC 17 and it was working fairly well.

**Comment by PhilAnzel** [comment]
Tamas please clarify a few things for me.

First question: Regarding the inability to reproduce the problem: were you referencing "Failure case 1" or "Failure case 2"? If either of these I'm concerned - not being able to reproduce tells me either something is wrong with what I've done or a repair is not testable with these examples.

Second question: With respect to "recompile the driver as a plugin", which driver are you referring to? Do I need anything else to recompile the driver other than what is in release-1911-x64-gdal-mapserver-src.zip?

Thanks for adding comments to nmake.opt. I will download the development MapServer+GDAL x64 source package on Monday from http://download.gisinternals.com/sdk/downloads/release-1911-x64-gdal-mapserver-src.zip.

Thanks.

**Comment by szekerest** [comment]
@PhilAnzel 
Q1: I've checked "Failure case 1" which refers to the OGR MSSQLSpatial driver. The generic "ODBC" driver in OGR should not be used to access MSSQL Server.

Q2: I'm referring to  ogr_MSSQLSpatial.dll which should be added to a /gdalplugins subdirectory or it's location should be included in GDAL_DRIVER_PATH. ogrinfo should report the driver as follows:
"MSSQLSpatial -vector- (rw+): Microsoft SQL Server Spatial Database (BCP)"

**Comment by PhilAnzel** [comment]
Thanks Tamas I shall try as soon as possible next week.

**Comment by PhilAnzel** [comment]
The fixes contributed by Tamas on December 14, 2018 addressed this issue. The "geometry" (and presumably "geography as well) columns are now hanled properly.

**Comment by bespin1** [comment]
@szekerest I'm having this issue on 2.3.2 from ubuntugis-unstable ppa (18.04) as well. What are my options given that 
> Driver version 17.2 or higher is required for Ubuntu 18.04 support.

**Comment by steveoh** [comment]
I am having the same issue with 2.3.3 from conda on windows. Should I open another issue?

**Comment by steveoh** [comment]
I had to explicitly cast the what i though already was a wkb geometry back to a geometry for some reason but that did solve my issues.

`GEOMETRY::STGeomFromWKB(shape.STAsBinary(), 26912)`
