### ISSUE TITLE
OGR GML-Driver .gfs issue regarding data types

### ISSUE THREAD

**Issue by JuergenWeichand** [OSGeo/gdal#1138]
## Expected behavior and actual behavior.
The following .gfs definition (Real 12.2) will result in a wrong field definition. 

```
...
<PropertyDefn>
   <Name>flaeche</Name>
   <ElementPath>flaeche</ElementPath>
   <Type>Real</Type>
   <Width>12.2</Width>
</PropertyDefn>
...
```

Test
```
ogrinfo -so wfsP80T80.gml Flurstueck
``` 

expected behavior
```
...
flaeche: Real (12.2)
...
```

current behavior
```
...
flaeche: Real (12.0)
...
```

## Operating system

Windows 7 / Ubuntu 16.04

## GDAL version and provenance

```
ogrinfo --version
GDAL 2.2.4, released 2018/03/19
```

**Comment by rouault** [comment]
The correct encoding would be
<Width>12</Width>
<Precision>2</Precision>

**Comment by JuergenWeichand** [comment]
@rouault Thank you very much for your quick support!
