### ISSUE TITLE
Missing EPSG/ESRI codes since updating to GDAL 3

### ISSUE THREAD

**Issue by rle-rsa** [OSGeo/gdal#11387]
### What is the bug?

Hello

I've been using GDAL for a while, in part to use WMTS datasets from NASA's Trek API such as those listed here: https://trek.nasa.gov/tiles/apidoc/trekAPI.html?body=mars
I've stayed on GDAL 2.4 for way too long, but recently updated. However, now NASA Trek's WMTS no longer load in GDAL:

> ERROR 1: PROJ: proj_create: crs not found: EPSG:104905
> ERROR 1: Cannot parse CRS 'urn:ogc:def:crs:EPSG::104905'

I'm using GDAL 3.8.3 and PROJ 7.2.1 currently (those packaged in my Linux distribution), but I also tried with the latest and get the same error. It worked with GDAL 2.4.2.

The code is this one: https://epsg.io/104905 + https://spatialreference.org/ref/esri/104905/. There is also 104903 for the Moon, etc.

Looking deeper, I can see that previously that was handled by WKT files in GDAL_DATA (specifically esri_extra.wkt for EPSG:104905), but now that's handled by proj.db in PROJ_LIB, and the code seems to be missing from that database.

I don't know if there is a good reason for this regression or if that is a bug, and I don't know if this is considered a GDAL or a PROJ issue. Sorry about that.
I guess I will try to add the codes to proj.db manually on the short term, but I wanted to inform you about this issue.

### Steps to reproduce the issue

gdalinfo https://trek.nasa.gov/tiles/Mars/EQ/THEMIS_NightIR_ControlledMosaics_100m_v2_oct2018/1.0.0/WMTSCapabilities.xml

### Versions and provenance

GDAL 3.8.3 (Windows 10 manual build + openSUSE Leap 15.6 package from distrib)
GDAL 3.9.3 (Windows 10 using latest OSGeo4W release)

**Comment by jratike80** [comment]
The WMTS capabilities show `<ows:SupportedCRS>urn:ogc:def:crs:EPSG::104905</ows:SupportedCRS>` but there is no EPSG:104905. ESRI:104905 does exist and my OSGeo4W GDAL 3.9.3, released 2024/10/07 shows:

```
projinfo ESRI:104905
PROJ.4 string:
+proj=longlat +a=3396190 +rf=169.894447223612 +no_defs +type=crs

WKT2:2019 string:
GEOGCRS["GCS_Mars_2000",
    DATUM["D_Mars_2000",
        ELLIPSOID["Mars_2000_IAU_IAG",3396190,169.894447223612,
            LENGTHUNIT["metre",1]]],
    PRIMEM["Reference_Meridian",0,
        ANGLEUNIT["degree",0.0174532925199433]],
    CS[ellipsoidal,2],
        AXIS["geodetic latitude (Lat)",north,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433]],
        AXIS["geodetic longitude (Lon)",east,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433]],
    USAGE[
        SCOPE["Not known."],
        AREA["World."],
        BBOX[-90,-180,90,180]],
    ID["ESRI",104905]]

```
I saved the GetCapabilities XML into local file and edited it by changing the two appearance of EPSG->ESRI. Now GDAL seems to be happy with the capabilities:

```
gdalinfo marstest.xml
Driver: WMTS/OGC Web Map Tile Service
Files: marstest.xml
Size is 262144, 94771
Coordinate System is:
GEOGCRS["GCS_Mars_2000",
    DATUM["D_Mars_2000",
        ELLIPSOID["Mars_2000_IAU_IAG",3396190,169.894447223612,
            LENGTHUNIT["metre",1]]],
    PRIMEM["Reference_Meridian",0,
        ANGLEUNIT["degree",0.0174532925199433]],
    CS[ellipsoidal,2],
        AXIS["geodetic latitude (Lat)",north,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433]],
        AXIS["geodetic longitude (Lon)",east,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433]],
    USAGE[
        SCOPE["Not known."],
        AREA["World."],
        BBOX[-90,-180,90,180]],
    ID["ESRI",104905]]
Data axis to CRS axis mapping: 2,1
Origin = (-180.000000000000000,65.001211284521617)
Pixel Size = (0.001371750917223,-0.001371750917223)
Metadata:
  TITLE=THEMIS_NightIR_ControlledMosaics_100m_v2_oct2018
  ...


```

**Comment by rle-rsa** [comment]
Thank you for your help!

I can confirm this fixes the issue with GDAL 3.9.3. It doesn't with my GDAL 3.8.3 + PROJ 7.2.1 build (gives new errors _URN urn:ogc:def:crs:ESRI::104905 has unrecognized authority_ + _Cannot parse CRS 'urn:ogc:def:crs:ESRI::104905'_), but I can update if that's what it takes.

However that solution is not ideal as it requires downloading and editing the WMTSCapabilities.xml file for every dataset. Ideally I would like to force the fixed code externally. I tried using the `<Projection>` tag in the calling GDAL_WMTS XML but it does not seem to work: I still get the error message about "EPSG:104905" .

**Comment by rouault** [comment]
Fixed by https://github.com/OSGeo/gdal/pull/11390
The axis order in elements of the WMTS capabilities doc was also wrong

**Comment by rle-rsa** [comment]
Thank you for the quick "fix", I will definitely update to the next release.
