### ISSUE TITLE
ogr2ogr transfer relationships defined in geopackages

### ISSUE THREAD

**Issue by ea-eriksson** [OSGeo/gdal#11397]
### Feature description

When converting between gpkgs with ogr2ogr, support transferring relationships defined by related tables or foreign keys to the output.

If ogr2ogr is for example used to reproject a gpkg, defined relationships appears to be lost and must be recreated again.

Recreating relationships defined with the related tables extension is not necessarily problematic, but lost foreign keys are more difficult to fix as the tables must be dropped and recreated. It would therefore be great if these relationships were transferred directly by ogr2ogr.

Most desirable would be if ogr2ogr could also transfer relations when converting formats, e.g. from File Geodatabase to gpkg.

**Comment by rouault** [comment]
[GDALRelationship](https://gdal.org/en/stable/doxygen/classGDALRelationship.html) could probably be transferred with moderate effort and risk by ogr2ogr
Foreign keys are much more tricky because tables must be created and filled in the right order depending on the dependency graph formed by foreign keys

**Comment by ea-eriksson** [comment]
Yes, I would suggest to only consider transferring GDAL relationships with ogr2ogr. I guess foreign key relationships in gpkgs are not often used anyway because they are limited in how they can be defined

**Comment by jratike80** [comment]
Transferring relations makes sense only when the data from the both sides of the relations are also transferrer, so it could be possible with a command like
`ogr2ogr -f gpkg output.gpkg input.gpkg [options that can be used for all layers]` (-spat, -t_srs, -a_srs, -clip*, ...)
May get complicated is user selects a subset of GPKG layers, including the ones used in relations into a VRT file and transfers then the whole VRT.
