### ISSUE TITLE
Reading ENVI files with only 2 columns

### ISSUE THREAD

**Issue by corrado9999** [OSGeo/gdal#1140]
## Expected behavior and actual behavior.

I expected that opening the attached [raster file](https://github.com/OSGeo/gdal/files/2667268/testfile.zip) (must be unzipped) requires ~2GB of RAM, but memory allocation almost reaches 50GB. 

## Steps to reproduce the problem.
Either by python code
```python
import gdal
ds = gdal.Open('testfile')
a = ds.ReadAsArray()
```
or also with `gdal_translate` (in this case, memory increases linearly with percentage completion)
```sh
gdal_translate -of GTiff testfile testfile_tif.tiff
```
The issue does not arise with GeoTIFF input (other formats untested) or when ENVI input file is less narrow (e.g. 100-200 columns).

## Operating system

CentOS 7.5/6.4 64 bit

## GDAL version and provenance

Both 2.0.1 compiled from scratch and 2.2.4 from conda-forge

**Comment by rouault** [comment]
The file raw size is 2 GB, so if you do ReadAsArray(), it is expected that it will take 2 GB too.

Regarding gdal_translate, this is the effect of the block cache that tops to 5% of your RAM. You can decrease the cunsumption by setting GDAL_CACHEMAX=X% for a percentage of the RAM  or GDAL_CACHEMAX=X for a fixed number of MB (let's say 100).

So things work as designed from my point of view

**Comment by corrado9999** [comment]
I have probably not been clear. I did expect 2GB of RAM allocation too, but the actual allocation was 50GB.
