### ISSUE TITLE
GML / AIXM: ElevatedCurve is not parsed

### ISSUE THREAD

**Issue by vlapra** [OSGeo/gdal#11425]
### What is the bug?

The ElevatedCurve geometry is not parsed.

### Steps to reproduce the issue

There is already a request AIXM ElevatedCurve not detected #4600, but nothing has changed for 3 years. Steps to reproduce is described there.

### Versions and provenance

latest / night build

### Additional context

A similar issue with ElevatedPoint was fixed quite quickly.
If GeodesicString is used, changing ElevatedCurve to Curve is sufficient, and the parsing will work correctly.
The dataset also contains Geodesic with more than two points, but I'm not sure if this is a data error.

Could it be possible to add processing for ElevatedCurve as well? This would improve the usability of this great library.

Attached whole dataset and short sample.

[Donlon.zip](https://github.com/user-attachments/files/17992493/Donlon.zip)
[wrong.zip](https://github.com/user-attachments/files/17992494/wrong.zip)

**Comment by jratike80** [comment]
Please add your comments to the existing issue instead of creating a dublicate.

**Comment by jratike80** [comment]
Please copy the appropriate comments to the other ticket and I will close this one. Or do you think that you found something essentially new and different?

**Comment by vlapra** [comment]
Thank you, I will copy this to the original issue.

I don't think I've discovered anything new, but unfortunately, my experience tells me that adding comments to long-standing requests marked as "Enhancement" usually doesn't get a response.

A modification for at least basic processing of ElevatedCurve should not be complicated and could be handled similarly to Curve.

I could try to make the modification myself, but unfortunately, I'm not very familiar with this project.

**Comment by jratike80** [comment]
I do not know AIX and elevated curves, but I wonder why there are elevated curves in the data contains just X and Y.  Elevation other possible attributes appears nowhere in the data. https://aixm.aero/sites/default/files/imce/AIXM51HTML/AIXM/Class_ElevatedCurve.html.
If GDAL would support ElavetedCurve, should it be able to handle all attributes then?

elevation
geoidUndulation
verticalDatum
verticalAccuracy
horizontalAccuracy

**Comment by antoniolocandro** [comment]
@jratike80 possibly someone didn't think it as a great deal, AIXM is 2.5D so in my mind no need to handle anything else but display the geometry.
