### ISSUE TITLE
Easier launch of individual .py files

### ISSUE THREAD

**Issue by rouault** [OSGeo/gdal#1142]
@craigds  I'm slightly annoyed to have to type "pytest foo.py" instead of just "./foo.py" as before.
While looking at the content of the pytest launch script, I've discovered that putting
```
import sys
from pytest import main
if __name__ == '__main__':
    sys.exit(main(sys.argv))
```

at the top of each .py file does the job (this must be put at the top, since the 'import ogrtest' would fail). Anything against that ? Could you automate adding this ?

**Comment by rcoup** [comment]
@craigds is there a way with this it can still pickup `conftest.py` from the right places? Otherwise I think the fixtures don't work

**Comment by craigds** [comment]
I don't suppose a normal shebang would work?

/me tries it

**Comment by craigds** [comment]
pytest.main() finds and runs the conftest.py correctly.

Doing this at the top of the file wreaks havoc with flake8 linter 😞 
<img width="764" alt="screen shot 2018-12-14 at 9 50 13 am" src="https://user-images.githubusercontent.com/32112/49966783-dd19f800-ff85-11e8-8f21-aeaf368e4686.png">

Just changing the shebang to `#!/usr/bin/env pytest` makes it work for me without linter craziness or a noisy `__main__` block, though presumably that won't work on Windows.

**Comment by craigds** [comment]
Having a `python` shebang doesn't make a lot of sense anyway when running the file with `python` does essentially nothing. I'll submit a PR for changing it.
