### ISSUE TITLE
CMAKE FindSFCGAL.cmake for libSFCGAL-osg.2.0.0

### ISSUE THREAD

**Issue by chris-english** [OSGeo/gdal#11453]
### Feature description

In the event that one has compiled libSFCGAL-osg.2.0.0, CMAKE FindSFCGAL only looks for SFCGAL and SFCGALd. Would:

find_library(SFCGAL_LIBRARY_RELEASE NAMES SFCGAL-osg
             HINTS ${SC_SFCGAL_LIBDIR}
             PATH ${SFCGAL_ROOT}
             PATH_SUFFIXES lib Lib
             )

be sufficient edit to FindSFCGAL.cmake that it would be found?

**Comment by rouault** [comment]
CC @lbartoletti 

@chris-english For my education, what is "libSFCGAL-osg" ? Which distribution channel provides it ?

**Comment by chris-english** [comment]
I managed to build it after following this OpenSceneGraph [PR](https://github.com/openscenegraph/OpenSceneGraph/pull/1281/commits/26f6c9b5a63715dde3c9f85c8faf035d3ec0f657). OpenSceneGraph is currently starved for resources as seemingly all devs are now working on Vulkan GPU. Yet, there remains a large group still working with CPU, including me.

**Comment by chris-english** [comment]
But given how Find is configured, even pointing to lib and include and GDAL_USE_SFCGAL=ON bring no joy in cmake <point-to-things> ..

**Comment by dg0yt** [comment]
A general change might be multiple NAMES + NAMES_PER_DIR.
And while writing this comment, I see that PATHS is misspelled in that find modules.
~~~diff
-find_library(SFCGAL_LIBRARY_RELEASE NAMES SFCGAL
+find_library(SFCGAL_LIBRARY_RELEASE
+             NAMES SFCGAL SFCGAL-osg
+             NAMES_PER_DIR
              HINTS ${SC_SFCGAL_LIBDIR}
-             PATH ${SFCGAL_ROOT}
+             PATHS ${SFCGAL_ROOT}
              PATH_SUFFIXES lib Lib
             )
~~~~

**Comment by chris-english** [comment]
The @dg0yt suggested change to cmake find library does find SFCGAL-osg, but then undefined references:
[ 86%] Linking CXX shared library libgdal.so
/usr/bin/ld: ogr/CMakeFiles/ogr.dir/ogrgeometry.cpp.o: in function `OGRGeometry::OGRexportToSFCGAL(OGRGeometry const*)':
ogrgeometry.cpp:(.text+0x84ce): undefined reference to `sfcgal_init'
/usr/bin/ld: ogrgeometry.cpp:(.text+0x8535): undefined reference to `sfcgal_io_read_wkt'
<---snip--->
that I'm still head scratching over.

**Comment by dg0yt** [comment]
IIUC the `SFCGAL-osg` library doesn't include the SFCGAL objects but links to the `SFCGAL` library.
So you don't want `SFCGAL-osg` for `SFCGAL_LIBRARY_*` if you need SFCGAL C API (`sfcgal_init` etc.).
https://gitlab.com/sfcgal/SFCGAL/-/blob/master/src/CMakeLists.txt#L100-109

**Comment by lbartoletti** [comment]
imho, you could remove sfcgal-osg. We haven't done any maintenance on this part for a very long time. In fact, it used to be there, because at the time it was used for a 3D viewer, but now we have other tools for that : QGIS 3D, Web 3D viewer...
Moreover, you have to use SFCGAL C API which doesn't use SFCGAL-osg

**Comment by rouault** [comment]
Closing as not a GDAL issue
