### ISSUE TITLE
Random failure on ngw tests

### ISSUE THREAD

**Issue by rouault** [OSGeo/gdal#1145]
@BishopGIS We just got a CI test failure on NGW tests. Presumably a network issue. Any way of making them more robust to that ?
See https://travis-ci.com/OSGeo/gdal/jobs/165088825 / https://api.travis-ci.com/v3/job/165088825/log.txt

**Comment by BishopGIS** [comment]
It seems to me the failure was in this CI run: https://api.travis-ci.org/v3/job/467785323/log.txt

I'll move raster tests from https://demo.nextgis.com to http://dev.nextgis.com/sanbox. Need to add CreateCopy for raster because sandbox freed weekly.

**Comment by rouault** [comment]
Re-opening this one. @BishopGIS Which commits need to be backported for 2.4 as well ? See https://github.com/OSGeo/gdal/commit/6460dae6c2111dfe7c4c704cc7ca6800612c431e#comments

**Comment by rouault** [comment]
Even in master, there are occasional failures (although much less frequent), like in https://api.travis-ci.com/v3/job/166847091/log.txt

**Comment by BishopGIS** [comment]
It seems to me commit 89883fcf068e4e45b0c91d2e868d1874bae16ab7 helped.

**Comment by BishopGIS** [comment]
I just need to commit changes to release/2.4 branch or additional steps needed?

**Comment by rouault** [comment]
Yes you may cherry-pick needed commits from master into release/2.4 and push. You may also do that in a branch based on release/2.4 and do a pull request against release/2.4 if you want the CI to have a try

**Comment by rouault** [comment]
https://github.com/OSGeo/gdal/commit/180cc0e360c9190a08dd030bc6466c4d9082be97 seems to have done it for release/2.4. Thanks. Closing

**Comment by rouault** [comment]
Still got a random failure on master
```
=================================== FAILURES ===================================
__________________________________ test_ngw_3 __________________________________

    def test_ngw_3():
    
        if gdaltest.ngw_drv is None:
            pytest.skip()
    
        if check_availability(gdaltest.ngw_test_server) == False:
            gdaltest.ngw_drv = None
            pytest.skip()
    
        new_name = 'gdaltest_group_' + str(int(time.time()) - 2)
        ds_resource_id = gdaltest.ngw_ds.GetMetadataItem('id', '')
        rename_url = 'NGW:' + gdaltest.ngw_test_server + '/resource/' + ds_resource_id
    
>       assert gdaltest.ngw_drv.Rename(new_name, rename_url) == gdal.CE_None, \
            'Rename datasource failed.'
E       AssertionError: Rename datasource failed.
E       assert 3 == 0
E        +  where 3 = <bound method Driver.Rename of <osgeo.gdal.Driver; proxy of <Swig Object of type 'GDALDriverShadow *' at 0x7f0de227a2d0> >>('gdaltest_group_1547071882', 'NGW:http://dev.nextgis.com/sandbox/resource/1653')
E        +    where <bound method Driver.Rename of <osgeo.gdal.Driver; proxy of <Swig Object of type 'GDALDriverShadow *' at 0x7f0de227a2d0> >> = <osgeo.gdal.Driver; proxy of <Swig Object of type 'GDALDriverShadow *' at 0x7f0de227a2d0> >.Rename
E        +      where <osgeo.gdal.Driver; proxy of <Swig Object of type 'GDALDriverShadow *' at 0x7f0de227a2d0> > = gdaltest.ngw_drv
E        +  and   0 = gdal.CE_None

ngw.py:125: AssertionError
```

I'd say perhaps 5% of the builds fail on NGW.  Stubbing the server like done for other drivers could be a more reliable solution. Or perhaps create a Docker image of the server and pull it in Travis to get local testing only ?

**Comment by rouault** [comment]
ngw tests are now skipped by default, closing
