### ISSUE TITLE
Wrong 404 not found

### ISSUE THREAD

**Issue by jjimenezshaw** [OSGeo/gdal#11456]
### What is the bug?

If I type a wrong URL, the URL changes to one adding "en/latest"
I don't know if it is a problem in ReadTheDocs, or in our configuration.

### Steps to reproduce the issue

If you go to
https://gdal.org/en/stable/foo
it is not found (that is correct), but redirects to
https://gdal.org/en/latest/en/stable/foo

### Versions and provenance

Webpage

**Comment by rouault** [comment]
> If I type a wrong URL, the URL changes to one adding "en/latest"

what's wrong with that ? This is the general mechanism to redirect to the default branch, for existing pages and unexistant ones. Or are you expected a custom 404 page ? If so, that would be more about https://docs.readthedocs.io/en/stable/reference/404-not-found.html

**Comment by jjimenezshaw** [comment]
> > If I type a wrong URL, the URL changes to one adding "en/latest"
> 
> what's wrong with that ? This is the general mechanism to redirect to the default branch, for existing pages and unexistant ones. Or are you expected a custom 404 page ? If so, that would be more about https://docs.readthedocs.io/en/stable/reference/404-not-found.html

Is it normal that it changes the URL? I was very confused that "latest" appeared in the URL, when it was not in the string I typed.

**Comment by dbaston** [comment]
Here's what's in our configuration. Now that we have a `/stable`, maybe we want to redirect there?

![image](https://github.com/user-attachments/assets/97b5211f-5ad2-4063-b6a2-47fc6b21db56)

**Comment by rouault** [comment]
> Is it normal that it changes the URL? I was very confused that "latest" appeared in the URL, when it was not in the string I typed.

oh, I didn't read carefully your initial post. I now understand what confused you.  I've fixed the manual redirection @dbaston pointed to, and the effect is now that https://gdal.org/en/stable/foo no longer redirects to something else. But the side effect is that https://gdal.org/en/latest/foo  redirects to https://gdal.org/en/stable/en/latest/foo . I don't think we can do anything about that on our side. More like a ReadTheDocs bug/feature resulting from the below general settings:

![image](https://github.com/user-attachments/assets/1c8a5224-6343-4bf2-8d64-0e8fcc2ee2bb)

> Why the language selection "/en/ there? Do we have or have plans to support more languages? 

Probably not, but I'd keep it as it for now to minimize further URL churn.

**Comment by jjimenezshaw** [comment]
> I don't think we can do anything about that on our side. More like a ReadTheDocs bug/feature resulting from the below general settings:

I think so too.
