### ISSUE TITLE
ogr2ogr: GML driver produces invalid XML for VSI GeoJSON input

### ISSUE THREAD

**Issue by dodinh** [OSGeo/gdal#11484]
### What is the bug?

ogr2ogr produces invalid XML in the following setting:
* using vsistdin
* GML output
* GeoJSON input
  * Feature or any geometry
  * FeatureCollection without "name"

This produces XML with an illegal tag: `<ogr: gml:id=".0">`

When creating from a file instead of vsistdin, the filename is used here.
When creating from a FeatureCollection with a "name" property, that value is used here.

### Steps to reproduce the issue

```
echo '{
    "type": "FeatureCollection",
    "features": [{
        "type":"Feature",
        "geometry": {
            "type":"Point",
            "coordinates":[10,20]
        }
    }]
}' | ogr2ogr -f GML /vsistdout/ /vsistdin/
```

produces

```
<?xml version="1.0" encoding="utf-8" ?>
<ogr:FeatureCollection
     gml:id="aFeatureCollection"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="http://ogr.maptools.org/ .xsd"
     xmlns:ogr="http://ogr.maptools.org/"
     xmlns:gml="http://www.opengis.net/gml/3.2">
  <gml:boundedBy><gml:Null /></gml:boundedBy>
  <ogr:featureMember>
    <ogr: gml:id=".0">
      <gml:boundedBy><gml:Envelope srsName="urn:ogc:def:crs:EPSG::4326"><gml:lowerCorner>20 10</gml:lowerCorner><gml:upperCorner>20 10</gml:upperCorner></gml:Envelope></gml:boundedBy>
      <ogr:geometryProperty><gml:Point srsName="urn:ogc:def:crs:EPSG::4326" gml:id=".geom.0"><gml:pos>20 10</gml:pos></gml:Point></ogr:geometryProperty>
    </ogr:>
  </ogr:featureMember>
</ogr:FeatureCollection>
```

Note esp. the `<ogr: gml:id=".0">`

Compare to a version producing valid XML using file input:

```
echo '{
    "type": "FeatureCollection",
    "features": [{
        "type":"Feature",
        "geometry": {
            "type":"Point",
            "coordinates":[10,20]
        }
    }]
}' > test.json
ogr2ogr -f GML /vsistdout/ test.json
```

produces

```
<?xml version="1.0" encoding="utf-8" ?>
<ogr:FeatureCollection
     gml:id="aFeatureCollection"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="http://ogr.maptools.org/ .xsd"
     xmlns:ogr="http://ogr.maptools.org/"
     xmlns:gml="http://www.opengis.net/gml/3.2">
  <gml:boundedBy><gml:Null /></gml:boundedBy>
  <ogr:featureMember>
    <ogr:test gml:id="test.0">
      <gml:boundedBy><gml:Envelope srsName="urn:ogc:def:crs:EPSG::4326"><gml:lowerCorner>20 10</gml:lowerCorner><gml:upperCorner>20 10</gml:upperCorner></gml:Envelope></gml:boundedBy>
      <ogr:geometryProperty><gml:Point srsName="urn:ogc:def:crs:EPSG::4326" gml:id="test.geom.0"><gml:pos>20 10</gml:pos></gml:Point></ogr:geometryProperty>
    </ogr:test>
  </ogr:featureMember>
</ogr:FeatureCollection>

```

### Versions and provenance

Linux Mint 22
GDAL 3.8.4, released 2024/02/08 (via apt)

**Comment by jratike80** [comment]
Maybe it is because the GeoJSON data does not contain the layer name? From the file input the layer name is derived from the file name.

I tried to make some tests but it appears to be complicated on Windows.

**Comment by dodinh** [comment]
> Maybe it is because the GeoJSON data does not contain the layer name

Yes, that is the cause. But as `name` is not mandatory in valid GeoJSON, it should ideally also not be needed here. If not existing, possibly something generic could be used (as is the case e.g. for WKT input via CSV, where the tag name is `<ogr:layer>`).

**Comment by rouault** [comment]
Fixed per https://github.com/OSGeo/gdal/commit/20ff89719d1953221a908c59f3c3c1ef786d6bdf

Workaround: add ``-nln some_name`` to your ogr2ogr command line
