### ISSUE TITLE
Mask for overlapped layers masks both of them

### ISSUE THREAD

**Issue by drnextgis** [OSGeo/gdal#1148]
I'd like to mosaic two overlapped rasters with VRT (see attachments). Both of them has a mask. But result looks like this. Is it expected result?

![image](https://user-images.githubusercontent.com/866124/50018834-d5cc0c00-ffd0-11e8-8b3e-b7ffccb80473.png)

```
gdalbuildvrt -input_file_list list.txt output.vrt
```

[overlapped-rasters.zip](https://github.com/OSGeo/gdal/files/2681162/overlapped-rasters.zip)

**Comment by rouault** [comment]
"expected" yes as some famous CPU founder claims that their chips work as intended despite having security holes :-)
So more seriously VRT doesn't do alpha-compositing. It just takes the alpha component of the last-appearing source.
gdalwarp is currently the tool to get the effect you want (so in a non virtual way)
