### ISSUE TITLE
ogr2ogr: projection / coordinate ordering options being ignored when converting GML to GeoJSON

### ISSUE THREAD

**Issue by dodinh** [OSGeo/gdal#11491]
### What is the bug?

When converting GML to GeoJSON, coordinate order is correctly changed from lat/long to long/lat when an srsName is specified in the GML. If the srsName is left out, the order does not change.

From the documentation pages
* for ogr2ogr: https://gdal.org/en/stable/programs/ogr2ogr.html#cmdoption-ogr2ogr-t_srs
* for the GML driver: https://gdal.org/en/stable/drivers/vector/gml.html#open-options

I would have thought that specifying `s_srs` and `t_srs` as ogr2ogr options would have the same effect as specifying srsName in the GML, but it doesn't change anything. Various "-oo" options targeting coordinate order also seem to be ignored:
* INVERT_AXIS_ORDER_IF_LAT_LONG
* SWAP_COORDINATES

### Steps to reproduce the issue

1. srsName is specified in the GML source:
```
echo -e '<?xml version="1.0" encoding="utf-8" ?>
<ogr:FeatureCollection
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="http://ogr.maptools.org/ .xsd"
     xmlns:ogr="http://ogr.maptools.org/"
     xmlns:gml="http://www.opengis.net/gml/3.2">
  <ogr:featureMember>
    <ogr:layer>
      <ogr:geometryProperty>
        <gml:Point srsName="EPSG:4326">
            <gml:pos>48.85824174833627 2.2945114390997503</gml:pos>
        </gml:Point>
      </ogr:geometryProperty>
    </ogr:layer>
  </ogr:featureMember>
</ogr:FeatureCollection>
' | ogr2ogr -f geojson /vsistdout/ /vsistdin/ -oo CONSIDER_EPSG_AS_URN=YES
```
correctly produces
```
{
"type": "FeatureCollection",
"name": "layer",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { }, "geometry": { "type": "Point", "coordinates": [ 2.29451143909975, 48.858241748336269 ] } }
]
}
```

2. srsName not specified in the GML source but via arguments to ogr2ogr:
```
echo -e '<?xml version="1.0" encoding="utf-8" ?>
<ogr:FeatureCollection
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="http://ogr.maptools.org/ .xsd"
     xmlns:ogr="http://ogr.maptools.org/"
     xmlns:gml="http://www.opengis.net/gml/3.2">
  <ogr:featureMember>
    <ogr:layer>
      <ogr:geometryProperty>
        <gml:Point>
            <gml:pos>48.85824174833627 2.2945114390997503</gml:pos>
        </gml:Point>
      </ogr:geometryProperty>
    </ogr:layer>
  </ogr:featureMember>
</ogr:FeatureCollection>
' | ogr2ogr -f geojson /vsistdout/ /vsistdin/ -oo CONSIDER_EPSG_AS_URN=YES -s_srs EPSG:4326 -t_srs EPSG:4326
```
unexpectedly produces
```
{
"type": "FeatureCollection",
"name": "layer",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { }, "geometry": { "type": "Point", "coordinates": [ 48.858241748336269, 2.29451143909975 ] } }
]
}
```

2b. Various combinations of `s_srs`, `t_srs`, `-oo INVERT_AXIS_ORDER_IF_LAT_LONG=YES / NO` and `-oo SWAP_COORDINATES=YES / NO` do not change the output in 2.

### Versions and provenance

Linux Mint 22
GDAL 3.8.4, released 2024/02/08 (via apt)

**Comment by rouault** [comment]
Fix in https://github.com/OSGeo/gdal/pull/11492 for "-oo SWAP_COORDINATES=YES" to have an effect in that case where there is no CRS inside the GML file.
Not that the -s_srs flag of ogr2ogr has no influence on any of those open options. Options specific of ogr2ogr like -s_srs cannot influence the processing done by the GML driver itself
