### ISSUE TITLE
autotest osr/osr_proj4.py missing shared libs name

### ISSUE THREAD

**Issue by matzeri** [OSGeo/gdal#1150]
## Expected behavior and actual behavior.
running autotest for 2.3.3rc2
  TEST: ogr_gpkg_15 ... cannot load libproj.so, proj.dll, proj-9.dll, libproj-0.dll, libproj-10.dll, cygproj-10.dll or libproj.dylib
success

while expected is
 TEST: ogr_gpkg_15 ... success

## Steps to reproduce the problem.

just run the run_all.py

## Operating system

Cygwin 64bit with  proj 5.2.0-1 package

## GDAL version and provenance

Built from source gdal-2.3.3rc2.tar.xz  gdalautotest-2.3.3rc2.tar.gz

## additional
the problem is due to osr/osr_proj4.py  expecting 

for name in ["libproj.so", "proj.dll", "proj-9.dll", "libproj-0.dll", "libproj-10.dll", "cygproj-10.dll", "libproj.dylib"]:

for cygwin there was never a cygproj-10.dll. The sequence was cygproj-9.dll, cygproj-12.dll, cygproj-13.dll

**Comment by rouault** [comment]
See https://lists.osgeo.org/pipermail/gdal-dev/2018-December/049475.html

**Comment by rouault** [comment]
This issue will become obsolete once the gdalbarn branch has been merged in master
