### ISSUE TITLE
OGRPolygon breaks if it crosses the date line

### ISSUE THREAD

**Issue by Kuprin2000** [OSGeo/gdal#11500]
### What is the bug?

I am trying to create an OGRPolygon from an OGRLinearRing that contains a set of points specified in a WGS84 spatial reference. If the OGRLinearRing contains points lying on different sides of the data line, I get an unexpected result.
![image](https://github.com/user-attachments/assets/ed567c6e-1f28-458c-acf7-e5c2c4a5a815)

### Steps to reproduce the issue

```
#include "gdal/ogrsf_frmts.h"
#include "gdal/gdal.h"

std::vector<double> lat = { 60.369458988155344, 60.192029612358240, 63.503129367347029, 63.720321197335139, 60.369458988155344 };
std::vector<double> lon = { -179.37040139158972, 173.10757687751484, 172.07307331731039, -179.27477570094075, -179.37040139158972 };

OGRLinearRing* ring = static_cast<OGRLinearRing*>(OGRGeometryFactory::createGeometry(wkbLinearRing));
ring->setPoints(lat.size(), lon.data(), lat.data());

std::shared_ptr<OGRPolygon> poly(static_cast<OGRPolygon*>(OGRGeometryFactory::createGeometry(OGRwkbGeometryType::wkbPolygon)), OGRGeometryFactory::destroyGeometry);
poly->addRingDirectly(ring);

std::string wkt = poly->exportToWkt();
// POLYGON ((-179.37040139159 60.3694589881553,173.107576877515 60.1920296123582,172.07307331731 63.503129367347,-179.274775700941 63.7203211973351,-179.37040139159 60.3694589881553))

```

### Versions and provenance

Windows 10
GDAL 3.9.1

**Comment by jratike80** [comment]
I think that the result is expected for GDAL. You must split the linear ring at the antimeridian.

**Comment by Kuprin2000** [comment]
> I think that the result is expected for GDAL. You must split the linear ring at the antimeridian.

Thank you for an answer. Could you please send a link on the documentation page where it says what to do in this case.

**Comment by jratike80** [comment]
I am just another user and I don't know if it is documented, or if it is just a secret that sorts out experienced and less experienced GIS folks. Myself I have learned by trial and error and from places like https://gis.stackexchange.com/questions/376720/gdal-vectortranslate-fails-to-wrap-the-antimeridian-on-specific-input. I feel that there are always problems with antimeridian but I live at 25 degrees East so I can mostly avoid them.

**Comment by Kuprin2000** [comment]
> I am just another user and I don't know if it is documented, or if it is just a secret that sorts out experienced and less experienced GIS folks. Myself I have learned by trial and error and from places like https://gis.stackexchange.com/questions/376720/gdal-vectortranslate-fails-to-wrap-the-antimeridian-on-specific-input. I feel that there are always problems with antimeridian but I live at 25 degrees East so I can mostly avoid them.

Thank you anyway :)
Let's wait for an oficial answer together

**Comment by msmitherdc** [comment]
Just to note, there is a way to get OGR to split geometries that cross the antemeridian, and that is to use the geojson driver with layer creation options "RFC7946=YES" and "WRAPDATELINE=YES". This is something Even taught me that works quite well. We use it in python a lot with /vsimem. For example:

out_ds = gdal.VectorTranslate("/vsimem/out.json",in_ds, format="GeoJSON", layerCreationOptions=["RFC7946=YES", "WRAPDATELINE=YES", "WRITE_BBOX=YES"])

 

Mike

 

 

-- 

Michael Smith

Remote Sensing/GIS Center

US Army Corps of Engineers

 

 

 

 

From: Jukka Rahkonen ***@***.***>
Reply-To: OSGeo/gdal ***@***.***>
Date: Monday, December 16, 2024 at 8:26 AM
To: OSGeo/gdal ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [OSGeo/gdal] OGRPolygon breaks if it crosses the date line (Issue #11500)

 

I am just another user and I don't know if it is documented, or if it is just a secret that sorts out experienced and less experienced GIS folks. Myself I have learned by trial and error and from places like https://gis.stackexchange.com/questions/376720/gdal-vectortranslate-fails-to-wrap-the-antimeridian-on-specific-input. I feel that there are always problems with antimeridian but I live at 25 degrees East so I can mostly avoid them.

**Comment by jratike80** [comment]
That is a good advice and I have been using that for fixing many datasets. But just for this use case, isn't it too late? If linear ring is built from std::vector<double> lat/lon, and GDAL creates a polygon `POLYGON ((-179.37040139159 60.3694589881553,173.107576877515 60.1920296123582,172.07307331731 63.503129367347,-179.274775700941 63.7203211973351,-179.37040139159 60.3694589881553))` it does not cross the antimeridian any more.

**Comment by msmitherdc** [comment]
Yes, it would have to be done before this and it would yield a single multipolygon object with a poly on either side

**Comment by rouault** [comment]
> Could you please send a link on the documentation page where it says what to do in case there are problems with antimeridian?

Actually, what would make thing in the documentation that OGR should do anything special regarding antimeridian ? The base OGR geometry model is a planar one, consistent with OGC Simple Features Access, that is completely projection agnostic. https://github.com/OSGeo/gdal/pull/11501 should hopefully clarify
