### ISSUE TITLE
Make CRS parsing of GTI:index.parquet consistent with STACIT:items.json

### ISSUE THREAD

**Issue by scottyhq** [OSGeo/gdal#11512]
### Feature description

I was expecting that STACIT and GTI drivers would recognize a STAC item's CRS in the same way, but this is currently only true if an item uses `proj:epsg`. 

For the [STAC projection extension](https://github.com/stac-extensions/projection#best-practices), it's possible to specify `proj:projjson` and `proj:wkt2` (and proj:epsg has been deprecated in favor of `proj:code`... I see those changes for STACIT are being worked on here https://github.com/OSGeo/gdal/pull/10773). 

If I understand correctly, the STACIT driver chooses the CRS with the following order (1. epsg code, 2. wkt2, 3. projjson)
https://github.com/OSGeo/gdal/blob/42ca02ce9397ec3f37dcc46eace97011f1aa0d53/frmts/stacit/stacitdataset.cpp#L221-L237

But the GTI driver currently does not read projjson or wkt2:
https://github.com/OSGeo/gdal/blob/42ca02ce9397ec3f37dcc46eace97011f1aa0d53/frmts/gti/gdaltileindexdataset.cpp#L1171-L1178

### Additional context

Here is a valid STAC item without epsg, but with wkt2:
For example, here is a STAC Item without an EPSG code:
https://landsatlook.usgs.gov/stac-server/collections/landsat-c2l2alb-sr/items/LC09_L2SP_062047_20241216_20241217_02_A1_SR

And here is a valid item with projjson:
https://raw.githubusercontent.com/uw-cryo/stv-aux-data/refs/heads/main/CO_WestCentral_2019_A19/utm12/USGS_1M_12_x76y426_CO_WestCentral_2019_A19.json

The docs are currently accurate in that the GTI driver only seems to look at `proj:epsg` and `proj:transform`, but it would be great if these similar drivers worked consistently with the CRS parsing.
> It can make use of fields proj:epsg and proj:transform from the [Projection Extension Specification](https://github.com/stac-extensions/projection/), to correctly infer the appropriate projection and resolution.

**Comment by rouault** [comment]
see https://github.com/OSGeo/gdal/pull/11514
