### ISSUE TITLE
OGRVRTLayer layer level SrcRegion clip not implemented

### ISSUE THREAD

**Issue by tcommandeur** [OSGeo/gdal#11519]
### What is the bug?

According to the documentation of [VRT](https://gdal.org/en/stable/drivers/vector/vrt.html) the SrcRegion on OGRVRTLayer should have a clip attribute.

> SrcRegion (optional) : This element is used to define an initial spatial filter for the source features. This spatial filter will be combined with any spatial filter explicitly set on the VRT layer with the SetSpatialFilter() method. The value of the element must be a valid WKT string defining a polygon. An optional clip attribute can be set to "TRUE" to clip the geometries to the source region, otherwise the source geometries are not modified.

For the GeometryField the SrcRegion clip="true" is working but looking at the source code its not implemented for OGRVRTLayer.

### Steps to reproduce the issue

**Not working VRT for SrcRegion clip on VRTLayer**
```
<OGRVRTDataSource>
    <OGRVRTLayer name="pand">
        <SrcDataSource>bag-light.gpkg</SrcDataSource>
        <SrcLayer>pand</SrcLayer>
        <LayerSRS>EPSG:28992</LayerSRS>
        <SrcRegion clip="true">POLYGON((120000 435000, 155000 435000, 155000 470000, 120000 470000, 120000 435000))</SrcRegion>
    </OGRVRTLayer>
</OGRVRTDataSource>
```

**Working VRT for GeometryField**
```
<OGRVRTDataSource>
    <OGRVRTLayer name="pand">
        <SrcDataSource>bag-light.gpkg</SrcDataSource>
        <SrcLayer>pand</SrcLayer>
        <LayerSRS>EPSG:28992</LayerSRS>
        <GeometryField>
            <!-- Clip is only implemented at GeometryField level and not at OGRVRTLayer level -->
            <SrcRegion clip="true">POLYGON((120000 435000, 155000 435000, 155000 470000, 120000 470000, 120000 435000))</SrcRegion>
        </GeometryField>
    </OGRVRTLayer>
</OGRVRTDataSource>
```

### Versions and provenance

GDAL 3.6, 3.9.3, 3.10.0 self-built from binaries.

**Comment by jratike80** [comment]
The documentation has an example https://github.com/OSGeo/gdal/blob/42ca02ce9397ec3f37dcc46eace97011f1aa0d53/doc/source/drivers/vector/vrt.rst#example-transparent-spatial-filtering 

```
<OGRVRTDataSource>
    <OGRVRTLayer name="source">
        <SrcDataSource>source.shp</SrcDataSource>
        <SrcRegion clip="true">POLYGON((0 40,10 40,10 50,0 50,0 40))</SrcRegion>
    </OGRVRTLayer>
</OGRVRTDataSource>
```

Doesn't it work?

**Comment by tcommandeur** [comment]
Thanks for the quick response! I clipped the geopackage and made a clip region.

Minimal geopackage with sample data:
[bag-light.zip](https://github.com/user-attachments/files/18227518/bag-light.zip)

Tested VRT:
```
<OGRVRTDataSource>
    <OGRVRTLayer name="pand">
        <SrcDataSource>/srv/datasets/bag-v2/2024-12/bag-light.gpkg</SrcDataSource>
        <SrcLayer>pand</SrcLayer>
        <GeometryField>
            <!-- Clip works only at GeometryField level and not at OGRVRTLayer level -->
            <SrcRegion clip="true">POLYGON((124115 435000, 155000 435000, 155000 470025, 124115 470025, 124115 435000))</SrcRegion>
        </GeometryField>
    </OGRVRTLayer>
    <OGRVRTLayer name="pand_clip_not_working">
        <SrcDataSource>/srv/datasets/bag-v2/2024-12/bag-light.gpkg</SrcDataSource>
        <SrcLayer>pand</SrcLayer>
        <SrcRegion clip="true">POLYGON((124115 435000, 155000 435000, 155000 470025, 124115 470025, 124115 435000))</SrcRegion>
    </OGRVRTLayer>
</OGRVRTDataSource>
```
