### ISSUE TITLE
MITAB label strings encoding

### ISSUE THREAD

**Issue by drons** [OSGeo/gdal#1151]
Due to [RFC5](https://trac.osgeo.org/gdal/wiki/rfc5_unicode) and  [RFC23](https://trac.osgeo.org/gdal/wiki/rfc23_ogr_unicode) GDAL/OGR work with unicode strings internally. But there is no explicit information about LABEL style strings encodings.

MITAB driver store label strings with local encoding, and does not perform any conversions. 
This leads to the impossibility of reading/writing files in different encodings.
I'm think we need to recode [TABText::m_pszString](https://github.com/OSGeo/gdal/blob/2502d5d62e3dad6a384b3c9cb1ef710e1d95d844/gdal/ogr/ogrsf_frmts/mitab/mitab.h#L1560) on read/ write operations and store in UTF-8 internally.

I can made PR If there is no objections.

PS. Apparently this affects other OGR drivers.

**Comment by rouault** [comment]
I agree encoding/decoding from/into UTF-8 would be appropriate

**Comment by drons** [comment]
OK. I will made PR soon.

**Comment by drons** [comment]
WIP: I'll add a test later.
