### ISSUE TITLE
The optios paraThe optios parameter of the Warp function cannot take effectmeter of the Warp function cannot take effect

### ISSUE THREAD

**Issue by Phoenix11-cell** [OSGeo/gdal#11529]
### What is the bug?

When I used warp to embed a large number of images, I tried to save space by using options COMPRESS and TILED, but neither worked. I repeated this many times, I thought it was a bug, I did it under windows, using Python, GDAL version 3.2.3
![image](https://github.com/user-attachments/assets/5b6f0c36-0ef9-40b4-aee8-dacf2ebf28f2)

### Steps to reproduce the issue

```Python
import rasterio as rio
folder = folders[1]
tif_files = glob(folder + r"\*.tif")
output_file = os.path.join("CanopyHeight",os.path.basename(folder)+"2.tif")
gdal.Warp(output_file, tif_files, format="GTiff",options=["TILED=YES", "COMPRESS=LZW"])
```

### Versions and provenance

os:Windows11
Python version:3.8.18
GDAL:3.2.3

**Comment by jratike80** [comment]
The Python code in the autotest suite  https://github.com/OSGeo/gdal/blob/e7b6c09d3b0de5886d9af9c4d0afb4eddafb0ef1/autotest/alg/warp.py#L1766 is using this syntax

```
 out_ds = gdal.Warp(
            "", src_ds, options="-of MEM -ts 1 1 -r average -wo EXCLUDED_VALUES=30,31"
        )

```
This issue tracker is for reporting bugs. Questions and requests about how to use GDAL correctly should be sent to other forums like gdal-dev mailint list, or to gis.stackexchange.com.

As a hint, it might be better to create first a virtual mosaic, for example with gdalbuildvrt utility, and warp the VRT into final tiff.  Adding files one by one with gdalwarp into a compressed target file may yield an unnecessarily large file.
