### ISSUE TITLE
`gdal_ls --version` exits with code 255 on success

### ISSUE THREAD

**Issue by ar-siddiqui** [OSGeo/gdal#11550]
### What is the bug?

When running `gdal_ls --version`, the tool prints a valid version string but exits with a code of 255 instead of 0. This non-zero exit code suggests an error occurred even though the command appears to run successfully.

### Steps to reproduce the issue

Run 
```sh
gdal_ls --version
echo $?
```
Observe that the command prints the expected version output but exits with code 255.

### Versions and provenance

Tested on GDAL 3.6.2 on Ubuntu 22.04 and 3.9.2 on Windows 10

### Additional context

Other GDAL commands like gdalwarp, gdal_merge exits with status 0 after printing valid version string.

**Comment by jratike80** [comment]
What is `gdal_ls`?

**Comment by rouault** [comment]
> What is `gdal_ls`?

this: https://github.com/OSGeo/gdal/blob/master/swig/python/gdal-utils/osgeo_utils/samples/gdal_ls.py#L6  . A non promoted script
