### ISSUE TITLE
ogr2ogr -f "Elasticsearch" fails for Elasticsearch 6

### ISSUE THREAD

**Issue by osvalban** [OSGeo/gdal#1162]
## Expected behavior and actual behavior.

I'd like to index shapefile data to Elasticsearch 6.X. Using ogr2ogr -f "Elasticsearch" to transform .shp with Elasticsearch host 6.5.0 fails.

## Steps to reproduce the problem.

ogr2ogr -f ElasticSearch http://localhost:9200/ gadm36_USA_1.shp
ERROR 1: HTTP error code : 405
ERROR 1: {"error":"Incorrect HTTP method for uri [//gadm36_usa_1] and method [PUT], allowed: [POST]","status":405}
ERROR 1: Terminating translation prematurely after failed

Instructions from: https://gdal.org/1.11/ogr/drv_elasticsearch.html

Switching to an older Elasticsearch host () the step above passes.

## Operating system

For example: macOS Mojave 10.14, 64-bit

## GDAL version and provenance

GDAL 2.3.1, released 2018/06/22

**Comment by rouault** [comment]
ElasticSearch 6.0 support has been added in the today released GDAL 2.4.0

**Comment by osvalban** [comment]
thanks @rouault. Latest homebrew gdal is at 2.3.2. Hopefully 2.4.0 makes it onto a Mac OS binary soon.
