### ISSUE TITLE
ogr2ogr - "ERROR 1: Unable to find driver `MySQL'."

### ISSUE THREAD

**Issue by osvalban** [OSGeo/gdal#1164]
## Expected behavior and actual behavior.

I'd like to migrate shapefiles to a MySQL database using ogr2ogr.

## Steps to reproduce the problem.

ogr2ogr -f MySQL MYSQL:<db_name>,host=localhost,user=root,port=3306,password=<password> -nln <table_name> <myFile>.shp

The tool replies with the following error:

"ERROR 1: Unable to find driver `MySQL'."

## Operating system

macOS Mojave (10.14)

## GDAL version and provenance

GDAL 2.3.2, released 2018/09/21 via homebrew

**Comment by rouault** [comment]
This is an issue with the binary build you use that has not been built against MySQL

**Comment by osvalban** [comment]
@rouault  ok, there is no mention of this in: https://www.gdal.org/drv_mysql.html.

Are there any step-by-step instructions to build from source for Mac OS X, with MySQL support?

**Comment by osvalban** [comment]
figured it out.

**Comment by danaras** [comment]
@osvalban I have the same issue. Do you mind explaining how you figured it out?
