### ISSUE TITLE
Any plans to make LWGEOM available for OGR tools on Windows?

### ISSUE THREAD

**Issue by WindingWinter** [OSGeo/gdal#1167]
Currently I can't use `ogr2ogr` to perform `ST_MakeValid` function. [This function is useful to fix the incorrect geometries.](https://www.gaia-gis.it/fossil/libspatialite/wiki?name=liblwgeom-4.0)  

On GIS Stack Exchange [there is such feature request ](https://gis.stackexchange.com/questions/147372/enabling-lwgeom-for-ogr-tools-qgis-2-8) also. Is there any plans to make  LWGEOM available for OGR tools, at least on Windows, with the GDAL.Net binding?

## Operating system

Windows 10

## GDAL version and provenance

GDAL 2.3.1

**Comment by rouault** [comment]
The GDAL project doesn't deliver binaries. This request must be passed to the project / people that creates the binary you use.
