### ISSUE TITLE
Any plans to allow one to write to memory instead of a disk path for ESRI shapefile?

### ISSUE THREAD

**Issue by WindingWinter** [OSGeo/gdal#1168]
I have code such as this, in GDAL.NET:

```
      private Layer ExtractPolygons(Band band)
      {
          var shapeFilePath = "ESRI Shape.shp"; //note that this must be a physical file location
            var ogrDriver = Ogr.GetDriverByName("ESRI Shapefile");
            var dst_ds = ogrDriver.CreateDataSource(shapeFilePath, null);  
            var dst_layer = dst_ds.CreateLayer("polygon", null, wkbGeometryType.wkbCompoundCurve, null); 

            var fieldDef = new FieldDefn("height", FieldType.OFTInteger);
            dst_layer.CreateField(fieldDef, 0);

            var outcome = Gdal.Polygonize(band, null, dst_layer, 0, null, null, null);
           return dst_layer;
       }
```
Note that I need to specify a `shapeFilePath` as a temporary placeholder to store the polygon. 

I look at [the underlying C++ reference](https://gdal.org/1.11/ogr/classOGRSFDriver.html#a4339101b2d0851e788b6bcfd248780f6), and it seems that there is `CreateDataSource` must pass in a file name currently, so this is not merely the limitation of the GDAL.Net wrapper. 

I wonder is it possible to enhance the GDAL, so that one can create such a placeholder in memory, instead of on a physical file disk? GDAL has something like [MEM-- In Memory Raster](https://www.gdal.org/frmt_mem.html), but I don't think we have anything for vector yet.

**Comment by rouault** [comment]
You can use "/vsimem/foo.shp" to generate a in-memory shapefile

**Comment by WindingWinter** [comment]
Thanks, it works.

It turns out that if you specify "/vsimem/ then [GDAL will write to in memory as in memory files](https://www.gdal.org/gdal_virtual_file_systems.html#gdal_virtual_file_systems_vsimem).
