### ISSUE TITLE
`pcs.csv` could not be found in `/usr/share/gdal/2.2`

### ISSUE THREAD

**Issue by jannes-m** [OSGeo/gdal#1171]
## Expected behavior and actual behavior.

I tried to install **rgdal** in R. The installation stopped since `pcs.csv ` could not be found in the expected folder namely `/usr/share/gdal/2.2` and as returned by `gdal-config --datadir`. Instead `pcs.csv` is located in `/usr/share/gdal`. 

## Steps to reproduce the problem.

From the terminal run:
```sh
# open R
R
install.packages("rgdal")
```
which returns following error message (shortened):

```sh
...
checking for gdal-config... /usr/bin/gdal-config
checking gdal-config usability... yes
configure: GDAL: 2.2.3
checking GDAL version >= 1.11.4... yes
checking gdal: linking with --libs only... yes
checking GDAL: /usr/share/gdal/2.2/pcs.csv readable... no
configure: error: pcs.csv not found in GDAL data directory.
ERROR: configuration failed for package ‘rgdal’
...
```
To make the **rgdal** installation work, I created the required folder and copied the required file into it:

```sh
sudo mkdir /usr/share/gdal/2.2
sudo cp /usr/share/gdal/pcs.csv /usr/share/gdal/2.2/pcs.csv
```
Hence, it would be great if you could adjust the hard-coded (?) paths as returned by `gdal-config --datadir`.

## Operating system

For example: Ubuntu 18.04 64 bit

## GDAL version and provenance

the 2.2.3 version as installed by QGIS3 via https://www.qgis.org/ubuntu. In https://qgis.org/ubuntu/dists/bionic/main/binary-amd64/Packages it says, dependencies are gdal-abi-2-2-3 and libgdal20 (>= 1.8.0).

**Comment by rouault** [comment]
This is likely an issue with the patches applied by DebianGIS / UbuntuGIS. That should be reported to them. But apparently they stopped doing this patching in 2.3.0 : https://salsa.debian.org/debian-gis-team/gdal/commit/5d7870aeccaaba3a7cb373b5e12f99127c8298a7
