### ISSUE TITLE
gdal.Warp gives different array size for v2.3 and v2.4

### ISSUE THREAD

**Issue by MarcYin** [OSGeo/gdal#1173]
With the same Sentinel 2 files:

[B02](https://storage.googleapis.com/gcp-public-data-sentinel-2/tiles/31/U/CU/S2B_MSIL1C_20171123T111349_N0206_R137_T31UCU_20171123T130706.SAFE/GRANULE/L1C_T31UCU_A003738_20171123T111347/IMG_DATA/T31UCU_20171123T111349_B02.jp2)

[B12](https://storage.googleapis.com/gcp-public-data-sentinel-2/tiles/31/U/CU/S2B_MSIL1C_20171123T111349_N0206_R137_T31UCU_20171123T130706.SAFE/GRANULE/L1C_T31UCU_A003738_20171123T111347/IMG_DATA/T31UCU_20171123T111349_B12.jp2)

and same GeoJSON:

[aoi](https://github.com/MarcYin/SIAC/blob/master/SIAC/tests/aoi.geojson)

With same code:

```python
import gdal

g  = gdal.Warp('', 'T31UCU_20171123T111349_B02.jp2',  cutlineDSName = 'aoi.geojson', cropToCutline = True, format='MEM', xRes=10, yRes=10, resampleAlg = gdal.GRA_NearestNeighbour)

g1 = gdal.Warp('', 'T31UCU_20171123T111349_B12.jp2',  cutlineDSName = 'aoi.geojson', cropToCutline = True, format='MEM', xRes=10, yRes=10, resampleAlg = gdal.GRA_NearestNeighbour) 

print( g.RasterXSize,  g.RasterYSize)
print(g1.RasterXSize, g1.RasterYSize)

```

The output from gdal 2.3 are the same for those two rasters, but different from 2.4.

I saw there were some changes to GeoJSON driver and also changes in the gdalwarp utilities. But for same geographic region with same spatial resolution, the output raster should have same number of pixels regardless of the origin spatial resolution, so is there anything I can do to make sure those two warped raster arrays to have same number of x and y pixels?

Thank you.

Marc

**Comment by rouault** [comment]
Backported in release/2.4 per https://github.com/OSGeo/gdal/commit/e3d4cef57683ee3e2c0f53e20d922e094bdb4279
