### ISSUE TITLE
Support WKT precision in the API

### ISSUE THREAD

**Issue by abellgithub** [OSGeo/gdal#1174]
## Expected behavior and actual behavior.

It would be nice if conversion from OGR to WKT would support precision in the API.

## Steps to reproduce the problem.

OGR supports the option OGR_WKT_PRECISION to configure the precision of conversion from an OGR object to WKT.  However, the value of this variable is stored in a static variable in the functions that do the actual conversion (assume this is done for efficiency) which makes it impossible to set the precision from the API more than once.  It would be nice if the precision could be provided to OGRMakeWktCoordinate() and OGRMakeWktCoordinateM() to allow API control of the WKT output precision.

## Operating system

Any

**Comment by abellgithub** [comment]
I'm happy to do the work on this if someone confirms that this is reasonable and desired.

**Comment by rouault** [comment]
That sounds reasonable. You'll need to change the prototype of OGRGeometry::exportToWkt() to have a precision argument. Actally I'd suggest instead of adding a new argument to the method to use instead a new GeometryWktOptions structure, in case we want to do further customizations, that will have as members the existing OGRwkbVariant setting and add the new precision

**Comment by abellgithub** [comment]
Is it preferable to modify the current API by changing the arguments of the function(s), or create a new function with a different signature?

**Comment by rouault** [comment]
As far as virtual methods is concerned, we want to change their signature to avoid having too many of them that would need to be implemented in each derived class. But in the OGRGeometry class, we might add a non-virtual method with the current signature that redirects to the virtual method

If you need this functionnality also exposed in the C API, a new function is needed as we try to avoid breaking the C API as much as possible.

**Comment by inquirer5** [comment]
Not sure if there's any traction on this, but would love to see it implemented.
