### ISSUE TITLE
How to do not hide symbols when compiling gdal

### ISSUE THREAD

**Issue by MisterRaindrop** [OSGeo/gdal#1175]
Since I modified the underlying VSIVirtualHandle. A new VSIHandle has been added. But I found in gdb debugging that I can't get into my newly added VSIHandle.
 Gdb reports "**gdb single stepping until exit from function xxx, which has no line number information**".
 I feel that **fvisibility=hidden** causes me to stop debugging.
How to modify the configuration file without symbol hiding. Can let me debug the underlying new VSIHandle.

**Comment by jratike80** [comment]
Gdal-dev mailing list is the right forum for asking questions. This is our bug tracker.

**Comment by rouault** [comment]
normally that doesn't affect debugging. You might just have not compiled with debug symbols enabled. Try --with-debug
