### ISSUE TITLE
gdalwarp on 2.4.0 behaving differently to 2.3.2 re size of output

### ISSUE THREAD

**Issue by rossoe** [OSGeo/gdal#1176]
## Expected behavior and actual behavior.

I expect to be able to run the following commands within QGIS python console:

**Setting CRS:**
`gdalwarp -t_srs EPSG:32631 -of GTiff "E:/Users/rosso/Arma/Terrain Heightmaps/Heightmaps Opentopo/output_srtm.asc" D:/Arma/QGIS/crm1.tif`

**Setting Resolution:**
`gdalwarp -tr 5.0 5.0 -of GTiff "D:/Arma/QGIS/crm1.tif" D:/Arma/QGIS/res1.tif`

**Cutting to shapefile:**
`gdalwarp -of GTiff -cutline E:/Users/rosso/Arma/QGIS/UTM31N/Test23-11-18/shape.shp -crop_to_cutline "D:/Arma/QGIS/res1.tif" D:/Arma/QGIS/cut1.tif`

and get an output tif of exactly 8192 x 8192 size

With GDAL - 2.3.2 (within QGIS 3.4.2) this is the case.

However with GDAL - 2.4.0 (within QGIS 3.4.3) I get an output of **8191 x 8191**

The shapefile feature used to cut the tif is a perfect square 40960 x 40960 so at 5m resolution I expect 8192 x 8192 output

## Steps to reproduce the problem.

Run the exact same commands (above) in both:
GDAL - 2.3.2  (within QGIS 3.4.2)
GDAL - 2.4.0  (within QGIS 3.4.3)

It appears that Extent and Origin are slightly different between the 2 output tif's 
output with GDAL 2.3.2 - [screenshot](https://ibb.co/Bs9zh7H)
output with GDAL 2.4.0 - [screenshot](https://ibb.co/pv0zt0w)

## Operating system

Windows 10

## GDAL version and provenance
Testing between:
GDAL - 2.3.2  (within QGIS 3.4.2)
GDAL - 2.4.0  (within QGIS 3.4.3)

**Comment by rouault** [comment]
Yes, this is in an intented change of -crop_to_cutline in GDAL 2.4.0.
From the NEWS file:
 * gdalwarp: make -crop_to_cutline stick to source pixel boundaries when no raster reprojection is involved, to avoid unnecessary resampling or resolution change

The likely reason for the difference is that the difference between the upper-left corner of your shapefile extent and the upper-left corner of res1.tif are not a multiple of 5m.

**Comment by rossoe** [comment]
Thanks rouault that's interesting - So not related to the size of the polygon feature created in shapefile. 

How do we now mitigate against the change to ensure it clips to exact size expected?

**Comment by rouault** [comment]
You can use -te instead of -crop_to_cutline. But be aware of what is mentionned in the NEWS: if you specify coordinates that are not aligned on the grid of the raster, you'll get sub-pixel displacement (which can be mitigated a bit if you use a non-nearest resampling)

**Comment by rossoe** [comment]
Thanks - tried your suggestion with -te
`gdalwarp -te 174425.81797744788 5600556.828797467 215386.81797744788 5641517.828797467 D:/Arma/QGIS/res1.tif D:/Arma/QGIS/cut4.tif`

sorts the **width** & **height** but now messes with my resolution -
https://ibb.co/Ph4dY8r

is that the sub pixel displacement you were warning about?

**Comment by rouault** [comment]
You can also use -tr to specify the resolution.

> is that the sub pixel displacement you were warning about?

Not really. For example imagine that the upper left corner of your raster is at (100,100) and the pixel size is (1,1). If with -te you specify a upper left corner at (95.5, 95.5), then you'll get a half-pixel shift in the geolocation of your target image w.r.t the source image.

**Comment by rossoe** [comment]
Superb, thanks for your help finally nailed it and combined commands as well:
`gdalwarp -t_srs EPSG:32631 -r cubic -wo SOURCE_EXTRA=1000 -tr 5.0 5.0 -r cubic -of GTiff -te 174425.817977 5600556.828797 215386.817977 5641517.828797 "E:/Users/rosso/Arma/Terrain Heightmaps/Heightmaps Opentopo/output_srtm.asc" D:/Arma/QGIS/converted7.tif`
