### ISSUE TITLE
gdal.Open returne output none 

### ISSUE THREAD

**Issue by majdo19** [OSGeo/gdal#1177]
hi, 

i need to open my file raster i use gdal in python spyder 
the problèm is when i do print( output) is none 

i don't know what i can do 

this is my script 
```
import os
import glob
from osgeo import gdal
from osgeo.gdalconst import *
import numpy as np
import matplotlib.pyplot as plt
import scipy.ndimage
import pandas as pd
import datetime as dt

#repertoire de travail 

inDir = 'C:/Doy2000/'
os.chdir(inDir)  
#repertoir sorti 
                                                             
outDir = os.path.normpath(os.path.split(inDir)[0] + os.sep + 'output') + '\\' 
if not os.path.exists(outDir): os.makedirs(outDir)
# Create list of MODIS rasters for surface reflectance
modis_EVI = glob.glob(os.path.join(inDir, 'MOD13Q1.006__250m_16_days_EVI_*.tif'))

EVI = gdal.Open(modis_EVI[0])
print(EVI)
```
```
print(EVI)
None
```
any solution .?

**Comment by rouault** [comment]
can the gdalinfo utility open the file you are trying to open with gdal.Open() ?

**Comment by majdo19** [comment]
i don't know how i can do it 

`gdalinfo EVI`

it like that ?

**Comment by rouault** [comment]
> it like that ?

Yes, "gdalinfo c:/path/to/the_tif_file.tif"

**Comment by majdo19** [comment]
```
```
"gdalinfo C:/Doy2000/MOD13Q1.006__250m_16_days_EVI_*.tif"
Out[29]: 'gdalinfo C:/Doy2000/MOD13Q1.006__250m_16_days_EVI_*.tif'
```

**Comment by rouault** [comment]
Your above output doesn't help... Please run this in a cmd shell

**Comment by majdo19** [comment]
i working in Python spyder 

in cmd 
`C:\Users\majdoulina>gdalinfo "C:/Doy2000/MOD13Q1.006__250m_16_days_EVI_*.tif"
ERROR 4: `C:/Doy2000/MOD13Q1.006__250m_16_days_EVI_*.tif' does not exist in the file system, and is not recognized as a supported dataset name.
gdalinfo failed - unable to open 'C:/Doy2000/MOD13Q1.006__250m_16_days_EVI_*.tif'.`

**Comment by rouault** [comment]
Is it really a filename that exists ? It looks like there should be something after the _EVI_ part since you do a glob.glob(os.path.join(inDir, 'MOD13Q1.006__250m_16_days_EVI_*.tif')) search in your code

**Comment by majdo19** [comment]
yes is exists i have a list files : 
```

 print(modis_EVI)
['C:/Doy2000\\MOD13Q1.006__250m_16_days_EVI_doy2000225_aid0001.tif', 'C:/Doy2000\\MOD13Q1.006__250m_16_days_EVI_doy2000241_aid0001.tif', 'C:/Doy2000\\MOD13Q1.006__250m_16_days_EVI_doy2000257_aid0001.tif', 'C:/Doy2000\\MOD13Q1.006__250m_16_days_EVI_doy2000273_aid0001.tif', 'C:/Doy2000\\MOD13Q1.006__250m_16_days_EVI_doy2000289_aid0001.tif', 'C:/Doy2000\\MOD13Q1.006__250m_16_days_EVI_doy2000305_aid0001.tif', 'C:/Doy2000\\MOD13Q1.006__250m_16_days_EVI_doy2000321_aid0001.tif', 'C:/Doy2000\\MOD13Q1.006__250m_16_days_EVI_doy2000337_aid0001.tif', 'C:/Doy2000\\MOD13Q1.006__250m_16_days_EVI_doy2000353_aid0001.tif']
```

**Comment by majdo19** [comment]
![rrrlkk](https://user-images.githubusercontent.com/46379775/50704507-e57ec380-1057-11e9-9bb2-373ae660d0b7.PNG)

**Comment by rouault** [comment]
yes, but you need to pass one of those filenames. A glob will not work in gdalinfo.
It looks more and more like you just misuse GDAL and there's no bug in GDAL itself. Closing this as a not a GDAL bug

**Comment by majdo19** [comment]
`(base) C:\Users\majdoulina>gdalinfo "C:/Doy2000/MOD13Q1.006__250m_16_days_EVI_doy2000225_aid0001.tif"
ERROR 4: This is a BigTIFF file.  BigTIFF is not supported by this version of GDAL and libtiff.
ERROR 4: This is a BigTIFF file.  BigTIFF is not supported by this version of GDAL and libtiff.
gdalinfo failed - unable to open 'C:/Doy2000/MOD13Q1.006__250m_16_days_EVI_doy2000225_aid0001.tif'.`

**Comment by rouault** [comment]
Ah that's interesting. No idea about anaconda, but indeed you need to upgrade to have a built against libtiff 4.x
