### ISSUE TITLE
Regenerate python bindings 

### ISSUE THREAD

**Issue by kbhalerao** [OSGeo/gdal#1178]
## Expected behavior and actual behavior.
I believe the swig-generated python bindings for GDAL 2.3.2 are a bit stale. 
on Python 3.6.5, with source-installed GDAL, 

`from osgeo import gdal ## works`
`from osgeo import gdal_array ## fails with ModuleError in numpy.core.multiarray`

## Steps to reproduce the problem.

install gdal 2.3.2 from source with the --without-python option
`pip install pygdal==2.3.2.4`
In python 3.6.5
`from osgeo import gdal_array`

## Operating system

Amazon Linux 2.7.7 with Python 3.6 (Elastic beanstalk standard AMI)

## GDAL version and provenance

The 2.3.2 version from download.osgeo.org/gdal/2.3.2/gdal-2.3.2.tar.gz

## Solution that appears to work 
in the gdal source folder, 
`yum install swig`
`cd swig/python`
`make veryclean && make generate`
`python setup.py build`
`python setup.py install`

**Comment by rouault** [comment]
pygdal is not maintained by the GDAL project itself. I'd suggest to contact its author. See https://pypi.org/project/pygdal/
