### ISSUE TITLE
ogr2ogr drops projection within MapInfo tab file

### ISSUE THREAD

**Issue by mgzon** [OSGeo/gdal#1183]
Hi,

I'm having trouble creating tab files with the correct srs.

I'm exporting information from an MS SQL Server into a TAB file. Unfortunately the projection is lost and I think this is the reason for the lines not being in their right position.

The command I issue is 
ogr2ogr -f "MapInfo File" mapcableline7.tab "MSSQL:server=servername;database=dbname;tables=tblname(Shape);trusted_connection=yes;GeometryFormat=wkb" -sql "SELECT OBJECTID, SHAPE.STAsBinary() from [dbname].[tblname]" -a_srs "EPSG:3008"

Then I issue the command:  ogrinfo -al -so mapcableline7.tab

The result: 
Layer name: mapcableline7
Geometry: Line String
Feature Count: 30902
Extent: (85489.440000, 6463014.680000) - (170481.690000, 6509417.060000)
Layer SRS WKT:
PROJCS["unnamed",
    GEOGCS["unnamed",
        DATUM["GRS_80",
            SPHEROID["GRS 80",6378137,298.257222101],
            TOWGS84[0,0,0,0,0,0,0]],
        PRIMEM["Greenwich",0],
        UNIT["degree",0.0174532925199433]],
    PROJECTION["Transverse_Mercator"],
    PARAMETER["latitude_of_origin",0],
    PARAMETER["central_meridian",13.5],
    PARAMETER["scale_factor",1],
    PARAMETER["false_easting",150000],
    PARAMETER["false_northing",0],
    UNIT["Meter",1.0]]
OBJECTID: Integer (10.0)

As you can see this is not the expected result since EPSG:3008 is lost.

If I instead create a shape file and run: ogrinfo -al -so mapcableline7.shp

I get:
Layer name: mapcableline7
Metadata:
  DBF_DATE_LAST_UPDATE=2019-01-08
Geometry: Line String
Feature Count: 30904
Extent: (85489.430000, 6463014.680000) - (170481.680000, 6509417.061000)
Layer SRS WKT:
PROJCS["SWEREF99 13 30",
    GEOGCS["SWEREF99",
        DATUM["SWEREF99",
            SPHEROID["GRS 1980",6378137,298.257222101,
                AUTHORITY["EPSG","7019"]],
            TOWGS84[0,0,0,0,0,0,0],
            AUTHORITY["EPSG","6619"]],
        PRIMEM["Greenwich",0,
            AUTHORITY["EPSG","8901"]],
        UNIT["degree",0.0174532925199433,
            AUTHORITY["EPSG","9122"]],
        AUTHORITY["EPSG","4619"]],
    PROJECTION["Transverse_Mercator"],
    PARAMETER["latitude_of_origin",0],
    PARAMETER["central_meridian",13.5],
    PARAMETER["scale_factor",1],
    PARAMETER["false_easting",150000],
    PARAMETER["false_northing",0],
    UNIT["metre",1,
        AUTHORITY["EPSG","9001"]],
    AUTHORITY["EPSG","3008"]]
OBJECTID: Integer64 (10.0)

I've also tried to convert the shape file to a tab file with ogr2ogr with the same result.

So, what could be the reason for the missing information within my tab file.

I’m running this on Windows and I’ve tested both the binaries from GISInternal (release-1911-x64-gdal-2-3-3-mapserver-7-2-1) and the 2.4 version from OSGeo4W. Both versions gives me that same result.

Regards
Mattias

**Comment by mgzon** [comment]
So, if i can't set the EPSG code what could be the reason for my lines not being in the correct position.

Below is a screenshot from mapinfo, the yellow line is the shapefile and the blue line is the tab file.
The yellow line is the correct position. The difference can be up to an inch or so.

When i open the shapefile in mapinfo it actually converts it to a tab file so mapinfo is able to create the tab file correctly.

Based on that i suspected that the lack of EPSG info in the tab file was causing my real issue.

![image](https://user-images.githubusercontent.com/46489410/50837167-47db0b00-135b-11e9-803d-dccaa16a2376.png)

**Comment by rouault** [comment]
What could be helpful is if you attach the original shape and the .tab/.dat/.id/.map created by mapinfo

**Comment by mgzon** [comment]
Ok, in the compressed zip file i've included four directories
- shpFromOgr, shape file created from MS SQL Server using ogr2ogr 
- tabFromOgr, tab file created from MS SQL Server using ogr2ogr
- tabFromShp, tab file created from above shape file using MapInfo Pro v12.5.5. It turned out that this tab file is pointing to the shape file
- tabFromMI, new tab file created in MapInfo. The single line was copied from content in the shape file.

It is the file in tabFromOgr that i'm having trouble with.

[tabFromShp.zip](https://github.com/OSGeo/gdal/files/2737452/tabFromShp.zip)

**Comment by mgzon** [comment]
I believe i found the problem. I had to add 
-lco "BOUNDS=62000.0,6130000.0,217000.0,6908000.0"
while running ogr2ogr to export the SQL database to a Tab file.

Anyway, thanks for your support.
