### ISSUE TITLE
Alpha value in color tables changed on write

### ISSUE THREAD

**Issue by ChristofKaufmann** [OSGeo/gdal#1190]
## Expected behavior and actual behavior

I used color tables and made a few tests with it. They can be added to datasets, but when writing a dataset with a color table to a file, the color table is not written as specified. The alpha values get changed. I tested with GTiff and PNG. The example below creates a 5x1 test dataset with nodata value set to 3 and with the color table

idx |  R  |  G  |   B  |  A
--- | --- | --- | ---- | ---
 0  |  0  |  0  |   0  |   0
 1  |  1  |  2  |   3  |   4
 2  |  2  |  4  |   6  |   8
 3  |  3  |  6  |   9  |  12
 4  |  4  |  8  |  12  |  16

When writing the dataset with GTiff it results in a color table with 256 entries:

idx |  R  |  G  |   B  |    A
--- | --- | --- | ---- | -------
 0  |  0  |  0  |   0  | **255**
 1  |  1  |  2  |   3  | **255**
 2  |  2  |  4  |   6  | **255**
 3  |  3  |  6  |   9  |   **0**
 4  |  4  |  8  |  12  | **255**
 5  |  0  |  0  |   0  | **255**
... | ... | ... |  ... |   ...
255 |  0  |  0  |   0  | **255**

So the alpha values have been changed to 255 except for the nodata entry for which it has been changed to 0.

When writing the dataset with PNG it results in a color table where only the alpha value of the nodata entry has been changed to 0:

idx |  R  |  G  |   B  |   A
--- | --- | --- | ---- | -----
 0  |  0  |  0  |   0  |   0
 1  |  1  |  2  |   3  |   4
 2  |  2  |  4  |   6  |   8
 3  |  3  |  6  |   9  | **0**
 4  |  4  |  8  |  12  |  16

Now, for me this seems to be a bug, since there appears to be no possibility to prevent the drivers from changing the values. Could you please say, whether this behavior is expected or an issue?

## Steps to reproduce the problem

Download test-script.py:
```python
#!/usr/bin/env python3

# create simple 5x1 test image
import numpy as np
raster = np.array([[0, 1, 2, 3, 4]], dtype=np.uint8)

from osgeo import gdal
print(gdal.__version__)

# create simple color table:
ct = gdal.ColorTable()
for i in range(5):
    ct.SetColorEntry(i, (i, 2*i, 3*i, 4*i))

# write test image with color table with GTiff
driver = gdal.GetDriverByName("GTiff")
ds = driver.Create("test.tif",
                   xsize=raster.shape[1], ysize=raster.shape[0],
                   bands=1, eType=gdal.GDT_Byte)
band = ds.GetRasterBand(1)
band.SetColorTable(ct)
band.SetNoDataValue(3)
band.WriteArray(raster)
ds = None

# write test image with color table with PNG
driver = gdal.GetDriverByName("PNG")
src = gdal.Open("test.tif")
band = src.GetRasterBand(1)
band.SetColorTable(ct)
ds = driver.CreateCopy("test.png", src)
ds = None
src = None
```

Then execute in a terminal:
```bash
python3 test-script.py
gdalinfo test.tif
gdalinfo test.png
```

## Operating system

Ubuntu 18.04.01 64 bit

## GDAL version and provenance

Tested with GDAL version 2.2.3 from Ubuntu 18.04.01 and with current git version 2.5.0dev-dfe030c641

**Comment by rouault** [comment]
Yes, this is expected. the TIFF format only stores R,G,B in color tables whereas PNG stores R,G,B,A.   On reading, GDAL force the alpha to 0 for the nodata entry

**Comment by ChristofKaufmann** [comment]
And is this also the desired behavior for TIFF, because it is defined by the standard or so, or would it be an enhancement if it behaved like PNG?

Maybe this could be documented in the driver page of GeoTiff in a short way, similarly as you just stated.

**Comment by rouault** [comment]
This is a limitation of the format itself. Just added a note in the doc per ec0d157
