### ISSUE TITLE
Add an OSRSetPROJSearchPaths function

### ISSUE THREAD

**Issue by sgillies** [OSGeo/gdal#1191]
Such as

```
void CPL_DLL OSRSetPROJSearchPaths( const char* const* papszPaths );
```

As discussed in https://lists.osgeo.org/pipermail/gdal-dev/2019-January/049570.html, this will prevent the need for callers to race GDAL to PROJ's default context, and will allow the search paths to be modified at any time that suits the caller.

**Comment by gbburkhardt** [comment]
I'd very much like to see this exposed through the Java and other interfaces.  In particular, Java doesn't let one set an environment variable programmatically without a hack.  Thanks.

**Comment by rouault** [comment]
> I'd very much like to see this exposed through the Java and other interfaces. In particular, Java doesn't let one set an environment variable programmatically without a hack. Thanks.

Was added a few days ago in master per https://github.com/OSGeo/gdal/pull/1658 and backported to 3.0 branch

**Comment by gbburkhardt** [comment]
You're ahead of the game, as usual.  Thanks.
