### ISSUE TITLE
how can i do times series EVI modis using gdal python 

### ISSUE THREAD

**Issue by majdo19** [OSGeo/gdal#1192]
hi ; 

i have 10 modis tifs in years and i need to plot the mean of EVI in some area inside my shapfile 
  i'm using gdal in python 3 ( spyder) 

i don't know how i can calcul the mean in the area inside the shapfile ( rastersiez, mask, calcul stati for mean ) 

need some help or explication to working or exemple 

all i doing is read all tifs of MODIS EVI , but i need to stack them first and clip with my mask and calcul mean of EVI inside my polygons 
?
any help i'm verry new in gdal python and timeseries 

this is my script 

```
# Import libraries
import os
import glob
from osgeo import gdal
import numpy as np
import matplotlib.pyplot as plt
import scipy.ndimage
import pandas as pd
import datetime as dt

#repertoire de travail 

inDir = 'D:/Rteledetection/Pivots/MODIS/Doy2000/'
os.chdir(inDir)  
#repertoir sorti 
                                                             
outDir = os.path.normpath(os.path.split(inDir)[0] + os.sep + 'output') + '\\' 
if not os.path.exists(outDir): os.makedirs(outDir)
# Create list of MODIS rasters for surface reflectance
modis_EVI = glob.glob(os.path.join(inDir, 'MOD13Q1.006__250m_16_days_EVI_doy*.tif'))

evi = gdal.Open(modis_EVI[1])
bandevi = evi.GetRasterBand(1)

EVIData = bandevi.ReadAsArray().astype('float')
# File Metadata
EVI_meta = evi.GetMetadata()
geotransform = evi.GetGeoTransform()
proj= evi.GetProjection()

# Set matplotlib plots inline
plt.imshow(EVIData)

```
plt.imshow(EVIData)
Out[9]: <matplotlib.image.AxesImage at 0x21638ec7a58>
￼
when i plot EVIDATA i can show just 1 one how i can plot all bande 

thank you

**Comment by majdo19** [comment]
![f](https://user-images.githubusercontent.com/46379775/50925428-93bcab80-1452-11e9-9335-ddd04f7007a5.PNG)

**Comment by rouault** [comment]
As indicated in the issue template, github issues are for proven issues, not question on how to use GDAL
