### ISSUE TITLE
how to access a shapefile on the internet

### ISSUE THREAD

**Issue by wise101** [OSGeo/gdal#1196]
## Expected behavior and actual behavior.

i compile gdal 2.3.1（Integrate curl 7.63 and openssl-1.0.1t） and run app ogrinfo as follow:

ogrinfo -ro -al -so /vsicurl/https://raw.githubusercontent.com/OSGeo/gdal/master/autotest/ogr/data/poly.shp

but open failed:
![image](https://user-images.githubusercontent.com/20125709/51022554-840ea580-15bf-11e9-9bd8-5e90509dec8c.png)

    https://raw.githubusercontent.com/OSGeo/gdal/master/autotest/ogr/data/poly.shp is really existed.

## Operating system

win7 sp1 64 bit

## GDAL version and provenance

the 2.3.1 version from win7 sp1 64 bit

**Comment by rouault** [comment]
Works for me on Linux. Perhaps an issue with accessing SSL certificates. Try adding ```--config GDAL_HTTP_UNSAFESSL YES``` . If that works you may retry without but define the CURL_CA_BUNDLE env variable to point to the bundle.crt file. See https://curl.haxx.se/docs/sslcerts.html

**Comment by wise101** [comment]
> bundle.crt file

         thank you for your reply.so how to get the CA cert file of microsoft Azure ?

**Comment by jratike80** [comment]
Works for me with the Windows binaries from gisinternals.com but fails with OSGeo4W.  The latter shows this info when run with "--debug on"

```
HTTP: libcurl/7.60.0 OpenSSL/1.0.2j zlib/1.2.8 WinIDN
VSICURL: GetFileSize(https://raw.githubusercontent.com/OSGeo/gdal/master/autotes
t/ogr/data/poly.shp)=0  response_code=0
VSICURL: GetFileList(/vsicurl/https://raw.githubusercontent.com/OSGeo/gdal/maste
r/autotest/ogr/data)
FAILURE:
Unable to open datasource `/vsicurl/https://raw.githubusercontent.com/OSGeo/gdal
/master/autotest/ogr/data/poly.shp' with the following drivers.
  -> JP2ECW
  -> OCI
  -> SOSI
  -> PCIDSK
  -> netCDF
  -> JP2OpenJPEG
  -> PDF
  -> MBTiles
  -> DB2ODBC
  -> ESRI Shapefile
  -> MapInfo File
...
```
