### ISSUE TITLE
gdalwrap transformation 4326 to 3857 issue

### ISSUE THREAD

**Issue by karigarweb** [OSGeo/gdal#1197]
## Expected behavior and actual behavior.

So everything was working great with this simple gdalwrap command for us:
`gdalwarp -s_srs EPSG:4326 -t_srs EPSG:3857 ./storage/tifs/1-28.tif ./storage/tifs/1-28-3857.tif`

but all of a sudden the output tiff got some duplicate image inside the view.

## Steps to reproduce the problem.

For example (please modify !!!): "gdalinfo myfile"

## Operating system
Ubuntu 16.04.2 64 bit

## GDAL version and provenance
GDAL 2.2.2, released 2017/09/15

Source File: http://d1.gotoproject.net/testfoler/1-28.tif
Output File: http://d1.gotoproject.net/testfoler/1-28-3857.tif

You can see there is image duplicated inside another image. Now this is happening to any input data I am trying to provide.

**Comment by rouault** [comment]
The correct version is the one at the middle. I'm not sure how you got the outer one. Perhaps you tried with a first image that had an incorrect georeferencing, and then did it again with the correct one. gdalwarp doesn't overwrite, but updates by default. So perhaps you just need to add the -overwrite flag

**Comment by rouault** [comment]
No feedback. Closing. reopen if you can provide more details
