### ISSUE TITLE
Add the ability to configure the project using CMake

### ISSUE THREAD

**Issue by swiss-knight** [OSGeo/gdal#1198]
Is the ability to configure & generating the project using CMake planned?

**Comment by miurahr** [comment]
And there is another trial  here https://github.com/miurahr/cmake4gdal

**Comment by mloskot** [comment]
There's no plan to support CMake and ,l numerous attempts have not moved forward too far.

If anyone is interested in contributing (and maintaining!) CMake configuration, it's very welcome to submit PR for review (and perhaps referring to this request or reopening it).
