### ISSUE TITLE
Number of derived datasets in gdalinfo output

### ISSUE THREAD

**Issue by drnextgis** [OSGeo/gdal#1200]
## Expected behavior and actual behavior.

Expected behavior is to have the full list of the derived datasets as presented in example here https://www.gdal.org/frmt_derived.html but at this point gdalinfo show just one of them.

## Steps to reproduce the problem.

```
$ gdalinfo -mdd DERIVED_SUBDATASETS rgb.tif 
Driver: GTiff/GeoTIFF
Files: rgb.tif
Size is 100, 100
...
Origin = (-6574807.424977720715106,-4070118.882129065692425)
Pixel Size = (76.437028285175984,-76.437028285176893)
Metadata:
  AREA_OR_POINT=Area
Metadata (DERIVED_SUBDATASETS):
  DERIVED_SUBDATASET_1_NAME=DERIVED_SUBDATASET:LOGAMPLITUDE:rgb.tif
  DERIVED_SUBDATASET_1_DESC=log10 of amplitude of input bands from rgb.tif
Image Structure Metadata:
  INTERLEAVE=PIXEL
```

## Operating system

Linux Mint 18.3

## GDAL version and provenance

GDAL 2.4.0, released 2018/12/14

**Comment by rouault** [comment]
This is the desired behaviour. Only LOGAMPLITUDE makes sense for non-complex data types.

**Comment by drnextgis** [comment]
Thanks, it makes sense. Why does subdataset indexing start from 1 (DERIVED_SUBDATASET_1) instead of DERIVED_SUBDATASET_0 as in example?

**Comment by rouault** [comment]
> Why does subdataset indexing start from 1 (DERIVED_SUBDATASET_1) instead of DERIVED_SUBDATASET_0 as in example?

example was outdated. Indices started at _1. Doc just updated
