### ISSUE TITLE
Refactor gdal.org to use Sphinx

### ISSUE THREAD

**Issue by hobu** [OSGeo/gdal#1204]
The GDAL.org website workflow is doxygen-based, documentation is inline with code, and much of the useful content is split across the [Trac website](https://trac.osgeo.org/gdal/). This is the same situation as PROJ had before the effort in 2016 to bring it into a single website that was managed by [Sphinx](http://www.sphinx-doc.org/en/master/). 

The [proj4.org](https://proj4.org) Sphinx migration has been very successful. In addition to providing canonical resources for the software, its coordinate systems, and how to use the software, it has attracted its own set of contributors who have been actively managing and participating in the curation of the content. These contributors were not part of the PROJ project before the website effort was made publicly available. A similar refactoring of gdal.org will hopefully have a similar effect, but even if it does not, it could still provide some significant benefits. These include:

* Un-mixing of docs and code (specifically considering driver-specific html pages)
* Alternative representations (PDF, Windows Compiled Help, automated manpage, etc) of generated output
* Better interlinking of GDAL to projects that are leveraging it. Sphinx [supports documentation 
interlinking](http://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html), and many of the downstream GDAL-using projects are also using Sphinx and could leverage this feature.
* Separation of developer-oriented documentation (classical doxygen API stuff) from user- and example-oriented documentation (website is weak on this and much of this exists in trac and in user-generated content on self-hosted websites).
* Automated refresh workflow 
  * borrow PROJ's workflow based on a Travis push to OSGeo/gdal.github.com and publish with GitHub pages
  * publish direct static content to OSGeo server
  * mirror content to https://readthedocs.org/
* Support Markdown content type with https://recommonmark.readthedocs.io/en/latest/index.html 
* Support Doxygen integration with https://exhale.readthedocs.io/en/latest/ and https://breathe.readthedocs.io/en/latest/

This is a project I would plan to make significant contribution to during the [OSGeo Community Sprint in May 2019](https://wiki.osgeo.org/wiki/OSGeo_Community_Sprint_2019), with automation of the infrastructure done by the event so that the grunt work of content curation and porting can be done during the code sprint.

**Comment by hobu** [comment]
https://gdal.dev is now setup as GitHub pages to prototype. It is backed by https://github.com/OSGeo/gdal-docs

**Comment by jmckenna** [comment]
Hi Howard, I want to also assist with the GDAL sphinx docs.  I'll help you with this too.  The more the merrier.

**Comment by mloskot** [comment]
The conversion work has not started yet, hasn't it? And, we are going to get it rolling during the Code Spring, correct?

**Comment by rcoup** [comment]
@hobu any nice way of surfacing the [Python] bindings API docs better? Would be nice to have them as an API alongside the C/C++ ones, and if there's no explicit docs for a particular method/constant/object we could fallback to linking through to the C++ equivalent.

**Comment by hobu** [comment]
>  any nice way of surfacing the [Python] bindings API docs better

That they are missing is an oversight. We will add it to the list. #1554

**Comment by jumpinjackie** [comment]
The old GDAL/OGR driver landing page had a nice table that indicates whether certain drivers were compiled by default (and if not, what libraries were needed to light up support for that driver).

Would it be hard to bring this table across to the sphinx-ified version?

**Comment by rouault** [comment]
> Would it be hard to bring this table across to the sphinx-ified version?

Do you think this must be presented as a table as it used to be ? Or perhaps that should be a "Build requirement" section in each driver page ?

**Comment by mloskot** [comment]
> Or perhaps that should be a "Build requirement" section in each driver page ?

A table is maintenance hassle. Info per driver page should be enough. PDAL solves this very neatly:

![image](https://user-images.githubusercontent.com/80741/59556427-a79ca880-8fc2-11e9-81b6-ed9819138da1.png)

**Comment by jumpinjackie** [comment]
@rouault I liked the table for its 10000ft view of "here's what's compiled by default". As long as the information exists somewhere, that's the important bit I guess, so if @mloskot 's suggestion is easy to carry out, then so be it.
