### ISSUE TITLE
Writing JP2KAK: tiny reads of the source data

### ISSUE THREAD

**Issue by rcoup** [OSGeo/gdal#1206]
## Expected behavior and actual behavior.

Translating from an GTiff sourced from vsis3 and converting to JP2KAK does thousands of 16KB fetches from the source tif. I'd expect it to do approximately the same number of source _reads_ as converting to any other format.

## Steps to reproduce the problem.

* `GDAL_CACHEMAX=128`
* `VSI_CACHE_SIZE=1073741824`
* `VSI_CACHE=TRUE`
* Source GTiff is 156MB; 6400x9600; striped; LZW-compressed

`$ CPL_DEBUG=ON gdal_translate -of JP2KAK -co QUALITY=100 /vsis3/mybucket/my.tif ./my.jp2`

Takes forever (3mins for a 156MB LZW-compressed GTiff). Logging ~10000 "VSICURL: Downloading A-B" messages, where `(B - A) == 16KB`

In comparison, converting to Tiled GTiff+ZSTD takes ~10s and does 22 requests of ~10MB each:

`$ CPL_DEBUG=ON gdal_translate -of GTiff -co TILED=YES -co COMPRESS=ZSTD /vsis3/mybucket/my.tif ./my.tif`

And by setting `GDAL_MAX_RAW_BLOCK_CACHE_SIZE=128000000` and `GDAL_SWATH_SIZE=128000000` writing the tiff takes two requests (no massive time difference). `GDAL_HTTP_MERGE_CONSECUTIVE_RANGES=YES` doesn't have any effect. Applying these settings make no difference to writing the JP2.

Setting `GDAL_FORCE_CACHING=YES` (regardless of the above settings) reduces the JP2 write time to ~22seconds (86 requests of ~2MB each).

I understand why the JP2 driver might use tiny writes, but why would that spill over into tiny reads of the source tiff and somehow avoid all the caching?

## Operating system

Ubuntu 14.04 64 bit

## GDAL version and provenance

2.3.2 + patches

**Comment by rouault** [comment]
From what I can see in https://github.com/OSGeo/gdal/blob/master/gdal/frmts/jp2kak/jp2kakdataset.cpp#L1874 , the JP2KAK driver proceeds to reading by chunks of one line at a time (actually lines of a block, if using tiled JPEG2000, which is the default if creating a file larger than 2048x2048). Whereas translating to GTiff will do reads on much larger chunks, enabling to do larger GET queries.
The JP2KAK driver could likely be enhanced to larger reads.

**Comment by rcoup** [comment]
Shouldn't that get aggregated in the GTiff driver (and/or in the vsi/block caches) to larger reads from source?

**Comment by rouault** [comment]
> Shouldn't that get aggregated in the GTiff driver (and/or in the vsi/block caches) to larger reads from source?

There's a constant tension between responsiveness/low latency and throughput... If the user (here the JP2KAK driver) request one line (or a fraction of a line), maybe it needs just that and reading 2 MB instead of 16 KB wouldn't be great. The GTiff driver can't know it will end up reading the whole file. Hum, saying that, actually the JP2KAK driver could issue a AdviseRead() to the GTiff driver to indicate its intent to read the whole file, but the GTiff driver doesn't implement AdviseRead() for now. Here the difficulty is that the JP2KAK driver will read by 2048x2048 chunks (and one line at a time in each chunk), and AdviseRead() has no way to communicate that to the GTiff driver, so the GTiff driver wouldn't really know the access pattern which would be impractical for efficient caching.

**Comment by rcoup** [comment]
So GDAL_FORCE_CACHING=YES works around this by using a different read approach with larger chunk sizes?

**Comment by rouault** [comment]
> So GDAL_FORCE_CACHING=YES works around this by using a different read approach with larger chunk sizes?

Yes, GDAL_FORCE_CACHING=YES forces the default IRasterIO() implementation to be taken which will issue a IReadBlock() to the GTiff driver. Whereas without GDAL_FORCE_CACHING, GTiffRasterBand::IRasterIO() is taken, and use the vsicurl multi-range request, which doesn't use the vsicurl caching for now (see my yesterday message : https://lists.osgeo.org/pipermail/gdal-dev/2019-January/049596.html). In the case of the JP2KAK driver querying the GTiff driver, it reads at most one block at a time, so the multi-range request is actually a single-range request, hence https://github.com/OSGeo/gdal/commit/06f24b2800eb1ad39d9660995d81d168801d1124 should hopefully make performance in the default case the same as with GDAL_FORCE_CACHING=YES

**Comment by rouault** [comment]
Can you confirm a perf improvement with the fix ?

**Comment by rcoup** [comment]
Seems a lot better 😄 Thanks!

FWIW, it's also reproducible & improved when converting to JPEGs instead of JP2s

Interestingly, both JPEG + JP2KAK seem to take 8x requests (after the copying begins) to spool up to 2MB chunks.

```
$ gdal_translate -of JPEG /vsis3/mybucket/my.tif ~/out.jpg
GNM: GNMRegisterAllInternal
GNM: RegisterGNMFile
GNM: RegisterGNMdatabase
S3: GetFileList(/vsis3/mybucket)
HTTP: libcurl/7.35.0 OpenSSL/1.0.1f zlib/1.2.8 libidn/1.28 librtmp/2.3
S3: Switching to region ap-southeast-2
VSICURL: Downloading 0-49151 (https://mybucket.s3.amazonaws.com/my.tif)...
VSICURL: Got response_code=206
VSICURL: Downloading 65536-114687 (https://mybucket.s3.amazonaws.com/my.tif)...
VSICURL: Got response_code=206
GDAL: GDALOpen(/vsis3/mybucket/my.tif, this=0x1196e20) succeeds as GTiff.
Input file size is 6400, 9600
0VSICURL: Downloading 49152-65535 (https://mybucket.s3.amazonaws.com/my.tif)...
VSICURL: Got response_code=206
GDAL: GDAL_CACHEMAX = 128 MB
VSICURL: Downloading 114688-131071 (https://mybucket.s3.amazonaws.com/my.tif)...
VSICURL: Got response_code=206
VSICURL: Downloading 131072-163839 (https://mybucket.s3.amazonaws.com/my.tif)...
VSICURL: Got response_code=206
VSICURL: Downloading 163840-229375 (https://mybucket.s3.amazonaws.com/my.tif)...
VSICURL: Got response_code=206
VSICURL: Downloading 229376-360447 (https://mybucket.s3.amazonaws.com/my.tif)...
VSICURL: Got response_code=206
VSICURL: Downloading 360448-622591 (https://mybucket.s3.amazonaws.com/my.tif)...
VSICURL: Got response_code=206
VSICURL: Downloading 622592-1146879 (https://mybucket.s3.amazonaws.com/my.tif)...
VSICURL: Got response_code=206
VSICURL: Downloading 1146880-2195455 (https://mybucket.s3.amazonaws.com/my.tif)...
VSICURL: Got response_code=206
VSICURL: Downloading 2195456-4292607 (https://mybucket.s3.amazonaws.com/my.tif)...
VSICURL: Got response_code=206
.VSICURL: Downloading 4292608-6389759 (https://mybucket.s3.amazonaws.com/my.tif)...
VSICURL: Got response_code=206
VSICURL: Downloading 6389760-8486911 (https://mybucket.s3.amazonaws.com/my.tif)...
VSICURL: Got response_code=206
...
VSICURL: Downloading 157384704-159481855 (https://mybucket.s3.amazonaws.com/my.tif)...
VSICURL: Got response_code=206
.VSICURL: Downloading 159481856-161579007 (https://mybucket.s3.amazonaws.com/my.tif)...
VSICURL: Got response_code=206
VSICURL: Downloading 161579008-162581826 (https://mybucket.s3.amazonaws.com/my.tif)...
VSICURL: Got response_code=206
100 - done.
GDAL: GDALClose(/home/vagrant/out.jpg, this=0x423ee10)
GDAL: GDALClose(/vsis3/mybucket/my.tif, this=0x1196e20)
GDAL: In GDALDestroy - unloading GDAL shared library.
```

**Comment by rouault** [comment]
> Interestingly, both JPEG + JP2KAK seem to take 8x requests (after the copying begins) to spool up to 2MB chunks.

yes, there is a heuristics in the vsicurl layer. It starts with a minimun chunk of 16 KB, and when it sees that the requests are consecutive, it double the chunk size until it reaches 2 MB.
