### ISSUE TITLE
Build failure against poppler-0.72

### ISSUE THREAD

**Issue by a17r** [OSGeo/gdal#1207]
The relevant (but easy to fix) change in poppler 0.72 release notes:
* Rename GooString::getCString to GooString::c_str

Downstream patch (against gdal-2.3.1, but still applies to master), needs ifdefs to be upstreamable:

https://gitweb.gentoo.org/repo/gentoo.git/tree/sci-libs/gdal/files/gdal-2.3.1-poppler-0.72.0.patch

**Comment by rouault** [comment]
Interesting in providing this as a pull request, which would also support the older versions currently supported (the trickiest part is to detect the poppler version) ?

**Comment by a17r** [comment]
@rouault: detection is why I did not try to make a backwards-compatible version. shouldn't this be easier using `pkgconfig`?

**Comment by a17r** [comment]
It seems that poppler has had pkgconfig files since 2008 at least, that should be long enough unless there has been some other issue aside from availability.
