### ISSUE TITLE
Build failure against poppler-0.73

### ISSUE THREAD

**Issue by a17r** [OSGeo/gdal#1208]
gdal-2.3.1 was built with patch from https://github.com/OSGeo/gdal/issues/1207 applied, so poppler-0.72 changes were fixed.

Breaking change in poppler-0.73:
* Remove Gulong, Guint, Gushort, Guchar typedefs

``pdfsdk_headers.h:53:10: fatal error: goo/gtypes.h: No such file or directory``

Downstream report including full build.log: https://bugs.gentoo.org/675450

**Comment by a17r** [comment]
Downstream fix: https://gitweb.gentoo.org/repo/gentoo.git/tree/sci-libs/gdal/files/gdal-2.3.1-poppler-0.73.0.patch

**Comment by sebastic** [comment]
Thanks for the notice. We just had the transition to 0.71.0, and we've passes the transition freeze in preparation for the buster release, so it's highly unlikely that poppler will be updated to >= 0.73.0 in the near future.

In the unlikely event that there is no new GDAL release when poppler _is_ updated, I'll cherry-pick those commits.
