### ISSUE TITLE
ogr2ogr DXF output work fine with previous Autocad version but make Autocad 2019 crash 

### ISSUE THREAD

**Issue by hchristol** [OSGeo/gdal#1213]
## Expected behavior and actual behavior.
I was using ogr2ogr for several years to export DXF file. But with Autocad 2019 any DXF that I open make Autocad crash. 
As I open the DWF I get the following error : "FATAL ERROR : Unhandled e0434352h Exception at FC8CBDEDh"

## Steps to reproduce the problem.
Export any data source to a DXF output. Then try to open it with Autocad 2019 : Autocad crashes.
Try to open the same DXF with a previous version of Autocad  (2016 for instance) : it works.

By saving DXF file in Autocad 2016 in 2004 DXF  format (as ogr2ogr is supposed to produce), it can be opened with Autocad 2019. 

## Operating system
Windows 7

## GDAL version and provenance
>ogr2ogr --version
GDAL 2.4.0, released 2018/12/14

**Comment by rouault** [comment]
CC @atlight

**Comment by atlight** [comment]
Unfortunately I only have AutoCAD 2016... There are a significant number of comments on #835 which probably will help solve the problem, but I don't have time to work through the very substantial amount of information offered there.

**Comment by rouault** [comment]
Same issue was raised in https://github.com/OSGeo/gdal/issues/1220 as affecting QGIS ( https://issues.qgis.org/issues/21052 )

**Comment by hchristol** [comment]
Surprisingly a DXF made with an older version of gdal **do NOT make Autocad 2019 crash** : 
Like this one (just a DXF with one point) : 

Generated with gdal 1.12 :
[https://drive.google.com/file/d/1tXsvJBeITdQo0EYxGSV1KoqH68HcwHa2/view?usp=sharing](url)

And this one generated with gdal 2.40 make Autocad 2019 crash :
[https://drive.google.com/file/d/1Y9w_SYoi2VSF1hQ53WVNPpoovDgCVsGt/view?usp=sharing](url)

Those two DXF have been created with the same command :
`ogr2ogr.exe -f DXF "C:/temp/one_point.dxf" C:/temp/one_point.shp one_point`

Here is the shape used for the conversion : 
[https://drive.google.com/file/d/1ZIFbbpmN8sZPrNJdOp8vPxtmGpTG7id4/view?usp=sharing](url)

**Comment by AlisterH** [comment]
Please note
- it is not just AutoCAD 2019 which crashes (e.g. 2017 does too).
- for convenience with the workaround, grab one of the ezdxf examples: https://github.com/mozman/ezdxf/blob/master/examples/copydxf.py

**Comment by rouault** [comment]
Not sure if https://github.com/OSGeo/gdal/pull/2352 might help . @lbartoletti Could you give it a try ?

**Comment by Tarot67** [comment]
I not tested effectively with autocad 2017!. But on Autocad 2016 there are
no problem at all.

The best way us module python ezdxf it's easy and it's works

Le mer. 25 mars 2020 à 18:30, Even Rouault <notifications@github.com> a
écrit :

**Comment by AlisterH** [comment]
> The best way us module python ezdxf it's easy and it's works

???
It would be far better if gdal produced dxf that was compatible with Autocad.

If someone is able to build with that change and convert the shapefile as per https://github.com/OSGeo/gdal/issues/1213#issuecomment-456109750 I can check whether it still crashes Autocad

**Comment by rouault** [comment]
> If someone is able to build with that change and convert the shapefile as per [#1213 (comment)](https://github.com/OSGeo/gdal/issues/1213#issuecomment-456109750) I can check whether it still crashes Autocad

Attached generated_with_fix_2348.dxf generated with "ogr2ogr generated_with_fix_2348.dxf /home/even/Téléchargements/one_point_gdal_1.12.dxf". 
[generated_with_fix_2348.dxf.zip](https://github.com/OSGeo/gdal/files/4383618/generated_with_fix_2348.dxf.zip)

**Comment by AlisterH** [comment]
Autocad 2020 still crashes with "INTERNAL ERROR: !dbspace.cpp@4033: eWrongDatabase"

**Comment by AlisterH** [comment]
Note that the error message is unchanged; it is different to the unhandled exception identified at the top of the thread, but I'm not sure if the difference is because of different dxfs or different autocad versions or what.

**Comment by Tarot67** [comment]
For: Even ROUAULT:

mozmann as create i huge piece of software and support DXF until 2018 DXF
format!.
Perhaps it's good idea to use his code with his permission of autor (The
licence is MIT).

There are a documentation in :
https://github.com/mozman/ezdxf/tree/master/examples

I don't know if the developer of the DXF driver for GDAL could take a look. I
think this module could allow it to rewrite easier. You have to redo the
API is a job. But in the end it will no longer have to deal with the
aspects of Autocad version 10,13,18 DXF file formats.

It's juste a idea!. I use ezdxf module to convert DXF generate by gdal and
i have never has problem at all.

**Comment by atlight** [comment]
Please note, the fix in bc1aa43f1d8a69312a8924e3e074426f4cc41ad6 is not a code change. It only modifies the `header.dxf` and `trailer.dxf` files in the GDAL `data` directory. You should be able to substitute these files in the `data` directory of your local installation, regardless of the GDAL version.

**Comment by Tarot67** [comment]
you have fixed. great! thank you very much.

I try this after covid-19 confining ;.( . Because for the moment i can't
access to Autocad > 2015

Le sam. 28 mars 2020 à 08:06, Alan Thomas <notifications@github.com> a
écrit :

**Comment by AlisterH** [comment]
Thanks for solving this, guys; the fix seems to have made it upstream e.g. to QGIS packages now.
There is another issue which seems like it may be related: when a dxf produced by gdal is opened in AutoCAD, it is impossible to select objects and copy them (copyclip in Autocad terminology).  Autocad says "copy to clipboard failed".  The file can be fixed by running the AutoCAD audit command.
(Googling, all I found on this error was an ezdxf ticket; they seem to have had the same symptom more than once, with different causes: https://github.com/mozman/ezdxf/issues/9)

**Comment by Tarot67** [comment]
Good news!

Thanks!
