### ISSUE TITLE
import gdal clobbering PATH environment variable on Ubuntu

### ISSUE THREAD

**Issue by Thingus** [OSGeo/gdal#1231]
## Problem description

On import, gdal prepends "[env]\\Library\\bin;" to PATH, breaking any subprocesses that depend on that path.

## Steps to reproduce the problem.

    >>> import os
    >>> os.environ["PATH"]
    '/home/john/miniconda3/envs/eoenv/bin:/home/john/miniconda3/bin:....'
    >>> import gdal
    >>> os.environ["PATH"]
    '/home/john/miniconda3/envs/eoenv\\Library\\bin;/home/john/miniconda3/envs/eoenv/bin:/home/john/miniconda3/bin...'
    >>> 

## Operating system

Ubuntu 18.04 64 bit

## GDAL version and provenance
GDAL 2.3.3 version from from conda ( py36hbb2a789_0)
Python 3.6.8

**Comment by rcoup** [comment]
@Thingus I can't find anything that sets PATH in the codebase, either via `os.environ` or `setenv()`/`putenv()`

This is under master (via the Trusty/Linux vagrant dev environment):
```
vagrant@gdal-vagrant:~$ python
Python 2.7.6 (default, Nov 23 2017, 15:49:48)
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.environ['PATH']
'/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games'
>>> import gdal
>>> os.environ['PATH']
'/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games'
>>> gdal.VersionInfo()
'2050000'
```

This is under 2.3.x on another Ubuntu host:
```
$ ipython
Python 2.7.6 (default, Nov 13 2018, 12:45:42)
Type "copyright", "credits" or "license" for more information.

IPython 1.2.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import os

In [2]: os.environ['PATH']
Out[2]: '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin'

In [3]: import gdal

In [4]: os.environ['PATH']
Out[4]: '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin'

In [5]: gdal.VersionInfo()
Out[5]: '2030200'
```

That would suggest it's something anaconda-related?

**Comment by rouault** [comment]
Neither the GDAL library nor the Python bindings of upstream GDAL touch the PATH. Must be something anaconda-related indeed. Should be reported to their bug tracker.

**Comment by ensafi** [comment]
> Neither the GDAL library nor the Python bindings of upstream GDAL touch the PATH. Must be something anaconda-related indeed. Should be reported to their bug tracker.

This is not true.  In the GDAL 2.3.2 Python bindings (using Python 3.6 under Anaconda3) you will find that "osgeo\/\_\_init\_\_.py" starts as follows:

```
# __init__ for osgeo package.

# making the osgeo package version the same as the gdal version:
import os
import sys
if not '%s\Library\bin' % (sys.prefix) in os.environ['PATH']:
    os.environ['PATH'] = r'%s\Library\bin;%s' % (sys.prefix, os.environ['PATH'])
```

Notice that it simply appends "\\Library\\bin;" to the PATH entry matching sys.prefix, without checking to see if the host system is Windows.

**Comment by rouault** [comment]
This is not the content of the official file provided by GDAL: https://github.com/OSGeo/gdal/blob/master/gdal/swig/python/osgeo/__init__.py

**Comment by ensafi** [comment]
Thank you, I see that now, and I have reported it to the Anaconda team. Looks like distribute patched versions of libraries.
