### ISSUE TITLE
Failure to save a deletion to an existing TAB file if it has no geometries (using QGIS)

### ISSUE THREAD

**Issue by RW-gis** [OSGeo/gdal#1232]
## Expected behavior and actual behavior.

Expected: QGIS (using OGR) should allow deletion of a row of data, where data saved in TAB format.
Actual: QGIS reports an error (on behalf of OGR) when attempting to save the change.

Error occurs where data has no geometries. No error if data has associated geometries.

## Steps to reproduce the problem.

Save a table of data with no geometries (e.g. originating from CSV) as TAB. Open TAB data in QGIS. Use QGIS to delete a row of data. Attempt to save this change. This produces an error.

To prove that the issue is the lack of geometry, save the same file as TAB with QGIS, using the setting to force it to be a point layer. New data has a point per row of data. A row of data from this new file can now be deleted (and the change saved) successfully.

## Operating system

Windows 7

## GDAL version and provenance

(Sorry for missing information) Using as an inherent element of QGIS. QGIS 2.18 downloaded using OSGeo4W network installer. Reproduced on QGIS 3.2 also installed using OSGeo4W installer, with different data.

**Comment by jratike80** [comment]
Steps to reproduce without QGIS

Write csv file

```
id,attr
1,a
2,b
```
Convert into .tab

`ogr2ogr -f "MapInfo file" csv.tab csv.csv`

Test with SQL SELECT

`ogrinfo -dialect sqlite -sql "select * from csv where attr='b'" csv.tab`

Success, now try to delete

```
ogrinfo -dialect sqlite -sql "delete from csv where attr='b'" csv.tab
INFO: Open of `csv.tab'
      using driver `MapInfo File' successful.
ERROR 1: In ExecuteSQL(): sqlite3_step(delete from csv where attr='b'):
  SQL logic error or missing database
```
