### ISSUE TITLE
OCI driver is missing OpenOption MULTI_LOAD

### ISSUE THREAD

**Issue by hlaebe** [OSGeo/gdal#1233]
## When appending to a data store it should be possible to set MULTI_LOAD=NO

While appending to an OCI data store, I receive randomly unique key violations. Since MULTI_LOAD defaults to YES and is not an OpenOption, the exception thrown from the data base leads to rejecting of multiple feature depending on the MULTI_LOAD_COUNT (100 default) setting.

You can work around this by specifying -doo MULTI_LOAD_COUNT=1, but it would be clearer to set -doo MULTI_LOAD=NO

## GDAL version and provenance

all versions up to 2.4

**Comment by jratike80** [comment]
I know that OCI driver has some own pecularities, but in theory the -gt option of ogr2ogr should reflect to MULTI_LOAD_COUNT and -skipfailures should trigger MULTI_LOAD=NO. Because you seem to have an environment ready for testing, could you also test what happens with ogr2ogr and add results into your ticket? Create a new ticket if OCI does not respect ogr2ogr -gt and -skipfailures options.

**Comment by hlaebe** [comment]
OCI driver checks only  MULTI_LOAD option , see

ogrocitablelayer.cpp/ICreateFeature line 972 cont.

/* -------------------------------------------------------------------- */
/*      Get the multi load count value from open options                */
/* -------------------------------------------------------------------- */

    this->bMultiLoad = CPLFetchBool( papszOptions, "MULTI_LOAD", true );

    this->nMultiLoadCount = 100;

    if (CSLFetchNameValue( papszOptions, "MULTI_LOAD_COUNT" ) != nullptr)
    {
        this->nMultiLoadCount = atoi( CSLFetchNameValue( papszOptions,
                                                         "MULTI_LOAD_COUNT" ) );
        this->bMultiLoad = true; // overwrites MULTI_LOAD=NO
    }

/* -------------------------------------------------------------------- */
/*      Do the actual creation.                                         */
/* -------------------------------------------------------------------- */
    if( bMultiLoad )
        return BoundCreateFeature( poFeature );
    else
        return UnboundCreateFeature( poFeature );
}


Von: jratike80 <notifications@github.com>
Gesendet: Freitag, 25. Januar 2019 15:45
An: OSGeo/gdal <gdal@noreply.github.com>
Cc: Läbe, Holger <laebe@geomapping.de>; Author <author@noreply.github.com>
Betreff: Re: [OSGeo/gdal] OCI driver is missing OpenOption MULTI_LOAD (#1233)


I know that OCI driver has some own pecularities, but in theory the -gt option of ogr2ogr should reflect to MULTI_LOAD_COUNT and -skipfailures should trigger MULTI_LOAD=NO. Because you seem to have an environment ready for testing, could you also test what happens with ogr2ogr and add results into your ticket? Create a new ticket if OCI does not respect ogr2ogr -gt and -skipfailures options.
