### ISSUE TITLE
How do I open a file in mif/mid format？ and translate to postgresql?

### ISSUE THREAD

**Issue by zhaoyangwyyx** [OSGeo/gdal#1242]
## Expected behavior and actual behavior.

For example (please modify !!!): I expected to be able to open this raster file (with a link to
the raster file, or it as an attachment) and it returns an error message
instead.

## Steps to reproduce the problem.

For example (please modify !!!): "gdalinfo myfile"

## Operating system

For example (please modify !!!): Ubuntu 16.04 64 bit

## GDAL version and provenance

For example (please modify !!!): the 2.2.3 version from ubuntugis-unstable PPA

**Comment by jratike80** [comment]
Please use gdal-dev mailing list for asking questions. This is a bug tracker and this ticket will be closed soon.

Read the documentation of ogr2ogr https://www.gdal.org/ogr2ogr.html, MapInfo and PostgreSQL drivers https://www.gdal.org/drv_mitab.html https://www.gdal.org/drv_pg.html. If you want to do the same with code you can find examples from https://pcjericks.github.io/py-gdalogr-cookbook/.
