### ISSUE TITLE
Compatibility with Elasticsearch 7.0

### ISSUE THREAD

**Issue by nickpeihl** [OSGeo/gdal#1246]
## Expected behavior and actual behavior.

Elasticsearch is [removing mapping types](https://www.elastic.co/guide/en/elasticsearch/reference/current/removal-of-types.html) for indices in the upcoming 7.0 release. The [GDAL Elasticsearch driver](https://www.gdal.org/drv_elasticsearch.html) has a `MAPPING_NAME` layer creation option that sets the index mapping type (`FeatureCollection` by default). So attempts to write to Elasticsearch 7+ will return an error.

Ideally we could just ignore the `MAPPING_NAME` option for Elasticsearch 7+ and not include the `_type` parameter ([ex.](https://github.com/OSGeo/gdal/blob/master/gdal/ogr/ogrsf_frmts/elastic/ogrelasticlayer.cpp#L2273)) in the request. But the `MAPPING_NAME` option also determines the JSON format of the document that is sent to Elasticsearch. If the `MAPPING_NAME` is `FeatureCollection` or left as the default, the document matches the GeoJSON Feature format. If `MAPPING_NAME` is anything else, the `feature.properties` object is flattened in the document.

Can we deprecate the `MAPPING_NAME` layer creation option and introduce a new layer creation option (e.g. `FLATTEN_PROPERTIES`) to specify the JSON format of the documents stored in Elasticsearch? 

I'm happy to open a PR, but I'd like to get input from the contributors first.

## Steps to reproduce the problem.
Using [Elasticsearch v7.0.0-alpha2](https://www.elastic.co/downloads/elasticsearch#preview-release)
`ogr2ogr -progress -lco BULK_SIZE=5000000 -f "ElasticSearch" http://localhost:9200 my_shapefile.shp`

Returns error from Elasticsearch 
```
ERROR 1: HTTP error code : 400
ERROR 1: {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Types cannot be provided in put mapping requests, unless the include_type_name parameter is set to true."}],"type":"illegal_argument_exception","reason":"Types cannot be provided in put mapping requests, unless the include_type_name parameter is set to true."},"status":400}
```

## GDAL version and provenance

GDAL 2.4.0

**Comment by rouault** [comment]
Another thought is I'm not sure of the value of having both the 'raw' and GeoJSON document representations. The GeoJSON was the only one offered by the initial write-only driver. And then when I added read support, I added support for arbitrary documents, and also write/update support for them. And I kept the GeoJSON path. But ultimately we should probably keep just one for the sake of maintenance simplicity and I bet the 'raw' one would be better (since the driver can support multiple geometry fields per document, whereas GeoJSON is limited to one). So I wouldn't personally be opposed in having just support for 'raw' documents in ES >=7. The only downside of this would be for people migrating old data with ES migration tools (assuming there are one), but a workaround would be to use ogr2ogr to do it.
I'm going to mention this to one stakeholder of this driver to see if he has an opinion on this.

**Comment by nickpeihl** [comment]
Thanks @rouault. I'm 👍 on just keeping the 'raw' representation. I look forward to hearing your stakeholder's opinion.

**Comment by rouault** [comment]
We want to preserve existing behaviour and options for ES <= 6
For ES >= 7, having just the 'raw' representation is fine, and MAPPING_NAME being ignored might be fine.
We might want to expose in the dataset metadata the ES server version for user decision.

**Comment by dszanto75** [comment]
Hi everyone,
Although Elasticsearch is eliminating `types` on versions 7+, there will be a single `type` _(and no other)_ named `_doc`.  If the default type name is always `_doc`, I believe things should work just fine according to the documentation.  I can't seem to find just yet where I read it, but as soon as I find it I'll add it here as well.

Hope this helps.

**Comment by dszanto75** [comment]
Hi again,
Here is the spec on how types will be removed on versions 7 and 8:
https://www.elastic.co/guide/en/elasticsearch/reference/master/removal-of-types.html

An idea could be to include `type` in paths, mappings and documents depending on the ES version.  The idea would be to add a simple `GET` query to `http://<server>:<port>` , recover the ES version, and omit types when version is greater or equal to 7.  This would simply render configurations such as MAPPING_NAME useless when using ES 7 or above, but backward compatibility would not be a problem _(i think)_.

I'm not very keen on C++, but I'll take a look at the code and see if I can work something out for this issue, 
I'll let you know if I feel confident enough to code something out myself.

Cheers!

**Comment by SomberOfShadow** [comment]
Hello everyone,

Anyone know how to set "include_type_name" by java rest high client 7.3.1 ?

Thanks a lot1

**Comment by jratike80** [comment]
If you talk about this elastic.co/guide/en/elasticsearch/client/java-rest/current/java-rest-high.html then this is definitely a wrong place.

**Comment by nickpeihl** [comment]
> Hello everyone,
> 
> 
> 
> Anyone know how to set "include_type_name" by java rest high client 7.3.1 ?
> 
> 
> 
> Thanks a lot1

AFAICT, there is no way to specify this parameter with the GDAL Elasticsearch driver. Types do not exist in Elasticsearch starting with 7.0. See https://www.elastic.co/guide/en/elasticsearch/reference/current/removal-of-types.html

**Comment by SomberOfShadow** [comment]
However I found Python API and Restful API to set "include_type_name", see following code snippet.
```
PUT /send-mje-version-size-test4?include_type_name=true
{
  "mappings": {
    "_doc": {          
      "properties": {
        "lastModified": { 
		        "type": "text"		
        },
        "mjeVersion": {   
            "type": "text"
        },
	     	"sizeOnDisk": {   
            "type": "long"
        }
      }
    }
  }
}
```

Python API:
`
es.indices.create(index=indexName, include_type_name=True)
`
or 
`
es.indices.put_mapping(index=indexName, body=mappings,include_type_name=True)
`
But can not find API by Java rest high client to set it.
