### ISSUE TITLE
Can't build GDAL 2.4.0 with Visual Studio 2015 x64

### ISSUE THREAD

**Issue by bottori** [OSGeo/gdal#1251]
Can't build GDAL 2.4.0 using Visual Studio 2015 x64.  I get the following link error after what looks to be a proper compilation.

         H:\Utilities\gdal240\gdal-2.4.0>if exist *.ilk del *.ilk 
         	link /nologo /dll /INCLUDE:OSRValidate  /INCLUDE:OPTGetProjectionMethods  /INCLUDE:OGR_G_GetPointCount  /INCLUDE:OGRRegisterAll /INCLUDE:GDALSimpleImageWarp  /INCLUDE:GDALReprojectImage  /INCLUDE:GDALComputeMedianCutPCT  /INCLUDE:GDALDitherRGB2PCT  /INCLUDE:OCTNewCoordinateTransformation port\*.obj gcore\*.obj alg\*.obj frmts\o\*.obj ogr\ogrsf_frmts\ogrsf_frmts.lib ogr\ogr.lib gnm\*.obj gnm\gnm_frmts\o\*.obj third_party\o\*.obj apps\commonutils.obj apps\gdalinfo_lib.obj apps\gdal_translate_lib.obj apps\gdalwarp_lib.obj apps\ogr2ogr_lib.obj  apps\gdaldem_lib.obj apps\nearblack_lib.obj apps\gdal_grid_lib.obj apps\gdal_rasterize_lib.obj apps\gdalbuildvrt_lib.obj                                      legacy_stdio_definitions.lib odbc32.lib odbccp32.lib user32.lib                           ws2_32.lib  kernel32.lib psapi.lib gcore\Version.res  /out:gdal204.dll /implib:gdal_i.lib   
            Creating library gdal_i.lib and object gdal_i.exp
     1>ogrsf_frmts.lib(ogrregisterall.obj) : error LNK2019: unresolved external symbol RegisterOGRNGW referenced in function OGRRegisterAllInternal
     1>gdal204.dll : fatal error LNK1120: 1 unresolved externals
     1>NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\x86_amd64\link.EXE"' : return code '0x460'
         Stop.
     1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.MakeFile.Targets(46,5): error MSB3073: The command "nmake -f makefile.vc MSVC_VER=1900 WIN64=1 clean && nmake -f makefile.vc MSVC_VER=1900" exited with code 2.
       Done executing task "Exec" -- FAILED.
     1>Done building target "Rebuild" in project "gdal_vs2015.vcxproj" -- FAILED.
     1>Done Building Project "H:\Utilities\gdal240\gdal-2.4.0\gdal_vs2015.vcxproj" (Rebuild target(s)) -- FAILED.

## Expected behavior and actual behavior.

Expect the GDAL build to complete normally with no errors under Visual Studio 2015 x64 release.

## Operating system

Windows 7 x64

## GDAL version and provenance

2.4.0

**Comment by gokhanakcay** [comment]
I got the same linker error with VS 2017 x64.

**Comment by rouault** [comment]
@BishopGIS Does that ring a bell to you ? Are there been a realted fix pushed in the 2.4 branch since 2.4.0 release ?

**Comment by vloppin** [comment]
Sounds to be fix on master with commit 16d6a60

**Comment by rouault** [comment]
OK, I've backported https://github.com/OSGeo/gdal/commit/16d6a60bc8171878a80efa9abcb1aee27ca646a4 . Didn't realize the issue was with builds without curl

**Comment by bottori** [comment]
Is there any progress on this issue?  I don't see a new update in the downloads area.  Is there an update 2.4.1 coming?  Any way I can patch with a new makefile.vc?

**Comment by rouault** [comment]
A 2.4.1 release candidate will be issued this Friday. You can always apply https://github.com/OSGeo/gdal/commit/16d6a60bc8171878a80efa9abcb1aee27ca646a4 locally in the mean time

**Comment by bottori** [comment]
I tried replacing the makefile.vc with the patched version and still get the same error.

I replaced the file makefile.vc in directory gdal-2.4.0\ogr\ogrsf_frmts\generic

**Comment by rouault** [comment]
Weird. Just to be sure can you try with : https://github.com/OSGeo/gdal/archive/release/2.4.zip ? This is the current snapshot of the 2.4 branch that includes the fix ?

**Comment by bottori** [comment]
Ok, I tried one last thing.  I did a clean of the library and then rebuilt and everything worked. ☺

Thanks
