### ISSUE TITLE
gdal_contour always fails with -p

### ISSUE THREAD

**Issue by typebrook** [OSGeo/gdal#1256]
#### Expect
- Use `gdal_contour` to generate contour polygon (with `-p`, which is introduced in 2.4)
#### Actual
- Progress shows `done`, but never ends. Like image below:
![screenshot from 2019-01-31 21-44-50](https://user-images.githubusercontent.com/19887090/52057997-78504680-25a1-11e9-9759-5d084faeabd9.png)
- Temporary files are empty
- Both output format: `ESRI Shapefile` and `GeoJSON` fails.
- Only happens with `-p` for generating polygon

## Steps to reproduce the problem.

Here I use sample GeoTiff file from [Mapbox](https://docs.mapbox.com/help/glossary/tiff/)
```
curl -O https://docs.mapbox.com/help/data/landsat.tif
gdal_contour -i 10 -p landsat.tif output.shp

# Or use docker image, which is also based on Ubuntu 18.04 bionic
docker run -v `pwd`:/data geographica/gdal2:2.4.0 bash -c "\
    gdal_contour -i 10 -p /data/landsat.tif output.shp"
```

## Operating system
Ubuntu 18.04 64 bit

## GDAL version and provenance

GDAL 2.4.0, from `ubuntugis-ubuntu-ppa-bionic`

**Comment by rouault** [comment]
CC @mhugo

**Comment by mhugo** [comment]
Well, the last part of the processing is probably just very slow ... https://github.com/OSGeo/gdal/blob/master/gdal/alg/marching_squares/polygon_ring_appender.h#L139

Contour rings are tested for inclusion with each other to decide which one is a hole and which one is an exterior ring. There should be ways to optimize. At the very least, the progress bar should be updated accordingly.

**Comment by typebrook** [comment]
@mhugo 
Thanks for you reply, it actually works on tiny GeoTIFF or large contour interval.
`-p` option is not quite practical with such a slow speed, hope it would be optimized later.
