### ISSUE TITLE
Add support to fetch all spatial references at once.

### ISSUE THREAD

**Issue by ktheijs** [OSGeo/gdal#1273]
## Expected behavior and actual behavior.

I require a list of all Spatial References that are listed in the EPSG derived support files (pcs.csv, gcs.csv,...). 

At the moment I get this list by reading these support files line by line and then use the EPSG code to get the spatial reference by using SpatialReference.ImportFromEPSG(). This is an extremely inefficient approach as ImportFromEPSG() is very slow. The documentation even states: "This method is relatively expensive, and generally involves quite a bit of text file scanning.  Reasonable efforts should be made to avoid calling it many times for the same coordinate system."

My request is that a new method is developed that gets all the Spatial References from these files at once. This would drastically increase performance as this method could be called once and cached.

## Steps to reproduce the problem.

Nil - not currently implemented.

## Operating system

All

## GDAL version and provenance

Feature request, not currently implemented.

**Comment by kannes** [comment]
This should be a non-issue in modern GDAL based modern ProJ5 as the CSV files were dropped in favour of a SQLite database.

Please test if it works performantly with an uptodate GDAL.

**Comment by ktheijs** [comment]
Thank you for your response.

I tried it on version 2.3.0 and I have now tried it again on version 2.4.0. I get the same result in both versions. It takes a little over 10 seconds to get all the Spatial References. 
I might have to add that I am using the C# bindings. I assume that doesn't have a significant impact. In which version was the SQLite database approach introduced?

**Comment by rouault** [comment]
This is not in a released version yet of GDAL and PROJ, but in their master branches. Actually I'm just adding a function in GDAL for that per https://github.com/OSGeo/gdal/pull/1279

**Comment by kannes** [comment]
You rock, Even!

**Comment by ktheijs** [comment]
Thank you! Perfect timing. 👍
