### ISSUE TITLE
FAILURE: Unknown resampling method: "med".

### ISSUE THREAD

**Issue by urskalbitzer** [OSGeo/gdal#1276]
## Expected behavior and actual behavior.

I am trying to use gdalwarp to decrease the resolution of a large raster file from the global forest change dataset (https://earthenginepartners.appspot.com/science-2013-global-forest).
My plan was to use the median as resampling method, which is listed as an available method at https://www.gdal.org/gdalwarp.html. However, I get the error:

> Available resampling methods:
>   near (default), bilinear, cubic, cubicspline, lanczos, average, mode.
>
> FAILURE: Unknown resampling method: "med".

## Steps to reproduce the problem.
Download https://storage.googleapis.com/earthenginepartners-hansen/GFC-2017-v1.5/Hansen_GFC-2017-v1.5_treecover2000_20N_090E.tif
and then run:
gdalwarp -tr 0.002 0.002 -ot Int16 -r med -of GTiff Hansen_GFC-2017-v1.5_treecover2000_20N_090E.tif Hansen_GFC-2017-v1.5_treecover2000_20N_090E_f8_gdalwarp.tif

## Operating system
macOS 10.14.2

## GDAL version and provenance
GDAL 1.11.5, released 2016/07/01

Thanks a lot for your help!
Urs

**Comment by jratike80** [comment]
This is a bug tracker. The forum to ask questions about how to use GDAL is the gdal-dev mailing list.
About your issue, please read the gdalwarp doc carefully. You say have GDAL 1.11.5 but the doc says that you must have at least 2.0.0.

med:
    median resampling, selects the median value of all non-NODATA contributing pixels. (GDAL >= 2.0.0)

**Comment by urskalbitzer** [comment]
Thanks a lot for this quick answer, and apologies for not checking the documentation carefully enough. I had missed the part on the minimum version number. I've updated GDAL and everything works now.

Urs
