### ISSUE TITLE
Wrong MAX_EPSG value 3768 instead of 32768 in OGR SXF Data Source

### ISSUE THREAD

**Issue by em2er** [OSGeo/gdal#1278]
## Expected behavior and actual behavior.

According to http://gis.stackexchange.com/a/18676/9904  EPSG code range is  (1000 – 32768) but in [ogrsxfdatasource.cpp](https://github.com/OSGeo/gdal/blob/master/gdal/ogr/ogrsf_frmts/sxf/ogrsxfdatasource.cpp) the range is
```c++
constexpr int MIN_EPSG = 1000;
constexpr int MAX_EPSG = 3768; //<--- 32768 EXPECTED
```

**Comment by BishopGIS** [comment]
Yes, this is a typo. Must be **32768**
Never saw SXF with EPSG value set in it, so this case never hit.
