### ISSUE TITLE
[DOCS] PDF_LIB in frmt_pdf not accepted as "open option"

### ISSUE THREAD

**Issue by tobwen** [OSGeo/gdal#1283]
## Expected behavior and actual behavior.
Seems like the "open options" are not implemented now? https://www.gdal.org/frmt_pdf.html

## Steps to reproduce the problem.
```
ogr2ogr output.geojson input.pdf --config OGR_PDF_READ_NON_STRUCTURED YES -oo PDF_LIB=POPPLER
Warning 6: driver PDF does not support open option PDF_LIB
```

## Operating system
Windows 7 Professional, 64-bit

## GDAL version and provenance
- GDAL 2.4.0, released 2018/12/14 from _OSGeo4W_ (2019-02-08)
- GDAL 2.5.0dev, released 2019/99/99 from _OSGeo4W_ (2019-02-08)

**Comment by jratike80** [comment]
Documentation mentions about that open option "PDF_LIB=[POPPLER/PODOFO/PDFIUM]: only available for builds with multiple backends." Do you know if OSGeo4W build is made with multiple PDF backends?

**Comment by tobwen** [comment]
> Do you know if OSGeo4W build is made with multiple PDF backends?

No, how can I find figure it out? I'd love to get a message like `You're using a single backend only` :)

**Comment by rouault** [comment]
`gdalinfo --format PDF` will output at the end things like
`
  Other metadata items:
    HAVE_PODOFO=YES
    HAVE_POPPLER=YES
`

**Comment by tobwen** [comment]
`HAVE_POPPLER=YES`

Okay, I'm gonna build it on my own on Linux and do some more PDF testing.
