### ISSUE TITLE
Optimize multi-range read requests

### ISSUE THREAD

**Issue by tbonfort** [OSGeo/gdal#1295]
This is a placeholder issue for moving the discussion about multi range requests out of #1289

From my understanding, this is the current situation. Please correct if I am wrong:
- For the time being, gtiff is the only driver to support multi-range read request
- When the geotiff driver constructs the offsets and sizes of the different ranges, it does not try to merge consecutive ranges to reduce the total number of requested ranges
- From a http vsi backend point of view, there is no real world use-case where it would be more efficient to emit two GET requests for consecutive ranges rather than merging them into a single one:
  - there will be more data to transmit down the wire (accounting for http headers)
  - there will be more GET requests emitted, which are usually billed by the unit by providers
  - there is no reason the parallel requests will finish faster than the merged one given they share the same network pipe. Theoretically this might be false if the provider purposefully throttles the download speed after the first N bytes, and both range requests are less than N bytes, and the merged consecutive request is larger than N
- By default, the vsicurl driver merges consecutive ranges, but this can be disabled with a config option. This ends up with curl allocating memory for the merged buffers during it's write callback.
- The plugin approach proposed in #1289 unconditionally merges consecutive ranges, and same as with curl with the slight cost of having to allocate buffers for the merged requests.
- Any vsi driver that wishes to implement multi-range requests will probably need to also implement consecutive range merging
- In #1289 @rouault states
  >  In some rare circumstances it might help not to merge consecutive ranges, but this is not a good default

  Could you give more details about these circumstances please?

What could be optimized? :
- Make gtiff (and other future drivers wishing to implement multi range reads) emit merged consecutive requests
- In VSIFReadMultiRangeL change the semantics of "merging consecutive ranges" to "merge close-enough ranges" with "close-enough" being something that could be tweaked by config options (This would imply the overhead of memory allocations). Eg:
  - merge ranges if they are less than N bytes apart from each other
  - merge ranges together if the merged range is less than N bytes
  - merge ranges together if the overhead of the merged size is less than P% of the sum of the two original sizes

  Note that at the cost of some memory allocation, we could remove the constraint of gtiff having to merge consecutive ranges by applying the strategy "merge ranges if they are less than 0 bytes apart from each other"
- (Optional, to reduce duplicate memory allocations) In vsicurl, stop using code to specifically handle range merging, and have the curl write callbacks write directly to the passed-in buffers rather than allocating them itself

**Comment by rouault** [comment]
>     * > In some rare circumstances it might help not to merge consecutive ranges, but this is not a good default
>       
>       
>       Could you give more details about these circumstances please?

Actually I found out my benchmarking results, and it turns out that non-merging strategy never lead to better results as you pointed out. So this was just one variable that was explored during the benchmarking exercice (among testing for HTTP/1.1 pipeling vs HTTP/2.0 multiplexing) and there's no practical point in modifying the default value of this undocumented configuration option.

**Comment by rouault** [comment]
@tbonfort I guess #1297 fixed that issue (or mostly fixed it) ?

**Comment by jratike80** [comment]
Who knows if this issue got fixed or not?
