### ISSUE TITLE
[enhancement] support for SENC from OpenCPN

### ISSUE THREAD

**Issue by free-x** [OSGeo/gdal#1300]
Hi,

OpenCPN (https://github.com/OpenCPN/OpenCPN ) converts for internal use S-57 to "SENC". Converting functions are available ( https://github.com/OpenCPN/OpenCPN/blob/d801b64869af1fd1e554d55685fa36bbe0c81e93/src/Osenc.cpp#L1452 ). is the possible ogr to extend that also SENC to process?

Example with S-57 and resulting SENC I have attached

Regards
free-x
[SENC.zip](https://github.com/OSGeo/gdal/files/2884746/SENC.zip)

**Comment by rouault** [comment]
If this "SENC" format is for OpenCPN internal use, I'm not sure what would be the value to add support for it in GDAL.

**Comment by free-x** [comment]
hi @rouault ,
I don't think I put it right. SENC is a container just like S-57. Basically it contains only already prepared S-52. I found something like this on the internet 
1. https://www.hydro-international.com/content/article/s-101-the-new-iho-electronic-navigational-chart-product-specification

> Production System Attributes

Currently, an S-57 based ECDIS has to spend considerable time during loading to identify the relationships between the geometries of certain features e.g. a wreck and its surrounding depth area. This is done in order for the System ENC (SENC) to pre-determine the appropriate display criteria so that the system can execute the S-52 Conditional Symbology Procedures (CSP) correctly. In order to reduce the need to call up these complex procedures that need to be calculated by the ECDIS at any change of the presentation, the ENC production systems will pre-calculate the values describing this relationship; store them as an attribute of the feature and export it as part of the S-101 dataset. This will increase the efficiency of creating the SENC, reduce the need for a significant number of CSPs and contribute to a faster and simpler loading process.

It's not really "internal" format. I don't know any other SENC available at the moment but maybe in the future there will be more in circulation.

greetings
free-x

**Comment by rouault** [comment]
Is the OpenCPN 'SENC' format the same as S-101 ? That's not clear at all to me. Are you connected with the OpenCPN developers that have developped this SENC format support so they can share some light on this ?

**Comment by rouault** [comment]
@free-x ping w.r.t my above question

**Comment by free-x** [comment]
@rouault ping back
Unfortunately, I still have your questions answered. I can only say that SENC is not S-101. I have not made contact with [@bdbcat](https://github.com/bdbcat).  I try my best. I don't know if he's interested in answering those questions :-(

**Comment by rouault** [comment]
Closing due to lack of feedback
