### ISSUE TITLE
gdal_translate fails to interpolate

### ISSUE THREAD

**Issue by andrew-paradis** [OSGeo/gdal#1301]
I am using GDAL to cut 256x256 slippy map tiles from the ETOPO1 data source, using the etopo1_ice_g_f4.flt file, with its associated .hdr and .aux.xml files. At zoom levels requiring upsampling of the elevation data (e.g., at zoom 10 we are spreading 24 arc-minutes over 256 pixels) I noticed that there was a great deal of pixelation, as if interpolation was not happening. 

To correct the problem, I have to translate the FLT file to a GeoTIFF, overriding the output projection to EPSG:4326, and then use the new TIF file for tile cutting. The new TIF file has the correct datum, and shows proper interpolation even when upsampling.

## Expected behavior and actual behavior.

Even though no datum is defined, the FLT file still has known pixel sizes and corner coordinates. Interpolation should not depend on the datum, and should work correctly even without one defined.

## Steps to reproduce the problem.

Using the etopo1_ice_g_f4.flt file, cut a tile for zoom 10, x = 306, y = 389:

`gdal_translate -of GTiff -projwin -72.42 39.64 -72.02 39.24 -outsize 256 256 -r bilinear C:\etopo1_ice_g_f4.flt C:\tile_z10_x306_y389.tif`

Now create a color-relief from the tile's TIF file:

`gdaldem color-relief C:\tile_z10_x306_y389.tif C:\colors.txt C:\tile_z10_x306_y389_relief.png -of PNG`

Can also be seen with hillshade:

`gdaldem hillshade C:\tile_z10_x306_y389.tif C:\tile_z10_x306_y389_hillshade.png -of PNG`

**Note the severe pixelation of the images.**

Finally, convert the FLT file to a geo-referenced TIF:

`gdal_translate -a_srs EPSG:4326 C:\etopo1_ice_g_f4.flt C:\etopo1_f4.tif`

When you then use the etopo1_f4.tif file to cut color-relief tiles, the interpolation will have been applied. Note, however, that the hillshade tiles still seem to be pixelated, even when cut from the TIF.

## Operating system

Windows 10, 64 bit

## GDAL version and provenance

Occurs in both GDAL 2.4.0 OSGeo4W Shell, and GDAL 2.3.3 C# binaries.

**Comment by rouault** [comment]
Please provide needed input files (etopo1_ice_g_f4.flt + colors.txt)

**Comment by andrew-paradis** [comment]
[colors file](https://github.com/OSGeo/gdal/files/2885504/colors.txt)

[etopo1 zip](https://drive.google.com/uc?export=download&id=1DMMRztPc0TSWB7xS-22HL-4xlKlD_DbS)

**Comment by rouault** [comment]
The link to etopo1.zip doesn't work

**Comment by andrew-paradis** [comment]
Apologies. Moved it to a hopefully more accessible location: [here](https://drive.google.com/drive/folders/1BV0a-uK9FFX1cilBtzboEfbtSBrlf_KV?usp=sharing).
