### ISSUE TITLE
netcdf crashes gdal (and QGIS)

### ISSUE THREAD

**Issue by rduivenvoorde** [OSGeo/gdal#1303]
## Expected behavior and actual behavior.

Not sure where I got this netcdf file from (probably form the KNMI in NL or so), but Panoply opens it ok.

But even browsing to it already crashes QGIS (see: https://issues.qgis.org/issues/21329)

## Steps to reproduce the problem.

Download http://duif.net/temp/testcrash.zip
unzip and do 

$ gdalinfo x055002.5y397502.5.nc 
Warning 1: No UNIDATA NC_GLOBAL:Conventions attribute
Segmentation fault

## Operating system

Debian testing

## GDAL version and provenance

$ gdalinfo --version
GDAL 2.4.0, released 2018/12/14

**Comment by rduivenvoorde** [comment]
Reproduced with QGIS master on Windows 10 too, so it is probably a filthy netcdf or some strange thing in it. But as it crashes both gdal and QGIS it is maybe nice to investigate?

**Comment by rduivenvoorde** [comment]
Thanks @rouault !

**Comment by joostecg** [comment]
This seems to be recurring on QGIS 3.16.0 on Windows 10 64bit, opening or browsing to a folder with a netcdf file in the folder causes the QGIS instance to terminate with no warning or error message. The same netcdf file still opens in QGIS 3.14.15.

**Comment by guzmi** [comment]
It seems like the problem originates from files created using netCDF version 4 (NC_NETCDF4). As reported by joostecg QGis 3.14 is OK but 3.16 badly crash. NetCDF files tagged with NC_CLOBBER seems to be OK in 3.16

**Comment by rduivenvoorde** [comment]
@guzmi @joostecg this issue was closed, so I don't think adding comments here will have an effect.
Also note that the original netcdf was crashing gdal, and in second status QGIS.

As you cannot reopen issues here (I think) it is better to create a new issue here with example data (or link to it) if it crashes gdal. If it only crashes QGIS it is better to add an issue in the QGIS tracker (also linking to the actual data).
Note that I currently do NOT have QGIS crashes with my netcdf's.
