### ISSUE TITLE
PDS4: ogr2ogr - output filenames on conversion

### ISSUE THREAD

**Issue by thareUSGS** [OSGeo/gdal#1308]
## Expected behavior and actual behavior.

Currently when converting a supported vector file to PDS4 format, the output PDS4 XML label file is written as expected but the created *.csv and *.vrt take the original file name. This could be problematic for converting to/from a PDS4 file and the output will override the input.

## Steps to reproduce the problem.

og2ogr -f PDS4 out.xml input.shp

output files:
out.xml (good)
input.csv (should be out.csv)
input.vrt (should be out.vrt).

## Operating system

CentOS 7.2.1511

## GDAL version and provenance

ogr2ogr --version
GDAL 2.5.0dev-0b8391a

**Comment by rouault** [comment]
@thareUSGS  In fact, this is an intended behaviour in case you convert from a input dataset that has multiple layers (let's say "foo" and "bar"), then you'll get a foo.csv and bar.csv files referenced by out.xml. With the current implementation, you could change the filename by using "-nln out"

A potential alternative would be to use {xml_basename}_{layername}.csv naming, so out_input.csv in your above example.

**Comment by rouault** [comment]
@thareUSGS What do you think about the {xml_basename}_{layername}.csv naming scheme ?

**Comment by thareUSGS** [comment]
We have talked it over here. I think to be consistent with existing drivers we would like to keep it as close to shapefile behaviour. see [Tiger](https://www.bostongis.com/PrinterFriendly.aspx?content_name=ogr_cheatsheet) section.

Let me see if I can get this correct:
- if multi-layer input, then create a folder for the single PDS4 XML {xml_basename}.xml and then each layer will be named {layername}.csv, {layername}vrt
- if input is a single layer, then create {xml_basename}.xml, {xml_basename}.csv, {xml_basename}.xml
- if user selects one single layer, then create {xml_basename}.xml, {xml_basename}.csv, {xml_basename}.xml

If I didn't get that straight, then hopefully the shapefile driver can guide this. thoughts?

**Comment by rouault** [comment]
> thoughts?

A bit complicated to be implemented. Yes the shapefile driver has special behaviour, but this involves dedicated code in ogr2ogr itself to handle this single vs multiple layer behavior for the shapefile case. As shapefile used to be the default format, this was acceptable, but I'd rather not complicate ogr2ogr logic for PDS4.
One thing to keep in mind is that a OGR driver has no prior knowledge if it is going to be called to create a single or multiple layers, and ogr2ogr will do "create first layer, populate it, create second layer, populate it", so the driver cannot really adapt the naming scheme.

My proposed {xml_basename}_{layername}.csv naming scheme would work with current unmodified ogr2ogr logic.
Or always create a {xml_basename}_table folder and put .csv files in it, even if there is a single one.

**Comment by thareUSGS** [comment]
More discussion here. I think the creation of a {xml_basename} folder sounds like the safest approach. It seems a safer approach such that files don't get overwritten (especially when doing a PDS4 to PDS4 conversion). Although I would be tempted to add a check in general in case the input{.csv} and output{.csv} names exactly matched for any conversion. 

But we are also fine strongly encouraging the use of the "-nln" option. I will try to make a pull-request (soon) on the html page with some recommended conversion tips.

**Comment by rouault** [comment]
> Although I would be tempted to add a check in general for the case where the input{.csv} and output{.csv} names exactly matched for any conversion.

Sorry, didn't get what you mean. Can you put an example of such a situation ?

**Comment by thareUSGS** [comment]
Currently, it is really easy to overwrite an input file unknowingly. But the proposed update should alleviate this situation. 

For example:

exsiting files: inPDS4.csv and inPDS4.xml
`> ogr2ogr -f PDS4 outPDS4.xml inPDS4.xml`
will create a new outPDS4.xml correctly, but will actually overwrite the existing inPDS4.csv file it is try to read from.

**Comment by rouault** [comment]
> Currently, it is really easy to overwrite an input file unknowingly. But the proposed update should alleviate this situation.

agreed. So are we good on the solution that consists in creating a directory, or do you need some more time to ponder this ?

**Comment by thareUSGS** [comment]
we are good here.

**Comment by rouault** [comment]
Implemented per https://github.com/OSGeo/gdal/commit/07862c2cb9532b08b06b48d62b6834eef13fd6c3
