### ISSUE TITLE
gdal_retile.py ignores NoData value on input

### ISSUE THREAD

**Issue by DanielFEvans** [OSGeo/gdal#1314]
## Expected behavior and actual behavior.

When I pass gdal_retile.py input files with NoData values set, I expect the output to also have NoData.

While the actual values are passed through without modification, the resulting tiles do not have NoData set.

## Steps to reproduce the problem.
Using an input file with nodata=-3.402823e+38. I run the following command:
`gdal_retile.py -targetDir out example.tif`

The input gives "no data" when queried at top right in QGIS:
![goodtile](https://user-images.githubusercontent.com/41120183/53247746-12d90c80-36ac-11e9-93b8-3cc187b532dc.PNG)

However, the nodata has been forgotten in the output, and QGIS (and any other tool) does not recognise that the top right contains no data:
![badtile](https://user-images.githubusercontent.com/41120183/53247810-313f0800-36ac-11e9-9008-70b362727831.PNG)

## Operating system

Windows 7 64 bit and RHEL 3.10.0 64 bit

## GDAL version and provenance

GDAL 2.2.0, internal company version with some modifications. Also tested with `gdal_retile.py` bundled with GDAL 2.4.0, no change

## Notes

I have come across this relatively old email on gdal-dev which contains a fix. Is there any reason why this fix was not adopted? I suspect it simply got missed, and I'd be happy to submit a PR including it.

http://osgeo-org.1560.x6.nabble.com/gdal-dev-gdal-retile-py-does-not-use-a-nodata-value-from-GeoTIFF-td5099823.html

**Comment by rouault** [comment]
> I have come across this relatively old email on gdal-dev which contains a fix. Is there any reason why this fix was not adopted?

Was before we got on github, so was rather "costly" to take responsibility of a patch. A PR with a new test in autotest/pyscripts/test_gdal_retile.py is welcome

**Comment by rouault** [comment]
Fixed per https://github.com/OSGeo/gdal/pull/1315
Backported to release/2.4 per 83ccdc0d761c2c3bdb40f7c726958b7cb43944cb
