### ISSUE TITLE
Error using ogr2ogr to export to MapInfo TAB with EPSG:4647

### ISSUE THREAD

**Issue by fuzsin** [OSGeo/gdal#1316]
## Expected behavior and actual behavior.

Trying to export a shapefile as a Mapinfo TAB in EPSG: 4647 - ETRS89 / UTM zone 32N (zE-N) results in problem with coordinates, where x coordinates are not recognized (or lay out of boundaries). It works fine with Mapinfo MIF/MID or by exporting to Mapinfo TAB with EPSG:25832.
The same issue with QGIS 3.4.4.

## Steps to reproduce the problem.

`ogr2ogr -f "MapInfo File" output.tab input.shp`

`Warning 503: Some objects were written outside of the file's predefined bounds. These objects may have invalid coordinates when the file is reopened. Predefined bounds: (-30000000,-15000000)-(30000000,15000000)`

The output.tab is displayed (e.g. with QGIS) as a vertical line and SRS is lost.

## Operating system

Windows 10 Pro 64 Bit

## GDAL version and provenance

GDAL 2.4.0 X64 from Tamas Szekeres’ Windows binaries (http://www.gisinternals.com)

**Comment by rouault** [comment]
Are you sure your input dataset is properly registered in EPSG:4647 ? The warning seems to indicate that the coordinates you pass are not in the expected range.

**Comment by fuzsin** [comment]
Here is the output of the command ogrinfo -al -so input.shp:
INFO: Open of `input.shp'
      using driver `ESRI Shapefile' successful.

Layer name: input
Metadata:
  DBF_DATE_LAST_UPDATE=2019-02-21
Geometry: Polygon
Feature Count: 2
Extent: (32347178.216461, 5676068.206704) - (32349917.332697, 5676937.552836)
Layer SRS WKT:
PROJCS["ETRS89 / UTM zone 32N (zE-N)",
    GEOGCS["ETRS89",
        DATUM["European_Terrestrial_Reference_System_1989",
            SPHEROID["GRS 1980",6378137,298.257222101,
                AUTHORITY["EPSG","7019"]],
            TOWGS84[0,0,0,0,0,0,0],
            AUTHORITY["EPSG","6258"]],
        PRIMEM["Greenwich",0,
            AUTHORITY["EPSG","8901"]],
        UNIT["degree",0.0174532925199433,
            AUTHORITY["EPSG","9122"]],
        AUTHORITY["EPSG","4258"]],
    PROJECTION["Transverse_Mercator"],
    PARAMETER["latitude_of_origin",0],
    PARAMETER["central_meridian",9],
    PARAMETER["scale_factor",0.9996],
    PARAMETER["false_easting",32500000],
    PARAMETER["false_northing",0],
    UNIT["metre",1,
        AUTHORITY["EPSG","9001"]],
    AXIS["Easting",EAST],
    AXIS["Northing",NORTH],
    AUTHORITY["EPSG","4647"]]
Id: Integer (6.0)
Datum: String (25.0)
KonzKlasse: String (25.0)
HBNummer: String (15.0)
Schadstoff: String (25.0)
