### ISSUE TITLE
PDS4: in schema resolution set to optional

### ISSUE THREAD

**Issue by thareUSGS** [OSGeo/gdal#1318]
## Expected behavior and actual behavior.

Currently, because of the PDS4 CART schema, it was required that ( latitude_resolution and longitude_resolution ) or ( pixel_resolution_x|y and pixel_scale_x|y pairs ) were required. These are only needed for images not vector files. Thus the schema is now update (today) to make these optional.
https://github.com/thareUSGS/ldd-cart/commit/bb6f2aa71356187e755f7874e441d55146a23a15

Note: the pixel_resolution_x|y and pixel_scale_x|y are made optional via the parent "Planar_Coordinate_Information". Thus, really only the "Planar_Coordinate_Information" was made optional. Even though optional it will still be needed for images.

For vector files, please remove section "Planar_Coordinate_Information" or both ( latitude_resolution and longitude_resolution entries).

## Steps to reproduce the problem.

ogr2ogr -f PDS4 ...

## Operating system
CentOS 7.2.1511

## GDAL version and provenance
ogr2ogr --version
GDAL 2.5.0dev-0b8391a

**Comment by rouault** [comment]
Fixed per https://github.com/OSGeo/gdal/commit/1035481d6a32aeb6f4e6a2d9f842ed3703482fb4
