### ISSUE TITLE
PDS4: use of <local_identifier> for layer names

### ISSUE THREAD

**Issue by thareUSGS** [OSGeo/gdal#1319]
## Expected behavior and actual behavior.

The use of <local_identifier> within each layer, helps other readers (e.g. pds4_viewer) to distinguish these layers by name. Currently it doesn't seem to be getting set for the layers.

for example see <local_identifier> for layer names
```
    <Table_Character>
      <local_identifier>{LAYER_NAME}</local_identifier>
      <offset unit="byte">0</offset>
...
    </Table_Character>
    <Table_Character>
      <local_identifier>{LAYER_NAME}</local_identifier>
      <offset unit="byte">50</offset>
      <records>13497</records>
...
    </Table_Character>
```

Here, I do see the use of "first_table". Can that also be the layer name? If I misunderstand, then can it be the filename?
https://github.com/OSGeo/gdal/blob/ab9e80368ef662712c963191fd86fde2c5b75600/gdal/frmts/pds/pds4vector.cpp#L2274

## Steps to reproduce the enhancement.

ogr2ogr -f PDS4 ...

## Operating system
CentOS 7.2.1511

## GDAL version and provenance
ogr2ogr --version
GDAL 2.5.0dev-0b8391a

**Comment by rouault** [comment]
Fixed per https://github.com/OSGeo/gdal/commit/09dd74012c10b9484c892543c46d00f50332999b
