### ISSUE TITLE
VRT: add option for working with different LoD

### ISSUE THREAD

**Issue by VNuhaan** [OSGeo/gdal#1320]
I have a request for adding an option to the VRT-driver for the OGRVRTUnionLayer to work with different levels of detail.

Background
I have a PostgreSQL/PostGIS database with data of the same area on different level of detail (LoD). I want to create a vector tileset with on the LoD depending on the zoom level.

The zoom level dependency could be something like:
```
<OGRVRTDataSource>
	<OGRVRTUnionLayer name="layer">
		<OGRVRTLayer name="layer_1">
			<SrcDataSource>PG:dbname=lod1</SrcDataSource>
			<SrcMinZoom>0</SrcMinZoom>
			<SrcMaxZoom>10</SrcMaxZoom>
			<SrcSQL>SELECT * FROM lod1</SrcSQL>
		</OGRVRTLayer>
		<OGRVRTLayer name="layer_2">
			<SrcDataSource>PG:dbname=lod2</SrcDataSource>
			<SrcMinZoom>10</SrcMinZoom>
			<SrcMaxZoom>16</SrcMaxZoom>
			<SrcSQL>SELECT * FROM lod2</SrcSQL>
		</OGRVRTLayer>
	</OGRVRTUnionLayer>	
</OGRVRTDataSource>
```

In the above I added a <SrcMinZoom> and a <SrcMaxZoom> so that the vector lite generation can select the right OGRVRTlayer.

Best regards,

Vincent

**Comment by rouault** [comment]
This is much more involved than just extending the VRT format. It would require the concept of LoD to be present in the OGR API itself

**Comment by VNuhaan** [comment]
Oh, it is a big change.

Is there a statement for the zoom level what I can use in the where statement in the SQL string? So that the MBtiles generation can use the correct LoD tabels in PostgreSQL/PostGIS.

Somthing like:
```
<OGRVRTDataSource>
	<OGRVRTUnionLayer name="layer">
		<OGRVRTLayer name="layer_1">
			<SrcDataSource>PG:dbname=lod1</SrcDataSource>
			<SrcSQL>SELECT * FROM lod1 WHERE zoomlevel < 10</SrcSQL>
		</OGRVRTLayer>
		<OGRVRTLayer name="layer_2">
			<SrcDataSource>PG:dbname=lod2</SrcDataSource>
			<SrcSQL>SELECT * FROM lod2 WHERE zoomlevel >= 10</SrcSQL>
		</OGRVRTLayer>
	</OGRVRTUnionLayer>	
</OGRVRTDataSource>
```

Best regards,

Vincent

**Comment by rouault** [comment]
Closing. I don't see anything actionable in this

**Comment by VNuhaan** [comment]
The vector tile set I create is a mbtiles file. Is it possible to add an option in the mbites driver to use different VRT's or PostgreSQL connections for different zoom levels?

I can now generate multiple mbtile files, for each zoom level one file. But I want to generate only one mbtiles file with all zoom levels in it.

Maybe If it is possible to create a MBTiles build file for the MBTiles driver. In this file you can define the zoom level dependent VRT or PostgreSQL connections in a file. The file could look like:
```
<OGRMBTile>
	<OGRMBTileLayer>
		<SrcDataSource>PG:dbname=lod1</SrcDataSource>
		<SrcMinZoom>0</SrcMinZoom>
		<SrcMaxZoom>9</SrcMaxZoom>
		<SrcSQL>SELECT * FROM lod1</SrcSQL>
	</OGRMBTileLayer>
	<OGRMBTileLayer>
		<SrcDataSource>lod2.vrt</SrcDataSource>
		<SrcMinZoom>10</SrcMinZoom>
		<SrcMaxZoom>16</SrcMaxZoom>
	</OGRMBTileLayer>	
</OGRMBTile>
```

Best regards,

Vincent
