### ISSUE TITLE
Add (and default to) LIST_ALL_TABLES=AUTO mode to SQLite driver

### ISSUE THREAD

**Issue by nirvn** [OSGeo/gdal#1326]
## Expected behavior and actual behavior.

The SQLite driver only lists spatial tables if a geometry_columns table is present, which results in a failure to show any non-spatial tables altogether. It'd be very useful if the SQLite driver would behave like its GeoPackage counterpart, with an LIST_ALL_TABLES=AUTO option whereas both spatial tables and non-system, non-spatial tables are also shown. 

## Steps to reproduce the current situation.

- Create a spatialite file with mixed spatial and non-spatial tables
- Use ogrinfo against the file you've just created, i.e. "ogrinfo my_database.sqlite" 
- Notice the lack of non-spatial tables listed in the ogrinfo output

## Operating system

Ubuntu 18.10.

## GDAL version and provenance

2.3.2 version from ubuntu's universe repository.

**Comment by jratike80** [comment]
Fixed at some moment. https://gdal.org/drivers/vector/sqlite.html

> Dataset open options
>
> LIST_ALL_TABLES=YES/NO: This may be “YES” to force all tables, including non-spatial ones, to be listed.
