### ISSUE TITLE
StyleTable definitions not saved to created KML file

### ISSUE THREAD

**Issue by DagViggo** [OSGeo/gdal#1329]
Defined styles are correctly attached to the imported features when READING a KML file, but this seems not to work when writing/creating a KML file....? 

NO defined styles in the StyleTable are saved to the KML file.  I have tried StyleTables attached both to the DataSource and layers.

The saved KML file do have features with an identical style attached 
"<Style><LineStyle><color>ff0000ff</color></LineStyle><PolyStyle><fill>0</fill></PolyStyle></Style>"

This style has not been set by code and seems to be a default style attached by the driver..? When setting a stylestring directly on a feature, it will recognize the PEN(...) value which is reflected in the LineStyle-node. No BRUSH(...) settings are saved to the polystyle-node.

## Expected behavior and actual behavior.

I expect the defined styles to be included in the KML file and features to link to a style.
Example: 
<Placemark>
      <name>Building 41</name>
      <styleUrl>#transBluePoly</styleUrl>
      <Polygon>...

## Steps to reproduce the problem.

1. Create the outputfile:
DataSource = Driver.CreateDataSource(filename, new string[] {  });

2. Attach styletable
var dataSourceStyleTable = new StyleTable();
dataSourceStyleTable.AddStyle("yellowLineGreenPoly", "PEN(c:#FFFF007F,w:4.000000px);BRUSH(fc:#00FF007F)");
dataSourceStyleTable.AddStyle("thickBlackLine", "PEN(c:#00000087,w:10.000000px)");
DataSource.SetStyleTable(dataSourceStyleTable);

3.Create features which link to style
feature.SetStyleString("@yellowLineGreenPoly");

4. There is no defined styles in the created KML file or the given pen and brush style attached to the feature.

## Operating system

Visual Studio 2017, Any CPU

## GDAL version and provenance

GDAL 2.3.3. 
Using C# Nuget packages:
https://www.nuget.org/packages/GDAL.Native/
https://www.nuget.org/packages/GDAL/

**Comment by rouault** [comment]
You need to use the LIBKML driver, not the KML one for such capability. StyleTable is tested by this script: https://github.com/OSGeo/gdal/blob/master/autotest/kml_generate_test_files.py
