### ISSUE TITLE
Add new hillshading algorithm "Igor" to gdaldem

### ISSUE THREAD

**Issue by zdila** [OSGeo/gdal#1330]
Igor's hillshading algorithm from Maperitive has a great property that [_renders a softer hillshade which tries to minimize effects on other map features_](http://maperitive.net/docs/Commands/GenerateReliefImageIgor.html). For example it doesn't alter (darken) flatlands.

For live usecase you can see for example:

* https://www.freemap.sk/?map=14/48.881086/21.396947&layers=X
* https://www.freemap.sk/?map=13/48.603404/20.445471&layers=T

Algorithm is shared at https://gist.github.com/breki/e69be079d43d449ad823d0ec50e42929 and https://gist.github.com/breki/0db16a5fcc2e0dd2022fb99eacf7b50c by Igor himself.

PS: For the reference see https://twitter.com/martinzdila/status/1100484997616750592

**Comment by rouault** [comment]
If you wish to submit this as a PR, that's welcome

**Comment by zdila** [comment]
@rouault please check

**Comment by jratike80** [comment]
How much there is left from the original implementation? Maperative is known be not open source. The algorithm may be open source or too simple to be copyrighted but there is no mention about that in GitHub https://gist.github.com/breki/e69be079d43d449ad823d0ec50e42929. Confirmation from @breki that MIT license is OK migh be good to have.

**Comment by breki** [comment]
Hi,

I can confirm the code/algorithm in question has been released with MIT
license (or whichever license your project is compatible with).

Kind regards,
Igor Brejc

**Comment by Symbian9** [comment]
@breki Is it same hillshading algorithm as `Alpenglow.py`?

- http://braincrunch.tumblr.com/post/26190799580/maperitive-alpenglow-effect-using-a-custom-shader

**Comment by breki** [comment]
It's similar, but not quite the same. First of all, alpenglow adds a
yellowish tint. Also, comparing the two source codes, the formulas for
shading factor are different.

Igor

**Comment by Symbian9** [comment]
@breki, could you also open sources of `Alpenglow` hillshading?

**Comment by breki** [comment]
It's already in public domain. I've attached the source code (it depends on
Maperitive's internal API, but the algorithm itself is in this file).

Cheers,
Igor
