### ISSUE TITLE
Cannot open GDB file using OpenFileGdb

### ISSUE THREAD

**Issue by nyalldawson** [OSGeo/gdal#1332]
The GDB file downloadable from https://vgin.maps.arcgis.com/home/item.html?id=29627d7c051a47dc8ce71b4484531ab3 cannot be read by the OpenFileGdb driver. 

Attempting to open the file results in the error: "Warning 1: VA_Parcels layer has a Virginia_Parcel_Dataset_2018Q4.gdb/a00000009.gdbtable.cdf file whose format is unhandled"

## Steps to reproduce the problem.

1. Download the gdb from https://vgin.maps.arcgis.com/home/item.html?id=29627d7c051a47dc8ce71b4484531ab3
2. Attempt to use with any OGR tool

## Operating system

Fedora 29

## GDAL version and provenance

GDAL 2.2.4

**Comment by rouault** [comment]
Yep, known limitation mentionned in https://gdal.org/drv_openfilegdb.html : "Cannot read data from compressed data in CDF format (Compressed Data Format)."
There isn't much that can be done. This is a completely different beast. My reverse engineering attempts of it miserably failed. It seems that there is encryption involved.

**Comment by nyalldawson** [comment]
Ok. Shall we close?
