### ISSUE TITLE
PDS4: capitalization updated for Planetocentric and Planetographic in schema

### ISSUE THREAD

**Issue by thareUSGS** [OSGeo/gdal#1334]
## Expected behavior and actual behavior.

The schema was inconsistent and was [updated](https://github.com/thareUSGS/ldd-cart) to correct for the case for these values. They should be now updated to **P**lanetocentric and **P**lanetographic.

sections in code which require minor updates:
https://github.com/OSGeo/gdal/blob/29693f999fa9435ffcf1c4bdc2ffa2eeb3011b9c/gdal/frmts/pds/pds4dataset.cpp#L2531

https://github.com/OSGeo/gdal/blob/29693f999fa9435ffcf1c4bdc2ffa2eeb3011b9c/gdal/frmts/pds/pds4dataset.cpp#L4220

in files:
https://github.com/OSGeo/gdal/blob/d5f6bb89b0e0db0a06489419050d432e8f58ff47/autotest/gdrivers/data/byte_pds4.xml#L77

https://github.com/OSGeo/gdal/blob/d5f6bb89b0e0db0a06489419050d432e8f58ff47/autotest/gdrivers/data/byte_pds4_multi_sds.xml#L77

https://github.com/OSGeo/gdal/blob/15ee4d88adf045b77b620d1d10e33e3dbe62ae2b/autotest/ogr/data/pds4/poly_delimited.xml#L87

https://github.com/OSGeo/gdal/blob/07862c2cb9532b08b06b48d62b6834eef13fd6c3/gdal/frmts/pds/frmt_pds4.html#L115

## Steps to reproduce the problem.

gdal_translate -of PDS4 ...

## Operating system

n/a

## GDAL version and provenance

dev

**Comment by rouault** [comment]
Fixed per https://github.com/OSGeo/gdal/commit/6559e25602588a787b76f247a28f049f6d28088a
