### ISSUE TITLE
The problems about the gdal_pansharpen.py

### ISSUE THREAD

**Issue by DRjy** [OSGeo/gdal#1337]
pth=r'E:\!fusion\GF1_ORTHOS'
out_panshapen=os.path.join(pth,'gdal_merge.tif')
pthon_pansharpen=r'D:\01Program\Anaconda3\envs\py36\Lib\site-packages\GDAL-2.2.2-py3.6-win-amd64.egg-info\scripts\gdal_pansharpen.py'
files=os.listdir(pth)
for file in files:
    if file.endswith('.tif') and '_ORTHO_MS' in file:
        pan_img=os.path.join(pth,file)
    if file.endswith('.tif') and '_ORTHO_PAN' in file:
        mss_img=os.path.join(pth,file)
cmd_str='python   {}  -b 1 -b 2 -b 3 {} {} '.format(pthon_pansharpen,pan_img,mss_img)

import subprocess
subprocess.call(cmd_str,shell=True)

But there is no outputs!
what's wrong?
python environment: python 3.6, windows platform

**Comment by rouault** [comment]
The issue is more about how to use GDAL. Please use the support channels mentionned in gdal.org or https://gis.stackexchange.com/
