### ISSUE TITLE
Value of degree-to-radians used in OGRProj4CT is too large

### ISSUE THREAD

**Issue by vaclavblazek** [OSGeo/gdal#1342]
## Expected behavior and actual behavior.

When converting between longlat above geoid to longlat above ellipsoid (or vice versa) at north/south pole one expects to get the same horizontal coordinates and the vertical component shifted by the height sampled from geoid grid.

Expected behaviour:
```
echo "0 90 0" | gdaltransform -s_srs "epsg:4326+5773" -t_srs "epsg:4326"
0 90 13.6062450408936
```
Actually behaviour:
```
ERROR 1: point not within available datum shift grids
transformation failed
```
## Steps to reproduce the problem.

See example above.

## Cause.

The cause of this behaviour is that degree-to-radians conversion factor is read from the WKT SRS definition `GEOGCS|UNIT` node. This value is a bit larger than the proper value and PROJ.4 subsequently gets angular coordinate slightly beyond 90 degrees and rejects to sample vertical shift grid (which ends exactly at 90 degrees north/south).
The PROJ.4-provided `cs2cs` tool has no such problem because it uses its own compiled-in constant.

The difference between value read from SRS node (0.0174532925199433) and the compiled-in constant (`#define DEG_TO_RAD      .0174532925199432958`) is `3.469446951953614e-18`. It seems insignificant but causes overflow over actual 90 degrees.

## Suggested fix.

 I added the following to `OGRProj4CT::InitializeNoLock` function in our build:
```c++
if (fabs(dfSourceToRadians - DEG_TO_RAD) < 1e-12) {
    // almost DEG_TO_RAD, replace with exact value
    dfSourceToRadians = DEG_TO_RAD;
}
```

I.e. I enforce the use of more exact conversion constant than the one coming from SRS but only when the value from SRS is really close to the actual constant. Probably the analogous operation should be done for `dfTargetToRadians`.

## Operating system
Debian Stretch 64 bit
Ubuntu 18.04 64 bit

## GDAL version and provenance
2.1.2+dfsg-5 from the official Debian repo
2.3.2+dfsg-2~bionic0 from the official Ubuntu repo

**Comment by rouault** [comment]
You can submit this as a pull request against the release/2.4 branch (the issue likely no longer exists in master since this part of the code has been completely rewritten)

**Comment by rouault** [comment]
Closing. Works for me with GDAL master with PROJ 6, and 2.4 branch with PROJ 5.1.0
