### ISSUE TITLE
gdalbuildvrt

### ISSUE THREAD

**Issue by manuelmx** [OSGeo/gdal#1344]
## Expected behavior and actual behavior.

For example (please modify !!!): I expected to be able to open this raster file (with a link to
the raster file, or it as an attachment) and it returns an error message
instead.

## Steps to reproduce the problem.

For example (please modify !!!): "gdalinfo myfile"

## Operating system

For example (please modify !!!): Ubuntu 16.04 64 bit

## GDAL version and provenance

For example (please modify !!!): the 2.2.3 version from ubuntugis-unstable PPA

**Comment by manuelmx** [comment]
I have a problem with gdalbuildvrt in QGIS 3.4.4 when I run Raster>Miscellaneous>Build Virtual Raster, there are a problem, the program display  /bin/sh: gdalbuildvrt: command not found. Some solution? Thanks.

**Comment by rouault** [comment]
This is something to report to the QGIS bug tracker
