### ISSUE TITLE
gdalwarp: properly document the -wm option

### ISSUE THREAD

**Issue by misev** [OSGeo/gdal#1345]
The documentation of gdalwarp specifies:

       -wm memory_in_mb:
           Set the amount of memory (in megabytes) that the warp API is allowed to use for caching.

However, in the code (gdalwarp_lib.cpp) gdalwarp does this:

        else if( EQUAL(papszArgv[i],"-wm") && i+1 < argc )
        {
            if( CPLAtofM(papszArgv[i+1]) < 10000 )
                psOptions->dfWarpMemoryLimit = CPLAtofM(papszArgv[i+1]) * 1024 * 1024;
            else
                psOptions->dfWarpMemoryLimit = CPLAtofM(papszArgv[i+1]);
            i++;
        }

which is clearly different, if -wm is >= 10000 it's actually considered to be bytes and not MB.

**Comment by misev** [comment]
Also multiplying by 1024 * 1024 indicates mebibyte (MiB) rather than MB, but this is not a big deal here I guess.

**Comment by misev** [comment]
> not a big deal here I guess

well.. for 10GB it adds up ~0.5GB, not so insignificant actually.

**Comment by jratike80** [comment]
How about adding a link to https://trac.osgeo.org/gdal/wiki/ConfigOptions#GDAL_CACHEMAX?
Did you have some problem when you came to make this ticket? Did you want to configure  gdalwarp to use less than 1 MB or more than 10000 MB of memory?

**Comment by misev** [comment]
I specified exactly 10000 (wanting 10GB), but got an error which didn't make sense according to gdalwarp's documentation:

    ERROR 5: GDALWarpOptions.Validate()
      dfWarpMemoryLimit=10000 is unreasonably small.

GDAL_CACHEMAX seems to have a different threshold according to that wiki page btw (100000) and also supports percentage format.

**Comment by jratike80** [comment]
Ok, link to GDAL_CACHEMAX does not resolve your issue.

It may be that you do not really want to use 10 GB of warping memory because usually it does not make warping faster. In the past pointing unnecessary much warping memory could even make warping much slower in some circumstances but that may have changed since this ticket https://trac.osgeo.org/gdal/ticket/3120 and this document were created https://trac.osgeo.org/gdal/wiki/UserDocs/GdalWarp#WillincreasingRAMincreasethespeedofgdalwarp

**Comment by misev** [comment]
I resolved my issue just fine by specifying 10 000 000 000 instead of 10 000.

The problem is that I had to go into the source code of gdalwarp to understand this. So I open this ticket to prevent a similar surprise to other users. It's trivial to fix this:
- update gdalwarp documentation of -wm (gdalwarp -h, man gdalwarp) to reflect its behavior exactly
- or change the behavior of gdalwarp

**Comment by jratike80** [comment]
I had no intention to be unpolite. I am just curious to know if having 10 GB of warping memory is reasonable in some use cases, while based on the old discussion that I have followed it is usually not. There may be a need to update the wiki document https://trac.osgeo.org/gdal/wiki/UserDocs/GdalWarp as well.

**Comment by misev** [comment]
This discussion is not very related to the ticket.

Intuitively I'd expect that the more memory given to gdalwarp the better the performance, as it would decrease or eliminate swapping. I have a huge file that takes hours to warp, but also a lot of resources (~0.7TB RAM), so giving gdalwarp more memory is no problem and will hopefully minimize the time it takes.

In https://trac.osgeo.org/gdal/ticket/3120 it seems like the -wm parameter somehow influences other parameters, which could in the end lead to worse performance. This is surprising, -wm should be decoupled as much as possible from such effects in my opinion.

**Comment by misev** [comment]
Maybe the documentation needs to be fixed wrt this as well? Currently for -wm it says "amount of memory (in megabytes) that the warp API is allowed to use for **caching**"

**Comment by misev** [comment]
Wow that's really surprising, thanks for checking! Based on this it seems like -wm 100 is around the best. I have a 70GB file of size 325000 x 230000, taking 20+ hours already without specifying any -wm, so doing a benchmark like this is not practical.

**Comment by jratike80** [comment]
Benchmarks are always practical. You can cut a smaller part of you image with gdal_translate for the benchmark. You know now that my laptop can warp my image in 4 minutes, you have 100 times bigger image so it should take roughly 400 minutes if there is a linear scale. You say you need 1200 minutes with something that is obviously not a laptop and I bet that it can do better. Do you have tiled images both as input and output? Have you tried with -multi?
