### ISSUE TITLE
PDS4: -co TEMPLATE=pds4_template.xml not recognized

### ISSUE THREAD

**Issue by thareUSGS** [OSGeo/gdal#1347]
## Expected behavior and actual behavior.

cp $GDAL_DATA/pds4_template.xml .
"-co TEMPLATE=pds4_template.xml" seems to return this error no matter how I test. I believe I am doing it correctly.
ERROR 6: Unknown option name '-co'

I am testing with pds4_template.xml, but any template XML file issues the same error.

## Steps to reproduce the problem.

ogr2ogr -f PDS4 -co TEMPLATE=pds4_template.xml out.xml in

## Operating system

CentOS Linux release 7.3.1611 (Core)

## GDAL version and provenance

GDAL 2.5.0dev-df9184e

**Comment by rouault** [comment]
For ogr2ogr, TEMPLATE is in the dataset/datasuorce creation option list, so you need to use -dsco TEMPLATE=foo.xml

**Comment by thareUSGS** [comment]
Good to hear. I will update the documentation to show more example use cases to distinguish GDAL/OGR commands.  I was confusing the use of TEMPLATE with gdal_translate which uses "-co".

One more -- in the ogr2ogr --format PDS4 command-line help, it shows TEMPLATE under <CreationOptionList>, should that be update to <DataSetCreationOptionList>?  I am fine with either.

**Comment by rouault** [comment]
agreed that DataSetCreationOptionList would be clearer in that context, but being a generic formatting for all drivers, that would break existing code.

**Comment by thareUSGS** [comment]
understood - we will keep it.
