### ISSUE TITLE
VFK driver regression: curved geometries ignored

### ISSUE THREAD

**Issue by landam** [OSGeo/gdal#1351]
## Expected behavior and actual behavior.

VFK driver supports curved geometries since 8b17b3d681fd971fe9a112529c6c53b8265cfabd

Unfortunately starting with 1edc0edef17175e78bdac0eaa40a976ebf10afa2 all curved geometries are simply skipped. This regression affects all active branches.

![vfk_broken](https://user-images.githubusercontent.com/5683186/54118760-1b437e00-43f4-11e9-8e7d-f1555b972383.jpg)

## Steps to reproduce the problem.

/opt/gdal/bin/ogrinfo file.vfk

## Operating system

Debian Unstable 64 bit

## GDAL version and provenance

2.4 git branch

**Comment by landam** [comment]
d45c6b8 should fix this issue.

![vfk_fixed](https://user-images.githubusercontent.com/5683186/54119329-58f4d680-43f5-11e9-935d-8b28c4481f47.jpg)

Backport to 2.4 and 2.3 branches planned.

**Comment by rouault** [comment]
Just as a remainder that I intend a 2.4.1 release this Friday (make sure to cherry-pick my follow up fix of https://github.com/OSGeo/gdal/commit/7b4ea5a4561efb2fd15123a55253fbaa358a1c45 if needed )

**Comment by landam** [comment]
Done, backport to 2.3 is probably not needed (not sure if any 2.3 release is planned)

**Comment by rouault** [comment]
> not sure if any 2.3 release is planned

none is planned indeed. We maintain only 2.4.x at that time
