### ISSUE TITLE
File GRIB2: it report bad data

### ISSUE THREAD

**Issue by polzader** [OSGeo/gdal#1354]
Expected behavior and actual behavior.

I need to process GFS data (global forecast system) of temperature, but gdalinfo reports incorrect maximums and minima. The format file is GRIB2. I compared minimun and maximun between output command wgrib (provisted by GFS) and gdalinfo. Also the original data is set to farenget degrees and the data once read by gdalinfo, reports that they are centric degrees.

Steps to reproduce the problem.

1 - ./gdalinfo -stats TMP_gfs.t00z.pgrb2.0p25.f002 
**The output:**
 Driver: GRIB/GRIdded Binary (.grb, .grb2)
Files: TMP_gfs.t00z.pgrb2.0p25.f002
         TMP_gfs.t00z.pgrb2.0p25.f002.aux.xml
Size is 301, 381
Coordinate System is:
GEOGCS["Coordinate System imported from GRIB file",
    DATUM["unknown",
        SPHEROID["Sphere",6371229,0]],
    PRIMEM["Greenwich",0],
    UNIT["degree",0.0174532925199433]]
Origin = (-120.125000000000000,35.125000000000000)
Pixel Size = (0.250000000000000,-0.250000000000000)
Corner Coordinates:
Upper Left  (-120.1250000,  35.1250000) 
Lower Left  (-120.1250000, -60.1250000) 
Upper Right ( -44.8750000,  35.1250000) 
Lower Right ( -44.8750000, -60.1250000) 
Center      ( -82.5000000, -12.5000000) 
Band 1 Block=301x1 Type=Float64, ColorInterp=Undefined
  Description = 2[m] HTGL="Specified height level above ground"
  Min=-4.567 Max=32.203 
  **Minimum=-4.567, Maximum=32.203**, Mean=19.699, StdDev=7.056
  Metadata:
    GRIB_COMMENT=Temperature [C]
    GRIB_DISCIPLINE=0(Meteorological)
    GRIB_ELEMENT=TMP
    GRIB_FORECAST_SECONDS=7200 
    GRIB_IDS=CENTER=7(US-NCEP) SUBCENTER=0 MASTER_TABLE=2 LOCAL_TABLE=1 SIGNF_REF_TIME=1(Start_of_Forecast) REF_TIME=2019-02-26T00:00:00Z PROD_STATUS=0(Operational) TYPE=1(Forecast)
    GRIB_PDS_PDTN=0
    GRIB_PDS_TEMPLATE_ASSEMBLED_VALUES=0 0 2 0 96 0 0 1 2 103 0 2 255 0 0
    GRIB_PDS_TEMPLATE_NUMBERS=0 0 2 0 96 0 0 0 1 0 0 0 2 103 0 0 0 0 2 255 0 0 0 0 0
    GRIB_REF_TIME=1551139200 sec UTC
    GRIB_SHORT_NAME=2-HTGL
    GRIB_UNIT=[C]
    GRIB_VALID_TIME=1551146400 sec UTC
    STATISTICS_MAXIMUM=32.203424072266
    STATISTICS_MEAN=19.698685298924
    STATISTICS_MINIMUM=-4.5665649414062
    STATISTICS_STDDEV=7.0560777031042
    STATISTICS_VALID_PERCENT=100

2 -  wgrib2 -V TMP_gfs.t00z.pgrb2.0p25.f002 
**The output:**
1:0:vt=2019022602:2 m above ground:2 hour fcst:TMP Temperature [K]:
    ndata=114681:undef=0:mean=292.849:**min=268.583:max=305.353**
    grid_template=0:winds(N/S):
	lat-lon grid:(301 x 381) units 1e-06 input WE:SN output WE:SN res 48
	lat -60.000000 to 35.000000 by 0.250000
	lon 240.000000 to 315.000000 by 0.250000 #points=114681

Operating system
Ubutu 18.04 LTS

GDAL version and provenance
./gdalinfo --version
GDAL 2.4.0, released 2018/12/14
Download from:
git clone -b release/2.4 https://github.com/OSGeo/gdal.git

Attached file:
[TMP_gfs.t00z.pgrb2.0p25.zip](https://github.com/OSGeo/gdal/files/2952800/TMP_gfs.t00z.pgrb2.0p25.zip)

Thanks

**Comment by rouault** [comment]
This is expected behaviour. GDAL reports temperatures as celcius degrees by default.
This is documented in https://gdal.org/frmt_grib.html
If you define the GRIB_NORMALIZE_UNITS=NO configuration option / environment variable, you will get Kelvins.
