### ISSUE TITLE
New feature: Patch to add "-input_file_list" option to gdaltindex

### ISSUE THREAD

**Issue by andrew-aitchison** [OSGeo/gdal#1356]
Gdalbuildvrt has an option "-input_file_list"  which allows the user to specify a text file with an input filename on each line.

The pull request
   https://github.com/OSGeo/gdal/pull/1353
adds the same feature to gdaltindex.
This includes updates to the documentation and test-suite.

## Operating system
The patch should work on all OSes; it was developed on Ubuntu 18.10 64 bit, g++ (Ubuntu 8.2.0-7ubuntu1) 8.2.0

**Comment by andrew-aitchison** [comment]
In the pull-request #1353, @rouault  wrote
> Hum, I'm not sure we need this. This could already be accomplished with --optfile your.txt. So perhaps this could be just a documentation hint. (Yes, I know that gdalbuildvrt has a -input_file_list switch, but this was an oversight from myself.)

Agreed. I'll close the pull request and leave the issue, to remind me to update the docs.

**Comment by jratike80** [comment]
It is documented in https://www.gdal.org/gdal_utilities.html but it is true that people do not find that page easily.

**Comment by andrew-aitchison** [comment]
Sorry. I'm getting my git clone in a mess.
This patch will do implement my fix, which is to mention the gdal_utilities docs in the gdaltindex man page.
[1356.1.patch.txt](https://github.com/OSGeo/gdal/files/2987826/1356.1.patch.txt)

**Comment by andrew-aitchison** [comment]
Looks good, but the man page doesn't have a helpful pointer. How about:
[1356.2.patch.txt](https://github.com/OSGeo/gdal/files/2988469/1356.2.patch.txt)
