### ISSUE TITLE
GDAL Library deployment

### ISSUE THREAD

**Issue by santhoshdec18** [OSGeo/gdal#1357]
Hi Team,

We develop ArcGIS add-ins for Shell and we have developed an add in to translate ZMap to Raster type. Since these ArcGIS products are desktop products, these add-ins are pushed to the user workstations through software center updates by scripting. As we understand, GDAL library need to be installed on the user desktops to get the plug-in working. The challenge here is, GDAL library is huge in size and pushing this to user desktops is very time consuming and users might not like it. Please guide us if there is any other way to avoid library deployment in the users desktop however include the dependencies as part of add-in assembly itself. 

Thanks,
Santosh

**Comment by rouault** [comment]
This is no a bug report. You may use the other support channels mentionned in https://gdal.org/ . But this is probably something that should be seen with ArcGIS support. ArcGIS itself uses GDAL internally...
