### ISSUE TITLE
Multipatch features of this shapefile cannot be seen with latest gdal version (unknown geometry)

### ISSUE THREAD

**Issue by yanivday** [OSGeo/gdal#1363]
## Expected behavior and actual behavior.
While a multipatch layer’s geometry is recognized as Polygon with Qgis 2.8 and the layer can be seen, the layer cannot be seen with QGISv3.6 (unknown geometry).
Thanks.
See conversation and sample shapefile here: https://issues.qgis.org/issues/21560 
(https://issues.qgis.org/attachments/download/14570/model.zip)

## Steps to reproduce the problem.

Import the shapefile to QGIS v3.6 (regression from v2.8)
https://issues.qgis.org/attachments/download/14570/model.zip 

## Operating system

OS=Windows 10x64.

## GDAL version and provenance

I'm not sure

**Comment by rouault** [comment]
This is something that should be fixed in QGIS. GDAL several versions ago has started reported multipatch as TIN or GEOMETRYCOLLECTION of TIN, instead of the improper MULTIPOLYGON as it did before. QGIS should be upgraded to handle those new geometry types.

For example ogrinfo reports
```
  GEOMETRYCOLLECTION Z (TIN Z (((36587034.5560299 3793637.11402507 298.450988769531,36587034.5560299 3793637.11402507 251.322998046875,36586985.6698492 3793626.85509158 291.41000366211,36587034.5560299 3793637.11402507 298.450988769531)),((36587034.5560299 3793637.11402507 251.322998046875,36586985.6698492 3793626.85509158 291.41000366211,36586985.6698492 3793626.85509158 243.074996948242,36587034.5560299 3793637.11402507 251.322998046875))),TIN Z (((36586985.6698492 3793626.85509158 291.41000366211,36586985.6698492 3793626.85509158 243.074996948242,36587006.4961656 3793675.55801473 294.063995361328,36586985.6698492 3793626.85509158 291.41000366211)),((36586985.6698492 3793626.85509158 243.074996948242,36587006.4961656 3793675.55801473 294.063995361328,36587006.4961656 3793675.55801473 245.207000732422,36586985.6698492 3793626.85509158 243.074996948242))),TIN Z (((36587006.4961656 3793675.55801473 294.063995361328,36587006.4961656 3793675.55801473 245.207000732422,36587034.5560299 3793637.11402507 298.450988769531,36587006.4961656 3793675.55801473 294.063995361328)),((36587006.4961656 3793675.55801473 245.207000732422,36587034.5560299 3793637.11402507 298.450988769531,36587034.5560299 3793637.11402507 251.322998046875,36587006.4961656 3793675.55801473 245.207000732422))),TIN Z (((36587034.5560299 3793637.11402507 298.450988769531,36586985.6698492 3793626.85509158 291.41000366211,36587006.4961656 3793675.55801473 294.063995361328,36587034.5560299 3793637.11402507 298.450988769531))),TIN Z (((36587006.4961656 3793675.55801473 245.207000732422,36586985.6698492 3793626.85509158 243.074996948242,36587034.5560299 3793637.11402507 251.322998046875,36587006.4961656 3793675.55801473 245.207000732422))))
```

**Comment by yanivday** [comment]
Thanks, @rouault 
I've updated QGIS support team: https://issues.qgis.org/issues/21560

**Comment by agiudiceandrea** [comment]
> This is something that should be fixed in QGIS. GDAL several versions ago has started reported multipatch as TIN or GEOMETRYCOLLECTION of TIN, instead of the improper MULTIPOLYGON as it did before.

So, it seems https://www.gdal.org/drv_shapefile.html should be updated. Now it states that:
`MultiPatch files are read and each patch geometry is turned into a multi-polygon representation with one polygon per triangle in triangle fans and meshes.`

**Comment by yanivday** [comment]
Hi @rouault ,
following our tests, TIN Geometry Type is not supported by GEOS. GDAL make use in GEOS, thus, GDAL Spatial Operation like Union will fail. The solution, as we can see it, is to support the old behavior by a new setting that will be set by CPLSetConfigOption. 
Is this possible?
Thanks.

**Comment by rouault** [comment]
> Is this possible?

Would require more thought. Please open a new ticket about that
