### ISSUE TITLE
GDAL command output: /bin/sh: gdalwarp: command not found

### ISSUE THREAD

**Issue by manuelmx** [OSGeo/gdal#1367]
Hi people,

I have this problem when I tried to applied clipper raster with mask in QGIS 3.4.5 in MacOS, I don't understand what happened. Any solution, thanks.

gdalwarp -of GTiff -cutline "/Users/marr/Documents/Año Sabatico/2018/SIG Manual/SIG QGIS/Práctica 15/Isla_Arena_Mascara.shp" -crop_to_cutline "/Users/marr/Documents/Año Sabatico/2018/SIG Manual/SIG QGIS/Práctica 15/Isla_Arena_ph_IDW.tif" "/Users/marr/Documents/Año Sabatico/2018/SIG Manual/SIG QGIS/Práctica 15/Prueba.tif"

**Comment by rouault** [comment]
What is the problem exactly ? Error message ? Wrong output ?

**Comment by rouault** [comment]
ah sorry: the error is in the title of the bug. Well this is likely an installation issue ? You might lack the GDAL binaries themselves. Not a GDAL bug. Closing

**Comment by YunzhiZhang** [comment]
Hello, I have encountered the same problem. How can I solve it
