### ISSUE TITLE
Handle SQLITE_BUSY response when decoding datasets gpkg in many threads

### ISSUE THREAD

**Issue by christapley** [OSGeo/gdal#1370]
## Expected behavior and actual behavior.

If we decode a gpkg dataset with many (>= 8) threads concurrently, occasionally sqlite3_step (ogr/ogrsf_frmts/gpkg/gdalgeopackagerasterband.cpp(922)) returns SQLITE_BUSY and then the requested block gets filled as empty.

![image](https://user-images.githubusercontent.com/13928402/54500899-9230c780-495c-11e9-8bd3-656f426b14a3.png)

During transcode, this results in a dataset that has random blank sections:

![image](https://user-images.githubusercontent.com/13928402/54500744-fb174000-495a-11e9-8d2b-e36ca1b7e862.png)

## Steps to reproduce the problem.

This can also be reproduced with https://github.com/OSGeo/gdal/blob/d5f6bb89b0e0db0a06489419050d432e8f58ff47/gdal/apps/multireadtest.cpp

[small.zip](https://github.com/OSGeo/gdal/files/2975951/small.zip)
```
Got checksum 47396, launching 1 worker threads on E:\Datasets\small.gpkg, 10 iterations.
All threads complete.
```
```
Got checksum 47396, launching 4 worker threads on E:\Datasets\small.gpkg, 10 iterations.
All threads complete.
```
```
Got checksum 47396, launching 8 worker threads on E:\Datasets\small.gpkg, 10 iterations.
Checksum ERROR in worker thread!
Checksum ERROR in worker thread!
Checksum ERROR in worker thread!
All threads complete.
```
If I compile multireadtest.cpp against the gisinternals gdal builds I also see the problem, however, it took more iterations:
```
C:\Users\ctapley\Downloads\release-1911-x64-gdal-2-4-0-mapserver-7-2-2\bin\gdal\apps>multireadtest.exe -t 8 -i 100 e:\datasets\small.gpkg
Got checksum 47396, launching 8 worker threads on e:\datasets\small.gpkg, 100 iterations.
Checksum ERROR in worker thread!
Checksum ERROR in worker thread!
Checksum ERROR in worker thread!
Checksum ERROR in worker thread!
Checksum ERROR in worker thread!
All threads complete.
```
I presume this is due to different sqlite versions in use (and we build sqlite with -DSQLITE_THREADSAFE=2 which is not the default)

## Operating system

I have only tested in Windows 10 x64 Version 1809 (b17763.379).

## GDAL version and provenance

I have only tested back as far as gdal-2.1.2 and I believe it is a problem since at least then

## Potential solution

Set a busy timeout (https://www.sqlite.org/c3ref/busy_timeout.html) when opening the sqlite dataset:
```
	const char* pszVal = CPLGetConfigOption("SQLITE_READ_TIMEOUT", "5000");
	if (pszVal != nullptr) {
		sqlite3_busy_timeout(hDB, atoi(pszVal));
	}
```
Qt's sqlite db driver uses a 5 second default (https://github.com/qt/qtbase/blob/c0b265662e618f0d953ed2c389bad9f50ac24f7f/src/plugins/sqldrivers/sqlite/qsql_sqlite.cpp#L778)

This will make sqlite retry until the time out is expired.  If, sqlite still returns SQLITE_BUSY then I think the driver should return an error or at least warn that your decode is probably broken.

Would gdal be happy with this solution?

**Comment by christapley** [comment]
Logging the sqlite queries doesn't show unexpected queries that would require write locking on the tile data:

[sqlite_queries.zip](https://github.com/OSGeo/gdal/files/2976071/sqlite_queries.zip)

```
{SQL} [SELECT 1 FROM sqlite_master WHERE (type = 'trigger' OR type = 'view') AND (sql LIKE '%%ogr_geocode%%' OR sql LIKE '%%ogr_datasource_load_layers%%' OR sql LIKE '%%ogr_GetConfigOption%%' OR sql LIKE '%%ogr_SetConfigOption%%' ) LIMIT 1]
{SQL} [PRAGMA foreign_key_check]
{SQL} [PRAGMA encoding]
{SQL} [SELECT COUNT(*) FROM sqlite_master WHERE name IN ('gpkg_spatial_ref_sys', 'gpkg_contents') AND type IN ('table', 'view')]
{SQL} [SELECT 1 FROM sqlite_master WHERE name = 'gpkg_ogr_contents' AND type = 'table']
{SQL} [SELECT 1 FROM sqlite_master WHERE name = 'gpkg_extensions' AND type IN ('table', 'view')]
{SQL} [SELECT 1 FROM sqlite_master WHERE name = 'gpkg_tile_matrix_set' AND type IN ('table', 'view')]
{SQL} [SELECT c.table_name, c.identifier, c.description, c.srs_id, c.min_x, c.min_y, c.max_x, c.max_y, tms.min_x, tms.min_y, tms.max_x, tms.max_y, c.data_type FROM gpkg_contents c JOIN gpkg_tile_matrix_set tms ON c.table_name = tms.table_name WHERE c.table_name IS NOT NULL AND tms.min_x IS NOT NULL AND tms.min_y IS NOT NULL AND tms.max_x IS NOT NULL AND tms.max_y IS NOT NULL AND data_type IN ('tiles', '2d-gridded-coverage') LIMIT 1000]
{SQL} [SELECT definition, organization, organization_coordsys_id FROM gpkg_spatial_ref_sys WHERE definition IS NOT NULL AND srs_id = 4326 LIMIT 2]
{SQL} [SELECT zoom_level, pixel_x_size, pixel_y_size, tile_width, tile_height, matrix_width, matrix_height FROM gpkg_tile_matrix tm WHERE table_name = 'small' AND zoom_level >= 0 AND zoom_level <= 65536 AND pixel_x_size > 0 AND pixel_y_size > 0 AND tile_width >= 1 AND tile_width <= 65536 AND tile_height >= 1 AND tile_height <= 65536 AND matrix_width >= 1 AND matrix_height >= 1 AND EXISTS(SELECT 1 FROM 'small' WHERE zoom_level = tm.zoom_level LIMIT 1) ORDER BY zoom_level DESC LIMIT 100]
{SQL} [SELECT 1 FROM sqlite_master WHERE name = 'gpkg_extensions' AND type IN ('table', 'view')]
{SQL} [SELECT tile_data FROM "small" WHERE zoom_level = 6 AND tile_row = 0 AND tile_column = 0]
{SQL} [SELECT tile_data FROM "small" WHERE zoom_level = 6 AND tile_row = 0 AND tile_column = 1]
{SQL} [SELECT tile_data FROM "small" WHERE zoom_level = 6 AND tile_row = 0 AND tile_column = 2]
{SQL} [SELECT tile_data FROM "small" WHERE zoom_level = 6 AND tile_row = 0 AND tile_column = 3]
{SQL} [SELECT tile_data FROM "small" WHERE zoom_level = 6 AND tile_row = 0 AND tile_column = 4]
{SQL} [SELECT tile_data FROM "small" WHERE zoom_level = 6 AND tile_row = 0 AND tile_column = 5]
{SQL} [SELECT tile_data FROM "small" WHERE zoom_level = 6 AND tile_row = 0 AND tile_column = 6]
{SQL} [SELECT tile_data FROM "small" WHERE zoom_level = 6 AND tile_row = 0 AND tile_column = 7]
...
```

**Comment by rouault** [comment]
I cannot reproduce on Linux with sqlite 3.11 from Ubuntu 16.04 or sqlite 3.25.1 compiled from source with -DSQLITE_THREADSAFE=2 . I can't understand why there would be timeout issues in read-only scenarios, but found some post of people in the same situation. Hum.. Your proposed fix could be acceptable, but I think it would also be appopriate to emit an error/warning when SQLITE_BUSY is returned. Do you want to submit a PR ?

**Comment by christapley** [comment]
Hello @rouault,

https://github.com/christapley/gdal/commit/3a29881ae32ed9c895850f3a6db88ac6e9b7aa4b

This is the minimal change I need to fix the issue.

With `SQLITE_READ_TIMEOUT=0` I can see many errors like:
```
ERROR 1: sqlite3_step(SELECT tile_data FROM "100kx100k" WHERE zoom_level = 9 AND tile_row = 0 AND tile_column = 170) failed (SQLITE_BUSY): database is locked
```

With `SQLITE_READ_TIMEOUT=5000` I don't see any errors.

There are many other places in gdal where sqlite3_open is called, do you want the sqlite3_busy_timeout called in all these places also?

**Comment by rouault** [comment]
> This is the minimal change I need to fix the issue.

That would be fine as a pull request. Perhaps rename the config options as SQLITE_BUSY_TIMEOUT as I guess this could also help in read/write scenarios

> There are many other places in gdal where sqlite3_open is called, do you want the sqlite3_busy_timeout called in all these places also?

In a number of cases, this might be a temporary file just opened once. I'd say we might consider adding this in other places as issues arise. I'm still a bit un-easy that timeout situations can happen in read-only scenarios, but probably due to subtelties how sqlite locking work....

**Comment by christapley** [comment]
Hello @rouault, I have changed the config option to SQLITE_BUSY_TIMEOUT and issued a PR.

**Comment by jratike80** [comment]
Would it be worth having a try by making SQLite connection as read-only https://sqlite.org/c3ref/open.html? Then it should at least never make sense to go to RESERVED, PENDING, or EXCLUSIVE locking states https://sqlite.org/lockingv3.html.

**Comment by rouault** [comment]
> Would it be worth having a try by making SQLite connection as read-only

They are already opened as read-only if the GDAL / OGR dataset is open as read-only too, which is the case with the multireadtest application.

**Comment by jratike80** [comment]
Then would it make sense to repeat the test with a database that is set to WAL mode?

**Comment by jratike80** [comment]
Being in WAL mode may even be the reason for the problem https://stackoverflow.com/questions/17115398/database-locked-in-wal-mode-with-only-readers. Using immutable=1 should skip all file locking checks https://sqlite.org/uri.html#uriimmutable.
