### ISSUE TITLE
resampling with gdal_merge.py productes different results depending on compression algorithm of input image?

### ISSUE THREAD

**Issue by wessm** [OSGeo/gdal#1376]
## Expected behavior and actual behavior.

My understanding is that LZW and DEFLATE are lossless compression algorithms, but when I run `gdal_merge` with `-ps` set on the same input image(s) compressed with a those two algorithms, the results look different.

## Steps to reproduce the problem.

Simplified example ("merging" only one image, input data is [here](https://drive.google.com/drive/folders/1LsbOQQJbPSlpnfK2hYvtL-wGDALKTsXG?usp=sharing)):

`gdal_merge.py -o merged_lzw.tif -ps 300 300 lzw.tif`

`gdal_merge.py -o merged_deflate.tif -ps 300 300 deflate.tif`

The resulting images have slight differences, although the input images and parameters are the same.

## Operating system

Ubuntu 16.04 64 bit

## GDAL version and provenance

2.2.2

**Comment by rouault** [comment]
The issue is  that deflate.tif has an internal overview, whereas lzw.tif doesn't, and given the pixel size given, this overview gets selected. So not a software bug

**Comment by wessm** [comment]
ok thx makes sense, didn't know that in this case gdal automatically uses the overview! Is there a way to  tell gdal to ignore the overview and read the full image before resampling?

**Comment by rouault** [comment]
> Is there a way to tell gdal to ignore the overview and read the full image before resampling?

Surprisingly, no, I can't think of an easy one. Well, except doing "gdal_translate in.tif tmp_without_overviews.tif", which doesn't copy the overviews.

**Comment by jratike80** [comment]
How about the -oo OVERVIEW_LEVEL http://erouault.blogspot.com/2014/10/warping-overviews-and-warped-overviews.html?

**Comment by rouault** [comment]
> How about the -oo OVERVIEW_LEVEL http://erouault.blogspot.com/2014/10/warping-overviews-and-warped-overviews.html?

That's a good point I considered, but it should support OVERVIEW_LEVEL=-1 (for main dataset), which it doesn't currently (wouldn't be too hard...)
