### ISSUE TITLE
Issues with gdal_fillnodata.py 

### ISSUE THREAD

**Issue by jvaldezch** [OSGeo/gdal#1380]
I have an image with some no data in the middle as you can see in the following image:

![image](https://user-images.githubusercontent.com/605927/54703462-7bc27180-4afe-11e9-84df-2c118b4a4b51.png)

I want to add 1 pixel on the edges but when using gdal_fillnodata.py on GDAL 2.2.4 there is an issue when using the following command:

`gdal_fillnodata.py -md 1 input.tif output.tif`

![image](https://user-images.githubusercontent.com/605927/54703626-c5ab5780-4afe-11e9-9a98-fb351048e28c.png)

It's only adding 1 pixel on vertical but nothing on horizontal as you can see in the image above. It's only when using a distance of 2 when the script adds pixels on horizontal but now I have 2 pixels on vertical

`gdal_fillnodata.py -md 2 input.tif output.tif`

![image](https://user-images.githubusercontent.com/605927/54704074-b082f880-4aff-11e9-8d45-f2ee6ab90d0a.png)

**Comment by rouault** [comment]
This has been fixed in GDAL master per https://github.com/OSGeo/gdal/issues/1228
