### ISSUE TITLE
Export tiles and keep georef for import

### ISSUE THREAD

**Issue by roya0045** [OSGeo/gdal#1382]
Greetings,

I'm not sure how feasible this is but I was wondering if it would be possible to have the option to export tiles (like the ones made with gdal2tiles) as distinct images. I'm assuming this would be doable by simply using numpy and slicing the image data and stacking them but I was curious if there was a way to preserve the coordinates.

Esri seems to use a tiling method to split up rasters to train their AI models and to reproject the 
output data on the map using the tiles. 

I might be able to do it in python or c++ if someone familiar with tiles could provide some support.

Thanks

**Comment by rouault** [comment]
Looks like you want to use https://www.gdal.org/gdal_retile.html

**Comment by roya0045** [comment]
> Looks like you want to use https://www.gdal.org/gdal_retile.html

Thanks a ton, I completely overlooked that function based on the name, I thought it was used to correct a file rather than export it. 

Would it be better to rename it something like split to tiles?

**Comment by jratike80** [comment]
The original author of the tool has not been limited to thinking that a tile means a very small image and named the script to reflect another situation. In the tutorial https://www.slideshare.net/geosolutions/creating-a-pyramid-with-gdal-reltile-for-serving-with-geoserver original tiles are digital maps or photos covering full mapsheets which typically are something like 10000 by 10000 pixels in size.

There is another utility https://www.gdal.org/gdal2tiles.html that splits to tiles. Gdal_retile does not only split but it can combine as well. If there was a nice illustrated wiki document about what gdal_retile really does we could have a link to that in the main manual page.
