### ISSUE TITLE
vsizip and relative paths to files such as RAT tables

### ISSUE THREAD

**Issue by gweis** [OSGeo/gdal#1385]
## Expected behavior and actual behavior.

gdalinfo /vsizip/aigrid.zip/aigrid/layer/hdr.adf 
-> output RAT table as well

gdalinfo /vsizip/aigrid.zip/aigrid/layer/hdr.adf
-> prints almost all information about grid (including color tables, but not RAT)

turning on CPL_DEBUG reveals:

```
CPLError: CPLError: EOF encountered in /vsizip/aigrid.zip/aigrid/layer/../info/arc.dir after reading 0 bytes while trying to read 32 bytes. File may be corrupt.
CPLError: EOF encountered in /vsizip/aigrid.zip/aigrid/layer/../info/arc.dir after reading 0 bytes while trying to read 32 bytes. File may be corrupt.
```

## Steps to reproduce the problem.

see above. Same problems happens with any zipped data format that relies on additional files found at relative paths.

## Operating system

Repreduced an Linux (RedHat, Ubuntu) and OSX

## GDAL version and provenance

Tested with GDAL 2.2, 2.3 and 2.4

## Additional notes:

One example source code location is in [aigdataset.cpp](https://github.com/OSGeo/gdal/blob/master/gdal/frmts/aigrid/aigdataset.cpp) in method [AIGDataset::ReadRAT](https://github.com/OSGeo/gdal/blob/master/gdal/frmts/aigrid/aigdataset.cpp#L406). 
see https://github.com/OSGeo/gdal/blob/master/gdal/frmts/aigrid/aigdataset.cpp#L417
It tries to locate the AIGrid `info` folder via a relative path. `/../info`. This works fine wen unzipping the dataset first, but it seems the the `vsizip` driver is not interpreting the `..` component of a path.

I am not sure what else is affected by this issue, but I would guess that many other `vsi` drivers don't normalize path`s like this.

**Comment by rouault** [comment]
That rings a bell to me, but I don't think your analysis is right. /vsizip/ has logic to solve ../
I can successfully read a zipped version of https://download.osgeo.org/gdal/data/aig/nzdem/ with
```
$ gdalinfo /vsizip//tmp/nzdem.zip/nzdem/nzdem500/hdr.adf
[...]
Driver: AIG/Arc/Info Binary Grid
Files: /vsizip//tmp/nzdem.zip/nzdem/nzdem500
       /vsizip//tmp/nzdem.zip/nzdem/nzdem500/sta.adf
       /vsizip//tmp/nzdem.zip/nzdem/nzdem500/dblbnd.adf
       /vsizip//tmp/nzdem.zip/nzdem/nzdem500/vat.adf
       /vsizip//tmp/nzdem.zip/nzdem/nzdem500/w001001.adf
       /vsizip//tmp/nzdem.zip/nzdem/nzdem500/log
       /vsizip//tmp/nzdem.zip/nzdem/nzdem500/w001001x.adf
       /vsizip//tmp/nzdem.zip/nzdem/nzdem500/hdr.adf
Size is 2003, 2948
Origin = (2000124.250000000000000,6784310.500000000000000)
Pixel Size = (500.000000000000000,-500.000000000000000)
Corner Coordinates:
Upper Left  ( 2000124.250, 6784310.500) 
Lower Left  ( 2000124.250, 5310310.500) 
Upper Right ( 3001624.250, 6784310.500) 
Lower Right ( 3001624.250, 5310310.500) 
Center      ( 2500874.250, 6047310.500) 
Band 1 Block=256x4 Type=Int16, ColorInterp=Undefined
  Min=0.000 Max=3627.000 
  NoData Value=-32768
<GDALRasterAttributeTable tableType="thematic">
  <FieldDefn index="0">
    <Name>VALUE</Name>
    <Type>0</Type>
    <Usage>5</Usage>
  </FieldDefn>
...
```

I believe the issue is more subtle and lies in the AVCBin driver with virtual files
Can you point to a dataset that exhibits the issue ?

**Comment by gweis** [comment]
Here is one (I have others as well, but this one is probably the easiest to access)

http://environment.gov.au/fed/catalog/search/resource/details.page?uuid=%7B991C36C0-3FEA-4469-8C30-BB56CC2C7772%7D

Hit the Download link / tab on that page and fetch the GRID_xxx.zip (Raster). It's about 60MB in size.
