### ISSUE TITLE
WCS: shift by half the ground size resolution

### ISSUE THREAD

**Issue by tobwen** [OSGeo/gdal#1394]
## Expected behavior and actual behavior.

I expected to download a raster file from a WCS in these corner coordinates: 
```
Upper Left  ( 4000000.000, 3600000.000)
Lower Left  ( 4000000.000, 2650000.000)
Upper Right ( 4700000.000, 3600000.000)
Lower Right ( 4700000.000, 2650000.000)
```

but I got these:
```
Upper Left  ( 3999950.000, 3600050.000)
Lower Left  ( 3999950.000, 2650050.000)
Upper Right ( 4699950.000, 3600050.000)
Lower Right ( 4699950.000, 2650050.000)
```

The result seems to be off by half of the ground resolution, which is 100 m per pixel.

## Steps to reproduce the problem.

```
gdalinfo --config GDAL_HTTP_UNSAFESSL YES "WCS:https://monitor.ioer.de/cgi-bin/wcs?map=V01RG_wcs"
gdalinfo --config GDAL_HTTP_UNSAFESSL YES "WCS:https://monitor.ioer.de/cgi-bin/wcs?map=V01RG_wcs&version=2.0.1&coverage=V01RG_2006_100m"
gdal_translate --config GDAL_HTTP_UNSAFESSL YES "WCS:https://monitor.ioer.de/cgi-bin/wcs?map=V01RG_wcs&REQUEST=GetCoverage&COVERAGE=V01RG_2006_100m" -a_nodata -9998 -of GTiff V01RG_2006_100m.tif
```

License of this dataset: http://www.ioer-monitor.de/fileadmin/Dokumente/PDFs/Nutzungsbedingungen_IOER-Monitor.pdf

## Operating system

Windows 7, 64 bit

## GDAL version and provenance

GDAL 2.5.0dev, released 2019/99/99 (latest one from OSGeo4W)

**Comment by rouault** [comment]
CC @ajolma

**Comment by ajolma** [comment]
There are quite a few options for servers that do not report the grid origin correctly at https://gdal.org/frmt_wcs.html. OriginAtBoundary for example. Are you sure that this is not a case where such an option should not be used?

**Comment by jratike80** [comment]
The extent of the coverage are found from DescribeCoverage result

https://monitor.ioer.de/cgi-bin/wcs?map=V01RG_wcs&service=WCS&version=2.0.1&request=DescribeCoverage&coverageID=V01RG_2006_100m

```
<gml:Envelope srsName="http://www.opengis.net/def/crs/EPSG/0/3035" axisLabels="y x" uomLabels="m m" srsDimension="2">
<gml:lowerCorner>2650000 4000000</gml:lowerCorner>
<gml:upperCorner>3600000 4700000</gml:upperCorner>
</gml:Envelope>
```

In WCS the coverage of a raster file is a GML rectified grid. The origin of the data and data points mean the centre point of the pixel is raster is of the common "pixel is area" type. GDAL reports the extens by the external bounderies (from left border of the left-most pixel to the right border of the right-most pixel). 

I would say that GDAL works in a correct way but the WCS server (seems to be MapServer) may be configured wrong.

**Comment by tobwen** [comment]
Thanks for your ideas, seems like `-oo OriginAtBoundary=TRUE` did it (I think, I can skip _TRUE_), but I'll check it more detailed in some minutes and close this issue then.

But I've figured out some interesting stuff: Once run with with open-option, the XML description file in `.gdal/.cache/` gets the entry `<OriginAtBoundary>TRUE</OriginAtBoundary>`. 

When re-running without this open-option, this entry doesn't get removed or rewritten. So the second time, it works without it. Maybe that's why there's `-oo CLEAR_CACHE` in one of the examples?
