### ISSUE TITLE
WCS: quoted and unquoted ampersand in subdataset

### ISSUE THREAD

**Issue by tobwen** [OSGeo/gdal#1395]
I expected unquoted ampersands only in the `SUBDATASET` name attribute.

```
SUBDATASET_1_NAME=WCS:https://monitor.ioer.de/cgi-bin/wcs?map=V01RG_wcs&amp;&version=2.0.1&coverage=V01RG_2006_100m
```

License of this dataset: http://www.ioer-monitor.de/fileadmin/Dokumente/PDFs/Nutzungsbedingungen_IOER-Monitor.pdf

## Steps to reproduce the problem.

```
gdalinfo --config GDAL_HTTP_UNSAFESSL YES "WCS:https://monitor.ioer.de/cgi-bin/wcs?map=V01RG_wcs"
```

License of this dataset: http://www.ioer-monitor.de/fileadmin/Dokumente/PDFs/Nutzungsbedingungen_IOER-Monitor.pdf

## Operating system

Windows 7, 64 bit

## GDAL version and provenance

GDAL 2.5.0dev, released 2019/99/99 (latest one from OSGeo4W)

**Comment by rouault** [comment]
CC @ajolma 
I also believe we should XML-unquote the WCS name reported in the SUBDATASET_x_NAME metadata

**Comment by ajolma** [comment]
That "\&amp;" originates from the capabilities document 
https://monitor.ioer.de/cgi-bin/wcs?map=V01RG_wcs&service=wcs&request=getcapabilities
OperationsMetadata/HTTP/GET
that is produced by the MapServer in question. Thus it seems to me that the configuration of the server in question is to be blamed.

**Comment by rouault** [comment]
> Thus it seems to me that the configuration of the server in question is to be blamed.

No, the server *has* to do that XML-escaping, otherwise the document would not be XML valid. But I'm surprised this cpl_minixml does not automatically unescape it (it has code to do that...)

**Comment by ajolma** [comment]
The capabilities XML contains "\&amp;amp;", which cpl_minixml unescapes to "\&amp;".

**Comment by rouault** [comment]
> The capabilities XML contains "&amp;amp;", which cpl_minixml unescapes to "&amp;".

ah, sorry I missed that when displaying the capabilities in Firefox. So yes this is a server-side configuration bug.
