### ISSUE TITLE
'*.he5' not recognized as a supported file format.

### ISSUE THREAD

**Issue by QiaoFeng0419** [OSGeo/gdal#1398]
## Expected behavior and actual behavior.

I want to open a GOCI remote sensing data file, but GDAL can't recognize it.

## Steps to reproduce the problem.

The GOCI data is download from [http://222.236.46.45/nfsdb/COMS/GOCI/1.0/2018/02/15/L1B/](GOCI), then i use `gdalinfo COMS_GOCI_L1B_GA_20180215001644.he5`, The problem arises `ERROR 4: COMS_GOCI_L1B_GA_20180215001644.he5 not recognized as a supported file format.`

## Operating system

CentOS 7.5 64 bit

## GDAL version and provenance

GDAL version is 2.4.

**Comment by rouault** [comment]
That works for me. I assume you didn't configure GDAL --with-hdf5 support

**Comment by QiaoFeng0419** [comment]
Thanks. It works. 

First, i try `gdalinfo --formats`, find no hdf5 support. 

Then, i install hdf5 and rebuild gdal with `--with-hdf5`.

And  it can open the .he5 file.
