### ISSUE TITLE
Carto driver doesn't cartodbfy if the SRS is unknown

### ISSUE THREAD

**Issue by ethervoid** [OSGeo/gdal#1399]
## Expected behavior and actual behavior.

I expect to cartodbfy a table when I force the SRS value using `a_srs/t_srs/s_srs` options

## Steps to reproduce the problem.

`ogr2ogr --config CARTO_API_KEY API_KEY_VALUE -a_srs "EPSG:4326" -s_srs "EPSG:4326" -t_srs "EPSG:4326" -lco OVERWRITE=YES -overwrite --config CPL_DEBUG HTTP --config CPL_DEBUG CARTO --debug ON -f Carto "Carto:user" sample_file.csv`

I'm using CSV because it usually doesn't have a defined SRS 

## Operating system

Ubuntu 18.10 64 bit

## GDAL version and provenance

I'm using the last compiled version `2.5.0dev-dde1ecec59-dirty`

I've added [this sample dataset](https://github.com/OSGeo/gdal/files/3018964/sample_dataset.zip) so you can test with it

**Comment by rouault** [comment]
You're example doesn't include -a_srs or -t_srs

**Comment by ethervoid** [comment]
Ok updating it, sorry :)

**Comment by Algunenano** [comment]
Calling with the following parameters:
```
--config CARTO_API_KEY cfd51af386ec59859a1415d51f9b1809c014d369     --config CARTO_HTTPS no     --config CARTO_API_URL http://localhost:8080/user/dev/api/v2/sql  --config CPL_DEBUG HTTP  -overwrite --config CPL_DEBUG CARTO     --debug ON     -f Carto "Carto:dev"   /tmp/sample_dataset.csv -a_srs "EPSG:4326" -s_srs "EPSG:4326" -t_srs "EPSG:4326"
```

When the process reaches `OGRCARTODataSource::ICreateLayer`:
```
(gdb) p bCartoify
$1 = true
(gdb) n
469             if( nSRID != 4326 )
(gdb) p nSRID
$2 = 0
(gdb) p poSpatialRef
$3 = (OGRSpatialReference *) 0x555555917e30
(gdb) p *poSpatialRef
$4 = {_vptr.OGRSpatialReference = 0x7ffff7f4c708 <vtable for OGRSpatialReference+16>, 
  d = std::unique_ptr<OGRSpatialReference::Private> = {get() = 0x555555917e50}}
(gdb) p eGType
$5 = wkbNone
(gdb) p FetchSRSId( poSpatialRef )
$6 = 4326
```

So the issue here is that with CSVs you get `eGType == wkbNone` and that disables `bCartoify`. 

So, adding it as a parameter (`-nlt GEOMETRY`) does the trick:
```
ogr2ogr --config CARTO_API_KEY cfd51af386ec59859a1415d51f9b1809c014d369     --config CARTO_HTTPS no     --config CARTO_API_URL http://localhost:8080/user/dev/api/v2/sql  --config CPL_DEBUG HTTP  -overwrite --config CPL_DEBUG CARTO     --debug ON     -f Carto "Carto:dev"   /tmp/sample_dataset.csv -a_srs "EPSG:4326" -s_srs "EPSG:4326" -t_srs "EPSG:4326" -nlt GEOMETRY

[...]

HTTP: These POSTFIELDS were sent:q=SELECT cdb_cartodbfytable('sample_dataset')&api_key=cfd51af386ec59859a1415d51f9b1809c014d369
CARTO: RunSQL Response:{"rows":[{"cdb_cartodbfytable":"sample_dataset"}],"time":0.91,"fields":{"cdb_cartodbfytable":{"type":"regclass"}},"total_rows":1,"notices":["trigger \"track_updates\" for relation \"sample_dataset\" does not exist, skipping","trigger \"update_the_geom_webmercator_trigger\" for relation \"sample_dataset\" does not exist, skipping","trigger \"test_quota\" for relation \"sample_dataset\" does not exist, skipping","trigger \"test_quota_per_row\" for relation \"sample_dataset\" does not exist, skipping"]}
HTTP: Ended persistent session named 'CARTO:0x55d3ddc18d60'.
GDAL: GDALClose(Carto:dev, this=0x55d3ddc18d60)
CSV: 1 features read on layer 'sample_dataset'.
GDAL: GDALClose(/tmp/sample_dataset.csv, this=0x55d3ddc1a940)
```

I think improving the documentation is enough with something like this:

```
CARTODBFY=YES/NO: Whether the created layer should be "Cartodbifi'ed" (i.e. registered in dashboard). Defaults to YES. Requires the SRID to be 4326 and the geometry type to be defined. See example below for CSV:
```

Then on examples:
```
* Creating a cartodbyed table from a CSV:
`ogr2ogr --config CARTO_API_KEY abcdefghijklmnopqrstuvw -f Carto "Carto:myaccount" dataset.csv -a_srs "EPSG:4326" -s_srs "EPSG:4326" -t_srs "EPSG:4326" -nlt GEOMETRY`
```

I'll create a PR with the doc changes.

**Comment by ethervoid** [comment]
Hum, I see something weird here. Using the sample I provided I'm having some problems:

The provided solution is not working because is duplicating the `the_geom` field, one with `GEOMETRY` field and the other one with `VARCHAR`:

`
HTTP: These POSTFIELDS were sent:q=CREATE TABLE "sample_dataset" ( cartodb_id SERIAL,the_geom Geometry(GEOMETRY,4326),"the_geom" VARCHAR,"tiv_2012" VARCHAR,"policyid" VARCHAR,"statecode" VARCHAR,"county" VARCHAR,"eq_site_limit" VARCHAR,"hu_site_limit" VARCHAR,"fl_site_limit" VARCHAR,"fr_site_limit" VARCHAR,"tiv_2011" VARCHAR,"eq_site_deductible" VARCHAR,"hu_site_deductible" VARCHAR,"fl_site_deductible" VARCHAR,"fr_site_deductible" VARCHAR,"point_latitude" VARCHAR,"point_longitude" VARCHAR,"line" VARCHAR,"construction" VARCHAR,"point_granularity" VARCHAR,PRIMARY KEY (cartodb_id) );DROP SEQUENCE IF EXISTS "sample_dataset_cartodb_id_seq" CASCADE;CREATE SEQUENCE "sample_dataset_cartodb_id_seq" START 1;ALTER SEQUENCE "sample_dataset_cartodb_id_seq" OWNED BY "sample_dataset".cartodb_id;ALTER TABLE "sample_dataset" ALTER COLUMN cartodb_id SET DEFAULT nextval('"sample_dataset_cartodb_id_seq"')&api_key=xxxxf
`

I've used the `-oo GEOM_POSSIBLE_NAMES=the_geom` option with the same result:

`ERROR 1: HTTP error code : 400
ERROR 1: RunSQL Error Message:HTTP error code : 400
CARTO: RunSQL Response:{"error":["column \"the_geom\" specified more than once"]}`

Using the `-select` option looks very cumbersome. Is there any reason that leads to have a duplicate columns for the same field?

**Comment by ethervoid** [comment]
@Algunenano ping pong
