### ISSUE TITLE
WCS: HTTP_PROXY is being ignored

### ISSUE THREAD

**Issue by tobwen** [OSGeo/gdal#1401]
## Expected behavior and actual behavior.
It seems that environment variables `HTTP_PROXY` and `GDAL_HTTP_PROXY` are being ignored at least for WCS reader. 

The download works, even if the local proxyserver doesn't exist at all. Expected it either a warning or an error message.

This might be a cygwin problem, but I've used it in the past. Maybe something has changed?

## Steps to reproduce the problem.

```
export HTTP_PROXY=http://127.0.0.1:1234
gdal_translate --debug on --config GDAL_HTTP_UNSAFESSL YES "WCS:..." -of GTiff test.tif
```

this works as expected:
```
gdal_translate --debug on --config GDAL_HTTP_PROXY "http://127.0.0.1:1234" --config GDAL_HTTP_UNSAFESSL YES "WCS:..." -of GTiff test.tif
```

## Operating system

Mintty with GNU bash, Version 4.4.12(3)-release (x86_64-unknown-cygwin) on Windows 7, 64 bit

## GDAL version and provenance

GDAL 2.5.0dev, released 2019/99/99 (latest one from OSGeo4W)

**Comment by jratike80** [comment]
You closed the ticket, did you notice that there was no issue with GDAL or why?

**Comment by tobwen** [comment]
@jratike80 It seems to work with `http_proxy` (lowercase). So I think, it's an issue caused by my mixing of _MinGW GDAL_ and _cygwin bash_.

There's no way to remove issues in Github, but I didn't want to wipe this, since I wanted to investigate it later.
