### ISSUE TITLE
Is a 512x512 file without internal overview a proper COG ?

### ISSUE THREAD

**Issue by vincentsarago** [OSGeo/gdal#1403]
Hi, I'm a bit confused by the language used in  https://github.com/OSGeo/gdal/blob/4baca75267de027f4f9dfbee44c8e3be0a4efccd/gdal/swig/python/samples/validate_cloud_optimized_geotiff.py#L90-L100

This might be a special case but I have a 512x512 file without internal overview nor internal tiles (because my profile has default 512x512 tile size) and thus the script is not considering my file as a proper cog and telling me the file is greater than 512x512 which it isn't the case

IMO we should replace the `>=512` bit `>512` in L90.

**Comment by vincentsarago** [comment]
edits: 
The scripts tells the file is a proper COG (🤦‍♂️)  but warns about not having internal overview 

```
The following warnings were found:
 - The file is greater than 512xH or Wx512, it is recommended to include internal overviews

output.tif is a valid cloud optimized GeoTIFF
```

**Comment by rouault** [comment]
I'm fine with a PR fixing this warning. > 512 looks good to me
