### ISSUE TITLE
Hardcoded clang warning flag in swig/python/setup.py

### ISSUE THREAD

**Issue by piyushrpt** [OSGeo/gdal#1407]
This is mostly a macports problem, but the root of the issue may lie in 

https://github.com/OSGeo/gdal/blob/master/gdal/swig/python/setup.py#L306-L309

For some convoluted reason, I have to build gdal with gcc on OSX with macports which I'm able to do since all the dependencies like hdf5 /netcdf etc are build with gcc. However, I can't then use port py36-gdal as is (libc++ vs libstdc++ issues for numpy interface) and have to try and use pip to install the bindings. Just setting the compilers to C++ does not seem to solve the problem due to the hardwired clang flags in setup.py

Would it be ok to include a compiler type check to ensure that clang is being used in addition to the existing check for "darwin"? 

## Steps to reproduce the problem.

```
sudo port install gdal +hdf5 +netcdf configure.cxx_stdlib=libstdc++ configure.compiler=macports-gcc-7
```

Followed by:
```
sudo CC=g++ CXX=g++ pip-3.6 install GDAL==2.3.2
```

Results in 

```
cc1plus: error: -Werror=unused-command-line-argument-hard-error-in-future: no option -Wunused-command-line-argument-hard-error-in-future
```

## Operating system

OS X 10.13 with Macports 2.4.0

## GDAL version and provenance

GDAL 2.3.2 from Macports

**Comment by rouault** [comment]
If you can come up with something that better works that's welcome. I did some hacks in that area completely in the blind since I don't have a Mac so as to fix failed Travis-CI OSX builds...
