### ISSUE TITLE
GeoPackage map shifted after zoom in

### ISSUE THREAD

**Issue by arturredzko** [OSGeo/gdal#1410]
I'm testing the latest GDAL using the library directly in my project and comparing via QGIS latest release. Testing the GeoPackage demo Topographic Web Map, raster data from https://www.lantmateriet.se/sv/Kartor-och-geografisk-information/geodataprodukter/topografisk-webbkarta/?steg=4, either reference - SWEREF 99 TM or - Web Mercator I see shifted map after zoom in. Full extent shows
![image](https://user-images.githubusercontent.com/4385342/55393073-d5825d00-553c-11e9-8549-c52aec17ac8c.png)
zoom in into center shows
![image](https://user-images.githubusercontent.com/4385342/55393113-eaf78700-553c-11e9-8ee1-2c780e43e518.png)
next click on Stockholm - the map disappears. I have to drag around to find a tile. Testing other datasets I don't get such problems.
Please check if it's a dataset problem or GDAL issue. 
Thanks Artur

**Comment by rouault** [comment]
I believe it is a dataset problem (or "feature" maybe given that it is labelled as a demo product). The dataset is very sparse. I found that if you zoom on the city of Gävle, you'll get tiles at all zoom levels and I don't perceive any shift.

The sparse character of the dataset can be show with
```
$ echo "select zoom_level, min(tile_column), max(tile_column), min(tile_row), max(tile_row), count(*) from topowebb group by zoom_level order by zoom_level;" | sqlite3 6722783_609090_sweref99tm.gpkg
0|0|0|0|0|1
1|0|1|0|1|4
2|0|3|0|3|16
3|4|7|4|7|16
4|8|11|8|11|16
5|20|23|20|23|16
6|44|47|40|47|32
7|92|95|84|91|32
8|184|191|172|179|64
9|368|383|348|355|128
10|740|763|696|711|384
11|1484|1527|1392|1423|1408
12|2968|3051|2788|2847|5040
13|5940|6099|5580|5695|18560
```

**Comment by arturredzko** [comment]
Thanks for info.

**Comment by arturredzko** [comment]
One more issue about performance upon panning and zooming when using GeoPackage. Panning and zooming is choppy and unpleasant - generally slow. Comparison to another manufacturer (using same sample data) is “blazing fast” and responsive (I saw screen recording from ArcGIS Pro). Is there any way to improve display performance of reading tiles from sqlite? I assume that reading is done in one sql query (or many) and no threading can be used ?

**Comment by rouault** [comment]
yes, GDAL GPKG driver isn't threaded internally. I believe the issue however is more in QGIS than in GDAL, since with the same GDAL build (2.4), with ancient QGIS 2.8, rendering is fast, and with QGIS 3.4, it is indeed significantly slower.
