### ISSUE TITLE
UKOOA P1/90 R records are mangled

### ISSUE THREAD

**Issue by kernant** [OSGeo/gdal#1411]
I am running into the same issue described 3 years ago here https://trac.osgeo.org/gdal/ticket/6276

GDAL is not reading the R record correctly for the OKOOA P1/90 format.

I've attached a test file to reproduce. Using V 2.2.3 on Ubuntu 16

[test.zip](https://github.com/OSGeo/gdal/files/3033971/test.zip)

**Comment by rouault** [comment]
@kernant If you're interested in funding improvements in that area, I could be available. See http://www.spatialys.com/en/contact/ for my contact

**Comment by rouault** [comment]
That driver has been retired and moved to a repository for unsupported drivers: https://github.com/OSGeo/gdal-extra-drivers/blob/master/doc/segukooa.rst . Closing
