### ISSUE TITLE
gdal configure should switch from pg_config to pkg-config

### ISSUE THREAD

**Issue by tigerfoot** [OSGeo/gdal#1412]
## Expected behavior and actual behavior.

Actually .configure (configure.ac) is used to find pg_config program to determine PostgreSQL header of libpq
With now pg 11, PostgreSQL would like to prefer to use pkg-config libpq for client part (which gdal is, right?) and reserve the usage of pg_config to backend (extension and so)

## Steps to reproduce the problem.

Building with as BuildRequires: pkg-config(libpq) give no pg_config found
Ideally --with-pg should accept result of 
```
pkg-config --libs --cflags libpq
-I/usr/include/pgsql -lpq
```

## Operating system

openSUSE Tumbleweed (20190402)

## GDAL version and provenance

2.4.1 released tarball

What would be you opinion on that ?

**Comment by rouault** [comment]
I'm fine with that

**Comment by tigerfoot** [comment]
But looking at the code, I'm seeing actually --includedir-server did we need that in gdal ?

**Comment by rouault** [comment]
> I'm seeing actually --includedir-server did we need that in gdal ?

I don't have in mind why we would need it. As far as I can see, GDAL only includes libpq-fe.h

**Comment by tigerfoot** [comment]
Ok let see if I can propose a patch for this.

**Comment by tigerfoot** [comment]
Seems that ugly patch is able to have PostgreSQL yes and building (need more tests tomorrow).
I'm so sorry but not really in my confort zone with configure.ac

```
diff -rup a/configure.ac b/configure.ac
--- a/configure.ac      2019-03-15 13:30:02.000000000 +0100
+++ b/configure.ac      2019-04-02 21:21:00.544544968 +0200
@@ -1252,7 +1252,7 @@ AC_ARG_WITH(pg,
               [Include PostgreSQL GDAL/OGR Support (ARG=path to pg_config)]),,)

 if test "x$with_pg" = "xyes" -o "x$with_pg" = "x" ; then
-  AC_PATH_PROG(PG_CONFIG, pg_config, no)
+  AC_PATH_PROG(PG_CONFIG, pkg-config, no)
 else
   PG_CONFIG=$with_pg
 fi
@@ -1268,24 +1268,25 @@ if test "x$PG_CONFIG" = "xno" ; then
   AC_MSG_RESULT([no])

 else
-  if test -d ${PG_CONFIG} ; then
-      AC_MSG_RESULT([no])
-      AC_MSG_ERROR([--with-pg argument is a directory.  It should be the path to the pg_config script, often somewhere like /usr/local/pgsql/bin/pg_config.])
-  fi
-
-  if test \! -x ${PG_CONFIG} ; then
-      AC_MSG_RESULT([no])
-      AC_MSG_ERROR([--with-pg argument is a not an executable file.  It should be the path to the pg_config script, often somewhere like /usr/local/pgsql/bin/pg_config.])
-  fi
+#  if test -d ${PG_CONFIG} ; then
+#      AC_MSG_RESULT([no])
+#      AC_MSG_ERROR([--with-pg argument is a directory.  It should be the path to the pg_config script, often somewhere like /usr/local/pgsql/bin/pg_config.])
+#  fi
+
+#  if test \! -x ${PG_CONFIG} ; then
+#      AC_MSG_RESULT([no])
+#      AC_MSG_ERROR([--with-pg argument is a not an executable file.  It should be the path to the pg_config script, often somewhere like /usr/local/pgsql/bin/pg_config.])
+#  fi

   AC_MSG_RESULT([yes])

-  AC_CHECK_LIB(pq,PQconnectdb,HAVE_PG=yes,HAVE_PG=no,-L`$PG_CONFIG --libdir`)
+#  AC_CHECK_LIB(pq,PQconnectdb,HAVE_PG=yes,HAVE_PG=no)

-  if test "${HAVE_PG}" = "yes" ; then
-    LIBS=-L`$PG_CONFIG --libdir`" -lpq $LIBS"
-    PG_INC=-I`$PG_CONFIG --includedir`" -I"`$PG_CONFIG --includedir-server`
-  fi
+#  if test "${HAVE_PG}" = "yes" ; then
+    HAVE_PG="yes"
+    LIBS="`pkg-config --libs libpq`"
+    PG_INC="`pkg-config --cflags --libs libpq`"
+#  fi

 fi
```
btw this is against 2.4.1 tarball not master
but with some advice, I can certainly make it commitable I guess :-)

**Comment by rouault** [comment]
There are more idiomatic uses of pkg_config elsewhere in configure.ac, like
```

elif test "$with_mongocxxv3" = "yes" -o "$with_mongocxxv3" = "" ; then

  PKG_PROG_PKG_CONFIG([0.21])
  PKG_CHECK_MODULES([MONGOCXXV3], [libmongocxx >= 3.4.0], [MONGOCXXV3_ENABLED=yes], [MONGOCXXV3_ENABLED=no])

  if test "$MONGOCXXV3_ENABLED" = "no" -a "$with_mongocxxv3" = "yes" ; then
    AC_MSG_ERROR([mongocxxv3 requested but no found])
  fi

fi

AC_SUBST(MONGOCXXV3_ENABLED, $MONGOCXXV3_ENABLED)
AC_SUBST(MONGOCXXV3_LIBS, $MONGOCXXV3_LIBS)
AC_SUBST(MONGOCXXV3_CFLAGS, $MONGOCXXV3_CFLAGS)
```

**Comment by tigerfoot** [comment]
Thanks for the pointer. 
Now a subsidiary question. Shall we let the code pg_conf as  it is, and introduce a --with-libpq ?
The advantage I see would be that downstream users will still have their package build toolchain working as it was, and others can use the new flags ?
And dropping --with-pg later on a major version ...

**Comment by rouault** [comment]
> Shall we let the code pg_conf as it is, and introduce a --with-libpq ?

Seems overkill. Our configure.ac is already complicated enough. Perhaps error out if the value of $with_pg is different of empty string, yes or no

**Comment by tigerfoot** [comment]
Ok then my patch is looking like this and see to work

```patch
diff -rup a/configure.ac b/configure.ac
--- a/configure.ac      2019-03-15 13:30:02.000000000 +0100
+++ b/configure.ac      2019-04-03 13:52:58.786937941 +0200
@@ -1249,12 +1249,10 @@ PG_CONFIG=no
 
 AC_ARG_WITH(pg,
            AS_HELP_STRING([--with-pg[=ARG]],
-              [Include PostgreSQL GDAL/OGR Support (ARG=path to pg_config)]),,)
+              [Include PostgreSQL GDAL/OGR Support (ARG=yes,no)]),,)

 if test "x$with_pg" = "xyes" -o "x$with_pg" = "x" ; then
-  AC_PATH_PROG(PG_CONFIG, pg_config, no)
-else
-  PG_CONFIG=$with_pg
+  PG_CONFIG=yes
 fi

 AC_MSG_CHECKING([for PostgreSQL])
@@ -1268,23 +1266,18 @@ if test "x$PG_CONFIG" = "xno" ; then
   AC_MSG_RESULT([no])

 else
-  if test -d ${PG_CONFIG} ; then
-      AC_MSG_RESULT([no])
-      AC_MSG_ERROR([--with-pg argument is a directory.  It should be the path to the pg_config script, often somewhere like /usr/local/pgsql/bin/pg_config.])
-  fi
-
-  if test \! -x ${PG_CONFIG} ; then
-      AC_MSG_RESULT([no])
-      AC_MSG_ERROR([--with-pg argument is a not an executable file.  It should be the path to the pg_config script, often somewhere like /usr/local/pgsql/bin/pg_config.])
-  fi

   AC_MSG_RESULT([yes])

-  AC_CHECK_LIB(pq,PQconnectdb,HAVE_PG=yes,HAVE_PG=no,-L`$PG_CONFIG --libdir`)
+#  AC_CHECK_LIB(pq,PQconnectdb,HAVE_PG=yes,HAVE_PG=no,-L`$PG_CONFIG --libdir`)
+  PKG_PROG_PKG_CONFIG([0.21])
+  PKG_CHECK_MODULES([libpq], [libpq >= 9.4], [HAVE_PG=yes], [HAVE_PG=no])
+

   if test "${HAVE_PG}" = "yes" ; then
-    LIBS=-L`$PG_CONFIG --libdir`" -lpq $LIBS"
-    PG_INC=-I`$PG_CONFIG --includedir`" -I"`$PG_CONFIG --includedir-server`
+    LIBS="`pkg-config --libs libpq` $LIBS"
+    PG_LIB="`pkg-config --libs libpq`"
+    PG_INC="`pkg-config --cflags --libs libpq`"
   fi

 fi
@@ -1293,6 +1286,7 @@ AC_SUBST(HAVE_PG,$HAVE_PG)
 AC_SUBST(PG_INC,$PG_INC)
 AC_SUBST(PG_LIB,$PG_LIB)

+
 dnl ---------------------------------------------------------------------------
 dnl Check if we should build with GRASS support.
 dnl ---------------------------------------------------------------------------
```

Is this start to look like acceptable ?

**Comment by rouault** [comment]
Not easy to comment line by line when this is not a PR
* AC_MSG_RESULT([yes]) --> does not look appropriate until pkgconfig has succeeded. Should be in if test "${HAVE_PG}" = "yes" ; then case. Or perhaps this AC_MSG_CHECKING / AC_MSG_RESULT can be completely removed since I guess PKG_CHECK_MODULES has its own success/failure output
* I bet libpq >= 9.4 requirement is stronger than we need
* If you do PKG_CHECK_MODULES([PQ], [libpq], [HAVE_PG=yes], [HAVE_PG=no]), then you should get PQ_LIBS and PQ_CFLAGS environment variable automatically set (thus not needing to call pkg-config --libs/--cflags)

**Comment by tigerfoot** [comment]
Hi Even, thanks for your input, especially about the PKG_CHECK_MODULES, I will try today to rearrange the patch and open a PR for it.
libpq >= 9.4 is now the minimal supported version from PostgreSQL community side (all older are unsupported, but I can lower it to 9.1 is desired)

**Comment by AndyColson** [comment]
I cannot build 3.0 with PG driver anymore.


`configure:28513: checking for PostgreSQL
configure:28576: checking for pkg-config
configure:28594: found /usr/bin/pkg-config
configure:28606: result: /usr/bin/pkg-config
configure:28631: checking pkg-config is at least version 0.21
configure:28634: result: yes
configure:28645: checking for PQ
configure:28653: $PKG_CONFIG --exists --print-errors "libpq > 9.1"
configure:28656: $? = 0
configure:28671: $PKG_CONFIG --exists --print-errors "libpq > 9.1"
configure:28674: $? = 0
configure:28710: result: yes
configure:28720: checking for PQconnectdb in -lpq
configure:28745: gcc -o conftest -DHAVE_AVX_AT_COMPILE_TIME -DHAVE_SSSE3_AT_COMPILE_TIME -DHAVE_SSE_AT_COMPILE_TIME -O2 -fPIC -flto -fvisibility=hidden   -flto conftest.c -lpq   >&5
/usr/lib64/gcc/x86_64-slackware-linux/5.5.0/../../../../x86_64-slackware-linux/bin/ld: cannot find -lpq
collect2: error: ld returned 1 exit status
configure:28745: $? = 1
`

pkg-config --libs libpq
`
-L/usr/local/pg11/lib -lpq
`

If I compile with:
`gcc test.c -L/usr/local/pg11/lib -lpq`

It works, without the -L it fails.

**Comment by AndyColson** [comment]
Ok, found it:

~ line 1580 in configure.ac, teh AC_CHECK_LIB needs an extra arguement, like this:
`AC_CHECK_LIB(pq,PQconnectdb,HAVE_PG=yes,HAVE_PG=no,$PG_LIB)`

Need to add the $PG_LIB

**Comment by rouault** [comment]
@AndyColson Can you please open a new ticket about that regression ? Another potential fix is to change LIBS="${PG_LIBS}" to LIBS="${PG_LIB}" I believe

**Comment by AndyColson** [comment]
`LIBS="${PG_LIBS}" to LIBS="${PG_LIB}"`

Yep, confirmed to work.  You'd really like me to open a ticket to delete a single character?  I can.  Just wanted to verify.

**Comment by rouault** [comment]
> You'd really like me to open a ticket to delete a single character?

yes, makes it easier to track things

**Comment by posikifi** [comment]
Hi!
I'm not sure if this is relevant for this bug, I just want to document somewhere about my findings with RHEL 7.7 and compiling GDAL 3.0.1 with PostgreSQL drivers:

For some reason (unknow for me), PostgreSQL 11 is not adding it's pkg-config files locations (like libpq.pc) to standard pkg-config file directories. But if you define variable PKG_CONFIG_PATH, then compiling with PostgreSQL drivers will work.

Listing pkg-config libraries:
`pkg-config --list-all`

Setting PKG_CONFIG_PATH:
`export PKG_CONFIG_PATH=/usr/pgsql-11/lib/pkgconfig/`

P

**Comment by TimJMartin** [comment]
@posikifi I am running into this problem when trying to build GDAL for Amazon Lambda so using https://github.com/RemotePixel/amazonlinux as a great starting point. So I modified the Dockerfile to do

```yum install -y postgresql-devel```

And the Dockerfile already had

ENV PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig/

When it tries to build it still gets PostgreSQL support no. When I run

```pkg-config --list-all```

It is still not listed and the folder /usr/pgsql does not exist.

Can you help explain how you successfully did it?

**Comment by vincentsarago** [comment]
@TimJMartin 
I'm going to add `pg` to https://github.com/RemotePixel/amazonlinux

FYI: when doing `yum install -y postgresql-devel` it install the lib to something like `/usr/lib` which is then not referenced by `ENV PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig/` and thus not found by GDAL at compile time (and also not shipped with the lambda package)

**Comment by TimJMartin** [comment]
@vincentsarago sounds brilliant. Will keep on eye on  [issue](https://github.com/RemotePixel/amazonlinux/issues/23)
