### ISSUE TITLE
Inconsistent gdal_pansharpen.py Results

### ISSUE THREAD

**Issue by cstutts** [OSGeo/gdal#1413]
Source Pan: WorldView-3 PAN
Source MSI (1): 8-Band (CB B G Y R RE N1 N2) WorldView-3 MSI
Source MSI (2): 3-Band (R G B) Subset from the same WorldView-3 Source MSI (1)

ColorInterp is Undefined (0) for each band. Each band are float32 reflectance values from 0 to 1

I get different RGB results in the pan_sharpened image using source MSI (1) versus source MSI (2). See Image. Source (2) produces higher more vibrant vegetation pixel values. Why are the results not the same for the RGB bands?

## Steps to reproduce the problem.

gdal_pansharpen [Source Pan] [Source MSI (1)] [Output File] -of GTiff -r cubic -threads ALL_CPUS -co COMPRESS=LZW -co TILED=YES -co INTERLEAVE=BAND

gdal_pansharpen [Source Pan] [Source MSI (2)] [Output File] -of GTiff -r cubic -threads ALL_CPUS -co COMPRESS=LZW -co TILED=YES -co INTERLEAVE=BAND

Load results in QGIS

## Operating system

Ubuntu 18.04 64 bit through Windows 10 WSL

## GDAL version and provenance

GDAL 2.4.0, released 2018/12/14

**Comment by rouault** [comment]
It is expected that the result is different due to how the Brovey algorithm detailed at https://gdal.org/gdal_vrttut.html#gdal_vrttut_pansharpen works:
```
pseudo_panchro[pixel] = sum(weight[i] * spectral[pixel][i] for i=0 to nb_spectral_bands-1)
ratio = panchro[pixel] / pseudo_panchro[pixel]
for i=0 to nb_spectral_bands-1:
    output_value[pixel][i] = input_value[pixel][i] * ratio
```
The default weight[i] is 1. / nb_spectral_bands

**Comment by cstutts** [comment]
Interesting. Thanks Evan.  Looks like someone has already gone through the trouble of calculating the weights for WV-3 MSI. https://pdfs.semanticscholar.org/ae82/ce17126f19ff8235f955d43e4e6fb2082073.pdf. Using these weights [0.005,0.142,0.209,0.144,0.234,0.157,0.116,0], I get a result that appears like the original MSI.
