### ISSUE TITLE
Segmentize causes IllegalArgumentException

### ISSUE THREAD

**Issue by martinfleis** [OSGeo/gdal#1414]
## Expected behavior and actual behavior.

I was using this script for couple of months without an issue under GDAL 2.3.3 under OSX an Ubuntu. After an update to 2.4.1, it raises WKTReadingError in certain cases, like the one in the example. Version of shapely does not affect the result. I think it is related to bug fix of #1341 .

## Steps to reproduce the problem.

Example in python:

    from osgeo import ogr
    import geopandas as gpd
    from shapely.wkt import loads

    wkt = 'POLYGON ((-743600.5992165749 -1042879.009361613, -743600.5991537668 -1042879.029354426, -743600.3691723208 -1042879.879377964, -743600.5491980131 -1042879.919356675, -743606.0091980109 -1042881.359347264, -743606.1891448292 -1042881.379352514, -743606.3691495601 -1042880.679358713, -743606.3791731107 -1042880.649348811, -743607.7291709057 -1042875.399400083, -743607.5891573754 -1042875.349418439, -743607.3591862218 -1042875.259399635, -743607.129148243 -1042875.179382119, -743606.8891414138 -1042875.08939864, -743606.6591702852 -1042874.999379823, -743602.1491469285 -1042873.319389059, -743602.1191552617 -1042873.429392017, -743602.1191633532 -1042873.449375061, -743600.5992165749 -1042879.009361613))'
    geom = ogr.CreateGeometryFromWkt(wkt)  # create ogr geometry
    geom.Segmentize(2)  # densify geometry by 2 metres
    wkt2 = geom.ExportToWkt()  # ogr geometry to wkt
    new = loads(wkt2) 

## Operating system

macOS 10.14.4, Ubuntu 18.04 64 bit

## GDAL version and provenance

2.3.3 version works
2.4.1 version does not
both from conda-forge

**Comment by rouault** [comment]
As a potential workaround, you could call geom.CloseRings() after Segmentize()
