### ISSUE TITLE
cpl_json_header.h: No such file or directory

### ISSUE THREAD

**Issue by Gpinchon** [OSGeo/gdal#1429]
## Expected behavior and actual behavior.

Should compile normally, stops at gdaldataset.cpp:55:10

## Steps to reproduce the problem.

Run configure with the options specified here : https://trac.osgeo.org/gdal/wiki/BuildingOnUnixWithMinimizedDrivers
Try to make gdal

## Operating system

Windows 7 x64, MINGW64 via MSYS2

## GDAL version and provenance

Cloned from Github, changeset 6729db1

**Comment by mloskot** [comment]
First, the Wiki page may be  out of date.

You need to inspect compiler command line and verify there is `-I` that points to location of the `port` directory.
Then, check if full build is successful.
Then, add `--without-*` flags one by one verifying the build.

**Comment by rouault** [comment]
Is /d/code/gdal/gdal/port a normal path for the MSYS g++ compiler ? If so, it should fine cpl_json_header.h in it
And what is the exact error message ? gdaldataset.cpp doesn't directly include cpl_json_header.h

**Comment by mloskot** [comment]
Assuming `-I/d/code/gdal/gdal/port` is correct path for MinGW compiler, then all these existing `#include`-s should resolve without problems

```
./apps/gdalinfo_lib.cpp:#include "cpl_json_header.h"
./frmts/eeda/eeda.h:#include "cpl_json_header.h"
./ogr/ogrfeature.cpp:#include "cpl_json_header.h"
./ogr/ogrsf_frmts/amigocloud/ogr_amigocloud.h:#include "cpl_json_header.h"
./ogr/ogrsf_frmts/carto/ogr_carto.h:#include "cpl_json_header.h"
./ogr/ogrsf_frmts/couchdb/ogr_couchdb.h:#include "cpl_json_header.h"
./ogr/ogrsf_frmts/elastic/ogr_elastic.h:#include "cpl_json_header.h"
./ogr/ogrsf_frmts/geojson/ogrgeojsonreader.h:#include "cpl_json_header.h"
./ogr/ogrsf_frmts/geojson/ogrgeojsonutils.h:#include "cpl_json_header.h"
./ogr/ogrsf_frmts/geojson/ogrgeojsonwriter.h:#include "cpl_json_header.h"
./ogr/ogrsf_frmts/gmlas/ogrgmlasreader.cpp:#include "cpl_json_header.h"
./port/cpl_json.cpp:#include "cpl_json_header.h"
```

**Comment by Gpinchon** [comment]
Small update, when trying to configure without flag, it fails when trying to find json-c/json.h
Which is strange because configure finds ljson-c, and json-c/json.h is present in C:\msys64\mingw64\include\json-c\
The error message :
```
checking for json_object_set_serializer in -ljson-c... yes
using pre-installed libjson-c
configure: error: could not find json-c/json.h
```

**Comment by mloskot** [comment]
Run `./configure` with `--with-libjson-c=internal`

**Comment by Gpinchon** [comment]
Sidenote, adding this to configure fixes the issue
```
  elif test -f "/mingw64/include/json-c/json.h"; then
    JSON_INCLUDE="-I/usr/local/include/json-c"
```

**Comment by Gpinchon** [comment]
When trying to build with option --with-libjson-c=internal, it fails on cpl_conv.cpp with this error message :
```
libtool: warning: libobj name 'libxml2 -DHAVE_LIBXML2 -DHAVE_CRYPTOPP -c -o cpl_conv.lo cpl_conv.lo' may not contain shell special characters.
rm: unknown option -- D
Try 'rm --help' for more information.
g++.exe: error: cpl_conv.o: No such file or directory
g++.exe: fatal error: no input files
compilation terminated.
```

**Comment by Gpinchon** [comment]
When trying to build with option --with-libjson-c=internal, it fails on cpl_conv.cpp with this error message :
```
C:/msys64/usr/bin/sh.exe /d/code/gdal/gdal/libtool --mode=compile --silent --tag=CXX g++ -I/d/code/gdal/gdal/port -I/d/code/gdal/gdal/gcore -I/d/code/gdal/gdal/alg -I/d/code/gdal/gdal/ogr -I/d/code/gdal/gdal/ogr/ogrsf_frmts -I/d/code/gdal/gdal/gnm -I/d/code/gdal/gdal/apps -Weffc++ -Wold-style-cast -DHAVE_AVX_AT_COMPILE_TIME -DHAVE_SSSE3_AT_COMPILE_TIME -DHAVE_SSE_AT_COMPILE_TIME -g -O2 -DSUPPORTS_WMAIN  -Wall -Wextra -Winit-self -Wunused-parameter -Wformat -Werror=format-security -Wno-format-nonliteral -Wlogical-op -Wshadow -Werror=vla -Wdate-time -Wnull-dereference -Wduplicated-cond -Wextra-semi -Wfloat-conversion -Wmissing-declarations -Wnon-virtual-dtor -Woverloaded-virtual -fno-operator-names -Wzero-as-null-pointer-constant -Wsuggest-override -Wimplicit-fallthrough  -DGNM_ENABLED -DDONT_DEPRECATE_SPRINTF -I/d/code/gdal/gdal/port -IC:/msys64/mingw64/include/openjpeg-2.3 -I/mingw64/include  -DGDAL_COMPILATION      -I/mingw64/include -I/d/code/gdal/gdal/ogr/ogrsf_frmts/geojson/libjson  -DINST_DATA=\"/mingw64/share/gdal\" -DHAVE_CURL -DHAVE_LIBZ -I/mingw64/include/libxml2 -DHAVE_LIBXML2 -DHAVE_CRYPTOPP -c -o cpl_conv.lo cpl_conv.cpp
libtool: warning: libobj name 'libxml2 -DHAVE_LIBXML2 -DHAVE_CRYPTOPP -c -o cpl_conv.lo cpl_conv.lo' may not contain shell special characters.
rm: unknown option -- D
Try 'rm --help' for more information.
g++.exe: error: cpl_conv.o: No such file or directory
g++.exe: fatal error: no input files
compilation terminated.
```

**Comment by mloskot** [comment]
I don't use MinGW myself, so zero experience here but there possibly is an issue in this toolset, see https://stackoverflow.com/questions/9330550/compiling-sqlite3-in-mingw

**Comment by Gpinchon** [comment]
So, after switching to MSYS2's make instead of MINGW64's, it successfully compiled... Until when it tried to link everything together... Maybe replacing explicit .o by wildcards would fix this issue which is bound to happen on some systems.
```
ar r /d/lgdal/libgdal.a /d/lgdal/frmts/o/*.o /d/lgdal/gcore/*.o /d/lgdal/port/*.o /d/lgdal/alg/*.o /d/lgdal/apps/commonutils.o /d/lgdal/apps/gdalinfo_lib.o /d/lgdal/apps/gdal_translate_lib.o /d/lgdal/apps/gdalwarp_lib.o /d/lgdal/apps/ogr2ogr_lib.o /d/lgdal/apps/gdaldem_lib.o /d/lgdal/apps/nearblack_lib.o /d/lgdal/apps/gdal_grid_lib.o /d/lgdal/apps/gdal_rasterize_lib.o /d/lgdal/apps/gdalbuildvrt_lib.o /d/lgdal/ogr/ogrsf_frmts/o/*.o /d/lgdal/third_party/o/*.o ./ogr/ogrgeometryfactory.o ./ogr/ogrpoint.o ./ogr/ogrcurve.o ./ogr/ogrlinestring.o ./ogr/ogrlinearring.o ./ogr/ogrpolygon.o ./ogr/ogrtriangle.o ./ogr/ogrutils.o ./ogr/ogrgeometry.o ./ogr/ogrgeometrycollection.o ./ogr/ogrmultipolygon.o ./ogr/ogrsurface.o ./ogr/ogrpolyhedralsurface.o ./ogr/ogrtriangulatedsurface.o ./ogr/ogrmultipoint.o ./ogr/ogrmultilinestring.o ./ogr/ogrcircularstring.o ./ogr/ogrcompoundcurve.o ./ogr/ogrcurvepolygon.o ./ogr/ogrcurvecollection.o ./ogr/ogrmulticurve.o ./ogr/ogrmultisurface.o ./ogr/ogr_api.o ./ogr/ogrfeature.o ./ogr/ogrfeaturedefn.o ./ogr/ogrfeaturequery.o ./ogr/ogrfeaturestyle.o ./ogr/ogrfielddefn.o ./ogr/ogrspatialreference.o ./ogr/ogr_srsnode.o ./ogr/ogr_fromepsg.o ./ogr/ogrct.o ./ogr/ogr_srs_esri.o ./ogr/ogr_srs_pci.o ./ogr/ogr_srs_usgs.o ./ogr/ogr_srs_dict.o ./ogr/ogr_srs_panorama.o ./ogr/ogr_srs_ozi.o ./ogr/ogr_srs_erm.o ./ogr/swq.o ./ogr/swq_expr_node.o ./ogr/swq_parser.o ./ogr/swq_select.o ./ogr/swq_op_registrar.o ./ogr/swq_op_general.o ./ogr/ogr_srs_xml.o ./ogr/ograssemblepolygon.o ./ogr/ogr2gmlgeometry.o ./ogr/gml2ogrgeometry.o ./ogr/ogr_expat.o ./ogr/ogrpgeogeometry.o ./ogr/ogrgeomediageometry.o ./ogr/ogr_geocoding.o ./ogr/ogrgeomfielddefn.o ./ogr/ograpispy.o ./ogr/ogr_xerces.o ./ogr/ogr_geo_utils.o ./ogr/ogr_proj_p.o
/bin/sh: /mingw64/bin/ar: Argument list too long
make[1]: *** [GNUmakefile:58: /d/lgdal/libgdal.a] Error 126
```

**Comment by mloskot** [comment]
> `Argument list too long`

This seems to be another MinGW issue and it is known to happen for `ar` as well as `g++` and other commands.

If you look at  this [mingw build gdal 2.1.2](https://translate.googleusercontent.com/translate_c?depth=1&rurl=translate.google.com&sl=auto&sp=nmt4&tl=en&u=https://www.cnblogs.com/oloroso/p/6856910.html&xid=17259,15700023,15700186,15700191,15700253,15700256,15700259&usg=ALkJrhhkn8wZnO8wStMQVHSkIpLDze-ZFQ) (translation to English), you will learn that manual split of `GDAL_OBJ` list and other modification of commands is required.

Other that that, I've run our of ideas apart from using MSVC as native on Windows, instead of MinGW alternative.
BTW, you may also try `./configure --without-libtool`

**Comment by Gpinchon** [comment]
I tried  `./configure --without-libtool` but still got the same issue.
Shouldn't these modifications on `GDAL_OBJ `be done in the library ? Why not use intermediate .o instead of doing this huge ar line ?
I can't really use MSVC as I am trying to use GDAL in a unix project, so I was trying to include it as a submodule, build a minimal version of it and then link with the generated .a
Anyway, too Argument list too long is an other issue so I will close this issue I think

**Comment by Gpinchon** [comment]
Was an issue with MINGW64 make, uninstalling it and using MSYS2 make instead fixes the issue.

**Comment by Gpinchon** [comment]
Update concerning this error :
```
In file included from cpl_json.cpp:32:
cpl_json_header.h:36:10: fatal error: json.h: No such file or directory
```

I am trying to use mingw32-make (because using MSYS2 make created other issues later) and this issue persists. The strange thing is that when running the compilation line from MSYS2 bash, the file compiles properly and the rest of the module compiles without issue if I re-launch mingw32-make.
Though, afterwards I get exactly the same issue with all other modules...

Apparently, when using mingw32-make with your makefiles, something keeps g++ from finding any local includes even though their path are specified using `-I` flag... Not sure if I should open a ticket on MSYS2 project instead of here...

Can you reproduce this issue ?
All packages are updated to the latest current version through Pacman.

The compilation line that won't run in mingw32-make :
```
g++ -I/d/code/gdal/gdal/port -I/d/code/gdal/gdal/gcore -I/d/code/gdal/gdal/alg -I/d/code/gdal/gdal/ogr -I/d/code/gdal/gdal/ogr/ogrsf_frmts -I/d/code/gdal/gdal/gnm -I/d/code/gdal/gdal/apps -Weffc++ -Wold-style-cast -DHAVE_AVX_AT_COMPILE_TIME -DHAVE_SSSE3_AT_COMPILE_TIME -DHAVE_SSE_AT_COMPILE_TIME -g -O2 -fPIC -fvisibility=hidden -DSUPPORTS_WMAIN  -Wall -Wextra -Winit-self -Wunused-parameter -Wformat -Werror=format-security -Wno-format-nonliteral -Wlogical-op -Wshadow -Werror=vla -Wdate-time -Wnull-dereference -Wduplicated-cond -Wextra-semi -Wfloat-conversion -Wmissing-declarations -Wnon-virtual-dtor -Woverloaded-virtual -fno-operator-names -Wzero-as-null-pointer-constant -Wsuggest-override -Wimplicit-fallthrough  -DDONT_DEPRECATE_SPRINTF -I/d/code/gdal/gdal/port  -DGDAL_COMPILATION       -I/d/code/gdal/gdal/ogr/ogrsf_frmts/geojson/libjson  -DINST_DATA=\"/mingw64/share/gdal\" -DHAVE_LIBZ -DUSE_ONLY_CRYPTODLL_ALG -c -o cpl_json.o cpl_json.cpp
```

**Comment by Gpinchon** [comment]
I opened an issue on MSYS2 github : https://github.com/msys2/MINGW-packages/issues/5245

**Comment by Gpinchon** [comment]
Got the explanation from MSYS2, don't use mingw32-make to build anything as it doesn't take Unix paths but some kind of mixed-breed between Windows and Unix paths (Windows paths with slashes instead of backslashes)
