### ISSUE TITLE
Configure script is not working with --crypto=path

### ISSUE THREAD

**Issue by MartinMikita** [OSGeo/gdal#1432]
Hi,

I have found a problem with configuration for custom OpenSSL Crypto build, using `--with-crypto=path`. This case is simply missing in the configuration script, nevertheless, it is mentioned that it is possible to use it.

[master](https://github.com/OSGeo/gdal/blob/master/gdal/configure.ac#L5683)
[v2.3.0](https://github.com/OSGeo/gdal/blob/v2.3.0/gdal/configure.ac#L5609)
[v2.4.1](https://github.com/OSGeo/gdal/blob/v2.4.1/gdal/configure.ac#L5571)

## Expected behavior and actual behavior.

Expected:
Compile with OpenSSL Crypto support, while the whole library is in the external `path` value.

Actual:
Will not compile with OpenSSL Crypto support at all. The only check is for either empty string or `yes`. Anything else is ignored, and therefore the support is disabled.

## Steps to reproduce the problem.

1. Download and extract source code
2. Compile and install OpenSSL library with prefix `/usr/local/`
3. run `./configure --with-crypto=/usr/local`
4. OpenSSL Crypto is disabled, `checking for crypto` is missing any value

## Operating system

Debian 8, 9, Ubuntu 18.04, macOS 10.12+

## GDAL version and provenance

Found in 2.3.0, 2.4.1, master.

**Comment by AgilentGCMS** [comment]
Confirm that the bug is still there in 3.0.2

**Comment by MartinMikita** [comment]
And still in 2.4.2 and 2.4.3

**Comment by rouault** [comment]
closing as configure has been removed and replaced by cmake
