### ISSUE TITLE
wrapper_GDALBuildVRT_objects in gdal_csharp.dll should take array of Dataset

### ISSUE THREAD

**Issue by andrew-paradis** [OSGeo/gdal#1436]
## Expected behavior and actual behavior.

I expected to be able to call Gdal.wrapper_GDALBuildVRT_objects(...) and supply an array of Datasets as the third parameter. This would bring this method in line with wrapper_GDALBuildVRT_names(...) which takes an array of filenames. 

The actual behavior is the third parameter is a SWIGTYPE_p_p_GDALDatasetShadow, which corresponds to nothing in the C# bindings.

## Steps to reproduce the problem.

Create any C# Gdal project, open a raster (from physical file) that contains subdatasets, create an in-memory Dataset from each subdataset, collect those Datasets in an in-memory array, attempt to call BuildVRT_objects with that Dataset array.

The purpose is to be able to get a VRT from the in-memory Dataset array without having to write intermediary files for each of the collected Datasets (and then use those filenames with the _names version of this build VRT method).

## Operating system

Windows 10, 64 bit.

## GDAL version and provenance

GDAL, GDAL.Native, GDAL.Plugins v 2.3.3 
https://www.nuget.org/packages/gdal/2.3.3

**Comment by MaxRev-Dev** [comment]
Hi @rouault. Do you know if this requires any specifics on the implementation? What is needed for this to bring it to life?

It seems like it's the only solution currently to use this workaround: https://lists.osgeo.org/pipermail/gdal-dev/2017-February/046046.html

https://github.com/OSGeo/gdal/blob/577fa18873510b9bcff1b53193fdcd1429152ebf/swig/include/csharp/gdal_csharp.i#L336-L352

**Comment by rouault** [comment]
> Do you know if this requires any specifics on the implementation? What is needed for this to bring it to life?

Probably taking inspiration from the extract of gdal_csharp.i related to Warp() and adapting it to BuildVRT()
