### ISSUE TITLE
SQLite driver fails writing infinity to geometry_columns_statistics

### ISSUE THREAD

**Issue by Nakaner** [OSGeo/gdal#1438]
## Expected behavior and actual behavior.

I write points into a SQlite database (with SPATIALITE=YES). One of these points has an negative infinity as y coordinate (result of projecting the south pole with a Mercator Projection which isn't defined at y=90°). When closing the dataset, the SQlite driver updates the `geometry_columns_statistics` table. The example programme below throws the following error:

`ERROR 1: sqlite3_exec(INSERT OR REPLACE INTO geometry_columns_statistics (f_table_name, f_geometry_column, row_count, extent_min_x, extent_min_y, extent_max_x, extent_max_y, last_verified) VALUES ('testlayer', 'geometry', 3, -7792364.35552914906, -inf, 14471533.803125564, -7361866.11305118911, strftime('%Y-%m-%dT%H:%M:%fZ','now'))) failed: no such column: inf`

`inf` is not valid in SQlite. `std::limits<double>::infinity()` from `limits.h` might be an option to be used.

`OGRSQLiteTableLayer::SaveStatistics()` tries to send that statement. The doubles are convered to strings using `OGRFormatDouble()`. That function writes a `inf` for an infinity.

## Steps to reproduce the problem.

The following example programme demonstrates the issue:

```cpp
#include <gdal/ogr_geometry.h>
#include <gdal/ogrsf_frmts.h>
#include <gdal/ogr_api.h>
#include <iostream>
#include <limits>
#include <string>

#if GDAL_VERSION_MAJOR >= 2
using gdal_dataset_type = GDALDataset;
using gdal_driver_type = GDALDriver;
#else
using gdal_dataset_type = OGRDataSource;
using gdal_driver_type = OGRSFDriver;
#endif

void add_geometry(OGRLayer* l, double x, double y, const int int_field_value) {
    OGRFeature* feature = OGRFeature::CreateFeature(l->GetLayerDefn());
    OGRPoint* point = new OGRPoint(x, y);
    feature->SetGeometryDirectly(static_cast<OGRGeometry*>(point));
    feature->SetField("id", int_field_value);
    if (l->CreateFeature(feature) != OGRERR_NONE) {
        std::cerr << "error creating feature\n";
    }
}

int main(int argc, char* argv[]) {
    if (argc != 2) {
        std::cerr << "ERROR: wrong usage\n  usage: " << argv[0] << " OUTFILE\n";
        exit(1);
    }
    const char* outfile = argv[1];
    OGRRegisterAll();

#if GDAL_VERSION_MAJOR >= 2
    gdal_driver_type* driver = GetGDALDriverManager()->GetDriverByName("SQlite");
#else
    gdal_driver_type driver = OGRSFDriverRegistrar::GetRegistrar()->GetDriverByName("SQlite");
#endif

    const char* options[] = {"SPATIALITE=TRUE", nullptr};
    gdal_dataset_type* dataset = driver->Create(outfile, 0, 0, 0, GDT_Unknown, const_cast<char**>(options));

    const char* layer_options[] = {nullptr};
    OGRLayer* layer = dataset->CreateLayer("testlayer", nullptr, wkbPoint, const_cast<char**>(layer_options));
    OGRFieldDefn field_defn {"id", OFTInteger};
    layer->CreateField(&field_defn);
    if (layer->StartTransaction() != OGRERR_NONE) {
        std::cerr << "error starting transaction\n";
        exit(1);
    }

    // lon=130.0 lat=-55.0
    add_geometry(layer, 14471533.803125564, -7361866.113051189, 1);
    // lon=-70.0 lat=-85.0
    add_geometry(layer, -7792364.355529149, -19971868.880408570, 2);
    // lon=0.0 lat=-90.0 (tangens not defined there)
    add_geometry(layer, 0.0, -(std::numeric_limits<double>::infinity()), 3);

    if (layer->CommitTransaction() != OGRERR_NONE) {
        std::cerr << "error committing transaction\n";
    }

    OGRCleanupAll();
}
```

Compile it with `g++ -Wall -Wextra -I/usr/include -o inftest inftest.cpp -L/usr/lib -lgdal`.

## Operating system

Ubuntu 18.04 amd64

## GDAL version and provenance

GDAL 2.2.3 (standard Ubuntu repositories)

A look into the current master branch shows that this bug is still likely to happen (I haven't checked that). I hope that the example code above makes checking that easy. 

## Remarks

Users using Proj.4 won't run into this issue because Proj.4 will throw an error with the following message: "tolerance condition error". This is already handled by GDAL. In my case, I use the Mercator implementation provided by Libosmium because it is faster. It returns negativ infinity for a latitude of 90°.

**Comment by rouault** [comment]
I consider this a odd use case (many things might break elsewhere with infinity values in geometries), but the fix was reasonable.
