### ISSUE TITLE
Shift in longitude when reading  netcdf with attributes axis set

### ISSUE THREAD

**Issue by svicario** [OSGeo/gdal#1440]
## Expected behavior and actual behavior.

A netcdf with attributes "axis" to define dimension on longitude is uncorrectly translated by gdal_translate and viewed by qgis that use gdal with a shift of 360 meters to east.

## Steps to reproduce the problem.
Original problem was found viewing a netcdf on qgis 3.6.
I produced a netcdf from a stack envi in python (xarray).  Following Nc convention 1.6, I added attribute "axis"  with value "X" to x longitude. Then I used gdal_translate to produce a tiff and image was shifted of 12 pixel (30m wide) to east in qgis and reading first cell of longitude in python I was getting 617250 in original dataset, while the gdal_translated had 616890. I used same file in python, removed axis attribute  on longitude and translation was fine. Adding the "axis:Y" attribute to latitude or "axis:T" to the third dimension didn't cause any trouble.

    MSAVI=xr.open_rasterio(path)
    MSAVI.to_netcdf("Good.nc")
    MSAVI.x.attrs["axis"]="X"
    MSAVI.to_netcdf("Fake.nc")

    %bash
    gdal_translate Fake.nc Fake.tif
    gdal_translate Good.nc good.tif

    Good=xr.open_rasterio("good.tif")
    Fake=xr.open_rasterio("Fake.tif")

    Fake.x[0]-MSAVI.x[0]
<xarray.DataArray 'x' ()>
array(-360.)

    Good.x[0]-MSAVI.x[0]
<xarray.DataArray 'x' ()>
array(0.)
Coordinates:
    x        float64 6.172e+05

## Operating system

Ubuntu 18.04 64 bit

## GDAL version and provenance

GDAL 2.4.0, released 2018/12/14

**Comment by rouault** [comment]
I have issues to understand this bug description. Adding dataset(s) would be helpful, and reducing to the minimum scenario as well

**Comment by svicario** [comment]
okay let'use this dataset
http://download.osgeo.org/geotiff/samples/made_up/bogota.tif
Adding the attribute axis:X to longitude will change the origin on longitude from 440720 to 440360

address for intermediate files
http://cloud.recas.ba.infn.it:8080/v1/AUTH_fb6d6fcd0e194a96bb6d0420dce8332f/0da513ef-3382-412b-9a32-bf7b18babe59/Good.nc

http://cloud.recas.ba.infn.it:8080/v1/AUTH_fb6d6fcd0e194a96bb6d0420dce8332f/0da513ef-3382-412b-9a32-bf7b18babe59/Fake.nc


read in python xarray in order to add attribute axis=X

    bog=xr.open_rasterio("http://download.osgeo.org/geotiff/samples/made_up/bogota.tif")
    bog.to_netcdf("Good.nc")
    bog.x.attrs["axis"]="X"
    bog.to_netcdf("Fake.nc")

    %%bash
    gdal_translate Fake.nc Fake.tif
    gdalinfo Fake.tif

Driver: GTiff/GeoTIFF
Files: Fake.tif
Size is 512, 512
Coordinate System is `'
Origin = (440360.000000000000000,100000.000000000000000)
...

    gdal_translate Good.nc Good.tif    
    gdalinfo Good.tif

   Driver: GTiff/GeoTIFF
Files: Good.tif
       Good.tif.aux.xml
Size is 512, 512
Coordinate System is `'
Origin = (440720.000000000000000,100000.000000000000000)

    gdalinfo bogota.tif

Driver: GTiff/GeoTIFF
Files: bogota.tif
Size is 512, 512
Coordinate System is:
....
Origin = (440720.000000000000000,100000.000000000000000)

**Comment by svicario** [comment]
Fake.nc and Good.nc have the same origin, the difference appear only in the tif

**Comment by rouault** [comment]
OK. I've confirmed the bug and pushed a fix. In the meantime, you can workaround this by setting GDAL_NETCDF_CENTERLONG_180=NO as environment varable
