### ISSUE TITLE
Makefile installer assumes python and gdal share the same path

### ISSUE THREAD

**Issue by etresoft** [OSGeo/gdal#1447]
## Expected behavior and actual behavior.

The GDAL makefile installs the python modules into its own root, assuming that is where Python is installed. But I have a custom build stack. My python is installed into its own location (because it doesn’t have an uninstaller). Python then can’t find the goal modules.

## Steps to reproduce the problem.

It’s complicated.

## Operating system

macOS 10.14.3 but with a custom GDAL stack much closer to old-school Unix.

## GDAL version and provenance

2.4.1 from GitHub tagged to v2.4.1

## Note

I can append the GDAL module path to PYTHONPATH and it works. I’m not sure what the right answer is. I’m not really a Python person. I just want to test my build, and the test suite uses Python. Maybe it would be nice to have a configurable option so one could specify where the swig modules should be installed.

**Comment by rouault** [comment]
You can test a GDAL build without installing it by sourcing "scripts/setdevenv.sh"

**Comment by rouault** [comment]
You can also probably play with the various options available with "python setup.py install [options]" (from gdal/swig/python) to install in a custom location.
Closing
