### ISSUE TITLE
Gdal does not recognize the geometry that is written using version 2 of SQL Server (some polygons are missing)

### ISSUE THREAD

**Issue by yanivday** [OSGeo/gdal#1448]
[Y_sql_esri_Esport_backup.zip](https://github.com/OSGeo/gdal/files/3087549/Y_sql_esri_Esport_backup.zip)
GDAL (and therefore, QGIS 3.6.0 ) does not support the current version of the SQL Server Spatial binary format. Specifically, GDAL appears to support only version 1 of the format (which was introduced with SQL Server 2008). However this format was updated to version 2 at the time SQL Server 2012 was released, so any geometry written to SQL Server Spatial, for example, by the current GeoMedia SQL Server Spatial data server, is written using version 2 of the format. This means that if you have a SQL Server Spatial database that has the old (version 1) format geometry present in it and you edit a feature as described in the ticket (or insert a new feature) the features will not be visible in QGIS because Gdal does not recognize the geometry that is written using version 2 of the format. 

The Microsoft site with the documentation for the CLR Types is located at... 
https://docs.microsoft.com/en-us/openspecs/sql_server_protocols/ms-ssclrt/77460aa9-8c2f-4449-a65e-1d649ebd77fa 

## Expected behavior and actual behavior.

When loading the data, some polygons are missing. I expect to see all polygons.

## Steps to reproduce the problem.

1.	Restore the attached database to Microsoft SQL and note SQE_SQL > SQW_Buildings table
2.	Connect to the databse with QGIS and load SQW_Buildings table
3.	Note that QGIS recognizes 33 records but loads less than that. some polygons are missing (see attached image)
 
4.	Points become complex geometry, polygons also becomes complex geometry.
![Missing_polygins](https://user-images.githubusercontent.com/48534097/56254651-ba574600-6115-11e9-893a-ed6ca943127b.jpg)
[Y_sql_esri_Esport_backup.zip](https://github.com/OSGeo/gdal/files/3087556/Y_sql_esri_Esport_backup.zip)

**Comment by mloskot** [comment]
@yanivday What does "please modify !!!" mean?

**Comment by mloskot** [comment]
@yanivday Ha! I had no idea :-) I suspected it's some request, but a bit obscure. Thanks!

**Comment by szekerest** [comment]
@yanivday The support for the v2 geometries has already been added in GDAL/master. I've checked your table an it was correctly rendered in mapserver (with both the native and the ogr driver). I'm also working on upgrading the QGIS native mssql driver to support these geometries, too.

**Comment by szekerest** [comment]
For more information, please refer to https://github.com/OSGeo/gdal/issues/1299

**Comment by yanivday** [comment]
Thanks @szekerest ! 
Can you tell what is the latest mssql driver version (to support these geometries)?

**Comment by larseggan** [comment]
Hi,
What's the status on the QGIS native mssql driver to support the version 2 geometries?

**Comment by szekerest** [comment]
@larseggan It is in pull request status
https://github.com/qgis/QGIS/pull/9981
Will be included after some test cases are implemented
