### ISSUE TITLE
gdalwarp reprojection:

### ISSUE THREAD

**Issue by NidhiPal619** [OSGeo/gdal#1450]
## Expected behavior and actual behavior.

For example (please modify !!!): I expected to be able to open this raster file (with a link to
the raster file, or it as an attachment) and it returns an error message
instead.

## Steps to reproduce the problem.

For example (please modify !!!): "gdalinfo myfile"

## Operating system

For example (please modify !!!): Ubuntu 16.04 64 bit

## GDAL version and provenance

For example (please modify !!!): the 2.2.3 version from ubuntugis-unstable PPA

**Comment by rouault** [comment]
Please update this bug description with something meaningful
