### ISSUE TITLE
ENCODING_TYPE support for PDS3 images 

### ISSUE THREAD

**Issue by Kelvinrr** [OSGeo/gdal#1457]
## Expected behavior and actual behavior.

GDAL fails to open a Kaguya Terrain Camera PDS3 image. The problem being that these images have an ENCODING_TYPE key in the label which GDAL doesn't currently support,

```
(ale) igswzawglt0091:ISIS3 kelvin$ gdalinfo ~/repos/ale/images/TC1W2B0_01_00366S495E1640.img
ERROR 4: *** PDS image file has an ENCODING_TYPE parameter:
*** gdal pds driver does not support compressed image types
found: (DCT_DECOMPRESSED)


gdalinfo failed - unable to open '/Users/kelvin/repos/ale/images/TC1W2B0_01_00366S495E1640.img'.
```

## Steps to reproduce the problem.

[TC1W2B0_01_00366S495E1640.zip](https://github.com/OSGeo/gdal/files/3095354/TC1W2B0_01_00366S495E1640.zip)

Download and unzip the above example. Simply run: 

`gdalinfo TC1W2B0_01_00366S495E1640.img`

## Operating system

MacOS 10.13.6

## GDAL version and provenance

gdal 2.4.1 from conda-forge, build py36h7eb7563_1

**Comment by Kelvinrr** [comment]
@thareUSGS Do you have any input on how to get this fix in?

**Comment by rouault** [comment]
It turns out that just allowing this value and going on leads to apparent correct behaviour.
