### ISSUE TITLE
Creating multi-page TIFF compatible with ImageJ

### ISSUE THREAD

**Issue by chacha21** [OSGeo/gdal#1458]
I can create (with GDAL) a multi-band TIFF that GDAL itself is able to re-open correctly, but so far, I wasn't able to generate (still with GDAL) a multi-page TIFF compatible with ImageJ. ImageJ always see only 1 image, no layers or stack or anything.
I have tried several options :
setting PROFILE=BASELINE
setting INTERLEAVE=BAND and creating the dataset of dimensions `width*height*bands`

use an alternative method where I create the dataset with 1 band (let's say "foo.tif"), then call `gdalDriver->Create("GTIFF_DIR:<index>:<path_to_foo.tif>", ...)` to add sub datasets
...
I wonder if any special care must be taken (closing the main dataset before adding subsets, use sharing options... I have tried many cases, always failing when trying to reopen with ImageJ)

Any other idea ?

(For information, each band is a 8-bit gray-level image).

**Comment by rouault** [comment]
Subdataset creation for GTiff has been added in this development cycle in GDAL master, so will be available in GDAL 2.5.0 (beta1 tomorrow):  `gdal_translate in.tif existing.tif -co APPEND_SUBDATASET=YES`
Anyway just trying with ImageJ, it only sees the first image, whereas gimp can see both. I presume that's a ImageJ limitation.
Not much to be done on GDAL side

**Comment by chacha21** [comment]
It is certainly not ImageJ's fault, because :
-ImageJ is a pretty solid reference about handling multi-page TIFF that are largely used in biology
-I even use Fiji, a distribution of ImageJ with additional features
-I already encountered multi-page TIFFs that were successfully opened by ImageJ, but not by GDAL (the exact inverse problem).

Now,
APPEND_SUBDATASET=YES was already referenced in GDAL 2.4.0. I tried it, since without success. What is new with 2.5.0 ?

A sample code of good usage for multi-page TIFF creation would be welcome, so that I would have a reference example to open an issue on ImageJ's side.

**Comment by rouault** [comment]
> It is certainly not ImageJ's fault only, because :

OK... then attach/link a TIFF image that works with ImageJ so that we can see how it is done exactly

> APPEND_SUBDATASET=YES was already referenced in GDAL 2.4.

No, it wasn't for GTiff. There's some generic handling of it in the core, but support in the GTiff driver was missing

> A sample code of good usage for multi-page TIFF creation would be welcome
What I mentionned above is enough to easily create such dataset:  `gdal_translate in.tif existing.tif -co APPEND_SUBDATASET=YES`. I'm attaching an image created that way : 
[multipage.tif.zip](https://github.com/OSGeo/gdal/files/3097570/multipage.tif.zip)

**Comment by rouault** [comment]
@chacha21 Any feedback on this ?

**Comment by chacha21** [comment]
I will upload such a TIFF in a few days, I am currently away from the machine where it is stored.

**Comment by chacha21** [comment]
#1486

**Comment by chacha21** [comment]
When GDAL 2.5.0 is out, I will submit to ImageJ an issue about multi-page Tiff generation from GDAL, with sample code showing the different possible strategies. Then I will go back here according to their answer.

**Comment by chacha21** [comment]
I have compiled current master branch (now 3.0.0) to check for multi-page TIFF
When trying to add sub datasets, I get a failure with an errorCode, but "No error" message.
`
error = 1, errorNum= 0, msg = <GDAL: GDALDriver::Create(GTiff,E:\tiff-strategy2.tiff,640,480,1,Byte,000000000026F018)>
error = 1, errorNum= 0, msg = <GDAL: GDALClose(E:\tiff-strategy2.tiff, this=00000000002BF7A0)>
error = 1, errorNum= 0, msg = <GDAL: GDALDriver::Create(GTiff,GTIFF_DIR:1:E:\tiff-strategy2.tiff,640,480,1,Byte,000000000026F058)>
error = 3, errorNum= 4, msg = <Attempt to create new tiff file `GTIFF_DIR:1:E:\tiff-strategy2.tiff' failed: No error>
`

`
//context w=640, h=480, z=100, images[i=0..z] are byte buffers ready to write

//strategy 2
  {
    char* tiffOptionsMain[] =
      {"PREDICTOR=1",
       "BIGTIFF=IF_NEEDED",
       "INTERLEAVE=BAND",
       0
       };
    char* tiffOptionsSub[] =
      {"PREDICTOR=1",
       "BIGTIFF=IF_NEEDED",
       "INTERLEAVE=BAND",
       "APPEND_SUBDATASET=YES,",
       0
       };
    GDALDataset* dstDataset = 0;
    dstDataset = !tiffDriver ? 0 : (GDALDataset*)tiffDriver->Create("E:\\tiff-strategy2.tiff", w, h, 1, GDALDataType::GDT_Byte, tiffOptionsMain);
    if (dstDataset)
    {
      GDALClose(dstDataset);
      dstDataset = 0;
    }//end if (dstDataset)
    for(int i = 0 ; i<z ; ++i)
    {
      char buffer[1024] = {0};
      snprintf(buffer, sizeof(buffer), "GTIFF_DIR:%d:%s", i+1, "E:\\tiff-strategy2.tiff");
      GDALDataset* subDataset = !tiffDriver ? 0 :
        //(GDALDataset*)GDALOpen(buffer, GA_Update);
        tiffDriver->Create(buffer, w, h, 1, GDALDataType::GDT_Byte, tiffOptionsSub);
      if (subDataset)
      {
        subDataset->RasterIO(GDALRWFlag::GF_Write, 0, 0, w, h,
                             images[i], w, h,
                             GDALDataType::GDT_Byte, 1, 0,
                             0, w, frameLength,
                             0);
        GDALClose(subDataset);
      }//end if (subDataset)
    }
  }`

**Comment by rouault** [comment]
> snprintf(buffer, sizeof(buffer), "GTIFF_DIR:%d:%s", i+1, "E:\tiff-strategy2.tiff");

You should just use the full filename without GTIFF_DIR:

**Comment by chacha21** [comment]
Ok, it works !
And ImageJ will open the TIFF and see the layers, that's great.

I suggest that you clarify a little the doc in [https://www.gdal.org/frmt_gtiff.html](url) about the use of APPEND_SUBDATASET

**Comment by chacha21** [comment]
When creating a multi-page tiff RGB as 3x8bits, ImageJ opens the TIFF correclty.
When creating a multi-page tiff RGB as 3x16bits, ImageJ reads the layer and raises an exception at the end of reading.
I dont know yet if it is imageJ's fault.

**Comment by chacha21** [comment]
[https://github.com/fiji/fiji/issues/225](url)

**Comment by chacha21** [comment]
Multi-page TIFF generated by GDAL 3.0 works and can even be seen through the Windows default viewer.
However, if you add a tag, the TIFF is broken and only the first subdataset will be seen by softwares

`dstDataset->SetMetadataItem("TIFFTAG_SOFTWARE", "something", domain);
//I tried with domain being null, "", "TIFF", "Tiff", "GTiff"
`

**Comment by rouault** [comment]
Regarding your last comment, I cannot confirm any issue with GDAL or libtiff tools, so this is likely a defect of other software regarding multi-page TIFF handling. Closing
