### ISSUE TITLE
gdal 2.4.1 ogr not able to process gmt file that worked in gdal 2.2.2 and 1.9.2 on ubuntu linux

### ISSUE THREAD

**Issue by hemantbist** [OSGeo/gdal#1461]
## Steps to reproduce the problem.
 The input test file bug.gmt is attached as  bug.gmt.txt. Please rename with .gmt extension to test.

ogrinfo -al /tmp/bug.gmt fails in new version bug works in old version.

The gmt file is simple tab seperated file with each line containing 
longitude,latitude,elevation

[bug.gmt.txt](https://github.com/OSGeo/gdal/files/3099138/bug.gmt.txt)

----- failure log from failed case ------
$ ogrinfo --version
GDAL 2.4.1, released 2019/03/15
ogrinfo -al /tmp/bug.gmt 
FAILURE:
Unable to open datasource `/tmp/bug.gmt' with the following drivers.
  -> PCIDSK
  -> netCDF
  -> JPEG2000
  -> PDF
  -> MBTiles
  -> EEDA
.... snippd 

-- Success log from 2.2.2 version -----
ogrinfo --version
GDAL 2.2.2, released 2017/09/15
ogrinfo -al /tmp/bug.gmt | head
INFO: Open of `/tmp/bug.gmt'
      using driver `OGR_GMT' successful.

Layer name: bug
Geometry: Unknown (any)
Feature Count: 10
Extent: (-91.077278, 45.888147) - (-91.076824, 45.888382)
Layer SRS WKT:
(unknown)

## Operating system
Ubuntu 16.04 64 bit / 14.04 64 bit ( on both os  versions problem can be reproduced.)

## GDAL version and provenance
2.4.1 stable release compiled on Ubuntu 16.04 with 
./configure --with-libtiff=/usr/lib --with-mysql --enable-debug --with-python

Note : In case the is a expected different behaviour, I would really appreciate any pointer to the right way to handle this case/any workaround for this. I tried to search release notes from 2.2.2 onwards, but could not find relevant pointer.

A common use case in our code is to convert these gmt files to shp using ogr2ogr

**Comment by rouault** [comment]
Fixed in master and release/2.4
Or a workaround is to add a "# @VGMT1.0" line at the beginning of the file

**Comment by hemantbist** [comment]
verfied that patch works for me.
ogr2ogr --version && ogrinfo -al /tmp/bug.gmt | head
GDAL 2.4.1, released 2019/03/15
INFO: Open of `/tmp/bug.gmt'
      using driver `OGR_GMT' successful.

Layer name: bug
Geometry: Unknown (any)
Feature Count: 10
Extent: (-91.077278, 45.888147) - (-91.076824, 45.888382)
Layer SRS WKT:
(unknown)
OGRFeature(bug):0
