### ISSUE TITLE
Readme is rendering incorrectly on pypi

### ISSUE THREAD

**Issue by walchko** [OSGeo/gdal#1462]
The [readme.txt](https://github.com/OSGeo/gdal/blob/master/gdal/swig/python/README.txt) is rendered incorrectly on [pypi.org](https://pypi.org/project/GDAL/). I *think* you wrote it in reStructuredText, but since the change in pypi Markdown I think is the preferred syntax. Maybe try using [Pandoc](http://pandoc.org/try/) to reformat it from `rst` to `md`.

**Comment by rouault** [comment]
after fix, now redender correctly in https://test.pypi.org/project/GDAL/
