### ISSUE TITLE
Restore OSRFixup to API

### ISSUE THREAD

**Issue by sgillies** [OSGeo/gdal#1466]
## Expected behavior and actual behavior.

Projects using the public API from GDAL 2.4 should build with GDAL 2.5: nothing should have been removed in 2.5. Fiona and Rasterio won't build with GDAL 2.5.0 beta1 because OSRFixup has been removed.

## Steps to reproduce the problem.

Fiona doesn't build with 2.5.0 beta1: https://github.com/Toblerity/Fiona/issues/745.

## Operating system

All.

## GDAL version and provenance

2.5.0 beta1

Removing OSRFixup breaks Fiona and Rasterio. Instead of removing OSRFixup outright, can we leave a function that does nothing, except maybe to warn about upcoming removal in a future major version?

The same should probably also be done for other functions that have been removed. Fiona and Rasterio don't use the others, but some projects may, and will find themselves broken.

**Comment by rouault** [comment]
The removal was intended and documented in MIGRATION_GUIDE.TXT.
Of course they could be restored to no-op, but as migrating to GDAL 2.5 involves changes that aren't just detected at compilation time (for example, difference in axis order handling), this might be a useful signal to downstream consumers they must taken some acts.
