### ISSUE TITLE
geobuf read/write driver

### ISSUE THREAD

**Issue by andrewharvey** [OSGeo/gdal#1467]
[geobuf](https://github.com/mapbox/geobuf) read/write driver support

I understand there was some discussion about adding support to PostGIS, but in the end it was added https://postgis.net/docs/ST_AsGeobuf.html.

(I'm creating ticket so people can subscribe to updates)

**Comment by rouault** [comment]
Is it to track an upcoming contribution from yours for such a driver ?

**Comment by andrewharvey** [comment]
> Is it to track an upcoming contribution from yours for such a driver ?

No I'm not planning on working on this. I'd like to see this as a user but couldn't see any open ticket I could subscribe to for updates.

**Comment by jratike80** [comment]
The geobuf repository https://github.com/mapbox/geobuf shows low activity. Maybe this ticket could be closed?

**Comment by rouault** [comment]
closing as likely no longer relevant
