### ISSUE TITLE
Can't find gcs.csv since release 2.4

### ISSUE THREAD

**Issue by gastoneb** [OSGeo/gdal#1471]
Hello,

I used to be able to find `gcs.csv` at `gdal/data/gcs.csv`. Now I cannot find the file in the master branch, only in branches `release/2.4` and earlier. I'm not sure what other data files may be missing. 

It's also absent from the latest 2.5.0 beta release [on the downloads page](http://download.osgeo.org/gdal/2.5.0/gdal250beta1.zip).

Apologies if the file was removed intentionally, or if I'm mistaken and it isn't normally found in `gdal/data`.

Thank you.

**Comment by jratike80** [comment]
CSV files are not included starting from GDAL 2.5 because of PROJ6 integration https://trac.osgeo.org/gdal/wiki/rfc73_proj6_wkt2_srsbarn. Information about coordinate systems is stored into SQLite database "proj.db" now.

**Comment by gastoneb** [comment]
That makes sense. Thanks.
