### ISSUE TITLE
xyz file no longer working in 2.4.1

### ISSUE THREAD

**Issue by johanvdw** [OSGeo/gdal#1472]
## Expected behavior and actual behavior.
I have a xyz file:
https://github.com/inbo/niche_vlaanderen/blob/master/tests/data/mlw_small.xyz

This used to work with gdal eg version 2.1.2 (Debian stretch). However it no longer works with gdal 2.4.1 
ie:

$ gdalinfo tests/data/mlw_small.xyz
ERROR 4: `tests/data/mlw_small.xyz' not recognized as a supported file format.
gdalinfo failed - unable to open 'tests/data/mlw_small.xyz'.

Is this a known issue? I could bisect down to the 

## Operating system
Debian Stretch
## GDAL version and provenance
gdal 2.1.2 (as provided by Debian stretch)
gdal 2.4.1 (compiled myself)

**Comment by jratike80** [comment]
Renaming the third column into "Z" makes the file understood by GDAL. That the third column is required to be "Z" seems to be against the documentation https://www.gdal.org/frmt_xyz.html

> If no header is present **or one of the column could not be identified in the header**, the X, Y and Z columns (in that order) are assumed to be the first 3 columns of each line. 

If the link will disappear some day, the header line is

`"X"	"Y"	"mlw"`
