### ISSUE TITLE
GetGeoTransform returns incorrect data for images rotated 90 and 270 degrees 

### ISSUE THREAD

**Issue by Razanjin** [OSGeo/gdal#1474]
## Expected behavior and actual behavior.

I am trying to get the GeoTransform array GT from ENVI images using GetGeoTransform. The images are rotated, so there is a _rotation_ argument within their header. The expected behaviour is to return an array GT as:

_In case of north up images, the GT(2) and GT(4) coefficients are zero, and the GT(1) is pixel width, and GT(5) is pixel height. The (GT(0),GT(3)) position is the top left corner of the top left pixel of the raster._

This is indeed the case for every rotation apart from 90.00000 and 270.00000. For these two values, GT(2) seem to become pixel width and GT(4) pixel height, while GT(1) and GT(5) become the rotation coefficients.

There may be a problem with some cos() or sin() within GetGeoTransform, as it behaves as expected for rotations such as 90.000001 or 89.999999.
 
## Steps to reproduce the problem.

To reproduce the problem, use GetGeoTransform on a georeferenced rotated ENVI image.

Example of info within the header:
```
map info = {UTM, 1.000, 1.000, 676960.169, 4254967.460, 2.0000000000e+00, 2.0000000000e+00, 10, North, WGS-84, units=Meters, rotation=90.0000001}
coordinate system string = {PROJCS["UTM_Zone_10N",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Transverse_Mercator"],PARAMETER["False_Easting",500000.0],PARAMETER["False_Northing",0.0],PARAMETER["Central_Meridian",-123.0],PARAMETER["Scale_Factor",0.9996],PARAMETER["Latitude_Of_Origin",0.0],UNIT["Meter",1.0]]}
```

## Operating system

OS: CentOS 7

## GDAL version and provenance
GDAL 2.4.0 from conda-forge on python 3.6.6

**Comment by rouault** [comment]
Please provide a link / attach an ENVI image that exhibits the issue

**Comment by jratike80** [comment]
Hi @Razanjin, it would be interesting to know how did you solve your problem.

**Comment by Razanjin** [comment]
Hi,
There was in fact no real issue with GDAL, and I had just misunderstood the documentation. 

It seems that when the image is not north-up, GT(1), GT(5)/GT(2), GT(4) do not directly correspond to rotation coefficients/pixel width anymore. However the formula given in the documentation to derive the coordinates from the GT array still applies and works as intended.

**Comment by ouyang-means-ouyang** [comment]
How to use GDAL to create a rotated image? I mean, the image is not facing north, that is, G (2) and G (4) are not zero

**Comment by ouyang-means-ouyang** [comment]
How to use GDAL to create a rotated image? I mean, the image is not facing north, that is, G (2) and G (4) are not zero

**Comment by rouault** [comment]
@ouyang-means-ouyang This is the 4th message on the same topic you send here or to my email. Please stop this
