### ISSUE TITLE
gdaldem: issue finding libstdc++ packages

### ISSUE THREAD

**Issue by spiesr** [OSGeo/gdal#1476]
## Expected behavior and actual behavior.

I am trying to run a project that makes a call to gdaldem to process DEM files, and I ran into an issue that stops the program. I expect it to run as normal, but instead I get the following log messages:

`gdaldem: /tmp/_MEIrH7XOA/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /usr/lib/libgdal.so.20)
gdaldem: /tmp/_MEIrH7XOA/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/lib/libgdal.so.20)
gdaldem: /tmp/_MEIrH7XOA/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /usr/lib/libgdal.so.20)
gdaldem: /tmp/_MEIrH7XOA/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /usr/lib/libgdal.so.20)
gdaldem: /tmp/_MEIrH7XOA/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /usr/lib/x86_64-linux-gnu/libpoppler.so.73)
gdaldem: /tmp/_MEIrH7XOA/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/lib/x86_64-linux-gnu/libgeos_c.so.1)
gdaldem: /tmp/_MEIrH7XOA/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /usr/lib/x86_64-linux-gnu/libkmlbase.so.1)
gdaldem: /tmp/_MEIrH7XOA/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /usr/lib/x86_64-linux-gnu/libkmlbase.so.1)
gdaldem: /tmp/_MEIrH7XOA/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/lib/x86_64-linux-gnu/libkmlbase.so.1)
gdaldem: /tmp/_MEIrH7XOA/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /usr/lib/x86_64-linux-gnu/libkmldom.so.1)
gdaldem: /tmp/_MEIrH7XOA/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /usr/lib/x86_64-linux-gnu/libkmldom.so.1)
gdaldem: /tmp/_MEIrH7XOA/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/lib/x86_64-linux-gnu/libkmldom.so.1)
gdaldem: /tmp/_MEIrH7XOA/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /usr/lib/x86_64-linux-gnu/libkmlengine.so.1)
gdaldem: /tmp/_MEIrH7XOA/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /usr/lib/x86_64-linux-gnu/libkmlengine.so.1)
gdaldem: /tmp/_MEIrH7XOA/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/lib/x86_64-linux-gnu/libkmlengine.so.1)
gdaldem: /tmp/_MEIrH7XOA/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /usr/lib/x86_64-linux-gnu/libxerces-c-3.2.so)
gdaldem: /tmp/_MEIrH7XOA/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /usr/lib/x86_64-linux-gnu/libxerces-c-3.2.so)
gdaldem: /tmp/_MEIrH7XOA/libz.so.1: version `ZLIB_1.2.9' not found (required by /usr/lib/x86_64-linux-gnu/libpng16.so.16)
gdaldem: /tmp/_MEIrH7XOA/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /usr/lib/x86_64-linux-gnu/libdapclient.so.6)
gdaldem: /tmp/_MEIrH7XOA/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /usr/lib/x86_64-linux-gnu/libdapclient.so.6)
gdaldem: /tmp/_MEIrH7XOA/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/lib/x86_64-linux-gnu/libdapclient.so.6)
gdaldem: /tmp/_MEIrH7XOA/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /usr/lib/x86_64-linux-gnu/libdap.so.25)
gdaldem: /tmp/_MEIrH7XOA/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /usr/lib/x86_64-linux-gnu/libdap.so.25)
gdaldem: /tmp/_MEIrH7XOA/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /usr/lib/x86_64-linux-gnu/libdap.so.25)
gdaldem: /tmp/_MEIrH7XOA/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/lib/x86_64-linux-gnu/libdap.so.25)
gdaldem: /tmp/_MEIrH7XOA/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /usr/lib/x86_64-linux-gnu/libgeos-3.6.2.so)
gdaldem: /tmp/_MEIrH7XOA/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/lib/x86_64-linux-gnu/libgeos-3.6.2.so)
gdaldem: /tmp/_MEIrH7XOA/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /usr/lib/x86_64-linux-gnu/libicuuc.so.60)`

These errors do not make sense to me, because when I use the `strings` command to find which packages are included in my libstdc++ installation they are all there. For some reason gdaldem is not linking to the correct libstdc++ installation, and instead targeting one in /tmp/. I would like to know where I should implement a fix so that I can get my program back up and running ASAP. Thanks so much in advance.

## Steps to reproduce the problem.

The command being called is
`gdaldem color-relief $fileHere $startingDirectoryHere/colormapfile.txt -OF png output.png`

## Operating system

Linux Mint 19.1 Cinnamon, 64 bit, running in KVM 

## GDAL version and provenance

GDAL 2.2.3 installed from the command `apt-get -y install gdal-bin`

**Comment by rouault** [comment]
This is likely an issue with how you build GDAL, not a GDAL issue itself. Please use the mailing list or other support channels.
