### ISSUE TITLE
GTIFF WebP lossless compression is very slow

### ISSUE THREAD

**Issue by palmerj** [OSGeo/gdal#1478]
## Expected behavior and actual behavior.

When doing GTIFF compression with WebP lossless the compute time seems very slow. When I compress the same image using the libwebp tool `cwebp` it is much faster. e.g

```
time cwebp -lossless BA31_2623.tif -o BA31_2623.webp
TIFFReadDirectory: Warning, Unknown field with tag 33550 (0x830e) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 33922 (0x8482) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 34735 (0x87af) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 34736 (0x87b0) encountered.
Saving file 'BA31_2623.webp'
File:      BA31_2623.tif
Dimension: 6400 x 9600
Output:    92949156 bytes (12.10 bpp)
Lossless-ARGB compressed size: 92949156 bytes
  * Header size: 126407 bytes, image data size: 92822724
  * Lossless features used: PREDICTION CROSS-COLOR-TRANSFORM SUBTRACT-GREEN
  * Precision Bits: histogram=8 transform=5 cache=0

real	0m46.333s
user	0m44.806s
sys	0m1.376s
```

But with gdal_translate I get about 6x slower:

```
time gdal_translate -of GTiff -co COMPRESS=WEBP -co WEBP_LOSSLESS=TRUE -co TILED=YES BA31_2623.tif BA31_2623_webplossless.tif
Input file size is 6400, 9600
0...10...20...30...40...50...60...70...80...90...100 - done.

real	4m49.142s
user	4m42.976s
sys	0m5.194s
```

When I did not use tiling it takes longer than 20mins, and I gave up waiting for a result:

```
time gdal_translate -of GTiff -co COMPRESS=WEBP -co WEBP_LOSSLESS=TRUE BA31_2623.tif BA31_2623_webplossless.tif
Input file size is 6400, 9600
0...10...20...30...40...50...60...70...80...90...100 - done.
^C

real	21m24.077s
user	21m7.774s
sys	0m6.992s
```

## Operating system

MacOSX 10.14.4

## GDAL version and provenance

GDAL 2.4.1 installed from MacOS osgeo-homebrew, using libwebp-1.0.2

**Comment by rouault** [comment]
(@palmerj I believe your above gdal_translate invokatings are mixed)

It seems there's a significant overhead on creation for each strip or tile with WebP compression. This can be demonstrated if I create a single-strip TIFF image with `gdal_translate -co COMPRESS=WEBP -co WEBP_LOSSLESS=TRUE BA31_2623.tif BA31_2623_webplossless_singlestrip.tif -co BLOCKYSIZE=9600`, the processing time is 1m27 s, which is similar to the 1m13s got with cwebp.
For multi strip/tile setups, breaking in a debugger shows that all the time in spent in libwebp itself (in the VP8LGetHistoImageSymbols() function called by VP8LEncodeImage() which is called internally by the WebPEncode() entry point).
With the single-strip approach, most of the time is spent in the VP8LCalculateEstimateForCacheSize() and then VP8LGetBackwardReferences() functions, both called internally by WebPEncode().
I'm not sure if anything can be done in GDAL or libtiff to improve performance.
Perhaps @normanb has some clues ?

**Comment by palmerj** [comment]
THanks Even. Sorry the last cmd should be fore "I did not use tiling"

**Comment by palmerj** [comment]
@rouault why is it that when `TILED=YES` it's faster than when defaults to stripped. Is the speed issue with strips only?

**Comment by normanb** [comment]
@palmerj when you are compressing tiles you are encoding more data than in the case of strips hence why it is faster. `cwep` is a good tool to use for comparison, the bulk of the encoder is configured  to the defaults - https://gitlab.com/libtiff/libtiff/blob/master/libtiff/tif_webp.c#L358 (same place in the internal libtiff build in GDAL)

When I was using webp in TIFF I did find the encoder to be relatively expensive the advantage for me was on reads as I could pull the webp image directly out of the TIFF file when it was set up as a COG.

**Comment by rouault** [comment]
> when you are compressing tiles you are encoding more data than in the case of strips hence why it is faster

To be clearer, with stripped (default) output, GDAL/libtiff defaults to creating strips of an height that aims to be at most 8 KB of uncompressed data (clearly a defaults from 30 years ago :-)). So in that case, it is 1-line per strip, and thus 9600 strips. In the tiled case, there are only (6400. / 256) * (9600. / 256) = 950 blocks. So there's clearly a large penaly when instantiating webp lossless compression.

**Comment by palmerj** [comment]
@normanb and @rouault thank you for the explanation - that all makes sense now.

**Comment by normanb** [comment]
referencing https://github.com/mapbox/COGDumper/issues/8
