### ISSUE TITLE
TileDB reads

### ISSUE THREAD

**Issue by normanb** [OSGeo/gdal#1479]
TileDB reads were `GLOBAL_ORDER` https://github.com/OSGeo/gdal/blob/master/gdal/frmts/tiledb/tiledbdataset.cpp#L220 and were changed to be `ROW_MAJOR` to reflect a change in TileDB approach to reads. The tests pass because all of the pixels are there. However when using `gdal_translate` the output is not visually correct. 

I will work on a fix today, noting that this is a critical bug for the upcoming GDAL release.

**Comment by rouault** [comment]
> this is a critical bug for the upcoming GDAL release.

Being a new functionality and not causing regression to existing workflows, I don't consider this warrants a RC2 just for that issue.
