### ISSUE TITLE
Build issue with MSVC 16 (VS 2019)

### ISSUE THREAD

**Issue by chacha21** [OSGeo/gdal#1489]
GDAL 2.4.1 :
`#include <cmath>` is missing in ogr/ogrlinestring.cpp
This is usually not a problem but Visual Studio 2019 will fail

**Comment by mloskot** [comment]
Fix seems trivial. Please, consider submitting PR.

**Comment by rouault** [comment]
Was fixed a few weeks ago per 22fa16e6e6de253438be943be1353187dca9b123
