### ISSUE TITLE
input WFS Z values not recognized by ogr2ogr, either by default or via dim=layer_dim

### ISSUE THREAD

**Issue by smnorris** [OSGeo/gdal#1495]
## Expected behavior and actual behavior.
Z values of 3D (XYZ) features from WFS not loaded to PostGIS with `ogr2ogr` with no `dim` option provided or with `-dim=layer_dim` option. If `-dim=XYZ` specified, the Z values are successfully loaded.

## Steps to reproduce the problem.

```
$ ogr2ogr -lco OVERWRITE=YES -lco GEOMETRY_NAME=geom -lco SCHEMA=temp -f PostgreSQL "PG:host=localhost user=postgres dbname=postgis password=postgres" -nln test_wfs_z -dim layer_dim "https://openmaps.gov.bc.ca/geo/pub/wfs?service=WFS&version=2.0.0&request=GetFeature&typeName=WHSE_BASEMAPPING.FWA_STREAM_NETWORKS_SP&outputFormat=json&SRSNAME=epsg%3A4326&CQL_FILTER=BLUE_LINE_KEY%3D354154932"

$ psql -c "SELECT max(ST_ZMax(geom)) FROM temp.test_wfs_z"

 max
-----
   0
(1 row)

$ ogr2ogr -lco OVERWRITE=YES -lco GEOMETRY_NAME=geom -lco SCHEMA=temp -f PostgreSQL "PG:host=localhost user=postgres dbname=postgis password=postgres" -nln test_wfs_z -dim XYZ "https://openmaps.gov.bc.ca/geo/pub/wfs?service=WFS&version=2.0.0&request=GetFeature&typeName=WHSE_BASEMAPPING.FWA_STREAM_NETWORKS_SP&outputFormat=json&SRSNAME=epsg%3A4326&CQL_FILTER=BLUE_LINE_KEY%3D354154932"

$ psql -c "SELECT max(ST_ZMax(geom)) FROM temp.test_wfs_z"
 max
-----
  39
(1 row)
```

## Operating system

MacOS 10.14.4

## GDAL version and provenance

GDAL 2.4.0, released 2018/12/14
Installed via homebrew

**Comment by jratike80** [comment]
Adding a comment about what was fixed. As I understand the issue happened because the first geometry from the WFS service had only XY coordinates 

`"geometry":{"type":"LineString","coordinates":[[-123.31933046,48.43114279,16.551],[-123.31968955,48.43129519,16]]}`
