### ISSUE TITLE
Update year in CITATION file, add note to HOW-TO-RELEASE

### ISSUE THREAD

**Issue by mwtoews** [OSGeo/gdal#1499]
Simple task: update the year in the CITATION file from 2018 to 2019. The year appears twice in this file.

Furthermore, I was about to modify HOW-TO-RELEASE as a PR, but couldn't find an obvious place to insert the step:

> x) Update two instances of year in CITATION file to the current year.

Perhaps there should be a sub section for updating version and/or release dates of a list of files (3.1, 3.2, 3.3, etc.), as the list of files that need updating appears to be dynamic. Or insert a new step and renumber the remaining steps.

**Comment by rouault** [comment]
> Or insert a new step

Put the content of 2 as 2.1, and add refreshing of CITATION as 2.2 ? (note: the CITATION file is not part as the generated tarball, but yes it does make sense to update CITATION with the year of the last release)
