### ISSUE TITLE
TIN Geometry Type is not supported by GEOS

### ISSUE THREAD

**Issue by yanivday** [OSGeo/gdal#1501]
Hi @rouault ,

Following https://github.com/OSGeo/gdal/issues/1363
TIN Geometry Type is not supported by GEOS. GDAL make use in GEOS, thus, GDAL Spatial Operation like Union will fail. The solution, as we can see it, is to support the old behavior by a new setting that will be set by CPLSetConfigOption.
Is this possible? 

Thanks, Yaniv

**Comment by rouault** [comment]
Closing this as wontfix. OGR has a OGR_G_ForceTo(geom, wkbMultiPolygon) function that can be used to "convert" TINs to multipolygon
