### ISSUE TITLE
Sentinel2 driver cannot open some L1C datasets downloaded with sentinelhub.aws

### ISSUE THREAD

**Issue by itongxiaojun** [OSGeo/gdal#1507]
download sentinel2 image and merger.

1. download sentinel2 image use sentinelhub.aws
sentinelhub.aws --product S2A_MSIL1C_20181119T031011_N0207_R075_T50TLK_20181119T061056 -f /data/AWS/
2. merger sentinel2 image use gdal_translate
gdal_translate MTD_MSIL1C.xml -sds outfile.tif

the test file 
http://52.194.225.66/data/aws/S2B_MSIL1C_20190113T031059_N0207_R075_T50TLK_20190113T054447.SAFE.tar.gz

The ERROR AT AWS Linux:
[root@ip-172-31-36-116 S2A_MSIL1C_20181219T031131_N0207_R075_T50TLK_20181219T045749.SAFE]# gdal_translate MTD_MSIL1C.xml -sds outfile.tif
ERROR 1: Cannot read ./GRANULE/L1C_T50TLK_A018233_20181219T031126/MTD_TL.xml
Input file size is 512, 512
ERROR 1: Input file has no bands, and so cannot be translated.

The Error At Windows:
E:\AWS\S2A_MSIL1C_20181219T031131_N0207_R075_T50TLK_20181219T045749.SAFE\S2A_MSIL1C_20181219T031131_N0207_R075_T50TLK_20181219T045749.SAFE>gdal_translate MTD_MSIL1C.xml -sds outfile.tif
ERROR 1: SENTINEL2GetGranuleInfo: Cannot read ./GRANULE/L1C_T50TLK_A018233_20181219T031126/MTD_TL.xml
Input file size is 512, 512
ERROR 1: Input file has no bands, and so cannot be translated.

The ERROR AT AWS Linux and GDAL 3.0:
[root@ip-172-31-36-116 S2A_MSIL1C_20181119T031011_N0207_R075_T50TLK_20181119T061056.SAFE]# /opt/gdal/bin/gdal_translate MTD_MSIL1C.xml -sds outfile.tif
ERROR 1: SENTINEL2GetGranuleInfo: Cannot read ./GRANULE/L1C_T50TLK_A017804_20181119T031012/MTD_TL.xml
Input file size is 512, 512
ERROR 1: Unable to export GeoTIFF files with zero bands.

**Comment by rouault** [comment]
This product is weird. The MTD_MSIL1C.xml file references <IMAGE_FILE>GRANULE/L1C_T50TLK_A017804_20181119T031012/IMG_DATA/T50TLK_20181119T031011_B01</IMAGE_FILE>, but the GRANULE/L1C_T50TLK_A017804_20181119T031012 directory does not exist. Instead this is GRANULE/L1C_T50TLK_A017804_20181119T031642

**Comment by itongxiaojun** [comment]
I meger images use s2Converter success.
https://github.com/jjrom/s2Converter.git

**Comment by rouault** [comment]
I've identified this as a defect of sentinehub-py for which I've proposed a fix: https://github.com/sentinel-hub/sentinelhub-py/pull/70.  The dataset downloaded directly from scihub.copernicus.eu has the right directory name and works fine with the GDAL Sentinel2 driver

**Comment by rouault** [comment]
Closing this ticket as a non-GDAL bug, but a sentinelhub-py one. See https://github.com/sentinel-hub/sentinelhub-py/blob/rouault-fix_tileid_path/sentinelhub/aws_safe.py#L285 for upcoming fix to the later
