### ISSUE TITLE
ogr2ogr: WFS string maxLength causes postgres error

### ISSUE THREAD

**Issue by magnus-m** [OSGeo/gdal#1508]
## Expected behavior and actual behavior.

**Expected behavior**
ogr2ogr will take the content of a feature from a WFS-service and create a corresponding table in PostgreSQL, where the data is stored.

**Actual behavior**
ogr2ogr tries to create a varchar column with a max length that exceeds the max length allowed by PostgreSQL, with the following error:

> ERROR: ALTER TABLE "schema_name"."tabel_name" ADD COLUMN "column_name" VARCHAR(1073741822)
> ERROR: length for type varchar cannot exceed 10485760

## Steps to reproduce the problem.

Have a WFS-service where a feature has a string length exceeding 10485760, which is the max length for VARCHAR in PostgreSQL

Shown here via a DescribeFeatureType command:
![objid](https://user-images.githubusercontent.com/19188046/57212120-f2e69300-6fe2-11e9-8dd4-43d2fa0c4afc.png)

The command used:

> ogr2ogr.exe --config PG_USE_COPY NO -lco schema=schema_name -a_srs EPSG:25832 -f "PostgreSQL" "PG:user=postgres password=secret dbname=db_name host=localhost port=5432" "WFS:http://url.com/arcgis_server/services/name/name/MapServer/WFSServer?service=WFS&version=1.0.0&token=secret_token" feature_name:name -lco PRECISION=YES -lco LAUNDER=YES -skipfailures -nln tabel_name

## Operating system

Windows 10

## GDAL version and provenance

GDAL 2.4.0, released 2018/12/14
Tested with both PostgreSQL 9.3 and 10

**Comment by rouault** [comment]
You can workaround the issue by adding -unsetFieldWidth
