### ISSUE TITLE
ISIS3 driver: gdal generated files are unreadable by ISIS3 when band metadata is present in source file

### ISSUE THREAD

**Issue by afrigeri** [OSGeo/gdal#1510]
## Expected behavior and actual behavior.

When writing an ISIS3 with gdal, the band name/number/width/filtername list get increased by one 'Null' band ahead of the existing ones.  

Moreover, the band names loose the quotation marks in the translation.  This makes the file unreadable by ISIS3 software, outputting  errors related to the parameter/value label parsing of the header. 

## Steps to reproduce the problem.

using the ISIS3 test file [FC21B0037339_15142232818F1C_3bands.cub.gz](https://github.com/OSGeo/gdal/files/3147248/FC21B0037339_15142232818F1C_3bands.cub.gz)

```
gunzip FC21B0037339_15142232818F1C_3bands.cub.gz
head -61 FC21B0037339_15142232818F1C_3bands.cub  | tail -5
    FilterNumber = (1, 1, 1)
    Center       = (700, 700, 700)
    Width        = (700, 700, 700)
    FilterName   = (Clear_F1, Clear_F1, Clear_F1)
    Name         = ("band 1","band 2","band 3")

gdal_translate -of ISIS3 FC21B0037339_15142232818F1C_3bands.cub test.cub

head -59 test.cub | tail -5
    FilterNumber = (, 1, 1, 1)
    Center       = (, 700, 700, 700)
    Width        = (, 700, 700, 700)
    FilterName   = (, Clear_F1, Clear_F1, Clear_F1)
    Name         = (, band 1, band 2, band 3)
```

The ISIS3 software can't open test.cub complaining about bands' metadata:

```
**ERROR** Unable to read PVL file [test.cub].
**ERROR** Error in PVL file on line [59].
**ERROR** Unable to read PVL keyword [Name         = (, band 1, band 2, band 3)].
**ERROR** Found extra data after [band] in array when reading PVL.
```

## Suggested Fixes

When writing the ISIS3 file:

 1. remove the trailing comma in the band list keys (BandBin group).
 2. add quotation marks to every band name in the __Name__ vector

## Operating system

Ubuntu 19.04 64 bit

## GDAL version and provenance
GDAL 2.4.0, released 2018/12/14 - ubuntugis-unstable PPA

**Comment by afrigeri** [comment]
Great! thanks.  

Alessandro

**Comment by thareUSGS** [comment]
@afrigeri thanks for getting this issue in. I was looking at going the other direction for band names (ISIS3 to other) and I am confused by the use of "Name" in the "Group = BandBin" in your label. Shouldn't that be written as "FilterName" instead of simple "Name"?

**Comment by afrigeri** [comment]
good point @thareUSGS !  I've found FilterName/FilterNumber in the bandbin group in data from multi-spectral imagers.  The "Name" key is being introduced in ISIS3 when for example we are computing derived values, as "Phase angle" or "Incidence angle" ( see the [phocube](https://isis.astrogeology.usgs.gov/Application/presentation/Tabbed/phocube/phocube.html) documentation).

To translate this in gdal-ian, maybe that ISIS3 key "Name" is the nearest concept to the _Band Description_ set by the SetDescription rasterband method in gdal.    If Name is not into the cub then I would get the FilterName into the _Band Description_.

Anyway it would be very cool to have the whole information of the bandbin group metadata structure into gdal.

**Comment by thareUSGS** [comment]
Been thinking about how to better label information across the "planetary" drivers. For Band Descriptions I guess first looking for "Name" and then looking for "FilterName" might work. Neither need to be there. But for other label information that doesn't fit, perhaps stashing it in a side-car *.aux.xml file...
