### ISSUE TITLE
Python gdal unretrievable datum?

### ISSUE THREAD

**Issue by itati01** [OSGeo/gdal#1512]
## Expected behavior and actual behavior.
Dear all,
I created a dummy raster file with QGIS and set the CRS to EPSG:25832: [test.zip](https://github.com/OSGeo/gdal/files/3149723/test.zip). gdalinfo shows the correct CRS but not the Python library. Any ideas what might be happening? Thanks in advance,
Andreas

1. This is what I get on the commandline with gdalinfo 2.4.0:
PROJCS["ETRS89 / UTM zone 32N",
    GEOGCS["ETRS89",
        DATUM["European_Terrestrial_Reference_System_1989",
            SPHEROID["GRS 1980",6378137,298.257222101,
                AUTHORITY["EPSG","7019"]],
            TOWGS84[0,0,0,0,0,0,0],
            AUTHORITY["EPSG","6258"]],
        PRIMEM["Greenwich",0,
            AUTHORITY["EPSG","8901"]],
        UNIT["degree",0.0174532925199433,
            AUTHORITY["EPSG","9122"]],
        AUTHORITY["EPSG","4258"]],
    PROJECTION["Transverse_Mercator"],
    PARAMETER["latitude_of_origin",0],
    PARAMETER["central_meridian",9],
    PARAMETER["scale_factor",0.9996],
    PARAMETER["false_easting",500000],
    PARAMETER["false_northing",0],
    UNIT["metre",1,
        AUTHORITY["EPSG","9001"]],
    AXIS["Easting",EAST],
    AXIS["Northing",NORTH],
    AUTHORITY["EPSG","25832"]]

2. This is what I get with Python: 
LOCAL_CS["ETRS89 / UTM zone 32N",GEOGCS["ETRS89",DATUM["unknown",SPHEROID["unretrievable - using WGS84",6378137,298.257223563],TOWGS84[0,0,0,0,0,0,0]],PRIMEM["Greenwich",0],UNIT["degree",0.0174532925199433]],AUTHORITY["EPSG","25832"],UNIT["metre",1,AUTHORITY["EPSG","9001"]]]

## Steps to reproduce the problem.

``` python
from osgeo import gdal
test = gdal.Open("test.tif")
test.GetProjectionRef()
```

## Operating system

Windows 10 64 bit

## GDAL version and provenance

the 2.3.3 version, installed with Anaconda 64bit (conda-forge)

**Comment by rouault** [comment]
Probably an issue with Anaconda distribution that doesn't define the GDAL_DATA environment variable to point to the directory where the GDAL .csv files are installed (such as geogcs.csv)

**Comment by itati01** [comment]
Tested Python under Ubuntu 18.04 and had no probs. Indeed, very likely an Anaconda issue.
