### ISSUE TITLE
GDAL 2.4.0 issue reading grid float rasters?

### ISSUE THREAD

**Issue by jgreif07** [OSGeo/gdal#1521]
I am having issues reading a certain grid float file (i can provided the file if need be) with gdal 2.4.0.  It will read fine with gdal 2.2.0 and other grid float files produced can be read by both versions.  I am curious if something changed from 2.2.0 in how grid float files are read?  I think this may be  bug and worth further investigation.

Thanks,

Jeremiah

**Comment by rouault** [comment]
Plese provide the file / a link to it

**Comment by jgreif07** [comment]
Here ya go, like i said it was produced using gdal 2.4.0, but wont' read in
2.4.0, others created the same way will.  But, it will sucessfully read in
gdal 2.2.0

thanks for looking into it

 usgs_ned_13_n61w153_gridfloat.flt
<https://drive.google.com/file/d/1raRNuZMP3FUfvDhfk_3SjkwlqodzvttO/view?usp=drive_web>

**Comment by rouault** [comment]
@jgreif07  How was this produced (which command line ) ? Is it a file supposed to be recognized by the EHdr driver ? In that case, there should be a side-car .hdr file accompanying it. Please provide it as well

**Comment by jgreif07** [comment]
it is produced using gdal_translate and yes suppose to be recognized by
EHDR driver, the rest of the files i've produced the same way are readable,
it is just this 1 giving issues... sorry i forgot to include the rest of
those files

**Comment by jratike80** [comment]
From the Filter encoding standard:

The <BBOX> element is defined as a convenient and more compact way of encoding the
very common bounding box constraint based on the gml:Envelope geometry. It is
equivalent to the spatial operation <Not><Disjoint> … </Disjoint></Not> meaning that
the <BBOX> operator should identify all geometries that spatially interact with the box.
If the optional <propertyName> element is not specified, the calling service must
determine which spatial property is the spatial key and apply the BBOX operator
accordingly. For feature types that has a single spatial property, this is a trivial matter.
For feature types that have multiple spatial properties, the calling service either knows
which spatial property is the spatial key or the calling service generates an exception
indicating that the feature contains multiple spatial properties and the <propertyName>
element must be specified. Of course a client application always has the options of
avoiding the exceptions by calling the DescribeFeatureType operation to get a
description of the feature type.

**Comment by jgreif07** [comment]
This doesn't really answer my question though why would this .flt read in
gdal 2.2.0 and not in 2.4.0?  What changed between versions that would
cause this?  there is something unique about only this one file (other .flt
read fine) that is causing gdal 2.4.0 to be unable to read it.

any help is greatly appreciated.

thanks

**Comment by rouault** [comment]
@jgreif07  please attach the .hdr file

**Comment by jratike80** [comment]
Sorry, comment pasted to all wrong Github project. I will delete it.

**Comment by jgreif07** [comment]
aaahhha no worries...thats why it didn't make any sense to me :)

**Comment by jgreif07** [comment]
also even here is that .hdr file

**Comment by rouault** [comment]
> also even here is that .hdr file

@jgreif07  I can't see it attached

**Comment by jgreif07** [comment]
weird, i've attached it twice now... is there another place i can put it?

**Comment by jgreif07** [comment]
try accessing it here:
https://drive.google.com/drive/folders/1pphdAhPRM881X3GoygfxTosrTRn_1tya?usp=sharing

**Comment by rouault** [comment]
Hum,  https://drive.google.com/drive/folders/1pphdAhPRM881X3GoygfxTosrTRn_1tya?usp=sharing is empty...

**Comment by jgreif07** [comment]
how about this?
https://drive.google.com/file/d/1TgzA4HW8ubCR-wCePALY2l4Pl5PNH-Kn/view?usp=sharing

**Comment by rouault** [comment]
OK, bug reproduced and fixed. A workaround is to set the GDAL_SKIP=GXF environment variable

**Comment by jgreif07** [comment]
awesome! thanks
