### ISSUE TITLE
gdaldem notworking

### ISSUE THREAD

**Issue by feivapo** [OSGeo/gdal#1524]
## Expected behavior and actual behavior.

Hi all, would appreciate some help in sorting out an issue that is not limiting the use of GDAL raster analysis tools. While trying to run any of the gdal raster analysis tools, the same error keeps popping up: "/bin/sh: gdaldem: command not found". I'm running Mac OS Mojave 10.14.4. QGIS version 3.6.2    

## Steps to reproduce the problem.
This is an example of the python 
gdaldem slope "/Users/~/S015E019_AVE_DSM.tif" /Users/~/Desktop/test_.tif -of GTiff -b 1 -s 1.0
## Operating system

Mac OS Mojave 10.14.4

## GDAL version and provenance

GDAL v. 2.4.1 + plugins (EWC, MrSID, GRASS). Downloaded from the compiled version from Kyngchaos.

**Comment by jratike80** [comment]
As written in the page where you created this issue, Questions should go to the gdal-dev mailing list (https://lists.osgeo.org/mailman/listinfo/gdal-dev) or other support forums. GitHub issues are for bug reports and suggestions for new features.

Your error  "/bin/sh: gdaldem: command not found" means that the QGIS installation on your Mac has something wrong and path to gdaldem utility is broken. So the right place to send mail is actually the qgis-users list.
