### ISSUE TITLE
gdal_contour produces erroneous results at fixed elevation levels that do not have 10 as a factor

### ISSUE THREAD

**Issue by dylanomics** [OSGeo/gdal#1544]
## Expected behavior and actual behavior.

Consider a raster layer of concentric squares with integer values from 8 to 13.
```
r <- raster::raster(ncol=11,nrow=11)
# concentric squares
for (col in 1:ncol(r)){
  for (row in 1:nrow(r)){
    new_row <- -abs(row - median(1:nrow(r)))
    new_col <- -abs(col - median(1:ncol(r)))
    r[row,col] <- min(new_row,new_col) + 13 # values -> [8,13]
  }
}
raster::writeRaster(r,"original.tif",overwrite=T)
```
We wish to build single contour lines at different levels using `gdal_contour -fl`
```
/path/to/gdal_contour/ -f "ESRI Shapefile" -fl "9" "original.tif" "contour_lines_9.shp"
```
The expected behaviour is for `gdal_contour` to produce a single feature (contour line) that is a box at the fixed level. For level 10, `gdal_contour` produces the intended result. However, for all other values `gdal_contour` produces three features, none of which correspond to the expected result (see [here](https://gist.github.com/dylanomics/6be9dfa0504d58f0cd314db7d409a3aa)).

When we scale the values by 10 in the following way
```
# solution: multiply by 10
r10x <- r*10
raster::writeRaster(r10x,"scaled.tif",overwrite=T)
```
we get the desired result for all contour lines at the corresponding scaled fixed levels.
```
/path/to/gdal_contour/ -f "ESRI Shapefile" -fl "90" "scaled.tif" "contour_lines_9.shp"
```

## Steps to reproduce the problem.

A minimum working example that re-produces the bug has been placed in a gist located [here](https://gist.github.com/dylanomics/6be9dfa0504d58f0cd314db7d409a3aa). The example can be run by downloading the repo and running `Rscript gdal_contour_mwe.R [</path/to/gdal_contour>]` at the command line. If no argument is provided, `R` will call the wrapper `gdalUtils::gdal_contour`, which will find your `GDAL` installation on your machine.

## GDAL and System Requirements

`GDAL 2.3.0` was used.

I am running macOS Mojave Version 10.14.2 and ran the code with R/3.5.0.  However, the bug appears to be present with different system configurations (e.g. `GDAL 2.3.2`, `R/3.5.1`).

**Comment by rouault** [comment]
You might want to try with GDAL 2.4 or above since gdal_contour was rewritten in that version

**Comment by dylanomics** [comment]
The bug is not present in GDAL 2.4.1. Thanks.
