### ISSUE TITLE
MRF TIF sanity checks

### ISSUE THREAD

**Issue by rouault** [OSGeo/gdal#1549]
@lucianpls While fixing https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=14782 per 8ce8a08e0922fa0214e4945182f13be111db9fd6, I see I've likely undone your recent commit bfdc46224b2300999d2c8dacd422794499edcd55
My commit is needed to fix the following issue:
unzip the attached .zip and do `gdalinfo /vsitar/test.tar/byte.mrf -checksum` (on a debug build so as to have the fuzzy-friendly pseudo-tar file format support
), and it crashes
[test.tar.zip](https://github.com/OSGeo/gdal/files/3202684/test.tar.zip)

**Comment by lucianpls** [comment]
@rouault Thanks, I'll take a look.
