### ISSUE TITLE
jpeg2000 files are loaded not completely

### ISSUE THREAD

**Issue by Alexandr-Lysikov** [OSGeo/gdal#1558]
I have problem with 2 jpeg2000 files.
In the 2.3, 2.4 and 3.0 versions with the extension gdal_ECW_JP2ECW.dll, both files are opened but file1.jp2 loaded completely, and the file2.jp2 not.
Without extension gdal_ECW_JP2ECW.dll both files are opened and on the contrary file1.jp2 loaded completely, and the file2.jp2 not.
[screenshot](http://lavresearch.com/gdal/bug_jp2000.png)

In 2.2.3 version both files are opened and loaded completely without extension gdal_ECW_JP2ECW.dll

I expected that both files will be loaded completely in new versions like in 2.2.3 version.
[file1.jp2](http://lavresearch.com/gdal/file1.jp2)
[file2.jp2](http://lavresearch.com/gdal/file2.jp2)

gdalinfo for files
[file1_with_plugins.info](https://github.com/Alexandr-Lysikov/gdal/blob/master/file1_with_plugins.info)
[file2_with_plugins.info](https://github.com/Alexandr-Lysikov/gdal/blob/master/file2_with_plugins.info)
[file1_without_plugins.info](https://github.com/Alexandr-Lysikov/gdal/blob/master/file1_without_plugins.info)
[file2_without_plugins.info](https://github.com/Alexandr-Lysikov/gdal/blob/master/file2_without_plugins.info)

Operating system Windows 10

**Comment by jratike80** [comment]
Where do those JPEG2000 files come? File2 may be somehow invalid.
Test with the OpenJPEG driver and GDAL 3.1dev gives 

```
gdal_translate -of GTiff -co tiled=yes -co compress=jpeg file2.jp2 file2.tif
Input file size is 5091, 6961
0ERROR 1: psImage->comps[0].data == nullptr
ERROR 1: psImage->comps[0].data == nullptr
ERROR 5: file2.jp2, band 1: Illegal nBlockXOff value (1464159776) in GDALRasterBand::TryGetLockedBlockRef()
ERROR 1: psImage->comps[0].data == nullptr
ERROR 5: file2.jp2, band 1: Illegal nBlockXOff value (1464159776) in GDALRasterBand::GetLockedBlockRef()
ERROR 5: file2.jp2, band 1: Illegal nBlockXOff value (-109024723) in GDALRasterBand::TryGetLockedBlockRef()
ERROR 5: file2.jp2, band 1: Illegal nBlockXOff value (-109024723) in GDALRasterBand::GetLockedBlockRef()
ERROR 1: psImage->comps[0].data == nullptr
ERROR 5: file2.jp2, band 1: Illegal nBlockXOff value (6029358) in GDALRasterBand::TryGetLockedBlockRef()
ERROR 5: file2.jp2, band 1: Illegal nBlockXOff value (6029358) in GDALRasterBand::GetLockedBlockRef()
ERROR 5: file2.jp2, band 1: Illegal nBlockXOff value (1311353664) in GDALRasterBand::TryGetLockedBlockRef()
ERROR 5: file2.jp2, band 1: Illegal nBlockXOff value (1311353664) in GDALRasterBand::GetLockedBlockRef()
ERROR 1: psImage->comps[0].data == nullptr
ERROR 1: file2.jp2, band 2: IReadBlock failed at X offset 0, Y offset 0: psImage->comps[0].data == nullptr
```

**Comment by antgraf** [comment]
I believe it is from Vermont Geodata Portal:
http://maps.vcgi.vermont.gov/opendata/tileselect_opendata.html?IndexLayerName=Index_NAIP_0_6M_CLRIR_2016&FolderURL=http://maps.vcgi.vermont.gov/gisdata/vcgi/imagery/NAIP/0_6M/CLRIR/2016/COMP/&cdownload=-1&InputLayerName=IMG_VCGI_NAIP2016_SP&InputFtype=imagery

**Comment by rouault** [comment]
This is a bug of openjpeg >= 2.2.0 and <= 2.3.0 (likely https://github.com/uclouvain/openjpeg/issues/1120). I've verified that file2.jp2 is read correctly by the GDAL JP2OpenJPEG driver with openjpeg 2.3.1

**Comment by Alexandr-Lysikov** [comment]
Oh, thanks, everything works, for some reason the new version of openjp2.dll is not included in GDAL
