### ISSUE TITLE
raster geopackage cant not set default value for type GDT_Byte

### ISSUE THREAD

**Issue by redheli** [OSGeo/gdal#1569]
Try to set default no data value for my raster gpkg (data type **GDT_Byte**)
I call `SetNoDataValue()` (C++ gdal 2.4.0), but it does not work.

check gdal source code, I find the `SetNoDataValue()` do nothing, if raster data type is GDT_Byte.

Is there reason behind?
Can I submit PR to make `SetNoDataValue()` work with `GDT_Byte`? 

```
CPLErr GDALGeoPackageRasterBand::SetNoDataValue( double dfNoDataValue )
{
    if( eDataType == GDT_Byte )
        return CE_None;
    ....
}
```

**Comment by rouault** [comment]
How you would that make work ? There is no nodata concept in GeoPackage tiled imagery

**Comment by redheli** [comment]
@rouault I think Raster GeoPackage has notdata concept, as it only store tiles which has actual data in sqlite.
so when retrieve tile id not find in db , it return data with default nodata value, for GDT_Byte, it is zero.

**Comment by rouault** [comment]
> has notdata concept, as it only store tiles which has actual data in sqlite.

That's not exactly how nodata works. You may have a tile with let's say values at 255, and value at 1, and decide that the nodata value is 1.
However the GeoPackage format itself has no provision to store that 1 is the nodata value. This might be a GDAL-only extension by storing it as a special metadata item
