### ISSUE TITLE
mitab - missing CP1250

### ISSUE THREAD

**Issue by bojanbizjak** [OSGeo/gdal#1571]
In the file mitab_imapinfofile.cpp, the definition for WindowsLatin2 is missing. It should be {"WindowsLatin2", "CP1250"}. 

Version: GDAL 3.0.0 (Master)

**Comment by rouault** [comment]
Looks like an easy pull request you could submit

**Comment by bojanbizjak** [comment]
I do not have the environment setup for making pull request. Would be possible for someone else to make the correction.

**Comment by rouault** [comment]
@bojanbizjak You can directly edit the file in github UI to submit a pull request
