### ISSUE TITLE
NITF file with bad UDID TRE won't parse IXSHD

### ISSUE THREAD

**Issue by manthey** [OSGeo/gdal#1578]
I have a NITF file with junk data in the UDID record (it contains an arbitrary string rather than a TRE).  Because GDAL's NITF reader concatenates the UDID and IXSHD records and then parses the joined TREs, it can't parse the valid TRE in the IXSHD.  It would be relatively easy to do some basic checks on the UDID contents and to ignore the UDID if it does't appear to be a valid TRE (if it is less than 11 bytes or the first length record is not all digits, for instance).

GDAL sensibly emits a failure message about failing to parse the combined TRE.  Instead, it could emit a message informing about the bad UDID contents.

I can make a PR if this is desired.  If it isn't, just close the issue.

## Expected behavior and actual behavior.

The current behavior is that neither the bad UDID nor the good IXSHD TREs are parsed.  It would be desirable if the bad UDID was skipped and the IXSHD was parsed.

## Steps to reproduce the problem.

Try to load a NITF file with both UDID and IXSHD records where the UDID is a text string instead of a TRE.

## Operating system

The behavior is the same on Ubuntu 18.04 and CentOS 6.

## GDAL version and provenance

master, built from source, as of 70d4dfe7fa6d9df3212854e471ead1232246e3dc.

**Comment by rouault** [comment]
> I can make a PR if this is desired.

sounds reasonable
