### ISSUE TITLE
Promote ogr_layer_algebra.py to official Python script

### ISSUE THREAD

**Issue by rouault** [OSGeo/gdal#1581]
The gdal/swig/python/samples/ogr_layer_algebra.py should be promoted to an official Python script

Steps:
- move it to gdal/swig/python/scripts
- create a new test script for it in autotest/pyscripts/test_ogr_layer_algebra.py
- write a documentation page in doc/source/programs/ogr_layer_algebra (and link it to the index)

**Comment by imshuv** [comment]
hey, i want to contribute in this project.. can anyone please guide me how to ?

**Comment by jatin142002** [comment]
I want to fix this issue , can anyone please help me with it ?? I need little bit of guidance so that I can make my first commit properly in this org .

**Comment by jatin142002** [comment]
I have completed the first step of this issue .
I have shifted ogr_layer_algebra.py  to gdal/swig/python/scripts

**Comment by rouault** [comment]
> I have shifted ogr_layer_algebra.py to gdal/swig/python/scripts

ah the ticket description is a bit outdated. There have been a rework in python utilities since it was written. There should be a simple calling ogr_layer_algebra.py script in swig/python/gdal-utils/scripts/  that calls the main script in swig/python/gdal-utils/osgeo_utils/ (usable as a function). You can look at other utilities for inspiration

**Comment by jatin142002** [comment]
Sir  , actually I am beginner what I am unable to understand is what  to do in test script ?? Could you please give some easy instructions so that I am able  to grab it . I read other test scripts but it is difficult for me to understand them .

**Comment by rouault** [comment]
Well, I don't know anything about your background, education, experience in programming or interest for geospatial, so it is hard to provide guidance. I don't want to discourage you, but I'd say that GDAL isn't propably the project most suited for beginners. The code base is non trivial, requires knowledge of the domain and our criterion for acceptance of pull requests are quite demanding. You need at least some familiarity with the language(s) of the part of the code base you touch, and with what it does. Perhaps that looking at the documentation for typos, grammar mistakes, broken links, etc would be a better possibility of contributing.

**Comment by kssvrk** [comment]
@rouault Is this issue still valid? Can I take this up

**Comment by rouault** [comment]
> Is this issue still valid? Can I take this up

yes

**Comment by kssvrk** [comment]
@rouault  Is there any version of existing documentation refering OGR_Layer_algebra other than the [RFC](https://gdal.org/development/rfc/rfc39_ogr_layer_algebra.html) that you know of?

**Comment by jratike80** [comment]
There is this wiki page https://trac.osgeo.org/gdal/wiki/LayerAlgebra and I suppose that @ajolma can be connected.

**Comment by rouault** [comment]
> Is there any version of existing documentation refering OGR_Layer_algebra other than the [RFC](https://gdal.org/development/rfc/rfc39_ogr_layer_algebra.html) that you know of?

the API documentation of the OGRLayer class: https://gdal.org/api/ogrlayer_cpp.html + source code at https://github.com/OSGeo/gdal/blob/master/ogr/ogrsf_frmts/generic/ogrlayer.cpp

**Comment by kssvrk** [comment]
@jratike80 those RFC 39 tests will be a good help. 
@rouault thanks for the pointers. I will see if i can submit a PR by next week for this issue.
