### ISSUE TITLE
Compiled for Android, missing ability to write DXF files

### ISSUE THREAD

**Issue by RGregat** [OSGeo/gdal#1582]
Hi,
I compiled based on this repository https://github.com/paamand/GDAL4Android a Version for Android. As far as I can tell, the gdal version is 2.4.
Everything works fine, I can do some transformations, read and write Shapefiles, create some WKT strings. But well there is one problem and I'm not sure how to solve it. I want to write DXF files with my Android-App but I'm not able to create a new DXF DataSource, I can create an instance for the Driver and load DXF-files, but I can't create new ones. If I do this, the DataSource is simply Null. Has someone encountered a similar issue? Is the capability to write DXF-Files deactivated?

**Comment by rouault** [comment]
The issue should rather be reported to https://github.com/paamand/GDAL4Android 
I guess this must be that the GDAL_DATA environment variable / configuration option is not set and GDAL thus can't find the needed header.dxf and trailer.dxf files which are located in the GDAL source tree in gdal/data
