### ISSUE TITLE
ApplyVerticalShiftGrid doesn't work with NAD grid g2012bu0.gtx 

### ISSUE THREAD

**Issue by vilaa** [OSGeo/gdal#1587]
## Expected behavior and actual behavior.

ApplyVerticalShiftGrid doesn't work with NAD grid *g2012bu0.gtx* from the [proj datum grid repo](https://github.com/OSGeo/proj-datumgrid)
 
Since the NAD grid extent is from 229 to 300 degrees of longitude while the raster to shift is located about -119° of longitude, i'm not certain that it's an issue strictly speaking. 

However using gdaltransform the vertical shift is actually applied for the raster coordinates. 

## Steps to reproduce the problem.

Here the file : 
[raster_step1_cecwj7yf.zip](https://github.com/OSGeo/gdal/files/3223982/raster_step1_cecwj7yf.zip)

Python code snippet :
```python
from osgeo import gdal

input_raster_path = "raster_step1_cecwj7yf.tiff"
grid_path = os.path.join("/usr/local/share/proj", "g2012bu0.gtx")
dsm_ds = gdal.Open(input_raster_path)
grid_ds = gdal.Open(grid_path)

# Since input raster SRS metadata are wrong and input SRS is actually in EPSG:4326
# we use the SRC_SRS option
shifted_ds = gdal.ApplyVerticalShiftGrid(dsm_ds, grid_ds, options=["SRC_SRS={}".format(grid_ds.GetProjection())])

driver = gdal.GetDriverByName('GTiff')
driver.CreateCopy("dsm_shifted.tiff", shifted_ds)
```
Pixel values of resulting file remain unchanged  

Behavior with gdal transform CLI
```bash
gdaltransform -ct "+proj=pipeline +step +proj=unitconvert +xy_in=deg +xy_out=rad +step +proj=vgridshift +grids=g2012bu0.gtx +step +proj=unitconvert +xy_in=rad xy_out=deg"
-119 34 0
>>> -119 34 36.8433990478803
```
## Operating system

Ubuntu 18.04.2 LTS

## GDAL version and provenance

Gdal 3.0.0 and Proj 6.1 executed in a docker container.
Docker image was built from the Dockerfile provided on this repository

**Comment by rouault** [comment]
No longer relevant since https://github.com/OSGeo/gdal/pull/4639
