### ISSUE TITLE
wrong rows selected by gdal_merge with -ul_lr ?

### ISSUE THREAD

**Issue by StefanEppert** [OSGeo/gdal#1599]
## Expected behavior and actual behavior.

I tried to merge two rasters with
gdal_merge.py -ul_lr 1.98 50.02 3.02 48.98 -o merge.tif testShift.xll.2.yll.49.tif testShift.xll.2.yll.50.tif
The test rasters contain constand values per row (1 to 100 north to south), the merged output skips row 99 and takes 98 instead.
Merging without -ul_lr seems to work fine.
 
## Steps to reproduce the problem.
gdal_merge.py -ul_lr 1.98 50.02 3.02 48.98 -o merge.tif testShift.xll.2.yll.49.tif testShift.xll.2.yll.50.tif
(files in testFiles.zip)

## Operating system

Ubuntu 18.04 64 bit

## GDAL version and provenance
2.1.3 (deb http://ppa.launchpad.net/ubuntugis/ppa/ubuntu xenial main)

[testFiles.zip](https://github.com/OSGeo/gdal/files/3231880/testFiles.zip)

**Comment by jratike80** [comment]
I can't reproduce with GDAL 3.1.4. Merge.tif has values 99 at the nothern edge and in the south all values 100, 99, 98... appear in the image.
