### ISSUE TITLE
gdal.Translate does not allow both resolution scaling and srcWin (ROI) from the input image

### ISSUE THREAD

**Issue by giladfr-rnd** [OSGeo/gdal#1601]
When trying to run the following python line:
```python
>>> gdal.Translate('', img, format='MEM', xRes=2, yRes=2, srcWin=[100, 100, 110, 110])
```

It returns an error:
```python
ERROR 5: The -tr option was used, but there's no geotransform or it is rotated.
This configuration is not supported.
```

Also running:
```python
gdal.Warp('', [img], format='MEM', transformerOptions=['SRC_METHOD=NO_GEOTRANSFORM', 'DST_METHOD=NO_GEOTRANSFORM'], resampleAlg=gdal.GRIORA_Bilinear, xRes=2, yRes=2, outputBounds=[100, 100, 110, 110])
```

runs, but the returned output has the ROI wrong.

**Comment by jratike80** [comment]
Is it true that geotransformation is not known? If GDAL does not know the resolution of the source image then how could it know what to do for changing the resolution?

**Comment by GoatWang** [comment]
Gdal use meter as its default unit for resolution, which means "xRes=2, yRes=2 " represents the target resolution is 2 meter. However, the geoTransform will be reset as (0.0, 1.0, 0.0, 0.0, 0.0, 1.0) when transformerOptions "transformerOptions=['SRC_METHOD=NO_GEOTRANSFORM', 'DST_METHOD=NO_GEOTRANSFORM']" is set. Also, (0.0, 1.0, 0.0, 0.0, 0.0, 1.0) means the pixel size of the image is 1 meter. As a result, the "xRes=2, yRes=2" represents the target resolution is the twice that of the original image.
