### ISSUE TITLE
Result is different between windows and macOS

### ISSUE THREAD

**Issue by chloe88** [OSGeo/gdal#1606]
the code   
CPLSetConfigOption("GDAL_DATA", "./src/gdal/data");
    //LOG_E("path is [%s] [%d]", path,insrs);
    //LOG_E("path is %d", insrs);
    OGRSpatialReference inRs,outRs;
    inRs.importFromEPSG(32648);
    outRs.importFromEPSG(4326);
    OGRCoordinateTransformation *poCT = OGRCreateCoordinateTransformation( &inRs, &outRs );
    double x =  645853, y = 3270537;
    if (poCT->Transform( 1, &x, &y)) {
        printf("x->%2f,y->%2f",x,y);
        delete poCT;

    }

macOS output  x->29.556031,y->106.505504 and windows output  x->106.505504,y->29.556031

**Comment by rouault** [comment]
likely one of your version uses GDAL 2.x and the other GDAL 3.0. In GDAL 3.0, there have been breaking changes regarding axis order: https://github.com/OSGeo/gdal/blob/master/gdal/MIGRATION_GUIDE.TXT#L7

**Comment by chloe88** [comment]
ok thank you
