### ISSUE TITLE
Debug message about SXF driver

### ISSUE THREAD

**Issue by rouault** [OSGeo/gdal#1607]
@drons Following latest changes in SXF driver, running GDAL with CPL_DEBUG=ON emits the following message "GDAL: Driver SXF that defines GDAL_DMD_OPENOPTIONLIST must also implement Identify(), so that it can be used"
This check is probably over-zealous, but it could be worthwhile, independently of it, if Identify() could be implemented

**Comment by drons** [comment]
A good idea. I'll try to do it a little later.
