### ISSUE TITLE
GISInternals no longer maintained?

### ISSUE THREAD

**Issue by ktheijs** [OSGeo/gdal#1610]
I have been using the C# binaries from GISInternals for some time now, but now it seems like it is no longer being maintained. The stable release is still on GDAL 2.4.0 and I get no response when I try to contact them. That's why I am trying to find out here if anyone knows if GISInternals is still being maintained and if we can expect a stable release of GDAL 3.0.0 any time soon?

**Comment by szekerest** [comment]
The package version update at GISInternals will be happening later today.

**Comment by ktheijs** [comment]
Great! Thank you.

**Comment by Otiel** [comment]
@szekerest Do you have any plan to publish the package for GDAL v3.1.0 on GISInternals?

**Comment by szekerest** [comment]
Yes, and I'm also preparing a complete refactor in the build set up where all the dependencies are upgraded to the latest versions.

**Comment by jratike80** [comment]
Fixed, outdated and not exactly GDAL bug at all, even did reach the right persons. Closing now.
