### ISSUE TITLE
ANDROID: GDAL Library Got crashed in 64 bit compatible APK

### ISSUE THREAD

**Issue by varshaj007** [OSGeo/gdal#1612]
## Expected behavior and actual behavior.

In 32 bit compitable APK the GDAL library is working properly. But in the case of 64 bit APK, the GDAL LIbrary will not work. because It is showing that there was no implementation found for the gdal library.
I analyzed the two apk(32 bit and 64 bit) by using apk analyzer,  We noticed that in 32 bit compatible folder maintains the .so files of the GDAL library. In the case of 64 bit, there will not maintain the .so file of the 64 bit compatible. So that's why the error showing "no implementation found" .

So my question is how to generate the .so files from GDAL libarary  by android studio? Is there any way to generate this??

## Operating system

Windows 10

## GDAL version and provenance

gdal 1.9.2
![32bit apkanlyser](https://user-images.githubusercontent.com/43340078/58856720-03148f80-86c1-11e9-9998-6c3c9f8c6be1.png)

![64bitapkanalyzer](https://user-images.githubusercontent.com/43340078/58856842-5686dd80-86c1-11e9-9400-ce23ce1b23a5.png)
![err](https://user-images.githubusercontent.com/43340078/58856858-630b3600-86c1-11e9-80a7-0838660edfce.png)
![libfilesnew](https://user-images.githubusercontent.com/43340078/58856870-6c949e00-86c1-11e9-90c8-55f42828b3b9.png)

**Comment by varshaj007** [comment]
![64bitapkanalyzer](https://user-images.githubusercontent.com/43340078/58856811-42db7700-86c1-11e9-966f-1344822c8de9.png)

**Comment by rouault** [comment]
Sounds more an issue how to build GDAL with AndroidStudio, rather than an issue with GDAL itself
