### ISSUE TITLE
Small but non-zero skew values break GeoTiff

### ISSUE THREAD

**Issue by DrJohnDale** [OSGeo/gdal#1615]
## Expected behavior and actual behavior.

Exported GeoTiff with certain affine transform values cannot be used (e.g. multiple merged together or loaded properly in, for example, qgis).  If the skew terms  in the affine transform are increased by an order of magnitude or forced to zero then the file is fine, can be merged with other geotiff files and loaded into qgis.

I have attached a bad version of the file, a zero skew version and 10 times skew version.  The gdalinfo for the files outputs the following:

[geotiff_files.zip](https://github.com/OSGeo/gdal/files/3253478/geotiff_files.zip)

bad version:
```
Driver: GTiff/GeoTIFF
Files: 260_676.tif
Size is 346, 417
Coordinate System is:
GEOGCS["WGS 84",
    DATUM["WGS_1984",
        SPHEROID["WGS 84",6378137,298.257223563,
            AUTHORITY["EPSG","7030"]],
        AUTHORITY["EPSG","6326"]],
    PRIMEM["Greenwich",0],
    UNIT["degree",0.0174532925199433],
    AUTHORITY["EPSG","4326"]]
GeoTransform =
  -1.489933837068185, 1.171620452781104e-08, 6.112335082519849e-09
  52.1909927657924, 3.303272951496163e-09, -8.188642652839917e-09
Metadata:
  AREA_OR_POINT=Area
Image Structure Metadata:
  INTERLEAVE=BAND
Corner Coordinates:
Upper Left  (  -1.4899338,  52.1909928) (  1d29'23.76"W, 52d11'27.57"N)
Lower Left  (  -1.4899313,  52.1909894) (  1d29'23.75"W, 52d11'27.56"N)
Upper Right (  -1.4899298,  52.1909939) (  1d29'23.75"W, 52d11'27.58"N)
Lower Right (  -1.4899272,  52.1909905) (  1d29'23.74"W, 52d11'27.57"N)
Center      (  -1.4899305,  52.1909916) (  1d29'23.75"W, 52d11'27.57"N)
Band 1 Block=346x5 Type=Float32, ColorInterp=Gray
  NoData Value=0
```
zero skew version:
```
Driver: GTiff/GeoTIFF
Files: 260_676_zero_skew.tif
Size is 346, 417
Coordinate System is:
GEOGCS["WGS 84",
    DATUM["WGS_1984",
        SPHEROID["WGS 84",6378137,298.257223563,
            AUTHORITY["EPSG","7030"]],
        AUTHORITY["EPSG","6326"]],
    PRIMEM["Greenwich",0],
    UNIT["degree",0.0174532925199433],
    AUTHORITY["EPSG","4326"]]
Origin = (-1.489933837068185,52.190992765792402)
Pixel Size = (0.000000011716205,-0.000000008188643)
Metadata:
  AREA_OR_POINT=Area
Image Structure Metadata:
  INTERLEAVE=BAND
Corner Coordinates:
Upper Left  (  -1.4899338,  52.1909928) (  1d29'23.76"W, 52d11'27.57"N)
Lower Left  (  -1.4899338,  52.1909894) (  1d29'23.76"W, 52d11'27.56"N)
Upper Right (  -1.4899298,  52.1909928) (  1d29'23.75"W, 52d11'27.57"N)
Lower Right (  -1.4899298,  52.1909894) (  1d29'23.75"W, 52d11'27.56"N)
Center      (  -1.4899318,  52.1909911) (  1d29'23.75"W, 52d11'27.57"N)
Band 1 Block=346x5 Type=Float32, ColorInterp=Gray
  NoData Value=0
```
10 times skew version:
```
Driver: GTiff/GeoTIFF
Files: 260_676_ten_skew.tif
Size is 346, 417
Coordinate System is:
GEOGCS["WGS 84",
    DATUM["WGS_1984",
        SPHEROID["WGS 84",6378137,298.257223563,
            AUTHORITY["EPSG","7030"]],
        AUTHORITY["EPSG","6326"]],
    PRIMEM["Greenwich",0],
    UNIT["degree",0.0174532925199433],
    AUTHORITY["EPSG","4326"]]
GeoTransform =
  -1.489933837068185, 1.171620452781104e-08, 6.112335082519849e-08
  52.1909927657924, 3.303272951496163e-08, -8.188642652839917e-09
Metadata:
  AREA_OR_POINT=Area
Image Structure Metadata:
  INTERLEAVE=BAND
Corner Coordinates:
Upper Left  (  -1.4899338,  52.1909928) (  1d29'23.76"W, 52d11'27.57"N)
Lower Left  (  -1.4899083,  52.1909894) (  1d29'23.67"W, 52d11'27.56"N)
Upper Right (  -1.4899298,  52.1910042) (  1d29'23.75"W, 52d11'27.62"N)
Lower Right (  -1.4899043,  52.1910008) (  1d29'23.66"W, 52d11'27.60"N)
Center      (  -1.4899191,  52.1909968) (  1d29'23.71"W, 52d11'27.59"N)
Band 1 Block=346x5 Type=Float32, ColorInterp=Gray
  NoData Value=0
```
The python code I used to export is:
``` 
def array_to_raster_2(array, file_name, x_pixels, y_pixels, aff, wkt_projection):
    driver = gdal.GetDriverByName('GTiff')
    data_set = driver.Create(
        file_name,
        x_pixels,
        y_pixels,
        1,
        gdal.GDT_Float32)

    data_set.SetGeoTransform(aff.to_gdal())
    data_set.GetRasterBand(1).SetNoDataValue(0.0)

    data_set.SetProjection(wkt_projection)
    data_set.GetRasterBand(1).WriteArray(array)
    data_set.FlushCache()  # Write to disk.
```

## Operating system
Ubuntu 18.04 64 bit

## GDAL version and provenance
the 2.2.3 version from ubuntu standard ppa

**Comment by rouault** [comment]
I don't understand what the issue is from your report. GeoTIFF with skew/rotational terms are perfectly valid. It is true they are less convenient for some purposes, but they remain valid nonetheless. You can create a "north-up" file with gdalwarp

**Comment by jratike80** [comment]
If I open all those images into QGIS 3.4.4 the "bad" image behaves sometimes badly when panning and zooming. I attached a screen capture, there should not be any gap between the images.
![bad_skew](https://user-images.githubusercontent.com/1751612/58911857-78b04800-8721-11e9-837e-7daa7c6fe9e2.png)

**Comment by DrJohnDale** [comment]
Hi, Thanks for the responses.

To be clear, the "bad" file is the file i want to produce, but it does not work when trying to merge with other geotiffs, and displays oddly in qgis (2.18.17) .

In the image below the skew should make the left edge follow the pink points, but it does not. also the image is repeating/tiling.
![image](https://user-images.githubusercontent.com/35268887/58941183-29930300-8773-11e9-956e-357c9c7f0503.png)
For comparison with the skew set to zero:
![image](https://user-images.githubusercontent.com/35268887/58940068-7b865980-8770-11e9-9111-509654309098.png)
and if the skew is multiplied by 10 (which is obviously does not follow the points):
![image](https://user-images.githubusercontent.com/35268887/58940750-3e22cb80-8772-11e9-855a-ed38d1d62a45.png)

As a note if the skew is multiple by smaller numbers, i.e. 4 then the image acts the same way as the 'bad' image but with a larger area.

While playing around I made the image 10 times wider in real space (same number of pixels) and i get the following.
![image](https://user-images.githubusercontent.com/35268887/58941552-f43ae500-8773-11e9-9a50-ed5d5bccea6f.png)
The wider version follows the pink points as expected. The GeoTiff info is:
```
Driver: GTiff/GeoTIFF
Files: 260_676.tif
       260_676.tif.aux.xml
Size is 346, 417
Coordinate System is:
GEOGCS["WGS 84",
    DATUM["WGS_1984",
        SPHEROID["WGS 84",6378137,298.257223563,
            AUTHORITY["EPSG","7030"]],
        AUTHORITY["EPSG","6326"]],
    PRIMEM["Greenwich",0],
    UNIT["degree",0.0174532925199433],
    AUTHORITY["EPSG","4326"]]
GeoTransform =
  -1.489933837068185, 1.171620723509789e-07, 6.112335082519849e-09
  52.19099276579239, 3.303271182584427e-08, -8.188642652839917e-09
Metadata:
  AREA_OR_POINT=Area
Image Structure Metadata:
  INTERLEAVE=BAND
Corner Coordinates:
Upper Left  (  -1.4899338,  52.1909928) (  1d29'23.76"W, 52d11'27.57"N)
Lower Left  (  -1.4899313,  52.1909894) (  1d29'23.75"W, 52d11'27.56"N)
Upper Right (  -1.4898933,  52.1910042) (  1d29'23.62"W, 52d11'27.62"N)
Lower Right (  -1.4898908,  52.1910008) (  1d29'23.61"W, 52d11'27.60"N)
Center      (  -1.4899123,  52.1909968) (  1d29'23.68"W, 52d11'27.59"N)
Band 1 Block=346x5 Type=Float32, ColorInterp=Gray
  Min=63.000 Max=184.000 
  Minimum=63.000, Maximum=184.000, Mean=125.626, StdDev=9.225
  NoData Value=0
  Metadata:
    STATISTICS_MAXIMUM=184
    STATISTICS_MEAN=125.62643988855
    STATISTICS_MINIMUM=63
    STATISTICS_STDDEV=9.2246203836106

```

I also realised I up loaded a different "bad" file, so i have added the zip again with the correct files and the additional wide file.
[geotiff_files.zip](https://github.com/OSGeo/gdal/files/3256219/geotiff_files.zip)

Cheers.

**Comment by rouault** [comment]
OK, the issue was with the inversion of the GeoTransform matrix that is needed for warping.
