### ISSUE TITLE
C# bindings Gdal.SetConfigOption method throws exception

### ISSUE THREAD

**Issue by Gigas002** [OSGeo/gdal#1616]
## Expected behavior and actual behavior.

I've just updated to **3.0.0** [GDAL](https://www.nuget.org/packages/GDAL/) and [GDAL.Native](https://www.nuget.org/packages/GDAL.Native/) packages. It seems, like `Gdal.SetConfigOption` throws an `Exception` every time it's called (it worked OK in 2.4.1 and previous versions). I can't even initialize **Gdal** using `GdalConfiguration` class.

## Steps to reproduce the problem.

Just add the packages to your solution and call `GdalConfiguration.ConfigureGdal()`. 
The first string, to throw an `Exception` in class `GdalConfiguration` is number 96 `Gdal.SetConfigOption("GDAL_DATA", gdalData);`. The following calls of `SetConfigOption` method also throws the same `Exception`.

## Operating system

Windows 10 x64

## GDAL version and provenance

**3.0.0** [GDAL](https://www.nuget.org/packages/GDAL/) and [GDAL.Native](https://www.nuget.org/packages/GDAL.Native/) c# bindings.

**Comment by szekerest** [comment]
This issue should rather added to https://github.com/gisinternals/buildsystem/issues

**Comment by szekerest** [comment]
The problem was fixed at nuget.org
