### ISSUE TITLE
OGRCoordinateTransformation::Transform on vertical projection doesn't effect on Z

### ISSUE THREAD

**Issue by aharondavid** [OSGeo/gdal#1622]
## Expected behavior 
Transform Vertical 

## Actual behavior.
OGRCoordinateTransformation::Transform effect only on X,Y coordinates despite to the fact that the egm96_15.gtx is exist in PROJ_LIB near to the proj.db.
I tried other vertical projection, none of them effect on Z.
the code below does change the Z if GDAL < 3

## Steps to reproduce the problem.

	auto* s = "COMPD_CS[\"WGS 84 + EGM96 geoid height\", GEOGCS[\"WGS 84\",DATUM[\"WGS_1984\",SPHEROID[\"WGS 84\",6378137,298.257223563,AUTHORITY[\"EPSG\",\"7030\"]],            AUTHORITY[\"EPSG\",\"6326\"]],PRIMEM[\"Greenwich\",0,AUTHORITY[\"EPSG\",\"8901\"]],UNIT[\"degree\",0.0174532925199433,            AUTHORITY[\"EPSG\",\"9122\"]],        AXIS[\"Latitude\",NORTH],        AXIS[\"Longitude\",EAST],        AUTHORITY[\"EPSG\",\"4326\"]],VERT_CS[\"EGM96 geoid height\",VERT_DATUM[\"EGM96 geoid\",2005,EXTENSION[\"PROJ4_GRIDS\",\"egm96_15.gtx\"],AUTHORITY[\"EPSG\",\"5171\"]],UNIT[\"metre\",1,AUTHORITY[\"EPSG\",\"9001\"]],AXIS[\"Up\",UP],AUTHORITY[\"EPSG\",\"5773\"]]]";
	auto *d = "GEOGCS[\"WGS 84\",DATUM[\"WGS_1984\",SPHEROID[\"WGS 84\",6378137,298.257223563,AUTHORITY[\"EPSG\",\"7030\"]],        AUTHORITY[\"EPSG\",\"6326\"]],    PRIMEM[\"Greenwich\",0,AUTHORITY[\"EPSG\",\"8901\"]],UNIT[\"degree\",0.0174532925199433,        AUTHORITY[\"EPSG\",\"9122\"]],    AXIS[\"Latitude\",NORTH],    AXIS[\"Longitude\",EAST],    AUTHORITY[\"EPSG\",\"4326\"]]";

	OGRSpatialReference source;
	source.SetAxisMappingStrategy(OAMS_TRADITIONAL_GIS_ORDER);
	OGRErr err1 = source.importFromWkt(s);

	OGRSpatialReference dest;
	dest.SetAxisMappingStrategy(OAMS_TRADITIONAL_GIS_ORDER);
	err1 = dest.importFromWkt(d);

	OGRCoordinateTransformation* ct = OGRCreateCoordinateTransformation(&source, &dest);
	double x[1] = { 34.99725975 }, y[1] = { 30.91412696 }, z[1] = { 1 };
	BOOL res = FALSE;
	if (ct != NULL)
		res = ct->Transform(1, x, y, z);

## Operating system
Windows 10

## GDAL version and provenance
GDAL 3.0.0 compiled with PROJ4 6.1

**Comment by rouault** [comment]
GDAL 3 requires 3D CRS on both sides of the transformation for Z values to be modified.

So replace your use of EPSG:4326 (WGS 84 2D) by EPSG:4979 (WGS 84 3D) for the destination, for example with dest.ImpotFromEPSG(4979).

```
$ echo "34.99725975 30.91412696 1" | gdaltransform -s_srs EPSG:4326+5773 -t_srs EPSG:4979
34.99725975 30.91412696 18.4886772534042
```

**Comment by aharondavid** [comment]
Hello Even.

Tank you so math for your answer.

We have a lot of WKT that saved in files, we load them by the new GDAL.
Is there more changes in backward capability in GDAL < 3 ?

**Comment by rouault** [comment]
> Is there more changes in backward capability in GDAL < 3 ?

presumably. Hard/impossible to list all of them; Basically in GDAL < 3, the WKT parser would accept things that could be pure garbage. In GDAL >= 3, it will only accepts WKT strings that can reconstruct valid CRS objects.
