### ISSUE TITLE
Importing WKT works in GDAL2.4.1 but fails in GDAL3.0.0

### ISSUE THREAD

**Issue by dfileccia** [OSGeo/gdal#1623]
Importing the following WKT text fails in works in GDAL2.4.1 but fails in GDAL3.0.0:

COMPD_CS["United States/NAD83/Arizona (Central)",PROJCS["",GEOGCS["",DATUM["North_American_Datum_1983",SPHEROID["GRS 1980",6378137,298.257222101],TOWGS84[0,0,0,0,0,0,0]],PRIMEM["Greenwich",0],UNIT["degree",0.01745329251994328],AXIS["Long",East],AXIS["Lat",North]],PROJECTION["Transverse_Mercator"],PARAMETER["latitude_of_origin",31],PARAMETER["central_meridian",-111.916666666667],PARAMETER["scale_factor",0.9999],PARAMETER["false_easting",213360],PARAMETER["false_northing",0],UNIT["metre",1],AXIS["East",East],AXIS["North",North]],VERT_CS["",VERT_DATUM["Ellipsoid",2002],UNIT["metre",1]]]

Here is my code to setup the transformations:
   // Create the SRS frames from the WKT
   OGRSpatialReference oWGS;
   oWGS.SetWellKnownGeogCS ("WGS84");

   OGRSpatialReference oWKT;
   oWKT.importFromWkt (wkt.toUtf8 ().constData ());

   // Set the transformations
   m_g2r = OGRCreateCoordinateTransformation (&oWGS, &oWKT);
   m_r2g = OGRCreateCoordinateTransformation (&oWKT, &oWGS);

Here is my usage code:
   double x = lla.lon;
   double y = lla.lat;
   double z = lla.height;

   // Perform the transformation from LLA to NEZ
   int ok = false;
   if (m_g2r) {
#if GDAL_VERSION_NUM < GDAL_COMPUTE_VERSION(3,0,0)
      ok = m_g2r->TransformEx (1, &x, &y, &z);
#else
      ok = m_g2r->Transform (1, &x, &y, &z);
#endif
   }

   // If we fail then return failed results
   if (!ok) {
      x = 0;
      y = 0;
      z = BAD_VALUE;
   }

This matches the tutorial but I think the problem is in the WKT since it is older. Is there a compatibility mode or what can I do to change my database of pre-defined WKTs to ones that work?

**Comment by rouault** [comment]
The issue is the axis directions East and North. Current PROJ 6 is probably a bit too strict, and expect uppercase values: EAST and NORTH. I'm pushing a fix there.
