### ISSUE TITLE
ElasticSearch: MapServer/OGR fails to get data from ElasticSearch 6 index

### ISSUE THREAD

**Issue by jbo-ads** [OSGeo/gdal#1628]
## Expected behavior and actual behavior.

Using OGR through MapServer, I am trying to draw a GeoJSON document that has been imported to an ElasticSearch index. Unfortunately, instead of producing a nice PNG image, MapServer only reports this error from OGR:

    msOGRFileNextShape(): OGR error. OGR GetNextFeature() error'd. Check logs.
    msOGRFileNextShape(): {"error":"Content-Type header [application/x-www-form-urlencoded] is not supported","status":406}

## Steps to reproduce the problem.

- Data import is successfully performed with:

      ogr2ogr ES: mydata.json

- MapFile configuration is as following:

      ...
      LAYER
        NAME mydata
        CONNECTIONTYPE OGR
        CONNECTION "ES:http://localhost:9200"
        DATA "mydata"
        ...

- MapServer is called from command line and is successful when directly using GeoJSON.

## Operating system

CentOS 7

## GDAL version and provenance

GDAL v2.4.0 compiled from GitHub sources.

MapServer is 7.4.0 and ElasicSearch is 6.2.1.

## Preliminary analysis of the issue

As far as I understand, ElasticSearch 6 needs that data it receives with HTTP's POST method be typed as **Content-Type: application/json**.

In `ogrelasticdatasource.cpp`, this is correctly set in `UploadFile()` method but not in `RunRequest()` method.

        papszOptions = CSLAddNameValue(papszOptions, "HEADERS",
                "Content-Type: application/json; charset=UTF-8");

Indeed, when that piece of code is copied from `UploadFile()` to `RunRequest()`, just after setting `POSTFIELDS` option, MapServer behaves as expected and returns a nice PNG map.

I prepared a fix that can be submitted as a PR if this analysis is confirmed.

**Comment by rouault** [comment]
@nickpeihl Can you confirm that "ElasticSearch 6 needs that data it receives with HTTP's POST method be typed as Content-Type: application/json" ? (and that it would also be fine for older versions)

**Comment by jbo-ads** [comment]
This is what I understand from a previous issue: #1125.

**Comment by rouault** [comment]
> This is what I understand from a previous issue: #1125.

ok, go ahead with a PR then
