### ISSUE TITLE
VRT: VRTAddBand return type is inconsistent in C and C++

### ISSUE THREAD

**Issue by MinluLi** [OSGeo/gdal#1637]
## Expected behavior and actual behavior.

The return type of VRTAddBand is int, but the return type of interface corresponding to C++ is CPLErr, which is inconsistent.

## Steps to reproduce the problem.

C API: `int CPL_DLL CPL_STDCALL VRTAddBand( VRTDatasetH, GDALDataType, char ** );`

https://github.com/OSGeo/gdal/blob/e735343071f2675cda2e834fb4e0614515b6f028/gdal/frmts/vrt/gdal_vrt.h#L87

C++ API: 'virtual CPLErr AddBand( GDALDataType eType, char **papszOptions=nullptr ) override;'

https://github.com/OSGeo/gdal/blob/e735343071f2675cda2e834fb4e0614515b6f028/gdal/frmts/vrt/vrtdataset.h#L232

## Operating system

None

## GDAL version and provenance

github master

**Comment by rouault** [comment]
@mloskot @MinluLi 's point is relevant. This is an historical oversight. CPLErr being a C enumeration, VRTAddBand() should also have returned it. I've added a documentation note to make that clearer. (I think we could also fix the return type to be CPLErr without breaking backward compatibility, but I don't think that's worth the risk)

**Comment by MinluLi** [comment]
@rouault In C++ the AddBand() function returns CE_None(as 0) on success，in C API, CE_None should be converted to int is 0(maybe FALSE), so this is contradiction.

**Comment by rouault** [comment]
@MinluLi  I think the issue is now solved with the documentation note I added. There are a number of C API where 0 as a return code means success, so you can't assume anything from a int return type. So in that particular case, success is when VRTAddBand() == CE_None

**Comment by mloskot** [comment]
@rouault I wasn't aware. Seems like I might have got confused with the old `OGRERR_*` issue (`#define` vs enum). @MinluLi  Apologies for confusion.

**Comment by MinluLi** [comment]
@rouault @mloskot I understand. Thank you for your work.
