### ISSUE TITLE
GDAL300.DLL OGRGeometryFactory::TransformWithOptionsCache link errors

### ISSUE THREAD

**Issue by cgohlke** [OSGeo/gdal#1639]
## Expected behavior and actual behavior.

I have built GDAL-3.0.0 binaries and Python bindings from source (current 3.0 release branch) on Windows using Visual Studio 2015 and 2017, 32 and 64-bit ([binaries](https://www.lfd.uci.edu/~gohlke/pythonlibs/#gdal)).

Building the [rasterio‑1.0.23](https://github.com/mapbox/rasterio) and [Fiona‑1.8.6](https://github.com/Toblerity/Fiona) Python packages by @sgillies against the GDAL300.DLL fail with the following link errors:
```
_warp.obj : error LNK2001: unresolved external symbol "public: __cdecl OGRGeometryFactory::TransformWithOptionsCache::~TransformWithOptionsCache(void)" (??1TransformWithOptionsCache@OGRGeometryFactory@@QEAA@XZ)
_warp.obj : error LNK2001: unresolved external symbol "public: __cdecl OGRGeometryFactory::TransformWithOptionsCache::TransformWithOptionsCache(void)" (??0TransformWithOptionsCache@OGRGeometryFactory@@QEAA@XZ)
build\lib.win-amd64-3.8\rasterio\_warp.cp38-win_amd64.pyd : fatal error LNK1120: 2 unresolved externals
```
```
_transform.obj : error LNK2001: unresolved external symbol "public: __cdecl OGRGeometryFactory::TransformWithOptionsCache::~TransformWithOptionsCache(void)" (??1TransformWithOptionsCache@OGRGeometryFactory@@QEAA@XZ)
_transform.obj : error LNK2001: unresolved external symbol "public: __cdecl OGRGeometryFactory::TransformWithOptionsCache::TransformWithOptionsCache(void)" (??0TransformWithOptionsCache@OGRGeometryFactory@@QEAA@XZ)
build\lib.win-amd64-3.8\fiona\_transform.cp38-win_amd64.pyd : fatal error LNK1120: 2 unresolved externals
```
Both packages build successfully against GDAL-2.4.1.

It looks like OGRGeometryFactory::TransformWithOptionsCache constructor and destructor are not exported from the GDAL300.DLL.

## Steps to reproduce the problem.

Build rasterio or Fiona Python packages against GDAL-3.0.0 on Windows.

## Operating system

Windows 10

## GDAL version and provenance

GDAL-3.0.0 from current 3.0 release branch
```
commit 8dd62073c3c99950d394db1b926438ccbc6ab232 (HEAD -> release/3.0, origin/release/3.0)
```
Using proj-6.1.0 and geos-3.4.3 in case that matters.

**Comment by cgohlke** [comment]
I get the same link errors using `libgdal-3.0.0-h7dc65ee_3.tar.bz2` from [conda-forge](https://anaconda.org/conda-forge/libgdal/files).

**Comment by rouault** [comment]
@cgohlke Does changing `class TransformWithOptionsCache` at line 2879 of ogr/ogr_geometry.h to `class CPL_DLL TransformWithOptionsCache` fix things ?

**Comment by cgohlke** [comment]
Thank you! Using `class CPL_DLL TransformWithOptionsCache` fixes this issue. `rasterio` builds successfully. `Fiona` fails with another link error `error LNK2001: unresolved external symbol OSRFixup`, but that's a [known issue](https://github.com/Toblerity/Fiona/issues/745).
