### ISSUE TITLE
How can I know about GTX grid that is not exist in PROJ_LIB

### ISSUE THREAD

**Issue by aharondavid** [OSGeo/gdal#1640]
## Expected behavior

auto wkt; //the wkt contain a GTX grid file that doesn't exist in PROJ_LIB.
the expected behavior is error returned from the the following call:
OGRErr error = OGRSpatialReference::importFromWkt(wkt);

##actual behavior.
error = OGRERR_NONE

## Steps to reproduce the problem.
Delete the egm96_15.gtx from the PROJ_LIB.
then, execute:
OGRErr error  = OGRSpatialReference::importFromEPSG(4979);

or

auto wkt = "COMPD_CS[\"NAD83_Illinois_East + egm96 geoid height\",    PROJCS[\"NAD83_Illinois_East\",        GEOGCS[\"NAD83\",            DATUM[\"North_American_Datum_1983\",                SPHEROID[\"GRS 1980\",6378137,298.257222101,                    AUTHORITY[\"EPSG\",\"7019\"]],                AUTHORITY[\"EPSG\",\"6269\"]],            PRIMEM[\"Greenwich\",0],            UNIT[\"degree\",0.0174532925199433,                AUTHORITY[\"EPSG\",\"9122\"]],            AUTHORITY[\"EPSG\",\"4269\"]],        PROJECTION[\"Transverse_Mercator\"],        PARAMETER[\"latitude_of_origin\",36.666666666667],        PARAMETER[\"central_meridian\",-88.333333333333],        PARAMETER[\"scale_factor\",0.999975],        PARAMETER[\"false_easting\",300000],        PARAMETER[\"false_northing\",0],        UNIT[\"metre\",1,            AUTHORITY[\"EPSG\",\"9001\"]],        AXIS[\"Easting\",EAST],        AXIS[\"Northing\",NORTH]],    VERT_CS[\"EGM96 geoid height\",        VERT_DATUM[\"EGM96 geoid\",2005,            EXTENSION[\"PROJ4_GRIDS\",\"egm96_15.gtx\"],            AUTHORITY[\"EPSG\",\"5171\"]],        UNIT[\"metre\",1,            AUTHORITY[\"EPSG\",\"9001\"]],        AXIS[\"Up\",UP],        AUTHORITY[\"EPSG\",\"5773\"]]]"

OGRErr error = OGRSpatialReference::importFromWkt(wkt);

## Operating system
Windows 10

## GDAL version and provenance
GDAL 3.0.0

**Comment by rouault** [comment]
EPSG:4979 is a WGS84 Geographic 3D CRS. It doesn't require grids. It is perfectly well defined by itself.

Regarding your WKT with a EXTENSION["PROJ4_GRIDS","egm96_15.gtx"], it is expected that on import you won't get errors even if a mentionned grid is missing.
What you can do is use OGRSpatialReference::exportoToProj4(), and use the returned string as the argument of proj_create() (from "proj.h"). It will fail if the grid is missing.

**Comment by aharondavid** [comment]
Hello Even.

By implementing your suggested above, are there more errors that will be catch except from gtx grid is missing? if the answer is yes, what kind of errors should I expected ?

My code:

OGRSpatialReference SRS;
OGRErr error = SRS.importFromWkt(pWKT);
if (error == OGRERR_NONE)
{

              char* pProj4Str=nullptr;
              SRS.exportToProj4(&pProj4Str);
              PJ* pj = proj_create(m_pPJ_LOG_CONTEXT, pProj4Str);
              if (!pj)
              {
                     // gtx grid is missing, display an error.

                     SL_USES_CONVERSION;
                     std::wstring str = SA2T(pProj4Str);
                     auto start_pos = str.rfind(L"+geoidgrids=");
                     if (start_pos != std::string::npos)
                     {
                           start_pos += std::string("+geoidgrids=").length();
                           auto end_pos = str.find(' ', start_pos);
                           if (end_pos == std::string::npos)
                                  end_pos = str.length();
                           std::wstring str_gtx_file_name = str.substr(start_pos, end_pos- start_pos);
                           PRINT_ERROR(_T("Fail to create projection, because gtx file - %s is missing"),str_gtx_file_name.c_str());

                     }
              }
              if(pProj4Str)
                     OGRFree(pProj4Str);
              if(pj)
                     proj_destroy(pj);

       }
