### ISSUE TITLE
GRIB: fails to build with `ENABLE_TDLPACK`

### ISSUE THREAD

**Issue by TheDorkKnight** [OSGeo/gdal#1648]
This issue relates to pull request #1009, where this build configuration was broken.

### Expected

GDAL builds with `ENABLE_TDLPACK` defined

### Actual

It does not build, since `DataSource` definition was removed in #1009

## Steps to reproduce the problem.

Modify `gdal/frmts/grib/GNUMakefile` to:
  - include `tdlpack.o` in `OBJ`
  - define `ENABLE_TDLPACK`

## Operating system

Demonstrable with Ubuntu 16.04 64 bit, but should be reproducible with any OS

## GDAL version and provenance

Build attempted in tagged version 2.4.1

**Comment by rouault** [comment]
And is it an issue ? I remember I asked on the mailing list what TDLPACK was, and nobody could figure out what this beast it, so this was removed per 394da1314428e6571ca1b24cb43ae32f880b2c7c , and nobody complained until now

**Comment by TheDorkKnight** [comment]
It's not a big issue, just a little problem for developers to trip over (especially if they're using their own build scripts instead of GDAL's).

I just figured *"Why keep blocks of `#ifdef`-d out code if they won't even compile when you enable them?"*

So it seemed logical to either:

 - delete tdlpack source files and `#ifdef ENABLE_TDLPACK` blocks
 - make changes as in #1009 to switch the tdlpack code over to `VSILFILE`

**Comment by TheDorkKnight** [comment]
But for my own part, I don't care if tdlpack stays or goes

**Comment by rouault** [comment]
The thing is is that the grib code comes from the upstream degrib project from which we resync from time to time (every 10 years ;-)), so keeping that dead code between #ifdef makes it a bit easier at the next resync to figure out that we disabled voluntarily this code, rather than new code appearing in degrib.

**Comment by TheDorkKnight** [comment]
Okay, sounds fine. Then might I suggest:

```c++
#if 0
//...
#endif
```

instead of:


```c++
#ifdef ENABLE_TDLPACK
//...
#endif
```

(including around the entire tdlpack source files).

This would more accurately capture your intent.

**Comment by rouault** [comment]
> ```c++
> #if 0
> ```

Would be fine. Do you want to submit a PR for that ?

**Comment by TheDorkKnight** [comment]
> Would be fine. Do you want to submit a PR for that ?

Sure, can do.
