### ISSUE TITLE
Using Gdal_cal.py in Anaconda,  opens Python idle instead of running the command

### ISSUE THREAD

**Issue by rupal-brahmbhatt** [OSGeo/gdal#1653]
Using Gdal_cal.py in Anaconda pop up Python idle instead of running the command
Any Gdal.py command do not run and opens Python idle with below text in that

#!C:/Users/rupal/Anaconda3\python.exe
### # EASY-INSTALL-SCRIPT: 'GDAL==2.3.3','gdal_calc.py'
__requires__ = 'GDAL==2.3.3'
__import__('pkg_resources').run_script('GDAL==2.3.3', 'gdal_calc.py')

## Expected behavior and actual behavior.

For example (please modify !!!): I expected to be able to open this raster file (with a link to
the raster file, or it as an attachment) and it returns an error message
instead.

## Steps to reproduce the problem.

For example (please modify !!!): "gdalinfo myfile"

## Operating system

For example (please modify !!!): Ubuntu 16.04 64 bit

## GDAL version and provenance

For example (please modify !!!): the 2.2.3 version from ubuntugis-unstable PPA

**Comment by rouault** [comment]
Should be reported to the maintainers of the GDAL Anaconda package
