### ISSUE TITLE
COG fails to create with BIGTIFF_OVERVIEW

### ISSUE THREAD

**Issue by blacha** [OSGeo/gdal#1655]
## Expected behavior and actual behavior.

I expected to be able to create a large COG using `gdal_translate -of COG --config BIGTIFF_OVERVIEW YES`

Instead a error occurs
> ERROR 1: TIFFAppendToStrip:Maximum TIFF file size exceeded. Use --config BIGTIFF_OVERVIEW YES configuration option.

## Steps to reproduce the problem.
I am using around 35GB of tifs then attempt to create a COG via the following command

```
docker run -v $PWD:$PWD -it osgeo/gdal:ubuntu-small-latest gdal_translate \
 -of COG \
 -co COMPRESS=WEBP \
 -co NUM_THREADS=ALL_CPUS \
 -co BIGTIFF=YES \
 --config BIGTIFF_OVERVIEW YES \
 --config GDAL_CACHEMAX 24576 \
 big_tif.vrt big_tif.webp.cog.tif
```

## Operating system

Ubuntu 19.04

## GDAL version and provenance

Docker osgeo/gdal:ubuntu-small-latest
 `sha256:1536b0177198f1d59e4d6731e0d9c1f5c06333afcb5aa911883a84dd9e81aaa8`

**Comment by blacha** [comment]
I have tested 16eb684 and it did not fix my issue. 

I have done a little bit of digging:

In my test case the overview file already exists when the overview is about to be made  which causes it to be opened as a Tiff rather than creating a Big Tiff

https://github.com/OSGeo/gdal/blob/master/gdal/frmts/gtiff/gt_overview.cpp#L666

Breaking at this point shows the file does indeed exist, although it is empty.
```
# ls -al *.tmp
-rw-r--r-- 1 root root 0 Jun 17 09:01 bg43.vrt.ovr.tmp
```

After adding some additional logging, https://github.com/blacha/gdal/commit/da4b2aa54c24f3ebb52762d188ebf1613a5a6b39
 (Forgive my c code, i'm quite rusty) it appears the `VSIFOpenL` is creating the 0 byte file

Output of the logs
```
BLACHA: Exists_Before=-1 bg43.vrt.ovr.tmp,
BLACHA: Exists_After=0
BLACHA: Exists_Close=0 bg43.vrt.ovr.tmp
```

**Comment by rouault** [comment]
> I have tested [16eb684](https://github.com/OSGeo/gdal/commit/16eb684ad97ea89148e1a4c85457f295c4d9c319) and it did not fix my issue.

Ah sorry for this. 348eb95 should really fix the issue.

**Comment by blacha** [comment]
> Ah sorry for this. [348eb95](https://github.com/OSGeo/gdal/commit/348eb95766f751c046b5e04dfcfd013d972beb6c) should really fix the issue.

It looks like that has indeed fixed my problem, I have managed to generate the COG that it was failing on.

Thanks!
