### ISSUE TITLE
gdal warp with cutline produces empty output with unusual datatypes scale combination

### ISSUE THREAD

**Issue by cpaulik** [OSGeo/gdal#1656]
## Expected behavior and actual behavior.

Running gdalwarp with a cutline should cutout the original file while keeping the data intact.

For the file attached to this bug report with the following bands:

```
Band 1 Block=281x1 Type=Float64, ColorInterp=Gray
  Min=11.200 Max=13.700 
  Minimum=11.200, Maximum=13.700, Mean=12.019, StdDev=0.412
  NoData Value=65535
  Offset: 0,   Scale:0.01
Band 2 Block=281x1 Type=Float64, ColorInterp=Undefined
  Min=-300.000 Max=-300.000 
  Minimum=-300.000, Maximum=-300.000, Mean=-300.000, StdDev=0.000
  NoData Value=65535
  Offset: 0,   Scale:0.01
```

the ouput is empty.

## Steps to reproduce the problem.

`gdalwarp -of GTiff -cutline 6004.shp -crop_to_cutline test_roi.tif output.tif`

## Operating system

Arch linux

## GDAL version and provenance
`gdal                      3.0.0            py27hf242f0b_3    conda-forge`

But also tested on `gdal 2.4.1` 

Files used [bug-report.zip](https://github.com/OSGeo/gdal/files/3301396/bug-report.zip)

**Comment by jratike80** [comment]
You mention unusual datatype scale combination in the title. Does it mean that with some other datatype-scale combination the result is good?

**Comment by cpaulik** [comment]
Yes, I've tried to cut another geotiff with this spapefile without issues. 

Also if you set `-ot uint16` in the gdalwarp command there is an output that is more than just no data values.
