### ISSUE TITLE
MVT tile produced by GDAL doesn't seem valid

### ISSUE THREAD

**Issue by drnextgis** [OSGeo/gdal#1664]
I've sent tile made with GDAL here https://github.com/mapbox/pbf/issues/104 and it turns out that this tile is not valid.

**Comment by rouault** [comment]
This is a gzipped compressed PBF tile. Did you uncompress it before passing it to https://github.com/mapbox/pbf/blob/master/index.js ?

**Comment by drnextgis** [comment]
Actually no, nice catch. Sorry for noise.
