### ISSUE TITLE
Huge memory requirements while generating MVT

### ISSUE THREAD

**Issue by copierrj** [OSGeo/gdal#1673]
## Expected behavior and actual behavior.

While converting a large set of GML files into MVT tilesets using ogr2ogr we expected memory usage to be fairly constant and related to the size of processed geometries.

We discovered that memory requirements where quite acceptable for most files but occasionally the memory requirements where much (order of magnitude) higher. We tried to narrow it down and discovered that the file size didn't really matter. While closely examining the files that required the highest amount of memory to process we discovered that all those files contained one or more rather complicated (but not necessary large) geometries. 

Confirmed to increase memory usage are:
- polygons with many interior rings
- multipolygons with significant amount of total exterior rings
- polygons with curves in rings

## Steps to reproduce the problem.

ogr2ogr -f MVT NL.IMRO.0363.GA1601PBPGST-OW01 -a_srs "EPSG:28992" -fieldTypeToString StringList,IntegerList,Date --config GML_SKIP_RESOLVE_ELEMS HUGE --config GML_SKIP_RESOLVE_ELEMS NONE --config GML_EXPOSE_FID NO --config GML_EXPOSE_GML_ID NO -dsco MINZOOM=1 -dsco MAXZOOM=11 -dsco TILING_SCHEME=EPSG:28992,-285401.92,903402.0,880803.84 NL.IMRO.0363.GA1601PBPGST-OW01-simplified.gml

[NL.IMRO.0363.GA1601PBPGST-OW01-simplified.zip](https://github.com/OSGeo/gdal/files/3323976/NL.IMRO.0363.GA1601PBPGST-OW01-simplified.zip)

This particular GML file required almost 1GiB of memory to process.

## Operating system

Ubuntu 19.04 64 bit

## GDAL version and provenance

GDAL 2.4.0, released 2018/12/14 (installed from default Ubuntu repository)

**Comment by rouault** [comment]
I've just pushed a fix for that in master. This reduces the memory usage to ~ 300 MB. It can technically be backported to 3.0 and 2.4, but this is a bit risky (same geometry object shared accross several processing threads, which should normally be fine in the current implementation, but who knows...), so I'd prefer to see this is a bit more tested before.
A workaround to avoid the issue (at the expense of longer processing time) is to disable multi-threading by adding `--config GDAL_NUM_THREADS 0`

**Comment by copierrj** [comment]
Setting GDAL_NUM_THREADS totally works for us. Thanks!
