### ISSUE TITLE
MSSQLSpatial: EMPTY geometries may cause a crash in the driver

### ISSUE THREAD

**Issue by szekerest** [OSGeo/gdal#1674]
Some examples:

POINT EMPTY
MULTIPOLYGON (EMPTY, EMPTY)
MULTIPOLYGON(((0 0, 0 1, 1 1, 0 0),(0.15 0.25, 0.15 0.75, 0.65 0.75, 0.15 0.25)), EMPTY)
MULTIPOLYGON(((0 0, 0 1, 1 1, 0 0),(0.15 0.25, 0.15 0.75, 0.65 0.75, 0.15 0.25)), EMPTY, ((2 2, 1 0, 1 1, 2 2)))

**Comment by rouault** [comment]
Any remaining action on that ticket ?
