### ISSUE TITLE
gdallocationinfo prints no error for non-existent file

### ISSUE THREAD

**Issue by kannes** [OSGeo/gdal#1684]
## Expected behavior and actual behavior.

Running `gdallocationinfo` on a non-existent file will simply return to the command line without an error message. The exit signal however seems correct.

`$ gdallocationinfo foo && echo "no error" || echo "error"`

Please add a user-friendly message when `gdallocationinfo` cannot access the specified path.

## Steps to reproduce the problem.

`$ gdallocationinfo foo`

## Operating system

Archlinux

## GDAL version and provenance

https://www.archlinux.org/packages/community/x86_64/gdal/: GDAL 2.4.1, released 2019/03/15

**Comment by jratike80** [comment]
Your command could alternatively give another error about missing x and y parameters but the result is the same with a correct syntax

`gdallocationinfo foo.tif 1 1`

**Comment by kannes** [comment]
Thanks Even!

@jratike80 if you mean that the tool does not output an error if there are no x and y parameters, that is by design as it waits for stdin. It's pretty hidden that it does that so I added a tiny example to the docs: https://github.com/OSGeo/gdal/pull/1685

**Comment by jratike80** [comment]
Thanks, I got wrong feeling that x and y are compulsory by looking at the help that the utility prints:

```
gdallocationinfo
Usage: gdallocationinfo [--help-general] [-xml] [-lifonly] [-valonly]
                        [-b band]* [-overview overview_level]
                        [-l_srs srs_def] [-geoloc] [-wgs84]
                        [-oo NAME=VALUE]* srcfile x y
```

Documentation has it as [x y].

**Comment by rouault** [comment]
> if you mean that the tool does not output an error if there are no x and y parameters, that is by design as it waits for stdin. It's pretty hidden

https://github.com/OSGeo/gdal/pull/1686 should make it obvious
