### ISSUE TITLE
ogr2ogr doesn't work with PostgreSQL 12beta

### ISSUE THREAD

**Issue by robe2** [OSGeo/gdal#1692]
## Expected behavior and actual behavior.

I was testing out a geopackage this query on PostgreSQL 12 beta2 (I know it's not released yet)
using the geopackage from https://gadm.org/download_world.html
(I used the world version, but I think any will d)

## Steps to reproduce the problem.
`ogr2ogr -f "PostgreSQL" PG:"host=localhost user=postgres port=5449 dbname=postgis_in_action password=mypassword" gadm36_levels.gpkg -lco GEOMETRY_NAME=geom -where "gid_0='USA'" -t_srs "EPSG:2163" -nln "us.admin_boundaries" level5`

Instead of loading into the database, returns this error:

> ERROR 1: ERROR:  column s.consrc does not exist
> LINE 1: ...nrelid = c.oid AND a.attnum = ANY (s.conkey) AND (s.consrc L...
>                                                              ^
> HINT:  Perhaps you meant to reference the column "s.conkey" or the column "s.conbin".
> 
> ERROR 1: ERROR:  column s.consrc does not exist
> LINE 1: ...nrelid = c.oid AND a.attnum = ANY (s.conkey) AND (s.consrc L...
>                                                              ^
> HINT:  Perhaps you meant to reference the column "s.conkey" or the column "s.conbin".
> 
> ERROR 1: ERROR:  current transaction is aborted, commands ignored until end of transaction block
> 
> ERROR 1: ERROR:  current transaction is aborted, commands ignored until end of transaction block
> 
> ERROR 1: ERROR:  current transaction is aborted, commands ignored until end of transaction block
> 
> ERROR 1: ERROR:  current transaction is aborted, commands ignored until end of transaction block
> 
> ERROR 1: ERROR:  current transaction is aborted, commands ignored until end of transaction block
> 
> ERROR 1: CREATE TABLE "us"."admin_boundaries" ( "fid" SERIAL, PRIMARY KEY ("fid"), "gid_0" VARCHAR, "name_0" VARCHAR, "gid_1" VARCHAR, "name_1" VARCHAR, "gid_2" VARCHAR, "name_2" VARCHAR, "gid_3" VARCHAR, "name_3" VARCHAR, "gid_4" VARCHAR, "name_4" VARCHAR, "gid_5" VARCHAR, "name_5" VARCHAR, "type_5" VARCHAR, "engtype_5" VARCHAR, "cc_5" VARCHAR, "geom" geometry(MULTIPOLYGON,1) )
> ERROR:  current transaction is aborted, commands ignored until end of transaction block

I think this is caused by changes in PostgreSQL 12, similar to the issue we faced in PostGIS -  
detail of issue (and resolution) at https://trac.osgeo.org/postgis/ticket/4231

## Operating system
Windows 10 64-bit 
## GDAL version and provenance
GDAL 3.1.0dev from - http://download.gisinternals.com/sdk/downloads/release-1911-x64-gdal-mapserver.zip (build dated 2019-06-30 23:49

**Comment by pramsey** [comment]
I see @robe2 beat me here. I just ran into this doing some testing work. Same symptoms.

**Comment by jimmyrocks** [comment]
I just compiled it with https://github.com/OSGeo/gdal/commit/963618e77de4eee5e7321f5f5ca7abc2b7287fa2 and it works! Thanks for the quick response @rouault!

**Comment by danny-wang** [comment]
I meet the same error on postgres13.  my gdal version is GDAL 2.4.2, released 2019/06/28
