### ISSUE TITLE
OGRSpatialReference set UTM fails in 3.0.0 and 3.0.1

### ISSUE THREAD

**Issue by srvoin** [OSGeo/gdal#1701]
## Steps to reproduce the problem.

```
OGRSpatialReference oSRS;
oSRS.SetWellKnownGeogCS( "WGS84" );
oSRS.SetUTM(41, TRUE);

int zone = 0;
zone = oSRS.GetUTMZone();
```

At this point zone gets a value 41 which is correct, however when I export CRS definition to WKT (or any other format):

```
char* wkt = NULL;
oSRS.exportToWkt(&wkt);
```

Produces following string:

> PROJCS["unnamed",GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563]],PRIMEM["Greenwich",0],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]]],PROJECTION["Transverse_Mercator"],PARAMETER["latitude_of_origin",0],PARAMETER["central_meridian",21],PARAMETER["scale_factor",0.9996],PARAMETER["false_easting",500000],PARAMETER["false_northing",0],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AXIS["Easting",EAST],AXIS["Northing",NORTH]]

instead of:

> PROJCS["WGS 84 / UTM zone 34N",GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4326"]],PROJECTION["Transverse_Mercator"],PARAMETER["latitude_of_origin",0],PARAMETER["central_meridian",21],PARAMETER["scale_factor",0.9996],PARAMETER["false_easting",500000],PARAMETER["false_northing",0],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AXIS["Easting",EAST],AXIS["Northing",NORTH],AUTHORITY["EPSG","32634"]]

With GDAL 2.x.x and PROJ 5.x/4.x it works properly.

## Operating system

Ubuntu 18.04 64 bit

## GDAL version and provenance

GDAL 3.0.1/3.0.0
Proj 6.1.1/6.1.0

PROJ_LIB and GDAL_DATA are set correctly

**Comment by rouault** [comment]
What is the issue exactly ? That the projection name is "unnamed" ?
(the WKT string you mention are not consistent with UTM 41, and even with GDAL 2.4, the name is not the one you mention, it is "UTM Zone 41, Northern Hemisphere" and the EPSG code is not set)

**Comment by srvoin** [comment]
sorry for confusion, indeed, provided WKT generated not by gdal, but this is what is really generated by GDAL 2.4:

> PROJCS["UTM Zone 34, Northern Hemisphere",GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4326"]],PROJECTION["Transverse_Mercator"],PARAMETER["latitude_of_origin",0],PARAMETER["central_meridian",21],PARAMETER["scale_factor",0.9996],PARAMETER["false_easting",500000],PARAMETER["false_northing",0],UNIT["Meter",1],AUTHORITY["EPSG","32634"]]

and this definition is used later for gdalwarp. With GDAL 2.4 this pipeline works with no issues. But after update to version 3 this "unnamed" projection name causing wrong function of gdalwarp. Am I doing something wrong?

**Comment by rouault** [comment]
The projection name is completely ignored by gdalwarp or any underlying reprojection code. The issue must be something else.

**Comment by rouault** [comment]
If it still persists, can you provide a full reproducer of your issue ?

**Comment by srvoin** [comment]
I found a problem in my code. I was passing wrong transformer options to gdalwarp. E.g. non-standard case: projecting an image in UTM projection to EPSG:4326. My software tried to set "-rpc" and further rpc -related options, although there are no RPC as the iput image already in UTM. GDAL 2.x ignored this. Now it is corrected in my side, and besides "unnamed" projection name in WKT (which has no impact) there are no issues. I would close is for now. Thanks
