### ISSUE TITLE
Cannot get JPEG2000 support working on Amazon linux container

### ISSUE THREAD

**Issue by brentonmallen1** [OSGeo/gdal#1708]
## Expected behavior and actual behavior.

I expect JPEG2000 to be a supported format.  I've tried multiple permutations of configure options but couldn't seem to get jpeg2000 support to work.  I also tried simply using `/configure` which didn't seem to have an affect.  I think I'm missing a dependency or something.

## Steps to reproduce the problem.

After building the container with 
```docker build -t gdal_lambda:latest --no-cache .```

Enter a bash shell using:

```docker run -v output:/blah -it gdal_lambda:latest /bin/bash```

Execute the following configuration:
```RUN ./configure \
   --with-geos \
   --with-geotiff=internal \
   --with-hide-internal-symbols \
   --with-libtiff=internal \
   --with-libz=internal \
   --with-threads \
   --without-bsb \
   --without-cfitsio \
   --without-cryptopp \
   --with-curl \
   --without-ecw \
   --without-expat \
   --without-fme \
   --without-freexl \
   --without-gif \
   --without-gnm \
   --without-grass \
   --without-grib \
   --without-hdf4 \
   --without-hdf5 \
   --without-idb \
   --without-ingres \
   --with-jasper \
   --without-jp2mrsid \
   --with-jpeg \
   --without-kakadu \
   --without-libgrass \
   --without-libkml \
   --without-libtool \
   --without-mrf \
   --without-mrsid \
   --without-mysql \
   --without-netcdf \
   --without-odbc \
   --without-ogdi \
   --with-openjpeg \
   --without-pcidsk \
   --without-pcraster \
   --without-pcre \
   --without-perl \
   --without-pg \
   --without-png \
   --without-python \
   --without-qhull \
   --without-sde \
   --without-sqlite3 \
   --without-webp \
   --without-xerces \
   --without-xml2 && \
make -j4 && \
make && \
make install
``` 
(or any other jpeg2000 option such as `--with-ecw`)

When running the following commands:
```
export LD_LIBRARY_PATH=/blah/gdal-2.4.1
```
followed by
`gdalinfo --formats | sort`
and see that JPEG2000 is not among the supported formats.

## Operating system

I'm using the following Dockerfile to create a container in which the above commands are run:

```
FROM amazonlinux:latest

ENV GDAL_VER 2.4.1
ENV PROJ_VER 6.0.0

RUN yum -y update && \
yum -y install yum-utils
RUN yum-config-manager --enable epel
RUN yum -y install make \
automake \
gcc \
gcc-c++ \
libcurl-devel \
proj-devel \
geos-devel \
tar.x86_64 \
gzip \
proj \
python-devel \
iputils

RUN mkdir /blah
RUN mkdir /blah/gdal-${GDAL_VER}
RUN mkdir /blah/proj-${PROJ_VER}
WORKDIR /blah

RUN curl -L -O http://download.osgeo.org/gdal/${GDAL_VER}/gdal-${GDAL_VER}.tar.gz && \
tar -zxf gdal-${GDAL_VER}.tar.gz

WORKDIR /blah/gdal-${GDAL_VER}
```

## GDAL version and provenance

`2.4.1`

**Comment by rouault** [comment]
You need to install the libopenjp2 depenency (or whatever it is called in amazonlinux), or compile it by yourself. See https://github.com/OSGeo/gdal/blob/master/gdal/docker/alpine-normal/Dockerfile#L173 as a ptential exemple

**Comment by vincentsarago** [comment]
@brentonmallen1 did you try with OpenJPEG ? feel free to check https://github.com/RemotePixel/amazonlinux-gdal/blob/gdal2.4.2/Dockerfile if it can help you

**Comment by brentonmallen1** [comment]
@vincentsarago That was extremely helpful!  Thanks a lot
