### ISSUE TITLE
WFS3 does not keep query string parameters

### ISSUE THREAD

**Issue by elpaso** [OSGeo/gdal#1710]
#785  Expected behavior and actual behavior.

When using a QGIS Server WFS3 server (https://github.com/qgis/QGIS/pull/10016) with MAP parameter, the library appends `/collections` to the parameter instead of appending it to the path.

- Base URL: `http://localhost:8001/wfs3?MAP=/projects/projects/helloworld.qgs`
- GDAL actual call: `http://localhost:8001/wfs3?MAP=/projects/helloworld.qgs/collections`
- GDAL expected call: `http://localhost:8001/wfs3/collections?MAP=/projects/helloworld.qgs`

## GDAL version and provenance

2.4.0

**Comment by rouault** [comment]
Backported in 3.0 and 2.4 branches
