### ISSUE TITLE
WFS3 does not accept content type `application/vnd.geo+json` 

### ISSUE THREAD

**Issue by elpaso** [OSGeo/gdal#1711]
When the WFS3 server responds with a content-type `application/vnd.geo+json` it is not recognized by GDAL as a valid WFS3 layer.

When using `application/geo+json` there are no problems and the layer opens correctly.

## Expected behavior and actual behavior.

Expected: layer opens with no errors.

Actual behavior: `ERROR 1: Unexpected Content-Type: application/vnd.geo+json`

## GDAL version and provenance

2.4.0

**Comment by rouault** [comment]
https://rawcdn.githack.com/opengeospatial/WFS_FES/3.0.0-draft.1/docs/17-069.html

Requirement 35
```
/req/geojson/definition

200-responses of the server SHALL support the following media types:

    application/geo+json for feature collections and features, and

    application/json for all other resources.
```

**Comment by elpaso** [comment]
Agreed, I have already changed the implementation in the server, I just wanted to be sure the vnd variant is really obsolete because if it is not, GDAL might want to be tolerant and accept both.

**Comment by rouault** [comment]
>  GDAL might want to be tolerant and accept both.

I don't really care about one way or another regarding this. You're welcome to provide pull requests :-)
