### ISSUE TITLE
I am getting below error while executing make in gdal folder. Please help if i am doing something wrong. I am using Proj6 and ./configure got executed without any errors.

### ISSUE THREAD

**Issue by aswiniy** [OSGeo/gdal#1714]
I am getting below error while executing make in gdal folder. Please help if i am doing something wrong. I am using Proj6 and ./configure got executed without any errors.

/Library/Developer/CommandLineTools/usr/bin/make -C postgisraster install-obj
/bin/sh /Users/aswini-1039/Personal/work/repository/git/GDAL/gdal/libtool --mode=compile --silent --tag=CXX g++ -std=c++11 -I/Users/aswini-1039/Personal/work/repository/git/GDAL/gdal/port -I/Users/aswini-1039/Personal/work/repository/git/GDAL/gdal/gcore -I/Users/aswini-1039/Personal/work/repository/git/GDAL/gdal/alg -I/Users/aswini-1039/Personal/work/repository/git/GDAL/gdal/ogr -I/Users/aswini-1039/Personal/work/repository/git/GDAL/gdal/ogr/ogrsf_frmts -I/Users/aswini-1039/Personal/work/repository/git/GDAL/gdal/gnm -I/Users/aswini-1039/Personal/work/repository/git/GDAL/gdal/apps -Weffc++ -Wold-style-cast -DHAVE_AVX_AT_COMPILE_TIME -DHAVE_SSSE3_AT_COMPILE_TIME -DHAVE_SSE_AT_COMPILE_TIME -g -O2  -Wall -Wextra -Winit-self -Wunused-parameter -Wformat -Werror=format-security -Wno-format-nonliteral -Wshorten-64-to-32 -Wshadow -Werror=vla -Wdate-time -Wnull-dereference -Wextra-semi -Wcomma -Wfloat-conversion -Wdocumentation -Wno-documentation-deprecated-sync -Wunused-private-field -Wmissing-prototypes -Wmissing-declarations -Wnon-virtual-dtor -Woverloaded-virtual -fno-operator-names -Wimplicit-fallthrough  -I ../mem -I ../vrt  -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.Internal.sdk/usr/include   -DGNM_ENABLED -I/Users/aswini-1039/Personal/work/repository/git/GDAL/gdal/port -I/usr/local/Cellar/openjpeg/2.3.1/include/openjpeg-2.3  -I/usr/local/Cellar/netcdf/4.6.3_1/include  -DGDAL_COMPILATION -DHAVE_XERCES -I/usr/local/include -I/usr/local/include/xercesc -I/Users/aswini-1039/Personal/work/repository/git/GDAL/gdal/port -I/usr/local/Cellar/openjpeg/2.3.1/include/openjpeg-2.3  -I/usr/local/Cellar/netcdf/4.6.3_1/include  -DGDAL_COMPILATION -c -o ../o/postgisrasterdriver.lo postgisrasterdriver.cpp
In file included from postgisrasterdriver.cpp:31:
./postgisraster.h:41:10: fatal error: 'libpq-fe.h' file not found
#include "libpq-fe.h"
         ^~~~~~~~~~~~
1 error generated.
make[2]: *** [../o/postgisrasterdriver.lo] Error 1
make[1]: *** [postgisraster-install-obj] Error 2
make: *** [frmts-target] Error 2

Thanks.

_Originally posted by @aswiniy in https://github.com/OSGeo/gdal/issues/1713#issuecomment-510048378_

**Comment by aswiniy** [comment]
Last lines when i execute ./configure are

  SFCGAL support:            no
  QHull support:             internal
  Poppler support:           no
  Podofo support:            no
  PDFium support:            no
  OpenCL support:            no
  Armadillo support:         no
  FreeXL support:            yes
  SOSI support:              no
  MongoDB support:           no
  MongoCXX v3 support:       no
  HDFS support:              no
  TileDB support:            no
  userfaultfd support:       no
  misc. gdal formats:        aaigrid adrg aigrid airsar arg blx bmp bsb cals ceos ceos2 coasp cosar ctg dimap dted e00grid elas envisat ers fit gff gsg gxf hf2 idrisi ignfheightasciigrid ilwis ingr iris iso8211 jaxapalsar jdem kmlsuperoverlay l1b leveller map mrf msgn ngsgeoid nitf northwood pds prf r raw rmf rs2 safe saga sdts sentinel2 sgi sigdem srtmhgt terragen til tsx usgsdem xpm xyz zmap rik ozi grib eeda plmosaic rda wcs wms wmts daas rasterlite mbtiles pdf
  disabled gdal formats:    
  misc. ogr formats:         aeronavfaa arcgen avc bna cad csv dgn dxf edigeo geoconcept georss gml gmt gpsbabel gpx gtm htf jml mvt ntf openair openfilegdb pgdump rec s57 segukooa segy selafin shape sua svg sxf tiger vdv wasp xplane idrisi pds sdts nas ili gmlas ods xlsx odbc pgeo mssqlspatial geomedia walk amigocloud carto cloudant couchdb csw elastic gft ngw plscenes wfs gpkg vfk osm
  disabled ogr formats:     

  Mac OS X Framework :       no

  SWIG Bindings:             no

  PROJ >= 6:                 yes
  enable GNM building:       yes
  enable pthread support:    yes
  enable POSIX iconv support:yes
  hide internal symbols:     no

**Comment by rouault** [comment]
you should install postgresql development headers, or disable postgresql support with --without-pg

**Comment by aswiniy** [comment]
Below error occured when i run make inside swig/java

../include/ogr.i:1173: Warning 516: Overloaded method OGRLayerShadow::Update(OGRLayerShadow *,OGRLayerShadow *,char **,GDALProgressFunc,void *) ignored,
../include/ogr.i:1173: Warning 516: using OGRLayerShadow::Update(OGRLayerShadow *,OGRLayerShadow *,char **,GDALProgressFunc) instead.
../include/ogr.i:1184: Warning 516: Overloaded method OGRLayerShadow::Clip(OGRLayerShadow *,OGRLayerShadow *,char **,GDALProgressFunc) ignored,
../include/ogr.i:1184: Warning 516: using OGRLayerShadow::Clip(OGRLayerShadow *,OGRLayerShadow *,char **,GDALProgressFunc,void *) instead.
../include/ogr.i:1184: Warning 516: Overloaded method OGRLayerShadow::Clip(OGRLayerShadow *,OGRLayerShadow *,char **,GDALProgressFunc,void *) ignored,
../include/ogr.i:1184: Warning 516: using OGRLayerShadow::Clip(OGRLayerShadow *,OGRLayerShadow *,char **,GDALProgressFunc) instead.
../include/ogr.i:1195: Warning 516: Overloaded method OGRLayerShadow::Erase(OGRLayerShadow *,OGRLayerShadow *,char **,GDALProgressFunc) ignored,
../include/ogr.i:1195: Warning 516: using OGRLayerShadow::Erase(OGRLayerShadow *,OGRLayerShadow *,char **,GDALProgressFunc,void *) instead.
../include/ogr.i:1195: Warning 516: Overloaded method OGRLayerShadow::Erase(OGRLayerShadow *,OGRLayerShadow *,char **,GDALProgressFunc,void *) ignored,
../include/ogr.i:1195: Warning 516: using OGRLayerShadow::Erase(OGRLayerShadow *,OGRLayerShadow *,char **,GDALProgressFunc) instead.
swig -Wall -I../include -I../include/java -I../include/java/docs -outdir "org/gdal/osr" -package "org.gdal.osr"  -I/Users/aswini-1039/Personal/work/repository/git/oscgo_2/GDAL/gdal -c++ -java -o osr_wrap.cpp ../include/osr.i
../include/osr.i:1159: Warning 516: Overloaded method OSRCoordinateTransformationShadow::TransformPoint(double [4]) ignored,
../include/osr.i:1146: Warning 516: using OSRCoordinateTransformationShadow::TransformPoint(double [3]) instead.
swig -Wall -I../include -I../include/java -I../include/java/docs -outdir "org/gdal/gnm" -package "org.gdal.gnm"  -I/Users/aswini-1039/Personal/work/repository/git/oscgo_2/GDAL/gdal -c++ -java -o gnm_wrap.cpp ../include/gnm.i
/bin/sh /Users/aswini-1039/Personal/work/repository/git/oscgo_2/GDAL/gdal/libtool --mode=compile --silent --tag=CC gcc -fno-strict-aliasing -I/Users/aswini-1039/Personal/work/repository/git/oscgo_2/GDAL/gdal/port -I/Users/aswini-1039/Personal/work/repository/git/oscgo_2/GDAL/gdal/gcore -I/Users/aswini-1039/Personal/work/repository/git/oscgo_2/GDAL/gdal/alg -I/Users/aswini-1039/Personal/work/repository/git/oscgo_2/GDAL/gdal/ogr -I/Users/aswini-1039/Personal/work/repository/git/oscgo_2/GDAL/gdal/ogr/ogrsf_frmts -I/Users/aswini-1039/Personal/work/repository/git/oscgo_2/GDAL/gdal/gnm -I/Users/aswini-1039/Personal/work/repository/git/oscgo_2/GDAL/gdal/apps -DHAVE_AVX_AT_COMPILE_TIME -DHAVE_SSSE3_AT_COMPILE_TIME -DHAVE_SSE_AT_COMPILE_TIME -g -O2  -Wall -Wdeclaration-after-statement -Wextra -Winit-self -Wunused-parameter -Wmissing-prototypes -Wmissing-declarations -Wformat -Werror=format-security -Wno-format-nonliteral -Wshorten-64-to-32 -Wshadow -Werror=vla -Wdeclaration-after-statement -Wdate-time -Wnull-dereference -Wcomma -Wfloat-conversion -Wdocumentation -Wno-documentation-deprecated-sync  -DSWIG_NOARRAYS   -DGNM_ENABLED -I/Users/aswini-1039/Personal/work/repository/git/oscgo_2/GDAL/gdal/port -I/usr/local/Cellar/openjpeg/2.3.1/include/openjpeg-2.3  -I/usr/local/Cellar/netcdf/4.6.3_1/include  -DGDAL_COMPILATION -DHAVE_XERCES -I/usr/local/include -I/usr/local/include/xercesc -I/Users/aswini-1039/Personal/work/repository/git/oscgo_2/GDAL/gdal/port -I/usr/local/Cellar/openjpeg/2.3.1/include/openjpeg-2.3  -I/usr/local/Cellar/netcdf/4.6.3_1/include  -DGDAL_COMPILATION -I/include -I/include/linux -c gdalconst_wrap.c
gdalconst_wrap.c:154:10: fatal error: 'jni.h' file not found
#include <jni.h>
         ^~~~~~~
1 error generated.
