### ISSUE TITLE
sphinx: driver overview pages have less information

### ISSUE THREAD

**Issue by jef-n** [OSGeo/gdal#1715]
I got feedback about the new sphinx documentation from someone:  The original driver overview pages ([vector](http://web.archive.org/web/20190126064924/https://www.gdal.org/ogr_formats.html) / [raster](http://web.archive.org/web/20190126064924/https://gdal.org/formats_list.html)) were a bit more informative - they also provided an overview over capabilities and restrictions and some also about file extensions.

**Comment by rouault** [comment]
Most of this information has been moved in each driver page

**Comment by mloskot** [comment]
Use search or browse to driver-specific page

**Comment by rouault** [comment]
This is now fixed
