### ISSUE TITLE
Can not open public Google Storage Bucket using /vsigs/ 

### ISSUE THREAD

**Issue by adriantre** [OSGeo/gdal#1718]
Trying to read Sentinel-2 Public GS Bucket.

```
gs_dir = '/vsigs/gs://gcp-public-data-sentinel-2/tiles/32/V/LQ/S2B_MSIL1C_20181108T111249_N0207_R137_T32VLQ_20181108T113514.SAFE/MTD_MSIL1C.xml'
gdal.UseExceptions()
dataset = gdal.Open(gs_dir, gdal.GA_ReadOnly)
```

Using the python gdal bindings yield:
> RuntimeError: `/vsigs/gs://gcp-public-data-sentinel-2/.../MTD_MSIL1C.xml' does not exist in the file system, and is not recognized as a supported dataset name.

gdalinfo yields:
>ERROR 11: HTTP response code: 0
gdalinfo failed - unable to open '/vsigs/gs://gcp-public-data-sentinel-2/.../MTD_MSIL1C.xml'

The same error occurs when trying to open a .jp2 directly, from within the bucket.

This works as expected on local files.

I have provided the environment variable `GOOGLE_APPLICATION_CREDENTIALS`.
Also tried using env variables `GS_SECRET_ACCESS_KEY` and `GS_ACCESS_KEY_ID`.
Still no luck.

As mentioned in this [gis.stackexchange post](https://gis.stackexchange.com/questions/291791/read-files-with-python-gdal-using-vsigs/292372#292372) I can get Rasterio to read the .jp2 images from the bucket (although it cannot interpret the metadata xml file).

This error is probably related to the comment on [gdal Virtual File Systems page](https://gdal.org/user/virtual_file_systems.html?highlight=vsigs#vsigs):
>/vsigs/ is a file system handler that allows on-the-fly random reading of (**primarily non-public**) files available in Google Cloud Storage buckets

Why is that though? I would love to use GDAL to do this.

This behaviour can be reproduced using the Docker image [osgeo/gdal:ubuntu-full-latest](https://github.com/OSGeo/gdal/tree/master/gdal/docker)

Resources:
[GDAL Sentinel-2 driver](https://gdal.org/drivers/raster/sentinel2.html)
[/vsigs/](https://gdal.org/user/virtual_file_systems.html?highlight=vsigs#vsigs)
[Sentinel-2 Public GS Bucket](https://cloud.google.com/storage/docs/public-datasets/sentinel-2)

**Comment by rouault** [comment]
Just use standard /vsicurl/ if no authentication is needed
```
gdalinfo /vsicurl/https://storage.googleapis.com/gcp-public-data-sentinel-2/tiles/32/V/LQ/S2B_MSIL1C_20181108T111249_N0207_R137_T32VLQ_20181108T113514.SAFE/MTD_MSIL1C.xml
```

**Comment by rouault** [comment]
Actually /vsigs/ also works. Uou just need to remove the gs:// prefix
```gdalinfo /vsigs/gcp-public-data-sentinel-2/tiles/32/V/LQ/S2B_MSIL1C_20181108T111249_N0207_R137_T32VLQ_20181108T113514.SAFE/MTD_MSIL1C.xml
```

**Comment by adriantre** [comment]
Oh man, your right. I was sure had tried that but looks like I didn't.

Thanks! Closing as resolved.

**Comment by thomascoquet** [comment]
Hi,

Tested in GDAL 2.4.2 & 3.0.4

Public dataset access does not seem to work for me:

```
gdalinfo /vsigs/gcp-public-data-sentinel-2/tiles/32/V/LQ/S2B_MSIL1C_20181108T111249_N0207_R137_T32VLQ_20181108T113514.SAFE/MTD_MSIL1C.xml
￼￼ 1
```

yields:

```
ERROR 15: GS_SECRET_ACCESS_KEY+GS_ACCESS_KEY_ID, GS_OAUTH2_REFRESH_TOKEN or GOOGLE_APPLICATION_CREDENTIALS or GS_OAUTH2_PRIVATE_KEY+GS_OAUTH2_CLIENT_EMAIL configuration options and /home/thomascoquet/.boto not defined
gdalinfo failed - unable to open '/vsigs/gcp-public-data-sentinel-2/tiles/32/V/LQ/S2B_MSIL1C_20181108T111249_N0207_R137_T32VLQ_20181108T113514.SAFE/MTD_MSIL1C.xml'.
```

Reading the issue, I was under the impression it should?

Thanks

**Comment by rouault** [comment]
> Public dataset access does not seem to work for me:
> 
> ```
> 
> ```

ah, I realized that worked for me because I have credentials in ~/.boto.
You have to use "gdalinfo /vsicurl/https://storage.googleapis.com/gcp-public-data-sentinel-2/tiles/32/V/LQ/S2B_MSIL1C_20181108T111249_N0207_R137_T32VLQ_20181108T113514.SAFE/MTD_MSIL1C.xml" then to work without credentials. From a quick try, GCS specific API like directory listing don't work with un-autheticated calls

eg.

$ curl "https://storage.googleapis.com/gcp-public-data-sentinel-2/?delimiter=%2F&prefix=tiles%2F32%2FV%2FLQ%2FS2B_MSIL1C_20181108T111249_N0207_R137_T32VLQ_20181108T113514.SAFE%2FGRANULE%2FL1C_T32VLQ_A008743_20181108T111249%2F"

outputs:

<?xml version='1.0' encoding='UTF-8'?><Error><Code>AccessDenied</Code><Message>Access denied.</Message><Details>Anonymous caller does not have storage.objects.list access to the Google Cloud Storage bucket.</Details></Error>

**Comment by thomascoquet** [comment]
Ok, thanks for the confirmation! That's what I ended up doing manually. 
Would be a nice-to-have feature if GDAL could try unauthenticated request if no GCP credentials are found (or an env var similar to AWS_NO_SIGN_REQUEST to get iso-behavior). 

True for bucket listings, but as Sentinel and Landsat URI can be guessed from product ids, I don't need to list blobs for my use case.

Thanks again for your work Even!
