### ISSUE TITLE
forked repo - Appveyor build fails with deprecated SWIG typemaps

### ISSUE THREAD

**Issue by zacharyburnettNOAA** [OSGeo/gdal#1725]
## Expected behavior and actual behavior.

When building [GlenRice-NOAA/gdal](https://github.com/GlenRice-NOAA/gdal) on Appveyor (using the root `appveyor.yml`), both builds fail with the following error:

```
Error: A deprecated csdestruct typemap was found for {type}, please remove it and replace all csdestruct, csdestruct_derived and csfinalize typemaps by the csdispose, csdispose_derived, csdisposing and csdisposing_derived typemaps.
```

for the following types:

```
RasterIOExtraArg
XMLNode
MajorObject
Driver
ColorEntry
GCP
AsyncReader
Dataset
Band
ColorTable
RasterAttributeTable
Transformer
GDALInfoOptions
GDALTranslateOptions
GDALWarpAppOptions
GDALVectorTranslateOptions
GDALDEMProcessingOptions
GDALNearblackOptions
GDALGridOptions
GDALRasterizeOptions
GDALBuildVRTOptions
```

is additional configuration required to build?

## Steps to reproduce the problem.

1. fork repository
2. connect Appveyor
3. start build

## Operating system

- [Visual Studio 2017 x86](https://ci.appveyor.com/project/GlenRice-NOAA/gdal/build/job/jjdskl845v2olcut)
- [Visual Studio 2015 x64](https://ci.appveyor.com/project/GlenRice-NOAA/gdal/build/job/ga2wktcvq4tlo9qa)

## GDAL version and provenance

`master`

**Comment by rouault** [comment]
> is additional configuration required to build?

I don't think so. Doesn't ring a bell. Works well with other forks

**Comment by rouault** [comment]
ok, comparing build logs, I found the issue. In your fork which is new SWIG 4.0 is installed by Chocalatey, whereas in existing forks like the OSGeo/gdal one or my own fork, it uses an older cached version (3.0.12). https://github.com/OSGeo/gdal/pull/1727 is an attempt to workaround this

**Comment by rouault** [comment]
Fixed by https://github.com/OSGeo/gdal/commit/8676b95ae61141c512fba9fbce875d85bd005578
