### ISSUE TITLE
SAR complex data bands show incorrectly in QGIS for GDAL/NITF/HFA driver

### ISSUE THREAD

**Issue by tjhokietiger** [OSGeo/gdal#1729]
Using QGIS 3.6.3 compiled against GDAL2.4.1 for loading SICD-NITF file.  

## Expected behavior and actual behavior.
Loading a Sensor Independent Complex Data (SICD) formatted NITF file, apparently uses NITF and HFA GDAL drivers.  QGIS/GDAL reads the complex image OK (shows as a VRT), but the band identifiers (in e.g., QGIS/Symbology) defaults to Band 1: Magnitude-1-HH and Band 2: Phase-2-HH and the data ranges / histograms are interpreted as Magnitude, only positive and Phase +/-.  However, these SICD files are in I (in-phase, real) and Q (quadrature, imaginary) format, not Mag & Phase.  NITF metadata TRE labels are correct (e.g., ISUBCAT001: I, ISUBCAT002: Q).  We can't figure out specifically where this is coming from, but with only NITF driver on, it reads the file, but doesn't recognize the data as SAR complex and with the HFA driver added, it recognizes the complex data, but with the incorrect info (not sure why an erdas driver comes into play, but it appears to be a dependency).  SICD files CAN be Mag/Phase, but most/many are I & Q.  We expect that GDAL should assign the band names properly and acknowledge the full data ranges (either INT16 or FLOAT32 +/-).  

NOTE: Ideally, a SICD in I&Q would have the magnitude calculated on-the-fly (RMS of I & Q) and displayed (Some ELTs do this), but that is probably too much to ask...  

## Workaround
One can manually set the min and max range as needed (e.g., set min to -1000 instead of 1).  No workaround for histogram display.  

## Steps to reproduce the problem.
Obtain an I/Q SICD NITF file (unfortunately, I can't attach an example file).  Open in QGIS.  Go to Layer Styling > Symbology and look at band identifiers and Min / Max ranges.  

## Operating system
Mac OSX 64-bit

## GDAL version and provenance
2.4.1 installed with QGIS 3.6.3

**Comment by rouault** [comment]
Could you paste the output of "gdalinfo -mm the.file", and list all the files involved so we can understand why NITF and HFA drivers are involved ?

**Comment by rouault** [comment]
closing due to lack of feedback
