### ISSUE TITLE
is this wrong typo?

### ISSUE THREAD

**Issue by billtian** [OSGeo/gdal#1730]
https://github.com/OSGeo/gdal/blob/9f1bfb89aacd6b991ac5ab91bdfe011bc5794e9a/gdal/gcore/gdaldefaultoverviews.cpp#L661

https://github.com/OSGeo/gdal/blob/9f1bfb89aacd6b991ac5ab91bdfe011bc5794e9a/gdal/gcore/gdaldefaultoverviews.cpp#L702

Are these line some thing wrong ? They done the same calc two times. I'm puzzled

**Comment by rouault** [comment]
Yes, this was a typo. Thanks for raising that. How did you discover this ?

**Comment by billtian** [comment]
@rouault I'm using gdaladdo to build overviews, and want to known how to do this.

btw, i'm a GISer.
