### ISSUE TITLE
Cannot clip geotiff image with polar stereographic projection 

### ISSUE THREAD

**Issue by jiaozhh** [OSGeo/gdal#1733]
## Expected behavior and actual behavior.

gdal_translate can clip the geotiff image.

## Steps to reproduce the problem.

> $ gdal_translate -projwin 113 -65 133 -85 -projwin_srs EPSG:4326 -of GTiff  E:\mxd02_test.tif E:\mxd02.tif

The following is the output: 

> Input file size is 3094, 2944
> ERROR 1: Error: Computed -srcwin 3064 2541 -2185 -721 has negative width and/or height.

[download mxd02_test.tif file](https://send.firefox.com/download/0768dfd99d048407/#X-NXSSNi-YwDgVl1-Z8CHA)

## Operating system

Windows 10 x64

## GDAL version and provenance

GDAL with version 3.0.1 is compiled by the VS 2019 in Windows 10 x64.

**Comment by rouault** [comment]
With a polar stereographic projection this is expected. -projwin_srs only makes sense when the geometry of a rectangle in the native projection is still more or less a rectangle, with same "orientation", in the projwin_srs projection.
