### ISSUE TITLE
Python 3.7 gdal 3.0.1 path issue: proj.db not in default directory

### ISSUE THREAD

**Issue by Janewyx** [OSGeo/gdal#1735]
Using `gdal 3.0.1` in Python 3.7  downloaded for Windows 64 bit from the wheels file (GDAL-3.0.1-cp37-cp37m-win_amd64.whl) at https://www.lfd.uci.edu/~gohlke/pythonlibs/#gdal , I run the [create PDF Python script](https://raw.githubusercontent.com/OSGeo/gdal/master/gdal/swig/python/samples/gdal_create_pdf.py) to create geoPDF from `.xml` composition file. 

I am returned the error 
> ERROR 1: PROJ: proj_create_from_database: Cannot find proj.db

The default `PROJ_LIB` (from 'C:\OSGeo4W64\apps\Python37\lib\site-packages\osgeo\__init__.py') is ''C:\OSGeo4W64\share\proj'', however, there is no 'proj.db' file in that folder. I attempted setting both Windows Environmental Variable and the `PROJ_LIB` Environment from within Python by `os.environ['PROJ_LIB'] = "C:\OSGeo4W64\apps\Python37\lib\site-packages\osgeo\data\proj"` , where 'proj.db' actually is, neither caused the error message to disappear.

I keep another working installation of gdal on my computer for our project purpose, and I can run the script from Commandline no problem with the binary files installed from [gisinternals](http://www.gisinternals.com/query.html?content=filelist&file=release-1900-x64-gdal-3-0-0-mapserver-7-4-0.zip) and after setting Windows Environmental Variables as such:

```
GDAL_DATA: C:\Program Files\GDAL\gdal-data
GDAL_DRIVER_PATH: C:\Program Files\GDAL\gdalplugins
PROJ_LIB: C:\Program Files\GDAL\projlib
PATH: %PATH%; C:\Program Files\GDAL
```
But it is desired that we call gdal functions from the OSGEO installed version.

## Operating system

Windows 10 64 bit

## GDAL version and provenance

GDAL 3.0.1 from OSGEO4W64, Python 3.7

**Comment by rouault** [comment]
This seems to be an issue with the package you use. Not something that the upstream project here can do about.

**Comment by Janewyx** [comment]
That makes sense. Do I understand correctly that the official OSGEO platform only supports stable version of GDAL, up to version 2.4.1? Other than that, GDAL 3.0.0 + will be available from OSGEO-independent platforms?

**Comment by cgohlke** [comment]
Please follow the advise at https://www.lfd.uci.edu/~gohlke/pythonlibs/#gdal: "Do not use together with OSGeo4W or gdalwin32".

`"C:\OSGeo4W64\apps\Python37\lib\site-packages\osgeo\data\proj"` contains escape sequences. Try a raw string instead: `r"C:\OSGeo4W64\apps\Python37\lib\site-packages\osgeo\data\proj"`

**Comment by rouault** [comment]
OSGeo4W will be eventually upgraded to GDAL 3 / PROJ 6.1. This is mostly a matter of time.

**Comment by bvramesh25** [comment]
Whichever folder is configured as PROJ_LIB. GDAL is looking for proj.db inside "%PROJ_LIB%\proj" folder.
To resolve the issue create a proj folder inside and copy all the content.
