### ISSUE TITLE
OGR netCDF driver accepts COMPRESS and ZLEVEL options but does not compress output.

### ISSUE THREAD

**Issue by dbaston** [OSGeo/gdal#1738]
## Expected behavior and actual behavior.

Vector netCDF driver accepts `COMPRESS` and `ZLEVEL` options but does not compress output.

## Steps to reproduce the problem.

```
# Write test data
echo 'name,pop\nAnguilla,8777' > pop.csv

# Convert to netCDF
ogr2ogr pop.nc pop.csv \
  -sql 'SELECT name, cast(pop AS float) AS pop FROM pop' \
  -dsco FORMAT=NC4C \
  -dsco COMPRESS=DEFLATE \
  -dsco ZLEVEL=2
  -dsco GEOMETRY_ENCODING=WKT

# Check for compression using ncks
ncks pop.nc | grep compress

## name: type NC_CHAR, 2 dimensions, 4 attributes, compressed? no, chunked? yes, packed? no
## pop: type NC_DOUBLE, 1 dimension, 3 attributes, compressed? no, chunked? yes, packed? no
```

## Operating system

Ubuntu 16.04 64 bit

## GDAL version and provenance

GDAL 2.3.1, released 2018/06/22
installed from source

**Comment by rouault** [comment]
This is expected. Those are for rasters. The ones that apply to vectors are at https://gdal.org/drivers/vector/netcdf.html

**Comment by dbaston** [comment]
I'd expect an error to be thrown for an unsupported creation operation, no?

**Comment by rouault** [comment]
in an ideal world yes :-)

**Comment by dbaston** [comment]
OK. I just wanted to make sure I wasn't missing something. I can look into supporting compression on the vector side if you're OK with that.

**Comment by rouault** [comment]
if that makes sense. That said, the old WKT-based approach is probably now a bit deprecated by the new CF-1.8 simple geometry support that was added in master

**Comment by dbaston** [comment]
Yes, I see that the files have been touched recently. I'm actually not working with geometry at all; just writing tabular data.

**Comment by rouault** [comment]
for such drivers that support both raster and vector, one possibility also to flag raster-only options is to add a `scope="raster"` attribute in the XML of the creation options

**Comment by jratike80** [comment]
This ticket originates from a misunderstanding and mixing raster and vector options. If the work that is done with the vector compression continues some day it will be better to create a new ticket about that. I believe that I will close this ticket soon.

**Comment by dbaston** [comment]
The expected behavior is to accept the options and ignore them?

**Comment by jratike80** [comment]
Perhaps like this then

```
ogr2ogr -f netcdf -dsco foo=bar jump.nc jump_point.shp
Warning 6: driver netCDF does not support creation option foo
```

Even suggested "one possibility also to flag raster-only options is to add a scope="raster" attribute in the XML of the creation options"

Would you mind to have a look?

**Comment by dbaston** [comment]
I think the XML in question is here: https://github.com/OSGeo/gdal/blob/c31ea2ec27d5954b6bb6720487f095c042a869b6/gdal/frmts/netcdf/netcdfdataset.cpp#L9206

But it's not clear to me if the code to pick up the `scope="raster"` tag exists already. I will try to look into it soon but can't do it immediately.

**Comment by dbaston** [comment]
Looks like the answer is yes, as the GeoPackage driver is doing it. Maybe I can take care of it right now.

**Comment by jratike80** [comment]
When you get going I think there is something to improve with PDF as well. See

`gdalinfo --format pdf`

**Comment by jratike80** [comment]
In https://github.com/OSGeo/gdal/blob/master/gdal/ogr/ogrsf_frmts/gpkg/ogrgeopackagedriver.cpp

`<Option name='TILE_FORMAT' type='string-select' scope='raster' description='Format to use to create tiles' default='AUTO'>" \`
