### ISSUE TITLE
ogr_ngw tests failing

### ISSUE THREAD

**Issue by rouault** [OSGeo/gdal#1746]
@BishopGIS 
See  https://api.travis-ci.com/v3/job/221312395/log.txt and https://travis-ci.com/OSGeo/gdal/jobs/221312402  . I can reproduce locally the failure on test_ogr_ngw_10

**Comment by rouault** [comment]
I've disabled ogr_ngw.py and ngw.py for now (trying to fix other CI issues at the same time...)

**Comment by BishopGIS** [comment]
This was a server side error. Fixed now.
