### ISSUE TITLE
gdal_contour -p is very slow

### ISSUE THREAD

**Issue by brewin** [OSGeo/gdal#1750]
`gdal_contour -p` is very slow for large rasters compared to other tools such as [matplotlib.pyplot.contourf](https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.contourf.html). It seems to be hundreds or even thousands of times slower. So here are some possible ways to optimize it... 

Each level can be processed in parallel. It should use all cores.

The code to attach inner rings (holes) to outer rings (polygon perimeters) isn't optimal. This problem is mentioned in [the code](https://github.com/OSGeo/gdal/blob/master/gdal/alg/marching_squares/polygon_ring_appender.h#L139) and in [this closed issue](https://github.com/OSGeo/gdal/issues/1256). As mentioned in the FIXME, inner rings should be removed from the list as they are attached to outer rings.

The progress bar should indicate progress. Right now it doesn't.

**Comment by rouault** [comment]
Pull requests are accepted ;-)

**Comment by brewin** [comment]
Of course! Unfortunately, my C++ skills are lacking. I did write a fast implementation of Marching Squares in Kotlin though. The ring attachment bit is [here](https://github.com/brewin/KotlinMarchingSquares/blob/master/src/main/kotlin/MarchingSquares.kt#L83) if someone wants to translate it.

**Comment by owvarley** [comment]
I've been doing some work with gdal_contour -p the last couple of months rendering contour polygons for 1 degree by 1 degree SRTM tiles and its performance is noticeable slow. For those that are hitting this issue some of the suggestions [here](https://github.com/OSGeo/gdal/issues/1256) are worth using. Notably changing the contour spacing from every 50ft to 500ft for us reduced processing time from ~1 hour down to ~1 minute per tile. 

There are essentially two issues; firstly the gdal progress bar completes a long time before the actual polygon shapefile is generated and secondly the algorithm is inefficient as outlined by @brewin above.

**Comment by rouault** [comment]
Closing that one in favor of https://github.com/OSGeo/gdal/issues/2241which has a precise reproducer

**Comment by hlthi** [comment]
Fixed  #2908
