### ISSUE TITLE
VSI cache is used for local datasets opened via a VRT

### ISSUE THREAD

**Issue by craigds** [OSGeo/gdal#1752]
## Expected behavior and actual behavior.

We set `VSI_CACHE=TRUE` and `VSI_CACHE_SIZE=1000000000` in our environment by default, because we do a fair bit of vsicurl and vsis3 access, and we expected this should avoid some remote access seeks. And 1GB felt cheap enough.

We've just discovered this is the cause of an enormous memory blowout while transforming from VRT files containing thousands of TIFs. 

All TIFs mentioned in the VRT are local, and no VSI filesystems are in use, so this was surprising to us. It seems that the VSI cache is used for other things that aren't documented.

## Steps to reproduce the problem.

* Create 1000 tif files of reasonable size
* create a VRT referencing all of them
* enable the VSI cache with a large size limit
* gdal_translate the VRT to kmlsuperoverlay or something

## Operating system

Ubuntu 14.04 64 bit (I know! we're working on upgrading)

## GDAL version and provenance

GDAL 2.4.2. slightly custom build but nothing relevant to this. This was also happening on GDAL 2.3 and possibly before that. 

## Related:

This would have been the actual problem behind https://trac.osgeo.org/gdal/ticket/7177 , but we never got aroudn to investigating it properly until now.

## Suggested fix

For our use case a cache for non-remote datasources seems unnecessary. Maybe it is useful for others on slower disks, or from NFS or something?

Perhaps if this behaviour is desirable, it could be documented better. The [trac wiki docs](https://trac.osgeo.org/gdal/wiki/ConfigOptions#VSI_CACHE) suggest it is only used by VSI filesystems.

**Comment by jratike80** [comment]
Did I understand right that with with the same data and `VSI_CACHE=FALSE` memory consumption is reasonable?

**Comment by craigds** [comment]
Correct, it works fine if we disable the VSI cache

**Comment by rouault** [comment]
Almost every I/O in GDAL, apart from a few exotic drives, goes through a VSI virtual file system handler, including local I/O. So the behaviour you see is expected because VSI_CACHE is a per-file cache, not a global one. As a VRT keeps open by default up to 450 sources when used from gdal_translate (can be changed with GDAL_MAX_DATASET_POOL_SIZE), then you can have up to 450 * VSI_CACHE_SIZE bytes allocated

**Comment by craigds** [comment]
Thanks @rouault. I've modified the wiki page to reflect that (diff: https://trac.osgeo.org/gdal/wiki/ConfigOptions?action=diff&version=50 )
