### ISSUE TITLE
what's the difference between version 2.*.* and version 3.*.*?

### ISSUE THREAD

**Issue by DRjy** [OSGeo/gdal#1758]
OR what're the things changed in version 3.*.*, compoare to the version 2.*.*?

**Comment by jratike80** [comment]
Please don't use issue tracker for asking questions. Questions should go to the gdal-dev mailing list (https://lists.osgeo.org/mailman/listinfo/gdal-dev)
or other support forums. GitHub issues are for bug reports and suggestions
for new features.

The release news is good reading to start with https://trac.osgeo.org/gdal/wiki/Release/3.0.0-News.

**Comment by mloskot** [comment]
As @jratike80 pointed, GDAL is shipped with carefully crafted release notes (hard work!). Just read it. 

Alternatively, generate your own list of changes, for exaemple, add this alias to your `.gitconfig`

```
[alias]
	ghclm = "!f() { git log $1...$2  --pretty=format:\"* [view](http://github.com/$3/$4/commit/%H) - %s\"; }; f"
```

generate changelog files, for example:

```
git checkout release/3.0
git ghclm origin/release/2.0 > 2-3.md

git checkout master
git ghclm origin/release/2.0 > 2-master.md
git ghclm origin/release/3.0 > 3-master.md
```

then paste to gist.github.com and happy reading.
