### ISSUE TITLE
gdal_translate fails on large-resolution sparse tiled data

### ISSUE THREAD

**Issue by Vineg** [OSGeo/gdal#1761]
## Expected behavior and actual behavior.

expected: gdal_translate successfully consumes tiled tiff
actual:
command

> gdal_translate -tr 0.0002 0.0002 -co SPARSE_OK=YES -co TILED=TRUE file.tiff out/file.tiff

fails with error

> Input file size is 239873, 75071
> ERROR 1: TIFFNumberOfTiles:Integer overflow in TIFFNumberOfTiles
> ERROR 1: TIFFReadDirectory:Cannot handle zero number of tiles
> ERROR 1: TIFFNumberOfTiles:Integer overflow in TIFFNumberOfTiles
> ERROR 1: lowres/875_900.tiff:Failed to allocate memory for for "StripOffsets" array (0 elements of 8 bytes each)
> ERROR 1: lowres/875_900.tiff:Failed to allocate memory for for "StripByteCounts" array (0 elements of 8 bytes each)
> ERROR 1: GTiffCreateCopy():No space for tile arrays
> ERROR 1: TIFFNumberOfTiles:Integer overflow in TIFFNumberOfTiles
> ERROR 1: TIFFReadDirectory:Cannot handle zero number of tiles
> ERROR 1: TIFFNumberOfTiles:Integer overflow in TIFFNumberOfTiles
> ERROR 1: TIFFReadDirectory:Cannot handle zero number of tiles

## Steps to reproduce the problem.

Take spatial tiff of large space and run gdal_translate

## Operating system

Ubuntu 18.04 64 bit
Windows 10 64 bit

## GDAL version and provenance

2.4.0 from ubuntugis-unstable, 3.0.1 from conda-forge

**Comment by Vineg** [comment]
gdal_merge fails as well

**Comment by rouault** [comment]
Can you paste the output of `gdalinfo file.tiff` ?

**Comment by Vineg** [comment]
> Driver: GTiff/GeoTIFF
> Files: file.tiff
> Size is 239873, 75071
> Coordinate System is:
> {WKT}
> Origin = {Origin}
> Pixel Size = (0.100000000000000,0.100000000000000)
> Metadata:
>   AREA_OR_POINT=Area
> Image Structure Metadata:
>   INTERLEAVE=BAND
> Corner Coordinates:
> {Coordinates}
> Band 1 Block=256x256 Type=Float32, ColorInterp=Gray
>   NoData Value=0

**Comment by Vineg** [comment]
I'll double check coordinate system, it may be my issue.

**Comment by Vineg** [comment]
Indeed, file was in metric coordinate system, which seems to be causing this issue.

**Comment by rouault** [comment]
The error is expected. You're starting from a very large file and you increase it by a factor of 500 x 500. I've estimated that the size of the TIFF tile arrays to allocate should be 1 TB large with a default tile size of 256x256...
