### ISSUE TITLE
ogr2ogr conversion problem in Mac os

### ISSUE THREAD

**Issue by wuyyururaviteja** [OSGeo/gdal#1765]
Hello GDAL Team,

We would like to use ogr2ogr file format conversion in our product using java bindings. We have generated the necessary library files and gdal jar from the directions given and upon using them to convert from kml to csv in CentOS it had worked well but upon doing the same in Mac OS we are facing an issue. The file for which we are facing the issue is attached below and also the errors. 

Error Message shown in Mac OS: 
Unable to open datasource ` 13_Colonies_Template.kml' with the following drivers.
  . PCIDSK
  . PDS4
  . PDF
  . EEDA
  . ESRI Shapefile
  . MapInfo File
  . UK .NTF
  . OGR_SDTS
  . S57
  . DGN
  . OGR_VRT
  . REC
  . Memory
  . BNA
  . CSV
  . GML
  . GPX
  . KML
  . GeoJSON
  . GeoJSONSeq
  . ESRIJSON
  . TopoJSON
  . OGR_GMT
  . WAsP
  . OpenFileGDB
  . XPlane
  . DXF
  . CAD
  . Geoconcept
  . GeoRSS
  . GPSTrackMaker
  . PGDUMP
  . GPSBabel
  . SUA
  . OpenAir
  . OGR_PDS
  . WFS
  . WFS3
  . HTF
  . AeronavFAA
  . EDIGEO
  . GFT
  . SVG
  . CouchDB
  . Cloudant
  . Idrisi
  . ARCGEN
  . SEGUKOOA
  . SEGY
  . ElasticSearch
  . Carto
  . AmigoCloud
  . SXF
  . Selafin
  . JML
  . PLSCENES
  . CSW
  . VDV
  . MVT
  . TIGER
  . AVCBin
  . AVCE00
  . NGW
  . HTTP
 
the file can be found here : https://sites.google.com/mrpiercey.com/resources/geo/kml-downloads 
with the file name as 13 Colonies Template.kml 
 
Iam using the gdal version 3.0.1 in both Os Systems.  

Thanks in advance

**Comment by rouault** [comment]
Works for me. In the error message, I see a space just before the 13 in  ` 13_Colonies_Template.kml' . Are you sure you're passing the right filename ?

**Comment by wuyyururaviteja** [comment]
yeah I changed the file name for easier running .
Are there any cases possible for even the driver exists but unable to load the file. Beacause I have checked for various file formats it worked for .shp file in both systems but for .geojson and .kml and .kmz its not working in mac.

**Comment by wuyyururaviteja** [comment]
Correct me if Iam wrong in installation procedure 
getting the gdal from git repository with tag v3.0.1 
running ./configure in gdal folder and then running make in the same directory
changing java.opt in swig/java for java home and running make 
and upon completion the gdal.jar file and the 4 .dylib files generated are copied to a different folder along with ogr2ogr.java file. 
(In macos its checking for native library files in system libraries path but not in java library path so copied the library files in the system library path and upon running native library files are loaded. This case has not occured in centos machine its taking files from java library path upon specifying the path)

**Comment by rouault** [comment]
Does `ogrinfo "13 Colonies Template.kml"` work with your build ?

**Comment by wuyyururaviteja** [comment]
no it shows an error as follows 
java -cp :gdal.jar -Djava.library.path=libs/ ogrinfo 13_Colonies_Template.kml 
Had to open data source read-only.
FAILURE:
Unable to open datasource `13_Colonies_Template.kml' with the following drivers.
  -> PCIDSK
  -> PDS4
  -> PDF
  -> EEDA
  -> ESRI Shapefile
  -> MapInfo File
  -> UK .NTF
  -> OGR_SDTS
  -> S57
  -> DGN
  -> OGR_VRT
  -> REC
  -> Memory
  -> BNA
  -> CSV
  -> GML
  -> GPX
  -> KML
  -> GeoJSON
  -> GeoJSONSeq
  -> ESRIJSON
  -> TopoJSON
  -> OGR_GMT
  -> WAsP
  -> OpenFileGDB
  -> XPlane
  -> DXF
  -> CAD
  -> Geoconcept
  -> GeoRSS
  -> GPSTrackMaker
  -> PGDUMP
  -> GPSBabel
  -> SUA
  -> OpenAir
  -> OGR_PDS
  -> WFS
  -> WFS3
  -> HTF
  -> AeronavFAA
  -> EDIGEO
  -> GFT
  -> SVG
  -> CouchDB
  -> Cloudant
  -> Idrisi
  -> ARCGEN
  -> SEGUKOOA
  -> SEGY
  -> ElasticSearch
  -> Carto
  -> AmigoCloud
  -> SXF
  -> Selafin
  -> JML
  -> PLSCENES
  -> CSW
  -> VDV
  -> MVT
  -> TIGER
  -> AVCBin
  -> AVCE00
  -> NGW
  -> HTTP

I had crosschecked the same with a CentOS Machine then the result is as follows
java -cp :gdal.jar -Djava.library.path=libs/ ogrinfo 13_Colonies_Template.kml 
INFO: Open of `13_Colonies_Template.kml'
      using driver `KML' successful.
1: 13 Colonies Information (3D Point)
2: Proclamation Line of 1763 (3D Line String)
3: New England Colonies (3D Polygon)
4: Middle Colonies (3D Polygon)
5: Southern Colonies (3D Polygon)

I have also checked for permissions of file for user in mac -rwxrwxrwx

**Comment by rouault** [comment]
On the Mac, did you build GDAL with Expat or Xerces-C support ?

**Comment by wuyyururaviteja** [comment]
No I haven't done anything like that 
The process followed by me for building is as follows 
1. downloaded gdal v3.0 zip and extracted it
2. in gdal folder run ./configure and make
3. add JAVA_HOME in java.opt in swig/java
4. run make in swig/java 
for running i copied necessary .dylib files to a folder and using gdal.jar I ran the ogr2ogr.java file

I have installed Expat in my system but during ./configure iam getting the following 
Expat support:             no
checking for Expat XML Parser... no 
 
even though expat is accessible from terminal, gdal is not detecting it  

Is there any change in procedure i need to follow for building gdal?

**Comment by rouault** [comment]
> Is there any change in procedure i need to follow for building gdal?

yes, you need to install the expat development packages.

**Comment by wuyyururaviteja** [comment]
checking for Expat XML Parser headers in /usr/local/include... found
checking for Expat XML Parser... yes
checking if Expat XML Parser version is >= 1.95.0... yes

 Expat support:             yes 

I have installed the expat development packages as suggested and run building gdal again but the problem still persists 

java -cp :gdal.jar -Djava.library.path=libs/ ogr2ogr "-t_srs" "CRS:84" "-f" "CSV" "trail123.csv" "kmls/Changing_Earth1.kml" "-lco" "GEOMETRY=AS_WKT"
FAILURE:
Unable to open datasource ` kmls/Changing_Earth1.kml' with the following drivers.
  . PCIDSK
  . PDS4
  . PDF
  . EEDA
  . ESRI Shapefile
  . MapInfo File
  . UK .NTF
  . OGR_SDTS
  . S57
  . DGN
  . OGR_VRT
  . REC
  . Memory
  . BNA
  . CSV
  . GML
  . GPX
  . KML
  . GeoJSON
  . GeoJSONSeq
  . ESRIJSON
  . TopoJSON
  . OGR_GMT
  . WAsP
  . OpenFileGDB
  . XPlane
  . DXF
  . CAD
  . Geoconcept
  . GeoRSS
  . GPSTrackMaker
  . PGDUMP
  . GPSBabel
  . SUA
  . OpenAir
  . OGR_PDS
  . WFS
  . WFS3
  . HTF
  . AeronavFAA
  . EDIGEO
  . GFT
  . SVG
  . CouchDB
  . Cloudant
  . Idrisi
  . ARCGEN
  . SEGUKOOA
  . SEGY
  . ElasticSearch
  . Carto
  . AmigoCloud
  . SXF
  . Selafin
  . JML
  . PLSCENES
  . CSW
  . VDV
  . MVT
  . TIGER
  . AVCBin
  . AVCE00
  . NGW
  . HTTP 

any suggestions to make it work?

**Comment by rouault** [comment]
make sure you have 'make clean' before rebuilding

**Comment by wuyyururaviteja** [comment]
Thanks it worked.

I have read in gdal website that for xlsx conversion there is no geometry support but may use ogr vrt capabilities for that. 
can you please elaborate the procedure i need to follow so i can convert .kml files directly to .xlsx format which has geometry included. 
Note: i have already built gdal with expat support so upon trying to convert from .kml to .xlsx iam getting file which misses Geometry Column.

Thanks in advance.
