### ISSUE TITLE
Unsigned underflow in rmfdem.cpp

### ISSUE THREAD

**Issue by rouault** [OSGeo/gdal#1774]
@drons While trying to build GDAL with -fsanitize=unsigned-integer-overflow (many other changes needed to make it pass), which triggers an abort whenever a overflow/underflow occurs on unsigned operations (a number of them are legit, others might be bug), one was triggered in rmfdem.cpp on test_rmf_31d.
Can also be reproduced with
```
gdal_translate ../autotest/gdrivers/data/t100.mtw out.mtw -of RMF -co MTW=YES -co COMPRESS=RMF_DEM
```
The underflow occurs on line 713 or rmfdem.cpp
```
        GUInt32 nElementDeltaSize(nRecordElementSize -
                                  anDeltaTypeSize[eCurrType >> 5]);
```
with nRecordElementSize == 0 and anDeltaTypeSize[eCurrType >> 5] == 12.

Underflow on unsigned arithmetic is well defined behaviour in C (wrap around behaviour), but here it looks a bit suspicous. Could you investigate that a bit, and if possible avoid the underflow situation (at a last resort we can tag functions with CPL_NOSANITIZE_UNSIGNED_INT_OVERFLOW)

**Comment by drons** [comment]
Thanks! This is looks like a bug.
