### ISSUE TITLE
ogrinfo - dxf driver -  which alignment points to read as the ogrFeature point?

### ISSUE THREAD

**Issue by faridcher** [OSGeo/gdal#1779]
## Expected behavior and actual behavior.

I expected ogrinfo  to read the TEXT entities's second alignment points (i.e. group code 11 and 21) as the ogrFeature point coordinates when horizontal or vertical alignment group codes (group code 72 and 73 respectively) is non-zero as the "Autocad 2014 DXF reference (page 163)" entails. 

```
if group 72 and/or 73 values are nonzero then the first alignment point values
are ignored and AutoCAD calculates new values based on the second alignment
point and the length and height of the text string itself (after applying the
text style). If the 72 and 73 values are zero or missing, then the second
alignment point is meaningless.
```

However, it reads the first alignment point coords (i.e. group code 10 and 20) as the ogrFeature point coordinates. Unlike GDAL, QCAD Community reads and shows it just fine.

## Steps to reproduce the problem.
In this example A253G1 is the label of a TEXT entity.

```shell
> ogrinfo b.dxf 'entities' | grep -C 5 A253G1

OGRFeature(entities):173
  Layer (String) = 3
  SubClasses (String) = AcDbEntity:AcDbText:AcDbText
  Linetype (String) = ByLayer
  EntityHandle (String) = 1A7
  Text (String) = A253G1
  Style = LABEL(f:"",t:"A253G1",p:2,a:2.45,s:0.3g,dx:0.761512g,dy:0.182617g,c:#ffff00)
  POINT Z (92.3107623117303 70.1995132656342 0)

OGRFeature(entities):174
  Layer (String) = 3
  SubClasses (String) = AcDbEntity:AcDbText:AcDbText


> grep -C 30 A253G1 b.dxf
0
  0
TEXT
  5
1A7
100
AcDbEntity
  8
3
 62
2
420
16776960
370
-1
 48
1.0
  6
ByLayer
100
AcDbText
 10
92.3107623117302722
 20
70.1995132656341667
 30
0.0
 40
0.3
  1
A253G1
 50
2.4499999999999971
 41
1.0
  7
textstyle36
 71
0
 72
1
 11
93.0722740634091252
 21
70.382130627431664
 31
0.0
100
AcDbText
 73
0
  0
TEXT
  5
1A8
100
AcDbEntity
  8
3
 62
2
```
The same entity in QCAD community edition:
![Screenshot from 2019-08-15 09-36-54](https://user-images.githubusercontent.com/9982519/63073996-8879b300-bf40-11e9-810c-c72c0789a38f.png)

## Operating system

Debian testing (upgraded to the latest release)

## GDAL version and provenance

2.4.2 package of the Debian testing

**Comment by rouault** [comment]
CC @atlight

**Comment by atlight** [comment]
It's not possible for GDAL to calculate "the length and height of the text string itself", because it has no knowledge of font metrics (unlike QCAD). Instead, you have access to both the first and second alignment points. The first alignment point is the feature geometry, and the second alignment point is found by adding the (dx,dy) values from the style string to the feature geometry.
