### ISSUE TITLE
GeoPDF composition creates corrupt PDF

### ISSUE THREAD

**Issue by nyalldawson** [OSGeo/gdal#1783]
With the attached input datasets and composition file, GDAL is creating a truncated/corrupt PDF file. 

I've created others using the same input datasets, which work fine. The only thing I can see which is different between them and these ones is the dpi and page size settings...

[components.zip](https://github.com/OSGeo/gdal/files/3508088/components.zip)

**Comment by chazanov** [comment]
@nyalldawson Have you compiled GDAL with poppler or with pdfium? I've discovered issues introduced between 3.0.0 and 3.0.1: https://github.com/OSGeo/gdal/issues/1760

**Comment by nyalldawson** [comment]
@chazanov poppler

**Comment by rouault** [comment]
@nyalldawson I can't reproduce any corruption. Here's the PDF I get 
[out.pdf](https://github.com/OSGeo/gdal/files/3510935/out.pdf) In case this would be relevant, what is your poppler version ?

**Comment by nyalldawson** [comment]
It's 0.67.

**Comment by rouault** [comment]
I just tried with 0.67.0 and can't reproduce a corruption when trying with swig/python/samples/gdal_create_pdf.py

**Comment by nyalldawson** [comment]
Sorry - false alarm. This was caused by another part of the script having an open file reference to the destination file used to export the PDF to. My apologies!
