### ISSUE TITLE
gdal_translate CCITTFAX4 and TILED=YES Incompatibility

### ISSUE THREAD

**Issue by Saijin-Naib** [OSGeo/gdal#1786]
## Expected behavior and actual behavior.
Expected: Able to set up following options and produce a valid GeoTIFF/COG
COMPRESSION=CCITTFAX4
TILED=YES
NBITS=1

Actual:
Receive the following errors until TILED=YES removed
QGIS version: 3.8.1-Zanzibar
QGIS code revision: dcd95cc648
Qt version: 5.11.2
GDAL version: 2.4.1
GEOS version: 3.7.2-CAPI-1.11.0 b55d2125
PROJ version: Rel. 5.2.0, September 15th, 2018
Processing algorithm…
Algorithm 'Translate (convert format)' starting…
Input parameters:
{ 'COPY_SUBDATASETS' : False, 'DATA_TYPE' : 0, 'INPUT' : 'C:/Users/user/Desktop/taxplates_nometadata/VRT.vrt', 'NODATA' : None, 'OPTIONS' : 'COMPRESS=CCITTFAX4|NBITS=1|TILED=YES', 'OUTPUT' : 'C:/Users/user/Desktop/taxplates_nometadata/VRT.tif', 'TARGET_CRS' : None }

GDAL command:
gdal_translate -of GTiff -co COMPRESS=CCITTFAX4 -co TILED=YES C:/Users/use/Desktop/taxplates_nometadata/VRT.vrt C:/Users/user/Desktop/taxplates_nometadata/VRT.tif
GDAL command output:
ERROR 1: TIFFNumberOfTiles:Integer overflow in TIFFNumberOfTiles

ERROR 1: TIFFReadDirectory:Cannot handle zero number of tiles

ERROR 1: TIFFNumberOfTiles:Integer overflow in TIFFNumberOfTiles

ERROR 1: C:/Users/user/Desktop/taxplates_nometadata/VRT.tif:Failed to allocate memory for for "StripOffsets" array (0 elements of 8 bytes each)

ERROR 1: C:/Users/user/Desktop/taxplates_nometadata/VRT.tif:Failed to allocate memory for for "StripByteCounts" array (0 elements of 8 bytes each)

ERROR 1: GTiffCreateCopy():No space for tile arrays

ERROR 1: TIFFNumberOfTiles:Integer overflow in TIFFNumberOfTiles

ERROR 1: TIFFReadDirectory:Cannot handle zero number of tiles

ERROR 1: TIFFNumberOfTiles:Integer overflow in TIFFNumberOfTiles

ERROR 1: TIFFReadDirectory:Cannot handle zero number of tiles

Input file size is 54433617, 33961039

Execution completed in 0.14 seconds
Results:
{'OUTPUT': 'C:/Users/user/Desktop/taxplates_nometadata/VRT.tif'}

Loading resulting layers
The following layers were not correctly generated.<ul><li>C:/Users/user/Desktop/taxplates_nometadata/VRT.tif</li></ul>You can check the 'Log Messages Panel' in QGIS main window to find more information about the execution of the algorithm.

## Steps to reproduce the problem.
Input parameters:
{ 'COPY_SUBDATASETS' : False, 'DATA_TYPE' : 0, 'INPUT' : 'C:/Users/user/Desktop/taxplates_nometadata/VRT.vrt', 'NODATA' : None, 'OPTIONS' : 'COMPRESS=CCITTFAX4|NBITS=1|TILED=YES', 'OUTPUT' : 'C:/Users/user/Desktop/taxplates_nometadata/VRT.tif', 'TARGET_CRS' : None }

## Operating system | GDAL version and provenance

QGIS version | 3.8.1-Zanzibar | QGIS code revision | dcd95cc648
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.7.2-CAPI-1.11.0 | Running against GEOS | 3.7.2-CAPI-1.11.0 b55d2125
PostgreSQL Client Version | 9.2.4 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Windows 10 (10.0) |   |

**Comment by rouault** [comment]
Please provide the input dataset

**Comment by Saijin-Naib** [comment]
Even,

The input dataset is a VRT referencing 95 TIFF files comprised of Tax Plates for a local municipality. I'm uncertain if I can share these data in this manner. Let me see if that is possible.

**Comment by rouault** [comment]
Wait a second. I ctually see in the output `54433617, 33961039`. This is absolutely gigantic ! This would result in a file with 28 billion tiles, and thus 28 billion * 16 bytes just to store the TIFF indexes. The error is completely expected

**Comment by Saijin-Naib** [comment]
Hmm, interesting.

I think there must be some issue with the source TIFFs since their Zoom to Raster Resolution yields a 1:1, which is certainly not true.

Perhaps I should resample at a more reasonable resolution and then try to re-composite it?

(The other compression drivers don't throw that error when put against the same dataset, btw)

**Comment by rouault** [comment]
> Perhaps I should resample at a more reasonable resolution and then try to re-composite it?

Likely

> The other compression drivers don't throw that error when put against the same dataset

I very mouch doubt about that. This is completely unrelated to the compression method. This is a TIFF limitation (or more exactly a libtiff implementation limitation, but quite reasonable)

**Comment by Saijin-Naib** [comment]
Even, we should close this. I've made a mistake about the source of the issue with the compression, as you've noted.

I apologize, and will follow-up again if needed.

Sorry for wasting your time with this.
