### ISSUE TITLE
ESRI Shapefile driver degrades MULTIPOLYGON to POLYGON on write

### ISSUE THREAD

**Issue by rsbivand** [OSGeo/gdal#1787]
## Expected behavior and actual behavior.

I expect ogr2ogr to convert a single feature two exterior ring (the rings touch) MULTIPOLYGON geometry from a GPKG file using the ESRI Shapefile driver without the second exterior ring being changed to interior and the feature to POLYGON. See https://github.com/r-spatial/sf/issues/1130 for details, showing that the driver is failing for this geometry on writing.

## Steps to reproduce the problem.

This file contains MP.gpkg (written from R using **sf** built against GDAL 3.0.1 and -`-with-geos=no`; same result with `--with-geos=yes`).

[case.zip](https://github.com/OSGeo/gdal/files/3511993/case.zip)

```
$ ogrinfo MP.gpkg
INFO: Open of `MP.gpkg'
      using driver `GPKG' successful.
1: file2397e5e7bc7 (Multi Polygon)
$ ogr2ogr -f "ESRI Shapefile" MP.shp MP.gpkg
$ ogrinfo MP.shp
INFO: Open of `MP.shp'
      using driver `ESRI Shapefile' successful.
1: MP (Polygon)
$
```

## Operating system

Fedora 29, updated 

## GDAL version and provenance

GDAL 3.0.1 built from source (with and without GEOS 3.7.2 built from source), PROJ 6.1.1 built from source.

**Comment by rouault** [comment]
The 2 parts of the multipolygon touch on an edge, not a single point. This is not a valid multipolygon per the simple feature geometry definition.
```
$ ogrinfo MP.gpkg -al -q -sql "select st_isvalid(geom) from file2397e5e7bc7"

GEOS warning: Self-intersection at or near point 2 1

Layer name: SELECT
OGRFeature(SELECT):0
  st_isvalid(geom) (Integer) = 0
```

**Comment by rsbivand** [comment]
Yes, but write drivers do not require validity in general, do they? 

```
$ ogrinfo MP.gpkg
INFO: Open of `MP.gpkg'
      using driver `GPKG' successful.
1: file2397e5e7bc7 (Multi Polygon)
$ ogr2ogr -f "GeoJSON" MP.geojson MP.gpkg
$ ogrinfo MP.geojson
INFO: Open of `MP.geojson'
      using driver `GeoJSON' successful.
1: file2397e5e7bc7 (Multi Polygon)
```

The object was invalid before being written using the GPKG driver, and the GeoJSON objects are also invalid.

This is why I rebuilt GDAL --with-geos=no to see whether the driver performs differently when GEOS is available - it made no difference, so something else is checking the validity, which doesn't happen when the drivers are assumed to be SF-compliant.

**Comment by rouault** [comment]
> Yes, but write drivers do not require validity in general, do they?

Indeed. But Shapefile is a bit particular because when writing a polygon/multipolygon, one must write parts with a particular winding order to mark if there are outer or inner rings. This is done by shapelib itself, which is lower level than OGR and thus has lost the information whether a ring is an outer or inner one. So shapelib codes includes a point-in-polygon test to determine if a ring is an inner ring of another one. The way it was written didn't take into account potential non-valid cases like the one of that ticket.
I've tried to improve this per https://github.com/OSGeo/gdal/pull/1788

**Comment by rsbivand** [comment]
Thanks, I'll check after CI completes and if the fix is merged. I like the "Completely degenerate case. Do not bother touching order." comment! I think the OP may have been trying to build polygons from grid patches without unary union, or similar, we don't know what the use case was.

**Comment by rsbivand** [comment]
With reference to https://github.com/r-spatial/sf/issues/1130, both sf @edzer and rgdal linking to GDAL master and including https://github.com/rouault/gdal/tree/shape_fix_1787 (fetched from this upstream) now round-trip the invalid objects (a multipolygon with exterior rings sharing edges). 

It seems that the change did not propagate to ogr2ogr, as ogrinfo is still reporting POLYGON for me, but maybe I didn't check thoroughly. The driver itself now writes a shapefile that round-trips as MULTIPOLYGON from both R packages using it from GDAL.

Thanks very much for looking into this!

The real work-around would be for users to check validity and to union the edge-touching exterior rings before writing, but because SF-compliant drivers accommodate invalid geometries, the ESRI Shapefile driver in this branch also tries to be more permissive when the geometry is a "completely degenerate case. Do not bother touching order." where order refers to the ring direction. We still need to help package authors depending on **sf** and **rgdal** to pass valid geometries, and to push back on users or package functions passing invalid geometries.
