### ISSUE TITLE
static-build: GTiffOneTimeInit try to load a shared module?

### ISSUE THREAD

**Issue by remoe** [OSGeo/gdal#1790]
I've build gdal 2.4.2 (llvm-wasm) with ```--enable-static``` and ```--with-geotiff=internal```. Why does load GTiffDataset::Open -> GTiffOneTimeInit a shared module? It calls _dlsym and _dlopen? I can't see the name of the module in the wasm environment.

**Comment by rouault** [comment]
This is due to https://github.com/OSGeo/gdal/blob/master/gdal/frmts/gtiff/geotiff.cpp#L19382
You can avoid this by enabling `--with-libtiff=internal --with-rename-internal-libtiff-symbols`

**Comment by remoe** [comment]
Thanks for this insider information ;)
