### ISSUE TITLE
Python: add gdal204 for Windows

### ISSUE THREAD

**Issue by olivierpons** [OSGeo/gdal#1791]
As explained [here](https://stackoverflow.com/a/54789312/106140), it would be nice to add the latest version number `C:\PythonXX\Lib\site-packages\django\contrib\gis\gdal\libgdal.py` and just change:

    lib_names = ['gdal203', 'gdal202', 'gdal201', 'gdal20', 'gdal111']

to:

    lib_names = ['gdal204', 'gdal203', 'gdal202', 'gdal201', 'gdal20', 'gdal111']

Otherwise developpers are forced to change the code source of this file which should never be done.

**Comment by rouault** [comment]
This file likely belongs to the Django project, or a project affiliated to it. It is not in GDAL itself. Closing as not a GDAL bug
