### ISSUE TITLE
--disable-driver-avc does not seem to take effect

### ISSUE THREAD

**Issue by hobu** [OSGeo/gdal#1793]
```
/var/task/gdal/gdal/.libs/libgdal.so: undefined reference to `AVCBinReadClose'
/var/task/gdal/gdal/.libs/libgdal.so: undefined reference to `AVCBinReadOpen'
/var/task/gdal/gdal/.libs/libgdal.so: undefined reference to `AVCBinReadNextTableRec
```

**Comment by rouault** [comment]
The support for --disable-driver-XXXX is rather raw and doesn't track inter-driver dependencies. The AVC code is also used by the GDAL AIGRID driver, so you should also add --disable-driver-aigrid

**Comment by rouault** [comment]
No longer relevant since autoconf has been dropped . For a good reason I don't remember, in CMake builds, the AVC driver is builtin and cannot be disabled
