### ISSUE TITLE
gdal_edit.py changes byte order from 0 to 1 on ENVI Float32 files

### ISSUE THREAD

**Issue by S0sh0rt** [OSGeo/gdal#1796]
I am working with ENVI files of Sentinel-1 SAR data created with SNAP. They are type=Float32 with byte order = 1.  Running a command similar to this:
gdal_edit.py -a_ullr  102 -15 103 -16 Beta0_VH.img
to adjust the georeferencing also, incorrectly changes the byte order header parameter to 0. However, the file data is not byte reordered.

## Operating system
CentOS 6 and 7,  AMD and Intel

## GDAL version and provenance
1.11 from CentOS EPL, 2.2.4 build from source, and 3.0.1 build from source

**Comment by rouault** [comment]
Isn't it the reverse case ? Apparently the ENVI driver always generate file with byte order = 0 (meaning Intel order) on Intel platforms, which is incorrect when updating a file whose byte order = 1 initially.

**Comment by rouault** [comment]
@S0sh0rt ping w.r.t above question

**Comment by rouault** [comment]
Closing due to lack of feedback. Please reopen if you can provide more

**Comment by S0sh0rt** [comment]
Evidently SNAP on Linux produces ENVI files with byte order 0.  The files display correctly and other software correctly displays the files.
The issue here is that gdal_edit.py arbitrarily changes the byte order code to 1 when the operation is to only djust the geocoordinates.  The byte order of the file is not changing, just the geocoordinates, so changing the code to 1 is incorrect. @rouault

**Comment by rouault** [comment]
I cannot reproduce a change of byte order from 0 to 1 when using gdal_edit.py. Can you attach the original dataset (or anyone with which you could reproduce the issue?)
hum: I assumed that you were running a Intel compatible machine (or a CPU with little endian order), but if you run a CPU with big endian order, then that might explain it.

**Comment by S0sh0rt** [comment]
I apologize for the confusion. After reading this again, I see that it is not obvious that it is just the ENVI header parameter: "byte order = 1" that is changed to 0, and not the byte order of the file that is changed.   I also must have initially reported the byte order parameter reversed (0=>1 instead of 1=>0)).
The problem can be reproduced by editing any ENVI file *.hdr and changing the byte order parameter to 1, then run:   gdal_edit.py -a_ullr 50.1 36.8 50.2 36.7 test.dat
The data in this file is byte order 0, and therefore will not display correctly with byte order 1 as delivered below.  The dataset is provided to just to reproduce the issue with the ENVI header file byte order incorrectly being changed by gdal_edit.py from 1 to 0.
[test.zip](https://github.com/OSGeo/gdal/files/3596251/test.zip)

**Comment by S0sh0rt** [comment]
I just tested using GDAL 2.4 in Cygwin on my Windows desktop. The effect is the same.  gdal_edit.py changed the byte order parameter from 1 to 0, although the data was not reordered.

**Comment by rouault** [comment]
> I have a python script in Linux using the gdal (v 3.6.4) ENVI driver to create multi-band ENVI files from those single-band ENVI files. The output multi-band ENVI files all have byte order = 0

that's fully expected. The byte_order of the ENVI driver is a ENVI driver implementation detail that the GDAL generic abstraction is not aware of. GDAL has no way of propagating it to the output file from the source file, unless some specific behavior would be added for that particular use case

**Comment by joaocarr** [comment]
Thanks for the quick reply. You're saying gdal per se will always generate files with byte order = 0?

**Comment by rouault** [comment]
> You're saying gdal per se will always generate files with byte order = 0?

yes, when creating new files (on little endian ordered hosts, that is Intel and most CPUs)

**Comment by joaocarr** [comment]
Ok, but I'm on a Linux system that created ENVI files with byte order = 1. Why is gdal changing the byte order? I'm terribly sorry if these are basic questions. Please feel free to close the issue.
