### ISSUE TITLE
X/Y axis units (radian)

### ISSUE THREAD

**Issue by magau** [OSGeo/gdal#1799]
According with the NUWG NetCDF Conventions for naming units, the value "rad" for radian unit shouldn't be used. Instead, the correct value should be "radian".
As one can see in the end of the following document:
https://www.unidata.ucar.edu/software/netcdf/netcdf/Units.html

My proposal to resolve this issue is to add both values ("rad" and "radian") as possible value for the X/Y axis/coordinates unit, in order to keep retro-compatibility.

So, instead of:
`else if( EQUAL( szUnits, "rad" ) )
`
I sugest:
`else if( EQUAL( szUnits, "rad" ) ||  EQUAL( szUnits, "radian" ))
`

As far as I know the following two lines should be changed:

https://github.com/OSGeo/gdal/blob/9e000458e2e65eb90f6822b974e8f5aa21d355b7/gdal/frmts/netcdf/netcdfdataset.cpp#L3642
https://github.com/OSGeo/gdal/blob/9e000458e2e65eb90f6822b974e8f5aa21d355b7/gdal/frmts/netcdf/netcdfdataset.cpp#L3660

Hope this small change can improve the GDAL library in order to keep the NetCDF standard to be used correctly.

Cheers!

**Comment by rouault** [comment]
Are there datasets that use "radian" and you hit that issue ? Your proposed change is reasonable. You could issue a pull request with it.

**Comment by magau** [comment]
Yes. The geostationary projection requires X/Y axis values in radians or km. My objective here is to encourage the data providers to use de "radians" value for the "units" attribute if the choose to represent the coordinates in radians and stop using "rad" which is the units for <absorbed dose>.

**Comment by rouault** [comment]
Fixed per https://github.com/OSGeo/gdal/pull/1803
