### ISSUE TITLE
gdal-3.0.1 compatibility with r-spatial/sf, monocle3

### ISSUE THREAD

**Issue by jbsysadmin** [OSGeo/gdal#1801]
Greetings.
I am a system admin, not software engineer; I apologize if these questions seem odd.

Given a Centos 7.6 OS, and the environment settings below, what other conditions are needed to install r-spatial/sf, using your gdal? Are there any special considerations, environment settings, etc. to be considered when used with proj version 6 and current monocle3?

The goal is an install of monocle3 (https://cole-trapnell-lab.github.io/monocle3/monocle3_docs/#installing-monocle-3). r-spatial/sf is the last dependency. sf installs under R seem to fail because of of discrepancies between proj and gdal. I have asked the r-spatial/sf support. But it occurs to me to bring this to your attention, too.

Error output is at bottom. However, that "missing" proj.h is in fact at /usr/local/company/dept/proj-6.1.1-x86_64/include)

This fails when running R interactively (with "R" or prepending env to that statement) and also when invoked this way:
/bin/R -e "remotes::install_github('r-spatial/sf', configure.args = '--with-gdal-config=/usr/local/company/dept/gdal-3.0.1-x86_64/bin/gdal-config --with-proj-include=/usr/local/company/dept/proj-6.1.1-x86_64/include/ --with-proj-lib=/usr/local/company/dept/proj-6.1.1-x86_64/lib/')" 

Changing the end value of "with-proj-lib" to proj-6.1.1-x86_64/share/proj made no difference.

Thank you for any leads.

Environment settings:

export PATH=/usr/local/company/dept/proj-6.1.1-x86_64/bin:/usr/local/company/dept/proj-6.1.1-x86_64/lib:/usr/local/company/dept/proj-6.1.1-x86_64/include:$PATH
export LD_LIBRARY_PATH=/usr/local/company/dept/proj-6.1.1-x86_64/lib:/usr/local/company/dept/proj-6.1.1-x86_64/include:$LD_LIBRARY_PATH

export PATH=/usr/local/company/dept/gdal-3.0.1-x86_64/bin:/usr/local/company/dept/gdal-3.0.1-x86_64/include:/usr/local/company/dept/gdal-3.0.1-x86_64/lib:$PATH
export LD_LIBRARY_PATH=/usr/local/company/dept/gdal-3.0.1-x86_64/include:/usr/local/company/dept/gdal-3.0.1-x86_64/lib:$LD_LIBRARY_PATH

export PKG_CONFIG_PATH="/usr/local/company/dept/proj-6.1.1-x86_64/lib/pkgconfig"

Selection of error output:
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc -m64 -std=gnu99 accepts -g... yes
checking for gcc -m64 -std=gnu99 option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -m64 -std=gnu99 -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking gdal.h usability... yes
checking gdal.h presence... yes
checking for gdal.h... yes
checking GDAL: linking with --libs only... yes
checking GDAL: /usr/local/company/dept/gdal-3.0.1-x86_64/share/gdal/pcs.csv readable... no
checking GDAL: checking whether PROJ is available for linking:... yes
checking GDAL: checking whether PROJ is available fur running:... yes
configure: pkg-config proj exists, will use it
checking proj.h usability... no
checking proj.h presence... no
checking for proj.h... no
configure: error: proj.h not found in standard or given locations.
ERROR: configuration failed for package ‘sf’
* removing ‘/usr/lib64/R/library/sf’
Error: Failed to install 'sf' from GitHub:

**Comment by rouault** [comment]
This is really something to see with the  r-spatial/sf  team.
