### ISSUE TITLE
Install of rgdal fails, resources in arbitrary places

### ISSUE THREAD

**Issue by jbsysadmin** [OSGeo/gdal#1804]
Related to Issue #1801,

On the invocation below, install of rgdal fails under R 3.6.0. What is needed to get the location of proj library recognized? The item "libproj.so"  is certainly present under proj-6.1.1-x86_64/lib.

Install attempt:

LD_LIBRARY_PATH=/usr/local/company/dept/gdal-3.0.1-x86_64/include:/usr/local/company/dept/gdal-3.0.1-x86_64/lib:/usr/local/company/dept/proj-6.1.1-x86_64/lib:/usr/local/company/dept/proj-6.1.1-x86_64/include PKG_CONFIG_PATH="/usr/local/company/dept/proj-6.1.1-x86_64/lib/pkgconfig" PROJ_LIB="/usr/local/company/dept/proj-6.1.1-x86_64/share/proj" /bin/R -e "install.packages('rgdal', repos='http://archive.linux.duke.edu/cran')" 

Result:

/bin/ld: cannot find -lproj
collect2: error: ld returned 1 exit status
make: *** [rgdal.so] Error 1
ERROR: compilation failed for package ‘rgdal’
* removing ‘/usr/lib64/R/library/rgdal’

Thank you for any leads.

**Comment by rouault** [comment]
Please don't use the GDAL issue tracker for issues related to other packages. Closing as not a GDAL bug
