### ISSUE TITLE
Is "ocea" projection supported?

### ISSUE THREAD

**Issue by hhrhhr** [OSGeo/gdal#1806]
## Expected behavior and actual behavior.

I have a georeferenced tiff with GCP embedded ([world.zip](https://github.com/OSGeo/gdal/files/3544453/world.zip), 500 Kb). I wanted a reproject it in the Oblique Cylindrical Equal Area using gdalwarp, something like this:

![Cylindrical_Equal-Area_Projection_Oblique_Case_Map_of_the_World](https://user-images.githubusercontent.com/966048/63743933-826fc480-c8a6-11e9-8502-05ef39e8100e.png)

but get error:

```
ERROR 1: Translating source or target SRS failed:
+proj=ocea +lonc=0.0 +alpha=45.0
Usage: gdalwarp [--help-general] [--formats]
--cuttet--
```

## Steps to reproduce the problem.

`>gdalwarp -s_srs "+proj=longlat" -t_srs "+proj=ocea +lonc=0.0 +alpha=45.0" world.tiff world_ocea.tiff`

## Operating system

Ubuntu 16.10 64 bit, Windows 10 64 bit

## GDAL version and provenance

Ubuntu — GDAL 2.2.3, released 2017/11/20
Windows — GDAL 2.4.1, released 2019/03/15, from OSGeo4W

**Comment by jratike80** [comment]
Please do not ask questions here. Questions should go to the gdal-dev mailing list (https://lists.osgeo.org/mailman/listinfo/gdal-dev)
or other support forums. GitHub issues are for bug reports and suggestions
for new features.

With my GDAL version 3.1.0dev from gisinternals the command runs fine.

```
gdalwarp  -t_srs "+proj=ocea +lonc=0.0 +alpha=45.0" file1.tif world_ocea.tiff
Creating output file that is 11392P x 11395L.
....
```

**Comment by hhrhhr** [comment]
This was not a “question”, this is a description of a bug. In the news (https://github.com/OSGeo/gdal/blob/v3.0.1/gdal/NEWS) I did not find information that something was changing or fixed for the ocea projection.

Could you share your `file1.tif` file for verification?

**Comment by rouault** [comment]
Due to GDAL 3 / PROJ 6 rework, all of PROJ methods will work out of the box. So this is kind of implictly doumented :-) With older GDAL versions, you need to add +wktext to the PROJ string
