### ISSUE TITLE
vsis3: Docs reference AWS_PROFILE, code reads AWS_DEFAULT_PROFILE

### ISSUE THREAD

**Issue by pedros007** [OSGeo/gdal#1807]
The [vsis3 docs](https://gdal.org/user/virtual_file_systems.html#vsis3-aws-s3-files-random-reading) state

> The profile may be specified with the `AWS_PROFILE` environment variable (the default profile is “default”)

```sh
$ env AWS_PROFILE=foo gdalinfo /vsis3/bucket/prefix.tif
ERROR 14: Access Denied
```

However, the code does not look for that variable.  Instead, it looks for `AWS_DEFAULT_PROFILE`

https://github.com/OSGeo/gdal/blob/dabadf7986c0d88fd0131a64ec69275ec0fe3969/gdal/port/cpl_aws.cpp#L813

```
$ env AWS_DEFAULT_PROFILE=foo gdalinfo /vsis3/bucket/prefix.tif
... correctly returns gdalinfo of the file
````

Also FWIW, the `AWS_PROFILE` setting does not work when the credentials file is configured to assume a role for a user in a different profile.  The details of that are described in [Using an IAM Role in the AWS CLI
](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-role.html)

**Comment by rouault** [comment]
Thanks. Fixed. By the way you can easily contribute document fixes with the "Edit on github" link on the top right of each page on gdal.org
