### ISSUE TITLE
COG driver LERC compression support?

### ISSUE THREAD

**Issue by smnorris** [OSGeo/gdal#1812]
## Expected behavior and actual behavior.

Using the GeoTIFF driver I am able to use this option:
`-co COMPRESS=LERC_DEFLATE`

But this option is not available using the new COG driver in v3.1:
https://github.com/OSGeo/gdal/blob/b1c9c12ad373e40b955162b45d704070d4ebf7b0/gdal/frmts/gtiff/geotiff.cpp#L19705

It would be great to be able to use LERC to shrink down my DEM files as per https://kokoalberti.com/articles/geotiff-compression-optimization-guide/. But maybe I am not understanding LERC and COG specs? Is LERC compression not compatible with goals of COG files? 

## Steps to reproduce the problem.
```
$ docker run -ti --rm -v $(pwd):/data osgeo/gdal:ubuntu-full-latest gdal_translate data/inputs/82e_042/bc_082e042_xli1m_utm11_2018.asc /data/outputs/OWB_82e042.tif -of COG -co COMPRESS=LERC_DEFLATE -co RESAMPLING=CUBIC
Input file size is 14896, 11639
Warning 6: 'LERC_DEFLATE' is an unexpected value for COMPRESS creation option of type string-select.
```

## Operating system

MacOS, Docker 2.1.0.1

## GDAL version and provenance

`docker pull osgeo/gdal:ubuntu-full-latest`

**Comment by rouault** [comment]
Well the COG "spec" doesn't say anything about which compression schemes should be affected. In the initial implementation effort there was no clear need for LERC compression, so I omitted it to limit the number of options, but it should be mostly trivial to add it. However I'm pretty sure most a number of non-GDAL based COG consumer will have troubles with "fancy" compression schemes. At the same time the driver allows for ZSTD or WEBP compression, which also are non-standard comprssion schemes for TIFF, also with a likely higher uptake than LERC.
@cholmes @vincentsarago What would be your opinion on this ?

**Comment by vincentsarago** [comment]
@rouault Thanks for asking, 
We talked about LERC in COG today at FOSS4G, so I had the feeling it was supported by COG but I was wrong. My take is that if it was supported by the previous way of creating COG, it would be nice to still support it in the new COG driver. 

@rouault when you say `ZSTD or WEBP compression, which also are non-standard comprssion schemes for TIFF` do you mean that is not supported at all in the basic libtiff ? (I guess this is why you need to compile GDAL with internal libtiff)

Maybe we could still support those compression scheme but be more upfront with the fact they are GDAL supported compression scheme and might not work on non-GDAL backed software ?

**Comment by smnorris** [comment]
I'll add that it will not work just on non-GDAL backed software. Many pre-compiled GDAL builds won't support it either - at least that has been my experience with ZSTD

**Comment by rouault** [comment]
> when you say `ZSTD or WEBP compression, which also are non-standard comprssion schemes for TIFF` do you mean that is not supported at all in the basic libtiff ?

I meant at the specification point of view. The TIFF 6 specification from 19.. doesn't of course has a provision for them, and as the Adobe registry is dead, libtiff had to self allocate codes for them. So they are not standard from that point of view. That said, they are now plugins available in upstream libtiff (4.0.10), so provided it is compiled with the right dependencies that would work.

Regarding LERC, I didn't dare upstreaming the tif_lerc.c plugin as there's no  real convenient distribution channel for a self contained liblerc, so you need to build GDAL with internal libtiff to get LERC support.

Anyway let's add back LERC_xxx options if that makes things less confusing

**Comment by arogozhnikov** [comment]
@rouault I'm using glal 3.1.2, but unable to use either of LERC-prefixed codecs. 
```
gdal_translate --version
GDAL 3.1.2, released 2020/07/07
```
Error:
```
Warning 6: 'LERC_ZSTD' is an unexpected value for COMPRESS creation option of type string-select.
```

**Comment by rouault** [comment]
> but unable to use either of LERC-prefixed codecs.

You need to build GDAL with its internal libtiff copy

**Comment by vincentsarago** [comment]
Sorry to jump on this old issue but I'm not able to create COG with lerc using the latest gdal docker images 

```
docker run --volume $(pwd)/:/tmp/ osgeo/gdal:alpine-ultrasmall-latest gdal_translate -of COG /tmp/image_float.tif /tmp/cog.tif -co COMPRESS=LERC
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
Input file size is 316, 341
Warning 6: 'LERC' is an unexpected value for COMPRESS creation option of type string-select.
Warning 6: 'LERC' is an unexpected value for COMPRESS creation option of type string-select.
ERROR 1: Cannot create TIFF file due to missing codec for LERC.
```

**Comment by rouault** [comment]
The alpine-ultrasmall-latest config uses the libtiff from the system, and as that libtiff doesn't include LERC support, you don't get it.
==> Use alpine-small-latest which uses internal libtiff

**Comment by rouault** [comment]
Precisions added in https://github.com/OSGeo/gdal/commit/89618167bd78e8748afb1770d30fdc82bbd1cef7

**Comment by vincentsarago** [comment]
🤦 thanks @rouault. Side question then, if we built GDAL using external libtiff 4.3.0 we should have LERC available, right ?

**Comment by rouault** [comment]
> f we built GDAL using external libtiff 4.3.0 we should have LERC available, right ?

yes, provided that you build libtiff against https://github.com/esri/lerc
