### ISSUE TITLE
gdal_transform: scale does not conform to prescribed range

### ISSUE THREAD

**Issue by aloboa** [OSGeo/gdal#1813]
## Expected behavior and actual behavior.
Goal: stretching a float image from its 2% to 98% quantiles to the 1-255 range (to ultimately leave 0 as nodata) saving as Byte (uint8).  
Result: Surprisingly, the output image has range from 0 to 255, not from 1 to 255 as prescribed in the command. Note I did not set nodata as 0 on purpose to verify the stretching:
 [Link to small test input image](https://www.dropbox.com/s/0vstg5cexlxodl7/imatest.tif)
Stats of input image:
```
gdalinfo imatest.tif
Band 1 Block=100x6 Type=Float32, ColorInterp=Gray
  Min=-7.623 Max=7.619
  Minimum=-7.623, Maximum=7.619, Mean=0.002, StdDev=1.999
  NoData Value=-9999
  Metadata:
    STATISTICS_MAXIMUM=7.6186722387237
    STATISTICS_MEAN=0.0020230046008175
    STATISTICS_MINIMUM=-7.6234764067032
    STATISTICS_STDDEV=1.9993564257
Band 2 Block=100x6 Type=Float32, ColorInterp=Undefined
  Min=-15.247 Max=15.237
  Minimum=-15.247, Maximum=15.237, Mean=0.004, StdDev=3.999
  NoData Value=-9999
  Metadata:
    STATISTICS_MAXIMUM=15.237344477447
    STATISTICS_MEAN=0.004046009201635
    STATISTICS_MINIMUM=-15.246952813406
    STATISTICS_STDDEV=3.9987128514
Band 3 Block=100x6 Type=Float32, ColorInterp=Undefined
  Min=2.377 Max=17.619
  Minimum=2.377, Maximum=17.619, Mean=10.002, StdDev=1.999
  NoData Value=-9999
  Metadata:
    STATISTICS_MAXIMUM=17.618672238724
    STATISTICS_MEAN=10.002023004601
    STATISTICS_MINIMUM=2.3765235932968
    STATISTICS_STDDEV=1.9993564257
```

## Steps to reproduce the problem.
(quantiles computed beforehand with R)
`gdal_translate -scale -4.06086443207913 4.06143129525944 1 255 -scale -8.12172886415826 8.12286259051888 1 255 -scale 5.93913556792087 14.0614312952594 1 255 -ot "Byte" -of "GTiff" "imatest.tif" "imateststretchgdal.tif"`

Surprisingly, the output image has range from 0 to 255, not from 1 to 255 as prescribed in the command. Note I did not set nodata as 0 on purpose to verify the stretching:

```
gdalinfo -stats imateststretchgdal.tif
.../...
Band 1 Block=100x27 Type=Byte, ColorInterp=Gray
  Minimum=0.000, Maximum=255.000, Mean=115.180, StdDev=68.898
  NoData Value=-9999
  Metadata:
    STATISTICS_MAXIMUM=255
    STATISTICS_MEAN=115.1802
    STATISTICS_MINIMUM=0
    STATISTICS_STDDEV=68.898160555707
    STATISTICS_VALID_PERCENT=100
Band 2 Block=100x27 Type=Byte, ColorInterp=Undefined
  Minimum=0.000, Maximum=255.000, Mean=115.180, StdDev=68.898
  NoData Value=-9999
  Metadata:
    STATISTICS_MAXIMUM=255
    STATISTICS_MEAN=115.1802
    STATISTICS_MINIMUM=0
    STATISTICS_STDDEV=68.898160555707
    STATISTICS_VALID_PERCENT=100
Band 3 Block=100x27 Type=Byte, ColorInterp=Undefined
  Minimum=0.000, Maximum=255.000, Mean=115.180, StdDev=68.898
  NoData Value=-9999
  Metadata:
    STATISTICS_MAXIMUM=255
    STATISTICS_MEAN=115.1802
    STATISTICS_MINIMUM=0
    STATISTICS_STDDEV=68.898160555707
    STATISTICS_VALID_PERCENT=100
```

## Operating system
Windows 7
## GDAL version and provenance
GDAL 2.4.0, released 2018/12/14
(From QGIS 3.4 install)

**Comment by rouault** [comment]
> Surprisingly, the output image has range from 0 to 255, not from 1 to 255 as prescribed in the command

This is not so surprising in fact. I guess you would have expected that input values between the actual minimum input in the dataset and the minimum input you give would be set to the minimum output, and similar for the maximum. But the implementation doesn't do such clipping, and extends the linear stretching outside of the input range you give. So the effect of -scale is just to define a offset & scale to apply to values. We would probably need a -scaleclip switch for the behaviour you likely expect.

**Comment by aloboa** [comment]
It is surprising if you expect the doc to be true:

> -scale [src_min src_max [dst_min dst_max]]
> "Rescale the input pixels values from the range src_min to src_max to the range dst_min to dst_max."
The new range after applying -scale is not src_min to src_max  at it should be according to the documentation.  
I do not think we need a new switch, I think this an error.

**Comment by rouault** [comment]
> The new range after applying -scale is not dst_min to dst_max at it should be according to the documentation.

The documentation doesn't say that. It specifies that any input in range [src_min, src_max] is transformed to [dst_min, dst_max]. It doesn't specify what happens for input < src_min or > src_max.

**Comment by aloboa** [comment]
It does say it indeed:
"to the **range** dst_min to dst_max" 

The range is, by definition, the min value and the max value. If the output has values
outside dst_min to dst_max, then the range is not dst_min to dst_max and thus the output does not conform to what is stated in the doc.

**Comment by jratike80** [comment]
If you feel that the documentation is unclear (I feel that it is indeed) you can suggest how to improve it. You can also do that also by yourself, there is a "Edit on GitHub" button on the top-right corner on the manual page https://gdal.org/programs/gdal_translate.html#gdal-translate.

New -scaleclip option might be worth making a new enhancement ticket.

**Comment by aloboa** [comment]
I rather feel that the program does not conform to the doc, not that the doc is wrong or  unclear. But if you want to do it that way, this is what I suggest:
-scale: "Rescale the input pixels values from the range src_min to src_max to dst_min to dst_max. Clipping controlled by the -scaleclip switch
-scaleclip: "Clip output values to the effective range dst_min to dst_max defined in -scale  

Do I have to submit a ticket for requesting -scaleclip?

**Comment by jratike80** [comment]
Relavant things are that -scale works as is works without clipping and -scaleclip does not exist. Documentation should reflect the reality so there is nothing to document about -scaleclip and the point to concentrate on is how to describe the "range" better so users understand that "range" means all that is between given lower-higher values which do not need to be absolute min-max values, and values outside the "range" are scaled linearly.

If you submit a ticket about implementing -scaleclip it won't be forgotten so easily. It does not guarantee that it will be implemented soon but it remains on the to-do list.

**Comment by aloboa** [comment]
#1825 submitted
Closing this one
