### ISSUE TITLE
Create DXF File ,can not find the field "RawCodeValues"

### ISSUE THREAD

**Issue by thishzw** [OSGeo/gdal#1814]
## Expected behavior and actual behavior.

I create a new DXF file,and want to use the RawCodeValues Filed,but I Can't get  it.
Then I found that when creating a DXF file,the function don't create the RawCodeValue Filed.
//ogrdxfwriterlayer.cpp
line 55
 OGRDXFDataSource::AddStandardFields( poFeatureDefn,ODFM_IncludeBlockFields );

## Steps to reproduce the problem.

Create DXF File ,can not find the field "RawCodeValues"

## Operating system

win10 ,VS2015

## GDAL version and provenance

GDAL 3.0

**Comment by rouault** [comment]
This is available on reading only, when the DXF_INCLUDE_RAW_CODE_VALUES configuration option is set to YES.

**Comment by thishzw** [comment]
I already have a old software that save DXF file,and there are some special value being saved in RAW_CODE_VALUES.Now,I want to make new software can save DXF file,which also have the same special value,can open by the old one.Is there anyway to do it?
