### ISSUE TITLE
Transform Z coordinate doesn't works on a lot of canonical Coordinate System in GDAL 3.

### ISSUE THREAD

**Issue by aharondavid** [OSGeo/gdal#1818]
Transform Z coordinate  doesn't works on a lot of canonical Coordinate System  in GDAL 3.

## Steps to reproduce the problem.

transform coordinate  Z doesn't works, for example, on the following CS's:

**sources CS samples:**

1. 

PROJCS["ENU (-77.410692720411:39.4145340892321)",GEOGCS["WGS 84",DATUM["World Geodetic System 1984",SPHEROID["WGS 84",6378137.0,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0.0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.017453292519943295],AXIS["Geodetic latitude",NORTH],AXIS["Geodetic longitude",EAST],AXIS["Ellipsoidal height",UP],AUTHORITY["EPSG","4979"]],PROJECTION["Orthographic"],PARAMETER["Latitude_Of_Center",39.4145340892321],PARAMETER["Longitude_Of_Center",-77.410692720411],PARAMETER["false_easting",0],PARAMETER["false_northing",0],UNIT["Meter",1]]

2. 
PROJCS["OSGB 1936 / British National Grid",GEOGCS["OSGB 1936",DATUM["OSGB_1936",SPHEROID["Airy 1830",6377563.396,299.3249646,AUTHORITY["EPSG","7001"]],AUTHORITY["EPSG","6277"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.01745329251994328,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4277"]],UNIT["metre",1,AUTHORITY["EPSG","9001"]],PROJECTION["Transverse_Mercator"],PARAMETER["latitude_of_origin",49],PARAMETER["central_meridian",-2],PARAMETER["scale_factor",0.9996012717],PARAMETER["false_easting",400000],PARAMETER["false_northing",-100000],AUTHORITY["EPSG","27700"],AXIS["Easting",EAST],AXIS["Northing",NORTH]]

3.
PROJCS["Orthographic (-85.4876596902845000,32.6035190542778000)",GEOGCS["GCS_WGS_1984",DATUM["D_unknown",SPHEROID["WGS84",6378137,298.257223563]],PRIMEM["Greenwich",0],UNIT["Degree",0.017453292519943295]],PROJECTION["Orthographic"],PARAMETER["Latitude_Of_Center",32.6035190542778000],PARAMETER["Longitude_Of_Center",-85.4876596902845000],PARAMETER["false_easting",0],PARAMETER["false_northing",0],UNIT["Meter",1]]

**Destination CS:**

COMPD_CS["WGS 84 + EGM96 geoid height",
    GEOGCS["WGS 84",
        DATUM["WGS_1984",
            SPHEROID["WGS 84",6378137,298.257223563,
                AUTHORITY["EPSG","7030"]],
            AUTHORITY["EPSG","6326"]],
        PRIMEM["Greenwich",0,
            AUTHORITY["EPSG","8901"]],
        UNIT["degree",0.0174532925199433,
            AUTHORITY["EPSG","9122"]],
        AXIS["Latitude",NORTH],
        AXIS["Longitude",EAST],
        AUTHORITY["EPSG","4326"]],
    VERT_CS["EGM96 height",
        VERT_DATUM["EGM96 geoid",2005,
            AUTHORITY["EPSG","5171"]],
        UNIT["metre",1,
            AUTHORITY["EPSG","9001"]],
        AXIS["Gravity-related height",UP],
        AUTHORITY["EPSG","5773"]]] 

## Operating system

Windows 10

## GDAL version and provenance

GDAL 3 compiled with Proj4 version 6.1.
proj data folder contain all the data that downloaded from Proj4

**Comment by rouault** [comment]
That's more a PROJ "issue" (can be discussed if it is a feature or a bug). You'll get Z transform only if both your input and output CRS are 3D:
```
$ echo "2 49 0" | gdaltransform -s_srs EPSG:4979 -t_srs EPSG:4326+5773
2 49 -44.6434936523438
```
vs
```
$ echo "2 49 0" | gdaltransform -s_srs EPSG:4326 -t_srs EPSG:4326+5773
2 49 0
```
Anyway, there's nothing GDAL itself can do about that. This is completely handled by PROJ. So closing as not a GDAL bug.

**Comment by aharondavid** [comment]
The first CS is 3D. about the second and the third I am not sure, how can I make them 3D ?
Any way, I will transfer this issue to PROJ.

Thanks!

**Comment by rouault** [comment]
> The first CS is 3D

Indeed, but specifying 3 axes for a geographic CRS in WKT1 wasn't supported (WKT1 didn't support Geographic 3D CRS). So either use WKT2, or just remove the axis definition in the WKT1 string to just keep the AUTHORITY["EPSG", 4979] node. That's not pedantically 'valid' WKT1, but the PROJ WKT1 parser doesn't complain about that.
```
$ echo "0 0 0" | gdaltransform -s_srs 'PROJCS["ENU (-77.410692720411:39.4145340892321)",GEOGCS["WGS 84",DATUM["World Geodetic System 1984",SPHEROID["WGS 84",6378137.0,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0.0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.017453292519943295],AUTHORITY["EPSG","4979"]],PROJECTION["Orthographic"],PARAMETER["Latitude_Of_Center",39.4145340892321],PARAMETER["Longitude_Of_Center",-77.410692720411],PARAMETER["false_easting",0],PARAMETER["false_northing",0],UNIT["Meter",1]]' -t_srs EPSG:4326+3855-77.410692720411 39.4145340892321 33.5861897709484
```
> about the second and the third I am not sure, how can I make them 3D ?

That's not obvious admitedly. You need to edit the WTK definition to replace the GEOGCS 2D by the equivalent GEOGCS 3D.
