### ISSUE TITLE
Crash in OGR2SQLITE_static_register 

### ISSUE THREAD

**Issue by PeterPetrik** [OSGeo/gdal#1820]
## Expected behavior and actual behavior.

when loading project on iPad (see https://github.com/lutraconsulting/input/issues/435) it crashes ogr in `pApi->create_module`. Probably due to static build (iOS does not support dynamic libraries), argument _pApi is nullptr and hence `pApi->create_module` triggers `EXC_BAD_ACCESS` see https://github.com/OSGeo/gdal/blob/6c20fa95d33fd0452329067f766b2d71a5ebd87f/gdal/ogr/ogrsf_frmts/sqlite/ogrsqlitevirtualogr.cpp#L2593

also during compilation of the ogrsqlitevirtualogr.cpp file there is a warning

```
ogrsqlitevirtualogr.cpp:74:5: warning: 'sqlite3_auto_extension' is deprecated: first deprecated in iOS 8.2 - Process-global auto extensions are not supported on Apple platforms
      [-Wdeprecated-declarations]
    sqlite3_auto_extension ((void (*)(void)) OGR2SQLITE_static_register);
    ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.4.sdk/usr/include/sqlite3.h:5997:16: note: 'sqlite3_auto_extension' has been
      explicitly marked deprecated here
SQLITE_API int sqlite3_auto_extension(void(*xEntryPoint)(void));
```

## proposed solution

the crash goes away if I change the line to 

` if( !pApi || pApi->create_module == nullptr ) `

or just remove the call to `sqlite3_auto_extension` in `OGR2SQLITE_Register` alltogether.

I am not sure if we have some flag for IOS builds to ifdef it? 

## Operating system

iOS 12.0

## GDAL version and provenance

GDAL 2.4.0 custom STATIC build from [input-sdk](https://github.com/lutraconsulting/input-sdk/blob/master/ios/recipes/gdal/recipe.sh) with system SQLITE3 (3.24.0)

**Comment by rouault** [comment]
> if( !pApi || pApi->create_module == nullptr )

would be fine for a PR

> just remove the call to sqlite3_auto_extension in OGR2SQLITE_Register alltogether.

You would loose functionnality. If you were to do this, you should replace the call to OGR2SQLITE_Register() at line 762 of ogrsqlitedatasource.cpp by something like
```
OGR2SQLITEModule* poModule = new OGR2SQLITEModule();
poModule->Setup(hDB)
```
(actually moved after the hDB has been instanciated)

> I am not sure if we have some flag for IOS builds to ifdef it?

Good question. I guess there must be some standard #define for iOS builds set by the compiler

**Comment by PeterPetrik** [comment]
you right... let me create PR (my first PR so I expect I miss all the conventions here:) )... BTW do you use astyle (pre-commit hook?) or so to format the code similar to QGIS

**Comment by rouault** [comment]
> BTW do you use astyle (pre-commit hook?) or so to format the code similar to QGIS

no, there's just some minimal styling checks done in some of the Travis configs, mostly to check that no tabulation characters are used
