### ISSUE TITLE
Thread safe use of RPCTransformer with RPC_DEM dataset

### ISSUE THREAD

**Issue by Unril** [OSGeo/gdal#1821]
## Expected behavior and actual behavior.

When calling `GDALRPCTransform` from different thread with the same `pTransformArg` and with set `RPC_DEM`, it uses shared buffer `padfDEMBuffer`. This behaviour leads to data races.

## Steps to reproduce the problem.

* Call `GDALCreateRPCTransformer` with `RPC_DEM` parameter set to some dataset.
* Create `GDALWarpOperation` that uses this transformer.
* Call `WarpRegionToBuffer` concurrently under thread_sanitizer from clang.

## Operating system

Ubuntu 19.04 64 bit.

## GDAL version and provenance

Branch v3.0.1 from github. Build using clang 8.

## Proposed solution

Add config option `GDAL_RPC_USE_DEM_BUFFER` (for example) than disables creation of `padfDEMBuffer`. Later, in `GDALRPCExtractDEMWindow`, there is a check `if( psTransform->padfDEMBuffer == nullptr )` that reads pixel values directly from `poDS`.

```diff
--- a/alg/gdal_rpc.cpp
+++ b/alg/gdal_rpc.cpp
@@ -1900,11 +1900,16 @@
         psTransform->nBufferMaxRadius =
             atoi(CPLGetConfigOption("GDAL_RPC_DEM_BUFFER_MAX_RADIUS", "2"));
         psTransform->nHitsInBuffer = 0;
-        const int nMaxWindowSize = 4;
-        psTransform->padfDEMBuffer = static_cast<double*>(VSIMalloc(
-            (nMaxWindowSize + 2 * psTransform->nBufferMaxRadius) *
-            (nMaxWindowSize + 2 * psTransform->nBufferMaxRadius) *
-            sizeof(double) ));
+        psTransform->padfDEMBuffer = nullptr;
+        // Disable DEM buffer when calling RPCTransform from differen threads.
+        if( CPLTestBool(CPLGetConfigOption("GDAL_RPC_USE_DEM_BUFFER", "YES")) )
+        {
+            const int nMaxWindowSize = 4;
+            psTransform->padfDEMBuffer = static_cast<double*>(VSIMalloc(
+                (nMaxWindowSize + 2 * psTransform->nBufferMaxRadius) *
+                (nMaxWindowSize + 2 * psTransform->nBufferMaxRadius) *
+                sizeof(double) ));
+        }
         psTransform->nBufferX = -1;
         psTransform->nBufferY = -1;
         psTransform->nBufferWidth = -1;

```

**Comment by rouault** [comment]
> When calling `GDALRPCTransform` from different thread with the same `pTransformArg`

You shouldn't do that at all. A pTransformArg can be only used by one thread at a time. Instanciate as many pTransformArg as threads you have. You might also run into issues with concurrent access to the DEM dataset.

**Comment by Unril** [comment]
> > When calling `GDALRPCTransform` from different thread with the same `pTransformArg`
> 
> You shouldn't do that at all. A pTransformArg can be only used by one thread at a time. Instanciate as many pTransformArg as threads you have. You might also run into issues with concurrent access to the DEM dataset.

I use custom thread-safe datasets for dem and source. So far I discovered only 2 data races in concurrent use of `WarpRegionToBuffer` with RPC transformer: here and in `OGRProjCT::Transform` (seems that there should be `proj_clone` instead of `proj_assign_context`). I think it is possible to make this functions more or less thread-safe.

**Comment by rouault** [comment]
>  I think it is possible to make this functions more or less thread-safe

This is not a design goal for the upstream project. Too risky. You're free to experiment on that on your own fork of course, but I don't think we want that in upstream GDAL.
