### ISSUE TITLE
Tiling 16-bit monochrome tifs produces corrupt tiles

### ISSUE THREAD

**Issue by nmoehrle** [OSGeo/gdal#1823]
## Expected behavior and actual behavior.

Tiling 16-bit monochrome tif image with `gdal_translate` produces corrupt tiles on the right border.

![test](https://user-images.githubusercontent.com/4200007/64436120-ff2f4980-d0c3-11e9-900e-a67d5f52f9b5.png)

![test-tiled](https://user-images.githubusercontent.com/4200007/64436144-10785600-d0c4-11e9-896b-51939daeaef2.png)

## Steps to reproduce the problem.

```
curl -LO https://github.com/OSGeo/gdal/files/3584404/tiling.tar.gz
tar -xf tiling.tar.gz
gdal_translate test.tif -co "TILED=YES" test-tiled-new.tif
```
[tiling.tar.gz](https://github.com/OSGeo/gdal/files/3584404/tiling.tar.gz)

## Operating system

Ubuntu 18.04 64 bit

## GDAL version and provenance

I have tried 2.1.3, 2.2.3 and 6c20fa95d33fd0452329067f766b2d71a5ebd87f with and without internal libtiff and geotiff. I've use gcc-7 (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0 to build the master and gcc-5 (Ubuntu 5.5.0-12ubuntu1) 5.5.0 20171010 was used to build the version 2.1.3.

This is the first ever issue I encountered while using gdal, thank you for the library and for all the work you have put in. I hope I have given you all the information to track this down.

Best wishes,
Nils

**Comment by jratike80** [comment]
Works for me without troubles on Windows with GDAL 2.4.0 from OSGeo4W and with GDAL 3.1.0dev from gisinternals.com. QGIS 3.4.0 was used for testing. Test-tiled.tif that was included in the archive looks good as well but you did not tell why it was included.

**Comment by nmoehrle** [comment]
The test-tiled.tif is the one I used to produce the test-tiled.png that is shown above. I have used convert (Version: ImageMagick 6.9.7-4 Q16 x86_64 20170114 http://www.imagemagick.org) for the conversion. I checked with a Windows machine and can confirm that it looks good there.

So I guess this means that the viewing on Linux is the issue.
The image is incorrectly displayed in feh (2.23.2) and eog (3.28.1), OpenCV (4.1.0) and ImageMagick(6.9.7-4) also interpret it incorrectly.
The image is correctly displayed in QGIS (3.8.1-Zanzibar) and GIMP (2.8.22 only 8bit).

Are you aware of anything that could cause this differing behavior?

**Comment by rouault** [comment]
I can also reproduce the incorrect display with eog 3.18.2 and the display utility from ImageMagick 6.8.9.9. I presume those utilities might have issues with dealing with non-Byte tiled TIFF.
If I do `gdal_translate test.tif -co "TILED=YES" test-tiled-byte.tif -ot byte -scale` to rescale to 8bit, this displays correctly.
Given that some utilities are able to display the tiles 16-bit image correctly, I don't think there's anything wrong in the way that GDAL generates this image.

**Comment by nmoehrle** [comment]
I concur, so I will close this ticket and open up issues for the respective viewers.
