### ISSUE TITLE
Failed to build gdal 2.4.2 python binding

### ISSUE THREAD

**Issue by seraphzl** [OSGeo/gdal#1824]
## Expected behavior and actual behavior.

When build python binding from gdal 2.4.2 release, it failed and output:

running build
running build_py
creating build
creating build/lib.linux-x86_64-2.7
copying gdal.py -> build/lib.linux-x86_64-2.7
copying ogr.py -> build/lib.linux-x86_64-2.7
copying osr.py -> build/lib.linux-x86_64-2.7
copying gdalconst.py -> build/lib.linux-x86_64-2.7
copying gdalnumeric.py -> build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/osgeo
copying osgeo/gdalnumeric.py -> build/lib.linux-x86_64-2.7/osgeo
copying osgeo/ogr.py -> build/lib.linux-x86_64-2.7/osgeo
copying osgeo/gnm.py -> build/lib.linux-x86_64-2.7/osgeo
copying osgeo/osr.py -> build/lib.linux-x86_64-2.7/osgeo
copying osgeo/gdalconst.py -> build/lib.linux-x86_64-2.7/osgeo
copying osgeo/gdal_array.py -> build/lib.linux-x86_64-2.7/osgeo
copying osgeo/__init__.py -> build/lib.linux-x86_64-2.7/osgeo
copying osgeo/gdal.py -> build/lib.linux-x86_64-2.7/osgeo
running build_ext
/home/lz/app/gcc-4.8.5/bin/gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I../../port -I../../gcore -I../../alg -I../../ogr/ -I../../ogr/ogrsf_frmts -I../../gnm -I../../apps -I/home/lz/app/python-2.7.15/include/python2.7 -I/home/lz/app/python-2.7.15/lib/python2.7/site-packages/numpy/core/include -I/home/lz/software/gdal-2.4.2/include -c gdal_python_cxx11_test.cpp -o gdal_python_cxx11_test.o
/home/lz/app/gcc-4.8.5/bin/gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I../../port -I../../gcore -I../../alg -I../../ogr/ -I../../ogr/ogrsf_frmts -I../../gnm -I../../apps -I/home/lz/app/python-2.7.15/include/python2.7 -I/home/lz/app/python-2.7.15/lib/python2.7/site-packages/numpy/core/include -I/home/lz/software/gdal-2.4.2/include -c gdal_python_cxx11_test.cpp -o gdal_python_cxx11_test.o -std=c++11
building 'osgeo._gdal' extension
creating build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/extensions
/home/lz/app/gcc-4.8.5/bin/gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I../../port -I../../gcore -I../../alg -I../../ogr/ -I../../ogr/ogrsf_frmts -I../../gnm -I../../apps -I/home/lz/app/python-2.7.15/include/python2.7 -I/home/lz/app/python-2.7.15/lib/python2.7/site-packages/numpy/core/include -I/home/lz/software/gdal-2.4.2/include -c extensions/gdal_wrap.cpp -o build/temp.linux-x86_64-2.7/extensions/gdal_wrap.o -std=c++11 -I/home/lz/software/gdal-2.4.2/port -I/home/lz/software/gdal-2.4.2/gcore -I/home/lz/software/gdal-2.4.2/alg -I/home/lz/software/gdal-2.4.2/ogr -I/home/lz/software/gdal-2.4.2/ogr/ogrsf_frmts -I/home/lz/software/gdal-2.4.2/frmts/vrt -I/home/lz/software/gdal-2.4.2/apps
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
/home/lz/app/gcc-4.8.5/bin/g++ -pthread -shared build/temp.linux-x86_64-2.7/extensions/gdal_wrap.o -L../../.libs -L../../ -L/home/lz/software/gdal-2.4.2/lib -lgdal -o build/lib.linux-x86_64-2.7/osgeo/_gdal.so
/usr/bin/ld: ../../.libs/libgdal.a(contour.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
../../.libs/libgdal.a: could not read symbols: Bad value
collect2: error: ld returned 1 exit status
error: command '/home/lz/app/gcc-4.8.5/bin/g++' failed with exit status 1

## Steps to reproduce the problem.

cd $HOME/software/gdal-2.4.2
./configure --prefix=$HOME/app/gdal-2.4.2 --enable-shared=no --with-python
make
make install
cd swig/python
python setup.py build

## Operating system

CentOS 6.10 64 bit

## GDAL version and provenance

2.4.2 release

**Comment by rouault** [comment]
This is likely due to --enable-shared=no . Removing this should fix the error.  Or perhaps adding CFLAGS=-fPIC CXXFLAGS=-fPIC to the ./configure command line
