### ISSUE TITLE
TLS unnecessary allocation and leaks

### ISSUE THREAD

**Issue by rconde01** [OSGeo/gdal#1838]
https://github.com/OSGeo/gdal/blob/3993eb2c54e66ffb5158eaa1ffd77dec8b98cadd/gdal/ogr/ogr_proj_p.cpp#L78

The OSRPJContextHolder calls init in it's contructor which causes creation/allocation of a proj context for every thread created in a process.

- This causes allocation on threads that never use proj
- This is unnecessary because the context is initialized when requested anyhow
- We have seen that OSRPJContextHolder destructor is not called for all threads using visual studio which causes memory leaks.

The simple solution solution is just to remove this line as it gets initialized when requested anyhow.

**Comment by rouault** [comment]
>     * This causes allocation on threads that never use proj

Interesting... I would have expected the object to be initialized only the first time it is actually used, not when a thread is created. Anyway someone reported to me about issues with thread_local objects with Visual Studio if GDAL was dynamically loaded in a thread, and I've committed https://github.com/OSGeo/gdal/commit/7014c40c69c71f90cdb52510c1f8f7491af7dd0e whose side effect should be to avoid OSRPJContextHolder to be constructed unless explicitly called (at least, that's how it works on Linux). Nevertheless I've just removed the call to init() in the constructor too
