### ISSUE TITLE
Python library not linking to libkml

### ISSUE THREAD

**Issue by adamjstewart** [OSGeo/gdal#1840]
## Expected behavior and actual behavior.

I'm trying to install GDAL with the LIBKML driver. Everything installs fine, but when I import the `osgeo` library, I get an error message:
```console
$ python -c 'import osgeo'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/gdal-3.0.1-yei4fbx2j5hp3vgpmt3z6sp7i2tigrgw/lib/python3.7/site-packages/osgeo/__init__.py", line 21, in <module>
    _gdal = swig_import_helper()
  File "/Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/gdal-3.0.1-yei4fbx2j5hp3vgpmt3z6sp7i2tigrgw/lib/python3.7/site-packages/osgeo/__init__.py", line 17, in swig_import_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)
  File "/Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/python-3.7.4-siqmpxwshahstjuke72arjx545i5mrq7/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/python-3.7.4-siqmpxwshahstjuke72arjx545i5mrq7/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: dlopen(/Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/gdal-3.0.1-yei4fbx2j5hp3vgpmt3z6sp7i2tigrgw/lib/python3.7/site-packages/osgeo/_gdal.cpython-37m-darwin.so, 2): Library not loaded: libkmlbase.1.dylib
  Referenced from: /Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/gdal-3.0.1-yei4fbx2j5hp3vgpmt3z6sp7i2tigrgw/lib/libgdal.26.dylib
  Reason: image not found
```
None of the other driver libraries cause any problems, just libkml.

## Steps to reproduce the problem.

I downloaded and built libkml 1.3.0 from https://github.com/libkml/libkml 

libkml is configured without SWIG/Python bindings. Does it need to be?

Here are the GDAL build logs and build environment:

- [build log](https://github.com/OSGeo/gdal/files/3614465/spack-build-out.txt)
- [build env](https://github.com/OSGeo/gdal/files/3614466/spack-build-env.txt)

## Operating system

macOS 10.14.6, Clang 10.0.1, Python 3.7.4

## GDAL version and provenance

GDAL 3.0.1 installed from source with the [Spack](https://spack.io/) package manager.

**Comment by adamjstewart** [comment]
If I set:
```console
$ export DYLD_LIBRARY_PATH=/Users/Adam/spack/opt/spack/darwin-mojave-x86_64/clang-10.0.1-apple/libkml-1.3.0-smdlkaxjx63mxxnh6txsiuapydfcj35v/lib
```
then the import works. Not sure why RPATH isn't working correctly.

**Comment by rouault** [comment]
> Not sure why RPATH isn't working correctly.

GDAL doesn't add rpath instruction when building the library

**Comment by adamjstewart** [comment]
> GDAL doesn't add rpath instruction when building the library

But Spack does. Either Spack has a bug, or GDAL isn't accepting its RPATH linking. Let me investigate on the Spack side of things.

**Comment by adamjstewart** [comment]
Finally tracked down the problem. There was a bug in the `libkml` installation where RPATHing wasn't working correctly. Applying the `install_name_tool` to the dynamic libraries solved the problem. Sorry for the noise!
