### ISSUE TITLE
Add hint to Docs about how GDAL_calc preserves the data type in operations

### ISSUE THREAD

**Issue by SrNetoChan** [OSGeo/gdal#1848]
## Improvement suggestion

Seems that gdal_calc always preserve the data type of inputs during operations, regardless the output type. this leads to some confusion.
For example, subtracting two Uint16 can will only return positives.

unsigned int A = 1;
unsigned int B = 2;
float C = A - B;

C will be 4294967296

Full explanation here:

https://lists.osgeo.org/pipermail/gdal-dev/2019-September/050766.html

My (actually @rouault ) suggestion is to add a new example/tip to gdal_calc docs:

https://gdal.org/programs/gdal_calc.html

**Comment by SrNetoChan** [comment]
@rouault or anyone, please assign this to me. I will take care of it ASAP

**Comment by Marwe** [comment]
There is an ancient ticket in the old trac (about adding an option to control this behaviour): 
https://trac.osgeo.org/gdal/ticket/4064
