### ISSUE TITLE
fgb_fuzzer: ASSERT: size_ < FLATBUFFERS_MAX_BUFFER_SIZE

### ISSUE THREAD

**Issue by rouault** [OSGeo/gdal#1849]
@bjornharrtell 

Short summary of https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=17312 (that you can't access for now)

The attached reproducer 
[clusterfuzz-testcase-minimized-fgb_fuzzer-5689644401819648.zip](https://github.com/OSGeo/gdal/files/3626579/clusterfuzz-testcase-minimized-fgb_fuzzer-5689644401819648.zip)
 crashes on
```
  | #3 0x7fa7e8d5cc81 in __assert_fail /build/glibc-LK5gWL/glibc-2.23/assert/assert.c:101
-- | --
  | #4 0x603f5a in flatbuffers::Verifier::Verifier(unsigned char const*, unsigned long, unsigned int, unsigned int, bool) gdal/gdal/ogr/ogrsf_frmts/flatgeobuf/flatbuffers/flatbuffers.h:1984:5
  | #5 0x610096 in OGRFlatGeobufLayer::parseFeature(OGRFeature*, OGRGeometry**) gdal/gdal/ogr/ogrsf_frmts/flatgeobuf/ogrflatgeobuflayer.cpp:533:18
  | #6 0x60e76e in OGRFlatGeobufLayer::GetNextFeature() gdal/gdal/ogr/ogrsf_frmts/flatgeobuf/ogrflatgeobuflayer.cpp:482:13
  | #7 0x6331fa in OGR_L_GetNextFeature gdal/gdal/ogr/ogrsf_frmts/generic/ogrlayer.cpp:552:47
  | #8 0x4ea477 in LLVMFuzzerTestOneInput gdal/gdal/fuzzers/ogr_fuzzer.cpp:123:33
```

Easily triggered with:
```
$ ogrinfo clusterfuzz-testcase-minimized-fgb_fuzzer-5689644401819648  -al
ERROR 1: PROJ: internal_proj_create_from_database: crs not found
ERROR 6: toOGRwkbGeometryType: Unknown FlatGeobuf::GeometryType 211
INFO: Open of `clusterfuzz-testcase-minimized-fgb_fuzzer-5689644401819648'
      using driver `FlatGeobuf' successful.

Layer name: 
Geometry: Unknown (any)
Feature Count: 108849084235775
ogrinfo: flatbuffers/flatbuffers.h:1984: flatbuffers::Verifier::Verifier(const uint8_t*, size_t, flatbuffers::uoffset_t, flatbuffers::uoffset_t, bool): Assertion `size_ < FLATBUFFERS_MAX_BUFFER_SIZE' failed.
Abandon (core dumped)
```

As there might be other issues coming in the next days, it might be preferable that I add you in the list of people authorized to look at oss-fuzz issue, to avoid duplicating them here. Could you indicate me an email that is associated with a gmail account (as you need to log through google authentication) ?

**Comment by bjornharrtell** [comment]
Ok! bjorn dot harrtell at gmail dot com.

**Comment by bjornharrtell** [comment]
I'm a bit surprised the verifier asserts causing abandon. Will look into that behavior.

**Comment by rouault** [comment]
> I'm a bit surprised the verifier asserts causing abandon. Will look into that behavior.

yeah, assertion should normally only be used to check for program logic, not validity of data. Nut experience shows that "it should never happen" is quite prone to happen in code dealing with external input.

You've just been added as oss-fuzz watcher for GDAL per https://github.com/google/oss-fuzz/pull/2847. Not sure if it has immediate effect, but at worse you should have access to tickets pointed by https://bugs.chromium.org/p/oss-fuzz/issues/list?can=2&q=gdal by tomorrow

**Comment by bjornharrtell** [comment]
My interpretation is that the max sizes should be checked by the user before using the verifier so that is done with #1865, but apparently this particular fuzz case has been fixed by something else already.
