### ISSUE TITLE
ISIS3: support for Oblique Cylindrical and Near-Sided Perspective

### ISSUE THREAD

**Issue by rouault** [OSGeo/gdal#1856]
the ISIS3 format has support for two projection methods  Oblique Cylindrical (implemented per   https://github.com/USGS-Astrogeology/ISIS3/blob/3.8.0/isis/src/base/objs/ObliqueCylindrical/ObliqueCylindrical.cpp ) and Near-Sided Perspective (implemented per  https://github.com/USGS-Astrogeology/ISIS3/blob/3.8.0/isis/src/base/objs/PointPerspective/PointPerspective.cpp ). Those projection methods are currently not handled by the GDAL ISIS3 driver. Those projection methods exists in the PROJ library, but with slightly different parameters. This tasks consist in identifying a mapping between the parameter of the ISIS3 projections and the ones available in PROJ, adding the needed parameters to the PROJ methods if needed, and enhancing the GDAL ISIS3 driver on the read and write side to map between the ISIS3 format and the GDAL CRS objects using those projection methods

**Comment by thareUSGS** [comment]
After looking into "Point Perspective" more this week, I am becoming more confident that this is the same as Near-sided perspective (without any additional parameters): https://proj.org/operations/projections/nsper.html  

Although I haven't actually matched the equations. But, I assume for testing in GDAL, this will need to be exposed for GDAL (if it is not already)?

**Comment by rouault** [comment]
>  But, I assume for testing in GDAL, this will need to be exposed for GDAL (if it is not already)?

Yes, a method in OGRSpatialReference should be added for that, and the corresponding one in PROJ.

Do you have test datasets with those 2 methods, and possibly with values of a few projected points and their corresponding lon, lat so that we can check if the mapping is correct ?

**Comment by thareUSGS** [comment]
I have samples, but let me quickly add some sampling pixel, lat, lon text files for each. BTW, Once Oblique Cylindrical is implemented, the PDS3 driver will need a quick update. It currently incorrectly maps this to "Swiss_Oblique_Cylindrical".  ISIS3 correctly ignores that projection (I assume PDS4 driver will also need to be touched).

**Comment by thareUSGS** [comment]
A little large, but here are some smaller files in there too: (temporary download location): ftp://ftpext.usgs.gov/pub/wr/az/flagstaff/thare/forGDAL/gdal_ticket1856_testProjections.zip

**Comment by rouault** [comment]
All subtasks for this ticket now completed
