### ISSUE TITLE
Adding Mongodb support is a real pain. Are these steps still valid?

### ISSUE THREAD

**Issue by donnyv** [OSGeo/gdal#1859]
Adding Mongodb support is not very straight forward. Before I dive into this article. I want to know if these instructions are still valid.
https://github.com/mongogis/mongodb-gdal-driver

Is there any hope Mongodb support could be added to the OSGeo4W setup app?

**Comment by rouault** [comment]
There are actually 2 MongoDB drivers in mainline GDAL depending on which version of the mongodb connector library you use : https://gdal.org/drivers/vector/mongodb.html and https://gdal.org/drivers/vector/mongodbv3.html

Adding support or them in OSGeo4W is something not directly in the scope of GDAL, but would be worth a ticket to https://trac.osgeo.org/osgeo4w/
