### ISSUE TITLE
FlatGeobuf overrides given filename in ogr2ogr

### ISSUE THREAD

**Issue by AsgerPetersen** [OSGeo/gdal#1862]
## Expected behavior and actual behavior.

Using
```bash
ogr2ogr outfile.fgb db.gpkg schema.layer
```
I would expect to get a file named `outfile.fgb`. Instead I get a file named `schema.layer.fgb`.

## Operating system

Tested on Windows

## GDAL version and provenance

Using nightly build (`GDAL 3.1.0dev, released 2019/99/99`) from OSGEO4W as of 2019-09-19

**Comment by mloskot** [comment]
> Using nightly build from OSGEO4W as of 2019-09-19

`ogr2ogr --version` as per https://gdal.org/programs/vector_common_options.html

**Comment by bjornharrtell** [comment]
I willingly admit I've had a hard time understanding this part of the driver code (which is mostly based on some of the others).

**Comment by mloskot** [comment]
TL:TR: AFAIU, current implementation always ignores filename of destination, just uses it to obtain destination directory, then always calculates output file based on layer name (and the obtained directory).

I think, this comment is incorrect vs the current implementation that follows:

https://github.com/OSGeo/gdal/blob/62df9534bcb26ad7ba330808dd5aca345dccd75f/gdal/ogr/ogrsf_frmts/flatgeobuf/ogrflatgeobufdataset.cpp#L237

So, for `outfile.fgb` this is true:

https://github.com/OSGeo/gdal/blob/62df9534bcb26ad7ba330808dd5aca345dccd75f/gdal/ogr/ogrsf_frmts/flatgeobuf/ogrflatgeobufdataset.cpp#L240

and the `outfile.fgb`'s directory is obtained (and `pszName` is not used anymore)

https://github.com/OSGeo/gdal/blob/62df9534bcb26ad7ba330808dd5aca345dccd75f/gdal/ogr/ogrsf_frmts/flatgeobuf/ogrflatgeobufdataset.cpp#L242

then the directory is passed as destination dataset

https://github.com/OSGeo/gdal/blob/62df9534bcb26ad7ba330808dd5aca345dccd75f/gdal/ogr/ogrsf_frmts/flatgeobuf/ogrflatgeobufdataset.cpp#L270

which is captured as `OGRFlatGeobufDataset::m_osName` and used to **compose** output filename:

https://github.com/OSGeo/gdal/blob/62df9534bcb26ad7ba330808dd5aca345dccd75f/gdal/ogr/ogrsf_frmts/flatgeobuf/ogrflatgeobufdataset.cpp#L329
