### ISSUE TITLE
https://gdal.org/python/ 404 error

### ISSUE THREAD

**Issue by davidkwast** [OSGeo/gdal#1867]
Hi. 10 minutes ago the URL "https://gdal.org/python/index.html" became "offline".

**Comment by rouault** [comment]
Perhaps a temporary issue or an issue on your side ? Works for me right now

**Comment by davidkwast** [comment]
@rouault thanks

It went back online now. Maybe it was a temporary downtime while it was being updated.

https://gdal.org/python/index.html
