### ISSUE TITLE
./configure: using --with-grass=path breaks --with-crypto

### ISSUE THREAD

**Issue by derabbink** [OSGeo/gdal#1871]
## Expected behavior and actual behavior.
I am attempting to `./configure` gdal-3.0.1 with the following two arguments:
* `--with-crypto`
* `--with-grass=path`

Using _only_ the `--with-grass=path` argument works as expected; `libcrypto` is found on my system. Also adding `--with-grass=path` to the argument list will cause `--with-crypto` to stop working.

If these two arguments are in fact mutually exclusive, the `./configure` script should warn the user about it, instead of silently/automatically dropping the `--with-crypto` argument.

I'm not sure if this is related to #1432

## Steps to reproduce the problem.
1. Install PROJ (in my example: at `/usr/local/proj`)  
as this is a hard requirement for `./configure` to complete successfully
2. download gdal-3.0.1 sources  
from the list of [Current Releases][gdal-download]
3. install `libcrypto`  
a.k.a. `libssl-dev`
4. run `./configure` with all necessary arguments (see below)

```sh
sudo apt-get install -y libssl-dev grass-dev

cd path/to/gdal-3.0.1/
./configure \
  --with-proj=/usr/local/proj \
  --with-crypto \
  --with-grass=/usr/lib/grass76
```
```
[...]
GDAL is now configured for x86_64-pc-linux-gnu

  Installation directory:    /usr/local
  C compiler:                gcc -DHAVE_AVX_AT_COMPILE_TIME -DHAVE_SSSE3_AT_COMPILE_TIME -DHAVE_SSE_AT_COMPILE_TIME -g -O2
  C++ compiler:              g++ -DHAVE_AVX_AT_COMPILE_TIME -DHAVE_SSSE3_AT_COMPILE_TIME -DHAVE_SSE_AT_COMPILE_TIME -g -O2
  C++14 support:             no

  LIBTOOL support:           yes

[...]

  crypto/openssl support:    no
  GRASS support:             grass70+
[...]
```

Please note the **`crypto/openssl support:    no`** in the summary output of `./configure`.  
If you _remove_ the  `--with-grass=/usr/lib/grass76` argument from the command, you'll find **`crypto/openssl support:    yes`** in the output

## Operating system

Debian Buster (10)

## GDAL version and provenance

3.0.1 (latest stable)

[gdal-download]: https://gdal.org/download.html#current-releases

**Comment by derabbink** [comment]
I also noticed the the use of `--with-grass=path` breaks CFITSIO detection.  
I haven't tested all combinations of `--with-grass=path` and other arguments, but I suspect specifying an additional path to scan is what breaks the rest of the `./configure` script

**Comment by rouault** [comment]
I believe your problem is more fundamental than just crypto not being detected. With which version of GDAL is GRASS compiled against ? I suspect that it is the version of GDAL that comes with Buster, and not the one you are building. So there's a strong risk that your resulting GDAL build will blow up when using GRASS.
So your workflow shoud be similar to what distributions do:
- build GDAL 3.0.1 without GRASS support
- build GRASS against this GDAL 3.0.1
- build the GDAL-GRASS plugin (see frmts/grass/pkg/README or what the distribution does in its build scripts for the gdal-grass plugin)

**Comment by derabbink** [comment]
you're right; I'm using the debian buster-provided grass build. Here's the dependency, chain, and it leads to gdal-2.4:
[`grass-dev` 7.6.0-1](https://packages.debian.org/buster/grass-dev)  
[`grass-core` 7.6.0-1](https://packages.debian.org/buster/grass-core)  
[`libgdal20` 2.4.0+dfsg-1](https://packages.debian.org/buster/libgdal20)

I'll look into your suggestion. Thanks you for your support.

Since there is indeed a version mismatch, I'll close this report.

**Comment by derabbink** [comment]
I'm now starting to think that there is something wrong with the `./configure` script and how it handles library paths in general.
I now noticed that adding `--with-dds` breaks the use of `--with-proj=path`

If I run `./configure --with-proj=/usr/local/proj --with-dds`, I end up with the following error output, and the script does not complete successfully.  
If I _omit_ `--with-dds`, it completes successfully.

```
checking how to link PROJ library... link statically.
checking for proj_create in -lproj... no
checking for pj_init in -lproj... no
checking for pj_init in -lproj... no
checking for pj_init in -lproj... no
checking for pj_init in -lproj... no
checking for pj_init in -lproj... no
configure: error: cannot find proj
```

Any guidance would be appreciated

**Comment by rouault** [comment]
closing as autoconf has been removed from master and replaced by cmake. furthermore the GRASS driver has been moved to the https://github.com/OSGeo/gdal-grass repository
