### ISSUE TITLE
forceToMultiLineString fails when geometry collection contains 3D or measured linestring (fix included)

### ISSUE THREAD

**Issue by igorthy** [OSGeo/gdal#1873]
Hi, 

gdal version 3.0.1

I noticed that method `OGRGeometryFactory::forceToMultiLineString` (ogrgeometryfactory.cpp) doesn't handle correctly the case of geometry collection containing 3D or measured LineString geometry.
In my scenario I was writing to shape file a geometry collection with wkbLineString25D geometries in it. The shape driver failed.

There is a loop:
`        for( auto&& poMember: poGC )
        {
            if(poMember->getGeometryType() != wkbLineString )
            {
                return poGeom;
            }
        }
`
The problem here is the absence of `wkbFlatten` wrapping `getGeometryType` call.
At least this is how it handled in other methods such as `OGRGeometryFactory::forceToMultiPoint`

**Comment by rouault** [comment]
You're at 90% of doing a pull request. Do you mind doing one with that fix ?

**Comment by jratike80** [comment]
What if input has several linestrings, some of type XY and some of XYZ(M)? There may arise some problems with the validity of collections with mixed dimensionality. For example this one is not valid for PostGIS (LWGEOM)

```
select ST_IsValid(ST_GeomFromText('MULTILINESTRING (( 3 3 3, 4 4 4 ), ( 0 0, 2 2 ))'));

ERROR:  Dimensions mismatch in lwcollection SQL state: XX000
```
Spatialite 5.0 beta considers this geometry also as invalid. JTS Test Builder with JTS version 1.14 seems to accept the geometry as valid but I am not sure if my test was reliable and if JTS just quietly dropped the Z coordinates of the first member.  However, OpenJUMP that is using JTS 1.14 as well returns XY and XYZ mix with Make geometries valid so it obviously considers that everything is OK.

I wonder if it would still be safest to cast all members of the new multilinestring into max dimensionality among all the source members. For some drivers this is probably mandatory.

I guess that having mixed dimension features on data is not so common but they may appear when merging layers or picking features from different tables, possibly through some functions.

**Comment by igorthy** [comment]
@rouault sure, I will

@jratike80 I my case geometry collection contained solely LineString25D objects.
IMHO, the fix I'm proposing just follows the same collection filtering rule as in other places like OGRGeometryFactory::forceToMultiPoint.
So, having all places doing it wrong at least more consistent :)

**Comment by rouault** [comment]
@igorthy Gentle reminder that we're waiting for your pull request :-) A new test case in autotest/ogr/ogr_geom.py would be welcome

**Comment by igorthy** [comment]
I would appreciate if someone else could do the pull request.
I don't care about credits and such...
I'm not very familiar working with git..all that commands... pull, push, fork... I need to learn this.
Thanks
