### ISSUE TITLE
OGRCoordinateTransformation leaks memory even when calling OGRCoordinateTransformation::DestroyCT

### ISSUE THREAD

**Issue by rconde01** [OSGeo/gdal#1880]
## Expected behavior and actual behavior.
In our code we call `OGRCreateCoordinateTransformation` and then later `OGRCoordinateTransformation::DestroyCT` on the result. Using the _CrtSetXXXX functions, we are seeing a memory leak. If we actually do a transform, we see additional very large memory leak (~4mb)...which is probably correlated to the size of the transformed data. There should be no memory leaks. 

## Steps to reproduce the problem.

See above. I can try to put together an example if necessary.

## Operating system

Windows

## GDAL version and provenance

Gdal 3.0.1 from the website.

## Workaround
If you call pj_deallocate_grids, it fixes the leak. Unfortunately, the function is deprecated and doesn't appear to have a replacement.

**Comment by rouault** [comment]
Those are not memory leaks, but global cached memory. The TLS PROJ context has also a cache

proj_cleanup() has been added in PROJ 6.2: https://github.com/OSGeo/PROJ/commit/96ac0f210b6dd3fdb499115d83bc13ff7739cd60#diff-c84c3443026615149dd2c6eebf0b17e3

**Comment by rconde01** [comment]
ok - that gives me a path forward thx
