### ISSUE TITLE
Layer.GetSpatialRef() return null on shapefile with PRJ file

### ISSUE THREAD

**Issue by aharondavid** [OSGeo/gdal#1881]
## Expected behavior and actual behavior.
Layer.GetSpatialRef() return null on shapefile with PRJ file that contained the following valid WKT:

`COMPD_CS["OSGB 1936 / British National Grid + odn height",PROJCS["OSGB 1936 / British National Grid",GEOGCS["OSGB 1936",DATUM["OSGB_1936",SPHEROID["Airy 1830",6377563.396,299.3249646,AUTHORITY["EPSG","7001"]],TOWGS84[446.448,-125.157,542.06,0.15,0.247,0.842,-20.489],AUTHORITY["EPSG","6277"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4277"]],PROJECTION["Transverse_Mercator"],PARAMETER["latitude_of_origin",49],PARAMETER["central_meridian",-2],PARAMETER["scale_factor",0.9996012717],PARAMETER["false_easting",400000],PARAMETER["false_northing",-100000],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AXIS["Easting",EAST],AXIS["Northing",NORTH],AUTHORITY["EPSG","27700"]],VERT_CS["ODN height",VERT_DATUM["Ordnance Datum Newlyn",2005,AUTHORITY["EPSG","5101"]],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AXIS["Up",UP],AUTHORITY["EPSG","5701"]]]`

## Operating system
Windows 10

## GDAL version and provenance
GDAL 2.2.2
GDAL 3

**Comment by rouault** [comment]
Was this PRJ file actually generated by an ESRI tool ?

**Comment by aharondavid** [comment]
Sorry, I don't know

**Comment by aharondavid** [comment]
@rouault , I saw your fix, Thank you!

**Comment by azrinsani** [comment]
Hi, how did you fix this?
