### ISSUE TITLE
Read Ellipse in DWG ERROR

### ISSUE THREAD

**Issue by thishzw** [OSGeo/gdal#1886]
## Expected behavior and actual behavior.

When I read Ellipse in DWG,I found that there were only two points in this Geometry.And We can't use only 2 points to get an  Ellipse.
something helpful:
I thought  the reason of this problem was because the wrong value of endAngle.the value of endAngle should be same of the startAngle but it was 0;
\ogr\ogrsf_frmts\cad\ogrcadlayer.cpp  line 711

## Operating system

Windows 10

## GDAL version and provenance

gdal 2.4.2 based on libopencad

**Comment by rouault** [comment]
CC @BishopGIS

**Comment by BishopGIS** [comment]
@thishzw can you attach sample DWG file with ellipse?

**Comment by thishzw** [comment]
[Drawing1.zip](https://github.com/OSGeo/gdal/files/3666180/Drawing1.zip)
There are only one Ellipse in this file.
