### ISSUE TITLE
where can i find the list of built-in drivers?

### ISSUE THREAD

**Issue by haies** [OSGeo/gdal#1892]
In[ docker readme](https://github.com/OSGeo/gdal/tree/release/3.0/gdal/docker),the vector divers list is discripted as following:
`Vector drivers: all built-in + XML based ones + SQLite-based ones + network-based ones + PostgreSQL`
but how can if found built-in drivers list?
Or does it contians both FileGDB and OpenFileGDB?

**Comment by rouault** [comment]
Run `gdalinfo --formats` and `ogrinfo --formats` from the Docker images. They contain OpenFileGDB but not FileGDB as it requires a proprietary bit

**Comment by mloskot** [comment]
@haies FYI, questions belong to https://lists.osgeo.org/pipermail/gdal-dev/ and not bug tracker on GitHUb

**Comment by haies** [comment]
@rouault  thanks a lot
