### ISSUE TITLE
Makefile.vc and nmake.opt don't support POSTFIX in debug configuration

### ISSUE THREAD

**Issue by rafamolopez** [OSGeo/gdal#1901]
Hello,

I was wondering if it would be possible to adapt nmake.opt and makefile.vc files to support debug configuration. A good way would be, adding postfix support and, thus, you can define/change it, like $(POSTFIX)='_d' and this postfix would be applied to GDAL_DLL, GDAL_LIB, GDAL_PDB, etc.
Actual behaviour is the same in both release and debug; same names in all files either release or debug mode.

Summarizing:
## Expected behaviour and actual behaviour.

I expected to have different names either release or debug configurations in all files built by nmake (using nmake.opt and makefile.vc).
It isn't possible at current version.

## Steps to reproduce the problem.

See nmake.opt and makefile.vc files.

## Operating system

Windows 10

## GDAL version and provenance

The 3.0.1 version from tag: https://github.com/OSGeo/gdal/releases/tag/v3.0.1

**Comment by rouault** [comment]
Sounds reasonable. Willing to contribute a pull request to implement that

**Comment by mloskot** [comment]
@rafamolopez This idea seems like a perfect first issue to contribute implementation for via PR. Would you be willing to do it?

**Comment by rouault** [comment]
> @rouault is doing it or question mark is missing from [#1901 (comment)](https://github.com/OSGeo/gdal/issues/1901#issuecomment-537208652) ?

Question mark was missing. I didn't volunteer for doing it

**Comment by rafamolopez** [comment]
@rouault @mloskot, OK, I am willing to contribute with the implementation of that.
