### ISSUE TITLE
Column header of .ods file not recognised

### ISSUE THREAD

**Issue by anothatuber** [OSGeo/gdal#1902]
## Expected behavior and actual behavior.

Preface:
I know I'm abusing ogr2ogr as a ods2csv converter also for non geodata but think the following is still a bug and hope it will be fixed.

When my input file doesn't contain longitude and latitude data, the column headers will be output as row data and the csv will contain "Field1,Field2" as header row. This is also valid if -oo OGR_ODS_HEADERS=FORCE is used for ogr2ogr. As soon as lat/lon columns are present, the real column names are output.

I expect ogr2ogr to always use the first row to be used as column names or at least when OGR_ODS_HEADERS=FORCE is given.

## Steps to reproduce the problem.

ogr2ogr -f CSV out.csv in.ods

## Operating system

Current Linux nightly docker image.

## GDAL version and provenance
GDAL 2.4.0 & GDAL 3.1.0dev

**Comment by rouault** [comment]
Please provide a sample dataset showing that behaviour

**Comment by rouault** [comment]
Closing due to lack of feedback
