### ISSUE TITLE
open tif file,GetProjectionRef return empty string

### ISSUE THREAD

**Issue by NodeGIS** [OSGeo/gdal#1905]
## Expected behavior and actual behavior.

open a tif image file,in version 300, function ’GetProjectionRef’ return empty string and GetSpatialRef return null;
in version 204, funtion GetProjectionRef can work fine!

## Steps to reproduce the problem.
```
int main()
{
	GDALAllRegister();  
	GDALDataset* dataset = static_cast<GDALDataset*>(GDALOpen("D:\\demo.tif", GA_ReadOnly)); 
	if (!dataset)
	{		
		return EXIT_FAILURE;	
	}	
	const char* pszProj = dataset->GetProjectionRef(); 
	//const OGRSpatialReference* ref  = dataset->GetSpatialRef();
	GDALClose(dataset); 
    std::cout << "Hello World!\n";
}
```

## Operating system

win10

## GDAL version and provenance

300

**Comment by rouault** [comment]
Make sure that the PROJ_LIB environment variable points to the directory where proj.db is located

**Comment by NodeGIS** [comment]
i set it by c++ code  as here:
_putenv_s("PROJ_LIB", "xxxxx"))

set by C# code as here:
Environment.SetEnvironmentVariable("PROJ_LIB", "xxxxxx");

xxxx is my proj.db location.

but it can not work normal, why？

i read proj code on github,  it get the value by getenv, i also get the  value by getenv.  i don't understand this.

but i set in “this computer-environmentvariable” is ok.

**Comment by NodeGIS** [comment]
@rouault 
i set it by c++ code as here:
_putenv_s("PROJ_LIB", "xxxxx"))

set by C# code as here:
Environment.SetEnvironmentVariable("PROJ_LIB", "xxxxxx");

xxxx is my proj.db location.

but it can not work normal, why？

i read proj code on github, it get the value by getenv, i also can get the value by getenv. i don't understand this.

but i set in “this computer-environmentvariable” is ok.

**Comment by rouault** [comment]
There's a known issue with C# and Environment.SetEnvironmentVariable(). I'm pretty sure there is a ticket about that. Yes as computer environement variable (or in a .bat before starting your C# code) is the way to make it work currently

**Comment by NodeGIS** [comment]
@rouault not only C#,  C api also not work:

_putenv_s("PROJ_LIB", "xxxxx"))

**Comment by rouault** [comment]
I think you're running into https://stackoverflow.com/a/5153586
Basically Windows sucks regarding setting environment variables once a process has started...
I'm just thinking that you might actually use the OSRSetPROJSearchPaths() function (for your C++ stuff) instead of putenv/setenv

**Comment by idanmiara** [comment]
> Make sure that the PROJ_LIB environment variable points to the directory where proj.db is located

I'm having the same issue unless I set the PROJ_LIB environment.
I'm trying to avoid setting this var and use the default.
I have gdal*.dll and proj*.dll in the same dir, and I've tried to put the proj data under .\data\proj and .\share\proj but it doesn't pick that up. What's the default path and relative to what?
Thanks.
