### ISSUE TITLE
[feature request] transformWithOptions to ogr python API

### ISSUE THREAD

**Issue by snowman2** [OSGeo/gdal#1911]
Currently there is:

```python
srs_from = osr.SpatialReference()
srs_from.ImportFromWkt(...)

srs_to = osr.SpatialReference()
srs_to.ImportFromEPSG(4326)

transformer = osr.CoordinateTransformation(srs_from, srs_to)

geom.Transform(transformer)
```

But, it would be nice to have something like `geom.TransformWithOptions` exposed or add kwargs to `geom.Transform` for `DATELINEOFFSET` or `WRAPDATELINE` in the python API.

Are there plans for this?

**Comment by snowman2** [comment]
Or even better, does it already exist and I just didn't find it?

**Comment by palmerj** [comment]
Any chance on this one? Would be nice to have this in the python API to deal with datelines :)

**Comment by rouault** [comment]
This project gladly accepts (reasonable) pull requests ;-)

**Comment by palmerj** [comment]
OK ;)

Do you think it makes sense to add this API as a new `transformWithOptions` method within python or better to overload?

**Comment by rouault** [comment]
I guess a Transform(options=...) would be more pythonic.

But anyway, at the C API level, you'll need to add a 
```
OGRErr CPL_DLL OGR_G_TransformWithOptions( OGRGeometryH, OGRCoordinateTransformationH, CSLConstList papszOptions );
```
and the existing SWIG Geometry::Transform() method can then map to it

**Comment by snowman2** [comment]
Thanks!

**Comment by palmerj** [comment]
Yes many thanks Even!
