### ISSUE TITLE
.kml to .xlsx conversion

### ISSUE THREAD

**Issue by wuyyururaviteja** [OSGeo/gdal#1913]
Hello GDAL Team,

We would like to use ogr2ogr file format conversion in our product using java bindings. I have read in gdal website that for xlsx conversion there is no geometry support but may use ogr vrt capabilities for that.
can you please elaborate the procedure i need to follow so i can convert .kml files directly to .xlsx format which has geometry included.
Note: i have already built gdal with expat support so upon trying to convert from .kml to .xlsx iam getting file which misses Geometry Column.

Thanks in advance.

**Comment by rouault** [comment]
Quoting issue template: """Questions should go to the gdal-dev mailing list (https://lists.osgeo.org/mailman/listinfo/gdal-dev)
or other support forums. GitHub issues are for bug reports and suggestions
for new features."""

**Comment by mloskot** [comment]
@wuyyururaviteja When you hit "New issue" button, first you were indeed displayed with this clear instruction

```
<!--
Questions should go to the gdal-dev mailing list (https://lists.osgeo.org/mailman/listinfo/gdal-dev)
or other support forums. GitHub issues are for bug reports and suggestions
for new features.
...
```

Apparently, you ignored that with cold blood. Please, next time, do not!
