### ISSUE TITLE
Gdal's python scripts are not working on some docker images

### ISSUE THREAD

**Issue by RemiSahl** [OSGeo/gdal#1915]
## Expected behavior and actual behavior.

When trying to run python programs from recent docker images (gdal_calc.py , gdal_merge.py), the command fails as it can't find python executable.

## Steps to reproduce the problem.

```
docker run -it osgeo/gdal:alpine-normal-latest gdal_calc.py
env: can't execute 'python': No such file or directory
```
## GDAL version and provenance

Latest gdal 3.1 docker images

## Possible solution

Add a symlink from python to python3 in dockerfile: 
```
ln -s /usr/bin/python3.7 /usr/bin/python
```
https://github.com/OSGeo/gdal/blob/master/gdal/docker/alpine-normal/Dockerfile#L379

**Comment by jphilippou27** [comment]
I'm also experiencing the same issue with the latest version of the docker image (pulled this AM)
<img width="865" alt="Screen Shot 2020-01-14 at 12 16 24 PM" src="https://user-images.githubusercontent.com/6182313/72366263-e82ee280-36c7-11ea-8a21-06e9f07f0b35.png">

I tried explicitly calling python3 but that didn't work

**Comment by jphilippou27** [comment]
Same message for the osgeo/gdal:ubuntu-full-latest image which seems like it should have python

**Comment by rouault** [comment]
For  osgeo/gdal:ubuntu-full-latest, you need for now to explictly use `python3 /usr/bin/gdal_polygonize.py`

**Comment by jphilippou27** [comment]
Thanks! works perfectly

**Comment by Nitaym** [comment]
Shouldn't scripts like gdal2tiles should update their shebang line from ``` #!/usr/bin/env python``` to
``` #!/usr/bin/env python3```?

**Comment by rouault** [comment]
See https://github.com/OSGeo/gdal/pull/2175
