### ISSUE TITLE
Viewshed adjustments

### ISSUE THREAD

**Issue by rouault** [OSGeo/gdal#1917]
Outstanding issues:

- [x]  The `-3d` option doesn't seem to be hooked up yet
- [ ]  No tests of the algorithm and utility provided 
- [x]  Documentation of the algorithm to improve

CC @hobu

**Comment by rouault** [comment]
and CC @szekerest

**Comment by szekerest** [comment]
The -3d option is not applicable here. It was probably taken over from the gdal_contour parameter set.
