### ISSUE TITLE
oss-fuzz fgb issues

### ISSUE THREAD

**Issue by rouault** [OSGeo/gdal#1918]
A few ones: https://bugs.chromium.org/p/oss-fuzz/issues/list?q=gdal%20fgb_fuzzer&can=2
CC @bjornharrtell 

Regarding https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=17680, I think one way to address it would be to check the file size before we try to allocate let's say more than 100 MB

**Comment by bjornharrtell** [comment]
I'm taking a stab at them now.

**Comment by bjornharrtell** [comment]
While I could come up with some reasonable heruistic if the file size is known, I feel unsure about if I always can expect to get the actual size - if the source is a non seekable stream and forward read only, I cannot get the size before hand? Regardless, I'm also unsure if I should use and trust VSIStatL or do a seek with SEEK_END.

**Comment by rouault** [comment]
Good point about non seekable streams such as /vsistdin/. As far as I know this is the only one you might explicitly exclude from such a test, and using VSIStatL() should be OK on others.
... That said, on a quick test, it seems that the driver cannot currently deal with /vsistdin/ :
```
$ cat with_flag.fgb  | ogrinfo /vsistdin/ -al -q

Layer name: DR_LINKKI_K
OGRFeature(DR_LINKKI_K):0
  LINK_ID (String) = 2461127
  LINK_MMLID (String) = 523114076
  SEGM_ID (String) = 318_13620
  KUNTAKOODI (Integer) = 318
  HALLINN_LK (Integer) = 1
  TOIMINN_LK (Integer) = 4
  LINKKITYYP (Integer) = 21
  SILTA_ALIK (Integer) = 0
  AJOSUUNTA (Integer) = 2
  MUOKKAUSPV (String) = 16.12.2016 14:34:56
  SIJ_TARK (Integer64) = 10000
  KOR_TARK (Integer64) = 201
  ALKU_PAALU (Real) = 0
  LOPP_PAALU (Real) = 662.164
  GEOM_FLIP (Integer) = 0
  GEOM_LAHDE (Integer) = 1
  MTK_TIE_LK (String) = 12151
  LINESTRING ZM (159664.518 6663049.355 -0.404 0,159002.381 6663055.347 -0.404 662.164099999995)

ERROR 6: backward Seek() unsupported on /vsistdin above first MB
ERROR 1: Unexpected I/O failure
ERROR 1: Fatal error querying spatial index
```
/vsistdin/ caches the first MB (for the purpose of driver identification) of the file, but after that no longer allows backward seeks

**Comment by bjornharrtell** [comment]
Good find, I'd like to get that fixed (and reproduced with a test case of course).

Assuming I can fix so that it does work, about excluding this case from the fuzzer I'm a bit clueless at this point.

**Comment by rouault** [comment]
> about excluding this case from the fuzzer I'm a bit clueless at this point.

Basically, something like the following (pseudo-code)
```
            if( featureOffsetsSize > 100_MB && !STARTS_WITH(filename, "/vsistdin/") )
            {
                  VSIStatL sStatBuf;
                  if( VSIStatL(filename, &sStatBuf) == 0 && sStatBuf.st_size < featureOffsetsSize )
                  {
                        // error out
                  }
            }
            m_featureOffsets = static_cast<uint64_t *>(VSI_MALLOC_VERBOSE(featureOffsetsSize));
            if (!m_featureOffsets)
                return CPLErrorMemoryAllocation();
```

**Comment by bjornharrtell** [comment]
Is there no feature flag or similar that can determine that a VSI source is forward only?

**Comment by rouault** [comment]
> Is there no feature flag or similar that can determine that a VSI source is forward only?

Not currently. A virtual method for that could potentially be added in VSIFilesystemHandler

**Comment by bjornharrtell** [comment]
Currently no fgb fuzzer issues so I think this could be closed.

**Comment by rouault** [comment]
agreed. closing
