### ISSUE TITLE
Snow Leopard, GDAL, DWG files with libOpenCAD : issue found

### ISSUE THREAD

**Issue by laurentang001** [OSGeo/gdal#1920]
OBJECT: Reopening the MacTypes.h error with Snow Leopard for GDAL. Additional comments.
Keywords : GDAL, v. 2.1.4, v. 2.2.4 and next, ogr, libopencad, r222.cpp, MacTypes.h, Mac OS X Snow Leopard.

Hi !

The current GDAL I use is the 2.1.4 version. Correctly compiled, installed, and run. Recently, I downloaded the 2.4.2 and 3.0.1, and I just ended to test the compilation and installation of the 2.4.2 version. As I had previouly with the 2.2.4 and 2.3.3 versions, I had the MacTypes.h error : not found. Please kindly acknowledge the following details about this issue.

In fact, athough make run, make install failed. This is the r2000.cpp that issues the MacTypes.h error (line 57). Running Spotlight, I found where was this C++ file, namely in :

ogr/ogrsf_frmts/cad/libopencad/dwg,

in the the GDAL source folder. r2000.cpp is part of libopencad, an opensource under the X/MIT license (URL: http://sandyre.github.io/libopencad/ ).

In fact, MacTypes.h is provided with Snow Leopard or, more precisely, very probably with XCode. We can find it in :

/Developer/Headers/FlatCarbon

However, MacTypes.h consists in a single line, a #include line in fact, pointing to CoreServices.h (part of a System framework). So, <Mactypes.h> in r2000.cpp (NB The only GDAL file where we find this include insertion) doesn't find it. Consequenetly, some fixing tests could be made :

1: include export PATH=$PATH:/Developer/Headers/FlatCarbon. But I tried some hours ago inside a shell script, it fails ;
2: give to configure : CPPFLAGS="-I/Developer/Headers/FlatCarbon" ;
3: Suppress, or comment the lines including #include<MacTypes.h> in r2000.cpp.

As Step 1 failed, I will test very soon Steps 2 & 3.

Please kindly note that libopencad is not part of the 2.1.4 version of GDAL, that works very pretty good in fact. Besides, <Mactypes.h>, that is likely never mentioned in GDAL 2.1.4, maybe is not mandatory. I suggest to test a modified version of libopencad without referring to MacTypes.h. When coding, use the KISS developement method : Keep It Simple... (NB This is why using Windows source code for UNIX is often too difficult and to many time waste ..). Furthermore, libopencad seems have to be developed many years ago, so including the MacTypes.h reference, an include file existing since at least 1985 (URL: https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=2ahUKEwj1gpSz2ILlAhU0A2MBHYnlANMQFjAAegQIARAB&url=https%3A%2F%2Fopensource.apple.com%2Fsource%2FCarbonHeaders%2FCarbonHeaders-18.1%2FMacTypes.h&usg=AOvVaw1y5lUYoeo7EMng9_bMpsIA ).

As at last but not least remark, GDAL v. 2.1.4 and before have not libopencad.

So, I just proved that this is libopencad that is fairly "ill-conditioned".

Eventually, I recommend to modify libopencad included in GDAL to suppress the MacTypes.h reference.

Kind regards,
MacTypes.zip

Laurent D.
[MacTypes.zip](https://github.com/OSGeo/gdal/files/3707591/MacTypes.zip)
[MacTypes.zip](https://github.com/OSGeo/gdal/files/3707593/MacTypes.zip)

**Comment by rouault** [comment]
CC @BishopGIS

**Comment by BishopGIS** [comment]
Just quick tested to build on Mac OS X 10.14 removed this include - build success.
As quick fix you can remove `#include <MacTypes.h>`

**Comment by laurentang001** [comment]
Thank you very much for your reply BishopGIS.

However, I did it, and it failed. However, I will test it again very soon.
Besides, please kindly note that the OS X version I still have is : Snow Leopard (10.6.8).

Kind regards,

Laurent D.

**Comment by BishopGIS** [comment]
@laurentang001 is this clean build? 
Can you attach error log?  

Also, it seems to me that GCC 4.2.1 not compatible with C++11 (https://gcc.gnu.org/projects/cxx-status.html#cxx11). The C++11 is mandatory for GDAL.

**Comment by laurentang001** [comment]
Hi BishopGIS : 

Thank you very much for your kind reply.

Please note that I usually never use GCC 4.2.1, provided with XCode (4.2.6 ; I have not the version in mind. Just to be verified). I use it when I canot do otherwise.

Currently, I use GCC 8.3.0 (NB I failed to compiled GCC 9.2.0), or LLVM/CLANG 3.8.1 I always first use before GCC 8.3.0. 

Nevertheless, I will send you the log files next as soon as I still have tested GDAL, last version.

Eventually, please also note that I failed to compile libopencad ( URL: http://sandyre.github.io/libopencad/ ) in its own.

Kind regards,

Laurent D.

**Comment by laurentang001** [comment]
Hi !

Please find herein my preliminary results according to compiling and installing GDAL v. 2.4.2 and further v. 3.0.1 (not reviewed today).

Please may I recall that I work under Mac OS X Snow Leopard (v. 10.6.8) and a GNU compiler I built and installed successfully GCC v. 8.3.0.

So, let's start !

1:
First, I erased the untarred GDAL v. 2.4.2, and untar it again. Then I run configure, make etc.  I have the MacTypes.h error with the r2000.cpp unmodified file. All the log files (sometimes, with the source files, modified or not, are included too) in the zip file are :
- config(some text).log : the log file issued by configure ;
- my-configure(some text).log file : a log file with what is displayed on the screen by configure ;
- my-make(some text).log  file : a log file with what is displayed on the screen by make ;
- my-install(some text).log file : a log file with what is displayed on the screen by make install.

You will find enclosed the 1st zip file with nothing changed : 1 FAILED-OSX_1068-GCC_830-r2000_cpp_mactypes_h_error.zip

2:
Then, I removed the MacTypes.h line from r2000.cpp, and I run configure and make again. Unfortunately, although taht libopencad seems to pass, another error appears : with ogrsqlitelayer.cpp. The 2nd zip file gives you the error message issued by make, although configure always seems to be good (no error). In this zip file, you will find r2000_modified.cpp, the modified version of r2000.cpp. This fiel and the log files thus are in : 
2 FAILED-OSX_1068-GCC_830-r2000_cpp_modified-strnlen_error_ogrsqlitelayer_cpp.zip

3:
Now, the strnlen error was modified in changing strnlen in strlen. I issued another error : two many parameters. Here enclosede is the 3rd zip files with the log ones :
3 FAILED-OSX_1068-GCC_830-r2000_cpp_modified-strlen_error_ogrsqlitelayer_cpp_too_many_parameters

I modified ogrsqlitelayer.cpp again, now with a unique parameter to be passed to strlen (strnlen needs two parameters). However, it fails too. This step is under study.

Nevertheless, I enclose a text (log) file issued by "diff -y" between the ogrsqlitelayer.cpp file of GDAL v. 2.4.2 and ogrsqlitelayer.cpp file of GDAL v. 2.1.4, successfully built.

Eventually, if they pass, individual log files and source files that were modified are included too.
[1 FAILED-OSX_1068-GCC_830-r2000_cpp_mactypes_h_error.zip](https://github.com/OSGeo/gdal/files/3734569/1.FAILED-OSX_1068-GCC_830-r2000_cpp_mactypes_h_error.zip)
[2 FAILED-OSX_1068-GCC_830-r2000_cpp_modified-strnlen_error_ogrsqlitelayer_cpp.zip](https://github.com/OSGeo/gdal/files/3734570/2.FAILED-OSX_1068-GCC_830-r2000_cpp_modified-strnlen_error_ogrsqlitelayer_cpp.zip)
[3 FAILED-OSX_1068-GCC_830-r2000_cpp_modified-strlen_error_ogrsqlitelayer_cpp_too_many_parameters.zip](https://github.com/OSGeo/gdal/files/3734572/3.FAILED-OSX_1068-GCC_830-r2000_cpp_modified-strlen_error_ogrsqlitelayer_cpp_too_many_parameters.zip)
[my-configure-OSX_1068-GCC_830-r2000_cpp_modified-strlen_error_ogrsqlitelayer_cpp_too_many_parameters.log](https://github.com/OSGeo/gdal/files/3734573/my-configure-OSX_1068-GCC_830-r2000_cpp_modified-strlen_error_ogrsqlitelayer_cpp_too_many_parameters.log)
[my-install-FAILED-OSX_1068-GCC_830-r2000_cpp_mactypes_h_error.log](https://github.com/OSGeo/gdal/files/3734574/my-install-FAILED-OSX_1068-GCC_830-r2000_cpp_mactypes_h_error.log)
[my-install-FAILED-OSX_1068-GCC_830-r2000_cpp_modified-strnlen_error_ogrsqlitelayer_cpp.log](https://github.com/OSGeo/gdal/files/3734575/my-install-FAILED-OSX_1068-GCC_830-r2000_cpp_modified-strnlen_error_ogrsqlitelayer_cpp.log)
[my-install-OSX_1068-GCC_830-r2000_cpp_modified-strlen_error_ogrsqlitelayer_cpp_too_many_parameters.log](https://github.com/OSGeo/gdal/files/3734576/my-install-OSX_1068-GCC_830-r2000_cpp_modified-strlen_error_ogrsqlitelayer_cpp_too_many_parameters.log)
[my-make-FAILED-OSX_1068-GCC_830-r2000_cpp_mactypes_h_error.log](https://github.com/OSGeo/gdal/files/3734577/my-make-FAILED-OSX_1068-GCC_830-r2000_cpp_mactypes_h_error.log)
[my-make-FAILED-OSX_1068-GCC_830-r2000_cpp_modified-strnlen_error_ogrsqlitelayer_cpp.log](https://github.com/OSGeo/gdal/files/3734578/my-make-FAILED-OSX_1068-GCC_830-r2000_cpp_modified-strnlen_error_ogrsqlitelayer_cpp.log)
[my-make-OSX_1068-GCC_830-r2000_cpp_modified-strlen_error_ogrsqlitelayer_cpp_too_many_parameters.log](https://github.com/OSGeo/gdal/files/3734579/my-make-OSX_1068-GCC_830-r2000_cpp_modified-strlen_error_ogrsqlitelayer_cpp_too_many_parameters.log)



[config-242-FAILED-OSX_1068-GCC_830-r2000_cpp_mactypes_h_error.log](https://github.com/OSGeo/gdal/files/3734580/config-242-FAILED-OSX_1068-GCC_830-r2000_cpp_mactypes_h_error.log)
[config-FAILED-OSX_1068-GCC_830-r2000_cpp_modified-strnlen_error_ogrsqlitelayer_cpp.log](https://github.com/OSGeo/gdal/files/3734581/config-FAILED-OSX_1068-GCC_830-r2000_cpp_modified-strnlen_error_ogrsqlitelayer_cpp.log)
[config-OSX_1068-GCC_830-r2000_cpp_modified-strlen_error_ogrsqlitelayer_cpp_too_many_parameters.log](https://github.com/OSGeo/gdal/files/3734582/config-OSX_1068-GCC_830-r2000_cpp_modified-strlen_error_ogrsqlitelayer_cpp_too_many_parameters.log)
[diff-y-242_214.log](https://github.com/OSGeo/gdal/files/3734583/diff-y-242_214.log)
[my-configure-FAILED-OSX_1068-GCC_830-r2000_cpp_mactypes_h_error.log](https://github.com/OSGeo/gdal/files/3734584/my-configure-FAILED-OSX_1068-GCC_830-r2000_cpp_mactypes_h_error.log)
[my-configure-FAILED-OSX_1068-GCC_830-r2000_cpp_modified-strnlen_error_ogrsqlitelayer_cpp.log](https://github.com/OSGeo/gdal/files/3734585/my-configure-FAILED-OSX_1068-GCC_830-r2000_cpp_modified-strnlen_error_ogrsqlitelayer_cpp.log)

Hoping you a good receipt.
Kind regards,

Laurent D.
