### ISSUE TITLE
PDS4: change of schema PDS4_CART_1B00.xsd breaking GDAL 3.0 branch autotest

### ISSUE THREAD

**Issue by rouault** [OSGeo/gdal#1934]
@thareUSGS  I've another issue, but with GDAL 3.0 branch this time. GDAL 3.0 uses the https://raw.githubusercontent.com/nasa-pds-data-dictionaries/ldd-cart/master/build/1.B.0.0/PDS4_CART_1B00.xsd schema, and its content seems to have changed very recently (less than 3 days ago). polar_radius is no longer available, and was replaced by intermediate_radius. GDAL 3.0 used to reference initially https://raw.githubusercontent.com/thareUSGS/ldd-cart/57b6d83a4976b2a409303ab3f3b9cd15eb8e1593/build/1.B.0.0/PDS4_CART_1B00.xsd , but you made me switch to the nasa-pds-data-dictionaries repository per f40cddf42b1dbb541e1a3a7277d1c085edc52378 . This change of content of https://raw.githubusercontent.com/nasa-pds-data-dictionaries/ldd-cart/master/build/1.B.0.0/PDS4_CART_1B00.xsd breaks GDAL autotest suite in the 3.0 branch, so ideally the file on nasa-pds-data-dictionaries should get its initial content (the one from thareUSGS), so that existing files produced by GDAL can validate.
Or if not possible I'll revert f40cddf42b1dbb541e1a3a7277d1c085edc52378 in the 3.0 branch to use again the https://raw.githubusercontent.com/thareUSGS/ldd-cart/57b6d83a4976b2a409303ab3f3b9cd15eb8e1593/build/1.B.0.0/PDS4_CART_1B00.xsd version (but files previously generated by GDAL 3.0 wouldn't validate anymore as referencing a schema that has changed in between)

**Comment by rouault** [comment]
@thareUSGS OK, I think I know what happened.While you have updated the new 1C00_1932 schema, you've probably also updated the 1B00 schema from your master version of https://github.com/pds-data-dictionaries/ldd-cart/tree/master/build/1.B.0.0 whereas nasa-pds-data-dictionaries/ldd-cart previously sticked to the version of https://github.com/thareUSGS/ldd-cart/commits/57b6d83a4976b2a409303ab3f3b9cd15eb8e1593

**Comment by thareUSGS** [comment]
I wasn't suppose to update 1B00 - that is on me (sorry about that). Hopefully pointing to at the NASA site for 1C00 should be much more stable than pointing at github. BTW, I have pushed a 1C00 so it should be hosted by tomorrow ( related #1851 ).

**Comment by rouault** [comment]
What do you suggest then regarding 3.0 / 1B00 ? Another alternative I'm thinking off would be to point to the pds-data-dictionaries repo, but at the specific revision that 3.0 is supposed to work with: https://raw.githubusercontent.com/pds-data-dictionaries/ldd-cart/57b6d83a4976b2a409303ab3f3b9cd15eb8e1593/build/1.B.0.0/PDS4_CART_1B00.xsd

**Comment by thareUSGS** [comment]
I did a revert (awkwardly) back for 1B00 (57b6d83a4976b2a409303ab3f3b9cd15eb8e1593), so hopefully that corrects the version GDAL is currently using.

**Comment by rouault** [comment]
OK, I do see that https://github.com/thareUSGS/ldd-cart/blob/master/build/1.B.0.0/PDS4_CART_1B00.xsd was reverted to the what GDAL 3.0 needs. Is that the new resource I should link to, or will that be migrated to the pds-data-dictionaries repository too ?

**Comment by thareUSGS** [comment]
Yes it probably makes more sense to point to the pds-data-dictionaries repository:
https://github.com/pds-data-dictionaries/ldd-cart/tree/master/build/1.B.0.0

Moving forward, once we change to 1.C.0.0 it is probably best to point to NASA's PDS4 schema website: https://pds.nasa.gov/datastandards/schema/released/#cart

**Comment by rouault** [comment]
ok, now that https://raw.githubusercontent.com/nasa-pds-data-dictionaries/ldd-cart/master/build/1.B.0.0/PDS4_CART_1B00.xsd has retrieved the content it used to have, tests are passing again

Closing this one
