### ISSUE TITLE
Segfault when loading image / band in python

### ISSUE THREAD

**Issue by simonrp84** [OSGeo/gdal#1939]
## Expected behavior and actual behavior.

I have a series of `tif` files that I want to read with gdal and convert into a numpy array. I expect that each image is opened, and then placed into an array.
But, instead I get a segfault: `Segmentation fault (core dumped)`

## Steps to reproduce the problem.
This causes a segfault:
```
import gdal
import glob
import numpy as np
in_dir = '/my/dir/'
files = glob.glob(in_dir+'*.tif*')
data = np.array(gdal.Open(files[0]).GetRasterBand(1).ReadAsArray())
```

This works as expected:
```
import gdal
import glob
import numpy as np
in_dir = '/my/dir/'
files = glob.glob(in_dir+'*.tif*')
ds = gdal.Open(inf)
data = np.array(ds.GetRasterBand(1).ReadAsArray())
```
## Operating system

Ubuntu 18.04, 64bit.

## GDAL version and provenance
I have tested on Python `3.7.3` installed via `miniconda`.
```
# Name                    Version                   Build  Channel
gdal                      3.0.1            py37hbb6b9fb_8    conda-forge
libgdal                   3.0.1                hf47eb90_8    conda-forge
numpy                     1.17.2           py37h95a1406_0    conda-forge
```

**Comment by rouault** [comment]
yes, known "gotcha" documented at https://trac.osgeo.org/gdal/wiki/PythonGotchas

**Comment by mloskot** [comment]
@simonrp84 FYI,  #1940 is a perfect first issue to contribute to GDAL
