### ISSUE TITLE
Port Python gotchas from wiki to documentation (help needed!)

### ISSUE THREAD

**Issue by mloskot** [OSGeo/gdal#1940]
I'm sure Python API users (e.g. #1939) would appreciate having this wiki page https://trac.osgeo.org/gdal/wiki/PythonGotchas dispplayed as a dedicated page linked from the main API documentation https://gdal.org/api/index.html

It's a perfect first issue. It only needs a bit of reStructuredText knwoledge to port from the wiki to the docs.

**Comment by torimcd** [comment]
Added pull request! https://github.com/OSGeo/gdal/pull/2072
