### ISSUE TITLE
RasterIO: wrong resampling over nodata areas

### ISSUE THREAD

**Issue by battisti-engineer** [OSGeo/gdal#1941]
## Expected behavior and actual behavior.

When calling RasterIO with resampling enabled (eg bilinear) over a no-data area, if the output buffer type is different than the input native type, the no-data pixels are not set properly.

The issue is described here in detail:
https://lists.osgeo.org/pipermail/gdal-dev/2019-October/050866.html

## Steps to reproduce the problem.

Input test data (140 MB):
http://lroc.sese.asu.edu/data/LRO-L-LROC-5-RDR-V1.0/LROLRC_2001/DATA/SDP/NAC_DTM/APOLLO17_3/NAC_DTM_APOLLO17_3.TIF

The following program shows the issue.

```
#include "gdal.h"

#define BNC 704
#define BNR 400
#define SNC 2525
#define SNR 4442
#define XOFF 0
#define YOFF 9880

int main() {

        GDALRasterIOExtraArg psExtraArg;
        GDALDatasetH hDataset;
        GDALDriverH hDriver;
        CPLErr err;
        double *buf, bmin, bmax;
        void *bp;
        unsigned int i;

        printf( "GDAL rasterio test\n"  );

        GDALAllRegister();
        hDataset = GDALOpenShared( "NAC_DTM_APOLLO17_3.TIF", GA_ReadOnly );
        hDriver = GDALGetDatasetDriver( hDataset );

        printf( "Driver: %s - %s\n", GDALGetDriverShortName( hDriver ), GDALGetDriverLongName( hDriver )  );
        printf( "b,r,c: %d, %d, %d\n", GDALGetRasterCount( hDataset ), GDALGetRasterYSize( hDataset ), GDALGetRasterXSize( hDataset ) );

        // read sub region
        buf = malloc( BNC * BNR * sizeof(double) );
        bp = (void *)buf;


        // use interpolation while reading
        INIT_RASTERIO_EXTRA_ARG(psExtraArg);
        psExtraArg.eResampleAlg = GRIORA_Bilinear; // GRIORA_NearestNeighbour | GRIORA_Bilinear

        err = GDALDatasetRasterIOEx(
                hDataset,
                GF_Read, // GDALRWFlag eRWFlag,
                XOFF, // int nDSXOff,
                YOFF, // int nDSYOff,
                SNC, // int nDSXSize,
                SNR, // int nDSYSize,
                bp, // void *pBuffer,
                BNC, // int nBXSize,
                BNR, // int nBYSize,
                GDT_Float64, // GDALDataType eBDataType,
                1, // int nBandCount,
                NULL, // int *panBandCount,
                0, // GSpacing nPixelSpace,
                0, // GSpacing nLineSpace,
                0, // GSpacing nBandSpace,
                &psExtraArg // GDALRasterIOExtraArg *psExtraArg
        );

        bmin = 1e50;
        bmax = -bmin;
        for (i=0; i < (BNC*BNR); ++i) {
                if (buf[i] > bmax) bmax = buf[i];
                if (buf[i] < bmin) bmin = buf[i];
        }
        printf( "computed min, max: %f, %f\n", bmin, bmax );

        GDALClose(hDataset);

        return 0;
} 

```

gcc `gdal-config --cflags` -g gtest.c `gdal-config  --libs` `gdal-config --dep-libs` -o gtest
./gtest shows:
computed min, max: -340282265508890445205022487695511781376.000000, 0.000000 

while the expected output is something like:
computed min, max: -340282265508890445205022487695511781376.000000, -2360.786377

## Proposed solution

At https://github.com/OSGeo/gdal/blob/master/gdal/gcore/rasterio.cpp#L1228

Instead of using:
```
                                GDALCopyWords(
                                    &fNoDataValue, GDT_Float32, 0,
                                    static_cast<GByte*>(pData) +
                                    nLineSpace * (j + nDstYOff) +
                                    nDstXOff * nPixelSpace,
                                    eBufType, static_cast<int>(nPixelSpace),
                                    nDstXCount);
```

Replace with:

```
	GDALCopyWords(
		&fNoDataValue, GDT_Float32, 0,
		static_cast<GByte*>(pDataMem) +
		nLSMem * (j + nDstYOff) +
                nDstXOff * nPSMem,
                eDTMem, static_cast<int>(nPSMem),
                nDstXCount);
```

**Comment by rouault** [comment]
@battisti-engineer  Your proposed change looks good on first sight. Thanks for digging deep into this. Would you mind submitting this as a pull request so that it gets tested against GDAL autotest suite. Could you also add a new test case for that in autotest/gcore/rasterio.py ?

**Comment by battisti-engineer** [comment]
I will try...
I wonder if I should first create a test case using a smaller dataset, what is the best practice in this case? Not familiar with the autotest suite.

**Comment by rouault** [comment]
I suggest to use a trivial in-memory dataset filled with just nodata != 0 values, like
```
        mem_ds = gdal.GetDriverByName('MEM').Create('', 4, 3, 1, GDT_Byte)
        mem_ds.GetRasterBand(1).SetNoDataValue(123)
        mem_ds.GetRasterBand(1).Fill(123)
```
You should be able to find inspiration from the existing tests in rasterio.py

**Comment by battisti-engineer** [comment]
OK.
I think the following shows the issue:
```

def test_rasterio_nodata():

	ndv = 123
	btype = [ gdal.GDT_Byte, gdal.GDT_Int16, gdal.GDT_Int32, gdal.GDT_Float32, gdal.GDT_Float64 ]

	### create a MEM dataset
	for src_type in btype:
		mem_ds = gdal.GetDriverByName('MEM').Create('', 10, 9, 1, src_type)
		mem_ds.GetRasterBand(1).SetNoDataValue(ndv)
		mem_ds.GetRasterBand(1).Fill(ndv)

		for dst_type in btype:
			if ( dst_type > src_type ):

				### read to a buffer of a wider type (and resample)
				data = mem_ds.GetRasterBand(1).ReadAsArray(0, 0, 10, 9, 4, 3, resample_alg=gdal.GRIORA_Bilinear, buf_type=dst_type)
				assert data[0,0] == ndv, 'did not read expected band data via ReadAsArray()'



```
As time allows I will work on the PR

**Comment by battisti-engineer** [comment]
Trying to get the autotest working. This is what I get for rasterio.py, is that expected?
```

$ pytest gcore/rasterio.py

Results (2.28s):
      16 passed
       5 failed
         - gcore/rasterio.py:849 test_rasterio_lanczos_nodata
         - gcore/rasterio.py:871 test_rasterio_resampled_value_is_nodata
         - gcore/rasterio.py:936 test_rasterio_dataset_readarray_cint16
         - gcore/rasterio.py:955 test_rasterio_rasterband_write_on_readonly
         - gcore/rasterio.py:964 test_rasterio_dataset_write_on_readonly
ERROR 1: TIFFWriteEncodedStrip:File not open for writing
ERROR 1: TIFFWriteEncodedStrip:File not open for writing

```

**Comment by rouault** [comment]
no, they're supposed to pass. Did you try before your changes ? Make sure your python bindings are linking against the GDAL .so you build and not the one from the system for example

**Comment by battisti-engineer** [comment]
I tried it after my changes. I will try again against master.
How do I ensure python bindings are linked to the latest gdal build?
I just did ./configure && make for GDAL, is that enough?
Do the py bindings need to be rebuilt?

**Comment by rouault** [comment]
> I just did ./configure && make for GDAL, is that enough?

Probably not. Make sure to source "scripts/setdevenv.sh" if you don"t install GDAL in a system-wide directory.

> Do the py bindings need to be rebuilt?

Generally, yes

**Comment by battisti-engineer** [comment]
ok! thanks that helped, I was missing the scripts/setdevenv.sh bit.
I have added a test on rasterio.py
