### ISSUE TITLE
GDAL 3.0.1: coordinate vertical transformation without geoid

### ISSUE THREAD

**Issue by and-marsh** [OSGeo/gdal#1946]
## Expected behavior and actual behavior.

Hi there!

During updating `GDAL` major version from `2` to `3` i discovered some interesting cases, that don't fit into my understanding. They regards to a new way `GDAL` works with 3D systems.

If i understand correctly, since `GDAL 3.0.0` there is a difference between 3D and 2D systems in coordinate transformation. As it is noticed in this issue https://github.com/OSGeo/gdal/issues/1622, to transform `z` coordinate it is necessary to have 3D systems as source and target systems during transformation.

So, to work with 2D Geographic CS the same way as with 3D we need to create Compound CS from this CS and some Vertical CS. In examples i used Geographic CS with number `EPSG:4175` and Vertical CS `EPSG:5773` with geoid file `egm96_15.gtx`

### Test for `GDAL 2.4.0` and `Proj4 5.2.0`: 
```
./gdaltransform --debug on -s_srs EPSG:4326 -t_srs EPSG:4175
OGRCT: Source: +proj=longlat +datum=WGS84 +no_defs
OGRCT: Target: +proj=longlat +ellps=clrk80 +towgs84=-88,4,101,0,0,0,0 +no_defs
OGRCT: Source: +proj=longlat +ellps=clrk80 +towgs84=-88,4,101,0,0,0,0 +no_defs
OGRCT: Target: +proj=longlat +datum=WGS84 +no_defs
-11 7
-10.9998835741026 6.99975949841979 -32.7834358848631
```
`z` is transformed in this example as expected
```
./gdaltransform --debug on -s_srs EPSG:4326 -t_srs EPSG:4175+5773                             130 ↵
OGRCT: Source: +proj=longlat +datum=WGS84 +no_defs
OGRCT: Target: +proj=longlat +ellps=clrk80 +towgs84=-88,4,101,0,0,0,0 +geoidgrids=egm96_15.gtx +vunits=m +no_defs
OGRCT: Source: +proj=longlat +ellps=clrk80 +towgs84=-88,4,101,0,0,0,0 +geoidgrids=egm96_15.gtx +vunits=m +no_defs
OGRCT: Target: +proj=longlat +datum=WGS84 +no_defs
-11 7
-10.9998835741026 6.99975949841979 -63.6640380659624
```
Here i added Vertical CS with geoid and it was applied to `z` coordinate as expected

### Test for `GDAL 3.0.1` and `Proj4 6.2.0`: 
```
./gdaltransform --debug on -s_srs EPSG:4979 -t_srs EPSG:4175                                  130 ↵
-11 7
-10.9998835741026 6.99975970834989 0
```
Here, since we use 2D CRS as target CRS `z` isn't transformed
```
./gdaltransform --debug on -s_srs EPSG:4979 -t_srs EPSG:4175+5773                             130 ↵
-11 7
OGRCT: Selecting transformation +proj=pipeline +step +proj=axisswap +order=2,1 +step +proj=unitconvert +xy_in=deg +xy_out=rad +step +inv +proj=vgridshift +grids=egm96_15.gtx +multiplier=1 +step +proj=push +v_3 +step +proj=cart +ellps=WGS84 +step +inv +proj=helmert +x=-88 +y=4 +z=101 +step +inv +proj=cart +a=6378249.145 +rf=293.465 +step +proj=pop +v_3 +step +proj=longlat +a=6378249.145 +rf=293.465 +step +proj=unitconvert +xy_in=rad +xy_out=deg +step +proj=axisswap +order=2,1 (WGS 84 to EGM96 height (1) + Inverse of Sierra Leone 1968 to WGS 84 (1))
-10.9998835735389 6.99975970717869 -30.8810844421387
```
After adding Vertical CRS as expected to the `z` coordinate was applied geoid shift. (We've already discussed difference between `GDAL 2` and `GDAL 3` results  in this issue https://github.com/OSGeo/gdal/issues/1836)

But how can i make behavior of `GDAL 3` similar to `GDAL 2`? I tried to create some Compound CS  based on some Vertical CS:
 ```
./gdaltransform -s_srs EPSG:4979 -t_srs \
'COMPOUNDCRS["Sierra Leone 1968 + Some height",
    GEOGCRS["Sierra Leone 1968",
        DATUM["Sierra Leone 1968",
            ELLIPSOID["Clarke 1880 (RGS)",6378249.145,293.465,
                LENGTHUNIT["metre",1]]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433]],
        CS[ellipsoidal,2],
            AXIS["geodetic latitude (Lat)",north,
                ORDER[1],
                ANGLEUNIT["degree",0.0174532925199433]],
            AXIS["geodetic longitude (Lon)",east,
                ORDER[2],
                ANGLEUNIT["degree",0.0174532925199433]],
        USAGE[
            SCOPE["unknown"],
            AREA["Sierra Leone - onshore"],
            BBOX[6.88,-13.35,10,-10.26]],
        ID["EPSG",4175]],
    VERTCRS["Some custom height",
        VDATUM["Some custom datum"],
        CS[vertical,1],
            AXIS["gravity-related height (H)",up,
                LENGTHUNIT["metre",1]],
        USAGE[
            SCOPE["unknown"],
            AREA["World"],
            BBOX[-90,-180,90,180]]]]'
-11 7
-10.9998835741026 6.99975970834989 0
```
Here Vertical CS hasn't any geoid, and is only used to turn 2D system into 3D. But `z` was not transformed, although there were 3D systems for source and target systems. 

Then i tried to get Proj4 string for current Compound CS with `projinfo` utility to use it as target CS:
```
./gdaltransform --debug on -s_srs EPSG:4979 -t_srs '+proj=longlat +a=6378249.145 +rf=293.465 +towgs84=-88,4,101,0,0,0,0 +vunits=m +no_defs +type=crs'
-11 7
-10.9998835741026 6.99975970834989 -32.7820108355954
```
And it worked! The height was transformed without vertical grid, just like in `GDAL 2`.

So, i'm interested is it a bug, that height transformation isn't applied if we use WKT for target system? And how can we force `GDAL 3` apply vertical transformation(not geoid shift) to any CS: Geographic 2D, Projected, Compound?

Thank you in advance for answer!

## Operating system 

macOS Catalina 10.15

## GDAL version and provenance

GDAL 3.0.1, PROJ 6.2.0

**Comment by rouault** [comment]
If you don't have a geoid grid or any explicit way of expressing the vertical transform, then it is rather indeterminate how to proceed: should coordinates be converted to geocentric coordinates back and forth between the 2 ellipsoids or not...  PROJ >= 6 has decided no longer to do that and keep the Z components unchanged. Unless you use the old +towgs84 syntax. But the "Sierra Leone 1968 to WGS 84 (1)" transformation is advertized by EPSG as being a 'Geocentric translations (geog2D domain)' operation, so normally the correction terms are only for the horizontal part, and not relevant for vertical transformations. So basically I believe that PROJ 6 behaviour is more correct.

**Comment by and-marsh** [comment]
Thank you Even,

Your answer clarified the situation.
