### ISSUE TITLE
VRT change block size for asynchronously R/W

### ISSUE THREAD

**Issue by winsento** [OSGeo/gdal#1948]
We have 2 GeoTiff 10Gb 80000x80000 Type=Float32.

Processing steps:
1. For input rasters, calculate the total intersected bounds and pixel size.
2. Create VRT files
```
vrt_options = gdal.BuildVRTOptions(
        outputBounds=bbox,
        xRes=pixel_size_x,
        yRes=-pixel_size_y,
        resampleAlg='near'
)
gdal.BuildVRT(path, [input_ds], options=vrt_options)
```
3. VRT files have `band.GetBlockSize() = (128, 128)`. We read each files band in array (by block), multiply arrays, and write to GeoTiff.

**GDAL Tests:**
Synchronously - time `3 min`
Asynchronously (via `pool.apply_async`) - `30 min`

**Rasterio test:**
Synchronously - time `6 min`

**Question:** Is it possible to set a block size in `BuildVRT`?

GDAL version: `GDAL 2.4.1, released 2019/03/15`

**Comment by rouault** [comment]
I'm not sure why the mention of synchronous vs asynchronous is relevant there ?

**Comment by rouault** [comment]
In recent versions, the VRT driver has a BLOCKXSIZE and BLOCKYSIZE creation option
