### ISSUE TITLE
3.x issue with PROJ4 string

### ISSUE THREAD

**Issue by thehesiod** [OSGeo/gdal#1951]
## Expected behavior and actual behavior.

expected: Ability to create proj4 projection with k != 1. 
actual: `proj_create: lat_ts != lat_0 and k != 1 not supported for Polar Stereographic`

## Steps to reproduce the problem.
This worked with GDAL 2.2, however causes the above error in 3.0.1
```python
import osr
PROJ4 = '+proj=stere +lat_0=90 +lat_ts=60 +lon_0=-105 +k_0=90 +x_0=0 +y_0=0 +a=6371200 +b=6371200 +units=m +no_defs'

ESPG_4326_PROJ4 = '+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs'

_espg_4326_sr = osr.SpatialReference()
_espg_4326_sr.ImportFromProj4(ESPG_4326_PROJ4)

ahps_v2_sr = osr.SpatialReference()
ahps_v2_sr.ImportFromProj4(PROJ4)

_4326_to_ahps_v2 = osr.CoordinateTransformation(_espg_4326_sr, ahps_v2_sr)

_ahps_v2_to_4326 = osr.CoordinateTransformation(ahps_v2_sr, _espg_4326_sr)
```

## Operating system

Debian Buster

## GDAL version and provenance

3.0.1 built via pip install against custom libproj
libproj: 6.2.0

**Comment by mloskot** [comment]
I think this issue fits the PROJ issues better as per [src/iso19111/io.cpp](https://github.com/OSGeo/PROJ/blob/caa512b5b135fcf00a01695a5860009671316eb2/src/iso19111/io.cpp#L8380-L8384)

```cpp
if (!lat_ts.empty() &&
    std::fabs(getAngularValue(lat_ts) - lat_0) > 1e-10 &&
    !k.empty() && std::fabs(getNumericValue(k) - 1) > 1e-10) {
    throw ParsingException("lat_ts != lat_0 and k != 1 not "
                            "supported for Polar Stereographic");
```

**Comment by thehesiod** [comment]
ok great, we got that from some AHPS NetCDF files so looks like they just created it wrong.  Thanks for the feedback.

**Comment by rouault** [comment]
> AHPS NetCDF files so looks like they just created it wron

can you point to / attach such a dataset ? We might want to put some hack in the netCDF driver to transparently deal with that

**Comment by thehesiod** [comment]
I'd have to do some exhaustive searching over over a decade of data.  They changed their PROJ4 string at least once, and at one point didn't even have one.  Also they often rewrite their historical files if they find issues so I may not be able to find it anymore.  I'll try though!  I found this via one of our unittests that test the scenarios we've seen in the past.

**Comment by thehesiod** [comment]
so I did some investigation and cannot find any AHPS files with this projection anymore, so it seems like they re-wrote all the files with bad projections.
