### ISSUE TITLE
Build broken: "fatal error U1050: PROJ_INCLUDE should be defined. PROJ >= 6 is a required dependency Stop.

### ISSUE THREAD

**Issue by maulanarachmat** [OSGeo/gdal#1953]
I tried to build on windows using 'nmake -f makefile.vc'
it gives error:
makefile.vc(6) : fatal error U1050: PROJ_INCLUDE should be defined. PROJ >= 6 is a required dependency
Stop.

**Environment**
Windows 10
Visual Studio 2019 Developer Command Prompt v16.3.6

**Comment by rouault** [comment]
The error message says pretty much all. See https://github.com/OSGeo/gdal/blob/master/appveyor.yml for a potential build recipe on Windows

**Comment by francoamato** [comment]
Hi Rouault, what should be done the appveyor.yml? I also tried to build gdal and I got some errors related to libgeotiff I think. Here the details:
1>...\gdal\frmts\gtiff\gt_wkt_srs.cpp(1318): error C3861: 'GTIFGetPROJContext': identifier not found
1>...\gdal\frmts\gtiff\gt_wkt_srs.cpp(1348): error C3861: 'GTIFGetPROJContext': identifier not found
1>...\gdal\frmts\gtiff\gt_wkt_srs.cpp(1450): error C3861: 'GTIFGetPROJContext': identifier not found
1>...\gdal\frmts\gtiff\gt_wkt_srs.cpp(1640): error C3861: 'GTIFGetPROJContext': identifier not found
1>...\gdal\frmts\gtiff\geotiff.cpp(10942): error C2065: 'LIBGEOTIFF_WARNING': undeclared identifier
1>...\gdal\frmts\gtiff\geotiff.cpp(10953): error C3861: 'GTIFNewEx': identifier not found
1>...\gdal\frmts\gtiff\geotiff.cpp(10956): error C3861: 'GTIFAttachPROJContext': identifier not found

Can you help please?
Regards

**Comment by smile4lee** [comment]
> Hi Rouault, what should be done with the appveyor.yml? I also tried to build gdal and I got some errors related to libgeotiff I think. Here the details:
> 1>...\gdal\frmts\gtiff\gt_wkt_srs.cpp(1318): error C3861: 'GTIFGetPROJContext': identifier not found
> 1>...\gdal\frmts\gtiff\gt_wkt_srs.cpp(1348): error C3861: 'GTIFGetPROJContext': identifier not found
> 1>...\gdal\frmts\gtiff\gt_wkt_srs.cpp(1450): error C3861: 'GTIFGetPROJContext': identifier not found
> 1>...\gdal\frmts\gtiff\gt_wkt_srs.cpp(1640): error C3861: 'GTIFGetPROJContext': identifier not found
> 1>...\gdal\frmts\gtiff\geotiff.cpp(10942): error C2065: 'LIBGEOTIFF_WARNING': undeclared identifier
> 1>...\gdal\frmts\gtiff\geotiff.cpp(10953): error C3861: 'GTIFNewEx': identifier not found
> 1>...\gdal\frmts\gtiff\geotiff.cpp(10956): error C3861: 'GTIFAttachPROJContext': identifier not found
> 
> Can you help please?
> Regards

Have you solved this? I encounted the same problem.
