### ISSUE TITLE
gdal3.0.1: gdalinfo can't find proj.db

### ISSUE THREAD

**Issue by qq2898** [OSGeo/gdal#1957]
I intalled GDAL3.0.1 in python3 with whl downloaded from uci, when I runs gdalinfo  xxx.tif, it shows
can't find proj.db, but there are actually 2 proj.db files in 
site-packages\osgeo\data\proj 
AND
site-packages\pyproj\proj_dir\share\proj

so why it can't find proj.db ?

**Comment by rouault** [comment]
See similar tickets: https://github.com/OSGeo/gdal/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+proj.db+PROJ_LIB
