### ISSUE TITLE
Opening a dataset with "MEM" driver silently ignores the requested access mode and sets access to GA_Update

### ISSUE THREAD

**Issue by gmgunter** [OSGeo/gdal#1971]
## Expected behavior and actual behavior.

__Expected:__
Opening an in-memory dataset using the "MEM" driver with `GA_ReadOnly` access mode should set the access mode to read-only, preventing modifying the dataset or the underlying memory. 

Alternatively, if read-only mode is not supported, attempting to open the dataset in `GA_ReadOnly` mode should raise an error.

__Actual:__
Opening an in-memory dataset using the "MEM" driver always sets the dataset's access mode to `GA_Update` regardless of the `eAccess` argument used in `GDALOpen`.

## Steps to reproduce the problem.

```c++
#include <gdal_priv.h>
#include <iostream>
#include <stdexcept>
#include <string>

int main()
{
    std::string name = "MEM:::DATAPOINTER=342343408,PIXELS=100,LINES=100,"
                       "BANDS=3,DATATYPE=Byte,PIXELOFFSET=3,LINEOFFSET=300,"
                       "BANDOFFSET=1";

    GDALAllRegister();
    GDALDatasetH handle = GDALOpen(name.c_str(), GA_ReadOnly);
    if (!handle) {
        throw std::runtime_error("unable to open GDAL dataset");
    }
    GDALDataset * dataset = GDALDataset::FromHandle(handle);

    if (dataset->GetAccess() == GA_ReadOnly) {
        std::cout << "GA_ReadOnly" << std::endl;
    }
    else if (dataset->GetAccess() == GA_Update) {
        std::cout << "GA_Update" << std::endl;
    }
    else {
        std::cout << "Unknown" << std::endl;
    }

    return 0;
}
```

```bash
$ g++ -o out test.cpp -Iinclude -Llib -lgdal && ./out
GA_Update
```

## Operating system

Ubuntu 16.04.4 64-bit

## GDAL version and provenance

2.3.3 via conda

Note that this behavior seems to be present in the current master branch as well:
https://github.com/OSGeo/gdal/blob/d9c232c73fb2150d50a75f9df0512893df23ea41/gdal/frmts/mem/memdataset.cpp#L1377

**Comment by rouault** [comment]
Fixed per https://github.com/OSGeo/gdal/pull/1976
