### ISSUE TITLE
GDAL 3.0.1: Transforming pixel, line position to latlon produces invalid results

### ISSUE THREAD

**Issue by BaconRanch** [OSGeo/gdal#1974]
## Expected behavior and actual behavior.

On older versions of GDAL (tested on 2.2.3), the below Python code produces correct output:
`24.8871064142 60.3400617637 0.0`

On GDAL 3.0.1, the below code produces:
`inf inf inf`

Note that the issue has something to do with the given projection / geotransform.  Other projections and geotransformations work fine.

## Steps to reproduce the problem.
```
from osgeo import gdal
from osgeo.osr import SpatialReference, CoordinateTransformation

geotransform = (25493659.366596557, 5.290018027612359, 0.0, 6692072.133870748, 0.0, -5.290858871228285)
projection = 'PROJCS["ETRS89 / GK25FIN",GEOGCS["ETRS89",DATUM["European_Terrestrial_Reference_System_1989",SPHEROID["GRS 1980",6378137,298.257222101,AUTHORITY["EPSG","7019"]],TOWGS84[0,0,0,0,0,0,0],AUTHORITY["EPSG","6258"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4258"]],PROJECTION["Transverse_Mercator"],PARAMETER["latitude_of_origin",0],PARAMETER["central_meridian",25],PARAMETER["scale_factor",1],PARAMETER["false_easting",25500000],PARAMETER["false_northing",0],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AXIS["Northing",NORTH],AXIS["Easting",EAST],AUTHORITY["EPSG","3879"]]'

source = SpatialReference()
source.ImportFromWkt(projection)

dest = SpatialReference()
dest.ImportFromEPSG(4326)

transform = CoordinateTransformation(source, dest)

x, y = gdal.ApplyGeoTransform(geotransform, 20, 20)
print transform.TransformPoint(x, y)
```

## Operating system

macOS 10.14.5

## GDAL version and provenance

GDAL 3.0.1 from homebrew tap [homebrew-osgeo4mac](https://github.com/OSGeo/homebrew-osgeo4mac/
)

**Comment by rouault** [comment]
GDAL 3 honours now by default CRS axis order. Either use transform.TransformPoint(y, x) or set .SetAxisMappingStrategy(osr.OAMS_TRADITIONAL_GIS_ORDER) on your source and/or dest objects. See https://github.com/OSGeo/gdal/blob/release/3.0/gdal/MIGRATION_GUIDE.TXT#L7

**Comment by BaconRanch** [comment]
Sorry I missed that in the documentation.  Thank you!

**Comment by tjwebb** [comment]
I'm still running into this issue with GDAL 3.1.4. Reprojecting 2284 -> 4326 and then `ExportToJson()` causes `[y,x]` coordinates to be written to the geojson coordinates array, rather than the correct `[x,y]` ordering.

**Comment by tjwebb** [comment]
`ExportToJson()` still produces incorrect ordering in GDAL 3 (tested in 3.1.4). Geojson should *always* order `[x,y]`, but for example reprojecting 2284 -> 4326 causes `[y,x]` coordinates to be written to the coordinates array.

**Comment by rouault** [comment]
> `ExportToJson()` still produces incorrect ordering in GDAL 3

Could you provide a self-contained snippet to reprudce the issue you see ?

**Comment by rouault** [comment]
@tjwebb https://github.com/OSGeo/gdal/pull/3311 should likely fix your issue, but I'm pretty sure it is going to break existing use cases, so will be a GDAL 3.3 material only
