### ISSUE TITLE
wrong documentation for mbtiles driver

### ISSUE THREAD

**Issue by j-lippmann** [OSGeo/gdal#1977]
if i run (gdal 3.1.0 dev installed via osgeo4w):
`gdal_translate -of MBTILES -co TILE_FORMAT=JPEG -co QUALITY=90 -co ZOOM_LEVEL=19 my.tif my.mbtiles`

> driver MBTiles does not support creation option ZOOM_LEVEL

but documentation say:

> Opening options

Starting with GDAL 2.1, the following open options are available:

    Raster and vector:

        ZOOM_LEVEL=value: Integer value between 0 and the maximum filled in the tiles table. By default, the driver will select the maximum zoom level, such as at least one tile at that zoom level is found in the ‘tiles’ table.

        USE_BOUNDS=YES/NO: Whether to use the ‘bounds’ metadata, when available, to determine the AOI. Defaults to YES.

https://gdal.org/drivers/raster/mbtiles.html

is the documentation wrong or should the driver know the ZOOM_LEVEL option?

**Comment by jratike80** [comment]
You are mixing open options (-oo) and creation options (-co).

Also, as stated on https://github.com/OSGeo/gdal/issues/new

> Questions should go to the gdal-dev mailing list at
> https://lists.osgeo.org/mailman/listinfo/gdal-dev
> or other support forums. GitHub issues are for bug
> reports and suggestions for new features.

**Comment by j-lippmann** [comment]
Ok. Thanks for the Info and Sorry for the Noise.
