### ISSUE TITLE
gdal_contour: total jam with GDAL 2.4.1, was OK in 2.2.3

### ISSUE THREAD

**Issue by jratike80** [OSGeo/gdal#1987]
Gdal_contour fails with Float32 GeoTIFF http://latuviitta.org/downloads/461864267output_la.tif with GDAL versions 2.4.1 and 3.1.0dev. On Windows the task just seems to stop at 0%. On Linux this error is observed:
`0ERROR 1: std::bad_alloc`

With GDAL 2.2.3 on Windows the process runs fine in a few seconds.

Command to use for testing:

`gdal_contour 461864267output_la.tif -f GPKG output_contour.gpkg -i 0.1`

The source tiff has NoData Value=3.40282346600000016e+38 but running the command with option `-snodata 3.40282346600000016e+38` does  not change the situation.  I believe that GDAL does not get the nodata right but starts to generate huge amount of contours. That would explain why command with fixed levels works well.

`gdal_contour 461864267output_la.tif -f GPKG output_contour.gpkg -fl 0.0 0.1 0.2`

Also, I am not sure if gdal_contour is supposed to work with a combination of "fixed levels" and "output as polygons" but on one Ubuntu machine it was leading to "core dumped". Another Ubuntu just aborted without dumping.

```
$ gdalinfo --version
GDAL 2.4.3, released 2019/10/28
$ time gdal_contour 461864267output_la.tif /home/ubuntu/output_contour.shp -fl 0.1 0.2 -p
0...10...20...30...40...50...60...70...80...90...100 - done.
gdal_contour: marching_squares/polygon_ring_appender.h:65: bool
marching_squares::PolygonRingAppender<PolygonWriter>::Ring::isIn(const
marching_squares::PolygonRingAppender<PolygonWriter>::Ring&) const 
[with PolygonWriter = PolygonContourWriter]:
Assertion `other.points.size() >= 4' failed.
Aborted (core dumped)
```

There may also be a connection with #1970

**Comment by rouault** [comment]
CC @mhugo
