### ISSUE TITLE
gdalwarp with multithreading return corrupted data (netcdf + geos projection)

### ISSUE THREAD

**Issue by vincentsarago** [OSGeo/gdal#1989]
Hi, following some experiment mentioned in #1985, I encountered another strange behaviour when doing warping with multithreading enabled.

## Steps to reproduce the problem.

```bash
$ aws s3 cp s3://noaa-goes16/ABI-L1b-RadF/2019/295/14/OR_ABI-L1b-RadF-M6C01_G16_s20192951400357_e20192951410065_c20192951410137.nc .

$ gdalwarp netcdf:OR_ABI-L1b-RadF-M6C01_G16_s20192951400357_e20192951410065_c20192951410137.nc:Rad rad_multi.tif -wo NUM_THREADS=8 -t_srs EPSG:4326
```
See the image above 👇 . Using multithreading creates lines with `nodata` values where it should be valid values.

![result](https://user-images.githubusercontent.com/10407788/68308082-3e552900-007a-11ea-8cc4-a9923adcdf9a.jpg)

When reducing the size of the chunk (reducing memory) fixes the lines (but print some error message, which from my understanding, are expected because some points are in space.)

```
$ gdalwarp netcdf:OR_ABI-L1b-RadF-M6C01_G16_s20192951400357_e20192951410065_c20192951410137.nc:Rad rad_multi_oneMb.tif -wm 1 -wo NUM_THREADS=8 -t_srs EPSG:4326
....
ERROR 1: Too many points (529 out of 529) failed to transform, unable to compute output bounds.
Warning 1: Unable to compute source region for output window 10474,9855,699,658, skipping.
....
```

Note: Not sure if this a bug report or more an issue to serve as documentation for people doing such work.

## GDAL version and provenance

gdal 3.0.1 (source)

**Comment by vincentsarago** [comment]
@rouault thanks for looking at this ❤️ 
Does this mean that if I pull Proj6.2 now I'll get the fix or should I wait for next PROJ release ?

**Comment by rouault** [comment]
Several options:
- pull PROJ 6.2 branch (once the backport is done) (or master). The next PROJ release will be 6.3.0 beginning of January
- and/or pull GDAL master or release/3.0 once https://github.com/OSGeo/gdal/pull/2009 is merged and backported

**Comment by rouault** [comment]
Backported to 3.0 and 2.4 branches
