### ISSUE TITLE
VICAR: support for INTFMT='HIGH'

### ISSUE THREAD

**Issue by thareUSGS** [OSGeo/gdal#1994]
## Expected behavior and actual behavior.

Using updated VICAR driver, I would like to open a file with  INTFMT='HIGH'

example file (only first 2048 bytes extracted). Can get full file if needed, but large.
ftp://ftpext.usgs.gov/pub/wr/az/flagstaff/thare/forGDAL/VICAR_testHIGH.vic

## Steps to reproduce the problem.

gdalinfo VICAR_testHIGH.vic

## Operating system

CentOS Linux release 7.2.1511 (Core)

## GDAL version and provenance

GDAL 2.5.0dev-df9184e, released 2019/99/99

**Comment by rouault** [comment]
> GDAL 2.5.0dev-df9184e, released 2019/99/99

That's expected.  df9184e is from March 6th . The file (the header) can be opened with latest GDAL master with my recent fixes
