### ISSUE TITLE
Common GDAL docker tags are missing

### ISSUE THREAD

**Issue by nyurik** [OSGeo/gdal#1995]
The [osgeo/gdal](https://hub.docker.com/r/osgeo/gdal/tags) docker images have two tagging problems (inter-related, thus one ticket, but could be broken up):
* there is no standard `latest` tag - which means the [automatic command](https://hub.docker.com/r/osgeo/gdal) shown for (and expected by) all users -- `docker pull osgeo/gdal` does not work.  I think the `ubuntu-full-latest` should also be published as `latest`
* There is no `GDAL 3.0.2` tag, only `v2.4.1` and `v2.5.0RC1`.  The various `latest` tags seem to match the latest 3.0.2, but that's not the same thing because I cannot fix my code to the well known tested version.

**Comment by rouault** [comment]
Both points adressed
