### ISSUE TITLE
Invalid srid in postgis when importing data by ogr2ogr

### ISSUE THREAD

**Issue by sandeepgadhwal** [OSGeo/gdal#2007]
I am using postgis 12 with postgis 3.0.0 and gdal 3.0.0 to copy data in it. The command i am using is

`ogr2ogr -f "PostgreSQL" PG:"host=127.0.0.1 dbname=db user=user port=5432 password=1" "file.geojson" -nln mutable`

The issue here is when i check the srid of the output table it is 900914 which is not correct in my case it should be 2223. To fix this i have to manually specify EPSG code by adding '-t_srs EPSG:2223'. This was not needed with previous version of ogr2ogr and postgis 2.5.

**Comment by rouault** [comment]
please attach such a geojson file

**Comment by sandeepgadhwal** [comment]
[parcel_0_1000.zip](https://github.com/OSGeo/gdal/files/3835920/parcel_0_1000.zip)
Here is a geojson file.

**Comment by rouault** [comment]
(This is a actually a ESRI JSON file). The file only contains a WKT without a EPSG code attached to it. When trying with GDAL 2.4, I also don't get automatic identification, so this does not seem to be an issue specific of GDAL 3
