### ISSUE TITLE
Allow DXF files with bulges to be treated as curve geometries instead of being converted to linestrings

### ISSUE THREAD

**Issue by raynerhoward** [OSGeo/gdal#2032]
It would be useful to get curve geometries from DXF files that contains bulges.  Curve geometries (or bulges) in DXF files are always tessellated (converted to short line strings which approximate the curve(s)).  Could the curve geometries be returned instead?

`ogrinfo -al has_bulges.dxf` returns the linestring representation of the curved features.

I understand that's how the DXF driver works at present:  https://gdal.org/drivers/vector/dxf.html

Could there be an option to show the geometries of DXF files as MULTICURVE, COMPOUNDCURVE and/or CIRCULARSTRING?

QGIS doesn't draw DXF 'features' as curves as a result of this limitation.

**Comment by jef-n** [comment]
The native import (see Project / Import/Export) will do this.
