### ISSUE TITLE
M-values aren't always included in shapefiles

### ISSUE THREAD

**Issue by graveland** [OSGeo/gdal#2033]
## Expected behavior and actual behavior.

I used ogr2ogr to convert a kml file (3D polygon with zeros for Z) to a shapefile, and the resulting shapefile didn't included the empty M values. It was created with shapetypes of 15 (polygonZ), but the should-be-empty M values were omitted.

## Steps to reproduce the problem.

[test-kml.txt](https://github.com/OSGeo/gdal/files/3865146/test-kml.txt)

ogr2ogr test.shp test.kml

resulting file has shapetype of 15, but no M values, so reading with other tools can fail.

## Operating system

macos 10.15.1

## GDAL version and provenance

3.0.2, installed with brew

**Comment by graveland** [comment]
When reading .shp files, I was using https://www.esri.com/library/whitepapers/pdfs/shapefile.pdf to parse them.

**Comment by rouault** [comment]
> I was using https://www.esri.com/library/whitepapers/pdfs/shapefile.pdf to parse them.

Do you mean your implementation based on this spec ? Well, at page 24, table 15 "PolygonZ Record Contents", it is mentionned that the Mmin, Mmax and Marray fields are optional, so I think GDAL is within its right not to write them.

**Comment by graveland** [comment]
huh. Thanks for pointing that out. I was looking more at page 18, M range and M array. There was no optional parts in there, and it seems I overlooked it. Page 19 doesn't mention M's being optional either. Sorry to bother you, I agree, that it's my problem not GDALs!

**Comment by graveland** [comment]
It's an interesting case- other packages (qgis for example) seems to write empty M values, so I had never seen M values being missing.

**Comment by jratike80** [comment]
Link to other necromancers http://osgeo-org.1560.x6.nabble.com/gdal-dev-RFC-61-Call-for-vote-on-adoption-td5249010i20.html

There is some discussion in that thread about how ESRI interprets "optional" - M may be empty, but should be present.
I just tested linez and polygonz shapefiles which I created with GDAL and ArcMap desktop 10.8 opens them without any messages so it is GDAL interoperable.
