### ISSUE TITLE
GDALDataset.SetProjection does not accept Proj4 string anymore

### ISSUE THREAD

**Issue by letmaik** [OSGeo/gdal#2034]
https://github.com/OSGeo/gdal/blob/6cbb39a741db60c96d6ea0f8d87e5134a2f3f7d9/gdal/gcore/gdaldataset.cpp#L983-L1017

This function was changed in 3.0 and is supposed to be a compatibility layer now, however, it only supports WKT strings and not proj4, breaking old behaviour and also contradicting the docstring.

## GDAL version and provenance

3 (master, see above)

**Comment by rouault** [comment]
Good point. Although I'd be surprised if most drivers would have worked properly with PROJ strings. Would you be willing to submit a pull request to fix this ? This should be just a matter of using SetFromUserInput() instead of importFromWkt().
