### ISSUE TITLE
Typo for Google Earth in 'Software using GDAL' doc

### ISSUE THREAD

**Issue by puran1218** [OSGeo/gdal#2036]
## Expected behavior and actual behavior.

`Geoogle Earth` should be `Google Earth` in [Software using GDAL](https://github.com/OSGeo/gdal/blob//master/gdal/doc/source/software_using_gdal.rst).

## Steps to reproduce the problem.

Open https://github.com/OSGeo/gdal/blob//master/gdal/doc/source/software_using_gdal.rst and goes to Software starting with G.
![image](https://user-images.githubusercontent.com/15075826/69256623-b97b1b00-0bf4-11ea-9adf-3c6bdf295ef0.png)

## Operating system

NA

## GDAL version and provenance

master branch

**Comment by rouault** [comment]
I'd suggest you use the "Edit on github" link to directly provide the correction as a pull request :-) That was intended for such trivial changes

**Comment by puran1218** [comment]
@rouault I will do that next time. Thanks :)
