### ISSUE TITLE
Drop GFT driver starting Dec. 3, 2019

### ISSUE THREAD

**Issue by rouault** [OSGeo/gdal#2050]
The GFT service stops at that date.

Drop it from master. Will be useless in 3.0 and 2.4 as well

**Comment by jratike80** [comment]
And GFT stands for "Google Fusion Tables"

**Comment by rouault** [comment]
CC @schwehr . Maybe you want to have the "privilege" to do that removal :-) ?

**Comment by rouault** [comment]
Removed everything related to GFT in master. In 3.0 and 2.4, just tests and doc

**Comment by schwehr** [comment]
Thanks!  Sorry I missed your note about the removal.
