### ISSUE TITLE
Getting double images when using gdal_translate from tif to png

### ISSUE THREAD

**Issue by donnyv** [OSGeo/gdal#2056]
## Expected behavior and actual behavior.
When I use gdal_translate to convert tif to png on a Windows 10 machine it works fine. But when I do it on Windows Server 2012 R2. It creates an image with double images. 
![image](https://user-images.githubusercontent.com/2224189/69647430-775c3a00-1037-11ea-93b9-8993f0dff36a.png)

Sources
http://gis.civilsolutions.biz/downloads/_sheet.png
http://gis.civilsolutions.biz/downloads/5ddc1c8012ae241ad4b58dd1.tif

## Steps to reproduce the problem.
gdal_translate -of PNG -b 1 "G:\5ddc1c8012ae241ad4b58dd1.tif" "G:\\_sheet.png"

## Operating system
Windows Server 2012 R2 Build 9600

## GDAL version and provenance
This happened in version 2.4.1-1 and 3.0.2-1

**Comment by rouault** [comment]
What do you mean by "double image" ? Which GDAL binary distribution do you use ? Is the problem reproduced with the same binary distribution (that is works on W10 but not WS2012) ?

**Comment by donnyv** [comment]
@rouault If you look at the numbers from the image I posted. It looks like its doubling the image. It could be doing something else but that what it looks to me. For the Win 10 and Windows Server install I used OSGeo4W to install GDAL.

**Comment by rouault** [comment]
And if you look  in Windows Server at the image generated by Win 10: is it OK ? Just want to be sure that the issue is on the generating side (GDAL) and not on the display side.

**Comment by donnyv** [comment]
Yes it is ok.

**Comment by jratike80** [comment]
I can only say that the results with my Windows 10 and GDAL versions 3.0.2 and 3.1.0dev are good. Problem seems to be something that is specific to Windows Server 2012. Have you tried to convert the tiff into png with some other program on the same Windows Server?

**Comment by donnyv** [comment]
Yes, I used IrfanView and it looks fine.
![image](https://user-images.githubusercontent.com/2224189/69728306-3ecd6680-10f2-11ea-8699-861b5c050432.png)

**Comment by donnyv** [comment]
Just wanted to give you guys an update. We eventually moved the app to Windows Server 2019 and it works fine there. So there is definitely something with 2012 R2. I guess just make a note and let people know they need to update. I'll close this unless you want to keep it open.
