### ISSUE TITLE
Converting projected coordinates (x[km],y[km]) to geographic coordinates (longitude,latitude)

### ISSUE THREAD

**Issue by mcFishin2039** [OSGeo/gdal#2059]
Hello, 

I am new to using the GDAL library and I am aware of the function gdaltransform. 

The data I have is x/y (units:km) and is projected in the EPSG:26707 NAD27 / UTM zone 7N  system. 
I want to transform these into geographic coordinates (longitude/latitude). 
What is the most pragmatic way to accomplish this with gdal? I have a simple input.csv file holding the x(km) and y(km) locations.   

I sincerely appreciate and welcome any tips or suggestions! Thanks!! 

- M

**Comment by rouault** [comment]
Quoting https://github.com/OSGeo/gdal/issues/new
```
IMPORTANT: Do NOT use GitHub to post any questions or support requests!
           They will be closed immediately and ignored.

Questions should go to the gdal-dev mailing list at
https://lists.osgeo.org/mailman/listinfo/gdal-dev
or other support forums. GitHub issues are for bug
reports and suggestions for new features.
```
