### ISSUE TITLE
ogr2ogr import shapefile to SQL Server 2017 arithmetic overflow

### ISSUE THREAD

**Issue by shar013** [OSGeo/gdal#2062]
I'm using ogr2ogr --version
GDAL 3.0.2, released 2019/10/28
to import shapefiles to SQL Server 2017 with only partial success, in that I end up with just a subset of the shapes imported.

This is my command:
ogr2ogr -f "MSSQLSpatial" -lco overwrite=yes -skipfailures "MSSQL:server=localhost;database=Spatial;trusted_connection=yes;driver=ODBC Driver 17 for SQL Server" "C:\Users\Steve\Downloads\statsnzgeneral-electoral-district-2002-SHP\general-electoral-district-2002.shp" -a_srs "EPSG:2193"

I get repeated instances of this error:
ERROR 1: INSERT command for new feature failed. [22003][Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Arithmetic overflow error converting numeric to data type numeric.(8115), [01000][Microsoft][ODBC Driver 17 for SQL Server][SQL Server]The statement has been terminated.(3621)

I've tried 5 different SQL Server ODBC drivers, the outcome is the same. So I looked at some of the failed shapes in QGIS. I find that shape_star sometimes has large values. Here's an example: 2236033666.630000114440918

The table created in SQL Server by ogr2ogr has the number columns as numeric(24, 15). This is too small to accommodate the number above which has 25 digits.

This is from ssms:
create table dbo.Test (
	shape_star numeric(24, 15) null
)
go
insert into dbo.Test values (2236033666.630000114440918)
go
Msg 8115, Level 16, State 8, Line 7
Arithmetic overflow error converting numeric to data type numeric.
The statement has been terminated.

So the column needs to be at least numeric(25, 15), but maybe you could make
+ the number columns numeric(38, 19). This will use a bit more space but the values are unlikely to ever overflow.

## Expected behavior and actual behavior.

For example (please modify !!!): I expected to be able to open this raster file (with a link to
the raster file, or it as an attachment) and it returns an error message
instead.

## Steps to reproduce the problem.

For example (please modify !!!): "gdalinfo myfile"

## Operating system

For example (please modify !!!): Ubuntu 16.04 64 bit

## GDAL version and provenance

For example (please modify !!!): the 2.2.3 version from ubuntugis-unstable PPA

**Comment by rouault** [comment]
Try adding `-unsetFieldWidth`

**Comment by shar013** [comment]
Er... okay. The shapes are all in the table now. The number columns are all float. The database is happy, QGIS is happy. I'm happy. Numbers a bit less precise, but I do not care about that. Thanks.
