### ISSUE TITLE
GDALWarpAppOptionsNew error

### ISSUE THREAD

**Issue by jingcb** [OSGeo/gdal#2066]
sir, I use gdal with 2.4.1 in Mac with Xcode

my code:
     char* warpArgv[13] = {"-te", "123", "456", "150", "500", "-t_srs", "epsg:3587", "-ts", "200", "200", "filepath", "/vsimem/", "-q"};
     GDALWarpAppOptions *psOptions = GDALWarpAppOptionsNew(warpArgv, nullptr);

<img width="987" alt="截屏2019-11-2900 57 11" src="https://user-images.githubusercontent.com/26957564/69823230-418ba100-1243-11ea-91fc-10b82613556d.png">

**Comment by rouault** [comment]
Add a final `, nullptr to warpArgv
