### ISSUE TITLE
Doc: Broken Link on gdal.org 

### ISSUE THREAD

**Issue by rjhale1971** [OSGeo/gdal#2070]
I was going to attempt a fix but my confidence level isn't high enough for it - plus I'm not 100% sure I have the destination of the broken link. 

On this page:  https://gdal.org/drivers/vector/sqlite.html . Scroll down to the SQLite SQL Dialect heading and click on the link:  OGR datasource if using the **SQLite SQL** dialect. 

I think the link should go here: https://gdal.org/user/sql_sqlite_dialect.html - but I'm not convinced.

**Comment by mloskot** [comment]
I think you are correct.

Additionally, on the same page there is this link in "SQL commands with **OGR SQL** engine" which should point to https://gdal.org/user/ogr_sql_dialect.html instead of https://gdal.org/drivers/vector/ogr_sql.html
