### ISSUE TITLE
Vertical transform failed

### ISSUE THREAD

**Issue by aharondavid** [OSGeo/gdal#2074]
## Expected behavior and actual behavior.

GDAL (probably proj4) failed to read PROJ_LIB environment variable when the file path encoding
is different from the system local 

## Steps to reproduce the problem.
1. set the  PROJ_LIB environment variable to something different from your current local (for example c:\temp\档案文件\proj )

2. add a egm96_15.gtx file to the above directory 

3.  //source or destination used in WKT that contained the Vertical Datum egm96_15.gtx 
OGRCoordinateTransformation* p =OGRCreateCoordinateTransformation(source,dest); 
p>Transform(1,X,Y,Z) //failed !
 

## Operating system

Windows 10

## GDAL version and provenance

GDAL 2.2.2 proj4 4.9.3

**Comment by rouault** [comment]
Hum, non ANSI characters in the path. I'm not sure PROJ is ready for that as it uses the ANSI Windows API. In any case this is a PROJ issue. Should be filed at https://github.com/OSGeo/PROJ/issues

**Comment by aharondavid** [comment]
Hello @rouault  and thank you for yourquick response.
I think that the proj4 already have a solution for that and GDAL just need to use it.
the solution is to overwrite the default file handling by using  the proj4 api: **pj_ctx_set_fileapi**

**Comment by rouault** [comment]
I'd perfer not doing that in GDAL, but rahter that PROJ does the right thing by default...

**Comment by aharondavid** [comment]
GDAL have a flag for that - GDAL_FILENAME_IS_UTF8.
 what you think the PROJ default behavior should be? a new method that get a UNICODE ? maybe UTF8 ?. I think, they will say - we have an API for that - pj_ctx_set_fileapi and you may to use it

**Comment by rouault** [comment]
I'm part of the PROJ team as well :-) I'm not completely of the appropriate solution on PROJ side: perhaps indeed a PROJ_FILENAME_IS_UTF8 that we could make the default. But from a pure engineering point of view, as PROJ_LIB is a PROJ variable, that should be up to PROJ to have support for Unicode paths. Not GDAL trying to workaround it. And pj_ctx_set_fileapi is in the obsolete proj_api.h that GDAL 3 no longer uses. There's no direct equivalent in PROJ 6 proj.h API

**Comment by aharondavid** [comment]
Ok @rouault , I will open the issue in PROJ.
Thanks !
