### ISSUE TITLE
Feature request: write append to GeoJSONSeq

### ISSUE THREAD

**Issue by kylebarron** [OSGeo/gdal#2080]
## Expected behavior and actual behavior.

Ability to append data to an existing GeoJSONSeq newline-delimited file. It appears from trial and error and from internet searches that this is not possible, or at the least not documented. The structure of newline-delimited GeoJSON seems to lend well to both incremental reading _and_ writing.

Originally reported on Toblerity/Fiona:
https://github.com/Toblerity/Fiona/issues/839

## Steps to reproduce the problem.

Example GeoJSON data:
```json
{
"type": "FeatureCollection",
"features": [
{ "type": "Feature", "properties": { }, "geometry": { "type": "Point", "coordinates": [ 0.0, 1.0 ] } }
]
}
```

Create GeoJSON newline-delimited file:
```
ogr2ogr -f GeoJSONSeq out.geojson in.geojson
> cat out.geojson
{ "type": "Feature", "properties": { }, "geometry": { "type": "Point", "coordinates": [ 0.0, 1.0 ] } 
```

But with any combination of `-append` and `-update`, an error is produced when trying to append to `out.geojson`
```
> ogr2ogr -f GeoJSONSeq -append out.geojson in.geojson
ERROR 1: Layer 'in' does not already exist in the output dataset, and cannot be created by the output driver.
ERROR 1: Terminating translation prematurely after failed
translation of layer in (use -skipfailures to skip errors)
> ogr2ogr -f GeoJSONSeq -update out.geojson in.geojson
ERROR 1: Layer 'in' does not already exist in the output dataset, and cannot be created by the output driver.
ERROR 1: Terminating translation prematurely after failed
translation of layer in (use -skipfailures to skip errors)
> ogr2ogr -f GeoJSONSeq -append -update out.geojson in.geojson
ERROR 1: Layer 'in' does not already exist in the output dataset, and cannot be created by the output driver.
ERROR 1: Terminating translation prematurely after failed
translation of layer in (use -skipfailures to skip errors)
```

## Operating system

MacOS 10.15.1

## GDAL version and provenance

```
> gdalinfo --version
GDAL 3.0.2, released 2019/10/28
```

Installed from Conda.

**Comment by jratike80** [comment]
The error message gives a hint. Let's check what we have

```
ogrinfo out.geojson
INFO: Open of `out.geojson'
      using driver `GeoJSON' successful.
1: out (Point)
```
GeoJSON can only have one layer so we must append to an existing layer

```
ogr2ogr -f GeoJSONSeq -update -append out.geojson in.geojson -nln out
ogrinfo out.geojson -al -so
INFO: Open of `out.geojson'
      using driver `GeoJSON' successful.

Layer name: out
Geometry: Point
Feature Count: 2
```

**Comment by kylebarron** [comment]
Thanks, I did miss that from my searching, but from a bit more testing, I still find that GeoJSONSeq incremental writing is not supported. Example:

`in.geojson` with two points:
```json
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {},
      "geometry": { "type": "Point", "coordinates": [0.0, 1.0] }
    },
    {
      "type": "Feature",
      "properties": {},
      "geometry": { "type": "Point", "coordinates": [2.0, 3.0] }
    }
  ]
}
```

Convert it to GeoJSONSeq:
```
> ogr2ogr -f GeoJSONSeq out.geojson in.geojson
> cat out.geojson
{ "type": "Feature", "properties": { }, "geometry": { "type": "Point", "coordinates": [ 0.0, 1.0 ] } }
{ "type": "Feature", "properties": { }, "geometry": { "type": "Point", "coordinates": [ 2.0, 3.0 ] } }
```

Then try to append `in.geojson` to `out.geojson`:
```
> ogrinfo out.geojson
INFO: Open of `out.geojson'
      using driver `GeoJSONSeq' successful.
1: out (Point)
> ogr2ogr -f GeoJSONSeq -update -append out.geojson in.geojson -nln out

ERROR 6: GeoJSONSeq driver does not support update
ERROR 1: Unable to open existing output datasource `out.geojson'.
```

**Comment by kylebarron** [comment]
Also, using my original example, the command works without raising an error, but it still converts GeoJSONSeq to normal GeoJSON, which seems like a bug to me.

`in.geojson`:
```json
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {},
      "geometry": { "type": "Point", "coordinates": [0.0, 1.0] }
    }
  ]
}
```

Create GeoJSONSeq
```
> ogr2ogr -f GeoJSONSeq out.geojson in.geojson
> cat out.geojson
{ "type": "Feature", "properties": { }, "geometry": { "type": "Point", "coordinates": [ 0.0, 1.0 ] } }
```

Append using your suggested command:
```
> ogrinfo out.geojson
INFO: Open of `out.geojson'
      using driver `GeoJSON' successful.
1: out (Point)
> ogr2ogr -f GeoJSONSeq -update -append out.geojson in.geojson -nln out
> \cat out.geojson
{
"type": "FeatureCollection",
"name": "out",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { }, "geometry": { "type": "Point", "coordinates": [ 0.0, 1.0 ] } },
{ "type": "Feature", "properties": { }, "geometry": { "type": "Point", "coordinates": [ 0.0, 1.0 ] } }
]
}
```

Despite specifying GeoJSONSeq, that output is normal GeoJSON. I'd expect:
```json
{ "type": "Feature", "properties": { }, "geometry": { "type": "Point", "coordinates": [ 0.0, 1.0 ] } },
{ "type": "Feature", "properties": { }, "geometry": { "type": "Point", "coordinates": [ 0.0, 1.0 ] } }
```

I'm using GDAL 3.0.2. Can you try these two examples with 3.1.0dev?

**Comment by jratike80** [comment]
Right, I just observed the same change from GeoJSONSeq into regular GeoJSON with your first example. That does feel like a bug to me. Thank you for testing.

**Comment by rouault** [comment]
The GeoJSONSeq driver is currently read-only or write-only (meaning creation-only). In the OGR data model, appending features is considered as a update of an existing datasource. That said, some limited update capability could be introduced to support just feature appending and not modification/deletion of existing features. Needs some work though

**Comment by answerquest** [comment]
Hi, given that the GeoJSONSeq file format is inherently easy to work with for appending, I supposed folks are getting by by doing simple hacks outside of the core program. But it would really be great to have it built-in. Giving this a bump in hopes of catching some developer's attention; sorry I can't contribute in code as of yet.
