### ISSUE TITLE
gdal shift after resampling with gdalwarp

### ISSUE THREAD

**Issue by NexusMaxus** [OSGeo/gdal#2081]
## Expected behavior and actual behavior.

After resampling a global map the output in gdal 3.0.1 is shifted (SE direction). The resampling was both run in the command line and in the python API. The same result was retrieved after running gdal 2.4.3. 

the original with a 0.25 degree resolution:
![Screenshot from 2019-12-03 14-17-53](https://user-images.githubusercontent.com/37043157/70056200-55385e00-15db-11ea-9270-9bdb4bc5572e.png)

resampled the map should look exacty the same, instead the result was shifted. The actual behavior is that the resampled at 0.009 degree resolution shows the shift:
![Screenshot from 2019-12-03 14-18-45](https://user-images.githubusercontent.com/37043157/70056212-59fd1200-15db-11ea-99e1-986603f6b525.png)

Here a zoom in of the image within the red box to see the shift more clearly:
![Screenshot from 2019-12-03 14-19-13](https://user-images.githubusercontent.com/37043157/70054488-f1f8fc80-15d7-11ea-8fd0-7725e56c5361.png)

This shift should not be there.

## Steps to reproduce the problem.

The code that was used in python is: 
`options = gdal.WarpOptions(xRes=0.00900900900901, yRes=-0.00900900900901, resampleAlg='mode') 
gdal.Warp('#PATH/rfi_{}_1000m.tif'.format(year), '#PATH/rfi_{}.tif'.format(year), options=options)`

In which my local path is replaced with #PATH 

## Operating system

Manjaro Linux 18.1.3 64 bit

## GDAL version and provenance

tried both:
gdal 3.0.1 from Manjaro Pacman
gdal 2.4.3 from conda-forge

**Comment by rouault** [comment]
As 0.25 / 0.009009 = 25.75 is not an integer, and given the nature of the "mode" resampling, it isn't obvious to me that there is a bug. You should include the input data if someone wants to try to reproduce

**Comment by rouault** [comment]
Closing due to lack of feedback. Reopen if you can provide more elements
