### ISSUE TITLE
EPSG:3857 regresion: longitude of natural origin is ignored on gdal 3.x, 2.x works ok

### ISSUE THREAD

**Issue by mkrivos** [OSGeo/gdal#2087]
## Expected behavior and actual behavior.

Gdal 3.x seems to ignore longitude of natural origin settings for spherical mercator (coordinate projection ignores this settings), cs2cs utility works still OK.

## Steps to reproduce the problem.

This trivial test code fails:

TEST(GeoReferenceTest, nonNullMeridianSphericalMercator)
{
    OGRSpatialReference* meridian0 = new OGRSpatialReference{"+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext  +no_defs"};
    OGRSpatialReference* meridian1 = new OGRSpatialReference{"+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=1 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext  +no_defs"};

    double m0 = meridian0->GetPrimeMeridian();
    EXPECT_EQ(0.0, m0);

    double m1 = meridian1->GetPrimeMeridian();
    EXPECT_EQ(1.0, m1);
}

## Operating system

Arch Linux 64

## GDAL version and provenance

gdal 3.0.1 + proj 6.2.0

**Comment by rouault** [comment]
PROJ issue, just fixed. Will be in PROJ 6.3.0

**Comment by mkrivos** [comment]
Hello Rouault,
ok.
Inspecting: double OGRSpatialReference::GetPrimeMeridian( const char **ppszName ) const
why "d->dfFromGreenwich" contains correct value (1.0) but "d->m_osPrimeMeridianName" is empty.

If m_osPrimeMeridianName will be not empty, gdal code returns correct result.
Maybe setting m_osPrimeMeridianName from PROJ is bug ?

Thank you very much.
