### ISSUE TITLE
gdal2tiles should not hard-code 256x256 pixel tile size

### ISSUE THREAD

**Issue by daniel-j-h** [OSGeo/gdal#2097]
Right now gdal2tiles hard-codes a tile size of 256x256 pixels.

It would be great to not hard-code this tile size but instead let the user pass the tile size from the command line, e.g. as in `--tilesize 512` to generate 512x512 pixel tiles.

The workaround right now is to use gdal2tiles, generate 256x256 pixel tiles, and then manually combining four of those tiles into a single 512x512 pixel tile.

**Comment by kannes** [comment]
Seems easy to expose and seems to work but should have some tests: https://gis.stackexchange.com/questions/112009/use-gdal2tiles-to-generate-512px-tiles/295254#295254
