### ISSUE TITLE
gdal2tiles should allow for XYZ slippy map tiles and not just TMS

### ISSUE THREAD

**Issue by daniel-j-h** [OSGeo/gdal#2098]
At the moment gdal2tiles generates TMS slippy map tiles.

It would be great to add an option to allow the user to create XYZ tiles, see e.g.

https://gist.github.com/tmcw/4954720

which implies just flipping the tile y coordinates.

Workaround right now is to use gdal2tiles to generate TMS tiles, and then manually flip the y tile coordinates. Or find a map framework which supports TMS tiles.

**Comment by mloskot** [comment]
Seem like a `good first issue`

**Comment by kannes** [comment]
There are several forks of gdal2tiles and it would be fantastic if someone merged them reasonably and re-introduced a modern version of it to the GDAL repo.

**Comment by daniel-j-h** [comment]
Cool, where are these gdal2tiles forks? What's their purpose?

What's the official roadmap or plan for the bundled gdal2tiles tool then for gdal?

**Comment by kannes** [comment]
I have no idea and I just realised I posted quite the off-topic comment on an issue, sorry.

Now that I actually looked at some of my ancient notes and saw that quite a few have been resolved, I wonder if it would make sense to drop `gdal2tiles.py` in favour of writing a mbtiles file and extracting that later if needed. This would mean that people could use all the magic of `gdal_translate` and no development effort would need to go into maintaining `gdal2tiles.py`. Would that make sense, @rouault?

Anyways, here's some links, there should be one with slippy map file names inside if I recall correctly:

- 
- https://github.com/tehamalab/gdal2tiles (quite ugly how they stole the name imo)
- https://github.com/roblabs/gdal2tilesp
- https://github.com/GitHubRGI/geopackage-python/blob/master/Tiling/gdal2tiles_parallel.py
- https://trac.osgeo.org/gdal/ticket/2052
- https://github.com/Luqqk/gdal2tiles
- https://github.com/mj10777/gdal2mbtiles
- http://osgeo-org.1560.x6.nabble.com/gdal-dev-MBTiles-from-gdal2tiles-vs-from-gdal-translate-td5304349.html

**Comment by rouault** [comment]
> Would that make sense, @rouault?

gdal2tiles does more than what you mention, like writing all the html & js stuff

**Comment by kannes** [comment]
Ah true, I always thought that was weird and pretty out of place though. It's not called gdalraster2web.
