### ISSUE TITLE
ogr2ogr to use purely java bindings 

### ISSUE THREAD

**Issue by wuyyururaviteja** [OSGeo/gdal#2099]
Iam using ogr2ogr with java bindings for file conversion. The conversion process is successful in the installed system but upon using the generated jars and library files in another system for conversion (same os configuration) it was not able to succeed since it needs proj installation. I would like to request you to suggest about any way so that i can generate in a single system and use those files for conversion on any no of systems with zero installation? the errors have occured in CentOs,Mac and linux.(CentOs is my top priority)  

CentOs:
ERROR 1: PROJ: internal_proj_create_from_wkt: Cannot find proj.db
ERROR 1: PROJ: internal_proj_create_from_wkt: Cannot find proj.db
ERROR 1: PROJ: internal_proj_identify: Cannot find proj.db
ERROR 1: PROJ: internal_proj_as_wkt: Cannot find proj.db
ERROR 1: PROJ: internal_proj_as_wkt: Cannot find proj.db
ERROR 1: PROJ: internal_proj_as_wkt: Cannot find proj.db
ERROR 1: PROJ: internal_proj_as_wkt: Cannot find proj.db
ERROR 1: PROJ: internal_proj_create: Cannot find proj.db
ERROR 1: PROJ: internal_proj_create: Cannot find proj.db
ERROR 1: PROJ: internal_proj_create_operation_factory_context: Cannot find proj.db
ERROR 1: PROJ: pj_obj_create: Cannot find proj.db
ERROR 1: PROJ: internal_proj_as_proj_string: Cannot find proj.db
ERROR 1: PROJ: pj_obj_create: Cannot find proj.db

(Note : I have installed proj from the script given in gdal/script/vagrant)

**Comment by jratike80** [comment]
Did you read the informative message that opens from https://github.com/OSGeo/gdal/issues/new? 


> IMPORTANT: Do NOT use GitHub to post any questions or support requests!
>            They will be closed immediately and ignored.
> 
> Questions should go to the gdal-dev mailing list at
> https://lists.osgeo.org/mailman/listinfo/gdal-dev
> or other support forums. GitHub issues are for bug
> reports and suggestions for new features.

**Comment by wuyyururaviteja** [comment]
Yeah i have read it but doesn't java bindings mean able to work with any system having java. but here the files generated are unable to work without proj from what i have found. if that was needed to work then i hope it would also be bundled with the jars of libs needed. So the name of java bindings have mislead from the basic understanding i hope. So i have raised it as a issue due to difference in expected behaviour. 
Thanks if someone could consider it and help me.

**Comment by jratike80** [comment]
I suppose that the java _bindings_ work on any system having Java. My understanding about Java bindings is that they do not turn C++ libraries into Java but they offer a way to use the libraries as if they were Java. The real work is still done by the native GDAL binaries. "Native" means also that the GDAL binaries must be compiled for the architecture of the computer. So even java bindings work similarly on Linux and Windows, 32 and 64 bit, user must install the right GDAL binaries and supporting files (.dll on Windows, .so on Linux, proj.db for the CRS support) for each platform. When it comes especially to proj.db, if you have already GDAL installed you also have proj.db and you need  just tell your Java where to find it. What was said about gcs.csv in this tutorial https://geoexamples.blogspot.com/2012/05/running-gdal-java.html is probably still valid.

You may know better if "bindings" have some other meaning in Java. For me GDAL Java bindings suit well with the definition of Language Binding in Wikipedia https://en.wikipedia.org/wiki/Language_binding.

Even if I am a GDAL user who is also lurking the GDAL issues I am not a Java user nor a programmer and so not the best person to help you. Please ask your question from the mailing list.

**Comment by rouault** [comment]
Also posted on the mailing list. Closing
