### ISSUE TITLE
GDAL docker containers do not include ca certificates

### ISSUE THREAD

**Issue by blacha** [OSGeo/gdal#2101]
## Expected behavior and actual behavior.

I would like to be able to use curl to connect to https inside of osgeo/gdal:ubuntu-small-3.0.2 (or latest)

This affects everything that uses curl too, such as /vsis3/

## Steps to reproduce the problem.

```
docker run -it osgeo/gdal:ubuntu-small-3.0.2 /bin/bash

$ curl https://google.com
curl: (77) error setting certificate verify locations:
  CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs

$ gdalinfo /vsis3/foo/bar.tif
ERROR 11: HTTP response code: 0
```

Adding  `ca-certificates` to this install should fix this issue. https://github.com/OSGeo/gdal/blob/32450164707ff447612c67262b7e2829168bfbb2/gdal/docker/ubuntu-small/Dockerfile#L171

## Operating system

Docker (Ubuntu 18.04)

## GDAL version and provenance

Docker 3.0.2 imageId: f536bf51f64d

**Comment by rouault** [comment]
Pull request gladly accepted

**Comment by blacha** [comment]
Ok, will do that now.

Would you like ca-certificates inside all containers?

**Comment by rouault** [comment]
> Would you like ca-certificates inside all containers?

yes please, except for alpine-ultrasmall which doesn't have curl at all

**Comment by blacha** [comment]
> > Would you like ca-certificates inside all containers?
> 
> yes please, except for alpine-ultrasmall which doesn't have curl at all

apline-ultrasmall has libcurl https://github.com/OSGeo/gdal/blob/d441cb8d6aa95d4a38dd9b7155ab73ac602465ff/gdal/docker/alpine-ultrasmall/Dockerfile#L206

I have made a commit which adds it to all of them including ultrasmall, i could take that out.

I am just rebuilding the containers to verifies it fixes the problem.

**Comment by rouault** [comment]
> except for alpine-ultrasmall which doesn't have curl at all

Sorry I was wrong. It does have curl support

**Comment by blacha** [comment]
Interestingly, alpine installs ca-certificates automatically with curl so using the alpine images just works.
