### ISSUE TITLE
TMS: wrong origin

### ISSUE THREAD

**Issue by tobwen** [OSGeo/gdal#2126]
## Expected behavior and actual behavior.
TMS tiles can have a different origin convention (borrowed from MapProxy documentation):
```
ll or sw:
If the x=0, y=0 tile is in the lower-left/south-west corner of the tile grid. This is the default.

ul or nw:
If the x=0, y=0 tile is in the upper-left/north-west corner of the tile grid
```
GDAL's TMS minidriver allows to set `<YOrigin/>` to either _bottom_ (sw) or _top_ (nw). But it doesn't seem to work, see the current output:

Using `<YOrigin>bottom</YOrigin>`
```
Origin = (273211.253253369708546,6111822.379438250325620)
Pixel Size = (1.192992591052709,-1.192991353626315)
Image Structure Metadata:
  INTERLEAVE=PIXEL
Corner Coordinates:
Upper Left  (  273211.253, 6111822.379) (  5d26'41.81"E, 55d 6' 4.19"N)
Lower Left  (  273211.253, 5200000.000) (  6d 1'17.71"E, 46d54'53.18"N)
Upper Right (  961083.623, 6111822.379) ( 16d12'13.00"E, 54d56'21.73"N)
Lower Right (  961083.623, 5200000.000) ( 15d 2'32.44"E, 46d47'37.56"N)
Center      (  617147.438, 5655911.190) ( 10d40'15.88"E, 51d 2'34.02"N)
```

Using `<YOrigin>top</YOrigin>`
```
Origin = (273211.253253369708546,6111822.379438250325620)
Pixel Size = (1.192992591052709,-1.192991353626315)
Image Structure Metadata:
  INTERLEAVE=PIXEL
Corner Coordinates:
Upper Left  (  273211.253, 6111822.379) (  5d26'41.81"E, 55d 6' 4.19"N)
Lower Left  (  273211.253, 5200000.000) (  6d 1'17.71"E, 46d54'53.18"N)
Upper Right (  961083.623, 6111822.379) ( 16d12'13.00"E, 54d56'21.73"N)
Lower Right (  961083.623, 5200000.000) ( 15d 2'32.44"E, 46d47'37.56"N)
Center      (  617147.438, 5655911.190) ( 10d40'15.88"E, 51d 2'34.02"N)
```

This is expected:
- bottom: `Origin = (273211.2532533697, 5200000)`
- top: `Origin = (273211.2532533697, 6111822.37943825)`

The TMS itself gives this origin (see service name below):
`<Origin x="273211.2532533697" y="5200000.0"/>`

## Steps to reproduce the problem.
1. create `privat_alle_16_mbit_germany.xml` with the XML content below
2. run `gdalinfo privat_alle_16_mbit_germany.xml`
3. change `<YOrigin>bottom</YOrigin>` to `<YOrigin>top</YOrigin>` and run again

```
<GDAL_WMS>
    <Service name="TMS">
        <!-- https://mapproxy.bba.atenekom.eu/tms/1.0.0/privat_alle_16_mbit/germany -->
        <ServerUrl>https://mapproxy.bba.atenekom.eu/tms/1.0.0/privat_alle_16_mbit/germany/${z}/${x}/${y}.${format}</ServerUrl>
        <Format>png</Format>
    </Service>
    <DataWindow>
        <UpperLeftX>273211.2532533697</UpperLeftX>
        <UpperLeftY>6111822.37943825</UpperLeftY>
        <LowerRightX>961083.6232988155</LowerRightX>
        <LowerRightY>5200000.0</LowerRightY>
        <TileLevel>17</TileLevel>
        <SizeX>576594</SizeX>
        <SizeY>764316</SizeY>
        <YOrigin>bottom</YOrigin>
    </DataWindow>
    <Projection>EPSG:25832</Projection>
    <BlockSizeX>256</BlockSizeX>
    <BlockSizeY>256</BlockSizeY>
    <BandsCount>3</BandsCount>
</GDAL_WMS>
```

## Operating system
Windows 7 Professional, 64-bit

## GDAL version and provenance
v3.1.0-170 (OSGeo4W build, downloaded 2019-12-21 20:20 UTC)

**Comment by rouault** [comment]
> <YOrigin>bottom</YOrigin>

What you observe is expected. YOrigin = bottom has no effect on the corner coordinates, which are determined by the UpperLeftX/Y and LowerRightX/Y values. It only affect tile request for the {y} variable. https://github.com/OSGeo/gdal/blob/master/gdal/frmts/wms/minidriver_tms.cpp#L84

**Comment by tobwen** [comment]
The problem is that the origin is wrong.

GDAL says: `Origin = (273211.253253369708546,6111822.379438250325620)`
But is is (like the server says): `Origin = (273211.2532533697, 5200000)`

That's why all the tiles do have an offset.

**Comment by tobwen** [comment]
Here, the origin is wrong, too: https://www.orka-mv.de/geodienste/orkamv/tms/1.0.0/orkamv/epsg_25833_adv

GDAL says: `Origin = (-464849.380000000004657,6310160.139999999664724)`
Server says: `<Origin x="-464849.38" y="5057815.8685756"/>`

**Comment by jratike80** [comment]
The origin of TMS is at the lower left corner https://wiki.osgeo.org/wiki/Tile_Map_Service_Specification#TileMap_Diagram and for GDAL the origin is at the upper left corner. Origin and pixel size must be looked together, the negative pixel size means that N coordinate is decreasing to the North.

```
Origin = (273211.253253369708546,6111822.379438250325620)
Pixel Size = (1.192992591052709,-1.192991353626315)
```
Thus it is correct to take maxy as origin for the georaphic space from https://www.orka-mv.de/geodienste/orkamv/tms/1.0.0/orkamv/epsg_25833_adv

The yOrigin setting it not for TMS but for other tile services like OSM tiles as documented in https://gdal.org/drivers/raster/wms.html and it does not change the origin of the geographic space (easting-northing) but the origin of the tile space if the 0,0 tile is top or bottom and if y tile index is growing to the North or to the South.

**Comment by tobwen** [comment]
But something really seems to be wrong. When extracting an image from any TMS not being 3857, the position of the imagery is wrong. It’s slightly offset.

I have set up local MapProxy and Mailserver. Leaflet and OpenLayers set the position correctly, GDAL does not.

I will create a fake service with tiles to provide information about this bug later today.

**Comment by tobwen** [comment]
I've figured out what's really wrong here. I'm just writing a new bug report, stay tuned
