### ISSUE TITLE
gdal_merge.py docs should mention that the process is band by band

### ISSUE THREAD

**Issue by kannes** [OSGeo/gdal#2127]
In reference to https://github.com/OSGeo/gdal/issues/1827

I will add a single sentence to the summary at the top of https://gdal.org/programs/gdal_merge.html or maybe change the last sentence itself.

That should make it easier to interpret results when bands have varying NODATA regions.

**Comment by dbaston** [comment]
Resolved by https://github.com/OSGeo/gdal/pull/5231/commits/cc14b708c53bbf514ff028d4c90f0d6fee872539

**Comment by kannes** [comment]
Ha, thanks! :D
