### ISSUE TITLE
OSRGetAreaOfUse not working with a custom coordinate system

### ISSUE THREAD

**Issue by sergey-suloev** [OSGeo/gdal#2129]
hello,

I want to obtain the extent of the following coordinate system: 

PROJCS["NAD_1983_HARN_UTM_Zone_4N",GEOGCS["GCS_North_American_1983_HARN",DATUM["D_North_American_1983_HARN",SPHEROID["GRS_1980",6378137.0,298.257222101]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Transverse_Mercator"],PARAMETER["False_Easting",1640416.66666666667979],PARAMETER["False_Northing",0.0],PARAMETER["Central_Meridian",-159.0],PARAMETER["Scale_Factor",0.9996],PARAMETER["Latitude_Of_Origin",0.0],UNIT["Foot_US",0.3048006096012192]]

I am using OSRGetAreaOfUse function but it fails. Is this a GDAL bug or am I doing something wrong ?

**Comment by rouault** [comment]
> Is this a GDAL bug or am I doing something wrong ?

There is no area of use in the WKT you mention. You could possibly get one by trying to identify to which known CRS this WKT corresponds to with OSRFindMatches(), and then use OSRGetAreaOfUse() on the results

**Comment by sergey-suloev** [comment]
@rouault  thanks for answer
It seems to me that OSRGetAreaOfUse() only works with coordinate systems having EPSG identifier, correct ?

**Comment by rouault** [comment]
> with coordinate systems having EPSG identifier, correct ?

more or less. But that's not necessary sufficient. If you use a WKT with a EPSG identifier, it also needs to have a USAGE[] node as can be seen when exporting to WKT2. If it is a WKT1, it won't work out of the box, and you will have to re-import the CRS from the EPSG code using importFromEPSG()

Example of WKT2 that will work out of the box
```
PROJCRS["WGS 84 / UTM zone 32N",
    BASEGEOGCRS["WGS 84",
        DATUM["World Geodetic System 1984",
            ELLIPSOID["WGS 84",6378137,298.257223563,
                LENGTHUNIT["metre",1]]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433]],
        ID["EPSG",4326]],
    CONVERSION["UTM zone 32N",
        METHOD["Transverse Mercator",
            ID["EPSG",9807]],
        PARAMETER["Latitude of natural origin",0,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",9,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["Scale factor at natural origin",0.9996,
            SCALEUNIT["unity",1],
            ID["EPSG",8805]],
        PARAMETER["False easting",500000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["(E)",east,
            ORDER[1],
            LENGTHUNIT["metre",1]],
        AXIS["(N)",north,
            ORDER[2],
            LENGTHUNIT["metre",1]],
    USAGE[
        SCOPE["unknown"],
        AREA["World - N hemisphere - 6°E to 12°E - by country"],
        BBOX[0,6,84,12]],
    ID["EPSG",32632]]
```

**Comment by sergey-suloev** [comment]
@rouault  so either WKT has USAGE or EPSG-registered coordinate system, correct ?
