### ISSUE TITLE
Geometry Transform doesn't work

### ISSUE THREAD

**Issue by Mike0534** [OSGeo/gdal#2136]
I want to transform a geometry from wgs84 to another spatialreference。
![image](https://user-images.githubusercontent.com/25402867/71540504-5b292100-2986-11ea-9039-e35a1a7acd05.png)

Is there some change in the use of this method?

Another question:
When i use gdalwarp utility to resample a Tif which nodata is -128 and datatype is sign integer to another , found that the new one's  nodata is setted to -128 but the real value in the piexl is 128(the minus is missing). Everything else is ok.
![image](https://user-images.githubusercontent.com/25402867/71541136-063dd880-298f-11ea-80c6-2578427184bf.png)

Thx very much.

**Comment by rouault** [comment]
> Is there some change in the use of this method?

Yes, this is even indicated in the issue template : "If you think there is an issue with coordinate order in GDAL 3.0, then it is likely an intended behaviour. See https://github.com/OSGeo/gdal/issues/1974
for more explanations."

**Comment by Mike0534** [comment]
> > Is there some change in the use of this method?
> 
> Yes, this is even indicated in the issue template : "If you think there is an issue with coordinate order in GDAL 3.0, then it is likely an intended behaviour. See #1974
> for more explanations."

Sorry I missed that issue. Thank you!
