### ISSUE TITLE
gdaladdo still slow on large TIFF

### ISSUE THREAD

**Issue by clikire** [OSGeo/gdal#2147]
I'm trying to build internal overviews on a big GeoTIFF using gdaladdo and it is way too slow.

From what I could find out it is a known problem (#1442) that has been solved in May last year

However in my case it is still excruciating slow. I'm wondering what I could do wrong (I use GDAL 3.0.2 released on 28/10/2019).

I tried to generate 1 level of external overview with the following command. It lasted 68 min which is fine

`P:\>gdaladdo -ro -r average --config BIGTIFF_OVERVIEW YES --config INTERLEAVE_OVERVIEW PIXEL --config GDAL_TIFF_INTERNAL_MASK YES --config PHOTOMETRIC_OVERVIEW YCBCR --config COMPRESS_OVERVIEW JPEG --config JPEG_QUALITY_OVERVIEW 85 "C:\superorto_ext.tif" 2`

With the exact same command on the same file but with internal overviews (without the -ro switch) it lasted 6 hours and 50 min which is not so fine

`P:\>gdaladdo -r average --config BIGTIFF_OVERVIEW YES --config INTERLEAVE_OVERVIEW PIXEL --config GDAL_TIFF_INTERNAL_MASK YES --config PHOTOMETRIC_OVERVIEW YCBCR --config COMPRESS_OVERVIEW JPEG --config JPEG_QUALITY_OVERVIEW 85 "C:\superorto_ext.tif" 2`

**Comment by rouault** [comment]
https://github.com/OSGeo/gdal/issues/1442 has been fixed in the GDAL master (future 3.1.0) branch, after GDAL 3.0 has been branched
