### ISSUE TITLE
WKT Parser overly-strict handling whitespace

### ISSUE THREAD

**Issue by abellgithub** [OSGeo/gdal#2149]
## Expected behavior and actual behavior.

The WKT specification is vague at best WRT whitespace as token separators.  GDAL only accepts the space and tab as whitespace when parsing WKT (see OGRWktReadToken).  The specification makes no mention of tabs, and while it defines a <space> production in the BNF, doesn't use it.  Table 6 in section 7.6.2 implies that newlines (or similar) are acceptable, but no mention of this is made in the BNF.

Given the ambiguity in the specification and GDAL's current practice of accepting tabs, I would like to see the GDAL WKT parser accept all whitespace as token separators.

## GDAL version and provenance

3.0 and earlier

**Comment by rouault** [comment]
I assume you speak about geometry WKT, not CRS WKT ? Your proposal sounds reasonable. Feel free to submit a PR.

**Comment by abellgithub** [comment]
Yes, geometry WKT.  I'll submit a PR.

**Comment by rouault** [comment]
any news on this ?

**Comment by jratike80** [comment]
Waiting feedback for a few more days before closing.

**Comment by jratike80** [comment]
Closing.
