### ISSUE TITLE
Make OLCStringsAsUTF8 true for GeoJSON

### ISSUE THREAD

**Issue by sgillies** [OSGeo/gdal#2151]
## Expected behavior and actual behavior.

GeoJSON layers should advertise UTF-8 strings (OLCStringsAsUTF8 as True) but they do not. The GeoJSON layer's capability testing delegates to the MEM driver, which does not advertise UTF-8 strings.

Theoretically, a GeoJSON file might be UTF-16 or UTF-32, but these are very rare and only weakly interoperable. By advertising UTF-8, the GeoJSON driver can help applications (like Fiona, see https://github.com/Toblerity/Fiona/blob/maint-1.8/fiona/ogrext.pyx#L544-L569) try to do the right thing with respect to data encoding.

**Comment by rouault** [comment]
Want try a PR ? Just edit OGRGeoJSONLayer::TestCapability() in ogr/ogrsf_frmts/geojson/ogrgeojsonlayer.cpp
