### ISSUE TITLE
gdal2tiles zoom level range should be independent of zoom level order

### ISSUE THREAD

**Issue by daniel-j-h** [OSGeo/gdal#2161]
The zoom level range option in gdal2tiles expects an ordering of: (low number, high number)

When users invoke gdal2tiles as in

    gdal2tiles.py -z 14-5 ..

they will get a single zoom level 5 directory - which is unexpected.

Instead the correct way would have been

    gdal2tiles.py -z 5-14 ..

This is easy to mix up and it would be great to
- either error out, or
- just flip min, max ourselves

Location where this is happening seems to be here

https://github.com/OSGeo/gdal/blob/ecdba6e8551c5bebcc8412392b2ea78095b94931/gdal/swig/python/scripts/gdal2tiles.py#L1427-L1438

GDAL 2.4.2, released 2019/06/28

**Comment by jratike80** [comment]
I think it would better to give an errror "max value smaller than min value" and stop. Syntax seems to be correctly documented in https://gdal.org/programs/gdal2tiles.html#gdal2tiles: `Zoom levels to render (format:‘2-5’ or ‘10’)`. There are certainly many range parameters (extent, scale,...) also in other GDAL programs and I don't think it makes sense to make GDAL to guess what user really means. But as a user I do appreciate explicit error messages.
