### ISSUE TITLE
Docker Image does not contain FlatGeoBuf

### ISSUE THREAD

**Issue by aaime** [OSGeo/gdal#2172]
## Expected behavior and actual behavior.

The documentation reports FlatGeoBuf as available since GDAL 3.1: https://gdal.org/drivers/vector/flatgeobuf.html
However the latest docker image does not contain it, despite being a 3.1. I'm guessing it has not been compiled in.

It would be great if it was, would allow easier testing of FlatGeoBuf without having to build from sources.

## Steps to reproduce the problem.

```
docker run --rm -v /home:/home osgeo/gdal:alpine-small-latest ogrinfo --version
GDAL 3.1.0dev-6d5d00851c24c25b4d814305cc5d4122ce72b4bc, released 2019/07/07

docker run --rm -v /home:/home osgeo/gdal:alpine-small-latest ogrinfo --formats | grep -i FlatGeobuf
-- no output, un matched
```

## Operating system

Latest ``osgeo/gdal:alpine-small-latest`` docker image

## GDAL version and provenance

GDAL 3.1.0dev-6d5d00851c24c25b4d814305cc5d4122ce72b4bc

**Comment by rouault** [comment]
> released 2019/07/07

That's a bit old for a driver that was merged after that date ;-)

You'd be better with
```
$ docker run --rm -v /home:/home osgeo/gdal:alpine-small-latest ogrinfo --version
GDAL 3.1.0dev-84d972714a80fa019fd11f53b86fa3d5eb2db6c6, released 2019/12/31

$ docker run --rm -v /home:/home osgeo/gdal:alpine-small-latest ogrinfo --formats | grep -i FlatGeobuf
  FlatGeobuf -vector- (rw+v): FlatGeobuf
```

**Comment by aaime** [comment]
Duh, my mistake, I did a docker pull of "latest" and then used "alpin-small-latest" in the interactive command runs (the latter was not pulled...). Works fine now, sorry for the noise.
