### ISSUE TITLE
Loses link against libxml2 with 2.9.10 (uses xml2-config)

### ISSUE THREAD

**Issue by sebastic** [OSGeo/gdal#2173]
As reported by Mattia Rizzolo in [Debian Bug #949167](https://bugs.debian.org/949167):
> Your package is using `xml2-config` to detect and use libxml2.  I'm
> removing that script, so please update your build system to use
> pkg-config instead.
>
> Additionally, your package is not failing to build, so it's creating
> binaries that are not linked against libxml2 anymore:
> ```
> Control files of package libgdal-dev: lines which differ (wdiff format)
> -----------------------------------------------------------------------
> Installed-Size: [-49905-] {+49850+}
>
> Control files of package libgdal26: lines which differ (wdiff format)
> ---------------------------------------------------------------------
> Depends: gdal-data (>= 3.0.3+dfsg-1), libarmadillo9 (>= 1:9.800.1+dfsg), libc6 (>= 2.29), libcfitsio8 (>= 3.470~), libcharls2 (>= 2.0.0+dfsg), libcurl3-gnutls (>= 7.56.1), libdap25 (>= 3.20.4), libdapclient6v5 (>= 3.20.4), libepsilon1 (>= 0.8.1), libexpat1 (>= 2.0.1), libfreexl1 (>= 0.0.2~beta20110817), libfyba0, libgcc1 (>= 1:4.2), libgeos-c1v5 (>= 3.8.0), libgeotiff5 (>= 1.5.0), libgif7 (>= 5.1), libhdf4-0-alt (>= 4.2r4), libhdf5-103, libjpeg62-turbo (>= 1.3.1), libjson-c4 (>= 0.13.1), libkmlbase1 (>= 1.3.0~rc0-3), libkmldom1 (>= 1.3.0~rc2), libkmlengine1 (>= 1.3.0~rc0-3), libmariadb3 (>= 3.0.0), libnetcdf13 (>= 1:4.0.0), libodbc1 (>= 2.3.1), libogdi4.1 (>= 3.2.0), libopenjp2-7 (>= 2.2.0), libpcre3, libpng16-16 (>= 1.6.2-1), libpoppler82 (>= 0.71.0), libpq5, libproj15 (>= 6.0.0), libqhull7, libspatialite7 (>= 4.3.0-3~), libstdc++6 (>= 9), libtiff5 (>= 4.0.8), libwebp6 (>= 0.5.1), libxerces-c3.2, [-libxml2 (>= 2.7.4),-] odbcinst1debian2 (>= 2.3.1), zlib1g (>= 1:1.2.2)
> Installed-Size: [-20385-] {+20353+}
> ```
> The libxml2 package in experimental already doesn't ship the xml2-config
> script.
>
> Attached is the full build log, hopefully relevant excerpt follows:
>
> ```
> checking for xml2-config... no
> ...
>   libxml2 support:           no
> ```

**Comment by rouault** [comment]
Fixed per https://github.com/OSGeo/gdal/commit/bfdf002a53e4ef7ce935b365c4490c96dee6f605
