### ISSUE TITLE
GPKG: datetime lost if not stored as ISO-8601 date/time strings

### ISSUE THREAD

**Issue by jratike80** [OSGeo/gdal#2183]
Source data:
ftp://download-open.lantmateriet.se/GEO-tester/Kartdata/Ers%C3%A4ttare_fastighetskartan/Testversion_01/mark_7453500_730500_v01.gpkg

Table "mark" is created as
`CREATE TABLE "mark" ( "fid" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "geom" GEOMETRY, "objektidentitet" TEXT, "giltigfran" DATETIME, "giltigtill" DATETIME, "lagesosakerhetplan" REAL, "lagesosakerhethojd" REAL, "matmetodplan" TEXT, "matmetodhojd" TEXT, "ursprorganisation" TEXT, "namn" TEXT, "objektversion" MEDIUMINT, "objekttypnummer" MEDIUMINT, "objekttyp" TEXT, "vattenytaid" TEXT, "hojd_over_havet" TEXT, "reglerat_vatten" TEXT)`

Data into fields "giltigfran" and "giltigtill" are stored as strings (perhaps ESRI style?)
`2018/02/13 23:59:59+01`

GDAL does not see these fields at all
```

ogrinfo -sql "select * from mark limit 1" mark_7453500_730500_v01.gpkg
INFO: Open of `mark_7453500_730500_v01.gpkg'
      using driver `GPKG' successful.

Layer name: SELECT
Geometry: Unknown (any)
Feature Count: 1
Extent: (730500.000000, 7455265.299000) - (730606.833000, 7455351.664000)
Layer SRS WKT:
...
FID Column = fid
Geometry Column = geom
objektidentitet: String (0.0)
giltigfran: DateTime (0.0)
giltigtill: DateTime (0.0)
lagesosakerhetplan: Real (0.0)
lagesosakerhethojd: Real (0.0)
matmetodplan: String (0.0)
matmetodhojd: String (0.0)
ursprorganisation: String (0.0)
namn: String (0.0)
objektversion: Integer (0.0)
objekttypnummer: Integer (0.0)
objekttyp: String (0.0)
vattenytaid: String (0.0)
hojd_over_havet: String (0.0)
reglerat_vatten: String (0.0)
OGRFeature(SELECT):0
  objektidentitet (String) = 6e9374d6-22b4-4fcd-8af2-014276805507
->two fields missing here
  lagesosakerhetplan (Real) = 0.6
  lagesosakerhethojd (Real) = 1
  matmetodplan (String) = Fotogr. Analytisk
...
```
It might be better to cast non-ISO time strings into text than to drop data.

**Comment by rouault** [comment]
> Data into fields "giltigfran" and "giltigtill" are stored as strings (perhaps ESRI style?)
> `2018/02/13 23:59:59+01`

Hum, that's actually the default format used by GDAL when formatting OFTDateTime fields into strings, but GDAL will not write this, normally...

> It might be better to cast non-ISO time strings into text than to drop data.

A bit hard, because that would require analyzing row content to determine field types. It would be easier here to recognize this string formatting as date time. But perhaps even better ask the data producer how they created that and if they could fix it, as it is invalid GeoPackage

**Comment by jratike80** [comment]
I was not sure if the formatting of datetime applies to feature tables. The datetime format is certainly fixed for the metadata tables in table 4, But probably it is done via "Table 1. GeoPackage Data Types" that defines datetime as "ISO-8601 date/time string in the form YYYY-MM-DDTHH:MM:SS.SSSZ with T separator character and Z suffix for coordinated universal time (UTC) encoded in either UTF-8 or UTF-16. See TEXT. Stored as SQLite TEXT." 
So if data provider wants to use such strings they should change the data type into TEXT. Do you agree?

**Comment by rouault** [comment]
>  probably it is done via "Table 1. GeoPackage Data Types"

yes, that's what I apply here

> So if data provider wants to use such strings they should change the data type into TEXT. Do you agree?

Yes, that's a possibility, but as the intent is to have a datetime, I'd rather say modify the content to be a ISO-8601 string conforming to table 1.

**Comment by jratike80** [comment]
Consider if there is anything to do or close the issue. Geopackage is not correct to the standard but all regular SQLite tools do see the strings because they are OK for SQLite. Silently turning the contents of the fields into nulls makes even experienced users to scratch their heads for a while and  debugging requires third party tools.

**Comment by jratike80** [comment]
Is it so that validate_gpkg.py does not validate the integrity of data except for geometries? There is something that could be tested, even it might be rather heavy and goes over the requirements of the Geopackage standard
- that dates/datetimes are ISO-8601 formatted or nulls
- that booleans are either null, 0, or 1
- that numeric fields does not contain text or numbers which too large to the defined type
- maybe more
Those are now just supposed to be correct in the data without testing and gpkg_data_column_constraints mainly give a way to constraint more.

**Comment by rouault** [comment]
> There is something that could be tested

I've given the file a try at OGC Cite testing, and it reports a similar issue as GDAL validate_gpkg, regarding geometry envelopes, but nothing regarding the content. I'm not sure if there's a formal requirement regarding the consistency of the content with the column declaration. That said, validate_gpkg could indeed potentially do more

**Comment by heidivanparys** [comment]
> I'm not sure if there's a formal requirement regarding the consistency of the content with the column declaration.

This should be clarified when opengeospatial/geopackage#530 is resolved.
