### ISSUE TITLE
gdalinfo not working on Mageia

### ISSUE THREAD

**Issue by david-geiger** [OSGeo/gdal#2188]
Hi,

On Mageia we have an issue with gdalinfo (and some others scripts), during build it creates a bash script instead of a real binary, I checked what is going wrong but without success:

$ gdalinfo --version
/usr/bin/gdalinfo: error: '/usr/bin/.libs/gdalinfo' does not exist

Mageia7 and Mageia Cauldron
gdal 2.4.3

https://bugs.mageia.org/show_bug.cgi?id=25809#c3

Here our spec file:

http://svnweb.mageia.org/packages/cauldron/gdal/current/SPECS/gdal.spec?revision=1478884&view=markup

**Comment by jratike80** [comment]
If you have not identified a bug in GDAL then it would be better to send a question to gdal-dev mailing list. There was a notice on the page that you used for creating a new ticket:

IMPORTANT: Do NOT use GitHub to post any questions or support requests!

**Comment by rouault** [comment]
Looks like a Mageia specific issue, unless proven otherwise
