### ISSUE TITLE
gdalinfo metadata reports lats <-> longs when using a driver that depends on .aux.xml metadata

### ISSUE THREAD

**Issue by normanb** [OSGeo/gdal#2195]
## Expected behavior and actual behavior.

Related issue - https://github.com/OSGeo/gdal/issues/2091

Using `gdalinfo` with any GDAL files that use `.aux.xml` metadata results in the LL corners being swapped between latitude and longitude. The source corners are reported correctly so this is relatively minor.

This was first reported by @djhoese as an issue with the TileDB driver in https://github.com/OSGeo/gdal/issues/2091

## Steps to reproduce the problem.

```
wget https://download.osgeo.org/geotiff/samples/spot/chicago/UTM2GTIF.TIF
gdalinfo UTM2GTIF.TIF # note LL corners
:
Corner Coordinates:
Upper Left  (  444650.000, 4640510.000) ( 87d40' 2.80"W, 41d54'59.49"N)
Lower Left  (  444650.000, 4631220.000) ( 87d39'59.67"W, 41d49'58.28"N)
Upper Right (  451640.000, 4640510.000) ( 87d34'59.37"W, 41d55' 1.14"N)
Lower Right (  451640.000, 4631220.000) ( 87d34'56.64"W, 41d49'59.92"N)
Center      (  448145.000, 4635865.000) ( 87d37'29.62"W, 41d52'29.73"N)
```
```
gdal_translate -OF JPEG UTM2GTIF.TIF out.jpg
gdalinfo out.jpg # note LL corners
Corner Coordinates:
Upper Left  (  444650.000, 4640510.000) ( 41d54'59.49"E, 87d40' 2.80"S)
Lower Left  (  444650.000, 4631220.000) ( 41d49'58.28"E, 87d39'59.67"S)
Upper Right (  451640.000, 4640510.000) ( 41d55' 1.14"E, 87d34'59.37"S)
Lower Right (  451640.000, 4631220.000) ( 41d49'59.92"E, 87d34'56.64"S)
Center      (  448145.000, 4635865.000) ( 41d52'29.73"E, 87d37'29.62"S)
```

## GDAL version and provenance

GDAL 3.x

I can get to looking at this as part of the maintenance of the TileDB driver but cc @rouault in case there is a quick fix that you know of.

**Comment by rouault** [comment]
Probably some OGRSpatialReference::SetAxisMappingStrategy(OAMS_TRADITIONAL_GIS_ORDER) call missing somewhere

**Comment by rouault** [comment]
@normanb Fixed per https://github.com/OSGeo/gdal/commit/18bfbd32302f611bde0832f61ca0747d4c4421dd. I'd bet this will fix the issue reported in TileDB. I let you check that part
