### ISSUE TITLE
PG support depends on optional PGDump driver

### ISSUE THREAD

**Issue by rcoup** [OSGeo/gdal#2197]
## Expected behavior and actual behavior.

Adding postgres back after disabling all optional drivers doesn't build.

## Steps to reproduce the problem.

`./configure --disable-all-optional-drivers --with-pg` configures correctly, but fails to link into libgdal:

```
Undefined symbols for architecture x86_64:
  "OGRPGCommonLaunderName(char const*, char const*)", referenced from:
      OGRPGDataSource::ICreateLayer(char const*, OGRSpatialReference*, OGRwkbGeometryType, char**) in ogrpgdatasource.o
      OGRPGTableLayer::CreateField(OGRFieldDefn*, int) in ogrpgtablelayer.o
      OGRPGTableLayer::CreateGeomField(OGRGeomFieldDefn*, int) in ogrpgtablelayer.o
      OGRPGTableLayer::AlterFieldDefn(int, OGRFieldDefn*, int) in ogrpgtablelayer.o
  "OGRPGCommonLayerGetType(OGRFieldDefn&, bool, bool)", referenced from:
      OGRPGTableLayer::CreateField(OGRFieldDefn*, int) in ogrpgtablelayer.o
      OGRPGTableLayer::AlterFieldDefn(int, OGRFieldDefn*, int) in ogrpgtablelayer.o
  "OGRPGCommonLayerSetType(OGRFieldDefn&, char const*, char const*, int)", referenced from:
      OGRPGTableLayer::ReadTableDefinition() in ogrpgtablelayer.o
  "OGRPGCommonAppendFieldValue(CPLString&, OGRFeature*, int, CPLString (*)(void*, char const*, int, char const*, char const*), void*)", referenced from:
      OGRPGTableLayer::ISetFeature(OGRFeature*) in ogrpgtablelayer.o
      OGRPGTableLayer::CreateFeatureViaInsert(OGRFeature*) in ogrpgtablelayer.o
  "OGRPGCommonLayerGetPGDefault(OGRFieldDefn*)", referenced from:
      OGRPGTableLayer::CreateField(OGRFieldDefn*, int) in ogrpgtablelayer.o
      OGRPGTableLayer::AlterFieldDefn(int, OGRFieldDefn*, int) in ogrpgtablelayer.o
  "OGRPGCommonLayerNormalizeDefault(OGRFieldDefn*, char const*)", referenced from:
      OGRPGTableLayer::ReadTableDefinition() in ogrpgtablelayer.o
  "OGRPGCommonAppendCopyFieldsExceptGeom(CPLString&, OGRFeature*, char const*, bool, CPLString (*)(void*, char const*, int, char const*, char const*), void*)", referenced from:
      OGRPGTableLayer::CreateFeatureViaCopy(OGRFeature*) in ogrpgtablelayer.o
ld: symbol(s) not found for architecture x86_64
```

`OGRPGCommon*` lives in `ogr/ogrsf_frmts/pgdump/`.

Running `./configure --disable-all-optional-drivers --with-pg --with-pgdump` builds correctly.

## Operating system

MacOS 10.15.2

## GDAL version and provenance

master @ c1f8e0d2

**Comment by rouault** [comment]
--disable-all-optional-drivers should be considered as an experimental/advanced feature. It clearly doesn't capture inter driver dependencies.

**Comment by rcoup** [comment]
I'm working through some minimal-build stuff at the moment so I might encounter a few more things:

1. should I make this a placeholder ticket for some of these issues?
2. is there a way to specify driver inter-dependencies at the moment that PG/PGDump can implement?

**Comment by rouault** [comment]
>     2\. is there a way to specify driver inter-dependencies at the moment that PG/PGDump can implement?

Should perhaps be some tuning of configure.ac to detect that if PG is enabled, then PGDump must also be enabled.

**Comment by rouault** [comment]
closing as configure has been removed and replaced by cmake
