### ISSUE TITLE
maximum number of samples exceeded (75000000 > 67108864) error: cannot decode code stream

### ISSUE THREAD

**Issue by ATNC** [OSGeo/gdal#2198]
## Expected behavior and actual behavior.

 I expected to be able to gdal_translate this raster [file](https://we.tl/t-fY2Ybu3vPw) and it returns an error message `maximum number of samples exceeded (75000000 > 67108864)
error: cannot decode code stream
0ERROR 1: output_8_4.jp2, band 1: IReadBlock failed at X offset 0, Y offset 0
`

I have this error with a different jp2 files.

## Steps to reproduce the problem.

"gdal_translate -of GTIFF output_8_4.jp2 res.tiff"

## Operating system

macOS Catalina 10.15.2 

## GDAL version and provenance

GDAL 2.4.2, released 2019/06/28

**Comment by rouault** [comment]
This is a defect of the Jasper library used by the JPEG2000 driver. Use a GDAL build using openjpeg to enable the JP2OpenJPEG driver. I've verified this image is decoded fine with it.

**Comment by ATNC** [comment]
@rouault  Thanks a lot!

**Comment by arattari** [comment]
> This is a defect of the Jasper library used by the JPEG2000 driver. Use a GDAL build using openjpeg to enable the JP2OpenJPEG driver. I've verified this image is decoded fine with it.

@rouault, How do I build GDAL to use openjpeg? I'm also getting the max number of sample error.
