### ISSUE TITLE
Error in the raster_api_tut.rst documentation file

### ISSUE THREAD

**Issue by alex1442** [OSGeo/gdal#2199]
in the python example section of this file:
https://github.com/OSGeo/gdal/blob/master/gdal/doc/source/tutorials/raster_api_tut.rst#techniques-for-creating-files
incorrect duplication in the if condition

```
if metadata.get(gdal.DCAP_CREATE) == "YES":
    print("Driver {} supports Create() method.".format(fileformat))

if metadata.get(gdal.DCAP_CREATE) == "YES": # DCAP_CREATE instead DCAP_CREATECOPY
    print("Driver {} supports CreateCopy() method.".format(fileformat))
```

**Comment by rouault** [comment]
Can you directly propose the correction as a pull request with https://github.com/OSGeo/gdal/edit//master/gdal/doc/source/tutorials/raster_api_tut.rst ?
