### ISSUE TITLE
Consistance error when trying to install gdal.  

### ISSUE THREAD

**Issue by OldSubSailor** [OSGeo/gdal#2204]
This has been going on for over a month.  The pip folks to me to contact you.
[pip error Jan 31.txt](https://github.com/OSGeo/gdal/files/4139990/pip.error.Jan.31.txt)

**Comment by rcoup** [comment]
Please don't ignore the issue template, is it there for a reason.

You're building the GDAL 3.0 Python code against GDAL 2.4.2 you have installed via Homebrew. I'd suggest using [pygdal](https://pypi.org/project/pygdal/) via `pip install pygdal=="$(gdal-config --version).*"` to make sure the Python code version matches the library version you have installed.

**Comment by rouault** [comment]
The reason of the error can be seen in the log
```
Collecting gdal
  Using cached GDAL-3.0.4.tar.gz (577 kB)
[...]
-I/usr/local/Cellar/gdal/2.4.2_5/include
```

So you're trying to fetch the Python bindings of GDAL 3.0.4 but have only GDAL 2.4.2 has a native library. Either upgrade your native library, or downgrade your GDAL Python package to 2.4.2 (pip install gdal==2.4.2)

**Comment by OldSubSailor** [comment]
Thank you. 
Please understand that all this is over my 72 year old head.  I sure could use a left foot, right foot instruction. 
Will deleting the home-brew install help in any manner.  
Upgrade native library?

**Comment by rouault** [comment]
@rcoup  Do you know what pygdal does exactly which is different from the plain gdal package ?

**Comment by OldSubSailor** [comment]
Not a bit.  I am just trying to get gdal to work with the usgs meshes available in Ortho4xp. 
Other Mac users are having the same issues, so I am just trying to get the methodology corrected and the fix posted on the forum.

**Comment by OldSubSailor** [comment]
Installing 2.4.2 worked!!
Thank you.
Would you mind if I gave you both credit for this fix in the forum post?

**Comment by OldSubSailor** [comment]
We are trying to get the Macintosh install for Ortho4xp current (python 3.8) I and easy to do.
I entered 
pip install pygdal=="$(gdal-config --version).*"
and attached the results. 
[did I do it right.txt](https://github.com/OSGeo/gdal/files/4226214/did.I.do.it.right.txt)

I have been messing with the install and did not use home brew to install python(3.7) nor gdal.
So how can I get things done as per your comments:
"So you're trying to fetch the Python bindings of GDAL 3.0.4 but have only GDAL 2.4.2 has a native library. Either upgrade your native library, or downgrade your GDAL Python package to 2.4.2 (pip install gdal==2.4.2)"
Native library (where is that located?)  upgrade etc.
Thank you
