### ISSUE TITLE
Broken link for MSG driver & opportunity to integrate underlying library more seamlessly

### ISSUE THREAD

**Issue by erget** [OSGeo/gdal#2205]
## Expected behavior and actual behavior.

https://gdal.org/drivers/raster/msg.html states that the Public Wavelet Transform Decompression Library software is licensed and free to download. This has now been updated:
1. The library is found under a [a new link](https://gitlab.eumetsat.int/open-source/PublicDecompWT)
1. It's got a FOSS license so it could be integrated directly into GDAL

That means that the link in the GDAL docs is broken, and also that there is the opportunity to pull in the library automatically. As it stands users can no longer download the library from the referenced link, so at minimum the link should be updated but I think we can do better than that so that users can install GDAL with MSG support without having to do gymnastics to acquire the EUMETSAT library.

I'm happy to update the doc. Is anybody interested in integrating the library now more tightly into GDAL? I'm not sure I'll be able to do that any time soon due to time constraints.

## Steps to reproduce the problem.

Try to install the MSG driver using the existing instructions ;)

## Operating system

All.

## GDAL version and provenance

Latest

**Comment by rouault** [comment]
Thanks for the note. Feel free to propose a document update with the "Edit on GitHub" link at the top right of the page

**Comment by NikosAlexandris** [comment]
Is #2213 related to this #2205?

**Comment by erget** [comment]
It looks like indirectly - AFAIK you would also have gotten this error before the change I described above. [The MSG driver doc](https://gdal.org/drivers/raster/msg.html) stipulates that you if you configure `--with-msg` you need to manually download the source codes. So it's never been seamless in the past - the only difference now is that it _could_ be seamless if we want to make it that ;)

**Comment by NikosAlexandris** [comment]
> It looks like indirectly - AFAIK you would also have gotten this error before the change I described above. [The MSG driver doc](https://gdal.org/drivers/raster/msg.html) stipulates that you if you configure `--with-msg` you need to manually download the source codes. So it's never been seamless in the past - the only difference now is that it _could_ be seamless if we want to make it that ;)

Thanks. I've seen that the `frmts/msg` directory contains a few files named after
`PublicDecompWT..` and guessed that the "decompression" library is already present.

See, the `PublicDecompWT_headers.h` file references the `CWTDecoder.h` header:
```
grep -n CWTDecoder.h PublicDecompWT_headers.h
5:#include "PublicDecompWT/COMP/WT/Inc/CWTDecoder.h"
```

**Comment by NikosAlexandris** [comment]
By the way, the link [Public Wavelet Transform Decompression Library Software](https://www.eumetsat.int/Home/Main/Access_to_Data/User_Support/SP_1117714787347) in the [MSG driver documentation](https://gdal.org/drivers/raster/msg.html) is broken.

**Comment by rouault** [comment]
@erget Regarding a potenitial seamless integration, I'd say that a requirement would be first that https://gitlab.eumetsat.int/open-source/PublicDecompWT has a more standard build system, typically autoconf+automake or cmake based, and in particular with a "make install" target that would install headers in ${install_prefix}/include, static & dynamic libraries in ${install_prefix}/lib, provide a pkg-config file, etc.

**Comment by erget** [comment]
@rouault understood, as the library is supported on a best-effort basis I don't see us making those changes in the near-term but I'll at least send a PR to get the link right.
