### ISSUE TITLE
CSVGetNextLine never returns valid data

### ISSUE THREAD

**Issue by sergey-suloev** [OSGeo/gdal#2231]
CSVGetNextLine never returns valid data because psTable->nLineCount  is always == 0. 
The one could probably call CSVIngest function prior to CSVGetNextLine  in order to initialize the context but CSVIngest is declared static.

**Comment by rouault** [comment]
CSVGetNextLine() is never used in GDAL code base as far as I can see. Do you use it in your own code ? I'd suggest you propose a pull request with a fix.

**Comment by jratike80** [comment]
Nothing found with https://github.com/OSGeo/gdal/search?q=*getnextline*&unscoped_q=*getnextline*
There is GetNextLineTokens() in 
https://github.com/OSGeo/gdal/blob/master/gdal/ogr/ogrsf_frmts/csv/ogrcsvlayer.cpp
but that does not feel the same. Pleas clarify.

**Comment by sergey-suloev** [comment]
@jratike80  clarify what ?  
the function is located here https://github.com/OSGeo/gdal/blob/56fb9f9986a5f28997ebdfb18d9dcb960eb0ea74/gdal/port/cpl_csv.cpp#L972

**Comment by sergey-suloev** [comment]
@rouault  ok that works for me

**Comment by jratike80** [comment]
@sergey-suloev , that was perfect clarification. I thought that my search from GitHub would have found it but search query requires exact term as a query parameter
https://github.com/OSGeo/gdal/search?q=CSVGetNextLine&unscoped_q=CSVGetNextLine
