### ISSUE TITLE
Pixels shift when resampling using "average" or "Lanczos"

### ISSUE THREAD

**Issue by rzinke** [OSGeo/gdal#2235]
## Expected behavior and actual behavior.

Expected behavior: When downsampling using gdalwarp with the averaging or Lanczos kernel options selected, I would expect the data to become smoother (as it does), and for the locations of map features (e.g., peaks and valleys) to remain at the same locations they were in before the resampling was applied. 

Actual behavior: The positions of peaks and valleys seem to shift by ~1 pixel when resampling is applied. This effect is difficult to notice when comparing images resampled by the "average" algorithm side-by-side with those sampled by the "Lanczos" algorithm. However, when the two images over overlain on top of one another, as in QGIS for instance, and the top image is flipped on and off, the locations of the pixels appear to shift N-S and/or or E-W. 

## Steps to reproduce the problem.
To test the problem, I downloaded a radar interferogram and resampled it using the "average" and "Lanczos" algorithms, with varying resolutions. This process can be followed using the commands below. 

wget https://aria-products.jpl.nasa.gov/search/dataset/grq_v2.0.2_s1-gunw-released/S1-GUNW-A-R-041-tops-20200122_20191229-115937-36109N_34063N-PP-f9aa-v2_0_2/S1-GUNW-A-R-041-tops-20200122_20191229-115937-36109N_34063N-PP-f9aa-v2_0_2.nc

Navigate to the download folder...

Extract unfiltered image:
gdal_translate NETCDF:"S1-GUNW-A-R-041-tops-20200122_20191229-115937-36109N_34063N-PP-f9aa-v2_0_2.nc":/science/grids/data/unwrappedPhase FullRes.tif

Warp using different resampling kernels and different downsampling factors:
gdalwarp -r average -tr 0.000833333333333 0.000833333333333 FullRes.tif Average1.tif
gdalwarp -r lanczos -tr 0.000833333333333 0.000833333333333 FullRes.tif Lanczos1.tif

gdalwarp -r average -tr 0.001666666666666 0.001666666666666 FullRes.tif Average2.tif
gdalwarp -r lanczos -tr 0.001666666666666 0.001666666666666 FullRes.tif Lanczos2.tif

gdalwarp -r average -tr 0.002499999999999 0.002499999999999 FullRes.tif Average3.tif
gdalwarp -r lanczos -tr 0.002499999999999 0.002499999999999 FullRes.tif Lanczos3.tif

gdalwarp -r average -tr 0.003333333333332 0.003333333333332 FullRes.tif Average4.tif
gdalwarp -r lanczos -tr 0.003333333333332 0.003333333333332 FullRes.tif Lanczos4.tif

gdalwarp -r average -tr 0.004166666666665 0.004166666666665 FullRes.tif Average5.tif
gdalwarp -r lanczos -tr 0.004166666666665 0.004166666666665 FullRes.tif Lanczos5.tif

Then, open the images so they can be viewed, one on top of another, and flip the top image on and off. The locations of features on the map should appear to shift back and forth depending on which image is on top. 

To really see this effect, I suggest clipping the image values between -2 and 4. 

## Operating system

I have tested this using MacOSX 10.14.6 Mojave and Linux version 3.10.0-957.21.3.el7.x86_64. 

## GDAL version and provenance

Tested using gdal versions 3.0.1 (Mac) and 3.0.4 (Linux).

**Comment by rouault** [comment]
Average is known to have potential sub-pixel shift. Lanczos should be OK

**Comment by rzinke** [comment]
@rouault many thanks for you quick response!

**Comment by jratike80** [comment]
I do not know what is "box" resampling. The supported methods are documented in https://gdal.org/en/stable/programs/gdalwarp.html.
Anyway, this issue was marked as fixed 4 years ago so maybe you are not talking about the same thing.
