### ISSUE TITLE
GDAL 3.x C# Install / Configuration Steps

### ISSUE THREAD

**Issue by aicukltd** [OSGeo/gdal#2236]
Hey,

Apologies if this is the wrong place to post this or it is a stupid question, however I am attempting to upgrade to GDAL 3.x in one of my C# NET Standard projects from 2.4.3. 

I have been previously using the GDAL NuGet packages however, they do not currently support the 3.x release of GDAL. 

Is there something I’m missing as to configuring GDAL manually?

Am I able to download the compiled binaries and reference the C# DLLs or is there some configuration I’m obviously missing?

**Comment by rouault** [comment]
Not a stupid question, but as indicated in the issue template, this is not the place to ask questions.
