### ISSUE TITLE
Converting PostGIS table with timestamp field to GPKG with ogr2ogr

### ISSUE THREAD

**Issue by arbakker** [OSGeo/gdal#2247]
Hi, I am having some trouble converting a PostGIS table containing a timestamp field to a GPKG with ogr2ogr. The timestamp field in the PostGIS table is formatted like `2006-03-15 00:00:00`. 

My first failed attempt was a plain ogr2ogr command to convert the data; the vliegdatum field in the resulting GPKG is filled with null values:

```
ogr2ogr -f GPKG vlieglijnen.gpkg "$PG_CONN_STRING" -sql "select vliegdatum, geom from ahn1_25m.vlieglijnen" -nln "vlieglijnen"
```

Then I tried to cast the field to a ogr2ogr DATETIME type, unfortunately this did not work; the GPKG is generated but the `vliegdatum` contains only null values again. If I cast the field to TEXT type the vliegdatum field is filled with the expected values, but I want a DATETIME field type. 

```bash
ogr2ogr -f GPKG vlieglijnen.gpkg "$PG_CONN_STRING" -sql "select CAST(vliegdatum as DATETIME) as vliegdatum, geom from ahn1_25m.vlieglijnen" -nln "vlieglijnen"
ogr2ogr -f GPKG vlieglijnen.gpkg "$PG_CONN_STRING" -sql "select CAST(vliegdatum as TEXT) as vliegdatum, geom from ahn1_25m.vlieglijnen" -nln "vlieglijnen"
```

Then I figured out that the DATETIME type in GPKG is just a ISO-8601 date/time string in the form YYYY-MM-DDTHH:MM:SS.SSSZ stored as TEXT. So I tried the following with the same result as previously; `vliegdatum` only contains null values yet again. When I cast to TEXT it works fine, but again this is not the type I want:

```bash
ogr2ogr -f GPKG vlieglijnen.gpkg "$PG_CONN_STRING" -sql "select CAST(NULLIF(concat(to_json(vliegdatum)#>>'{}','Z'),'Z') AS DATETIME) as vliegdatum, geom from ahn1_25m.vlieglijnen" -nln "vlieglijnen"
ogr2ogr -f GPKG vlieglijnen.gpkg "$PG_CONN_STRING" -sql "select CAST(NULLIF(concat(to_json(vliegdatum)#>>'{}','Z'),'Z') AS TEXT) as vliegdatum, geom from ahn1_25m.vlieglijnen" -nln "vlieglijnen"
```

To my suprise I could generate a GPKG with DATETIME with the following steps:

```bash
ogr2ogr -f GPKG vlieglijnen.gpkg "$PG_CONN_STRING" -sql "select CAST(NULLIF(concat(to_json(vliegdatum)#>>'{}','Z'),'Z') AS TEXT) as vliegdatum, geom from ahn1_25m.vlieglijnen" -nln "vlieglijnen"
ogrinfo vlieglijnen.gpkg -sql "ALTER TABLE vlieglijnen add column vliegdatum_dt DATETIME"
ogrinfo vlieglijnen.gpkg -sql "UPDATE vlieglijnen set vliegdatum_dt=vliegdatum"
```

Any insights in why ogr2ogr is behaving like this are very much appreciated!

Environment:
- 5.3.0-28-generic \# 30~18.04.1-Ubuntu SMP Fri Jan 17 06:14:09 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- GDAL 2.4.0, released 2018/12/14

**Comment by rouault** [comment]
This is more a user question, than a bug report, hence closing this ticket.

ogr2ogr should do the right thing if the column in PostgreSQL uses one of TIMESTAMP / TIMESTAMP WITH TZ data types. I'm pretty sure there are Postgres functions to convert from the formatting you have to that. Probably that just casting to TIMESTAMP should do it.

As the SQL you execute is a Postgres one, whatever convention the output driver (here GPKG) uses is irrelevant. A good way is also to check with ogrinfo first that everything is properly recognized
