### ISSUE TITLE
GetProjection() RuntimeError: PROJ: proj_create_from_database: Cannot find proj.db

### ISSUE THREAD

**Issue by enemni** [OSGeo/gdal#2248]
Using gdal 3.02 python 3.7.6 conda 4.8.2, I have the error below. I found in the past that the combination python<3.7 with gdal 2.2.4 or 2.4.1 was not causing the problem. Unfortunately I cannot find a combination that works at the moment. My final aim is to create a binary mask from a shapefile, using the georef of a tiff, as shown below:

```
dataset = gdal.Open(tif_file,0) #importing using gda, 0 is for reading only 
ref_filename=tif_file
geotransform = dataset.GetGeoTransform() #Fetches the coefficients for transforming between pixel/line (P,L) raster space, and projection coordinates (Xp,Yp) space.
projection=dataset.GetProjection()
data= dataset.GetRasterBand(1).ReadAsArray() #CHECK THE CORRECT BAND 
print("The following file is uploaded: ",tif_file)

driver = ogr.GetDriverByName('ESRI Shapefile')
DS = driver.Open(shapefile, 0)
Layer = DS.GetLayer()
driver = gdal.GetDriverByName('MEM') # In memory dataset
print("The following file is uploaded: ",shapefile) ##check

#Creating a new raster file from the shape file with the size of the .tiff file
target_ds =driver.Create('', dataset.RasterXSize, dataset.RasterYSize, 1, gdal.GDT_Byte) 
target_ds.SetGeoTransform( geotransform ) #same geotrasformation
target_ds.SetProjection( str(projection) ) #same projection
#Rasterization
gdal.RasterizeLayer( target_ds, [1], Layer, burn_values=[0], options=["ATTRIBUTE=Water_Clas"]) #CHANGE IT HERE!
#ATTRIBUTE is the name of the column in the .shp file of the binary classification which is 1 for each polygon
#Definition: gdal.RasterizeLayer(ds,bands,layer,burn_values, options = ["BURN_VALUE_FROM=Z"])
labeled_pixels = target_ds.GetRasterBand(1).ReadAsArray() 
os.chdir(ROOT_DIR)
outfile = '%s.tif' %(os.path.join(ROOT_DIR,  os.path.splitext(tif_file)[0]+"_mask"))
#save_tiff(outfile,labeled_pixels,ref_filename,nodata_value=-9999.9)
print("Mask Saved")    
print("Done", datetime.datetime.now() - time)                

```
This is error

![image](https://user-images.githubusercontent.com/35107754/74642258-f6fb3000-5172-11ea-9bdc-ea1512a7b456.png)

**Comment by jratike80** [comment]
You should read https://trac.osgeo.org/gdal/wiki/rfc73_proj6_wkt2_srsbarn.

Gdal-dev mailing list is the channel to use for asking questions about how to use GDAL.

**Comment by rouault** [comment]
You need to set the PROJ_LIB environment variable to point to the directory where proj.db is installed in your conda env.

**Comment by enemni** [comment]
How can I do it?

**Comment by enemni** [comment]
> You need to set the PROJ_LIB environment variable to point to the directory where proj.db is installed in your conda env.

How can I do it?

**Comment by shaheen-git** [comment]
You need to include the location of proj.db in the windows PATH .
To do so:
- Open "Edit Environment Variables for your account"
- The top panel is the list of current user's environment variables.
- Select the "path" variable and click on Edit button.
- Add the folder containing "proj.db" to the list (e.g. C:\OSGeo4W64\share\proj )
- Apply and close the dialogs.
- You have to close your programming environment and reload it to load the updated path.

**Comment by TTnTTT** [comment]
> In addition to creating the PROJ_LIB environment variable as @rouault mentioned, you need to include the location of proj.db in the windows PATH . To do so:
> 
> * Open "Edit Environment Variables for your account"
> * The top panel is the list of current user's environment variables.
> * Click on "New". In the new dialog box, for the variable name enter "PROJ_LIB" and for the variable value, add the folder path where proj.db is located. Click Ok and close.
> * Select the "path" variable and click on Edit button.
> * Add the folder containing "proj.db" to the list (e.g. C:\OSGeo4W64\share\proj )
> * Apply and close the dialog boxes.
> * You have to close your programming environment and reload it to load the updated path.

thanks very much!

**Comment by jratike80** [comment]
The "proj.db" file is supposed to be where "PROJ_LIB" points and I do not have that path included in PATH variable on my Windows computer. Not for OSGeo4W nor gisinternals installation, and both works fine.
