### ISSUE TITLE
gdal.Warp() generates a black image when using the outputBounds option 

### ISSUE THREAD

**Issue by gutorsantos** [OSGeo/gdal#2251]
## Expected behavior and actual behavior.

The expected result was a one of tiles in the raster image .tif 256x256 pixels. However, when adding the WarpOption, **outputBounds**, the output file is a black image.

![raster](https://user-images.githubusercontent.com/12007361/74681473-4147d580-51a2-11ea-8a05-3033a52c56df.png)
_Raster Image_

![119433](https://user-images.githubusercontent.com/12007361/74682093-d7303000-51a3-11ea-9685-90d3cc5a5f0a.png)
_Tile expected_

![errorImage (2)](https://user-images.githubusercontent.com/12007361/74680689-312ef680-51a0-11ea-974a-86e5be6f003c.png)
 _Unexpected output_
## Steps to reproduce the problem.
```
Driver: GTiff/GeoTIFF
Files: warp_test.tif
Size is 256, 256
Coordinate System is:
PROJCS["WGS_1984_Web_Mercator_Auxiliary_Sphere",
    GEOGCS["WGS 84",
        DATUM["WGS_1984",
            SPHEROID["WGS 84",6378137,298.257223563,
                AUTHORITY["EPSG","7030"]],
            AUTHORITY["EPSG","6326"]],
        PRIMEM["Greenwich",0],
        UNIT["degree",0.0174532925199433],
        AUTHORITY["EPSG","4326"]],
    PROJECTION["Mercator_1SP"],
    PARAMETER["central_meridian",0],
    PARAMETER["scale_factor",1],
    PARAMETER["false_easting",0],
    PARAMETER["false_northing",0],
    UNIT["metre",1,
        AUTHORITY["EPSG","9001"]],
    EXTENSION["PROJ4","+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext  +no_defs"],
    AUTHORITY["EPSG","3857"]]
Origin = (1779301.144422332756221,5332399.967230462469161)
Pixel Size = (0.597164283478378,-0.597164283473830)
Metadata:
  AREA_OR_POINT=Area
  TIFFTAG_COPYRIGHT=Image Copyright 2016 DigitalGlobe Inc
  TIFFTAG_RESOLUTIONUNIT=1 (unitless)
  TIFFTAG_XRESOLUTION=1
  TIFFTAG_YRESOLUTION=1
Image Structure Metadata:
  INTERLEAVE=PIXEL
Corner Coordinates:
Upper Left  ( 1779301.144, 5332399.967) ( 15d59' 1.44"E, 43d 8' 2.63"N)
Lower Left  ( 1779301.144, 5332247.093) ( 15d59' 1.44"E, 43d 7'59.02"N)
Upper Right ( 1779454.018, 5332399.967) ( 15d59' 6.39"E, 43d 8' 2.63"N)
Lower Right ( 1779454.018, 5332247.093) ( 15d59' 6.39"E, 43d 7'59.02"N)
Center      ( 1779377.581, 5332323.530) ( 15d59' 3.91"E, 43d 8' 0.82"N)
Band 1 Block=256x10 Type=Byte, ColorInterp=Red
Band 2 Block=256x10 Type=Byte, ColorInterp=Green
Band 3 Block=256x10 Type=Byte, ColorInterp=Blue
```

## Operating system
```
Operating System: Ubuntu 18.04.4 LTS
Kernel: Linux 5.3.0-28-generic
Architecture: x86-64
```

## GDAL version and provenance
**GDAL 3.0.2, released 2019/10/28**

**Comment by jratike80** [comment]
Was this resolved by checking that the given bounds are certainly within the source image?

**Comment by gutorsantos** [comment]
The coordinates was changed, this occurred because pyproj.transform() has some kind of error.

# pyproj.transform() - function signature

```python
transform(p1, p2, x1, y1, z1, radians=False)
  return x2, y2, z2
``` 

But when using EPSG:4326 as source projection to convert to another you have to change the x and y params order as well as the function return is also changed.

```python
transform(p1, p2, y1, x1, z1, radians=False)
  return y2, x2, z2
```

**Comment by jratike80** [comment]
GDAL nowadays tries to handle the coordinate axis order as it is defined for the respective coordinate system https://gdal.org/development/rfc/rfc73_proj6_wkt2_srsbarn.html.  I guess that another option for you with EPSG:4326 would have been to add OAMS_TRADITIONAL_GIS_ORDER into some strategic place.

I apologize that axis order thing is complicated.

**Comment by gutorsantos** [comment]
No problem,
Thanks for suport!
