### ISSUE TITLE
gdal-data breaks libgdal20

### ISSUE THREAD

**Issue by pri-pro** [OSGeo/gdal#2256]
gdal-data breaks libgdal20 (<=2.5 )
there is libgdal26. But somehow I need to run libgdal20.
Any suggestions?

**Comment by jratike80** [comment]
I suggest to ask questions in the the gdal-dev mailing list. You probably saw the message when you started to create the issue 

> IMPORTANT: Do NOT use GitHub to post any questions or support requests!

**Comment by rouault** [comment]
Seems to be an issue with using packages from a distribution (Debian/Ubuntu). Not a GDAL itself issue. Closing
