### ISSUE TITLE
Anyone else experience these dependency issues on EC2?

### ISSUE THREAD

**Issue by Zalkota** [OSGeo/gdal#2257]
This is the second error GDAL has returned on my AWS EC2, the original error was looking for libcrypto.s0.1.1. Now it's looking for libjson-c.so.3. 

[Wed Feb 19 04:46:01.617682 2020] [:error] [pid 32491]     from .fields import (  # NOQA
[Wed Feb 19 04:46:01.617688 2020] [:error] [pid 32491]   File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/contrib/gis/forms/fields.py", line 2, in <module>
[Wed Feb 19 04:46:01.617691 2020] [:error] [pid 32491]     from django.contrib.gis.geos import GEOSException, GEOSGeometry
[Wed Feb 19 04:46:01.617696 2020] [:error] [pid 32491]   File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/contrib/gis/geos/__init__.py", line 5, in <module>
[Wed Feb 19 04:46:01.617699 2020] [:error] [pid 32491]     from .collections import (  # NOQA
[Wed Feb 19 04:46:01.617704 2020] [:error] [pid 32491]   File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/contrib/gis/geos/collections.py", line 9, in <module>
[Wed Feb 19 04:46:01.617707 2020] [:error] [pid 32491]     from django.contrib.gis.geos.geometry import GEOSGeometry, LinearGeometryMixin
[Wed Feb 19 04:46:01.617712 2020] [:error] [pid 32491]   File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/contrib/gis/geos/geometry.py", line 8, in <module>
[Wed Feb 19 04:46:01.617715 2020] [:error] [pid 32491]     from django.contrib.gis import gdal
[Wed Feb 19 04:46:01.617720 2020] [:error] [pid 32491]   File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/contrib/gis/gdal/__init__.py", line 28, in <module>
[Wed Feb 19 04:46:01.617724 2020] [:error] [pid 32491]     from django.contrib.gis.gdal.datasource import DataSource
[Wed Feb 19 04:46:01.617729 2020] [:error] [pid 32491]   File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/contrib/gis/gdal/datasource.py", line 39, in <module>
[Wed Feb 19 04:46:01.617732 2020] [:error] [pid 32491]     from django.contrib.gis.gdal.driver import Driver
[Wed Feb 19 04:46:01.617737 2020] [:error] [pid 32491]   File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/contrib/gis/gdal/driver.py", line 5, in <module>
[Wed Feb 19 04:46:01.617740 2020] [:error] [pid 32491]     from django.contrib.gis.gdal.prototypes import ds as vcapi, raster as rcapi
[Wed Feb 19 04:46:01.617745 2020] [:error] [pid 32491]   File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/contrib/gis/gdal/prototypes/ds.py", line 9, in <module>
[Wed Feb 19 04:46:01.617748 2020] [:error] [pid 32491]     from django.contrib.gis.gdal.libgdal import GDAL_VERSION, lgdal
[Wed Feb 19 04:46:01.617754 2020] [:error] [pid 32491]   File "/opt/python/run/venv/local/lib/python3.6/site-packages/django/contrib/gis/gdal/libgdal.py", line 47, in <module>
[Wed Feb 19 04:46:01.617757 2020] [:error] [pid 32491]     lgdal = CDLL(lib_path)
[Wed Feb 19 04:46:01.617762 2020] [:error] [pid 32491]   File "/usr/lib64/python3.6/ctypes/__init__.py", line 343, in __init__
[Wed Feb 19 04:46:01.617765 2020] [:error] [pid 32491]     self._handle = _dlopen(self._name, mode)
[Wed Feb 19 04:46:01.617802 2020] [:error] [pid 32491] OSError: libjson-c.so.3: cannot open shared object file: No such file or directory

**Comment by rcoup** [comment]
@Zalkota please fill in (and read) the issue template.

When you post to the gdal-dev mailing list, please include where from & how you're installing GDAL. 

Clearly you're doing something different to [GeoDjango's install guide](https://docs.djangoproject.com/en/3.0/ref/contrib/gis/install/geolibs/#gdal) — my guess is building GDAL with a set of dependencies that doesn't match your EC2 environment.
