### ISSUE TITLE
OGR_L_GetExtent() doesn't return expected value when creating a GeoJSON file

### ISSUE THREAD

**Issue by rbuffat** [OSGeo/gdal#2269]
The following code snippet outputs the extent after adding a feature. It produces different output for the GeoJSON, GPKG as well as ESRI Shapefile driver:

```
from osgeo import gdal
from osgeo import ogr

print("GDAL:", gdal.__version__)

for filename, driverName in [("abc.geojson", "GeoJSON"),
                             ("abc.gpkg", "GPKG"),
                             ("abc.shp", "ESRI Shapefile")]:

    drv = gdal.GetDriverByName( driverName )


    ds = drv.Create( filename, 0, 0, 0, gdal.GDT_Unknown )
    if ds is None:
        print("Creation of output file failed.\n")
        sys.exit( 1 )

    lyr = ds.CreateLayer( "abc", None, ogr.wkbPoint )
    if lyr is None:
        print("Layer creation failed.\n")
        sys.exit( 1 )

    field_defn = ogr.FieldDefn( "Name", ogr.OFTString )
    field_defn.SetWidth( 32 )

    if lyr.CreateField ( field_defn ) != 0:
        print("Creating Name field failed.\n")
        sys.exit( 1 )

    for x, y, name in [(0.0, 0.0, "p1"),
                    (0.0, 10.0, "p2")]:

        feat = ogr.Feature( lyr.GetLayerDefn())
        feat.SetField( "Name", name )

        pt = ogr.Geometry(ogr.wkbPoint)
        pt.SetPoint_2D(0, x, y)

        feat.SetGeometry(pt)

        if lyr.CreateFeature(feat) != 0:
            print("Failed to create feature in shapefile.\n")
            sys.exit( 1 )

        feat.Destroy()
        
        extent = lyr.GetExtent(force=1)
        print(driverName, name, extent)

    ds = None
```

Output (OS: Arch Linux):

```
GDAL: 3.0.4
GeoJSON p1 (0.0, 0.0, 0.0, 0.0)
GeoJSON p2 (0.0, 0.0, 0.0, 0.0)
GPKG p1 (0.0, 0.0, 0.0, 0.0)
GPKG p2 (0.0, 0.0, 0.0, 10.0)
ESRI Shapefile p1 (0.0, 0.0, 0.0, 0.0)
ESRI Shapefile p2 (0.0, 0.0, 10.0, 10.0)
```

Is it generally unsafe to query the extent after a data source was modified? 

I hope I didn't miss something obvious in the documentation.

**Comment by rouault** [comment]
> Is it generally unsafe to query the extent after a data source was modified?

This is highly dependent on driver implementation. Shapefile and GPKG have full read/write capabilities, and seem to do the job well here. The GeoJSON implementation is a write-only one, and all reading capaiblities (GetNextFeature(), GetExtent(), etc...) have dummy implementation

**Comment by rbuffat** [comment]
> Shapefile and GPKG have full read/write capabilities, and seem to do the job well here

I think only the GPKG driver is correct in this instance:
`GPKG p2 (0.0, 0.0, 0.0, 10.0)`
while the ESRI Shapefile driver returns a wrong ymin value:
`ESRI Shapefile p2 (0.0, 0.0, 10.0, 10.0)`

**Comment by rbuffat** [comment]
With 

```
    for x, y, name in [(0.0, 10.0, "p1"),
                               (0.0, 20.0, "p2")]:
``` 

I get the correct output:

```
ESRI Shapefile p1 (0.0, 0.0, 10.0, 10.0)
ESRI Shapefile p2 (0.0, 0.0, 10.0, 20.0)
```

With 

```
    for x, y, name in [(0.0, 0.0, "p1"), 
                        (0.0, 20.0, "p2")]:
```

not:

```
ESRI Shapefile p1 (0.0, 0.0, 0.0, 0.0)
ESRI Shapefile p2 (0.0, 0.0, 20.0, 20.0)

```

It looks as 0.0 values are ignored for calculating the extent for the ESRI Shapefile driver.

**Comment by rouault** [comment]
> It looks as 0.0 values are ignored for calculating the extent with the ESRI Shapefile driver.

yes, was a bug. Just fixed

**Comment by rbuffat** [comment]
@rouault Great! Thank you.
