### ISSUE TITLE
Incorrect shapefile CRS detection

### ISSUE THREAD

**Issue by nyalldawson** [OSGeo/gdal#2270]
From https://github.com/qgis/QGIS/issues/34660

Running ogrinfo on the attached file gives a projection definition

Layer SRS WKT:
```
GEOGCRS["GCS_Assumed_Geographic_1",
    DATUM["North American Datum 1983",
        ELLIPSOID["GRS 1980",6378137,298.257222101,
            LENGTHUNIT["metre",1]],
        ID["EPSG",6269]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["Degree",0.0174532925199433]],
    CS[ellipsoidal,2],
        AXIS["longitude",east,
            ORDER[1],
            ANGLEUNIT["Degree",0.0174532925199433]],
        AXIS["latitude",north,
            ORDER[2],
            ANGLEUNIT["Degree",0.0174532925199433]]]
```
Plugging ogr's detected CRS into projinfo --identify reports:

```
Identification match count: 1
ESRI:104000: 25 %
```
In contrast, plugging the .prj contents:
```
GEOGCS["GCS_Assumed_Geographic_1",DATUM["D_North_American_1983",SPHEROID["GRS_1980",6378137.0,298.257222101]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]]		
```

directly into projinfo reports:
```
Identification match count: 2
EPSG:4269: 70 %
ESRI:104000: 25 %
```

[prj_issue_example_project_and_data.zip](https://github.com/OSGeo/gdal/files/4252708/prj_issue_example_project_and_data.zip)

**Comment by rouault** [comment]
As far as I can see, this is purely a PROJ issue, or presumably even a PROJ feature :-)

ESRI:104000 resolves to using D_North_American_1927 datum, but the above definition uses D_North_American_1983.

When given the WKT2 definition with the lon, lat axis order, EPSG:4269 cannot be considered at all given that its axis order is lat, lon. When given the ESRI WKT definition, as there's no explicit axis order, both can be considered.

projinfo ESRI:104000 resolves to a definition with lat, lon axis, which is likely unwanted as in the ESRI realm, things are propably more lon,lat. When providing the ESRI PRJ directly, as there's no axis specification, PROJ can consider both. But once you provide the WKT2 definition with the lon, lat order, EPSG:4269 is no longer a candidate (and should have never been)

So from my point of view, this behaves as expected

**Comment by nyalldawson** [comment]
Ok, thanks for the investigation!

I double checked within ArcMap and it also reports that a custom CRS is in use for the layer. Sorry about the noise!
