### ISSUE TITLE
Rasterize failing on some line segments

### ISSUE THREAD

**Issue by gktval** [OSGeo/gdal#2275]
Rasterize will miss cells if cells if the line falls exactly on the extents.

Scratch that. the raster size should be 1+ the extents

**Comment by jratike80** [comment]
Why did you close the issue? Was your observation wrong or did you fix it somehow?

**Comment by gktval** [comment]
It was wrong. I work a lot with surfer grid, which are half a pixel offset from gdal. When creating the output dataset, I was calculating the size of the raster incorrectly: (maxX-Minx)/ xResolution. I needed to add a +1 at the end. Thus, the output dataset was cutting off the last columns /row of pixels.
