### ISSUE TITLE
FlatGeoBuf: spatial filter doesn't always work

### ISSUE THREAD

**Issue by rouault** [OSGeo/gdal#2282]
- Download zipped geopackage at https://filetransfer.io/data-package/VVKkoE4D and unzip it
- ogr2ogr grid_germany.fgb grid_germany.gpkg
- test_ogrsf -ro grid_germany.fgb

Following error is emitted:
ERROR: Spatial filter (0) eliminated a feature unexpectedly!

The .fgb is ~ 700 MB large

CC @bjornharrtell 

Looking a bit at the code, the logic in parseFeature() to decide whether to do a VSIFSeekL() or not seemed a bit suspicious, but even when doing unconditionnaly the VSIFSeekL(), the error is still there

**Comment by rouault** [comment]
Actually can be reproduced on a much smaller file created with:
$ ogr2ogr small.fgb grid_germany.fgb -spat 4200000 3000000 4202000 3002000

Only 40 features in it: [small.fgb.zip](https://github.com/OSGeo/gdal/files/4270129/small.fgb.zip)

**Comment by rouault** [comment]
It seems related to an issue with FID stability:
```
$ ogrinfo small.fgb -spat 4200405 3000405 4200410 3000410 -al -q

Layer name: GPKG demo
OGRFeature(GPKG demo):42
  gitter_id_100m (String) = 100mN30004E42004
  POLYGON ((4200400 3000400,4200400 3000500,4200500 3000500,4200500 3000400,4200400 3000400))
```
Note the FID 42, but the layer has only 40 features (FID 0 to 39)
```
$ ogrinfo small.fgb -fid 42 -al -q

Layer name: GPKG demo
ERROR 1: Requested feature id is out of bounds
Unable to locate feature id 42 on this layer.
```

I guess that FlatGeobuf should include a FID special attribute in a Feature

**Comment by bjornharrtell** [comment]
Hmm this is worrying. The FID should be the index position in the leaf nodes in the index (specifially pos - 1 at https://github.com/OSGeo/gdal/blob/e5f3dfe78b0f1ac124173f2fc6b014d7fdaeec13/gdal/ogr/ogrsf_frmts/flatgeobuf/packedrtree.cpp#L321). Will try to find out what is going on...

**Comment by rouault** [comment]
Fixed per https://github.com/OSGeo/gdal/pull/2284
