### ISSUE TITLE
FlatGeoBuf: creating a large file can be super slow with a rotational disk

### ISSUE THREAD

**Issue by rouault** [OSGeo/gdal#2287]
I've attempted "ogr2ogr france_osm_points.fgb france-latest.osm.pbf points" (where france-latest.osm.pbf is a OSM extract from a couple years. File size is 3.6 GB). The conversion itself runs in a few minutes to 100%, but the writing to the final file with the Hilbert sorting was super slow. It would have taken hours at the rate the file was written. I've a slow rotational disk, which might be the reason. And/or perhaps due to use of FILE* buffered I/O (but I presume the disk is the major factor) The final size is 1.3 GB.

With the following patch that adds a OGR_FLATGEOBUF_VSIMEM_TEMP_FILE=YES configuration option to create the temporary file in /vsimem/, it is a matter of a few tens of seconds to write the final file
```
diff --git a/gdal/ogr/ogrsf_frmts/flatgeobuf/ogrflatgeobufdataset.cpp b/gdal/ogr/ogrsf_frmts/flatgeobuf/ogrflatgeobufdataset.cpp
index 14a53e7..0299436 100644
--- a/gdal/ogr/ogrsf_frmts/flatgeobuf/ogrflatgeobufdataset.cpp
+++ b/gdal/ogr/ogrsf_frmts/flatgeobuf/ogrflatgeobufdataset.cpp
@@ -438,7 +438,9 @@ OGRLayer* OGRFlatGeobufDataset::ICreateLayer( const char *pszLayerName,
         CPLDebug("FlatGeobuf", "Spatial index requested will write to temp file and do second pass on close");
         const CPLString osDirname(CPLGetPath(osFilename.c_str()));
         const CPLString osBasename(CPLGetBasename(osFilename.c_str()));
-        osTempFile = (STARTS_WITH(osFilename, "/vsi") &&
+        osTempFile = CPLTestBool(CPLGetConfigOption("OGR_FLATGEOBUF_VSIMEM_TEMP_FILE", "NO")) ?
+            CPLSPrintf("/vsimem/tempflatgeobuf/%p", this) :
+                      (STARTS_WITH(osFilename, "/vsi") &&
                       !STARTS_WITH(osFilename, "/vsimem/")) ?
             CPLGenerateTempFilename(osBasename) :
             CPLFormFilename(osDirname, osBasename, nullptr);
```

Besides that strategy, I guess an alternative strategy could be to allocate a buffer of let's say 100 MB and when re-writing the file blobs from the temporary file to the final, do that in batch. The main loop for (size_t i = 0; i < m_featuresCount; i++) { would have a sub-loop, where it would collect the (src_file_offset, target_file_offset) of features until 100 MB is reached. It would sort by increasing src_file_offset. Read that content in increasing offset order w.r.t the source temporary file. And then write that to the final file by increasing target_file_offset. Hopefully the above makes sense.

I'm not sure how much gain there would be from that, but I did something a bit similar in the past in the GeoPackage driver when generating the R-Tree: instead of doing a single "INSERT INTO layer_rtree SELECT [...] from layer", I iterate over 100 K features in the layer to grab their id and extent, and then insert that in the R-Tree. That saved a lot of seeking within the file.

CC @bjornharrtell

**Comment by bjornharrtell** [comment]
I agree this is likely caused by the combination of large amounts of seeks when concurrently reading from the temp file and writing to the destination on the same slow rotational drive so it would make sense to make it easy to choose where the temp file is to be kept.

The optimization also sounds reasonable to do and likely beneficial for more than the slow rotational disk.
