### ISSUE TITLE
Grib2 File reading bands taking too much time and the process never ends.

### ISSUE THREAD

**Issue by Mdttz** [OSGeo/gdal#2288]
Hello, I have 2 valid grib2 files (from Météo France): 
1. [File1](http://geodelivery.astrium-geo.com/main.html?download&weblink=20cb69884e8d3fc34a2ea1f6d8624325&realfilename=routine-meteo-work.grib2) This file is working correctly with the recovering of a band using a GDAL request. 
2. [File2](http://geodelivery.astrium-geo.com/main.html?download&weblink=9573738c46a54d4617074e3f142d10d9&realfilename=routine-meteo-notwork.grib2) This file is not working correctly with the recovering of a band using a GDAL request. 
## Steps to reproduce the problem. 
I use GDAL to obtain the band’s data, for example the 100th band. 
- With the first file, there is no problem. 
- With the second file, GDAL is taking too much time and the process never ends. 

_What I have noticed:_

If I make a request on a band near the beginning with the second file, there is no problem. But the more I move away from the beginning, the more time GDAL takes to give me the band’s data and the process never ends. 
It seems that the difference between the 2 files is the architecture, as the sequence of the bands is not the same: 

In the first file, the sequence is: 

- Data-A-1 
- Data-B-1 
- Data-C-1 
- Data-A-2 
- Data-B-2 
- Data-C-2
- Etc.

 

In the second file, the sequence is: 

- Data-A-1
- Data-A-2
- ... 
- Data-B-1  
- Data-B-2 
- ... 
- Data-C-1 
- Data-C-2
- ... 

## Operating system 
Windows 10, 64 bits, version 17134.471 
## GDAL version and provenance 
Building GDAL 2.3 for Windows in use, but it seems that QGIS has the same problem with the 3.0.4 version.

**Comment by rouault** [comment]
@Mdttz Would you know of somewhat small GRIB files (max a few hundreds of KB) that would exhibit this structure of multiple subgrids in a same GRIB message, as used in File 2 http://geodelivery.astrium-geo.com/main.html?download&weblink=9573738c46a54d4617074e3f142d10d9&realfilename=routine-meteo-notwork.grib2 ? I don't think we have any in GDAL autotest suite

**Comment by Mdttz** [comment]
@rouault after search i don't have small GRIB files with this structure.  My smallest file with this structure is like File 2 (200MB+).

**Comment by rouault** [comment]
only for 3.1.0 currently. Backporting it to older versions would be doable, but with more efforts (previous commits to backport as well)
