### ISSUE TITLE
EPSG of dataset not recognized in GDAL 3.

### ISSUE THREAD

**Issue by ktheijs** [OSGeo/gdal#2290]
## Expected behavior and actual behavior.

I have a geotiff that loses its EPSG code when read with GDAL 3.0. When I do `Dataset.GetProjection()` in gdal 2.4, I get:

`PROJCS["NAD27 / Alabama West",`
`	GEOGCS["NAD27",`
`		DATUM["North_American_Datum_1927",SPHEROID["Clarke 1866",6378206.4,294.9786982138982,AUTHORITY["EPSG","7008"]],AUTHORITY["EPSG","6267"]],`
`		PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],`
`		UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],`
`		AUTHORITY["EPSG","4267"]],`
`	PROJECTION["Transverse_Mercator"],`
`	PARAMETER["latitude_of_origin",30],`
`	PARAMETER["central_meridian",-87.5],`
`	PARAMETER["scale_factor",0.999933333],`
`	PARAMETER["false_easting",500000],`
`	PARAMETER["false_northing",0],`
`	UNIT["US survey foot",0.3048006096012192,AUTHORITY["EPSG","9003"]],`
`	AXIS["X",EAST],`
`	AXIS["Y",NORTH],`
`	AUTHORITY["EPSG","26730"]]`

(Mind the last line.)
When I do the same in Gdal 3.0, I get:

`PROJCS["NAD27 / Alabama West",`
`	GEOGCS["NAD27",`
`		DATUM["North_American_Datum_1927",SPHEROID["Clarke 1866",6378206.4,294.978698213898,AUTHORITY["EPSG","7008"]],TOWGS84[-8,160,176,0,0,0,0],AUTHORITY["EPSG","6267"]],`
`		PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],`
`		UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],`
`		AUTHORITY["EPSG","4267"]],`
`	PROJECTION["Transverse_Mercator"],`
`	PARAMETER["latitude_of_origin",30],`
`	PARAMETER["central_meridian",-87.5],`
`	PARAMETER["scale_factor",0.999933333],`
`	PARAMETER["false_easting",500000],`
`	PARAMETER["false_northing",0],`
`	UNIT["US survey foot",0.304800609601219,AUTHORITY["9003","EPSG"]],`
`	AXIS["Easting",EAST],`
`	AXIS["Northing",NORTH]]`

I would expect to get the same result in GDAL 3.0. Also, when I try to do 'myDataset.GetEPSG()', I get -1 for GDAL 3.0 and I get 26730 for GDAL 2.4.

Any idea why the EPSG isn't recognized by GDAL 3.0? I am using exactly the same Geotiff in both cases.

## Operating system

Windows 10 x64

## GDAL version and provenance

Using the C# wrappers from GISInternals: release-1911-x64-gdal-3-0-2-mapserver-7-4-2.

**Comment by rouault** [comment]
Please attach such a file or provide a link to it

**Comment by ktheijs** [comment]
Here is the file that I was talking about:
[DemEpsg26730.zip](https://github.com/OSGeo/gdal/files/4279810/DemEpsg26730.zip)

**Comment by jratike80** [comment]
Verified with gdalinfo from GDAL 2.4.2 vs GDAL 3.1.0dev.
I get the same result with missing AUTHORITY also if I make a copy with `gdal_translate -a_srs epsg:26730`

Listgeo finds the GeoTIFF tag `PCS = 26730 (NAD27 / Alabama West)`

**Comment by rouault** [comment]
Originally a PROJ 6 issue with a proposed fix queued in https://github.com/OSGeo/PROJ/pull/2011
GDAL workaround pushed as well

**Comment by ktheijs** [comment]
Great! Thank you.

In which release will this fix/workaround be included, and is there already an ETA for that version?

**Comment by rouault** [comment]
Any of PROJ 7.0.1 May 1st 2020 and/or GDAL 3.0.5 (no ETA. Presumably in May) will fix the behaviour
