### ISSUE TITLE
Incorrect handling of negative values for nodata in gdalwarp when using int8

### ISSUE THREAD

**Issue by Kirill888** [OSGeo/gdal#2298]
## Expected behavior and actual behavior.

Warp operations on signed byte data clamp negative `nodata` values to `0`:

https://github.com/OSGeo/gdal/blob/04a8d012807a2d2dd66085e68b167e3ade164348/gdal/apps/gdalwarp_lib.cpp#L1758-L1761

This ignores `PIXELTYPE="SIGNEDBYTE"` case. For example gdal_translate has a more complicated check here:

https://github.com/OSGeo/gdal/blob/04a8d012807a2d2dd66085e68b167e3ade164348/gdal/apps/gdal_translate_lib.cpp#L594-L596

I guess same needs to be used in `gdalwarp`

**Comment by Kirill888** [comment]
Looks like it's not just `nodata` rather `int8` inputs are handled as `uint8` inputs by `gdalwarp`.

File [int8_checkers.tif](https://gist.github.com/Kirill888/96e9c07ddc591a682a22e5d5b502154c/raw/0951f4f9a7bb441c4cd12cec7f60bf84daa15ac7/int8_checkers.tif) is 64x64 with pixel values `88, -11` repeated in a checkers pattern

```
 88 -11  88 -11 ...
-11  88 -11  88 ...
 88 -11  88 -11 ...
-11  88 -11  88 ...
...
```

```bash
wget https://gist.github.com/Kirill888/96e9c07ddc591a682a22e5d5b502154c/raw/0951f4f9a7bb441c4cd12cec7f60bf84daa15ac7/int8_checkers.tif

gdalinfo -stats int8_checkers.tif
...
Band 1 Block=64x64 Type=Byte, ColorInterp=Gray
  Min=-11.000 Max=88.000 
  Minimum=-11.000, Maximum=88.000, Mean=38.500, StdDev=49.500
  Metadata:
    STATISTICS_MAXIMUM=88
    STATISTICS_MEAN=38.5
    STATISTICS_MINIMUM=-11
    STATISTICS_STDDEV=49.5
    STATISTICS_VALID_PERCENT=100
  Image Structure Metadata:
    PIXELTYPE=SIGNEDBYTE
```

If we are to shrink this image by a factor of 2 using `min` as a resampling mode we expect to get an image with value `-11`. However what we get is image with value `88`, also on output image type is `unsigned integer`

```bash
gdalwarp -r min -ts 32 32 int8_checkers.tif out.tif
gdalinfo -stats out.tif
...
Band 1 Block=32x32 Type=Byte, ColorInterp=Gray
  Minimum=88.000, Maximum=88.000, Mean=88.000, StdDev=0.000
  Metadata:
    STATISTICS_MAXIMUM=88
    STATISTICS_MEAN=88
    STATISTICS_MINIMUM=88
    STATISTICS_STDDEV=0
    STATISTICS_VALID_PERCENT=100
```

Repeating the same with `int16` produces expected result.

**Comment by rouault** [comment]
Signed byte is not a dedicated data type in GDAL. There is *some* support in *some* places, but you shouldn't expect it to work everywhere properly. My advice is to gdal_translate to Int16 before doing any processing.

**Comment by Kirill888** [comment]
@rouault thanks, good to know

**Comment by mdsumner** [comment]
works now, iiuc?

```bash
gdalwarp -r min -ts 32 32 /vsicurl/https://gist.github.com/Kirill888/96e9c07ddc591a682a22e5d5b502154c/raw/0951f4f9a7bb441c4cd12cec7f60bf84daa15ac7/int8_checkers.tif out.tif

gdalinfo -stats out.tif
```

```
...
Band 1 Block=32x32 Type=Int8, ColorInterp=Gray
  Minimum=-11.000, Maximum=-11.000, Mean=-11.000, StdDev=0.000
  Metadata:
    STATISTICS_MINIMUM=-11
    STATISTICS_MAXIMUM=-11
    STATISTICS_MEAN=-11
    STATISTICS_STDDEV=0

```
