### ISSUE TITLE
ogr2ogr 3.0.3+ began showing ring self-intersection errors in Natural Earth data

### ISSUE THREAD

**Issue by nyurik** [OSGeo/gdal#2301]
Upgrading v3.0.2 to osgeo/gdal:alpine-normal-3.0.3 or 3.0.4 docker image shows data errors during import of the Natural Earth data, either latest or published in the last few months.

Input file: http://naciscdn.org/naturalearth/packages/natural_earth_vector.sqlite.zip

I do not know if this is a bug in ogr2ogr, or Natural Earth has had these issues for a while and ogr2ogr has changed its behavior and began catching them (a bit unexpected for a patch version update).

```bash
  PGCLIENTENCODING=UTF8 ogr2ogr \
    -progress \
    -f Postgresql \
    -s_srs EPSG:4326 \
    -t_srs EPSG:3857 \
    -clipsrc -180.1 -85.0511 180.1 85.0511 \
    "PG:$PGCONN" \
    -lco GEOMETRY_NAME=geometry \
    -lco OVERWRITE=YES \
    -lco DIM=2 \
    -nlt GEOMETRY \
    -overwrite \
    natural_earth_vector.sqlite
```

```
0.

ERROR 1: TopologyException: Input geom 0 is invalid: Ring Self-intersection at or near point -47.302481858850683 -16.040054212431983 at -47.302481858850683 -16.040054212431983

..10...20...30...40...50...60...70...80...90

ERROR 1: TopologyException: Input geom 0 is invalid: Ring Self-intersection at or near point -152.16893469960382 61.632025457806435 at -152.16893469960382 61.632025457806435
ERROR 1: TopologyException: Input geom 0 is invalid: Ring Self-intersection at or near point -73.334828254291267 -50.498304945839322 at -73.334828254291267 -50.498304945839322
ERROR 1: TopologyException: Input geom 0 is invalid: Ring Self-intersection at or near point -141.94237219960382 60.743150132285791 at -141.94237219960382 60.743150132285791
ERROR 1: TopologyException: Input geom 0 is invalid: Ring Self-intersection at or near point -101.77565703357999 58.608011489987462 at -101.77565703357999 58.608011489987462
ERROR 1: TopologyException: Input geom 0 is invalid: Ring Self-intersection at or near point 101.81010566020808 55.633167621194787 at 101.81010566020808 55.633167621194787
ERROR 1: TopologyException: Input geom 0 is invalid: Ring Self-intersection at or near point 178.85466556100005 71.212632554000038 at 178.85466556100005 71.212632554000038
ERROR 1: Terminating translation prematurely after failed
translation of layer ne_10m_ocean (use -skipfailures to skip errors)
```

**Comment by rouault** [comment]
The issue comes from the data. Between 3.0.2 and 3.0.3, I've updated the Docker dependencies of the alpine image to GEOS 3.8.0 and it apparently does geometry validation before doing an intersection (-clipsrc causes an intersection), whereas previous versions probably didn't.

Spatialite (through GEOS) reports an invalid on the following feature for example:
```
$ ogrinfo ne/packages/natural_earth_vector.sqlite  -sql "select st_isvalidreason(geometry) from ne_10m_admin_0_countries_lakes where ogc_fid = 49" -q

Layer name: SELECT
OGRFeature(SELECT):0
  st_isvalidreason(geometry) (String) = Invalid: NULL Geometry
```
The message is a bit mysterious because the geometry is not null... Perhaps one of its subcomponent is.

Doing the following (converting to GML, and validating them) shows something more interesting:
```
ogr2ogr -f gml -overwrite out.gml  ne/packages/natural_earth_vector.sqlite ne_10m_admin_0_countries_lakes -fid 49
$ ogrinfo out.gml -sql "select st_isvalidreason(geometry) from ne_10m_admin_0_countries_lakes" -dialect sqlite -q

Layer name: SELECT
OGRFeature(SELECT):0
  st_isvalidreason(geometry) (String) = Ring Self-intersection[30.7968205385827 61.7041333791584]
```
Looking in QGIS the GML or the original SQLite file at that coordinate indeed shows a self intersection in a small island in a lake in the north west of Russia.

**Comment by nyurik** [comment]
@rouault thank you so much for a quick and detailed answer!  I have contacted @nvkelso about this issue over email. In the mean time I guess we will have to either keep back from upgrading or start using `-skipfailures`, or examine if we even need to use `-clipsrc` (not exactly sure if we even need to filter, and/or if it will cause any validation errors without it)

**Comment by Duiesel** [comment]
@nyurik I've tried ogr2ogr 3.0.4 with `-skipfailures` and got at least one empty `ne_10m_ocean` table as a result. So this option is useless in this case.

**Comment by nyurik** [comment]
@Duiesel yes, i also ran into more issues with that. I suspect I will have to do an import without the `-clipsrc`, followed by some magical SQL statement that would filter/modify imported data if needed using Postgis functions.  Suggestions/ideas are welcome.

**Comment by Duiesel** [comment]
@nyurik I investigate more time to check this and found that it isn't a bug. There are only one row (feature) in `ne_10m_ocean` table so it failed.

**Comment by Duiesel** [comment]
> Suggestions/ideas are welcome.

May be fresh build of natural earth can solve the problem?
