### ISSUE TITLE
GDAL python not well configured for the Ubuntu-small-3.0.4 docker tag

### ISSUE THREAD

**Issue by Rovaro** [OSGeo/gdal#2304]
Taking a look at the docs for the [docker version 3.0.4 tag](https://github.com/OSGeo/gdal/tree/v3.0.4/gdal/docker#small-osgeogdalubuntu-small-latest), the image supports GDAL python. But when I try to execute any of the python based commands of the GDAL cli, I get an error.

Exec:
```
docker run --rm osgeo/gdal:ubuntu-small-3.0.4 gdal_calc.py -h
```

Result:
```error
/usr/bin/env: 'python': No such file or directory
```

Using the image `osgeo/gdal:alpine-normal-3.0.4` or `osgeo/gdal:ubuntu-small-latest` I'm able to use any of the python tools.

## GDAL version and provenance

Docker image: [osgeo/gdal:ubuntu-small-3.0.4](https://hub.docker.com/layers/osgeo/gdal/ubuntu-small-3.0.4/images/sha256-f395f6f83adc5d3279e8d0bfe443213e7a8178757e93e0bbac2153c370b09a92?context=explore)

**Comment by rouault** [comment]
In GDAL 3.x, you need to explicitly specify "python3 /usr/bin/gdal_calc.py" with the Docker images. GDAL master now defaults to python3 as default python interpreter

The doc to consult for the 3.0.4 tag is actually the one of master, so GDAL 3.0.3 and above use python 3.6 currently (I know this is confusing)
