### ISSUE TITLE
Build fails on MacOS with java and hdfs support

### ISSUE THREAD

**Issue by esmeetu** [OSGeo/gdal#2313]
## Expected behavior and actual behavior.

Build success.
Supporting `libjvm.dylib` to build.

## Steps to reproduce the problem.

```bash
./configure --prefix=/usr/local/Cellar/gdal/2.4.0 --with-java=$JAVA_HOME --with-hdfs=$HADOOP_HOME
```
output:
```bash
checking GDAL version information from gdal_version.h.in: 2.4.0
checking for Mac OS X Framework build... disabled
checking for perl bindings... disabled
checking for python bindings... disabled
checking whether we should include Java support... yes
configure: error: Unable to find libjvm.so.
```
![image](https://user-images.githubusercontent.com/6694539/76510106-088ed980-648c-11ea-9741-b4b7dc8b47dd.png)
In above image, i only have libjvm.dylib instead of libjvm.so. And i check the `configure.ac` file, it doesn't consider of `libjvm.dylib`. [related link in configure.ac](https://github.com/OSGeo/gdal/blob/9d4d488a492510fdf3b20d8b74aba06ebeb5ba76/gdal/configure.ac#L5387)
## Operating system

Mac OSX 10.15.3

## GDAL version and provenance

2.4.0

**Comment by rouault** [comment]
Pull requests are accepted
