### ISSUE TITLE
Dose v2.4.4  in Nuget not support HDF driver ?

### ISSUE THREAD

**Issue by qq2898** [OSGeo/gdal#2318]
I want to use GDAL in C# to read MODIS HDF files, and referenced GDAL/GDAL.native/GDAL.plugins from Nuget with version 2.4.4，but  the hdf seems not in the support drivers, is it true ? How Can I do to deal with hdf in c# GDAL ? thank you

**Comment by rouault** [comment]
The GDAL build in Nuget is not maintained by the GDAL upstream project. And as indicated in the issue template, this bug tracker is not meant for questions.
