### ISSUE TITLE
ESRI Projection strings are case sensitive

### ISSUE THREAD

**Issue by whatnick** [OSGeo/gdal#2329]
## Expected behavior and actual behavior.

GDAL (OSR) supports ESRI projection strings with "ESRI" prefix, however these are case sensitive and "esri" does not work. Unling "EPSG" , where both "epsg" and "EPSG" work.

## Steps to reproduce the problem.

```bash
gdalsrsinfo esri:102022
ERROR 1: ERROR - failed to load SRS definition from esri:102022
```

while these work
```bash
gdalsrsinfo EPSG:3857

PROJ.4 : +proj=merc +a=6378137 +b=6378137 +lat_ts=0 +lon_0=0 +x_0=0 +y_0=0 +k=1 +units=m +nadgrids=@null +wktext +no_defs

OGC WKT2:2018 :
PROJCRS["WGS 84 / Pseudo-Mercator",
...
```

and

```bash
gdalsrsinfo epsg:3857

PROJ.4 : +proj=merc +a=6378137 +b=6378137 +lat_ts=0 +lon_0=0 +x_0=0 +y_0=0 +k=1 +units=m +nadgrids=@null +wktext +no_defs

OGC WKT2:2018 :
PROJCRS["WGS 84 / Pseudo-Mercator",
...
```

## Operating system

Ubuntu 16.04 64 bit

## GDAL version and provenance

GDAL 3.0.2, released 2019/10/28 ( Installed via conda)

```bash
which gdalinfo
/home/ubuntu/miniconda3/bin/gdalinfo
```

**Comment by rouault** [comment]
I'd be tempted to close this a "won't fix". That epsg and EPSG are accepted is mostly an accident

**Comment by mloskot** [comment]
Perhaps support of `epsg` was added in relation to this https://mapserver.org/mapfile/projection.html

> This refers to an EPSG lookup file that contains a ‘26915’ code with the full projection parameters. “epsg” in this instance is case-sensitive because it is referring to a file name. If your file system is case-sensitive, this must be lower case, or MapServer (PROJ actually) will complain about not being able to find this file.
