### ISSUE TITLE
I cannot find gdal-config after installing gdal core gdal-300-1900-x64-core.msi

### ISSUE THREAD

**Issue by bacloud14** [OSGeo/gdal#2330]
Hi,
I could not proceed with installing "rasterio" or "Fiona", I added `GDAL_DATA` to environment variables.
The error when running pip in windows:

> INFO:root:Building on Windows requires extra options to setup.py to locate needed GDAL files. More information is available in the README.
  ERROR: A GDAL API version must be specified. Provide a path to gdal-config using a GDAL_CONFIG environment variable or use a GDAL_VERSION environment variable.

**Comment by rouault** [comment]
There are windows binary wheels for rasterio or fiona. Look at related documentation and support channels

**Comment by marcolincs** [comment]
Hi @rouault ,

sorry for reopening the question and taking it in a slightly more focused direction.

Are you saying that for windows OS users the `pip install gdal` does not work and never will? Or there are conditions under which it does work?

Currently it seems the only way out for windows users is to either manually download and install some unofficial binary wheel, or to convert to using conda and run the working `conda install gdal` instead

Cheers,

**Comment by rouault** [comment]
> Are you saying that for windows OS users the `pip install gdal` does not work and never will?

yes, I doubt this will work on Windows. You'd at least have to have MSVC available + the native library and its headers available, but I'm not sure setup.py would manage to find them. For Python and native libs, conda is the way to go.
