### ISSUE TITLE
Wrong EPSG code found for projection 

### ISSUE THREAD

**Issue by apjoseph** [OSGeo/gdal#2332]
I have the following .prj file which gdal incorrectly identifies as EPSG:2772 when it should be EPSG:2876:

`PROJCS["NAD_1983_HARN_StatePlane_Colorado_North_FIPS_0501",GEOGCS["GCS_North_American_1983_HARN",DATUM["D_North_American_1983_HARN",SPHEROID["GRS_1980",6378137.0,298.257222101]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Lambert_Conformal_Conic"],PARAMETER["False_Easting",3000000.000316083],PARAMETER["False_Northing",999999.999996],PARAMETER["Central_Meridian",-105.5],PARAMETER["Standard_Parallel_1",39.71666666666667],PARAMETER["Standard_Parallel_2",40.78333333333333],PARAMETER["Latitude_Of_Origin",39.33333333333334],UNIT["Foot_US",0.3048006096012192]]`

QGIS (3.12) is able to read the projection properly, and when I reexport the data from QGIS with same projection, GDAL is able to correctly interpret the .prj file:

`PROJCS["NAD83_HARN_Colorado_North_ftUS",GEOGCS["GCS_NAD83(HARN)",DATUM["D_North_American_1983_HARN",SPHEROID["GRS_1980",6378137,298.257222101]],PRIMEM["Greenwich",0],UNIT["Degree",0.017453292519943295]],PROJECTION["Lambert_Conformal_Conic"],PARAMETER["standard_parallel_1",40.78333333333333],PARAMETER["standard_parallel_2",39.71666666666667],PARAMETER["latitude_of_origin",39.33333333333334],PARAMETER["central_meridian",-105.5],PARAMETER["false_easting",3000000],PARAMETER["false_northing",1000000],UNIT["Foot_US",0.30480060960121924]]`

OS=Debian Buster
GDAL_VERSION=3.0.4
GEOS_VERSION=3.7.3
PROJ_VERSION=6.2.1

**Comment by rouault** [comment]
Could you paste the content of thicket in https://github.com/OSGeo/PROJ/issues ? This is now entirely the job of PROJ, and GDAL is just a consumer of the logic of PROJ

> QGIS (3.12) is able to read the projection properly,

This part is a bit strange as QGIS uses PROJ for code identification...

**Comment by apjoseph** [comment]
@rouault I tested projinfo and indeed found that proj incorrectly identifies the code. Filed issue on proj here. https://github.com/OSGeo/PROJ/issues/2086
