### ISSUE TITLE
Possible memory leak with leftover tif.aux.xml files in /vsimem

### ISSUE THREAD

**Issue by cpaulik** [OSGeo/gdal#2337]
## Expected behavior and actual behavior.

Running e.g. `gdal_translate` into a `/vsimem` file and then using `gdal.Unlink` to remove the file leaves behind a `.tif.aux.xml` file in `/vsimem`. This seems only to be a problem if the file has a `NaN` no data value. We ran this script in a loop and found the it keeps increasing in memory usage.

We are aware of the `export GDAL_PAM_ENABLED=NO` option but still found this surprising enough to raise here. Sorry if this should have gone to gdal-dev first.

## Steps to reproduce the problem.
The following script illustrates the problem and produces the following output:

```
['test.tif', 'test.tif.aux.xml']
['test.tif.aux.xml']
```

```python
from osgeo import gdal
from osgeo import osr
import numpy as np
from osgeo import gdal_array

raster, geo_transform = np.arange(12).reshape((3, 4)), (0, 1, 0, 0, 0, 1)
numpy_dtype = raster.dtype
t = np.float32 if numpy_dtype == np.float64 else numpy_dtype
t = np.int32 if numpy_dtype == np.int64 else numpy_dtype
data_type = gdal_array.NumericTypeCodeToGDALTypeCode(t)

file_name = 'test.tif'
cols = raster.shape[1]
rows = raster.shape[0]
driver = gdal.GetDriverByName("GTiff")
ds = driver.Create(file_name, cols, rows, len(raster), data_type)
ds.SetGeoTransform(geo_transform)
srs = osr.SpatialReference()
srs.SetWellKnownGeogCS("WGS84")
projection = srs.ExportToWkt()
ds.SetProjection(projection)
band = ds.GetRasterBand(1)

# comment this line to see empty output or replace `np.nan` by e.g. `3`
band.SetNoDataValue(np.nan)
band.WriteArray(raster)

ds.FlushCache()
ds = None

gdal.Translate('/vsimem/test.tif', 'test.tif')
print([ds.name for ds in gdal.listdir('/vsimem')])
gdal.Unlink('/vsimem/test.tif')
print([ds.name for ds in gdal.listdir('/vsimem')])
```

## Operating system

Manjaro/Docker

## GDAL version and provenance

gdal 3.0.4 from conda-forge

**Comment by rouault** [comment]
Not a bug. gdal.Unlink() suppresses a file, not a dataset (possibly made of several files, like the side car .aux.xml). Use gdal.GetDriverByName('GTiff').Delete('/vsimem/test.tif') instead
