### ISSUE TITLE
Convert_to_linear and promote_to_multi cannot both be specified in VectorTranslate

### ISSUE THREAD

**Issue by apjoseph** [OSGeo/gdal#2338]
The [documentation](https://gdal.org/development/rfc/rfc49_curve_geometries.html#changes-in-utilities) states that  `-nlt CONVERT_TO_LINEAR` and `-nlt PROMOTE_TO_MULTI` can be used together. However actual behavior is that only one of the two flags is chosen which is problematic when importing a mixed Polygon/MultiPolygon layer with MultiSurfaces.

GDAL=3.0.4
GEOS=3.73
PROJ=6.2.1
OS=Debian Buster

**Comment by jratike80** [comment]
Documentation is about ogr2ogr and based on the title you observed the problem with VectorTranslate library function. Is that right? Have you made also a test with ogr2ogr?

**Comment by rouault** [comment]
I'm working on fixing this
