### ISSUE TITLE
unloading+loading GDAL might cause PROJ 7.0.0 to loose its way to proj.db.

### ISSUE THREAD

**Issue by edzer** [OSGeo/gdal#2344]
One of the tests in R package `sf` unloads GDAL, which calls
```
    OGRCleanupAll();
    OSRCleanup();
```
and then loads it again, which calls
```
    GDALAllRegister();
    OGRRegisterAll();
```
After this test, all GDAL/PROJ calls result in
```
In CPL_crs_from_input(x) :
  GDAL Error 1: PROJ: proj_create_from_database: Cannot find proj.db
```
where `CPL_crs_from_input(x)` calls `OGRSpatialReference::SetFromUserInput`.

This happens in GDAL 3.0.4/PROJ 7.0.0 combinations, not seen in GDAL 3.0.2/PROJ 6.3.1 versions. Removing the unload/load GDAL test resolved the issue. Can you work with this, or shall I try to put this in a standalone C++ program causing an error?

Cc: @rsbivand

**Comment by rouault** [comment]
I've tried the following reproducer, but works fine for me with GDAL master/3.0 branch + PROJ master:
```
#include <gdal_priv.h>
#include <ogr_spatialref.h>

int main(int argc, char* argv[]){
    GDALAllRegister();
    OGRRegisterAll();

    {
        OGRSpatialReference oSRS;
        printf("ok = %d\n", oSRS.importFromEPSG(32631) == OGRERR_NONE);
    }

    OGRCleanupAll();
    OSRCleanup();

    GDALAllRegister();
    OGRRegisterAll();

    {
        OGRSpatialReference oSRS;
        printf("ok = %d\n", oSRS.importFromEPSG(32631) == OGRERR_NONE);
    }

    return 0;
}
```

**Comment by rouault** [comment]
@edzer Is this still an issue ?

**Comment by edzer** [comment]
Thanks for looking at this, Even! I haven't been able to reproduce this outside the R context, and am now somewhat confused whether this has disappeared in the R context or not. If not, I'll get back here to  dive into it further.
