### ISSUE TITLE
Retrieve metadata of an HDF5 subdataset

### ISSUE THREAD

**Issue by NikosAlexandris** [OSGeo/gdal#2346]
I am trying, unsuccessfully, to retrieve the metadata of an HDF5 subdataset. Like so:
```python
lst = gdal.Open('HDF5:ECOSTRESS_L2_LSTE_05525_002_20190627T070809_0600_01.h5://SDS/LST')
lst.GetMetadata()
{}
```
I read now in the [Metadata section of the GDAL HDF5 raster driver documentation](https://gdal.org/drivers/raster/hdf5.html#metadata) that
> No Metadata are read at this time from the HDF5 files.

Is it really not possible to retrieve per-subdataset metadata tags?

`gdalinfo` reports correctly in the command line the metadata of a subdataset. For example:
```
gdalinfo HDF5:"ECOSTRESS_L2_LSTE_05525_002_20190627T070809_0600_01.h5"://SDS/LST
Driver: HDF5Image/HDF5 Dataset
Files: ECOSTRESS_L2_LSTE_05525_002_20190627T070809_0600_01.h5
Size is 5400, 5632
Corner Coordinates:
Upper Left  (    0.0,    0.0)
Lower Left  (    0.0, 5632.0)
Upper Right ( 5400.0,    0.0)
Lower Right ( 5400.0, 5632.0)
Center      ( 2700.0, 2816.0)
Band 1 Block=5400x1 Type=UInt16, ColorInterp=Undefined
  Metadata:
    SDS_LST_add_offset=0
    SDS_LST_coordsys=cartesian
    SDS_LST_format=scaled
    SDS_LST_long_name=Land Surface Temperature
    SDS_LST_scale_factor=0.02
    SDS_LST_units=K
    SDS_LST_valid_range=7500 65535
    SDS_LST__FillValue=0
```
Unfortunately, even `gdalinfo` won't report _only_ the metadata. Unless there is someway to do this via the `mdd` option (?).

ps- Just in case, I 've been using `rasterio` and reported a similar issue there: https://github.com/mapbox/rasterio/issues/1893

**Comment by rouault** [comment]
> I read now in the [Metadata section of the GDAL HDF5 raster driver documentation](https://gdal.org/drivers/raster/hdf5.html#metadata) that

This is obsolete. I've just removed it

> Is it really not possible to retrieve per-subdataset metadata tags?

It is obviously possible if you can see them with gdalinfo :-) In that instance, those are band metadata. So must be retrieved with GDALGetMetadata() on a GDALRasterBandH object
`gdalinfo -json` can also be used to extra more easily the information you need

**Comment by NikosAlexandris** [comment]
Cool! I didn't know there is a [Python port of gdalinfo](https://github.com/OSGeo/gdal/blob/master/gdal/swig/python/samples/gdalinfo.py).

This works:
```python
sds_lst = gdal.Open('HDF5:ECOSTRESS_L2_LSTE_05525_002_20190627T070809_0600_01.h5://SDS/LST', gdal.GA_ReadOnly)
lst = sds_lst.GetRasterBand(1)
lst.GetMetadata()
{'SDS_LST_add_offset': '0 ',
 'SDS_LST_coordsys': 'cartesian',
 'SDS_LST_format': 'scaled',
 'SDS_LST_long_name': 'Land Surface Temperature',
 'SDS_LST_scale_factor': '0.02 ',
 'SDS_LST_units': 'K',
 'SDS_LST_valid_range': '7500 65535 ',
 'SDS_LST__FillValue': '0 '}
```

ps- Eventually, and obviously, I want to retrieve some subdataset's specific attribute + value. Not knowing how, I went for a hack like the following (using `rasterio` and a bad-practice of hardcoding the meta-tags):
```python
METADATA_TAGS_SUFFIXES = [
        '_FillValue',
        'add_offset',
        'coordsys',
        'format',
        'long_name',
        'scale_factor',
        'units',
        'valid_range',
]
def retrieve_subdataset_metadata(subdataset, hdf5):
     list_tags = lambda hdf5: rasterio.open(hdf5).tags()
     tags = list_tags(hdf5)
     subdataset_metadata = {}
     for metadata_tag_suffix in METADATA_TAGS_SUFFIXES:
         subdataset_metadata_tag = subdataset + '_' + metadata_tag_suffix
         for tag in tags:
             if subdataset_metadata_tag in tag:
                 subdataset_metadata[tag] = tags[tag]
     return subdataset_metadata

def retrieve_subdataset_metadata_tag(tag, subdataset, hdf5):
     subdataset_metadata = retrieve_subdataset_metadata(subdataset, hdf5)
     for key in subdataset_metadata:
         return {key: value for key, value in subdataset_metadata.items() if tag in key}
```

**Comment by NikosAlexandris** [comment]
@rouault just out of curiosity, and if you have the time, what does 'h' or 'H' stand for in `GDALRasterBandH` or in [`hDataset`](https://github.com/OSGeo/gdal/blob/master/gdal/swig/python/samples/gdalinfo.py#L149)?

**Comment by rouault** [comment]
H stands for Handle, that is a kind of pointer to an opaque object

**Comment by sgillies** [comment]
@rouault to be clear: the metadata of an HDF5 subdataset surface as metadata of bands of the "main" dataset?

**Comment by rouault** [comment]
> the metadata of an HDF5 subdataset surface as metadata of bands of the "main" dataset?

yes. Not sure why this design choice was made (comes from original commit e1fdee6ff77bcb3c803e07ea84fae07633e8fd63 15 years ago), because the metadata of a HDF5Image dataset is the same for all bands of the same subdataset... In other drivers, per-dataset vs per-band metadata are used in a more logical way. So the current behaviour is a kind of bug

**Comment by sgillies** [comment]
And the HDF5 driver bug is effectively patched in gdalinfo?

**Comment by rouault** [comment]
> And the HDF5 driver bug is effectively patched in gdalinfo?

"bug" is a bit strong. I should have rather said a mis-use in that particular context. Normally, it should have reported that metadata as per-dataset metadata instead of per-band metadata. gdalinfo can report both types, as it calls GDALGetMetadata() on dataset and raster bands.

**Comment by NikosAlexandris** [comment]
> H stands for Handle, that is a kind of pointer to an opaque object

Thank you for the clarification
