### ISSUE TITLE
DXF exporter writes layer tag in wrong subclass

### ISSUE THREAD

**Issue by mozman** [OSGeo/gdal#2348]
I reopen the DXF issue for the `Fiona` package here because:

> Fiona is a wrapper library for GDAL. GDAL is a library for input and output of geospatial data. Some supported formats, e.g. DXF, deviate from the GDAL data model and thus have some limitations: https://gdal.org/drivers/vector/dxf.html
> 
> As the implementation of the DXF input/output is within GDAL, I would suggest creating your bug report on their issue tracker: https://github.com/OSGeo/gdal

Your DXF exporter for LWPOLYLINE (and maybe other entities) writes the layer tag (group code 8) in front of the subclass marker `AcDbEntity`, according to the DXF reference this tag should be written after the the `AcDbEntity` marker:

![AcDbEntity](https://user-images.githubusercontent.com/4230966/77508283-a5794b80-6e6a-11ea-910a-44b48e46d8c6.png)

Excerpt from DXF file created by your package:

![image](https://user-images.githubusercontent.com/4230966/77508495-25071a80-6e6b-11ea-87b7-b29103433a79.png)

AutoCAD and BricsCAD do read this files, so it is not really a bug!

I am the author of [ezdxf](https://github.com/mozman/ezdxf) and got an [error message](https://groups.google.com/forum/#!topic/python-ezdxf/9kAOhxJfTK4) from a `Fiona` user, that`ezdxf` has (had) the problem of ignoring the layer tag in your DXF files, because it is written in the wrong subclass.

It would be nice if you could correct this issue in your package.

To the argument "don't assume tags in a particular order": This is true inside of a subclass but not overall subclasses, because with the introduction with DXF R13/14, the same group tag can occur in different subclasses with different meanings and a tag can also occur multiple times in the same subclass, example LWPOLYLINE vertex tag (10).

**Comment by rouault** [comment]
>  according to the DXF reference

Can you point to where it is ? What you show isn't identical to https://www.autodesk.com/techpubs/autocad/acad2000/dxf/lwpolyline_dxf_06.htm nor could I find it in https://images.autodesk.com/adsk/files/autocad_2012_pdf_dxf-reference_enu.pdf (I'm not intimately familiar with the subtleties of DXF)

**Comment by rouault** [comment]
@atlight Any opinion on this ? Wouldn't that hold with other entities type too, that is we should write tag 100 before calling WriteCore() ?

**Comment by mozman** [comment]
This topic can be found on page 62 in the linked DXF R2012 reference: Common Group Codes for Entities or in the actual online reference for [DXF R2018](http://help.autodesk.com/view/OARX/2018/ENU/?guid=GUID-3610039E-27D1-4E23-B6D3-7E60B22BB5BD).

**Comment by rouault** [comment]
@mozman The reference you quote mentions "Note: Do not write programs that rely on the order shown in these DXF code tables". They don't seem to mention exceptions regarding things that would be subclass specific.

**Comment by mozman** [comment]
It seem to valid to mix the group codes of the "base" class and the "AcDbEntity" class, ezdxf accepts now the mix of this two classes. So there is no need to change anything, but it is most  of the time better to write the group codes into the appropriate subclass and as I remember of my testing sometimes also required.

The annoying thing is, sometimes AutoCAD does not load DXF files if tags are not in the correct order or even crash and other things are can be mixed in any order.

And to finish this topic: Not everything written in the DXF reference is correct or true ;-).

**Comment by mozman** [comment]
Had to do some testing to be sure I am not crazy:

![image](https://user-images.githubusercontent.com/4230966/77563946-421b0800-6ec2-11ea-92bc-68247afb34cc.png)

ARC with start- and end angle (50, 51) in wrong subclass AcDbCircle instead of AcDbArc, results in not loading by AutoCAD:

![image](https://user-images.githubusercontent.com/4230966/77564069-71317980-6ec2-11ea-97fa-14293d2353b3.png)

There are exception.

**Comment by rouault** [comment]
Proposed pull request fixing this: https://github.com/OSGeo/gdal/pull/2352
