### ISSUE TITLE
Python and C# binding - encoding

### ISSUE THREAD

**Issue by AdiPeled10** [OSGeo/gdal#2351]
Hi, 
I'm experiencing an issue with field names and feature class names that aren't in English or the OS naive language encoding when exporting to a GDB.
When exporting to geojson I also experience that issue, so it may be more then just the ESRI driver.
I workaround it playing with encode-decode utf8-unicode in order to generate 'garbage' string that GDAL turned into the correct value. Pretty sure I've just reversed your string encoding process...
Hope you could write a permanent workaround.

good luck and thanks for the power of GDAL.

**Comment by rouault** [comment]
This ticket is much too imprecise to be actionable. Please provide input dataset and procedure to reproduce.

**Comment by rouault** [comment]
Closing due to lack of feedback. Reopen if you can provide more elements
