### ISSUE TITLE
gdaldem color-relief integer overflow

### ISSUE THREAD

**Issue by MinluLi** [OSGeo/gdal#2354]
gdaldem color-relief has integer overflow problem. 

https://github.com/OSGeo/gdal/blob/4d86c3496843f24d02839104577dc2da73c01a03/gdal/apps/gdaldem_lib.cpp#L2012

```
    const int nXSize = GDALGetRasterBandXSize(hSrcBand);
    const int nYSize = GDALGetRasterBandXSize(hSrcBand);
```

```
	GIntBig nXSize = GDALGetRasterBandXSize(hSrcBand);
	GIntBig nYSize = GDALGetRasterBandYSize(hSrcBand);
```

**Comment by rouault** [comment]
Thanks. Do not hesitate to submit PR when you're so close of the fix :-)
