### ISSUE TITLE
configure geos and netcdf library paths shadow local --with-proj

### ISSUE THREAD

**Issue by eleaver** [OSGeo/gdal#2357]
This is related to #1926 , closed Oct 2019. I'm working with gdal-3.0.4 and git master on Fedora30. GDAL 3 requires proj6 or greater, Fedora is on proj5 so I install a /usr/local/proj-6.3.0. But I link system geos and netcdf from /usr/lib64. 

The problem is in configure.ac. When configure.ac determines the netcdf and geos library paths is does not guard against they being -L/usr/lib or -L/usr/lib64, and (e.g. on Fedora) includes "-L/usr/lib64 -lgeos" and "-L/usr/lib64 -lnetcdf".  This is incorrect: the default system library paths should never be specified explicitly via -L/usr/lib64 or -L/usr/lib. The linker knows where they are. 

In my case on fedora there are some 70 system packages that rely upon proj, and proj-5.2.0 is installed on the system under /usr/lib64 as well. The explicit inclusion of -L/usr/lib64 from --with-geos or --with-netcdf on the ld command line shadows the later -L/usr/local/proj-6.3.0/lib and causes ld to pick up /usr/lib64/libproj.so instead, with resulting undefined symbol errors.

A patch for gdal-git<master> is quite simple:

`diff --git a/gdal/configure.ac b/gdal/configure.ac
index ad73f1f4d1..5a5a2e9ea8 100644
--- a/gdal/configure.ac
+++ b/gdal/configure.ac
@@ -2898,7 +2898,7 @@ else
     NETCDF_VERSION=`$NETCDF_NCCONFIG --version`
     NETCDF_PREFIX=`$NETCDF_NCCONFIG --prefix`
     NETCDF_INCLUDEDIR=`$NETCDF_NCCONFIG --includedir`
-    NETCDF_LIBS=`$NETCDF_NCCONFIG --libs`
+    NETCDF_LIBS=`$NETCDF_NCCONFIG --libs | sed -e 's:-L/usr/lib64 ::' -e 's:-L/usr/lib ::'`
     echo ""
     AC_MSG_RESULT([ got version="$NETCDF_VERSION", prefix="$NETCDF_PREFIX",
  libs="$NETCDF_LIBS", includedir="$NETCDF_INCLUDEDIR"])
@@ -4558,6 +4558,7 @@ HAVE_GEOS_RESULT="no"
 if test "${HAVE_GEOS}" = "yes" ; then

   AC_MSG_NOTICE([Using C API from GEOS $GEOS_VERSION])
+  GEOS_LIBS=`echo $GEOS_LIBS | sed -e 's:-L/usr/lib64 ::' -e 's:-L/usr/lib ::'`
   LIBS="${GEOS_LIBS} ${LIBS}"
   HAVE_GEOS_RESULT="yes"
 fi
`
If desired I could issue a pull request, unless the patch alone would suffice. It is against gdal-git, master branch.

There may be other gdal options with similar shadow issues; geos and netcdf are the ones I happened to stumble upon.

As an unrelated aside, when searching for proj library directories, GDAL's configure looks for /usr/local/proj-6.3.0/lib, but not /usr/local/proj-6.3.0/lib64, which is where the proj build puts them by default. But this is easy for me to fix with proj either with a lib->lib64 symlink, or setting proj's CMAKE_INSTALL_LIBDIR to lib rather than it's lib64 default.  

Thanks!

## Expected behavior and actual behavior.

For example (please modify !!!): I expected to be able to open this raster file (with a link to
the raster file, or it as an attachment) and it returns an error message
instead.

## Steps to reproduce the problem.

For example (please modify !!!): "gdalinfo myfile"

## Operating system

For example (please modify !!!): Ubuntu 16.04 64 bit

## GDAL version and provenance

For example (please modify !!!): the 2.2.3 version from ubuntugis-unstable PPA

**Comment by rouault** [comment]
You can provide a pull request with your patch. Please make sure to commit the regenerated autoconf file as well
