### ISSUE TITLE
Cannot read multiband jp2 (linux)

### ISSUE THREAD

**Issue by JaimeGeoPi** [OSGeo/gdal#2367]
Hi,
Thank you in advance for your work. I am not a developer but I will try to be clear.

## My Environment
-- Operative System: Kubuntu 64 bits (Ubuntu 18.04.4 LTS)
-- GDAL version 3.0.4.

## Expected behaviour and actual behaviour.
I am trying to work with a _jp2_ image (georreferenced and with 4 bands).
It is available here:
[https://drive.google.com/file/d/1ZxOUZg2-FKjYwa257VFLMpTXRWxEoP0a/view?usp=sharing](url)

--1--Trying to read this file. QGIS and Octave (rasterread) failed. I think they use GDAL to read the image.
--2--Using **gdal_translate** I get :
ERROR 1: psImage->comps[0].data == nullptr
--3--Using **ogrinfo -ro file.jp2** to get information I get :
_FAILURE:
Unable to open datasource `.....jp2' with the following drivers._
----> Among the drivers it cites, _JP2OpenJPEG_  is included.

##  More comments.
These problems do not exist in windows.

Kind Regards.

**Comment by jratike80** [comment]
JPEG2000 can contain also some vector data but I suggest still make the second test again with **gdalinfo**.

**Comment by JaimeGeoPi** [comment]
Thanks a lot jratike80, really!!
I have run gdalinfo in the console and it has worked. However, I have tried to convert the image to tif with **gdal_translate** and I have got:
_Input file size is 14880, 9960
0ERROR 1: psImage->comps[0].data == nullptr
ERROR 1: psImage->comps[0].data == nullptr
ERROR 1: psImage->comps[0].data == nullptr..._
..... [several times more]

**Comment by jratike80** [comment]
I have Windows and QGIS 3.12 opens the image as totally white but it does not throw errors. Gdal_translate of GDAL 3.1.0dev fails 

```

Input file size is 15040, 10120
0ERROR 1: psImage->comps[0].data == nullptr
ERROR 1: psImage->comps[0].data == nullptr
ERROR 1: 0722_5-1_2019.jp2, band 2: IReadBlock failed at X offset 0, Y offset 0: psImage->comps[0].data == nullptr

```
Kakadu kdu_show opens the image nicely. Image seems to be created with FME and ECW JPEG 2000 SDK v5.4.0

**Comment by rouault** [comment]
I've determined this is a openjp2 issue and created https://github.com/uclouvain/openjpeg/issues/1241 . Closing this ticket

**Comment by ValZapod** [comment]
@JaimeGeoPi The sample is gone.
