### ISSUE TITLE
Rogue Git release tags (3.0.3 / 2.4.4)

### ISSUE THREAD

**Issue by rcoup** [OSGeo/gdal#2371]
I've noticed there's the main `v3.0.3` tag in the git repo, and another `3.0.3` tag (no `v`)
And the same for `v2.4.4` vs `2.4.4`

They point to the same commit (5c9f87c) that is on master but not either the 2.4 or 3.0 release branches.

It's mostly annoying because looking at "which releases is this commit in?" on Github might list "master; 3.0.3; 2.4.4" when it should actually be "master". eg:

![2020-04-02 at 5 11 pm](https://user-images.githubusercontent.com/59874/78272106-f93c0280-7504-11ea-9c9c-b1a54fdf4f94.png)

The following will clean it up (didn't want to just do it without writing it down somewhere)

```console
git push --delete origin 3.0.3
git push --delete origin 2.4.4
```

**Comment by rouault** [comment]
Good catch. I've just deleted them
