### ISSUE TITLE
Using libpq pg_service.conf to connect ogr2ogr to PostGIS

### ISSUE THREAD

**Issue by swiss-knight** [OSGeo/gdal#2373]
Hi devs,

I want to inject data from an ESRI Shapefile into a PostGIS database using `ogr2ogr` using a [pg service file](https://www.postgresql.org/docs/10/libpq-pgservice.html) (libpq) where the connection parameters to my data base are specified.

## Steps to reproduce the problem.

```
$ cat ~/.pg_service.conf
# comment
[myservice]
    host=localhost
    port=5432
    dbname=my_database
    user=user
```
I tried this because, if I understood correctly, gdal can use libpq functionalities (https://gdal.org/drivers/vector/pg.html):

```
ogr2ogr --config OGR_TRUNCATE YES --config PG_USE_COPY YES \
-nlt PROMOTE_TO_MULTI \
-nln vector_data.el_lines \
-f "PostgreSQL" PG:"service=myservice" \
-a_srs EPSG:4326 "${shapedir}/my_shapefile_lin.shp"
```

It warns me with this message;
```
ERROR 1: You must specify at least a db name
```

To have the `ogr2ogr` command to work correctly, I have to specify the `db_name` in addition:

```
ogr2ogr --config OGR_TRUNCATE YES --config PG_USE_COPY YES \
-nlt PROMOTE_TO_MULTI \
-nln vector_data.el_lines \
-f "PostgreSQL" PG:"dbname=my_database service=myservice" \
-a_srs EPSG:4326 "${shapedir}/my_shapefile_lin.shp"
```

Which is redundant because the `db_name` is **already** specified in my `~/.pg_service.conf` file.

How could I rely only on the `~/.pg_service.conf` file to connect `ogr2ogr` to my PostGIS database?

## Operating system

Ubuntu 18.04 64 bit

## GDAL version and provenance

```
$ ogr2ogr --version
GDAL 2.4.0, released 2018/12/14
```

```
$ apt-cache policy gdal-bin
gdal-bin:
  Installed: 2.4.0+10-0bionic1
  Candidate: 2.4.0+10-0bionic1
  Version table:
 *** 2.4.0+10-0bionic1 100
        100 /var/lib/dpkg/status
     2.2.3+dfsg-2 500
        500 http://ch.archive.ubuntu.com/ubuntu bionic/universe amd64 Packages

```

**Comment by andersonad** [comment]
Just wanted to point out that this feature is not working for me on a service string that works for pgadmin4 and psql directly.

![Screenshot from 2020-05-21 16-25-19](https://user-images.githubusercontent.com/12083964/82609268-cf58a100-9b81-11ea-8036-1ae9d98b9cfc.png)

**Comment by rouault** [comment]
> Just wanted to point out that this feature is not working for me

OK, fixed per https://github.com/OSGeo/gdal/commit/ca072e09ada35d31a8228bfce416bea31b44245a
You can workaround (actually, that's the syntax I'd recommend) by using instead: "ogr2ogr -updatePG:"service=....." ...."  , that is using -update instead of -f PostgreSQL.
