### ISSUE TITLE
gdal.Translate produces VRT with `dataAxisToSRSAxisMapping` attribute in GCPList

### ISSUE THREAD

**Issue by underchemist** [OSGeo/gdal#2378]
## Expected behavior and actual behavior.

`gdal.Translate` of a GeoTIFF with GCPs produces an xml document with `dataAxisToSRSAxisMapping` attribute in the `GCPList` element. According to https://raw.githubusercontent.com/OSGeo/gdal/master/gdal/data/gdalvrt.xsd this does not conform to the VRT xml schema. I'm not sure if Translate is producing an invalid xml document, or if the xml schema file needs to be updated to include the `dataAxisToSRSAxisMapping` attribute.

Expected: The VRT xml file to conform to xml schema.
Actual: The VRT xml file does not conform to xml schema.

Happy to file a PR if it's just the xsd file that needs updating. Thanks!

## Steps to reproduce the problem.

https://gist.github.com/underchemist/c244994fc93185a9141dca4141269a6d

## Operating system

Windows 10 1903

## GDAL version and provenance

GDAL: 3.0.4 (conda-forge)
Python: 3.8.2 (default, Mar 25 2020, 08:56:29) [MSC v.1916 64 bit (AMD64)]

**Comment by rouault** [comment]
The .xsd needed to be updated indeed. Now fixed. Thanks for the report
