### ISSUE TITLE
gdalwarp missing sum resampling method

### ISSUE THREAD

**Issue by johnWilshire** [OSGeo/gdal#2383]
## Expected behavior and actual behavior.

The documentation here: https://gdal.org/programs/gdalwarp.html
says that the resampling method "sum", is available since 3.1.0.
But it is not listed as an available resampling method when using the latest ubuntu-full docker image:

![Screen Shot 2020-04-06 at 12 13 20 PM](https://user-images.githubusercontent.com/1732458/78580183-0821fe00-7800-11ea-858b-317bbc400aa0.png)

Is this resampling method available?
## Steps to reproduce the problem.

```
gdal-config --version
gdalwarp --version 
gdalwarp
```

## Operating system
ubuntu-full docker image

## GDAL version and provenance
3.1.0

**Comment by johnWilshire** [comment]
Hey, I just saw 3faf501 was added 5 days ago, which explains why the image doesn't allow this resampling method.
Thanks.
Closing now.

**Comment by rouault** [comment]
ah I see docker builds have stopped since that capability was added a few days ago. Re-starting them. Should be available in a couple hours

**Comment by johnWilshire** [comment]
Oh great! Thanks again.
