### ISSUE TITLE
AREA_OR_POINT=Point coordinate display is incorrect for DTED

### ISSUE THREAD

**Issue by msmitherdc** [OSGeo/gdal#2384]
gdal version 3.0.4

For SRTM dted file
```
File Name: \w073\n43.dt1
Last Modified Date: 10/31/19, 5:44 PM
File Size: 2,834 K Bytes
Terrain Data Type: SRTM
Terrain Representation: Grid
Terrain Extent:
  LL Coordinate: 43 00 00.0000N 073 00 00.0000W
  UR Coordinate: 44 00 00.0000N 072 00 00.0000W
Number of Posts: 1,442,401 
Number of columns: 1,201 
Number of rows: 1,201
Percent Valid Posts: 100%
X Post Spacing: 3.0 Seconds
Y Post Spacing: 3.0 Seconds
Terrain Elevation Unit: Meters
Vertical Reference: MSL(EGM96)
```

gdalinfo reports:
```
Driver: DTED/DTED Elevation Raster
Files: n43.dt1
Size is 1201, 1201
Coordinate System is:
GEOGCRS["WGS 84",
    DATUM["World Geodetic System 1984",
        ELLIPSOID["WGS 84",6378137,298.257223563,
            LENGTHUNIT["metre",1]]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["degree",0.0174532925199433]],
    CS[ellipsoidal,2],
        AXIS["geodetic latitude (Lat)",north,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433]],
        AXIS["geodetic longitude (Lon)",east,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433]],
    ID["EPSG",4326]]
Data axis to CRS axis mapping: 2,1
Origin = (-73.000416666666666,44.000416666666666)
Pixel Size = (0.000833333333333,-0.000833333333333)
Metadata:
  AREA_OR_POINT=Point
  DTED_CompilationDate=0002
  DTED_DataEdition=02
  DTED_DigitizingSystem=SRTM
  DTED_HorizontalAccuracy=0013
  DTED_HorizontalDatum=WGS84
  DTED_MaintenanceDate=0000
  DTED_MaintenanceDescription=0000
  DTED_MatchMergeDate=0000
  DTED_MatchMergeVersion=A
  DTED_NimaDesignator=DTED1
  DTED_OriginLatitude=0430000N
  DTED_OriginLongitude=0730000W
  DTED_PartialCellIndicator=00
  DTED_Producer=USCNIMA
  DTED_RelHorizontalAccuracy=NA
  DTED_RelVerticalAccuracy=0006
  DTED_SecurityCode_DSI=U
  DTED_SecurityCode_UHL=U
  DTED_UniqueRef_DSI=F19 053
  DTED_UniqueRef_UHL=F19 053
  DTED_VerticalAccuracy_ACC=0006
  DTED_VerticalAccuracy_UHL=0006
  DTED_VerticalDatum=E96
Corner Coordinates:
Upper Left  ( -73.0004167,  44.0004167) ( 73d 0' 1.50"W, 44d 0' 1.50"N)
Lower Left  ( -73.0004167,  42.9995833) ( 73d 0' 1.50"W, 42d59'58.50"N)
Upper Right ( -71.9995833,  44.0004167) ( 71d59'58.50"W, 44d 0' 1.50"N)
Lower Right ( -71.9995833,  42.9995833) ( 71d59'58.50"W, 42d59'58.50"N)
Center      ( -72.5000000,  43.5000000) ( 72d30' 0.00"W, 43d30' 0.00"N)
```

This appears to use the AREA model for georeferencing rather than the POINT model. Also,  REPORT_COMPD_CS=TRUE gdalinfo n43.dt1 is not reporting the compound cs (EGM96).

**Comment by rouault** [comment]
GDAL will always report pixel coordinates with a pixel-is-area / pixel-corner convention, whatever the value of AREA_OR_POINT is. This is by design

For the compound CRS issue, the DTED driver only reports the horizontal CRS as the SRS.

**Comment by hobu** [comment]
> whatever the value of AREA_OR_POINT is. This is by design

For this driver, the interpretation is wrong though. It's a pixel-is-area interpretation. I wonder if there's ever a time when we can reconsider this "design". Even having per-driver metadata would be helpful here to disambiguate.

**Comment by rouault** [comment]
> For this driver, the interpretation is wrong though

Is there documentation explaining what space (ie point vs area) takes each grid value for DTED ?

**Comment by hobu** [comment]
https://dds.cr.usgs.gov/srtm/version2_1/Documentation/MIL-PDF-89020B.pdf 

> "The locations of elevation posts are defined by the intersections of rows and columns within a matrix. "

This implies Pixel-is-Point to me.

**Comment by msmitherdc** [comment]
Another way to look at it is also the reported extents. This is a 1x1 degree geocell but gdal reported it not aligned with the lat/lon boundaries. This is contrast to SocetGXP as shown above.

**Comment by msmitherdc** [comment]
```
3.5.1 One-degree cell. A data file of DTED Level 0, DTED Level 1 or
DTED Level 2 is a 1° by 1° cell defined by whole degree latitude and longitude
lines on WGS. A DTED file shall not cross whole degree latitude or longitude
lines.
```

**Comment by rouault** [comment]
> This is a 1x1 degree geocell but gdal reported it not aligned with the lat/lon boundaries

yes, GDAL uses a pixel-is-area convention to report the geotransform whatever AREA_OR_POINT mentions (AREA_OR_POINT is a hint on the interpretation of the data, not the georeferencing). This is what I mean by "by design". If you use that convention of pixel-is-area, you have to apply a half pixel shift, so that the common row/column of neighbouring tiles overlaps

**Comment by jratike80** [comment]
I think that pixel is point vs. pixel is area is handled correctly in this case but the logic with the anchor point location and how the point/area metadata affects on the reported extent is not chrystal clear. The image below illustrates how I have understood it.

In this example case gdalinfo reports these facts:
```
Origin = (-73.000416666666666,44.000416666666666)
Pixel Size = (0.000833333333333,-0.000833333333333)
AREA_OR_POINT=Point

```
How to read it:
- The top-left corner of the top-left pixel is at (-73.000416666666666,44.000416666666666)
- But hey, it is an pixel-is-point type of image and it means that the anchor point is not there
- Calculate (OriginX + half-a-pixel) and (OriginY - half-a-pixel) = (-73,44)
- This is the point on Earth where the height in DEM has been measured.

With pixel-is-area metadata gdalinfo would report that the origin is at (-73,44) and the interpretation of the value in DEM would be "the average height of the area that is covered by the pixel having its top-left corner at (-73,44)".

The hard part for me was to accept that in the pixel-is-area case the anchor point is not at the centre or the area that the pixel value is presenting but at the corner. Somehow the logic feels wrong but I do not think about it any more.

![pixel-is-point-vs-pixel-is-area](https://user-images.githubusercontent.com/1751612/78755440-d5a00e80-7981-11ea-9cf2-2ae2c99111a8.png)

**Comment by jratike80** [comment]
> 
> 
> GDAL will always report pixel coordinates with a pixel-is-area / pixel-corner convention, whatever the value of AREA_OR_POINT is. This is by design

I clarify that this does not apply to gdalinfo. It is reporting different corner coordinates for pixel-is-point and pixel-is-area images that are having exactly same TIFF tags as ModelTiepointTag and ModelPixelScaleTag.
