### ISSUE TITLE
Python/OGR layer.DeleteFeature() not working in GDAL v 2.2.2

### ISSUE THREAD

**Issue by mwooten3** [OSGeo/gdal#2387]
## Expected behavior and actual behavior.

I believe this is a bug. I am trying to iterate through features in Python and delete items from a shapefile if a criteria is met. I read that with GDAL 2.2 the issue of deletions not actually being applied to the resultant dataset was resolved without having to run dataset.ExecuteSQL('REPACK ' + layer.GetName()),, but even with that in the code features are not actually being deleted.

Printing "cnt" reveals that there are over a thousand features that should be deleted. But the resulting shapefile has the same amount of features as it did in the beginning.

## Steps to reproduce the problem.

In Python:

    drv = ogr.GetDriverByName("ESRI Shapefile")
    ds = drv.Open(shp)
    layer = ds.GetLayer()
    cnt=0

    for feature in layer:

        lon = feature.GetGeometryRef().Centroid().GetX()
        lat = feature.GetGeometryRef().Centroid().GetY()

        # this is not actually the criteria but for simplicity sake:
        if lon > 50 and lat < 0:

            layer.DeleteFeature(feature.GetFID())
            ds.ExecuteSQL('REPACK ' + layer.GetName())

            cnt+=1

            continue # Do nothing else

        layer.SetFeature(feature)

    ds = layer = feature = None

    print cnt

## Operating system

Debian GNU/Linux 8 (jessie)

## GDAL version and provenance

GDAL 2.2.2

**Comment by jratike80** [comment]
This is a bug tracker. If it is possible that there is some issue in your code the preferred first contact point is the gdal-dev mailing list.

There are a few Python tests that use REPACK in the GDAL shapefile autotest https://github.com/OSGeo/gdal/blob/master/autotest/ogr/ogr_shape.py.  Please check them and compare with your code.

**Comment by rouault** [comment]
Deleting a feature from a layer & repacking while iterating over it is a bad idea. You'd better collect the FID in the loop, then delete them in a second loop, and finally repack

**Comment by mwooten3** [comment]
That still did not work @rouault. I assumed this was a bug, my apologies. I will move this issue over to the mailing list.
