### ISSUE TITLE
importFromProj4(...+wktext") not working as documented

### ISSUE THREAD

**Issue by dg0yt** [OSGeo/gdal#2392]
(Edits: 1. Format changed from WKT2_2018 to WKT1_GDAL. 2. Added result from OGRExportToProj4.)

## Expected behavior and actual behavior.

`+wktext` is [documented](https://gdal.org/api/ogrspatialref.html?highlight=wktext#_CPPv4N19OGRSpatialReference15importFromProj4EPKc) to be 
> meaning “embed the entire PROJ string in the WKT and use it literally when converting back to PROJ format”. 
> For example: “+proj=nzmg +lat_0=-41 +lon_0=173 +x_0=2510000 +y_0=6023150 +ellps=intl +units=m +nadgrids=nzgd2kgrid0005.gsb +wktext”
> will be translated as :
>
> ~~~
> PROJCS["unnamed",
>    GEOGCS["International 1909 (Hayford)",
>        DATUM["unknown",
>            SPHEROID["intl",6378388,297]],
>        PRIMEM["Greenwich",0],
>        UNIT["degree",0.0174532925199433]],
>    PROJECTION["New_Zealand_Map_Grid"],
>    PARAMETER["latitude_of_origin",-41],
>    PARAMETER["central_meridian",173],
>    PARAMETER["false_easting",2510000],
>    PARAMETER["false_northing",6023150],
>    UNIT["Meter",1],
>    EXTENSION["PROJ4","+proj=nzmg +lat_0=-41 +lon_0=173 +x_0=2510000
>               +y_0=6023150 +ellps=intl  +units=m +nadgrids=nzgd2kgrid0005.gsb +wktext"]]
> 

However, what I get now for "WKT1_GDAL" with GDAL 3.0.4 is:

~~~
PROJCS["unknown",
    GEOGCS["unknown",
        DATUM["Unknown based on International 1909 (Hayford) ellipsoid",
            SPHEROID["International 1909 (Hayford)",6378388,297],
            EXTENSION["PROJ4_GRIDS","nzgd2kgrid0005.gsb"]],
        PRIMEM["Greenwich",0,
            AUTHORITY["EPSG","8901"]],
        UNIT["degree",0.0174532925199433,
            AUTHORITY["EPSG","9122"]]],
    PROJECTION["New_Zealand_Map_Grid"],
    PARAMETER["latitude_of_origin",-41],
    PARAMETER["central_meridian",173],
    PARAMETER["false_easting",2510000],
    PARAMETER["false_northing",6023150],
    UNIT["metre",1,
        AUTHORITY["EPSG","9001"]],
    AXIS["Easting",EAST],
    AXIS["Northing",NORTH]]
~~~

i.e. GDAL does not seem to try to  “embed the entire PROJ string in the WKT". I wonder if this is intentional?

However it seems to work like GDAL would "use it literally when converting back to PROJ format”, except for the missing `+wktext`:

~~~
+proj=nzmg +lat_0=-41 +lon_0=173 +x_0=2510000 +y_0=6023150 +ellps=intl +nadgrids=nzgd2kgrid0005.gsb +units=m +no_defs
~~~

I stumbled over this when I tried to understand *why* I was adding `+wktext` to PROJ specs after I found that this keyword caused trouble when attempting coordinate transformations from `+init=epsg:27700 +wktext` to `WGS84`. The is no difference in OSRExportToProj4 output for `+init=epsg:27700 +wktext` vs. `+init=epsg:27700`, but there is a difference in OGR coordinate transformations.

## Steps to reproduce the problem.

~~~
void gdal_wktext_test(const char *spec)
{
	// Cf. OgrFileExport::setupGeoreferencing
	auto* map_srs = OSRNewSpatialReference(nullptr);
	OSRSetProjCS(map_srs, "Projected map SRS");
	OSRSetWellKnownGeogCS(map_srs, "WGS84");
	assert(OSRImportFromProj4(map_srs, spec) == OGRERR_NONE);
	char *pszWKT = nullptr;
	const char* apszOptions[] = { "FORMAT=WKT1_GDAL", "MULTILINE=YES", nullptr };
	assert(OSRExportToWktEx(map_srs, &pszWKT, apszOptions) == OGRERR_NONE);
	printf( "%s:\n", spec );
	printf( "%s\n\n", pszWKT );
	CPLFree(pszWKT);
	assert(OSRExportToProj4(map_srs, &pszWKT) == OGRERR_NONE);
	printf( ">>>PROJ4:\n");
	printf( "%s\n\n", pszWKT );
	CPLFree(pszWKT);
	OSRDestroySpatialReference(map_srs);
}

int main()
{
	gdal_wktext_test("+proj=nzmg +lat_0=-41 +lon_0=173 +x_0=2510000 +y_0=6023150 +ellps=intl"
	                 " +units=m +nadgrids=nzgd2kgrid0005.gsb +wktext");
	return 0;
}
~~~

## Operating system

macOS, Windows, Linux

## GDAL version and provenance

3.0.4 (source code)

**Comment by rouault** [comment]
+wktext should be a no-op now with PROJ >= 6, so I've removed mention from it in the doc. The fact that it made a difference for "+init=epsg:27700 +wktext " vs "+init=epsg:27700" in coordinate transformation was a bug in PROJ, which I've fixed to
