### ISSUE TITLE
How to convert raster line to vector line?

### ISSUE THREAD

**Issue by sanersbug** [OSGeo/gdal#2398]
windwos 7 
python 2.7.12
GDAL 2.2.4

My raster image is single line ,but when i use following code , i get double vector line , how to get single vector line ,any one know it ???

    border_path = "D:/2/tool/test/border.tif"
    border_driver = gdal.Open(border_path)
    border_band = border_driver.GetRasterBand(1)
    border_mask = border_band.GetMaskBand()
    dst_filename = 'D:/2/tool/test/temp.shp'
    frmt = GetOutputDriverFor(dst_filename)
    drv = ogr.GetDriverByName(frmt)
    dst_ds = drv.CreateDataSource(dst_filename)
    
    dst_layername = 'out'
    srs = osr.SpatialReference(wkt=border_driver.GetProjection())
    # dst_layer = dst_ds.CreateLayer(dst_layername, geom_type=ogr.wkbPolygon, srs=srs)
    dst_layer = dst_ds.CreateLayer(dst_layername, geom_type=ogr.wkbLineString, srs=srs)

    dst_fieldname = 'DN'
    fd = ogr.FieldDefn(dst_fieldname, ogr.OFTInteger)
    dst_layer.CreateField(fd)
    dst_field = -1

    options = []
    options.append('DATASET_FOR_GEOREF=' + border_path)
    prog_func = gdal.TermProgress_nocb
    gdal.Polygonize(border_band, border_mask, dst_layer, dst_field, options,
                         callback=prog_func)

    srcband = None
    src_ds = None
    dst_ds = None
    mask_ds = None

![image](https://user-images.githubusercontent.com/31174846/79036004-494a5180-7bf6-11ea-868f-6a5eca7cb67c.png)

![image](https://user-images.githubusercontent.com/31174846/79035978-07b9a680-7bf6-11ea-8319-218938b59c77.png)

**Comment by rouault** [comment]
"""IMPORTANT: Do NOT use GitHub to post any questions or support requests!
           They will be closed immediately and ignored.
"""
