### ISSUE TITLE
postgresql search_path ignored with ogr/gdal utilities

### ISSUE THREAD

**Issue by saultdon** [OSGeo/gdal#2400]
## Steps to reproduce the problem.
Looks like a lot of the GDAL utilities ignore search_path when using schemas=, active_schema= in the connection string.

This is kind of a problem when the postgis extension is not installed into the public schema, but somewhere else.

psql --
```
CREATE SCHEMA postgis;
CREATE EXTENSION postgis SCHEMA postgis;
```

gdal --
```
ogrinfo -ro PG:"dbname=${db} user=${db_user} active_schema=vri"                                   :(  =100%
ERROR 1: ERROR:  function postgis_version() does not exist
LINE 1: SELECT postgis_version()
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

INFO: Open of `PG:dbname=${db} user=${db_user} active_schema=vri'
      using driver `PostgreSQL' successful.
ERROR 1: ERROR:  relation "geometry_columns" does not exist
LINE 1: ... JOIN pg_namespace n ON c.relnamespace=n.oid JOIN geometry_c...
                                                             ^

ERROR 1: ERROR:  relation "geometry_columns" does not exist
LINE 1: ... JOIN pg_namespace n ON c.relnamespace=n.oid JOIN geometry_c...
```

## Operating system

Arch Linux 64-bit 5.6.3 (kernel)

## GDAL version and provenance

GDAL 3.0.4 64-bit

**Comment by rouault** [comment]
I can see several options:
- extend the values accepted by active_schema to support comma separated schemas, so you could specify active_schema=vri,postgis
- add a new postgis_schema=xxxx option that would be combined with active_schema.
Both would result in setting search_path.

Another option would be to automatically determine in which schema postgis is with something like
"SELECT n.nspname from pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace WHERE  proname = 'postgis_version'"

@jratike80 any opinions ?

**Comment by rouault** [comment]
> Another option would be to automatically determine in which schema postgis

I've decided for that in PR #2405

**Comment by jratike80** [comment]
Automatic detection is fine from the users point of view. Is there a need to consider some corner cases like PostGIS installed into both/all schemas? Or even different versions of PostGIS?

**Comment by rouault** [comment]
> Is there a need to consider some corner cases like PostGIS installed into both/all schemas? Or even different versions of PostGIS?

It will pick up the first (as the first returned by a SQL request, that is unspecified) schema that has a postgis_version function, in case there are several ones. I doubt it makes sense in a given database to have multiple PostGIS versions, and given there's a native C library behind, that would likely result in runtime crashes.
