### ISSUE TITLE
v3.0.2: Build failure on CentOS inside Docker

### ISSUE THREAD

**Issue by mjsteinbaugh** [OSGeo/gdal#2402]
## Install script

Attempting to install GDAL inside Docker using this build script:
https://github.com/acidgenomics/koopa/blob/master/os/linux/bin/install-gdal

Script is confirmed to work with Debian 10, Ubuntu 18 LTS, and Fedora 31.
I'm only seeing this error consistently on CentOS 8.

## Steps to reproduce the problem

```sh
# Using CentOS 8 Docker image.
docker pull centos
docker run -it centos

# Install koopa.
# https://koopa.acidgenomics.com/
curl -sSL https://koopa.acidgenomics.com/install \
    | bash -s -- --non-interactive

# Activate koopa and run VM configuration script.
source /usr/local/koopa/bin/koopa

# Stepwise configuration:
install-python  # 3.8.2
install-sqlite  # 3.30.1
install-proj    # 6.3.1
install-gdal    # 3.0.2

# Or automatic VM config:
configure-vm
```

## Operating system

CentOS 8

## GDAL version and provenance

- proj    6.3.1
- sqlite  3.30.1
- python  3.8.2

Build error log is attached.

Best,
Mike

[gdal-centos-build-error.txt](https://github.com/OSGeo/gdal/files/4476414/gdal-centos-build-error.txt)

**Comment by rouault** [comment]
The error seems to be:
```
jpeg2000dataset.cpp:40:10: fatal error: jasper/jasper.h: No such file or directory
 #include <jasper/jasper.h>
          ^~~~~~~~~~~~~~~~~
```
So I assume that on CentOS, the jasper header gets installed somewhere else ?
Anyway I'd suggest not to build against Jasper which is a bit abandonned, and rather use libopenjp2

**Comment by mjsteinbaugh** [comment]
Nice, thanks I'll take a look into that today.

**Comment by mjsteinbaugh** [comment]
Potentially related: #1708

**Comment by mjsteinbaugh** [comment]
@rouault Thanks for your help. Enforcing the use of `openjpeg` instead of `jasper` fixed my build issue on CentOS. For future reference in case any one else comes across this in a search, here are some useful steps:

On Fedora / RHEL / CentOS, install `openjpeg2-devel`.
On Debian / Ubuntu, install `libopenjp2-7-dev`.

For the `configure` step, set these flags: `--with-openjpeg`, `--without-jasper`.
