### ISSUE TITLE
gdal raises an error and a warning when generating contours for a DTED file with an invalid CRC but still produces an output and returns an exit code of 0

### ISSUE THREAD

**Issue by owvarley** [OSGeo/gdal#2410]
## Expected behavior and actual behavior.

I modified a DTED tile and changed the value of a height post away from its original value. I was expecting that running gdal_contour with DTED_VERIFY_CHECKSUM=YES would return an error and **not** generate the contours as the checksum was incorrect.

The command use was:
``` 
gdal_contour -i 15.24 -a height n51_preprocessed.dt1 test.shp
```

This was using the DTED tile contained within this zip file ([n51_preprocessed.zip](https://github.com/OSGeo/gdal/files/4481439/n51_preprocessed.zip))

The observed behaviour was that GDAL reported:
```
Warning 1: The DTED driver has found a computed and read checksum that do not match at column 383. Computed 0x1B86C, read 0x1B87B

ERROR 1: n51_preprocessed.dt1, band 1: IReadBlock failed at X offset 383, Y offset 0: The DTED driver has found a computed and read checksum that do not match at column 383. Computed 0x1B86C, read 0x1B87B
```
It still generates the shapefile for the DTED tile and returns an exit code of 0. This means I am unable to catch the error using the return code from gdal_contour. Should this not return a non-zero return code?

## Steps to reproduce the problem.

1. Set the environment variable DTED_VERIFY_CHECKSUM to YES.
2. Unzip the file ([n51_preprocessed.zip](https://github.com/OSGeo/gdal/files/4481439/n51_preprocessed.zip)) 
3. Execute the command ```gdal_contour -i 15.24 -a height n51_preprocessed.dt1 test.shp```

## Operating system

Debian Stretch Slim

## GDAL version and provenance

GDAL 3.1.0dev-b9bf325d1fb4f6d3a9d84769dd36d08f260f4cfb, released 2019/11/23

**Comment by owvarley** [comment]
@rouault thanks for the rapid resolution!

**Comment by Ryanf55** [comment]
Is this expected to trigger a checksum error?
```
$ gdallocationinfo n51_preprocessed.dt1 -wgs84 -3.2 51.8
Report:
  Location: (480P,240L)
  Band 1:
    Value: 390
$ env | grep DTED
DTED_VERIFY_CHECKSUM=YES
```

I don't see one, and am seeing this in my application code. `RasterIo` only reports a checksum error if the region requested is large enough. Single-point query does not hit it.

**Comment by rouault** [comment]
> Single-point query does not hit it.

DTED data is organized by columns. The checksum error occurs on column 383. So if you don't read that faulty column, you don't get errors as data is valid

**Comment by Ryanf55** [comment]
Got it. Seems like it might be worthwhile reading a single column of data on application bootup to ensure the file is not entirely corrupted?

**Comment by rouault** [comment]
> Seems like it might be worthwhile reading a single column of data

a single line you mean (that will effectively trigger reading the whole file), so that all columns are read

**Comment by Ryanf55** [comment]
Yep, both. I appreciate the recommendations (on an old issue). Hopefully this helps someone else too!
