### ISSUE TITLE
Docker usage example does not work on Mac

### ISSUE THREAD

**Issue by pgoldtho** [OSGeo/gdal#2419]
## Expected behavior and actual behavior.
```
docker run --rm -v /home:/home osgeo/gdal:alpine-normal-latest ogrinfo $PWD/S_FLD_HAZ_AR.shp
```
returns an error:
```
FAILURE:
Unable to open datasource `/Users/pgoldtho/S_FLD_HAZ_AR.shp' with the following drivers.
  -> PCIDSK
  -> netCDF
  -> PDS4 
....
```
This is because the the Mac has a `/Users` directory instead of `/home`. Swapping the positions of `$PWD` and `/home` fixes the problem:
```
docker run --rm -v $PWD:/home osgeo/gdal:alpine-normal-latest ogrinfo /home/S_FLD_HAZ_AR.shp
```
Returns:
```
INFO: Open of `/home/S_FLD_HAZ_AR.shp'
      using driver `ESRI Shapefile' successful.
1: S_FLD_HAZ_AR (Polygon) 
```

## Steps to reproduce the problem.
Follow usage instructions at the bottom of page
[https://github.com/OSGeo/gdal/tree/master/gdal/docker](https://github.com/OSGeo/gdal/tree/master/gdal/docker)

## Operating system

macOS 10.15.4

## GDAL version and provenance

`docker run --rm osgeo/gdal:alpine-normal-latest ogrinfo --version`
GDAL 3.1.0dev-56f70ba0d99f1c2e0226f6092744dcb51bb24767, released 2020/04/18

**Comment by rouault** [comment]
Just swapping will not cover all uses cases I had in mind, like being have to open a file somewhere else in /home, but this is just an example, and Mac users will be hopefully smart enough to adapt the example to their own OS. I didn't even know that a Linux image could work on Mac.
Anyway, feel free to submit a PR with a specific example for Mac is you wish.
That should be something like -v /Users:/Users probably.

**Comment by pgoldtho** [comment]
@rouault the error message made it look like gdal found the file but was not able to open it.  I assumed that meant an issue with the shapefile.  It took me a while to figure out this was a problem with the volume mount.

**Comment by rouault** [comment]
>  It took me a while to figure out this was a problem with the volume mount.

ok, you can easily propose a Mac specific example by editing https://github.com/OSGeo/gdal/edit/master/gdal/docker/README.md and submitting a pull request

**Comment by pgoldtho** [comment]
done see https://github.com/OSGeo/gdal/pull/2423
