### ISSUE TITLE
Use https and non-default UA in frmt_wms_openstreetmap_tms.xml

### ISSUE THREAD

**Issue by pnorman** [OSGeo/gdal#2421]
[frmt_wms_openstreetmap_tms.xml](https://github.com/OSGeo/gdal/blob/master/gdal/frmts/wms/frmt_wms_openstreetmap_tms.xml) specifies the <ServerUrl> with http://. [This should be https](https://twitter.com/OSM_Tech/status/1250017714430717953)

In addition to the URL, the user-agent should be specified in the example with an instruction to change it. "GDAL WMS driver (http://www.gdal.org/frmt_wms.html)" shows up high in our usage reports and we have no way to break it down by user in any more detail. If a user were misusing the tile servers with that user-agent we'd be forced to block all people using the default UA.

**Comment by rouault** [comment]
Feel free to submit a pull request.
