### ISSUE TITLE
nmake /f makefile.vc NMAKE :fatal error U1077 :"vs2019/c1.exe" return code "0x2"

### ISSUE THREAD

**Issue by EyesUP** [OSGeo/gdal#2425]
hi the Technology Daniel,Thanks for providing such a powerful tool. When I user GDAL3.0.4，I encountered some problems,please also answer for me.Thank U
when I use "x64 Native Tools Command Prompt for 2019" to initialize GDAL3.0.4，the code used is "nmake /f makefile.vc /i".The following erro occurred:
![image](https://user-images.githubusercontent.com/22089247/79728430-81514300-8320-11ea-852b-509af4d94de2.png)

**Comment by rouault** [comment]
You probably need to add WIN64=1

**Comment by EyesUP** [comment]
> You probably need to add WIN64=1

Thanks for replying to me.
When I add the parameter you said .I still reported the same error.
This is the code I used: "nmake /f makefile.vc /i WIN64=1"

**Comment by EyesUP** [comment]
> You probably need to add WIN64=1

I have changed the "nmake.opt",WIN64 = YES
![image](https://user-images.githubusercontent.com/22089247/79732921-e9a32300-8326-11ea-8821-6eb002335f6f.png)
