### ISSUE TITLE
Issue with creating SpatialReference instance

### ISSUE THREAD

**Issue by kavinder-Gupta** [OSGeo/gdal#2433]
## Expected behavior and actual behavior.

We are using GDAL 3.0.4 with projlib 6.2 in our application.

When we create a CRS using spatialReference.ImportFromEPSG(3857). The resultant CRS unit is in Metric. 

We have converted its unit from Meter to Foot using SpatialReference.SetLinearUnitsAndUpdateParameters("Foot",0.3048).

Which gets reflected in the object correctly.

But, when we export the updated SpatialReference to ProjWKT (using spatialReference.ExportToProj4()), we get the following output:

ProjWKT: +proj=merc +a=6378137 +b=6378137 +lat_ts=0 +lon_0=0 +x_0=0 +y_0=0 +k=1 +units=m +nadgrids=@null +wktext +no_defs

The above Proj wkt state that, the CRS unit is Meter. Although we have changed the unit to feet earlier.

Alternatively, when we export its WKT (using spatialReference.ExportToWkt) the exported wkt (below) clearly shows the CRS is in the international foot.

WKT: PROJCS["WGS 84 / Pseudo-Mercator",GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563]],PRIMEM["Greenwich",0],UNIT["degree",0.0174532925199433]],PROJECTION["Mercator_1SP"],PARAMETER["central_meridian",0],PARAMETER["scale_factor",1],PARAMETER["false_easting",0],PARAMETER["false_northing",0],UNIT["International Foot",0.3048]]

Also, when we try to create a new SpatialReference instance from the above WKT the SpatialReference has been created with the Metric unit instead of the International Foot unit.

We think proj database is fetching the unit incorrectly, please suggest a way to handle this issue.

## Expected behavior and actual behavior.

After converting a spatialReference unit from Meter to Foot using SpatialReference.SetLinearUnitsAndUpdateParameters("Foot",0.3048), it should be reflected in both the WKT as well as ProjWKT and when we create a new spatialReference instance using the above WKT, then the SpatialReference instance should be created with the International Foot unit 

## Steps to reproduce the problem.

Describe above

## Operating system

Windows 10 64-bit

## GDAL version and provenance

GDAL 3.0.4 with projlib 6.2

**Comment by rouault** [comment]
This is a PROJ issue. Investigating
