### ISSUE TITLE
Using 'BAG' driver option CreateCopy() 

### ISSUE THREAD

**Issue by dhasmartie** [OSGeo/gdal#2434]
Driver driver = null;
String src_filename = "C:\\vd_test\\nominal_only.bag";
String dst_filename = "C:\\vd_test\\nominal_only_out.bag";
        
Dataset src_ds = gdal.Open( src_filename);       
driver = gdal.GetDriverByName("BAG");    
Dataset dst_ds = driver.CreateCopy(dst_filename, src_ds);

ERROR 6: BAG driver requires a source dataset with a projection
ERROR 1: PROJ: proj_create_from_wkt: Cannot find proj.db
ERROR 1: PROJ: proj_as_wkt: Cannot find proj.db
ERROR 1: PROJ: proj_create_from_database: Cannot find proj.db
ERROR 1: PROJ: proj_as_wkt: Cannot find proj.db
ERROR 1: PROJ: proj_create: Cannot find proj.db
ERROR 1: PROJ: proj_create: unrecognized format / unknown name
ERROR 1: Cannot instantiate source_crs

**Comment by rouault** [comment]
You need to set the PROJ_LIB environement variable to point to the directory where the PROJ resource files are (including proj.db) : https://proj.org/resource_files.html

**Comment by rouault** [comment]
For the "BAG driver requires a source dataset with a projection", this might also be possibly connected with the fix done yesterday per https://github.com/OSGeo/gdal/pull/2428
