### ISSUE TITLE
gdalinfo fails with libjpeg.9.dylib symbol not found error

### ISSUE THREAD

**Issue by RWhite-EDR** [OSGeo/gdal#2440]
## Expected behavior and actual behavior.
gdalinfo --version should return the version of GDAL

Getting error:
dyld: Symbol not found: __cg_jpeg_resync_to_restart
  Referenced from: /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
  Expected in: /usr/local/lib/libjpeg.9.dylib
 in /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO

## Steps to reproduce the problem.
gdalinfo --version

## Operating system
macOS, Catalina, version 10.15.4

## GDAL version and provenance
gdal 2.4.4_4
brew gdal also brew osgeo-gdal

xcode command line tools are up to date.

gdal 2.4.4 appears to have been working last week.

I've tried a bunch of different things including trying to find an older version of the brew recipe for both jpeg and gdal.

**Comment by rouault** [comment]
Doesn't sound as an issue with GDAL upstream, but a homebrew packaging issue

**Comment by RWhite-EDR** [comment]
@rouault 

Sure, but it is failing with both the osgeo-gdal and gdal.  My guess is that something changed in the jpeg requirement that is conflicting with the OS ImageIO.framework on the mac.

Any suggestions where else to poke around?

**Comment by rouault** [comment]
report the issue to the maintainers of GDAL in homebrew. They'll better know.

**Comment by Geoyi** [comment]
Upgrade my OS system to Big Sur 11.6, and I saw this error as well. Have any of you solved it?

```
 $ gdalinfo --version 
dyld: Symbol not found: __cg_jpeg_resync_to_restart
  Referenced from: /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
  Expected in: /usr/local/lib/libjpeg.9.dylib
 in /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
```

**Comment by Geoyi** [comment]
Follow @RWhite-EDR's footsteps and found his solution 
`brew unlink libpng libtiff libjpeg giflib` 

and it helped to solve the issue.
