### ISSUE TITLE
Latest ubuntu-full docker image is broken

### ISSUE THREAD

**Issue by RemiSahl** [OSGeo/gdal#2450]
## Expected behavior and actual behavior.

I expected python and pip executables to be available inside latest ubuntu-full docker image.

## Steps to reproduce the problem.

```
$ docker pull osgeo/gdal:ubuntu-full-latest
$ docker run -it osgeo/gdal:ubuntu-full-latest python
docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"python\": executable file not found in $PATH": unknown.
ERRO[0000] error waiting for container: context canceled 
$ docker run -it osgeo/gdal:ubuntu-full-latest pip
docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"pip\": executable file not found in $PATH": unknown.
ERRO[0000] error waiting for container: context canceled 
```

**Comment by rouault** [comment]
use python3.
And if you want pip, apt install python3-pip (not installed since this brings 76 new packages!)

**Comment by RemiSahl** [comment]
Alright, thanks!

**Comment by rouault** [comment]
I've just added the installation of the python-is-python3 package which is a symlink from python to python3. Will be available tomorrow in the built images

**Comment by RemiSahl** [comment]
Thanks.
IMHO, I think the environment should maybe be more stable? I already had an issue previously https://github.com/OSGeo/gdal/issues/1915 and I keep having to modify my build routines accordingly.

I install my environment on top of your images in docker "FROM osgeo/gdal:ubuntu-full-latest" which means I have to constantly watch out for these issues. 
I imagine my problems will be less invasive once gdal 3.1 is officially released and I will be able to pin the version..

PS: I also noticed that I am unable to install cartopy using the latest image even though it worked last week.

**Comment by rouault** [comment]
> IMHO, I think the environment should maybe be more stable?

Always a tension between people asking for stability and people wanting to have bleeding edges. Those Docker images are more oriented for the later kind. The changes here are due to switching to Ubuntu 20.04. People can still use a past version of the Dockerfile if they need it
