### ISSUE TITLE
Bad conversion from EPSG:4979 to EPSG:2056 using WKT strings when target is bound to WGS84

### ISSUE THREAD

**Issue by hernando** [OSGeo/gdal#2454]
## Expected behavior and actual behavior.

With `gdaltransform`, I can get ellipsoidal heights transformed from WGS84 to the Bessel ellipsoid of EPSG:2056 if I do this (in bash):

    echo 6.561943 46.5173732  400 | ~/local/modules/gdal/debug/bin/gdaltransform -s_srs EPSG:4979 -t_srs "$(projinfo EPSG:2056 --3d -q -o WKT2:2019)"  
    ERROR 1: PCRaster driver was compiled against GDAL 3.1, but the current library version is 3.2
    ... more warnings like the above...
    2532722.85522802 1152162.50462102 348.578428523615

The result looks about right because as far as I know, the Bessel ellipsoid is 50 m "higher" in the region of the input coordinates.

But this doesn't work:

    echo 6.561943 46.5173732  400 | ~/local/modules/gdal/debug/bin/gdaltransform -s_srs EPSG:4979 -t_srs "$(projinfo EPSG:2056 --3d -q -o WKT2:2019 --boundcrs-to-wgs84)"  
    ....
    2532722.85522802 1152162.50462102 400

Using code I tried to do it with the WKT1:GDAL with TOWGS84 after promoting to 3D and it doesn't work either.

I originally thought this could be a problem in GDAL because in a previous commit it was printing a warning in this conversion, but it seems that the problem is in PROJ as `cs2cs` does the same thing. I decided to post the bug report here because I was working on a reproducer program based on GDAL that I thought could be useful. Let me know if you want me to move this issue to PROJ.

## Minimal code example to reproduce it

    #include <gdal/ogr_spatialref.h>
    #include <iostream>
    
    constexpr auto epsg4979 = R"WKT(GEOGCRS["WGS 84",DATUM["World Geodetic System 1984",ELLIPSOID["WGS 84",6378137,298.257223563,LENGTHUNIT["metre",1]]],PRIMEM["Greenwich",0,ANGLEUNIT["degree",0.0174532925199433]],CS[ellipsoidal,3],AXIS["geodetic latitude (Lat)",north,ORDER[1],ANGLEUNIT["degree",0.0174532925199433]],AXIS["geodetic longitude (Lon)",east,ORDER[2],ANGLEUNIT["degree",0.0174532925199433]],AXIS["ellipsoidal height (h)",up,ORDER[3],LENGTHUNIT["metre",1]],USAGE[SCOPE["unknown"],AREA["World (by country)"],BBOX[-90,-180,90,180]],ID["EPSG",4979]])WKT";
    
    constexpr auto epsg2056_3dWkt2 = R"WKT(PROJCRS["CH1903+ / LV95",BASEGEOGCRS["CH1903+",DATUM["CH1903+",ELLIPSOID["Bessel 1841",6377397.155,299.1528128,LENGTHUNIT["metre",1]],ID["EPSG",6150]],PRIMEM["Greenwich",0,ANGLEUNIT["degree",0.0174532925199433],ID["EPSG",8901]]],CONVERSION["Swiss Oblique Mercator 1995",METHOD["Hotine Oblique Mercator (variant B)",ID["EPSG",9815]],PARAMETER["Latitude of projection centre",46.9524055555556,ANGLEUNIT["degree",0.0174532925199433],ID["EPSG",8811]],PARAMETER["Longitude of projection centre",7.43958333333333,ANGLEUNIT["degree",0.0174532925199433],ID["EPSG",8812]],PARAMETER["Azimuth of initial line",90,ANGLEUNIT["degree",0.0174532925199433],ID["EPSG",8813]],PARAMETER["Angle from Rectified to Skew Grid",90,ANGLEUNIT["degree",0.0174532925199433],ID["EPSG",8814]],PARAMETER["Scale factor on initial line",1,SCALEUNIT["unity",1],ID["EPSG",8815]],PARAMETER["Easting at projection centre",2600000,LENGTHUNIT["metre",1],ID["EPSG",8816]],PARAMETER["Northing at projection centre",1200000,LENGTHUNIT["metre",1],ID["EPSG",8817]],ID["EPSG",19950]],CS[Cartesian,3],AXIS["(E)",east,ORDER[1],LENGTHUNIT["metre",1,ID["EPSG",9001]]],AXIS["(N)",north,ORDER[2],LENGTHUNIT["metre",1,ID["EPSG",9001]]],AXIS["ellipsoidal height (h)",up,ORDER[3],LENGTHUNIT["metre",1,ID["EPSG",9001]]]])WKT";
    
    constexpr auto epsg2056_Wkt1 = R"WKT(
    PROJCS["CH1903+ / LV95",GEOGCS["CH1903+",DATUM["CH1903+",SPHEROID["Bessel 1841",6377397.155,299.1528128,AUTHORITY["EPSG","7004"]],AUTHORITY["EPSG","6150"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4150"]],PROJECTION["Hotine_Oblique_Mercator_Azimuth_Center"],PARAMETER["latitude_of_center",46.9524055555556],PARAMETER["longitude_of_center",7.43958333333333],PARAMETER["azimuth",90],PARAMETER["rectified_grid_angle",90],PARAMETER["scale_factor",1],PARAMETER["false_easting",2600000],PARAMETER["false_northing",1200000],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AXIS["Easting",EAST],AXIS["Northing",NORTH],AUTHORITY["EPSG","2056"]])WKT";
    
    constexpr auto epsg2056_BoundWkt1 = R"WKT(PROJCS["CH1903+ / LV95",GEOGCS["CH1903+",DATUM["CH1903+",SPHEROID["Bessel 1841",6377397.155,299.1528128,AUTHORITY["EPSG","7004"]],TOWGS84[674.374,15.056,405.346,0,0,0,0],AUTHORITY["EPSG","6150"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4150"]],PROJECTION["Hotine_Oblique_Mercator_Azimuth_Center"],PARAMETER["latitude_of_center",46.9524055555556],PARAMETER["longitude_of_center",7.43958333333333],PARAMETER["azimuth",90],PARAMETER["rectified_grid_angle",90],PARAMETER["scale_factor",1],PARAMETER["false_easting",2600000],PARAMETER["false_northing",1200000],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AXIS["Easting",EAST],AXIS["Northing",NORTH],AUTHORITY["EPSG","2056"]])WKT";
    
    int main()
    {
        OGRSpatialReference inputSrs(epsg4979);
        OGRSpatialReference outputSrs(epsg2056_3dWkt2);
        OGRCoordinateTransformation* transformation = OGRCreateCoordinateTransformation(&inputSrs, &outputSrs);
    
        double position[] = {46.51737327402766, 6.561943218111992, 400.};
        std::cout << position[0] << " " << position[1] << " " << position[2] << std::endl;
        transformation->Transform(1, &position[0], &position[1], &position[2]); // Good
        std::cout << position[0] << " " << position[1] << " " << position[2] << std::endl;
    
        OGRSpatialReference outputSrs2(epsg2056_Wkt1);
        outputSrs2.PromoteTo3D(nullptr);
        OGRCoordinateTransformation* transformation2 = OGRCreateCoordinateTransformation(&inputSrs, &outputSrs2);
    
        double position2[] = {46.51737327402766, 6.561943218111992, 400.};
        transformation2->Transform(1, &position2[0], &position2[1], &position2[2]); // Good
        std::cout << position2[0] << " " << position2[1] << " " << position2[2] << std::endl;
    
        OGRSpatialReference outputSrs3(epsg2056_BoundWkt1);
        outputSrs3.PromoteTo3D(nullptr);
        OGRCoordinateTransformation* transformation3 = OGRCreateCoordinateTransformation(&inputSrs, &outputSrs3);
    
        double position3[] = {46.51737327402766, 6.561943218111992, 400.};
        transformation3->Transform(1, &position3[0], &position3[1], &position3[2]); // Bad
        std::cout << position3[0] << " " << position3[1] << " " << position3[2] << std::endl;
    }
## Operating system

Ubuntu 18.04 64 bit

## GDAL version and provenance

origin/v3.1.0RC1 compiled from source

**Comment by rouault** [comment]
Should be indeed reported to the PROJ tracker. But honestly  --boundcrs-to-wgs84 is a legacy feature, that should generally be avoided unless really needed, and that it doesn't work combined with --3d is a very very particular use case. 
I wouldn't bet too much on the appropriateness of considering the change in ellipsoidal height as relevant, but I don't know about the particulars about the "CH1903+ to WGS 84 (1)" transformation. Should be confirmed with Swiss geodetic authorities

**Comment by rouault** [comment]
What meks me doubt about the 3D aspect of the transformation is that in EPSG, there is only a CH1903+ geographic 2D CRS. But no corresponding record for a geographic 3D or geocentric CRS. Might be just that they are missing, or an indication that CH1903+ ellipsoidal heights are not well defined.

**Comment by hernando** [comment]
Maybe this is a corner case, but it got me scratching my head for a while to figure out why the height was transformed in some cases and not others until I discovered the reason, so I thought it was worth reporting for others. This problem probably happens with the Airy ellipsoid as well, although I haven't tried. I will follow your advice and avoid bonding to WGS84.

If you think it's not worth fixing, at least it should be documented as a known limitation in my opinion. I'll move the ticket tomorrow to PROJ if you are going to take any action, please let me know.

I have no answer about whether it's relevant to transform ellipsoidal heights between different ellipsoids, I would need to seek an expert opinion about it. In my opinion (as a software developer, not a surveyor), people who care about heights in a projected coordinate system should be using orthometric heights, so what really matters is that WGS84 ellipsoidal heights get converted to the target vertical CRS using the appropriate geoid model (which in the case of Switzerland is not free).

**Comment by hernando** [comment]
Regarding CH1903+ ellipsoidal heights, I would bet they are well defined because CHGeo2004 is defined over the Bessel ellipsoid as far as I know.
In fact, I've just checked https://www.swisstopo.admin.ch/en/maps-data-online/calculation-services/reframe.html and their online calculator allows to convert between `Ellipsoidal heights (on BESSEL)` and `National Height Network LNH95 (CHGeo2004)`

**Comment by rouault** [comment]
ok, interesting. Please create the corresponding PROJ issue. I might worked at making  --boundcrs-to-wgs84  and --3d work together, but no promise

**Comment by hernando** [comment]
Moved to OSGeo/PROJ#2202
