### ISSUE TITLE
(python) Seeming incompatibility between libgdal and libcfitsio on MacOS X

### ISSUE THREAD

**Issue by cbworden** [OSGeo/gdal#2456]
## Expected behavior and actual behavior.

Error when importing gdal:

``ImportError: dlopen(/Users/cbworden/anaconda3/envs/shakemap/lib/python3.8/site-packages/osgeo/_gdal.cpython-38-darwin.so, 2): Symbol not found: _crc32
  Referenced from: /Users/cbworden/anaconda3/envs/shakemap/lib/libgdal.26.dylib
  Expected in: /Users/cbworden/anaconda3/envs/shakemap/lib/libcfitsio.8.dylib
 in /Users/cbworden/anaconda3/envs/shakemap/lib/libgdal.26.dylib ``

## Steps to reproduce the problem.

import gdal

## Operating system

Darwin 17.7.0 Darwin Kernel Version 17.7.0: Sun Dec  1 19:19:56 PST 2019; root:xnu-4570.71.63~1/RELEASE_X86_64 x86_64

Happens on MacOS X 10.13, 10.14, 10.15

## GDAL version and provenance

  gdal               conda-forge/osx-64::gdal-3.0.4-py38h9f7df5a_6
  geos               conda-forge/osx-64::geos-3.8.1-h4a8c4bd_0
  cfitsio            conda-forge/osx-64::cfitsio-3.470-h35c4aa5_3

**Comment by rouault** [comment]
Seems to be a conda-forge specific issue . Perhaps GDAL needs to be rebuilt there ?  Actually I see it has been raised there as https://github.com/conda-forge/gdal-feedstock/issues/382
