### ISSUE TITLE
Geo .PDF to .tiff has a transparent background colour on macOS

### ISSUE THREAD

**Issue by JanC** [OSGeo/gdal#2457]
## Expected behavior and actual behavior.
Converting a .pdf to .tiff using gdal_translate creates a .tiff with transparent background

**Expected behavior**
I would expect the .tiff to have a white color as background as the source PDF does not contain any `NoData` value

**Screenshots**
**Source PDF:**
![Screenshot 2020-04-23 at 18 55 44](https://user-images.githubusercontent.com/707703/80300086-dadec500-8799-11ea-8fa9-a4d97d4bf620.png)

**Generated .tiff**

![Screenshot 2020-04-23 at 18 59 51](https://user-images.githubusercontent.com/707703/80300094-eaf6a480-8799-11ea-92b3-e39c019c7c81.png)

## Steps to reproduce the problem.

1. Install [homebrew-osgeo4mac](https://github.com/OSGeo/homebrew-osgeo4mac)
2. Download this [00989I11.PDF](https://www.dropbox.com/s/7nw82o89cjew3zl/00989I11.PDF?dl=0)
3. run `gdal_translate 00989I11.PDF 00989I11.tiff`
4. Open the resulting [00989I11.tiff](https://www.dropbox.com/s/o3bx8gi5rd8blae/00989I11.tiff?dl=0)

## Operating system
macOS 10.15.3

## GDAL version and provenance
- homebrew-osgeo4mac

```
gdalinfo --version
GDAL 3.0.4, released 2020/01/28
```

## Notes
- The `gdalinfo` of the .pdf is:
```
    gdalinfo 00989I11.PDF
    Driver: PDF/Geospatial PDF
    Files: 00989I11.PDF
    Size is 806, 1237
    Coordinate System is:
    PROJCRS["",
        BASEGEOGCRS["NAD83",
            DATUM["North American Datum 1983",
                ELLIPSOID["GRS 1980",6378137,298.2572221,
                    LENGTHUNIT["metre",1]],
                ID["EPSG",6269]],
            PRIMEM["Greenwich",0,
                ANGLEUNIT["Degree",0.0174532925199433]]],
        CONVERSION["unnamed",
            METHOD["Lambert Conic Conformal (2SP)",
                ID["EPSG",9802]],
            PARAMETER["Latitude of false origin",35.2372777777778,
                ANGLEUNIT["Degree",0.0174532925199433],
                ID["EPSG",8821]],
            PARAMETER["Longitude of false origin",-120.642611111111,
                ANGLEUNIT["Degree",0.0174532925199433],
                ID["EPSG",8822]],
            PARAMETER["Latitude of 1st standard parallel",45,
                ANGLEUNIT["Degree",0.0174532925199433],
                ID["EPSG",8823]],
            PARAMETER["Latitude of 2nd standard parallel",33,
                ANGLEUNIT["Degree",0.0174532925199433],
                ID["EPSG",8824]],
            PARAMETER["Easting at false origin",0,
                LENGTHUNIT["Inch",0.0254000508001],
                ID["EPSG",8826]],
            PARAMETER["Northing at false origin",0,
                LENGTHUNIT["Inch",0.0254000508001],
                ID["EPSG",8827]]],
        CS[Cartesian,2],
            AXIS["(E)",east,
                ORDER[1],
                LENGTHUNIT["Inch",0.0254000508001]],
            AXIS["(N)",north,
                ORDER[2],
                LENGTHUNIT["Inch",0.0254000508001]]]
    Data axis to CRS axis mapping: 1,2
    Origin = (-1807172.000000000000000,2042985.000000000000000)
    Pixel Size = (3334.000000000000000,-3335.000000000000000)
    Metadata:
      AUTHOR=
      CREATION_DATE=D:20190718071421-04'00'
      CREATOR=MicroStation 8.11.9.867 by Bentley Systems, Incorporated
      NEATLINE=POLYGON ((-1487388.02470535 -1654179.3669621,563048.661741154 -1654193.12139478,563073.777508997 1615063.22966106,-1487370.34966788 1615075.17034221,-1487388.02470535 -1654179.3669621))
      PRODUCER=Adobe PDF Library 9.0
      TITLE=00989I11
    Corner Coordinates:
    Upper Left  (-1807172.000, 2042985.000) (121d 9' 6.29"W, 35d42'19.70"N)
    Lower Left  (-1807172.000,-2082410.000) (121d 8'43.15"W, 34d45'28.56"N)
    Upper Right (  880032.000, 2042985.000) (120d23'40.84"W, 35d42'22.90"N)
    Lower Right (  880032.000,-2082410.000) (120d23'52.11"W, 34d45'31.72"N)
    Center      ( -463570.000,  -19712.500) (120d46'20.58"W, 35d13'57.63"N)
    Band 1 Block=806x1 Type=Byte, ColorInterp=Red
      Overviews: 403x619, 202x310, 101x155
      Mask Flags: PER_DATASET ALPHA 
      Overviews of mask band: 403x619, 202x310, 101x155
    Band 2 Block=806x1 Type=Byte, ColorInterp=Green
      Overviews: 403x619, 202x310, 101x155
      Mask Flags: PER_DATASET ALPHA 
      Overviews of mask band: 403x619, 202x310, 101x155
    Band 3 Block=806x1 Type=Byte, ColorInterp=Blue
      Overviews: 403x619, 202x310, 101x155
      Mask Flags: PER_DATASET ALPHA 
      Overviews of mask band: 403x619, 202x310, 101x155
    Band 4 Block=806x1 Type=Byte, ColorInterp=Alpha
      Overviews: 403x619, 202x310, 101x155
```

- The same command with the same input file creates a .tiff with a white color when using the Linux version of gdal:

**Linux output:**
<img width="707" alt="Screenshot 2020-04-26 at 08 54 03" src="https://user-images.githubusercontent.com/707703/80300275-84728600-879b-11ea-9ced-6c736b32fc1b.png">

I'm linking the original issue I opened on the osgeo4mac repo: https://github.com/OSGeo/homebrew-osgeo4mac/issues/1374

**Comment by rouault** [comment]
There's nothing Mac specific here. It can depend on how GDAL is built, and open option provided.
If GDAL is built with Pdfium support, then the BANDS open option will default to 4, RGBA, and a transparent background will be used
If GDAL is built only with Poppler support, then the BANDS open option will default to 3, RGB, and a white background will be used.
Actually that's a bit more complicated than that, the driver will driver to see if there are raster images in the PDF with a transparency mask, and in that case, it will switch to RGBA.

I've just improved https://gdal.org/drivers/raster/pdf.html to better reflect this
```
-  *GDAL_PDF_BANDS* = 3 or 4 : whether the PDF should be rendered as a
   RGB (3) or RGBA (4) image. The default value will depend on the PDF rendering
   used (Poppler vs PDFium) and on the content found in the PDF file (if an
   image with transparency is recognized, then 4 will be used). When 3 bands
   is selected, a white background is used.
```
So adding explicitly the -oo BANDS=3 open option should give you the result you expect.

**Comment by JanC** [comment]
Hi @rouault 

👍 thanks a lot for your explanation. It works indeed as documented.

I'm closing the issue
