### ISSUE TITLE
Output file names in gdal2tiles --xyz

### ISSUE THREAD

**Issue by thiagohersan** [OSGeo/gdal#2463]
## Expected behavior and actual behavior.
I expected the tiles generated from gdal2tiles to follow the pattern:
0/0/0.png
1/0/0.png
1/0/1.png
1/1/0.png
1/1/1.png
...

but when it gets to the 2/ directory I get:
2/0/1.png
2/0/2.png
2/0/3.png

There's no 2/0/0.png.

When I generate tiles with the kml option, all the expected kml files are there, but the png names are off by some offset. And it goes like that for all directories above 1/.

<img width="691" alt="Screen Shot 2020-04-30 at 11 42 17 PM" src="https://user-images.githubusercontent.com/850815/80778009-64491b00-8b3d-11ea-97da-ca13aed8ecb3.png">

## Steps to reproduce the problem.
Run:
```gdal2tiles.py --profile=raster --xyz test.jpg```

## Operating system
Ubuntu from Docker image (osgeo/gdal:ubuntu-small-3.0.4)

## GDAL version and provenance
GDAL 3.2.0dev-4bff89e8e5ef53034d5dcd4f92d868ad6cac3176, released 2020/05/01

**Comment by rouault** [comment]
CC @quipo Does --xyz makes sense with --profile=raster ?

**Comment by trinopoty** [comment]
The xyz filename convention is only a renamed version of `--profile=mercator`. It should have been implemented as a profile rather than a flag now that I think about it.

**Comment by rouault** [comment]
> It should have been implemented as a profile rather than a flag now that I think about it.

Perhaps we should accept --profile=xyz as well, and somewhat deprecate --xyz and error out if it is used with --profile != raster ?

**Comment by trinopoty** [comment]
Yes that's possible. Something like, if the `--xyz` flag is specified and profile is `mercator`, change the profile to `xyz`.

**Comment by rouault** [comment]
Actually, I'm thinking --xyz could probably make sense for profile=geodetic, even if it doesn't look like being implemented now. So probably just erroring out when --xyz and --profile != mercator would be sufficient for now

**Comment by trinopoty** [comment]
That also makes sense. I don't know enough about geodetic to know if xyz works for that or not.

**Comment by rouault** [comment]
> I don't know enough about geodetic to know if xyz works for that or not

there's no reason it could not work. This is just a matter of convention on the location of the y=0 tile. Can work potentially with any tiling scheme. It is just that the implementation restricts this to mercator for now.

@trinopoty Interested in submitting a PR to add the check ?

**Comment by trinopoty** [comment]
Sure. I'll try to submit a PR for this.
