### ISSUE TITLE
how to get or modify the feature dataset in ESRI's geodatabase ?

### ISSUE THREAD

**Issue by qq2898** [OSGeo/gdal#2469]
How to get the name, spatial-reference and other infomations about feature dataset in geodatabase? and can GDAL rename the feature dataset?

**Comment by mloskot** [comment]
When you open a new issue, you are supposed to actually read the [instructions included in the template]( https://raw.githubusercontent.com/OSGeo/gdal/master/.github/ISSUE_TEMPLATE.md).

```
Questions should go to the gdal-dev mailing list at
https://lists.osgeo.org/mailman/listinfo/gdal-dev
or other support forums. GitHub issues are for bug
reports and suggestions for new features.
```
