### ISSUE TITLE
AWS_PROFILE vs AWS_DEFAULT_PROFILE

### ISSUE THREAD

**Issue by blacha** [OSGeo/gdal#2470]
## Expected behavior and actual behavior.

All of the AWS SDK's I work with use `AWS_PROFILE` to configure which AWS profile to use 

- [Python](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html?highlight=aws_profile)
- [Nodejs](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/loading-node-credentials-shared.html) 
- [AWS CLI](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html)

Where as GDAL only uses `AWS_DEFAULT_PROFILE`

This means that when I want to use GDAL with a AWS SDK I have to set both `AWS_PROFILE` and  `AWS_DEFAULT_PROFILE`.

Is there a reason that `AWS_DEFAULT_PROFILE` is used over `AWS_PROFILE`?

## Steps to reproduce the problem.

`AWS_PROFILE=foo gdalinfo /vsis3/foo/bar`

## Operating system

ubuntu-small-latest

## GDAL version and provenance

Nightly Build (Docker ubuntu-small-latest)

**Comment by rouault** [comment]
Googling for AWS_DEFAULT_PROFILE shows that it was definitely used by AWS cli at some point (https://stackoverflow.com/questions/31012460/how-do-i-set-the-name-of-the-default-profile-in-aws-cli) . It might have been deprecated in favor of AWS_PROFILE now. Actually https://github.com/aws/aws-cli/issues/1748 and https://www.gitmemory.com/issue/boto/botocore/1725/490596498 seems to confirm a shift from AWS_DEFAULT_PROFILE to AWS_PROFILE

**Comment by blacha** [comment]
Awesome, Thanks for the quick response & fix!
