### ISSUE TITLE
OGR: broken handling of `POINT EMPTY`

### ISSUE THREAD

**Issue by craigds** [OSGeo/gdal#2472]
## Expected behavior and actual behavior.

There are two closely related bugs, but I figured it'd make sense to discuss them in one ticket rather than two.

### OGRGeometry.ExportToWkb() corrupts `POINT EMPTY`

```python
import binascii
from osgeo import ogr

p = ogr.CreateGeometryFromWkt('POINT EMPTY')
wkb = p.ExportToWkb()
print(f'wkb: {binascii.hexlify(wkb)}')

wkt = ogr.CreateGeometryFromWkb(wkb).ExportToWkt()
print(f'wkt: {wkt}')
```

This prints:

```
wkb: b'000000000100000000000000000000000000000000'
wkt: POINT (0 0)
```

I am aware that 'POINT EMPTY' has no direct equivalent in the WKB spec, however a common substitute is `POINT(nan nan)`. The GPKG spec uses this, and OGR handles _reading_ it:

```python
import binascii
from osgeo import ogr
wkb = b'\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\xF8\x7F\x00\x00\x00\x00\x00\x00\xF8\x7F'
print(f'wkb: {binascii.hexlify(wkb)}')
p = ogr.CreateGeometryFromWkb(wkb)
print(p.ExportToWkt())
```

which prints:

```
original: b'0101000000000000000000f87f000000000000f87f'
wkb:      b'0101000000000000000000f87f000000000000f87f'
wkt:      POINT EMPTY
```

It seems natural that OGR should also _produce_ this when exporting `POINT EMPTY` as WKB.

### CreateGeometryFromWkt() can't handle `'POINT(nan nan)'`

This bug is less of a problem, but is frustrating for testing the above. I had to start with some WKB as a constant above, because I can't create the geometry from WKT:

```python
from osgeo import ogr
>>> ogr.CreateGeometryFromWkt('POINT(nan nan)')
ERROR 5: OGR Error: Corrupt data
```

Varieties of capitalisation on 'nan' don't affect this

## Operating system

MacOS 10.15.3

## GDAL version and provenance

GDAL 3.0.3, built using https://github.com/koordinates/sno/blob/master/vendor/gdal/Makefile

**Comment by jratike80** [comment]
GeoPackage has also an empty geometry flag so it can handle all kinds of empty geometries (LINESTRING EMPTY, POLYGON EMPTY etc.).
I wonder what other WKB implementations will do when they meet wkb that presents empty point in a self-designed way that is not a part of the standard. You wrote that POINT(nan nan) is a common substitute. Could you mension some examples by name? I do know that OpenJUMP can handle all kind of empty geometries and separate empty points from empty polygons which may mean that JTS can do the same but I am not sure.

**Comment by rcoup** [comment]
@jratike80 GeoPackage specifies `NaN, NaN` for `POINT EMPTY`: http://www.geopackage.org/spec/#r152

> If the geometry is a Point, it SHALL be encoded with each coordinate value set to an IEEE-754 quiet NaN value. GeoPackages SHALL use big endian 0x7ff8000000000000 or little endian 0x000000000000f87f as the binary encoding of the NaN values. (This is because Well-Known Binary as defined in OGC 06-103r4 [9] does not provide a standardized encoding for an empty point set, i.e., 'Point Empty' in Well-Known Text.)

**Comment by rcoup** [comment]
background: reason it only affects POINT is that everything else in WKB (Linestring, Polygon, Multi*, etc) has some sort of a component/vertex count field, which is set to 0 for empty geometries. Point just directly encodes vertex values, with the logic being that any count would always be 1.

**Comment by rcoup** [comment]
Elsewhere:

* GEOS reads and writes WKT, but won't write WKB: https://trac.osgeo.org/geos/ticket/1005 (verified at 3.4.2)
* PostGIS round-trips: https://trac.osgeo.org/postgis/ticket/3181 (though see https://trac.osgeo.org/postgis/ticket/3426#comment:11 for complexities of NaN possibilities)

**Comment by mloskot** [comment]
PostGIS does (or used to do?) report any empty geometry as `GEOMETRYCOLLECTION EMPTY`
http://mateusz.loskot.net/post/2010/02/26/sqlgeometry-and-point-empty-in-wkb/

SQL Server reports it as MULTIPOINT with zero elements
http://mateusz.loskot.net/post/2011/10/22/update-on-sqlgeometry-and-point-empty-in-wkb/

**Comment by jratike80** [comment]
What I wrote about the empty flag and possibility to store also something that is equivalent to for example "POLYGON empty" was just to point out that it is possible to store empty geometries into a table that is fixed to contain only polygons in the gpkg_geometry_columns. The WKB part is always POINT EMPTY.

OpenJUMP is using GEOMETRYCOLLECTION EMPTY when it is does not exactly know what kind of empty geometries it is dealing with because geometrycollections accept anything and I used that as an example when I suggested to add a support for empty geometries into the GeoPackage standard.  The first drafts were missing that option. Perhaps it was Paul Ramsey who suggested the current implementasion.

**Comment by rouault** [comment]
Use ExportToIsoWkb() instead of ExportToWkb() to get a point with 2 NANs. This is probably an abuse to call this "IsoWkb", but this is how export to GeoPackage and PostGIS is done.

**Comment by jratike80** [comment]
Calling it IsoWkb is probably not so bad choice. See the answer by  Pepijn Van Eeckhoudt in https://gis.stackexchange.com/questions/109889/wkt-what-is-the-reasoning-behind-the-concept-of-a-point-empty.

**Comment by craigds** [comment]
Thanks for all the replies! 

> Use ExportToIsoWkb() instead of ExportToWkb() to get a point with 2 NANs.

That sounds like a great solution... but seems to have other implications. It looks to have different ways of marking the presense of ZM coordinates. Does this mean that ISO WKB geometries in general are not as portable?

e.g. can they be:
- parsed by `ogr.CreateGeometryFromWkb()`
- embedded directly in GPKG geometries
- handed directly to postgis

If so I guess that'd solve the problem entirely.

**Comment by rouault** [comment]
> It looks to have different ways of marking the presense of ZM coordinates.

Yes, GDAL's original way predates the final Simple Feature or ISO SQL/MM Part 3 specs, and use the 2.5D extension as per 99-402.

> Does this mean that ISO WKB geometries in general are not as portable?

No, just that they are not the GDAL-original way of encoding it, but should be supported since GDAL 2.0 with https://gdal.org/development/rfc/rfc49_curve_geometries.html

> e.g. can they be:
>    parsed by ogr.CreateGeometryFromWkb()
Yes

>    embedded directly in GPKG geometries
Yes, that's what the GPKG driver uses after adding the GPKG geometry header

>    handed directly to postgis
Similarly, that's what is done with PostGIS >= 2.2 after adding the EWKB geometry header

**Comment by craigds** [comment]
Awesome, thanks for that. It sounds like we should just switch to using that everywhere and it will solve the problem. This issue can probably be closed.
