### ISSUE TITLE
Larger number than field width - ESRI Shapefile Driver

### ISSUE THREAD

**Issue by anakaine** [OSGeo/gdal#2474]
## Expected behavior and actual behavior.

I expected to be able to write long numbers (eg Unix Epoch Timestamp in Seconds - 10 digits) to a field in a new shapefile using gdal.ContourGenerate. An error is thrown stating (example): `Warning 1: Value 1573660800 of field mdTmBrn of feature 866 not successfully written. Possibly due to too larger number with respect to field width `

## Steps to reproduce the problem.

Begin with a raster (geotiff) whose cell values are the second values of a unix epoch. eg: 1573660800.

I am using python, below, however, the issue is apparently also reproducible when using command-line tools to convert between gpkg and shp. 

`
    #make contours from the raster
    print('Setting up contours')
    indataset1 = gdal.Open(os.sep.join([output_dir, os.path.basename(sabre_out_dir)]) + 'mdTmBrn.tif', GA_ReadOnly)
    sr = osr.SpatialReference(indataset1.GetProjection())
    in1 = indataset1.GetRasterBand(1)
    dst_filename = os.sep.join([output_dir, os.path.basename(sabre_out_dir)]) + 'mdTmBrn_contour.shp'
    ogr_ds = ogr.GetDriverByName("ESRI Shapefile").CreateDataSource(dst_filename)
    #ogr_ds = ogr.GetDriverByName("GPKG").CreateDataSource(dst_filename)
    #contour_shp = ogr_ds.CreateLayer('contour')
    contour_shp = ogr_ds.CreateLayer('contour', sr)

    field_defn = ogr.FieldDefn("ID", ogr.OFTInteger)
    contour_shp.CreateField(field_defn)
    field_defn = ogr.FieldDefn("mdTmBrn", ogr.OFTReal)
    contour_shp.CreateField(field_defn)

    print('Making contours')
    #Generate Contourlines - ContourGenerate from https://gdal.org/python/
    gdal.ContourGenerate(
        in1,    #Band srcBand
        1800,      #double contourInterval
        0,      #double contourBase
        [],      #int fixedLevelCount
        0,      #int useNoData
        0,      #double noDataValue
        contour_shp, #Layer dstLayer
        0,      #int idField
        1       #int elevField
        )
`

## Operating system

Windows 10,
Python 3.7.7

## GDAL version and provenance

using `pip list` reveals GDAL 3.0.4

**Comment by jratike80** [comment]
GDAL project has a mailing list gdal-dev that is the right forum for asking questions about how to use GDAL.

By some experiments it seems that GDAL wants to save value 1573660800 into a field that is of type Integer64. Probably that is because even 1573660800 is small enough to be an integer some ten numbers wide numbers must be  presented as Integer64.

It is certainly possible to store 1573660800 into shapefile with GDAL as you can see below.

```ogrinfo inttest2.shp -dialect sqlite -sql "update inttest2 set test=1573660800" inttest2.shp
INFO: Open of `inttest2.shp'
      using driver `ESRI Shapefile' successful.
layer names ignored in combination with -sql.

ogrinfo inttest2.shp -al
INFO: Open of `inttest2.shp'
      using driver `ESRI Shapefile' successful.

Layer name: inttest2
Metadata:
  DBF_DATE_LAST_UPDATE=2020-05-05
Geometry: Point
Feature Count: 1
Extent: (340.000000, 556.000000) - (340.000000, 556.000000)
Layer SRS WKT:
(unknown)
test: Integer64 (10.0)
OGRFeature(inttest2):0
  test (Integer64) = 1573660800
  POINT (340 556)```

**Comment by rouault** [comment]
field_defn = ogr.FieldDefn("mdTmBrn", ogr.OFTReal)

will use by default width = 24, precision = 15 formatting, which means it cannot store more than 8 figures before decimal point (for a positive number)
Using OFTInteger or OFTInteger64 instead
Or use field_defn.SetWidth() and field_defn.SetPrecision() to adjust to the extent and precision of the numbers you'll store.

**Comment by anakaine** [comment]
Thanks. Looks like I'll need to dig in the library I'm using that creates the shapefile with ogr.
