### ISSUE TITLE
GPKG driver: update to upcoming 1.3

### ISSUE THREAD

**Issue by rouault** [OSGeo/gdal#2479]
Not ratified yet, but call for review at https://www.ogc.org/standards/requests/207
From a quick analysis of the change log at https://portal.ogc.org/files/92744:
- 6.1. Clarify use of views in user-defined table:  We could relax the ad-hoc requirement we had about having a column called OGC_FID. For a 1.3 DB, the first column of a registered view should act as a integer primary key.  Not sure validate_gpkg deals with views
- 6.2. Enforce alignment of SRS IDs between tables (2.1.5.1.2 and 2.2.6.1.2) : shouldn't affect the driver, but validate_gpkg could be enhanced
- 6.3. Allow Metadata Scopes to be extended : affects the driver (and potentialy validation script). Triggers to remove. See https://github.com/opengeospatial/geopackage/issues/520 for a question I have
- 6.4. Allow Schemas to be used with Attributes and Extensions (Annex F.9): would only affect validate_gpkg
- 6.5 Create new R152 to describe empty geometries. As far as I can see, GPkgGeometryFromOGR() is already compliant. Could potentially affect validate_gpkg
- update of user_version: see https://github.com/opengeospatial/geopackage/issues/519

**Comment by rouault** [comment]
GeoPackage 1.3 has now been approved:
- https://docs.ogc.org/is/12-128r17/12-128r17.html
- https://docs.ogc.org/is/12-128r17/18-066r1.html

**Comment by jratike80** [comment]
For those who consume geopackages the differences are very small and 1.3 gpkg database should work even with programs who know only 1.2. But I wonder if there are programs that check the version and quit.

I can't use ArcMap or ArcGIS at the moment but I can have a try later with gpkg lifted into 1.3 by `pragma user_version=10300;`.
