### ISSUE TITLE
HDF5 driver prints to stderr

### ISSUE THREAD

**Issue by sgillies** [OSGeo/gdal#2480]
It looks like some HDF5 specific error stack management needs to be done around this call https://github.com/OSGeo/gdal/commit/35e18b0537329030e19114390038054101b7f25c#diff-cb9b73e7e7e0d423d01b40cae2679299R298. According to https://github.com/mapbox/rasterio/issues/1847 the problem showed up after this commit (GDAL 2.4.2).

**Comment by rouault** [comment]
This has been fixed in 3.0 cycle per 1937d70990182aef316ac76f0c7c8fb3647259b2
