### ISSUE TITLE
GDAL 3: PROJ API: inability to clear the grid_list cache

### ISSUE THREAD

**Issue by and-marsh** [OSGeo/gdal#2484]
Hello,

I faced a problem using GDAL coordinate transformation API. The problem is related to the transformations that use grid files. If I understand correctly, during a first using of any grid this grid will be cached by PROJ in `static PJ_GRIDINFO *grid_list` global variable (`gridlist.cpp`). It's ok, as it's necessary for transformation performance.
Since this variable is global it will be alive all time that program runs. There are several ways to clean up it in runtime: `pj_deallocate_grids()` and `proj_cleanup()`. The problem is both of them is unavailable via GDAL API. 

I understand that i can easy include `proj.h` header and use those functions through it. But it's a real problem to use them on Android devices, because of lack of JNI bindings for this API.

I'd like to know are there plans to port this API to GDAL or if there any other way to clear grid  cache.
Maybe i can try to contribute a port of this API to GDAL along with SWIG-bindings if you would say it is acceptable way to solve this problem.

## GDAL version and provenance

GDAL 3.0.4, PROJ 6.3.0

**Comment by rouault** [comment]
Why would you want to clear the grid cache ? Anyway, this mechanism no longer exists in PROJ 7. Grids are owned by each PJ* objects

**Comment by and-marsh** [comment]
It's necessary if you use a lot of transformations with grids during single app run. There can be much memory occupied by unnecessary now grids, if you for example have used once transformation with `egm2008` geoid and don't use it more in this run app session.
It leads to a RAM lack especially on old devices that have not a lot of RAM and this memory can bee freed only by restarting app.

But since the problem no longer exists in PROJ 7 it is not relevant anymore. 

Anyway thanks for the quick reply! Sorry for disturbing!
