### ISSUE TITLE
build fails for 3.1.0 because of sphinx / breathe

### ISSUE THREAD

**Issue by mmomtchev** [OSGeo/gdal#2491]
## Expected behavior and actual behavior.

sphinx-build chokes on build/xml/gdal__alg_8h.xml
with UnboundLocalError: local variable 'declaration' referenced before assignment
the error comes from sphinxrenderer.py :

```Python
        if node.definition.startswith('typedef '):
            declaration = ' '.join([type_, name, node.get_argsstring()])
        elif node.definition.startswith('using '):
            # TODO: looks like Doxygen does not generate the proper XML
            #       for the template paramter list
            declaration = self.create_template_prefix(node)
            declaration += ' ' + name + " = " + type_
        return self.handle_declaration(node, declaration)
```
Obviously this piece of code does not expect node.definition to be something else than 'typedef' or 'using'.

In the XML I found:
```XML
      <memberdef kind="typedef" id="gdal__alg_8h_1a7df61123fec15deb3da3acabce19e647" prot="public" static="no">
        <type>int(*</type>
        <definition>int GDALTransformerFunc</definition>
        <argsstring>)(void *pTransformerArg, int bDstToSrc, int nPointCount, double *x, double *y, double *z, int *panSuccess)</argsstring>
        <name>GDALTransformerFunc</name>

```

which definitely doesn't look very good. There is maybe some problem with the syntax in alg/gdaltransformer.cpp but it is not very obvious? Maybe an incompatible breathe? Sphinx version? 

## Steps to reproduce the problem.

cd doc && make man

## Operating system

Ubuntu 19.10 64 bit and Debian 10 64 bit

breathe                       4.18.0        
sphinx-rtd-theme              0.4.3         
sphinxcontrib-applehelp       1.0.2         
sphinxcontrib-devhelp         1.0.2         
sphinxcontrib-htmlhelp        1.0.3         
sphinxcontrib-jsmath          1.0.1         
sphinxcontrib-qthelp          1.0.3         
sphinxcontrib-serializinghtml 1.1.4         

## GDAL version and provenance

3.1.0 check-out from git

**Comment by rouault** [comment]
That reminds me of a similar issue with PROJ. I believe the issue is a Doxygen bug instead. I use successfully Doxygen 1.8.11 and the Docker image used for the website if based on Ubuntu 18.04 with Doxygen 1.8.13

If you use the official tarball, the man pages are already pre-generated and you just need to use the install-man target

**Comment by mmomtchev** [comment]
I have
doxygen 1.8.13-10ubuntu3 on Ubuntu and
doxygen 1.8.13-10 on Debian
I will try with the official tarball

**Comment by mmomtchev** [comment]
This seems to work for me, but I have never used Sphinx before, so it is pure guesswork
(this is the way the other typedefs for function pointers are)
