### ISSUE TITLE
DIMAP driver fails to load georefencing information

### ISSUE THREAD

**Issue by gfkeith** [OSGeo/gdal#2493]
## Expected behavior and actual behavior.

Georeferencing expected to be loaded from DIMAP file, but `gdalinfo DIM...XML` has no coordinate system and pixel corner coordinates. At least the coordinate system is expected.

## Steps to reproduce the problem.

Some DIMAP files do not have the 'Geoposition.Geoposition_Insert' node, instead having 'Geoposition.Geoposition_Models' as follows:
```xml
    <Geoposition_Models>
      <Rational_Function_Model>
        <Component>
          <COMPONENT_TITLE>RPC Model</COMPONENT_TITLE>
          <COMPONENT_CONTENT>Geoposition Model</COMPONENT_CONTENT>
          <COMPONENT_TYPE>DIMAP</COMPONENT_TYPE>
          <COMPONENT_PATH href="RPC_SPOT6_P_201912362718249_SEN_4253891101.XML"/>
        </Component>
      </Rational_Function_Model>
    </Geoposition_Models>
```
Use `gdalinfo DIM...XML` on any such file (or any other method of view dataset information, e.g. ds.GetProjection() in python). The underlying GeoTIFFs must not have embedded georeferencing.

## Operating system

Windows 10 64 bit, WSL Ubuntu

## GDAL version and provenance

3.0.4 (https://www.lfd.uci.edu/~gohlke/pythonlibs/), 2.4.0 (nextgis/ppa)

## Comments

If a 'Geoposition.Geoposition_Insert' node is added to the DIMAP file, both geotransform and projection can be accessed. 

https://github.com/OSGeo/gdal/blob/master/gdal/frmts/dimap/dimapdataset.cpp#L1285 would probably explain why there is no geotransform information, and combined with https://github.com/OSGeo/gdal/blob/master/gdal/frmts/dimap/dimapdataset.cpp#L226 might explain no projection. The DIMAP file comes from a non-ortho SPOT scene, which is probably why it is different. It still contains the Dataset_Extent node, with LON, LAT, ROW, COL nodes for each corner, and an associated RPC model, so it should be possible to get the georeferencing info (if a little more complicated), however I understand that that might be beyond the scope of GDAL.

**Comment by rouault** [comment]
Having access to the dataset would be needed

**Comment by gfkeith** [comment]
Unfortunately I don't think I can share this particular dataset due to licensing. I've been trying to find a publicly available dataset and finally seem to have - https://www.intelligence-airbusds.com/en/9317-sample-imagery-detail?product=17340&keyword=&type=363.

**Comment by rouault** [comment]
Trying gdalinfo Pleiades_Primary_Product_Bundle/FCGC600031035/IMG_PHR1A_P_001/DIM_PHR1A_P_201202250025599_SEN_PRG_FC_5847-001.XML , I get
```
RPC Metadata:
  HEIGHT_OFF=60
  HEIGHT_SCALE=60
  LAT_OFF=-37.81850437219109
  LAT_SCALE=0.05601881303291023
  LINE_DEN_COEFF= 1 0.0001620558278999023 -0.0002903477573361241 -1.287957389667461e-06 -5.845049445390062e-06 -6.042669564773309e-09 1.345196525175688e-08 1.80802383748586e-05 -5.376321386755563e-05 2.727108113815714e-05 -1.519846297887851e-10 3.085365014117928e-08 9.238268301611578e-07 8.851621348003659e-09 4.018512081145706e-07 -7.998383945040524e-08 -4.260605700540489e-09 -8.796348563888441e-11 1.309846571729149e-08 -7.129742301277753e-11
  LINE_NUM_COEFF= -0.0004249801887025409 -0.0008063534045916749 -1.000809734099668 4.854764918828103e-05 0.0001616810717049461 -8.886054825983429e-09 -1.302652433467579e-06 0.001001499737588301 0.0001347676102631605 -1.884624351474659e-09 8.093096984505246e-09 -1.777825027177536e-07 -9.528490472293718e-06 -2.216572099506163e-08 -1.832054863536304e-05 -9.589800854856092e-05 -2.73034599620041e-05 2.16608213671011e-09 1.372777350901934e-08 1.325519092146825e-09
  LINE_OFF=12381.5
  LINE_SCALE=12381.5
  LONG_OFF=144.9558522564973
  LONG_SCALE=0.1152840617118471
  SAMP_DEN_COEFF= 1 4.54511169079185e-05 -0.0004364163500737836 -4.68154706305291e-05 -3.969508725394494e-07 1.102202839531934e-08 -1.213817867690509e-08 3.593357571351222e-06 6.726710942795597e-07 -2.83343527327547e-06 -4.725699251935035e-09 2.837731241794827e-08 6.216546109317793e-07 -8.045874686829871e-10 3.918316098930609e-08 2.100325804513623e-07 2.444906312714436e-09 1.249363189372619e-09 1.127871874285866e-09 2.502207777355469e-10
  SAMP_NUM_COEFF= 0.0002001114282439561 1.001016004246746 -0.0003540247633882741 0.0001146420178672275 0.0004360421422798639 4.675787009224147e-05 -1.326178394645707e-05 -0.0002455727817749047 9.927598278284553e-05 4.260957818661205e-09 9.072751694038962e-09 -8.399932021032866e-06 -4.300477492599503e-06 -2.825191266320701e-06 3.263295916416256e-05 0.0002343306198087664 5.122625092207982e-12 -1.340074571502415e-08 -3.914886192232008e-08 -3.167496661294686e-10
  SAMP_OFF=19999.5
  SAMP_SCALE=19999.5
```
The fact that there's no geotransform reported is expected since it is given by the ULXMAP, ULYMAP, XDIM and YDIM child elements of Geoposition.Geoposition_Insert. If they are not present, we cannot report a geotransform. Dataset_Extent only gives the coordinates of the corners, but infering a geotransform from that would be only an approximation, not something exact. I believe the current behaviour is OK (at least on that dataset)

**Comment by gfkeith** [comment]
That seems fair enough, it is a useful approximation but being an approximation it is probably better off left to the user.

Thanks for your time.
