### ISSUE TITLE
Conversion from Geotiff to ArcInfoAscii using gdal_translate results in flipped raster.

### ISSUE THREAD

**Issue by vernimmen** [OSGeo/gdal#2494]
## Expected behavior and actual behavior.

Conversion from Geotiff to ArcInfoAscii using gdal_translate results in flipped raster. Likely cause is the positive pixel spacing in y-direction which may not be supported by ascii?

from gdalinfo:

Pixel Size = (0.100000000000000,0.100000000000000)

See attached geotiff

## Steps to reproduce the problem.

gdal_translate -of AAIGrid 3B-DAY-GIS.MS.MRG.3IMERG.20000701.V06B_SEAsia.tif 3B-DAY-GIS.MS.MRG.3IMERG.20000701.V06B_SEAsia.asc

## Operating system

Windows 10, 64 bit

## GDAL version and provenance

GDAL 3.0.4, released 2020/01/28 installed through Anaconda (Anaconda3-2019.10-Windows-x86_64.exe), build py37hd44be9e_6

[3B-DAY-GIS.MS.MRG.3IMERG.20000701.V06B_SEAsia.zip](https://github.com/OSGeo/gdal/files/4597611/3B-DAY-GIS.MS.MRG.3IMERG.20000701.V06B_SEAsia.zip)

**Comment by vernimmen** [comment]
temporary solution is first using gdalwarp

gdalwarp -tr 0.1 0.1 3B-DAY-GIS.MS.MRG.3IMERG.20000701.V06B_SEAsia.tif 3B-DAY-GIS.MS.MRG.3IMERG.20000701.V06B_SEAsia_trans.tif

which results in

Pixel Size = (0.100000000000000,-0.100000000000000)

after which the following results in proper asc file

gdal_translate -of AAIGrid 3B-DAY-GIS.MS.MRG.3IMERG.20000701.V06B_SEAsia_trans.tif 3B-DAY-GIS.MS.MRG.3IMERG.20000701.V06B_SEAsia_trans.asc

**Comment by rouault** [comment]
The original GeoTIFF also use a positive-y resolution (that is the top of the TIFF file when seen as an image is the southern-most row), and the translation to AAIGrid also preserves this, as the format supports it. So for me, things work as designed . Using gdalwarp is indeed the way to "fix" the georeferencing to use the more conventional top row = northern-most row
