### ISSUE TITLE
GDAL 3.1.0, PROJ 7.0.1, VS 2017, Windows 10 SDK, missing ucrt.lib

### ISSUE THREAD

**Issue by chacha21** [OSGeo/gdal#2499]
Hello,
Not sure if it is a bug or a misuse from my part, but here is the issue:

First, something that works :
-I want to compile GDAL (currently 3.1.0) x64 with VS2019 on Windows 7 64b
-To do that, I first compile PROJ (currently 7.0.1) x64 as a static lib with VS2019
It works, as it used to work with GDAL 3.0 and PROJ 6.*

Now, something that does not work any more :
I want to do the same build with VS2017 instead of VS2019. This is just the initial choice in the CMake of both PROJ and GDAL
It used to work, with GDAL 3.0 and PROJ 6.*
Now GDAL fails at link stage, complaining about missing ucrt.lib

I am pretty sure that the problem comes from the fact that my very first action with CMake, before selecting VS2017, is to set CMAKE_SYSTEM_VERSION to the string "10.0" to force the use of the latest Windows 10 SDK (even if I am under Windows 7).
I have never had any problem with that (either for previous GDAL/PROJ, or other projects like OpenCV)
But with GDAL 3.1.0 and PROJ 7.0.1, this new error (ucrt.lib not found) occurs.
Since GDAL heavily use nmake instead of vcxproj usual settings, I do not really know what is the good fix.

**Comment by mloskot** [comment]
May help to launch VS 2017 installer and pick UCRT SDK

**Comment by chacha21** [comment]
I have just checked, it's already checked in the Visual Studio Installer > Visual Studio 2017 Community > Modify > Individual components

**Comment by rouault** [comment]
Looks like a build problem specific to some configuration, not a general one. Closing
