### ISSUE TITLE
GDALDataset::RasterIO wrong read half pixel shifted buffer

### ISSUE THREAD

**Issue by Unril** [OSGeo/gdal#2507]
**Given**

GeoTIFF with ```INTERLEAVE=PIXEL```. Try to read buffer shifted by 0.5 pixels:

```c++
int bufferSize = 100;
GDALRasterIOExtraArg args;
INIT_RASTERIO_EXTRA_ARG(args);
args.eResampleAlg = GRIORA_Bilinear;
args.bFloatingPointWindowValidity = true;
args.dfXOff = 0.5;
args.dfYOff = 0.5;
args.dfXSize = bufferSize;
args.dfYSize = bufferSize;
dataset->RasterIO(GF_Read, 0, 0, bufferSize, bufferSize, buffer, bufferSize, bufferSize, GDT_Byte, 3, nullptr, 0, 0, 0, &args);
```

**Results**

Expected
![img_expected_bi_0 5](https://user-images.githubusercontent.com/3948696/81483442-e674c600-9246-11ea-8599-52f5d93d58ce.png)

Got
![img_got_bi_0 5](https://user-images.githubusercontent.com/3948696/81483443-e7a5f300-9246-11ea-862f-0b6a09233e69.png)

Nearest neighbour with origin at (0,0)
![img_nn_0 0](https://user-images.githubusercontent.com/3948696/81483444-e7a5f300-9246-11ea-8bac-60da205ddf8a.png)

Nearest neighbour with origin at (0.5,0.5)
![img_nn_0 5](https://user-images.githubusercontent.com/3948696/81483445-e83e8980-9246-11ea-8998-cb0d04337715.png)

Nearest neighbour with origin at (1,1)
![img_nn_1 0](https://user-images.githubusercontent.com/3948696/81483446-e83e8980-9246-11ea-8a0a-c10412eb90a5.png)

**Possible error**

* Enter GDALDataset::RasterIO https://github.com/OSGeo/gdal/blob/master/gdal/gcore/gdaldataset.cpp#L2413
* Call GDALDataset::IRasterIO https://github.com/OSGeo/gdal/blob/master/gdal/gcore/gdaldataset.cpp#L2539
* Call GDALDataset::BlockBasedRasterIO https://github.com/OSGeo/gdal/blob/master/gdal/gcore/gdaldataset.cpp#L2041
* All bands are have the same type and block size and buffer size is equal to region size https://github.com/OSGeo/gdal/blob/master/gdal/gcore/rasterio.cpp#L3865
* Information about resampling is lost https://github.com/OSGeo/gdal/blob/master/gdal/gcore/rasterio.cpp#L3903

**Comment by rouault** [comment]
You seem close to a fix. Can you submit a pull request ?

**Comment by Unril** [comment]
> You seem close to a fix. Can you submit a pull request ?

I don't really know where is the best place to apply a fix.
The bug seems to be here https://github.com/OSGeo/gdal/blob/master/gdal/gcore/rasterio.cpp#L3865 and it can be fixed by adding ResampleAlg check:
```c++
if( nXSize == nBufXSize && nYSize == nBufYSize && psExtraArg->eResampleAlg == GRIORA_NearestNeighbour)
```

**Comment by rouault** [comment]
or perhaps propagate eResampleAlg, dfXOff, dfYOff, dfXSize and dfYSize to the sDummyExtraArg, which should be renamed to something like sBandExtraArg

**Comment by Unril** [comment]
> or perhaps propagate eResampleAlg, dfXOff, dfYOff, dfXSize and dfYSize to the sDummyExtraArg, which should be renamed to something like sBandExtraArg

It seems that in this case chunk iteration logic will be changed. And performance will be worse, GDALRasterBand::IRasterIO will create temporary dataset for each block for each band.

**Comment by rouault** [comment]
or then your initial proposal is probably OK

**Comment by Unril** [comment]
> or then your initial proposal is probably OK

Maybe it is better to change condition here https://github.com/OSGeo/gdal/blob/master/gdal/gcore/gdaldataset.cpp#L2036
```c++
    if (nXSize == nBufXSize && nYSize == nBufYSize && nBandCount > 1 &&
        psExtraArg->eResampleAlg == GRIORA_NearestNeighbour &&
        (pszInterleave = GetMetadataItem("INTERLEAVE", "IMAGE_STRUCTURE")) !=
            nullptr &&
        EQUAL(pszInterleave, "PIXEL"))
```
It this case resampling will be done using GDALDataset::RasterIOResampled which is probably faster.

**Comment by rouault** [comment]
I let you try & investigate the different options you see.

**Comment by Unril** [comment]
> I let you try & investigate the different options you see.

https://github.com/OSGeo/gdal/pull/2510 Disabling BlockBasedRasterIO optimization for this particular case should fix this problem.
