### ISSUE TITLE
Indicate defaults for EVERY parameter in documentation

### ISSUE THREAD

**Issue by ianengelbrecht** [OSGeo/gdal#2520]
For example, in gdal2tiles.py, is there a default for --s_srs? Does it use the input layer SRS, assume mercator? This would be very helpful for trouble shooting.

**Comment by rouault** [comment]
This is far way too broad to be actionable. Open a ticket (and better provide a pull request with enhancements) for specific items where information is missing

**Comment by ianengelbrecht** [comment]
You guys are building valuable software on this project, but the documentation is lacking, particularly for users with lower technical ability. Having more comprehensive documentation would facilitate wider adoption by a broader community of users by lowering the barriers to successful use. Good documentation is what's made tools like R a success. What I would rather suggest is that the GDAL team set standards for documentation, and that part of those standards be that every parameter should indicate default values if there are defaults, and include an example value so users  see the formats of parameter values too.

**Comment by rcoup** [comment]
@ianengelbrecht no-one is paid to work on generic "make GDAL better" improvements — that is all volunteer time, and it's not for anyone to dictate what people must work on in their own time.

Of course everyone wants great documentation, but wishing for it doesn't make it magically happen. I'm sure the project could find technical writers if there was funding available.

A PR to add documentation with default values for even a single function that's bothering you would be a great contribution you could make. Search for the function name and find out where its existing docs come from. There's a guide available to the [documentation formatting](https://gdal.org/contributing/rst_style.html).

**Comment by ianengelbrecht** [comment]
Okay, thank you, I've added a new issue #2549 with more specific suggestions.
