### ISSUE TITLE
Some indexes have less language switcher links than others

### ISSUE THREAD

**Issue by jidanni** [OSGeo/gdal#2523]
file:///usr/share/doc/libgdal-doc/gdal/index_ru.html
only has three languages at

> Select language: [English][Russian][Portuguese]

whereas file:///usr/share/doc/libgdal-doc/gdal/index.html
has more.

libgdal-doc_3.0.4+dfsg-1

**Comment by rouault** [comment]
We no longer have those unmaintained translations since GDAL 3.1
