### ISSUE TITLE
Python GDAL cannot access L2A-specific bands of a Sentinel-2 image

### ISSUE THREAD

**Issue by JanChytry** [OSGeo/gdal#2530]
### Expected behavior and actual behavior
I have a Sentinel-2 L2A image and was able to access it with:
```
In[1]:
import os 
import gdal

image = gdal.Open(os.path.join(s2l2a_image.SAFE, "MTD_MSIL2A.xml")
image.GetSubdatasets()

Out[1]:
[('SENTINEL2_L2A:s2l2a_image.SAFE/S2A_MSIL2A_20190620T100031_N0212_R122_T33UXQ_20190620T131720.SAFE/MTD_MSIL2A.xml:10m:EPSG_32633',
  'Bands B2, B3, B4, B8 with 10m resolution, UTM 33N'),
 ('SENTINEL2_L2A:s2l2a_image.SAFE/S2A_MSIL2A_20190620T100031_N0212_R122_T33UXQ_20190620T131720.SAFE/MTD_MSIL2A.xml:20m:EPSG_32633',
  'Bands B5, B6, B7, B8A, B11, B12 with 20m resolution, UTM 33N'),
 ('SENTINEL2_L2A:s2l2a_image.SAFE/S2A_MSIL2A_20190620T100031_N0212_R122_T33UXQ_20190620T131720.SAFE/MTD_MSIL2A.xml:60m:EPSG_32633',
  'Bands B1, B9 with 60m resolution, UTM 33N'),
 ('SENTINEL2_L2A:s2l2a_image.SAFE/S2A_MSIL2A_20190620T100031_N0212_R122_T33UXQ_20190620T131720.SAFE/MTD_MSIL2A.xml:TCI:EPSG_32633',
  'True color image, UTM 33N')]
```
This is great, however, I thought I could look at all bands of `subdataset[1]`. GDAL documentation on Sentinel-2 driver ([here](https://gdal.org/drivers/raster/sentinel2.html)) talks about L2A-specific layers, such as Scene Classification Layer (SCL) and others. I tried a lot, inspected subdatasets  and their RasterBands and such, but found no way to access them.

### Steps to reproduce the problem
Possible to reproduce with any undamaged/unaltered Sentinel-2 SAFE file.

### Operating system
```
CentOS 7
Python version 3.6
```
### GDAL version and provenance
GDAL version:
```
[user@server~]$ gdalinfo --version
GDAL 2.4.3, released 2019/10/28
```

Python API binding:
```
In[2]: 
import gdal
gdal.VersionInfo()

Out[2]:
2040300
```

**Comment by rouault** [comment]
This has normally been fixed in GDAL 3.1 per b846e11320355c1e9ba146b7f672f4ea597c704c / #2404
