### ISSUE TITLE
Refer to PROJ not PROJ.4 throughout the docs

### ISSUE THREAD

**Issue by jidanni** [OSGeo/gdal#2547]
https://en.wikipedia.org/wiki/PROJ says
> PROJ (formerly PROJ.4)...
> With the release of version 5.0 in February 2018, the software was renamed to PROJ, removing version four (".4") from the name. With the acquisition of the proj.org domain name in June 2019, the project was also renamed as PROJ.

The GDAL docs are full of PROJ.4/proj.4 mentions. Please sweep through them removing the dot four.

Wait, there are even switches: -proj4 (gdalinfo...) and -o proj4
(gdalsrsinfo), so when searching, search for /\bproj\.?4/i, and think
deeply about if they are worth changing or better yet adding an additional -proj and -o proj.

Parts of e.g., gdalwarp doc already just say PROJ. Good.

**Comment by rouault** [comment]
I've fixed in 183c8c7 instances where this was justified. But "PROJ.4 definition/string/format" is still a legitimate way of expressing this format, and underline it is now a legacy
