### ISSUE TITLE
Suggested improvements for gdal2tiles and common options documentation

### ISSUE THREAD

**Issue by ianengelbrecht** [OSGeo/gdal#2549]
Following on from suggestion in #2520, the documentation for gdal2tiles could be improved as follows:

--xyz: users unfamiliar with TMS vs XYZ might not understand the nuances of the two. I suggest adding the a [link to this URL](https://alastaira.wordpress.com/2011/07/06/converting-tms-tile-coordinates-to-googlebingosm-tile-coordinates/) or something similar so that users understand the differences.

-a <NODATA>, --srcnodata=<NODATA>: Description is 'NODATA transparency value to assign to the input data', which is unclear. I see several posts online where people aren't sure what to add here. Is this the nodata value in the dataset? How do we set the output colour for nodata values in the result? Some people get black areas around the maps, I got purple areas in some of my maps. An example would be helpful here. Is there a default?

--processes=<NB_PROCESSES>: It's not clear what NB_PROCESSES refers to. Is there a default?

--tilesize=<TILESIZE>: Description says 'Pixel size of the tiles'. Does this mean the pixel dimensions, i.e. n_pixels x n_pixels. If this is the case it would be better if the parameter value was PIXELS and not TILESIZE. Please also indicate the default. 

Then in the common options page, perhaps update the title to something like 'Use and common options', and add a section to the page called 'using options' or something like that, with a description of the formats used for options in the documentation. For example, I couldn't understand what  '--format <format>' meant. Sometimes the <value> section is in caps and other times not. Does this mean there are sometimes default values and other times not? I couldn't find something that explained what these  different things meant. So some basic explanation here of how to interpret the documentation would help. Eg. '<value> indicates the value passed to the option. Where values, like file paths, have spaces, wrap them in quotation marks', and so on. 

I hope these suggestions are more helpful.

**Comment by rouault** [comment]
I've improved the doc of gdal2tiles. But I didn't follow what you wanted exactly in the common options page. I suggest you issue pull request with the improvements you have in mind
