### ISSUE TITLE
PDF tables distorted due to long file names

### ISSUE THREAD

**Issue by jidanni** [OSGeo/gdal#2554]
The verylongfilenames in
https://github.com/OSGeo/gdal/blob/master/gdal/doc/source/drivers/vector/eeda.rst
cause massive damage in https://gdal.org/gdal.pdf .

gdal.pdf#subsection.5.20.6 should use the same line breaking method as
 5.32.12.1  GMLAS - Mapping examples

But then some other problem with three tables in 5.32.12.2  GMLAS - Metadata layers

**Comment by rouault** [comment]
Not sure how much control when have on this. This is generated by the latexpdf output
