### ISSUE TITLE
Too much blank space in PDF

### ISSUE THREAD

**Issue by jidanni** [OSGeo/gdal#2555]
Downloading https://gdal.org/gdal.pdf , then we see:
file:gdal.pdf#section.5.91.3 too much
blank space. Also
file:gdal.pdf#section.5.91.4 too.

**Comment by rouault** [comment]
What is section 5.91.3 & 5.91.4 ?

**Comment by jidanni** [comment]
5.91.3  Virtual File Format
![26784-0](https://user-images.githubusercontent.com/1230959/82129723-4f37e180-97f7-11ea-93b1-ac7adf1dfddb.jpg)
