### ISSUE TITLE
Implement --print-uris --simulate --just-print --dry-run --no-act

### ISSUE THREAD

**Issue by jidanni** [OSGeo/gdal#2569]
In https://github.com/OSGeo/gdal/issues/2052#issuecomment-628650934 we observe that with $ CPL_CURL_VERBOSE=YES ... --debug on
we are able to see what HTTP(S) fetching is going on.

That's great, but it still requires a network connection or at least a
running HTTP server on localhost. Or else the best we get is some info
in an error message.

Do consider instead adding concepts like:
```
WWW::Mechanize::Cookbook(3pm)
   See what will be sent without actually sending anything
           $mech->add_handler("request_send", sub { shift->dump; exit; });
           $mech->get("http://www.example.com");
```

for showing all the headers that would have been sent. And,

```
apt-get --print-uris --simulate --just-print --dry-run --no-act
```

```
rsync --dry-run #but alas no --just-print, --print-uris
```

for showing all the URIs that would have been fetched... all without making even one HTTP request.

**Comment by rouault** [comment]
Why would that be needed ?

**Comment by jidanni** [comment]
Why it is good to have a way to see what HTTP(s) one is about to send, before actually sending them? Well,


- In the PDF manual, we observe
> 6.8.2 List of configuration options and where they apply
> Note: **This list is known to be incomplete.** It depends on proper annotation of configuration options where they are mentioned elsewhere in the documentation...

  And some, e.g., CPL_CURL_VERBOSE aren't even documented at all.
Thus, without downloading and thoroughly examining the entire source code, the user indeed has no idea of what HTTP(s) requests he is actually about to send.

- Even worse is he is given the ability to adjust Referer: etc. headers, obviously to be able to get into highly restricted sites, but has no ability to double check those headers to see that he has got them right, before sending the wrong ones, tripping off alarm bells at those sites.

- No need for blind live experimentation not knowing exactly what HTTP(S) requests or how many of them you are sending to other people's servers, while at the same time indeed using GDAL's very own User-Agent string... one can only think of why e.g.,
`   User-Agent: lwp-request/* libwww-perl/*`
is blacklisted widely these days.
Sure, one might advise "Be sure to change the User-Agent to something other than GDAL/OGR's while testing. Looping out of control might get our User-Agent banned from e.g., maps.google.com for everybody!". However it would be much more proper to simply let users be able to check what requests they are about to make before hammering the network. Indeed, one might not be able to stop a test gone awry: e.g., a truck hits a utility pole and one can no longer connect to the virtual private server where the loop is being generated.
- No more need to learn and configure an entire man-in-the-middle HTTPS proxy and DNS overrides via /etc/hosts, netcat,  just to simply figure our what **we ourselves**, and not anybody else, are about to send.

**Comment by jidanni** [comment]
https://github.com/curl/curl/issues/5426 we observe curl currently offers no way to stop itself from sending things, so GDAL would need to add this functionality itself.

**Comment by jidanni** [comment]
Indeed, maybe it would be best to simply wait until that Perl library feature is implemented ...

**Comment by jratike80** [comment]
I guess that it would be very difficult to make a perfect dryrun option because in many cases the first response has an effect on what the next request will be.

**Comment by jidanni** [comment]
> I guess that it would be very difficult to make a perfect dryrun option because in many cases the first response has an effect on what the next request will be.

Example?

**Comment by rouault** [comment]
things like WFS involve several server <--> client exchanges and the client adapt its request regarding response of the server to previous one.
I think I'll just close this ticket as won't fix. I don't think it is reasonably doable and a rather specialized use. People with that need can use a fake server, or log requests at other levels

**Comment by jratike80** [comment]
Here is an example (beta disappears sometimes in summer 2020)
`ogrinfo oapif:"https://beta-paikkatieto.maanmittauslaitos.fi/maastotiedot/wfs3/v1/" --config CPL_CURL_VERBOSE YES --debug on`
