### ISSUE TITLE
Document all CPL... variables

### ISSUE THREAD

**Issue by jidanni** [OSGeo/gdal#2571]
In https://github.com/OSGeo/gdal/issues/2052#issuecomment-628650934 we see

> $ CPL_CURL_VERBOSE=YES GDAL_HTTP_HEADER_FILE...

The user can find (command line) documentation about
GDAL_... variables, but not CPL_... variables, in the various doc files.

**Comment by rouault** [comment]
This is just too generic to be actionable.
