### ISSUE TITLE
PDF-only documents

### ISSUE THREAD

**Issue by jidanni** [OSGeo/gdal#2574]
(Rendered) https://github.com/OSGeo/gdal/blob/master/gdal/doc/source/user/configoptions.rst is included in
https://gdal.org/gdal.pdf but not in any of
python3-gdal gdal-bin gdal-data libgdal27 libgdal-doc
packages that I see here on Debian.

**Comment by rouault** [comment]
This is an issue to file to Debian packaging.

**Comment by jidanni** [comment]
OK. Filed https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=960964 .

**Comment by jidanni** [comment]
They said libgdal-doc is gone in 3.1.0.

**Comment by jidanni** [comment]
@rouault
 `gdal (3.1.0~rc1+dfsg-1~exp1) experimental; urgency=medium`
  * Drop libgdal-java package.
    (closes: #947960)
  * Exclude doc directory from repacked upstream tarball.
  * Update copyright file.
  * **Drop libgdal-doc package, license & copyright review is unpleasant.**
...
