### ISSUE TITLE
MRF raster driver: should be enabled only if libpng, libjpeg and zlib available

### ISSUE THREAD

**Issue by SpaceIm** [OSGeo/gdal#2581]
## Expected behavior and actual behavior.

GDAL fails to compile because some MRF source files don't find either `libpng`, `libjpeg` or `zlib` headers if disabled.
I guess that MRF driver shouldn't be built by default, but only if these three dependencies are not disabled by user.

## Steps to reproduce the problem.

Build GDAL 3.1.0 from source with either `--with-png=no`, `--with-jpeg=no` or `--with-zlib=no`.
For example, `PNG_band.cpp` fails to compile if `--with-png=no`.

If `--with-png=yes` and others are disabled, it might work because `libjpeg` and `zlib` are optional dependencies of `libtiff` (and also `zlib` is a dependency of `libcurl` which is now an optional dependency of `proj` >= 7).

## Current Workaround

Pass `--disable-driver-mrf` if at least one of `--with-png`, `--with-jpeg`, `--with-zlib` is disabled.

## Operating system

Ubuntu 18.04 64 bit

## GDAL version and provenance

3.1.0 source code from github

**Comment by rouault** [comment]
CC @lucianpls

**Comment by rouault** [comment]
Closing as probably no longer valid with CMake builds
