### ISSUE TITLE
Failure to exit safely when GDALGetResampleFunction returns NULL

### ISSUE THREAD

**Issue by sgillies** [OSGeo/gdal#2587]
In https://github.com/mapbox/rasterio/issues/1930 a user reports a segmentation fault when Rasterio uses "max" to resample an overview. I've been able to reproduce the crash.

It looks like the problem might be here
https://github.com/OSGeo/gdal/blob/ff5f9da32d24e93eb2735ebf8dcee8632a711716/gdal/gcore/rasterio.cpp#L1041 where the NULL pointer check is only done for a debug build?

**Comment by rouault** [comment]
I believe this is a rasterio issue. The GDALRIOResampleAlg doesn't incorporate (yet) the max constant. You must be putting a GDALResampleAlg (using for warping) into the eResampleAlg field of GDALRasterIOExtraArg at https://github.com/mapbox/rasterio/blob/5bb3e60448dac4d73722a1dcfb268de791735786/rasterio/shim_rasterioex.pxi#L64 . This leads to undefined behaviour. Before doing this cast the input int value should be validated

**Comment by rouault** [comment]
Amusingly, GDAL's own bindings were affected by the same issue : https://github.com/OSGeo/gdal/pull/2591

**Comment by sgillies** [comment]
Thanks @rouault !
