### ISSUE TITLE
gdal_viewshed incorrect output

### ISSUE THREAD

**Issue by giacomov** [OSGeo/gdal#2599]
@hobu 

## Expected behavior and actual behavior.

`gdal_viewshed` should compute a viewshed similar to other existing tools (r.viewshed from GRASS and/or QGIS Visibility Analysis plugin).`gdal_viewshed` completes in 1/10th of the time (which would be awesome), but the output looks incorrect.

I provide here an example using a DEM of the Coit Tower area in San Francisco, CA. The viewshed is computed from a point at the South border of the top of the tower. The tower sits on top of a hill and dominates the city, so the visibility should be pretty much everything except the shadow of tall buildings (and what's obscured by the tower itself). This is exactly what I see in the output of `r.viewshed` or the QGIS plugin, but the output from `gdal_viewshed` is very different.

### DEM
(this is a hillshade applied to the DEM, the cross is the observer location)
![image](https://user-images.githubusercontent.com/5917371/82717192-157c3600-9c50-11ea-82a5-06245d2297f2.png)

### Output of `gdal_viewshed`
![image](https://user-images.githubusercontent.com/5917371/82717019-4a3bbd80-9c4f-11ea-8253-3927f36dd720.png)

### Expected output
![image](https://user-images.githubusercontent.com/5917371/82716975-1f516980-9c4f-11ea-902d-6d588a220a53.png)

## Steps to reproduce the problem.

```
gdal_viewshed -ox -13626155 -oy 4551540 -md 5000 coit_dsm_mosaic.tiff coit_viewshed_2.tif
```

## Operating system

Ubuntu 18.04 64 bit

## GDAL version and provenance

GDAL 3.1.0, released 2020/05/03 (from the `conda-forge` channel of conda)

**Comment by rouault** [comment]
Where is the input dataset ?

**Comment by giacomov** [comment]
I uploaded a smaller version here:

https://drive.google.com/drive/folders/1UKEub_39TXirxEui95udFNaRXfh_rgMz?usp=sharing

coit_dsm_mosaic: input DSM
coit_viewshed_2: output of `gdal_viewshed -ox -13626155 -oy 4551540 -md 5000 coit_dsm_mosaic.tiff coit_viewshed_2.tif`
coit_viewshed_grass.tif : output of `r.viewshed` from GRASS

**Comment by rouault** [comment]
CC @szekerest

**Comment by rouault** [comment]
In https://github.com/OSGeo/gdal/pull/2609 I've a fix that improves the accuracy of the result. I can then get a result that looks similar to the GRASS one (in the above Drive directory) by specifying -oz 2 . As the view point is in a area where elevations change very quickly from one pixel to the next one (by 10 or 20 metres), the result is super sensitive on how distance or elevation computations are done.

**Comment by giacomov** [comment]
@rouault thank you very much for the quick fix!

Reading the code, it looks like you changed how to compute the position of the observer in pixel coordinates. If I understand correctly, the problem was that the observer was assigned to the wrong pixel in some cases, and since the particular DEM I sent is changing drastically from one pixel to the next, this would cause the big differences. Am I interpreting that right?

I am going to build gdal from master and verify the fix in a few cases. Thanks!

**Comment by rouault** [comment]
> Am I interpreting that right?

yes

**Comment by szekerest** [comment]
Thanks for the fix @rouault

**Comment by giacomov** [comment]
I verified the fix by using the docker nightly builds. It seems to have fixed the problem indeed.

Thank you for the very fast response! Amazing work
