### ISSUE TITLE
OSM import always drops area tag

### ISSUE THREAD

**Issue by dg0yt** [OSGeo/gdal#2603]
## Expected behavior and actual behavior.

The `osmconf.ini` allows to configure which tags are to be imported and which are to be ignored. The default file explicitly list `area` as ignored:
https://github.com/OSGeo/gdal/blob/1c7fef4227e294ffd159e48d2dcb51ae0f6552f1/gdal/data/osmconf.ini#L118

When moving `area` from `ignore` to `attributes`, one would expect that the tag is properly imported. However, this is not the case: This tag is always removed. I assume this is happening here (also for other tags):
https://github.com/OSGeo/gdal/blob/1c7fef4227e294ffd159e48d2dcb51ae0f6552f1/gdal/ogr/ogrsf_frmts/osm/ogrosmdatasource.cpp#L2079-L2085

In the end, it is no longer possible to restore the flag, or to tell whether an object with "highway=pedestrian" is a circular footpath or a square.

## Steps to reproduce the problem.

Run `ogrinfo --config OSM_CONFIG_FILE mapper-osmconf.ini -ro area_yes.osm multipolygons` on [files from area_yes.zip](https://github.com/OSGeo/gdal/files/4671529/area_yes.zip):
`area=yes` is missing, but `highway` is created as configured in mapper-osmconf.ini.

## Operating system

Any.

## GDAL version and provenance

Any.

**Comment by dg0yt** [comment]
I verified that removing the following lines solves the issue for `area`:
https://github.com/OSGeo/gdal/blob/1c7fef4227e294ffd159e48d2dcb51ae0f6552f1/gdal/ogr/ogrsf_frmts/osm/ogrosmdatasource.cpp#L2084-L2085

I can create a PR, but what to do with the other tags handled in this function and listed in `osmconf.ini`:
https://github.com/OSGeo/gdal/blob/1c7fef4227e294ffd159e48d2dcb51ae0f6552f1/gdal/data/osmconf.ini:
created_by, converted_by, note, fixme, FIXME

In addition, there is also `todo` which might need to be removed from `ogrosmdatasource.cpp` and listed in `osmconf.ini` instead.

**Comment by rouault** [comment]
> I can create a PR, but what to do with the other tags handled in this function

you could try to remove them as well, and move todo to osmconf.ini. But I'd like you to try import of large enough .pbf files, like geofabrik export of France, to check that it still works (checking timing and output, for example of a ogr2ogr -f GPKG). Defered filtering on those attributes (particularly source that can have large values) could potentially break some assumptions as the driver is (probably too) optimized.

**Comment by dg0yt** [comment]
> But I'd like you to try import of large enough .pbf files
Oh, I need to see if I find a system to do that import, and compare performance.
Or we immediately start to look for a way to trim that hard coded filter to match configuration.

**Comment by rouault** [comment]
Note: https://github.com/OSGeo/gdal/pull/2604 (other change in OSM driver) has just been merged into master

**Comment by dg0yt** [comment]
For the record, it is possible to workaround the issue to some extent, by using a calculated field in `osmconf.ini`:

~~~
...
[multipolygons]
...
computed_attributes=is_area
is_area_type=String
is_area_sql="SELECT (CASE WHEN [osm_way_id] IS NOT NULL THEN 'yes' ELSE NULL END)"
~~~

This may help on systems which do not receive a new version of GDAL, e.g. using the official packages from Linux distributions.
