### ISSUE TITLE
compile and make gdal 3.1 fails because of missing PROJ 6 symbols

### ISSUE THREAD

**Issue by GeraldCNelson** [OSGeo/gdal#2608]
## Expected behavior and actual behavior.

I am attempting to compile gdal 3.1 on a mac book pro with Catalina 10.15.4 installed, Xcode version is 11.5, and command line tools are installed and up today. When I attempt to compile it fails with this configure `error configure: error: PROJ 6 symbols not found`.  Note that proj Rel. 7.0.1, May 1st, 2020 is installed. The reason I need to do this is that the brew version of gdal is gdal-2.4.4_6. 

The expected behavior is that configure completes successfully and then I'll run make and make install.

## Steps to reproduce the problem.

Download gdal-3.1.0.tar.gz to Downloads. Unpack it. In a terminal window, cd to the gdal-3.1.0 directory and run` ./configure`. 

## Operating system

Catalina 10.15.4

## GDAL version and provenance

gdal-3.1.0.tar.gz downloaded from https://gdal.org/download.html#current-releases

**Comment by rouault** [comment]
> Note that proj Rel. 7.0.1, May 1st, 2020 is installed.

where ? In a system directory or somewhere else ? Did you point to it with --with-proj ?

**Comment by GeraldCNelson** [comment]
I hadn’t tried using which proj but have now. Some information
Which proj returns /usr/local/bin/proj

This is a simlink to ../Cellar/proj/7.0.1/bin/proj

When I run ./configure --with-proj=/usr/local/bin/ or./configure --with-proj=/usr/local/bin/ proj
from the gdal-3.1.0 directory, I still get the same error message

Should I point –with-proj to the Cellar proj file?

Gerald C. Nelson
Professor Emeritus, UIUC
+1 217-390-7888 (cell)
+1 970-639-2079 (land line)
Skype: jerrynelson
http://bit.ly/1arho7d

**Comment by rouault** [comment]
try `./configure --with-proj=/usr/local`

**Comment by GeraldCNelson** [comment]
Same outcome. Here’s a bit more of the output


checking for PROJ >= 6 library... checking for proj_create_from_wkt in -lproj... no

checking for proj_create_from_wkt in -lproj... no

checking for proj_create_from_wkt in -lproj... no

checking for internal_proj_create_from_wkt in -lproj... no

checking for internal_proj_create_from_wkt in -lproj... no

checking for internal_proj_create_from_wkt in -linternalproj... no

checking for internal_proj_create_from_wkt in -linternalproj... (cached) no

configure: error: PROJ 6 symbols not found


Gerald C. Nelson
Professor Emeritus, UIUC
+1 217-390-7888 (cell)
+1 970-639-2079 (land line)
Skype: jerrynelson
http://bit.ly/1arho7d

**Comment by rouault** [comment]
or perhaps try `./configure --with-proj=/usr/local/Cellar/proj/7.0.1`  (if that directory exists well, guessing from your above indications)

**Comment by GeraldCNelson** [comment]
It does exist. And I get the same error message with your configure below.

Would it help to past the complete set of messages from the configure output?


Gerald C. Nelson
Professor Emeritus, UIUC
+1 217-390-7888 (cell)
+1 970-639-2079 (land line)
Skype: jerrynelson
http://bit.ly/1arho7d

**Comment by rouault** [comment]
can you show the output of `find /usr/local/Cellar/proj/7.0.1` and attach config.log ?

**Comment by GeraldCNelson** [comment]
The find output is below. Not sure where to look for config.log

/usr/local/Cellar/proj/7.0.1
/usr/local/Cellar/proj/7.0.1/INSTALL_RECEIPT.json
/usr/local/Cellar/proj/7.0.1/bin
/usr/local/Cellar/proj/7.0.1/bin/proj
/usr/local/Cellar/proj/7.0.1/bin/invgeod
/usr/local/Cellar/proj/7.0.1/bin/gie
/usr/local/Cellar/proj/7.0.1/bin/geod
/usr/local/Cellar/proj/7.0.1/bin/projinfo
/usr/local/Cellar/proj/7.0.1/bin/cct
/usr/local/Cellar/proj/7.0.1/bin/cs2cs
/usr/local/Cellar/proj/7.0.1/bin/invproj
/usr/local/Cellar/proj/7.0.1/bin/projsync
/usr/local/Cellar/proj/7.0.1/.brew
/usr/local/Cellar/proj/7.0.1/.brew/proj.rb
/usr/local/Cellar/proj/7.0.1/ChangeLog
/usr/local/Cellar/proj/7.0.1/AUTHORS
/usr/local/Cellar/proj/7.0.1/include
/usr/local/Cellar/proj/7.0.1/include/proj
/usr/local/Cellar/proj/7.0.1/include/proj/coordinatesystem.hpp
/usr/local/Cellar/proj/7.0.1/include/proj/nn.hpp
/usr/local/Cellar/proj/7.0.1/include/proj/io.hpp
/usr/local/Cellar/proj/7.0.1/include/proj/metadata.hpp
/usr/local/Cellar/proj/7.0.1/include/proj/datum.hpp
/usr/local/Cellar/proj/7.0.1/include/proj/coordinateoperation.hpp
/usr/local/Cellar/proj/7.0.1/include/proj/common.hpp
/usr/local/Cellar/proj/7.0.1/include/proj/util.hpp
/usr/local/Cellar/proj/7.0.1/include/proj/crs.hpp
/usr/local/Cellar/proj/7.0.1/include/geodesic.h
/usr/local/Cellar/proj/7.0.1/include/proj_api.h
/usr/local/Cellar/proj/7.0.1/include/proj_constants.h
/usr/local/Cellar/proj/7.0.1/include/proj.h
/usr/local/Cellar/proj/7.0.1/include/proj_experimental.h
/usr/local/Cellar/proj/7.0.1/include/proj_symbol_rename.h
/usr/local/Cellar/proj/7.0.1/README
/usr/local/Cellar/proj/7.0.1/README.md
/usr/local/Cellar/proj/7.0.1/COPYING
/usr/local/Cellar/proj/7.0.1/NEWS
/usr/local/Cellar/proj/7.0.1/lib
/usr/local/Cellar/proj/7.0.1/lib/libproj.la
/usr/local/Cellar/proj/7.0.1/lib/libproj.a
/usr/local/Cellar/proj/7.0.1/lib/pkgconfig
/usr/local/Cellar/proj/7.0.1/lib/pkgconfig/proj.pc
/usr/local/Cellar/proj/7.0.1/lib/libproj.dylib
/usr/local/Cellar/proj/7.0.1/lib/libproj.19.dylib
/usr/local/Cellar/proj/7.0.1/share
/usr/local/Cellar/proj/7.0.1/share/man
/usr/local/Cellar/proj/7.0.1/share/man/man1
/usr/local/Cellar/proj/7.0.1/share/man/man1/gie.1
/usr/local/Cellar/proj/7.0.1/share/man/man1/cct.1
/usr/local/Cellar/proj/7.0.1/share/man/man1/projinfo.1
/usr/local/Cellar/proj/7.0.1/share/man/man1/cs2cs.1
/usr/local/Cellar/proj/7.0.1/share/man/man1/proj.1
/usr/local/Cellar/proj/7.0.1/share/man/man1/geod.1
/usr/local/Cellar/proj/7.0.1/share/man/man1/projsync.1
/usr/local/Cellar/proj/7.0.1/share/proj
/usr/local/Cellar/proj/7.0.1/share/proj/proj.db
/usr/local/Cellar/proj/7.0.1/share/proj/nad83
/usr/local/Cellar/proj/7.0.1/share/proj/CH
/usr/local/Cellar/proj/7.0.1/share/proj/world
/usr/local/Cellar/proj/7.0.1/share/proj/proj.ini
/usr/local/Cellar/proj/7.0.1/share/proj/nad.lst
/usr/local/Cellar/proj/7.0.1/share/proj/ITRF2000
/usr/local/Cellar/proj/7.0.1/share/proj/ITRF2008
/usr/local/Cellar/proj/7.0.1/share/proj/nad27
/usr/local/Cellar/proj/7.0.1/share/proj/projjson.schema.json
/usr/local/Cellar/proj/7.0.1/share/proj/GL27
/usr/local/Cellar/proj/7.0.1/share/proj/ITRF2014
/usr/local/Cellar/proj/7.0.1/share/proj/other.extra

**Comment by rouault** [comment]
> Not sure where to look for config.log

it is an output of the configure script, in the same directory

**Comment by GeraldCNelson** [comment]
Ah, obvious once you say it. I have attached a zip version of it. 
[config.log.zip](https://github.com/OSGeo/gdal/files/4674274/config.log.zip)

**Comment by rouault** [comment]
Relevant extract is
```
configure:24262: g++ -std=c++11 -o conftest -g -O2   conftest.cpp -lproj  -L/usr/local/Cellar/proj/7.0.1/lib -lproj -lsqlite3  -lz -lpthread -ldl  >&5
g++: warning: couldn't understand kern.osversion '19.4.0
ld: warning: building for macOS 10.4 is deprecated
ld: warning: Csu support file -lcrt1.o not found, changing to target macOS 10.8 where it is not needed
ld: library not found for -lgcc_s.10.4
collect2: error: ld returned 1 exit status
```
This looks to be very Mac specific or to your installation. Particularly the "ld: library not found for -lgcc_s.10.4". Perhaps an issue of mixing gcc vs clang. I don't think I can help further. Perhaps post to the mailing list where more people might be able to help.

**Comment by GeraldCNelson** [comment]
looking at this log file, there are lots of issues with /usr/local/include/_stdio.h. The file is a simlink to /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/_stdio.h and was created on Oct 24, 2019. 

This warning also occurs several time. g++: warning: couldn't understand kern.osversion '19.4.0

**Comment by GeraldCNelson** [comment]
Am I understanding the log correctly to say that the information about kern.osversion '19.4.0 comes fro
/usr/bin/hostinfo      = Mach kernel version:
	 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64?

If I look in /usr/bin, hostinfo was created on Mar 17.

**Comment by GeraldCNelson** [comment]
Another issue. I don't find lcrt1.o on my Mac. What should have installed that?

**Comment by GeraldCNelson** [comment]
What's the url for the mailing list?

**Comment by rouault** [comment]
it was indicated in the preamble of the issue template ....https://lists.osgeo.org/mailman/listinfo/gdal-dev

**Comment by GeraldCNelson** [comment]
After studying the config.log file some more and doing some more research on my mac, I discovered an old g++ file. I renamed it to g++old and now ./configure runs to completion. Make returns some errors but that's a problem for another issue. Hopefully not.
