### ISSUE TITLE
MapInfo File converts None value for OFTTime field to '00:00:00'

### ISSUE THREAD

**Issue by rbuffat** [OSGeo/gdal#2612]
I noticed that the MapInfo File driver saves, since GDAL 2.0, None values as  '00:00:00', which is unexpected for me. However, I'm not familiar with this file format, thus I'm not sure if this normal for this format. 

Code to reproduce:
```
from osgeo import gdal
from osgeo import ogr
import osgeo.osr as osr
import sys
import os

print("GDAL:", gdal.__version__)

gdal.UseExceptions()

driverName = 'MapInfo File'
filename = '/tmp/test.tab'

if os.path.exists(filename):
    os.unlink(filename)


def error_handler(err_level, err_no, err_msg):
    print(err_level, err_no, err_msg)


gdal.PushErrorHandler(error_handler)


drv = gdal.GetDriverByName(driverName)
srs = osr.SpatialReference()
srs.ImportFromEPSG(4326)

ds = drv.Create(filename, 0, 0, 0, gdal.GDT_Unknown)
if ds is None:
    print("Creation of output file failed.\n")
    sys.exit(1)

lyr = ds.CreateLayer("abc", None, ogr.wkbPoint)
if lyr is None:
    print("Layer creation failed.\n")
    sys.exit(1)

field_defn = ogr.FieldDefn("time", ogr.OFTTime)
if lyr.CreateField(field_defn) != 0:
    print("Creating field failed.\n")
    sys.exit(1)

# None value for ogr.OFTTime field
point = ogr.Geometry(ogr.wkbPoint)
point.SetPoint_2D(0, 1, 2)
feat = ogr.Feature(lyr.GetLayerDefn())
feat.SetField("time", None)
feat.SetGeometry(point)
if lyr.CreateFeature(feat) != 0:
    print("Failed to create feature in shapefile.\n")
    sys.exit(1)
feat.Destroy()

# Normal value for ogr.OFTTime field
point = ogr.Geometry(ogr.wkbPoint)
point.SetPoint_2D(0, 3, 4)
feat = ogr.Feature(lyr.GetLayerDefn())
feat.SetField("time", 2020, 1, 1, 14, 32, 3.0, 0)
feat.SetGeometry(point)
if lyr.CreateFeature(feat) != 0:
    print("Failed to create feature in shapefile.\n")
    sys.exit(1)
feat.Destroy()

ds = None

driver = ogr.GetDriverByName(driverName)
dataSource = driver.Open(filename, 0)
layer = dataSource.GetLayer()
for feat in layer:
    geom = feat.GetGeometryRef()
    print("WKT: {}, Time: {}".format(geom.ExportToWkt(), feat.GetField("time")))
```

Output:
```
GDAL: 3.0.4
WKT: POINT (0.99 2.0), Time: 00:00:00
WKT: POINT (3.0 4.01), Time: 14:32:03
```

**Comment by rouault** [comment]
> I noticed that the MapInfo File driver saves, since GDAL 2.0, None values as '00:00:00', which is unexpected for me

I believe that would have been the same pre 2.0 with a unset field, as far as I can see from the code (didn't try 1.11, but looking at the code). I don't know how to encode a null / unset field in .dat files. The issue would be the same for a numeric data type where 0 would be written. If you have access to MapInfo and it can generate a dataset with null / empty fields (or have a dataset with such fields), that could be helpful to reverse engineer how this is done.

Looking at the defunct pull request where PB tried to submit their EFAL driver for the MapInfo extended format, I can see in https://github.com/anshulgoelpb27/gdal/blob/9afe20c201f904354bf047b3a519e9be9c4efb5a/gdal/ogr/ogrsf_frmts/EFAL/ogrefallayer.cpp#L749 that it seems that the concept of unset and null fields are present, but that's perhaps an enhancement of the extended format.

**Comment by rbuffat** [comment]
Unfortunately not, I found this issue when creating tests for Fiona. It seems as they offer a 30day trial version. I will try if I can get it to run on Linux and report back.

A quick google search revealed some wild results of using -9999 as equivalent to null 🤔: 
- https://gis.stackexchange.com/questions/18599/mapinfo-tab-integer-fields-and-null-values/18604
- https://s3.amazonaws.com/gitbook/Desktop-Advanced-2018/DesktopAdvanced1Attributes/1.07.HandlingNullAttributes.html

**Comment by nyalldawson** [comment]
I think I've still access to MapInfo 16 through one of my clients - I'll check today and see if I can make a reference file.

**Comment by rbuffat** [comment]
I just found this old discussion, in case it helps: https://trac.osgeo.org/gdal/ticket/4337

**Comment by rouault** [comment]
Looking at the XXX.* dataset attached to https://trac.osgeo.org/gdal/ticket/4337, it has only Date fields, not Time one. For those date fields, empty/null dates are encoded as 0000/00/00 which is properly handled on the read and write side of the driver.

For Time, they are encoded in the .DAT as a number of milliseconds on a signed 32bit integer. On the read side of the driver, a negative value or one > 86400000 is considered as non set, with a comment "nS is set to -1 when the value is 'not set'", and there seems to be some code on the write side with it. So it would be a potential solution, at least interoperable in the OGR world. But a dataset coming from Mapinfo wouldn't hurt indeed.

@nyalldawson I'm attaching a dataset converted with a patched GDAL to use this -1 trick for time field. Can you try it possibly with Mapinfo ?  [ogrtimenull.tab.zip](https://github.com/OSGeo/gdal/files/4678801/ogrtimenull.tab.zip)
content: one record with timefield, datefield, datetimefiel set, and another one with them empty
```
OGRFeature(timenull):1
  id (Integer) = 1
  timefield (Time) = 12:34:56
  datefield (Date) = 2020/05/25
  datetimefield (DateTime) = 2020/05/25 12:34:56
  WKT (String) = POINT (1 2)
  Style = SYMBOL(a:0,c:#000000,s:12pt,id:"mapinfo-sym-35,ogr-sym-10")
  POINT (1 2)

OGRFeature(timenull):2
  id (Integer) = 2
  WKT (String) = POINT (3 4)
  Style = SYMBOL(a:0,c:#000000,s:12pt,id:"mapinfo-sym-35,ogr-sym-10")
  POINT (3 4)
```
Numeric (integer / floating point) would be interesting. I guess there isn't much possibility for integers. For floating points, some special IEEE754 values could probably be an option (like NaN)

**Comment by nyalldawson** [comment]
Here's a table created in Mapinfo 16 with all possible field types, and a mix of null/not null rows.

Note that it's impossible to null the numeric and logical (boolean) field types - there's just no way in MapInfo to do this, they keep getting reset back to 0/false.

Time fields CAN be nulled in MapInfo.
 
[mixed_nulls.zip](https://github.com/OSGeo/gdal/files/4679032/mixed_nulls.zip)

**Comment by nyalldawson** [comment]
@rouault 
> I'm attaching a dataset converted with a patched GDAL to use this -1 trick for time field. Can you try it possibly with Mapinfo ? ogrtimenull.tab.zip
content: one record with timefield, datefield, datetimefiel set, and another one with them empty

Here's how this looks in MI 12.5:

![image](https://user-images.githubusercontent.com/1829991/82846201-0ab0f200-9f2b-11ea-83c9-eee6719c4355.png)

**Comment by nyalldawson** [comment]
ogrtimenull.tab.zip seems correct to me -- I can't see any difference in the null time field present in that table vs a table created solely in MapInfo.

**Comment by rouault** [comment]
@nyalldawson Thanks ! I confirm MapInfo does use the time  = -1 trick to indicate unset value. Fix under way

**Comment by nyalldawson** [comment]
@rouault great! Is there anything else which would be useful to test/datasets to craft in MapInfo while I've got this license available?

**Comment by rouault** [comment]
> Is there anything else which would be useful to test/datasets to craft in MapInfo while I've got this license available?

probably the CRS side of things. Like if there was a way to automate the generation of .tab files with all supported EPSG codes...

**Comment by nyalldawson** [comment]
Ok, inbound!

**Comment by nyalldawson** [comment]
Here you go: Lots of null records here, wherever MapInfo reports "Invalid coordinate system".

That said, this version of MapInfo is quite out of date, so likely a newer one would fill some of these gaps.

[crs.txt](https://github.com/OSGeo/gdal/files/4679191/crs.txt)

**Comment by rbuffat** [comment]
Thanks! @rouault @nyalldawson
