### ISSUE TITLE
Getting vertical units from 3D CRS

### ISSUE THREAD

**Issue by jjimenezshaw** [OSGeo/gdal#2617]
## Expected behavior and actual behavior.

I am trying to get the axis information in C++, including **units**, from all the axes in a CRS.

For 2D CRSs there is no problem with `OGRSpatialReference::GetAngularUnits` and `OGRSpatialReference::GetTargetLinearUnits`.
For compound CRSs I can get the vertical axis unit with `OGRSpatialReference::GetTargetLinearUnits("VERT_CS",...)`.

However for a 3D CRS, like `EPSG:4979` I do not find how to get it.
I get only `unknown`.

## GDAL version and provenance
compiled GDAL 3.1.0 from source.

**Comment by rouault** [comment]
I'm not super enthusiastic about extending the SRS API of GDAL. It is mostly historical and a bit at odds with the modern modeling now used by PROJ. My initial feeling would be to suggest you to either use PROJ API to do that, or export to PROJJSON and parse the JSON.
