### ISSUE TITLE
configure: error: PROJ 6 symbols not found (Tried in a thousand ways)

### ISSUE THREAD

**Issue by Saszalez** [OSGeo/gdal#2619]
I have the problem that when compiling **Gdal-3.1.0** it cannot find _PROJ 6_. I have version **Proj-7.0.0** installed and I am using Intel compilers. My operating system is _CentOS 7.3_

The configuration:
`./configure --prefix=/home/libraries/intel/gdal --with-poppler=/home/libraries/intel/poppler --with-proj=/home/libraries/intel/proj`

Further:
```
export CPPFLAGS=-I/home/libraries/intel/proj/include/
export CFLAGS=-I/home/libraries/intel/proj/include/
export LDFLAGS=-L/home/libraries/intel/proj/lib
```

I also tried indicating the library:
`export LDFLAGS='-L/home/libraries/intel/proj/lib -lproj'`

I don't know what else to try to find Proj.

**Comment by rouault** [comment]
Look at the config.log report when it tries to link PROJ.

**Comment by Saszalez** [comment]
```
checking for PROJ >= 6 library... checking for proj_create_from_wkt in -lproj... no
checking for proj_create_from_wkt in -lproj... no
checking for proj_create_from_wkt in -lproj... no
checking for internal_proj_create_from_wkt in -lproj... no
checking for internal_proj_create_from_wkt in -lproj... no
checking for internal_proj_create_from_wkt in -linternalproj... no
checking for internal_proj_create_from_wkt in -linternalproj... (cached) no
configure: error: PROJ 6 symbols not found
```

**Comment by rouault** [comment]
I really mean the `config.log` file generated by ./configure in the same directory as it. It will show the compilation and linking lines and result for each of this "checking for ..." attempts

**Comment by Saszalez** [comment]
Sorry, you're right, you meant the file. I just saw the following lines:

```
configure:24007: checking for PROJ >= 6 library
configure:24237: checking for proj_create_from_wkt in -lproj
configure:24262: icpc -std=c++11 -o conftest -DHAVE_AVX_AT_COMPILE_TIME -DHAVE_SSSE3_AT_COMPILE_TIME -DHAVE_SSE_AT_COMPILE_TIME -g -O2 -I/home/libraries/intel/proj/include/ -L/home/libraries/intel/proj/lib -lproj conftest.cpp -lproj  -L/home/libraries/intel/proj/lib -lproj -lsqlite3  -lz -lpthread -lm -lrt -ldl  >&5
ld: cannot find -lsqlite3
```
Could the error be because it can't find sqlite3? I could tell you the path to Gdal, just like I did when I compiled Proj.

**Comment by rouault** [comment]
Yes, you can add it to LDFLAGS. Or wit the --with-proj-extra-lib-for-test=ARG option. (There is a now a recent fix in GDAL master to avoid those manual steps and use the GDAL detection of sqlite3 when trying to link PROJ)

**Comment by Saszalez** [comment]
Using the `--with-proj-extra-lib-for-test=ARG` option doesn't work for me. But I solved it in the following way:
`./configure --prefix=/home/libraries/intel/gdal --with-poppler=/home/libraries/intel/poppler/ --with-proj=/home/libraries/intel/proj/ LDFLAGS='-L/home/libraries/intel/sqlite/lib -lsqlite3'`

**Comment by ev0065** [comment]
@rouault I was hoping that you could help me with this issue too. I'm working on Ubuntu 20.04 now and I am simply trying to build gdal from the source code. In other words, I cloned the repo and now trying to run `./configure`. I am however getting this error during `./configure`: 
```
checking for SQLite3 library >= 3.0.0... yes
checking for sqlite3_column_table_name in -lsqlite3... yes
checking for PROJ >= 6 library... checking for proj_create_from_wkt in -lproj... no
checking for internal_proj_create_from_wkt in -lproj... no
checking for internal_proj_create_from_wkt in -linternalproj... no
configure: error: PROJ 6 symbols not found
```
and this from config.log:
```
configure:20798: checking for PROJ >= 6 library
configure:21028: checking for proj_create_from_wkt in -lproj
configure:21053: g++ -o conftest -DHAVE_AVX_AT_COMPILE_TIME -DHAVE_SSSE3_AT_COMPILE_TIME -DHAVE_SSE_AT_COMPILE_TIME -g -O2   conftest.cpp -lproj  -L/usr/bin//lib -lproj   -lsqlite3 -lpthread -lm -lrt -ldl  >&5
```

As you can see, sqlite3 is installed and found. `which proj` outputs `/usr/bin/proj`, so I tried running `./configure --with-proj=/usr/bin` and `./configure --with-proj=/usr/bin/proj` as well as with `/user/local`, even though it isn't stored there (Just something I saw online). I was hoping on clarification for LDFLAGS and exactly what needs to be put there.

**Comment by mgomov** [comment]
@ev0065 I'm just going through this process on Ubuntu 20.04 as well. You need the proj dev symbols, which I believe you can get using `sudo apt-get install libproj-dev`.

**Comment by ev0065** [comment]
@mgomov And that worked, thanks! I'm proceeding to `make` now so we'll see if that ends up working too. I feel like there is a major lack of documentation surrounding how to download this project - the only tutorials out there are over 7 years old and use Python 2.7. Maybe i'll make a how-to and post it somewhere

**Comment by rouault** [comment]
> Maybe i'll make a how-to and post it somewhere

You can also consider contributing to the main documentation.

**Comment by ev0065** [comment]
> You can also consider contributing to the main documentation.

Good idea, I'll look into that. 
Also @mgomov since we're on the same system, have you been able to run the python scripts? The `make` and `make install` work, and I'm now trying to run a python script, like `gdal2tiles.py` or `gdal_retile.py`. But, I'm getting the obvious error that I need to install gdal-bin. However, gdal-bin points to gdal version 3.0 and not 3.1 and I need specific options from gdal 3.1 for my usage. Any thoughts on that?

**Comment by mgomov** [comment]
@ev0065 I believe you need to `pip3 install gdal` to have access to those scripts, but a quick `find . -name "gdal2tiles*" in my build directory says that there's a version of the script in `swig/python/scripts/gdal2tiles.py` (I'm not sure if it gets installed anywhere with `make install`).

**Comment by larsop** [comment]
Just a comment on this. I am testing on CentOs 8 and I have Installed this proj packges using yum

```
proj72-debuginfo-7.2.0-1.rhel8.x86_64
proj72-7.2.0-1.rhel8.x86_64
proj72-devel-7.2.0-1.rhel8.x86_64
proj72-debugsource-7.2.0-1.rhel8.x86_64
proj72-static-7.2.0-1.rhel8.x86_64

```
On release HEAD detached at v3.2.0 I try to compile , so I run

./configure --with-pgconfig=/usr/pgsql-12/bin/pg_config --with-geosconfig=/usr/geos38/bin/geos-config --with-projdir=/usr/proj72 --with-raster --with-python

In the console I see this 

```
checking for PROJ >= 6 library... checking for proj_create_from_wkt in -lproj... no
checking for internal_proj_create_from_wkt in -lproj... no
checking for internal_proj_create_from_wkt in -linternalproj... no
configure: error: PROJ 6 symbols not found


```
The log is attached
[config.log](https://github.com/OSGeo/gdal/files/5558306/config.log)

To resolve this I had to to checkout PROJ and build and install that On branch 7.2 and then run 

./configure --with-pgconfig=/usr/pgsql-12/bin/pg_config --with-geosconfig=/usr/geos38/bin/geos-config --with-projdir=/usr/proj72 --with-raster --with-python

And then error message was gone.
