### ISSUE TITLE
LIBGDAL_CURRENT GDALmake.opt.in update

### ISSUE THREAD

**Issue by QuiteAFoxtrot** [OSGeo/gdal#2629]
I was installing GDAL from gdal-3.1.0.tar.gz for the python bindings, I got it installed into my environment, so I popped open a python terminal and gave it the old "import gdal" to see if it worked -- it came back with an error
"ImportError: libgdal.so.27: cannot open shared object file: No such file or directory"

However, after running 'make' and 'make install' I had a perfectly good libgdal.so.3.1.0 (and symlinks libgdal.so. and libgdal.so.3 both pointing to libgdal.3.1.0) in my /prefix/lib directory.  I created a symlink libgdal.so.27 -> libgdal.so.3.1.0 and when I do "import gdal" it imports just fine, and I opened up a geotiff file and got the raster into a numpy array and such successfully.  I wondered what could be causing this headache, and I noticed in "GDALmake.opt.in" the value of LIBGDAL_CURRENT is set to 27.  Should this value have been updated for the GDAL-3.X.X releases?

**Comment by rouault** [comment]
LIBGDAL_CURRENT = 27 is expected for GDAL 3.1 and was on purpose set to that value.
I'm not sure about the cause for your issue (mix between libtool and non-libtool builds, or lack of sufficient cleanup of a previous installation ?), but LIBGDAL_CURRENT value isn't the root cause

**Comment by QuiteAFoxtrot** [comment]
Thanks rouault, I think that's exactly what it was, I couldn't get it to work right using libtools so I added --without-libtools to the configure, but I had left behind a libgdal.so.27.0.0 in the .libs directory.

**Comment by spacyk** [comment]
I solved this by adding `/usr/local/bin` to the shared libraries path:
 `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib`.

**Comment by EmileSonneveld** [comment]
I solved this locally by running `ln -s /usr/lib/libgdal.so /usr/lib/libgdal.so.27`. For gdal version 3.2.2

**Comment by paul-papacz** [comment]
Another (potential) solution is to run `./configure` with `--libdir=/usr/lib` or `--libdir=/usr/lib64` (and potentially `--prefix=/usr`) so that the shared objects get installed there.

That way you could avoid having to set `LD_LIBRARY_PATH` or create symlinks.

Just make sure it doesn't clash with another installation of GDAL.
