### ISSUE TITLE
Intel Compiler 14.0.2 (ipcp) fails c++11 check in ./configure

### ISSUE THREAD

**Issue by wwlwpd** [OSGeo/gdal#2639]
## Expected behavior and actual behavior.

I'd expect this to compile with `icpc` version 14.0.2.

## Steps to reproduce the problem.
run `CC=icc CXX=icpc ./configure` on a system with 14.0.2 of `icpc`,

>icpc --version
>icpc (ICC) 14.0.2 20140120
>Copyright (C) 1985-2014 Intel Corporation.  All rights reserved.

## Operating system
>Red Hat Enterprise Linux Server release 6.8 (Santiago)

## GDAL version and provenance

master, `f658cb31e79e`

**Comment by wwlwpd** [comment]
Last passed c++11 check in tag 2.2.4

**Comment by rouault** [comment]
There might be a possibility that the configure check wrongly rejects that compiler, but I've no means of checking. But it is likely too that ICC 14.0.2 dating from 2014 doesn't support completely C++11. 
So I think the resolution would be to update to a more recent compiler (I believe newer ICC pass the test).
GDAL 2.2 was the last version not to require C++11
