### ISSUE TITLE
RGdal compilation fails - OGR_write.cpp:232:29: error: ‘GDALClose’ was not declared in this scope

### ISSUE THREAD

**Issue by pascalgulikers** [OSGeo/gdal#2640]
## Expected behavior and actual behavior.

Succesful compilation but fails for the latest rgdal release 1.5-8

install.packages(rgdal)
* installing *source* package ‘rgdal’ ...
** package ‘rgdal’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
OGR_write.cpp: In function ‘SEXPREC* OGR_write(SEXP)’:
OGR_write.cpp:232:29: error: ‘GDALClose’ was not declared in this scope
             GDALClose( poDS );
                             ^
make: *** [OGR_write.o] Error 1
ERROR: compilation failed for package ‘rgdal’

## Steps to reproduce the problem.
install.packages(rgdal)

## Operating system

Red Hat Enterprise Linux Server 7.6

## GDAL version and provenance

GDAL 1.11.4
Proj 4.8.0
GCC 5.3.1-6.1

**Comment by rouault** [comment]
This is to report to the rgdal developers. rgdal != GDAL

**Comment by pascalgulikers** [comment]
Yes, I'm aware of that. I couldn't find a place to report and noticed that previous bugs were reported here as well. Sorry!

**Comment by rouault** [comment]
> noticed that previous bugs were reported

and closed for the same reason :-)

>  Sorry!

No problem
