### ISSUE TITLE
Can't convert BSQ starting with a ?magic number?

### ISSUE THREAD

**Issue by floppyzedolfin** [OSGeo/gdal#2641]
## Expected behavior and actual behavior.
Current behaviour:
> gdalinfo myFile.bsq
> ERROR 1: Invalid dataset dimensions : 0 x 0
> gdalinfo failed – unable to open ‘myFile.bsq’

Expected behaviour:
> gdalinfo myFile.bsq
> Driver: EHdr/ESRI .hdr Labelled 
> Files: myFile.bsq 
>       myFile.hdr 
> Size is 2048, 2048 
> Origin = (-0.500000000000000,0.500000000000000) 
> Pixel Size = (1.000000000000000,-1.000000000000000) 
> Corner Coordinates: 
> Upper Left ( -0.5000000, 0.5000000) 
> Lower Left ( -0.500, -2047.500) 
> Upper Right ( 2047.500, 0.500) 
> Lower Right ( 2047.500, -2047.500) 
> Center ( 1023.500, -1023.500) 
> Band 1 Block=2048x1 Type=UInt32, ColorInterp=Undefined

## Steps to reproduce the problem.
First, you need a .bsq and a .hdr file. Any file would be OK.
Then, hexedit the .bsq and write this as the first bytes : _14 00 00 00_ (overwrite existing data, in order not to change the size of the file)
(those are the first bits of my image)
Then, `gdalinfo myFile.bsq`

## Operating system
gdal 2.2.2 on CentOS-7 (reproduced on the gdal-ubuntu-light docker image)

## GDAL version and provenance
gdal versions 2.2.2 and 3.2.0 reproduce the issue. gdal version 1.11.4 doesn't.

## Investigation
We _think_ the issue comes from the fact that a driver accepts 14 00 as a magic number for its format, and that this causes gdal to try and use it instead of the EHdr one.
We tried and changed the first bits to _00 00 ..._, and this did solve our problem (this is NOT an acceptable solution, of course).

## Workaround
We declared a list of drivers not to use (all but the input and the output), in order to minimize the potentiality of this happening. However, 0% probability doesn't exist.

## Expected solution(s)
I'd like a -if parameter that specified the format of the input data.
Alternatively, formats with no magic number (and especially raw-buffers) should be tested before formats with magic numbers when trying to find the adequate driver.
[myFile.tar.zip](https://github.com/OSGeo/gdal/files/4716967/myFile.tar.zip)

**Comment by jratike80** [comment]
ArcMap 10.8 cannot open that image. How/what software has created it? How do you know that it is a valid "EHdr/ESRI .hdr Labelled" image?

**Comment by floppyzedolfin** [comment]
I generated this monoband image from source code. I'm pretty sure it'd be possible to generate such an image from a basic image (all you need to have is a 14 00 00 00 in the top left, and... that's it.

.bsq is a raw buffer, no header, no metadata whatsoever. I'll try and provide an image that can't be converted back.

**Comment by jratike80** [comment]
It may be that the name "EHdr/ESRI .hdr Labelled" misleads me because fundamentally it is just raw data. But if the format is supposed to be some of those that ArcMap supports (probably bil + hdr then) I can have a try and convert your source image to have something to compare with.

**Comment by rouault** [comment]
"EHdr/ESRI .hdr Labelled"  is this format: https://desktop.arcgis.com/en/arcmap/10.3/manage-data/raster-and-images/bil-bip-and-bsq-raster-files.htm

**Comment by floppyzedolfin** [comment]
[2641.tar.zip](https://github.com/OSGeo/gdal/files/4717738/2641.tar.zip)

Contents of the tar :
- a valid PGM image I wrote : test.pgm
- that image converted to png (via convert): `convert test.pgm test.png`
- that same image converted from png to EHdr via gdal : `gdal_translate -of EHdr test.png test.bsq`
- the bsq and hdr files that gdal 3.2 generated (with warnings) 

```
/tmp# gdal_translate -of EHdr test.png test.bsq
Input file size is 24, 700
ERROR 1: Invalid dataset dimensions : 0 x 0
ERROR 1: Invalid dataset dimensions : 0 x 0
0ERROR 1: Invalid dataset dimensions : 0 x 0
...10...20...30...40...50...60...70...80...90...100 - done.
/tmp# echo $?
0
/tmp# gdalinfo test.bsq
ERROR 1: Invalid dataset dimensions : 0 x 0
gdalinfo failed - unable to open 'test.bsq'.
```

The size of the input image is just there to make the number of file "big enough" to skip header-size related checks.

**Comment by jratike80** [comment]
I made some testing with GDAL and ArcMap. Neither of them could convert the image into bil/bsq (I suppose bil=bsq when there is only one band) with the default settings. ArcMap gave an error without proper explanation. File is still created on the disk but GDAL reports 0x0 size.

However, if I changed the output pixel type in ArcMap into 8 bit unsigned or 32 bit unsigned then the conversion did succeed. 

GDAL does also good job with
`gdal_translate -of EHdr test.png testz.bsq -ot int32`

The problem has something to do with the datatype. I am not an expert on this area and I can't say if "14 00 00 00" is valid as int16/uint16 type, but at least both GDAL and ArcMap have hard times with it.

**Comment by rouault** [comment]
> I am not an expert on this area and I can't say if "14 00 00 00" is valid as int16/uint16 type, but at least both GDAL and ArcMap have hard times with it.

There was definitely a bug in GDAL, with the LCP driver improperly recognizing the .bsq file. Not the first time we have such issue, not the last time

Regarding ArcMap, I don't know. Maybe they suffer from the GDAL bug as well.

Changing output type changes the raw values written, which will cause the LCP driver no longer to recognize the .bsq file.

**Comment by jratike80** [comment]
Ok. I will try to send this information to ESRI through the Finnish supplier.
