### ISSUE TITLE
configure: error: PROJ 6 symbols not found - CentOS 8

### ISSUE THREAD

**Issue by cvernooy23** [OSGeo/gdal#2645]
I am trying to install gdal 3.1.0 on CentOS 8 and I am getting this error:

```
[user@hostname gdal-3.1.0]$ ./autogen.sh
[user@hostname gdal-3.1.0]$ ./configure
...
configure: Bash completions not requested
checking for PROJ >= 6 library... checking for proj_create_from_wkt in -lproj... no
checking for proj_create_from_wkt in -lproj... no
checking for proj_create_from_wkt in -lproj... no
checking for internal_proj_create_from_wkt in -lproj... no
checking for internal_proj_create_from_wkt in -lproj... no
checking for internal_proj_create_from_wkt in -linternalproj... no
checking for internal_proj_create_from_wkt in -linternalproj... (cached) no
configure: error: PROJ 6 symbols not found
...
```

proj 6.2.0 is installed
```
[user@hostname gdal-3.1.0]$ proj
Rel. 6.2.0, September 1st, 2019
```

I reviewed issue #1352 and I tried the example solution given, which also doesn't work

`./configure --with-proj=/usr/local`

I found `/usr/share/proj` using `sudo find / -name "proj"`

all of the following also failed, with the same error

`./configure --with-proj=/usr/share`
`./configure --with-proj=/usr/share/proj`
`./configure --with-proj=/usr/bin`
`./configure --with-python=python3 --with-proj=/usr/share`
`./configure --with-python=python3`

proj was intalled from the EPEL repo 

```
Installed Package
Name         : proj
Version      : 6.2.0
Release      : 1.el8
Architecture : x86_64
Size         : 9.0 M
Source       : proj-6.2.0-1.el8.src.rpm
Repository   : @System
From repo    : epel
Summary      : Cartographic projection software (PROJ)
URL          : https://proj.org
License      : MIT
Description  : Proj and invproj perform respective forward and inverse transformation of
             : cartographic data to or from cartesian data with a wide range of selectable
             : projection functions.
```
## Expected behavior and actual behavior.

I expect it to find proj

## Steps to reproduce the problem.
```
yum -y install epel-release
sudo yum install proj python3-pip postgresql96-contrib -y ## (epel & postgres repos)
wget http://download.osgeo.org/gdal/CURRENT/gdal-3.1.0.tar.gz
tar xvfz gdal-3.1.0.tar.gz
cd gdal-3.1.0/
sudo pip3 install -r doc/requirements.txt
./autogen.sh
./configure
```
## Operating system

CentOS 8 kernel 4.18

## GDAL version and provenance

gdal 3.1.0 from http://download.osgeo.org/gdal/CURRENT

**Comment by rouault** [comment]
You likely need to use the proj-devel package. 
See https://copr.fedorainfracloud.org/coprs/neteler/GDAL/ for CentOS / Fedora GDAL packages

**Comment by cvernooy23** [comment]
gotcha thanks. that definitely works when the system has access to the internet. But I see the repo & GPG links so that definitely points me in the right direction, without manually resolving these dependencies manually and building from source. 

I'm doing this on centos8 but that's just to resolve the application deps, my target is ubi8/8.2, any advice or special instructions on that platform?

**Comment by rouault** [comment]
I'm not familiar with ubi8. You could perhaps ask on the GDAL mailing list

**Comment by ev0065** [comment]
@cvernooy23 Did you ever figure this out? I'm migrating to centos 8 and trying to use gdal 3.1, since it doesn't work on Windows...

**Comment by lefrog** [comment]
Just for others in case they faced the same issue, as per @rouault suggestion installing proj-dev library fixed it for me
OS: Ubuntu 20.04
Package: libproj-dev
cmd: `sudo apt install libproj-dev`
