### ISSUE TITLE
Referencing to the function isatty without any compiler/OS protection. Error on Visual Studio

### ISSUE THREAD

**Issue by mariopettinati** [OSGeo/gdal#2647]
## Expected behavior and actual behavior.

Some apps are referencing the function isatty without any compiler/OS protection. This results in error when compiling in Visual Studio.

The library is correctly built, but for some executables we get an error

Examples:
apps/gdaltransform.cpp:344
apps/gdallocationinfo.cpp:233

## Steps to reproduce the problem.

Just start the compilation using Visual Studio. 

Edit 1: 
I used the following command line
nmake -f makefile.vc MSVC_VER=1910 DLLBUILD=1 WIN64=1 VERSION=310

Also attaching the nmake.local file with local 3rd party. Renaming it to .txt so it can be uploaded
[nmake.local.txt](https://github.com/OSGeo/gdal/files/4722964/nmake.local.txt)

Edit 2:

This is the error message:

gdaltransform.cpp
The GEOS C++ API is unstable, please use the C API instead
HINT: #include geos_c.h
c:\temp\inpe\deps\build\terralib-3rdparty-msvc17\terralib-3rdparty-msvc17\gdal-3.1.0\apps\gdaltransform.cpp(344): error C3861: 'isatty': identificador nƯ encontrado

The message in English would be: 'isatty': Identifier not found

## Operating system

Windows 10 - Visual Studio 2017 (Community Version)

## GDAL version and provenance

3.1.0 - stable

**Comment by rouault** [comment]
Well, we do have succesful Visual Studio builds : https://ci.appveyor.com/project/OSGeo/gdal/history

There must be something different in the way you invoke yours compared to those ones

**Comment by rouault** [comment]
Please give more elements on how you reproduce the issue exactly, and the exact compilation error messages emitted

**Comment by mariopettinati** [comment]
I've made some additions to the description. I paste the command line that I have been using since the prior version of the library, the nmake.local file and the error message.

The library have been correctly built in release and in debug. The issue is related to two executables that are built after the library

Maybe it has something to do with the way that I am building it. Using this command line and this nmake.local, I'm getting this same error message regarding to the use of the 'isatty' functon, that is not present in VS library

**Comment by rouault** [comment]
I'm wondering if there is not a "io.h" (which is the header where isatty() is defined in Windows) in your include path that would conflict with the Visual Studio one. Can you check that ?

**Comment by mariopettinati** [comment]
I'll try to check that. I'll look for this function in this file from VS library. 

My VS version is the community one. I added this info to the description

**Comment by mariopettinati** [comment]
Indeed the function is there. Is is protected by some defines, but it is there. I even opened one project that I have here, added the include and the funcition call, and it built. 

You are probably right. It must be a problem related to my environment when trying to find the correct implementation of "io.h". I'll invest more time on it. 

I'm terrible sorry for taking your time. May I close the issue or you do it?
