### ISSUE TITLE
GRIB CRS: no TOWGS84 ?

### ISSUE THREAD

**Issue by mheiskan** [OSGeo/gdal#2653]
I suspected the datum on a global weather forecast was incorrect. The `shapeOfTheEarth` was set to 6 - a globe with radius 6731229. I changed it to WGS84 using `eccodes` tools:
```
> grib_set -s shapeOfTheEarth=5 t2m_orig.grb2 t2m_wgs84.grb2
```
Nothing else was changed in the data except byte 69 defining the shape:
```
> cmp -l t2m_orig.grb2 t2m_wgs84.grb2
     69   6   5
```
However, when I displayed both GRIB files simultaneously using QGis with WGS84 map data, the rasters were placed identically. In reality the difference should have been about 0.2 degrees or about 20 kilometers in European latitudes.

It looks like this is due to how the GRIB driver interprets the shape settings:
```
>  gdalinfo -proj4 t2m_orig.grb2 | grep proj=
'+proj=longlat +R=6371229 +no_defs'
> gdalinfo -proj4 t2m_wgs84.grb2 | grep proj=
'+proj=longlat +datum=WGS84 +no_defs'
```
Shouldn't the first one be `+proj=longlat +R=6371229 +towgs=0,0,0 +no_defs`? Otherwise the global forecast will be placed at the same location no matter what the shape of the earth is, isn't it?

Platform: Fedora 32
GDAL version: 3.0.4
QGis version: 3.12

The `t2m_orig.grb2` filesize is 9.3M, so I'm not including it automatically. I can attach it later though if so requested.

**Comment by rouault** [comment]
I believe current behaviour is expected. The info in the GRIB dataset doesn't define a datum, but just an ellipsoid. We don't know how it relates to WGS84.

**Comment by mheiskan** [comment]
This seems to be the relevant documentation then:

https://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/grib2_table3-2.shtml

Quoted since such links often do not survive long:

"(2) With respect to code figures 0, 1, 3, 6 and 7, coordinates can only be unambiguously interpreted, if the coordinate reference system in which they are embedded is known. Therefore, defining the shape of the Earth alone without coordinate system axis origins is ambiguous. Generally, the prime meridian defined in the geodetic system WGS-84 can be safely assumed to be the longitudinal origin. However, because these code figures do not specify the longitudinal origin explicitly, it is suggested to contact the originating centre if high precision coordinates are needed, in order to obtain the precise details of the coordinate system used (effective as from 16 November 2016)."

Code figures 0, 1, 3, 6 and 7 refer to spheres or ellipsoids without any reference to the origin. This does make proper handling of GRIBs very inconvenient.

**Comment by mheiskan** [comment]
It is quite unfortunate that +towgs84=0,0,0 cannot even be guessed as the default, since several significant forecast models actually seem to be +datum=WGS84 despite the metadata claiming a spherical earth.

**Comment by rouault** [comment]
> since several significant forecast models actually seem to be +datum=WGS84 despite the metadata claiming a spherical earth.

Then that's a bug of the data producer. They should really use "5 : Earth assumed represented by WGS84"

**Comment by mheiskan** [comment]
We are in the process of convincing the producer their settings are wrong.
