### ISSUE TITLE
Limitation in conversion from StringList to String

### ISSUE THREAD

**Issue by andreadapisa** [OSGeo/gdal#2661]
## Expected behavior and actual behavior.
When a StringList field is converted to string type, the final string is limited to first 80 characters of original data.

This limitation of result length is enough for numeric and date fields, but is blocker when the source contains long strings.

For example, in S57 format there is the LNAM_REFS field (created by GDAL) that contains values of 16 characters.
This limitation cause the imposibility to link more than 4 features to a single feature.

A new option to configure is the string length could be useful. 

## Steps to reproduce the problem.

Get a S57 files from https://charts.noaa.gov/ENCs/ENCs.shtml

ogr2ogr -f "PostgreSQL" PG:"" US5NY1IM.000 -explodecollections --config OGR_S57_OPTIONS "SPLIT_MULTIPOINT=ON,ADD_SOUNDG_DEPTH=ON,RECODE_BY_DSSI=ON" --config S57_CSV .\data --config S57_PROFILE "Inland_Waterways" -mapFieldType "StringList=String"

The LNAM_REFS field contains values as "(n:AAAANNNNNNNNSSSS,AAAANNNNNNNNSSSS,AAAANNNNNNNNSSSS,AAAANNNNNNNNSSSS,...)"
where n= number of values, AAAA= 4 bytes for AGEN, NNNNNNNN= 8 bytes for FIDN, SSSS= 4 bytes for FIDS, all fields are hexadecimals.

## Source code
```c
constexpr int TEMP_BUFFER_SIZE = 80;
char szTempBuffer[TEMP_BUFFER_SIZE] = {};
```

## Operating system

Windows 10 
Ubuntu 16.04 64 bit

## GDAL version and provenance

GDAL 3.0.2 version from OSGeo/gdal site

**Comment by jratike80** [comment]
Have you tried to run ogr2ogr with option -unsetFieldWidth "Set field width and precision to 0."?

**Comment by andreadapisa** [comment]
I'm trying now, but the result hasn't changed.

Debugging the code I saw that the limitation is due to the size of the temporary buffer within the GetFieldAsString method, in which all the source strings (with comma separators) are collected in order to create a single string to be returned.

I open this ticket to remove this limitation (as an improvement):
or adding a new option to set the temporary buffer size,
or rather, using dynamic memory allocation for it in order to completely remove this limitation.

**Comment by jratike80** [comment]
Where is that piece of code?

**Comment by andreadapisa** [comment]
I saw your link , the options are different but I think it is the same issue:
-fieldTypeToString or -mapFieldType "StringList=String create the same result.

The code is in [ogrfeature.cpp](https://github.com/OSGeo/gdal/blob/master/gdal/ogr/ogrfeature.cpp)

The small temporary buffer is allocated at line [2300](https://github.com/OSGeo/gdal/blob/ad40f8889452fc6c298b1ec992fff78729f7acea/gdal/ogr/ogrfeature.cpp#L2300)
```c
char szTempBuffer[TEMP_BUFFER_SIZE] = {};
```
The loop on source values is interrupted at line [2585](https://github.com/OSGeo/gdal/blob/ad40f8889452fc6c298b1ec992fff78729f7acea/gdal/ogr/ogrfeature.cpp#L2585)
```c
if( strlen(szTempBuffer) + strlen(pszItem) + 6 >= sizeof(szTempBuffer) )
{
    break;
}
```
And the ellipsis is added at line [2595](https://github.com/OSGeo/gdal/blob/ad40f8889452fc6c298b1ec992fff78729f7acea/gdal/ogr/ogrfeature.cpp#L2595)
```c
if( i < nCount )
    strcat( szTempBuffer, ",...)" );
```

Using fieldTypeToString option I think the issue is also present for other type of source data, like OFTIntegerList, OFTInteger64List and OFTRealList.
