### ISSUE TITLE
Visual Studio and shared lib: CPL_DLL should be __declspec(dllexport) only for build

### ISSUE THREAD

**Issue by SpaceIm** [OSGeo/gdal#2664]
## Expected behavior and actual behavior.

Currently, consuming gdal shared with Visual Studio leads to a lot of warning C4251 like `ogr_featurestyle.h(89,41): warning C4251: 'OGRStyleTable::osLastRequestedStyleName'ÿ: class 'CPLString' needs to have dll-interface to be used by clients of class 'OGRStyleTable'`.

## Steps to reproduce the problem.

- Build gdal as a shared lib with Visual Studio.
- Link gdal shared in an executable or an other lib.

## Operating system

Windows 10

## GDAL version and provenance

GDAL 3.1.0 from github, built from source

## Workarounds:

- define `CPL_DISABLE_DLL` ~~or `CPL_DLL=__declspec(dllimport)`~~ while consuming gdal shared (counterintuitive)
- patch gdal with something like this:

in gdal/port/cpl_port.h:

```patch
--- a/gdal/port/cpl_port.h
+++ b/gdal/port/cpl_port.h
@@ -344,7 +344,11 @@ typedef unsigned int  GUIntptr_t;
 
 #ifndef CPL_DLL
 #if defined(_MSC_VER) && !defined(CPL_DISABLE_DLL)
-#  define CPL_DLL     __declspec(dllexport)
+#  ifdef GDAL_EXPORTS
+#    define CPL_DLL     __declspec(dllexport)
+#  else
+#    define CPL_DLL     __declspec(dllimport)
+#  endif
 #  define CPL_INTERNAL
 #else
 #  if defined(USE_GCC_VISIBILITY_FLAG)

```

And define `GDAL_EXPORTS` when compiling gdal source files if shared in NMake files.

**Comment by rouault** [comment]
Can you provide a pull request implementing that change ?

**Comment by SpaceIm** [comment]
Sure, first I need to look at NMake files to see where `GDAL_EXPORTS` should be defined.
