### ISSUE TITLE
COG Quality - Resampling with reprojecton and overview creation

### ISSUE THREAD

**Issue by blacha** [OSGeo/gdal#2671]
## Expected behavior and actual behavior.

We would like the COGS generated by GDAL to have the highest possible quality, we have noticed some loss of quality when using different reprojection methods when reprojecting and creating overviews.

## Steps to reproduce the problem.

We are creating COGs using a command very similar to: where we reproject imagery from EPSG:2193 to EPSG:3857 and create a GoogleMapsCompatible COG

```
COMPRESS=webp
BLOCKSIZE=256

for RESAMPLE in cubic lanczos bilinear
do
gdal_translate \
    -of COG \
    -co COMPRESS=$COMPRESS\
    -co NUM_THREADS=ALL_CPUS \
    -co BIGTIFF=YES \
    -co TILING_SCHEME=GoogleMapsCompatible \
    --config BIGTIFF_OVERVIEW YES \
    -co ALIGNED_LEVELS=1 \
    -co SPARSE_OK=TRUE \
    -co ADD_ALPHA=YES \
    -co BLOCKSIZE=$BLOCKSIZE \
    -co RESAMPLING=$RESAMPLE \
    -co QUALITY=90 \
    -co ZOOM_LEVEL_STRATEGY=UPPER \
    $PWD/$TIF_FOLDER/.vrt $PWD/$TIF_FOLDER.$COMPRESS.google.r_$RESAMPLE.bs_$BLOCKSIZE.aligned.cog.tif
done
```

When creating COGs using the different resampling methods the output quality differs alot.

Here are some overviews created using some of the different resampling methods:

### Lanczos

Lanczos provides quite a nice and crisp output

![i6 lanczos](https://user-images.githubusercontent.com/1082761/84453615-652cab00-acac-11ea-974d-28613f509a04.png)

### Cubic

Cubic creates weird artifacts around the edges

![i6 cubic](https://user-images.githubusercontent.com/1082761/84453629-707fd680-acac-11ea-817b-9f2feaafbe19.png)

### Bilinear

looks quite blury

![i6 bilinear](https://user-images.githubusercontent.com/1082761/84453640-7970a800-acac-11ea-92ae-23679385fdbf.png)

Using lanczos looks best for our overview creation, however when we use lanczos for the cog creation we start getting jagged lines inside the high resolution images

Here are some higher resolution aerial imagery image 0 with different resampling methods, these are tiles taken directly from a tiff and converted to png.

### Lanczos

Creates a jaggeredness, look at the street markings and the edges of the buildings

![005_006_0_lanczos](https://user-images.githubusercontent.com/1082761/84453685-9907d080-acac-11ea-9325-47c2a94c58a0.png)

### Bilinear

Seems to create quite a nice image

![005_006_0_bilinear](https://user-images.githubusercontent.com/1082761/84453697-a1600b80-acac-11ea-8975-c5adc0ef5893.png)

For our use case reprojection seems to be best done as bilinear, where as Overview creation seems to be best done as lanczos.

What options do we have to use create COGs using different resampling methods for reprojection vs overview creation?

## Operating system

Ubuntu 20.04 

## GDAL version and provenance

GDAL Nightly docker container

**Comment by palmerj** [comment]
To me it looks like those bilinear rendered overviews are actually nearest neighbour. Also gdal overview generation doesn't support resampling using bilinear methods.

**Comment by rouault** [comment]
> Also gdal overview generation doesn't support resampling using bilinear methods.

It does. Was just documentation lagging behind

**Comment by rouault** [comment]
@blacha  Would https://github.com/rouault/gdal/commit/5d7a84a2e206b529bbed0d570be142876929652f help ?

**Comment by palmerj** [comment]
> It does. Was just documentation lagging behind

Thanks Even!

**Comment by blacha** [comment]
> @blacha  Would https://github.com/rouault/gdal/commit/5d7a84a2e206b529bbed0d570be142876929652f help ?

Thanks, I'll build some cogs with that and let you know!

**Comment by palmerj** [comment]
@rouault I did a little further testing. If you use compression for the overviews, it seems the quality to gets marginally worse. For example, I generated a COG using WebP, then extracted a specific lower-res overview, cleaned the cog of overviews, and generated an overview from the nominal data.  Or is this is not caused by the compression, because the process of making the next overview using the previous overview degrades the result, rather than generating each overview from the nominal resolution data?

```
COMPRESS=WebP
BLOCKSIZE=256
RESAMPLE=bilinear

# generate COG. Overviews are 8704x7808, 4352x3904, 1740x1561, 870x780, 435x390, 217x195
gdal_translate -of COG \
    -co COMPRESS=$COMPRESS \
    -co NUM_THREADS=ALL_CPUS \
    -co BIGTIFF=YES \
    -co TILING_SCHEME=NZTM2000 \
    --config BIGTIFF_OVERVIEW YES \
    -co ALIGNED_LEVELS=1 \
    -co SPARSE_OK=TRUE \
    -co ADD_ALPHA=YES \
    -co BLOCKSIZE=$BLOCKSIZE \
    -co RESAMPLING=$RESAMPLE \
    -co QUALITY=90 \
    -co ZOOM_LEVEL_STRATEGY=UPPER \
    new_zealand_sentinel_2018-19_10m.vrt \
    cog.tif

# extract generated overview
gdal_translate -outsize 435 390 cog.tif cog_4.tif

# clean overviews and generate same overview resolution with 
gdaladdo -clean cog.tif
gdal_translate -outsize 435 390 -r $RESAMPLE cog.tif cog_435x390.tif
```
[overviews.zip](https://github.com/OSGeo/gdal/files/4776013/overviews.zip)

I also noticed the extracted COG overview is missing edge pixels vs the manually generated overview resolution.

**Comment by rouault** [comment]
> If you use compression for the overviews, it seems the quality to gets marginally worse.

No, I don't think that's the reason. The COG driver uses ZSTD when generating the temporary overview file. It just uses the final compression when translating the full resolution and temporary overviews

> Or is this is not caused by the compression, because the process of making the next overview using the previous overview degrades the result, rather than generating each overview from the nominal resolution data?

That's exactly that. For efficiency (CPU and memory usage), we create each pyramid level from the one that just got generated. When using rasters with integer data types, successive rounding to integers probably accumulate more error than if this was done on floating point data.

> I also noticed the extracted COG overview is missing edge pixels vs the manually generated overview resolution.

Very possible. The way transitions from transparent to valid pixels is dealt in the overview generation process tends to favor transparency. So when repeating the process several times, transparent pixels will progressively win over valid ones, whereas when doing the computation one single time, you won't get that accumulation.

**Comment by palmerj** [comment]
Thanks Even on both counts.

**Comment by blacha** [comment]
@rouault Thanks this seems to be working really well!

I have rendered a few COGs using 

```
WARP_RESAMPLING=bilinear
OVERVIEW_RESAMPLING=lanczos
```

And compared it agains `RESAMPLING=lanczos` & `RESAMPLING=bilinear`

Here is a Overview (image#5 in a COG) 

![wlg-rs_bilinear i4](https://user-images.githubusercontent.com/1082761/84608217-758b9280-af05-11ea-9edc-e93f522b58da.png)
![wlg-rs_lanczos i4](https://user-images.githubusercontent.com/1082761/84608222-791f1980-af05-11ea-8fcb-6cea96cd5d1d.png)
![wlg-wr_bilinear-or_lanczos i4](https://user-images.githubusercontent.com/1082761/84608224-7ae8dd00-af05-11ea-8db5-65197e6c7902.png)

Which shows that the blilinear was really blury but the combined resampling looks good!

And here is a tile from the base image

![wlg-rs_bilinear i0](https://user-images.githubusercontent.com/1082761/84608337-15492080-af06-11ea-9ebf-9c1a6694f852.png)
![wlg-rs_lanczos i0](https://user-images.githubusercontent.com/1082761/84608339-18441100-af06-11ea-8790-32c60af140a3.png)
![wlg-wr_bilinear-or_lanczos i0](https://user-images.githubusercontent.com/1082761/84608345-1b3f0180-af06-11ea-8633-829135d5ebad.png)

Where Lanczos was quite jaggeder but now looks fine

And here is overview level 1, which looks very crisp and does not have the jaggedness to it
![wr_bilinear or_lanczos i1](https://user-images.githubusercontent.com/1082761/84608625-63aaef00-af07-11ea-97a8-c3d1ae1d5180.png)

**Comment by reyemtm** [comment]
@blacha can you share your final gdal_translate command to achieve the above results?
