### ISSUE TITLE
VS 2019 compilation

### ISSUE THREAD

**Issue by chacha21** [OSGeo/gdal#2676]
Hello,

The scripts to compile GDAL are up-to-date for Visual Studio 2017, they could be adapted to support VS 2019 as well.

In generate_vcxproj.bat, one could add the if "%_vcver_%"=="16.0"  case to match the value 16 for the <Visual C++ version> script argument

In nmake.opt, MSVC_VER should be tested against 1910 and 1920 to adapt the PLATFORM_TOOLSET_DIR to 141 or 142

**Comment by rouault** [comment]
Feel free to submit a pull request implementing this
