### ISSUE TITLE
VFR: Property name typo in gfs

### ISSUE THREAD

**Issue by tlinhart** [OSGeo/gdal#2682]
## Expected behavior and actual behavior.

I believe there is a typo in `data/ruian_vf_ob_v1.gfs` and `data/ruian_vf_v1.gfs`. There is a property with name `BonitovaneDilRizeniId` while the name should read `BonitovanyDilRizeniId`.

## GDAL version and provenance

master

**Comment by rouault** [comment]
CC @landam
