### ISSUE TITLE
Kernel restarts when doing method chaining 

### ISSUE THREAD

**Issue by jnsplt** [OSGeo/gdal#2684]
## Expected behavior and actual behavior.

Opening a file AND reading a raster band as array, all in one line without assigning the gdal dataset to a variable, crashes the python kernel.

**Error message in Jupyter lab:** "Kernel Restarting
The kernel for [...].ipynb appears to have died. It will restart automatically."

It actually should just return the raster as an array. This works when assigning the openend gdal dataset to a variable first.

## Steps to reproduce the problem.

I can't provide you a file, since I got them from [Climate Data Store (ERA5)](https://cds.climate.copernicus.eu/cdsapp#!/dataset/reanalysis-era5-land?tab=form) and [LPDAAC (NASA MODIS)](https://e4ftl01.cr.usgs.gov/MOLT/MOD11A1.006/). The error appeared for both files (.grib and .hdf).

```
import gdal
fpath = /path/to/file.hdf  
array = gdal.Open(fpath).GetRasterBand(1).ReadAsArray()
```

However this works:

```
import gdal
fpath = /path/to/file.hdf
gds = gdal.Open(fpath)
aray = gds.GetRasterBand(1).ReadAsArray()
```

**note:** If you get a MODIS HDF file as linked above to reproduce this, make sure to get the path to one of the subdatasets first and use that as `fpath`.

## Operating system

Ubuntu 18.04.4 LTS 64 bit

## GDAL version and provenance

gdal 3.0.4 from conda-forge

**Comment by rouault** [comment]
yes, this is historic behaviour detailed in https://gdal.org/api/python_gotchas.html

**Comment by jnsplt** [comment]
Ah, interesting! Thanks for the quick answer, @rouault
