### ISSUE TITLE
gdal 3.1.0 fails to build docs/man on breathe extension error

### ISSUE THREAD

**Issue by ggardet** [OSGeo/gdal#2690]
## Expected behavior and actual behavior.
When building docs/man on openSUSE Leap 15.1 (or upcoming 15.2), I get the following error:
```
[  183s] Warning, treated as error:
[  183s] the breathe extension does not declare if it is safe for parallel reading, assuming it isn't - please ask the extension author to check and make it explicit
```
but it should pass as on openSUSE Tumbleweed (rolling release).

## Steps to reproduce the problem.
Build 3.1.0 with patch from https://github.com/OSGeo/gdal/issues/2673 for openSUSE Leap.

## Operating system
openSUSE Leap 15.1 and 15.2.

## GDAL version and provenance
3.1.0

**Comment by rouault** [comment]
I'd suggest you patch doc/Makefile in GDAL to remove the -W flag from the SPHINXOPTS line, to avoid warnings to be treated as errors
```
SPHINXOPTS    = --keep-going -j auto
```

**Comment by ggardet** [comment]
It is not enough to remove `-W`. It prints a number of warnings and stop at:
````
[  325s] Sphinx error:
[  325s] master file /home/abuild/rpmbuild/BUILD/gdal-3.1.0/doc/source/contents.rst not found
```

**Comment by rouault** [comment]
> contents.rst not found

Weird, what is the Sphinx version you use ?

**Comment by ggardet** [comment]
This happen with sphinx `1.7.6` and I needed to remove the `--keep-going` flag, as it is not supported.

**Comment by rouault** [comment]
> sphinx `1.7.6`

this is likely too old. The oldest we've tried is 2.0.
