### ISSUE TITLE
Windows 10 gdal2tiles not executing

### ISSUE THREAD

**Issue by ev0065** [OSGeo/gdal#2693]
## Expected behavior and actual behavior.

I expect to execute `gdal2tiles` and have a new folder with the geotiff file as tiles. When I run the command `gdal2tiles.py geo.tif outFolder`, I am prompted to select how I want to open the .py file and nothing runs from the command prompt. Please find more detailed information below.

## Steps to reproduce the problem.

1. Install the [binaries](http://www.gisinternals.com/query.html?content=filelist&file=release-1911-x64-gdal-mapserver.zip). I am working on Windows 10 (64 bit) and I already have Python 3.7 installed. Here are the specific binaries I installed: `GDAL-3.1.0.win-amd64-py3.7.msi` and `gdal-300-1911-x64-core.msi`.
2. Edit the environment variables (following [this post](https://gis.stackexchange.com/questions/44958/gdal-importerror-in-python-on-windows/143140#143140)): 
-> Add `C:\Program Files\GDAL` to path 
-> Add variable `GDAL_DATA` as `C:\Program Files\GDAL\gdal-data`
-> Add variable `GDAL_DRIVER_PATH` as `C:\Program Files\GDAL\gdalplugins`
3. Open the command prompt/terminal
4. Navigate to where the geotiff file is stored.
5. Run the command `gdal2tiles.py geo.tif outFolder`. In this case, we did not provide any options. But I need gdal 3.1 because I need the `--xyz` and `--tilesize=X` options, which will be provided during regular runs.

Expected output: The folder `outFolder` created and storing tiles in OSM format (e.g. z/x/y).
Actual output: Quite literally, nothing. The file is not executed. I do not believe that it is a path issue, since everything is added to my path. I was wondering if it may be caused because I have gdal 3.0 core and gdal 3.1 binaries (which I need).

Please let me know what could be causing this issue, or if I can help debug it further. I looked on many other forums but could not find any information. Thanks!

## Operating system

Windows 10

## GDAL version and provenance

Installed from Windows [binaries](http://www.gisinternals.com/query.html?content=filelist&file=release-1911-x64-gdal-mapserver.zip).

Binaries: `GDAL-3.1.0.win-amd64-py3.7.msi` 
Core: `gdal-300-1911-x64-core.msi`.

**Comment by rouault** [comment]
@szekerest This might be a gisinternals issue. In http://www.gisinternals.com/query.html?content=filelist&file=release-1911-x64-gdal-mapserver.zip, I see gdal-300-XXXX files, and in particularly gdal-300-1911-x64-core.msi which dates back to 2020-04-27 . Looks like there might be mixes of versions

@evan0065 You could probably use http://download.gisinternals.com/sdk/downloads/release-1911-x64-gdal-mapserver.zip which should contain both the GDAL lib/binaries and python bindings

**Comment by evan0065** [comment]
@rouault Hmm I'd be interested to see if the versions are mixed up. I had my doubts when downloading gdal core for version 3.0 and not 3.1, but wasn't sure if that would cause issues. 

Thanks for the new binaries and python bindings. Should I update my path and environment variables to point to these? E.g. I would add `C:\path\new-gdal\bin` to the path and the variables now point to `C:\path\new-gdal\bin` for `GDAL_DRIVER_PATH` and `C:\path\new-gdal\bin\gdal-data` for `GDAL_DATA`

**Comment by rouault** [comment]
there's a SDKShell.bat file to run to set env variables

**Comment by evan0065** [comment]
@rouault Good catch, I missed that one. 

On the bright side, I got a new error with this - which means that it is actually running now! Would you mind taking a look at it and seeing what could be happening? 

```

C:\Users\...\path>gdal2tiles.py --xyz --tilesize=256 geo.tif outother
Traceback (most recent call last):
  File "C:\Users\...\AppData\Local\Programs\Python\Python37\lib\site-packages\osgeo\__init__.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Users\...\AppData\Local\Programs\Python\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 670, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 583, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1043, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\...\AppData\Local\Programs\Python\Python37\Scripts\gdal2tiles.py", line 53, in <module>
    from osgeo import gdal
  File "C:\Users\...\AppData\Local\Programs\Python\Python37\lib\site-packages\osgeo\__init__.py", line 32, in <module>
    _gdal = swig_import_helper()
  File "C:\Users\...\AppData\Local\Programs\Python\Python37\lib\site-packages\osgeo\__init__.py", line 31, in swig_import_helper
    return importlib.import_module('_gdal')
  File "C:\Users\...\AppData\Local\Programs\Python\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_gdal'

C:\Users\...\path>
```

**Comment by rouault** [comment]
> Would you mind taking a look at it and seeing what could be happening?

Did you run SDKShell.bat ?

**Comment by evan0065** [comment]
Yes - I ran it and it outputted the directory twice and said something along of the lines of "setting environment for GDAL"

**Comment by rouault** [comment]
the fact that it emits
> "C:\Users\...\AppData\Local\Programs\Python\Python37\lib\site-packages\osgeo\__init__.py
tends to show you're not running the Python modules from the .zip which is in the bin/gdal/python subdirectory.
Anyway this doesn't sound like a upstream issue, so I'm closing it. You could perhaps ask help on other forums.

**Comment by ev0065** [comment]
Fair enough. Thanks for the binaries and the zip file, I'll try to play around with things and see if I can get it to work.

**Comment by szekerest** [comment]
@ev0065  Did you also tried to include C:\Program Files\GDAL in the PATH environment variable? Also make sure to use the matching x86/x64 version of the msi packages with your Python installation.

**Comment by ev0065** [comment]
@szekerest Yes, that was previously in the path. I decided to delete everything off my machine and start from scratch... I installed the same files I mentioned in the description above. I have Python 3.7 64bit, so I installed `GDAL-3.1.0.win-amd64-py3.7.msi` for the bindings. 

My PATH (for system) contains C:\Program Files\GDAL. My GDAL_DATA  and GDAL_DRIVER_PATH are updated to point to their folders in C:\Program Files\GDAL. Now, I'm still getting this error: 

```
C:\Users\...>gdal2tiles.py
Traceback (most recent call last):
  File "C:\Users\...\AppData\Local\Programs\Python\Python37\lib\site-packages\osgeo\__init__.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Users\...\AppData\Local\Programs\Python\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 670, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 583, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1043, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\GDAL\gdal2tiles.py", line 53, in <module>
    from osgeo import gdal
  File "C:\Users\...\AppData\Local\Programs\Python\Python37\lib\site-packages\osgeo\__init__.py", line 32, in <module>
    _gdal = swig_import_helper()
  File "C:\Users\...\AppData\Local\Programs\Python\Python37\lib\site-packages\osgeo\__init__.py", line 31, in swig_import_helper
    return importlib.import_module('_gdal')
  File "C:\Users\...\AppData\Local\Programs\Python\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_gdal'
```

However, I run this and it works: 
```
C:\Users\...>gdalinfo geo.tif
Driver: GTiff/GeoTIFF
Files: geo.tif
Size is 21600, 10800

--- MORE INFORMATION ---
```

I honestly don't know why it's caused, but it is extremely frustrating... I'm looking in my `Python37/Scripts` directory and I see many gdal python files, including gdal2tiles.py. 

Unfortunately, the zip file that @rouault provided did not end up fixing anything. I had a PYTHONPATH environment variable before, but I don't know where to point it to now. I would really appreciate any help fixing this issue. Thank you

**Comment by ev0065** [comment]
@szekerest This is super weird. I deleted python bindings for gdal 3.1 and installed them for gdal 3.0. Here is what I get now: 
```
C:\Users\...>gdal2tiles.py geo.tif out
Usage: gdal2tiles.py [options] input_file [output]

gdal2tiles.py: error: You need to specify at least an input file as argument to the script
```

Any idea why???

**Comment by szekerest** [comment]
@ev0065 You should probably use process monitor to see the expected location of the dlls when running python.exe, and check if a dll couldn't be loaded actually.
https://docs.microsoft.com/en-us/sysinternals/downloads/procmon

**Comment by ev0065** [comment]
@szekerest Thanks, that's a good idea. I used the process monitor and found that it was looking for `gdal301.dll` in many directories, including `C:\Program Files\GDAL`. I see `gdal300.dll` located in that directory, but no `gdal301.dll` in there or in gdalplugins. What does that mean?

**Comment by ev0065** [comment]
@szekerest I uninstalled basically everything and installed python 32 bit along with gdal 32 bit. I am still getting the error that it is looking for gdal301.dll, which I cannot find anywhere either. This is the only "Name not found" error from the process monitor, so it must be related. I believe that this is an issue with gdal 3.1. I may open a new issue so that we can look at it with others, if you agree.
