### ISSUE TITLE
gdal2tiles.py clipping tiles with rotated world file

### ISSUE THREAD

**Issue by jakerye** [OSGeo/gdal#2694]
## Expected behavior and actual behavior.

When generating tiles with a world file that includes rotation (e.g. 45 deg), the tiles seem to get cropped to the original image area instead of the rotated image area. See below

[screenshot.png](https://drive.google.com/file/d/13KX53nPAdnHlDB29y3g2YztpCbnHsdZD/view?usp=sharing)

## Steps to reproduce the problem.

```
export GDAL_ALLOW_LARGE_LIBJPEG_MEM_ALLOC=YES
gdal2tiles.py ~/Downloads/example.png ~/Downloads/example-tiles zoom 16-21 -r lanczos -a 0 -s EPSG:4326 --processes 4
```
[example.png](https://drive.google.com/file/d/1puAui8ynOt7d8wLSFxpgwufOcEFNMtJo/view?usp=sharing)
[example.pgw](https://drive.google.com/file/d/1dFbKHWUG__CgYHnOoYb21kXdqGqFSLFE/view?usp=sharing)

## Operating system

macOS Catalina v10.15.5

## GDAL version and provenance

GDAL v3.0.4 from conda
Python v3.7.7

**Comment by jratike80** [comment]
What if you remove the rotation by running the image through gdalwarp, is the result correct then?

**Comment by jakerye** [comment]
Ah yes that fixes is, thank you!

For any future references, the updated commands are:

```
export GDAL_ALLOW_LARGE_LIBJPEG_MEM_ALLOC=YES
gdalwarp -s_srs EPSG:4326 -t_srs EPSG:4326 -r lanczos example.png example.tif
gdal2tiles.py example.tif example-tiles zoom 16-21 -r lanczos -a 0 -s EPSG:4326 --processes 4
```

**Comment by jratike80** [comment]
Well, I would call it only as a workaround. 
You can also try if you could use .vrt file as an output for gdalwarp and so avoid writing a material tiff file.

**Comment by rouault** [comment]
Re-opening as it indeed sounds as an issue that would need to receive a proper fix

**Comment by jakerye** [comment]
Turns out this was a ui rendering bug and the gdal generation worked fine. Thanks for the support though!
