### ISSUE TITLE
Python DEMProcessing 'color-relief' doesn't follow color ramps exactly

### ISSUE THREAD

**Issue by erobeck** [OSGeo/gdal#2702]
## Expected behavior and actual behavior.

Using a "pseudo-quantile" color ramp (with very small gaps between bands of equal color -- see attached), the result of a Python DEMProcessing 'color-relief' command will be a raster with discrete color pixels corresponding to those in the color ramp bands. 

This process works for gdaldem 'color-relief' commands, but not with the Python equivalents. Using gdaldem, for example, this command generates Image 1 below:

`gdaldem color-relief "C:\dem\source\SRTM_aspect_degrees.tif" "C:\dem\code\aspect_ramp_quantile.txt" "C:\dem\output\SRTM_aspect_color.tif"`

The image is identical to Image 2, produced using a "nearest" color ramp with midpoint cardinal and inter-cardinal directions and option '-nearest_color_entry':

`gdaldem color-relief "C:\dem\source\SRTM_aspect_degrees.tif" "C:\dem\code\aspect_ramp_nearest.txt" "C:\dem\output\SRTM_degrees_color.tif" -nearest_color_entry`

**1. gdaldem with aspect_ramp_quantile.txt**
![gdaldem_quantile](https://user-images.githubusercontent.com/39314399/85049278-14a8c800-b15a-11ea-88b6-6ab61cff33cc.png)

**2. gdaldem with aspect_ramp_nearest.txt (uses -nearest_color_entry)**
![gdaldem_nearest](https://user-images.githubusercontent.com/39314399/85049291-196d7c00-b15a-11ea-8ce8-624a0d5f0aed.png)

## Steps to reproduce the problem.

The same product is not generated by the Python API. Because a "nearest_color_entry" option isn't available, I used the quantile color map to create the aspect color map in Image 3 as follows:

```
    gdal.DEMProcessing(aspect_degrees_file, dem, 'aspect', computeEdges=True)
    gdal.DEMProcessing(aspect_color_file, aspect_degrees_file, 'color-relief', colorFilename="aspect_ramp_quantile.txt"
, computeEdges=True)
```

The problem is some interpolation or anti-aliasing occurs that is not in the gdaldem output. The resulting image is not quantile.

However, the blurring isn't as severe as one generated from the Python command using a "continuous" color ramp (see Image 4). So some color banding occurs, but it is not as tight as the 0.00001 degree gaps would suggest.

**3. GDAL Python API with aspect_ramp_quantile.txt**
![gdal_python_quantile](https://user-images.githubusercontent.com/39314399/85050198-5c7c1f00-b15b-11ea-8e16-b95a6e682256.png)

**4. GDAL Python with aspect_ramp_continuous.txt**
![gdal_python_continuous](https://user-images.githubusercontent.com/39314399/85050238-6867e100-b15b-11ea-9fab-48a6792dbd1d.png)

## Operating system

Windows 10 Home, version 2004, OS build 19041.329

## GDAL version and provenance

3.0.4-2

[aspect_ramp_quantile.txt](https://github.com/OSGeo/gdal/files/4799942/aspect_ramp_quantile.txt)
[aspect_ramp_nearest.txt](https://github.com/OSGeo/gdal/files/4799957/aspect_ramp_nearest.txt)
[aspect_ramp_continuous.txt](https://github.com/OSGeo/gdal/files/4799962/aspect_ramp_continuous.txt)

**Comment by rouault** [comment]
> because a "nearest_color_entry" option isn't available

It is not directly exposed, but as all other command line utilities exposed in Python, you can specify the command line switches in a options argument. So if you add ``options='-nearest_color_entry'``, you get the same result as the binary

https://github.com/OSGeo/gdal/pull/2688 will bring more synthaxic sugar

**Comment by erobeck** [comment]
Even, thanks for your comment. The 'options='nearest_color_entry' works and I'll use it going forward. The main source of my problem (that I should have caught sooner) is that the script performed an intermediate Warp reprojection from UTM to geographic using GRA_Bilinear, which was responsible for the "anti-aliased" pixels. Changing the resampling algorithm to GRA_NearestNeighbour retained the discrete values. Lesson learned.

**Comment by rouault** [comment]
Fixed per https://github.com/OSGeo/gdal/pull/2688
