### ISSUE TITLE
ogr2ogr -sql @filename doesn't replace variable with value

### ISSUE THREAD

**Issue by brocksm** [OSGeo/gdal#2704]
## Expected behavior and actual behavior.

I expected ogr2ogr to evaluate the variables in my external sql file. However, it treats them as literals.

## Steps to reproduce the problem.

writing the sql query directly in terminal works as intended:
```
STOP_NAME=Alewife
ogr2ogr \
-f geojson \
/vsistdout/ \
stops.csv \
-dialect sqlite \
-sql "SELECT * FROM stops WHERE stop_name = '$STOP_NAME'"
```

feeding the sql query from an external file doesn't evaluate the variable:
```
STOP_NAME=Alewife
ogr2ogr \
-f geojson \
/vsistdout/ \
stops.csv \
-dialect sqlite \
-sql @stop_geo.txt
```
[stop_pre.txt](https://github.com/OSGeo/gdal/files/4801802/stop_pre.txt)

## Operating system

MacOS 10.13.6

## GDAL version and provenance

2.4.4

**Comment by rouault** [comment]
Substitution of environment variables is not intended in the current implementation. This is the job of the shell and it thus would require a specific behaviour to implement if we wanted to extend it to the -sql @filename syntax

**Comment by brocksm** [comment]
Thanks @rouault. Personally I would find this quite useful as default behavior, if possible: for complex queries that require the use of variable expansion, I find it much easier/maintainable to keep the queries in separate files from the rest of the shell script, and pass them into ogr via the @ syntax.

**Comment by rouault** [comment]
Closing. I don't think we want to deal with this. There are external ways to GDAL of accomplishing this
