### ISSUE TITLE
Python GDAL TranslateOptions Does Not Handle metadataOptions Correctly

### ISSUE THREAD

**Issue by carpenlc** [OSGeo/gdal#2709]
## Expected behavior and actual behavior.

While using the python interface to set the GTRasterTypeGeoKey GeoTIFF metadata tag as described in the post at:  https://gdal.org/development/rfc/rfc33_gtiff_pixelispoint.html we found that the <code>metadataOptions</code> parameter of <code>TranslateOptions</code> function is not being parsed correctly.

## Steps to reproduce the problem.
Here is a simplified version of the function we're attempting to run:
```
    def translate(self, dem) -> gdal.Dataset:
        translate_options = gdal.TranslateOptions(metadataOptions='AREA_OR_POINT=Point',
                                                  format='MEM')
        return gdal.Translate(" ", dem, options=translate_options)
```
In the <code>TranslateOptions</code> function at line 412 in <code>osgeo/gdal.py</code> the code loops through each character contained in the value of the <code>metadataOptions</code> parameter and adds a separate <code>-mo</code> option for each character.  In the above example the <code>metadataOptions</code> is parsed as:
```
['-mo', 'A', '-mo', 'R', '-mo', 'E', '-mo', 'A', '-mo', '_', '-mo', 'O', '-mo', 'R', '-mo', '_', '-mo', 'P', '-mo', 'O', '-mo', 'I', '-mo', 'N', '-mo', 'T', '-mo', '=', '-mo', 'P', '-mo', 'o', '-mo', 'i', '-mo', 'n', '-mo', 't']
```
It should be:
```
['-mo', 'AREA_OR_POINT=Point']
```
## Workaround
You can work around the issue by leveraging the string <code>options</code> parameter as follows: 
```
    def translate(self, dem) -> gdal.Dataset:
        translate_options = gdal.TranslateOptions(options='-mo AREA_OR_POINT=Point',
                                                  format='MEM')
        return gdal.Translate(" ", dem, options=translate_options)
```
## Operating system

Ubuntu 18.04 64 bit

## GDAL version and provenance

GDAL 3.0.4 (Anaconda)

**Comment by underchemist** [comment]
Don't you just need to specify `metadataOptions=["AREA_OR_POINT=Point"]`? The `metadataOptions` keyword argument expects an iterator/sequence like object, which a string also happens to be which is why you get every char as a metadata option.

**Comment by carpenlc** [comment]
That does indeed work as well.  I should have thought of that before writing the issue!

**Comment by rouault** [comment]
> Don't you just need to specify `metadataOptions=["AREA_OR_POINT=Point"]`?

yes, that's the nominal usage. However we are lenient in other places, so I'm just adding that capability
