### ISSUE TITLE
Build fails on macports no member named 'ImageTypeNotSupported' in 'charls::jpegls_errc'

### ISSUE THREAD

**Issue by nasyxx** [OSGeo/gdal#2710]
## Expected behavior and actual behavior.

**Expected**: With Macports, `port install gdal` should build GDAL from source, and create library files.
**Actual**: It built failed.

## Steps to reproduce the problem.

1. On macOS, install macports with custom port dir.  Like "/Users/Nasy/.macports/"
2. `sudo port install gdal`

## Operating system

macOS 10.15.5 (19F101)

## GDAL version and provenance

GitHub OSGeo/gdal v3.1.0 tag

## Error

Full log here: https://gist.github.com/nasyxx/8929dc9bf2990b596fa52ca1491a177a

Sample here:

```
:info:build /bin/sh /Users/Nasy/.macports/var/macports/build/_Users_Nasy_.macports_macports-ports_gis_gdal/gdal/work/gdal-3.1.0/gdal/libtool --mode=compile --silent --tag=CC /usr/bin/clang -c -Ilibjpeg12 -DDEFAULT_MAX_MEM=500000000L -I../mem -DJPEG_DUAL_MODE_8_12 -Ilibjpeg -DDEFAULT_MAX_MEM=500000000L  -DGNM_ENABLED -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -I/Users/Nasy/.macports/var/macports/build/_Users_Nasy_.macports_macports-ports_gis_gdal/gdal/work/gdal-3.1.0/gdal/port -I/Users/Nasy/.macports/include/openjpeg-2.3 -I/Users/Nasy/.macports/include/include  -DGDAL_COMPILATION -I/Users/Nasy/.macports/include  -DENABLE_LIBJPEG_NO_RETURN -DHAVE_AVX_AT_COMPILE_TIME -DHAVE_SSSE3_AT_COMPILE_TIME -DHAVE_SSE_AT_COMPILE_TIME -pipe -Os -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -arch x86_64 -flto  -Wall -Wdeclaration-after-statement -Wextra -Winit-self -Wunused-parameter -Wmissing-prototypes -Wmissing-declarations -Wformat -Werror=format-security -Wno-format-nonliteral -Wshorten-64-to-32 -Wshadow -Werror=vla -Wdeclaration-after-statement -Wdate-time -Wnull-dereference -Wcomma -Wfloat-conversion -Wdocumentation -Wno-documentation-deprecated-sync  libjpeg12/jcinit12.c -o ../o/jcinit12.lo
:info:build jpeglsdataset.cpp:126:35: error: no member named 'ImageTypeNotSupported' in 'charls::jpegls_errc'
:info:build         case CharlsApiResultType::ImageTypeNotSupported: return "ImageTypeNotSupported";
:info:build              ~~~~~~~~~~~~~~~~~~~~~^
:info:build jpeglsdataset.cpp:127:35: error: no member named 'UnsupportedBitDepthForTransform' in 'charls::jpegls_errc'; did you mean 'UnsupportedColorTransform'?
:info:build         case CharlsApiResultType::UnsupportedBitDepthForTransform: return "UnsupportedBitDepthForTransform";
:info:build              ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
:info:build                                   UnsupportedColorTransform
:info:build /Users/Nasy/.macports/include/CharLS/public_types.h:360:5: note: 'UnsupportedColorTransform' declared here
:info:build     UnsupportedColorTransform = color_transform_not_supported,
:info:build     ^
:info:build jpeglsdataset.cpp:125:14: error: duplicate case value: 'ParameterValueNotSupported' and 'InvalidCompressedData' both equal '5'
:info:build         case CharlsApiResultType::InvalidCompressedData: return "InvalidCompressedData";
:info:build              ^
:info:build jpeglsdataset.cpp:121:14: note: previous case defined here
:info:build         case CharlsApiResultType::ParameterValueNotSupported: return "ParameterValueNotSupported";
:info:build              ^
:info:build jpeglsdataset.cpp:129:14: error: duplicate case value 'UnsupportedColorTransform'
:info:build         case CharlsApiResultType::UnsupportedColorTransform: return "UnsupportedColorTransform";
:info:build              ^
:info:build jpeglsdataset.cpp:127:14: note: previous case defined here
:info:build         case CharlsApiResultType::UnsupportedBitDepthForTransform: return "UnsupportedBitDepthForTransform";
```

**Comment by rouault** [comment]
Which version of Charls is available on Macports ?

**Comment by nasyxx** [comment]
> Which version of Charls is available on Macports ?

It is 2.1.0

```
> port info Charls
charls @2.1.0 (graphics)
Variants:             (-)debug, (-)universal

Description:          CharLS implements JPEG-LS, a lossless JPEG codec.
--------------
> port installed Charls
The following ports are currently installed:
  charls @2.1.0_0 (active)
```

**Comment by rouault** [comment]
GDAL 3.1 is supposed to support CharLS 2.1, but I see the configure.ac check to differentiale charls 2.0 from 2.1 is based on checking "CharLS/charls.h" (charls 2.0) vs "charls/charls.h" (charls 2.1). Isn't the filesystem on Mac case insensitive for filenames ?

**Comment by nasyxx** [comment]
No, the filesystem isn't case insensitive.

<img width="915" alt="Screen Shot 2020-06-20 at 8 24 37 PM" src="https://user-images.githubusercontent.com/5007613/85214031-1201ca80-b334-11ea-8cc8-b84706c52118.png">

**Comment by nasyxx** [comment]
Does gdal check its version by checking filename?

I deleted the two links, and it succeeded.

<img width="988" alt="Screen Shot 2020-06-20 at 8 29 22 PM" src="https://user-images.githubusercontent.com/5007613/85214090-bbe15700-b334-11ea-8b2e-5b8f94955a58.png">
<img width="1007" alt="Screen Shot 2020-06-20 at 8 47 00 PM" src="https://user-images.githubusercontent.com/5007613/85214341-593d8a80-b337-11ea-9555-d94971248c0e.png">

**Comment by rouault** [comment]
> No, the filesystem isn't case insensitive.

your screenshot proves the contrary. It has created only the first file 'A', and not the second one 'a'

> I deleted the two links, and it succeeded.

Well, then GDAL ./configure failed at detecting charls during the linking test, and hence the build went on without charls support

**Comment by nasyxx** [comment]
> your screenshot proves the contrary. It has created only the first file 'A', and not the second one 'a'
Sorry for my poor English.  I haven't noticed that it is two "no" on this sentence.
