### ISSUE TITLE
GetProjection() crashing Python

### ISSUE THREAD

**Issue by vic1309** [OSGeo/gdal#2716]
Dear developers

I'm trying to plot NSIDC tif data using gdal (please see [code](https://github.com/vic1309/tif_seaice_data/blob/master/seaice_tif_basemap.py) and example [data](https://github.com/vic1309/tif_seaice_data/blob/master/N_197904_concentration_v3.0.tif)) but Python crashes every time it reaches `GetProjection()` (please see the figure attached). I found out that if Basemap is called before `GetProjection()`, Python crashes otherwise it doesn't. Any ideas of what this could be related to? 

![abort](https://user-images.githubusercontent.com/11020112/85332219-d9025b00-b4d7-11ea-8908-a86c7371d3d7.png)

## Expected behavior and actual behavior.

The expected figure is also attached here.
![iceconc_index3](https://user-images.githubusercontent.com/11020112/85332376-267ec800-b4d8-11ea-8899-53e5342bc226.png)

## Steps to reproduce the problem.
Data and code were provided above.

## Operating system

Ubuntu 18.04.4 LTS
Python: 3.7.3 
Ipython: 7.10.1 

## GDAL version and provenance
3.0.4

Cheers

**Comment by rouault** [comment]
Seeing https://github.com/matplotlib/basemap , it depends on pyproj, which may potentially come with a binary wheel with a PROJ version that would be different that the one libgdal would link against.
