### ISSUE TITLE
3.1.0 : VS2019 compilation failed with missing #include <stdexcept> in ogrflatgeobuflayer.cpp

### ISSUE THREAD

**Issue by chacha21** [OSGeo/gdal#2717]
When compiling GDAL 3.1.0 with VS2019 (Version 16.6.2), a missing `#include <stdexcept>` in ogrflatgeobuflayer.cpp prevents proper compilation because of std::runtime_error being not found.

Adding the #include fixes the problem.

**Comment by rouault** [comment]
can you submit a pull request with this fix ?

**Comment by chacha21** [comment]
Just checked; already fixed in current master by commit 35f823b76d0ca00b65129a0505100eb86cb3657a
