### ISSUE TITLE
Fatal Python error: PyThreadState_Get: no current thread

### ISSUE THREAD

**Issue by nikhil003** [OSGeo/gdal#2721]
## Expected behavior and actual behavior.

I have a function to get the projection from a tif file using gdal. I am able to run the function from a usual python script, but when I can call the same function from py.test, I get a Fatal Python error.

## Steps to reproduce the problem.

This is the function to get the projection string from a tif file

```python
def return_proj4(gdal_file):
    >>> out_str = return_proj4("test.tif")
    """
    out = ""
    gdal_dataset = gdal.Open(gdal_file)
    if hasattr(gdal_dataset, "GetSpatialRef"):
        out = gdal_dataset.GetSpatialRef().ExportToProj4()
    else:
        proj = gdal_dataset.GetProjection()
        if len(proj) > 1:
            proj_ref = osr.SpatialReference()
            proj_ref.ImportFromWkt(proj)
            out = proj_ref.ExportToProj4()
    return out
```

```python
@pytest.mark.skipif(not dataset.HAS_GDAL, reason="gdal library is not installed")
def test_gdal(tmpdir):
    filePath = tmpdir.join("gs_test.tif")
    print(filePath.strpath)
    print(os.path.exists(filePath.strpath))
    print(return_proj4(filePath.strpath))
```

When calling from python interpreter

```
>>> 
>>> return_proj4("test_fire.tif")
'+proj=lcc +lat_0=-37 +lon_0=145 +lat_1=-36 +lat_2=-38 +x_0=2500000 +y_0=2500000 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs'
```

However, when I call the same function from py.test

> Fatal Python error: PyThreadState_Get: no current thread
> 
> Current thread 0x00007fa6d7a8c700 (most recent call first):
>   File "/home/gar305/Documents/geostack/miniconda3/lib/python3.7/site-packages/osgeo/gdal.py", line 2084 in GetSpatialRef
>   File "/home/gar305/Documents/geostack/py_build/python/src/geostack/readers/rasterReaders.py", line 95 in return_proj4
>   File "/home/gar305/Documents/geostack/py_build/python/src/geostack/dataset/supported_libs.py", line 44 in inner_func
>   File "/home/gar305/Documents/geostack/py_build/python/src/geostack/readers/test/test_readers.py", line 73 in test_gdal
>   File "/home/gar305/Documents/geostack/miniconda3/lib/python3.7/site-packages/_pytest/python.py", line 167 in pytest_pyfunc_call
>   File "/home/gar305/Documents/geostack/miniconda3/lib/python3.7/site-packages/pluggy/callers.py", line 187 in _multicall
>   File "/home/gar305/Documents/geostack/miniconda3/lib/python3.7/site-packages/pluggy/manager.py", line 86 in <lambda>
>   File "/home/gar305/Documents/geostack/miniconda3/lib/python3.7/site-packages/pluggy/manager.py", line 92 in _hookexec
>   File "/home/gar305/Documents/geostack/miniconda3/lib/python3.7/site-packages/pluggy/hooks.py", line 286 in __call__
>   File "/home/gar305/Documents/geostack/miniconda3/lib/python3.7/site-packages/_pytest/python.py", line 1445 in runtest
>   File "/home/gar305/Documents/geostack/miniconda3/lib/python3.7/site-packages/_pytest/runner.py", line 134 in pytest_runtest_call
>   File "/home/gar305/Documents/geostack/miniconda3/lib/python3.7/site-packages/pluggy/callers.py", line 187 in _multicall
>   File "/home/gar305/Documents/geostack/miniconda3/lib/python3.7/site-packages/pluggy/manager.py", line 86 in <lambda>
>   File "/home/gar305/Documents/geostack/miniconda3/lib/python3.7/site-packages/pluggy/manager.py", line 92 in _hookexec
>   File "/home/gar305/Documents/geostack/miniconda3/lib/python3.7/site-packages/pluggy/hooks.py", line 286 in __call__
>   File "/home/gar305/Documents/geostack/miniconda3/lib/python3.7/site-packages/_pytest/runner.py", line 210 in <lambda>
>   File "/home/gar305/Documents/geostack/miniconda3/lib/python3.7/site-packages/_pytest/runner.py", line 237 in from_call
>   File "/home/gar305/Documents/geostack/miniconda3/lib/python3.7/site-packages/_pytest/runner.py", line 210 in call_runtest_hook
>   File "/home/gar305/Documents/geostack/miniconda3/lib/python3.7/site-packages/_pytest/runner.py", line 185 in call_and_report
>   File "/home/gar305/Documents/geostack/miniconda3/lib/python3.7/site-packages/_pytest/runner.py", line 99 in runtestprotocol
>   File "/home/gar305/Documents/geostack/miniconda3/lib/python3.7/site-packages/_pytest/runner.py", line 84 in pytest_runtest_protocol
>   File "/home/gar305/Documents/geostack/miniconda3/lib/python3.7/site-packages/pluggy/callers.py", line 187 in _multicall
>   File "/home/gar305/Documents/geostack/miniconda3/lib/python3.7/site-packages/pluggy/manager.py", line 86 in <lambda>
>   File "/home/gar305/Documents/geostack/miniconda3/lib/python3.7/site-packages/pluggy/manager.py", line 92 in _hookexec
>   File "/home/gar305/Documents/geostack/miniconda3/lib/python3.7/site-packages/pluggy/hooks.py", line 286 in __call__
>   File "/home/gar305/Documents/geostack/miniconda3/lib/python3.7/site-packages/_pytest/main.py", line 271 in pytest_runtestloop
>   File "/home/gar305/Documents/geostack/miniconda3/lib/python3.7/site-packages/pluggy/callers.py", line 187 in _multicall
>   File "/home/gar305/Documents/geostack/miniconda3/lib/python3.7/site-packages/pluggy/manager.py", line 86 in <lambda>
>   File "/home/gar305/Documents/geostack/miniconda3/lib/python3.7/site-packages/pluggy/manager.py", line 92 in _hookexec
>   File "/home/gar305/Documents/geostack/miniconda3/lib/python3.7/site-packages/pluggy/hooks.py", line 286 in __call__
>   File "/home/gar305/Documents/geostack/miniconda3/lib/python3.7/site-packages/_pytest/main.py", line 247 in _main
>   File "/home/gar305/Documents/geostack/miniconda3/lib/python3.7/site-packages/_pytest/main.py", line 197 in wrap_session
>   File "/home/gar305/Documents/geostack/miniconda3/lib/python3.7/site-packages/_pytest/main.py", line 240 in pytest_cmdline_main
>   File "/home/gar305/Documents/geostack/miniconda3/lib/python3.7/site-packages/pluggy/callers.py", line 187 in _multicall
>   File "/home/gar305/Documents/geostack/miniconda3/lib/python3.7/site-packages/pluggy/manager.py", line 86 in <lambda>
>   File "/home/gar305/Documents/geostack/miniconda3/lib/python3.7/site-packages/pluggy/manager.py", line 92 in _hookexec
>   File "/home/gar305/Documents/geostack/miniconda3/lib/python3.7/site-packages/pluggy/hooks.py", line 286 in __call__
>   File "/home/gar305/Documents/geostack/miniconda3/lib/python3.7/site-packages/_pytest/config/__init__.py", line 93 in main
>   File "/home/gar305/Documents/geostack/miniconda3/bin/py.test", line 11 in <module>

## Operating system

Ubuntu 16.04 64 bit

## GDAL version and provenance

GDAL 3.0.4, released 2020/01/28 from conda-forge

## PYTHON information

> Python 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 21:52:21) 
> [GCC 7.3.0] :: Anaconda, Inc. on linux
> Type "help", "copyright", "credits" or "license" for more information.

**Comment by rouault** [comment]
Looks quite similar to https://github.com/OSGeo/gdal/issues/2716 : is there pyproj involved / a mix of PROJ versions ?

**Comment by rouault** [comment]
closing due to lack of feedback
