### ISSUE TITLE
Fatal error U1077: problems building gdal under Windows using vs2019

### ISSUE THREAD

**Issue by francoamato** [OSGeo/gdal#2731]
Good morning,
I am trying to build gdal under windows, using visual studio 2019 community edition.
After making some changes to nmake.opt to satisfy some dependencies, i can't solve some that give me these errors:
1>...l\gdal\frmts\gtiff\gt_wkt_srs.cpp(1318): error C3861: 'GTIFGetPROJContext': identifier not found
1>...\gdal\frmts\gtiff\gt_wkt_srs.cpp(1348): error C3861: 'GTIFGetPROJContext': identifier not found
1>...\gdal\frmts\gtiff\gt_wkt_srs.cpp(1450): error C3861: 'GTIFGetPROJContext': identifier not found
1>...\gdal\frmts\gtiff\gt_wkt_srs.cpp(1640): error C3861: 'GTIFGetPROJContext': identifier not found
1>...\gdal\frmts\gtiff\geotiff.cpp(10942): error C2065: 'LIBGEOTIFF_WARNING': undeclared identifier
1>...\gdal\frmts\gtiff\geotiff.cpp(10953): error C3861: 'GTIFNewEx': identifier not found
1>...\gdal\frmts\gtiff\geotiff.cpp(10956): error C3861: 'GTIFAttachPROJContext': identifier not found

Environment
Windows 10 Pro
Visual Studio 2019 Community edition

Another question please: how to use https://github.com/OSGeo/gdal/blob/master/appveyor.yml file?

Regards

**Comment by rouault** [comment]
> After making some changes to nmake.opt to satisfy some dependencies

if using external libgeotiff, you need libgeotiff 1.6.0 or later

> Another question please: how to use https://github.com/OSGeo/gdal/blob/master/appveyor.yml file?

you can't use it directly . It's for the appveyor continuous integration service. But you can take inspiration from it

**Comment by francoamato** [comment]
Please can you send the link to download libgeotiff 1.6.0?
Thank you

**Comment by rouault** [comment]
> Please can you send the link to download libgeotiff 1.6.0?

https://github.com/OSGeo/libgeotiff

But I'd suggest to make things simpler  that you just use the internal copy in GDAL (and so let GEOTIFF_INC and GEOTIFF_LIB commented)

**Comment by francoamato** [comment]
I didn't know it was possible, the nmake.opt file doesn't specify it. What other dependencies can I comment on?

**Comment by francoamato** [comment]
I followed your suggestion and I still get the same errors:

\gdal\frmts\gtiff\gt_wkt_srs.cpp(1318): error C3861: 'GTIFGetPROJContext': identifier not found
\gdal\frmts\gtiff\gt_wkt_srs.cpp(1348): error C3861: 'GTIFGetPROJContext': identifier not found
\gdal\frmts\gtiff\gt_wkt_srs.cpp(1450): error C3861: 'GTIFGetPROJContext': identifier not found
\gdal\frmts\gtiff\gt_wkt_srs.cpp(1640): error C3861: 'GTIFGetPROJContext': identifier not found
\gdal\frmts\gtiff\gt_overview.cpp(178): error C2065: 'TIFFTAG_LERC_PARAMETERS': undeclared identifier

This is the settings in nmake.opt
# if using an external libtiff library. Must be libtiff >= 4.0
#TIFF_INC =	-Ic:/warmerda/libtiff/libtiff
#TIFF_LIB =	c:/warmerda/libtiff/libtiff/libtiff_i.lib

# if using an external libgeotiff library
#GEOTIFF_INC =   -Ic:/warmerda/libgeotiff -Ic:/warmerda/libgeotiff/libxtiff
#GEOTIFF_LIB =   C:/warmerda/libgeotiff/geotiff_i.lib

Any suggestion please?

**Comment by jratike80** [comment]
Please use gdal-dev mailing list for asking questions. This is a bug tracker.
