### ISSUE TITLE
ISIS3 in-line default label size

### ISSUE THREAD

**Issue by thareUSGS** [OSGeo/gdal#2741]
## Expected behavior and actual behavior.

I have recently learned when writing and ISIS3 cube (with an in-line label), there is a default behaviour to allocate 65536 bytes no matter how small the label is. If the label doesn't require 65526 bytes, it is padded with nulls.
see: https://astrodiscuss.usgs.gov/t/isis-cube-minimal-header-size/431

To be more in-line with the default behavior for ISIS3 cubes, can the ISIS3 driver be updated to support this default label size . Unfortunately, knowing this might have made the original ISIS3 implementation (for write) easier.

from the post above:
[This is the function](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/isis/src/base/objs/Cube/Cube.cpp#L2373) that writes out the cube label. The default size is set [here](https://github.com/USGS-Astrogeology/ISIS3/blob/dev/isis/src/base/objs/Cube/Cube.cpp#L2046).

Example showing Bytes=65536 :
https://github.com/OSGeo/gdal/blob/master/autotest/gdrivers/data/isis3/isis3_unit_test.cub

Note that ISIS3 detached labels are not padded (only in-line labels).

## Steps to reproduce the problem.

gdal_translate -of ISIS3 in.tif out.cub

## Operating system

Ubuntu 18.02 64 bit

## GDAL version and provenance

3.1.0 version from conda-forge

**Comment by rouault** [comment]
> Unfortunately, knowing this might have made the original ISIS3 implementation (for write) easier.

Not really, as for detached label, or big in-line label, we still have to deal with variable length label, and patching the size.
