### ISSUE TITLE
GDAL 3.1.1 and PROJ 7.1.0 : link error for unresolved CoTaskMemFree

### ISSUE THREAD

**Issue by chacha21** [OSGeo/gdal#2743]
very similar to #2488
(Windows 64b, Visual Studio 2019, x64 compilation)

Solution : I had to add ole32.lib in the PROJ_LIBRARY list of libs

I don't have time for now to check if it is a change in PROJ 7.1.0 vs 7.0.1, but I will update the issue as soon as I have more info.
Just reporting for the moment

**Comment by rouault** [comment]
CoTaskMemFree is new to PROJ 7.1 indeed
