### ISSUE TITLE
ECW: error C1083: Cannot open include file: 'NCSIOStreamOptions.h': No such file or directory

### ISSUE THREAD

**Issue by francoamato** [OSGeo/gdal#2745]
Hi to all,
I would compile GDAL with support to ECW sdk. I downloaed the ERDAS ECW 5.5.0 version from Hexagon web page and I set the paths in nmake.local file but i got the following errors:

fatal error C1083: Cannot open include file: 'NCSIOStreamOptions.h': No such file or directory (compiling source file ecwdataset.cpp)
gdal-3.1.1\gdal\frmts\ecw\gdal_ecw.h(48): fatal error C1083: Cannot open include file: 'NCSIOStreamOptions.h': No such file or directory (compiling source file ecwasyncreader.cpp)
gdal-3.1.1\gdal\frmts\ecw\gdal_ecw.h(48): fatal error C1083: Cannot open include file: 'NCSIOStreamOptions.h': No such file or directory (compiling source file ecwcreatecopy.cpp)
gdal-3.1.1\gdal\frmts\ecw\gdal_ecw.h(48): fatal error C1083: Cannot open include file: 'NCSIOStreamOptions.h': No such file or directory (compiling source file jp2userbox.cpp)

I noticed that such file does not exist in the hexagon include folders.
What should i do?
Regards

**Comment by rouault** [comment]
CC @jbowman-hexagon . I see you've added this include in 0f2d7e956f88679a2ff40c803c61a08c7c099089

**Comment by chacha21** [comment]
Seems to be a SDK missing file.
As a workaround, you can replace #include "NCSIOStreamOptions.h" by
```
#include "NCSIOStream.h"

namespace NCS {
class CIOStream::CIOStreamOptions
{
  public:
    void SetIsRemoteStream(bool) {}
};
}//end namespace NCS
```

**Comment by jbowman-hexagon** [comment]
Turns out this file was shipped with the linux SDK installer but not Windows. We will ship in Windows installer in the 5.5 Update 2 - in perhaps a month or so. For now, NCSIOStreamOptions.h attached to this comment.

[NCSIOStreamOptions.zip](https://github.com/OSGeo/gdal/files/4883190/NCSIOStreamOptions.zip)

**Comment by francoamato** [comment]
Thank you very much

**Comment by kyngchaos** [comment]
This file is missing in the Mac SDK also.

**Comment by jbowman-hexagon** [comment]
> 
> 
> This file is missing in the Mac SDK also.

We will also include the file in the next update for Mac. Thanks for letting us know.

**Comment by rouault** [comment]
closing as not a GDAL bug
