### ISSUE TITLE
Nodata value for GSBG format ignored

### ISSUE THREAD

**Issue by sssangha** [OSGeo/gdal#2759]
## Expected behavior and actual behavior.

When translating or warping a raster to the ```GSBG``` format, the user-specified nodata value is ignored and the output file always has the nodata value ```1.70141000918782799e+38```.

## Steps to reproduce the problem.

Please refer to the attached zip file containing the example input raster for reference and the corresponding example commands listed below.
[example_files.zip](https://github.com/OSGeo/gdal/files/4910136/example_files.zip)

For example:
```
gdal_translate amplitude.rdr updated_amplitude.rdr -of GSBG -a_nodata 0.
gdalinfo updated_amplitude.rdr
....
Band 1 Block=3173x1 Type=Float32, ColorInterp=Undefined
  Min=0.000 Max=754838.062 
  NoData Value=1.70141000918782799e+38
  Metadata:
    description=Amplitude
    grid_mapping=crs
    long_name=amplitude
    NETCDF_VARNAME=amplitude
    standard_name=amplitude
    units=watt
    _FillValue=0
```

Similarly, this using gdalWarp also produces the same result:
```
gdalwarp amplitude.rdr updated_amplitude.rdr -of GSBG -dstnodata 0.
gdalinfo updated_amplitude.rdr
....
Band 1 Block=3173x1 Type=Float32, ColorInterp=Undefined
  Min=0.000 Max=754838.062 
  NoData Value=1.70141000918782799e+38
  Metadata:
    description=Amplitude
    grid_mapping=crs
    long_name=amplitude
    NETCDF_VARNAME=amplitude
    standard_name=amplitude
    units=watt
    _FillValue=0
```

If other formats are specified (e.g. ```ISCE```, ```ENVI```, etc), the nodata value is reported as expected:
```
gdal_translate amplitude.rdr updated_amplitude.rdr -of ISCE -a_nodata 0.
gdalinfo updated_amplitude.rdr
...
Band 1 Block=3173x1 Type=Float32, ColorInterp=Undefined
  Min=0.071 Max=754838.062 
  Minimum=0.071, Maximum=754838.062, Mean=1288.246, StdDev=3061.974
  NoData Value=0
  Metadata:
    description=Amplitude
    grid_mapping=crs
    long_name=amplitude
    NETCDF_VARNAME=amplitude
    standard_name=amplitude
    STATISTICS_MAXIMUM=754838.0625
    STATISTICS_MEAN=1288.2459699851
    STATISTICS_MINIMUM=0.07080165296793
    STATISTICS_STDDEV=3061.9741678996
    units=watt
    _FillValue=0
```

This discrepancy is also replicated in the osgeo GDAL python drivers.

## Operating system

CentOS Linux release 7.2

## GDAL version and provenance

3.0.4 version from conda 4.8.2

**Comment by rouault** [comment]
This is by design of the format. Surfer 8 has a fixed nodata value at 1.701410009187828e+38f, and no provision for setting another value in the header. When writing a GSBG dataset, GDAL remaps the user-specfied input nodata value to 1.701410009187828e+38f
