### ISSUE TITLE
Modified g2_getfld() breaks other programs that use g2clib and link to gdal

### ISSUE THREAD

**Issue by opoplawski** [OSGeo/gdal#2775]
## Expected behavior and actual behavior.

ncl linked with gdal uses gdal's g2_getfld() instead of original g2clib version that it expects.

## Steps to reproduce the problem.

```
Breakpoint 1, g2_getfld (cgrib=cgrib@entry=0x7d2adc0 "GRIB", cgrib_length=cgrib_length@entry=1, ifldnum=ifldnum@entry=0, unpack=unpack@entry=0, 
    expand=expand@entry=-14328, gfld=0x7ffff2c7ba60 <main_arena+96>) at degrib/g2clib/g2_getfld.c:255
(gdb) up
#1  0x000000000056e6bd in Grib2OpenFile (rec=<optimized out>, path=<optimized out>, wr_status=wr_status@entry=1) at NclGRIB2.c:10038
10038               err = g2_getfld(g2buf, i + 1, unpack, expand, &g2fld);
```

So ncl is calling the 5 arg g2_getfld but ends up with th 6 arg version from gdal.  The modified gdal version of g2clib needs to have its symbols renamed.

## Operating system

Fedora x86_64

## GDAL version and provenance

3.1.2 Fedora package

**Comment by opoplawski** [comment]
See also https://bugzilla.redhat.com/show_bug.cgi?id=1856959

**Comment by rouault** [comment]
Those changes were done to validate input data and avoid crashes when reading hostile/corrupted datasets. Ideally we'd want them to be integrated in upstream g2clib but we haven't yet figured the process to do so.
In the meantime, I've added a pull request that renames the symbols of the internal copy of g2clib in GDAL
