### ISSUE TITLE
ECW: Reference to undefined identifier NCS_DELETE_ALL_COPY_AND_MOVE

### ISSUE THREAD

**Issue by jschultz** [OSGeo/gdal#2776]
Attempting to build GDAL with ECW support on Debian using ECW SDK version 5.4 falls over at line 129 of gdal_ecw.h:

```
#if ECWSDK_VERSION >= 54
    NCS_DELETE_ALL_COPY_AND_MOVE(VSIIOStream)
#endif
```
This code was introduced on 2019-10-15 with commit e5cb5406ea9
I have no idea where `NCS_DELETE_ALL_COPY_AND_MOVE` is supposed to be defined but I can find no reference to it in GDAL or in the Desktop_Read-Only version of the SDK, which I presume should be supported.

**Comment by rouault** [comment]
What is you change this to >= 55 instead ?
And/or update to SDK 5.5 (but there are other issues with it, with "recent" Linux distros. might perhaps affect 5.4 as well)

**Comment by studiofuga** [comment]
@rouault it compiles, but will it work correctly? By the way, the issue is also with SDK 5.5, so we should be probably remove that line instead (or use a different test)

**Comment by rouault** [comment]
>  By the way, the issue is also with SDK 5.5

Hum, it seems some SDK distributions on some platforms at least have issues. CC @jbowman-hexagon

**Comment by jbowman-hexagon** [comment]
@jschultz Can you supply more details? Debian version, GCC version?

**Comment by studiofuga** [comment]
I'll put mine.
Windows 10, Visual Studio 2019 (not last release), Proj 6.x, gdal 3.1.1 or 3.1.2 (same issue), ECW sdk Read only versions 5.5, 5.4 and probably 5.3 too.
I haven't tested linux, probably I'll test it in near future.

**Comment by jschultz** [comment]
I'm running Debian/sid (unstable) with gcc version 9.3.0, using ECW SDK 5.4
However as best I can see that information is irrelevant. Version 5.4 of the SDK does not define `NCS_DELETE_ALL_COPY_AND_MOVE` while version 5.5 does. At least the Linux versions.
Probably unrelated, but if I try to build gdal using the 5.5 SDK then I get a different error involving undefined references to the following:

```
NCS::CIOStream::GetOptions()
NCS::CIOStream::GetStreamCounters[abi:cxx11]()
NCS::CView::OpenForRead(NCS::CString const&, std::shared_ptr<NCS::CIOStream>, bool)
NCS::CView::Open(std::shared_ptr<NCS::CIOStream> const&, bool, NCSFileType)
NCS::SDK::CBox::UnParse(NCS::SDK::CFileBase&, std::shared_ptr<NCS::CIOStream> const&)
vtable for NCS::CError
NCS::CView::OpenForWrite(NCS::CString const&, std::shared_ptr<NCS::CIOStream>, bool, NCSFileType)
NCS::CView::FindSteamByStreamNameFromOpenDatasets(NCS::CString const&)
NCS::CView::GetCompressionMemoryRequirementsBytes()
```

**Comment by studiofuga** [comment]
@jschultz , the issue with 5.5 is probably related to issue #2745 .

**Comment by jbowman-hexagon** [comment]
If using SDK v5.4, please also install update 1. For linux: http://download.hexagongeospatial.com/downloads/ecw/erdas-ecw-jp2-sdk-v54-update-1-for-linux. Similar available for Windows and Mac with a quick search.

SDK v5.5 can also be used but requires GDAL >= 3.1.

**Comment by GregersP** [comment]
> What is you change this to >= 55 instead ?
> And/or update to SDK 5.5 (but there are other issues with it, with "recent" Linux distros. might perhaps affect 5.4 as well)

I had the same error - and my simple patch for making it compile was:

```diff
--- a/gdal/frmts/ecw/gdal_ecw.h
+++ b/gdal/frmts/ecw/gdal_ecw.h
@@ -126,7 +126,7 @@ public:
 class VSIIOStream final: public CNCSJPCIOStream
 {
 #if ECWSDK_VERSION >= 54
-    NCS_DELETE_ALL_COPY_AND_MOVE(VSIIOStream)
+    NCS_DELETE_ALL_COPY_AND_MOVE(VSIIOStream);
 #endif
     char     *m_Filename;
   public:
```

**Comment by rouault** [comment]
> I had the same error

@GregersP  with which SDK version ?

**Comment by GregersP** [comment]
SDK 5.4

**Comment by GregersP** [comment]
I have now built an run a test where I read a couple of thousand ECWs. The semicolon was the only thing "stopping" me from compiling a working version against "ERDAS_ECWJP2_SDK-5.4.0.bin".
