### ISSUE TITLE
Open grb2 file which size  big than 300M will lead to a bug.

### ISSUE THREAD

**Issue by ljj1505204588** [OSGeo/gdal#2781]
This is error message : 
   Program received signal SIGSEGV, Segmentation fault.
gbits (in=in@entry=0x7fffdc96d010 "GRIB", iout=iout@entry=0x7fffffffd94c, iskip=iskip@entry=-2141203096, nbyte=nbyte@entry=32, nskip=nskip@entry=0, n=n@entry=1)
    at degrib18/g2clib-1.0.4/gbits.c:41

Use gdb tool find error point :
When: Try to open a grb2 type file which is big than 300M .
File: frmts/grib/degrib18/g2clib-1.0.4/gbits.c
function：void gbits(unsigned char *in,g2int *iout,g2int iskip,g2int nbyte,g2int nskip,                                                                                              g2int n)
error：parameter iskip(int)  will big than  2,147,483,647 than become a error num, like :-2141203096

How can I fix this ,or have another way to open this file success! 
Thanks very much !!!

**Comment by rouault** [comment]
From the stracktrace you indicate this must be with GDAL 2.2 or earlier. Please update to a more recent version. If the issue persists with newer versions, please re-open and provide a link to such a dataset
