### ISSUE TITLE
Open grb2 file which size big than 300M will lead to a bug.

### ISSUE THREAD

**Issue by ljj1505204588** [OSGeo/gdal#2788]
First,Thank you for answering my question
I install gdal-3.1.2 in linux system, but still have this error 

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff6f36143 in gbits (in=in@entry=0x7fffdc0bd010 "GRIB", in_length=in_length@entry=-1, iout=iout@entry=0x7fffffffd41c, iskip=iskip@entry=-2141203096, nbyte=nbyte@entry=32,
    nskip=nskip@entry=0, n=1) at degrib/g2clib/gbits.c:53

This error happen everytime when I try to open a grb2 type file which is big than 300M. 
I set a break point in func gbits ，than I find  this parameter ：iskip = initial number of bits to skip
Will overflow than make error。
This parameter type is int，So maybe It just suppost open file which less than 300M 
How can I fix this error . Thank you very much.

**Comment by rouault** [comment]
Please attach a link to such a dataset so this can be investigated

**Comment by ljj1505204588** [comment]
Sorry，I can't provied it for you ,this GRB2 type file is belong to company。
than I try to find a grb2 file  which is big than 300M,but i falied.

May be I can give other message to help you .
Can you tell me what you need. thank you.  
I watch this func step by step ，I find this parameter grow up step by step too. than 
become a negative number 。 

 By the way , I find the other way to open it. I use grib_api lib to split big file ，than I can use this small file in gdal.

Thank you for you patience 。
Thanks for you answering my question too .

**Comment by rouault** [comment]
300 MB ~= 2.4 giga-bits, which overflows a int32. I can actually see that the code in gbits.c works on int32  in many places. Should be updated to use long long. Hard/impossible to do without a sample file to reproduce the issue and iterate on fixing those insufficient large data types in all required places.

**Comment by ljj1505204588** [comment]
I create a big grib file which save a lot of the same bands . So this file just 14MB .I hope this file can help you  
This is link : https://c-t.work/s/acc53cbd695343
This is password : 64btbv
Thank you .
waiting for your respond。

**Comment by rouault** [comment]
I've tried the file at https://c-t.work/s/acc53cbd695343 but can't reproduce any issue with it. I suspect the issue is not about the file size, but the size of a GRIB band / message. Here there are 100 bands, so they are each well below 300 MB.

**Comment by ljj1505204588** [comment]
But error file have 80 bands too ,I just ues the first band 100 times  to create big file...
Maybe Gdal optimize the file reading process because all band have the same size or something else...
I will try to create another file which can cause error 。
please waiting for me。
Thanks.

**Comment by rouault** [comment]
Closing due to lack of feedback
