### ISSUE TITLE
Error generating geojson file arcgis services in GDAL 2.4 Debian 10

### ISSUE THREAD

**Issue by ccataldov** [OSGeo/gdal#2791]
## Expected behavior and actual behavior.

First of all, excuse the translation, English is not my native language.
The following procedure (URL arcgis services) in GDAL 2.4 Debian 10 not work.
![gdal_2 4-Debian10](https://user-images.githubusercontent.com/16226945/88218234-c2ae0300-cc2d-11ea-8678-d03245c65a41.png)
The same procedure in GDAL 2.2 Linux Mint it works.
![gdal_2 2-LinuxMint](https://user-images.githubusercontent.com/16226945/88218983-df970600-cc2e-11ea-9ac1-4e718abcc0c2.png)

## Operating system

SO Debian 10 64 bit

## GDAL version and provenance

GDAL version 2.4.0

-------------------------------------------------------------------------------------
For what is this?
Greetings and thanks

**Comment by rouault** [comment]
Since GDAL 2.3.0, ESRIJson is handled by the ESRIJSON driver, and the layer name is "ESRIJSON". You can check this easily by using ogrinfo on the connection string
