### ISSUE TITLE
projection missing while reading jp2 on mac using GDAL 3.1.2

### ISSUE THREAD

**Issue by palaiya** [OSGeo/gdal#2796]
## Steps to reproduce the problem.

I tried to read the JP2 (sentinel-2) file CRS using rasterio. So, i got the CRS value for every JP2 to be none. I deep dived further and checked that GDAL itself is not able to read it. As reproduced below as you can see projection is coming out to be blank. Where as if i open the same file in QGIS i get the proper CRS.

<img width="1274" alt="gdal-error" src="https://user-images.githubusercontent.com/10070831/88285281-72f23900-cd0c-11ea-86b4-eaadc70e17fd.png">

<img width="576" alt="Qgis-crs" src="https://user-images.githubusercontent.com/10070831/88285994-b0a39180-cd0d-11ea-9dc5-50e4e3eae881.png">

## Operating system

Mac os 10.14.5 

## GDAL version and provenance

GDAL 3.1.2, released 2020/07/07

**Comment by rouault** [comment]
From the error message, it looks like you're using a PROJ data directory that is not the one that is aimed to be used with the PROJ library.
