### ISSUE TITLE
gdal2tiles -p raster generates broken tiles if the max zoom level is not from the recommended range

### ISSUE THREAD

**Issue by itrambovetskyi** [OSGeo/gdal#2799]
Issue/Feature Request

gdal2tiles generates broken tiles if the max zoom level is not from the recommended range.
Also, I would like to have the ability to skip the generation of some zoom levels from a zoom level range.
For example:
Input image has size  7952x5304
Recommended zoom level range, in case of tiles size 256, is 0-5
I need only 0-4, I don't want even generate fifth level (to speed up the process)

Current state:
If I run the next command

`gdal2tiles.py -p raster --xyz --zoom=0-4 --tilesize=256 ...
`

this will generate "broken" tiles. Example:

![0](https://user-images.githubusercontent.com/13900051/88333808-7fd95180-cd39-11ea-9daf-90d6e0445952.png)

I need to have the ability to generate correct tiles with the previous command or add a special key for skipping levels. Example (**--skip-zoom-level**):

`gdal2tiles.py -p raster --xyz --zoom=0-5 --skip-zoom-level=5 --tilesize=256 ...`

**Comment by rouault** [comment]
The issue seems to be specific of the ``-p raster`` mode
