### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by tangxianqiang** [OSGeo/gdal#2800]
Can you give a complete Android compilation tutorial? in some area, we need use GDAL in phone. But there are not enough tutorial to make android app. 

We are not good at make GDAL (.so file or jar or aar) for android. If your team can meke a complete android aar will be very helpful for many developer

**Comment by rouault** [comment]
The upstream project cannot go into dealing with all the hundreds of different build environments that GDAL can be used with. Below various links with build recipees for Android:
https://github.com/opengisch/OSGeo4A
https://github.com/lutraconsulting/input-sdk
https://github.com/paamand/GDAL4Android

**Comment by tangxianqiang** [comment]
thanks

**Comment by jessebadry** [comment]
Hi, what did you end up doing to get GDAL working on android? 
Me and a friend can't figure out how to use the paamand GDAL4Android repo. Curious to see how your project turned out.

**Comment by dg0yt** [comment]
Basically, GDAL builds for Android just like any other CMake project. That's how it is available in vcpkg.
GDAL4Android questions should be asked there.
