### ISSUE TITLE
LVBAG: Check LokaalId conforms to 16 characters

### ISSUE THREAD

**Issue by tabeckers** [OSGeo/gdal#2804]
## Expected behavior and actual behavior.

The BAG format of LokaalId is a 16 characters long number, stored as text in their database. Some LokaalId fields in the BAG database aren't 16 characters long. The original numbers often start with one or more zeroes, which could sometims get discarded by accident when casting the LokaalId to a number before storing it as text in the database. These cases should be filtered out by prepending zeroes to the values until they have their original length of 16 characters.

## GDAL version and provenance

3.1.2-master

**Comment by rouault** [comment]
Which driver is implied here ? The new LVBAG driver in master ? In any case please attach a dataset, or a link to it

**Comment by yorickdewid** [comment]
@rouault This is LVBAG. Spec demands some fields to be exact 16 chars in size, which they often are, but not always.

#### Possible fix:
I'll add a check and will try to repair when `length(field) < 16` with prefix `0`.
If `length(field) > 16` we conclude invalid data and write a warning and ignore the feature.
