### ISSUE TITLE
VSI issue with TerraSAR-X (TSX) driver

### ISSUE THREAD

**Issue by gfkeith** [OSGeo/gdal#2814]
##  Expected behavior and actual behavior.

I expect to be able to open a TerraSAR-X image in an archive using the appropriate VSI prefix (/vsitar or /vsizip) and the path within the archive.

Actual behaviour is:
* If path in the archive is specified using '\' as in [the third example in the /vsizip section](https://gdal.org/user/virtual_file_systems.html#vsizip-zip-archives:~:text=%2Fvsizip%2Fc%3A%5Cusers%5Ceven%5Cmy.zip%5Csubdir%5Cmy.tif), then the following error occurs:

```
>>> ds = gdal.Open(r'/vsizip/2008-05-12_Strait_of_Gibraltar_SM_S_GEC_SE.zip\TSX1_SAR__GEC_SE___SM_S_SRA_20080512T062951_20080512T063000\TSX1_SAR__GEC_SE___SM_S_SRA_20080512T062951_20080512T063000.xml')
ERROR 4: `/vsizip/2008-05-12_Strait_of_Gibraltar_SM_S_GEC_SE.zip\TSX1_SAR__GEC_SE___SM_S_SRA_20080512T062951_20080512T063000\TSX1_SAR__GEC_SE___SM_S_SRA_20080512T062951_20080512T063000.xml' does not exist in the file system, and is not recognized as a supported dataset name.
```

* If the path in the archive is specified using '/':

```
>>> ds = gdal.Open(r'/vsizip/2008-05-12_Strait_of_Gibraltar_SM_S_GEC_SE.zip\TSX1_SAR__GEC_SE___SM_S_SRA_20080512T062951_20080512T063000/TSX1_SAR__GEC_SE___SM_S_SRA_20080512T062951_20080512T063000.xml')
ERROR 4: `tif' does not exist in the file system, and is not recognized as a supported dataset name.
ERROR 3: Cannot open file '/vsizip/2008-05-12_Strait_of_Gibraltar_SM_S_GEC_SE.zip\TSX1_SAR__GEC_SE___SM_S_SRA_20080512T062951_20080512T063000/ANNOTATION\GEOREF.xml'
```

Note that if the same steps are performed on Ubuntu (on WSL) with all path separators as /, then the image opens as expected.

## Steps to reproduce the problem.

Get a TerraSAR-X image in an archive format. The examples here are done using the sample image [here](https://www.intelligence-airbusds.com/en/9317-sample-imagery-detail?product=5297) but I have had the issue with others, including in .tar.gz archives using /vsitar.

```python
from osgeo import gdal

ds = gdal.Open(r'/vsizip/2008-05-12_Strait_of_Gibraltar_SM_S_GEC_SE.zip\TSX1_SAR__GEC_SE___SM_S_SRA_20080512T062951_20080512T063000/TSX1_SAR__GEC_SE___SM_S_SRA_20080512T062951_20080512T063000.xml')
```

## Operating system

Windows 10 64-bit, using Anaconda and Python 3.6

## GDAL version and provenance

3.0.4 originally sourced from [here](https://www.lfd.uci.edu/~gohlke/pythonlibs/#gdal).

## Notes

It seems that the internal archive paths always have to be specified using /, even on a Windows host. My guess is that CPLFormFilename is not doing this, so when the TSX driver attempts to open related files, the paths inside the archive are generated relative to the xml file with \ separator. e.g. ```/vsizip/2008-05-12_Strait_of_Gibraltar_SM_S_GEC_SE.zip\TSX1_SAR__GEC_SE___SM_S_SRA_20080512T062951_20080512T063000/ANNOTATION\GEOREF.xml```, noting ```ANNOTATION\GEOREF.xml``` at the end. Using other drivers such as DIMAP works with VSI, but the xml file to open is in the same directory as the image files so it doesn't have to use any path separators. Again, it only seems to work if the path to the xml is specified with / inside the archive, and \ outside of it, e.g. ```/vsizip/c:\path\to\archive.zip\path/inside/archive.xml```.

This might be related to https://trac.osgeo.org/gdal/ticket/6310.

**Comment by rouault** [comment]
@gfkeith  Can you try the following patch ?

```
diff --git a/gdal/frmts/tsx/tsxdataset.cpp b/gdal/frmts/tsx/tsxdataset.cpp
index f49c778..7933346 100644
--- a/gdal/frmts/tsx/tsxdataset.cpp
+++ b/gdal/frmts/tsx/tsxdataset.cpp
@@ -60,16 +60,16 @@ enum eProductType {
 /* GetFilePath: return a relative path to a file within an XML node.
  * Returns Null on failure
  */
-static const char *GetFilePath(CPLXMLNode *psXMLNode, const char **pszNodeType) {
+static CPLString GetFilePath(CPLXMLNode *psXMLNode, const char **pszNodeType) {
     const char *pszDirectory = CPLGetXMLValue( psXMLNode, "file.location.path", "" );
     const char *pszFilename = CPLGetXMLValue( psXMLNode, "file.location.filename", "" );
     *pszNodeType = CPLGetXMLValue (psXMLNode, "type", " " );
 
     if (pszDirectory == nullptr || pszFilename == nullptr) {
-        return nullptr;
+        return "";
     }
 
-    return CPLFormFilename( pszDirectory, pszFilename, "" );
+    return CPLString( pszDirectory ) + '/' + pszFilename;
 }
 
 /************************************************************************/
@@ -558,7 +558,7 @@ GDALDataset *TSXDataset::Open( GDALOpenInfo *poOpenInfo ) {
         const char *pszType = nullptr;
         const char *pszPath = CPLFormFilename(
                 CPLGetDirname( osFilename ),
-                GetFilePath(psComponent, &pszType),
+                GetFilePath(psComponent, &pszType).c_str(),
                 "" );
         const char *pszPolLayer = CPLGetXMLValue(psComponent, "polLayer", " ");
 
```

**Comment by gfkeith** [comment]
@rouault I haven't got the python bindings built correctly yet, but just using ```gdalinfo``` on the file appears to work correctly with that patch, thanks.
