### ISSUE TITLE
Geopackage empty geometry

### ISSUE THREAD

**Issue by adepoch** [OSGeo/gdal#2820]
Hi. I logged this with the QGIS project, but they said it was GDAL's tools that were the issues and to log it here instead. My aim was to produce an empty geometry so that I could pull it apart in binary format to see how it looks at binary and bitwise levels. I don't think the empty geometry for Geopackages is as according to the standard says (https://www.geopackage.org/spec/#gpb_spec). Here's what I did to prove this: I opened QGIS and created a blank Geopackage which automatically adds a table according to the user's requirements. Having added the table to the project I opened the table view and added a record from that window (rather than by adding a feature from the map interface). I hit save. When I use SQLite methods (in Python's sqlite3 package) to browse the table as a database table instead of a spatial layer the geometry column for that new record is a NULL. According to the standard an Empty geometry is actually meant to be a BLOB object with flags set to indicate it is an empty Geometry, and possibly with an empty envelope (it was hard interpret this part of the standard. I think the GDAL methods that QGIS are using might not be creating the empty Geometry properly. Unless there's something I'm missing? Thanks.

**Comment by rouault** [comment]
NULL geometries can also be accepted. They are different from EMPTY geometries. I don't think there's an issue with the way GDAL writes GeoPackage files

**Comment by rouault** [comment]
Can you attach such a GeoPackage file ? I'll run it through the OGC GeoPackage validation test suite

**Comment by adepoch** [comment]
Here's the file. If it's considered valid, then could you please tell me how to create an empty geometry. I tried to log a bug with ESRI Australia over how they handled nulls in the geometry column (which is by not showing it in the table view, unless you sort by a column) and they said it wasn't a bug, it was just invalid in how it showed up, it needed to be an empty geometry, not a null value in that field. I'd like to find the best way for my organisation to support all vendors, and it apepars only empty geometries might be supported at this stage by ESRI.

[new_geopackage.zip](https://github.com/OSGeo/gdal/files/5011884/new_geopackage.zip)

**Comment by rouault** [comment]
I tried the file on the OGC GeoPackage validator and it has issues with those null geometries, but I believe this is an issue with the validator. I've reported it as https://github.com/opengeospatial/ets-gpkg12/issues/106

Regarding creating empty geometries instead of null one, this is a matter of the code that calls the writing side of the OGR GeoPackage driver to pass an empty geometry instead of a null one. The driver can write (and read) both kinds.

**Comment by adepoch** [comment]
Thanks for that. Regarding you comment "The driver can write (and read) both kinds" are you saying that I can still use GDAL to create the empty geometry, just not using the QGIS tools as they call it with a default of nulls instead of empty?

**Comment by jratike80** [comment]
[point_gml.txt](https://github.com/OSGeo/gdal/files/5014249/point_gml.txt)

Rename the attached gml file and run. Do not care about the error.
```
ogr2ogr -f gpkg point_empty.gpkg point.gml
ERROR 1: Wrong field type for fid
```

Check the result

```
ogrinfo point_empty.gpkg -al
INFO: Open of `point_empty.gpkg'
      using driver `GPKG' successful.

Layer name: point
Geometry: Unknown (any)
Feature Count: 2
Extent: (330.000000, 269.000000) - (330.000000, 269.000000)
Layer SRS WKT:
(unknown)
FID Column = fid
Geometry Column = geometryProperty
attr: String (0.0)
OGRFeature(point):1
  attr (String) = a
  POINT (330 269)

OGRFeature(point):2
  attr (String) = b
  POINT EMPTY
```
I had to experiment a bit before getting an example that can be run with ogr2ogr and ogrinfo. PostGIS still does not export empty geometries as GML, see https://trac.osgeo.org/postgis/ticket/1377. 
OpenJUMP does save empty geometries into JML files but it seems to do it in a way that is not valid GML according to research made by Even in the above mentioned PostGIS ticket (<gml:Point></gml:Point>).
And SpatiaLite seems to handle empty geometries as NULL geometries and this query inserted geometry as NULL into geopackage
`ogrinfo -dialect indirect_sqlite -sql "insert into point (rowid,geom,attr) values (4,ST_GeomFromText('POINT EMPTY'), 'd')" emptytest.gpkg`

Finally I had success by converting JML file into gml with ogr2ogr and hand editing it by adding empty gml_coordinates list.

**Comment by rouault** [comment]
> are you saying that I can still use GDAL to create the empty geometry, just not using the QGIS tools as they call it with a default of nulls instead of empty?

It is a bit unfortunate that we don't manage with Spatialite to do it in SQL, but the following Python script will do the job to post-process a .gpkg with NULL geometries and put EMPTY geometries instead:

```
import sys
from osgeo import ogr

ds = ogr.Open(sys.argv[1], update=1)
for lyr in ds:
    if lyr.GetGeomType() != ogr.wkbNone:
        empty_geom = ogr.Geometry(lyr.GetGeomType())
        for feat in lyr:
            if feat.GetGeometryRef() is None:
                feat.SetGeometry(empty_geom)
                lyr.SetFeature(feat)
```
```
$ python set_empty.py my.gpkg
```

**Comment by rouault** [comment]
There's a pending change ( https://github.com/opengeospatial/ets-gpkg12/pull/109 ) in the GeoPackage test suite to allow again null geometries, so from my point of view, there's nothing to do on GDAL side.
