### ISSUE TITLE
Unexpected behaviour of ogr2ogr postgres connection string using non default schema

### ISSUE THREAD

**Issue by JGGeo** [OSGeo/gdal#2824]
Dear esteemed developers,

I just wanted to report a possible bug in the ogr2ogr tool.

## Expected behavior and actual behavior.
I want to export a PostGIS table from a defined schema into a shape file.

It works fine using the "input dataset open options" (-oo) for the schema definitions in the command:
```
ogr2ogr -overwrite -oo "ACTIVE_SCHEMA=userschema" -oo "SCHEMAS=userschema" -f "ESRI Shapefile"  "C:\Temp\temp.shp" PG:"host='localhost' port='5432' dbname='dbtemp' user='myuser' password='myuser'" "geotable"
```

It will not work using the "connection string" (PG:) for the schema definitions in the command:
```
ogr2ogr.exe -overwrite -f "ESRI Shapefile" "C:\Temp\temp.shp" PG:"host='localhost' port='5432' dbname='dbtemp' schemas='userschema' active_schema='userschema' user='myuser' password='myuser'" "geotable"
```
Debug Messsage of the failig second command:
> PG: PostGIS schema: 'public'
> PG: PostgreSQL version string : 'PostgreSQL 9.6.15, compiled by Visual C++ build 1800, 64-bit'
> PG: PostGIS version string : '2.5 USE_GEOS=1 USE_PROJ=1 USE_STATS=1'
> GDAL: GDALOpen(PG:host='localhost' port='5432' dbname='dbtemp' schemas='userschema' active_schema='userschema' user='myuser' password=XXXXXX this=0000017B8920BC50) succeeds as PostgreSQL.
> GDAL: GDALDriver::Create(ESRI Shapefile,C:\Temp\temp.shp,0,0,0,Unknown,0000000000000000)
> PG: Could not retrieve table oid for geotable
> ERROR 1: Couldn't fetch requested layer 'geotable'!
> GDAL: GDALClose(C:\Temp\temp.shp, this=0000017B8922ABC0)
> GDAL: GDALClose(PG:host='localhost' port='5432' dbname='dbtemp' schemas='userschema' active_schema='userschema' user='myuser' password=XXXXXX this=0000017B8920BC50)
> GDAL: In GDALDestroy - unloading GDAL shared library.

Am I wrong expecting the same behaviour of the two commands?

## Steps to reproduce the problem.

See above. It should be reproducable with any normal PostGIS table.

## Operating system

Windows 10 x64

## GDAL version and provenance

the 3.2.0dev (compiled 31.07.2020) version from [gisinternals.com](http://www.gisinternals.com/query.html?content=filelist&file=release-1911-x64-gdal-mapserver.zip)

**Comment by JGGeo** [comment]
Just noticed the same behavior is shown when importing a shapefile into a new PostGIS table.

I need to specify the "destination dataset open options" `-doo "SCHEMAS={3}" -doo "ACTIVE_SCHEMA={3}"` as the schema settings in the "connection string" (PG:) will be ignorred. -> The table will be written in the 'public' schema, if no "destination dataset open options" are set.

Here I also would expect the same behavior of the two command variations as the "connection string" limits the available schema.

**Comment by jratike80** [comment]
Where is the usage of schema parameters in the PostgreSQL connection string documented? GDAL documentation says that PQconnectdb()  is used and the documentation of PostgreSQL version https://www.postgresql.org/docs/12/libpq-connect.html does not list "schemas" of "active_schema" as supported parameters. If I read right keyword "options" with value -csearch_path= could be used for controlling access to schemas but I do not really know how to use it.

Do you know that `schemas='userschema' active_schema='userschema'` should work or do you only expect so?

**Comment by JGGeo** [comment]
@jratike80 It is used in the [advanced example section](https://gdal.org/drivers/vector/pg_advanced.html#advanced-examples).

**Comment by jratike80** [comment]
Ok, there are two links to that advanced examples section but I still think that the documentation on the main page of PostgreSQL driver is a bit misleading where it says

> Note: We use PQconnectdb() to make the connection, so any other options and defaults that would apply to it, apply to the name here (refer to the documentation of the PostgreSQL server. Here for PostgreSQL 8.4). The PG: prefix is used to mark the name as a postgres connection string.

**Comment by JGGeo** [comment]
[This section](https://gdal.org/drivers/vector/pg_advanced.html#connection-options-related-to-schemas-and-tables) describes the GDAL use of the schema connection options in detail. As I understand the "connection string" (PG:) can be used to limit the available schemas and the default schema for all ogr2ogr actions. But english is not my first language and I might not understand it correctly.

I see two options:
* Adjust the text in the [Connection options related to schemas and tables](https://gdal.org/drivers/vector/pg_advanced.html#connection-options-related-to-schemas-and-tables) section and the advanced example descriptions.
* Implement the expected behaviour (at least in my understanding).
If the  "connection string" (PG:) is restricted to certain schemas and the default schema is set -> respect it for all ogr2ogr processes.

**Comment by rouault** [comment]
schemas and active_schemas in connection string are parsed in a dedicated way by the driver and this is tested in https://github.com/OSGeo/gdal/blob/master/autotest/ogr/ogr_pg.py#L1935 and https://github.com/OSGeo/gdal/blob/master/autotest/ogr/ogr_pg.py#L1963 .

**Comment by jratike80** [comment]
So what goes wrong? Is it due to usage of single quotes in `schemas='userschema' active_schema='userschema'`?
Compare with the document of advanced options
`ogr2ogr -f PostgreSQL "PG:dbname=warmerda active_schema=apt200810" apt200810` and with the building of connection string in the autotest
` ds = ogr.Open('PG:' + gdaltest.pg_connection_string + ' active_schema=AutoTest-schema', update=1)`.

**Comment by rouault** [comment]
> Is it due to usage of single quotes in

ah very likely! GDAL parses its specific arguments in a custom & simple way, and doesn't understand single quoting

**Comment by JGGeo** [comment]
Thats it. Thanks for the help. If i remove the single quotes from the parameters : `schemas `and `active_schema` it works as expected.

But it is only neccessary to remove the quotes from the schema options. I can leave the single quotes around the other parameters and everything still works.

This seems a bit inconsistent. I expect the quotes around the `password` parameter is needed as I don't know how spaces are treated? And then, how do I escape singlequotes in the password?

**Comment by rouault** [comment]
> This seems a bit inconsistent.

indeed

> I expect the quotes around the password parameter is needed as I don't know how spaces are treated? And then, how do I escape singlequotes in the password?

The following from https://www.postgresql.org/docs/10/libpq-connect.html should apply from the standard connection parameters at least: 
```
33.1.1.1. Keyword/Value Connection Strings

In the first format, each parameter setting is in the form keyword = value. Spaces around the equal sign are optional. To write an empty value, or a value containing spaces, surround it with single quotes, e.g., keyword = 'a value'. Single quotes and backslashes within the value must be escaped with a backslash, i.e., \' and \\.
```

**Comment by JGGeo** [comment]
@rouault Thanks very much for the clarification! That is very helpful.

**Comment by screamsyk** [comment]
when I use option `active_schema`, `active_schema=schema_name` is right, and `active_schema='schema_name'` is bad.
be care for the single quotes
