### ISSUE TITLE
Invalid result when converting GeoJSON to RFC7946 conformant GeoJSON

### ISSUE THREAD

**Issue by ravhed** [OSGeo/gdal#2833]
## Expected behavior and actual behavior.

I'm trying to convert the following GeoJSON to RFC7946 conformant GeoJSON using `ogr2ogr`. GeoJSON:
```json
{
    "type": "Polygon",
    "coordinates": [
        [
            [-180, -90.0],
            [180, -90.0],
            [180, 90.0],
            [-180, 90.0],
            [-180, -90.0]
        ]
    ]
}
```
The expected behavior is that the produced RFC7946 GeoJSON will be world covering as the polygon above. This is not the case which you can see from the following output from `ogr2ogr`:

```json
{
    "type": "FeatureCollection",
    "features": [{
        "type": "Feature",
        "properties": {},
        "geometry": {
            "type": "MultiPolygon",
            "coordinates": [
                [],
                [
                    [
                        [-180.0, 90.0, 0.0],
                        [-180.0, -90.0, 0.0],
                        [0.0, -90.0, 0.0],
                        [0.0, 90.0, 0.0],
                        [-180.0, 90.0, 0.0]
                    ]
                ]
            ]
        }
    }]
}
```

I believe that converting it to multipolygon (splitting it at the antimeridian) is correct according to RFC7946 standard. However it seems like one polygon is missing from the result.

## Steps to reproduce the problem.

In a terminal with `ogr2ogr` available, the issue can be reproduced by running the following command:

```bash
echo '{"type":"Polygon","coordinates":[[[-180,-90.0],[180,-90.0],[180,90.0],[-180,90.0],[-180,-90.0]]]}' | ogr2ogr -f GeoJSON -lco RFC7946=YES /vsistdout/ /vsistdin/
```

## Operating system

Arch Linux x86_64

## GDAL version and provenance

GDAL 3.0.4, released 2020/01/28 (https://www.archlinux.org/packages/community/x86_64/gdal/)

**Comment by jratike80** [comment]
Did the fix correct also this double-instruction case?
`ogr2ogr -f geojson -lco RFC7946=YES dateline7946.json dateline.json -wrapdateline`
Result was
```
OGRFeature(dateline):0
  POLYGON ((-180 90,-180 -90,0 -90,0 90,-180 90))
```

**Comment by rouault** [comment]
> Did the fix correct also this double-instruction case?

yes

**Comment by ravhed** [comment]
Thanks for the very quick fix!
