### ISSUE TITLE
Sentinel1 SAFE driver for WV swath should not use measurements as bands 

### ISSUE THREAD

**Issue by oarcher** [OSGeo/gdal#2843]
Sentinel-1 WV acquisition mode (aka 'wave mode') contains multiples images (ie tiff), at [different spatial position](https://sentinel.esa.int/web/sentinel/user-guides/sentinel-1-sar/acquisition-modes/wave).

If there is only one polarization (ie 'VV'), each image are at *different spatial position*, and can't be stacked together as bands, as they can't share GCPs.

## Expected behavior and actual behavior.

Exemple file is `S1A_WV_SLC__1SSV_20160510T101603_20160510T102143_011195_010EA1_7038.SAFE` 

  * download zip: ftp://ftp.ifremer.fr/ifremer/cersat/datarmor/project/sarwing/SAFE_REF/S1A_WV_SLC__1SSV_20160510T101603_20160510T102143_011195_010EA1_7038.SAFE.zip 
  * browse: ftp://ftp.ifremer.fr/ifremer/cersat/datarmor/project/sarwing/SAFE_REF/S1A_WV_SLC__1SSV_20160510T101603_20160510T102143_011195_010EA1_7038.SAFE/

I expected to be able to open this SAFE raster file, by specifying witch image I want to load as a GDAL subdataset . But instead of having 24 subdatasets, gdal consider that there are only 2 subdatasets (WV1 and WV2) containing each 12 images.

Currently, gdalinfo give the following information on the WV1_VV subdataset:

```
gdalinfo SENTINEL1_DS:S1A_WV_SLC__1SSV_20160510T101603_20160510T102143_011195_010EA1_7038.SAFE:WV1_VV
Driver: SAFE/Sentinel-1 SAR SAFE Product
Files: S1A_WV_SLC__1SSV_20160510T101603_20160510T102143_011195_010EA1_7038.SAFE/manifest.safe
       S1A_WV_SLC__1SSV_20160510T101603_20160510T102143_011195_010EA1_7038.SAFE/annotation/s1a-wv1-slc-vv-20160510t101603-20160510t101606-011195-010ea1-001.xml
       S1A_WV_SLC__1SSV_20160510T101603_20160510T102143_011195_010EA1_7038.SAFE/measurement/s1a-wv1-slc-vv-20160510t101603-20160510t101606-011195-010ea1-001.tiff
       
[all file of WV1 subset listed]

S1A_WV_SLC__1SSV_20160510T101603_20160510T102143_011195_010EA1_7038.SAFE/annotation/s1a-wv1-slc-vv-20160510t102126-20160510t102129-011195-010ea1-023.xml
       S1A_WV_SLC__1SSV_20160510T101603_20160510T102143_011195_010EA1_7038.SAFE/measurement/s1a-wv1-slc-vv-20160510t102126-20160510t102129-011195-010ea1-023.tiff
Size is 4500, 4783
 
[...]

Data axis to CRS axis mapping: 2,1
GCP[  0]: Id=1, Info=
          (0,0) -> (-66.4285234994182,21.7549951761393,0)

[ Only 88 GCPs listed. I've checked that each tiff has 88 GCPs. 
I don't know from which file those come from... ]

GCP[ 87]: Id=88, Info=
          (4499,4782) -> (-66.6577199983997,21.6143805128245,0)
Metadata:
[...]
  SWATH=WV1
Subdatasets:
  SUBDATASET_1_NAME=SENTINEL1_DS:S1A_WV_SLC__1SSV_20160510T101603_20160510T102143_011195_010EA1_7038.SAFE:WV1_VV
  SUBDATASET_1_DESC=Single band with WV1 swath and VV polarisation
  SUBDATASET_2_NAME=SENTINEL1_DS:S1A_WV_SLC__1SSV_20160510T101603_20160510T102143_011195_010EA1_7038.SAFE:WV2_VV
  SUBDATASET_2_DESC=Single band with WV2 swath and VV polarisation

[ Only 2 subdatasets listed. Should be 24 ]

Band 1 Block=5681x1 Type=CInt16, ColorInterp=Undefined

[ 12 bands, corresponding to 12 tiff that are not a the same place ]

Band 12 Block=5681x1 Type=CInt16, ColorInterp=Undefined

```

## Operating system

Ubuntu 20.04 64 bit

## GDAL version and provenance

gdal 3.0.2 from anaconda.

**Comment by grouny** [comment]
Hi @rouault, do you plan to release  the version 3.1.3 on anaconda cloud?
Your correction for WV SAFE seems to work perfectly (I tested using gdalinfo command) but I can't find the way to install gdal 3.1.3 within an existing conda env.

**Comment by rouault** [comment]
3.1.3 isn't fully released yet. on Monday likely. And I guess the GDAL Conda folks will take care of packaging it afterwards.
