### ISSUE TITLE
error compiling jpeg2000 driver with gdal 3.1.2

### ISSUE THREAD

**Issue by saultdon** [OSGeo/gdal#2844]
## Expected behavior and actual behavior.

Trying to compile GDAL against jpeg2000 and it results in the error during compile:

>make -C jpeg2000 install-obj
make[2]: Entering directory '/tmp/makepkg/gdal/src/gdal-3.1.2/frmts/jpeg2000'
/bin/sh /tmp/makepkg/gdal/src/gdal-3.1.2/libtool --mode=compile --silent --tag=CXX g++ -I/tmp/makepkg/gdal/src/gdal-3.1.2/port -I/tmp/makepkg/gdal/src/gdal-3.1.2/gcore -I/tmp/makepkg/gdal/src/gdal-3.1.2/alg -I/tmp/makepkg/gdal/src/gdal-3.1.2/ogr -I/tmp/makepkg/gdal/src/gdal-3.1.2/ogr/ogrsf_frmts -I/tmp/makepkg/gdal/src/gdal-3.1.2/gnm -I/tmp/makepkg/gdal/src/gdal-3.1.2/apps -DHAVE_AVX_AT_COMPILE_TIME -DHAVE_SSSE3_AT_COMPILE_TIME -DHAVE_SSE_AT_COMPILE_TIME -march=native -O2 -pipe -fstack-protector-strong -fno-plt  -Wall -Wextra -Winit-self -Wunused-parameter -Wformat -Werror=format-security -Wno-format-nonliteral -Wlogical-op -Wshadow -Werror=vla -Wdate-time -Wnull-dereference -Wduplicated-cond -Wextra-semi -Wfloat-conversion -Wmissing-declarations -Wnon-virtual-dtor -Woverloaded-virtual -fno-operator-names -Wzero-as-null-pointer-constant -Wsuggest-override -Wimplicit-fallthrough   -DGNM_ENABLED -D_FORTIFY_SOURCE=2 -I/tmp/makepkg/gdal/src/gdal-3.1.2/port -I/usr/include/openjpeg-2.3  -I/usr/include  -DGDAL_COMPILATION -DHAVE_XERCES -I/usr/include -I/usr/include/xercesc -D_FORTIFY_SOURCE=2 -I/tmp/makepkg/gdal/src/gdal-3.1.2/port -I/usr/include/openjpeg-2.3  -I/usr/include  -DGDAL_COMPILATION -c -o ../o/jpeg2000dataset.lo jpeg2000dataset.cpp
jpeg2000dataset.cpp: In member function ‘int JPEG2000Dataset::DecodeImage()’
jpeg2000dataset.cpp:487:20: warning: comparison of integer expressions of different signedness: ‘int’ and ‘unsigned int’ [-Wsign-compare]
  487 |         if (nBands != jas_image_numcmpts( psImage ))
      |                    ^
jpeg2000dataset.cpp: In static member function ‘static GDALDataset* JPEG2000Dataset::Open(GDALOpenInfo*)’
jpeg2000dataset.cpp:611:46: error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]
  611 |     if ( !(pszFormatName = jas_image_fmttostr( iFormat )) )
      |                            ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
      |                                              |
      |                                              const char*
make[2]: *** [../../GDALmake.opt:649: ../o/jpeg2000dataset.lo] Error 1
make[2]: Leaving directory '/tmp/makepkg/gdal/src/gdal-3.1.2/frmts/jpeg2000'
make[1]: *** [GNUmakefile:15: jpeg2000-install-obj] Error 2
make[1]: Leaving directory '/tmp/makepkg/gdal/src/gdal-3.1.2/frmts'
make: *** [GNUmakefile:114: frmts-target] Error 2

## Operating system

Arch Linux 64-bit 5.7.12-arch1-1

## GDAL version and provenance

GDAL 3.1.2
jasper 2.0.17-1
libjpeg-turbo 2.0.5-1
openjpeg2 2.3.1-2

**Comment by stumbles** [comment]
I have the same issue using lunar-linux. 

GDAL 3.1.2
jasper 2.0.19
libjpeg-turbo 2.0.5
openjpeg-2 2.3.1

**Comment by saultdon** [comment]
The build has gotten farther with the patch provided, but here's where it gets hung up now:

`make -C jpeg2000 install-obj
make[2]: Entering directory '/tmp/makepkg/gdal/src/gdal-3.1.2/frmts/jpeg2000'
/bin/sh /tmp/makepkg/gdal/src/gdal-3.1.2/libtool --mode=compile --silent --tag=CXX g++ -I/tmp/makepkg/gdal/src/gdal-3.1.2/port -I/tmp/makepkg/gdal/src/gdal-3.1.2/gcore -I/tmp/makepkg/gdal/src/gdal-3.1.2/alg -I/tmp/makepkg/gdal/src/gdal-3.1.2/ogr -I/tmp/makepkg/gdal/src/gdal-3.1.2/ogr/ogrsf_frmts -I/tmp/makepkg/gdal/src/gdal-3.1.2/gnm -I/tmp/makepkg/gdal/src/gdal-3.1.2/apps -DHAVE_AVX_AT_COMPILE_TIME -DHAVE_SSSE3_AT_COMPILE_TIME -DHAVE_SSE_AT_COMPILE_TIME -march=native -O2 -pipe -fstack-protector-strong -fno-plt  -Wall -Wextra -Winit-self -Wunused-parameter -Wformat -Werror=format-security -Wno-format-nonliteral -Wlogical-op -Wshadow -Werror=vla -Wdate-time -Wnull-dereference -Wduplicated-cond -Wextra-semi -Wfloat-conversion -Wmissing-declarations -Wnon-virtual-dtor -Woverloaded-virtual -fno-operator-names -Wzero-as-null-pointer-constant -Wsuggest-override -Wimplicit-fallthrough   -DGNM_ENABLED -D_FORTIFY_SOURCE=2 -I/tmp/makepkg/gdal/src/gdal-3.1.2/port -I/usr/include/openjpeg-2.3  -I/usr/include  -DGDAL_COMPILATION -DHAVE_XERCES -I/usr/include -I/usr/include/xercesc -D_FORTIFY_SOURCE=2 -I/tmp/makepkg/gdal/src/gdal-3.1.2/port -I/usr/include/openjpeg-2.3  -I/usr/include  -DGDAL_COMPILATION -c -o ../o/jpeg2000dataset.lo jpeg2000dataset.cpp
/bin/sh /tmp/makepkg/gdal/src/gdal-3.1.2/libtool --mode=compile --silent --tag=CXX g++ -I/tmp/makepkg/gdal/src/gdal-3.1.2/port -I/tmp/makepkg/gdal/src/gdal-3.1.2/gcore -I/tmp/makepkg/gdal/src/gdal-3.1.2/alg -I/tmp/makepkg/gdal/src/gdal-3.1.2/ogr -I/tmp/makepkg/gdal/src/gdal-3.1.2/ogr/ogrsf_frmts -I/tmp/makepkg/gdal/src/gdal-3.1.2/gnm -I/tmp/makepkg/gdal/src/gdal-3.1.2/apps -DHAVE_AVX_AT_COMPILE_TIME -DHAVE_SSSE3_AT_COMPILE_TIME -DHAVE_SSE_AT_COMPILE_TIME -march=native -O2 -pipe -fstack-protector-strong -fno-plt  -Wall -Wextra -Winit-self -Wunused-parameter -Wformat -Werror=format-security -Wno-format-nonliteral -Wlogical-op -Wshadow -Werror=vla -Wdate-time -Wnull-dereference -Wduplicated-cond -Wextra-semi -Wfloat-conversion -Wmissing-declarations -Wnon-virtual-dtor -Woverloaded-virtual -fno-operator-names -Wzero-as-null-pointer-constant -Wsuggest-override -Wimplicit-fallthrough   -DGNM_ENABLED -D_FORTIFY_SOURCE=2 -I/tmp/makepkg/gdal/src/gdal-3.1.2/port -I/usr/include/openjpeg-2.3  -I/usr/include  -DGDAL_COMPILATION -DHAVE_XERCES -I/usr/include -I/usr/include/xercesc -D_FORTIFY_SOURCE=2 -I/tmp/makepkg/gdal/src/gdal-3.1.2/port -I/usr/include/openjpeg-2.3  -I/usr/include  -DGDAL_COMPILATION -c -o ../o/jpeg2000_vsil_io.lo jpeg2000_vsil_io.cpp
jpeg2000_vsil_io.cpp:140:5: error: invalid conversion from ‘int (*)(jas_stream_obj_t*, char*, int)’ {aka ‘int (*)(void*, char*, int)’} to ‘int (*)(jas_stream_obj_t*, char*, unsigned int)’ {aka ‘int (*)(void*, char*, unsigned int)’} [-fpermissive]
  140 |     JPEG2000_VSIL_read,
      |     ^~~~~~~~~~~~~~~~~~
      |     |
      |     int (*)(jas_stream_obj_t*, char*, int) {aka int (*)(void*, char*, int)}
jpeg2000_vsil_io.cpp:141:5: error: invalid conversion from ‘int (*)(jas_stream_obj_t*, char*, int)’ {aka ‘int (*)(void*, char*, int)’} to ‘int (*)(jas_stream_obj_t*, char*, unsigned int)’ {aka ‘int (*)(void*, char*, unsigned int)’} [-fpermissive]
  141 |     JPEG2000_VSIL_write,
      |     ^~~~~~~~~~~~~~~~~~~
      |     |
      |     int (*)(jas_stream_obj_t*, char*, int) {aka int (*)(void*, char*, int)}
make[2]: *** [../../GDALmake.opt:649: ../o/jpeg2000_vsil_io.lo] Error 1
make[2]: Leaving directory '/tmp/makepkg/gdal/src/gdal-3.1.2/frmts/jpeg2000'
make[1]: *** [GNUmakefile:15: jpeg2000-install-obj] Error 2
make[1]: Leaving directory '/tmp/makepkg/gdal/src/gdal-3.1.2/frmts'
make: *** [GNUmakefile:114: frmts-target] Error 2`
