### ISSUE TITLE
GDAL 3.1.2 build error on Fedora 32

### ISSUE THREAD

**Issue by devrimgunduz** [OSGeo/gdal#2859]
Hi,
I'm getting the following error while building GDAL 3.1.2 on Fedora 32 (gcc 10.2.1). Checked the commits post 3.1.2, but could not see anything that fixes it. Any ideas?

Thanks! Devrim

`make[4]: Entering directory '/home/devrim/Documents/Devrim/Projects/repo/pgrpms/rpm/redhat/master/common/gdal31/master/gdal-3.1.2-fedora/ogr/ogrsf_frmts/walk'
/bin/sh /home/devrim/belgeler/Devrim/Projects/repo/pgrpms/rpm/redhat/master/common/gdal31/master/gdal-3.1.2-fedora/libtool --mode=compile --silent --tag=CXX g++ -I/home/devrim/belgeler/Devrim/Projects/repo/pgrpms/rpm/redhat/master/common/gdal31/master/gdal-3.1.2-fedora/port -I/home/devrim/belgeler/Devrim/Projects/repo/pgrpms/rpm/redhat/master/common/gdal31/master/gdal-3.1.2-fedora/gcore -I/home/devrim/belgeler/Devrim/Projects/repo/pgrpms/rpm/redhat/master/common/gdal31/master/gdal-3.1.2-fedora/alg -I/home/devrim/belgeler/Devrim/Projects/repo/pgrpms/rpm/redhat/master/common/gdal31/master/gdal-3.1.2-fedora/ogr -I/home/devrim/belgeler/Devrim/Projects/repo/pgrpms/rpm/redhat/master/common/gdal31/master/gdal-3.1.2-fedora/ogr/ogrsf_frmts -I/home/devrim/belgeler/Devrim/Projects/repo/pgrpms/rpm/redhat/master/common/gdal31/master/gdal-3.1.2-fedora/gnm -I/home/devrim/belgeler/Devrim/Projects/repo/pgrpms/rpm/redhat/master/common/gdal31/master/gdal-3.1.2-fedora/apps -DHAVE_AVX_AT_COMPILE_TIME -DHAVE_SSSE3_AT_COMPILE_TIME -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fpic -I/usr/libgeotiff15/include -I/usr/geos38/include  -I/usr/ogdi41/include -I/usr/libspatialite15/include -I/usr/include/tirpc  -Wall -Wextra -Winit-self -Wunused-parameter -Wformat -Werror=format-security -Wno-format-nonliteral -Wlogical-op -Wshadow -Werror=vla -Wdate-time -Wnull-dereference -Wduplicated-cond -Wextra-semi -Wfloat-conversion -Wmissing-declarations -Wnon-virtual-dtor -Woverloaded-virtual -fno-operator-names -Wzero-as-null-pointer-constant -Wsuggest-override -Wimplicit-fallthrough  -I.. -I../.. -I../generic -I../pgeo  -DGNM_ENABLED -I/usr/libgeotiff15/include -I/usr/geos38/include -I/usr/ogdi41/include -I/usr/libspatialite15/include -I/usr/include/tirpc -I/home/devrim/belgeler/Devrim/Projects/repo/pgrpms/rpm/redhat/master/common/gdal31/master/gdal-3.1.2-fedora/port -I/usr/include/openjpeg-2.3  -I/usr/include -I/usr/libgeotiff15/include -Iexternal/include -I/usr/include/cfitsio  -DGDAL_COMPILATION -DHAVE_XERCES -I/usr/include -I/usr/include/xercesc -I/usr/libgeotiff15/include -I/usr/geos38/include -I/usr/ogdi41/include -I/usr/libspatialite15/include -I/usr/include/tirpc -I/home/devrim/belgeler/Devrim/Projects/repo/pgrpms/rpm/redhat/master/common/gdal31/master/gdal-3.1.2-fedora/port -I/usr/include/openjpeg-2.3  -I/usr/include -I/usr/libgeotiff15/include -Iexternal/include -I/usr/include/cfitsio  -DGDAL_COMPILATION -c -o ../o/ogrwalkdriver.lo ogrwalkdriver.cpp
/bin/sh /home/devrim/belgeler/Devrim/Projects/repo/pgrpms/rpm/redhat/master/common/gdal31/master/gdal-3.1.2-fedora/libtool --mode=compile --silent --tag=CXX g++ -I/home/devrim/belgeler/Devrim/Projects/repo/pgrpms/rpm/redhat/master/common/gdal31/master/gdal-3.1.2-fedora/port -I/home/devrim/belgeler/Devrim/Projects/repo/pgrpms/rpm/redhat/master/common/gdal31/master/gdal-3.1.2-fedora/gcore -I/home/devrim/belgeler/Devrim/Projects/repo/pgrpms/rpm/redhat/master/common/gdal31/master/gdal-3.1.2-fedora/alg -I/home/devrim/belgeler/Devrim/Projects/repo/pgrpms/rpm/redhat/master/common/gdal31/master/gdal-3.1.2-fedora/ogr -I/home/devrim/belgeler/Devrim/Projects/repo/pgrpms/rpm/redhat/master/common/gdal31/master/gdal-3.1.2-fedora/ogr/ogrsf_frmts -I/home/devrim/belgeler/Devrim/Projects/repo/pgrpms/rpm/redhat/master/common/gdal31/master/gdal-3.1.2-fedora/gnm -I/home/devrim/belgeler/Devrim/Projects/repo/pgrpms/rpm/redhat/master/common/gdal31/master/gdal-3.1.2-fedora/apps -DHAVE_AVX_AT_COMPILE_TIME -DHAVE_SSSE3_AT_COMPILE_TIME -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fpic -I/usr/libgeotiff15/include -I/usr/geos38/include  -I/usr/ogdi41/include -I/usr/libspatialite15/include -I/usr/include/tirpc  -Wall -Wextra -Winit-self -Wunused-parameter -Wformat -Werror=format-security -Wno-format-nonliteral -Wlogical-op -Wshadow -Werror=vla -Wdate-time -Wnull-dereference -Wduplicated-cond -Wextra-semi -Wfloat-conversion -Wmissing-declarations -Wnon-virtual-dtor -Woverloaded-virtual -fno-operator-names -Wzero-as-null-pointer-constant -Wsuggest-override -Wimplicit-fallthrough  -I.. -I../.. -DGNM_ENABLED -I/usr/libgeotiff15/include -I/usr/geos38/include -I/usr/ogdi41/include -I/usr/libspatialite15/include -I/usr/include/tirpc -I/home/devrim/belgeler/Devrim/Projects/repo/pgrpms/rpm/redhat/master/common/gdal31/master/gdal-3.1.2-fedora/port -I/usr/include/openjpeg-2.3  -I/usr/include -I/usr/libgeotiff15/include -Iexternal/include -I/usr/include/cfitsio  -DGDAL_COMPILATION -DHAVE_XERCES -I/usr/include -I/usr/include/xercesc -I/usr/libgeotiff15/include -I/usr/geos38/include -I/usr/ogdi41/include -I/usr/libspatialite15/include -I/usr/include/tirpc -I/home/devrim/belgeler/Devrim/Projects/repo/pgrpms/rpm/redhat/master/common/gdal31/master/gdal-3.1.2-fedora/port -I/usr/include/openjpeg-2.3  -I/usr/include -I/usr/libgeotiff15/include -Iexternal/include -I/usr/include/cfitsio  -DGDAL_COMPILATION -c -o ../o/ogrmssqlgeometryvalidator.lo ogrmssqlgeometryvalidator.cpp
In file included from /usr/lib/gcc/x86_64-redhat-linux/10/include/immintrin.h:55,
                 from /usr/lib/gcc/x86_64-redhat-linux/10/include/x86intrin.h:32,
                 from /home/devrim/belgeler/Devrim/Projects/repo/pgrpms/rpm/redhat/master/common/gdal31/master/gdal-3.1.2-fedora/port/cpl_port.h:712,
                 from /home/devrim/belgeler/Devrim/Projects/repo/pgrpms/rpm/redhat/master/common/gdal31/master/gdal-3.1.2-fedora/port/cpl_conv.h:35,
                 from ogrgeomediaselectlayer.cpp:31:
/usr/lib/gcc/x86_64-redhat-linux/10/include/avx512fintrin.h: In function '__m512i _mm512_set_epi16(short int, short int, short int, short int, short int, short int, short int, short int, short int, short int, short int, short int, short int, short int, short int, short int, short int, short int, short int, short int, short int, short int, short int, short int, short int, short int, short int, short int, short int, short int, short int, short int)':
/usr/lib/gcc/x86_64-redhat-linux/10/include/avx512fintrin.h:111:41: error: expected primary-expression before ')' token
  111 |   return __extension__ (__m512i)(__v32hi){
      |                                         ^
/usr/lib/gcc/x86_64-redhat-linux/10/include/avx512fintrin.h:111:42: error: expected ';' before '{' token
  111 |   return __extension__ (__m512i)(__v32hi){
      |                                          ^
      |                                          ;
/usr/lib/gcc/x86_64-redhat-linux/10/include/avx512fintrin.h:115:59: error: expected ':' before '}' token
  115 |     __q24, __q25, __q26, __q27, __q28, __q29, __q30, __q31
      |                                                           ^
      |                                                           :
  116 |   };
      |   ~                                                        
/usr/lib/gcc/x86_64-redhat-linux/10/include/avx512fintrin.h:116:3: error: expected primary-expression before '}' token
  116 |   };
      |   ^
make[4]: *** [../../../GDALmake.opt:649: ../o/ogrgeomediaselectlayer.lo] Error 1
make[4]: Leaving directory '/home/devrim/Documents/Devrim/Projects/repo/pgrpms/rpm/redhat/master/common/gdal31/master/gdal-3.1.2-fedora/ogr/ogrsf_frmts/geomedia'
make[3]: *** [../../GDALmake.opt:662: geomedia-target] Error 2
make[3]: *** Waiting for unfinished jobs....
/bin/sh /home/devrim/belgeler/Devrim/Projects/repo/pgr`

**Comment by devrimgunduz** [comment]
A better looking version of the message:

https://www.gunduz.org/temp/gdal-3.1.2-2859.txt

**Comment by rouault** [comment]
I've tried to replicate on a Docker fedora:32 image with a standard build, and adding a few of the specific build flags I could see int the compilation line, but can't get a build failure on ogrgeomediaselectlayer.cpp.  Maybe something included that would mess with the __v32hi type. Is it the only file on which the compilation error occur ?

**Comment by devrimgunduz** [comment]
Hi @rouault ,

Disabled parallel build, and here is the  first failure:

https://www.gunduz.org/temp/gdal-3.1.2-2859-0.txt

Please note that I applied the patch below to the  RPM spec file, which is supposed to fix this failure:

https://git.postgresql.org/gitweb/?p=pgrpms.git;a=blob;f=rpm/redhat/master/common/gdal31/master/gdal-3.1.2-jasper-2.0.17-fix.patch;h=44f5278466f58a1637af8537c69564890fdf85b9;hb=ea360a5fdc4d30b4b3eb2c687516c439f064a63a

Regards, Devrim

**Comment by rouault** [comment]
> Please note that I applied the patch below to the RPM spec file, which is supposed to fix this failure:

this jpeg2000 failure seems completely related to your initial one. I didn't get if the patch you applied for this jpeg2000 failure did solve the issue in the jpeg2000 driver

**Comment by rouault** [comment]
Ah, you also need ab72c4893e6d14d488dfed25745d79f11bee45b9 for the jpeg2000 build failure

**Comment by devrimgunduz** [comment]
Hi @rouault ,

Ok, applied that patch as well. Now, have another one:

 https://www.gunduz.org/temp/gdal-3.1.2-2859-1.txt

**Comment by devrimgunduz** [comment]
FWIW, this is the last version of the patch:

https://git.postgresql.org/gitweb/?p=pgrpms.git;a=blob;f=rpm/redhat/master/common/gdal31/master/gdal-3.1.2-jasper-2.0.17-fix.patch;h=334d460a2a6bed8e78a9fa8cbcba6089f9bd020f;hb=d33b1ac9f90fdd8e60fe741ef5a8fb993f9acbfd

I may be missing something, per #2844 .

**Comment by rouault** [comment]
> I may be missing something, per #2844 .

The patch looks good, but you should check if your Jasper include files have the PRIjas_seqent macro. 2.0.19 does, but
apparently there was some confusion in the tagging of 2.0.17, so depending on which 2.0.17 you use, you might get issues

**Comment by devrimgunduz** [comment]
Hi @rouault ,

I'm using the stock 2.0.17 that comes with Fedora:

jasper-libs-2.0.17-1.fc32.x86_64

Checked spec file, and there are no extra patches. How can patch this 2.0.17?

Regards, Devrim

**Comment by rouault** [comment]
> How can patch this 2.0.17?

you might perhaps need to change your GDAL patch to take the following lines
```
static int JPEG2000_VSIL_read(jas_stream_obj_t *obj, char *buf, unsigned cnt)
static int JPEG2000_VSIL_write(jas_stream_obj_t *obj, char *buf, unsigned int cnt)
```
(that is as if "#ifndef PRIjas_seqent" evaluates to "#if 0")

**Comment by devrimgunduz** [comment]
Can you please elaborate? I'm not a C guy, sorry :(

**Comment by rouault** [comment]
> Can you please elaborate?

in your patch, change the 2 occurences of ```#ifndef PRIjas_seqent``` to ```#if 0```.

**Comment by devrimgunduz** [comment]
We are getting there: ) So, I need another help.

libtool is throwing an error:

<snip>

```
 third_party/o/Lerc.lo third_party/o/Lerc2.lo third_party/o/Lerc_c_api_impl.lo third_party/o/RLE.lo \
    -rpath /usr/gdal31/lib \
    -no-undefined \
    -version-info 27:2:0

*** Warning: Linking the shared library libgdal.la against the loadable module
*** libSFCGAL.so is not portable!
g++: error: /usr/lib/libSFCGAL.so: No such file or directory
```

The message is correct, because it is under /usr/lib64 directory.  However, configure finds it correctly:


```
configure:34789: checking for sfcgal-config
configure:34807: found /usr/bin/sfcgal-config
configure:34820: result: /usr/bin/sfcgal-config
configure:34920: checking for SFCGAL version >= 1.2.2
configure:34943: result: yes
configure:34973: checking for sfcgal_version in -lSFCGAL
configure:34999: gcc -o conftest -I/usr/include  -I/usr/libgeotiff15/include -I/usr/geos38/include -I/usr/ogdi41/include -I/usr/libspatialite15/include -I/usr/include/tirpc   
-L/usr/ogdi41/lib -L/usr/libgeotiff15/lib -L/usr/geos38/lib64 -L/usr/libspatialite15/lib conftest.c -lSFCGAL
       -L/usr/lib64 -lSFCGAL -lgmpxx >&5
configure:34999: $? = 0
configure:35008: result: yes
configure:35032: Using C API from SFCGAL 1.3.7

```

and sfcgal-config returns correct dir:


```
sfcgal-config --libs
-L/usr/lib64 -lSFCGAL -lgmpxx

```

Any ideas what is changing  /usr/lib64 to /usr/lib? Please note that  3.0.4 could be built with the same combination.

Thanks!

Regards, Devrim

**Comment by rouault** [comment]
> Any ideas what is changing /usr/lib64 to /usr/lib?

Hum, I suspect this might be the consequence of bb87efed9a8be32116f4e9c3f41250479302f560 that removes some linking paths like -L/usr/lib, -L/usr/lib64 as they can shadow custom libraries installed in non-system directories. You might try to remove the 2 lines at https://github.com/OSGeo/gdal/commit/bb87efed9a8be32116f4e9c3f41250479302f560#diff-586e3bcb3ce8ae39b270d0fababb2770R4598-R4599 , and regenerate configure with "autoconf"

**Comment by devrimgunduz** [comment]
Hi @rouault ,

Thanks a lof for your  help. Wiht the ast comment, I could build GDAL 3.1.2 on RHEL 7, RHEL 8 and Fedora. RPMs will be out very soon at https://yum.postgresql.org 

Regards, Devrim

**Comment by devrimgunduz** [comment]
Good morning @rouault ,

Based on this thread, do you think you need to revert some commits before the next version, or will I carry these patches in the RPMs?

Regards, Devrim

**Comment by rouault** [comment]
> do you think you need to revert some commits before the next version

The JPEG2000 changes should be fine hopefully for jasper < 2.0 or = 2.0.19 (not sure about the future since they seem to do code sanitzations lately, so might break again).
But I'm not so sure about the configure stripping logic. @eleaver Do you think https://github.com/OSGeo/gdal/commit/bb87efed9a8be32116f4e9c3f41250479302f560 could be improved to avoid the issue found here on Fedora ? I'm pondering if it shouldn't be reverted

**Comment by rouault** [comment]
ping @eleaver : Do you think bb87efe could be improved to avoid the issue found here on Fedora ? I'm pondering if it shouldn't be reverted

**Comment by rouault** [comment]
closing as 3.1.2 and autoconf builds are no longer supported
