### ISSUE TITLE
Error in using gdal3.0.0 static library compiled on win10 

### ISSUE THREAD

**Issue by yliu1yb** [OSGeo/gdal#2861]
## Expected behavior and actual behavior.

I set  "DLLBUILD=0"  in the nmake.opt,  compiled a statical gdal3.0, and got a gdal.lib.  
```
# Set DLLBUILD=0 to create a static lib instead of a shared lib (.DLL)
!IFNDEF DLLBUILD
DLLBUILD=0
!ENDIF
```
when I run my code with static lib, error occoured. Error info is “MDd_DynamicDebug” not match “MTd_StaticDebug”.
But,I run my code with Dynamic library, it runs well.
I try to modify the Gdal3.0 nmake.opt, but  I find no MTd info in the nmake.opt,  just exist MDd and MD info.

## Steps to reproduce the problem.

run code with static lib.

## Operating system

windows10 vs2015

## GDAL version and provenance
GDAL3.0.0, [http://download.osgeo.org/gdal/3.0.0/gdal300.zip](url)

**Comment by rouault** [comment]
yes, the static build of GDAL still uses dynamic runtimes. You need to hand edit the OPTFLAGS line if you want to change this

**Comment by yliu1yb** [comment]
@rouault 
```
!IFNDEF OPTFLAGS
!IF "$(DEBUG)" == "0"
OPTFLAGS= $(CXX_ANALYZE_FLAGS) $(CXX_PDB_FLAGS) /nologo /MP /MD /EHsc /Ox /FC /D_CRT_SECURE_NO_DEPRECATE /D_CRT_NONSTDC_NO_DEPRECATE /DNDEBUG
!ELSE
OPTFLAGS= $(CXX_ANALYZE_FLAGS) $(CXX_PDB_FLAGS) /nologo /MP /MDd /EHsc /FC /D_CRT_SECURE_NO_DEPRECATE /D_CRT_NONSTDC_NO_DEPRECATE /DDEBUG
!ENDIF
!ENDIF  # OPTFLAGS
```
Just change MDd to MTd?(if DEBUG == 1)

**Comment by rouault** [comment]
> Just change MDd to MTd?(if DEBUG == 1)

yes

**Comment by yliu1yb** [comment]
@rouault 
I have Changed MDd to MTd, and recompiled it.
but when I test my code with gdal.lib,  errors occurred.
error info were 
`
gdal.lib(cpl_vsisimple.obj) "MDd_DynamicDebug" not match "MTd_StaticDebug”(GdalTest.obj)
gdal.lib(cpl_vsisimple.obj) "MDd_DynamicDebug" not match "MTd_StaticDebug”(GdalTest.obj)
gdal.lib(cpl_vsisimple.obj) "MDd_DynamicDebug" not match "MTd_StaticDebug”(GdalTest.obj)
gdal.lib(cpl_vsisimple.obj) "MDd_DynamicDebug" not match "MTd_StaticDebug”(GdalTest.obj)
gdal.lib(cpl_vsisimple.obj) "MDd_DynamicDebug" not match "MTd_StaticDebug”(GdalTest.obj)
gdal.lib(cpl_vsisimple.obj) "MDd_DynamicDebug" not match "MTd_StaticDebug”(GdalTest.obj)
gdal.lib(cpl_vsisimple.obj) "MDd_DynamicDebug" not match "MTd_StaticDebug”(GdalTest.obj)
`

**Comment by rouault** [comment]
Closing. Not clear this is a GDAL issue
