### ISSUE TITLE
doc build issues on RHEL 7 and 8

### ISSUE THREAD

**Issue by devrimgunduz** [OSGeo/gdal#2863]
Hi,

GDAL 3.1.2 doc builds failed on RHEL 7 and 8, because of the sphinx-build version:

RHEL 7: python3-sphinx-1.2.3-6
RHEL 8: python3-sphinx-1.7.6-1

Looks like GDAL 3.1.2 needs a more recent sphinx (like 2.2.2) that accepts --keep-going parameter:

```
+ /usr/bin/make man
make[1]: Entering directory '/var/lib/pgsql/git/pgrpms/rpm/redhat/master/common/gdal31/master/gdal-3.1.2-fedora'
(cd doc; make man)
make[2]: Entering directory '/var/lib/pgsql/git/pgrpms/rpm/redhat/master/common/gdal31/master/gdal-3.1.2-fedora/doc'
python3 "source/build_driver_summary.py" "source/drivers/raster" raster_driver_summary "source/drivers/raster/driver_summary.rst"
python3 "source/build_driver_summary.py" "source/drivers/vector" vector_driver_summary "source/drivers/vector/driver_summary.rst"
python3 "source/build_configoptions_index.py"  "source" "source/user/configoptions_index_generated.rst"
sphinx-build-3 -M man "source" "build" --keep-going -j auto -W 
usage: sphinx-build-3 [OPTIONS] SOURCEDIR OUTPUTDIR [FILENAMES...]
sphinx-build-3: error: unrecognized arguments: --keep-going
make[2]: *** [Makefile:48: man] Error 2
make[2]: Leaving directory '/var/lib/pgsql/git/pgrpms/rpm/redhat/master/common/gdal31/master/gdal-3.1.2-fedora/doc'
make[1]: *** [GNUmakefile:181: man] Error 2
make[1]: Leaving directory '/var/lib/pgsql/git/pgrpms/rpm/redhat/master/common/gdal31/master/gdal-3.1.2-fedora'
error: Bad exit status from /var/tmp/rpm-tmp.DKb7Fc (%build)

```

Regards, Devrim

**Comment by rouault** [comment]
> Looks like GDAL 3.1.2 needs a more recent sphinx (like 2.2.2) that accepts --keep-going parameter:

yes, those sphinx versions are failly old. You could potentially try to remove the --keep-going parameter (as well as -W in case warnings happen), but I cannot guarantee that the doc will build completely fine. Locally the oldest sphinx version I have is 2.4.4

**Comment by mloskot** [comment]
@devrimgunduz  By the way, this could be bumped to `=>2.4`

https://github.com/OSGeo/gdal/blob/4d2a82e83fef8c37be5c0e11b4355f3f17d276f9/gdal/doc/requirements.txt#L4

**Comment by devrimgunduz** [comment]
Hi,

I need to use OS-supplied sphinx packages (RPMs do not use pip, etc).

Patching doc/Makefile did not work (RHEL 7 has more issues). Can I disable doc builds? Could not find a clue in the configure script.

Regards,

**Comment by rouault** [comment]
> Can I disable doc builds?

Just don't run the "make man" target. The tarballs have already the man pages already generated, so they can be installed by just running "make install"
