### ISSUE TITLE
No longer able to overwrite rasters with gdalWarp in gdal 3.1.1

### ISSUE THREAD

**Issue by sssangha** [OSGeo/gdal#2867]
## Expected behavior and actual behavior.

I am no longer able to overwrite files using ```gdalWarp``` calls in gdal 3.1.1, as I had been able to using gdal 3.0.4

## Steps to reproduce the problem.

Refer to the attached files to replicate this test. Note that the test outlined below is meant to be a barebones example meant to illustrate this issue, and is not representative of a specific call I wish to incorporate in a routine. You may also refer to https://github.com/aria-tools/ARIA-tools/issues/210 for a more practical example that stems from the same issue.

With gdal 3.1.1, the call fails:
```
(ariaMintpy) [ssangha@leffe incidenceAngle]$ python3
Python 3.8.5 | packaged by conda-forge | (default, Jul 31 2020, 02:39:48) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from osgeo import gdal
>>> 
>>> outname='20181210_20181204'
>>> gdal.Warp(outname, outname, options=gdal.WarpOptions(format='ISCE', options=['-overwrite']))
ERROR 3: Failed to read scanline 0.
ERROR 1: 20181210_20181204, band 1: IReadBlock failed at X offset 0, Y offset 0: Failed to read scanline 0.
```

With gdal 3.0.4, gdalWarp works fine:
```
(ARIA-tools) [ssangha@leffe incidenceAngle]$ python3
Python 3.8.5 | packaged by conda-forge | (default, Jul 24 2020, 01:25:15) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from osgeo import gdal
>>> 
>>> outname='20181210_20181204'
>>> 
>>> gdal.Warp(outname, outname, options=gdal.WarpOptions(format='ISCE', options=['-overwrite']))
<osgeo.gdal.Dataset; proxy of <Swig Object of type 'GDALDatasetShadow *' at 0x7f3167b1b4e0> >
```

## Operating system

CentOS Linux 7.6.1810 64 bit

## GDAL version and provenance

3.1.1 version from anaconda (https://anaconda.org/conda-forge/libgdal)

[test_files.zip](https://github.com/OSGeo/gdal/files/5095172/test_files.zip)

**Comment by rouault** [comment]
> gdal.Warp(outname, outname,

You cannot warp a file onto itself. That it might have worked in previous versions is a pure matter of luck
