### ISSUE TITLE
ContourGenerate function creating Python type error

### ISSUE THREAD

**Issue by Parth38** [OSGeo/gdal#2875]
## Expected behavior and actual behavior.
I am trying to generate contours from a TIF file
While running gdal function ContourGenerate creating Python Type Error

## Steps to reproduce the problem.

gdal_data = gdal.Open(tif_file)
gdal_band = gdal_data.GetRasterBand(3)

import osgeo.osr as osr

srs = osr.SpatialReference(gdal_data.GetProjection())
srs.ImportFromEPSG(4326)

#Creating new shapefile
# set up the shapefile driver
driver = ogr.GetDriverByName("ESRI Shapefile")

# create the data source
data_source = driver.CreateDataSource("cont_9200.shp")

# create the layer
layer = data_source.CreateLayer("contours", srs)

#adding fields
field_defn = ogr.FieldDefn("ID", ogr.OFTInteger)
layer.CreateField(field_defn)
field_defn = ogr.FieldDefn("ELEV", ogr.OFTInteger64)
layer.CreateField(field_defn)

#Generating contour
 layer=gdal.ContourGenerate(gdal_band,contourInterval=10,contourBase=10,fixedLevelCount=0,useNoData=0,noDataValue=0,dstLayer=layer,idField=0,elevField=1) 

##Output
TypeError                                 Traceback (most recent call last)

<ipython-input-32-600be350ded0> in <module>()
      1 #Generating contour
----> 2 layer=gdal.ContourGenerate(gdal_band,contourInterval=10,contourBase=10,fixedLevelCount=0,useNoData=0,noDataValue=0,dstLayer=layer,idField=0,elevField=1)

/usr/lib/python3/dist-packages/osgeo/gdal.py in ContourGenerate(*args, **kwargs)
   2857 def ContourGenerate(*args, **kwargs):
   2858     """ContourGenerate(Band srcBand, double contourInterval, double contourBase, int fixedLevelCount, int useNoData, double noDataValue, Layer dstLayer, int idField, int elevField, GDALProgressFunc callback=0, void * callback_data=None) -> int"""
-> 2859     return _gdal.ContourGenerate(*args, **kwargs)
   2860 
   2861 def AutoCreateWarpedVRT(*args):

TypeError: not a sequence

## Operating system

running on google colab
## GDAL version and provenance

running on google colab

**Comment by rouault** [comment]
See https://github.com/OSGeo/gdal/blob/master/autotest/alg/contour.py for examples
