### ISSUE TITLE
GDAL 2.x bug with spatial predicate consistently returns -1 on Mac OS X

### ISSUE THREAD

**Issue by migurski** [OSGeo/gdal#2886]
## Expected behavior and actual behavior.

I am attempting a spatial join between a polygon layer and a point layer, looking for points contained within polygons with `ST_Contains()`. The integer return value is consistently -1 indicating a NULL input, but I know this is not the case. I had been testing this on a Mac running OS X 10.14.6 with GDAL 2.4.2, so I re-attempted on Ubuntu 18.04 with GDAL 2.2.3 which worked as-expected.

I’ve reduced the problem to a minimal pair of single-feature layers, [one-tl_2018_39.gpkg](https://github.com/OSGeo/gdal/files/5119556/one-tl_2018_39.gpkg.zip).

## Steps to reproduce the problem.

Apply this SQL to the [attached Geopackage](https://github.com/OSGeo/gdal/files/5119556/one-tl_2018_39.gpkg.zip) using ogr2ogr with `ogr2ogr -f GPKG -sql @blocks_2018.sql one-tl_2018_39.gpkg one-tl_2018_39.gpkg`:

```SQL
select
    B.geom, B.block_geoid, B.block_area,
    P.prec_elec, P.prec_county_name,
    ST_Intersects(B.geom, P.geom) AS prec_intersects,
    ST_Within(B.geom, P.geom) AS prec_within,
    ST_Contains(P.geom, B.geom) AS prec_contains,
    ST_Disjoint(P.geom, B.geom) AS prec_disjoint,
    ST_SRID(B.geom) AS block_srid,
    ST_SRID(P.geom) AS prec_srid,
    ST_Area(P.geom) AS prec_area,
    ST_GeometryType(P.geom) AS prec_type,
    ST_IsEmpty(P.geom) AS prec_empty,
    ST_IsValid(P.geom) AS prec_valid,
    SUBSTR(ST_AsText(P.geom), 1, 32)||'...' AS prec_wkt,
    Length(P.geom) AS prec_len,
    ST_Envelope(P.geom) AS prec_envelope,
    ST_AsText(ST_Envelope(P.geom)) AS prec_envelope_wkt,
    CAST(P.fid AS number) as prec_fid,
    CAST(B.fid AS number) as block_fid,
    ST_AsText(B.geom) AS block_wkt,
    ST_Envelope(B.geom) AS block_envelope,
    spatialite_version() as spatialite_version,
    proj4_version() as proj4_version,
    geos_version() as geos_version
from tabblock AS B
left join precincts_2016 AS P
```

### Expected Result

Running on Ubuntu 18.04 with GDAL 2.2.3 shows the expected result row:

    block_geoid (String) = 10100US390351413001002
    block_area (Integer64) = 72298
    prec_elec (String) = CLEVELAND HEIGHTS-01-A
    prec_county_name (String) = cuyahoga
    prec_intersects (Integer) = 1
    prec_within (Integer) = 1
    prec_contains (Integer) = 1
    prec_disjoint (Integer) = 0
    block_srid (Integer) = 4269
    prec_srid (Integer) = 4269
    prec_area (Real) = 5.28431531600598e-05
    prec_type (String) = MULTIPOLYGON
    prec_empty (Integer) = 0
    prec_valid (Integer) = 1
    prec_wkt (String) = MULTIPOLYGON(((-81.594515 41.494...
    prec_len (Integer) = 1262
    prec_envelope (Binary) = 0001AD10000064797B219C6654C01FB62A2746BF4440206675870C6654C09A1782912CC0...
    prec_envelope_wkt (String) = POLYGON((-81.603279 41.494328, -81.594515 41.494328, -81.594515 41.50136, -81.603279 41.50136, -81.603279 41.494328))
    prec_fid (Integer) = 2785
    block_fid (Integer) = 330613
    block_wkt (String) = POINT(-81.595175 41.498061)
    block_envelope (Binary) = 0001AD100000FAD8B859176654C009B42A78C0BF4440FAD8B859176654C009B42A78C0BF...
    spatialite_version (String) = 4.3.0a
    proj4_version (String) = Rel. 4.9.3, 15 August 2016
    geos_version (String) = 3.6.2-CAPI-1.10.2 4d2925d6
    POINT (-81.5951752 41.4980612)

### Actual Result

Running on OS X 10.14.6 with GDAL 2.4.2 shows this incorrect result row with missing data from the precincts layer:

    block_geoid (String) = 10100US390351413001002
    block_area (Integer64) = 72298
    prec_elec (String) = CLEVELAND HEIGHTS-01-A
    prec_county_name (String) = cuyahoga
    prec_intersects (Integer) = -1
    prec_within (Integer) = -1
    prec_contains (Integer) = -1
    prec_disjoint (Integer) = -1
    block_srid (Integer) = 4269
    prec_srid (Integer) = 4269
    prec_area (String) = (null)
    prec_type (String) = MULTIPOLYGON
    prec_empty (Integer) = 0
    prec_valid (Integer) = -1
    prec_wkt (String) = (null)
    prec_len (Integer) = 1262
    prec_envelope (String) = (null)
    prec_envelope_wkt (String) = (null)
    prec_fid (Integer) = 2785
    block_fid (Integer) = 330613
    block_wkt (String) = (null)
    block_envelope (String) = (null)
    spatialite_version (String) = 4.4.0-RC1
    proj4_version (String) = Rel. 5.2.0, September 15th, 2018
    geos_version (String) = 3.7.2-CAPI-1.11.2 b55d2125
    POINT (-81.5951752 41.4980612)

## Operating system

OS X 10.14.6

## GDAL version and provenance

GDAL 2.4.2, installed with a package download to `/Library/Frameworks/GDAL.framework`

**Comment by rouault** [comment]
I'm not sure where the error is, but anyway GDAL 2.x is no longer maintained, so unless you can reproduce with GDAL 3.1, I'm closing this ticket

**Comment by migurski** [comment]
I was unable to reproduce this bug with the GDAL 3.1 currently distributed by Kyngchaos.
