### ISSUE TITLE
gdal2tiles fails when the input raster is very small (7x8)

### ISSUE THREAD

**Issue by Nodjo** [OSGeo/gdal#2896]
I want to export tiles from a very small raster (7x8) and the tiles are all transparent.

I found out that if I translate the raster to increase its size (say give it a width of 100), then the output is as expected.

Here's my code (I'm using gdal2tiles python bindings but I've also reproduced this issue with multiple versions of gdal2tiles.py)

gdal2tiles.generate_tiles(in_raster_path, out_dir, zoom='12-24')

I'm attaching the raster file
[bug_gdal2tiles.zip](https://github.com/OSGeo/gdal/files/5142262/bug_gdal2tiles.zip)

**Comment by rouault** [comment]
Note: I've pushed a fix, but the quality of the result will be far from optimal. As overview tiles are computed from the ones at the previous zoom level (ie level 12 is generated from level 13, ... level 23 from level 24), and level 24 is incredibly zooming in the base raster, the lower zoom levels are of a lesser quality than they would be from being directly generated. A potential strategy might be to generate lower zoom levels afterwards.
