### ISSUE TITLE
GPKG driver: wrong format on writing for datetime when ISO 8601 with UTC offset

### ISSUE THREAD

**Issue by heidivanparys** [OSGeo/gdal#2898]
## Expected behavior and actual behavior.

The GPKG driver recognizes datetimes that have a UTC offset and are formatted according to ISO 8601, but does not write them correctly again on conversion to another GPKG file.

## Steps to reproduce the problem.

I have the following table in a GeoPackage, `mydata.gpkg`:

```sql
CREATE TABLE "myfeaturetype" (
  "_id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  "mydatetime" DATETIME NOT NULL,
  "location" POINT,
  "label" TEXT NOT NULL
);
```
It contains the datetimes `2020-08-18T09:02:00Z` and `2020-08-18T11:02:00+02:00`:

```
ogrinfo mydata.gpkg -sql "select cast(mydatetime as text) as mydatetime_as_text from myfeaturetype"
INFO: Open of `mydata.gpkg'
      using driver `GPKG' successful.

Layer name: SELECT
Geometry: None
Feature Count: 2
Layer SRS WKT:
(unknown)
mydatetime_as_text: String (0.0)
OGRFeature(SELECT):0
  mydatetime_as_text (String) = 2020-08-18T09:02:00Z

OGRFeature(SELECT):1
  mydatetime_as_text (String) = 2020-08-18T11:02:00+02:00
```

When I create a new GeoPackage `mydata_ogr2ogr.gpkg` (a possible use case could be a change of coordinate reference system, omitted in this example):

```
ogr2ogr -f GPKG mydata_ogr2ogr.gpkg mydata.gpkg myfeaturetype
```

`mydata_ogr2ogr.gpkg` contains the datetimes `2020-08-18T09:02:00Z` and `2020/08/18 11:02:00+02`:

```
ogrinfo mydata_ogr2ogr.gpkg -sql "select cast(mydatetime as text) as mydatetime_as_text from myfeaturetype"
INFO: Open of `mydata_ogr2ogr.gpkg'
      using driver `GPKG' successful.

Layer name: SELECT
Geometry: None
Feature Count: 2
Layer SRS WKT:
(unknown)
mydatetime_as_text: String (0.0)
OGRFeature(SELECT):0
  mydatetime_as_text (String) = 2020-08-18T09:02:00Z

OGRFeature(SELECT):1
  mydatetime_as_text (String) = 2020/08/18 11:02:00+02
```

So the UTC time is correct, but the datetime that had a UTC offset is formatted incorrectly. That is also reported in a warning (9917ae7d7d11f9d2ba0438853ca81298d803c6fa) when showing info for the whole layer:

```
ogrinfo -q mydata_ogr2ogr.gpkg myfeaturetype

Layer name: myfeaturetype
OGRFeature(myfeaturetype):1
  mydatetime (DateTime) = 2020/08/18 09:02:00+00
  label (String) = UTC time
  POINT (722125 6178892)

Warning 1: Non-conformant content for record 2 in column mydatetime, 2020/08/18 11:02:00+02, successfully parsed
OGRFeature(myfeaturetype):2
  mydatetime (DateTime) = 2020/08/18 11:02:00+02
  label (String) = time with time zone
  POINT (722130 6178892)
```

## GDAL version and provenance

GDAL 3.2.0dev (installed via OsGeo4W).

**Comment by rouault** [comment]
I see you discussed this in https://github.com/opengeospatial/geopackage/issues/530
I'm not sure of the best resolution:
- either we extend a bit the current GeoPackage spec and allow ISO-8601 datetime with timezone
- or we 'convert' the datetime to the UTC timezone

**Comment by heidivanparys** [comment]
How about a pragmatic solution and turning it into a "feature" of the driver? E.g. adding a dataset creation option that allows to choose whether to convert to UTC? Something like

DATE_TIME_EXPRESSIONS=UNCHANGED/UTC: Defines whether to keep the date and time expressions in the time zones as used in the data source, or to convert the date and time expressions to UTC (Coordinated Universal Time). Defaults to UNCHANGED.

A note should be probably added on date and time expressions without time zone information in the source data. As far as I can see, there are assumed to be UTC (provided that the driver used for the source data recognizes those fields as containing date and time expressions).

**Comment by rouault** [comment]
> How about a pragmatic solution and turning it into a "feature" of the driver?

Good suggestion. See https://github.com/OSGeo/gdal/pull/2902. I've decided for different names for the option name and its values

**Comment by heidivanparys** [comment]
> Good suggestion. See #2902. I've decided for different names for the option name and its values

Great, thanks!

**Comment by jratike80** [comment]
> A note should be probably added on date and time expressions without time zone information in the source data. As far as I can see, there are assumed to be UTC

By the ISO standard they mean local time https://en.wikipedia.org/wiki/ISO_8601 and I believe that in most cases if I see such times in Finnish datasets they really mean "our time" as it was in a clock (UTC+2 or +3 if it was summer). I also believe that most users somehow await that the hours do not change 01 today into 23 yesterday when they convert data into GeoPackage, even it is wrong to the letter of the standard so assuming UTC is probably right in practise, though wrong in theory. 

From the code of the commit I am not sure how time '2020/01/01T01:34:56.789+02' gets stored into GeoPackage if the format is WITH_TZ.

**Comment by rouault** [comment]
> From the code of the commit I am not sure how time '2020/01/01T01:34:56.789+02' gets stored into GeoPackage if the format is WITH_TZ.

It will be stored losslessly, as  '2020-01-01T01:34:56.789+02:00'
