### ISSUE TITLE
GetProjection() causes:    ERROR 1: PROJ: proj_create_geographic_crs: SQLite error on SELECT name

### ISSUE THREAD

**Issue by Arking1995** [OSGeo/gdal#2900]
Hi,

I install GDAL long time ago and it worked well. Recently I installed osmnx and its all pre-requisite libraries, including geopandas, fiona, pyproj, shapely, six, rtree. Now when I use GDAL with .GetProjection(), it returns this bug info:

ERROR 1: PROJ: proj_create_geographic_crs: SQLite error on SELECT name, ellipsoid_auth_name, ellipsoid_code, prime_meridian_auth_name, prime_meridian_code, area_of_use_auth_name, area_of_use_code, publication_date, deprecated FROM geodetic_datum WHERE auth_name = ? AND code = ?: no such column: publication_date

Do you have any idea about what happened? Thank you!

**Comment by rouault** [comment]
You are using a PROJ version different than the version of the proj.db it tries to open. Probably some of the mix of libraries is setting PROJ_LIB to point to an installation, but the runtime library used is pointing to another one.

**Comment by Arking1995** [comment]
Thanks very much for your help! Would you know some simple way that we can setup the PROJ_LIB at running time?
