### ISSUE TITLE
Java bindings don't build against a native library built --without-gnm

### ISSUE THREAD

**Issue by adamjstewart** [OSGeo/gdal#2918]
## Expected behavior and actual behavior.

I'm trying to build GDAL with Java support but it crashes during compilation:
```
Undefined symbols for architecture x86_64:
  "_GNMChangeAllBlockState", referenced from:
      _Java_org_gdal_gnm_gnmJNI_GenericNetwork_1ChangeAllBlockState_1_1SWIG_10 in gnm_wrap.o
      _Java_org_gdal_gnm_gnmJNI_GenericNetwork_1ChangeAllBlockState_1_1SWIG_11 in gnm_wrap.o
  "_GNMChangeBlockState", referenced from:
      _Java_org_gdal_gnm_gnmJNI_GenericNetwork_1ChangeBlockState in gnm_wrap.o
  "_GNMConnectFeatures", referenced from:
      _Java_org_gdal_gnm_gnmJNI_GenericNetwork_1ConnectFeatures in gnm_wrap.o
  "_GNMConnectPointsByLines", referenced from:
      _Java_org_gdal_gnm_gnmJNI_GenericNetwork_1ConnectPointsByLines in gnm_wrap.o
  "_GNMCreateRule", referenced from:
      _Java_org_gdal_gnm_gnmJNI_GenericNetwork_1CreateRule in gnm_wrap.o
  "_GNMDeleteAllRules", referenced from:
      _Java_org_gdal_gnm_gnmJNI_GenericNetwork_1DeleteAllRules in gnm_wrap.o
  "_GNMDeleteRule", referenced from:
      _Java_org_gdal_gnm_gnmJNI_GenericNetwork_1DeleteRule in gnm_wrap.o
  "_GNMDisconnectAll", referenced from:
      _Java_org_gdal_gnm_gnmJNI_Network_1DisconnectAll in gnm_wrap.o
  "_GNMDisconnectFeatures", referenced from:
      _Java_org_gdal_gnm_gnmJNI_GenericNetwork_1DisconnectFeatures in gnm_wrap.o
  "_GNMDisconnectFeaturesWithId", referenced from:
      _Java_org_gdal_gnm_gnmJNI_GenericNetwork_1DisconnectFeaturesWithId in gnm_wrap.o
  "_GNMGetFeatureByGlobalFID", referenced from:
      _Java_org_gdal_gnm_gnmJNI_Network_1GetFeatureByGlobalFID in gnm_wrap.o
  "_GNMGetName", referenced from:
      _Java_org_gdal_gnm_gnmJNI_Network_1GetName in gnm_wrap.o
  "_GNMGetPath", referenced from:
      _Java_org_gdal_gnm_gnmJNI_Network_1GetPath_1_1SWIG_10 in gnm_wrap.o
      _Java_org_gdal_gnm_gnmJNI_Network_1GetPath_1_1SWIG_11 in gnm_wrap.o
  "_GNMGetRules", referenced from:
      _Java_org_gdal_gnm_gnmJNI_GenericNetwork_1GetRules in gnm_wrap.o
  "_GNMGetVersion", referenced from:
      _Java_org_gdal_gnm_gnmJNI_Network_1GetVersion in gnm_wrap.o
  "_GNMReconnectFeatures", referenced from:
      _Java_org_gdal_gnm_gnmJNI_GenericNetwork_1ReconnectFeatures in gnm_wrap.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [GNUmakefile:108: libgdalalljni.la] Error 1
```
I would expect the instructions at https://trac.osgeo.org/gdal/wiki/GdalOgrInJavaBuildInstructionsUnix to work on macOS without an error.

## Steps to reproduce the problem.

```console
$ ./configure --with-java=... --with-jvm-lib=... --with-jvm-lib-add-rpath
$ make -j4
$ cd swig/java
$ sed -i .bkp 's/linux/darwin/' java.opt
$ make -j4
```
## Operating system

macOS 10.15.6 64 bit, Apple Clang 11.0.3

## GDAL version and provenance

GDAL 3.1.2, Oracle JDK 12.0.1, [Spack](https://spack.io/) package manager

## Additional Information

Here are the build logs:

* [build log](https://github.com/OSGeo/gdal/files/5171655/spack-build-out.txt)
* [build env](https://github.com/OSGeo/gdal/files/5171658/spack-build-env.txt)

Let me know if I can provide you with any additional debugging information.

**Comment by adamjstewart** [comment]
Tried again with GDAL 3.1.3 and tried removing the `--with-jvm-lib-add-rpath` flag but it didn't help, same error message.

**Comment by adamjstewart** [comment]
I tried again with Oracle JDK 10.0.1_10 and 1.8.0_231-b11 on macOS but still got the same error message. Another user tried with Oracle JDK 12.0.2_10 and 1.8.0_241 on CentOS 7. For them, JDK 8 worked but JDK 12 didn't.

**Comment by adamjstewart** [comment]
It looks like @rouault was the last person to modify the `swig/java` directory.

**Comment by rouault** [comment]
> It looks like @rouault was the last person to modify the `swig/java` directory.

Don't have a Mac, so can't really help.
'd suggest editing swig/java/java.opt to tune the path to JDK rather than using ./configure switches that are made for drivers that depend on the JDK. Two separate Java uses in GDAL. A bit confusing probably

**Comment by adamjstewart** [comment]
@rouault thanks for the suggestion. I did change `linux` to `darwin` in the `java.opt` file. Other than that, all of the paths look correct:
```console
$ echo $JAVA_HOME
/Library/Java/JavaVirtualMachines/jdk-12.0.1.jdk/Contents/Home
$ ls $JAVA_HOME/bin
jaotc		javac		jconsole	jfr		jjs		jps		jstat		rmic		unpack200
jar		javadoc		jdb		jhsdb		jlink		jrunscript	jstatd		rmid
jarsigner	javap		jdeprscan	jimage		jmap		jshell		keytool		rmiregistry
java		jcmd		jdeps		jinfo		jmod		jstack		pack200		serialver
$ ls $JAVA_HOME/include
classfile_constants.h	darwin			jawt.h			jdwpTransport.h		jni.h			jvmti.h			jvmticmlr.h
$ ls $JAVA_HOME/include/darwin
jawt_md.h	jni_md.h
```
This is for JDK 12, the directory structure for JDK 8 appears to be the same.

**Comment by hococoder** [comment]
@adamjstewart did you ever find a fix for this?  I'm running into the same problem.

**Comment by adamjstewart** [comment]
Hi @hococoder, unfortunately not, I just tried again with GDAL 3.3.2 on macOS 10.15.7 with Apple Clang 12.0.0 and Java 1.8.0 and I still get the same error. It seems like the Java driver isn't supported on macOS...

**Comment by hococoder** [comment]
I did get it to compile by leaving out --without-gnm in my configure, if that helps you at all!

**Comment by rouault** [comment]
oh I see the config.log includes --without-gnm when building the native library. The Java bindings makefile isn't ready for that non standard configuration. I guess the other bindings wouldn't like that too.
Not sure about the resolution: removing the --without-gnm switch is propably simpler than making the bindings makefile adapt to the without-gnm situation
Defering until we switch to cmake

**Comment by hococoder** [comment]
I hope I can ask one more question that is at least tangential to this discussion (java bindings) - is there a way to have the dylib not have absolute path pointers?  I'm looking to make a set of jars/dylibs that are portable, so I don't want it pointing to directories on my system (so others can use them).  I think in this case I would handle it with DYLD_LIBRARY_PATH.  Thanks.

**Comment by adamjstewart** [comment]
@hococoder I assume that's what the `--with-jvm-lib-add-rpath` flag is doing? If you don't use that then you should be good to go. Within Spack, we kind of have to use that.

**Comment by adamjstewart** [comment]
@rouault good catch! Removing that flag from Spack's build recipe solved the issue for me. I'll submit a PR to do that.

If you notice any other non-standard config options in our Spack package let me know! Our goal is to disable drivers that pull in external dependencies to prevent non-deterministic behavior where two installations with the same configuration result in different executables. For things like `gnm` that don't involve external deps, we're completely fine with using the defaults.

**Comment by hococoder** [comment]
@adamjstewart I'm not using that flag - I actually got a warning from configure that it was invalid (?).  I'm also trying to (and I have no idea if this will work) build everything on the java side as statically as I can, because we want to include cfitsio functionality, but don't want to have the user install that on their system.  If you'd got any insights into this I'd love to hear them.

**Comment by rouault** [comment]
closing as configure has been removed and replaced by cmake
