### ISSUE TITLE
Extreme memory utilization with ECW driver and SDK version 5.5

### ISSUE THREAD

**Issue by sgillies** [OSGeo/gdal#2926]
## Expected behavior and actual behavior.

gdal_translate of a large ECW to GTiff should use a little more than 5% of a computer's memory. I've run gdal_translate (version 3.1.0) to convert a very large 9.6 GB GTiff to another GTiff and the maximum memory utilization was 6.2%. 5 of this is the raster band cache. I would expect ECW conversion to not use much more memory.

What I observe is that gdal_translate 3.1.0 built with the ECW SDK version 5.5 uses all the available memory on my computer to translate a 600 MB ECW to a 9.6 GB tiled GTiff and thus creeps to completion.

## Steps to reproduce the problem.

`gdal_translate -of GTiff -co TILED=YES attached.ecw /tmp/output.tif`

## Operating system

Ubuntu 18.04

## GDAL version and provenance

3.1.0 build from source release and ECWJP2 SDK 5.5.0.1640. I have also observed this on another system using GDAL 3.1.2.

**Comment by rouault** [comment]
Have you tried to specify the ECW_CACHE_MAXMEM config option (https://gdal.org/drivers/raster/ecw.html). Looking at the driver, this should not be more than 2 billion (bytes) to avoid overflow ?
Have you tested with earlier SDK releases ?

**Comment by sgillies** [comment]
TIL! Yes, that's the ticket @rouault . Thank you.

Is the raster band cache used when reading an ECW? Why are there different cache configurations?

**Comment by rouault** [comment]
> TIL! Yes, that's the ticket @rouault . Thank you.

OK, so if you don't specify ECW_CACHE_MAXMEM, all RAM is taken. Looks like a bug of the SDK if so ? CC @jbowman-hexagon 

> Is the raster band cache used when reading an ECW?

Yes, the GDAL raster band cache might possibly be used, depending on which requests are done to the driver

> Why are there different cache configurations?

Do you mean ECW_CACHE_MAXMEM in addition to the GDAL cache ? Well, ECW_CACHE_MAXMEM is a SDK specific one. For JPEG2000, I guess this might be used to store JPEG2000 code blocks. And for ECW, perhaps similar concepts, but who knows, this is closed format & code.

**Comment by sgillies** [comment]
Well, on my computer, gdal_translate of the ECW was utilizing 32% of my memory. That's roughly equal to 25% for ECW plus 5% for the band cache, so I don't think there's necessarily a leak. I can confirm that the ECW config option does cap the memory utilization.

**Comment by jbowman-hexagon** [comment]
Hi @sgillies . This is expected behaviour. If the ECW_CACHE_MAXMEM option is NOT specified, by default, the ECW SDK will limit itself to 25% of total memory. So this agrees with the observations in your last comment. As you discovered you can limit the usage by setting the env var's value, in  bytes.
