### ISSUE TITLE
Artifacts when warping continuous valued image with nearest neighbor resampling

### ISSUE THREAD

**Issue by pblankenau2** [OSGeo/gdal#2927]
## Expected behavior and actual behavior.

The expected behavior is to have gdalwarp produce an artifact free image using the nearest neighbor resampling scheme on continuous data.

The actual behavior is that gdalwarp produces artifacts when warping a continuous value image using the nearest neighbor resampling scheme.

A Landsat band in EPSG:32612 reprojected to ESRI:102003:

![image](https://user-images.githubusercontent.com/13680523/92504457-ef0ee600-f1bf-11ea-94af-b418da6b5d3b.png)

## Steps to reproduce the problem.

gdalwarp -t_srs ESRI:102003 -r near -of GTiff <path to gtiff>LC08_L1TP_040029_20200407_20200410_01_T1_B10.TIF <path to output>OUTPUT.tif

## Operating system

Windows 10 Pro Version 1909

## GDAL version and provenance

gdal                      3.0.4            py38h3ba59e7_9    conda-forge
libgdal                  3.0.4                h6f60a84_9    conda-forge

**Comment by rouault** [comment]
This might not be completely unexpected given the nature of nearest resampling. If the data is of continuous nature, you'll be better using non-nearest resampling.

**Comment by pblankenau2** [comment]
My goal with using nearest neighbor was to preserve the original range of the data.  I should note that reprojecting using ArcGIS does not result in the artifact seen above.  Could this be due to the way GDAL is chunking the data during warping?

**Comment by rouault** [comment]
Please attach a link to the source dataset

**Comment by pblankenau2** [comment]
It turns out that ArcGIS actually does produce a similar artifact, so ignore my previous claim.

Here is the data: https://drive.google.com/file/d/1YxKxw-feEJ009QCzjv6fQMbeVy29fpPe/view?usp=sharing

**Comment by rouault** [comment]
Those artifacts are only visible if you zoom in significantly beyond 100% resolution, which indicates that they are sub-pixel artifacts, which is expected given the nature of nearest resampling. Only more advanced resampling (bilinear, bicubic, etc.) can produce a nice looking image beyond 100% zoom. Nearest shouldn't be used for continuous data. See https://gis.stackexchange.com/questions/121646/what-resampling-technique-should-be-used-to-reproject-an-altitude-raster
