### ISSUE TITLE
HDF5 driver: add support for new "CSK 2nd generation" (CSG)

### ISSUE THREAD

**Issue by FilipGh** [OSGeo/gdal#2930]
## Expected behavior and actual behavior.
CSK 2nd generation images come with a new **_Mission ID_** value: **CSG**
There is some ad hoc code to deal with CSK complex type images

## Steps to reproduce the problem.
gdalinfo does not interpret the number of bands correctly.

## Operating system
It is not OS dependent

## GDAL version and provenance
GDAM V3.0.2

## Proposed patch
Add a 3rd value to check the "special case "
<pre>
// Check if the mission type is CSK, KMPS or CSG.
// KMPS: Komsat-5 is Korean mission with a SAR instrument.
// CSG: Cosmo Skymed 2nd Generation
if(EQUAL(pszMissionId, "CSK") || EQUAL(pszMissionId, "KMPS")
                              || EQUAL(pszMissionId, "CSG"))
{
</pre>

[hdf5imagedataset.cpp.patch.txt](https://github.com/OSGeo/gdal/files/5203016/hdf5imagedataset.cpp.patch.txt)

**Comment by rouault** [comment]
Do you have links to such datasets ?

**Comment by FilipGh** [comment]
Airbus Amber
Dear Evan,

I am afraid I cannot share such datasets.
I received it from one of our customer. I tried to find some more data samples on the internet, with no success.

Sincerely
Philippe




THIS DOCUMENT IS NOT SUBJECT TO EXPORT CONTROL.

**Comment by piyushrpt** [comment]
Would this be an opportunity to pull CSK into its own driver? The HDF5 driver already seems pretty cluttered and more if-else statements for CSK makes it harder to work with.
