### ISSUE TITLE
WMTS: local files do not accept ZeroBlockHttpCodes

### ISSUE THREAD

**Issue by janosimas** [OSGeo/gdal#2941]
## Expected behavior and actual behavior.

I'm consuming a local WMTS server structure, for some technical reasons some tiles may be missing.

Local WMTS with missing tiles will generate and error and a blank image.
I expected it to  behave like online WMTS, an image with missing areas.

## Steps to reproduce the problem.

Draw a local WMTS with missing tiles.

## Operating system

The problem is system independent

## GDAL version and provenance

Build from source 2.4.0

## Proposed solution

From the documentation, I understand the `ZeroBlockHttpCodes` is used in this cases, eg.: 404 - file not found in a online server.

But for local files, `curl` does not set a Http Response code, currently gdal already goes around it and when no error message is set, [it sets the response code to 200](https://github.com/OSGeo/gdal/blob/master/gdal/frmts/wms/gdalhttp.cpp#L224).

A solution would be map the curl error `CURLE_FILE_COULDNT_READ_FILE` to a gdal reponse code `404`.

*In case we agree upon the solution I plan to make a pull request to the current version.*

**Comment by rouault** [comment]
> A solution would be map the curl error `CURLE_FILE_COULDNT_READ_FILE` to a gdal reponse code `404`.

Sounds good. Pull request welcome

**Comment by gladijos** [comment]
same issue I got on TMS local files. When gdal try access to unexisted files  in log I got 
"HTTP status code: 0, error: <url> malformed."
