### ISSUE TITLE
gdal2tiles input pdf multiple processes ignoring --config DPI parameter

### ISSUE THREAD

**Issue by py-qgis-user** [OSGeo/gdal#2950]
Not sure if this belongs in the gdal-dev mailing list or here

## Expected behavior and actual behavior.
I'm using gdal2tiles to transform a georeferenced pdf to map tiles.
To increase the output tile quality, I used the [pdf driver option](https://gdal.org/drivers/raster/pdf.html) --config GDAL_PDF_DPI  1200
When running with 1 process (run 1 below), the quality of the tiles is excellent
When trying to run with multiple processes (run 2 below), the quality of the created files is similar to running it without the --config option.

Might not be a bug, but just a missing feature

## Steps to reproduce the problem.

Input: any vector-based PDF
Run 1 cmd:
gdal2tiles -r antialias -a 255 input.pdf test1 --config GDAL_PDF_DPI 1200
Run 2 cmd:
gdal2tiles -r antialias -a 255 --processes=4 input.pdf test2 --config GDAL_PDF_DPI 1200

## Operating system

Windows 10 64 bit

## GDAL version and provenance
GDAL 2.4.0
gdal2tiles $Id: gdal2tiles.py 1f32f6fdbfd2fd352047db41d316d8afbe3c3319 2018-11-30 01:05:06 +0100 Even Rouault $

With GDAL 3.1.2 similar issues are encountered. Instead of generating tiles at default DPI, only the size of the original DPI-pdf contains content. (E.g.: for a pdf with size 100x100 at default dpi, at double the DPI it'll create tiles for a georeferenced PDF at size 200x200, but only the top-left 100x100 contains content, the other has nodata value).

**Comment by rouault** [comment]
Fixed per c844925163e58df4b0faa2befa26434c19c04e07

An easy workaround is to specify the configuration option as an environment variable before invoking gdal2tiles

**Comment by py-qgis-user** [comment]
Fabulous, tested in 3.1.2 and works great!
