### ISSUE TITLE
gdal/docker - multi os/arch support, registry/image overrides

### ISSUE THREAD

**Issue by awill1988** [OSGeo/gdal#2959]
## Expected behavior and actual behavior.

1. I expected to be able to run `docker pull osgeo/gdal:latest` and run it in a raspberry pi. However, the only supported OS/ARCH is `linux/amd64` as indicated [on Docker Hub](https://hub.docker.com/r/osgeo/gdal/tags).

2. Additionally, looking at the shell scripts, you cannot provide your own registry/image location. This would be helpful for those seeking to independently build and host their own gdal container.

## Steps to reproduce the problem.

1. Setup docker on a RPi, open a terminal and run `docker run osgeo/gdal:latest`
2. Attempt to run `gdal/docker/alpine-small/build.sh` to build and push, you will see that the BASE_IMAGE_NAME is not dynamic.

## Operating system

1. `Linux k8s-master-0 5.4.0-1018-raspi #20-Ubuntu SMP Sun Sep 6 05:11:16 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux`
2. N/A

## GDAL version and provenance

(latest)

**Comment by rouault** [comment]
I think I'm going to close this as a wontfix. I don't have the build infrastructure to build for a Raspberry Pi. If you can provide modification to the Dockerfile itself as a pull request to be more configurable, please do it, but you'll have to Docker build it yourself.

**Comment by awill1988** [comment]
Thanks @rouault for being proactive and prompt in handling of this. I probably should have mentioned or waited until my PR was ready, but I do intend to submit a request to update the build scripts that should satisfy all these features without breaking anything you guys are doing today. It will presume that the end-user will have `docker buildx` operational.

Just waiting for the water to boil (takes forever) and to make sure my changes successfully build the `linux/arm64` os/arch before I commit and initiate the PR. Should I link this issue to it?

**Comment by rouault** [comment]
ok, great. re-opening this ticket until you sumit the PR

**Comment by rouault** [comment]
Implemented per https://github.com/OSGeo/gdal/pull/2965
