### ISSUE TITLE
Java binding in docker image

### ISSUE THREAD

**Issue by exotfboy** [OSGeo/gdal#2967]
There are 5 docker images provided. But none of them contains java building.

Is it possible to add this to the plan?

**Comment by jratike80** [comment]
When you opened this ticket you should have seen this notice

```
<!--
IMPORTANT: Do NOT use GitHub to post any questions or support requests!
           They will be closed immediately and ignored.

Questions should go to the gdal-dev mailing list at
https://lists.osgeo.org/mailman/listinfo/gdal-dev
or other support forums. GitHub issues are for bug
reports and suggestions for new features.
```

**Comment by exotfboy** [comment]
Yes, I saw that, and I also saw this:

>GitHub issues are for bug reports and **suggestions for new features**.

**Comment by jratike80** [comment]
Right, I was reading your message as a question.
Can you suggest in which image that would fit best?

**Comment by exotfboy** [comment]
I am not sure. Different application may have different requirements.

Maybe an extra tag for each like `osgeo/gdal:alpine-small-jdk8:latest`?

While maybe people need different jdk version.  OMG :(
