### ISSUE TITLE
GDAL 3.1.3 build error on MacOS 10.15.7

### ISSUE THREAD

**Issue by filislav** [OSGeo/gdal#2981]
## Expected behavior and actual behavior.

When i do make in gdal-3.1.3 on MacOS 10.15.7 i have next message about error:

jpeg2000_vsil_io.cpp:151:5: error: cannot initialize a member subobject of type
      'int (*)(jas_stream_obj_t *, const char *, unsigned int)' (aka 'int
      (*)(void *, const char *, unsigned int)') with an lvalue of type 'int
      (jas_stream_obj_t *, char *, unsigned int)' (aka 'int (void *, char *,
      unsigned int)'): type mismatch at 2nd parameter ('const char *' vs
      'char *')
    JPEG2000_VSIL_write,
    ^~~~~~~~~~~~~~~~~~~
51 warnings and 1 error generated.
make[2]: *** [../o/jpeg2000_vsil_io.lo] Error 1
make[1]: *** [jpeg2000-install-obj] Error 2
make: *** [frmts-target] Error 2

## Steps to reproduce the problem.

I am trying to patch jpeg2000dataset.cpp, but in this version all updates already done.

## Operating system

MacOS 10.15.7

## GDAL version and provenance

gdal-3.1.3

**Comment by rouault** [comment]
you may need to update Jasper to 2.0.19 as there were issues with 2.0.17. Or build --without-jasper . If you need JPEG2000 support, using libopenjp2 is preferable, that is building --with-openjpeg.

**Comment by filislav** [comment]
I have jasper 2.0.20 installing through homebrew

**Comment by filislav** [comment]
I am configure with --without-jasper key, but finally i have an error with message:

Undefined symbols for architecture x86_64:
  "JPEG2000_VSIL_fopen(char const*, char const*)", referenced from:
      JPEG2000Dataset::Open(GDALOpenInfo*) in jpeg2000dataset.o
      JPEG2000CreateCopy(char const*, GDALDataset*, int, char**, int (*)(double, char const*, void*), void*) in jpeg2000dataset.o
  "_jas_cmprof_createfromclrspc", referenced from:
      JPEG2000Dataset::DecodeImage() in jpeg2000dataset.o
  "_jas_cmprof_destroy", referenced from:
      JPEG2000Dataset::DecodeImage() in jpeg2000dataset.o
  "_jas_image_addcmpt", referenced from:
      JPEG2000CreateCopy(char const*, GDALDataset*, int, char**, int (*)(double, char const*, void*), void*) in jpeg2000dataset.o
  "_jas_image_chclrspc", referenced from:
      JPEG2000Dataset::DecodeImage() in jpeg2000dataset.o
  "_jas_image_create0", referenced from:
      JPEG2000CreateCopy(char const*, GDALDataset*, int, char**, int (*)(double, char const*, void*), void*) in jpeg2000dataset.o
  "_jas_image_decode", referenced from:
      JPEG2000Dataset::DecodeImage() in jpeg2000dataset.o
  "_jas_image_destroy", referenced from:
      JPEG2000Dataset::DecodeImage() in jpeg2000dataset.o
      JPEG2000Dataset::~JPEG2000Dataset() in jpeg2000dataset.o
      JPEG2000Dataset::~JPEG2000Dataset() in jpeg2000dataset.o
      JPEG2000Dataset::~JPEG2000Dataset() in jpeg2000dataset.o
      JPEG2000CreateCopy(char const*, GDALDataset*, int, char**, int (*)(double, char const*, void*), void*) in jpeg2000dataset.o
  "_jas_image_fmttostr", referenced from:
      JPEG2000Dataset::DecodeImage() in jpeg2000dataset.o
      JPEG2000Dataset::Open(GDALOpenInfo*) in jpeg2000dataset.o
  "_jas_image_getfmt", referenced from:
      JPEG2000Dataset::Open(GDALOpenInfo*) in jpeg2000dataset.o
  "_jas_image_readcmpt", referenced from:
      JPEG2000RasterBand::IReadBlock(int, int, void*) in jpeg2000dataset.o
  "_jas_image_writecmpt", referenced from:
      JPEG2000CreateCopy(char const*, GDALDataset*, int, char**, int (*)(double, char const*, void*), void*) in jpeg2000dataset.o
  "_jas_init", referenced from:
      JPEG2000Dataset::Open(GDALOpenInfo*) in jpeg2000dataset.o
      JPEG2000CreateCopy(char const*, GDALDataset*, int, char**, int (*)(double, char const*, void*), void*) in jpeg2000dataset.o
  "_jas_matrix_create", referenced from:
      JPEG2000RasterBand::JPEG2000RasterBand(JPEG2000Dataset*, int, int, int) in jpeg2000dataset.o
      JPEG2000CreateCopy(char const*, GDALDataset*, int, char**, int (*)(double, char const*, void*), void*) in jpeg2000dataset.o
  "_jas_matrix_destroy", referenced from:
      JPEG2000RasterBand::~JPEG2000RasterBand() in jpeg2000dataset.o
      JPEG2000RasterBand::~JPEG2000RasterBand() in jpeg2000dataset.o
      JPEG2000RasterBand::~JPEG2000RasterBand() in jpeg2000dataset.o
      JPEG2000CreateCopy(char const*, GDALDataset*, int, char**, int (*)(double, char const*, void*), void*) in jpeg2000dataset.o
  "_jas_stream_close", referenced from:
      JPEG2000Dataset::~JPEG2000Dataset() in jpeg2000dataset.o
      JPEG2000Dataset::~JPEG2000Dataset() in jpeg2000dataset.o
      JPEG2000Dataset::~JPEG2000Dataset() in jpeg2000dataset.o
      JPEG2000Dataset::Open(GDALOpenInfo*) in jpeg2000dataset.o
      JPEG2000CreateCopy(char const*, GDALDataset*, int, char**, int (*)(double, char const*, void*), void*) in jpeg2000dataset.o
  "_jas_stream_flush", referenced from:
      JPEG2000CreateCopy(char const*, GDALDataset*, int, char**, int (*)(double, char const*, void*), void*) in jpeg2000dataset.o
  "_jas_stream_rewind", referenced from:
      JPEG2000Dataset::Open(GDALOpenInfo*) in jpeg2000dataset.o
  "_jp2_box_destroy", referenced from:
      JPEG2000Dataset::Open(GDALOpenInfo*) in jpeg2000dataset.o
  "_jp2_box_get", referenced from:
      JPEG2000Dataset::Open(GDALOpenInfo*) in jpeg2000dataset.o
  "_jp2_encode", referenced from:
      JPEG2000CreateCopy(char const*, GDALDataset*, int, char**, int (*)(double, char const*, void*), void*) in jpeg2000dataset.o
  "_jpc_encode", referenced from:
      JPEG2000CreateCopy(char const*, GDALDataset*, int, char**, int (*)(double, char const*, void*), void*) in jpeg2000dataset.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [libgdal.la] Error 1
make: *** [check-lib] Error 2

**Comment by rouault** [comment]
> I am configure with --without-jasper key, but finally i have an error with message:

you need to "make clean", before rebuilding each time you change ./configure switches

**Comment by filislav** [comment]
Ok. Make finished successful, but when i do make on swig/java i have next error
/bin/sh /Users/slava/Downloads/gdal-3.1.3/libtool --mode=link --silent g++ -std=c++11  gdalconst_wrap.lo gdal_wrap.lo osr_wrap.lo ogr_wrap.lo gnm_wrap.lo  /Users/slava/Downloads/gdal-3.1.3/libgdal.la -o libgdalalljni.la -rpath /usr/local/lib -no-undefined -version-info 27:3:0
libtool: warning: '/usr/local/lib/libproj.la' seems to be moved
if [ -f ".libs/libgdalalljni.so" ] ; then \
		cp .libs/*.so . ; \
	fi
echo ".libs/libgdalalljni.27.dylib .libs/libgdalalljni.dylib"
.libs/libgdalalljni.27.dylib .libs/libgdalalljni.dylib
if [ -f ".libs/libgdalalljni.dylib" ] ; then \
		cp .libs/*.dylib . ; \
	fi
ant
make: ant: No such file or directory
make: *** [build] Error 1

How i may fix it?

**Comment by rouault** [comment]
> make: ant: No such file or directory

You need to install whatever package provide the "ant" utility
