### ISSUE TITLE
OGR: add option to deactivate .gfs creation when opening a GML

### ISSUE THREAD

**Issue by ungarj** [OSGeo/gdal#2982]
## Expected behavior and actual behavior.

Unless the file system is read-only (see the [switch here](https://github.com/OSGeo/gdal/blob/master/gdal/ogr/ogrsf_frmts/gml/ogrgmldatasource.cpp#L1276)) OGR will automatically try to create a .gfs file whenever it opens a GML file.

This also means when the GML file is on an object storage OGR will try to make a PUT request to upload the .gfs. In case a user either doesn't want or need this or has no write permissions to this bucket anyway, OGR will waste this PUT request which could lead to unexpected and avoidable costs (e.g. using AWS S3).

It would be convenient if we had a configuration flag to turn off the .gfs creation if necessary.

## Steps to reproduce the problem.

```shell
$ ogrinfo /vsis3/sentinel-s2-l2a/tiles/51/K/XR/2020/7/31/0/qi/MSK_DETFOO_B01.gml
ERROR 1: Only read-only mode is supported for /vsicurl
ERROR 1: DoSinglePartPUT of /vsis3/sentinel-s2-l2a/tiles/51/K/XR/2020/7/31/0/qi/MSK_DETFOO_B01.gfs failed
ERROR 1: DoSinglePartPUT of /vsis3/sentinel-s2-l2a/tiles/51/K/XR/2020/7/31/0/qi/MSK_DETFOO_B01.gfs failed
Had to open data source read-only.
INFO: Open of `/vsis3/sentinel-s2-l2a/tiles/51/K/XR/2020/7/31/0/qi/MSK_DETFOO_B01.gml'
      using driver `GML' successful.
Metadata:
  NAME=MSK_DETFOO pixels mask from data-strip S2A_OPER_MSK_DETFOO_EPAE_20200731T032617_A026669_T51KXR_B01_MSIL1C
1: MaskFeature (3D Polygon)
```

## Operating system

Ubuntu 16.04 64 bit

## GDAL version and provenance

the 2.2.2 version from ubuntugis-unstable PPA

**Comment by jratike80** [comment]
What happens if you open the link as read-only? Does GDAL still try to PUT?
I could not test myself because of missing security-credentials.

**Comment by ungarj** [comment]
Sorry for the late reply and thanks for the hints, @jratike80 !

Not sure how to explicitly trigger read-only mode via the command line? Shouldn't `ogrinfo` then per default hopen the file read-only?

I also tried with Fiona's `fio insp` command, which -- at least on the Python side -- opens the file as read-only.

Yes, when reviewing the documentation I also found the option with providing and XSD file. However in our use case, where plainly reading the mask GMLs worked so far, I don't really see the point in triggering an additional request to an XSD file for every Sentinel-2 product.

Thanks @rouault for acting quickly and writing a patch!

**Comment by jratike80** [comment]
About ogrinfo and read-only, it is documented in https://gdal.org/programs/ogrinfo.html

> -ro
> Open the data source in read-only mode.

That ogrinfo can do much more than just to print some metadata, and that the read-write mode is the default may surprise users, but it is really possible to do for example

`ogrinfo -sql "drop table test" test.shp`

and then there will be no shapefile "test.shp"

**Comment by ungarj** [comment]
Oh thanks, I missed that flag!

However, using `-ro` still lets OGR make a PUT request:

```
$ ogrinfo -ro /vsis3/sentinel-s2-l2a/tiles/51/K/XR/2020/7/31/0/qi/MSK_DETFOO_B01.gml
ERROR 1: DoSinglePartPUT of /vsis3/sentinel-s2-l2a/tiles/51/K/XR/2020/7/31/0/qi/MSK_DETFOO_B01.gfs failed
ERROR 1: DoSinglePartPUT of /vsis3/sentinel-s2-l2a/tiles/51/K/XR/2020/7/31/0/qi/MSK_DETFOO_B01.gfs failed
INFO: Open of `/vsis3/sentinel-s2-l2a/tiles/51/K/XR/2020/7/31/0/qi/MSK_DETFOO_B01.gml'
      using driver `GML' successful.
Metadata:
  NAME=MSK_DETFOO pixels mask from data-strip S2A_OPER_MSK_DETFOO_EPAE_20200731T032617_A026669_T51KXR_B01_MSIL1C
1: MaskFeature (3D Polygon)
```

**Comment by rouault** [comment]
.gfs files are created, regardless of the read-only / update flag of the dataset (as they are side car files, and do not modify the main file)
