### ISSUE TITLE
GDAL configure script complains that it cannot find PROJ 6 symbols

### ISSUE THREAD

**Issue by jormundgand** [OSGeo/gdal#3020]
## Expected behavior

Running the configure script results in a viable build system.

## Actual behavior

The GDAL configure script complain that PROJ 6 symbols are not found.

```bash
checking for PROJ >= 6 library... checking for proj_create_from_wkt in -lproj... no
checking for internal_proj_create_from_wkt in -lproj... no
checking for internal_proj_create_from_wkt in -linternalproj... no
configure: error: PROJ 6 symbols not found
```

## Steps to reproduce the problem.

run ./configure

## Operating system

Ubuntu 18.04

## GDAL version and provenance

GDAL 3.1.3 (today's git master)

**Comment by rouault** [comment]
The error message says it all. You need to build GDAL against PROJ >= 6. The PROJ version in ubuntu 18.04 is too old

The ubuntugis-unstable PPA has PROJ 7.0.0 for bionic: https://launchpad.net/~ubuntugis/+archive/ubuntu/ubuntugis-unstable

**Comment by jormundgand** [comment]
According to the documentation, the only dependency that GDAL has is a working c++ compiler. This is clearly not true.

**Comment by rouault** [comment]
> I say documentation..

Fair enough. Just added https://gdal.org/download.html#build-requirements
