### ISSUE TITLE
Trouble compiling with DEBUG and MSVC 140

### ISSUE THREAD

**Issue by mmomtchev** [OSGeo/gdal#3034]
https://github.com/OSGeo/gdal/blob/3a0ce017270ffcb2ab5f419f94c5d381603b837b/gdal/ogr/ogrsf_frmts/avc/avc_binwr.cpp#L1520

Because of VSIL_STRICT_ENFORCE, FILE cannot be converted to VSIFILE

**Comment by rouault** [comment]
Can you issue a pull request to change FILE *fp to VSILFILE *fp ?
(I'm wondering if we still really need this WIN32 specific code path, but this is another topic)
