### ISSUE TITLE
MSSQLSpatial: Cannot write binary field when MSSQLSPATIAL_USE_BCP = TRUE

### ISSUE THREAD

**Issue by srweal** [OSGeo/gdal#3040]
I'm expecting a binary field to write from an OpenFileGDB source into MSSQLSpatial. However, it returns the following error for every feature in the source:
`ERROR 1: INSERT command for new feature failed. [37000][Microsoft][ODBC SQL Server Driver][SQL Server]Incorrect syntax near '0xffd8ffe...`

This happens when I run the command within GDAL 3.1.3 (released 2020/09/01) on Windows 10 obtained from GIS Internals (https://www.gisinternals.com/query.html?content=filelist&file=release-1911-x64-gdal-3-1-3-mapserver-7-6-1.zip):
`ogr2ogr -f "MSSQLSpatial" "MSSQL:server=.;database=MyDB;Uid=sa;Pwd=password;" source.gdb.zip -skipfailures`

I have reproduced the problem on GDAL 2.3.3 (released 2018/12/14) also. I have run MSSQL Profiler to watch the commands generated and noticed that they are each missing the closing ) on the overall INSERT statement:. 

`'SET IDENTITY_INSERT [dbo].[inspections__attach] ON;INSERT INTO [dbo].[inspections__attach] ([attachmentid], [globalid], [rel_globalid], [content_type], [att_name], [data_size], [data]) VALUES (16, @P1, @P2, @P3, @P4, 318830, 0xffd8ffe...d454e308d8',N'@P1 nvarchar(39),@P2 nvarchar(39),@P3 nvarchar(11),@P4 nvarchar(12)',N'{B397675D-739A-4183-97FA-012E889320A6}',N'{D8D13DD1-92CC-4A1A-B7CF-FC171EEDC59F}',N'image/jpeg',N'Photo 2.jpg'`

Please note that same OGR2OGR statement works fine when there are no binary fields involved in the source database. Weird.

I am unfamiliar with the GDAL source, but this looks to be where the closing bracket gets included into the statements, but for some reason it is not being included on these INSERTS - https://github.com/OSGeo/gdal/blob/b51dc28ab7da7c84c1cac3477560dbc9ba9f5c9e/gdal/ogr/ogrsf_frmts/mssqlspatial/ogrmssqlspatialtablelayer.cpp#L2350

**Comment by elpaso** [comment]
Note: this only happens when config option "MSSQLSPATIAL_USE_BCP" is "TRUE"
