### ISSUE TITLE
wiki : building on unix with minimized drivers

### ISSUE THREAD

**Issue by fxi** [OSGeo/gdal#3043]
I post this here, as your wiki is not public.

This could be improved : https://trac.osgeo.org/gdal/wiki/BuildingOnUnixWithMinimizedDrivers#no1

Now, it does not really build a minimized binary and some options do not exist anymore. E.g.: `configure: WARNING: unrecognized options: --without-bsb, --without-dwgdirect, --without-grib, --without-mrf, --without-php`

Maybe just mention that `--disable-all-optional-drivers` could cover the case where “minimized drivers“ is a requirement. 

Or remove the page :)

Thanks

**Comment by rouault** [comment]
The wiki is no longer maintained, and https://gdal.org is the only maintained documentation now. We could appreciate contributions migrating (and updating!) old wiki content. In that instance, I could imagine a "Build hints" subparagraph under https://gdal.org/download.html#development-source . See the "edit on github" button the top right of each page to submit enhancements

**Comment by fxi** [comment]
Thanks @rouault ! I was not aware of this. A deprecation notice could then be added as a banner in the wiki to redirect lost minds to the real deal.
If I get something worth sharing on this topic, I will fork this repo and edit the new doc.

**Comment by rouault** [comment]
I've improved a bit the warning banner on top of https://trac.osgeo.org/gdal/wiki

**Comment by fxi** [comment]
Good :) 

It could even be better with that banner visible on top of each pages - as users like me usually land where google throw them – more often than not – on pages not maintained anymore. That's just an idea.

**Comment by rouault** [comment]
closing as configure has been removed and replaced by cmake. https://gdal.org/build_hints.html document minimal builds
