### ISSUE TITLE
Gdaladdo creates tiles with nodatavalue-1 in tiled gridded GPKG

### ISSUE THREAD

**Issue by matsamentet** [OSGeo/gdal#3044]
## Expected behavior and actual behavior.

I'm trying to create a tiled gridded GeoPackage with PNG tiles from a 32 bit GeoTIFF representing a digital surface model. Using gdalwarp to create the GeoPackage, it looks correct before adding overviews. The "data_null" field is set to 65535.0 in gpkg_2d_gridded_coverage_ancillary, and it is set on the correct pixels compared to the source file.

I then run Gdaladdo, which seem to conflate the data_null value with actual values (?) when calculating overviews, and proceed to create some tiles with the value 65534, which of course creates some huge spikes in the output file. I have tested this with -r average, bilinear and cubic, with similar results.
![image](https://user-images.githubusercontent.com/22658674/95584749-7f01b300-0a3e-11eb-9c66-5da1a8ceb380.png)

## Steps to reproduce the problem.
Testfile: https://files.teleplan.no/sharing/x3ltRyDi4

`gdalwarp -of GPKG -co TILE_FORMAT=PNG 33-155-190.tif outfile.gpkg`
`gdaladdo -r average outfile.gpkg`

## Operating system

Windows 10 Enterprise

## GDAL version and provenance

GDAL 3.1.2 from GISInternals

**Comment by rouault** [comment]
Fixed per 814736ec26adc43f1674af83d0100ccd2fc48b09 (backported in 3.1 as well in 4b5bb72). It depends also on another fix done in 3.1.3:
```
commit 40351196c306fc5c643bfa5b4b1a6adb0feeaec1
Author: Even Rouault <even.rouault@spatialys.com>
Date:   Mon Aug 17 16:40:53 2020 +0200

    GPKG: on reading of gridded coverage data with PNG tiles, select -FLT_MAX as the nodata value (fixes #2857)
```
