### ISSUE TITLE
DAAS driver: invalid type used for buffer retrieval when mixing UInt16 image with Byte masks

### ISSUE THREAD

**Issue by bchretien** [OSGeo/gdal#3061]
## Expected behavior and actual behavior.

Hi,

When opening an `UInt16` image containing `Byte` masks with the GDAL DAAS driver, we got the following error:
```
ERROR 1: Got buffer of 262144 bytes, whereas 524288 were expected
ERROR 1: DAAS:http://xxxxx, band 5: IReadBlock failed at X offset 0, Y offset 0: Got buffer of 262144 bytes, whereas 524288 were expected
```
This appears to be an error with the type used when retrieving the buffer. It seems that the source of the error is [here](https://github.com/OSGeo/gdal/blob/f02356245e81e2f9d95069b6d126219d1d85736b/gdal/frmts/daas/daasdataset.cpp#L2434): with `oBandArray.Size() > 0` the error appears to be gone.

Additionally, the [list of configuration options](https://gdal.org/user/configoptions.html) is incomplete: the options from the DAAS driver are missing

## Steps to reproduce the problem.

Try to open an `UInt16` image with `Byte` masks with the DAAS driver, for example with `gdal_translate` or `gdalwrap`:
```
$ gdal_translate DAAS:http://xxxxx out.tiff
Input file size is 9999, 8746
0..
ERROR 1: Got buffer of 262144 bytes, whereas 524288 were expected
ERROR 1: DAAS:http://xxxxx, band 5: IReadBlock failed at X offset 0, Y offset 0: Got buffer of 262144 bytes, whereas 524288 were expected
```

## Operating system

Ubuntu 20.04.1.

## GDAL version and provenance

The 3.0.4 version ~~compiled from source~~ from Ubuntu packages ([this mirror](http://europe-west4-a.gce.clouds.archive.ubuntu.com/ubuntu)).

**Comment by rouault** [comment]
> When opening an `UInt16` image containing `Byte` masks with the GDAL DAAS driver,

Could you give the URL of the image ? (I know it will require authentication to be useful)

> Additionally, the list of configuration options is incomplete: the options from the DAAS driver are missing

Open options specific the DAAS driver are a different concept than configuration options which might have a global scope. They are documented here https://gdal.org/drivers/raster/daas.html#open-options

**Comment by bchretien** [comment]
> Open options specific the DAAS driver are a different concept than configuration options which might have a global scope. They are documented here https://gdal.org/drivers/raster/daas.html#open-options

According to the DAAS driver documentation, `GDAL_DAAS_API_KEY`, `GDAL_DAAS_CLIENT_ID` and `GDAL_DAAS_X_FORWARDED_USER` are configuration options, so shouldn't they appear in the configuration options documentation? It's not a big problem, just something I noticed while testing the driver and reading the documentation.

> Could you give the URL of the image ? (I know it will require authentication to be useful)

I'll try to see what I can do. In the meantime, to give more information, `eDataType` [here](https://github.com/OSGeo/gdal/blob/f02356245e81e2f9d95069b6d126219d1d85736b/gdal/frmts/daas/daasdataset.cpp#L2432) was the image type (so `UInt16`), and since the condition `oBandArray.Size() > 1` was not fulfilled, `GetGDALDataTypeFromDAASPixelType(osPixelType)` was not called to get the actual type of the mask (`Byte`).

**Comment by Schebb** [comment]
Sorry I didn't provide accurate information to @bchretien (We worked together on this subject).

> Try to open an UInt16 image with Byte masks with the DAAS driver, for example with gdal_translate or gdalwarp:

I ran more tests. If the image contains multiple masks, it still fails with `gdalwarp` but not with `gdal_translate`.

It fails always with both `gdalwarp` and `gdal_translate` when using an UInt16 image with **only one** Byte mask (so it does not trigger the mentioned condition).
Note I also reproduced the error from GDAL 3.1.3, released 2020/09/01, compiled from source on Ubuntu 20.04.1.

```bash
$ gdal_translate DAAS:http://xxxx out.tiff
Input file size is 9652, 17229
0ERROR 1: Got buffer of 4941824 bytes, whereas 9883648 were expected
ERROR 1: Got buffer of 262144 bytes, whereas 524288 were expected
ERROR 1: DAAS:http://xxxx, band 5: IReadBlock failed at X offset 0, Y offset 0

```

I will come back to you as soon as I have authorizations to give all necessary data to reproduce this error.
