### ISSUE TITLE
I can’t find epsg code 9357 in qgis

### ISSUE THREAD

**Issue by Fdalbouh** [OSGeo/gdal#3092]
On March 20, 2020 my national government agency registered our new coordinate system with EPSG Geodetic Registry but I still can't use it because it still not exist within QGIS or Arcgis. I don't know how often GDAL OR PROJ library is updated with EPSG Database. Is there a timeline for that or another way to use them because it's already registered with epsg https://epsg.org/search/by-name?sessionkey=jy5knr1nwt&searchedTerms=Grf

**Comment by jratike80** [comment]
Don't ask questions in the bug tracker. Use the mailing list instead.

You can have a quick look on the Proj release notes https://proj.org/news.html. Last EPSG database update is from September 1st: Updated EPSG database to version 9.8.15 but I do not know how to check from epsg.org in which database version the change https://epsg.org/closed-change-request/browse/id/2020.03 first appears. At least it is present in current version 10.005. The jump into version 10 is not small but there seems to be a pull request that is related to EPSG v10 in the Proj GitHub project https://github.com/OSGeo/PROJ/pull/2371.

**Comment by rouault** [comment]
EPSG:9357 is available at least in PROJ 7.1.1
