### ISSUE TITLE
OSGEO4W wrong grass version

### ISSUE THREAD

**Issue by chleidersdorff** [OSGeo/gdal#3096]
When installing QGis through OSGeo4W everyting installs without problems but when running Qgis with GRASS and turning on the  GRASS CORE plugin there is an error saying GRASS is built agains wrong version. 

Have tried selecting different versions of GRASS and teh GRASS plugin during install and it is the same ploblem.

![image](https://user-images.githubusercontent.com/52182284/96961558-4686cc80-1548-11eb-88e2-9bd6d725c95a.png)

**Comment by rouault** [comment]
Definitely not a GDAL source issue but a OSGeo4W one. I believe this has already been reported. Check QGIS bug tracker or mailing list. Otherwise file issue at https://trac.osgeo.org/osgeo4w/
