### ISSUE TITLE
NODATA setting at source level not taken into account with -r cubic

### ISSUE THREAD

**Issue by lnicola** [OSGeo/gdal#3098]
# Expected behavior and actual behavior.

Sorry if this is a known issue, the `gdal_translate -projwin` docs hint that it might be.

I'm trying to create a DEM raster from multiple tiles (the SRTM DEM in this case). The steps I've used are:

 - `gdalbuildvrt -srcnodata -32768 -vrtnodata 0 -resolution highest -overwrite srtm.vrt srtm/*.tif`
 - `gdalwarp -overwrite -multi -r cubic -t_srs EPSG:32629 -dstnodata none -tr 10.0 -10.0 -te 699960.0 3690240.0 809760.0 3800040.0 srtm.vrt dem.tif`

I have to set `-vrtnodata` to mask off the large nodata values, which otherwise are used during resampling.

If I do the steps above with a single SRTM tile (or two, or probably some small number of them), it works fine. But if I build the VRT from all the tiles, there is a shift introduced in the output. Using `gdalbuildvrt -r cubic` fixes the shift, but brings back the nodata resampling problem.

I also tried to make two VRTs, one built from the tiles with `-vrtnodata 0`, the second built from the first with `-r cubic`, but unsurprisingly, that doesn't help.

The workaround seems to be to make a copy of each SRTM tile with a new nodata value, then to use `gdalbuildvrt -r cubic`, but I hope to avoid that.

## GDAL version and provenance

`osgeo/gdal:alpine-small-latest`

**Comment by rouault** [comment]
> The workaround seems to be to make a copy of each SRTM tile with a new nodata value, then to use `gdalbuildvrt -r cub`

Hum, this is tricky. I believe the issue is that the NODATA setting at the VRTComplexSource level is ignored by the GDALRasterBand::RasterIO() code. I'm afraid that the VRT code would have to create on-the-fly a VRT altering the nodata value for the purpose of  GDALRasterBand::RasterIO()

Your workaround is probably the only one right now. Note that you don't necessarily need to 'materizalize' a SRTM tile with a new nodata value. You could do a "gdal_translate src.tif src_nodata_zero.vrt -of VRT -a_nodata 0" and then run gdalbuildvrt on those .vrt files.

**Comment by lnicola** [comment]
I guess you meant `gdalwarp -srcnodata -32768 -dstnodata 0 -et 0` -- that works indeed, thank you.

But I filed this issue for the shift, do you think it can't / shouldn't be fixed?

**Comment by rouault** [comment]
> for the shift, do you think it can't / shouldn't be fixed?

It is (mathematically) expected that the default nearest resampling introduces sub-pixel shift.

**Comment by lnicola** [comment]
I guess that my mental model of "`gdalwarp -r cubic foo.vrt` never hits non-integer pixels in the underlying images" isn't quite accurate then. Do you want to close this issue, or should we leave it open for any possible improvements wrt. nodata handling in VRTs?

**Comment by rouault** [comment]
> or should we leave it open for any possible improvements wrt. nodata handling in VRTs?

yes, I think ultimately it would be nice to take into account the source nodata override specified by gdalbuildvrt -srcnodata , as it is certainly surprising to see it ignored when doing non-nearest resampling.

**Comment by lnicola** [comment]
> take into account the source nodata override specified by gdalbuildvrt -srcnodata

I think it's taken into account (propagated), but the bicubic resampling doesn't ignore those pixels like average does, so it's unusable. That's why I was trying to mask them to 0. So my issue was rather "I can't use -vrtnodata and -r cubic in a single step".

**Comment by rouault** [comment]
I'm a bit lost now. Could you try to provide a very minimum reproducer (ideally one single tiff file + the gdalbuildvrt/gdalwarp invokations), to reproduce only the issue with the nodata + cubic

**Comment by lnicola** [comment]
Sorry, let's close this. I think the nodata values are handled as expected -- which isn't ideal for my use case (replacing nodata pixels with a different value before reading from the file), but can be worked around like you hinted above, with a VRT and `-dstnodata`. And while not ideal, it doesn't look like a bug to me, it's just how GDAL works.

Basically, as in my first comment:

```
# this handles nodata "correctly", but introduces a shift
gdalbuildvrt -srcnodata -32768 -vrtnodata 0 -resolution highest -overwrite srtm.vrt srtm/*.tif
gdalwarp -overwrite -multi -r cubic -t_srs EPSG:32629 -dstnodata none -tr 10.0 -10.0 -te 699960.0 3690240.0 809760.0 3800040.0 srtm.vrt dem.tif

# this produces no shift, but uses -32768 during resampling, and not 0
gdalbuildvrt -srcnodata -32768 -vrtnodata 0 -resolution highest -r cubic -overwrite srtm.vrt srtm/*.tif
gdalwarp -overwrite -multi -r cubic -t_srs EPSG:32629 -dstnodata none -tr 10.0 -10.0 -te 699960.0 3690240.0 809760.0 3800040.0 srtm.vrt dem.tif
```
