### ISSUE TITLE
Sub-pixel discrepancy between GDALDatasetRasterIOEx and GDALRasterIOEx

### ISSUE THREAD

**Issue by sgillies** [OSGeo/gdal#3101]
In https://github.com/mapbox/rasterio/issues/2022 a rasterio user reported a discrepancy between the results of `dataset.read()` and `dataset.read_mask()` when using floating point windows and nearest neighbor resampling. The major difference between these rasterio methods is that `read()` (for reading band data) calls `GDALDatasetRasterIOEx` one time only (in an attempt to be more efficient) and `read_mask()` calls `GDALRasterIOEx` one time per band. When I changed the implementation of `read()` to call `GDALRasterIOEx` one time per band in https://github.com/mapbox/rasterio/pull/2023/commits/cf16f8c95fb496c4e3add9a3e682ede9a22b82d6 the discrepancy is not observed.

I'm using GDAL version 3.1.4. But from what I see in https://travis-ci.org/github/mapbox/rasterio/builds/738588031 this discrepancy exists in earlier versions where floating point read/write windows are possible.

I guess that this isn't related to #2507 and #2510? But it looks like that logic isn't present in GDALDatasetRasterIOEx and perhaps there is another lurking issue.

**Comment by rouault** [comment]
> I guess that this isn't related to #2507 and #2510?

No, but you pointed the code path that was actually taken here, that is the BlockBasedRasterIO() method, which didn't deal properly with floating-point coordinates.

Should be fixed per https://github.com/OSGeo/gdal/pull/3102 . At least this fixes the test case I added

**Comment by sgillies** [comment]
Thanks @rouault ! I've got a patch for GDAL versions before 3.2.0 based on this and am testing it.
