### ISSUE TITLE
C# Bindings - Osr.GetPROJSearchPaths does not return the value defined by Osr.SetPROJSearchPath

### ISSUE THREAD

**Issue by sylvaneau** [OSGeo/gdal#3106]
## Expected behavior and actual behavior.

When initializing GDAL using C# wrapper, Osr.SetPROJSearchPath(string) must be called to correctly initialize ProjDb resources.
Expected : After calling this method a call to Osr.GetProjSearchPaths() should return the value previously set.
Actual : Osr.GetProjSearchPaths() returns "E:/builds/release-1911-x64/share/proj"

Please note that the wrapper works (surprisingly) even if the returned path is incorrect.

## Steps to reproduce the problem.

- Create a .Net Framework console project (4.7)
- Add references to GDAL and wrappers (from GisInternals)
- Set PATH Environment variables, GDAL_DATA, GDAL_DRIVER_PATH
- Call Osr.SetPROJSearchPath

## Operating system

Windows 10

## GDAL version and provenance

GDAL 3.1.3 x64 (MSVC2017) from GisInternals

**Comment by rouault** [comment]
Has been fixed in GDAL 3.1.4 per

commit dfd53495b4bb7ab09b44013115f687961bf59182
Author: Even Rouault <even.rouault@spatialys.com>
Date:   Mon Aug 17 19:09:12 2020 +0200

    Make OSRGetPROJSearchPaths() return the value set by OSRSetPROJSearchPaths()
