### ISSUE TITLE
GDAL_HTTPS_PROXY option missing from docs

### ISSUE THREAD

**Issue by agiudiceandrea** [OSGeo/gdal#3111]
GDAL_HTTPS_PROXY option was introduced with PR https://github.com/OSGeo/gdal/pull/972 to fix https://github.com/OSGeo/gdal/issues/878

Anyway in the docs [here](https://gdal.org/user/configoptions.html) and [here](https://gdal.org/user/virtual_file_systems.html#network-based-file-systems) it is not listed as a valid option.

**Comment by jratike80** [comment]
You can try self service by pressing the button "Edit on GitHub" at the top right corner of those doc pages.

**Comment by agiudiceandrea** [comment]
Thanks @jratike80. Anyway I'm not sure about how to correctly reword the relevant part of the docs where it is stated that for GDAL_HTTP_PROXY  "the syntax to use is the one of Curl CURLOPT_PROXY" ("The proxy string may be prefixed with [scheme]:// to specify which kind of proxy is used") which it seems to me it's not the case, but I could be wrong.
