### ISSUE TITLE
Drop support for Python 2 (min Python v2.7 -> v3.6)

### ISSUE THREAD

**Issue by idanmiara** [OSGeo/gdal#3114]
**Why?**

[Python 2 is dead since the January 2020](https://www.python.org/doc/sunset-python-2/)
I think that there is no point in keeping it alive as it it forbids us using all the goodies Python 3 is bringing and make us backporting Python3 code in order to commit it to GDAL.

Now that GDAL 3.2 is almost out, I think it might be the time to fully migrate to Python 3 for GDAL 3.3.

**Related projects that made the transition to Python3:**

[QGIS since v3.0 - February 2018. (Python 3.7)](https://www.qgis.org/en/site/forusers/visualchangelog30/index.html) 
[GRASS GIS since v7.8 - September 2019 (Python 3.7)](https://trac.osgeo.org/grass/wiki/Python3Support)
[pyproj since v2.3 - August 2019 (Python 3.5-3.7)](https://pyproj4.github.io/pyproj/stable/history.html)

**Which version should be the new minimum version ?**

[Python 3.6 will be end of life on 23 Dec 2021](https://endoflife.date/python#:~:text=The%20support%20for%20Python%202.7,dropping%20support%20for%20Python%202.7.)
[Python 3.7](https://realpython.com/python37-new-features/), which was released on June 2018, is already widely adopted.

[Recommend Python and Numpy version support as a community policy standard
](https://numpy.org/neps/nep-0029-deprecation_policy.html)

**Comment by rcoup** [comment]
> Which version should be the new minimum version ?
> 
> Python 3.6 will be end of life on 23 Dec 2021
> Python 3.7, which was released on June 2018, is already widely adopted, so I think that it should be the new minimum version.

From these choices I'd prefer Python 3.6 — not that people shouldn't be using 3.7, but it is a fairly minor increment (ignoring asyncio), whereas 3.6 added f-strings, builtin pathlib, underscores in numeric literals, annotations, and malloc debugging — several of which are immediately useful to simplify code or improve testing.

Python versions on various Ubuntu distros
* Ubuntu Xenial LTS (EOL April 2021): Python 3.5
* Ubuntu Bionic LTS (EOL 2023): Python 3.6
* Debian Stretch LTS (EOL 2022): Python 3.5
* Debian Buster LTS (EOL 2024): Python 3.7
* Centos/RHEL 8 distributes Python 3.6 AFAICT
* Amazon Linux supports Python 3.6 until it's EOL upstream at the end of 2021

SWIG seems to support Python <3.8 with 3.0.12, for 3.8 support you need to go to SWIG 4.0.0

**Comment by idanmiara** [comment]
Python 3.6 and 3.7 are both great choices.
I agree that 3.6 brings the most important features.

**Comment by rouault** [comment]
From an early thought, I'd be supportive of 3.6 as the minimum version. I see Rasterio should bump to that too in > 1.1.0 according to https://github.com/mapbox/rasterio/issues/1774
I think this will be worth a mini RFC for consultation with the community at large and approval by the PSC. Impacts on our CI should be analyzed.

**Comment by idanmiara** [comment]
@rouault @rcoup 
Thanks for your input and please feel free to co-author this RFC.

**Comment by rcoup** [comment]
[RFC77](https://gdal.org/development/rfc/rfc77_drop_python2_support.html) has been approved and implementation will be dealt with as separate issues
