### ISSUE TITLE
Did something happen with gdal_rasterize's -i flag behaviour?

### ISSUE THREAD

**Issue by xerosugar** [OSGeo/gdal#3124]
## Expected behavior and actual behavior.
I expect this command to make the whole image transparent, *except* for the area contained in the geometry from the geojson-file.
`gdal_rasterize -i -b 1 -b 2 -b 3 -b 4 -burn 0 -burn 0 -burn 0 -burn 0 filter.geojson map.tif`

But what actually happens is that the whole image becomes transparent.
If I remove the -i flag, it works as intended; the area *inside* the geometry becomes transparent, and everything else is unaffected.

## Steps to reproduce the problem.
- Take a GeoTiff.
- Drop that GeoTiff in QGIS.
- Draw one polygon on top of it (this polygon will serve as a mask), export that geometry to a geojson-file.
- Run the above gdal_rasterize-command with your geojson-file as input and your GeoTiff as the last argument.

## Operating system
Win 10 Pro, 64-bit.

## GDAL version and provenance
```
$ gdalinfo --version
GDAL 3.1.4, released 2020/10/20
```

**Comment by jratike80** [comment]
It is possible, I don't see a test for -i in https://github.com/OSGeo/gdal/blob/master/autotest/utilities/test_gdal_rasterize.py.
Can you point some older GDAL version that gives the right result?

**Comment by xerosugar** [comment]
I'm using GDAL 2.2.3 on another server and that works. But I'm not 100% sure if there are other GDAL configurations that I'm unaware of that makes it work on 2.2.3 and not 3.1.4.

**Comment by xerosugar** [comment]
GDAL 2.4.3 seems to work, even if it gives somes warnings and errors.
Here's a site that you can download older versions from:
https://www.gisinternals.com/query.html?content=filelist&file=release-1911-x64-gdal-2-4-3-mapserver-7-4-2.zip

**Comment by jratike80** [comment]
Command line test cases:

```
gdal_rasterize -dialect SQLite -burn 255 -burn 0 -burn 0 -ot Byte -ts 1000 1000 -sql "select ST_GeomFromText('POLYGON (( 554 539, 729 400, 501 378, 554 539 ))')" foo.jml mask.tif

gdal_rasterize -dialect SQLite -i -burn 255 -burn 0 -burn 0 -ot Byte -ts 1000 1000 -sql "select ST_GeomFromText('POLYGON (( 554 539, 729 400, 501 378, 554 539 ))')" foo.jml inverted_mask.tif
```

There must be some vector source as input and I used foo.jml but because the geometry is really generated on-the-fly with SQL the source can be just anything. And this is the result.

![kuva](https://user-images.githubusercontent.com/1751612/97693906-8438a780-1aaa-11eb-90ad-db452dc28c5b.png)
![kuva](https://user-images.githubusercontent.com/1751612/97693950-9286c380-1aaa-11eb-9941-f6c9609c6a6f.png)
