### ISSUE TITLE
Compiling 2.4.4 with HTTP -raster,vector- (ro): HTTP Fetching Wrapper

### ISSUE THREAD

**Issue by jvaldezch** [OSGeo/gdal#3125]
Hi, I'm trying to compile and old version of GDAL over a Debian system and I figure it out that I'm unable to read files from S3 using /vsis3 driver, I presume is that failed to compile with HTTP Fetching Wrapper support. Wonder how can I enable the flag during compilation.

**Comment by jratike80** [comment]
Did you find some bug or is this rather a question? Questions should go to the gdal-dev mailing list.

**Comment by rouault** [comment]
Make sure ./configure reports that it founds Curl. And make clean between build attempts
