### ISSUE TITLE
[3.2.0] Changelog  and libtiff

### ISSUE THREAD

**Issue by chacha21** [OSGeo/gdal#3135]
In the 3.2.0 release changelog it is written :

> Faster GTIFF Deflate compression/decompression through libdeflate (if using internal libtiff or libtiff > 4.1.0)

But latest libtiff at the current time is 4.1.0, so what does that mean ? Is it a typo instead of "libtiff >= 4.1.0" or is it a reference to some patched libtiff ?

**Comment by rouault** [comment]
> or is it a reference to some patched libtiff ?

the later. A reference to a not-yet-released libtiff version (presumably called 4.2.0)
