### ISSUE TITLE
Unable to add custom projection(s)

### ISSUE THREAD

**Issue by 1Map** [OSGeo/gdal#3136]
Before we could add a custom projection in file "epsg" (/usr/share/proj/epsg), like:

```
# SACRS_NO_15
<40015> +proj=tmerc +lat_0=0 +lon_0=15 +k=1 +x_0=0 +y_0=0 +axis=enu +ellps=WGS84 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs
# SACRS_NO_17
<40017> +proj=tmerc +lat_0=0 +lon_0=17 +k=1 +x_0=0 +y_0=0 +axis=enu +ellps=WGS84 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs
# SACRS_NO_19
<40019> +proj=tmerc +lat_0=0 +lon_0=19 +k=1 +x_0=0 +y_0=0 +axis=enu +ellps=WGS84 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs
# SACRS_NO_21
<40021> +proj=tmerc +lat_0=0 +lon_0=21 +k=1 +x_0=0 +y_0=0 +axis=enu +ellps=WGS84 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs
# SACRS_NO_23
<40023> +proj=tmerc +lat_0=0 +lon_0=23 +k=1 +x_0=0 +y_0=0 +axis=enu +ellps=WGS84 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs
# SACRS_NO_25
<40025> +proj=tmerc +lat_0=0 +lon_0=25 +k=1 +x_0=0 +y_0=0 +axis=enu +ellps=WGS84 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs
# SACRS_NO_27
<40027> +proj=tmerc +lat_0=0 +lon_0=27 +k=1 +x_0=0 +y_0=0 +axis=enu +ellps=WGS84 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs
# SACRS_NO_29
<40029> +proj=tmerc +lat_0=0 +lon_0=29 +k=1 +x_0=0 +y_0=0 +axis=enu +ellps=WGS84 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs
# SACRS_NO_31
<40031> +proj=tmerc +lat_0=0 +lon_0=31 +k=1 +x_0=0 +y_0=0 +axis=enu +ellps=WGS84 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs
# SACRS_NO_33
<40033> +proj=tmerc +lat_0=0 +lon_0=33 +k=1 +x_0=0 +y_0=0 +axis=enu +ellps=WGS84 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs
```

Now, with the latest version that file is no longer there.  My question is:

How can I add a custom projection to be recognized by all gdal commands?

**Comment by jratike80** [comment]
You can actually still add a file named as "epsg" into the directory where PROJ_LIB refers. Then you can use the +init syntax.
Example with a fake 900900 code that I added
```
gdalsrsinfo +init=epsg:900900
Warning 1: +init=epsg:XXXX syntax is deprecated. It might return a CRS with a non-EPSG compliant axis order.

PROJ.4 : +proj=merc +a=6378137 +b=6378137 +lat_ts=0 +lon_0=0 +x_0=0 +y_0=0 +k=1 +units=m +nadgrids=@null +wktext +no_defs
```
BTW we reallly mean that we want that questions are asked on the mailing list and not in a bug tracker. There are also other users who may have the same problem and they will learn from your case. Or some other user knows the answer and helps you.

**Comment by 1Map** [comment]
Thanks all good, but how would you do it on:

gdalsrsinfo and ogr2ogr ?

I tried:

`gdalsrsinfo +init=EPSG:40019
`
and it returns:

```
ERROR 1: PROJ: proj_create: crs not found
ERROR 1: ERROR - failed to load SRS definition from +init=EPSG:40019
```

**Comment by jratike80** [comment]
Works for me with commands
```
gdalsrsinfo +init=epsg:900900
ogr2ogr -f gml -a_srs +init=epsg:900900 test.gml test.shp
```
Commands were not sensitive to epsg vs. EPSG. 
I am using Windows, GDAL 3.2 and Proj 6.1.1 from gisinternals.com.

**Comment by 1Map** [comment]
Ok, mine at last works on:

`gdalsrsinfo +init=other.extra:40021`

and

`ogr2ogr -f gml -a_srs +init=other.extra:40021 test.gml test.shp`

Thanks for pointing me in the right direction

**Comment by 1Map** [comment]
NOTE the following on Ubuntu/Linux:

**DOES NOT WORK**
`gdalsrsinfo +init=EPSG:40019`

**WORK WITH Warning**
`gdalsrsinfo +init=epsg:40019`

**WORK WITHOUT Warning**
`gdalsrsinfo +init=other.extra:40019`
