### ISSUE TITLE
Ogr2ogr ERROR 1: MSSQL extents query returned a NULL value

### ISSUE THREAD

**Issue by koetter** [OSGeo/gdal#3140]
## Expected behavior and actual behavior.
When using ogr2ogr for importing geometries to MS SQL Server, I'm expecting ogr2ogr to create geometries in the MS SQL Server table. Data are imported, but the geometry-column is empty (NULL) and I'm getting this error:
```
ERROR 1: MSSQL extents query returned a NULL value
Warning 1: Failed to get extent for spatial index.
```
I'm getting the same error when importing from shape- and tab-files and from wfs-services.

Error appered after updating to version GDAL 3.1.4 - it was working fine before updating

## Steps to reproduce the problem.
`
ogr2ogr -f MSSQLSpatial "MSSQL:server=hostname;driver=SQL Server;database=Staging;trusted_connection=yes" .\testdata.shp -lco GEOMETRY_NAME=GEOM -lco GEOM_TYPE=GEOMETRY -nln testtable -a_srs "EPSG:25832" -overwrite -progress -skipfailures
`

Where hostname is the hostname of my PC

## Operating system: Microsoft Windows 10 Enterprise
OSArchitecture : 64-bit
Version        : 10.0.17134
BuildNumber    : 17134

## SQL Server version:
Microsoft SQL Server 2017 (RTM) - 14.0.1000.169 (X64)

## GDAL version and provenance
GDAL 3.1.4, released 2020/10/20 (OSGeo4Win)

**Comment by panya-term** [comment]
I found same this problem. Because I used GDAL 3.1.4, released 2020/10/20 (OSGeo4Win) from QGIS 3.16.0. 
But I can import same file in older gdalinfo --version ==> 2.4.1 released 2019/03/15 from QGIS 3.4.11.
I think gdal new version have problem to import shape file to SQLSERVER Database. You will change gdal version for import shape file to sqlserver.

**Operating system: Microsoft Windows 10 pro**
version 10.0.19042.685
build 19042.685

**SQL Server version:**
Microsoft SQL Server 2019 Developer

**GDAL version and provenance**
GDAL 2.4.1 released 2019/03/15(OSGeo4Win) from QGIS 3.4

**Comment by koetter** [comment]
**Work around**
The error can be fixed by specifying a newer driver in the connection string. According to this link ([https://mapserver.org/id/input/vector/mssql.html](https://mapserver.org/id/input/vector/mssql.html)) ogr2ogr uses the ODBC driver "SQL Server" by default, and this driver has not been updated by Microsoft since 2010. By installing ODBC driver 17 and specifying this in the connection string, ogr2ogr (GDAL version 3.1.4) can write to sql server i.e. 

`MSSQLSpatial "MSSQL:server=hostname;driver={ODBC Driver 17 for SQL Server};database=Staging;trusted_connection=yes"`

**Comment by jkr-wrk** [comment]
I had exact this problem with QGis 3.16.1 with lots of other problems getting it to run. I finally found out that I had to use QGis 3.4.11 do get it to work.


So if you don't want to install the driver 17 and you need to load data into the MSSQL table you can do this by using the 3.4 version of QGis. This can load the data with the ogr2ogr function in OSGEO4Win.

ogr2ogr -overwrite -f MSSQLSpatial "MSSQL:server=xxxxxx.database.windows.net;database=myTargetDatabase;UID=myUser;PWD=myPass" -f PostgreSQL PG:"host=127.0.0.1 port=5432 dbname=mySourceDatabase user=sourceUser password=sourcePass" public.myTable -progress

**Comment by carlsunderman** [comment]
gdal 3.3.0dev has this issue as well, even with the ODBC Driver 17

**Comment by abdullahsaleh14** [comment]
> **Work around**
> The error can be fixed by specifying a newer driver in the connection string. According to this link (https://mapserver.org/id/input/vector/mssql.html) ogr2ogr uses the ODBC driver "SQL Server" by default, and this driver has not been updated by Microsoft since 2010. By installing ODBC driver 17 and specifying this in the connection string, ogr2ogr (GDAL version 3.1.4) can write to sql server i.e.
> 
> `MSSQLSpatial "MSSQL:server=hostname;driver={ODBC Driver 17 for SQL Server};database=Staging;trusted_connection=yes"`

This fixed my issues.

**Comment by williamorrie** [comment]
Changing the driver did not work for me. Downgrading from 3.16 to 3.4 was the only solution.

**Comment by OculiViridi** [comment]
I'm having a similiar issue, but I'm not getting errors from the below command, but instead I see that the table is created on SQL Server database but then no rows is loaded inside.
I've no output after launching the command, but the layer is 80 MB size and the command terminates in a couple of seconds...

### Layer's specifications from QGIS

![image](https://user-images.githubusercontent.com/42179710/135991957-5a027557-b484-4a26-b2d6-be5a7be70ba5.png)

### Command

`ogr2ogr -f MSSQLSpatial "MSSQL:server=mydbhost.dev\db2017;driver={SQL Server Native Client 11.0};database=GeoData;trusted_connection=yes" "Layer1_WGS84.shp" -a_srs EPSG:32632 -nln Layer1 -nlt MULTIPOLYGON -progress -overwrite -skipfailures`

I've also tried with the following options:
- `-lco UPLOAD_GEOM_FORMAT=wkt` (and `wkb` too)
- `driver={ODBC Driver 17 for SQL Server}` (and without specifing any driver too)
- `-nlt POLYGON`

But I always get the same behaviour.

### Environment
OS: **Windows 10 v10.0.19043.1237**
SQL Server: **SQL Server 2017 v14.0.3356.20**
GDAL: **GDAL 3.3.1, released 2021/06/28**
OGR2OGR: installed with **QGIS v3.20.3-Odense**

**Comment by GISFYFathima** [comment]
This works in windows server

- Download ODBC driver

- Open OSGeo4W Shell

C:\OSGeo4W\bin>ogr2ogr -f MSSQLSpatial "MSSQL:server=XXXX;driver={ODBC Driver 17 for SQL Server};database=TestDatabase;uid=XXX;pwd=XXX" C:\Shapefiles-Test\District1.shp -a_srs EPSG:4326 -nln Layer6 --config MSSQLSPATIAL_USE_BCP FALSE

**Comment by LukeHSC** [comment]
GISFYFathima - what OS/SQL/GDAL/ogr2ogr versions are you using? 

> This works in windows server
> 
> * Download ODBC driver
> * Open OSGeo4W Shell
> 
> C:\OSGeo4W\bin>ogr2ogr -f MSSQLSpatial "MSSQL:server=XXXX;driver={ODBC Driver 17 for SQL Server};database=TestDatabase;uid=XXX;pwd=XXX" C:\Shapefiles-Test\District1.shp -a_srs EPSG:4326 -nln Layer6 --config MSSQLSPATIAL_USE_BCP FALSE

**Comment by elpaso** [comment]
The issue with ogr2ogr import into MSSQL with BCP option on (which is the default) has been solved with https://github.com/OSGeo/gdal/pull/7792.

Some of the symptoms reported in this ticket might be related to that and they might be now fixed. 

I'd recommend to close this ticket and re-open in case the problem persists with newer GDAL versions that contain the  patch mentioned above.

**Comment by MohammadRezaNehi** [comment]
ogr2ogr -skipfailures  -progress -f "MSSQLSpatial" "MSSQL:server=.; driver={ODBC Driver 17 for SQL Server}; database=GisTemp; trusted_connection=yes ; Encrypt=no" "address\name.shp"

**Comment by jratike80** [comment]
@MohammadRezaNehi , what does your comment mean?

**Comment by MohammadRezaNehi** [comment]
jratike80
This command solves the problem

**Comment by MohammadRezaNehi** [comment]
> @MohammadRezaNehi , what does your comment mean?

https://github.com/jratike80

**Comment by MohammadRezaNehi** [comment]
> @MohammadRezaNehi , what does your comment mean?

This command will solve the problem
