### ISSUE TITLE
Add a UUID data type

### ISSUE THREAD

**Issue by bjornharrtell** [OSGeo/gdal#3141]
Required for https://github.com/OSGeo/gdal/issues/3057 and other data sources that have a native UUID/GUID datatype.

@rouault would you welcome such an addition?

**Comment by rouault** [comment]
> @rouault would you welcome such an addition?

I'd see that as a OFSTUUID sub type of the OFTString type (similarly as we deal with JSON). The OpenFileGDB driver could make use of it (provided the string representation of that type is somewhat universal)

**Comment by bjornharrtell** [comment]
On the top of my head drivers that could make use of it would be `pg`, `pgdump`, `filegdb`, `openfilegdb`, `oci`, `wfs` and `mssqlspatial`.

**Comment by sgillies** [comment]
@rouault what are the advantages of a UUID type over just using the existing string type?

**Comment by bjornharrtell** [comment]
@sgillies my motivation is that when using OGR as a way to transfer data from one source to another it can be important that the transformation doesn't convert datatypes (if possible) as it's a kind of a loss of information. For exotic datatypes coercion can  perhaps unavoidable but UUID is, in my opinion, an important and common datatype.
