### ISSUE TITLE
ogrinfo -json

### ISSUE THREAD

**Issue by andrewharvey** [OSGeo/gdal#3143]
gdalinfo has a `-json` option to provide metadata in a more machine readable format, would be nice to see ogrinfo support `-json`.

**Comment by codajo** [comment]
That would be fine if both tools could have the json option

**Comment by rouault** [comment]
-json output to ogrinfo was added in GDAL 3.7 : https://gdal.org/programs/ogrinfo.html#cmdoption-ogrinfo-json

**Comment by codajo** [comment]
Great, thank you for the response.
