### ISSUE TITLE
GDAL 3.2.0 build error on Fedora 33

### ISSUE THREAD

**Issue by devrimgunduz** [OSGeo/gdal#3146]
Hi,

GDAL 3.2.0 fails to build on Fedora 33. Can you please let me know how I can fix it?

Thanks!
Devrim

`In file included from /usr/include/string.h:519,
                 from /build/gdal32/master/gdal-3.2.0-fedora/port/cpl_port.h:141,
                 from /build/gdal32/master/gdal-3.2.0-fedora/gcore/gdal_frmts.h:34,
                 from doq1dataset.cpp:30:
In function 'strncpy',
    inlined from 'DOQGetField(unsigned char*, int)' at doq1dataset.cpp:66:12,
    inlined from 'DOQ1Dataset::Open(GDALOpenInfo*)' at doq1dataset.cpp:367:30:
/usr/include/bits/string_fortified.h:106:34: warning: 'strncpy' output may be truncated copying 24 bytes from a string of length 211 [-Wstringop-truncation]
  106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
      |          ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In function 'strncpy',
    inlined from 'DOQGetField(unsigned char*, int)' at doq1dataset.cpp:66:12,
    inlined from 'DOQ1Dataset::Open(GDALOpenInfo*)' at doq1dataset.cpp:368:30:
/usr/include/bits/string_fortified.h:106:34: warning: 'strncpy' output may be truncated copying 24 bytes from a string of length 187 [-Wstringop-truncation]
  106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
      |          ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In function 'strncpy',
    inlined from 'DOQGetField(unsigned char*, int)' at doq1dataset.cpp:66:12,
    inlined from 'DOQ1Dataset::Open(GDALOpenInfo*)' at doq1dataset.cpp:381:37:
/usr/include/bits/string_fortified.h:106:34: warning: 'strncpy' output may be truncated copying 12 bytes from a string of length 440 [-Wstringop-truncation]
  106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
      |          ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In function 'strncpy',
    inlined from 'DOQGetField(unsigned char*, int)' at doq1dataset.cpp:66:12,
    inlined from 'DOQ1Dataset::Open(GDALOpenInfo*)' at doq1dataset.cpp:382:37:
/usr/include/bits/string_fortified.h:106:34: warning: 'strncpy' output may be truncated copying 12 bytes from a string of length 428 [-Wstringop-truncation]
  106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));

In file included from /usr/include/stdio.h:866,
                 from /build/gdal32/master/gdal-3.2.0-fedora/port/cpl_port.h:137,
                 from /build/gdal32/master/gdal-3.2.0-fedora/port/cpl_error.h:34,
                 from /build/gdal32/master/gdal-3.2.0-fedora/port/cpl_string.h:35,
                 from landataset.cpp:30:
/usr/include/bits/stdio2.h:253:13: error: expected unqualified-id before '+' token
  253 | extern char *__REDIRECT (__fgets_chk_warn,
      |             ^
/usr/include/bits/stdio2.h: In function 'char* fgets(char*, int, FILE*)':
/usr/include/bits/stdio2.h:268:9: error: '__fgets_chk_warn' was not declared in this scope; did you mean '__fgets_chk'?
  268 |  return __fgets_chk_warn (__s, __bos (__s), __n, __stream);
      |         ^~~~~~~~~~~~~~~~
      |         __fgets_chk
make[3]: *** [../../GDALmake.opt:646: ../o/landataset.lo] Error 1

ake[5]: *** [GNUmakefile:27: ../../o/cadtables.lo] Error 1
make[5]: Leaving directory '/build/gdal32/master/gdal-3.2.0-fedora/ogr/ogrsf_frmts/cad/libopencad'
make[4]: *** [../../../GDALmake.opt:659: libopencad-target] Error 2
make[4]: Leaving directory '/build/gdal32/master/gdal-3.2.0-fedora/ogr/ogrsf_frmts/cad'
make[3]: *** [../../GDALmake.opt:659: cad-target] Error 2
make[3]: Leaving directory '/build/gdal32/master/gdal-3.2.0-fedora/ogr/ogrsf_frmts'
make[2]: *** [GNUmakefile:58: sublibs] Error 2
make[2]: Leaving directory '/build/gdal32/master/gdal-3.2.0-fedora/ogr'
make[1]: *** [GNUmakefile:100: ogr-target] Error 2

`

**Comment by rouault** [comment]
The warnings in doq1dataset.cpp look to me like false positives, but they aren't failing the .
The error in landataset.cpp is a bit more mysterious. Is it the extensive error log for that ? Just #include "cpl_string.h" as the first include would be the error ? But they are other files with that pattern.

**Comment by devrimgunduz** [comment]
Have a better one:

`In file included from /usr/lib/gcc/x86_64-redhat-linux/10/include/immintrin.h:71,
                 from /usr/lib/gcc/x86_64-redhat-linux/10/include/x86intrin.h:32,
                 from /home/devrim/belgeler/Devrim/Projects/repo/pgrpms/rpm/redhat/master/common/gdal32/main/gdal-3.2.0-fedora/port/cpl_port.h:716,
                 from irisdataset.cpp:32:
/usr/lib/gcc/x86_64-redhat-linux/10/include/avx512vldqintrin.h:288:17: error: expected unqualified-id before '.*' token
  288 | extern __inline __m256i
      |                 ^~~~~~~
make[3]: *** [../../GDALmake.opt:646: ../o/irisdataset.lo] Error 1
make[3]: Leaving directory '/home/devrim/Documents/Devrim/Projects/repo/pgrpms/rpm/redhat/master/common/gdal32/main/gdal-3.2.0-fedora/frmts/iris'
make[2]: *** [GNUmakefile:15: iris-install-obj] Error 2
make[2]: Leaving directory '/home/devrim/Documents/Devrim/Projects/repo/pgrpms/rpm/redhat/master/common/gdal32/main/gdal-3.2.0-fedora/frmts'
make[1]: *** [GNUmakefile:114: frmts-target] Error 2
make[1]: *** Waiting for unfinished jobs....
`

**Comment by rouault** [comment]
in https://github.com/OSGeo/gdal/issues/2859, you also had issues that were apparently about avx stuff and were something different (but I'm not clear how you solved it)

**Comment by jratike80** [comment]
It seems that you are asking a question in a bug tracker but because it is easier to have discussion here than in the mailing list and because Even is answering you anyway so take this just as a reminder for other kind of questions you may have in the future.

**Comment by devrimgunduz** [comment]
@jratike80 I think build errors should be in the  bug tracker, no?

**Comment by devrimgunduz** [comment]
Anyway, I don't know what happened (I did not change anything), but the error went away. Closing.

**Comment by jratike80** [comment]
Certainly build errors belong to bug tracker if they are GDAL bugs. Some other users have had errors in their own build scripts or  build errors have been caused by their special environment. I do not claim that you did not fase some real bug but I am happy that you are fine with your build now.
