### ISSUE TITLE
GDAL picks up 2 proj versions

### ISSUE THREAD

**Issue by devrimgunduz** [OSGeo/gdal#3148]
Hi,

I'm building custom GDAL packages for PostgreSQL RPM repository, and recently got 2 reports that GDAL picks two separate versions of libproj.so:

ldd /usr/gdal31/lib/libgdal.so | grep -i proj
	libproj.so.15 => /lib64/libproj.so.15 (0x00007f8083f0c000)
	libproj.so.19 => /usr/proj71/lib/libproj.so.19 (0x00007f807a0ac000)

This happens when there are 2 PROJ versions are installed on the OS:

* PROJ 6.3, provided by OS, installed under /usr/lib64
* PROJ 7.1, provided by my packages, installed under /usr/proj71

This is how I use CFLAGS and LDFLAGS:

https://git.postgresql.org/gitweb/?p=pgrpms.git;a=blob;f=rpm/redhat/master/common/gdal31/master/gdal31.spec;h=1052ece5f751598413c2c724ffe46b36f586e313;hb=HEAD#l344 

The custom macros refer to /usr/libgeotiff16, /usr/proj71/lib, /usr/libspatialite50, and  /usr/ogdi41 directories.

This is how I change libproj.so to libproj.so.19:

https://git.postgresql.org/gitweb/?p=pgrpms.git;a=blob;f=rpm/redhat/master/common/gdal31/master/gdal31.spec;h=1052ece5f751598413c2c724ffe46b36f586e313;hb=HEAD#l320

This is how I configure GDAL:

https://git.postgresql.org/gitweb/?p=pgrpms.git;a=blob;f=rpm/redhat/master/common/gdal31/master/gdal31.spec;h=1052ece5f751598413c2c724ffe46b36f586e313;hb=HEAD#l409

The only hardcoded path is here:

ogr/ogrsf_frmts/pgeo/ogrpgeodriver.cpp

and patching it with changing them to point to my custom packages did not helo? 

Am I doing something wrong, or is there an issue with GDAL?

I can provide any logs you want.

Thanks!

Regards, Devrim

**Comment by rouault** [comment]
I'd say it is undefined behaviour if you've PROJ versions that are reachable by different -L path. There's certainly something else in the GDAL linking line that adds -L/usr/lb64. . You could try manually editing GDALmake.opt after configure to remove occurences of "-L/usr/lib64 " (with trainling space) (although we have some logic to do that for a few deps I believe), but I'd suggest removing the system proj-dev package

**Comment by rouault** [comment]
I think this can be closed ?
