### ISSUE TITLE
Python bindings ogr module removed from gdal 3.2 / Not in release Notes

### ISSUE THREAD

**Issue by cpaulik** [OSGeo/gdal#3149]
## Expected behavior and actual behavior.

```python
import ogr
```
gives

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'ogr'
```

in gdal 3.2.

I know that we should use `from osgeo import ogr` but since I could not find this breaking change in the release notes I was wondering if it was removed by mistake or forgotten in the release notes. 

It still works under gdal 3.1

## Operating system

Arch linux

## GDAL version and provenance

gdal 3.2 from conda-forge

**Comment by rouault** [comment]
"import ogr" still works fine for me with 3.2 . I can't think of any related change.

**Comment by cpaulik** [comment]
Thanks. I've created https://github.com/conda-forge/gdal-feedstock/issues/419 to see if it is a conda-forge issue. 

Closing this for now.

**Comment by cpaulik** [comment]
`conda-forge` claimed to have changed nothing. But they needed to remove their `import ogr` statements in their python tests. 

Does gdal have a CI test for this import? If so then something in the middle goes wrong.

**Comment by ocefpaf** [comment]
> "import ogr" still works fine for me with 3.2 . I can't think of any related change.

It did not work in our builds. Should we activate a flag or something to enable it?

**Comment by rouault** [comment]
@cpaulik I can actually reproduce the issue now. The fact that it worked was due to testing in a dev environement where "ogr" is a subdirectory... So it doesn't appear that "import ogr" is tested in CI. That said this has been deprecated for 10 years or so.

@idanmiara I believe this change might be caused by your rework of setup.py when moving the utilities under osgeo/scripts . The gdal.py, ogr.py, etc. files that used to be generated under swig/python/build/lib.XXXXXX are no longer there

I'm a bit hesitating what to do now: should we restore the "import ogr" way or just update our NEWS to reflect the change...

**Comment by idanmiara** [comment]
> @idanmiara I believe this change might be caused by your rework of setup.py when moving the utilities under osgeo/scripts . The gdal.py, ogr.py, etc. files that used to be generated under swig/python/build/lib.XXXXXX are no longer there
> 
> I'm a bit hesitating what to do now: should we restore the "import ogr" way or just update our NEWS to reflect the change...

I guess I could have been mistaken to think that the py_modules section in setup.py is deprecated.
I hope this fixes this issue:
https://github.com/OSGeo/gdal/pull/3150

**Comment by ocefpaf** [comment]
> I'm a bit hesitating what to do now: should we restore the "import ogr" way or just update our NEWS to reflect the change...

I'm only one data point and, while restoring it would be "easy," the cat is out of the bag. Document the change and move on.

PS: thanks for all the work on gdal!

**Comment by rouault** [comment]
Polling the wider community : https://lists.osgeo.org/pipermail/gdal-dev/2020-November/052921.html

**Comment by cpaulik** [comment]
I'm happy with documenting it and moving forward. We've already changed our imports.

**Comment by jomey** [comment]
How about doing a quick poll here by reacting with :+1: for moving on and :-1: for restoring?
