### ISSUE TITLE
gpkg output for ogr2ogr ignores linux acl

### ISSUE THREAD

**Issue by robin-snt** [OSGeo/gdal#3152]
## Expected behavior and actual behavior.

When using `ogr2ogr` to convert data to `gpkg` format, the output file ignores the linux acl rules somehow.
It is expected that acl rules apply, which they do when using other output formats, like ESRI Shapefile or CSV.

## Steps to reproduce the problem.

```sh
mkdir foo
setfacl -Rdm o::rwX  foo
cd foo
ogr2ogr -f GPKG holmestrand.gpkg holmestrand.csv
ls -l holmestrand.gpg
```

Expected: `other` to have `rw` access, instead just `r`.

Content of `holmestrand.csv` uploaded as [`holmestrand.txt`](https://github.com/OSGeo/gdal/files/5500922/holmestrand.txt) as Github did not allow me to upload a csv file:

## Operating system

Ubuntu 18.04 64 bit

## GDAL version and provenance

3.0.4 version from ubuntugis-unstable PPA

**Comment by rouault** [comment]
As far as I can see, this is a SQLite3 upstream issue as I could reproduce it by creating a simple database with "echo "create table foo(id);" | sqlite3 foo.db"
It is also reported here:
https://stackoverflow.com/questions/58626363/database-created-by-sqlite-does-not-inherit-default-acl-set-for-parent-directory
You could report that to SQLite3 upstream given the instructions given at https://www.sqlite.org/src/wiki?name=Bug+Reports

**Comment by robin-snt** [comment]
I see. Thank you so much for your time and help.
