### ISSUE TITLE
cryptopp/aes.h: No such file or directory

### ISSUE THREAD

**Issue by saultdon** [OSGeo/gdal#3154]
## Expected behavior and actual behavior.

For example (please modify !!!): Compiling 3.2.0 and getting "cryptopp/aes.h: No such file or directory"

But that file is owned by linux-headers found at:
```
pacman -Ql linux-headers | grep aes.h
linux-headers /usr/lib/modules/5.9.4-arch1-1/build/include/config/crypto/aes.h
linux-headers /usr/lib/modules/5.9.4-arch1-1/build/include/config/crypto/dev/padlock/aes.h
linux-headers /usr/lib/modules/5.9.4-arch1-1/build/include/config/crypto/lib/aes.h
linux-headers /usr/lib/modules/5.9.4-arch1-1/build/include/crypto/aes.h
```

## Steps to reproduce the problem.

For example (please modify !!!):
```
   ./configure --prefix=/usr --with-netcdf --with-libtiff --with-sqlite3 --with-geotiff \
           --with-mysql --with-curl --with-hdf5 --with-perl --with-geos \
           --with-png --with-poppler --with-spatialite --with-openjpeg --with-fgdb=/usr

make
```

Results in:

```
checking for cryptopp... testcryptopp.cpp:1:10: fatal error: cryptopp/aes.h: No such file or directory
     | #include <cryptopp/aes.h>
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
no
checking for crypto... checking for EVP_sha256 in -lcrypto... yes
```

## Operating system

For example (please modify !!!): Arch Linux 64-bit 5.9.4-arch1-1

## GDAL version and provenance

For example (please modify !!!): from GDAL 3.2.0 source

**Comment by rouault** [comment]
> But that file is owned by linux-headers found at:

GDAL will not use Linux kernel crypto headers :-) It is expecting libcrypto++-dev or whatever it is called on Arch Linux to be installed.

**Comment by saultdon** [comment]
> > But that file is owned by linux-headers found at:
> 
> GDAL will not use Linux kernel crypto headers :-) It is expecting libcrypto++-dev or whatever it is called on Arch Linux to be installed.

Awesome, thanks. Looks like for Arch Linux it's found in the community/crypto++ package.
