### ISSUE TITLE
FlatGeobuf: editing capabilities does not work in QGIS nightly Windows

### ISSUE THREAD

**Issue by bjornharrtell** [OSGeo/gdal#3157]
Error output when trying to change and add a feature:

Errors: ERROR: 1 feature(s) not added.
  
  Provider errors:
      OGR error syncing to disk: Cannot rename files
      OGR error changing geometry: feature 150 not found
      OGR error syncing to disk: Cannot rename files
      OGR error creating feature -27: Cannot rename files
      OGR error syncing to disk: Cannot rename files

**Comment by bjornharrtell** [comment]
I've also been able to get crashes like:

Crash ID: 6d75d55b940a0476aa310b3aafce4c1966e9f93b


Stack Trace


VSIFWriteL :
IGMLReader::~IGMLReader :
OGREditableLayer::ICreateFeature :
QgsOgrLayer::CreateFeature qgsogrprovider.cpp:6310
QgsOgrProvider::addFeaturePrivate qgsogrprovider.cpp:1845
QgsOgrProvider::addFeatures qgsogrprovider.cpp:1883
QgsVectorLayerEditBuffer::commitChanges qgsvectorlayereditbuffer.cpp:630
QgsVectorLayer::commitChanges qgsvectorlayer.cpp:3355
QgisApp::toggleEditing qgisapp.cpp:11111

**Comment by bjornharrtell** [comment]
And finally I get only this:

2020-11-07T23:09:32     CRITICAL    Layer countries : OGR error syncing to disk: Cannot rename files

When doing just a single vertex change on existing data and then end edit session and save.

**Comment by rouault** [comment]
Is this on Windows ? I remember we've had similar issues where quick rename of files fail on Windows. The reason isn't completely clear. Might be antivirus kicking in and holding a lock on a file being renamed. For the shapefile driver for example, we have a logic where on Windows we rewrite in place a file instead of renaming. Look at the logic towards the end of OGRShapeDataSource::RecompressIfNeeded()

**Comment by bjornharrtell** [comment]
@rouault yep Windows, installed using OSGeo4W it's the only trivial/easy way I have to get a working QGIS and GDAL binary nightly build. Thanks for the tip, will investigate.

**Comment by bjornharrtell** [comment]
I would assume that QGIS have a lock on the file.

**Comment by rouault** [comment]
> I would assume that QGIS have a lock on the file.

that might also be it. But in qgsogrprovider.cpp, there is logic to try to invalidate cached connections for feature iterators when updating a layer (in QgsOgrProvider::syncToDisc() ), but it didn't prove to be always sufficient. I've a vague souvenir to have observer weirdness outside of QGIS context with file renaming on Windows.

**Comment by bjornharrtell** [comment]
Tried edits with the same QGIS for CSV and GeoJSON formats and it works without issues but I haven't determined if QGIS has some quirks for those formats or if it uses GDAL as is.

**Comment by bjornharrtell** [comment]
I've now compiled QGIS + GDAL on Ubuntu focal and I have made a fair bit of editing with new, updated, and deleted features without issues so it definitely looks like a Windows issue... One suspect thing I see in debug output though is:

ERROR 1: Requested feature id is out of bounds

Not sure what action is causing it.

**Comment by bjornharrtell** [comment]
I've searched around in QGIS source to learn if something special is done for CSV and/or GeoJSON but cannot find any evidence that there is special treatment for those. So I do wonder how that can work without issues on QGIS under Windows... any ideas @rouault?

**Comment by jef-n** [comment]
> I've searched around in QGIS source to learn if something special is done for CSV and/or GeoJSON but cannot find any evidence that there is special treatment for those. So I do wonder how that can work without issues on QGIS under Windows... any ideas @rouault?

opened files cannot be renamed on windows - unlike *x.  I'd say CSV has the same issue (qgis/QGIS#35144).

**Comment by rouault** [comment]
@bjornharrtell 
I was partly right&wrong regarding QgsOgrProvider::syncToDisc(). It only invalidates connections in a particular case. What you could try is to add the following at the beginning of the method
```
QgsOgrConnPool::instance()->invalidateConnections( QgsOgrProviderUtils::connectionPoolId( dataSourceUri( true ), mShareSameDatasetAmongLayers ) );
```
And you would probably have to modify the end of QgsOgrProvider::changeAttributeValues() and QgsOgrProvider::changeGeometryValues() to call QgsOgrProvider::syncToDisc() instead of calling mOgrLayer->SyncToDisk() + QgsOgrConnPool::instance()->invalidateConnections() (invalidateConnections() has to be called before OGRLayer::SyncToDisk())

**Comment by bjornharrtell** [comment]
Thanks for the input @jef-n and @rouault, I will make an attempt. But it will be a bit in the dark as I will do it from nix dev env, I do not think I will be able (mentally or otherwise) to setup a windows development machine.

**Comment by bjornharrtell** [comment]
Verified fix in QGIS is effective.
