### ISSUE TITLE
Large Rasters not produced correctly using WMS drivers

### ISSUE THREAD

**Issue by k-cybulski** [OSGeo/gdal#3191]
## Expected behavior and actual behavior.

GDAL fails to produce correct rasters from WMS version 1.3.0 using RasterIO when dealing with large images. The images given by GDAL are a composition of multiple images wrongly cropped together which _would be_ correct if their positions were mirrored along the diagonal from bottom left to top right. Also, they seem to be slightly scaled wrongly. Below I have two examples of expected images and images obtained from GDAL's RasterIO.

I am not sure about the details, but given the weird mirroring behaviour I believe this may be related to [axis ordering in WMS 1.3.0 being dependent on the CRS used](https://docs.geoserver.org/stable/en/user/services/wms/basics.html#axis-ordering). I have not tested WMS 1.1.1 to verify this hypothesis, though.

### First example
Using this string to initialize a GDALDataset: 
```
WMS:https://mapy.geoportal.gov.pl/wss/service/PZGIK/ORTO/WMS/HighResolution?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&STYLES=default&LAYERS=Raster&CRS=EPSG:2180&format=image/jpeg&BBOX=506600,357600,507400,358400&MINRESOLUTION=0.2
```
I expected to be able to obtain an image like this one: https://mapy.geoportal.gov.pl/wss/service/PZGIK/ORTO/WMS/HighResolution?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&STYLES=default&LAYERS=Raster&CRS=EPSG:2180&format=image/jpeg&BBOX=506600,357600,507400,358400&width=4000&height=4000

Expected image:
![poznan_target](https://user-images.githubusercontent.com/31585687/99427541-d597c200-2905-11eb-9b45-5d56c3cfadb6.jpg)

Obtained image:
![poznan_test](https://user-images.githubusercontent.com/31585687/99426837-f14e9880-2904-11eb-868b-63aa4d3a4bd4.jpg)

### Second example
Using this string to initialize a GDALDataset: 
```
WMS:https://www.wms.nrw.de/geobasis/wms_nw_dop?service=WMS&version=1.3.0&request=GetMap&layers=nw_dop_rgb&styles=&crs=EPSG:3034&format=image/jpeg&bbox=2675200,3732300,2676000,3733100&minresolution=0.2
```
I expected to be able to obtain an image like this one: https://www.wms.nrw.de/geobasis/wms_nw_dop?service=WMS&version=1.3.0&request=GetMap&layers=nw_dop_rgb&styles=&crs=EPSG:3034&format=image/jpeg&bbox=2675200,3732300,2676000,3733100&width=4000&height=4000

Expected image:
![aachen_target](https://user-images.githubusercontent.com/31585687/99427774-1f80a800-2906-11eb-9d81-48b0889a48ee.jpg)

Obtained image:
![aachen_test](https://user-images.githubusercontent.com/31585687/99427794-25768900-2906-11eb-9420-9a9c73d48d90.jpg)

## Steps to reproduce the problem.

The error occurs when attempting to read large rasters from a WMS dataset using RasterIO. I am not sure about the precise size, though I think above 1000 by 1000 pixels should be enough to trigger this. It will occur if GDAL sends multiple requests to the WMS server to produce an image.

The minimal script below was made to reproduce errors presented. This script should generate the second example from the previous section.
```c++
#include <cstring>
#include <gdal/gdal_priv.h>

// This script should produce an image equivalent to https://www.wms.nrw.de/geobasis/wms_nw_dop?service=WMS&version=1.3.0&request=GetMap&layers=nw_dop_rgb&styles=&crs=EPSG:3034&format=image/jpeg&bbox=2675200,3732300,2676000,3733100&width=4000&height=4000


int main(int argc, char** argv)
{
    int width = 4000;
    int height = width;
    int numberOfBands = 4;
    int numberOfBytes = width * height * numberOfBands;
    unsigned char* data = new unsigned char[numberOfBytes];
    std::memset(data, 255, numberOfBytes);

    GDALAllRegister();

    CPLStringList optionList;
    
    const char* wmsUrl = "WMS:https://www.wms.nrw.de/geobasis/wms_nw_dop?service=WMS&version=1.3.0&request=GetMap&layers=nw_dop_rgb&styles=&crs=EPSG:3034&format=image/jpeg&bbox=2675200,3732300,2676000,3733100&minresolution=0.2";
    GDALDataset* readDataset = static_cast<GDALDataset*>(GDALOpenEx(wmsUrl, GDAL_OF_RASTER | GA_ReadOnly, nullptr, optionList.List(), nullptr));
    int rasterCount = readDataset->GetRasterCount();

    CPLErr error = readDataset->RasterIO(GDALRWFlag::GF_Read,
                      0, 0,
                      width, height,
                      data,
                      width, height,
                      GDALDataType::GDT_Byte,
                      rasterCount,
                      nullptr,
                      numberOfBands, width * static_cast<int>(numberOfBands), 1, nullptr);

    GDALDriver *driver = GetGDALDriverManager()->GetDriverByName("GTiff");
    CPLStringList optionList2;
    GDALDataset *writeDataset = driver->Create("aachen_test.tiff", width, height, numberOfBands, GDT_Byte, optionList2.List());
    CPLErr error2 = writeDataset->RasterIO(GDALRWFlag::GF_Write,
                      0, 0,
                      width, height,
                      data,
                      width, height,
                      GDALDataType::GDT_Byte,
                      numberOfBands,
                      nullptr,
                      numberOfBands, width * numberOfBands, 1, nullptr);
    writeDataset->FlushCache();
}

```
To reproduce the first example from the previous section, set the `wmsUrl` variable to
```
WMS:https://mapy.geoportal.gov.pl/wss/service/PZGIK/ORTO/WMS/HighResolution?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&STYLES=default&LAYERS=Raster&CRS=EPSG:2180&format=image/jpeg&BBOX=506600,357600,507400,358400&MINRESOLUTION=0.2
```
before initializing `readDataset`.

## Operating system

Ubuntu 20.04.1 LTS 64 bit

## GDAL version and provenance

I have reproduced this error in two versions of GDAL compiled from source (with [WMS driver](https://gdal.org/drivers/raster/wms.html), so with Ubuntu package `libcurl4-gnutls-dev`):
 - The current master (commit `57c38531b69ea2afd096a80d8d72c292ac4855d9`)
 - The branch `release/3.0`

**Comment by rouault** [comment]
Fixed in master and release/3.2 branch.
You can workaround the issue by adding "&BBOXORDER=yxYX" to your connection string
