### ISSUE TITLE
Translate raster in .asc format (AAIgrid) with a specific value NODATA_value=-9999 in the header is replaced by nan in the main text

### ISSUE THREAD

**Issue by ilikeqgis** [OSGeo/gdal#3195]
## Expected behavior and actual behavior.
I tried to create an .asc file from a Geotiff file with NODATA_value=nan by creating this .asc file with NODATA_value=-9999.
I use gdal_translate and I get for my .asc file a header with NODATA_value=-9999 but the main text is with nan...

**I get this :** 
[Myfile_export_asc_1.zip](https://github.com/OSGeo/gdal/files/5560230/Myfile_export_asc_1.zip)

ncols        10
nrows        9
xllcorner    698362.000000000000
yllcorner    6946119.000000000000
cellsize     1.000000000000
**NODATA_value  -9999**
 **nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan** 55.299999237060546875 55.299999237060546875 55.200000762939453125 55.200000762939453125 55.200000762939453125
 **nan nan nan nan** 55.299999237060546875 55.299999237060546875 55.299999237060546875 55.299999237060546875 55.200000762939453125 55.200000762939453125
 **nan nan nan** 55.40000152587890625 55.299999237060546875 55.299999237060546875 55.299999237060546875 55.299999237060546875 55.299999237060546875 55.200000762939453125
 nan nan 55.40000152587890625 55.40000152587890625 55.40000152587890625 55.299999237060546875 55.299999237060546875 55.299999237060546875 55.299999237060546875 55.200000762939453125
 nan 55.5 55.40000152587890625 55.40000152587890625 55.40000152587890625 55.40000152587890625 55.299999237060546875 55.299999237060546875 55.299999237060546875 55.299999237060546875
 55.5 55.5 55.40000152587890625 55.40000152587890625 55.40000152587890625 55.40000152587890625 55.40000152587890625 55.299999237060546875 55.299999237060546875 55.299999237060546875
 55.5 55.5 55.5 55.40000152587890625 55.40000152587890625 55.40000152587890625 55.40000152587890625 55.299999237060546875 55.299999237060546875 55.299999237060546875

**I expect this :** 
[Myfile_export_asc_2.zip](https://github.com/OSGeo/gdal/files/5560232/Myfile_export_asc_2.zip)

ncols        10
nrows        9
xllcorner    698362.000000000000
yllcorner    6946119.000000000000
cellsize     1.000000000000
**NODATA_value  -9999
 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999
 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999 -9999
 -9999 -9999 -9999 -9999 -9999** 55.299999237060546875 55.299999237060546875 55.200000762939453125 55.200000762939453125 55.200000762939453125
 **-9999 -9999 -9999 -9999** 55.299999237060546875 55.299999237060546875 55.299999237060546875 55.299999237060546875 55.200000762939453125 55.200000762939453125
 **-9999 -9999 -9999** 55.40000152587890625 55.299999237060546875 55.299999237060546875 55.299999237060546875 55.299999237060546875 55.299999237060546875 55.200000762939453125
 **-9999 -9999** 55.40000152587890625 55.40000152587890625 55.40000152587890625 55.299999237060546875 55.299999237060546875 55.299999237060546875 55.299999237060546875 55.200000762939453125
 **-9999** 55.5 55.40000152587890625 55.40000152587890625 55.40000152587890625 55.40000152587890625 55.299999237060546875 55.299999237060546875 55.299999237060546875 55.299999237060546875
 55.5 55.5 55.40000152587890625 55.40000152587890625 55.40000152587890625 55.40000152587890625 55.40000152587890625 55.299999237060546875 55.299999237060546875 55.299999237060546875
 55.5 55.5 55.5 55.40000152587890625 55.40000152587890625 55.40000152587890625 55.40000152587890625 55.299999237060546875 55.299999237060546875 55.299999237060546875

## Steps to reproduce the problem.
I use a GeoTiff file : [Myfile.zip](https://github.com/OSGeo/gdal/files/5560188/Myfile.zip

I translate it to .asc file with **this command** : 
**gdal_translate -a_srs EPSG:2154 -a_nodata -9999 -of AAIGrid C:/Temp/Myfile.tif C:/Temp/Myfile_export_asc_1.asc**
![gdal_translate_osgeo4w_shell](https://user-images.githubusercontent.com/7483093/99537685-4691b500-29ac-11eb-9c65-ee6435c2ae65.jpg)

**I have used the same command inside QGIS 3.16 :** https://github.com/qgis/QGIS/issues/40157

**I get this :** 
[Myfile_export_asc_1.zip](https://github.com/OSGeo/gdal/files/5560230/Myfile_export_asc_1.zip)
![gdal_translate_result](https://user-images.githubusercontent.com/7483093/99537842-75a82680-29ac-11eb-9e22-66e81a7ea52b.jpg)

ncols        10
nrows        9
xllcorner    698362.000000000000
yllcorner    6946119.000000000000
cellsize     1.000000000000
**NODATA_value  -9999
 nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan** 55.299999237060546875 55.299999237060546875 55.200000762939453125 55.200000762939453125 55.200000762939453125
 **nan nan nan nan** 55.299999237060546875 55.299999237060546875 55.299999237060546875 55.299999237060546875 55.200000762939453125 55.200000762939453125
 **nan nan nan** 55.40000152587890625 55.299999237060546875 55.299999237060546875 55.299999237060546875 55.299999237060546875 55.299999237060546875 55.200000762939453125
 **nan nan** 55.40000152587890625 55.40000152587890625 55.40000152587890625 55.299999237060546875 55.299999237060546875 55.299999237060546875 55.299999237060546875 55.200000762939453125
 **nan** 55.5 55.40000152587890625 55.40000152587890625 55.40000152587890625 55.40000152587890625 55.299999237060546875 55.299999237060546875 55.299999237060546875 55.299999237060546875
 55.5 55.5 55.40000152587890625 55.40000152587890625 55.40000152587890625 55.40000152587890625 55.40000152587890625 55.299999237060546875 55.299999237060546875 55.299999237060546875
 55.5 55.5 55.5 55.40000152587890625 55.40000152587890625 55.40000152587890625 55.40000152587890625 55.299999237060546875 55.299999237060546875 55.299999237060546875

## Operating system
Windows 10 64 bit

## GDAL version and provenance
GDAL 3.1.4, released 2020/10/20

**Comment by rouault** [comment]
gdal_translate -a_nodata just assigns the nodata value setting, but doesn't alter grid values. You may want to use gdalwarp -srcnodata -dstnodata to do a full nodata remapping
