### ISSUE TITLE
gdal2tiles.py with -p raster --xyz does not generate tilemapresource.xml

### ISSUE THREAD

**Issue by roddc** [OSGeo/gdal#3197]
## Expected behavior and actual behavior.

I expected to be able to generate the tiles with tilemapresource.xml.

## Steps to reproduce the problem.

 "docker run --rm -v $PWD:/home --workdir /home --user $(id -u):$(id -g) 1a3702a4a64e gdal2tiles.py -p raster --xyz -z 0-3 $PWD/user/Pictures/image.png $PWD/user/tiles "

## Operating system

ubuntu:20.04

## GDAL version and provenance

the 3.2.0 version from ubuntu-small docker image

**Comment by rouault** [comment]
tilemapresource.xml uses the TMS convention of tile at y=0 being the most bottom one, whereas --xyz uses the convention of tile at y=0 being the top one, hence tilemapresource.xml cannot be generated when --xyz is used
