### ISSUE TITLE
Null geographies in history sets

### ISSUE THREAD

**Issue by nanodan** [OSGeo/gdal#3208]
## Expected behavior and actual behavior.

Expect the history tables to be generated to contain geography if such geography is specified in OSM. However, the geography returned is often null. This happens quite often. This can be seen in Googles GDAL converted osm tables:

```sql
select geometry is null as IsNull, count(1) Cnt
  from `bigquery-public-data.geo_openstreetmap.history_ways`
 group by 1
```

![image](https://user-images.githubusercontent.com/5264336/99905972-46423400-2ca2-11eb-962f-5078ac5c3530.png)

## Steps to reproduce the problem.

```sql
select geometry is null as IsNull, count(1) Cnt
  from `bigquery-public-data.geo_openstreetmap.history_ways`
 group by 1
```

**Comment by rouault** [comment]
This report is incomplete, and not actionable as it. It is unclear that is a GDAL matter at all. To which type of database is this SQL submitted too (PostgreSQL) ? How was the import from OSM done ?

**Comment by nanodan** [comment]
I'll ask the google folks to join in and provide additional details. I originally posted as an issue on their tracker and they advised to open it here.
https://github.com/gcp-pdp/geo-openstreetmap/issues/27

**Comment by rouault** [comment]
Any update on this ?, otherwise I'll close it
