### ISSUE TITLE
Incorrect history

### ISSUE THREAD

**Issue by nanodan** [OSGeo/gdal#3209]
## Expected behavior and actual behavior.

Expect the history tables generated for osm changesets to match osm. They sometimes do not.

Example is WayId = 160372962
As of writing the ticket, the latest change is 2020-10-31. There are 11 nodes in this way and it is accurately represented on the map. 
![image](https://user-images.githubusercontent.com/5264336/99906035-9ae5af00-2ca2-11eb-854d-d7b4bb9ceb8f.png)

However, the change history produced by gdal is wrong and includes a different node (8058129230) which is up in Norway and creates a completely incorrect geography for the way. It's missing node 1286.
![image](https://user-images.githubusercontent.com/5264336/99906047-ae911580-2ca2-11eb-8025-3fdd82ab316b.png)

**Comment by rouault** [comment]
Same remark as https://github.com/OSGeo/gdal/issues/3208 . I've no idea what to do with that ticket. Please provide ways to reproduce your issue with GDAL command line utilities (ogr2ogr)

**Comment by allenday** [comment]
@rouault @nanodan do you know if there is there a tool for exporting a single changeset from the history file? This would let us construct an isolated example.

**Comment by rouault** [comment]
> from the history file?

No idea... The OSM driver isn't specifically designed to deal with the history file. I had no idea what it was before just reading https://wiki.openstreetmap.org/wiki/Planet.osm/full

**Comment by rouault** [comment]
Any update on this ?, otherwise I'll close it
