### ISSUE TITLE
Excessive memory allocation for ENVI BIP files "ERROR 2: Too much memory needed"

### ISSUE THREAD

**Issue by HGS-EricSchmiedeberg** [OSGeo/gdal#3213]
### Expected
gdal 1.11 is able to handle ENVI BIP files that are quite large. 9.6 GB in my test case. gdalinfo and gdal_translate work as expected with 1.11 versions of the executables.

### Actual
With gdal 3.0.4 and 3.2.0 the following error prints when trying to use gdalinfo or gdal_translate:
`ERROR 2: Too much memory needed`

This seems to be a known issue in the code here:
https://github.com/OSGeo/gdal/blob/42979b8faad298a7450da22c1a8153f2c7c65e02/gdal/frmts/raw/envidataset.cpp#L2426-L2442

## Steps to reproduce the problem.

run gdalinfo on a large ENVI BIP file

## Operating system

Windows 10

## GDAL version and provenance

Tested on 3.0.4 and 3.2.0

**Comment by rouault** [comment]
Please share the ENVI .hdr file

**Comment by HGS-EricSchmiedeberg** [comment]
Hi @rouault I attached the ENVI .hdr file. I also included an IDL script that'll generate the corresponding .dat file.
[hdr and script.zip](https://github.com/OSGeo/gdal/files/5585975/hdr.and.script.zip)
