### ISSUE TITLE
Error when using Gdal with Ortho4xp 

### ISSUE THREAD

**Issue by OldSubSailor** [OSGeo/gdal#3216]
## Expected behavior and actual behavior.
Expected is to have elevation reported and generated (was working before Big Sur and python 3.9 last week)
Actual:
When generating a tile, using USGS the following error message is generated:
 Loading elevation data and smoothing it over airports.
    Downloading  ./Elevation_data/+20-100/N29W097_NED13.img from USGS.
   WARNING: unsupported raster (install Gdal): ./Elevation_data/+20-100/N29W097_NED13.img -> replaced with zero altitude.
    * Min altitude: 0.0 , Max altitude: 0.0 , Mean: 0.0

**NOTE:** This message or a similar message was generated about a year or so in the past and Gdal was corrected 

## Steps to reproduce the problem.

Run Ortho4xplane, step 1, Assemble Vector Data

## Operating system

macOS Big Sur

## GDAL version and provenance

% brew info gdal
gdal: stable 3.2.0 (bottled), HEAD
Geospatial Data Abstraction Library
https://www.gdal.org/
Conflicts with:
  cpl (because both install cpl_error.h)
/usr/local/Cellar/gdal/3.2.0 (296 files, 57.6MB) *
  Poured from bottle on 2020-11-23 at 19:47:32
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/gdal.rb
License: MIT
==> Dependencies
Build: pkg-config ✘
Required: cfitsio ✔, epsilon ✔, expat ✔, freexl ✔, geos ✔, giflib ✔, hdf5 ✔, jpeg ✔, json-c ✔, libdap ✔, libgeotiff ✔, libpng ✔, libpq ✔, libspatialite ✔, libtiff ✔, libxml2 ✔, netcdf ✔, numpy ✔, openjpeg ✔, pcre ✔, poppler ✔, proj ✔, python@3.9 ✔, sqlite ✔, unixodbc ✔, webp ✔, xerces-c ✔, xz ✔, zstd ✔

**Comment by rouault** [comment]
I'm not sure if it is a GDAL upstream issue. Could you explain how to reproduce that with GDAL command line utilities (gdalinfo, gdal_translate, etc.) outside of Ortho4xplane ?
Providing a link to the dataset would also help

**Comment by OldSubSailor** [comment]
Alas, I only use it for ortho4xp plane.  Also I do not know what you mean by a link to the data set. I would be happy to if I can.

**Comment by OldSubSailor** [comment]
This was all working fine last week until I upgraded to Big Sur which forced me to upgrade to python 3.9 and reinstall homebrew and python packages.

**Comment by jratike80** [comment]
Dataset means the file, `N29W097_NED13.img from USGS.`.

**Comment by OldSubSailor** [comment]
I am headed out of town for a week. As best as I can tell, the error is generated because for some reason gdal can’t be located. 

Other observations gdal was installed using homebrew.  It appears in the pip listings.  Yet I can’t install it as a python package using 
Python3 -m pip install. 
??

**Comment by rouault** [comment]
This is something to see with homebrew packaging. Not something we the upstream project can control on.

**Comment by OldSubSailor** [comment]
So would that Usgs file even be recreated?   I will try searching for it when I get back home.

**Comment by OldSubSailor** [comment]
% gdalinfo --version
GDAL 3.2.0, released 2020/10/26
%

**Comment by OldSubSailor** [comment]
There was no usgs file created.

**Comment by OldSubSailor** [comment]
![warning](https://user-images.githubusercontent.com/54075170/103009609-a5db6b80-44fc-11eb-9e85-c053ae74b9f2.jpg)
I finally found that file that y'all asked about. However it is huge, about 500 meg, so I can't send it. It is a disk image that my iMac can't recognize / open so would that be the root cause of the issue with GDAL? I suppose that it would be coming from USGS?

**Comment by jratike80** [comment]
It is not really a disk image but your Mac seems to believe so because of the file name extension `.img`.

**Comment by OldSubSailor** [comment]
Thank you for your reply. So do you have a suggestion on how to correct this? Evidently this is how it was downloaded or received by Ortho4XP. Your advice will be appreciated.  This evidently only happens when I try to access NED from USGS. 
TRAV

**Comment by jratike80** [comment]
What do you get with command 
`gdalinfo N29W097_NED13.img`?
You can try also to get more details with
 `gdalinfo N29W097_NED13.img -- debug on`

**Comment by OldSubSailor** [comment]
% gdalinfo N29W097_NED13.img
Driver: HFA/Erdas Imagine Images (.img)
Files: N29W097_NED13.img
Size is 10812, 10812
Coordinate System is:
GEOGCRS["NAD83",
    DATUM["North American Datum 1983",
        ELLIPSOID["GRS 1980",6378137,298.257222101,
            LENGTHUNIT["metre",1]]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["degree",0.0174532925199433]],
    CS[ellipsoidal,2],
        AXIS["geodetic latitude (Lat)",north,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433]],
        AXIS["geodetic longitude (Lon)",east,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433]],
    ID["EPSG",4269]]
Data axis to CRS axis mapping: 2,1
Origin = (-97.000555556493097,30.000555556594499)
Pixel Size = (0.000092592592775,-0.000092592592775)
Metadata:
  AREA_OR_POINT=Area
  BandDefinitionKeyword=*
  DataType=*
Corner Coordinates:
Upper Left  ( -97.0005556,  30.0005556) ( 97d 0' 2.00"W, 30d 0' 2.00"N)
Lower Left  ( -97.0005556,  28.9994444) ( 97d 0' 2.00"W, 28d59'58.00"N)
Upper Right ( -95.9994444,  30.0005556) ( 95d59'58.00"W, 30d 0' 2.00"N)
Lower Right ( -95.9994444,  28.9994444) ( 95d59'58.00"W, 28d59'58.00"N)
Center      ( -96.5000000,  29.5000000) ( 96d30' 0.00"W, 29d30' 0.00"N)
Band 1 Block=64x64 Type=Float32, ColorInterp=Undefined
  Description = Layer_1
  Min=5.497 Max=170.096 
  Minimum=5.497, Maximum=170.096, Mean=58.100, StdDev=29.069
  NoData Value=-3.40282306073709653e+38
  Metadata:
    LAYER_TYPE=athematic
    RepresentationType=*
    STATISTICS_EXCLUDEDVALUES=
    STATISTICS_MAXIMUM=170.0964050293
    STATISTICS_MEAN=58.100496317166
    STATISTICS_MEDIAN=0
    STATISTICS_MINIMUM=5.4973649978638
    STATISTICS_MODE=0
    STATISTICS_SKIPFACTORX=1
    STATISTICS_SKIPFACTORY=1
    STATISTICS_STDDEV=29.068621349218
    STATISTICS_VALID_PERCENT=100
  Image Structure Metadata:
    COMPRESSION=RLE




% gdalinfo N29W097_NED13.img --debug on  
OSR: TOWGS84 information has been removed. It can be kept by setting the OSR_STRIP_TOWGS84 configuration option to NO
GDAL: GDALOpen(N29W097_NED13.img, this=0x7fc57203bc00) succeeds as HFA.
Driver: HFA/Erdas Imagine Images (.img)
GDAL: GDALDefaultOverviews::OverviewScan()
Files: N29W097_NED13.img
Size is 10812, 10812
Coordinate System is:
GEOGCRS["NAD83",
    DATUM["North American Datum 1983",
        ELLIPSOID["GRS 1980",6378137,298.257222101,
            LENGTHUNIT["metre",1]]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["degree",0.0174532925199433]],
    CS[ellipsoidal,2],
        AXIS["geodetic latitude (Lat)",north,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433]],
        AXIS["geodetic longitude (Lon)",east,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433]],
    ID["EPSG",4269]]
Data axis to CRS axis mapping: 2,1
Origin = (-97.000555556493097,30.000555556594499)
Pixel Size = (0.000092592592775,-0.000092592592775)
Metadata:
  AREA_OR_POINT=Area
  BandDefinitionKeyword=*
  DataType=*
Corner Coordinates:
Upper Left  ( -97.0005556,  30.0005556) ( 97d 0' 2.00"W, 30d 0' 2.00"N)
Lower Left  ( -97.0005556,  28.9994444) ( 97d 0' 2.00"W, 28d59'58.00"N)
Upper Right ( -95.9994444,  30.0005556) ( 95d59'58.00"W, 30d 0' 2.00"N)
Lower Right ( -95.9994444,  28.9994444) ( 95d59'58.00"W, 28d59'58.00"N)
Center      ( -96.5000000,  29.5000000) ( 96d30' 0.00"W, 29d30' 0.00"N)
Band 1 Block=64x64 Type=Float32, ColorInterp=Undefined
  Description = Layer_1
  Min=5.497 Max=170.096 
  Minimum=5.497, Maximum=170.096, Mean=58.100, StdDev=29.069
  NoData Value=-3.40282306073709653e+38
  Metadata:
    LAYER_TYPE=athematic
    RepresentationType=*
    STATISTICS_EXCLUDEDVALUES=
    STATISTICS_MAXIMUM=170.0964050293
    STATISTICS_MEAN=58.100496317166
    STATISTICS_MEDIAN=0
    STATISTICS_MINIMUM=5.4973649978638
    STATISTICS_MODE=0
    STATISTICS_SKIPFACTORX=1
    STATISTICS_SKIPFACTORY=1
    STATISTICS_STDDEV=29.068621349218
    STATISTICS_VALID_PERCENT=100
  Image Structure Metadata:
    COMPRESSION=RLE

GDAL: GDALClose(N29W097_NED13.img, this=0x7fc57203bc00)
%

**Comment by jratike80** [comment]
It means that GDAL is OK. It confirms that what is not OK is that Ortho4xplane in your environment cannot find GDAL. I repeat what Even wrote earlier:
"This is something to see with homebrew packaging. Not something we the upstream project can control on."

**Comment by OldSubSailor** [comment]
My concern is why is the file a disk image although it isn't. The file extension .img makes it so to macOS, so nothing can proceed in that it is an unreadable file. I think that this all happens so fast and at once and "confuses" Ortho. 
Again, until the upgrade to Big Sur, GDAL and Ortho4Xp was working fine. 
I was just hoping that y'all had an idea as to why that file was being tagged as an .img file. 
I had played with the gadalinf commands earlier and come to the conclusion that gdal was working and left that message on the ortho4xp board. I had just hoped that you might see something, a magic pill.

I appreciate your help

**Comment by jratike80** [comment]
The file is named as .img because it is correct. It stands for ERDAS Imagine image file. Here you can find a few other common usages for .img https://fileinfo.com/extension/img. I am pretty sure that your issue is not due to confusion with the file name extension. It worked before and .img was also then used to mean also "Macintosh file image". 

Your environment, efter upgrade to Big Sur, GDAL, and Ortho4Xp, is now broken somehow and Ortho4Xp does not find GDAL even you do have it in your system as was confirmed by the successful test with gdalinfo. In other words, you can read the message from Ortho4Px  "WARNING: unsupported raster (install Gdal)" as "Please configure me and your system so that I can find GDAL".

**Comment by OldSubSailor** [comment]
Ok then. Clarification so that I can talk to this at the Ortho4XP Forum. Although at this time, macOS shows this file as a Disk Image, as shown in the screen shot; these files were and are always .img files and because of THE CHANGE Ortho4XP is broken and can't find GDAL which is the root cause. The Disk Image is sort of a Red Herring. 
![Disk Image](https://user-images.githubusercontent.com/54075170/103091677-8c005e00-45ba-11eb-8bc7-e0230b49e195.jpg)

**Comment by OldSubSailor** [comment]
Once again since homebrew was mentioned, does this look correct complete to you
% brew info GDAL
gdal: stable 3.2.0 (bottled), HEAD
Geospatial Data Abstraction Library
https://www.gdal.org/
Conflicts with:
  cpl (because both install cpl_error.h)
/usr/local/Cellar/gdal/3.2.0_1 (296 files, 57.6MB) *
  Poured from bottle on 2020-12-23 at 10:42:06
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/gdal.rb
License: MIT
==> Dependencies
Build: pkg-config ✔
Required: cfitsio ✔, epsilon ✔, expat ✔, freexl ✔, geos ✔, giflib ✔, hdf5 ✔, jpeg ✔, json-c ✔, libdap ✔, libgeotiff ✔, libpng ✔, libpq ✔, libspatialite ✔, libtiff ✔, libxml2 ✔, netcdf ✔, numpy ✔, openjpeg ✔, pcre ✔, poppler ✔, proj ✔, python@3.9 ✔, sqlite ✔, unixodbc ✔, webp ✔, xerces-c ✔, xz ✔, zstd ✔
==> Options
--HEAD
	Install HEAD version
==> Analytics
install: 18,114 (30 days), 63,541 (90 days), 185,129 (365 days)
install-on-request: 14,304 (30 days), 47,790 (90 days), 122,906 (365 days)
build-error: 0 (30 days)
%

**Comment by OldSubSailor** [comment]
The tests show that GDAL does work.  As installed, would it be considered a Python module?
