### ISSUE TITLE
GDAL gdalinfo issue with some GRIB2 files from NOMADS (NOAA Operational Model Archive and Distribution System)

### ISSUE THREAD

**Issue by jmblouis** [OSGeo/gdal#3220]
## Expected behavior and actual behavior.

I expected to be able to get information from this raster file:
https://nomads.ncep.noaa.gov/cgi-bin/filter_gefs_chem_0p25.pl?file=gefs.chem.t00z.a2d_0p25.f003.grib2&all_var=on&var_AOTK=on&var_SCTAOTK=on&var_SSALBK=on&subregion=&leftlon=-10&rightlon=30&toplat=70&bottomlat=30&dir=%2Fgefs.20201124%2F00%2Fchem%2Fpgrb2ap25 and it returns an error message
instead.

ERROR 4: /export/DATA/NOAA/GFS/gefs.chem.t00z.a2d_0p25.f003.grib2 is a grib file, but no raster dataset was succe                                                                                ssfully identified.
gdalinfo failed - unable to open '/export/DATA/NOAA/GFS/gefs.chem.t00z.a2d_0p25.f003.grib2'.

## Steps to reproduce the problem.

/usr/local/bin/gdalinfo /export/DATA/NOAA/GFS/gefs.chem.t00z.a2d_0p25.f003.grib2

## Operating system

Ubuntu 14.04.5 LTS

## GDAL version and provenance

The 2.2.1 version from add-apt-repository ppa:ubuntugis/ppa
 Official stable UbuntuGIS packages.

## Remark
gdalinfo works for other GRIB2 files from the same system:

https://nomads.ncep.noaa.gov/cgi-bin/filter_gfs_0p25.pl?file=gfs.t00z.pgrb2.0p25.f003&var_PWAT=on&subregion=&leftlon=-10&rightlon=30&toplat=70&bottomlat=30&dir=%2Fgfs.20201124%2F00

/usr/local/bin/gdalinfo /export/DATA/NOAA/GFS/gfs.t00z.pgrb2.0p25.f003
Driver: GRIB/GRIdded Binary (.grb)
Files: /export/DATA/NOAA/GFS/gfs.t00z.pgrb2.0p25.f003
Size is 161, 161
Coordinate System is:
GEOGCS["Coordinate System imported from GRIB file",
    DATUM["unknown",
        SPHEROID["Sphere",6371229,0]],
    PRIMEM["Greenwich",0],
    UNIT["degree",0.0174532925199433]]
Origin = (349.875000000000000,70.125000000000000)
Pixel Size = (0.250000000000000,-0.250000000000000)
Corner Coordinates:
Upper Left  (     349.875,      70.125) (349d52'30.00"E, 70d 7'30.00"N)
Lower Left  (     349.875,      29.875) (349d52'30.00"E, 29d52'30.00"N)
Upper Right (     390.125,      70.125) (Invalid angle, 70d 7'30.00"N)
Lower Right (     390.125,      29.875) (Invalid angle, 29d52'30.00"N)
Center      (     370.000,      50.000) (Invalid angle, 50d 0' 0.00"N)
Band 1 Block=161x1 Type=Float64, ColorInterp=Undefined
  Description = 0[-] EATM="Entire atmosphere (considered as a single layer)"
  Metadata:
    GRIB_COMMENT=Precipitable water [kg/(m^2)]
    GRIB_ELEMENT=PWAT
    GRIB_FORECAST_SECONDS=10800 sec
    GRIB_PDS_PDTN=0
    GRIB_PDS_TEMPLATE_NUMBERS=1 3 2 0 96 0 0 0 1 0 0 0 3 200 0 0 0 0 0 255 0 0 0 0 0
    GRIB_REF_TIME=  1606176000 sec UTC
    GRIB_SHORT_NAME=0-EATM
    GRIB_UNIT=[kg/(m^2)]
    GRIB_VALID_TIME=  1606186800 sec UTC

**Comment by rouault** [comment]
https://nomads.ncep.noaa.gov/cgi-bin/filter_gefs_chem_0p25.pl?file=gefs.chem.t00z.a2d_0p25.f003.grib2&all_var=on&var_AOTK=on&var_SCTAOTK=on&var_SSALBK=on&subregion=&leftlon=-10&rightlon=30&toplat=70&bottomlat=30&dir=%2Fgefs.20201124%2F00%2Fchem%2Fpgrb2ap25 can be opened at least with GDAL 2.4 or above. You need to upgrade your GDAL version / system

**Comment by jmblouis** [comment]
Good to know!.
Thanks you for your quick reply.
