### ISSUE TITLE
Use gcc++ and cmake to build gdal under window

### ISSUE THREAD

**Issue by mylove10086** [OSGeo/gdal#3231]
I cannot use gcc++ and cmake to build GDAL under the Windows operating system. The main reason is that I cannot create the cmakelist.txt file. I don’t know which GDAL files should be imported, and I don’t know the required third-party libraries.
Do you have any suggestions?

**Comment by mloskot** [comment]
> Do you have any suggestions?

You will need to browse through the documentation where global as well as driver-specific dependencies are listed.
You will need to read the makefiles, for Unix and for Windows, to learn the details about the dependencies.

You can run [gdal/generate_vcxproj.bat](https://github.com/OSGeo/gdal/blob/master/gdal/generate_vcxproj.bat), then open the generated project in Visual Studio and learn the details about source structure, etc. from the project properties.
Keep in mind, the generated projects are special as they call to the NMAKE makefiles, so you control all the dependencies via editing `nmake.opt` (or `nmake.opt.local), so reading the `nmake.opt` is necessary.

Finally, you may want to look at existing third-party CMake configurations for GDAL:
- https://github.com/miurahr/cmake4gdal
- https://github.com/nextgis-borsch/lib_gdal

You may want to contact authors of those projects with detailed questions.

**Comment by rouault** [comment]
You could also possibly use MSYS2 + mingw to build GDAL.
