### ISSUE TITLE
gdalwarp ignores Scale (and possibly also Offset)

### ISSUE THREAD

**Issue by idanmiara** [OSGeo/gdal#3232]
## Expected behavior and actual behavior.

gdalwarp ignores Scale, and the output raster values are greatly different from the source values because the scale is ignored. I assume Offset is ignored as well, but I didn't check.

Actual behavior:
The output has offset=0 and scale=1 but the pixel values do not correspond to these values as the original offset and scale were just ignored.

Expected behavior:
I guess there are two possible correct outputs:
1. assign the same Scale and Offset to the output raster (see below python workaround)
2. unscale and unoffset the raster when warping so that the output raster will have offset=0 and scale=1. 
I guess the second option will make sense only in some cases, i.e. the input is int (and that's why offset/scale was useful) and the output is float.

## Steps to reproduce the problem.

Run the following command:
`gdalwarp -t_srs EPSG:4326 32636.tif 4326.tif`

With the provided sample 4x4 int16 raster 32636.tif that has (Offset: 0,   Scale:0.1). 
see below gdalinfo for the input and output.

[input: 32636.tif](https://drive.google.com/file/d/1Q9VU8o60jAA7IaneteGGOXGzVAFGQOGu/view?usp=sharing)
[output: 4326.tif](https://drive.google.com/file/d/13X7rhsDKDFNNNFmAnmyt8sr6LtNIJI9r/view?usp=sharing)

Creating output file that is 4P x 4L.
Processing 32636.tif [1/1] : 0Using internal nodata values (e.g. -32768) for image 32636.tif.
Copying nodata values from source 32636.tif to destination 4326.tif.
...10...20...30...40...50...60...70...80...90...100 - done.

## Workaround

Use the provided function to fix the output ds:

```
def assign_same_scale_and_offset_values(out_ds, in_ds):
    out_bands_count = out_ds.RasterCount
    in_bands_count = in_ds.RasterCount
    scale = 1
    offset = 0
    for i in range(out_bands_count):
        if i < in_bands_count:
            in_bnd = in_ds.GetRasterBand(i + 1)
            scale = in_bnd.GetScale()
            offset = in_bnd.GetOffset()
        out_bnd = out_ds.GetRasterBand(i + 1)
        out_bnd.SetScale(scale)
        out_bnd.SetOffset(offset)
```

## Gdalinfo

`gdalinfo 32636.tif`

```
Driver: GTiff/GeoTIFF
Files: 32636.tif
Size is 4, 4
Coordinate System is:
PROJCRS["WGS 84 / UTM zone 36N",
    BASEGEOGCRS["WGS 84",
        DATUM["World Geodetic System 1984",
            ELLIPSOID["WGS 84",6378137,298.257223563,
                LENGTHUNIT["metre",1]]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433]],
        ID["EPSG",4326]],
    CONVERSION["UTM zone 36N",
        METHOD["Transverse Mercator",
            ID["EPSG",9807]],
        PARAMETER["Latitude of natural origin",0,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",33,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["Scale factor at natural origin",0.9996,
            SCALEUNIT["unity",1],
            ID["EPSG",8805]],
        PARAMETER["False easting",500000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["(E)",east,
            ORDER[1],
            LENGTHUNIT["metre",1]],
        AXIS["(N)",north,
            ORDER[2],
            LENGTHUNIT["metre",1]],
    USAGE[
        SCOPE["Engineering survey, topographic mapping."],
        AREA["Between 30┬░E and 36┬░E, northern hemisphere between equator and 84┬░N, onshore and offshore. Belarus. Cyprus. Egypt. Ethiopia. Finland. Israel. Jordan. Kenya. Lebanon. Moldova. Norway. Russian Federation. Saudi Arabia. Sudan. Syria. Turkey. Uganda. Ukraine."],
        BBOX[0,30,84,36]],
    ID["EPSG",32636]]
Data axis to CRS axis mapping: 1,2
Origin = (699980.000000000000000,3500117.000000000000000)
Pixel Size = (31.000000000000000,-31.000000000000000)
Metadata:
  AREA_OR_POINT=Area
Image Structure Metadata:
  COMPRESSION=DEFLATE
  INTERLEAVE=BAND
Corner Coordinates:
Upper Left  (  699980.000, 3500117.000) ( 35d 6'29.88"E, 31d37' 7.80"N)
Lower Left  (  699980.000, 3499993.000) ( 35d 6'29.79"E, 31d37' 3.78"N)
Upper Right (  700104.000, 3500117.000) ( 35d 6'34.58"E, 31d37' 7.72"N)
Lower Right (  700104.000, 3499993.000) ( 35d 6'34.49"E, 31d37' 3.70"N)
Center      (  700042.000, 3500055.000) ( 35d 6'32.18"E, 31d37' 5.75"N)
Band 1 Block=256x256 Type=Float32, ColorInterp=Gray
  NoData Value=-32768
  Offset: 0,   Scale:0.1
```

--------------------

`gdalinfo 4326.tif`

```
Driver: GTiff/GeoTIFF
Files: 4326.tif
Size is 4, 4
Coordinate System is:
GEOGCRS["WGS 84",
    DATUM["World Geodetic System 1984",
        ELLIPSOID["WGS 84",6378137,298.257223563,
            LENGTHUNIT["metre",1]]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["degree",0.0174532925199433]],
    CS[ellipsoidal,2],
        AXIS["geodetic latitude (Lat)",north,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433]],
        AXIS["geodetic longitude (Lon)",east,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433]],
    ID["EPSG",4326]]
Data axis to CRS axis mapping: 2,1
Origin = (35.108273747456380,31.618833454223228)
Pixel Size = (0.000303128617109,-0.000303128617109)
Metadata:
  AREA_OR_POINT=Area
Image Structure Metadata:
  INTERLEAVE=BAND
Corner Coordinates:
Upper Left  (  35.1082737,  31.6188335) ( 35d 6'29.79"E, 31d37' 7.80"N)
Lower Left  (  35.1082737,  31.6176209) ( 35d 6'29.79"E, 31d37' 3.44"N)
Upper Right (  35.1094863,  31.6188335) ( 35d 6'34.15"E, 31d37' 7.80"N)
Lower Right (  35.1094863,  31.6176209) ( 35d 6'34.15"E, 31d37' 3.44"N)
Center      (  35.1088800,  31.6182272) ( 35d 6'31.97"E, 31d37' 5.62"N)
Band 1 Block=4x4 Type=Float32, ColorInterp=Gray
  NoData Value=-32768

```

## Operating system

Win64

## GDAL version and provenance

3.3.0dev

**Comment by jratike80** [comment]
I am remembering that unscaling with gdal_translate was recommended in some mailing list thread.

**Comment by idanmiara** [comment]
> I am remembering that unscaling with gdal_translate was recommended in some mailing list thread.

Thanks, That could be a second workaround. 
I think that the obvious fix would be to set the same offset/scale to the output, as I made in the first suggested workaround.

**Comment by jratike80** [comment]
I was just reading this https://trac.osgeo.org/gdal/ticket/3221 but did not make a conclusion yet. Could there be something more to think if the input is some clever VRT? Maybe not.

**Comment by idanmiara** [comment]
> I was just reading this https://trac.osgeo.org/gdal/ticket/3221 but did not make a conclusion yet. Could there be something more to think if the input is some clever VRT? Maybe not.

If the VRT reports offset and scale, then warp should address them as in a normal raster, right?
 
> How about the mathematics with various resampling methods? Is the result right if resampling is done with unscaled values and scale + offset are copied from the source? Is the question perhaps "are all the resampling methods linear"? Quadratic Mean?

I don't know about all the resampling methods. 
I guess that at least for `nearest`, `mode` and `average` there shouldn't be a problem.
For `cubic` I'm not sure, but the result look right, or at least not obviously wrong.

**Comment by jratike80** [comment]
Have you checked if gdal_translate copies scale and offset (wondering what formats support them...) and if they are removed when -unscale is used?

If output format does not support scale and offset, will gdalwarp create a pam xml file?

**Comment by idanmiara** [comment]
> Have you checked if gdal_translate copies scale and offset (wondering what formats support them...) and if they are removed when -unscale is used?
> 
> If output format does not support scale and offset, will gdalwarp create a pam xml file?

`gdal_translate -of gtiff 32636.tif 32636b.tif` - output tif has correct scale
`gdal_translate -of HFA 32636.tif 32636.img` - aux 32636.img.aux.xml has correct the scale info
`gdal_translate -of gtiff -unscale 32636.tif 32636u.tif` - unscales correctly

All the above rasters look the same in QGIS, So no problem with `gdal_translate`.

**Comment by idanmiara** [comment]
Thanks!
