### ISSUE TITLE
Unused variable assignments in gdal code base

### ISSUE THREAD

**Issue by FloridSleeves** [OSGeo/gdal#3233]
## Expected behavior and actual behavior.

Hi! I've recently used some tool to check gdal code (master branch, newest version) and find that there are some unused value assignments in the code base. When a developer assigns some value to a variable, the expectation is they will use this value somewhere. If they don’t, it could potentially indicate bugs. The unused value assignments are as follows:
File Name	|  Line Number	| Variable Name 
-------------------- |------------------------------|--------------------
gdal/port/cpl_cpu_features.cpp | 153 | nXCRHigh
gdal/ogr/ogrsf_frmts/geojson/ogrgeojsonreader.cpp | 2721 | it.val
gdal/ogr/ogrsf_frmts/dxf/ogrdxflayer.cpp | 2871 | oTransformer.dfXOffset
gdal/ogr/ogrsf_frmts/dxf/ogrdxflayer.cpp | 2871 | oTransformer.dfYOffset
gdal/ogr/ogrsf_frmts/dxf/ogrdxflayer.cpp | 2871 | oTransformer.dfZOffset
gdal/frmts/aigrid/aigccitt.c | 1857 | rawcp (The unused assignment is in MACRO UNCACHE_STATE)
gdal/frmts/aigrid/aigccitt.c | 1860 | rawcp (The unused assignment is in MACRO UNCACHE_STATE)
gdal/frmts/aigrid/aigccitt.c | 1857 | rawcc (The unused  assignment is in MACRO UNCACHE_STATE)
gdal/frmts/aigrid/aigccitt.c | 1860 | rawcc (The unused assignment is in MACRO UNCACHE_STATE)

Besides, there are two assignments that are redundant. Though they may not be bug, they may affect the readability of code. So I list them here:
File Name	|  Line Number	| Variable Name 
-------------------- |------------------------------|--------------------
gdal/alg/internal_libqhull/merge.c | 1151 | nummerges
gdal/frmts/grib/degrib/g2clib/reduce.c | 195 | novl

I will appreciate it so much if you could take a bit time to confirm.

Even if they are not bugs, they may invoke compiler warnings and may still deserve to be dealt with. I wonder if I can help to remove them so that they can keep quiet when compiled.

Thanks! And happy Thanksgiving Day!

## Steps to reproduce the problem.

It's in source code of gdal newest version, master branch.

**Comment by atlight** [comment]
The DXF ones seem to be false positives. If I'm not mistaken, the assigned values are used when `oTransformer.GetOffsetTransformer()` (defined [here](https://github.com/OSGeo/gdal/blob/master/gdal/ogr/ogrsf_frmts/dxf/ogr_dxf.h#L134-L141)) is called on lines 2986 and 3001 of that function.
