### ISSUE TITLE
Only getting "Warning 1: All options related to creation ignored in update mode" from command line

### ISSUE THREAD

**Issue by SevenFoldDeep** [OSGeo/gdal#3239]
#2613  Expected behavior and actual behavior.

I have some code which when run in Jupyter Notebook works perfectly. However, I have now written it into a python script and when I try to call this script from the command line I get the "Warning 1: All options related to creation ignored in update mode" message, and the files written from the script are unchanged from the original copies that I gave as inputs.

## Steps to reproduce the problem.

Below is the code that I am running:

```
# Load image and get it's geotransform
teax = './dummy_file.tif'
orig_raster= gdal.Open(teax)
geoTransform = orig_raster.GetGeoTransform()

# get a bounding box to clip to. For simplicity I just take the extent of the image and take a few meters off each side
minx = geoTransform [0]
maxy = geoTransform [3]
maxx = minx + geoTransform [1] * orig_raster.RasterXSize
miny = maxy + geoTransform [5] * orig_raster.RasterYSize
bb =  (minx+5, miny+5, maxx-5, maxy-5)

# create empty dataset in memory
mem_drv = gdal.GetDriverByName('MEM')
clipped_out = mem_drv.Create("", orig_raster.RasterXSize, orig_raster.RasterYSize, 1, gdal.GDT_Float32) 
clipped_out.SetProjection(orig_raster.GetProjection())
clipped_out.SetGeoTransform(geoTransform)

# set warp options
opt = gdal.WarpOptions(dstSRS = orig_raster.GetProjection(),
                           outputBounds = bb,
                           polynomialOrder = 0,
                           targetAlignedPixels = False)

# perform clipping
gdal.Warp(srcDSOrSrcDSTab = orig_raster, 
          destNameOrDestDS = clipped_out, 
          options = opt)

```
In the script the code goes on further to write the dataset 'clipped_out' to a file on disk, but thats not the problem, the problem is the 'Warning' message that I get when the code gets to the gdal.Warp function. However, as I said before, this only happens if I run the script from the command line. If I perform the exact same steps with the exact same files in the Jupyter Notebook then everything works fine...

## Operating system

Ubuntu 16.04.7

## GDAL version and provenance

GDAL 3.0.2

**Comment by rouault** [comment]
As the warning suggests, the use of some of the options like outputBounds of targetAlignedPixels is not possible when the output dataset is an existing one, like clipped_out here. For those to work, you need to specify a dataset name as the destNameOrDestDS (can be an empty one for a MEM dataset, and add a format = 'MEM' option), not as a dataset object.

**Comment by SevenFoldDeep** [comment]
Ok, still don't understand why the behaviour is different when I run the code using a jupyter notebook, but it works when I changed the warp options to : 
```
# Load image and get it's geotransform
teax = './dummy_file.tif'
orig_raster= gdal.Open(teax)
geoTransform = orig_raster.GetGeoTransform()

# get a bounding box to clip to. For simplicity I just take the extent of the image and take a few meters off each side
minx = geoTransform [0]
maxy = geoTransform [3]
maxx = minx + geoTransform [1] * orig_raster.RasterXSize
miny = maxy + geoTransform [5] * orig_raster.RasterYSize
bb =  (minx+5, miny+5, maxx-5, maxy-5)

# get the number of rows and columns for the output
resolution = geoTransform [1]
n_col = round((bb[2] - bb[0]) / resolution )
n_row = round((bb[-1] - bb[1]) / resolution )

# set warp options
opt = gdal.WarpOptions(dstSRS = orig_raster.GetProjection(),
                       format = 'MEM',
                       outputBounds = bb,
                       polynomialOrder = 0,
                       targetAlignedPixels = False,
                       width  = col,
                       height = row,
                       xRes = resolution)

# perform clipping
clipping_out = gdal.Warp(srcDSOrSrcDSTab = orig_raster, 
                                          destNameOrDestDS = clipped_out, 
                                           options = opt)

```

Thanks.

**Comment by rouault** [comment]
Perhaps Jupyter notebook hides warnings.
