### ISSUE TITLE
ExecuteSQL on dataset fails when ORDER BY clause contains more than 1 field

### ISSUE THREAD

**Issue by scopars** [OSGeo/gdal#3249]
Calling GDALDataset::ExecuteSQL method on various datasets works in almost all cases except when I have an SQL query with an ORDER BY containing 2 fields on the attached dataset. (OrderByTestData.geojson)

Problem can also be reproduced using the ogrinfo tool.

For the attached dataset the following succeed:

ogrinfo -sql "SELECT * FROM test ORDER BY NAME" OrderByTestData.geojson
ogrinfo -sql "SELECT * FROM test ORDER BY COUNT" OrderByTestData.geojson

but this fails:

ogrinfo -sql "SELECT * FROM test ORDER BY COUNT, NAME" OrderByTestData.geojson

In the failure case, is no error is generated, and the returned OGRLayer is not null. The OGRLayer is in a bad state, and calling any methods on the OGRLayer causes a crash. (eg. null pointer access) 

Also, remove any 1 feature from the geoJSON file and the request succeeds.

Environment:
GDAL 3.1.0 on windows

[OrderByTestData.geojson.txt](https://github.com/OSGeo/gdal/files/5616893/OrderByTestData.geojson.txt)

**Comment by jratike80** [comment]
The behavior is documented in https://gdal.org/user/ogr_sql_dialect.html

> ORDER BY
> The ORDER BY clause is used force the returned features to be reordered into sorted order (ascending or descending) on one of the field values. Ascending (increasing) order is the default if neither the ASC or DESC keyword is provided.

Use SQLite dialect instead

`ogrinfo -dialect sqlite -sql "SELECT * FROM test ORDER BY COUNT, NAME" OrderByTestData.geojson`

Perhaps the documentation could say it more clear, and give advice to use SQLite dialect for more demanding ORDER BY statements. Did you read it? Could you propose how to improve?

**Comment by rouault** [comment]
> The behavior is documented in https://gdal.org/user/ogr_sql_dialect.html

The doc is not super accurate. Multiple column ORDER BY was supposedly supported, but there was indeed a bug fixed per #3252
