### ISSUE TITLE
VRT File Lock Issue

### ISSUE THREAD

**Issue by pankajsachdeva85** [OSGeo/gdal#3253]
## Expected behavior and actual behavior.

I've noticed a VRT file locking issue with GDAL 3.0.4 which is as follows:

I've 2 VRT files whose source files names are same but the files (i.e., VRT & source file) are located at different locations but after opening both of them in readonly mode, I closed one of the file. Then, ideally the file I closed must be free to updated but it is not until I close down the other VRT file.

I verified the same in QGIS 3.16.1-Hannover which is using GDAL 3.1.4 and it has the same issue.

## Steps to reproduce the problem.

Open the both of the attached VRT in QGIS and remove one of them and try to rename the source Tiff file of the removed VRT.

## Operating system

Windows 10

## GDAL version and provenance

3.0.4
[Dataset.zip](https://github.com/OSGeo/gdal/files/5622350/Dataset.zip)

**Comment by piyushrpt** [comment]
Using `gdal.SetConfigOption("VRT_SHARED_SOURCE", "0")`  or adding attribute `shared="0"` right next to relativeToVRT attribute should fix this.  You can verify the order in which files are closed by setting CPL_DEBUG=ON for debugging. 

VRT driver opens datasets in shared mode by default as is documented on the VRT docs page.

**Comment by pankajsachdeva85** [comment]
Thank you @piyushrpt that fixes my problem.
