### ISSUE TITLE
SQL query with FID does not output FID to csv file

### ISSUE THREAD

**Issue by StefanBrand** [OSGeo/gdal#3256]
## Expected behavior and actual behavior.

I expected that the CSV output contains a `FID` column. Instead, the resulting CSV does not contain `FID`.
Find sample data attached: [bug_output_fid_to_csv.zip](https://github.com/OSGeo/gdal/files/5629704/bug_output_fid_to_csv.zip)

- `sample.gpkg` (exported via `ogr2ogr -sql "SELECT * FROM inspire_schlaege_2019 LIMIT 10;" sample.gpkg inspire_schlaege_2019.gpkg`)
- `ogrinfo.txt` (`ogrinfo inspire_schlaege_2019.gpkg -so -al > ogrinfo.txt`)
- `sample.csv` (`ogr2ogr -f CSV -sql "SELECT FID, * FROM inspire_schlaege_2019 LIMIT 10;" sample.csv inspire_schlaege_2019.gpkg`, as per https://gdal.org/user/ogr_sql_dialect.html#fid)

```csv
FS_KENNUNG,SNAR_BEZEICHNUNG,SL_FLAECHE_BRUTTO_HA
73799472,LSE BÄUME / BÜSCHE,0
73799472,LSE BÄUME / BÜSCHE,0
73799472,LSE BÄUME / BÜSCHE,0
73799472,LSE BÄUME / BÜSCHE,0
73799472,LSE BÄUME / BÜSCHE,0
73799472,LSE BÄUME / BÜSCHE,0
73799472,LSE BÄUME / BÜSCHE,0
73799472,LSE BÄUME / BÜSCHE,0
73799472,LSE BÄUME / BÜSCHE,0
73799472,LSE BÄUME / BÜSCHE,0
```

The original file can be found here: https://www.data.gv.at/katalog/dataset/invekos-schlaege-oesterreich-2019

## Steps to reproduce the problem.

1. Use a GPKG, of which `ogrinfo` says: `[...] FID Column = fid [...]`
2. `ogr2ogr -f CSV -sql "SELECT FID, * FROM layer" out.csv in.gpkg`
3. `cat out.csv` -> Does not contain `FID`.

## Operating system

`ubuntu:focal-20201008`

## GDAL version and provenance

```
gdal                      3.1.2            py38hb61cb63_2    conda-forge
```

___

Edit: ~~note that `FID, *` with wildcard works alright~~ just tested again and doesn't work. I updated the commands and the sample data.

**Comment by rouault** [comment]
https://gdal.org/user/ogr_sql_dialect.html#fid is about the OGR SQL dialect, which is the default one for datasources that have no built-in SQL capabilities (shapefile, etc). But here you use GeoPackage as the source, so the SQLite engine is used, and it doesn't have the special behaviour of the OGR SQL dialect.  If you add ``-dialect OGRSQL`` to your ogr2ogr invokation, then the fid column will be exported. Alternatively you could use a SQL statement like "SELECT FID AS RENAMED_FID, * FROM layer" so that the GeoPackage driver doesn't identify the select column as the the FID one.

**Comment by jratike80** [comment]
FIDs are somewhat puzzling to handle but I would say that your bug report belongs rather to gdal-dev mailing list as a question.

Feature IDs are special attributes and it is not correct to suppose that they are exposed, or that they should be exposed as attributes into other formats. Think about shapefiles where the FID is just a counting number from the first to the last feature and usually meaningless for other purposes. But you are right that there are use cases when FIDs are good to include into output as normal attributes. Ogr2ogr has some parameters which affect how FIDs are handled but they do not help in this case. But you almost discovered how to do it with SQL. Only thing that was missing was to rename FID into something else for hiding its special meaning.

Sorry that German umlauts does not transform so great into Finnish umlauts and back on my Windows.

```
ogr2ogr -f CSV -sql "SELECT FID as foo, * FROM \"select\"" sample.csv sample.gpkg

type sample.csv
foo,FS_KENNUNG,SNAR_BEZEICHNUNG,SL_FLAECHE_BRUTTO_HA
"1",73799472,LSE B├äUME / B├£SCHE,0
"2",73799472,LSE B├äUME / B├£SCHE,0
"3",73799472,LSE B├äUME / B├£SCHE,0
"4",73799472,LSE B├äUME / B├£SCHE,0
"5",73799472,LSE B├äUME / B├£SCHE,0
"6",73799472,LSE B├äUME / B├£SCHE,0
"7",73799472,LSE B├äUME / B├£SCHE,0
"8",73799472,LSE B├äUME / B├£SCHE,0
"9",73799472,LSE B├äUME / B├£SCHE,0
"10",73799472,LSE B├äUME / B├£SCHE,0
```



ogrinfo -sql "SELECT FID as foo, * FROM \"select\"" sample.gpkg

**Comment by StefanBrand** [comment]
@rouault Ah, thanks a lot! I wasn't aware that the GPKG driver defaults to the SQLite dialect. :smile: 

@jratike80 As noted in the first post, the `OGRSQL` dialect actually supports output of `FID` without renaming the attribute: https://gdal.org/user/ogr_sql_dialect.html#fid I was looking into the [SQLite dialect](https://gdal.org/user/sql_sqlite_dialect.html) docs as well, but didn't find anything about the `fid` there.

**Comment by jratike80** [comment]
Yes, and there are more SQL dialects (at least PostgreSQL, Oracle, and MySQL) and they behave in their own ways.

```
ogr2ogr -f csv csv.csv PG:"host=localhost port=5432 dbname=pg user=user password=password" -sql "select ogc_fid, * from states limit 5"
Warning 1: More than one ogc_fid column was found in the result of the SQL request. Only last one will be used
```

Despite the warning text that may lead to think otherwise this command does not write ogc_fid into CSV. So ogc_fid is used once, and discarded. Also with the PostgreSQL dialect the fid column must be renamed. I do not know how the other dialects work; using an alias for FID always should be a safe way.
