### ISSUE TITLE
Layer.GetFeature uses 1 based indexing for geopackage and 0 based for e.g. GeoJson

### ISSUE THREAD

**Issue by cpaulik** [OSGeo/gdal#3257]
## Expected behavior and actual behavior.

I'm not 100% sure if this is intended or unintended but it seems the indexing is inconsistent between geopackage and other drivers.

```python
from osgeo import ogr
import os
root_path = ""
# ran command ogr2ogr test_region_1x1_tiles.gpkg test_region_1x1_tiles.geojson -f GPKG
# ogr2ogr test_region_1x1_tiles.shp test_region_1x1_tiles.geojson -f "ESRI Shapefile"
for fname in ['test_region_1x1_tiles.geojson', 'test_region_1x1_tiles.gpkg', 'test_region_1x1_tiles.shp']:
    full_fname = os.path.join(root_path, fname)
    print(f"Filename: {fname}")
    ds = ogr.Open(full_fname)
    layer = ds.GetLayerByIndex(0)
    n_features = layer.GetFeatureCount()
    print(f"Number of features in file: {n_features}")
    last_feature = layer.GetFeature(n_features)
    print(f"Last feature with index {n_features}: {last_feature}")
    first_feature = layer.GetFeature(0)
    print(f"First feature with index 0: {first_feature}")
```

outputs

```
Filename: test_region_1x1_tiles.geojson
Number of features in file: 4
Last feature with index 4: None
First feature with index 0: <osgeo.ogr.Feature; proxy of <Swig Object of type 'OGRFeatureShadow *' at 0x7ff123c31750> >
Filename: test_region_1x1_tiles.gpkg
	- 'VirtualXPath'	[XML Path Language - XPath]
Number of features in file: 4
Last feature with index 4: <osgeo.ogr.Feature; proxy of <Swig Object of type 'OGRFeatureShadow *' at 0x7ff123c95ea0> >
First feature with index 0: None
Filename: test_region_1x1_tiles.shp
Number of features in file: 4
ERROR 1: Attempt to read shape with feature id (4) out of available range.
Last feature with index 4: None
First feature with index 0: <osgeo.ogr.Feature; proxy of <Swig Object of type 'OGRFeatureShadow *' at 0x7ff123c95e10> >
```

## Steps to reproduce the problem.
Run the script above with the attached files

[test_region_1x1_tiles.zip](https://github.com/OSGeo/gdal/files/5630521/test_region_1x1_tiles.zip)

## Operating system

Arch Linux

## GDAL version and provenance

gdal version 3.1.4 from conda forge

**Comment by rouault** [comment]
> but it seems the indexing is inconsistent between geopackage and other drivers

yes, there is no guarantee that drivers will use the same convention. And more than that, FID can have holes in some drivers (geopackage for example) whereas in others this is a purely sequential number (shapefiles). And for some drivers, like GeoJSON, FID can be sequential or "random" depending if the feature has a id field or not.

**Comment by cpaulik** [comment]
Ok that is quite surprising. At least to me. I guess I expect to much from the `abstraction` part of gdal :smile:

So using something like

```python
    n_features = layer.GetFeatureCount()
    for n in range(n_features):
        feature = layer.GetNextFeature()
```
would be a more driver agnostic way of reading all the features then. 

Thank you for the explanation.

**Comment by rouault** [comment]
Even better:
```
for feature in layer:
    ....
```
(equivalent to calling GetNextFeature() until it returns None. Saves a call to GetFeatureCount() which can be slow on huge datasets)

**Comment by cpaulik** [comment]
ok, now I fell a little bad. It seems I expect too little from the gdal python bindings. 

Thanks again.
