### ISSUE TITLE
How can I get the alias of the Layer in ArcGIS FileGDB

### ISSUE THREAD

**Issue by fangyuzhong2016** [OSGeo/gdal#3258]
I use ogr.GetDriverByName("OpenFileGDB") to open ArcGIS FileGDB (ArcGIS 10.0). How can I get the alias of the Layer in ArcGIS FileGDB?   GDAL  version  is   3.2.0
Thank you

**Comment by jratike80** [comment]
I remind you about this:

IMPORTANT: Do NOT use GitHub to post any questions or support requests!
           They will be closed immediately and ignored.

Questions should go to the gdal-dev mailing list at
https://lists.osgeo.org/mailman/listinfo/gdal-dev
or other support forums. GitHub issues are for bug
reports and suggestions for new features.

**Comment by fangyuzhong2016** [comment]
OK

**Comment by jratike80** [comment]
That means also that you are welcome to ask questions on the gdal-dev mailing list!
