### ISSUE TITLE
VirtualXPath [XML Path Language - XPath] lines in stdout

### ISSUE THREAD

**Issue by emlys** [OSGeo/gdal#3269]
## Expected behavior and actual behavior.
I get many lines of `- 'VirtualXPath'	[XML Path Language - XPath]` output from GDAL (3.1.3 and later) coming from `Create` and possibly other functions. It appears to be related to `libspatialite`. I expect these lines of output should not exist.

## Steps to reproduce the problem.
test.py:
```
from osgeo import gdal

driver = gdal.GetDriverByName('GPKG')
filepath = '/Users/emily/Documents/vector.gpkg'
vector = driver.Create(filepath, 0, 0, gdal.GDT_Unknown)
```
```
$ python test.py
	- 'VirtualXPath'	[XML Path Language - XPath]
```

## Operating system
macOS Catalina 10.15.6

## GDAL version and provenance
3.1.3 from conda-forge

**Comment by rouault** [comment]
This is a Spatialite upstream problem. See https://www.gaia-gis.it/fossil/libspatialite/tktview?name=760ef1affb . It has been fixed in Spatialite upstream (in commit https://www.gaia-gis.it/fossil/libspatialite/info/8b6d038947169ceb), so should be resolved at its next release
