### ISSUE TITLE
README example wanted: multistage build

### ISSUE THREAD

**Issue by adriantre** [OSGeo/gdal#3272]
I would like to take advantage of the [gdal/docker](https://github.com/OSGeo/gdal/blob/master/gdal/docker) images in a [multistage](https://docs.docker.com/develop/develop-images/multistage-build/#use-multi-stage-builds) fashion. It would be very helpful to have an example of usage in the README. In another repo ([perrygeo/docker-gdal-base](https://github.com/perrygeo/docker-gdal-base#extending-the-image)) it is described as 

```
FROM perrygeo/gdal-base:latest as builder

# Install the previously-built shared libaries from the builder image
COPY --from=builder /usr/local /usr/local
RUN ldconfig
```

Would something similar work for these images? Thanks!

**Comment by rouault** [comment]
I'm not completely sure how the example you quote could be adapted. You cannot use the binaries of the Docker images with any Linux distribution as a base. You must use the one for which the image was built.
That said, the Docker images are already built in a multistage fashion. You could certainly adapt the Dockerfile to your needs. Or just use the GDAL Docker image as the base for your work.

**Comment by adriantre** [comment]
I now see I over simplified my original example. It was supposed to include another build step after the first one. 

```python
FROM perrygeo/gdal-base:latest as builder

FROM tiangolo/uvicorn-gunicorn:python3.8-slim as final
COPY --from=builder /usr/local /usr/local
RUN ldconfig
```

The reason I dont want use the GDAL Docker image as the final stage is that [tiangolo/uvicorn-gunicorn:python3.8-slim](https://github.com/tiangolo/uvicorn-gunicorn-docker) image is optimised for web server.

But as you say, since `python3.8-slim` is based on debian, I cannot use the docker images from [gdal/docker](gdal/docker). I didn't catch that. (Although I could see if the alpine3.10 image of gunicorn works with GDAL alpine image).

Looks like the [perrygeo](https://github.com/perrygeo/docker-gdal-base#extending-the-image) image is based on debian though, so I think I will try going forward with that one for now.

Or would you recommend other methods for installing GDAL in debian?

Thanks for your guidance!

**Comment by rouault** [comment]
You could likely easily adapt the Ubuntu based Docker images to use Debian instead as a base. Those Dockerfile are examples of what can be done, but don't pretend to fit all needs.
