### ISSUE TITLE
GDALCreateCopy is getting slower

### ISSUE THREAD

**Issue by Fivedogs** [OSGeo/gdal#3277]
I try to use GDALCreateCopy() to transform "VRT" to "MEM",it's getting slower with higher version.Why?
My test result:
version: 2.1.0->2.4.0->3.0.0->3.2.0
time cost: 5 seconds -> 30 seconds -> 1.5 minutes -> 2.5 minutes.

#code
	auto process = GDALCreateWarpedVRT(srcdata, width, height, (double*)&geoTransform, psWarpOptions);
	if (!process) 
	{
		GDALDestroyWarpOptions(psWarpOptions);
		GDALDestroyGenImgProjTransformer(transformerArg);
		//LOG(ERROR) << "GDALCreateWarpedVRT failed";
		return nullptr;
	}

	auto mem = GDALCreateCopy(GDALGetDriverByName("MEM"), "", process, 0, 0, 0, NULL);

**Comment by rouault** [comment]
Please provide a fully contained reproducer (something that can be compiled with g++ without any other dependency than GDAL). It might be dependent on a very precise factor

**Comment by rouault** [comment]
@Fivedogs Please provide the above requested information, otherwise this ticket will be closed as non actionable
