### ISSUE TITLE
Conda builds broken

### ISSUE THREAD

**Issue by rouault** [OSGeo/gdal#3310]
We have constant failures in Conda builds since two days. See https://github.com/OSGeo/gdal/pull/3303/checks?check_run_id=1581595590
==> "gdalinfo: error while loading shared libraries: libicui18n.so.68: cannot open shared object file: No such file or directory" .

CC @hobu

**Comment by hobu** [comment]
Fixed in https://github.com/OSGeo/gdal/pull/3316
