### ISSUE TITLE
v3.2.0 polygonize bug: some binary raster file leads to incorrect result

### ISSUE THREAD

**Issue by cartosquare** [OSGeo/gdal#3319]
## Expected behavior and actual behavior.

I expected to be able to vectorize this [binary raster file](https://1drv.ms/u/s!AiH6_Po0vGSNiFcI2oH440wWIND2), but the result is obviously incorrect.

the binary raster file screenshot:

https://1drv.ms/u/s!AiH6_Po0vGSNiFgIISK2LWj52Oil

the result file screenshot:

https://1drv.ms/u/s!AiH6_Po0vGSNiFm1ptzqvS7ucU5P

## Steps to reproduce the problem.

```bash
gdal_polygonize.py -mask fail_case_binary.tif fail_case_binary.tif fail_case_binary.shp
```

## Operating system

Ubuntu 18.04 64 bit

## GDAL version and provenance

GDAL 3.2.0, released 2020/10/26

**Comment by rouault** [comment]
This is the same as https://github.com/OSGeo/gdal/issues/1158

**Comment by cartosquare** [comment]
> This is the same as #1158

yes, the two issues ara both because of self intersection polygon. 
To avoid this, my solution is to isolate the pixel when it may cause self intersection. This solution will generate small polygons wich is just one pixel large. I also tested images in #1158, the generated vector areas(by DN value) now can exactly matching the raster image(by DN value).
Do you think this solution is acceptable?

**Comment by rouault** [comment]
> Do you think this solution is work?

I'm not sure. I'm moderately familiar with the algorithm. As a first step, you could submit a pull request with your proposed fix, and extend the test suite with the simple test case of https://github.com/OSGeo/gdal/issues/1158#issuecomment-449743255 and similar ones
