### ISSUE TITLE
Errors in Terrain Ruggedness Index (TRI) calculated in GDAL

### ISSUE THREAD

**Issue by deccantrap** [OSGeo/gdal#3320]
## Expected behavior and actual behavior.

TRI calculated using GDAL is 3-4 times greater than the hand-calculated value, the latter being calculated using the original math in Riley et al 1999 on which TRI is based. The TRI calculator in QGIS was able to reproduce the hand-calculated result, but GDAL result was way off

**Comment by rouault** [comment]
In which projection are your files ? The results of gdaldem for TRI will only be correct for projected coordinate systems with metre as the linear unit.

**Comment by deccantrap** [comment]
Hello, I ran TRI calculations for both projected and unprojected versions of the same DEM, both of which use metre as the linear unit. I am getting the same GDAL result in either case, and the result is not the same as calculated using the equation in Riley 1999.

Please note in my original entry I said the GDAL TRI is 3-4 times greater. Actually I meant the opposite, the values calculated by hand and QGIS are 3-4 times greater than GDAL TRI values.

**Comment by rouault** [comment]
gdaldem TRI is documented in https://gdal.org/programs/gdaldem.html to be : """TRI stands for Terrain Ruggedness Index, which is defined as the mean difference between a central pixel and its surrounding cells (see Wilson et al 2007, Marine Geodesy 30:3-35)."""  So it doesn't implement Riley 1999 which apparently uses the square root of the sum of the square of the differences, instead of mean of absolute differences for Wilson et al 2007.
GDAL's implementation (at least part of it, unsure for TRI) originates from an old version of GRASS GIS

**Comment by deccantrap** [comment]
Hmm, thanks for the clarification. The TRI in Wilson et al 2007 (which in turn is based on Valentine et al 2004) is an adaption of Riley 1999 for **bathymetric** data which represents a small sliver of terrain analysis applications (i.e., most applications are for above water terrain and would use Riley et al 1999 not Wilson et al 2007. I suspect I am not the first nor last person to be confused by the use of a bathymetric TRI rather than above-water TRI in GDAL.

**Comment by jratike80** [comment]
It should be noted that the default is still to use Wilson so confusion among users who do not read the documentation will be continued but that's life.

**Comment by rouault** [comment]
> It should be noted that the default is still to use Wilson

yes I hesitated about changing. But I'm not super familiar with that topic, so I'm not sure to which point they are really specific to a use case, or just a matter of preference. The papers are not super clear on that, at least for me

**Comment by deccantrap** [comment]
Hello @rouault thank you very much for making the change. My view is the option between Riley and Wilson is not a matter of personal choice; Riley is used for ground surface terrain, Wilson is used for _underwater_ terrain. For obvious reasons, in practice, most roughness calculations are for ground surfaces, not underwater terrain. For instance, the top 20 Google Scholar searches for "terrain roughness index" do not contain any reference to Wilson (they do to Riley). Of course, I am advocating here that the default should be the Riley method because its use if more widespread. Regardless, thanks again for your work on this!

**Comment by rouault** [comment]
I've added a commit to change the default to Riley

**Comment by jratike80** [comment]
Out of curiosity, which TRI current GRASS code computes? I do not find squares and square roots in https://github.com/OSGeo/grass-addons/blob/master/grass7/raster/r.tri/r.tri.py but I am not especially good in reading the code.
