### ISSUE TITLE
ENH: Add GDT_Int64 & GDT_UInt64 Data Types

### ISSUE THREAD

**Issue by snowman2** [OSGeo/gdal#3325]
Forward from:
- https://trac.osgeo.org/gdal/ticket/6879
- https://github.com/mapbox/rasterio/issues/2072
- https://github.com/Toblerity/Fiona/issues/365

This comes from use cases I have seen recently:
- https://github.com/corteva/rioxarray/issues/195
- https://github.com/corteva/geocube/discussions/52

Bringing this up again in case there is interest in adding this, but was forgotten.

**Comment by rouault** [comment]
Note: I have an implementation ready for this, but would appreciate compensation for the time spent working on it.

**Comment by jratike80** [comment]
Implementing new features in not exactly in the core of the NumFocus funding  https://gdal.org/development/rfc/rfc80_numfocus_relationship.html if you mean that.

**Comment by rouault** [comment]
I was considering bringing that to life, but are there actual datasets that use int64/uint64 with upper 32 bit sets... ?

**Comment by snowman2** [comment]
OGR supports it: https://gdal.org/development/rfc/rfc31_ogr_64.html

The main thing that comes to mind is that when rasterizing a vector file with int64, you will run into problems.

There are also other scenarios users have run into due to numpy:  https://github.com/OSGeo/gdal/issues/3325#issue-775437314
