### ISSUE TITLE
Reading subdatasets from TIFF files

### ISSUE THREAD

**Issue by acraimundo** [OSGeo/gdal#3329]
## Expected behavior and actual behavior.

I've downloaded GDAL from GisInternals for testing purposes. I'm evaluating the library because in the company that I work for we want to replace our own C++ library for reading and writing TIFF files with GDAL.

I have a TIFF file in the link below. 
https://1drv.ms/u/s!AimCQ8fNYtmkqS1s0ckHJBmXVz13?e=XFtUyx

It is an aerial image in TIFF format that has multi-page. I was trying to read the pages using GDALDataset::GetMetadata("SUBDATASETS") and the library wasn't returning anything. Then, I realized gdalinfo.exe program couldn't read internal pages too.

```
❯ .\gdalinfo.exe -sd 5 '.\IC_5,2_1021_01_00010.tif'
gdalinfo warning: subdataset 5 of 0 requested. Reading the main dataset.
```

I've read in GTiff driver documentation the following:

_Starting with GDAL 3.2, read-only access to subdataset overviews and masks is possible provided that they are referenced by their parent IFD through the TIFFTAG_SUBIFD tag._

Maybe this is the issue with my TIFF file? Is there another way for me to read the pages?

## Steps to reproduce the problem.

gdalinfo.exe -sd 5 IC_5,2_1021_01_00010.tif

## Operating system

Windows 10 Enterprise
Version 1909 (OS Build 18363.1256)

## GDAL version and provenance

3.2.0 version from GisInternals - Stable Releases
MSVC 2017 x64
release-1911-x64-gdal-3-2-0-mapserver-7-6-1

https://www.gisinternals.com/query.html?content=filelist&file=release-1911-x64-gdal-3-2-0-mapserver-7-6-1.zip

**Comment by rouault** [comment]
From the gdalinfo output, you can see:
```
Band 1 Block=256x256 Type=Byte, ColorInterp=Red
  Overviews: 3880x5164, 1940x2582, 970x1291, 485x646, 243x323, 122x162, 61x81, 31x41, 16x21
Band 2 Block=256x256 Type=Byte, ColorInterp=Green
  Overviews: 3880x5164, 1940x2582, 970x1291, 485x646, 243x323, 122x162, 61x81, 31x41, 16x21
Band 3 Block=256x256 Type=Byte, ColorInterp=Blue
  Overviews: 3880x5164, 1940x2582, 970x1291, 485x646, 243x323, 122x162, 61x81, 31x41, 16x21
```

The TIFF subdirectories are recognized by GDAL as overview bands. You can use the GDALRasterBand::GetOverview() method to extract them
