### ISSUE TITLE
geom.Transform no longer works in GDAL 3.2.0

### ISSUE THREAD

**Issue by tjwebb** [OSGeo/gdal#3330]
## Expected behavior and actual behavior.

This code works in 2.4.4 and 3.1.2, but in 3.2.0 it runs without error but no coordinate transformation takes place. The before/after geometries are identical.

## Steps to reproduce the problem.
```python
src_prj = osr.SpatialReference()
src_prj.ImportFromEPSG(4269)
target_prj = osr.SpatialReference()
target_prj.ImportFromEPSG(4326)

geom = ... any geom
geom.Transform(osr.CoordinateTransformation(src_prj, target_prj))
# no effect. geom.GetSpatialReference() claims that it is 4326,
# but the coordinates are still in the 4269 projection
```

## Operating system
OSX Catalina

## GDAL version and provenance
gdal 3.2.0 from https://www.kyngchaos.com/software/frameworks/, python gdal 3.2.0 from pip. Everything else about my gdal installation seems to work perfectly.

```
>>> gdal.VersionInfo()
'3020000'

$ gdal-config --version
3.2.0
```

**Comment by jratike80** [comment]
I believe that you closed the ticket because you noticed that it is correct that the coordinates do not change. Here is a test with gdaltranslate.

```
gdaltransform -s_srs epsg:4269 -t_srs epsg:4326
Enter X Y [Z [T]] values separated by space, and press Return.
30 60 0
30 60 0
```

**Comment by tjwebb** [comment]
close! AutoIdentifyEPSG was incorrectly identifying my projection as 4269,
when the actual projection was EPSG 3968. Not sure if that's a separate
bug, or just part of the risk I take in asking osr to try to be too clever.

**Comment by jratike80** [comment]
But EPSG:3968 https://epsg.org/crs/wkt/id/3968 has rather little in common with EPSG:4269, mainly the ellipsoid.

**Comment by tjwebb** [comment]
Exactly, I don't know why 4269 was being identified. If you're interested
in pursuing further I can point you to the shapefile this occurs on.
