### ISSUE TITLE
gdal_translate crashes when generating some COG outputs

### ISSUE THREAD

**Issue by manthey** [OSGeo/gdal#3336]
## Expected behavior and actual behavior.

When using `gdal_translate` to convert a non-cog tiff to a cog tiff, with some files it crashes after printing `0...10...` (or sometimes `0...10...20`.  No output is generated.  For other files, this works as expected (a COG file is generated).

## Steps to reproduce the problem.

With the attached file, `gdal_translate nlcd_20000_300.tif test.tiff -of COG` will crash rather than output a file.

Here is a file that produces the problem on my system (gzipped for size):
[nlcd_20000_300.tif.gz](https://github.com/OSGeo/gdal/files/5758316/nlcd_20000_300.tif.gz)
This file was generated by downloading https://s3-us-west-2.amazonaws.com/mrlc/NLCD_2011_Land_Cover_L48_20190424.zip, unzipping it, and then running `gdal_translate ./NLCD_2011_Land_Cover_L48_20190424/NLCD_2011_Land_Cover_L48_20190424.img nlcd_20000_300.tif -tr 20000 300 -r nearest`

Based on the source `.img` file, if I use gdal_translate to change the resolution to a vertical spacing of more than 300 or so, the error doesn't occur.  I reduced the horizontal resolution more than the vertical to get a smaller sample file.  Not changing the resolution at all (just converting from img to tiff) will produce a file that causes the problem.  Using the img file directly does NOT cause the problem.

## Operating system

Ubuntu 18.04 64 bit on two different computers.  Also debian:sid docker.

## GDAL version and provenance

GDAL built from source on the Ubuntu machines.  This worked without crashing on GDAL 3.1.4 but not 3.2.0.  Doing a bisection, this works on commit d2730ae5f2fb6784daa55e54a661d0efce812c75, and starts failing on e03e81cac7b9f2ce703e3043894fd94486221969 ("Overview building: rework to avoid I/O to be done in resampling kernel").

I also confirmed this error occurs with a fresh docker container running debian:sid with gdal-bin installed via apt-get (GDAL 3.2.0, released 2020/10/26).

**Comment by manthey** [comment]
Thanks for the speedy fix for the file I attached.  This still crashes in the same way for files generated in similar manners.  For instance, a file generated via `gdal_translate ./NLCD_2011_Land_Cover_L48_20190424/NLCD_2011_Land_Cover_L48_20190424.img nlcd_250.tif -tr 250 250 -r nearest` still crashes.  This file is too big to upload to the github issue: [here is a link instead](https://data.kitware.com/api/v1/file/5ff468c62fa25629b9c1d69a/download).

**Comment by manthey** [comment]
@rouault Would you like me to make a new issue for the file that still fails?

**Comment by rouault** [comment]
> Would you like me to make a new issue for the file that still fails?

No, I've fixed it yesterday
