### ISSUE TITLE
Issue with gdal via conda install

### ISSUE THREAD

**Issue by Pikus16** [OSGeo/gdal#3338]
## Expected behavior and actual behavior.

When installing gdal==3.2.0 via conda, python fails to find the gdal module and we get the following -  "No module named gdal".
When installing gdal==3.1.1, this issue was not there.

Command line utilities like gdalwarp are found with no problem.

## Steps to reproduce the problem.

conda create -n test_gdal python=3.7
conda activate test_gdal 
conda install -c conda-forge gdal 
python -c "import gdal" # will give error here

## Operating system

Ubuntu 18.04 64 bit

## GDAL version and provenance

3.2.0

**Comment by rouault** [comment]
> python -c "import gdal" # will give error here

This syntax has been deprecated for ~ 10 years. You should use "from osgeo import gdal" now. See https://github.com/OSGeo/gdal/blob/master/gdal/MIGRATION_GUIDE.TXT#L4
