### ISSUE TITLE
Failed to link with kakadu 8.0.3 (windows)

### ISSUE THREAD

**Issue by lahavy** [OSGeo/gdal#3340]
failed to build gdal v 3.2.1 with kakadu v8_0_3-01674C wit vs 2017
## Steps to reproduce the problem.

1. Compile kakadu core sys and apps with vs 2017 (64bit)
2. modify nmake to compile with kakadu
3. compile gdal using C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Auxiliary\Build\vcvarsall amd64, and the following command line:
nmake -f makefile.vc MSVC_VER=1910 WIN64=yes

here is sample of the link errors:
 
c:\test\kakadu\v8_0_3-01674c\v8_0_3-01674c\managed\all_includes\kdu_image.h(367): warning C4458: declaration of 'meta_manager' hides class member
c:\test\kakadu\v8_0_3-01674c\v8_0_3-01674c\managed\all_includes\kdu_image.h(774): note: see declaration of 'kdu_supp::kdu_image_dims::meta_manager'
        link /dll  /out:gdal_JP2KAK.dll jp2kakdataset.obj ..\..\gdal_i.lib C:\Test\kakadu\v8_0_3-01674C\lib_x64\kdu_v80R.lib    C:\Test\kakadu\v8_0_3-01674C\lib_x64\kdu_v80R.lib
Microsoft (R) Incremental Linker Version 14.16.27032.1
Copyright (C) Microsoft Corporation.  All rights reserved.

   Creating library gdal_JP2KAK.lib and object gdal_JP2KAK.exp
jp2kakdataset.obj : error LNK2001: unresolved external symbol "public: virtual void __cdecl kdu_supp::jp2_family_src::open(char const *,bool,class kdu_core::kdu_membroker *)" (?open@jp2_family_src@kdu_supp@@UEAAXPEBD_NPEAVkdu_membroker@kdu_core@@@Z)
jp2kakdataset.obj : error LNK2019: unresolved external symbol "public: virtual void __cdecl kdu_supp::jp2_family_src::open(class kdu_core::kdu_compressed_source *,class kdu_core::kdu_membroker *)" (?open@jp2_family_src@kdu_supp@@UEAAXPEAVkdu_compressed_source@kdu_core@@PEAVkdu_membroker@4@@Z) referenced in function "private: enum CPLErr __cdecl JP2KAKDataset::DirectRasterIO(enum GDALRWFlag,int,int,int,int,void *,int,int,enum GDALDataType,int,int *,__int64,__int64,__int64,struct GDALRasterIOExtraArg *)" (?DirectRasterIO@JP2KAKDataset@@AEAA?AW4CPLErr@@W4GDALRWFlag@@HHHHPEAXHHW4GDALDataType@@HPEAH_J44PEAUGDALRasterIOExtraArg@@@Z)
jp2kakdataset.obj : error LNK2001: unresolved external symbol "public: virtual void __cdecl kdu_supp::jp2_family_src::open(class kdu_supp::kdu_cache *,class kdu_core::kdu_membroker *)" (?open@jp2_family_src@kdu_supp@@UEAAXPEAVkdu_cache@2@PEAVkdu_membroker@kdu_core@@@Z)
jp2kakdataset.obj : error LNK2019: unresolved external symbol "public: virtual void __cdecl kdu_supp::jp2_family_src::close(bool)" (?close@jp2_family_src@kdu_supp@@UEAAX_N@Z) referenced in function "private: enum CPLErr __cdecl JP2KAKDataset::DirectRasterIO(enum GDALRWFlag,int,int,int,int,void *,int,int,enum GDALDataType,int,int *,__int64,__int64,__int64,struct GDALRasterIOExtraArg *)" (?DirectRasterIO@JP2KAKDataset@@AEAA?AW4CPLErr@@W4GDALRWFlag@@HHHHPEAXHHW4GDALDataType@@HPEAH_J44PEAUGDALRasterIOExtraArg@@@Z)
jp2kakdataset.obj : error LNK2019: unresolved external symbol "public: void __cdecl kdu_supp::jp2_family_tgt::open(class kdu_core::kdu_compressed_target *,class kdu_core::kdu_membroker *)" (?open@jp2_family_tgt@kdu_supp@@QEAAXPEAVkdu_compressed_target@kdu_core@@PEAVkdu_membroker@4@@Z) referenced in function "class GDALDataset * __cdecl JP2KAKCreateCopy(char const *,class GDALDataset *,int,char * *,int (__cdecl*)(double,char const *,void *),void *)" (?JP2KAKCreateCopy@@YAPEAVGDALDataset@@PEBDPEAV1@HPEAPEADP6AHN0PEAX@Z3@Z)
jp2kakdataset.obj : error LNK2019: unresolved external symbol "public: void __cdecl kdu_supp::jp2_family_tgt::close(void)" (?close@jp2_family_tgt@kdu_supp@@QEAAXXZ) referenced in function "class GDALDataset * __cdecl JP2KAKCreateCopy(char const *,class GDALDataset *,int,char * *,int (__cdecl*)(double,char const *,void *),void *)" (?JP2KAKCreateCopy@@YAPEAVGDALDataset@@PEBDPEAV1@HPEAPEADP6AHN0PEAX@Z3@Z)
......
## Operating system
Windows

**Comment by rouault** [comment]
>     2\. modify nmake to compile with kakadu

Please indicate your nmake.opt Kakadu related settings

**Comment by lahavy** [comment]
nmake modifications for kakadu:

KAKFLAGS=-DKDU_MAJOR_VERSION=8 -DKDU_MINOR_VERSION=0 -DKDU_PATCH_VERSION=3
KAKDIR = C:\Test\kakadu\v8_0_3-01674C
KAKLIB = $(KAKDIR)\lib_x64\kdu_v80R.lib 	
KAKSRC = $(KAKDIR)\v8_0_3-01674C
KAKEXTRAINC=-I$(KAKDIR)
KAKOBJDIR =  $(KAKDIR)\v8_generated_x64
JP2KAK_PLUGIN = YES
!IFNDEF KAKADU_7_5_OR_LATER
KAKADU_7_5_OR_LATER = YES
!ENDIF

**Comment by lahavy** [comment]
After adding $(KAKDIR)\lib_x64\kdu_a80R.lib it compiled without errors, but the following command fails with link errors:

nmake -f makefile.vc install MSVC_VER=1910 WIN64=yes

Errors:
C:\Test\gdal-3.2.1\gdal-3.2.1>if exist *.ilk del *.ilk
        link /nologo /dll /INCLUDE:OSRValidate  /INCLUDE:OGR_G_GetPointCount  /INCLUDE:OGRRegisterAll /INCLUDE:GDALSimpleImageWarp  /INCLUDE:GDALReprojectImage  /INCLUDE:GDALComputeMedianCutPCT  /INCLUDE:GDALDitherRGB2PCT  /INCLUDE:OCTNewCoordinateTransformation port\*.obj gcore\*.obj alg\*.obj frmts\o\*.obj ogr\ogrsf_frmts\ogrsf_frmts.lib ogr\ogr.lib gnm\*.obj gnm\gnm_frmts\o\*.obj third_party\o\*.obj apps\commonutils.obj apps\gdalinfo_lib.obj apps\gdal_translate_lib.obj apps\gdalwarp_lib.obj apps\ogr2ogr_lib.obj  apps\gdaldem_lib.obj apps\nearblack_lib.obj apps\gdal_grid_lib.obj apps\gdal_rasterize_lib.obj apps\gdalbuildvrt_lib.obj  apps\gdalmdiminfo_lib.obj apps\gdalmdimtranslate_lib.obj                      C:\OSGeo4W64_proj7.2.0\lib\proj.lib               legacy_stdio_definitions.lib odbc32.lib odbccp32.lib user32.lib                              ws2_32.lib       kernel32.lib psapi.lib wbemuuid.lib gcore\Version.res  /out:gdal302.dll /implib:gdal_i.lib
   Creating library gdal_i.lib and object gdal_i.exp
jpx.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: __cdecl kdu_core::kdu_error::kdu_error(char const *)" (__imp_??0kdu_error@kdu_core@@QEAA@PEBD@Z)
kdu_region_decompressor.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: __cdecl kdu_core::kdu_error::kdu_error(char const *)" (__imp_??0kdu_error@kdu_core@@QEAA@PEBD@Z)
kdu_stripe_decompressor.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: __cdecl kdu_core::kdu_error::kdu_error(char const *)" (__imp_??0kdu_error@kdu_core@@QEAA@PEBD@Z)
mj2.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: __cdecl kdu_core::kdu_error::kdu_error(char const *)" (__imp_??0kdu_error@kdu_core@@QEAA@PEBD@Z)
args.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: __cdecl kdu_core::kdu_error::kdu_error(char const *)" (__imp_??0kdu_error@kdu_core@@QEAA@PEBD@Z)
image_in.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: __cdecl kdu_core::kdu_error::kdu_error(char const *)" (__imp_??0kdu_error@kdu_core@@QEAA@PEBD@Z)
image_out.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: __cdecl kdu_core::kdu_error::kdu_error(char const *)" (__imp_??0kdu_error@kdu_core@@QEAA@PEBD@Z)
jp2.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: __cdecl kdu_core::kdu_error::kdu_error(char const *)" (__imp_??0kdu_error@kdu_core@@QEAA@PEBD@Z)
mj2.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: virtual __cdecl kdu_core::kdu_error::~kdu_error(void)" (__imp_??1kdu_error@kdu_core@@UEAA@XZ)
roi_sources.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: virtual __cdecl kdu_core::kdu_error::~kdu_error(void)" (__imp_??1kdu_error@kdu_core@@UEAA@XZ)
jpx.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: virtual __cdecl kdu_core::kdu_error::~kdu_error(void)" (__imp_??1kdu_error@kdu_core@@UEAA@XZ)
kdu_region_decompressor.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: virtual __cdecl kdu_core::kdu_error::~kdu_error(void)" (__imp_??1kdu_error@kdu_core@@UEAA@XZ)
kdu_stripe_decompressor.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: virtual __cdecl kdu_core::kdu_error::~kdu_error(void)" (__imp_??1kdu_error@kdu_core@@UEAA@XZ)
kdu_tiff.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: virtual __cdecl kdu_core::kdu_error::~kdu_error(void)" (__imp_??1kdu_error@kdu_core@@UEAA@XZ)
args.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: virtual __cdecl kdu_core::kdu_error::~kdu_error(void)" (__imp_??1kdu_error@kdu_core@@UEAA@XZ)
image_in.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: virtual __cdecl kdu_core::kdu_error::~kdu_error(void)" (__imp_??1kdu_error@kdu_core@@UEAA@XZ)
image_out.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: virtual __cdecl kdu_core::kdu_error::~kdu_error(void)" (__imp_??1kdu_error@kdu_core@@UEAA@XZ)
jp2.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: virtual __cdecl kdu_core::kdu_error::~kdu_error(void)" (__imp_??1kdu_error@kdu_core@@UEAA@XZ)
image_in.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl kdu_core::kdu_error::kdu_error(void)" (__imp_??0kdu_error@kdu_core@@QEAA@XZ) referenced in function "public: __cdecl kd_supp_image_local::bmp_in::bmp_in(char const *,class kdu_supp::kdu_image_dims &,int &,bool &,struct kdu_supp::kdu_rgb8_palette *,__int64)" (??0bmp_in@kd_supp_image_local@@QEAA@PEBDAEAVkdu_image_dims@kdu_supp@@AEAHAEA_NPEAUkdu_rgb8_palette@3@_J@Z)
image_out.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: __cdecl kdu_core::kdu_error::kdu_error(void)" (__imp_??0kdu_error@kdu_core@@QEAA@XZ)
kdu_tiff.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: __cdecl kdu_core::kdu_error::kdu_error(void)" (__imp_??0kdu_error@kdu_core@@QEAA@XZ)
roi_sources.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: __cdecl kdu_core::kdu_error::kdu_error(void)" (__imp_??0kdu_error@kdu_core@@QEAA@XZ)
image_in.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) public: __cdecl kdu_core::kdu_warning::kdu_warning(void)" (__imp_??0kdu_warning@kdu_core@@QEAA@XZ) referenced in function "public: __cdecl kd_supp_image_local::bmp_in::bmp_in(char const *,class kdu_supp::kdu_image_dims &,int &,bool &,struct kdu_supp::kdu_rgb8_palette *,__int64)" (??0bmp_in@kd_supp_image_local@@QEAA@PEBDAEAVkdu_image_dims@kdu_supp@@AEAHAEA_NPEAUkdu_rgb8_palette@3@_J@Z)
.....

**Comment by lahavy** [comment]
commented KAKOBJDIR and it works.
