### ISSUE TITLE
semi_major and semi_minor WKT parameters are ignored 

### ISSUE THREAD

**Issue by simonff** [OSGeo/gdal#3346]
## Expected behavior and actual behavior.

semi_major and semi_minor WKT parameters are ignored at least for one projection

## Steps to reproduce the problem.

(semi_minor and semi_major values are intentionally bad. It does not matter what src.tif is)

gdal_translate -a_srs 'PROJCS["NWS CONUS", GEOGCS["WGS 84", DATUM["World Geodetic System 1984", SPHEROID["WGS 84", 6378137.0, 298.257223563, AUTHORITY["EPSG","7030"]], AUTHORITY["EPSG","6326"]], PRIMEM["Greenwich", 0.0, AUTHORITY["EPSG","8901"]], UNIT["degree", 0.017453292519943295], AXIS["Geodetic longitude", EAST], AXIS["Geodetic latitude", NORTH], AUTHORITY["EPSG","4326"]], PROJECTION["Lambert_Conformal_Conic_1SP"], PARAMETER["semi_major", 8371200.0], PARAMETER["semi_minor", 7371200.0], PARAMETER["central_meridian", -95.0], PARAMETER["latitude_of_origin", 25.0], PARAMETER["scale_factor", 1.0], PARAMETER["false_easting", 0.0], PARAMETER["false_northing", 0.0], UNIT["m", 1.0], AXIS["x", EAST], AXIS["y", NORTH]]' src.tif dst.tif

Then gdalinfo reports an SRS without semi_minor and semi_major values

## Operating system

Google Debian 64 bit

## GDAL version and provenance

3.1.4 from Google corp distribution

**Comment by rouault** [comment]
Can you post the gdalinfo output ?

I get with GDAL master
```
PROJCRS["NWS CONUS",
    BASEGEOGCRS["WGS 84",
        DATUM["World Geodetic System 1984",
            ELLIPSOID["WGS 84",6378137,298.257223563,
                LENGTHUNIT["metre",1]]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433]],
        ID["EPSG",4326]],
    CONVERSION["Lambert Conic Conformal (1SP)",
        METHOD["Lambert Conic Conformal (1SP)",
            ID["EPSG",9801]],
        PARAMETER["Latitude of natural origin",25,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",-95,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["Scale factor at natural origin",1,
            SCALEUNIT["unity",1],
            ID["EPSG",8805]],
        PARAMETER["False easting",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["easting",east,
            ORDER[1],
            LENGTHUNIT["metre",1,
                ID["EPSG",9001]]],
        AXIS["northing",north,
            ORDER[2],
            LENGTHUNIT["metre",1,
                ID["EPSG",9001]]]]
```

> 3.1.4 from Google corp distribution

What's that ??

**Comment by rouault** [comment]
Ah, sorry I missed the PARAMETER["semi_major", 8371200.0], PARAMETER["semi_minor", 7371200.0] in your WKT. Those parameters are non standard for LCC_1SP, and are thus ignored. GDAL / PROJ behaves as expected here

**Comment by jratike80** [comment]
See the reference of supported parameters https://proj.org/operations/projections/lcc.html.

**Comment by rouault** [comment]
@simonff  What is the semantics of those semi_major and semi_minor WKT parameters ? Where such non-standard WKT come from ?

**Comment by simonff** [comment]
The LambertConformal projection in geotools supports these fields, which are defined in the parent class MapProjection and used there. Earth Engine uses geotools, so it can understand this WKT.

**Comment by rouault** [comment]
The standard way of encoding the ellipsoidal parameters is in the SPHEROID["name", semi_major, reverse_flattening] node. And the values of semi_major=8371200.0 and semi_minor=7371200.0 are quite suspicious for Earth.

**Comment by simonff** [comment]
Yes, I made these values bad on purpose for debugging. I'll try using the encoding you suggest.

**Comment by rouault** [comment]
You might also need to change the datum name and remove the AUTHORITY["EPSG","6326"] node, to avoid PROJ to be confused by inline definition != EPSG definition. And possibly do the same as the GEOGCS level

**Comment by rouault** [comment]
This is too geotools specific and no longer aligns with the new WKT specifications. We could possibly hack some support for that in PROJ when ingesting such WKT, but there's no way GeoTIFF can store a semi_major and semi_minor that don't match the ones of the ellipsoid of the datum.
