### ISSUE TITLE
AttributeError: module '_gdal' has no attribute 'DirEntry_name_get'

### ISSUE THREAD

**Issue by HanwGeek** [OSGeo/gdal#3360]
## Expected behavior and actual behavior.

I want to use gdal in python3.6 with QGIS but when I `from osgeo import gdal`, it shows:
```python
>>> from osgeo import gdal
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/osgeo/gdal.py", line 1565, in <module>
    class DirEntry(_object):
  File "/usr/local/lib/python3.6/dist-packages/osgeo/gdal.py", line 1573, in DirEntry
    __swig_getmethods__["name"] = _gdal.DirEntry_name_get
AttributeError: module '_gdal' has no attribute 'DirEntry_name_get'
```

## Steps to reproduce the problem.

`from osgeo import gdal`

## Operating system

 Ubuntu 18.04 64 bit

## GDAL version and provenance

the 2.2.3 version from qgis.org repo

**Comment by jratike80** [comment]
You have also asked a question on the mailing list. That's the right place to ask questions. There was no need to open also a bug report.

Unfortunately I don't know how to correct your environment. I am using GDAL 3.1.4 on Windows with Python 3.7 without problems, all installed with OSGeo4W installer.

**Comment by rouault** [comment]
I assume something wrong with your installation. DirEntry_name_get should be found in /usr/local/lib/python3.6/dist-packages/osgeo/_gdal.so

**Comment by HanwGeek** [comment]
I first removed all dependencies and the install GDAL with QGIS from
qgis.org repo. In fact, before I install QGIS, I can use GDAL normally.

Even Rouault <notifications@github.com> 于2021年1月9日周六 上午1:41写道：

**Comment by rouault** [comment]
This is likely some conflict between the GDAL package from the distribution and the ones from qgis.org. Not a GDAL upstream bug.
