### ISSUE TITLE
Flatgeobuf: Heap-buffer-overflow in VSIMemHandle::Read

### ISSUE THREAD

**Issue by rouault** [OSGeo/gdal#3364]
CC @bjornharrtell 

See https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=29462

**Comment by bjornharrtell** [comment]
I can see it is a `heap-buffer-overflow` triggered by https://github.com/OSGeo/gdal/blob/a03fb3d0c81b307917f13b7dbcc7ca66717a8433/gdal/ogr/ogrsf_frmts/flatgeobuf/ogrflatgeobuflayer.cpp#L515 but I'm at a loss to understand the cause.

**Comment by nathreed** [comment]
Should this be marked as closed? Looks like (as per the linked oss-fuzz page) it was fixed in commit 7b98226... on April 5, 2021.
