### ISSUE TITLE
Incorrect transformation from EPSG:4326 to EPGS:2774

### ISSUE THREAD

**Issue by jtiai** [OSGeo/gdal#3377]
## Expected behavior and actual behavior.

When converting the following coordinates with GDAL 3.2.1 incorrect transformation happens:

| |EPSG:4326 | EPSG:2774 |
|-|------------|-------------|
| Incorrect | POINT (-104.609 38.255) | POINT (992386.3085979 481454.8075174) |
| Correct | POINT (-104.609 38.255) | POINT (992385.4472045 481455.4944650) |

## Steps to reproduce the problem.

Install `python3-gdal` package and use the following Python code:

```python
from osgeo import ogr
from osgeo import osr

InSR = osr.SpatialReference()
InSR.ImportFromEPSG(4326)       # WGS84/Geographic
OutSR = osr.SpatialReference()
OutSR.ImportFromEPSG(2774)     # NAD83(HARN) / Colorado South

Point = ogr.Geometry(ogr.wkbPoint)
Point.AddPoint(38.255,-104.609) # use your coordinates here
Point.AssignSpatialReference(InSR)    # tell the point what coordinates it's in
Point.TransformTo(OutSR)              # project it to the out spatial reference
print('{0},{1}'.format(Point.GetX(),Point.GetY())) # output projected X and Y coordinates
```

## Operating system

Debian 10.7 (correct behavior)
Debian testing (incorrect behavior)

## GDAL version and provenance

Debian 10.7, GDAL 2.4.0 (correct behavior)
Debian testing, GDAL 3.2.1 (incorrect behavior)

**Comment by jratike80** [comment]
The results are slightly different but what is your reference for the correct result?
I guess the difference is in different Proj versions.

Proj 6.2 seems to give the result that you think is correct.
Proj 8 gives the result that you call as incorrect.

**Comment by jtiai** [comment]
https://epsg.io/transform#s_srs=4326&t_srs=2774&x=-104.6090000&y=38.2550000

Above gives only 2 decimals but they are closer to "correct" values.

Also Django Web Framework has quite extensive GIS suite which passes on Debian 10.7 (apparently Proj 6.2) but fails coordinate transformation tests on Debian Test (apparently Proj 8) specially on that particular conversion.

**Comment by rouault** [comment]
Despite its name, epsg.io is *NOT* a reference. It is not maintained by EPSG.
And here, as a datum shift is involved, there is generally no real *true* result, it is always the result of a somewhat arbitrary choice if you don't specify the transformation you wish.

The result with recent PROJ uses the "NAD83(HARN) to WGS 84 (3)" transformation that does a Helmert shift, whereas previously it used "NAD83(HARN) to WGS 84 (1)" that is a null transformation. Both are advertized by EPSG as having a 1 m accuracy. Recent PROJ versions will use by default the transformation "foo (X)" over "foo (Y)" where X > Y when both transformations have the same advertized accuracy (which is the case here), whereas earlier versions would use X < Y.

With PROJ-master:
```
$ projinfo -s EPSG:4326 -t EPSG:2774 -o PROJ
Candidate operations found: 2
-------------------------------------
Operation No. 1:

unknown id, Inverse of NAD83(HARN) to WGS 84 (3) + SPCS83 Colorado South zone (meters), 1 m, United States (USA) - CONUS onshore - Alabama; Arizona; Arkansas; California; Colorado; Connecticut; Delaware; Florida; Georgia; Idaho; Illinois; Indiana; Iowa; Kansas; Kentucky; Louisiana; Maine; Maryland; Massachusetts; Michigan; Minnesota; Mississippi; Missouri; Montana; Nebraska; Nevada; New Hampshire; New Jersey; New Mexico; New York; North Carolina; North Dakota; Ohio; Oklahoma; Oregon; Pennsylvania; Rhode Island; South Carolina; South Dakota; Tennessee; Texas; Utah; Vermont; Virginia; Washington; West Virginia; Wisconsin; Wyoming.

PROJ string:
+proj=pipeline
  +step +proj=axisswap +order=2,1
  +step +proj=unitconvert +xy_in=deg +xy_out=rad
  +step +proj=push +v_3
  +step +proj=cart +ellps=WGS84
  +step +inv +proj=helmert +x=-0.991 +y=1.9072 +z=0.5129 +rx=-0.0257899075194932
        +ry=-0.0096500989602704 +rz=-0.0116599432323421 +s=0
        +convention=coordinate_frame
  +step +inv +proj=cart +ellps=GRS80
  +step +proj=pop +v_3
  +step +proj=lcc +lat_0=36.6666666666667 +lon_0=-105.5 +lat_1=38.4333333333333
        +lat_2=37.2333333333333 +x_0=914401.8289 +y_0=304800.6096 +ellps=GRS80

-------------------------------------
Operation No. 2:

unknown id, Inverse of NAD83(HARN) to WGS 84 (1) + SPCS83 Colorado South zone (meters), 1 m, American Samoa - onshore - Tutuila, Aunu'u, Ofu, Olesega, Ta'u and Rose islands. Guam - onshore. Northern Mariana Islands - onshore. Puerto Rico - onshore. United States (USA) - onshore Alabama, Alaska, Arizona, Arkansas, California, Colorado, Connecticut, Delaware, Florida, Georgia, Hawaii, Idaho, Illinois, Indiana, Iowa, Kansas, Kentucky, Louisiana, Maine, Maryland, Massachusetts, Michigan, Minnesota, Mississippi, Missouri, Montana, Nebraska, Nevada, New Hampshire, New Jersey, New Mexico, New York, North Carolina, North Dakota, Ohio, Oklahoma, Oregon, Pennsylvania, Rhode Island, South Carolina, South Dakota, Tennessee, Texas, Utah, Vermont, Virginia, Washington, West Virginia, Wisconsin and Wyoming; offshore Gulf of Mexico continental shelf (GoM OCS). US Virgin Islands - onshore.

PROJ string:
+proj=pipeline
  +step +proj=axisswap +order=2,1
  +step +proj=unitconvert +xy_in=deg +xy_out=rad
  +step +proj=lcc +lat_0=36.6666666666667 +lon_0=-105.5 +lat_1=38.4333333333333
        +lat_2=37.2333333333333 +x_0=914401.8289 +y_0=304800.6096 +ellps=GRS80
```

```
$ echo 38.255 -104.609 0 | cct +proj=pipeline +step +proj=axisswap +order=2,1 +step +proj=unitconvert +xy_in=deg +xy_out=rad +step +proj=push +v_3 +step +proj=cart +ellps=WGS84 +step +inv +proj=helmert +x=-0.991 +y=1.9072 +z=0.5129 +rx=-0.0257899075194932 +ry=-0.0096500989602704 +rz=-0.0116599432323421 +s=0 +convention=coordinate_frame +step +inv +proj=cart +ellps=GRS80 +step +proj=pop +v_3 +step +proj=lcc +lat_0=36.6666666666667 +lon_0=-105.5 +lat_1=38.4333333333333 +lat_2=37.2333333333333 +x_0=914401.8289 +y_0=304800.6096 +ellps=GRS80
  992386.3086    481454.8075        0.0000           inf
```

```
$ echo 38.255 -104.609 0 | cct +proj=pipeline  +step +proj=axisswap +order=2,1  +step +proj=unitconvert +xy_in=deg +xy_out=rad  +step +proj=lcc +lat_0=36.6666666666667 +lon_0=-105.5 +lat_1=38.4333333333333   +lat_2=37.2333333333333 +x_0=914401.8289 +y_0=304800.6096 +ellps=GRS80
  992385.4472    481455.4944        0.0000           inf
```

So I'd say there's nothing to fix. And this is a purely PROJ behaviour.

**Comment by rouault** [comment]
Actually the new behaviour is the correct one. The old one was using a datum shift valid for American Samoa... wheras the new one used a transformation valid for Continental US

**Comment by jtiai** [comment]
Also if I'm not mistaken Oracle database gis coordinate transformations does faulty trasformation because it returns same as older proj4. 

But thank you for detailed explanation.
