### ISSUE TITLE
请问有中文使用文档吗

### ISSUE THREAD

**Issue by momowuyule** [OSGeo/gdal#338]
## Expected behavior and actual behavior.

For example: I expected to be able to open this raster file (with a link to
the raster file, or it as an attachement) and it returns an error message
instead.

## Steps to reproduce the problem.

For example: "gdalinfo myfile"

## Operating system

For example: Ubuntu 16.04 64 bit

## GDAL version and provenance

For example: the 2.2.3 version from ubuntugis-unstable PPA

**Comment by rouault** [comment]
Closing. The title apparently means "Do you have documents in Chinese ?". This is to report issues , not ask questions.
