### ISSUE TITLE
VRT derived band pixel function in Python doesn't support complex data

### ISSUE THREAD

**Issue by clausmichele** [OSGeo/gdal#3383]
## Expected behavior and actual behavior.

I wrote two VRT with as input a raster of complex data and as output the real and imaginary part using a python function, following [this.](http://osgeo-org.1560.x6.nabble.com/gdal-dev-VRT-derived-band-pixel-functions-written-in-Python-td5285323.html)
The result for the real part is ok. The one for the imaginary part is always 0.
I did a bit of investigation and it seems that **the array inside the Python function comes already "filtered" without the imaginary part**.

I've tried to open the vrts in QGIS and to write a new geotiff using the command `gdal_translate --config GDAL_VRT_ENABLE_PYTHON YES test_im.vrt test_im.tif` and I got the same result, the imaginary part is always 0.

## Steps to reproduce the problem.

1. Download the sample data and vrts: [complex_data_VRT.zip](https://github.com/OSGeo/gdal/files/5820858/complex_data_VRT.zip)
2. Extract the imaginary part: `gdal_translate --config GDAL_VRT_ENABLE_PYTHON YES test_im.vrt test_im.tif`
3. Check the result with QGIS or gdal, which is a matrix of zeros.
4. Extract the real part: `gdal_translate --config GDAL_VRT_ENABLE_PYTHON YES test_real.vrt test_real.tif`
5. Check the result with QGIS or gdal, it shows the correct real part of the input data.

## Operating system

Ubuntu 18.04 64 bit

## GDAL version and provenance

GDAL 2.4.4, released 2020/01/08
and also
GDAL 3.0.2, released 2019/10/28

**Comment by avalentino** [comment]
My first guess is that probably you should use
```
<SourceTransferType>CFloat64</SourceTransferType>
```
as described in [VRT](https://gdal.org/drivers/raster/vrt.html?highlight=pixelfunction#using-derived-bands-with-pixel-functions-in-c-c) format documentation.
