### ISSUE TITLE
gdalbuildvrt -input_file_list is prone to errors

### ISSUE THREAD

**Issue by frspp** [OSGeo/gdal#3389]
GDAL 3.1.2, released 2020/07/07
macos 11.1 (m1 mac)

**CASE1**
**input-file.txt content** 
/Users/m/GIS/korkeusmalli-hila_10m/etrs-tm35fin-n2000/K2/K23/K2344.tif  
/Users/m/GIS/korkeusmalli-hila_10m/etrs-tm35fin-n2000/K2/K24/K2433.tif  
/Users/m/GIS/korkeusmalli-hila_10m/etrs-tm35fin-n2000/K2/K24/K2434.tif 
 
**Command**
$ /Applications/QGIS.app/Contents/MacOS/bin/gdalbuildvrt -resolution average -r nearest /Users/m/GIS/vinovalovarjoste.vrt -input_file_list /Users/m/GIS/vinovalovarjoste-input-list.txt

**output**
0...10...20...30...40...50...60...70...80...90...100 - done.
ERROR 4: `/Users/m/GIS/korkeusmalli-hila_10m/etrs-tm35fin-n2000/K2/K23/K2344.tif  /Users/m/GIS/korkeusmalli-hila_10m/etrs-tm35fin-n2000/K2/K24/K2433.tif

_and later_
/Users/m/GIS/korkeusmalli-hila_10m/etrs-tm35fin-n2000/X5/X52/X5213.tif' does not exist in the file system, and is not recognized as a supported dataset name.
Warning 1: Can't open /Users/m/GIS/korkeusmalli-hila_10m/etrs-tm35fin-n2000/K2/K23/K2344.tif

**CASE 2** 
**input-file.txt content like**
"/Users/m/GIS/korkeusmalli-hila_10m/etrs-tm35fin-n2000/K2/K23/K2344.tif"  
"/Users/m/GIS/korkeusmalli-hila_10m/etrs-tm35fin-n2000/K2/K24/K2433.tif"  
"/Users/m/GIS/korkeusmalli-hila_10m/etrs-tm35fin-n2000/K2/K24/K2434.tif" 
 "/Users/m/GIS/korkeusmalli-hila_10m/etrs-tm35fin-n2000/K2/K24/K2441.tif"  

**Command**
$ /Applications/QGIS.app/Contents/MacOS/bin/gdalbuildvrt -resolution average -r nearest /Users/m/GIS/vinovalovarjoste.vrt -input_file_list /Users/m/GIS/vinovalovarjoste-input-list.txt

**output**
0...10...20...30...40...50...60...70...80...90...100 - done.
ERROR 4: `"/Users/m/GIS/korkeusmalli-hila_10m/etrs-tm35fin-n2000/K2/K23/K2344.tif"  "/Users/m/GIS/korkeusmalli-hila_10m/etrs-tm35fin-n2000/K2/K24/K2433.tif"  "/Users/m/GIS/korkeusmalli-hila_10m/etrs-tm35fin-n2000/K2/K24/K2434.tif" 

_and in later_ 
Warning 1: Can't open "/Users/m/GIS/korkeusmalli-hila_10m/etrs-tm35fin-n2000/K2/K23/K2344.tif"  "/Users/m/GIS/korkeusmalli-hila_10m/etrs-tm35fin-n2000/K2/K24/K2433.tif"  "/Users/m/GIS/korkeusmalli-hila_10m/etrs-tm35fin-n2000/K2/K24/K2434.tif" ...  "/Users/m/GIS/korkeusmalli-hila_10m/etrs-tm35fin-n2000/X5/X52/X5213.tif". Skipping it

**Suggested fix**
Accept input file with two formats:

"file1" "file2" "file3"

file1 
file2 
file3 

**ALSO related**
"There is definitely a limitation on the size of the command. To reduce that and be able to include as many files as possible, put all files into a folder on the root with a small name like a 2-3 character. This way the possibility of getting error will be minimized!" https://gis.stackexchange.com/a/342772

**Comment by jratike80** [comment]
Hi,

I am just running a test with a text file where I stored all the filenames of the 2 m DEM of the National Land Survey of Finland. My path is rather similar. Z is not a local disk but a network share. There are 10185 rows in the text file.

```
Z:\korkeusmalli\hila_2m\etrs-tm35fin-n2000\K2\K24\K2444F.tif
Z:\korkeusmalli\hila_2m\etrs-tm35fin-n2000\K2\K24\K2444H.tif
Z:\korkeusmalli\hila_2m\etrs-tm35fin-n2000\K3\K32\K3222B.tif
```

I did not face any errors.

```
gdalbuildvrt -resolution average -r nearest vinovalovarjoste.vrt -input_file_list files.txt
0...10...20...30...40...50...60...70...80...90...100 - done.
```
The filesize of the result:

`5 030 136 vinovalovarjoste.vrt`

I suppose that your troubles have something to do with your environment. Have you experienced any hardware problems with you disk? Did you check with gdalinfo that the suspicious files really are on the disk and that they are not corrupted?

The stackexchange answer may make sense if the filenames are given directly from the command line. For  Windods command line the limit is 32767 characters. Input list file should not have such limit. My list file that I used in the test above has more than 600000 characters.

**Comment by frspp** [comment]
Thanks for the reply. No hw problems. 

Is checksum or approx_stats fine for checking files are on the disk and not corrupted?

**% /Applications/QGIS.app/Contents/MacOS/bin/gdalinfo -checksum /Users/m/GIS/korkeusmalli-hila_10m/etrs-tm35fin-n2000/K2/K24/K2433.tif**
Driver: GTiff/GeoTIFF
Files: /Users/m/GIS/korkeusmalli-hila_10m/etrs-tm35fin-n2000/K2/K24/K2433.tif
       /Users/m/GIS/korkeusmalli-hila_10m/etrs-tm35fin-n2000/K2/K24/K2433.tif.aux.xml
Size is 2400, 1200
Coordinate System is:
PROJCRS["ETRS89 / TM35FIN(E,N)",
    BASEGEOGCRS["ETRS89",
        DATUM["European Terrestrial Reference System 1989",
            ELLIPSOID["GRS 1980",6378137,298.257222101,
                LENGTHUNIT["metre",1]]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433]],
        ID["EPSG",4258]],
    CONVERSION["TM35FIN",
        METHOD["Transverse Mercator",
            ID["EPSG",9807]],
        PARAMETER["Latitude of natural origin",0,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",27,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["Scale factor at natural origin",0.9996,
            SCALEUNIT["unity",1],
            ID["EPSG",8805]],
        PARAMETER["False easting",500000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["(E)",east,
            ORDER[1],
            LENGTHUNIT["metre",1]],
        AXIS["(N)",north,
            ORDER[2],
            LENGTHUNIT["metre",1]],
    USAGE[
        SCOPE["unknown"],
        AREA["Finland"],
        BBOX[58.84,19.08,70.09,31.59]],
    ID["EPSG",3067]]
Data axis to CRS axis mapping: 1,2
Origin = (92000.000000000000000,6630000.000000000000000)
Pixel Size = (10.000000000000000,-10.000000000000000)
Metadata:
  AREA_OR_POINT=Area
Image Structure Metadata:
  COMPRESSION=LZW
  INTERLEAVE=BAND
Corner Coordinates:
Upper Left  (   92000.000, 6630000.000) ( 19d45'40.44"E, 59d36'27.74"N)
Lower Left  (   92000.000, 6618000.000) ( 19d47' 3.33"E, 59d30' 2.89"N)
Upper Right (  116000.000, 6630000.000) ( 20d11' 0.37"E, 59d37'49.63"N)
Lower Right (  116000.000, 6618000.000) ( 20d12'18.51"E, 59d31'24.43"N)
Center      (  104000.000, 6624000.000) ( 19d59' 0.44"E, 59d33'56.78"N)
Band 1 Block=256x256 Type=Float32, ColorInterp=Gray
  Min=0.279 Max=0.283 
  Minimum=0.279, Maximum=0.283, Mean=0.280, StdDev=0.001
  Checksum=27156
  NoData Value=-9999
  Metadata:
    STATISTICS_MAXIMUM=0.28299999237061
    STATISTICS_MEAN=0.2801427502868
    STATISTICS_MINIMUM=0.2790000140667
    STATISTICS_STDDEV=0.00093469689660237
    STATISTICS_VALID_PERCENT=34.96

Then using file as direct input works ok
**$ /Applications/QGIS.app/Contents/MacOS/bin/gdalbuildvrt -resolution average -r nearest /Users/m/GIS/vinovalovarjoste.vrt /Users/m/GIS/korkeusmalli-hila_10m/etrs-tm35fin-n2000/K2/K24/K2433.tif** 
0...10...20...30...40...50...60...70...80...90...100 - done.

Using -input_file_list does not work
**$ /Applications/QGIS.app/Contents/MacOS/bin/gdalbuildvrt -resolution average -r nearest -input_file_list /Users/m/GIS/vinovalovarjoste-input-list-manual.txt /Users/m/GIS/vinovalovarjoste.vrt**
0...10...20...30...40...50...60...70...80...90...100 - done.
ERROR 4: /Users/m/GIS/korkeusmalli-hila_10m/etrs-tm35fin-n2000/K2/K24/K2433.tif : No such file or directory
Warning 1: Can't open /Users/m/GIS/korkeusmalli-hila_10m/etrs-tm35fin-n2000/K2/K24/K2433.tif . Skipping it

**Comment by frspp** [comment]
Tried giving the files, folder and parent folders read & write access for everyone (default only read), did not help.
Tried granting Terminal.app "Full Disk Access" in system settings > Privacy, did not help.

**Comment by jratike80** [comment]
It feels like buildvrt is scanning the files two times and in my 2 m DEM test the second round took longer than the first round. I do not know what happens after the progress indicator has reached `- done`.  

Do you get lines like these on screen if you run your buildvrt command with `--debug on`?

```
GDAL: GDALOpen(Z:\korkeusmalli\hila_10m\etrs-tm35fin-n2000\X5\X51\X5134.tif, this=000002604AC59CB0) succeeds as GTiff.
OSR: TOWGS84 information has been removed. It can be kept by setting the OSR_STRIP_TOWGS84 configuration option to NO
GDAL: GDALClose(Z:\korkeusmalli\hila_10m\etrs-tm35fin-n2000\X5\X51\X5134.tif, this=000002604AC59CB0)
```

**Comment by frspp** [comment]
```
$ /Applications/QGIS.app/Contents/MacOS/bin/gdalbuildvrt -resolution average -r nearest --debug -input_file_list /Users/m/GIS/vinovalovarjoste-input-list-westernmac.txt /Users/m/GIS/vinovalovarjoste.vrt 
0...10...20...30...40...50...60...70...80...90...100 - done.
```

with --debug gives no error. .vrt file appeared in the folder. I deleted it and retried right again. Now same command gives

```
$ /Applications/QGIS.app/Contents/MacOS/bin/gdalbuildvrt -resolution average -r nearest --debug -input_file_list /Users/m/GIS/vinovalovarjoste-input-list-westernmac.txt /Users/m/GIS/vinovalovarjoste.vrt
0...10...20...30...40...50...60...70...80...90...100 - done.
ERROR 4: `/Users/m/GIS/vinovalovarjoste.vrt' not recognized as a supported file format.
Warning 1: Can't open /Users/m/GIS/vinovalovarjoste.vrt. Skipping it
```

This is mysterious.

**Comment by jratike80** [comment]
The right syntax is literally `--debug on`. 

Sometimes character sets can make this kind of odd behavior. The most suspicious character in your path is the dash "-". There are quite many characters in UTF-8 that look like a dash but are something else. I would write a input file list with just two lines by hand from the keyboard. If you have imported your list from some other place the dashes may have changed. This is a blind shot but it has happened to me even with dashes but more often with double quotes.

**Comment by frspp** [comment]
```
 % /Applications/QGIS.app/Contents/MacOS/bin/gdalbuildvrt -input_file_list /Users/m/GIS/vinovalovarjoste-input-list-spaces4.txt /Users/m/GIS/vinovalovarjoste.vrt
0...10...20...30...40...50...60...70...80...90...100 - done.
```
on my setup this command actually makes change to .txt file, not to .vrt file.

**Comment by jratike80** [comment]
Order of parameters do not make any difference for me. The result is identical and good also with 

`gdalbuildvrt -resolution average -r nearest -input_file_list files10m.txt vinovalovarjoste_other_order.vrt --debug on`

**Comment by frspp** [comment]
This system crazy. For a while terminal did not autocompleted folders but not filename. Then little later it did. 

Now I remade input list manually in texteditor and buildvrt ran fine.

I need to remake full input list with script and continue testing.

**Comment by frspp** [comment]
Redid everything. 

Some files are missing but I quess those are corrupted or such, even if I can view them on file browser.
