### ISSUE TITLE
building GDAL with MSVC 2017

### ISSUE THREAD

**Issue by jbensabat** [OSGeo/gdal#3394]
Hello 
I am using the batch files in the GDAL distribution to build GDAL 
the project file that is created does not compile and or build the lib
any help and or experience sharing would be welcome
best
jac

## Expected behavior and actual behavior.

For example (please modify !!!): I expected to be able to open this raster file (with a link to
the raster file, or it as an attachment) and it returns an error message
instead.

## Steps to reproduce the problem.

For example (please modify !!!): "gdalinfo myfile"

## Operating system

For example (please modify !!!): Ubuntu 16.04 64 bit

## GDAL version and provenance

For example (please modify !!!): the 2.2.3 version from ubuntugis-unstable PPA

**Comment by mloskot** [comment]
Building GDAL with MSVC 2017 on Ubuntu 16.04?

**Comment by jbensabat** [comment]
on windows 10 / 64

**Comment by mloskot** [comment]
Use NMAKE files as they are yhe official build configuration and they work, see the CI builds on Windows.
