### ISSUE TITLE
ModuleNotFoundError: No module named 'osr'

### ISSUE THREAD

**Issue by TejaishwaryaGagadam** [OSGeo/gdal#3397]
I downloaded GDAL's latest version 3.2.1. 

```
import gdal
```

works just fine. However, I am unable to 
```
import osr
```

I want to use osr for SpatialReference().

**Comment by msmitherdc** [comment]
Please do not use the bug tracker for questions. Use the mailing list. 
Release notes state
``` 
- Python bindings: old-style "import gdal" is no longer available. Use "from osgeo import gdal" instead
```
Use `from osgeo import osr`
