### ISSUE TITLE
Implement raster support for GDB

### ISSUE THREAD

**Issue by roya0045** [OSGeo/gdal#3406]
Request and work towards GDB raster support seems to have been fluctuating in time.

To this effect I thought that having an open enhancement request might help.

I have read about some preliminary work towards this and knowing the status and ways forward might help me or anyone more competent to progress towards this goal.

**Comment by jratike80** [comment]
If you have ESRI support contract you may ask your local support to pass on a wish to make the format open.

**Comment by roya0045** [comment]
@jratike80 I don't think ESRI is that kind of organisation. Though from what I can see many things are displayed pretty clearly in some tables when it comes to raster layer. With the existing driver elements this should be a good first step, also Even said some preliminary work was done, if this work was available somewhere this may help potential contributors rather than starting from scratch. There was also a proposal on the closed tracker, unsure what became of that.

**Comment by roya0045** [comment]
Stumbled upon this https://github.com/r-barnes/ArcRasterRescue I'll look into it to see if I am comfortable to do anything.

**Comment by rouault** [comment]
See https://github.com/qgis/QGIS-Enhancement-Proposals/issues/173 (proposed for QGIS 2020 grant proposal, but not selected). There might be a funding source available in some undefined future to implement this.

**Comment by roya0045** [comment]
@rouault I forgot about that, but I think new features are not eligible for qgis grants, I'm not sure if this would be considered as a new feature or an improvement, its skirting the line, though fundraiser may be a viable option. Either way if you can get paid to implement this I won't look too hard into it as you are bound to do better work on this than I can hope to.

**Comment by roya0045** [comment]
I'll look into refactoring arcrasterrescue to be more compatible with gdal, as it seems to be the most complete solution.  I can't make too many promises as I'm out of my league but hopefully it'll be usable. I'm not too sure how to handle the container/tables aspect of the format.

**Comment by MichiHo** [comment]
Just as a note for anyone stumbling upon this issue: GDB raster support has been added as of GDAL 3.7.
