### ISSUE TITLE
RuntimeError: E:\test\20190918_L1A1119926317-1.tif, band 1: IReadBlock failed at X offset 0, Y offset 0: _TIFFPartialReadStripArray:Invalid type for [Strip|Tile][Offset/ByteCount] tag

### ISSUE THREAD

**Issue by wantaoliu** [OSGeo/gdal#3409]
## Expected behavior and actual behavior.

# gdal读取tif得到的数组顺序为：channels，行，列
def readTif(src, opentype=None):
    dataset = gdal.Open(src)
    if dataset == None:
        print(src + "文件无法打开")
    im_width = dataset.RasterXSize  # 栅格矩阵的列数
    im_height = dataset.RasterYSize  # 栅格矩阵的行数
    im_bands = dataset.RasterCount  # 波段数
    im_geotrans = dataset.GetGeoTransform()  # 获取仿射矩阵信息
    im_pro = dataset.GetProjection()
    im_data = dataset.ReadAsArray(0, 0, im_width, im_height)  # 获取数据
    return im_data, im_width, im_height, im_bands, im_geotrans, im_pro

img, im_width, im_height, img_bands, im_geotrans, im_pro = readTif(path)
## Steps to reproduce the problem.

Warning 1: TIFFFetchNormalTag:ASCII value for tag "GeoASCIIParams" contains null byte in value; value incorrectly truncated during reading due to implementation limitations
Warning 1: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
Traceback (most recent call last):
  File "D:\SoftWare\AnacondaNew\envs\GF6\lib\site-packages\IPython\core\interactiveshell.py", line 3291, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-61fea1466c15>", line 1, in <module>
    runfile('D:/segmentation_models-master/segmentation_models-master/water_Extraction.py', wdir='D:/segmentation_models-master/segmentation_models-master')
  File "D:\SoftWare\PyCharm Community Edition 2020.2.1\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "D:\SoftWare\PyCharm Community Edition 2020.2.1\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/segmentation_models-master/segmentation_models-master/water_Extraction.py", line 84, in <module>
    img, im_width, im_height, img_bands, im_geotrans, im_pro = readTif(x)
  File "D:\segmentation_models-master\segmentation_models-master\myprepressduoboduan.py", line 614, in readTif
    im_data = dataset.ReadAsArray(0, 0, im_width, im_height)  # 获取数据
  File "D:\SoftWare\AnacondaNew\envs\GF6\lib\site-packages\osgeo\gdal.py", line 2333, in ReadAsArray
    interleave=interleave )
  File "D:\SoftWare\AnacondaNew\envs\GF6\lib\site-packages\osgeo\gdal_array.py", line 349, in DatasetReadAsArray
    _RaiseException()
  File "D:\SoftWare\AnacondaNew\envs\GF6\lib\site-packages\osgeo\gdal_array.py", line 244, in _RaiseException
    raise RuntimeError(gdal.GetLastErrorMsg())
RuntimeError: E:\test\20190918_L1A1119926317-1.tif, band 1: IReadBlock failed at X offset 0, Y offset 0: _TIFFPartialReadStripArray:Invalid type for [Strip|Tile][Offset/ByteCount] tag

## Operating system

windows 10

## GDAL version and provenance

gdal :3.1.4

**Comment by jratike80** [comment]
The essential part of the error is this:

> RuntimeError: E:\test\20190918_L1A1119926317-1.tif, band 1: IReadBlock failed at X offset 0, Y offset 0: _TIFFPartialReadStripArray:Invalid type for [Strip|Tile][Offset/ByteCount] tag

It the value of `Invalid type for [Strip|Tile][Offset/ByteCount] tag` is invalid then the error is in the data, not in GDAL. Can you share the image `E:\test\20190918_L1A1119926317-1.tif`? Does gdalinfo report anything special? Can you convert the image with gdal_translate `gdal_translate -of GTiff E:\test\20190918_L1A1119926317-1.tif test.tif`?

**Comment by jratike80** [comment]
We need your feedback.

**Comment by zhongzisha** [comment]
Hi @jratike80 , I have met the same problem of `_TIFFPartialReadStripArray:Invalid type for [Strip|Tile][Offset/ByteCount] tag` using my own compiled `gdal-3.2.1` from source. And after converting the original tif using the command `gdal_translate -of GTiff src.tif src_converted.tif` you provided. The error is gone. 

But using the system gdal library (installed by `sudo apt-get install libgdal-dev` etc.), there is no problem in either `src.tif` or `src_converted.tif`.

So I doubt that the compiled gdal library might not be complete, so it cannot handle the `src.tif`. The system is `Ubuntu 20.04 64bit`. 

Hope this helpful. Thank you!

**Comment by rouault** [comment]
> So I doubt that the compiled gdal library might not be complete, so it cannot handle the `src.ti`

Please attach a file to reproduce the issue. When you build yourself GDAL, it uses its own copy of libtiff, which is more recent, and there have been changes in the area that triggers this error message that could have causes regressions

**Comment by zhongzisha** [comment]
Hi @rouault , thanks for your suggestion!

Please check the following screenshots:

[compile error for gdal-3.2.1 tools on Ubuntu 20.04](https://imgur.com/Qyq0x9O)
[compiled gdal library for gdal-3.2.1 on Ubuntu 20.04](https://imgur.com/ieKIGaW)
[tiff libraries installed on Ubuntu 20.04](https://imgur.com/av4GF4b)
[compiled gdal-python library on Ubuntu 20.04](https://imgur.com/VdqICz2)
[system tiff library on Ubuntu 20.04](https://imgur.com/J0btfJs)

The gdal library can be compiled successfully and the gdal-python library can be compiled successfully. And I've tested the python library. But the gdal tools cannot be compiled successfully, as shown in the above pictures.

I also compiled the `gdal-3.2.1` from the source on Windows 10. The `proj-7.2.1` and `tiff-4.2.0` are also compiled from source. And there is no problem with the `src.tif` using the `gdal.Open('src.tif')`.

[compiled gdal-python library on Windows 10](https://imgur.com/tEqtc3z)
[compiled gdal library on Windows 10](https://imgur.com/4UycUx5)

So I think the problem may lie in the tiff library in the Ubuntu 20.04 system.

**Comment by rouault** [comment]
It might be that the tiff version in 20.04 has not this fix: https://gitlab.com/libtiff/libtiff/commit/3db0ff91bc6db20fc4cb035be366a9bbb4e701cf , but it might be something else

Could you at least put here the output of "tiffdump src.tif" if you cannot attach it or provide a link to it ? It is not fun for us to guess without appropriate diagnosis.

**Comment by zhongzisha** [comment]
@rouault , please check the following outputs for the `src.tif` and `src_converted.tif`:

    src.tif:
    Magic: 0x4949 <little-endian> Version: 0x2b <BigTIFF>
    OffsetSize: 0x8 Unused: 0
    Directory 0: offset 6375569084 (0x17c0376bc) next 0 (0)
    SubFileType (254) SLONG (9) 1<0>
    ImageWidth (256) SLONG (9) 1<19087>
    ImageLength (257) SLONG (9) 1<111249>
    BitsPerSample (258) SSHORT (8) 3<8 8 8>
    Compression (259) SSHORT (8) 1<1>
    Photometric (262) SSHORT (8) 1<2>
    StripOffsets (273) LONG8 (16) 333747<2669992 2689079 2708166 2727253 2746340 2765427 2784514 2803601 2822688 2841775 2860862 2879949 2899036 2918123 2937210 2956297 2975384 2994471 3013558 3032645 3051732 3070819 3089906 3108993 ...>
    Orientation (274) SSHORT (8) 1<1>
    SamplesPerPixel (277) SSHORT (8) 1<3>
    RowsPerStrip (278) SLONG (9) 1<1>
    StripByteCounts (279) SLONG8 (17) 333747<19087 19087 19087 19087 19087 19087 19087 19087 19087 19087 19087 19087 19087 19087 19087 19087 19087 19087 19087 19087 19087 19087 19087 19087 ...>
    XResolution (282) RATIONAL (5) 1<1>
    YResolution (283) RATIONAL (5) 1<1>
    PlanarConfig (284) SSHORT (8) 1<2>
    33550 (0x830e) DOUBLE (12) 3<0.06981 0.06981 0>
    33922 (0x8482) DOUBLE (12) 6<0 0 0 557913 2.58232e+06 0>
    34735 (0x87af) SSHORT (8) 24<1 1 0 5 1024 0 1 1 1025 0 1 1 2052 0 1 9001 2054 0 1 9102 3072 0 1 32649>
    34737 (0x87b1) ASCII (2) 7<\265v\003|\001\0\0>


    src_converted.tif:
    Magic: 0x4949 <little-endian> Version: 0x2b <BigTIFF>
    OffsetSize: 0x8 Unused: 0
    Directory 0: offset 16 (0x10) next 0 (0)
    ImageWidth (256) SHORT (3) 1<19087>
    ImageLength (257) LONG (4) 1<111249>
    BitsPerSample (258) SHORT (3) 3<8 8 8>
    Compression (259) SHORT (3) 1<1>
    Photometric (262) SHORT (3) 1<2>
    StripOffsets (273) LONG8 (16) 111249<6362008474 6362065735 6362122996 6362180257 6362237518 6362294779 6362352040 6362409301 6362466562 6362523823 6362581084 6362638345 6362695606 6362752867 6362810128 6362867389 6362924650 6362981911 6363039172 6363096433 6363153694 6363210955 6363268216 6363325477 ...>
    SamplesPerPixel (277) SHORT (3) 1<3>
    RowsPerStrip (278) SHORT (3) 1<1>
    StripByteCounts (279) SHORT (3) 111249<57261 57261 57261 57261 57261 57261 57261 57261 57261 57261 57261 57261 57261 57261 57261 57261 57261 57261 57261 57261 57261 57261 57261 57261 ...>
    XResolution (282) RATIONAL (5) 1<1>
    YResolution (283) RATIONAL (5) 1<1>
    PlanarConfig (284) SHORT (3) 1<1>
    SampleFormat (339) SHORT (3) 3<1 1 1>
    33550 (0x830e) DOUBLE (12) 3<0.06981 0.06981 0>
    33922 (0x8482) DOUBLE (12) 6<0 0 0 557913 2.58232e+06 0>
    34735 (0x87af) SHORT (3) 32<1 1 0 7 1024 0 1 1 1025 0 1 1 1026 34737 22 0 2049 34737 7 22 2054 0 1 9102 ...>
    34737 (0x87b1) ASCII (2) 30<WGS 84 / UTM zone 49N|WG ...>

**Comment by zhongzisha** [comment]
Hi @rouault , confirmed that the problem is related to the tiff library. Like on the Windows 10, I compiled the `tiff-4.2.0` from source on Ubuntu 20.04 and using it to compile the `gdal-3.2.1` form source, then all errors are gone. 

After compiled the `tiff-4.2.0` library, some details are as follows:

    cd gdal-3.2.1
    ./configure --with-python --prefix=`pwd`/install --with-tiff=/media/ubuntu/Data/tiff-4.2.0/install/ --enable-shared --enable-static --with-pic
    export LD_LIBRARY_PATH=/media/ubuntu/Data/tiff-4.2.0/install/lib:/media/ubuntu/Working/anaconda3/lib/:$LD_LIBRARY_PATH
    make -j8
    make install

The third line is important for using the compiled tiff library and using the `krb5.so` in the anaconda environment. Or it is possible that there are some `undefined references` errors when compiling the gdal. 

After that, all the gdal related things (`libgdal.so`, gdal tools, gdal-python bindings, etc.) will be compiled successfully.

When using the gdal-python, we should first do the following:

    export LD_LIBRARY_PATH=/media/ubuntu/Data/gdal-3.2.1/install/lib:/media/ubuntu/Data/tiff-4.2.0/install/lib:/media/ubuntu/Working/anaconda3/lib/:$LD_LIBRARY_PATH
    export PYTHONPATH=/media/ubuntu/Data/gdal-3.2.1/install/lib/python3.8/site-packages/:$PYTHONPATH

Then, both the `src.tif` and `src_converted.tif` can be loaded correctly. It was OK by now, not sure if this will produce other errors.

**Comment by rouault** [comment]
> StripByteCounts (279) SLONG8 (17) 333747<19087 19087 19087 19087 19087 19087 19087 19087 19087 19087 19087 19087 19087 19087 19087 19087 19087 19087 19087 19087 19087 19087 19087 19087 ...>

OK, so my guess was correct. StripByteCounts array of type SLONG8 that was fixed per https://gitlab.com/libtiff/libtiff/commit/3db0ff91bc6db20fc4cb035be366a9bbb4e701cf that went into libtiff 4.2.

So bug fixed

**Comment by zhongzisha** [comment]
@rouault Great, thank you!

**Comment by wantaoliu** [comment]
if we  use GDAL=3.3.3,it is ok!
