### ISSUE TITLE
Python gdal.Rasterize fails if result not saved to variable

### ISSUE THREAD

**Issue by viktor76525** [OSGeo/gdal#3410]
## Expected behavior and actual behavior.

I was trying to burn in a shapefile attribute and instead got a black GTiff (0s). If I set a burn value instead, the value was some large/small float in QGIS even though the datatype was `GDT_Byte`.

Even if this was expected behaviour, I spent an afternoon without making progress because I was trying different parameters and sometimes it seemed to have worked (accidentally pasted the variable to save to) so very confusing. So I think there should at least be an Error message if this can't be fixed to notify the user that you need to store in the variable. Didn't notice any comment in the source code and didn't find documentation online.

## Steps to reproduce the problem.
instead of 
```
ds = gdal.Rasterize(...
ds = None
```
do:
```
gdal.Rasterize(...
```

## Operating system
Gentoo x86_64

## GDAL version and provenance
gdal-3.0.4-r1 from gentoo repo
gdal-3.2.1 from gentoo repo

**Comment by jratike80** [comment]
Sorry but I do not understand your description. Could you add complete code for re-producing your issue with some test data?

You can find usage examples from https://github.com/OSGeo/gdal/blob/master/autotest/utilities/test_gdal_rasterize_lib.py.
Documentation of the Python script version gdal_rasterize.py https://gdal.org/programs/gdal_rasterize.html should be useful.
Python API is documented in https://gdal.org/python/osgeo.gdal-module.html#Rasterize.

BTW questions should be sent to the mailing list as we inform in https://github.com/OSGeo/gdal/issues/new.

**Comment by viktor76525** [comment]
The second call to Rasterize will fail below. But now I notice that it is only while Python remains open. If you paste the code into the Python shell, `works.tif` will be usable, `broken.tif` won't be untill you close the Python shell.

```python
from osgeo import gdal

shapefile = "sample/sample.shp"

ds = gdal.Rasterize("works.tif",
                    shapefile,
                    creationOptions=["COMPRESS=DEFLATE"],
                    outputBounds=[1511409, 6217416, 1523331, 6223139],
                    xRes=100,
                    yRes=100,
                    noData=255,
                    targetAlignedPixels=True,
                    attribute="gid",
                    outputType=gdal.GDT_Byte)
ds = None

gdal.Rasterize("broken.tif",
               shapefile,
               creationOptions=["COMPRESS=DEFLATE"],
               outputBounds=[1511409, 6217416, 1523331, 6223139],
               xRes=100,
               yRes=100,
               noData=255,
               targetAlignedPixels=False,
               attribute="gid",
               outputType=gdal.GDT_Byte)
```
               

[sample.zip](https://github.com/OSGeo/gdal/files/5869908/sample.zip)

**Comment by jratike80** [comment]
Writing the actual data into file is triggered reliably only by closing the dataset https://gdal.org/api/python_gotchas.html#saving-and-closing-datasets-datasources. It is expected behavior and use of "ds = None" is documented in the link above, in https://pcjericks.github.io/py-gdalogr-cookbook/raster_layers.html#close-a-raster-dataset, and in Python examples that you can find from the net.

**Comment by viktor76525** [comment]
ok
