### ISSUE TITLE
-limit option for ogrinfo

### ISSUE THREAD

**Issue by StefanBrand** [OSGeo/gdal#3413]
## Expected behavior and actual behavior.

`ogr2ogr` has a [`-limit` option](ghttps://gdal.org/programs/ogr2ogr.html#cmdoption-ogr2ogr-limit). I couldn't find this option for `ogrinfo`, while `ogrinfo` has e.g. `-where`.

## Steps to reproduce the problem.

`ogrinfo -limit 10 file.gpkg -al`

## Operating system

Ubuntu 20.04 64 bit

## GDAL version and provenance

GDAL 3.0.4, released 2020/01/28, http://at.archive.ubuntu.com/ubuntu focal/universe amd64 Packages

**Comment by jratike80** [comment]
For each layer you can run

`ogrinfo -sql "select * from layer limit 10" file.gpkg`

**Comment by StefanBrand** [comment]
I would like to use the same simplicity like with the `-where` flag, e.g. neither specify `select *` nor `from layer`.

**Comment by jratike80** [comment]
I agree that it is not especially simple. Would you use that option often, so to read 10 features from all the layers of your datastore?

Another workaround could be write and keep available a skript that does

```
ogr2ogr -f gpkg temp.gpkp %input_here% -limit 10
ogrinfo temp.gpkg -al
del temp.gpkg

```

**Comment by StefanBrand** [comment]
Actually, I use it to look at actual values of a layer. `-so` only gives the column names and column types, and simply `ogrinfo` spams the terminal if you are doing it on a file with 2.5 mio features.

Thinking about it, what would actually be useful, is an enhanced `ogrinfo -so` that gives some sample values for each column, similar to what the representation of an `xarray.DataArray` looks like: 

![image](https://user-images.githubusercontent.com/8948865/106754243-06e27d00-662d-11eb-93c6-2cbbbaf996d2.png)

**Comment by jratike80** [comment]
What I do is to hit Ctrl-C to stop the spam. And if geometries are large linestrings or polygons they build up spam as well which makes ogrinfo not optimal tool for having a quick look at the data.

I personally use spatialite-gui and DB Browser for SQLite for having a look at geopackage data. And I think that using temporary geopackage `ogr2ogr -f gpkg temp.gpkp %input_here% -limit 10` was not too bad idea either.

I do not mean that your idea is worthless but I feel that actually you would not be satisfied by the -limit option of ogrinfo. You want something more that is some quick statistics tool. Try to meet some Python developer and  sell your idea.

About the sampling tool, QGIS can do that but only field by field with the Query builder. SQL is your friend for  min/max/average.

![image](https://user-images.githubusercontent.com/1751612/106757029-93466d00-6638-11eb-8439-4872b5f46f67.png)

**Comment by StefanBrand** [comment]
Sorry, my screenshot was just an illustration. I am not interested in any statistics.
___

I'm working inside a JupyterLab and there is no way to start any GUI applications. There are only a Terminal, iPython console and Jupyter notebooks. Besides, Ctrl+C often is not carried out for a minute

I'm just trying out your snippet. It's pretty fast on a GPKG, but takes ages for GeoJSON. GeoJSON is a primitive format and fetching 10 entries should not take long. (Simply doing `head file.geojson` does not work if the file has all its contents on one line.)

**Comment by jratike80** [comment]
How about `ogrinfo -al gigantic.json|more` ?

**Comment by StefanBrand** [comment]
Maybe it's a bad example, but I must use GeoJSON because Django does not support any other format for serializing PostGIS table contents... :grimacing: 

`-nocount -noextent -nogeomtype`: These don't work together with your original proposal using `ogr2ogr`, right? :thinking: Unfortunately, cannot test `ogrinfo -nogeomtype` at the moment, since I'm still on GDAL 3.0.4...

**Comment by StefanBrand** [comment]
For GeoJSON this sort of works (adjust `-c` to your needs):

```
head -c 1000 HPG_2019_simplified.geojson
```
prints: 

```
{
"type": "FeatureCollection",
"name": "HPG_2019_simplified",
"crs": {
"properties": {"name": "EPSG:31287"}, "type": "name"
},
"features": [
{ "type": "Feature", "properties": { "ID": "1", "NAME": "Hochalpen" }, "geometry": { "type": "MultiPolygon", "coordinates": [ [ [ [ 183502.200000002980232, 410278.980000000447035 ], [ 183184.21000000089407, 410241.309999998658895 ], [ 182856.229999996721745, 411575.989999998360872 ], [ 182187.340000003576279, 411651.309999998658895 ], [ 181957.79, 411868.420000001788139 ], [ 181877.96000000089407, 412190.29 ], [ 182004.369999997317791, 412222.199999999254942 ], [ 181681.71000000089407, 412771.949999999254942 ], [ 182168.920000001788139, 412954.219999998807907 ], [ 181993.840000003576279, 413202.21000000089407 ], [ 182310.929999999701977, 413482.019999999552965 ], [ 183716.969999998807907, 413258.309999998658895 ], [ 184776.369999997317791, 413716.649999998509884 ], [ 184979.799999997019768, 413687.149999998509884 ], [ 184990.759999997913837, 41343
```

**Comment by jratike80** [comment]
This would have been a wonderful discussion topic on the mailing list or as a question in gis.stackexchange.  As a bug report/feature request in GitHub the other GDAL users do see the discussion and do not learn from it.

I believe that you have discovered a better solution than what `ogrinfo -limit` would have been.

**Comment by StefanBrand** [comment]
Unfortunately my solution for GeoJSON cannot be generalized to GPKG or any other file that OGR reads. 

I have started a gis.SE question for GeoJSON here: https://gis.stackexchange.com/questions/386331/one-liner-to-print-first-feature-from-geojson/386332#386332

I have also started one for GPKG and you can post your answer there if you want: https://gis.stackexchange.com/questions/386333/one-liner-to-print-first-feature-from-gpkg

**Comment by jratike80** [comment]
I repeat my very first comment, here as generalized to work for any OGR source.

`ogrinfo -dialect SQLite -sql "select * from layer limit 1" any_datasource`

Yes, it requires that user writes a bit longer text than `-limit` and that they check the name of the layer. However, I believe that it is worth the pain to learn to use it. The `-limit` option would have very limited space somewhere between `-al -so` and full featured `-sql`. Hmm, what values there may appear in a certain attribute, wait a second and check.

`ogrinfo -sql "select distinct(attribute) from myshapefile order by attribute" myshapefile.shp`
