### ISSUE TITLE
Compile error on gcc 4.9.3

### ISSUE THREAD

**Issue by jeroen** [OSGeo/gdal#3414]
Hello! I have been asked to update the GDAL binaries for the R programming language. We have 2 toolchains, the current gcc 8.3.0 and the legacy gcc 4.9.3 toolchain. On the current toolchain everything works 💯 . However on gcc 4.9.3 we see:

```
In file included from ogr_elastic.h:33:0,
                  from ogrelasticlayer.cpp:30:
 D:/a/rtools-backports/rtools-backports/mingw-w64-gdal/src/build-i686-w64-mingw32/ogr/ogrsf_frmts/ogrsf_frmts.h: In lambda function:
 D:/a/rtools-backports/rtools-backports/mingw-w64-gdal/src/build-i686-w64-mingw32/ogr/ogrsf_frmts/ogrsf_frmts.h:109:18: error: 'OGRErr OGRLayer::GetExtentInternal(int, OGREnvelope*, int)' is protected
      OGRErr       GetExtentInternal(int iGeomField, OGREnvelope *psExtent, int bForce );
                   ^
 ogrelasticlayer.cpp:3513:83: error: within this context
          const auto eRet = OGRLayer::GetExtentInternal(iGeomField, psExtent, bForce);
                                                                                    ^
 make[3]: *** [../../../GDALmake.opt:646: ../o/ogrelasticlayer.lo] Error 1
 make[3]: Leaving directory '/d/a/rtools-backports/rtools-backports/mingw-w64-gdal/src/build-i686-w64-mingw32/ogr/ogrsf_frmts/elastic'
 make[2]: *** [../../GDALmake.opt:659: elastic-target] Error 2
```

This is probably a [bug in gcc](https://stackoverflow.com/a/31389692/318752). I know gcc 4.9.3 is old, but we need to support this until April 2021. Would you maybe suggest a patch or workaround so that we can make this build?

Looks like the problem was introduced by this commit from @rouault last november: https://github.com/OSGeo/gdal/commit/89906207f6212d45adbca88378c748f37262aa67

Full log is here: https://github.com/r-windows/rtools-backports/pull/37

**Comment by jeroen** [comment]
@rouault We have some environmental govt R users who would really like to use the new GDAL, but this issue is preventing me from updating the R binaries. Would you have any suggestion? Thank you!

**Comment by hobu** [comment]
It's a seven year old compiler.

Just disable the elastic driver and recompile given that you are self compiling anyway.

**Comment by rouault** [comment]
@jeroen Why are you using a sad smiley ? You got an effective answer that solved your issue in less than 2 business days. That's a level of support worth of several thousands of dollars per month.

**Comment by rouault** [comment]
Proprietary software is also a good alternative. You don't have to go in the hassle of building yourself the software. Government users should really avoid using unsupported open source software done by hobbyists

**Comment by dbaston** [comment]
@jeroen Looks like it was [fixed](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=66957) in 4.9.4 if you have the option of updating RTools35.

**Comment by sgillies** [comment]
Also a duplicate of #3374.
