### ISSUE TITLE
[Enhancement] Gdal Vector Warp

### ISSUE THREAD

**Issue by roya0045** [OSGeo/gdal#3426]
Greetings,

I would like to suggest having a version of gdalwarp that would work on vector data.

I had a look at some of the code and I think this proposal would be doable if my understanding of the code is good, more of the current base (kernel, transforms, etc) could be reused and applied to the coordinates of geometries instead of pixels. 

I someone has pointers or is more familiar with that part of the codebase let me know if this seems realistic.

**Comment by jratike80** [comment]
Ogr2ogr https://gdal.org/programs/ogr2ogr.html when `-s_srs` is different from `-t_srs` converts vector data from one coordinate system into another. With the `-gcp` option it is possible to add ground control points into non-georeferenced data. Options `-order` and `-tps` are connected to -gcp option.

Please have a look and consider if ogr2ogr could do what you want to do.

**Comment by roya0045** [comment]
@jratike80 Thanks a ton! I have completely overlooked this! I'll give it a try and if sufficient I'll close this ticket.

**Comment by roya0045** [comment]
@jratike80 Did some tests, seems pretty much what I needed, It should be fairly adapt to QGIS. Thanks again for the help!
