### ISSUE TITLE
GDALWarp command usage

### ISSUE THREAD

**Issue by kunalkhosla93** [OSGeo/gdal#3429]
Version of GDAL:GDAL 3.1.3
MSVisual Studio: 2019
I tried to build a small programme in C++ to generate gcps and then use gdaltranslate followed by gdalwarp in python(as in QGIS).
The GDALTransalte () function works well, but i am unable to use GDALWarp correctly. I am new to GDAL and wanted to get the programme to georeference a unreferenced image using gcp.
The QGIS generate gdal script in python is shown below: 
gdal_translate -of GTiff -gcp 423.808 490.151 x y -gcp 600.421 202.41 x1 y1 -gcp 1074.7 204.395 x2 y2 "1.jpg" "1.jpg"
gdalwarp -r cubicspline -tps -co COMPRESS=NONE  -t_srs EPSG:3857 "1.jpg" "1_modified.tif"
But I want to do it in C++. Any help will be greatly appreciated.
The error occurs when I run the GDALWarp command and it takes me to gdalrasterband.cpp (line 1982,GetColorInterpretation).

Any help will be appreciated.

**Comment by mloskot** [comment]
1. There is mailing list to post questions about GDAL usage
2. RTFM! https://gdal.org/tutorials/warp_tut.html
3. Read source code of the `gdalwarp` apps.
