### ISSUE TITLE
feature: mbtiles webp image support

### ISSUE THREAD

**Issue by eddy-geek** [OSGeo/gdal#3437]
MBTiles supports WebP since 1.3 : [mbutil](https://github.com/mapbox/mbutil) supports it, and the [spec](https://github.com/mapbox/mbtiles-spec/blob/master/1.3/spec.md) says:

> format (string): The file format of the tile data: pbf, jpg, png, webp, or an IETF media type for other formats.

But as of latest Gdal 3.2, it is not possible to use WebP with MBTiles, but is it supported [elsewhere](https://gdal.org/drivers/raster/webp.html) since 1.9 (eg [geotiff](https://gdal.org/drivers/raster/gtiff.html?highlight=webp) or the similar [rasterlite](https://gdal.org/drivers/raster/rasterlite.html) can write WebP). [Gdal MBTiles doc](https://gdal.org/drivers/raster/mbtiles.html) says:

> TILE_FORMAT=PNG/PNG8/JPEG: Format used to store tiles.

And this is indeed the case in [mbtilesdataset.cpp](https://github.com/OSGeo/gdal/blob/e984e8fba5b45396cfe0e8872911a2d894ca7429/gdal/frmts/mbtiles/mbtilesdataset.cpp).

Would it be possible to add WebP as it can reduce file size by 30%?

**Comment by DavidDohmen** [comment]
+1 this would very much appreciated! We also need this feature!
