### ISSUE TITLE
Cannot Load DEM defined in UTM zone 19 Southern Hemisphere

### ISSUE THREAD

**Issue by kavindergupta** [OSGeo/gdal#344]
There is a bug in the latest version of GDAL 2.2.3 that when we trying to load a DEM whose UTM zone is defined as "-19" (UTM zone 19 Southern Hemisphere). GDAL throws "Invalid Zone -19" exception. However, in the earlier version GDAL201, I was able to load the same DEM perfectly. There is a bug which recently introduced.

The DEM should load perfectly in the UTM zone 19 Southern Hemisphere as it was loading.

## Steps to reproduce the problem.

GDAL.Open(DEMFIle) and it throws the "Invalid Zone -19" exception.

## Operating system

Windows 10 x64

## GDAL version and provenance

GDAL version 2.2.3 version

**Comment by rouault** [comment]
Can you provide a link to the dataset ? Otherwise it is impossible to analyze and fix

**Comment by kavindergupta** [comment]
[TopoQ2.zip](https://github.com/OSGeo/gdal/files/1870561/TopoQ2.zip)
