### ISSUE TITLE
Python standard type aliases are deprecated in NumPy 1.20

### ISSUE THREAD

**Issue by QuLogic** [OSGeo/gdal#3444]
## Expected behavior and actual behavior.

NumPy's aliases for standard Python types are deprecated, and generate some warnings when running tests:

```
  /usr/lib64/python3.9/site-packages/osgeo/gdal_array.py:555: DeprecationWarning: Converting `np.character` to a dtype is deprecated. The current result is `np.dtype(np.str_)` which is not strictly correct. Note that `np.character` is generally deprecated and 'S1' should be used.
    array = array.astype(numpy.character)
gcore/hfa_rfc40.py::test_hfa_rfc40_2
gcore/hfa_rfc40.py::test_hfa_rfc40_4
gcore/hfa_rfc40.py::test_hfa_rfc40_6
gcore/hfa_rfc40.py::test_hfa_rfc40_9
  .../gdalautotest-3.2.1/gcore/hfa_rfc40.py:193: DeprecationWarning: Converting `np.character` to a dtype is deprecated. The current result is `np.dtype(np.str_)` which is not strictly correct. Note that `np.character` is generally deprecated and 'S1' should be used.
    if not (data == STRING_DATA.astype(numpy.character)).all():
gcore/hfa_rfc40.py::test_hfa_rfc40_2
gcore/hfa_rfc40.py::test_hfa_rfc40_4
gcore/hfa_rfc40.py::test_hfa_rfc40_6
gcore/hfa_rfc40.py::test_hfa_rfc40_9
  .../gdalautotest-3.2.1/gcore/hfa_rfc40.py:201: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    if not (data == STRING_DATA_INTS.astype(numpy.int)).all():
gcore/hfa_rfc40.py::test_hfa_rfc40_2
gcore/hfa_rfc40.py::test_hfa_rfc40_4
gcore/hfa_rfc40.py::test_hfa_rfc40_6
gcore/hfa_rfc40.py::test_hfa_rfc40_9
  .../gdalautotest-3.2.1/gcore/hfa_rfc40.py:213: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    if not (data.astype(numpy.int) == INT_DATA).all():
gcore/hfa_rfc40.py::test_hfa_rfc40_7
  .../gdalautotest-3.2.1/gcore/hfa_rfc40.py:304: DeprecationWarning: Converting `np.character` to a dtype is deprecated. The current result is `np.dtype(np.str_)` which is not strictly correct. Note that `np.character` is generally deprecated and 'S1' should be used.
    if not (data == STRING_DATA.astype(numpy.character)).all():
gcore/hfa_rfc40.py::test_hfa_rfc40_10
  .../gdalautotest-3.2.1/gcore/hfa_rfc40.py:332: DeprecationWarning: Converting `np.character` to a dtype is deprecated. The current result is `np.dtype(np.str_)` which is not strictly correct. Note that `np.character` is generally deprecated and 'S1' should be used.
    if not (data == LONG_STRING_DATA.astype(numpy.character)).all():
gdrivers/memmultidim.py::test_mem_md_array_get_mask
  /usr/lib64/python3.9/site-packages/osgeo/gdal.py:3124: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```

See also the reference deprecation note: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

## Steps to reproduce the problem.

Run `autotest` with NumPy 1.20.

## Operating system

Fedora Rawhide (34)

## GDAL version and provenance

3.2.1, building package from source

**Comment by rcoup** [comment]
@idanmiara what did we decide the minimum numpy version is?

I know Numpy 1.20 drops Py3.6 support, so we need to support <1.20 for quite a while yet.

**Comment by idanmiara** [comment]
> @idanmiara what did we decide the minimum numpy version is?
> 
> I know Numpy 1.20 drops Py3.6 support, so we need to support <1.20 for quite a while yet.

I don't recall a conversation about a minimum `numpy` version, I think we just referenced [NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html) while dropping Python 2 support.

I use `numpy!=1.19.4` because `1.19.4` had a bug with windows.
I don't have a recommendation for a minimum version as I don't know which features of `numpy` are essential for our usecase.

**Comment by rcoup** [comment]
As we have [3.6 as the minimum supported Python version](https://gdal.org/development/rfc/rfc77_drop_python2_support.html) we need to support a NumPy that works with it (ie. 1.19+)

@QuLogic were these deprecations added with 1.20, or have they been there for a long time?

**Comment by idanmiara** [comment]
> As we have [3.6 as the minimum supported Python version](https://gdal.org/development/rfc/rfc77_drop_python2_support.html) we need to support a NumPy that works with it (ie. 1.19+)
> 
> @QuLogic were these deprecations added with 1.20, or have they been there for a long time?

[Numpy Toolchain Roadmap](https://docs.scipy.org/doc/scipy/reference/toolchain.html):
Python 3.6 support -> Numpy >= 1.14.5 and  Numpy <= 1.19.x

[NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html):
Numpy < 1.17 is deprecated since Jan 13, 2021.

Unless we actually use Numpy 1.19, I think we should set numpy minimum version to 1.17.

**Comment by QuLogic** [comment]
They were added in 1.20, though it says they were aliases for a long time.

**Comment by idanmiara** [comment]
> They were added in 1.20, though it says they were aliases for a long time.

Can you figure out if they exist in Numpy 1.17 or otherwise when exactly they were introduced?

**Comment by QuLogic** [comment]
Yes, they have been exact duplicates since at least 1.17:
https://github.com/numpy/numpy/blob/v1.17.0/numpy/__init__.py#L157-L163
