### ISSUE TITLE
Crash during gdal_translate from VRT to JP2 on Centos7 64bits + Kakadu 7.10.3

### ISSUE THREAD

**Issue by ebremont** [OSGeo/gdal#345]
[B01.zip](https://github.com/OSGeo/gdal/files/1864065/B01.zip)
## Expected behavior and actual behavior.

I try to make a reprojection to SRS 3857 of a jpeg2000 file, but the gdaltranslate operation crashes (segmentation fault). I get the following log : 
ERROR 1 : Kakadu Core Error:
Malformed attribute string, "QStep=0.0000152588" !
Problem encountered at ".0000152588"
Record must be separated by commas
terminate called after throwing an instance of 'kdu_cpl_error_message::JP2KAKException"

I attach to this post the input JP2 file.

## Steps to reproduce the problem.

gdal_warp -of VRT -t_srs EPSG:3857 input.jp2 output.VRT
gdaltranslate -of JP2KAK output.VRT output.JP2 --> crash

but :
gdal_warp -t_srs EPSG:3857 input.jp2 output.tif
gdaltranslate -of JP2KAK output.tif output.JP2 --> ok

## Operating system

Centos 7.3.1611 64b

## GDAL version and provenance

the 2.2.3 version (sources from http://download.osgeo.org/gdal/2.2.3/gdal223.zip)
Kakadu 7.10.3

**Comment by rouault** [comment]
Closing. Not actionable
