### ISSUE TITLE
feature: COG overview compression configuration

### ISSUE THREAD

**Issue by blacha** [OSGeo/gdal#3453]
### Background

We have 150TB of scanned historical imagery that we are looking to COG and store in AWS, We would like to leave the main image in a lossless format such as LZW. We would prefer to use a more optimized version for the overviews (Jpeg/WebP), so that we can keep the file size as small as possible

Looking at the source code for the geotiff driver, the compression for the overviews is set the same as the main image. If I manually modify the line and force it to compress into webp, the COG is still created and looks like it "works" in QGIS.

specifically if I hard code https://github.com/OSGeo/gdal/blob/master/gdal/frmts/gtiff/geotiff.cpp#L10310 to `COMPRESSION_WEBP` it generates the following tiff (it is 20GB and hosted in NZ)

https://public.lo.chard.com/new_zealand_sentinel_2019-2020_10m.vrt.lzw.cog.tiff

```
Id  	Size                	Tile Size           	Tile Count          	Resolution          	Compression         
0   	100800x151200       	394x591             	232854              	10                  	application/lzw     
1   	50400x75600         	197x296             	58312               	20                  	image/webp          
2   	25200x37800         	99x148              	14652               	40                  	image/webp          
3   	12600x18900         	50x74               	3700                	80                  	image/webp          
4   	6300x9450           	25x37               	925                 	160                 	image/webp          
5   	3150x4725           	13x19               	247                 	320                 	image/webp          
6   	1575x2362           	7x10                	70                  	640                 	image/webp          
7   	787x1181            	4x5                 	20                  	1280.8132           	image/webp          
8   	393x590             	2x3                 	6                   	2564.8854           	image/webp          
9   	196x295             	1x2                 	2                   	5142.8571           	image/webp          
10  	98x147              	1x1                 	1                   	10285.7142          	image/webp  
```

### Suggestion

Add `OVERVIEW_COMPRESS` (since `OVERVIEW_RESAMPLING` exists in the COG driver) to the COG driver so it can generate compressed overviews.

**Comment by jratike80** [comment]
I believe that the normal configuration options for compressing overviews work also for COG https://gdal.org/programs/gdaladdo.html

Have a try with 

`--config COMPRESS_OVERVIEW JPEG --config PHOTOMETRIC_OVERVIEW YCBCR --config INTERLEAVE_OVERVIEW PIXEL`

If they work it would be good to mention them in the COG document page because COG combines the GeoTIFF driver and gdaladdo and users normally do not need to have a look at the gdaladdo document.

**Comment by blacha** [comment]
Looking at the source code, it appears to pull the compression type `m_nCompression` from the TiffTag `TIFFTAG_COMPRESSION`  of the first image and has no logic to pull it from flags.

When running with gdal 3.1.3

```
$ gdal_translate small.vrt  -of COG -co COMPRESS_OVERVIEW=webp small.cog                                                                                 

Warning 6: driver COG does not support creation option COMPRESS_OVERVIEW
```

**Comment by jratike80** [comment]
Just copy and paste without editing. `-co` stands for creation option but `--config COMPRESS_OVERVIEW JPEG` sets a configuration option.

**Comment by blacha** [comment]
Ahh good catch on the `-co` vs `--config`

```
gdal_translate small.vrt  -of COG --config COMPRESS_OVERVIEW webp small.cog    
```
Creates all the overviews as `lzw` the source imagery is `lzw`

**Comment by jratike80** [comment]
I confirm, unfortunately config option has no effect

```
gdal_translate p4433h.tif  -of COG ovtest1.tif
gdal_translate p4433h.tif  -of COG ovtest2.tif --config COMPRESS_OVERVIEW JPEG

12.02.2021  10.17       606 353 466 ovtest1.tif
12.02.2021  10.17       606 353 466 ovtest2.tif
```

**Comment by jratike80** [comment]
As a workaround it might work to create overviews as you wish for the VRT with gdaladdo and then convert VRT into COG. The overviews should be copied.

**Comment by blacha** [comment]
By running your commands against a 27MB test file I have get a file around 44MB.  All overviews of this file use the same compression as the source file

```
45615260 ovtest3.cog.tif 
```

When using my build of GDAL which forces webp for the overview creation, the file output is 30MB 
```
31458568 ovtest3.webp.cog.tiff
```

so pretty significant savings if I can webp the overviews
