### ISSUE TITLE
Segmentation fault reading features from mdb file using odbc driver

### ISSUE THREAD

**Issue by uclaros** [OSGeo/gdal#3455]
## Expected behavior and actual behavior.
I was given some *mdb* files with geometryless tables that cause a segmentation fault when trying to read features from.
I can successfully get the tables with `ogrinfo file.mdb` but get a segfault with `ogrinfo file.mdb bad_table`.

File is opened using the 'ODBC' driver.
File can be successfully read with mdbtools 

## Steps to reproduce the problem.
1. Download [file.zip](https://github.com/OSGeo/gdal/files/5976019/file.zip), and unzip `file.mdb`
2. run `ogrinfo file.mdb bad_table` to get a segfault
3. dragging into QGIS causes it to crash too.

## Operating system
Debian testing

## GDAL version and provenance
GDAL 3.2.1, released 2020/12/29 (from debian repo)

**Comment by nyalldawson** [comment]
Which version of mdbtools have you got? Anything prior to .9 (very recent) had all sorts of issues and crashes in the odbc driver.

**Comment by uclaros** [comment]
That's `mdbtools       0.9.1-1      amd64`

**Comment by nyalldawson** [comment]
Hmmmm - I think you'll need to debug the query which gdal is sending via odbc and then see if you can reproduce via the Unixodbc command line tools. It's quite likely the crash is coming from either Unixodbc or mdbtools itself.

**Comment by uclaros** [comment]
Tested a little in `isql`:
- `select * from bad_table` gives a segfault.
- `select * from bad_table where 1=2` returns the headers
- selecting text fields works ok
- selecting numeric fields segfaults

**Comment by nyalldawson** [comment]
Thanks @uclaros ! So we can close this report and move it over to https://github.com/mdbtools/mdbtools

**Comment by uclaros** [comment]
Yes, indeed, I am already filing an issue upstream to mdbtools!

**Comment by nyalldawson** [comment]
Fix submitted to mdbtools here: https://github.com/mdbtools/mdbtools/pull/256
