### ISSUE TITLE
ogr silently ignores some rows in mdb with odbc driver

### ISSUE THREAD

**Issue by uclaros** [OSGeo/gdal#3456]
## Expected behavior and actual behavior.
I came across some geometryless mdbs that while correctly reporting their feature count, they only return a subset of their features when read with ogr (ogrinfo or ogr2ogr) and odbc driver.

## Steps to reproduce the problem.
An offending mdb is [bad.zip](https://github.com/OSGeo/gdal/files/5976607/bad.zip)
The file originally had three thousand rows but only returned 2. After deleting some dozen other tables and most of the offending table's rows, it now returns 4 instead of 6 rows.
`ogrinfo bad.mbd PROP` correctly shows feature count 6, but incorrectly lists only 4 features.
`ogr2ogr bad.gpkg bad.mdb PROP` creates a geopackage containing only 4 features instead of 6.

mdbtools correctly exports all rows, ie `mdb-export bad.mdb PROP` returns 6 rows.
mdbtools odbc correctly list all rows, ie open the mdb in `isql` and run `select * from PROP` returns 6 rows.

## Operating system
Debian bullseye

## GDAL version and provenance
GDAL 3.2.1, released 2020/12/29 (from debian repo)
mdbtools 0.9.1-1

**Comment by nyalldawson** [comment]
...looking into this...
