### ISSUE TITLE
geotiff.cpp(10989): error: identifier "LIBGEOTIFF_WARNING" is undefined

### ISSUE THREAD

**Issue by valerie-vallet** [OSGeo/gdal#3457]
## Expected behavior and actual behavior.

I am trying to install gdal-3.2.1 on a linux plateform.
./configure --prefix=/share/apps --with-proj=/share/apps --with-geotiff=internal --with-hide-internal-symbols --with-libtiff=internal --without-libtool
But I get an error when compiling the geotiff part:

geotiff.cpp(10989): error: identifier "LIBGEOTIFF_WARNING" is undefined
      CPLErrorV( (level == LIBGEOTIFF_WARNING ) ? CE_Warning : CE_Failure,

## Steps to reproduce the problem.

make

## Operating system

CentOS Linux release 7.4.1708 (Core)

## GDAL version and provenance

3.2.1: https://github.com/OSGeo/gdal/releases/download/v3.2.1/gdal-3.2.1.tar.gz

**Comment by rouault** [comment]
I suspect there's a geotiff.h from an older geotiff version in /share/apps/include

**Comment by rouault** [comment]
@valerie-vallet Can you give some feedback with respect to my above hypothesis ?

**Comment by valerie-vallet** [comment]
Hi @rouault, The geotiff error disappeared after uninstalling an old version of geotiff.h,
But now I get the following error:
g++ -std=c++11 -I/share/apps/share/gdal-3.2.1/port -I/share/apps/share/gdal-3.2.1/gcore -I/share/apps/share/gdal-3.2.1/alg -I/share/apps/share/gdal-3.2.1/ogr -I/share/apps/share/gdal-3.2.1/ogr/ogrsf_frmts -I/share/apps/share/gdal-3.2.1/gnm -I/share/apps/share/gdal-3.2.1/apps -DHAVE_AVX_AT_COMPILE_TIME -DHAVE_SSSE3_AT_COMPILE_TIME -DHAVE_SSE_AT_COMPILE_TIME -g -O2 -fPIC  -Wall -Wextra -Winit-self -Wunused-parameter -Wformat -Werror=format-security -Wno-format-nonliteral -Wlogical-op -Wshadow -Werror=vla -Wdate-time -Wfloat-conversion -Wmissing-declarations -Wnon-virtual-dtor -Woverloaded-virtual -fno-operator-names -Wzero-as-null-pointer-constant  -DGNM_ENABLED -I/share/apps/share/gdal-3.2.1/port -I/share/apps/include  -DGDAL_COMPILATION -DHAVE_HDF5 -DNETCDF_HAS_NC4   -c -o ../o/netcdfdataset.o netcdfdataset.cpp
In file included from netcdfsgwriterutil.h:39:0,
                 from netcdfdataset.h:48,
                 from netcdfdataset.cpp:53:
netcdfvirtual.h:146:42: error: ‘NC_INT’ was not declared in this scope
     typedef netCDFVGeneralAttribute<int, NC_INT> netCDFVIntAttribute;
                                          ^
netcdfvirtual.h:146:48: error: template argument 2 is invalid
     typedef netCDFVGeneralAttribute<int, NC_INT> netCDFVIntAttribute;
                                                ^
netcdfvirtual.h:146:69: error: invalid type in declaration before ‘;’ token
     typedef netCDFVGeneralAttribute<int, NC_INT> netCDFVIntAttribute;
 
In the netcdf part. Any idea?

**Comment by rouault** [comment]
> In the netcdf part. Any idea?

you're probably using a too old version of netcdf, or without NC4 support.

**Comment by mloskot** [comment]
@valerie-vallet  Try https://lists.osgeo.org/pipermail/gdal-dev/2008-April/016937.html as it may be related

**Comment by valerie-vallet** [comment]
Thanks for the tip, I installed the latest netcdf and gdal now compiles smoothly! What a relieve !
Thanks @rouault and @mloskot for your help!
