### ISSUE TITLE
Error with WMTS driver

### ISSUE THREAD

**Issue by elenaaplitop** [OSGeo/gdal#3459]
Hello, I´m trying to call web services (WMTS and WMS) using GDAL 3.0.2, but I have a problem with this example:
 
gdal_translate "WMTS:http://www.ign.es/wmts/pnoa-ma?request=GetCapabilities&service=WMTS,layer=OI.OrthoimageCoverage,tilematrixset=EPSG:4326" d://wmts_bm.xml -of WMTS
ERROR 1: Invalid dataset dimensions : -135056383 x -167901439

In this server http://www.ign.es/wmts/pnoa-ma has available the next CRS :
SUBDATASET_1_NAME=WMTS:http://www.ign.es/wmts/pnoa-ma?request=GetCapabilities&service=WMTS,layer=OI.OrthoimageCoverage,tilematrixset=InspireCRS84Quad
SUBDATASET_2_NAME=WMTS:http://www.ign.es/wmts/pnoa-ma?request=GetCapabilities&service=WMTS,layer=OI.OrthoimageCoverage,tilematrixset=EPSG:4326
SUBDATASET_3_NAME=WMTS:http://www.ign.es/wmts/pnoa-ma?request=GetCapabilities&service=WMTS,layer=OI.OrthoimageCoverage,tilematrixset=EPSG:4258
SUBDATASET_4_NAME=WMTS:http://www.ign.es/wmts/pnoa-ma?request=GetCapabilities&service=WMTS,layer=OI.OrthoimageCoverage,tilematrixset=EPSG:25830
SUBDATASET_5_NAME=WMTS:http://www.ign.es/wmts/pnoa-ma?request=GetCapabilities&service=WMTS,layer=OI.OrthoimageCoverage,tilematrixset=GoogleMapsCompatible

But when I want to Know the information or download a image in certain coordinates  with EPSG:4326, it returns an error “ERROR 1: Invalid dataset dimensions : -135056383 x -167901439”, with EPSG:25830 works fine. Is this a bug?

----
Here is ML thread where @elenaaplitop posted this, where it also received some responses
 https://lists.osgeo.org/pipermail/gdal-dev/2021-February/053465.html

**Comment by jratike80** [comment]
Well, it may be a bug or then not. You have correctly asked the same question on the mailing list but unfortunately you did not get any final answer there. I will, however, send some more info within couple of minutes into that mail thread.

**Comment by mloskot** [comment]
By the way, isn't the correct URL for capabilities `http://www.ign.es/wmts/pnoa-ma?request=GetCapabilities&service=WMTS&version=1.0.0`?  Is the `,layer=OI.OrthoimageCoverage,tilematrixset=EPSG:4326` part etc. necessary there for the `GetCapabilities` request?

**Comment by elenaaplitop** [comment]
Hello, If Itry with http://www.ign.es/wmts/pnoa-ma?request=GetCapabilities&service=WMTS&version=1.0.0, the result is:


 *   gdal_translate "WMTS:http://www.ign.es/wmts/pnoa-ma?request=GetCapabilities&service=WMTS&version=1.0.0" d://wmts_bm.xml -of WMTS
Input file size is 16394432, 8334011
ERROR 1: Invalid dataset dimensions : -31316991 x -84258559
ERROR 1: Invalid dataset dimensions : -31316991 x -84258559

The same way get error for EPSG:4326 and EPSG:4258, both have the axes x and y reversed, Do you Know Why?
Regards
________________________________

[https://www.aplitop.com/descargas/firma1.jpg]


Elena Ruiz
Sofware Development & Technical Support
Tel. +34 952 43 97 71
eruiz@aplitop.com
Sumatra, 9 - 29190 Málaga (Spain)
www.aplitop.com

[cid:SocialLink_Facebook_32x32_a745adb8-c250-4372-8480-e77f503dad3d.png]<https://www.facebook.com/AplitopSL/>   [cid:SocialLink_Twitter_32x32_858247f6-9d4a-4740-a6b3-9b5ebfd98a97.png] <https://twitter.com/aplitop>    [cid:SocialLink_Linkedin_32x32_154d63de-bf68-468f-9eb0-ffed102fac77.png] <https://www.linkedin.com/company/aplitop>    [cid:SocialLink_Youtube_32x32_0dea15dd-3774-4086-be9d-f62560b70c86.png] <https://www.youtube.com/user/aplitop>


In accordance with the provisions of the European Regulation of Data Protection 2016/679 (Reglamento Europeo de Protección de Datos 2016/679), we inform you that the data and the information you provide us through this medium will be used by APLITOP, S.L., with C.I.F. B-92543396 and with address at C / Sumatra, 9, Malaga, 29190, in order to answer your questions and inform you about our products. The data provided will be kept as long as it does not request its cessation and will not be transferred to third parties except in cases where there is a legal obligation. You have the right to access your personal data, correct inaccurate data or request its deletion when the data is no longer necessary for the purposes that were collected, as well as any rights recognized in the RGPD 2016/679

<https://www.aplitop.com/Event/en/358/intergeo-2019>

De: Mateusz Łoskot <notifications@github.com>
Enviado el: lunes, 15 de febrero de 2021 13:26
Para: OSGeo/gdal <gdal@noreply.github.com>
CC: Elena Ruiz <eruiz@aplitop.com>; Mention <mention@noreply.github.com>
Asunto: Re: [OSGeo/gdal] Error with WMTS driver (#3459)


By the way, isn't the correct URL for capabilities http://www.ign.es/wmts/pnoa-ma?request=GetCapabilities&service=WMTS&version=1.0.0? Is the ,layer=OI.OrthoimageCoverage,tilematrixset=EPSG:4326 part etc. necessary there for the GetCapabilities request?

**Comment by jratike80** [comment]
IGN, for some reason, is using short EPSG:4326 expression for the SupportedCRS. GDAL seems to await lon-lat order.
If they used the same expression that is used in the note of the OGC standard
`<ows:SupportedCRS>urn:ogc:def:crs:EPSG::4326</ows:SupportedCRS>`
GDAL probably could interpret the dimensions right.

**Comment by elenaaplitop** [comment]
But the request of GDAL if I change EPSG:4326 for urn:ogc:def:crs:EPSG::4326:

>gdal_translate "WMTS:http://www.ign.es/wmts/pnoa-ma?request=GetCapabilities&service=WMTS,layer=OI.OrthoimageCoverage,tilematrixset=urn:ogc:def:crs:EPSG::4326" d://wmts_bm.xml -of WMTS
ERROR 1: Missing TileMatrixSetLink and/or Style

It seems that it does not recognize this format (urn:ogc:def:crs:EPSG::4326)


________________________________

[https://www.aplitop.com/descargas/firma1.jpg]


Elena Ruiz
Programación y Soporte Técnico
Tel. +34 952 43 97 71
eruiz@aplitop.com
Sumatra, 9 - 29190 Málaga (Spain)
www.aplitop.com

[cid:SocialLink_Facebook_32x32_25acade9-a391-48e8-a505-f65c90749377.png]<https://www.facebook.com/AplitopSL/>  [cid:SocialLink_Twitter_32x32_99fbb569-a1f2-4ff4-a474-e7cd1a6d2828.png] <https://twitter.com/aplitop>   [cid:SocialLink_Linkedin_32x32_f550270e-4111-43e9-a975-6451cd781766.png] <https://www.linkedin.com/company/aplitop>    [cid:SocialLink_Youtube_32x32_29ecd8ca-8049-47c1-927e-a321d4902e68.png] <https://www.youtube.com/user/aplitop>


De acuerdo con lo dispuesto en el Reglamento Europeo de Protección de Datos 2016/679, le informamos que los datos y la información que nos facilita a través de este medio será utilizada por APLITOP, S.L., con C.I.F. B-92543396 y con domicilio en C/Sumatra, 9, Málaga, 29190, con la finalidad de atender sus consultas e informarle sobre nuestros productos. Los datos proporcionados se conservarán mientras no solicite su cese y no se cederán a terceros salvo en los casos en que exista una obligación legal. Usted tiene el derecho a acceder a sus datos personales, rectificar los datos inexactos o solicitar su supresión cuando los datos ya no sean necesarios para los fines que fueron recogidos, así como cualesquiera derecho reconocidos en el RGPD 2016/679.
<https://www.aplitop.com/Event/es/430/intergeo-2019>

<https://www.aplitop.com/New/es/415/lanzamiento-de-mdt-versin-8>
De: Jukka Rahkonen <notifications@github.com>
Enviado el: lunes, 15 de febrero de 2021 13:56
Para: OSGeo/gdal <gdal@noreply.github.com>
CC: Elena Ruiz <eruiz@aplitop.com>; Mention <mention@noreply.github.com>
Asunto: Re: [OSGeo/gdal] Error with WMTS driver (#3459)


IGN, for some reason, is using short EPSG:4326 expression for the SupportedCRS. GDAL seems to await lon-lat order.
If they used the same expression that is used in the note of the OGC standard
<ows:SupportedCRS>urn:ogc:def:crs:EPSG::4326</ows:SupportedCRS>
GDAL probably could interpret the dimensions right.

**Comment by jratike80** [comment]
The server does not have TileMatrixSet named as `urn:ogc:def:crs:EPSG::4326`. It has only `EPSG:4326`. And server connects TileMatrixSet "EPSG:4326" (the name of the matrix set) with coordinate system "EPSG:4326". You can't change those on-the-fly, they are configured by the IGN.

I fear there is not an easy workaround. One thing that could work is to capture the GetCapabilities XML from the IGN server, edit the SupportedCRS, put the static XML into your own http server and point GDAL to use your edited capabilities document. The GetTile links would still point to the real server. 

```
<ows:Operation name="GetTile">
<ows:DCP>
<ows:HTTP>
<ows:Get xlink:href="http://www.ign.es/wmts/pnoa-ma?">
```
This is a blind shot anyway, I do not know how much the WMTS driver relies on the GetCapabilities.

I would contact IGN anyway. But obviously they have fiddled with CRS intentionally so they may say that it is not wrong.

**Comment by jratike80** [comment]
> By the way, isn't the correct URL for capabilities `http://www.ign.es/wmts/pnoa-ma?request=GetCapabilities&service=WMTS&version=1.0.0`? Is the `,layer=OI.OrthoimageCoverage,tilematrixset=EPSG:4326` part etc. necessary there for the `GetCapabilities`

Perhaps not necessary but it selects the desired subdataset and tilematrixset. Usage is documented in section "Generation of WMTS service description XML file" https://gdal.org/drivers/raster/wmts.html.

**Comment by elenaaplitop** [comment]
The XML file is:

<GDAL_WMTS>
  <GetCapabilitiesUrl>http://www.ign.es/wmts/pnoa-ma?request=GetCapabilities&amp;service=WMTS</GetCapabilitiesUrl>
  <Layer>OI.OrthoimageCoverage</Layer>
  <TileMatrixSet>EPSG:4326</TileMatrixSet> //can be optional
  <TileMatrix>EPSG:4326:18</TileMatrix> //can be optional
  <Format>image/png</Format>
  <DataWindow>
    <UpperLeftX>-3.98640</UpperLeftX>
    <UpperLeftY>37.91226</UpperLeftY>
    <LowerRightX>-3.96872</LowerRightX>
    <LowerRightY>37.90300</LowerRightY>
  </DataWindow>
  <Projection>urn:ogc:def:crs:EPSG::4326</Projection > // can be optional
  <BandsCount>4</BandsCount>
  <Cache />
  <UnsafeSSL>true</UnsafeSSL>
  <ZeroBlockHttpCodes>204,404</ZeroBlockHttpCodes>
  <ZeroBlockOnServerException>true</ZeroBlockOnServerException>
</GDAL_WMTS>

In this file there are labels that are optional as TileMatrixSet, I have tried several options:
* If I remove the TileMatrixSet, the result is :
>gdal_translate d:\geoserver_01.xml d:\image_4326.jpg
ERROR 1: Cannot find TileMatrix 'EPSG:4326:18' in TileMatrixSet 'InspireCRS84Quad'
In this case although the projection is put as <Projection>urn:ogc:def:crs:EPSG::4326</Projection >, gdal_translate understands that the projection is InspireCRS84Quad, 
* If I put TileMatrixSet, the result is:
ERROR 1: Invalid dataset dimensions : -84246783 x -89815039

Therefore it does not work neither putting the url nor with the XML file...

**Comment by jratike80** [comment]
I managed to get something out from that service. The result may be correct or not and I still think that IGN should revert the change that they have made with the CRS. But by following these steps I have managed to read a tile from that service with GDAL.

1. Read the GetCapabilities from http://www.ign.es/wmts/pnoa-ma?request=GetCapabilities&service=WMTS&version=1.1.0. Save the result as a textfile on local disk I named it "ign_capabilities.xml".
2. Open the file with text editor. Find row number 1001 and change
Change this
`<ows:SupportedCRS>EPSG:4326</ows:SupportedCRS>`
into
`<ows:SupportedCRS>urn:ogc:def:crs:EPSG::4326</ows:SupportedCRS>`
Save again
3. Test with gdalinfo, it should print some info:
`gdalinfo ign_capabilities.xml`
4. Create XML file for the GDAL WMTS driver. Read the GetCapabilities from the file that you just corrected.

```
gdal_translate WMTS:ign_capabilities.xml,layer=OI.OrthoimageCoverage,tilematrixset=EPSG:4326 -of WMTS ign_wmts.xml
Input file size is 65577729, 33336043
```

5. Test ign_wmts.xml with gdalinfo, it should print some info:
`gdalinfo ign_wmts.xml`

6. Test with gdal_translate (I selected the projwin from somewhere in the middle of Spain)
`gdal_translate -of GTiff -projwin  -3.0983316  40.5271178 -3.0982316  40.5270178 -outsize 100 100 ign_wmts.xml out.tif --debug on`

![image](https://user-images.githubusercontent.com/1751612/108060638-cc7ed400-705f-11eb-8e1d-dda3b40c1833.png)



I suggest you to do 3 things:
1. Close this ticket and write a mail to the gdal-dev mailing list in order to help other people who are struggling with axis order issues with WMTS. There is no GDAL bug as the title puts it "Error with WMTS driver". The issue is that WMTS driver does not cope with WMTS server that is configured wrong.
2. Contact IGN and ask them to seriously consider to use `urn:ogc:def:crs:EPSG::4326`.
3. Write a new GDAL enhancement ticket about adding some "flip_tilematrixset_axis" control into WMTS driver. It would be nice if you can find a developer to implement that, or if you can it yourself.

**Comment by elenaaplitop** [comment]
Hello, thank you very much for the solution, it is a somewhat far-fetched solution, but it works for me, and it is clear to me that the problem is from IGN.
Regards

**Comment by drnextgis** [comment]
I stumbled upon the similar issue but using another public WMTS service. To overcome the issue I downloaded `GetCapabilities` document and swapped coordinates of the buggy `TileMatrix` inside `TopLeftCorner` tag.
