### ISSUE TITLE
Not able to return lat lon

### ISSUE THREAD

**Issue by Vdm88** [OSGeo/gdal#3461]
Added the following in the config

[points]
# common attributes
osm_id=yes
osm_version=no
osm_timestamp=no
osm_uid=no
osm_user=no
osm_changeset=no
osm_lat=yes
osm_lon=yes

Lat and lon are not outputted.

Used Gdal 2.4.4 c#

**Comment by jratike80** [comment]
You should have asked this as a question on the mailing list.

GDAL supports a fixed list of common attributes https://github.com/OSGeo/gdal/blob/master/gdal/data/osmconf.ini

```
# common attributes
osm_id=yes
osm_version=no
osm_timestamp=no
osm_uid=no
osm_user=no
osm_changeset=no

```

You cannot just add new attributes into osmconf.ini but you must also change the code of the OSM driver to deal with them. I believe that if you make a PR that adds osm_lat and osm_lon into the list it would have good chance to be accepted. The default must be "no".
