### ISSUE TITLE
linker issue with internal (probably external too) with PNG neon detection with gdal 3.2.1

### ISSUE THREAD

**Issue by vautieri** [OSGeo/gdal#3464]
## Operating system
wsl2 ubuntu cross compile for android 
LLVM 9.0.8
aarch64 linux android28

Note,  the same build environment has no issues building gdal 2.4 I am now moving to gdal 3.2.1.  I am not sure if this really belongs here, but we don't have issues using png as an external lib with other projects.  NOTE, something in gdal's ./configure is making things build with this detection turned on (my guess), trying to use neon for the arm64.  

I hacked the code below to get me going, as I am not sure of the proper way to fix,.

```
#  if (defined(__ARM_NEON__) || defined(__ARM_NEON)) && \
   defined(PNG_ALIGNED_MEMORY_SUPPORTED)
#     define PNG_ARM_NEON_OPT 0  ,// HACK FIX, this was 2 ***** this keeps gdal from trying build with neon/arm64 assembly
#  else
#     define PNG_ARM_NEON_OPT 0 
#  endif
#endif
```

**Comment by jjimenezshaw** [comment]
I think this was fixed in 1c719a864232daf58b799fbb2da785f3f9b2d579 , effective since 3.4.0
This issue can be closed
