### ISSUE TITLE
Runtime error and code execution stops

### ISSUE THREAD

**Issue by kunalkhosla93** [OSGeo/gdal#3478]
I wish to build a programme that uses GCPs to georefernece a image. I am using GDALCreateGCPTransformer to create a transformer which I am calling later to warp the image. However, during runtime my programme stops after this line.
`void* transform = GDALCreateGCPTransformer (3,gcps,2,FALSE);
` 
I hope i am using the correct libraries to link my programme(gdal_i.lib). I used vcpkg to intall gdal on windows.

What am i doing wrong?? I also have included the bin directory with correct .dll files in my PATH variable. I think i have not installed GDAL correctly. Can some one guide me here?? 

This happened to me before for GDALWarp as well.

My programme builds correctly so i have no reason to doubt that all header files and libraries have been included. Is this a bug in gdal itself? Kindly help..

**Comment by mloskot** [comment]
> However, during runtime my programme stops after this line.
> ```
> void* transform = GDALCreateGCPTransformer (3,gcps,2,FALSE); 
> ```

You will have to debug your application.

> Can some one guide me here??

I guess nobody here has access to a crystal sphere to guess details of your setup, build, code, etc. or time to teach you how to use the development toolkit of your choice.

Finally, we expect questions to be posted to https://lists.osgeo.org/mailman/listinfo/gdal-dev, not as GitHub issues.
