### ISSUE TITLE
RPC missing ERR_BIAS and ERR_RAND values

### ISSUE THREAD

**Issue by cstutts** [OSGeo/gdal#3484]
## Expected behavior and actual behavior.

When I open a DigitalGlobe NTF file (Basic 1B processing) I see the the RPC domain is missing the ERR_BIAS and ERR_RAND values. I can grab these from the RPC00B metadata item in the TRE domain and set them manually using the below code. For a NTF file it writes out an aux.xml file with the added fields, but does not update the actual RPC domain in the file (i.e. I don't want to drag along extra files with my imagery). If I convert the NTF to a GeoTIFF (which is the first step in my pipeline), then setting the RPC items sticks until I save the file, after which when reading the file back in ERR_BIAS and ERR_RAND are still missing.

Shouldn't these fields be included in the RPC by default?

## Steps to reproduce the problem.

from osgeo import gdal
ds = gdal.Open("MyFile.tif",gdal.GA_Update) # Can be a NTF too, but this aux.xml gets created instead of updating the header 
rpc = ds.GetMetadata("RPC")
print(rpc)

{'HEIGHT_OFF': '-21',                                                                                             
 'HEIGHT_SCALE': '501',                                                                                           
 'LAT_OFF': '30.3003',                                                                                             
 'LAT_SCALE': '0.0703',                                                                                           
 'LINE_DEN_COEFF': '1 0.0001684873 -6.335265e-05 1.507818e-05 4.833381e-06 1.910986e-07 1.795369e-06 1.114958e-05 -
3.57498e-05 1.553184e-05 3.877905e-07 0 -1.523022e-05 0 4.164689e-07 0.0001748632 8.989371e-08 0 -6.761896e-06 0',
 'LINE_NUM_COEFF': '-9.59544e-05 0.03701784 -1.051146 0.01355396 0.0001434057 -2.877661e-06 1.275568e-05 -0.0004139
917 8.666037e-05 -1.204151e-06 -3.238694e-07 5.050705e-07 3.533154e-06 5.778745e-07 -1.224662e-05 -5.844016e-05 -1.
634623e-05 1.783486e-07 1.085339e-06 2.096943e-07',                                                                
 'LINE_OFF': '22757',                                                                                             
 'LINE_SCALE': '22758',                                                                                           
 'LONG_OFF': '-81.6408',                                                                                          
 'LONG_SCALE': '0.0729',                                                                                          
 'SAMP_DEN_COEFF': '1 0.001049638 0.0009599374 -0.0004588982 -1.043929e-05 -8.670581e-07 1.354862e-07 5.755182e-06
3.026614e-07 -2.442154e-06 -2.770866e-08 0 1.838139e-07 0 -1.399761e-07 1.059721e-07 0 0 0 0',                    
 'SAMP_NUM_COEFF': '-0.004379428 1.016398 0.0008397763 -0.01385913 -0.0009450556 0.000391861 -0.0002151448 0.003352
82 -0.000251548 -1.929016e-06 -1.477436e-06 4.961405e-06 -4.221051e-06 -2.19379e-06 1.754333e-05 -3.721629e-05 -9.6
91363e-08 2.320462e-06 1.804481e-06 3.192365e-08',                                                                
 'SAMP_OFF': '21249',                                                                                             
 'SAMP_SCALE': '21250'}

# ERR_BIAS and ERR_RAND are located in the RPC00B metadata item of the TRE domain
rpc00b = ds.GetMetadata("RPC00B","TRE")
err_bias = rpc00b[1:8]
err_rand = rpc00b[8:15]

ds.SetMetadataItem("ERR_BIAS",err_bias,"RPC")
ds.SetMetadataItem("ERR_RAND",err_rand,"RPC")
ds = None

ds = gdal.Open("MyFile.tif",gdal.GA_ReadOnly)

rpc = ds.GetMetadata("RPC")
print(rpc)

{'HEIGHT_OFF': '-21',                                                                                             
 'HEIGHT_SCALE': '501',                                                                                           
 'LAT_OFF': '30.3003',                                                                                             
 'LAT_SCALE': '0.0703',                                                                                           
 'LINE_DEN_COEFF': '1 0.0001684873 -6.335265e-05 1.507818e-05 4.833381e-06 1.910986e-07 1.795369e-06 1.114958e-05 -
3.57498e-05 1.553184e-05 3.877905e-07 0 -1.523022e-05 0 4.164689e-07 0.0001748632 8.989371e-08 0 -6.761896e-06 0',
 'LINE_NUM_COEFF': '-9.59544e-05 0.03701784 -1.051146 0.01355396 0.0001434057 -2.877661e-06 1.275568e-05 -0.0004139
917 8.666037e-05 -1.204151e-06 -3.238694e-07 5.050705e-07 3.533154e-06 5.778745e-07 -1.224662e-05 -5.844016e-05 -1.
634623e-05 1.783486e-07 1.085339e-06 2.096943e-07',                                                                
 'LINE_OFF': '22757',                                                                                             
 'LINE_SCALE': '22758',                                                                                           
 'LONG_OFF': '-81.6408',                                                                                          
 'LONG_SCALE': '0.0729',                                                                                          
 'SAMP_DEN_COEFF': '1 0.001049638 0.0009599374 -0.0004588982 -1.043929e-05 -8.670581e-07 1.354862e-07 5.755182e-06
3.026614e-07 -2.442154e-06 -2.770866e-08 0 1.838139e-07 0 -1.399761e-07 1.059721e-07 0 0 0 0',                    
 'SAMP_NUM_COEFF': '-0.004379428 1.016398 0.0008397763 -0.01385913 -0.0009450556 0.000391861 -0.0002151448 0.003352
82 -0.000251548 -1.929016e-06 -1.477436e-06 4.961405e-06 -4.221051e-06 -2.19379e-06 1.754333e-05 -3.721629e-05 -9.6
91363e-08 2.320462e-06 1.804481e-06 3.192365e-08',                                                                
 'SAMP_OFF': '21249',                                                                                             
 'SAMP_SCALE': '21250'} 

## Operating system

Ubuntu 18.04

## GDAL version and provenance

GDAL 3.1.2 built from source

**Comment by nmaxwell** [comment]
Looking at  geotiff.cpp, around line 11981:

https://github.com/OSGeo/gdal/blob/30d47f0bf14b8234892905434f251b9ef6c5f918/gdal/frmts/gtiff/geotiff.cpp#L11981

there is 

```
    CPLStringList asMD;
    asMD.SetNameValue(RPC_LINE_OFF, CPLOPrintf("%.15g", padfRPCTag[2]));
    asMD.SetNameValue(RPC_SAMP_OFF, CPLOPrintf("%.15g", padfRPCTag[3]));
```

we noticed that the function starts reading at position 2, of padfRPCTag. Do positions 0 and 1 contain the missing values?

**Comment by jpapadakis** [comment]
I have made an attempt to add these parameters to GDALRPCInfo and correctly parse them when reading NITFs and GeoTIFFs.

**Comment by cstutts** [comment]
The RPC metadata domain in generated in GDAL ultimately from the NITF RPC00A or RPC00B block based on the NITF STDI-00002 spec document. According to that document (https://gwg.nga.mil/ntb/baseline/docs/stdi0002/stdi0002_v10/stdi0002_v10.pdf) TABLE 10-9. RPCOOA – RAPID POSITIONING CAPABILITY EXTENSION FORMAT states that ERR_BIAS and ERR_RAND are required fields in the spec.
For our purposes, we need these fields to be present in the RPC and RPB block.

**Comment by rouault** [comment]
> For our purposes, we need these fields to be present in the RPC and RPB block.

That's more a quality checking to do on you side (or add some option to the NITF driver to be very strict regarding that and bail out if not present). We shouldn't prevent to read files that we used to before.

**Comment by cstutts** [comment]
I'm assuming the RPB is always generated from the the NITF TRE RPC00B or RPC00A fields. My sources for imagery containing these are typically from DigitalGlobe provided in an archive and ERR_BIAS and ERR_Rand are always specified. I'm guessing that RPB files missing these fields were generated via PAM_ENABLED from GDAL prior to this fix (similar to how IMD files get generated if there is an IMD metadata domain)? Since they're required in the NITF spec, doesn't it makes since to always write them out when generating RPBs? I agree there shouldn't be an error when trying to read RPB files missing these fields. Would it not be best to assign a value outside the 0000.00 to 6553.50 range (e.g. -1) in the return value from GDAL for these fields if they're missing from an RPB file or re-obtain them directly from the NITF TRE if present?

**Comment by rouault** [comment]
> Since they're required in the NITF spec, doesn't it makes since to always write them out when generating RPBs?

I'd decouple things. NITF requirements are NITF ones. I'm not sure if there's a RPB specification ?
Evaluating RPCs (ie transforming between image coordinates and geographic coordinates) doesn't need those fields.

> Would it not be best to assign a value outside the 0000.00 to 6553.50 range (e.g. -1) in the return value from GDAL for these fields if they're missing from an RPB file 

It seems to me clearer that GDALLoadRPBFile() doesn't "invent" values if they aren't found. 

> Would it not be best to assign a value outside the 0000.00 to 6553.50 range (e.g. -1) in the return value from GDAL for these fields if they're missing from an RPB file or re-obtain them directly from the NITF TRE if present

Not immediately obvious to me how we'd do that in the GDAL architecture.

**Comment by deng0** [comment]
While I agree that RPB files should probably always contain the errBias and errRand fields, I also think reading should not fail when they are missing.

Regarding GDAL writing RPB files:
It seems prior to 3.3 when creating RPB files GDAL always wrote those two fields hardcoded with values 0.0 and now it writes the actual values unless they are missing, then it still writes 0.0. 
```
        if( pszRPBVal == nullptr )
        {
            if (strcmp(apszRPBMap[i], RPC_ERR_BIAS) == 0) {
                bOK &= VSIFPrintfL( fp, "%s", "\terrBias = 0.0;\n" ) > 0;
                continue;
            } else if (strcmp(apszRPBMap[i], RPC_ERR_RAND) == 0) {
                bOK &= VSIFPrintfL( fp, "%s", "\terrRand = 0.0;\n" ) > 0;
                continue;
            } 
```

I think a negative value might be better but because it has been like this for years, it's probably better not to change that.
