### ISSUE TITLE
GDL 3.2.1 OGR GetFieldAsString UTF-8 UTF-16

### ISSUE THREAD

**Issue by sagido123** [OSGeo/gdal#3490]
GetFieldAsString return UTF-8 (when opening some maps) or UTF-16  (when opening some other maps).
Is the result map depended ?
How can I detect that ?

**Comment by rouault** [comment]
You must be more specific about which datasource (and the related driver) you open

**Comment by sagido123** [comment]
I open Esri shp files.

**Comment by rouault** [comment]
> I open Esri shp files.

The shapefile driver should return UTF-8 whatever the encoding of the shapefile (provided that the relevant encoding information is stored in the .dbf header or in a side-car .cpg file). If it returns UTF-16, could you attach a zip file with the shape file (with all side car files) in that ticket ?

**Comment by sagido123** [comment]
[rivers.zip](https://github.com/OSGeo/gdal/files/6068768/rivers.zip)

**Comment by rouault** [comment]
This is a dataset issue. It doesn't contain any encoding information. I tried to force the open option -oo  ENCODING=UTF-16 but it doesn't look to produce correct output, so I'm doubtful the source encoding is UTF-16. Closing as not a GDAL bug

**Comment by sagido123** [comment]
I can open this dataset with old code of OGR .

**Comment by rouault** [comment]
> I can open this dataset with old code of OGR .

With which version of GDAL did you manage to successfully decode the content ?

**Comment by sagido123** [comment]
GDAL 1.3.0

**Comment by rouault** [comment]
> GDAL 1.3.0

aouch ! I was hardly born at that time. But I've just managed to build GDAL 1.3.0 and I get the exact same output with ogrinfo with it than with GDAL master...
```
NFO: Open of `rivers.shp'
using driver `ESRI Shapefile' successful.

Layer name: rivers
Geometry: Line String
Feature Count: 4501
Extent: (139225.546875, 378994.500000) - (279598.375000, 803417.250000)
Layer SRS WKT:
(unknown)
<F9><ED>: String (100.0)
<EE><E3><F8><E2>: Real (24.15)
<F8><F9><E5><FA>_<F0><E9><F7><E5><E6>: String (100.0)
<F8><F6><E5><F2><FA>_<F0><E7><EC>: String (100.0)
<E9><F9>_<E1>_35: String (100.0)
Style: String (100.0)
OGRFeature(rivers):0
  <F9><ED> (String) = (null)
  <EE><E3><F8><E2> (Real) =        4.000000000000000
  <F8><F9><E5><FA>_<F0><E9><F7><E5><E6> (String) = <F9><F7><EE><E4> <E1><F9><E5><F8>
  <F8><F6><E5><F2><FA>_<F0><E7><EC> (String) = (null)
  <E9><F9>_<E1>_35 (String) = (null)
  Style (String) = PEN(c:#000000,w:0.1pt,id:ogr-pen-0)
  LINESTRING (164448.140625 600828.75,164410.78125 600735.4375,164410.78125 600617.1875,164417.015625 600561.1875,164385.890625 600480.3125,164354.765625 600411.9375,164328.984375 600360.3125,164272.953125 600310.5,164223.15625 600310.5,164173.375 600285.625,164086.234375 600273.1875,164017.765625 600242.0625,163961.75 600204.75,163768.78125 600092.75)
```
(the <XX> notation is with non-printable characters displayed by the ``less`` utility)
I'm afraid this ticket is non actionable.
