### ISSUE TITLE
Fix typos in the documentation of new OGC API driver

### ISSUE THREAD

**Issue by ghobona** [OSGeo/gdal#3491]
## Expected behavior and actual behavior.

There are some typos in the documentation of the new GDAL driver for OGC API - Tiles, OGC API - Maps or OGC API - Coverages.

"OGC API - Coverage" should be "OGC API - Coverages"

OAPIF should be expanded to OGC API - Features. The reason is that the official acronyms have not been decided yet.

## Steps to reproduce the problem.

https://gdal.org/drivers/raster/ogcapi.html#ogcapi-ogc-api-tiles-maps

## Operating system

Any

## GDAL version and provenance

3.2

**Comment by mloskot** [comment]
Thanks, fixed in https://github.com/OSGeo/gdal/pull/3492
