### ISSUE TITLE
Merging COG files with JPEG compression using gdalwarp does not consider nodata

### ISSUE THREAD

**Issue by mehran66** [OSGeo/gdal#3495]
## Expected behavior and actual behavior.

Merging Geotifs leads to black pixels OR no data is overwrite the pixels from another image. I am working with COG files and the compression is JPEG. The same issue happens with 3+apha band imagery.
This the biggest issue that I have had with GDAL and have not found any solution for it yet. The only solution that works is to first uncompress the geotiffs, but for a large project, it is a very big challenge. Also it seems that gdalbuildvrt accepts a new parameter (-ignore_srcmaskband) in version 3.3 that solves this issue, but I was wondering if there is any other solution for this issue at the moment!?

## Steps to reproduce the problem.

gdalwarp -multi -co NUM_THREADS=ALL_CPUS -co BIGTIFF=YES -of GTiff -r bilinear --config GDAL_CACHEMAX 999 -wm 999 image1.tif image2.tif result.tif

## Operating system

Ubuntu 20 64 bit

## GDAL version and provenance

GDAL 3.1.4, released 2020/10/20

# gdalinfo
Driver: GTiff/GeoTIFF
Files: /home/mehran/backup/code/gis/imagery2grid-v2/input-imagery/Zambia-all-imagery-5cm-02-25-2021/image-tiles/ZA_35S_r409_c232_x631025_y8300110.tif
Size is 40000, 40000
Coordinate System is:
PROJCRS["WGS 84 / UTM zone 35S",
    BASEGEOGCRS["WGS 84",
        DATUM["World Geodetic System 1984",
            ELLIPSOID["WGS 84",6378137,298.257223563,
                LENGTHUNIT["metre",1]]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433]],
        ID["EPSG",4326]],
    CONVERSION["UTM zone 35S",
        METHOD["Transverse Mercator",
            ID["EPSG",9807]],
        PARAMETER["Latitude of natural origin",0,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",27,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["Scale factor at natural origin",0.9996,
            SCALEUNIT["unity",1],
            ID["EPSG",8805]],
        PARAMETER["False easting",500000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",10000000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["(E)",east,
            ORDER[1],
            LENGTHUNIT["metre",1]],
        AXIS["(N)",north,
            ORDER[2],
            LENGTHUNIT["metre",1]],
    USAGE[
        SCOPE["unknown"],
        AREA["World - S hemisphere - 24°E to 30°E - by country"],
        BBOX[-80,24,0,30]],
    ID["EPSG",32735]]
Data axis to CRS axis mapping: 1,2
Origin = (631025.184099999954924,8300110.156899999827147)
Pixel Size = (0.050000000000000,-0.050000000000000)
Metadata:
  AREA_OR_POINT=Area
  TIFFTAG_DATETIME=*
  TIFFTAG_RESOLUTIONUNIT=2 (pixels/inch)
  TIFFTAG_SOFTWARE=*
  TIFFTAG_XRESOLUTION=72
  TIFFTAG_YRESOLUTION=72
Image Structure Metadata:
  COMPRESSION=YCbCr JPEG
  INTERLEAVE=PIXEL
  LAYOUT=COG
  SOURCE_COLOR_SPACE=YCbCr
Corner Coordinates:
Upper Left  (  631025.184, 8300110.157) ( 28d13'14.93"E, 15d22'20.77"S)
Lower Left  (  631025.184, 8298110.157) ( 28d13'15.31"E, 15d23'25.85"S)
Upper Right (  633025.184, 8300110.157) ( 28d14'22.00"E, 15d22'20.40"S)
Lower Right (  633025.184, 8298110.157) ( 28d14'22.39"E, 15d23'25.48"S)
Center      (  632025.184, 8299110.157) ( 28d13'48.66"E, 15d22'53.13"S)
Band 1 Block=512x512 Type=Byte, ColorInterp=Red
  Overviews: 20000x20000, 10000x10000, 5000x5000, 2500x2500, 1250x1250, 625x625, 313x313
  Mask Flags: PER_DATASET 
  Overviews of mask band: 20000x20000, 10000x10000, 5000x5000, 2500x2500, 1250x1250, 625x625, 313x313
Band 2 Block=512x512 Type=Byte, ColorInterp=Green
  Overviews: 20000x20000, 10000x10000, 5000x5000, 2500x2500, 1250x1250, 625x625, 313x313
  Mask Flags: PER_DATASET 
  Overviews of mask band: 20000x20000, 10000x10000, 5000x5000, 2500x2500, 1250x1250, 625x625, 313x313
Band 3 Block=512x512 Type=Byte, ColorInterp=Blue
  Overviews: 20000x20000, 10000x10000, 5000x5000, 2500x2500, 1250x1250, 625x625, 313x313
  Mask Flags: PER_DATASET 
  Overviews of mask band: 20000x20000, 10000x10000, 5000x5000, 2500x2500, 1250x1250, 625x625, 313x313

**Comment by jratike80** [comment]
Please make a test set with two small test images and the commands to reproduce the issue.

**Comment by mehran66** [comment]
It seems that I do not have this issue in the new version of GDAL (3.2.2)
