### ISSUE TITLE
import polygons shape files into SQL server get incorrect orientation.

### ISSUE THREAD

**Issue by qjohnchen** [OSGeo/gdal#3497]
## Expected behavior and actual behavior.

The imported polygon in SQL should be in the correct ring orientation.

Currently, after importing, the polygons are in the wrong orientation. I have to create a column Poly (geography) convert the imported polygon using ReorientObject() for simple polygons. And have to write a little function for Multi-polygon or Donut shaped polygons.

## Steps to reproduce the problem.

using following command in OSGeo4W shell
ogr2ogr -overwrite -f MSSQLSpatial "MSSQL:server=111.123.45.67;database=MyDB;trusted_connection=yes;Driver={SQL Server Native Client 11.0}" "E:\MyFolder\\polygons.shp" -progress -nln "Polygons" -lco "GEOM_TYPE=geography" -lco "GEOM_NAME=Poly_Imported" -lco "SPATIAL_INDEX=No" -lco "PRECISION=No" -lco "LAUNDER=No" -gt 5000

## Operating system

Windows. I use OSGeo4W shell
SQL Server 2016 (well not OS but hope this help)

## GDAL version and provenance

Not sure but come with QGIS Desktop 3.10.2

**Comment by jratike80** [comment]
Isn't this a duplicate of https://github.com/OSGeo/gdal/issues/1128?

The core developers do not work much with MSSQL so it may be that you should try the workaround that I suggested. It is rather simple and it should work. There is also another function, ST_ForcePolygonCCW, that should be better http://www.gaia-gis.it/gaia-sins/spatialite-sql-latest.html and not reverse linestrings by the same but unfortunately Spatialite versions 4.3.0a and 5.0.0beta-0 do not know that. I sent a mail to the spatialite forum and asked why.

BTW there does  not seem to be any test concerning geography type in https://github.com/OSGeo/gdal/blob/master/autotest/ogr/ogr_mssqlspatial.py.

**Comment by qjohnchen** [comment]
Yes, it is a duplicate of #1128. 
As in #1128, we can fix it after polygons are upload to SQL.  
SQL Server's ReorientObject() function only works for simply polygon. I created my own ReorientObject to handle multi-polygon situation. No big deal. The problem is that I sometimes import millions of records. it take extra space and time do convert.

This is a great tool importing shape files. Hope the core developers can take a look and fix it. They already did the hard part and this seems to be a relative easy fix.

Sorry I am a new member of the Github. Should I closed this as it is a duplicate?

**Comment by jratike80** [comment]
It does not help to keep two similar bug reports open. Close this and refresh #1128 by adding your comments.

And try ogr2ogr with `-dialect SQLite -sql "select ST_Reverse(geometry), atrribute_1, attribute_2 from Land_Parcels"`
It does not take extra space and probably not much extra time either. I don't have MSSQL to test but it should work.

Common situation for all popular OS projects is that core developers have much more work to do than they have time.

**Comment by qjohnchen** [comment]
Close this as it is a duplicate of #1128.
I will try Jukka's suggestion first before put comments in #1128.
