### ISSUE TITLE
returned value from OGRGeometry::exportToKML() is ignore the numeric loacel rules (1.23 insetd of 1,23 , for example)

### ISSUE THREAD

**Issue by aharondavid** [OSGeo/gdal#3510]
## Expected behavior and actual behavior.

 returned value from OGRGeometry::exportToKML() is ignore the numeric loacel rules (1.23 insetd of 1,23 , for example)

## Steps to reproduce the problem.
1. In Windows 10, set reginal setting to Franch
2.  execute OGRGeometry::exportToKML()  on some Polygon Geometry

## Operating system

Windows 10

## GDAL version and provenance

GDAL 3.1.2

**Comment by rouault** [comment]
What is your issue exactly ? That the numeric local rules would be used to format polygon coordinates, which then results in invalid geometries ?

**Comment by aharondavid** [comment]
I expect to get from OGRGeometry::exportToKML()  the follwoing:
<-coordinate->
				-38,48397101218318 65,65363411404573 0 -9,376794037993131 72,20203876862733 0 -0,1467941780153781 66,34162990886387 0 -0,3401948324929682 61,80527715273607 0 -0,7089534164569056 61,50703125570862 0 -1,24304141437413 61,00924609925942 0 -8,115016054951653 56,98964286084907 0 -9,158859328321665 56,42293151438462 0 
			<-coordinate->
	
insted of:
		<-coordinate->
				-38.48397101218318,65.65363411404573,0 -9.376794037993131,72.20203876862733,0 -0.1467941780153781,66.34162990886387,0 -0.3401948324929682,61.80527715273607,0 -0.7089534164569056,61.50703125570862,0 -1.24304141437413,61.00924609925942,0 -8.115016054951653,56.98964286084907,0 -9.158859328321665,56.42293151438462,0 
			<-coordinate->

**Comment by jratike80** [comment]
That's invalid KLM. Decimal separator must be a point. If you want to create such KML I recommend to use some other tool than GDAL.

**Comment by aharondavid** [comment]
OK,
Thanks!
