### ISSUE TITLE
tWMS: flaky test

### ISSUE THREAD

**Issue by rouault** [OSGeo/gdal#3511]
CC @lucianpls The new WMS test with the GIBS server is flaky. See https://github.com/OSGeo/gdal/pull/3506/checks?check_run_id=2006511991 for example (but it has failed on a number of other configurations):
```
=================================== FAILURES ===================================
________________________________ test_twms_GIBS ________________________________

    def test_twms_GIBS():
    
        # if not gdaltest.run_slow_tests():
        #     pytest.skip()
        baseURL = "https://gibs.earthdata.nasa.gov/twms/epsg4326/best/twms.cgi?"
    
        try:
            subdatasets = gdaltest.subdatasets
        except:
            pytest.skip()
    
        # Connects to the server
        ds = gdal.Open(subdatasets['SUBDATASET_1_NAME'])
        if ds is None and gdaltest.gdalurlopen(baseURL + "request=GetTileService"):
>           pytest.fail()
E           Failed

/home/runner/work/gdal/gdal/autotest/gdrivers/wms.py:864: Failed
----------------------------- Captured stderr call -----------------------------
ERROR 1: GDAL_WMS TiledWMS:  No TiledGroup MODIS Terra CorrectedReflectance TrueColor tileset in server response.
ERROR 1: GDALWMS: Failed to initialize minidriver.
```

**Comment by lucianpls** [comment]
The tile group name is picked from the server response. The only way for this failure to happen is if the GIBS server responds with a different configuration on the two consecutive calls. It happened before, I'll try to duplicate this.

**Comment by mcechini** [comment]
Can you provide more information regarding the characteristics of "flaky."  It does look like we were failing back from our DR system yesterday around 2pm ET, which I believe correlates to when you were running your test.  Seems plausible that there was a hiccup as services were coming online.  I would be interested in knowing when else you see these issues.

**Comment by rouault** [comment]
I haven't seen the issue yesterday. Closing for now

**Comment by rouault** [comment]
Re-opening. We currently get issues on a number of CI config related to that server. I do get one locally on Ubuntu 20.04 :
```
$ curl -v "https://gibs.earthdata.nasa.gov/twms/epsg4326/best/twms.cgi?request=GetTileService"
*   Trying 2001:4d0:241a:442::5:443...
* TCP_NODELAY set
* Connected to gibs.earthdata.nasa.gov (2001:4d0:241a:442::5) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (OUT), TLS alert, handshake failure (552):
* error:1414D172:SSL routines:tls12_check_peer_sigalg:wrong signature type
* Closing connection 0
curl: (35) error:1414D172:SSL routines:tls12_check_peer_sigalg:wrong signature type
```
Also with wget, but not in Firefox or Chromium. Weird

**Comment by rouault** [comment]
Actually, the issue seems to be related to Ubuntu enforcing stronger SSL requirements for server keys. You should likely generate a stronger SSL key and install it.
