### ISSUE TITLE
DEP: Python 3.6 Support

### ISSUE THREAD

**Issue by snowman2** [OSGeo/gdal#3521]
EOL is December 2021: https://devguide.python.org/#status-of-python-branches

- numpy dropped support June 2020 [ref](https://numpy.org/neps/nep-0029-deprecation_policy.html)
- pandas dropped support June 2020 [ref](https://github.com/pandas-dev/pandas/issues/34472)
- xarray dropped support in 0.17.0 (http://xarray.pydata.org/en/stable/whats-new.html#breaking-changes)
- conda-forge support will be dropped soon [ref](https://github.com/conda-forge/rasterio-feedstock/pull/184#issuecomment-767161877)
- pyproj [ref](https://github.com/pyproj4/pyproj/issues/790)

**Comment by rcoup** [comment]
See [RFC77](https://gdal.orgdevelopment/rfc/rfc77_drop_python2_support.html) and the related tickets for discussion of supported Python versions.

It's likely we'll drop support for Python versions in GDAL releases after they are EOL'd either upstream or in OS releases that are important to GDAL users.

I don't see there's anything particularly actionable here?
