### ISSUE TITLE
ngw tests flaky

### ISSUE THREAD

**Issue by rouault** [OSGeo/gdal#3530]
This happens every few builds, like in https://github.com/OSGeo/gdal/pull/3529/checks?check_run_id=2034161164
CC @BishopGIS

**Comment by BishopGIS** [comment]
Looks like test failing on Mondays when sandbox restores the state.
It seems to me the problem in time zones or something similar: https://github.com/OSGeo/gdal/blob/master/autotest/gdrivers/ngw.py#L47-L50
I'm thinking to increase period or change sandbox availability checks.
