### ISSUE TITLE
"Fittofile" parameter for gdalwarp

### ISSUE THREAD

**Issue by swalterfub** [OSGeo/gdal#3534]
It would be nice to be able to fit a file to a specific reference file, in terms of projection and extent. The output file would then be pixel-aligned to the reference file.
I could contribute to that with a pull-request, but before doing the development, I'd like to ask if there is the possibility to include such a parameter in the official gdalwarp tool. If not, I'd probably stay with my Python version for that. Thanks for consideration!

**Comment by rouault** [comment]
Isn't it what "gdal_create -if template.tif output.tif" followed by "gdalwarp in.tif output.tif" would do ?

**Comment by jratike80** [comment]
Please test the suggestion. I would say that it does what you want to achieve.

**Comment by swalterfub** [comment]
Thank you for pointing me on this. I wasn't aware of the "-if" parameter for gdal_create. Yes indeed this is what I was asking for, it's acceptable for having a two-step workflow. There is one case where a "gdalwarp" option would still be more convenient, that is for a multi-spectral input file being matched to a single-band template file.

By the way, I answered to the second comment already 3 days ago and confirmed with "Close with comment", but now that I check back it was obviously not saved.

**Comment by jratike80** [comment]
You can use `-if` and override the band count with `-bands`.

**Comment by swalterfub** [comment]
Thanks that works as well!
