### ISSUE TITLE
Doc: missing paragraph pointing to bindings in other languages

### ISSUE THREAD

**Issue by rouault** [OSGeo/gdal#3539]
The sphinx doc lacks a page with the content of https://trac.osgeo.org/gdal#GDALOGRInOtherLanguages

**Comment by jonnyforestGIS** [comment]
@rouault make sense to add in here? https://gdal.org/api/index.html or do you have in my other pace? I can help with a PR adding the information.
Regards

**Comment by rouault** [comment]
> @rouault make sense to add in here? https://gdal.org/api/index.html

yes, I guess that could be a paragraph "Other languages" at the end of that page

**Comment by agiudiceandrea** [comment]
Was this issue fixed by https://github.com/OSGeo/gdal/pull/3544?

**Comment by rouault** [comment]
> Was this issue fixed by #3544?

yep
