### ISSUE TITLE
error: too many initializers for 'const sqlite3_module'

### ISSUE THREAD

**Issue by bcherkezovtf** [OSGeo/gdal#3547]
I'm receiving the following error when I try to build docker alpine small image for gdal >= 3

#11 1743.4 ogrsqlitevirtualogr.cpp:1720:1: error: too many initializers for 'const sqlite3_module'

**Comment by rouault** [comment]
Can you tell exactly how to reproduce the error ? The alpine small image builds fine for me, and I'd expect for anyone else...

**Comment by bcherkezovtf** [comment]
I'm building only the builder stage of the Dockerfile as a part of my custom file.
I'm using Alpine 3.12 and I'm trying to build  GDAL 3.0.2. The build fails with the above error message.

I'm running the build on MacOS.

**Comment by rouault** [comment]
This is a too custom case for us to support, and we only support GDAL >= 3.2 at this stage. Probably something to do with SQLite3. Closing as not upstream bug
