### ISSUE TITLE
如何安装

### ISSUE THREAD

**Issue by phpsxg** [OSGeo/gdal#3550]
using ICONV_CPP_CONST=""
configure: Bash completions not requested
checking for libtiff... checking for TIFFScanlineSize64 in -ltiff... no
using internal TIFF code.
checking for curl-config... no
checking for SQLite3 library >= 3.0.0... disabled
checking for PROJ >= 6 library... checking for proj_create_from_wkt in -lproj... no
checking for internal_proj_create_from_wkt in -lproj... no
checking for internal_proj_create_from_wkt in -linternalproj... no
configure: error: PROJ 6 symbols not found

**Comment by jratike80** [comment]
You certainly saw this informative message:

> IMPORTANT: Do NOT use GitHub to post any questions or support requests!
           They will be closed immediately and ignored.

GDAL is using GitHub for handling bugs. User questions should go to gdal-dev mailing list. Also gis.stackexchange site is often a good support forum.
