### ISSUE TITLE
GDAL 3.2.1 window (vs2019) Release has debug dependencies 

### ISSUE THREAD

**Issue by sagido123** [OSGeo/gdal#3551]
MSVCP140.dll
VCRUNTIME140D.dll
VCRUNTIME140_1D.dll

**Comment by jratike80** [comment]
If you mean the GDAL builds from gisinternals.com you should report the issue there. GDAL project does not maintain that site, even it is known to be very valuable for the GDAL community.

**Comment by mloskot** [comment]
Have mercy and submit something better than such shitty bug report!

**Comment by sagido123** [comment]
using  generate_vcxproj.bat 

[nmake.zip](https://github.com/OSGeo/gdal/files/6100786/nmake.zip)

**Comment by jratike80** [comment]
Are you referring to this source code package https://gisinternals.com/query.html?content=filelist&file=release-1928-x64-dev.zip?
