### ISSUE TITLE
GDAL 3.5: remove deprecated drivers and Perl bindings

### ISSUE THREAD

**Issue by rouault** [OSGeo/gdal#3555]
See https://lists.osgeo.org/pipermail/gdal-dev/2021-March/053590.html .
Except that ZMAP was removed from deprecation per #4086
Maybe except DODS: ticket about DODS driver: https://github.com/OSGeo/gdal/issues/5173
Add MDB to the list: https://github.com/OSGeo/gdal/issues/4311

**Comment by idanmiara** [comment]
Not that I use the Perl bindings, but I didn't see any correspondence for that in the attached email.
Are they going to be deprecated ?

**Comment by rouault** [comment]
See https://github.com/OSGeo/gdal/pull/3541

**Comment by rouault** [comment]
from from https://github.com/OSGeo/gdal/issues/5291 it seems GMT raster is still in use..
