### ISSUE TITLE
Do not put Python bindings generated files in git

### ISSUE THREAD

**Issue by rouault** [OSGeo/gdal#3562]
Having to regenerate them each time the interface .i files are modified is a bad practice and not intuitive for new contributors
Will require running SWIG in the CI configurations, Docker, etc.

**Comment by hobu** [comment]
To clarify, you want to regenerate the bindings for all CI and docker building tasks and remove them from the source tree? 👍 

Maybe this is the first step of moving the bindings OUT of GDAL 😄

**Comment by rouault** [comment]
> To clarify, you want to regenerate the bindings for all CI and docker building tasks and remove them from the source tree? +1

yes. mkgdaldist.sh will also likely be impacted

**Comment by theroggy** [comment]
I think this was inplemented in #7390

**Comment by rouault** [comment]
Closing as implemented
