### ISSUE TITLE
Issue with pcs.csv not found in GDAL data

### ISSUE THREAD

**Issue by nitin-a** [OSGeo/gdal#3567]
We are on RHEL v8 and having the below issue

fully unpacked and MD5 sums checked\nconfigure: R_HOME: /opt/R/3.5.2/lib/R\nconfigure: CC: gcc\nconfigure: CXX: g++\nconfigure: C++11 support available\nconfigure: rgdal: 1.3-6\nchecking for /usr/bin/svnversion... no\nconfigure: svn revision: 773\nchecking for gdal-config... /usr/bin/gdal-config\nchecking gdal-config usability... yes\nconfigure: GDAL: 3.0.4\nchecking GDAL version >= 1.11.4... yes\nchecking gdal: linking with --libs only... yes\nchecking GDAL: /usr/share/gdal/pcs.csv readable... no\nconfigure: error: pcs.csv not found in GDAL data
[Connect] Build error: An R package cannot be installed because a required system-level dependency is missing. (r-missing-system-library)

Have no clue what we need to install additionally.
R version 3.5.2
GDAL version 3.0.4

**Comment by rouault** [comment]
This is an issue with rgdal, not GDAL. Since GDAL 3, pcs.csv no longer exists.

**Comment by nitin-a** [comment]
Any recommendations on where should i post this issue. Thanks a lot for your help in advance

**Comment by rsbivand** [comment]
@nitin-a commented on a long-closed **sf** issue https://github.com/r-spatial/sf/issues/921#issuecomment-793739041. I replied: 

> GDAL 2.* need pcs.csv, GDAL 3.* do not use it at all. Almost certainly, you have multiple installs of GDAL on your system. See https://github.com/r-spatial/sf#multiple-gdal-geos-andor-proj-versions-on-your-system.

The declared GDAL version was 3.0.4, so I think at least two GDAL installs are present, and must be disambiguated. **sf** only looks for `pcs.csv` and throws an error if GDAL <= 2.5.0 https://github.com/r-spatial/sf/blob/ce439eb89cb9265f9bc2a2fb795d5422a6a24659/configure.ac#L207-L216. On my system with PROJ 8.0.0 and GDAL 3.2.2:
```
$ ls /usr/local/share/gdal/pcs.csv
ls: cannot access '/usr/local/share/gdal/pcs.csv': No such file or directory
$ ./configure
configure: CC: gcc
configure: CXX: g++ -std=gnu++11
checking for gdal-config... /usr/local/bin/gdal-config
checking gdal-config usability... yes
configure: GDAL: 3.2.2
checking GDAL version >= 2.0.1... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking gdal.h usability... yes
checking gdal.h presence... yes
checking for gdal.h... yes
checking GDAL: linking with --libs only... yes
checking GDAL: /usr/local/share/gdal/pcs.csv readable... no
checking GDAL: checking whether PROJ is available for linking:... yes
checking GDAL: checking whether PROJ is available fur running:... yes
configure: GDAL: 3.2.2
configure: pkg-config proj exists, will use it
configure: using proj.h.
configure: PROJ: 8.0.0
checking PROJ: checking whether PROJ and sqlite3 are available for linking:... yes
checking for geos-config... /usr/local/bin/geos-config
checking geos-config usability... yes
configure: GEOS: 3.9.1
checking GEOS version >= 3.4.0... yes
checking geos_c.h usability... yes
checking geos_c.h presence... yes
checking for geos_c.h... yes
checking geos: linking with -L/usr/local/lib -lgeos_c... yes
configure: Package CPP flags:   -DHAVE_PROJ_H -I/usr/local/include -I/usr/local/include
configure: Package LIBS: -L/usr/local/lib -lproj -lsqlite3 -ltiff -lcurl -lstdc++    -L/usr/local/lib -lgdal -L/usr/local/lib -lgeos_c
configure: creating ./config.status
config.status: creating src/Makevars
```
so the file is not found as expected and the script concludes successfully. If the script output is confusing, please say that that is your issue.

**Comment by rsbivand** [comment]
For **rgdal**, https://r-forge.r-project.org/scm/viewvc.php/pkg/configure.ac?root=rgdal&r1=828&r2=829 implemented the same condition as **sf** two years ago, and switched the configure test to `stateplane.csv` in November 2019 https://r-forge.r-project.org/scm/viewvc.php/pkg/configure.ac?root=rgdal&r1=882&r2=894 (**rgdal** has not tested for `pcs.csv` since then).

**Comment by nitin-a** [comment]
Thanks, @rsbivand  I will look into this suggestion. But much appreciated your suggestions.
