### ISSUE TITLE
Feathering of overlapping images in gdal_merge.py, gdalwarp or gdalbuildvrt

### ISSUE THREAD

**Issue by swalterfub** [OSGeo/gdal#3568]
Is it planned to implement feathering into one of the mosaic routines? That means, where images overlap, the pixels are blended over from one image to the other? This would be a very important and powerful feature to have, in my opinion.

**Comment by rouault** [comment]
gdalwarp with multiple input images can do that (or on update of an existing output image)

**Comment by swalterfub** [comment]
Thanks. I was looking for feathering, but I now found it under "blending".
