### ISSUE TITLE
 version

### ISSUE THREAD

**Issue by QgeXYZ** [OSGeo/gdal#3571]
## Expected behavior and actual behavior.

For example (please modify !!!): I expected to be able to open this raster file (with a link to
the raster file, or it as an attachment) and it returns an error message
instead.

## Steps to reproduce the problem.

For example (please modify !!!): "gdalinfo myfile"

## Operating system

For example (please modify !!!): Ubuntu 16.04 64 bit

## GDAL version and provenance

For example (please modify !!!): the 2.2.3 version from ubuntugis-unstable PPA

**Comment by mloskot** [comment]
You'll need to offer something better than a shitty report, including meaningful issue subject, exact command line, exact errors you're receiving, etc. IOW, a good report.

**Comment by QgeXYZ** [comment]
Sorry, I must have published an issue while not meaning it while reading an other one.

Best
