### ISSUE TITLE
[C#] geometry.IsValid  throw exception

### ISSUE THREAD

**Issue by gitlsl** [OSGeo/gdal#3578]
## Expected behavior and actual behavior.

I want to check geometry is valid

## Steps to reproduce the problem.
C# bingding code
````
    string wkt =
                @"MULTIPOLYGON (((88.596063218 21.882490585,88.596061621 21.8824907530001,88.596063218 21.882490585)),((88.596063218 21.882490585,88.596064798 21.882490665,88.596066347 21.882490988,88.596067828 21.8824915440001,88.596069206 21.882492321,88.596070449 21.8824933000001,88.596071512 21.882494437,88.59607239 21.882495722,88.596073065 21.882497125,88.596073519 21.882498614,88.596073744 21.8825001540001,88.59607378 21.882536927,88.596229059 21.882536814,88.596229015 21.8824906790001,88.596229199 21.882489809,88.596229521 21.8824889810001,88.596229973 21.8824882160001,88.596230543 21.8824875340001,88.59623886 21.8824869530001,88.596231974 21.882486488,88.596232797 21.8824861530001,88.596223835 21.882487203,88.596094435 21.8824872970001,88.596070527 21.882489815,88.596063218 21.882490585)))";

            var geometry = Ogr.CreateGeometryFromWkt(ref wkt, null);

            Console.WriteLine(geometry.IsValid());
/*
System.ApplicationException : IllegalArgumentException: Invalid number of points in LinearRing found 3 - must be 0 or >= 4
it should return false!
*/
````

## Operating system

win10 20h2 x64

## GDAL version and provenance

3.2.1  from `https://www.gisinternals.com/release.php`

**Comment by jratike80** [comment]
I consider that you asked a question "Why do I get an exception with this code" and you should have sent it to the mailing list. However, there may be some bug-alike elements as well.

I believe there are two things connected:

1) JTS and downstream GEOS do not accept a polygon that has a ring with only 3 points. See https://github.com/locationtech/jts/issues/558. That's the reason for the error. Other kind of topology errors, like ring self-intersection throw just warnings.

2) It seems that your code is using exceptions. Perhaps C# bindings behave in opposite way then Python ones which by default do not use exceptions https://gdal.org/api/python_gotchas.html. Maybe also C# bindings have the function `ogr.DontUseExceptions`. See the Python test below.

```
>>> ogr.DontUseExceptions()
>>> geom.IsValid()
ERROR 1: IllegalArgumentException: Invalid number of points in LinearRing found 3 - must be 0 or >= 4
False

>>> ogr.UseExceptions()
>>> geom.IsValid()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\OSGEO4~1\apps\Python37\lib\site-packages\osgeo\ogr.py", line 6656, in IsValid
    return _ogr.Geometry_IsValid(self, *args)
RuntimeError: IllegalArgumentException: Invalid number of points in LinearRing found 3 - must be 0 or >= 4
```

**Comment by dbaston** [comment]
GEOS will be updated to avoid throwing this error on a ring with 3 points: https://github.com/libgeos/geos/issues/406. However, it will continue to throw on 1-2 points. If GDAL isn't to throw an exception in that case (it seems like it shouldn't) then it would either need to do some validation on its own before handing the geometry over to GEOS, or it would need to catch the GEOS error and just return `false`. 

GDAL would need to validate the following:
- rings must be closed
- rings must have > 3 points (or >= 3 points for next GEOS version)
- polygon with an empty shell must not have holes
- lines must have 0 or > 1 points
- points must have 0 or 1 points
- all components of multipart geometries have declared type

I can put together a PR for this. Is there a preference on the approach?

**Comment by dbaston** [comment]
Making the changes I described would introduce a new problem, in which GDAL would happily report that the geometry is invalid and then throw an error when you take the logical next stop of calling MakeValid on it.

**Comment by jratike80** [comment]
How it has been done with other topology errors? Like self-intersections which are not valid but they are still acceptable:
```
>>> geom = ogr.CreateGeometryFromWkt('POLYGON ((-65 0, -30 -30, -30 0, -65 -30, -65 0))')
>>> geom.IsValid()
Warning 1: Self-intersection at or near point -47.5 -15
False
```
Is it so that GEOS geometry gets constructed only once some GEOS function is called, in this case IsValid?

**Comment by dbaston** [comment]
> Is it so that GEOS geometry gets constructed only once some GEOS function is called, in this case IsValid?

Yes, GDAL constructs and destroys a GEOS geometry for each GEOS operation. GEOS allows some types of invalid geometry to be constructed, but the conditions I listed above will cause GEOS to throw an error on construction.

**Comment by rouault** [comment]
I believe the only fix required here would probably to change the OGRGeometry::IsValid() implementation so that it creates a GEOSContext with ```initGEOS_r( OGRGEOSWarningHandler, OGRGEOSWarningHandler ); ``` so that a CPLError with the CE_Failure class is not emitted, which is the reason for the SWIG bindings to emit a Python/C# exceptions.
If the user then tries to call MakeValid() on those completely degenerate geometries that can't be repaired, he will get an exception, which is fine.
