### ISSUE TITLE
LVBAG Driver: autocorrecting invalid Pand/Building geometry renders non-Polygon types

### ISSUE THREAD

**Issue by justb4** [OSGeo/gdal#3581]
## Expected behavior and actual behavior.
Issue #3467 with PR #3531 assigned (correctly) a Polygon type as the Pand (Building) geometry-type as this is the official 
type in the BAG XSD.

When using `ogr2ogr` to write to e.g. PostGIS we now see the following errors:

    ogr2ogr -f PostgreSQL "PG:dbname=bagv2 host=bagv2_db port=5432 user=*** password=*** active_schema=bagactueel" -lco LAUNDER=YES -lco PREC\
    ISION=NO -lco FID=gid -lco SPATIAL_INDEX=NONE -append --config PG_USE_COPY YES -a_srs EPSG:28992 -gt 200000  -oo AUTOCORRECT_INVALID_DATA=YES -oo LEGACY_ID=YES temp/temp_dir
    Warning 1: Self-intersection at or near point 210444.6939819445 462183.56186922867
    Warning 1: Geometry to be inserted is of type Multi Polygon, whereas the layer geometry type is Polygon.
    Insertion is likely to fail
    ERROR 1: COPY statement failed.
    ERROR:  Geometry type (MultiPolygon) does not match column type (Polygon)
    CONTEXT:  COPY pand, line 28484, column wkb_geometry: "010600002040710000020000000103000000010000000A000000DD67468D65B00941A7A55A3F9E351C416ABC749391B00941..."
    ERROR 1: COPY statement failed.
    Warning 1: Self-intersection at or near point 192905.48699999999 426593.91399999999
    Warning 1: Geometry to be inserted is of type Geometry Collection, whereas the layer geometry type is Polygon.
    Insertion is likely to fail
    ERROR 1: COPY statement failed.
    ERROR:  Geometry type (GeometryCollection) does not match column type (Polygon)
    CONTEXT:  COPY pand, line 189263, column wkb_geometry: "0107000020407100000200000001030000000100000016000000894160E54B8C0741B29DEFA787091A4121B07268668C0741..."
  etc

This happens on the following conditions/settings:

* option `-oo AUTOCORRECT_INVALID_DATA=YES` (with `NO` only the self-intersection warnings)
* with the country-wide Dutch NL LV BAG source dataset (18 million building XML objects). Single city XML like Amsterdam and Rotterdam is ok, but by accident as no invalid geometry is present

## Steps to reproduce the problem.

I figured out an example failing `Pand/Building` object (there are many more). 
It has identifier `0147100000016964` (address Lavendel 7, 7621BL  Borne) and is present in the source file: 
`9999PND08112020-000185.xml` from the country dataset of March 15, 2021. But also was invalid in earlier versions.
FIltering out the relevant piece of source XML, is pasted here:

```
<?xml version="1.0" encoding="UTF-8"?>
<sl-bag-extract:bagStand xmlns:DatatypenNEN3610="www.kadaster.nl/schemas/lvbag/imbag/datatypennen3610/v20200601" xmlns:Objecten="www.kadaster.nl/schemas/lvbag/imbag/objecten/v20200601"
                         xmlns:gml="http://www.opengis.net/gml/3.2" xmlns:Historie="www.kadaster.nl/schemas/lvbag/imbag/historie/v20200601"
                         xmlns:Objecten-ref="www.kadaster.nl/schemas/lvbag/imbag/objecten-ref/v20200601" xmlns:nen5825="www.kadaster.nl/schemas/lvbag/imbag/nen5825/v20200601"
                         xmlns:KenmerkInOnderzoek="www.kadaster.nl/schemas/lvbag/imbag/kenmerkinonderzoek/v20200601"
                         xmlns:selecties-extract="http://www.kadaster.nl/schemas/lvbag/extract-selecties/v20200601"
                         xmlns:sl-bag-extract="http://www.kadaster.nl/schemas/lvbag/extract-deelbestand-lvc/v20200601" xmlns:sl="http://www.kadaster.nl/schemas/standlevering-generiek/1.0"
                         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema"
                         xsi:schemaLocation="http://www.kadaster.nl/schemas/lvbag/extract-deelbestand-lvc/v20200601 http://www.kadaster.nl/schemas/bag-verstrekkingen/extract-deelbestand-lvc/v20200601/BagvsExtractDeelbestandExtractLvc-2.1.0.xsd">
    <sl-bag-extract:bagInfo>
        <selecties-extract:Gebied-Registratief>
            <selecties-extract:Gebied-NLD/>
        </selecties-extract:Gebied-Registratief>
        <selecties-extract:LVC-Extract>
            <selecties-extract:StandTechnischeDatum>2020-11-08</selecties-extract:StandTechnischeDatum>
        </selecties-extract:LVC-Extract>
    </sl-bag-extract:bagInfo>
    <sl:standBestand>
        <sl:dataset>LVBAG</sl:dataset>
        <sl:inhoud>
            <sl:gebied>Nederland</sl:gebied>
            <sl:leveringsId>0000000001</sl:leveringsId>
            <sl:objectTypen>
                <sl:objectType>PND</sl:objectType>
            </sl:objectTypen>
        </sl:inhoud>
        <sl:stand>
            <sl-bag-extract:bagObject>
                <Objecten:Pand>
                    <Objecten:identificatie domein="NL.IMBAG.Pand">0147100000016964</Objecten:identificatie>
                    <Objecten:geometrie>
                        <!-- Invalid  also in PostGIS for self-intersection
                        SELECT ST_IsValidReason(ST_GeomFromText('POLYGON((247452.468 480187.571, 247453.262 480177.649, 247460.405 480177.914, 247459.876 480188.894, 247456.834 480188.629, 247456.834 480187.174, 247452.468 480187.306, 247452.468 480187.571))'));
                        Self-intersection[247452.489257842 480187.305357298]
                         -->
                        <gml:Polygon srsName="urn:ogc:def:crs:EPSG::28992" srsDimension="3">
                            <gml:exterior>
                                <gml:LinearRing>
                                    <gml:posList count="8">
                                        247452.468 480187.571 0.0
                                        247453.262 480177.649 0.0
                                        247460.405 480177.914 0.0
                                        247459.876 480188.894 0.0
                                        247456.834 480188.629 0.0
                                        247456.834 480187.174 0.0
                                        247452.468 480187.306 0.0
                                        247452.468 480187.571 0.0
                                    </gml:posList>
                                </gml:LinearRing>
                            </gml:exterior>
                        </gml:Polygon>
                    </Objecten:geometrie>
                    <Objecten:oorspronkelijkBouwjaar>1978</Objecten:oorspronkelijkBouwjaar>
                    <Objecten:status>Pand in gebruik</Objecten:status>
                    <Objecten:geconstateerd>N</Objecten:geconstateerd>
                    <Objecten:documentdatum>2018-11-20</Objecten:documentdatum>
                    <Objecten:documentnummer>18int04302</Objecten:documentnummer>
                    <Objecten:voorkomen>
                        <Historie:Voorkomen>
                            <Historie:voorkomenidentificatie>4</Historie:voorkomenidentificatie>
                            <Historie:beginGeldigheid>2018-11-20</Historie:beginGeldigheid>
                            <Historie:eindGeldigheid>2019-01-08</Historie:eindGeldigheid>
                            <Historie:tijdstipRegistratie>2018-11-21T11:47:47.000</Historie:tijdstipRegistratie>
                            <Historie:eindRegistratie>2019-01-09T09:44:04.000</Historie:eindRegistratie>
                            <Historie:BeschikbaarLV>
                                <Historie:tijdstipRegistratieLV>2018-11-21T12:00:45.948</Historie:tijdstipRegistratieLV>
                                <Historie:tijdstipEindRegistratieLV>2019-01-09T10:00:30.550</Historie:tijdstipEindRegistratieLV>
                            </Historie:BeschikbaarLV>
                        </Historie:Voorkomen>
                    </Objecten:voorkomen>
                </Objecten:Pand>
            </sl-bag-extract:bagObject>
        </sl:stand>

    </sl:standBestand>
</sl-bag-extract:bagStand>
```

* run this XML with e.g. `ogr2ogr` and the `AUTOCORRECT_INVALID_DATA=YES` option like above
* see the error `ERROR:  Geometry type (MultiPolygon) does not match column type (Polygon)`
* this error happened after Pand geometry type was made `Polygon` via Issue #3409 

## Analysis
The BAG data has always contained invalid geometry-data. Most, if not all, is present in "historic" records as above.
This may even be the reason to put these records in history.

What happens IMHO, when calling GEOS to repair/make valid the geometry a MultiPolygon or GeometryCollection is generated by GEOS which conflicts with the Pand type `Polygon`.

One can emulate this in PostGIS using the geometry data of the failing object:

```
SELECT ST_AsText(ST_MakeValid(ST_GeomFromText('POLYGON((247452.468 480187.571, 247453.262 480177.649, 247460.405 480177.914, 247459.876 480188.894, 247456.834 480188.629, 247456.834 480187.174, 247452.468 480187.306, 247452.468 480187.571))')));
```

This creates a PostGIS `Multipolygon` with this in upper left corner:

![image](https://user-images.githubusercontent.com/582630/111188304-36ce5a00-85b5-11eb-8430-caccaa978ff9.png)

The workaround is to set `AUTOCORRECT_INVALID_DATA=NO` and possibly fix in PostGIS itself, but the one looses also Date-type error corrections. 

## Operating system

Ubuntu 20 in Docker `gdal:ubuntu-small-latest`

## GDAL version and provenance

Latest with GEOS as on March 15, 2021 using Docker `gdal:ubuntu-small-latest` from DockerHub

**Comment by rouault** [comment]
You may use the -makevalid and -nlt PROMOTE_TO_MULTI flags of ogr2ogr to resolve this

**Comment by justb4** [comment]
Thanks @rouault , good to know these options. IMHO for the LVBAG Driver this will not apply, but @yorickdewid can possibly enlighten us: the LVBAG Driver defines Geometry types for all (7) BAG object types within the BAG Dataset. For `Pand`/Building this is Polygon. When  used as input the Driver parses the XML (with GML Namespaces for Geometries) and assigns the geom attribute to the OGR internal Feature datastruct.  There it optionally calls `Makevalid()`, which succeeds and renders a `MultiPolygon` (or `GeometryCollection`). This is then assigned, to the Polygon Geometry field. Better to show code and possibly some hints at fixes (my C++ is too rusty, otherwise I would PR).

The relevant code starts at [ogrlvbaglayer.cpp L637](https://github.com/OSGeo/gdal/blob/master/gdal/ogr/ogrsf_frmts/lvbag/ogrlvbaglayer.cpp#L637):

```
            std::unique_ptr<OGRGeometry> poGeom = std::unique_ptr<OGRGeometry>{
                reinterpret_cast<OGRGeometry *>(OGR_G_CreateFromGML(osElementString.c_str())) };
```
The geom is parsed from GML and assigned to `poGeom`. Invalid geom is optionally fixed:

```
                if( !poGeom->IsValid() && bFixInvalidData )
                {
                    std::unique_ptr<OGRGeometry> poSubGeom = std::unique_ptr<OGRGeometry>{
                        poGeom->MakeValid() };
                    if( poSubGeom && poSubGeom->IsValid() )
                        poGeom.reset(poSubGeom.release());
                }
```

[658](https://github.com/OSGeo/gdal/blob/master/gdal/ogr/ogrsf_frmts/lvbag/ogrlvbaglayer.cpp#L658): The geom field definition is gotten (in our case Polygon):

```
                OGRGeomFieldDefn *poGeomField = poFeatureDefn->GetGeomFieldDefn(0);
```
[664](https://github.com/OSGeo/gdal/blob/master/gdal/ogr/ogrsf_frmts/lvbag/ogrlvbaglayer.cpp#L664): a series of if/else statements to optionally recast/redefine `poGeom` based on its definition type in `poGeomField` and the actual geom. Most relevant:

```
                else if( poGeomField->GetType() == wkbMultiPolygon
                    && poGeom->getGeometryType() == wkbPolygon )
                {
                    std::unique_ptr<OGRMultiPolygon> poMultiPolygon = std::unique_ptr<OGRMultiPolygon>{ new OGRMultiPolygon };
                    poMultiPolygon->addGeometry(poGeom.get());
                    poGeom.reset(poMultiPolygon.release());
                }
                else if( poGeomField->GetType() == wkbMultiPolygon
                    && poGeom->getGeometryType() == wkbGeometryCollection
                    && poGeom->toGeometryCollection()->getNumGeometries() > 0
                    && poGeom->toGeometryCollection()->getGeometryRef(0)->getGeometryType() == wkbPolygon )
                {
                    std::unique_ptr<OGRMultiPolygon> poMultiPolygon = std::unique_ptr<OGRMultiPolygon>{ new OGRMultiPolygon };
                    for (auto &poChildGeom : poGeom->toGeometryCollection())
                        poMultiPolygon->addGeometry(poChildGeom);
                    poGeom.reset(poMultiPolygon.release());
                }
```

In "our" case, this condition applies:
```
 poGeomField->GetType() == wkbPolygon && ( poGeom->getGeometryType() == wkbGeometryCollection || 
poGeom->getGeometryType() == wkbMultiPolygon) 
```

These conditions "fall through" and at [707](https://github.com/OSGeo/gdal/blob/master/gdal/ogr/ogrsf_frmts/lvbag/ogrlvbaglayer.cpp#L707) poGeom is assigned from the unaltered geom leading to the error.

```
                m_poFeature->SetGeometryDirectly(poGeom.release());
```

But I don't know if `m_poFeature->SetGeometryDirectly()` verifies that it should only have a `Polygon` type actual param. The PostGIS output driver in our `ogr2ogr` command at least is not forcing any Field (geom) types. e.g. no GFS applies. But still it may happen there if the first copy/inserts are Polygon and then it chokes on a `MultiPolygon`....

What could be a fix is to generate a `GeometryCollection` of `Polygons` and assign the first `Polygon` to `poGeom`, or even better/advanced: assign the `Polygon` with the largest surface from the `GeometryCollection` (see picture above).

I hope this helps.
