### ISSUE TITLE
OGR2OGR ignores standard parallel when reprojecting

### ISSUE THREAD

**Issue by fcalef** [OSGeo/gdal#3594]
## Expected behavior and actual behavior.

I expected to be able to reprojection a GeoJSON file from an Equidistant Cylindrical projection with standard parallel defined (in our case 18.4663 degrees) to another geocentric coordinates (longitude/latitude). Example command:
**ogr2ogr -a_srs source.prj -t_srs destination.prj out.json in.shp**

where source.prj is
PROJCS["Jezero_Crater_Projection",GEOGCS["GCS_Mars_2000_Sphere",DATUM["D_Mars_2000_Sphere",SPHEROID["Mars_2000_Sphere",3396190.0,0.0]],PRIMEM["Reference_Meridian",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Equidistant_Cylindrical"],PARAMETER["False_Easting",0.0],PARAMETER["False_Northing",0.0],PARAMETER["Central_Meridian",0.0],PARAMETER["Standard_Parallel_1",18.4663],UNIT["Meter",1.0]]

and destination.prj is
GEOGCS["GCS_Mars_2000_sphere",DATUM["D_<custom>",SPHEROID["_custom",3396190.0,0.0]],PRIMEM["Reference_Meridian",0.0],UNIT["Degree",0.0174532925199433]]

Original units (one line from a geojson file create from a shapefile):
{ "type": "Feature", "properties": { "LEFT_FID": 0, "RIGHT_FID": 0, "Id": 0 }, "geometry": { "type": "LineString", "coordinates": [ [ 4354501.324, 1093313.544999999692664 ], [ 4354499.92100000102073, 1093372.065000000176951 ] ] } }

Output units should look like below (one line from GeoJSON)
{ "type": "Feature", "properties": { "LEFT_FID": 0, "RIGHT_FID": 0, "Id": 0, "Name": "Flight Path" }, "geometry": { "type": "LineString", "coordinates": [ [ 77.45101447, 18.4448608 ], [ 77.45098951, 18.44584807 ] ] } }

## Steps to reproduce the problem.

ogr2ogr -a_srs source.prj -t_srs destination.prj out.json in.shp

input coordinates (one line from a geojson file create from a shapefile)
{ "type": "Feature", "properties": { "LEFT_FID": 0, "RIGHT_FID": 0, "Id": 0 }, "geometry": { "type": "LineString", "coordinates": [ [ 4354501.324, 1093313.544999999692664 ], [ 4354499.92100000102073, 1093372.065000000176951 ] ] } }

results in incorrect longitude coordinates (one line from converted geojson):
{ "type": "Feature", "properties": { "LEFT_FID": 0, "RIGHT_FID": 0, "Id": 0, "Name": "Flight Path" }, "geometry": { "type": "LineString", "coordinates": [ [ 73.463071191343545, 18.444860803720164 ], [ 73.463047521884945, 18.445848071516469 ] ] } }

gdaltransform (v3.2.2) does correctly generate the correct longitude value using the same projections as above:
gdaltransform -s_srs source.prj -t_srs destination.prj
Enter X Y [Z [T]] values separated by space, and press Return.
4354499 1093306
77.4509731315987 18.4447335150065 0

## Operating system

Windows 10 Enterprise, Version 2004, OS Build 19041.867

## GDAL version and provenance

orgr2ogr --version
GDAL 3.2.2, released 2021/03/05

## Thoughts
Is GDAL/OGR2OGR forcing a strict adherence to the GeoJSON standard to be in WGS_84 (thereby an Earth radius)? In the planetary community, we need to be able to 'bend' the GeoJSON standard to non-Earth projections and other coordinate systems .

## Suggested solution
Allow the GeoJSON standard (WGS_84 coordinates only) to be modified with non-Earth geographic/geocentric coordinates OR provide a flag to override the standed.

**Comment by rouault** [comment]
> ogr2ogr -a_srs source.prj -t_srs destination.prj out.json in.shp

This is just a usage error. Should use -s_srs instead of -a_srs. This gives your expected result.
