### ISSUE TITLE
gdalinfo: /usr/pgsql-13/lib/libpq.so.5: no version information available (required by /lib64/libgdal.so.27)

### ISSUE THREAD

**Issue by askonivala** [OSGeo/gdal#3596]
## Expected behavior and actual behavior.

After installation of postgres 13 and postgis 3.1, my gdal is broken. After running `gdalinfo --version` gdal crashes:

```
gdalinfo: /usr/pgsql-13/lib/libpq.so.5: no version information available (required by /lib64/libgdal.so.27)
GDAL 3.1.4, released 2020/10/20
Segmentation fault (core dumped)
```

This might be related to conflicting Fedora packages/libraries or it is a bug in gdal.

## Operating system

Fedora 33 with postgres 13 and postgis 3.1. Postgres version: https://download.postgresql.org/pub/repos/yum/reporpms/F-33-x86_64/pgdg-fedora-repo-latest.noarch.rpm

## GDAL version and provenance

Package gdal-3.1.4-2.fc33.x86_64 (Fedora).

**Comment by rouault** [comment]
Yes, this is likely a conflict between the base Fedora repository and the download.postgresql.org one. Not something we can address at upstream level. You may need to rebuild the GDAL package from the src rpm against the updated postgresql.
