### ISSUE TITLE
Add tolerance/threshold to contours

### ISSUE THREAD

**Issue by mimi89999** [OSGeo/gdal#3602]
## Expected behavior and actual behavior.

A setting should be added that makes it possible to add some tolerance/threshold for what color changes are a change in value

## Steps to reproduce the problem.

Make contours form a map that has a texture instead of a plain color for a value. Notice that the texture will be treated as a change in value. The color diff between parts the texture is very small and between values big. It should be possible make contours ignore very small color changes.

![Capture d’écran de 2021-03-21 22-31-56](https://user-images.githubusercontent.com/8530546/111922223-f715df80-8a98-11eb-9dce-f21609c8b248.png)
![Capture d’écran de 2021-03-21 22-32-04](https://user-images.githubusercontent.com/8530546/111922224-f7ae7600-8a98-11eb-8b73-91fd2131b6b7.png)

## Operating system

Debian Bullseye

## GDAL version and provenance

`3.2.1+dfsg-1+b1`

**Comment by hobu** [comment]
This appears to be some kind of QGIS issue. `gdal_contour` does not deal with anything other than the creation of lines with values.

**Comment by mimi89999** [comment]
I know, but it created too many limes because of the small color difference on the texture.

**Comment by jratike80** [comment]
The normal source data for contours is digital elevation model. You seem to use something like digital topographic map or alike. Nothing wrong with that but gdal_contour is definitely not designed for such usage.

**Comment by mimi89999** [comment]
Could you recommend me another FOSS tool to do that? Could gdal contour be adapted to work with such maps?

**Comment by jratike80** [comment]
I would try if people who follow gis.stackexchange happens to have experience on working with such data. Classification programs like eCognition (not open source) can certainly deal pretty well with uniform textures.
