### ISSUE TITLE
Warp resampling does not appear to respect pixel density change.

### ISSUE THREAD

**Issue by JesseRMeyer** [OSGeo/gdal#3610]
## Expected behavior and actual behavior.
I expect the change in area density during resampling to be respected.  More generally, I expect the dataset's band's sum to be reasonably 'conserved' after resampling.  

In the instance below, warp() does not appear to account for the change in area density during upsampling.  Cubic and bilinear resampling techniques have been tested to show the behavior.  I am measuring a similar issue with downsampling as well.  I can open a new ticket for that if necessary but this appears to be a more general problem.

How should I provide our input image for your verification?

## Steps to reproduce the problem.
Below is a minimal reproduction of the problem.  The output from the various print() functions have been inlined.

```python
from numpy import uint64

from osgeo import gdal
gdal.UseExceptions()

# Sum 128m^2 ds
src_ds = gdal.Open('/path_to_image/source_128.tif')
assert src_ds

src_gt = src_ds.GetGeoTransform() # Already projected into UTM

assert src_gt[1] == 128
assert src_gt[5] == -128

# Compute raster sum.
src_band = src_ds.GetRasterBand(1)

src_arr = src_ds.ReadAsArray()
assert src_band.GetNoDataValue() == 65_535
src_arr[src_arr == 65_535] = 0 # Do not count no-data values.
src_sum = src_arr.sum(dtype=uint64)

print(src_sum) #886,013,110

# Upsample to 1ha (100m^2) texel size
dst_ds = gdal.Warp('', src_ds, format='MEM', xRes=100, yRes=100, resampleAlg='cubic')
assert dst_ds

dst_gt = dst_ds.GetGeoTransform()
assert dst_gt[1] == 100
assert dst_gt[5] == -100

#Compute warp upsampled raster sum
dst_band = dst_ds.GetRasterBand(1)
dst_arr = dst_band.ReadAsArray()
assert dst_band.GetNoDataValue() == 65_535
dst_arr[dst_arr == 65_535] = 0 # As above.
dst_sum = dst_arr.sum(dtype=uint64)

print(dst_sum) # 1,450,621,791

print(dst_sum / src_sum) # 1.6372
print(128**2 / 100**2) # Propotion of src texel to dst area density ... 1.6384
```

## Operating system
SUSE Linux Enterprise Server 11
OSX 10.15.7
We have a Windows 10 machine to test if helpful.

## GDAL version and provenance
Gdal version: 3.2.1

**Comment by jratike80** [comment]
I am an amateur in resampling so could you link some reference implementation, or article, that shows how to do it right? I would also like to know what pixel density means.

Are you sure that bilinear and cubic methods can maintain the sums like you suppose in your test? Both methods seem to introduce some smoothing https://pro.arcgis.com/en/pro-app/latest/tool-reference/environment-settings/resampling-method.htm. 

If you are scientifically minded there was an interesting mail thread about resampling a few years ago http://osgeo-org.1560.x6.nabble.com/gdal-dev-downsampling-geotiff-with-a-low-pass-filter-td5385890.html.

**Comment by rouault** [comment]
cubic and bilinear won't / can't maintain the sum. You should use average instead, and with recent GDAL versions, and when no reprojection is involved. With integer data types, you won't get perfect preservation too.

**Comment by JesseRMeyer** [comment]
Hi jratike80,

I have not inspected GDAL's resampling code carefully and am not sure how this case is specifically handled.  I am not a digital signal researcher and cannot handily point to formal arguments in my defense.  At the least, this issue is to highlight the surprise in what was produced.  I am willing to be educated that my expectations are unreasonable. :)

By density, I mean the area the pixel covers (and thereby the area sampled to produce that value).    I am not expecting complete conservation.  Resampling with finite resources is often a juggle of lossy encoding strategies.  But you can imagine my surprise in seeing the resampled value overreport the sum value by a whopping 1.6x -- nearly exactly the change in proportion of area in the transformation.

**Comment by rouault** [comment]
> Can you confirm for me that an increase of 1.6x in the sum after resampling is what you would have expected in this instance?

absolutely. this is totally expected. bicubic, bilinear are interpolation methods to build a continuous field from a discrete set of values. They have absolutely no total sum preservation property.

my remark about average preserving the sum will only be valid when downsampling, at least in the current implementation. When upsampling, if for a given target pixel there's only one or less source pixel, its value will be propagated unmodified.

**Comment by JesseRMeyer** [comment]
Thanks for the explanation!

Is there any significance to how strongly correlated the change in pixel size is to the change in sum?  Is there interest in providing an improved interpolation method that extends the simple family of, bi cubic/linear, etc, that accounts for changes in pixel size (as opposed to what appears to just blindly interpolate with those pixels which so happen to be neighbors at the new size?)

**Comment by jratike80** [comment]
If you have a totally flat raster the correlation is certainly strong. With weighted methods the deviation in the source data has an effect on the change of sum.
Isn't average the method you are searching for?

I do not believe we have a BI interpolation method (blind interpolation). Algorithms are based on mathematically defined methods.

**Comment by rouault** [comment]
> Is there any significance to how strongly correlated the change in pixel size is to the change in sum?

should roughly be the same as the ratio in source / target pixel areas as you noted

> Is there interest in providing an improved interpolation method that extends the simple family of, bi cubic/linear, etc, that accounts for changes in pixel size (as opposed to what appears to just blindly interpolate those pixels which so happen to be neighbors at the new size?)

We use methods well known in the litterature and used in other GIS or imaging processing. I'm not aware of a sum preserving bicubic being used and what its usefulness would be.

Closing this ticket

**Comment by JesseRMeyer** [comment]
@jratike80  
> Isn't average the method you are searching for?

This may be the best approximation of what I'm searching for.  It will depend on how source pixels that only partially overlap the destination pixel are weighed in their averaging contribution.  Thanks for your links, they were helpful to read through.

**Comment by JesseRMeyer** [comment]
@jratike80 
> Isn't average the method you are searching for?

After testing, the average method suffers from exactly the same problem.
