### ISSUE TITLE
Missing js in doxygen documentation

### ISSUE THREAD

**Issue by jjimenezshaw** [OSGeo/gdal#3619]
The documentation in Doxygen has some toggles that expand elements like parent class. They do not work.
See an example in `|>  Public Member Functions inherited from GDALMajorObject`
https://gdal.org/doxygen/classGDALRasterBand.html

The browser console error is
```
classGDALRasterBand.html:246 Uncaught ReferenceError: toggleInherit is not defined
    at HTMLTableCellElement.onclick (classGDALRasterBand.html:246)
```
Having a look at the html code, I see that it should be loading the file `dynsections.js`, but it is not there. I assume that this file contains the missing javascript code.

I found a similar problem in this other project
https://gitlab.kitware.com/vtk/vtk/-/issues/17472

They fixed it this way: "This has been fixed by bumping the doxygen version from 1.8.11 to 1.8.16"

I am not sure where do we generate the doxygen documentation, I guess in Ubuntu 18.04.
If this is the case, it is probably doxygen 1.8.13, based on https://packages.ubuntu.com/search?keywords=doxygen

Maybe it is fixed just moving it to Ubuntu 20.04, that uses doxygen 1.8.17 (just based on the comment in "vtk").

Note: running manually `make html` in `gdal/doc` in my Ubuntu 20.04 produces the html where the toggle works.

**Comment by rouault** [comment]
The toggle now works
