### ISSUE TITLE
ESRI shp file cannot open by gdal

### ISSUE THREAD

**Issue by Gitookps** [OSGeo/gdal#363]
## Expected behavior and actual behavior.

I expected to be able to open an ESRI shape file  and it returns a None type instead.

## Steps to reproduce the problem.

the code is simple, which is attached below:
import osgeo.gdal
import ogr
ogr.RegisterAll()
dataset = ogr.Open('river.shp',0)
print type(dataset)
## Operating system
MacOS 10.13.4

## GDAL version and provenance
1.10.1 installed in Anaconda 5.0.1 by 'conda install gdal'

**Comment by rouault** [comment]
Can you attach the shapefile or provide a link to it ? I'd note that GDAL 1.10 is largely outdated ! (but it should be able to open a shapefile fine)

**Comment by rouault** [comment]
@Gitookps See above comment. We need a dataset to check if your report is legit or not

**Comment by rouault** [comment]
Closing due to lack of feedback. Please re-open if you have more elements to provide to us
