### ISSUE TITLE
GML driver ignoring provided XSD

### ISSUE THREAD

**Issue by mlalis** [OSGeo/gdal#3634]
## Expected behavior and actual behavior.

Hi,
I am attempting to use ogr2ogr to convert a GML file to GeoJSON with a specified XSD. The XSD I'm trying to use is the AIXM 5.1 schema which can be found here: https://aixm.aero/document/aixm-51-xml-schema-xsd 

I expected to be able to set the XSD open option to this XSD and parse my data accordingly, but when running the command with debug turned on, I see a message stating that the XSD is being ignored and a .gfs file is being created instead: "GML: Generating aixm_file.gfs file, ignoring /Users/mlalis/Repos/AIXM/flask-api/resources/aixm51xsd/message/AIXM_BasicMessage.xsd".  There is no indication as to why the XSD is being ignored, and I have had success reading it with other drivers (GMLAS in particular), so I am certain that the XSD file can be accessed from the location where I am running the command.  

I've tried changing the XSD option to point to the https location (https://www.aixm.aero/schema/5.1/message/AIXM_BasicMessage.xsd) instead of a local file and received the same output. 

Note that I am still able to get a GeoJSON output, but it is missing fields that are in the original XML file and that are defined in the AIXM 5.1 XSD. 

## Steps to reproduce the problem.

This is the full command I am running: `ogr2ogr -f GeoJSON aixm_file.json aixm_file.xml --debug on --config GML_SWAP_COORDINATES NO -oo XSD=/Users/mlalis/Repos/AIXM/flask-api/resources/aixm51xsd/message/AIXM_BasicMessage.xsd`

And this is the full output: 
```
GML: Using Expat reader
GML: Generating aixm_file.gfs file, ignoring /Users/mlalis/Repos/AIXM/flask-api/resources/aixm51xsd/message/AIXM_BasicMessage.xsd
GDAL: GDALOpen(aixm_file.xml, this=0x7fdbdad47d70) succeeds as GML.
GDAL: GDALDriver::Create(GeoJSON,aixm_file.json,0,0,0,Unknown,0x0)
GML: ResetReading()
GML: ResetReading()
GDALVectorTranslate: 665 features written in layer 'VerticalStructure'
GDAL: GDALClose(aixm_file.xml, this=0x7fdbdad47d70)
GDAL: GDALClose(aixm_file.json, this=0x7fdbdad49f30)
GDAL: In GDALDestroy - unloading GDAL shared library.
```

## Operating system

macOS Catalina Version 10.15.7

## GDAL version and provenance

GDAL 3.2.0, released 2020/10/26, installed using Homebrew `brew install gdal`

**Comment by rouault** [comment]
The GML driver can only understand .xsd that use features of the GML Simple Feature profile. AIXM is more complex than that. Using the GMLAS driver is appropriate for such cases

**Comment by mlalis** [comment]
That is good to know. Is the GMLAS driver compatible with the GeoJSON driver? I tried to do the conversion to GeoJSON using the GMLAS driver, but received warnings and errors which made me think it would not be compatible. It is possible that I am missing some config or open options that would make it work properly

**Comment by rouault** [comment]
the GMLAS driver will report generally a lot of layers (use the REMOVE_UNUSED_LAYERS=YES open option to reduce that number to only those used in the dataset) . The GeoJSON driver can only write one layer at a time. So you neeed to do several ogr2ogr invokation by selectin which layer you want to convert to GeoJSON.
