### ISSUE TITLE
ogr2ogr converted DXF file lost Global width property

### ISSUE THREAD

**Issue by kbumsik** [OSGeo/gdal#3636]
## Expected behavior and actual behavior.

This is how the original DXF looks like. The Polylines here have "Global Width" property so the lines are thick.
 
![original_dxf](https://user-images.githubusercontent.com/7823583/113401529-73d08400-93de-11eb-9887-0045972e2e47.png)

I reprojected the DXF to a different CRS.

```
ogr2ogr -skipfailures -f DXF -s_srs EPSG:5186 -t_srs EPSG:3857 test_ogr2ogr.dxf test.dxf
```

Then the polylines lost "Global Width" property so the lines become thin...

![reprojected_dxf](https://user-images.githubusercontent.com/7823583/113401755-db86cf00-93de-11eb-8fd2-b9e1bbb3bbcd.png)

## Steps to reproduce the problem.

Get the DXF file:
[test.zip](https://github.com/OSGeo/gdal/files/6248730/test.zip)

run the following command:

```
ogr2ogr -skipfailures -f DXF -s_srs EPSG:5186 -t_srs EPSG:3857 test_ogr2ogr.dxf test.dxf
```

Then the converted DXF loose the "Global Width" property. This is the output file.
[test_ogr2ogr.zip](https://github.com/OSGeo/gdal/files/6248732/test_ogr2ogr.zip)

## Operating system

Ubuntu 20.04 LTS

## GDAL version and provenance

Installed from ubuntugis stable PPA
```
ogr2ogr --version
GDAL 3.2.1, released 2020/12/29
```

**Comment by rouault** [comment]
CC @atlight

**Comment by atlight** [comment]
The lack of support for polyline width in our DXF driver is a [known issue](https://github.com/OSGeo/gdal/blob/master/gdal/ogr/ogrsf_frmts/dxf/KNOWN_ISSUES.md#lwpolyline). I don't intend to fix this myself, but code contributions are always welcome.
