### ISSUE TITLE
GetSpatialRef returns None value after second call

### ISSUE THREAD

**Issue by habibutsu** [OSGeo/gdal#3642]
```python
In [96]: import gdal

In [97]: gdal.VersionInfo()
Out[97]: '3000400'

In [98]: ds = gdal.Open('/vsis3/sentinel-s1-l1c/GRD/2021/1/17/IW/DV/S1B_IW_GRDH_1SDV_20210117T234523_20210117T234548_025201_030026_D7A5/measurement/iw-vh.tiff')

In [99]: ds.GetSpatialRef()
Out[99]: <osgeo.osr.SpatialReference; proxy of <Swig Object of type 'OSRSpatialReferenceShadow *' at 0x7f41e64c9660> >

In [100]: ds.GetSpatialRef()

In [101]: !uname -a
Linux habibutsu 5.3.0-64-generic #58-Ubuntu SMP Fri Jul 10 19:33:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Actual behavior:**  method `GetSpatialRef` returns `None` value after second call
**Expected behavior:** method `GetSpatialRef` returns reference to object every time

**Comment by rouault** [comment]
Actually the bug is that GetSpatialRef() returns a non-null object at the first call. As this dataset has GCPs and not geotransform, GetSpatialRef() should return null and GetGCPSpatialRef() non-null.
More consistant behaviour with https://github.com/OSGeo/gdal/pull/3643
