### ISSUE TITLE
How to resolve "gdalinfo failed - unable to open /vsihdfs/hdfs://"?

### ISSUE THREAD

**Issue by JenniferYingyiWu2020** [OSGeo/gdal#3655]
Hi,
    I have tried several times through the command "gdalinfo /vsihdfs/hdfs://..." or "gdalinfo hdfs://..." or "gdal.Open('hdfs://...')", the errors "ERROR 4: /vsihdfs/hdfs://...: No such file or directory
gdalinfo failed - unable to open '/vsihdfs/hdfs://...'." still exist.
However, the "gdalinfo" can access the local file successfully.
    For the preparation of my testing, the three conda environments has been created.
    Firstly, I install the latest GDAL using conda under the first "conda environment":
![1](https://user-images.githubusercontent.com/72843232/113802729-ca96de80-978d-11eb-9c85-33fca802be34.png)
![2](https://user-images.githubusercontent.com/72843232/113802738-cec2fc00-978d-11eb-95d9-90e70251896c.png)
![3](https://user-images.githubusercontent.com/72843232/113802743-d1bdec80-978d-11eb-9b21-1316596a5711.png)
![4](https://user-images.githubusercontent.com/72843232/113802755-d71b3700-978d-11eb-94a8-f97cd910225f.png)
![5](https://user-images.githubusercontent.com/72843232/113802761-dbdfeb00-978d-11eb-9492-46f11885c485.png)
![6](https://user-images.githubusercontent.com/72843232/113802773-df737200-978d-11eb-996b-947e93b3b382.png)
    Then,  I change to install GDAL from source code under the second "conda environment":
![21](https://user-images.githubusercontent.com/72843232/113802809-ef8b5180-978d-11eb-9624-01620f3f6bdd.png)
![22](https://user-images.githubusercontent.com/72843232/113802824-f31ed880-978d-11eb-85a2-a7cf0d1b0879.png)
![23](https://user-images.githubusercontent.com/72843232/113802833-f619c900-978d-11eb-8d47-2dea6716ff90.png)
![24](https://user-images.githubusercontent.com/72843232/113802844-fa45e680-978d-11eb-8ee8-23947cd4c612.png)
![25](https://user-images.githubusercontent.com/72843232/113802854-fdd96d80-978d-11eb-85a5-593de54b3649.png)
    Lastly, under my local hadoop user environment, the GDAL that is the version of 2.4.4 has been installed using "conda" under the third "conda environment":
![31](https://user-images.githubusercontent.com/72843232/113802940-26f9fe00-978e-11eb-82fd-4a203c1c6b9d.png)
![32](https://user-images.githubusercontent.com/72843232/113802955-2bbeb200-978e-11eb-95b6-3b57e391fd92.png)
![33](https://user-images.githubusercontent.com/72843232/113802959-2e210c00-978e-11eb-9b19-6272076bae07.png)
![34](https://user-images.githubusercontent.com/72843232/113802963-31b49300-978e-11eb-86ac-d81a744a4628.png)
![35](https://user-images.githubusercontent.com/72843232/113802975-37aa7400-978e-11eb-85dc-eb778c9ec2bb.png)
![36](https://user-images.githubusercontent.com/72843232/113803651-945a5e80-978f-11eb-9f0c-29454d9248b6.png)

    So, could you pls help to give me some suggestions? Thanks!

**Comment by jratike80** [comment]
You should use the mailing list for asking questions even it may be more convenient to use GitHub bug tracker especially with screen captures.

Hadoop is strange to me but try what is suggested in https://stackoverflow.com/questions/53416174/open-a-raster-in-hdfs-using-gdal.

**Comment by rouault** [comment]
The open syntax of the /vsihdfs/ (Java based, likely not in standard conda build) file system is at https://gdal.org/user/virtual_file_systems.html#vsihdfs-hadoop-file-system
And the one of /vsiwebhdfs/ (using libcurl, in Conda) is at https://gdal.org/user/virtual_file_systems.html#vsiwebhdfs-web-hadoop-file-system-rest-api
gdalinfo "hdfs://" will never work

**Comment by JenniferYingyiWu2020** [comment]
Hi,
    Now, the shell command "gdalinfo /vsihdfs/hdfs://.../..tif" can be executed successfully.
![1](https://user-images.githubusercontent.com/72843232/113965359-c935e680-985f-11eb-898c-f747133a24c3.png)
    However, when I changed to Python3 command line environment, the "gdal.Open('/vsihdfs/hdfs://.../..tif)" made the below error appear:
ERROR 4: /vsihdfs/hdfs://.../...tif: No such file or directory


    So, could you pls help to give me some suggestions? Thanks!
