### ISSUE TITLE
gdal_merge rgb tifs,result washed out color

### ISSUE THREAD

**Issue by jiangnight** [OSGeo/gdal#3673]
![washedout](https://user-images.githubusercontent.com/23185222/114330963-7e74e100-9b75-11eb-9f91-8fa3d412bcc7.png)

## Operating system

win10  64 bit

## GDAL version and provenance
3.1.4

**Comment by jratike80** [comment]
Please do not ask questions in the bug tracker.
By reading the question in the gis.stackexchange the result of the merge is a 4 band image. QGIS is using the fourth band as an alpha/transparency band. Select only 3 bands to be used as RGB with QGIS settings and image should look bright.
