### ISSUE TITLE
ogr2ogr /vsistdout/ for certain drivers (dxf, gpkg, ...)

### ISSUE THREAD

**Issue by faridcher** [OSGeo/gdal#3675]
- According to the documentation most file based drivers support "large file API" and hence could use virtual file systems. The `v` in the list of formats further confirms it.

```sh
~/subdiv ogrinfo --formats | grep -E 'gpkg|dxf|geojson|kml'
  LIBKML -vector- (rw+v): Keyhole Markup Language (LIBKML)
  KML -vector- (rw+v): Keyhole Markup Language (KML)
  GeoJSON -vector- (rw+v): GeoJSON
  GeoJSONSeq -vector- (rw+v): GeoJSON Sequence
  GPKG -raster,vector- (rw+vs): GeoPackage
  DXF -vector- (rw+v): AutoCAD DXF
```

However, /vsistdout/ seems to only be supported for gml/kml/geojson/csv output format but not with dxf/gpkg/'esri shapefile' format. Lack of support for [Shapefile](http://osgeo-org.1560.x6.nabble.com/gdal-dev-Piping-ogr2ogr-SHP-format-vsistdout-to-unix-command-td5389350.html) format makes sense since it is a multi-file format but not for gpkg or dxf! Is there any peculiarity to the /vsistdout/? If so, I think, this should be documented at a driver's page manual. 

```sh
echo a,b |\
  \ogr2ogr -dialect sqlite \
  -sql 'select "GDAL is great" F1, GeomFromText("POINT(0 0)") geom' \
  -f gml /vsistdout/ csv:/vsistdin/

<?xml version="1.0" encoding="utf-8" ?>
<ogr:FeatureCollection
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="http://ogr.maptools.org/ .xsd"
     xmlns:ogr="http://ogr.maptools.org/"
     xmlns:gml="http://www.opengis.net/gml">
  <gml:boundedBy><gml:null>missing</gml:null></gml:boundedBy>
  <gml:featureMember>
    <ogr:SELECT fid="SELECT.0">
      <ogr:geom><gml:Point><gml:coordinates>0,0</gml:coordinates></gml:Point></ogr:geom>
      <ogr:F1>GDAL is great</ogr:F1>
    </ogr:SELECT>
  </gml:featureMember>
</ogr:FeatureCollection>

echo a,b |\
  \ogr2ogr -dialect sqlite \
  -sql 'select "GDAL is great" F1, GeomFromText("POINT(0 0)") geom' \
  -f dxf /vsistdout/ csv:/vsistdin/

ERROR 6: Read or update mode not supported on /vsistdout
ERROR 4: Failed to open '/vsistdout/' for writing: 
ERROR 1: dxf driver failed to create /vsistdout/
```

related discusion:
https://trac.osgeo.org/gdal/ticket/4226

**Comment by rouault** [comment]
In general drivers that support /vsistdout/ indicates so. It is more the exception than the rule. Generating geopackage and DXF require random-write access which is not compatible with /vsistdout/
