### ISSUE TITLE
GDAL 3.x: CoordinateTransformation() doesn't work for some projections

### ISSUE THREAD

**Issue by mobigroup** [OSGeo/gdal#3677]
On MacOS 10.15.7 the script below returns (inf, inf, inf) (inf, inf, inf) while it's works for other projections:
```
from osgeo import gdal
from osgeo.osr import SpatialReference, CoordinateTransformation

projection = 'PROJCS["MODIS Sinusoidal",GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4326"]],PROJECTION["Sinusoidal"],PARAMETER["longitude_of_center",0],PARAMETER["false_easting",0],PARAMETER["false_northing",0],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AXIS["Easting",EAST],AXIS["Northing",NORTH]]'
source = SpatialReference()
source.ImportFromWkt(projection)

dest = SpatialReference()
dest.ImportFromEPSG(4326)

transform = CoordinateTransformation(source, dest)

x, y = -20014877.698, 10007323.021
print (transform.TransformPoint(x, y), transform.TransformPoint(y, x))
```
Note: here reverse x, y coordinates order added for GDAL 2.x compability.

**Comment by rouault** [comment]
your point is likely outside the validity area of the projection

**Comment by mobigroup** [comment]
@rouault It's valid coordinate and you need to check it first before closing the ticket:
```
echo "-20014877.698, 10007323.021" | gdaltransform -s_srs EPSG:6842 -t_srs WGS84
140.652814726436 7.33447383181857 0
```

**Comment by EvertEt** [comment]
The EPSG in your example above does not seem to match the WKT in your example as they give different results:
```
from osgeo.osr import SpatialReference, CoordinateTransformation

source_epsg = SpatialReference()
source_epsg.ImportFromEPSG(6842)

projection = 'PROJCS["MODIS Sinusoidal",GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4326"]],PROJECTION["Sinusoidal"],PARAMETER["longitude_of_center",0],PARAMETER["false_easting",0],PARAMETER["false_northing",0],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AXIS["Easting",EAST],AXIS["Northing",NORTH]]'
source_wkt = SpatialReference()
source_wkt.ImportFromWkt(projection)


dest = SpatialReference()
dest.ImportFromEPSG(4326)


transform_epsg = CoordinateTransformation(source_epsg, dest)
transform_wkt = CoordinateTransformation(source_wkt, dest)


x, y = -20014877.698, 10007323.021
print (transform_epsg.TransformPoint(x, y), transform_epsg.TransformPoint(y, x))
print (transform_wkt.TransformPoint(x, y), transform_wkt.TransformPoint(y, x))

```

```
(7.334473831818574, 140.65281472643647, 0.0) (-17.735340465200434, -25.40717404220627, 0.0)
(inf, inf, inf) (inf, inf, inf)

```

**Comment by mobigroup** [comment]
This is the dataset:
https://developers.google.com/earth-engine/datasets/catalog/MODIS_006_MOD17A3HGF
and GDAL is able to transform the raster:
```
gdalwarp -t_srs WGS84 2000_02_18.tif 2000_02_18.wgs84.tif
```
but we can't use it's WKT projection definition in the script above:
```
gdal.Open('2000_02_18.tif').GetProjection()
```

**Comment by mobigroup** [comment]
@EvertEt 
This is MODIS Sinusoidal projection:
https://spatialreference.org/ref/sr-org/modis-sinusoidal-3/
for the MODIS dataset
https://developers.google.com/earth-engine/datasets/catalog/MODIS_006_MOD17A3HGF

**Comment by EvertEt** [comment]
https://spatialreference.org/ref/sr-org/modis-sinusoidal-3/json/ does say it is a different EPSG then you linked above. Not sure where the difference is

**Comment by mobigroup** [comment]
@EvertEt The same file can be converted to WGS84 by console GDAL tools with all valid coordinates:
```
gdalwarp -ts 1000 1000 -t_srs WGS84 2000_02_18.tif 2000_02_18.wgs84.tif

gdalinfo 2000_02_18.wgs84.tif
Driver: GTiff/GeoTIFF
Files: 2000_02_18.wgs84.tif
Size is 1000, 1000
Coordinate System is:
GEOGCRS["WGS 84",
    DATUM["World Geodetic System 1984",
        ELLIPSOID["WGS 84",6378137,298.257223563,
            LENGTHUNIT["metre",1]]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["degree",0.0174532925199433]],
    CS[ellipsoidal,2],
        AXIS["geodetic latitude (Lat)",north,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433]],
        AXIS["geodetic longitude (Lon)",east,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433]],
    ID["EPSG",4326]]
Data axis to CRS axis mapping: 2,1
Origin = (-179.999999139816452,88.258073062558083)
Pixel Size = (0.359999458281589,-0.176515247510649)
Metadata:
  AREA_OR_POINT=Area
  google=max_source_file_timestamp=1609511724000
Image Structure Metadata:
  INTERLEAVE=PIXEL
Corner Coordinates:
Upper Left  (-179.9999991,  88.2580731) (180d 0' 0.00"W, 88d15'29.06"N)
Lower Left  (-179.9999991, -88.2571744) (180d 0' 0.00"W, 88d15'25.83"S)
Upper Right ( 179.9994591,  88.2580731) (179d59'58.05"E, 88d15'29.06"N)
Lower Right ( 179.9994591, -88.2571744) (179d59'58.05"E, 88d15'25.83"S)
Center      (  -0.0002700,   0.0004493) (  0d 0' 0.97"W,  0d 0' 1.62"N)
Band 1 Block=1000x2 Type=Int16, ColorInterp=Gray
  Description = Npp
Band 2 Block=1000x2 Type=Int16, ColorInterp=Undefined
  Description = Npp_QC
```

and for the original file:
```
gdalinfo 2000_02_18.tif
Driver: GTiff/GeoTIFF
Files: 2000_02_18.tif
Size is 86400, 43200
Coordinate System is:
PROJCRS["MODIS Sinusoidal",
    BASEGEOGCRS["WGS 84",
        DATUM["World Geodetic System 1984",
            ELLIPSOID["WGS 84",6378137,298.257223563,
                LENGTHUNIT["metre",1]]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433]],
        ID["EPSG",4326]],
    CONVERSION["Sinusoidal",
        METHOD["Sinusoidal"],
        PARAMETER["Longitude of natural origin",0,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["False easting",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["easting",east,
            ORDER[1],
            LENGTHUNIT["metre",1,
                ID["EPSG",9001]]],
        AXIS["northing",north,
            ORDER[2],
            LENGTHUNIT["metre",1,
                ID["EPSG",9001]]]]
Data axis to CRS axis mapping: 1,2
Origin = (-20015109.353987999260426,10007554.676993999630213)
Pixel Size = (463.312716527916507,-463.312716527499902)
Metadata:
  AREA_OR_POINT=Area
  google=max_source_file_timestamp=1609511724000
Image Structure Metadata:
  INTERLEAVE=PIXEL
Corner Coordinates:
Upper Left  (-20015109.354,10007554.677) 
Lower Left  (-20015109.354,-10007554.677) 
Upper Right (20015109.354,10007554.677) 
Lower Right (20015109.354,-10007554.677) 
Center      (   0.0000180,   0.0000000) (  0d 0' 0.00"E,  0d 0' 0.00"N)
Band 1 Block=86400x1 Type=Int16, ColorInterp=Gray
  Description = Npp
Band 2 Block=86400x1 Type=Int16, ColorInterp=Undefined
  Description = Npp_QC
```

**Comment by mobigroup** [comment]
@EvertEt 
> https://spatialreference.org/ref/sr-org/modis-sinusoidal-3/json/ does say it is a different EPSG then you linked above. Not sure where the difference is

Although there are 3 MODIS Sinusoidal projections with minor modifications:
https://spatialreference.org/ref/?search=MODIS+Sinusoidal
SR-ORG:6842: MODIS Sinusoidal
SR-ORG:6965: MODIS Sinusoidal
SR-ORG:6974: MODIS Sinusoidal
and only the first one is available in GDAL.

**Comment by jratike80** [comment]
Result from my test:

```
gdaltest>gdaltransform -s_srs test.prj -t_srs epsg:4326 --debug on
Enter X Y [Z [T]] values separated by space, and press Return.
-20014877.698 10007323.021
OGRCT: tolerance condition error
transformation failed.
```

I have no idea about what is that tolerance condition error.

**Comment by rouault** [comment]
> I have no idea about what is that tolerance condition error.

typically emitted by PROJ when transforming points outside of the validity domain

**Comment by mobigroup** [comment]
@rouault 
Global MODIS Sinusoidal projection (https://spatialreference.org/ref/sr-org/6842/) is global, yes:
> WGS84 Bounds: -180.0000, -82.3089, 180.0000, 89.6831
Projected Bounds: -2275822.9000, -9152341.5816, 2097942.4893, 9972315.0495

But we have the projection error when we try to reproject "Origin" point of the raster with modis.prj copied from the recent projection definition (https://spatialreference.org/ref/sr-org/6974/) by
```
echo "-20015109.353987999260426 10007554.676993999630213" \
| gdaltransform --debug on -s_srs modis.prj -t_srs WGS84 
transformation failed.
```

At the same time, we are still able to transform it by GDAL tools:
```
gdalwarp --debug on --config GDAL_CACHEMAX 30000 \
-s_srs modis.prj -t_srs WGS84 2000_02_18.tif 2000_02_18.wgs84.tif
```
There are no processing errors and the output is correct:
```
gdalinfo 2000_02_18.wgs84.tif
Driver: GTiff/GeoTIFF
Files: 2000_02_18.wgs84.tif
Size is 86733, 42527
Coordinate System is:
GEOGCRS["WGS 84",
...
Origin = (-179.999999139816452,88.258073062558083)
Pixel Size = (0.004150663049607,-0.004150663049607)
...
Corner Coordinates:
Upper Left  (-179.9999991,  88.2580731) (180d 0' 0.00"W, 88d15'29.06"N)
Lower Left  (-179.9999991, -88.2571744) (180d 0' 0.00"W, 88d15'25.83"S)
Upper Right ( 179.9994591,  88.2580731) (179d59'58.05"E, 88d15'29.06"N)
Lower Right ( 179.9994591, -88.2571744) (179d59'58.05"E, 88d15'25.83"S)
Center      (  -0.0002700,   0.0004493) (  0d 0' 0.97"W,  0d 0' 1.62"N)
...
```
Let's compare to the original one:
```
gdalinfo 2000_02_18.tif
Driver: GTiff/GeoTIFF
Files: 2000_02_18.tif
Size is 86400, 43200
Coordinate System is:
PROJCRS["MODIS Sinusoidal",
...
Origin = (-20015109.353987999260426,10007554.676993999630213)
Pixel Size = (463.312716527916507,-463.312716527499902)
...
Corner Coordinates:
Upper Left  (-20015109.354,10007554.677) 
Lower Left  (-20015109.354,-10007554.677) 
Upper Right (20015109.354,10007554.677) 
Lower Right (20015109.354,-10007554.677) 
...
```

As you see, the origin point is converted successfully from
Origin = (-20015109.353987999260426,10007554.676993999630213)
to
Origin = (-179.999999139816452,88.258073062558083)

**Comment by jratike80** [comment]
If projected bounds are `Projected Bounds: -2275822.9000, -9152341.5816, 2097942.4893, 9972315.0495`
then the y-coordinate of the test point `echo "-20015109.353987999260426 10007554.676993999630213"`
is out of bounds.

However, are these numbers checked to be consistent?
```
WGS84 Bounds: -180.0000, -82.3089, 180.0000, 89.6831
Projected Bounds: -2275822.9000, -9152341.5816, 2097942.4893, 9972315.0495
```

Is is a success to run this conversion when the result seems to be pretty much wrong (88.25 degrees converts into a value that is larger than the maximum 9972315, that should stand for 89.6831?

```
Origin = (-20015109.353987999260426,10007554.676993999630213)
to
Origin = (-179.999999139816452,88.258073062558083)
```

**Comment by mobigroup** [comment]
@jratike80 
> If projected bounds are Projected Bounds: -2275822.9000, -9152341.5816, 2097942.4893, 9972315.0495
then the y-coordinate of the test point echo "-20015109.353987999260426 10007554.676993999630213" is out of bounds.

Do you compare x,y coordinates separately? That doesn't work for many coordinates systems.

**Comment by jratike80** [comment]
I do not understand what you mean. If valid minY is  -9152341.5816 and valid maxY is 9972315.0495 and the y of the test point is 10007554 then it is out of bounds with any value of x coordinate.

**Comment by mobigroup** [comment]
@jratike80 

You wrongly equate "Projected Bounds" to maximum and minimum coordinates. Projected bounds mean projected WGS84 Bounds only. Projection of some point inside the WGS84 bounds might be outside of the projected WGS84 bounds points because the coordinate transformation is not linear.

**Comment by rouault** [comment]
> > 
> 
> But we have the projection error when we try to reproject "Origin" point of the raster with modis.prj copied from the recent projection definition (https://spatialreference.org/ref/sr-org/6974/) by

The projected bounds is the bounding box of the projected domain, but there are points within this bounding box that do not belong to the projected domain. gdalwarp has logic to skip those. But when using gdaltransform you transform point by point, and when there is no solution for a point, it logically can't display an output.
Look at the chart at https://proj.org/operations/projections/sinu.html. The point you try to transform would be at the top-left corner of the chart, outside the projection domain.

**Comment by jratike80** [comment]
You may be right but still am still suspicious with the value 10007554 and that it located as far South as 88.25 degrees. It does not convert back with your projection.

 


How about the inverse projection with your reference point:
```
gdaltransform -t_srs test.prj -s_srs epsg:4326 --debug on
Enter X Y [Z [T]] values separated by space, and press Return.
-179.999999139816452 88.258073062558083
-611140.848655246 9807403.58345412 0
```

It differs quite a lot from -20015109.353987999260426,10007554.676993999630213 

But this point with Y value 9807403.583454 does convert back to 88.25 degrees.

```
gdaltransform -s_srs test.prj -t_srs epsg:4326 --debug on
Enter X Y [Z [T]] values separated by space, and press Return.
-611140.848655246 9807403.58345412 0
-179.999999139819 88.2580730625581 0
```

Could you imagine that there is any, even tiny chance that you are wrong with the validity of 10007554 as Y/North coordinate?

**Comment by mobigroup** [comment]
@jratike80 
First, you use outdated projection definition https://spatialreference.org/ref/sr-org/6842/ instead of the recent one which results I included above. This projection has limited definition area but it’s extended to global in the next two definitions. Anyway, it doesn’t work as expected.
Second, this projection different in GDAL when we call it by EPSG code and produces weird results when we use it’s WKT definition. When I printed the projection name from Python GDAL code it shows some local projection instead of the defined one. But again, it should work when it’s defined by WKT but it doesn’t as I see.
Third, the recent projection definition is global without limits https://spatialreference.org/ref/sr-org/6974/ but it doesn’t work with gdalwarp while it works with gdaltransform as I explained above. Here we can’t use EPSG code because it’s missed in available projections list and need to use WKT definition only but it still doesn’t work properly.

P.S. As I remember, Modis sinusoidal projection is broken in GDAL for many years (not sure, maybe I’ve already reported same issues 10-15 years ago).

**Comment by jratike80** [comment]
I used the WKT string that you used in the original question. This is a long and messy thread, could you please edit the question and add the alternative WKT string into the question? I would not be surprised by being wrong because I am just another GDAL user and this is my first experience ever about the Modis sinusoidal.

Do you have any other, not Proj and GDAL based, reference about what is the correct result when converting Modis coordinates (-20015109.353987999260426,10007554.676993999630213) into EPSG:4326? I can have a try with ArcGIS Pro once you have attached the WKT that you want me to test.

I could find some tickets from that time but perhaps not exactly about this issue.
https://trac.osgeo.org/gdal/query?status=assigned&status=closed&status=new&status=reopened&description=~Modis&order=id
https://trac.osgeo.org/gdal/query?status=assigned&status=closed&status=new&status=reopened&description=~sinusoidal&order=id
