### ISSUE TITLE
OGR GML Reader : error on CircleByCenterPoint with uom in kilometers

### ISSUE THREAD

**Issue by olivegak971** [OSGeo/gdal#3686]
Parsing this piece of GML code (extract from Aviation AIXM data) with **GDAL 3.1.4** leads to generate a wrong geometry :

`<aixm:Surface srsName="urn:ogc:def:crs:EPSG::4326" gml:id="id.98dc2683-1bd8-4a1d-882f-014288ba51a7">
                                            <gml:patches>
                                                <gml:PolygonPatch interpolation="planar">
                                                    <gml:exterior>
                                                        <gml:Ring>
                                                            <gml:curveMember xlink:type="simple">
                                                                <gml:Curve srsName="urn:ogc:def:crs:EPSG::4326" gml:id="id.c3079e23-1331-4aab-ac72-050221db93da">
                                                                    <gml:segments>
                                                                        <gml:CircleByCenterPoint interpolation="circularArcCenterPointWithRadius" numArc="1">
                                                                            <gml:pos>47.233333333 0.166666667</gml:pos>
                                                                            <gml:radius uom="km">5.0</gml:radius>
                                                                        </gml:CircleByCenterPoint>
                                                                    </gml:segments>
                                                                </gml:Curve>
                                                            </gml:curveMember>
                                                        </gml:Ring>
                                                    </gml:exterior>
                                                </gml:PolygonPatch>
                                            </gml:patches>
                                        </aixm:Surface>`
 
When I change the uom with "**[nmi_i]**" or even "**m**", it generates the **expected** geometry.
It seems "**km**" is not recognized and therefore GDAL assumes a radius of 5 deg by default (I checked that on QGIS, as the measure of the circle radius equals to 300 NM, aka 5*60 NM).

Result of ogrinfo command (only beginning) when _uom="km"_ is used : 
_Layer name: Airspace
Geometry: **Curve Polygon**
Feature Count: 1
Extent: (42.233333, -4.833333) - (52.233333, 5.166667)_

Result of ogrinfo command (beginning only with one feature in the GML file) when _uom="[nmi_i]" or uom="m"_ is used : 
_Layer name: Airspace
Geometry: **Polygon**
Feature Count: 1
Extent: (47.188333, 0.100433) - (47.278333, 0.232901)_

**Comment by jratike80** [comment]
See https://github.com/OSGeo/gdal/issues/3118 and test with a newer GDAL version.
