### ISSUE TITLE
VFK driver: suppress geometry

### ISSUE THREAD

**Issue by landam** [OSGeo/gdal#371]
## Expected behavior and actual behavior.

VFK driver resolves features' geometry by default. It can be time-consuming task when reading huge VFK files. Some of users are not interested at features geometries. It would be reasonable to add new open option to suppress resolving geometry. Than all reported layers would have wkbNone type.

**Comment by rouault** [comment]
I don't know if you have considered it, but a user can set the ignored flag on a geometry field definition  (can be done with OGR_FD_SetGeometryIgnored, OGR_GFld_SetIgnored or OGR_L_SetIgnoredFields) and the driver could use that hint to avoid reading the geometries. That's for example what QGIS does when it displays the attribute table on a layer ( https://github.com/qgis/QGIS/blob/fcacb0db7ca56fd4bc1c27c0fea788df5b55c24c/src/providers/ogr/qgsogrprovider.cpp#L1033 ). But there's no trivial way of doing that through ogr2ogr if that's your use case, so the open option is reasonable. Just wanted to mention other possibilities

**Comment by landam** [comment]
Thanks for hint. Yes, ogr2ogr is an issue.

**Comment by rouault** [comment]
Ticket ready to be closed ?

**Comment by landam** [comment]
I performed some tests. Closing.
