### ISSUE TITLE
CI: Unable to find package Microsoft.NETCore.App in windows_build.yml

### ISSUE THREAD

**Issue by rouault** [OSGeo/gdal#3711]
@bjornharrtell @szekerest  Starting today, we get an error "D:\a\gdal\gdal\gdal\swig\csharp\apps\ogrinfo.csproj : error NU1101: Unable to find package Microsoft.NETCore.App. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages" in .github/workflows/windows_build.yml : https://github.com/OSGeo/gdal/pull/3710/checks?check_run_id=2400373159

any idea how to fix that?

**Comment by rouault** [comment]
There's a ``NETCORE = netcoreapp2.1`` default value in swig/csharp/makefile.vc  . Eithat that could/should be changed, or overriding it in the nmake.local file generated in windows_build.yml

**Comment by bjornharrtell** [comment]
I've made https://github.com/OSGeo/gdal/pull/3712 and I'll check up on what CI says about it.

**Comment by bjornharrtell** [comment]
Doesn't appear to help. The error is refering to "Microsoft Visual Studio Offline Packages" as the source of dependencies and I'm not sure what that is but it appears to not have what was and is needed.
