### ISSUE TITLE
Incorrect encoding used when reading DXF in C#

### ISSUE THREAD

**Issue by YaroslavKormushyn** [OSGeo/gdal#3716]
## Summary

I'm trying to query a DXF file for its layers using the [gdal.netcore](https://github.com/MaxRev-Dev/gdal.netcore) wrapper. It's using the `sql` option of `ogrinfo` under the hood. My file has characters like `ä`, which are not properly returned. I don't see an option to specify the encoding when opening a file.

I tested this using the command line `ogrinfo` and got a similar result, where the characters were not properly displayed.

My DXF file is in UTF-8 and opening it in VS Code works fine with the characters displayed just fine. I'm thinking this is related to the default code page on my machine.

## Expected behavior and actual behavior.

Expected: DXF file opened in UTF-8 and queries return properly decoded values.
Actual: DXF file opened in ISO-8859-1 and queries return invalid decoded values.

## Steps to reproduce the problem.

Run `ogrinfo d7d5eadd-40c6-480d-afbc-8e41fd1e2099.dxf -sql "select distinct layer from entities"` using [this file](https://github.com/OSGeo/gdal/files/6358005/d7d5eadd-40c6-480d-afbc-8e41fd1e2099.zip).

This is similar to using this code snippet with [this library](https://github.com/MaxRev-Dev/gdal.netcore):

```csharp
using var dxfDriver = Ogr.GetDriverByName("DXF");
using var ds = dxfDriver.Open(dxfFilePath, 0);
using var layersQuery = ds.ExecuteSQL("select distinct layer from entities", null, null);
var count = (int)layersQuery.GetFeatureCount(0);
var features = Enumerable.Range(0, count).Select(index => layer.GetFeature(index)).ToArray();

var fixBrokenEncoding = false;
return features
      .Select(feature => fixBrokenEncoding
          ? Encoding.UTF8.GetString(Encoding.GetEncoding("iso-8859-1").GetBytes(feature.GetFieldAsString("layer")))
          : feature.GetFieldAsString("layer"))
      .ToArray();
```

By using the `fixBrokenEncoding=true` path I'm able to re-decode the values properly, but that means I'll need some way to find the encoding `ogrinfo` is using to read this. It would be much simpler if I could tell ogrinfo which encoding to use.

## Operating system

Windows 10 64 bit

## GDAL version and provenance

3.2.0 stable ([more info here](https://github.com/MaxRev-Dev/gdal.netcore#about-build-configuration))

**Comment by rouault** [comment]
CC @atlight

**Comment by atlight** [comment]
@YaroslavKormushyn can you confirm you have seen https://gdal.org/drivers/vector/dxf.html#character-encodings? You might need to set the `DXF_ENCODING` configuration option (I'm not familiar with how to do that on the C# bindings).

**Comment by jratike80** [comment]
The DXF file seems to  announce this code page
```
$DWGCODEPAGE
  3
ANSI_1251
```
It is not the most common to use for Swedish but I do not know it is matters.

**Comment by YaroslavKormushyn** [comment]
@jratike80 you are definitely right, I needed to set the `DXF_ENCODING` option to the one announced on the code page. I completely missed the encoding section of the DXF driver documentation.

**Comment by YaroslavKormushyn** [comment]
Thank you so much!
I'll close this, thanks for the help.

**Comment by pessimo** [comment]
> @YaroslavKormushyn can you confirm you have seen https://gdal.org/drivers/vector/dxf.html#character-encodings? You might need to set the `DXF_ENCODING` configuration option (I'm not familiar with how to do that on the C# bindings).

Hi, did you know how to set that in python?
I got mac ventura, python3.8, gdal 3.6.3 and when I'm trying to set DXF_ENCODING in the following code, I got error, it told me there's no option as DXF_ENCODING

```python
from osgeo import ogr
dxf_path = r"path/to/file.dxf"

dxf_driver = ogr.GetDriverByName("DXF")
dxf_driver.Register()
dxf_datasource = dxf_driver.Open(dxf_path, DXF_ENCODING='UTF8') 

layer = dxf_datasource.GetLayer()
```

**Comment by rouault** [comment]
> I got mac ventura, python3.8, gdal 3.6.3 and when I'm trying to set DXF_ENCODING in the following code, I got error, it told me there's no option as DXF_ENCODING

gdal.SetConfigOption("DXF_ENCODING", "UTF-8")
