### ISSUE TITLE
[Python] gdal install uses a non default python path

### ISSUE THREAD

**Issue by jgrocha** [OSGeo/gdal#3735]
## Expected behavior and actual behavior.

On new Ubuntu 20.04 deployment, the default Python path is:
```
$ python3
Python 3.8.5 (default, Jan 27 2021, 15:41:15) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.path
[
'', 
'/usr/lib/python38.zip', 
'/usr/lib/python3.8', 
'/usr/lib/python3.8/lib-dynload', 
'/home/jgr/.local/lib/python3.8/site-packages', 
'/usr/local/lib/python3.8/dist-packages', 
'/usr/lib/python3/dist-packages']
```
This default **does not include** `/usr/local/lib/python3/dist-packages`.

If I compile and install gdal, the Python generated libraries goes to:
```
/usr/local/lib/python3/dist-packages/
``` 
### Actual behavior
In a new instance, without changing the PYTHONPATH, gdal is not available:
```
python3
Python 3.8.5 (default, Jan 27 2021, 15:41:15) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from osgeo import gdal
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'osgeo'
>>> 
```
Of course, setting the PYTHONPATH works:
```
$ PYTHONPATH='/usr/local/lib/python3/dist-packages/' python3
Python 3.8.5 (default, Jan 27 2021, 15:41:15) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from osgeo import gdal
>>> print(gdal.__file__)
/usr/local/lib/python3/dist-packages/osgeo/gdal.py
```
## Steps to reproduce the problem.

* Install Ubuntu :-)
* Compile gdal with python
* Install gdal
* Use gdal python library will fail, if PYTHONPATH is not setup

## Operating system

Only tested on Ubuntu 20.04.

## GDAL version and provenance

GDAL compiled with `--with-python=python3`

**Comment by rouault** [comment]
Python module installation is basically voodoo science. This is related to commit 8cae2eb0696 (PR https://github.com/OSGeo/gdal/pull/65 ) with invokes "python3 setup.py install --install-layout=deb". 
If, from swig/python, you do ``python3 setup.py install  --prefix=/usr/local``, it will install in /usr/local/lib/python3.8/dist-packages/

**Comment by jgrocha** [comment]
Thanks for the feedback @rouault 

Running just `python3 setup.py install` should output it to `/usr/local/lib/python3.8/dist-packages`. According to the [python documentation](https://docs.python.org/3/install/) the default installation folder in Unix should be `/usr/local/lib/pythonX.Y/site-packages`. The same is written in [Debian Python Documentation Project](https://debian-python.readthedocs.io/en/latest/debian-policy.html).

We are doing this currently:
```python3
Python 3.8.5 (default, Jan 27 2021, 15:41:15) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from distutils.sysconfig import get_python_lib
>>> get_python_lib()
'/usr/lib/python3/dist-packages'
```

I would say that this is (a|the) correct way of finding the library.

An alternative way, which works is:
```python3
Python 3.8.5 (default, Jan 27 2021, 15:41:15) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import site
>>> site.getsitepackages()[0]
'/usr/local/lib/python3.8/dist-packages'
```
Is this second way better? I do not know. I'm not a a voodoo expert ;-)

**Comment by jgrocha** [comment]
Let's keep this issue open while we think about an alternative to `distutils`. Distutils is now deprecated (see [PEP 632](https://www.python.org/dev/peps/pep-0632/)) since [Jan, 2021](https://mail.python.org/archives/list/python-dev@python.org/thread/TXU6TVOMBLQU3SV57DMMOA5Y2E67AW7P/).

**Comment by rouault** [comment]
closing as probably outdated by all CMake related changes
