### ISSUE TITLE
请问搭载m1芯片的MacBook支持gdal吗

### ISSUE THREAD

**Issue by EdwinIZ8** [OSGeo/gdal#3737]
## Expected behavior and actual behavior.

我的电脑是搭载m1芯片的MacBook Air电脑，需要使用gdal打开和处理数据。但是，gdal支持m1芯片的MacBook Air吗？

## Operating system

macOS big sur

## GDAL version and provenance

任何版本都行。

**Comment by rouault** [comment]
translation: "My computer is a MacBook Air computer with m1 chip, and I need to use gdal to open and process data. But, does gdal support MacBook Air with m1 chip? "

As indicated in the issue template, Questions should go (in English) to the gdal-dev mailing list at https://lists.osgeo.org/mailman/listinfo/gdal-dev or other support forums. GitHub issues are for bug reports and suggestions for new features.

如問題模板中所示，問題應（英語）發送到位於https://lists.osgeo.org/mailman/listinfo/gdal-dev或其他支持論壇的gdal-dev郵件列表。 GitHub問題是關於錯誤報告和新功能的建議。
