### ISSUE TITLE
Python - No module named '_gdal_array' on two different computers

### ISSUE THREAD

**Issue by John2397** [OSGeo/gdal#3744]
The error `No module named '_gdal_array'` appears when I run any code that uses the `_gdal_array` .

For example, if I just type `from osgeo import gdalnumeric` this is what I get:

        Python 3.6.8 (default, Feb  3 2021, 18:30:24) 
	[GCC 9.3.0] on linux
	Type "help", "copyright", "credits" or "license" for more information.
	>>> from osgeo import gdalnumeric
	Traceback (most recent call last):
	  File ""/.../venv/lib/python3.6/site-packages/osgeo/gdal_array.py", line 18, in swig_import_helper
	    fp, pathname, description = imp.find_module('_gdal_array', [dirname(__file__)])
	  File "/usr/local/lib/python3.6/imp.py", line 297, in find_module
	    raise ImportError(_ERR_MSG.format(name), name=name)
	ImportError: No module named '_gdal_array'

	During handling of the above exception, another exception occurred:

	Traceback (most recent call last):
	  File "<stdin>", line 1, in <module>
	  File "/.../venv/lib/python3.6/site-packages/osgeo/gdalnumeric.py", line 2, in <module>
	    from osgeo.gdal_array import *
	  File "/.../venv/lib/python3.6/site-packages/osgeo/gdal_array.py", line 28, in <module>
	    _gdal_array = swig_import_helper()
	  File "/.../venv/lib/python3.6/site-packages/osgeo/gdal_array.py", line 20, in swig_import_helper
	    import _gdal_array
	ModuleNotFoundError: No module named '_gdal_array'
	>>> 

Other answers suggest to download `numpy` but I already have it installed.
I tried uninstalling both gdal and numpy and reinstalling them again without success.
Also tried older numpy versions.

I use Ubuntu 20, `Gdal==3.0.4` and `numpy==1.19.5`
I thought maybe there is a conflict with another package and tried it on another computer with the same specs as above, and had the same result.

My question is what causes the above error and how could I take care of it?

**Comment by rouault** [comment]
you need to install the python3-numpy apt package when building the bindings to have the gdal_array module to be built. Having just the numpy pip module is not enoguh

**Comment by John2397** [comment]
@rouault thank you for the response. I also have already installed the `python3-numpy` package.
However I re-installed it just to be sure (`sudo apt-get install --reinstall python3-numpy`).

Then I reinstalled gdal but the error is still there. Is this some kind of a bug?

**Comment by allanlewis** [comment]
> you need to install the python3-numpy apt package when building the bindings to have the gdal_array module to be built. Having just the numpy pip module is not enoguh

@rouault why is this? I'm trying to build GDAL 3.2 for Python 3.6 but my base image's `python3-numpy` is compiled for Python 3.9. What specifically is needed in addition to the `numpy` package from PyPI? Should it work if I build `numpy` from source? i.e.:
```
pip install --no-binary=numpy numpy
```

**Comment by rouault** [comment]
You need to make sure that with the python binary you use that the following returns a non-empty string:
```
python -c "import numpy; print(numpy.get_include())"
```

**Comment by allanlewis** [comment]
Thanks, @rouault! I _think_ I've got it working by installing `numpy` from source using the command in my previous comment: https://github.com/OSGeo/gdal/issues/3744#issuecomment-986275324

**Comment by allanlewis** [comment]
If anyone's interested, I made a branch with my changes to get v3.2.3 building against Python 3.6 on a branch: https://github.com/OSGeo/gdal/compare/master...allanlewis:python-3.6

This command now appears to build an image successfully, although I haven't tested it beyond the sanity checks done by `build.sh`:
```
BASE_IMAGE=python:3.6 TARGET_BASE_IMAGE=python:3.6 ubuntu-small/build.sh --release --gdal v3.2.3 --proj 8.2.0
```
