### ISSUE TITLE
GML file (FAA AIXM) is not interpreted by GDAL

### ISSUE THREAD

**Issue by antoniolocandro** [OSGeo/gdal#3749]
Hi the attached file can't be interpreted by GDAL/QGIS 
[AWOS_AIXM.zip](https://github.com/OSGeo/gdal/files/6386357/AWOS_AIXM.zip)

But if I change a few parts of the file it is understood
[AWOS_AIXM - edit.zip](https://github.com/OSGeo/gdal/files/6386358/AWOS_AIXM.-.edit.zip)

I can't say its 100% GDAl issue but it seems odd I changed very few things and it worked so maybe something on how GDAL is reading the file?

**Comment by jratike80** [comment]
That XML has a very complex application schema. The GMLAS driver should be able to resolve it totally. You can test it by running `ogrinfo gmlas:EA_AIP_DS_FULL_20170701_downloaded_20200818.xml`
That printed 1669 layers for me.

The old GML driver does not resolve the schema. It is just reads the XML and tries to convert as much of the data as it can into GDAL vector layers. The GML driver does also have special handling for some well known applications schemas (a few INSPIRE datasets, GML for topological data of NLS Finland etc.). I am not sure if AIXM belongs to those special cases. The command 
`ogrinfo EA_AIP_DS_FULL_20170701_downloaded_20200818.xml airspace` seems to find both linestring and polygon geometries but I can't say if they are interpreted right or wrong, and how QGIS interprets them.

Read https://gdal.org/drivers/vector/gml.html and https://gdal.org/drivers/vector/gmlas.html for understanding better what is different between the GML and GMLAL drivers.

**Comment by antoniolocandro** [comment]
Thank you for the input, the AIXM file is handled a bit by the GML driver and it works well and easier for users but you are correct maybe some instances are too complex based on how it was coded by the different users, mostly it all works except when US data is used but other countries it works great.

The GML airspace case is looking good in QGIS and it adds the benefit now users can use an opensource solution by just drag & drop so I am grateful for that. I think I will close this and try the GMLAS driver for it

**Comment by jratike80** [comment]
I did try GMLAS with QGIS by adding `GMLAS:` in front of the file URL. Unfortunately the layers that were imported into QGIS were all without geometries and the result was rather useful. If you will have a try set REMOVE_UNUSED_LAYERS and REMOVE_UNUSED_FIELDS into "NO".
