### ISSUE TITLE
gdal_translate batch processing error

### ISSUE THREAD

**Issue by gnihalk** [OSGeo/gdal#3756]
Hi you all.  I have a huge MODIS dataset and I need to translate them to tiff but each data is in a different sub-folder. 
C:\Users\HP\Desktop\modis\5000000889913\5000000889913\88258783\MOD10A2.2016322095024.hdf
C:\Users\HP\Desktop\modis\5000000889913\5000000889913\96113659\MOD10A2.A2016321.h20v05.006.2016340133152.hdf
....
.....
the dataset subfolders go like this...

and the code that im trying to run is:
`for /R C:\Users\HP\Desktop\modis\5000000889913\5000000889913\88258783 %f IN (MOD10A2.2016322095024.hdf) do gdal_translate.exe -sds -of gtiff %f C:\Users\HP\Desktop\modis\5000000889913\5000000889913\88258783\MOD10A2.2016322095024.tiff`

I tried to make a loop for all subfolders that I have but I got an error massage. I would appreciate it if I can take your opinions about it.
Thank you,
Gulnihal

**Comment by rouault** [comment]
This looks like a general scripting usage issue, not a GDAL specific bug. Closing for the reasons mentioned in the issue template.

**Comment by gnihalk** [comment]
> This looks like a general scripting usage issue, not a GDAL specific bug. Closing for the reasons mentioned in the issue template.

oh thank you. sorry for that. have a good day
