### ISSUE TITLE
Variable resolution BAG: "too many refinement grids" error

### ISSUE THREAD

**Issue by jessevarner** [OSGeo/gdal#3759]
## Expected behavior and actual behavior.
I am trying to read some variable-resolution BAGs from NOAA. It works for most of them, but some of them give the error: 
ERROR 6: Too many refinement grids
ERROR 1: No supergrids available. RESAMPLED_GRID mode not available

## Steps to reproduce the problem.
These are some of the BAGs that exhibit this problem:
https://data.ngdc.noaa.gov/platforms/ocean/nos/coast/D00001-D02000/D00158/BAG/D00158_MB_VR_MLLW_2of2.bag (109 MB) 
https://data.ngdc.noaa.gov/platforms/ocean/nos/coast/D00001-D02000/D00248/BAG/D00248_MB_VR_MLLW.bag (34 MB)
https://data.ngdc.noaa.gov/platforms/ocean/nos/coast/F00001-F02000/F00693/BAG/F00693_MB_VR_MLLW.bag (163 MB)
https://data.ngdc.noaa.gov/platforms/ocean/nos/coast/H12001-H14000/H13298/BAG/H13298_MB_VR_MLLW.bag (346 MB)

If I try to read one of them using, for example: 
gdal_translate -oo MODE=RESAMPLED_GRID -co COMPRESS=LZW D00158_MB_VR_MLLW_2of2.bag output.tif
I get the error.

## Operating system
Red Hat Enterprise Linux 7.9

## GDAL version and provenance
GDAL 3.2.2 from Miniconda
(conda install -c conda-forge gdal)

Is this a problem that should be addressed by the data provider, or can this be fixed in GDAL?

**Comment by rouault** [comment]
Looking at https://data.ngdc.noaa.gov/platforms/ocean/nos/coast/D00001-D02000/D00248/BAG/D00248_MB_VR_MLLW.bag , I see its "low resolution" grid is already a 8192 x 8192 grid. GDAL has an artibrary limitation to 10 million pixel for user supergrids, which is hit here (8192 ^2 > 10 million).  It could potentially be increased but at the expense of significant memory consumption and processing time

Another oddity of that dataset is that the min_dimensions_x, max_dimensions_x, min_resolution_x, max_resolution_x, min_dimensions_y, max_dimensions_y, min_resolution_y and max_resolution_y attributes of the varres_metadata variable are all set to zero

**Comment by jessevarner** [comment]
Thanks, that makes sense. The D00158 BAG is even worse... it's 16384 x 16384 for the "low resolution" grid, which at ~268 million far exceeds the 10 million pixel limit. It's a single BAG that covers a huge distance from the Florida Keys to South Carolina. 

I would be in favor of increasing the 10 million pixel "supergrid" limit somewhat, but it doesn't seem reasonable to remove it entirely.

For now, I can still read the "low resolution" version by taking out the MODE=RESAMPLED_GRID option. I will pass along feedback to the NOAA data provider that these BAGs are unreadable as VR using GDAL.

**Comment by giumas** [comment]
Hi @rouault, 

I understand your concerns related to memory consumption and processing time, however it is quite common for this huge BAG files that the majority of the nodes of the super grid are actually not populated. 
Isn't the memory consumption for those empty nodes about 28 bytes (the size of BAGRefinementGrid struct)?
I also assume that a longer processing time for huge BAG files should be kind of expected by the user.

Furthermore, as you mentioned, this 10-million-nodes limit is totally arbitrary given that it is not present in the BAG Format Specification Document. 

As such, what about totally removing this size check in favour of a memory error in case that not enough memory is on the user machine?

**Comment by giumas** [comment]
Thank you @rouault for the very quick action!
Do you have a rough estimate on when those great changes will be released?

**Comment by rouault** [comment]
> Do you have a rough estimate on when those great changes will be released?

in a couple days in GDAL 3.4.2
