### ISSUE TITLE
Using the degree sign in gdalinfo

### ISSUE THREAD

**Issue by andrew-aitchison** [OSGeo/gdal#3763]
https://lists.osgeo.org/pipermail/gdal-dev/2021-April/054032.html
https://lists.osgeo.org/pipermail/gdal-dev/2021-April/054033.html

Now that PROJ data includes "AREA" descriptions with "°" the degree sign,
it would be nice if gdalinfo reported other angles with "°" too.

I am happy to do the work.

**Comment by jratike80** [comment]
Degreesign did not work so well on Windows and related PR has been closed already.
