### ISSUE TITLE
g++: error: frmts/o/.libs/gsagdataset.o: No such file or directory

### ISSUE THREAD

**Issue by gisspace** [OSGeo/gdal#3766]
centos 8.2 x64
gcc 8.3
er.lo port/cplstring.lo port/cplstringlist.lo third_party/o/BitMask.lo third_party/o/BitStuffer2.lo third_party/o/Huffman.lo third_party/o/Lerc.lo third_party/o/Lerc2.lo third_party/o/Lerc_c_api_impl.lo third_party/o/RLE.lo \
    -rpath /usr/local/lib \
    -no-undefined \
    -version-info 28:1:0
g++: error: frmts/o/.libs/gsagdataset.o: No such file or directory
make[1]: *** [GNUmakefile:75：libgdal.la] 错误 1
make[1]: 离开目录“/usr/local/gisspace/gdal-3.2.1”
make: *** [GNUmakefile:88：check-lib] 错误 2

**Comment by rouault** [comment]
> frmts/o/.libs/gsagdataset.o: No such file or directory

did you post the full error log ? If you build with -j parallel flag, I suspect there might be a previous error somewhere

**Comment by rouault** [comment]
Closing due to lack of feedback
