### ISSUE TITLE
Build error: frmts/exr fails using Imath / openexr 3.0.1

### ISSUE THREAD

**Issue by jhgit** [OSGeo/gdal#3770]
See https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=255216

Fix: add #include "ImathInt64.h" in openexr_headers.h

I have not yet investigated compatibility with other (older) versions of openexr.  I suspect that file may not be in older versions, so this may need some configure support (#if HAVE_XXX tests) to allow building with Imath* headers from older versions.

**Comment by rouault** [comment]
include ImathInt64.h isn't the solution, and I'm surprised it builds for you. It doesn't for me . https://github.com/OSGeo/gdal/pull/3771 works against OpenEXR 2.4 and 3.0.1 locally for me. Let's see how CI likes it

**Comment by jhgit** [comment]
> include ImathInt64.h isn't the solution, and I'm surprised it builds for you. It doesn't for me .

It worked because that header has 'typedef long unsigned int Int64'.  That may or may not necessarily be 64 bits depending on the platform you build on.  On amd64 with recent gcc or clang, it is 64 bits.
It also included a deprecation warning, so if warnings are set to error out (-Werror, for instance), that would cause a build failure.

Your commit is better - for one thing, it doesn't depend on the deprecated Int64.  Thanks.
