### ISSUE TITLE
No module named '_gdal' when importing Shapely first

### ISSUE THREAD

**Issue by jacopofar** [OSGeo/gdal#3779]
hello,
I'm using the latest stable from GDAL and Shapely on macOS, with Python 3.9.
When importing GDAL or Shapely separately they work, but when using both I get an error only when using a specific order.
Seems the same issue as #2957 but on macOS.

## Expected behavior and actual behavior.

I expect to be able to import and usa GDAL and Shapely in any order.

## Steps to reproduce the problem.

    # create the virtualenv
    python3 -m venv .venv
    source .venv/bin/activate
    
    gdal-config --version
    # output: 3.2.2
    
    python3 -m pip install numpy==1.20.2
    python3 -m pip install --no-binary=Shapely Shapely==1.7.1
    python3 -m pip install --no-binary GDAL GDAL==3.2.2
    # this works
    python3 -c 'import osgeo; from shapely.geometry import shape'
    # this breaks
    python3 -c 'from shapely.geometry import shape; import osgeo'

The error is:
      
      Traceback (most recent call last):
        File "/Users/jacopo/projects/geoshiny/.venv/lib/python3.9/site-packages/osgeo/__init__.py", line 18, in swig_import_helper
          return importlib.import_module(mname)
        File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
        File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
        File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
        File "<frozen importlib._bootstrap>", line 565, in module_from_spec
        File "<frozen importlib._bootstrap_external>", line 1108, in create_module
        File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
      ImportError: dlopen(/Users/jacopo/projects/geoshiny/.venv/lib/python3.9/site-packages/osgeo/_gdal.cpython-39-darwin.so, 2): Symbol not found: _GEOSArea
        Referenced from: /usr/local/opt/libspatialite/lib/libspatialite.7.dylib
        Expected in: flat namespace
       in /usr/local/opt/libspatialite/lib/libspatialite.7.dylib
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "/Users/jacopo/projects/geoshiny/.venv/lib/python3.9/site-packages/osgeo/__init__.py", line 32, in <module>
          _gdal = swig_import_helper()
        File "/Users/jacopo/projects/geoshiny/.venv/lib/python3.9/site-packages/osgeo/__init__.py", line 31, in swig_import_helper
          return importlib.import_module('_gdal')
        File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
      ModuleNotFoundError: No module named '_gdal'

## Operating system
macOS 11.3

## GDAL version and provenance
GDAL 3.2.2 from homebrew

**Comment by rouault** [comment]
Perhaps @sgillies has some clues ? My first reaction would have that it is a conflict between the GEOS version embedded in shapely an the one used by libgdal, but I see you use --no-binary=Shapely (I'm not familiar with that option: is there a reason for the presence/absence of the equal sign in --no-binary=Shapely vs --no-binary GDAL ?). Or maybe it comes from the way shapely loads GEOS, which then confuses GDAL ?

**Comment by jacopofar** [comment]
@rouault no I don't think there's a difference, however to be sure I just retried without the `=` and it is the same.

**Comment by sgillies** [comment]
My guess is you've got multiple copies of the GEOS lib on your system and the shapely build found one incompatible with GDAL. Also, there's no reason to mix shapely and the gdal bindings in a Python program. The former doesn't provide anything that's not in the latter.

**Comment by jacopofar** [comment]
As far as I'm aware I have only one copy of GEOS:

    $ type geos-config
    geos-config is /usr/local/bin/geos-config

which is a symlink to the homebrew package in `/usr/local/Cellar/geos/3.9.1/bin/geos-config`, I checked and can confirm there are no other homebrew-installed versions on my system. The same happens with gdal, which is version`3.2.2_3`.

I tried the steps above by setting `GEOS_CONFIG=/usr/local/bin/geos-config` and the problem persists.

> there's no reason to mix shapely and the gdal bindings in a Python program. The former doesn't provide anything that's not in the latter

I'm not sure you understand what you mean, I'm using Shapely to handle geometries and GDAL to generate geoTIFF raster images, as far as I understand the former is not in the scope of GDAL

**Comment by rouault** [comment]
> as far as I understand the former is not in the scope of GDAL

GDAL has geometry classes and API, and binds a few GEOS methods (but perhaps in a lesser extent to shapely. See OGR_G_ functions of https://gdal.org/api/vector_c_api.html , that are bound in Python as ogr.Geometry.xxx   And https://github.com/OSGeo/gdal/blob/master/autotest/ogr/ogr_geom.py and https://github.com/OSGeo/gdal/blob/master/autotest/ogr/ogr_geos.py for a few examples

**Comment by rouault** [comment]
Closing. I don't see anything actionable on this
