### ISSUE TITLE
Add support for iterative geojson parser

### ISSUE THREAD

**Issue by nvkelso** [OSGeo/gdal#378]
## Expected behavior and actual behavior.

When opening data from https://www.alltheplaces.xyz/ I only get the first record and not all several 100,000 records in QGIS. QGIS is using the ORG GeoJSON driver to open the file.

## Steps to reproduce the problem.

Go to https://www.alltheplaces.xyz/ and choose download. The latest download I used was: https://s3.amazonaws.com/placescraper-results/runs/2018-03-25-18-54-21/output.geojson.gz. Uncompress and open the file into QGIS. Only the first record is imported.

I believe this is because this file is almost a GeoJSON feature collection, but not quite. It's just missing the Feature Collection declaration at the top and closure at the bottom. 

Instead it's a newline delimitated file where each GeoJSON feature is on it's own line as following this spec: http://ndjson.org/, making it easier to stream the file. It would be great if OGR could support this GeoJSON variant directly.

## Operating system

macOS 10.13.3

## GDAL version and provenance

2.1.3 version from QGIS 2.18.15

**Comment by sgillies** [comment]
@rouault my projects implement it, I've seen it elsewhere, but RFC 8142 really needs support from OGR. That will make all the difference 😃  Until then, people will keep trading multi-GB GeoJSON feature collections with each other.

**Comment by andrewharvey** [comment]
> I'd note that current GDAL master can now read FeatureCollection of arbitrary size with very modest memory requirements (still requiring an initial pass to establish the feature definition)

Looks like that's now made it into [2.3.0](https://trac.osgeo.org/gdal/wiki/Release/2.3.0-News)!

**Comment by sgillies** [comment]
Awesome, @rouault ! Can the reader read RS-delimited sequences of pretty-printed JSON?

**Comment by rouault** [comment]
> Can the reader read RS-delimited sequences of pretty-printed JSON?

yes

**Comment by nvkelso** [comment]
Rad!
