### ISSUE TITLE
Unable to disable GEOS and SFCGAL when building from source

### ISSUE THREAD

**Issue by adamjstewart** [OSGeo/gdal#3782]
## Expected behavior and actual behavior.

I expected to be able to disable GEOS support when building from source but it returns an error message instead.

## Steps to reproduce the problem.

```console
$ ./configure --with-geos=no
...
GEOS support disabled
configure: error: GEOS support explicitly enabled, but geos-config could not be found
```

## Operating system

macOS 10.15.7

## GDAL version and provenance

GDAL 3.3.0

This used to work fine in GDAL 3.2.2, so this is a new bug.

**Comment by adamjstewart** [comment]
UPDATE: This seems to be the case for all optional packages, not just GEOS.

**Comment by sgillies** [comment]
@adamjstewart the configure options have been globally changed, for example to `--without-geos`.

**Comment by adamjstewart** [comment]
Thanks, you may want to update the `./configure --help` output, as it still says:
```
  --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
...
  --with-geos=ARG         Include GEOS support (ARG=yes, no or geos-config
                          path)
```
I assume `--without-geos` works in all older versions (GDAL 1–3)?

**Comment by sgillies** [comment]
I said that the configure options have been globally changed, but I wrote that based on a memory of seeing something. I could not in fact find the change or any mention of it. I may be wrong.

**Comment by tbonfort** [comment]
> @adamjstewart the configure options have been globally changed, for example to `--without-geos`.

the `--with-geos=no` is a standard autoconf construct (https://www.gnu.org/software/autoconf/manual/autoconf-2.66/html_node/External-Software.html#External-Software)  that we should support. I'll look into submitting a PR to handle this tomorrow, and check whether this is geos specific or more global

**Comment by adamjstewart** [comment]
It seems to be a global problem, not sure what changed in the autoconf handling.

**Comment by sgillies** [comment]
@tbonfort maybe one of the commits in https://github.com/OSGeo/gdal/pull/3476/files ?

**Comment by adamjstewart** [comment]
UPDATE: `--without-geos` also doesn't work for the same reason.

**Comment by tbonfort** [comment]
> It seems to be a global problem, not sure what changed in the autoconf handling.

A quick test on my end does not show this (aside from --with-sfcgal). Do you have any examples

**Comment by tbonfort** [comment]
Tentative fix submitted in #3786

**Comment by tbonfort** [comment]
> It seems to be a global problem, not sure what changed in the autoconf handling.

Given that my automated build at https://github.com/airbusgeo/godal/blob/main/.github/workflows/build-gdal.sh#L14 works correctly while explicitely using
```
--without-crypto \
	--without-cryptopp \
	--without-gnm \
	--without-qhull \
	--without-sqlite3 \
	--without-pcidsk \
	--without-lerc  \
	--without-gif \
	--without-pcraster \
	--without-curl \
	--without-png \
	--without-tiledb \
	--without-odbc \
	--without-freexl \
	--without-pcre \
	--without-libkml \
	--without-xml2 \
	--without-expat \
	--without-xerces \
	--without-lerc \
	--without-pg \
	--without-curl \
	--without-openjpeg \
	--without-netcdf \
	--without-hdf5 \
	--without-hdf4 \
	--without-ogdi \
	--without-exr \
	--without-spatialite
```
I'm reasonably confident that this is not a global problem

**Comment by adamjstewart** [comment]
Ah, I noticed the issue for both GEOS and SFCGAL so I assumed it was an issue for all of them. I'll try out your patch today and let you know if it solves the issue for me!
