### ISSUE TITLE
Unable to replace a RAT in GTiff

### ISSUE THREAD

**Issue by elpaso** [OSGeo/gdal#3783]
Failing test case on current master:

in `autotest/gcore/rat.py`

```python

def test_rat_4():

    ds = gdal.GetDriverByName('GTiff').Create('/tmp/rat_4.tif', 1, 1)
    rat = gdal.RasterAttributeTable()
    rat.CreateColumn('VALUE', gdal.GFT_Integer, gdal.GFU_MinMax)
    rat.CreateColumn('CLASS', gdal.GFT_String, gdal.GFU_Name)
    rat.SetValueAsInt(0, 0, 123)
    rat.SetValueAsString(0, 1, 'Class1')
    ds.GetRasterBand(1).SetDefaultRAT(rat)
    ds = None

    ds = gdal.OpenEx('/tmp/rat_4.tif')
    gdal_band = ds.GetRasterBand(1)
    rat = gdal_band.GetDefaultRAT()
    assert rat is not None
    assert rat.GetValueAsInt(0, 0) == 456
    ds = None

    # Replace existing RAT
    rat = gdal.RasterAttributeTable()
    rat.CreateColumn('VALUE', gdal.GFT_Integer, gdal.GFU_MinMax)
    rat.CreateColumn('CLASS', gdal.GFT_String, gdal.GFU_Name)
    rat.SetValueAsInt(0, 0, 789)
    rat.SetValueAsString(0, 1, 'Class1')

    ds = gdal.OpenEx('/tmp/rat_4.tif', gdal.OF_RASTER | gdal.OF_UPDATE)
    ds.GetRasterBand(1).SetDefaultRAT(rat)
    ds = None

    ds = gdal.OpenEx('/tmp/rat_4.tif')
    gdal_band = ds.GetRasterBand(1)
    rat = gdal_band.GetDefaultRAT()
    assert rat is not None
    assert rat.GetValueAsInt(0, 0) == 789
    ds = None

```

**Comment by rouault** [comment]
Might be just a usage issue. You didn't open the file in update mode

==>   ds = gdal.OpenEx('/tmp/rat_4.tif', gdal.OF_RASTER | gdal.OF_UPDATE)

**Comment by elpaso** [comment]
Thanks, I tried that but the test still fails, I've updated the code above to reflect the changes.

**Comment by jratike80** [comment]
I can confirm that with `GDAL 3.1.4, released 2020/10/20` from OSGeo4W, the value of `GetValueAsInt(0, 0)` is still `123` after running your code. I also tried to remove RAT by copying a line `    ds.GetRasterBand(1).SetDefaultRAT(gdal.RasterAttributeTable())
` from https://github.com/OSGeo/gdal/blob/master/autotest/gcore/rat.py  but that does not delete the rat_4.tif.aux.xml file and RAT is still there when rat_4.tif is opened next time.

**Comment by rouault** [comment]
> Thanks, I tried that but the test still fails, I've updated the code above to reflect the changes.

actually that was a bad suggestion of mine. RAT in TIFF is handled by the PAM / .aux.xml code and updates in .aux.xml files can be done, for good or worse, even when the dataset is opened in read-only mode

**Comment by elpaso** [comment]
A possible fix: https://github.com/OSGeo/gdal/pull/3796
