### ISSUE TITLE
GeoTIFF CreateCopy ignores NUM_THREADS parameter when copying overview images

### ISSUE THREAD

**Issue by Kirill888** [OSGeo/gdal#3785]
## Expected behavior and actual behavior.

I'm creating large COG files using 2 pass approach

1. Generate in-memory file with in memory external overviews using fast configuration of ZSTD compression
2. Re-encode into COG using `GDALCreateCopy` with WEBP/JPEG or DEFLATE (this is in Python using `rasterio.shutil.copy` wrapper) using `copy_src_overviews=TRUE`

I'm configuring multi-threaded encoding with `NUM_THREADS=ALL_CPUS` (this is running in AWS on 16-core instance).

I have noticed that there is long period of single threaded activity, followed by multi-threaded load. Multi-threading helps a lot in my scenario. If I don't have overviews present, re-encode is very quick and most of the time all cpu cores are engaged. When copying overviews however there is long period of single core only load. I have confirmed the same behavior with `gdal_translate`.

## Steps to reproduce the problem.

On a multi-core machine run this command on a large tiff image with overviews (external or internal)

```bash
src=large_file_with_overviews.tif
dst=cog.tif
B=1024
P=2
Q=9
gdal_translate \
    -co COMPRESS=deflate \
    -co ZLEVEL=${Q} \
    -co PREDICTOR=${P} \
    -co BIGTIFF=YES \
    -co SPARSE_OK=TRUE \
    -co TILED=yes \
    -co BLOCKXSIZE=${B} \
    -co BLOCKYSIZE=${B} \
    -co NUM_THREADS=ALL_CPUS \
    -co COPY_SRC_OVERVIEWS=YES \
    $src $dst
```
Observe long periods of single threaded load followed by "all cores are engaged" in the second part.

## Operating system

Ubuntu 18.04 64 bit

## GDAL version and provenance

3.0.4 (compiled from source)

**Comment by jratike80** [comment]
Did you consider to send mail into gdal-dev list and ask why GDAL behaves like it does? I am not sure if you have found a bug. Perhaps it is impossible of impractical to write the overviews exactly into where they belong in the TIFF file as multithreaded? I don't  know, therefore I would have asked.

**Comment by rouault** [comment]
Please use more recent versions. Multi-threaded overview computation was added in GDAL 3.2

**Comment by jratike80** [comment]
Does overview computation happen even when the overviews are copied `copy_src_overviews=TRUE`?

**Comment by rouault** [comment]
> Does overview computation happen even when the overviews are copied `copy_src_overviews=TRUE`?

https://gdal.org/drivers/raster/gtiff.html: 'COPY_SRC_OVERVIEWS=[YES/NO]: (CreateCopy() only) By setting this to YES (default is NO), the potential existing overviews of the source dataset will be copied to the target dataset without being recomputed'

So technically no, the pixel values are not computed, but upgrading to a more recent GDAL version might help that the generation of the corresponding TIFF tiles benefit from multithreading
