### ISSUE TITLE
Nodatavalue may be float 64 for a float 32 band

### ISSUE THREAD

**Issue by rafaqz** [OSGeo/gdal#3791]
This can lead to floating point errors where the 64 bit nodata value will not compare as equal to the 32 bit nodata value used in the band. Im not sure if this is specific to how some files are stored, or to how files are loaded generally.

See: https://github.com/yeesian/ArchGDAL.jl/issues/188#issue-875182970

**Comment by rouault** [comment]
You need to be much more specific with a code snippet that demonstrates what you to do and/or details on the format used, how you compare values, etc.

**Comment by rafaqz** [comment]
My problems are from using it through GDAL.jl, but I'll use a command line example, the behavior seems to be the same. Using the first file in this zip:

```bash
wget https://biogeo.ucdavis.edu/data/worldclim/v2.1/base/wc2.1_10m_tmin.zip
unzip wc2.1_10m_tmin.zip
gdalinfo wc2.1_10m_tmin_01.tif
gdallocationinfo -b 1 wc2.1_10m_tmin_01.tif 1 1
```

With the important `gdalinfo` being:
```bash
Band 1 Block=2160x1 Type=Float32, ColorInterp=Gray
  Min=-49.724 Max=27.750
  Minimum=-49.724, Maximum=27.750, Mean=nan, StdDev=nan
  NoData Value=-3.39999999999999996e+38
```
Where NoData Value is 64 bit. 

And `gdallocationinfo`:

```bash
$ gdallocationinfo -b 1 wc2.1_10m_tmin_01.tif 1 1
Report:
  Location: (1P,1L)
  Band 1:
    Value: -3.39999995214436e+38
```

Where the actual value is 32 bit, but printed as 64 bit. In Julia at least, the float 32 nodata value in the band and the float 64 NoData value do not evaluate as equal with `isequal` or `==`.  If both are converted to float 32 then equality holds.

But I'm not sure if this file is just badly constructed, or if this is happening in GDAL internally. I also don't know if this is a common issue or just among the datasets I use. But I'm looking to work out where to handle it in the stack of wrappers, gdal -> GDAL.jl -> ArchGDAL.jl -> GeoData.jl so that equality can be used with nodata values instead of `isapprox`.

Currently I convert the nodata type to match the band type in GeoData.jl, which works fine and maybe that is enough. But it seems like it may be a wider problem.

**Comment by rouault** [comment]
> but I'll use a command line example, the behavior seems to be the same. Using the first file in this zip:

thanks. Proposed fix in https://github.com/OSGeo/gdal/pull/3794.
As a workaround in your code, you can cast the return of GetNoDataValue() to float (what the fix does), before comparing it to pixel values
