### ISSUE TITLE
GRIB: using .idx sidecar files to speed up opening

### ISSUE THREAD

**Issue by rouault** [OSGeo/gdal#3799]
gdalinfo "/vsicurl/https://ftpprd.ncep.noaa.gov/data/nccf/com/hrrr/prod/hrrr.20210505/conus/hrrr.t15z.wrfsfcf01.grib2" fails after some time with:

```
> GET /data/nccf/com/hrrr/prod/hrrr.20210505/conus/hrrr.t15z.wrfsfcf01.grib2 HTTP/1.1
Host: ftpprd.ncep.noaa.gov
Accept: */*
Range: bytes=84819968-84836351

* Mark bundle as not supporting multiuse
< HTTP/1.1  302 Your allowed limit has been reached. Please go to https://www.weather.gov/abusive-user-block  for more info
* no chunk, no close, no size. Assume close to signal end
<
```

So it seems that after a number of quickly consecutive GET requests to the server as here, the server no longer want to see us. The 302 HTTP error it sends however is not appropriate. 429 "Too many requests" would be more appropriate

GRIB files with lots of "messages" / bands like that one aren't really cloud friendly, as you have to skip in many parts of the file to get an inventory of it.

That said, I see that in that instance, the .grib files are accompanied by a sidecar file, like https://ftpprd.ncep.noaa.gov/data/nccf/com/hrrr/prod/hrrr.20210505/conus/hrrr.t15z.wrfsfcf01.grib2.idx, which I believe is produced by the wgrib utility. We could conceptually try to make use of it, however it doesn't contain all metadata that are typically retrieved by the driver, so for gdalinfo itself that wouldn't be sufficient, but for just a Open() call that might be enough.

**Comment by isodrosotherm** [comment]
I'm not sure if this is of any help to you (or if you want me to do some specific debugging) but I ran into this problem yesterday, as well. However, The problem does not persist for me on my windows machine, only my mac. Additionally, I do not prepend the url with "/vsicurl/" on windows.

**Comment by rouault** [comment]
> Additionally, I do not prepend the url with "/vsicurl/" on windows.

if you don't prepend with /vsicurl/, then the whole file is ingested in memory with a single HTTP GET, which 'stresses' the server less (of course the downside is that you're limited by the amount of RAM).

**Comment by isodrosotherm** [comment]
do you have any tips regarding your last paragraph for how one could get around the error using the .idx with an Open() call? Is there a way to specify byte range when using gdal.Open()?

**Comment by rouault** [comment]
> do you have any tips regarding your last paragraph for how one could get around the error using the .idx with an Open() call?

you can't use a .idx file currently. That would require extra code.

> Is there a way to specify byte range when using gdal.Open()?

no, your best hope currently is to download locally the file and/or complain to ftpprd.ncep.noaa.gov that they should relax their server side checks a bit
