### ISSUE TITLE
ogr2ogr Segmentation fault when converting large json file to csv

### ISSUE THREAD

**Issue by ketograph** [OSGeo/gdal#3831]
## Expected behavior and actual behavior.
I want to convert a large (14MB) json file to a csv file using `ogr2ogr`. I expect a csv file with all elements inside after the conversion. 
However, the conversation fails with a Segmentation fault after creating a csv file with the header and one data row. 
When I manually edit the file (see `file_small.json`) and use only one or two features (instead of thousands), this problem does not occur and a proper csv file is created.

## Steps to reproduce the problem.

```terminal
$ ogr2ogr file_big.csv file_big.json
Segmentation fault
```

## Operating system
Ubuntu 20.04 LTS running under WSL2 in Windows 10

## GDAL version
3.0.4+dfsg-1build3 from the default Ubuntu packages (`http://archive.ubuntu.com/ubuntu focal/universe amd64 Packages`)

## Attachments
* [file_big.json.gz](https://github.com/OSGeo/gdal/files/6457774/file_big.json.gz)
* [file_small.json.gz](https://github.com/OSGeo/gdal/files/6457776/file_small.json.gz)

**Comment by jratike80** [comment]
I can confirm that GDAL 3.3 on Windows also converts just one feature and stops.
I am not sure how good selection CSV is for your data that have RealList and StringList attributes but GDAL should not segfault.

I also tried to convert data into Spatialite but that did not even create a layer into the database. Conversion into GML was successful.

**Comment by jratike80** [comment]
The lists in the data do not have equal length. By default the lists are split into fields and if next feature has a longer or shorter list the number of fields does not match. Perhaps the parsing is OK but the data are not suitable for CSV if the fields are split. There is no mechanism with intelligence to do "in feature 2 s1_recording_dates has only 219 list items, I must fill fields 220-346 with blanks to keep the CSV file synchronized".

Splitting the fields feels also unpractical, the first feature has 346 recording_dates but that is off-topic.  But segmentation fault is bad, a reasonable error message would be good.
