### ISSUE TITLE
3.3.0 Make failed with gcc 4.9.x and Mac osx 10.7.x Lion

### ISSUE THREAD

**Issue by laurentang001** [OSGeo/gdal#3836]
OS : Mac os x 10.7.x (last) Lion.
Computer : Mac mini Intel core 2 duo
Compiler : built gcc 4.9.x (last)
Gdal compiled : 3.3.0

Issue : configure is OK but make failed. Although everything was OK with the same configure parameterization as for gdal 3.1.4, boost and uriparser errors occurred during make.
NB Last gdal version installed : 3.1.4.

Enclosed (if correctly uploaded) : 
- config.log
- my-configure.log: issued by configure
- my-make.log : issued by make. 
[config.log](https://github.com/OSGeo/gdal/files/6471588/config.log)
[my-configure.log](https://github.com/OSGeo/gdal/files/6471593/my-configure.log)
[my-make.log](https://github.com/OSGeo/gdal/files/6471595/my-make.log)

**Comment by rouault** [comment]
> (if correctly uploaded) :

no, I'd suggest to put them in a zip and attach the zip

**Comment by laurentang001** [comment]
> now maybe. From my mobile phone, not my Mac. Thank you.

**Comment by rouault** [comment]
I suspect this is related to commit 3708420fcd84068707ad0c2faef24d2398d02f32 / #2740.
Do you have ``grep`` available on your system ?
What does ``echo "foo pds pds4" | grep -w -o pds`` return for you ?

**Comment by laurentang001** [comment]
NB Upon request, I can built gdal 3.1.4 again to acknowledge its correct installation with the same parameters given to configure.
Kind regards,

**Comment by rouault** [comment]
> I can built gdal 3.1.4 again to acknowledge its correct installation with the same parameters given to configure.

the changes I pointed in https://github.com/OSGeo/gdal/issues/3836#issuecomment-840443743 were introduced in 3.2 . Can you answer the questions of this above comment ?

**Comment by laurentang001** [comment]
Object: your grep question.

Yes, I entered the command. 
It gives as output :
foo pds pds4

Typing grep --version gives : gnep (gnu grep) 2.5.1 
Thank you.

**Comment by laurentang001** [comment]
Rrmark: v. 10.3.0

I tried to recompile this gcc version, I failed earlier. Same kind of error : boost and uriparser. 
Next night, I likely am going to compile again gcc v. 10.2.x.
Thank you.

**Comment by rouault** [comment]
> It gives as output :
> foo pds pds4
> 
> Typing grep --version gives : gnep (gnu grep) 2.5.1

hum might be a Mac specific thing.  Using officially GNU grep 2.5.1 (super antiquated. 2002...) from https://gnu.askapache.com/grep/grep-2.5.1.tar.gz , I get
```
pds
pds
```
as output, which gcore/GNUmakefile wouldn't like either. So we need to be a bit more robust for those old versions

**Comment by laurentang001** [comment]
foo pds pds4

grep --version gives : 2.5.1

**Comment by laurentang001** [comment]
I also installed grep v. 3.6. Tests passed.
