### ISSUE TITLE
SQLITE_USE_OGR_VFS and OGR_SQLITE_JOURNAL options missing from docs

### ISSUE THREAD

**Issue by agiudiceandrea** [OSGeo/gdal#3842]
SQLITE_USE_OGR_VFS option was introduced with https://github.com/OSGeo/gdal/commit/73df9050e3d29d73cd5ef7b4264a2109d3c0e589 "SQLite: add capability to use VSI Virtual File API when needed"

Such option and its explanation seems not present in https://gdal.org/drivers/vector/sqlite.html and https://gdal.org/user/configoptions.html

**Comment by agiudiceandrea** [comment]
Another missing option related to SQLite is OGR_SQLITE_JOURNAL

**Comment by theroggy** [comment]
I encountered this issue and OGR_SQLITE_JOURNAL was already added in #5610, so I had a go at documenting SQLITE_USE_OGR_VFS as well...

**Comment by agiudiceandrea** [comment]
Thanks a lot @theroggy!
