### ISSUE TITLE
ERROR 1: TIFFReadEncodedTile() failed during gdaladdo

### ISSUE THREAD

**Issue by stijn-vranckx** [OSGeo/gdal#3844]
## Expected behavior and actual behavior.

Generate the overview levels of the GeoTiff without errors. I get the error ERROR 1: TIFFReadEncodedTile() failed.

## Steps to reproduce the problem.

gdaladdo test.tif 2 4 8 16

## Operating system

OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.19042 N/A Build 19042

Cygwin Package Information
Package              Version        Status
cygwin               3.2.0-1        OK

## GDAL version and provenance

GDAL 3.3.0, released 2021/04/26 from https://mirrors.aliyun.com

**Comment by stijn-vranckx** [comment]
We can not provide the source tif file, but if there is a way to increase to log level and provide additional info we will happily do so.

**Comment by stijn-vranckx** [comment]
I can open the file with Luciad Product Suite and with Snap From ESA both Java applications. 
gdal_translate fails with the same error.

I have added the ouput of gdalinfo.

> $ gdalinfo test.TIF
Driver: GTiff/GeoTIFF
Files: test.TIF
Size is 44936, 40496
Coordinate System is:
GEOGCRS["WGS 84",
    DATUM["World Geodetic System 1984",
        ELLIPSOID["WGS 84",6378137,298.257223563,
            LENGTHUNIT["metre",1]]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["degree",0.0174532925199433]],
    CS[ellipsoidal,2],
        AXIS["latitude",north,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433]],
        AXIS["longitude",east,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433]],
    ID["EPSG",4326]]
Data axis to CRS axis mapping: 2,1
Origin = (45.040868795015328,-13.021068424956226)
Pixel Size = (0.000004499994930,-0.000004499994930)
Metadata:
  AREA_OR_POINT=Area
  METADATATYPE=DG
Image Structure Metadata:
  COMPRESSION=DEFLATE
  INTERLEAVE=PIXEL
Corner Coordinates:
Upper Left  (  45.0408688, -13.0210684) ( 45d 2'27.13"E, 13d 1'15.85"S)
Lower Left  (  45.0408688, -13.2033002) ( 45d 2'27.13"E, 13d12'11.88"S)
Upper Right (  45.2430806, -13.0210684) ( 45d14'35.09"E, 13d 1'15.85"S)
Lower Right (  45.2430806, -13.2033002) ( 45d14'35.09"E, 13d12'11.88"S)
Center      (  45.1419747, -13.1121843) ( 45d 8'31.11"E, 13d 6'43.86"S)
Band 1 Block=512x512 Type=Byte, ColorInterp=Red
  NoData Value=0
  Overviews: 22468x20248, 11234x10124, 5617x5062, 2809x2531
Band 2 Block=512x512 Type=Byte, ColorInterp=Green
  NoData Value=0
  Overviews: 22468x20248, 11234x10124, 5617x5062, 2809x2531
Band 3 Block=512x512 Type=Byte, ColorInterp=Blue
  NoData Value=0
  Overviews: 22468x20248, 11234x10124, 5617x5062, 2809x2531

**Comment by jratike80** [comment]
So I think that libtiff cannot read the tile. Try http://www.libtiff.org/man/tiffinfo.1.html and play with the options. Unfortunately I cannot help with them but `-D` looks promising.

**Comment by rouault** [comment]
This is likely indeed an issue with one of the tile. This ticket is not actionable if a developer cannot access the faulty file. You can provide me privately (even.rouault at spatialys.com) with a link where to download it

**Comment by rouault** [comment]
@ stijn-vranckx  Could you at least provide me with the full dataset identification ? I might be able to get the image from the data producer.

**Comment by rouault** [comment]
@stijn-vranckx Could you at least provide me with the full dataset identification ? I might be able to get the image from the data producer.

**Comment by rouault** [comment]
Closing due to lack of feedback
