### ISSUE TITLE
Multi-threaded Geotiff export gets stuck in an infinite loop

### ISSUE THREAD

**Issue by azhow** [OSGeo/gdal#3848]
## Expected behavior and actual behavior

Using GDAL (DLL compiled from source) I was trying to split a big GeoTIFF file into smaller files using multi-threading (~20 threads). Sometimes the process would get stuck at the loop https://github.com/OSGeo/gdal/blob/b8857cbabf90abc92e17c07789c6e567f1b7e335/gdal/gcore/gdalrasterblock.cpp#L1016-L1024 while all the other threads would be waiting for this thread to unlock.

I observed that the value tested (&(poTarget->nLockCount)) in https://github.com/OSGeo/gdal/blob/b8857cbabf90abc92e17c07789c6e567f1b7e335/gdal/gcore/gdalrasterblock.cpp#L1018-L1019 is actually already -1 so because of that the break condition is never hit.

## Steps to reproduce the problem

I could not reliably reproduce the problem. I noticed by reading the commit comment of that code section that there might be some problems in multi-threaded usage depending on the cache size and using this information I started using the option of GTIFF_DIRECT_IO set to YES.

That change seemed to lower the probability of the issue happening so that originally it happened every ~5 runs to it happening once in almost 30 runs. Because of that I also increased the cache size from the default 5% to 10%. This other change seemed to avoid the issue on the different setups (different CPUs and RAM capacities) I had available to test.

As it is a multi-threaded issue it was very hard to debug the problem and I was only able to do it using WinDBG without symbol information.

## Operating system

Windows 7 and 10 64-bit

## GDAL version and provenance

DLL compiled from the source of the tag [v3.1.0](https://github.com/OSGeo/gdal/releases/tag/v3.1.0)

**Comment by rouault** [comment]
> Using GDAL (DLL compiled from source) I was trying to split a big GeoTIFF file into smaller files using multi-threading (~20 threads).

Do you use a GDAL dataset per thread ? A single GDAL dataset object can't be used concurrently.

**Comment by azhow** [comment]
Yes. I open the file separately for each thread.

**Comment by rouault** [comment]
A standalone reproducer (even if not completely reliable) + input dataset (or the gdal_create (https://gdal.org/programs/gdal_create.html) invokation to generate a representative one) would be needed

**Comment by azhow** [comment]
[Here](https://github.com/OSGeo/gdal/files/6510667/main.zip) is a standalone (only a main.cpp) which only requires GDAL DLL to reproduce the issue. I've been able to reproduce it very consistently with this [input dataset](http://geospatialearth.in/BM/TrueMarble.250m.21600x21600.D3.tif.gz).

I can also provide another detail (which is mentioned in the code) that if I close the datasets the issue doesn't happen at all, which for me it makes sense as it wouldn't use that much cache (that's my guess).

This reproducer was tested with the following setup:
* Windows 10 - 64 bit
* I7 - 9700
* 16GB RAM
* SSD

**Comment by KhalCamargo** [comment]
Hello, do you have any news regarding this issue?

**Comment by azhow** [comment]
Hi, do you have any updates on this matter?

Best regards!

**Comment by rouault** [comment]
First, there's an issue in your test file.  The return of CSLSetNameValue(pOptions, "TILED", "YES"); should be affected to pOptions, so that should be
```
           pOptions = CSLSetNameValue(pOptions, "TILED", "YES");
           pOptions = CSLSetNameValue(pOptions, "BLOCKXSIZE", "64");
           pOptions = CSLSetNameValue(pOptions, "BLOCKYSIZE", "64");
           pOptions = CSLSetNameValue(pOptions, "COMPRESS", "PACKBITS");
```
otherwise you might get memory corruptions.
That said I reproduced your issue, but with nRefCount = 1
There's indeed a flow in the code that you spotted and the following fix should be applied, and seems to solve the issue for me
```
diff --git a/gdal/gcore/gdalrasterblock.cpp b/gdal/gcore/gdalrasterblock.cpp
index 2e662fb381..83d493193d 100644
--- a/gdal/gcore/gdalrasterblock.cpp
+++ b/gdal/gcore/gdalrasterblock.cpp
@@ -1021,6 +1021,7 @@ CPLErr GDALRasterBlock::Internalize()
                                 CPLDebug("GDAL", "Evicting dirty block of another dataset");
                                 break;
                             }
+                            poTarget = poTarget->poPrevious;
                         }
                     }
                 }
```
Could you apply it and confirm it fixes your issue ?
That said, multi-threaded writing of datasets with the current design of the GDAL block cache will suffer from scalability issues. Fixing that would require likely a per-thread / per-dataset block cache
