### ISSUE TITLE
Trojan in latest release?

### ISSUE THREAD

**Issue by mteiden** [OSGeo/gdal#3850]
I downloaded latest version and extracted files, our Fidelis antivirus reported the following trojan 

5/18/2021 2:10:45 PM
Gen:Variant.Fugrafa.58728
...\gdal-3.3.0\conftest.exe

My apologies if this is not appropriate place to report this, but is literally the first time I have logged into GitHub...

**Comment by rouault** [comment]
The project doesn't deliver executables. You must check with whoever provided you with the GDAL binaries. But this is likely a false positive.

**Comment by mteiden** [comment]
I downloaded from here, I thought was related, my apologies
https://gdal.org/download.html
Current Releases
    2021-05-03 gdal-3.3.0.tar.gz

**Comment by mteiden** [comment]
The alert occurred during ./configure, will check if there is somewhere on the site to report

**Comment by rouault** [comment]
Ok,  gdal-3.3.0.tar.gz is indeed a delivery of the project but the archive doesn't contain conftest.exe. It is something that is generated when running ./configure, presumably on MSYS2. Unless your MSYS2 installation has been infected, this is likely a false positive

**Comment by mteiden** [comment]
I see, that is possible, I am trying to build under Windows 10 with MinGW in a GIT GUI window... what could go wrong :), thx for quick reply.
