### ISSUE TITLE
[iOS] GeoJSON not recognized when located in the application's Documents folder

### ISSUE THREAD

**Issue by rascal222** [OSGeo/gdal#3861]
## Expected behavior and actual behavior.

Trying to open a GeoJSON file using the `GDALOpenEx` method but encountered this error :
```
ERROR 4: 'path/to/file.json' not recognized as a supported file format.
```

The `GDALOpenEx` method works fine when the file is embedded within the application's bundle (read-only). Unfortunatly it fails when the file is stored in the application's `Documents` folder (read-write). Directly passing the file content instead of the file path seems to solve the issue.

Note : Renaming to `.json` or `.geojson` does not seem to have an effect on the outcome.

References : https://gis.stackexchange.com/questions/302257/gdalopenex-doesnt-works-anymore-with-ios-12

## Steps to reproduce the problem.

File content example :
```json
{
   "type" : "FeatureCollection",
   "features" : [{
      "type": "Feature",
      "geometry": {
         "type": "Point",
         "coordinates": [125.6, 10.1]
      },
      "properties": {
         "name": "Dinagat Islands"
      }
   }]
}
```

Load this file into the application's `Documents` folder and load it using :
```c++
GDALOpenEx(filepath, GDAL_OF_VECTOR, nullptr, nullptr, nullptr);
```

## Operating system

iOS 12+
Xcode 12.4+

## GDAL version and provenance

v2.4.4

**Comment by rouault** [comment]
Does filepath contain UTF-8 characters not in the ASCII range ?
