### ISSUE TITLE
GMLJP2 V2 (for J2K drivers): incorrect coordinates order for WGS84 (EPSG 4326) in <gml:boundedBy> element

### ISSUE THREAD

**Issue by EmDevys** [OSGeo/gdal#3866]
GDAL 3.1.4, win64
using J2KopenJPEG driver (but I guess this applies to all J2K drivers using GMLJP2 v2), the coordinates order is incorrect for WGS84 (EPSG 4326), being  long, lat. It should be changed to lat, long, as this is the case for the other elements in the GMLJP2 document (<gml:origin> and <gml:offsetVector>).
Attached is an example of such a gmljp2 document.

[GMLJP2v2_WGS84.txt](https://github.com/OSGeo/gdal/files/6518829/GMLJP2v2_WGS84.txt)

**Comment by rouault** [comment]
Reproducer:
gdal_translate ../autotest/gdrivers/data/small_world.tif test.jp2 -co gmljp2v2_def=yes -of jp2openjpeg
gdalinfo -mdd all test.jp2

**Comment by jratike80** [comment]
The attached example presents the desired result, not the buggy one, right?
```
 <gml:boundedBy>
       <gml:Envelope srsDimension="2" srsName="http://www.opengis.net/def/crs/EPSG/0/4326">
         <gml:lowerCorner>35.9666666670238 -101.641666336667</gml:lowerCorner>
         <gml:upperCorner>41.9333333336666 -95.1583330033592</gml:upperCorner>
       </gml:Envelope>
     </gml:boundedBy>
     ```

**Comment by rouault** [comment]
> The attached example presents the desired result, not the buggy one, right?

yes, the attachment was manually edited with an additional <swe:DataRecord> section not normally generated with just -co gmljp2v2_def=yes
