### ISSUE TITLE
Python bindings are missing a clean way to close datasets (also, support for context managers)

### ISSUE THREAD

**Issue by s-m-e** [OSGeo/gdal#3872]
I just came across an inconsistency. Datasets, once opened, can not be directly closed via [the Python bindings](https://gdal.org/python/osgeo.gdal.Dataset-class.html). There is no `close` or any similar method in this class. In a similar manner, [context managers](https://docs.python.org/3/reference/datamodel.html#context-managers) via `__exit__` are [not supported](https://stackoverflow.com/q/40513144/1672565).

There are a couple of [commonly recommended workarounds](https://gis.stackexchange.com/q/80366/13332), the most prominent one being the use of `del`. Long story short: This is a [notoriously unreliable](https://docs.python.org/3/reference/datamodel.html#object.__del__) way of hoping for Python's garbage collector to do *the right thing*™ (see warning in Python's official documentation).

Interestingly, `GDAL` knows how to close datasets properly [as can be seen here in rasterio](https://github.com/sgillies/rasterio/blob/fcc13eb63c62256611b399e2eb8fc65e50133a2b/rasterio/_io.pyx#L1463), although this appears to be an internal / "private" API.

**Comment by jratike80** [comment]
Have you already seen https://gdal.org/api/python_gotchas.html#saving-and-closing-datasets-datasources?

**Comment by jratike80** [comment]
No, you understood it right, I just wanted to point that it is not a new observation and workaround is also documented in GDAL documentation, not only in gis.stackexchange.

Let's see if developers can tell why the situation is what it is, and what it would mean in real life to introduce a clean way to close.

**Comment by javierbg** [comment]
I agree with @s-m-e , this is a dangerous overlook as the garbage collector offers no guarantee for when resources will be freed.

Why isn't the `GDALClose()` function exposed in the Python API? Is there a technical problem preventing it? Exposing this function would at least allow users to close their datasets properly and even implement their own wrapper with an `__exit__()` method for use in a `with` block.

**Comment by rouault** [comment]
> Why isn't the `GDALClose()` function exposed in the Python API? Is there a technical problem preventing it?

The technical problem is that, for a clean resolution, we'd also need to make sure that any further call to this Python Dataset object (and any object that it owns indirectly through the corresponding C++ GDALDataset) doesn't lead to a crash. Which would involve likely quite a lot of boilerplate in the SWIG .i files

**Comment by jratike80** [comment]
Is this resolved by https://github.com/OSGeo/gdal/pull/8454?

**Comment by rouault** [comment]
yes
