### ISSUE TITLE
OpenEx fails to open compressed ENVI raster

### ISSUE THREAD

**Issue by jakimowb** [OSGeo/gdal#3876]
## Expected behavior and actual behavior.

The expected behavior is, that `gdal.OpenEx` is able to open a compressed ENVI raster image, as `gdal.Open` still does.

However, since GDAL 3.3. the actual behavior seem to be that `gdal.OpenEx` throws an error instead:

> Driver GTM is considered for removal in GDAL 3.5. You are invited to convert any dataset in that format to another more common one .If you need this driver in future GDAL versions, create a ticket at https://github.com/OSGeo/gdal (look first for an existing one first) to explain how critical it is for you (but the GDAL project may still remove it), and to enable it now, set the GDAL_ENABLE_DEPRECATED_DRIVER_GTM configuration option / environment variable to YES

Opening uncompressed files works fine. I wounder why the error refers to the GTM driver and not the ENVI driver.
I discovered this when looking for reasons why QGIS 3.19 (GDAL 3.3) fails to open compressed image, while QGIS 3.18.2 (GDAL 3.2.2) does not.

## Steps to reproduce the problem.

1. download and unzip [envi_driver_bug_example.zip](https://github.com/OSGeo/gdal/files/6526002/envi_driver_bug_example.zip). It contains two raster, envi_uncompressed.bsq and envi_compressed.bsq, and an example script envi_driver_example.py

2. open a CLI with gdal-enabled python and run `python envi_driver_example.py`

````python
import pathlib
from osgeo import gdal
TEST_DATA_DIR = pathlib.Path(__file__).parent
path_uncompressed = TEST_DATA_DIR / 'envi_uncompressed.bsq'
path_compressed = TEST_DATA_DIR / 'envi_compressed.bsq'

print(gdal.VersionInfo(''))
for path in [path_uncompressed.as_posix(),
             path_compressed.as_posix()]:
    print(f'Test {path}')
    assert isinstance(gdal.Open(path), gdal.Dataset), f'Unable to open {path} by gdal.Open()'

    # this fails with compressed ENVI file and thows an error like
    # "ERROR 1: Driver GTM is considered for removal in GDAL 3.5 ..."
    assert isinstance(gdal.OpenEx(path), gdal.Dataset), f'Unable to open {path} by gdal.OpenEx()'

````

## Operating system

Windows 10

## GDAL version and provenance

GDAL 3.3.0, released 2021/04/26, installed via OSGeo4W

**Comment by rouault** [comment]
works fine with current GDAL versions:
```
$ python envi_driver_example.py
GDAL 3.5.2, released 2022/09/25
Test ../../gdal/build_cmake/envi_uncompressed.bsq
Test ../../gdal/build_cmake/envi_compressed.bsq
```

**Comment by jakimowb** [comment]
Thanks a lot for taking care!
