### ISSUE TITLE
OGR Access MDB Driver appears unable to parse certain numbers

### ISSUE THREAD

**Issue by Saijin-Naib** [OSGeo/gdal#3885]
## Expected behavior and actual behavior.
For some odd reason QGIS does not properly read some records from some columns of a vanilla/aspatial Access MDB when joined against a GPKG with mixed spatial/aspatial data.

## Steps to reproduce the problem.
Have GPKG with geometries and some tabular data joined against a completely vanilla/aspatial MDB
Note that some records in QGIS are not parsed/loaded correctly (For example, CAMP_Length)
Verify that these records can be recalled properly outside of QGIS/OGRinfo

## Operating system
OS Name	Microsoft Windows 10 Pro
Version	10.0.19043 Build 19043

## GDAL version and provenance
GDAL 3.3.0 from OSGeo4W-NG

## Further Information
QGIS view:  
![image](https://user-images.githubusercontent.com/19295950/119404253-8dd76600-bcad-11eb-8533-534a3049596a.png)
Note how many segments have a CAMP_Length of 0. This is not valid. Some records in the dataset are NULL, but they show properly as NULL.

Compare to the view in CAMP-RS:  
![image](https://user-images.githubusercontent.com/19295950/119404336-a778ad80-bcad-11eb-8674-ac6a1208b03e.png)

Compare to the view in MDBPlus:  
![image](https://user-images.githubusercontent.com/19295950/119404431-cbd48a00-bcad-11eb-9a6f-2d61641bbe1a.png)

```
PS C:\OSGeo4W64\bin> .\ogrinfo.exe -fields=yes -sql "SELECT * FROM Inventory" Q:\User\Brett_Carlock\Projects\QGIS\Data\CAMP-RS\CAMP-RS.mdb > stdout 2> stderr
```

It looks like OGR isn't reading some of the values properly, at least according to stderr. I guess these are the ones that read out as 0 when they should not be.

It is tricky to pick out in the stdout because BEGIN_MP of 0 is totally valid, especially for a segment that begins that roadway (the milepoint of that roadway would normally begin at 0.0mi and increase from there). However, END_MP and LENGTH can NEVER be 0, so any records that OGR parses with those as 0 are erroneous. NULL is perfectly acceptable.

[stdout.txt](https://github.com/qgis/QGIS/files/6539643/stdout.txt)
[stderr.txt](https://github.com/qgis/QGIS/files/6539644/stderr.txt)

**Additional context**
Same dataset as Issue #43287 
https://github.com/qgis/QGIS/issues/43287#issuecomment-847312168

**Comment by nyalldawson** [comment]
@rouault can you assign to me?

**Comment by nyalldawson** [comment]
I've been looking into this one, and I believe it's an issue in the Microsoft Access ODBC driver itself when a numeric field is fetched as a character value. I can avoid the issue if I instead request the attribute as a float/double value, but that change is quite intrusive...

**Comment by Saijin-Naib** [comment]
Even if I'm not accessing it via ODBC?

Things like MDBPlus use MDAC (built into Windows 10) and serve it up fine.

Intrusive sounds not great, though I suppose the likelihood of anyone upstream at Microsoft taking this on is basically zero, as I imagine this would have massive knock-on effects...

Can we ship mdbtools with QGIS for OSGeo4W-NG, Mac, and Linux and have that access Access instead of using platform ODBC or otherwise? If I'm not mistaken, you've done an absolute ton of work on that recently.

**Comment by nyalldawson** [comment]
> Even if I'm not accessing it via ODBC Control Panel, but only relying upon the Microsoft Access 2013 Runtime?

Internally GDAL is still using the ODBC driver for access to read this. 

> Things like MDBPlus use MDAC (built into Windows 10) and serve it up fine.

I suspect these are fetching attributes using their actual data types, instead of always fetching CHAR values (which is what GDAL does)

> Can we ship mdbtools with QGIS for OSGeo4W-NG, Mac, and Linux and have that access Access instead of using platform ODBC or otherwise? If I'm not mistaken, you've done an absolute ton of work on that recently.

Potentially, but it would need a whole new GDAL driver (which uses mdbtools directly instead of going through ODBC). It's a non-trivial piece of work, but the benefit would be that any GDAL install would be able to read mdb without the need for additional drivers...

**Comment by Saijin-Naib** [comment]
Ah, I completely misunderstood how GDAL was accessing Access. Thanks!

Oh, okay. Would it have any value if I reached out to the creator of MDBPlus to confirm that's what they're doing to fetch attributes?

This sounds like a major undertaking...
Community fund-raising, or would it be best top-down from organization level?

**Comment by jgrocha** [comment]
I know that it does help much, but using the old other driver
