### ISSUE TITLE
GDAL linking to system libjson-c instead of requested libjson-c

### ISSUE THREAD

**Issue by adamjstewart** [OSGeo/gdal#3895]
## Expected behavior and actual behavior.

I'm trying to install GDAL using an existing installation of `libjson-c`. I'm telling `configure` where to find it using `--with-libjson-c`. According to the `config.log`, the build does pick up the right version of `libjson-c`, but ultimately links against the system version and the build crashes with:
```
/gcc/g++  gdalinfo_bin.lo  /data/geol552/a/adamjs5/spack-stage-gdal-3.2.3-ozkzmsnz4b4ucfeag6ezpb7xg6e67kpf/spack-src/libgdal.la  -o gdalinfo
/data/geol552/a/adamjs5/spack-stage-gdal-3.2.3-ozkzmsnz4b4ucfeag6ezpb7xg6e67kpf/spack-src/.libs/libgdal.so: undefined reference to `json_object_get_userdata'
/data/geol552/a/adamjs5/spack-stage-gdal-3.2.3-ozkzmsnz4b4ucfeag6ezpb7xg6e67kpf/spack-src/.libs/libgdal.so: undefined reference to `json_c_object_sizeof'
collect2: error: ld returned 1 exit status
make[1]: *** [GNUmakefile:90: gdalinfo] Error 1
make[1]: Leaving directory '/data/geol552/a/adamjs5/spack-stage-gdal-3.2.3-ozkzmsnz4b4ucfeag6ezpb7xg6e67kpf/spack-src/apps'
make: *** [GNUmakefile:120: apps-target] Error 2
```
```console
$ ldd -r /data/geol552/a/adamjs5/spack-stage-gdal-3.2.3-ozkzmsnz4b4ucfeag6ezpb7xg6e67kpf/spack-src/.libs/libgdal.so
	linux-vdso.so.1 =>  (0x00007ffc92ffb000)
	libjson-c.so.2 => /lib64/libjson-c.so.2 (0x00002ada82e03000)
	libjpeg.so.62 => /data/keeling/a/adamjs5/spack/opt/spack/linux-centos7-x86_64/gcc-9.3.0/libjpeg-turbo-2.0.6-2uplqkmzpxxntoli3z4gno2r3ov4txq7/lib64/libjpeg.so.62 (0x00002ada8300e000)
	libgeotiff.so.5 => /data/keeling/a/adamjs5/spack/opt/spack/linux-centos7-x86_64/gcc-9.3.0/libgeotiff-1.6.0-yq4is6bs7taipfuyi2uqraenrwcyxvuk/lib/libgeotiff.so.5 (0x00002ada832a3000)
	liblzma.so.5 => /data/keeling/a/adamjs5/spack/opt/spack/linux-centos7-x86_64/gcc-9.3.0/xz-5.2.5-tlrh4ts46kmxzwx34ay7d7fdk6m4y3xd/lib/liblzma.so.5 (0x00002ada834d7000)
	libproj.so.19 => /data/keeling/a/adamjs5/spack/opt/spack/linux-centos7-x86_64/gcc-9.3.0/proj-7.2.1-dzvrkjdzoy42ivr6acuticd4eqvs66ul/lib/libproj.so.19 (0x00002ada836fd000)
	libtiff.so.5 => /data/keeling/a/adamjs5/spack/opt/spack/linux-centos7-x86_64/gcc-9.3.0/libtiff-4.1.0-ufpixfx7frhh37ovmfvqnil6mnwzvx7g/lib/libtiff.so.5 (0x00002ada83c5f000)
	libz.so.1 => /data/keeling/a/adamjs5/spack/opt/spack/linux-centos7-x86_64/gcc-9.3.0/zlib-1.2.11-o5eyrr46zecie66pglu4lamuqvhpcrkl/lib/libz.so.1 (0x00002ada83eda000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00002ada840f1000)
	librt.so.1 => /lib64/librt.so.1 (0x00002ada8430d000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00002ada84515000)
	libiconv.so.2 => /data/keeling/a/adamjs5/spack/opt/spack/linux-centos7-x86_64/gcc-9.3.0/libiconv-1.16-3h4ijv3dekrsfiejax5zgakffztcr4a5/lib/libiconv.so.2 (0x00002ada84719000)
	libstdc++.so.6 => /sw/gcc-9.3.0/lib/../lib64/libstdc++.so.6 (0x00002ada84a16000)
	libm.so.6 => /lib64/libm.so.6 (0x00002ada84df0000)
	libc.so.6 => /lib64/libc.so.6 (0x00002ada850f2000)
	/lib64/ld-linux-x86-64.so.2 (0x00002ada81c7d000)
	libgcc_s.so.1 => /sw/gcc-9.3.0/lib/../lib64/libgcc_s.so.1 (0x00002ada854c0000)
	libsqlite3.so.0 => /data/keeling/a/adamjs5/spack/opt/spack/linux-centos7-x86_64/gcc-9.3.0/sqlite-3.35.5-7nsxx6bdqfxhbzubr3qo5xtjwkmcyeaw/lib/libsqlite3.so.0 (0x00002ada856d8000)
	libcurl.so.4 => /data/keeling/a/adamjs5/spack/opt/spack/linux-centos7-x86_64/gcc-9.3.0/curl-7.76.1-p24yzuljbvtdkotcts7twz5d245fbwlx/lib/libcurl.so.4 (0x00002ada859fb000)
	libidn2.so.0 => /data/keeling/a/adamjs5/spack/opt/spack/linux-centos7-x86_64/gcc-9.3.0/libidn2-2.3.0-pb37dfy42weiwnilmp7gjumphgei7k7j/lib/libidn2.so.0 (0x00002ada85c7d000)
	libssl.so.1.1 => /data/keeling/a/adamjs5/spack/opt/spack/linux-centos7-x86_64/gcc-9.3.0/openssl-1.1.1k-fpqvofqgdeat5is2k6am5dzinbxcz2tu/lib/libssl.so.1.1 (0x00002ada85e9d000)
	libcrypto.so.1.1 => /data/keeling/a/adamjs5/spack/opt/spack/linux-centos7-x86_64/gcc-9.3.0/openssl-1.1.1k-fpqvofqgdeat5is2k6am5dzinbxcz2tu/lib/libcrypto.so.1.1 (0x00002ada86130000)
	libunistring.so.2 => /data/keeling/a/adamjs5/spack/opt/spack/linux-centos7-x86_64/gcc-9.3.0/libunistring-0.9.10-72fcbpxxc3gvpxptlj4i7u5aqow3cyqt/lib/libunistring.so.2 (0x00002ada86615000)
undefined symbol: json_object_get_userdata	(/data/geol552/a/adamjs5/spack-stage-gdal-3.2.3-ozkzmsnz4b4ucfeag6ezpb7xg6e67kpf/spack-src/.libs/libgdal.so)
undefined symbol: json_c_object_sizeof	(/data/geol552/a/adamjs5/spack-stage-gdal-3.2.3-ozkzmsnz4b4ucfeag6ezpb7xg6e67kpf/spack-src/.libs/libgdal.so)
```
## Steps to reproduce the problem.

```console
$ configure ... --with-libjson-c=/data/keeling/a/adamjs5/spack/opt/spack/linux-centos7-x86_64/gcc-9.3.0/json-c-0.15-jypilhqx24qxiynsqbfypwqjf7gsheib
```
See the following files for the full build log and environment variables used:

* [build log](https://github.com/OSGeo/gdal/files/6556509/spack-build-out.txt)
* [build env](https://github.com/OSGeo/gdal/files/6556511/spack-build-env.txt)
* [config.log](https://github.com/OSGeo/gdal/files/6556519/config.txt)

## Operating system

This error has occurred on the following operating systems:

* CentOS 7.9.2009 64-bit
* RHEL 7 64-bit

## GDAL version and provenance

I'm attempting to install GDAL using the [Spack](https://spack.io) package manager. The above failure happens for both GDAL 3.3.0 and 3.2.3.

Originally reported by @tldahlgren in https://github.com/spack/spack/issues/23943

P.S. If anyone wants to help me maintain Spack's GDAL recipe, please let me know!

**Comment by rouault** [comment]
GDAL configure doesn't use rpath, so you have to set LD_LIBRARY_PATH appropriately (or perhaps just specify LDFLAGS to add the rpath invokation)

**Comment by adamjstewart** [comment]
Spack contains compiler wrappers that inject RPATHs automatically, so I would expect this to still work. The build picks up all of my other libraries without any problems. Also, the process is failing during build-time, not during run-time, so I would still expect the build to succeed. Am I missing something?

**Comment by rouault** [comment]
In config.log, I  just see ``-rpath /data/keeling/a/adamjs5/spack/opt/spack/linux-centos7-x86_64/gcc-9.3.0/gdal-3.2.3-ozkzmsnz4b4ucfeag6ezpb7xg6e67kpf/lib``   . This isn't going to work with your json-c build in ``/data/keeling/a/adamjs5/spack/opt/spack/linux-centos7-x86_64/gcc-9.3.0/json-c-0.15-jypilhqx24qxiynsqbfypwqjf7gsheib/lib`` . You woud likely need a ``-Wl,-rpath=/data/keeling/a/adamjs5/spack/opt/spack/linux-centos7-x86_64/gcc-9.3.0/json-c-0.15-jypilhqx24qxiynsqbfypwqjf7gsheib/lib -ljson-c``

**Comment by adamjstewart** [comment]
Yes, if the compiler wrappers are called with `-L/path/to/lib`, they should automatically add `-Wl,-rpath=/path/to/lib` to the call line. I'll see if I can get you a build log that contains the flags added by the compiler wrappers...

**Comment by adamjstewart** [comment]
Okay, here are the promised logs. The first file contains all of the calls to the compiler wrapper. The second file contains what the compiler wrappers actually ran. As you can see, we're using `-Wl,-rpath,/data/keeling/a/adamjs5/spack/opt/spack/linux-centos7-x86_64/gcc-9.3.0/json-c-0.15-jypilhqx24qxiynsqbfypwqjf7gsheib/lib64` as expected.

* [compiler wrapper input](https://github.com/OSGeo/gdal/files/6557420/spack-cc-gdal-c6jts6v.in.log)
* [compiler wrapper output](https://github.com/OSGeo/gdal/files/6557421/spack-cc-gdal-c6jts6v.out.log)

**Comment by adamjstewart** [comment]
Any updates on this? @davidhoover reported that symlinking the json-c installation prefix `lib64` directory to `lib` solved the problem.

**Comment by rouault** [comment]
> Any updates on this? @davidhoover reported that symlinking the json-c installation prefix `lib64` directory to `lib` solved the problem.

how should GDAL guess that the lib is in $libjson_prefix/lib64 instead of standard $libjson_prefix/lib ?

**Comment by adamjstewart** [comment]
It should either check both lib and lib64, or allow users to specify which directory to search.

**Comment by adamjstewart** [comment]
On RHEL/CentOS/Fedora, lib64 is more commonly used than lib, so I wouldn't consider lib to be standard.

**Comment by adamjstewart** [comment]
Also, my compiler wrappers seem to be injecting `-L/data/keeling/a/adamjs5/spack/opt/spack/linux-centos7-x86_64/gcc-9.3.0/json-c-0.15-jypilhqx24qxiynsqbfypwqjf7gsheib/lib64 -Wl,-rpath,/data/keeling/a/adamjs5/spack/opt/spack/linux-centos7-x86_64/gcc-9.3.0/json-c-0.15-jypilhqx24qxiynsqbfypwqjf7gsheib/lib64`, so the build should look there anyway.

**Comment by adamjstewart** [comment]
Encountered this again on a different CentOS 7 system.

**Comment by adamjstewart** [comment]
This is still an issue for me on Frontera (CentOS 7)

**Comment by rouault** [comment]
Better control of which library is linked should come with the new CMake build system available in master. Closing that one as we are unlikely to be fix that with the autoconf build system
