### ISSUE TITLE
ESRI File Geodatabase raster support

### ISSUE THREAD

**Issue by gubuntu** [OSGeo/gdal#3901]
It seems this Trac ticket might not have been reported in GitHub and there is still a need for this

https://trac.osgeo.org/gdal/ticket/7008

The project that should enable this is actively maintained https://github.com/r-barnes/ArcRasterRescue

**Comment by MichiHo** [comment]
Raster layers are supported, starting with GDAL 3.7. I guess this ticket can be closed?
