### ISSUE TITLE
gdal2tiles with -w leaflet and --xyz incorrectly generates tms: true

### ISSUE THREAD

**Issue by zdila** [OSGeo/gdal#3903]
`gdal2tiles.py` with `-w leaflet` and `--xyz` incorrectly generates `tms: true` in `L.tileLayer` options. For XYZ this Leaflet option should not be specified (or should be `false`).

**Comment by jratike80** [comment]
Confirmed with GDAL 3.1.4. The command

`gdal2tiles.py -w leaflet --xyz p4433h.tif leaftest`

created Leaflet page that does not show the image without editing the html into

`var lyr = L.tileLayer('./{z}/{x}/{y}.png', {tms: false, opacity: 0.7, attribution: "", minZoom: 11, maxZoom: 17});`

**Comment by rouault** [comment]
This has been fixed in GDAL 3.3.0 per #3359
