### ISSUE TITLE
Compiling gdal 3.3.0 on Alma Linux fails

### ISSUE THREAD

**Issue by ncastrog** [OSGeo/gdal#3922]
## Expected behavior and actual behavior.

Compiling fails on Alma Linux fails using:
 ./configure --with-python=/usr/bin/python3 --with-pg

## Steps to reproduce the problem.

Download source code , decompress and execute ./ configure
./configure --with-python=/usr/bin/python3 --with-pg
checking for PostgreSQL... checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.21... yes
checking for PQ... no
configure: error: --with-pg was requested, but libpq is not available

if i run ldconfig the libpq library is installed.

/usr/pgsql-13/lib: (from /etc/ld.so.conf.d/postgresql-pgdg-libs.conf:1)
        libpgrouting-3.1.so -> libpgrouting-3.1.so
        libpqwalreceiver.so -> libpqwalreceiver.so
        libpq.so.5 -> libpq.so.5.13 ---------------------------------------------> libpq
        libpgtypes.so.3 -> libpgtypes.so.3.13
        libecpg_compat.so.3 -> libecpg_compat.so.3.13
        libecpg.so.6 -> libecpg.so.6.13

## Operating system

Alma Linux kernel 4.18.0-305.el8.x86_64

## GDAL version and provenance
gdal 3.3.0 from source code.

**Comment by rouault** [comment]
What does the following report ?
pkg-config --modversion libpq
pkg-config --cflags libpq
pkg-config --libs libpq

Please also attach ``config.log`` generated by configure

**Comment by ncastrog** [comment]
Thanks.

(pydev) [root@localhost gdal-3.3.0]# pkg-config --modversion libpq
Package libpq was not found in the pkg-config search path.
Perhaps you should add the directory containing `libpq.pc'
to the PKG_CONFIG_PATH environment variable
Package 'libpq', required by 'virtual:world', not found

(pydev) [root@localhost gdal-3.3.0]# pkg-config --cflags libpq
Package libpq was not found in the pkg-config search path.
Perhaps you should add the directory containing `libpq.pc'
to the PKG_CONFIG_PATH environment variable
Package 'libpq', required by 'virtual:world', not found

(pydev) [root@localhost gdal-3.3.0]# pkg-config --libs libpq
Package libpq was not found in the pkg-config search path.
Perhaps you should add the directory containing `libpq.pc'
to the PKG_CONFIG_PATH environment variable
Package 'libpq', required by 'virtual:world', not found


[config.log](https://github.com/OSGeo/gdal/files/6577574/config.log)

**Comment by rouault** [comment]
ok then you need to set PKG_CONFIG_PATH=/usr/pgsql-13/lib/pkgconfig before running ./configure

**Comment by ncastrog** [comment]
Thanks it worked.

(pydev) [root@localhost gdal-3.3.0]# gdalinfo --formats
Supported Formats:
  VRT -raster,multidimensional raster- (rw+v): Virtual Raster
  DERIVED -raster- (ro): Derived datasets using VRT pixel functions
  GTiff -raster- (rw+vs): GeoTIFF
  COG -raster- (wv): Cloud optimized GeoTIFF generator
  NITF -raster- (rw+vs): National Imagery Transmission Format
  RPFTOC -raster- (rovs): Raster Product Format TOC format
  ECRGTOC -raster- (rovs): ECRG TOC format
  HFA -raster- (rw+v): Erdas Imagine Images (.img)
...
