### ISSUE TITLE
DXF: "Assertion `iSrcBufferOffset <= nSrcBufferBytes' failed in file `ogrdxfreader.cpp', line 105"

### ISSUE THREAD

**Issue by rouault** [OSGeo/gdal#3936]
CC @atlight 

From https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=34927

After https://github.com/OSGeo/gdal/pull/3909, we get a crash on the attached file. 
[clusterfuzz-testcase-minimized-shape_fuzzer-6126814756995072.zip](https://github.com/OSGeo/gdal/files/6598600/clusterfuzz-testcase-minimized-shape_fuzzer-6126814756995072.zip)

$ ogrinfo -al clusterfuzz-testcase-minimized-shape_fuzzer-6126814756995072 
INFO: Open of `clusterfuzz-testcase-minimized-shape_fuzzer-6126814756995072'
      using driver `DXF' successful.

Layer name: entities
Geometry: Unknown (any)
ERROR 7: Assertion `iSrcBufferOffset <= nSrcBufferBytes' failed in file `ogrdxfreader.cpp', line 105
Abandon (core dumped)

**Comment by atlight** [comment]
Fixed this one, but I wouldn't be shocked if fuzzer finds more problems with this.

**Comment by rouault** [comment]
> but I wouldn't be shocked if fuzzer finds more problems with this.

indeed, there's another issue with the attached test case  from https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=35080 

[clusterfuzz-testcase-minimized-dxf_fuzzer-5400376672124928.zip](https://github.com/OSGeo/gdal/files/6618964/clusterfuzz-testcase-minimized-dxf_fuzzer-5400376672124928.zip)


```
$ ogrinfo clusterfuzz-testcase-minimized-dxf_fuzzer-5400376672124928 -al
INFO: Open of `clusterfuzz-testcase-minimized-dxf_fuzzer-5400376672124928'
      using driver `DXF' successful.

Layer name: entities
Geometry: Unknown (any)
ERROR 7: Assertion `nLastValueSize > 0' failed in file `ogrdxfreader.cpp', line 298
Abandon (core dumped)
```
