### ISSUE TITLE
Reading MID/MIF format files with long lines

### ISSUE THREAD

**Issue by tomalrussell** [OSGeo/gdal#3943]
## Expected behavior and actual behavior.

I expect to be able to open or convert the MIF/MID files in [PHL_fluvial_rcp4p5.zip](https://github.com/OSGeo/gdal/files/6610944/PHL_fluvial_rcp4p5.zip). Currently GDAL fails to read the second feature.

I think this is due to the length of the line in the MID file (10,370 characters) - which would correspond to the MIDMAXCHAR constant in [gdal/ogr/ogrsf_frmts/mitab/mitab_priv.h, line 1910](https://github.com/OSGeo/gdal/blob/2cd5a96c74ea993f4acd774f7b9952a4d36be59c/gdal/ogr/ogrsf_frmts/mitab/mitab_priv.h#L1910). 

If I change it to 100,000 and recompile as in [CONTRIBUTING.md](https://github.com/OSGeo/gdal/blob/master/CONTRIBUTING.md), it reads both features okay. 

I wonder if there's a way of passing a runtime or compilation flag to configure this?

This is a dataset with an unusually large number of columns, and could well be reworked or split to avoid hitting this limit. For context, this is the project where the issue came up: https://github.com/oi-analytics/oi-risk-vis/issues/8.

## Steps to reproduce the problem.

Run `ogrinfo` to read through the file and `grep` for `osm_id` to minimise output and make it clear which features are read okay:

```bash
$ ogrinfo -ro PHL_fluvial_rcp4p5.mid PHL_fluvial_rcp4p5 | grep osm_id
# ... lots of warnings about field names
osm_id: String (254.0)
ERROR 1: Maximum number of characters allowed reached.
  osm_id (String) = 15787240
ERROR 3: Unexpected EOF while reading attribute record from MID file.
ERROR 6: Error during reading Record.

# check line lengths
$ cat PHL_fluvial_rcp4p5.mid | awk '{print length}' 
2847
10370
```

With patched MIDMAXCHAR:
```cpp
-#define MIDMAXCHAR 10000
+#define MIDMAXCHAR 100000
```

```bash
$ ogrinfo -ro  PHL_fluvial_rcp4p5.mid PHL_fluvial_rcp4p5 | grep osm_id
# ... lots of warnings about field names
osm_id: String (254.0)
  osm_id (String) = 15787240
  osm_id (String) = 23525388
```

## Operating system

Ubuntu 20.04 64 bit

## GDAL version and provenance

GDAL 3.2.1, released 2020/12/29, installed via miniconda.

Quick patch-test from GDAL 3.4.0dev-2cd5a96c74-dirty.

**Comment by craigds** [comment]
Does this limit exist for some security reason? We are hitting this when processing client data and wonder if there's any reason not to just change this limit to 1,000,000 and move on :)

**Comment by rouault** [comment]
> Does this limit exist for some security reason? We are hitting this when processing client data and wonder if there's any reason not to just change this limit to 1,000,000,000 and move on :)

It currently and initially exists because it is used to allocate a buffer of this size, so we can't put an arbitrarily large number, but this can be easily changed to a dynamically allocated one. However we likely need to put some limit to avoid denial of service on excessively large lines. Would 1 MB be OK for your use cases ? (you can check with wc -L)

**Comment by craigds** [comment]
Yes that looks great, thanks!
