### ISSUE TITLE
PDF: Pdfium backend doesn't honour GDAL_PDF_LAYERS_OFF

### ISSUE THREAD

**Issue by CartoLake** [OSGeo/gdal#3949]
Using the latest docker container (and seems to be on GDAL versions > 3.2.2), the GDAL_PDF_LAYERS_OFF option doesn't seem to be working.  

## Expected behavior and actual behavior.

The layers set in the option aren't ignored when rendering the tif.

## Steps to reproduce the problem.

Here's a set of steps to illustrate the problem using a sample PDF from the USGS.  

1. Create working dir
mkdir ~/Desktop/pdftest

2. Download the PDF to the working directory
curl -o ~/Desktop/pdftest/MA_Worcester_North_20210309_TM_geo.pdf https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/USTopo/PDF/MA/MA_Worcester_North_20210309_TM_geo.pdf

3. Pull the latest code
docker pull osgeo/gdal:ubuntu-full-latest

3.1 Get GDAL version
docker run --rm -t osgeo/gdal:ubuntu-full-latest gdalinfo --version 
Version as of issue submission: GDAL 3.4.0dev-36e6f4be69f41a9f67387019d43cc3aa52ffd180, released 2021/06/01

4. Get a list of the layers to double check list below
docker run --rm -t -v ~/Desktop/pdftest:/perm osgeo/gdal:ubuntu-full-latest gdalinfo /perm/MA_Worcester_North_20210309_TM_geo.pdf -mdd LAYERS

5. Run warp.
docker run --rm -t -v ~/Desktop/pdftest:/perm osgeo/gdal:ubuntu-full-latest gdalwarp -of GTiff -overwrite perm/MA_Worcester_North_20210309_TM_geo.pdf perm/MA_Worcester_North_20210309_TM_geo.latest.100.tif --config GDAL_PDF_DPI 100 --config GDAL_PDF_LAYERS_OFF "Map_Collar,Map_Frame.Projection_and_Grids,Images,Images.Orthoimage,Barcode" 

However, 3.2.2 works as expected
docker pull osgeo/gdal:ubuntu-full-3.2.2

docker run --rm -t -v ~/Desktop/pdftest:/perm osgeo/gdal:ubuntu-full-3.2.2 gdalinfo /perm/MA_Worcester_North_20210309_TM_geo.pdf -mdd LAYERS

docker run --rm -t -v ~/Desktop/pdftest:/perm osgeo/gdal:ubuntu-full-3.2.2 gdalwarp -of GTiff -overwrite perm/MA_Worcester_North_20210309_TM_geo.pdf perm/MA_Worcester_North_20210309_TM_geo.322.100.tif --config GDAL_PDF_DPI 100 --config GDAL_PDF_LAYERS_OFF "Map_Collar,Map_Frame.Projection_and_Grids,Images,Images.Orthoimage,Barcode" 

## Operating system
Ubuntu docker build

## GDAL version and provenance
Latest compared to 3.2.2

Example of 3.2.2 and latest next to each other
<img width="1535" alt="Screen Shot 2021-06-08 at 6 46 55 PM" src="https://user-images.githubusercontent.com/82988795/121267786-b7d28000-c88a-11eb-96e1-875f7e8ba81d.png">

**Comment by rouault** [comment]
This appears to be an issue with the Pdfium backend that is enabled in the recent images.
You can workaround the issue by adding ``--config GDAL_PDF_LIB poppler``

**Comment by rouault** [comment]
I've investigated and I believe that the PDF file is malformed. When using the Poppler backend, one can see error messages like
ERROR 1: Pos = 43114454, insufficient arguments for Marked Content
ERROR 1: Pos = 43114471, insufficient arguments for Marked Content
ERROR 1: Pos = 43114479, insufficient arguments for Marked Content

Marked Content is the mechanism use for layers in PDF. So it seems that Poppler is a bit more robust here than PDFium. PDFium could perhaps be improved (you can report the issue at https://bugs.chromium.org/p/pdfium/issues/list I beleive, possibly pointing to this thread for the above analysis), but GDAL itself cannot do anything when using it.
