### ISSUE TITLE
Docker images do not (fully) support connections to postgresql over ssl (ogr2ogr)

### ISSUE THREAD

**Issue by anneb** [OSGeo/gdal#3950]
## Expected behavior and actual behavior.

expected 
ogr2ogr can connect to PostgreSQL where SSL is required

## Steps to reproduce the problem.
ogr2ogr -f \"PostgreSQL\" PG:\"host=dbhost.example.com user=myuser dbname=mydb password=xxxx port=5432 sslmode=require\"

Results in the following error:
sslmode value "require" invalid when SSL support is not compiled in

## Operating system
docker images:
osgeo/gdal:ubuntu-small-3.3.0
osgeo/gdal:alpine-normal-3.3.0

## GDAL version and provenance
osgeo/gdal:ubuntu-small-3.3.0
osgeo/gdal:alpine-normal-3.3.0

**Comment by rouault** [comment]
> Results in the following error:

weird. AFAICS, both docker images have a libpq.so with libssl support. Are you really the above ogr2ogr command line within those images ?

**Comment by anneb** [comment]
I can no longer reproduce the problem. ogr2ogr SSL works fine using both Docker images. Weird indeed. I must have 'tested' some other instance of ogr2ogr. Apologies for wasting your time.
