### ISSUE TITLE
need help! how java call warp use WarpOptions as param,

### ISSUE THREAD

**Issue by youraregood** [OSGeo/gdal#3952]
## Expected behavior and actual behavior.

public  void gdaldata(){
    gdal.AllRegister();

    String shpPath ="C:\\MapDownload\\OutPut\\a\\clip.shp";
    Vector vector =new Vector();
    vector.add("xRes=150");
    vector.add("yRes=150");
    WarpOptions warpOptions=new WarpOptions(vector);
    String path ="C:\\MapDownload\\OutPut\\a\\ks_new.tif";
    Dataset olddata=  gdal.Open(path);
    Dataset newdata = gdal.Warp("C:\\MapDownload\\OutPut\\a\\test121281.tiff",new Dataset[]{data},warpOptions);
    newdata .delete();

  }

**i want modify olddata xres yres, but  it didn't  work,  is ”xRes=150“ param right?**

## Steps to reproduce the problem.

For example (please modify !!!): "gdalinfo myfile"

## Operating system

For example (please modify !!!): Ubuntu 16.04 64 bit

## GDAL version and provenance

For example (please modify !!!): the 2.2.3 version from ubuntugis-unstable PPA

**Comment by rouault** [comment]
You need to use the same syntax as the command line utility, so that would be something along
vector.add("-tr");
vector.add("150");
vector.add("150");
