### ISSUE TITLE
GTiff  signedbyte : zero values written instead of negative nodata value for tiles/strips entirely at the nodata value

### ISSUE THREAD

**Issue by sgillies** [OSGeo/gdal#3984]
While working on write support for int8 arrays in rasterio https://github.com/mapbox/rasterio/issues/2180 I have found (I believe) that GDAL's IO functions depend on image structure metadata values being made persistent in a driver-specific way. For example, I can call GDALCreate with `driver=MEM` and `PIXELTYPE=SIGNEDBYTE` (in creation options) and then write a signed int buffer directly to the new dataset. But if I call GDALCreate with `driver=GTiff` and `PIXELTYPE=SIGNEDBYTE` (in creation options) I find that I have to close the dataset and reopen it in update mode before I can write a signed int buffer. So, I'm trying to switch to the later in rasterio. It does fix the issue reported in #2180.

However, the change has destabilized other parts of rasterio. Color interpretation is one. For GeoTIFFs, the effect of `PHOTOMETRIC=CMYK` is lost when a dataset created with `driver=GTiff` and `PHOTOMETRIC=CMYK` is re-opened in update mode.

Is there a driver-independent best practice for creating a new dataset and writing data to it? Is there a simple split into creation-only and other formats? Or is it very driver specific?

**Comment by rouault** [comment]
> But if I call GDALCreate with `driver=GTiff` and `PIXELTYPE=SIGNEDBYTE` (in creation options) I find that I have to close the dataset and reopen it in update mode before I can write a signed int buffer.

Sounds like a bug of the GTiff driver. You shouldn't have to close & re-open

> For GeoTIFFs, the effect of PHOTOMETRIC=CMYK is lost when a dataset created with driver=GTiff and PHOTOMETRIC=CMYK is re-opened in update mode.

CMYK handling is particular indeed. On re-opening, one uses the TIFF RGBA interface for such exotic colorspaces

> Is there a driver-independent best practice for creating a new dataset and writing data to it? 

Directly write to it is the recommended way (pending bugs like the one you spotted with signedbyte in TIFF)

**Comment by rouault** [comment]
> Sounds like a bug of the GTiff driver. You shouldn't have to close & re-open

Looking a bit at the code, I can't see where this would be faulty. Could you demonstrate the issue with some C code or use of GDAL Python API ?  Note that the handling of PIXELTYPE=SIGNEDBYTE in GDAL is super hacky : this is mostly an interpretation hint of the data for the user. You need to pass the signed byte content as cast to unsigned byte, ie you need to write -1 as 255.

**Comment by sgillies** [comment]
@rouault here's my attempt to reproduce in GDAL's autotests what we see in rasterio: https://travis-ci.com/github/OSGeo/gdal/jobs/515100573#L15722.
