### ISSUE TITLE
How to use  gdal dataset.AddBand() API in java

### ISSUE THREAD

**Issue by PingYufeng** [OSGeo/gdal#3989]
String inputFilePath = "D:\\rgb2714.tif";
 Dataset ds = gdal.Open(inputFilePath, gdalconstConstants.GA_Update);

byte[] redData = new byte[ds.getRasterXSize() * ds.getRasterYSize()];
ds.GetRasterBand(1).ReadRaster(0, 0, ds.getRasterXSize() , ds.getRasterYSize(), gdalconstConstants.GDT_Byte, redData);

byte[] alphaData = new byte[ds.getRasterXSize() * ds.getRasterYSize()];
for (int i = 0; i < redData.length; i++) {
      if (redData[i] == 0) {
                alphaData[i] = 0;
            }else {
                alphaData[i] = -1;
      }
}

**Comment by jratike80** [comment]
I believe that you did see this notice so I am closing as we promise.

> IMPORTANT: Do NOT use GitHub to post any questions or support requests!
>            They will be closed immediately and ignored.
> 
> Questions should go to the gdal-dev mailing list at
> https://lists.osgeo.org/mailman/listinfo/gdal-dev
> or other support forums. GitHub issues are for bug
> reports and suggestions for new features.
