### ISSUE TITLE
symbol lookup error

### ISSUE THREAD

**Issue by Navid61** [OSGeo/gdal#3995]
## Expected behavior and actual behavior.

I'd expect sudo ./configure can prepare gdal-3.3.0 for installation correctly, but it can not find many driver
after installation when I did try for import geopackage to PostgreSQL I got this error:

symbol lookup error: /usr/local/lib/gdalplugins/gdal_LEGACY.so: undefined symbol: RegisterOGROpenAir
I should mention I did install Proj v 8 already

## Steps to reproduce the problem.

~:gdal-3.3.0>sudo ./configure
I got this error:
...

  Armadillo support:         no
  CFITSIO support:           no
  crypto/openssl support:    yes
  cryptopp support:          no
  cURL support (wms/wcs/...):no
  DDS support:               no
  DODS support:              no
  ECW support:               no
  Expat support:             yes
  EXR support:               no
  FGDB support:              no
  FreeXL support:            no
  GEORASTER support:         no
  GEOS support:              no
  Google libkml support:     no
  GRASS support:             no
  GTA support:               no
  HDF4 support:              no
  HDF5 support:              no
  HDFS support:              no
  HEIF support:              no
  INFORMIX DataBlade support:no
  Ingres support:            no
  JP2Lura support:           no
  JPEG 12 bit:               no
  JPEG-in-TIFF 12 bit:       no
  JPEG JasPer support:       no
  JPEG-Lossless/CharLS:      no
  Kakadu support:            no
  Kea support:               no
  LERC support:              internal
  libdeflate support:        no
  LIBGEOTIFF support:        internal
  LIBGIF support:            internal
  LIBJPEG support:           external
  LIBLZMA support:           no
  LIBPNG support:            external
  LIBTIFF support:           external (BigTIFF=yes)
  libxml2 support:           yes
  LIBZ support:              external
  MDB support:               no
  MongoCXX v3 support:       no
  MongoDB support:           no
  MrSID/MG4 Lidar support:   no
  MrSID support:             no
  MSG support:               no
  MySQL support:             no
  NetCDF support:            no
  OCI support:               no
  ODBC support:              no
  OGDI support:              no
  OpenCL support:            no
  OpenJPEG support:          no
  PCIDSK support:            internal
  PCRaster support:          internal
  PCRE support:              yes
  PDFium support:            no
  Podofo support:            no
  Poppler support:           no
  PostgreSQL support:        no
  QHull support:             internal
  Rasdaman support:          no
  RasterLite2 support:       no
  RDB support:               no
  SFCGAL support:            no
  SOSI support:              no
  SpatiaLite support:        no
  SQLite support:            yes
  Teigha (DWG and DGNv8):    no
  TileDB support:            no
  userfaultfd support:       yes
  WebP support:              yes
  Xerces-C support:          no
  ZSTD support:              no

  misc. gdal formats:        aaigrid adrg aigrid airsar arg blx bmp bsb cals ceos ceos2 coasp cosar ctg dimap dted elas envisat ers esric fit gff gsg gxf hf2 idrisi ilwis ingr iris iso8211 jaxapalsar jdem kmlsuperoverlay l1b leveller map mrf msgn ngsgeoid nitf northwood pds prf r raw rmf rs2 safe saga sdts sentinel2 sgi sigdem srtmhgt stacta terragen tga til tsx usgsdem xpm xyz zmap rik ozi rasterlite mbtiles grib pdf
  misc. ogr formats:         arcgen avc cad csv dgn dxf edigeo flatgeobuf geoconcept georss gml gmt gpsbabel gpx gtm jml mapml mvt ntf openfilegdb pgdump rec s57 selafin shape svg sxf tiger vdv wasp idrisi pds sdts gpkg vfk osm ods xlsx lvbag

  disabled gdal formats:    
  disabled ogr formats:     

  SWIG Bindings:             no

  PROJ >= 6:                 yes
  enable GNM building:       yes
  enable pthread support:    yes
  enable POSIX iconv support:yes
  hide internal symb

## Operating system

LMDE v 4 (LinuxMint Debbie) Debian Version

## GDAL version and provenance

[config.txt](https://github.com/OSGeo/gdal/files/6663438/config.txt)
3.3.0 form github

**Comment by rouault** [comment]
The GeoPackage driver is mentionned in the "misc. ogr formats list" ("gpkg")
I'm not sure about the error related to "symbol lookup error: /usr/local/lib/gdalplugins/gdal_LEGACY.so: undefined symbol: RegisterOGROpenAir", but the https://github.com/OSGeo/gdal-extra-drivers repository is unsupported.
