### ISSUE TITLE
How can psNext or psChild not report nullptr's error ?

### ISSUE THREAD

**Issue by wenhwu** [OSGeo/gdal#4019]
How to modify struct CPLXMLNode in order to prevent **the error of nullptr** from being reported during the complicated XML reading process (For example, **psRoot->psChild->psNext->psNext->psChild->psChild->psChild->psNext->psNext->psChild->psChild**) ?

Thanks

**Comment by rouault** [comment]
Sorry, I don't understand your question. Can you be much more specific ? I assume this is an usage issue in your code, more than an error in GDAL itself ?

**Comment by wenhwu** [comment]
@rouault , thank you for your quickly reply.

You're right, it seems to be an usage issue in my code. I have to read a very complex XML file (which requires a long read process), so I am using a combination of psNext and psChild (for example, psRoot->psChild->psNext->psNext->psChild->psChild->psChild->psNext->psNext->psChild->psChild), but this is not stable and may crash the program prematurely by reading nullptr. Can psNext or psChild read nullptr and not crash, but return nullptr instead?

many thanks

**Comment by rouault** [comment]
> Can psNext or psChild read nullptr and not crash, but return nullptr instead?

well, if you dereference a nullptr, it will crash. This is basic C/C++ common rules. Nothing we can do about. cpl_minixml.h has a few accessors function that can make things a bit easier: CPLGetXMLNode(), CPLGetXMLValue(), etc.
