### ISSUE TITLE
LERC_PREC option not honored in Python

### ISSUE THREAD

**Issue by kwinwithak** [OSGeo/gdal#4024]
## Expected behavior and actual behavior.

The `LERC_PREC` option allows for control of LERC error tolerance when using `gdal_translate` to convert rasters to MRF. The Python bindings for GDAL should honor this option and produce lossier compression when the `LERC_PREC` value is increased. Instead, I'm finding that no matter what `LERC_PREC` value I specify, `gdal.Translate` always produces a lossless LERC file.

## Steps to reproduce the problem.

Using the command line, it's clear that core GDAL honors the `LERC_PREC` option and produces increasing levels of compression as the error allowed increases.
```
/usr/app# gdal_translate -of mrf -co COMPRESS=LERC -co OPTIONS="LERC_PREC=1 V2=ON" /vsicurl/http://landsat-pds.s3.amazonaws.com/c1/L8/086/240/LC08_L1GT_086240_20180827_20180827_01_RT/LC08_L1GT_086240_20180827_20180827_01_RT_B1.TIF out-lerc-prec-1.mrf
Input file size is 9151, 9151
0...10...20...30...40...50...60...70...80...90...100 - done.

/usr/app# gdal_translate -of mrf -co COMPRESS=LERC -co OPTIONS="LERC_PREC=2 V2=ON" /vsicurl/http://landsat-pds.s3.amazonaws.com/c1/L8/086/240/LC08_L1GT_086240_20180827_20180827_01_RT/LC08_L1GT_086240_20180827_20180827_01_RT_B1.TIF out-lerc-prec-2.mrf
Input file size is 9151, 9151
0...10...20...30...40...50...60...70...80...90...100 - done.

/usr/app# gdal_translate -of mrf -co COMPRESS=LERC -co OPTIONS="LERC_PREC=3 V2=ON" /vsicurl/http://landsat-pds.s3.amazonaws.com/c1/L8/086/240/LC08_L1GT_086240_20180827_20180827_01_RT/LC08_L1GT_086240_20180827_20180827_01_RT_B1.TIF out-lerc-prec-3.mrf
Input file size is 9151, 9151
0...10...20...30...40...50...60...70...80...90...100 - done.

/usr/app# ls -l *.lrc
-rw-r--r-- 1 root root 42128772 Jun 22 19:29 out-lerc-prec-1.lrc
-rw-r--r-- 1 root root 36938568 Jun 22 19:30 out-lerc-prec-2.lrc
-rw-r--r-- 1 root root 33918377 Jun 22 19:31 out-lerc-prec-3.lrc
```

Not so with the GDAL Python bindings. No matter what `LERC_PREC` is used, the output raster is the same and appears to be lossless.

```
from osgeo import gdal
input_raster = "/vsicurl/http://landsat-pds.s3.amazonaws.com/c1/L8/086/240/LC08_L1GT_086240_20180827_20180827_01_RT/LC08_L1GT_086240_20180827_20180827_01_RT_B1.TIF"
trans_options_1 = gdal.TranslateOptions(format='MRF', creationOptions=['COMPRESS=LERC', 'OPTIONS="LERC_PREC=1 V2=ON"'])
trans_options_2 = gdal.TranslateOptions(format='MRF', creationOptions=['COMPRESS=LERC', 'OPTIONS="LERC_PREC=2 V2=ON"'])
trans_options_3 = gdal.TranslateOptions(format='MRF', creationOptions=['COMPRESS=LERC', 'OPTIONS="LERC_PREC=3 V2=ON"'])
gdal.Translate("out-lerc-prec-1-python.mrf", input_raster, options=trans_options_1)
gdal.Translate("out-lerc-prec-2-python.mrf", input_raster, options=trans_options_2)
gdal.Translate("out-lerc-prec-3-python.mrf", input_raster, options=trans_options_3)
```
Python output:
```
/usr/app# ll -l *.lrc
-rw-r--r-- 1 root root 47317540 Jun 22 19:41 out-lerc-prec-1-python.lrc
-rw-r--r-- 1 root root 47317540 Jun 22 19:41 out-lerc-prec-2-python.lrc
-rw-r--r-- 1 root root 47317540 Jun 22 19:42 out-lerc-prec-3-python.lrc
```

## Operating system

I'm running the tests above in a Docker container using the `osgeo/gdal:ubuntu-small-3.3.0` image, but I'm experiencing the same issue in containers based on `lambci/lambda:build-python3.7` using GDAL 3.1.2.

## GDAL versions and provenance

- GDAL Python 3.3.0 packaged in `osgeo/gdal:ubuntu-small-3.3.0`
- GDAL Python 3.1.2 from https://pypi.org/project/GDAL/3.1.2/

**Comment by jratike80** [comment]
You seem to use a bit different syntax for giving the options than here https://github.com/OSGeo/gdal/blob/master/autotest/gdrivers/mrf.py.

**Comment by rouault** [comment]
The issue is the double quoting of the value of OPTIONS, which is only necessary on command line.

The following works fine
```python
from osgeo import gdal
input_raster = "/vsicurl/http://landsat-pds.s3.amazonaws.com/c1/L8/086/240/LC08_L1GT_086240_20180827_20180827_01_RT/LC08_L1GT_086240_20180827_20180827_01_RT_B1.TIF"
trans_options_1 = gdal.TranslateOptions(format='MRF', creationOptions=['COMPRESS=LERC', 'OPTIONS=LERC_PREC=1 V2=ON'])
trans_options_2 = gdal.TranslateOptions(format='MRF', creationOptions=['COMPRESS=LERC', 'OPTIONS=LERC_PREC=2 V2=ON'])
trans_options_3 = gdal.TranslateOptions(format='MRF', creationOptions=['COMPRESS=LERC', 'OPTIONS=LERC_PREC=3 V2=ON'])
gdal.Translate("out-lerc-prec-1-python.mrf", input_raster, options=trans_options_1)
gdal.Translate("out-lerc-prec-2-python.mrf", input_raster, options=trans_options_2)
gdal.Translate("out-lerc-prec-3-python.mrf", input_raster, options=trans_options_3)
```

**Comment by kwinwithak** [comment]
Ah, both of your suggested syntaxes work for me. Thank you for the clarification!

P.S. I'm not sure if `V2=ON` actually does anything in Python. Whereas the command line seems to require opting into LERC version 2 in this way, the python bindings appear to assume v2 and allow switching to v1 per @jratike80's comment.

**Comment by rouault** [comment]
> P.S. I'm not sure if `V2=ON` actually does anything in Python

there's no reason that the behavior is different in command line vs Python

**Comment by jratike80** [comment]
LERC options are documented at least in https://github.com/nasa-gibs/mrf/blob/master/doc/MUG.md but not directly in GDAL documentation. I do not know what would be the best place to document them because LECR is supported at least in MRF, GTiff, and COG drivers.
