### ISSUE TITLE
Maintainer for Spack GDAL package

### ISSUE THREAD

**Issue by adamjstewart** [OSGeo/gdal#4025]
@rouault just saw your tweet about Spack: https://twitter.com/EvenRouault/status/1398014177340530696

I'm the leading contributor to Spack. I also happen to do geospatial research! I wrote the build recipes for and maintain most of the geospatial packages in Spack, including libraries like [GDAL](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/gdal/package.py), [GEOS](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/geos/package.py), [GMT](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/gmt/package.py), [GRASS](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/grass/package.py), [libgeotiff](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/libgeotiff/package.py), [PROJ](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/proj/package.py), and [QGIS](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/qgis/package.py), as well as dozens of Python libraries like [cartopy](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/py-cartopy/package.py), [fiona](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/py-fiona/package.py), [geopandas](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/py-geopandas/package.py), [geoplot](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/py-geoplot/package.py), [geopy](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/py-geopy/package.py), [pygeos](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/py-pygeos/package.py), [pyproj](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/py-pyproj/package.py), [rasterio](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/py-rasterio/package.py), and [shapely](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/py-shapely/package.py).

Unlike other packages managers, Spack allows users to completely control how a package is built. For example, if I want to build GDAL 3.2.3 with the Intel compilers, adding support for HDF4/5, and using a specific version of PROJ, I can get this like so:
```console
$ spack install gdal@3.2.3 %intel@19.1.2 +hdf4+hdf5 ^proj@7.1.0
```
Of course, if users don't care about the details, they can also just run `spack install gdal` and Spack will choose good defaults. Spack is designed for supercomputers, but can also run on your laptop. I personally use it to install all of my geospatial software in the cloud.

We at Spack would love to collaborate with you to make our builds even more robust. Would you or anyone else from your team be interested in helping maintain any of our build recipes for geospatial software? You don't have to know anything about Spack, it just gives us an expert to ping when a user reports build issues or submits a PR to modify the build recipe for that package. Of course, I'll still be helping to maintain these packages, so I can handle any Spack-specific questions.

**Comment by rouault** [comment]
I'm not sure who has a specific interest in Spack, but you can drop a question here or on the mailing list when needed.

**Comment by jcphill** [comment]
My site is undergoing a transition to Spack, as are most HPC sites that I follow. Based on my experience I'd like to second Adam's request for input on the default configuration options, which basically turns everything off, so I had to ask our admins to enable png, sqlite3, curl, and python variants, and then modify the package.py script to not disable pam (which is an internal feature that introduces no dependencies and that GDAL enables by default because prior to 3.5.0 it is required for some drivers to work correctly).

Ideally Spack should provide the same default GDAL feature set that GDAL's cmake scripts do. This is a good time for input with the deprecation of autoconf in GDAL 3.5.0.

**Comment by adamjstewart** [comment]
Yes, I set our defaults to build the smallest possible subset of GDAL to improve build times. We were getting a lot of complaints from users saying that compilation takes too long. Since we build everything from source, a minimal compilation can take 5 min and involve 5 dependencies, but using the same defaults as Autotools/CMake could take hours and involve hundreds of dependencies. @tgamblin is planning to start aggressively offering pre-compiled binaries on as many platforms as we can, so once that happens I'm planning on changing the defaults to be more useful.

**Comment by jcphill** [comment]
Perhaps there could be different defaults for domain experts who know what features they need and support generalists who were simply asked to install GDAL and don't care how long the build runs as long as the users are happy and they only need to do it once?

**Comment by jcphill** [comment]
You could have meta-variants named "minimal" (for fast builds, turns most things off unless explicitly enabled),  "recommended" (for system installs, includes all features that users would typically expect), and "everything" (for testing).
