### ISSUE TITLE
OCI driver TRUNCATE gives ORA-13223: duplicate entry for <table> in SDO_GEOM_METADATA

### ISSUE THREAD

**Issue by btostevepritchard** [OSGeo/gdal#4027]
## Expected behavior and actual behavior.

I expect to be able to use ogr2ogr to load data into an existing Oracle table, using the TRUNCATE option.
But when I try this I get:

ERROR 1: ORA-13223: duplicate entry for OGR_TEST.GEOM in SDO_GEOM_METADATA
ORA-06512: at "MDSYS.MD", line 1723
ORA-06512: at "MDSYS.MDERR", line 17
ORA-06512: at "MDSYS.SDO_GEOM_TRIG_INS1", line 69
ORA-04088: error during execution of trigger 'MDSYS.SDO_GEOM_TRIG_INS1'
 in INSERT INTO USER_SDO_GEOM_METADATA VALUES ('OGR_TEST', 'GEOM', MDSYS.SDO_DIM_ARRAY(MDSYS.SDO_DIM_ELEMENT('X',201696.9970999998,362918.3580000005,0.001),MDSYS.SDO_DIM_ELEMENT('Y',316766.9969000001,452497.6229999992,0.001)), 29902)
ERROR 1: ORA-00955: name is already used by an existing object
 in CREATE INDEX "OGR_TEST_IDX" ON OGR_TEST("GEOM") INDEXTYPE IS MDSYS.SPATIAL_INDEX  PARAMETERS( 'LAYER_GTYPE=MULTIPOLYGON' )

## Steps to reproduce the problem.

Create a table in Oracle:

    ogr2ogr -progress -f OCI -nln OGR_TEST -lco GEOMETRY_NAME=geom -lco SRID=27700 -lco LAUNDER=YES OCI:/@mydb: test.gdb test_layer

Works fine.

Now try to reload the data into this table:

    ogr2ogr -progress -f OCI -nln OGR_TEST -lco TRUNCATE=YES -lco GEOMETRY_NAME=geom -lco SRID=27700 -lco LAUNDER=YES OCI:/@mydb: test.gdb test_layer

Fails with ORA-13223 as above.

## Operating system

Windows 10 (x64).

## GDAL version and provenance

GDAL 2.4.0 shipped with QGIS 3.6.
Same behaviour on GDAL 3.4.0dev built from https://github.com/OSGeo/gdal.

## Suggested modification

https://github.com/OSGeo/gdal/blob/master/gdal/ogr/ogrsf_frmts/oci/ogrocidatasource.cpp#L622 currently has:

        poLayer = new OGROCITableLayer( this, pszSafeLayerName, eType,
                                        EQUAL(szSRSId,"NULL") ? -1 : atoi(szSRSId),
                                        TRUE, TRUE );

Propose:

        poLayer = new OGROCITableLayer( this, pszSafeLayerName, eType,
                                        EQUAL(szSRSId,"NULL") ? -1 : atoi(szSRSId),
                                        TRUE, 
                                        CPLFetchBool(papszOptions, "TRUNCATE", false) ? FALSE : TRUE );

Works as expected with this change.

**Comment by rouault** [comment]
Please issue a pull request with the proposed fix
