### ISSUE TITLE
MultiPolygon features missing in certain .kml files

### ISSUE THREAD

**Issue by atlight** [OSGeo/gdal#4031]
## Expected behavior and actual behavior.

Certain MultiPolygon features in .kml files lose their geometry when imported into GDAL. Google Earth can read them without a problem.

## Steps to reproduce the problem.

See [multipolygon-brokenness.zip](https://github.com/OSGeo/gdal/files/6706836/multipolygon-brokenness.zip).

```
C:\Projects>ogrinfo -al -where "Name = 'BASS'" multipolygon-brokenness.kml
[snip]
OGRFeature(multipolygon-brokenness):3
  Name (String) = BASS
  description (String) =
                                <table>
                                                <tr><td>Voters:</td><td>48,174</td></tr>
                                                <tr><td>Deviation:</td><td>-0.93%</td></tr>
                                        </table>

  visibility (Integer) = -1
  Style = BRUSH(fc:#12CBC4AA)

```

This feature should have a MultiPolygon geometry. Instead it has no geometry.

This .kml file is the submission of Brendan Andrews to the 2021 Victorian state redivision (redistricting), downloadable at https://www.ebc.vic.gov.au/CurrentRedivision/ViewSubmissions.html. I don't know what tool was used to create the .kml file, other than it is probably a serverside headless tool rather than a desktop GIS.

## Operating system

Windows

## GDAL version and provenance

master

**Comment by jratike80** [comment]
By looking at https://developers.google.com/kml/documentation/kmlreference#multigeometry MultiPolygon is not supported in KML. It does support MultiGeometry.

I changed MultiPolygon into MultiGeometry with a text editor and now

```
gdaltest>ogrinfo -al -where "Name = 'BASS'" multipolygon-brokenness_fixed.kml |more
INFO: Open of `multipolygon-brokenness_fixed.kml'
      using driver `LIBKML' successful.
...
  tessellate (Integer) = -1
  extrude (Integer) = 0
  visibility (Integer) = -1
  Style = BRUSH(fc:#12CBC4AA)
  MULTIPOLYGON (((145.60569 -38.332432,145.622911334447 -38.3357335671075,145.626784771903 -38.3381495425319,145.628063786815 -38.3379322020906,145.629599 -38.339049,145.629262562627 -38.3405217195022,145.63452246756 -38.3438030245868,145.643824688803 -38.3422688202063
...
```

**Comment by atlight** [comment]
Fair call. But if Google Earth accepts `<MultiPolygon>` I think we should too.

**Comment by jratike80** [comment]
Perhaps but I am not sure. KML is standard and it is XML with an official schema and MultiPolygons are definitely not valid http://schemas.opengis.net/kml/2.2.0/ogckml22.xsd but like in this case, being lenient may be the only way to use some datasets. Certainly we must not write out MultiPolygons.

Being lenient too early encourages bad usage but Google has already taken this step. Would you like to experiment a bit and try how GE treats other invalid cases: MultiPoints and MultiLineStrings?

I would vote -0.

**Comment by rouault** [comment]
> how GE treats other invalid cases: MultiPoints and MultiLineStrings?

It also accept MultiPoint and MultiLineString. And interestingly when opening those files with MultiPolygon, MultiPoint and MultiLineString and exporting them from Google Earth Pro, in whole or just the feature, it also re-export them with the original invalid geometry type! I presume they must keep the XML DOM.

We could probably be tolerant on import, but we should likely emit a CE_Warning when encountering those invalid constructs.
- For the LIBKML driver, the https://github.com/libkml/libkml/ library we rely on doesn't handle those non-conformant geometry types, so we'd have to pre-process the file to replace ``<MultiPolygon>`` by ``<MultiGeometry>`` and ``</MultiPolygon>`` by ``</MultiGeometry>``. We already have logic to do such preprocessing for other situations
- For the KML one, the parser should be modified.
