### ISSUE TITLE
Can't open GeoPackage file on WSL from Windows

### ISSUE THREAD

**Issue by markgrujic** [OSGeo/gdal#4033]
## Expected behavior and actual behavior.
I have a geopackage file that is in my Windows Subsystem for Linux home directory.
I am unable to access it using GDAL installed on Windows.
However, it is accessible using GDAL installed on WSL.

## Steps to reproduce the problem.

Example of expected behaviour (GDAL on Linux, file on Linux):
```
(base) ubuntu@MicroPC:~/work/temp$ ogrinfo example.gpkg
        - 'VirtualXPath'        [XML Path Language - XPath]
INFO: Open of `example.gpkg'
      using driver `GPKG' successful.
1: example (Point)
```

Example of unexpected behaviour (GDAL on Windows, file on Linux):
```
C:\work\temp>"C:\Program Files\QGIS 3.18\bin\ogrinfo.exe" "\\wsl.localhost\Ubuntu\home\ubuntu\work\temp\example.gpkg"
ERROR 1: database is locked
ERROR 1: database is locked
FAILURE:
Unable to open datasource `\\wsl.localhost\Ubuntu\home\ubuntu\work\temp\example.gpkg' with the following drivers.
  -> JP2ECW
  -> OCI
  -> SOSI
  -> PCIDSK
  -> netCDF
  -> PDS4
  -> VICAR
  -> JP2OpenJPEG
  -> PDF
  -> MBTiles
  -> EEDA
  -> DB2ODBC
  -> ESRI Shapefile
  -> MapInfo File
  -> UK .NTF
  -> OGR_SDTS
  -> S57
  -> DGN
  -> OGR_VRT
  -> REC
  -> Memory
  -> BNA
  -> CSV
  -> NAS
  -> GML
  -> GPX
  -> LIBKML
  -> KML
  -> GeoJSON
  -> GeoJSONSeq
  -> ESRIJSON
  -> TopoJSON
  -> Interlis 1
  -> Interlis 2
  -> OGR_GMT
  -> GPKG
  -> SQLite
  -> ODBC
  -> WAsP
  -> PGeo
  -> MSSQLSpatial
  -> OGR_OGDI
  -> PostgreSQL
  -> MySQL
  -> OpenFileGDB
  -> XPlane
  -> DXF
  -> CAD
  -> FlatGeobuf
  -> Geoconcept
  -> GeoRSS
  -> GPSTrackMaker
  -> VFK
  -> PGDUMP
  -> OSM
  -> GPSBabel
  -> SUA
  -> OpenAir
  -> OGR_PDS
  -> WFS
  -> OAPIF
  -> HTF
  -> AeronavFAA
  -> Geomedia
  -> EDIGEO
  -> SVG
  -> CouchDB
  -> Cloudant
  -> Idrisi
  -> ARCGEN
  -> SEGUKOOA
  -> SEGY
  -> XLS
  -> ODS
  -> XLSX
  -> Elasticsearch
  -> Walk
  -> Carto
  -> AmigoCloud
  -> SXF
  -> Selafin
  -> JML
  -> PLSCENES
  -> CSW
  -> VDV
  -> GMLAS
  -> MVT
  -> NGW
  -> MapML
  -> TIGER
  -> AVCBin
  -> AVCE00
  -> HTTP
```

Moving the file to a Windows directory results in expected behaviour when using GDAL on Windows:
```
C:\work\temp>"C:\Program Files\QGIS 3.18\bin\ogrinfo.exe" example.gpkg
INFO: Open of `example.gpkg'
      using driver `GPKG' successful.
1: example (Point)
```

## Operating system

OS: Windows 10 Pro 10.0.21390
WSL2 version: 2
Linux Distro on WSL2: Ubuntu 20.04.02

## GDAL version and provenance

Windows GDAL: 3.1.4 version installed with QGIS 3.18.3-Zürich
Ubuntu GDAL: 3.2.1 from ubuntugis/ppa

**Comment by rouault** [comment]
does ``sqlite3.exe \\wsl.localhost\Ubuntu\home\ubuntu\work\temp\example.gpkg`` work with a binary from https://sqlite.org/download.html ?

**Comment by markgrujic** [comment]
Here is the output from sqlite3.exe after calling the command and checking the database when the geopackage is in the Windows directory, then in WSL2:
```
C:\work\temp>sqlite3.exe example.gpkg
SQLite version 3.36.0 2021-06-18 18:36:39
Enter ".help" for usage hints.
sqlite> .databases
main: C:\work\temp\example.gpkg r/w
sqlite> .quit

C:\work\temp>sqlite3.exe \\wsl.localhost\Ubuntu\home\ubuntu\work\temp\example.gpkg
SQLite version 3.36.0 2021-06-18 18:36:39
Enter ".help" for usage hints.
sqlite> .databases
Error: database is locked
```

I hope this helps, please let me know what else I can provide.

**Comment by rouault** [comment]
> I hope this helps, please let me know what else I can provide.

This helps in the sense that it shows it is an upstream issue in SQLite itself, so it should be reported to them: https://sqlite.org/forum/forummain

One thing you could potentially try with GDAL is to add ``--config SQLITE_USE_OGR_VFS YES`` to your ogrinfo command line and see if it helps

**Comment by markgrujic** [comment]
Yep understood. Thanks for clearing that up. Ill head over to sqlite. Should I close this?

**Comment by jratike80** [comment]
Do you know if the Windsows side has write access to the WSL side directories? By https://docs.microsoft.com/en-us/windows/wsl/file-permissions it should work but maybe you should make a test by writing a shapefile with GDAL into `"\\wsl.localhost\Ubuntu\home\ubuntu\work\temp\`.

**Comment by markgrujic** [comment]
Yep, Windows has write access to WSL directories. I have tested by writing a shapefile with GDAL into that directory without problems.

**Comment by rouault** [comment]
> add `--config SQLITE_USE_OGR_VFS YES` to your ogrinfo command line and see if it helps

did you try this ?

**Comment by rouault** [comment]
closing due to lack of feedback

**Comment by aborruso** [comment]
> > add `--config SQLITE_USE_OGR_VFS YES` to your ogrinfo command line and see if it helps
> 
> did you try this ?

It works, very useful, thank you very much
