### ISSUE TITLE
GDAL creates IMD files with unquoted string values, which GDAL itself cannot read

### ISSUE THREAD

**Issue by deng0** [OSGeo/gdal#4037]
When creating a copy of a spot6/7 image with DIMAP metadata xml, an IMD file is created with the IMD metadata entries.
When loading the copy, I would expect the IMD metadata to be loaded, but GDALLoadIMDFile fails because string values are not quoted in the IMD file created by GDAL (it would work if the string values would not contain spaces, but they often do).

I used the current GDAL 3.3.0 release version, but I think older versions are also affected.

**Comment by rouault** [comment]
Can you attach such IMD file with missing quotes ?

**Comment by deng0** [comment]
Yes certainly.  Here it is:
[IMG_SPOT7_MS_202006010954241_SEN_5549694101_R1C1_Export_2.IMD.zip](https://github.com/OSGeo/gdal/files/6718002/IMG_SPOT7_MS_202006010954241_SEN_5549694101_R1C1_Export_2.IMD.zip)
