### ISSUE TITLE
Use reentrant version of Qhull

### ISSUE THREAD

**Issue by sebastic** [OSGeo/gdal#4040]
As reported in [Debian Bug #990403](https://bugs.debian.org/990403):
> your package builds and links against the non-reentrant version of
Qhull, which has been deprecated by Qhull upstream and is likely to
disappear soon.
> 
> This bug is not release-critical for Bullseye, but you can expect the
severity to raise eventually when Qhull stops shipping with the
non-reentrant library.
> 
> You can verify that your binary package links against the correct
library if it no longer depends on libqhull8.0 but libqhull-r8.0
instead.

`configure.ac` uses `AC_CHECK_LIB` on `qhull` and does not try `qhull_r`.

If gdal supports reentrant Qhull, only changes to configure are needed.

**Comment by rouault** [comment]
As far as I can read in https://github.com/qhull/qhull/blob/348d229efdd66e97f146e2340b98ee8dc7f878c6/src/libqhull/DEPRECATED.txt#L27 , the way we use libqhull " will be supported indefinitely" since we don't use the qh_QHpointer variation, so there's no urgency. That said migrating to the re-entrant libqhull will avoid the mutex we need currently. It is not just a configure.ac change: it will require code changes. And most of the effort will probably be in adapting the vendorized version (used typically for Windows builds) in alg/internal_libqhull to be the re-entrant one.

**Comment by nieder** [comment]
As a point of reference, trying to build gdal-3.3.2 on macOS against qhull-2020.2, I get this error (configure locally patched to look for qhull_r):
```
/bin/sh /sw/build.build/gdal3-3.3.2-1/gdal-3.3.2/libtool --mode=link --silent g++ -std=c++11 -L/sw/lib -L/sw/lib -lheif -L/sw/lib -lIlmImf-2_4 -lImath-2_4 -lHalf-2_4 -lIex-2_4 -lIexMath-2_4 -lIlmThread-2_4 -lcryptopp  -ljson-c -L/sw/lib -L/sw/lib -lfreexl -lqhull_r -L/sw/opt/libgeos3.6.1/lib -lgeos_c -L/sw/lib -lwebp -L/sw -L/sw/lib -lodbc -lodbcinst -L/sw/lib -lexpat -L/sw/lib -lxerces-c -lpthread -L/sw/lib -lopenjp2 -L/sw -L/sw/lib -ljasper -L/sw/lib -lnetcdf -L/sw/opt/hdf5.v1.10/lib -lhdf5  -L/sw -L/sw/lib -logdi -L/sw -L/sw/lib -lgif -L/sw/lib -lgeotiff -L/sw -L/sw/lib -lpng -L/sw -L/sw/lib -lcfitsio -L/sw/opt/postgresql-12/lib -lpq -llzma -L/sw/lib -lsqlite3 -L/sw/lib -lproj  -L/sw/lib -lsqlite3 -L/sw/lib -ltiff -L/sw -L/sw/lib -ljpeg -ldeflate -lz -L/sw -L/sw/lib -lpthread -ldl  -L/sw/lib -L/sw/lib -lspatialite -L/sw/opt/libdap11/lib -ldap -ldapserver -ldapclient -L/sw/lib -lcurl -L/sw/lib -lxml2 -lpthread   -lpcre   -L/sw/lib -lcurl          -liconv  -L/sw/lib -lxml2       -o libgdal.la \
<tons of .lo objects>
    -rpath /sw/lib \
    -no-undefined \
    -version-info 29:2:0
Undefined symbols for architecture x86_64:
  "_qh_qh", referenced from:
      _GDALTriangulationCreateDelaunay in delaunay.o
ld: symbol(s) not found for architecture x86_64
```
I had a similiar error with plplot-5.15.0 that tries to use either the older or newer qhull, but fails to actually build with the new one. I used [Debian's patch](https://salsa.debian.org/science-team/plplot/-/blob/master/debian/patches/reentrant-qhull.patch) to build plplot against qhull-2020.2

**Comment by rouault** [comment]
What remains to be done is to use qhull 2020.2 (8.0.2) as internal libqhull, and possibly remove in master support for non-reentrant qhull for the sake of cleaning a bit the code base.
