### ISSUE TITLE
big conversion geotiff to netcdf

### ISSUE THREAD

**Issue by DrJosdeLaat** [OSGeo/gdal#4042]
GDL 3.1.4 conversion geotiff-file (byte-array data type) to NetCDF creates a NC-file in which the attribute "valid_range" is a short, yet the data is still byte. That creates a warning in Python3.9.5 when reading the NetCDF ("cannot be safely cast to variable data type"). Data and valid_range should be of similar type.

**Comment by rouault** [comment]
The issue here is that by default GDAL uses the netCDF 3 format which doesn't support unsigned byte data type, so there isn't much alternative. You can use the FORMAT=NC4 creation option to create a netCDF 4 format which will use the ``ubyte`` data type, and will not use valid_range

**Comment by DrJosdeLaat** [comment]
OK, thanks.

----------------------------------
A.T.J. de Laat (Jos), Ph.D, Senior Scientist
Royal Netherlands Meteorological Institute (KNMI)
PO box 201
3730 AE de Bilt
The Netherlands
Tel (direct): 030-2206892
Fax: 030-2210407
e-mail: ***@***.******@***.***> ***@***.***>
----------------------------------

"being a true expert involves not only knowing stuff
about the world but also knowing the limits of your
knowledge and expertise." [Eric Angner, 2020]
