### ISSUE TITLE
Publish ARM Docker containers on docker hub

### ISSUE THREAD

**Issue by blacha** [OSGeo/gdal#4044]
## Expected behavior and actual behavior.

I would like to try using GDAL on a cluster of ARM machines using docker.

When I run `docker run osgeo/gdal gdal_translate --version`  on a ARM machine it fails.

Would it be possible to publish the ARM containers to https://hub.docker.com/r/osgeo/gdal/tags?page=1&ordering=last_updated at the same time the `linux/amd64` containers are published?

It looks like ARM support was added a while ago https://github.com/OSGeo/gdal/pull/2965 but I cannot find where the actual publishing of the containers happens

**Comment by rouault** [comment]
There is infrastructure to do cross builds, but we haven't used it yet

**Comment by rouault** [comment]
Images for 3.3.1 now support linux/amd64 and linux/arm64
