### ISSUE TITLE
Suggestion: Include MDB Tools for PGeo driver in ubuntu-full docker

### ISSUE THREAD

**Issue by prusswan** [OSGeo/gdal#4059]
After going through https://gdal.org/drivers/vector/pgeo.html#vector-pgeo, it appears to me that only the missing MDB Tools is preventing the PGeo driver from being usable right out of the box. So, would it be a good idea to include it? As PGeo can now read non-spatial tables (#2889) and work with mdb files directly (provided MDB Tools is already installed)

Related: https://github.com/OSGeo/gdal/pull/2974 (which already brought in MDB and FileGDB support)

**Comment by rouault** [comment]
Actually accessing Personal Geodatabases is already possible, but requires excluding the ODBC driver with "--config OGR_SKIP ODBC" , and the Java-based MDB driver is then used.
In #4059 I've queued changes to be able to use the PGeo driver itself, but it also requires excluding explicltly the ODBC driver (for odd reasons it seems a failed attempt at connecting with the ODBC driver prevents the PGeo one from working)
