### ISSUE TITLE
Develop new driver to support Radarsat Constellation Mission (RCM) products

### ISSUE THREAD

**Issue by kdesjard** [OSGeo/gdal#4065]
I propose the creation of a new driver based on a modified rs2 driver to take into account the many differences between the two mission's product.xml files as well as other changes like the support for ScanSAR mode and SLC product type where each burst is written as a separate image file.

**Comment by rouault** [comment]
Who can access datasets in that format?

**Comment by kdesjard** [comment]
https://www.asc-csa.gc.ca/eng/satellites/radarsat/faq.asp#access

_"Certain RCM image products are freely and openly available to users outside the Government of Canada, subject to exceptions in terms of security, privacy and confidentiality."_

Currently, public access is limited to GRD and GCD products over Canada Land coarser or equal to 16 m.

_"The data distribution approach being implemented for the RCM is aligned with the spirit of the Directive on Open Government and the global trends in Earth observation. It provides access to image products (subject to security restrictions set out in Canadian legislation) for free to users."_
