### ISSUE TITLE
Progress calculation error

### ISSUE THREAD

**Issue by nikkymen** [OSGeo/gdal#4067]
There is an error in the place where the progress is calculated:

https://github.com/OSGeo/gdal/blob/1d77534d0a1ee1efcda7d9f3d0bf1f7b91348e34/gdal/gcore/rasterio.cpp#L4145

Instead `std::max`, we must use `std::min`, otherwise progress will always return **1.0**.

**Comment by rouault** [comment]
Sounds reasonable. Do you mind sending a pull request for that ? (you could even do it directly from github UI)

**Comment by nikkymen** [comment]
Ok i did it
