### ISSUE TITLE
BUG: Affine missing for netcdf file

### ISSUE THREAD

**Issue by snowman2** [OSGeo/gdal#4075]
From: https://github.com/corteva/rioxarray/issues/371
Input file: https://github.com/corteva/rioxarray/blob/master/test/test_data/input/MODIS_ARRAY.nc?raw=true

Information about dx/dy:
```python
>>> import xarray
>>> rds = xarray.open_dataarray("MODIS_ARRAY.nc")
>>> (rds.x.values[:-1] - rds.x.values[1:]).max()
-231.65635826345533
>>> (rds.x.values[:-1] - rds.x.values[1:]).min()
-231.65635826438665
>>> (rds.y.values[:-1] - rds.y.values[1:]).max()
231.65635826438665
>>> (rds.y.values[:-1] - rds.y.values[1:]).min()
231.65635826345533
```

Most likely culprit: https://github.com/OSGeo/gdal/pull/3753 [commit](https://github.com/OSGeo/gdal/commit/295cc128cf825aa0a66762dcade905b62d46a4e0#diff-2cad011d75bba38ea38554b3dc07cef735a259752a5bf6fa1d7ff7e3e9ef95d2)

Other potential culprits:
- https://github.com/OSGeo/gdal/commit/7ea0f5d143ae412f0695b2d311006a4e65ba41ff#diff-2cad011d75bba38ea38554b3dc07cef735a259752a5bf6fa1d7ff7e3e9ef95d2
- https://github.com/OSGeo/gdal/commit/ced20253a7d7d61d3865feba93e020a434bc9617#diff-2cad011d75bba38ea38554b3dc07cef735a259752a5bf6fa1d7ff7e3e9ef95d2

## Expected behavior and actual behavior.

GDAL version 3.3.0 or previous:
```python
from osgeo import gdal
ds = gdal.Open("MODIS_ARRAY.nc")
ds.GetGeoTransform(can_return_null=True)
```
```
(-7274009.649486291, 231.6563582639561, 0.0, 5050108.61015275, 0.0, -231.65635826375018)
```
GDAL version 3.3.1:
```python
from osgeo import gdal
ds = gdal.Open("MODIS_ARRAY.nc")
ds.GetGeoTransform(can_return_null=True)
```

## Operating system

Ubuntu 20, MacOS, etc.

## GDAL version and provenance

Issue in GDAL version 3.3.1

**Comment by rouault** [comment]
> Most likely culprit: #3753 [commit](https://github.com/OSGeo/gdal/commit/295cc128cf825aa0a66762dcade905b62d46a4e0#diff-2cad011d75bba38ea38554b3dc07cef735a259752a5bf6fa1d7ff7e3e9ef95d2)

That was indeed it. This MODIS_ARRAY.nc file uses a non-CF compliant way of specifying georeferencing axis and CRS. I've added in PR #4081 specific checks for it, and a more generic way of relaxing the now stricter checks to decide if indexing variables are georeferenced axis with the GDAL_NETCDF_IGNORE_XY_AXIS_NAME_CHECKS configuration option
