### ISSUE TITLE
Feature request: gdalinfo specify single band

### ISSUE THREAD

**Issue by chapmanjacobd** [OSGeo/gdal#4076]
## Expected behavior and actual behavior.

Currently I have to do this:

- gdal_translate -b 1 file.tif file_temp.tif
- gdalinfo -json -mm file_temp.tif

It might be nice to provide functionality similar to this via:

```
gdalinfo -json -mm -b 1 file_temp.tif
```

but if the speed is the same then I don't really care that much about this....

**Comment by mdsumner** [comment]
with 

```bash
gdalinfo vrt://file.tif?bands=1
```

I think we can close this
