### ISSUE TITLE
Greater/less than operator not doing anything in gdal_calc

### ISSUE THREAD

**Issue by jfbourdon** [OSGeo/gdal#4083]
## Expected behavior and actual behavior
In gdal_calc, when doing a simple operation like `A>0`, the result will be identical to `A`. Operators `<` `<=` `>=` are having the same problem. However, using `greater(A,0)` will yield the expected result.

## Steps to reproduce the problem.
With any raster, use a command similar to:
```
gdal_calc.py --calc "A>0" --format GTiff --type Byte -A C:/input.tif --A_band 1 --outfile C:/over0.tif
```

## Operating system
Windows 10

## GDAL version and provenance
Used through QGIS with the _gdal:rastercalculator_ tool. The tool was fine in QGIS 3.14.1 (GDAL 3.0.4)  but not in QGIS 3.20.0 (GDAL 3.3.0)

**Comment by rouault** [comment]
I can't confirm this. Works fine for me on Linux with latest GDAL master or 3.3 branch:
```
$ python swig/python/gdal-utils/scripts/gdal_calc.py  --calc "A>0" --format GTiff --type Byte -A ../autotest/gcore/data/byte.tif --outfile wrk/out.tif --overwrite
$ gdal_translate wrk/out.tif /vsistdout/ -of aaigrid
ncols        20
nrows        20
xllcorner    440720.000000000000
yllcorner    3750120.000000000000
cellsize     60.000000000000
NODATA_value 255
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
```

**Comment by jfbourdon** [comment]
Then the problem is probably in the way QGIS calls _gdal_calc.py_ as I also get the expected result when calling it from the OSGeo4W shell. I'll look a bit more and report the issue on QGIS' side if I find anything.
