### ISSUE TITLE
Zmap driver, please keep it

### ISSUE THREAD

**Issue by gernigon** [OSGeo/gdal#4086]
In a previous post.  https://lists.osgeo.org/pipermail/gdal-dev/2021-January/053260.html
the Zmap driver was considered to be removed in the future . 
Zmap is definitively important. It is a standard format used by many software in geophysics .
It is now impossible to read Zmap file anylonger with Qgis 3.20 and the problem may be due to the Gdal drivers.
All our Qgis projects include Zmap grid files. Total disaster for us.

**Comment by rouault** [comment]
> It is now impossible to read Zmap file anylonger with Qgis 3.20

You can re-enable the driver by setting the GDAL_ENABLE_DRIVER_ZMAP environment variable to YES, either in your global environment or in QGIS (Settings --> Options --> System --> Environment)

**Comment by gernigon** [comment]
> 
> 
> > It is now impossible to read Zmap file anylonger with Qgis 3.20
> 
> You can re-enable the driver by setting the GDAL_ENABLE_DRIVER_ZMAP environment variable to YES, either in your global environment or in QGIS (Settings --> Options --> System --> Environment)

Hello,
I just reinstall the last Qgis 3.2 and set the environment variable to YES but the I can not import the file anymore. It still work on the previous Qgis version. Any solutions ?

**Comment by rouault** [comment]
you need to restart QGIS after setting the environment variable

**Comment by gernigon** [comment]
> 
> 
> you need to restart QGIS after setting the environment variable

**Comment by gernigon** [comment]
![CaptureGDAL](https://user-images.githubusercontent.com/55848300/131257865-be3d1254-eb7e-4afb-aa1d-ad0a42432512.JPG)

Not sure if this is correct (see picture) but 1) I set the GDAL_ENABLE_DRIVER_ZMAP environment variable to YES in Qgis directly, 2) restart again but I still have a problem to read my ZMAP grid

**Comment by gernigon** [comment]
Ok I ve tried again with "GDAL_ENABLE_DEPRECATED_DRIVER_ZMAP" set to YES and it works !!!

**Comment by rouault** [comment]
> Ok I ve tried again with "GDAL_ENABLE_DEPRECATED_DRIVER_ZMAP" set to YES and it works !!!

oops, sorry for giving the wrong name (fixing that in my original message). Great you managed to make it work.

**Comment by chhei-s** [comment]
I'd like to second @gernigon's request not to deprecate the ZMAP driver for GDAL. It is very much still used as one of the most robust grid file formats to exchange data between geophysics applications (mainly seismic interpretation) and the GIS world.

**Comment by rouault** [comment]
It is no longer deprecate since GDAL 3.3.2

**Comment by gernigon** [comment]
Hi Christian,
The problem was fixed few  months ago, you also have to set your environment variable in option (see picture).

**Comment by chhei-s** [comment]
@rouault, @gernigon - thanks for the quick responses, this is good to hear. However, in my case this was not related to QGIS but to the gdal* command line version.

**Comment by rouault** [comment]
>However, in my case this was not related to QGIS but to the gdal* command line version.

Add ``--config GDAL_ENABLE_DEPRECATED_DRIVER_ZMAP YES``
