### ISSUE TITLE
VERSION file confuses Xcode 12.5

### ISSUE THREAD

**Issue by mathstuf** [OSGeo/gdal#4087]
The compilation on macOS with Xcode 12.5 fails because the standard library has a `#include <version>` in the `<cstddef>` header. This ends up selecting the `VERSION` file in the source tree and doesn't work (as one might expect). Unfortunately, case-insensitivity is not something that Apple is likely to change anytime soon. I think just renaming the file to be `VERSION.gdal` or something to avoid this confusion.

**Comment by rouault** [comment]
Can you should the compilation line(s) that fail ? There's no reason that the root folder is included during compilation, so we should likely fix that

**Comment by mathstuf** [comment]
It seems it comes from an `-I.` which, with the `Ninja` generator is the top-level of the build tree.

```
/Applications/Xcode-12.5.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DHAVE_ASSERT_H -DHAVE_DLFCN_H -DHAVE_ERRNO_H -DHAVE_FCNTL_H -DHAVE_FLOAT_H -DHAVE_INTTYPES_H -DHAVE_LIBZ -DHAVE_LIMITS_H -DHAVE_MEMORY_H -DHAVE_STDDEF_H -DHAVE_STDINT_H -DHAVE_STDLIB_H -DHAVE_STRINGS_H -DHAVE_STRING_H -DHAVE_SYS_STAT_H -DHAVE_SYS_TYPES_H -DHAVE_UNISTD_H -DHAVE_ZLIB -DHAVE_ZLIB_H -DOGR_ENABLED -DSTRICT -DZIP_SUPPORT -I/Users/svc-dashboard/ben.boeckel/cmb/build-sb/superbuild/gdal/src -I. -I/Users/svc-dashboard/ben.boeckel/cmb/build-sb/superbuild/gdal/src/port -I/Users/svc-dashboard/ben.boeckel/cmb/build-sb/install/include -fPIC  -mmacosx-version-min=11.0     -std=c++11 -stdlib=libc++ -O3 -DNDEBUG -arch arm64 -isysroot /Applications/Xcode-12.5.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk -mmacosx-version-min=11.0 -std=gnu++11 -MD -MT port/CMakeFiles/cpl.dir/cpl_http.cpp.o -MF port/CMakeFiles/cpl.dir/cpl_http.cpp.o.d -o port/CMakeFiles/cpl.dir/cpl_http.cpp.o -c /Users/svc-dashboard/ben.boeckel/cmb/build-sb/superbuild/gdal/src/port/cpl_http.cpp                                                                                              
In file included from /Users/svc-dashboard/ben.boeckel/cmb/build-sb/superbuild/gdal/src/port/cpl_http.cpp:30:                                                                                                                                  
In file included from /Applications/Xcode-12.5.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/c++/v1/map:481:                                                                                      
In file included from /Applications/Xcode-12.5.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/c++/v1/__tree:14: 
In file included from /Applications/Xcode-12.5.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/c++/v1/iterator:419:   
In file included from /Applications/Xcode-12.5.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/c++/v1/__functional_base:14:
In file included from /Applications/Xcode-12.5.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/c++/v1/type_traits:417:
In file included from /Applications/Xcode-12.5.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/c++/v1/cstddef:37:
/Users/svc-dashboard/ben.boeckel/cmb/build-sb/superbuild/gdal/src/version:1:1: error: expected unqualified-id                                                                                                                                  
1.11.0                                                                                                                                                                                                                                         
^                                                                                                                                                                                                                                              
```

**Comment by mathstuf** [comment]
I now see the `include_directories(${CMAKE_CURRENT_SOURCE_DIR})` in the top-level `CMakeLists.txt`. Removing it makes my build still work; will file a PR.

**Comment by rouault** [comment]
Seeing mentions of CMakeFiles, it doesn't seem that this is the standard build system of GDAL, so there's likely anything we can do on our side.

**Comment by mathstuf** [comment]
Oh, I had completely forgotten that we hacked this up at some point (probably for an easier time on Windows) and are still sitting on that fork. Sorry for the noise.

**Comment by tbonfort** [comment]
somewhat related, I see we're using `-I` instead of `-iquote` to reference local include dirs, and e.g. `#include <ogr_core.h>` instead of `#include "ogr_core.h"`. Fixing both of those should prevent future issues like this by robustifying the autoconf build. Should I submit a PR for this or does it have a too high risk of breaking older systems?

**Comment by rouault** [comment]
> Should I submit a PR for this or does it have a too high risk of breaking older systems?

Changing  `#include <ogr_core.h>` to `#include "ogr_core.h"` should be universally fine.
Regarding -iquote, I don't have a strong opinion. If the above change is done, it shouldn't be normally necessary as, at least for gcc, system locations would be looked after custom locations

**Comment by tbonfort** [comment]
> Regarding -iquote, I don't have a strong opinion. If the above change is done, it shouldn't be normally necessary as, at least for gcc, system locations would be looked after custom locations
Well, we do have many `-I../..` which can someday cause a similar issue (for example if someone adds a VERSION file to the ogr/ subdirectory)

**Comment by rouault** [comment]
I'm fine if you want to tackle -iquote changes (I *guess* that should be supported by the compilers we target?). But we'll probably switch to cmake at some point

**Comment by mathstuf** [comment]
FWIW, I don't think CMake has an `-iquote` abstraction today (though it can certainly [be requested](https://gitlab.kitware.com/cmake/cmake/-/issues)). I don't know how useful it'll be, but our CMake-ified fork lives [here](https://www.paraview.org/files/dependencies/gdal-98353693d6f1d607954220b2f8b040375e3d1744.tar.bz2). It seems our backing repository was removed; I'll see if I can't dig up a clone from my backups and at least push that history to my fork.

**Comment by mathstuf** [comment]
Oh, it does exist, I just could not see the important part of the URL. It's here: https://github.com/judajake/gdal-svn
