### ISSUE TITLE
VRT: subwindow output differs when read through VRT. 

### ISSUE THREAD

**Issue by gogglesguy** [OSGeo/gdal#4098]
Exporting a subwindow from a dataset returns different results depending on whether the dataset is accessed through a VRT or directly.

Version Used:

> gdal_translate --version
GDAL 3.3.0, released 2021/04/26

> gdalbuildvrt --version
GDAL 3.3.0, released 2021/04/26

Given a "dummy" dataset with a fictional georeferencing:

> data_g.png

![data_g](https://user-images.githubusercontent.com/1843382/125139291-e0da7080-e0d5-11eb-80f9-7687ef7c8cec.png)

Select a subwindow from the dataset and blow it up to "tile" size:

> gdal_translate -srcwin 71.41 84.41 7.35 7.35 -outsize 256 256 -r nearest data_g.png from_png.png

![from_png](https://user-images.githubusercontent.com/1843382/125139262-d7e99f00-e0d5-11eb-9553-eb502aa61bd6.png)

Now produce a VRT file:

> gdalbuildvrt data_g.vrt data_g.png

Now do the same for the VRT file:

> gdal_translate -srcwin 71.41 84.41 7.35 7.35 -outsize 256 256 -r nearest data_g.vrt from_vrt.png

![from_vrt](https://user-images.githubusercontent.com/1843382/125139269-da4bf900-e0d5-11eb-8e03-d01a43a1bd32.png)

Please advise. Is this expected behaviour? We noticed this issue with real world data when tiling at high zoomlevels using rasterio. When using the `boundless` option in rasterio.read to handle areas outside the domain, it internally uses an VRT and exposed this bug/issue.

**Comment by gogglesguy** [comment]
Running through the debugger, it looks like the full floating point values of the srcwin stored in psExtraArgs get overwritten in:

https://github.com/OSGeo/gdal/blob/24a99c11dfc71d0510d32f4a2e6cc2ded0b7bf09/gdal/frmts/vrt/vrtsources.cpp#L2539-L2543

Which are calculated by `GetSrcDstWindow`
https://github.com/OSGeo/gdal/blob/24a99c11dfc71d0510d32f4a2e6cc2ded0b7bf09/gdal/frmts/vrt/vrtsources.cpp#L948

This function does not take into account any of the psExtraArgsIn.

**Comment by gogglesguy** [comment]
One possible solution is to modify `GetSrcDstWindow`:
https://github.com/OSGeo/gdal/blob/24a99c11dfc71d0510d32f4a2e6cc2ded0b7bf09/gdal/frmts/vrt/vrtsources.cpp#L1005-L1008

Instead of using the integer values, always use the double values:
```
double dfRXOff = *pdfReqXOff;
double dfRYOff = *pdfReqYOff;
double dfRXSize = *pdfReqXSize;
double dfRYSize = *pdfReqYSize;
```
the function(s) that calls GetSrcDstWindow needs initialize these parameters to either the integer values or the optional ExtraArgs:
https://github.com/OSGeo/gdal/blob/24a99c11dfc71d0510d32f4a2e6cc2ded0b7bf09/gdal/frmts/vrt/vrtsources.cpp#L1289-L1312

So some extra logic before calling GetSrcDstWindow:
 ```
    if( psExtraArgIn != nullptr && psExtraArgIn->bFloatingPointWindowValidity)
    {
        dfReqXOff = psExtraArgIn->dfXOff;
        dfReqYOff = psExtraArgIn->dfYOff;
        if (psExtraArgIn->dfXSize == 0)
            dfReqXSize = nXSize;
        else
            dfReqXSize = psExtraArgIn->dfXSize;

        if (psExtraArgIn->dfYSize == 0)
            dfReqYSize = nYSize;
        else
            dfReqYSize = psExtraArgIn->dfYSize;
    }
    else
    {
        dfReqXOff = nXOff;
        dfReqYOff = nYOff;
        dfReqXSize = nXSize;
        dfReqYSize = nYSize;
    }

```

**Comment by rouault** [comment]
Excellent analysis! Fix queued in https://github.com/OSGeo/gdal/pull/4099

**Comment by gogglesguy** [comment]
Thanks! That was quick. I verified my local test case here and the data now looks correct.

For consistency, should similar fixes be made here:

https://github.com/OSGeo/gdal/blob/dc52eacecf0b6fe7a60f99bc5586c3466b02d8cd/gdal/frmts/vrt/vrtfilters.cpp#L126-L170

https://github.com/OSGeo/gdal/blob/dc52eacecf0b6fe7a60f99bc5586c3466b02d8cd/gdal/frmts/vrt/vrtsourcedrasterband.cpp#L214-L239

**Comment by rouault** [comment]
> For consistency, should similar fixes be made here:

Do you want to issue a pull request for that ?

**Comment by gogglesguy** [comment]
> > For consistency, should similar fixes be made here:
> 
> Do you want to issue a pull request for that ?

I sure can.
