### ISSUE TITLE
Error: Couldn't parse SQL when using ogrinfo + PGeo driver with -sql option

### ISSUE THREAD

**Issue by prusswan** [OSGeo/gdal#4103]
Happens on latest master (osgeo/gdal:ubuntu-full-latest):

<pre>

root@9ce060982584:/data# ogrinfo GEONAMES.mdb -sql "select count(*) from  GEONAMES_ANNO_PLACES"
INFO: Open of `GEONAMES.mdb'
      using driver `PGeo' successful.
Error at Line : syntax error
syntax error
Got no result for 'select count(*) from  GEONAMES_ANNO_PLACES' command
ERROR 1: [     ]Couldn't parse SQL
(1)
root@9ce060982584:/data# ogrinfo GEONAMES.mdb -sql "select count(*) from  GEONAMES_ANNO_PLACES"  -dialect sqlite
INFO: Open of `GEONAMES.mdb'
      using driver `PGeo' successful.
Error at Line : syntax error
syntax error
Got no result for 'SELECT COUNT(*) FROM GEONAMES_ANNO_PLACES' command
ERROR 1: GetFeatureCount() failed on query SELECT COUNT(*) FROM GEONAMES_ANNO_PLACES.
[     ]Couldn't parse SQL
(1)

Layer name: SELECT
Geometry: None
Feature Count: 1
Layer SRS WKT:
(unknown)
count(*): Integer (0.0)
OGRFeature(SELECT):0
  count(*) (Integer) = 2246

root@9ce060982584:/data# gdalinfo --version
GDAL 3.4.0dev-8f9afedfd2f5f9e916323e96d896056b7749b3d6, released 2021/07/11

</pre>

I had to specify `-dialect sqlite` to get a meaningful result from this, but the error message still gets printed

**Comment by nyalldawson** [comment]
I think this is actually a regression in mdbtools' odbc driver

**Comment by prusswan** [comment]
I found this related issue which details supported SQL in mdbtools, count(*) was listed as working back then: mdbtools/mdbtools#203. But in `mdb-sql.txt` it states "no aggregates".

I never thought too much about this as previously I try to do all the MDB extraction work on Windows to minimize surprises.

**Comment by rouault** [comment]
>  found this related issue which details supported SQL in mdbtools, count(*) was listed as working back then:

ok, so on 0.9.0 it works. I ran a git bisect session that pointed https://github.com/mdbtools/mdbtools/commit/d05c86fa3dbe46d86dd942873ab4099a81fe6088 as the offending commit

**Comment by rouault** [comment]
Reported upstream in https://github.com/mdbtools/mdbtools/issues/318
