### ISSUE TITLE
Georaster driver does not generate spatial extent when option EXTENTSRID is not present

### ISSUE THREAD

**Issue by fechen123** [OSGeo/gdal#4106]
## Expected behavior and actual behavior.

Expected behavior:
When loading an image into GeoRaster object in Oracle Database with option SPATIALEXTENT=true (which is default) , the spatialExtent attribute of the GeoRaster object should be generated with the same SRID as the GeoRaster object. 

Actual behavior:
The spatialExtent is not generated if option EXTENTSRID is not specified. 

## Steps to reproduce the problem.

- create a table in Oracle database: 
create table grtab (id number, grobj sdo_georaster);
create table rdt_1 of MDSYS.SDO_RASTER
  (primary key (rasterId, pyramidLevel, bandBlockNumber,
                rowBlockNumber, columnBlockNumber))
  lob(rasterblock) store as 
  (cache reads pctversion 0 storage (pctincrease 0));

- load geotiff image xxx.tif to the database table grtab. 
gdal_translate -of georaster xxx.tif geor:user/pwd,,grtab,grobj -co "INSERT=VALUES(1, sdo_geor.init('rdt_1', 1))"

- Start sqlplus session in Oracle database and run the following query:
SQL>select t.grobj.spatialextent from grtab t where id = 1;

## Operating system

Linux

## GDAL version and provenance

GDAL 3.3.1 and below.

**Comment by fechen123** [comment]
I will fix this shortly. BTW, how to update the documentation of the GeoRaster driver at https://gdal.org/drivers/raster/georaster.html?

**Comment by rouault** [comment]
> how to update the documentation of the GeoRaster driver at https://gdal.org/drivers/raster/georaster.html?

Just click on the "Edit on github" button on the top right :-) ? (you can include the change to the doc with your commit)

**Comment by rouault** [comment]
Unrelated note: I've just indicated you as maintainer for GeoRaster and OCI in the wikipage ( https://github.com/OSGeo/gdal/wiki/Maintainers-per-sub-system/_compare/9d493a644090a9beea4ea3682be3a2847831b8b0...26aa196ed6c5364150deb5970af3732ac9f3d379 ). I can revert that if you prefer not being mentioned

**Comment by fechen123** [comment]
> 
> 
> Unrelated note: I've just indicated you as maintainer for GeoRaster and OCI in the wikipage ( https://github.com/OSGeo/gdal/wiki/Maintainers-per-sub-system/_compare/9d493a644090a9beea4ea3682be3a2847831b8b0...26aa196ed6c5364150deb5970af3732ac9f3d379 ). I can revert that if you prefer not being mentioned



> 
> 
> > how to update the documentation of the GeoRaster driver at https://gdal.org/drivers/raster/georaster.html?
> 
> Just click on the "Edit on github" button on the top right :-) ? (you can include the change to the doc with your commit)

Thanks, I have made the changes online. It seems it is merged automatically.

**Comment by fechen123** [comment]
> 
> 
> > It seems it is merged automatically.
> 
> not in GDAL master normally as you don't have direct push rights. I guess that has created a branch in your fork

So I need to create a pull request?

**Comment by rouault** [comment]
> So I need to create a pull request?

yes, you can put it in the same pull request as the code changes
