### ISSUE TITLE
Support Chinese Field and Enitity Name after converting to FGDB using FileGDB driver

### ISSUE THREAD

**Issue by tom62291** [OSGeo/gdal#4112]
Hi,

FGDB should able to support Chinese Field and Entity Name. However, when i converting GML containing chinese field/entity name to FGDB, it will normalize to "_________".

May I ask how to convert GML with chinese field/entity name to FGDB correctly?

**Comment by rouault** [comment]
> May I ask how to convert GML with chinese field/entity name to FGDB correctly?

This will require code modifications in the FileGDB driver since it applies the "laundering" logic unconditionally. But I'm wondering to which extent the FileGDB format, and also ESRI software, supports non-ASCII characters for field names. Couldn't find online information regarding this. Have you seen such file geodatabases ?

**Comment by tom62291** [comment]
Yes, I does have FGDB containing Chinese field name.
 I also find there is some post which talking about chinese field or entity name:

<a href='https://trac.osgeo.org/gdal/ticket/5859'>https://trac.osgeo.org/gdal/ticket/5859</a>

**Comment by rouault** [comment]
> Yes, I does have FGDB containing Chinese field name.
> I also find there is some post which talking about chinese field or entity name:
> https://trac.osgeo.org/gdal/ticket/5859

Could you attach a .zip file with a FGDB with Chinese field names ? https://trac.osgeo.org/gdal/ticket/5859 seems to be about Chinese text as field *values*, not field names.

**Comment by tom62291** [comment]
Hi please find the attached FGDB with chinese entity and field name as well.

[GDBWithChineseEntityAndField.gdb.zip](https://github.com/OSGeo/gdal/files/6821202/GDBWithChineseEntityAndField.gdb.zip)

**Comment by gitlsl** [comment]
may be something relate https://github.com/OSGeo/gdal/issues/3633

**Comment by gitlsl** [comment]
hi, @rouault  
my env:  win11  ,gdal 3.6.2 x64 ,
 I  both try  openfilegdb  and  FileGDB    , they can not read  correct chinese layer  name  still , setup throught nuget `https://www.nuget.org/packages/GDAL.Plugins/3.6.2`

**Comment by jratike80** [comment]
Please provide test data.

**Comment by gitlsl** [comment]
@jratike80 
[test_data.zip](https://github.com/OSGeo/gdal/files/11045848/test_data.zip)

I update a zip, which contain  one gdb and a picture show in qgis
