### ISSUE TITLE
Is Geopdf <VectorLabel> will support other than point?

### ISSUE THREAD

**Issue by chakravarthi-vl** [OSGeo/gdal#4113]
HI Team

Is Geopdf  <VectorLabel>  will support line and polygon, if support please share any sample thing

**Comment by rouault** [comment]
"""
IMPORTANT: Do NOT use GitHub to post any questions or support requests!
           They will be closed immediately and ignored.

Questions should go to the gdal-dev mailing list at
https://lists.osgeo.org/mailman/listinfo/gdal-dev
or other support forums. GitHub issues are for bug
reports and suggestions for new features.
"""
