### ISSUE TITLE
No RPC metadata read from PCIDSK PIX file

### ISSUE THREAD

**Issue by deng0** [OSGeo/gdal#4118]
I've noticed that GDAL 3.3.0 no longer reads the RPC metadata from a PIX raster.
In GDAL 3.1 it still works.

Here is a small example pix (created by PCI2017):
[pix-test.zip](https://github.com/OSGeo/gdal/files/6822835/pix-test.zip)

Perhaps the regression is related to #3299

**Comment by rouault** [comment]
CC @pciphelippeneveu
