### ISSUE TITLE
Perhaps bug: Parsing S-57 map, most fields are not provided.

### ISSUE THREAD

**Issue by daniel-momot** [OSGeo/gdal#4121]
## Expected behavior and actual behavior.
I have a valid .000-file containing map in S-57 format ([US5TX51M.txt](https://github.com/OSGeo/gdal/files/6830725/US5TX51M.txt), extension is txt because .000 cannot be attached). I am trying to open it and read all fields contained in every feature.
By S-57 standard definition, each feature has 11 fields, common for all features (RCID, PRIM, GRUP, OBJL, RVER, AGEN, FIDN, FIDS, LNAM, LNAM_REFS, FFPT_RIND) and some other fields, special for type of object stored in the feature.
Some old version of GDAL (unfortunately, don't know which one) opens files correctly. Anyway, modern ones (view below) show only 11 attributes for all features, except of the single meta feature.

## Steps to reproduce the problem.
The C++ code is below. It completely follows [the example from docs](https://gdal.org/tutorials/vector_api_tut.html#reading-from-ogr).
Single changed line: from `for(const OGRLayer* poLayer: poDS->GetLayers())` to `for(OGRLayer* poLayer: poDS->GetLayers())`.
VS solution structure: MFC project calls DLL, it calles GDAL; Bug is present in 64-bit mode Debug and Release.

## Operating system
Windows 10 Home 20H2 build 19042.1110, Windows Feature Experience Pack 120.2212.3530.0
C++17
Visual Studio 2019 16.6.5, version 4.8.04084

## GDAL version and provenance
Tested on [GDAL 3.2.0](https://www.gisinternals.com/query.html?content=filelist&file=release-1911-x64-gdal-3-2-0-mapserver-7-6-1.zip), [GDAL 3.2.1](https://www.gisinternals.com/query.html?content=filelist&file=release-1911-x64-gdal-3-2-1-mapserver-7-6-2.zip), [GDAL 3.2.2](https://www.gisinternals.com/query.html?content=filelist&file=release-1928-x64-gdal-3-2-2-mapserver-7-6-2.zip), [GDAL 3.2.3](https://www.gisinternals.com/query.html?content=filelist&file=release-1928-x64-gdal-3-2-3-mapserver-7-6-3.zip), [GDAL 3.3.0](https://www.gisinternals.com/query.html?content=filelist&file=release-1928-x64-gdal-3-3-0-mapserver-7-6-3.zip).
Used one lib-file (gdal-i.lib) and all needed DLL-s (used Dependency Scan).

## Testing code
`
GDALAllRegister();
GDALDatasetUniquePtr poDS(GDALDataset::Open("US5TX51M.000", GDAL_OF_VECTOR));
if( poDS == nullptr ) {
  printf( "Open failed.\n" );
  exit( 1 );
}

    for (OGRLayer* poLayer : poDS->GetLayers()) {
      if (strcmp(poLayer->GetName(), "DSID") != 0) {  // Meta level is not interesting
        for (const auto& poFeature : *poLayer) {
          std::string s = "";
          for (const auto& oField : *poFeature)
            s += std::string(oField.GetName()) + " ";

          std::string out = "Met " + std::to_string(poFeature.get()->GetFieldCount()) + " fields: " + s + "\n";
          std::cout << out;
        }
      }
    }
`

**Comment by rouault** [comment]
I can't reproduce this.

For example the ogrinfo utility reports for ACHARE layer the following fields:
RCID: Integer (10.0)
PRIM: Integer (3.0)
GRUP: Integer (3.0)
OBJL: Integer (5.0)
RVER: Integer (3.0)
AGEN: Integer (5.0)
FIDN: Integer (10.0)
FIDS: Integer (5.0)
LNAM: String (16.0)
LNAM_REFS: StringList (16.0)
FFPT_RIND: IntegerList (1.0)
CATACH: StringList (0.0)
DATEND: String (0.0)
DATSTA: String (0.0)
NOBJNM: String (0.0)
OBJNAM: String (0.0)
PEREND: String (0.0)
PERSTA: String (0.0)
RESTRN: StringList (0.0)
STATUS: StringList (0.0)
INFORM: String (0.0)
NINFOM: String (0.0)
NTXTDS: String (0.0)
SCAMAX: Integer (0.0)
SCAMIN: Integer (0.0)
TXTDSC: String (0.0)
RECDAT: String (0.0)
RECIND: String (0.0)
SORDAT: String (0.0)
SORIND: String (0.0)

You should verify that the GDAL_DATA environment variable is pointing to the directory where the S57 resource files (s57attributes.csv, s57expectedinput.csv, s57objectclasses.csv) are located.

**Comment by daniel-momot** [comment]
@rouault Thank you so much! This was my fault, i set incorrect value of GDAL_DATA variable.
