### ISSUE TITLE
Building with static proj does not work

### ISSUE THREAD

**Issue by oleg-alexandrov** [OSGeo/gdal#4126]
## Expected behavior and actual behavior.

Building GDAL 3.3.1 with static proj per the doc  fails to work.

## Steps to reproduce the problem.

./configure --prefix=$PREFIX --with-proj=$PREFIX --enable-static --enable-static=proj  other-options

and it still links dynamically to libproj, so it can be seen when doing ldd libgdal.so. 

I tried some variations of the above with no luck.

I searched a lot on the mailing list and on the issues list and I cannot find a good recent answer to that. 

I need to build with static proj as otherwise I get conflicts with other dependencies which use an older proj.

## Operating system

Ubuntu 18 64 bit

## GDAL version and provenance

3.3.1, fetched from https://github.com/OSGeo/gdal/archive/refs/tags/v3.3.1.tar.gz

**Comment by rouault** [comment]
> with static proj per the doc

which doc ? There's no particular option to do static linking. You need to make sure libproj.so is not available at linking time. And I'm not sure that static linking will avoid clashes with other dependencies that use an older proj. The safe solution is to build everything against the same PROJ version

**Comment by oleg-alexandrov** [comment]
Thank you for your response. By the doc I meant the output of ./configure --help. 

It says:  --enable-static[=PKGS]  build static libraries [default=yes]

Also:

--with-proj-extra-lib-for-test=ARG   Additional libraries to pass the detection test, but not used for libgdal linking (i.e. -lcurl -ltiff ...). Mainly for static libproj

**Comment by rouault** [comment]
>  --enable-static

That's a generic configure option. It is meant to build GDAL as a static library, but given the odd use with do of autoconf/automake, I'm not sure if it is really effective

> --with-proj-extra-lib-for-test

This can help for statically linking PROJ to GDAL, but not necessarily enforce it. The best way is to make sure that only libproj.a is available

**Comment by oleg-alexandrov** [comment]
Yes, keeping only libproj.a forces gdal to link to it statically. Thank you very much! 

Now, I think you right that lumping libproj.a statically into libgdal.so won't result in its symbols being hidden so while ldd libgdal.so won't show libproj.so, the symbols in libproj.a could still cause conflict if another libproj.so is present. Apparently even --with-hide-internal-symbols is not working that great, according to this. https://trac.osgeo.org/gdal/ticket/1810
