### ISSUE TITLE
New PDFium changes

### ISSUE THREAD

**Issue by paulo-coutinho** [OSGeo/gdal#4134]
Hi,

To make it compatible with recent PDFium changes, please see this:
https://github.com/paulo-coutinho/gdal-pdfium/issues/2

Can you change the necessary things?

Most of things is already done, but left one or other.

Thanks.

**Comment by rouault** [comment]
> Can you change the necessary things?

The GDAL PDF driver is expected to be built against a specific (patched) version of pdfium as indicated in https://gdal.org/drivers/raster/pdf.html#pdfium

**Comment by paulo-coutinho** [comment]
Hi,

All patches are here:
https://github.com/paulo-coutinho/pdfium-lib/blob/gdal-support/modules/ios.py#L234-L356
