### ISSUE TITLE
gdaladdo memory issue cannot allocate *X* bytes

### ISSUE THREAD

**Issue by AnguIar** [OSGeo/gdal#4141]
## Expected behavior and actual behavior.

I have a `.gpkg` raster that holds data (only) in zoom level 15.
I then tried to build overviews with `gdaladdo` for this raster, using the following command:
 `gdaladdo --config GDAL_CACHEMAX 1500 --config COMPRESS_OVERVIEW DEFLATE  -r bilinear DUMMY.gpkg 16 32 64 128 256 512 1024 2048 4096 8192 16384 32768`

It DOES manage to build overviews until a certain point (zoom level 11), where it fails with this message: 
`0...10...20..ERROR 2: overview.cpp, 4145: cannot allocate 29949646468 bytes`

One more thing is, when I run `gdaladdo` on this raster without any parameters (e.g. `gdaladdo -r bilinear DUMMY.gpkg`)  - it SUCCESSFULLY builds the overviews BUT the process ends in zoom level 10 (if fills zoom levels 10-14).

## Operating system
```
$ hostnamectl
Operating System: Ubuntu 18.04.2 LTS
Kernel: Linux 5.4.0-77-generic
Architecture: x86-64
```

## GDAL version and provenance

```
$ gdaladdo --version
GDAL 3.2.0, released 2020/10/26
```
Also tried on another machine (`Ubuntu 18.04 x86-64`) with GDAL 3.3.0 on it and got the same result.
```
$ gdaladdo --version
GDAL 3.3.0, released 2021/04/26
```

**Comment by rouault** [comment]
Can you paste the output of ``gdalinfo DUMMY.gpkg`` ?

**Comment by AnguIar** [comment]
I've found out that the problem was with the extents of the raster file (table `gpkg_contents`). `gdaladdo` then couldn't process the correct overviews since the extent was broken. Sorry to bother and thanks anyways!
