### ISSUE TITLE
Update OGCAPI driver doc to reflect finalization of OGC API - Processes

### ISSUE THREAD

**Issue by jerstlouis** [OSGeo/gdal#4148]
## Expected behavior and actual behavior.

A sample execution request leveraging _OGC API - Proceses - Part 3: Workflows_ extension is presented in the OGC API driver documentation. The _OGC API - Processes - Part 1: Core_ has been finalized and a few changes should be made as a result:

```json
{
   "process" : "https://maps.ecere.com/ogcapi/processes/RenderMap",
   "inputs" : {
       "transparent" : false,
       "background" : "navy",
       "layers" : [
            { "collection" : "https://maps.ecere.com/ogcapi/collections/NaturalEarth:physical:bathymetry" },
            { "collection" : "https://maps.ecere.com/ogcapi/collections/SRTM_ViewFinderPanorama" }
        ]
    }
}
```
Note that the driver itself should not need any changes at this point, as it only looks for the top-level `process` key which remains unchanged, and submits the whole JSON document to that execution end-point.

The execution end-point for _OGC API - Processes - Part 1: Core_ did change from `/processes/{processId}` to `/processes/{processId}/execution`, and the _Workflows_ extension will likely adopt this change as well, but at this point the mechanism to distinguish regular sync/async execution from deferred mode (i.e.  returning a collection as this end-point currently does) has not yet been established, so the Ecere implementation still maintains the end-point in this example to indicate that a collection description should be returned rather than the sync process output (which is returned for `/processes/{processId}/execution`).

Once a decision on this is made, the GDAL OGC API driver would need to automatically append `/execution` and likely a query parameter to the URL identified by the `process` key. I will file a separate issue for this at that time.

## Steps to reproduce the problem.

Visit https://gdal.org/drivers/raster/ogcapi.html

## Operating system

N/A

## GDAL version and provenance

Latest

**Comment by rouault** [comment]
You could directly issue a pull request with the doc update :-) Just click on the edit on github link on top right of the doc page

**Comment by jerstlouis** [comment]
@rouault Done: https://github.com/OSGeo/gdal/compare/master...jerstlouis:patch-1
Sorry, I never noticed that link despite looking at that page so many times! :)
