### ISSUE TITLE
Error on GDALRasterBand::GetIndexColorTranslationTo

### ISSUE THREAD

**Issue by ldsw2112** [OSGeo/gdal#4156]
## Expected behavior and actual behavior.

Every color in Source color table should have a match in Dest color table.

## Steps to reproduce the problem.

```
std::array<unsigned char, 256Ui64> p_rBuffer;
unsigned char *l_pResult = m_pBandA->GetIndexColorTranslationTo(m_pBandB, p_rBuffer.data());

m_pBandA: ColorTable:
NO_DATA=0, [
0 -> 0xFF000000
1 -> 0xFF000000
2 -> 0xFF464663
3 -> 0xFF787878
4 -> 0xFFAFAFAF
...
39 -> 0xFFFAC8FA
]

m_pBandB: ColorTable:
NO_DATA=0, [
0 -> 0xFF000000
1 -> 0xFF000000
2 -> 0xFF323232
3 -> 0xFF787878
4 -> 0xFF969696
...
52 -> 0xFF808080
]

```

## Operating system

Windows 10 64bits
 
## GDAL version and provenance

Present in master branch

## Proposal:
```
if( !samePalette )
{
    // TODO(schwehr): Make 256 a constant and explain it.
    if (pTranslationTable == NULL)
        pTranslationTable =
            static_cast<unsigned char *>( CPLMalloc(256) );

    // Trying to remap the product palette on the subdataset
    // palette.
    for( int i = 0; i < nEntries; ++i )
    {
        if( bHasNoDataValueSrc && bHasNoDataValueRef &&
            noDataValueSrc == i )
            continue;
        const GDALColorEntry* entry =
            srcColorTable->GetColorEntry(i);
        int j = 0;  // j used after for.
        for( j = 0; j < nRefEntries; ++j )
        {
            if (bHasNoDataValueRef && noDataValueRef == j)
                continue;
            const GDALColorEntry* entryRef =
                destColorTable->GetColorEntry(j);
            if( entry->c1 == entryRef->c1 &&
                entry->c2 == entryRef->c2 &&
                entry->c3 == entryRef->c3 )
            {
                pTranslationTable[i] =
                    static_cast<unsigned char>(j);
                break;
            }
        }
        if( j == nRefEntries )
        {
            // No exact match. Looking for closest color now.
            int best_j = 0;
            int best_distance = 0;
            if( pApproximateMatching )
                *pApproximateMatching = TRUE;
            for( j = 0; j < nRefEntries; ++j )
            {
                const GDALColorEntry* entryRef =
                    destColorTable->GetColorEntry(j);
                int distance =
                    (entry->c1 - entryRef->c1) *
                        (entry->c1 - entryRef->c1) +
                    (entry->c2 - entryRef->c2) *
                        (entry->c2 - entryRef->c2) +
                    (entry->c3 - entryRef->c3) *
                        (entry->c3 - entryRef->c3);
                if( j == 0 || distance < best_distance )
                {
                    best_j = j;
                    best_distance = distance;
                }
            }
            pTranslationTable[i] =
                static_cast<unsigned char>(best_j);
        }
    }
    if( bHasNoDataValueRef && bHasNoDataValueSrc )
        pTranslationTable[noDataValueSrc] =
            static_cast<unsigned char>( noDataValueRef );

    return pTranslationTable;
}
```

The error is the condition to access the `No exact match` scope. If no match has been found then `j == nRefEntries` (ie number of color in dest color table.

**Comment by rouault** [comment]
I don't understand what the issue is, nor what would be wrong in the code you point to. Can you be more specific about what the issue is (which color doesn't have a match) and/or provide a full reproducer ?

**Comment by ldsw2112** [comment]
Hello,

The error is that you cannot have approximate color match. If an entry is
not found (exact match) then there is no index set in the translation table.

I join you some sample file,
 digest-file.7z
<https://drive.google.com/file/d/1S_g79lfia2l7k0rOxeOKhaKfdJZEX4UK/view?usp=drive_web>
try and execute this code:


GDALDataset *const l_pDatasetA = static_cast<GDALDataset
> *>(GDALOpenEx("DIRC01/DIRC0101.IMG", GDAL_OF_READONLY | GDAL_OF_RASTER |
> GDAL_OF_VERBOSE_ERROR, NULL, NULL, NULL));
> GDALDataset *const l_pDatasetB = static_cast<GDALDataset
> *>(GDALOpenEx("DIRC04/DIRC0401.IMG", GDAL_OF_READONLY | GDAL_OF_RASTER |
> GDAL_OF_VERBOSE_ERROR, NULL, NULL, NULL));

unsigned char* l_pBuffer[256];

m_pDatasetA->GetRasterBand(1)->GetIndexColorTranslationTo(m_pDatasetB->GetRasterBand(1),l_pBuffer);


It should be sufficient, if you look at l_pBuffer.
I expect:
[image: image.png]

Actually, I have:
[image: image.png]

This because there is no computation of approximate color (The condition is
wrong, it should be if (j == nRefEntries).


Jean-Yves CORBEL
Ingénieur développement logiciel, THALES Services S.A.S., Villeurbanne (FR)
------------------------------


*Avant d'imprimer assurez-vous que c'est bien nécessaire.Antes de imprimir,
piense en su responsabilidad y compromiso con el MEDIO AMBIENTE.Before
printing think about your responsibility and commitment to the ENVIRONMENT.*


Le sam. 31 juil. 2021 à 10:56, Even Rouault ***@***.***> a
écrit :
