### ISSUE TITLE
Implement some form of fail-safe mechanism when deleting vsimem files

### ISSUE THREAD

**Issue by mmomtchev** [OSGeo/gdal#4158]
## Expected behavior and actual behavior.

Currently it is all too easy to delete an open vsimem file by calling `VSIGetMemFileBuffer` with `bUnlinkAndSeize=TRUE`
Ideally, it should return `EBUSY` if there is an open dataset

## Steps to reproduce the problem.

The problem is evident in the Node.js bindings where it is (usually) up to the garbage collector to close open datasets

## GDAL version and provenance

3.3.1

**Comment by mmomtchev** [comment]
I am volunteering, but I wonder if this should be limited to vsimem and `VSIGetMemFileBuffer`

**Comment by rouault** [comment]
I don't think this would be a good idea. /vsimem/ aims at honoring POSIX file system policies, and unlinking an open file is something that is definitely permitted (and wishable) in POSIX.

**Comment by mmomtchev** [comment]
Yes but you don't get a kernel panic when closing that file
How about failing further operations gracefully?

**Comment by rouault** [comment]
> Yes but you don't get a kernel panic when closing that file
> How about failing further operations gracefully?

I understand there's a sequence of calls that present some issue for you. What is it exactly ?

**Comment by mmomtchev** [comment]
Not really, I just got burned by a code that did not explicitly close a Dataset obtained by `CreateCopy`. Just like in Python, closing in JS is optional - the garbage collector does it for you. If you always call `close`, there will be no problem. But without it - you get a silent error followed by random memory corruption. Normally, in the safe care bearers world of JS and Python programmers, these should be impossible.

**Comment by mmomtchev** [comment]
@rouault, there is an undocumented `gdal.VSIGetMemFileBuffer_unsafe` in the Python bindings?

**Comment by rouault** [comment]
> there is an undocumented `gdal.VSIGetMemFileBuffer_unsafe` in the Python bindings? What is unsafe about it?

I see this was added in fc81f28ae04b97bc3a14e30ecf53a105eb1065fe. @tzickel could you comment about what is unsafe ?

**Comment by tzickel** [comment]
It's unsafe that the function returns a Python memoryview object to a piece of raw memory which the lifetime isn't controlled by Python's memory management (so if the user isn't careful it might result in memory corruption).

**Comment by mmomtchev** [comment]
@tzickel, Ok, so it is precisely the same problem as the Node.js bindings
In Node.js I use `bUnlinkAndSeize` to create a Node.js-controlled `Buffer` - but I have the problem of still open Datasets that will cause memory corruption when they are reclaimed by the garbage collector.
This seems a very touchy point and I don't know enough about Python memory management to do it properly, but I was thinking about delaying the destruction of the `VSIMemFile` object until `nRefCount==0` while setting `pabyData=nullptr` and then checking for this special case in `Read`, `Write` and `Close` - so that I can fail gracefully.
@tzickel, would this be compatible with Python?
