### ISSUE TITLE
LVBAG Driver ignores field 'gerelateerdewoonplaats' for Feature Type 'nummeraanduiding' 

### ISSUE THREAD

**Issue by justb4** [OSGeo/gdal#4161]
## Expected behavior and actual behavior.

The LVBAG OGR Driver processes the Dutch Kadaster national dataset for Addresses and Buildings, called "BAG".
The feature type `nummeraanduiding` denotes a house number and refers to a "road" via the field `gerelateerdeopenbareruimte`. That road is usually completely contained within a city, called `woonplaats`.
But in some cases, about 2000, the same road is present in two cities. 
For those cases the BAG has defined an extra Field in  `nummeraanduiding`, called `gerelateerdewoonplaats`. 
So we expect that Field to be populated (usually NULL) by the LVBAG Driver.
But the LVBAG driver currently ignores the Field 'gerelateerdewoonplaats'. This leads to addresses that are present in the 'wrong' city. An example below.

@yorickdewid 

## Steps to reproduce the problem.

One example is the adres 'Kalfjeslaan 1 - 1181BN - Amstelveen'. The `nummeraanduiding` id is `0362010002079586`.
The adres can be viewed in the Dutch Kadaster BAG Viewer: 
https://bagviewer.kadaster.nl/lvbag/bag-viewer/index.html#?searchQuery=0362010002079586
The road id is `0363300000003944` which relates to city with id, `3594`, which is Amsterdam.
So the adres would be incorrectly reported as located in Amsterdam. But the `nummeraanduiding` source XML in this case contains the element `gerelateerdewoonplaats` populated with `1050`, which is Amstelveen. This is meant to override the default (of `3594`, Amsterdam).

## Operating system

Any.

## GDAL version and provenance

Latest as on august 3, 2021 using Docker Image `osgeo/gdal:ubuntu-small-latest`.

## Suggested Fix
Unfortunately my C++ is rusty, but the fix is very simple, only 2 lines, to read the missing field. A test case may be needed as well. 

In the file [gdal/ogr/ogrsf_frmts/lvbag/ogrlvbaglayer.cpp line L237](https://github.com/OSGeo/gdal/blob/master/gdal/ogr/ogrsf_frmts/lvbag/ogrlvbaglayer.cpp#L237) add the missing field with these two lines:

* L238: ` OGRFieldDefn oField6("gerelateerdewoonplaats", OFTString);`
* L245: `poFeatureDefn->AddFieldDefn(&oField6);`

**Comment by yorickdewid** [comment]
PR the feature, I'll review. If any test fail, it does work  :rofl:

**Comment by justb4** [comment]
Ok thanks @yorickdewid , will PR. "If any test fail, it does work", missing a negation somewhere  :-) ?

**Comment by justb4** [comment]
NB it appears that the XML Element is similarly structured as `openbareruimteRef`, e.g.

```
                    <Objecten:documentnummer>2009-BB01570</Objecten:documentnummer>
                    <Objecten:ligtIn>
                        <Objecten-ref:WoonplaatsRef domein="NL.IMBAG.Woonplaats">1050</Objecten-ref:WoonplaatsRef>
                    </Objecten:ligtIn>
                    <Objecten:voorkomen>
.
.
                    <Objecten:ligtAan>
                        <Objecten-ref:OpenbareRuimteRef domein="NL.IMBAG.Openbareruimte">0106300000002560</Objecten-ref:OpenbareRuimteRef>
                    </Objecten:ligtAan>

```

Advantage is that uses the existing parsing and prepending for `domein` attribute. Hence the Field will be named
`woonplaatsRef` with typical value like `NL.IMBAG.Woonplaats.1050`. This will be added to the test-data and cases in PR 4168.
