### ISSUE TITLE
VSIMemFile: use std::shared_ptr instead of manual ref counting

### ISSUE THREAD

**Issue by rouault** [OSGeo/gdal#4180]
As shown in https://github.com/OSGeo/gdal/pull/4179, VSIMemFile handling of shared VSIMemFile object is cumbersome. We should remove the nRefCount member in VSIMemFile and use a std::shared_ptr<VSIMemFile> in the oFileList map of VSIMemFilesystemHandler

**Comment by mmomtchev** [comment]
I don't see any elegant solution to `bOwnData = FALSE` with a shared_ptr

**Comment by rouault** [comment]
> I don't see any elegant solution to `bOwnData = FALSE` with a shared_ptr

that wouldn't fix that, but at least that will fix ref counting issues

**Comment by mmomtchev** [comment]
Maybe a custom deleter that deletes only when  `bOwnData = TRUE`
