### ISSUE TITLE
GDALFillNodata on 8bit image with any smoothing iterations reverts to prior image

### ISSUE THREAD

**Issue by AndrewAnnex** [OSGeo/gdal#4192]
## Expected behavior and actual behavior.

Running gdal_fillnodata.py on a 8bit image with 0 as the nodata value without smoothing iterations (default) works as expected. However, if the smoothing iterations ('si') parameter is set to any value other than the default, the output appears nearly identical to the input data, see attached data.

I am not sure if this is expected behavior with Fillnodata, my expectation would be that once the filled image is computed the smoothing operation would occur over the areas that were filled and then merged back with the original raster, and that the smoothing operation would not revert all of the correctly filled pixels to nans. Maybe the nodata mask is not being properly recomputed at https://github.com/OSGeo/gdal/blob/5cbb3cf16f3a04289db9e5d9b293e74479b34137/gdal/alg/rasterfill.cpp#L873 
or I need to pass in a explicit mask file to correct this behavior?

I should clarify, that with any smoothing iterations the generated image is not _literally_ the same as the input image despite the title, as the nodata areas do shrink slightly but possibly by a single pixel or so, otherwise at first glance the regions appear unchanged.

## Steps to reproduce the problem.

use this example raster [test_raster.tif.zip](https://github.com/OSGeo/gdal/files/6962597/test_raster.tif.zip) (~1.3mb compressed, ~2.3 uncompressed, uncompressed file sha256 b58bbec6a8f1f7c338153237eed091365b0633639e50c05f4b53b6ee8794b41e )
```
gdal_fillnodata.py -md 500 -si 0 test_raster.tif tf_si_0.tif
gdal_fillnodata.py -md 500 -si 1 test_raster.tif tf_si_1.tif
```
visually compare the three images to see before/after/after with smoothing iterations

## Operating system

Ubuntu 20.04 64 bit

## GDAL version and provenance

3.2.1 and 3.3.1 from conda-forge

**Comment by jratike80** [comment]
I can see a warning in https://gdal.org/api/gdal_alg.html#_CPPv414GDALFillNodata15GDALRasterBandH15GDALRasterBandHdiiPPc16GDALProgressFuncPv

> papszOptions – additional name=value options in a string list.
> 
> TEMP_FILE_DRIVER=gdal_driver_name. For example MEM.
> 
> NODATA=value (starting with GDAL 2.4). Source pixels at that value will be ignored by the interpolator. Warning: currently this will not be honored by smoothing passes.

**Comment by AndrewAnnex** [comment]
🎉 thanks @rouault!
