### ISSUE TITLE
64-Bit Integer Support for ESRI File Geodatabase

### ISSUE THREAD

**Issue by esnyder-rve** [OSGeo/gdal#4231]
## Problem
When exporting a geopackage with an integer field to a file geodatabase, the integer field gets converted to a double. There is a warning message that GDAL prints stating that Integer64 is not supported: `Warning 1: The output driver does not seem to natively support Integer64 type for field id. Converting it to Real instead. -mapFieldType can be used to control field type conversion.` Shouldn't this conversion be documented in the Known Issues section of the driver?

## Notes
* The file geodatabase supports both short and long integers.
* If the SDK does not provide such mechanic to specify, This limitation really should be documented in the driver's Known Issues section.
* ESRI has released newer SDK's since 1.4 on GitHub (yeah, I know🤯) https://github.com/Esri/file-geodatabase-api/

## Solution(s)
* Try and find how to store 64-Bit Integers as Long Integers with the current SDK
* Same as above, but with the latest SDK
* Document this limitation

**Comment by rouault** [comment]
This is a limitation of the file format itself. See https://pro.arcgis.com/en/pro-app/2.7/help/data/geodatabases/overview/arcgis-field-data-types.htm . "long integers" are just 32 bit integers

**Comment by esnyder-rve** [comment]
😒 Hmm... In that case, can this limitation be documented in the GDAL driver documentation somewhere?

**Comment by rouault** [comment]
> can this limitation be documented in the GDAL driver documentation somewhere?

done per https://github.com/OSGeo/gdal/commit/df3c95fd687a4ca21a82f8b2f98f7210c54a88b4
