### ISSUE TITLE
Linker errors when building with custom proj path.

### ISSUE THREAD

**Issue by here-abarany** [OSGeo/gdal#4237]
## Expected behavior and actual behavior.

Build on Linux fails to link executables due to being unable to find libproj.so and failing to resolve symbols.

## Steps to reproduce the problem.

1. Run `configure` with `--with-proj=/path/to/proj/prefix` argument.
2. Run make to build project.
3. Linking the CLI tools will fail because linking to libgdal.so will fail to find libproj.so and resolve its symbols.

As a workaround, you can add the following parameter to the call to `configure`: `LDFLAGS=-Wl,-rpath-link,/path/to/proj/prefix/lib`. This will use the `-rpath-link` ld option to provide the path where it can find libproj.so.

## Operating system

Arch Linux 

## GDAL version and provenance

GDAL 3.3.1.

This worked in 3.0.4, my guess is some changes in linker flags caused the failing tools to inherit the dependency to libproj.so from libgdal.so rather than linking to it directly. As a result the linker directory (passed with `-L`) is no longer provided, and `-rpath-link` needs to be used to find recursive library dependencies. (as `-L` is only searched for libraries being linked to directly)

**Comment by here-abarany** [comment]
It looks like this build error is limited to Linux. When testing on a Mac, the link error doesn't occur and the `-rpath-link` option isn't supported by the linker. (i.e. the workaround needs to be skipped on Mac)

**Comment by rouault** [comment]
I'm not sure there's any action needed on our side. You've likely another libproj.so in a system directory, which confuses linking if not prividing rpath.

**Comment by here-abarany** [comment]
I don't have libproj.so installed in any system directory or on my `PATH` environment variable. This is the cause of the problem: since libproj.so is in a custom path not searched by the linker by default, it's not able to find the libproj.so library when the tools link with libgdal.so. Since the purpose of setting `--with-proj=/path/to/proj/prefix` option is to provide a custom location of libproj.so, I'd consider that a bug with the build system that it won't work with additional custom linker flags. We set a custom rpath by adding the linker command-line argument `-rpath $ORIGIN/../lib` so we can create a redistributable package of external dependencies, but this can only find the library after it's been installed, and I've verified that the same problem occurs when I remove that argument.

As far as the fix on the GDAL side, I think you would want to add the linker argument `-Wl,-rpath-link,/path/to/proj/prefix/lib` when building on Linux and the `--with-proj=/path/to/proj/prefix` option is provided to the configure script. Otherwise the `--with-proj` option will always fail unless you either pass custom linker flags or make sure the `/path/to/proj/prefix` is in one of the default search paths for the linker.

On a similar topic, have you guys considered moving to something like CMake for the build system? CMake is pretty good about managing rpath, using absolute paths to the library locations during the normal build and the ability to customize rpath on install. It also handles a lot of other parts of the build in nicer ways, such as allowing out of source builds and easier ways to adjust lookup paths for external libraries. It took a significant amount of effort to integrate GDAL into our build for external dependencies, while nearly all of the other dependencies were built on top of CMake and trivial to integrate.

**Comment by rouault** [comment]
> I don't have libproj.so installed in any system directory or on my PATH environment variable

you may need to add it in LD_LIBRARY_PATH. But I see some builds where it is not needed. Is it a --without-libtool build ? Builds without --withou-libtool don't seem to need to set LD_LIBRARY_PATH

> On a similar topic, have you guys considered moving to something like CMake for the build system?

this is definitely something considered. Hopefully we should be able to start on that in the coming months

**Comment by here-abarany** [comment]
I double checked the flags we're passing and it looks like we were already passing `--without-libtool`. However, removing that flag does allow it to build without the `-rpath_link` workaround.

Glad to hear that moving to CMake is planned. Given that it works with the default options (with libtool enabled), and you're hoping to start moving to CMake in a few months, this probably isn't very high priority.

**Comment by rouault** [comment]
Wontfix given that cmake support is now in master
