### ISSUE TITLE
Cleanup: remove support for spatialite < 4.1.2

### ISSUE THREAD

**Issue by rouault** [OSGeo/gdal#4244]
spatialite < 4.1.2 is now ancient, and as we have a number of SPATIALITE_412_OR_LATER tests in the code base, it is time to clean that up

**Comment by theroggy** [comment]
@rouault I think this issue can be closed?

**Comment by rouault** [comment]
no, it hasn't been committed. There was a CI issue in https://github.com/OSGeo/gdal/pull/5265

**Comment by rouault** [comment]
removed per https://github.com/OSGeo/gdal/pull/7451 . The CI failure no longer happen as it was when running tests, and running tests has been disabled some time ago for another reason. That said I've done a manual minimal build of GDAL against gisinternals SDK and I managed to get spatialite working.
