### ISSUE TITLE
gdalwarp -dstalpha ignores internal nodata value

### ISSUE THREAD

**Issue by jessnichi** [OSGeo/gdal#4253]
## Expected behavior and actual behavior.

Running `gdalwarp -dstalpha` on a geotiff with an internal nodata value set, I would expect the resulting alpha band to be 0 in areas with nodata.  Instead, the resulting data is set to 255, unless `-srcnodata` is also supplied when calling gdalwarp.  This seems redundant, unintuitive, and - given the message during processing about using internal nodata values - likely not intended behavior.

## Steps to reproduce the problem.
```
$ gdalinfo input.tif 
Driver: GTiff/GeoTIFF
...
Band 1 Block=16384x1 Type=Byte, ColorInterp=Red
  NoData Value=0
Band 2 Block=16384x1 Type=Byte, ColorInterp=Green
  NoData Value=0
Band 3 Block=16384x1 Type=Byte, ColorInterp=Blue
  NoData Value=0
```

```
$ gdalwarp -dstalpha input.tif 1.tif
Creating output file that is 16384P x 16384L.
Processing input.tif [1/1] : 0Using internal nodata values (e.g. 0) for image input.tif.
...10...20...30...40...50...60...70...80...90...100 - done.
```

```
$ gdallocationinfo 1.tif 0 0
Report:
  Location: (0P,0L)
  Band 1:
    Value: 0
  Band 2:
    Value: 0
  Band 3:
    Value: 0
  Band 4:
    Value: 255
```

```
$ gdalwarp -dstalpha -srcnodata 0 input.tif 2.tif
Creating output file that is 16384P x 16384L.
Processing input.tif [1/1] : 0...10...20...30...40...50...60...70...80...90...100 - done.
```

```
$ gdallocationinfo 2.tif 0 0
Report:
  Location: (0P,0L)
  Band 1:
    Value: 0
  Band 2:
    Value: 0
  Band 3:
    Value: 0
  Band 4:
    Value: 0
```

## Operating system

Tested on Windows 10, CentOS 7, RHEL 6.10

## GDAL version and provenance

3.3.0 & 3.3.1 from conda-forge

**Comment by rouault** [comment]
I've queued a fix for that in https://github.com/OSGeo/gdal/pull/4257 . If you look at the updated documentation, you'll see this is quite subtle.  You can also workaround the issue by adding ``-wo UNIFIED_SRC_NODATA=YES`` if a pixel is considered to be invalid only if it evalues to (0,0,0), which is what is implied when specifying -srcnodata explictly
