### ISSUE TITLE
Compressed metadata can't be read.

### ISSUE THREAD

**Issue by geohardtke** [OSGeo/gdal#4292]
## Expected behavior and actual behavior.

In previous versions of gdal (<3.3.x) it was possible to set and then read compressed metadata. This functionality seems to be broken in the most recent versions of gdal.

## Steps to reproduce the problem.
The two  assertions in the python snippet bellow are true up to gdal 3.2.3. In , while the second one fails for gdal > 3.3.0

```python
from osgeo import gdal, gdalconst
import numpy as np
import zlib
import base64

# # Create a test file with metadata
test_filename = "test.img"
data = np.arange(81)
data.shape = (9,9)
fileformat = "HFA"
driver = gdal.GetDriverByName(fileformat)
dst_ds = driver.Create(test_filename, xsize=9, ysize=9,
                    bands=1, eType=gdal.GDT_Byte)
band = dst_ds.GetRasterBand(1)
meta_test  = {'key1': 'test', 'key2': 'test'}
band.SetMetadata( meta_test )
dst_ds = None
band = None

# Read the metadata and make sure it is the same
src = gdal.Open('test.img', gdalconst.GA_ReadOnly)
band = src.GetRasterBand(1)
src_meta = band.GetMetadata()
src_meta =  {k:v for (k,v) in src_meta.items() if k != 'LAYER_TYPE' }
assert(meta_test == src_meta)

# test compressing the metadata
test_filename = "test.img"
data = np.arange(81)
data.shape = (9,9)
fileformat = "HFA"
driver = gdal.GetDriverByName(fileformat)
dst_ds = driver.Create(test_filename, xsize=9, ysize=9,
                    bands=1, eType=gdal.GDT_Byte)
band = dst_ds.GetRasterBand(1)
meta_test  = {'key1': 'test', 'key2': 'test'}
meta_compressed = base64.b64encode(zlib.compress( bytes(str(meta_test), 'utf-8'), 9))

meta = dst_ds.GetMetadata()
meta["test"] = meta_compressed
band.SetMetadata( meta )
dst_ds = None

# Read the metadata and make sure it is the same
src = gdal.Open('test.img', gdalconst.GA_ReadOnly)
band = src.GetRasterBand(1)
src_meta = band.GetMetadata()
src_meta = src_meta["test"] 
src_meta = zlib.decompress(base64.b64decode(src_meta)).decode()
assert(str(meta_test) == src_meta)
```
With gdal > 3.3.0, I get an error:

```bash
Traceback (most recent call last):
  File "gdal_issue.py", line 51, in <module>
    src_meta = zlib.decompress(base64.b64decode(src_meta)).decode()
zlib.error: Error -3 while decompressing data: incorrect header check
```
I narrowed the problem down and it seems that `_gdal.MajorObject_GetMetadata_Dict(self, *args)` in line 1893 of https://github.com/OSGeo/gdal/blob/master/gdal/swig/python/osgeo/gdal.py returns an object with wrapped in an extra pair of quotation marks.  i.e. It use to return `b'eNqtWe9jsloow93jfjsjJGFkJtR4'`  (bytes) and now returns `"b'eNqtWe9jsloow93jfjsjJGFkJtR4'"` (string)  making zlib fail.

## GDAL version and provenance

I tested against version 3.2.3 and 3.3.0 versions available from dockerhub and also with self compiled versions.

**Comment by rouault** [comment]
Fix queued in https://github.com/OSGeo/gdal/pull/4297
An easy workaround is to do ``meta_compressed = meta_compressed.encode('utf-8')``

**Comment by geohardtke** [comment]
Excellent, thanks!
