### ISSUE TITLE
Consider deprecating the "mdb" driver

### ISSUE THREAD

**Issue by nyalldawson** [OSGeo/gdal#4311]
A potential candidate for driver deprecation is the "mdb" driver. 

From the driver page: "*This driver is primarily meant as being used on Unix platforms to overcome the issues often met with the MDBTools library that acts as the ODBC driver for MDB databases.*"

However, the MDBTools library is now actively maintained and recent versions offer a first rate experience with gdal. If that is indeed the main motivation behind the mdb driver, it could potentially be deprecated now.

**Comment by rouault** [comment]
As the author of the Java-based MDB driver and a non-maintainer of it, I support this. Let's mark it as deprecated in 3.4 for removal in 3.5 with the other already marked drivers
