### ISSUE TITLE
docker image 'tag' (eg. 3.2.3) doesn't remotely match software release

### ISSUE THREAD

**Issue by tb3088** [OSGeo/gdal#4329]
## Expected behavior and actual behavior.

branch v3.2 Dockerfile (actually pretty much all of them regardless of branch) is hard-coded to checkout 'master' branch which is a GROSS error. The osgeo/gdal:alpine-small-3.2.3 (and it's Ubuntu brothers) for example ships with v3.1.4 of the GDAL code not ~3.2

## Steps to reproduce the problem.

apk info py3-gdal
py3-gdal-3.1.4-r3 installed size:
2772 KiB

## Operating system

alpine

## GDAL version and provenance

3.2 branch

**Comment by rouault** [comment]
> The osgeo/gdal:alpine-small-3.2.3 (and it's Ubuntu brothers) for example ships with v3.1.4

this is not true:
```
$ docker run --rm -it osgeo/gdal:alpine-small-3.2.3 gdalinfo --version
GDAL 3.2.3, released 2021/04/27
```
If you use apk within the image, then yes you'll get an older version from the distro, not the custom one built in the image.

The default of the build scripts indeed uses GDAL master but you can specify tags / branches as well.

```
 ./docker/alpine-small/build.sh --help
Usage: build.sh [--push] [--tag name] [--gdal tag|sha1|master] [--gdal-repository repo] [--proj tag|sha1|master] [--release]

--push: push image to Docker hub
--tag name: suffix to append to image name. Defaults to 'latest' for non release builds or the GDAL tag name for release builds
--gdal tag|sha1|master: GDAL version to use. Defaults to master
--proj tag|sha1|master: PROJ version to use. Defaults to master
--gdal-repository repo: github repository. Defaults to OSGeo/gdal
--release. Whether this is a release build. In which case --gdal tag must be used.
--with-debug-symbols/--without-debug-symbols. Whether to include debug symbols. Only applies to ubuntu-full, default is to include for non-release builds.
```

**Comment by tb3088** [comment]
then why bundling outdated python bindings?

**Comment by rouault** [comment]
> then why bundling outdated python bindings?

they are not bundled. It is you who install them :-) The scope of each Docker image is described in https://github.com/OSGeo/gdal/tree/master/gdal/docker, and alpine-small doesn't bundle Python. As soon as you use the packaging system to install something GDAL related then you'll get the version of the distribution, which is outside of our control.  Java bindings aren't in the scope of those images.

**Comment by tb3088** [comment]
I installed nothing.

211(127) $ docker run -it osgeo/gdal:alpine-small-3.2.3 sh -c 'apk update; apk list -i | grep gdal'
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/x86_64/APKINDEX.tar.gz
v3.13.5-302-g9aab52aab9 [https://dl-cdn.alpinelinux.org/alpine/v3.13/main]
v3.13.5-301-gdaf41ef0ec [https://dl-cdn.alpinelinux.org/alpine/v3.13/community]
OK: 13902 distinct packages available
gdal-tools-3.1.4-r3 x86_64 {gdal} (MIT)
java-gdal-3.1.4-r3 x86_64 {gdal} (MIT)
py3-gdal-3.1.4-r3 x86_64 {gdal} (MIT)
gdal-static-3.1.4-r3 x86_64 {gdal} (MIT)
gdal-dev-3.1.4-r3 x86_64 {gdal} (MIT)
gdal-3.1.4-r3 x86_64 {gdal} (MIT)
