### ISSUE TITLE
Docker image does not bundle py3 or Java bindings

### ISSUE THREAD

**Issue by tb3088** [OSGeo/gdal#4331]
## Expected behavior and actual behavior.

image contains only GDAL shared-libs and minimal tooling but no Python or Java bindings. This yields a preposterous situation where one is dependent on the OS vendor to maintain and ship vital but often outdated modules. The bindings should be compiled and installed in /usr/local to avoid collision with OS vendor's "maybe we'll get around to it" approach of tracking GDAL project releases.

eg. osgeo/gdal:alpine-small-3.2.3 only supplies v3.1.4 of the bindings (because that's what Alpine 3.13 offers) while the GDAL libraries are at 3.2. The drift can trivially worsen if OS maintainers are slow/lazy about tracking upstream.

The bindings are in the same source tree, they should ALWAYS be included in the image.
The 'tiny' image can leave them out or perhaps just include the Python. 'small' might contain might add Java and 'normal' would contain all available.

## Operating system

alpine and ubuntu

## GDAL version and provenance

applies to any

**Comment by rouault** [comment]
closing as wontfix
