### ISSUE TITLE
GEOS LDFLAGS overwrite created a regression when configuring a build against Android NDK

### ISSUE THREAD

**Issue by nirvn** [OSGeo/gdal#4368]
This commit (https://github.com/OSGeo/gdal/commit/2a19767c76429ee03d5d0d41b55bb38ac7775c6a#diff-3c73726b523598e4e4779ab40bddce9bb1eb99c79244a3c2777b950c951064bd) caused a regression when building gdal in an Android NDK environment. This was discovered when I was updating the gdal recipe on OSGeo4A (QField's Android SDK).

Removing the LDFLAGS overwrite/whipe (as done here https://github.com/opengisch/OSGeo4A/pull/120/files#diff-beb9e4f3ba0c2c87c63fa93cbecc455dc7d2a8ec1fae998268ba01ff0c314915R36 ) fixes the configuration's GEOS handling.

@QuLogic , pinging you on this as you were the author of the above-mentioned commit.

**Comment by nirvn** [comment]
The configuration error I was getting is:

```
checking for geos-config... /usr/src/build/stage/arm64-v8a/bin/geos-config
checking for GEOS version >= 3.1.0... yes
checking for GEOSversion in -lgeos_c... no
configure: error: GEOS library could not be linked
The command '/bin/sh -c ARCHES="${ARCHES}" /usr/src/build_arches.sh' returned a non-zero code: 255

```

**Comment by rouault** [comment]
Yes clearing LDFLAGS is probably inappropriate. If the rationale to clear LDFLAGS was that CFLAGS was overwritten, then I think we should rather do CFLAGS="${GEOS_CFLAGS} ${CFLAGS}"

**Comment by nirvn** [comment]
@rouault , yeah, I think that'd be a better option.

**Comment by QuLogic** [comment]
Either is fine for me, as long as both are done the same way.
