### ISSUE TITLE
Auto recognize geometry field name of GML

### ISSUE THREAD

**Issue by tom62291** [OSGeo/gdal#4386]
Hi, I have below sample GML data
```
    <testschema:DCTC gml:id="DCTC_JI2N4iHJnE">
      <gml:boundedBy>
        <gml:Envelope srsName="http://www.opengis.net/gml/srs/epsg.xml#4326" srsDimension="2">
          <gml:lowerCorner>114.20894 22.391054</gml:lowerCorner>
          <gml:upperCorner>114.20894 22.391054</gml:upperCorner>
        </gml:Envelope>
      </gml:boundedBy>
      <testschema:FacilityName>Some Ltd.</testschema:FacilityName>
      <testschema:thisistextualfieldhahaha>
        <gml:Point srsName="http://www.opengis.net/gml/srs/epsg.xml#4326" srsDimension="2">
          <gml:pos>114.20894 22.391054</gml:pos>
        </gml:Point>
      </testschema:thisistextualfieldhahaha>
    </testschema:DCTC>
```

And then i use below python code to read it ,
```
inSource = ogr.Open("sample.gml")
inLayer = inSource.GetLayer()
f = inLayer.GetNextFeature()
g = f.GetGeometryRef()
r = g.GetSpatialReference()
print("Name:" +f.GetGeomFieldDefnRef(0).GetNameRef())
```

However, it print out empty string or null from the output, but I expect it shoule be "thisistextualfieldhahaha"  for the geometry field name.
May I know it is possible to auto recognize geometry field name of GML?

**Comment by jratike80** [comment]
Please use the gdal-dev mailing list for asking questions.

A test with a simple GML that is converted with ogr2ogr from a shapefile reveals that sometimes the name of the geometry field can be recognized.

```
ogrinfo states.gml -al -so
INFO: Open of `states.gml'
      using driver `GML' successful.

Layer name: states
Geometry: Polygon
Feature Count: 49
Extent: (-124.731422, 24.955967) - (-66.969849, 49.371735)
Layer SRS WKT:
(unknown)
Geometry Column = geometryProperty
```

However, I believe that the GML driver can resolve the name of the geometry field only if the XML schema is simple. For example from snippet from Finnish topological data the name "sijainti" is not recognized.

```
<MaastokuvionReuna gid="2044530150" dimension="3">
			<sijaintitarkkuus>7500</sijaintitarkkuus>
			<korkeustarkkuus>5000</korkeustarkkuus>
			<aineistolahde>2</aineistolahde>
			<alkupvm>2021-02-13</alkupvm>
			<kulkutapa>1</kulkutapa>
			<sijainti>
				<Murtoviiva>
					<gml:posList srsDimension="3">116000.000 6964068.435 0.001 114113.157 6954000.000 0.001</gml:posList>
				</Murtoviiva>
			</sijainti>
			<kohderyhma>19</kohderyhma>
			<kohdeluokka>30999</kohdeluokka>
			<aluejakoonOsallistuminen>0</aluejakoonOsallistuminen>
			<kartografinenLuokka>36211</kartografinenLuokka>
</MaastokuvionReuna>
```

**Comment by tom62291** [comment]
ok thank you. Will ask in gdal-dev

**Comment by tom62291** [comment]
But, If I change the GML to 
```
<testschema:geometry>
        <gml:Point srsName="http://www.opengis.net/gml/srs/epsg.xml#4326" srsDimension="2">
          <gml:pos>114.20894 22.391054</gml:pos>
        </gml:Point>
      </testschema:geometry>
```

It can read the "geometry" field  name out.
Is this a bug?

**Comment by jratike80** [comment]
Well, I suppose that GDAL is made to guess that geometry means geometry but that does not apply to "thisistextualfieldhahaha" or "sijainti". The proper way and how XML is supposed to work is create a valid XML schema file and map that thisistextualfieldhahaha means the GML geometry property. The other GDAL driver GMLAS can read and validate the schema. GML driver reads the data and tries to guess the contents "by scanning the file and looking for “known” gml objects in the gml namespace to determine the organization". Read about "schema" from https://gdal.org/drivers/vector/gml.html.

If you absolutely want to use the GML driver and geometry field "thisistextualfieldhahaha" it may be possible to do if you help GDAL by writing a xsd shema file.

I still consider that you are asking a question and not reporting a bug.

**Comment by tom62291** [comment]
Hi, may I know which version in https://www.gisinternals.com I can have a test on this fix?
