### ISSUE TITLE
autotest/gdrivers/rmf.py::test_rmf_31e randomly fails

### ISSUE THREAD

**Issue by rouault** [OSGeo/gdal#4399]
e.g in https://github.com/OSGeo/gdal/pull/4398/checks?check_run_id=3473089379
The random nature of the failure is likely due to this tests using random numbers. I strongly suspect this is due to the delta encoding of the values with a variable integer strategy in the RMFDem compressor, and for some deltas inappropriately being classified. Or using one of the reserved value.

**Comment by rouault** [comment]
CC @drons

**Comment by drons** [comment]
> CC @drons

Ok, I'll check it out.

**Comment by rouault** [comment]
Seems to be fixed
