### ISSUE TITLE
GPKG created from file without SRS returns file with GCS_Undefined_geographic_SRS

### ISSUE THREAD

**Issue by edzer** [OSGeo/gdal#4408]
While checking 3.3.2rc3, I found this from [regression tests in R package sf](https://github.com/r-spatial/sf/issues/1776), but could reproduce it with a shapefile without SRS, then `ogr2ogr x2.gpkg x2.shp`, then `ogrinfo x2.gpkg x2` gives the `GCS_Undefined_geographic_SRS`.  Shapefile:
[x2.zip](https://github.com/OSGeo/gdal/files/7093053/x2.zip)

In R, I'm using CreateLayer with NULL srs to create a GPKG, and it comes out with the GCS_Undefined_geographic_SRS.

**Comment by rouault** [comment]
This is related to https://github.com/OSGeo/gdal/pull/3286 (which went into 3.3.0).
Per http://www.geopackage.org/spec130/#_gpkg_geometry_columns, any spatial layer must have a SRID associated with it. In the absence of one, we arbitrarily select srid = 0 which is used for undefined geographic coordinate reference systems. 
If a undefined projected coordinate system (srid = -1) is better suited for your use case, you might pass a SRS created from the following WKT : ``LOCAL_CS["Undefined cartesian SRS"]``
So for me, this is "works as expected"

**Comment by rouault** [comment]
Now documented in https://github.com/OSGeo/gdal/pull/4409

**Comment by edzer** [comment]
Thanks, @rouault ! I'm sorry to learn that - we mapped the former behavior to "SRS unknown", which seems no longer possible for GPKG - users need to choose between unknown/Cartesian and unknown/Geographic, but what is a good default if the data are
```
a,b,geom
1,2,"POINT(0 1)"
2,3,"POINT(4 5)"
```
If you convert this csv file using `ogr2ogr x.gpkg x.csv`, I still see with `ogrinfo x.gpkg x`:
```
INFO: Open of `x.gpkg'
      using driver `GPKG' successful.

Layer name: x
Geometry: None
Feature Count: 2
Layer SRS WKT:
(unknown)
FID Column = fid
...
```
does that point to a hole that I can use too, or is that going to be fixed? ;-)
