### ISSUE TITLE
viewshed default curvature coefficient

### ISSUE THREAD

**Issue by rouault** [OSGeo/gdal#4415]
@szekerest  The doc mentions "Thus the default value for CurvCoeff that gdal_viewshed uses is 0.85714 (=~ 1-1/7).", but seeing gdal_viewshed.cpp dfCurvCoeff is initialized to 0. Should the doc be updated to reflect this 0 value (flat earth model if I understand well), or should the default value in code be adjusted to 0.85714  ?

**Comment by rouault** [comment]
Actually CC @idanmiara because it seems you were the one to document this option in https://github.com/OSGeo/gdal/pull/3103

**Comment by idanmiara** [comment]
I was going to check the viewshed algorithm more closely, but I didn't get to it.

ASAIK the default coefficient should not be zero.

**Comment by szekerest** [comment]
@rouault @idanmiara Yes the default value should be changed to 6/7 which is normally used by the other geospatial tools (like r.viewshed in GRASS)
