### ISSUE TITLE
autotest: Should GPSBabel read tests be skipped if OGR/GPX driver lacks read support?

### ISSUE THREAD

**Issue by DFEvans** [OSGeo/gdal#4420]
With a _very_ basic GDAL development build, two of the GPSBabel tests fail because my build lacks the Expat library - GDAL gives a fairly clear `ERROR 6: OGR/GPX driver has not been built with read support. Expat library required`.

I believe that all other driver-specific tests are automatically skipped if the driver is not available (at least, I didn't encounter any other failures!). `autotest/ogr/ogr_gpsbabel.py` does include `require_driver` entries for `GPSBabel` and `GPX`; however, from the ERROR 6 above, it sounds as if the GPX driver is available but only with write support.

Is there a way to specify that some of the tests should only run if read support exists?

```
―――――――――――――――――――――――――――――――――――――――――――――――― test_ogr_gpsbabel_1 ――――――――――――――――――――――――――――――――――――――――――――――――

    def test_ogr_gpsbabel_1():

        ds = ogr.Open('GPSBabel:nmea:data/gpsbabel/nmea.txt')
>       assert ds is not None
E       assert None is not None

/home/jbanorthwest.co.uk/danielevans/gdal/autotest/ogr/ogr_gpsbabel.py:60: AssertionError
----------------------------------------------- Captured stderr call ------------------------------------------------
ERROR 6: OGR/GPX driver has not been built with read support. Expat library required

 ogr/ogr_gpsbabel.py ⨯                                                                                 10% █

―――――――――――――――――――――――――――――――――――――――――――――――― test_ogr_gpsbabel_2 ――――――――――――――――――――――――――――――――――――――――――――――――

    def test_ogr_gpsbabel_2():

        ds = ogr.Open('data/gpsbabel/nmea.txt')
>       assert ds is not None
E       assert None is not None

/home/jbanorthwest.co.uk/danielevans/gdal/autotest/ogr/ogr_gpsbabel.py:71: AssertionError
----------------------------------------------- Captured stderr call ------------------------------------------------
ERROR 6: OGR/GPX driver has not been built with read support. Expat library required
```

**Comment by rouault** [comment]
> GPSBabel hasn't required expat in many, many years

I trust you on this, but the OGR GPX driver does need Expat. As the OGR GPSBabel driver uses gpsbabel to convert files from GPSBabel-understood formats to GPX, and the OGR GPX driver is used to read them, the GPSBabel driver is only functional if GDAL is built with Expat support
