### ISSUE TITLE
Wrong netcdf extent in GDAL 3.3.1

### ISSUE THREAD

**Issue by mcomelli** [OSGeo/gdal#4439]
[netcdf.zip](https://github.com/OSGeo/gdal/files/7114304/netcdf.zip)

## Expected behavior and actual behavior.

I expect to find the correct extent, but it's different depending on GDAL version.
Using GDAL 3.2.2:

> gdalinfo netcdf.nc
```
...
Corner Coordinates:
Upper Left  (   4.6196633,  52.4973840) 
Lower Left  (   4.6196633,  52.1612044) 
Upper Right (   5.1695632,  52.4973840) 
Lower Right (   5.1695632,  52.1612044) 
Center      (   4.8946133,  52.3292942) 
...
```
which is the expected answer.

Using GDAL 3.3.1:
> gdalinfo netcdf.nc
```
...
Corner Coordinates:
Upper Left  (    0.0,    0.0)
Lower Left  (    0.0,  431.0)
Upper Right (  705.0,    0.0)
Lower Right (  705.0,  431.0)
Center      (  352.5,  215.5)
...
```

## Steps to reproduce the problem.

gdalinfo netcdf.nc

## Operating system

Windows 10

## GDAL version and provenance

GDAL 3.2.2
GDAL 3.3.1

**Comment by jratike80** [comment]
Does the command print a list of subdatasets? If it does use the name of the subdataset as input, like
`gdalinfo NETCDF:"nap.nc":Band2`.

**Comment by mcomelli** [comment]
Thanks for fast answer.
Test file netcdf.zip is already attached at the beginning of my request (maybe not the best position...)
I have the problem when importing the file in QGIS (last version uses GDAL 3.3.1), so I'm using gdalinfo just to explain what the GDAL issue is.

**Comment by jratike80** [comment]
Sorry for being blind. I can repeat with GDAL 3.1.4 (ok) and GDAL 3.4.0dev (not ok) on Windows. No subdatasets reported.

**Comment by rouault** [comment]
You can workaround the issue by setting the configuration option / environment variable GDAL_NETCDF_IGNORE_XY_AXIS_NAME_CHECKS to YES
