### ISSUE TITLE
Code Checks warning about deprecated environment

### ISSUE THREAD

**Issue by DFEvans** [OSGeo/gdal#4448]
The Code Checks workflow (https://github.com/OSGeo/gdal/actions/workflows/code_checks.yml) is warning that it is using a deprecated environment:

> The ubuntu-16.04 environment is deprecated and will be removed on September 20, 2021. Migrate to ubuntu-latest instead. For more details see https://github.com/actions/virtual-environments/issues/3287

.github/workflows/code_checks.yml reveals that it's used in cppcheck_1604, a build specifically testing ubuntu-16.04, so it's not immediately obvious to me if it should be shifted to Ubuntu 18.04 or just removed entirely.

**Comment by rouault** [comment]
> .github/workflows/code_checks.yml reveals that it's used in cppcheck_1604, a build specifically testing ubuntu-16.04, so it's not immediately obvious to me if it should be shifted to Ubuntu 18.04 or just removed entirely.

I'd completely remove it, given that we have cppcheck_2004
