### ISSUE TITLE
CI: Conda ubuntu fails

### ISSUE THREAD

**Issue by rouault** [OSGeo/gdal#4450]
Our Conda ubuntu fails during the "conda build recipe" step of https://github.com/OSGeo/gdal/blob/master/gdal/ci/travis/conda/compile.sh . It fails after building GDAL itself, in a post processing stage of patching some files. I can also reproduce that locally when replicating the CI steps, although my failure occurs a bit later, in the GDAL python files, than in github action where it fails on the post processing of the native lib.

CC @ocefpaf sorry to annoy you about that but you've perhaps a better clue than me on that. So we do in GDAL CI custom Conda builds of GDAL master : the main purpose is to offer for download custom Conda builds as build artifacts, but it is also a means for us to check that we still build in Conda environment. Since Sept 6 (2 days ago), the Conda ubuntu build fails with https://github.com/OSGeo/gdal/runs/3538064934 and I don't think it is related in a change in GDAL itself, nor in the gdal-feedstock whose latest commit dates back to Sept 1st. @hobu mentioned to me that there was a lot of churn in conda-forge lately regarding compiler settings.

Relevant files:
- github workflow: https://github.com/OSGeo/gdal/blob/master/.github/workflows/conda.yml
- and the scripts it calls: https://github.com/OSGeo/gdal/tree/master/gdal/ci/travis/conda

**Comment by ocefpaf** [comment]
> CC @ocefpaf sorry to annoy you about that but you've perhaps a better clue than me on that.

You are probable the only person who has carte blanche to annoy anyone who depends/uses on gdal :smile:

I'm looking at it now. There are conflicts that are probably due to old pins. Sometimes those can be solved by rebuilding the pinned packages with modern dependencies/compilers, sometimes that is  too hard and we have to update it by releasing the pin. I'll let you know as soon as I find something.

**Comment by ocefpaf** [comment]
It is definitely a change in our packages upstream and nothing related to gdal. Even our own feedstock is broken with the same conflict when building the python extension. I'm still debugging it and hopefully, when we fix it, you can just restart the CIs and they'll pass.

**Comment by ocefpaf** [comment]
Thanks to @xylar we now the source of the conflict. If you want to get the CIs up online now we can send a PR to pin libffi here but if you wait a bit we will have new builds of Python with the proper pin, that will remove the conflict, in 1-2 days.

**Comment by rouault** [comment]
> if you wait a bit we will have new builds of Python with the proper pin, that will remove the conflict, in 1-2 days.

waiting for a few days is fine. Thanks for your investigation

**Comment by rouault** [comment]
Things are green again ! Closing
