### ISSUE TITLE
docker ubuntu-small and FileGDB_API

### ISSUE THREAD

**Issue by chyzwar** [OSGeo/gdal#4455]
I was trying to use mailing list but I gave up. 

We would like to use ubuntu-small image but with FileGDB_API.
I am not very familiar with gdal build system. Can someone provide information on how add FileGDB_API on top of ubuntu-small?
 
Please

**Comment by jratike80** [comment]
What was your problem with the mailing list?

**Comment by rouault** [comment]
Optional support it is only included in the ubuntu-full image if you pass ``--build-arg WITH_FILEGDB=yes`` to docker build. You could likely port the logic from ubuntu-full to ubuntu-small. Look for WITH_FILEGDB in docker/ubuntu-full/Dockerfile and docker/ubuntu-full/bh-gdal.sh

**Comment by chyzwar** [comment]
I managed to register but when I try to visit gdal-dev
```
gdal-dev roster authentication failed.
```

**Comment by chyzwar** [comment]
It would be nice if there is an image where everything is optional and we can pick and choose what is included.

**Comment by rouault** [comment]
> It would be nice if there is an image where everything is optional and we can pick and choose what is included.

the build recipees are provided to enable anyone to customize them according to their need.

**Comment by jratike80** [comment]
I am not sure what you did "when I try to visit gdal-dev". After registration you should be able to send mail from you own mail account into gdal-dev@lists.osgeo.org.

**Comment by chyzwar** [comment]
> the build recipees are provided to enable anyone to customize them according to their need.

How? There is no single example how to customize gdal build(drivers)  in https://github.com/OSGeo/gdal/tree/master/gdal/docker
What you need to do is fork these Dockerfiles and figure out how to add a build dependency. If you are not familiar with gdal build system, it is non-trivial and require a lot of trial and error.  

What I suggest is more like Erlang install where you use --with-x flags https://erlang.org/doc/installation_guide/INSTALL.html
You could have one installation script used across different images. 

```Dockerfile
FROM ubuntu:focal

RUN curl -fsSL https://.....gdal.org/release -o gdal-install-3.21.bash
RUN bash gdal-install.bash \
  --with-FileGDB \
  --with-GPKG

```

Same script could be used to build small and full images, just with different options. Instead, what we have is small-image that is too small and full image that is too big. There is no documentation on how to build gdal beside these Dockerfiles.
