### ISSUE TITLE
Mention deprecated drivers in doc

### ISSUE THREAD

**Issue by VirtualTim** [OSGeo/gdal#4456]
Doco ([link](https://gdal.org/drivers/raster/intergraphraster.html)) says that the driver is build by default. That is not the case in 3.3. Trying to use one of those formats logs:

> ERROR 1: Driver INGR is considered for removal in GDAL 3.5. You are invited to convert any dataset in that format to another more common one.
> If you need this driver in future GDAL versions, create a ticket at https://github.com/OSGeo/gdal (look first for an existing one first) to explain how critical it is for you (but the GDAL project may still remove it), and to enable it now, set the GDAL_ENABLE_DEPRECATED_DRIVER_INGR configuration option / environment variable to YES
> gdalinfo failed - unable to open 'test.cit'.

**Comment by rouault** [comment]
technically the driver is still built. You just need an extra runtime step to activate it.
We've just prototyped documenting those drivers in https://github.com/OSGeo/gdal/pull/4365

**Comment by rouault** [comment]
Fixed per https://github.com/OSGeo/gdal/pull/4473

**Comment by VirtualTim** [comment]
Oh OK. I took the message to mean that you needed to set `GDAL_ENABLE_DEPRECATED_DRIVER_INGR` at _compile_ time.
I guess I just misunderstood the message.
