### ISSUE TITLE
WMTS: wrong default extent for www.ign.es/wmts/pnoa-ma WMTS in EPSG:25830

### ISSUE THREAD

**Issue by rouault** [OSGeo/gdal#4461]
Related to https://lists.osgeo.org/pipermail/gdal-dev/2021-September/054657.html

gdalinfo "WMTS:http://www.ign.es/wmts/pnoa-ma?request=GetCapabilities&service=WMTS&layer=OI.OrthoimageCoverage,tilematrixset=EPSG:25830"
reports
Upper Left  (  404318.828, 7271532.000) (  5d 4'19.71"W, 65d33' 6.57"N)
Lower Left  (  404318.828, 2992357.845) (  3d57'53.21"W, 27d 3' 0.59"N)
Upper Right (  468954.099, 7271532.000) (  3d40'21.33"W, 65d33'52.09"N)
Lower Right (  468954.099, 2992357.845) (  3d18'47.02"W, 27d 3'11.25"N)
Center      (  436636.463, 5131944.922) (  3d49'24.02"W, 46d20'17.22"N)

This extent is wrong and comes from reprojecting the following almost global extent to EPSG:25830 which is Transverse Mercator
<ows:WGS84BoundingBox>
<ows:LowerCorner>-179.9776170624479 -73.51695785571678</ows:LowerCorner>
<ows:UpperCorner>179.9838090799818 84.650213009049</ows:UpperCorner>
</ows:WGS84BoundingBox>

The logic
```
                    // Otherwise try to reproject the bounding box of the
                    // layer from its SRS to the TMS SRS. Except in some cases
                    // where this would result in non-sense. (this could be
                    // improved !)
                    if( !(bIsTMerc && oSRS.IsGeographic() &&
                          fabs(oIter->second.MinX - -180) < 1e-8 &&
                          fabs(oIter->second.MaxX - 180) < 1e-8) )
                    {
```
should be tuned to avoid that.

Specifying  -oo EXTENT_METHOD=MOST_PRECISE_TILE_MATRIX works around the issue

**Comment by fbecir** [comment]
Hello

The workaround does not seem to work:
`gdalinfo -oo EXTENT_METHOD=MOST_PRECISE_TILE_MATRIX "WMTS:https://wxs.ign.fr/ortho/geoportail/wmts?SERVICE=WMTS&VERSION=1.0.0&REQUEST=GetCapabilities,layer=ORTHOIMAGERY.ORTHOPHOTOS"`

It gives a truncated bounding box:
```
Corner Coordinates:
Upper Left  (    4586.222, 6392887.298) (  0d 2'28.32"E, 49d41'26.63"N)
Lower Left  (    4586.222, 5346617.254) (  0d 2'28.32"E, 43d13'37.90"N)
Upper Right (  634427.335, 6392887.298) (  5d41'56.97"E, 49d41'26.63"N)
Lower Right (  634427.335, 5346617.254) (  5d41'56.97"E, 43d13'37.90"N)
Center      (  319506.778, 5869752.276) (  2d52'12.64"E, 46d33'18.30"N)
```
Normally, the layer should cover the world, but even France is truncated. Here is the GetCapabilities result for this layer:
```
<ows:WGS84BoundingBox>
<ows:LowerCorner>-178.187 -85</ows:LowerCorner>
<ows:UpperCorner>175 85</ows:UpperCorner>
</ows:WGS84BoundingBox>
```
If we restrict the zoom level, the bounding box is larger:
`gdalinfo -oo EXTENT_METHOD=MOST_PRECISE_TILE_MATRIX -oo ZOOM_LEVEL=18 "WMTS:https://wxs.ign.fr/ortho/geoportail/wmts?SERVICE=WMTS&VERSION=1.0.0&REQUEST=GetCapabilities,layer=ORTHOIMAGERY.ORTHOPHOTOS"`

```
Corner Coordinates:
Upper Left  (-19836938.178, 9360784.232) (178d11'53.69"W, 64d 2'36.11"N)
Lower Left  (-19836938.178,-2604973.924) (178d11'53.69"W, 22d46'34.25"S)
Upper Right (18697108.615, 9360784.232) (167d57'32.34"E, 64d 2'36.11"N)
Lower Right (18697108.615,-2604973.924) (167d57'32.34"E, 22d46'34.25"S)
Center      ( -569914.781, 3377905.154) (  5d 7'10.67"W, 29d 1' 3.89"N)
```

Any idea how to solve this problem ?
Thanks a lot

**Comment by jratike80** [comment]
Results look odd but are we looking at the same bounding box?
```
<ows:WGS84BoundingBox>
<ows:LowerCorner>-63.1607 -21.4013</ows:LowerCorner>
<ows:UpperCorner>55.8464 64.0698</ows:UpperCorner>
</ows:WGS84BoundingBox>
<ows:Identifier>HR.ORTHOIMAGERY.ORTHOPHOTOS</ows:Identifier>
```

**Comment by fbecir** [comment]
Hello 

Thank you for your quick answer and your help.
We are not talking about the same layer (you : HR.ORTHOIMAGERY.ORTHOPHOTOS , me :ORTHOIMAGERY.ORTHOPHOTOS).
ORTHOIMAGERY.ORTHOPHOTOS is the third layer in the GetCapabilities.

I don't think there is a limit in the tile matrix set:
<TileMatrixLimits>
<TileMatrix>0</TileMatrix>
<MinTileRow>0</MinTileRow>
<MaxTileRow>0</MaxTileRow>
<MinTileCol>0</MinTileCol>
<MaxTileCol>1</MaxTileCol>
</TileMatrixLimits>
<TileMatrixLimits>
<TileMatrix>1</TileMatrix>
<MinTileRow>0</MinTileRow>
<MaxTileRow>1</MaxTileRow>
<MinTileCol>0</MinTileCol>
<MaxTileCol>2</MaxTileCol>
</TileMatrixLimits>
...

**Comment by jratike80** [comment]
Right. It seems to use TileMatrixSet "PM" and TileMatrix "0" is defined
```
<TileMatrixSet>
...
</TileMatrixSet>
<TileMatrixSet>
<ows:Identifier>PM_5cm</ows:Identifier>
<ows:SupportedCRS>EPSG:3857</ows:SupportedCRS>
<TileMatrix>
<ows:Identifier>0</ows:Identifier>
<ScaleDenominator>559082264.0287178958533332</ScaleDenominator>
<TopLeftCorner>-20037508.3427892476320267 20037508.3427892476320267</TopLeftCorner>
<TileWidth>256</TileWidth>
<TileHeight>256</TileHeight>
<MatrixWidth>1</MatrixWidth>
<MatrixHeight>1</MatrixHeight>
```
I have not done these exercises a lot. If that level has one tile, doesn't it feel odd if MinTileCol=0 and MacTileCol=1. I think it means two tiles side by side, but there is only one in the matrix.

**Comment by fbecir** [comment]
The PM TileMatrixSet is the number 8 in the list.
Here is the start of PM:
```
<TileMatrixSet>
<ows:Identifier>PM</ows:Identifier>
<ows:SupportedCRS>EPSG:3857</ows:SupportedCRS>
<TileMatrix>
<ows:Identifier>0</ows:Identifier>
<ScaleDenominator>559082264.0287178958533332</ScaleDenominator>
<TopLeftCorner>
-20037508.3427892476320267 20037508.3427892476320267
</TopLeftCorner>
<TileWidth>256</TileWidth>
<TileHeight>256</TileHeight>
<MatrixWidth>1</MatrixWidth>
<MatrixHeight>1</MatrixHeight>
</TileMatrix>
```

I have the problem with gdalinfo but I have no problem with QGIS.

**Comment by jratike80** [comment]
So TileMatrix "0" in TileMatrixSet "PM" has one tile. Do you feel that the limits are right:
```
<TileMatrixLimits>
<TileMatrix>0</TileMatrix>
<MinTileRow>0</MinTileRow>
<MaxTileRow>0</MaxTileRow>
<MinTileCol>0</MinTileCol>
<MaxTileCol>1</MaxTileCol>
</TileMatrixLimits>
```
Doesn't that mean that there should be two tiles side by side, but there exists only one?

**Comment by fbecir** [comment]
In the OGC specifications of WMTS, you can read:
minTileRow : Minimum tile row index valid for this layer.
maxTileRow : Maximum tile row index valid for this layer. 

Thus the index 0 is valid. It means that you have 2 tiles : [0 ; 0] and [0 ; 1] 
It is how I understand the specifications ... but my English is not so good !

**Comment by jratike80** [comment]
Compare it with the matrix size
``
<MatrixWidth>1</MatrixWidth>
<MatrixHeight>1</MatrixHeight>
```

**Comment by jratike80** [comment]
Look the limits of all zoom levels. They are wrong for levels 0 and 1. Since that the limits set same number of rows and colums, for example 4:
```
<TileMatrixLimits>
<TileMatrix>4</TileMatrix>
<MinTileRow>0</MinTileRow>
<MaxTileRow>16</MaxTileRow>
<MinTileCol>0</MinTileCol>
<MaxTileCol>16</MaxTileCol>
</TileMatrixLimits>
```
When you limit the zoom level gdalinfo reads the configuration of corresponding TileMatrix and if it is not "0" or "1" then it is configured right. I suggest to contact IGN and ask them to fix their service if somebody else confirms my thoughts.

**Comment by fbecir** [comment]
You are right, the tile matrix should be corrected.
I do not have the same understanding of the ZOOM_LEVEL parameter.
How I understand it, with ZOOM_LEVEL=18, it means that I do not use the zoom_level 19, 20 ... but I still use the zoom_level 0.
For instance gdalinfo with ZOOM_LEVEL=18 gives:
`Pixel Size = (0.597164283477939,-0.597164283477939)`
Without ZOOM_LEVEL :
`Pixel Size = (0.074645535434742,-0.074645535434742)`

**Comment by jratike80** [comment]
Perhaps my guess is not right even gdalinfo results would suit to that assumption.

Even mentions an open option that does not seem to be documented in https://gdal.org/drivers/raster/wmts.html
`Specifying -oo EXTENT_METHOD=MOST_PRECISE_TILE_MATRIX works around the issue`

**Comment by fbecir** [comment]
I downloaded the xml file given by the GetCapabilities and I made the corrections in the TileMatrixLimits.
But gdalinfo still gives me the same results ...
Thus it is something else.
Thanks a lot Jukka for your help 👍

**Comment by fbecir** [comment]
Still working on this issue ...
Thus I tried to debug what happens exactly in the WMTS driver (wmtsdataset.cpp).
I am not sure to understand everything, but the driver reads perfectly the bounding box, the TileMatrixSet ... but it clips the bounding box on the most precise tile matrix (line 1852):
```
// Clip with limits of most precise TM when available
        {
            const WMTSTileMatrix& oTM = oTMS.aoTM.back();
            if( aoMapTileMatrixLimits.find(oTM.osIdentifier) != aoMapTileMatrixLimits.end() )
            {
                const WMTSTileMatrixLimits& oTMLimits = aoMapTileMatrixLimits[oTM.osIdentifier];
                double dfTileWidthUnits = oTM.dfPixelSize * oTM.nTileWidth;
                double dfTileHeightUnits = oTM.dfPixelSize * oTM.nTileHeight;
                sAOI.MinX = std::max(sAOI.MinX, oTM.dfTLX + oTMLimits.nMinTileCol * dfTileWidthUnits);
                sAOI.MaxY = std::min(sAOI.MaxY, oTM.dfTLY - oTMLimits.nMinTileRow * dfTileHeightUnits);
                sAOI.MaxX = std::min(sAOI.MaxX, oTM.dfTLX + (oTMLimits.nMaxTileCol + 1) * dfTileWidthUnits);
                sAOI.MinY = std::max(sAOI.MinY, oTM.dfTLY - (oTMLimits.nMaxTileRow + 1) * dfTileHeightUnits);
            }
        }
```
In this case, it is unfortunate. 
This layer covers the all world on the low levels (0, 1, 2 ...).
But on the last zoom level (21), the layer covers just a part of France.
Why does GDAL clip the bounding box of the layer ?

Now I understand why it works better when I use the ZOOM_LEVEL parameter but it does not solve my problem.

**Comment by jratike80** [comment]
I have not checked, but is it so that at the best resolution `Pixel Size = (0.074645535434742,-0.074645535434742)` service does not have any data outside that part of France? Or do you mean that the clipped bbox is wrong?

**Comment by fbecir** [comment]
Thanks a lot Even and Jukka 👍

@jratike80 : the computation made by GDAL is good, but the very high resolution does not exist everywhere in France.

@rouault : thanks a lot for the future new option.  I believe that a lot of WMTS servers of national institutes like IGN can have the same behaviour : they need to show the whole world on the low levels of the pyramid, but the high resolution data exist only on the bounding box of the country.

**Comment by jratike80** [comment]
If there are high resolution imagery only from France but the zoom levels 0-2 cover the whole world, what happens when user trusts the global bbox and requests high resolution data from Spain? Error from the server, empty tiles, or what?

**Comment by fbecir** [comment]
Jukka, normally the Tile Matrix limits give you, for each zoom level, the bounding box where you can find valid tiles.

A WMTS dataset is a group of several layers. Each layer has several zoom levels, each zoom level has its own bounding box. My understanding is that the bounding box of the layer should be the union of the bounding boxes of the zoom levels.
But I can also understand that some users prefer to have the intersection of the bounding boxes : they want to be sure to have valid tiles for each zoom level.

**Comment by jratike80** [comment]
On the other hand, if there orthophotos from France with 0.5 m pixel size, is it worth to inform that there are something in Canada as well, but with some 100 km pixel size? But users will have a choice now.

**Comment by fbecir** [comment]
Well, in France it is a bit more complicated : France has territories all over the world (French Guyana, Martinique, Guadeloupe, Réunion, Mayotte ... and Saint-Pierre-et-Miquelon near Canada !!!).
Thus you have a 0.25 m pixel size on the French territories and in order to connect them, there is a low resolution imagery.

**Comment by jratike80** [comment]
The orthophoto layer in the IGN WMTS has for example these limits
```
<TileMatrixLimits>
<TileMatrix>18</TileMatrix>
<MinTileRow>69840</MinTileRow>
<MaxTileRow>148111</MaxTileRow>
<MinTileCol>1312</MinTileCol>
<MaxTileCol>253375</MaxTileCol>
</TileMatrixLimits>
```
Do you mean that there are orthophotos also elsewhere, and actually this service should have many limits, like a multipolygon?

**Comment by fbecir** [comment]
In a perfect world, you are right : the limits should be a multipolygon. But the WMTS specifications do not allow such a thing.

In the example you gave, the bounding box defined by the TileMatrixLimits is 12000 km x 38000 km !
You can find the zoom level 19 on the Réunion island:

`https://wxs.ign.fr/ortho/geoportail/wmts?LAYER=ORTHOIMAGERY.ORTHOPHOTOS&EXCEPTIONS=text/xml&FORMAT=image/jpeg&SERVICE=WMTS&VERSION=1.0.0&REQUEST=GetTile&STYLE=normal&TILEMATRIXSET=PM&TILEMATRIX=19&TILEROW=294002&TILECOL=343365&`

Have a look also to the IRC orthoimage (ORTHOIMAGERY.ORTHOPHOTOS.IRC).
You have tiles on the zoom level 19 for Saint-Pierre-et-Miquelon:
`https://wxs.ign.fr/ortho/geoportail/wmts?LAYER=ORTHOIMAGERY.ORTHOPHOTOS.IRC&EXCEPTIONS=text/xml&FORMAT=image/jpeg&SERVICE=WMTS&VERSION=1.0.0&REQUEST=GetTile&STYLE=normal&TILEMATRIXSET=PM&TILEMATRIX=19&TILEROW=184865&TILECOL=180342&`

French Guyana:
`https://wxs.ign.fr/ortho/geoportail/wmts?LAYER=ORTHOIMAGERY.ORTHOPHOTOS.IRC&EXCEPTIONS=text/xml&FORMAT=image/jpeg&SERVICE=WMTS&VERSION=1.0.0&REQUEST=GetTile&STYLE=normal&TILEMATRIXSET=PM&TILEMATRIX=19&TILEROW=254953&TILECOL=185989&`

Martinique:
`https://wxs.ign.fr/ortho/geoportail/wmts?LAYER=ORTHOIMAGERY.ORTHOPHOTOS.IRC&EXCEPTIONS=text/xml&FORMAT=image/jpeg&SERVICE=WMTS&VERSION=1.0.0&REQUEST=GetTile&STYLE=normal&TILEMATRIXSET=PM&TILEMATRIX=19&TILEROW=240636&TILECOL=173238&`

and so on for La Réunion, la Guadeloupe ...

But for the rest of the world, you just have white pixels ...
