### ISSUE TITLE
OpenFileGDB driver does not list non-spatial tables in certain circumstances

### ISSUE THREAD

**Issue by nyalldawson** [OSGeo/gdal#4463]
I've encountered some GDB databases with non-spatial tables which aren't exposed by the OpenFileGDB driver. 

Looks like these non-spatial tables are stored slightly different in GDB files. They aren't present in the GDB_Items layer, but are instead listed only in the GDB_SystemCatalog table. Currently the driver only shows non-spatial tables which are also present in the GDB_Items layer. 

I suspect there must be some logic happening in the GDB spec which causes "simple" non-spatial tables (i.e. those without domains, metadata, aliases, etc) to skip the GDB_Items catalog and only be referenced in GDB_SystemCatalog. (Although I've been unable to find the magic formula required to actually make this happen!)

The logic we should follow would be something like the PGeo driver does, where we read all tables from the GDB_SystemCatalog list, skipping any with a GDB_ prefix (unless a LIST_ALL_TABLES open option is present, in which case we should mark them as private layers).

**Comment by rouault** [comment]
How does the FileGDB driver behave on such databases ? I'd be curious to see such one.
And does ArcMap exposes them to the user ? I would have thought that only tables listed in GDB_Items would be of user interest.

> The logic we should follow would be something like the PGeo driver does, where we read all tables from the GDB_SystemCatalog list, skipping any with a GDB_ prefix (unless a LIST_ALL_TABLES open option is present, in which case we should mark them as private layers).

At first sight, that makes sense

**Comment by nyalldawson** [comment]
> And does ArcMap exposes them to the user

Yes

I've a meeting with the customer next week to discuss and hopefully clarify the workflow which leads to the difference.
