### ISSUE TITLE
GDALWarpOperation in some cases inadequately selects working data type

### ISSUE THREAD

**Issue by vagran** [OSGeo/gdal#4469]
Having dataset with Float32 sample data type, and having "no data value" set to some integer, causes Float64 type be used as working data type for warp operation, thus using two times more memory than really needed for that.

The case is very typical for DEM TIFF files, having heights represented in Float32 samples and no data value something like "-10000".

Here the working type is determined:
https://github.com/OSGeo/gdal/blob/3302b5c9cb62191df3409676aa97fced07c92c3b/gdal/alg/gdalwarpoperation.cpp#L549
Here it is first set to Float32 as in source dataset:
https://github.com/OSGeo/gdal/blob/3302b5c9cb62191df3409676aa97fced07c92c3b/gdal/alg/gdalwarper.cpp#L1512
Then type is united with source dataset no data value (which almost always happens to be integer for typical DEM):
https://github.com/OSGeo/gdal/blob/3302b5c9cb62191df3409676aa97fced07c92c3b/gdal/alg/gdalwarper.cpp#L1520
So here it determined to be Int32:
https://github.com/OSGeo/gdal/blob/368c58c0a7580539a7d25070a473bac4ca59dd9c/gdal/gcore/gdal_misc.cpp#L178
which is united with Float32 in next line, calling GDALDataTypeUnion() which returns Float64, because of this line:
https://github.com/OSGeo/gdal/blob/368c58c0a7580539a7d25070a473bac4ca59dd9c/gdal/gcore/gdal_misc.cpp#L71

So the final type is Float64 with no mean for that if looking onto initial conditions - Float32 sample data type and no data value which happens to be small integer. The issue causes decreased capacity for GDAL-based products when working with most typical DEM files.

**Comment by rouault** [comment]
I can't confirm that with "gdalwarp float32.tif -srcnodata -10000 out.tif -overwrite". The working data type is Float32. Could you give an exact (minimum) reproducer of your issue ?

**Comment by rouault** [comment]
Nevermind, I can reproduce with -99999
