### ISSUE TITLE
WCS performing wrong request when dealing with two equal-length negative numbers

### ISSUE THREAD

**Issue by albertoparadisllop** [OSGeo/gdal#4483]
#### Expected behavior

When performing a WCS Request on an EPSG:4326 coverage, when the minimum requested extent and the coverage's minimum extent are both negative and have the same number of characters, for example, `-5` and `-9`, the maximum of the two will be used when performing the request: `-5`

#### Actual behavior

When performing the request mentioned earlier, the minimum of the two is used instead. For `-5` and `-9`, `-9` is used.
Any attempt to request a coverage with extents as describer earlier results in the following error:
```
ERROR 1: Returned tile does not match expected configuration.
Got 6266x288 instead of 288x288.
```
## Steps to reproduce the problem.

`gdal_translate -projwin -0.15, 39.5, 0.15, 39.2 -oo NoGridAxisSwap "WCS:https://<server_url>?version=2.0.1&coverage=<coverage_name>" out.tiff`

Where coverage `<coverage_name>` in `<server_url>` has a minimum longitude of X, where `-10 < X < -0.15`

## Operating system

Ubuntu 20.04.1 LTS 64 bit

## GDAL version

GDAL 3.1.4

**Comment by pixeledbrain** [comment]
I suspect it might have to do with function  [`CompareNumbers` in wcsutils](https://github.com/OSGeo/gdal/blob/master/gdal/frmts/wcs/wcsutils.cpp#L47-L88), as it seems to do a string comparison of both inputs to determine the result, so for `-1` and `-5`, for example, string-wise, `-5` will be bigger.

**Comment by rouault** [comment]
CC @ajolma

**Comment by ajolma** [comment]
Can you give me a working server url and coverage name?

**Comment by albertoparadisllop** [comment]
> Can you give me a working server url and coverage name?

I can't give you the one I used, as it's a company server, however, I found this public one in which I was able to recreate the issue:

WCS Server: `https://servicios.idee.es/wcs-inspire/mdt?version=2.0.1&service=WCS`
Coverage: `Elevacion4326_1000`

To recreate the issue, the requested projwin must have a minimum longitude of the same *number of digits* as the extent's minimum longitude. I recreated it requesting the following projwin: `[-10.28, 39.58, -9.226, 38.84]`

**Comment by ajolma** [comment]
I really don't understand/remember why the CompareNumbers is implemented in such a complex way. If I replace its contents with 
    double ad = std::stod(a);
    double bd = std::stod(b);
    if (ad < bd) {
        return -1;
    } else if (ad > bd) {
        return 1;
    } else {
        return 0;
    }
The error disappears. I seem to be unable to run the autotest locally so I'll make a PR and see if those are ok.
