### ISSUE TITLE
autotest: Use pytest.mark.require_driver where appropriate

### ISSUE THREAD

**Issue by DFEvans** [OSGeo/gdal#4487]
The autotest runner has in-built support for skipping tests that require a certain driver that is unavailable, but many older tests contain their own checks of driver availability (presumably as they pre-date the centralised driver check). The newer driver check is more compact, better decouples the tests from how the driver check is actually implemented, and can be applied to a whole module with only a single line of code. Updating the codebase also makes it more likely that new contributors will learn the newer method of checking tests.

An individual test can be skipped with this decorator:
```
@pytest.mark.require_driver('GTiff')
def test_warp_19(tmpdir, size, datatype, resampling_string):
```

A module can be skipped by defining `pytestmark` at module level:
```
import pytest

pytestmark = pytest.mark.require_driver('DAAS')
```

The older code to replace is usually of the form:
```
    gdaltest.tiff_drv = gdal.GetDriverByName('GTiff')
    if gdaltest.tiff_drv is None:
        pytest.skip()
```

**Comment by DFEvans** [comment]
I note that driver checks are quite patchy, e.g. `autotest/alg/warp.py` only seems to check the GTiff driver in about half of tests, despite most(/all?) requiring it. Is that because GTiff is guaranteed to exist and so a check isn't needed, or just that it's so common that no one has ever noticed/cared about the lack of a check?

**Comment by rouault** [comment]
> Is that because GTiff is guaranteed to exist and so a check isn't needed, or just that it's so common that no one has ever noticed/cared about the lack of a check?

I'd expect a huge number of tests in other files to fail if GTiff isn't available. You can't build GDAL without GTiff support (unless you change the code & build-system). You might exclude it at runtime though with GDAL_SKIP, but IMHO that isn't really a use case we need to test. For such a built-in core driver, I'd say we'd probably be better just removing checks for its presence

**Comment by DFEvans** [comment]
> You can't build GDAL without GTiff support (unless you change the code & build-system)

Right, that's what I was getting at.
