### ISSUE TITLE
Possible bug in GetOutputDriversFor (Python API)

### ISSUE THREAD

**Issue by dmikushin** [OSGeo/gdal#4498]
On [this line](https://github.com/OSGeo/gdal/blob/master/gdal/swig/python/gdal-utils/osgeo_utils/auxiliary/util.py#L72) the ANDed conditions are mutually exclusive, and can never be fit. The `not drv_list` part means the list of drivers is empty, however it is ANDed with conditions assuming it is NOT empty:

```
if ext.lower() == 'nc' and not drv_list and \
                drv_list[0].upper() == 'GMT' and drv_list[1].upper() == 'NETCDF':
```

The fix should be `s/not drv_list/drv_list/`

**Comment by rouault** [comment]
CC @idanmiara
