### ISSUE TITLE
[filegdb] The layer name or field name does not support Chinese

### ISSUE THREAD

**Issue by spenggch** [OSGeo/gdal#4511]
The layer name or field name does not support Chinese ！！！

The error code is at line 465 of [ogr/ogrsf_frmts/filegdb/FGdbUtils.cpp] 

If this method [FGDBLaunderName] does not do any processing, the layer name or field name can support Chinese

**Comment by rouault** [comment]
Duplicate of https://github.com/OSGeo/gdal/issues/4112
