### ISSUE TITLE
[DWG] Dwg Driver does not support polygons reading

### ISSUE THREAD

**Issue by lchevallier69** [OSGeo/gdal#4535]
## Expected behavior and actual behavior.

When i read a DWG with DWGDriver (GDAL Compiled with ODA), AcDbFace and AcDbRegion are ignored, in fact, a lot of DWG files contain those type of object. In the reader there are nothing to read polygons present in the dwg. I would like to convert also AcDbRegion and AcDbFaces to Ogr Polygons

## Steps to reproduce the problem.

Create a DWG with faces or regions, the launch this command line ,

 `ogrinfo.exe C:\Users\fkouadjosse\Downloads\Luc\Modele_intraSITE.dwg entities --debug ON `
 
the output does not contains any polygon and the output explains that AcDbFace or AcDbRegion are ignored.

## Operating system

Windows 10 64 bit & Linux Ubuntu 16.04 64 bit

## GDAL version and provenance

GDAL 3.2 on Ubuntu & 3.0.4 on Windows

![Clipboard - 22 septembre 2021 09_21](https://user-images.githubusercontent.com/91180972/134303826-e14ab3a7-e803-4ed4-b039-d262fff48db5.png)
1

**Comment by rouault** [comment]
Please attach a file that demonstrates the issue

**Comment by lchevallier69** [comment]
[sample_face_region_dwg.zip](https://github.com/OSGeo/gdal/files/7210482/sample_face_region_dwg.zip)
here a sample DWG with faces and region

**Comment by lchevallier69** [comment]
![image](https://user-images.githubusercontent.com/91180972/134340184-6543dfdc-91de-472a-b6e6-11ad29111760.png)
Green shapes are faces

**Comment by lchevallier69** [comment]
![image](https://user-images.githubusercontent.com/91180972/134340293-51cc03c9-20fa-40a2-b498-140379e38d31.png)
this rounded wall is a region

**Comment by lchevallier69** [comment]
both types are ignored by the DWG driver

**Comment by lchevallier69** [comment]
[sample_face_region_dwg.zip](https://github.com/OSGeo/gdal/files/7210593/sample_face_region_dwg.zip)

**Comment by lchevallier69** [comment]
right for AcDbRegion, lets read AcDbFace, i'll make a pull request for that
