### ISSUE TITLE
docker image possibly missing symlink for libproj

### ISSUE THREAD

**Issue by itcarroll** [OSGeo/gdal#4537]
## Expected behavior and actual behavior.

The docker image osgeo/gdal:ubuntu-full-3.3.2 contains libproj, but linking fails when I try to build the Python cartopy package (following the cartopy instructions). I think the problem is the image does not contain a symlink to /usr/lib/libproj.so.22 from /usr/lib/libproj.so. At least, creating that symlink allows cartopy installation, but I'm no software developer.

## Steps to reproduce the problem.

```
$ docker run --rm -it osgeo/gdal:ubuntu-full-3.3.2 bash
# ldconfig -p | grep libproj
	libproj.so.22 (libc6,x86-64) => /usr/local/lib/libproj.so.22
	libproj.so.15 (libc6,x86-64) => /lib/x86_64-linux-gnu/libproj.so.15
```

Compare to libgdal, which has the un-versioned symlink.

```
# ldconfig -p | grep libgdal
	libgdalalljni.so (libc6,x86-64) => /lib/libgdalalljni.so
	libgdal.so.3.3.2 (libc6,x86-64) => /lib/libgdal.so.3.3.2
	libgdal.so.3 (libc6,x86-64) => /lib/libgdal.so.3
	libgdal.so (libc6,x86-64) => /lib/libgdal.so
```

**Comment by rouault** [comment]
I'm a bit surprised by this. The PROJ build in /usr/local/build is only aimed at being used by GDAL itself. It contains renamed symbols that can't be used by other software, unless they specify special build options, like GDAL does.

Could you detail exactly which steps you followed to install cartopy ?

Anyway the Docker images as they are done aren't really well designed to build things on top of them, as they don't follow the practice of the package management of the Linux distribution they rely on.

**Comment by itcarroll** [comment]
> The PROJ build in /usr/local/build is only aimed at being used by GDAL itself. It contains renamed symbols that can't be used by other software, unless they specify special build options, like GDAL does.

Ah, nevermind then. I just realized that my "fix" only made installation appear to succeed. The package was broken (undefined symbols). Back to square one on building cartopy without conda ...

**Comment by rouault** [comment]
you may rather need to install the libproj-dev package
