### ISSUE TITLE
gdal failed to run test on windows

### ISSUE THREAD

**Issue by spacelg** [OSGeo/gdal#4553]
Hi All,

Environment:
VS 2019 + Windows Server 2016

gdal failed to run test on windows with ModuleNotFoundError: No module named 'osgeo' on master branch. Could you please help look at this issue?

**Repro steps:**
1. git clone https://github.com/OSGeo/gdal F:\gitP\OSGeo\gdal
2. Using osgeo4w-setup-x86-v1.exe install proj.
3. modirfy F:\gitP\OSGeo\gdal\gdal\nmake.opt(PROJ_INCLUDE = -IF:\gitP\OSGeo\OSGeo4W\include and PROJ_LIBRARY = F:\gitP\OSGeo\OSGeo4W\lib\proj_i.lib)
4. Open a vs2019 x86 command prompt and cd F:\gitP\OSGeo\gdal\gdal
5. generate_vcxproj.bat 16.0 32 gdal_vs2019_x86
6. msbuild /m /p:Platform=Win32 /p:Configuration=Release gdal_vs2019_x86.vcxproj /t:Rebuild
7. cd F:\gitP\OSGeo\gdal\autotest\cpp
8. msbuild /m /p:Platform=Win32 /p:Configuration=Release gdal_vs2019_x86_test.vcxproj /t:Rebuild
9. cd F:\gitP\OSGeo\gdal\autotest
10. pip install -r ./requirements.txt
11. pytest

**Error info:**
F:\gitP\OSGeo\gdal\autotest>pytest
ImportError while loading conftest 'F:\gitP\OSGeo\gdal\autotest\conftest.py'.
conftest.py:9: in <module>
    from osgeo import gdal
E   ModuleNotFoundError: No module named 'osgeo'

**Comment by rouault** [comment]
you also need to explicitly build the Python bindings. Look at https://github.com/OSGeo/gdal/blob/b3d3d0bf586706e89e65f1ed622933ec168ffb21/.github/workflows/windows_build.yml#L226 to L230 for how to do it
