### ISSUE TITLE
XLSX driver doesn't read correctly datetime from LibreOffice  

### ISSUE THREAD

**Issue by bucibucii** [OSGeo/gdal#4571]
## Expected behavior and actual behavior.
expected 2021-03-08 00:00:00 actual  2021-03-03 08:00:00.000

Latest version

**Comment by rouault** [comment]
Please attach a file reproducing the issue. I've tried to create a .ods file ([testdatetime.ods](https://github.com/OSGeo/gdal/files/7262476/testdatetime.ods) )  with the date you provide and OGR reports the correct date

**Comment by bucibucii** [comment]
[Test.xlsx](https://github.com/OSGeo/gdal/files/7285375/Test.xlsx)

**Comment by rouault** [comment]
Closing due to lack of feedback
