### ISSUE TITLE
Gdalwarp reprojection from Lat/Lon to meters (EPSG) pixel size problem 

### ISSUE THREAD

**Issue by sebbarbadreddine** [OSGeo/gdal#4572]
print ("\nSpecific var in netcdf to image")
		# variable .tif extracted from .nc
		image_var_ll = op.join(out, var + "_ll.tif")
		cmd_nc_tif = "gdal_translate -ot Float64 -unscale NETCDF:\"" + nc_file + "\":" + var + " " + image_var_ll
		subprocess.call(cmd_nc_tif, shell=True)
		
		print ("\nWGS84 from 0>360 to -180>180")
		# reprojection from 0>360 to -180>180
		image_var_ll180 = op.join(out, var + "_ll_180.tif")
		cmd_360_180 = "gdalwarp -s_srs \"+proj=longlat +ellps=WGS84\" -t_srs WGS84 "
		cmd_360_180 += image_var_ll + " " + image_var_ll180
		cmd_360_180 += " -wo SOURCE_EXTRA=1000 --config CENTER_LONG 0 "
		subprocess.call(cmd_360_180, shell=True)

		print ("\nlatlon to meters")
		# reprojection in epsg of landsat image
		cmd_latlon_meter = 'gdalwarp  -t_srs EPSG:32629 ' + " "
		cmd_latlon_meter += image_var_ll180 + " " + image_var_m
		#cmd_latlon_meter +=" -wo SOURCE_EXTRA=1000 --config CENTER_LONG 0 "
		subprocess.call(cmd_latlon_meter, shell=True)
# why does it change the resolution of the pixel during the last reprojection from ~10Km to ~5km ??

**Comment by jratike80** [comment]
Please use gdal-dev mailing list for asking questions.

What was the pixel size before projecting into EPSG:32629? Was the pixel size same in lat and lon directions? Notice the ranges from -90 to 90 vs. -180 to 180.

You can control the pixel size of gdalwarp exactly with the `-tr` parameter.

**Comment by sebbarbadreddine** [comment]
Thanks for your reply, 
Before the projection  into EPSG 32629the pixel size was about 10 km yet the xres and yres were slightly different. After the projection the resolution became about 5km almost square (xres and yres). When i force the -tr commande the pixels are forced to that resolution and the results do not seem good. Why it doesn't keep the same resolution automatically ? how can i fix that ?tell the gdalwarp to keep the resolution of the input image (  is there a command) ? 
Thanx again.

**Comment by rouault** [comment]
Please post the output of gdalinfo on the image used as input to the final gdalwarp

**Comment by sebbarbadreddine** [comment]
latlon to meters
Creating output file that is 3710P x 4416L.
Processing data_ERA5\reanalysis-era5-land\20200929_11\t2m_ll_180.tif [1/1] : 0Using internal nodata values (e.g. -32767) for image data_ERA5\reanalysis-era5-land\20200929_11\t2m_ll_180.tif.
Copying nodata values from source data_ERA5\reanalysis-era5-land\20200929_11\t2m_ll_180.tif to destination data_ERA5\reanalysis-era5-land\20200929_11\t2m_meter_32629.tif.
...10...20...30...40...50...60...70...80...90...100 - done.
Un sous-r�pertoire ou un fichier data_ERA5\reanalysis-era5-land\20200929_11 existe d�j�.
Driver: GTiff/GeoTIFF
Files: data_ERA5\reanalysis-era5-land\20200929_11\t2m_meter_32629.tif
Size is 3710, 4416
Coordinate System is:
PROJCRS["WGS 84 / UTM zone 29N",
    BASEGEOGCRS["WGS 84",
        DATUM["World Geodetic System 1984",
            ELLIPSOID["WGS 84",6378137,298.257223563,
                LENGTHUNIT["metre",1]]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433]],
        ID["EPSG",4326]],
    CONVERSION["UTM zone 29N",
        METHOD["Transverse Mercator",
            ID["EPSG",9807]],
        PARAMETER["Latitude of natural origin",0,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",-9,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["Scale factor at natural origin",0.9996,
            SCALEUNIT["unity",1],
            ID["EPSG",8805]],
        PARAMETER["False easting",500000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["(E)",east,
            ORDER[1],
            LENGTHUNIT["metre",1]],
        AXIS["(N)",north,
            ORDER[2],
            LENGTHUNIT["metre",1]],
    USAGE[
        SCOPE["unknown"],
        AREA["World - N hemisphere - 12°W to 6°W - by country"],
        BBOX[0,-12,84,-6]],
    ID["EPSG",32629]]
Data axis to CRS axis mapping: 1,2
Origin = (-16197650.923912977799773,19872147.372716657817364)
Pixel Size = (9000.000000000000000,-9000.000000000000000)
Metadata:
  AREA_OR_POINT=Area
  latitude#long_name=latitude
  latitude#units=degrees_north
  longitude#long_name=longitude
  longitude#units=degrees_east
  NC_GLOBAL#Conventions=CF-1.6
  NC_GLOBAL#history=2021-09-20 16:34:41 GMT by grib_to_netcdf-2.20.0: /opt/ecmwf/mars-client/bin/grib_to_netcdf -S param -o /cache/data9/adaptor.mars.internal-1632155680.7967076-2898-12-eeaef54f-03c1-41ef-986b-9d85aee90915.nc /cache/tmp/eeaef54f-03c1-41ef-986b-9d85aee90915-adaptor.mars.internal-1632155680.347018-2898-19-tmp.grib
  NETCDF_DIM_EXTRA={time}
  NETCDF_DIM_time_DEF={1,4}
  NETCDF_DIM_time_VALUES=1058435
  t2m#add_offset=264.350472219205
  t2m#long_name=2 metre temperature
  t2m#missing_value=-32767
  t2m#scale_factor=0.001631245183724231
  t2m#units=K
  t2m#_FillValue=-32767
  time#calendar=gregorian
  time#long_name=time
  time#units=hours since 1900-01-01 00:00:00.0
Image Structure Metadata:
  INTERLEAVE=BAND
Corner Coordinates:
Upper Left  (-16197650.924,19872147.373) (107d59'56.89"W,  0d 8'45.24"N)
Lower Left  (-16197650.924,-19871852.627) (107d59'56.86"W,  0d 8'46.49"S)
Upper Right (17192349.076,19872147.373) ( 90d 0'19.25"E,  0d 8'45.80"N)
Lower Right (17192349.076,-19871852.627) ( 90d 0'19.22"E,  0d 8'47.05"S)
Center      (  497349.076,     147.373) (  9d 1'25.76"W,  0d 0' 4.80"N)
Band 1 Block=3710x1 Type=Float64, ColorInterp=Gray
  NoData Value=-32767
  Metadata:
    add_offset=264.350472219205
    long_name=2 metre temperature
    missing_value=-32767
    NETCDF_DIM_time=1058435
    NETCDF_VARNAME=t2m
    scale_factor=0.001631245183724231
    units=K
    _FillValue=-32767

**Comment by sebbarbadreddine** [comment]
Sorry this was the final output

here is what you requested : 
Driver: GTiff/GeoTIFF
Files: data_ERA5\reanalysis-era5-land\20200929_11\t2m_ll_180.tif
Size is 8046, 4025
Coordinate System is:
GEOGCRS["WGS 84",
    DATUM["World Geodetic System 1984",
        ELLIPSOID["WGS 84",6378137,298.257223563,
            LENGTHUNIT["metre",1]]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["degree",0.0174532925199433]],
    CS[ellipsoidal,2],
        AXIS["geodetic latitude (Lat)",north,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433]],
        AXIS["geodetic longitude (Lon)",east,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433]],
    ID["EPSG",4326]]
Data axis to CRS axis mapping: 2,1
Origin = (-179.999954224481570,90.049999999999997)
Pixel Size = (0.044741232397103,-0.044741232397103)
Metadata:
  AREA_OR_POINT=Area
  latitude#long_name=latitude
  latitude#units=degrees_north
  longitude#long_name=longitude
  longitude#units=degrees_east
  NC_GLOBAL#Conventions=CF-1.6
  NC_GLOBAL#history=2021-09-20 16:34:41 GMT by grib_to_netcdf-2.20.0: /opt/ecmwf/mars-client/bin/grib_to_netcdf -S param -o /cache/data9/adaptor.mars.internal-1632155680.7967076-2898-12-eeaef54f-03c1-41ef-986b-9d85aee90915.nc /cache/tmp/eeaef54f-03c1-41ef-986b-9d85aee90915-adaptor.mars.internal-1632155680.347018-2898-19-tmp.grib
  NETCDF_DIM_EXTRA={time}
  NETCDF_DIM_time_DEF={1,4}
  NETCDF_DIM_time_VALUES=1058435
  t2m#add_offset=264.350472219205
  t2m#long_name=2 metre temperature
  t2m#missing_value=-32767
  t2m#scale_factor=0.001631245183724231
  t2m#units=K
  t2m#_FillValue=-32767
  time#calendar=gregorian
  time#long_name=time
  time#units=hours since 1900-01-01 00:00:00.0
Image Structure Metadata:
  INTERLEAVE=BAND
Corner Coordinates:
Upper Left  (-179.9999542,  90.0500000) (179d59'59.84"W, 90d 3' 0.00"N)
Lower Left  (-179.9999542, -90.0334604) (179d59'59.84"W, 90d 2' 0.46"S)
Upper Right ( 179.9880016,  90.0500000) (179d59'16.81"E, 90d 3' 0.00"N)
Lower Right ( 179.9880016, -90.0334604) (179d59'16.81"E, 90d 2' 0.46"S)
Center      (  -0.0059763,   0.0082698) (  0d 0'21.51"W,  0d 0'29.77"N)
Band 1 Block=8046x1 Type=Float64, ColorInterp=Gray
  NoData Value=-32767
  Metadata:
    add_offset=264.350472219205
    long_name=2 metre temperature
    missing_value=-32767
    NETCDF_DIM_time=1058435
    NETCDF_VARNAME=t2m
    scale_factor=0.001631245183724231
    units=K
    _FillValue=-32767

**Comment by sebbarbadreddine** [comment]
I do use -tr 9000 9000

**Comment by rouault** [comment]
ok so you're reprojection a whole world extent in EPSG:4326 to EPSG:32629 which is a Transverse Mercator projection. While the Transverse Mercator can technically be used to map any point of the world, in practice it is intended to be used within a few degrees of its central meridian. If you use it with the whole world extent, you'll necessarily get weird results far from the central meridian. You should likely add a -te xmin ymin xmax ymax argument to restrict the extent of the output target.
From the elements you give, I don't see any defect, hence closing. Further questions would be best directed at locations indicated in https://gdal.org/community/index.html or other community support channels

**Comment by jratike80** [comment]
If the source CRS is EPSG:4326, pixel size is (0.044741232397103,-0.044741232397103) in degrees, and target CRS is some projected system then your question "Why it doesn't keep the same resolution automatically?" is not relevant. The length of one degree is not uniform but it is changing from the equator towards the poles. You can play with some calculator, for example http://www.csgnetwork.com/degreelenllavcalc.html.

**Comment by sebbarbadreddine** [comment]
> ok so you're reprojection a whole world extent in EPSG:4326 to EPSG:32629 which is a Transverse Mercator projection. While the Transverse Mercator can technically be used to map any point of the world, in practice it is intended to be used within a few degrees of its central meridian. If you use it with the whole world extent, you'll necessarily get weird results far from the central meridian. You should likely add a -te xmin ymin xmax ymax argument to restrict the extent of the output target. From the elements you give, I don't see any defect, hence closing. Further questions would be best directed at locations indicated in https://gdal.org/community/index.html or other community support channels

Actually, altough I restrict the extent, the prolem consists, and the solution ( that i want to share altough the issue is closed ) is by deleting the command " -wo SOURCE_EXTRA=1000 --config CENTER_LONG 0 ". 

THa,ks a lot, 
have a good day.
