### ISSUE TITLE
gdal.TermProgress failing using gdal_fillnodata.py 

### ISSUE THREAD

**Issue by mattijn** [OSGeo/gdal#458]
The following command for `gdal_fillnodata.py` (with the GDAL installation from https://www.lfd.uci.edu/~gohlke/pythonlibs/#gdal)

`gdal_fillnodata.py -of GTiff C:/tmp/grid_withnodata.asc C:/tmp/grid_filled.tif`

Returns the following error:

```
Traceback (most recent call last):
  File "C:\Python35\Lib\site-packages\osgeo\scripts\gdal_fillnodata.py", line 19
7, in <module>
    callback = prog_func )
  File "C:\Python35\lib\site-packages\osgeo\gdal.py", line 2750, in FillNodata
    return _gdal.FillNodata(*args, **kwargs)
RuntimeError: Object given is not a Python function

```

The pointer comparison for the `gdal.TermProgress` Python/SWIG function and the `GDALTermProgress` C function seems to fail at: 
https://github.com/OSGeo/gdal/blob/release/2.2/gdal/swig/include/python/typemaps_python.i#L1320. 

```
if ($input && $input != Py_None ) {
    void* cbfunction = NULL;
    CPL_IGNORE_RET_VAL(SWIG_ConvertPtr( $input,
                     (void**)&cbfunction,
                     SWIGTYPE_p_f_double_p_q_const__char_p_void__int,
                     SWIG_POINTER_EXCEPTION | 0 ));

    if ( cbfunction == GDALTermProgress ) {
        $1 = GDALTermProgress;
    } else {
        if (!PyCallable_Check($input)) {
            PyErr_SetString( PyExc_RuntimeError,
                             "Object given is not a Python function" );
            SWIG_fail;
        }
        psProgressInfo->psPyCallback = $input;
        $1 = PyProgressProxy;
    }

}
```

Maybe a SWIG 3.0.12 bug? File of the command can be obtained from here: [grid_withnodata.zip](https://github.com/OSGeo/gdal/files/1930997/grid_withnodata.zip)

Christoph Gohlke noticed a workaround, run `gdal_fillnodata.py` in quiet mode (`-q`) to avoid the callback.

**Comment by cgohlke** [comment]
Thank you, https://github.com/OSGeo/gdal/commit/1121758f74589f8850193a5baced7ab1335a4b39 fixed the issue.
