### ISSUE TITLE
Gdalinfo doesn't recognice netcdf file with time coordinates

### ISSUE THREAD

**Issue by axelschweiger** [OSGeo/gdal#4592]
## Expected behavior and actual behavior.
Two nearly identical netcdf files with times series raster data. One has a coordinate assigned to the time axis, the other doesn't. gdalinfo provides correct information about the one without time axis coordinate. The one with time axis coordinate gdalinfo doesn't recognize as a netcdf file. Both files are created using python xarray. The only differences is that a time coordinate is assigned. I have tried different formats of the time axis coordinate even copied one from a file that opens fine,   (cftime, datetime) even copied one from a file that seems to have not problem. I have also tried different netcdf engines for xarray. Other netcdf tools seem to have no problem with the files.  Coordinate is assigned using h.assign_coords({"time":timeaxis}) ; where h is an xarray object and timeaxis a datetime object. Gdaltranslate opens the file but Qgis cannot open the file apparently having the same problem. 

gdalinfo with_time_coord_nf_small.nc
gdalinfo failed - unable to open 'with_time_coord_nf_small.nc'

Output snippet of one without time coordinate 
gdalinfo notime_coord_nf_small.nc | more
Warning 1: Recode from UTF-8 to CP_ACP failed with the error: "Invalid argument".
ERROR 1: buildCS: missing UNIT
Warning 1: No 1D variable is indexed by dimension time
Driver: netCDF/Network Common Data Format
Files: notime_coord_nf_small.nc
Size is 500, 400
Coordinate System is:
PROJCRS["unnamed",
    BASEGEOGCRS["unknown",
        DATUM["unnamed",
            ELLIPSOID["Spheroid",6370000,0,
                LENGTHUNIT["metre",1,
                    ID["EPSG",9001]]]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433,
                ID["EPSG",9122]]]],
.
Not sure where the "Missing Unit" message comes from but that doesn't seem to affect anything. 

## Steps to reproduce the problem.
see above. 
## Operating system
Windows 10

## GDAL version and provenance
gdal 3.3.1 Works ok on Ubuntu 18.4 earlier Gdal version 2.2.3. 

[data.zip](https://github.com/OSGeo/gdal/files/7280364/data.zip)

**Comment by rouault** [comment]
I don't reproduce the issue with GDAL 3.3 head branch on Ubuntu 20.04. I believe the issue you have is that the with_time_coord_nf_small.nc file uses a int64 variable for the time axis. It might be that your netCDF build lacks netCDF 4 support or, perhaps just that your GDAL build lacks it because of a missing ``NETCDF_HAS_NC4 = yes`` in nmake.opt/nmake.local

The ``ERROR 1: buildCS: missing UNIT`` message is due to the spatial_ref attribute holding a technically invalid WKT1 string. It should contain a ``,UNIT["meter",1]`` node. However that's not blocking.

**Comment by axelschweiger** [comment]
Even
Thanks much. I was working with the gdal distro that comes with the Qgis OSGeo4 package. Turns out that NETCDF_HAS_NC4 wasn’t the problem. After fixing the “missing UNIT” issue by completing the WKT string the problem with the time axis went away.

Now I have another problem. When loading in Qgis 3.20/3.16 on Windows the y axis is flipped while it is correct on Ubuntu Qgis 3.16. Gdalinfo provides the same corner coordinates in either case. I suppose this is a different issue and probably Qgis related, just in chance this rings a bell.

Axel
