### ISSUE TITLE
Conda MacOS builds failure

### ISSUE THREAD

**Issue by rouault** [OSGeo/gdal#4599]
Conda MacOS builds fail since today with apparently the following cause:
```
    raise RuntimeError("Setuptools downloading is disabled in conda build. "
RuntimeError: Setuptools downloading is disabled in conda build. Be sure to add all dependencies in the meta.yaml  url=https://pypi.org/simple/GDAL/
```
See https://github.com/OSGeo/gdal/pull/4596/checks?check_run_id=3806165549

**Comment by rouault** [comment]
CC @ocefpaf (let me know if I should ping someone else)

**Comment by ocefpaf** [comment]
I cannot see anything obviously wrong. Pip doesn't guve us enough info to debug. Let me try this locally and I'll get back to you.

**Comment by rouault** [comment]
The initial error solved "by itself", but additional fixes on GDAL side were needed. Fixed per https://github.com/OSGeo/gdal/pull/4860
