### ISSUE TITLE
AIXM ElevatedCurve not detected

### ISSUE THREAD

**Issue by antoniolocandro** [OSGeo/gdal#4600]
It seems that elevated curve is not detected from the attached file, I think previously something similar was added to be able to see ElevatedPoint since I can view those

								<aixm:ElevatedCurve srsDimension="2" srsName="urn:ogc:def:crs:EPSG::4326" gml:id="olvsp_1">
									<gml:segments>
										<gml:GeodesicString>
											<gml:posList>61.5862899140001 5.02869262600007 61.586227266 5.02864029300002 61.5861767230001 5.02865488100002 61.586086349 5.02868456800007 61.586021122 5.02871348500003 61.585952096 5.02874779200005 61.58588538 5.02879349800003 61.585817686 5.02884574200004 61.5857489620001 5.02889660900007 61.5857047700001 5.02892867600002 61.5856576040001 5.02895735300007 61.5856083460001 5.02899139100003 61.585520096 5.02905701800006 61.5854687250001 5.02909566400007 61.585412578 5.02913699700002 61.5853562390001 5.02918099400006 61.5853349750001 5.02920088300004 61.5853596260001 5.02935917900004 61.585374232 5.02945029600005 61.585385408 5.02951620000005</gml:posList>
										</gml:GeodesicString>
									</gml:segments>
									<aixm:elevation>11.47</aixm:elevation>
								</aixm:ElevatedCurve>

## Expected behavior and actual behavior.

I would expect upon adding the file it detects it contains points and lines, this already works for other AIXM features. 

## Steps to reproduce the problem.

Load the attached file in QGIS or I guess you can try OGRinfo (sorry if I am mistaken about the CLI tool)

![image](https://user-images.githubusercontent.com/4627073/136119912-5bc80675-28eb-45fb-8622-e8f897333d68.png)

You can see the points are detected but not the lines

Adding this will make open source tools more accessible to the aviation domain to be able to visualize these type of data without needing to do more complex data handling, it is understood that it is not a full fledge parser but I am trying to make it accessible to anyone who wants to visualize this data.

Appreciate the efforts

## Operating system

Windows 11

## GDAL version and provenance

3.3.1

**Comment by vlapra** [comment]
I encountered a similar issue and found that unfortunately, nothing has been done about it in the past three years. Could it be possible to add processing for ElevatedCurve as well? This would greatly improve the usability of this great library.
The modification should not be complex:
If GeodesicString is used, changing ElevatedCurve to Curve is sufficient, and the parsing will work correctly.

The attached dataset also contains ElevatedCurve with Geodesic with more than two points, but it might be a data error.

I’ve attached the entire dataset and a short sample.
[wrong.zip](https://github.com/user-attachments/files/17992689/wrong.zip)
[Donlon.zip](https://github.com/user-attachments/files/17992690/Donlon.zip)

**Comment by jratike80** [comment]
Perhaps useful information here https://ext.eurocontrol.int/aixm_confluence/display/AIXM52CP/%5BAIXM-589%5D+Elevated+geometry+objects+modified+derivation+chain

You wrote "This would greatly improve the usability.." Do you mean that it is common to have ElevatedCurves in AIX data?

**Comment by antoniolocandro** [comment]
@jratike80 unfortunately AIXM is not "strict" on what you can encode but adding this will make it easier to get products like QGIS for example to read the most common flavors of it. When the points were added it made a huge difference and allowed me to push opensource to be used in aeronautical charting.

**Comment by antoniolocandro** [comment]
I still get the same results as earlier

![image](https://github.com/user-attachments/assets/4f3d6b84-67ed-44f5-a7c3-7af2bf68ff38)

I think the issue is related that the ElevatedCurve is within the VerticalStructure. So I should see on the layer tree two or three times the VerticalStructure (or any other AIXM tag).
1. Point
2. Lines
3. Polygons

Currently it loads only the points for VerticalStructure.

I don't know if what I wrote make sense

**Comment by jratike80** [comment]
> I still get the same results as earlier

I think that nothing has changed in the code, so no surprise.
