### ISSUE TITLE
/vsitar/ Path too long causing not found image

### ISSUE THREAD

**Issue by mdhsl** [OSGeo/gdal#4625]
There is an issue when you use /vsitar/ and the name is too long. Indeed, after several tests, if the path in the tar exceeds 100 characters, the file will not be found.

example:

```sh
$ gdalinfo /vsitar/test.tar/aaaaaaaaaaa/VOL_SPOT7_001_A/IMG_SPOT7_PMS_001_A/IMG_SPOT7_PMS_201501310941329_PRJ_2138263101_R1C1.TIF 
ERROR 4: `/vsitar/test.tar/aaaaaaaaaaaaa/VOL_SPOT7_001_A/IMG_SPOT7_PMS_001_A/IMG_SPOT7_PMS_201501310941329_PRJ_2138263101_R1C1.TIF' does not exist in the file system, and is not recognized as a supported dataset name.
gdalinfo failed - unable to open '/vsitar/test.tar/aaaaaaaaaaa/VOL_SPOT7_001_A/IMG_SPOT7_PMS_001_A/IMG_SPOT7_PMS_201501310941329_PRJ_2138263101_R1C1.TIF'.
```

The path is 101 characters long.

If I rename the path `aaaaaaaaaaa` by `aaaaaaaaaa` (1 character less),
the gdalinfo will succeed:

```sh
$ gdalinfo  /vsitar/test.tar/aaaaaaaaaa/VOL_SPOT7_001_A/IMG_SPOT7_PMS_001_A/IMG_SPOT7_PMS_201501310941329_PRJ_2138263101_R1C1.TIF 
Driver: GTiff/GeoTIFF
Files: /vsitar/test.tar/aaaaaaaaaa/VOL_SPOT7_001_A/IMG_SPOT7_PMS_001_A/IMG_SPOT7_PMS_201501310941329_PRJ_2138263101_R1C1.TIF
       /vsitar/test.tar/aaaaaaaaaa/VOL_SPOT7_001_A/IMG_SPOT7_PMS_001_A/DIM_SPOT7_PMS_201501310941329_PRJ_2138263101.XML
       /vsitar/test.tar/aaaaaaaaaa/VOL_SPOT7_001_A/IMG_SPOT7_PMS_001_A/RPC_SPOT7_PMS_201501310941329_PRJ_2138263101.XML
Size is 7098, 4754
Coordinate System is:
PROJCRS["WGS 84 / UTM zone 33N",
    BASEGEOGCRS["WGS 84",
        DATUM["World Geodetic System 1984",
[...]
```

## Expected behavior and actual behavior.

Read image content for various needs: gdalinfo, translate etc.
Cannot find the image because the name is too long

## Steps to reproduce the problem.

create a tar and a subdirectory having more than 100 characters long and try to read image metadata using /vsitar/ and gdalinfo

## Operating system

Linux 64 bits

## GDAL version and provenance

3.3.2 release

**Comment by jratike80** [comment]
Can you suggest how long paths should be supported?
