### ISSUE TITLE
Pre-signed Cloudfront URLs behave like Pre-signed S3 URLs

### ISSUE THREAD

**Issue by bbuechler** [OSGeo/gdal#4641]
I suspect that recent problems accessing NASA earth science data is related to a shift in CloudFront behavior in the Earthdata Cloud Distribution environment. We recently went from having pre-signed CloudFront URL's valid for BOTH `GET` and `HEAD`, to URL's **ONLY** valid for `GET` or `HEAD`.

This puts CloudFront downloads urls in-line with observable behavior for S3 URL's. Since the pre-signed Cloudfront URLs still contain that `X-Amz-Signature` parameter, simply adding `.cloudfront.net/` and `.cloudfront.net:` to this clause should help resolve the data access issues. I think. Maybe. 🤞 

https://github.com/OSGeo/gdal/blob/793101437b6209e460d0980ce1d689a3a42e36e3/gdal/port/cpl_vsil_curl.cpp#L736-L737

**Comment by bbuechler** [comment]
I don't know if this is the proper channel. Feel free to close this Issue if it is not.

**Comment by jhkennedy** [comment]
> recent problems accessing NASA earth science data

For reference, these problems have been discussed in:
* the gdal-dev mailing list 
  * https://lists.osgeo.org/pipermail/gdal-dev/2021-September/054727.html
  * https://lists.osgeo.org/pipermail/gdal-dev/2021-October/054751.html
  * https://lists.osgeo.org/pipermail/gdal-dev/2021-October/054816.html
* the ISCE2 forum, which is using GDAL on the backend
  * https://github.com/isce-framework/isce2/discussions/349
