### ISSUE TITLE
MarkSuppressOnClose() does not prevent FlushCache() on close

### ISSUE THREAD

**Issue by chacha21** [OSGeo/gdal#4652]
GDAL 3.3.2

ENVI dataset

I observed that even when a dataset is marked with MarkSuppressOnClose(), FlushCache() will still be called internally at closing.

The problem for me is that I was expecting to drop the dataset quickly (to start a new one), without having to wait for a long sync with disk, since the files will be deleted anyway.

So:
-is this expected behaviour ?
-is there a way to close a dataset and drop everything that was not flushed yet to quickly get rid of the dataset ?

**Comment by rouault** [comment]
Turned out to be more complex than the 5-minute fix I expected... I'd appreciate if you could confirm that https://github.com/OSGeo/gdal/pull/4653 fixes the issue

**Comment by chacha21** [comment]
I checked #4653 and I think the fix is not complete.
in `GDALRasterBand::FlushCache()`, there is indeed a call to `poBandBlockCache->DisableDirtyBlockWriting();`, but that does not prevent `GDALArrayBandBlockCache::FlushCache()` to run and call `GDALArrayBandBlockCache::FlushBlock(...)` with `bWriteDirtyBlock `set to 1.
It seems that `m_bWriteDirtyBlocks` is ignored

**Comment by chacha21** [comment]
I checked again, and this time it does the job. Dropping a dataset is now very fast.

**Comment by micking** [comment]
the DWG plugin does not build anymore caused by the modified signature of FlushCache

**Comment by rouault** [comment]
> the DWG plugin does not build anymore caused by the modified signature of FlushCache

thanks for notifying (by the way it is better to open new tickets, since a notification on a closed ticket can easily be missed). I've pushed a fix
