### ISSUE TITLE
GeoTIFF: COGifying .msk sidecars substantially increases their size

### ISSUE THREAD

**Issue by mojodna** [OSGeo/gdal#468]
Starting with https://map.openaerialmap.org/#/25.28981541199998,53.89605287200003,14/latest/5ad7a75e91b5310010e0d54f?_k=aaveo9 (direct links: https://oin-hotosm.s3.amazonaws.com/5ad7a59991b5310010e0d54b/1/5ad7a59991b5310010e0d54d.tif, https://oin-hotosm.s3.amazonaws.com/5ad7a59991b5310010e0d54b/1/5ad7a59991b5310010e0d54d.tif.msk) (which is already a COG, but that's irrelevant), creating a new COG (including a `.msk` sidecar, which needs to be transcoded separately) results in a mask that is substantially larger than the non-COG mask.

Adding overviews to the mask seems necessary in order to apply the mask when using GeoTIFF overviews. However, adding overviews breaks the COG structure and requires the mask to be explicitly converted to a COG. Somehow this final `gdal_translate` substantially increases the size of the mask, presumably by dropping optimizations like `NBITS=1` (I couldn't figure out what's different or how to recreate the initial mask output; context here: https://github.com/hotosm/OpenAerialMap/issues/102#issuecomment-373594175)

## Processing Steps

```bash
# download source image
curl -sLO https://oin-hotosm.s3.amazonaws.com/5ad7a59991b5310010e0d54b/1/5ad7a59991b5310010e0d54d.tif
curl -sLO https://oin-hotosm.s3.amazonaws.com/5ad7a59991b5310010e0d54b/1/5ad7a59991b5310010e0d54d.tif.msk

# convert to target profile (produces test.tif.msk sidecar)
gdal_translate \
  -q \
  -b 1 -b 2 -b 3 \
  -mask mask \
  -co TILED=yes \
  -co BLOCKXSIZE=512 \
  -co BLOCKYSIZE=512 \
  -co NUM_THREADS=ALL_CPUS \
  -co COMPRESS=JPEG -co PHOTOMETRIC=YCbCr \
   5ad7a59991b5310010e0d54d.tif test.tif

# add overviews
gdaladdo \
  -r lanczos \
  --config GDAL_TIFF_OVR_BLOCKSIZE 512 \
  --config TILED_OVERVIEW yes \
  --config BLOCKXSIZE_OVERVIEW 512 \
  --config BLOCKYSIZE_OVERVIEW 512 \
  --config NUM_THREADS_OVERVIEW ALL_CPUS \
  --config COMPRESS_OVERVIEW JPEG --config PHOTOMETRIC_OVERVIEW YCbCr \
  test.tif \
  2 4 8 16 32 64 128

# convert to COG (skip the mask)
gdal_translate \
  -b 1 -b 2 -b 3 \
  -co TILED=yes \
  -co BLOCKXSIZE=512 \
  -co BLOCKYSIZE=512 \
  -co NUM_THREADS=ALL_CPUS \
  -co COMPRESS=JPEG -co PHOTOMETRIC=YCbCr \
  --config COMPRESS_OVERVIEW JPEG --config PHOTOMETRIC_OVERVIEW YCbCr \
  -co COPY_SRC_OVERVIEWS=YES \
  --config GDAL_TIFF_OVR_BLOCKSIZE 512 \
  test.tif cog.tif

# add overviews to the mask
gdaladdo \
  --config GDAL_TIFF_OVR_BLOCKSIZE 512 \
  --config TILED_OVERVIEW yes \
  --config COMPRESS_OVERVIEW DEFLATE \
  --config BLOCKXSIZE_OVERVIEW 512 \
  --config BLOCKYSIZE_OVERVIEW 512 \
  --config SPARSE_OK_OVERVIEW yes \
  --config NUM_THREADS_OVERVIEW ALL_CPUS \
  test.tif.msk \
  2 4 8 16 32 64 128

# convert the mask to a COG
gdal_translate \
  -of GTiff \
  -co TILED=yes \
  -co BLOCKXSIZE=512 \
  -co BLOCKYSIZE=512 \
  -co NUM_THREADS=ALL_CPUS \
  -co COPY_SRC_OVERVIEWS=YES \
  -co COMPRESS=DEFLATE \
  -co PREDICTOR=2 \
  --config GDAL_TIFF_OVR_BLOCKSIZE 512 \
  test.tif.msk cog.tif.msk
```

## Output

`gdal_translate` mask: http://mojodna-temp.s3.amazonaws.com/test.tif.msk - 1.7M 
http://mojodna-temp.s3.amazonaws.com/cog.tif.msk - 3.8M

## COG validation errors for `test.tif.msk`

```
The offset of the first block of overview of index 5 should be after the one of the overview of index 6
The offset of the first block of overview of index 4 should be after the one of the overview of index 5
The offset of the first block of overview of index 3 should be after the one of the overview of index 4
The offset of the first block of overview of index 2 should be after the one of the overview of index 3
The offset of the first block of overview of index 1 should be after the one of the overview of index 2
The offset of the first block of overview of index 0 should be after the one of the overview of index 1
The offset of the first block of the main resolution image should be after the one of the overview of index 6
```

## GDAL version and provenance

2.3.0beta1 using this Docker image: quay.io/mojodna/gdal:v2.3.0beta1 (`docker run -it --rm quay.io/mojodna/gdal:v2.3.0beta1`)

I originally noticed this w/ 2.2.x.

**Comment by rouault** [comment]
The increased size is due to -co PREDICTOR=2 which in that case is less efficient than no predictor.
And you also need to specify -co NBITS=1 since external masks are created with 8 BitsPerSample with the CreateMaskBand() interface

**Comment by rouault** [comment]
> QGIS sees test.tif.msk as having pixels w/ values of 0 and 255; cog.tif.msk with 0 and 1.

Yes, that's expected. More a visualization issue than a GDAL issue

**Comment by rouault** [comment]
> More a visualization issue than a GDAL issue

Hum actually for an internal TIFF mask (with nbits=1), GDAL does automatically the 0-1 to 0-255 conversion. Could be wise doing the same for an external mask

**Comment by mojodna** [comment]
> Hum actually for an internal TIFF mask (with nbits=1), GDAL does automatically the 0-1 to 0-255 conversion. Could be wise doing the same for an external mask

This sounds right to me and seems like it would allow QGIS (etc.) to do the right thing (since all it sees is a mask). It's potentially being treated as a transparency value otherwise?

Meanwhile, the solution to this issue appears to be to drop `PREDICTOR=2` and ignore `NBITS=1`; the resulting mask will be the same size as the original (non-COG) version but not quite as small as it could be.

**Comment by mojodna** [comment]
I can't remember my original rationale, but I think it had to do with resampling algorithms being applied to the mask when doing decimated reads, resulting in edges that weren't as crisp as they should have been.

**Comment by rouault** [comment]
OK looks like this issue can be closed. I let you file an enhancement issue for automatic promotion to 8-bits of external 1-bit masks if you wish.
