### ISSUE TITLE
Different behavior from using ImportFromEPSG and ImportFromProj4 method on SpatialReference object

### ISSUE THREAD

**Issue by kikitte** [OSGeo/gdal#4702]
## Expected behavior and actual behavior.

A CoordinateTransformation is created to transform a point from WGS84 to WGS 84 / UTM zone 48N(aka EPSG:32648), and it is ok when initializing the SpatialReference object with ImportFromProj4, but it shows an error message if the SpatialReference object is initialized by ImportFromEPSG. 

As you can see from the code below, we set the proj4 string from the SpatialReference object which is initialized using ImportFromEPSG, the transformation is ok, so I think the PROJ database is ok.

Expected behavior: Transform point successfully when initializing the SpatialReference object with ImportFromEPSG method.

## Steps to reproduce the problem.

```python
from osgeo import osr

src_srs = osr.SpatialReference()
src_srs.ImportFromEPSG(4326)
dst_srs = osr.SpatialReference()
dst_srs.ImportFromEPSG(32648)
trans = osr.CoordinateTransformation(src_srs, dst_srs)
trans.TransformPoint(105, 32)

# OUTPUT
# ERROR 1: PROJ: utm: Invalid latitude
# ERROR 1: Invalid coordinate
# (inf, inf, inf)

src_srs_new = osr.SpatialReference()
src_srs_new.ImportFromProj4(src_srs.ExportToProj4())
dst_srs_new = osr.SpatialReference()
dst_srs_new.ImportFromProj4(dst_srs.ExportToProj4())
trans_new = osr.CoordinateTransformation(src_srs_new, dst_srs_new)
trans_new.TransformPoint(105, 32)

# OUTPUT
# (499999.9999999976, 3540435.693282792, 0.0)
```

## Operating system

Arch Linux

## GDAL version and provenance

GDAL 3.3.1 from ArchLinux official  repository

**Comment by FriendsOfJustic** [comment]
> > ```python
> > trans.TransformPoint(105, 32)
> > ```
> 
> EPSG:4326 uses latitude, longitude ordering. See https://gdal.org/tutorials/osr_api_tut.html#crs-and-axis-order When importing from Proj4 strings, the axis order of the authority is lost, and hence the order is longitude, latitude

i have a wkt in a string type "_pipesectionRoute" which it srid is 4326 ,and i want to import a geom from wkt , then transform it to 3857
so the right way to trans is below?


```
 OGRSpatialReference* proj = new OGRSpatialReference;
      proj->importFromEPSG(4326);
      OGRRegisterAll();
      OGRGeometry* geom = nullptr;
      auto err = OGRGeometryFactory::createFromWkt(&(_pipesectionRoute[0]),
                                                   proj, &geom);
      cout << geom->getSpatialReference()->GetName() << endl;
      OGRSpatialReference* proj_tran = new OGRSpatialReference;
      proj_tran->importFromEPSG(3857);
      proj->SetAxisMappingStrategy(OAMS_TRADITIONAL_GIS_ORDER);
      OGRCoordinateTransformation* transform =
          OGRCreateCoordinateTransformation(proj, proj_tran);
      geom->transform(transform);
      geom->assignSpatialReference(proj_tran);
```
