### ISSUE TITLE
gdalwarp setting pixels outside target image bounds when using geolocation arrays

### ISSUE THREAD

**Issue by fredliporace** [OSGeo/gdal#4707]
## Expected behavior and actual behavior.

It seems that gdalwarp is setting pixel values outside the target image bounding when using geolocation arrays.

I've marked the source raster with bounding rectangles to check how these were being reprojected, upper left corner is for instance:

![image](https://user-images.githubusercontent.com/28077347/138900704-e2d56370-4ce0-43eb-874a-892158d54463.png)

The target raster correctly computes the corners but seems to replicate the source's border pixel value outside the target image boundary. Figure below shows the target top left corner, a similar behavior happens for all corners:

![image](https://user-images.githubusercontent.com/28077347/138901745-18a73468-95f7-4544-b085-674699507171.png)

## Steps to reproduce the problem.

Execute in [raw data](https://drive.google.com/file/d/1RU8vzhyNNFBPnWv3O3dUcFRWkEMfEtXe/view?usp=sharing) `issue` directory:

`gdalwarp -of GTiff -geoloc -s_srs EPSG:4326 -t_srs EPSG:3031 -dstnodata 0 -tr 3.5 3.5 -r near geoloc.vrt result.tif`

## Operating system

Tested against docker images `gdal:ubuntu-small-latest released 2021/10/07` and 
`gdal:ubuntu-small-3.3.2`.

## GDAL version and provenance

See above.

**Comment by fredliporace** [comment]
After some code level debugging I guess the problem is related to this [ticket](https://trac.osgeo.org/gdal/ticket/6959).

It seems that a new backmap implementation for geolocation arrays is being considered - in the past I used the algorithm described in section 3.1.5.3.6.4 of the [Landsat 7 Image Assessment System Geometric ATBD](https://www.usgs.gov/media/files/landsat-7-image-assessment-system-geometric-atbd). That algorithm could be simplified (I think) by assuming that there are no internal grid discontinuities - L7 raw scans did not match with its neighbors and there was also the possibility of a gap between scans.

I could contribute to the implementation, will send an e-mail to gdal-dev.

**Comment by vincentschut** [comment]
Note that, if we also want this to be useful for SAR data (projecting from slantrange to groundrange), we cannot assume that there are no internal grid discontinuities. Due to the intrinsic nature of SAR data and its interaction with terrain, there will be discontinuities whenever there is significant relief. Btw I think ISCE is using it like this currently. Perhaps the algorithmic simplification could be made optional?

**Comment by fredliporace** [comment]
I found that for this issue specifically some artifacts are due to the algorithm used to fill holes in the backmap, see image with the filling holes processing step removed:

![image](https://user-images.githubusercontent.com/28077347/139747659-9e4f6e4a-778d-4d92-b3ec-dc7ba31987d6.png)

**Comment by fredliporace** [comment]
@vincentschut I'm still playing with the current implementation so I'm not sure of its capabilities. I'd say that the discontinuity you mentioned is "well behaved" when compared to the case I mentioned (raw LS 7 ETM scans). The general case for geolocation arrays seems to be very hard.

**Comment by fredliporace** [comment]
Here is the output using #5520 

![image](https://user-images.githubusercontent.com/28077347/160481224-f6bd1321-a87f-4f04-a5e7-1e628df65bfc.png)

**Comment by fredliporace** [comment]
Solved in 3.5.0
