### ISSUE TITLE
gdal_translate problem converting GMT GRD file to GeoTiff

### ISSUE THREAD

**Issue by mkbarker** [OSGeo/gdal#4732]
Using gdal/3.3.2 gdal_translate to convert a GMT GRD file to GeoTiff, the UL/LL/UR/LR limits are not correctly preserved.

Example:

p4='+proj=stere +lat_0=-90 +lon_0=0 +lat_ts=-90 +k=1 +x_0=0 +y_0=0 +units=m +a=1737400 +b=1737400 +no_defs'
gdal_translate ldem_m208_m188_m208_m188_ldem_5mpp_surf.grd test.tif -of GTiff -a_srs "${p4}"
gdalinfo test.tif
Driver: GTiff/GeoTIFF
Files: test.tif
Size is 4000, 4000
Coordinate System is:
PROJCRS["unknown",
    BASEGEOGCRS["unknown",
        DATUM["unknown",
            ELLIPSOID["unknown",1737400,0,
                LENGTHUNIT["metre",1,
                    ID["EPSG",9001]]]],
        PRIMEM["Reference meridian",0,
            ANGLEUNIT["degree",0.0174532925199433,
                ID["EPSG",9122]]]],
    CONVERSION["Polar Stereographic (variant A)",
        METHOD["Polar Stereographic (variant A)",
            ID["EPSG",9810]],
        PARAMETER["Latitude of natural origin",-90,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",0,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["Scale factor at natural origin",1,
            SCALEUNIT["unity",1],
            ID["EPSG",8805]],
        PARAMETER["False easting",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["(E)",north,
            MERIDIAN[90,
                ANGLEUNIT["degree",0.0174532925199433,
                    ID["EPSG",9122]]],
            ORDER[1],
            LENGTHUNIT["metre",1]],
        AXIS["(N)",north,
            MERIDIAN[0,
                ANGLEUNIT["degree",0.0174532925199433,
                    ID["EPSG",9122]]],
            ORDER[2],
            LENGTHUNIT["metre",1]]]
Data axis to CRS axis mapping: 1,2
Metadata:
  AREA_OR_POINT=Area
  NC_GLOBAL#Conventions=COARDS, CF-1.5
  NC_GLOBAL#GMT_version=5.4.2 (r18461) [64-bit]
  NC_GLOBAL#history=grdmath ldem_m208_m188_m208_m188_ldem_5mpp_surf.grd 1e3 MUL = ldem_m208_m188_m208_m188_ldem_5mpp_surf.grd
  NC_GLOBAL#node_offset=1
  NC_GLOBAL#title=Produced by grdmath
  x#actual_range={-208000,-188000}
  x#long_name=x
  y#actual_range={-208000,-188000}
  y#long_name=y
  z#actual_range={-2838.252685546875,-840.9860229492188}
  z#long_name=z
  z#_FillValue=nan
Image Structure Metadata:
  INTERLEAVE=BAND
Corner Coordinates:
Upper Left  (    0.0,    0.0)
Lower Left  (    0.0, 4000.0)
Upper Right ( 4000.0,    0.0)
Lower Right ( 4000.0, 4000.0)
Center      ( 2000.0, 2000.0)
Band 1 Block=4000x1 Type=Float32, ColorInterp=Gray
  NoData Value=nan
  Metadata:
    actual_range={-2838.252685546875,-840.9860229492188}
    long_name=z
    NETCDF_VARNAME=z
    _FillValue=nan

The corner coordinates appear to have units of pixels rather than meters.

However, if I run the same commands with gdal/3.0.0, the UL/LL/UR/LR coordinates are correct:

gdalinfo test.tif
Driver: GTiff/GeoTIFF
Files: test.tif
Size is 4000, 4000
Coordinate System is:
PROJCRS["unknown",
    BASEGEOGCRS["unknown",
        DATUM["unknown",
            ELLIPSOID["unknown",1737400,0,
                LENGTHUNIT["metre",1,
                    ID["EPSG",9001]]]],
        PRIMEM["Reference meridian",0,
            ANGLEUNIT["degree",0.0174532925199433,
                ID["EPSG",9122]]]],
    CONVERSION["unnamed",
        METHOD["Polar Stereographic (variant B)",
            ID["EPSG",9829]],
        PARAMETER["Latitude of standard parallel",-90,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8832]],
        PARAMETER["Longitude of origin",0,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8833]],
        PARAMETER["False easting",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["easting",north,
            ORDER[1],
            LENGTHUNIT["metre",1]],
        AXIS["northing",north,
            ORDER[2],
            LENGTHUNIT["metre",1]]]
Data axis to CRS axis mapping: 1,2
Origin = (-208000.000000000000000,-188000.000000000000000)
Pixel Size = (5.000000000000000,-5.000000000000000)
Metadata:
  AREA_OR_POINT=Area
  NC_GLOBAL#Conventions=COARDS, CF-1.5
  NC_GLOBAL#GMT_version=5.4.2 (r18461) [64-bit]
  NC_GLOBAL#history=grdmath ldem_m208_m188_m208_m188_ldem_5mpp_surf.grd 1e3 MUL = ldem_m208_m188_m208_m188_ldem_5mpp_surf.grd
  NC_GLOBAL#node_offset=1
  NC_GLOBAL#title=Produced by grdmath
  x#actual_range={-208000,-188000}
  x#long_name=x
  y#actual_range={-208000,-188000}
  y#long_name=y
  z#actual_range={-2838.252685546875,-840.9860229492188}
  z#long_name=z
  z#_FillValue=nan
Image Structure Metadata:
  INTERLEAVE=BAND
Corner Coordinates:
Upper Left  ( -208000.000, -188000.000) (132d 6'31.43"W, 80d46'26.18"S)
Lower Left  ( -208000.000, -208000.000) (135d 0' 0.00"W, 80d19'20.70"S)
Upper Right ( -188000.000, -188000.000) (135d 0' 0.00"W, 81d14'56.94"S)
Lower Right ( -188000.000, -208000.000) (137d53'28.57"W, 80d46'26.18"S)
Center      ( -198000.000, -198000.000) (135d 0' 0.00"W, 80d47' 8.27"S)
Band 1 Block=4000x1 Type=Float32, ColorInterp=Gray
  NoData Value=nan
  Metadata:
    actual_range={-2838.252685546875,-840.9860229492188}
    long_name=z
    NETCDF_VARNAME=z
    _FillValue=nan

## Operating system
CentOS 7, 64bit

I'm sorry, but I'm having trouble attaching the GMT GRD file in a format that is supported by this form.

**Comment by PaulWessel** [comment]
FYI, GMT master now issues the axis attributes which handles this issue.
