### ISSUE TITLE
gdallocationinfo issue for ASCIIGrid file

### ISSUE THREAD

**Issue by alastairUK** [OSGeo/gdal#4747]
## Expected behavior and actual behavior.

I have an ASCIIGrid file with the following header

ncols 500
nrows 500
xllcorner    531000
yllcorner    178000
cellsize     2
NODATA_value -9999

If I do gdalinfo on the file

gdalinfo "tq3178_DSM_2M.asc"

I get 

Driver: AAIGrid/Arc/Info ASCII Grid
Files: tq3178_DSM_2M.asc
Size is 500, 500
Origin = (531000.000000000000000,179000.000000000000000)
Pixel Size = (2.000000000000000,-2.000000000000000)
Corner Coordinates:
Upper Left  (  531000.000,  179000.000)
Lower Left  (  531000.000,  178000.000)
Upper Right (  532000.000,  179000.000)
Lower Right (  532000.000,  178000.000)
Center      (  531500.000,  178500.000)
Band 1 Block=500x1 Type=Float32, ColorInterp=Undefined
  NoData Value=-9999

gdallocationinfo -geoloc "q3178_DSM_2M.asc" 531000 178000

Report:
  Location: (0P,500L)

Location is off this file! No further details to report.

I am not sure that's right as the file is referenced to the Lower Left so in fact the folllowing command should be the one that is "off the end"

gdallocationinfo -geoloc "tq3178_DSM_2M.asc" 531000 179000
Report:
  Location: (0P,0L)
  Band 1:
    Value: 3.99000000953674

I have checked the file with MapInfo Pro and I get the following

![image](https://user-images.githubusercontent.com/5337814/139700611-363f625f-465f-4279-b61a-2034e9c56aff.png)

![image](https://user-images.githubusercontent.com/5337814/139700712-908f2ed5-b4c8-4d8a-8ec8-e478b957d29e.png)

## GDAL version and provenance

gdalinfo --version
GDAL 3.3.3, released 2021/10/25

**Comment by jratike80** [comment]
The anchor point of the pixel is at the top-left corner so Upper Left ( 531000.000, 179000.000) is where you expect it to be. The corner coordinate of the upper right corner gives the coordinates of the upper right corner of the upper right pixel. That is at the anchor point of pixel number 500 (zero based). So the last pixel in the row is indeed touching the y-coordinate 179000 but that is still considered to be outside that pixel, and belong to the next one (that does not exist).

**Comment by rouault** [comment]
This is expected. You're just slightly off the raster due to GDAL using ultimately an upper-left corner convention to reference pixel coordinates.

``gdallocationinfo -geoloc "q3178_DSM_2M.asc" 531000 178000.01`` would work

**Comment by alastairUK** [comment]
Thanks for the very quick reply.

I follow what you say but I definitely consider the top row to be 531000 178998 as the next tile will have the values from 531000 179000 (as the data doesn't overlap)

If I do 

gdallocationinfo -geoloc "tq3178_DSM_2M.asc" 531000 178998
Report:
  Location: (0P,1L)
  Band 1:
    Value: 4.04300022125244

This is returning the second row whereas I'd expect the top as the data extends over 500 rows from 531000
178000

![image](https://user-images.githubusercontent.com/5337814/139714448-dff0bcd4-3021-4ef5-82e7-465d76b5b55f.png)

MapInfo Pro:
![image](https://user-images.githubusercontent.com/5337814/139714487-dd903ca4-f49c-4593-a96b-ba451bbda8ab.png)

Global Mapper:
![image](https://user-images.githubusercontent.com/5337814/139714549-b8fbfdde-033d-4eda-b4bc-49fdb6e489ae.png)

**Comment by rouault** [comment]
Given the georeferencing of the file, when you request a coordinate on exactly a pixel boundary, you're exposed to different rounding in different software. If you request instead the pixel center like 531001 178999, that would be much more fool proof

**Comment by jratike80** [comment]
This comes to fundamental question if pixel is point or if it presents an area. The default for GDAL is pixel-is-area. Here is a 3x3 pixel image http://latuviitta.org/documents/TFW_lunttilappu.png. The top left corner is at 100,100 and green area ends at 103,100. For the last pixel (102<= pixel x < 103) applies and if the next image starts from 103,100 there will be no overlap nor gap between the pixels.

**Comment by alastairUK** [comment]
> Given the georeferencing of the file, when you request a coordinate on exactly a pixel boundary, you're exposed to different rounding in different software. If you request instead the pixel center like 531001 178999, that would be much more fool proof

That I 100% understand. But in the case of 531000 178998 I am getting different results from gdallocationinfo than what I would expect (as it's returning the second row) and it seems other s/w agrees the result is 3.99 not 4.043. 

The pixel of the top row extends from 178998->179000 (well just below) . So if it's assuming closest point then surely it returns the top row value? 

The pixel-is-area I would assume is valid when using xllcenter, yllcenter but the ASCIIGrid format is possibly unclear on this.

For this dataset I guess I'd always assumed these are "post" values.

**Comment by jratike80** [comment]
By this document http://surferhelp.goldensoftware.com/subsys/subsys_ASC_Arc_Info_ASCII_Grid.htm xllcorner is at the lower left corner of the lower left pixel. GDAL puts anchor to upper left corner. So the top row **does** contain Y value 179000 but it does not contain value 178998, that belongs to the second row.

This may be worth reading https://trac.osgeo.org/gdal/wiki/rfc33_gtiff_pixelispoint.

**Comment by alastairUK** [comment]
[tq3178_DSM_2M.zip](https://github.com/OSGeo/gdal/files/7455608/tq3178_DSM_2M.zip)

**Comment by jratike80** [comment]
It seems that I must learn how to make raster queries by using point data, the interactive query tool is inaccurate. But if the Surfer documentation about the ASCII Grid format is right user should avoid making queries at the pixel boundaries if it is crucial to get the value from just the right pixel.

> The Z values are always reported for the center of each grid cell. These real numbers (with optional decimal point, if needed) and are delimited using a single space character.

**Comment by jratike80** [comment]
Unfortunately I must give up, my license does not allow to use the Extract values to points tool.

**Comment by alastairUK** [comment]
Grabbed a demo version of ArcGIS pro

ExtractByPoints("tq3178_DSM_2M.asc", [arcpy.Point(531000, 178998)],"INSIDE").getStatistics()
[{'min': 3.990000009536743, 'max': 3.990000009536743, 'mean': 3.990000009536743, 'standardDeviation': 0.0, 'skipX': 1, 'skipY': 1, 'count': 0.0}]

![image](https://user-images.githubusercontent.com/5337814/139853114-a4cca06c-d86b-417d-9464-51e78a9e9220.png)

**Comment by jratike80** [comment]
Please try with a set of y-coordinates
179000, 178998, 178996, 178994, 178992, 178990

In my manual test the same pixel was selected with 179000 and 178998 even that should not be possible, but because of floating point inaccuracies that would not be really surprising. But it may be just due to a poor method.

**Comment by alastairUK** [comment]
ExtractByPoints("tq3178_DSM_2M.asc", [arcpy.Point(531000, 179000)],"INSIDE").getStatistics()
[{'min': 3.990000009536743, 'max': 3.990000009536743, 'mean': 3.990000009536743, 'standardDeviation': 0.0, 'skipX': 1, 'skipY': 1, 'count': 0.0}]
ExtractByPoints("tq3178_DSM_2M.asc", [arcpy.Point(531000, 178998)],"INSIDE").getStatistics()
[{'min': 3.990000009536743, 'max': 3.990000009536743, 'mean': 3.990000009536743, 'standardDeviation': 0.0, 'skipX': 1, 'skipY': 1, 'count': 0.0}]
ExtractByPoints("tq3178_DSM_2M.asc", [arcpy.Point(531000, 178996)],"INSIDE").getStatistics()
[{'min': 4.043000221252441, 'max': 4.043000221252441, 'mean': 4.043000221252441, 'standardDeviation': 0.0, 'skipX': 1, 'skipY': 1, 'count': 0.0}]
ExtractByPoints("tq3178_DSM_2M.asc", [arcpy.Point(531000, 178994)],"INSIDE").getStatistics()
[{'min': 4.052000045776367, 'max': 4.052000045776367, 'mean': 4.052000045776367, 'standardDeviation': 0.0, 'skipX': 1, 'skipY': 1, 'count': 0.0}]
ExtractByPoints("tq3178_DSM_2M.asc", [arcpy.Point(531000, 178992)],"INSIDE").getStatistics()
[{'min': 4.0879998207092285, 'max': 4.0879998207092285, 'mean': 4.0879998207092285, 'standardDeviation': 0.0, 'skipX': 1, 'skipY': 1, 'count': 0.0}]
ExtractByPoints("tq3178_DSM_2M.asc", [arcpy.Point(531000, 178990)],"INSIDE").getStatistics()
[{'min': 4.144999980926514, 'max': 4.144999980926514, 'mean': 4.144999980926514, 'standardDeviation': 0.0, 'skipX': 1, 'skipY': 1, 'count': 0.0}]


![image](https://user-images.githubusercontent.com/5337814/139856764-f6218046-d670-434c-b00c-2c8e7b5f5501.png)

**Comment by alastairUK** [comment]
Aside from the 531000, 179000 value I would say ArcInfo looks *right*

Note: gdallocationinfo is "off by 1" to this

>gdallocationinfo -geoloc "tq3178_DSM_2M.asc" 531000 179000
Report:
  Location: (0P,0L)
  Band 1:
    Value: 3.99000000953674

>gdallocationinfo -geoloc "tq3178_DSM_2M.asc" 531000 178998
Report:
  Location: (0P,1L)
  Band 1:
    Value: 4.04300022125244

>gdallocationinfo -geoloc "tq3178_DSM_2M.asc" 531000 178996
Report:
  Location: (0P,2L)
  Band 1:
    Value: 4.05200004577637

>gdallocationinfo -geoloc "tq3178_DSM_2M.asc" 531000 178994
Report:
  Location: (0P,3L)
  Band 1:
    Value: 4.08799982070923

>gdallocationinfo -geoloc "tq3178_DSM_2M.asc" 531000 178992
Report:
  Location: (0P,4L)
  Band 1:
    Value: 4.14499998092651

>gdallocationinfo -geoloc "tq3178_DSM_2M.asc" 531000 178990
Report:
  Location: (0P,5L)
  Band 1:
    Value: 4.13700008392334

**Comment by jratike80** [comment]
I would say that ArcGIS Pro looks at least _different_ when it considers that point with Y value at the border of two pixels belongs to the upper pixel while GDAL considers that it belongs to the lower pixel. In addition, ArcGIS has a special rule for the pixels at the upper row. I made a quick test with GeoTIFF `gdal_translate tq3178_DSM_2M.asc tq3178_DSM_2M.tif` and ArcGIS pro and I did not see any difference between .asc and .tif so I think that ESRI is using the same rules for GeoTIFF and that's a logical and good thing.

Now we could start to study the GeoTIFF standard http://docs.opengeospatial.org/is/19-008r4/19-008r4.html. For me it seems rather clear that the ModelTiePoint belongs to the pixel that is to the right and below the ModelTiePoint

> Its ModelTiePoint tag may be used to provide the location of pixel (0, 0) with the coordinates of the upper left corner of this pixel (in case of PixelIsArea) 

You did make an interesting observation but I do not believe that ESRI will change anything and I do not see a reason to change how GDAL behaves. Perhaps users should be informed to be careful at pixel borders.

**Comment by alastairUK** [comment]
Strikes me that ArcInfo, MapInfo Pro and GlobalMapper Pro all seem to take the same/similar approach and GDAL is perhaps the outlier for this edge-case scenario.

Is it not (simply) the case of which direction you approach from? From ASCII Grid it references the LOWER LEFT so we approach upwards. Whereas I believe GDAL works down from TOP LEFT?
