### ISSUE TITLE
GDAL 3.3.3 build error on SLES 15

### ISSUE THREAD

**Issue by devrimgunduz** [OSGeo/gdal#4750]
Hi,

This is a platform that I never built GDAL, so this is likely an issue coming from the  past. I'm getting the following error while building GDAL 3.3.3 on SLES 15. Component versions are:

* GeOS 3.9.1
* GCC 7.5.0
* libspatialite 4.3
* libgeotiff 1.6
* OGDI 4.1
* libdap 3.20.5

Any idea how we can fix this? Thanks!

> 
/bin/sh /var/lib/pgsql/git/pgrpms/rpm/redhat/master/common/gdal33/main/gdal-3.3.3-fedora/libtool --mode=link --silent g++ -L/usr/proj81/lib -L/usr/ogdi41/lib -L/usr/libgeotiff16/lib -L/usr/geos39/lib64 -L/usr/libspatialite43/lib -L/usr/lib64 gdal_translate_bin.lo  /var/lib/pgsql/git/pgrpms/rpm/redhat/master/common/gdal33/main/gdal-3.3.3-fedora/libgdal.la -o gdal_translate
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: /var/lib/pgsql/git/pgrpms/rpm/redhat/master/common/gdal33/main/gdal-3.3.3-fedora/.libs/libgdal.so: undefined reference to `libdap::Error::get_error_message[abi:cxx11]() const'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: /var/lib/pgsql/git/pgrpms/rpm/redhat/master/common/gdal33/main/gdal-3.3.3-fedora/.libs/libgdal.so: undefined reference to `libdap::www2id(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: /var/lib/pgsql/git/pgrpms/rpm/redhat/master/common/gdal33/main/gdal-3.3.3-fedora/.libs/libgdal.so: undefined reference to `libdap::DDS::var(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::stack<libdap::BaseType*, std::deque<libdap::BaseType*, std::allocator<libdap::BaseType*> > >*)'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: /var/lib/pgsql/git/pgrpms/rpm/redhat/master/common/gdal33/main/gdal-3.3.3-fedora/.libs/libgdal.so: undefined reference to `libdap::DDS::DDS(libdap::BaseTypeFactory*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: /var/lib/pgsql/git/pgrpms/rpm/redhat/master/common/gdal33/main/gdal-3.3.3-fedora/.libs/libgdal.so: undefined reference to `libdap::DataDDS::DataDDS(libdap::BaseTypeFactory*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: /var/lib/pgsql/git/pgrpms/rpm/redhat/master/common/gdal33/main/gdal-3.3.3-fedora/.libs/libgdal.so: undefined reference to `libdap::InternalErr::InternalErr(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: /var/lib/pgsql/git/pgrpms/rpm/redhat/master/common/gdal33/main/gdal-3.3.3-fedora/.libs/libgdal.so: undefined reference to `libdap::Connect::Connect(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: /var/lib/pgsql/git/pgrpms/rpm/redhat/master/common/gdal33/main/gdal-3.3.3-fedora/.libs/libgdal.so: undefined reference to `libdap::DAS::get_table(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: /var/lib/pgsql/git/pgrpms/rpm/redhat/master/common/gdal33/main/gdal-3.3.3-fedora/.libs/libgdal.so: undefined reference to `libdap::Error::Error(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
collect2: error: ld returned 1 exit status
make: *** [GNUmakefile:90: gdalinfo] Error 1
make: *** Waiting for unfinished jobs....
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: /var/lib/pgsql/git/pgrpms/rpm/redhat/master/common/gdal33/main/gdal-3.3.3-fedora/.libs/libgdal.so: undefined reference to `libdap::Error::get_error_message[abi:cxx11]() const'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: /var/lib/pgsql/git/pgrpms/rpm/redhat/master/common/gdal33/main/gdal-3.3.3-fedora/.libs/libgdal.so: undefined reference to `libdap::www2id(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: /var/lib/pgsql/git/pgrpms/rpm/redhat/master/common/gdal33/main/gdal-3.3.3-fedora/.libs/libgdal.so: undefined reference to `libdap::DDS::var(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::stack<libdap::BaseType*, std::deque<libdap::BaseType*, std::allocator<libdap::BaseType*> > >*)'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: /var/lib/pgsql/git/pgrpms/rpm/redhat/master/common/gdal33/main/gdal-3.3.3-fedora/.libs/libgdal.so: undefined reference to `libdap::DDS::DDS(libdap::BaseTypeFactory*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: /var/lib/pgsql/git/pgrpms/rpm/redhat/master/common/gdal33/main/gdal-3.3.3-fedora/.libs/libgdal.so: undefined reference to `libdap::DataDDS::DataDDS(libdap::BaseTypeFactory*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: /var/lib/pgsql/git/pgrpms/rpm/redhat/master/common/gdal33/main/gdal-3.3.3-fedora/.libs/libgdal.so: undefined reference to `libdap::InternalErr::InternalErr(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: /var/lib/pgsql/git/pgrpms/rpm/redhat/master/common/gdal33/main/gdal-3.3.3-fedora/.libs/libgdal.so: undefined reference to `libdap::Connect::Connect(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: /var/lib/pgsql/git/pgrpms/rpm/redhat/master/common/gdal33/main/gdal-3.3.3-fedora/.libs/libgdal.so: undefined reference to `libdap::DAS::get_table(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: /var/lib/pgsql/git/pgrpms/rpm/redhat/master/common/gdal33/main/gdal-3.3.3-fedora/.libs/libgdal.so: undefined reference to `libdap::Error::Error(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
collect2: error: ld returned 1 exit status
make: *** [GNUmakefile:99: gdal_translate] Error 1

**Comment by rouault** [comment]
I'd suggest to just drop DODS support in your build. It will be eventually completed removed from the code base in GDAL 3.5

**Comment by devrimgunduz** [comment]
Thanks @rouault , this worked!
