### ISSUE TITLE
MITAB: Can't read MID files containing strings with quoted newlines 

### ISSUE THREAD

**Issue by craigds** [OSGeo/gdal#4789]
## Expected behavior and actual behavior.

A customer supplied some MIF data to us, which has MID files where the attribute data contains windows newline characters (`\r\n`)

GDAL fails to read the records which contain the newlines:

```
ERROR 6: Error during reading Record.
```

I guess this issue is [here](https://github.com/OSGeo/gdal/blob/1645ac2d9ee2dae57f99519ab318e02061820e5e/ogr/ogrsf_frmts/mitab/mitab_middatafile.cpp#L160) in the source code. I wonder could this just call the CSV driver, since this MID file appears to be an identical format to a fairly normal CSV file?

## Steps to reproduce the problem.

Here's a minimal MIF and MID file that cause the error (I removed/replaced proprietary customer data but retained the newlines):

MIF: 
```
Version   410
Charset "WindowsLatin1"
Delimiter ","
Index 1,2
CoordSys Earth Projection 8, 12, "m", 153, 0, 0.9996, 500000, 10000000 Bounds (-7745874.38492, 1999.40969607) (8745874.38492, 19998000.5903)
Columns 3
  Name Char(51)
  Notes Char(100)
  Awesome Logical
Data

Pline 3
482281.14 6738543.72
482278.29 6738548.02
482276.11 6738551.17
    Pen (4,104,8421504) 
```

MID: 
```
"NEWNAME ROAD","NAME CHANGED FROM OLDNAME ROAD  11-05-01

Oldname Rd (No.123) added 11-05-01",F
```

## Operating system

MacOS 11.6

## GDAL version and provenance

GDAL 3.3.2, released 2021/09/01

**Comment by rouault** [comment]
Using CSVReadParseLine2L from port/cpl_port.h should do the job. Perhaps enhanced as CSVReadParseLine3L with an extra argument for the maximum line size, and with the use of std::string as in OGRCSVReadParseLineL() from ogr/ogrsf_frmts/csv/ogrcsvlayer.cpp to speed-up concatenation

**Comment by rouault** [comment]
> A customer supplied some MIF data to us, which has MID files where the attribute data contains windows newline characters (`\r\n`)

by the way, is that properly recognized when read with MapInfo software ?

**Comment by jratike80** [comment]
I can have a try with MapInfo but could you put the mid+mif into a zip? I am not sure if copy-paste will create me correct contents.

**Comment by jratike80** [comment]
Found a capture from specification:
The textual data is delimited data, with one row per record and either Carriage Return, Carriage Return plus Line Feed, or Line Feed between lines.

Title mentions "strings with quoted newlines". How are they quoted? The text box above does not show any quotation, perhaps markup is changing the text.

**Comment by craigds** [comment]
Thanks for looking at this. The quoting is visible for me above - it's just regular double-quotes quoting the entire attribute value (just like in regular CSV). here's a zip file:

[minimal-newline-issue.zip](https://github.com/OSGeo/gdal/files/7500104/minimal-newline-issue.zip)
.

**Comment by jratike80** [comment]
I understand it now, the whole second string is quoted with double quotes and CR-LR appear there in between. "with quoted newlines" made me to search for something like `\\r\\n` within the string. I will report back how MapInfo behaves.

**Comment by jratike80** [comment]
MapInfo version 17.0.3 Release build 19 opens this MIF/MID and shows the multi-line content of the second field in this way:

![MapInfo_multi_line](https://user-images.githubusercontent.com/1751612/140888253-9b5b3b3a-adaa-4868-937a-69197b6ce1f0.png)
