### ISSUE TITLE
Small Typo in FindSQLite3.cmake

### ISSUE THREAD

**Issue by spezialspezial** [OSGeo/gdal#4795]
https://github.com/OSGeo/gdal/blob/60c71fa450885399c96039a8cf59a259112f4a9e/cmake/modules/packages/FindSQLite3.cmake#L31

Should be SQLite3_LIBRARY, not SQ**LI**ite3_LIBRARY

**Comment by rouault** [comment]
Fixed thanks. Do not hesitate to directly file pull requests with the fix
