### ISSUE TITLE
FindECW.cmake unavailable libraries NCSCnet, NCSEcwC, NCSUtil

### ISSUE THREAD

**Issue by spezialspezial** [OSGeo/gdal#4796]
https://github.com/OSGeo/gdal/blob/60c71fa450885399c96039a8cf59a259112f4a9e/cmake/modules/packages/FindECW.cmake#L91-L93

The Hexagon ECW SDK does not sport these files, at least in version 5.5.0. Sure these are mandatory?

**Comment by rouault** [comment]
> The Hexagon ECW SDK does not sport these files, at least in version 5.5.0. Sure these are mandatory?

they are only looked for ECW SDK 3.3, where they are necessary. I'll add a comment to make that clear

**Comment by spezialspezial** [comment]
Ah, got it, thanks
