### ISSUE TITLE
PROJ: proj_create_from_database: ellipsoid not found

### ISSUE THREAD

**Issue by Go-Tak** [OSGeo/gdal#4801]
In python console of QGIS3.16.13, above error occurred when executing GetProjection() statement as shown in section of Steps to reproduce the problem. The file used is attached below as zip file.

The same statement works fine in Jupyter environment using the same file attached and the same PROJ_LIB. Both environment use the same version of GDAL as shown below.

What does ellipsoid mean in this case and what should I do to solve this problem?

## Actual behavior. 

1. Traceback (most recent call last):
2.   File "C:\PROGRA~1\QGIS3~1.16\apps\Python37\lib\code.py", line 90, in runcode
3.     exec(code, self.locals)
4.   File "<input>", line 1, in <module>
5.   File "C:\Users\go_ta\AppData\Roaming\Python\Python37\site-packages\osgeo\gdal.py", line 2093, in GetProjection
6.     return _gdal.Dataset_GetProjection(self, *args)
7. RuntimeError: PROJ: proj_create_from_database: ellipsoid not found
8

## place where this error detected

GetProjection  function defined in gdal.py

1. def GetProjection(self, *args):
2.         r"""GetProjection(Dataset self) -> char const *"""
3.         return _gdal.Dataset_GetProjection(self, *args)

--> I don't understand 2nd statement which may cause this error

## Steps to reproduce the problem.

1. from osgeo import gdal, gdalconst
2. l = gdal.Open('c:\\Users\\go_ta\\Downloads\\2021-10-30-00_00_2021-10-30-23_59_Sentinel-2_L2A_B03_(Raw).tiff', gdalconst.GA_ReadOnly)
3. crs = l.GetProjection()

## Operating system & Python 

Windows 11 Home(64bit)
QGIS: 3.7.0
JUpyter: 3.7.10

## GDAL version and provenance
osgeo.gdal.VersionInfo("RELEASE_NAME")
'3.3.1'

[2021-10-30-00_00_2021-10-30-23_59_Sentinel-2_L2A_B03_(Raw).zip](https://github.com/OSGeo/gdal/files/7503052/2021-10-30-00_00_2021-10-30-23_59_Sentinel-2_L2A_B03_.Raw.zip)
[out.zip](https://github.com/OSGeo/gdal/files/7503587/out.zip)

**Comment by rouault** [comment]
Emitting errors is a bit strong indeed, especially when using gdal.UseExceptions(). I've turned them as warnings. But they are legitimate here as the georeferencing of that file is partially invalid. It uses 1 as a value for GeogGeodeticDatumGeoKey and  GeogEllipsoidGeoKey which is in the reserved value range (1-1023). 32767 = User defined should rather be used here. This is something the data producer should correct

**Comment by Go-Tak** [comment]
Thank you for the comment.

What do you think of the different activity of 2 same version of gdal? 

Anyway I will check the other files downloaded from the same organization.

**Comment by rouault** [comment]
> What do you think of the different activity of 2 same version of gdal?

maybe Jupyter catches GDAL errors & warnings to redirect them somewhere

**Comment by Go-Tak** [comment]
Thank you the response.

I understand the reason.

I checked several tiff files and found that no errors.
