### ISSUE TITLE
check_symbol_exists in FindSQLite3.cmake fails for static library

### ISSUE THREAD

**Issue by spezialspezial** [OSGeo/gdal#4811]
Hi, I'm trying to link in a static sqlite but the check in FindSQLite3.cmake

https://github.com/OSGeo/gdal/blob/eae5c2449d0691b4dc13e69adb9206effddadbd1/cmake/modules/packages/FindSQLite3.cmake#L61-L62

doesn't detect the symbols in the object's table.

-- Looking for sqlite3_column_table_name - not found
-- Looking for sqlite3_rtree_query_callback - not found

Right now I'm forcing this to pass using

-DSQLite3_HAS_COLUMN_METADATA=yes \
-DSQLite3_HAS_RTREE=yes \

but I'm not sure that is how it's supposed to work.

**Comment by rouault** [comment]
> Right now I'm forcing this to pass using
> 
> -DSQLite3_HAS_COLUMN_METADATA=yes -DSQLite3_HAS_RTREE=yes \
> 
> but I'm not sure that is how it's supposed to work.

you shouldn't have to do that, and if you do that, I'd suspect GDAL will not link.

How did you build your static sqlite ?

**Comment by spezialspezial** [comment]
```
CPPFLAGS="-DSQLITE_ENABLE_COLUMN_METADATA=1" \
./configure --prefix=${INSTALLDIR} \
	--enable-rtree \
	2>&1 | tee ${INSTALLDIR}/sqlite3-configure-log.txt

make clean
make -j$(nproc) | tee ${INSTALLDIR}/sqlite3-build-log.txt
make install 

nm -gD ${INSTALLDIR}/lib/libsqlite3.so | grep sqlite3_column_*
nm -gD ${INSTALLDIR}/lib/libsqlite3.so | grep sqlite3_rtree_*
nm -gC libsqlite3.a | grep sqlite3_column_*
nm -gC libsqlite3.a | grep sqlite3_rtree_*
```

**Comment by spezialspezial** [comment]
It works for the shared library. check_symbol_exists might be incapable or not designed to find symbols in objects would be my guess.

**Comment by spezialspezial** [comment]
> I'd suspect GDAL will not link.

Yeah, kind of. It ignores the static library and uses the shared one

**Comment by rouault** [comment]
With the following patch
```
diff --git a/cmake/modules/packages/FindSQLite3.cmake b/cmake/modules/packages/FindSQLite3.cmake
index 08966cc7e8..7ad882044b 100644
--- a/cmake/modules/packages/FindSQLite3.cmake
+++ b/cmake/modules/packages/FindSQLite3.cmake
@@ -56,7 +56,11 @@ endif()
 
 if(SQLite3_INCLUDE_DIR AND SQLite3_LIBRARY)
     # check column metadata
-    set(CMAKE_REQUIRED_LIBRARIES ${SQLite3_LIBRARY})
+    if( ${SQLite3_LIBRARY} MATCHES "libsqlite3.a" AND PC_SQLITE3_STATIC_LIBRARIES)
+        set(CMAKE_REQUIRED_LIBRARIES ${PC_SQLITE3_STATIC_LIBRARIES})
+    else()
+        set(CMAKE_REQUIRED_LIBRARIES ${SQLite3_LIBRARY})
+    endif()
     set(CMAKE_REQUIRED_INCLUDES ${SQLite3_INCLUDE_DIR})
     check_symbol_exists(sqlite3_column_table_name sqlite3.h SQLite3_HAS_COLUMN_METADATA)
     check_symbol_exists(sqlite3_rtree_query_callback sqlite3.h SQLite3_HAS_RTREE)
```

and building sqlite3 from sqlite-autoconf-3360000 with
CPPFLAGS="-DSQLITE_ENABLE_COLUMN_METADATA=1" ./configure --prefix=$HOME/install-sqlite-3.36.0-static --disable-shared --enable-rtree

and then in a GDAL build dir
PKG_CONFIG_PATH=/home/even/install-sqlite-3.36.0-static/lib/pkgconfig cmake ..

I manage to make SQLite3 features detected

**Comment by spezialspezial** [comment]
The patch works nicely so far. It links to any shared sqlite library it can find tho. I doublecheck PKG_CONFIG_PATH and how to suppress system paths first thing in the morning.

**Comment by spezialspezial** [comment]
After quite a bit digging in the guts of the machine it seems libcurl pulls in another dependency to a shared libsqlite3. I'll see how that goes.
