### ISSUE TITLE
Add support for pcre2

### ISSUE THREAD

**Issue by sebastic** [OSGeo/gdal#4822]
GDAL currently requires the deprecated [PCRE library](https://pcre.org/) (`pcre.h`), as used by the Debian package via libpcre3-dev.

The maintainer of the pcre3 package in Debian intends to remove it in favour of pcre2 (`pcre2.h`), because upstream is increasingly unwilling to fix issues in the old PCRE library, see: https://lists.debian.org/debian-devel/2021/11/msg00176.html

GDAL currently only supports the PCRE API, it should also support the PCRE2 API for regex support for SQLite.

**Comment by jmckenna** [comment]
I recently hit this for the MS4W 5.0 release effort (as Apache HTTP, MapCache, GDAL, MapServer, etc. all do not support PCRE2 yet, but PHP8 does).  Workaround is for now to use PCRE 8.45 throughout, but I agree, all projects should support the maintained PCRE2 going forward.
