### ISSUE TITLE
gdalwarp hangs with -cutline polygon

### ISSUE THREAD

**Issue by cgodkin** [OSGeo/gdal#4826]
## Expected behavior and actual behavior.

I am trying to use gdalwarp to transform and clip some GeoTIFF images but 
gdalwarp is hanging in GDAL 3.3.3 and 3.4.0 when clipping a GeoTIFF with a fairly simple GeoJSON (or Shapefile).

Note that my command line _works_ and produces the expected output with GDAL 2.4.4 so I guess this is a regression.

## Steps to reproduce the problem.
```
gdalwarp -t_srs EPSG:4326 \
        -cutline "New York HEL.json" -crop_to_cutline -dstalpha \
       "New York HEL.tif" out.tif --debug ON
```
Output:
```
GDAL: GDALOpen(New York HEL.tif, this=0000028BF43FF020) succeeds as GTiff.
GDAL: Using GTiff driver
GeoJSON: First pass: 100.00 %
GDAL: GDALOpen(New York HEL.json, this=0000028BF247BB40) succeeds as GeoJSON.
GDAL: GDALClose(New York HEL.json, this=0000028BF247BB40)
```

Various things I tried:
- I tried converting my GeoJSON to a shapefile - Same behavior 
- I tried EPSG:3857 as the output SRS - Same behavior
- Various versions of GDAL as reported

## Operating system

Windows 10

## GDAL version and provenance

GDAL 2.4.4, released 2020/01/08 - from MS4W installation **works**
GDAL 3.3.3, released 2021/10/25 - from Conda (`conda install -c conda-forge gdal`)  **fails**
GDAL 3.4.0, released 2021/11/04 - built myself from source  **fails**

I will attach the GeoJSON since it's small but the GeoTIFF is available from [here](https://aeronav.faa.gov/visual/10-07-2021/heli_files/New_York_Heli.zip).

Note that GitHub says it doesn't support JSON files (really?) so the file I attached has a .txt suffix appended.
[New York HEL.json.txt](https://github.com/OSGeo/gdal/files/7533987/New.York.HEL.json.txt)

**Comment by cgodkin** [comment]
I have a second case too that fails (hangs) in ALL three GDAL versions that I tried, so this is not _only_  a regression.
```
gdalwarp -t_srs EPSG:3857 \
    -cutline "ENR_H04.shp" -crop_to_cutline -dstalpha \
    "ENR_H04.tif" out2.tif --debug ON
```
The debug output:
```
GDAL: GDALOpen(ENR_H04.tif, this=0000024D45D1A6A0) succeeds as GTiff.
GDAL: Using GTiff driver
Shape: DBF Codepage = LDID/87 for ENR_H04.shp
Shape: Treating as encoding 'ISO-8859-1'.
GDAL: GDALOpen(ENR_H04.shp, this=0000024D45F5E230) succeeds as ESRI Shapefile.
Shape: 1 features read on layer 'ENR_H04'.
GDAL: GDALClose(ENR_H04.shp, this=0000024D45F5E230)
```

The GeoTIFF is available from [here](https://aeronav.faa.gov/enroute/10-07-2021/enr_h04.zip) and I'll attach the shapefile cutline zipped up.
[ENR_H04.zip](https://github.com/OSGeo/gdal/files/7534012/ENR_H04.zip)

Thanks!

**Comment by jratike80** [comment]
For the curious ones, the perimeter of the test geometry is over 5020 km long.

**Comment by cgodkin** [comment]
I just built gdal-master here and can confirm that both of the previously failing gdalwarp command lines now work fine.

Thank you very much!!
