### ISSUE TITLE
VS17.0 build error

### ISSUE THREAD

**Issue by egorpugin** [OSGeo/gdal#4842]
## Expected behavior and actual behavior.

Error during build `frmts/gtiff/tif_jxl.c`:
```
frmts/gtiff/tif_jxl.c(295): error C2059: syntax error: '}'
frmts/gtiff/tif_jxl.c(487): error C2059: syntax error: '}'
frmts/gtiff/tif_jxl.c(492): error C2059: syntax error: '}'
frmts/gtiff/tif_jxl.c(577): error C2059: syntax error: '}'
```

## Operating system

win11

## GDAL version and provenance

3.4.0; custom build system

---

Replacing `= {};` with `= {0};` in these places fixes the issue.

**Comment by rouault** [comment]
> Replacing `= {};` with `= {0};` in these places fixes the issue.

would you mind issuing a pull request with those fixes ?

**Comment by egorpugin** [comment]
See https://github.com/OSGeo/gdal/pull/4843
