### ISSUE TITLE
MAX_Z_ERROR_OVERVIEW config option

### ISSUE THREAD

**Issue by dncpax** [OSGeo/gdal#4848]
## Expected behavior and actual behavior.

I expect to compress overviews with LERC_DEFLATE and set the MAX_Z_ERROR. But there is no way to set this parameter.

## GDAL version and provenance

The 3.3.3 version from osgeo4w (32bit).

**Comment by kannes** [comment]
I just had the same idea. It would be nice to compress overviews with a higher Z error or even one at all, compared to the "raw" data for some space savings through lossy compression while staying with the same algorithm.

**Comment by tbonfort** [comment]
Until the day gdal supports advanced compression/creation options for overviews, you might want to consider https://github.com/airbusgeo/cogger#advanced which was in part created to support this use case.
