### ISSUE TITLE
Compile errors when installing PyPi GDAL 3.4.0 package

### ISSUE THREAD

**Issue by spezialspezial** [OSGeo/gdal#4863]
Hi,

just a quick FYI. I'm getting some compile errors trying to install the latest GDAL 3.4.0 for python via pip/wheel. Classic setup.py fails too. Installing 3.4.0 via Conda, also 3.8 interpreter, seems to work out.

## Steps to reproduce the problem.
1. Activate your favorite venv
2. (venv) hu@ha:~$ pip3 install GDAL
3. [GDAL_python_install.txt](https://github.com/OSGeo/gdal/files/7574978/GDAL_python_install.txt)

## Operating system
Ubuntu 20.04 64 bit, pip version 20.2.4 and 21.3.1, Python 3.8.10 

## GDAL version and provenance
latest from https://pypi.org/project/GDAL/
GDAL-3.4.0.tar.gz (756 kB)

**Comment by rouault** [comment]
you need to have installed the GDAL native library of the version that corresponds to the GDAL Python bindings you want to install.

**Comment by rouault** [comment]
See https://github.com/OSGeo/gdal/issues/880
