### ISSUE TITLE
Document hardcoded PNG dimension limits

### ISSUE THREAD

**Issue by kannes** [OSGeo/gdal#4870]
https://gdal.org/drivers/raster/png.html has a hardcoded limit on the image dimensions to 1000000x1000000 pixels while the format could handle 2^31.

This is set in the internal libpng's https://github.com/OSGeo/gdal/blob/35c07b18316b4b6d238f6d60b82c31e25662ad27/frmts/png/libpng/pnglibconf.h#L209-L210 which is (at least pretty much) a direct clone of https://sourceforge.net/p/libpng/code/ci/master/tree/scripts/pnglibconf.h.prebuilt, so this is not a limitation that GDAL invented and an external libpng would most probably have the same limitation.

If the users tries to create a bigger image, GDAL will quit with:
```
Warning 1: libpng: Image width exceeds user limit in IHDR
ERROR 1: libpng: Invalid IHDR data
```

Please add a note to the documentation page that mentions the hardcoded limit.

Note: **I will do this** when I find the time to do a small PR

**Comment by jratike80** [comment]
Should we also mention that even 1000000x1000000 is ridiculously big png image because when png is opened it must be read totally into memory? Should we similarly document the JPEG max size of 65535×65535? I think I saw a question about that some time ago in gis.stackexchange.

**Comment by rouault** [comment]
> because when png is opened it must be read totally into memory?

I don't think that's true, at least for GDAL. GDAL reads line by line (I don't believe libpng itself needs to allocate the memory for the whole image), so you could read sequentially a 1000000x1000000 PNG file with just ~ 1 MB of RAM. But as there are no pointers to the start of each row, if you don't read sequentially from top to bottom, then GDAL will need to decompress content it won't use.

**Comment by kannes** [comment]
I like those suggestions! https://gdal.org/drivers/raster/webp.html does it nicely, mentions the maximum size as well as the memory issue:

> The WebP library (at least in its version 0.1) only offers compression and decompression of whole images, so RAM might be a limitation when dealing with big images (which are limited to 16383x16383 pixels).

Can you verify that PNG will be handled in a whole in RAM? Then I'd add a similar sentence to it.

For JPEG I am not sure a notice would help, https://gdal.org/drivers/raster/jpeg.html sounds like it cannot be used to create a JPEG from scratch and the sane way for GIS JPEG is JPEG in GeoTIFF anyways which uses tiles and then it does not matter.

**Comment by jratike80** [comment]
Ok, I had wrong knowledge about png based on another software.

**Comment by kannes** [comment]
Raced over by @rouault being so quick to clarify PNG in GDAL and merge my PR, thanks! :)

**Comment by jratike80** [comment]
> For JPEG I am not sure a notice would help, https://gdal.org/drivers/raster/jpeg.html sounds like it cannot be used to create a JPEG from scratch

Certainly it can
```
gdal_translate -of JPEG truecolorsample.tif truecolorsample.jpg
Input file size is 1878, 1807
0...10...20...30...40...50...60...70...80...90...100 - done.
```

**Comment by rouault** [comment]
> For JPEG I am not sure a notice would help, https://gdal.org/drivers/raster/jpeg.html sounds like it cannot be used to create a JPEG from scratch

the PNG and JPEG driver have pretty much the same capabilities/limitations: they can be created with CreateCopy() / gdal_translate, that is from a source dataset that is entirely known in advance of the creation process, since they need to write row by row from top to bottom. What they can't do is : update an existing image, or write content in arbitrary order, which is what the Create() API allows

**Comment by kannes** [comment]
Fixed in https://github.com/OSGeo/gdal/pull/5228

**Comment by jratike80** [comment]
I think it is OK with JPEG but we have loads of supported file formats and each of them has some limits when it comes to size, number of bands, supported bit depths etc. Question a) How much we should try to document limitations which arise from the format itself b) if we start to document those things more generally, should we add a a new section "limitations" to driver pages so that users could find the information from a predictable place?
