### ISSUE TITLE
OGR "ERROR 1: Error occurred in filegdbtable.cpp at line 1553" (and 1444)

### ISSUE THREAD

**Issue by maphew** [OSGeo/gdal#4881]
## Expected behavior and actual behavior.

**Ogr2ogr** reports errors on some Esri feature classes, perhaps 15 or 20% out of the 1000 I've been working with. If `-skipfailures` is used the output layer is created but is empty. Qgis can open and view the source feature class geometry and attributes, but within the fields characters do no show properly.

## Steps to reproduce the problem.
~~~
ogr2ogr -where "Category = 1" ^
  -nln gy_sat_footprints ^
  broken.gpkg ^
  S_Satellites.gdb ^
  S_Satellites_SnakeR_321_30Jul2018_150cm_NAD1983_UTM8N_f
~~~

Result:
~~~
ERROR 1: Error occurred in filegdbtable.cpp at line 1553
ERROR 1: Error occurred in filegdbtable.cpp at line 1444
ERROR 1: Error occurred in filegdbtable.cpp at line 1444
ERROR 1: Error occurred in filegdbtable.cpp at line 1444
ERROR 1: Error occurred in filegdbtable.cpp at line 1444
ERROR 1: Error occurred in filegdbtable.cpp at line 1444
ERROR 1: Error occurred in filegdbtable.cpp at line 1444
ERROR 1: Error occurred in filegdbtable.cpp at line 1444
ERROR 1: Error occurred in filegdbtable.cpp at line 1444
ERROR 1: Error occurred in filegdbtable.cpp at line 1444
ERROR 1: Error occurred in filegdbtable.cpp at line 1553
ERROR 1: Error occurred in filegdbtable.cpp at line 1444
ERROR 1: Error occurred in filegdbtable.cpp at line 1444
ERROR 1: Error occurred in filegdbtable.cpp at line 1444
ERROR 1: Error occurred in filegdbtable.cpp at line 1444
ERROR 1: Error occurred in filegdbtable.cpp at line 1444
ERROR 1: Error occurred in filegdbtable.cpp at line 1444
ERROR 1: Error occurred in filegdbtable.cpp at line 1444
ERROR 1: Error occurred in filegdbtable.cpp at line 1444
ERROR 1: Error occurred in filegdbtable.cpp at line 1444
ERROR 1: Error occurred in filegdbtable.cpp at line 1444
ERROR 1: Error occurred in filegdbtable.cpp at line 1444
ERROR 1: Error occurred in filegdbtable.cpp at line 1669
ERROR 1: Error occurred in filegdbtable.cpp at line 1444
ERROR 1: Error occurred in filegdbtable.cpp at line 1444
ERROR 1: Terminating translation prematurely after failed
translation of layer S_Satellites_SnakeR_321_30Jul2018_150cm_NAD1983_UTM8N_f (use -skipfailures to skip errors)
~~~

~~~
$ ogrinfo broken.gpkg *
INFO: Open of `broken.gpkg'
      using driver `GPKG' successful.
FAILURE: Couldn't fetch requested layer all-footprints.gpkg!
~~~

`ogrinfo` on the source layer is generally successful but issues those same errors periodically (full output attached: [src-layer-info.txt](https://github.com/OSGeo/gdal/files/7583010/src-layer-info.txt)). Snippet:

~~~
TypeID: Integer (0.0), alternative name="Raster Type ID"
ItemTS: Real (0.0)
UriHash: String (50.0)
Uri: Binary (0.0)
Shape_Length: Real (0.0)
Shape_Area: Real (0.0)
ERROR 1: Error occurred in filegdbtable.cpp at line 1553
ERROR 1: Error occurred in filegdbtable.cpp at line 1444
ERROR 1: Error occurred in filegdbtable.cpp at line 1444
ERROR 1: Error occurred in filegdbtable.cpp at line 1444
ERROR 1: Error occurred in filegdbtable.cpp at line 1444
ERROR 1: Error occurred in filegdbtable.cpp at line 1444
ERROR 1: Error occurred in filegdbtable.cpp at line 1444
ERROR 1: Error occurred in filegdbtable.cpp at line 1444
ERROR 1: Error occurred in filegdbtable.cpp at line 1444
ERROR 1: Error occurred in filegdbtable.cpp at line 1444
OGRFeature(S_Satellites_SnakeR_321_30Jul2018_150cm_NAD1983_UTM8N_f):1
  Raster (Integer) = 1262428869
  Name (String) = ▼‼┘≥CæαEí╟♠²╤
  MinPS (Real) = 3.75894675116383e-147
  MaxPS (Real) = 5.55342671114556e+239
~~~ 

The source feature class in ArcMap 10 and Qgis side by side:  
![image](https://user-images.githubusercontent.com/486200/142903409-4dfc6d92-5f85-43b6-8c98-39caf331c1c7.png)

## Operating system

Windows 10 Enterprise  
Version	10.0.19041 Build 19041

## GDAL version and provenance

GDAL 3.3.2, released 2021/09/01 via QGIS 3.22.0

**Comment by rouault** [comment]
Please attach or link to a geodatabase that triggers those "Error occurred in filegdbtable.cpp ..."

**Comment by maphew** [comment]
[s_satellites.gdb.zip](https://github.com/OSGeo/gdal/files/7583364/s_satellites.gdb.zip)

**Comment by maphew** [comment]
wow. fast! Merci Even.

**Comment by toczydlowski** [comment]
I am getting a similar error/behavior.  Layer of GDB reads in fine in ArcPro but throws the above error that started this issue (my exact error below) using:

`vect("/path/to/my/gdb", layer = "mylayer")` in R.

`Error occurred in filegdbtable.cpp at line 1379 (GDAL error 1)`

Can someone investigate - or tips for me to troubleshoot/investigate?  Thanks!

**Comment by rouault** [comment]
> I am getting a similar error/behavior. Layer of GDB reads in fine in ArcPro but throws the above error that started this issue (my exact error below) using:

what is your GDAL version? If it is not the latest one (3.9.2), please update. If you can still reproduce with it, please file another ticket and attach the dataset
