### ISSUE TITLE
Raster Attribute Table (RAT) not fully populated for geotiff with aux PAM

### ISSUE THREAD

**Issue by VirtualTim** [OSGeo/gdal#4885]
## Expected behavior and actual behavior.

Attached dataset was classified with Erdas Imagine. ([sample_datasets.zip](https://github.com/OSGeo/gdal/files/7586270/sample_datasets.zip))

When loading the attached tiffs, calling `GDALRasterBand::GetDefaultRAT()` only populates two columns; "Class_Names" and "Opacity".
When viewing these file with Imagine RGB columns are displayed.
![image](https://user-images.githubusercontent.com/5424257/142978793-0271e2e9-9567-4f84-b177-dafb28a694ab.png)

From a code point of view, `GTiffRasterBand::GetDefaultRAT()` calls into `HFARasterBand::GetDefaultRAT()`. `HFARasterBand::GetDefaultRAT()` returns (what appears to be) the correct RAT.

`GTiffDataset::LoadGeoreferencingAndPamIfNeeded()` calls `TryLoadXML()`, which loads the aux PAM, then calls `ApplyPamInfo()`.
I believe that `ApplyPamInfo()` should join/combine the PAM RAT with the tiff color table (ColorMap).

----

Potentially also related, `GTiffDataset::ApplyPamInfo()` calls `oMDMD.GetDomainList()`, but I wonder if it's supposed to call `GTiffDataset::GetMetadataDomainList()`?
Same question for `poBand->oMDMD.GetDomainList()`, should that be `poBand->GetMetadataDomainList()`?

----

## Steps to reproduce the problem.

I've attached two samples, supervised_gdal.tif has Class_Names generated by me (so they're things like "Class 1").

## Operating system

Windows 10

## GDAL version and provenance

3.3.0

**Comment by VirtualTim** [comment]
For additional information, the way I'm resolving this on my end is by getting the colourtable (`GetColorTable()`) and the RAT (`GetDefaultRAT()`) and stitching those two together. But I was still wondering if this was something better placed in gdal.

**Comment by rouault** [comment]
I woud be hesitant for the GeoTIFF driver or PAM to mix color table and RAT from .aux.  They are independent concepts in the GDAL API, even if in some drivers like the HFA one, due to both ending up in the same object, they are mixed.
Closing as wontfix
