### ISSUE TITLE
GDALDataset::GetMetadata() is not thread safe

### ISSUE THREAD

**Issue by chacha21** [OSGeo/gdal#4906]
I was expecting GDALDataset::GetMetadata() to be thread-safe in a multiple readers-only scenario.
It appears that the field "oDerivedMetadataList" is modified, resulting in an undefined behaviour (crash for me)

Is it by design, or should AcquireMutex()/ReleaseMutex be added ?

**Comment by rouault** [comment]
> I was expecting GDALDataset::GetMetadata() to be thread-safe

The general rule is that no object in GDAL (as most C++ libraries) is thread-safe, unless otherwise explicitly specified.

**Comment by chacha21** [comment]
So do we let it as is, or is it an improvement to use the mutex in  GDALDataset::GetMetadata() ?

**Comment by rouault** [comment]
> in GDALDataset::GetMetadata() ?

there's no reason why GetMetadata() would be dealt differently as other members, and we definitely don't want to make every method of GDALDataset and GDALRasterBand thread-safe by default (and if we wanted to, that would imply going in *all* drivers). It is the responsibility of users to synchronize concurrent access to GDAL objects.

**Comment by chacha21** [comment]
That makes sense. Since GetMetadata() is a "read" method, it was unexpected that mutating a field was implied, but I can cope with it.
