### ISSUE TITLE
Doc : misleading GDALDriver::CreateCopy() documentation

### ISSUE THREAD

**Issue by chacha21** [OSGeo/gdal#4911]
Let's try to `GDALDriver::CreateCopy()` from an ENVI dataset created with LINE interleaving (thanks to `INTERLEAVE=BIL` creation option)
`dst_ds = enviDriver->CreateCopy(<some dst path>, src_ds_envi_bil, TRUE, 0, 0, 0);`

The dst_ds will be an ENVI with BSQ (BAND) interleaving (the default for this driver)
So it seems that the same creation options must be used to get the same data layout.

I found the doc misleading because :

- it does not mention the importance of the creation options
- it let me believe that bStrict=TRUE would keep the interleaving

**Comment by rouault** [comment]
Perhaps you could suggest a pull request with proposed doc improvements ?

**Comment by chacha21** [comment]
:+ I am always afraid to pull something wrong because of a misunderstanding, but I can do this one

**Comment by rouault** [comment]
You could also have a CreateCopy() implementation in the ENVI driver that would fetch the interleaving from the source dataset and pass it to Create(), and then fallback to DefaultCreateCopy().  EHdrDataset::CreateCopy() could be inspirational for that. Actually it might be possible to have a general logic in DefaultCreateCopy(), that would look if a INTERLEAVE=BIL/BIP/BSQ creation option exists in the output driver, and if a INTERLEAVE metadata item exists in the source dataset

**Comment by chacha21** [comment]
> that would look if a INTERLEAVE=BIL/BIP/BSQ creation option exists in the output driver, and if a INTERLEAVE metadata item exists in the source dataset
Since the syntax for interleaving might differ between drivers (MEM:PIXEL/BAND and ENVI:BIP/BIL/BSQ, for instance) it seems difficult to find a robust generic handling

**Comment by rouault** [comment]
> Since the syntax for `INTERLEAVE=...` might differ between drivers (MEM:PIXEL/BAND and ENVI:BIP/BIL/BSQ, for instance) it seems difficult to find a robust generic handling

that must be about the 2 variations possible. By looking at the possible values in the GDAL_DMD_CREATIONOPTIONLIST, one can figure it out

**Comment by chacha21** [comment]
I am currently investigating, and I can't find a way to get the interleave information from a MEM dataset. There is no associated metadata in my different tests.
Also, to make code simpler in some enhaced CreateCopy() that would support smart interleaving guess, I have to check if every driver behaves the same if the "INTERLEAVE=..." options is repeated in the creation options. With ENVI, the *first* one seems to get precedence, it is (surprinsingly to me) not overwritten by the *last* one

**Comment by chacha21** [comment]
Anyway, changing the CreateCopy() behaviour to smart-guess the interleaving would be a breaking change regarding backward compatibility, so this is certainly not acceptable.

**Comment by rouault** [comment]
> I can't find a way to get the interleave information from a MEM dataset. There is no associated metadata in my different tests.

It should be set there : https://github.com/OSGeo/gdal/blob/master/frmts/mem/memdataset.cpp#L1566

> I have to check if every driver behaves the same if the "INTERLEAVE=..." options is repeated in the creation options

If INTERLEAVE is already defined in the creation options passed by the user, CreateCopy() should not override it.

> changing the CreateCopy() behaviour to smart-guess the interleaving would be a breaking change regarding backward compatibility, so this is certainly not acceptable.

That is a quite reasonable change of behaviour. I believe it would be OK if properly documented, and if the user can have the control with an explicit INTERLEAVE option.
