### ISSUE TITLE
Slow cloud optimization on certain files with gdal_translate

### ISSUE THREAD

**Issue by mplough-kobold** [OSGeo/gdal#4923]
## Expected behavior and actual behavior.

On certain files, cloud optimization runs very slowly.  

When cloud optimizing a 1000x767 pixel TIFF file, I expect the optimization to run quickly.  Instead it takes about a minute and 30 seconds.  Cloud optimizing the same file using rio-cogeo takes about 1 second.

The image is attached in a zip file: [no_crs.tiff.zip](https://github.com/OSGeo/gdal/files/7627875/no_crs.tiff.zip)

## Steps to reproduce the problem.

Create deflate-compressed cloud-optimized GeoTIFFs with GDAL and rio-cogeo.

With GDAL 3.4.0, run:
```
time gdal_translate -of COG -co COMPRESS=deflate no_crs.tiff gdal_cog.tiff
```
The command takes about 1 minute 30 seconds to complete.

With rio-cogeo 3.0.0, run:
```
time rio cogeo create no_crs.tiff rio_cog.tiff
```
The command takes about 1 second to complete.

## Operating system

Docker containers on macOS 11.6.1 (Intel), as described in the next section.

## GDAL version and provenance

* GDAL 3.4.0 in `osgeo/gdal:alpine-small-3.4.0`.
* Rasterio and rio-cogeo in:

```dockerfile
# python:3.8-slim-buster
FROM python@sha256:ebfc7ab9e8a4196a66d7a893a33ebe693f135990128d08b2f35d61d0a010ee40

RUN pip install rasterio==1.2.10
RUN pip install rio-cogeo==3.0.0
```

**Comment by jratike80** [comment]
I think that COG is not the key but GDAL is very slow with that image always. Could you also have a try with this:

`gdal_translate no_crs.tiff copy.tiff`

I see a fast progress till 20% and then full stop for quite a long time.

**Comment by mplough-kobold** [comment]
Interesting.  Yes, I am seeing the same behavior here when running 
```
gdal_translate no_crs.tiff copy.tiff
```
Operation remains slow when running `gdal_translate` again on the output:
```
gdal_translate copy.tiff copy1.tiff
```

**Comment by vincentsarago** [comment]
@mplough-kobold I wonder if this has to do with the enormous `Color Profile` metadata 

the `TIFFTAG_TRANSFERFUNCTION_BLUE` contains thousand of value, which seems really odd 

```
# rio cogeo won't forward the `Color Profile` metadata and run faster 
$ time rio cogeo create no_crs.tiff no_crs_cog.tif --use-cog-driver --quiet
rio cogeo create no_crs.tiff no_crs_cog.tif --use-cog-driver --quiet  
2.06s user 1.13s system 265% cpu 1.200 total

$ time gdal_translate -of COG no_crs.tiff no_crs_cog.tif -q
gdal_translate -of COG no_crs.tiff no_crs_cog.tif -q  
11.70s user 0.11s system 99% cpu 11.835 total
```

**Comment by jratike80** [comment]
Excellent, with `-noxmp` GDAL is fast. Try!

**Comment by mplough-kobold** [comment]
Thanks so much, @vincentsarago and @jratike80 .  The original `gdal_translate` command with `-noxmp` added to skip copying the XMP metadata takes 0.28s on my system.

@vincentsarago if you don't mind my asking, which tool did you use to look at the file to discover that the `TIFFTAG_TRANSFERFUNCTION_BLUE` item is so large?  I've tried `mediainfo`, `exiftool`, `gdalinfo`, `rio info`, and `rio insp`, as well as Hex Fiend with the TIFF template and I haven't been able to get that info to show up.  Maybe I'm missing something easy?

**Comment by vincentsarago** [comment]
@mplough-kobold I used `rio cogeo info`

**Comment by rouault** [comment]
Fixed per 937f1ef9ff7cd5100b824c6e25f6fba1e09ac692

**Comment by mplough-kobold** [comment]
Thanks so much! It looks like this is not an issue with GDAL and is instead the expected behavior with a very strange TIFF file that happened to be in my test data set.  Even better, I now have a better set of tools to inspect TIFF files myself.

**Comment by rouault** [comment]
> It looks like this is not an issue with GDAL and is instead the expected behavior with a very strange TIFF file that happened to be in my test data set.

no, this was a GDAL issue
