### ISSUE TITLE
GDALDriver::Create( ) - Not working for COG driver

### ISSUE THREAD

**Issue by maawoo** [OSGeo/gdal#4929]
## Expected behavior and actual behavior.

```python
driver = gdal.GetDriverByName('COG')
out = driver.Create(...)
```
I expected this to work, but I get the following error message:

`ERROR 6: GDALDriver::Create() ... no create method implemented for this format.` 

Are there any options to circumvent this issue?

## Operating system

Ubuntu 21.04 64 bit

## GDAL version and provenance

GDAL 3.4.0 via conda

**Comment by rouault** [comment]
> Are there any options to circumvent this issue?

This driver is a CreateCopy() only capable driver. If you need to generate the source dataset, you need to use a temporary standard GeoTIFF file first, or a MEM dataset, etc.
