### ISSUE TITLE
GTiff: overview creation issues

### ISSUE THREAD

**Issue by tbonfort** [OSGeo/gdal#4932]
I'm facing 2 issues when transforming a rather large (~100Mb but highly compressed) tiff file, who's spec is
```
Driver: GTiff/GeoTIFF
Files: swbd.tif
Size is 1296000, 428400
Origin = (-180.000000000000000,60.000000000000000)
Pixel Size = (0.000277777777778,-0.000277777777778)
Image Structure Metadata:
  COMPRESSION=CCITTFAX4
  INTERLEAVE=BAND
Corner Coordinates:
Upper Left  (-180.0000000,  60.0000000) 
Lower Left  (-180.0000000, -59.0000000) 
Upper Right ( 180.0000000,  60.0000000) 
Lower Right ( 180.0000000, -59.0000000) 
Center      (   0.0000000,   0.5000000) 
Band 1 Block=2048x2048 Type=Byte, ColorInterp=Palette
  NoData Value=0
  Image Structure Metadata:
    NBITS=1
  Color Table (RGB with 2 entries)
    0: 0,0,0,0
    1: 255,255,255,255
```

First step:
```
gdal_translate -co COMPRESS=CCITTFAX4 -co BLOCKXSIZE=1024 -co BLOCKYSIZE=1024 -co NBITS=1 -co SPARSE_OK=TRUE -co TILED=YES -co BIGTIFF=YES -co NUM_THREADS=8 -of GTiff swbd.tif trncc.tif
```

Second step:
```
gdaladdo trncc.tif --config GDAL_NUM_THREADS 8
```

Issues:
- `gdaladdo` ran from the command line is OOMKilled. changing GDAL_NUM_THREADS does not seem to affect the outcome
- when running the same steps from the api instead of the command line (i.e. a call to GDALTranslate followed by GDALBuildOverviews) the overview creation succeeds but is very slow: it lasts ~1h45 whereas the equivalent computation relying on a series of `GDALTranslate() -outsize 50% 50%` lasts ~15min
- GDALBuildOverviews() does not honor the SPARSE_OK creation option

the dataset can be shared privately.

**Comment by rouault** [comment]
> the dataset can be shared privately.

please share it with me

**Comment by tbonfort** [comment]
thanks Even!
