### ISSUE TITLE
Unable to access features in KML file with Conda GDAL 3.2.1 on WSL2/Hera

### ISSUE THREAD

**Issue by ericgyounkin** [OSGeo/gdal#4938]
Writing on behalf of a colleague of mine.  He is unable to access features in [this KML file](https://drive.google.com/file/d/1rqqOYtpoF3pDyDm_iEtfQf9Q0wwwXYQT/view?usp=sharing) with Conda GDAL 3.2.1 on WSL2/Hera.  This is true for all the KML files that I have, I am only uploading this one as an example.  

To reproduce:

```
from osgeo import ogr

vector = ogr.Open(r"ALFLgom02_8301.kml")
layer = vector.GetLayerByIndex(0)
feature_one = layer.GetFeature(0)
print(feature_one['Name'])

Traceback (most recent call last):
  File "ogr_test.py", line 11, in <module>
    print(feature_one['Name'])
TypeError: 'NoneType' object is not subscriptable
```

Using the following OS's:

3.2.1 (py 3.8.8) and 3.3.2 (py3.9.7) on Conda on Hera -> Didn't work
3.2.1 (py 3.8.8) on Conda on WSL2 -> Didn't work
3.2.1 (py 3.8.8) on Conda on Windows -> Works fine
3.4 (py3.9.5) on [Docker ](https://github.com/OSGeo/gdal/tree/master/docker)-> Works fine

Using 3.2.1 and Windows on my machine I get:

```
vector = ogr.Open(r"ALFLgom02_8301.kml")
layer = vector.GetLayerByIndex(0)
feature_one = layer.GetFeature(0)
print(feature_one['Name'])

'ALFLgom02_8301.bnd'
```

So it appears that the 'didn't work' versions are unable to read the features in these KML files.

**Comment by rouault** [comment]
> 3.2.1 (py 3.8.8) and 3.3.2 (py3.9.7) on Conda on Hera -> Didn't work

Is Hera https://en.wikipedia.org/wiki/Elementary_OS#5.1_Hera ?

> 3.2.1 (py 3.8.8) on Conda on WSL2 -> Didn't work

which Linux distribution on WSL2 ?

Which driver is used, the "KML" one or the "LIBKML" one  (if you open with ds = gdal.OpenEx(), you can see the driver name with ds.GetDriver().GetDescription() ? (but on my Ubuntu 20.04 system, both drivers behave OK on that file). If both are available, you can exclude one of them by setting the OGR_SKIP environment variable to KML or LIBKML, and see if that affects the result

... actually I do see that the feature id of the first feature for the LIBKML driver is 1, and for the KML one it is 0. So I suspect the cases where it doesn't work are with the LIBKML driver. Anyway reading features with GetFeature(fid) is generally inefficient. Scrolling through features is best done with layer.GetNextFeature()

**Comment by SorooshMani-NOAA** [comment]
@rouault 
Hera is [NOAA's supercomputer](https://www.noaa.gov/organization/information-technology/hera). On WSL2 I'm using Ubuntu 20.04.

Thanks, I'll try getting feature 1 instead of 0 on the WSL2 Conda env to see how it works. The GetFeature() call was actually a test code for another package I am trying to use, but thanks for the performance tip.

**Comment by SorooshMani-NOAA** [comment]
@rouault @ericgyounkin `GetFeature(1)`  and `GetNextFeature` works fine on my WSL2 Conda env. It should have been the KML vs LIBKML difference that was causing the issue. Thanks!
