### ISSUE TITLE
GeoTIFF read crash in JPEGSetupDecode

### ISSUE THREAD

**Issue by bal-agates** [OSGeo/gdal#4948]
## Expected behavior and actual behavior.

Initially encountered a hard crash in QGIS 3.22.0 when displaying layer with GeoTIFF.  I was able to duplicate the crash in a much simpler setup using rgb2pct.py.  

The source GeoTIFF was downloaded from [USGS NGMDB I-614](https://ngmdb.usgs.gov/Prodesc/proddesc_9405.htm) by following this link [GeoTIFF ZIP archive](https://ngmdb.usgs.gov/ngm-bin/pdp/download.pl?q=17300_9405_5)

## Steps to reproduce the problem.

python /opt/local/Library/Frameworks/Python.framework/Versions/3.9/bin/rgb2pct.py USGS_I-614_1.tif USGS_I-614_1_index.tif

Crash log is attached.  [GDAL rgb2pct.py JPEGSetupDecode crash.txt](https://github.com/OSGeo/gdal/files/7655069/GDAL.rgb2pct.py.JPEGSetupDecode.crash.txt)

gdalinfo works fine (no crash) on the same file but it is only reading metadata, not reading the image data.  A portion of what it reports is:

>   Image Structure Metadata:
>   COMPRESSION=YCbCr JPEG
>   INTERLEAVE=PIXEL
>   JPEGTABLESMODE=3
>   JPEG_QUALITY=65
>   SOURCE_COLOR_SPACE=YCbCr

## Operating system

macOS 12.0.1
CPU = M1 Pro (arm64)

## GDAL version and provenance

Compiled for arm64 (native for CPU)
MacPorts build of gdal @3.3.1_2+postgresql13+proj8
libgdal.29.dylib
$ gdalinfo --version
GDAL 3.3.1, released 2021/06/28

## Other Info

No problems with same file using QGIS 3.16.4 on macOS 10.13.6 (Intel) with gdal 3.2.1 (2020/12/29).

**Comment by bal-agates** [comment]
Forgot to mention no crash when the GeoTIFF is RGBA uncompressed or 255 indexed colortable.  So problem appears to be only when TIFF uses JPEG compression.  I do not understand the command line error reference to JPEGLib version (see top of crash log).  On my system I see.

```
/opt/local/lib/libjpeg.8.dylib:
   /opt/local/lib/libjpeg.8.dylib (compatibility version 8.0.0, current version 8.2.2)
   /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.0.0)
```

This is provided by MacPort `libjpeg-turbo @2.1.1_0 (active)`

**Comment by rouault** [comment]
The cause is indeed "JPEGLib:Wrong JPEG library version: library is 62, caller expects 80"
It means that GDAL was compiled against the headers of its internal libjpeg library (which is libjpeg 6b / version 62), but is also linked against libjpeg 8, likely indirectly through another of its dependencies
Perhaps the libjpeg-turbo headers were not available at the time GDAL was built and thus it selected its internal libjpeg versio ?
GDAL should be rebuilt with ./configure  --with-jpeg=/opt/local

**Comment by bal-agates** [comment]
My gdal library was built with 
```
--with-libtiff=internal
--with-jpeg=internal
--with-proj=${prefix}/lib/proj8
```
It appears that the proj8 library depends on libtiff.5.dylib
```
/opt/local/lib/proj8/lib/libproj.22.dylib:
        /opt/local/lib/proj8/lib/libproj.22.dylib (compatibility version 25.0.0, current version 25.0.0)
        /opt/local/lib/libsqlite3.0.dylib (compatibility version 9.0.0, current version 9.6.0)
        /opt/local/lib/libtiff.5.dylib (compatibility version 13.0.0, current version 13.0.0)
        /opt/local/lib/libcurl.4.dylib (compatibility version 12.0.0, current version 12.0.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.0.0)
        /usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1200.3.0)
```
And libtiff.5.dylib depends on libjpeg.8.dylib
```
/opt/local/lib/libtiff.5.dylib:
        /opt/local/lib/libtiff.5.dylib (compatibility version 13.0.0, current version 13.0.0)
        /opt/local/lib/libzstd.1.dylib (compatibility version 1.0.0, current version 1.5.0)
        /opt/local/lib/liblzma.5.dylib (compatibility version 8.0.0, current version 8.5.0)
        /opt/local/lib/libjpeg.8.dylib (compatibility version 8.0.0, current version 8.2.2)
        /opt/local/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.0.0)
```

Another problem was that MacPorts was installing a prebuilt binary rather than recompiling.  So I cannot be certain what was available when that was configured.  I am assuming it was built with the same recipe.  Rebuilding gdal from source with
```
--with-libtiff=/opt/local
--with-jpeg=/opt/local
```
appears to have fixed my initial issue.  Thanks.  You can close this issue.

I will need to think about how to prevent this problem in a more general way.
