### ISSUE TITLE
GEO_TIFF  With MERCATOR_2SP From Hydrographic office not placed correctly

### ISSUE THREAD

**Issue by richy46** [OSGeo/gdal#4958]
Dear All, 
We have a Geo tiff with nautical chart info that is not placed correctly. Due to copyrights I can not provide the original tiff itself but I removed it's contents while the meta keys stayed intact. So it is still representative. 

When I run GDAL info on it it gives the printout as seen below.
And of course the warning 1 is noticed by me.

When I open it in QGIS it shows on the wrong spot (too far north).
 
Now the question is can this be fixed? And is there an alternative proj4 string that can be used to place this tiff on the correct location?

Thank you all,
Rich

[JERSEY.zip](https://github.com/OSGeo/gdal/files/7666950/JERSEY.zip)
[Screenshot of QGIS.zip](https://github.com/OSGeo/gdal/files/7666952/Screenshot.of.QGIS.zip)

C:\OSGeo4W64\bin>gdalinfo "c:\temp\JERSEY.tif"
Driver: GTiff/GeoTIFF
Files: c:\temp\JERSEY.tif
Size is 3841, 5545
Warning 1: Mercator projection should not define both StdParallel1 and ScaleAtNatOrigin.  Using StdParallel1 and ignoring ScaleAtNatOrigin.
Coordinate System is:
PROJCRS["Mercator",
    BASEGEOGCRS["WGS 84",
        DATUM["World Geodetic System 1984",
            ELLIPSOID["WGS 84",6378137,298.257223563,
                LENGTHUNIT["metre",1]]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433]],
        ID["EPSG",4326]],
    CONVERSION["Mercator (variant B)",
        METHOD["Mercator (variant B)",
            ID["EPSG",9805]],
        PARAMETER["Latitude of 1st standard parallel",51,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8823]],
        PARAMETER["Longitude of natural origin",0,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["False easting",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["easting",east,
            ORDER[1],
            LENGTHUNIT["metre",1,
                ID["EPSG",9001]]],
        AXIS["northing",north,
            ORDER[2],
            LENGTHUNIT["metre",1,
                ID["EPSG",9001]]]]
Data axis to CRS axis mapping: 1,2
Origin = (-346602.939268003043253,6427637.617659794166684)
Pixel Size = (47.574182306760456,-47.573743065766408)
```

**Comment by jratike80** [comment]
Please send your question to gdal-dev mailing list.

> 
> IMPORTANT: Do NOT use GitHub to post any questions or support requests!
>            They will be closed immediately and ignored.

**Comment by richy46** [comment]
Hello jratike80,
I admit your commitment to keep this clean but this is a bug until proven otherwise IMO.

**Comment by jratike80** [comment]
Let's discuss about it in the mailing list.

**Comment by richy46** [comment]
ok, i'll repost there, cheers
