### ISSUE TITLE
Saving a WarpedVRT to disk via GDALSetDescription is broken at relativeToVRT

### ISSUE THREAD

**Issue by sgillies** [OSGeo/gdal#4983]
The default seems to be `relativeToVRT="0"` but the path is a relative path, not an absolute path, lacking a leading `/`.

Perhaps related: GDALCreateCopy from a in-memory WarpedVRT to a GTiff results in an empty file .

**Comment by rouault** [comment]
More details would be welcome: are the file name of the sources absolute or relative, and the name passed to SetDescription() absolute or relative ? (examples of actual names would help)
Can you replicate with gdalwarp -of VRT ?

**Comment by sgillies** [comment]
Yes, details coming soon. I aimed this ticket for myself but forgot to say that :)

**Comment by rouault** [comment]
is this issue still valid ?

**Comment by sgillies** [comment]
Unless there have been any fixes made that I didn't see. I haven't done any work on this over the holiday break.

**Comment by rouault** [comment]
@sgillies I suspect https://github.com/OSGeo/gdal/pull/5239 might help

**Comment by rouault** [comment]
Closing. Re-open if issue persists

**Comment by sgillies** [comment]
I saw on gdal-dev that the VRT's XML text is also exposed in a particular metadata domain? That might be even better for my use case.

**Comment by rouault** [comment]
> in a particular metadata domain?

yes, "xml:VRT". Now documented at https://gdal.org/drivers/raster/vrt.html
