### ISSUE TITLE
Can I ask a question? In the process of converting CAD to Shapefile, some coordinates have been offset, I know the amount of offset, so I need to add the offset to the coordinates that have been offset during the conversion process, does GDAL now have this function? I read the documentation as if there were no similar features.

### ISSUE THREAD

**Issue by TTnTTT** [OSGeo/gdal#4989]
## Expected behavior and actual behavior.

Thank you in advance for your help

## Steps to reproduce the problem.

For example (please modify !!!): "gdalinfo myfile"

## Operating system

Windows11

## GDAL version and provenance

For example (please modify !!!): the 2.2.3 version from ubuntugis-unstable PPA

**Comment by jratike80** [comment]
Please send questions to the gdal-dev mailing list.
