### ISSUE TITLE
Allow output to stdout when using e.g. GMT/OGR

### ISSUE THREAD

**Issue by anbj** [OSGeo/gdal#4993]
What is the rationale that output to `stdout` (`/vsistdout/`) is not possible when using e.g. the GMT/OGR driver?

```
$ ogr2ogr -sql "select * from prlAreaCurrent" -F GMT /vsistdout/ prlAreaCurrent.gpkg
# @VGMT1.0 @GPOLYGON
# REGION_STUB                                                             
# @Je4230
# @Jp"+proj=longlat +ellps=intl +no_defs"
# @Jw"GEOGCS[\"ED50\",DATUM[\"European_Datum_1950\",SPHEROID[\"International 1924\",6378388,297,AUTHORITY[\"EPSG\",\"7022\"]],AUTHORITY[\"EPSG\",\"6230\"]],PRIMEM[\"Greenwich\",0,AUTHORITY[\"EPSG\",\"8901\"]],UNIT[\"degree\",0.0174532925199433,AUTHORITY[\"EPSG\",\"9122\"]],AXIS[\"Latitude\",NORTH],AXIS[\"Longitude\",EAST],AUTHORITY[\"EPSG\",\"4230\"]]"
ERROR 6: Read or update mode not supported on /vsistdout
ERROR 1: Terminating translation prematurely after failed
translation from sql statement.
```

This is basically a script, dumping all the data in the geopackage file to a GMT/OGR file.

It would be very beneficial if this was possible.
I'm using the GMT/OGR driver to output data in a script, generating a movie with > 20.000 frames. If `ogr2ogr` allowed me to send output to `stdout` I would not need to write > 20.000 temporary files to disk, but instead pipe directly to the plotting utility.

Also something, not quite related, that I found interesting:

```
$ time ogr2ogr -dialect indirect_sqlite -sql "select st_buffer(st_transform(geom, 32632),4000) as geomerfds from prlAreaCurrent WHERE geom IS NOT NULL" -F GMT temp.gmt prlAreaCurrent.gpkg

real 0m0.916s
user 0m0.881s
sys 0m0.032s
```
```
$ time ogr2ogr -sql "select st_buffer(st_transform(geom, 32632),4000) as geomerfds from prlAreaCurrent WHERE geom IS NOT NULL" -F GMT temp2.gmt prlAreaCurrent.gpkg

real 0m6.888s
user 0m6.271s
sys 0m0.617s
```

Using the `-dialect indirect_sqlite` is much faster (7.5x faster) than using the _native SQL dialect_ (as I would assume is being used as per description in https://gdal.org/user/sql_sqlite_dialect.html). On the man page, it also says that using `-dialect indirect_sqlite` should be avoided : _This should be used only when necessary, since going through the virtual table mechanism might affect performance._ The opposite seems to be the case. Is this due to better plumbing in the `gdal` machinery, and/or outdated documentation?

**Comment by rouault** [comment]
> What is the rationale that output to `stdout` (`/vsistdout/`) is not possible when using e.g. the GMT/OGR driver?

The driver needs to be able to seek backward to the file to update the "# REGION_STUB" placeholder with the real bounding box of the layer ("# @Rminx/maxx/miny/maxy). I've no idea if it is a mandatory keyword or no. Could you try in a valid .gmt file to replace the line starting with "# @R" by "# REGION_STUB" and see if that works ? If so, we could probably make the driver more tolerant.

> Using the -dialect indirect_sqlite is much faster 

On first thought, that's weird indeed. But that should be filed in a separate ticket and with a input file to reproduce.

**Comment by anbj** [comment]
I will test, but I'm almost certain that a 'valid' `@R` is not mandatory; the only mandatory field is `# @VGMT1.0`; _Parsing of the OGR/GMT format is only activated if the version code-sequence has been found._ (https://docs.generic-mapping-tools.org/dev/cookbook/ogrgmt-format.html#format-version).

**Comment by anbj** [comment]
Replacing the line starting with "# @r" by "# REGION_STUB" works fine.
It also works fine if you completely remove the `# @r`-line.
Tested in GMT and QGIS.
