### ISSUE TITLE
gdalwarp: COG output to Eckert IV adds spurious data to out-of-projection areas

### ISSUE THREAD

**Issue by pnuu** [OSGeo/gdal#4997]
## Expected behavior and actual behavior.

Resampling an [image](https://www.dropbox.com/s/2n5zx54xeo67zid/20211214_1200_GOES-16_geos_truecolor_with_ash.tif?dl=0) in `geos` projection to Eckert IV adds some spurious data to the non-valid areas of the image, see the level-3 overview (`test-3.png` from `convert test.tif test.png`). These appear only with `-of COG`, using `-co tiled=yes` and `gdaladdo test.tif 2 4 8 16` produces a clean image.

![test-3](https://user-images.githubusercontent.com/3170788/146139973-a4629ede-35a7-4e65-971b-fcad516e6091.png)

## Steps to reproduce the problem.

`gdalwarp -co compress=deflate -t_srs ESRI:54012 -tr 2000 2000 -te -14692011.430 -8313010.558165222 573988.570 8313010.558165222 -of COG 20211214_1200_GOES-16_geos_truecolor_with_ash.tif test.tif`

## Operating system

Ubuntu 20.40.3.

## GDAL version and provenance

GDAL 3.3.3 from conda-forge.

**Comment by jratike80** [comment]
I can confirm with GDAL 3.4 on Windows. Did you also get these messages :
```
Using band 4 of source image as alpha.
ERROR 1: tolerance condition error
```
I do not know 

I tried COG without overviews `-co overviews=none` but even then the COG result has some artifacts, though not as many and in different place.

**Comment by pnuu** [comment]
The full output I get with `3.3.3` is
```
Using band 4 of source image as alpha.
ERROR 1: Point outside of projection domain
ERROR 1: Point outside of projection domain
ERROR 1: Point outside of projection domain
ERROR 1: Point outside of projection domain
Creating output file that is 7633P x 8313L.
0...10...20...30...40...50...60...70...80...90...100 - done.
```

I also see the difference when using `-co overviews=none`.

**Comment by rouault** [comment]
"Minimum" reproducer showing the code path taken with COG output, but which isn't COG specific, but rather an issue with the warped VRT mechanism used underneath:
```
gdalwarp -t_srs ESRI:54012 -tr 4000 4000  -te -14692011.430 -8313010.558165222 573988.570 8313010.558165222  20211214_1200_GOES-16_geos_truecolor_with_ash.tif tmp.vrt
gdal_translate tmp.vrt out.tif  -co tiled=yes
```

**Comment by pnuu** [comment]
Just now found time to test, and `3.4.1` fixes the issue. Thanks a lot!
