### ISSUE TITLE
C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x86\\cl.exe' failed with exit status 2

### ISSUE THREAD

**Issue by Clives-online** [OSGeo/gdal#5012]
Installation throws an error message.

## Steps to reproduce the problem.

GDAL-3.3.3.win-amd64-py3.8.msi

## Operating system
Windows 10 64bit

## GDAL version and provenance
GDAL-3.3.3.win-amd64-py3.8

## ISSUE
[gdal.txt](https://github.com/OSGeo/gdal/files/7728184/gdal.txt)

    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x86\\cl.exe' failed with exit status 2

**Comment by rouault** [comment]
This is a usage issue. Admitedly building the bindings on Windows isn't always the easiest task.
if you use GDAL-3.3.3.win-amd64-py3.8.msi, the bindings are already generated, so you don't need to build them from source
if you build the bindings from source, you can take inspiration from a CI job like https://github.com/OSGeo/gdal/blob/master/.github/workflows/windows_build.yml#L226
I'm not sure that on Windows it is possible to build only the bindings from the pip package, without being in a full GDAL source tree

**Comment by rouault** [comment]
you can also use Conda to get GDAL and its Python bindings; https://gdal.org/download.html#conda
