### ISSUE TITLE
CMAKE : link fails when using LIBTIFF

### ISSUE THREAD

**Issue by chacha21** [OSGeo/gdal#5018]
Visual Studio 2019, Windows 7 64b
With the experimental CMake build

When TIFF_INCLUDE_DIR and TIFF_LIBRARY_DEBUG/RELEASED are filled correctly, all the compilation part of gdal is properly achieved.
But the linker fails at the end because the tiff[_d].lib is not referenced in the additional libraries of the gdal vcxproj.

Adding that reference manually in the gdal project properties does fix it and the link step will succeed.

It might have worked if the libtiff was a static build linked to proj[_d].lib (I have not checked that), but in my case the libtiff is a shared build.

**Comment by rouault** [comment]
I don't reproduce this with Windows builds against dependencies provided by Conda or vcpkg and "cmake --build . --config Release" . You'll have to provide exact reproduction details

**Comment by chacha21** [comment]
Some hints of my build :

CMakeGUI 3.22.1 under Windows 7 64b, targetting Visual Studio 2019 x64 with native compilers

I have external builds of libgeotiff, libtiff, proj, all performed by CMake

Here are attached various CMake outputs

[CMakeCache.txt](https://github.com/OSGeo/gdal/files/7750595/CMakeCache.txt)
[CMakeOutput.log](https://github.com/OSGeo/gdal/files/7750600/CMakeOutput.log)
[CMakeError.log](https://github.com/OSGeo/gdal/files/7750601/CMakeError.log)

**Comment by rouault** [comment]
In your CMakeCache.txt, I see
```
//Use internal libgeotiff copy (if set to ON, has precedence over
// GDAL_USE_GEOTIFF)
GDAL_USE_LIBGEOTIFF_INTERNAL:BOOL=ON

GDAL_USE_LIBTIFF_INTERNAL:BOOL=ON
```
so it is expected that you don't see libtiff.lib in the dependencies.
Unset those variables, or set them to OFF, and you should see your external libs used

**Comment by rouault** [comment]
is it still valid ?

**Comment by chacha21** [comment]
Indeed, unchecking GDAL_USE_LIBGEOTIFF_INTERNAL in the CMake parameters will fix the problem.
