### ISSUE TITLE
Build for arm64 fails: png_do_expand_palette_rgba8_neon is lost from libpng

### ISSUE THREAD

**Issue by alexey-pelykh** [OSGeo/gdal#5028]
Entire `arm` folder is missing https://github.com/glennrp/libpng/tree/a37d4836519517bdce6cb9d956092321eca3e73b/arm and that would fail in case `PNG_ARM_NEON_IMPLEMENTATION` happens to be undefined (and thus automatically defined).

**Comment by rouault** [comment]
build issues with internal libpng and ARM have been fixed in GDAL 3.3

**Comment by alexey-pelykh** [comment]
Odd, since I'm using 3.4.0 and it fails with internal libpng on ARM

**Comment by rouault** [comment]
The fix was in 1c719a864232daf58b799fbb2da785f3f9b2d579 (actually this was 3.4.0 not 3.3.0)
