### ISSUE TITLE
ogr2ogr - Disk I/O error generating gpkg using azure blob storage as output source

### ISSUE THREAD

**Issue by Greginator** [OSGeo/gdal#5031]
I am trying to generate gpkg files from a table in a managed postgres instance hosted on azure and trying to store the gpkg directly in the blob store using vsiaz. Doing so works properly for small geopackages however it consistently falls over around 25410000 features with a disk I/O error. 

I am using the osgeo/gdal:ubuntu-full-latest container image (GDAL 3.4.0dev-d2f9067ffb15e593e9b826ca939dbd183636c780) to run ogr2ogr, however it doesn't seem to make a difference whether I use ogr2ogr locally on my machine, in a container on my machine, or in a container hosted on azure container instances.

## Expected behavior and actual behavior.

I expected to be able to create a geopackage stored on the blob store, instead I receive the following stack trace.

```
ERROR 1: failed to execute insert : disk I/O error
ERROR 1: Unable to write feature 25411295 from layer sql_statement.
ERROR 1: Terminating translation prematurely after failed
translation from sql statement.
ERROR 1: failed to execute insertion in RTree : disk I/O error
ERROR 1: sqlite3_exec(ROLLBACK) failed: cannot rollback - no transaction is active
```

## Steps to reproduce the problem.

- execute the following command on a gdal container with the prerequisite azure resources set up.

`ogr2ogr --config AZURE_STORAGE_CONNECTION_STRING "<blob store connection string>" --config AZURE_STORAGE_ACCOUNT "<blob store name>" --config AZURE_STORAGE_ACCESS_KEY "<blob store access key>" --config CPL_VSIL_USE_TEMP_FILE_FOR_RANDOM_WRITE "YES" -nln "<table name>" -f GPKG -append /vsiaz/myblobstorecontainer/mygeopackage.gpkg PG:"host=<postgres url> user=<username> dbname=<dbname> password=<password>" -sql "select * from <table name>"
`

## Operating system

osgeo/gdal:ubuntu-full-latest container image

## GDAL version and provenance

GDAL 3.4.0dev-d2f9067ffb15e593e9b826ca939dbd183636c780

## Full stack trace

```
ERROR 1: Only read-only mode is supported for /vsicurl
ERROR 1: sqlite3_exec(x-ms-date: Thu, 23 Dec 2021 00:12:24 GMT) failed: near "4": syntax error
Warning 1: Multi-column primary key in 'bld_fts_bldprt' detected but not supported.
ERROR 1: failed to execute insert : disk I/O error
ERROR 1: Unable to write feature 25413453 from layer sql_statement.
ERROR 1: Terminating translation prematurely after failed
translation from sql statement.
ERROR 1: failed to execute insertion in RTree : disk I/O error
ERROR 1: sqlite3_exec(ROLLBACK) failed: cannot rollback - no transaction is active
```

**Comment by rouault** [comment]
what is the file size when it starts to fail ?

**Comment by Greginator** [comment]
49.2 GiB is the size of the output file in the blob store.

**Comment by rouault** [comment]
I see you use the -append flag, which implies the geopackage file already exists on /vsiaz/, but this isn't going to work with CPL_VSIL_USE_TEMP_FILE_FOR_RANDOM_WRITE=YES which only works when creating a new file (at least as implemented currently). But I'm not sure that's the cause of the error here. It looks like the GeoPackage driver would try to read something from the network while using the local temp file (the "sqlite3_exec(x-ms-date: Thu, 23 Dec 2021 00:12:24 GMT)" message is quite intriguing)
Does using a local geopackage target file work ?

**Comment by Greginator** [comment]
Yes, I have been able to write complete geopackages to the disk on a dedicated Ubuntu virtual machine in Azure. (Azure container instances which I was using to run the gdal container can't have non-networked storage attached)

**Comment by rouault** [comment]
> Azure container instances which I was using to run the gdal container can't have non-networked storage attached

aren't you running into a 50 GB limit on temporary storage then ?

**Comment by Greginator** [comment]
I have also encountered this issue using a dedicated VM on azure to vsiaz to blob store. ACI is serverless computing I don't believe this is a storage issue with ACI, it could be something to do with the blob store but I can't find anything in the documentation that suggests there's a 50gb limit or why files would fall over at that size. All documentation I can find says there's a 200gb limit.


I removed the append flag and ran it again targetting a new file name.

command:
`ogr2ogr --config AZURE_STORAGE_CONNECTION_STRING "<blob store connection string>" --config AZURE_STORAGE_ACCOUNT "<blob store name>" --config AZURE_STORAGE_ACCESS_KEY "<blob store access key>" --config CPL_VSIL_USE_TEMP_FILE_FOR_RANDOM_WRITE "YES" -nln "<table name>" -f GPKG /vsiaz/myblobstorecontainer/mygeopackage2.gpkg PG:"host=<postgres url> user=<username> dbname=<dbname> password=<password>" -sql "select * from <table name>" `

output: 
```
ERROR 1: sqlite3_exec(x-ms-date: Thu, 23 Dec 2021 13:21:57 GMT) failed: near "7": syntax error
Warning 1: Multi-column primary key in 'bld_fts_bldprt' detected but not supported.
ERROR 1: failed to execute insert : disk I/O error
ERROR 1: Unable to write feature 25413667 from layer sql_statement.
ERROR 1: Terminating translation prematurely after failed
translation from sql statement.
ERROR 1: failed to execute insertion in RTree : disk I/O error
ERROR 1: sqlite3_exec(ROLLBACK) failed: cannot rollback - no transaction is active
```

Output gpkg size was 49.2gb.

**Comment by Greginator** [comment]
Hi, after you mentioned about it being a container specific issue I ran it again using a dedicated VM in azure with ubuntu 20.04 and the PPA version of ogr2ogr.

`ogrinfo --version
GDAL 3.3.2, released 2021/09/01
free(): invalid pointer
Aborted (core dumped)
`

running the following command:

`ogr2ogr --config AZURE_STORAGE_CONNECTION_STRING "<blob store connection string>" --config AZURE_STORAGE_ACCOUNT "<blob store name>" --config AZURE_STORAGE_ACCESS_KEY "<blob store access key>" --config CPL_VSIL_USE_TEMP_FILE_FOR_RANDOM_WRITE "YES" -nln "<table name>" -f GPKG /vsiaz/myblobstorecontainer/geopackagefromvm.gpkg PG:"host=<postgres url> user=<username> dbname=<dbname> password=<password>" -sql "select * from <table name>"`

Gives the output:
```
ERROR 1: sqlite3_exec(x-ms-date: Fri, 07 Jan 2022 15:36:45 GMT) failed: near "5": syntax error
Warning 1: Multi-column primary key in 'bld_fts_bldprt' detected but not supported.
ERROR 1: failed to execute insert : disk I/O error
ERROR 1: Unable to write feature 12889448 from layer sql_statement.
ERROR 1: Terminating translation prematurely after failed
translation from sql statement.
ERROR 1: failed to execute insertion in RTree : disk I/O error
ERROR 1: sqlite3_exec(ROLLBACK) failed: cannot rollback - no transaction is active
free(): invalid pointer
Aborted (core dumped)
```
This time the geopackage size was 24.95 GB.
The `free(): invalid pointer
Aborted (core dumped)` at the very end in a red herring as that shows up on ogrinfo --version also.

This is not an issue unique to containers I have experienced this same behaviour on VMs before trying to work around it.

**Comment by rouault** [comment]
> The `free(): invalid pointer Aborted (core dumped)` at the very end in a red herring as that shows up on ogrinfo --version also.

that's definitely something wrong with your GDAL build (but probably not the cause of your issue): check with ldd on libgdal.so that you don't have 2 different PROJ versions linked to GDAL. This can happen for example if libspatialite or libgeotiff link to system PROJ and GDAL to a custom PROJ version.

**Comment by Greginator** [comment]
That would make sense, I had installed gdal on the VM prior to the test via the ubuntu package manager, then realised that the version they provide was out of date and installed it via PPA.

**Comment by Greginator** [comment]
I have doen further research on this after realising that the VM consistently would fall over around 24.95gb, which seemed odd to me when ACI would all over at just under 50gb.

The VM had a disk size of 30gb, upon googling around ACI and 50gb I found [this](https://www.youtube.com/watch?v=7QVAXZPNaMI) which said ACI has 50gb of space which lines up with the size I was finding the gpkg being created.

When I ran the command I posted earlier on the VM, cd into a new disk I manually attached of 128gb it was able to compelete with a gpkg size of 95gb. This has solved my issue of how I can generate large enough geopackages but created a new problem: Is there a way to generate a gpkg and insert it into blob store without it being limited by the size of the disk on the machine executing the command?
I assume the `CPL_VSIL_USE_TEMP_FILE_FOR_RANDOM_WRITE` flag is what causes this behaviour but when I remove it the ogr2ogr command errors
`ERROR 1: w+ not supported for /vsiaz, unless CPL_VSIL_USE_TEMP_FILE_FOR_RANDOM_WRITE is set to YES`

Is there some way I can perform large ogr2ogr commands targetting the blob store without encountering this or is this a technical limitation to how vsiaz works?

**Comment by rouault** [comment]
> Is there some way I can perform large ogr2ogr commands targetting the blob store without encountering this or is this a technical limitation to how vsiaz works?

Writing a GeoPackage or any SQLite3 file requires read-write random access, not just sequential write access. Azure and other similiar blob storages aren't ideal for read-write random. In some situations it might be perhaps implemented (I don't believe it would work for Azure as we use append blobs if I recall well) but even if possible, performance would probably suffer

**Comment by Greginator** [comment]
So am I correct in saying in order to avoid this error from occuring I should make sure there is always enough empty disk space for the final gpkg size? For example, I could not run two ogr2ogr operations simultaneously to generate two 90gb geopackages with only a 128gb disk.

> Writing a GeoPackage or any SQLite3 file requires read-write random access, not just sequential write access. 

Could this problem then be avoided using a different target file type (e.g. csv)?

**Comment by rouault** [comment]
> So am I correct in saying in order to avoid this error from occuring I should make sure there is always enough empty disk space for the final gpkg size?

yes

> Could this problem then be avoided using a different target file type (e.g. csv)?

the CSV driver indeed supports sequential writing mode
