### ISSUE TITLE
[DWG] : enhancement , expose block attributes as feature fields

### ISSUE THREAD

**Issue by lchevallier69** [OSGeo/gdal#5035]
## Expected behavior and actual behavior.
It would be fine to expose block attributes as feature attribute, this behavior can allow filters and a much more simple data conversion, target table could contains attributes stored in blocks. So far, with the actual version, only a concatened string value is available, no structured.

In fact, this behavior could be activate with a specific option, I propose something like : DWG_ATTRIBUTES_AS_VALUES=TRUE.

Block attributes should be exposed as feature attributes values.

**Comment by lchevallier69** [comment]
a exemple of implementation, to be discussed :

https://github.com/lchevallier69/gdal/commit/c2a581c497c07d868da1b49a9cd6f9b028399f1e

**Comment by rouault** [comment]
> a exemple of implementation, to be discussed :
> 
> [lchevallier69@c2a581c](https://github.com/lchevallier69/gdal/commit/c2a581c497c07d868da1b49a9cd6f9b028399f1e)

Seems reasonable as material for a pull request, with some doc in doc/source/drivers/vector/dwg.rst

**Comment by lchevallier69** [comment]
@rouault i've done the doc and PR, thank you for remarks
