### ISSUE TITLE
Is it meant to prefix geometry column name as "_WKT"

### ISSUE THREAD

**Issue by S-Venkat-S** [OSGeo/gdal#5045]
https://github.com/OSGeo/gdal/blob/19f4833c3167106e288a030c30da26f2afa07f59/ogr/ogrsf_frmts/csv/ogrcsvlayer.cpp#L602

The "_WKT" condition in this line forces to write the column names with prefix as "_WKT", is it necessary.
So far, i am using WKT_POINT as a standard.

**Comment by rouault** [comment]
The _WKT condition is mostly an internal non-documented feature used for testing purposes. The documented way at https://gdal.org/drivers/vector/csv.html is to create a .csvt file with geometry columns with WKT content being tagged with "WKT"
