### ISSUE TITLE
gdalwarp Error 6: Coordinate operations error for EPSG:6394/NAD83-Alaska Zone 1

### ISSUE THREAD

**Issue by shihlinlu** [OSGeo/gdal#5047]
## Expected behavior and actual behavior.

I expected to be able to crop a raster file in the NAD83-Alaska Zone 1 CRS using `gdalwarp` without errors in the command line, but it returns an error message before the process completes. The cropped raster file renders without error after validating it in QGIS or ArcGIS Pro, but I think there may be a bug within `gdalwarp` for this particular CRS.

```
ERROR 6: Cannot find coordinate operations from `EPSG:6394' to `BOUNDCRS[SOURCECRS[GEOGCRS["NAD83(2011)",DATUM["NAD83 (National Spatial Reference System 2011)",ELLIPSOID["GRS 1980",6378137,298.257222101004,LENGTHUNIT["metre",1]],ID["EPSG",1116]],PRIMEM["Greenwich",0,ANGLEUNIT["degree",0.0174532925199433,ID["EPSG",9122]]],CS[ellipsoidal,2],AXIS["geodetic latitude (Lat)",north,ORDER[1],ANGLEUNIT["degree",0.0174532925199433,ID["EPSG",9122]]],AXIS["geodetic longitude (Lon)",east,ORDER[2],ANGLEUNIT["degree",0.0174532925199433,ID["EPSG",9122]]]]],TARGETCRS[GEOGCRS["WGS 84",DATUM["World Geodetic System 1984",ELLIPSOID["WGS 84",6378137,298.257223563,LENGTHUNIT["metre",1]]],PRIMEM["Greenwich",0,ANGLEUNIT["degree",0.0174532925199433]],CS[ellipsoidal,2],AXIS["latitude",north,ORDER[1],ANGLEUNIT["degree",0.0174532925199433]],AXIS["longitude",east,ORDER[2],ANGLEUNIT["degree",0.0174532925199433]],ID["EPSG",4326]]],ABRIDGEDTRANSFORMATION["Transformation from NAD83(2011) to WGS84",METHOD["Position Vector transformation (geog2D domain)",ID["EPSG",9606]],PARAMETER["X-axis translation",0,ID["EPSG",8605]],PARAMETER["Y-axis translation",0,ID["EPSG",8606]],PARAMETER["Z-axis translation",0,ID["EPSG",8607]],PARAMETER["X-axis rotation",0,ID["EPSG",8608]],PARAMETER["Y-axis rotation",0,ID["EPSG",8609]],PARAMETER["Z-axis rotation",0,ID["EPSG",8610]],PARAMETER["Scale difference",1,ID["EPSG",8611]]]]'
Creating output file that is 185799P x 213951L.
Processing rw-11-29a.tif [1/1] : 0ERROR 6: Cannot find coordinate operations from `EPSG:6394' to `BOUNDCRS[SOURCECRS[GEOGCRS["NAD83(2011)",DATUM["NAD83 (National Spatial Reference System 2011)",ELLIPSOID["GRS 1980",6378137,298.257222101004,LENGTHUNIT["metre",1]],ID["EPSG",1116]],PRIMEM["Greenwich",0,ANGLEUNIT["degree",0.0174532925199433,ID["EPSG",9122]]],CS[ellipsoidal,2],AXIS["geodetic latitude (Lat)",north,ORDER[1],ANGLEUNIT["degree",0.0174532925199433,ID["EPSG",9122]]],AXIS["geodetic longitude (Lon)",east,ORDER[2],ANGLEUNIT["degree",0.0174532925199433,ID["EPSG",9122]]]]],TARGETCRS[GEOGCRS["WGS 84",DATUM["World Geodetic System 1984",ELLIPSOID["WGS 84",6378137,298.257223563,LENGTHUNIT["metre",1]]],PRIMEM["Greenwich",0,ANGLEUNIT["degree",0.0174532925199433]],CS[ellipsoidal,2],AXIS["latitude",north,ORDER[1],ANGLEUNIT["degree",0.0174532925199433]],AXIS["longitude",east,ORDER[2],ANGLEUNIT["degree",0.0174532925199433]],ID["EPSG",4326]]],ABRIDGEDTRANSFORMATION["Transformation from NAD83(2011) to WGS84",METHOD["Position Vector transformation (geog2D domain)",ID["EPSG",9606]],PARAMETER["X-axis translation",0,ID["EPSG",8605]],PARAMETER["Y-axis translation",0,ID["EPSG",8606]],PARAMETER["Z-axis translation",0,ID["EPSG",8607]],PARAMETER["X-axis rotation",0,ID["EPSG",8608]],PARAMETER["Y-axis rotation",0,ID["EPSG",8609]],PARAMETER["Z-axis rotation",0,ID["EPSG",8610]],PARAMETER["Scale difference",1,ID["EPSG",8611]]]]'
```

## Steps to reproduce the problem.

1. Prepare an input GeoTIFF in NAD83 Alaska Zone 1/EPSG:6394 CRS: https://epsg.io/6394
2. Prepare a shapefile in NAD83 Alaska Zone 1
3. Run gdalwarp command: ```gdalwarp -of GTiff -cutline [shapefile] -crop_to_cutline [input-tif] [output-tif] -wo NUM_THREADS=ALL_CPUS -co BIGTIFF=YES -co TILED=YES -co COMPRESS=JPEG -multi```
4. Coordinate Operations Error message log appears in the terminal
5. The gdalwarp process still runs and an output tif is created, but the message log is very confusing and conflicting

## Operating system

Ubuntu 20.04.3 LTS

## GDAL version and provenance

3.0.2

**Comment by rouault** [comment]
I believe this might be a bug of the PROJ 6.3.1 version used by Ubuntu 20.04. I can't reproduce with more recent PROJ versions

**Comment by shihlinlu** [comment]
@rouault Thanks for the feedback. I saw a related issue with PROJ for Ubuntu 20.04 here: https://issueexplorer.com/issue/OSGeo/PROJ/2794. Should I use a different version of Ubuntu? I installed `gdal` through conda. I'm weary if upgrading PROJ with conda forge is going conflict with the existing 6.3 version.

**Comment by rouault** [comment]
which version of PROJ did you get through Conda ?

**Comment by shihlinlu** [comment]
@rouault I did not install PROJ through Conda. I downloaded `gdal` version 3.0.2 through Conda, which I'm assuming is when PROJ was installed as a dependency. I see there is a newer version of gdal 3.4.0, but will wait to upgrade until my current `gdalwarp` commands complete.

**Comment by shihlinlu** [comment]
@rouault I was not able to download the gdal 3.4.0 through conda: https://anaconda.org/conda-forge/gdal. It keeps defaulting to version 3.0.2. I'm not sure if this is a limitation of the Ubuntu version.
