### ISSUE TITLE
gdal_translate aborts without error when converting form a .vrt with external mask

### ISSUE THREAD

**Issue by maphew** [OSGeo/gdal#5049]
## Expected behavior and actual behavior.

`gdal_translate` aborts after about 5% without error when converting form a .vrt with external mask (`filename.vrt.msk`).

## Steps to reproduce the problem.

_Note: I'm unsure if this is the minimal reproducible recipe and I don't have time to test more today. I just wanted to get this out of my head while still fresh. There may be aspects of the image files the vrt is referencing at play._ 

1. Create a .vrt referencing a geotiff on a different volume.
2. Create an external mask file with nearblack against original geotiff (`nearblack -o outfile.tif -setmask infile.tif`)
3. Copy/rename mask from `source\file.tif.msk` to `myvrt.vrt.msk`
4. `gdal_translate -of cog -co compress=lzw myvrt.vrt outcog.tif`

~~~
$ gdal_translate   -co compress=lzw   -co predictor=yes   -co bigtiff=yes   -of cog   SPOT6_ClearCk_RGB_150cm_02Oct2016_NAD_1983_Yukon_Albers.rgb-nir.vrt ..\deliverable\sft-2021-12-29\SPOT6_ClearCk_RGB_150cm_02Oct2016_NAD_1983_Yukon_Albers.rgb-nir.tif
Input file size is 47037, 51199
0.
~~~

5. Some time after progress counter emits 1st `.` gdal exits without any messages. In the output folder is a tif file of a few hundred kb and a `.msk.tmp` file.

Delete or move the `.vrt.msk` file out of the way and repeat step 4: the translation goes to 100% and the output file is complete and intact.

## Operating system

Microsoft Windows [Version 10.0.19041.1288]

## GDAL version and provenance

GDAL 3.4.0, released 2021/11/04, via QGIS installed with chocolatey.

**Comment by rouault** [comment]
Although it doesn't look directly related, it might be another symptom of https://github.com/OSGeo/gdal/issues/4932 that will get fixed to 3.4.1. If that still reproduce with that version, a precise reproduced might be needed

**Comment by rouault** [comment]
@maphew does it still apply ?

**Comment by maphew** [comment]
With 3.4.1 I am not able to reproduce the problem with a small sample (1.5MB source). I'm running the same test against full res source and will re-open if there's a problem. Thank you @rouault!
