### ISSUE TITLE
PDAL Raster Interpolation

### ISSUE THREAD

**Issue by shubham9436** [OSGeo/gdal#5050]
I have converted Point Cloud to Raster using PDAL. But, Geotiff generated through PDAL have huge holes/gaps in between them. 

How could I interpolate the generated Raster using GDAL tools? I have tried gdal_grid tool but it says the file format is not supported.
I have zipped the Geotiff file.

[dtm-b.zip](https://github.com/OSGeo/gdal/files/7792622/dtm-b.zip)

**Comment by jratike80** [comment]
Please send questions about how to use GDAL into gdal-dev mailing list.

> <!--
> IMPORTANT: Do NOT use GitHub to post any questions or support requests!
>            They will be closed immediately and ignored.
>
