### ISSUE TITLE
VectorTranslate does not return the right code when the geometryType is invalid

### ISSUE THREAD

**Issue by dthib** [OSGeo/gdal#5054]
## Expected behavior and actual behavior.

Hi !
I am using gdal VectorTranslate with python bindings in order to import a shapefile into postgis.

The following error is in the logs
ERROR: Geometry type (MultiPolygon) does not match column type (Polygon)
And I was able to fix it by specifying the geometryType.

However, when not adding the geometryType, I am surprised that the return code is ok (=1) whereas the error is in the log and the layer has not been created. I have activated gdal.UseExceptions(). Do I have to do something else to get an exception or a different code ?
Thanks

## Steps to reproduce the problem.

Use VectorTranslate to import a multipolygon shp into postgis without specifying geometryType to MULTIPOLYGON (ex: https://data.statistik.gv.at/data/OGDEXT_GEM_1_STATISTIK_AUSTRIA_20170101.zip)

`conn_string = f"PG:host={host} dbname={db} user={user} password={pwd} port=5432"
        dstDS = gdal.OpenEx(conn_string, gdal.OF_UPDATE | gdal.OF_VECTOR)
        translateCode = gdal.VectorTranslate(
            dstDS,
            f'{extractedPath}/STATISTIK_AUSTRIA_GEM_20170101.shp',
            format = "PostgreSQL",
            layerName = layerName,
            accessMode = "overwrite"
        )
        
        if translateCode is None or translateCode != 1:
            response["error_code"] = translateCode`

## Operating system

Gdal docker image based on andrejreznik/python-gdal:py3.10.0-gdal3.2.3 (Debian)

## GDAL version and provenance

Gdal docker image based on andrejreznik/python-gdal:py3.10.0-gdal3.2.3

**Comment by jratike80** [comment]
I can't say anything about the Python error, but as a hint when working with shapefiles you should be aware that shapefile can contain any mixture of polygons and multipolygons. If the first geometry is a polygon and PostGIS table is created so, there will be an error when the first multipolygon is found from the shapefile. Or vise versa. The right thing to do is either to create the PostGIS table with a generic geometry type "geometry", or to create the table as MultiPolygon and cast all geometries from shapefile into multipolygons. Ogr2ogr has an option "promote_to_multi" for that purpose.

**Comment by dthib** [comment]
Hi, thanks for the reply. Yes I have found the way to fix the error by specifiying the geometryType as mentioned but my message is more related to error handling: when not adding the geometryType, to my mind, the VectorTranslate is supposed to return an error. In my test, no error was returned and I had to find in logs what was happening. What do you think ?
Best

**Comment by dthib** [comment]
Thanks a lot Even, that's  great!
