### ISSUE TITLE
CMake: add support for Brunsli for MRF driver

### ISSUE THREAD

**Issue by rouault** [OSGeo/gdal#5068]
@lucianpls Want to tackle that ? (autoconf & nmake will be deprecated and eventually removed in future GDAL versions)

**Comment by lucianpls** [comment]
I'm still learning CMake, not doing very well with it. It will take me some time.

**Comment by rouault** [comment]
> I'm still learning CMake, not doing very well with it. It will take me some time.

you'll find tons of examples in cmake/modules/packages/  . the entry point to ask to detect a new dependency is in cmake/helpers/CheckDependentLibraries.cmake
