### ISSUE TITLE
AAIGrid driver does not support NODATA_value  null

### ISSUE THREAD

**Issue by AlisterH** [OSGeo/gdal#5095]
## Expected behavior and actual behavior.

12D allows to generate AAIGrid files setting NODATA_value as "null" rather than a number.  GDAL does not recognise these files, but it would be nice if it did.

I have no idea if software other than 12D supports AAIGrid files using "null", or if there is a specification that this violates...

Obviously the workaround is simple - replace "null" with a numerical NODATA_value, so feel free to close this ticket if you think it is appropriate to do so.

## Steps to reproduce the problem.

```
root@CivilWS02:/mnt/c/Processing#  gdalinfo test.asc
Driver: AAIGrid/Arc/Info ASCII Grid
Files: test.asc
Size is 95, 56
Coordinate System is `'
Origin = (415630.000000000000000,759380.000000000000000)
Pixel Size = (10.000000000000000,-10.000000000000000)
Corner Coordinates:
Upper Left  (  415630.000,  759380.000)
Lower Left  (  415630.000,  758820.000)
Upper Right (  416580.000,  759380.000)
Lower Right (  416580.000,  758820.000)
Center      (  416105.000,  759100.000)
Band 1 Block=95x1 Type=Float32, ColorInterp=Undefined
  NoData Value=-9999
root@CivilWS02:/mnt/c/Processing#  gdalinfo test_null.asc
ERROR 1: Couldn't find data values in ASCII Grid file.
gdalinfo failed - unable to open 'test_null.asc'.
```
[Example files.zip](https://github.com/OSGeo/gdal/files/7850819/Example.files.zip)

## Operating system

Any (I am using Windows, but tests with Ubuntu under WSL show OS is irrelevant).

## GDAL version and provenance

3.4.0 from QGIS on windows
2.4.2 from Ubuntu under WSL

**Comment by jratike80** [comment]
ArcMAP does not open the test_null.asc file so I think it is best to consider that it is invalid.

**Comment by rouault** [comment]
Such files are indeed dubious according to the format description at https://desktop.arcgis.com/en/arcmap/10.3/manage-data/raster-and-images/esri-ascii-raster-format.htm. That said I've queued https://github.com/OSGeo/gdal/pull/5098 to add support for them since it is relatively easy

**Comment by jratike80** [comment]
All right, maybe, if we do not unintentionally write out asc that does not open with ESRI software.

**Comment by rouault** [comment]
> if we do not unintentionally write out asc that does not open with ESRI software.

that's only on the read side. The null is remapped to the largest negative float32 / float64 value
