### ISSUE TITLE
[DWG] : Block Attributes exposition  should not take visibility into account for data conversion

### ISSUE THREAD

**Issue by lchevallier69** [OSGeo/gdal#5103]
The DWG driver should not filter attributes by visibility, in fact the current visibility in the DWG file should not implies the existence or not of a specific attribute, i think the visibility is only for display, and we loose a lot of informations when we dump a DWG. @jgrocha do you agree with that ? perhaps a new parameter could be set to ignore visibility

## Steps to reproduce the problem.

ogrinfo -al --config DWG_ATTRIBUTES TRUE --config DWG_INLINE_BLOCKS FALSE attribs2.dwg

## Operating system

All

## GDAL version and provenance

Master

**Comment by lchevallier69** [comment]
[attribs2.zip](https://github.com/OSGeo/gdal/files/7861362/attribs2.zip)
here a sample file

**Comment by jgrocha** [comment]
### Easy to implement

It is ok for me to ignore the visibility flag and output all attributes by default.

### Easy to implement

It is ok for me to ignore the visibility flag based on a configuration flag like `DWG_BLOCK_ATTRIBUTES`.

### More difficult to implement

If we want a more detailed information about block attributes, we could output for each attribute the value, the prompt and the visibility. Something like: 
```javascript
"ARM_NUMERO": { "value": "002", "prompt": "Numéro de l'armoire", "visibible": "true"}, "ARM_REF": { ... }, ...
```
Any option is good for me.

The example was taken from your DWG file.
![Capture](https://user-images.githubusercontent.com/163681/149305959-4fb52566-b6c2-4be9-ae15-e1aaf5d53798.PNG)
