### ISSUE TITLE
when using setting up configuration parameter CPL_DEBUG to ON, and setting up CPL_LOG with a file path with a space in it in Windows, it won t work

### ISSUE THREAD

**Issue by crichaud-work** [OSGeo/gdal#5105]
## Expected behavior and actual behavior.

I would like to be able to write logs using any file path name including space or not.

## Steps to reproduce the problem.

I am using the configuration options described here: https://trac.osgeo.org/gdal/wiki/ConfigOptions using CPLSetConfigOption
CPL_DEBUG
CPL_LOG_ERRORS
CPL_LOG
I am using CPLLoggingErrorHandler as default handler

Here is the code:

   CPLPushErrorHandler(CPLLoggingErrorHandler);//Error handler that logs into the file defined by the CPL_LOG configuration option, or stderr otherwise.
    CPLSetConfigOption("CPL_DEBUG", "ON");
    CPLSetConfigOption("CPL_LOG_ERRORS", "ON");

**if I use:
CPLSetConfigOption("CPL_LOG", "C:\\arcgisgdal\\cpl.log");
it works**.

**if I have a space in the file path like C:\arcgis gdal\cpl.log it does not work.**

I tried to escape the string, I try the add  \"...nothing worked.

I also noticed something weird in the code of 
void CPL_STDCALL CPLLoggingErrorHandler( CPLErr eErrClass, CPLErrorNum nError,
                                         const char * pszErrorMsg )

https://github.com/OSGeo/gdal/blob/master/port/cpl_error.cpp#L1033

why adding a +20 to the file path.

## Operating system

Platform: WINDOWS SERVER 2016, 64 bit

## GDAL version and provenance

gdal version 3.3 from gitub

**Comment by jratike80** [comment]
I believe that `nPathLen = strlen(cpl_log) + 20;` add 20 to the length of the path string.

**Comment by crichaud-work** [comment]
> I believe that `nPathLen = strlen(cpl_log) + 20;` adds 20 to the length of the path string.

yes but why would you do that. but that's not my main issue. my main issue is that I cannot open my log file if it contains a space.

**Comment by jratike80** [comment]
Maybe it is needed for the next step "// Generate sequenced log file names, inserting # before ext." If you want to understand the programming details you may try to ask a question from gdal-dev mailing list.

I am not sure if this helps but tried the config options with ogrinfo

`ogrinfo PG:"host=localhost port=5432 dbname=db user=user password=pw" --config CPL_DEBUG ON --config CPL_LOG "c:\data\log dir\foo bar.log"`

Path with spaces works for me and file `foo bar.log` appears into directory `c:\data\log dir`.

I am using GDAL 3.4.0.

**Comment by rouault** [comment]
@crichaud-work  Please test with GDAL 3.4.0 or 3.4.1 . There have been changes done in GDAL 3.4 to address non-ASCII characters on Windows for log filenames, although it doesn't seem to be your issue here. But I can't make sense why filenames with space could be a problem.

**Comment by crichaud-work** [comment]
Sorry for my late reply, I was on holiday. @rouault I am working with a gdal delivered by ESRI based on 3.3, and I don t have their code, I have to guess. BUT I will do my testing with your released 3.3 and 3.4.
@jratike80 I tried your command line with what ESRI provided me it does not work. I suspect their version of gdal is bugged. I will try today with a "standard" released gdal.

**Comment by crichaud-work** [comment]
I tried ogrinfo --formats --config CPL_DEBUG ON --config CPL_LOG "c:\data\log dir\foo bar.log" it works with gdal 3.3 that you have released. 
and ogrinfo is using EarlySetConfigOptions which is using the exact same CPLSetConfigOption. Something in the ESRI gdal makes it fail. I don t get it. But I will take your changes to address non-ASCII characters on Windows for log filenames in 3.3.

**Comment by jratike80** [comment]
Utilize your ESRI support channels and try to report your issue. It may stop at the local level with an explanation that the possible error in not in the ESRI code but you pay for the service.

**Comment by crichaud-work** [comment]
I will close the issue. It was still useful to know the changes made for NON ASCII characters. And I will use the ESRI channel. I don t think they will change their gdal for my custom gdalplugin driver.

**Comment by crichaud-work** [comment]
Closed. is an ESRI issue
