### ISSUE TITLE
not able to use 'ogr' in gdal version 3.3.2  while working with ".shp" files

### ISSUE THREAD

**Issue by Nageshbansal** [OSGeo/gdal#5114]
## Expected behavior and actual behavior.
While I am having gdal 3.2.2, if I try to import ogr in a script dealing with ".shp" files, it doesn't import,
but if I downgrade my gdal to 3.0.2 I'm able to import ogr and script run successfully

### ogr_not_working
![ogr_not_defined](https://user-images.githubusercontent.com/76246968/149594012-9fb4e909-a9e9-45d6-8e07-cd3c1b1556c6.jpg)
### ogr_working
![ogr_working](https://user-images.githubusercontent.com/76246968/149594015-42a3bde7-5cbd-4ea1-949e-ba4cb529bfeb.jpg)

## Operating system
 Ubuntu 20.04 bit

## GDAL version and provenance
GDAL 3.3.2 version from ubuntugis-unstable PPA

**Comment by rouault** [comment]
I suspect you need to update your script accordingly to https://github.com/OSGeo/gdal/blob/master/MIGRATION_GUIDE.TXT#L46

**Comment by Nageshbansal** [comment]
while importing gdal(3.3.2) i'm using : 
from osgeo import gdal
from osgeo import ogr 
and same for gdal (3.0.2)
but still it show 'ogr' not defined

**Comment by jratike80** [comment]
The error seems to say that you have a file named "ogr" in the directory that the script is using and version 3.3.2 asks to remove that file and try again. So nothing about an error in importing ogr. Could you check your shapefile directory?

**Comment by Nageshbansal** [comment]
Hey!!, i have no file named as 'ogr' , and the shaplefile is a dataset provided by [!natrual earth](https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/cultural/10m_cultural.zip) ,
and if i downgrade gdal , everything works fine

**Comment by EvertEt** [comment]
Could you share your Python script?

**Comment by jratike80** [comment]
Can you do something with ogr? For example this from https://pcjericks.github.io/py-gdalogr-cookbook/geometry.html#create-a-point
```
from osgeo import ogr
point = ogr.Geometry(ogr.wkbPoint)
point.AddPoint(1198054.34, 648493.09)
print (point.ExportToWkt())
```
If you can then ogr is generally available but something makes your old code to fail.
