### ISSUE TITLE
Extend the OGR C Interface `OGR_F_StealGeometry` function to geometries other than 1st one

### ISSUE THREAD

**Issue by mathieu17g** [OSGeo/gdal#5115]
Would there be any undesirable side effects of implementing `OGR_F_StealGeometry( int iGeomField )` as it is available as a C++ method but not on the C interface ?

The need relates to ArchGDAL.jl when converting a OGR Feature Layer to a table object. Stealing geometries is faster than cloning. This would bring a performance enhancement for layers with multiple geometry fields (https://github.com/yeesian/ArchGDAL.jl/pull/266)

**Comment by rouault** [comment]
> Would there be any undesirable side effects of implementing `OGR_F_StealGeometry( int iGeomField )` as it is available as a C++ method but not on the C interface ?

would be reasonable, as a new function OGRGeometryH CPL_DLL OGR_F_StealGeometryEx( OGRFeatureH, int iGeomField ) CPL_WARN_UNUSED_RESULT .
Are you willing to do a pull request for that ?

**Comment by mathieu17g** [comment]
Sure I can give a try
I can read C/C++ but have not written any code in C/C++ since the nineties :-)

**Comment by mathieu17g** [comment]
@rouault I have made a PR (my first PR in C/C++ actually).  
But I need some guidance to complete the PR #5196 .

*Testing*:
- I haven't found any unit testing using `OGR_F_StealGeometry` and therefore have no clue where to put unit testing if required
- I do have found `OGR_F_StealGeometry` usage in other functions for which I have not found anything looking like testing
I must miss something about testing of compiled languages. Could you give me an hint where to look for ?

*Documentation*: I have updated documentation comment blocks in the relevant source file. Is there any other documentation source to update ?
