### ISSUE TITLE
Jpeg2000 and transparency

### ISSUE THREAD

**Issue by ebremont** [OSGeo/gdal#512]
## Expected behavior and actual behavior.

I would like to reproject a JP2 File from EPSG 2154 to EPSG 3857 and to store the target image in a JP2 File with transparent background.
I expect the output.jp2 to have tranparent pixel areas (due to the reprojection), but background is black.
Is there something particular to do ?

## Steps to reproduce the problem.

gdalwarp -of VRT -t_srs 3857 -dstalpha input.jp2 output.vrt
gdal_translate -of JP2KAK  output.vrt output.jp2

## Operating system

Centos 7.3.1611 64bits

## GDAL version and provenance

Gdal 2.2.3 (sources from http://download.osgeo.org/gdal/)
Kakadu 7.10.4

**Comment by ebremont** [comment]
Thanks Even for your feedback. 
That means that the structure differences of input file we used may be a part of the answer.
Here's a JP2 file I use for my tests.

**Comment by rouault** [comment]
That works properly on your example for me. The alpha band in the padding area due to the reprojection is filled (mostly, there are a few values close to 0 that are due to the lossy characteristic of the compression) with 0

**Comment by ebremont** [comment]
I do not really understand. It seems that the alpha information was lost. When I try to convert to tif format, the value 0 seems to be interpreted as transparent but it is black for jp2 (as if the alpha info is lost).
Do you specify an argument to the command lines to force transparency ? What type (byte/int32...) do you use ?

**Comment by rouault** [comment]
> When I try to convert to tif format, the value 0 seems to be interpreted as transparent but it is black for jp2 (as if the alpha info is lost)

Perhaps an issue with the viewer you use that doesn't support alpha in JP2 ?

> Do you specify an argument to the command lines to force transparency ? What type (byte/int32...) do you use ?

No extra argument. Just tried your above commands. Byte data type

**Comment by rouault** [comment]
I've tried with okular and it displays indeed th padding as black. probably it doesn't support alpha in jp2. But QGIS (using GDAL drivers) displays it fine

**Comment by rouault** [comment]
@ebremont  Do you still believe there's a bug on GDAL side ?

**Comment by ebremont** [comment]
Sorry for my late answer.
I found that the opacity was due to an bad option used through the Kakadu java API. The basic tests I made were good... But I didn't have enough time to go further in my investigations and in my tests :-( .
In my opinion, given the first results I got, there's no bug in GDAL. :-)
