### ISSUE TITLE
Problem with UTF-8 in gdal python

### ISSUE THREAD

**Issue by mahdian-organization** [OSGeo/gdal#5121]
I want to convert Geojson to Shapefile with gdal in python. My Geojson encoding is UTF-8 but I get this error when convert to Shapefile:
`GDAL_ERROR 1: b"One or several characters couldn't be converted correctly from UTF-8 to ISO-8859-1.  This warning will not be emitted anymore."`

This is my code:
```
pathlib.Path(folder_path).mkdir(parents=True, exist_ok=True)
gdal.UseExceptions()
srcDS = gdal.OpenEx(geojson)
ds = gdal.VectorTranslate(output_path, srcDS=srcDS, format='ESRI Shapefile',
                          layerCreationOptions=['RFC7946=YES', 'WRITE_BBOX=YES']
                          )

# Dereference and close dataset, then reopen.
del ds
ds = gdal.OpenEx(output_path)

print(srcDS.GetLayer(0).GetFeatureCount())
print(ds.GetLayer(0).GetFeatureCount())
```

Thanks.

**Comment by rouault** [comment]
See https://gdal.org/drivers/vector/shapefile.html#layer-creation-options. Change layerCreationOptions=['RFC7946=YES', 'WRITE_BBOX=YES'] to layerCreationOptions=['ENCODING=UTF-8'] .  RFC7946 and WRITE_BBOX are creation options of GeoJSON, that is when you write GeoJSON.
