### ISSUE TITLE
Add support for 'rate' and 'Creversible' compression parameter into JP2KAK driver

### ISSUE THREAD

**Issue by mdhsl** [OSGeo/gdal#5131]
It would be useful to add support for the 'rate' compression parameter to the creation option of the JP2KAK driver options. 

Some examples:

- compressed data-rate 1 bit/pixel:
kdu_compress -i image.pgm -o out.j2c Qfactor=85 -rate 1.0)

- 3 embedded bit-rates
kdu_compress -i image.pgm -o out.j2c -rate 1.0,0.5,0.25

- compression with a progressive lossy to lossless code-stream having 4 layers
kdu_compress -i image.pgm -o out.j2c Creversible=yes -rate -,1,0.5,0.25

It would be useful to add support for the 'Creversible' compression parameter to the creation option of the JP2KAK driver options.
It is actually automatically computed depending on the Quality value. This should be able to be set manually

**Comment by mdhsl** [comment]
Update the issue to add CReevrsible support option

**Comment by rouault** [comment]
> Updated the issue to add CReversible support option

already implemented as documented in https://gdal.org/drivers/raster/jp2kak.html : "QUALITY=n: Set the compressed size ratio as a percentage of the size of the uncompressed image.[...]. A value of 100 will result in use of the lossless compression algorithm"

**Comment by mdhsl** [comment]
In case of use of Quality parameter. But, In case of using RATE parameter, we would decide if we want to make it lossless such like kdu_compress parameter:
```sh
kdu_compress -i image.tif -o out.jp2 Creversible=yes -rate -,1,0.5
```

Quality option is kind of simplification of potential KDU option we have. Specifying Rate is more accurate and can be associated to Creversible option.

Does it make sense?

**Comment by rouault** [comment]
> Does it make sense?

yes, but to avoid option proliferation, I imagined you could potentially use both QUALITY=100 (which implies CReversible=yes) and the RATE option if specified should include a lossless layer (which must be the "-" I guess). I don't have any firm opinion on this though. This will up to anyone that will be potentially willing to tackle this (you ?) to decide.

**Comment by mdhsl** [comment]
Yes it is an idea. If so, the documentation has to be clear about how the Reversible option is set to yes and in which case.

For me, but I could be wrong, the reversibility is not linked to the quality factor.

From the Kakadu documentation:

"Irreversible matrix decorrelation transforms are corresponding points from each input component to the transform are treated as a vector which is multiplied by an M × N matrix, with M the number of output components and N the number of input components to the block."

"Reversible matrix decorrelation transforms are a sequence of reversible combinatorial steps progressively transforms the N block input components into N output components with integer values. These transformsmay be exactly inverted."

"Reversible and irreversible wavelet transformations are corresponding points from each of the block input components are treated as subband samples from a DWT with a speciﬁed depth and canvas origin (in the component direction). Arbitrary wavelet kernels are supported."

This is probably more associated to JPE200 specifications and the associated transformation algorithm.

In some Kakadu examples, we have:

```sh
kdu_compress -i image.tif -o out.jp2 Creversible=yes  -rate 1.0,0.04
```
```sh
kdu_compress -i image.tif -o out.jp2 Creversible=yes  -rate 1.5
```
```sh
kdu_compress -i image.tif -o out.jp2 Creversible=yes  -rate  -,1.0,0.04
```

For your second statement, yes, I am going to work on this. I have already a piece of code I have to improve before pushing a PR.

**Comment by rouault** [comment]
> What do you think?

technically bit rate and reversibility/irreversibility are indeed 2 different JPEG2000 concepts. That said, in practice, using a reversible kernel but without all quality layers doesn't make much sense, as it is going to be lossy.

**Comment by jratike80** [comment]
In theory it could make some sense because it is possible that some software is faster with reversible(5-3) kernel + lossy compression than with the (9-7) kernel even the file size is slightly bigger.

**Comment by rouault** [comment]
> because it is possible that some software is faster with reversible(5-3) kernel + lossy compression than with the (9-7) kernel

maybe, but the cost of the wavelet compression is quite marginal in JPEG2000 decompression, so I wouldn't expect reversible vs irreversible to really make a significant timing difference all other things equal.
