### ISSUE TITLE
3.4.1 build error on recent RHEL/Fedora distros

### ISSUE THREAD

**Issue by devrimgunduz** [OSGeo/gdal#5145]
Hi,

3.4.1 fails to build on RHEL 8, Fedora 35 and Fedora 34. Using PROJ 8.2.1, OGDI 4.1.0, GeOS 3.10.2, libspatialite 5.0.1.  OTOH I don't see any issues on RHEL 7. The differences between these platforms are RHEL 7 uses netcdf 4.3.3, and failing ones use netcdf 4.7.x and 4.8(Fedora 35). 

Errors are below:

```
> /bin/sh /var/lib/pgsql/rpmcommon/BUILD/gdal-3.4.1-fedora/libtool --mode=link --silent g++ -L/usr/proj82/lib -L/usr/ogdi41/lib -L/usr/libgeotiff16/lib -L/usr/geos310/lib64 -L/usr/libspatialite50/lib -L/usr/lib64 gdaladdo.lo  /var/lib/pgsql/rpmcommon/BUILD/gdal-3.4.1-fedora/libgdal.la -o gdaladdo
> cc1plus: warning: external/include: No such file or directory [-Wmissing-include-dirs]
> cc1plus: warning: external/include: No such file or directory [-Wmissing-include-dirs]
> /bin/sh /var/lib/pgsql/rpmcommon/BUILD/gdal-3.4.1-fedora/libtool --mode=link --silent g++ -L/usr/proj82/lib -L/usr/ogdi41/lib -L/usr/libgeotiff16/lib -L/usr/geos310/lib64 -L/usr/libspatialite50/lib -L/usr/lib64 gdalwarp_bin.lo  /var/lib/pgsql/rpmcommon/BUILD/gdal-3.4.1-fedora/libgdal.la -o gdalwarp
> /var/lib/pgsql/rpmcommon/BUILD/gdal-3.4.1-fedora/.libs/libgdal.so: undefined reference to `proj_create_conversion_pole_rotation_netcdf_cf_convention'
> collect2: error: ld returned 1 exit status
> /var/lib/pgsql/rpmcommon/BUILD/gdal-3.4.1-fedora/.libs/libgdal.so: undefined reference to `proj_create_conversion_pole_rotation_netcdf_cf_convention'
> collect2: error: ld returned 1 exit status
> make[2]: *** [GNUmakefile:98: gdal_translate] Error 1
> make[2]: *** Waiting for unfinished jobs....
> make[2]: *** [GNUmakefile:89: gdalinfo] Error 1
> /var/lib/pgsql/rpmcommon/BUILD/gdal-3.4.1-fedora/.libs/libgdal.so: undefined reference to `proj_create_conversion_pole_rotation_netcdf_cf_convention'
> collect2: error: ld returned 1 exit status
> make[2]: *** [GNUmakefile:101: gdaladdo] Error 1
> /var/lib/pgsql/rpmcommon/BUILD/gdal-3.4.1-fedora/.libs/libgdal.so: undefined reference to `proj_create_conversion_pole_rotation_netcdf_cf_convention'
> collect2: error: ld returned 1 exit status
> make[2]: *** [GNUmakefile:104: gdalwarp] Error 1
> make[2]: Leaving directory '/var/lib/pgsql/rpmcommon/BUILD/gdal-3.4.1-fedora/apps'
> make[1]: *** [GNUmakefile:123: apps-target] Error 2
> make[1]: Leaving directory '/var/lib/pgsql/rpmcommon/BUILD/gdal-3.4.1-fedora'
> error: Bad exit status from /var/tmp/rpm-tmp.vAn4OA (%build)
> 
```

Any ideas?

Regards, Devrim

**Comment by rouault** [comment]
I suspect you have a mixup of PROJ versions. It seems your GDAL is built against PROJ headers of PROJ >= 8.2 (since the proj_create_conversion_pole_rotation_netcdf_cf_convention symbol is used only when PROJ >= 8.2 is detected) but you link against an older version

**Comment by devrimgunduz** [comment]
Hi @rouault ,

Thanks for the tip. Removed other occurances of PROJ, and I could build it.

However this is not the first time that multiple PROJ version installed, and apparently 3.4 is first version that --with-proj option was not *properly* honoured. Please note that all other PROJ installations are under their own directories (/usr/projXY) Could there be something somewhere that GDAL may ignore --with-proj option?

Thanks!

**Comment by rouault** [comment]
> Could there be something somewhere that GDAL may ignore --with-proj option?

The effect of the option is just to add a -L/path/to/lib -lproj to the linking line. If another library that GDAL links to before links to another PROJ version, or maybe passe a -L that points to a location with a libproj that isn't the one you want, then it might be the one that will get selected. I can't recall any particular change related to that. Perhaps things will get more predictable with the CMake builds
