### ISSUE TITLE
CSV to geopackage: -dsco GEOMETRY_NAME=geom does not work

### ISSUE THREAD

**Issue by anbj** [OSGeo/gdal#5153]
I'm trying to convert a .csv file to gpkg with the *-dsco GEOMETRY_NAME=geom* option, but this returns a warning:
```
$ ogr2ogr -F GPKG -makevalid -a_srs EPSG:4230 -oo KEEP_GEOM_COLUMNS=NO -dsco GEOMETRY_NAME=geom gis.gpkg Area.csv -oo GEOM_POSSIBLE_NAMES=AreaWKT

Warning 6: driver GPKG does not support creation option GEOMETRY_NAME
```

* Should not this be possible? Ref. https://gdal.org/drivers/vector/gpkg.html#layer-creation-options: *GEOMETRY_NAME: Column to use for the geometry column. Default to “geom”. Note: This option was called GEOMETRY_COLUMN in releases before GDAL 2*

* When I omit *-dsco GEOMETRY_NAME=geom* the geometry column gets the same name as the input wkt-field. In the example above, the geometry field is named *AreaWKT*. Not the default, *geom* as indicated in the docs.

**Comment by jratike80** [comment]
Bug tracker is meant for reporting bugs. Ask questions on gdal-dev mailing list. If discussion reveals a bug the issue into GitHub can be created later.

`-dsco` : datastore creation option, `-lco` : layer creation option

**Comment by anbj** [comment]
Thanks jratike80.
