### ISSUE TITLE
WCS: Failing SSL handshake blocks subsequent trials

### ISSUE THREAD

**Issue by jratike80** [OSGeo/gdal#516]
## Expected behavior and actual behavior.
@ajolma 

If WCS driver fails with SSL handshaking because of certificate problem an empty xml file like "XYZZXY.xml" is written into the wcs_cache directory.  If the request if repeated by setting the config option GDAL_HTTP_UNSAFESSL=YES the request fails again but now because WCS driver tries to use the cached xml file, which does exist but which is empty and invalid.

WCS driver should not write an empty XML file if it cannot make a proper connection with the WCS server. If it finds an existing but invalid xml file it should do something reasonable, perhaps to delete the faulty xml file from the cache and try to read the contents again from the WMS server. 

## Steps to reproduce the problem.

The error can be reproduced today with the following commands but probably the server certificate will be fixed soon.

First request:
gdalinfo WCS:"https://beta-karttakuva.maanmittauslaitos.fi/wcs/service/ows?"
ERROR 1: SSL certificate problem: unable to get local issuer certificate
gdalinfo failed - unable to open 'WCS:https://beta-karttakuva.maanmittauslaitos.fi/wcs/service/ows?'

Second request:
gdalinfo WCS:"https://beta-karttakuva.maanmittauslaitos.fi/wcs/service/ows?" --config
 GDAL_HTTP_UNSAFESSL YES
ERROR 3: Cannot open file 'C:\Users\JRAHKONEN\.gdal\wcs_cache\RFWGM.aux.xml'
gdalinfo failed - unable to open 'WCS:https://beta-karttakuva.maanmittauslaitos.fi/wcs/service/ows?'

## GDAL version and provenance

GDAL version 2.2.4-dev from gisinternals.com

**Comment by ajolma** [comment]
The certificate is fixed now but with https://arijolma.org/geoserver/ows?request=WCS I can reproduce this.

The cache options documented on the driver page can be used. However, REFRESH_CACHE does not seem to be strong enough so one needs to use CLEAR_CACHE (i.e. -oo CLEAR_CACHE in the command). So, this is not a blocker but the driver should be improved.

In addition, WCS is disabled in the above, which can be seen from the exception but the driver does not report that, instead it reports a local problem -- it should not get that far.
