### ISSUE TITLE
TGA: Scrambled read of RLE images

### ISSUE THREAD

**Issue by clundgren** [OSGeo/gdal#5168]
## Expected behavior and actual behavior.

Reading from run-length encoded tga images produces a scrambled result. I've [attached](https://github.com/OSGeo/gdal/files/7936229/examples.zip) some sample images that reproduce the issue (originally found [here](https://samples.ffmpeg.org/image-samples/)).

For example, reading the attached test1g.tga produces the following result:
![test1g](https://user-images.githubusercontent.com/6045555/151037505-8f162839-9f09-405a-93f2-58ee2c2d1c01.png)

When it should actually look like this:
![test1g-fixed](https://user-images.githubusercontent.com/6045555/151037617-e80d57e4-e837-4018-bb86-d45fde59f689.png)

I believe the problem is that `GDALTGARasterBand::IReadBlock()` implicitly assumes that runs are independent per row, but it is actually possible for runs to span multiple rows. That is, it is not enough to seek to a location and start reading from there. A row may need to start with some data "leftover" from the previous row.

## Steps to reproduce the problem.

Translate one of the attached images, e.g. `gdal_translate.exe test1g.tga test1g.png`

## Operating system

Windows 10 64 bit

## GDAL version and provenance

GDAL 3.4.1, released 2021/12/27, from OSGeo4w

**Comment by rouault** [comment]
> I believe the problem is that `GDALTGARasterBand::IReadBlock()` implicitly assumes that runs are independent per row, but it is actually possible for runs to span multiple rows

hum, I believe you're right. https://en.wikipedia.org/wiki/Truevision_TGA#Specification_discrepancies applies here: the driver currently assume that runs to no cross rows.
