### ISSUE TITLE
CMake Poppler cleanup

### ISSUE THREAD

**Issue by rouault** [OSGeo/gdal#5170]
When we'll have removed support autoconf and cmake, you should revisit frmts/pdf/CMakeLists.txt and frmts/pdf/pdfsdk_headers.h to use only ${Poppler_INCLUDE_DIRS} (and not ${Poppler_INCLUDE_DIR}/.. and change the #include's to remove the "poppler/" prefix.
See https://github.com/OSGeo/gdal/pull/5165#discussion_r792075445

**Comment by dg0yt** [comment]
A cleanup is not enough.
- There are dangerous `#define private public` hacks in `pdfsdk_headers.h`. AFAIU it is needed e.g. for this hack:
  https://github.com/OSGeo/gdal/blob/cb181d1ac2ad3400f6de2db481d2d29dcf7ff0ef/frmts/pdf/pdfdataset.cpp#L2375-L2379
- Poppler now uses `std::optional` in its API, i.e. it  needs C++17.

**Comment by rouault** [comment]
> There are dangerous #define private public hacks in pdfsdk_headers.h. AFAIU it is needed e.g. for this hack:

yeah. Not much alternatives given what is present in the Poppler C++ API. We could perhaps propose something to upstream Poppler but they aren't always super receptive to things required by external users like us, since they consider the C++ API as internal. And the Poppler C API is not enough for GDAL needs (it is too high level), and it would be unpractical to extend it. Past discussions with Poppler team went quickly stuck.

> * Poppler now uses `std::optional` in its API, i.e. it  needs C++17.

Already enabled per https://github.com/OSGeo/gdal/blob/cb181d1ac2ad3400f6de2db481d2d29dcf7ff0ef/frmts/pdf/CMakeLists.txt#L33

**Comment by dg0yt** [comment]
> > * Poppler now uses `std::optional` in its API, i.e. it  needs C++17.
> 
> Already enabled

:+1:

> > There are dangerous #define private public hacks in pdfsdk_headers.h. AFAIU it is needed e.g. for this hack:
> 
> yeah. Not much alternatives given what is present in the Poppler C++ API. We could perhaps propose something to upstream Poppler but they aren't always super receptive to things required by external users like us, since they consider the C++ API as internal. And the Poppler C API is not enough for GDAL needs (it is too high level), and it would be unpractical to extend it. Past discussions with Poppler team went quickly stuck.

- How long ago is "past discussions"? This particular workaround seems to be here for more than 10 years, and poppler seems to be much more active in recent years.
- AFAIU gdal doesn't use the "[Poppler C++ API](https://poppler.freedesktop.org/api/cpp/)" but its private C++ implementation. (You are probably aware of this.) I guess the public API has an even wider gap to gdal's  requirements?
- IIUC the problem only occurs when using different CRTs in Windows (poppler vs. gdal). Is this the common case or the exception? As someone who builds everything from source I really wonder if this isn't too much pessimization for everyone, just to help people with different Windows CRTs. And now there is also UCRT.

I guess poppler really needs an actual proposal or PR. I wonder if there are more spots like this.

Disclaimer: I use MSVC only in CI.

**Comment by rouault** [comment]
> * How long ago is "past discussions"?

https://trac.osgeo.org/gdal/ticket/7034 and https://lists.freedesktop.org/archives/poppler/2017-September/thread.html#12515
