### ISSUE TITLE
GTiff does not always consider proj search paths given with OSRSetPROJSearchPaths()

### ISSUE THREAD

**Issue by olivier80** [OSGeo/gdal#5184]
During reprojection of some jp2 files, a warning "proj_create_from database: Cannot find proj.db" is showing. However, the operations seems to complete successfully. We use OSRSetPROJSearchPaths() to setup correct proj-data path.
I ran a debug session and found that the error is thrown when extracting crs metadata from the files in frmts/gtiff/gt_wkt_srs.cpp because the path setup with OSRSetPROJSearchPaths() is not taken account.

I try the simple modification attached and it seems to do the job. Not sure if it's the good correction.

## Operating system

Windows 10 64 bits

## GDAL version and provenance

gdal 3.4.1
proj 8.1.1
[gtiff_proj_context.zip](https://github.com/OSGeo/gdal/files/7950364/gtiff_proj_context.zip)

**Comment by rouault** [comment]
> I try the simple modification attached and it seems to do the job. Not sure if it's the good correction.

Looks good! Please submit it as a pull request against master

**Comment by olivier80** [comment]
Done : #5187
