### ISSUE TITLE
GDAL: GetAreaOfUse coordinate transformation failure

### ISSUE THREAD

**Issue by sergey-suloev** [OSGeo/gdal#5197]
I am trying to do coordinate transformations from EPSG:26714 to its geog SRS and vice versa. I am using OS windows10 pro, Visual Studio 2019 and the very latest GDAL compiled from the source code.

The coordinates obtained by srs->GetAreaOfUse() call I am trying to convert to EPSG:26714  and then back.

GDAL seems to transform coordinates correctly when using the C++ transformation class directly but transformations won't  work via an instance of C++ class  OGRPolygon. 

I attached my C++ sample so that you can easily reproduce the issue. I put my comments directly to the sample so you can understand what should happen at every step and what goes wrong.

What am I doing wrong ?

**Comment by sergey-suloev** [comment]
int main()
{
    OGRSpatialReference *projSRS = new OGRSpatialReference();
    OGRSpatialReference *geogSRS;
    OGRErr  err;
    double  dfWestLongitudeDeg;
    double  dfSouthLatitudeDeg;
    double  dfEastLongitudeDeg;
    double  dfNorthLatitudeDeg;
    const char  *pszAreaName;
    OGRCoordinateTransformation *transP2G, *transG2P;

    // 1) Create SRS instance for EPSG:26714 
    err = projSRS->importFromEPSG(26714);
    if (err != OGRERR_NONE)
    {
        std::cerr << "Unable to import SRS  from EPSG\n";
        return 1;
    }

    geogSRS = projSRS->CloneGeogCS();
    if (geogSRS == NULL)
    {
        std::cerr << "Unable to retrieve geog SRS from projected SRS\n";
        return 1;
    }

    geogSRS->SetAxisMappingStrategy(OAMS_TRADITIONAL_GIS_ORDER);

    if(!projSRS->GetAreaOfUse(&dfWestLongitudeDeg,
                            &dfSouthLatitudeDeg,
                            &dfEastLongitudeDeg,
                            &dfNorthLatitudeDeg,
                            &pszAreaName))
    {
        std::cerr << "Unable to get area of use for projected SRS\n";
        return 1;
    }

    transG2P =
        OGRCreateCoordinateTransformation( geogSRS, projSRS );
    transP2G =
        OGRCreateCoordinateTransformation( projSRS, geogSRS );

    // Create  2 array sets for easy by-eye comparation
    //
    double x[] = { dfWestLongitudeDeg, dfEastLongitudeDeg };
    double y[] = { dfSouthLatitudeDeg, dfNorthLatitudeDeg };

    double x2[] = { dfWestLongitudeDeg, dfEastLongitudeDeg };
    double y2[] = { dfSouthLatitudeDeg, dfNorthLatitudeDeg };

    if (! transG2P->Transform(2, x2, y2))
    {
        std::cerr << "Unable to transform coordinates from geog SRS to projected SRS\n";
        return 1;
    }

    // Create a polygon geometry for testing 
    OGRLinearRing *pRing = new OGRLinearRing();
    pRing->setNumPoints(4);
    pRing->setPoint(0, x2[0], y2[0]);
    pRing->setPoint(1, x2[0], y2[1]);
    pRing->setPoint(2, x2[1], y2[1]);
    pRing->setPoint(3, x2[1], y2[0]);
    OGRPolygon *pPolygon = new OGRPolygon();
    pPolygon->addRingDirectly(pRing);	// classical polygon with only exterior ring
    pPolygon->closeRings();				// forces the ring to be closed

    char *pszPolygon1;
    err = pPolygon->exportToWkt(&pszPolygon1);
    std::cout << "Projected SRS: " << pszPolygon1 << std::endl;


    // Do transform coordinates from projected SRS to geog SRS
    //
    if (!transP2G->Transform(2, x2, y2))
    {
        std::cerr << "Unable to transform coordinates from projected SRS to geog SRS\n";
        return 1;
    }

    //
    // Compare x,y and x2,y2
    // NOTE, that they are 99.9% similar
    //

    // Now tranform geometry from projected SRS to geog SRS
    //
    err = pPolygon->transform(transP2G);
    if (err != OGRERR_NONE)
    {
        std::cerr << "Unable to transform geometry from projected SRS to geog SRS\n";
        return 1;
    }

    //
    // Verify geometry points
    // NOTE, that polygon points are now DIFFERENT
    //
    char* pszPolygon2;
    err = pPolygon->exportToWkt(&pszPolygon2);
    std::cout << "Geog SRS: " << pszPolygon2 << std::endl;


    std::cout << "Success!\n";
}

**Comment by sergey-suloev** [comment]
````
int main()
{
    OGRSpatialReference *projSRS = new OGRSpatialReference();
    OGRSpatialReference *geogSRS;
    OGRErr  err;
    double  dfWestLongitudeDeg;
    double  dfSouthLatitudeDeg;
    double  dfEastLongitudeDeg;
    double  dfNorthLatitudeDeg;
    const char  *pszAreaName;
    OGRCoordinateTransformation *transP2G, *transG2P;

    // 1) Create SRS instance for EPSG:26714 
    err = projSRS->importFromEPSG(26714);
    if (err != OGRERR_NONE)
    {
        std::cerr << "Unable to import SRS  from EPSG\n";
        return 1;
    }

    geogSRS = projSRS->CloneGeogCS();
    if (geogSRS == NULL)
    {
        std::cerr << "Unable to retrieve geog SRS from projected SRS\n";
        return 1;
    }

    geogSRS->SetAxisMappingStrategy(OAMS_TRADITIONAL_GIS_ORDER);

    if(!projSRS->GetAreaOfUse(&dfWestLongitudeDeg,
                            &dfSouthLatitudeDeg,
                            &dfEastLongitudeDeg,
                            &dfNorthLatitudeDeg,
                            &pszAreaName))
    {
        std::cerr << "Unable to get area of use for projected SRS\n";
        return 1;
    }

    transG2P =
        OGRCreateCoordinateTransformation( geogSRS, projSRS );
    transP2G =
        OGRCreateCoordinateTransformation( projSRS, geogSRS );

    // Create  2 array sets for easy by-eye comparation
    //
    double x[] = { dfWestLongitudeDeg, dfEastLongitudeDeg };
    double y[] = { dfSouthLatitudeDeg, dfNorthLatitudeDeg };

    double x2[] = { dfWestLongitudeDeg, dfEastLongitudeDeg };
    double y2[] = { dfSouthLatitudeDeg, dfNorthLatitudeDeg };

    if (! transG2P->Transform(2, x2, y2))
    {
        std::cerr << "Unable to transform coordinates from geog SRS to projected SRS\n";
        return 1;
    }

    // Create a polygon geometry for testing 
    OGRLinearRing *pRing = new OGRLinearRing();
    pRing->setNumPoints(4);
    pRing->setPoint(0, x2[0], y2[0]);
    pRing->setPoint(1, x2[0], y2[1]);
    pRing->setPoint(2, x2[1], y2[1]);
    pRing->setPoint(3, x2[1], y2[0]);
    OGRPolygon *pPolygon = new OGRPolygon();
    pPolygon->addRingDirectly(pRing);	// classical polygon with only exterior ring
    pPolygon->closeRings();				// forces the ring to be closed

    char *pszPolygon1;
    err = pPolygon->exportToWkt(&pszPolygon1);
    std::cout << "Projected SRS: " << pszPolygon1 << std::endl;


    // Do transform coordinates from projected SRS to geog SRS
    //
    if (!transP2G->Transform(2, x2, y2))
    {
        std::cerr << "Unable to transform coordinates from projected SRS to geog SRS\n";
        return 1;
    }

    //
    // Compare x,y and x2,y2
    // NOTE, that they are 99.9% similar
    //

    // Now tranform geometry from projected SRS to geog SRS
    //
    err = pPolygon->transform(transP2G);
    if (err != OGRERR_NONE)
    {
        std::cerr << "Unable to transform geometry from projected SRS to geog SRS\n";
        return 1;
    }

    //
    // Verify geometry points
    // NOTE, that polygon points are now DIFFERENT
    //
    char* pszPolygon2;
    err = pPolygon->exportToWkt(&pszPolygon2);
    std::cout << "Geog SRS: " << pszPolygon2 << std::endl;


    std::cout << "Success!\n";
}
````

**Comment by rouault** [comment]
here's the output I get:
```
Projected SRS: POLYGON ((178247.917120721 1725744.17214756,178247.917120721 8965448.70883136,553872.581641276 8965448.70883136,553872.581641276 1725744.17214756,178247.917120721 1725744.17214756))
Geog SRS: POLYGON ((-102 15.59,-116.387001594411 80.3178189257012,-96 80.74,-98.4974540979665 15.6099064845999,-102 15.59))
Success!
```
It looks OK to me. The first point of the geog SRS Polygon is -102 15.59 , that is x[0],y[0], and the third one is x[1],y[1]

**Comment by sergey-suloev** [comment]
@rouault  I have the same output. But is not good because it is not the same as GetAreaOfUse returned in the beginning.

**Comment by rouault** [comment]
> The coordinate -116.387001594411 80.3178189257012 falls outside the initial box.

This is completely expected ! A bit complicated to explain with words. Would require some drawing. I'm pretty sure there must be some online resources for that. But that's definitely a property of map projections. Basically a rectangle in a projected CRS is not a rectangle in the corresponding geographic CRS and vice-verca. Also note that the area of use of EPSG:26714 is more a hint than something absolute. A UTM projection can mathematically be used far beyond its usual +/- 3 deg of longitude range around the central meridian.

**Comment by sergey-suloev** [comment]
@rouault  but how is it possible to write code if I can't get the initial results that I provided in the beginning?

**Comment by sergey-suloev** [comment]
I have update the source code. Please , look at the end the sample. The last transformation fails, and I guess because the previous transformation was incorrect.

**Comment by rouault** [comment]
> The last transformation fails, and I guess because the previous transformation was incorrect.

no it fails because the extent of the CONUS grid used by urn:ogc:def:coordinateOperation:EPSG::15851 doesn't go to latitude 80. Its extent is
Upper Left  (-131.1250000,  50.1250000) (131d 7'30.00"W, 50d 7'30.00"N)
Lower Left  (-131.1250000,  19.8750000) (131d 7'30.00"W, 19d52'30.00"N)
Upper Right ( -62.8750000,  50.1250000) ( 62d52'30.00"W, 50d 7'30.00"N)
Lower Right ( -62.8750000,  19.8750000) ( 62d52'30.00"W, 19d52'30.00"N)

**Comment by sergey-suloev** [comment]
@rouault so it is a GDAL limitation?

**Comment by rouault** [comment]
> so it is a GDAL limitation?

not really. Your asking GDAL to use a transformation but you provide points outside its area of use. "projinfo -k operation EPSG:15851" reports BBOX[23.81,-129.17,49.38,-65.69]] (order is south_lat, west_lon, north_lat, east_lat).  Hence the failure.
If you remove the call to "options.SetCoordinateOperation("urn:ogc:def:coordinateOperation:EPSG::15851", false)", PROJ will decide by itself which transformations it can use. In that situation it will use NAD 27->WGS 84 transformations valid for Mexico and Canada given that the points of your geometry fall into those areas.

> GetAreaOfUse is returning an incorrect box ?

It is returning what the EPSG dataset returns. The area of use of EPSG:26714 extend beyond the conterminous US (CONUS), hence you can't use a US-only transformations if reprojection a geometry that goes beyond CONUS extent.
Lots of subtelties in using projections and coordinate transformations.

**Comment by sergey-suloev** [comment]
@rouault Ok, thank you for explanation. 

Is this possible to call "projinfo -k operation EPSG:15851" with GDAL API ? 
This way I could adjust the box given by GetAreaOfUse in case I need to use a specific transformation.

**Comment by rouault** [comment]
> Is this possible to call "projinfo -k operation EPSG:15851" with GDAL API ?

with the PROJ API rather: https://proj.org/development/reference/functions.html?highlight=proj_get_area_of_use#c.proj_get_area_of_use   + proj_create(context, "urn:ogc:def:coordinateOperation:EPSG::15851") to get the PJ* object needed.

I'll stop with that last comment, because as said in the issue template, github tickets are for bugs, and after examination, this is not a bug.

**Comment by sergey-suloev** [comment]
@rouault ok, I agree. thank you so much

**Comment by jratike80** [comment]
I am sorry but I am not a programmer and I cannot follow the code properly. Is it transforming the four corners of a polygon between EPSG:26714 and EPSG:4267? And then the standard conversion is EPSG:26714 (taken from https://epsg.org/crs_26714/NAD27-UTM-zone-14N.html) but the code takes somehow EPSG:15851 https://epsg.org/transformation_15851/NAD27-to-WGS-84-79.html? that is invalid for the polygon that is used as input?

My PostGIS seems to use transformation that is valid for this area (if this is the same thing that the code does at all)
```
select 
st_astext(
st_transform(
	st_transform(st_geomfromtext('POLYGON ((-102 15.59,-102 80.74,-96 80.74,-96 15.59,-102 15.59))',4267),
26714),4267))

"POLYGON((-102 15.59,-102 80.74,-96.00000000000001 80.74,-96.00000000000001 15.59,-102 15.59))"
```

**Comment by rouault** [comment]
> Is it transforming the four corners of a polygon between EPSG:26714 and EPSG:4267?

not really. It starts from the (west, south) and (east, north) long-lat corners, reproject them into EPSG:26714, then build a rectangular polygon from the projected coordinates of those 2 corners, and project it back to EPSG:4267.
This is different from reprojecting the 4 corners (west, south), (west, north), (east, north) and (east, south) forth and back, as you did with the PostGIS SQL.

**Comment by jratike80** [comment]
Ok. Then when in EPSG:26714 the geometry it looks like this (geometry densified to get interim points)
<img width="57" alt="image" src="https://user-images.githubusercontent.com/1751612/151704286-66780f8a-a366-4037-b2cd-da5079e7af16.png">

and the envelope of this 26714 geometry is not the same as the geometry itself, even it was the case in source EPSG:4267.

**Comment by sergey-suloev** [comment]
@jratike80  Here is what I finally found. My customer wants to use the datum transformation 15851. In my software I also need to get the coordinate system maximum extents/box which I obtain via GetAreaOfUse. The problem is that the box is larger than the one supported by the transformation 15851 and when I convert the box back and forth I get an error. 

So finally I came to the idea of adjusting the box given by GetAreaOfUse with the limits defined for a particular transformation. 
I have no idea how to link GDAL api  I am using now and PROJ api which I know is used inside GDAL but I believe I should be able to find the right way to do that.

**Comment by sergey-suloev** [comment]
@rouault  another question is why transformations made by OGRCoordinateTransformation->Transform give different results than those obtained by polygon->Transform

**Comment by jratike80** [comment]
Please use gdal-dev mailing list for asking questions. 1) Other friendly users may be able to give answers, just like you can after a while 2) Other users dealing with similar problems get learned by the answers and 3)  I guess that the behavior is not a bug. If it is a new issue can be created later.

**Comment by sergey-suloev** [comment]
@jratike80 Thank you for your explanation with pictures. It's much more clearly now.

**Comment by sergey-suloev** [comment]
@rouault Could it be logical and possible to add GetAreaOfUse into OGRCoordinateTransformation class ? It seems to be so because the same method exists in OGRSpatialReference class.
