### ISSUE TITLE
GDAL: GetAreaOfUse coordinate transformation failure

### ISSUE THREAD

**Issue by sergey-suloev** [OSGeo/gdal#5199]
Create a copy of the closed one as it was not resolved.

See details

https://github.com/OSGeo/gdal/issues/5197

**Comment by jratike80** [comment]
I do not want to be unpolite but this is not the right way to handle the case when the answer did not satisfy you. I try to give more detailed answer in the original bug report, that actually could have been a question in gdal-dev mailing list or in gis.stackexchange.

**Comment by sergey-suloev** [comment]
@jratike80 
I have update the source code. Please , look at the end the sample. The last transformation fails, and I guess because the previous transformation was incorrect.

**Comment by sergey-suloev** [comment]
@jratike80 Excuse me, sir, but I don't see any reason to close an unresolved issue. This is absolutely wrong and , sating your words, impolite.

**Comment by jratike80** [comment]
Please let me explain first, I am writing an answer to you with screen captures. I wish you were here so we could talk face to face.
