### ISSUE TITLE
Update python sample scripts documentation

### ISSUE THREAD

**Issue by kubaszostak** [OSGeo/gdal#5205]
## Expected behavior and actual behavior.

Expected behavior: [Python sample scripts](https://gdal.org/api/python_samples.html) documentation should contain information about sample scripts.  
Actual behavior: In some sections of documentation there are 'dots' without any content.

## Steps to reproduce the problem.

Go to <https://gdal.org/api/python_samples.html>

![image](https://user-images.githubusercontent.com/4609437/151753657-7d484fc4-1e82-4672-8d10-0585e4d23f2d.png)

## Operating system

Any

## GDAL version and provenance

The master branch, currently the 3.4 version ([9e9f8b2](https://github.com/OSGeo/gdal/commit/9e9f8b294418e5f2670dacd5cacb5d6cdeabb797#diff-37a88d1c61b233f1b5dd6a3311f4c90fb0baba6e16517497afb3cc07e12bda08))

**Comment by rouault** [comment]
@idanmiara  I'm looking at this and python_samples.rst has syntax like:
```
    - .. _assemblepoly: Script demonstrates how to assemble polygons from arcs. Demonstrates various aspects of OGR Python API.
```
Was the intent to have ``.. _assemblepoly`` to be a link to the python source code ?
