### ISSUE TITLE
gdal_calc: enhance Calc function

### ISSUE THREAD

**Issue by kikitte** [OSGeo/gdal#5219]
gdal_calc.py implements an element-wise computation using an expression, but in many cases, expression is not enough to express the complex calculation logic, so a callback function is needed for the Calc function to evaluate the calculation logic.  With this change, we can import the Calc function, define our calculation logic as a function and pass it to the Calc function.
For backward comparability, we need to define an expression evaluator for command line usage in the script. 
If this thought is on the right way, I am willing to try to achieve it.

https://github.com/OSGeo/gdal/blob/583d25f31a0a5ecaf411494ce19f4fbe296d15a1/swig/python/gdal-utils/osgeo_utils/gdal_calc.py#L94-L101

**Comment by rouault** [comment]
This is actually already implemented. See https://gdal.org/programs/gdal_calc.html#cmdoption-arg-user_namespace and https://github.com/OSGeo/gdal/blob/de854681fffc64f2622c2b8721f574d3a53ee752/autotest/pyscripts/test_gdal_calc.py#L394

**Comment by kikitte** [comment]
it is a good news,, thanks @rouault
