### ISSUE TITLE
vistar: shapefiles with invalid topology can be read from .tar files but not .tar.gz files

### ISSUE THREAD

**Issue by shawnlaffan** [OSGeo/gdal#5225]
## Expected behavior and actual behavior.

GDAL seems able to read shapefiles with invalid topology (self-intersecting polygons in this case) when they are "plain" shapefiles or via ```/vsitar/``` when they are in an uncompressed tar file.  

However, it throws an error when the same shapefile is in a gzipped tar file.

The files are readable after passing them through ```ogr2ogr``` with ```-makevalid```, then retarring and gzipping 

Example data are from the Collection 6 MODIS Burned Area Product.  FWIW, it appears fewer than 1% of the files have invalid topology.

Steps below use ```ogrinfo``` but the same error occurs when using  ```st_read``` via the ```sf``` library for R.

## Steps to reproduce the problem.

```bash
#  file 1 fails as a gzipped tar file but works as a plain tar file; file 2 works
export TARFILE1=MCD64monthly.A2021001.Win20.006.burndate.shapefiles.tar
export TARFILE2=MCD64monthly.A2021032.Win20.006.burndate.shapefiles.tar

#  password is published in the product user guide: https://modis-fire.umd.edu/files/MODIS_C6_BA_User_Guide_1.3.pdf
#  password is "burnt"
sftp -a sftp://fire@fuoco.geog.umd.edu/data/MODIS/C6/MCD64A1/SHP/Win20/2021/${TARFILE1}.gz
sftp -a sftp://fire@fuoco.geog.umd.edu/data/MODIS/C6/MCD64A1/SHP/Win20/2021/${TARFILE2}.gz

#  fails with errors
ogrinfo /vsitar/${TARFILE1}.gz
#  INFO: Open of `/vsitar/MCD64monthly.A2021001.Win20.006.burndate.shapefiles.tar.gz'
#      using driver `ESRI Shapefile' successful.
# ERROR 4: Unable to open /vsitar/MCD64monthly.A2021001.Win20.006.burndate.shapefiles.tar.gz/MCD64monthly.A2021001.Win20.006.burndate.shp or /vsitar/MCD64monthly.A2021001.Win20.006.burndate.shapefiles.tar.gz/MCD64monthly.A2021001.Win20.006.burndate.SHP.
# ERROR 4: Failed to open file /vsitar/MCD64monthly.A2021001.Win20.006.burndate.shapefiles.tar.gz/MCD64monthly.A2021001.Win20.006.burndate.shp.It may be corrupt or read-only file accessed in update mode.

#  works without error
ogrinfo /vsitar/${TARFILE2}.gz


#  unzipped tar file is processed without error
gzip -d ${TARFILE1}.gz
ogrinfo /vsitar/${TARFILE1}

#  After using ogr2ogr to make the topology valid,
#  the cleaned file is processed without error
#  (noting that makevalid arg needs a recent-ish version of GDAL - 3.2?)
#  Running ogr2ogr without -make_valid gives the same errors as above 
#  after data set is tarred and gzipped
ogr2ogr cleaned.shp /vsitar/${TARFILE1} -makevalid
tar cfv cleaned_file.tar cleaned.???
gzip cleaned_file.tar
ogrinfo /vsitar/cleaned_file.tar.gz

```

## Operating systems

Ubuntu 20.04.3 LTS (Focal Fossa) (via WSL2 on Windows 10)
CentOS Linux release 7.9.2009 (Core)
Windows 10

## GDAL version and provenance

Ubuntu:  3.0.4, via ```apt install gdal-bin```
CentOS:  3.4.2, locally compiled
Windows: 3.2.1, via sf library install under R 4.1.0

**Comment by jratike80** [comment]
I am not sure, maybe it is something else. The attached file contains a shapefile with polygon ` POLYGON ((240 400,360 280,140 280,260 200,240 400))` and `ogrinfo /vsitar/gdaltest.tar.gz -al` reads it from layer "invalid".

[gdaltest.tar.gz](https://github.com/OSGeo/gdal/files/7992763/gdaltest.tar.gz)

**Comment by rouault** [comment]
I don't manage to fetch MCD64monthly.A2021001.Win20.006.burndate.shapefiles.tar.gz through sftp . Can you attach that file here, or provide a link to a location where it can be easily downloaded ?

**Comment by shawnlaffan** [comment]
File attached.  

[MCD64monthly.A2021001.Win20.006.burndate.shapefiles.tar.gz](https://github.com/OSGeo/gdal/files/7998566/MCD64monthly.A2021001.Win20.006.burndate.shapefiles.tar.gz)

**Comment by shawnlaffan** [comment]
Thanks @rouault for the rapid diagnosis and fix.
