### ISSUE TITLE
CMake: cannot build with DODS

### ISSUE THREAD

**Issue by mathieu17g** [OSGeo/gdal#5252]
## Expected behavior and actual behavior.

I have lib dap version 3.20 installed, but `FindDAP.cmake` does not identify a DAP version > 3.10. Therefore symbol `LIBDAP_310` is not defined and the file `AISConnect.h` in tried to be included instead of `Connect.h`. Since `AISConnect.h` is not part anymore of libdap release 3.20, there is an error at build

The issue comes from `dap-config --version` called in `FindDAP.cmake` returns `libdap X.Y.Z` which is stored in `DAP_VERSION` CMake variable. 

https://github.com/OSGeo/gdal/blob/15860d15bb87b2a0036ea36a7525b78a9f86b5be/cmake/modules/packages/FindDAP.cmake#L55-L61

This variable is then compared to 3.9 or 3.10 with CMake boolean operation on versions `VERSION_GREATER` and `VERSION_EQUAL` which fails and `LIBDAP_310` is not defined

https://github.com/OSGeo/gdal/blob/15860d15bb87b2a0036ea36a7525b78a9f86b5be/frmts/dods/CMakeLists.txt#L7-L12

Then in `libdap_headers.h`, `#include <AISConnect.h>` fails

https://github.com/OSGeo/gdal/blob/15860d15bb87b2a0036ea36a7525b78a9f86b5be/frmts/dods/libdap_headers.h#L53-L59

It can be corrected by adding the following line after the `dap-config --version` call in `FindDAP.cmake`:
```cmake
if(DAP_INCLUDE_DIR AND DAP_LIBRARY)
    set(DAP_CONFIG_EXE dap-config)
    execute_process(COMMAND ${DAP_CONFIG_EXE} --version
           OUTPUT_VARIABLE DAP_VERSION
           OUTPUT_STRIP_TRAILING_WHITESPACE
    )
    # Isolate version in what dap-config --version returned
    string(REGEX MATCH "([0-9]+\\.)?([0-9]+\\.)?([0-9]+)" DAP_VERSION ${DAP_VERSION})
endif()
```

## Steps to reproduce the problem.

If the `dap-config` output is the same on every environnement, the problem should occur in every environnement, I guess
```
➜  build dap-config --version
libdap 3.20.9
➜  build
```

## Operating system

MacOSX 11.6.3

## GDAL version and provenance

GDAL master [79ff091](https://github.com/OSGeo/gdal/commit/79ff09114e2cca21633e8ef4e5fdddd093bee1ba), cloned via git

**Comment by rouault** [comment]
> It can be corrected by adding the following line after the `dap-config --version` call in `FindDAP.cmake`:

please issue a pull request with the suggested fix

Also note that if, beyond just fixing build issues, you've interested in the DODS drivers: https://github.com/OSGeo/gdal/issues/5173

**Comment by mathieu17g** [comment]
OK done. I not using DODS at all and do not plan to. 

I was just itched of having to set DODS to OFF in CMakeCache.txt repeatedly, since I did not want to solve the dependencies to be able to uninstall libdap
