### ISSUE TITLE
Feature Request: (GPKG driver) change dataset creation option DATETIME_FORMAT=WITH_TZ/UTC  to a layer creation option

### ISSUE THREAD

**Issue by Meibes** [OSGeo/gdal#5256]
Hello,

thanks for this awesome library!

I'm recently using ogr2ogr to convert some datasets into valid version 1.3 geopackages. Some of these datasets contain datetime information with and without timezone information. Using the "[DATETIME_FORMAT](https://gdal.org/drivers/vector/gpkg.html#dataset-creation-options)" dataset creation option enables me convert the datetime values with ease. The issue I'm facing is when I'm trying to create a geopackage with multiple layers (using ogr2ogr [-update](https://gdal.org/programs/ogr2ogr.html#cmdoption-ogr2ogr-update)). I can't use "DATETIME_FORMAT" here because the dataset already exists and therefore the datetime values don't get converted.

My current workaround is to create a geopackage for each layer and merge them all at the end to get the desired result. This works for me, but having a layer creation option instead of a dataset creation option would make this work even easier.

What do you think?

cheers

**Comment by rouault** [comment]
In https://github.com/OSGeo/gdal/pull/5263 I've followed another idea, which seems more efficient to me. When creating a database with DATETIME_FORMAT=UTC, a "OGR system" table "gpkg_ogr_metadata" will be created to store this setting, and this will be used on re-opening it. So you can then use ogr2ogr -update and the setting will be preserved.

**Comment by jratike80** [comment]
That does not feel totally problem-free. Users may get surprised because their datetimes sometimes get changed into UTC without warning and sometimes not even they use exactly same commands all the time. It may be too much to require that they should have a look at the gpkg_ogr_metadata before they add new tables. I think that average gis.stackexchange user does not know what is table or SQL. And tables added either with GDAL or with some other program could yield different results.

**Comment by rouault** [comment]
> That does not feel totally problem-free. Users may get surprised because their datetimes sometimes get changed into UTC without warning and sometimes not even they use exactly same commands all the time. It may be too much to require that they should have a look at the gpkg_ogr_metadata before they add new tables. I think that average gis.stackexchange user does not know what is table or SQL. And tables added either with GDAL or with some other program could yield different results.

the datetime gets changed into UTC because they first requested it at creation of the database. It seems to me that the property of being in "pedantic/compliant/UTC" mode is something you want for the whole file, not per layer.

**Comment by jratike80** [comment]
I agree that good practice is to have all the tables to use the same time mode. But users do not necessarily request UTC mode themselves but they may get a ready made geopackage somewhere and perhaps want to enhance it with their own data.

**Comment by rouault** [comment]
> But users do not necessarily request UTC mode themselves but they may get a ready made geopackage somewhere and perhaps want to enhance it with their own data.

maybe... but isn't that a bit of an edge case? What we could potentially is to add a DATETIME_FORMAT=UTC metadata item in the ogrinfo output if that may help (?)
Or maybe, better, emit a CPL warning the first time a datetime is converted into UTC when updating a database ? (that is in the same session where the option would have been set, we wouldn't emit it, but in an update scenario, yes)

**Comment by jratike80** [comment]
CPL warning might be good.
I was considering if we should use DATETIME_FORMAT=UTC in the geopackages that we at NLS create and deliver. I mean the metadata, times should already be in UTC because we try to follow the standard. But because our local time is UTC+2 it might mean to our customers that if they add their own data into gpkg not only hours but also day and even year may change if the timestamp is set to the first second of a day. But probably this is really an edge case.
When I tried to find examples from my computer I found one gpkg that has datetimes as
`2011-09-23T00:00:00` and dates as `2011-09-27Z`. Both are invalid to the letter of the standard but the datetime may be interpreted to mean either local time or UTC as discussed in https://github.com/opengeospatial/geopackage/issues/530.
But what is that `2011-09-27Z` expression? I understand what it means and it feels practical but ISO 8601 seems to support Z and other zones only for times https://en.wikipedia.org/wiki/ISO_8601.

**Comment by Meibes** [comment]
> When creating a database with DATETIME_FORMAT=UTC, a "OGR system" table "gpkg_ogr_metadata" will be created to store this setting, and this will be used on re-opening it

this is a good idea when you create the geopackage yourself

> the datetime gets changed into UTC because they first requested it at creation of the database

when you downloaded the gpkg from some website and try to add your own data, you might be surprised to have your data altered

> Users may get surprised because their datetimes sometimes get changed into UTC without warning

+1 that would be the case for me

> emit a CPL warning the first time a datetime is converted into UTC when updating a database

I don't think this is in line with the [DATETIME_FORMAT "Defaults to WITH_TZ"](https://gdal.org/drivers/vector/gpkg.html#dataset-creation-options) setting. this setting is in favor of the user "your data is not touched, even if it is not compliant with the specification" as opposed to "your data is converted to utc, but we give you a warning". there would also be the need to either add an option to alter the "gpkg_ogr_metadata" table, remove or ignore it. this way everytime you get in contact with a geopackage you have not created yourself, you would have to either check for the table "gpkg_ogr_metadata" or use the option to alter/remove/ignore this table, to be sure your data is untouched. another workaround would be to not touch any geopackages you receive at all but always create new geopackages and copy the contents before adding your own data.

I'm using gpkg on mobile devices and since storage and bandwidth capacity is limited on mobile devices, having another table with data that is not needed is just occupied space and takes more time to transfer

I was suggesting to convert it to a layer creation option because I thought that it would require the least amount of work. Another option could be to convert the values column based via something like "-convert_utc <field_list>", but i think that would better fit into ogr2ogr because this could also be used for other drivers

**Comment by rouault** [comment]
I've dropped https://github.com/OSGeo/gdal/pull/5263

**Comment by rouault** [comment]
Other approach in https://github.com/OSGeo/gdal/pull/7144: "ogr2ogr: add a -dateTimeTo option to convert datetime between timezones"

**Comment by Meibes** [comment]
> Other approach in #7144: "ogr2ogr: add a -dateTimeTo option to convert datetime between timezones"

this looks great!

> Datetime whose timezone is unknown or localtime are not modified.

1. I don't know what localtime means here. let' say my localtime is +02 and all my datetime is stored in +02. for the geopackage encoding standard I want to have all converted to UTC, so I guess I would be doing "-dateTimeTo UTC" - would my datetime stored in +02 (which is my localtime) be converted to UTC or not?

> Converts date time values from the timezone specified in the source value to the target timezone

2. the geopackage contains some internal columns like "last_change" that need to be in UTC, would they also be converted to +04 if I would use "-dateTimeTo UTC+04" ?
3. does this mean all my datetime columns are getting converted? e.g. if I have columns with different timezones: server_time (utc), client_time (different timezones) would all be converted to +06 if I use "-dateTimeTo UTC+06" or are there options to exclude/include columns?
4. would it be possible to add a convenience parameter like "-dateTimeTo localtime"? this would greatly help in dealing with daylight savings

**Comment by jratike80** [comment]
Local time is the time that is expressed without Z or +/-. My definition would be "the time I see in my wristwatch". Definition from https://en.wikipedia.org/wiki/ISO_8601#Local_time_(unqualified)

> Local time (unqualified)
> If no UTC relation information is given with a time representation, the time is assumed to be in local time. While it may be safe to assume local time when communicating in the same time zone, it is ambiguous when used in communicating across different time zones. Even within a single geographic time zone, some local times will be ambiguous if the region observes [daylight saving time](https://en.wikipedia.org/wiki/Daylight_saving_time). It is usually preferable to indicate a time zone (zone designator) using the standard's notation.

**Comment by rouault** [comment]
> 2\. the geopackage contains some internal columns like "last_change" that need to be in UTC, would they also be converted to +04 if I would use "-dateTimeTo UTC+04" ?

no. But Those should already be set in UTC

> does this mean all my datetime columns are getting converted?

yes

> or are there options to exclude/include columns?

no, seems too complicated

> would it be possible to add a convenience parameter like "-dateTimeTo localtime"? this would greatly help in dealing with daylight savings

GDAL cannot be sure if the localtime of the database is *your* localtime or the one of the creator of the database, hence I prefered excluding anything related to localtime.

**Comment by rouault** [comment]
> so unknown timezone is basically localtime?

GDAL has in theory both concepts: unknown and localtime. In practice, they are pretty similar... It could potentially assume that localtime = localtime of the machine and use that to do timezone shifts, but I'm not aware of any driver/code currently in GDAL doing something special with localtime
