### ISSUE TITLE
stale link in drivers/raster/rraster.rst

### ISSUE THREAD

**Issue by rsbivand** [OSGeo/gdal#5260]
The link in 

https://github.com/OSGeo/gdal/blob/master/doc/source/drivers/raster/rraster.rst 

to 

https://cran.r-project.org/web/packages/raster/vignettes/rasterfile.pdf 

is stale, please replace with 

https://rspatial.org/raster/pkg/appendix2.html

**Comment by jratike80** [comment]
There is a link "Edit on GitHub" on the top right corner of the page https://gdal.org/drivers/raster/rraster.html. Would you like to try it and create a Pull Request?

**Comment by rsbivand** [comment]
Thanks, PR #5261
