### ISSUE TITLE
GDAL Raster Calculator Overwrite Issue

### ISSUE THREAD

**Issue by ar-siddiqui** [OSGeo/gdal#5270]
## Expected behaviour and actual behaviour.

For GDAL Raster Calculator the expected behaviour is that without `--overwrite`, it will not overwrite an existing file and with `--overwrite` it will. The opposite of this is happening if you have the file open in another program, for example, QGIS.

Even when the file is not open in another program. GDAL still overwriting it without the `--overwrite` flag.

![image](https://user-images.githubusercontent.com/53625184/153117941-d15508e0-793f-4a3f-a9c4-710b844e09f8.png)

## Steps to reproduce the problem.
Open a raster in another program (ex QGIS) then run gdal raster calculator (with and without `--overwrite` flag) and overwrite a file that is open in another program.

## Operating system

Windows 10 64 bit

## GDAL version and provenance

GDAL version: 3.4.0

**Comment by rouault** [comment]
> The opposite of this is happening if you have the file open in another program, for example, QGIS.

Technically the file is not overwritten. It is updated in place... This is very similar to how gdalwarp operates.

But we should infer from the --format or --type argument that creation of a new file was intended and error out. And better documentation is also needed

**Comment by ar-siddiqui** [comment]
@rouault thanks for the resolution. Apart from documentation does the recent commit changes the behaviour of the raster_calc with or without `overwrite` flag?

**Comment by rouault** [comment]
> Apart from documentation does the recent commit changes the behaviour of the raster_calc with or without `overwrite` flag?

as implied by the commit message: "gdal_calc.py: raise error when overwriting behavior is apparently wished but not specified "
