### ISSUE TITLE
gdal-utils: improve command line in Windows and ditch .bat wrappers

### ISSUE THREAD

**Issue by maphew** [OSGeo/gdal#5281]
## Expected behavior and actual behavior.

To avoid having to call every script on the command line like this: `python path\to\gdal\Scripts\gdal_edit.py` on Windows after installing gdal-utils one myse either generate batchfile wrappers or change the PATHEXT variable and ASSOC  & FILETYPE commands. 

This method is well travelled enough that there is both a batch file helper script courtesy of Osgeo4w for some years as well as python utility for more easily creating the wrappers (see https://www.mail-archive.com/gdal-dev@lists.osgeo.org/msg37290.html). These help alleviate but do not remove the pain.

I believe using `entry_points` and  `console_scripts` in `setup.py` instead of the current `scripts` method can resolve this in a solid way that fixes Windows without impacting other platforms. When I've gone through some more testing I will issue a pull request.

## Steps to reproduce the problem.

n/a

## Operating system

Windows

## GDAL version and provenance

All

_cc @idanmiara_

**Comment by jratike80** [comment]
cc @jef-n
