### ISSUE TITLE
Issue with import of GMT grd files into new versions of Qgis

### ISSUE THREAD

**Issue by jescartin** [OSGeo/gdal#5291]
Issue loading NETCDF grd files intro QGIS (GDAL version 3.3.2)

Link to the file

https://github.com/qgis/QGIS/files/8044723/junk.zip

## Expected behavior and actual behavior.

NECDF files (GMT grd format), that could be opened in prior versions og QGIS (e.g., 20.1, GDAL version 3.2.3) do not display in the right position/scale in newer QGIS versions (e.g., 3.22, GDAL version 3.3.2).

## Steps to reproduce the problem.

Using QGIS - load .grd grid as a raster

See link above

## Operating system

mac OSX

## GDAL version and provenance

Not working for GDAL version 3.3.2
Working for GDAL version 3.2.3

**Comment by rouault** [comment]
Refs https://github.com/qgis/QGIS/issues/47158 / https://github.com/qgis/QGIS/issues/45704
hum, we likely need to add an heuristic for those GMT generated files
