### ISSUE TITLE
Creation options issue using gdal.driver.Create() function

### ISSUE THREAD

**Issue by eromero-es** [OSGeo/gdal#5295]
## Expected behavior and actual behavior.

I expect to form a composite raster using the GTiff driver with compression of my designation. My function takes several input rasters and creates a composite raster with each input as an individual band. I do this by creating an empty n-band raster with creation options.

I then  iterate over the input rasters and write each of them to their respective band in the empty output raster:

The expectation is that my raster will be written with the compression that I designated in the creation options. The expected size of the raster is ~2GB. Instead, the output raster is close to 90GB.

## Steps to reproduce the problem.

creation_options = ['BIGTIFF=IF_NEEDED', 'INTERLEAVE=BAND', 'COMPRESS=DEFLATE',
 'PREDICTOR=2', 'Tiled=YES', 'BLOCKXSIZE=256', 'BLOCKYSIZE=256', 'SPARSE_OK=True', 'NUM_THREADS=ALL_CPUS' ]

driver = gdal.GetDriverByName('GTiff')
out_ds = driver.Create(out_dir + '\\' + out_fn_ext, out_x_size, out_y_size, out_band_no + 1, gdalconst.GDT_Byte, 
                options=creation_options)
out_ds.SetProjection(out_proj)
out_ds.SetGeoTransform(out_gt)

for i, img in enumerate(in_dir_imgs):
       in_ds = gdal.Open(in_dir + '\\' + img)
       in_arr = in_ds.GetRasterBand(1).ReadAsArray().astype(np.byte)
 
       out_ds.GetRasterBand(i+1).WriteArray(in_arr)
       out_ds.GetRasterBand(i+1).SetNoDataValue(out_nodata)

## Operating system

Windows64

## GDAL version and provenance

GDAL 3.2.1 from Anaconda Install (Code above is Python 3.9.2)

**Comment by rouault** [comment]
how did you come with an estimate of 2 GB ? With what you provide only in the current description, this ticket is hard to address without access to your source images. Perhaps you could come with a simpler reproducer using the same source image (which could be a VRT of a small image), so that you can provide something that is fully self contained.

Did you try to use gdalbuildvrt -separate tmp.vrt source1 ... sourceN   followed by gdal_translate tmp.vrt final.tif [all creation options here] to compare ?

The only thing I can think of is if your datasets are made of a lot of nodata value, you should definitely call SetNoDataValue() before WriteArray().

**Comment by eromero-es** [comment]
I arrived at the 2GB estimate just by adding the file sizes of the input datasets which also use DEFLATE compression. I was able to find alternate work arounds by building a multi-band VRT of the input imagery and then translating the VRT to a GTiff via gdal.Translate() with gdal.TranslateOptions() indicated. Another work-around I found was for to create a multi-band dataset using the memory driver 'MEM' and then using gdal.driver.CreateCopy() with creation options indicated. 

I will try setting the nodata value before writing the array, but how would this explain the compression issue I seem to be having?

**Comment by rouault** [comment]
> I will try setting the nodata value before writing the array, but how would this explain the compression issue I seem to be having?

if your data is very sparse (lots of blocks at nodata), then GDAL needs to know the nodata value before blocks are written so that SPARSE_OK=True has effect

**Comment by eromero-es** [comment]
I see. I will give this a try and see if it has an effect. Thank you for your assistance.

**Comment by rouault** [comment]
@eromero-es  is this issue still relevant?

**Comment by eromero-es** [comment]
Hi again, sorry for not responding. Your recommendation solves my issue! Thank you.
