### ISSUE TITLE
Add division to VRT Default Pixel Functions

### ISSUE THREAD

**Issue by lpinner** [OSGeo/gdal#5298]
Suggest to add division (`div`) to VRT default pixel functions [[1](https://gdal.org/drivers/raster/vrt.html#default-pixel-functions), [2](https://github.com/OSGeo/gdal/blob/master/frmts/vrt/pixelfunctions.cpp)].

Would be useful where a python pixel function can't be used for whatever reason (e.g. performance, possibly locked down corporate environments) and avoids a complex `<SourceFilename etc...> <![CDATA[vrt xml string]]></SourceFilename>` inlining of VRT XML to combine `mul` and `inv` functions [[3](https://gis.stackexchange.com/a/423557/2856)]

**Comment by avalentino** [comment]
Dear @lpinner thanks for the interesting pointer to [3](https://gis.stackexchange.com/questions/423154/gdal-vrt-how-to-create-rgb-composite-from-two-input-geotiff-files-input1-inp/423557#423557), probably we should describe that trick in the user documentation or at lest have a link to the discussion.

Regarding the addition of the "div" pixel function I do not remember why it was not included in the base set of pixel functions at the beginning [1](https://trac.osgeo.org/gdal/ticket/3367).
I was planning to submit a PR to add some pixel functions (to improve conversion form/to dB and conversion form amp+phase to complex).
I could add also the "div" implementation to the PR.

@rouault do you have comments7recommendations?

**Comment by rouault** [comment]
> @rouault do you have comments7recommendations?

that sounds good
