### ISSUE TITLE
CI: build-windows-msys2-mingw disabled

### ISSUE THREAD

**Issue by rouault** [OSGeo/gdal#5317]
An upgrade in the msys2-mingw toolchain causes lots of warnings and errors to appear: https://github.com/OSGeo/gdal/runs/5216450145?check_suite_focus=true
We can not differences in the following packages:
``
$ diff -u /tmp/old.txt /tmp/new.txt
--- /tmp/old.txt	2022-02-16 14:56:34.422230084 +0100
+++ /tmp/new.txt	2022-02-16 14:56:22.422319897 +0100
@@ -1,4 +1,3 @@
-: Retrieving packages...
 mingw-w64-x86_64-gcc-11.2.0-8-any downloading...
 mingw-w64-x86_64-gcc-ada-11.2.0-8-any downloading...
 mingw-w64-x86_64-python-3.9.10-2-any downloading...
@@ -8,11 +7,11 @@
 mingw-w64-x86_64-cmake-3.22.2-1-any downloading...
 mingw-w64-x86_64-sqlite3-3.37.2-1-any downloading...
 mingw-w64-x86_64-gdb-multiarch-11.2-2-any downloading...
-mingw-w64-x86_64-binutils-2.37-4-any downloading...
-mingw-w64-x86_64-headers-git-9.0.0.6373.5be8fcd83-1-any downloading...
+mingw-w64-x86_64-binutils-2.37-5-any downloading...
+mingw-w64-x86_64-headers-git-9.0.0.6373.5be8fcd83-2-any downloading...
 mingw-w64-x86_64-openssl-1.1.1.m-1-any downloading...
 mingw-w64-x86_64-gdb-11.2-2-any downloading...
-mingw-w64-x86_64-crt-git-9.0.0.6373.5be8fcd83-1-any downloading...
+mingw-w64-x86_64-crt-git-9.0.0.6373.5be8fcd83-2-any downloading...
 mingw-w64-x86_64-gettext-0.21-3-any downloading...
 mingw-w64-x86_64-tcl-8.6.11-5-any downloading...
 mingw-w64-x86_64-tk-8.6.11.1-2-any downloading...
@@ -60,11 +59,11 @@
 mingw-w64-x86_64-mpc-1.2.1-1-any downloading...
 mingw-w64-x86_64-jansson-2.14-1-any downloading...
 mingw-w64-x86_64-libffi-3.3-4-any downloading...
-mingw-w64-x86_64-winpthreads-git-9.0.0.6373.5be8fcd83-1-any downloading...
-mingw-w64-x86_64-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any downloading...
+mingw-w64-x86_64-winpthreads-git-9.0.0.6373.5be8fcd83-2-any downloading...
+mingw-w64-x86_64-libwinpthread-git-9.0.0.6373.5be8fcd83-2-any downloading...
 mingw-w64-x86_64-termcap-1.3.1-6-any downloading...
 mingw-w64-x86_64-libsystre-1.0.1-4-any downloading...
 mingw-w64-x86_64-libb2-0.98.1-1-any downloading...
 mingw-w64-x86_64-libmangle-git-9.0.0.6373.5be8fcd83-1-any downloading...
-mingw-w64-x86_64-winstorecompat-git-9.0.0.6373.5be8fcd83-1-any downloading...
-mingw-w64-x86_64-windows-default-manifest-6.4-3-any downloading...
+mingw-w64-x86_64-winstorecompat-git-9.0.0.6373.5be8fcd83-2-any downloading...
+mingw-w64-x86_64-windows-default-manifest-6.4-4-any downloading...

**Comment by lazka** [comment]
Is this still a problem?

**Comment by dg0yt** [comment]
@lazka In my fork, it still happened 25 min ago. 
https://github.com/dg0yt/gdal/runs/5227868088?check_suite_focus=true

**Comment by lazka** [comment]
thanks. hm, the build logs indicated that the build is mixing msys2 mingw and choco mingw for some reason.

**Comment by dg0yt** [comment]
Mixing runtimes? Sounds familiar from vcpkg...

**Comment by mmuetzel** [comment]
@dg0yt: Looks like it is mixing a different (older) compiler with the headers from MSYS2/MINGW64.
During configure:
```
-- The C compiler identification is GNU 8.1.0
-- The CXX compiler identification is GNU 8.1.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/ProgramData/chocolatey/bin/gcc.exe - skipped
```
When building:
```
C:/tools/msys64/mingw64/include/stdio.h:1249:29: error: use of old-style cast to 'wint_t' {aka 'short unsigned int'} [-Werror=old-style-cast]
```

GCC in MSYS2/MINGW64 is currently version 11.2.0.

Does it work for you if you are using the compilers from MSYS2/MINGW64?

**Comment by rouault** [comment]
ok, I'm making progress in it per https://github.com/OSGeo/gdal/compare/master...rouault:restore_msys2_mingw?expand=1 . There are a few new warnings that need to be shut up. Investigating

**Comment by dg0yt** [comment]
I try to use msys2/setup-msys2@v2 in 
https://github.com/OSGeo/gdal/compare/master...dg0yt:mingw
