### ISSUE TITLE
regression: shapefile writer: writing large multilinestring features is very slow in 3.4.1

### ISSUE THREAD

**Issue by brendan-ward** [OSGeo/gdal#5321]
## Expected behavior and actual behavior.

Writing features with MultiLineString geometries with a large number (>10,000) of LineStrings should be successful and perform like in 3.3.x.

Under GDAL 3.4.0 and 3.4.1, writing MultiLineString geometries with a large number of LineStrings is very slow or hangs for larger datasets (eventually killed process).

Under GDAL 3.3.x, writing these same features does not experience these slowdowns.

I did not see anything in the NEWS or existing pull requests or issues that indicates this is expected or has already been reported.

## Steps to reproduce the problem.

For attached geopackage, attempting to write using the features to a shapefile using the C API or ogr2ogr is very slow (several minutes) using GDAL 3.4.0 and 3.4.1, tested using Docker containers `osgeo/gdal:ubuntu-small-3.4.0`, `osgeo/gdal:ubuntu-small-3.4.1`.  (also on MacOS GDAL 3.4.1 via homebrew).

Writing the same geopackage to shapefile using `osgeo/gdal:ubuntu-small-3.2.3` completes quickly (a couple seconds), as expected.

`ogr2ogr test.shp test.gpkg -progress`

[test.gpkg.zip](https://github.com/OSGeo/gdal/files/8081904/test.gpkg.zip)

## Operating system

MacOS 10.15 and GDAL Ubuntu small Docker container (running on MacOS host).

## GDAL version and provenance

GDAL 3.4.0 and 3.4.1 experience this issue.  GDAL 3.2.3 does not.

**Comment by jratike80** [comment]
Confirmed on Windows with GDAL 3.4.0.
