### ISSUE TITLE
CMake build on Ubuntu 21.10 failing on expat

### ISSUE THREAD

**Issue by andrew-aitchison** [OSGeo/gdal#5324]
## Expected behavior and actual behavior.

cmake .

## Steps to reproduce the problem.
cd builddir
cmake -B . -S ~/git/gdal

## Expected behavior: 
Output ends with
-- Configuring done
-- Generating done

## Actual behavior: 
Output ends with (blank lines reduced):

-- Configuring done
CMake Error in CMakeLists.txt:
  Imported target "expat::expat" includes non-existent path
    "/usr/lib/include"
  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:
  * The path was deleted, renamed, or moved to another location.
  * An install or uninstall procedure did not complete successfully.
  * The installation package was faulty and references files it does not provide.

CMake Error in CMakeLists.txt:
  Imported target "expat::expat" includes non-existent path
    "/usr/lib/include"
  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:
  * The path was deleted, renamed, or moved to another location.
  * An install or uninstall procedure did not complete successfully.
  * The installation package was faulty and references files it does not provide.

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.

Yes, the error is reported twice.

## Operating system
Ubuntu 21.10 64 bit

## GDAL version 
Checked out from github.com/OSGeo/gdal master on 16 Feb 2022.

## Comments
Ubuntu 21.10 (and presumably the LTS version 22.04 due in April)
has a new(ish) version of expat which suffers from
   https://github.com/libexpat/libexpat/issues/501
  
The expat developer hartwork recognised the issue in July 2021 but said:
  Confirming for --includedir= and (for some cases) of --libdir=.  A clean universal fix is not trivial and the issue can be worked 
  around on packaging level (downstream) rather easily, so it's not very high priority right now.

Not sure whether Hartwork means the OS or package level and it is not obvious to me where to look to fix this.

I note that since github.com/OSGeo/gdal/issues/5178 the docker version has an even more recent version of expat.

**Comment by rouault** [comment]
Fix queued in https://github.com/OSGeo/gdal/pull/5326
A workaround is to add  `-DGDAL_CHECK_PACKAGE_EXPAT_TARGETS=` to the cmake invokation

**Comment by dg0yt** [comment]
Was this also reported to Ubuntu and/or Debian?

**Comment by rouault** [comment]
> Was this also reported to Ubuntu and/or Debian?

I've just checked with debian:unstable and ubuntu:jammy and it works fine there, so it looks to be 21.10 issue only
