### ISSUE TITLE
[COG] ALIGNED_LEVELS=1 has no effect on the COG

### ISSUE THREAD

**Issue by vincentsarago** [OSGeo/gdal#5336]
## Expected behavior and actual behavior.

Passing `ALIGNED_LEVELS=1` seems to have no effects on the COG while I was assuming it should aligned the first overview level with the grid 

## Steps to reproduce the problem.

```
# Create COG with different Aligned Levels
gdal_translate -of COG non_cog.tif cog.tif -co TILING_SCHEME=GoogleMapsCompatible -co COMPRESS=DEFLATE -co OVERVIEWS=IGNORE_EXISTING -co ALIGNED_LEVELS=0
gdal_translate -of COG non_cog.tif cog_1.tif -co TILING_SCHEME=GoogleMapsCompatible -co COMPRESS=DEFLATE -co OVERVIEWS=IGNORE_EXISTING -co ALIGNED_LEVELS=1
gdal_translate -of COG non_cog.tif cog_2.tif -co TILING_SCHEME=GoogleMapsCompatible -co COMPRESS=DEFLATE -co OVERVIEWS=IGNORE_EXISTING -co ALIGNED_LEVELS=2

# Check the origin (using the geoTransform)
$ gdalinfo cog.tif -json | jq -c '.geoTransform'
[-8843764.172594892,1.1943285669557164,0,4848553.578185299,0,-1.1943285669557928]

$ gdalinfo cog_1.tif -json | jq -c '.geoTransform' 
[-8843764.172594892,1.1943285669557164,0,4848553.578185299,0,-1.1943285669557928]

$ gdalinfo cog_2.tif -json | jq -c '.geoTransform' 
[-8844069.920708034,1.194328566955907,0,4848553.578185299,0,-1.1943285669557928]
```

👇 are screenshot made using [tilebench](https://github.com/developmentseed/tilebench) to visualize the shape of internal tiles vs mercator tile. 

`ALIGNED_LEVEL=1` : internal tile of the first overview (red) vs mercator grid (blue)
![ALIGNED_LEVEL=1](https://user-images.githubusercontent.com/10407788/154484153-ffc96f7a-0f4e-437a-b89b-17a19e1e2a16.png)

`ALIGNED_LEVEL=2`: internal tile of the first overview (red) vs mercator grid (blue)
![ALIGNED_LEVEL=2](https://user-images.githubusercontent.com/10407788/154484225-36bcc312-6522-4c21-8034-b4f80fc236d7.png)

## Operating system

Mac OS, homebrew

## GDAL version and provenance
```
gdalinfo --version
GDAL 3.4.1, released 2021/12/27
```

**Comment by rouault** [comment]
The effect of this option starts at 2 indeed, since the full resolution level is "naturally" aligned. Perhaps the doc should say " Number of resolution levels" (instead of "Number of overview levels"), and mention that it should be a minimum of 2 ?

**Comment by vincentsarago** [comment]
> Number of resolution levels" (instead of "Number of overview levels")

Yes, I guess this will be better.
