### ISSUE TITLE
TILING_SCHEME=GoogleMapsCompatible generating non-square/unaligned COG's

### ISSUE THREAD

**Issue by Plantain** [OSGeo/gdal#5343]
## Expected behavior and actual behavior.

Expected behaviour:
If a COG is created with TILING_SCHEME=GoogleMapsCompatible, the COG's tiles should be aligned and tiled to the GoogleMapsCompatible Scale Set. (https://gdal.org/drivers/raster/cog.html)

Actual behaviour:
The COG is misaligned, with a non-square pixel resolution and trying to serve directly from this COG requires double the requests to load each tile to match Web Mercator.

Originally from: https://github.com/developmentseed/titiler/issues/431

## Steps to reproduce the problem.
http://static2.skysight.io/himawari.tiff is a sample file (GEOS projected satellite imagery)

```
gdal_translate himawari.tiff himawari-googlemaps.tiff -of COG -co TILING_SCHEME=GoogleMapsCompatible -co COMPRESS=JPEG -co NUM_THREADS=ALL_CPUS -co ZOOM_LEVEL_STRATEGY=UPPER
```

Observe the non-square pixel size:
Pixel Size = (1222.992452562820063,-1222.992452562820290)

```
gdalinfo himawari-googlemaps.tiff 
Driver: GTiff/GeoTIFF
Files: himawari-googlemaps.tiff
Size is 32768, 25088
Coordinate System is:
PROJCRS["WGS 84 / Pseudo-Mercator",
    BASEGEOGCRS["WGS 84",
        DATUM["World Geodetic System 1984",
            ELLIPSOID["WGS 84",6378137,298.257223563,
                LENGTHUNIT["metre",1]]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433]],
        ID["EPSG",4326]],
    CONVERSION["Popular Visualisation Pseudo-Mercator",
        METHOD["Popular Visualisation Pseudo Mercator",
            ID["EPSG",1024]],
        PARAMETER["Latitude of natural origin",0,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",0,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["False easting",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["easting (X)",east,
            ORDER[1],
            LENGTHUNIT["metre",1]],
        AXIS["northing (Y)",north,
            ORDER[2],
            LENGTHUNIT["metre",1]],
    USAGE[
        SCOPE["Web mapping and visualisation."],
        AREA["World between 85.06°S and 85.06°N."],
        BBOX[-85.06,-180,85.06,180]],
    ID["EPSG",3857]]
Data axis to CRS axis mapping: 1,2
Origin = (-20037508.342789243906736,15341217.324948014691472)
Pixel Size = (1222.992452562820063,-1222.992452562820290)
Metadata:
  AREA_OR_POINT=Area
  TIFFTAG_DATETIME=2022:02:05 00:00:20
Image Structure Metadata:
  COMPRESSION=YCbCr JPEG
  INTERLEAVE=PIXEL
  JPEGTABLESMODE=1
  JPEG_QUALITY=75
  LAYOUT=COG
  SOURCE_COLOR_SPACE=YCbCr
Tiling Scheme:
  NAME=GoogleMapsCompatible
  ZOOM_LEVEL=7
Corner Coordinates:
Upper Left  (-20037508.343,15341217.325) (180d 0' 0.00"W, 79d41'13.86"N)
Lower Left  (-20037508.343,-15341217.325) (180d 0' 0.00"W, 79d41'13.86"S)
Upper Right (20037508.343,15341217.325) (180d 0' 0.00"E, 79d41'13.86"N)
Lower Right (20037508.343,-15341217.325) (180d 0' 0.00"E, 79d41'13.86"S)
Center      (   0.0000000,  -0.0000000) (  0d 0' 0.01"E,  0d 0' 0.00"S)
Band 1 Block=256x256 Type=Byte, ColorInterp=Red
  NoData Value=0
  Overviews: 16384x12544, 8192x6272, 4096x3136, 2048x1568, 1024x784, 512x392, 256x196
Band 2 Block=256x256 Type=Byte, ColorInterp=Green
  NoData Value=0
  Overviews: 16384x12544, 8192x6272, 4096x3136, 2048x1568, 1024x784, 512x392, 256x196
Band 3 Block=256x256 Type=Byte, ColorInterp=Blue
  NoData Value=0
  Overviews: 16384x12544, 8192x6272, 4096x3136, 2048x1568, 1024x784, 512x392, 256x196
```

## Operating system
Ubuntu 20.04
## GDAL version and provenance
GDAL 3.3.2, released 2021/09/01

**Comment by jratike80** [comment]
Looks very square to me `Pixel Size = (1222.992452562820063,-1222.992452562820290)`. Do you mean the very last digits?

**Comment by Plantain** [comment]
Yes - it seems to be enough error that the tiles are slightly offset from clients correctly calculating the OGC GoogleMapsCompatible Scale Set.

(see https://github.com/developmentseed/titiler/issues/431 for example on how this propagates)

**Comment by jratike80** [comment]
The twelve first decimals are equal. It means picometers difference in a 1.2 kilometers tile.
I believe that there is bug somewhere but I think that the fix must happen in some other place.

**Comment by vincentsarago** [comment]
sorry I didn't think about this earlier @Plantain, but we can force GDAL to fix the resolution:

```bash
$ gdal_translate -of COG himawari.tiff himawari_cog.tif \
-co TILING_SCHEME=GoogleMapsCompatible \
-co COMPRESS=JPEG \
-co ZOOM_LEVEL_STRATEGY=UPPER \
-co RES=1222.99245256282 
```

Sadly this don't totally fix the issue 😭, I'm still able to see some tile request with 3 GET (but less then before), so maybe there are other issue at play.

**Comment by Plantain** [comment]
I don't think that helps, because unless the documentation is wrong, if
TILING_SCHEME is set, RES is ignored.
"In non-CUSTOM mode, TARGET_SRS, RES and EXTENT options are ignored."

**Comment by jratike80** [comment]
Try again by adding the ALIGNED_LEVELS creation option.  You seem to need 8 levels.


> ALIGNED_LEVELS=INT: Number of resolution levels for which GeoTIFF tile and tiles defined in the tiling scheme match. When specifying this option, padding tiles will be added to the left and top sides of the target raster, when needed, so that a GeoTIFF tile matches with a tile of the tiling scheme. Only taken into account if TILING_SCHEME is different from CUSTOM. Effect of this option is only visible when settting it at 2 or more, since the full resolution level is by default aligned with the tiling scheme. For a tiling scheme whose consecutive zoom level resolutions differ by a factor of 2, care must be taken in setting this value to a high number of levels, as up to 2^(ALIGNED_LEVELS-1) tiles can be added in each dimension. The driver enforces a hard limit of 10.

**Comment by rouault** [comment]
I've queued https://github.com/OSGeo/gdal/pull/5345 to make sure that the COG driver output exactly square pixels when using -co TILING_SCHEME. Could you test that branch ?
But honestly I feel there's something wrong on the reading side of your software stack. It should be much more tolerant to tiny differences in floating-point values. I suspect some truncation to integer instead of rounding to closest is missing. (well, I won't be too peremptory and can't exclude it might end up being in GDAL depending on what you use exactly in it, but if you use the RasterIO() interface of GDAL, it takes (line,col) integer, so the caller is responsible for properly computing them)
You could also potentially try to use the JSON definition of http://docs.opengeospatial.org/is/17-083r2/17-083r2.html#73 (after replacing editorial quotes by ASCII double quotes), call it tms_GMAP.json for example, put it in the GDAL_DATA directory and use -co TILING_SCHEME=GMAP  to see if the slight difference of origins has an influence. But note that GDAL will actually only use the values at zoom level 0, in particular the resolution, and will compute it for the higher zoom levels by dividing by power of twos). But still, the values from the OGC examples should probably be taken with caution, as they're rounded to limited accuracy, slighly smaller than the one of a 64 bit double, whereas GDAL uses full 64-bit double accuracy.

**Comment by vincentsarago** [comment]
thanks so much, all of this is really helpful 🙏 

> I'd say it is a Lanczos kernel (whose radius is 3) Is it something the user can set, and if not which resampling method is set ?

🤷, I'm using rasterio directly without any magic. Resampling is set to `nearest`. 

I'm also working on the rio-tiler side, to see if I'm not doing something stupid (once again 😄 )

**Comment by rouault** [comment]
> What I can't explain is why you have requests with a 256x128 dest block.

ok thanks to the help of @vincentsarago to setup a replication environment, the explanation is quite simple: rasterio creates a warped VRT of 256x256 pixels (I was expecting it to be the full size raster for some reason...), and the m_nBlockXSize is initialized to std::min( nXSize, 512 ), so min (256,512)=256.

with PR #5345 and particularly its second commit, ``tilebench  profile http://0.0.0.0:8000/himawari_cog.tif --tile  7-72-58 --config GDAL_INGESTED_BYTES_AT_OPEN=200000 --config GDAL_DISABLE_READDIR_ON_OPEN=EMPTY_DIR --add-kernels  | jq . `` now shows
```json
{
  "LIST": {
    "count": 0
  },
  "HEAD": {
    "count": 1
  },
  "GET": {
    "count": 2,
    "bytes": 229376,
    "ranges": [
      "0-212991",
      "26574848-26591231"
    ]
  },
  "WarpKernels": [
    [
      "Src=18432,11008,256x128",
      "Dst=0,0,256x128"
    ],
    [
      "Src=18432,11136,256x128",
      "Dst=0,128,256x128"
    ]
  ],
  "Timing": 0.04473876953125
}
```

wheras without it, it shows:
```
{
  "LIST": {
    "count": 0
  },
  "HEAD": {
    "count": 1
  },
  "GET": {
    "count": 3,
    "bytes": 245760,
    "ranges": [
      "0-212991",
      "26574848-26591231",
      "27164672-27181055"
    ]
  },
  "WarpKernels": [
    [
      "Src=18432,11008,256x129",
      "Dst=0,0,256x128"
    ],
    [
      "Src=18432,11136,256x129",
      "Dst=0,128,256x128"
    ]
  ],
  "Timing": 0.04548335075378418
}
```

**Comment by Plantain** [comment]
In the example I provided, yes, I was using titiler with resampling=lanczos.

**Comment by vincentsarago** [comment]
> rasterio creates a warped VRT of 256x256 pixels (I was expecting it to be the full size raster for some reason...),

Yes, I always forget but this was made to make sure we fetch the overview (I don't remember why exactly, this was written  by Sean some time ago I think).

**Comment by rouault** [comment]
> In the example I provided, yes, I was using titiler with resampling=lanczos.

third commit in PR #5345 should help for that case too

**Comment by blacha** [comment]
> maybe @blacha could validated that he never had any issue with Web aligned COG vs GET requests

I havent noticed any, But then I havent really been paying that much attention to individual tile requests, I will write a script to validate all our COGs against this.

Am I correct in assuming this only applies to COGs that have been warped/reprojected?
