### ISSUE TITLE
Feature request: support dynamic C++ pixel functions

### ISSUE THREAD

**Issue by mmomtchev** [OSGeo/gdal#5353]
The current C++ API for adding pixel functions expects a single pointer to function:
https://github.com/OSGeo/gdal/blob/79be49e6791f262de2182cacf6773eae785bcb5c/gcore/gdal.h#L1106

The corresponding function will then be called with this signature:
https://github.com/OSGeo/gdal/blob/79be49e6791f262de2182cacf6773eae785bcb5c/gcore/gdal.h#L963

This does not allow for dynamic functions that are not known at compile time - especially when interpreting a function in another language - because in this case all pixel functions will point to the same C++ function.

As this API was very recently modified, adding a second form of the method for adding functions, I am somewhat reticent of adding a third one, unless 

These are the only options I was able to come up with:
* Adding a classical `void*` argument to be passed back to the function - which is ideal but it adds a 3rd form of this API
* Passing the function name or some form of an id in a `kwarg`  along the other optional function arguments - which minimizes the API change but it goes against the logic of this API
* Adding a method that allows the C++ user to create himself the lambda that is used internally - leaving the C user out in the cold

If you have some time to spare and you have a knack for C obfuscation contests you can check this guy proposal, who claims to have invented C++ dynamic function pointers - but it is in fact, simply a very fancy way of creating a static array of X lambdas and then getting C function pointers to them: https://stackoverflow.com/questions/44051517/dynamically-create-a-function-and-get-a-pointer

Any other ideas? Suggestions?

**Comment by dbaston** [comment]
> Passing the function name or some form of an id in a kwarg along the other optional function arguments - which minimizes the API change but it goes against the logic of this API

This seems like a reasonable solution to me, especially since some amount of translation is likely needed between the arguments provided by GDAL and the arguments expected by a function written in an interpreted language. Why do you say it goes against the logic of this API?

**Comment by mmomtchev** [comment]
Because it is a list of arguments and because this will add an additional string operation at every function call - for a feature that will be rarely used - but yes, it is probably the best solution

**Comment by mmomtchev** [comment]
@rouault, @dbaston 

Ok, so here is my proposal:

```xml
<PixelFunctionArgumentsList>
    <DataTypes>
        <Value>Float32</Value>
        <Value>Float64</Value>
    </DataTypes>
    <Argument name='y' description='Value to add to all results' type='double' default='0' mandatory='YES'>
    </Argument>
    <Argument name='rounding' description='Integer rounding used' type='string-select' default='MATH'>
        <Value>CAST</Value>
        <Value>MATH</Value>
    </Argument>
    <Argument name='fast' type='boolean' default='YES'>
    </Argument>
    <Argument builtin='NoData'>
    </Argument>
    <Argument builtin='offset'>
    </Argument>
    <Argument builtin='scale'>
    </Argument>
    <Argument constant='tableId' value='FEA0AB'>
    </Argument>
</PixelFunctionArgumentsList>
```

If there is no metadata, it works as before. If there is metadata, it is checked before calling the function, throwing an error if something doesn't fit in.
Three types of arguments: the current arguments from the VRT XML, some builtins and the possibility to set a constant to be included in each call.

**Comment by rouault** [comment]
CC @avalentino  too

Is DataTypes the list of allowed eBufType values, i.e. the type of the output buffer ? Why is that needed ? 
Otherwise looks good to me

**Comment by rouault** [comment]
> Can the input and output types be different?

yes, you have the SourceTransferType (from the VRT XML) which is the one used to request the sources, and is communicated with the eSrcType parameter to the pixel function. And eBufType is the type of the output pData buffer : it is not necessarily the data type of the VRT band as the caller of the RasterIO() method can ask for any output data type.

**Comment by mmomtchev** [comment]
Ok, so there must be separate `SrcDataTypes` and `OutDataTypes` - with the function considered to support everything when not specified

**Comment by rouault** [comment]
> Ok, so there must be separate `SrcDataTypes` and `OutDataTypes` - with the function considered to support everything when not specified - or maybe all output types are to be supported in all cases?

all existing pixel functions support all output data types as far as I can see (sometimes the conversion to the output data type will be very lossy, but that's the responsibility of the user). And for input data types, this is also the case except for SqrtPixelFunc() or a few other functions which reject complex data types.  As the pixel function get the source and output data types as options, it doesn't seem necessary to me to add special validation for that in the vrtderivedrasterband.cpp file.

**Comment by mmomtchev** [comment]
I was thinking about a pixel function converting `NoData` to `NaN` - that will work only for floating data types - but this can be solved by returning an error from the pixel function

**Comment by mmomtchev** [comment]
@rouault, I also wonder about adding
* builtins (`NoData`, `scale` and `offset`) access from Python pixel functions, currently only C++ functions that ask for them in their metadata will get them
  - either through additional statements in the VRT
  - either by making them available to every function 

* adding `SetPixelFunction` and its `RasterIO` support to all datasets - without saving it in the file
  - including support for setting a builtin pixel function from Python

**Comment by rouault** [comment]
> builtins (`NoData`, `scale` and `offset`) access from Python pixel functions, currently only C++ functions that ask for them in their metadata will get them
> 
>     * either through additional statements in the VRT
> 
>     * either by making them available to every function

We can't add them to the regular args by default without breaking backward compatibility  (unless there's a way in python to know if a callable has X number of regular arguments), so if we add them to every function that would be in the kwargs. Or through explicit user request but that's probably more convoluted.

> adding SetPixelFunction and its RasterIO support to all datasets - without saving it in the file.     including support for setting a builtin pixel function from Python

I didn't understand that

**Comment by rouault** [comment]
> Adding the ability to use a pixel function on a regular dataset

how would you do that ? You can use a non-serialized VRT file too (if you create it with "" empty name)

**Comment by mmomtchev** [comment]
What would prevent me from applying a pixel function in the generic `RasterIO`?

But, yes, never mind, this solves my problem. I suppose I can stack this several times too? So no need to add support for chaining pixel functions either?

**Comment by rouault** [comment]
implemented per https://github.com/OSGeo/gdal/pull/5371
