### ISSUE TITLE
Shape: Difference between GDAL and ESRI with special polygons

### ISSUE THREAD

**Issue by jratike80** [OSGeo/gdal#5356]
ESRI considers self-intersecting polygons valid if intersection happens at one vertex. This is a well known case when a hole is made from a loop in a boundary
![kuva](https://user-images.githubusercontent.com/1751612/154910636-baaeb7b6-ed8a-47df-b387-94e23cfdc649.png)

and for example PostGIS considers it as valid when the ESRI flag is used
```
select ST_IsValidReason(
ST_GeomFromText('POLYGON (( 260 193, 260 235, 329 234, 325 157, 257 160, 260 193, 283 170, 287 207, 260 193 ))'),1);
```

However, a ring may intersect itself at one point also in another way as shown in https://esri.github.io/geometry-api-java/doc/Polygon.html
![kuva](https://user-images.githubusercontent.com/1751612/154911505-f9c5a204-3b2e-4584-9ad2-b65ba18fb1dd.png)

I confirmed that such polygon is valid for ArcGIS desktop 10.8. For PostGIS it is invalid even when the ESRI flag is set 

```
select ST_IsValidReason(
ST_GeomFromText('POLYGON (( 363 239, 408 278, 355 320, 452 321, 408 278, 451 236, 363 239 ))'),1)
"Interior is disconnected"
```

The issue with GDAL is that if I save this butterfly-shaped polygon into shapefile then ArcGIS does open the shape but the Check geometries tool reports an error. It finds a feature with FID -1 and with problem "spatial index is not found"

![kuva](https://user-images.githubusercontent.com/1751612/154913108-835c38de-6fc2-440e-a64e-0283d37433f7.png)

I attach a shapefile created by GDAL that ArcMap does not like and another one that it likes because it is created by itself.

This is a corner case but I created an issue because I spent so much time when I tried to understand a problem with our municipality data and I had all the notes at hand. I tag @pramsey if the case happens to interest.

[esri_butterfly.zip](https://github.com/OSGeo/gdal/files/8107389/esri_butterfly.zip)
[gdal_butterfly.zip](https://github.com/OSGeo/gdal/files/8107390/gdal_butterfly.zip)

I suppose that the butterfly polygons in our data are written by FME but it may be that our tailor made process is feeds the geometires into the ETL process.

**Comment by rouault** [comment]
@jratike80 Are you sure you've attached the right files ? The .shp and .shx files of esri_butterfly and gdal_butterfly are binary identical.

**Comment by jratike80** [comment]
The files were right but it appears that the geometry validator in ArcMAP wants to find also the .sbn and .sbx files. This is not documented in https://desktop.arcgis.com/en/arcmap/latest/tools/data-management-toolbox/check-geometry.htm but when I deleted .sbn and .sbx files I got the same error for esri_butterfly shape.
