### ISSUE TITLE
OSGeo4W: gdalinfo fails for jpg/jpeg

### ISSUE THREAD

**Issue by pathmapper** [OSGeo/gdal#5368]
Similar issue as https://github.com/OSGeo/gdal/issues/3284.

Opened https://trac.osgeo.org/osgeo4w/ticket/730, **posting this also here to be able to provide a sample image**.

---

## Expected behavior and actual behavior.

`gdalinfo` doesn't error for the following jpg: [test.zip](https://github.com/OSGeo/gdal/files/8115614/test.zip)

`gdalinfo` errors with
```
ERROR 1: libjpeg: Bogus Huffman table definition
gdalinfo failed - unable to open 'test.JPG'.
```

## Steps to reproduce the problem.

`gdalinfo test.JPG`

## Operating system

Windows 10

## GDAL version and provenance

GDAL 3.4.1, released 2021/12/27 installed with OSGeo4W Shell along with QGIS 3.22.3 (standalone installer https://qgis.org/downloads/QGIS-OSGeo4W-3.22.3-1.msi)

**Comment by pathmapper** [comment]
Another sample jpg [test2.zip](https://github.com/OSGeo/gdal/files/8115730/test2.zip) with a different error:

```
gdalinfo test2.JPG
Warning 1: libjpeg: Corrupt JPEG data: 10 extraneous bytes before marker 0xc4 (this warning can be turned as an error by setting GDAL_ERROR_ON_LIBJPEG_WARNING to TRUE)
ERROR 1: libjpeg: Invalid component ID 2 in SOS
gdalinfo failed - unable to open 'test2.JPG'.

```

**Comment by rouault** [comment]
CC @jef-n
This seems to be a OSGeo4W specific issue. I can open this image fine on my own build of GDAL master on Windows, using conda-forge as source for dependencies and using its jpeg-9d library.

Actually looking at https://github.com/jef-n/OSGeo4W/blob/master/src/gdal/osgeo4w/nmake.opt, I see it uses the internal libjpeg-6b copy of GDAL. On GDAL 3.4 this did *not* cause the libjpeg symbols to be renamed (this has been added in GDAL master in CMake builds), so maybe there's a conflict between GDAL internal libjpeg copy and another dependency of GDAL that would use an external libjpeg ?

The GDAL commit that introduced the symbol renaming is https://github.com/OSGeo/gdal/commit/f3090267d5c30e4560df5cde7ee3c805a8a2ddab . I didn't want to backport this to official 3.4 as a bit too large, but it could perhaps be used for OSGeo4W. It would require the /DRENAME_INTERNAL_LIBJPEG_SYMBOLS flag to be a general flag of the GDAL build (not just in frmts/jpeg makefile.vc)

**Comment by pathmapper** [comment]
Fixed in https://github.com/jef-n/OSGeo4W/commit/e71eabec0fd0f976703b7d600aea1be29b55ae2a, thanks @rouault and @jef-n !
