### ISSUE TITLE
`gdal` installed from `conda-forge` as a dependency fails to install properly but no alarm raised (old OS with very early GLIBC)

### ISSUE THREAD

**Issue by valeriupredoi** [OSGeo/gdal#5375]
## Context

Hey guys, something that might help others if you consider implementing a fix for this issue; not critical, but nice :grin: 

Here's the setting: I am on a machine that has a very old OS, hence a very early GLIBC, and I am creating a `conda` environment with `miniconda`, I am installing a package there that needs `gdal` as dependency (e.g. installing `fiona` that will install `gdal` as its dependency), then I am trying to use the package that I just installed in my virtual env, and all hell breaks loose from the get going. Most of the times the errors I'll get will be obscure, and will marginally point to an issue with `gdal` if at all, let alone telling me that `gdal` was not properly installed; if I run me a `gdalinfo --version` or any executable from within `gdal` the issue will become obvious (see below), but sometimes it won't be straightforward that there is a faulty installation of GDAL in the midst of the kerfuffle so a user will not even think of checking if the `gdal` installation went well; conda says nothing and tells you all packages were installed correctly.

## Expected behavior and actual behavior.

A conda/mamba installation of a package that needs GDAL as a dependency, therefore installs it in a Python virtual environment, does not raise any alarm bells if GDAL was not installed correctly due to an old GLIBC (fails silently?), I would expect a warning, if not an exception and termination of the install process if the required `GLIBC_2.xx` is not found.

## Steps to reproduce the problem.

`mamba install -c conda-forge fiona` on a machine with GLIBC<2.14

## Operating system

```
LSB Version:    :base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID: RedHatEnterpriseServer
Description:    Red Hat Enterprise Linux Server release 6.10 (Santiago)
Release:        6.10
Codename:       Santiago

> ldd --version
ldd (GNU libc) 2.12
Copyright (C) 2010 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

## GDAL version and provenance

```

> mamba --version
mamba 0.21.2
conda 4.11.0

> python -V
Python 3.10.2

> mamba list gcc && mamba list gxx
# packages in environment at /mnt/lustre02/work/bd0854/b309141/mambaforge/envs/xxx:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
gcc                       9.4.0                h192d537_5    conda-forge
gcc_impl_linux-64         9.4.0               h03d3576_12    conda-forge
gcc_linux-64              9.4.0                h391b98a_5    conda-forge
libgcc-devel_linux-64     9.4.0               hd854feb_12    conda-forge
libgcc-ng                 11.2.0              h1d223b6_12    conda-forge
# packages in environment at /mnt/lustre02/work/bd0854/b309141/mambaforge/envs/xxx:
#
# Name                    Version                   Build  Channel
gxx                       9.4.0                h192d537_5    conda-forge
gxx_impl_linux-64         9.4.0               h03d3576_12    conda-forge
gxx_linux-64              9.4.0                h0316aca_5    conda-forge

> mamba list gdal
# packages in environment at /mnt/lustre02/work/bd0854/b309141/mambaforge/envs/xxx:
#
# Name                    Version                   Build  Channel
gdal                      3.4.1           py310h222ae0d_3    conda-forge
libgdal                   3.4.1                hc3d8651_3    conda-forge
```

## Here's where the show stops

```
> which gdalinfo && gdalinfo --version
/mnt/lustre02/work/bd0854/b309141/mambaforge/envs/xxx/bin/gdalinfo
gdalinfo: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /mnt/lustre02/work/bd0854/b309141/mambaforge/envs/xxx/bin/../lib/libgdal.so.30)
gdalinfo: /lib64/libc.so.6: version `GLIBC_2.15' not found (required by /mnt/lustre02/work/bd0854/b309141/mambaforge/envs/xxx/bin/../lib/libgdal.so.30)
```

but before that, trying to use my new shiny `fiona` is akin to a fight with a tiger in a jungle at night, e.g.:

```
$ esmvaltool run examples/recipe_python.yml
ERROR:esmvalcore._main:Program terminated abnormally, see stack trace below for more information:
Traceback (most recent call last):
  File "/work/bd0854/b309192/soft/miniconda3/envs/test/lib/python3.10/site-packages/esmvalcore/_main.py", line 479, in run
    fire.Fire(ESMValTool())
  File "/work/bd0854/b309192/soft/miniconda3/envs/test/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/work/bd0854/b309192/soft/miniconda3/envs/test/lib/python3.10/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/work/bd0854/b309192/soft/miniconda3/envs/test/lib/python3.10/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/work/bd0854/b309192/soft/miniconda3/envs/test/lib/python3.10/site-packages/esmvalcore/_main.py", line 376, in run
    from ._recipe import TASKSEP
  File "/work/bd0854/b309192/soft/miniconda3/envs/test/lib/python3.10/site-packages/esmvalcore/_recipe.py", line 15, in <module>
    from . import _recipe_checks as check
  File "/work/bd0854/b309192/soft/miniconda3/envs/test/lib/python3.10/site-packages/esmvalcore/_recipe_checks.py", line 13, in <module>
    from .preprocessor import TIME_PREPROCESSORS, PreprocessingTask
  File "/work/bd0854/b309192/soft/miniconda3/envs/test/lib/python3.10/site-packages/esmvalcore/preprocessor/__init__.py", line 14, in <module>
    from ._area import (
  File "/work/bd0854/b309192/soft/miniconda3/envs/test/lib/python3.10/site-packages/esmvalcore/preprocessor/_area.py", line 9, in <module>
    import fiona
  File "/work/bd0854/b309192/soft/miniconda3/envs/test/lib/python3.10/site-packages/fiona/__init__.py", line 85, in <module>
    with fiona._loading.add_gdal_dll_directories():
AttributeError: partially initialized module 'fiona' has no attribute '_loading' (most likely due to a circular import)
```

trace which barely touches upon the fact that there may be something awry with GDAL.

Cheers muchly! :beer:

**Comment by rouault** [comment]
apart from the Docker images at https://github.com/OSGeo/gdal/tree/master/docker, the GDAL project itself doesn't deliver any binaries. So this issue should likely be reported to the mamba project and/or https://github.com/conda-forge/gdal-feedstock

**Comment by valeriupredoi** [comment]
@rouault cheers muchly, mate! I was suspecting there'd be better for this issue to be, I'll move it over to the feedstock; it'd be good if you fellas put a pointer to the conda feedstock repo in your [README](https://github.com/OSGeo/gdal/blob/master/README.md) :beer:

**Comment by winstonma** [comment]
Hi all, I got the this problem too and I filed under https://github.com/conda-forge/conda-forge.github.io/issues/1748.

Would like to know if there are solution for this? Thanks
