### ISSUE TITLE
gdal_translate changes SRID to 4326 for rasters with SRID 900913.

### ISSUE THREAD

**Issue by zazhil-ha** [OSGeo/gdal#5382]
**Expected behavior:**
I am using GDAL Python API to clip a raster, the original raster SRID is 900913 and I expect the resulting SRID of gdal_translate is still 900913. Or I would expect an error, or None in case this specific SRID is not supported.

**Actual behavior:**
gdal_translate returns a dataset with SRID 4326 without sending any errors. 

## Steps to reproduce the problem.
```python
src = gdal.Open("<GDAL_WMTS><GetCapabilitiesUrl>https://maps.nyc.gov/wmts/1.0.0/?REQUEST=getcapabilities</GetCapabilitiesUrl><Layer>2018</Layer></GDAL_WMTS>")

proj = osr.SpatialReference(wkt=src.GetProjection())
crs = proj.GetAttrValue('AUTHORITY',1)
print('input srid: ' + crs)

src2 = gdal.Translate('/vsimem/mytest', src, options=" -outsize 512 512 -projwin -8232784.670082498 4983065.552504431 -8232584.670082498 4982865.552504431")

proj = osr.SpatialReference(wkt=src2.GetProjection())
crs = proj.GetAttrValue('AUTHORITY',1)
print('output srid: ' + crs)
```
## Operating system

Oracle Linux 7.9

## GDAL version and provenance

GDAL 3.3.1 continues in GDAL 3.4.1

**Comment by rouault** [comment]
crs = proj.GetAttrValue('AUTHORITY',1) doesn't necessary retrieve the top level ID of a CRS object. When outputing to GeoTIFF as 900913 is a quite special ID, a valid and equivalent CRS is producted but without a top level ID and thus the only ID is on the geographic CRS of the projected CRS, and that's what GetAttrValue('AUTHORITY', 1) will retrive.
A safer method to get the code of a CRS, and only on the CRS, is to use ``proj.GetAuthorityCode(None)`` which will return None here.
You'd better add "-a_srs EPSG:3857" to get a valid code on your output GeoTIFF.
