### ISSUE TITLE
Can't Filter by an empty Attribute in Shapefile

### ISSUE THREAD

**Issue by aharondavid** [OSGeo/gdal#5394]
## Expected behavior and actual behavior.
I have a Shapefile Layer with an empty Attribute. 
layer.SetAttributeFilter("MyAttribute=''");
then, Layer.GetNextFeature()  return an empty result.
Execute the same on Memeory Layer DataSource, return the expected result.

## Steps to reproduce the problem.
Create a Shapefile with an empty Attribute
and execute the above. 

## Operating system

Windows 10

## GDAL version and provenance

GDAL 3.1.2

**Comment by jratike80** [comment]
Could it be because shapefile format does not support null in attributes? See the ESRI FAQ https://support.esri.com/en/technical-article/000005811

**Comment by aharondavid** [comment]
Hello jratike80, thanks for your response.

I think that the Shapefile Driver should implement it in its SetAttributeFilter method - replace '' by ' ' in case of string type.
Think about a case of the same Where statement that are given into SetAttributeFilter above different kinds of DataSource including Shapefile.

**Comment by jratike80** [comment]
[nulltest.zip](https://github.com/OSGeo/gdal/files/8149030/nulltest.zip)

> It seems that something like what you suggest is happening already. There are two points in the shapefile, one with empty/null attributes, string + integer.
> 
> ogrinfo -sql "select * from \"null\" where attr_1 is null" null.shp
> INFO: Open of `null.shp'
>       using driver `ESRI Shapefile' successful.
> 
> Layer name: null
> Geometry: Point
> Feature Count: 1
> Extent: (6.347723, 17.829307) - (8.194851, 17.913267)
> Layer SRS WKT:
> (unknown)
> Geometry Column = _ogr_geometry_
> attr_1: String (3.0)
> attr_2: Integer (3.0)
> OGRFeature(null):0
>   attr_1 (String) = (null)
>   attr_2 (Integer) = 0
>   POINT (6.34772277227723 17.8293069306931)
> 

How did you make your shapefile? Does my ogrinfo request find empty strings from it?

**Comment by aharondavid** [comment]
I expected from Shapefile to return the same result when the query string is empty either null,
but I can gess why it works like that.

Thanks!
