### ISSUE TITLE
gdalwarp offset on reprojection from epsg:28992 to epsg:25831

### ISSUE THREAD

**Issue by freekvw** [OSGeo/gdal#5399]
## Expected behavior and actual behavior.
Reprojecting some tiles of the Dutch AHN3 elevation model results in offsets in the output of >100 meters.

## Steps to reproduce the problem.

* Download & unpack e.g. tile https://download.pdok.nl/rws/ahn3/v1_0/5m_dsm/R5_46BN2.ZIP
* `gdalwarp -t_srs EPSG:25831 R5_46BN2.TIF R5_46BN2-25831.TIF`

Now open both files in e.g. QGIS and observe the offset of approximately 30 m east and 110 m north.

## Operating system

Reproducible on various Linux variants, including Ubuntu 20.04.

## GDAL version and provenance

Various, including a fresh build of master using proj 8.2.0.

## Further details
Specifying `-ct` to gdalwarp makes the issue go away. E.g.:
```
$ gdalwarp -t_srs EPSG:25831 -ct '+proj=pipeline +step +inv +proj=sterea +lat_0=52.1561605555556 +lon_0=5.38763888888889         +k=0.9999079 +x_0=155000 +y_0=463000 +ellps=bessel   +step +proj=push +v_3 +step +proj=cart +ellps=bessel   +step +proj=helmert +x=565.7381 +y=50.4018 +z=465.2904 +rx=0.395025981036064 +ry=-0.330772431242031 +rz=1.87607329462821 +s=4.07244  +convention=coordinate_frame +step +inv +proj=cart +ellps=GRS80 +step +proj=pop +v_3 +step +proj=utm +zone=31 +ellps=GRS80' R5_46BN2.TIF R5_46BN2-25831-2.TIF
$ gdalinfo R5_46BN2-25831.TIF | grep Origin
Origin = (704565.326535094529390,5744584.640074593946338)
$ gdalinfo R5_46BN2-25831-2.TIF | grep Origin
Origin = (704533.696954668965191,5744477.634767718613148)
```

**Comment by jratike80** [comment]
The QGIS test means just that when is does on-the-fly re-projection it does it in another way than what  gdalwarp was using. Gdalwarp probably uses the best method that Proj finds and is using gridshift file

```
projinfo -s epsg:28992 -t epsg:25831
Candidate operations found: 2
-------------------------------------
Operation No. 1:

unknown id, Inverse of RD New + Amersfoort to ETRS89 (9) + UTM zone 31N, 0.001 m, Netherlands - onshore, including Waddenzee, Dutch Wadden Islands and 12-mile offshore coastal zone.

PROJ string:
+proj=pipeline
  +step +inv +proj=sterea +lat_0=52.1561605555556 +lon_0=5.38763888888889
        +k=0.9999079 +x_0=155000 +y_0=463000 +ellps=bessel
  +step +proj=hgridshift +grids=nl_nsgi_rdtrans2018.tif
  +step +proj=utm +zone=31 +ellps=GRS80
```

The second best option is this:

```
Operation No. 2:

unknown id, Inverse of RD New + Amersfoort to ETRS89 (8) + UTM zone 31N, 0.25 m, Netherlands - onshore, including Waddenzee, Dutch Wadden Islands and 12-mile offshore coastal zone.

PROJ string:
+proj=pipeline
  +step +inv +proj=sterea +lat_0=52.1561605555556 +lon_0=5.38763888888889
        +k=0.9999079 +x_0=155000 +y_0=463000 +ellps=bessel
  +step +proj=push +v_3
  +step +proj=cart +ellps=bessel
  +step +proj=helmert +x=565.7381 +y=50.4018 +z=465.2904 +rx=0.395025981036064
        +ry=-0.330772431242031 +rz=1.87607329462821 +s=4.07244
        +convention=coordinate_frame
  +step +inv +proj=cart +ellps=GRS80
  +step +proj=pop +v_3
  +step +proj=utm +zone=31 +ellps=GRS80

```

When I added the files for the first time into QGIS I was asked to select from two transformations. I did not record the alternatives and now I do not get them back but QGIS opens the files without any questions.

But my conclusion is that by using `-ct` you force GDAL to use the less accurate conversion but maybe you should rather find a way to make QGIS to use the more accurate one.

**Comment by jratike80** [comment]
I believe I got it by I do not understand what it means. Have a try and define also the source CRS instead of letting GDAL to find it out

`gdalwarp -s_srs epsg:28992 -t_srs EPSG:25831 R5_46BN2.TIF R5_46BN2-25831-5.TIF`

There is a 120 m shift with/without `s_srs`. Can you confirm?

**Comment by freekvw** [comment]
Thanks, you're right, I hadn't noticed this tile has a different spatial reference from other AHN3 tiles.  I will notify the publisher.

**Comment by jratike80** [comment]
Let's keep this open, the difference in the coordinate system WKT does not look so big to me. Maybe it could still be interpreted to mean the same as EPSG:28992.

**Comment by freekvw** [comment]
Ok.  I do also believe there is some issue in GDAL, I just haven't dug into it sufficiently.  E.g. I observed a difference when calling or not calling `OGRSpatialReference::IsSame()` on the file's georeference and EPSG:28992 before doing warping, while I would have expected that function not to have side effects.

**Comment by rouault** [comment]
The issue here comes from the values of the 2 following geokeys:
```
      GeogSemiMinorAxisGeoKey (Double,1): 6356078.96284    
      GeogInvFlatteningGeoKey (Double,1): 299.152813106079 
```
whose value is not exactly the one contained in EPSG. Consequently PROJ consider that the datum is not Amersfoort, and is enable to perform datum shift.
In https://github.com/OSGeo/gdal/pull/5428, I've added a warning when this is detected and a GTIFF_SRS_SOURCE=EPSG/GEOKEYS configuration option to alter the SRS.

The best resolution would be for the data producer to either correct the wrong geokeys, or just remove them and essentially keep the GTModelTypeGeoKey, GTRasterTypeGeoKey and ProjectedCSTypeGeoKey geokeys which are sufficient to fully describe the CRS without any risk of self-contradiction.

**Comment by freekvw** [comment]
Thanks rouault, that's a helpful workaround.  I have contacted the data provider to make them aware of the issue.
