### ISSUE TITLE
Cmake issues jpeg (cross compile/ubuntu -> android)  IMPORTED_LOCATION not set for imported target .... "Release".

### ISSUE THREAD

**Issue by vautieri2** [OSGeo/gdal#5405]
You get this error building for all drivers as this is a sample.  Note this happens after the message "-- Configuring done:"  I also tried adding "Release"  (-DCMAKE_BUILD_TYPE=Release) thinking this might be a work around, but it did not work.  I'm not sure yet how to fix or get around this issue.  With that said, the system does start compiling after all these errors, which gets us into a couple more issues.  Again, this is on your main branch as I don't believe this is any version of software yet.

  IMPORTED_LOCATION not set for imported target "TIFF::TIFF" configuration
  "Release".

CMake Error in CMakeLists.txt:
  IMPORTED_LOCATION not set for imported target "TIFF::TIFF" configuration
  "Release".

CMake Error in CMakeLists.txt:
  IMPORTED_LOCATION not set for imported target "XercesC::XercesC"
  configuration "Release".

CMake Error in CMakeLists.txt:
  IMPORTED_LOCATION not set for imported target "PNG::PNG" configuration
  "Release".

**Comment by rouault** [comment]
How can one reproduce this ? (see my comment in https://github.com/OSGeo/gdal/issues/5406#issuecomment-1061674825 on the best way to provide a reproducer)

**Comment by vautieri2** [comment]
Just some early feedback as I will look at your comment on the best way to reproduce and do better, but below is what I am doing incase you see something glaring.  I went down to just proj and this gets spit out dozens of times.

CMake Error in CMakeLists.txt:
  IMPORTED_LOCATION not set for imported target "PROJ::proj" configuration
  "Release".
..................................................................

cmake	-B$PWD/arm64-v8a -DANDROID_NDK=$ANDROID_NDK -DANDROID_ABI=arm64-v8a -DCMAKE_INSTALL_PREFIX=$INSTALL_PREFIX_DIR -DBUILD_SHARED_LIBS=OFF -DCMAKE_TOOLCHAIN_FILE=$CMAKEBUILD/android.toolchain.cmake -DCMAKE_BUILD_TYPE=Release\
			-DCMAKE_TOOLCHAIN_FILE=$CMAKEBUILD/android.toolchain.cmake -DANDROID_NATIVE_API_LEVEL=$NDK_VERSION -DANDROID_PLATFORM=$MIN_SDK_VERSION\
			-DPROJ_DIR=$PROJ_DIR/lib/cmake/proj/ -DPROJ_INCLUDE_DIR=$PROJ_DIR/include -DPROJ_LIBRARY_RELEASE=$PROJ_DIR/lib/proj
			
	cmake --build "" --target install


where 
MIN_SDK_VERSION=28
NDK_VERSION='r22b'
PROJ_DIR=$BaseDirectory/proj/arm64-v8a
	ANDROID_NDK=$PWD/build/linux-x86_64/android-ndk-$NDK_VERSION
	export ANDROID_NDK_HOME=$ANDROID_NDK
	export TOOLCHAIN=$ANDROID_NDK/toolchains/llvm/prebuilt/$HOST_TAG
	export CMAKEBUILD=$ANDROID_NDK/build/cmake
	export LD=$TOOLCHAIN/bin/ld
	export RANLIB=$TOOLCHAIN/bin/llvm-ranlib
	export STRIP=$TOOLCHAIN/bin/llvm-strip

**Comment by dg0yt** [comment]
The problem is not so much in PROJ but in the provided CMake config for TIFF etc. 
In another case on gdal the mailing list, TIFF was broken by configuring for a wrong build type just by forgetting a single space between `-DCMAKE_BUILD_TYPE=Release` and the next `-D...` - some config files were written with wrong names.

If you really want to mix build types for a `Release` build of PROJ, you can configure PROJ with `-DCMAKE_MAP_IMPORTED_CONFIG_Release=Release;...`.

**Comment by vautieri2** [comment]
I rebuilt all my projects as well as used the -B option with cmake for all of them.  I also dumped all my installs into a flat layout (such as having all third party libs installed to the same lib directory)..aka not proj\lib   int all just in lib.  Things seem to be working much better now and this specific issue can be closed.  Thank you!
