### ISSUE TITLE
Wrong Height value after transformation

### ISSUE THREAD

**Issue by sgamperl** [OSGeo/gdal#5408]
Hello,

we use the GDAL library to transform and show raster files and we use the OSR-classes (ogr_spatialref) to transform coordinates between coordinate systems. In the past we used our own proj-strings to transform the coordinates.
Now we upgraded from GDAL 2.4.4 to GDAL 3.3.3. We know that we now have a new version of Proj library (Proj 7.2.1) which transforms the data.
We've seen that the new version assumes that the z-component is an ellipsoidal height if we don't explicit specify a vertical coordinate system. There is no transformation of the z-component if the coordinate reference systems don't have a vertical crs specified.
So far so good. 

We checked our transformation with the projinfo - tool. 

projinfo -s "+proj=tmerc +lat_0=0 +lon_0=34 +k=1 +x_0=0 +y_0=-5000000 +ellps=bessel +pm=ferro  +towgs84=577.326,90.129,463.919,5.137,1.474,5.297,2.4232 +units=m +no_defs +type=crs" -t "+proj=longlat +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +no_defs +type=crs" -o PROJ

So we want to transform from EPSG:31253 to EPSG:4258 with these strings.
Then we see the resulting pipeline:

```
+proj=pipeline
  +step +inv +proj=tmerc +lat_0=0 +lon_0=34 +k=1 +x_0=0 +y_0=-5000000
        +ellps=bessel +pm=ferro
  **+step +proj=push +v_3**
  +step +proj=cart +ellps=bessel
  +step +proj=helmert +x=577.326 +y=90.129 +z=463.919 +rx=5.137 +ry=1.474
        +rz=5.297 +s=2.4232 +convention=position_vector
  +step +inv +proj=cart +ellps=GRS80
  +**step +proj=pop +v_3**
  +step +proj=unitconvert +xy_in=rad +xy_out=deg
```

The push and pop of v_3 is responsible that the elevation is not handled in our case. Therfore we call the projinfo command with the --3d switch, which promotes a 3D crs before transforming. 

```
projinfo -s "+proj=tmerc +lat_0=0 +lon_0=34 +k=1 +x_0=0 +y_0=-5000000 +ellps=bessel +pm=ferro  +towgs84=577.326,90.129,463.919,5.137,1.474,5.297,2.4232 +units=m +no_defs +type=crs" -t "+proj=longlat +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +no_defs +type=crs" -o PROJ --3d
Candidate operations found: 1
-------------------------------------
Operation No. 1:

unknown id, Inverse of unknown + Transformation from unknown to WGS84 + Inverse of Transformation from unknown to WGS84, unknown accuracy, World

PROJ string:
+proj=pipeline
  +step +inv +proj=tmerc +lat_0=0 +lon_0=34 +k=1 +x_0=0 +y_0=-5000000
        +ellps=bessel +pm=ferro
  +step +proj=cart +ellps=bessel
  +step +proj=helmert +x=577.326 +y=90.129 +z=463.919 +rx=5.137 +ry=1.474
        +rz=5.297 +s=2.4232 +convention=position_vector
  +step +inv +proj=cart +ellps=GRS80
  +step +proj=unitconvert +xy_in=rad +z_in=m +xy_out=deg +z_out=m
```

With this pipeline we get the correct elevations after transformation.  The option --3d calls the internal function proj_crs_promote_to_3D. 

Now we also want to use this solution with GDAL and OSR. Therefore we instantiate a crs and call the PromoteTo3D() function on the OGRSpatialReference. Then we call the transform method.

**Failed test case:**

Coordinates -15348.78, 247012.17, 398.00 in EPSG:31253
Transformaed Coordinates 16.1290148681238, 47.3618994565543,398.00 
The height is wrong.

**Expected result:**
Coordinates -15348.78, 247012.17, 398.00 in EPSG:31253
Expected Coordinates 16.1290148681238, 47.3618994565543, 443.420991772786 in EPSG:4258

The PromoteTo3D() is not handled correctly. The libary uses the wrong transformation pipeline:
```
+proj=pipeline
  +step +inv +proj=tmerc +lat_0=0 +lon_0=34 +k=1 +x_0=0 +y_0=-5000000
        +ellps=bessel +pm=ferro
  **+step +proj=push +v_3**
  +step +proj=cart +ellps=bessel
  +step +proj=helmert +x=577.326 +y=90.129 +z=463.919 +rx=5.137 +ry=1.474
        +rz=5.297 +s=2.4232 +convention=position_vector
  +step +inv +proj=cart +ellps=GRS80
  +**step +proj=pop +v_3**
  +step +proj=unitconvert +xy_in=rad +xy_out=deg
```

GDAL Version 3.3.3 used with PROJ 7.2.1

**Comment by rouault** [comment]
PROJ issue. Fix in https://github.com/OSGeo/PROJ/pull/3098
