### ISSUE TITLE
Setting RPATH on CMake Installations (MacOS)

### ISSUE THREAD

**Issue by youngpm** [OSGeo/gdal#5413]
## Expected behavior and actual behavior.

I built head on MacOS via the new CMake tooling and installed it to a nonstandard location (building with ninja is fast!).  The various installed GDAL executables failed to find the GDAL shared library.  I've previously built older versions with the autotools based build system and those builds do find their shared library dependencies.

## Steps to reproduce the problem.

Using HEAD, at least on macos,

```
cmake -GNinja -DCMAKE_INSTALL_PREFIX=/mygdalbuilds/gdal-github -DCMAKE_BUILD_TYPE=Release ..
cmake --build .
cmake --build . --target install
```
The executables under /mygdalbuilds/gdal-github/bin` will report they're missing the gdal dylib.

To get the binaries using a RPATH, I cracked open [Professional CMake](https://crascit.com/professional-cmake/), and in Section 26.2.3 snagged this snippet and changed up `gdal.cmake` as follows:

```
# Install properties
if (GDAL_ENABLE_MACOSX_FRAMEWORK)
  ...
else ()
  include(GNUInstallDirs)
  set(INSTALL_PLUGIN_DIR
      "lib/gdalplugins/${GDAL_VERSION_MAJOR}.${GDAL_VERSION_MINOR}"
      CACHE PATH "Installation sub-directory for plugins")
  set(GDAL_RESOURCE_PATH ${CMAKE_INSTALL_DATADIR}/gdal)

  if(APPLE)
    set(base @loader_path)
  else()
    set(base $ORIGIN)
  endif()

  file(RELATIVE_PATH relDir
    ${CMAKE_CURRENT_BINARY_DIR}/${CMAKE_INSTALL_BINDIR}
    ${CMAKE_CURRENT_BINARY_DIR}/${CMAKE_INSTALL_LIBDIR}
  )
  set(CMAKE_INSTALL_RPATH ${base} ${base}/${relDir})
endif ()
```

The installed executables now find their runtime dependencies as expected.  I have not yet tried this on linux but I think the same issue might happen there as I didn't see much in `gdal.cmake` related to RPATHs and I think CMake's default is to not set it on installed executables.

I am happy to submit a PR if desired, I wasn't sure if this setting the RPATH on install is something GDAL wants to do.

## Operating system

MacOS (possibly linux too?)

## GDAL version and provenance

Latest from GitHub.

**Comment by forestgnome** [comment]
I would not predefine the *.cmake-files for certain target environments. 
For full app-stacks(like QGIS), RPATH is required, for command-line tools (gdalinfo,etc.), RPATH is a nightmare.
Overriding the standard cmake-command is sufficiently powerful to define the RPATH-behaviour and external dependecies (/usr/local, /opt/, what ever you like).
	cmake \
		-D CMAKE_INSTALL_PREFIX=my/install/dir" \
		-D CMAKE_MACOSX_RPATH="$enableRPATH" \
		-D GEOS_INCLUDE_DIR="$geosInstalledDir"/include \
		-D GEOS_LIBRARY="$geosInstalledDir"/lib/libgeos_c.dylib \
		-D PROJ_INCLUDE_DIR="$projInstalledDir"/include \
		-D PROJ_LIBRARY="$projInstalledDir"/lib/libproj.dylib \
		..

**Comment by rouault** [comment]
> I am happy to submit a PR if desired, I wasn't sure if this setting the RPATH on install is something GDAL wants to do.

I'm not sure either. As mentioned by @frestgnome, it might depend on use cases, and if cmake doesn't do it by default, there might be good reasons. I'm not sure why autoconf builds on Mac set the rpath. That's perhaps something done under the hood by libtool on Mac.
Perhaps you could submit a pull request with what you propose, but controlled by a GDAL_SET_RPATH boolean option, probably OFF by default ? (and have it documented in doc/source/build_hints.rst)

**Comment by rouault** [comment]
implemented in https://github.com/OSGeo/gdal/pull/5485
