### ISSUE TITLE
Is GDAL support on Oracle cloud?

### ISSUE THREAD

**Issue by chaitanyajalluri** [OSGeo/gdal#5416]
Does GDAL has support to access and render raster files stored on Oracle cloud Storage (virtual file system)? If it is please share the documentation to access.

**Comment by jratike80** [comment]
I suppose you did read this advise when you created this new issue:

 "IMPORTANT: Do NOT use GitHub to post any questions or support requests!
           They will be closed immediately and ignored.

Questions should go to the gdal-dev mailing list at
https://lists.osgeo.org/mailman/listinfo/gdal-dev
or other support forums. GitHub issues are for bug
reports and suggestions for new features."
