### ISSUE TITLE
ogr2ogr does not correctly parse the coordinate in shapefile

### ISSUE THREAD

**Issue by jerry73204** [OSGeo/gdal#542]
## Description

The problem arises when I tried to convert a shapefile to geojson. I got started with the following.
```
dir
├── in.dbf
├── in.prj
├── in.sbn
├── in.sbx
├── in.shp
├── in.shp.xml
└── in.shx
```

Here is my conversion command with ogr2ogr.
```sh
env SHAPE_ENCODING=BIG5-HKSCS \
    ogr2ogr \
    -t_srs EPSG:4326 -s_srs EPSG:3826 \
    -f GeoJSON \
    out.json \
    dir/in.shp
```

I expect it to do its job and exit normally. However, it complains with lots of warnings like this.
```
Warning 1: Value '΢^D' of field in.ID parsed incompletely to integer 0.
Warning 1: Value '993110   34 3   0' of field in.Y坐標 parsed incompletely to real 993110.
Warning 1: Value '768093110   34 2' of field in.Y坐標 parsed incompletely to real 768093110.
Warning 1: Value '8923393110   34 1' of field in.Y坐標 parsed incompletely to real 8923393110.
Warning 1: Value '8957793110   3' of field in.Y坐標 parsed incompletely to real 8957793110.
Warning 1: Value '4 3   0' of field in.ID parsed incompletely to integer 4.
Warning 1: Value '34 4' of field in.ID parsed incompletely to integer 34.
Warning 1: Value '4 3   0' of field in.X坐標 parsed incompletely to real 4.
Warning 1: Value '10   34' of field in.ID parsed incompletely to integer 10.
Warning 1: Value '34 4   0' of field in.X坐標 parsed incompletely to real 34.
Warning 1: Value '10   13 1   0' of field in.X坐標 parsed incompletely to real 10.
Warning 1: Value '93110   6412 105' of field in.X坐標 parsed incompletely to real 93110.
Warning 1: Value '10393110   34 5 105' of field in.X坐標 parsed incompletely to real 10393110.
Warning 1: Value '7211593110   34 4' of field in.X坐標 parsed incompletely to real 7211593110.
Warning 1: Value '7212893110   13' of field in.X坐標 parsed incompletely to real 7212893110.
Warning 1: Value '1 105' of field in.Y坐標 parsed incompletely to real 1.
Warning 1: Value '13 1 105' of field in.Y坐標 parsed incompletely to real 13.
Warning 1: Value '0   13 1 105' of field in.Y坐標 parsed incompletely to real 0.
Warning 1: Value '3110   13 1 105' of field in.Y坐標 parsed incompletely to real 3110.
Warning 1: Value '8293110   13 1 105' of field in.Y坐標 parsed incompletely to real 8293110.
Warning 1: Value '7219493110   13 1 1' of field in.Y坐標 parsed incompletely to real 7219493110.
Warning 1: Value '7220693110   13' of field in.Y坐標 parsed incompletely to real 7220693110.
...
```

As mentioned in stderr, for example, the line `Warning 1: Value '993110   34 3   0' of field in.Y坐標 parsed incompletely to real 993110.` in English states a y-coordinate is parsed incorrectly to 993110. The value latitude 993110 appears in the produced geojson file, which is far from its original point. (I expect it to be around 2655xxx.)

I inspect the shapefile with hexdump, and write the python script the verify if this file is correctly formulated.
```python
import fiona
import sys
import struct

def main():
    assert len(sys.argv) == 2
    filename = sys.argv[1]

    with open(filename, 'rb') as fp:
        header = fp.read(100)

        while True:
            record_header = fp.read(8)
            if len(record_header) == 0:
                exit()

            number, length = struct.unpack('>II', record_header)
            payload = fp.read((length) * 2)

            feat_type = struct.unpack('<I', payload[:4])[0]

            if feat_type == 1:
                x, y = struct.unpack('dd', payload[4:])
                print(number, length, feat_type, x, y)

if __name__ == '__main__':
    main()
```

It turns out that every feature is of point type in this file (type == 1). No corrupted coordinate is discovered (like 993110) and is in expected range (2655xxx). Thus, I consider it an ogr2ogr bug.

For GDAL developers, there are reasons I cannot publish the shapefile here. If you need this interesting shapefile, please contact my email jerry73204@gmail.com and I can give a help. 

## Operating system

Arch Linux

## GDAL version and provenance

gdal 2.2.4 from Arch Linux official repository

**Comment by jratike80** [comment]
For me it seems that the errors are not referring to the geometries but to normal attributes which are saved into the .dbf file (attribute names Y坐標  and X坐標). That your geometries are in a wrong place is probably a different problem. I suppose that you do not await that ogr2ogr is changing the X- and Y-coordinate values which are stored as attributes into .dbf file because that will not happen.

Try if you get rid of the warnings by converting just the geometries but no attributes at all with 
`ogr2ogr -t_srs EPSG:4326 -s_srs EPSG:3826 -f GeoJSON -dialect SQLite -sql "select geometry from in" out.json dir/in.shp`

**Comment by jerry73204** [comment]
Thanks. It seems it's not the case. The issue could be closed.
Is it possible to accept or reject certain properties from shp/dbf?

**Comment by rouault** [comment]
From the shapefile you sent me, it seems there's a corruption in the DBF file towards its ends. The conversion up to 80% works fine. I don't think this is an issue in GDAL. The corruption actually starts at feature fid=171590. And indeed looking in the dbf file with an hexadecimal starting at offset 103469056, it shows weird content
