### ISSUE TITLE
gdalwarp with both --crop_to_cutline and -tr create a miss-aligned output

### ISSUE THREAD

**Issue by nicogodet** [OSGeo/gdal#5430]
## Expected behavior and actual behavior.

Data : https://cloud.nicodet.fr/s/GdDqQni9pxckErq

With `--crop_to_cutline` only (Default config of qgis alg `gdal:cliprasterbymasklayer`)
`gdalwarp -overwrite -of GTiff -cutline D:/Pays_Benin_EPSG32631.shp -cl Pays_Benin_EPSG32631 -crop_to_cutline D:/MNT_SRTM_EPSG32631.tif C:/Users/godet/AppData/Local/Temp/processing_GoOkMA/73b4d45f22d34af587c66f5ecc38cce4/OUTPUT.tif`
![image](https://user-images.githubusercontent.com/39594821/157397381-d90e4e4f-81a8-4830-9fbc-4bed13f2af4f.png)
![image](https://user-images.githubusercontent.com/39594821/157397989-d9d49cfc-f3a1-4936-a4d4-b7194b7a7ff8.png)

With `-tr` or "Keep resolution of input raster"
`gdalwarp -overwrite -of GTiff -tr 30.66359603295757 -30.663596032957575 -tap -cutline D:/Pays_Benin_EPSG32631.shp -cl Pays_Benin_EPSG32631 -crop_to_cutline D:/MNT_SRTM_EPSG32631.tif C:/Users/godet/AppData/Local/Temp/processing_GoOkMA/ffe75f2c3dfa4486b21357706e9437e6/OUTPUT.tif`
![image](https://user-images.githubusercontent.com/39594821/157397918-23fc3361-eb64-47d5-815a-927057de0042.png)
![image](https://user-images.githubusercontent.com/39594821/157397966-80f099a2-b2bc-4fdf-8d7b-15bbdf32bb72.png)

## Steps to reproduce the problem.

Both command lines are written above (need to be adapted based on where your files are).

## Operating system

Windows 10

## GDAL version and provenance

GDAL 3.4.1 QGIS 3.24.0 OSGeo4W

**Comment by jratike80** [comment]
Have you tried "target aligned pixels" `-tap`?

**Comment by jratike80** [comment]
I can reproduce the shift with GDAL 3.4.0. Pixels are aligned differently with all three options:
- with `-tr`
- with `-tr -tap`
- without both

Is the fix that you would like to see about this:

gdalwarp should produce the same result with or without `-tr` when the source resolution=target resolution and source-srs= target-srs.

**Comment by rouault** [comment]
""""
-tap
    (target aligned pixels) align the coordinates of the extent of the output file to the values of the [-tr](https://gdal.org/programs/gdalwarp.html#cmdoption-gdalwarp-tr), such that the aligned extent includes the minimum extent.
"""
Perhaps clearer: the coordinates of the top-left corner of the output raster are such the result of their division by the -tr values is an integer.

**Comment by nicogodet** [comment]
@rouault Indeed clearer !
So in case we want pixel aligned AND same resolution, I just need to crop ?

**Comment by rouault** [comment]
> I just need to crop ?

Yes, looking at the code that deal with --crop_to_cutline, there's this comment when -tr is not specified:
        // No raster reprojection: stick on exact pixel boundaries of the source
        // to preserve resolution and avoid resampling

**Comment by jratike80** [comment]
So it works also with non-square pixels?

**Comment by jratike80** [comment]
I was thinking about the same. Plain crop option that just picks the pixels based on the crop geometry could rather be placed into gdal_translate or as a special sampling tool. Gdalwarp is after all planned for warping. Specialized tool could also have options "all touched", "centre inside", "completely inside", "with buffer", support several geometries (a bunch of research sites at once) and point/line geometries.

**Comment by nicogodet** [comment]
> Yes, looking at the code that deal with --crop_to_cutline, there's this comment when -tr is not specified: // No raster reprojection: stick on exact pixel boundaries of the source // to preserve resolution and avoid resampling

Based on this, I suggest to rephrase the option in QGIS which lead to this issue in first place. Should I open an issue ?

**Comment by rouault** [comment]
> Should I open an issue ?

this is your call :-)
