### ISSUE TITLE
3.4.2 compile fails when using clang++ options "-Werror,-Wfloat-equal"

### ISSUE THREAD

**Issue by andrew-aitchison** [OSGeo/gdal#5432]
3.4.2 compile fails when using clang++ options "-Werror,-Wfloat-equal"
#5379 fixed this in master
https://github.com/OSGeo/gdal/commit/9e2aa033dca20986565ee79a8e709794cd9bc90c

## GDAL version and provenance
Fixed in master, needed for 3.4.2 release

**Comment by rouault** [comment]
commit https://github.com/OSGeo/gdal/commit/9e2aa033dca20986565ee79a8e709794cd9bc90c cherry-picked in release/3.4 as  3b0c26d57528326c074a9c82890e737e2d516a7d
