### ISSUE TITLE
Colormap of Geotiff file

### ISSUE THREAD

**Issue by vijay2712** [OSGeo/gdal#5439]
Hi,

I have downloaded a satellite NDVI band using API but it is greyscaled.I have used gdal to remove the zero pixel value and saved it to my local directory.

How to change the raster image from greyscale to an RGB color map and save it to local directory? 

Thanks in advance

**Comment by jratike80** [comment]
Did you read the notice on the bug report template

> IMPORTANT: Do NOT use GitHub to post any questions or support requests!
>            They will be closed immediately and ignored.
> 
> Questions should go to the gdal-dev mailing list at
> https://lists.osgeo.org/mailman/listinfo/gdal-dev
> or other support forums. GitHub issues are for bug
> reports and suggestions for new features

.
