### ISSUE TITLE
GDAL.Native does not work properly when it is installed on a referenced project (csharp)

### ISSUE THREAD

**Issue by xavierpena** [OSGeo/gdal#5454]
## Expected behavior and actual behavior.

GDAL.Native adds `gdal_wrap.dll` in the "wrong" folder when the nuget package is installed in a sub-project (that is: a project that is not the top project that is being executed, but a referenced project instead)

## Steps to reproduce the problem.

 * I had 2 projects in my solution: `ProjectA` and `ProjectB`

 * I was executing `ProjectA`, and `ProjectA` was referencing `ProjectB`

 * `ProjectB` is the one that contained the references to both `GDAL` and `GDAL.Native`

 * `ProjectA` tried to find GDAL.Native's files under `ProjectA\bin\Debug\netcoreapp3.1\gdal` ... but in reality those files are under `ProjectB\bin\Debug\netcoreapp3.1\gdal`

## Operating system

Windows 10 Home

## GDAL version and provenance

Nuget packages:

```
<PackageReference Include="GDAL" Version="3.4.1" />
<PackageReference Include="GDAL.Native" Version="3.4.1" />
```

---

Workarounds:

 * Dirty solution: just copy the files from `ProjectB` under `ProjectA\bin\Debug\netcoreapp3.1`
 
 * Okayish solution: add the `GDAL.Native` package to each one of your "entry projects"

---

I don't like either of those solutions. I know that all this stuff happens under `GdalConfiguration.cs`, so maybe there is a way to modify it to find the correct path. 

I have tried it myself, but I don't like the idea of scanning all the other projects until I find those files. Also I don't think this strategy is going to hold if I do a release (I have not tested it yet).

The "clean" solution would be for `GDAL.Native` to create the files under the top-level project (instead of "hiding" them under the referenced project folder... which is not part of the "executing assembly").

**Comment by rouault** [comment]
CC @runette As I'm illiterate in the C# ecosystem, not sure if the above is an issue in the C# bindings themselves, a nuget issue or just something that "works as expected" (or not expected depending on point of view) ?

**Comment by szekerest** [comment]
@xavierpena Replicated this item to:  https://github.com/gisinternals/buildsystem/issues/191

**Comment by szekerest** [comment]
@xavierpena Please see my comments in the referred ticket about the suggested approach of referring the GDAL and GDAL.Native packages.
