### ISSUE TITLE
Autotools configure script doesn't honour --disable-rpath directive

### ISSUE THREAD

**Issue by RichardLangFromNZ** [OSGeo/gdal#546]
Despite being advertised as supported by configure --help, I'm still getting an RPATH entry in produced in the GDAL binaries when specifying --disable-rpath to the configure script.

I'm by no means skilled in bash scripting, but a simple text search of the script doesn't reveal any obvious sign of the directive being parsed or used.

**Comment by rddesmond** [comment]
Love GDAL, but I found this too.  Poking around in m4/lib-link.m4:
```sh
  AC_ARG_ENABLE(rpath,
    [  --disable-rpath         do not hardcode runtime library paths],
    :, enable_rpath=yes)
```
and `enable_rpath` is used like
```sh
if test "$enable_rpath" != no; then
...
```

Since `enable_rpath` is either "yes" or blank, it's always not no and the rpath is always created.  I think this should be
```sh
AC_MSG_CHECKING(whether to use rpath)
AC_ARG_ENABLE(rpath,
	[AC_HELP_STRING([--disable-rpath],
			[do not hardcode runtime library paths.])],
	[enable_rpath="$enableval"], [enable_rpath="yes"])
AC_MSG_RESULT($enable_rpath)
```

**Comment by rouault** [comment]
Improvements to autotools build systems will no longer be considered now that we are developing a cmake build system that will eventually replace it
