### ISSUE TITLE
S57 official updates from NOAA not correctly applied

### ISSUE THREAD

**Issue by maitaivw** [OSGeo/gdal#5461]
## Expected behavior and actual behavior.

Using this official chart from NOAA: [US2MI80M](https://www.charts.noaa.gov/ENCs/US2MI80M.zip). It contains up to 28 updates and starting from update 10 gdal prints a lot of errors on the console, and the chart becomes unusable. I have identified several issues starting from update 10 (one insert is on RCID=4566 that already exists),  but even if I skip it gdal starts to complain about not being able to find geometry or to close polygons, etc. Some objects (LIGHTS, LNDMRK) even change geometry type from wkbPoint to wkbPoint25D which is actually impossible, and makes me think the whole chart is completely corrupted. As far as I can tell, the updates are correctly swallowed by SeeMyEnc. I have also read this old post: https://trac.osgeo.org/gdal/ticket/5162 which seems very similar but likewise I cannot believe NOAA is producing so deeply bugged updates.

Thanks and sorry if this is not the correct place to report.
Philippe Lelong

## Steps to reproduce the problem.

Just load the chart with debug info on.

## Operating system

Windows, Ubuntu, Raspberry, etc.

## GDAL version and provenance

3.4.1 from github, built against Proj 6.

**Comment by maitaivw** [comment]
I have investigated a bit more:
The problem seems to occur when an update (RUIN=3) concerns coordinates, with a CCUI=2 (delete coordinate). For instance in the case of US2MI080M update 010 has a record for RCID 1852, which contains a delete coordinate:
  DDFField:
      Tag = `SGCC'
      DataSize = 6
      Data = `\02\01\00\01\00\1E'
      Subfield `CCUI' = 2
      Subfield `CCIX' = 1
      Subfield `CCNC' = 1
After applying just that update, another item (RCID 3893) complains that it cannot close polygon and therefore has no geometry.
I will continue searching but maybe the method used to wipe out one coordinate does not resize correctly the data?
poTarget->SetFieldRaw( poDstSG2D, i + nCCIX - 1, nullptr, 0 );

--Philippe

**Comment by maitaivw** [comment]
Hello again,

Finally the issue was resolved.

The user updated its chart folder by unzipping the new files from NOAA into an existing directory containing an old revision of the chart (Edition 9, while the new one is Edition 16). Edition 9 had 28 update files, and edition 16 has only 9. So GDAL was applying updates 10 to 28 from Edition 9 to the new Edition 16, obviously resulting in a mess.

I think this case should be taken into account in GDAL (i.e. rejecting updates when in DSID record EDTN does not match the Edition Number of the dataset), especially since it is legal to send an update with EDTN=0 to cancel the whole chart.

Furthermore, there is a bug in s57Reader.cpp line 2689:

    unsigned char *pnRVER
        = (unsigned char *) poKey->GetSubfieldData( poRVER_SFD, nullptr, 0 );
should be changed to
    unsigned int *pnRVER
        = (unsigned int *) poKey->GetSubfieldData( poRVER_SFD, nullptr, 0 );

because like it is it is limited to 255 changes for one RCID and then all subsequent updates are ignored because RVER has returned to 0. Some chart updates from NOAA contain much more updates for a single item than 255, for instance in chart US5ME51M feature with RCID=1224 receives more than 1000 updates.

--Philippe

**Comment by rouault** [comment]
> Furthermore, there is a bug in s57Reader.cpp line 2689:

@maitaivw do you mind creating a pull request with that fix ?

**Comment by maitaivw** [comment]
I am not familiar with github but I did something. It is supposed to be pull request #5534
