### ISSUE TITLE
How to install gdal on macOS and how to compile gdal from source files

### ISSUE THREAD

**Issue by EdwinIZ8** [OSGeo/gdal#5462]
## How to install gdal on macOS and how to compile gdal from source files

Hello, Everyone!
I want to install gdal on my MacBook. But what should I do except installing it via homebrew. I tried the method but failed because my MacBook is m1 edition. So I want to compile gdal from source files myself. But how to do it? Do you have a step-by-step tutorial? 

## Operating system

macOS Monterey

## GDAL version and provenance

the 3.4.2 version from official website.

**Comment by jratike80** [comment]
Please take the notice on bug report page seriously

> IMPORTANT: Do NOT use GitHub to post any questions or support requests!
>            They will be closed immediately and ignored.
> 
> Questions should go to the gdal-dev mailing list at
> https://lists.osgeo.org/mailman/listinfo/gdal-dev
> or other support forums. GitHub issues are for bug
> reports and suggestions for new features.
