### ISSUE TITLE
Layer.GetNextFeature() throws exception when there is error that ring not closed in polygon even when Ogr.DontUseExceptions() is set in C#

### ISSUE THREAD

**Issue by nav-ch** [OSGeo/gdal#5488]
## Expected behavior and actual behavior.

When reading a polygon layer in C# using Layer.GetNextFeature() it throws exception when there is error that ring not closed in polygon even when Ogr.DontUseExceptions(); is set. Also there is no way to read that feature in C# as it always throws error saying ring not closed. We inspected the data and found out that the starting and ending point z coordinate has a difference in less that 0.005 units or so. All software like QGIS, ArcGIS, Geomedia etc shows the data. Is there a way to workaround this and read the feature without exception to see the coordinates.

## Steps to reproduce the problem.

Please read the attached polygon which contains 2 records which has error. When we call Layer.GetNextFeature() it throws error.

## Operating system

Windows 10 64 bit

## GDAL version and provenance

Tested with GDAL 3.4.1 and 3.4.2 from Nuget. Both throws the same error. Other features are read properly.
[InvalidPolygon.zip](https://github.com/OSGeo/gdal/files/8321781/InvalidPolygon.zip)

**Comment by rouault** [comment]
This sounds weird to me: neither the generic GetNextFeature() call nor the shapefile driver check that rings are closed. And I don't confirm your issue with the CSharp Mono bindings on Linux:
```
$ (cd swig/csharp && MONO_PATH=. OgrInfo/OgrInfo.exe ../../InvalidPolygon.shp)

Using driver ESRI Shapefile
Layer name: InvalidPolygon
Feature Count: 2
Extent: 365768,2592,365812,334,2666729,287,2666807,3884
Layer SRS WKT: PROJCS["WGS 84 / UTM zone 40N",
    GEOGCS["WGS 84",
        DATUM["WGS_1984",
            SPHEROID["WGS 84",6378137,298.257223563]],
        PRIMEM["Greenwich",0],
        UNIT["degree",0.0174532925199433]],
    PROJECTION["Transverse_Mercator"],
    PARAMETER["latitude_of_origin",0],
    PARAMETER["central_meridian",57],
    PARAMETER["scale_factor",0.9996],
    PARAMETER["false_easting",500000],
    PARAMETER["false_northing",0],
    UNIT["metre",1]]
Field definition:
OBJECTID: Real (20.0)
PARKINGTYP: String (30.0)
SHAPE_Leng: Real (24.15)
SHAPE_Area: Real (24.15)
_errors: String (254.0)

Feature(InvalidPolygon): 0
OBJECTID (Real) = 1850
PARKINGTYP (String) = public
SHAPE_Leng (Real) = 83.000000000000000
SHAPE_Area (Real) = 82.829999999999998
_errors (String) = ring 0 not closed
  POLYGON(wkbPolygon25D)
  subgeom0: LINEARRING(wkbLineString25D)
   ENVELOPE: 365768,2592,365779,903,2666729,287,2666747,409
  POLYGON ((365776.4114 2666747.409 235.339000000007,365779.903 2666741.657 235.426000000007,365777.606 2666740.292 235.422000000006,365778.427 2666738.931 235.434999999998,365776.136 2666737.547 235.429000000004,365776.906 2666736.194 235.441999999995,365774.63 2666734.827 235.436000000002,365775.421 2666733.475 235.460999999996,365773.134 2666732.053 235.452000000005,365773.924 2666730.726 235.468999999997,365771.625 2666729.287 235.486000000004,365769.292 2666733.165 235.395000000004,365768.2592 2666733.1421 235.395000000004,365768.4087 2666733.4038 235.393899999995,365776.4114 2666747.409 235.339999999997))

Feature(InvalidPolygon): 1
OBJECTID (Real) = 1851
PARKINGTYP (String) = public
SHAPE_Leng (Real) = 85.000000000000000
SHAPE_Area (Real) = 85.010000000000005
_errors (String) = ring 0 not closed
  POLYGON(wkbPolygon25D)
  subgeom0: LINEARRING(wkbLineString25D)
   ENVELOPE: 365800,709,365812,334,2666788,71,2666807,3884
  POLYGON ((365808.8565 2666807.3884 235.346000000005,365808.8704 2666806.7885 235.346000000005,365812.334 2666801.081 235.437000000005,365810.05 2666799.659 235.407999999996,365810.874 2666798.317 235.438999999998,365808.553 2666796.925 235.399000000005,365809.369 2666795.601 235.411999999997,365807.068 2666794.171 235.399999999994,365807.894 2666792.868 235.407999999996,365805.564 2666791.439 235.376999999993,365806.393 2666790.101 235.395000000004,365804.098 2666788.71 235.403999999995,365801.772 2666792.498 235.323000000004,365800.709 2666792.4973 235.293000000005,365808.4791 2666806.6986 235.343500000003,365808.8565 2666807.3884 235.447))
```

**Comment by nav-ch** [comment]
I think when I exported the data from gdb to shp file the issue disappeared. I have exported a new gdb with sample data of 5 records where record where IDs 1,2 and 5 are readable but 3 and 4 throws error,. To show the problem I have created a small console application in .Net  framework 4.8 with latest GDAL libraries from Nuget. When you run the application you can see the error in the output. Hope this will help identify the problem which I believe is only for GDB driver.

Also please copy the test data folder to bin>debug or bin>release or change the path in source code.

Source code and test data attached.

[GDAL_Issue_Console.zip](https://github.com/OSGeo/gdal/files/8369118/GDAL_Issue_Console.zip)

Test Data:

[InvalidPolygonTestData.gdb.zip](https://github.com/OSGeo/gdal/files/8369125/InvalidPolygonTestData.gdb.zip)

**Comment by jratike80** [comment]
I can't do anything for the issue but what I can do is to thank you for the test data and test code which both feels excellent!

**Comment by nav-ch** [comment]
Is there any parameter we can set in OGR for this to bypass this exception and return the coordinates itself? Couldn't find anything in the docs or wiki. QGIS and similar software are able to read the data even though this error is shows up.

**Comment by rouault** [comment]
> Is there any parameter we can set in OGR for this to bypass this exception and return the coordinates itself?

I don't think so. This must be a behaviour of the C# bindings to throw an error when a CPLError(CE_Failure, ) has been emitted in the last call.

https://github.com/OSGeo/gdal/pull/5562 avoids this CE_Failure situation
