### ISSUE TITLE
Error while reading geotiff: IReadBlock failed at X offset *, Y offset *: TIFFReadEncodedTile() failed

### ISSUE THREAD

**Issue by ktheijs** [OSGeo/gdal#5489]
## Expected behavior and actual behavior.

I expect to be able to read a specific location of a geotiff but I'm getting an error saying "IReadBlock failed at X offset *, Y offset *: TIFFReadEncodedTile() failed.".

I have seen this issue for many years in many different versions, but I now finally have a dataset on which I can reproduce the issue. I can provide the data privately if it helps to fix the problem.

## Steps to reproduce the problem.

The issue can be reproduced in C# with the code below. This is only one specific location where I know it crashes, but there are multiple.

```
RasterIOExtraArg extraArg = new RasterIOExtraArg();
        extraArg.nVersion = 1;
        extraArg.eResampleAlg = RIOResampleAlg.GRIORA_CubicSpline;
        extraArg.dfXOff = 49265.901653834488;
        extraArg.dfYOff = 665.27952667756563;
        extraArg.dfXSize = 129.00000000002183;
        extraArg.dfYSize = 129.000000000015;
        extraArg.bFloatingPointWindowValidity = 1;

float[] byteBuffer = new float[16384];	
int[] bandMap = { 1 };	
Dataset myDataset = Gdal.Open([MY_FILENAME], Access.GA_ReadOnly)
myDataset .ReadRaster(
         xOff = 49265,
         yOff = 665,
         xSize = 130,
         ySize = 130,
         byteBuffer,
         buf_xSize = 128,
         buf_ySize = 128,
         bandCount = 1,
         bandMap = bandMap,
         pixelSpace = 0,
         lineSpace = 0,
         bandSpace = 0,
         extraArg = extraArg);
```

It can also be reproduced in QGIS by trying to get the pixel info in the same location. I can provide data privately so you can easily find the location. You should get an error like in the screenshot below.

![image](https://user-images.githubusercontent.com/12170304/159459017-eb730420-eae2-4183-b335-81b3090c2588.png)

## Operating system

Windows 11 - 64 bit (OS build 22000.556)

## GDAL version and provenance

GDAL 3.3.3 in C# from https://www.gisinternals.com/
It can also be reproduced in QGIS 3.10.8 (which uses GDAL 3.0.4)
The first time I have encountered this issue must have been more than 4 years ago so I assume it happens in all versions of GDAL.

**Comment by jratike80** [comment]
Try if you can reproduce the error with a raster that you can create with gdal_create https://gdal.org/programs/gdal_create.html

`gdal_create -if your_raster.tif test_raster.tif`

If you can it should be safe to share the new file, it is empty.

**Comment by ktheijs** [comment]
The issue also happens if I pass 'null' instead of extra args. In QGIS they will surely also have different parameters and it also happens there. So it's most likely not related to the extraArgs. 

Through the following link you can download the data: https://www.dropbox.com/t/TgcELr8lZsD5nsFM
* 'ReadIssueRaster.tif' is the dataset that triggers the crash.
* 'issueArea.shp' is marks one area where you can trigger the crash.

**Comment by fbecir** [comment]
Hello
I have downloaded your image and I tried to read the tile (190 , 3).
With GDAL 3.4.2, RasterIO returns an error code.
I tried also with an "home-made" software, and I have also an error in the LZW decompression. The LZW stream seems to be invalid. But I did not have time to really investigate (thus there is perhaps a bug in my software).
What software did you use to generate this image ?
Do you have a software that is able to read this image ?

**Comment by jratike80** [comment]
The file size of the image makes me think that it could be created as a normal TIFF and then reached the 4 GB size limit here:
`ERROR 1: LZWDecode:Wrong length of decoded string: data probably corrupted at scanline 48384`.
The header seems to tell if image is TIFF or BigTIFF stackoverflow.com/questions/43376951/tiff-versus-bigtiff but I did not dare to try to analyze the image.

How did you create the file? Did you create it as BigTIFF?

**Comment by ktheijs** [comment]
I currently don't have the original data, but I am trying to get it. I do know that it has been processed with GDAL_Translate with the options below. It could be that the original was not BigTiff. Could that be the reason why we see this crash? 
If the issue really happens because of a corrupt block, that probably means that it's not possible to create a fix in GDAL's read method, right?

```
-of "GTiff"
-co "BIGTIFF=YES"
-co "TILED=YES"
-co "BLOCKXSIZE=256"
-co "BLOCKYSIZE=256"
-co "NUM_THREADS=ALL_CPUS"
-ot "Float32"
-co "INTERLEAVE=BAND"
-co "COMPRESS=LZW"
-co "PREDICTOR=3"
-b "1"
-q
-stats
```

**Comment by rouault** [comment]
I don't believe this is a BigTIFF related issue. One faulty block is (189,1) which is at offset 72524846.

@ktheijs I'm afraid we can't do anything this ticket with the elements curently available. 2 hypothesis:
- there was a corruption of the file after it was generated
- GDAL (more likely the underlying libtiff) produced a corrupted file. But if that was the case, we'd need a reproducing recipee that takes a non-corrupted file as input and generates the corrupt file.

**Comment by ktheijs** [comment]
Ok thanks @rouault , that's what I was thinking too. I'll do my best to get you that recipee. It seems harder than I hoped though.

When I search online for that error, people keep mentioning that it might be related to having insufficient memory. In the case that I've shared they are also trying to mosaic over 300GB of data. Do you think that could have something to do with it?

This could also explain why it is so hard to reproduce (as it is device specific).

References:
https://lists.osgeo.org/pipermail/gdal-dev/2010-December/026973.html
https://legacy.imagemagick.org/discourse-server/viewtopic.php?t=23490
https://www.mail-archive.com/gdal-dev@lists.osgeo.org/msg09226.html
https://community.safe.com/s/question/0D54Q00008JLG8vSAH/error-building-mosaic-from-tiff-files

**Comment by rouault** [comment]
@wiesehahn could you provide input datasets that can be used to reproduce the issue (that you generated the input tiles with R shouldn't be related. I assume that "gdalinfo -checksum tile1.tif" or tile2.tif works fine ? and that the issue is random failures when generating the COG file ?)

**Comment by wiesehahn** [comment]
gdalinfos results seem to be fine at first glance. 
here are two tiles and also the corresponding VRT  

[testfiles.zip](https://github.com/OSGeo/gdal/files/8876604/testfiles.zip)

**Comment by rouault** [comment]
> here are two tiles and also the corresponding VRT

I've tried to reproduce with those files, on Linux & Windows with latest master on release builds, and that works consistently fine, generating the same output file each time. 12 virtual CPUs here (Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz with 6 cores and hyperthreading)

**Comment by Simone-Brotto** [comment]
Hi,
I am working with QGIS 3.26.0 on Windows 10 pro, I am experiencing this error message:
"crn25_109: IReadBlock failed at X offset 10, Y offset 0: TIFFReadEncodedTile() failed."
I can load and see the file anyway, but I have this annoying error message, error message pops up only with this tif file. Same error was with previous QGIS releases. Here you can download the zip file from local governative site, EPSG is 6708.
https://irdat.regione.fvg.it/cartogdownload/CRN_RASTER/6708/crn25_109_RDN2008_TM33.zip

**Comment by jef-n** [comment]
> Hi, I am working with QGIS 3.26.0 on Windows 10 pro, I am experiencing this error message: "crn25_109: IReadBlock failed at X offset 10, Y offset 0: TIFFReadEncodedTile() failed." I can load and see the file anyway, but I have this annoying error message, error message pops up only with this tif file. Same error was with previous QGIS releases. Here you can download the zip file from local governative site, EPSG is 6708. https://irdat.regione.fvg.it/cartogdownload/CRN_RASTER/6708/crn25_109_RDN2008_TM33.zip

Not reproducable OSGeo4W (QGIS 3.26.0 w/ GDAL 3.5.0)

**Comment by agiudiceandrea** [comment]
> Not reproducable OSGeo4W (QGIS 3.26.0 w/ GDAL 3.5.0).

@jef-n, try zooming in and out in the northern part of the image:

```
2022-06-29T16:29:19     WARNING    crn25_109_RDN2008_TM33 — crn25_109.tif : IReadBlock failed at X offset 1, Y offset 0: TIFFReadEncodedTile() failed.
2022-06-29T16:29:33     WARNING    crn25_109_RDN2008_TM33 — crn25_109.tif : IReadBlock failed at X offset 26, Y offset 0: TIFFReadEncodedTile() failed.,IReadBlock failed at X offset 26, Y offset 0: TIFFReadEncodedTile() failed.,IReadBlock failed at X offset 26, Y offset 0: TIFFReadEncodedTile() failed.
2022-06-29T16:29:33     WARNING    crn25_109_RDN2008_TM33 — crn25_109.tif : IReadBlock failed at X offset 26, Y offset 0: TIFFReadEncodedTile() failed.
2022-06-29T16:29:39     WARNING    crn25_109_RDN2008_TM33 — crn25_109.tif : IReadBlock failed at X offset 16, Y offset 0: TIFFReadEncodedTile() failed.,IReadBlock failed at X offset 16, Y offset 0: TIFFReadEncodedTile() failed.,IReadBlock failed at X offset 16, Y offset 0: TIFFReadEncodedTile() failed.
2022-06-29T16:29:39     WARNING    crn25_109_RDN2008_TM33 — crn25_109.tif : IReadBlock failed at X offset 16, Y offset 0: TIFFReadEncodedTile() failed.
2022-06-29T16:29:53     WARNING    crn25_109_RDN2008_TM33 — crn25_109.tif : IReadBlock failed at X offset 35, Y offset 0: TIFFReadEncodedTile() failed.,IReadBlock failed at X offset 35, Y offset 0: TIFFReadEncodedTile() failed.,IReadBlock failed at X offset 35, Y offset 0: TIFFReadEncodedTile() failed.
2022-06-29T16:29:53     WARNING    crn25_109_RDN2008_TM33 — crn25_109.tif : IReadBlock failed at X offset 35, Y offset 0: TIFFReadEncodedTile() failed.
2022-06-29T16:30:19     WARNING    crn25_109_RDN2008_TM33 — crn25_109.tif : IReadBlock failed at X offset 6, Y offset 0: TIFFReadEncodedTile() failed.,IReadBlock failed at X offset 6, Y offset 0: TIFFReadEncodedTile() failed.,IReadBlock failed at X offset 6, Y offset 0: TIFFReadEncodedTile() failed.
2022-06-29T16:30:19     WARNING    crn25_109_RDN2008_TM33 — crn25_109.tif : IReadBlock failed at X offset 6, Y offset 0: TIFFReadEncodedTile() failed.
2022-06-29T16:30:23     WARNING    crn25_109_RDN2008_TM33 — crn25_109.tif : IReadBlock failed at X offset 4, Y offset 0: TIFFReadEncodedTile() failed.,IReadBlock failed at X offset 4, Y offset 0: TIFFReadEncodedTile() failed.,IReadBlock failed at X offset 4, Y offset 0: TIFFReadEncodedTile() failed.
2022-06-29T16:30:23     WARNING    crn25_109_RDN2008_TM33 — crn25_109.tif : IReadBlock failed at X offset 4, Y offset 0: TIFFReadEncodedTile() failed. 
```

**Comment by rouault** [comment]
> https://irdat.regione.fvg.it/cartogdownload/CRN_RASTER/6708/crn25_109_RDN2008_TM33.zip

as far as I can see, the full resolution image is OK, but the first overview level is corrupted. The issue is on the data producer side.

**Comment by rouault** [comment]
closing as not a GDAL bug

**Comment by robmarkcole** [comment]
I have experienced this error after attempting to open an image that has been downloaded from S3 using s3fs. The same image can be read from S3 direct with error, so the file must be corrupted. Strangely it is only affecting one band

**Comment by Zhugguanglei** [comment]
I also experienced this error after attempting to open an Landsat image. The data is just official Level 2 product. My computer environment is Windows 10 ，python=3.8， GDAL=3.6.0，but  on my other  computer，GDAL=3.3.3, it can work. @rouault

**Comment by Zhugguanglei** [comment]
I think the issue is a GDAL bug. I created a new anaconda environment set the same packages except GDAL version, when GDAL version > 3.3.3, the bug will happen. @rouault

**Comment by jratike80** [comment]
Test data is needed. Add a link to "The just official Level 2 product".

**Comment by Zhugguanglei** [comment]
This is official Level 2 product [https://drive.google.com/file/d/1Z02jXPoO8qNKorygflv9sdwdkTYDep-V/view?usp=sharing](url),I also find that if GDAL is installed by conda ,the bug will happen(No matter which version), but if GDAL is installed by whl file ,it can work, the version also should be < 3.3.*. I download the whl file from [https://www.lfd.uci.edu/~gohlke/pythonlibs/#gdal](url)

**Comment by agiudiceandrea** [comment]
@Zhugguanglei, I don't see any issue opening the provided raster with QGIS 3.28.5 using GDAL 3.6.3 or QGIS 3.28.6 using GDAL 3.6.4.

**Comment by jratike80** [comment]
Works for me with GDAL 3.7.0dev-5ce7ba068f, released 2023/01/17 on Windows, from gisinternals, and with GDAL 3.6.4, released 2023/04/17 from OSGeo4W. Tested with this command that I suppose to read and copy the full resolution data and all overviews as well:
`gdal_translate -of COG LC08_L2SP_128032_20200603_20200824_02_T1_SR_B4.TIF copy2.tif --config COPY_SRC_OVERVIEWS YES`

**Comment by Zhugguanglei** [comment]
> gdal_translate -of COG LC08_L2SP_128032_20200603_20200824_02_T1_SR_B4.TIF copy2.tif --config COPY_SRC_OVERVIEWS YES

Works also for me， tested with your command ，but when I run the code：

`tif_file = r'D:\Desktop\Work\2022\smart_irrigation\LC08_L2SP_128032_20200603_20200824_02_T1_SR_B4.TIF'
in_ds = gdal.Open(tif_file )
in_band = in_ds.GetRasterBand(1)
ds_arr = in_band.ReadAsArray()`
when I use the pycharm debug the ds_rr shows is None and it  produced the following information：
`ERROR 1: ZIPDecode:Decoding error at scanline 1536
ERROR 1: TIFFReadEncodedTile() failed.
ERROR 1: D:\Desktop\Work\2022\smart_irrigation\LC08_L2SP_128032_20200603_20200824_02_T1_SR_B4.TIF, band 1: IReadBlock failed at X offset 6, Y offset 0: TIFFReadEncodedTile()  failed.`
@jratike80

**Comment by jratike80** [comment]
Because the error comes from ERROR 1: ZIPDecode: I wonder if there could be some difference in the library that takes care of decompressing the DEFLATE compressed data.

**Comment by rouault** [comment]
@Zhugguanglei Trying with a fresh Conda environment on Windows with the conda-forge channel, I can't reproduce any issue.

As this is deflate TIFF compression, the relevant libraries are libgdal, libtiff, zlib and libdeflate. Here are the versions I've tested (as indicate by "conda list"):
```
# Name                    Version                   Build  Channel
libgdal                   3.6.4                h36c8192_2    conda-forge
libtiff                   4.5.0                h6c8260b_6    conda-forge
zlib                      1.2.13               hcfcfb64_4    conda-forge
libdeflate                1.18                 hcfcfb64_0    conda-forge
```

**Comment by Zhugguanglei** [comment]
> Because the error comes from `ZIPDecode:` I wonder if there could be some difference in the library that takes care of decompressing the DEFLATE compressed data.

Thanks for your reply, will try your suggestion

**Comment by shixi2ng** [comment]
> I also experienced this error after attempting to open an Landsat image. The data is just official Level 2 product. My computer environment is Windows 10 ，python=3.8， GDAL=3.6.0，but on my other computer，GDAL=3.3.3, it can work. @rouault

I have experienced the same problem. When I installed gdal in a new conda environment with the conda-forge channel, the following error occurred no matter which version I installed (3.3.2, 3.4.3, 3.6.2). But using the pip install instead the gdal with version 3.4.3, it can successfully read the TIF files.

Error using conda-installed gdal:
```
ERROR 1: ZIPDecode: Decoding error at scanline 1280
ERROR 1: TIFFReadEncodedTile() failed.
ERROR 1: G:\A_Landsat_veg\LC08_L2SP_122039_20130910_20200913_02_T1_SR_B3.TIF, band 1: IReadBlock failed at X offset 5, Y offset 0: TIFFReadEncodedTile() failed.
```

OS: Win 10 pro (Win 64)
Python version: Anaconda Python 3.8.1

The TIF file can be found here: https://drive.google.com/file/d/1o-jkhStxHOmiWrom15U2TUdsVoURMrrx/view?usp=sharing

**Comment by agiudiceandrea** [comment]
@shixi2ng, I don't see any issue using the provided raster layer on Windows with QGIS 3.28 and GDAL 3.7 from OSGeo4W.

**Comment by shixi2ng** [comment]
> @shixi2ng, I don't see any issue using the provided raster layer on Windows with QGIS 3.28 and GDAL 3.7 from OSGeo4W.


I apologize if my previous statement was unclear. What I want to describe is that the GDAL package from conda-forge may have some issues, leading to problems similar to those described in this topic.

**Comment by filippeof** [comment]
After having a simillar issue for some time (in my case using Warp and gdal_merge.py), I tried to remove parameters one by one. Apparently "NUM_THREADS=ALL_CPUS" was raising the issue. 
gdal = 3.6.2 installed through conda, w10
I am happy to provide more details if needed.

**Comment by anupambera** [comment]
I have experienced the same problem when adding overviews to a big GeoTiff file (>300 GB) using the GDAL `gdaladdo` utility. I rerun the same command and got success. It might be a memory-related issue.

![Screenshot 2024-10-07 193409](https://github.com/user-attachments/assets/4ea4b3c1-0c60-46db-9670-714d453ce641)

**Comment by pgeleg** [comment]
I have a service that processes data. I get this error occasionally and its inconsistent. 

The service, on failure, retries on subsequent runs of the service. Using the same code and same input data, it works the following time. 

So at least in the cases I've seen it, it seems like an issue that happens on an inconsistent basis. Usually maybe 1 in every 50-100 GeoTIFFs that go through processing.

Linux server and GDAL installed through conda-forge and across various versions of GDAL 3.6.2 to GDAL 3.10.3

Traceback (sorry for poor formatting for anyone reading):

```
Error: NYC_REGION_20250312.tiff, band 3: IReadBlock failed at X offset 0, Y offset 2068: TIFFReadEncodedStrip() failed.
May be caused by: TIFFReadEncodedStrip() failed.
May be caused by: ZIPDecode:Decoding error at scanline 2068 Class: RuntimeError Traceback:  File "/home/my.user/my_app/utils.py", line 545, in check_for_val |     arr = band.ReadAsArray() |   File "/home/my.user/.conda/envs/my_conda_env/lib/python3.13/site-packages/osgeo/gdal.py", line 8265, in ReadAsArray |     return gdal_array.BandReadAsArray(self, xoff, yoff, |            ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^ |                                        win_xsize, win_ysize, |                                        ^^^^^^^^^^^^^^^^^^^^^ |     ...<2 lines>... |                                        callback=callback, |                                        ^^^^^^^^^^^^^^^^^^ |                                        callback_data=callback_data) |                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ |   File "/home/my.user/.conda/envs/my_conda_env/lib/python3.13/site-packages/osgeo/gdal_array.py", line 634, in BandReadAsArray |     if BandRasterIONumPy(band, 0, xoff, yoff, win_xsize, win_ysize, |        ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ |                          buf_obj, buf_type, resample_alg, callback, callback_data) != 0: |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ |   File "/home/my.user/.conda/envs/my_conda_env/lib/python3.13/site-packages/osgeo/gdal_array.py", line 252, in BandRasterIONumPy |     return _gdal_array.BandRasterIONumPy(band, bWrite, xoff, yoff, xsize, ysize, psArray, buf_type, resample_alg, callback, callback_data) | 
```

**Comment by lagamura** [comment]
> After having a simillar issue for some time (in my case using Warp and gdal_merge.py), I tried to remove parameters one by one. Apparently "NUM_THREADS=ALL_CPUS" was raising the issue. gdal = 3.6.2 installed through conda, w10 I am happy to provide more details if needed.

@filippeof That is intresting to me as I am facing the some corrupted products with:
```txt
Input file size is 10980, 10980
0...10...20...30..ERROR 1: ZSTDDecode:Error in ZSTD_decompressStream(): Corrupted block detected
ERROR 1: TIFFReadEncodedTile() failed.
ERROR 1: PRODUCT_NAME.tiff, band 1: IReadBlock failed at X offset 20, Y offset 16: TIFFReadEncodedTile() failed.
```

And I also use `NUM_THREADAS=ALL_CPUS`. Did you ever dig further into it? Or have you seen that reported elsewhere too?

**Comment by wiesehahn** [comment]
Not sure but I think in my case it is related to some network problems. I am under Windows and the files are read from a network drive. 
I also encounter this occasionally in QGIS, after some time the layer cannot be read anymore and I see a message
`some_raster.tif, band 1: IReadBlock failed at X offset 56, Y offset 79: TIFFReadEncodedTile() failed.`
Setting the layer source again helps temporarily, but the error might reappear after some time. What helps better is to define the layer source as UNC-path instead of mapped drive paths (e.g. `\\lb-srv\folder\some_raster.tif` instead of `Y:\folder\some_raster.tif`)
