### ISSUE TITLE
VFK: Driver parser bug

### ISSUE THREAD

**Issue by seidlmic** [OSGeo/gdal#5495]
## Expected behavior and actual behavior.
The text data cointaining apostrophs are wrongly parsed.

## Steps to reproduce the problem.
The data from block OPSUB
`&DOPSUB;612140308;0;"06.01.2015 12:39:49";"";3;34900368010;;;;;"OPO";11;47252472;;"""South Bohemia Star"" spoleènost s ruèením omezeným";"""SOUTH BOHEMIA STAR"" SPOLECNOST S RUCENIM OMEZENYM";"";"";"";"";"";"";"";718;"";"©tìpnice";"Veselí nad Lu¾nicí II";"Veselí nad Lu¾nicí";"";"";39181;"";1;"";;6729223;
`

Should result with text `"South Bohemia Star" ...` but you will get `South Bohemia Star ...` The apostrophs are completely stripped. The correct result was also verified with WSDP service that returns `"South Bohemia Star" ...`

## Operating system

Debian

## GDAL version and provenance

compiled from source GDAL 2.4.4

**Comment by rouault** [comment]
CC @landam

**Comment by seidlmic** [comment]
Not known when and how (may be by correcting multi line data issue) but current driver version parses correctly.
