### ISSUE TITLE
GRIB Split&Swap mode doesn't trigger with GFSWave files

### ISSUE THREAD

**Issue by zakjan** [OSGeo/gdal#5496]
## Expected behavior and actual behavior.

GRIB Split&Swap mode (#4526) doesn't trigger with GFSWave files, because they fail a check: https://github.com/OSGeo/gdal/blob/bf46d36353e260eaff378c9fcd5ea1269871b0ff/frmts/grib/gribdataset.cpp#L2583-L2585 

The files have a weird pixel X size 0.250000011118833. (Regular GFS files have a correct pixel X size of 0.25)

1440 * 0.250000011118833 = 360.000016011119520

I'm not sure what would be the proper fix though. Update the check to allow overlap of a single pixel?

## Steps to reproduce the problem.

Download file from https://nomads.ncep.noaa.gov/pub/data/nccf/com/gfs/prod/gfs.20220323/00/wave/gridded/gfswave.t00z.global.0p25.f000.grib2 (adjust the date if it doesn't exist anymore).

```
$ gdalinfo --debug ON gfswave.t00z.global.0p25.f000.grib2
...
GRIB: Cannot properly handle GRIB2 files with overlaps and 0-360 longitudes
...
Size is 1440, 721
...
Pixel Size = (0.250000011118833,-0.250000000000000)
```

## Operating system

macOS 12.1 M1

## GDAL version and provenance

3.4.2 from brew

**Comment by rouault** [comment]
CC @mmomtchev

**Comment by mmomtchev** [comment]
Yes, I guess that should be protected by a `fabs` like the line below

**Comment by zakjan** [comment]
Thanks @mmomtchev!
