### ISSUE TITLE
Feature Request: Add support for named NEATLINE extraction from Adobe ISO32000 style Geospatial PDF 

### ISSUE THREAD

**Issue by pascalscheffers** [OSGeo/gdal#5504]
The pdf driver already supports the extraction of named NEATLINE in pdfs following the best practices as outlined in 08-139r3_GeoPDF_Encoding_Best_Practice_Version_2.2.pdf (that's the comment in pdfdataset.cpp, line 4781).

I've implemented the same functionality for Adobe ISO32000 style Geospatial PDF and will create a pull request to integrate this shortly. This format output by Esri ArcMap. 

I have used the same NEATLINE command line option to specify the name.
I have added two CPLDebug lines to debug the new behaviour. One outputs the names of the viewports as they occur in the dictionary. The second one outputs the index of the viewport name if it was selected.
If no NEATLINE was requested or there is no match, the largest viewport is selected as before.

**Comment by rouault** [comment]
fixed per https://github.com/OSGeo/gdal/pull/5507
