### ISSUE TITLE
gdal_grid inefficiencies

### ISSUE THREAD

**Issue by bnordgren** [OSGeo/gdal#5530]
## Proposed enhancement

`gdal_grid` appears to "brute force" its way through the entire collection of geometries in order to generate a value for each pixel. I'd have expected it to preselect only those points within the envelope via some smart spatial indexing. 

This was brought up concerning the 1.x series 14 years ago on this Trac ticket: https://trac.osgeo.org/gdal/ticket/2411. A patch was produced to apply against then-subversion revision r15067. (Now d70f96a276d3129f8e58d3fe4e23d901e9116478)

The above trac ticket was confusingly closed 6 years ago after noting that the patch had _not_ been applied yet, but that it should help if it were to be applied.

When you have a few million pixels, a few million points, and a few dozen scenes to do; brute forcing can take quite a long time.

**Comment by rouault** [comment]
GDAL uses a quadtree structure for nearest neighbour and inverse distance to a power nearest neighbour. There's a queued enhancement to extend this to other algorithms as well: https://github.com/OSGeo/gdal/pull/5397
