### ISSUE TITLE
Converting .tiff (raster) file to vector (.shp) with gdal.Polygonize do not transfers CRS to output_file

### ISSUE THREAD

**Issue by janceviciusjulius** [OSGeo/gdal#5537]
Good afternoon,

While converting raster to vector, output file do not have CRS projection.
![image](https://user-images.githubusercontent.com/64422065/160607376-942f4219-11bb-4ca2-8e7b-ee1147697883.png)

Code:
![image](https://user-images.githubusercontent.com/64422065/160607185-eb2ad2f5-30af-49bf-89d4-999bcc569e1c.png)

**Comment by jratike80** [comment]
Did you see
IMPORTANT: Do NOT use GitHub to post any questions or support requests!
           They will be closed immediately and ignored.

Questions should go to the gdal-dev mailing list at
https://lists.osgeo.org/mailman/listinfo/gdal-dev
or other support forums. GitHub issues are for bug
reports and suggestions for new features.

I do not know much about coding but you seem to create the output layer as `srs=None` and it makes me feel that you get what you have asked for.

**Comment by jratike80** [comment]
Have a look at gdal_polygonize.py https://github.com/OSGeo/gdal/blob/master/swig/python/gdal-utils/osgeo_utils/gdal_polygonize.py with lines like

 ```
  srs = src_ds.GetSpatialRef()
        dst_layer = dst_ds.CreateLayer(dst_layername, geom_type=ogr.wkbPolygon, srs=srs)
```

**Comment by janceviciusjulius** [comment]
I am sorry. Thank You for your reply. Have a nice day
