### ISSUE TITLE
MITAB: Update list of Ellipsoids

### ISSUE THREAD

**Issue by maximchurilin** [OSGeo/gdal#5541]
In MapInfo 16.0.4 two new ellipsoids were added.
Information can be seen for example in this file on page 22: https://download.mapinfo.ru/~estimap/download/download_new/Desktop_GIS/MapInfo_Professional/documentation_ru/1604_MapInfoProReleaseNotes.pdf

Is it okay to add them to asSpheroidInfoList in mitab_spatialref.cpp? I could make commit and pull request if needed.

**Comment by rouault** [comment]
> Is it okay to add them to asSpheroidInfoList in mitab_spatialref.cpp? I could make commit and pull request if needed.

sure
