### ISSUE TITLE
[cmake] how to properly disable drivers/features

### ISSUE THREAD

**Issue by landryb** [OSGeo/gdal#5558]
## Expected behavior and actual behavior.

Packaging 3.5.0alpha1 on OpenBSD, i want to switch to cmake-based builds - for packaging reasons, i want to selectively disable some drivers and make sure they wont get silently picked when found by cmake (as the build env might be different from what i have on my machine), but it seems that doesnt 100% work. I also want to use support for *_ROOT to specify that dependencies should be found/searched for under `/usr/local`.

from reading https://gdal.org/build_hints.html and picking mysql as the example, `GDAL_USE_MYSQL=OFF` (or `GDAL_USE_MYSQL=Bool:OFF` ?) in cmake args is supposed to disable the use of this driver even if cmake finds it.

but configure output says:
```
...
-- Found MySQL: /usr/local/lib/libmysqlclient.so.29.0 (found version "")
...
-- The following features have been enabled:
...
 * ogr_MYSQL, MySQL       
...          
-- The following OPTIONAL packages have been found:   
...
 * MySQL
   MySQL
```
so it seems disabling drivers doesnt work how it's documented.

furthermore, at the end of configure i have this list of CMake warnings (which mostly refer to drivers i'm trying to make sure arent picked if found):

```
CMake Warning:
  Manually-specified variables were not used by the project:

    GDAL_USE_CFITSIO
    GDAL_USE_CRYPTOPP
    GDAL_USE_HEIF
    GDAL_USE_IDB
    GDAL_USE_MYSQL
    GDAL_USE_ODBC
    GDAL_USE_OPENEXR
    GDAL_USE_POSTGRESQL
    GDAL_USE_XERCESC
    OPENJPEG_ROOT
```

I'm not sure if the documentation needs updating or the cmake machinery. Is the casing of mysql right ?

## Operating system

OpenBSD

## GDAL version and provenance

3.5.0alpha1

**Comment by dg0yt** [comment]
You might be interested in `GDAL_USE_EXTERNAL_LIBS`:
https://gdal.org/build_hints.html#cmdoption-arg-GDAL_USE_EXTERNAL_LIBS-BOOL

**Comment by rouault** [comment]
>  (or GDAL_USE_MYSQL=Bool:OFF ?) 

no, that must be GDAL_USE_MYSQL=OFF or GDAL_USE_MYSQL:BOOL=OFF


``cmake .. -DGDAL_USE_MYSQL=OFF`` works for me
```
-- Disabled components:

 *MYSQL component has been detected, but is disabled with GDAL_USE_MYSQL=OFF
```

To avoid any potential side effects of options that have influence on others, make sure to remove CMakeCache.txt when changing options

If issues persist, please paste your exact cmake invokation

**Comment by landryb** [comment]
found where it came from, the _ in `GDAL_USE` in my port Makefile was an unprintable utf char or something, when looking at CMakeCache.txt on another box this jumped to the eye... *sigh*.

now the detected bits are indeed properly disabled:
```
-- Disabled components:

 *MYSQL component has been detected, but is disabled with GDAL_USE_MYSQL=OFF
 *XERCESC component has been detected, but is disabled with GDAL_USE_XERCESC=OFF
 *CRYPTOPP component has been detected, but is disabled with GDAL_USE_CRYPTOPP=OFF
 *OPENEXR component has been detected, but is disabled with GDAL_USE_OPENEXR=OFF
```
Nevertheless, it seems the *_ROOT vars arent used as advertised in https://gdal.org/build_hints.html#cmdoption-arg-CMAKE_PREFIX_PATH:
```
CMake Warning:
  Manually-specified variables were not used by the project:

    OPENJPEG_ROOT
```
and it seems there are inconsistencies between `*_DIR` and `*_ROOT`, because even if deps are found the 'missing' msgs are a bit misleading.. with this argument list
```
-DGDAL_USE_CFITSIO:BOOL=OFF  -DGDAL_USE_CRYPTOPP:BOOL=OFF  -DGDAL_USE_XERCESC:BOOL=OFF  -DGDAL_USE_MYSQL:BOOL=OFF  -DGDAL_USE_HEIF:BOOL=OFF  -DGDAL_USE_ODBC:BOOL=OFF  -DGDAL_USE_QHULL:BOOL=OFF  -DGDAL_USE_IDB:BOOL=OFF  -DGDAL_USE_OPENEXR:BOOL=OFF  -DPython_ROOT=/usr/local  -DGEOS_ROOT=/usr/local  -DSPATIALITE_ROOT=/usr/local  -DPNG_ROOT=/usr/local  -DTIFF_ROOT=/usr/local  -DCURL_ROOT=/usr/local  -DGIF_ROOT=/usr/local  -DJPEG_ROOT=/usr/local  -DOPENJPEG_DIR=/usr/local  -DGeoTIFF_DIR=/usr/local  -DJSONC_DIR=/usr/local  -DRASTERLITE2_DIR=/usr/local  -DZSTD_DIR=/usr/local  -DHDF5_DIR=/usr/local -DPYTHON_EXECUTABLE=/usr/local/bin/python3.9 -DPYTHON_LIBRARY_DIRS=/usr/local/lib/python3.9 -DPYTHON_INCLUDE_DIR=/usr/local/include/python3.9 -DCMAKE_BUILD_TYPE=Release
```
i get during configure:
```
-- Could NOT find CURL (missing: CURL_DIR)
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
-- Found CURL: /usr/local/lib/libcurl.so.26.13 (found version "7.82.0")  
...
-- Could NOT find ZSTD (missing: ZSTD_DIR)
-- Found ZSTD: /usr/local/lib/libzstd.so.6.1 (found version "1.5.2")  
...
-- Could NOT find GeoTIFF (missing: GeoTIFF_DIR)
-- Found GeoTIFF: /usr/local/lib/libgeotiff.so.3.1 (found version "1.7.1.0") 
...
-- Could NOT find JSONC (missing: JSONC_DIR)
-- Found JSONC: /usr/local/lib/libjson-c.so.1.1  
```
that's with cmake 3.20.3 packaged on OpenBSD.

CMakeCache.txt attached
[CMakeCache.txt](https://github.com/OSGeo/gdal/files/8407947/CMakeCache.txt)

**Comment by landryb** [comment]
ok, rereading the CMakeCache file, it seems `*package*_DIR` should be 'the path to a dir which contains a cmake config file/module for *package*' ? should point to /usr/local/share/cmake/Modules/ then ?

**Comment by rouault** [comment]
One important point for the _ROOT and _DIR variables is that you must match the case of the module . For OpenJPEG, this is "OpenJPEG" : https://gdal.org/build_hints.html#openjpeg , despite that module accepting OPENJPEG_INCLUDE_DIR/_LIBRARY in full uppercase. I know this is confusing. Part of that comes from a diversity of FindXXXX.cmake that were imported.

> it seems *package*_DIR should be 'the path to a dir which contains a cmake config file/module for package' ? should point to /usr/local/share/cmake/Modules/ then ?

yes

**Comment by landryb** [comment]
thanks even, that's much clearer this way, and yes cmake can be damn confusing :)

I also thought that the Jasper/JPEG2000 driver was supposed to be ditched/disabled by default in 3.5, but apparently if jasper is found by cmake then it's enabled in the build by default (and fails for me):

```
In file included from /usr/obj/ports/gdal-3.5.0alpha1-python3/gdal-3.5.0alpha1/frmts/jpeg2000/jpeg2000_vsil_io.cpp:81:                   
In file included from /usr/obj/ports/gdal-3.5.0alpha1-python3/gdal-3.5.0alpha1/frmts/jpeg2000/jpeg2000_vsil_io.h:33:                                                                                                                                                              
In file included from /usr/local/include/jasper/jasper.h:73:                                                                                                                                                                                                                      
/usr/local/include/jasper/jas_config.h:115:2: warning: "Your code is being built against an older version of the C standard than JasPer was.  Although this is supported, this may require some extra preprocessor defines when building." [-W#warnings]                          
#warning "Your code is being built against an older version of the C standard than JasPer was.  Although this is supported, this may require some extra preprocessor defines when building."                                                                                      
 ^    
....
In file included from /usr/obj/ports/gdal-3.5.0alpha1-python3/gdal-3.5.0alpha1/frmts/jpeg2000/jpeg2000_vsil_io.cpp:82:
In file included from /usr/obj/ports/gdal-3.5.0alpha1-python3/gdal-3.5.0alpha1/port/cpl_vsi.h:35:
In file included from /usr/obj/ports/gdal-3.5.0alpha1-python3/gdal-3.5.0alpha1/port/cpl_port.h:139:
In file included from /usr/include/c++/v1/math.h:309:
In file included from /usr/include/c++/v1/type_traits:420:
/usr/include/c++/v1/cstddef:53:9: error: expected unqualified-id
using ::max_align_t _LIBCPP_USING_IF_EXISTS;
        ^
/usr/local/include/jasper/jas_types.h:185:22: note: expanded from macro 'max_align_t'
#       define max_align_t long double
                           ^
/usr/obj/ports/gdal-3.5.0alpha1-python3/gdal-3.5.0alpha1/frmts/jpeg2000/jpeg2000_vsil_io.cpp:152:5: error: cannot initialize a member subobject of type 'ssize_t (*)(jas_stream_obj_t *, char *, size_t)' (aka 'long (*)(void *, char *, unsigned long)') with an lvalue of type 'int (jas_stream_obj_t *, char *, unsigned int)' (aka 'int (void *, char *, unsigned int)'): type mismatch at 3rd parameter ('size_t' (aka 'unsigned long') vs 'unsigned int')
    JPEG2000_VSIL_read,
    ^~~~~~~~~~~~~~~~~~
/usr/obj/ports/gdal-3.5.0alpha1-python3/gdal-3.5.0alpha1/frmts/jpeg2000/jpeg2000_vsil_io.cpp:153:5: error: cannot initialize a member subobject of type 'ssize_t (*)(jas_stream_obj_t *, const char *, size_t)' (aka 'long (*)(void *, const char *, unsigned long)') with an lvalue of type 'int (jas_stream_obj_t *, const char *, unsigned int)' (aka 'int (void *, const char *, unsigned int)'): type mismatch at 3rd parameter ('size_t' (aka 'unsigned long') vs 'unsigned int')
    JPEG2000_VSIL_write,
    ^~~~~~~~~~~~~~~~~~~
88 warnings and 3 errors generated.
```
i'll disable it locally with `-DGDAL_USE_JASPER:BOOL=OFF` now that i have the proper invocation :)

**Comment by rouault** [comment]
> I also thought that the Jasper/JPEG2000 driver was supposed to be ditched/disabled by default in 3.5,

this has been done just last week, so after 3.5.0alpha1 was cut

**Comment by landryb** [comment]
great, thanks ! closing now, since your hints properly addressed the issues i had disabling features. thanks for your time :)
