### ISSUE TITLE
Build fails with "--with-poppler=yes --enable-pdf-plugin" configure options

### ISSUE THREAD

**Issue by RichardLangFromNZ** [OSGeo/gdal#556]
Native build on linux Mint 18 (/ubuntu 16.04) with GCC 5.4.0, of gdal trunk commit hash 0ac25aa

I've been working on figuring out the required configuration for generating a minimal external dependencies build, in preparation for cross-compiling.  All external drivers have been disabled apart from sqlite, and basic geo-referenced image support (jpeg, tiff etc.) switched to internal.  Project configured as follows:

    configure --with-hide-internal-symbols=yes --with-libtool --without-bsb --without-cfitsio --without-cryptopp --without-curl --without-ecw --without-expat --without-fme --without-freexl --without-gnm --without-geos --without-grass --without-grib --without-hdf4 --without-hdf5 --without-idb --without-ingres --without-jasper --without-jp2mrsid --without-kakadu --without-libgrass --without-libkml --without-libjson-c --without-mrf --without-mrsid --without-mysql --without-netcdf --without-odbc --without-ogdi --without-openjpeg --without-pcidsk --without-pcraster --without-pcre --without-perl --without-pg --without-php --without-python --without-qhull --without-sde --without-webp --without-xerces --without-xml2 --with-geotiff=internal --with-libtiff=internal --with-libz=internal --with-png=internal --with-jpeg=internal --with-gif=internal --with-libjson-c=internal    --with-threads --with-sqlite3=yes

Build completed successfully and components seemed to behave in a sensible manner. 

However when I add `--with-poppler=yes --enable-pdf-plugin` to the configure options and rerun the configure & build in a clean working copy it eventually fails with the following:

```
make[1]: Entering directory '/home/richard/SATCO/Development/gdal_issues/gdal/gdal/frmts/pdf'
/bin/bash /home/richard/SATCO/Development/gdal_issues/gdal/gdal/libtool --mode=compile --silent
--tag=CXX g++ -std=c++11 -DHAVE_AVX_AT_COMPILE_TIME -DHAVE_SSSE3_AT_COMPILE_TIME
-DHAVE_SSE_AT_COMPILE_TIME -g -O2 -fvisibility=hidden  -Wall -Wextra -Winit-self -Wunused-parameter
-Wformat -Werror=format-security -Wno-format-nonliteral -Wlogical-op -Wshadow -Werror=vla -Wdate-
time -Wfloat-conversion -Wmissing-declarations -Wnon-virtual-dtor -Woverloaded-virtual -fno-
operator-names -Wzero-as-null-pointer-constant -Wsuggest-override  -I../vrt -I../mem
-I../../ogr/ogrsf_frmts/mem -I/home/richard/SATCO/Development/gdal_issues/gdal/gdal/port
-DGDAL_COMPILATION -DHAVE_POPPLER -DPOPPLER_HAS_OPTCONTENT -DPOPPLER_BASE_STREAM_HAS_TWO_ARGS
-DPOPPLER_0_20_OR_LATER -DPOPPLER_0_23_OR_LATER -I/usr/include -I/usr/include/poppler
-DDO_NOT_USE_DEBUG_BOOL  -c -o pdfdataset.o pdfdataset.cpp
In file included from pdfdataset.cpp:36:0: 
gdal_pdf.h:55:22: fatal error: gdal_pam.h: No such file or directory
```
Looks to me like the configure script has neglected to generate an include path for `gcore`

Complete build log attached.
[build_log.txt](https://github.com/OSGeo/gdal/files/1962740/build_log.txt)

**Comment by rouault** [comment]
Semi satisfactory 'fix' pushed in https://github.com/OSGeo/gdal/commit/23ae02c65c4fca4b86196b82a0ea602e7a67e4e6 . I tried to fix frmts/pdf/GNUmakefile to support libtool builds but didn't succeed
