### ISSUE TITLE
GRIB: segfault with multidim API via vsicurl when .idx file is present

### ISSUE THREAD

**Issue by mdsumner** [OSGeo/gdal#5569]
## Expected behavior and actual behavior.

This GRIB source URL causes a segfault when used with '/vsicurl' with gdalmdiminfo.

> https://noaa-gefs-pds.s3.amazonaws.com/gefs.20220316/00/atmos/pgrb2ap5/gep01.t00z.pgrb2a.0p50.f024

Works fine with gdalinfo, and (more importantly) if the '-oo USE_IDX=NO' option is added. 

## Steps to reproduce the problem.

This works. change 'NO' to 'YES' to segfault

```bash
gdalmdiminfo  /vsicurl/https://noaa-gefs-pds.s3.amazonaws.com/gefs.20220316/00/atmos/pgrb2ap5/gep01.t00z.pgrb2a.0p50.f024 --oo USE_IDX=NO
```

## Operating system

Ubuntu 20.04 64 bit

## GDAL version and provenance

Tested on 3.4.0 and master 

> GDAL 3.5.0dev-859cf88b0a-dirty, released 2022/04/03
> GDAL 3.4.0, released 2021/11/04

**Comment by jratike80** [comment]
I do not know what this message that I get with `-oo USE_IDX=YES --debug on` means and if it has something to do with the issue:
`GRIB: Rewrapping around the antimeridian at column 360`
Anyway, I get that with GDAL 3.5.0dev on Windows. With USE_IDX=NO I do not see that line about rewrapping and gdalmdiminfo prints a long report.

The documentation https://gdal.org/drivers/raster/grib.html does not tell if USE_IDX is supported for gdamdiminfo. It only tells that for gdalinfo it is not supported.
