### ISSUE TITLE
gdal2tile.py pool not closed in case of failure

### ISSUE THREAD

**Issue by zeevdr** [OSGeo/gdal#5581]
The pool opened in
https://github.com/OSGeo/gdal/blob/95c9d336b2db0c5d240f191638c116c37fd8bb02/swig/python/gdal-utils/osgeo_utils/gdal2tiles.py#L3299

Will not be closed if an exceptio occurs before 
https://github.com/OSGeo/gdal/blob/95c9d336b2db0c5d240f191638c116c37fd8bb02/swig/python/gdal-utils/osgeo_utils/gdal2tiles.py#L3337

should add `try/finally`.

Somthing like:
```
    if pool is not None:
        ...
        created_pool = False
    else:
        ...
        pool = Pool(processes=nb_processes)
        created_pool = True
    try:
        ...
    finally:
        if created_pool:
            pool.terminate()
```

**Comment by rouault** [comment]
can you submit a pull request for that ?

**Comment by zeevdr** [comment]
@[rouault](https://github.com/rouault) will do, once I have the time

**Comment by jcphill** [comment]
Sure, although I'll probably refactor to use a with statement rather than try/finally/terminate/close/join.

**Comment by jcphill** [comment]
@zeevdr I'd appreciate your comments on https://github.com/OSGeo/gdal/pull/5675
