### ISSUE TITLE
Feature request: Option for PROJ

### ISSUE THREAD

**Issue by OgreTransporter** [OSGeo/gdal#5595]
I suggest to add an additional option `PROJ_LIB` to the list of options (https://gdal.org/user/configoptions.html). The value should then be passed to the function `proj_context_set_search_paths` (https://proj.org/development/reference/functions.html#c.proj_context_set_search_paths). So GDAL can be used then namely also without environment variables.

`PROJ_LIB` is the location of PROJ resource files. Starting with PROJ 6, multiple directories can be specified. On Unix, they should be separated by the colon (:) character. on Windows, by the semi-colon (;) character. PROJ is hardcoded to look for resource files in other locations as well, amongst those are the installation directory (usually share/proj under the PROJ installation root) and the current folder. You can also set the location of the resource files using `proj_context_set_search_paths()` in the proj.h API header.

**Comment by rouault** [comment]
This is already implemented. See OSRSetPROJSearchPaths : https://gdal.org/doxygen/ogr__srs__api_8h.html#a610f585565b2f84e14bbb4655ffe2b39
