### ISSUE TITLE
Missing python bindings for CPLGetConfigOptions and CPLSetConfigOptions

### ISSUE THREAD

**Issue by theroggy** [OSGeo/gdal#5596]
To be able to set and cleanup config options correctly the functions [CPLGetConfigOptions](https://gdal.org/api/cpl.html#_CPPv419CPLGetConfigOptionsv) and [CPLSetConfigOptions](https://gdal.org/api/cpl.html#_CPPv418CPLSetConfigOptionPKcPKc) are the logical functions to use, but they are not exposed in the python API.

Especially [CPLGetConfigOptions](https://gdal.org/api/cpl.html#_CPPv419CPLGetConfigOptionsv) seems important as it is the only clean way to get the config options that are not set as environment variables, because `GetConfigOption` will also look in the environment variables if an option is not found in the "local" config options.

For my personal use case this isn't relevant, but the same applies to [CPLGetThreadLocalConfigOptions](https://gdal.org/api/cpl.html#_CPPv430CPLGetThreadLocalConfigOptionsv) and [CPLSetThreadLocalConfigOptions](https://gdal.org/api/cpl.html#_CPPv430CPLSetThreadLocalConfigOptionsPPCKc).

I don't have any experiency in writing python bindings or in the gdal codebase in general... so I hope there is someone willing to implement it that does have the experience.

A clean way to set temporary config options would be via a context manager that does the setting and cleanup transparantly. I implemented one at the moment without having `GetConfigOptions` and `SetConfigOptions` but added "TODO" comments where changes would be applicable when support would be added. With some extra (dirty) code it could do a better job in trying to emulate having the `GetConfigOptions` information available, but hopefully the bindings can be added instead.

### Possible implementation of a context manager
```
from osgeo import gdal

class set_config_options(object):
    """
    Context manager to set temporary config options. 

    Args:
        config_options (dict): dict with config options to set.
            `Eg. { "OGR_SQLITE_CACHE", "128" }`
    """
    def __init__(self, config_options: dict):
        self.config_options = config_options
    def __enter__(self):
        # TODO: uncomment if GetConfigOptions() is supported
        #self.config_options_backup = gdal.GetConfigOptions()
        for name, value in self.config_options.items():
            gdal.SetConfigOption(name, value)
    def __exit__(self, type, value, traceback):
        # Remove config options that were set
        # TODO: delete loop + uncomment if SetConfigOptions() is supported
        for name, value in self.config_options.items():
            gdal.SetConfigOption(name, None)
        #gdal.SetConfigOptions(self.config_options_backup)  
```

### A test for the context manager
```
import os

from osgeo import gdal

def test_set_config_options():
    # Init
    test1_config_notset = "TEST_CONFIG_OPTION_1"
    test2_config_alreadyset = "TEST_CONFIG_OPTION_2"
    test3_config_envset = "TEST_CONFIG_OPTION_3"
    assert gdal.GetConfigOption(test1_config_notset) is None
    assert gdal.GetConfigOption(test2_config_alreadyset) is None
    gdal.SetConfigOption(test2_config_alreadyset, "test2_original_value")
    assert test3_config_envset not in os.environ
    os.environ[test3_config_envset] = "test3_original_env_value"
    
    # Set config options with context manager
    with _ogr_util.set_config_options(
            {   test1_config_notset: "test1_context_value",
                test2_config_alreadyset: "test2_context_value",
                test3_config_envset: "test3_context_value", } ):
        assert gdal.GetConfigOption(test1_config_notset) == "test1_context_value"
        assert gdal.GetConfigOption(test2_config_alreadyset) == "test2_context_value"
        assert gdal.GetConfigOption(test3_config_envset) == "test3_context_value"

    # The options set with context manager should be gone
    assert gdal.GetConfigOption(test1_config_notset) is None
    # TODO: delete next line + uncomment 2nd if GetConfigOptions is supported
    assert gdal.GetConfigOption(test2_config_alreadyset) is None
    #assert gdal.GetConfigOption(test2_config_alreadyset) == "test2_original_value"
    assert gdal.GetConfigOption(test3_config_envset) == "test3_original_env_value"

    # If option via env is changed, it changes here as well
    os.environ[test3_config_envset] = "test3_new_env_value"
    assert gdal.GetConfigOption(test3_config_envset) == "test3_new_env_value"
```

**Comment by dbaston** [comment]
I _think_ this is covered by the `gdal.config_options` context manager and the addition of `gdal.GetConfigOptions` in https://github.com/OSGeo/gdal/pull/8066. If I'm missing something, please feel free to re-open.
