### ISSUE TITLE
Bug to read TerraSAR-X Complex SAR Data Product

### ISSUE THREAD

**Issue by ES20180816** [OSGeo/gdal#5622]
Hello everyone,

I have tried to use GDAL to read TerraSAR-X Complex SAR Data Product, which can be opened successfully.

But, the last column in every row is always 0, which is incorrect.

When reading other data typres, which is no problem.

GDAL version: 3.4.1

**Comment by rouault** [comment]
Can you point to such dataset ?

**Comment by ES20180816** [comment]
Dear rouault,

Do you mean the type of the dataset?

The dataset  was downloaded from the DLR website, which should be an annotated binary matrix.

Except for the last colunm,  the rest of the data is normal.

**Comment by rouault** [comment]
> Do you mean the type of the dataset?

no, a concrete link to where to download a dataset. I'm not familiar with the DLR website.

**Comment by ES20180816** [comment]
Unfortunately, this data cannot be downloaded  publicly. 

If you could give me an email address or ohter contact method, I can share a test data with you.

Thanks a lot.
