### ISSUE TITLE
GDAL_rasterize - 3d support for flat polygon rasterization

### ISSUE THREAD

**Issue by sbilbault** [OSGeo/gdal#563]
Reading gdal_documentation, I understood 3d polygon are not supported currently by gdal_rasterize, which is limited to lines and points for the -3d option.

How could I rasterize such 3d polygons ? Would it be possible to extend GDAL_rasterize features to include flat 3D polygons in the -3d option ?

**Comment by sbilbault** [comment]
The flat polygons I was mentionning where not necessarily horizontal, so Z values may differ along the vertices. A simple linear interpolation between points would work are they are flat. Is this feature supported, similarly to a linear interpolation between lines points which is currently mentionnned ?

**Comment by esgn** [comment]
Would also be interested in this feature :)
