### ISSUE TITLE
Support linking with GEOS through CMake

### ISSUE THREAD

**Issue by mmomtchev** [OSGeo/gdal#5655]
## Expected behavior and actual behavior.

Currently `FindGEOS.cmake` always uses `geos-config` to find GEOS. Contrast this with PROJ which can use the included cmake config:
https://github.com/OSGeo/gdal/blob/b3784fc2c4fec13d51c5d088dc9aea9f506261b9/cmake/helpers/CheckDependentLibraries.cmake#L329

## Steps to reproduce the problem.

Fully Integrated self-contained build with
```
add_subdirectory(deps/proj)
add_subdirectory(deps/geos)
add_subdirectory(deps/gdal)
```

## Operating system

Ubuntu 20.04 64 bit

## GDAL version and provenance

GDAL 3.5.0-git

**Comment by dg0yt** [comment]
It already checks for GEOS cmake config, matching name `GEOS` and providing target `GEOS::geos_c`. So it doesn't have to use the find module / `geos-config`

https://github.com/OSGeo/gdal/blob/b3784fc2c4fec13d51c5d088dc9aea9f506261b9/cmake/helpers/CheckDependentLibraries.cmake#L574-L577

**Comment by mmomtchev** [comment]
This is a GEOS problem solved in https://github.com/libgeos/geos/pull/518
