### ISSUE TITLE
gdalbuildvrt fails using wildcards

### ISSUE THREAD

**Issue by Langlaeufer** [OSGeo/gdal#568]
## Expected behavior and actual behavior.

gdalbuildvrt fails handling wildcards * under windows 10 1803
it was working before windows update
testet on 2 computers
results now:
computer 1: program is running without any messages, no result is produced
computer 2. error message of missing file, vrt is built but first file of each folder is missing. 
It thows a error message for each folder the one file is not found.
the filename of the not found file is the first character of the file name missed file.

## Steps to reproduce the problem.
gdalbuildvrt dest.vrt folder/*.tif

## Operating system
Windows 10 April update (1803)

## GDAL version and provenance
comming with qgis 3.0.1/2

**Comment by jratike80** [comment]
Ok to close as invalid then?

**Comment by aklink** [comment]
Has anyone reported this bug to the **QGIS development** team? Because even it is no issue in current GDAL build, the same issue occurs in QGIS 2.18.21 and QGIS 3.2.0 both using GDAL 2.2.4, released 2018/03/19. Both QGIS versions were released after this issue was closed here.

**Comment by Langlaeufer** [comment]
@aklink: at the first time it was the same for me: only the first file was was missing. later it does not work at all.  I reopen the bug, because the working verions from GIS Internals is 2.03 an we are here now at 2.24.

**Comment by aklink** [comment]
@Langlaeufer 
I have tested **GDAL 2.3.0** (released 2018/05/04) from **GISInternals**. It works **without issue** using Win10 (1803). 
In OsGeo4W GDAL 2.3.0 is not available yet - latest is **GDAL 2.2.4** (released 2018/03/19) showing the issue. The GIS Internals version is definitelly newer than the Version in OSGeo4W. 
Unfortunatelly Version 2.2.4 was skipped in GIS Internals (previous was 2.2.3) so I can not double-check using 2.2.4 from GIS Internals. 
I have not testet version 2.2.3 with Win 10 (1803) yet - it is available both from GIS Internals and OSGEO4W.

**Comment by aklink** [comment]
Issue was [fixed](https://trac.osgeo.org/osgeo4w/ticket/574) in OSGeo4W build in **GDAL 2.2.4-2** (available via OSGeo4W installer). Hopefully it will be in next QGIS release.

**Comment by aklink** [comment]
@Langlaeufer can be closed here

**Comment by jef-n** [comment]
@aklink  All involved maintainers are already aware of this - I'm shaving them all ;)
