### ISSUE TITLE
Remove autoconf & nmake build systems

### ISSUE THREAD

**Issue by rouault** [OSGeo/gdal#5680]
- [x] Migrate CI (.github, appveyor.yml, .travis.yml) to CMake builds:
    * [x] Travis CI s390x and graviton2: https://github.com/OSGeo/gdal/pull/6040
    * [x]  mingw_w64: https://github.com/OSGeo/gdal/pull/6048
    * [x]  fedora: https://github.com/OSGeo/gdal/pull/6053
    * [x]  asan: https://github.com/OSGeo/gdal/pull/6055
    * [x] windows: https://github.com/OSGeo/gdal/pull/6056 
    * [x] code_checks: https://github.com/OSGeo/gdal/pull/6057
    * [x] ubuntu_2004: https://github.com/OSGeo/gdal/pull/6058
    * [x] ubuntu_1804 and ubuntu_1804_32bit: https://github.com/OSGeo/gdal/pull/6101
    * [x] macos:  https://github.com/OSGeo/gdal/pull/6108
    * [x] clang static analyzer: https://github.com/OSGeo/gdal/pull/6107 
    * [x]  Remove .github/workflows/android.yml: android_cmake.yml already exists: https://github.com/OSGeo/gdal/commit/678a428cac4dfcf8690ed27923e1834bc3b55661
    * [x] Remove appveyor.yml: https://github.com/OSGeo/gdal/commit/265f3e8db7057d59356331ffb0a67bd176bc5c02 
- [x] Migrate OSSFuzz fuzzers/build.sh to CMake builds: https://github.com/OSGeo/gdal/pull/6038
- [ ] Remove configure.ac, m4, GDALmake.opt.in, nmake.opt, all GNUmakefile & makefile.vc files, generate_vcxproj.bat: https://github.com/OSGeo/gdal/pull/6110
- [x] Adapt release process / mkgdaldist.sh: https://github.com/OSGeo/gdal/pull/6039
- [x] swig/python/CMakeLists.txt: apply all customizations from GNUmakefile: https://github.com/OSGeo/gdal/pull/6100

**Comment by rouault** [comment]
> The `generate_vcxproj.bat` file in the repo root is `nmake`-based and will need to be updated.

--> to be removed actually

**Comment by atlight** [comment]
> > to be removed actually
> 
> @atlight why sad face ? The CMake visual studio generator should do an equivalent job, or am I missing something ?

Ah, if an alternative option is available that is ok. I am not familiar with CMake at all so I was scared of losing access to such a resource.
