### ISSUE TITLE
NUMFOCUS

### ISSUE THREAD

**Issue by houmanmaleki** [OSGeo/gdal#5703]
Open Code = Better Science

**Comment by rouault** [comment]
what's the purpose of this ticket ? I assume this can be closed

**Comment by houmanmaleki** [comment]
Hi,

With my current Email ID, I think that it comes to an Issue where needs to
be fixed. I will let you know if necessary. This was not intented to create
any further ticket. Thanks,

NO SIGNATURE REQUIRED
IMPORTANT - RETAIN COPY FOR YOUR RECORDS

Regards,

Houman Maleki- 208
