### ISSUE TITLE
Registration of Goldensoftware grids out by half a pixel?

### ISSUE THREAD

**Issue by geokimbo** [OSGeo/gdal#5705]
I am not sure if this is a gdal issue or in the way that QGis is using gdal but I'll start here.

Golden Software define their origin (MINX and MINY) as the south west (lower left) corner of the south west (lower left) most pixel. When displayed in QGis the grids are projecting as if the origin is in the centre of the pixel.

The max/min limits written to the grid header are the limits of the grid not the limits of the grid less one pixel. i.e for a single pixel grid MAXX= MINX +  pixel width and NROW=NCOL=1. NOT MINX=MAXX as a centre pixel registration would require. 
 
ERMapper defaults to a centre pixel origin of the north west (upper left) pixel - unless the user redefines the origin in the ERS file using registrationcellx/y or origincellx/y.

I have a routine which converts between ERMapper and Goldensoft grids which I wrote ~30 years ago and have applied it to thousands of grids which have been shared with others, since then. i.e the transform has been tested by many others.

Knowing that ERMapper defaults to a centre reference I offset the origin written to the Goldensoft grids by half a pixel on conversion. After conversion both grids should overlap when loaded into QGis - they do not - there is a half pixel offset.

QGis is currently using gdal 3.0.4 which agrees with the output of  gdalinfo --version
I'm currently using QGis 3.24.2 on an Ubuntu 20.4 host  but this has been an issue for many years - back to QGis 2.7 and Ubuntu 16

The acid test is to bring a Goldensoft grid into Goldensoftware's Surfer (free trial version - windows only) and zoom in and digitise the co-ords of the south west of the image. Do the same in QGis and you will find a half pixel difference.

Cheers
Kim

**Comment by jratike80** [comment]
By looking at the source code https://github.com/OSGeo/gdal/blob/master/frmts/gsg/gsbgdataset.cpp I think that it tries to take the half pixel shifts into account

```
/* calculate pixel size first */
    padfGeoTransform[1] = (poGRB->dfMaxX - poGRB->dfMinX)/(nRasterXSize - 1);
    padfGeoTransform[5] = (poGRB->dfMinY - poGRB->dfMaxY)/(nRasterYSize - 1);

    /* then calculate image origin */
    padfGeoTransform[0] = poGRB->dfMinX - padfGeoTransform[1] / 2;
    padfGeoTransform[3] = poGRB->dfMaxY - padfGeoTransform[5] / 2;
```

Could it be that your own routine is making one half pixel shift and GDAL is making another one, and for preventing that to happen you should not apply your own but trust on GDAL?

**Comment by jratike80** [comment]
The file format if defined in https://grapherhelp.goldensoftware.com/subsys/ascii_grid_file_format.htm

**Comment by jratike80** [comment]
For me it seems that Surfer does not render outside the data limits, or rather if clips the rendered image by the data extent. See the image with labels at the data points (the labels of the bottom line are not visible) 

<img width="431" alt="image" src="https://user-images.githubusercontent.com/1751612/167875451-a507acbe-2b45-4bc6-a1d1-528ba1e75346.png">

**Comment by rouault** [comment]
This is probably just a matter of convention. Surfer must use a pixel-is-point convention, whereas GDAL always expose a pixel-is-area raster, and thus adds a half-pixel shift so that the centre of the pixel matches the registration of the surfer grid.
I don't believe there's any bug here. Usual issue.

**Comment by geokimbo** [comment]
@jratike80 

Thanks on two counts. I'd forgotten that Y pixel size was negative so subtracting it from MaxY now makes sense. The pixel-is-point and pixel-is-area notation may be a standard syntax but having not come across it before I found it confusing.  Your picture helped greatly. I guess I'd prefer to think of surfer as writing nodes of a regular mesh and interpolating between them whereas gdal is writing pixels which each have a constant value. Put another way, it is the difference between representing scientific data and representing a picture or the difference between point data and cell data in the vtk/Paraview syntax. So Surfer clips to nodes while gdal clips to pixels. As long as we deal with the registration issues correctly then the difference will disappear once we start to process the data. Thanks.

@rouault 
I agree.

Cheers
Kim
