### ISSUE TITLE
Docker: ubuntu-full-gdal-3.4.3 missing libproj.so

### ISSUE THREAD

**Issue by snowman2** [OSGeo/gdal#5717]
## Expected behavior and actual behavior.
I was expecting the `pyproj` installation to work. However, it failed.

Current contents (`ls -l /usr/local/lib/`):
```
total 4068
drwxr-xr-x 4 root root     4096 May  4 12:00 cmake
lrwxrwxrwx 1 root root       27 May  4 12:00 libinternalproj.so -> libinternalproj.so.25.9.0.0
lrwxrwxrwx 1 root root       27 May  4 12:00 libinternalproj.so.25 -> libinternalproj.so.25.9.0.0
-rw-r--r-- 1 root root  4153096 May  4 12:00 libinternalproj.so.25.9.0.0
lrwxrwxrwx 1 root root       27 May  4 12:00 libproj.so.25 -> libinternalproj.so.25.9.0.0
drwxr-xr-x 2 root root     4096 May  4 12:00 pkgconfig
drwxrwsr-x 3 root staff    4096 May  4 16:02 python3.8
```

## Steps to reproduce the problem
```
docker run -it osgeo/gdal:ubuntu-full-3.4.3 /bin/bash
apt-get update
apt-get install -y python3-venv python3-dev g++
python3 -m venv venv
. venv/bin/activate
PIP_NO_BINARY=pyproj python -m pip install pyproj
```
Error:
```
/usr/bin/ld: cannot find -lproj
```
Hack to fix:
```
ln -s /usr/local/lib/libinternalproj.so /usr/local/lib/libproj.so
```
What would be the best way to address this?

**Comment by rouault** [comment]
The proj build in /usr/local/lib is intended to be private to the GDAL build.
So either do your hack or add the proj-dev package to get the system PROJ

**Comment by snowman2** [comment]
> The proj build in /usr/local/lib is intended to be private to the GDAL build.
> So either do your hack or add the proj-dev package to get the system PROJ

Would you prefer that I don't add a MR to add to `docker/ubuntu-full/bh-proj.sh`?
```
ln -s "libinternalproj.so.${PROJ_SO}" "${DESTDIR}${PROJ_INSTALL_PREFIX}/lib/libproj.so"
```

**Comment by snowman2** [comment]
This line makes me think not:
```
rm "${DESTDIR}${PROJ_INSTALL_PREFIX}/lib"/libproj.*
```

**Comment by snowman2** [comment]
Thanks for the clarification @rouault :+1:

**Comment by snowman2** [comment]
I am seeing `undefined symbol: proj_context_set_enable_network`. Is this related?
https://github.com/OSGeo/gdal/blob/e88d4e82cb1e141e0c96942c386bd6f7af162d8d/docker/ubuntu-full/bh-proj.sh#L34-L35

**Comment by rouault** [comment]
> Is this related?

yes, you'll need to set those defines to use the internal proj

**Comment by snowman2** [comment]
> yes, you'll need to set those defines to use the internal proj

It is clear that you wanted to discourage the use of the PROJ compiled with GDAL. What was the motivation? Was it to prevent conflicts in the scenario that the system PROJ was installed?

**Comment by rouault** [comment]
> Was it to prevent conflicts in the scenario that the system PROJ was installed?

yes. And one such conflict is that the GDAL build uses the libspatialite-dev package which depends on system PROJ. That's a bit the issue with those Docker images: they provide recent versions of GDAL & PROJ but by skipping the 'clean' packaging process.

**Comment by snowman2** [comment]
That makes sense. I understand why you would likely not want to get into the business of managing the builds of all these dependencies yourself. It would be nice to have a docker image with all of GDAL's dependencies (without GDAL) for downstream applications to build & test against the latest GDAL (https://github.com/rasterio/rasterio/issues/2456). Maybe if something like that were done using a 'clean' build method, it would alleviate the troubles mentioned in this issue as well as the GDAL docker image could be built against the same base docker image.
