### ISSUE TITLE
[3.5.0] [CMake] no more explicit file versioning

### ISSUE THREAD

**Issue by chacha21** [OSGeo/gdal#5723]
I am happy to report that the CMake system in 3.5.0 works flawlessly with
Windows+Visual Studio+dependencies to proj/libtiff/libgeotiff/cfitsio/sqlite

I have just noticed that instead of gdal_305[d].dll, the build will now produce gdal[d].dll
Is it expected behaviour ?

**Comment by rouault** [comment]
> Is it expected behaviour ?

maybe... At least this is the standard behaviour of CMake and I don't see a strong reason to strictly replicate what the nmake builds did. I presume users can tune CMake options to change the DLL name if needed (see somewhat related discussion in https://github.com/OSGeo/gdal/pull/5701)

**Comment by chacha21** [comment]
:+1:
