### ISSUE TITLE
osgeo/ogr.py refers to OGRError which does not exist

### ISSUE THREAD

**Issue by tzickel** [OSGeo/gdal#574]
https://github.com/OSGeo/gdal/blob/5599ef04316c9b148ac6832400c7feeee5012de6/gdal/swig/python/osgeo/ogr.py#L1191

Topic

@bje-

**Comment by rouault** [comment]
Oh indeed. I thought that was related to the suppression of the bare exceptions. Apparently nobody has ever hit that code !
