### ISSUE TITLE
OpenFileGDB The layer coordinate system in the dataset does not change with the dataset

### ISSUE THREAD

**Issue by Hsxxxxxx** [OSGeo/gdal#5747]
When a layer is created in a gdb dataset, the layer will obtain the coordinate system of the dataset by default,
After modifying the coordinate system of the dataset, 
OpenFileGDB still reads the old coordinate system (wrong),
FileGDB will read the normal coordinate system

## Steps to reproduce the problem.
Python3.7 + GDAL:3.4.2
`
 
    # Test
    file = "./test.gdb"
    openfilegdb_driver = ogr.GetDriverByName("OpenFileGDB")
    filegdb_driver = ogr.GetDriverByName("FileGDB")
    openfilegdb_ds = openfilegdb_driver.Open(file, 0)
    filegdb_ds = filegdb_driver.Open(file, 0)

    print("="*30)
    for layer in openfilegdb_ds:
        print(layer.GetName())
        print(layer.GetSpatialRef())

    print("="*30)
    for layer in filegdb_ds:
        print(layer.GetName())
        print(layer.GetSpatialRef())
`
# result print
test_layer
GEOGCS["China Geodetic Coordinate System 2000",
    DATUM["China_2000",
        SPHEROID["CGCS2000",6378137,298.257222101,
            AUTHORITY["EPSG","1024"]],
        AUTHORITY["EPSG","1043"]],
    PRIMEM["Greenwich",0,
        AUTHORITY["EPSG","8901"]],
    UNIT["degree",0.0174532925199433,
        AUTHORITY["EPSG","9122"]],
    AXIS["Latitude",NORTH],
    AXIS["Longitude",EAST],
    AUTHORITY["EPSG","4490"]]
test_layer
GEOGCS["WGS 84",
    DATUM["WGS_1984",
        SPHEROID["WGS 84",6378137,298.257223563,
            AUTHORITY["EPSG","7030"]],
        AUTHORITY["EPSG","6326"]],
    PRIMEM["Greenwich",0,
        AUTHORITY["EPSG","8901"]],
    UNIT["degree",0.0174532925199433,
        AUTHORITY["EPSG","9122"]],
    AXIS["Latitude",NORTH],
    AXIS["Longitude",EAST],
    AUTHORITY["EPSG","4326"]]

## Operating system

Ubuntu 20 

## GDAL version and provenance

GDAL: 3.4.2

**Comment by rouault** [comment]
@Hsxxxxxx 

> When a layer is created in a gdb dataset, the layer will obtain the coordinate system of the dataset by default,
After modifying the coordinate system of the dataset,

- are you speaking about a feature dataset ?
- with which tool do you modify the coordinate system ?
- please attach a zip file with a dataset that can be used to reproduce the issue

**Comment by Hsxxxxxx** [comment]
Yes, I use a 2D Polygon Feature layer.

the data in this question was created and modified with ArcMap 10.1.

(url
[test.zip](https://github.com/OSGeo/gdal/files/8714974/test.zip)
)
