### ISSUE TITLE
Transforming using ntv2 nadgrids is behaving different between GDAL 2.3.1 and GDAL 3.4.2

### ISSUE THREAD

**Issue by csmemoe-aquaveo** [OSGeo/gdal#5749]
## Expected behavior and actual behavior

If I specify a nadgrid using a PROJ.4 string when using the gdaltransform commandline executable I would expect the transformation to succeed if all the parameters are correct.  This worked in past versions of the software.  In GDAL 3.4.2 (and likely more recent versions), I get an error that the transformation fails. Similar issues occur if I try to transform using the updated python or c++ libraries.

I am using the beta2007.gsb ntv2 grid file which can be downloaded [here](http://crs.bkg.bund.de/crseu/crs/descrtrans/BeTA/de_dhdn2etrs_beta.php).

## Steps to reproduce the problem

The following gdaltransform command fails (I turned on PROJ_DEBUG=3 and included only the output after entering the coordinates):

```
gdaltransform --version
GDAL 3.4.2, released 2022/03/08

gdaltransform --debug ON -s_srs EPSG:3044 -t_srs "+proj=tmerc +lat_0=0 +lon_0=12 +k=1 +x_0=4500000 +ellps=bessel +nadgrids=C:\temp\BETA2007.gsb +units=m +no_defs"
Enter X Y [Z [T]] values separated by space, and press Return.
4547442.8444401 5290333.4162611
PROJ: Using coordinate operation Inverse of UTM zone 32N + Ballpark geographic offset from ETRS89 to WGS 84 + Inverse of unknown to WGS84 + unknown
PROJ: pj_open_lib(C:\temp\BETA2007.gsb): call fopen(C:\temp\BETA2007.gsb) - succeeded
PROJ_TRACE: NTv2 DHDN90   62x84: LL=(5.5,47) UR=(15.6666667,55.3)
OGRCT: Invalid argument
transformation failed.

```
However, if I do the same command using gdaltransform in GDAL 2.3.1 with the same coordinates, I get a successful transformation:

```
gdaltransform --version
GDAL 2.3.1, released 2018/06/22

gdaltransform --debug ON -s_srs EPSG:3044 -t_srs "+proj=tmerc +lat_0=0 +lon_0=12 +k=1 +x_0=4500000 +ellps=bessel +nadgrids=C:\temp\BETA2007.gsb +units=m +no_defs"
OGRCT: PROJ >= 4.8.0 features enabled
OGRCT: Source: +proj=utm +zone=32 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs
OGRCT: Target: +proj=tmerc +lat_0=0 +lon_0=12 +k=1 +x_0=4500000 +y_0=0 +ellps=bessel +nadgrids=C:\\temp\\BETA2007.gsb +units=m +no_defs
OGRCT: Source: +proj=tmerc +lat_0=0 +lon_0=12 +k=1 +x_0=4500000 +y_0=0 +ellps=bessel +nadgrids=C:\\temp\\BETA2007.gsb +units=m +no_defs
OGRCT: Target: +proj=utm +zone=32 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs
4547442.8444401 5290333.4162611
8171986.89299032 5104179.28005939 -3.96016985177994e-05

```

I have tried various things to get the transformation with the nadgrid to work, including using a wkt string with the nadgrid included. I am able to convert the coordinates from EPSG 3044 to EPSG 5678, but the coordinates are way off from where they should be. Perhaps there is a way to define this BETA2007.gsb nadgrid that works correctly using the gdal commandline utilities, the python function calls, or the c++ function calls so I can correctly convert these coordinates.  If there is, I have not been able to locate any documentation on this.

## Operating system

Windows 10 64 bit

Edition	Windows 10 Pro
Version	21H2
Installed on	‎7/‎26/‎2021
OS build	19044.1645
Experience	Windows Feature Experience Pack 120.2212.4170.0

## GDAL version and provenance

GDAL 3.4.2 MSVC 2019 x64 from [gisinternals.com](https://www.gisinternals.com/)

**Comment by jratike80** [comment]
With recent Proj versions that recent GDAL is using I think you can just use the EPSG codes. The grid shift file is in TIFF format and it is available in the Proj repository. My GDAL/Proj installation seems to have it and wants to use it by default.

```
projinfo -s epsg:3044 -t EPSG:5678
Candidate operations found: 2
Note: using '--spatial-test intersects' would bring more results (5)
-------------------------------------
Operation No. 1:

unknown id, Inverse of UTM zone 32N + Inverse of DHDN to ETRS89 (8) + 3-degree Gauss-Kruger zone 4, 0.9 m, Germany - onshore - states of Baden-Wurtemberg, Bayern, Berlin, Brandenburg, Bremen, Hamburg, Hessen, Mecklenburg-Vorpommern, Niedersachsen, Nordrhein-Westfalen, Rheinland-Pfalz, Saarland, Sachsen, Sachsen-Anhalt, Schleswig-Holstein, Thuringen.

PROJ string:
+proj=pipeline
  +step +proj=axisswap +order=2,1
  +step +inv +proj=utm +zone=32 +ellps=GRS80
  +step +inv +proj=hgridshift +grids=de_adv_BETA2007.tif
  +step +proj=tmerc +lat_0=0 +lon_0=12 +k=1 +x_0=4500000 +y_0=0 +ellps=bessel
  ...
```

**Comment by rouault** [comment]
The coordinates 4547442.8444401 5290333.4162611 in EPSG:3044 correspond to a latitude of 37.7 deg and longitude of 54.2 . This doesn't fall in Germany for which the BETA2007 grid is valid.

If I use a point in Germany, then things work:
```
$ echo 10 50 | gdaltransform -s_srs EPSG:4326 -t_srs EPSG:3044
571666.447504128 5539109.81517567 0

$ echo 571666.447504128 5539109.81517567 0 | gdaltransform  -s_srs EPSG:3044 -t_srs "+proj=tmerc +lat_0=0 +lon_0=12 +k=1 +x_0=4500000 +ellps=bessel +nadgrids=BETA2007.gsb +units=m +no_defs"
4356719.60516803 5542321.55008064 0
```

If you want the grid to be ignored when a point doesn't fall into it, then you can add ,@null at the end of the nadgrids value
```
$ echo 4547442.8444401 5290333.4162611 | gdaltransform -s_srs EPSG:3044 -t_srs "+proj=tmerc +lat_0=0 +lon_0=12 +k=1 +x_0=4500000 +ellps=bessel +nadgrids=BETA2007.gsb,@null +units=m +no_defs"
8276390.34855434 5132236.65966789 0
```

The difference in results is due to PROJ 5.2 or later using an "exact" Transverse Mercator implementation for points far from the Central Meridian

If you want to replicate (almost) the same result as the old GDAL/PROJ you need the set the OSR_USE_APPROX_TMERC configuration option to YES
```
$ echo 4547442.8444401 5290333.4162611 | gdaltransform -s_srs EPSG:3044 -t_srs "+proj=tmerc +lat_0=0 +lon_0=12 +k=1 +x_0=4500000 +ellps=bessel +nadgrids=BETA2007.gsb,@null +units=m +no_defs" --config OSR_USE_APPROX_TMERC YES
8171982.39362058 5104187.61751904 0
```

**Comment by csmemoe-aquaveo** [comment]
Wow, that really helps! I should have recognized that the point I was testing was outside the grid's domain. Thank you!
