### ISSUE TITLE
Docker: ubuntu-full-3.5.0 -> libparquet.so.800: No such file or directory

### ISSUE THREAD

**Issue by snowman2** [OSGeo/gdal#5750]
https://github.com/rasterio/rasterio/runs/6492154156

Note that it works without issue for previous GDAL versions.

## Expected behavior and actual behavior.

This error shouldn't happen:
```
ImportError: libparquet.so.800: cannot open shared object file: No such file or directory
```

## Steps to reproduce the problem.

```
git clone https://github.com/rasterio/rasterio
cd rasterio
GDAL=ubuntu-full-3.5.0 make dockertest
```

## Operating system

Ubuntu 20.04 64 bit

## GDAL version and provenance

3.5.0

**Comment by snowman2** [comment]
Should these be 800?

**Comment by rouault** [comment]
ah, arrow-cpp has been updated just a few days before I built the image... Have to update that...

**Comment by snowman2** [comment]
Thanks 👍

**Comment by cjauvin** [comment]
While trying to build `ubuntu-full-3.5.1`, I had to do `800 -> 900` to make it work.
