### ISSUE TITLE
Mailing list broke?

### ISSUE THREAD

**Issue by alturic** [OSGeo/gdal#5757]
I've been sending mail to gdal-dev@lists.osgeo.org the past 3 days, but it doesn't seem like the list is reflecting the email. I've tried subscribing as well and still haven't received any email confirmation of the subscription (nor the daily digest) either?

**Comment by rouault** [comment]
To be able to subscribe, you absolutely need to click on the link that is sent in the confirmation email ... that you didn't receive. Some email providers apparently do not like emails sent by the osgeo mailing list. 
You can file an issue to the OSGeo system administration committee at https://trac.osgeo.org/osgeo/newticket about your issue, with some details (your email, your email provider, etc). You'll need a OSGeo id first to file a ticket there: https://id.osgeo.org/ldap/create
