### ISSUE TITLE
FileGDB launders field names with foreign characters even when -lco LAUNDER_RESERVED_KEYWORDS=FALSE

### ISSUE THREAD

**Issue by adamgutons** [OSGeo/gdal#5792]
## Expected behavior and actual behavior.

Using the Esri FileGDB API, I expected to be able to create a file .gdb layer with field names containing accented characters (é, á, etc.) when using  -lco LAUNDER_RESERVED_KEYWORDS=FALSE.  However the field and layer names are laundered regardless.  See below

        Creating Feature Class: **inspection_de_sécurité**
        Warning 6: dataset C:\code\export-service\client\lvutildev\template.gdb does not support layer creation option LAUNDER
        Warning 6: Normalized/laundered layer name: **'inspection_de_sécurité' to 'inspection_de_s__curit__'**
        Warning 6: Normalized/laundered field name: 'Contrôle_de_la_trafic_approprié' to 'Contr__le_de_la_trafic_appropri__'
        Warning 6: Normalized/laundered field name: 'Sélectionnez_les_éléments_insat' to 'S__lectionnez_les___l__ments_insat'
        Warning 6: Normalized/laundered field name: 'léments_ne_figurant_pas_dans_la' to 'l__ments_ne_figurant_pas_dans_la'
        Warning 6: Normalized/laundered field name: 'Trois_hommes_déquipage_présents' to 'Trois_hommes_d__quipage_pr__sents'
        Warning 6: Normalized/laundered field name: 'Tous_les_membres_de_léquipage_u' to 'Tous_les_membres_de_l__quipage_u'
        Warning 6: Normalized/laundered field name: 'Sélectionner_les_éléments_dEPI_' to 'S__lectionner_les___l__ments_dEPI_'
        Warning 6: Normalized/laundered field name: 'Briefing_pré_job_réalisé' to 'Briefing_pr___job_r__alis__'
        Warning 6: Normalized/laundered field name: 'Ménage_approprié_sur_place' to 'M__nage_appropri___sur_place'
        Warning 6: Normalized/laundered field name: 'Matériaux_vérifiés' to 'Mat__riaux_v__rifi__s'
        Warning 6: Normalized/laundered field name: 'Détecteurs_de_gaz_de_CO_et_doxy' to 'D__tecteurs_de_gaz_de_CO_et_doxy'
        Warning 6: Normalized/laundered field name: 'léments_de_détecteur_insatisfai' to 'l__ments_de_d__tecteur_insatisfai'
        Warning 6: Normalized/laundered field name: 'Entrez_les_éléments_de_détecteu' to 'Entrez_les___l__ments_de_d__tecteu'
        Warning 6: Normalized/laundered field name: 'Camion_équipé_dun_équipement_da' to 'Camion___quip___dun___quipement_da'
        Warning 6: Normalized/laundered field name: 'Bouteille_à_feu_adéquate' to 'Bouteille____feu_ad__quate'
        Warning 6: Normalized/laundered field name: 'Sélectionnez_les_articles_de_bo' to 'S__lectionnez_les_articles_de_bo'
        Warning 6: Normalized/laundered field name: 'Entrez_les_éléments_insatisfais' to 'Entrez_les___l__ments_insatisfais'
        Warning 6: Normalized/laundered field name: 'Lacunes_identifiées' to 'Lacunes_identifi__es'
        Warning 6: Normalized/laundered field name: 'Sélectionner_les_actions_effect' to 'S__lectionner_les_actions_effect'
        Warning 6: Normalized/laundered field name: 'Entrez_les_étapes_de_correction' to 'Entrez_les___tapes_de_correction'
        Warning 6: Normalized/laundered field name: 'Des_conditions_météorologiques_' to 'Des_conditions_m__t__orologiques_'
        Warning 6: Normalized/laundered field name: 'Des_détails' to 'Des_d__tails'
        Warning 6: Normalized/laundered field name: 'Entrez_les_conditions_météorolo' to 'Entrez_les_conditions_m__t__orolo'

## Steps to reproduce the problem.
The field definition information (name, type, alias) is stored in a separate system and retrieved from a python script.  However the name laundering seems to occur regardless of the field type, length, precision, etc.

```
options = ["LAUNDER_RESERVED_KEYWORDS=FALSE"]
layer = gdb_datasource.CreateLayer(table_name, spatial_reference, geometry_type, options=options)
field_def = ogr.FieldDefn(field_name, field_type)
field_def.SetWidth(field_length)
field_def.SetAlternativeName(field_alias)
layer.CreateField(field_def)
```
## Operating system

Windows 10

## GDAL version and provenance

gdal 3.4.2 installed form conda forge gdal=3.4.2=py39h3f5efd6_
[template.zip](https://github.com/OSGeo/gdal/files/8780429/template.zip)
5

**Comment by rouault** [comment]
-lco LAUNDER_RESERVED_KEYWORDS=FALSE only controls launder of reserved keywords (SQL keywords typically). "Regular laundering". That is transforming to alphanumeric (0-9, a-z, A-Z, '_')  is systematically done.

That seems in line with the recommendations of https://support.esri.com/en/technical-article/000005588

The only ambiguity to me is about the meaning of "alphanumeric". Are accentuated non-ASCII characters allowed... ?

@adamgutons Do you have access to ESRI software (ArcMap, ArcGIS pro) to check if it is possible to use non-ASCII characters in field names ?

**Comment by adamgutons** [comment]
It is possible when the table is generated in Esri.  
Attached is a copy of the same .gdb with table/fields created via arcpy

And a snippet of the fields displayed in the application

<img width="486" alt="arc_fields" src="https://user-images.githubusercontent.com/34498995/170533787-27e36100-762d-49dd-9b94-646b89192327.PNG">

[template_arc.zip](https://github.com/OSGeo/gdal/files/8780583/template_arc.zip)

**Comment by jratike80** [comment]
I made a test with ArcMAP and it allows for example `åöäè` and it denied as documented  all these `Special characters include hyphens such as in x-coordinate and y-coordinate; parentheses; brackets; and symbols such as $, %, and #.`

**Comment by adamgutons** [comment]
@rouault @jratike80 
Perhaps this has to do with version of Arc?  I am using ArcPro and able to add the `åöäè` characters as field and alias name.  Attached is the same .gdb with the  `åöäè` field. 

<img width="508" alt="arcfields_2" src="https://user-images.githubusercontent.com/34498995/170546435-81751dce-5acc-4a0c-8815-2ec8d9755d04.PNG">
[template_arc (2).zip](https://github.com/OSGeo/gdal/files/8781054/template_arc.2.zip)

**Comment by rouault** [comment]
Could you also test the following limitation "Geodatabase feature class, table, and field names can be up to 64 characters." . I'm not sure if it is 64 unicode characters or 64 bytes (UTF-8 characters). In your example it seems to truncate at 32 unicode characters. 
To test, you try entering some accentated character like "é" repeated as many times as you can.

**Comment by adamgutons** [comment]
ArcPro appears to truncate at 64 characters.  

Below in the first field I am inserting 120 "é" characters which truncates to 64 total in the field name, all 120 characters remain for the field alias.  The second "é" field contains 32 characters.  The third field contains 35 "é" characters.

<img width="923" alt="trunc" src="https://user-images.githubusercontent.com/34498995/170559085-55c514ce-380c-4483-bedc-c043f23d544d.PNG">

**Comment by jratike80** [comment]
> Perhaps this has to do with version of Arc? I am using ArcPro and able to add the `åöäè` characters as field and alias name.

I meant that  `åöäè` were OK for ArcMAP. Characters `-()[]$%#` were not allowed, just as documented in that ESRI reference.

**Comment by adamgutons** [comment]
> I meant that åöäè were OK for ArcMAP. Characters -()[]$%# were not allowed, just as documented in that ESRI reference.

I misread your original comment @jratike80 thank you for clarifying.
