### ISSUE TITLE
GRD files shows wrong no data value on gdalinfo output

### ISSUE THREAD

**Issue by coim32** [OSGeo/gdal#5794]
## Expected behavior and actual behavior.
a GRD file should return -1.0E37 as no data value instead NoData Value=-9.9999999338158125e+036 is returned
gdalinfo_lib.cpp:1076 could be related with this issue, a format like %.7g could produce the correct result

## Steps to reproduce the problem.
gdalinfo myfile.grd

## Operating system
Windows 64

## GDAL version and provenance
2.1.3, released 2017/20/01

**Comment by rouault** [comment]
Can you paste the full output of gdalinfo on your GRD file, so I can know which driver it it is about, and the data type reported ? (or attach a sample file exhibiting that behavior)

**Comment by coim32** [comment]
gdalinfo height_20m_0_0.grd
Driver: NWT_GRD/Northwood Numeric Grid Format .grd/.tab
Files: height_20m_0_0.grd
Size is 20628, 14387
Coordinate System is:
PROJCS["unnamed",
    GEOGCS["unnamed",
        DATUM["WGS_1984",
            SPHEROID["WGS 84",6378137,298.257223563],
            TOWGS84[0,0,0,0,0,0,0]],
        PRIMEM["Greenwich",0],
        UNIT["degree",0.0174532925199433]],
    PROJECTION["Lambert_Conformal_Conic_2SP"],
    PARAMETER["standard_parallel_1",47],
    PARAMETER["standard_parallel_2",51],
    PARAMETER["latitude_of_origin",44],
    PARAMETER["central_meridian",32],
    PARAMETER["false_easting",750000],
    PARAMETER["false_northing",0],
    UNIT["Meter",1.0]]
Origin = (51630.000000000000000,955310.000000000000000)
Pixel Size = (20.000000000000000,-20.000000000000000)
Corner Coordinates:
Upper Left  (   51630.000,  955310.000)
Lower Left  (   51630.000,  667570.000)
Upper Right (  464190.000,  955310.000)
Lower Right (  464190.000,  667570.000)
Center      (  257910.000,  811440.000)
Band 1 Block=20628x1 Type=Byte, ColorInterp=Red
Band 2 Block=20628x1 Type=Byte, ColorInterp=Green
Band 3 Block=20628x1 Type=Byte, ColorInterp=Blue
Band 4 Block=20628x1 Type=Float32, ColorInterp=Undefined
  NoData Value=-9.9999999338158125e+036

**Comment by coim32** [comment]
-1.0E37 is the default no data value for that format
