### ISSUE TITLE
CPLFinderInit() doesn't check GDAL_PREFIX in GDAL 2.3.0

### ISSUE THREAD

**Issue by sebastic** [OSGeo/gdal#582]
## Expected behavior and actual behavior.

The `gdal` Debian package is patch to use `/usr/share/gdal/<GDAL_VERSION_MAJOR>.<GDAL_VERSION_MINOR>` as the `datapath` by patching `CPLFinderInit()`:
```
117 #ifdef GDAL_PREFIX
118   #ifdef MACOSX_FRAMEWORK
119             CPLPushFinderLocation( GDAL_PREFIX "/Resources/gdal" );
120   #else
121             CPLPushFinderLocation( GDAL_PREFIX "/share/gdal/2.3" );
122   #endif
123 #endif
```
And during the build the `install` target is called with `INST_DATA="\$$(prefix)/share/gdal/2.3"`

One of the postgis tests fails with the gdal (2.3.0~rc1-1~exp1) Debian package because it cannot find the data file, see: https://trac.osgeo.org/postgis/ticket/4078

A similar issue affects Fiona, see: https://github.com/Toblerity/Fiona/issues/583

It seems that the hardcoded path in `CPLFinderInit()` is no longer used in GDAL 2.3.0, because the PostGIS and Fiona issues can be worked around by settings the `GDAL_DATA` environment variable.

## Steps to reproduce the problem.

Build the postgis Debian package using the gdal Debian package from the experimental repository.

## Operating system

Debian unstable

## GDAL version and provenance

2.3.0-rc1 from Debian unstable

**Comment by rouault** [comment]
I can't remember what would have changed in that area in 2.3.0 and comparing the code of port/cpl_findfile.cpp and port/GNUmakefile between 2.3.0 and 2.2.0 doens't show anything significant. Furthermore I've just testing debian experimental and it seems the CSV files can be found as shown below

```
root@f5fc944fc40d:/# dpkg -l | grep gdal
ii  gdal-bin                  2.3.0~rc1+dfsg-1~exp1          amd64        Geospatial Data Abstraction Library - Utility programs
ii  gdal-data                 2.3.0~rc1+dfsg-1~exp1          all          Geospatial Data Abstraction Library - Data files
ii  libgdal20                 2.3.0~rc1+dfsg-1~exp1          amd64        Geospatial Data Abstraction Library

root@f5fc944fc40d:/# gdalinfo --version
GDAL 2.3.0, released 2018/05/04

root@f5fc944fc40d:/# env | grep GDAL_DATA
root@f5fc944fc40d:/# 

root@f5fc944fc40d:/# gdalsrsinfo EPSG:4328

PROJ.4 : +proj=geocent +datum=WGS84 +units=m +no_defs 

OGC WKT :
GEOCCS["WGS 84 (geocentric)",
    DATUM["WGS_1984",
        SPHEROID["WGS 84",6378137,298.257223563,
            AUTHORITY["EPSG","7030"]],
        AUTHORITY["EPSG","6326"]],
    PRIMEM["Greenwich",0,
        AUTHORITY["EPSG","8901"]],
    UNIT["metre",1,
        AUTHORITY["EPSG","9001"]],
    AXIS["Geocentric X",OTHER],
    AXIS["Geocentric Y",OTHER],
    AXIS["Geocentric Z",NORTH],
    AUTHORITY["EPSG","4328"]]

root@f5fc944fc40d:/# strace gdalsrsinfo EPSG:4328 2>&1 | grep csv
stat("/usr/share/gdal/2.3/gcs.csv", {st_mode=S_IFREG|0644, st_size=54388, ...}) = 0
openat(AT_FDCWD, "/usr/share/gdal/2.3/gcs.csv", O_RDONLY) = 3
stat("/usr/share/gdal/2.3/gcs.override.csv", {st_mode=S_IFREG|0644, st_size=513, ...}) = 0
openat(AT_FDCWD, "/usr/share/gdal/2.3/gcs.override.csv", O_RDONLY) = 3
stat("/usr/share/gdal/2.3/pcs.override.csv", {st_mode=S_IFREG|0644, st_size=1581, ...}) = 0
openat(AT_FDCWD, "/usr/share/gdal/2.3/pcs.override.csv", O_RDONLY) = 3
stat("/usr/share/gdal/2.3/pcs.csv", {st_mode=S_IFREG|0644, st_size=798625, ...}) = 0
openat(AT_FDCWD, "/usr/share/gdal/2.3/pcs.csv", O_RDONLY) = 3
stat("/usr/share/gdal/2.3/vertcs.override.csv", {st_mode=S_IFREG|0644, st_size=1081, ...}) = 0
openat(AT_FDCWD, "/usr/share/gdal/2.3/vertcs.override.csv", O_RDONLY) = 3
stat("/usr/share/gdal/2.3/vertcs.csv", {st_mode=S_IFREG|0644, st_size=13530, ...}) = 0
openat(AT_FDCWD, "/usr/share/gdal/2.3/vertcs.csv", O_RDONLY) = 3
stat("/usr/share/gdal/2.3/compdcs.csv", {st_mode=S_IFREG|0644, st_size=9202, ...}) = 0
openat(AT_FDCWD, "/usr/share/gdal/2.3/compdcs.csv", O_RDONLY) = 3
stat("/usr/share/gdal/2.3/geoccs.csv", {st_mode=S_IFREG|0644, st_size=15669, ...}) = 0
openat(AT_FDCWD, "/usr/share/gdal/2.3/geoccs.csv", O_RDONLY) = 3
stat("/usr/share/gdal/2.3/ellipsoid.csv", {st_mode=S_IFREG|0644, st_size=14759, ...}) = 0
openat(AT_FDCWD, "/usr/share/gdal/2.3/ellipsoid.csv", O_RDONLY) = 3
```

**Comment by rouault** [comment]
@sebastic I assume we can close that ticket ?

**Comment by sebastic** [comment]
Yes, we have a reasonable solution by not using the versions specific subdirectory any more.

**Comment by rouault** [comment]
Reviewing your initial comment, ```during the build the install target is called with INST_DATA="\$$(prefix)/share/gdal/2.3"```, that was likely to be inefficient regarding CPLFinderInit(), since -DINST_DATA must be active during the 'make' target so as to be hardcoded. But the #ifdef GDAL_PREFIX should have triggered never-the-less (GDAL_PREFIX is defined in port/cpl_config.h at configure time) and the related override should have worked. So why this didn't work is a bit of a mistery
