### ISSUE TITLE
Unable to calculate slope with SRTM DEM data

### ISSUE THREAD

**Issue by minjinclara** [OSGeo/gdal#5825]
I downloaded the DEM(elevation) tif file of South Korea with 30m resolution of SRTM  provided by USGS.
I used this dem data to write a Python code that shows the aspect and slope.
The code runs well, but it was found to be strange when calculating the slope.
The result of calculating the slope of the entire South Korean region appears as the following image.

![slope(using gdal)](https://user-images.githubusercontent.com/96167962/171104415-94b155b3-9369-4648-99b3-c0c6c1a2d0cb.png)
![slope(using richdem)](https://user-images.githubusercontent.com/96167962/171104419-af2a8b22-0607-4230-8309-c9228a88b9ad.png)

I calculated the slope in a lot of different ways (richdem, gdal, etc.), but the results were always the same. 
Is the dem data wrong or is it a problem that can be solved within Gdal?

**Comment by rouault** [comment]
Quoting top of issue template:
```
IMPORTANT: Do NOT use GitHub to post any questions or support requests!
           They will be closed immediately and ignored.

Questions should go to the gdal-dev mailing list at
https://lists.osgeo.org/mailman/listinfo/gdal-dev
or other support forums. GitHub issues are for bug
reports and suggestions for new features.
```
