### ISSUE TITLE
Cannot load Benicia DEM file (USGSDEM driver)

### ISSUE THREAD

**Issue by kavindergupta** [OSGeo/gdal#583]
## Expected behavior and actual behavior.

I have tried to load the attached DEM in other GIS software (i.e., GlobalMapper 18, etc). They are able to load the DEM correctly. It seems to be a bug in GDAL.
[Benica.zip](https://github.com/OSGeo/gdal/files/1979497/Benica.zip)

## Steps to reproduce the problem.

Load the attached DEM file and try to read the elevation data. Also, try to compute the Statistics.

## Operating system

Windows 10 x64

## GDAL version and provenance

2.2.4

**Comment by rouault** [comment]
Confirmed. Can be reproduced at lest starting with GDAL 1.11 to 2.3.0. Accessing the imagery fails with
```
ERROR 1: Benicia.dem, band 1: IReadBlock failed at X offset 0, Y offset 0
ERROR 3: Checksum value could not be computed due to I/O read error.
```
