### ISSUE TITLE
CMake problem for Python bindings on Windows

### ISSUE THREAD

**Issue by zklaus** [OSGeo/gdal#5831]
## Expected behavior and actual behavior.

In Conda-forge, when building Gdal with Cmake on Windows, we ran into the following problem.
In the Python bindings `CMakeLists.txt`, in [line 107](https://github.com/OSGeo/gdal/blob/dbf2ae50d0b43496c70328ccc4450c5ded90cc46/swig/python/CMakeLists.txt#L107) the target directory for a copy operation is converted to native Windows format with a trailing slash. This ends up as a trailing backslash in [line 114](https://github.com/OSGeo/gdal/blob/dbf2ae50d0b43496c70328ccc4450c5ded90cc46/swig/python/CMakeLists.txt#L114), which in turn is then interpreted as a continuation line in the generated makefile, joining the next line to the copy command to form the non-sensical
[`[...] copy_if_different [...] cd %BUILD_DIR%`](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=514385&view=logs&j=171a126d-c574-5c8c-1269-ff3b989e923d&t=1183ba29-a0b5-5324-8463-2a49ace9e213&l=7891).

## Steps to reproduce the problem.
Build Python bindings with CMake on Windows.

## Operating system
Windows CI Azure

## GDAL version and provenance
3.5.0 source

**Comment by rouault** [comment]
@zklaus can you check if https://github.com/OSGeo/gdal/pull/5833 fixes your issue ?  I assume you use Ninja as the build tool ? I couldn't reproduce the issue with Visual Studio projects in the SWIG_REGENERATE_PYTHON=OFF code path

**Comment by zklaus** [comment]
Trying it now. We use `"NMake Makefiles"` and `cmake --build`.

**Comment by rouault** [comment]
@zklaus  did PR #5833 help ?

**Comment by zklaus** [comment]
@rouault, I think yes. But following your questions, I switched to Ninja and independently I ran into other Cmake related problems. If it's ok for you, I would like to get the whole build to work and then make one last pass to sort out which of the changes are actually necessary. Would that be ok?

**Comment by rouault** [comment]
> Would that be ok?

fine to me

**Comment by rouault** [comment]
@zklaus Congrats for https://github.com/conda-forge/gdal-feedstock/pull/629 being now merge. Would be great if you could push upstream the patches you had to make

**Comment by zklaus** [comment]
Thanks, @rouault. Sorry I didn't manage to pick this up in time.

**Comment by rouault** [comment]
I tried to pick up patch https://github.com/zklaus/gdal-feedstock/blob/2972fd6abec521ed6f01f153207b8b90b6fc0636/recipe/0002-Use-cmake-path-instead-of-native-path.patch but it was causing regressions on installation of the Python bindings on one of our Windows config where paths such as "d:a/gdal/..." where generated instead of "d:/a/gdal/..."
