### ISSUE TITLE
Ubuntu-Full 3.5.0 Docker container doesn't include JNI/Java bindings

### ISSUE THREAD

**Issue by agxs** [OSGeo/gdal#5845]
## Expected behavior and actual behavior.

The ubuntu-full-3.5.0 container doesn't include the JNI bindings anymore. The previous 3.4.3 version did.

Looking at the changes it looks like 3.5.0 introduced cmake to replace the old build system. The docs for the Java hints indicate that the Java bindings should be included by default (and I can see in the Dockerfile that both `ant` and `openjdk-11` are installed)

The 3.5.0 CMake build log also says:

```
-- The following OPTIONAL packages have not been found:

[... removed other drivers...]
 * JNI
   SWIG_JAVA: Java binding
[...]
```

indicating that there is some kind of build problem to me.

## Steps to reproduce the problem.

`docker run -it --rm osgeo/gdal:ubuntu-full-3.5.0 find / -name \*jni\*` doesn't include `/usr/lib/libgdalalljni.so`.

`docker run -it --rm osgeo/gdal:ubuntu-full-3.4.3 find / -name \*jni\*` does include the above file.

## Operating system

Anything that runs the GDAL Ubuntu Full Docker image

## GDAL version and provenance

3.5.0

**Comment by rouault** [comment]
issues have been corrected in the osgeo/gdal:latest image. Regeneration of osgeo/gdal:ubuntu-full-3.5.0 (using tag v3.5.0.2) in progress

**Comment by rouault** [comment]
osgeo/gdal:ubuntu-full-3.5.0  successfully regenerated with Java bindings:

$ docker run -it --rm osgeo/gdal:ubuntu-full-3.5.0 find / -name \*jni\*
[...]
/usr/share/java/libgdalalljni.so
[...]

**Comment by nobodo** [comment]
Broken again; libgdalalljni.so no longer found from the latest images
