### ISSUE TITLE
VFK: Support for UTF-8 encoding

### ISSUE THREAD

**Issue by isax-sro** [OSGeo/gdal#5853]
## Expected behavior and actual behavior.

Support for UTF-8 is needed from 14.4.2022. We have already fixed VFK driver through modification of 3.4.4 GDAL version code. Hopefully we will soon suggest pull request.

## Steps to reproduce the problem.

Encoding error while trying read VFK data with UTF-8 encoding

## Operating system

Debian 10

## GDAL version and provenance

Tested with 3.4.4

**Comment by rouault** [comment]
I believe a related fix was already pushed in latest to master / 3.5 branch by @landam

**Comment by jratike80** [comment]
Repeating: @landam can this ticket be closed ?

**Comment by landam** [comment]
Sorry for my silence. Yes, we can close the issue.
