### ISSUE TITLE
FIleGdb Driver rounds M values on write

### ISSUE THREAD

**Issue by jsmith-pathway** [OSGeo/gdal#5858]
## Expected behavior and actual behavior.

I expected to be able to store more than 4 decimal places to the M values of vertexes. Instead when I store 7 decimals I get rounded values after I write my features to the layer.

## Steps to reproduce the problem.

Create a new feature in memory and assign a geometry object that contains points with M values. If those M values have more than 4 decimal places they will be rounded after the feature is added to the FileGdb layer.

## Operating system

Windows 10

## GDAL version and provenance

I've tested both 2.4.3 and 3.4.3 and the behavior seems to be the same. I'm using the swig C# libraries and adding the Esri FileGdb plugin to my environment.

**Comment by rouault** [comment]
With the fix in https://github.com/OSGeo/gdal/pull/5860, setting the MSCALE to a higher value than its default 10000 value will help select the desired precision for M values
