### ISSUE TITLE
MSSQLSPATIAL_LIST_ALL_TABLES: no column definition

### ISSUE THREAD

**Issue by landam** [OSGeo/gdal#586]
## Expected behavior and actual behavior.

MSSQLSPATIAL_LIST_ALL_TABLES config option seems to not work correctly under some conditions. Tested with SQL Server 2014, see below.

See also related discussion on ML: https://lists.osgeo.org/pipermail/gdal-dev/2018-May/048480.html

## Steps to reproduce the problem.

```
ogrinfo "MSSQL:database=kn;..." sobr -so

Layer name: sobr
...
FID Column = fid
id: Integer64 (19.0)
```

Fails with MSSQLSPATIAL_LIST_ALL_TABLES:

```
$ ogrinfo "MSSQL:database=kn;..." --config MSSQLSPATIAL_LIST_ALL_TABLES YES sobr -so 
ERROR 1: No column definitions found for table 'dbo.geometry_columns', layer not usable.
ERROR 1: No column definitions found for table 'dbo.spatial_ref_sys', layer not usable.
INFO: Open of `MSSQL:database=kn;server=geo103.fsv.cvut.cz\kartografiesql;uid=landa;pwd=landa'
      using driver `MSSQLSpatial' successful.
FAILURE: Couldn't fetch requested layer sobr!
````

## GDAL version and provenance

GDAL master

**Comment by landam** [comment]
@szekerest Thanks for fix! Tested, works fine. Are you planning backport to release/2.3/2.2 branches?

**Comment by szekerest** [comment]
yes, as far as I see only the 2.3 branch is affected

**Comment by rouault** [comment]
I've cherry-picked https://github.com/OSGeo/gdal/commit/25db15fb6ce1380574ef477f213325238759b8fd as 70e91e1b9a45d33f5aa9a4cde043c527d674aa18 in release/2.3

**Comment by szekerest** [comment]
Thanks for backporting
