### ISSUE TITLE
MVT driver adds layers that are not part of the `CONF` json

### ISSUE THREAD

**Issue by ChristianBeilschmidt** [OSGeo/gdal#5874]
## Expected behavior and actual behavior.

I'm using OGR for creating EPSG:4326 MVT from the natural earth GPKG file. For testing, I just wanted to add one layer, `ocean`, by having two input tables depending on the zoom level. However, `ogr2ogr` adds about 100 other layers to the output MVT.

## Steps to reproduce the problem.

You can find the natural earth data here: http://naciscdn.org/naturalearth/packages/natural_earth_vector.gpkg.zip

```bash
ogr2ogr -f MVT tileset \
            natural_earth_vector.gpkg \
            -dsco MAXZOOM=5 \
            -dsco TILING_SCHEME="EPSG:4326,-180,180,360" \
            -dsco FORMAT=DIRECTORY \
            -dsco COMPRESS=YES \
            -dsco TYPE=baselayer \
            -dsco NAME=ne \
            -dsco DESCRIPTION="Natural Earth Basemap" \
            -dsco CONF=gdal_mvt_ne_conf.json
```

Content of the `gdal_mvt_ne_conf.json`:

```json
{
  "ne_110m_ocean": {
    "target_name": "ocean",
    "minzoom": 0,
    "maxzoom": 2
  },
  "ne_50m_ocean": {
    "target_name": "ocean",
    "minzoom": 3,
    "maxzoom": 5
  }
}
```

```bash
ogrinfo MVT:tileset/1/0/0.pbf 
INFO: Open of `MVT:tileset/1/0/0.pbf'
      using driver `MVT' successful.
1: ne_110m_ocean
2: ocean
3: ne_110m_land (Polygon)
4: ne_110m_admin_0_countries (Multi Polygon)
5: ne_110m_admin_0_map_units (Multi Polygon)
[…]
97: ne_10m_admin_0_boundary_lines_map_units (Multi Line String)
98: ne_10m_admin_1_seams (Multi Line String)
99: ne_50m_admin_1_seams (Line String)
100: ne_10m_rivers_europe (Line String)
101: ne_50m_admin_0_boundary_map_units (Line String)
102: ne_10m_lakes_north_america (Multi Polygon)
103: ne_10m_lakes_pluvial (Multi Polygon)
```

## Operating system

I used the following Docker image: `osgeo/gdal:alpine-normal-3.5.0`

## GDAL version and provenance

GDAL 3.5 from the official docker image

**Comment by jratike80** [comment]
I have not used MVT driver myself and I am not sure by reading https://gdal.org/drivers/vector/mvt.html if the CONF option is supposed to select the layers from the source dataset by the same, or just to configure the layers that are found from the conf file in a certain way.

The normal  way to select layers with ogr2ogr should work also in this use case. Add a list of the layers that you want to convert to the end of the ogr2ogr command:
```
\
 ne_110m_ocean ne_50m_ocean
```

**Comment by ChristianBeilschmidt** [comment]
Wow, you are right. When I specify `ne_110m_ocean ne_50m_ocean` above, then only one layer, `ocean`, is in the output.
