### ISSUE TITLE
A problem occurred during the GDAL installation

### ISSUE THREAD

**Issue by 1ftt** [OSGeo/gdal#5876]
Ubuntu22.04
After running this operation：  ./configure

GDAL is now configured for x86_64-pc-linux-gnu

  Installation directory:    /usr/local
  C compiler:                gcc -DHAVE_AVX_AT_COMPILE_TIME -DHAVE_SSSE3_AT_COMPILE_TIME -DHAVE_SSE_AT_COMPILE_TIME -g -O2
  C++ compiler:              g++ -DHAVE_AVX_AT_COMPILE_TIME -DHAVE_SSSE3_AT_COMPILE_TIME -DHAVE_SSE_AT_COMPILE_TIME -g -O2
  C++14 support:             no

  LIBTOOL support:           yes

  Armadillo support:         no
  Blosc support:             yes
  CFITSIO support:           external
  crypto/openssl support:    yes
  cryptopp support:          no
  cURL support (wms/wcs/...):yes
  DDS support:               no
  DODS support:              no
  ECW support:               no
  Expat support:             yes
  EXR support:               no
  FGDB support:              no
  FreeXL support:            yes
  GEORASTER support:         no
  GEOS support:              yes
  Google libkml support:     yes
  GRASS support:             no
  GTA support:               no
  HDF4 support:              yes
  HDF5 support:              yes
  JXL support:               no
  HDFS support:              no
  HEIF support:              yes
  INFORMIX DataBlade support:no
  Ingres support:            no
  JP2Lura support:           no
  JPEG 12 bit:               yes
  JPEG-in-TIFF 12 bit:       no
  JPEG JasPer support:       no
  JPEG-Lossless/CharLS:      yes
  Kakadu support:            no
  Kea support:               yes
  LERC support:              internal
  libbrunsli support:        no
  libdeflate support:        yes
  LIBGEOTIFF support:        external
  LIBGIF support:            external
  LIBJPEG support:           external
  LIBLZMA support:           no
  LIBPNG support:            external
  LIBTIFF support:           external (BigTIFF=yes)
  libxml2 support:           yes
  LIBZ support:              external
  LZ4 support:               yes
  MDB support:               no
  MongoCXX v3 support:       no
  MongoDB support:           no
  MrSID/MG4 Lidar support:   no
  MrSID support:             no
  MSG support:               no
  MySQL support:             no
  NetCDF has netcdf_mem.h:   yes
  NetCDF support:            yes
  OCI support:               no
  ODBC support:              yes
  OGDI support:              yes
  OpenCL support:            no
  OpenJPEG support:          yes
  PCIDSK support:            internal
  PCRaster support:          internal
  PCRE support:              no
  PCRE2 support:             yes
  PDFium support:            no
  Podofo support:            no
  Poppler support:           no
  PostgreSQL support:        yes
  QHull support:             external
  Rasdaman support:          no
  RasterLite2 support:       no
  RDB support:               no
  SFCGAL support:            
  SOSI support:              no
  SpatiaLite support:        no
  SQLite support:            yes
  Teigha (DWG and DGNv8):    no
  TileDB support:            yes
  userfaultfd support:       yes
  WebP support:              yes
  Xerces-C support:          yes
  ZSTD support:              yes

  misc. gdal formats:        aaigrid adrg aigrid airsar arg blx bmp bsb cals ceos ceos2 coasp cosar ctg dimap dted elas envisat ers esric fit gff gsg gxf hf2 idrisi ilwis ingr iris iso8211 jaxapalsar jdem kmlsuperoverlay l1b leveller map mrf msgn ngsgeoid nitf northwood pds prf r raw rmf rs2 safe saga sdts sentinel2 sgi sigdem srtmhgt stacit stacta terragen tga til tsx usgsdem xpm xyz zarr zmap rik ozi eeda plmosaic rda wcs wms wmts daas ogcapi rasterlite mbtiles grib pdf
  misc. ogr formats:         arcgen avc cad csv dgn dxf edigeo flatgeobuf geoconcept georss gml gmt gpsbabel gpx gtm jml mapml mvt ntf openfilegdb pgdump rec s57 selafin shape svg sxf tiger vdv wasp idrisi pds sdts amigocloud carto cloudant couchdb csw elastic ngw plscenes wfs gpkg vfk osm nas ili gmlas ods xlsx lvbag odbc pgeo mssqlspatial geomedia walk

  disabled gdal formats:    
  disabled ogr formats:     

  SWIG Bindings:             python 

  PROJ >= 6:                 yes
  enable GNM building:       yes
  enable pthread support:    yes
  enable POSIX iconv support:yes
  hide internal symbols:     no

Do not know how to solve the problem when running make operation

/usr/bin/ld: /home/ftt/gdal-3.4.1/.libs/libgdal.so: undefined reference to `tiledb_dimension_get_tile_extent'
/usr/bin/ld: /home/ftt/gdal-3.4.1/.libs/libgdal.so: undefined reference to `tiledb_filter_list_free'
/usr/bin/ld: /home/ftt/gdal-3.4.1/.libs/libgdal.so: undefined reference to `jpeg_set_colorspace@LIBJPEG_9.0'
/usr/bin/ld: /home/ftt/gdal-3.4.1/.libs/libgdal.so: undefined reference to `jpeg_read_coefficients@LIBJPEG_9.0'
/usr/bin/ld: /home/ftt/gdal-3.4.1/.libs/libgdal.so: undefined reference to `kealib::KEAImageIO::maskCreated(unsigned int)'
/usr/bin/ld: /home/ftt/gdal-3.4.1/.libs/libgdal.so: undefined reference to `json_tokener_new_ex'
/usr/bin/ld: /home/ftt/gdal-3.4.1/.libs/libgdal.so: undefined reference to `json_object_to_json_string'
/usr/bin/ld: /home/ftt/gdal-3.4.1/.libs/libgdal.so: undefined reference to `tiledb_attribute_free'
/usr/bin/ld: /home/ftt/gdal-3.4.1/.libs/libgdal.so: undefined reference to `kealib::KEAImageIO::openKeaH5RW(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, unsigned long long, unsigned long long, double, unsigned long long, unsigned long long)'
collect2: error: ld returned 1 exit status
make[1]: *** [GNUmakefile:89: gdalinfo] Error 1
make[1]: Leaving directory '/home/ftt/gdal-3.4.1/apps'
make: *** [GNUmakefile:123: apps-target] Error 2

can you give me a hand？

**Comment by rouault** [comment]
You likely need to add in LD_LIBRARY_PATH the path to the lib subdirectory of tiledb, libjpeg, libjson-c and libkea.

**Comment by 1ftt** [comment]
> 



> 您可能需要添加LD_LIBRARY_PATH tiledb，libjpeg，libjson-c和libkea的lib子目录的路径。

Error message editing after running make.    I have rewritten it, please have a look again.

db_dimension_get_tile_extent'
/usr/bin/ld: /home/ftt/gdal-3.4.1/.libs/libgdal.so: undefined reference to `tiledb_filter_list_free'
/usr/bin/ld: /home/ftt/gdal-3.4.1/.libs/libgdal.so: undefined reference to `jpeg_set_colorspace@LIBJPEG_9.0'
/usr/bin/ld: /home/ftt/gdal-3.4.1/.libs/libgdal.so: undefined reference to `jpeg_read_coefficients@LIBJPEG_9.0'
/usr/bin/ld: /home/ftt/gdal-3.4.1/.libs/libgdal.so: undefined reference to `kealib::KEAImageIO::maskCreated(unsigned int)'
/usr/bin/ld: /home/ftt/gdal-3.4.1/.libs/libgdal.so: undefined reference to `json_tokener_new_ex'
/usr/bin/ld: /home/ftt/gdal-3.4.1/.libs/libgdal.so: undefined reference to `json_object_to_json_string'
/usr/bin/ld: /home/ftt/gdal-3.4.1/.libs/libgdal.so: undefined reference to `tiledb_attribute_free'
/usr/bin/ld: /home/ftt/gdal-3.4.1/.libs/libgdal.so: undefined reference to `kealib::KEAImageIO::openKeaH5RW(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, unsigned long long, unsigned long long, double, unsigned long long, unsigned long long)'
collect2: error: ld returned 1 exit status
make[1]: *** [GNUmakefile:89: gdalinfo] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/home/ftt/gdal-3.4.1/apps'
make: *** [GNUmakefile:123: apps-target] Error 2

**Comment by rouault** [comment]
closing as I think this is just a usage issue and not a GDAL bug.
