### ISSUE TITLE
CSV driver: AUTODETECT_SIZE_LIMIT=0 silently fails

### ISSUE THREAD

**Issue by spencermathews** [OSGeo/gdal#5885]
## Expected behavior and actual behavior

I expect when using `ogr2ogr` with a CSV datasource and the `-oo AUTODETECT_TYPE=YES` option combined with `-oo AUTODETECT_SIZE_LIMIT=0` that autodetect will consider the whole file, as stated in the docs.

https://github.com/OSGeo/gdal/blob/20c8127acf675ca9610ce481691cb78c93ac9ea1/doc/source/drivers/vector/csv.rst?plain=1#L280-L284

However, when working with a 17 GB CSV file this not the case. A particular field containing mostly integer values, but also some alphabetic values, was incorrectly detected as `Integer` type with the default `AUTODETECT_SIZE_LIMIT` of 1,000,000 bytes. I attempted to use `AUTODETECT_SIZE_LIMIT=0` but the field was still not properly detected as `String` type. Then, I tried `AUTODETECT_SIZE_LIMIT=17469850133`, the file size in byes (as reported by `wc`), to the same effect.

All these cases threw a `Warning 1: Invalid value type found in record X for field Y. This warning will no longer be emitted.` to indicate that the alphabetic values encountered later in the file were being ignored.

I suspected that this had something to do with the large file size, and a glance at `ogrcsvlayer.cpp` suggested integer overflow involving `int nBytes`. I tried again with `AUTODETECT_SIZE_LIMIT=2147483647`, the maximum value of a 32-bit `int` (`long`), and the field was properly detected as `String`. I tested this bound with `AUTODETECT_SIZE_LIMIT=2147483648` and, indeed, autodetect failed on the field in question.

Either `AUTODETECT_SIZE_LIMIT=0` should actually consider the whole file or the user should be warned that it is not doing so.

https://github.com/OSGeo/gdal/blob/20c8127acf675ca9610ce481691cb78c93ac9ea1/ogr/ogrsf_frmts/csv/ogrcsvlayer.cpp#L919-L934

https://github.com/OSGeo/gdal/blob/20c8127acf675ca9610ce481691cb78c93ac9ea1/ogr/ogrsf_frmts/csv/ogrcsvdriver.cpp#L364

## Possible solutions

1. Document the maximum valid `AUTODETECT_SIZE_LIMIT` for the end user, at the very least.
2. Warn the user if they specify an `AUTODETECT_SIZE_LIMIT` value that is out of bounds.
3. Warn the user if they specify `AUTODETECT_SIZE_LIMIT=0` value that is out of bounds but the file size exceeds the autodetect's byte limit.
4. Improve exception handling of the above cases to fall back on the effective maximum `AUTODETECT_SIZE_LIMIT` of `2147483647` bytes , not the much lower default of `1000000` bytes.

One final question, as far as I can tell the only way to directly specify the field types of a CSV datasource is through a `*.csvt` file, but this requires specifying the type of all fields. Is it really not possible to specify the type for some fields then let autodetect handle the rest?

## Operating system

CentOS 7.9

## GDAL version and provenance

gdal34-libs.x86_64 3.4.1-3.rhel7 @pgdg-common

## References

* [<limits.h>](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/limits.h.html)
* [<limits.h>](https://sourceware.org/git/?p=glibc.git;a=blob;f=include/limits.h;hb=master)

**Comment by jratike80** [comment]
> One final question, as far as I can tell the only way to directly specify the field types of a CSV datasource is through a *.csvt file, but this requires specifying the type of all fields. Is it really not possible to specify the type for some fields then let autodetect handle the rest?

I think I would take another approach and autodetect a small sample and edit the csvt manually.

`ogr2ogr -f csv -oo autodetect_type=yes -sql "select * from huge limit 100" -lco create_csvt=yes out.csv huge.csv`

Now the out.csvt file will have all fields autodetected from the first 100 rows and you do not even need to count how many fields there are in the csv as you should do if your aim was to write a partial csvt file with some defined and some undefined fields somehow like this
`Integer,-,-,-,String,-,-,String`
