### ISSUE TITLE
GDAL v. 3.4.2 and 3.4.3, Mac OS X Lion : built OK but gdalinfo (--formats) issues a PROJ error

### ISSUE THREAD

**Issue by Laurent-777** [OSGeo/gdal#5894]
# Expected behavior and actual behavior.
No error when running : gdalinfo --formats (a simple test I use)

## Steps to reproduce the problem.

gdalinfo --formats

## Operating system

Mac OS X Lion (10.7.5)
Mac mini Intel Core 2 Duo
GCC/G++ 4.9.4 (built with my Mac)
PROJ.6 v. 6.3 used (compiled with source code).

## GDAL version and provenance
3.4.2 and 3.4.3. Source codes downloaded, then compiled.

Remark : no problem before

**Comment by Laurent-777** [comment]
[config.log](https://github.com/OSGeo/gdal/files/8868556/config.log)
[my-configure.log](https://github.com/OSGeo/gdal/files/8868557/my-configure.log)
[my-make.log](https://github.com/OSGeo/gdal/files/8868558/my-make.log)
[my-install.log](https://github.com/OSGeo/gdal/files/8868560/my-install.log)
[my-gdal-formats.log](https://github.com/OSGeo/gdal/files/8868563/my-gdal-formats.log)

**Comment by rouault** [comment]
Closing as the error is in PROJ
