### ISSUE TITLE
Gdal v. 3.5.0.3, Mac Lion-inner dyld with Cmake not inner set comparing to autotools 

### ISSUE THREAD

**Issue by Laurent-777** [OSGeo/gdal#5908]
gdalinfo - -formats not running anymore even though gdal 3.5.0.3 seems to be installed correctly. 
-->

## Expected behavior and actual behavior.
1/ gdalinfo - - formats returns the formats 
2/ no dynamic library (gdal, third parties) is referenced anymore since Cmake, but previous versions work.DYLD_LIBRARY_PATH is not set anymore with Cmake. 

## Steps to reproduce the problem
gdalinfo - - formats doesn't find the gdal library and other ones such as proj (NB Proj. 9 was used and seems to "work"). 

## Operating system
Mac mini Intel core 2 duo
Mac os x lion 
Gnu gcc 4.9.4(to be confirmed) built with my Mac. 

## GDAL version and provenance
3.5.0.3 (in fact, even not yest tested, it should be the same with 3.5.0.x, 3.5.y.x maybe). 

Kind regards,

**Comment by rouault** [comment]
if you want the RPATH to be set on installed binaries, you may need to pass the -DGDAL_SET_INSTALL_RELATIVE_RPATH=ON option to CMake

See https://gdal.org/build_hints.html#cmdoption-arg-GDAL_SET_INSTALL_RELATIVE_RPATH

**Comment by Laurent-777** [comment]
OK. I guess I will try it this weekend.
Besides, please note that almost all my softwares, including thirdparties ones, are not in a standard location, namely, not in /usr/local.
Thank you very much.
Kind regards,

**Comment by Laurent-777** [comment]
Hi 👍
I tried it this morning, as indicated.
Nevertheless, it  fails again. Now, gdalinfo - - formats asks the proj library, and probably the other dependent ones Gdal needs. I guess one may set or find DYLD_LIBRARY_PATG.
Besides, this version of Gdal is compiled and installed correctly, as for previous versions.

Note : curl provided by Apple (Lion) makes the compilation failing with this version. The curl version I compiled is OK. Same remark with Sqlite (and Spatialite), recent versions. Eventually, Java fails make to compile : but I am not using Java. As with C++, I do not use these programming languages. In fact. I use Objective-C, sometimes Fortran, and I probably will investigate D, Go, possibly one or more others.

Kind regards,

**Comment by Laurent-777** [comment]
Hi : Same error with autotools (after having run autogen.sh). I will try to find what differs from versions previous to v. 3.5.x. Probably with diff.

Kind regards,

**Comment by Laurent-777** [comment]
Hi :
I guess I found what matters. Hereafter what I did for.
I used autotools and I changed the Proj configuration from Proj9 to Proj6. I run autogen.sh then configure and make etc.
With proj6, gdalinfo - - formats gave the appropriate information (but one format maybe, as for the most recent gdal versions).
So, up to proj6, it works. I have not tested with proj7 and proj8.
First task I will do, is to test with Cmake, and proj6.
If I have time, testing with proj7 and proj8.
However, please note that I am very late in my work, due to many bugs I found elsewhere, I fix step by step.
So, it seems this is a proj bug.

Kind regards, 
Encl. Log files as earlier.

**Comment by Laurent-777** [comment]
Hi : Hereafter, enclosed PDF file from ADC (Apple Developer Community).
Kind regards,

Laurent D.

Encl. 2
[Dynamic Library Programming Topics (2006-11-07).pdf](https://github.com/OSGeo/gdal/files/8928736/Dynamic.Library.Programming.Topics.2006-11-07.pdf)
[Framework Programming Guide (2006-11-07).pdf](https://github.com/OSGeo/gdal/files/8928737/Framework.Programming.Guide.2006-11-07.pdf)

**Comment by Laurent-777** [comment]
Hi !

Hereafter my progress to find what matters. First, PROJ7, 8, and 9 issues failure to find the dynamic libaries.

Now, I found other bugs.
First, libzstd makes fail GDAL (version investigated). Enclosed the log files just herefater.
[config.log](https://github.com/OSGeo/gdal/files/8965925/config.log)
[my-configure.log](https://github.com/OSGeo/gdal/files/8965926/my-configure.log)
[my-gdal-formats.log](https://github.com/OSGeo/gdal/files/8965927/my-gdal-formats.log)
[my-install.log](https://github.com/OSGeo/gdal/files/8965928/my-install.log)
[my-make.log](https://github.com/OSGeo/gdal/files/8965929/my-make.log)
[my-python-autotest.log](https://github.com/OSGeo/gdal/files/8965930/my-python-autotest.log)

**Comment by Laurent-777** [comment]
Now a geos/spatailite error (NB I remember that the spatialite team doesn't advise to compile spatialite with Geos).
Hereafter too, log files enclosed.
[config.log](https://github.com/OSGeo/gdal/files/8965950/config.log)
[my-configure.log](https://github.com/OSGeo/gdal/files/8965951/my-configure.log)
[my-gdal-formats.log](https://github.com/OSGeo/gdal/files/8965952/my-gdal-formats.log)
[my-install.log](https://github.com/OSGeo/gdal/files/8965953/my-install.log)
[my-make.log](https://github.com/OSGeo/gdal/files/8965954/my-make.log)
[my-python-autotest.log](https://github.com/OSGeo/gdal/files/8965955/my-python-autotest.log)

**Comment by Laurent-777** [comment]
GEOS error...
Encl
[config.log](https://github.com/OSGeo/gdal/files/8965977/config.log)
[my-configure.log](https://github.com/OSGeo/gdal/files/8965978/my-configure.log)
[my-gdal-formats.log](https://github.com/OSGeo/gdal/files/8965979/my-gdal-formats.log)
[my-install.log](https://github.com/OSGeo/gdal/files/8965980/my-install.log)
[my-make.log](https://github.com/OSGeo/gdal/files/8965981/my-make.log)
[my-python-autotest.log](https://github.com/OSGeo/gdal/files/8965983/my-python-autotest.log)

**Comment by Laurent-777** [comment]
The basis configuration that makes the compilation OK.
Encl.
[config.log](https://github.com/OSGeo/gdal/files/8965988/config.log)
[my-configure.log](https://github.com/OSGeo/gdal/files/8965990/my-configure.log)
[my-gdal-formats.log](https://github.com/OSGeo/gdal/files/8965991/my-gdal-formats.log)
[my-install.log](https://github.com/OSGeo/gdal/files/8965992/my-install.log)
[my-make.log](https://github.com/OSGeo/gdal/files/8965993/my-make.log)
[my-python-autotest.log](https://github.com/OSGeo/gdal/files/8965994/my-python-autotest.log)

**Comment by Laurent-777** [comment]
Before, the compilations were made with PROJ.6x.
Besides, I invetsigated the PROJ sensitivity. Here with PROJ.7. gdalinfo --formats failed...
Encl.
[config.log](https://github.com/OSGeo/gdal/files/8966005/config.log)
[my-configure.log](https://github.com/OSGeo/gdal/files/8966006/my-configure.log)
[my-gdal-formats.log](https://github.com/OSGeo/gdal/files/8966007/my-gdal-formats.log)
[my-install.log](https://github.com/OSGeo/gdal/files/8966008/my-install.log)
[my-make.log](https://github.com/OSGeo/gdal/files/8966009/my-make.log)
[my-python-autotest.log](https://github.com/OSGeo/gdal/files/8966010/my-python-autotest.log)

**Comment by Laurent-777** [comment]
Now with PROJ.8... 
Encl.
[config.log](https://github.com/OSGeo/gdal/files/8966012/config.log)
[my-configure.log](https://github.com/OSGeo/gdal/files/8966013/my-configure.log)
[my-gdal-formats.log](https://github.com/OSGeo/gdal/files/8966014/my-gdal-formats.log)
[my-install.log](https://github.com/OSGeo/gdal/files/8966015/my-install.log)
[my-make.log](https://github.com/OSGeo/gdal/files/8966016/my-make.log)
[my-python-autotest.log](https://github.com/OSGeo/gdal/files/8966017/my-python-autotest.log)

**Comment by jratike80** [comment]
> (NB I remember that the spatialite team doesn't advise to compile spatialite with Geos)

What do you mean with this? Many of the SpatiaLite functions depend on GEOS https://www.gaia-gis.it/gaia-sins/spatialite-sql-latest.html and I think that it is rather uncommon to make builds without those.

**Comment by rouault** [comment]
I'm closing this as I suspect it might be setup specific. I'd note also that OS X Lion is quite old, but I'm not sure this is the issue here

**Comment by Laurent-777** [comment]
Fixed : works with PROJ 6.3.x but not with PROJ 7 and PROJ 8 (in a "as is" devlopment manner). Seems to be OK with PROJ 9.
For THIS version of GDAL, it works. gdal-info --formats gives the formats used and, integrated in a GIS software, I opened raster data easily.
It is a PROJ issue first.

Kind regards,

Laurent Delphin
