### ISSUE TITLE
Appending spatial data to ENVI dataset

### ISSUE THREAD

**Issue by chacha21** [OSGeo/gdal#5923]
As far as I know, it is not possible to append data to an ENVI dataset to increase its spatial size. The spatial size must be known at creation. I can understand why : according to BIL/BIP/BSQ layout, appending spatial data may be cheap (appending data to end of the data file) or stupid (totally scrambling the data).
Therefore, the smart user (me) can just cleverly choose BIL/BIP/BSQ layout according to the nature/layout of the data being appended (in my case : it would be spatial rows, so BIL or BIP would be ok), and manually create the data file and hdr file. GDAL would not create the dataset, it would open it afterwards.

My question is : can I do differently ? Do I miss something in GDAL that would make it easier to create an empty dataset and spatially fill it until some condition ?

**Comment by rouault** [comment]
> Do I miss something in GDAL that would make it easier to create an empty dataset and spatially fill it until some condition ?

no, you don't miss anything. Extending the raster size is not supported in the GDAL API.
Depending on your use case, if you know the final size of the dataset, you could use the Create() API to create it at the final size. The raw file will be normally created in a sparse way (that is zero'ed but not really allocated, if the file system supports it), so this should be fast.

**Comment by chacha21** [comment]
> if you know the final size of the dataset
I don't, it is time dependent; that was the problem.
Anyway, I have my own solution, I just wanted to be sure that I could not do better.
