### ISSUE TITLE
Doc: missing doc of COG JPEG-XL support

### ISSUE THREAD

**Issue by Plantain** [OSGeo/gdal#5939]
The GeoTIFF driver now supports JPEG-XL via libjxl (https://gdal.org/drivers/raster/gtiff.html), but the COG driver does not (https://gdal.org/drivers/raster/cog.html)

Is there a technical limitation here from the JPEG-XL format, or could JXL be added to COG's relatively easily like LERC was in #1812 ?

JPEG-XL has ~60% of the filesize of a similar JPEG, so this would be a really significant improvement in storage efficiency.

**Comment by jratike80** [comment]
I understand the motivation behind developing and adopting new compression techniques but as a user I feel a bit uncomfortable too. Do users without JXL or LERC compatible GDAL version get clear enough message about why they cannot open certain COG files from the web?

**Comment by jratike80** [comment]
I try to help people in gis.stackexchange and I know that the next question is "I wonder what is missing" and then "How can I get what I miss into my Conda/Mac/some other environment". The name of the codec would save one question/answer round.
