### ISSUE TITLE
gdal_contour -snodata value kills the command

### ISSUE THREAD

**Issue by ghtmtt** [OSGeo/gdal#594]
## Expected behavior and actual behavior.

Using `gdal_contour` with `-snodata` flag kills the command after a while. Without this flag it works nice

## Steps to reproduce the problem.

gdal_contour -b 1 -a ELEV -i 500.0 -snodata 0.0 -f "ESRI Shapefile" /home/matteo/dtm.tif "home/matteo/OUTPUT.shp"

Both with CLI and within QGIS 3.1 master

## Operating system

Linux Debian SID

## GDAL version and provenance

GDAL 2.2.4, released 2018/03/19

**Comment by ghtmtt** [comment]
here it is https://www.dropbox.com/s/diwt92hrkeq7j0i/dtm.tif?dl=0

**Comment by rouault** [comment]
The core issue here is the override of the nodata value with 0.0 whereas the raster has a nodata value of -3.4028234663852886e+38. So when encountering such big negative values with nodata overrideen to 0, the algorithm will try to generate billions of intermediate coutour lines
The fix will avoid such attempt and error out immediately

**Comment by ghtmtt** [comment]
Thank for the super quick fix!
