### ISSUE TITLE
GDAL 3.6.0 (master): calling GDALDestroyDriverManager() multiple times causes segmentation fault

### ISSUE THREAD

**Issue by mngr777** [OSGeo/gdal#5946]
## Expected behavior and actual behavior.

C API: calling `GDALDestroyDriverManager()` multiple times causes segmentation fault.

## Steps to reproduce the problem.

The segfault currently appears in PostGIS raster extension built with latest GDAL from master: https://github.com/konturio/postgis/runs/6962928235?check_suite_focus=true
This is simplified version of what happens in the extension that triggers the segfault:
```
#include <gdal.h>

int main() {
    GDALDestroyDriverManager();
    GDALAllRegister();

    GDALDestroyDriverManager();
    GDALAllRegister();

    GDALDestroyDriverManager();
}
```
Compile and run with latest GDAL version to reproduce.

## Operating system

Ubuntu 20.04.4 64-bit

## GDAL version and provenance

3.6.0 (master)

## Cause

The segfault is caused by `VSIStdinFilesystemHandler::~VSIStdinFilesystemHandler` setting gStdinFile to nullptr but not handling nullptr value:
https://github.com/OSGeo/gdal/blob/09879f42fb007c7212b67f4a3bc01520791c8ee3/port/cpl_vsil_stdin.cpp#L396

**Comment by mngr777** [comment]
@rouault Thank you for a quick fix!
Just in case, I noticed gStdinFile can still become nullptr when `fopen` fails in `ParseFilename()`:
https://github.com/OSGeo/gdal/blob/f3c420323cc6ccfdbaa525e01bee42bf54cc4d1d/port/cpl_vsil_stdin.cpp#L535
Can't it still cause the same problem?

**Comment by rouault** [comment]
> Can't it still cause the same problem?

unlikely to happen in real-world usages as it is in a code path normally only used for testing purposes. I've pushed a fix for that anyway
