### ISSUE TITLE
OpenFileGDB Exceptions to create/update capabilities

### ISSUE THREAD

**Issue by Hsxxxxxx** [OSGeo/gdal#5952]
[https://github.com/OSGeo/gdal/pull/5910#issue-1267741143](url)
@rouault 
hi.
I found these issues when using test docker, but not sure if they have been fixed
 **rouault/gdal:alpine-normal-openfilegdb_write**

## Expected behavior and actual behavior.
Python3.10
- DataSource.Rollbacktransaction()
execute ds.Rollbacktransaction() will cause GDB corruption, which makes it impossible to preview or edit
you can open this files in arcmap10.1 to view the error messages
[test.zip](https://github.com/OSGeo/gdal/files/8947168/test.zip)
1. test_c_r_161618.gdb   #error gdb
2. test_commit_161618.gdb  #normal gdb
3. test_rollback_161618.gdb #error gdb

- Layer.CreateField()
 When creating a text field for a layer, the default length is 0, resulting in an error during editing. In filegdb, the default length is 65536
eg: GDB：test_161618.gdb - 》Layer：test_field-》field： field_10

## Steps to reproduce the problem.

run  in  test docker  
`#python test2.py`
get gdb file and test the gdb file in arcmap10.1

## Operating system
Windows10 + ArcMap10.1

## GDAL version and provenance

#5910 test docker image： rouault/gdal:alpine-normal-openfilegdb_write

**Comment by rouault** [comment]
"osgeo/gdal:alpine-normal-latest" docker image has been regenerated with fix for https://github.com/OSGeo/gdal/issues/5952, and outdated "rouault/gdal:alpine-normal-openfilegdb_write" has been removed
