### ISSUE TITLE
CMake links to PNG even with -DGDAL_USE_PNG=OFF

### ISSUE THREAD

**Issue by adamjstewart** [OSGeo/gdal#5994]
## Expected behavior and actual behavior.

Since PNG isn't listed as a required dependency, I would expect to be able to build GDAL without PNG. However, CMake errors out with the following error message even if I use `-DGDAL_USE_PNG=OFF`:
```
CMake Error at gdal.cmake:478 (target_link_libraries):
  Target "GDAL" links to:

    PNG::PNG

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

Call Stack (most recent call first):
  CMakeLists.txt:218 (include)
```

## Steps to reproduce the problem.

Make sure you're on a system where PNG isn't installed. Then run:
```console
$ git clone https://github.com/OSGeo/gdal.git
$ cd gdal
$ cmake . -DGDAL_USE_PNG=OFF
```

## Operating system

macOS 12.4 (Apple M1 Pro)

## GDAL version and provenance

The 3.5.0 version built from source with Spack.

Full build logs:

* [build log](https://github.com/OSGeo/gdal/files/8983634/spack-build-out.txt)
* [build env](https://github.com/OSGeo/gdal/files/8983635/spack-build-env-mods.txt)

**Comment by adamjstewart** [comment]
Looks like this is also the case in the old Autotools build system. Configure passes, but make fails:
```
JPNG_band.cpp:27:10: fatal error: 'png.h' file not found
#include <png.h>
         ^~~~~~~
1 error generated.
make[2]: *** [../../GDALmake.opt:668: ../o/JPNG_band.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
```
Build logs for 3.4.3:

* [build log](https://github.com/OSGeo/gdal/files/8983642/spack-build-out.txt)
* [build env](https://github.com/OSGeo/gdal/files/8983643/spack-build-env-mods.txt)

I know the Autotools build system is no longer supported, just wanted to point out that this bug has existed long before you moved to CMake.

**Comment by rouault** [comment]
Has been fixed in master and 3.5 branch (after 3.5.0) per https://github.com/OSGeo/gdal/pull/5744

**Comment by adamjstewart** [comment]
Thanks! I see that PR also touches zlib. Is zlib not supposed to be required, or am I reading that wrong? From what I can tell so far, proj, zlib, libtiff, libgeotiff, and json-c are the only required (either external or internal) dependencies.

**Comment by rouault** [comment]
> proj, zlib, libtiff, libgeotiff, and json-c are the only required (either external or internal) dependencies.

yes, as well as libqhull_r

**Comment by adamjstewart** [comment]
Really? I managed to build GDAL without qhull (either internal or external).

**Comment by rouault** [comment]
> Really? I managed to build GDAL without qhull (either internal or external).

turns out I was wrong :-) Yes, it is indeed optional.
