### ISSUE TITLE
macos installation error: 'numpy' has no attribute '__version__'

### ISSUE THREAD

**Issue by kipintouch** [OSGeo/gdal#6012]
## Expected behavior and actual behavior.

I am trying to install GDAL on mac os (details below) with *homebrew* via 
```
brew install gdal
```

All dependencies are installed correctly, including rebuilding python@3.9.
I am getting errors in installation of `swig`. After digging around, i noticed that the error is in how `setup.py` in `gdal/swig/python`
[looks up numpy version](https://github.com/OSGeo/gdal/blob/master/swig/python/setup.py#L81)

Homebrew installs `python-numpy` as a dependency for `GDAL`. My current version is `1.23`

Error Statement

```
==> /Users/user.name/opt/homebrew/opt/python@3.9/bin/python3 -c import setuptools... --no-user-cfg install --prefix=/Users/user.name/opt/homebrew/Cellar/gdal/3.5.0_1 --install-scripts=/Users/user.name
Last 15 lines from /Users/user.name/Library/Logs/Homebrew/gdal/04.python3:
__file__ = 'setup.py'
exec(compile(getattr(tokenize, 'open', open)(__file__).read()
  .replace('\r\n', '\n'), __file__, 'exec'))
--no-user-cfg
install
--prefix=/Users/user.name/opt/homebrew/Cellar/gdal/3.5.0_1
--install-scripts=/Users/user.name/opt/homebrew/Cellar/gdal/3.5.0_1/bin
--single-version-externally-managed
--record=installed.txt

Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "setup.py", line 81, in <module>
    numpy_major = numpy.__version__.split('.')[0]
AttributeError: module 'numpy' has no attribute '__version__'

Do not report this issue to Homebrew/brew or Homebrew/core!%
```

## Operating system

*Output from config.log*

uname -m = x86_64
uname -r = 21.5.0
uname -s = Darwin
uname -v = Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64

/usr/bin/uname -p = i386
/bin/uname -X     = unknown

/bin/arch              = unknown
/usr/bin/arch -k       = unknown
/usr/convex/getsysinfo = unknown
/usr/bin/hostinfo      = Mach kernel version:
	 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64
Kernel configured for up to 16 processors.
8 processors are physically available.
16 processors are logically available.
Processor type: x86_64h (Intel x86-64h Haswell)
Processors active: 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15
Primary memory available: 16.00 gigabytes
Default processor set: 556 tasks, 2260 threads, 16 processors
Load average: 1.77, Mach factor: 14.22
/bin/machine           = unknown
/usr/bin/oslevel       = unknown
/bin/universe          = unknown

PATH: /Users/user.name/opt/homebrew/Library/Homebrew/shims/mac/super
PATH: /Users/user.name/opt/homebrew/opt/pkg-config/bin
PATH: /Users/user.name/opt/homebrew/opt/epsilon/bin
PATH: /Users/user.name/opt/homebrew/opt/expat/bin
PATH: /Users/user.name/opt/homebrew/opt/geos/bin
PATH: /Users/user.name/opt/homebrew/opt/giflib/bin
PATH: /Users/user.name/opt/homebrew/opt/zstd/bin
PATH: /Users/user.name/opt/homebrew/opt/gcc/bin
PATH: /Users/user.name/opt/homebrew/opt/libaec/bin
PATH: /Users/user.name/opt/homebrew/opt/hdf5/bin
PATH: /Users/user.name/opt/homebrew/opt/jpeg/bin
PATH: /Users/user.name/opt/homebrew/opt/icu4c/bin
PATH: /Users/user.name/opt/homebrew/opt/libxml2/bin
PATH: /Users/user.name/opt/homebrew/opt/openssl@1.1/bin
PATH: /Users/user.name/opt/homebrew/opt/libdap/bin
PATH: /Users/user.name/opt/homebrew/opt/libtiff/bin
PATH: /Users/user.name/opt/homebrew/opt/proj/bin
PATH: /Users/user.name/opt/homebrew/opt/libgeotiff/bin
PATH: /Users/user.name/opt/homebrew/opt/libpng/bin
PATH: /Users/user.name/opt/homebrew/opt/krb5/bin
PATH: /Users/user.name/opt/homebrew/opt/libpq/bin
PATH: /Users/user.name/opt/homebrew/opt/sqlite/bin
PATH: /Users/user.name/opt/homebrew/opt/netcdf/bin
PATH: /Users/user.name/opt/homebrew/opt/numpy/bin
PATH: /Users/user.name/opt/homebrew/opt/little-cms2/bin
PATH: /Users/user.name/opt/homebrew/opt/openjpeg/bin
PATH: /Users/user.name/opt/homebrew/opt/pcre2/bin
PATH: /Users/user.name/opt/homebrew/opt/freetype/bin
PATH: /Users/user.name/opt/homebrew/opt/fontconfig/bin
PATH: /Users/user.name/opt/homebrew/opt/gettext/bin
PATH: /Users/user.name/opt/homebrew/opt/pcre/bin
PATH: /Users/user.name/opt/homebrew/opt/gdbm/bin
PATH: /Users/user.name/opt/homebrew/opt/xz/bin
PATH: /Users/user.name/opt/homebrew/opt/python@3.9/bin
PATH: /Users/user.name/opt/homebrew/opt/glib/bin
PATH: /Users/user.name/opt/homebrew/opt/cairo/bin
PATH: /Users/user.name/opt/homebrew/opt/nspr/bin
PATH: /Users/user.name/opt/homebrew/opt/nss/bin
PATH: /Users/user.name/opt/homebrew/opt/jpeg-turbo/bin
PATH: /Users/user.name/opt/homebrew/opt/webp/bin
PATH: /Users/user.name/opt/homebrew/opt/qt@5/bin
PATH: /Users/user.name/opt/homebrew/opt/poppler-qt5/bin
PATH: /Users/user.name/opt/homebrew/opt/m4/bin
PATH: /Users/user.name/opt/homebrew/opt/libtool/bin
PATH: /Users/user.name/opt/homebrew/opt/unixodbc/bin
PATH: /Users/user.name/opt/homebrew/opt/xerces-c/bin
PATH: /usr/bin
PATH: /bin
PATH: /usr/sbin
PATH: /sbin

## GDAL version and provenance

Version = 3.5.0

**Comment by rouault** [comment]
Looking at https://stackoverflow.com/questions/50311096/attributeerror-module-numpy-has-no-attribute-version, I suspect something broken in your installation

**Comment by kipintouch** [comment]
Not sure why Homebrew adds `numpy` as dependency for GDAL since it does not install it. { in my case,  the system python version (3.10) is different from what GDAL formula says (3.9) }.

For everybody else, you have to install `numpy` via pip for the python version installed via GDAL. 
`/path/to/gdal/python -m pip install numpy`
