### ISSUE TITLE
fatal error: 'linux/userfaultfd.h' on macOS

### ISSUE THREAD

**Issue by TacomaGranny** [OSGeo/gdal#6049]
## Expected behavior and actual behavior.

CMake failure on Darwin: 
 builld/CMakeFiles/CMakeTmp/CheckIncludeFile.c:1:10: fatal error: 'linux/userfaultfd.h'
 Should not be a requirement in macOS

## Steps to reproduce the problem.

Run CMake on macOS 12.4.
 error message in CMakeError.log
 
Performing C++ SOURCE FILE Test DEPRECATE_SPRINTF failed with the following output:
Change Dir: /Users/Shared/AppDev/GIS/GDAL/gdal-3.5.1/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/local/bin/gmake -f Makefile cmTC_36d53/fast && /usr/local/bin/gmake  -f CMakeFiles/cmTC_36d53.dir/build.make CMakeFiles/cmTC_36d53.dir/build
gmake[1]: Entering directory '/Users/Shared/AppDev/GIS/GDAL/gdal-3.5.1/build/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_36d53.dir/src.cxx.o
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -DDEPRECATE_SPRINTF  -std=c++17 -O2 -W -arch x86_64    -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=12.0 -std=gnu++11 -MD -MT CMakeFiles/cmTC_36d53.dir/src.cxx.o -MF CMakeFiles/cmTC_36d53.dir/src.cxx.o.d -o CMakeFiles/cmTC_36d53.dir/src.cxx.o -c /Users/Shared/AppDev/GIS/GDAL/gdal-3.5.1/build/CMakeFiles/CMakeTmp/src.cxx
Linking CXX executable cmTC_36d53
/Users/Shared/AppDev/GTK/gtk/inst/bin/cmake -E cmake_link_script CMakeFiles/cmTC_36d53.dir/link.txt --verbose=1
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -std=c++17 -O2 -W -arch x86_64    -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=12.0 -Wl,-search_paths_first -Wl,-headerpad_max_install_names -L/Users/Shared/AppDev/GTK/gtk/inst/lib -lintl -ljpeg -lpng16 -L/usr/local/unixodbc/lib -lodbc -lodbcinst -L/usr/local/lib -liconv -larchive -lproj.22 -lfreexl -L/usr/local/PostgreSQL/14/lib -lpq -L/usr/local/mysql/lib -L/Library/Frameworks/Python.framework/Versions/3.10/lib -L/Applications/XCode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib -L/Applications/XCode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib/system -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/13.1.6/lib/darwin  CMakeFiles/cmTC_36d53.dir/src.cxx.o -o cmTC_36d53 
Undefined symbols for architecture x86_64:
  "_main", referenced from:
     implicit entry/start for main executable
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
gmake[1]: *** [CMakeFiles/cmTC_36d53.dir/build.make:100: cmTC_36d53] Error 1
gmake[1]: Leaving directory '/Users/Shared/AppDev/GIS/GDAL/gdal-3.5.1/build/CMakeFiles/CMakeTmp'
gmake: *** [Makefile:127: cmTC_36d53/fast] Error 2

Source file was:
#define _XOPEN_SOURCE
#include <vector>
#include <stdio.h>
extern "C"
 {int sprintf(char *str, const char* fmt, ...);}
Determining if the include file linux/userfaultfd.h exists failed with the following output:
Change Dir: /Users/Shared/AppDev/GIS/GDAL/gdal-3.5.1/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/local/bin/gmake -f Makefile cmTC_37bd7/fast && /usr/local/bin/gmake  -f CMakeFiles/cmTC_37bd7.dir/build.make CMakeFiles/cmTC_37bd7.dir/build
gmake[1]: Entering directory '/Users/Shared/AppDev/GIS/GDAL/gdal-3.5.1/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_37bd7.dir/CheckIncludeFile.c.o
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang   -fno-common -Wno-implicit-function-declaration -Wno-pointer-sign -Wno-implicit-fallthrough -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk    -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=12.0 -std=gnu99 -MD -MT CMakeFiles/cmTC_37bd7.dir/CheckIncludeFile.c.o -MF CMakeFiles/cmTC_37bd7.dir/CheckIncludeFile.c.o.d -o CMakeFiles/cmTC_37bd7.dir/CheckIncludeFile.c.o -c /Users/Shared/AppDev/GIS/GDAL/gdal-3.5.1/build/CMakeFiles/CMakeTmp/CheckIncludeFile.c
/Users/Shared/AppDev/GIS/GDAL/gdal-3.5.1/build/CMakeFiles/CMakeTmp/CheckIncludeFile.c:1:10: fatal error: 'linux/userfaultfd.h' file not found
#include <linux/userfaultfd.h>
         ^~~~~~~~~~~~~~~~~~~~~
1 error generated.
gmake[1]: *** [CMakeFiles/cmTC_37bd7.dir/build.make:79: CMakeFiles/cmTC_37bd7.dir/CheckIncludeFile.c.o] Error 1
gmake[1]: Leaving directory '/Users/Shared/AppDev/GIS/GDAL/gdal-3.5.1/build/CMakeFiles/CMakeTmp'
gmake: *** [Makefile:127: cmTC_37bd7/fast] Error 2

## Operating system

macOS Monterey, Darwin Kernel Version 21.5.0

## GDAL version and provenance

gdal-3.5.1
[CMakeError.log](https://github.com/OSGeo/gdal/files/9075509/CMakeError.log)

**Comment by rouault** [comment]
That's just an attempted feature check, which may succeed or fail depending on the platform. Errors in CMakeError.log are rarely true errors. If the config phase of CMake doesn't run with verbose errors on the standard error stream, then things are OK.
See https://github.com/OSGeo/gdal/runs/7252054262?check_suite_focus=true as an example of a successfull run on macOS.

**Comment by TacomaGranny** [comment]
It's a fatal error, not a warning. The CMake build stops at that point. If I comment it out of the CMake scripts, the build continues.
Besides being pointless on Darwin. Needs to be under Linux.

**Comment by rouault** [comment]
> The CMake build stops

The build or the cmake configuration phase ? Can you display the exact error displayed in the console ?
And what is the output of "grep USER CMakeCache.txt" ?

**Comment by dg0yt** [comment]
> CMakeError.log

This file logs stderr from configuration tests, so failures are expected. 
You are facing a different error, and it is printed to the console (stdout, stderr).
