### ISSUE TITLE
GDALBuildVrt output with -a_srs not as expected

### ISSUE THREAD

**Issue by OneChuck** [OSGeo/gdal#6070]
## Expected behavior and actual behavior.
As a test for a larger project I ran the following (see below) to create a VRT from a GeoTiff. The GeoTiff is in EPSG:32634 and `-a_srs` is set to EPSG:4326.

```
gdalbuildvrt -b 1 -resolution highest -a_srs EPSG:4326 -r nearest "output.vrt" "input.tif"
```
Inspecting the VRT in QGIS the CRS is reported as EPSG:4326 but the coordinates are reported in meters instead of degrees. Looking at the VRT in a text editor also show the `<GeoTransform>`  coordinates in meters and no subClass=”VRTWarpedDataset” is present.
My understanding of VRTs is that processing happens on-the-fly and, in this case, the VRT should have the CRS as EPSG:4326 and the coordinates (geotransform) should also be in degrees.

## Steps to reproduce the problem.
Run 
```
gdalbuildvrt -b 1 -resolution highest -a_srs EPSG:4326 -r nearest "output.vrt" "input.tif"
```
on the input.tif file that can be found [here](https://github.com/OneChuck/Build_vrt_data).

## Operating system
Windows 10 Pro

## GDAL version and provenance
GDAL version: 3.4.3
Wheel file from https://www.lfd.uci.edu/~gohlke/pythonlibs/

**Comment by rouault** [comment]
https://gdal.org/programs/gdalbuildvrt.html#cmdoption-gdalbuildvrt-a_srs is explicit : "Override the projection for the output file. [...]. No reprojection is done.". So it is mostly to fix or add a missing SRS information.
If you want to reproject you need to 2 in two steps:
- gdalbuildvrt -b 1 -resolution highest  -r nearest "output.vrt" "input.tif"
- gdalwarp -t_srs EPSG:4326 output.vrt output_warped.vrt

**Comment by OneChuck** [comment]
Thanks for clarifying. Was under the wrong impression of how gdalbuildvrt handles projections with `-a_srs`.
