### ISSUE TITLE
Improve errors from GTiff driver

### ISSUE THREAD

**Issue by sgillies** [OSGeo/gdal#6071]
While digging into https://github.com/rasterio/rasterio/issues/2053, it occurred to me that `IReadBlock failed` is not very useful to a programmer. It doesn't tell us if we can retry a call due to random failure or if the data file is corrupted. Consider the errors below.

```
ERROR 1: TIFFFillTile:No space for data buffer at scanline 4294967295
ERROR 1: TIFFReadEncodedTile() failed.
ERROR 1: /home/ubuntu/Documents/CDL_tiffs/2015_30m_cdls.tif, band 1: IReadBlock failed at X offset 189, Y offset 60: TIFFReadEncodedTile() failed.
```

What a programmer (well, me) wants to see is `No space for data buffer`. Which is still ambiguous, but hints that I might be able to retry the dataset read operation.

**Comment by rouault** [comment]
> What a programmer (well, me) wants to see is `No space for data buffer`

This error is emitted by libtiff (apparently when a malloc() fails), and re-emitted as an opaque string by GDAL. Neither libtiff nor GDAL have the concept of retriable errors (and I'm not completely sure the state of libtiff & GDAL allow retrying in the same session, as this is pretty much untested code paths).
I'm not sure how the concept of retriable could be communicated, perhaps through the CPLE_OutOfMemory error number ? But I guess there could be situations when a corrupted file contains a wrong very large tile/strip size, which causes an OutOfMemory situation, and there's no way that retrying would work.

**Comment by sgillies** [comment]
@rouault thanks! I think I misread that as being in libtiff while reading too quickly.

**Comment by sgillies** [comment]
I'm starting to figure out how to get the root errors within a GDAL function call https://github.com/rasterio/rasterio/pull/2526. I may be abusing [PEP 3134](https://peps.python.org/pep-3134/#explicit-exception-chaining)... I'll ask around about this.

**Comment by andrew-aitchison** [comment]
I am probably off-topic here, but to my mind the important information is "at scanline 4294967295"
Now  4294967295=-1 mod 2^32 which suggests that we have a signed/unsigned mismatch and a possible underflow.

**Comment by sgillies** [comment]
I'm going to close this. I've found a pretty good solution in rasterio that doesn't require any changes in GDAL.
