### ISSUE TITLE
gdalwarp USE_OPENCL memory leaks.

### ISSUE THREAD

**Issue by liminlu0314** [OSGeo/gdal#610]
## Expected behavior and actual behavior.

gdalwarp.exe use OpenCL and the memory leak.

## Steps to reproduce the problem.

gdalwarp.exe -r cubic -wo USE_OPENCL=YES C:\input.tif C:\output.tif

## Operating system

Windows 10

## GDAL version and provenance

2.2.3

##Patch
[in file gdalwarpkernel_opencl.cpp line [1765:]](https://github.com/OSGeo/gdal/blob/c0633e5f34e0be5c786c0ab539a59a2e04ca1e25/gdal/alg/gdalwarpkernel_opencl.cpp#L1765)
```c++
static
cl_int execute_kern(struct oclWarper *warper, cl_kernel kern, size_t loc_size)
{
...

#ifdef DEBUG_OPENCL
    handleErr(err = clGetEventProfilingInfo(ev, CL_PROFILING_COMMAND_START,
                                            sizeof(size_t), &start_time, nullptr));
    handleErr(err = clGetEventProfilingInfo(ev, CL_PROFILING_COMMAND_END,
                                            sizeof(size_t), &end_time, nullptr));
    assert(end_time != 0);
    assert(start_time != 0);
    handleErr(err = clReleaseEvent(ev));  //only release event on define DEBUG_OPENCL macro
    if (kern == warper->kern4)
        vecTxt = "(vec)";

    CPLDebug("OpenCL", "Kernel Time: %6s %10lu", vecTxt, (long int)((end_time-start_time)/100000));
#endif
    return CL_SUCCESS;
}
```
The code “handleErr(err = clReleaseEvent(ev)); ” should be placed before the “return CL_SUCCESS”.

**Comment by rouault** [comment]
Can you propose a pull request ?

**Comment by liminlu0314** [comment]
[I have submitted a pull request. ](https://github.com/OSGeo/gdal/pull/613)

**Comment by rouault** [comment]
Cherry-picked in 2.3 branch per 954f08f
