### ISSUE TITLE
Build issue on master with M1 Mac; linker error for CXX shared library

### ISSUE THREAD

**Issue by atchad** [OSGeo/gdal#6109]
## Expected behavior and actual behavior.

Attempting to build GDAL master on MacOS Monterey v12.4. I have an M1 chip which I'm assuming has something to do with the error I'm getting:
```
[ 87%] Linking CXX shared library libgdal.dylib
ld: can't map file, errno=22 file '/Library/Frameworks/rasterlite2.framework' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libgdal.31.3.6.0.dylib] Error 1
make[1]: *** [CMakeFiles/GDAL.dir/all] Error 2
make: *** [all] Error 2
```

## Steps to reproduce the problem.

Within a local GDAL master directory, `cmake .` passes but `cmake --build .`, fails with the error above.

## Operating system

MacOS Monterey v12.4 M1 chip

## GDAL version and provenance

Master branch

**Comment by rouault** [comment]
is /Library/Frameworks/rasterlite2.framework compatible of arm64 architecture ?
try "cmake -DGDAL_USE_RASTERLITE2=OFF" if you don't need rasterlite2 support
