### ISSUE TITLE
Reprojecting an image on the dateline results in a wide empty image

### ISSUE THREAD

**Issue by HGS-JoeDecker** [OSGeo/gdal#6112]
## Expected behavior and actual behavior.

I have an image on the dateline. I want to be able to convert this image to a googlemapscompatible cloud optimized geotiff.
When I attempt to reproject the image to EPSG:3857 the output image does not include the source image's content. Instead, it is a very wide image of the entire world excluding the original area of the source image.

## Steps to reproduce the problem.

[reproducedata.zip](https://github.com/OSGeo/gdal/files/9162478/reproducedata.zip)

Normally I use createcopy to generate a cog with TILING_SCHEME=GoogleMapsCompatible. However I was also able to reproduce the issue using gdal warp:

gdalwarp -s_src EPSG:32760 -t_srs EPSG:3857 -r near -f GTiff reproduce.dat OUTPUT.tif

## Operating system

Windows 10

## GDAL version and provenance

GDAL 3.4.2 and GDAL 3.5.1 built from source code.
I also tried in QGIS 3.18 which uses gdal 3.1.4.

**Comment by rouault** [comment]
> Instead, it is a very wide image of the entire world excluding the original area of the source image.

even if it worker correctly, it would be an impractically wide image. There's no much alternative than warping the west and east parts in 2 separate files.

**Comment by HGS-JoeDecker** [comment]
Thank you! I will close this out.
