### ISSUE TITLE
Setting DEBUG_VERBOSE macro inserts code with a typo

### ISSUE THREAD

**Issue by dnewhall** [OSGeo/gdal#6147]
We ran into a build issue with 3.5.1 and the current trunk/master that took us a bit of time to figure out.

If you set DEBUG_VERBOSE in one of the various *FLAGS variables (we had it in CURL_CFLAGS), GDAL won't build.

cpl_vsi_mem.cpp won't compile due to line 307:

#ifdef DEBUG_VERBOSE
        CPLDebug("VSIMEM", "Closing handle %p on %s: ref_count=%d (before)",
                 this, poFile->osFilename.c_str(), poFile.use_count());
#endif

VSIMemFile doesn't have a use_count method. I'm guessing it once did, but no one has built with DEBUG_VERBOSE since then?

**Comment by rouault** [comment]
Actually, there was an issue at line 955 with poFile->use_count() being wrongly used instead of poFile.use_count()
