### ISSUE TITLE
gdalwarp produces unexpected results operating on large raster files with some projections

### ISSUE THREAD

**Issue by tzakharko** [OSGeo/gdal#6155]
## Overview

When attempting to reproject [natural earth raster data](https://www.naturalearthdata.com/downloads/50m-raster-data/50m-natural-earth-2/) (NE2_50M_SR_W.tif) I ran into some inconsistent behaviour with `gdalwarp`. Reprojected images either have strange sizes or are cropped. But if I reduce the size of the input file using `gdal_translate`, everything works as expected. As I am a novice user, I cannot exclude that this is a user error, but given that the behaviour differs based on the image resolution (with the data and geographical metadata being the same) I decided to report it here.  

System information: M1 Apple MacBook Pro (ARM), GDAL 3.5.1 installed via HomeBrew

## Detailed description

These are the results I get with equal earth projection applied to the original 10800 × 5400 pixel image:

```
gdalwarp -t_srs ESRI:53037  -r near -dstalpha -wo SOURCE_EXTRA=1000  NE2_50M_SR_W.tif NE2_50M_SR_W_ea.tif
```

Produces a cropped image, with portions of the map removed on either sides

<details>
 <summary>Click to show image</summary>

![NE2_50M_SR_W_ea](https://user-images.githubusercontent.com/9529318/182546882-9b1e6385-a734-4b2c-bbbe-7b7535531808.jpg)

</details>

---

If however I reduce the size of the original file, everything works as expected, e.g.:

```
gdal_translate -r near -tr 0.1 0.1   NE2_50M_SR_W.tif NE2_50M_SR_W_small.tif
gdalwarp -t_srs ESRI:53037  -r near -dstalpha -wo SOURCE_EXTRA=1000  NE2_50M_SR_W_small.tif NE2_50M_SR_W_small_ea.tif
```

<details>
 <summary>Click to show image</summary>

![NE2_50M_SR_W_small_ea](https://user-images.githubusercontent.com/9529318/182547895-85d411c3-d94f-4f6c-952c-b13ccb867a2e.jpg)

</details>

Note that similar issues occur with some other projections I have tried (e.g. Mollweide following this [tutorial](https://medium.com/planet-stories/a-gentle-introduction-to-gdal-part-2-map-projections-gdalwarp-e05173bd710a)). The original issue report also mentioned Mercator projection, but that was an error on my part since I misconfigured the parameters — when removing polar caps the mercator projection works the same way for the large and small images.

**Comment by jratike80** [comment]
The odd looking result in the first case with output as EPSG:3395 https://epsg.org/crs_3395/WGS-84-World-Mercator.html? comes because the source image covers the whole World between  90°S and 90°N but the target CRS is valid only between 80°S and 84°N. Run gdalwarp with `-te` and remove the polar areas.

**Comment by tzakharko** [comment]
@jratike80 Thanks, this works! It seems I have conflated two unrelated issues (at least one of which was user error). I have edited the issue to remove mention of mercator as that was user error.
