### ISSUE TITLE
How to install gdal on geoserver to support img format

### ISSUE THREAD

**Issue by freemankevin** [OSGeo/gdal#6159]
I have tried for several days, but it has not been successful. I can compile gdal.jar normally, but the plug-in function cannot be displayed normally on the geoserver side.

**Comment by rouault** [comment]
This is probably more a question for the GeoServer.
Besides gdal.jar, you need to deploy the gdaljni .so/.dll and gdal .so/.dll native libraries in java.library.path and/or system path.

**Comment by freemankevin** [comment]
> 这可能是 GeoServer 的更多问题。 除了格达尔.jar，您需要部署格达尔杰尼.so/.dll 和格达尔java.library.path 和/或系统路径中的 .so/.dll 本机库。

Can you be specific, now our geoserver is running using container images, but the gdal module cannot be used anyway。
![image](https://user-images.githubusercontent.com/71524776/183541378-383124a4-48eb-46b4-a0f1-23bf1f94067f.png)
