### ISSUE TITLE
gdalwarp and gdal_translate bilinear interpolation sub-pixel shift around nodata

### ISSUE THREAD

**Issue by cefect** [OSGeo/gdal#6166]
## Expected behavior and actual behavior.

for bilinear interpolation, I expect cells with data and nodata to be in the same location in the result (as with nearest neighbour or GRASS's r.resamp.interp). I get the same behavior with gdal_translate.

original:
![image](https://user-images.githubusercontent.com/47092034/183245225-2d9e4d2a-d9e6-41a0-8157-c3162ad938e8.png)

warped:
![image](https://user-images.githubusercontent.com/47092034/183245236-43e859be-1d27-452d-818c-5fc21538677c.png)

## Steps to reproduce the problem.
I tried with a few rasters and got the same issue, but [here's a test raster](https://drive.google.com/file/d/19HuT_M1T6oLY9LTo1Z39-pOjTDIxAz0b/view?usp=sharing).

gdalwarp -r bilinear -of GTiff scratch.tif result.tif

## Operating system

Windows 10

## GDAL version and provenance

GDAL/OGR version 3.5.0

Thank you for your help,

**Comment by rouault** [comment]
I don't see any issue here. The shape and location of pixels in the source and target raster di not match, per design of gdalwarp which outputs square pixels by default. So they don't overlap, and when zooming a lot, you will necessary have some gaps around nodata areas. Can't see how it could be different. Just a property of raster being discrete representations. If you increased the target resolution a lot, the gap would tend towards zero

**Comment by cefect** [comment]
Thank you for the feedback @rouault. 

I'm a bit confused by your response however. Perhaps the following will clarify:

- there is no change of resolution or CRS specified in my gdalwarp call. 
- gdalwarp returns the (closer to) expected result with -r near (see below)
- zooming in/out has no affect

Using a simpler test case [lay1](https://drive.google.com/file/d/1KVwJubBqNjTO_4_M4KZgQZ29YncKj50y/view?usp=sharing), 

![image](https://user-images.githubusercontent.com/47092034/183633022-137413d4-c079-489f-b66d-5b5b9fef5e50.png)

gdalwarp -r **near** -of GTiff lay1.tif OUTPUT.tif
![image](https://user-images.githubusercontent.com/47092034/183633101-60c2487e-d9b0-43b5-8216-26cd28344ba0.png)

gdalwarp -r **bilinear** -of GTiff lay1.tif OUTPUT.tif
![image](https://user-images.githubusercontent.com/47092034/183633227-19003682-40c4-426f-ac9d-4e9e9eb1e099.png)

Doing a bit more digging, I notice that gdalwarp is changing the resolution and extent slightly (despite me not passing -te or -tr):

**lay1** (original):
2164888.284, 139229.002, 2164914.182, 139253.390 [EPSG:3979] 13w x 12h (1.99216923, 2.03237500)

**warped** (near and bilinear)
2164888.284, 139229.261, 2164914.424, 139253.390 [EPSG:3979] 13w x 12h (2.01076631, 2.01076631)

From this, I found a simple workaround which is to warp first to nearest, then to bilinear. 

Regardless, I see two unexpected behaviors:
- change of resolution and extents absent relevant commands (and without warning)
- 'bilinear' resolving significantly different from 'near'

Thank you in advance for your feedback

**Comment by jratike80** [comment]
Even wrote that by gdalwarp is writing square pixels by default if user does not use the `-tr` option. In your case the source image does not have square pixels:
`Pixel Size = (10.008780952380977,-9.986650724638848)`
