### ISSUE TITLE
PROPOSAL: pre-commit for code lint checks

### ISSUE THREAD

**Issue by snowman2** [OSGeo/gdal#6167]
What are the current thoughts on using [pre-commit](https://github.com/pre-commit/pre-commit) for code linter support? The checks are run with each commit and can work as an as-you-go type thing. You can also run `pre-commit run --all-files`.

Examples:
- [pyproj: .pre-commit-config.yaml](https://github.com/pyproj4/pyproj/blob/master/.pre-commit-config.yaml)
- [xarray: .pre-commit-config.yaml](https://github.com/pydata/xarray/blob/main/.pre-commit-config.yaml)
- [pandas: .pre-commit-config.yaml](https://github.com/pandas-dev/pandas/blob/main/.pre-commit-config.yaml)

Here are some potentially useful ones:
- [black](https://github.com/psf/black) - really nice because it forces all programmers on the project to use the same code style regardless of our individual preferences
- [isort](https://github.com/timothycrosley/isort)
- [flake8](https://github.com/PyCQA/flake8)

**Comment by rouault** [comment]
> What are the current thoughts on using [pre-commit](https://github.com/pre-commit/pre-commit) for code linter support?

why not, although I'm not familar at all with it, but from a cursory review, this looks non intrusive. We should just make sure there isn't too much copy&paste / duplication between CI checks and pre-commit, to avoid updating one place and forgetting the other one
