### ISSUE TITLE
MSSQLSpatial: Bulk copy for multiple layers doesn't work

### ISSUE THREAD

**Issue by szekerest** [OSGeo/gdal#619]
## Expected behavior and actual behavior.

Uploading multiple layers raises an error:
ERROR 1: Failed to set identity insert on layer, [Microsoft][SQL Server Native C
lient 11.0][SQL Server]IDENTITY_INSERT is already ON for table 'kn2.dbo.par'. Ca
nnot perform SET operation for table 'dbo.bud'..
ERROR 1: Unable to write feature 1 from layer BUD.
ERROR 1: Terminating translation prematurely after failed
translation of layer BUD (use -skipfailures to skip errors)

## Steps to reproduce the problem.

1) create new mssql db
2) C:\OSGeo4W64/apps/gdal-dev/bin/ogr2ogr -f MSSQLSpatial --config
GDAL_DRIVER_PATH C:\OSGeo4W64\apps\gdal-dev\bin\gdalplugins --config
MSSQLSPATIAL_LIST_ALL_TABLES YES %connstr% %filedb%

## Operating system

Windows 10

## GDAL version and provenance

master

**Comment by landam** [comment]
Tested, works. Thanks for quick fix! @szekerest Are you planning backport to release/2.3 and probably also release/2.2 branches?

**Comment by rouault** [comment]
I've cherry-picked   e12742473a0bcbc666302f74f4f93e5fbccf36d4 ,    6ac2a69aa302181cb64b90fdc5934e9b24fd76c3 and     6001cd6f5df377063166c2d40abb0e795e7427a7 as 
eb9f38ed0b59555a745cf11fe42ae16f64b58b3c in release/2.3

**Comment by szekerest** [comment]
Many thanks

**Comment by landam** [comment]
Thanks to all, I am taking liberty to close issue. Feel free to reopen if needed.
