### ISSUE TITLE
Static linking ECW 5.5 broken on Windows?

### ISSUE THREAD

**Issue by dnewhall** [OSGeo/gdal#6190]
As far as we can tell, statically linking the ECW 5.5 libraries just doesn't work on Windows.

We built GDAL 3.5.1 using nmake with the following changes to nmake.opt:
(In short: You have to add -DNCSECW_STATIC_LIBS to ECWFLAGS and ECW_LIB_LINK_SUFFIX = S)

ECWDIR = "C:/Hexagon/ERDAS ECW JPEG 2000 SDK 5.5.0/Desktop Read-Only"
ECW_MAJOR_MINOR_VERSION = 55

ECW_INCLUDES = -I$(ECWDIR)/include \
       -I$(ECWDIR)/include/NCSEcw/API -I$(ECWDIR)/include/NCSEcw/JP2 \
       -I$(ECWDIR)/include/NCSEcw/ECW

#ECW_ENABLE_COMPRESSION = -DHAVE_COMPRESS
#ECWFLAGS = -DECWSDK_VERSION=$(ECW_MAJOR_MINOR_VERSION) $(ECW_ENABLE_COMPRESSION) $(ECW_INCLUDES)
ECWFLAGS = -DECWSDK_VERSION=$(ECW_MAJOR_MINOR_VERSION) $(ECW_ENABLE_COMPRESSION) $(ECW_INCLUDES) -DNCSECW_STATIC_LIBS
ECW_LIB_LINK_SUFFIX = S
ECWLIB = $(ECWDIR)\lib\$(ECW_PLATFORM_TOOLSET_DIR)\$(ECW_PLATFORM_DIR)\NCSEcw$(ECW_LIB_LINK_SUFFIX).lib

When we load in the resulting gdal305.dll and try to call GDALOpen, we get a null pointer access with the following stack trace:

	gdal305.dll!NCSMalloc(unsigned int iSize, unsigned char bClear) Line 94	C++
	gdal305.dll!NCSStrDupT(const wchar_t * pString) Line 282	C++
	gdal305.dll!NCSGetTempDirectoryW() Line 1941	C++
	[Inline Frame] gdal305.dll!NCS::SDK::CConfig::Reset() Line 163	C++
	gdal305.dll!NCS::SDK::CConfig::CConfig() Line 89	C++
	gdal305.dll!NCS::SDK::CGlobalInfo::CGlobalInfo() Line 27	C++
	gdal305.dll!NCS::SDK::CFileBase::CFileFactory::CFileFactory() Line 72	C++
	[Inline Frame] gdal305.dll!NCS::SDK::CFileBase::CFileFactoryHelper::{ctor}() Line 828	C++
	gdal305.dll!NCS::SDK::CFileBase::sFilesHelper() Line 857	C++
	[Inline Frame] gdal305.dll!NCS::SDK::CFileBase::sFiles() Line 225	C++
	[Inline Frame] gdal305.dll!NCS::SDK::CFileBase::sConfig() Line 234	C++
	gdal305.dll!NCSSetConfig(NCSConfigType eType, ...) Line 73	C++
	gdal305.dll!ECWInitialize() Line 3477	C++
	gdal305.dll!ECWDataset::Open(GDALOpenInfo * poOpenInfo, int bIsJPEG2000) Line 2629	C++
	gdal305.dll!GDALOpenEx(const char * pszFilename, unsigned int nOpenFlags, const char * const * papszAllowedDrivers, const char * const * papszOpenOptions, const char * const * papszSiblingFiles) Line 3514	C++
	gdal305.dll!GDALOpen(const char * pszFilename, GDALAccess eAccess) Line 3243	C++
	tifutil11_x64.dll!GeoImgUtil::readGeolocationInfo(CSCGL::Vector2D * uVec, CSCGL::Vector2D * vVec, CSCGL::Point2D * ulCenPt, int * pxWdt, int * pxHgt, const csString & imgPath) Line 1486	C++

The code that triggers this is frmts\ecw\ecsdataset.cpp:3470:

#if ECWSDK_VERSION>= 50
    NCSecwSetConfig(NCSCFG_ECWP_CLIENT_HTTP_USER_AGENT,
                    "ECW GDAL Driver/" NCS_ECWJP2_FULL_VERSION_STRING_DOT_DEL);
#endif

Best guess from the stack trace is there's a null pointer in the ECW library itself while allocating the string for the temporary directory when loading the ECW-specific config options.

Calling apps/gdalinfo.exe --formats returns:
  ...
  ECW -raster- (rov): ERDAS Compressed Wavelets (SDK 5.5)
  JP2ECW -raster,vector- (rov): ERDAS JPEG2000 (SDK 5.5)
  ...

So the ECW driver is in there, but then when you call, for example, apps/gdalinfo.exe --mm example.ecw you get no output and $LASTERRORCODE is garbage.

ECW support works with dynamic linking, but static linking appears to be broken.

**Comment by rouault** [comment]
nmake builds have been removed in GDAL master, and they are in a frozen state in the 3.5 maintenance branch.
Ca you try cmake builds instead ? But I wouldn't be surprised that static linking of the ECW SDK doesn't work.
