### ISSUE TITLE
When building Gdal emits some errors U1050 , MSB3073 , MSB1009 on MSVC

### ISSUE THREAD

**Issue by nnfdnkns** [OSGeo/gdal#6200]
Hi All,
When building Gdal emits some errors U1050 , MSB3073 , MSB1009 on MSVC.Could you please help look at this issue?

## Expected behavior and actual behavior.
Expected behavior：build successful
actual behavior：build failed

For example (please modify !!!): I expected to be able to open this raster file (with a link to
the raster file, or it as an attachment) and it returns an error message
instead.

## Steps to reproduce the problem.
1.git clone https://github.com/OSGeo/gdal F:\gitP\OSGeo\gdal
2.cd F:\gitP\OSGeo\gdal
3.msbuild /m /p:Platform=Win32 /p:Configuration=Release /p:WindowsTargetPlatformVersion=10.0.18362.0 gdal_vs2019_x86.vcxproj /t:Rebuild 2>&1
4.cd F:\gitP\OSGeo\gdal\autotest\cpp
5.msbuild /m /p:Platform=Win32 /p:Configuration=Release /p:WindowsTargetPlatformVersion=10.0.18362.0 gdal_vs2019_x86_test.vcxproj /t:Rebuild 2>&1

For example (please modify !!!): "gdalinfo myfile"

## Operating system
VS 2019 + Windows Server 2019
For example (please modify !!!): Ubuntu 16.04 64 bit

## GDAL version and provenance

For example (please modify !!!): the 2.2.3 version from ubuntugis-unstable PPA
**erro ifo**
  "F:\gitP\OSGeo\gdal\gdal_vs2019_x86.vcxproj" (Rebuild target) (1) ->
       (Rebuild target) -> 
         makefile.vc(6): fatal error U1050: PROJ_INCLUDE should be defined. PROJ >= 6 is a required dependency [F:\gitP\OSGeo\gdal\gdal_vs2019_x86.vcxproj]
         C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.MakeFile.Targets(54,5): error MSB3073: The command "nmake -f makefile.vc MSVC_VER=1920  clean && nmake -f makefile.vc MSVC_VER=1920" exited with code 2. [F:\gitP\OSGeo\gdal\gdal_vs2019_x86.vcxproj]
**log**
[build (1).log](https://github.com/OSGeo/gdal/files/9347321/build.1.log)

**Comment by rouault** [comment]
The error message says it all:

> makefile.vc(6): fatal error U1050: PROJ_INCLUDE should be defined. PROJ >= 6 is a required dependency

If you aren't familiar with building GDAL and/or C++ projects, I'd suggest you use pre-build binaries (cf https://gdal.org/download.html#windows). nmake builds are also now deprecated since GDAL 3.5, and using CMake builds is now strongly recommended. See https://gdal.org/build_hints.html
