### ISSUE TITLE
Compilation of GDAL on AWS ec2

### ISSUE THREAD

**Issue by mariolarochelle** [OSGeo/gdal#6206]
I have tried to compile GDAL 3.2.1 on ec2 with support for pg. Even if I have installed libpq, the configure script doesn't pick it up.

The expected behavior would be for this to compile correctly without any error messages.

I am using an ec2 instance and running current software.

Thanks

**Comment by rouault** [comment]
GDAL 3.2 is no longer supported. Please update to GDAL 3.5.1 with CMake build. You need to install the libpq-devel or the equivalent package from your distribution that provides the PostgreSQL client libpq-fe.h header
