### ISSUE TITLE
gdal2tiles.py - impossibility to generate tiles beyond zoom limit

### ISSUE THREAD

**Issue by nancim** [OSGeo/gdal#6207]
# Make some way to generate tiles beyond <q>native</q> zoom limit.

For years we could make tiles from zoom 2 all the way to zoom level 10.
Now even at the latest version there I find no way to generate tiles beyond <q>native</q> zoom limit level.

## Steps to reproduce the problem.
Image used is over whole of Slovenia (extent: [370000.0, 20000.0, 630000.0, 200000.0]) in EPSG:3912 geo-system. Sorry for long not so important print of gdalinfo. I tried to submit original tif file itself, but it is too big:

> E:\water-images\2021>gdalinfo 2021-colors.tif
> Driver: GTiff/GeoTIFF
> Files: 2021-colors.tif
> Size is 52000, 36000
> Coordinate System is:
> PROJCRS["MGI 1901 / Slovene National Grid",
>     BASEGEOGCRS["MGI 1901",
>         DATUM["MGI 1901",
>             ELLIPSOID["Bessel 1841",6377397.155,299.1528128,
>                 LENGTHUNIT["metre",1]]],
>         PRIMEM["Greenwich",0,
>             ANGLEUNIT["degree",0.0174532925199433]],
>         ID["EPSG",3906]],
>     CONVERSION["Slovene National Grid",
>         METHOD["Transverse Mercator",
>             ID["EPSG",9807]],
>         PARAMETER["Latitude of natural origin",0,
>             ANGLEUNIT["degree",0.0174532925199433],
>             ID["EPSG",8801]],
>         PARAMETER["Longitude of natural origin",15,
>             ANGLEUNIT["degree",0.0174532925199433],
>             ID["EPSG",8802]],
>         PARAMETER["Scale factor at natural origin",0.9999,
>             SCALEUNIT["unity",1],
>             ID["EPSG",8805]],
>         PARAMETER["False easting",500000,
>             LENGTHUNIT["metre",1],
>             ID["EPSG",8806]],
>         PARAMETER["False northing",-5000000,
>             LENGTHUNIT["metre",1],
>             ID["EPSG",8807]]],
>     CS[Cartesian,2],
>         AXIS["easting (Y)",east,
>             ORDER[1],
>             LENGTHUNIT["metre",1]],
>         AXIS["northing (X)",north,
>             ORDER[2],
>             LENGTHUNIT["metre",1]],
>     USAGE[
>         SCOPE["Cadastre, engineering survey, topographic mapping (large and medium scale)."],
>         AREA["Slovenia - onshore and offshore."],
>         BBOX[45.42,13.38,46.88,16.61]],
>     ID["EPSG",3912]]
> Data axis to CRS axis mapping: 1,2
> Origin = (370000.000000000000000,200000.000000000000000)
> Pixel Size = (5.000000000000000,-5.000000000000000)
> Metadata:
>   AREA_OR_POINT=Area
> Image Structure Metadata:
>   COMPRESSION=DEFLATE
>   INTERLEAVE=PIXEL
> Corner Coordinates:
> Upper Left  (  370000.000,  200000.000) ( 13d17'33.07"E, 46d55'53.46"N)
> Lower Left  (  370000.000,   20000.000) ( 13d20'30.58"E, 45d18'44.98"N)
> Upper Right (  630000.000,  200000.000) ( 16d42'26.93"E, 46d55'53.46"N)
> Lower Right (  630000.000,   20000.000) ( 16d39'29.42"E, 45d18'44.98"N)
> Center      (  500000.000,  110000.000) ( 15d 0' 0.00"E, 46d 8' 4.01"N)
> Band 1 Block=256x256 Type=Byte, ColorInterp=Red
>   Mask Flags: PER_DATASET ALPHA
> Band 2 Block=256x256 Type=Byte, ColorInterp=Green
>   Mask Flags: PER_DATASET ALPHA
> Band 3 Block=256x256 Type=Byte, ColorInterp=Blue
>   Mask Flags: PER_DATASET ALPHA
> Band 4 Block=256x256 Type=Byte, ColorInterp=Alpha

Such file is then used in gdal2tiles (within OSGeo4W Shell):

> E:\water-images>gdal2tiles --profile raster --s_srs "EPSG:3912" --zoom 2-10 --no-kml --webviewer openlayers --processes=8 "2021\2021-colors.tif" "2021\tiles" --exclude
> **Clamping max zoom level to 8**
> Generating Base Tiles:

I expected some way or argument to be able to generate zoom levels 9 and 10 like for years before. But now we do have <q>native</q> zoom limit and are unable to do so.

This GDAL/OGR is installed from [download QGIS](https://www.qgis.org/en/site/forusers/download.html) site for Windows 10. I used [OSGeo4W Network Installer](https://download.osgeo.org/osgeo4w/v2/osgeo4w-setup.exe).

## Operating system
> Windows 10 Pro 21H1

## GDAL version and provenance
> GDAL 3.5.1, released 2022/06/30

**Comment by rouault** [comment]
Related past changes:
- https://github.com/OSGeo/gdal/commit/c5ca6eae321f6480471c970c701d5a490d4fd0d8
- https://github.com/OSGeo/gdal/pull/2808
