### ISSUE TITLE
GDALTranslate reports heap corruption when built with VS2019 and supplying srcwin parameter

### ISSUE THREAD

**Issue by bowie-eyes** [OSGeo/gdal#6218]
A heap corruption (as reported by VS2019) appears to happen within the GDALTranslate method of gdal_translate_lib, but only when supplying the -srcwin parameter.

Using VS2019, I have built a copy of gdal_translate (using unmodified code directly from the 3.5.1 tag), and attached the debugger.    I pass the following parameters to gdal_translate:
```
-srcwin 0 0 1024 1024 -of PNG testing.xml testing.png
```

Contents of "testing.xml":
```
<GDAL_WMS>
     <Service Name="AGS">
          <ServerUrl>https://itnternal-arcgis:6443/arcgis/rest/services/CapeBreton/SydneyCapeBreton_WebMerc/MapServer</ServerUrl>
          <SRS>EPSG:3857</SRS>
          <Layers>Sydney-WebMerc.tiff</Layers>
     </Service>
     <DataWindow>
          <UpperLeftX>-6705373.0973476423</UpperLeftX>
          <UpperLeftY>5807599.2296817359</UpperLeftY>
          <LowerRightX>-6697713.5854136115</LowerRightX>
          <LowerRightY>5799343.0820812639</LowerRightY>
          <SizeX>6413</SizeX><SizeY>6912</SizeY>
     </DataWindow>
     <MaxConnections>8</MaxConnections>
     <Timeout>30</Timeout>
     <BandsCount>4</BandsCount>
</GDAL_WMS>
```

The executable throws a heap corruption exception and terminates just as the call to GDALTranslate completes.  Interestingly, the file "testing.png" is created, and contains the expected raster data.  If gdal_translate is called from the commandline, and not in a debugging session, you are not given any indication it has had an exception, making it appear as if it completed without issue.  If you modify gdal_translate_bin, and try output something AFTER it calls GDALTranslate, nothing will appear as it has terminated early.

I have been able to replicate this using a build of the GDAL I've done myself, as well as against the VS2019 build supplied from GISInternals. 

This seems to only happen when supplying the srcwin parameter.  Supplying the projwin parameter completes successfully, without throwing any sort of exception. 

This does not appear to happen on builds for linux/android; only if the code is built with VS2019.

**Comment by rouault** [comment]
Please provide a reproducer that uses a public ArcGIS server (or any other WMS-like source)

**Comment by bowie-eyes** [comment]
Sure.  I can replicate the issue (seemingly) with all services.  For example, I can see it happening when connecting to a public service as follows:

```
<GDAL_WMS><Service Name="AGS"> 
    <ServerUrl>https://sampleserver6.arcgisonline.com/arcgis/rest/services/USA/MapServer</ServerUrl>
     <SRS>EPSG:3857</SRS>
     <Layers>Cities, Highways, States, Counties</Layers></Service>
     <DataWindow>
          <UpperLeftX>-9754890.7706770822</UpperLeftX>
          <UpperLeftY>4585847.2883809805</UpperLeftY>
          <LowerRightX>-9393687.6456414424</LowerRightX>
          <LowerRightY>4190823.2522050445</LowerRightY>
          <SizeX>4725</SizeX><SizeY>5167</SizeY>
     </DataWindow>
     <MaxConnections>8</MaxConnections>
     <Timeout>30</Timeout>
     <BandsCount>4</BandsCount>
</GDAL_WMS>
```

Sample project (just gdal_translate_bin and gdal_translate_lib wrapped in a VS2019 solution):
[GDAL_Translate_VS2019.zip](https://github.com/OSGeo/gdal/files/9381318/GDAL_Translate_VS2019.zip)

Using the sample project, I launch the debug project with the parameters provided.  Everything proceeds as normally until one of two points:

1.  Line 2334 of gdal_translate_lib, where the virtual dataset is closed (it is almost always this one)

or

2.  Line 371 of gdal_translate_bin, where the returned dataset is closed (if I choose to output a VRT instead of a PNG/etc)

For the test, I used the GIS Internals release-1928-x64-dev kit, along with their matching binaries (the same thing happens if I build my own version of the GDAL).  I can also see that it terminates after calling GDALTranslate, by either placing a breakpoint after the call, or writing to the console sometime after.  Neither will be hit.

I target Win 10 SDK 10.0.17763.0, and I'm using the v142 build tools.

**Comment by bowie-eyes** [comment]
From what I can see, something may be happening after the band(s) are copied to the VRTSimpleSource.  From that point forward, closing the dataset can cause the heap corruption exception.

**Comment by rouault** [comment]
I don't reproduce this with my Windows GDAL custom builds using Conda, neither with gisinternals https://download.gisinternals.com/sdk/downloads/release-1928-x64-gdal-3-5-1-mapserver-7-6-4.zip

Beow full log of a run with gisinternals builds, and adding "&& echo Success!" to check that the process has correctly terminated
```
C:\dev\release-1928-x64-gdal-3-5-1-mapserver-7-6-4>gdal_translate z:/test.xml -srcwin 0 0 1024 1024 -of PNG testing.png --debug on && echo Success!
GDAL: Auto register C:\dev\release-1928-x64-gdal-3-5-1-mapserver-7-6-4\bin\gdal\plugins\gdal_BAG.dll using GDALRegister_BAG.
GDAL: Auto register C:\dev\release-1928-x64-gdal-3-5-1-mapserver-7-6-4\bin\gdal\plugins\gdal_ECW_JP2ECW.dll using GDALRegister_ECW_JP2ECW.
GDAL: Auto register C:\dev\release-1928-x64-gdal-3-5-1-mapserver-7-6-4\bin\gdal\plugins\gdal_FITS.dll using GDALRegister_FITS.
GDAL: Auto register C:\dev\release-1928-x64-gdal-3-5-1-mapserver-7-6-4\bin\gdal\plugins\gdal_HDF4.dll using GDALRegister_HDF4.
GDAL: Auto register C:\dev\release-1928-x64-gdal-3-5-1-mapserver-7-6-4\bin\gdal\plugins\gdal_HDF4Image.dll using GDALRegister_HDF4Image.
GDAL: Auto register C:\dev\release-1928-x64-gdal-3-5-1-mapserver-7-6-4\bin\gdal\plugins\gdal_HDF5.dll using GDALRegister_HDF5.
GDAL: Auto register C:\dev\release-1928-x64-gdal-3-5-1-mapserver-7-6-4\bin\gdal\plugins\gdal_HDF5Image.dll using GDALRegister_HDF5Image.
GDAL: Auto register C:\dev\release-1928-x64-gdal-3-5-1-mapserver-7-6-4\bin\gdal\plugins\gdal_KEA.dll using GDALRegister_KEA.
GDAL: Auto register C:\dev\release-1928-x64-gdal-3-5-1-mapserver-7-6-4\bin\gdal\plugins\gdal_MrSID.dll using GDALRegister_MrSID.
GDAL: Auto register C:\dev\release-1928-x64-gdal-3-5-1-mapserver-7-6-4\bin\gdal\plugins\gdal_netCDF.dll using GDALRegister_netCDF.
GDAL: Auto register C:\dev\release-1928-x64-gdal-3-5-1-mapserver-7-6-4\bin\gdal\plugins\gdal_PDF.dll using GDALRegister_PDF.
GDAL: Auto register C:\dev\release-1928-x64-gdal-3-5-1-mapserver-7-6-4\bin\gdal\plugins\ogr_AmigoCloud.dll using RegisterOGRAmigoCloud.
GDAL: GDALOpen(z:/test.xml, this=00000173AB68FFE0) succeeds as WMS.
Input file size is 4725, 5167
GDAL: GDALOpen(testing.png, this=00000173ABD47A80) succeeds as PNG.
GDAL: GDALDefaultOverviews::OverviewScan()
GDAL: GDALClose(testing.png, this=00000173ABD47A80)
GDAL: GDALOpen(z:/test.xml, this=00000173ABABEA30) succeeds as WMS.
GDAL: GDALClose(z:/test.xml, this=00000173ABABEA30)
GDAL: QuietDelete(testing.png) invoking Delete()
GDAL: GDALOpen(testing.png, this=00000173ABD46940) succeeds as PNG.
GDAL: GDALDefaultOverviews::OverviewScan()
GDAL: GDALClose(testing.png, this=00000173ABD46940)
GDAL: GDAL_CACHEMAX = 299 MB
HTTP: libcurl/7.79.1-DEV OpenSSL/1.1.1l zlib/1.2.11
HTTP: Requesting [1/1] https://sampleserver6.arcgisonline.com/arcgis/rest/services/USA/MapServer/export?f=image&bbox=-9754890.77067708%2C4507561.12367338%2C-9676610.98230957%2C4585847.28838098&size=1024%2C1024&imageSR=3857&bboxSR=3857&format=png&layers=Cities,%20Highways,%20States,%20Counties&transparent=false&time=
HTTP: Request [0] https://sampleserver6.arcgisonline.com/arcgis/rest/services/USA/MapServer/export?f=image&bbox=-9754890.77067708%2C4507561.12367338%2C-9676610.98230957%2C4585847.28838098&size=1024%2C1024&imageSR=3857&bboxSR=3857&format=png&layers=Cities,%20Highways,%20States,%20Counties&transparent=false&time= : status = 200, type = image/png, error = (null)
GDAL: GDALOpen(/vsimem/wms/00000173ABE896A0/wmsresult.dat, this=00000173ABE00680) succeeds as PNG.
GDAL: GDALClose(/vsimem/wms/00000173ABE896A0/wmsresult.dat, this=00000173ABE00680)
0...10...20...30...40...50...60...70...80...90...100 - done.
GDAL: GDALClose(testing.png, this=00000173ABDFFB00)
GDAL: GDALClose(z:/test.xml, this=00000173AB68FFE0)
GDAL: In GDALDestroy - unloading GDAL shared library.
Success!
```

**Comment by bowie-eyes** [comment]
I've moved to a personal (not corporate) machine to test again.  Using the above attached VS2019 solution, freshly downloaded GIS internal .libs and .dlls, I have rebuilt gdal_translate.  When running in debug mode via Visual Studio, I execute using the mentioned parameters.  The heap corruption exception occurs at the very end of GDALTranslate as expected.

I notice you are executing gdal_translate from the command line with the -debug parameter.  Could you attempt executing it via VS2019. using the VS2019 debugger instead?  In the previously attached solution, I had placed a printf statement at the end of gdal_translate_bin which should display: "I'm never reached if built with VS2019".  This output is never reached, and if I attempt to place a breakpoint anywhere after the call to GDALTranslate, it is never hit (as an exception has been raised).

I can replicate the "Success!" output you get as well; but that is because the echo happens outside the execution of the gdal_translate executable, making it appear as if it was successful.  I cannot get gdal_translate itself to output anything to the console, if I put the output after the call to GDALTranslate.   

I can see this exception raised inside VS2019 on multiple different machines.  My personal machine is running a completely different version of Win10 (Home, v21H2), different hardware, etc.

**Comment by rouault** [comment]
> I can replicate the "Success!" output you get as well; but that is because the echo happens outside the execution of the gdal_translate executable, making it appear as if it was successful.

If gdal_translate would crash, then Success wouldn't be executed

I've also tried running GDALTranslate() many times in the same process using Python bindings, and without issues:
```
(myenv) C:\dev\gdal_cmake\build_conda>python
Python 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from osgeo import gdal
>>> ds = gdal.Translate('testing.png', 'z:/test.xml', options='-srcwin 0 0 1024 1024')
>>> ds = None
>>> ds = gdal.Translate('testing.png', 'z:/test.xml', options='-srcwin 0 0 1024 1024')
>>> ds = None
>>> ds = gdal.Translate('testing.png', 'z:/test.xml', options='-srcwin 0 0 1024 1024')
>>> ds = None
>>>
```

In my Conda build, I've edited gdal_translate_bin.cpp to have a ``	printf("after GDALDestroy and before return nRetCode=%d\n", nRetCode);`` at the location indicated in the printf. And I get
```
(myenv) C:\dev\gdal_cmake\build_conda>gdal_translate z:/test.xml -srcwin 0 0 1024 1024 -of PNG testing.png --debug off && echo Success!
Input file size is 4725, 5167
0...10...20...30...40...50...60...70...80...90...100 - done.
after GDALDestroy and before return nRetCode=0
Success!
```

I strong suspect you've likely an issue of mixing different C runtimes, debug vs release, or something like that.

Closing as works-for-me
