### ISSUE TITLE
libgdal.so.30 error

### ISSUE THREAD

**Issue by havenerk** [OSGeo/gdal#6237]
## Expected behavior and actual behavior.

gdalinfo should return a usage message.  Instead, I get gdalinfo: symbol lookup error: /lib/libgdal.so.30: undefined symbol: opj_encoder_set_extra_options

## Steps to reproduce the problem.

Install gdal-bin

## Operating system

Ubuntu 22.04 x64, but not all Ubuntu 22.04 x64 systems.

## GDAL version and provenance

gdal-bin 3.4.1+dfsg-1build4 (gdalinfo does not work nor does any other gdal command)

**Comment by rouault** [comment]
> gdalinfo should return a usage message. Instead, I get gdalinfo: symbol lookup error: /lib/libgdal.so.30: undefined symbol: opj_encoder_set_extra_options

you've likekly a mismatch of libopenjp2 version: you've built against a libopenjp2 that is more recent than the one you're executed against
There's nothing gdal can do about that. That's a mechanism of the operating system

**Comment by havenerk** [comment]
Are you sure?  I have one system that works and one that doesn't.  They are both built against libopenjp2-7 2.0.4-6

**Comment by havenerk** [comment]
Never mind.  I found the stray install of libopenjp2.  In addition to 2.0.4-6.

**Comment by jef-n** [comment]
See also https://github.com/qgis/QGIS/issues/48685

**Comment by jambari** [comment]
I am about to unistall the geos, but I dont have any idea to do that.

**Comment by jratike80** [comment]
The ticket was closed as fixed in August 21, 2022. Perhaps you have some other issue that is alike.
