### ISSUE TITLE
OGR WFS3

### ISSUE THREAD

**Issue by tomkralidis** [OSGeo/gdal#626]
## Expected behavior and actual behavior.

OGR's WFS3 support seems to have issues interpreting (present) WFS3 response.
## Steps to reproduce the problem.
```bash
kralidist@geomet-dev-02:/data/geomet/dev/gdal/gdal/gdal$ /data/geomet/dev/gdal/bin/ogrinfo --version
GDAL 2.4.0dev-0e775c6, released 2018/99/99

kralidist@geomet-dev-02:/data/geomet/dev/gdal/gdal/gdal$ /data/geomet/dev/gdal/bin/ogrinfo
WFS3:http://geo.kralidis.ca/pygeoapi/collections
INFO: Open of `WFS3:http://geo.kralidis.ca/pygeoapi/collections'
      using driver `WFS3' successful.
ERROR 1: HTTP error code : 400
ERROR 1: {"description": "Invalid feature collection", "code":
"InvalidParameterValue"}
1: obs
2: ne_110m_populated_places_simple
3: lakes
4: countries

kralidist@geomet-dev-02:/data/geomet/dev/gdal/gdal/gdal$ /data/geomet/dev/gdal/bin/ogrinfo
WFS3:http://geo.kralidis.ca/pygeoapi/collections obs
INFO: Open of `WFS3:http://geo.kralidis.ca/pygeoapi/collections'
      using driver `WFS3' successful.
ERROR 1: HTTP error code : 400
ERROR 1: {"description": "Invalid feature collection", "code":
"InvalidParameterValue"}

Layer name: obs
Metadata:
  DESCRIPTION=Observations
  TITLE=Observations
Geometry: Unknown (any)
Feature Count: 0
Layer SRS WKT:
(unknown)
```

## Operating system

For example: Ubuntu 14.04 64 bit

## GDAL version and provenance

master (2018-05-17) built from source.

**Comment by rouault** [comment]
Now 'WFS3:http://geo.kralidis.ca/pygeoapi' will work (note that this is the endpoint without /collections)

I've noted 2 things with your endpoint:
* the obs layer returns invalid GeoJSON geometries: the x and y members are strings instead of numbers
* the countries layer returns non conformat GeoJSON features. There is a lack of "type": "Feature" in the feature objects.
