### ISSUE TITLE
ogr2ogr not laundering geometry column name

### ISSUE THREAD

**Issue by pdean** [OSGeo/gdal#6261]
## Expected behavior and actual behavior.

I've been converting geodatabase files to postgis for many years downloaded from qspatial.  Just recently I found that geometry fields changed from shape to SHAPE so I complained because now I have to double quote whenever I use those names.  Qspatial insist they haven't changed anything.  It seems that ogr2ogr has been sheltering me from the insanity of capital letters without my knowledge.  And no longer does!

## Steps to reproduce the problem.
ogr2ogr -progress -overwrite -skipfailures \
        -f "PostgreSQL" PG:"host=alarmpi3.local user=gis dbname=gis active_schema=qspatial " \
        -lco LAUNDER=yes \
        data.gpkg \
        --config PG_USE_COPY YES

## Operating system

Arch

## GDAL version and provenance

pacman -Qi gdal

Name            : gdal
Version         : 3.5.1-2

**Comment by jratike80** [comment]
I can confirm that the name of the geometry column is not laundered with my GDAL 3.6.0dev

<img width="111" alt="image" src="https://user-images.githubusercontent.com/1751612/186996903-f9ef7165-c2bf-4c80-860e-24ce703ee9c3.png">

A workaround is to define the name of the geometry field in the ogr2ogr command `-lco geometry_name=shape`

**Comment by pdean** [comment]
Thanks for confirming that.  And a simple workaround.
