### ISSUE TITLE
The GDAL_NUM_THREADS config item can effect when the output format is pdf. but the pdf format does not support multithreading.

### ISSUE THREAD

**Issue by ningfc** [OSGeo/gdal#6270]
I try to translate tif format raster to pdf, when I set GDAL_NUM_THREADS bigger than 1, and run gdal_translate.exe , the result pdf just has a part of.

```
set GDAL_NUM_THREADS=2
gdal_translate.exe -of PDF D:\GISData\Image\Cq-Pz-J48G051091.tif D:\GISData\Image\Cq-Pz-J48G051091_tr.pdf
```
![output1](https://user-images.githubusercontent.com/17332186/187344506-97221f7d-1e86-4ea6-8601-aeda1b3de0e0.png)

and then I unset GDAL_NUM_THREADS or set it's to 1, the result is OK as expected.

```
set GDAL_NUM_THREADS=
gdal_translate.exe -of PDF D:\GISData\Image\Cq-Pz-J48G051091.tif D:\GISData\Image\Cq-Pz-J48G051091_tr.pdf
```
or
```
set GDAL_NUM_THREADS=1
gdal_translate.exe -of PDF D:\GISData\Image\Cq-Pz-J48G051091.tif D:\GISData\Image\Cq-Pz-J48G051091_tr.pdf
```
![image](https://user-images.githubusercontent.com/17332186/187344579-a01b6de4-e598-4d91-88f1-5526710a522f.png)

I read the pdf driver code, the pdf does not support multithreading, so maybe we need to ignore this configuration when the output is pdf format.

## Operating system
Windows11
## GDAL version and provenance
3.3.2

**Comment by rouault** [comment]
> I read the pdf driver code, the pdf does not support multithreading,

This is indeed really surprising. Can you point to a source image that can reproduce the issue ? Or at least, paste the output of "gdalinfo D:\GISData\Image\Cq-Pz-J48G051091.tif"

**Comment by rouault** [comment]
@ningfc Any feedback regarding my above comment ?

**Comment by rouault** [comment]
closing due to lack of feedback
