### ISSUE TITLE
CMAKE_INSTALL_PREFIX not properly attributed to Python bindings

### ISSUE THREAD

**Issue by atchad** [OSGeo/gdal#6273]
## Expected behavior and actual behavior.

I expected to build GDAL with `-DCMAKE_INSTALL_PREFIX=/usr/local/bin`, and then install with `python3 setup.py`. Installation succeeds, however, Python is looking for `.dylib` files in an incorrect location upon import. 

```
>>> from osgeo import gdal
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/GDAL-3.6.0-py3.10-macosx-10.9-universal2.egg/osgeo/__init__.py", line 30, in swig_import_helper
    return importlib.import_module(mname)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 674, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1176, in create_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/GDAL-3.6.0-py3.10-macosx-10.9-universal2.egg/osgeo/_gdal.cpython-310-darwin.so, 0x0002): Library not loaded: '@rpath/libgdal.31.dylib'
  Referenced from: '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/GDAL-3.6.0-py3.10-macosx-10.9-universal2.egg/osgeo/_gdal.cpython-310-darwin.so'
  Reason: tried: '/usr/lib/libgdal.31.dylib' (no such file)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/GDAL-3.6.0-py3.10-macosx-10.9-universal2.egg/osgeo/__init__.py", line 46, in <module>
    _gdal = swig_import_helper()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/GDAL-3.6.0-py3.10-macosx-10.9-universal2.egg/osgeo/__init__.py", line 43, in swig_import_helper
    return importlib.import_module('_gdal')
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_gdal'
```
In the above it seems that `@rpath` is forcibly set to `/usr/lib` regardless of any CMake arguments.

<img width="778" alt="image" src="https://user-images.githubusercontent.com/47636540/187451680-1a611788-07b8-4f84-83b3-63c6c4a00850.png">

Installation is successful in the correct location `/usr/local/lib`

## Steps to reproduce the problem.

`sudo cmake .. -DCMAKE_BUILD_TYPE=Release -DPython_LOOKUP_VERSION=3.10.6 -DPython_ROOT=/Library/Frameworks/Python.framework/Versions/3.10 -DCMAKE_INSTALL_PREFIX=/usr/local/bin`
`sudo cmake --build .`
`sudo cmake --build . --target install`
`cd swig/python`
`python3 setup.py build`
`python3 setup.py install`

## Operating system

macOS Monterey 12.5.1

## GDAL version and provenance

`master`

**Comment by rouault** [comment]
you probably want to use the ``--rpath`` flag of ``python3 setup.py build_ext``
See https://wiki.hackzine.org/development/python/library-in-custom-path.html
One could argue perhaps that if CMAKE_INSTALL_RPATH is set, the automatic build of the extension should use it. Mac behaviour & habits are always strange to me...

**Comment by rcoup** [comment]
@atchad can you run `otool -L /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/GDAL-3.6.0-py3.10-macosx-10.9-universal2.egg/osgeo/_gdal.cpython-310-darwin.so` and `otool -l /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/GDAL-3.6.0-py3.10-macosx-10.9-universal2.egg/osgeo/_gdal.cpython-310-darwin.so | grep PATH -A3` and paste the results?

**Comment by atchad** [comment]
@rcoup sure thing
```
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/GDAL-3.6.0-py3.10-macosx-10.9-universal2.egg/osgeo/_gdal.cpython-310-darwin.so (architecture x86_64):
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1300.23.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.100.3)
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/GDAL-3.6.0-py3.10-macosx-10.9-universal2.egg/osgeo/_gdal.cpython-310-darwin.so (architecture arm64):
	@rpath/libgdal.31.dylib (compatibility version 31.0.0, current version 31.3.6)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1300.23.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.100.3)
```
No results from the second line you have there.

**Comment by rcoup** [comment]
Yeah, so there's no RPATH value set at all on the bindings dylib. 

> One could argue perhaps that if CMAKE_INSTALL_RPATH is set, the automatic build of the extension should use it.

Makes sense to me, but I'm not sure how we could achieve it?

Maybe a useful order of preference:
* Use `build_ext --rpath=` value
* Use `CMAKE_INSTALL_RPATH` value
* Use the path to `libgdal.dylib` (either via passing a full path to the linker, or setting the rpath)

**Comment by rouault** [comment]
> I passed the `--rpath` through and it still does not seem to work

please paste the exact commands you did, and the updated output of otool

**Comment by atchad** [comment]
`sudo python3 setup.py build_ext --rpath=/usr/local/lib install `

```
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/GDAL-3.6.0-py3.10-macosx-10.9-universal2.egg/osgeo/_gdal.cpython-310-darwin.so (architecture x86_64):
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1300.23.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.100.3)
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/GDAL-3.6.0-py3.10-macosx-10.9-universal2.egg/osgeo/_gdal.cpython-310-darwin.so (architecture arm64):
	@rpath/libgdal.31.dylib (compatibility version 31.0.0, current version 31.3.6)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 1300.23.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1311.100.3)
```
Still no output for the second `otool`

**Comment by atchad** [comment]
Just tried again using `sudo python3 setup.py build_ext --inplace --rpath /usr/local/lib install` and I'm still seeing the same results.

**Comment by atchad** [comment]
@rouault Finally got it to work after executing `sudo python3 setup.py build_ext --inplace --rpath=/usr/local/bin/lib --force install`. No other option other than `--force` worked. Seems a bit convoluted to have to do it that way.
