### ISSUE TITLE
Environment variable to prevent GDAL from using environment variables

### ISSUE THREAD

**Issue by hobu** [OSGeo/gdal#6280]
~For better or worse, a lot of GDAL's behavior is controlled via environment variables. Credentials, file system layout, application behavior, and available memory are all things that are articulated and controlled via environment variables. Environment variables are really useful for sidestepping application assumptions and altering GDAL's behavior from outside an application. Depending on the environment GDAL is running in, we may not want to allow that.~ 

~The solution to having too many environment variables is to add another, `GDAL_CONFIG_FILE`, that points to a file that GDAL uses to get all of its environment variable information.~

GDAL has `GDAL_CONFIG_FILE` as of 3.3. This ticket is about proposing another environment variable that prevents any other variables being provided via environment, and only being allowed via config file.

**Comment by rouault** [comment]
This strongly intersects with an existing capability: https://gdal.org/user/configoptions.html#gdal-configuration-file

What is mostly missing is an option in that config file to not take into account other environment variables

**Comment by hobu** [comment]
> What is mostly missing is an option in that config file to not take into account other environment variables

I missed that this is already available. But yes, I was most interested in disallowing configuration variables from being used at all from the environment.
