### ISSUE TITLE
TerraSAR COSAR v2 reading as incorrect data type

### ISSUE THREAD

**Issue by lsma604** [OSGeo/gdal#6289]
## Expected behavior and actual behavior.

I expect to be able to correctly read TerraSAR captures that are using the COSAR v2 format (from TanDEM-X CoSSC files).
Instead, the imagery that is read has incorrect I and Q values (likely incorrectly assumed integers rather than half-precision floats).

## Steps to reproduce the problem.

- Use GDAL to read a TerraSAR image of COSAR v2 format.

Unfortunately I cannot find any public example dataset for this.

## GDAL version and provenance

I have only been using GDAL through Orfeo Toolbox, so I have only tested this with GDAL v3.2.2.0 for Windows.

## What I believe the issue is

GDAL is reading COSAR v2 imagery as integers rather than half-precision floats.
See: https://tandemx-science.dlr.de/pdfs/TD-GS-PS-3028_TanDEM-X-Experimental-Product-Description_1.2.pdf
To fix this it would mean checking for the COSAR version when reading and change datatype accordingly.
I initially encountered this error with another library which has implemented a fix here:
https://github.com/ngageoint/sarpy/issues/339

**Comment by rouault** [comment]
@lsma604 could you confirm that https://github.com/OSGeo/gdal/pull/6312 fixes your issue ?

**Comment by lsma604** [comment]
> @lsma604 could you confirm that #6312 fixes your issue ?

Thank you! Yes, #6312 fixes the issue and COSAR v2 imagery is read correctly (half-precision floats).
