### ISSUE TITLE
Unable to create a file .gdb layer using creation options XML_DEFINITION or DOCUMENTATION when XML contains subtype and domain elements

### ISSUE THREAD

**Issue by adamgutons** [OSGeo/gdal#6299]
## Expected behavior and actual behavior.
I am trying to create a layer in a file geodatabase using an XML string that contains subtype and domain information, however an error message is returned when using the FileGDB driver.  The OpenFileGDB driver issues a warning when using the DOCUMENTATION layer creation option with an XML string containing subtype/domain information, but there are no fields in the output feature class table.  The same happens for OpenFileGDB even when using an XML string without subtype/domain information.

## Steps to reproduce the problem.

Using the FileGDB driver:
```
xml = r"C:\output\XMLEXPORT_Copy.XML"
driver = gdal.GetDriverByName("FileGDB")
ds = driver.Create(r"C:\output\testSubtypes.gdb")
with open(xml, 'r') as reader:
    xml_str = reader.read()
lyr = ds.CreateLayer("TrueTest", geom_type=ogr.wkbPoint, options=[f"XML_DEFINITION={xml_str}"])
ERROR 1: Failed at creating table for \TrueTest (General function failure.)
```
If the subtype information is removed (see attached XMLEXPORT_Copy_NOSubtypesDomains.XML), FileGDB driver creates the layer successfully with all expected fields.
<img width="195" alt="expected" src="https://user-images.githubusercontent.com/34498995/187960215-f116e6db-d369-4ab6-81b7-cd9d221d28ce.PNG">

Using the OpenFileGDB driver:
```
ds = gdal.GetDriverByName("OpenFileGDB").Create("testing2.gdb", 0,0,0, gdal.GDT_Unknown)
with open(xml, 'r') as reader:
    xml_str = reader.read()
lyr = ds.CreateLayer("TrueTest", geom_type=ogr.wkbPoint, options=[f"DOCUMENTATION={xml_str}"])
Warning 6: Normalized/laundered layer name: 'TrueTest' to 'TrueTest_1'
```
If the subtype information is removed (see attached XMLEXPORT_Copy_NOSubtypesDomains.XML), OpenFileGDB driver does not report Warning 6, and it appears that CreateLayer is successful.  However upon examining the file geodatabase there are only Shape and ObjectID fields:
<img width="239" alt="fields" src="https://user-images.githubusercontent.com/34498995/187957958-527eea47-ab91-456d-98bb-c88ff3953acf.PNG">

I have attached a zip folder to this ticket that contains the XML that I am using, one file contains the Subtype/Domain information, the other has this information removed.
## Operating system
Windows 10
Ubuntu 22.04

## GDAL version and provenance
FileGDB Driver - GDAL 3.4.2
OpenFileGDB Driver - GDAL 3.6.0dev-c387ba85a9
[test_xmls.zip](https://github.com/OSGeo/gdal/files/9471429/test_xmls.zip)

**Comment by rouault** [comment]
> If the subtype information is removed (see attached XMLEXPORT_Copy_NOSubtypesDomains.XML), FileGDB driver creates the layer successfully with all expected fields.

There's nothing we can do about the FileGDB driver. The closed-source SDK itself does the job, and when it doesn't want to do something, you just have to admit this is game over.

> Using the OpenFileGDB driver:

You cannot put field definition into the DOCUMENTATION creation option. It serves a completely different purpose. To create fields, you should use the Layer.CreateField() API. And for domains, the Dataset.AddFieldDomain() and Field.SetDomainName() methods. See https://github.com/OSGeo/gdal/blob/master/autotest/ogr/ogr_openfilegdb_write.py for example
Subtype isn't supported currently by the OpenFileGDB driver.
That said, you could possibly open the system table a00000004.gdbtable with the OpenFileGDB driver and try to modify its Definition field, after the layer has been created. Be careful to not *add* new fields that way. You can only tune "metadata" around existing fields.

**Comment by adamgutons** [comment]
Thank you for the clarification, I may take a shot at your suggestion for opening the system table. However if there is no direct way to create subtypesthroug
