### ISSUE TITLE
Logo Proporsal: Gdal

### ISSUE THREAD

**Issue by tjulises** [OSGeo/gdal#630]
Hey, I'm graphic designer and my aim is supporting open source projects and make my portfolio better. So, I can contribute on your project with making logo design. I am waiting your feedback! Have a nice day! :)

Best Regards,
TJ Ulises 
Visual Communication Designer

**Comment by rouault** [comment]
Thanks for the proposal. In case you are not aware, the project has already a logo : https://github.com/OSGeo/gdal/blob/master/gdal/data/GDALLogoColor.svg . And I haven't heard complaints about it, so we're probably going to stick with it for now :-)
