### ISSUE TITLE
ogr2ogr -makevalid will only retain polygons in GeometryCollection

### ISSUE THREAD

**Issue by jxeeno** [OSGeo/gdal#6340]
## Expected behavior and actual behavior.

When using ogr2ogr to transform data with the `-makevalid` option, features consisting of a `GeometryCollection` with multiple types of geometries (e.g. `Point`, `Polygon` and `LineString`) in the input will only retain the polygon(s) in the output.

The expected behaviour is to return retain the GeometryCollection and perform the `makevalid` operation for each geometry type.

## Steps to reproduce the problem.

Using the following input as `example.geojson`:

```json
{
    "type": "FeatureCollection",
    "features": [
        {
            "type": "Feature",
            "geometry": {
                "type": "GeometryCollection",
                "geometries": [
                    {"type": "Point", "coordinates": [151.193,-33.872]},
                    {"type": "Polygon","coordinates": [[[151.201,-33.903],[151.259,-33.879],[151.223,-33.867],[151.201,-33.903]]]},
                    {"type": "LineString","coordinates": [[151.268,-33.890],[151.268,-33.894],[151.268,-33.897]]}
                ]
            },
            "properties": {
                "gdal": "example"
            }
        }
    ]
}
```

Run:

```
ogr2ogr -f GeoJSON exampleout.geojson example.geojson  -makevalid
```

`exampleout.geojson` becomes:

```json
{
"type": "FeatureCollection",
"name": "example",
"features": [
{ "type": "Feature", "properties": { "gdal": "example" }, "geometry": { "type": "Polygon", "coordinates": [ [ [ 151.201, -33.903 ], [ 151.259, -33.879 ], [ 151.223, -33.867 ], [ 151.201, -33.903 ] ] ] } }
]
}
```

NOTE: GeometryCollection is flattened to a Polygon.  LineString and Point in the input is omitted.

## Operating system

Ubuntu 22.04 LTS

## GDAL version and provenance

GDAL 3.6.0dev-e10d39568c6ab37077f4b6bc2ee3fb93e1e4d41e, released 2022/06/28

**Comment by jratike80** [comment]
Another variation of the error. Trial to save result into GeoPackage with GDAL 3.6.0dev gives more detailed error message because of geometry triggers of GPKG:

> ogr2ogr -f gpkg collection.gpkg collection.json -makevalid
> Warning 1: A geometry of type POLYGON is inserted into layer collection of geometry type GEOMETRYCOLLECTION, which is not normally allowed by the GeoPackage specification, but the driver will however do it. To create a conformant GeoPackage, if using ogr2ogr, the -nlt option can be used to override the layer geometry type. This warning will no longer be emitted for this combination of layer and feature geometry type.
> 

Test with PostGIS:
```
select st_astext(st_makevalid('GEOMETRYCOLLECTION ( POINT ( 151.193 -33.872 ), LINESTRING ( 151.268 -33.89, 151.268 -33.894, 151.268 -33.897 ), POLYGON (( 151.201 -33.903, 151.259 -33.879, 151.223 -33.867, 151.201 -33.903 )))'))

"GEOMETRYCOLLECTION(POINT(151.193 -33.872),LINESTRING(151.268 -33.89,151.268 -33.894,151.268 -33.897),POLYGON((151.201 -33.903,151.259 -33.879,151.223 -33.867,151.201 -33.903)))"
```
Spatialite does not seem to process geometry collections with ST_MakeValid.
