### ISSUE TITLE
ogr2ogr converts date-like strings to dates (stripping trailing characters)

### ISSUE THREAD

**Issue by lucasprograms** [OSGeo/gdal#6351]
## Expected behavior and actual behavior.

ogr2ogr converts date-like strings to dates (stripping trailing characters)

## Steps to reproduce the problem.

Use the following geojson:
```
{
  "type": "FeatureCollection",
  "name": "date-test",
  "features": [
    {
      "type": "Feature",
      "properties": {
        "not_a_date": "2022/05/12 blah blah blah blah"
      },
      "geometry": { "type": "Point", "coordinates": [0, 0] }
    }
  ]
}
```
`ogr2ogr out.geojson input.geojson`
or
`ogr2ogr out.geojson input.geojson  -mapFieldType All=string`

**Expected**
`not_a_date` field remains the same

**Actual**
`not_a_date` field becomes `"2022/05/12"`

## Operating system

Ubuntu22.04

## GDAL version and provenance

3.4.1

**Comment by jratike80** [comment]
Confirmed with ogrinfo 

```
OGRFeature(abc):0
  Notes (Date) = 2022/05/12
  POINT (-76 39)
```

If Notes is edited into `"Notes": "z2022/05/12 blah blah blah"` the string remains
```
OGRFeature(abc):0
  Notes (String) = z2022/05/12 blah blah blah
  POINT (-76 39)

```
