### ISSUE TITLE
BUG: Support integer data types for netCDF _Unsigned convention

### ISSUE THREAD

**Issue by snowman2** [OSGeo/gdal#6352]
Related:
-  https://github.com/corteva/rioxarray/issues/574
-  https://github.com/Unidata/netcdf4-python/issues/656
-  https://github.com/pydata/xarray/issues/1444

Currently, GDAL only checks for the unsigned type when the datatype is byte:
https://github.com/OSGeo/gdal/blob/8e4c84b5103a832f5f0ca507ce2eec36f479f994/frmts/netcdf/netcdfdataset.cpp#L626-L702

However, there are scenarios when the datatype is an integer (See: https://github.com/corteva/rioxarray/issues/574). Thoughts on this?

Also, sometimes users want to convert this data to other formats. I didn't see a standard way to preserve the original data type while denoting that the data should be converted to unsigned in the GDAL metadata. Did I miss something?

**Comment by snowman2** [comment]
How xarray handles it:
https://github.com/pydata/xarray/blob/abe1e613a96b000ae603c53d135828df532b952e/xarray/coding/variables.py#L306-L334

**Comment by rouault** [comment]
> I didn't see a standard way to preserve the original data type while denoting that the data should be converted to unsigned in the GDAL metadata. Did I miss something?

no. That would be quite horrible to have in the GDAL abstraction that remnant of a netCDF hack (or "implementation detail" if one wants to be more neutral)
(That said, the only exception to this is for signed byte as we don't have a native signed byte type for GDAL raster data types. So this is modeled as GDT_Byte + PIXELTYPE=SIGNEDBYTE in band STRUCTURE metadata domain.)

The right fix is here would be to expose short + _Unsigned=true as GDT_UInt16

**Comment by snowman2** [comment]
Thanks @rouault 👍
