### ISSUE TITLE
Remove use of std::regex

### ISSUE THREAD

**Issue by rouault** [OSGeo/gdal#6358]
std::regex has implementation issues and will be deprecated in a future version of C++: https://github.com/sg16-unicode/sg16/issues/57 and https://github.com/r-spatial/sf/issues/1995#issuecomment-1246548294

We have probably no better alternative than doing poor-man hand std::string parsing if not using an external lib

std::regex is used in ogr/ogrsf_frmts/sqlite/ogrsqliteutility.cpp (I'll take care of that one) and ogr/ogrsf_frmts/hana/ogrhanatablelayer.cpp (CC @mrylov)

**Comment by afnansyed** [comment]
Hello! I am a beginner when it comes to open source contributions and was hoping to gain some experience by attempting this issue. Can I try fixing the issue in the ogrhanatablelayer.cpp file?
