### ISSUE TITLE
Python bindings do not honor CMAKE_INSTALL_RPATH for CMake build

### ISSUE THREAD

**Issue by pedros007** [OSGeo/gdal#6371]
## Expected behavior and actual behavior.

I build GDAL on Mac OSX and install the bindings to a non-standard location.. By default the Python bindings are installed to `${CMAKE_INSTALL_PREFIX}/lib/python-3.x/site-packages`.  I use `GDAL_PYTHON_INSTALL_PREFIX` to install the Python bindings to a different location. However, the RPATH entry is not updated properly, so `libgdal.31.dylib` is not found without overriding `DYLD_LIBRARY_PATH` at runtime.

I think this could be resolved by updating the Python binding installation to honor [CMAKE_INSTALL_RPATH](https://gitlab.kitware.com/cmake/community/-/wikis/doc/cmake/RPATH-handling#always-full-rpath).

## Steps to reproduce the problem.

```bash
cmake .. \
    -DCMAKE_INSTALL_PREFIX=/Users/pschmitt/opt/gdal-3.5.2 \
    -DCMAKE_INSTALL_RPATH=/Users/pschmitt/opt/gdal-3.5.2/lib \
    -DGDAL_PYTHON_INSTALL_PREFIX=$(pyenv prefix)
cmake --build . -j$(sysctl -n hw.ncpu)
cmake --build . --target install
```

`pyenv prefix` evaluates to `/Users/pschmitt/.pyenv/versions/3.8.12`

After install, gdal binaries have the proper rpath set:

```bash
otool -l $(which gdal_translate) | grep -i path
         name @rpath/libgdal.31.dylib (offset 24)
          cmd LC_RPATH
         path /Users/pschmitt/opt/gdal-3.5.2/lib (offset 12)
```

However, the Python bindings do not:

```bash
otool -l /Users/pschmitt/.pyenv/versions/3.8.12/lib/python3.8/site-packages/osgeo/_gdal.cpython-38-darwin.so | grep path
         name @rpath/libgdal.31.dylib (offset 24)
```

This results in runtime errors:

```
python -c "from osgeo import gdal"
Traceback (most recent call last):
  File "/Users/pschmitt/.pyenv/versions/3.8.12/lib/python3.8/site-packages/osgeo/__init__.py", line 30, in swig_import_helper
    return importlib.import_module(mname)
...
ImportError: dlopen(/Users/pschmitt/.pyenv/versions/3.8.12/lib/python3.8/site-packages/osgeo/_gdal.cpython-38-darwin.so, 0x0002): Library not loaded: '@rpath/libgdal.31.dylib'
  Referenced from: '/Users/pschmitt/.pyenv/versions/3.8.12/lib/python3.8/site-packages/osgeo/_gdal.cpython-38-darwin.so'
  Reason: tried: '/usr/local/lib/libgdal.31.dylib' (no such file), '/usr/lib/libgdal.31.dylib' (no such file)
```

## Operating system

macOS Monterrey 12.5.x
python 3.8.12

## GDAL version and provenance

gdal-3.5.2 source

**Comment by rouault** [comment]
This seems to be the same as https://github.com/OSGeo/gdal/issues/6273
Seems that we should do something like ``python3 setup.py build_ext --inplace --rpath=${CMAKE_INSTALL_RPATH} --force install``

**Comment by pedros007** [comment]
I tried adding `--rpath=${CMAKE_INSTALL_RPATH}`  after `--inplace` here:
https://github.com/OSGeo/gdal/blob/6057b4a03eb725ced2601a666e3ed9972f04fbef/swig/python/CMakeLists.txt#L295
which did not seem to do the trick: otool did not show the rpath getting applied to the library:

```
otool -l build/lib.macosx-11.6-x86_64-3.8/osgeo/_gdal.cpython-38-darwin.so | grep -i path
         name @rpath/libgdal.31.dylib (offset 24)
```

I could get things working if I did the following from a build directory:

```bash
cd swig/python
rm build/lib.macosx-11.6-x86_64-3.8/osgeo/*.so osgeo/*.so
env LDFLAGS="-Wl,-rpath,/Users/pschmitt/opt/gdal-3.5.2/lib" /Users/pschmitt/.pyenv/shims/python3.8 /Users/pschmitt/opt/src/gdal-3.5.2/build/swig/python/setup.py build_ext --inplace
```

now the rpath is set correctly:

```bash
otool -l build/lib.macosx-11.6-x86_64-3.8/osgeo/_gdal.cpython-38-darwin.so | grep -i path
         name @rpath/libgdal.31.dylib (offset 24)
          cmd LC_RPATH
         path /Users/pschmitt/opt/gdal-3.5.2/lib (offset 12)
```

and `python -c "from osgeo import gdal"` runs without error.

**Comment by rouault** [comment]
> I tried adding `--rpath=${CMAKE_INSTALL_RPATH}` after `--inplace` here:

apparently `--force` was critical to make things works in #6273. Did you try that ?

**Comment by pedros007** [comment]
I did also try adding `--force`. I suspect you need `--force` if you don't first delete the following build artifacts:

```bash
rm build/python/swig/build/lib.macosx-11.6-x86_64-3.8/osgeo/*.so \
    build/python/swig/osgeo/*.so
```

**Comment by pedros007** [comment]
It turns out I had an old version of setuptools that did not honor the `--rpath` flag!  Upon upgrading setuptools via `pip install -U setuptools`, 
```bash
setup.py build_ext --rpath /Users/pschmitt/opt/gdal-3.5.2/lib
``` 

now results in a link line that includes `-Wl,-rpath,/Users/pschmitt/opt/gdal-3.5.2/lib`!   

To resolve this issue I propose:

1. Update build-hints docs to suggest upgrading setuptools
2. Something like the patch below only when `CMAKE_INSTALL_RPATH` is set:

```patch
--- gdal-3.5.2/swig/python/CMakeLists.txt       2022-09-15 15:17:20.000000000 -0600
+++ gdal-3.5.2/swig/python/CMakeLists.txt~      2022-09-02 06:20:08.000000000 -0600
@@ -222,12 +222,12 @@
       GENERATE
       OUTPUT ${BUILD_EXT_FILENAME}
       CONTENT
-        "execute_process(COMMAND $<IF:$<NOT:$<CONFIG:Debug>>,${Python_EXECUTABLE} ${SETUP_PY_FILENAME} build_ext --inplace --rpath ${CMAKE_INSTALL_RPATH},${CMAKE_COMMAND} -E echo \"setup.py build_ext only run in configuration != Debug\">)\n${BUILD_EXT_EXTRA_CONTENT}"
+        "execute_process(COMMAND $<IF:$<NOT:$<CONFIG:Debug>>,${Python_EXECUTABLE} ${SETUP_PY_FILENAME} build_ext --inplace,${CMAKE_COMMAND} -E echo \"setup.py build_ext only run in configuration != Debug\">)\n${BUILD_EXT_EXTRA_CONTENT}"
       )
   else ()
     set(BUILD_EXT_FILENAME ${CMAKE_CURRENT_BINARY_DIR}/build_ext.cmake)
     file(WRITE ${BUILD_EXT_FILENAME}
-         "execute_process(COMMAND ${Python_EXECUTABLE} ${SETUP_PY_FILENAME} build_ext --inplace --rpath ${CMAKE_INSTALL_RPATH})\n${BUILD_EXT_EXTRA_CONTENT}")
+         "execute_process(COMMAND ${Python_EXECUTABLE} ${SETUP_PY_FILENAME} build_ext --inplace)\n${BUILD_EXT_EXTRA_CONTENT}")
   endif ()
   add_custom_command(
     OUTPUT ${PY_SO_LIST}
```

The `--force` flag is unecessary unless you have artifacts in `build/python/swig/build/lib.macosx-11.6-x86_64-3.8/osgeo`.

**Comment by pedros007** [comment]
Might be worth mentioning that whatever is going on in #5485 doesn't seem to update the rpath of the Python bindings. So with `GDAL_SET_INSTALL_RELATIVE_RPATH=ON`, the utilities have the proper rpath, but the python shared objects installed to `site-packages/osgeo/*.so` do not. This results in runtime import errors when the `GDAL_PYTHON_INSTALL_PREFIX` was set.

**Comment by rouault** [comment]
@pedros007  can you check https://github.com/OSGeo/gdal/pull/6382 ? (tested on Linux on my side)
