### ISSUE TITLE
Default User-Agent

### ISSUE THREAD

**Issue by drnextgis** [OSGeo/gdal#6376]
I know that there are some ways to set the value of User-Agent, for example:

```
$ GDAL_HTTP_USERAGENT="gdal/3.0.4" gdalinfo /vsicurl/https://...
```

But it would be nice if GDAL could have some default value for it (ideally with the version). This is how it is done in [requests](https://github.com/psf/requests/blob/7104ad4b135daab0ed19d8e41bd469874702342b/requests/utils.py#L899):

```python
>>> from requests.utils import default_user_agent
>>> default_user_agent()
'python-requests/2.16.5'
```

**Comment by jratike80** [comment]
At least WMS driver sets a default User-Agent, I do not know if any other driver does.

**Comment by drnextgis** [comment]
Thanks!
