### ISSUE TITLE
GDAL 3.5.2 Docker container is missing and doesn't work when I build it

### ISSUE THREAD

**Issue by lnicola** [OSGeo/gdal#6390]
Only `alpine-normal-3.5.2` is available: https://hub.docker.com/r/osgeo/gdal/tags?page=1&name=3.5.2.

**Comment by learning4life** [comment]
I also need the Ubuntu-full docker image in v3.5.2 and can see others has mentioned this in the mail archive as a known issue:

[missing docker images for 3.5.2](https://lists.osgeo.org/pipermail/gdal-dev/2022-September/056206.html)

**Comment by learning4life** [comment]
I did try to build the ubuntu-full docker locally but ended with this error:

`rsync: link_stat "/root/.cache" failed: No such file or directory (2)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1207) [sender=3.1.3]
The command '/bin/sh -c . /buildscripts/bh-set-envvars.sh     && DESTDIR=/build_tmp_proj /buildscripts/bh-proj.sh      && LD_LIBRARY_PATH=/build_tmp_proj/usr/local/lib /build_tmp_proj/usr/local/bin/projsync --target-dir /tmp/proj_grids --all      && rm -rf /build_tmp_proj' returned a non-zero code: 23
`

Using:
`git clone -b v3.5.2 https://github.com/OSGeo/gdal.git  .`

`cd docker/ubuntu-full/ && ./build.sh`

I will let the pro work it out and hope he gets a fiber connection and a workstation in the process ;)

**Comment by lnicola** [comment]
I can confirm the `libparquet.so.900` error. It shows at the end (maybe the build script tries to run `ogrinfo --version` or whatever, I haven't checked), but also happens in the resulting container.

The container has `/usr/lib/x86_64-linux-gnu/libparquet.so.800` instead.

**Comment by lnicola** [comment]
I can confirm that the new container works, thanks!
