### ISSUE TITLE
Undocumented commandline option for gdal2tiles.py --tmscompatible

### ISSUE THREAD

**Issue by MCBama** [OSGeo/gdal#6404]
Ran into an issue that slowed my progress for several days and figured I would bring it up here. There is an option for use with the geodetic profile to indicate if a particular map you are tiling is TMS compatible or not which changes the base resolution and thus the number of tiles at zoom level 0 (`--tmscompatible`). However, this option is only explained in the help of `gdal2tiles.py` and not the online documentation. It's my own fault for not checking the help file itself and relying on the online documentation however I do recommend the option being added to the documentation as this option is required to output CADRG and other TOC map tiles at the correct zoom levels.

![image](https://user-images.githubusercontent.com/8883315/191322800-5ca18571-ed00-4894-b910-7c202ff9cecc.png)

**Comment by rouault** [comment]
@MCBama  are you willing to add the documentation ? Mostly a matter of clicking on the "Edit on github" link at the top right of https://gdal.org/programs/gdal2tiles.html

**Comment by MCBama** [comment]
PR #6406 exists. First time providing support on this project so if I did something wrong that needs correcting let me know and I will do so.
