### ISSUE TITLE
docker image want FILEGDB Driver

### ISSUE THREAD

**Issue by zzm123zhaozm** [OSGeo/gdal#6408]
there is no FILEGDB Driver in the ubuntu-full-3.5.2 image

**Comment by rouault** [comment]
yes, that's intended. We only ship free and open source software in the image, and the FileGDB SDK is proprietary.
Either use the osgeo/gdal:ubuntu-full-latest image (currently of GDAL 3.6.0dev) that has read/write capabilities with the OpenFileGDB driver, or build yourself the docker/ubuntu-full/Dockerfile with the WITH_FILEGDB=yes docker build-time variable
