### ISSUE TITLE
Issue while creating coordinate reference system

### ISSUE THREAD

**Issue by kavindergupta** [OSGeo/gdal#642]
## Expected behavior and actual behavior.

The CRSs bounds should be same because the CRS parameters (Projection, Central_Meradian, Latitude of origin, Standard Parallel 1, Standard Parallel 2, False Easting, False Northing Datum, and units) are exactly same.

## Steps to reproduce the problem.

Create CRS using the below WKTs

Correct WKT: PROJCS["NAD83 / Texas Central (ftUS)", 
  GEOGCS["NAD83", 
    DATUM["North American Datum 1983", 
      SPHEROID["GRS 1980", 6378137.0, 298.257222101, AUTHORITY["EPSG","7019"]], 
      TOWGS84[1.0, 1.0, -1.0, 0.0, 0.0, 0.0, 0.0], 
      AUTHORITY["EPSG","6269"]], 
    PRIMEM["Greenwich", 0.0, AUTHORITY["EPSG","8901"]], 
    UNIT["degree", 0.017453292519943295], 
    AXIS["Geodetic longitude", EAST], 
    AXIS["Geodetic latitude", NORTH], 
    AUTHORITY["EPSG","4269"]], 
  PROJECTION["Lambert Conic Conformal (2SP)", AUTHORITY["EPSG","9802"]], 
  PARAMETER["central_meridian", -100.33333333333333], 
  PARAMETER["latitude_of_origin", 29.666666666666668], 
  PARAMETER["standard_parallel_1", 31.883333333333336], 
  PARAMETER["false_easting", 2296583.333], 
  PARAMETER["false_northing", 9842500.0], 
  PARAMETER["scale_factor", 1.0], 
  PARAMETER["standard_parallel_2", 30.116666666666667], 
  UNIT["foot_survey_us", 0.30480060960121924], 
  AXIS["Easting", EAST], 
  AXIS["Northing", NORTH], 
  AUTHORITY["EPSG","2277"]]

Incorrect WKT: PROJCS["NAD83_Texas_Central_ftUS",
GEOGCS["GCS_North_American_1983",
DATUM["D_NORTH_AMERICAN_1983",
SPHEROID["GRS_1980",6378137,298.257222101],
PRIMEM["Greenwich",0,
UNIT["Degree",0.017453292519943295],
PROJECTION["Lambert_Conformal_Conic",
PARAMETER["central_meridian",-100.3333333333333,
PARAMETER["latitude_of_origin",29.66666666666667,
PARAMETER["scale_factor",1,
PARAMETER["standard_parallel_2",31.88333333333333,
PARAMETER["false_easting",2296583.333,
PARAMETER["false_northing",9842500.0,
PARAMETER["standard_parallel_1",30.11666666666667,
UNIT["Foot_US",0.30480060960121924]]

## Operating system

Windows 10 x64

## GDAL version and provenance

GDAL version is 2.2.3

**Comment by rouault** [comment]
Can you better describe the problem ? What did you do exactly / which API did you use, and what expected result did you expect ?

**Comment by kavindergupta** [comment]
I am trying to load multiple shapefiles and sometimes I found that the CRS WKT defined in the associated Prj file does not contain EPSG code/ Authority code and when I try to create a coordinate system using SpatialReference.ImportFromWkt(ref wkt) API. The created coordinate system bounds are incorrect and the data lies outside the CRS bounds. When I load the same shapefile having the same CRS parameters (Projection, Central_Meradian, Latitude of origin, Standard Parallel 1, Standard Parallel 2, False Easting, False Northing Datum, and units) along with its actual EPSG code, then the coordinated system bounds are different and the same data lies within the coordinate system bounds. 

I do not understand why this is happening. It seems like that the parameters defined in the ESRI database are different that's why when I create a coordinate reference system using an EPSG code and WKT, the results are different only for few CRS.

I have also mentioned the above CRS WKTs to identify the issue. Please let me know if anything else is required.

**Comment by rouault** [comment]
Yes, ESRI WKT differs in a number of things from "standard" WKT, and it is not always possible to recover the lost information. See http://gdal.org/wktproblems.html
In your use case after calling ImportFromWkt(), you should also call MorphFromESRI() to transform things in something better understandable by other GDAL software layers.

**Comment by kavindergupta** [comment]
Thanks for the suggestion. I tried your suggestion (MorphFromESRI()) and found the same behavior. I have attached another shapefile having the same problem. The shapefile data lies completely outside the CRS's domain. But if I create a coordinate system from EPSG code 2256 (which is have the same parameters), then the same shapefile lies within the CRS bounds. Also, when I load the same shapefile in GlobalMapper or ArcMap, they are able to load it correctly. Please let me know if there is any other workaround for this problem. 

[CFR_20180209.zip](https://github.com/OSGeo/gdal/files/2039431/CFR_20180209.zip)

**Comment by rouault** [comment]
Not sure what happens for you, but testest with GDAL 2.2.4, things work for me

```
$ gdalsrsinfo "Cross Sections.shp"

PROJ.4 : '+proj=lcc +lat_1=49 +lat_2=45 +lat_0=44.25 +lon_0=-109.5 +x_0=599999.9999976 +y_0=0 +datum=NAD83 +units=ft +no_defs '

OGC WKT :
PROJCS["NAD83_Montana_ft",
    GEOGCS["GCS_North_American_1983",
        DATUM["North_American_Datum_1983",
            SPHEROID["GRS_1980",6378137,298.257222101]],
        PRIMEM["Greenwich",0],
        UNIT["Degree",0.017453292519943295],
        AUTHORITY["EPSG","4269"]],
    PROJECTION["Lambert_Conformal_Conic_2SP"],
    PARAMETER["standard_parallel_1",49],
    PARAMETER["standard_parallel_2",45],
    PARAMETER["latitude_of_origin",44.25],
    PARAMETER["central_meridian",-109.5],
    PARAMETER["false_easting",1968503.937],
    PARAMETER["false_northing",0],
    UNIT["Foot",0.3048]]
```

```
$ ogr2ogr montana.shp "Cross Sections.shp" -t_srs EPSG:4326 -overwrite
$ ogrinfo montana.shp -al -so
INFO: Open of `montana.shp'
      using driver `ESRI Shapefile' successful.

Layer name: montana
Metadata:
  DBF_DATE_LAST_UPDATE=2018-05-30
Geometry: 3D Line String
Feature Count: 498
Extent: (-115.094480, 46.995317) - (-114.688658, 47.329863)
```

The extent once reprojected in EPSG:4326 is consistant with Montana bounds

**Comment by rouault** [comment]
closing as I can't really reproduce an issue
