### ISSUE TITLE
Parallel make fails on Perl SWIG modules

### ISSUE THREAD

**Issue by Ariki** [OSGeo/gdal#643]
## Expected behavior and actual behavior.

When I try to build current GDAL master or 2.3 branch from GitHub with `make -j8`, the build fails with an error:
```
perl Makefile.PL INSTALLDIRS=vendor
GDAL Perl modules not found, perhaps you need to run make generate? at Makefile.PL line 14.
make[2]: *** [GNUmakefile:33: Makefile_Geo__GDAL] Error 2
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/home/alexei/builds/gdal-master/src/gdal-2.3.0/swig/perl'
make[1]: *** [GNUmakefile:29: build] Error 2
make[1]: Leaving directory '/home/alexei/builds/gdal-master/src/gdal-2.3.0/swig'
make: *** [GNUmakefile:115: swig-modules] Error 2
```
The error does not occur when building with `make -j1`. Also, it does not occur when building 2.3 tarball downloaded from http://download.osgeo.org/gdal/2.3.0/gdal-2.3.0.tar.gz .

When I check the build directory, I see that `*.pm` files exist in `swig/perl/` directory but `swig/perl/lib/Geo/` contains only `*.dox` files.

## Steps to reproduce the problem.

I use [PKGBUILD](https://git.archlinux.org/svntogit/community.git/tree/trunk?h=packages/gdal) from Arch Linux community repository with some modifications: I change source link, skip checksum verification, rename unpacked source, add `-j8` make option, and don't apply [gdal-poppler-0.64.patch](https://git.archlinux.org/svntogit/community.git/tree/trunk/gdal-poppler-0.64.patch?h=packages/gdal) since the problem it addresses has been solved upstream recently. But I still apply [gdal-perl-vendor.patch](https://git.archlinux.org/svntogit/community.git/tree/trunk/gdal-perl-vendor.patch?h=packages/gdal).

## Operating system

Arch Linux 64 bit

## GDAL version and provenance

Current 2.3 and master branch from GitHub

**Comment by ajolma** [comment]
I could produce the error once but not twice, so it seems to be a bit random. I'm also not a gnu make guru. However, would this kind of change fix the errror:
`
diff --git a/gdal/swig/perl/GNUmakefile b/gdal/swig/perl/GNUmakefile
index b4d1c39..68d389d 100644
--- a/gdal/swig/perl/GNUmakefile
+++ b/gdal/swig/perl/GNUmakefile
@@ -29,7 +29,7 @@ build: gdal_wrap.cc Makefile_Geo__GDAL
 
 gdal_wrap.cc: generate
 
-Makefile_Geo__GDAL:
+Makefile_Geo__GDAL: gdal_wrap.cc
        perl Makefile.PL INSTALL_BASE=$(INST_PREFIX)
 
 test: build
`

**Comment by ajolma** [comment]
The error seemed to require a clean clone. `make clean` was not enough.
Fixed in 246ce4b and  6abc41e

**Comment by Ariki** [comment]
Thank you for quick response. I will not be able to build on the same system until tomorrow but now I'm trying to build on my home laptop (it's somewhat slow, so experiments take too much time).

There's target `veryclean` in`gdal/swig/perl/GNUmakefile` which removes generated files. I've discovered that the tarball from gdal.org downloads page has generated `*.pm` files in `swig/perl/lib/Geo` directory. That's why build from this tarball did not fail.

But on my laptop both with `make -j4` and `make -j1` I'm getting different errors:

```
chmod 755 blib/arch/auto/Geo/GNM/GNM.so
Manifying 1 pod document
make[3]: Leaving directory '/home/alexei/builds/gdal/src/gdal-2.3.0/swig/perl'
make[2]: Leaving directory '/home/alexei/builds/gdal/src/gdal-2.3.0/swig/perl'
make[1]: Leaving directory '/home/alexei/builds/gdal/src/gdal-2.3.0/swig'
rm -f gdal.pc
echo 'CONFIG_VERSION='`cat ./VERSION`'' >> gdal.pc
echo 'CONFIG_INST_PREFIX=/usr' >> gdal.pc
echo 'CONFIG_INST_LIBS=-L/usr/lib -lgdal' >> gdal.pc
echo 'CONFIG_INST_CFLAGS=-I/usr/include' >> gdal.pc
echo 'CONFIG_INST_DATA=/usr/share/gdal' >> gdal.pc
cat gdal.pc.in >> gdal.pc
(cat Doxyfile ; echo "ENABLED_SECTIONS=man"; echo "INPUT=apps swig/python/scripts"; echo "FILE_PATTERNS=*.cpp *.dox"; echo "GENERATE_H
TML=NO"; echo "GENERATE_MAN=YES" ; echo "LAYOUT_FILE=/dev/null") | doxygen -
warning: Tag `XML_SCHEMA' at line 829 of file `-' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
warning: Tag `XML_DTD' at line 835 of file `-' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
error: fatal: at line 1 column 1 of /dev/null: unexpected end of file
error: fatal: at line 1 column 1 of /dev/null: error while parsing prolog
Parsing layout file /dev/null...
```
and after that
```
osr_wrap.o: file not recognized: File truncated
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile_Geo__OSR:495: blib/arch/auto/Geo/OSR/OSR.so] Error 1
make[3]: Leaving directory '/home/alexei/builds/gdal/src/gdal-2.3.0/swig/perl'
make[2]: *** [GNUmakefile:26: build] Error 2
make[2]: Leaving directory '/home/alexei/builds/gdal/src/gdal-2.3.0/swig/perl'
make[1]: *** [GNUmakefile:32: install] Error 2
make[1]: Leaving directory '/home/alexei/builds/gdal/src/gdal-2.3.0/swig'
make: *** [GNUmakefile:234: install-actions] Error 2
make: *** Waiting for unfinished jobs....
```
These are probably unrelated to the issue but I'm not sure.

**Comment by ajolma** [comment]
In the first one make has moved away from swig/perl and the errors are doxygen errors happening in the man target of root GNUmakefile. I'm not sure they are real errors. In the second one one of the wrapper object files is probably not yet made(?) when it is being used. Problem of parallelization(?) However, I can't produce that.

**Comment by Ariki** [comment]
Today I can't reproduce it too. If I find something later, I'll open an issue. Thank you.
