### ISSUE TITLE
COPY_SRC_OVERVIEWS not supporting lossless copy

### ISSUE THREAD

**Issue by idanaviv10** [OSGeo/gdal#6439]
Hi,
I have a raster that I want to convert to cog (with webp compression).
I am looking for a way to convert the raster and its overviews losses (to have the exact same checksum for all bands in all levels).

I tried to do this using the cog driver (OVERVIEWS= FORCE_USE_EXISTING, COMPRESSION= WEBP QUALITY =100, OVERVIEW_QUALITY = 100).  After the conversion I perform checksum test (using gdalinfo) but I got that the overviews checksum are different between the two rasters (while level 0 is equal).

I did another test where I use the GTIFF driver (COPY_SRC_OVERVIEWS = YES, COMPRESS = WEBP, WEBP_LEVEL = 100, WEBP_LOSSLESS = True, COMPRESS_OVERVIEW = WEBP, WEBP_LEVEL_OVERVIEW = 100). And still I got different overviews checksum. 

Am I doing something wrong ?  Is there a parameter like WEBP_LOSSLESS_OVERVIEW that I should use (couldn't find any parameter in the documentation that would fit).

I am using the gdal 3.5.2 version.

Thanks in advance,
Idan

**Comment by rouault** [comment]
> I tried to do this using the cog driver (OVERVIEWS= FORCE_USE_EXISTING, COMPRESSION= WEBP QUALITY =100, OVERVIEW_QUALITY = 100). After the conversion I perform checksum test (using gdalinfo) but I got that the overviews checksum are different between the two rasters (while level 0 is equal).

I don't reproduce this, even on GDAL 3.5.2, with the following method. Can you provide a dataset (as small as possible) reproducing your issue ?
```
$ cp autotest/gdrivers/data/small_world.tif .
$ gdaladdo -ro -r cubic small_world.tif 2
$ gdal_translate small_world.tif test.tif -of COG -co compress=webp -co quality=100 -co OVERVIEWS=FORCE_USE_EXISTING 
$ gdalinfo -checksum small_world.tif| grep "Overviews checksum"
  Overviews checksum: 9179
  Overviews checksum: 8705
  Overviews checksum: 26197
$ gdalinfo -checksum test.tif| grep "Overviews checksum"
  Overviews checksum: 9179
  Overviews checksum: 8705
  Overviews checksum: 26197
```

**Comment by idanaviv10** [comment]
Hi, 
I tested it again using a gdal 3.5.2 docker and look like it's working properly (like you said). 
It might be my local installation of Kakadu that is creating the problem.
I will keep testing it and look where is the problem.
Thanks for adding the option of WEBP_LOSSLESS_OVERVIEW, it will help a lot as I usually use the GTIFF driver to create COG rasters. 
For now you can close the issue until I understand what wrong with my local installation.
