### ISSUE TITLE
support for the nvJPEG2000 codec

### ISSUE THREAD

**Issue by idanaviv10** [OSGeo/gdal#6451]
Hi, 
I am looking for a fast codec for decoding/encoding jpeg2000 images.
It looks like my options are: OpenJPEG, KAKADU and nvJPEG2000.
While I would love to use the OpenJPEG (having all the benefits of open source project), [according to this ](https://www.fastcompression.com/benchmarks/decoder-benchmarks-j2k.htm) it look like its performance are not as good as Kakadu's performance. 
I also saw that there is codec called nvJPEG2000 made by Nvidia, that can utilize both cpu and gpu, with very promising performance. 
Is there away that we could use this codec within gdal ? 

Thanks in advance, 
Idan

**Comment by jratike80** [comment]
The message that you saw when you wrote your question in meant to be taken seriously.

> IMPORTANT: Do NOT use GitHub to post any questions or support requests!
>            They will be closed immediately and ignored.
> 
> Questions should go to the gdal-dev mailing list at
> https://lists.osgeo.org/mailman/listinfo/gdal-dev
> or other support forums. GitHub issues are for bug
> reports and suggestions for new features.

The test in the article decodes the whole image that is rather small. Typical use case with geospatial images is to decode a small subset from arbitrary place inside a big image. Fastvideo JPEG2000 may be flaming fast also in that use case but it should be tested with a proper test.
Using nvJPEG2000 would require a new driver and for that someone needs to write it or to hire someone else to do the programming. The SDK seems to be freeware but not open source. I suggest to contact Nvidia and ask if they are interested in writing the GDAL driver and maintain it.

**Comment by idanaviv10** [comment]
Ok, thanks for the respond.
I thought that requesting for nvJPEG2000 support is under the suggestion of new features in the:

> GitHub issues are for bug
reports and suggestions for new features

Sorry, my bad!

**Comment by jratike80** [comment]
You are right but suggestions are usually more concentrated and would require less work for the developers and therefore they every now and then leads into action. See examples https://github.com/OSGeo/gdal/issues?q=is%3Aissue+enhancement+label%3Aenhancement. It is unlikely that any developer picks a large feature request for a new proprietary driver from GitHub issues and starts to work on it for fun. The gdal-dev mailing list is reaching a much wider audience and you may find other interested people there. Maybe someone gets interested enough for funding.
