### ISSUE TITLE
Transforming several GPX files to one CSV file (with -update -append) throw an error

### ISSUE THREAD

**Issue by darrepac** [OSGeo/gdal#6452]
## Expected behavior and actual behavior.
Transforming several GPX files to one CSV file throw an error

## Steps to reproduce the problem.
```
for gpx in $(ls *.gpx)
do
 echo "$gpx"
 ogr2ogr -update -append -f CSV output.csv $gpx track_points -lco GEOMETRY=AS_XY
done

```

Give the following error for each gpx file except the first one:
```
ERROR 1: Attempt to create csv layer (file) against a non-directory datasource.
ERROR 1: Terminating translation prematurely after failed
translation of layer track_points (use -skipfailures to skip errors)

```
## Operating system
Ubuntu 22.04 

## GDAL version and provenance
GDAL 3.4.1, released 2021/12/27

**Comment by jratike80** [comment]
Have you tried to include also `-update`?

**Comment by darrepac** [comment]
Yes I tried with `-update` initialy... I will update the post

**Comment by jratike80** [comment]
And with `-nln output`?

**Comment by rouault** [comment]
doing that kind of append directly to CSV is going to be complicated/impossible
Rather  modify your loop to output to Geopackage, and then ogr2ogr 'it to CSV
```
ogr2ogr -append temp.gpkg one.gpx track_points
ogr2ogr -append temp.gpkg two.gpx track_points
ogr2ogr output.csv temp.gpkg -lco GEOMETRY=AS_XY
```

**Comment by darrepac** [comment]
> doing that kind of append directly to CSV is going to be complicated/impossible Rather modify your loop to output to Geopackage, and then ogr2ogr 'it to CSV
> 
> ```
> ogr2ogr -append temp.gpkg one.gpx track_points
> ogr2ogr -append temp.gpkg two.gpx track_points
> ogr2ogr output.csv temp.gpkg -lco GEOMETRY=AS_XY
> ```

Why it is complicated?
I will give a try

**Comment by darrepac** [comment]
> And with `-nln output`? If that is the name of the layer that you see with `ogrinfo output.csv -so`

what is the purpose of this option `-nln ouput`?

**Comment by rouault** [comment]
> Why it is complicated?

the fact that the layer creation option -lco GEOMETRY=AS_XY is only a creation one (that is the first time the file is created), but does not exist as an open option one that would be used when you append to an existing file. Doing the final conversion of the concatenated content in CSV solves that

**Comment by darrepac** [comment]
ok! the error should be clearer.

```
ogr2ogr -append temp.gpkg one.gpx track_points
ogr2ogr -append temp.gpkg two.gpx track_points
ogr2ogr output.csv temp.gpkg -lco GEOMETRY=AS_XY
```
seems to work well!

**Comment by darrepac** [comment]
Only issue, gpkg seems quite heavy in size... I have thousands of GPX files...

**Comment by jratike80** [comment]
There is not much to do with it. The GPKG format is indeed not most compact but probably still more compact than GPX and CSV and the file is just temporary. If I would need to save disk space I think I would keep the GPKG, never create CSV, and move the GPX files into backup storage. But I guess that you need just CSV.
