### ISSUE TITLE
New Python API doc is less user-friendly than previous doc

### ISSUE THREAD

**Issue by jontwo** [OSGeo/gdal#6465]
The recent improvements to the Python doc are welcome, but... from a usability perspective, the doc is much harder to navigate.

It's actually easier to refer to the old doc at https://web.archive.org/web/20220328010331/https://gdal.org/python/ than to try and scroll through the huge page of items at https://gdal.org/api/python/osgeo.html.

Maybe all it needs is to add everything in to the sidebar - is it just a case of increasing the TOC level or does Sphinx make you jump through more hoops to achieve this?

**Comment by rouault** [comment]
CC @snowman2

**Comment by snowman2** [comment]
Looks like the page has somehow changed from the original in #6137.

![image](https://user-images.githubusercontent.com/8699967/193838749-98f9eda5-d61e-48e6-b1e5-292195be9164.png)

@rouault are you aware of any changes made by GDAL? Or, do you think it is related to an upstream change in the sphinx related packages?

**Comment by rouault** [comment]
> are you aware of any changes made by GDAL?

https://github.com/OSGeo/gdal/commits/master/doc/source/api doesn't show much trafic

> Or, do you think it is related to an upstream change in the sphinx related packages?

that might be it. The Docker osgeo/proj-docs image is refreshed regularly with latest versions of packages

**Comment by snowman2** [comment]
What I am thinking is to generate the Python API sphinx `.rst` files and then make them static instead of using `sphinxcontrib.apidoc` to generate the `.rst` files. That way it can be customized without being overwritten.

**Comment by jontwo** [comment]
Nice one. This is what we do in our API docs and I was wondering if there was a better way. People are always forgetting to update it when adding a new package.
