### ISSUE TITLE
Adding options to build overviews function

### ISSUE THREAD

**Issue by idanaviv10** [OSGeo/gdal#6467]
Hi, 
I want to add overviews to a raster using build overviews, where the options/config can change between rasters (like different compression type, compression quality, ...).
If I use the command line I can use the gdalaldo and set there the options I want, such as:
`gdaladdo --config GDAL_NUM_THREADS 4 --config COMPRESS_OVERVIEW ZSTD geotif.tif 2 4 8 16 32`

But if I use the c#/ python swig wrapper I can use the BuildOverviews function like this:
`gdal.SetConfigOption("COMPRESS_OVERVIEW", "DEFLATE")` 
`Image.BuildOverviews("AVERAGE", [2,4,8,16,32,64, 128, 256])` 
From my understating the gdal.SetConfigOption is a global parameter, meaning that that the next time I will want to built an overview it will use the same config option unless I set it otherwise.

This structure makes it really difficult to built generic code that can handle multiple config options, for example having a function that take as input the overview options and use it to add overviews to the raster with this options. It will be much simpler if the BuildOverviews will have the ability to receive the overviews options/config, like there is for the translate function.

Am I missing something ? Is there a way to setConfigOption only for a specific raster ?

Thanks in advance,
Idan

I am using gdal 3.5.2

**Comment by rouault** [comment]
> Am I missing something ?

no, that's the current way of doing things.

That said I'm considering an enhanced method signature to do what you suggest (which will probably still set configuration options under the hood)

**Comment by tbonfort** [comment]
yes, that will work, configuration options can be scoped to only the descendants of a function call, you can even do that today in python/rasterio today: https://rasterio.readthedocs.io/en/latest/topics/configuration.html#rasterio

**Comment by idanaviv10** [comment]
Great !
I actually need this functionality in c#, so I don't know if rasterio will help in my situation.
Having this enhanced method signature will help a lot.
