### ISSUE TITLE
Issue with python bindings gdal_translate

### ISSUE THREAD

**Issue by cschloer** [OSGeo/gdal#6469]
## Expected behavior and actual behavior.

Hi, I created a stack exchange post here: https://gis.stackexchange.com/questions/441827/gdal-translate-python-seems-to-fail-with-arbitrarily-different-window

I will copy over the text, and the link to the file is here: https://drive.google.com/file/d/1S0ebdtDACbfOmgxshv9o2f20eiU3LsLs/view?usp=sharing

TLDR: An operation works as expected with `gdal_translate` and doesn't work as expected with the same python command.

_______ text from stackexchange:

I'm trying to take a satellite image tile (Sentinel 2, product 2A) and crop it to a smaller window using lat lon coords. I've created a tiff image combining all of the different Sentinel 2 bands using this code: https://github.com/dairejpwalsh/Sentinel-Scripts

If I crop the image like so:
```
DUMP_FILE_NAME = ...
TIF_FILE_PATH = ...

window = (-88.85120523926013,44.28567970079606, -88.26144083496325, 43.9340763284468 )
gdal.UseExceptions()
gdal.Translate(DUMP_FILE_NAME, TIF_FILE_PATH, projWin = window, projWinSRS="EPSG:4326")
```

It successfully creates the new tif file and I can display the RGB channels properly:
[![enter image description here][1]][1]

However, as you can see, the lat lon coordinates I've provided go out of the bounds of the original image (on the top). So naturally I would like to crop the latitude even more. So I try these bounds:

```
DUMP_FILE_NAME = ...
TIF_FILE_PATH = ...

window = (-88.85120523926013,44.22567970079606, -88.26144083496325, 43.9340763284468 )
gdal.UseExceptions()
gdal.Translate(DUMP_FILE_NAME, TIF_FILE_PATH, projWin = window, projWinSRS="EPSG:4326")
```

All I've changed is the top left corner latitude value to `44.22...` instead of `44.28...`

Now, when I try to display the image it is entirely black, and I've confirmed that the values are all 0 (in all bands).
[![enter image description here][2]][2]

  [1]: https://i.stack.imgur.com/4pKyS.jpg
  [2]: https://i.stack.imgur.com/CVDMq.png

__________ end stackexchange post

See accepted answer. It works fine when I just directly called gdal_translate

## Steps to reproduce the problem.

See above

## Operating system

 Python 3 Google Compute Engine backend (using google notebook)

## GDAL version and provenance

python GDAL==2.2.2

**Comment by rouault** [comment]
I don't confirm this with GDAL master where I get binary identical results with python bindings or gdal_translate. GDAL 2.2.2 is completely antiquated

```
$ python -c 'from osgeo import gdal; DUMP_FILE_NAME = "out.tif"; DUMP_FILE_NAME = "out.tif"
TIF_FILE_PATH = "merged.tif"; window = (-88.85120523926013,44.22567970079606, -88.26144083496325, 43.9340763284468 );gdal.UseExceptions(); gdal.Translate(DUMP_FILE_NAME, TIF_FILE_PATH, projWin = window, projWinSRS="EPSG:4326")' && md5sum out.tif
3e74fa1ec7eb816df6bab818b0149928  out.tif

$ gdal_translate merged.tif out.tif -q -projwin -88.85120523926013 44.22567970079606 -88.26144083496325 43.9340763284468 -projwin_srs EPSG:4326 && md5sum out.tif
3e74fa1ec7eb816df6bab818b0149928  out.tif
```
