### ISSUE TITLE
The problem of using copylayer in FileGDB

### ISSUE THREAD

**Issue by YuChenu** [OSGeo/gdal#6472]
## Expected behavior and actual behavior.

I want to copy and rename the layer in the dataset in FileGDB. Then I found the "GDALDataset:: CopyLayer" method. However, when I use it to copy a layer, the error "ERROR 1: Failed at creating table f (Invalid spatial reference.)" appears. I guess there is a problem with the projection of the output layer, and I have taken some actions, but the problem is still unresolved.
The code is following:

 ```
    const char* gdbpath = "G:\\GeoMarkData\\K3_1_1.gdb";
    GDALAllRegister();
    CPLSetConfigOption("GDAL_FILENAME_IS_UTF8", "NO");  
    CPLSetConfigOption("SHAPE_ENCODING", "");
    GDALDriver* driver = GetGDALDriverManager()->GetDriverByName("FileGDB");
    if (driver != NULL)
    {
        GDALDataset* ds = (GDALDataset*)GDALOpenEx(gdbpath, GDAL_OF_VECTOR | GDAL_OF_UPDATE, NULL, NULL, NULL);

        if (ds->GetLayerCount() > 0)
        {
            
            vector<string> CopiedName;

            for (int i = 0; i < ds->GetLayerCount(); i++)
            {
                CopiedName.push_back(ds->GetLayer(i)->GetName());
            }

            for (int i = 0; i < CopiedName.size(); i++)
            {

                OGRLayer* old_layer = ds->GetLayerByName(CopiedName.at(i).c_str());
                OGRSpatialReference* oldsp = old_layer->GetSpatialRef();

                char* sp = NULL;
                oldsp->exportToWkt(&sp);
                cout << sp << endl;

                string nametemp = CopiedName.at(i);
                string copyname = nametemp + "temp";
                char** papszOptions = NULL;

                papszOptions = CSLSetNameValue(papszOptions, "DST_SRSWKT", sp);
                papszOptions = CSLSetNameValue(papszOptions, "FEATURE_DATASET", "K2");

                OGRLayer* templayer = ds->CopyLayer(old_layer, copyname.c_str(), papszOptions);
                CSLDestroy(papszOptions);
            }
        }
        GDALClose(ds);
    }
```

## Operating system

My machine is Windows x64.

## GDAL version and provenance

The GDAL version is 3.0.2 and the FileGDB API has been installed.

**Comment by rouault** [comment]
The FileGDB SDK is quite restrictive on the CRS it accepts and it can be tricky to convince it. The best is to use the definition of an official EPSG code.
DST_SRSWKT is not a valid options of https://gdal.org/drivers/vector/filegdb.html
To override the CRS, you might rather use the GDALVectorTranslate() API (C API of ogr2ogr) with the -a_srs option.
