### ISSUE TITLE
X-margin warp issue with statistical resampling

### ISSUE THREAD

**Issue by mdsumner** [OSGeo/gdal#6478]
I see a sampling artefact with the warper,  a one-column apparent shift - it's the very left and right of the source seems to be shifted  in the output, and only when 'average' (or sum, min, med, q1)  is used. 

( I made low-resolution version of the source I found the problem in to make it very clear and small to share). 

## Expectation: 

This is similar to what I expect to see, no pixels advanced into the Ross Sea: 

![image](https://user-images.githubusercontent.com/4107631/194255014-07a959d9-c397-49e7-8d5f-8f507ea44aec.png)

## Result (middle column shift): 

Here there seems to be a southward shift of the values at the antimeridian towards the pole (near the dot marked red): 

![image](https://user-images.githubusercontent.com/4107631/194259317-49de456a-e972-44bc-a5a6-22e21a68c6cf.png)

I found the issue on a Pacific-centred raster 0,360 but the result is the same (column shift at the 0,360 line in that case). 

This is obtained with the GeoTIFF in this file: 

```
wget https://github.com/hypertidy/vapour/files/9721390/world_ocean_ssh.zip
unzip world_ocean_ssh.zip

gdalwarp world_ocean_ssh.tif average.tif -te -6400000 -6400000 6400000 6400000 -ts 60 60 -t_srs "ESRI:102020" -r average

gdalwarp world_ocean_ssh.tif near.tif -te -6400000 -6400000 6400000 6400000 -ts 60 60 -t_srs "ESRI:102020" -r near

```

## Notes

It does not appear to be affected by SOURCE_EXTRA, SAMPLE_GRID, or SAMPLE_STEPS. 

It occurs when I use multiple inputs as intended for 'average", originally it was with ~30 inputs, I just had identified that the result was the same whether 1 or more inputs. 

There are other differences in the final distribution of nodata values, but that meridian seam is really a problem for my intended uses where the minor differences are not. I assume it's just nearest vs. interpolation-based method that a responsible for the other methods, and for example 'bilinear' does not get the issue with one or multiple inputs. 

## Artefacts 

In the first section above is a 'wget' and 'unzip' code block to get the source file. 

The two output tifs from gdalwarp above are zipped and attached here. 

[stat.zip](https://github.com/OSGeo/gdal/files/9722557/stat.zip)

## Operating system

Ubuntu  Ubuntu 20.04.5 LTS 64 bit

## GDAL version and provenance

GDAL 3.6.0dev-8eec4c1216-dirty, released 2022/10/05 (debug build)

**Comment by mdsumner** [comment]
Some extra notes I left out, edited into the above report.

**Comment by jratike80** [comment]
Do you believe that the issue is related to just "ESRI:102020" or similar coordinate reference systems?

**Comment by mdsumner** [comment]
hmm, good question - it doesn't depend on being at the south pole I use  "+proj=laea +lon_0=0 +lat_0=-90" (the equivalent of  ESRI:102020) for a range of latitudes and longitudes and it's still an issue.  But, see different aspects of the issue 

![image](https://user-images.githubusercontent.com/4107631/194314289-4c20c62d-5c78-4809-8ca6-0343f9dbf7d7.png)


![image](https://user-images.githubusercontent.com/4107631/194314440-abf46095-b580-40ac-b1e6-40101a190eb8.png)


also Lambert Conformal Conic

![image](https://user-images.githubusercontent.com/4107631/194315412-f9e6bf50-ca4d-4f5e-a6e2-616d68a82312.png)


and Stereographic

![image](https://user-images.githubusercontent.com/4107631/194315603-e3aa3431-9981-4220-a971-0f9b6aefabf9.png)


This is a rich seam for exploration so thank you for the idea, I'll come back if I find a better way to hone in on the issue.

**Comment by rouault** [comment]
Fix in https://github.com/OSGeo/gdal/pull/6482

**Comment by mdsumner** [comment]
Excellent, thanks so much @rouault and @jratike80 - this is a really big deal for us after a long road of flushing through other challenges, this is extremely powerful. 

I've confirmed on the tests above and with some very different cases as well. Very much appreciated.
