### ISSUE TITLE
Loading  *.wcs files fails. (Segmentation fault)

### ISSUE THREAD

**Issue by mitxel-m** [OSGeo/gdal#648]
## Expected behavior and actual behavior

From GDAL 2.3.0 loading a *.wcs  file makes the program to crash(qmapshack, gdalinfo, ...), and I get "Segmentation fault"  

I have checked with several *.wcs files and all of them failed from GDAL 2.3.0 ( So far I have been working with with the same *.wcs files with no problem in previous GDAL releases )

I have also tested on different OS / GDAL combinations in the same PC, and all of them failed from GDAL 2.3.0

## Steps to reproduce the problem
`gdalinfo ESP_IGN-MDT25.wcs`    __FAILS__    I get Segmentation fault.

`gdalinfo WCS:http://www.ign.es/wcs/mdt?`  __OK !!__  As expected, It connects with the server and retrieves the info about the WCS

## Operating system
* Linux Mint 18.3 64bits
* Win10 64 bits in a VM for testing

## GDAL version and provenance
* (Linux)  GDAL 2.3.0 self compiled  --> Fails
* (win10) GDAL 2.3.0 from [GisInternals](http://download.gisinternals.com/sdk/downloads/release-1911-x64-gdal-2-3-0-mapserver-7-0-7.zip)--> Fails
* (win10) GDAL 2.4.0dev from GisInternals (daily) --> Fails
* (win10) GDAL 2.2.3 from [GisInternals](http://download.gisinternals.com/sdk/downloads/release-1911-x64-gdal-2-2-3-mapserver-7-0-7.zip) --> OK !!

## Hardware 
* 4 Gb RAM

## Sample .wcs file
The attached sample file `ESP_IGN-MDT25.wcs` should get elevation data from Spanish IGN

```
 <WCS_GDAL>
   <ServiceURL>http://www.ign.es/wcs/mdt?</ServiceURL>
   <CoverageName>mdt:Elevacion25830_25</CoverageName>
   <Version>1.0.0</Version>
 </WCS_GDAL>
```
[sample.zip](https://github.com/OSGeo/gdal/files/2045976/sample.zip)

**Comment by jratike80** [comment]
I had a try by editing the WCS version in the .wcs file to 2.0.1. That prevents the crash but does not work either because some probing request fails.

```
WCS: Requesting http://www.ign.es/wcs/mdt?SERVICE=WCS&REQUEST=GetCoverage&VERSION=2.0.1&COVERAGEID=m
dt%3AElevacion25830_25&SUBSET=E%284895212.1990754111,4895162.1990754111%29&SUBSET=N%28-88767.6488786
7612,-88767.648878676118%29&Format=image/tiff
HTTP: Fetch(http://www.ign.es/wcs/mdt?SERVICE=WCS&REQUEST=GetCoverage&VERSION=2.0.1&COVERAGEID=mdt%3
AElevacion25830_25&SUBSET=E%284895212.1990754111,4895162.1990754111%29&SUBSET=N%28-88767.64887867612
,-88767.648878676118%29&Format=image/tiff)
HTTP: libcurl/7.37.1 OpenSSL/1.0.1h zlib/1.2.3
ERROR 1: HTTP error code : 404
ERROR 1: InvalidSubsetting: Low greater than High
```

**Comment by ajolma** [comment]
Using a self-made .wcs file is the old way (i.e. not using the cache+letting the driver manage the files), which should of course still work. The driver fails (and dumps core) in this case because the metadata (.aux.xml) file is not there (I assume it should be done to fix the bug). If I make a stub metadata file
```
<PAMDataset>
  <Metadata>
    <MDI key="x">y</MDI>
  </Metadata>
</PAMDataset>
```
(There needs to be one key to prevent a nullptr from GetMetadata() call) the call `gdalinfo ESP_IGN-MDT25.wcs` does not fail and probably returns correct info. Probably the code should also test for nullptr return from GetMetadata() to fix this bug.

mitxel-m, if you make above kind of metadata file, are there any more errors in your workflow?

**Comment by ajolma** [comment]
The "Low greater than High" error comes from GeoServer. I assume it is expecting some parameters to be set but I need to investigate more.

**Comment by ajolma** [comment]
calling 
`gdalinfo WCS:http://www.ign.es/wcs/mdt?version=2.0.1`
seems to work, and it also seems to suggest using version 1.0.0

**Comment by mitxel-m** [comment]
After last commit , I have been testing with the same   .wcs files and it works for me now .
Thanks for this quick fix !!!
