### ISSUE TITLE
Python bindings: add mapFieldType option to gdal.VectorTranslate()

### ISSUE THREAD

**Issue by vianmora** [OSGeo/gdal#6486]
Hello :) 

I searched for some project to add new options to vector translate, but i found nothing, 
for my project, i could need the `mapFieldType` option, 

Is it possible to add it ? Or someone could help me to do it please ?  

I found [this commit](https://github.com/OSGeo/gdal/commit/1c6f9839082f81b3906048f7160fee82adc96822) I could be inspired of, but as i'm new in the open source game, i wouldn't do something bad :/ 

It also could be the moment to add all the new options that are compatible with ogr2ogr : https://gdal.org/programs/ogr2ogr.htm  
- mapFieldType
- preserve_fid
- fid
- geomfield
- gt
- clipsrs, clipsrclayer, clipsrcwhere, clipdst, clipdstsql, clipdstlayer, clipdstwhere, 
- wrapdateline
- datelineoffset
- segmentize
- unsetFid
- relaxedFieldNameMatch
- unsetDefault
- fieldTypeToString
- unsetFieldWidth
- fieldmap
- splitlistfields
- maxsubfields
- explodecollections
- zfield 
- gcp
- s_coord_epoch , t_coord_epoch , a_coord_epoch 
- nomd
- mo
- noNativeData

**Comment by rouault** [comment]
> I found [this commit](https://github.com/OSGeo/gdal/commit/1c6f9839082f81b3906048f7160fee82adc96822) I could be inspired of, but as i'm new in the open source game, i wouldn't do something bad :/

Yes you could certainly take inspiration from that to add new option(s). Don't be afraid to submit a PR. This will not do any harm. See https://github.com/OSGeo/gdal/blob/master/CONTRIBUTING.md first
