### ISSUE TITLE
GDAL_VALIDATE_CREATION_OPTIONS doesn't work as expected

### ISSUE THREAD

**Issue by drnextgis** [OSGeo/gdal#6487]
It might be that I misunderstood the purpose of [GDAL_VALIDATE_CREATION_OPTIONS](https://github.com/OSGeo/gdal/blob/c221336ec64b1b8be3f99d55783f0eca2b733f44/gcore/gdaldriver.cpp#L134) but it doesn't work in this very simple case:

```
$ GDAL_VALIDATE_CREATION_OPTIONS=NO ogr2ogr -lco ENCODING=UTF8 -f LIBKML data.kml data.geojson
Warning 6: dataset data.kml does not support layer creation option ENCODING
```

Also the option isn't listed [here](https://gdal.org/user/configoptions.html).

**Comment by jratike80** [comment]
Some config options are documented only in the the old wiki page. https://trac.osgeo.org/gdal/wiki/ConfigOptions#GDAL_VALIDATE_CREATION_OPTIONS

> When using GDALDriver::Create() or GDALDriver::CreateCopy() (for example when using the -co option of gdal_translate or gdalwarp utilies) , GDAL checks by default that the passed creation options match the syntax of the allowed options declared by the driver. If they don't match the syntax, a warning will be emitted. There should be hardly any reason to set this option to FALSE, as it's either a sign of a user typo, or an error in the declared options of the driver. The latter should be worth a bug report.

It seems that this configuration option is made for skipping the validation of GDAL raster creation options `-co`, not the vector side OGR layer creation options `-lco`.

**Comment by drnextgis** [comment]
Thank you @jratike80. It would be nice to have it for OGR as well.

**Comment by drnextgis** [comment]
Thank you Even!
