### ISSUE TITLE
Polygon points sequence changed automatically after save to shape file

### ISSUE THREAD

**Issue by muyanchen-zen** [OSGeo/gdal#6493]
I read from my shp file and save all the data directly without any other operation, but it turned out some of my polygons' (wkbPolygon25D) points sequence reversed. Is there any way to control it?

**Comment by jratike80** [comment]
Did you notice this

> IMPORTANT: Do NOT use GitHub to post any questions or support requests!
>            They will be closed immediately and ignored.
> 
> Questions should go to the gdal-dev mailing list at
> https://lists.osgeo.org/mailman/listinfo/gdal-dev
> or other support forums. GitHub issues are for bug
> reports and suggestions for new features.
> 

Maybe the configuration option that is documented in https://gdal.org/drivers/vector/shapefile.html could help

> SHAPE_REWIND_ON_WRITE can be set to NO to prevent the shapefile writer to correct the winding order of exterior/interior rings to be conformant with the one mandated by the Shapefile specification. This can be useful in some situations where a MultiPolygon passed to the shapefile writer is not really a compliant Single Feature polygon, but originates from example from a MultiPatch object (from a Shapefile/FileGDB/PGeo datasource).

Or you can use the SQLite dialect and Spatialite functions ForcePolygonCW or ForcePolygonCCW https://www.gaia-gis.it/gaia-sins/spatialite-sql-latest.html.
