### ISSUE TITLE
Failed to open the data created by the OpenFIleGDB Driver in ArcMap

### ISSUE THREAD

**Issue by Hsxxxxxx** [OSGeo/gdal#6494]
## Expected behavior and actual behavior.

Failed to open FeatureLayer in arcmap10.1 software after exporting the data in postgis to gdb.
postgis data: data.zip/pg_data_backup
error data: data.zip/gdal360_openfilegdb.gdb( By OpenFIleGDB Driver)
normal data: gdal342_filegdb.gdb ( By FIleGDB Driver)

## Error Message
Error opening feature class
Project is not defined. [point]
Project is not defined.
The XML file being loaded cannot be parsed. [physical name: POINT]
Project is not defined. [point]
Project is not defined.
The XML file being loaded cannot be parsed. [physical name: POINT]
No class registered 

## Operating system
Desktop: Windows10 + ArcMap10.1 

## GDAL version and provenance
docker images: osgeo/gdal:ubuntu-small-latest(amd)
docker images: osgeo/gdal:ubuntu-small-latest-arm64(arm)

[data.zip](https://github.com/OSGeo/gdal/files/9744690/data.zip)

**Comment by Hsxxxxxx** [comment]
Some exported data can be opened using arcmap, and no error message is prompted in the exported python program. Perhaps it is a problem with FID Column or Geometry Column?

**Comment by jratike80** [comment]
I get similar error for all three layers (line, point, polygon) with ArcMap 10.8. I try to test also with ArcGIS Pro if I manage to start it.

**Comment by rouault** [comment]
@Hsxxxxxx @jratike80 I suspect this might have something to do with how default values are declared. Would you mind testing the following datasets from [data_rouault.zip](https://github.com/OSGeo/gdal/files/9747703/data_rouault.zip) produced with:
```
ogr2ogr sdk_RHEL7_64gcc83.gdb gdal360_openfilegdb.gdb -f filegdb
ogr2ogr sdk_RHEL7_64gcc83_no_default_value.gdb gdal360_openfilegdb.gdb -f filegdb -unsetdefault
ogr2ogr openfilegdb_no_default_value.gdb gdal360_openfilegdb.gdb -f openfilegdb -unsetdefault
```

In the first one (sdk_RHEL7_64gcc83_gdb), I observe that the generated XML by the SDK is different, using "http://www.esri.com/schemas/ArcGIS/10.3" namespace whereas "gdal342_filegdb.gdb" uses "http://www.esri.com/schemas/ArcGIS/10.1", and there are slight differences in which default values are registered. The openfilegdb driver produces something as close as possible to the output of the sdk_RHEL7_64gcc83.

I would also welcome a fresh new filegdb generated by ArcMap and/or ArcGIS Pro with a integer and double columns that have a default value.

**Comment by jratike80** [comment]
Part 1: all layers from all gdb files in your zip open without errors with ArcMap.

**Comment by rouault** [comment]
could you test openfilegdb_with_xmlns_xs.gdb [openfilegdb_with_xmlns_xs.gdb.zip](https://github.com/OSGeo/gdal/files/9747980/openfilegdb_with_xmlns_xs.gdb.zip) generated from ``ogr2ogr openfilegdb_with_xmlns_xs.gdb gdal360_openfilegdb.gdb -f openfilegdb`` with the driver with the fix of https://github.com/OSGeo/gdal/pull/6496 ?

**Comment by jratike80** [comment]
No errors with ArcMap 10.8.

**Comment by Hsxxxxxx** [comment]
@rouault @jratike80 
Thank you for your help, I have finished compiling and testing, and the commit can effectively solve this problem
[https://github.com/rouault/gdal/commit/951103c0c8a73cbdb4ec7a9e8218236439de00c2](https://github.com/rouault/gdal/commit/951103c0c8a73cbdb4ec7a9e8218236439de00c2)
