### ISSUE TITLE
`gdal_retile.py -pyramidOnly` shouldn't require `input_files`

### ISSUE THREAD

**Issue by dhardestylewis** [OSGeo/gdal#6512]
@rouault 

## Expected behavior and actual behavior.

For example (please modify !!!): I expected to be able to open this raster file (with a link to
the raster file, or it as an attachment) and it returns an error message
instead.

`gdal_retile.py -pyramidOnly` shouldn't require `input_files`

## Steps to reproduce the problem.

For example (please modify !!!): "gdalinfo myfile"

```bash
ls -1 TileDirectory
```
```
tile_1_1.png
tile_1_2.png
tile_2_1.png
tile_2_2.png
```
```bash
gdal_retile.py -pyramidOnly -targetDir TileDirectory
```
```
No input files selected.
Usage: gdal_retile.py 
        [-v] [-q] [-co NAME=VALUE]* [-of out_format]
        [-ps pixelWidth pixelHeight]
        [-overlap val_in_pixel]
        [-ot  {Byte/Int16/UInt16/UInt32/Int32/Float32/Float64/
               CInt16/CInt32/CFloat32/CFloat64}]
        [ -tileIndex tileIndexName [-tileIndexField fieldName]]
        [ -csv fileName [-csvDelim delimiter]]
        [-s_srs srs_def]  [-pyramidOnly] -levels numberoflevels
        [-r {near/bilinear/cubic/cubicspline/lanczos}]
        [-useDirForEachRow] [-resume]
        -targetDir TileDirectory input_files
```

## Operating system

For example (please modify !!!): Ubuntu 16.04 64 bit

Any

## GDAL version and provenance

For example (please modify !!!): the 2.2.3 version from ubuntugis-unstable PPA

as of `GDAL 3.5.2, released 2022/09/02`

**Comment by rouault** [comment]
> `gdal_retile.py -pyramidOnly` shouldn't require `input_files`

well, that's how it is intended to work. Changing that would likely require a significant rework of the utility
Closing as won't fix

**Comment by dhardestylewis** [comment]
Am I correct in understanding `gdal_retile.py`'s pyramids are resampled from underlying levels, or are the resampled directly from `input_files`?

**Comment by rouault** [comment]
> Am I correct in understanding `gdal_retile.py`'s pyramids are resampled from underlying levels, or are the resampled directly from `input_files`?

should be answered by df62fd238a2e0b7ae365aed047a991c2b7333974
