### ISSUE TITLE
VSIMemFile 16bit support

### ISSUE THREAD

**Issue by luckyroooo** [OSGeo/gdal#6517]
I found it unable to create a VSIMemFile from a 16-bit in memory buffer. 
Could you please add in anything about VSIMemFile 16-bit support?

**Comment by jratike80** [comment]
IMPORTANT: Do NOT use GitHub to post any questions or support requests!
           They will be closed immediately and ignored.

Questions should go to the gdal-dev mailing list at
https://lists.osgeo.org/mailman/listinfo/gdal-dev
or other support forums. GitHub issues are for bug
reports and suggestions for new features.
