### ISSUE TITLE
gdalwarp not working correctly on Apple M1, USE_OPENCL=NO not making a difference

### ISSUE THREAD

**Issue by alvanelz** [OSGeo/gdal#6519]
## Expected behavior and actual behavior.

Trying to rescale any file with gdalwarp produces blocky results on my Apple M1 2020 machine (macOS 12.6). 

## Steps to reproduce the problem.
Download this example dem: https://tiles.calazoffice.biz/gdal/dem.tif
Running `gdalwarp -tr 4 4 dem.tif 4m.tif` produces this file (shown with hillshade rendering to exaggerate the problem):
<img width="645" alt="Skärmavbild 2022-10-13 kl  09 29 09" src="https://user-images.githubusercontent.com/115692716/195530662-9ef5f5c7-74ba-47bb-a536-455b45f3997c.png">

You can download the output file here: https://tiles.calazoffice.biz/gdal/output.tif

I have tried -wo USE_OPENCL=NO with no difference in the output.

Here is the debug output:
```
GDAL: GDALOpen(dem.tif, this=0x15660e550) succeeds as GTiff.
GDAL: Using GTiff driver
GDAL: Computing area of interest: 11.3527, 59.2323, 11.3648, 59.2371
Creating output file that is 166P x 123L.
GDAL: GDALDriver::Create(GTiff,debug.tif,166,123,1,Float32,0x0)
Processing dem.tif [1/1] : 0WARP: Copying metadata from first source to destination dataset
GTiff: ScanDirectories()
GDAL: GDALDefaultOverviews::OverviewScan()
Using internal nodata values (e.g. -32767) for image dem.tif.
Copying nodata values from source dem.tif to destination debug.tif.
WARP: srcNoData=-32767.000000 dstNoData=-32767.000000
WARP: calling GDALSetRasterNoDataValue() for band#0
GDALWARP: Defining SKIP_NOSOURCE=YES
GDAL: GDAL_CACHEMAX = 819 MB
GDAL: GDALWarpKernel()::GWKNearestFloat() Src=0,0,665x493 Dst=0,0,166x123
...10...20...30...40...50...60...70...80...90...100 - done.
GDAL: Flushing dirty blocks: 0...10...20...30...40...50...60...70...80...90...100 - done.
GTiff: Adjusted bytes to write from 7968 to 1992.
GDAL: GDALClose(debug.tif, this=0x15663e220)
GDAL: GDALClose(dem.tif, this=0x15660e550)
```

## GDAL version and provenance
GDAL 3.5.2 from homebrew.

Here are some related issues I found:
- https://github.com/OSGeo/gdal/issues/5155
- https://github.com/OSGeo/gdal/issues/4754

**Comment by jratike80** [comment]
The hillshade created from the output.tif with the QGIS hillshade function looks good on my computer. Did you share the right file?

<img width="264" alt="image" src="https://user-images.githubusercontent.com/1751612/195535618-c9041a45-08d8-493c-9c69-6592dc6dd8cb.png">

I tried also more suitable resampling methods for your original dem.tif (average and cubic) but they did not make a big difference so the default resampling (nearest neighbor) does not explain your artifacts. Have you a possibility to test with Linux or Windows?

**Comment by alvanelz** [comment]
Oops! Sorry. I was confused when I saw the output in QGIS and it showed the blocky output, since it probably still uses OpenCL. But the file itself is fine as you say. Closing this issue.
