### ISSUE TITLE
'ERROR 1: PROJ: proj_create_from_database: crs not found' when running gdalinfo on geospatial PDF

### ISSUE THREAD

**Issue by AndrewAtAvenza** [OSGeo/gdal#6522]
#### Problem description

When I run `gdalinfo` on the attached PDF file, it will print out the WKT but it will also spit out error:

```
ERROR 1: PROJ: proj_create_from_database: crs not found
```

beforehand. This did not happen in GDAL 2.4 (I can't speak for any other versions).

#### Environment Information

I used pre-built GDAL 3.5.2 binaries from OSGeo4W. They ship with DLLs of both PROJ 9.0 & 9.1, so I'm not actually sure which version of PROJ was used when I ran `gdalinfo`.

#### Installation method

I downloaded the binaries from OSGeo4W.

[11.2 - Cape Spear Path - Blackhead to Maddox Cove GEO.pdf](https://github.com/OSGeo/PROJ/files/9778407/11.2.-.Cape.Spear.Path.-.Blackhead.to.Maddox.Cove.GEO.pdf)

**Comment by rouault** [comment]
transferring as a GDAL issue

**Comment by rouault** [comment]
fix in https://github.com/OSGeo/gdal/pull/6523
