### ISSUE TITLE
License question 

### ISSUE THREAD

**Issue by hrieke** [OSGeo/gdal#6524]
@atlight 
The file:
dxf/intronurbs.cpp contains a BSD 3-clause license, however the license notice on David F. Rodger's page (https://www.nar-associates.com/nurbs/c_code.html) states "Each of the C implementations is copyrighted by the author. Noncommercial use is authorized. Commercial use requires written permission of the author.".

Is it documented anywhere that he donated his code under the BSD 3-Clause or where this code was picked up from?

Thanks!

**Comment by rouault** [comment]
This would rather be a question for @warmerdam since intronurbs was added long time ago per a754362ed384c40b17825292ad607eec73302526

**Comment by warmerdam** [comment]
I have an email thread from 2009 and early 2010 in which Dave agreed to BSD license the code in question.  I could provide it if needed.   The final email in the series read:

"""
G'day Frank,

No worries. I have looked at the material you linked
below and I am good with it.

Thanks again,

Dave Rogers

Frank Warmerdam wrote:
> dfr wrote:
>> G'day Frank,
>>
>> Thanks for doing this. My initial reaction is that it looks fine.
>> I made very slight changes to the COPYING and README files.
>> I have attached the changed files.
>
> David,
>
> I realize I must have neglected to reply to this message.  I have
> incorporated the suggested README and COPYING changes.
>
>> What would you think about attaching a list of references to the
>> README file? Some of the references are no longer readily available
>> but over time I might be able to reset them and put them on the website.
>> However, there is no need to delay release for that.
>
>> Where do we want to host the release: with you? on the Intro to NURBS
>> page? or both? Is there a standard place to submit a package?
>
> I have placed them off my projects page at:
>
>   http://home.gdal.org/projects/intronurbs/index.html
>
> You can grab the .tar.gz and .zip files from their and also host them
> on your page.  Let me know if you would like any other adjustments, added
> references, etc.  Your website is really still the master reference for all
> such material of course.
>
> The portion of this material that I need for my spline interpolation is
> captured in the file:
>
>   http://svn.osgeo.org/gdal/trunk/gdal/ogr/ogrsf_frmts/dxf/intronurbs.cpp
>
> Please let me know if you would like any adjustements to the prelude text
> on this file.   I have also added a segment in the overall GDAL
> "LICENSE" file
> which is user visible - it is at the end of:
>
>   http://svn.osgeo.org/gdal/trunk/gdal/LICENSE.TXT
>
> This file is intended to contain any credits and other notices required for
> subcomponents of the GDAL library.
>
> Best regards,
"""

**Comment by hrieke** [comment]
Thanks!

**Comment by rouault** [comment]
Precision added in source code in 5617daabf4
