### ISSUE TITLE
warp issues when target is not aligned

### ISSUE THREAD

**Issue by rhijmans** [OSGeo/gdal#6526]
We have been seeing issues with gdalwarp when the input and output raster are not aligned. That is, when the (smaller) input cells cross the (larger) output cell borders. Please see [here](https://github.com/rspatial/terra/issues/847) for illustrations. Most of it the examples use R package "terra". terra calls the C API, but I also show that the same problem happens with the gdalwarp command line tool.

This happens with GDAL 3,4,3 and 3.5.2; but it does not happen with GDAL 2.2.3

**Comment by rouault** [comment]
Please provide here input & output files and gdalwarp invokations

**Comment by rhijmans** [comment]
with GDAL 3,4,3 and 3.5.2 
```
gdalwarp f.tif -te 0.025 0.025 1.025 1.025 -tr .2 .2 -r max -overwrite max.tif
```

`max.tif` is not correct 

with GDAL 2.2.3 

```
gdalwarp f.tif -te 0.025 0.025 1.025 1.025 -tr .2 .2 -r max -overwrite out.tif
```
`out.tif` is correct 

The files are [here](https://github.com/rspatial/files)
