### ISSUE TITLE
INGR driver deprecated / removed

### ISSUE THREAD

**Issue by lupynos** [OSGeo/gdal#6549]
## Expected behavior and actual behavior.

There is deprecated/removed driver INGR for handling CIT files, conversion to more common raster format TIFF etc. So this ticket is used for those who need use GDAL to convert CIT files in the future with GDAL (or QGIS using GDAL).

Behaviour is expected, driver was deprecated in version GDAL 3.4.3 (can be activated by set GDAL_ENABLE_DEPRECATED_DRIVER_INGR=true) and was removed in 3.5.x branch.

## Steps to reproduce the problem.

(batch script)
```
for /r %%I in (*.cit) do gdal_translate -of GTiff -a_nodata 0 -co NBITS=1 -co COMPRESS=CCITTFAX4 -co TFW=NO -co TILED=YES --config GDAL_PAM_ENABLED FALSE --config GDAL_CACHEMAX 2047 --config GDAL_GEOREF_SOURCES WORLDFILE %%~I %%~nI.tif
```

## Operating system

Windows 10

## GDAL version and provenance

GDAL 3.4.3 and 3.5.x builds from GISInternals Support Site
(and also QGIS using this versions of GDAL)

**Comment by rouault** [comment]
Thanks for the hint for future readers.
I'm going to close the ticket though, as there's no action needed from the maintainers, and we want to keep the list of opened tickets only to actionable tickets. People can still search in closed tickets.
