### ISSUE TITLE
Control the number of overviews in cog using ZOOM_LEVEL

### ISSUE THREAD

**Issue by IdanAviv89** [OSGeo/gdal#6555]
Hi, 
I am trying to create cog and control the number of overviews created. 
I am using the following command:
`gdal_translate la.tif output_cog4.tif -of COG -co COMPRESS=WEBP -co QUALITY=100 -co OVERVIEW_COMPRESS=WEBP -co OVERVIEW_QUALITY=100 -co NUM_THREADS=ALL_CPUS -co ZOOM_LEVEL=1 -co OVERVIEWS=IGNORE_EXISTING `
This dose't change the number of overviews created.

In the documentation it says that I need to change the TILING_SCHEME from custom, but when I try to put the "other" option I get the following response:
`ERROR 1: Invalid tiling matrix set name`

Am I doing something wrong ?

Thanks in advance,
Idan 

using version 3.6

**Comment by rouault** [comment]
you are supposed to replace "other" by a meaningful value :-).  cf the list returned by gdalinfo --format COG (this list is dynamically built from the content of the GDAL data directory). Should be clarified per a34adc3a95c70cf54ac67893f4f5275140450ffa

**Comment by IdanAviv89** [comment]
Sorry my bad :).
Is there a way to control the number of overview created without the TILING_SCHEME. 
Why would custom TILING_SCHEME can't have customize number of overviews ?

**Comment by rouault** [comment]
> Is there a way to control the number of overview created without the TILING_SCHEME. Why would custom TILING_SCHEME can't have customize number of overviews ?

no. the COG driver was intended to be dead simple for users, but people keep asking for more complexity/features in it in available options. Control on the number of overviews could be implemented quite simply, but it isn't currently

**Comment by IdanAviv89** [comment]
Got it.
This option is also not supported in the GTIFF driver, am I right ?

**Comment by rouault** [comment]
> This option is also not supported in the GTIFF driver, am I right ?

the geotiff driver doesn't automatically create overviews. You have to use gdaladdo. The main difference of the COG driver w.r.t GTiff one is to do both at the same time

**Comment by IdanAviv89** [comment]
`no. the COG driver was intended to be dead simple for users, but people keep asking for more complexity/features in it in available options. Control on the number of overviews could be implemented quite simply, but it isn't currently`

I actually think that having the ability to control the number of overviews created is really basic functionality. The alternative way to do such a simple task is way too complex, having to use both gdal_translate and gdaladdo. And then having to use something to make the tif to cog, like cogger or again gdal_translate(which is slow). While cogger is really great, using it introduce more complexity (having to deal with Golang and .so or dll files). I believe that having a really basic parameter (like zoom_level and number_of_overviews) that limits the number of overviews, will actually simplify the use of cog and promote others to use it.

I actually made a simple parameter to control the number of overviews when using the IGNORE_EXISTING option. Here is a link to my [fork](https://github.com/IdanAviv89/gdal/tree/NUMBER_OF_OVERVIEWS).

**Comment by jratike80** [comment]
My personal view is that very few COG users care about the number of overviews because the default is good for them but I may be wrong. Could you explain what is your use case and why do you need to control the number of overviews? I guess that you want to skip first one or two overviews so that the full resolution uncompressed data are used and change to the compressed overviews only a bit later.

**Comment by IdanAviv89** [comment]
In my case I found out that having less overviews improve the user experience on streaming (having less get request and using more of the cache). I believe that are many more user how would enjoy the freedom of deciding how many overviews to have on the raster (look at cogger for example, which it’s main functionally is customize the overviews).

**Comment by jratike80** [comment]
Would you recommend that less overviews should be the new default? What set of overviews has been proved best in your tests? I do not mean that it could not be selectable by the users but most users rather use the defaults than go to learning the details about how to optimize. I understand that fine tuning can be important for big cloud data providers.

**Comment by IdanAviv89** [comment]
In my case the lower resolution overviews made the streamer slower. I don’t know if it should be the new default, it might change base on the use case. I believe that have such an optional parameter will let more advance use cases without adding complexity for those how don’t need it.

**Comment by rouault** [comment]
please file an enhancement ticket about that. I guess that the OVERVIEW_LEVEL creation option can be repurposed for the CUSTOM tiling scheme. If you say your raster is at OVERVIEW_LEVEL=2, then 2 overviews need to be created (level 1 and level 0).
