### ISSUE TITLE
Why is the result about method GetGeometryCount()？

### ISSUE THREAD

**Issue by catofmrlu** [OSGeo/gdal#6572]
```python
geom = ogr.CreateGeometryFromWkt("POLYGON((1 1,5 1,5 5,1 5,1 1),(2 2,2 3,3 3,3 2,2 2))")
count = geom.GetGeometryCount()   //the result  is 2
print(count) 
```
the above result is 2,howevver, POLYGON((1 1,5 1,5 5,1 5,1 1),(2 2,2 3,3 3,3 2,2 2)) is one.
is it  a issue?

**Comment by rouault** [comment]
see https://gdal.org/api/vector_c_api.html#_CPPv422OGR_G_GetGeometryCount12OGRGeometryH
"For a polygon, the returned number is the number of rings (exterior ring + interior rings)."
