### ISSUE TITLE
Cannot read from public S3 bucket with /vsis3

### ISSUE THREAD

**Issue by simoneves** [OSGeo/gdal#658]
## Expected behavior and actual behavior.

Using either the API, or simply "ogrinfo"...

I am unable to read a file in a public S3 bucket using the /vsis3 VSI path syntax

I can read it using /vsicurl and the full https://s3-$REGION.amazonaws.com/$BUCKET/... URL

I can read files from both public *and* private buckets using the /vsis3 syntax if I have AWS_* env vars set or if I set values for them using CPLSetConfigOption when using the API.

## Steps to reproduce the problem.

// AWS_* env vars NOT set
ogrinfo -ro /vsis3/$PUBLIC/file.geojson (fail; NOT expected)
ogrinfo -ro /vsis3/$PRIVATE/file.geojson (fail; expected)
ogrinfo -ro /vsicurl/https://s3-$REGION.amazonaws.com/$PUBLIC/file.geojson (success; expected)
ogrinfo -ro /vsicurl/https://s3-$REGION.amazonaws.com/$PRIVATE/file.geojson (fail; expected)

// AWS_* env vars set
ogrinfo -ro /vsis3/$PUBLIC/file.geojson (success)
ogrinfo -ro /vsis3/$PRIVATE/file.geojson (success)
ogrinfo -ro /vsicurl/https://s3-$REGION.amazonaws.com/$PUBLIC/file.geojson (success; expected)
ogrinfo -ro /vsicurl/https://s3-$REGION.amazonaws.com/$PRIVATE/file.geojson (fail; expected)

## Operating system

Ubuntu 17.10 and CentOS 6

## GDAL version and provenance

GDAL 2.2.3 and 2.2.4

**Comment by rouault** [comment]
For /vsis3/$PUBLIC/file.geojson , you need to define AWS_NO_SIGN_REQUEST=YES. This was added in GDAL 2.3.0

**Comment by simoneves** [comment]
To be clear, GDAL 2.2.x cannot read from public buckets using /vsis3 without auth? We need to upgrade to 2.3 and set AWS_NO_SIGN_REQUEST?

**Comment by rouault** [comment]
> To be clear, GDAL 2.2.x cannot read from public buckets using /vsis3 without auth? We need to upgrade to 2.3 and set AWS_NO_SIGN_REQUEST?

yes
