### ISSUE TITLE
MRF format gdal crash

### ISSUE THREAD

**Issue by wklechka** [OSGeo/gdal#6581]
## Expected behavior and actual behavior.

Open an MRF file.  Crash on overviews.

## Steps to reproduce the problem.

Will not happen on a small MRF.  It needs to make overviews to fail.  Specifically when the overviews are added in MRFDataset::AddOveriews the list of overviews are bad because variable poDS is null.  The overviews are created just fine, but the crash happens when the overviews are used.

How to fix the problem...I went ahead and debugged it to find the problem.  

In mrf_band.cpp:

In older version of mrf_band.cpp the variable poDS(parent_dataset) was set.  This is missing in the new version and replaced with poMRFDS(parent_dataset),  I fixed it by just re-added poDS(parent_dataset) along with poMRFDS(parent_dataset)

So the constructor needs both variable set like this:
MRFRasterBand::MRFRasterBand( MRFDataset *parent_dataset,
                                      const ILImage &image, int band, int ov ) :
    poMRFDS(parent_dataset),
    poDS(parent_dataset),
    dodeflate(GetOptlist().FetchBoolean("DEFLATE", FALSE)),
    // Bring the quality to 0 to 9
    deflate_flags(image.quality / 10),
    dozstd(GetOptlist().FetchBoolean("ZSTD", FALSE)),
    zstd_level(9),
    m_l(ov),
    img(image)
{
...
}

## Operating system
Windows 10

## GDAL version and provenance
3.6, latest out of github

**Comment by rouault** [comment]
I don't manage to reproduce a crash doing:
```
gdal_translate autotest/gcore/data/byte.tif byte.mrf -outsize 2048 2048
gdaladdo byte.mrf 2 4 8
gdal_translate byte.mrf out.tif -outsize 128 128
```
where autotest/gcore/data/byte.tif is https://github.com/OSGeo/gdal/blob/master/autotest/gcore/data/byte.tif

Could you give a reproducible procedure, preferably just using GDAL command line utilties, to reproduce the issue ?

**Comment by wklechka** [comment]
Sorry for not being more clear.  The issue happens on reading of a MRF that has overviews and the overview is actually used.

The test you did likely does not use overviews and hence fails to reproduce the error.  I discovered the error in my own code and I don't know what gdal utility would generate it.  

So to reproduce the issue you need an MRF with overviews and you need to make a call to IRasterIO that actually uses an overview.  If an overview is not actually used the issue will not be reproduced.  The MRF I was testing ends up constructing a JPEG_Band derived from MRFRasterBand.  I don't this being a JPEG_Band is the problem.  But I believe MRFRasterBand constructors needs to set poDS(parent_dataset) because later on poDS is dereferenced and it crashes because it was null.  Adding this fix seems to solve my issue.

When reading an MRF you need to land inside this IF to reproduce the problem:
In rasterio.cpp in IRasterIO() you need to land inside this IF:
/* ==================================================================== */
/*      Do we have overviews that would be appropriate to satisfy       */
/*      this request?                                                   */
/* ==================================================================== */
    if( (nBufXSize < nXSize || nBufYSize < nYSize)
        && GetOverviewCount() > 0 && eRWFlag == GF_Read )
		{
		..
		}


The overviews are created previously created in:
marfa_dataset.cpp in fucntion AddOverviews().  newMRFRasterBand() constructs the band and is where I believe the problem is.
When one of these overveiws is used in IRasterIO the crash will happen.

If you need a sample MRF I have some around 30MB.  Let me know if you need me to send it to you.

**Comment by rouault** [comment]
> The test you did likely does not use overviews and hence fails to reproduce the error.

it does. "gdal_translate byte.mrf out.tif -outsize 128 128" does use overviews, and I do get in the code path of line 379 of rasterio.cpp.
I also tried with JPEG compression, and still no crash

> If you need a sample MRF

Yes, please. maybe just try to attach it here as a .zip file (or a reduced version that can reproduce the issue), or through some file sharing solution

**Comment by wklechka** [comment]
[SU6975-RGB-12cm.mrf.aux.zip](https://github.com/OSGeo/gdal/files/9883077/SU6975-RGB-12cm.mrf.aux.zip)

I've attached an MRF.  If this one works for you, then I will need to further investigate.

**Comment by rouault** [comment]
``gdal_translate SU6975-RGB-12cm.mrf out.tif -outsize 128 128`` works for me

**Comment by wklechka** [comment]
I reverted my change so I could see the exact spot it crashed.
![screen shot](https://user-images.githubusercontent.com/83663999/198402343-e7654347-1442-4e1c-8d13-2a152af6dd12.jpg)
I know this does not help much, but when MEMRasterBand gets called the poDIn is null and GetAccess crashes.  Maybe something in the callstack will help?  Maybe my code path is not the same.  Anyway, if you can't reproduce it; then I guess we can close it.

**Comment by wklechka** [comment]
Maybe the resampling cause me to use a different code path and maybe this is why poDS in now actually used and caused the crash?

**Comment by rouault** [comment]
issue reproduced and fixed per https://github.com/OSGeo/gdal/pull/6586
The key was indeed to use a resampling method != nearest.
