### ISSUE TITLE
S3 ConfigOptions stick at first set value in 2.3 when using AWS_NO_SIGN_REQUEST

### ISSUE THREAD

**Issue by simoneves** [OSGeo/gdal#659]
## Expected behavior and actual behavior.

Setting S3 authentication tokens using C++ API CPLSetConfigOption() of AWS_REGION, AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY and AWS_NO_SIGN_REQUEST.

Subsequent file ops behave as if those tokens stick at the first value set through the API, and later sets have no effect, even though an immediate Get reports the correct value (and hence implicitly the problem lies below the ConfigOptions layer).

## Steps to reproduce the problem.

Attached test code.

## Operating system

Ubuntu 17.10

## GDAL version and provenance

GDAL 2.3.0 (will test with 2.2.4)

**Comment by simoneves** [comment]
[gdal_test_no_keys.cpp.txt](https://github.com/OSGeo/gdal/files/2055947/gdal_test_no_keys.cpp.txt)

**Comment by simoneves** [comment]
The GDAL code for this option is very simple and I can't see how it could go wrong. I can see no code which would retain a value unexpectedly. Setting it to YES would simply cause VSIS3HandleHelper::GetConfiguration to return empty strings, and setting it to NO or NULL should take effect next time, unless that function is not called again for some reason. Trying a DEBUG build of GDAL to test this.

**Comment by rouault** [comment]
The result of VSIStatL() and other operations is cached for performance reasons.
You can call VSICurlClearCache() to clear the cache.

**Comment by simoneves** [comment]
Will test when I get to the office. If that is the case, why does the result change correctly depending on auth or no auth when *not* using the NO_SIGN option? Does something else reset the cache?

**Comment by simoneves** [comment]
Never mind. Clearing the cache before each stat fixes the problem. Thank you.
