### ISSUE TITLE
3.5.3 build failure on Fedora Rawhide with -D_FORTIFY_SOURCE=2: error: inlining failed in call to 'always_inline' 'open.localalias'

### ISSUE THREAD

**Issue by manisandro** [OSGeo/gdal#6599]
gdal-3.5.3 fails to build on Fedora Rawhide with `-D_FORTIFY_SOURCE=2`, extract:
  
    /usr/bin/g++ -DDONT_DEPRECATE_SPRINTF -DGDAL_CMAKE_BUILD -DGDAL_COMPILATION -DHAVE_AVX_AT_COMPILE_TIME -DHAVE_SSE_AT_COMPILE_TIME -DHAVE_SSSE3_AT_COMPILE_TIME -Dvsipreload_EXPORTS -I/builddir/build/BUILD/gdal-3.5.3-fedora/apps -I/builddir/build/BUILD/gdal-3.5.3-fedora/alg -I/builddir/build/BUILD/gdal-3.5.3-fedora/gcore -I/builddir/build/BUILD/gdal-3.5.3-fedora/redhat-linux-build/gcore/gdal_version_full -I/builddir/build/BUILD/gdal-3.5.3-fedora/port -I/builddir/build/BUILD/gdal-3.5.3-fedora/redhat-linux-build/port -I/builddir/build/BUILD/gdal-3.5.3-fedora/ogr -I/builddir/build/BUILD/gdal-3.5.3-fedora/ogr/ogrsf_frmts -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64  -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fvisibility=hidden -fPIC -std=gnu++11 -MD -MT autotest/cpp/CMakeFiles/vsipreload.dir/__/__/port/vsipreload.cpp.o -MF CMakeFiles/vsipreload.dir/__/__/port/vsipreload.cpp.o.d -o CMakeFiles/vsipreload.dir/__/__/port/vsipreload.cpp.o -c /builddir/build/BUILD/gdal-3.5.3-fedora/port/vsipreload.cpp
  
    /builddir/build/BUILD/gdal-3.5.3-fedora/port/vsipreload.cpp: In function 'open':
    /builddir/build/BUILD/gdal-3.5.3-fedora/port/vsipreload.cpp:950:13: error: inlining failed in call to 'always_inline' 'open.localalias': redefined extern inline functions are not considered for inlining
    950 | int CPL_DLL open( const char *path, int flags, ... )

(see https://koji.fedoraproject.org/koji/getfile?taskID=93657379&volume=DEFAULT&name=build.log).

This looks like the same issue as described here: https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/2526

The following patch fixes the problem (taken from the pipewire issue):

    diff -rupN gdal-3.5.3-fedora/port/vsipreload.cpp gdal-3.5.3-fedora-new/port/vsipreload.cpp
    --- gdal-3.5.3-fedora/port/vsipreload.cpp	2022-10-21 16:57:18.000000000 +0200
    +++ gdal-3.5.3-fedora-new/port/vsipreload.cpp	2022-11-01 11:11:12.423024266 +0100
    @@ -46,6 +46,17 @@
    // LD_PRELOAD=./vsipreload.so ls -al /vsicurl/http://download.osgeo.org/gdal/data/sqlite3
    // LD_PRELOAD=./vsipreload.so find /vsicurl/http://download.osgeo.org/gdal/data/sqlite3
    
    +
    +/*
    + * We need to export open* etc., but _FORTIFY_SOURCE defines conflicting
    + * always_inline versions. Disable _FORTIFY_SOURCE for this file, so we
    + * can define our overrides.
    + */
    +#ifdef _FORTIFY_SOURCE
    +#undef _FORTIFY_SOURCE
    +#endif
    +
    +
    #define _GNU_SOURCE 1
    #define _LARGEFILE64_SOURCE 1
    #include <stdio.h>

**Comment by rouault** [comment]
was fixed per https://github.com/OSGeo/gdal/pull/6600
