### ISSUE TITLE
Add FileGDB to the "full" docker images

### ISSUE THREAD

**Issue by rooby** [OSGeo/gdal#6605]
## Expected behavior and actual behavior.

I would like to be able to use the full GDAL docker images with the FileGDB driver.
Currently the full docker image does not support the FileGDB driver.

I assume that this omission relates to licencing, however the required Esri software is licenced under Apache 2.0 - See https://github.com/Esri/file-geodatabase-api (maybe this didn't used to be the case?)

I believe that Apache 2.0 licenced FileGDB API is the only thing required and the restricted Esri SDK isn't required.

Could this possible be added or am I missing something about the licencing and why this is currently excluded?

## GDAL version and provenance

osgeo/gdal:ubuntu-full-3.4.3

**Comment by rouault** [comment]
see https://github.com/OSGeo/gdal/issues/6408#issuecomment-1253332394

>  is licenced under Apache 2.0 

yeah, but only the binaries. Their source code isn't open. As an open source project, we avoid to ship such binaries

**Comment by rooby** [comment]
@rouault  Thanks for the link with the workarounds. 
I don't know how I didn't find that before I posted.
