### ISSUE TITLE
Syntax error when using NETCDF with vsicurl_streaming

### ISSUE THREAD

**Issue by frafra** [OSGeo/gdal#6610]
## Expected behavior and actual behavior.

I expect to be able to use `vsicurl_streaming` instead of `vsicurl` by replacing the latter with the first on the command line. It does not seem to be possible, but a syntax error is triggered:

```
$ gdallocationinfo -wgs84 -b 1 NETCDF:"/vsicurl/https://thredds.met.no/thredds/fileServer/senorge/seNorge_2018/Archive/seNorge2018_2020.nc":rr 10.407 63.431
Report:
  Location: (345P,958L)
  Band 1:
    Value: 13.8500003814697
$ gdallocationinfo -wgs84 -b 1 NETCDF:"/vsicurl_streaming/https://thredds.met.no/thredds/fileServer/senorge/seNorge_2018/Archive/seNorge2018_2020.nc":rr 10.407 63.431
ERROR 1: Failed to parse NETCDF: prefix string into expected 2, 3 or 4 fields.
```

The server seems perfectly capable of accepting ranged requests:

```
curl -I HEAD 'https://thredds.met.no/thredds/fileServer/senorge/seNorge_2018/Archive/seNorge2018_2020.nc'
curl: (6) Could not resolve host: HEAD
HTTP/1.1 200 
Server: nginx
Date: Thu, 03 Nov 2022 12:20:48 GMT
Content-Type: application/x-netcdf
Content-Length: 2202711489
Connection: keep-alive
Access-Control-Allow-Origin: *
Content-Disposition: attachment; filename="seNorge2018_2020.nc"
Accept-Ranges: bytes
Via: HTTP/1.1 r740xd-4w2cj13-k8s-aq
Strict-Transport-Security: max-age=63072000
```

## Steps to reproduce the problem.

Use `gdalinfo` or `gdalallocationinfo` with remote NETCDF resources via `vsicurl_streaming`.

## Operating system

- Ubuntu 18.04.6 LTS
- Debian GNU/Linux 11 (bullseye)
- Fedora 36

## GDAL version and provenance

- Ubuntu: 3.0.4+dfsg-1~bionic0
- Debian: 3.2.2+dfsg-2+deb11u2
- Fedora: gdal-3.4.3-1.fc36.x86_64

**Comment by rouault** [comment]
I've pushed a fix in time for GDAL 3.6.0 for that, because there was no reason not to allow /vsicurl_streaming/, but in practice, performance absolutely sucks (I didn't have patience to wait), so you're much better with using /vsicurl/
