### ISSUE TITLE
Gaps between SRTM tiles after warping to mercator

### ISSUE THREAD

**Issue by rouen-sk** [OSGeo/gdal#662]
I am using GDAL 2.2.3. on Windows 10, to process SRTM (SRTMGL1) in order to create hillshade files to be further rendered with mapnik. This is my processing "pipeline" for single file:
```
gdal_translate -of GTiff -co "TILED=YES" -a_srs "+proj=latlong" N48E016.hgt N48E016.tif
gdalwarp -of GTiff -co "TILED=YES" -srcnodata 32767 -t_srs "+proj=merc +ellps=sphere +R=6378137 +a=6378137 +units=m" -rcs -order 3 -tr 30 30 -multi N48E016.tif N48E016_warped.tif
gdaldem hillshade N48E016_warped.tif N48E016_hillshade.tif
```
I have noticed 1px "gaps" on edges of hillshade "tiles" in result mapnik map image, so I investigated intermediate files, and I have found out the gap is created in warping step. If I open `N48E016_warped.tif` and the next one `N48E017_warped.tif` in QGIS, the gap is already visible, and also noticable in extents (from properties of these files shown by QGIS):
```
Extent of N48E016_warped
1781096.3916519894264638,6106854.9605779703706503 : 1892456.3916519894264638,6274884.9605779703706503

Extent of N48E017_warped
1892415.8824452632106841,6106854.9605779703706503 : 2003775.8824452632106841,6274884.9605779703706503
```
Before warping, there is no gap in extent (even tiny overlap, it seems):
```
Extent of N48E016
15.9998611111111106,47.9998611111111160 : 17.0001388888888876,49.0001388888888911

Extent of N48E017
16.9998611111111124,47.9998611111111160 : 18.0001388888888911,49.0001388888888911
```
Am I missing some options of `gdalwarp` to prevent this, or is this bug? Thanks!

**Comment by rouault** [comment]
you could try adding the -tap switch
use -t_srs EPSG:3857 for having a proper Google Mercator reprojection
-order 3 is useless, and always a bad idea
you should drop your -srcnodata 32767 that is likely incorrect (it is supposed to be -32768 for SRTM HGT)

**Comment by rouen-sk** [comment]
Thanks for suggestions @rouault , I have changed the warp command to 
```
gdalwarp -of GTiff -co "TILED=YES" -t_srs "EPSG:3857" -rcs -tr 30 30 -multi -tap N48E016.tif N48E016_warped2.tif
```
and it seems it helped. Strange thing is, I can still see the small gap in QGIS, but no longer in mapnik image rendered from hillshades. Also the extends have tiny overlap now (same as source data):
```
N48E016_warped2:
1781070.0000000000000000,6106830.0000000000000000 : 1892460.0000000000000000,6274890.0000000000000000

N48E017_warped2:
1892400.0000000000000000,6106830.0000000000000000 : 2003790.0000000000000000,6274890.0000000000000000
```
So it is probably fine (and maybe there is some bug in QGIS). Thanks again.
