### ISSUE TITLE
VS2017 builds broken in master

### ISSUE THREAD

**Issue by szekerest** [OSGeo/gdal#6624]
The cmake build in master with Visual Studio 2017 yields the following errors:

E:\buildsystem\src\gdal-vc15x64\alg\gdalchecksum.cpp(153): error C2039: 'max': is not a member of 'std' [E:\buildsystem
\src\gdal-vc15x64\vc15x64\alg\alg.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\vector(20): note: see
   declaration of 'std'
E:\buildsystem\src\gdal-vc15x64\alg\gdalchecksum.cpp(153): error C3861: 'max': identifier not found [E:\buildsystem\src
\gdal-vc15x64\vc15x64\alg\alg.vcxproj]
E:\buildsystem\src\gdal-vc15x64\alg\gdalchecksum.cpp(164): error C2039: 'min': is not a member of 'std' [E:\buildsystem
\src\gdal-vc15x64\vc15x64\alg\alg.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\vector(20): note: see
   declaration of 'std'
E:\buildsystem\src\gdal-vc15x64\alg\gdalchecksum.cpp(166): error C2039: 'max': is not a member of 'std' [E:\buildsystem
\src\gdal-vc15x64\vc15x64\alg\alg.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\vector(20): note: see
   declaration of 'std'
E:\buildsystem\src\gdal-vc15x64\alg\gdalchecksum.cpp(166): error C3861: 'max': identifier not found [E:\buildsystem\src
\gdal-vc15x64\vc15x64\alg\alg.vcxproj]
E:\buildsystem\src\gdal-vc15x64\alg\gdalchecksum.cpp(164): error C3861: 'min': identifier not found [E:\buildsystem\src
\gdal-vc15x64\vc15x64\alg\alg.vcxproj]

E:\buildsystem\src\gdal-vc15x64\alg\gdalgrid.cpp(676): error C2039: 'max': is not a member of 'std' [E:\buildsystem\src
\gdal-vc15x64\vc15x64\alg\alg.vcxproj]
E:\buildsystem>  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\vector(20): note: see
   declaration of 'std'
E:\buildsystem\src\gdal-vc15x64\alg\gdalgrid.cpp(676): error C3861: 'max': identifier not found [E:\buildsystem\src\gda
l-vc15x64\vc15x64\alg\alg.vcxproj]

Looks like it misses the following include in the corresponding files:

`#include <algorithm>`

**Comment by rouault** [comment]
Hi Tamas. I plan to issue a 3.6.0RC2 with the few fixes since RC1. Let me know when things look good for you.

**Comment by szekerest** [comment]
@rouault I was thinking to set CSHARP_LIBRARY_VERSION=netstandard2.0 by default (like it was set with the nmake build earlier), but it can be set externally, so it's not that important.
