### ISSUE TITLE
gdal_translate fails when trying to add a raster to an existing vector-only GeoPackage

### ISSUE THREAD

**Issue by wdonahoe** [OSGeo/gdal#663]
## Expected behavior and actual behavior.

I have an existing GeoPackage (`soils.gpkg`) containing a single vector dataset that I created using an internal tool.

I am trying to add a TIFF raster (`tiff_test_wgs84.tif`) to this GeoPackage using `gdal_translate`:

`gdal_translate -of GPKG tiff_test_wgs84.tif soils.gpkg -co APPEND_SUBDATASET=YES`

Expected behavior: `tiff_test_wgs84` is added to the GeoPackage.

Actual behavior:

```
0ERROR 1: sqlite3_exec(INSERT INTO gpkg_tile_matrix_set (table_name,srs_id,min_x,min_y,max_x,max_y) VALUES ('tiff_test_wgs84',-1,-77.42268164174656,38.75415988758648,-77.41131759799439,38.76552393133866)) failed: no such table: gpkg_tile_matrix_set
...10...20...30...40...50...60...70...80...90...100 - done.
ERROR 1: failed to prepare SQL INSERT OR REPLACE INTO 'tiff_test_wgs84' (zoom_level, tile_row, tile_column, tile_data) VALUES (5, 0, 0, ?): no such table: main.gpkg_tile_matrix
ERROR 1: failed to prepare SQL INSERT OR REPLACE INTO 'tiff_test_wgs84' (zoom_level, tile_row, tile_column, tile_data) VALUES (5, 0, 1, ?): no such table: main.gpkg_tile_matrix
ERROR 1: failed to prepare SQL INSERT OR REPLACE INTO 'tiff_test_wgs84' (zoom_level, tile_row, tile_column, tile_data) VALUES (5, 0, 2, ?): no such table: main.gpkg_tile_matrix
ERROR 1: failed to prepare SQL INSERT OR REPLACE INTO 'tiff_test_wgs84' (zoom_level, tile_row, tile_column, tile_data) VALUES (5, 0, 3, ?): no such table: main.gpkg_tile_matrix
```

I have verified that `gdal_translate` does create a correct GeoPackage from this TIFF when executing the following command:

`gdal_translate -of GPKG tiff_test_wgs84.tif out.gpkg`

## Steps to reproduce the problem.

`gdal_translate -of GPKG tiff_test_wgs84.tif soils.gpkg -co APPEND_SUBDATASET=YES`

## Operating system

Windows 10 Pro, Version 1709, Build 16299.431

## GDAL version and provenance

GDAL 2.1.3

**Comment by rouault** [comment]
I suspect this issue has been fixed in later versions. Works fine for me with GDAL 2.2 and later
```
even@even-i700:~/gdal/git/2.2/gdal$ ogr2ogr -f gpkg out.gpkg ../autotest/ogr/data/poly.shp
even@even-i700:~/gdal/git/2.2/gdal$ gdal_translate -of gpkg ../autotest/gcore/data/byte.tif out.gpkg -co APPEND_SUBDATASET=YES
Input file size is 20, 20
0...10...20...30...40...50...60...70...80...90...100 - done.
```

**Comment by jratike80** [comment]
@rouault , do you have a test for adding raster into gpkg database that does not already have gpkg_tile_matrix and gpkg_tile_matrix_set tables? They are not compulsory for vector-only gpkg even GDAL creates them always. Because of triggers and constraints I could not drop those tables easily for making a test myself.

**Comment by rouault** [comment]
@jratike80 Yes this is tested per https://github.com/OSGeo/gdal/blob/master/autotest/gdrivers/gpkg.py#L3708

There's a hidden configuration option CREATE_RASTER_TABLES=NO that exists mostly for the purpose of that test.
