### ISSUE TITLE
Plugins are not connected. C#

### ISSUE THREAD

**Issue by SemaSanych** [OSGeo/gdal#6631]
## Expected behavior and actual behavior.
If in GdalConfiguration() "GDAL_DRIVER_PATH" contains Cyrillic characters, then the AutoLoadDrivers() cannot connect the *.dll located there. When specifying a relative path, everything works.
Then I ran into the problem that when launching the application through a custom launcher (Launcher.exe -> myProject.exe ) relative paths also stop working. Specifying the edited path in "GDAL_DRIVER_PATH", taking into account the directory.GetCurrentDirectory(), does not change the result.
Cyrillic support was expected.

gdaldrivermanager.cpp  755
GDALDriverManager::AutoLoadDrivers()

Sorry for my bad English.

## Steps to reproduce the problem.
Create a project in a directory with Cyrillic characters -> 
install Gdal from NuGet packages (gdal, native, plugins). 
The import of the *.ecw file will not occur.

## Operating system
Windows 10 64 bit

## GDAL version and provenance
Gdal 3.5.3 from NuGet (VS2019)

**Comment by rouault** [comment]
This should work if GDAL_DRIVER_PATH is a UTF-8 encoded string.

Alternatively if you use the current ANSI page, you can try setting the GDAL_FILENAME_IS_UTF8 configuration option/environment variable to NO, but this is not recommended.

**Comment by SemaSanych** [comment]
That feeling when I realized that I hadn't read the instructions to the end. Thanks. The problem is solved, I'll figure it out further.
