### ISSUE TITLE
gdal + proj 5 ignores non-earth planet radius

### ISSUE THREAD

**Issue by malytomas** [OSGeo/gdal#665]
## Expected behavior and actual behavior.

Converting coordinates on, say, Mars yields values as if on Earth.

## Steps to reproduce the problem.

Here https://github.com/vaclavblazek/gdalproj5 is an example code that reproduces the issue.
It should print approximately 3e6 ...
But it prints 6e6 ..

## Operating system

windows 10, x64, visual studio 2017 15.7.3, building for x64

## GDAL version and provenance

Gdal tag 2.3.0
Proj tag 5.1.0 (does have this issue)
(Proj tag 4.9.3 does not have the issue)
Both libraries taken from github

**Comment by rouault** [comment]
As a fix or workaround (not sure yet :-)), you can use the following string as the target SRS:
"+proj=cart +a=3396190 +b=3376200 +lon_0=0 +units=m +no_defs +wktext"
so changing from geocent to cart, and adding +wktext

**Comment by rouault** [comment]
fixed in proj with https://github.com/OSGeo/proj.4/pull/1026
