### ISSUE TITLE
REGR: Failed to open HDF-EOS file

### ISSUE THREAD

**Issue by snowman2** [OSGeo/gdal#6665]
From: https://github.com/corteva/rioxarray/pull/606
Related: https://github.com/corteva/rioxarray/issues/544

## Expected behavior and actual behavior.

This works with GDAL 3.5.3:
```
FAILED test/integration/test_integration__io.py::test_open_group_filter[open_rasterio_engine] - rasterio.errors.RasterioIOError: Failed to open HDF-EOS file "/__w/rioxarray/rioxarray/test/test_data/input/MOD09GA.A2008296.h14v17.006.2015181011753.hdf" for swath reading.
FAILED test/integration/test_integration_xarray_plugin.py::test_xarray_open_dataset__drop_variables - rasterio.errors.RasterioIOError: HDF4_EOS:EOS_GRID:/__w/rioxarray/rioxarray/test/test_data/input/MOD09GA.A2008296.h14v17.006.2015181011753.hdf:MODIS_Grid_500m_2D:iobs_res_1: No such file or directory
```

## Steps to reproduce the problem.

Input file: https://github.com/corteva/rioxarray/blob/master/test/test_data/input/MOD09GA.A2008296.h14v17.006.2015181011753.hdf?raw=true

Seems related to opening and reading the file multiple times. The first read works okay.
```python
from osgeo import gdal

path = "MOD09GA.A2008296.h14v17.006.2015181011753.hdf"
layers = []
for iii in range(100):
    ds = gdal.Open(path)
    if not ds:
        print(iii)
        break
    subds = gdal.Open(ds.GetSubDatasets()[0][0])
    if not subds:
        print(iii)
        break
    layers.append(subds)
    subds.GetRasterBand(1).GetNoDataValue()
    del ds
```
Output:
```
ERROR 4: Failed to open HDF-EOS file "MOD09GA.A2008296.h14v17.006.2015181011753.hdf" for swath reading.
32
```

## Operating system

Ubuntu 20.04 64 bit

## GDAL version and provenance

GDAL 3.5.3 & 3.6.0 from docker image.

**Comment by rouault** [comment]
I know what's going on. It is related to the HDF4_HAS_MAXOPENFILES #define no longer being set in CMake builds. Working on fixing that

**Comment by snowman2** [comment]
Thanks @rouault :+1:

**Comment by snowman2** [comment]
Similar issue seen with sentinel2 data: https://github.com/rasterio/rasterio/issues/2490#issuecomment-1231771007
