### ISSUE TITLE
[optimization] Better retrieval of rtree bounding box for GeoPackage

### ISSUE THREAD

**Issue by rouault** [OSGeo/gdal#667]
See https://github.com/OSGeo/gdal/commit/f3276e81274936027803295b32187a59db234eca#commitcomment-29252718

**Comment by jratike80** [comment]
Is this fixed with this stuff https://github.com/OSGeo/gdal/blob/f683709e3105c1bac2f75ba6d24afe20abea31b9/ogr/ogrsf_frmts/gpkg/ogrgeopackagetablelayer.cpp#L3895?

**Comment by rouault** [comment]
> Is this issue fixed with this stuff

yes
