### ISSUE TITLE
Incorrect auto-type detection for GeoJSON files with "id" attribute

### ISSUE THREAD

**Issue by palmerj** [OSGeo/gdal#669]
## Expected behaviour and actual behaviour.

When loading the attached GeoJSON file I expect the datatype of the 'id' attribute to be integer, but instead it's reported as string. Funnily enough if the JSON file only has 1 feature the type is integer. 

## Steps to reproduce the problem.

```
ogrinfo test.json -al -so
INFO: Open of `test.json'
      using driver `GeoJSON' successful.

Layer name: test
Geometry: Point
Feature Count: 2
Extent: (168.330053, -46.201706) - (170.969936, -45.074053)
Layer SRS WKT:
GEOGCS["NZGD2000",
    DATUM["New_Zealand_Geodetic_Datum_2000",
        SPHEROID["GRS 1980",6378137,298.257222101,
            AUTHORITY["EPSG","7019"]],
        TOWGS84[0,0,0,0,0,0,0],
        AUTHORITY["EPSG","6167"]],
    PRIMEM["Greenwich",0,
        AUTHORITY["EPSG","8901"]],
    UNIT["degree",0.0174532925199433,
        AUTHORITY["EPSG","9122"]],
    AUTHORITY["EPSG","4167"]]
__change__: String (0.0)
id: String (0.0)
cos_id_official: Integer (0.0)
type: String (0.0)
status: String (0.0)
order_group_off: Integer (0.0)
sit_id: String (0.0)
alt_id: String (0.0)
wrk_id_created: Integer (0.0)
audit_id: Integer (0.0)
se_row_id: Integer (0.0)
```

## Operating system
MacOSX

## GDAL version and provenance

2.2.4 installed via homebrew

[test.json.txt](https://github.com/OSGeo/gdal/files/2074445/test.json.txt)

**Comment by jratike80** [comment]
Your data seem to have two times "id" for each feature:
First in 
`{"type":"Feature","id":"layer-51993-changeset.17881811"`
and later again in properties
`"properties":{"__change__":"UPDATE","id":13242,`

Perhaps id field is initialized by the first one that is a string but value gets overwritten by the next one. If I edit the GeoJSON file and remove the id from properties then ogrinfo lists

```
OGRFeature(test2):0
  id (String) = layer-51993-changeset.17881811
```

**Comment by palmerj** [comment]
Good point. Reading the GeoJSON RFC the "id" in outer doc is a Foreign Member. What should be the behaviour in the case the same property name is defined in both the outer GeoJSON doc and as a key/value within the properties member?

**Comment by rouault** [comment]
> What should be the behaviour in the case the same property name is defined in both the outer GeoJSON doc and as a key/value within the properties member?

Probably undefined behaviour. OGR arbitrary decision is to take the Feature.properties.id as a OGR field, and use Feature.id as FID if it is of type int/int64. And if Feature.id is String and there's a Feature.properties.id, then Feature.id is ignored.

**Comment by jratike80** [comment]
Did you take into consideration section 3.2 of the GeoJSON standard:

> If a Feature has a commonly used identifier, that identifier
>       SHOULD be included as a member of the Feature object with the name
>       "id", and the value of this member is either a JSON string or
>       number.

**Comment by rouault** [comment]
> Did you take into consideration section 3.2 of the GeoJSON standard

To the extent of what the OGR feature model allows. We cannot have strings as FID. So if there's a Feature.id of type string, and no Feature.properties.id, then OGR will expose a "id" attribute of type string.

**Comment by palmerj** [comment]
> Probably undefined behaviour. OGR arbitrary decision is to take the Feature.properties.id as a OGR field, and use Feature.id as FID if it is of type int/int64. And if Feature.id is String and there's a Feature.properties.id, then Feature.id is ignored.

Thanks you @rouault for hte fix. This logic makes good sense.
