### ISSUE TITLE
Feature Request for Gdal2Tiles: Support JPEG format

### ISSUE THREAD

**Issue by asafMasa** [OSGeo/gdal#6703]
## Expected behavior and actual behavior.

Use gdal2tiles to create tiles in jpg format 👍 (tenth of the PNG size )
gdal2tiles currently supports only PNG or WEBP 😢 
https://gdal.org/programs/gdal2tiles.html#cmdoption-gdal2tiles-tiledriver

**Comment by asafMasa** [comment]
Let me consider it for a few days

**Comment by jratike80** [comment]
As a reminder, pure JPEG tiles make some issues with the border tiles, but of course something like geosolutionsgroup.com/blog/geoserver-smart-transparency/ can be implemented later or just to leave it for more feature rich tiling systems .

**Comment by asafMasa** [comment]
> As a reminder, pure JPEG tiles make some issues with the border tiles, but of course something like geosolutionsgroup.com/blog/geoserver-smart-transparency/ can be implemented later or just to leave it for more feature rich tiling systems .

My use-case is for world wide layer [-90,-180,90,180] so the border is not of a concern

**Comment by asafMasa** [comment]
@zdila @rouault is there any progress with this issue?
