### ISSUE TITLE
Build warning: parameter 'nBands' shadows member inherited from type 'GDALDataset'

### ISSUE THREAD

**Issue by elpaso** [OSGeo/gdal#6710]
## Expected behavior and actual behavior.

While building, there is a warning:

```
[751/1323 13.4/sec] Building CXX object frmts/georaster/CMakeFiles/gdal_GEOR.dir/georaster_dataset.cpp.o
../frmts/georaster/georaster_dataset.cpp:821:44: warning: parameter 'nBands' shadows member inherited from type 'GDALDataset' [-Wshadow-field]
                                       int nBands,
                                           ^
../gcore/gdal_priv.h:370:17: note: declared here
    int         nBands = 0;
                ^
1 warning generated.
```

Expected behavior: build without warnings

## Steps to reproduce the problem.

Build with cmake defaults, clang10

## Operating system

Ubuntu 20.04 64 bit

## GDAL version and provenance

current master, self-built

**Comment by rouault** [comment]
cf 3f6c8dc3a56825b24e69634c5d2c3abd74a53ce5 for similar issue/fix in other drivers
CC @fechen123
