### ISSUE TITLE
Cmake failes on windows with visual studio community 

### ISSUE THREAD

**Issue by asafMasa** [OSGeo/gdal#6719]
## Expected behavior and actual behavior.

I expected to be able to open GDAL via visual stuio community 2022 for build / run porpuses seamlessly via cmake,
but cmake fails with the following exception
![image](https://user-images.githubusercontent.com/18442671/202243861-603c8a70-5fc6-44d6-9c0e-5c3c4c473802.png)

## Steps to reproduce the problem.

git clone gdal
open visual studio community - cmake will then build the project seamlessly 

## Operating system

windows 10 enterprise version 1909

## GDAL version and provenance

latest

**Comment by rouault** [comment]
Not a bug. PROJ >= 6 is a required dependency of GDAL as documented in https://gdal.org/build_hints.html#build-requirements
See https://proj.org/install.html for potential ways of installing the PROJ dependency

**Comment by asafMasa** [comment]
> Not a bug. PROJ >= 6 is a required dependency of GDAL as documented in https://gdal.org/build_hints.html#build-requirements See https://proj.org/install.html for potential ways of installing the PROJ dependency

@rouault i don't understand why it isn't a bug? Why do i need to change things to make it work? isn't CMake supposed to work after a fresh clone?

**Comment by rouault** [comment]
> isn't CMake supposed to work after a fresh clone?

there are documented build requirements : a C++11 compiler, CMake >= 3.10 and a PROJ >= 6 development package. See the links I provided
