### ISSUE TITLE
Performance problem because of RawRasterBand::CanUseDirectIO()

### ISSUE THREAD

**Issue by chacha21** [OSGeo/gdal#6726]
GDAL 3.5.3
Windows 7 64b
Visual Studio 2019 (latest)

I have noticed a performance problem due to an unexpected overhead in `RawRasterBand::CanUseDirectIO()`

Short story : the call to `CPLGetConfigOption("GDAL_ONE_BIG_READ", nullptr);` is too expensive, and perhaps should be cached with some new field of `GDALRasterIOExtraArg`

Long story :
I am using a dataset with LINE interleaving. For information : spatial size 800x1000, bandsCount 734.
I am submitting 1000 elements of size 800x734 for writing (which best fits the interleaving, that's why the dataset was configured that way).
I was surprised to see a very high difference in writing performance between a "MEM" and an "ENVI" dataset.
The ENVI dataset was ~6x times slower
So, at first, I made sure to "warm up the cache" so that no cached block allocation was needed during writing, and the performance was still ~x3 slower with ENVI.
I did not understand where the overhead could com from.
After investigation, I replaced `const char *pszGDAL_ONE_BIG_READ = CPLGetConfigOption("GDAL_ONE_BIG_READ", nullptr);` with `const char *pszGDAL_ONE_BIG_READ = nullptr;`, and boom, the performance was now comparable.
I think this occurs because `RawRasterBand::CanUseDirectIO()` is inside a band-driven loop, and I have 734 bands, which is a lot.

Is it affordable to extend `GDALRasterIOExtraArg` with a cached value for `CPLGetConfigOption("GDAL_ONE_BIG_READ", nullptr);` ?

**Comment by rouault** [comment]
> Is it affordable to extend `GDALRasterIOExtraArg` with a cached value for `CPLGetConfigOption("GDAL_ONE_BIG_READ", nullptr);` ?

I would rather suggest to had a member variable in RawRasterBand to cache the value of GDAL_ONE_BIG_READ (1 if CPLTestBool() is true, 0 if its is false, and -1 if the config option is not set at all) the first time it is accessed. The behavior will be slightly changed compared to currently, but I believe it is acceptable to assume that on a given dataset/band instance, the value of GDAL_ONE_BIG_READ shouldn't change between invokations of RasterIO()

**Comment by rouault** [comment]
> Do you want me to PR ?

yes

**Comment by chacha21** [comment]
> I would rather suggest to ~had~ add a member variable in RawRasterBand
Isn't it strange to make a per-band member variable ? It needs to initialize this variable for all bands at the beginning of each RasterIO(), and ultimately the will all the same value.

**Comment by rouault** [comment]
> Isn't it strange to make a per-band member variable ?

that could potentially be at the RawDataset level. But you would need to check dynamic_cast<RawDataset*>(poDS) != nullptr since there's no guarantee a RawRasterBand is owned by a class deriving from RawDataset (cf RawRasterBand::IsBIP() that does such check), even if it is definitely the most common scenario.
