### ISSUE TITLE
ogr2ogr raises an error from PostGIS but the resulting exit code is zero

### ISSUE THREAD

**Issue by boardend** [OSGeo/gdal#6728]
## Expected behavior and actual behavior.
If ogr2ogr raises an error from PostGIS, the exit code should be none zero:

```
C:\Users\someuser>"C:/Program Files/QGIS 3.28.0/bin/ogr2ogr.exe" -f "PostgreSQL" PG:"host=somepostgis port=5432 dbname=somedb user=someuser password=somepw" D:/99_case_1.shp -nlt PROMOTE_TO_MULTI -nln "geometries.t_99_case_1" -lco GEOMETRY_NAME=the_geom -t_srs EPSG:4326 -preserve_fid -overwrite -sql "SELECT id AS id FROM \"99_case_1\""
ERROR 1: ERROR:  setval: value 0 is out of bounds for sequence "t_99_case_1_ogc_fid_seq" (1..2147483647)

C:\Users\someuser>echo Exit Code is %errorlevel%
Exit Code is 0
```

## Steps to reproduce the problem.

Using ogr2ogr to import to PostGIS with FIDs starting with 0 will trigger the "value 0 is out of bounds for sequence" error.

(In the example above, `-preserve_fid` causes a FID starting with 0)

## Operating system
Windows 11 (Version 21H2 (OS Build 22000.1281)) / In `cmd.exe`

## GDAL version and provenance
GDAL 3.5.2, released 2022/09/02, from QGIS 3.28.0-2

(The same behavior was observed with GDAL 3.5.1, released 2022/06/30, from QGIS 3.26.1)

**Comment by rouault** [comment]
I can only replicate that error if you insert just one feature of FID 0 ? Is that your case ? If not please provide a shapefile (as a .zip of the .shp, .shx and .dbf files) reproducing the error

**Comment by boardend** [comment]
Yes, the `preserve_fid` from above will result in an insert with FID 0. Of course this is a user/data problem, but the exit code of zero makes it really hard to spot the error from PostGIS, if this happens during execution of a larger script.

I can’t say if this only happens with `setval`/FID 0, or if every error from PostGIS (e.g. a constraint valuation) will just be printed to the console, but ogr2ogr will exit with a status of zero.

**Comment by rouault** [comment]
> I can’t say if this only happens with `setval`/FID 0, or if every error from PostGIS (e.g. a constraint valuation) will just be printed to the console

This is specific to this one. Actually here the error can be ignored as inserting a feature of FID 0 is valid. It is just that setval() doesn't like it. So GDAL should probably just silent this setval error and still return success

**Comment by boardend** [comment]
> I can only replicate that error if you insert just one feature of FID 0 ? Is that your case?

I can confirm that the problem only occurs if there is one feature with FID 0.

If the .shp file only contains one feature, nothing gets imported. If the .shp has more than one feature, all of them seem to get imported:

```C:\Users\someuser>"C:/Program Files/QGIS 3.28.1/bin/ogr2ogr.exe" -f "PostgreSQL" PG:"host=somepostgis port=5432 dbname=somedb user=someuser password=somepw" D:/case_1.shp -nlt PROMOTE_TO_MULTI -nln "geometries.case_1" -lco GEOMETRY_NAME=the_geom -t_srs EPSG:4326 -preserve_fid -overwrite -sql "SELECT id AS id FROM \"case_1\""```

CPL_DEBUG Output with **one feature** in `case_1.shp`:

````
Shape: DBF Codepage = UTF-8 for D:/case_1.shp
Shape: Treating as encoding 'UTF-8'.
GDAL: GDALOpen(D:/case_1.shp, this=000001BA7E269AF0) succeeds as ESRI Shapefile.
PG: Client encoding: 'UTF8'
PG: PostGIS schema: 'postgis'
PG: PostgreSQL version string : 'PostgreSQL 14.2 (Debian 14.2-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit'
PG: PostGIS version string : '3.2 USE_GEOS=1 USE_PROJ=1 USE_STATS=1'
GDAL: GDALOpen(PG:host=somepostgis port=5432 dbname=somedb user=someuser password=XXXXXXXXXXXXXXXXXXX this=000001BA7E24E690) succeeds as PostgreSQL.
PG: Could not retrieve table oid for case_1
PG: Could not retrieve table oid for case_1
GDALVectorTranslate: 1 features written in layer 'geometries.case_1'
GenSQL: 1 features read on layer 'case_1'.
PG: PQputCopyEnd()
ERROR 1: ERROR:  setval: value 0 is out of bounds for sequence "case_1_ogc_fid_seq" (1..2147483647)

Shape: 1 features read on layer 'case_1'.
GDAL: GDALClose(D:/case_1.shp, this=000001BA7E269AF0)
GDAL: GDALClose(PG:host=somepostgis port=5432 dbname=somedb user=someuser password=XXXXXXXXXXXXXXXXXXX this=000001BA7E24E690)
GDAL: In GDALDestroy - unloading GDAL shared library.
````

Result: **Table `geometries.case_1` does not exist**. Exit code is zero (NOK).

------

CPL_DEBUG Output with **two features** in `case_1.shp`:

````
Shape: DBF Codepage = UTF-8 for D:/case_1.shp
Shape: Treating as encoding 'UTF-8'.
GDAL: GDALOpen(D:/case_1.shp, this=0000020489271B30) succeeds as ESRI Shapefile.
PG: Client encoding: 'UTF8'
PG: PostGIS schema: 'postgis'
PG: PostgreSQL version string : 'PostgreSQL 14.2 (Debian 14.2-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit'
PG: PostGIS version string : '3.2 USE_GEOS=1 USE_PROJ=1 USE_STATS=1'
GDAL: GDALOpen(PG:host=somepostgis port=5432 dbname=somedb user=someuser password=XXXXXXXXXXXXXXXXXXX this=00000204895802D0) succeeds as PostgreSQL.
PG: Could not retrieve table oid for case_1
PG: Could not retrieve table oid for case_1
GDALVectorTranslate: 2 features written in layer 'geometries.case_1'
GenSQL: 2 features read on layer 'case_1'.
PG: PQputCopyEnd()
Shape: 2 features read on layer 'case_1'.
GDAL: GDALClose(D:/case_1.shp, this=0000020489271B30)
GDAL: GDALClose(PG:host=somepostgis port=5432 dbname=somedb user=someuser password=XXXXXXXXXXXXXXXXXXX this=00000204895802D0)
GDAL: In GDALDestroy - unloading GDAL shared library.
````

Result: **Table `geometries.case_1` is created and the two features are present**. Exit code is zero (OK).

------

I can try to create a minimal repro, but problably not before end of this week (47). But as you said, this is an edge case when only one feature with FID 0 is imported to PostGIS.

**Comment by boardend** [comment]
Thank you for the fix and in general for your precious work for the whole geospatial community 🙌
