### ISSUE TITLE
Incorrect URL when retrieving IAM credentials within ECS

### ISSUE THREAD

**Issue by mojodna** [OSGeo/gdal#673]
The metadata / credential URL below works on EC2 instances. However, when running within a container under ECS (e.g. AWS Batch), a special environment variable (`AWS_CONTAINER_CREDENTIALS_RELATIVE_URI`) is set in order to allow per-containing IAM roles (vs. host-level). ECS credential fetching should use `169.254.170.2${AWS_CONTAINER_CREDENTIALS_RELATIVE_URI}` instead.

https://github.com/OSGeo/gdal/blob/e648607661fdd5cbc6bb778c17c20c3e7979a734/gdal/port/cpl_aws.cpp#L650

Implementation-wise, it probably makes sense to fall back to this behavior when `AWS_CONTAINER_CREDENTIALS_RELATIVE_URI` is set (this is the behavior of many AWS credential provider chains).

## Environment

Amazon Elastic Container Service (ECS)

## GDAL version and provenance

2.3.0

**Comment by rouault** [comment]
want to submit a PR ?

**Comment by mojodna** [comment]
I'll see if I can find time, but my C skills are pretty dull and it'll be slow.

**Comment by rouault** [comment]
okay, I can try making a patch in the blind from your info, and let you test it ?

**Comment by mojodna** [comment]
That'd be awesome. To be clear, it's nowhere near blocking me (I use https://github.com/mojodna/marblecutter-tools/blob/2a7c6afa2f0b58db2c1ad04e50c8a8d5edf8a660/bin/process.sh#L89-L119 as a pre-IAM support workaround).

I noticed it while trying to debug a problem running on Lambda that turned out to be unrelated and figured I'd log it.

**Comment by rouault** [comment]
Here it is: 
[gdal_issue_673.patch.txt](https://github.com/OSGeo/gdal/files/2078313/gdal_issue_673.patch.txt)

**Comment by mojodna** [comment]
Fantastic. The patch looks good to me.
