### ISSUE TITLE
gdalinfo fails on selected XYZ files originating from same open data provider

### ISSUE THREAD

**Issue by neteler** [OSGeo/gdal#6736]
## Expected behavior and actual behavior.

The city of Berlin, Germany, offers open data. Among other datasets there is a surface model ("DOM" - Digitales Oberflächenmodell) at high resolution available. They are offered in XYZ ASCII structure, e.g.:

```
371999.50 5806917.50 41.21
371999.50 5806918.50 51.99
371998.50 5806919.50 53.50
...
```

Most files can be read but some cannot for unknown reason, see example below.

## Steps to reproduce the problem.

Download sample files:

```
# download DOM XYZ files
wget https://fbinter.stadt-berlin.de/fb/atom/DOM/DOM1_372_5812.zip
wget https://fbinter.stadt-berlin.de/fb/atom/DOM/DOM1_370_5806.zip

unzip DOM1_370_5806.zip
unzip DOM1_372_5812.zip
```

Inspect the first map:

```
head -n 3 DOM1_372_5812.txt
372000.500 5812000.500 75.32
372001.500 5812000.500 65.47
372002.500 5812000.500 65.14

file DOM1_372_5812.txt
DOM1_372_5812.txt: ASCII text, with CRLF line terminators

gdalinfo DOM1_372_5812.txt
Driver: XYZ/ASCII Gridded XYZ
Files: DOM1_372_5812.txt
Size is 2000, 2000
Origin = (372000.000000000000000,5812000.000000000000000)
Pixel Size = (1.000000000000000,1.000000000000000)
Corner Coordinates:
Upper Left  (  372000.000, 5812000.000) 
Lower Left  (  372000.000, 5814000.000) 
Upper Right (  374000.000, 5812000.000) 
Lower Right (  374000.000, 5814000.000) 
Center      (  373000.000, 5813000.000) 
Band 1 Block=2000x1 Type=Float32, ColorInterp=Undefined
  Min=29.090 Max=94.630
```

Inspect the second map (for whatever reason with one digit less for X and Y but that should not matter I think):

```
head -n 3 DOM1_370_5806.txt
371999.50 5806917.50 41.21
371999.50 5806918.50 51.99
371998.50 5806919.50 53.50

file DOM1_370_5806.txt
DOM1_370_5806.txt: ASCII text, with CRLF line terminators

gdalinfo DOM1_370_5806.txt
ERROR 1: Ungridded dataset: At line 3, X spacing was -1.000000. Expected >0 value
gdalinfo failed - unable to open 'DOM1_370_5806.txt'.
```

I spent some time to find file encoding issues, to no avail. Not sure what's different in the second XYZ file (and others).

## Operating system

Fedora release 36 (also reproduced on Ubuntu)

## GDAL version and provenance

gdal-3.4.3-1.fc36.x86_64 (from Fedora) - also reproduced in gdal-3.4.1.

**Comment by rouault** [comment]
not promising it will fix all instances of your issue, but https://github.com/OSGeo/gdal/pull/6737 at least solves the issue with DOM1_370_5806.txt.
Counter-intuitively, it is rather hard to verify that XYZ input is regularly gridded and with a regular organization, with such datasets that have lines with very sparse content.

**Comment by neteler** [comment]
Thanks for the almost real time PR! We are going to test it with multiple datasets.
