### ISSUE TITLE
GDAL_DRIVER_PATH: add lib64 to default paths

### ISSUE THREAD

**Issue by metzm** [OSGeo/gdal#6744]
## Expected behavior and actual behavior.

The current default search paths for [GDAL_DRIVER_PATH](https://trac.osgeo.org/gdal/wiki/ConfigOptions#GDAL_DRIVER_PATH) are
"the /usr/local/lib/gdalplugins directory, and (if known) the lib/gdalplugins subdirectory of the gdal home directory"

However, various operating systems, e.g. based on Debian or RHEL, put shared libraries and also gdal plugins not in some lib directory, but in some lib64 directory such as /usr/lib64/gdalplugins/ or /usr/local/lib64/gdalplugins/.

Adding these lib64 directories to the default search paths of GDAL_DRIVER_PATH would avoid the need to set GDAL_DRIVER_PATH manually.

## Operating system

For example Debian and RHEL based 64 bit systems.

## GDAL version and provenance

All GDAL versions AFAICT.

## Solution

This issue could probably be addressed by adding a few lines of code to https://github.com/OSGeo/gdal/blob/master/gcore/gdaldrivermanager.cpp#L697 such as

```
papszSearchPaths = CSLAddString( papszSearchPaths,
                                            "/usr/lib64/gdalplugins" );
papszSearchPaths = CSLAddString( papszSearchPaths,
                                            "/usr/local/lib64/gdalplugins" );
```

**Comment by rouault** [comment]
The documentation might be slightly out of date, butwith CMake builds this should not be necessary as you will go to https://github.com/OSGeo/gdal/blob/4766e134ab71c51b13bb4d97613b19f4d45afb99/gcore/gdaldrivermanager.cpp#L716, where INSTALL_PLUGIN_FULL_DIR is burnt at build time from the installation prefix and lib vs lib64 specifies of the system. Did you check its value ?

You can do easily by patching gcore/CMakeLists.txt with
```
diff --git a/gcore/CMakeLists.txt b/gcore/CMakeLists.txt
index ff3344879c..d78e3b46b3 100644
--- a/gcore/CMakeLists.txt
+++ b/gcore/CMakeLists.txt
@@ -65,6 +65,7 @@ set_property(
   SOURCE gdaldrivermanager.cpp
   APPEND
   PROPERTY COMPILE_DEFINITIONS INST_DATA="${INST_DATA_PATH}" INSTALL_PLUGIN_FULL_DIR="${INSTALL_PLUGIN_FULL_DIR}")
+message(FATAL_ERROR ${INSTALL_PLUGIN_FULL_DIR})
 if (GDAL_USE_XERCESC)
   target_include_directories(gcore PRIVATE ${XercesC_INCLUDE_DIRS} ${XercesC_INCLUDE_DIRS}/xercesc)
   set_property(
```

**Comment by metzm** [comment]
Thanks for the hint, I found it, INSTALL_PLUGIN_FULL_DIR is set correctly to /usr/local/lib64/gdalplugins.
