### ISSUE TITLE
Cannot make /vsitar/ work

### ISSUE THREAD

**Issue by simoneves** [OSGeo/gdal#675]
## Expected behavior and actual behavior.

Failing to access files inside a TAR/TGZ/TAR.GZ archive using /vsitar/

What am I doing wrong?

Sorry, I would have posted this to gdal-dev but I am not (yet) a member...

## Steps to reproduce the problem.

I have a zip and a tar archive of the same folder containing an ESRI Shapefile set:

`$ unzip -l cb_2014_us_state_20m.zip`

`Archive:  cb_2014_us_state_20m.zip`
`  Length      Date    Time    Name`
`---------  ---------- -----   ----`
`        0  2018-06-08 09:44   cb_2014_us_state_20m/`
`    30219  2017-11-06 12:15   cb_2014_us_state_20m/cb_2014_us_state_20m.shp.iso.xml`
`       24  2017-11-06 12:15   cb_2014_us_state_20m/cb_2014_us_state_20m.shp.ea.iso.gfs`
`   446116  2017-11-06 12:15   cb_2014_us_state_20m/cb_2014_us_state_20m.shp`
`    19204  2017-11-06 12:15   cb_2014_us_state_20m/cb_2014_us_state_20m.shp.ea.iso.xml`
`     8434  2017-11-06 12:15   cb_2014_us_state_20m/cb_2014_us_state_20m.dbf`
`        9  2017-11-06 12:15   cb_2014_us_state_20m/cb_2014_us_state_20m.cpg`
`      165  2017-11-06 12:15   cb_2014_us_state_20m/cb_2014_us_state_20m.prj`
`      516  2017-11-06 12:15   cb_2014_us_state_20m/cb_2014_us_state_20m.shx`
`    18599  2017-11-06 12:15   cb_2014_us_state_20m/cb_2014_us_state_20m.shp.xml`
`---------                     -------`
`   523286                     10 files`

`$ tar tvf cb_2014_us_state_20m.tar`

`drwxr-xr-x simon.eves/mapd   0 2018-06-08 09:44 cb_2014_us_state_20m/`
`-rw-r--r-- simon.eves/mapd 30219 2017-11-06 12:15 cb_2014_us_state_20m/cb_2014_us_state_20m.shp.iso.xml`
`-rw-r--r-- simon.eves/mapd    24 2017-11-06 12:15 cb_2014_us_state_20m/cb_2014_us_state_20m.shp.ea.iso.gfs`
`-rw-r--r-- simon.eves/mapd 446116 2017-11-06 12:15 cb_2014_us_state_20m/cb_2014_us_state_20m.shp`
`-rwxr-xr-x simon.eves/mapd  19204 2017-11-06 12:15 cb_2014_us_state_20m/cb_2014_us_state_20m.shp.ea.iso.xml`
`-rw-r--r-- simon.eves/mapd   8434 2017-11-06 12:15 cb_2014_us_state_20m/cb_2014_us_state_20m.dbf`
`-rw-r--r-- simon.eves/mapd      9 2017-11-06 12:15 cb_2014_us_state_20m/cb_2014_us_state_20m.cpg`
`-rw-r--r-- simon.eves/mapd    165 2017-11-06 12:15 cb_2014_us_state_20m/cb_2014_us_state_20m.prj`
`-rw-r--r-- simon.eves/mapd    516 2017-11-06 12:15 cb_2014_us_state_20m/cb_2014_us_state_20m.shx`
`-rw-r--r-- simon.eves/mapd  18599 2017-11-06 12:15 cb_2014_us_state_20m/cb_2014_us_state_20m.shp.xml`

Accessing the Shapefile in the zip through /vsizip/ works fine:

`$ ogrinfo -ro /vsizip/cb_2014_us_state_20m.zip/cb_2014_us_state_20m/cb_2014_us_state_20m.shp`

`INFO: Open of /vsizip/cb_2014_us_state_20m.zip/cb_2014_us_state_20m/cb_2014_us_state_20m.shp' using driver 'ESRI Shapefile' successful.`
`1: cb_2014_us_state_20m (3D Polygon)`

Trying the same with /vsitar/ does not. tgz and tar.gz do not work either. Nor does an absolute path.

`$ ogrinfo -ro /vsitar/cb_2014_us_state_20m.tar/cb_2014_us_state_20m/cb_2014_us_state_20m.shp`

`FAILURE:`
`Unable to open datasource /vsitar/cb_2014_us_state_20m.tar/cb_2014_us_state_20m/cb_2014_us_state_20m.shp' with the following drivers.`
...

## Operating system

Ubuntu 17.10

## GDAL version and provenance

2.2.3 (Ubuntu provided) and 2.3.0 (self-built)

**Comment by simoneves** [comment]
I did check to make sure TAR support wasn't a build option I hadn't specified, but it seems not.

**Comment by rouault** [comment]
Can you provide a link to such a .tar ?

**Comment by simoneves** [comment]
TAR https://drive.google.com/open?id=1umDpdtLyzSc7xyNPp2Pk6u2-qRULka4r
ZIP https://drive.google.com/open?id=1LGEaCjUMudxzBIhubKELU_byF58-JTNT

**Comment by simoneves** [comment]
Seems to fail in the test for expected nulls and spaces in abyHeader in VsiTarReader::GotoNextFile (cpl_vsil_tar.cpp:340)

abyHeader is:

$11 = "cb_2014_us_state_20m/", '\000' <repeats 79 times>, "\060\060\060\060\067\065\065\000\200\000\000\000\006\224\222c\200\000\000\000\006\224\222\a", '0' <repeats 11 times>, "\000\061\063\063\060\066\065\063\061\061\062\065\000\060\061\064\066\067\065\000 5", '\000' <repe
ats 100 times>...

**Comment by simoneves** [comment]
The TAR was made with standard system tar (1.29) on Ubuntu 17.10, just with `tar cvf cb_2014_us_state_20m.tar cb_2014_us_state_20m` (where the latter is just a plain directory)

**Comment by simoneves** [comment]
So it's not me. Would this cherry-pick neatly into 2.3.0?

**Comment by rouault** [comment]
> Would this cherry-pick neatly into 2.3.0?

Yes, I've backported this to release/2.3 for 2.3.1 release

**Comment by simoneves** [comment]
I meant could WE cherry-pick it, if 2.3.1 isn't due out any time soon? We have an imminent release which would really benefit from this, and we already build our own GDAL.

**Comment by schwehr** [comment]
Probably.  You can quickly make a patch with `git format-patch` and see if it patches cleanly.
