### ISSUE TITLE
Multi process map reading efficiency

### ISSUE THREAD

**Issue by Iamlearn** [OSGeo/gdal#6757]
Gdal is great, but I have a question.I found that the efficiency is slower when I read the map with multiple processes. I guess that gdal reads a line of data, decodes it, and processes it in turn. At this time, opening multiple processes will lead to random reading, which slows down the speed. Is there any solution? Here is my process code:

def SignReadImg(path, curLs, shareImg, dtype, readBatchSize, id):
    temp = np.frombuffer(shareImg, dtype=dtype).reshape([readBatchSize[3], readBatchSize[2]]) for i, name in enumerate(curLs):
        ds = gdal.Open(path + name, gdal.GA_ReadOnly)
        ds.ReadAsArray(*readBatchSize, buf_obj=temp, buf_xsize=readBatchSize[2], buf_ysize=readBatchSize[3]) ds = None

**Comment by rouault** [comment]
Quoting issue template:
```
IMPORTANT: Do NOT use GitHub to post any questions or support requests!
           They will be closed immediately and ignored.

Questions should go to the gdal-dev mailing list at
https://lists.osgeo.org/mailman/listinfo/gdal-dev
or other support forums. GitHub issues are for bug
reports and suggestions for new features.
```
thus closing
