### ISSUE TITLE
GDAL 3.6.0 does not produce aux.xml for geotiff with WKT2

### ISSUE THREAD

**Issue by jjimenezshaw** [OSGeo/gdal#6758]
## Expected behavior and actual behavior.
I was using GDAL 3.3.2 (with PROJ 9.1.0) and generating a GeoTIFF with a DerivedProjected CRS. It worked fine, just creating a sidecar file (`.aux.xml`) specifying the CRS there, in WKT2 format.

However when I update to GDAL 3.6.0 (also happens with 3.5.0), it is not working, and the message produced is `ERROR 1: PROJ: proj_as_wkt: DerivedProjectedCRS can only be exported to WKT2:2019` when the dataset is closed.

Is this a regression, or is it intended? What is the actual expected behaviour? If it is a regression, should I try to fix it in a PR? (hints welcome).

`.aux.xml` file automatically generated with 3.3.2:
```
<PAMDataset>
  <SRS dataAxisToSRSAxisMapping="1,2,3">DERIVEDPROJCRS["Site Localization",BASEPROJCRS["Transverse Mercator centered in area of interest",BASEGEOGCRS["ETRS89",ENSEMBLE["European Terrestrial Reference System 1989 ensemble",MEMBER["European Terrestrial Reference Frame 1989"],MEMBER["European Terrestrial Reference Frame 1990"],MEMBER["European Terrestrial Reference Frame 1991"],MEMBER["European Terrestrial Reference Frame 1992"],MEMBER["European Terrestrial Reference Frame 1993"],MEMBER["European Terrestrial Reference Frame 1994"],MEMBER["European Terrestrial Reference Frame 1996"],MEMBER["European Terrestrial Reference Frame 1997"],MEMBER["European Terrestrial Reference Frame 2000"],MEMBER["European Terrestrial Reference Frame 2005"],MEMBER["European Terrestrial Reference Frame 2014"],ELLIPSOID["GRS 1980",6378137,298.257222101,LENGTHUNIT["metre",1]],ENSEMBLEACCURACY[0.1]],PRIMEM["Greenwich",0,ANGLEUNIT["degree",0.0174532925199433]]],CONVERSION["Transverse Mercator",METHOD["Transverse Mercator",ID["EPSG",9807]],PARAMETER["Latitude of natural origin",46.5289246891571,ANGLEUNIT["degree",0.0174532925199433],ID["EPSG",8801]],PARAMETER["Longitude of natural origin",6.70096726335249,ANGLEUNIT["degree",0.0174532925199433],ID["EPSG",8802]],PARAMETER["Scale factor at natural origin",1,SCALEUNIT["unity",1],ID["EPSG",8805]],PARAMETER["False easting",0,LENGTHUNIT["metre",1],ID["EPSG",8806]],PARAMETER["False northing",0,LENGTHUNIT["metre",1],ID["EPSG",8807]]]],DERIVINGCONVERSION["Affine transformation as PROJ-based",METHOD["PROJ-based operation method: +proj=pipeline  +step +proj=affine +xoff=6018.77495 +yoff=614.23698 +zoff=-399.91220 +s11=0.998812215508 +s12=0.0303546283772 +s13=-0.00129655684858 +s21=-0.0303565906348 +s22=0.998811840177 +s23=-0.00152042684237 +s31=0.00124977142441 +s32=0.00155911155192 +s33=0.999272201962"]],CS[Cartesian,3],AXIS["site east (x)",east,ORDER[1],LENGTHUNIT["metre",1,ID["EPSG",9001]]],AXIS["site north (y)",north,ORDER[2],LENGTHUNIT["metre",1,ID["EPSG",9001]]],AXIS["site up (z)",up,ORDER[3],LENGTHUNIT["metre",1,ID["EPSG",9001]]]]</SRS>
</PAMDataset>
```

## Steps to reproduce the problem.
Create a GeoTIFF and call the C++ function `SetProjection` to set the WKT2 of a derived projected CRS, like the one above.

## Operating system
Ubuntu 22.04

## GDAL version and provenance
3.3.2, 3.5.0 and 3.6.0 compiled from code
PROJ 9.1.0 compiled from code (also tested with 9.0.1, same behaviour).

**Comment by rouault** [comment]
Fix in https://github.com/OSGeo/gdal/pull/6760
Potential workaround: use the PROFILE=BASELINE creation option that avoids any attempt of writing GeoTIFF tags, but that will also push GDAL metadata and nodata to .aux.xml

**Comment by jjimenezshaw** [comment]
Thanks @rouault I tested it, and works fine.
