### ISSUE TITLE
vsiaz + azurite: Append Blob request fails

### ISSUE THREAD

**Issue by roelarents** [OSGeo/gdal#6759]
## Expected behavior and actual behavior.

Expected:
Writing a big* (geotif) file to [Azurite](https://github.com/Azure/Azurite) (Azure Blob Storage local emulator) with `vsiaz` (using `gdal_translate` for example) results in the output ending up on the blob storage.

\* big means something bigger than 4 MiB, when an _append blob_ is created.

Actual:
Azurite complains that: _Content-Length must be 0 for Create Append Blob request_. A blob is created, but with size 0.

* big means something bigger than 4 MiB, when an _append blob_ is created.

Related issue for Azurite + golang azure client which indicates that the Azure spec requires this, but production Azure does not adhere but Azurite does: https://github.com/Azure/Azurite/issues/682

Line of code affected probably here: https://github.com/OSGeo/gdal/blob/master/port/cpl_vsil_az.cpp#L1219

## Steps to reproduce the problem.

* Take a GeoTiff that's bigger than 4 MiB (after translating).
* Set `CPL_VSIL_USE_TEMP_FILE_FOR_RANDOM_WRITE=YES`
* Setup Azurite with default options. Create a container, e.g. `public`
* Set `AZURE_STORAGE_CONNECTION_STRING=` to the default for Azurite. Example [here](https://github.com/OSGeo/gdal/issues/957#issuecomment-425895378).
* Run `gdal_translate --debug on -of COG <your-tif> /vsiaz/public/foo.tif`.  
  (Ensure the output is actually going to be > 4 MiB. Or use something else than gdal_translate that writes to vsiaz.)

## Operating system

Ubuntu 22.04
(using [gdal docker image ubuntu-small-3.6.0](https://hub.docker.com/layers/osgeo/gdal/ubuntu-small-3.6.0/images/sha256-b445cb8a77a8d5c26120ad37d38b9a950334508ef22d5c646819040db65b25f8?context=explore))

## GDAL version and provenance

GDAL 3.6.0, released 2022/11/06

**Comment by rouault** [comment]
The issue was actually that a x-ms-blob-type=AppendBlob header was specified for AppendBlock operations whereas it is only required for the creation of the append blob. Fix in https://github.com/OSGeo/gdal/pull/6761
