### ISSUE TITLE
MongoDB OGR plugin unable to load driver

### ISSUE THREAD

**Issue by nickrobison** [OSGeo/gdal#676]
Hello! Not sure if this is the appropriate place to post this error, but I thought I'd give it a shot.

I'm attempting to add mongodb support to the gdal package in the osgeo/homebrew-osgeo4mac tap.

I've succeeded in building the mongodb driver in legacy mode, as well as compiling a gdalplugin, but unfortunately, I'm unable to get it to load correctly.

## Expected behavior and actual behavior.

`GDAL_DRIVER_PATH=/usr/local/lib/gdalplugins/ /usr/local/opt/gdal2/bin/ogrinfo --format GTiff` should return info without any error messages.

Instead, I get the following error output

```
ERROR 1: dlopen(/usr/local/lib/gdalplugins/2.3/ogr_mongodb.dylib, 1): Symbol not found: __ZN5mongo14BSONObjBuilder12numStrsReadyE
  Referenced from: /usr/local/lib/gdalplugins/2.3/ogr_mongodb.dylib
  Expected in: flat namespace
 in /usr/local/lib/gdalplugins/2.3/ogr_mongodb.dylib
ERROR 1: dlopen(/usr/local/lib/gdalplugins/2.3/ogr_mongodb.dylib, 1): Symbol not found: __ZN5mongo14BSONObjBuilder12numStrsReadyE
  Referenced from: /usr/local/lib/gdalplugins/2.3/ogr_mongodb.dylib
  Expected in: flat namespace
 in /usr/local/lib/gdalplugins/2.3/ogr_mongodb.dylib
```

I'm not sure if this is a problem with the mongo cxx driver, the compilation settings used in the formulae, or gdal itself, but I figured this would be a good place to start.

## Steps to reproduce the problem.

1. Install GDAL2 from the homebrew tap `brew tap osgeo/homebrew-osgeo4mac && brew install gdal2`
2. Install the mongo db legacy driver. `brew install mongo-cxx-driver-legacy`
3. Install the gdal2-mongodb plugin `brew install https://raw.githubusercontent.com/nickrobison/homebrew-osgeo4mac/gdal-mongo/Formula/gdal2-mongodb.rb`
4. Execute the following command: `GDAL_DRIVER_PATH=/usr/local/lib/gdalplugins/ /usr/local/opt/gdal2/bin/ogrinfo --format GTiff`

## Operating system

MacOS 10.13.4

## GDAL version and provenance

GDAL 2.3.0 installed from `homebrew-osgeo4mac` tap.

**Comment by rouault** [comment]
Can't test on a mac but it looks like the plugin doesn't link against the mongo shared object.

**Comment by nickrobison** [comment]
@rouault Thanks for the feedback, that was indeed the issue. Our formula didn't properly link in the mongodb driver, consulting your comments in the `mongodbdriver.cpp` file helped clear things up.

Apologies for the unnecessary bug report. Looks like we've gotten the plugin working and merged into our tap.
