### ISSUE TITLE
Read pixels at large offsets with RasterIO

### ISSUE THREAD

**Issue by DamienJTh** [OSGeo/gdal#6770]
Hi,

I'm working with the GDAL C API to process big GeoTiff images (reading them, changing the pixels values etc...) and for the moment I don't have any problem because my images are 32768x32768 pixels so when I use GDALRasterIO() function I don't overflow the 32bits integers offsets (nDSXOff and nDSYOff) of the function:

CPLErr GDALRasterIO(GDALRasterBandH hRBand, GDALRWFlag eRWFlag, **int nDSXOff, int nDSYOff**, int nDSXSize, int nDSYSize, void *pBuffer, int nBXSize, int nBYSize, GDALDataType eBDataType, int nPixelSpace, int nLineSpace)

I see there are other functions to read data from an image: GDALRasterIOEx() and GDALReadBlock() but they also use 32bits integers.

There may be a time where I need to process larger images, so I would like to know if it is possible to modify the signature of these functions to handle offsets larger than 32bits signed integer (and maybe also the sizes):

CPLErr GDALRasterIO(GDALRasterBandH hRBand, GDALRWFlag eRWFlag, **long nDSXOff, long nDSYOff**, int nDSXSize, int nDSYSize, void *pBuffer, int nBXSize, int nBYSize, GDALDataType eBDataType, int nPixelSpace, int nLineSpace)

## Steps to reproduce the problem.

Open an image of more than 32768x32768 pixels, for instance 40000x40000 pixels.
Try reading a pixel value at offset 35000x35000:
```c
#include <gdal.h>

GDALDatasetH dataset;
GDALRasterBandH band;
int pixel = 0;

dataset = GDALOpen("big_img.tif", GA_ReadOnly);
band = GDALGetRasterBand(dataset, 1);
GDALRasterIO(band, GF_Read, 35000, 35000, 1, 1, &pixel, 1, 1, GDT_Int16, 0, 0);
```

This will overflow the 32bits signed integers offsets.

## Environment

O.S.: Ubuntu 22.04 64 bit
GDAL version: GDAL 3.5.2, released 2022/09/02 installed with apt
GCC: gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0

Let me know if I have forgotten some details.
Thanks in advance.

**Comment by tbonfort** [comment]
With signed 32 bit ints you are fine reading images up to 2,147,483,647 not 32768 :)

**Comment by DamienJTh** [comment]
Oh yes, indeed, I'm an idiot :D
Sorry and thanks !
