### ISSUE TITLE
gdalwarp creates empty cells along the edge of adjacent files when -t_srs, --tap and --tr options are enabled

### ISSUE THREAD

**Issue by jfbourgon** [OSGeo/gdal#6777]
## Expected behavior and actual behavior.

Using gdalwarp to reproject two adjacent raster files that share a common edge boundary in the original projection (EPSG:2960 in this specific case) is creating empty/nodata cells along the edge of the files when a target grid is enforced using `-t_srs`, `--tap` and `--tr` options

Edge boundary in original files (displayed in the target srs but not yet reprojected)
![image](https://user-images.githubusercontent.com/1030226/203408998-a5381ebd-5422-4c2e-ad6e-6e443050d2fa.png)

Edge boundary in target files (once reprojected)
![image](https://user-images.githubusercontent.com/1030226/203408908-0268fb97-1b0c-4e94-8f68-5cf207b83c88.png)

Since the original files are adjacent, we would expect the edge boundary to do not include any empty/no data cells. It looks like gdalwarp in not identifying any contributing cells from the source grids to fill some cells in the target grid along the edge while performing the reprojection even if there is no gap in the source coverage. The `--tap` and `--tr` options are specified to ensure a target grid with fixed/rounded cell sizes aligned with target srs.

## Steps to reproduce the problem.

Source DTM file are available here:
https://datacube-stage-data-public.s3.ca-central-1.amazonaws.com/share/dtm_1m_utm19_w_21_110.tif
https://datacube-stage-data-public.s3.ca-central-1.amazonaws.com/share/dtm_1m_utm19_w_21_111.tif

The reprojection is performed using the following commands:
```
gdalwarp -co COMPRESS=LZW -t_srs EPSG:3979 -r bilinear -tr 1 1 -tap dtm_1m_utm19_w_21_110.tif dtm_1m_utm19_w_21_110-3979.tif
gdalwarp -co COMPRESS=LZW -t_srs EPSG:3979 -r bilinear -tr 1 1 -tap dtm_1m_utm19_w_21_111.tif dtm_1m_utm19_w_21_111-3979.tif
```
Then the result is displayed using QGIS 3.26

## Operating system & GDAL version and provenance
Behavior was tested against following docker images: `osgeo/gdal:ubuntu-small-3.6.0` and `osgeo/gdal:ubuntu-small-3.5.3`

**Comment by jratike80** [comment]
The -tap option was designed to resolve that situation and for example I have been using it for tens of thousands of aerial images with good results so the title is too pessimistic - that does not happen always. However, it seems to happen to you. I will have a try with your images and commands. Meanwhile you could help a bit and test the different resampling methods. I believe I have been using just average.

**Comment by rouault** [comment]
The issue is related to the default error theshold used for the default approximate coordinate transformation, and is independent of the selected resampling method. Setting ``-et 0`` solves the issue at the expense of significantly longer processing time. I'm looking if there wouldn't be a way to apply the exact coordinate tranformer specifically on edges of the source raster to avoid that issue while enjoying the overall speedup of the approximate coordinate transformer elsewhere
Another possibiility is to use gdalbuildvrt to create a virtual mosaic of the 2 input tiles, and reproject it with gdalwarp.
