### ISSUE TITLE
Gdal installation

### ISSUE THREAD

**Issue by PelopG** [OSGeo/gdal#6793]
## Expected behavior and actual behavior.

For example (please modify !!!): I expected to be able to install gdal on conda enviroment and it returns an error message
instead.

## Steps to reproduce the problem.

Tried all the possible installations from: https://anaconda.org/conda-forge/gdal
Erros hyave to do with packages incompatability

## Operating system

MacOS Ventura M1 pro (processor)

## GDAL version and provenance

Required a version of >=3.1

**Comment by rouault** [comment]
This issue is about the use of a package, not the source distribution. Closing consequently. Rather report to https://github.com/conda-forge/gdal-feedstock/issues/new/choose after making sure you've read Conda related documentation.
