### ISSUE TITLE
New version of gdalinfo doesn't show the pixel size of the NetCDF data

### ISSUE THREAD

**Issue by anikfal** [OSGeo/gdal#6806]
With this problem, `gdal_translate` cannot convert NetCDF to GeoTIFF correctly.

**GDAL 2.2.3, released 2017/11/20**

`gdalinfo rh_700hpa_2022-08-08_18.nc`
> Driver: netCDF/Network Common Data Format
> Files: rh_700hpa_2022-08-08_18.nc
> Size is 325, 244
> Coordinate System is `'
> Origin = (36.557564111403480,44.705391487466947)
> Pixel Size = (0.100142773286796,-0.100045365070610)
> Metadata:
>   NC_GLOBAL#Conventions=None
>   varname#_FillValue=9.96921e+36
> Corner Coordinates:
> Upper Left  (  36.5575641,  44.7053915) 
> Lower Left  (  36.5575641,  20.2943224) 
> Upper Right (  69.1039654,  44.7053915) 
> Lower Right (  69.1039654,  20.2943224) 
> Center      (  52.8307648,  32.4998569) 
> Band 1 Block=325x1 Type=Float32, ColorInterp=Undefined
>   NoData Value=9.96920996838686905e+36
>   Metadata:
>     NETCDF_VARNAME=varname
>     _FillValue=9.96921e+36

**GDAL 3.4.3, released 2022/04/22**
Unlike GDAL 2.2.3, "Origin" and "Pixel Size" are missing. My OS is Fedora-36.

`gdalinfo rh_700hpa_2022-08-08_18.nc`

> Driver: netCDF/Network Common Data Format
> Files: rh_700hpa_2022-08-08_18.nc
> Size is 325, 244
> Metadata:
>   NC_GLOBAL#Conventions=None
>   varname#_FillValue=9.96921e+36
> Corner Coordinates:
> Upper Left  (    0.0,    0.0)
> Lower Left  (    0.0,  244.0)
> Upper Right (  325.0,    0.0)
> Lower Right (  325.0,  244.0)
> Center      (  162.5,  122.0)
> Band 1 Block=325x1 Type=Float32, ColorInterp=Undefined
>   NoData Value=9.96920996838686905e+36
>   Metadata:
>     NETCDF_VARNAME=varname
>     _FillValue=9.96921e+36

**Comment by rouault** [comment]
Please attach the file so we can have a look, but this is likely a file that doesn't fully follow netCDF-CF conventions, and we have harden that in GDAL 3.4.2 and later to avoid false positive geotransform reports for non spatial variables

See response https://github.com/OSGeo/gdal/issues/6556#issuecomment-1285981714

**Comment by anikfal** [comment]
Thank you very much. Actually I never took NetCDF convention as something that can be problematic in data processing. That was really a valuable insight for me.

I have implemented gdal in my software ([PostWRF](https://github.com/anikfal/PostWRF)), to convert a special NetCDF data (with no convention) to GeoTIFF.

For now, I use the workaround you commented in #6556. That works for my case.

**Comment by rouault** [comment]
The issue with just taking the values of the X and Y dimensions as geotransform is there are situations, in particularly when using simultaneously a combination of (X,Y) projected and (lon, lat) geographic variables where GDAL could use indexing variables as projected coordinates whereas they were just integer values. This would lead to wrong georeferencing. So GDAL now strictly adheres to the netCDF CF conventions to avoid any false positive.
