### ISSUE TITLE
rgdal compilation problem

### ISSUE THREAD

**Issue by paulz1** [OSGeo/gdal#681]
Sorry, I understand that probably here we should post gdal issues, not the rgdal.
But I could not find how and where to post rgdal problem, so may be someone here could help me.

I try to install rgdal on CentOS 7 system.
R-core-3.5.0-1.el7.x86_64
gdal-1.11.4-3.el7.x86_64
gdal-devel-1.11.4-3.el7.x86_64

install.packages("rgdal") does not work because of compilation problem.

Finally I found that the problem is in wrong instructions like :
```
#if GDAL_VERSION_MAJOR <= 2 && GDAL_VERSION_MINOR <= 2 
  oSRS.importFromWkt( &pszSRS_WKT );
#else
  oSRS.importFromWkt( (const char*) pszSRS_WKT );
#endif

```
As we have GDAL_VERSION_MINOR > 2 it goes to the "else" branch, but it's not congruent/conform to gdal-devel installation. So the compilation stopped.

Manually replace these instructions to "then" branch, for example like that : 
```
oSRS.importFromWkt( &pszSRS_WKT );
#if GDAL_VERSION_MAJOR <= 2 && GDAL_VERSION_MINOR <= 2 
  oSRS.importFromWkt( &pszSRS_WKT );
#else
  oSRS.importFromWkt( (const char*) pszSRS_WKT );
#endif
```
fix the problem.
So we could compile and install rgdal.

I understand that it's a very silly and wrong approach, I did it just to make a test.

Could someone help me about this problem?

**Comment by paulz1** [comment]
Additional information.
When the compilation stopped we have the errors like :

> gdal-bindings.cpp: In function ‘SEXPREC* RGDAL_GDALwithGEOS()’:
> gdal-bindings.cpp:332:81: error: no matching function for call to ‘OGRGeometryFactory::createFromWkt(const char*, NULL, OGRGeometry**)’
>      OGRGeometryFactory::createFromWkt( (const char*) pszWKT, NULL, &poGeometry1 );
>                                                                                  ^
> gdal-bindings.cpp:332:81: note: candidate is:
> In file included from /usr/include/gdal/ogr_feature.h:34:0,
>                  from /usr/include/gdal/ogrsf_frmts.h:35,
>                  from gdal-bindings.cpp:7:
> /usr/include/gdal/ogr_geometry.h:663:19: note: static OGRErr OGRGeometryFactory::createFromWkt(char**, OGRSpatialReference*, OGRGeometry**)
>      static OGRErr createFromWkt( char **, OGRSpatialReference *,
>                    ^
> /usr/include/gdal/ogr_geometry.h:663:19: note:   no known conversion for argument 1 from ‘const char*’ to ‘char**’
> gdal-bindings.cpp:338:81: error: no matching function for call to ‘OGRGeometryFactory::createFromWkt(const char*, NULL, OGRGeometry**)’
>      OGRGeometryFactory::createFromWkt( (const char*) pszWKT, NULL, &poGeometry2 );
>                                                                                  ^

**Comment by paulz1** [comment]
The files concerned in rgdal package are : gdal-bindings.cpp and ogr_proj.cpp

**Comment by rouault** [comment]
Maybe @rsbivand can help here for this rgdal issue.

I think the rgdal #ifdef is not properly written. It should be
```
#if GDAL_VERSION_MAJOR == 1 || ( GDAL_VERSION_MAJOR == 2 && GDAL_VERSION_MINOR <= 2 )
```
to support GDAL 1.x versions

**Comment by rsbivand** [comment]
Thanks, @rouault . This is a solution, the OP should have posted on [R-sig-geo](https://stat.ethz.ch/mailman/listinfo/r-sig-geo) and/or contacted me as maintainer. CentOS is a real headache because people think that free means you don't need to help maintain software that is adjusting to current releases while using PROJ 4.8.0. An easy fix is to install PROJ and GDAL from source and benefit from all the new features and bug fixes.

**Comment by paulz1** [comment]
Thanks @rouault and @rsbivand

So no solution for CentOS 7 for the moment?
Or..

a) solution to install PROJ and GDAL from source ;
b) modify rgdal source like @rouault proposed ;

"a" is not possible to us. We have several servers in prod (I work in research laboratory) so I could not manually install such things.
"b" could be a solution even if it's a little bit dirty.

**Comment by rsbivand** [comment]
Fixed src/gdal-bindings.cpp committed to [R-Forge](https://r-forge.r-project.org/scm/viewvc.php/pkg/src/gdal-bindings.cpp?root=rgdal&view=log) - download and replace in source tarball. As yet unchecked, you can help by doing that.

**Comment by paulz1** [comment]
@rsbivand 
The fix of src/gdal-bindings.cpp seems to work perfectly. But there is the same problem with src/ogr_proj.cpp at line 59.
Could you fix it as well?

Thank you very much in advance.

**Comment by rsbivand** [comment]
Committed revision 757 (no inflight netwoirk). Please download src/ogr_proj.cpp, try and report back.

**Comment by rsbivand** [comment]
Reported success from a CentOS user by email - I'd alerted him to the thread.

**Comment by paulz1** [comment]
Ok, I confirm. It works without problem on our CentOS 7 server.
Thank you very much.

**Comment by rsbivand** [comment]
Great, thanks!

**Comment by rsbivand** [comment]
Please refer to [this posting](https://stat.ethz.ch/pipermail/r-sig-geo/2018-June/026677.html) and consider testing:

```
install.packages("rgdal", repos="http://R-Forge.R-project.org")
```
just to be sure.
