### ISSUE TITLE
Feature request: Support pipe "|" as a separator for CSV driver

### ISSUE THREAD

**Issue by jumpinjackie** [OSGeo/gdal#6811]
In my country (Australia) we have a popular open data set called the [Geocoded National Address File (G-NAF)](https://data.gov.au/dataset/ds-dga-19432f89-dc3a-4ef3-b943-5326ef1dbecc/details?q=g-naf), which is an authoritative file of every address in the country with latitude/longitude included.

This data set is updated quarterly and is provided as a series of pipe `|` delimited text files.

Unfortunately, my attempts to read such files with `ogrinfo` or `ogr2ogr` are not successful because the OGR CSV driver does not support/detect pipes as a valid separator, making OGR un-suitable as a starting point of any ETL process to convert/massage this dataset into other spatial data formats or relational databases.

It would be very nice if the CSV driver can support pipes as separator

**Comment by jumpinjackie** [comment]
@jratike80 Thanks for the `sed` suggestion. It sounds like a solid workaround in the absence of this support in the CSV driver.

**Comment by rouault** [comment]
@jumpinjackie I guess we could accept a patch supporting pipe as separator. It should be a matter of editing https://github.com/OSGeo/gdal/blob/dc39f7d68095621842a2547ab06c60a03fd34a19/port/cpl_csv.cpp#L539
