### ISSUE TITLE
Performance of ENVI BIP interleave

### ISSUE THREAD

**Issue by chacha21** [OSGeo/gdal#6819]
GDAL 3.5.3
Windows 7 64b
Latest Visual studio

I was surprised to discover that submitting pixel-interleaved data to a BIP envi dataset was ultimately not mapped to a `memcpy()` in `GDALRasterBand::IRasterIO()` but had to resort to some `GDALCopyWords64()` to handle different strides of input buffer and dst dataset.
I thought that using the same interleaving for the input buffer and the dataset guaranteed the best performance by avoiding storage reinterleaving.
Did I make a mistake somewhere ?

```

  GDALAllRegister();

  {
    GDALDriverManager* gdalDriverManager = GetGDALDriverManager();
    GDALDriver* enviDriver = !gdalDriverManager ? 0 : gdalDriverManager->GetDriverByName("ENVI");

    const int spatialWidth = 800;
    const int spatialHeight = 1000;
    const int bandsCount = 734;
    std::vector<float> dataLine(bandsCount*spatialWidth);//we assume PIXEL interleave

    const char* envi_options[] = {
      "INTERLEAVE=BIP",
      nullptr
    };
    const char** options = &envi_options[0];
    GDALDriver* gdalDriver = enviDriver;

    CPLErr error = CE_None;
    std::string dstFilepath = "temp.bip";
    GDALDataset* ds = gdalDriver->Create(dstFilepath.c_str(), spatialWidth, spatialHeight, bandsCount, GDT_Float32, options);
    for(int line = 0 ; line<spatialHeight ; ++line)
    {
      error = GDALDatasetRasterIO(ds, GDALRWFlag::GF_Write,
        0, line,
        spatialWidth, 1,
        dataLine.data(), spatialWidth, 1,
        GDT_Float32,
        bandsCount, nullptr, 
        static_cast<int>(bandsCount*sizeof(float)),//pixel
        static_cast<int>(bandsCount*spatialWidth*sizeof(float)),//line
        static_cast<int>(sizeof(float))//band
      );
    }
    ds->Release();
  }
```

**Comment by chacha21** [comment]
Could it be that the cache block structure is inherently band-based and that BIP has no efficient backing representation ?

**Comment by chacha21** [comment]
I have just tested and I don't think it is fixed for an ENVI dataset.
When submitting a spatial line as BIP, (a 2D buffer where x is bands, y is pixels), an inner loop on bands (in BlockBasedRasterIO()) will still deinterleave and not resort to a memcpy

**Comment by rouault** [comment]
> When submitting a spatial line as BIP, (a 2D buffer where x is bands, y is pixels), an inner loop on bands (in BlockBasedRasterIO()) will still deinterleave and not resort to a memcpy

the optimization triggers in very specific conditions. See the code

**Comment by chacha21** [comment]
Ok, I can see now that it is only triggered for GF_Read, not GF_Write

**Comment by rouault** [comment]
GF_Write could likely be added in a similar way, but it would need to take care of flushing potentially cached buffers before writing directly to the file

**Comment by chacha21** [comment]
I understand better now : your strategy would be to bypass the cache and directly write to the file.
However, it is unclear how it would affect overall performance. Is it better to deinterleave in memory, or call a sequential file write (that might be cached by the OS) ? The answer is certainly "it depends".

**Comment by chacha21** [comment]
In rawdataset.cpp, `bCanDirectAccessToBIPDataset` should perhaps request `eAccess == GA_ReadOnly `
Or there is a missing invalidation of `poBand->bNeedFileFlush` somewhere in the write process
