### ISSUE TITLE
ogr2ogr2 .tab => .shp does not create empty Shapefile

### ISSUE THREAD

**Issue by boomdrak** [OSGeo/gdal#682]
When trying to convert empty ESRI Tab files to Shapefile, ogr2ogr only creates .dbf and .prj file. It simply skips creating an empty .shp and .shx file.

This works fine on GDAL 2.2.3 and below..

How to reproduce the problem
----------------------------------

ogr2ogr.exe -f "ESRI Shapefile" "5_Plan_Ror.shp" "5_Plan_Ror.tab" -t_srs EPSG:900913 -where "ogr_geometry='POINT'"

Tab files for testing purpose: https://gem.micado.no/dl/gdal-bug.zip 

GDAL Version
---------------
GDAL 2.3.0 Windows x64 
Filename: gdal-203-1911-x64-core.msi
SHA1: 1E1D76162FEF610BF18615D5EE48828AF7A935B1
Download link: http://download.gisinternals.com/sdk/downloads/release-1911-x64-gdal-2-3-0-mapserver-7-0-7/gdal-203-1911-x64-core.msi

**Comment by rouault** [comment]
This is an intended change. In GDAL 2.3.0, the MITAB driver has been enhanced to better detect non-spatial .tab files, as in your example
```
 * report aspatial .tab as wkbNone geometry type
```
You can force the generation of a point shapefile by adding -nlt POINT to your ogr2ogr command line

**Comment by boomdrak** [comment]
Thank you so much for clarification :) (Y)
