### ISSUE TITLE
ogcapi update / fixes required

### ISSUE THREAD

**Issue by jerstlouis** [OSGeo/gdal#6832]
In the context of the [OGC Web Mapping Code Sprint](https://developer.ogc.org/sprints/19/).
Related QGIS issue about better supporting OGC API: https://github.com/qgis/QGIS/issues/50296 .
Note: [_OGC API - Tiles_](https://docs.ogc.org/is/20-057/20-057.html) is now published.

## Expected behavior and actual behavior.

**_First part: (out of date OGC API - Maps)_**

Using _gdalinfo_ and _ogrinfo_ with some OGC API collection end-points offering vector tiles reports a failure, and triggers invalid `/map?f=json` requests.

For example: `OGCAPI:https://maps.gnosis.earth/ogcapi/collections/Daraa:AgricultureSrf`

Note that the `f=` parameter is not specified by most OGC API (_EDR_ being the one exception), and that clients should always use the `Accept:` header instead to negotiate a particular representation, or follow typed links (that would _already_ contain the `f` parameter). The `href` in links must be treated as opaque and the client should not add additional parameters.

**The _map metadata_ resource is no longer part of the _OGC API - Maps_ specification.** Instead, the landing page and/or collection contains a link to a map resource with the `[ogc-rel:map]` relation type, which is directly the map itself.

**_Second part: (out of date OGC API - Tiles)_**

Furthermore, although both _gdalinfo_ and _ogrinfo_ on a multi-layer collection shows subdatasets in gdalinfo and ogrinfo, QGIS will report a failure to add the layer. It is unclear whether this is a GDAL or QGIS bug... It used to be that QGIS would show a dialog listing available collections to add.

For example: `OGCAPI:https://maps.gnosis.earth/ogcapi/collections/Daraa`

One change that has been introduced that may be the source of the problem is the **separate `tilesets-map` / `tilesets-vector` / `tilesets-coverage`** URIs for different tilesets types, **as opposed to `tilesets`** for all.

Also please note that the client should support both `http://` URIs and CURIEs, e.g. `[ogc-rel:tilesets-vector]`, for TileMatrixSets URIs as well (but see https://github.com/opengeospatial/NamingAuthority/issues/211).

Note that both Map and Coverage collections still seem to work fine in QGIS, e.g.:

https://maps.gnosis.earth/ogcapi/collections/SRTM_ViewFinderPanorama

https://maps.gnosis.earth/ogcapi/collections/blueMarble

## Steps to reproduce the problem.

**_First problem_** (single layer collection showing FAILURE: in ogrinfo and gdalinfo):

gdalinfo `OGCAPI:https://maps.gnosis.earth/ogcapi/collections/Daraa:AgricultureSrf`
ogrinfo `OGCAPI:https://maps.gnosis.earth/ogcapi/collections/Daraa:AgricultureSrf`

**_Second problem_** (neither multi-layer nor single layer collection offering vector tiles working in QGIS:

QGIS > Add Layer > Vector > File > OGCAPI:https://maps.gnosis.earth/ogcapi/collections/Daraa ; Add button
or
QGIS > Add Layer > Vector > File > OGCAPI:https://maps.gnosis.earth/ogcapi/collections/Daraa:AgricultureSrf ; Add button.

## GDAL version and provenance

GDAL 3.3.1, released 2021/06/28
QGIS version | 3.22.2-Białowieża

**Comment by rouault** [comment]
> and triggers invalid `/map?f=json` requests.

``gdalinfo "OGCAPI:https://maps.gnosis.earth/ogcapi/collections/Daraa:AgricultureSrf" `` triggers a ``ERROR 1: <h1>GNOSIS Map Server (OGCAPI) - 406 Not Acceptable</h1><h3>Cannot return map in acceptable format</h3>`` because of the following snippet in https://maps.gnosis.earth/ogcapi/collections/Daraa:AgricultureSrf JSON response:
```json
      {
          "rel" : "http://www.opengis.net/def/rel/ogc/1.0/map",
          "type" : "application/json",
          "title" : "Maps available for this dataset (as JSON)",
          "href" : "/ogcapi/collections/Daraa:AgricultureSrf/map?f=json"
       }
```

None of the following requests work:
```
$ curl "https://maps.gnosis.earth/ogcapi/collections/Daraa:AgricultureSrf/map?f=json"
<h1>GNOSIS Map Server (OGCAPI) - 406 Not Acceptable</h1><h3>Cannot return map in acceptable format</h3>

$ curl "https://maps.gnosis.earth/ogcapi/collections/Daraa:AgricultureSrf/map?f=json" -H "Accept: application/json"
<h1>GNOSIS Map Server (OGCAPI) - 406 Not Acceptable</h1><h3>Cannot return map in acceptable format</h

$ curl "https://maps.gnosis.earth/ogcapi/collections/Daraa:AgricultureSrf/map" -H "Accept: application/json"
<h1>GNOSIS Map Server (OGCAPI) - 406 Not Acceptable</h1><h3>Cannot return map in acceptable format</h
```

So this is a server error. The OGCAPI driver only follows the href as it is specified.

**Comment by jerstlouis** [comment]
@rouault Thank you very much for looking into this. Oops, apologies, there is definitely a server error that I am fixing right now -- that JSON link should not be included.

However, there is no longer a separate JSON document describing the map, so the client should not be looking for or negotiating an `application/json` representation of the map. It should go straight for the PNG, JPEG or GeoTIFF at `/map`.

**Comment by rouault** [comment]
The churn in OGC APIs is quite concerning. https://github.com/OSGeo/gdal/pull/6881 tries to fix most issues reported here, but tilesets API don't work due to the JSON output of requests like https://maps.gnosis.earth/ogcapi/tileMatrixSets/WorldCRS84Quad having changed in incompatible way... Sigh^2. Hint for potential contributors: changes should be done in gcore/tilematrixset.cpp

**Comment by jerstlouis** [comment]
@rouault Thank you very much for the fixes.

Which change(s) do you refer too? I thought we had taken a great amount of care to minimize any changes, and I honestly didnt't think anything was changed about this since our last successful _Tiles_ TIEs with GDAL.

**Comment by rouault** [comment]
> Which change(s) do you refer too?

My guess is that GDAL expects the JSON profile of OGC Two Dimensional Tile Matrix Set v1.0 (https://docs.opengeospatial.org/is/17-083r2/17-083r2.html), whereas https://maps.gnosis.earth/ogcapi/tileMatrixSets/WorldCRS84Quad is probably v2 (https://docs.opengeospatial.org/is/17-083r4/17-083r4.html) (weird that the OGC ID of the doc is the same, except the revision number)

**Comment by jerstlouis** [comment]
@rouault Yes it is definitely 2.0, 1.0 is more or less abandoned.
I was under the impression the TIEs with GDAL we did back in March 2021 were already following the draft v2 though, I might be remembering wrong.

**Comment by jerstlouis** [comment]
Also note that a client is not actually required to parse the TileMatrixSet definition and can recognize a registered TileMatrixSet when the `tileMatrixSetURI` property is present for a tileset either in the [list of tilesets](https://maps.gnosis.earth/ogcapi/collections/blueMarble/tiles?f=json) or in a particular [tileset metadata document](https://maps.gnosis.earth/ogcapi/collections/blueMarble/tiles/WorldCRS84Quad?f=json).

e.g., GDAL could always parse its own embedded metadata in v1 format, or the one at https://schemas.opengis.net/tms/1.0/json/examples/WorldCRS84Quad.json, or use another hard-coded mechanism to understand _WorldCRS84Quad_.
