### ISSUE TITLE
Segmentation Fault from ogr2ogr when clipsrc is larger than gml:Envelope when converting to FileGDB

### ISSUE THREAD

**Issue by rooby** [OSGeo/gdal#6836]
## Expected behavior and actual behavior.

When converting a GML file to FileGDB, if I use the clipsrc param with a BBOX larger than the BBOX of the gml:Envelope in the input file, it throws a Segmentation Fault.
The -t_srs projection also seems to affect this. For example, 4326 doesn't seem to have the same issues as 7855.
It seems to work if clipsrc is removed or if it is reduced to the GML envelope.
It also seems to work OK with other output formats like GeoJSON, even if clipsrc is larger than the envelope.

It would be ideal if it would successfully run the command, like it does with other formats, although it would also be better even if it just errored in a nicer way than a Segmentation Fault.

## Steps to reproduce the problem.
```
ogr2ogr -f FileGDB -t_srs EPSG:7855 -clipsrc 144 -34.7 144.7 -34 -skipfailures -makevalid -oo EXPOSE_GML_ID=NO -oo DOWNLOAD_SCHEMA=NO ogr2ogr-segfault-input.gdb ogr2ogr-segfault-input.xml
```
Example file attached with extension changed to txt.
[ogr2ogr-segfault-input.txt](https://github.com/OSGeo/gdal/files/10138802/ogr2ogr-segfault-input.txt)

## Operating system

Amazon Linux 2: 4.14.291-218.527.amzn2.x86_64
Although I've reproduced it on other Linux and Windows machines.

## GDAL version and provenance

3.4.0 - Custom build from source
Also tried on 3.4.0 from GISInternals

I'm running using the Java bindings, using VectorTranslate, however the same thing happens on the cli with ogr2ogr.

**Comment by jratike80** [comment]
> It also seems to work OK with other formats like GeoJSON, even if clipsrc is larger than the envelope.
I guess you mean other formats than FileGDB as output, but please confirm.

**Comment by rooby** [comment]
> It also seems to work OK with other formats like GeoJSON, even if clipsrc is larger than the envelope.
> I guess you mean other formats than FileGDB as output, but please confirm.

That’s right. Other output formats.

**Comment by rouault** [comment]
If you use GDAL 3.6.0 with the OpenFileGDB driver, you won't get the crash.
Fix for the FileGDB driver queued in https://github.com/OSGeo/gdal/pull/6841

**Comment by rooby** [comment]
Thanks for the quick fix @rouault 
So it wasn't related to the clipsrc at all?

When I run in 3.6.0 with OpenFileGDB I get 8 of this error:

> ERROR 6: Can only insert a LineString/MultiLineString/CircularString/CompoundCurve/MultiCurve in a esriGeometryLine layer

But it doesn't give me any information regarding which feature or line or anything that the error relates to, and as far as I can tell the only geometries in there are LineString so I'm not sure what's causing the error.

**Comment by rooby** [comment]
Oh right, that makes sense now.
Thanks @rouault
