### ISSUE TITLE
Python bindings: print(geometry) doesn't export M values

### ISSUE THREAD

**Issue by sirhcybe** [OSGeo/gdal#6842]
## Expected behavior and actual behavior.
Expected:
I am using the OpenFileGDB driver to open an Esri GeoDatabase and read the geometry in each feature into a WKT string. I am working with linear referencing data of either type MULTILINESTRING M or MULTILINESTRING ZM. When I use Esri's ArcPy library to export the WKT string it always correctly outputs the geometry type. I would expect GDAL to do the same.

Actual:
I have found GDAL does not always correctly detect the geometry type. When I use GDAL to do it, some MULTILINESTRING M or MULTILINESTRING ZM features are read as MULTILINESTRING or MULTILINESTRING Z. I suspect that this is because there are data issues in the underlying data. For example, I noticed one feature that is not working has NaN values in it's Z field in the ArcPy WKT string. However, my requirements are to simply read in the data as it is and having the geometry type changed by GDAL is causing a lot of issues.

## Steps to reproduce the problem.

This Python code will output the WKT strings for all features in the first layer of a GDB:

```
from osgeo import ogr
driver = ogr.GetDriverByName("OpenFileGDB")
ds = driver.Open(r"<Path to GDB>", 0)
layer = ds.GetLayerByIndex(0)
feature = layer.GetNextFeature()
while feature is not None:
    geometry = feature.GetGeometryRef()
    print(geometry)
    feature = layer.GetNextFeature()
```
[GDAL_WKT_Issue.gdb.zip](https://github.com/OSGeo/gdal/files/10145044/GDAL_WKT_Issue.gdb.zip)
The zipped GDB that I have attached has a single geometry that should export as MULTILINESTRING M but instead exports as MULTILINESTRING. If the above script is pointed to the attached GDB, you can reproduce the issue.

## Operating system

Windows 10 x64

## GDAL version and provenance

3.3.0e

**Comment by rouault** [comment]
> For example, I noticed one feature that is not working has NaN values in it's Z field in the ArcPy WKT string.

actually inspecting with a low level tool, the geometry has no Z values in that geometry at all. It is a GeneralPolyline with curves and M values, no Z.
Can you paste the WKT string ArcPy export ? As far as I known, NaN values are illegal in WKT. So GDAL behavior seems very reasonable to me.

**Comment by rouault** [comment]
oh, I see your issue.
print(geometry) must use the old ExportToWkt(), ot ExportToIsoWkt()
If you use, print(geometry.ExportToIsoWkt()) you'll get "MULTILINESTRING M ((-87.904578194 37.398957393 0,-87.904385921 37.3994051610001 0.032999999995809,"
So the issue is more in the Python bindings

**Comment by sirhcybe** [comment]
Hmm, I did try using ExportToIsoWkt() and had the same results. However, I updated GDAL to 3.6.0 and tried again and that worked so it must be a bug that was fixed already.
