### ISSUE TITLE
GeoJSONSeq: the -t_srs in ogr2ogr is not working when the target file type is GeoJSONSeq

### ISSUE THREAD

**Issue by qwertwwwe** [OSGeo/gdal#6859]
## Expected behavior and actual behavior.

In ogr2ogr cmd, the spatial reference in the output file should be the same as the parameter passed in the -t_srs.
When the output file type is GeoJSONSeq, the spatial reference is always 4326 no matter what passed in -t_srs, and there is no error message.

## Steps to reproduce the problem.

simple data: 
[test-shape.zip](https://github.com/OSGeo/gdal/files/10152805/test-shape.zip)

ogr2ogr -f "GeoJSONSeq" -t_srs "EPSG:3857" test.json ./test-shape.shp

## Operating system

Ubuntu 16.04 64 bit

## GDAL version and provenance

the 3.6.0 version from docker image osgeo/gdal:ubuntu-small-3.6.0

**Comment by jratike80** [comment]
Maybe that is intentional. By the documentation https://gdal.org/drivers/vector/geojsonseq.html the driver implements https://tools.ietf.org/html/rfc7946 and https://tools.ietf.org/html/rfc8142 and thus only CRS84 coordinate system (WGS84 coordinates in longitude-latitude order) is supported.
