### ISSUE TITLE
gdalinfo check wmts service link failed related to proj

### ISSUE THREAD

**Issue by z-pc** [OSGeo/gdal#6866]
## Expected behavior and actual behavior.
I'm beginner in gdal.   
I read this [this guide](https://gdal.org/drivers/raster/wmts.html) to check a wmts service, but I always get an error message related to proj.

## Steps to reproduce the problem.
Run: `gdalinfo "http://maps.wien.gv.at/wmts/1.0.0/WMTSCapabilities.xml"` 

Get result:
```
Driver: WMTS/OGC Web Map Tile Service
Files: none associated
Size is 512, 512
Origin = (0.000000000000000,0.000000000000000)
Pixel Size = (1.000000000000000,1.000000000000000)
Subdatasets:
  SUBDATASET_1_NAME=WMTS:http://maps.wien.gv.at/wmts/1.0.0/WMTSCapabilities.xml,layer=fmzk3dviewer
  SUBDATASET_1_DESC=Layer Stadtplan3D Grundkarte
  SUBDATASET_2_NAME=WMTS:http://maps.wien.gv.at/wmts/1.0.0/WMTSCapabilities.xml,layer=lb
  SUBDATASET_2_DESC=Layer Orthofoto 2021
  SUBDATASET_3_NAME=WMTS:http://maps.wien.gv.at/wmts/1.0.0/WMTSCapabilities.xml,layer=lb2020
  SUBDATASET_3_DESC=Layer Orthofoto 2020
  SUBDATASET_4_NAME=WMTS:http://maps.wien.gv.at/wmts/1.0.0/WMTSCapabilities.xml,layer=lb2019
  SUBDATASET_4_DESC=Layer Orthofoto 2019
  SUBDATASET_5_NAME=WMTS:http://maps.wien.gv.at/wmts/1.0.0/WMTSCapabilities.xml,layer=lb2018
  SUBDATASET_5_DESC=Layer Orthofoto 2018
  SUBDATASET_6_NAME=WMTS:http://maps.wien.gv.at/wmts/1.0.0/WMTSCapabilities.xml,layer=lb2017
  SUBDATASET_6_DESC=Layer Orthofoto 2017
  SUBDATASET_7_NAME=WMTS:http://maps.wien.gv.at/wmts/1.0.0/WMTSCapabilities.xml,layer=lb2016
  SUBDATASET_7_DESC=Layer Orthofoto 2016
  SUBDATASET_8_NAME=WMTS:http://maps.wien.gv.at/wmts/1.0.0/WMTSCapabilities.xml,layer=lb2015
  SUBDATASET_8_DESC=Layer Orthofoto 2015
  SUBDATASET_9_NAME=WMTS:http://maps.wien.gv.at/wmts/1.0.0/WMTSCapabilities.xml,layer=lb2014
  SUBDATASET_9_DESC=Layer Orthofoto 2014
  SUBDATASET_10_NAME=WMTS:http://maps.wien.gv.at/wmts/1.0.0/WMTSCapabilities.xml,layer=lb1992
  SUBDATASET_10_DESC=Layer Luftbildplan 1992
  SUBDATASET_11_NAME=WMTS:http://maps.wien.gv.at/wmts/1.0.0/WMTSCapabilities.xml,layer=lb1976
  SUBDATASET_11_DESC=Layer Luftbildplan 1976
  SUBDATASET_12_NAME=WMTS:http://maps.wien.gv.at/wmts/1.0.0/WMTSCapabilities.xml,layer=lb1956
  SUBDATASET_12_DESC=Layer Luftbildplan 1956
  SUBDATASET_13_NAME=WMTS:http://maps.wien.gv.at/wmts/1.0.0/WMTSCapabilities.xml,layer=lb1938
  SUBDATASET_13_DESC=Layer Luftbildplan 1938
  SUBDATASET_14_NAME=WMTS:http://maps.wien.gv.at/wmts/1.0.0/WMTSCapabilities.xml,layer=fmzk
  SUBDATASET_14_DESC=Layer Stadtplan Grundkarte
  SUBDATASET_15_NAME=WMTS:http://maps.wien.gv.at/wmts/1.0.0/WMTSCapabilities.xml,layer=flwbplmzk
  SUBDATASET_15_DESC=Layer Fl├ñchenwidmungs- und Bebauungsplan
  SUBDATASET_16_NAME=WMTS:http://maps.wien.gv.at/wmts/1.0.0/WMTSCapabilities.xml,layer=beschriftung
  SUBDATASET_16_DESC=Layer Stadtplan Beschriftung
Corner Coordinates:
Upper Left  (   0.0000000,   0.0000000)
Lower Left  (       0.000,     512.000)
Upper Right (     512.000,       0.000)
Lower Right (     512.000,     512.000)
Center      (     256.000,     256.000)
```
Next, I copied a layer link on that result to get the information for the layer:
`gdalinfo "WMTS:http://maps.wien.gv.at/wmts/1.0.0/WMTSCapabilities.xml,layer=lb"` 
I get results:
```
ERROR 1: PROJ: proj_create: no database context specified
ERROR 1: PROJ: proj_create: no database context specified
ERROR 1: Cannot parse CRS 'urn:ogc:def:crs:EPSG:6.18.3:3857'
gdalinfo failed - unable to open 'WMTS:http://maps.wien.gv.at/wmts/1.0.0/WMTSCapabilities.xml,layer=lb'.
```
I tried on some other public services, and get the same error, eg:
[https://gis.sinica.edu.tw/worldmap/wmts?REQUEST=GetCapabilities&SERVICE=WMTS](https://gis.sinica.edu.tw/worldmap/wmts?REQUEST=GetCapabilities&SERVICE=WMTS)
[http://spectrum.mapinfoservices.com/rest/Spatial/WMTS/1.0.0/WMTSCapabilities.xml](http://spectrum.mapinfoservices.com/rest/Spatial/WMTS/1.0.0/WMTSCapabilities.xml)
[https://geobretagne.fr/geoserver/gwc/service/wmts?service=wmts&request=GetCapabilities](https://geobretagne.fr/geoserver/gwc/service/wmts?service=wmts&request=GetCapabilities)

Also tried connecting with this code:
```
    GDALAllRegister();
    std::string strUrlWmts = "WMTS:https://gis.sinica.edu.tw/worldmap/wmts/1.0.0/WMTSCapabilities.xml,layer=BingH" ;
    char** papszAllowInputDrivers = nullptr;
    char** papszOpenOptions = nullptr;

    GDALDatasetH hDataset =
        GDALOpenEx(strUrlWmts.c_str(), GDAL_OF_READONLY | GDAL_OF_RASTER | GDAL_OF_VERBOSE_ERROR,
                   papszAllowInputDrivers, papszOpenOptions, nullptr);
```
Still get the same error, and when debugging into the file: 
".\gdal\ogr\ogrspatialreference.cpp" -> "OGRErr OGRSpatialReference::importFromURN( const char *pszURN )"
-> `auto obj = proj_create(d->getPROJContext(), pszURN);`
proj_create always return nullptr, 

Did I forget something or do something stupid?
## Operating system

Windows 11
Visual Studio 2019
MSVC with C++  17

## GDAL version and provenance
GDAL 3.5.3
I tried using gadlinfo 3.5.3 built by vcpkg and self-build from the source.   
Thanks.

**Comment by jratike80** [comment]
There is no bug but there is something wrong in your GDAL and Proj installation. If you can't find out what is wrong with your configuration you can ask help from gdal-dev mailing list. Notice that because the error is in your system you must give detailed information about how you have build and installed Proj and GDAL, including what environmental variables you have set. For example wrong or missing PROJ_LIB could explain your problem.

If you want to see quickly GDAL and WMTS in action on Windows you can install GDAL with the OSGeo4W installer.

```
gdalinfo "WMTS:http://maps.wien.gv.at/wmts/1.0.0/WMTSCapabilities.xml,layer=lb"
Driver: WMTS/OGC Web Map Tile Service
Files: none associated
Size is 305719, 257379
Coordinate System is:
PROJCRS["WGS 84 / Pseudo-Mercator",
    BASEGEOGCRS["WGS 84",
    ...
```
