### ISSUE TITLE
Csharp cmake build broken

### ISSUE THREAD

**Issue by szekerest** [OSGeo/gdal#6871]
Seems like the builds no longer support netstandard 2.0. Supporting netstandard2.0 for the library dll-s is essential to provide the same binaries to work with netcore and netframework clients, like currently for the [GDAL nuget package](https://www.nuget.org/packages/GDAL#supportedframeworks-body-tab)
Before [this commit](https://github.com/OSGeo/gdal/commit/b2248c5d35defbe4bf22ca6871da13e6141ef513), the library could be set by the -DCSHARP_LIBRARY_VERSION=netstandard2.0 cmake flag.

Currently I get the following cmake output with this setting:

```
-- Available SDKS: 5.0;6.0
-- Requested Library DotNet SDK Level: 2.0
-- Requested Application DotNet SDK Level: 6.0
-- The Requested DotNet SDK was not found. C# Bindings will not be built
```

For the earlier build history refer to the [GISInternals logs](https://build2.gisinternals.com/sdk/build-output/vc17x64-dev.html).

**Comment by szekerest** [comment]
cc @runette @rouault

**Comment by rouault** [comment]
@runette Can you hae a look at that ?

**Comment by runette** [comment]
Yep

**Comment by runette** [comment]
Sorry for that. Should be fixed now. Forgot that netstandard will not appear in the SDK list

**Comment by szekerest** [comment]
@runette Thank you
