### ISSUE TITLE
KML/KMZ is always writes to Encoding UTF-8. How to write other encoding format like ISO-8859-1?

### ISSUE THREAD

**Issue by sivaganeshgithub** [OSGeo/gdal#6873]
We have a requirement to write some GIS data in KML and KMZ formats. When we export the data having diacritics from French Locale machine, it writes the data correctly, but still Encoding is UTF-8. 

Is there any plan to support changing the encoding from GDAL library?

## Expected behavior and actual behavior.

For example (please modify !!!): I expected to be able to open this raster file (with a link to
the raster file, or it as an attachment) and it returns an error message
instead.

## Steps to reproduce the problem.

For example (please modify !!!): "gdalinfo myfile"

## Operating system

For example (please modify !!!): Ubuntu 16.04 64 bit

## GDAL version and provenance

For example (please modify !!!): the 2.2.3 version from ubuntugis-unstable PPA

**Comment by rouault** [comment]
If using GDAL API, you need to make sure that the strings you pass to it are UTF-8 encoded. If you convert from an input datasource, GDAL will try to convert to UTF-8, but for some formats, there are no encoding indications (or they are wrong) in the input format. You may need to use for example the iconv utility to fix that.
