### ISSUE TITLE
[Python] ReprojectImage function seems to ignore geotiff internal mask

### ISSUE THREAD

**Issue by domlysz** [OSGeo/gdal#689]
[test.tif.zip](https://github.com/OSGeo/gdal/files/2109038/test.tif.zip)

Please find in attachment a test file (geotiff with internal mask building from a png file with gdal_translate). The following python snippet correctly reproject it, but the resulting internal mask is not  filled as expected (all zero). Not sure if I just missing something.

```python
from osgeo import osr, gdal

gdal.SetConfigOption('GDAL_TIFF_INTERNAL_MASK', 'YES')

#gdal_translate --config GDAL_TIFF_INTERNAL_MASK YES -b 1 -b 2 -b 3 -mask 4 -of GTiff test.png test.tif
ds1 = gdal.Open('./test.tif')

outPath = './out_test.tif'
geoTiffOptions={'TFW':'YES', 'TILED':'YES', 'BIGTIFF':'YES', 'COMPRESS':'JPEG', 'JPEG_QUALITY':80, 'PHOTOMETRIC':'YCBCR'}
options = [str(k) + '=' + str(v) for k, v in geoTiffOptions.items()]

ds2 = gdal.GetDriverByName('GTiff').Create(outPath, 1000, 1000, 3, gdal.GetDataTypeByName('byte'), options)
ds2.CreateMaskBand(gdal.GMF_PER_DATASET)
#ds2.GetRasterBand(1).GetMaskBand().Fill(255)

geoTrans = (254726, 10, 0, 909097, 0, -10) #xmin, resx, rotx, ymax, roty, resy
ds2.SetGeoTransform(geoTrans)

prj1 = osr.SpatialReference()
prj1.ImportFromEPSG(3857)
wkt1 = prj1.ExportToWkt()
ds1.SetProjection(wkt1)

prj2 = osr.SpatialReference()
prj2.ImportFromEPSG(2154)
wkt2 = prj2.ExportToWkt()
ds2.SetProjection(wkt2)

gdal.ReprojectImage(ds1, ds2, wkt1, wkt2, gdal.GRA_Cubic)
```

GDAL 2.2.2 on Linux Mint 17 64bits from ubuntugis PPA with python 3.5.1

**Comment by rouault** [comment]
Generating warped mask band is not supported. Create a destination alpha band instead, and this will work. You'll then have to translate it to RGB + mask if you want to use JPEG YCbCr compression (with gdal.Translate() )

**Comment by TsybusovDmitriy** [comment]
@rouault , @domlysz,  I ran into the same problem. Could you please explain how to 

> Create a destination alpha band instead.

Would be glad to examples.

**Comment by TsybusovDmitriy** [comment]
I ran into the same problem. Could you please explain how to 

> Create a destination alpha band instead.

Would be glad to examples.
