### ISSUE TITLE
ogr2ogr not recognize file if has ".txt" in path, source data CSV

### ISSUE THREAD

**Issue by krzysztof-adamski** [OSGeo/gdal#6902]
`ogr2ogr -f "GPKG" -fieldTypeToString All OUTPUT.gpkg 20221025a.txt`

`
FAILURE:
Unable to open datasource `20221025a.txt' with the following drivers.
  -> `FITS'
  -> `PCIDSK'
  -> `netCDF'
  -> `PDS4'
  -> `VICAR'
  -> `JP2OpenJPEG'
  -> `PDF'
  -> `MBTiles'
  -> `BAG'
....
`

but if we change suffix to .csv, all is fine.

**Comment by jratike80** [comment]
Documented in https://gdal.org/drivers/vector/csv.html
`For files structured as CSV, but not ending with .CSV extension, the ‘CSV:’ prefix can be added before the filename to force loading by the CSV driver.`
Thus this should work:

`ogr2ogr -f "GPKG" -fieldTypeToString All OUTPUT.gpkg CSV:20221025a.txt`

**Comment by krzysztof-adamski** [comment]
@jratike80 All is fine, work well. But .. :) in my case not.

I working in QGIS and try use process gdal:convertformat, and there cannot set corectly CSV:

`        export_parapeters = {
            "INPUT": layer_path,
            "OPTIONS": '-nlt POINT -lco FID=fid -lco GEOMETRY_NAME=geometry -t_srs EPSG:4326 -a_srs EPSG:4326 -oo KEEP_GEOM_COLUMNS=YES -fieldTypeToString All ',
            'OUTPUT': "TEMPORARY_OUTPUT"
        }
        `
        `        dialog = processing.createAlgorithmDialog("gdal:convertformat", export_parapeters)
        dialog.show()
        `
