### ISSUE TITLE
Python bindings - Add GeoTIFF internal overlay (gdaladdo)

### ISSUE THREAD

**Issue by FredFunk** [OSGeo/gdal#6908]
I can't seem to locate the gdaladdo function (or equivalent) for creating internal GeoTIFF overview images in the python bindings. I imagine I could leverage -of COG as a workaround but want to confirm I'm simply not missing something.

**Comment by rouault** [comment]
cf https://gdal.org/api/python/osgeo.gdal.html#osgeo.gdal.Dataset.BuildOverviews
