### ISSUE TITLE
wrong y-resolution sign in netCDF driver

### ISSUE THREAD

**Issue by rhijmans** [OSGeo/gdal#6909]
It seems to me that the attached file does not have the correct geotransform for the y resolution. 

[testf.zip](https://github.com/OSGeo/gdal/files/10215481/testf.zip)

GDALinfo gives 

```
Origin = (-150.400001525878906,-16.850000381469727)
Pixel Size = (0.050003051757813, -0.049999237060547)
``` 

But the y resolution should have a positive sign in this case. I believe that here:

https://github.com/OSGeo/gdal/blob/e8b253032fbf2c6b1e2db2a8742c07cbd158bc87/frmts/netcdf/netcdfdataset.cpp#L4610-L4623

line 4614 should be changed to
```
adfTempGeoTransform[5] = (yMinMax[0] - yMinMax[1]) /
```

This is how the file was created with R

```
url <- "https://pae-paha.pacioos.hawaii.edu/erddap/griddap/dhw_5km.nc?CRW_HOTSPOT[(2018-11-02)][(-16.925):1:(-16.875)][(-150.375):1:(-150.325)]"
download.file(url, "testf.nc", mode="wb")
```

The values can be checked here: 

```
https://pae-paha.pacioos.hawaii.edu/erddap/griddap/dhw_5km.htmlTable?CRW_HOTSPOT[(2018-11-02)][(-16.925):1:(-16.875)][(-150.375):1:(-150.325)]
```

I get the correct results when using the "raster" package (that does not use GDAL to read netCDF)

```
library(raster)
r <- raster("testf.nc")
as.matrix(r)
#      [,1]  [,2]
#[1,] -1.51 -1.53
#[2,] -1.54 -1.55

as.data.frame(r, xy=TRUE)
#         x       y coral.bleaching.hotspot
#1 -150.375 -16.875                   -1.51
#2 -150.325 -16.875                   -1.53
#3 -150.375 -16.925                   -1.54
#4 -150.325 -16.925                   -1.55
```

But I get incorrect results with "terra", that uses GDAL, because of the incorrect sign.

```
library(terra)
x <- rast("testf.nc") 
as.matrix(x, wide=TRUE)
#      [,1]  [,2]
#[1,] -1.54 -1.55
#[2,] -1.51 -1.53

as.data.frame(x, xy=TRUE)
#         x       y CRW_HOTSPOT
#1 -150.375 -16.875       -1.54
#2 -150.325 -16.875       -1.55
#3 -150.375 -16.925       -1.51
#4 -150.325 -16.925       -1.53
 
terra:::.geotransform("testf.nc")
#[1] -150.40000153    0.05000305    0.00000000  -16.85000038    0.00000000   -0.04999924
```

**Comment by jratike80** [comment]
The NetCDF driver is working right for the cases in the autotests in https://github.com/OSGeo/gdal/tree/master/autotest/gdrivers. The corresponding test files are in the directory https://github.com/OSGeo/gdal/tree/master/autotest/gdrivers/data.

I suppose that the fix that you suggested could make every test case that works correctly now to fail in the future.  The right thing to do is probably to find out what is special with the data that you are using and why the driver does not detect the dimensions right with that data.

Meanwhile you can test if the raster package and GDAL agree on the interpretation of the .nc files in the test data directory.

**Comment by mdsumner** [comment]
fwiw you can pivot with 

```R
Sys.setenv(GDAL_NETCDF_BOTTOMUP = "NO")
```

I tried a much larger window to check (the latitude values run from north to south).

**Comment by rhijmans** [comment]
@jratike80: Thanks for the suggestion. I did not find discrepancies in the test cases, It looks like they all report a negative y dimension in the geotransform, even when thye arguably the should not. I suppose that means that the y order is dealt with somewhere else. 

@mdsumner: 
Thanks, with R/terra you can use `setGDALconfig("GDAL_NETCDF_BOTTOMUP", "NO")` to get the correct values.

**Comment by jratike80** [comment]
Somebody else can certainly  explain what this part of the documentation in https://gdal.org/drivers/raster/netcdf.html means.

> WRITE_BOTTOMUP=[YES/NO]: Set the y-axis order for export, overriding the order detected by the driver. NetCDF files are usually assumed “bottom-up”, contrary to GDAL’s model which is “north up”. This normally does not create a problem in the y-axis order, unless there is no y axis geo-referencing. The default for this setting is YES, so files will be exported in the NetCDF default “bottom-up” order. For import see Configuration Option GDAL_NETCDF_BOTTOMUP below.

What is normal to GDAL is that the origin is placed at the top-left corner and when reading new lines of data the y value is degreasing and thus the y-size of the pixel is negative. If I understand the documentation right it is more common in NetCDF that data are written beginning from the bottom left corner and thus the y-size of the pixel is positive. I do not know if it means that GDAL is automatically flipping NetCDF data around the latitude of the first line and if the NetCDF file is of the less common sort so that the latitude dimension is advancing from north to south then this flipping must be prevented with "GDAL_NETCDF_BOTTOMUP NO".

**Comment by rouault** [comment]
Bug confirmed. Fix in https://github.com/OSGeo/gdal/pull/6918

**Comment by rouault** [comment]
The geotransform is actually correct, but the data was not returned in the appropriate order
