### ISSUE TITLE
`RasterizeLayer` not working with a `WHERE` clause with "Generic SQL" layer

### ISSUE THREAD

**Issue by camden-lowrance** [OSGeo/gdal#6925]
## Expected behavior and actual behavior.

I am expecting a raster to be generated with valid pixels.  I am observing that including a `WHERE` clause in an `ExecuteSQL` call on a parquet file produces no valid pixels.  Excluding the clause produces pixels as expected.  I created the parquet using `geopandas` and have attached a 1000 row sample.

## Steps to reproduce the problem.

Here is a MRE with the python bindings:
```python
from osgeo import gdal

ds = gdal.OpenEx("test.parquet", gdal.OF_VECTOR)
# layer = ds.ExecuteSQL("SELECT * FROM test")  # this works
layer = ds.ExecuteSQL("SELECT * FROM test WHERE speed > 0")  # this fails
assert layer is not None and layer.GetFeatureCount() > 0

PIXEL_SIZE = 1
xmin, xmax, ymin, ymax = layer.GetExtent()
xsize = int((xmax - xmin) / PIXEL_SIZE)
ysize = int((ymax - ymin) / PIXEL_SIZE)

dst = gdal.GetDriverByName("GTiff").Create(
    "test.tif",
    xsize=xsize,
    ysize=ysize,
    bands=1,
    eType=gdal.GDT_Float64,
)
dst.SetGeoTransform((xmin, PIXEL_SIZE, 0, ymax, 0, -PIXEL_SIZE))
dst.SetProjection(layer.GetSpatialRef().ExportToWkt())

band = dst.GetRasterBand(1)
NO_DATA_VALUE = -9999
band.Fill(NO_DATA_VALUE)
band.SetNoDataValue(NO_DATA_VALUE)

gdal.RasterizeLayer(dst, [1], layer, options=["ATTRIBUTE=speed"])
```

Here is a snippet of the `gdalinfo` for the working ex:
```
Band 1 Block=19x20 Type=Float64, ColorInterp=Gray
  Min=3.300 Max=6.400 
  Minimum=3.300, Maximum=6.400, Mean=4.684, StdDev=0.786
  NoData Value=-9999
  Metadata:
    STATISTICS_MAXIMUM=6.4
    STATISTICS_MEAN=4.684142394822
    STATISTICS_MINIMUM=3.3
    STATISTICS_STDDEV=0.78557442494949
    STATISTICS_VALID_PERCENT=81.32
```

And for the failing:
```
Band 1 Block=19x20 Type=Float64, ColorInterp=Gray
ERROR 1: test.tif, band 1: Failed to compute statistics, no valid pixels found in sampling.
  NoData Value=-9999
  Metadata:
    STATISTICS_VALID_PERCENT=0
```

## Operating system

macOS Ventura 13.0.1

## GDAL version and provenance

3.6.0 via conda-forge, build py310h5abc6fc_14

### Supporting files
[test.parquet.zip](https://github.com/OSGeo/gdal/files/10233587/test.parquet.zip)
here is a snippet of the above file:
```
	speed	geometry
0	3.6	POLYGON ((464495.581 4092362.668, 464495.463 4...
1	3.6	POLYGON ((464495.463 4092361.917, 464495.345 4...
2	3.8	POLYGON ((464495.865 4092362.625, 464495.754 4...
3	3.8	POLYGON ((464495.754 4092361.874, 464495.644 4...
4	3.8	POLYGON ((464495.644 4092361.122, 464495.533 4...
```

**Comment by jratike80** [comment]
Does gdal_rasterize work for you?

```
gdal_rasterize  test.parquet -sql "SELECT * FROM test WHERE speed > 0" parquet.tif -burn 200 -ts 200 200
0...10...20...30...40...50...60...70...80...90...100 - done.
```

<img width="93" alt="image" src="https://user-images.githubusercontent.com/1751612/207796928-b8a42a6d-6894-4ec3-b59d-6323a30a7a71.png">

**Comment by camden-lowrance** [comment]
> Does gdal_rasterize work for you?

Yes, that would be a temporary workaround.  I believe `gdal_rasterize` doesn't use `RasterizeLayer` and uses `Rasterize` directly, which might account for the difference.

**Comment by rouault** [comment]
fix in https://github.com/OSGeo/gdal/pull/6929
Workaround: use the SQLite dialect instead of the default OGRSQL one:
```
layer = ds.ExecuteSQL("SELECT * FROM test WHERE speed > 0", dialect = "SQLite")
```
