### ISSUE TITLE
 Failed to get WEBP driver 

### ISSUE THREAD

**Issue by lihuaxiaoyang** [OSGeo/gdal#6931]
## Expected behavior and actual behavior.
 I try to get the WEBP driver in java (gdal.GetDriverByName("WEBP")), its returned result is null ,but i can get WEBP driver with Python (gdal.GetDriverByName("WEBP")). 

## Operating system

Windows 10 professional

## GDAL version and provenance

python:python39     gdal 3.4.3
java: java8     gdal  3.4.0

**Comment by lihuaxiaoyang** [comment]
There are 9 fewer drivers in the Java package than in the Python package...

**Comment by rouault** [comment]
It is a packaging issue, not an upstream one
