### ISSUE TITLE
Dockerfile update from proj-datumgrid to PROJ-data

### ISSUE THREAD

**Issue by webmap2015** [OSGeo/gdal#6936]
## Expected behavior and actual behavior.

Hi,

While building the docker image. it's downloading proj-datumgrid.

![1](https://user-images.githubusercontent.com/10267317/208241575-6fc872b1-3c5a-4ba5-aac0-52995ca3fa52.PNG)

When using PROJ 7 or later, should PROJ-data be used?

![2](https://user-images.githubusercontent.com/10267317/208241579-d0c0629c-0f7a-46ec-926b-76c9a91ed08e.PNG)

Thanks.

## Operating system
Ubuntu 22.04 64 bit (docker image)

## GDAL version and provenance
the master (3.7.0dev) version.

**Comment by rouault** [comment]
PROJ-data is recommended for higher accuracy needs and if you have enough storage. proj-datumgrid is still used for the smaller Docker images (all but ubunfu-full) because otherwise the image size would be much bigger

**Comment by webmap2015** [comment]
Thanks.
