### ISSUE TITLE
Several problems with WFS driver for importing layers (with docker images, not tested with simpler versions)

### ISSUE THREAD

**Issue by rbonnefoi** [OSGeo/gdal#6940]
Hi all,

Any help will be appreciated for resolving the 3 following problems, which I think are bugs of the WFS driver. I took several hours to try to understand and define the precise context of the problems.

Anyway, GDAL brings great tools.

## Expected behavior and actual behavior.

I use ogr2ogr (from official docker image) to import a layer from a (too slow) WFS server, and I encountered three main problems : 

1. using the default GML32 outputformat, the layer is seen empty. I have to force an `&outputFormat=json` to get any result.

2. the latter solution only works if I use the `alpine-normal` docker version, not the `ubuntu-full`, for which the layer is also empty 

3. the WFS driver doesn't seem to respect the Geoserver standard on coordinates order (cf. [https://docs.geoserver.org/latest/en/user/services/wfs/axis_order.html]) and the subtile difference between the way of naming spatial reference systems (EPSG:xxxx vs urn:ogc:def:crs:EPSG::xxxx)

## Steps to reproduce the problem.
Before, a header file is needed to be able to connect to the WFS server
`echo "User-Agent: \"Mozilla/5.0\"" > wfs_header.conf`

For testing, as the whole layer contains millions of features, the number of returned features is limited to 10 using the config option
`--config OGR_WFS_PAGING_ALLOWED OFF` and adding parameter `&count=10` to the WFS address

### For point 1
Without any outputFormat specified (i.e. using the default gml32 one), the returned layer is empty:
`docker run -i --rm -v $PWD:/ftp osgeo/gdal:alpine-normal-latest ogr2ogr --config GDAL_HTTP_HEADER_FILE /ftp/wfs_header.conf --config OGR_WFS_PAGING_ALLOWED OFF -f Geojson /ftp/test.geojson WFS:"https://wxs-gpu.mongeoportail.ign.fr/externe/39wtxmgtn23okfbbs1al2lz3/wfs?service=WFS&request=GetFeature&srsName=EPSG:4326&count=10" wfs_du:prescription_surf`

With an `&outputFormat=json` added to the WFS address, the result is as expected: 
`docker run -i --rm -v $PWD:/ftp osgeo/gdal:alpine-normal-latest ogr2ogr --config GDAL_HTTP_HEADER_FILE /ftp/wfs_header.conf --config OGR_WFS_PAGING_ALLOWED OFF -f Geojson /ftp/test.geojson WFS:"https://wxs-gpu.mongeoportail.ign.fr/externe/39wtxmgtn23okfbbs1al2lz3/wfs?service=WFS&request=GetFeature&srsName=EPSG:4326&count=10&outputFormat=json" wfs_du:prescription_surf`

You'll find attached both outputs with the `--debug on` option.

I precise that when the WFS is requested through a web client, with the default gml32 output format (i.e. without any mention of `&outputFormat=json`), it returns the required features:
[https://wxs-gpu.mongeoportail.ign.fr/externe/39wtxmgtn23okfbbs1al2lz3/wfs?SERVICE=WFS&REQUEST=GetFeature&srsName=EPSG:4326&count=10&TYPENAMES=wfs_du:prescription_surf](url)

It makes me think that the problem comes from the WFS driver.

### For point 2
Executing the following command returns nothing at all (even not an empty layer):
`docker run -i --rm -v $PWD:/ftp osgeo/gdal ogrinfo --config GDAL_HTTP_HEADER_FILE /ftp/wfs_header.conf WFS:"https://wxs-gpu.mongeoportail.ign.fr/externe/39wtxmgtn23okfbbs1al2lz3/wfs?service=WFS&typeNames=wfs_du:prescription_surf"`

while adding an alpine-normal-latest version returns the requested features: 
`docker run -i --rm -v $PWD:/ftp osgeo/gdal:alpine-normal-latest ogrinfo --config GDAL_HTTP_HEADER_FILE /ftp/wfs_header.conf WFS:"https://wxs-gpu.mongeoportail.ign.fr/externe/39wtxmgtn23okfbbs1al2lz3/wfs?service=WFS&typeNames=wfs_du:prescription_surf"`

The problem is the same using ogr2ogr, that's why I think it also comes from the WFS driver and not any vector program of gdal. The `--debug on` option doesn't give any information in the first case.

### For point 3
When the `&srsName=EPSG:4326` is removed from the WFS address, lontitude and latitude are switched:
`docker run -i --rm -v $PWD:/ftp osgeo/gdal:alpine-normal-latest ogr2ogr --config GDAL_HTTP_HEADER_FILE /ftp/wfs_header.conf --config OGR_WFS_PAGING_ALLOWED OFF -f Geojson /ftp/test.geojson WFS:"https://wxs-gpu.mongeoportail.ign.fr/externe/39wtxmgtn23okfbbs1al2lz3/wfs?service=WFS&request=GetFeature&count=10&outputFormat=json" wfs_du:prescription_surf`

as it uses the default `urn:ogc:def:crs:EPSG::4326` reference system, which uses latitude/longitude axis order, while the previously specified `EPSG:4326` uses a longitude/latitude axis order. 

Whenever the result is loaded into a GeoJSON file or a Postgis geometry database, the coordinates are in the wrong order in the first case, in the right order in the latter.

I think the WFS driver should be able to determine how to deal with axis order. 

## Operating system
NAS Asustor (linux kernel 5.13)

## GDAL version and provenance
docker osgeo/gdal images (latest and alpine-normal-latest)

Many thanks.

[debug_output_jsonl.txt](https://github.com/OSGeo/gdal/files/10252190/debug_output_jsonl.txt)
[debug_output_gml.txt](https://github.com/OSGeo/gdal/files/10252191/debug_output_gml.txt)

**Comment by rouault** [comment]
- Your point 1, issue with GML32, output is adressed per https://github.com/OSGeo/gdal/pull/6941
- Not sure about your point 2, but point 1 should hopefully fix it
- Regarding your point 3, axis order in WFS with non-GML output is a mess I won't attempt to address. Cf https://osgeo-org.atlassian.net/jira/software/c/projects/GEOS/issues/GEOS-3657, https://osgeo-org.atlassian.net/browse/GEOS-2397#icft=GEOS-2397 and https://github.com/OSGeo/gdal/blob/a632e3093d6dd34cdcf979a5b2a20529fe2df943/ogr/ogrsf_frmts/wfs/ogrwfslayer.cpp#L1375

**Comment by rbonnefoi** [comment]
@rouault Many thanks for your fast answer and action. I look forward for the next gdal update.

I take note of your answer about axis order. Sorry for my remark, I should have better read the driver help page.
