### ISSUE TITLE
AAIGrid flips image when writing from south-up oriented raster

### ISSUE THREAD

**Issue by snowman2** [OSGeo/gdal#6946]
## Expected behavior and actual behavior.

See: https://github.com/corteva/rioxarray/issues/586

The image is flipped when reading the ascii file for some reason.

## Steps to reproduce the problem.

[test_tiff.zip](https://github.com/OSGeo/gdal/files/10262788/test_tiff.zip)
```
gdal_translate -of AAIGrid test_tiff.tiff test_tiff.asc
```

## Operating system

Ubuntu 22.04

## GDAL version and provenance

3.5.3 from conda-forge

**Comment by jratike80** [comment]
The TIFF file is south-up (pixels with positive y-size), maybe that has some effect.
`Pixel Size = (0.009999999142735,0.009999999999998)`.

**Comment by snowman2** [comment]
Thanks @jratike80  @rouault :+1:
