### ISSUE TITLE
Upgrade GDAL Docker Image to Java 17

### ISSUE THREAD

**Issue by raynigon** [OSGeo/gdal#6949]
## Expected behavior and actual behavior.

The current ubuntu-full docker image ships with Java 11.
The new Version of the ubuntu-full docker image should ship with Java 17

**Comment by jratike80** [comment]
Do you know if the bindings work with Java 17?

**Comment by raynigon** [comment]
I tried it locally with docker, but it did not work on first try. I need to look into it a bit deeper to find the cause. It could be, that it was just a problem with my setup.

**Comment by adamgutons** [comment]
I have been trying to build GDAL bindings for Java 17 outside of Docker and am not having luck.  All of the proper files are created (gdal.jar,  libgdalalljni.dylib, etc.).  It would be great to know if anyone has successfully built the bindings for 17.   I have been able to build the exact same way but using JDK 8.  The only difference now is the switch to 17.

```
Native library load failed.
java.lang.UnsatisfiedLinkError: no gdalalljni in java.library.path: ...
Exception in thread "main" java.lang.UnsatisfiedLinkError: 'void org.gdal.gdal.gdalJNI.AllRegister()'
at org.gdal.gdal.gdalJNI.AllRegister(Native Method)
at org.gdal.gdal.gdal.AllRegister(gdal.java:664)
at Main.main(Main.java:14)
```

My system specs:
 
      System Version: macOS 12.6.1 (21G217)
      Kernel Version: Darwin 21.6.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 15 days 20:17
      Model Name: MacBook Pro
      Model Identifier: MacBookPro18,3
      Chip: Apple M1 Pro

When I run the build I see that the Java bindings are generated, the .jar and libgdalalljni.dylib are created in /build/swig/java.  Here are the build commands used:

```
sudo arch -x86_64 /usr/local/homebrew/bin/cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local/bin -DBUILD_JAVA_BINDINGS=ON -DBUILD_PYTHON_BINDINGS=OFF -DCMAKE_OSX_ARCHITECTURES=x86_64 -DGDAL_USE_ZSTD=OFF
sudo arch -x86_64 /usr/local/homebrew/bin/cmake --build .
sudo arch -x86_64 /usr/local/homebrew/bin/cmake --build . --target install
```



VM options: -Djava.library.path=/Users/<username>/code/gdal-<version>/build/swig/java:$PATH$
Environment Vars: PATH=/Users/<username>/code/gdal-<version>:/Users/<username>/code/gdal-<version>/build/swig/java:$PATH$

**Comment by jratike80** [comment]
Thank you for reporting. I forwarded your success story to Geoserver developers. I am not sure if it is important for them but Geoserver is dropping support for Java 8 and imageio-ext is using GDAL bindings https://docs.geoserver.org/stable/en/user/data/raster/gdal.html.

**Comment by jodygarnett** [comment]
I would like to try this myself; and perhaps add example to geoserver user guide?
