### ISSUE TITLE
[CMAKE] when using TIFF_External, nitfdump project is missing the libTIFF dependency and won't compile

### ISSUE THREAD

**Issue by chacha21** [OSGeo/gdal#6968]
Windows 7 64 b
Visual Studio 2019 (latest)
CMake 3.25.1

I have configured GDAL to use external TIFF and GeoTiff
the gdal library builds OK, but nitfdump won't build:
- it requires tiffio.h but the libtiff is not in the INCLUDES of the nitfdump.vcxproj
- adding the missing INCLUDES will compile, but link will fail because libtiff is neither in the dependent libraries of the nitfdump.vcxproj
- adding the missing libtiff dependency will ultimately work

**Comment by rouault** [comment]
@chacha21 does https://github.com/OSGeo/gdal/pull/6969 fix your issue ?

**Comment by rouault** [comment]
> So I always have to add includes to that build directory

well, tiffconf.h is installed in the same directory as other TIFF header files, if you install libtiff. I don't think we want to support linking an external libtiff that is not installed, but just as a build artifact.

**Comment by chacha21** [comment]
I don't "install libtiff" I build it from source with CMake, that's why I have a separate build folder.
