### ISSUE TITLE
Missing TOWGS84 node when upgrading from 3.1.3 to 3.4.3.

### ISSUE THREAD

**Issue by aymesp** [OSGeo/gdal#6972]
When upgrading from 3.1.3 to 3.4.3, we noticed that when exporting an OGRSpatialReference from one of our file to wkt, the newer versions seems to be missing a TOWGS84 node.

Initially, calling exportToWkt() results in this:

PROJCS["unnamed",GEOGCS["Belge 1972",DATUM["Reseau_National_Belge_1972",SPHEROID["International 1924",6378388,297.000000000005,AUTHORITY["EPSG","7022"]],AUTHORITY["EPSG","6313"]],PRIMEM["Greenwich",0],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4313"]],PROJECTION["Lambert_Conformal_Conic_2SP"],PARAMETER["latitude_of_origin",90],PARAMETER["central_meridian",4.36748666666667],PARAMETER["standard_parallel_1",49.8333339],PARAMETER["standard_parallel_2",51.1666672333333],PARAMETER["false_easting",150000.01256],PARAMETER["false_northing",5400088.4378],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AXIS["Easting",EAST],AXIS["Northing",NORTH]]

In 3.1.3, after calling AddGuessedTOWGS84(), it would become this:

PROJCS["unnamed",GEOGCS["Belge 1972",DATUM["Reseau_National_Belge_1972",SPHEROID["International 1924",6378388,297.000000000005,AUTHORITY["EPSG","7022"]],TOWGS84[-99.059,53.322,-112.486,0.419,-0.83,1.885,-1],AUTHORITY["EPSG","6313"]],PRIMEM["Greenwich",0],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4313"]],PROJECTION["Lambert_Conformal_Conic_2SP"],PARAMETER["latitude_of_origin",90],PARAMETER["central_meridian",4.36748666666667],PARAMETER["standard_parallel_1",49.8333339],PARAMETER["standard_parallel_2",51.1666672333333],PARAMETER["false_easting",150000.01256],PARAMETER["false_northing",5400088.4378],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AXIS["Easting",EAST],AXIS["Northing",NORTH]]

But in 3.4.3, even if AddGuessedTOWGS84() reports no error, the result is identical to what it was before the call. Could it be a regression? Or was the behavior changed on purpose and we're missing some configuration option?

## Operating system

Windows and Linux

## GDAL version and provenance

3.4.4

**Comment by rouault** [comment]
I suspect this is due to an update of the PROJ version too. In EPSG, there are 3 different Helmert transformations from Belge 1972 to WGS 84, and thus PROJ can't know which ones should be used.
TOWGS84[] is now a deprecated feature that is less useful with PROJ >= 6
