### ISSUE TITLE
Building PROJ process of ubuntu-full docker

### ISSUE THREAD

**Issue by webmap2015** [OSGeo/gdal#6978]
## Expected behavior and actual behavior.

Hi,

While building the docker image, the PROJ is building twice.

In the line:245 and line:252.

![proj](https://user-images.githubusercontent.com/10267317/209663288-6d5b7720-dbd5-4d55-aff1-a1709db9cc4c.PNG)

Should line 252 be removed?

Thanks.

## Operating system

Ubuntu 22.04 64 bit (docker image)

## GDAL version and provenance

the master (3.7.0dev) version.

**Comment by rouault** [comment]
This is intentional. Cf comment added in 4488c24f1e177e8129e4892faa7c16c5356cc576
