### ISSUE TITLE
GML:  In parsing CityGML, should dimension be handled in 3D as default?

### ISSUE THREAD

**Issue by Kanahiro** [OSGeo/gdal#6989]
related: https://github.com/OSGeo/gdal/issues/6986

6.2.3.  Relationships between CityGML objects https://docs.ogc.org/is/20-010/20-010.html#toc23
> With only a few exceptions, all geometries must use 3D coordinate values.

For me this could be read as CityGML coordinates are in 3D except for few cases but ogr parses GML in 2D as default. You can change this behavior by setting environment variable `GML_SRS_DIMENSION_IF_MISSING`  but in parsing CityGML, should dimension be treated in 3D as default? What do you think?

sampledata: [533946_urf_6668_yoto_op.gml.zip](https://github.com/OSGeo/gdal/files/10314925/533946_urf_6668_yoto_op.gml.zip) from https://www.geospatial.jp/ckan/dataset/plateau-tokyo23ku, CC-BY 4.0

**Comment by Kanahiro** [comment]
A default dimension seems to be set in this line: https://github.com/OSGeo/gdal/blob/master/ogr/ogrsf_frmts/gml/gmlhandler.cpp#L779

**Comment by jratike80** [comment]
I think that if something in CityGML could well be 2d then LOD0 footprints might be. But in the LOD0 example file at https://schemas.opengis.net/citygml/examples/2.0/building/ there is another flat geometry for the roof above the footprint and height coordinate is also meaningful. So probably 3-dimension is a good default for CityGML. But the GML driver is a generic driver, would 3 dimensionality be good default for all kind of GML? Or is there already some check somewhere in the code like "isCityGML=true"?

**Comment by Kanahiro** [comment]
Thank you for comment. I think you are right it is better 3d as default only to CityGML.

I'm not sure codebases but `APPSCHEMA_CITYGML` in enum `GMLAppSchemaType` can be a flag whether GML is CityGML.
https://github.com/OSGeo/gdal/blob/master/ogr/ogrsf_frmts/gml/gmlhandler.cpp#L1372

**Comment by Kanahiro** [comment]
I changed my codes to apply above discussion.
https://github.com/OSGeo/gdal/pull/6990
