### ISSUE TITLE
I can't successfully build this project, can you help me check my build steps?

### ISSUE THREAD

**Issue by WickWeiWkSpace** [OSGeo/gdal#6993]
Hello,

Sorry to bother you with this kind of problem, when I build this project, I always get an error in cmake, but I don't know where the problem is, can you help me? Thanks in advance.

**My build step：**
1. git clone https://github.com/OSGeo/gdal.git F:\gitP\OSGeo\gdal
2. cinst -y --no-progress swig
3. pip install numpy
4. cd F:\gitP\Microsoft\vcpkg
5. bootstrap-vcpkg.bat 2>&1
6. vcpkg.exe install --recurse sqlite3 --triplet x86-windows --clean-after-build 2>&1
7. cd F:\gitP\OSGeo\gdal\build
8. curl https://sqlite.org/2018/sqlite-tools-win32-x86-3250100.zip -O -L 2>&1
9. set PATH=F:\tools\7-Zip;%PATH%
10. 7z x F:\gitP\OSGeo\gdal\build\sqlite-tools-win32-x86-3250100.zip -oF:\gitP\OSGeo\gdal\build -aoa 2>&1
11. cmake -G "Visual Studio 16 2019" -A Win32 -DCMAKE_SYSTEM_VERSION=10.0.18362.0 -DPROJ_TESTS=OFF -DCMAKE_BUILD_TYPE=Release /DGDAL_USE_EXTERNAL_LIBS=OFF -DBUILD_LIBPROJ_SHARED=ON -DCMAKE_TOOLCHAIN_FILE=F:\gitP\Microsoft\vcpkg\scripts\buildsystems\vcpkg.cmake -DBUILD_SHARED_LIBS=ON -DENABLE_CURL=OFF -DENABLE_TIFF=OFF -DBUILD_PROJSYNC=OFF .. 2>&1

**Error msg:**
-- GDAL_VERSION          = 3.7.0dev
-- GDAL_ABI_FULL_VERSION = 37
-- GDAL_SOVERSION        = 
-- Found ODBC: odbc32.lib   
-- Could NOT find ODBCCPP (missing: ODBCCPP_LIBRARY ODBCCPP_INCLUDE_DIR) 
-- Could NOT find MSSQL_NCLI (missing: MSSQL_NCLI_LIBRARY MSSQL_NCLI_INCLUDE_DIR MSSQL_NCLI_VERSION) 
-- Found MSSQL_ODBC: C:/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/SDK/Lib/x86/msodbcsql17.lib (found version "17") 
-- Could NOT find MySQL (missing: MYSQL_LIBRARY MYSQL_INCLUDE_DIR) 
-- Could NOT find CURL (missing: CURL_LIBRARY CURL_INCLUDE_DIR) 
-- Could NOT find Iconv (missing: Iconv_LIBRARY Iconv_CHARSET_LIBRARY) 
-- Could NOT find LibXml2 (missing: LIBXML2_LIBRARY) (found version "2.9.9")
-- Could NOT find EXPAT (missing: EXPAT_DIR)
-- Could NOT find EXPAT (missing: EXPAT_LIBRARY) (found version "2.2.6")
-- Failed to find XercesC (missing: XercesC_LIBRARY XercesC_INCLUDE_DIR XercesC_VERSION) 
-- Could NOT find ZLIB (missing: ZLIB_LIBRARY) (found version "1.2.11")
-- Could NOT find Deflate (missing: Deflate_LIBRARY Deflate_INCLUDE_DIR) 
-- Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY SSL Crypto) (found version "1.1.1i")
-- Could NOT find CryptoPP (missing: CRYPTOPP_LIBRARY CRYPTOPP_TEST_KNOWNBUG CRYPTOPP_INCLUDE_DIR) 
-- Configuring incomplete, errors occurred!

CMake Error at C:/Program Files/CMake/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find PROJ (missing: PROJ_LIBRARY PROJ_INCLUDE_DIR) (Required is
  at least version "6.0")
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/packages/FindPROJ.cmake:57 (find_package_handle_standard_args)
  F:/gitP/microsoft/vcpkg/scripts/buildsystems/vcpkg.cmake:829 (_find_package)
  cmake/helpers/CheckDependentLibraries.cmake:355 (find_package)
  gdal.cmake:265 (include)
  CMakeLists.txt:224 (include)

**Comment by dg0yt** [comment]
> Could NOT find PROJ (missing: PROJ_LIBRARY PROJ_INCLUDE_DIR) (Required is at least version "6.0")

PROJ is a required dependency of GDAL.
You are using vcpkg classic mode: Explicit manual installation of packages. So you need to extent your vcpkg command line to list not only "sqlite3" but also "proj".
You can look at vcpkg's  ports/gdal/vcpkg.json for more dependencies.

You can also install gdal with vcpkg. And you may even try to build the latest master with `vcpkg install --head gdal`, but this is untested and may fail.

**Comment by jratike80** [comment]
I am closing this issue as a support request.

> IMPORTANT: Do NOT use GitHub to post any questions or support requests!
>            They will be closed immediately and ignored.
> 
> Questions should go to the gdal-dev mailing list at
> https://lists.osgeo.org/mailman/listinfo/gdal-dev
> or other support forums. GitHub issues are for bug
> reports and suggestions for new features.

**Comment by WickWeiWkSpace** [comment]
I'm sorry to bother you, but thank you for your help！

**Comment by jratike80** [comment]
No need to apologize, it is all right to ask questions. Use gdal-dev mailing list if you need more advice.

**Comment by WickWeiWkSpace** [comment]
Ok！Thank you！

**Comment by WickWeiWkSpace** [comment]
Hello, 
I'm sorry to bother you. I met some mistakes when building Gdal. But I don't know how to get help through this link. 
https://lists.osgeo.org/mailman/listinfo/gdal-dev
Can you tell me other ways to ask some questions?

**Comment by jratike80** [comment]
Create an account in the section "Subscribing to gdal-dev" When you have subscribed you can send mail to address [gdal-dev@lists.osgeo.org](mailto:gdal-dev@lists.osgeo.org).
