### ISSUE TITLE
OSRCleanup() -> CleanupSRSWGS84Mutex()  can crash when OGRSpatialReference::GetWGS84SRS() is simultaneously called.

### ISSUE THREAD

**Issue by MaartenHilferink** [OSGeo/gdal#7010]
(using code from vcpkg gdal 3.6.0 on Win32 x64 with Visual Studio 17.4.2)

When one thread calls `GDALOpenEx(...)` -> `OGRSpatialReference::GetWGS84SRS()` while another thread calls `OSRCleanup()`, a race condition may occur on `poSRSWGS84` in `CleanupSRSWGS84Mutex()` as this function is NOT synchronized with `OGRSpatialReference::GetWGS84SRS()` as `hMutex != nullptr` does NOT guarantee that `poSRSWGS84` has been initialized, specifically when `new OGRSpatialReference` hasn't returned yet.

advice: change in ogr/spatialreference.cpp, lines 10993...11002 from

```
static void CleanupSRSWGS84Mutex()
{
    if( hMutex != nullptr )
    {
        poSRSWGS84->Release();
        poSRSWGS84 = nullptr;
        CPLDestroyMutex(hMutex);
        hMutex = nullptr;
    }
}

```
to
```
static void CleanupSRSWGS84Mutex()
{
    CPLMutexHolderD(&hMutex);
    if (poSRSWGS84 != nullptr)
    {
        poSRSWGS84->Release();
        poSRSWGS84 = nullptr;
        CPLDestroyMutex(hMutex);
        hMutex = nullptr;
    }
}

```

**Comment by rouault** [comment]
> When one thread calls `GDALOpenEx(...)` -> `OGRSpatialReference::GetWGS84SRS()` while another thread calls `OSRCleanup()`

The cleanup functions of GDAL/OGR/OSR should only be called from the main thread, at process termination. They are not intended to be thread safe.

**Comment by MaartenHilferink** [comment]
Not calling OSRCleanup() per thread causes memory leaks caused by OSRGetProjTLSContext() as mentioned in https://github.com/OSGeo/gdal/issues/1838 and https://github.com/ObjectVision/GeoDMS/issues/11

Using a `OSRPJContextHolder` or calling `proj_context_create()` and `proj_context_destroy()` directly for each worker thread that might call `OGRLayer::GetSpatialRef()` -> `OSRPJContextHolder()` -> `OSRGetProjTLSContext()` indirectly doesn't prevent this, as it manages a separate copy of a `std::shared_ptr<osgeo::proj::io::DataBaseContext>` aside from the TLS one that `OSRPJContextHolder()` keeps.

**Comment by MaartenHilferink** [comment]
Calling `CPLCleanupTLS()` instead of `OSRCleanup()` did mange to clean-up the leaks from `OSRGetProjTLSContext()` while not causing this issue.
