### ISSUE TITLE
The -preserve_fid flag in shp to postgis export using ogr2ogr

### ISSUE THREAD

**Issue by dispiste** [OSGeo/gdal#7011]
## Expected behavior and actual behavior.

When exporting a shapefile to postgis, the -preserve_fid flag produces the exact opposed behavior compared to the expected one. If the shapefile includes an ogc_fid field and -preserve_fid flag is NOT provided, then the layer is exported and the FIDs in the resulting postgis table match the FIDs of the ogc_fid field of the shapefile (so FIDS are preserved).

However, if the -preserve_fid flag IS provided for the same shapefile, then the resulting postgis table does not match the FIDs of the shapefile. For instance, assuming a shapefile with 3 features having FIDs 1, 2 and 3, they are exported as 0, 1 and 2 to postgis. So FIDs are not preserved.

This happens when creating the table and also when overwriting an existing table.

## Steps to reproduce the problem.

Creation:
`/usr/bin/ogr2ogr -update -preserve_fid -a_srs EPSG:3857 -s_srs EPSG:3857 -f PostgreSQL -lco LAUNDER=YES -lco precision=NO --config SHAPE_ENCODING LATIN1 --config OGR_TRUNCATE NO -nln ds_cmartinez.puntosogr -nlt PROMOTE_TO_MULTI -dim 2 "PG:host='localhost' port='5432' user='theuser' dbname='thedbname' password='thepass'" "puntosogr.shp"`

Overwrite:
`/usr/local/bin/ogr2ogr -update -overwrite -preserve_fid -a_srs EPSG:3857 -s_srs EPSG:3857 -f PostgreSQL -lco LAUNDER=YES -lco precision=NO --config SHAPE_ENCODING LATIN1 --config OGR_TRUNCATE NO -nln ds_cmartinez.puntosogr -nlt PROMOTE_TO_MULTI -dim 2 "PG:host='localhost' port='5432' user='theuser' dbname='thedbname' password='thepass'" "puntosogr.shp"`

## Operating system

Tested in Ubuntu 22.04 and CentOS 7.

## GDAL version and provenance

Tested in GDAL versions 3.4.1+dfsg-1build4 (Ubuntu 22.04), Gdal 2.4.4 and Gdal 1.11.4

**Comment by rouault** [comment]
That's perhaps counter intuitive, but the current behaviour is correct.
The FID column of a shapefile dataset is implicit, and is *not* the ogc_fid column used by default by the PostgreSQL driver. The shapefile driver will enumerate FIDs starting at 0, so when you use -preserve_fid, that's this FID value that is used for the content of the ogc_fid column, not the value of the ogc_fid column from the source.

**Comment by jratike80** [comment]
I believe that this is something that happens by chance. I have understood that shapefile cannot have any other FID than the automatic one that is based in the order of features. In the following the FIDS are 0, 1, and 3. The ogc_fid attribute is just an attribute without any special meaning.


```
Layer name: fidtest
Metadata:
  DBF_DATE_LAST_UPDATE=2023-01-02
Geometry: Point
Feature Count: 3
Extent: (159.000000, 320.000000) - (354.000000, 390.000000)
Layer SRS WKT:
(unknown)
ogc_fid: Integer (6.0)
OGRFeature(fidtest):0
  ogc_fid (Integer) = 1000
  POINT (213 375)

OGRFeature(fidtest):1
  ogc_fid (Integer) = 2000
  POINT (159 390)

OGRFeature(fidtest):2
  ogc_fid (Integer) = 3000
  POINT (354 320)
```

So the `-preserve_fid` option should create fids starting from 0.  That PostGIS captures the fid from ogc_fid is probably because that is the default name of the fid field for PostGIS driver. Make a test by converting data into GeoPackage and you'll see that ogc_fid is not used as a FID but it starts running from 1 by default, and from 0 with -preserve_fid.

**Comment by dispiste** [comment]
Well, it is certainly a confusing behaviour, specially when not using -preserve_fid.

If I understand correctly what you mean, it is the PostGIS driver that uses the content of the source ogc_fid field as primary key instead of generating new values, so it preserves fids by chance. That is a quite surprising behaviour from the Postgres side, but well, at least there is a way to load original fids from SHP to PostGIS.

It would be great if there is an ogr2ogr parameter to specify the name of the FID field to use (for drivers/formats such as Shapefile that don't have a formal way to define a primary key / FID in the format). I believe it is a common use case to have a PK field in the data even if not strictly defined in the format.

**Comment by jratike80** [comment]
I do not know where and if this is documented, but at least this works. Take a shapefile with these attributes
```
attr: String (1.0)
newcol: String (1.0)
my_fid: Integer (3.0)
```
The aim is to use the values of "my_fid" as FID  in PostGIS.

`ogr2ogr PG:"host=localhost port=5432 dbname=db user=user password=pw" -sql "select my_fid as ogc_fid, * from point" point.shp -nln fidtest`

The ogc_fid has now the desired values from my_fid (11, 12, and 13)
<img width="196" alt="image" src="https://user-images.githubusercontent.com/1751612/222139196-70da06fe-8cb2-46ad-b8b4-96567b184d82.png">

**Comment by dispiste** [comment]
@jratike80 the -sql parameter works, as far as you don't use the -preserve_fid parameter.
