### ISSUE TITLE
GDAL /vsizip fails to open ZIP archive which is compressed with Deflate64

### ISSUE THREAD

**Issue by neteler** [OSGeo/gdal#7013]
Trying to read open data provided by the City of Hamburg in Germany leads to an issue with unsupported Deflate64 compression:

```
gdalinfo /vsizip/vsicurl/https://daten-hamburg.de/geographie_geologie_geobasisdaten/digitales_hoehenmodell_bdom/DOM1_XYZ_HH_2020_04_30.zip/dom1_32_555_5928_1_hh.xyz
ERROR 6: A file in the ZIP archive uses the Deflate64 unsupported compression method. You can uncompress priorly with the unzip utility.
ERROR 1: cpl_unzOpenCurrentFile() failed
gdalinfo failed - unable to open '/vsizip/vsicurl/https://daten-hamburg.de/geographie_geologie_geobasisdaten/digitales_hoehenmodell_bdom/DOM1_XYZ_HH_2020_04_30.zip/dom1_32_555_5928_1_hh.xyz'.
```

The related code section is here:

https://github.com/OSGeo/gdal/blob/30daf01d3269dfe6933c50c7e422ea5a1d97c727/port/cpl_minizip_unzip.cpp#L1346

I cannot judge how much effort it would be to implement support for the  Deflate64 compression (for now we can go on with download/uncompress, then continue with GDAL) but I took liberty to open an issue.

**Comment by rouault** [comment]
> how much effort it would be to implement support for the Deflate64 compression

A non-trivial one, given that Deflate64 is not supported by zlib itself: https://en.wikipedia.org/wiki/Deflate#Deflate64/Enhanced_Deflate. That said it seems that the code at https://github.com/madler/zlib/tree/master/contrib/infback9 could be used, seeing it mentioned at https://pypi.org/project/zipfile-deflate64/

**Comment by rouault** [comment]
Implemented in https://github.com/OSGeo/gdal/pull/7014. Was quite tricky as infback9 needs to be patched to be usable for streamed reading.

**Comment by neteler** [comment]
Wow, thanks for your efforts, @rouault!
