### ISSUE TITLE
BMP file not properly created if only calling Create() on it

### ISSUE THREAD

**Issue by gktval** [OSGeo/gdal#7025]
## Expected behavior and actual behavior.
After creating a Dataset with the BMP driver, then trying to reopen the dataset, I am get an exception:
'C:\Data\myfile.bmp' not recognized as a supported file format.

This method started failing after upgrading to GDAL 3.5.2. My previous version was 2.4.4

## Steps to reproduce the problem.

Here is code to create the bmp file, then reopen it.
```
        Dim name as string = "C:\Data\myfile.bmp"

        'Create the Directory if it doesn't exist
        If Not Directory.Exists(Path.GetDirectoryName(name)) Then
            Directory.CreateDirectory(Path.GetDirectoryName(name))
        End If

        Dim drvName As String = "BMP"

        Dim drv As Driver = Gdal.GetDriverByName(drvName)

        If drv Is Nothing Then
            Return Nothing  'GDAL Driver Not Found
        End If

        Dim gdalDataType As DataType = OSGeo.GDAL.DataType.GDT_Byte
        Dim dataset As Dataset = drv.Create(name, 256, 256, 1, gdalDataType, New String() {})
        dataset.FlushCache()
        dataset.Dispose()

        Try
           Dim newDataset as Dataset = Gdal.Open(name, OSGeo.GDAL.Access.GA_ReadOnly)
        Catch ex As Exception
           'Will Throw Error Here
           MessageBox.Show(ex.Message)
        End Try
```

## Operating system
Windows 11 64bit

## GDAL version and provenance
GDAL nuget 3.5.2

**Comment by rouault** [comment]
Is It C# ?
I'm not sure what .Dispose() does, but it isn't probably enough to call the native GDALClose() (which is needed here to make sure the dataset is properly finalized on disk)
@runette ?

**Comment by gktval** [comment]
It is VB.Net. Which is very similar to c#. It uses the c# bindings. I believe that FlushCache closes it and Dispose clears the Garbage and releases it.

**Comment by rouault** [comment]
> believe that FlushCache closes it

definitely not: the FlushCache() method in GDAL just empties the block cache, but doesn't close the dataset.

This looks like an issue with garbage collection indeed. Perhaps also try to nullify the object or call a .close() / .delete() method if such method exists (sorry if that's wrong track: I'm illiterate in the C# / VB.Net ecosystem). In Java bindings, in a similar scenario dataset.delete() must be called.

**Comment by gktval** [comment]
Regardless. That is not the issue. This is standard for c#/vb.Net. You FlushCache, the Dispose. I also have dataset  = Nothing. The problem is not that the file is in use. The error is 'not recognized as a supported file format.'

**Comment by runette** [comment]
Hi

I had a quick look. I was able to reproduce the problem (always a good start) and the problem is in the creation of the file (gdalinfo on the created file reports the same problem).

I can't see anything obviously wrong with the code that is there (although I don't use VB - just C#). I am thinking that is has to do with the code that is NOT there. You are creating a Dataset but not a Band. I don't know if that is the problem.

I don't have the time at the moment to work out the VB to do that - but the C# GDALWrite.cs test program (https://github.com/OSGeo/gdal/blob/master/swig/csharp/apps/GDALWrite.cs) works with the latest versions of GDAL - so try to recreate that and see if the problem persists

**Comment by gktval** [comment]
Thanks for the response. Below is the code in c#. I have used this method for the past 10ish years. It creates an empty file with a single band. After that, I come back and write the data to it. I tested it with other drivers, such as GTiff and it works. So it's just bmp files. I'll see if I can dig into it deeper.

```
public void Test()
{
    string name = @"C:\Data\myfile.bmp";

    // Create the Directory if it doesn't exist
    if (!Directory.Exists(Path.GetDirectoryName(name)))
        Directory.CreateDirectory(Path.GetDirectoryName(name));

    string drvName = "BMP";

    Driver drv = Gdal.GetDriverByName(drvName);

    if (drv == null)
        return null;// GDAL Driver Not Found

    DataType gdalDataType = OSGeo.GDAL.DataType.GDT_Byte;
    Dataset dataset = drv.Create(name, 256, 256, 1, gdalDataType, new string[] { });
    dataset.FlushCache();
    dataset.Dispose();

    try
    {
        Dataset newDataset = Gdal.Open(name, OSGeo.GDAL.Access.GA_ReadOnly);
    }
    catch (Exception ex)
    {
        // Will Throw Error Here
        MessageBox.Show(ex.Message);
    }
}

```

**Comment by runette** [comment]
You need to write the Band as well as the Dataset. The fact that a shortcut works in a very old version and other drivers is not relevant. The following does work

```
string name = @"C:\Data\myfile.bmp";
    Gdal.AllRegister();

    // Create the Directory if it doesn't exist
    if (!Directory.Exists(Path.GetDirectoryName(name)))
        Directory.CreateDirectory(Path.GetDirectoryName(name));

    string drvName = "BMP";

    Driver drv = Gdal.GetDriverByName(drvName);


    if (drv == null)
        return;// GDAL Driver Not Found

    DataType gdalDataType = OSGeo.GDAL.DataType.GDT_Byte;
    Dataset dataset = drv.Create(name, 256, 256, 1, gdalDataType, new string[] { });
    Band band = dataset.GetRasterBand(1);

    byte[] buffer = new byte[256 * 256];
    band.WriteRaster(0, 0, 256, 256, buffer, 256, 256, 0, 0);

    band.FlushCache();

    dataset.FlushCache();
    dataset.Dispose();

    try
    {
        Dataset newDataset = Gdal.Open(name, OSGeo.GDAL.Access.GA_ReadOnly);
    }
    catch (Exception ex)
    {
        // Will Throw Error Here
        Console.WriteLine(ex.ToString());
    }
```

**Comment by rouault** [comment]
Ah, I wrongly assumed this was a C# / VB.net bindings usage issue, but it is an issue in the BMP driver itself that doesn't properly null-initialize itself.
"gdal_create -outsize 10 10 out.bmp" generates an invalid BMP file, whereas it should be valid.

**Comment by gktval** [comment]
Thanks. I would agree that creating a blank bitmap before adding data SHOULD still be a valid bmp. Backwards compatibility and compatibility to other drivers is not a shortcut.
