### ISSUE TITLE
HDF4 Information list is incompelete

### ISSUE THREAD

**Issue by pdycp3** [OSGeo/gdal#7026]
when i use gdalinfo.exe to list the modis formate Image (T2020169030500.L1B_LAC), the subdataset is not incomplete ,while version is 3.6.1
![image](https://user-images.githubusercontent.com/45677507/210914865-66d40e3c-2e05-4113-a406-159ae626cb02.png)
but in version 2.3.2 is complete
![image](https://user-images.githubusercontent.com/45677507/210915178-5d161903-d630-4b12-b55b-ed79fa152366.png)
how to read complete subdataset?

**Comment by rouault** [comment]
Please provide a link where to download the dataset (or attach it here in a .zip if not too big)

**Comment by piyushrpt** [comment]
Can you try with `LIST_SDS=YES`. See Open Options here: https://gdal.org/drivers/raster/hdf4.html

**Comment by pdycp3** [comment]
> Please provide a link where to download the dataset (or attach it here in a .zip if not too big)

sorry the file is148m

**Comment by pdycp3** [comment]
> Can you try with `LIST_SDS=YES`. See Open Options here: https://gdal.org/drivers/raster/hdf4.html#open-options

![image](https://user-images.githubusercontent.com/45677507/210924270-cdbaa51d-4d49-4505-9fa0-a2f3caa57209.png)
how to set this option，

**Comment by pdycp3** [comment]
> > Please provide a link where to download the dataset (or attach it here in a .zip if not too big)
> 
> sorry the file is148m

thank you I know how to set -oo LIST_SDS=YES

**Comment by pdycp3** [comment]
> Can you try with `LIST_SDS=YES`. See Open Options here: https://gdal.org/drivers/raster/hdf4.html#open-options

![image](https://user-images.githubusercontent.com/45677507/210930793-821ecd61-4b29-42fd-9f97-e0373ad30c38.png)
thank you I know how use gdalinfo.exe to set -oo LIST_SDS=YES,when i use gdal to open this image,how to set this option

**Comment by piyushrpt** [comment]
Use `GDALOpenEx`. Gives you more control - https://github.com/OSGeo/gdal/blob/92f2bab2bfd8001ee076af8abc90fe9cbfdcd5f0/apps/gdalinfo_bin.cpp#L137

**Comment by pdycp3** [comment]
> Use `GDALOpenEx`. Gives you more control -
> 
> https://github.com/OSGeo/gdal/blob/92f2bab2bfd8001ee076af8abc90fe9cbfdcd5f0/apps/gdalinfo_bin.cpp#L137

thanks i get it success!!!

**Comment by piyushrpt** [comment]
:+1: Plz close this issue
