### ISSUE TITLE
The GDALPolygonize function causes the program to crash

### ISSUE THREAD

**Issue by wuxianshenga** [OSGeo/gdal#7027]
## Expected behavior and actual behavior.

Using GDALPolygonize function transformation vector and raster (61640, 35398) to program an exception occurs collapse, locating the problem occurred in GDALRasterPolygonEnumeratorT: : NewPolygon, When CPLRealloc returns nullptr,

panPolyIdMap[nPolyId] = nPolyId;
panPolyValue[nPolyId] = nValue;
Raises a null pointer exception

Hopefully, you can add the null pointer check code before the above code

## Operating system

windows/linux

## GDAL version and provenance

3.1.4

**Comment by rouault** [comment]
Please provide the dataset on which this can be reproduced (the content matters. the dimensions are not enough) and the amount of RAM on your system
