### ISSUE TITLE
nmake build variable defined checks

### ISSUE THREAD

**Issue by dirkvdb** [OSGeo/gdal#703]
the nmake.opt file sets up a number of variables like this:
```
!IFNDEF DLLBUILD
DLLBUILD=1
!ENDIF
```
and subsequently performs checks on these variables like:
```
!IFDEF DLLBUILD
GDALLIB	=    $(GDAL_ROOT)/gdal_i.lib
!ELSE
GDALLIB	=    $(GDAL_ROOT)/gdal.lib
!ENDIF
```

This prohibits us from specifying DLLBUILD=0 on the nmake command line because when a variable is 0 it is considered as defined by nmake.
In similar fashion, providing DEBUG=0 on the command line creates a debug build.

This is really counter intuitive and requires us to patch the nmake.opt to get the build settings we want.

**Comment by rouault** [comment]
Has been fixed a few days ago per d551a0b66ddb600b91dc6c8d78d1a2a2e1427876 / #678 for the DLLBUILD part.
I've just fixed the DEBUG part with b286909

**Comment by dirkvdb** [comment]
Thanks!
The same issue is still present for:
```
INCLUDE_OGR_FRMTS
INCLUDE_GNM_FRMTS
```

**Comment by rouault** [comment]
> The same issue is still present for:
> 
> INCLUDE_OGR_FRMTS
> INCLUDE_GNM_FRMTS

Those are advanced settings, not actually tested, so I wouldn't do any particular effort for those.
