### ISSUE TITLE
Failure to lookup dependent package if transitively already found

### ISSUE THREAD

**Issue by Neumann-A** [OSGeo/gdal#7040]
https://github.com/OSGeo/gdal/blob/516e10a58d1a218afcbae9988956e078bf1ea769/cmake/helpers/CheckDependentLibraries.cmake#L113

is a problem and stops `gdal` to lookup `zstd` correctly if `zstd` was already looked up by `tiff`. So `tiff` calls for `zstd` -> `ZSTD_FOUND` set. gdal uses target `ZSTD:zstd` but forgot to setup that target since upstream target names differs. 

Generally don't guard `find_package(pkg)` calls with `pkg_FOUND` stuff.

**Comment by mathstuf** [comment]
Generally, I try to push these name differences upstream. See https://github.com/zeux/pugixml/blob/master/scripts/pugixml-config.cmake.in#L5-L12 as an example.

**Comment by mathstuf** [comment]
Though that specific case is upstream itself renaming (adding a namespace), upstream providing these bridges helps to get projects to migrate off of their own local find modules.

**Comment by Neumann-A** [comment]
Furthermore according to the trace `find_package2` didn't do anything. It simply returned since it couldn't find any info in the variables which probably need to be set somehow.

**Comment by rouault** [comment]
> (as in the current changes by @Neumann-A and @rouault)

I didn't try much the effectiveness @Neumann-A suggested change beyond just checking it didn't break my own build (and CI)

happy to let others submit a better fix :-)

**Comment by dg0yt** [comment]
> Isn't find_package2 not just a pkg-config lookup?

> Furthermore according to the trace `find_package2` didn't do anything. It simply returned (
> 
> https://github.com/OSGeo/gdal/blob/6bdeb5623b5e7febde1fcfb932ee9214db9594dc/cmake/modules/DefineFindPackage2.cmake#L99
> ) since it couldn't find any info in the variables which probably need to be set somehow.

The problem is not what `find_package2` does for zstd.
The problem is the guard in its current form.
It is presence breaks zstd in vcpkg, due to unexpected interaction with regular `find_package` variables.
It is absence may break the cases where `find_package2` is used. Which my or may not be covered by vcpkg or gdal CI.
That's why I'm proposing to separate the concerns. I can make a PR, but not in a hurry.

**Comment by Neumann-A** [comment]
I don't see that interaction in the trace logs. 

Basically 
https://github.com/OSGeo/gdal/blob/6bdeb5623b5e7febde1fcfb932ee9214db9594dc/cmake/modules/DefineFindPackage2.cmake#L85-L87
acts as the stop gate for `find_package2` according to the trace. (There is no define_find_package2 for either TIFF or ZSTD)

Furthermore the targets of `find_package2` and the other way don't generally overlap so it is save to call both.

The real issue however is that `gdal_check_package_target(${key} ${GDAL_CHECK_PACKAGE_${name}_TARGETS})` is not called if one of the searched for targets already exists.

**Comment by dg0yt** [comment]
Again, the problem is the guard in its current form.
https://github.com/OSGeo/gdal/blob/516e10a58d1a218afcbae9988956e078bf1ea769/cmake/helpers/CheckDependentLibraries.cmake#L113

Even you propose to remove it.

> Furthermore the targets of find_package2 and the other way don't generally overlap so it is save to call both.

You cannot know. It depends on the CMake configs and find modules available in the user's context.

**Comment by Neumann-A** [comment]
> It depends on the CMake configs and find modules available in the user's context.

Only if you build gdal not when you consume it. As stated in https://github.com/microsoft/vcpkg/pull/28839#issuecomment-1376908991 a problem may only occur if the target names collide and the target mean doesn't exactly mean the same thing (e.g. somebody attached custom properties to it and put the code for that into the `if(NOT TARGET)` part of the target definition). As such it would be better to always use project unique target names instead of possibly defining new conflicting ones. So Instead of using `ZSTD::zstd`, gdal could safely define `GDAL::zstd` depending on what external targets exist and use that internally,

Search possible target names/or pkgconfig -> If target found -> define `GDAL::pkg` and link against found target -> Use only `GDAL::pkg` internally. (This is basically the VTK style of linking external deps.)

**Comment by dg0yt** [comment]
> Only if you build gdal not when you consume it.

This is the GDAL repo, so building GDAL is relevant.

>  problem may only occur if the target names collide and the target mean doesn't exactly mean the same thing (e.g. somebody attached custom properties to it and put the code for that into the if(NOT TARGET) part of the target definition). As such it would be better to always use project unique target names instead of possibly defining new conflicting ones. So Instead of using ZSTD::zstd, gdal could safely define GDAL::zstd depending on what external targets exist and use that internally,

I fully agree. But this change has a different scope, probably not the right thing to backport to 3.6.
