### ISSUE TITLE
Support several rasters in gdal_contour

### ISSUE THREAD

**Issue by latot** [OSGeo/gdal#7049]
Hi all!, Actually we can get the contours for example with the script ```gdal_contour```, and is great.

The actual algorithm in my little research is right, is just seems the implementation does not support several rasters, is not the same process one raster, to split it in four for example, run contours and join to one file.

In particular, the contours in the limits of the rasters are broken, so...., Would be great a script/function that allow us to send several raster files and get one big and right contour file.

Thx!

**Comment by jratike80** [comment]
You can combine the rasters into a virtual raster https://gdal.org/drivers/raster/vrt.html with gdalbuildvrt https://gdal.org/programs/gdalbuildvrt.html and use that as input for gdal_contour.

You should have noticed this:

> IMPORTANT: Do NOT use GitHub to post any questions or support requests!
>            They will be closed immediately and ignored.
> 
> Questions should go to the gdal-dev mailing list at
> https://lists.osgeo.org/mailman/listinfo/gdal-dev
> or other support forums. GitHub issues are for bug
> reports and suggestions for new features.
>
