### ISSUE TITLE
GDAL 3.6.2 : OS X (x86_64) and DYNAMIC LIBRARY (GDAL) : not found but could be fixed easily

### ISSUE THREAD

**Issue by Laurent-777** [OSGeo/gdal#7051]
## Expected behavior and actual behavior.

GDAL library(ies) to be correctly found/loaded, in particular, when typing gdal_info --formats

For example (please modify !!!): I expected to be able to open this raster file (with a link to
the raster file, or it as an attachment) and it returns an error message
instead.

## Steps to reproduce the problem.
Correctly installed but, when not installed in a "standard" location (such as in /usr/local, or /Library/Frameworks), namely as in my case in an external HD, the GDAL libraries are not found. As an example, this is the case (testing GDAL) when I run : gdal_info --formats. It fails.
However, when I set GDAL_SET_INSTALL_RELATIVE_RPATH to ON, it works. But... it fails to when integrated in a GIS software. To fix this new case, I need to write in the same Terminal window : export DYLD_LIBRARY_PATH=the_path_of_the_GDAL_libraries_folder. So, the GIS sofware uses GDAL 3.6.2 adequately.

## Operating system
OS X Lion (10.7.5) ; gcc 4.9.4.
CMake 3.18.x (x is probably 6).
PROJ 6.3.x.

## GDAL version and provenance
3.6.2

So, I guess this is a CMake, and simple, variable(s) issue with the RPATH or similar.

Kind regards,

Laurent Delphin

Please kindly see :

Please kindly see this :

https://gdal.org/development/building_from_source.html

https://developer.apple.com/library/archive/documentation/DeveloperTools/Conceptual/DynamicLibraries/100-Articles/UsingDynamicLibraries.html

**Comment by rouault** [comment]
Well, the solution is what you did: set DYLD_LIBRARY_PATH.
How could this GIS software know where to find your custom build otherwise ? Am I missing something ?

**Comment by Laurent-777** [comment]
Hi !

No matter, it's not your fault. In fact, what I let you know is very specific of OS X. I am afraid that it doesn't appear with Windows-, or Linux-based computers.

Nevertheless, GDAL is a very powerful software, having asked and asking full expertise as well as a lot of work.

Without GDAL, no doubt I was not able to do what I do in Research.

Many many thanks.

Kind regards,

Laurent Delphin

PS Developers should be aware of teh new Apple chips (M1, M2...).

**Comment by rouault** [comment]
> I am afraid that it doesn't appear with Windows-, or Linux-based computers.

well, no, it applies to any operating system. There are a set of default locations where shared libraries are found (specific to each operating system). If you install outside of it, on all systems you need to use some "trick" to make the binary aware of where to find. No magic :-)
