### ISSUE TITLE
Autotools configure script doesn't pass driver package paths to linker during build step

### ISSUE THREAD

**Issue by RichardLangFromNZ** [OSGeo/gdal#706]
So, trying to build GDAL on linux with a custom poppler library that I've previously built and installed into a custom location (`/foo/bar`,  such that libraries and sym-links are in `/foo/bar/lib`, headers in` /foo/bar/include` etc.)   

So I invoke the configure script with a `--with-poppler=/foo/bar` argument and the configure step executes successfully, detecting my custom poppler install, however the subsequent build step kicks up a linker warning 

`/usr/bin/ld: warning: libpoppler.so.77, needed by /some/path/libgdal.so, not found (try using -rpath or -rpath-link)`

to fix the error I also need to pass the configure script a `"LDFLAGS=-Wl,-rpath-link=/foo/bar/lib"` argument.  This seems a violation of the DRY principle (don't repeat yourself), a well mannered script would handle this internally (see also #531)

**Comment by rouault** [comment]
I'm not sure we should systematically pass -Wl,-rpath-link=/foo/bar/lib in case people build in some directories but deploy to a more standard layout

**Comment by RichardLangFromNZ** [comment]
Perhaps, but a couple of things to consider:
- `/foo/bar` does need to be an install directory with `lib` and `include` directories underneath it, not just some random location in the build tree where a copy of the libraries can be found.  I think that increases the likelihood that if a user specifies a custom path it is actually what they mean.
- Don't take my word for it, but as far as I know, `-rpath-link` doesn't actually have any effect on the built binaries, it's just used as part of a build-time check that all the symbols that are required from a shared library at run time are actually resolvable.  Thus it doesn't actually do any harm if the check is performed against a copy of the library in a different location to the one that is actually used at run time.

**Comment by rouault** [comment]
Improvements to autotools build systems will no longer be considered now that we are developing a cmake build system that will eventually replace it
