### ISSUE TITLE
netCDF variable with colon in name

### ISSUE THREAD

**Issue by rhijmans** [OSGeo/gdal#7061]
It seems that GDAL cannot handle netCDF variables that have a colon in their name (reported here: https://github.com/rspatial/terra/issues/975)

Here is the example file [test.zip](https://github.com/OSGeo/gdal/files/10414256/test.zip) with the variables: "VAR_NAME" (works) and VAR:NAME (does not work)

This is what is returned by `gdalinfo` for "VAR:NAME". 

```
$ gdalinfo NETCDF:"test.nc":VAR:NAME

ERROR 1: Failed to parse NETCDF: prefix string into expected 2, 3 or 4 fields.
gdalinfo failed - unable to open 'NETCDF:test.nc:VAR:NAME'.
```

And for "VAR_NAME"

```
$ gdalinfo NETCDF:"test.nc":VAR_NAME

Warning 1: No UNIDATA NC_GLOBAL:Conventions attribute
Driver: netCDF/Network Common Data Format
Files: test.nc
Size is 91, 91
Coordinate System is `'
Origin = (0.950000000000000,10.050000000000001)
Pixel Size = (0.100000000000000,-0.100000000000000)
Metadata:
  lat#long_name=lat
  lat#units=degrees_north
  lon#long_name=lon
  lon#units=degrees_east
Corner Coordinates:
Upper Left  (   0.9500000,  10.0500000)
Lower Left  (   0.9500000,   0.9500000)
Upper Right (  10.0500000,  10.0500000)
Lower Right (  10.0500000,   0.9500000)
Center      (   5.5000000,   5.5000000)
Band 1 Block=91x1 Type=Float32, ColorInterp=Undefined
  NoData Value=9.96920996838686905e+36
  Metadata:
    NETCDF_VARNAME=VAR_NAME
```

**Comment by rouault** [comment]
fix in https://github.com/OSGeo/gdal/pull/7062
The issue is more when creating the subdataset list.
If you use ``NETCDF:"test.nc":"VAR:NAME"`` as connection string, that will work (on Bash shell, you need to surround the whole connection string with single quote characters, otherwise the double quotes are just stripped off by the shell)

**Comment by rhijmans** [comment]
I can confirm that `gdalinfo 'NETCDF:"test.nc":"VAR:NAME"'` works but that the underlying problem I see with terra is with the subdatasets.
