### ISSUE TITLE
CSV driver doesn't recognize "pipe" as a separator

### ISSUE THREAD

**Issue by tobwen** [OSGeo/gdal#7074]
## Expected behavior and actual behavior.
Docs (https://github.com/OSGeo/gdal/blob/master/doc/source/drivers/vector/csv.rst) say:
```
The driver will also accept a semicolon, a tabulation, **a pipe**, or a space character as field separator . 
```

Actual behavior when the separator is a pipe:

```
FAILURE:
Unable to open datasource `...' with the following drivers.
```
## Steps to reproduce the problem.
doesn't work
```
printf 'First|Second\n1|2' | ogrinfo CSV:/vsistdin/ -ro -al 
printf 'First|Second\n1|2' > test.txt; ogrinfo CSV:test.txt -ro -al 
```

works
```
printf 'First;Second\n1;2' | ogrinfo CSV:/vsistdin/ -ro -al 
printf 'First;Second\n1;2' > test.txt; ogrinfo CSV:test.txt -ro -al 
```

## Operating system
- Debian Buster (10, latest updates)
- Windows 10 Professional, 64 bit (latest updates)

## GDAL version and provenance
- GDAL 2.4.0
- GDAL 3.6.2

**Comment by rouault** [comment]
This is only available in master / 3.7.0dev
