### ISSUE TITLE
question: curly brackets in filename?

### ISSUE THREAD

**Issue by tobwen** [OSGeo/gdal#7076]
I've seen curly brackets in this recommendation:
https://github.com/OSGeo/gdal/blob/a632e3093d6dd34cdcf979a5b2a20529fe2df943/port/cpl_vsil_abstract_archive.cpp#L625

Curly brackets might normally be interpreted by a shell. Is this by accident or by design?

**Comment by rouault** [comment]
> Is this by accident or by design?

by design. bash doesn't do anything particular with just curly brackets, unless there's a $ sign before {

**Comment by lnicola** [comment]
It does in contexts like `{a,b}{1,2}`, but I don't think that happens when there's no comma.

**Comment by tobwen** [comment]
Yeah, I hope the comma gets escaped or quoted. I've often seen filenames containing commas.
