### ISSUE TITLE
ogr2ogr Script fails via SQL or Windows server, but works on my machine

### ISSUE THREAD

**Issue by joshuageoghegan** [OSGeo/gdal#709]
I have a script which reprojects SQL data. It works completely fine if I run it via my machine, but if I run the same script on the server it fails, even though the same files live on that server, so it is exactly the same script/files that work under my login - not a copy. Similarly it fails when running within SQL. The SQL error I get is 

`ERROR 1: Can't load requested DLL: Z:\BroadSpectrumSQLTreeExtract\ogr2ogr\gdalplugins\ogr_MSSQLSpatial.dll`

The cmd line error on the server is
`ERROR 1: Can't load requested DLL: Z:\BroadSpectrumSQLTreeExtract\ogr2ogr\gdalplugins\ogr_MSSQLSpatial.dll
126: the specified module could not be found.`

## Steps to reproduce the problem.

Double click on the same bat file that lives on the server. Within this file (I've simplified it for this issue)
`pushd \\servername\foldername
ogr2ogr -f "MSSQLSpatial" -s_srs "EPSG:4283"  "MSSQL:server=servername;database=databasename;trusted_connection=yes" "MSSQL:server=servername;database=databasename;trusted_connection=yes" -sql "SELECT blah FROM blah" -t_srs "EPSG:28355" -lco "GEOM_TYPE=geometry" -lco "GEOM_NAME=GEOMETRY_SPA" -nln "Blah_reprojected"
popd \\servername\foldername`

## Operating system

Server: Windows Server 2008 R2 Standard
My machine: Windows 10 Enterprize

## GDAL version and provenance

This is difficult to tell but it looks like version 4.74.8702 for Intramaps Map Manager 2.
The files are a part of our Tech 1 Intramaps GIS installation. Is there an easy way to find the version?

**Comment by rouault** [comment]
Use "Dependency walker" ( http://www.dependencywalker.com/ ) on ogr_MSSQLSpatial.dll. You probably need some DLL in your server installation (probably from MSSQL SDK). Anyway as you mention this is a GDAL build coming from some vendor, you should ask to their support.

**Comment by joshuageoghegan** [comment]
Thanks Evan,

I’ll look into Dependency Walker.
I did ask the vendor but they couldn’t help as they don’t use it this way.

Regards,




[MPSlogo]

JOSHUA GEOGHEGAN | GIS Specialist
phone: 03 5950 1321
email: joshua.geoghegan@mornpen.vic.gov.au<mailto:joshua.geoghegan@mornpen.vic.gov.au>
Private Bag 1000, Rosebud VIC 3939 | 90 Besgrove Street, Rosebud VIC 3939


www.mornpen.vic.gov.au<https://www.mornpen.vic.gov.au> | Twitter @MornPenShire<http://twitter.com/MornPenShire> | Facebook @MornPenShire<https://www.facebook.com/mornpenshire>

[cid:image002.png@01D40D29.A994F9C0]

Mornington Peninsula Shire acknowledges and pays respect to the Bunurong/Boon Wurrung people,
the traditional custodians of these lands and waters.
