### ISSUE TITLE
VFK driver: missing geometry for SBPG layer

### ISSUE THREAD

**Issue by landam** [OSGeo/gdal#710]
Geometry should be built for SBPG layer similarly as for SBP layer.

## Expected behavior and actual behavior.

```
ogrinfo ~/geodata/vfk/Export_vse.vfk --config OGR_VFK_DB_OVERWRITE YES | grep SBP
```

Currently:

```
50: SBP (Line String)
77: SBPG (None)
```

Should be:

```
50: SBP (Line String)
77: SBPG (Line String)
```

## GDAL version and provenance

GDAL master

**Comment by rouault** [comment]
Will probably be for 2.3.2 as I'll call to promote 2.3.1 RC2 as final

**Comment by landam** [comment]
Agreed, 2.3.2 will be fine.

**Comment by rouault** [comment]
Is there still activity to be done on that ticket ?

**Comment by landam** [comment]
Sorry for delay, backport done.
