### ISSUE TITLE
cmake build results in "error while loading shared libraries: libgdal.so ..."

### ISSUE THREAD

**Issue by seidlmic** [OSGeo/gdal#7104]
## Expected behavior and actual behavior.

While ./configure --prefix=[path] makes GDAL to be installed in given path and looks for libgdal.so.xx also in this directory with
cmake -DCMAKE_INSTALL_PREFIX=[path] GDAL looks for libgdal.so.xx in system directories  like /lib/... or /usr/lib/... (found with strace) which results in  **'error while loading shared libraries: libgdal.so.31: cannot open shared object file: No such file or directory'**

## Steps to reproduce the problem.

From build directory:
$ cmake ..  -DCMAKE_INSTALL_PREFIX=[path]
$ cmake --build . -j 8
$ cmake --build . --target install
$ [path]/bin/ogr2ogr

## Operating system

Ubuntu 20.04 64 bit

## GDAL version and provenance

3.5.1
master

**Comment by rouault** [comment]
Add -DGDAL_SET_INSTALL_RELATIVE_RPATH=ON or -DCMAKE_INSTALL_RPATH=[path]/lib to your initial cmake invokation.
