### ISSUE TITLE
HDF5 bands

### ISSUE THREAD

**Issue by MarcYin** [OSGeo/gdal#7117]
## Expected behavior and actual behavior.

gdal gives wrong number of bands for HDF5 file. It is expected to be 3 bands, but gdal gives 1200 bands.

The file I used can be accessed from [here](https://github.com/MarcYin/Files/raw/main/VNP43MA1.A2021343.h17v04.001.2021351230811.h5)

## Steps to reproduce the problem.

```python
>>> from osgeo import gdal
>>> file_url = 'https://github.com/MarcYin/Files/raw/main/VNP43MA1.A2021343.h17v04.001.2021351230811.h5'
>>> subdataset = 'HDF5:"/vsicurl/%s"://HDFEOS/GRIDS/VIIRS_Grid_BRDF/Data_Fields/BRDF_Albedo_Parameters_M3'%file_url
>>> g = gdal.Open(subdataset)
>>> print(g.RasterCount, g.RasterXSize, g.RasterYSize)
1200 3 1200
```

Expected to be:

(3, 1200, 1200)

## Operating system

Centos-7.9.2009-Core

## GDAL version and provenance
gdal 3.3.1

**Comment by jgomezdans** [comment]
Can confirm with GDAL Python bindings versions 3.4.1 and 3.5.0 on Linux (using conda forge packages)
