### ISSUE TITLE
CRSs 3003 and 3004

### ISSUE THREAD

**Issue by gpsaliola** [OSGeo/gdal#7123]
GeoTiff does not seem to implement the change of 1/15/2003 (https://epsg.org/closed-change-request_2003.02/Correct-projCRS-prime-meridian-and-projection-inconsistency.html?sessionkey=gezx4ovz52) which introduces CRSs 3003 (Monte Mario / Italy zone 1) and 3004 (Monte Mario / Italy zone 2). CRSs 26591 (Monte Mario (Rome) / Italy zone 1) and 26592 (Monte Mario (Rome) / Italy zone 2) are obsolete.
Thank you.

**Comment by jratike80** [comment]
Works for me with GDAL 3.6.2, released 2023/01/02

`gdal_translate -of GTiff -a_srs EPSG:3003 stat.tif 3003test.tif`
```
gdalinfo 3003test.tif
Driver: GTiff/GeoTIFF
Files: 3003test.tif
Size is 12000, 12000
Coordinate System is:
PROJCRS["Monte Mario / Italy zone 1",
    BASEGEOGCRS["Monte Mario",
        DATUM["Monte Mario",
            ELLIPSOID["International 1924",6378388,297,
                LENGTHUNIT["metre",1]]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433]],
        ID["EPSG",4265]],
    CONVERSION["Italy zone 1",
        METHOD["Transverse Mercator",
            ID["EPSG",9807]],
        PARAMETER["Latitude of natural origin",0,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",9,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["Scale factor at natural origin",0.9996,
            SCALEUNIT["unity",1],
            ID["EPSG",8805]],
        PARAMETER["False easting",1500000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["easting (X)",east,
            ORDER[1],
            LENGTHUNIT["metre",1]],
        AXIS["northing (Y)",north,
            ORDER[2],
            LENGTHUNIT["metre",1]],
    USAGE[
        SCOPE["Engineering survey, topographic mapping."],
        AREA["Italy - onshore and offshore - west of 12┬░E."],
        BBOX[36.53,5.93,47.04,12]],
    ID["EPSG",3003]]
    ```

**Comment by rouault** [comment]
@gpsaliola You must give detailed explanations / reproducing instructions of what your are attempting exactly

**Comment by gpsaliola** [comment]
I use GDAL ver. 3.4.2.
The command I use is 
gdal_translate -of MBTiles -q test.tif test.mbtiles
The result is traslated of some meters.
These are the geotiff tags:

Geotiff_Information:
   Version: 1
   Key_Revision: 1.0
   Tagged_Information:
      ModelTransformationTag (4,4):
         0.169133917      0.000779294983   0                1518761.74       
         0.00037119212    -0.169015705     0                4962486.79       
         0                0                1                0                
         0                0                0                1                
      End_Of_Tags.
   Keyed_Information:
      GTModelTypeGeoKey (Short,1): ModelTypeProjected
      GTRasterTypeGeoKey (Short,1): RasterPixelIsArea
      GeogAngularUnitsGeoKey (Short,1): Angular_Degree
      ProjectedCSTypeGeoKey (Short,1): Unknown-3003
      ProjLinearUnitsGeoKey (Short,1): Linear_Meter
      End_Of_Keys.
   End_Of_Geotiff.

PCS = 3003 (name unknown)
Projection Linear Units: 9001/metre (1.000000m)

Corner Coordinates:
Upper Left    (1518761.735,4962486.786)
Lower Left    (1518764.470,4961893.541)
Upper Right   (1519598.948,4962488.624)
Lower Right   (1519601.683,4961895.379)
Center        (1519181.709,4962191.082)

**Comment by rouault** [comment]
https://gdal.org/drivers/raster/mbtiles.html#raster-creation-issues: "When using the CreateCopy() API (such as with gdal_translate), automatic reprojection of the input dataset to EPSG:3857 (WebMercator) will be done"

**Comment by jratike80** [comment]
Do you actually mean that you can see an offset of a few meters when you convert your EPSG:3003 image into EPSG:3857 that MBTiles is always using? In that case you can test the same with gdalwarp:

`gdalwarp -t_srs EPSG:3857 test.tif test_3857.tif`

But if you experience an offset you must also tell what do you use as a reference that is known to be correct.

**Comment by gpsaliola** [comment]
I've used Listgeo ver 1.1.4.
Now I've downloaded these package:
[libgeotiff125.zip](https://download.osgeo.org/geotiff/libgeotiff/libgeotiff125.zip)
[listgeo-geotifcp-win32-x86-112502.zip](https://download.osgeo.org/geotiff/libgeotiff/listgeo-geotifcp-win32-x86-112502.zip)
Now this is the output of my tiff file:

Geotiff_Information:
   Version: 1
   Key_Revision: 1.0
   Tagged_Information:
      ModelTransformationTag (4,4):
         0.169133917      0.000779294983   0                1518761.74
         0.00037119212    -0.169015705     0                4962486.79
         0                0                1                0
         0                0                0                1
      End_Of_Tags.
   Keyed_Information:
      GTModelTypeGeoKey (Short,1): ModelTypeProjected
      GTRasterTypeGeoKey (Short,1): RasterPixelIsArea
      GeogAngularUnitsGeoKey (Short,1): Angular_Degree
      ProjectedCSTypeGeoKey (Short,1): Unknown-3003
      ProjLinearUnitsGeoKey (Short,1): Linear_Meter
      End_Of_Keys.
   End_Of_Geotiff.

PCS = 3003 (name unknown)
Projection Linear Units: 9001/metre (1.000000m)

Corner Coordinates:
Upper Left    (1518761.735,4962486.786)
Lower Left    (1518764.470,4961893.541)
Upper Right   (1519598.948,4962488.624)
Lower Right   (1519601.683,4961895.379)
Center        (1519181.709,4962191.082)

I guess that tags GTCitationGeoKey  and GeogCitationGeoKey  are deduced from ProjectedCSTypeGeoKey tag.

**Comment by jratike80** [comment]
We are actually discussing in a GDAL bug tracker about a thing that is not a GDAL bug. I suggest to write mail to gdal-dev mailing list. I believe that gis.stackexchange can serve you as well. Whatever forum you decide to use you will be asked to give more information.
- Can you share your image?
- What does `gdalinfo test.tif`show?
- If you rewrite your image `gdal_translate -a_srs EPSG:3003 test.tif rewritten.tif`, does the listgeo output change?
- What is the exact problem that you have and how the theory about not implemented change of 1/15/2003 is related to your issue?

**Comment by gpsaliola** [comment]
[test.zip](https://github.com/OSGeo/gdal/files/10499434/test.zip)

gdalinfo output:

Driver: GTiff/GeoTIFF
Files: C:\Users\gpsal\Desktop\p\test.tif
Size is 4950, 3510
Coordinate System is:
PROJCS["Monte Mario / Italy zone 1",
    GEOGCS["Monte Mario",
        DATUM["Monte_Mario",
            SPHEROID["International 1924",6378388,297,
                AUTHORITY["EPSG","7022"]],
            AUTHORITY["EPSG","6265"]],
        PRIMEM["Greenwich",0,
            AUTHORITY["EPSG","8901"]],
        UNIT["degree",0.0174532925199433,
            AUTHORITY["EPSG","9122"]],
        AUTHORITY["EPSG","4265"]],
    PROJECTION["Transverse_Mercator"],
    PARAMETER["latitude_of_origin",0],
    PARAMETER["central_meridian",9],
    PARAMETER["scale_factor",0.9996],
    PARAMETER["false_easting",1500000],
    PARAMETER["false_northing",0],
    UNIT["metre",1,
        AUTHORITY["EPSG","9001"]],
    AXIS["Easting",EAST],
    AXIS["Northing",NORTH],
    AUTHORITY["EPSG","3003"]]
Data axis to CRS axis mapping: 1,2
PROJ.4 string is:
'+proj=tmerc +lat_0=0 +lon_0=9 +k=0.9996 +x_0=1500000 +y_0=0 +ellps=intl +units=m +no_defs'
GeoTransform =
  1518761.735050049, 0.1691339168349253, 0.0007792949834319073
  4962486.786306337, 0.0003711921198545058, -0.1690157049981233
Metadata:
  AREA_OR_POINT=Area
  TIFFTAG_RESOLUTIONUNIT=2 (pixels/inch)
  TIFFTAG_XRESOLUTION=300
  TIFFTAG_YRESOLUTION=300
Image Structure Metadata:
  COMPRESSION=LZW
  INTERLEAVE=PIXEL
  PREDICTOR=2
Corner Coordinates:
Upper Left  ( 1518761.735, 4962486.786) (  9d14'14.18"E, 44d48'52.96"N)
Lower Left  ( 1518764.470, 4961893.541) (  9d14'14.23"E, 44d48'33.73"N)
Upper Right ( 1519598.948, 4962488.624) (  9d14'52.30"E, 44d48'52.93"N)
Lower Right ( 1519601.683, 4961895.379) (  9d14'52.34"E, 44d48'33.71"N)
Center      ( 1519181.709, 4962191.082) (  9d14'33.26"E, 44d48'43.33"N)
Band 1 Block=4950x1 Type=Byte, ColorInterp=Red
  Mask Flags: PER_DATASET ALPHA 
Band 2 Block=4950x1 Type=Byte, ColorInterp=Green
  Mask Flags: PER_DATASET ALPHA 
Band 3 Block=4950x1 Type=Byte, ColorInterp=Blue
  Mask Flags: PER_DATASET ALPHA 
Band 4 Block=4950x1 Type=Byte, ColorInterp=Alpha

If I use gdal_translate -a_srs EPSG:3003 test.tif rewritten.tif in the gdalinfo output the only difference is compression (in output file there isn't compression LZW and the file is more heavy.

I thought ProjectedCSTypeGeoKey (Short,1): Unknown-3003 was a problem.
If I open the tiff with Google Earth, using the transparency slider, I notice a small offset with the background image.
At this point it is possible that the tiff is badly calibrated or that Google Earth only accepts geotiff in EPSG:3856 (WGS 84 / Pseudo-Mercator).

**Comment by jratike80** [comment]
My listgeo finds a name for the Code-3003 in the annexed test.tif

```
Keyed_Information:
      GTModelTypeGeoKey (Short,1): ModelTypeProjected
      GTRasterTypeGeoKey (Short,1): RasterPixelIsArea
      GeogAngularUnitsGeoKey (Short,1): Angular_Degree
      ProjectedCSTypeGeoKey (Short,1): Code-3003 (Monte Mario / Italy zone 1)
      ProjLinearUnitsGeoKey (Short,1): Linear_Meter
      End_Of_Keys.
   End_Of_Geotiff.
```

Your image is slightly rotated as you can see from the corner coordinates or from 
`GeoTransform =
  1518761.735050049, 0.1691339168349253, 0.0007792949834319073
  4962486.786306337, 0.0003711921198545058, -0.1690157049981233`

Maybe Google Earth does does not handle the rotation right. Try what happens if you warp the image into north-up
`gdalwarp test.tif test_warped.tif`

**Comment by gpsaliola** [comment]
The map is slightly rotated by 0.0239° and even if I warp the map with GDAL nothing changes in Google Earth.
What version of listgeo are you using? Where can I download it?
Thanks a lot for your support.

**Comment by jratike80** [comment]
I use Windows and libgeotiff is installed by the OSGeo4W installer. The libgeotiff version seems to be 1.7.1-4 and it is marked also as latest in https://github.com/OSGeo/libgeotiff/releases.

**Comment by gpsaliola** [comment]
Thank you, you're so kind. May I ask how do I compile the sources?

**Comment by jratike80** [comment]
No idea, I have never compiled anything, I only use ready made Windows binaries.

**Comment by gpsaliola** [comment]
Ok, thank you very much!
