### ISSUE TITLE
Incorrect transformation compared to gdaltransform, epsg.io & FME

### ISSUE THREAD

**Issue by TJPovey** [OSGeo/gdal#7125]
## Expected behavior and actual behavior.

Note: I am using the MaxRev Gdal .NET Core package, but I believe the issue is within the base Gdal package (or rather me not using it correctly) - correct me if I'm wrong.

When converting points from one coordinate system to EPSG:4979/EPSG4326 using Gdal, I expect the same results / very similar results when running the the command line tool gdaltransform.

Using Gdal NET returns incorrect values, whereas gdaltransform returns the correct values. epsg.io and FME also return very similar results than gdaltransform. GDAL NET has just over 1 meter in difference. Is suspect there is a vertical datum which isn't being assigned within Gdal NET, but I'm unsure how to get it from just an EPSG code.

<html>
<body>

From EPSG:27700 | To EPSG:4979 (or 4326) using GDAL | To EPSG:4979 (or 4326) using gdaltransform/epsg.io/FME
-- | -- | --
X: 330231.2515625854  |  LONG:  -3.047789419352417|  LONG: -3.04778889624274
Y: 376174.72374993586  |  LAT:  53.277941280668884|  LAT: 53.2779570544652
Z: -7.352000006675735  |  ELEV:  -7.352000006675735|  ELEV: -7.35200000667573

</body>
</html>

## Steps to reproduce the problem.
using gdaltransform:
```
gdaltransform -s_srs epsg:27700 -t_srs epsg:4979
Enter X Y [Z [T]] values separated by space, and press Return.
330231.25156258536 376174.72374993586 -7.352000006675735
-3.04778889624274 53.2779570544652 -7.35200000667573
```
using Gdal NET:
```csharp
    GdalBase.ConfigureAll();
    Ogr.RegisterAll();

    var x = 330231.25156258536;
    var y = 376174.72374993586;
    var z = -7.352000006675735;

    var epsg27700 = 27700;
    var epsg4979 = 4979; // same result for 4326


    var inputCS= new SpatialReference(null);
    inputCS.ImportFromEPSG(epsg27700);

    var wgs84 = new SpatialReference(null);
    wgs84.ImportFromEPSG(epsg4979);

    var ct = new CoordinateTransformation(inputCS, wgs84);
    var transformed = new double[3];
    ct.TransformPoint(transformed, x, y, z);
    Console.WriteLine($"long: {transformed[0]}, lat: {transformed[1]}, z: {transformed[2]}");
```

I'm unsure if this is the intended behaviour, or if I need to add a vertical datum since EPSG:4979 needs handling in the vertical datum via Gdal Net which may make the lat/longs correct. 

## Operating system
Windows 10 64 bit

## GDAL version and provenance
Gdal NET 3.6.1
Gdal cli gdaltransform 3.6.2

**Comment by rouault** [comment]
> sing the MaxRev Gdal .NET Core package, but I believe the issue is within the base Gdal package (or rather me not using it correctly) - correct me if I'm wrong.

I'd assume the issue is in this MaxRev package that may ship with an outdated PROJ version and/or lack its grids (cf https://proj.org/resource_files.html#proj-data)

**Comment by jratike80** [comment]
You can make a test and find this file from where your Proj is:
uk_os_OSTN15_NTv2_OSGBtoETRS.tif

Rename the file and you should get less accurate results with all methods.

**Comment by TJPovey** [comment]
Thanks @rouault, testing with GDAL 3.7.0dev-5ce7ba068f, released 2023/01/17 and Proj Rel. 8.2.0, November 1st, 2021, the results are the same as with Gdal net. Although the original gdaltransform results are the correct results as this matches the Ordanance Survey transformation tool (https://www.ordnancesurvey.co.uk/gps/transformation/), which takes into account the ETRS89 geodetic reference frame.

So my question is - how did gdaltransform in 3.6.2, prior to the update return the correct results - did it default to using a certain vertical shift?

**Comment by TJPovey** [comment]
@jratike80 thanks for the info, I'll give this a go

**Comment by TJPovey** [comment]
@jratike80 you were correct - Gdal NET was missing this shift file, adding this and it works as expected. Thanks!
