### ISSUE TITLE
Writing GeoJSONSeq to /vsigzip/ broken in GDAL 3.6+

### ISSUE THREAD

**Issue by arredond** [OSGeo/gdal#7130]
## Expected behavior and actual behavior.

In previous versions of GDAL (testing in 3.3.2 and 3.5.2), writing a gzipped GeoJSONSeq using the `/vsigzip` VSI worked fine:

```bash
ogr2ogr /vsigzip/example.geojsonseq.gz -f GeoJSONSeq example.geojson
```

However, this no longer works in GDAL 3.6.2. The following error is returned:

```
ERROR 1: Write+update (w+) not supported for /vsigzip, only read-only or write-only.
ERROR 4: Failed to create /vsigzip/example.geojsonseq.gz:
ERROR 1: GeoJSONSeq driver failed to create /vsigzip/example.geojsonseq.gz
```
 I suspect this is was introduced in the following 3.6.0 change (#2080):

```
GeoJSONSeq driver:

  - add support for appending features to an existing file (#2080)
```

## Steps to reproduce the problem.

Simply try to convert any file to a zipped GeoJSONSeq using `/vsigzip` and `-f GeoJSONSeq`

## Operating system

Tested in both Ubuntu 20.04.3 and macOS Monterey Version 12.6 with M1 chip

## GDAL version and provenance

Tested on versions 3.6.2 installed using [Homebrew](https://formulae.brew.sh/formula/gdal) (macOS) and on version 3.6.2 (built from source on Amazon Linux 2)

## Extra Question

In the meantime, is there any way of forcing the GeoJSONSeq driver to use the old behavior of writing everything at once instead of attempting to append lines one by one?

**Comment by arredond** [comment]
@rouault second time you blow me away with such a quick fix. Really appreciated.

> Unfortunately no workaround I can think of but to write in a uncompressed file and compress it afterwards

I don't think this is an option for us - we're writing compressed directly because of some storage limitations. That's alright though, happy to wait for the fix to ship before upgrading.

**Comment by rouault** [comment]
Actually there's a workaround:
```
ogr2ogr /vsistdout/ -f GeoJSONSeq  autotest/ogr/data/poly.shp | gzip > out.gz
```

**Comment by sgillies** [comment]
@rouault from my perspective, that's not a workaround, it's the canonical use :smile:  GeoJSON feature sequences isn't a file format, it's a stream of features.
