### ISSUE TITLE
[Docs] OGR_ORGANIZE_POLYGONS info needs to be improved

### ISSUE THREAD

**Issue by agiudiceandrea** [OSGeo/gdal#7145]
## Expected behavior and actual behavior.

The `OGR_ORGANIZE_POLYGONS` configuration option is cited in the [ESRI Shapefile](https://gdal.org/drivers/vector/shapefile.html) doc page in which only the `DEFAULT` value is named.
The description of the other `OGR_ORGANIZE_POLYGONS` configuration option values is missing.

Such option is missing in the [OpenFileGDB](https://gdal.org/drivers/vector/openfilegdb.html) doc page.

**Comment by rouault** [comment]
What is the motivation behind this request ? I'd rather see this as a rather obscure option that should be rarely used.

**Comment by nyalldawson** [comment]
I suspect it's in response to https://twitter.com/totofiandaca/status/1619409200605696000?t=aIHn2gQtqhH-5k7VUK6aGA&s=19

**Comment by rouault** [comment]
Hum, a reproducer dataset would be the first step before concluding one has to mess with OGR_ORGANIZE_POLYGONS :-)

**Comment by agiudiceandrea** [comment]
Actually for the sake of completeness of the GDAL docs.
I saw [this](https://www.facebook.com/pigreco314/posts/pfbid0x3jw1YTqUHeKCBfSWKpwPoMZWN25T8z8EiFb9P9DpXDxsmHESYqttE7UygzT9Qqzl) wondering what is the reason of using OGR_ORGANIZE_POLYGONS option and then I found some pieces of information spread in various places [[1](https://github.com/OSGeo/gdal/issues/1369)] [[2](https://github.com/qgis/QGIS/pull/47705)] [[3](https://gis.stackexchange.com/questions/431106/importing-a-gdb-file-into-postgis-using-ogr2ogr)] [[4](https://gis.stackexchange.com/questions/370739/ogr2ogr-large-gdb-file-to-sqlite-warning-organizepolygons-received-a-polygon)] [[5](https://gdal.org/api/ogrgeometry_cpp.html#_CPPv4N18OGRGeometryFactory16organizePolygonsEPP11OGRGeometryiPiPPKc)], that seems missing in the docs (except in API docs page, where anyway the DEFAULT value is not named).
