### ISSUE TITLE
vsicurl wont get metadata without full download when using S3 pre-signed URL

### ISSUE THREAD

**Issue by artttt** [OSGeo/gdal#7150]
Im moving from GDAL: 3.5.1 to GDAL: 3.6.2

Using GDAL: 3.5.1 im able to for example do

```
gdalinfo /vsicurl/...url to a large cog file.. .tif
```
and quickly get a result with minimal download or memory use

using GDAL: 3.6.2 the same command tries to download the whole file into memory

The same issue appears using any of the following:

`gdalbuildvrt`
`osgeo_utils.samples.validate_cloud_optimized_geotiff`
`rasterio.open`

the issue does NOT occur if using a `/vsis3/` path

## Operating system

Ubuntu 22.04.1 LTS

## GDAL version and provenance

GDAL: 3.6.2
comparing to 
GDAL: 3.5.1

**Comment by rouault** [comment]
Please provide a URL demonstrating the issue

**Comment by artttt** [comment]
Sorry about that. I didn't have a large public COG to hand.

Now im trying with a few public COGs im not replicating the issue. 

Im not sure if its size related ( the public COGs ive found are only about 100MB and the private ones im using are 100GB ) or something else about the files.

I will do a bit of testing over the next day or so to see if i can narrow it down further.

**Comment by artttt** [comment]
I think I now understand what is going on.
Hopefully I can describe this adequately.

```
time env GDAL_NUM_THREADS=1 CPL_CURL_VERBOSE=1 GDAL_HTTP_VERSION=1.1 GDAL_DISABLE_READDIR_ON_OPEN=YES CPL_VSIL_CURL_ALLOWED_EXTENSIONS=tif AWS_NO_SIGN_REQUEST=YES  gdalinfo '/vsicurl/https://copernicus-dem-30m.s3.amazonaws.com/Copernicus_DSM_COG_10_N00_00_E015_00_DEM/Copernicus_DSM_COG_10_N00_00_E015_00_DEM.tif'
```
makes 2 requests
```
> HEAD /Copernicus_DSM_COG_10_N00_00_E015_00_DEM/Copernicus_DSM_COG_10_N00_00_E015_00_DEM.tif HTTP/1.1
Host: copernicus-dem-30m.s3.amazonaws.com
Accept: */*

> GET /Copernicus_DSM_COG_10_N00_00_E015_00_DEM/Copernicus_DSM_COG_10_N00_00_E015_00_DEM.tif HTTP/1.1
Host: copernicus-dem-30m.s3.amazonaws.com
Accept: */*
Range: bytes=0-16383
```

if I add in `CPL_VSIL_CURL_USE_HEAD=NO`

it also makes 2 requests

```
> GET /Copernicus_DSM_COG_10_N00_00_E015_00_DEM/Copernicus_DSM_COG_10_N00_00_E015_00_DEM.tif HTTP/1.1
Host: copernicus-dem-30m.s3.amazonaws.com
Accept: */*

> GET /Copernicus_DSM_COG_10_N00_00_E015_00_DEM/Copernicus_DSM_COG_10_N00_00_E015_00_DEM.tif HTTP/1.1
Host: copernicus-dem-30m.s3.amazonaws.com
Accept: */*
Range: bytes=0-16383
```

using version 3.6.2 -  between these 2 requests there is a delay while i assume the full file is downloaded to memory.
using version 3.5.1 -  between these 2 requests there is this message

```
* Failure writing output to destination
* Closing connection 0
```
So that looks like a bug fix has occurred.

However,

If i move the dataset into my s3 bucket and use a  pre-signed URL gdal seems to ignore `CPL_VSIL_CURL_USE_HEAD` and always do 2 GET requests. With version 3.5.1 the first GET hits the bug and was quick. With version 3.6.2 The first GET tries to download the whole file resulting in the issue im seeing with large files.


A search for old issues with `CPL_VSIL_CURL_USE_HEAD` bring up a few related ones and if i understand correctly s3 presigned urls are either authorised for a GET or a HEAD request not both so that is why `CPL_VSIL_CURL_USE_HEAD` isnt doing anything. 

Now stepping beyond my level of understanding........

Are 2 requests needed? Why not go straight for the second `Range: bytes=0-16383` GET request.

OR

if 2 are needed can the first one be a `Range: bytes=0-0` GET request if its only a replacement for a HEAD request.
