### ISSUE TITLE
SWIGTYPE_p_p_GDALDatasetShadow is missing from version 3.5.3

### ISSUE THREAD

**Issue by timeichfeld-msa** [OSGeo/gdal#7152]
Hello,

I am migrating from GDAL 
<package id="GDAL" version="2.4.4" targetFramework="net452" />

to 
 <package id="GDAL" version="3.5.3" targetFramework="net48" />
 
 but the class SWIGTYPE_p_p_GDALDatasetShadow no longer exists.  
 I tried SWIGTYPE_p_p_GDALRasterBandShadow, but it is not an intPtr and cannot be used with Gdal.wrapper_GDALBuildVRT_objects
 
 Please provide a pointer to the Breaking Change documentation?

**Comment by rouault** [comment]
That SWIGTYPE_p_p_GDALDatasetShadow was used was a bug at the first place. Has GDALBuildVRT() been usable at all from C# at some point ? I would have assumed not, because of missing SWIG typemaps
