### ISSUE TITLE
Missing projection types in MITAB

### ISSUE THREAD

**Issue by UffeKousgaard** [OSGeo/gdal#7161]
mitab_spatialref.cpp is not handling projection types 34 and 35.

34 is "Extended Transverse Mercator", see MapInfoProUserGuide.pdf, chapter "Projection Types List". 5 parameters.

35 is used by Malaysian Coordinate Systems in MAPINFOW.PRJ, but is not listed in the PDF above. 7 parameters.

Both have been in MapInfo since at least version 15 (final 32-bit release).

**Comment by rouault** [comment]
Please provide sample data files using those if possible

**Comment by UffeKousgaard** [comment]
[proj_34.zip](https://github.com/OSGeo/gdal/files/10562147/proj_34.zip)
[proj_35.zip](https://github.com/OSGeo/gdal/files/10562153/proj_35.zip)
