### ISSUE TITLE
valid_range check is applied without scaling factor.

### ISSUE THREAD

**Issue by bertcoerver** [OSGeo/gdal#7167]
## Expected behavior and actual behavior.

I've got a netCDF file with the following band-metadata:

> add_offset_err=0
> calibrated_nt=5
> coordinates=Latitude Longitude
> grid_mapping=spatial_ref
> long_name=250m 16 days NDVI
> NETCDF_DIM_time=16
> NETCDF_VARNAME=ndvi
> orig_add_offset=0
> orig_scale_factor=10000
> scale_factor=0.0001
> scale_factor_err=0
> units=NDVI
> valid_max=1
> valid_min=-0.2
> _FillValue=-9999

When opening this dataset, all of its data gets masked, even though most of its data is valid. Setting the option `HONOUR_VALID_RANGE="NO"` gives the data correctly.

## Steps to reproduce the problem.

The issue is explained more detailed here https://github.com/rasterio/rasterio/discussions/2751

When running this on the file linked below:

```python
with rasterio.open(src_path) as src:
    array = src.read()[0,:,:]
```

`array` contains only -9999, even though most of the data falls between [-0.2, 1].

While doing this return the data as expected.

```python
with rasterio.open(src_path, HONOUR_VALID_RANGE="NO") as src:
    array = src.read()[0,:,:]
```

## Operating system

macOS Ventura 13.2 (M2)

## GDAL version and provenance

GDAL 3.5.2, released 2022/09/02

## File

[MYD13Q1.061.nc.zip](https://github.com/rasterio/rasterio/files/10570136/MYD13Q1.061.nc.zip)

<details><summary>GDAL INFO</summary>
<p>

> Driver: netCDF/Network Common Data Format
> Files: /Users/hmcoerver/Local/7_custom_level_interception/MODIS/MYD13Q1.061.nc
> Size is 296, 295
> Coordinate System is:
> GEOGCRS["WGS 84",
>     DATUM["World Geodetic System 1984",
>         ELLIPSOID["WGS 84",6378137,298.257223563,
>             LENGTHUNIT["metre",1]]],
>     PRIMEM["Greenwich",0,
>         ANGLEUNIT["degree",0.0174532925199433]],
>     CS[ellipsoidal,2],
>         AXIS["geodetic latitude (Lat)",north,
>             ORDER[1],
>             ANGLEUNIT["degree",0.0174532925199433]],
>         AXIS["geodetic longitude (Lon)",east,
>             ORDER[2],
>             ANGLEUNIT["degree",0.0174532925199433]],
>     ID["EPSG",4326]]
> Data axis to CRS axis mapping: 2,1
> Origin = (68.499607048128311,26.001041664331137)
> Pixel Size = (0.001694639445271,-0.001694639445271)
> Metadata:
>   ndvi#add_offset_err=0
>   ndvi#calibrated_nt=5
>   ndvi#coordinates=Latitude Longitude
>   ndvi#grid_mapping=spatial_ref
>   ndvi#long_name=250m 16 days NDVI
>   ndvi#orig_add_offset=0
>   ndvi#orig_scale_factor=10000
>   ndvi#scale_factor=0.0001
>   ndvi#scale_factor_err=0
>   ndvi#units=NDVI
>   ndvi#valid_max=1
>   ndvi#valid_min=-0.2
>   ndvi#_FillValue=-9999
>   NETCDF_DIM_EXTRA={time}
>   NETCDF_DIM_time_DEF={2,6}
>   NETCDF_DIM_time_VALUES={0,16}
>   spatial_ref#crs_wkt=GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AXIS["Latitude",NORTH],AXIS["Longitude",EAST],AUTHORITY["EPSG","4326"]]
>   spatial_ref#geographic_crs_name=WGS 84
>   spatial_ref#GeoTransform=68.49960704812831 0.0016946394452707224 0.0 26.001041664331137 0.0 -0.001694639445270765
>   spatial_ref#grid_mapping_name=latitude_longitude
>   spatial_ref#inverse_flattening=298.257223563
>   spatial_ref#longitude_of_prime_meridian=0
>   spatial_ref#prime_meridian_name=Greenwich
>   spatial_ref#reference_ellipsoid_name=WGS 84
>   spatial_ref#semi_major_axis=6378137
>   spatial_ref#semi_minor_axis=6356752.314245179
>   spatial_ref#spatial_ref=GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AXIS["Latitude",NORTH],AXIS["Longitude",EAST],AUTHORITY["EPSG","4326"]]
>   time#calendar=proleptic_gregorian
>   time#units=days since 2021-08-13 00:00:00
>   time#_FillValue=nan
>   x#axis=X
>   x#long_name=longitude
>   x#standard_name=longitude
>   x#units=degrees_east
>   x#_FillValue=nan
>   y#axis=Y
>   y#long_name=latitude
>   y#standard_name=latitude
>   y#units=degrees_north
>   y#_FillValue=nan
> Corner Coordinates:
> Upper Left  (  68.4996070,  26.0010417) ( 68d29'58.59"E, 26d 0' 3.75"N)
> Lower Left  (  68.4996070,  25.5011230) ( 68d29'58.59"E, 25d30' 4.04"N)
> Upper Right (  69.0012203,  26.0010417) ( 69d 0' 4.39"E, 26d 0' 3.75"N)
> Lower Right (  69.0012203,  25.5011230) ( 69d 0' 4.39"E, 25d30' 4.04"N)
> Center      (  68.7504137,  25.7510823) ( 68d45' 1.49"E, 25d45' 3.90"N)
> Band 1 Block=296x295 Type=Int32, ColorInterp=Undefined
>   NoData Value=-9999
>   Unit Type: NDVI
>   Offset: 0,   Scale:0.0001
>   Metadata:
>     add_offset_err=0
>     calibrated_nt=5
>     coordinates=Latitude Longitude
>     grid_mapping=spatial_ref
>     long_name=250m 16 days NDVI
>     NETCDF_DIM_time=0
>     NETCDF_VARNAME=ndvi
>     orig_add_offset=0
>     orig_scale_factor=10000
>     scale_factor=0.0001
>     scale_factor_err=0
>     units=NDVI
>     valid_max=1
>     valid_min=-0.2
>     _FillValue=-9999
> Band 2 Block=296x295 Type=Int32, ColorInterp=Undefined
>   NoData Value=-9999
>   Unit Type: NDVI
>   Offset: 0,   Scale:0.0001
>   Metadata:
>     add_offset_err=0
>     calibrated_nt=5
>     coordinates=Latitude Longitude
>     grid_mapping=spatial_ref
>     long_name=250m 16 days NDVI
>     NETCDF_DIM_time=16
>     NETCDF_VARNAME=ndvi
>     orig_add_offset=0
>     orig_scale_factor=10000
>     scale_factor=0.0001
>     scale_factor_err=0
>     units=NDVI
>     valid_max=1
>     valid_min=-0.2
>     _FillValue=-9999

</p>
</details>

**Comment by jratike80** [comment]
Is this right source for a reference https://docs.unidata.ucar.edu/netcdf-c/current/attribute_conventions.html?

> If the variable is packed using scale_factor and add_offset attributes (see below), the _FillValue, missing_value, valid_range, valid_min, or valid_max attributes should have the data type of the packed data.

**Comment by rouault** [comment]
I concur the dataset doesn't follow the conventions. Workaround implemented in https://github.com/OSGeo/gdal/pull/7169

**Comment by jratike80** [comment]
Explanation: Because of the following the compressed data should contain integers, so valid_min and valid_max should be integers as well

> The attributes scale_factor and add_offset can be used together to provide simple data compression to store low-resolution floating-point data as small integers in a netCDF dataset.
