### ISSUE TITLE
Using GDAL to open zarr zipstore

### ISSUE THREAD

**Issue by caviere** [OSGeo/gdal#7173]
## Expected behavior and actual behavior.

I expected to be able to open a zarr zipstore and instead it returns this error:
```
ERROR 4: ZARR:"/home/kinya/testing_zipstore/datasets/ESP0025722.zip": No such file or directory
```

## Steps to reproduce the problem.
```
from osgeo import gdal
import os

filepath = "datasets/ESP0025722.zip"
full_filepath = f'ZARR:"{os.path.abspath(filepath}"'
ds = gdal.Open(full_filepath)
    
```
The dataset is from this [link](https://zenodo.org/record/5745520#.Y9zdIhxByV4)
## Operating system

Ubuntu 22.04.1 LTS

## GDAL version and provenance

GDAL 3.4.3, released 2022/04/22

**Comment by jratike80** [comment]
It is a zip. This way I can get output

`gdalinfo /vsizip/ESP0025722.zip`

With my GDAL build I cannot test any further because of `ERROR 1: Decompressor blosc not handled`

**Comment by caviere** [comment]
In my case, when I run gdalinfo, I get the following error:
```
ERROR 4: `ESP0025722.zip' not recognized as a supported file format.
gdalinfo failed - unable to open 'ESP0025722.zip'.
```

**Comment by jratike80** [comment]
And did your command include /vsizip/? `gdalinfo /vsizip/ESP0025722.zip` 
Do you have ZARR driver? You can check it with `gdalinfo --format Zarr`

**Comment by caviere** [comment]
My command did not include /vsizip/. I have the Zarr driver installed, this is what I get for `gdalinfo --format Zarr`:
```
Format Details:
  Short Name: Zarr
  Long Name: Zarr
  Supports: Raster
  Supports: Multidimensional raster
  Supports: Raster subdatasets
  Supports: Open() - Open existing dataset.
  Supports: Create() - Create writable dataset.
  Supports: CreateMultiDimensional() - Create multidimensional dataset.
  Supports: Virtual IO - eg. /vsimem/
  Creation Datatypes: Byte Int16 UInt16 Int32 UInt32 Float32 Float64 CFloat32 CFloat64
```
and so on

**Comment by caviere** [comment]
Okay, when I run `gdalinfo /vsizip/datasets/ESP0025722.zip` I get the following:
```
Driver: Zarr/Zarr
Files: /vsizip/datasets/ESP0025722.zip
Size is 512, 512
Subdatasets:
  SUBDATASET_1_NAME=ZARR:"/vsizip/datasets/ESP0025722.zip":/A/1/0/0
  SUBDATASET_1_DESC=Array /A/1/0/0
  SUBDATASET_2_NAME=ZARR:"/vsizip/datasets/ESP0025722.zip":/A/1/0/1
  SUBDATASET_2_DESC=Array /A/1/0/1
  SUBDATASET_3_NAME=ZARR:"/vsizip/datasets/ESP0025722.zip":/A/1/0/2
  SUBDATASET_3_DESC=Array /A/1/0/2
  SUBDATASET_4_NAME=ZARR:"/vsizip/datasets/ESP0025722.zip":/A/1/0/3
  SUBDATASET_4_DESC=Array /A/1/0/3
  SUBDATASET_5_NAME=ZARR:"/vsizip/datasets/ESP0025722.zip":/A/1/0/4
  SUBDATASET_5_DESC=Array /A/1/0/4
  SUBDATASET_6_NAME=ZARR:"/vsizip/datasets/ESP0025722.zip":/A/1/1/0
  SUBDATASET_6_DESC=Array /A/1/1/0
  SUBDATASET_7_NAME=ZARR:"/vsizip/datasets/ESP0025722.zip":/A/1/1/1
  SUBDATASET_7_DESC=Array /A/1/1/1
  SUBDATASET_8_NAME=ZARR:"/vsizip/datasets/ESP0025722.zip":/A/1/1/2
  SUBDATASET_8_DESC=Array /A/1/1/2

...


Corner Coordinates:
Upper Left  (    0.0,    0.0)
Lower Left  (    0.0,  512.0)
Upper Right (  512.0,    0.0)
Lower Right (  512.0,  512.0)
Center      (  256.0,  256.0)
```
Sample has been truncated

**Comment by jratike80** [comment]
Ok, so no bug. Now you can get more info about the subdatasets by using their names.
gdalinfo "/vsizip/datasets/ESP0025722.zip":/A/1/0/0

 If you need help with usage follow the advice:

> Questions should go to the gdal-dev mailing list at
> https://lists.osgeo.org/mailman/listinfo/gdal-dev
> or other support forums. GitHub issues are for bug
> reports and suggestions for new features.

Maybe you can find some usable examples about how to read subdatasets with Python from https://github.com/OSGeo/gdal/blob/master/autotest/gdrivers/zarr_driver.py.

**Comment by caviere** [comment]
For the python script I still get the same error (ERROR 4) whether I use the relative path:
```
ERROR 4: vsizip/datasets/ESP0025722.zip: No such file or directory
```
Or the absolute path:
```
ERROR 4: vsizip//home/kinya/testing_zipstore/datasets/ESP0025722.zip: No such file or directory
```

**Comment by caviere** [comment]
Thank you @jratike80 , I checked through the link you provided and got the solution which is I should not add quotation marks to the and I should include the `gdal.OF_MULTIDIM_RASTER` option: 

```
ds = gdal.OpenEx(f'ZARR:{filepath}', gdal.OF_MULTIDIM_RASTER)
assert ds is not None
```

**Comment by jratike80** [comment]
Great. I have no experience at all on Zarr so you are now much better than I.
