### ISSUE TITLE
Black edges appear after using "gdal_translate" to reduce the image

### ISSUE THREAD

**Issue by MinluLi** [OSGeo/gdal#7186]
## Expected behavior and actual behavior.

Use gdal_translate tool reduces the image, and the generated image has black edges. If you use mspaint or photoshop to reduce the image, the result is normal.

This problem is related to the size of the input image. If the input image is 4592 * 3056, black edges will appear. If the input image is 7360 * 4912, the result is normal.

Attachments are input images and output images.

## Steps to reproduce the problem.

The command is as follows:
`gdal_translate.exe -of PNG -outsize 128 85 D:/Data/images/DSC00153.JPG D:/Test/0000000000.png`

## Operating system

Win11 64 bit

## GDAL version and provenance

3.6.2

![gdal_translate](https://user-images.githubusercontent.com/8480282/216894668-6766ed51-3040-491a-b935-485bebc78168.png)
![mspaint](https://user-images.githubusercontent.com/8480282/216894701-60cd9a68-cc74-4e2e-bb82-5e02f0ea8d25.png)
![DSC00153](https://user-images.githubusercontent.com/8480282/216894830-79eb9f66-85e6-4e79-9183-d3b6d099d00b.JPG)

**Comment by jratike80** [comment]
Downsampling is picking by default the closest overview as source data. For JPEG the overviews are computed from the JPEG automatically based on the structure of the JPEG data stream. I guess that this automatic overview system for JPEG data creates black fills into blocks sometimes. GDAL finds these overviews from your test image:
`Overviews: 2296x1528, 1148x764, 574x382`

You will get the result that you wish by discarding the JPEG overviews

`gdal_translate.exe -of PNG -outsize 128 85 -ovr none test.jpg test_out.png`

**Comment by MinluLi** [comment]
> 

Thank you for your reply. The problem has been solved in your way.
