### ISSUE TITLE
WFS: paging not detected, but executed anyway

### ISSUE THREAD

**Issue by tobwen** [OSGeo/gdal#719]
## Expected behavior and actual behavior.
This issue stays in connection with #720, since the same WFS is affected.

When trying to download data from this WFS, ogr2ogr reports that no paging is supported. But actually, paging works and data gets downloaded using STARTINDEX/COUNT.

> WFS: https://www.wfs.nrw.de/geobasis/wfs_nw_alkis_vereinfacht?SERVICE=WFS&REQUEST=GetCapabilities
> HTTP: Fetch(https://www.wfs.nrw.de/geobasis/wfs_nw_alkis_vereinfacht?SERVICE=WFS&REQUEST=GetCapabilities)
> HTTP: libcurl/7.52.1 GnuTLS/3.5.8 zlib/1.2.8 libidn2/0.16 libpsl/0.17.0 (+libidn2/0.16) libssh2/1.7.0 nghttp2/1.18.1 librtmp/2.3
> WFS: No paging support
> WFS: No ImplementsStandardJoins support
> WFS: No transaction support

## Steps to reproduce the problem.
`ogr2ogr --debug ON -f GML /vsigzip/alkis_nrw_TN_2018-01-01.gml.gz "WFS:https://www.wfs.nrw.de/geobasis/wfs_nw_alkis_vereinfacht" "ave:Nutzung" --config OGR_WFS_PAGE_SIZE 1000 --config GDAL_HTTP_UNSAFESSL`

## Operating system
Microsoft Windows 7, Version 6.1.7601 (64-bit)

## GDAL version and provenance
GDAL 2.4.0dev, released 2018/99/99 from OSGeo4W (64-bit)

**Comment by rouault** [comment]
The OGR WFS driver is consistent with the fact that the server declares it does not support paging:
```
    <ows:Constraint name="ImplementsResultPaging">
      <ows:NoValues/>
      <ows:DefaultValue>FALSE</ows:DefaultValue>
    </ows:Constraint>
```

**Comment by rouault** [comment]
The server indeed seems to implements paging, except it forgets to declare it in its capabilities. Should be reported to the server

**Comment by tobwen** [comment]
:+1: I'm closing this, since it's not an issue of OGR. And I'll contact the provider.
