### ISSUE TITLE
Request Feature: custom metadata when writting with GPX driver

### ISSUE THREAD

**Issue by Binnette** [OSGeo/gdal#7190]
## Actual behavior.

GPX schema allows to add 'metadata' in GPX files: https://www.topografix.com/GPX/1/1/#type_metadataType

```
<metadata>
    <name> xsd:string </name>
    <desc> xsd:string </desc>
    <author> personType </author>
    <copyright> copyrightType </copyright>
    <link> linkType </link>
    <time> xsd:dateTime </time>
    <keywords> xsd:string </keywords>
    <bounds> boundsType </bounds>
    <extensions> extensionsType </extensions>
</metadata>
```

But GDAL do not provide a way to add those metadata in created GPX files.

## Expected behavior

GDAL should support exporting metadata to GPX file.

**Comment by rouault** [comment]
Support added in https://github.com/OSGeo/gdal/pull/7191

**Comment by Binnette** [comment]
Perfect thanks
