### ISSUE TITLE
Seg fault in BuildOverviews with COMPRESS_OVERVIEW when XSize is 1

### ISSUE THREAD

**Issue by jontwo** [OSGeo/gdal#7194]
## Expected behavior and actual behavior.

I'm writing a Python unit test that calls BuildOverviews and when COMPRESS_OVERVIEW config option is set to LZW and the raster XSize is 1 (with larger YSize) there is a segmentation fault.

## Steps to reproduce the problem.

Repro case, simplified from a program that uses the "tiff directory thrashing" method described [here](https://trac.osgeo.org/gdal/ticket/5067). The error occurs when calling BuildOverviews on a x.tif.ovr file that is 1 pixel wide.

```
import numpy as np
from osgeo import gdal


xsize = 1
ysize = 5
gdal.SetConfigOption('COMPRESS_OVERVIEW', 'LZW')

gdal.SetConfigOption('CPL_DEBUG', 'ON')
path = r"c:\temp\ovr_test.tif"
dtype = gdal.GDT_Byte
arr = np.ones((ysize, xsize))
raster_create_opts = (path, arr.shape[-1], arr.shape[-2], 1, dtype)
raster_driver = gdal.GetDriverByName('GTiff')
ds = raster_driver.Create(*raster_create_opts)
rb = ds.GetRasterBand(1)
rb.WriteArray(arr)
ds.FlushCache()
del rb, ds
ds = gdal.OpenEx(path)
ds.BuildOverviews('nearest', [2])
del ds
ds = gdal.OpenEx(path + ".ovr")
# seg fault happens here
ds.BuildOverviews('nearest', [2])
del ds

ds = gdal.OpenEx(path)
print(f"Band count: {ds.RasterCount} size: {ds.RasterXSize}x{ds.RasterYSize}")
rb = ds.GetRasterBand(1)
for i in range(rb.GetOverviewCount()):
    ovr = rb.GetOverview(i)
    print(f"Overview {i} size: {ovr.XSize}x{ovr.YSize}")
```

If you comment out the COMPRESS_OVERVIEW config option or change `xsize` to 3 or more, the script runs through without error.

## Operating system

Windows 10 Pro Build 19045.2486 + Python 3.9.5
(Have also repro'd on Ubuntu 22.04.1 LTS + Python 3.10.6)

## GDAL version and provenance

GDAL 3.5.2, released 2022/09/02 (from OSGeo4W)
(Ubuntu GDAL 3.5.1, built using a wheel recipe based on https://github.com/youngpm/gdalmanylinux)

**Comment by rouault** [comment]
Even after looking at the ticket you point to, I don't understand what you mean by "a program that uses the "tiff directory thrashing" method". Please provide the input file or a way to regenerate it in a simple way

I've tried the following on GDAL master and it works fine:
```
gdal_create -outsize 1 16000 test.tif -co COMPRESS=LZW
gdaladdo --config COMPRESS_OVERVIEW LZW -ro test.tif 2
gdaladdo --config COMPRESS_OVERVIEW LZW -ro test.tif.ovr 2
```

**Comment by jratike80** [comment]
I can confirm that Python dies at the line that you have marked. Tested with OSGeo4W, GDAL 3.6.2, Python 3.9.5. Gdaladdo runs successfully and creates external overview  ovr_test.tif.ovr.ovr.ovr that contains one pixel but the filesize is rather big, 16554 bytes.

**Comment by rouault** [comment]
ah, sorry I misunderstood the message and thought that the script required an input dataset to fetch somewhere. I can also reproduce

**Comment by rouault** [comment]
gdal_create -outsize 1 5 test.tif
gdaladdo --config COMPRESS_OVERVIEW LZW -ro test.tif 2
gdaladdo --config COMPRESS_OVERVIEW LZW -ro test.tif.ovr 2

**Comment by rouault** [comment]
fix in https://github.com/OSGeo/gdal/pull/7195

**Comment by jontwo** [comment]
Many thanks for the quick fix!
