### ISSUE TITLE
NetCDF raster is displayed wrongly in QGIS 3.22

### ISSUE THREAD

**Issue by krirein** [OSGeo/gdal#7199]
## Expected behavior and actual behavior.
A WRF NetCDF-raster file ("OUTPUT FROM WRF V3.9.1 MODEL") is wrongly projected in QGIS 3.22. After reading https://github.com/qgis/QGIS/issues/47158 I chose to set
IGNORE_XY_AXIS_NAME_CHECKS=YES
when adding the file, but this did not help.

I got some help here: https://github.com/qgis/QGIS/issues/51758 but I was adviced to create a new issue report here in the GDAL repository.

The upper left corner of my layer has been assigned with coordinates (0,0), but should have been (69.628°N, 17.9877°E) Screenshot is added below
![image](https://user-images.githubusercontent.com/124601641/217341628-eb3e8ebe-9ffb-4962-8a8d-a2614ba6defb.png)

## Steps to reproduce the problem.

1. From the top menu in QGIS choose: Layer - Add Layer - Add raster layer

2. Load the netcdf file (attached below as zip-file) and set IGNORE_XY_AXIS_NAME_CHECKS=YES
[d04_hgt.zip](https://github.com/OSGeo/gdal/files/10678546/d04_hgt.zip)

3. Press Add, select the variable(s) you would like to visualize and press Add layers.

4. Double-click on the added layer and in the Source-panel set the Assigned CRS to WGS 84 and press Apply.

The layer will now be wrongly projected.

## Operating system

Windows 11 version 21H2, 64 bit

## GDAL version and provenance

GDAL 3.5.1 in QGIS 3.22.10
GDAL 3.6.2 in QGIS 3.22.16

**Comment by rouault** [comment]
This is a rather complex dataset, where the longitude and latitude arrays are time dependent (although they seem to have the same values in the different time slices, luckily). GDAL does its best and reports a GEOLOCATION array:
```
Geolocation:
  GEOREFERENCING_CONVENTION=PIXEL_CENTER
  LINE_OFFSET=0
  LINE_STEP=1
  PIXEL_OFFSET=0
  PIXEL_STEP=1
  SRS=GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AXIS["Latitude",NORTH],AXIS["Longitude",EAST],AUTHORITY["EPSG","4326"]]
  X_BAND=1
  X_DATASET=NETCDF:"d04_hgt.nc":XLONG
  Y_BAND=1
  Y_DATASET=NETCDF:"d04_hgt.nc":XLAT
```
It's say it should be a QGIS improvement to use a GDAL GEOLOCATION array with a warped VRT to on-the-fly rectify the dataset.
Closing as not a GDAL bug but a QGIS improvement to do
