### ISSUE TITLE
gdal_translate does not use OSR_USE_NON_DEPRECATED option when assigned inline 

### ISSUE THREAD

**Issue by trey-stafford** [OSGeo/gdal#7210]
## Expected behavior and actual behavior.

Expected behavior: I expect to be able to use the `OSR_USE_NON_DEPRECATED=NO`
setting inline with `gdal_translate` as described here:
https://github.com/OSGeo/gdal/blame/master/doc/source/user/configoptions.rst#L28-L31

Actual behavior: `gdal_translate` ignores this option when the option is set
inline and uses the non-deprecated CRS instead.

Note: Using `gdal_translate`'s `--config` arg to set the
`OSR_USE_NON_DEPRECATED` option _does_ work. Additionally, I have confirmed that
exporting the setting (`export OSR_USE_NON_DEPRECATED=NO`) also works. 

Given this is the case, I _think_ the issue is either:

*  The documentation for setting options is incorrect (or misleading)
*  or `gdal_translate` is not passing the option along to it's subprocesses as it should. 

## Steps to reproduce the problem.

I encountered this issue using data from [NSIDC's EASE-Grid Sea Ice Age, Version 4](https://nsidc.org/data/nsidc-0611/versions/4) dataset. Specifically, `iceage_nh_12.5km_20210101_20211231_v4.1.nc`. This NetCDF file has data in `EPSG:3408` (note that the EPSG registery has incorrectly marked this CRS as deprecated. The associated replacement is *NOT* correct. We are addressing that issue with the maintainers of EPSG separately).

Explicitly request that `gdal_translate` uses `EPSG:3408` (`-a_srs "EPSG:3408"`) and use the `OSR_USE_NON_DEPRECATED` setting:
```
$ OSR_USE_NON_DEPRECATED=NO gdal_translate -b 1 -a_srs "EPSG:3408" NETCDF:iceage_nh_12.5km_20210101_20211231_v4.1.nc:age_of_sea_ice age_of_seai
ce.tif
ERROR 1: unhandled axis direction: UNKNOWN
Input file size is 722, 722
0...10...20...30...40...50...60...70...80...90...100 - done.
$ echo $?
0
```

Note that gdal does raise an error message about unhandled axis direction, but the exit code is 0 and the output file is created successfully. However, the CRS is incorrect. `gdalinfo` indicates the CRS is `WGS 84 / NSIDC EASE-Grid 2.0 North` NOT the expected `NSIDC EASE-Grid North`.

```
$  gdalinfo age_of_seaice.tif
Driver: GTiff/GeoTIFF
Files: age_of_seaice.tif
Size is 722, 722
Coordinate System is:
PROJCRS["WGS 84 / NSIDC EASE-Grid 2.0 North",
    BASEGEOGCRS["WGS 84",
...
<outputcut for brevity>
```

## Operating system

```
$  cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.5 LTS"

```

## GDAL version and provenance

```
$ conda list gdal
# packages in environment at /home/trst2284/miniconda3/envs/gdal:
#
# Name                    Version                   Build  Channel
gdal                      3.6.2           py311hadb6153_6    conda-forge
libgdal                   3.6.2                h8c90c07_6    conda-forge
```

**Comment by jratike80** [comment]
Is that syntax something that is specific to bash? Is it worth documenting if there are other ways to set the config options? Does it have any advantage over `--config ...`?

**Comment by rouault** [comment]
I can't manage to create an account on this darned platform. @trey-stafford Can you post the output of "ncdump -h iceage_nh_12.5km_20210101_20211231_v4.1.nc" ?

**Comment by trey-stafford** [comment]
@jratike80 [the documentation](https://github.com/OSGeo/gdal/blame/master/doc/source/user/configoptions.rst#L21-L22) notes:

> It can be set in the environment on Unix (bash/bourne) shell like this

I don't think this method of inline assignment has any advantage over using `--config`, but it's [included as an option in the documentation](https://github.com/OSGeo/gdal/blame/master/doc/source/user/configoptions.rst#L28-L31). I encountered the issue described above because of this. I would probably advise removing this suggestion from the documentation if users should be directed to use `--config`.

**Comment by trey-stafford** [comment]
@rouault Apologies for frustrations over obtaining the data. If you have problems in the future and would like to work with data from NSDIC, please don't hesitate to reach out to nsidc@nsidc.org.

Here's the output of `ncdump`:

```
netcdf iceage_nh_12.5km_20210101_20211231_v4.1 {
dimensions:
        x = 722 ;
        y = 722 ;
        time = UNLIMITED ; // (52 currently)
variables:
        float x(x) ;
                x:standard_name = "projection_x_coordinate" ;
                x:coverage_content_type = "coordinate" ;
                x:long_name = "x" ;
                x:units = "meters" ;
                x:axis = "X" ;
        float y(y) ;
                y:standard_name = "projection_y_coordinate" ;
                y:coverage_content_type = "coordinate" ;
                y:long_name = "y" ;
                y:units = "meters" ;
                y:axis = "Y" ;
        double time(time) ;
                time:standard_name = "time" ;
                time:units = "days since 1970-01-01" ;
                time:calendar = "julian" ;
                time:axis = "T" ;
        int crs ;
                crs:grid_mapping_name = "lambert_azimuthal_equal_area" ;
                crs:longitude_of_projection_origin = 0LL ;
                crs:false_easting = 0LL ;
                crs:false_northing = 0LL ;
                crs:long_name = "EASEgrid_N12.5km_pole_centered" ;
                crs:latitude_of_projection_origin = 90LL ;
                crs:srid = "urn:ogc:def:crs:EPSG::3408" ;
                crs:proj4text = "+proj=laea +lat_0=90 +lon_0=0 +x_0=0 +y_0=0 +a=6371228 +b=6371228 +units=m +no_defs" ;
                crs:crs_wkt = "PROJCS[\"NSIDC EASE-Grid North\",GEOGCS[\"Unspecified datum based upon the International 1924 Authalic Sphere\",DATUM[\"Not_specified_based_on_International_1924_Authalic_Sphere\",SPHEROID[\"International 1924 Authalic Sphere\",6371228,0,AUTHORITY[\"EPSG\",\"7057\"]],AUTHORITY[\"EPSG\",\"6053\"]],PRIMEM[\"Greenwich\",0,AUTHORITY[\"EPSG\",\"8901\"]],UNIT[\"degree\",0.01745329251994328,AUTHORITY[\"EPSG\",\"9122\"]],AUTHORITY[\"EPSG\",\"4053\"]],UNIT[\"metre\",1,AUTHORITY[\"EPSG\",\"9001\"]],PROJECTION[\"Lambert_Azimuthal_Equal_Area\"],PARAMETER[\"latitude_of_center\",90],PARAMETER[\"longitude_of_center\",0],PARAMETER[\"false_easting\",0],PARAMETER[\"false_northing\",0],AUTHORITY[\"EPSG\",\"3408\"],AXIS[\"X\",UNKNOWN],AXIS[\"Y\",UNKNOWN]]" ;
        ubyte age_of_sea_ice(time, y, x) ;
                age_of_sea_ice:short_name = "ice age" ;
                age_of_sea_ice:long_name = "age_of_sea_ice" ;
                age_of_sea_ice:standard_name = "age_of_sea_ice" ;
                age_of_sea_ice:units = "year" ;
                age_of_sea_ice:flag_values = 20UB, 21UB ;
                age_of_sea_ice:grid_mapping = "crs" ;
                age_of_sea_ice:comment = "Ice of this age is up-to-this-number of years old.  A value of 1 indicates first-year ice, which is up to one year old.  Age value of 20 indicate the dilated land mask.  Age values of 21 indicate ocean where ice age cannot be calculated because the ice motion is not provided near coasts and in lakes" ;
        float latitude(y, x) ;
                latitude:standard_name = "latitude" ;
                latitude:units = "degrees_north" ;
        float longitude(y, x) ;
                longitude:standard_name = "longitude" ;
                longitude:units = "degrees_east" ;

// global attributes:
                :version = "4.1" ;
                :release_date = "May 2022" ;
                :Conventions = "CF-1.4" ;
                :dataset_doi = "10.5067/UTAV7490FEPB" ;
}
```

If you would like to work with the data yourself, I have attached it here (in a zip file):
[data.zip](https://github.com/OSGeo/gdal/files/10702061/data.zip)

**Comment by rouault** [comment]
> I don't think this method of inline assignment has any advantage over using `--config`

ok, removed per 3a60aa339d36239f5f5eb5447cbf34a008ecf361

The "ERROR 1: unhandled axis direction: UNKNOWN" error actually comes from the WKT that is invalid and uses a UNKNOWN axis direction, which isn't a valid keyword in WKT1. Older GDAL versions were tolerant to it. PROJ is stricter now, but should probably be made more tolerant and just issue a warning. The inability to parse the WKT is not fatal from the point of view of the driver, hence gdal_translate returns a success code. Either point, strict vs tolerant, has its pros & cons, so I won't change this behavior.

**Comment by trey-stafford** [comment]
@rouault Great, thanks! I appreciate your prompt replies and additional details about the error message I was getting. I think we can probably consider this issue closed now.
