### ISSUE TITLE
CAD: undefined behaviour due to left shift

### ISSUE THREAD

**Issue by rouault** [OSGeo/gdal#722]
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=9151
```
io.cpp:589:34: runtime error: left shift of 78 by 28 places cannot be represented in type 'int'
--
  | #0 0x966e1f in CADBuffer::ReadUMCHAR() gdal/gdal/ogr/ogrsf_frmts/cad/libopencad/dwg/io.cpp:589:34
```

We should likely mask the value before shifting so that no bits are lost

**Comment by BishopGIS** [comment]
Do you mean this?

```c++
    int nOffset = 0;
    for(unsigned char i = 0; i < nMCharBytesCount; ++i)
    {
        long nVal = aMCharBytes[i];
        result += nVal << nOffset;
        nOffset += 7;
    }
```

here https://github.com/OSGeo/gdal/blob/master/gdal/ogr/ogrsf_frmts/cad/libopencad/dwg/io.cpp#L586-L591 
and here https://github.com/OSGeo/gdal/blob/master/gdal/ogr/ogrsf_frmts/cad/libopencad/dwg/io.cpp#L630-L635

**Comment by rouault** [comment]
> Do you mean this?

Yes. I believe the reason is that nVal is *signed* , which causes to trigger https://stackoverflow.com/questions/3784996/why-does-left-shift-operation-invoke-undefined-behaviour-when-the-left-side-oper
If you operate on a unsigned type, that should be fine

**Comment by rouault** [comment]
And for aMCharBytes[i] << something , as aMCharBytes[i] is unsigned char, the type promotion rules promote it to a signed int, not a unsigned int...

**Comment by BishopGIS** [comment]
I little confused, so the right solution is to use **unsigned long**?

```c++
    int nOffset = 0;
    for(unsigned char i = 0; i < nMCharBytesCount; ++i)
    {
        unsigned long nVal = aMCharBytes[i];
        result += nVal << nOffset;
        nOffset += 7;
    }
```

**Comment by rouault** [comment]
> the right solution is to use unsigned long?

I think so.
You should be able to reproduce/check by building GDAL with -fsanitize=undefined
