### ISSUE TITLE
Input to PixelFunctionType includes all ComplexSource, regardless of DstRect

### ISSUE THREAD

**Issue by zedrdave** [OSGeo/gdal#7223]
## Expected behavior and actual behavior.

I have a large (>2000) number of rasters produced by processing large sources tile-by-tile. The rasters have some (limited) overlap, that we would like to handle in a specific way.

To this end, we are generating a VRT, and providing a (Numba) Python `PixelFunctionType` to each `VRTDataset`.

Things work well when for smaller numbers of rasters, but when the number reaches 1000, Numba crashes, due to the fact that it cannot handle tuples with more than 1000 elements.

GDAL seems to be calling the `PixelFunctionType` function with every single layer, regardless of `DstRect`, resulting in a large number of empty arrays (filled with `nodata` value) and only a few (or sometimes even no) arrays containing data.

This happens, regardless of whether I use `gdalwarp` or `gdal_translate` to generate the mosaic'ed tif.

Even though I have applied a temporary workaround by filtering the `in_arr` argument in a non-Numba function to remove all-nodata arrays, before calling the Numba code, this seems hugely suboptimal.

## Steps to reproduce the problem.

VRT file looks like this:
 
```
<VRTDataset rasterXSize="58786" rasterYSize="9222">
 <SRS dataAxisToSRSAxisMapping="1,2”>[…]</SRS>
 <GeoTransform> -7.9902911092382642e+06,  4.6331271652776735e+02,  0.0000000000000000e+00,  2.2618926820882889e+06,  0.0000000000000000e+00, -4.6331271652773665e+02</GeoTransform>
 <VRTRasterBand subClass="VRTDerivedRasterBand" dataType="Float32" band="1" NoDataValue="0" blockXSize="128" blockYSize="128">
   <PixelFunctionType>test.test</PixelFunctionType><PixelFunctionArguments nodata="0" /><PixelFunctionLanguage>Python</PixelFunctionLanguage>
   <NoDataValue>0</NoDataValue>
   <HideNoDataValue>1</HideNoDataValue>
   <ColorInterp>Gray</ColorInterp>
   <ComplexSource>
     <SourceFilename relativeToVRT="1">././test_vrt/0a06211d1ceccd06aff9a5a50f5e70b5.tif</SourceFilename>
     <SourceBand>1</SourceBand>
     <SourceProperties RasterXSize="568" RasterYSize="544" DataType="Float32" BlockXSize="256" BlockYSize="256" />
     <SrcRect xOff="0" yOff="0" xSize="568" ySize="544" />
     <DstRect xOff="52791" yOff="4881" xSize="568" ySize="544" />
     <NODATA>0</NODATA>
   </ComplexSource>
   <ComplexSource>
     <SourceFilename relativeToVRT="1">././test_vrt/0a120c177147927bc0bd8c766907e65f.tif</SourceFilename>
     <SourceBand>1</SourceBand>
     <SourceProperties RasterXSize="556" RasterYSize="544" DataType="Float32" BlockXSize="256" BlockYSize="256" />
     <SrcRect xOff="0" yOff="0" xSize="556" ySize="544" />
     <DstRect xOff="24236" yOff="3796" xSize="556" ySize="544" />
     <NODATA>0</NODATA>
   </ComplexSource>
[…] 
[~2000 ComplexSource elements]
```

with a Python function:

```
@nb.jit(cache=True, parallel=True, nopython=True, nogil=True)
def test(in_arr, out_arr, xoff, yoff, xsize, ysize, raster_xsize, raster_ysize, buf_radius, gt, nodata):
```

Running gdalwarp:
`gdalwarp test.vrt test.tif -co TILED=TRUE -co NUM_THREADS=ALL_CPUS --config GDAL_VRT_ENABLE_PYTHON YES`
will send tuples of length 2000 (or whatever the number of `ComplexSource` elements is), resulting in an error if the function is using Numba.

## Operating system

MacOs 13.1 (22C65)

## GDAL version and provenance

GDAL 3.4.1, released 2021/12/27

**Comment by rouault** [comment]
implementation in https://github.com/OSGeo/gdal/pull/7243

**Comment by zedrdave** [comment]
@rouault Thanks a lot for the fast response to this. Looking forward to testing it.

BTW, on a somewhat related note: it's been a bit difficult to figure out, from the doc, what the recommended workflow for mosaicing such a VRT would be: `gdalwarp` or `gdal_translate`…

Our use-case is the simplest one: no format conversion (tif to tif) and no reprojection (all sources have the same CRS, and expecting output in that same CRS)…

I found a number of sources variously recommending to use `gdalwarp` or `gdal_translate` for speed (I'd expect the product to be bit-for-bit identical). But counter-intuitively, our tests seem to show gdalwarp to be faster (might be a matter of tweaking RAM/CPU options).

Did I miss any discussion of this in the doc?

**Comment by rouault** [comment]
generally gdal_translate is faster (I can't really thing of a scenario where it isn't) than gdalwarp. But the derived VRT band is perhaps an exception. This might depend on the shape of the blocks queried through gdal_translate and gdalwarp. Perhaps there are more friendly in the gdalwarp use case. Hard to predict without close analysis (breaking with debugger...)
