### ISSUE TITLE
Tiling a raster with a shapefile results in lost pixels

### ISSUE THREAD

**Issue by RobM-RMU** [OSGeo/gdal#7226]
I have a large raster at 10 cm resolution that I want to tile into square 1 km tiles using a shapefile. If the tile edges are perfectly "on the grid", meaning that the edge of the shape is coincident with the edge of the 10 cm pixel (e.g., XXXXXX.0000000 or XXXXXX.100000) then everything is fine.

However, if the tile is shifted by even a nanometer, a precision which cannot be investigated in any GIS, a line of pixels will be lost from the edge of the affected tile. Tellingly, no pixels are ever lost from diagonal lines, and they are definitely _not_ "on the grid". Therefore, the solution that was found to fix the issue of missing pixels was to rotate all tiles by a miniscule amount (e.g., 0.0001 degrees). Then the pixels reappear. Another solution is to create the shapefile cleanly, but sometimes shapefiles are received from other parties and after being through a few different GIS's or CRS's they might gain some "noise" and are no longer perfect.

So the statement is:

**GDAL will generate tiles with missing pixels 
IF:         tile edges are perfectly north-south/east-west
AND:    tile vertices are not exactly on the grid**

Example of four tile corners where the tile vertices are not perfectly (XXXXXXXX.000000000000, YYYYYYYYYY.00000000000)

![Unrotated cut shapefiles](https://user-images.githubusercontent.com/125090909/218200496-7f9a6752-6692-4897-bbe2-e33fc404b7df.png)

The same tiles after individually rotating each shape around its centroid by 0.0001 degrees:

![Rotated cut shapefiles](https://user-images.githubusercontent.com/125090909/218200545-d2d0c5af-502a-4f75-aa55-7842d152a67d.png)

-->

## Expected behavior and actual behavior.

I expect a pixel to fall into either one tile or the other, based on its centroid. Instead, some pixels are lost altogether, even though they clearly fall within a cut shape.

## Steps to reproduce the problem.

For example, generate a fishnet in any GIS and shift it manually by a random amount. Use that to tile a raster, and pixels will be missing.
The command I am using is: gdalwarp -co GTiff -co "COMPRESS=LZW" -cutline [tiles shapefile] -cwhere [shapefile field] -crop_to_cutline [vrt] [output tiles]

## Operating system

Windows Server 2016 Datacenter, 64-bit

## GDAL version and provenance

GDAL 3.4.3, not sure of provenance

**Comment by rouault** [comment]
without an exact reproducer, difficult to confirm, but https://github.com/OSGeo/gdal/pull/7245 should hopefully fix your issue

**Comment by RobM-RMU** [comment]
I did not have a chance to respond, so apologies for reopening. The matter is confusing and difficult to troubleshoot. So:

1.	We start with a 0.1 m resolution mosaic generated by _gdal_translate_ that ends up with a world file that looks like this, with nano and pico-meter inaccuracies: 
![Original raster world file](https://user-images.githubusercontent.com/125090909/219801062-f27673e0-157d-4929-bbab-4ed033ffc0d2.png)

2.	Then I extract a small tile from this larger raster with _gdal_warp_, which generates this world file:
![Tile world file](https://user-images.githubusercontent.com/125090909/219801563-f6ee27dd-0cc5-44b5-bacc-35ad1cbcae69.png)

3.	I can’t say whether that is good or not -  I don’t think so because I would wish for it to be perfect, but close enough I’d think. This is how it looks in GIS:
![Original tile in GIS](https://user-images.githubusercontent.com/125090909/219801588-c97037a7-72a6-486e-a76d-89f39918008b.png)

4.	I create a fishnet in Arc GIS to use as a cut shapefile, with vertices as perfect as I can make them:
![Fishnet attributes](https://user-images.githubusercontent.com/125090909/219801605-7c78a04c-5eed-4e46-ad11-470a453121c3.png)
![Original tile in GIS with fishnet](https://user-images.githubusercontent.com/125090909/219801623-8083c3d5-43ac-4a80-a173-9c9741edd2b3.png)

5.	Then I tile or crop into four pieces using gdal_warp, and this is the result (I adjusted the colors to make it clearer). You can see a vertical line of missing pixels (but not horizontal in this case). There is also a line of Band 4 pixels (no data, but appear black in the image) along the right and top edges, but can probably leave those for the time being.:
![Tiled tile with missing pixels](https://user-images.githubusercontent.com/125090909/219801645-07570df5-760c-410b-ac49-622539378acc.png)

6.	Any mismatch is less than 0.1% of pixel size, so I am not sure what the ticket meant that you referenced.
![Zoomed missing pixels](https://user-images.githubusercontent.com/125090909/219802234-5f51c57c-a744-4748-8a2a-45ce586bf658.png)

7.	I rotated the fishnet by a random amount and ran _gdal_warp_ again. 
![Original tile in GIS with rotated fishnet](https://user-images.githubusercontent.com/125090909/219801718-0ddec3da-cdcc-4cd7-a564-5dfe074d8361.png)

8.	I was going to show you then that now there would be no missing pixels, but there are… That is the painful nature of this issue. But at least apart from that once central band of missing pixels, elsewhere along these diagonal lines everything comes together properly, including south of the central point where previously there _was_ a line of missing pixels: if a pixel centroid falls inside a cut shape there it is included and that is how I would expect gdal to operate, irrespective of any micro or nanometer inaccuracies in the origin, cell size and cut shapes. (Note that there are No Data pixels along the edges of these rotated tiles that I have made transparent.)
![Zoomed missing pixels after rotation](https://user-images.githubusercontent.com/125090909/219801896-d8387c9f-5491-49b9-88c0-8fc3b2f47f1f.png)

Thanks for your help.

**Comment by jratike80** [comment]
I wonder if target aligned pixels `-tap` option would help.

**Comment by RobM-RMU** [comment]
Thank you for the comment. I wasn’t aware of the -tap option but will try it out.

**Comment by jratike80** [comment]
-tap may prevent empty pixels to appear in the rotated case. It may not have an effect in the non-rotated use case but if you try it, notice that the target aligned extents are multiples of the pixel size and may not match with your clipping polygons.
