### ISSUE TITLE
Allow @ path in gdal_rasterize -sql 

### ISSUE THREAD

**Issue by PostholerCom** [OSGeo/gdal#7232]
Some utilities allow you to use the -sql switch with a path to an sql file, such as:
-sql @/some/path/to/source.sql

It would be a nice feature if gdal_rasterize would do this. It can be rather cumbersome to paste the whole query into the command line.

3.6.2

**Comment by jratike80** [comment]
Have you tried `--optfile` as documented in https://gdal.org/programs/raster_common_options.html#raster-common-options?

**Comment by PostholerCom** [comment]
> Have you tried `--optfile` as documented in https://gdal.org/programs/raster_common_options.html#raster-common-options?

@jratike80 it throws the same error as it does on the command line:

`ERROR 1: ERROR:  syntax error at or near "@/"
LINE 1: @/path/to/source.sql`

**Comment by jratike80** [comment]
Please write the whole command and the content of the optfile. The real source data and the exact SQL is not relevant if you do not want to reveal those. You can test for example with the Natural Earth GeoPackage datasets https://www.naturalearthdata.com/.
