### ISSUE TITLE
MITAB, projection 35, 7th parameter

### ISSUE THREAD

**Issue by UffeKousgaard** [OSGeo/gdal#7236]
TAB files using projection 35 has 7 projection parameters, but the original MAP file header had only room for 6 parameters. The 7th is stored in the extended header block, location hex 0268. The attached sample file shows this.

**Comment by UffeKousgaard** [comment]
[proj_35_77.zip](https://github.com/OSGeo/gdal/files/10717386/proj_35_77.zip)

**Comment by rouault** [comment]
> The 7th is stored in the extended header block, location hex 0268.

how did you figure that out ? :-) fix in https://github.com/OSGeo/gdal/pull/7237

**Comment by UffeKousgaard** [comment]
I knew from this document (https://www.routeware.dk/mitab/notes.html), that there is only room for 6 parameters, so I wondered where the 7th one would go. Looking at your changes for implementing projection type 35, I assumed you did not handle this issue. Finally I edited the MIF file, imported it into MapInfo and looked at the MAP file, to see where the "77" went. We still keep mitab 1.7.0 DLL updated, since mitab 2 do not have the DLL interface anymore. At some point we may start working on a DLL based upon mitab 2.
