### ISSUE TITLE
Segmentation fault (core dumped) issue when gdal(3.0.4) is configured with EFAL_19.0

### ISSUE THREAD

**Issue by divysts** [OSGeo/gdal#7240]
I have install efal_19.0 from ```https://support.precisely.com/product-downloads/item/mapinfo-efal-sdk-download/``` this link in order to support nativeX format. after configuring efal in bashrc with efal driver and SDK i am getting ```Segmentation fault (core dumped) ```. Steps to Replicate the issue:                                                                                                                                                                               
1.On ubuntu 20.04 install gdal-bin 3.04 version.
2. Download both SDK and driver from above link.
3. Download driver folder 
4./home/user/gdal3_efal_drv
5. Extract EFAL_19 zip file and copy contents of export/common to export uu64
6. Edit bashrc like this
1. ```export EFAL_SDK_DIR=/home/user/Downloads/EFAL_19.0/export/uu64
2. export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$EFAL_SDK_DIR
3. export GDAL_DRIVER_PATH=/home/user/efal/drv  
4.  cp /home/divyanshu/gdal3_efal_drv/ogr_EFAL.so $GDAL_DRIVER_PATH ```
7. source ~/.bashrc
After editing trying to convert any file using ogr2ogr command. It is showing Segmentation fault (core dumped)

**Comment by rouault** [comment]
The EFAL driver is closed source software developed by Precisely. You should contact their support about any issue you get with it. Nothing we can do here
