### ISSUE TITLE
IDW Error: Null value considered as 0

### ISSUE THREAD

**Issue by cesarcorreo** [OSGeo/gdal#7241]
Null values are considered as 0 in IDW GDAL interpolation

I´m having the same bug with GDAL IDW interpolation in QGIS (3.16 & . 3.28)
Example:
We consider 5 points where 4 of them at the extremes always have a value of 10 and the central point with three assumptions:

All values -> All points with a value of 10.
0_Value -> Centre point value of 0
Null_Value-> Centre point value of Null
Result:

The resulting interpolated layer behaves:

In assumption 1 constant raster layer with value of 10.
Assumptions 2 and 3. The resulting raster layer shows a central depression with a value of 0.
I understand that the result in assumption 1 should be a constant layer with value equal to 10 and not the result that results in the resulting layer giving a value of 0 at the point with null value.
(I have taken into account a very wide search radius value to avoid problems in "locating points")

Versions
(Also tested in 3.16.16 with the same bug)

Versión de QGIS
3.28.3-Firenze
Revisión del código de QGIS
https://github.com/qgis/QGIS/commit/c12bcb2f76c9a77fd4d3f9579e0c3f863237eb2f
Versión Qt
5.15.3
Versión de Python
3.9.5
Versión de GDAL/OGR
3.6.2
Versión de PROJ
9.1.1
Versión del registro de base de datos EPSG
v10.076 (2022-08-31)
Versión de GEOS
3.11.1-CAPI-1.17.1
Versión de SQLite
3.39.4
Versión de PDAL
2.4.3
Versión del cliente de PostgreSQL
unknown
Versión de SpatiaLite
5.0.1
Versión de QWT
6.1.6
Versión de QScintilla2
2.13.1
Versión del SO
Windows 10 Version 2009

Complementos activos de Python
Cadastral_Divisions-main
1.2
ClipMultipleLayers
3.2.0
contour
2.0.12
dataexplorer
3.1.1
DataPlotly
3.9.2
kmltools
3.1.27
latlontools
3.6.8
magic_map_loader
1.0
mmqgis
2021.9.10
PlanCreator-3
0.1
PluginLoadTimes
3.0.1
pointsamplingtool
0.5.4
polystrip
3.0.1
processing_saga_nextgen
0.0.7
profiletool
4.2.2
project_report
1.2

Qgis2threejs
2.7.1
qgis2web
3.16.0
QGISSortAndNumber-master
1.0
quick_map_services
0.19.33
refFunctions
1.6
rvt-qgis
0.9.4.1
searchlayers
3.0.12
Serval
3.10.5
Smart_Map
1.2
Spanish_Inspire_Catastral_Downloader
1.1
SpreadsheetLayers
2.1.0-alpha1
StreetView
3.2
Submission
0.7
ThreePointMethod
0.1
valuetool
3.0.15
volume_calculation_tool
0.4
db_manager
0.1.20
grassprovider
-->

## Expected behavior and actual behavior.

For example (please modify !!!): I expected to be able to open this raster file (with a link to
the raster file, or it as an attachment) and it returns an error message
instead.

## Steps to reproduce the problem.

For example (please modify !!!): "gdalinfo myfile"

## Operating system

For example (please modify !!!): Ubuntu 16.04 64 bit

## GDAL version and provenance

For example (please modify !!!): the 2.2.3 version from ubuntugis-unstable PPA

[IDW_GDAL_ERROR.zip](https://github.com/OSGeo/gdal/files/10722188/IDW_GDAL_ERROR.zip)
![4](https://user-images.githubusercontent.com/25932761/218458084-1e3c2d79-6222-4884-b3e1-19d17bb86c25.jpg)

![1](https://user-images.githubusercontent.com/25932761/218458046-bc9b23e4-5090-41d1-
![3](https://user-images.githubusercontent.com/25932761/218458074-8123cc10-8ebf-4b14-8c02-4f179aed8e04.jpg)
a651-e97d05a4ef13.jpg)
![2](https://user-images.githubusercontent.com/25932761/218458059-71ba8fdf-560c-44eb-9b66-73eaf1414440.jpg)

[IDW_GDAL_ERROR.zip](https://github.com/OSGeo/gdal/files/10722198/IDW_GDAL_ERROR.zip)

**Comment by rouault** [comment]
@cesarcorreo  Please edit the issue template to provide accurate details, including how to reproduce it

**Comment by cesarcorreo** [comment]
> @cesarcorreo Please edit the issue template to provide accurate details, including how to reproduce it

Sorry.
Posted again

**Comment by rouault** [comment]
What is the exact gdal_grid command line used ? You probably need to set the ``nodata`` option of the gridding algorithm. See https://gdal.org/programs/gdal_grid.html#interpolation-algorithms

**Comment by cesarcorreo** [comment]
> What is the exact gdal_grid command line used ? You probably need to set the `nodata` option of the gridding algorithm. See https://gdal.org/programs/gdal_grid.html#interpolation-algorithms

You are right. 

I don't see in the documentation to leave null values without being changed to 0.
If I delete the value of 0 it is put back


![6](https://user-images.githubusercontent.com/25932761/218489026-98664615-146e-4195-9a62-2cd61b381330.jpg)

**Comment by rouault** [comment]
ok, I get it. The issue is that points whose Z attribute is unset/null should be ignored.

**Comment by cesarcorreo** [comment]
You are right.

**Comment by rouault** [comment]
fx in https://github.com/OSGeo/gdal/pull/7244
