### ISSUE TITLE
Problem when save .prj file

### ISSUE THREAD

**Issue by diogocaribe** [OSGeo/gdal#725]
## Expected behavior and actual behavior.

I expect that gdal writes .prj correctly. I run gdal-segment and it save shapefile with wrong .prj. I put problem in gisexchange - https://gis.stackexchange.com/questions/280346/why-ogr-doesnt-read-this-kind-of-prj -  and Luck suggested that can be a bug problem. He had read the code from gdal-segment and suggested that can be a problem in gdal function that write it.

It save .prj like this (not expected):

> PROJCS["PROJCS["WGS 84 / UTM zone 24N",GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4326"]],PROJECTION["Transverse_Mercator"],PARAMETER["latitude_of_origin",0],PARAMETER["central_meridian",-39],PARAMETER["scale_factor",0.9996],PARAMETER["false_easting",500000],PARAMETER["false_northing",0],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AXIS["Easting",EAST],AXIS["Northing",NORTH],AUTHORITY["EPSG","32624"]]",-->UNIT["Meter",1]]

As expected:

> PROJCS["WGS 84 / UTM zone 24N",GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4326"]],PROJECTION["Transverse_Mercator"],PARAMETER["latitude_of_origin",0],PARAMETER["central_meridian",-39],PARAMETER["scale_factor",0.9996],PARAMETER["false_easting",500000],PARAMETER["false_northing",0],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AXIS["Easting",EAST],AXIS["Northing",NORTH],AUTHORITY["EPSG","32624"]]"]

## Steps to reproduce the problem.

I run gdal-segment (https://github.com/cbalint13/gdal-segment) and it saves a shapefile with wrong .prj file. The raster file that I used was downloaded from Landsat 8 from USGS.

## Operating system
Ubuntu 16.04 64 bit
gdal version: 2.2.2

**Comment by rouault** [comment]
I believe this is a bug of gdal-segment itself at line https://github.com/cbalint13/gdal-segment/blob/d1876e25c4d7de923427b57c4db9936cdef8ee0c/src/io/vector.cpp#L177 . You should report it to gdal-segment

It should call oSRS.SetFromUserInput() instead of oSRS.SetProjCS().

Closing as not a GDAL bug
