### ISSUE TITLE
Documentation site search is broken

### ISSUE THREAD

**Issue by rcoup** [OSGeo/gdal#7251]
## Expected behavior and actual behavior.

I expect the search box on https://gdal.org to return results, but it doesn't. It used to 😁 

## Steps to reproduce the problem.

1. https://gdal.org
2. Search for strings that are definitely present. eg: "gdalinfo", "config", "configuration", "CPL_DEBUG", "gtiff", "vsis3", ...
3. "Your search did not match any documents. Please make sure that all words are spelled correctly and that you've selected enough categories."

## Operating system

Google Chrome 109 on macOS

## GDAL version and provenance

Whatever is published at 15 Feb 2023 (main is 9ec53d9)

**Comment by rouault** [comment]
yeah we have the same issue on proj.org as well. I assume this is an issue with the Read The Docs Sphynx theme, or something like that. Interestingly the same PROJ doc hosted by the Read The Docs infrastructure has the functionality working : cf https://pointcloud.org/en/9.1/ (yeah the pointcloud.org domain is just as this is beta test)

**Comment by rouault** [comment]
It definitely used to work a few weeks/months ago, and I don't hink we have changed anything related
