### ISSUE TITLE
mbtiles to geotiff create infinite sized resultant

### ISSUE THREAD

**Issue by CraigglesO** [OSGeo/gdal#727]
## Expected behavior and actual behavior.
A new geotiff file from the mbtiles. Unfortunately the program runs indefinitely until memory on my computer runs out. The original .mbtiles size is about 186 MB.

BTW - I got this hillshade dataset from openmaptiles. I can't get geotiff from them unless I subscribe for $500, but I got the Utah hillshade for $40, so... I figured I could just decompose.

## Steps to reproduce the problem.
`gdal_translate -of GTiff hillshade-utah.mbtiles export.tiff`

## Operating system
OS X Sierra

## GDAL version and provenance
GDAL 1.11.5, released 2016/07/01

**Comment by rouault** [comment]
GDAL 1.11 is really ancient. You should upgrade to a more recent version, for example GDAL 2.3.1

**Comment by CraigglesO** [comment]
Beautiful! That did it.

Didn't realize brew was still giving out an old version.

For those with OS X dealing with the same problem, here is the fix:
https://www.karambelkar.info/2016/10/gdal-2-on-mac-with-homebrew/

Thanks a heap @rouault - and thanks for the speedy response.
