### ISSUE TITLE
GDAL-Georefrencing already Georefrenced single band Raster

### ISSUE THREAD

**Issue by nikamsa1** [OSGeo/gdal#728]
I am trying to georeference already georeferenced single band raster data using GDAL with four GCP's.

Input image is having Coordinate system GCS- WGS1984 (EPSG:4326).
Following Command is run on command Prompt:

"gdal_translate -of GTiff -gcp 72.4819 23.0179 72.4819 23.0179 -gcp 72.492 23.0079 72.492 23.0079 -gcp 72.4819 23.0086 72.4819 23.0086 -gcp 72.496 23.0169 72.496 23.0169 input.tiff output1.tiff
gdalwarp -r near -order 1 -co COMPRESS=NONE -s_srs EPSG:4326 -t_srs EPSG:4326 output1.tiff" output.tiff"

Issues:
-> After running this command on command prompt and opening output generated file  in QGIS the output is not having the coordinate system as EPSG:4326.

-> Image is opening somewhere else location in QGIS viewer. Hence the image is not properly georeferenced.

-> For cross verification I ran  georefrencing tool in QGIS with same input dataset it is giving the expected output and image is opening on exact Geographic location.

-> For cross verification, I copied generated gdal script from QGIS and ran again in Command Prompt and opened output  again in QGIS. The image is not as expected.

Questions:
1. Is this above command is correct for georeferencing already georeferenced data?
2. Apart from above command Is there any another internal Command QGIS using for georeferencing image?
3. After running gdalwarp, why the output generated is not resampled and not having mentioned coordinate system.

**Comment by rouault** [comment]
Please do not abuse project bandwidth. You already posted this on the mailing list, which was appropriate, since it is questions, and not a bug report
