### ISSUE TITLE
GRIB file with incorrect transform, crs

### ISSUE THREAD

**Issue by mdsumner** [OSGeo/gdal#7298]
This GRIB file reports as having transform

```
-25404784      7673         0  27510851         0     -7673
```

and Polar Stereographic (variant B) which is the *northern hemisphere*. 

As far as I know the actual transform should be more like (this was derived empirically so isn't logically aligned exactly to the definition of the grid)

```
-3380000.000     7985.612        0.000  3410000.000        0.000    -7977.099
```

and the CRS should be equivalent to 

```
"+proj=stere +lat_0=-90 +lat_ts=-71 +lon_0=180 +x_0=0 +y_0=0 +a=6367470 +b=6367470"
```

(southern hemisphere!!)

and it looks like this  (band 19 is a good choice for geographic context)

![image](https://user-images.githubusercontent.com/4107631/220796449-b94aba1a-ee52-477d-8aa2-ba57eff55638.png)

The grid definition is *like the one at* https://amps-backup.ucar.edu/information/configuration/maps.html "Grid 2 (10-km Continental grid), mass grid" - but the dimensions are different since then.  (I'll dig up provenance info if I can). 

I haven't investigated the details in the file (long ago I simply worked around this but want to record this example and pursue).  I can see with mdim that X and Y axis coordinate values are incorrect. 

## Steps to reproduce the problem.

*EDITED: to remove a custom file creation, and replaced with wget of the entire original file from its source as requested in comments below*

wget this file and gdalinfo (file will be transient and disappear in a few weeks/months)

```
wget https://www2.mmm.ucar.edu/rt/amps/wrf_grib/2023022312/2023022312_WRF_d2_f000.grb
gdalinfo 2023022312/2023022312_WRF_d2_f000.grb
```

```
Driver: GRIB/GRIdded Binary (.grb, .grb2)
Files: 2023022312_WRF_d2_f000.grb
Size is 834, 786
Coordinate System is:
PROJCRS["unnamed",
    BASEGEOGCRS["Coordinate System imported from GRIB file",
        DATUM["unnamed",
            ELLIPSOID["Sphere",6367470,0,
                LENGTHUNIT["metre",1,
                    ID["EPSG",9001]]]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433,
                ID["EPSG",9122]]]],
    CONVERSION["Polar Stereographic (variant B)",
        METHOD["Polar Stereographic (variant B)",
            ID["EPSG",9829]],
        PARAMETER["Latitude of standard parallel",60,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8832]],
        PARAMETER["Longitude of origin",180,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8833]],
        PARAMETER["False easting",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["(E)",south,
            MERIDIAN[90,
                ANGLEUNIT["degree",0.0174532925199433,
                    ID["EPSG",9122]]],
            ORDER[1],
            LENGTHUNIT["Metre",1]],
        AXIS["(N)",south,
            MERIDIAN[180,
                ANGLEUNIT["degree",0.0174532925199433,
                    ID["EPSG",9122]]],
            ORDER[2],
            LENGTHUNIT["Metre",1]]]
Data axis to CRS axis mapping: 1,2
Origin = (-25404783.837483372539282,27510850.990491051226854)
Pixel Size = (7673.000000000000000,-7673.000000000000000)
Corner Coordinates:
```

```## Operating system

 Ubuntu 20.04 64 bit

## GDAL version and provenance

GDAL 3.7.0dev-8ec21bbf70-dirty, released 2023/02/22

**Comment by rouault** [comment]
What is the URL of the original product ? We cannot reliably reason on the subset produced by GDAL

**Comment by mdsumner** [comment]
Similear files can be found here: 

https://www2.mmm.ucar.edu/rt/amps/wrf_grib

a conveniently size 76Mb one is wget-able at

```
https://www2.mmm.ucar.edu/rt/amps/wrf_grib/2023022312/2023022312_WRF_DRAKE_f000.grb
```

The files are transient on the order of weeks, so these URLs won't persist, I'd actually thought they were harder to get than this hence the slice extracted.

**Comment by mdsumner** [comment]
sorry, that file was  a bad choice - it's a different grid to the one reported above. I'll follow up

**Comment by mdsumner** [comment]
This one matches the spec in the OP - it's "d2"

```
wget https://www2.mmm.ucar.edu/rt/amps/wrf_grib/2023022312/2023022312_WRF_d2_f000.grb
```

I've updated the question with a source file and wget. Thanks!
