### ISSUE TITLE
MSVC Static Library

### ISSUE THREAD

**Issue by reid-p** [OSGeo/gdal#7299]
Building gdal as a static libary creates the following warning with the MSVC linker:
 warning LNK4286: symbol 'deflateInit_' defined in 'zlib.lib(deflate.obj)' is imported by 'gdal.lib(cpl_vsil_gzip.cpp.obj)'

This due the unconditional setting of ZLIB_DLL in the cmake files for MSVC.

The following patch address the problem.

[fix-zlib-linking.patch](https://github.com/OSGeo/gdal/files/10809987/fix-zlib-linking.patch)

**Comment by rouault** [comment]
The condition shouldn't be on GDAL being built as a shared library but on the zlib library being a static one (you could potentially build a GDAL shared library that would statically link against zlib, at least I guess that's doable). I'd suggest replacing BUILD_SHARED_LIBS with NOT ZLIB_IS_STATIC (and documented it in https://github.com/OSGeo/gdal/edit/master/doc/source/development/building_from_source.rst). A pull request would be welcome
