### ISSUE TITLE
Deployment and Compatibility Optimization Issues

### ISSUE THREAD

**Issue by freemankevin** [OSGeo/gdal#7301]
Is there no one to maintain it properly? No matter what the environment is, there are only dependencies and various jams. There are problems with the python environment, geosense dependencies, ubuntu, and debian，arm64  dependencies. Can you sort out this document and the environment clearly, the installation cost is too high to use now, it feels like a pile of shit.

**Comment by jratike80** [comment]
If you want to learn the ecosystem we welcome you to the team. We appreciate all useful inputs to the documentation and processes.

**Comment by nyalldawson** [comment]
There's zero tolerance for abusive language like this. I suggest you learn some basic manners.

**Comment by hobu** [comment]
blocked

**Comment by sgillies** [comment]
@hobu to be clear, blocked for violation of the code of conduct? I think they clearly did so. I'm going to do the same for Fiona, where they also did a rude drive by.

**Comment by hobu** [comment]
> @hobu to be clear, blocked for violation of the code of conduct? 

Correct. They can take it up with the OSGeo Board if they think they should be reinstated.
