### ISSUE TITLE
GDAL 3.5.3 warping issues with geolocation arrays

### ISSUE THREAD

**Issue by debaeckerv** [OSGeo/gdal#7302]
## Expected behavior and actual behavior.

I found some issues when passing from gdal 3.4.3 to 3.5.3 (conda-forge) using geolocations arrays in gdalwarp with datasets derived from SLSTR L1B products:

![comparison_gdal_3 4 3_vs_3 5 3](https://user-images.githubusercontent.com/98812595/220928037-9608c9d4-8e4d-46b5-ae21-5cc177284df1.jpg)

First issue (nan values in output) looks similar to a closed issue:  #5823 (but relates to gdal 3.5.0 and should be fixed already in 3.5.1)

Second issue is about some tiles of the output image appearing extremely stretched.

Note: geolocation arrays here are lat/lon grids (SLSTR L1B) converted (using pyproj) into a tpers projection that fits location and azimuth of the scene.

## Steps to reproduce the problem.

Input/outputs datasets and logs are available here: 
https://drive.google.com/drive/folders/1czL-fS1Dfheux2r7IWcERwAtTWbpdQdv?usp=sharing

The  `input_slstr_l1b_tpers.nc` file contains the image (S3 band) and the X and Y coordinates. Geolocation arrays are defined through the vrt files: `coords_x.vrt`, `coords_y.vrt` and `input_slstr_l1b_tpers.vrt`.

The `command.txt` file show the command being used to generate the outputs (same command for testing the 2 gdal versions). 
This looks like:

`gdalwarp -overwrite -geoloc -r bilinear input_slstr_l1b_tpers.vrt output_slstr_l1b_tpers_gdal3.5.3.tif`

## Operating system

`Ubuntu 18.04.6 LTS`

## GDAL version and provenance
* Version as reference: `GDAL 3.4.3, released 2022/04/22` from `conda-forge`
* Version with issue: `GDAL 3.5.3, released 2022/10/21` from `conda-forge`

**Comment by debaeckerv** [comment]
I have also tested the `--config GDAL_GEOLOC_INVERSE_METHOD QUADTREE` option as suggested in #5823.
It looks much better, but still some nan values spread everywhere.
(I've changed the dynamic of the images below to highlight the nodata values issue)

![comparison_gdal_3 4 3_vs_3 5 3_quadtree](https://user-images.githubusercontent.com/98812595/220931322-4b43197a-afff-4a16-99e7-ace03b8e331a.jpg)

**Comment by rouault** [comment]
> Input/outputs datasets and logs are available here:
> https://drive.google.com/drive/folders/1czL-fS1Dfheux2r7IWcERwAtTWbpdQdv?usp=sharing

@debaeckerv It lacks public permissions

**Comment by rouault** [comment]
https://github.com/OSGeo/gdal/pull/7308 fixes the hole issues on the dataset of this ticket. This is due to a number of the geolocation quadrilaterals being degenerate to triangles.

**Comment by debaeckerv** [comment]
Just tested the fix. Working great. Many thanks @rouault ! 
Also thanks for the improvement of the geometric accuracy compared to gdal version < 3.5
