### ISSUE TITLE
Parallel computation for Big Data mosaic and COG generation

### ISSUE THREAD

**Issue by yu-feng-ho** [OSGeo/gdal#7303]
## Problem 
I used `gdal_translate` to generate a world map at `30m`, `Int32`, `COMPRESS=DEFLATE`, and 'COG' map. 
Input data is tiled to `1000x1000` and is about `21,6915` tiles. 

First I used 

````
gdalbuildvrt -input_file_list /input_folder/*.tiff input.vrt
````

and it took me ~ **4 hours** to generate a `input.vrt`.

Then, I used `gdal_translate` as following codes:

````
gdal_translate -co TILED=YES -co BIGTIFF=YES -co COMPRESS=DEFLATE -co BLOCKXSIZE=1024 -co BLOCKYSIZE=1024 -co NUM_THREADS=8 -co SPARSE_OK=TRUE input.vrt input.tif
````

and it took me ~ **28 hours**.

Final, I used `gdal_translate` again:

````
gdal_translate -a_scale 0.1 --config GDAL_CACHEMAX 2048 -co BLOCKSIZE=1024 -co BIGTIFF=YES -co COMPRESS=DEFLATE -co NUM_THREADS=8 -co LEVEL=9 -of COG input.tif output_cog.tif
````

and it took me ~**40 hours**. Input file size is `1296000, 525000` 

To add up, the whole process costs me **4+28+40=72 hrs (3 days)**. We have 80 thread CPUs and would like to speed up processing as much as possible. Waiting 3 days just to generate file is turning into a bottleneck in our processing workflow.

I am here suggesting maybe a feature of parallel computation in `gdal_translate` or anything other way to speed up **mosaic** and **COG generating** dramatically in huge map. 

Any discussion is welcome! Thanks for any contribution in advance!

## Operating system

Ubuntu 20.04.5 LTS

## GDAL version and provenance

gdal 3.1.4: [https://download.osgeo.org/gdal/3.1.4/](https://download.osgeo.org/gdal/3.1.4/)

**Comment by rouault** [comment]
Why not using input.vrt directly as the source of the COG generation ? You don't necessarily have to use a materialized file. It is expected that creating a COG file that large takes a lot of time. As it is a single file output, parallelizing more than currently is hard

**Comment by yu-feng-ho** [comment]
I noticed compression could be a critical bottleneck. It is also possible to speed up by changing `COMPRESS=DEFLATE` to `COMPRESS=LZW` and increase `NUM_THREADS=8`  to  `NUM_THREADS=ALL_CPUs` ? 

Another point, if the tile size increases and tile number decreases, will it speed up too?

Thanks for replying. It's very helpful to know!

**Comment by rouault** [comment]
> It is also possible to speed up by changing COMPRESS=DEFLATE to COMPRESS=LZW and increase NUM_THREADS=8 to NUM_THREADS=ALL_CPUs ?

making sure your libtiff build is built against libdeflate will give a ~ x2 speedup. Increasing NUM_THREADS might indeed help, but I've some doubts it will scale up linearly to 80 vCPUs.

> Another point, if the tile size increases and tile number decreases, will it speed up too?

hard to predict, but I wouldn't anticipate tile size changes to change a lot execution time. This is mostly the number of pixels that matters.

**Comment by rouault** [comment]
I'm closing this as this is too generic. People would always love for things to be faster...
