### ISSUE TITLE
Docs Request - move SWIG to optional deps when building from source

### ISSUE THREAD

**Issue by Ryanf55** [OSGeo/gdal#7330]
## Expected behavior and actual behavior.

**Expected:** When building GDAL, if I do not install [required dependencies](https://gdal.org/development/dev_environment.html#build-requirements), like SWIG, I would expect the build to fail.
**Actual:** The build passes fine without [SWIG](https://open-box.readthedocs.io/en/latest/installation/install_swig.html) since it's not actually required. 

I would prefer if the docs instead say SWIG is an optional requireement instead of a mandatory minimum requirement. That way, I can install the minimum amount of packages for building. 

## Steps to reproduce the problem.

1. Install [build dependendencies](https://gdal.org/development/dev_environment.html#build-requirements) for GDAL
    ```console
    sudo apt install libproj-dev
    ```

    * **Note** I skip Swig, and verify it's not on my system.

1. Download GDAL 3.6
    ```console
    wget https://github.com/OSGeo/gdal/releases/download/v3.6.2/gdal-3.6.2.tar.gz
    ```
1. Build it from source
    ```console
    cd gdal-3.6.2
    cmake -S . -B build
    ```

See the following in the log:
```
-- The following RECOMMENDED packages have not been found:

...
 * SWIG, software development tool that connects programs written in C and C++ with a variety of high-level programming languages., <http://swig.org/>
   Enable language bindings
```

## Operating system

Ubuntu 22.04 64 bit

## GDAL version and provenance

The 3.6.2 version from Github source releases

## Contribution

If the maintainers approve this change, I can issue a PR to the docs to move SWIG from required to optional. If the devs want SWIG to be required, I can issue a PR modify the CmakeLists to make SWIG required.

**Comment by rouault** [comment]
CC @dbaston
