### ISSUE TITLE
ogrinfo CSW json output does not contain all the standard output informations

### ISSUE THREAD

**Issue by aborruso** [OSGeo/gdal#7342]
## Expected behavior and actual behavior.

Hi, if I run a CSW standard query, I have a different output than when I use the `-json` parameter

## Steps to reproduce the problem.

If you run

```
ogrinfo  -ro -al "CSW:http://geodati.gov.it/RNDT/csw" -where "anytext LIKE 'PTPR'"  | grep -P 'title.+PTPR'
```

you get the list of all title fields that contain the string `PTPR`

In example

```
...
title (String) = Quadro di unione PTPR93 - Tutele
title (String) = Quadro di unione PTPR93 - Dissesto
title (String) = Quadro di unione PTPR93 - Uso Reale del Suolo
...
```

If you add only `-json`

```
ogrinfo -json  -ro -al "CSW:http://geodati.gov.it/RNDT/csw" -where "anytext LIKE 'PTPR'"  | grep -P 'title.+PTPR'
```

you get no result.

Is it normal?

## Operating system

Debian 11

## GDAL version and provenance

GDAL 3.7.0dev-b0aa6065a3, released 2023/01/11 (debug build)

**Comment by jratike80** [comment]
It seems that ogrinfo behaves in a different way even with these simple requests:

```
ogrinfo -ro  "CSW:http://geodati.gov.it/RNDT/csw"  --debug on --config CPL_CURL_VERBOSE YES
ogrinfo -json  -ro  "CSW:http://geodati.gov.it/RNDT/csw"  --debug on --config CPL_CURL_VERBOSE YES
```
The first request is satisfied at this stage

```
OGR: GetLayerCount() = 1
GDAL: GDALClose(CSW:http://geodati.gov.it/RNDT/csw, this=00000292E3226690)
```
but with `-json` ogrinfo continues by doing lots of other requests

```
HTTP: Fetch(http://geodati.gov.it/RNDT/csw)
HTTP: These POSTFIELDS were sent:<?xml version="1.0" encoding="UTF-8"?><csw:GetRecords resultType="results" service="CSW" version="2.0.2" startPosition="1" maxRecords="500" xmlns:csw="http://www.opengis.net/cat/csw/2.0.2" xmlns:gml="http://www.opengis.net/gml" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dct="http://purl.org/dc/terms/" xmlns:ogc="http://www.opengis.net/ogc" xmlns:ows="http://www.opengis.net/ows" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/cat/csw/2.0.2 http://schemas.opengis.net/csw/2.0.2/CSW-discovery.xsd"><csw:Query typeNames="csw:Record"><csw:ElementSetName>full</csw:ElementSetName></csw:Query></csw:GetRecords>
```

**Comment by agiudiceandrea** [comment]
@aborruso have you read https://gdal.org/programs/ogrinfo.html#cmdoption-ogrinfo-al? It seems `-al` is not needed, while you need `-features` to obtain the same result.

**Comment by aborruso** [comment]
> It seems `-al` is not needed wth `-json`, while you need `-features` to obtain a similar result.

Yes I know.

Than you think that it's by design: the same command, using `-json`, gives a different output pattern (not only the different size, which is an expected fact).

Ok, I close it

**Comment by aborruso** [comment]
> @aborruso have you read [gdal.org/programs/ogrinfo.html#cmdoption-ogrinfo-al](https://gdal.org/programs/ogrinfo.html#cmdoption-ogrinfo-al)? It seems `-al` is not needed wth `-json`, while you need `-features` to obtain a similar result.

In any case, I have probably some problems with my GDAL 3.7.0dev-b0aa6065a3, released 2023/01/11 (debug build).

If I run

```
ogrinfo  -features -json "CSW:http://geodati.gov.it/RNDT/csw" -where "anytext LIKE 'PTPR'"
```

I have [this JSON](https://gist.github.com/ead35e55a678a92cae2eaee31a659fef) without any title.

**Comment by agiudiceandrea** [comment]
Try with:
`ogrinfo -json -features "CSW:http://geodati.gov.it/RNDT/csw" -where "anytext LIKE 'PTPR'"`

It seems in this case the parameter's order matters. I think this is a bug.

**Comment by aborruso** [comment]
> It seems in this case the order of the `-json` and `-features` parameters matters. I think this is a bug or at least a non documented behaviour.

It works, thank you
