### ISSUE TITLE
 gdal for ios build error

### ISSUE THREAD

**Issue by HerryJessica** [OSGeo/gdal#7343]
hi
When I use cmake to compile gdal3.6 for ios arm64 build error
<img width="2755" alt="截屏2023-03-03 17 46 39" src="https://user-images.githubusercontent.com/44019088/222687890-b17eb6ec-8a16-41c5-acc2-e77fbe206e96.png">
 I don't know what causes this！

**Comment by rouault** [comment]
i would say there's something wrong in your tool chain. It looks like CMake would have detected that your compiler supported Intel CPUs. Perhaps try to remove CMakeCache.txt and retry

**Comment by HerryJessica** [comment]
I tried deleting CMakeCache.txt and rebuilding, but still the same error.Below is my toolchain and error log：

    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x c++ -target arm64-apple-ios16 -fmessage-length\=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit\=0 -Wno-trigraphs -fpascal-strings -O3 -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-return-type -Wno-non-virtual-dtor -Wno-overloaded-virtual -Wno-exit-time-destructors -Wno-missing-braces -Wparentheses -Wswitch -Wno-unused-function -Wno-unused-label -Wno-unused-parameter -Wno-unused-variable -Wunused-value -Wno-empty-body -Wno-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wno-constant-conversion -Wno-int-conversion -Wno-bool-conversion -Wno-enum-conversion -Wno-float-conversion -Wno-non-literal-null-conversion -Wno-objc-literal-conversion -Wshorten-64-to-32 -Wno-newline-eof -Wno-c++11-extensions -Wno-implicit-fallthrough -DCMAKE_INTDIR\=\"Release-iphoneos\" -DINST_DATA\=\"/Users/charles/Documents/BmNewEarth/3rdparty/ios/gdal/share/gdal\" -DSYSCONFDIR\=\"/Users/charles/Documents/BmNewEarth/3rdparty/ios/gdal/etc\" -DHAVE_PREAD_BSD -DSIZEOF_OFF_T\=8 -DHAVE_SSSE3_AT_COMPILE_TIME -DHAVE_AVX_AT_COMPILE_TIME -DHAVE_LIBZ -DZIP_SUPPORT -DHAVE_ZLIB_H -DHAVE_ZLIB -DHAVE_CURL -DHAVE_ICONV -DHAVE_LIBXML2 -DHAVE_SSE_AT_COMPILE_TIME -DDONT_DEPRECATE_SPRINTF -DGDAL_COMPILATION -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.2.sdk -fstrict-aliasing -Wdeprecated-declarations -Winvalid-offsetof -Wno-sign-conversion -Wno-infinite-recursion -Wno-move -Wno-comma -Wno-block-capture-autoreleasing -Wno-strict-prototypes -Wno-range-loop-analysis -Wno-semicolon-before-method-body -I/Users/charles/Documents/BmNewEarth/build/ios/gdal3.6/build/cpl.build/Release-iphoneos/include -I/Users/charles/Documents/BmNewEarth/3rdparty/ios/boost -I/Users/charles/Documents/BmNewEarth/3rdparty/gdal-3.6.0/port -I/Users/charles/Documents/BmNewEarth/build/ios/gdal3.6/port -I/Users/charles/Documents/BmNewEarth/3rdparty/gdal-3.6.0/ogr/ogrsf_frmts/geojson/libjson -I/Users/charles/Documents/BmNewEarth/3rdparty/ios/zlib/include -I/Users/charles/Documents/BmNewEarth/3rdparty/ios/curl/include -I/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include/libxml2 -I/Users/charles/Documents/BmNewEarth/build/ios/gdal3.6/build/cpl.build/Release-iphoneos/DerivedSources-normal/arm64 -I/Users/charles/Documents/BmNewEarth/build/ios/gdal3.6/build/cpl.build/Release-iphoneos/DerivedSources/arm64 -I/Users/charles/Documents/BmNewEarth/build/ios/gdal3.6/build/cpl.build/Release-iphoneos/DerivedSources -F/Users/charles/Documents/BmNewEarth/build/ios/gdal3.6/build/cpl.build/Release-iphoneos -DNDEBUG -fPIC -Wall -Wextra -Winit-self -Wunused-parameter -Wmissing-declarations -Wshorten-64-to-32 -Wshadow -Wshadow-field -Wmissing-include-dirs -Wformat -Werror\=format-security -Wno-format-nonliteral -Werror\=vla -Wdate-time -Wnull-dereference -Wextra-semi -Wcomma -Wfloat-conversion -Wdocumentation -Wno-documentation-deprecated-sync -Wunused-private-field -Wnon-virtual-dtor -Woverloaded-virtual -Wsuggest-override -fno-operator-names -Wzero-as-null-pointer-constant -Wold-style-cast -Weffc++ -std\=gnu++11 -MMD -MT dependencies -MF /Users/charles/Documents/BmNewEarth/build/ios/gdal3.6/build/cpl.build/Release-iphoneos/Objects-normal/arm64/cpl_cpu_features.d --serialize-diagnostics /Users/charles/Documents/BmNewEarth/build/ios/gdal3.6/build/cpl.build/Release-iphoneos/Objects-normal/arm64/cpl_cpu_features.dia -c /Users/charles/Documents/BmNewEarth/3rdparty/gdal-3.6.0/port/cpl_cpu_features.cpp -o /Users/charles/Documents/BmNewEarth/build/ios/gdal3.6/build/cpl.build/Release-iphoneos/Objects-normal/arm64/cpl_cpu_features.o
/Users/charles/Documents/BmNewEarth/3rdparty/gdal-3.6.0/port/cpl_cpu_features.cpp:85:5: error: invalid output constraint '=a' in asm
    CPL_CPUID(1, cpuinfo);
    ^
/Users/charles/Documents/BmNewEarth/3rdparty/gdal-3.6.0/port/cpl_cpu_features.cpp:67:33: note: expanded from macro 'CPL_CPUID'
#define CPL_CPUID(level, array) GCC_CPUID(level, array[0], array[1], array[2], array[3])
                                ^
/Users/charles/Documents/BmNewEarth/3rdparty/gdal-3.6.0/port/cpl_cpu_features.cpp:63:10: note: expanded from macro 'GCC_CPUID'
       : "=a" (a), "=r" (b), "=c" (c), "=d" (d) \
         ^
/Users/charles/Documents/BmNewEarth/3rdparty/gdal-3.6.0/port/cpl_cpu_features.cpp:100 : 5: error: invalid output constraint '=a' in asm
    CPL_CPUID(1, cpuinfo);
    ^
/Users/charles/Documents/BmNewEarth/3rdparty/gdal-3.6.0/port/cpl_cpu_features.cpp:67:33: note: expanded from macro 'CPL_CPUID'
#define CPL_CPUID(level, array) GCC_CPUID(level, array[0], array[1], array[2], array[3])
                                ^
/Users/charles/Documents/BmNewEarth/3rdparty/gdal-3.6.0/port/cpl_cpu_features.cpp:63:10: note: expanded from macro 'GCC_CPUID'
       : "=a" (a), "=r" (b), "=c" (c), "=d" (d) \
         ^
/Users/charles/Documents/BmNewEarth/3rdparty/gdal-3.6.0/port/cpl_cpu_features.cpp:135:5: error: invalid output constraint '=a' in asm
    CPL_CPUID(1, cpuinfo);
    ^
/Users/charles/Documents/BmNewEarth/3rdparty/gdal-3.6.0/port/cpl_cpu_features.cpp:67:33: note: expanded from macro 'CPL_CPUID'
#define CPL_CPUID(level, array) GCC_CPUID(level, array[0], array[1], array[2], array[3])
                                ^
/Users/charles/Documents/BmNewEarth/3rdparty/gdal-3.6.0/port/cpl_cpu_features.cpp:63:10: note: expanded from macro 'GCC_CPUID'
       : "=a" (a), "=r" (b), "=c" (c), "=d" (d) \
         ^
/Users/charles/Documents/BmNewEarth/3rdparty/gdal-3.6.0/port/cpl_cpu_features.cpp:152:25: error: invalid output constraint '=a' in asm
    __asm__ ("xgetbv" : "=a" (nXCRLow), "=d" (nXCRHigh) : "c" (0));
                        ^
4 errors generated.

**Comment by HerryJessica** [comment]
I found the problem where the cmake tool chain was set incorrectly, causing the output of the CMAKE_SYSTEM_PROCESSOR parameter to be x86_64, which should be arm64. I modified it and built it successfully, but after the build, I did not output libgdal.a as normal, but I got a bunch of script files. I don’t know. How to use it or build errors
<img width="925" alt="截屏2023-03-06 17 02 05" src="https://user-images.githubusercontent.com/44019088/223064420-c8d5185f-a1c3-4b6c-8250-2a8cf1585407.png">

output log：
Create build description
Build description signature: 9e648abf5c92fa25843dcdf41b284c43
Build description path: /Users/charles/Documents/BmNewEarth/build/ios/gdal3.6-Qt6/build/XCBuildData/9e648abf5c92fa25843dcdf41b284c43-desc.xcbuild

note: Building targets in dependency order
note: Run script build phase 'Generate CMakeFiles/ZERO_CHECK' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'ZERO_CHECK' from project 'gdal')
PhaseScriptExecution Generate\ CMakeFiles/ZERO_CHECK /Users/charles/Documents/BmNewEarth/build/ios/gdal3.6-Qt6/build/gdal.build/Release-iphoneos/ZERO_CHECK.build/Script-92682D34FB5E189E8E29F8F8.sh (in target 'ZERO_CHECK' from project 'gdal')
    cd /Users/charles/Documents/BmNewEarth/3rdparty/gdal-3.6.0
    /bin/sh -c /Users/charles/Documents/BmNewEarth/build/ios/gdal3.6-Qt6/build/gdal.build/Release-iphoneos/ZERO_CHECK.build/Script-92682D34FB5E189E8E29F8F8.sh
make: `/Users/charles/Documents/BmNewEarth/build/ios/gdal3.6-Qt6/CMakeFiles/cmake.check_cache' is up to date.

note: Run script build phase 'Generate CMakeFiles/generate_gdal_version_h' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'generate_gdal_version_h' from project 'gdal')
PhaseScriptExecution Generate\ CMakeFiles/generate_gdal_version_h /Users/charles/Documents/BmNewEarth/build/ios/gdal3.6-Qt6/build/gdal.build/Release-iphoneos/generate_gdal_version_h.build/Script-B55FF1E518F22A3BD0639BBF.sh (in target 'generate_gdal_version_h' from project 'gdal')
    cd /Users/charles/Documents/BmNewEarth/3rdparty/gdal-3.6.0
    /bin/sh -c /Users/charles/Documents/BmNewEarth/build/ios/gdal3.6-Qt6/build/gdal.build/Release-iphoneos/generate_gdal_version_h.build/Script-B55FF1E518F22A3BD0639BBF.sh

note: Run script build phase 'Generate ogr/CMakeFiles/check_swq_parser_md5' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'check_swq_parser_md5' from project 'gdal')
PhaseScriptExecution Generate\ ogr/CMakeFiles/check_swq_parser_md5 /Users/charles/Documents/BmNewEarth/build/ios/gdal3.6-Qt6/build/gdal.build/Release-iphoneos/check_swq_parser_md5.build/Script-0567761E71F896B5563EBEE8.sh (in target 'check_swq_parser_md5' from project 'gdal')
    cd /Users/charles/Documents/BmNewEarth/3rdparty/gdal-3.6.0
    /bin/sh -c /Users/charles/Documents/BmNewEarth/build/ios/gdal3.6-Qt6/build/gdal.build/Release-iphoneos/check_swq_parser_md5.build/Script-0567761E71F896B5563EBEE8.sh

note: Run script build phase 'Generate ogr/ogrsf_frmts/ods/CMakeFiles/check_ods_formula_parser_md5' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'check_ods_formula_parser_md5' from project 'gdal')
PhaseScriptExecution Generate\ ogr/ogrsf_frmts/ods/CMakeFiles/check_ods_formula_parser_md5 /Users/charles/Documents/BmNewEarth/build/ios/gdal3.6-Qt6/build/gdal.build/Release-iphoneos/check_ods_formula_parser_md5.build/Script-048CC93CDC7CAF43A26E0E10.sh (in target 'check_ods_formula_parser_md5' from project 'gdal')
    cd /Users/charles/Documents/BmNewEarth/3rdparty/gdal-3.6.0
    /bin/sh -c /Users/charles/Documents/BmNewEarth/build/ios/gdal3.6-Qt6/build/gdal.build/Release-iphoneos/check_ods_formula_parser_md5.build/Script-048CC93CDC7CAF43A26E0E10.sh

note: Run script build phase 'Generate CMakeFiles/ALL_BUILD' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'ALL_BUILD' from project 'gdal')
PhaseScriptExecution Generate\ CMakeFiles/ALL_BUILD /Users/charles/Documents/BmNewEarth/build/ios/gdal3.6-Qt6/build/gdal.build/Release-iphoneos/ALL_BUILD.build/Script-C2D587E97E2330E9072D9373.sh (in target 'ALL_BUILD' from project 'gdal')
    cd /Users/charles/Documents/BmNewEarth/3rdparty/gdal-3.6.0
    /bin/sh -c /Users/charles/Documents/BmNewEarth/build/ios/gdal3.6-Qt6/build/gdal.build/Release-iphoneos/ALL_BUILD.build/Script-C2D587E97E2330E9072D9373.sh
Build all projects

** BUILD SUCCEEDED **

**Comment by HerryJessica** [comment]
I try to use cmake to build the xcode project and the above problem will occur, but I use cmake to build ninja and the compilation is successful

**Comment by tildraev** [comment]
has anyone had luck building GDAL for iOS at this point? I could use some help if anyone is willing.
