### ISSUE TITLE
CMake: Poppler detection should check for Object.h private header availability

### ISSUE THREAD

**Issue by rouault** [OSGeo/gdal#7352]
GDAL depends on Poppler being built with ENABLE_UNSTABLE_API_ABI_HEADERS=YES CMake option. Currently we successfully detect a Poppler build without it, but fail at building time since headers like Object.h aren't available. During configuration phase, we should issue an explicit warning hinting the user. And https://gdal.org/development/building_from_source.html#poppler should also underline this

**Comment by rsbivand** [comment]
Thanks for raising this!
