### ISSUE TITLE
Containers for GDAL build/test environments

### ISSUE THREAD

**Issue by dbaston** [OSGeo/gdal#7379]
I've been writing up some notes on reproducing GDAL CI failures locally and had some thoughts on simplifying the process.

The GDAL CI jobs I've looked into either:
1. start with a "stock" container such as `alpine:edge`, `fedora:rawhide`, or `ubuntu:18.04` and install build dependencies during each CI run
2. create a container with the complete build environment and save it to GitLab CI's cache for use in subsequent CI runs (the Ubuntu 20.04 run is an example)

A modification of the second method would make it a bit easier to reproduce CI failures locally, while also providing good CI performance:

3. create a container with the complete build environment and save it to a container registry for use in CI runs

My experience with other projects using this approach has been positive. The only way I've set it up is to create the build environment containers via a separate process from the CI runs themselves, such as a job that runs on a specified frequency. (This covers the case where you want to track the dev version of some dependencies.) An alternative that is closer to the current GDAL practice would be to have the CI run itself update the container if the Dockerfile that defines it has changed. This _should_ be possible (e.g., via https://github.com/moby/moby/issues/39003#issuecomment-571470958) although I have not yet made it work.

Is there any interest in restructuring the GDAL CI runs along these lines?

Maybe it is also worth thinking about harmonizing the containers used for CI (`.github/workflows/**`) and those used for distribution (`docker/**`).

**Comment by rouault** [comment]
> The only way I've set it up is to create the build environment containers via a separate process from the CI runs themselves, such as a job that runs on a specified frequency.

I believe that's what QGIS does with https://github.com/qgis/QGIS/blob/master/.github/workflows/build-docker.yml . Perhaps @elpaso can confirm ?

**Comment by elpaso** [comment]
> > The only way I've set it up is to create the build environment containers via a separate process from the CI runs themselves, such as a job that runs on a specified frequency.
> 
> I believe that's what QGIS does with https://github.com/qgis/QGIS/blob/master/.github/workflows/build-docker.yml . Perhaps @elpaso can confirm ?

Yeah, I believe so, I didn't set it up myself so I am not familiar with the details. I think there is also a ccache permanent storage across builds to speed compilation up (in QGIS it could take hours, GDAL is surely faster).

**Comment by dbaston** [comment]
@rouault Do you want to assign this one to me?

**Comment by rouault** [comment]
> Do you want to assign this one to me?

done. I've sent you a GH invitation with "triage" role, that should hopefully be good enough for you to be able to assign tickets etc

**Comment by dbaston** [comment]
Would it make sense to migrate the Ubuntu 18.04 builds over to this style, or with 18.04 going EOL in a month does it make sense to add the components tested by these builds (Postgres, MySQL, MongoDB etc.) to the 20.04 (or a 22.04) build?

**Comment by dbaston** [comment]
Completed with 7759d3c2d1390a91db5d70b31703b037992c4e6c
