### ISSUE TITLE
Use GDALDataset::FromHandle instead of C-style cast in C++ raster tutorial

### ISSUE THREAD

**Issue by Ryanf55** [OSGeo/gdal#7380]
## Expected behavior and actual behavior.

Expected: In the [C++ Raster API Tutorial](https://gdal.org/tutorials/raster_api_tut.html#opening-the-file), I would expect to use the `C++` features of the GDAL Library. 
Actual: A c-style cast is used to convert from X to Y. 
```c++
#include "gdal_priv.h"
#include "cpl_conv.h" // for CPLMalloc()
int main()
{
    GDALDataset  *poDataset; // Using a raw ptr instead of unique pointer. 
    GDALAllRegister();
    poDataset = (GDALDataset *) GDALOpen( pszFilename, GA_ReadOnly ); // The C-style cast is here
    if( poDataset == NULL ) // NULL is used, instead of nullptr
    {
        ...;
    }
```

A more C++ way of doing the conversion would be a `static_cast`, or use the included `FromHandle` function like so (which uses static_cast under the hood), as per [C++ core guidelines to use C++ over C rule cpl1](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#cpl1-prefer-c-to-c).
```c++
GDALDataset  *poDataset;
GDALAllRegister();
const GDALAccess access = GA_ReadOnly;
poDataset= GDALDataset::FromHandle(GDALOpen(pszFilename, access));
```

Another room for improvement, instead of using raw pointer to `GDALDataset`, is to use the `GDALDatasetUniquePtr` per [C++ Core Guidelines R.20](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#r20-use-unique_ptr-or-shared_ptr-to-represent-ownership), and comparing to  `nullptr` instead of `NULL` per the [C++ Core Guidelines es.47](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#es47-use-nullptr-rather-than-0-or-null). 

## Steps to reproduce the problem.

N/A (it's documentation)

## Operating system

Ubuntu 22.04

## GDAL version and provenance

Raster API tutorial [9e9f8b2](https://github.com/OSGeo/gdal/commit/9e9f8b294418e5f2670dacd5cacb5d6cdeabb797)

If the maintainers are open to it, I would like to submit the change to use `FromHandle`. I can also switch to `GDALDatasetUniquePtr`, as well as using `nullptr` instead of `null` in the same change, or a separate PR. 

Why? Following ISOCPP core guidelines makes code safer that has access to C++.

**Comment by rouault** [comment]
> Thanks, can you assign this to me (so I can keep track)?

done

**Comment by Ryanf55** [comment]
I have the changes ready. I have also read the contributing guidelines. I am getting errors running `make html`. 

I have installed sphinx. https://www.sphinx-doc.org/en/master/usage/installation.html#linux
And, I have installed breathe, from pip. https://pypi.org/project/breathe/

Is there any documentation in GDAL I am missing for how to install all the documentation building dependencies?

**Comment by rouault** [comment]
> for how to install all the documentation building dependencies?

@Ryanf55: try "pip install -r doc/requirements.txt"

CC @dbaston  : we may need extra directions regarding doc building
