### ISSUE TITLE
Docs refer to using python executable which doesn't exist on Ubuntu 20.04 because it needs to be python3

### ISSUE THREAD

**Issue by Ryanf55** [OSGeo/gdal#7383]
## Expected behavior and actual behavior.

Expected: On Ubuntu 20.04, I can copy commands from the documentation, and they refer to executables that exit
Actual: Commands referring to `python` no longer work . It needs to be `python3` to work on Linux. 

## Steps to reproduce the problem.

Try following [instructions for installing pre-commit](https://gdal.org/development/dev_practices.html#commit-hooks)

## Operating system

Ubuntu 20.04

## GDAL version and provenance

`doc/source/development)/dev_practices.rst` at hash [e03e966](https://github.com/OSGeo/gdal/commit/e03e966994bd01bc45cf739eeaf81fd02c385c19)

## Reference

According to pep 0394, the `python` command may refer to either python2 or python3, so if the documentations intend users to use python3 for a command, it should say that. 

https://itsfoss.com/python-not-found-ubuntu/
https://opensource.com/article/19/5/python-3-default-mac
https://peps.python.org/pep-0394/

**Comment by Ryanf55** [comment]
If you think it's an OK modification to spell out `python3` in the relevant places rather than `python`, let me know, assign this to me and I can do it.

**Comment by rouault** [comment]
> to spell out `python3` in the relevant places rather than `python`

+1

**Comment by Ryanf55** [comment]
The work is pushed. I restricted changes to :

include `doc/**`
Excluding `doc/build/**`, `**.py`, `doc/source/development/rfc/rfc*.rst`

Note: The code blocks in `.rst` files  all refer to `python` as the syntax. I did take a look, and these are automatically rendering with python3 syntax (this was changed automatically when python2 was deprecated). 

https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-code-block
https://pygments.org/docs/lexers/
