### ISSUE TITLE
ogr2ogr: GeoJSON with (simple) JSON Array to GeoPackage

### ISSUE THREAD

**Issue by kraftto** [OSGeo/gdal#7397]
## Expected behavior and actual behavior.

When converting a GeoJSON File to GPKG with `ogr2ogr`, JSON Objects and Arrays of Ojects are translated just fine. `ogrinfo` identifies them as Type=String(JSON). Simple JSON Arrays that contain only primitives, however, are identified as, e.g., StringList, and `ogr2ogr` raises a warning:

```Warning 1: The output driver does not natively support StringList type for field X. Misconversion can happen. -mapFieldType can be used to control field type conversion.```

The resulting values in the GPKG field looks like this and cannot be interpreted by QGIS:

```(1:besondereArtDerBaulNutzung)```
```(3:gebietsArt,gemeinde[0]/XP_Gemeinde/gemeindeName,gemeinde[0]/XP_Gemeinde/ags)```

Using `-mapFieldType StringList=String(JSON)` or `-fieldTypeToString StringList` do not seem tohave any effect. 

The expected behaviour is that JSON Arrays in a GeoJSON file are interpreted as String(JSON) and the resulting representation in GPKG - using the examples above - would be like:

```["besondereArtDerBaulNutzung"]```
```["gebietsArt", "gemeinde[0]/XP_Gemeinde/gemeindeName", "gemeinde[0]/XP_Gemeinde/ags"]```

## Steps to reproduce the problem.

1. Unzip [xplan.zip](https://github.com/OSGeo/gdal/files/10941082/xplan.zip)
2. ```ogr2ogr -f GPKG xplan.gpkg xplan.json```

## Operating system

Windows 10 64 bit

## GDAL version and provenance

GDAL 3.6.2 from OSGEO4W

**Comment by rouault** [comment]
> a GPKG TEXT field containing a string that's a valid JSON array literal containing primitives (like `["besondereArtDerBaulNutzung"]`) should then probably be identified as String(JSON) instead of just String

Are you speaking on a "intelligent" behaviour on the reading side that tries to autoguess the field type ? That would be a bit too "magic", and that cannot be done without scanning the whole table, so definitely not appropriate for the base functionality of a OGR driver.

**Comment by kraftto** [comment]
I just meant the same/consistent behaviour as for arrays of objects in a GPKG TEXT field. A field value like this:
```[ { "href": "urn:uuid:a630c212-8ae0-4be6-91c4-b0dc8cba820a", "rel": "related" } ]```
is apparently interpreted as OGR field type String(JSON), while
```["string1", "string2", "string3"]```
is not/is type String.

**Comment by rouault** [comment]
> I just meant the same/consistent behaviour as for arrays of objects in a GPKG TEXT field. A field value like this:
> `[ { "href": "urn:uuid:a630c212-8ae0-4be6-91c4-b0dc8cba820a", "rel": "related" } ]`
> is apparently interpreted as OGR field type String(JSON), while
> `["string1", "string2", "string3"]`
> is not/is just type String.

sorry I have troubles following you. It looks like a different issue and would need a reproducer

**Comment by kraftto** [comment]
OK, I'll open a separate issue. Thanks for the quick response with [a6ff77b](https://github.com/rouault/gdal/commit/a6ff77b416a4fa83bd106aee7ca2948fe7ad5b55)

**Comment by kraftto** [comment]
I figured it out: I wasn't aware that the table gpkg_data_columns is used to store mime_type=application/json for fields of OGR type String(JSON). So i guess once the ogr2ogr fix is available, an entry will be added for arrays of primitives as well.
