### ISSUE TITLE
Which projection database to use

### ISSUE THREAD

**Issue by Kurtaja** [OSGeo/gdal#7398]
Hi,
I have downloaded the latest EPSG WKT database from the https://epsg.org/download-dataset.html page.
I'm using gdal from an Anaconda venv on win 11.
How can I configure in my python scripts that the gdal package shall use the particular dataset version that I have downloaded?
Kind regards 
Kurt

**Comment by rouault** [comment]
"""IMPORTANT: Do NOT use GitHub to post any questions or support requests!
           They will be closed immediately and ignored.

Questions should go to the gdal-dev mailing list at
https://lists.osgeo.org/mailman/listinfo/gdal-dev
or other support forums. GitHub issues are for bug
reports and suggestions for new features."""
