### ISSUE TITLE
[OGR] Feature request: support for JSON-FG

### ISSUE THREAD

**Issue by kraftto** [OSGeo/gdal#7399]
[JSON-FG](https://docs.ogc.org/DRAFTS/21-045.html) is an emerging OGC standard that 
> extends GeoJSON to support a limited set of additional capabilities that are out-of-scope for GeoJSON, but that are important for a variety of use cases involving feature data.

This includes a concept for FeatureTypes by introcuding a new top-level-member "featureType" and support for CRS other than WGS84. An uptake in implementations and by communities is vital, and adoption by GDAL/OGR would certainly be a great step forward. 

Here are some initial suggestions to implement JSON-FG support by extending existing GeoJSON driver functionality:

- a FeatureCollection containing heterogenous features could be interpreted as separate layers based on the ["featureType"](https://docs.ogc.org/DRAFTS/21-045.html#_the_featuretype_member)-member 
- an Open Option could be added to choose whether the "geometry"-member or the "place"-member in conjunction with the "coordRefSys"-member should be used as OGR Geometry
- Dataset creation could support creating a heterogenous FeatureCollection from several OGR Layers, and homogenous collections with a "featureType"-member at collection level from a single OGR Layer

**Comment by sgillies** [comment]
In the past we extended the GeoJSON driver so that it handled every JSON format and it turned out to be a bad idea. I hope we won't repeat this. At the very least, I think JSON-FG should be its own driver.

**Comment by rouault** [comment]
> we extended the GeoJSON driver so that it handled every JSON format

are you thinking about EsriJSON and GeoJSONSeq ? They are actually in separated drivers, and share code that needs to be shared in a hopefully sensible way

> At the very least, I think JSON-FG should be its own driver.

The overlap with GeoJSON is huge. At least there is a lot of code that should be re-used. But yes, JSON-FG management should likely go to a dedicated GDALDriver object, with its own open & creation options, even if it reuses lots of code of the GeoJSON driver underneath. On the reading side, there would be a bit magic to add to the existing magic that distinguishes GeoJSON, GeoJSONSeq and ESRIJSON to make JSON-FG content be detected by the right driver.

Anyway that's a non-trivial amount of work and would require someone to come up with the code or funding. Some concepts of JSON FG are also hard to represent in the OGR model, in particular geometries like MultiPolyhedron (we'd probably need a new OGRGeometry class for that) or Prism (could probably be represented by a Polyhedron though)

**Comment by sgillies** [comment]
@rouault I'm thinking of the situation of e.g. version 2.1 when different JSON format handlers were in the GeoJSON driver module https://github.com/OSGeo/gdal/blob/release/2.1/gdal/ogr/ogrsf_frmts/geojson/ogrgeojsondriver.cpp#L66.

**Comment by rouault** [comment]
Assigning myself as I've been commissioned to work on this
