### ISSUE TITLE
FlatGeobuf: Rows with empty or null geometries are not written (or read?) to/from FlatGeobuf file

### ISSUE THREAD

**Issue by theroggy** [OSGeo/gdal#7401]
## Expected behavior and actual behavior.

When copying a layer with rows with null and/or empty geometries from a GPKG file to a FlatGeobuf file the rows with null or empty geometries disappear.

Issue was originally encountered here: [pyogrio # 226](https://github.com/geopandas/pyogrio/issues/226). In that issue is also a python script that reproduces and illustrates the issue.

## Steps to reproduce the problem.

[Link to test.gpkg file](https://drive.google.com/file/d/12lzjXPi8IC_oq6bDhOVOgEXwpJGEsRWR/view?usp=sharing). This file has 3 rows: 
- one with a valid point geometry, 
- one with an empty point geometry and 
- one with a null geometry.

In test2.gpkg is only the row with the valid point geometry left.
```
ogr2ogr test.fgb test.gpkg
ogr2ogr test2.gpkg test.fgb
```

## Operating system

Windows 10

## GDAL version and provenance

gdal 3.6.2

**Comment by rouault** [comment]
CC @bjornharrtell  I see that ICreateFeature() explicitly discards input features without geometry or with a IsEmpty() geometry.  On the reading side though, GetNextFeature() seems to be tolerant to missing geometry.  Regarding the behaviour of the writer, I assume the reason to discard those features without geometry is related to the sorting of features according to the spatial index ? But couldn't those features without geometry be just put at the beginning or at the end of the file ?

**Comment by bjornharrtell** [comment]
@rouault I don't recall the details.. but I also do not recall any intention to throw away empty geoms and it should be a supported case also for indexed FlatGeobuf. That said I don't think it's a use case that has been well explored or tested.

**Comment by bjornharrtell** [comment]
@rouault I will try find time to look into this as soon as possible.

**Comment by bjornharrtell** [comment]
I now believe I did briefly think about this case and thought it is silly to consider non spatial data when spatially Indexing so just ignore. This might of course been a bit naive... And is perhaps fixable but it will likely take some time and effort to carefully retrofit.

**Comment by bjornharrtell** [comment]
I think you are right @rouault it should likely be fine to just write them at the end. I will try to make a test case reproduction and fix.

**Comment by rouault** [comment]
The ArrowArray reading is just on the reading side, and I don't think it should go into your way, as it is reuses the logic of GetNextFeature() regarding index. Anyway you can ignore that and I'll retrofit it if you manage to make GetNextFeature() working
For the batch buffering, I assume this is on the writing side (lines 582-665) ? Same here, if that goes into your way, just try to make the non batch writing working, and I'll adapt.

**Comment by bjornharrtell** [comment]
Above PR includes a test case reproduction of the problem and an attempt to fix it but for me it results in invalid buffers (it test case fails with ERROR 1: Buffer verification failed). As of yet I've been unable to understand why.

**Comment by bjornharrtell** [comment]
@theroggy this is unfortunately looking harder to solve than initially expected and might even need a revision of the FlatGeobuf spec which is undesirable to me.

I'm considering simply forbidding the use case and make the implementation error out when attempted.

This is because I have a difficult time understanding why one would want indexed files with some non indexable content. But I might reconsider if you can provide some motivation to why it would be useful to support it.

**Comment by jratike80** [comment]
I meet features without geometries in registers like cadaster or land parcel identification system, where a new unit can be created by the responsible authority, but the geometry is not known by then and it is added later after field visit. Huge majority of the features do have geometries. So the use case is real, but empty geometries tend to make trouble also for many other GIS systems. That has lead to workarounds like using a fake placeholder geometries. I know that there used to be hundreds of economic centers of farms which received EU subsidies placed into the sea between Finland and Sweden and that astonished some ignorant users.
I just want to tell that there use cases, not that spatial index with empty geometries must be supported. They would make trouble in any case. For example, should "intersects" filter return all the empty geometries always, or never?

**Comment by bjornharrtell** [comment]
@jratike80 agreed it's a real world scenario that is always problematic regardless if your format supports to handle/store it or not. This is actually a reason for my hesistance of supporting it in the first place as it might even be better to avoid it entirely. As for the "intersects" filter I would say it is wrong to return null/empty geometries.

**Comment by jratike80** [comment]
> As for the "intersects" filter I would say it is wrong to return null/empty geometries.

Yeah, and then if somebody wants to read big dataset as tiles they will never get the empty geometries because they do not intersect with any tile. Same happens if some WFS server or client thinks that it is a good idea to use BBOX filter always, using the layer extent as default if user does not give any. But with the other approach the empty geometries would be included in all the tiles.

**Comment by bjornharrtell** [comment]
@theroggy good points and feedback. It looks like I will have to make this an error for now since it's looks like the only option short term + some clarifications in spec and FAQ places. I've added a discussion point at https://github.com/flatgeobuf/flatgeobuf/discussions/260 for a better place to discuss the pro/cons of supporting the specific case.

**Comment by jratike80** [comment]
For information only: the OGC API Features and Records standards require that bbox filter matches empty geometries. See OGC API Features ticket https://github.com/opengeospatial/ogcapi-features/issues/765 and consideration in https://github.com/opengeospatial/ogcapi-records/issues/175#issuecomment-1174847632.

`The bbox parameter SHALL match all features in the collection that are not associated with a spatial geometry, too`

**Comment by bjornharrtell** [comment]
@jratike80 interesting. Pretty wierd in my opinion. I wouldn't expect to get 1 million non spatial data entries when attemping to use bbox filter for a small area. Read the linked issues but couldn't find any good rationale for it.

**Comment by bjornharrtell** [comment]
@rouault I think this can be closed.
