### ISSUE TITLE
gdaltest: replace gdal.PushErrorHandler("CPLQuietErrorHandler")

### ISSUE THREAD

**Issue by rouault** [OSGeo/gdal#7418]
Replace
```
gdal.PushErrorHandler("CPLQuietErrorHandler")
... something ...
gdal.PopErrorHandler()
```
with
```
with gdaltest.error_handler():
    ... something ....
```

**Comment by rouault** [comment]
@dbaston You should differ this a bit, as the changes I'm doing for #7452 involve modifying a number of places affected by error handler related code

**Comment by dbaston** [comment]
I've done the `autotest/ogr` subdir but will set it aside for now.

Unrelated, I was thinking that maybe `with gdaltest.quiet_errors():` would be more clear than `with gdaltest.error_handler():`

**Comment by rouault** [comment]
> I've done the `autotest/ogr` subdir but will set it aside for now.

perhaps issue a PR with just that ?
