### ISSUE TITLE
GDALDatasetRasterIOEx sometimes wrongly gives zeros on bands 2,3,4 

### ISSUE THREAD

**Issue by lahavy** [OSGeo/gdal#7431]
Call to GDALDatasetRasterIOEx on a few specific 4band tiff images, gives zeros on the 2nd, 3rd and 4th bands (sometimes only 3rd, and 4th). 
This happens when requesting the output to be ~twice smaller than the input, and for any resize interpolation.

Only when changing the target size to be equal to the input size, all bands are retrieved correctly.

Please also note that GDALDatasetRasterIOEx  returns no error.

## Operating system

Windows 10

## GDAL version and provenance
3.6.2 (and also in 3.2.1)

**Comment by rouault** [comment]
Please provide a full standalone reproducer .c or .cpp + input data. If "gdal_translate -outsize 50% 50% in.tf out.tif" works, it is likely an issue in your code.

**Comment by lahavy** [comment]
Thanks for your answer.

After digging a little bit, found that there was a corrupted .ovr image near the image (with missing bands).

Is there a way to prevent GDAL from using overview files when reading the image?

**Comment by jratike80** [comment]
It is even documented https://gdal.org/programs/gdal_translate.html.

> -ovr <level|AUTO|AUTO-n|NONE>[](https://gdal.org/programs/gdal_translate.html#cmdoption-gdal_translate-ovr)
> New in version 3.6.
> 
> To specify which overview level of source file must be used. The default choice, AUTO, will select the overview level whose resolution is the closest to the target resolution. Specify an integer value (0-based, i.e. 0=1st overview level) to select a particular level. Specify AUTO-n where n is an integer greater or equal to 1, to select an overview level below the AUTO one. Or specify NONE to force the base resolution to be used (can be useful if overviews have been generated with a low quality resampling method, and a higher quality resampling method is specified with [-r](https://gdal.org/programs/gdal_translate.html#cmdoption-gdal_translate-r).
> 
> When [-ovr](https://gdal.org/programs/gdal_translate.html#cmdoption-gdal_translate-ovr) is specified to an integer value, and none of [-outsize](https://gdal.org/programs/gdal_translate.html#cmdoption-gdal_translate-outsize) and [-tr](https://gdal.org/programs/gdal_translate.html#cmdoption-gdal_translate-tr) is specified, the size of the overview will be used as the output size.
> 
> When [-ovr](https://gdal.org/programs/gdal_translate.html#cmdoption-gdal_translate-ovr) is specified, values of [-srcwin](https://gdal.org/programs/gdal_translate.html#cmdoption-gdal_translate-srcwin), when specified, should be expressed as pixel offset and size of the full resolution source dataset. Similarly when using [-outsize](https://gdal.org/programs/gdal_translate.html#cmdoption-gdal_translate-outsize) with percentage values, they refer to the size of the full resolution source dataset.

**Comment by lahavy** [comment]
I am looking for an API function, not using translate

**Comment by jratike80** [comment]
Sorry, I read only "Is there a way to prevent GDAL from using overview files when reading the image?".
