### ISSUE TITLE
Builds not generating all *jni.dll

### ISSUE THREAD

**Issue by njpsanghani** [OSGeo/gdal#744]
Builds not generating all *jni.dll

## Expected behavior and actual behavior.

For example: I expected to be able to open this raster file (with a link to
the raster file, or it as an attachment) and it returns an error message
instead.

## Steps to reproduce the problem.

For example: "gdalinfo myfile"

## Operating system

For example: Ubuntu 16.04 64 bit

## GDAL version and provenance

For example: the 2.2.3 version from ubuntugis-unstable PPA

**Comment by rouault** [comment]
You have to install the libgdal-java package

**Comment by njpsanghani** [comment]
Hello, could u help me where to find it??
