### ISSUE TITLE
osgeo.ogr.DataSource.ExecuteSQL "no such function: ogr_layer_Extent" for GeoPackage, works for Shapefile

### ISSUE THREAD

**Issue by captaincoordinates** [OSGeo/gdal#7443]
## Expected behavior and actual behavior.

I expect `osgeo.ogr.DataSource.ExecuteSQL` to behave the same regardless of data source, however at least one function that is available for a Shapefile data source is not available for a GeoPackage data source.

## Steps to reproduce the problem.

See this [minimal repo](https://github.com/captaincoordinates/ogr-gpkg-sqlite-bug) for steps to reproduce. This example executes `SELECT ogr_layer_Extent` against first a Shapefile and then a GeoPackage. The Shapefile works as expected but the GeoPackage produces
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/test.py", line 23, in <module>
    read_layer_extent(src_path=args.src_path)
  File "/test.py", line 11, in read_layer_extent
    extents = datasource.ExecuteSQL(sql, dialect="SQLite")
  File "/usr/lib/python3/dist-packages/osgeo/ogr.py", line 952, in ExecuteSQL
    return _ogr.DataSource_ExecuteSQL(self, *args, **kwargs)
RuntimeError: In ExecuteSQL(): sqlite3_prepare_v2(SELECT ogr_layer_Extent('poly_4326')):
  no such function: ogr_layer_Extent
```

## Operating system

Ubuntu in Docker image osgeo/gdal:ubuntu-full-3.6.3

## GDAL version and provenance

3.6.3 from Docker image osgeo/gdal:ubuntu-full-3.6.3

**Comment by rouault** [comment]
The way SQLite is integrated with GDAL is a bit complicated.
Several options:
- use dialect="indirect_sqlite" for a GPKG dataset
- use the layer.GetExtent() method

**Comment by jratike80** [comment]
I can see that something has changed since writing the documentation https://gdal.org/drivers/vector/gpkg.html

> SQL SELECT statements passed to ExecuteSQL() are also executed directly against the database. If Spatialite is used, a recent version (4.2.0) is needed and use of explicit cast operators AsGPB() is required to transform GeoPackage geometries to Spatialite geometries (the reverse conversion from Spatialite geometries is automatically done by the GPKG driver). It is also possible to use with any Spatialite version, but in a slower way, by specifying the “INDIRECT_SQLITE” dialect. In which case, GeoPackage geometries automatically appear as Spatialite geometries after translation by OGR.

and https://gdal.org/user/sql_sqlite_dialect.html

> If the datasource is SQLite database (GeoPackage, SpatiaLite) then SQLite dialect acts as native SQL dialect and Virtual Table Mechanism is not used. It is possible to force GDAL to use Virtual Tables even in this case by specifying “-dialect INDIRECT_SQLITE”. This should be used only when necessary, since going through the virtual table mechanism might affect performance.

There is no need to use `AsGPB()`, probably since some SpatiaLite version that introduced "CastAutomagic". And I also noticed that at least with GDAL 3.7.0dev the SpatiaLite functions seem to work against GeoPackage even with `-dialect SQLite`. I would like to edit the documentation about using SQLite dialect for GeoPackages but unfortunately I do not know exactly what is the current truth.

**Comment by rouault** [comment]
> Is the SQLite dialect with SpatiaLite functions selected now automatically?

Spatialite functions are loaded in the default dialect of a GeoPackage datasource, with "amphibious" mode turned on automatically with spatialite >= 4.3. Since a long time (2014 or even older)

**Comment by captaincoordinates** [comment]
> The way SQLite is integrated with GDAL is a bit complicated. Several options:
> 
> * use dialect="indirect_sqlite" for a GPKG dataset
> * use the layer.GetExtent() method

Having workarounds is good, but if possible I would prefer not to detect the incoming data source type and branch based on if / how the source supports SQL. It's hugely valuable sometimes that for the most part OGR "just works" with so many different vector formats.

**Comment by theroggy** [comment]
> Having workarounds is good, but if possible I would prefer not to detect the incoming data source type and branch based on if / how the source supports SQL. It's hugely valuable sometimes that for the most part OGR "just works" with so many different vector formats. If nothing else the SQL documentation should indicate that there is variable support.

Apparently it isn't clear, but [here](https://gdal.org/user/ogr_sql_dialect.html#non-ogr-sql) in the OGRSQL documentation is explained that drivers for databases/file databases use their native SQL syntax by default... and as GPKG is actually an sqlite file, the SQLITE dialect is the default.

To get information about a layer, I personally use the python API as it is a portable option and easy to get all relevant data, including e.g. the extent (or total_bounds). For inspiration you could have a look at a helper function I wrote that collects the typical properties of a layer:
- [API documentation](https://geofileops.readthedocs.io/en/stable/api/geofileops.get_layerinfo.html#geofileops.get_layerinfo) 
- [source code](https://github.com/geofileops/geofileops/blob/ddb8b40396cc1c5daa03390b5a0ccf990e2b24e2/geofileops/fileops.py#L207)

**Comment by rouault** [comment]
> the SQLITE dialect is the default.

that's a bit more complicated than that. GPKG recognizes the "sqlite" dialect, but doesn't use the same implementation as other drivers implementing sqlite as indirect_sqlite and that use spatialite geometry blobs when spatial functions are involved. So GPKG is a bit of a special case

**Comment by theroggy** [comment]
> > the SQLITE dialect is the default.
> 
> that's a bit more complicated than that. GPKG recognizes the "sqlite" dialect, but doesn't use the same implementation as other drivers implementing sqlite as indirect_sqlite and that use spatialite geometry blobs when spatial functions are involved. So GPKG is a bit of a special case

Yes, the phrasing "the SQLITE dialect" was indeed not ideal. "native SQLite SQL syntax" or something like that is probably clearer for what I meant to say.

**Comment by captaincoordinates** [comment]
Thanks all for the considered input. To clarify: I am not looking for workarounds - I'm quite comfortable working in the python API - I just think there is a disagreement here between documentation and reality that could be addressed. It's probably worth explicitly identifying GPKG in the [Non-OGR SQL](https://gdal.org/user/ogr_sql_dialect.html#non-ogr-sql) section, and I think there's also value in 1) moving this section to the top of the page and 2) duplicating or referencing it on the [SQLite Dialect page](https://gdal.org/user/sql_sqlite_dialect.html). I'm happy to submit a PR if this is considered appropriate.

**Comment by rouault** [comment]
I'm working on making ogr_layer_Extent() available on GPKG datasources with its default dialect or dialect='SQLite'

> I'm happy to submit a PR if this is considered appropriate.

Doc enhancements welcome
