### ISSUE TITLE
 Docker is sunsetting Free Team organizations

### ISSUE THREAD

**Issue by rouault** [OSGeo/gdal#7447]
The Docker https://hub.docker.com/orgs/osgeo organization is going to be removed soon (see below email received today), and images belonging to it, unless we pay the Docker tax, and we probably wont. We should migrate OSGeo/proj-docs and OSGeo/gdal* images to github Docker repository

```
Docker is sunsetting Free Team organizations

Free Team organizations are a legacy subscription tier that no longer exists. This tier included many of the same features, rates, and functionality as a paid Docker Team subscription.

After reviewing the list of accounts that are members of legacy Free Team organizations, we’ve identified yours as potentially being one of them.

If you own a legacy Free Team organization, access to paid features — including private repositories — will be suspended on April 14, 2023 (11:59 pm UTC). Upgrade your subscription before April 14, 2023 to continue accessing your organization.

If you don’t upgrade to a paid subscription, Docker will retain your organization data for 30 days, after which it will be subject to deletion. During that time, you will maintain access to any images in your public repositories, though rate limitations will apply. At any point during the 30-day period, you can restore access to your organization account if you upgrade to a paid subscription. Visit our [FAQ](https://em.docker.com/NzkwLVNTQi0zNzUAAAGKf9xJYdJ-goN4ukTVBTscp1izduByO1KAcR3D-r2Dz-ZG9JPjxhzvu_GiO-8eLdXB0qqjlJuhobTNdYw=) for more information.
```

**Comment by rouault** [comment]
I've filled an application to the Docker-Sponsored Open Source Program. I got a acknowledgement: "You’ll receive an update within 30 days. But if you have any questions, feel free to email opensource@docker.com along with the name of your project in the subject line."

**Comment by rouault** [comment]
Reading https://blog.alexellis.io/docker-is-deleting-open-source-images/, it is not obvious that the application will work given that we have funding and companies that have services around GDAL. Probably the GH way is the safer road for now

**Comment by hobu** [comment]
GH at https://github.com/orgs/OSGeo/packages is fine until they force us to move too.

**Comment by rouault** [comment]
> GH at https://github.com/orgs/OSGeo/packages is fine until they force us to move too.

yes, I'm running a script that pulls the osgeo/gdal:variant-x.y.z images from docker.io and repushes them to ghcr.io

**Comment by Vad1mo** [comment]
If, for some reason, the Docker-Sponsored Open-Source Program isn't working out, we are happy to help you out. We operate a Harbor-based [container registry as a service ](https://container-registry.com/)  that has many benefits over most of the other registries out there.

There are also features regarding containerized image distribution, that might be valuable too as well.

**Comment by rouault** [comment]
> We should migrate OSGeo/proj-docs

I see that https://github.com/OSGeo/PROJ/blob/master/.github/workflows/docker.yml already pushes to ghcr.io. So we just have to update references

**Comment by rouault** [comment]
Just received an email from opensource@docker.com:
```
Hi Even Rouault,

Congratulations! Your project has been approved for the Docker-Sponsored Open Source program. A Docker Team subscription will be allocated to the project organization Docker ID specified in your application within the next 3 weeks. In addition to a Team subscription, you now have:

    free autobuilds

    rate-limit removal for all users pulling public images from your project namespace

    special badging on Docker Hub (this will be visible within two weeks)

If you haven’t already, please take the time to update your project’s Hub pages to include a detailed project description, links to your project source code, as well as contributing guidelines, and a link to your organization’s website. Projects lacking this information may not receive the Docker Sponsored Open Source badging for their images on Docker Hub.

Membership in the Docker-Sponsored Open Source (DSOS) program is valid for one year. You will receive a reminder email from us when it is time to renew your membership.

We are thrilled to have you as an open-source partner. If you have any questions regarding the open source program please contact [opensource@docker.com](mailto:opensource@docker.com) and include the name of your project in the subject line. If you have questions regarding technical support please contact [support@docker.com](mailto:support@docker.com).

Thank you!
 ```

**Comment by vincentschut** [comment]
fair enough. Will update our codebases then to use ghcr.io too. Thanks for letting me know.
