### ISSUE TITLE
How to create Block References in dxf files using GDAL?

### ISSUE THREAD

**Issue by DXwangnima** [OSGeo/gdal#7449]
I need to use GDAL to create dxf files in AutoCAD. I have already implemented the creation of point-line geometry layers and label layers, but now the creation of Block References keeps failing. In the official [GDAL documentation](https://gdal.org/drivers/vector/dxf.html#vector-dxf), I found that it supports the creation of Block References.

![image](https://user-images.githubusercontent.com/45487731/225236248-31dd0fcb-dbf3-4b79-805d-ec96e39c7396.png)

First, configure DXF_INLINE_BLOCKS=FALSE, where I don't know how to assign the relevant parameter settings：BlockName、BlockScale、BlockAngle、BlockOCSNormal、BlockOCSCoords、BlockAttributes、Block. In the CAD layers with Block References I found with the properties BlockScale, BlockOCSCoords, the others do not know how to set.

First, configure DXF_INLINE_BLOCKS=FALSE, where I don't know how to assign the relevant parameter settings：BlockName、BlockScale、BlockAngle、BlockOCSNormal、BlockOCSCoords、BlockAttributes、Block. In the CAD layers with Block References I found with the properties BlockScale, BlockOCSCoords, the others do not know how to set.

![image](https://user-images.githubusercontent.com/45487731/225236363-724fc6f5-656c-491a-be58-8dc8df54a9b5.png)

This is the shape of the Block References.

![image](https://user-images.githubusercontent.com/45487731/225236487-c5e77640-0384-480a-bd28-f894f745314f.png)

this is my java code.
```
Driver driver = ogr.GetDriverByName("DXF");
DataSource dataSource = driver.CreateDataSource(path);
Layer blockLayer = dataSource.CreateLayer("blocks");
```
...
```
public void AddBlockFeature(String name, String blockName, String style, long fid, String geom){
    Feature feature = new Feature(blockLayer.GetLayerDefn());
    // FID
    feature.SetFID(fid);
    feature.SetField("Layer", name);
    // set Block
    feature.SetField("Block", name);
    //set BlockName
    feature.SetField("BlockName", blockName);
    //set BlockScale
    feature.SetField("BlockScale", "[0.5,0.5,0.5]");
    // geometry  WKT 
    Geometry geometry = ogr.CreateGeometryFromWkt(geom);
    feature.SetGeometry(geometry);
    //set xyz
    String xyz = String.format("[%f,%f,%f]", geometry.GetX(), geometry.GetY(), 0.0);
    feature.SetField("BlockOCSCoords", xyz);
    //set style
    feature.SetStyleString(style);
    // layer add feature
    blockLayer.CreateFeature(feature);
}
```

I found that SYMBOL is provided in the [Feature Style Specification](https://gdal.org/user/ogr_feature_style.html) of GDAL, and I don't know if it can be achieved through style.

**Comment by jratike80** [comment]
Sorry, but you must have seen this already

> IMPORTANT: Do NOT use GitHub to post any questions or support requests!
>            They will be closed immediately and ignored.
> 
> Questions should go to the gdal-dev mailing list at
> https://lists.osgeo.org/mailman/listinfo/gdal-dev
> or other support forums. GitHub issues are for bug
> reports and suggestions for new features.

Write mail to gdal-dev mailing list. I think you asked the same question in gis.stackexchange already so you can include the link in your mail. That way users can see your screen captures.
