### ISSUE TITLE
Do you know why i can not use python script to install gdal 

### ISSUE THREAD

**Issue by Tun555** [OSGeo/gdal#7450]
Do you know why i can not use python script to install gdal
if i use anaconda create a env and command
"conda install -c conda-forge gdal" It's ok i can open python and from osgeo import gdal but i need to write a python scirpt that can install gdal automatically by subprocess this is my code
import subprocess
command = ["conda", "install", "-c", "conda-forge", "gdal", "--yes", "--debug"]
subprocess.run(command, capture_output=True, text=True)
it's dont work

**Comment by jratike80** [comment]
Sorry,

> IMPORTANT: Do NOT use GitHub to post any questions or support requests!
>            They will be closed immediately and ignored.
> 
> Questions should go to the gdal-dev mailing list at
> https://lists.osgeo.org/mailman/listinfo/gdal-dev
> or other support forums. GitHub issues are for bug
> reports and suggestions for new features.
