### ISSUE TITLE
Export to TAB file made mistake in coordinates

### ISSUE THREAD

**Issue by IlyuninIvan** [OSGeo/gdal#7465]
Export to TAB file made mistake in coordinates
Example: ogr2ogr -f "MapInfo File" C:/temp/w.tab path_to_data_file layer_name

CRS: ESRI 54009 Mollweide
Original Point (-10637609.23280559107661247 4744640.05099706165492535)

CRS: ESRI 54009 Mollweide
TAB exported point
Point (-10637609.22000000067055225 4744640.05999999959021807)

**Comment by rouault** [comment]
This is expected behaviour given that TAB coordinates are discretized to integer to fit within the declared BOUNDS. Cf https://gdal.org/drivers/vector/mitab.html#creation-issues
