### ISSUE TITLE
cpl_recode_iconv.cpp:145:26: error: invalid conversion from ‘const char**’ to ‘char**’

### ISSUE THREAD

**Issue by StonePanda** [OSGeo/gdal#7472]
## Expected behavior and actual behavior.

I expexted to build GDAL-3.6.3 on Ubuntu22.04 using the command line "cmake --build ." and it returns an error message:
```
cpl_recode_iconv.cpp:145:26: error: invalid conversion from ‘const char**’ to ‘char**’ [-fpermissive]
  145 |             iconv(sConv, &pszSrcBuf, &nSrcLen, &pszDstBuf, &nDstLen);
      |                          ^~~~~~~~~~
      |                          |
      |                          const char**
```

## Steps to reproduce the problem.
```
cmake ..
cmake --build .
```
## Operating system

Ubuntu22.04 64bit

## GDAL version and provenance

[gdal-3.6.3.tar.gz](http://download.osgeo.org/gdal/3.6.3/gdal-3.6.3.tar.gz)
the gdal-3.6.3.tar.gz from http://download.osgeo.org/gdal/3.6.3/

**Comment by rouault** [comment]
I can't reproduce. There must be something specific to your system. Can you paste the output of ``grep -i iconv CMakeCache.txt`` ? Here's what I get in my ubuntu 22.04 env:
```
//Set ON to use ICONV
GDAL_USE_ICONV:BOOL=ON
//iconv on windows has individual libcharset
Iconv_CHARSET_LIBRARY:FILEPATH=Iconv_CHARSET_LIBRARY-NOTFOUND
//iconv include directory
Iconv_INCLUDE_DIR:FILEPATH=
//iconv library (potentially the C library)
Iconv_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libc.so
//Details about finding Iconv
FIND_PACKAGE_MESSAGE_DETAILS_Iconv:INTERNAL=[/usr/lib/x86_64-linux-gnu/libc.so][v()]
//Test ICONV_HAS_EXTRA_CHARSETS
ICONV_HAS_EXTRA_CHARSETS:INTERNAL=1
ICONV_HAS_EXTRA_CHARSETS_COMPILED:INTERNAL=TRUE
ICONV_HAS_EXTRA_CHARSETS_EXITCODE:INTERNAL=0
//ADVANCED property for variable: Iconv_CHARSET_LIBRARY
Iconv_CHARSET_LIBRARY-ADVANCED:INTERNAL=1
//ADVANCED property for variable: Iconv_INCLUDE_DIR
Iconv_INCLUDE_DIR-ADVANCED:INTERNAL=1
//Test Iconv_IS_BUILT_IN
Iconv_IS_BUILT_IN:INTERNAL=1
//ADVANCED property for variable: Iconv_LIBRARY
Iconv_LIBRARY-ADVANCED:INTERNAL=1
//Test _ICONV_SECOND_ARGUMENT_IS_NOT_CONST
_ICONV_SECOND_ARGUMENT_IS_NOT_CONST:INTERNAL=1
```

If you've done multiple build attempts with adding new dependencies, etc, try also to remove the existing CMakeCache.txt before running cmake again.

**Comment by StonePanda** [comment]
THANK U VERY MUCH !!! 
I have tried the command `grep -i iconv CMakeCache.txt` but it returns nothing. It must be something wrong with my Ubuntu env. 
I have tried OPENPOSE in Windows11 and it works well !!!
THANK U FOR UR GREAT WORK !!!

**Comment by StonePanda** [comment]
I am so SORRY, I need to build gdal again and there is still the same error:
I tried the command `grep -i iconv CMakeCache.txt` and it returns:
```
//Set ON to use ICONV
GDAL_USE_ICONV:BOOL=ON
//iconv on windows has individual libcharset
Iconv_CHARSET_LIBRARY:FILEPATH=Iconv_CHARSET_LIBRARY-NOTFOUND
//iconv include directory
Iconv_INCLUDE_DIR:FILEPATH=
//iconv library (potentially the C library)
Iconv_LIBRARY:FILEPATH=/home/user/anaconda3/x86_64-conda-linux-gnu/sysroot/usr/lib/libc.so
//Details about finding Iconv
FIND_PACKAGE_MESSAGE_DETAILS_Iconv:INTERNAL=[/home/user/anaconda3/x86_64-conda-linux-gnu/sysroot/usr/lib/libc.so][v()]
//Test ICONV_HAS_EXTRA_CHARSETS
ICONV_HAS_EXTRA_CHARSETS:INTERNAL=
ICONV_HAS_EXTRA_CHARSETS_COMPILED:INTERNAL=FALSE
//ADVANCED property for variable: Iconv_CHARSET_LIBRARY
Iconv_CHARSET_LIBRARY-ADVANCED:INTERNAL=1
//ADVANCED property for variable: Iconv_INCLUDE_DIR
Iconv_INCLUDE_DIR-ADVANCED:INTERNAL=1
//Test Iconv_IS_BUILT_IN
Iconv_IS_BUILT_IN:INTERNAL=1
//ADVANCED property for variable: Iconv_LIBRARY
Iconv_LIBRARY-ADVANCED:INTERNAL=1
//Test _ICONV_SECOND_ARGUMENT_IS_NOT_CONST
_ICONV_SECOND_ARGUMENT_IS_NOT_CONST:INTERNAL=
```
It seems like that the `Iconv_LIBRARY:FILEPATH` get the wrong value, but I don't know how to fix it.
It would be very grateful if you have any idea to solve this.
Thank u for ur great work!

**Comment by rouault** [comment]
> Iconv_LIBRARY:FILEPATH=/home/user/anaconda3/x86_64-conda-linux-gnu/sysroot/usr/lib/libc.so

It appears that you have a Conda environment enabled. It links to it, but the include dir must be the same one. Basically your build environment is mixed up. Either you should fully build against a Conda environment, or against Ubuntu system libraries, but not mixing both. You need to investigate a bit with generic CMake options to make sure to have a consistent build option (and sorry I don't know them by heart. But this is definitely not a GDAL specific issue)

**Comment by huzaifacontour** [comment]
@StonePanda I'm facing this issue also, did you find a workaround for this?
