### ISSUE TITLE
`GDAL_NUM_THREADS` vs `NUM_THREADS` in COG Creation

### ISSUE THREAD

**Issue by blacha** [OSGeo/gdal#7478]
## Expected behavior and actual behavior.

When creating a COG using the COG driver, I supply `-co NUM_THREADS=ALL_CPUS`  

Recently I was told that also adding `--config  GDAL_NUM_THREADS all_cpus` could improve performance when also applying a warp during the COG creation.

Some basic testing

```bash
time gdal_translate -of COG -co NUM_THREADS=all_cpus  -co compress=zstd -co predictor=yes -co TILING_SCHEME=GoogleMapsCompatible  $INFILE out.tiff

vs

time gdal_translate -of COG -co NUM_THREADS=all_cpus  -co compress=zstd -co predictor=yes -co TILING_SCHEME=GoogleMapsCompatible  --config GDAL_NUM_THREADS all_cpus $INFILE out.tiff
```

```bash
gdal_translate: no-warp

with --config: 54s
without --config: 54s 

gdal_translate --co  TILING_SCHEME=GoogleMapsCompatible

with --config: 1m46s
without --config: 4m16s
```

These tests were done on a 5950x on a 6GB tiff in EPSG:32760 using  gdal3.7.0-dev

Should `--config GDAL_NUM_THREADS` be set automatically by the COG driver, should the docs be updated to recommend using both options? 

Is there any downsides to using both options?

## Operating system

ubuntu-docker

## GDAL version and provenance

gdal3.7.0-dev built with the Dockerfile ubutnu-small from GDAL 3.7.0dev-0c1667a0ed

also tested with GDAL 3.4.1, released 2021/12/27 from ubuntu debian packages

**Comment by rouault** [comment]
> Should `--config GDAL_NUM_THREADS` be set automatically by the COG driver

ah, yes, it's a shortcoming. It should apply it for the warping too

> Is there any downsides to using both options?

no
