### ISSUE TITLE
translate dxf to geojson, "properties" miss some attribute like Multiline text‘s color,rotation and Line's thickness,color etc...

### ISSUE THREAD

**Issue by changkeke** [OSGeo/gdal#7481]
When I translated dxf to geojson, "properties" miss some attribute like Multiline text‘s color,rotation and Line's thickness,color etc...
ex:
![image](https://user-images.githubusercontent.com/33918095/226233051-b0fb6d69-6f8e-4b8d-a576-f61c5da55ac3.png)

**Comment by changkeke** [comment]
@rouault help...

**Comment by jratike80** [comment]
Could you add also dxf test data? Generally speaking, did you read this notice in our bug report template?

> The GDAL project is made of contributions from various individuals and
> organizations, each with their own focus. The issue you are facing is
> not necessarily in the priority list of those contributors and consequently
> there is no guarantee that it will be addressed in a timely manner.
> If this bug report or feature request is high-priority for you, and you
> cannot address it yourself, we suggest engaging a GDAL developer or support
> organisation and financially sponsoring a fix.
