### ISSUE TITLE
pgdump driver puts geometry column first in table structure

### ISSUE THREAD

**Issue by haubourg** [OSGeo/gdal#7482]
## Expected behavior and actual behavior.

Generating a postGIS dump using the ogr pgDump driver generates geometry field as the first field. 
The most common practice around seem to put geometry fieds at the end of a table's structure

## Steps  to reproduce the problem.

- export a ogr PGdump from a postgis database with geometry columns

ogr2ogr -progress --config PG_USE_COPY YES -f PGDump /tmp/dump_test.sql 'PG:service=myservice' -sql  "select * from aschema.atable limit 10 "

- audit the generated DDL ,  the

```sql
SET standard_conforming_strings = OFF;
DROP TABLE IF EXISTS "public"."sql_statement" CASCADE;
BEGIN;
CREATE TABLE "public"."sql_statement" ( "ogc_fid" SERIAL, CONSTRAINT "sql_statement_pk" PRIMARY KEY ("ogc_fid") );
SELECT AddGeometryColumn('public','sql_statement','geom',2154,'GEOMETRY',2);
CREATE INDEX "sql_statement_geom_geom_idx" ON "public"."sql_statement" USING GIST ("geom");
ALTER TABLE "public"."sql_statement" ADD COLUMN "id" VARCHAR NOT NULL;
ALTER TABLE "public"."sql_statement" ADD COLUMN "insee_arr" VARCHAR(1);
ALTER TABLE "public"."sql_statement" ADD COLUMN "insee_dep" VARCHAR(3);
ALTER TABLE "public"."sql_statement" ADD COLUMN "insee_reg" VARCHAR(2);
COPY "public"."sql_statement" ("geom", "id", "insee_arr", "insee_dep", "insee_reg") FROM STDIN;
```

## GDAL version and provenance

GDAL 3.4.3

**Comment by haubourg** [comment]
> Does the behavior make some real issue for you?

Hi, nothing we can't work around for sure. But this will make the dumps different from the data dictionary tools and documentation.  
This is a "comfort" annoyance, but I wanted to raise feedback here and see if others are also concerned. 
There is no demand for fixing for free at all.  ;-)

**Comment by rouault** [comment]
> But this will make the dumps different from the data dictionary tools and documentation.

Can you be more explicit of what you mean by that exactly?

The PG driver also creates the geometry column after the FID one, and before attributes one.

This could also affect ogr2ogr core logic, as when a layer with multiple geometry columns is created, the geometry fields are created before the attribute ones.

**Comment by haubourg** [comment]
> > But this will make the dumps different from the data dictionary tools and documentation.
> 
> Can you be more explicit of what you mean by that exactly?
> 
> The PG driver also creates the geometry column after the FID one, and before attributes one.
> 
> This could also affect ogr2ogr core logic, as when a layer with multiple geometry columns is created, the geometry fields are created before the attribute ones.

Hi Even, 
Yes ogc_fid field is also a concern, since it doesn't exists in the data source. 
We bet on using ogr PGdump driver instead of a native pg_dump + sed post cleanups to be able to export the most interoperable SQL dump possible. 
It works nicely , expect those two annoyances. 
If this would require a full rewrite of gdal's logic, it is probably not worth the effort. I think we can close this issue then

**Comment by rouault** [comment]
implementation in PGDump driver in https://github.com/OSGeo/gdal/pull/7485

**Comment by haubourg** [comment]
Wow thanks Even! I really didn't ask for free job here.

**Comment by jratike80** [comment]
There is a Sponsor button down there in the bottom right corner...

**Comment by jratike80** [comment]
That works as well. Find a candidate contractor for example from https://gdal.org/community/service_providers.html#service-providers, present your plan, and if the service provider is interested, negotiate the price. Larger changes may sometimes need discussion with the community via RFC. As an example the RCF about a new transformation method that National Land Survey of Finland wanted to get into Proj https://proj.org/community/rfc/rfc-6.html.
