### ISSUE TITLE
Use network class from gnm java api

### ISSUE THREAD

**Issue by maheshvitthani** [OSGeo/gdal#749]
Hi, 
I'm  new to use gdal and all things, i m using gnm package in **java** 
I'm trying to use network class to get path from layer, but the problem was how to initialize network class, that i don't know.
can any one help me by giving small example

Thanks,

**Comment by BishopGIS** [comment]
Do you read the tutorial: http://gdal.org/gnm_tut.html ?

Can you share you code that is not working?

**Comment by maheshvitthani** [comment]
Thanks,
Yes, i have read [http://gdal.org/gnm_tut.html]

Below is the code in java using latest **jdal.jar** version 
And **gdaljniall.dll**

But i don't know how to cast in network class,  can you please guide me how to create network by using java ?

please make sure this is using by java 


```
String filePath = "C:\\Users\\mahesh.vitthani\\Downloads\\qgis_sample_data\\shapefiles\\majrivers.shp";
		DataSource dataSource  = ogr.Open(filePath);
		Layer layer = dataSource.GetLayer("majrivers");
		Network network =new Network(1, false);
                network.CopyLayer(layer, "River");
		
		Layer path = network.GetPath(5, 10, GraphAlgorithm.GATDijkstraShortestPath);
```

**Comment by BishopGIS** [comment]
Your code is not working because you open ``ESRI Shape file``  **majrivers.shp** which is not valid GNM dataset.
You need (see mentiond tutorial):
1. Create GNMGenericNetwork like this:

```java
Driver drv = gdal.GetDriverByName('GNMFile')
Dataset ds = drv->Create...
```

2. Load your Shape file into the network

```java
Layer majrivers = ...
ds.CopyLayer(majrivers, 'rivers')
```

3. Create graph connecting geometries of loaded layer

```java
GenericNetwork dgn = gnm.CastToGenericNetwork(ds)
dgn->ConnectFeatures...
``` 

4. And only after valid network will be created, you can make queries like `GetPath`

Sorry, I'm not familiar with GDAL Java bindings. 
Also there are example in unit tests (on python): https://github.com/OSGeo/gdal/blob/master/autotest/gnm/gnm_test.py

**Comment by maheshvitthani** [comment]
Thanks, 

This can be given null
`Driver drv = gdal.GetDriverByName('GNMFile')`


This below can not work in java 
`GenericNetwork dgn = gnm.CastToGenericNetwork(ds)`


Below is full code in java, but not working it can gives null pointer at data source when creating **gnmfile**

           ```
 String filePath = "C:\\Users\\mahesh.vitthani\\Downloads\\qgis_sample_data\\shapefiles\\majrivers.shp";
		
		DataSource dataSource  = ogr.Open(filePath);

              Driver shapeDriver = ogr.GetDriverByName("GNMfile");
	      DataSource dataSource1 = shapeDriver.CreateDataSource("D:\\");
	      dataSource1.CopyLayer(dataSource.GetLayer(0), "rivers");


GenericNetwork genericNetwork= new GenericNetwork(DataSource.getCPtr(dataSource1), true);

Layer layer1 = genericNetwork.GetPath(2, 5, GraphAlgorithm.GATKShortestPath);
```

**Comment by maheshvitthani** [comment]
Thanks, @BishopGIS  
I have tried using those, which you have mentioned, but it was not working 
it work c++ great but not using java 


when i m using 
 ```
Driver shapeDriver = gdal.GetDriverByName("GNMFile");
 Dataset dataset1 =  shapeDriver.Create(path,x,y) //  this methos is for rater image not use for `vector`
```



@rouault  do you have any idea about using java api to making perfect 

How make network file from Esri shapeFile ? please let me if knows 

Thanks

**Comment by maheshvitthani** [comment]
Thanks @BishopGIS  really helpful, solved
