### ISSUE TITLE
gdalwarp: vertical transform with -ot Byte creates holes between tiles

### ISSUE THREAD

**Issue by micpilon** [OSGeo/gdal#7491]
The orthorectification of an orthoready product (LV2A) from DigitalGlobe using RPCs sometimes generates holes in the middle of the images. These holes have a pattern that suggests that they are located at the edges of tiles generated to optimize processing. This issue occurs when the NODATA value on the source is set to 0 and when the -ot for the transformation is Byte. On the other hand, if the -ot is set to Float32, the resulting image is complete. 

Expected behavior would be to propagate the nodata value only for pixels outside the image's valid extent for 8-bit images.

## Expected behavior and actual behavior.

Image warped with `-ot Float32`
<img width="600" alt="warped_float32" src="https://user-images.githubusercontent.com/46534635/226656144-8db6f0be-4c3f-4f04-9c4f-7bfdc9651eb5.PNG">

Image warped with `-ot Byte`
<img width="600" alt="warped_byte" src="https://user-images.githubusercontent.com/46534635/226666397-67e8df01-6ecf-4574-a42f-82a2d5dea3da.PNG">

## Steps to reproduce the problem.

1. Convert image to VRT
`gdal_translate -of VRT "src.tif" "src.vrt"`

2. Warp image using RPCs and DEM
`gdalwarp --config GDAL_NUM_THREADS 16 -wo NUM_THREADS=16 -multi -srcnodata "0" -of GTiff -ot Byte -te 478833.999999999825 5490005.000000000000 498801.500000000000 5508998.000000000931 -tr 0.500000000000 0.500000000000 -co "TILED=YES" -co "BIGTIFF=YES" -t_srs "+proj=utm +zone=10 +datum=WGS84 +units=m +no_defs" -r cubic -et 0.01 -rpc -to "RPC_DEM=src_dsm.tif" src.vrt dst.tif`

## Operating system

Microsoft Windows 10 Entreprise

## GDAL version and provenance

GDAL 3.6.3

**Comment by rouault** [comment]
We would need access to the src.tif and src_dsm.tif dataset. If they cannot be shared publicly, they can possibly be shared to just me (even.rouault at spatialys.com).
You can possibly create the equivalent of src.tif with blanked pixel data in it with "gdal_create -if src.tif src_blanked.tif". The real pixel values of src_dsm.tif are however likely important.

**Comment by rouault** [comment]
@micpilon I don't reproduce the issue with the datasets you've provided.
- Can you re-run gdalwarp and add ``--debug ON`` and look for a line starting with ``GDAL: GDAL_CACHEMAX = `` and indicate the value it gives?
- Which PROJ version do you use ? (cf ``gdalinfo --build`` output)

**Comment by micpilon** [comment]
@rouault Sorry, I realise I provided the wrong bounds in gdalwarp call. I edited the gdalwarp command from the original post accordingly. The glitch showcased in the screenshot should appear at 49.659324° N, 123.085844° W on resulting image. 

> Can you re-run gdalwarp and add --debug ON and look for a line starting with GDAL: GDAL_CACHEMAX =  and indicate the value it gives?

GDAL: GDAL_CACHEMAX = 5816 MB

> Which PROJ version do you use ? (cf gdalinfo --build output)

PROJ_BUILD_VERSION=9.2.0
PROJ_RUNTIME_VERSION=9.2.0



Thanks for your time!

**Comment by rouault** [comment]
Fix in https://github.com/OSGeo/gdal/pull/7496
You can workaround by adding ``-wo SOURCE_EXTRA=10`` (or more if needed)
Note also that as the RPC_DEM dataset has no vertical reference, and RPC warping expects elevation as ellipsoidal heights, but the DEM is likely in orthometric height, you might have an error of +/- 100m on the elevation depending on where you're on Earth
You could workaround that by assigning EGM96 (EPSG:5773) as the vertical reference for the DEM, which will enable GDAL/PROJ to transform the orthometric height of the DSM to WGS84 ellipsoidal height:
```
export WKT=$(projinfo EPSG:32610+5773 -o WKT2:2019 -q)
gdal_translate your_source_dem.tif  your_source_dem_with_vert_reference.vrt -a_srs "$WKT"
```

**Comment by micpilon** [comment]
@rouault  I have been able to fix the issue using the `-wo SOURCE_EXTRA=50` workaround.

Thanks for the heads up on the DSM's vertical referential. It was already converted to ellipsoidal using a method outside of GDAL (h = H + N). Could take a further look at transforms already handled with GDAL/PROJ.
