### ISSUE TITLE
Erroneous call to OGRAllRegister ?

### ISSUE THREAD

**Issue by tbonfort** [OSGeo/gdal#7511]
Using gdalwarp through its C api,  when using -crop there is a call to OGRRegisterAll:

https://github.com/OSGeo/gdal/blob/89e3fc244652771ca4f8abc0a6fe5794e2201b26/apps/gdalwarp_lib.cpp#L3198

Is this intended? It would seem to me that it is up to the caller to ensure that the required driver has already been loaded, not to mention that IIRC the OGRRegisterAll function should not be called concurrently across multiple threads, which is not a requirement for GDALWarp itself.

**Comment by rouault** [comment]
> Is this intended?

Good catch. There are left-overs of the times where the utilities where standalone binaries only and before the GDAL 2.0 GDAL/OGR unification.
