### ISSUE TITLE
missing subdatasets in HDF read

### ISSUE THREAD

**Issue by jdmcbr** [OSGeo/gdal#7514]
## Expected behavior and actual behavior.
I'm not able to read all subdatasets from an hdf file (specifically from MODIS) in GDAL in the latest stable ubuntu release (22.04) vs the prior stable ubuntu release (20.04).

## Steps to reproduce the problem.
With gdal in ubuntu 20.04, installed with `apt install gdal-bin`:

```
$ gdalinfo --version                                                          
GDAL 3.0.4, released 2020/01/28
$ gdalinfo MOD04_L2.A2017156.1815.061.2017315140531.hdf | grep SUBDATASET | wc
    284     780   26696
```

With gdal in ubuntu 22.04, installed with `apt install gdal-bin`:

```
$ gdalinfo --version
GDAL 3.4.1, released 2021/12/27
$ gdalinfo MOD04_L2.A2017156.1815.061.2017315140531.hdf | grep SUBDATASET | wc
    140     420   14588
```

Roughly ~half of the subdatasets are not visible/readable in GDAL in the more recent LTS ubuntu release (140 in GDAL 3.4.1, 284 in GDAL 3.0.4). I haven't checked the very latest GDAL, but I see the same behavior in `GDAL 3.5.1, released 2022/06/30` installed from source. If possible that a more recent GDAL version is likely to remedy this, I'm happy to install from source and test.

## Operating system

Ubuntu 22.04

## GDAL version and provenance
GDAL 3.4.1, released 2021/12/27, installed from default ubuntu ppa

## Example file
[MOD04_L2.A2017156.1815.061.2017315140531.hdf.zip](https://github.com/OSGeo/gdal/files/11068285/MOD04_L2.A2017156.1815.061.2017315140531.hdf.zip)

**Comment by rouault** [comment]
yes, this is expected. There has been an enhancement to remove duplicated subdatasets. In GDAL 3.0, you had the same subdatasets reported both as HDF4_EOS:EOS_SWATH: and HDF4_SDS:UNKNOWN:
In more recent GDAL versions (>= 3.2), they are only reported as HDF4_EOS:EOS_SWATH: , at least by default.
You may get the whole list of subdatasets by adding ``-oo LIST_SDS=YES``, but this should bring little added value

**Comment by jdmcbr** [comment]
@rouault Thanks so much for the quick response! I had looked some in the changelog for whether this was an intended change and didn't catch this, but makes sense.

I'm admittedly fairly unfamiliar with HDF storage, so there may be some better way to handle this, but the HDF files from MODIS I'm working with don't have a geospatial transform set, and instead have Latitude and Longitude written as subdatasets. Using LIST_SDS=YES gets me the Longitude/Latitude info I was looking for.

**Comment by rouault** [comment]
The geolocation arrays are automatically attached to EOS_SWATH when possible.

e.g. :
```
$ gdalinfo HDF4_EOS:EOS_SWATH:"MOD04_L2.A2017156.1815.061.2017315140531.hdf":mod04:Image_Optical_Depth_Land_And_Ocean
[...]
Geolocation:
  LINE_OFFSET=0
  LINE_STEP=1
  PIXEL_OFFSET=0
  PIXEL_STEP=1
  SRS=
  X_BAND=1
  X_DATASET=HDF4_EOS:EOS_SWATH_GEOL:"MOD04_L2.A2017156.1815.061.2017315140531.hdf":mod04:Longitude
  Y_BAND=1
  Y_DATASET=HDF4_EOS:EOS_SWATH_GEOL:"MOD04_L2.A2017156.1815.061.2017315140531.hdf":mod04:Latitude
```

**Comment by jdmcbr** [comment]
Oh thanks, I wasn't aware of that. I really appreciate the direction!
