### ISSUE TITLE
OpenFileGdb handles only vector data

### ISSUE THREAD

**Issue by XRolland** [OSGeo/gdal#752]
## Expected behavior and actual behavior.
When I read [the doc](http://gdal.org/drv_openfilegdb.html), there's no restriction or drawback explained about raster data. 

## Steps to reproduce the problem.
Read the doc. :-)

Or trying to open a file geodatabase with some raster data under QGIS. 
Or:
```
"C:\Program Files\QGIS 3.2\bin\ogrinfo.exe" "R:\Toto.gdb"
Had to open data source read-only.
INFO: Open of `Toto.gdb'
      using driver `OpenFileGDB' successful.
```

Or (maybe it's stupid... but nobody told me) :

```
"C:\Program Files\QGIS 3.2\bin\gdalinfo.exe" "Toto.gdb"
ERROR 4: Toto.gdb: Permission denied
gdalinfo failed - unable to open 'Toto.gdb'
```

## Operating system
W10

## GDAL version and provenance
2.2.4, shipped with QGIS 3.2.0 win64

**Comment by XRolland** [comment]
Until it will one day maybe implemented, perhaps someone has just to specify that's a vector/ogr only driver in the doc?

**Comment by XRolland** [comment]
Thanks for improving the doc, @rouault . Is there a hope that the driver could read raster data one day?

**Comment by rouault** [comment]
There is always hope... Anyone is welcome to contribute it. There were some preliminary work on reverse engineering it which were promising

**Comment by XRolland** [comment]
I'm not able to contribute to code. But, now I keep the hope. :-); 
Thanks for your work on this driver.
