### ISSUE TITLE
ogr2ogr: add reduceprecision functionality

### ISSUE THREAD

**Issue by theroggy** [OSGeo/gdal#7520]
It would be great to have an equivalent to the [ST_ReducePrecision](https://postgis.net/docs/ST_ReducePrecision.html) function in ogr2ogr/ogr API to be able to round coordinates and remove slivers narrower than the precision specified from a dataset.

Something like this:
```
ogr2ogr [-reduceprecision gridsize]
```

I'm not sure how ogr2ogr would deal with geometries that would become empty geometries because of this, but I suppose they would be saved as null geometries. I'm not sure if the existing `-where` function would be evaluated after `-reduceprecision`... If so it would be possible to handle the filtering there. If not, a `-filteremptygeometries` option might be useful as well to offer the option not to save those.

Probably it is also useful to consider using this when converting coordinates to strings like for conversion to WKT, geojson,... because that way the geometries would/should still be valid after rounding the coordinates.

**Comment by jratike80** [comment]
You could try to make a feature request for SpatiaLite and by that route also to the SQLite SQL dialect.

**Comment by theroggy** [comment]
> You could try to make a feature request for SpatiaLite and by that route also to the SQLite SQL dialect.

I also kind of did that, but I suggested broader support for the precision options available in geos, [here](https://groups.google.com/g/spatialite-users/c/6mWQCM5686M).

A few hours ago I also remembered the option to use ST_makevalid(ST_snaptogrid(...)), but I'm not sure if it leads to the same results and/or performance of using geos set_precision(). So I'm planning to do some tests on that option.

Nonetheless, having dedicated support for it in the OGR API and ogr2ogr sounds nice as well, also because of the options is opens to creating consistently valid wkt, geojson,...

**Comment by theroggy** [comment]
I've done some further testing for this and with the basic tests I did it became that (logically) `ST_makevalid(ST_snaptogrid(...))` isn't sufficient to replace `ST_ReducePrecision()`. An `ST_CollectionExtract()` is necessary as well to e.g. extract only polygons if the initial input geometry was a polygon and the `ST_snaptogrid()` resulted in some parts of the polygon to collapse to e.g. lines.

If the layer being selected from only contains geometries of the same type this is still possible, but if it contains different geometry types the query becomes really cumbersome to extract the correct geometry types.

I could do some more testing on the results being produced by both approaches, but anyway it seems clear that having access to the function as it is implemented in geos/postGIS is the best solution. So, I also created a feature request specifically for ST_Reduceprecision in the spatialite forum: https://groups.google.com/g/spatialite-users/c/3ITVRH3gCa0

**Comment by theroggy** [comment]
New update on this: using `ST_CollectionExtract(ST_makevalid(ST_snaptogrid(...)))` leads to some results but isn't sufficient. Because it only rounds all coordinates to a certain precision (e.g. 1 millimeter precision), it sill leaves many narrow slivers (e.g. < 1 mm) because just rounding coordinates isn't sufficient to clean them up.

Good news though: `GEOS setprecision` does a much better job and has been added in [Spatialite 5.1 as ST_ReducePrecision](https://groups.google.com/g/spatialite-users/c/3ITVRH3gCa0), so it should be become usable in gdal shortly using sql_dialect="SQLITE".

So, I'll close this ticket as the functionality has become available...
