### ISSUE TITLE
New rasterize behaviour is missing pixels that should be included

### ISSUE THREAD

**Issue by jontwo** [OSGeo/gdal#7523]
## Expected behavior and actual behavior.

There was a recent change to GDAL rasterize that meant pixels with a small overlap were no longer included. For example, we have a 5m tapped raster and when you rasterize a polygon that slightly overlaps the pixels on the left hand edge (vertices are 475439.99661332502728328m in the x direction vs pixel boundary of 475440m)

![image](https://user-images.githubusercontent.com/5537223/227925947-5ddf8e24-83fd-46e5-8c89-fa46d1095580.png)

Previously it was rasterized to this:

```
array([[1, 1, 0],
       [1, 1, 0],
       [1, 1, 0],
       [1, 1, 1],
       [1, 1, 1]], dtype=uint8)
```

but now you get this:

```
array([[1, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 1],
       [1, 1, 1]], dtype=uint8)
```

If the top left and bottom left pixels are included, the ones in between should also be included because they overlap by the same amount.

Is this a side effect of the fix for #6414?

## Steps to reproduce the problem.

Rasterize a polygon where two vertices slightly overlap a row/column of pixels (by a proportion less than 0.01)

## Operating system

Ubuntu 22.04 64 bit

## GDAL version and provenance

This was working at 3.5.1 but broken at 3.6.2.

**Comment by rouault** [comment]
Please provide a source dataset and the gdal_rasterize (or Python scription) to reproduce the issue

**Comment by jontwo** [comment]
[ras_test.zip](https://github.com/OSGeo/gdal/files/11080893/ras_test.zip)
Unzip the attached file or rename to .shz then
```
gdal_rasterize -at -tr 5 5 -te 475435 424120 475450 424145 -burn 1 ras_test.shz out.tif
```

At GDAL v3.6.2 I get this

![image](https://user-images.githubusercontent.com/5537223/228003216-b6aa5094-398d-4548-9555-9453ccf470fe.png)

At GDAL v3.0.4 I get this

![image](https://user-images.githubusercontent.com/5537223/228003315-98634331-1720-48a0-9aaa-4fc9738254a3.png)

**Comment by rouault** [comment]
fix proposed in https://github.com/OSGeo/gdal/pull/7526
