### ISSUE TITLE
Replacement of deprecated CRSes should be disabled by default, or at least noisy

### ISSUE THREAD

**Issue by Kodiologist** [OSGeo/gdal#7524]
As pointed out in #5106, GDAL will replace deprecated CRSes. This can be disabled with `OSR_USE_NON_DEPRECATED=NO`, but the fact that it happens by default, and without warning, is dangerous for scientific code that is intended to be reproducible. The user asks for one projection, silently gets something else, and can get pretty perplexed trying to find out what changed, if they even notice. (Ask me how I know.) I don't think #5108 is sufficient because it seems to only affect `gdalsrsinfo`.

I think the right thing to do here would be to always use the requested CRS, and offer a separate feature to upgrade a CRS to its non-deprecated equivalent if one exists.

**Comment by jratike80** [comment]
Or should the default be to do nothing else but send a message "deprecated" and require user to make an explicit selection? I think that deprecation is meant to be taken seriously, and therefore non-registered users cannot even get the definitions of EPSG:3411 from https://epsg.org. Registered user can see the remark

> The datum is unspecified. Uncertainty in location of over 1 km may result; at the coarse resolution and very small scales for which this system should be used this uncertainty may be insignificant. See CRS 3413 for geodetically preferred alternative.

**Comment by Kodiologist** [comment]
> Or should the default be to do nothing else but send a message "deprecated" and require user to make an explicit selection?

That seems reasonable.

**Comment by rouault** [comment]
Asking to users is not really an option for a library like GDAL which has generally no way to interact with it. I would be leaning towards moving the warning from gdalsrsinfo to the importFromEPSG() method where the substitution is done. I guess it is impossible to reach a consensus on the default value for the configuration option. There are certainly use cases where substitution makes sense (and given the current config option people don't complain about that), and others where people can still make something useful with the deprecated object...

**Comment by Kodiologist** [comment]
That looks like a big improvement. Thanks.
