### ISSUE TITLE
OpenFileGdb can't read data from a compressed file geodatabase

### ISSUE THREAD

**Issue by XRolland** [OSGeo/gdal#753]
## Expected behavior and actual behavior.
When I read [the doc](http://gdal.org/drv_openfilegdb.html), there's no restriction or drawback explained about compressed file geodatabase. 

In ArcGIS, you can compress your file GDB with a dedicated tool. In fact, you choose one or more data inside the GDB to compress, and if you want lossless or lossy compression. After executing this tool, GDB became read-only in ArcGIS and it's reputed to increase speed access for ArcGIS software.

## Steps to reproduce the problem.
```
"C:\Program Files\QGIS 3.2\bin\ogrinfo.exe" "R:\Compressed_Toto.gdb"
Warning 1: Topo_ASC layer has a R:\Compressed_Toto.gdb\a00000009.gdbtable.cdf file whose format is unhandled
Warning 1: SousTypes layer has a R:\Compressed_Toto.gdb\a0000000a.gdbtable.cdf file whose format is unhandled
Warning 1: CpRp_Pln layer has a R:\Compressed_Toto.gdb\a0000000b.gdbtable.cdf file whose format is unhandled
Warning 1: FUS_Pgn layer has a R:\Compressed_Toto.gdb\a0000000c.gdbtable.cdf file whose format is unhandled
Warning 1: Topo_Stations layer has a R:\Compressed_Toto.gdb\a0000000d.gdbtable.cdf file whose format is unhandled
Warning 1: Emprise_Pgn layer has a R:\Compressed_Toto.gdb\a0000000e.gdbtable.cdf file whose format is unhandled
Warning 1: FUS_Pln layer has a R:\Compressed_Toto.gdb\a0000000f.gdbtable.cdf file whose format is unhandled
Warning 1: CFSd_Pln layer has a R:\Compressed_Toto.gdb\a00000011.gdbtable.cdf file whose format is unhandled
Warning 1: Topo_Pgn layer has a R:\Compressed_Toto.gdb\a00000012.gdbtable.cdf file whose format is unhandled
Warning 1: Topo_Pln layer has a R:\Compressed_Toto.gdb\a00000013.gdbtable.cdf file whose format is unhandled
Warning 1: Topo_Pts layer has a R:\Compressed_Toto.gdb\a00000014.gdbtable.cdf file whose format is unhandled
Warning 1: Bati layer has a R:\Compressed_Toto.gdb\a00000015.gdbtable.cdf file whose format is unhandled
Warning 1: Profondeur layer has a R:\Compressed_Toto.gdb\a00000018.gdbtable.cdf file whose format is unhandled
Warning 1: CFSd_Pgn layer has a R:\Compressed_Toto.gdb\a0000001a.gdbtable.cdf file whose format is unhandled
Warning 1: Sep_Pgn layer has a R:\Compressed_Toto.gdb\a0000009e.gdbtable.cdf file whose format is unhandled
Warning 1: FUS_Bords layer has a R:\Compressed_Toto.gdb\a0000009f.gdbtable.cdf file whose format is unhandled
FAILURE:
Unable to open datasource `R:\Compressed_Toto.gdb' with the following drivers.
  -> JP2ECW
  -> OCI
  -> SOSI
  -> PCIDSK
  -> netCDF
(...)
```
=> OGR is able to see my compressed data but can't read them.

## Operating system

W10

## GDAL version and provenance

GDAL 2.2.4, shipped with QGIS 3.2.0 win64

**Comment by rouault** [comment]
This is mentionned in the doc "Cannot read data from compressed data in CDF format (Compressed Data Format)."

**Comment by XRolland** [comment]
Ok I'm stupid! ;-)
But as a long time ArGIS user I never heard or read about this name (CDF). 
Maybe something like this could be useful in the doc ?

> Cannot read data from compressed data in CDF format (Compressed Data Format), which are produced by the ESRI/ArcGIS file geodatabase compression tool

**Comment by aabdelw1** [comment]
What doc are you guys referring too? I am running into the same issue and can't find anything about it

**Comment by Jbollenbacher** [comment]
Revisiting this issue 2024.  Is there progress on this or a workaround?  Can geodatabases containing .gdbtable.cdf files be converted into uncompressed format?

**Comment by rouault** [comment]
> Is there progress on this or a workaround?

no

>  I have a file which only exists in .gdbtable.cdf and I dont have access to native esri software to open it.

you have to build the FileGDB driver then based on the ESRI SDK: https://gdal.org/drivers/vector/filegdb.html
