### ISSUE TITLE
gdal2tiles.py - openlayers - layer switcher exception

### ISSUE THREAD

**Issue by paalmiso** [OSGeo/gdal#7544]
Hello,

using gdal2tiles.py from GDAL 3.6.2, generated openlayers html have problems with layerswitcher plugin.

it is throwing this exception to console:
```
Uncaught TypeError: Class constructor hh cannot be invoked without 'new'
at new LayerSwitcher (ol-layerswitcher@3.5.0:126:119)
at openlayers.html:96:24
```

Thank you!

**Comment by rouault** [comment]
> generated openlayers html have problems with layerswitcher plugin.

It looks like out of scope of the GDAL project. The only thing we want to demonstrate with the generated openlayers.html file is base display functionnality

**Comment by paalmiso** [comment]
Maybe I was not clear enough, layerswitcher is used in generated html by gdal2tiles.py, and it is throwing errors.

**Comment by paalmiso** [comment]
Actually I've found a fix simply increasing version of ol-layerswitcher to 4.1.1 will try to commit it if possible
