### ISSUE TITLE
No layer in NetCDF file with gdal version used by QGIS 3.30

### ISSUE THREAD

**Issue by ludo-ifr** [OSGeo/gdal#7550]
Dear Gdal,
I was using QGIS 3.14 (GDAL/OGR 3.0.4) to open a NETCDF file
And I was able to plot the trajectory with color depending on a variable

Using QGIS 3.30 (GDAL/OGR 3.6.2) this is no working anymore.

I have sent the issue to QGIS members [issue 52418](https://github.com/qgis/QGIS/issues/52418)  and after digging they redirected me to you.

Using ogrinfo 3.0.4 I can see a layer:

````
1: AR_TS_TS_58GS_changed_traj (3D Point)
````

Using ogrinfo 3.6.2  I cannot see any layer.

Link to the file : [trajectory file](https://drive.google.com/file/d/1dTR-JOgnjWDH2ZPvixLuwFo9kAFGVAuy/view?usp=share_link) 

Best regards

**Comment by jef-n** [comment]
> Issue confirmed. ogrinfo does open the dataset, reports attributes, but fails to report the layer.

ouch.

**Comment by agiudiceandrea** [comment]
Hi @rouault, the same user reported an issue with another nc layer: please see https://github.com/qgis/QGIS/issues/52418#issuecomment-1794531692 and https://github.com/qgis/QGIS/issues/52418#issuecomment-1797965895.
