### ISSUE TITLE
ogr2ogr convert shape file to oracle spatial database 

### ISSUE THREAD

**Issue by amwps290** [OSGeo/gdal#7551]
when i use ogr2ogr convert shape file to oracle database ,the SRID OF USER_SDO_GEOM_METADATA is not correct. 

the sql is :

```sql
INSERT INTO USER_SDO_GEOM_METADATA VALUES ('BJROAD', 'ORA_GEOMETRY', MDSYS.SDO_DIM_ARRAY(MDSYS.SDO_DIM_ELEMENT('X',12843486.24727394,13080040.17120964,0.001),MDSYS.SDO_DIM_ELEMENT('Y',4781532.934468937,5024640.603382006,0.001)), 1000026974)
```

the SRID shoule be EPSG:3857,not 1000026974.

then i use the -a_srs EPSG:3857 it not worked.

**Comment by jratike80** [comment]
If I remember right the standard `-a_srs` does not work with Oracle but the driver has a specific `SRID` creation option https://gdal.org/drivers/vector/oci.html.
