### ISSUE TITLE
OGR C API: possibility to expose OGRGetISO8601DateTime functionality?

### ISSUE THREAD

**Issue by jorisvandenbossche** [OSGeo/gdal#7555]
## Expected behavior and actual behavior.

Currently, when you get a string from a OFTDateTime field (using `OGR_F_GetFieldAsString`), you get a string formatted as "YYYY/MM/DD HH:MM:SS.sss+ZZ":

https://github.com/OSGeo/gdal/blob/991ecec26161e5ab0cb53a01120efd432455def5/ogr/ogrfeature.cpp#L2546-L2553

This is not an ISO formatted string (using `/` instead of `-` as the separator in the date part). Getting a ISO formatted string is implemented (`OGRGetISO8601DateTime`) and used internally for certain drivers, I think, but not exposed through the C API. 

Would there be interest to enable this via the C API? For example a `OGR_F_GetFieldAsISO8601DateTime`? (I suppose the existing behaviour of `OGR_F_GetFieldAsString` cannot easily be changed for backwards compatibility)

**Comment by rouault** [comment]
Do you absolutely need a string ? Otherwise OGR_F_GetFieldAsDateTimeEx() should do the job

**Comment by jorisvandenbossche** [comment]
Yes, I am aware of `OGR_F_GetFieldAsDateTimeEx` (and that's also what we currently use in pyogrio and fiona), but I ran into this because I was looking into an alternative way to construct the data on the python side, going through a string instead of going through the datetime components. 

And I was looking into this partly as an easier way to get the timezone information (xref https://github.com/geopandas/pyogrio/issues/123#issuecomment-1494380636), and in addition this also turns out to be faster (in practice, going through strings doesn't need to be faster (or isn't expected to be faster), but it just happens that we have fast, vectorized string parsers on the python side, while constructing from the components is slower).

So it's more that to handle those values on the python side, we have more and better tools available to work with an array of strings, compared to an array of year/month/day/hour/.. components.

For pyogrio specifically, in the end we actually want an integer (like unix epoch values, just not necessarily in seconds but in milliseconds), so neither the string representation or the components. And the question is what's the easiest way to convert from something to that integer.

**Comment by rouault** [comment]
> For example a `OGR_F_GetFieldAsISO8601DateTime`?

ok, that makes sense if you want to propose this. I can imagine that it would take a final ``CSLConstList papszOptions`` argument, even if unused currently as a provision for customization of the output (like normalizing to UTC, etc.)

**Comment by rouault** [comment]
implemeneted per https://github.com/OSGeo/gdal/pull/7607

**Comment by jorisvandenbossche** [comment]
Thanks for adding this!
