### ISSUE TITLE
CMake build issues with ndk-23c on Mac-OSX (GDAL release/3.6)  -ANDROID_ARCH_ABI=arm64-v8a

### ISSUE THREAD

**Issue by beikehanbao23** [OSGeo/gdal#7557]
Hi all, I compile gdal for my android application.

According to the method in the link below  

[https://github.com/OSGeo/gdal/blob/master/.github/workflows/android_cmake/start.sh(https://github.com/OSGeo/gdal/blob/master/.github/workflows/android_cmake/start.sh) , 

I modified the above script for mac as follows

#---------------------------------------------------------------

export ANDROID_NDK=/Users/comeed/code/github/gdal/ci/travis/android/android-ndk-r23c
# mac NDK_TOOLCHAIN
export NDK_TOOLCHAIN=$ANDROID_NDK/toolchains/llvm/prebuilt/darwin-x86_64
export CMAKE_ANDROID_NDK=$ANDROID_NDK

ccache -M 1G
ccache -s

#---------------------------------------------------------------
# SQLite
wget -q https://sqlite.org/2022/sqlite-autoconf-3370200.tar.gz
tar xzf sqlite-autoconf-3370200.tar.gz
cd sqlite-autoconf-3370200
CC="ccache $NDK_TOOLCHAIN/bin/aarch64-linux-android24-clang" ./configure \
  --prefix=/tmp/install --host=aarch64-linux-android24
make -j3
make install
cd ..

#---------------------------------------------------------------
# Build proj
wget -q https://download.osgeo.org/proj/proj-9.0.0.tar.gz
tar xzf proj-9.0.0.tar.gz
cd proj-9.0.0
mkdir build
cd build
# See later comment in GDAL build section about MAKE_FIND_ROOT_PATH_MODE_INCLUDE, CMAKE_FIND_ROOT_PATH_MODE_LIBRARY

# Build GDAL
mkdir build_android_cmake
cd build_android_cmake

cmake .. \
  -DUSE_CCACHE=ON \
  -DENABLE_TIFF=OFF -DENABLE_CURL=OFF -DBUILD_APPS=OFF -DBUILD_TESTING=OFF \
  -DCMAKE_INSTALL_PREFIX=/tmp/install \
  -DCMAKE_SYSTEM_NAME=Android \
  -DCMAKE_ANDROID_NDK=$ANDROID_NDK \
  -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a \
  -DCMAKE_SYSTEM_VERSION=24 \
  "-DCMAKE_PREFIX_PATH=/tmp/install;$NDK_TOOLCHAIN/sysroot/usr/" \
  -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=NEVER \
  -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=NEVER \
  -DEXE_SQLITE3=/usr/bin/sqlite3

**Comment by beikehanbao23** [comment]
I got an error in the step [# Build GDAL - > make -j3]
The build log

Hoping for your help, I've been stuck on this for quite some time now. Thank you all
------------- 
[ 94%] Built target ogrsf_generic
[ 94%] Building CXX object gcore/CMakeFiles/gcore.dir/gdalallvalidmaskband.cpp.o
[ 94%] Building CXX object gcore/CMakeFiles/gcore.dir/gdalnodatavaluesmaskband.cpp.o
[ 94%] Building CXX object gcore/CMakeFiles/gcore.dir/gdalnodatamaskband.cpp.o
[ 94%] Building CXX object gcore/CMakeFiles/gcore.dir/gdalproxydataset.cpp.o
[ 94%] Building CXX object gcore/CMakeFiles/gcore.dir/gdalproxypool.cpp.o
[ 94%] Building CXX object gcore/CMakeFiles/gcore.dir/gdaldefaultasync.cpp.o
[ 95%] Building CXX object gcore/CMakeFiles/gcore.dir/gdaldllmain.cpp.o
[ 95%] Building CXX object gcore/CMakeFiles/gcore.dir/gdalexif.cpp.o
[ 95%] Building CXX object gcore/CMakeFiles/gcore.dir/gdalgeorefpamdataset.cpp.o
[ 95%] Building CXX object gcore/CMakeFiles/gcore.dir/gdalvirtualmem.cpp.o
[ 95%] Building CXX object gcore/CMakeFiles/gcore.dir/gdaljp2abstractdataset.cpp.o
[ 95%] Building CXX object gcore/CMakeFiles/gcore.dir/gdaloverviewdataset.cpp.o
[ 95%] Building CXX object gcore/CMakeFiles/gcore.dir/gdalrescaledalphaband.cpp.o
[ 95%] Building CXX object gcore/CMakeFiles/gcore.dir/gdaljp2structure.cpp.o
[ 95%] Building CXX object gcore/CMakeFiles/gcore.dir/gdal_mdreader.cpp.o
[ 95%] Building CXX object gcore/CMakeFiles/gcore.dir/gdalabstractbandblockcache.cpp.o
[ 95%] Building CXX object gcore/CMakeFiles/gcore.dir/gdaljp2metadatagenerator.cpp.o
[ 96%] Building CXX object gcore/CMakeFiles/gcore.dir/gdalarraybandblockcache.cpp.o
[ 96%] Building CXX object gcore/CMakeFiles/gcore.dir/gdalrelationship.cpp.o
[ 96%] Building CXX object gcore/CMakeFiles/gcore.dir/gdalhashsetbandblockcache.cpp.o
[ 96%] Building CXX object gcore/CMakeFiles/gcore.dir/overview.cpp.o
[ 96%] Building CXX object gcore/CMakeFiles/gcore.dir/rasterio.cpp.o
[ 96%] Building CXX object gcore/CMakeFiles/gcore.dir/rawdataset.cpp.o
[ 96%] Building CXX object gcore/CMakeFiles/gcore.dir/gdalmultidim.cpp.o
[ 96%] Building CXX object gcore/CMakeFiles/gcore.dir/gdalpython.cpp.o
[ 96%] Building CXX object gcore/CMakeFiles/gcore.dir/gdalpythondriverloader.cpp.o
[ 96%] Building CXX object gcore/CMakeFiles/gcore.dir/tilematrixset.cpp.o
[ 97%] Building CXX object gcore/CMakeFiles/gcore.dir/nasakeywordhandler.cpp.o
[ 97%] Building CXX object gcore/CMakeFiles/gcore.dir/gdal_thread_pool.cpp.o
[ 97%] Built target gcore
[ 97%] Linking CXX shared library libgdal.so
ld: error: undefined symbol: json_object_put
>>> referenced by cpl_json.cpp:55 (/Users/metesau/code/github/gdal/port/cpl_json.cpp:55)
>>>               port/CMakeFiles/cpl.dir/cpl_json.cpp.o:(CPLJSONDocument::~CPLJSONDocument())
>>> referenced by cpl_json.cpp:69 (/Users/metesau/code/github/gdal/port/cpl_json.cpp:69)
>>>               port/CMakeFiles/cpl.dir/cpl_json.cpp.o:(CPLJSONDocument::operator=(CPLJSONDocument const&))
>>> referenced by cpl_json.cpp:87 (/Users/metesau/code/github/gdal/port/cpl_json.cpp:87)
>>>               port/CMakeFiles/cpl.dir/cpl_json.cpp.o:(CPLJSONDocument::operator=(CPLJSONDocument&&))
>>> referenced 111 more times
>>> did you mean: _json_object_put
>>> defined in: /usr/local/Cellar/json-c/0.16/lib/libjson-c.a

ld: error: undefined symbol: json_object_get
>>> referenced by cpl_json.cpp:59 (/Users/metesau/code/github/gdal/port/cpl_json.cpp:59)
>>>               port/CMakeFiles/cpl.dir/cpl_json.cpp.o:(CPLJSONDocument::CPLJSONDocument(CPLJSONDocument const&))
>>> referenced by cpl_json.cpp:70 (/Users/metesau/code/github/gdal/port/cpl_json.cpp:70)
>>>               port/CMakeFiles/cpl.dir/cpl_json.cpp.o:(CPLJSONDocument::operator=(CPLJ

**Comment by rouault** [comment]
It seems that your build tries to link to your host libjson library. You need to tweak CMake cross compilation options to forbid it to use your homebrew host packages. Perhaps try -DGDAL_USE_EXTERNAL_LIBS=OFF too. Cf https://gdal.org/development/building_from_source.html#cmdoption-arg-GDAL_USE_EXTERNAL_LIBS-BOOL

**Comment by beikehanbao23** [comment]
@rouault 
I see the 100% progress. "DGDAL_USE_EXTERNAL_LIBS=OFF" Solved my problem.

I want to express the depth of my gratitude to you.

Hope this is useful to others too

> It seems that your build tries to link to your host libjson library. You need to tweak CMake cross compilation options to forbid it to use your homebrew host packages. Perhaps try -DGDAL_USE_EXTERNAL_LIBS=OFF too. Cf https://gdal.org/development/building_from_source.html#cmdoption-arg-GDAL_USE_EXTERNAL_LIBS-BOOL
