### ISSUE TITLE
feature request, PG: append geom column at the end of the row

### ISSUE THREAD

**Issue by tobwen** [OSGeo/gdal#756]
Would it be possible to move geometry column to the end of the row? When looking into the data using `psql` or `pgAdmin` (and of course others), geometry columns is pretty wide and attributes are starting on the very right side of the screen. On smaller screens this produces problems and makes you to scroll all the time.

Of course, a workaround is to use `-select "..., ..., geom"`, but then all the attributes need to be listed manually.

**Comment by rouault** [comment]
Closing. Can be done using the PGDump driver with option

 <Option name="GEOM_COLUMN_POSITION" type="string-select" description="Whether geometry/geography columns should be created as soon they are created (IMMEDIATE) or after non-spatial columns" default="IMMEDIATE">
    <Value>IMMEDIATE</Value>
    <Value>END</Value>
  </Option>
