### ISSUE TITLE
gdal.Warp not outputing image with proper dimensions

### ISSUE THREAD

**Issue by cstutts** [OSGeo/gdal#7562]
## Expected behavior and actual behavior.

I am converting Copernicus 30 meter DEM from vertical datum EGM2008 to WGS84 using gdal.Warp in Python, which should return an image with the same extents and image shape. However, I have encountered cases where the return shape is not the same as the input. 

## Steps to reproduce the problem.

result = gdal.Warp(
        "",
        str(dem_file),
        format="MEM",
        warpOptions=wo,
        multithread=True,
        resampleAlg="bilinear",
        srcSRS=source_srs,
        dstSRS=dest_srs,
        srcNodata=nodata,
        dstNodata=nodata,
    )
dem = gdal_array.DatasetReadAsArray(result)

where: 
wo = ["WRITE_FLUSH=YES", "OPTIMIZE_SIZE=YES"]
source_srs = "+proj=longlat +datum=WGS84 +no_defs +geoidgrids=" + gtx_file
dest_srs = "+proj=longlat +datum=WGS84 +no_def"
gtx_file is a 1 minute EGM2008 geoid file that can be downloaded here: https://s3-eu-west-1.amazonaws.com/download.agisoft.com/gtg/us_nga_egm2008_1.tif
nodata=-32768

Works fine until I reach DEM file: Copernicus_DSM_COG_10_N50_00_E000_00_DEM.tif
This file has a spatial reference with CRS=EPSG:4326, shape:rows=3600, cols=2400) and Affine transform: Affine(0.00041666666666666664, 0.0, -0.00020833333333333332,
       0.0, -0.0002777777777777778, 51.00013888888889)

I would expect the dem loaded back in to be size 3600x2400 since this is just a vertical datum switch. However, dem is size 3059x3059 with spatial information:
CRS=EPSG:4326, shape:rows=3059, cols=3059 and Affine transform: 
Affine(0.00032686022523030673, 0.0, -0.00020833333333333332,
       0.0, -0.00032686022523030673, 51.00013888888889)

## Operating system

WSL Ubuntu 20.04.6 LTS

## GDAL version and provenance

GDAL version 3.4.2 built from source
[Copernicus_DSM_COG_10_N50_00_E000_00_DEM.zip](https://github.com/OSGeo/gdal/files/11171654/Copernicus_DSM_COG_10_N50_00_E000_00_DEM.zip)

**Comment by rouault** [comment]
Resolved per https://github.com/OSGeo/gdal/pull/7565
The default behaviour of gdalwarp is to generate square pixels, whatever their source resolution. This has been amended in GDAL 3.7.0dev for situations where no reprojection is involved.
For existing released versions the workaround is to specify explicitly the bounds (outputBounds options) and resolution (xRes and yRes options) to be the same as the input

**Comment by mdsumner** [comment]
nice 🤘

**Comment by cstutts** [comment]
Ok. I added xRes and yRes and matched these too the input file's X and Y res respectively, which got me past several more files where the X and Y pixel sizes are different, but I noticed gdal.Warp is just hanging on this file without producing any results.
[Copernicus_DSM_COG_10_N51_00_W180_00_DEM.zip](https://github.com/OSGeo/gdal/files/11174581/Copernicus_DSM_COG_10_N51_00_W180_00_DEM.zip)

**Comment by cstutts** [comment]
If I provide outputBounds, it finishes quickly. I seem to be off by half a res though on my bounds. gdal.Warp is definitely getting stuck though if I provide xRes, yRes, without providing outputBounds.

**Comment by cstutts** [comment]
Finished processing all the files. Not sure why gdal.Warp gets stuck with files like the above N51 W180 file attached above, when xRes and yRes are added without defining outputBounds. Worked fine once I provided outputBounds (and corrected the 1/2 pixel offset that var wanted).

**Comment by rouault** [comment]
I didn't reproduce exactly the issue with Copernicus_DSM_COG_10_N51_00_W180_00_DEM.tif with GDAL 3.6.x or master, presumably because an heuristic has changed since the version you use, but it generated a 4339P x 12L large raster with an extent that goes from -179.99999something to 179.94something in longitude, due to reprojection of the longitude slightly below of -180 to slightly below +180. Anyway this will also be resolved per #7565

**Comment by cstutts** [comment]
Ah ok. Thanks for checking. I'll get us updated to the latest release when it's ready.
