### ISSUE TITLE
Unknown GDAL data type: Int8 in gdal_merge -ot

### ISSUE THREAD

**Issue by adelenelai** [OSGeo/gdal#7563]
## Expected behavior and actual behavior.
When calling  `gdal_merge.py -ps 100 100 -ot Int8 -o output/file tile.tif`, I expect it to run without errors, as Int8 is listed as one of the `-ot` options https://gdal.org/programs/gdal_merge.html#cmdoption-gdal_merge-ot

However, specifying `-ot Int8` gives: 

`Unknown GDAL data type: Int8`

Other output types work ok.

## Operating system

Ubuntu running on Windows subsystem for linux [Windows Version 10.0.22621.1413]:

Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
Codename:       jammy

## GDAL version and provenance

gdal                      3.5.0            py38h51ade5a_4    conda-forge

**Comment by rouault** [comment]
the online documentation is the one of the master branch / 3.7.0dev. Support for Int8 has only been added in GDAL 3.7 (cf https://gdal.org/development/rfc/rfc87_signed_int8.html), so isn't available in your version
