### ISSUE TITLE
How to access "tiff image" on hdfs cluster using "gdal.Open"?

### ISSUE THREAD

**Issue by JenniferYingyiWu2020** [OSGeo/gdal#7568]
Hi,
    I have uploaded a tiff image to HDFS cluster, and would like to access it using following codes:
![003](https://user-images.githubusercontent.com/72843232/230533473-46e89ad4-4218-4911-8bb8-8ba567ca1e55.png)
![001](https://user-images.githubusercontent.com/72843232/230533488-9ff2dd60-f3af-4fc3-862f-1d7ae23a3326.png)
![002](https://user-images.githubusercontent.com/72843232/230533496-5a40bd41-5623-4597-ac88-9cb6c8784e3f.png)

    So, would you pls help to give me some suggestions?

**Comment by rouault** [comment]
It seems you use GDAL from Conda. Not sure if it is directly the GDAL from Conda or the one bundled with rasterio. But in any case none of them link against libhdfs. So if you want to use it, you'll have to build it yourself (cf https://gdal.org/development/building_from_source.html#hdfs hints). Last time I tried this didn't work super well for me at runtime.
You might want to try the /vsiwebhdfs/ virtual file system handle, that should be available in your GDAL build: https://gdal.org/user/virtual_file_systems.html#vsiwebhdfs-web-hadoop-file-system-rest-api
