### ISSUE TITLE
CI: coverity-scan job broken

### ISSUE THREAD

**Issue by rouault** [OSGeo/gdal#7569]
Since the refactoring of Linux CI jobs in #7501, the weekly scheduled build of https://github.com/OSGeo/gdal/blob/master/.github/workflows/coverity_scan.yml fails due to trying to access files that have been restructured. Cf last build log: https://github.com/OSGeo/gdal/actions/runs/4590046226/jobs/8105339818

**Comment by rouault** [comment]
CC @dbaston I'm not sure about the right approach here:
- copy&past the relevant parts of linux_build.yml to coverity_scan.yml (coverity_scan.yml reuses the same build depenendencies as ubuntu_20.04, and just passes secrets.COVERITY_SCAN_TOKEN/COVERITY_SCAN_EMAIL as COVERITY_SCAN_TOKEN/COVERITY_SCAN_EMAIL env variable to the ubuntu_20.04/build.sh script 
- or add a new matrix config to linux_build.yml, but that would be run only with the cron settings.

**Comment by rouault** [comment]
> I would be inclined to:

sounds good (we actually just need the Build step). I'll look at that, unless you've started

**Comment by dbaston** [comment]
I have not
