### ISSUE TITLE
CSV file with Nulls after <cr><lf> are not ignored

### ISSUE THREAD

**Issue by kehlawler** [OSGeo/gdal#757]
I am using GDAL version 2.1.2 compiled with xCode and the OGR CSV driver.

I have csv files that have a null character at the end of each line after the <cr><lf> characters.   Because of the null characters it doesn't read each line as a feature properly (going through debug it appears to ignore them as it's interpreting the null character as the first character in the next record).

It would be nice if it would ignore the nulls instead of having to strip them before using the file.  Attached is a sample file (Note: I've renamed from .csv to .txt to allow the upload)

[DEMO_World_Cities.txt](https://github.com/OSGeo/gdal/files/2196352/DEMO_World_Cities.txt)

**Comment by rouault** [comment]
This is really a weird formulation. The data producer should fix that. I see that LibreCalc has some success in opening it though

**Comment by kehlawler** [comment]
OK - I will see if I can fix at the other end - thanks.
