### ISSUE TITLE
what is the origin corner of a vrt file?

### ISSUE THREAD

**Issue by 12rambau** [OSGeo/gdal#7574]
It's a documentation question/issue, I'll be happy to make a PR if someone points me to where I should make a modification. 

I'm writting by hand a .vrt file and I'm struggling to understand a spec of the format: https://gdal.org/drivers/raster/vrt.html.

When a source is added in a SimpleSource tag, one should add the positioning of the source with respect to the global vrt:

```xml
<SimpleSource>
  <SourceFilename relativeToVRT="1">utm.tif</SourceFilename>
  <OpenOptions>
      <OOI key="OVERVIEW_LEVEL">0</OOI>
  </OpenOptions>
  <SourceBand>1</SourceBand>
  <SourceProperties RasterXSize="256" RasterYSize="256" DataType="Byte" BlockXSize="128" BlockYSize="128"/>
  <SrcRect xOff="0" yOff="0" xSize="256" ySize="256"/>
  <DstRect xOff="0" yOff="0" xSize="256" ySize="256"/>
</SimpleSource>
```

but what is the source corner of the .vrt format ?

After some try and error I concluded it's top-left but didn't find it specified anywhere. I prefer to ask here first before making a documentation edit duplication

**Comment by rouault** [comment]
> After some try and error I concluded it's top-left but didn't find it specified anywhere

Well, by itself , the VRT format doesn't make any assumption. You have a 2D space with X/column and Y/line axis. The semantics of the (0,0) corner depends on the geotransform matrix that is associated with the raster (for a VRT, the geotransform of the source and the one of the VRT itself must be obviously consistent). If the 6th term of the geotransform matrix is negative, then (0,0) is the upper-left corner of the image.
The VRT format is not particularly special, and all of this comes from the raster data model followed by GDAL: https://gdal.org/user/raster_data_model.html#affine-geotransform

**Comment by 12rambau** [comment]
do you think it would diserve an addition to the docs ? 
If not, feel free to close this issue

**Comment by rouault** [comment]
clarification attempt in https://github.com/OSGeo/gdal/pull/7577
