### ISSUE TITLE
Allow creating GoogleMapsCompatible COGs with zoom level > 24

### ISSUE THREAD

**Issue by dmahr1** [OSGeo/gdal#7585]
## Expected behavior and actual behavior.

Given [a very high resolution GeoTIFF](https://drive.google.com/file/d/1YAmitEiPPUSC9DCh_Fo95MgmB2iJ-1aY/view?usp=share_link) with pixels that are 3.3 millimeters on a side...
```
$ gdalinfo data.tif | grep "Pixel Size"    
Pixel Size = (0.003298897768200,-0.003298897768200)
```
...I would like to create a Google Maps compatible Web Mercator COG at zoom level 25 or even zoom level 26, but this fails with an error:
```
$ gdal_translate -of COG -ot Byte -b 1 -b 2 -b 3 -mask 4 -co ZOOM_LEVEL=25 -co TILING_SCHEME=GoogleMapsCompatible -co OVERVIEWS=IGNORE_EXISTING data.tif cog.tif
Input file size is 1000, 1000
ERROR 1: Invalid zoom level: should be in [0,24]
```
There is a similar error when using `ZOOM_LEVEL_STRATEGY=UPPER`:
```
$ gdal_translate -of COG -ot Byte -b 1 -b 2 -b 3 -mask 4 -co ZOOM_LEVEL_STRATEGY=UPPER -co TILING_SCHEME=GoogleMapsCompatible -co OVERVIEWS=IGNORE_EXISTING data.tif cog.tif
Input file size is 1000, 1000
ERROR 1: Could not find an appropriate zoom level
```

I suppose I could use a custom TileMatrixSet but this seems clunky given that the fix might be very small.

## Possible fix?
Based on my reading of the GDAL code, the number of zoom levels in the GoogleMapsCompatible TileMatrixSet is specified [here](https://github.com/OSGeo/gdal/blob/4752d6edfd585864236b56b2fd625f581920f2dc/gcore/tilematrixset.cpp). Could I change this as follows to enable support for zoom levels up to and including 30? Zoom level 30 has 0.146 millimeter pixels which should be safe for awhile.
```diff
-        for (int i = 0; i < 25; i++)
+        for (int i = 0; i <= 30; i++)
```

I expect that I'd also have to change [this test](https://github.com/OSGeo/gdal/blob/1d756793ef30ce875528fd9b54a39dc14e42da66/autotest/gcore/cog.py#L1324).

Is that correct? I've never contributed code to GDAL before so please excuse my limited understanding. I'm happy to give a PR a try.

## Operating system, GDAL version, and provenance
GDAL running in Docker from `ghcr.io/osgeo/gdal:ubuntu-small-3.6.3`:
```
> docker run --rm -it -v /scratch:/scratch ghcr.io/osgeo/gdal:ubuntu-small-3.6.3 bash
$ gdalinfo --version
GDAL 3.6.3, released 2023/03/07
```

**Comment by rouault** [comment]
> Is that correct?

yes, that seems quite reasonable. 30 is indeed the maximum limit to fit on a 32 bit integer.

**Comment by jratike80** [comment]
I see that there is an autotest with `options=["TILING_SCHEME=GoogleMapsCompatible", "ZOOM_LEVEL=-1"`. What does -1 mean, it seems to be undocumented?

**Comment by rouault** [comment]
> What does -1 mean, it seems to be undocumented?

-1 is invalid input. The test checks that the driver doesn't crash on this
