### ISSUE TITLE
Problem with Java-GDAL bindings under Windows 10

### ISSUE THREAD

**Issue by antonio-rodriges** [OSGeo/gdal#759]
## Expected behavior and actual behavior.

```
hProj = new SpatialReference();
hProj.SetWellKnownGeogCS("EPSG:32632");
```
should "Set a GeogCS based on well known name."
http://gdal.org/java/org/gdal/osr/SpatialReference.html#SetWellKnownGeogCS-java.lang.String-

However, it generates
```

Exception in thread "main" java.lang.RuntimeException: OGR Error: General Error
    at org.gdal.osr.osrJNI.SpatialReference_SetWellKnownGeogCS(Native Method)
    at org.gdal.osr.SpatialReference.SetWellKnownGeogCS(SpatialReference.java:473)
    at rgeo.lesson_x.JavaGDALTests.main(JavaGDALTests.java:22)
```

and crashes.

On the contrary, this code works fine:
```
hProj = new SpatialReference();
hProj.ImportFromEPSG(32632);
```

## Steps to reproduce the problem.

Setup a GDAL environment on Windows and run those 2 lines.

## Operating system

Windows 10

## GDAL version and provenance

jar file:

```
 <!-- https://mvnrepository.com/artifact/org.gdal/gdal -->
        <dependency>
            <groupId>org.gdal</groupId>
            <artifactId>gdal</artifactId>
            <version>2.3.0</version>
        </dependency>
```

native `gdalalljni.dll` and other GDAL resources are from
http://www.gisinternals.com/query.html?content=filelist&file=release-1911-x64-gdal-2-3-0-mapserver-7-0-7.zip

**Comment by rouault** [comment]
> Does this mean that the following will only work when n=4326 or other non-projected geographic coordinate system?

Yes. For other use SetFromUserInput("EPSG:XXXX") or ImportFromEPSG(XXXX) (both are equivalent)
