### ISSUE TITLE
fortran ordering dataset support for gdal_translate

### ISSUE THREAD

**Issue by nuitlejour** [OSGeo/gdal#7610]
I am trying to convert some HDF5 satellite data with gdal_translate, which was written out by fortran. 
After gdal_translate, the image orientation is wrong, it will be much more convenient for gdal_translate to add an option for fortran ordering dataset. 
thank you for your time.

**Comment by rouault** [comment]
Can you provide a link to such HDF5 image data (or attach a sample here, in a zip, if it is small enough)
You might want to use the gdamdimtranslate utility with the -array option using the transpose= argument to switch dimensions:
https://gdal.org/programs/gdalmdimtranslate.html#cmdoption-gdalmdimtranslate-array

**Comment by nuitlejour** [comment]
@rouault, thank your for your attention.

I have already tried gdalmdimtranslate to tranpose the dataset, it does the work, but it's very slow, even slower than gdal_translate itself. 

And I think it would be a better for gdal_translate to have an option to deal with fortran ordering dataset, it's more intuitive and more efficient.

here is my input HDF dataset in HDF format.
[FY4B-_GHI---_N_REGX_1330E_L1-_FDI-_MULT_NOM_20230414084900_20230414084959_2000M_V0001.zip](https://github.com/OSGeo/gdal/files/11258525/FY4B-_GHI---_N_REGX_1330E_L1-_FDI-_MULT_NOM_20230414084900_20230414084959_2000M_V0001.zip)

here is the dataset shown in qgis before gdal_translate
![before](https://user-images.githubusercontent.com/20106317/232687298-9befa427-f036-4d20-b972-59141b556d08.png)

and here is the dataset shown in qgis after gdal_translate
![after](https://user-images.githubusercontent.com/20106317/232687263-9c8b74fd-62ec-402a-9394-217b4a2c332a.png)

**Comment by nuitlejour** [comment]
@rouault, sorry, I think I made mistake, the gdal_translate does not mess up image orientation, I have input wrong parameters for -a_ullr <ulx> <uly> <lrx> <lry>, and make the image upside down, I will close the issue.
