### ISSUE TITLE
PNG/vsicurl: slow, complex output from png url

### ISSUE THREAD

**Issue by mdsumner** [OSGeo/gdal#7613]
This gives a lot of repetitive output and is slow

```
gdalinfo /vsicurl/https://tiles.openseamap.org/seamark/0/0/0.png
#Driver: PNG/Portable Network Graphics
```

output like 

```
ERROR 1: Maximum number of characters allowed reached.
ERROR 1: GetFileList() called with too many recursion levels
ERROR 1: GDALOpen() called with too many recursion levels

```

Not a useful source as far as I can tell, I found it in a list of leaflet providers and was trying to flush them

wget and info is as expected

```
wget https://tiles.openseamap.org/seamark/0/0/0.png

gdalinfo 0.png

Driver: PNG/Portable Network Graphics
Files: 0.png
Size is 256, 256
Image Structure Metadata:
  INTERLEAVE=PIXEL
Corner Coordinates:
Upper Left  (    0.0,    0.0)
Lower Left  (    0.0,  256.0)
Upper Right (  256.0,    0.0)
Lower Right (  256.0,  256.0)
Center      (  128.0,  128.0)
Band 1 Block=256x256 Type=Byte, ColorInterp=Red
  Mask Flags: PER_DATASET ALPHA
Band 2 Block=256x256 Type=Byte, ColorInterp=Green
  Mask Flags: PER_DATASET ALPHA
Band 3 Block=256x256 Type=Byte, ColorInterp=Blue
  Mask Flags: PER_DATASET ALPHA
Band 4 Block=256x256 Type=Byte, ColorInterp=Alpha
```

## Operating system

Ubuntu 22.04.2 LTS

## GDAL version and provenance

GDAL 3.7.0dev-7cd1a9bb31, released 2023/04/17 (debug build)

**Comment by jratike80** [comment]
Try this: 
`gdalinfo /vsicurl/https://tiles.openseamap.org/seamark/0/0/0.png --config GDAL_DISABLE_READDIR_ON_OPEN EMPTY_DIR`
See also the documentation https://trac.osgeo.org/gdal/wiki/ConfigOptions#GDAL_DISABLE_READDIR_ON_OPEN.

**Comment by mdsumner** [comment]
ah nice, thanks, and sorry for the noise
