### ISSUE TITLE
Gdal Info VSISTDIN

### ISSUE THREAD

**Issue by wselwood** [OSGeo/gdal#762]
Using /vsistdin/ reports an error with the IFD of a Geo Tiff while just passing the file in does not error. 

See shell output below for an example.

## Expected behavior and actual behavior.

```shell
wselwood@X:/$ gdalinfo --version
GDAL 2.2.3, released 2017/11/20
wselwood@X:/$ gdalinfo /vsistdin/ < /data/20170112_WV3_MS_ortho_gspansharp_img.tif
ERROR 6: IFD start should be at offset 8 for a streamed TIFF
gdalinfo failed - unable to open '/vsistdin/'.
wselwood@X:/$ gdalinfo /data/20170112_WV3_MS_ortho_gspansharp_img.tif
Driver: GTiff/GeoTIFF
Files: /data/20170112_WV3_MS_ortho_gspansharp_img.tif
Size is 18627, 14692
Coordinate System is:
PROJCS["WGS 84 / UTM zone 37S",
...
```

## Steps to reproduce the problem.

gdalinfo /vsistdin/ < /data/20170112_WV3_MS_ortho_gspansharp_img.tif

## Operating system

 Ubuntu 18.04 64 bit

## GDAL version and provenance

GDAL 2.2.3

**Comment by rouault** [comment]
GeoTIFF files are generally not compabile of being read by /vsistdin/ unless they are specifically created for it. See the "streaming operations" paragraph of http://gdal.org/frmt_gtiff.html
