### ISSUE TITLE
ogr2ogr -clipsrc seems to work badly (in Linux, in Windows it seems to work)

### ISSUE THREAD

**Issue by aborruso** [OSGeo/gdal#7641]
## Expected behavior and actual behavior.

Hi,
I run a clip using ogr2ogr, and the output does not contain the right objects

## Steps to reproduce the problem.

Run this command, using [these files](https://github.com/OSGeo/gdal/files/11309144/clip_debug.zip):

```bash
ogr2ogr -skipfailures -overwrite -nln linestring -f OpenFileGDB output.gdb source.shp source -clipsrc blade.shp -lco FEATURE_DATASET=myFD
```

The output layer (in white) is missing a piece. In the image below a comparison with the input layers (in black). In the output the central part is missing.

![clip](https://user-images.githubusercontent.com/30607/233968260-472b7783-4661-42fb-9e81-a916e3634d14.gif)

## Operating system

Debian 11

## GDAL version and provenance

GDAL 3.7.0dev-b0aa6065a3, released 2023/01/11 (debug build)

**Comment by jratike80** [comment]
Probably the geometry is valid, but could there be something special in this feature (the last one)?
```
OGRFeature(source):3
  OBJECTID (Real) = (null)
  DBGT (Integer64) = (null)
  Shape_Leng (Real) = (null)
  cls (String) = (null)
  LINESTRING Z (541283.330223848 4557801.07656933 0,542184.195180087 4557774.05062065 0)

**Comment by aborruso** [comment]
@jratike80 

> Probably the geometry is valid, but could there be something special in this feature (the last one)?

Why special? For the null values? This record is null also in the input.

If I don't understand, let me understand.

Thank you

**Comment by jratike80** [comment]
Just wondering why the attributes are null in the input, but you are right that they can well be nulls.
GDAL-dev from OSGeo4W (today), version GDAL 3.7.0dev-717dcc0eed, released 2023/04/19 does not run the command. I changed the output format for dropping the possible complexity of OpenFileGDL driver. For some reason I get this:

```
ogr2ogr -skipfailures -overwrite -f JML output.jml source.shp source -clipsrc blade.shp
ERROR 5: cannot load source clip geometry

With another GDAL (gisinternals, GDAL 3.7.0dev-5ce7ba068f, released 2023/01/17) the command runs OK and the output does not miss a part.

**Comment by jratike80** [comment]
Yes, by copy-pasting your command the result contains
```
  MULTILINESTRING Z ((539668.223999977 4559589.40399981 0,539667.888000011 4559590.63800001 0))
  MULTILINESTRING Z ((539667.888000011 4559590.63800001 0,539667.888000011 4559591.64699984 0))
  MULTILINESTRING Z ((539667.888000011 4559591.64699984 0,539668.393000126 4559592.76800013 0))
  MULTILINESTRING Z ((541283.330200195 4557801.07660007 0,541862.55340004 4557783.69990015 0))
  ```

**Comment by jratike80** [comment]
Comes here 
[output.gdb.zip](https://github.com/OSGeo/gdal/files/11309742/output.gdb.zip)

**Comment by aborruso** [comment]
> Comes here
> [output.gdb.zip](https://github.com/OSGeo/gdal/files/11309742/output.gdb.zip)

No error thank you.

But if I use gisinternal "GDAL 3.7.0dev-717dcc0eed, released 2023/04/22", I get "cannot load source clip geometry"

```
GDAL: Auto register C:\gdal\bin\gdal\plugins\gdal_ECW_JP2ECW.dll using GDALRegister_ECW_JP2ECW.
GDAL: Auto register C:\gdal\bin\gdal\plugins\gdal_FITS.dll using GDALRegister_FITS.
GDAL: Auto register C:\gdal\bin\gdal\plugins\gdal_HDF4.dll using GDALRegister_HDF4.
GDAL: Auto register C:\gdal\bin\gdal\plugins\gdal_HDF5.dll using GDALRegister_HDF5.
GDAL: Auto register C:\gdal\bin\gdal\plugins\gdal_KEA.dll using GDALRegister_KEA.
GDAL: Auto register C:\gdal\bin\gdal\plugins\gdal_netCDF.dll using GDALRegister_netCDF.
GDAL: Auto register C:\gdal\bin\gdal\plugins\gdal_PDF.dll using GDALRegister_PDF.
GDAL: Auto register C:\gdal\bin\gdal\plugins\ogr_ODBC.dll using RegisterOGRODBC.
Shape: DBF Codepage = UTF-8 for source.shp
Shape: Treating as encoding 'UTF-8'.
GDAL: GDALOpen(source.shp, this=000001F6B7D1CAE0) succeeds as ESRI Shapefile.
Shape: DBF Codepage = LDID/87 for blade.shp
Shape: Treating as encoding 'ISO-8859-1'.
GDAL: GDALOpen(blade.shp, this=000001F6B7D1D720) succeeds as ESRI Shapefile.
Shape: 1 features read on layer 'blade'.
GDAL: GDALClose(blade.shp, this=000001F6B7D1D720)
ERROR 5: cannot load source clip geometry
GDAL: GDALClose(source.shp, this=000001F6B7D1CAE0)
GDAL: In GDALDestroy - unloading GDAL shared library.
```

**Comment by jratike80** [comment]
Great, so something happened between "released 2023/01/17" and released "2023/04/22" in main. OSGeo4W version GDAL 3.6.4, released 2023/04/17 seems to work OK. Isn't it odd, that ogrinfo does not give any errors or warnings about blade.shp?

**Comment by dbaston** [comment]
The logic of loading the `clipsrc` was changed a bit recently and now only accepts polygonal clipping geometries; see https://github.com/OSGeo/gdal/pull/7409/files

**Comment by jratike80** [comment]
The blade geometry is rather polygonal to me:
` POLYGON Z ((541860.2107 4558192.4637 0,541876.1171 4555417.1003 0,534883.384 4555383.708 0,534856.9123 4560931.132 0,538350.5795 4560948.6841 0,541844.2894 4560967.8422 0,541860.2107 4558192.4637 0))`

**Comment by aborruso** [comment]
> The logic of loading the `clipsrc` was changed a bit recently and now only accepts polygonal clipping geometries; see [#7409 (files)](https://github.com/OSGeo/gdal/pull/7409/files)

My blade is a polygon

**Comment by jratike80** [comment]
> My blade is a polygon

It is a POLYGON Z. Convert it into 2D polygon and current dev version will accept it.
However, your original problem with a dropped feature must have some other reason. But if current dev version works for you with 2D polygon then maybe we can forget it?

**Comment by pigreco** [comment]
Also in QGIS (OSGEo4W Network Installer on WIN 10 pro) I get error:

```
QGIS version: 3.31.0-Master
QGIS code revision: 755709567e
Qt version: 5.15.3
Python version: 3.9.5
GDAL version: 3.7.0dev-717dcc0eed
GEOS version: 3.11.2-CAPI-1.17.2
PROJ version: Rel. 9.2.0, March 1st, 2023
PDAL version: 2.5.2 (git-version: 57c4e7)
Algorithm started at: 2023-04-24T13:37:37
Algorithm 'Clip vector by mask layer' starting…
Input parameters:
{ 'INPUT' : 'C:/Users/s.fiandaca/Downloads/clip_debug/blade.shp', 'MASK' : 'C:/Users/s.fiandaca/Downloads/clip_debug/blade.shp', 'OPTIONS' : '', 'OUTPUT' : 'TEMPORARY_OUTPUT' }

GDAL command:
ogr2ogr -clipsrc C:/Users/s.fiandaca/Downloads/clip_debug/blade.shp -clipsrclayer blade C:/Users/s.fiandaca/AppData/Local/Temp/processing_MySTvi/c03e45ff9a6e4e1c851819b00c4f2522/OUTPUT.gpkg C:/Users/s.fiandaca/Downloads/clip_debug/blade.shp blade -f "GPKG"
GDAL command output:
ERROR 5: cannot load source clip geometry
Process returned error code 1
Execution completed in 0.28 seconds
Results:
{'OUTPUT': 'C:/Users/s.fiandaca/AppData/Local/Temp/processing_MySTvi/c03e45ff9a6e4e1c851819b00c4f2522/OUTPUT.gpkg'}

Loading resulting layers
The following layers were not correctly generated.
• C:/Users/s.fiandaca/AppData/Local/Temp/processing_MySTvi/c03e45ff9a6e4e1c851819b00c4f2522/OUTPUT.gpkg
You can check the 'Log Messages Panel' in QGIS main window to find more information about the execution of the algorithm.
```

**Comment by aborruso** [comment]
> It is a POLYGON Z. Convert it into 2D polygon and current dev version will accept it.

Ok, with a 2d poly, it works. Then I must update my gdal in Debian.

I close issue. However, I think that the non-management of Z polygons is a bug and not a choice by design cc @dbaston 

Thank you to alle

**Comment by dbaston** [comment]
> I think that the non-management of Z polygons is a bug

Agree, I will submit a PR to fix shortly

**Comment by dbaston** [comment]
@aborruso what GEOS version do you have? If not up-to-date t's possible you're seeing https://github.com/libgeos/geos/issues/700

**Comment by aborruso** [comment]
> @aborruso what GEOS version do you have? If not up-to-date t's possible you're seeing [libgeos/geos#700](https://github.com/libgeos/geos/issues/700)

I think I have 3.9.0-1

![image](https://user-images.githubusercontent.com/30607/234016633-3a2e12a6-9cd4-4b61-8b99-00cd1af03484.png)

**Comment by dbaston** [comment]
I think the GEOS version is the issue (current version in the 3.9 series is 3.9.4). Perturbing one of the X values as @jratike80 suggests should confirm this.

**Comment by aborruso** [comment]
> I think the GEOS version is the issue (current version in the 3.9 series is 3.9.4). Perturbing one of the X values as @jratike80 suggests should confirm this.

I have compiled and installed geos  geos-3.9.4.

And I have compiled gdal `cmake  GDAL_USE_GEOS=ON ..`.

But I always have the same problem. Could you test it in your Linux?

**Comment by dbaston** [comment]
> Could you test it in your Linux?

Using #7642 I see

```
➜ ogr2ogr -skipfailures -overwrite -nln linestring -f OpenFileGDB output.gdb source.shp source -clipsrc blade.shp -lco FEATURE_DATASET=myFD
Warning 1: The output driver does not seem to natively support Integer64 type for field DBGT. Converting it to Real instead. -mapFieldType can be used to control field type conversion.
➜ ogrinfo -al output.gdb | grep LINESTRING
  MULTILINESTRING Z ((539668.223999977 4559589.40399981 0,539667.888000011 4559590.63800001 0))
  MULTILINESTRING Z ((539667.888000011 4559590.63800001 0,539667.888000011 4559591.64699984 0))
  MULTILINESTRING Z ((539667.888000011 4559591.64699984 0,539668.393000126 4559592.76800013 0))
  MULTILINESTRING Z ((541283.330200195 4557801.07660007 0,541862.55340004 4557783.69990015 0))
```

**Comment by aborruso** [comment]
> But I always have the same problem. Could you test it in your Linux?

This morning it works. I was probably tired yesterday after the upgrade.


Thank you @dbaston @jratike80
