### ISSUE TITLE
MRSid not added to drivers list.

### ISSUE THREAD

**Issue by sagido** [OSGeo/gdal#7643]
I added Mrsid to gdal. MRsid dlls were added to Gdal dependencies. But after GDALAllRegister() I don't see any new driver. 
I followed this https://trac.osgeo.org/gdal/wiki/MrSID.
Appreciate any help.

**Comment by rouault** [comment]
Cf the following CMake options: https://gdal.org/development/building_from_source.html#mrsid
and https://github.com/OSGeo/gdal/blob/c33d207c6dd65743129a7e35f5d1e60cdd2b8be3/.github/workflows/ubuntu_20.04/build.sh#L15 and https://github.com/OSGeo/gdal/blob/c33d207c6dd65743129a7e35f5d1e60cdd2b8be3/.github/workflows/ubuntu_20.04/Dockerfile.ci#L141 for how it is tested with Linux continuous integration
