### ISSUE TITLE
issues with using gdalwarp -t_srs ... +over. Works on Windows but +/- fails on Linux

### ISSUE THREAD

**Issue by joa-quim** [OSGeo/gdal#7644]
On Windows this prints lots of warnings but creates the wished output (would not if output was asked to be .nc)
```
gdalwarp -t_srs "+proj=vandg +over" earth15.grd lixo.tiff
````

However, it fails on Linux on first run but works on a second run, and this time it does not print any warnings.
> ERROR 1: PROJ: vandg: Invalid latitude

It always fail on Linux if I use -overwrite option.

The problem is that I want to run this from Julia and it works on Windows but fails on Linux (all in-memory transactions).
See this GMT [forum post](https://forum.generic-mapping-tools.org/t/best-projection-for-rectangular-world-map/3715/79) for context. 

[earth15.zip](https://github.com/OSGeo/gdal/files/11325977/earth15.zip)

**Comment by joa-quim** [comment]
Actually, the behavior is more projection dependent. Using ``+proj=wintri`` still prints the complaining messages but it works on the first run also on Linux.
```
gdalwarp -t_srs "+proj=wintri +over" earth15.grd lixo2.tiff
```

**Comment by rouault** [comment]
This is very much dependend on the PROJ version you use, and is unlikely to depend on the GDAL version or the operating system. There have been generic fixes in recent PROJ versions regarding +over support, and one very specific of vandg in https://github.com/OSGeo/PROJ/commit/0e050eea2a737f88b4821f9f94ac340f1b73af8e in PROJ 9.2.0
which PROJ versions do you use on Windows and Linux ? (cf the output of ``gdalinfo --build`` for example)
I get something that looks at a reasonable output with latest PROJ (despite the "Invalid latitude" errors which are likely related to the input dataset having latitudes slightly above 90)

**Comment by joa-quim** [comment]
Yes, that might be it. On Win I build everything myself and I'm normally on the edge with master builds. The Linux version uses artifacts built with a Julia env and I think it uses PROJ 9.1

Regarding the "Invalid latitudes" that is strange because, as far as  I can tell the latitudes do not overflow the 90 degrees, though I can't be 100% sure that last bit of the float64 doesn't do it.

I might come with more ``+over`` cases, where, for example, ``+proj=wintri`` works well in ``gdalwarp`` but not in ``ogr2ogr`` (or, to be precise, with their Julia wrappers).

**Comment by rouault** [comment]
> On Win I build everything myself and I'm normally on the edge with master builds.

Ok, so closing given that with recent PROJ versions this works

> Regarding the "Invalid latitudes" that is strange because, as far as I can tell the latitudes do not overflow the 90 degrees

yes, but as netCDF uses a center-of-pixel convention to define where a geospatial coordinate applies in a coordinate and GDAL a pixel-corner one, GDAL sees the range of latitude going from -90.25 to 90.25 (half-pixel extension).

**Comment by joa-quim** [comment]
>  but as netCDF uses a center-of-pixel convention to define where a geospatial coordinate applies

Actually netCDF supports both models. In GMT we call it [pixel and gridline registrations](https://docs.generic-mapping-tools.org/latest/cookbook/options.html#grid-registration-the-r-option) and [distribute](https://docs.generic-mapping-tools.org/latest/datasets/remote-data.html#currently-available-remote-data-sets) several grids & images that use both models. It's quite possible that I've used a _gridline registered_ grid in my example.
