### ISSUE TITLE
GRIB reporting wrong nodata value for band > 1

### ISSUE THREAD

**Issue by IvanLucena** [OSGeo/gdal#7649]
## Expected behavior and actual behavior.

The correct nodata values for all the bands in a WMO GRIB image is 9999, and gdalinfo reports it right. 

But when calling the GDAL API in Python, for example, only the nodata value of the first band is correctly, the others return None, as we can see here:

```
>>> from osgeo import gdal
>>> ds = gdal.Open('/GRIB/2023/PS.557WW_SC.U_DI.C_GP.LIS_GR.C0P09DEG_AR.GLOBAL_PA.LIS24_DD.20230412_DT.1200_DF.GR2')
>>> for b in range(1,19):
...     print(ds.GetRasterBand(b).GetNoDataValue())
...
9999.0
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
```

## Steps to reproduce the problem.

Download a sample file from [Fast Downloading of GRIB Files](https://www.cpc.ncep.noaa.gov/products/wesley/fast_downloading_grib.html) and run the above sequence of code.

After some investigation, I noticed that if we call GetStatistics() before calling GetNoDataValue, the return values are correct. That is not a solution, but it might be a clue to fix the code.
 
```
>>> from osgeo import gdal
>>> ds = gdal.Open('/GRIB/2023/PS.557WW_SC.U_DI.C_GP.LIS_GR.C0P09DEG_AR.GLOBAL_PA.LIS24_DD.20230412_DT.1200_DF.GR2')
>>> for b in range(1,19):
...     s = ds.GetRasterBand(b).GetStatistics(True, False)
...     print(ds.GetRasterBand(b).GetNoDataValue())
...
9999.0
9999.0
9999.0
9999.0
9999.0
9999.0
9999.0
9999.0
9999.0
9999.0
9999.0
9999.0
9999.0
9999.0
9999.0
9999.0
9999.0
9999.0
```

That might explain why gdalinfo and gdalinfo.py always report the correct nodata value. Because they both call GetStatistics() before GetNoDataValue().

## Operating system

Linux (x86_64 Redhat) and Windows (Server 2016 64).

## GDAL version and provenance

GDAL versions 3.4 and 3.6.

On Linux GDAL was build from source and on Windows it was installed via Anaconda 3.

That issues does not occurs in GDAL 2.3, not in Linux or Windows.

**Comment by elpaso** [comment]
Can you please attach a link to directly download a dataset that shows the issue? 
I've tried to find one without success.

**Comment by IvanLucena** [comment]
[GRIB.gr2.002.txt](https://github.com/OSGeo/gdal/files/11355850/GRIB.gr2.002.txt)
[GRIB.gr2.003.txt](https://github.com/OSGeo/gdal/files/11355851/GRIB.gr2.003.txt)
[GRIB.gr2.001.txt](https://github.com/OSGeo/gdal/files/11355852/GRIB.gr2.001.txt)

In order to unzip the file, you might need to remove the ''.txt' from the 3 files and then you unzipped the three files together.

Let me know if that works. I could not upload it in a single file and the .00N file name is not permitted for uploading.

**Comment by IvanLucena** [comment]
I applied the changes to 3.4 and build it on Linux and I can confirm that it is fixed.

Thank you guys so very much.
