### ISSUE TITLE
gdal_translate missing Int8

### ISSUE THREAD

**Issue by yokada2254** [OSGeo/gdal#7688]
hello

gdal_translate with options -ot Int8 can be found on document
https://gdal.org/programs/gdal_translate.html
and available when install with "conda install -c gdal-master gdal" on windows platform 

gdal_translate.exe --version
GDAL 3.8.0dev-78e9c2fc49-dirty, released 2023/05/02

but not available on Linux platform 
I had tried different ways like build from source, apt install and install via conda 
Int8 option still not available.

**Comment by jratike80** [comment]
Did you find it somewhere?

**Comment by yokada2254** [comment]
> Did you find it somewhere?

Int8 option is available if I build from latest source (3.8.0Dev) on github.
