### ISSUE TITLE
i have a problem with "PDF" driver

### ISSUE THREAD

**Issue by Tarot67** [OSGeo/gdal#769]
Bug description

i made a geopackege with vector geometries (point).
A layer of points named "point_layer"  with attribute name (text), angle (a real value between 0 - 360°) and geom it's self represent the insertion point of label.

when i  tape

ogr2ogr  resulte.pdf -f "PDF" my_geopakege.gpkg  -sql  "select geom,name,angle, 'LABEL(f:Arial,c:#000000,a:{angle},t:{name})' AS OGR_STYLE FROM point_layer"

My pdf label display but not with angle field table value. All label are horizontally display.

But if i put a:14 it's works. But all my label as the same angle! 14°.

 I don't know why. It's a bug ?

Libraries and OS version

I try with several version of linux: Arch linux, Slackware, ubuntu i have the same problem.
(X86_64 only)
gdal-2.3.0
spatialite-4.4.0-RC0 (with liblwgeom because i need ST_Azimuth())
geos-3.6
postGIS-2.4.4
poppler 0.62.0

Regards,

JeanSeb

email:tarot@unistra.fr

**Comment by rouault** [comment]
Try modifying your sql request as
 -sql "select geom,name,angle, 'LABEL(f:Arial,c:#000000,a:' || angle || ',t:' || label || ')' AS OGR_STYLE FROM point_layer"

**Comment by Tarot67** [comment]
YES it works!

Thank you!. You save my life. I use your PDF driver for generate a map for
the DICTs (Request for commencement of work (public works)).

2018-07-20 15:44 GMT+02:00 Even Rouault <notifications@github.com>:
