### ISSUE TITLE
NetCDF: subdatasets missing in GDAL 3.6.4

### ISSUE THREAD

**Issue by snowman2** [OSGeo/gdal#7695]
## Expected behavior and actual behavior.

In GDAL<=3.6.3, subdatasets existed for the netCDF file.

## Steps to reproduce the problem.

[tmmx_20190121.nc](https://github.com/corteva/rioxarray/blob/master/test/test_data/input/tmmx_20190121.nc)

```
gdalinfo tmmx_20190121.nc
```
GDAL <=3.6.3
```
Subdatasets:
  SUBDATASET_1_NAME=NETCDF:"tmmx_20190121.nc":air_temperature
  SUBDATASET_1_DESC=[585x1386] tmmx (16-bit unsigned integer)
```
GDAL 3.6.4
It is missing.

## Operating system

Ubuntu 22

## GDAL version and provenance

Docker image: ubuntu-full-3.6.4 & ubuntu-full-3.6.3

**Comment by rouault** [comment]
I don't see a bug here. Previously one single subdataset was reported, which does not make a lot of sense. As the dataset contains only one single 2D variable, it makes sense to present it as a regular dataset.

**Comment by snowman2** [comment]
Thanks for verifying that the change in behavior is expected :+1:
