### ISSUE TITLE
CSV driver emitting CSVT and PRJ when using /vsistdout/ driver

### ISSUE THREAD

**Issue by moicalcob** [OSGeo/gdal#7699]
## Expected behavior and actual behavior.

When using /vsistdout/ driver the `.csvt` and `.prj` content is emitted if using `CREATE_CSVT=YES` layer creation option. If this driver is used I expect to obtain just the CSV content.

## Steps to reproduce the problem.

```
ogr2ogr -f CSV  /vsistdout/ /vsizip/shapefile.zip -lco GEOMETRY_NAME=geom -lco CREATE_CSVT=YE
```

## Operating system

macOS 13.2.1

## GDAL version and provenance

3.6.3 version installed from Homebrew

**Comment by jratike80** [comment]
Another case that does not honor the command that asks to write out two files into /vsistdout/. Only one output with internal schema is written. No real issue here I believe because the GML data is still valid.

`ogr2ogr -f "GML"  /vsistdout/ point.shp  -dsco XSISCHEMA=EXTERNAL`
