### ISSUE TITLE
gdal2tiles 2.3 generates pixelated tiles on Mapbox

### ISSUE THREAD

**Issue by vadnart1** [OSGeo/gdal#770]
we've been using gdal2tiles to generate tiles for use in Mapbox.   it's been working perfectly in gdal v2.2.4.

but when we try to run v2.3 we are seeing highly pixelated map tiles.

here's our command :   gdal2tiles.py -wnone -a 0 test.tif tilesets

also we noticed gdal2tiles v2.3  takes much longer to run, about an hour (~ 400MB tif) vs less than 20 minutes for same tif in v2.2.4.   

Thanks for any help.

regards,
David

**Comment by rouault** [comment]
Please provide a link (or attach it here) to a dataset showing the problem

**Comment by vadnart1** [comment]
Hi Even,
Thanks for the quick reply. Below are the details of the datasets.  let me know if any additional information or clarification.  thanks again for your help.

1. Tilesets generated from a 375MB geotiff located at:
[http://s3.amazonaws.com/test-geotiff/geotiff/375MB/test.tif]

2.  GDAL Info for the test.tif file located at:
[http://s3.amazonaws.com/test-geotiff/geotiff/375MB/test.info.txt]

**Tilesets were generated using GDAL v2.2.3 and GDAL v2.3.1:**

1.  Version 2.2.3:
gdal2tiles.py -a 0 test.tif tilesets_2.2.3
Command duration -> 15 minutes and 50 seconds

Openlayers web interface located at:
[http://s3.amazonaws.com/test-geotiff/geotiff/375MB/tilesets_2.2.3/openlayers.html]

2.  Version 2.3.1:
gdal2tiles.py -a 0 test.tif tilesets_2.3.1
Command duration -> 1 hour 13 minutes and 50 seconds

Openlayers web interface located at:
Tilesets generated from a 375MB geotiff located at:
[http://s3.amazonaws.com/test-geotiff/geotiff/375MB/test.tif]

GDAL Info for the test.tif file located at:
[http://s3.amazonaws.com/test-geotiff/geotiff/375MB/test.info.txt]

Tilesets were generated using GDAL v2.2.3 and GDAL v2.3.1:

Version 2.2.3:
gdal2tiles.py -a 0 test.tif tilesets_2.2.3
Command duration -> 15 minutes and 50 seconds

Openlayers web interface located at:
[http://s3.amazonaws.com/test-geotiff/geotiff/375MB/tilesets_2.2.3/openlayers.html]

Version 2.3.1:
gdal2tiles.py -a 0 test.tif tilesets_2.3.1
Command duration -> 1 hour 13 minutes and 50 seconds

Openlayers web interface located at:
http://s3.amazonaws.com/test-geotiff/geotiff/375MB/tilesets_2.3.1/openlayers.html](url)

GDAL Info for the test.tif file located at:
[http://s3.amazonaws.com/test-geotiff/geotiff/375MB/test.info.txt]

Tilesets were generated using GDAL v2.2.3 and GDAL v2.3.1:

Version 2.2.3:
gdal2tiles.py -a 0 test.tif tilesets_2.2.3
Command duration -> 15 minutes and 50 seconds

Openlayers web interface located at:
[http://s3.amazonaws.com/test-geotiff/geotiff/375MB/tilesets_2.2.3/openlayers.html](url)

Version 2.3.1:
gdal2tiles.py -a 0 test.tif tilesets_2.3.1
Command duration -> 1 hour 13 minutes and 50 seconds

Openlayers web interface located at:
[http://s3.amazonaws.com/test-geotiff/geotiff/375MB/tilesets_2.3.1/openlayers.html](url)

**Comment by vadnart1** [comment]
awesome, thanks Even!  when do you expect 2.3.2 release ?   is there way we can try out the changes?
