### ISSUE TITLE
[CMake] variable GDAL_USE_QB3 not used

### ISSUE THREAD

**Issue by jmckenna** [OSGeo/gdal#7727]
- using today's `master` & CMake version 3.26.3
- CMake reports that the variable `GDAL_USE_QB3` was not used, even though it is listed in the documentation at https://gdal.org/development/building_from_source.html#qb3
- exact setting used is `-DGDAL_USE_QB3=OFF`
- (this could just be a documentation issue I realize)

**Comment by rouault** [comment]
good catch. The actual name of the option is GDAL_USE_LIBQB3. Doc fix queued in https://github.com/OSGeo/gdal/pull/7728
