### ISSUE TITLE
gdal_edit.py breaks COG layout and warns only after the damage is done 

### ISSUE THREAD

**Issue by foobarbecue** [OSGeo/gdal#7735]
## Expected behavior and actual behavior.

Using `gdal_edit.py -setstats` on a cloud-optimized geotiff. I expect it to either:
- set stats
- output an error and quit
- if I'm doing a risky operation, warn me and ask if I would like to proceed

Instead, it destroys my file and then says `Warning 1: /app/media/images/M1180855200RE_cog.tif: The IFD has been rewritten at the end of the file, which breaks COG layout.`

## Steps to reproduce the problem.

1. Use gdal_edit.py with -setstats on a tif with COG layout

## Operating system

Windows and Ubuntu

## GDAL version and provenance

GDAL 3.4.1

**Comment by jratike80** [comment]
It does not destroy your file. It is still a valid TIFF file that probably behaves quite nice in a cloud even the IDF must be read from the end of the file. It is not reasonable to analyze and tell users all possible side effects that gdal_edit may do for each supported format but maybe COG could be an exception.

If it is practically impossible to edit a COG organized TIFF without breaking the optimization, then it could be documented in the COG driver manual. I do not know if that is the case.

**Comment by rouault** [comment]
> If it is practically impossible to edit a COG organized TIFF without breaking the optimization, then it could be documented in the COG driver manual. I do not know if that is the case.

yes, that's close to impossible. See https://github.com/OSGeo/gdal/pull/7736 where I introduce an explicit open option to allow COG update.

**Comment by foobarbecue** [comment]
> It does not destroy your file. It is still a valid TIFF file that probably behaves quite nice in a cloud even the IDF must be read from the end of the file.

I should have been more specific about my experience, because maybe I'm misunderstanding something about this bug. I'm displaying COG files using ArcGIS Maps SDK for JavaScript 4.26. I used gdal_edit.py to try and improve the display of the files, only to find the jsapi complained that they were no longer COG files and was no longer able to display them. I couldn't find an easy way to repair the files other than re-converting to COG with `gdal_translate` -- could you point me to a reference with more info about "the IDF must be read from the end of the file" (I'm new to the concept of IDF)?

I'm wondering if I'm also experiencing a bug in the gdal_translate COG driver, because converting to COG with `gdal_translate seems` to change the minimum and maximum on certain of my COGs to a much larger range than the data (so the whole image displays as solid white). That's what I was trying to fix with gdal_edit.py in the first place.

**Comment by foobarbecue** [comment]
#7736 seems like a good solution.

**Comment by rouault** [comment]
> could you point me to a reference with more info about "the IDF must be read from the end of the file" (I'm new to the concept of IDF)?

IFD = Image File Descriptor. cf https://www.fileformat.info/format/tiff/egff.htm + https://gdal.org/drivers/raster/cog.html#file-format-details
