### ISSUE TITLE
RMF tests randomy failing

### ISSUE THREAD

**Issue by rouault** [OSGeo/gdal#774]
@drons
For example on https://api.travis-ci.com/v3/job/135655350/log.txt

```
  TEST: rmf_32a ... success
ERROR 3: Can't decompress tile xOff 3 yOff 0. Raw tile size is 196608 but decompressed is 134324. Compressed tile size is 146105
ERROR 3: Failed to read tile xOff 3 yOff 0
ERROR 1: data/../tmp/rmf_32b.rsw, band 1: IReadBlock failed at X offset 3, Y offset 0: Failed to read tile xOff 3 yOff 0
ERROR 3: Checksum value could not be computed due to I/O read error.
  TEST: rmf_32b ... fail
    line 617: Checksum for band 1 in "../tmp/rmf_32b.rsw" is 0, but expected 5540.
```

**Comment by drons** [comment]
@rouault 
I tried to fix this bug in my PR #766. But there were only more problems.
I hope fixes in #779, #780 will fix this problem too.

**Comment by drons** [comment]
I'll run rmf.py with gcc sanitizer for a few hours.
I'll see, maybe on my computer will fall, too.

**Comment by drons** [comment]
I think that to fix the problem, we need to move GDALDataset::FlushCache() on top of [RMFDataset::FlushCache()](https://github.com/OSGeo/gdal/blob/master/gdal/frmts/rmf/rmfdataset.cpp#L1030).

I will do additional tests and send the PR.
