### ISSUE TITLE
Incomplete result of gdal.Warp at the image edges

### ISSUE THREAD

**Issue by danschef** [OSGeo/gdal#7751]
## Expected behavior and actual behavior.

The result of gdal.Warp does not include the full input image data at the image edges (bilinear resampling). Here is an example output generated exactly as described in https://github.com/OSGeo/gdal/issues/7750 (same input data):

Upper left image corner with cubic resampling:
![grafik](https://github.com/OSGeo/gdal/assets/16669114/1bfb05af-f79f-437a-939c-88ad5068de21)

Lower right image corner with cubic resampling:
![grafik](https://github.com/OSGeo/gdal/assets/16669114/5b23b7f4-4859-48e3-a8f8-07f516c1f7e6)

Although the input data has zeros at the first and last lines and columns, it seems like in the output there is something missing at the left and lower edge of the resampled image.

This is even more apparent with nearest neighbor resampling:
![grafik](https://github.com/OSGeo/gdal/assets/16669114/f4e42b05-5c33-4302-b567-34cf472137fb)

Not sure if it is related to the image warping via GEOLOCATION arrays but I guess not.

Setting `gdal.WarpOptions(errorThreshold=0)` does not change anything.

## Steps to reproduce the problem.

Just use the code example and test data in https://github.com/OSGeo/gdal/issues/7750 (same input data).

## Operating system

Ubuntu 22.04 64 bit

## GDAL version and provenance

gdal 3.6.2 from conda-forge

**Comment by danschef** [comment]
Probably related to https://github.com/OSGeo/gdal/issues/4707.

**Comment by rouault** [comment]
@danschef Not toally sure if it is the reason, but your input dataset is 501x501 pixels, but your longitude & latitude arrays are only 500x500 pixels

**Comment by danschef** [comment]
@rouault You are completely right, that fixes it. However, I am wondering why this works without raising an error. Shouldn't the GEOLOCATION arrays be expected in the same dimension like the input data?

**Comment by rouault** [comment]
> Shouldn't the GEOLOCATION arrays be expected in the same dimension like the input data?

not necessarily, since there are the PIXEL_OFFSET, LINE_OFFSET, PIXEL_STEP, LINE_STEP metadata items that can be used to have geolocation arrays smaller than the input data. But perhaps we could emit a warning if we detect an inconsistency
