### ISSUE TITLE
Missing grid message

### ISSUE THREAD

**Issue by SunBlack** [OSGeo/gdal#7753]
## Expected behavior and actual behavior.

In case a grid file is missing you are currently getting only a message like:
```
ERROR 1: No inverse operation
```

After long research I found that the reason was a missing grid file, which can only detected by using:
```
set PROJ_DEBUG=2
set CPL_DEBUG=ON
```

which leads to:

```
PROJ: pj_open_lib(proj.ini): call fopen(C:\dev\dependencies\proj-9.2.0/share/proj/proj.ini) - succeeded
PROJ: pj_open_lib(proj.db): call fopen(C:\dev\dependencies\proj-9.2.0/share/proj/proj.db) - succeeded
PROJ: pj_open_lib(de_adv_BETA2007.tif): call fopen(de_adv_BETA2007.tif) - failed
PROJ: pj_open_lib(BETA2007.gsb): call fopen(BETA2007.gsb) - failed
```

Expected would be a message like:
```
ERROR 1: Could not find grid file de_adv_BETA2007.tif
```

Note: I think it is enough to print the `proj_grid_name`, so `original_grid_name` and `old_proj_grid_name` are just optional additional hints as these are just fallback files.

To catch this issue and show a better message to the user, you can currently only set both environment variables and set `CPLSetErrorHandler` with a regex filter to `PROJ: pj_open_lib\(([^)]*)\): call fopen\(\1\) - failed` (untested).

I also considered abusing PROJ's networking capability for this, but that would require us to explicitly link against PROJ, which would be a bit overkill just to get a better error message.

Another approach is to extract all `proj_grid_name` from the proj.db itself to test in advance if the database matches with the proj-data package, but again this would require explicitly linking sqlite3 (apart from that it would be handy to retrieve all needed files to better test your setup if all files are required, but for that Proj would have to provide an API first)

Note: I came across the issue, as for example vcpkg does not download the proj-data archive itself when building PROJ without network capability.

## Steps to reproduce the problem.

Use following simplified code (and make sure in `PROJ_DATA` only the `proj.db` exists, but no TIFF file or at least no `de_adv_BETA2007.tif` in this case):

```cpp
OGRSpatialReference ogrSpatialReferenceSource;
ogrSpatialReferenceSource.SetAxisMappingStrategy(OAMS_TRADITIONAL_GIS_ORDER);
ogrSpatialReferenceSource.importFromEPSG(3396);
OGRSpatialReference ogrSpatialReferenceTarget;
ogrSpatialReferenceTarget.SetAxisMappingStrategy(OAMS_TRADITIONAL_GIS_ORDER);
ogrSpatialReferenceTarget.importFromEPSG(4978);

const auto ogrCoordinateTransformation = OGRCreateCoordinateTransformation(&ogrSpatialReferenceSource, &ogrSpatialReferenceTarget);

// x/y values from projected bounds
double x = 3563762.14;
double y = 5563059.05;
double z = 100.0;
ogrCoordinateTransformation->Transform(1, &x, &y, &z);

OGRCoordinateTransformation::DestroyCT(ogrCoordinateTransformation);
```

## Operating system

Win10

## GDAL version and provenance

GDAL 3.6.4 + PROJ 9.2

**Comment by jratike80** [comment]
I tried what happens with
`projinfo -s EPSG:3396 -t EPSG:4978`
I have Proj 9.2.0 and GDAL 3.7.0dev-717dcc0eed, released 2023/04/19.
The command gives a hint about missing grid shift file and it is also listing an alternative method

```
...
Grid de_adv_BETA2007.tif needed but not found on the system. Can be obtained at https://cdn.proj.org/de_adv_BETA2007.tif

Operation No. 2:

unknown id, Inverse of 3-degree Gauss-Kruger zone 3 + Ballpark geographic offset from PD/83 to WGS 84 (geographic) + Conversion from WGS 84 (geographic) to WGS 84, unknown accuracy, World, has ballpark transformation

PROJ string:
+proj=pipeline
  +step +proj=axisswap +order=2,1
  +step +inv +proj=tmerc +lat_0=0 +lon_0=9 +k=1 +x_0=3500000 +y_0=0 +ellps=bessel
  +step +proj=cart +ellps=WGS84
```
Sorry, I do not know what this test proves, if anything.

**Comment by msmitherdc** [comment]
You can also set PROJ_NETWORK=on (or set an ini or other methods https://proj.org/usage/network.html) and it should fetch the grid from the CDN. If this needs to be used offline, you can use projsync to sync the file locally.MikeOn May 12, 2023, at 7:32 AM, Jukka Rahkonen ***@***.***> wrote:﻿
I tried what happens with
projinfo -s EPSG:3396 -t EPSG:4978
I have Proj 9.2.0 and GDAL 3.7.0dev-717dcc0eed, released 2023/04/19.
The command gives a hint about missing grid shift file and it is also listing an alternative method
...
Grid de_adv_BETA2007.tif needed but not found on the system. Can be obtained at https://cdn.proj.org/de_adv_BETA2007.tif

Operation No. 2:

unknown id, Inverse of 3-degree Gauss-Kruger zone 3 + Ballpark geographic offset from PD/83 to WGS 84 (geographic) + Conversion from WGS 84 (geographic) to WGS 84, unknown accuracy, World, has ballpark transformation

PROJ string:
+proj=pipeline
  +step +proj=axisswap +order=2,1
  +step +inv +proj=tmerc +lat_0=0 +lon_0=9 +k=1 +x_0=3500000 +y_0=0 +ellps=bessel
  +step +proj=cart +ellps=WGS84

Sorry, I do not know what this test proves, if anything.

**Comment by SunBlack** [comment]
@jratike80 Your output is specific just for the `projinfo` app, see [here](https://github.com/OSGeo/PROJ/blob/f3f6f8f9de9da9f3ddfbdeb71cda4ed93574990f/src/apps/projinfo.cpp#L727). I just wanted to test if the output is different with GDAL 3.7 (this only came out during my debugging), but there I currently have an install error, so I can't test it at the moment.

@msmitherdc That's exactly the point: If you deliver a setup to a customer who doesn't have web access (which some of us actually don't) or PROJ was built without network support, the error message is currently not very helpful. In our case it took me a while to find the error, because first many transformations are successful and only at some point fail (I guess because we first transform some data from 3396 to 4979 and then only coordinates from 3396 to 4978), so at first it was not clear why it failed all of a sudden, because the error message is not very helpful.

**Comment by jratike80** [comment]
I could reproduce with gdaltransform, but it does print the errors. Maybe that could have saved some of your time.
```
gdaltransform -s_srs epsg:3396 -t_srs epsg:4978
ERROR 1: PROJ: hgridshift: could not find required grid(s).
ERROR 1: PROJ: pipeline: Pipeline: Bad step definition: proj=hgridshift (File not found or invalid)
Enter X Y [Z [T]] values separated by space, and press Return.
3563762.14  5563059.05 100.0
transformation failed.
```

**Comment by SunBlack** [comment]
Mhm okay, I guess I have to debug again. It still doesn't say which files are missing, but the message is indeed more helpful.

In our code (see sample code), I don't get the message. If I set the breakpoint in `hgridshift` and see that it comes through there. However, the debug level of the PROJ context there is `0` and not `2`, as on the default PROJ context - and on the `gdaltransform` app I don't see offhand either if that is explicitly set manually.

**Comment by SunBlack** [comment]
Debugged `gdaltransform` now. I can archive same output by calling `GetInverse()` as this somehow causes another call into `hgridshift` with another debug level (removed `PROJ_DEBUG` and `CPL_DEBUG` for this tests now).

So I would have to do this, even if I don't know why I should get the inverse or if it is always needed for a transformation.
```cpp
	OGRSpatialReference ogrSpatialReferenceSource;
	ogrSpatialReferenceSource.SetAxisMappingStrategy(OAMS_TRADITIONAL_GIS_ORDER);
	ogrSpatialReferenceSource.importFromEPSG(3396);
	OGRSpatialReference ogrSpatialReferenceTarget;
	ogrSpatialReferenceTarget.SetAxisMappingStrategy(OAMS_TRADITIONAL_GIS_ORDER);
	ogrSpatialReferenceTarget.importFromEPSG(4978);

	const auto ogrCoordinateTransformation = OGRCreateCoordinateTransformation(&ogrSpatialReferenceSource, &ogrSpatialReferenceTarget);
	OGRCoordinateTransformation::DestroyCT(ogrCoordinateTransformation->GetInverse()); // Just to get an error message in case a grid is missing

	double x = 3563762.14;
	double y = 5563059.05;
	double z = 100.0;
	ogrCoordinateTransformation->Transform(1, &x, &y, &z);

	OGRCoordinateTransformation::DestroyCT(ogrCoordinateTransformation);
```

**Comment by SunBlack** [comment]
Some more details: In the code above `proj_log_error(P, _("could not find required grid(s)."));` will called twice:
1) Due to `proj_create_crs_to_crs_from_pj` (called within `OGRCreateCoordinateTransformation`)
2) Due to `proj_clone` (called within `GetInverse`)

The difference: In the first case the message will be explicitly suppressed (see [here](https://github.com/OSGeo/PROJ/blob/4a7fbe48b489d8e7c5a10de0f67cda8a3b3904a0/src/4D_api.cpp#L2033-L2038)), as the `debug_level` will be set to `PJ_LOG_NONE` in case `errorIfBestTransformationNotAvailable` or `warnIfBestTransformationNotAvailable` are true. The constructor of `pj_ctx` intialize `warnIfBestTransformationNotAvailableDefault` to `true` and `errorIfBestTransformationNotAvailableDefault` to `false`. Both values could be set to `false` by adding the option `ONLY_BEST=no` (which is not possible as you can influence `OGRProjCT::Initialize` only to set `ACCURACY` and `ALLOW_BALLPARK` and nothing other). The other variant: Set the environment variable `PROJ_ONLY_BEST_DEFAULT` or the `proj.ini` value `only_best_default` to e.g. `no` (all everything except `ON`, `YES` or `TRUE`). Bad sadly `hgridshift` isn't called anymore after this.

So still no good was to get a warning.

**Comment by rouault** [comment]
In the current and historical logic of PROJ "do whatever is possible to return some output, even if it is quite approximate", this transformation shouldn't have failed. This is a regression of PROJ 9.2.0, specific to the fact that a geocentric CRS is involved, that will be solved per https://github.com/OSGeo/PROJ/pull/3729

That said, it could be reasonable indeed to have an option in OGRCoordinateTransformationOptions to enable the ONLY_BEST=YES mode of PROJ so that users are sure to get the "best" result and get a meaningful error if not.

**Comment by SunBlack** [comment]
Thanks @rouault. I had not been working with PROJ so much that I knew a fallback was being used (it seems we need to review our transformed data from the last few years). Does the GDAL API provide anything so that you can read which transformation is being used? Because currently it is not apparent if the use of `PROJ_ONLY_BEST_DEFAULT` only affects missing grids or other transforms as well, so I would rather allow the fallback but show the user a warning.

**Comment by jratike80** [comment]
I wonder if users who want to have a total control on what happens should tell what transformations to use with Proj pipelines instead of relying on the defaults which may change. I guess that no fallbacks would happen in that case.

**Comment by SunBlack** [comment]
@jratike80 Basically, I don't want to control the transformation, but show the user a warning if a good transformation is not available, so that he gets a hint why, for example, the transformed data is not exactly where it should be located.

**Comment by rouault** [comment]
> Does the GDAL API provide anything so that you can read which transformation is being used?

no, this could be tricky because if you transform several points at once, different transformations could be used according to which area of validity the points to transform fall into
