### ISSUE TITLE
gdalinfo and other tools finish every command with Segmentation fault (gdal-3.7.0 built from source) 

### ISSUE THREAD

**Issue by velle** [OSGeo/gdal#7770]
## Expected behavior and actual behavior.

Freshly compiled version 3.7.0 seems to work, but all commands finish with a "Segmentation fault". Even when they print the help message, they finish with segmentation fault. 

## Examples of commands finishing with a segmentation fault

```
$ apps/gdalmanage
Usage: gdalmanage identify [-r|-fr] [-u] files*
    or gdalmanage copy [-f driver] oldname newname
    or gdalmanage rename [-f driver] oldname newname
    or gdalmanage delete [-f driver] datasetname
Segmentation fault (core dumped)
```

```
$ apps/gdalinfo "https://api.dataforsyningen.dk/orto_sommer_2008?token=notarealtoken&service=wms"
Driver: WMS/OGC Web Map Service
Files: none associated
Size is 512, 512
Subdatasets:
  SUBDATASET_1_NAME=WMS:https://api.dataforsyningen.dk/orto_sommer_2008?&token=notarealtoken&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&LAYERS=orto_sommer_2008&SRS=EPSG:25832&BBOX=406000,6028000,924000,6430000
  SUBDATASET_1_DESC=Orto sommer 2008
Corner Coordinates:
Upper Left  (    0.0,    0.0)
Lower Left  (    0.0,  512.0)
Upper Right (  512.0,    0.0)
Lower Right (  512.0,  512.0)
Center      (  256.0,  256.0)
Segmentation fault (core dumped)
```

```
$ apps/gdalinfo --help-general 
Generic GDAL utility command options:
  --version: report version of GDAL in use.
  --build: report detailed information about GDAL in use.
  --license: report GDAL license info.
  --formats: report all configured format drivers.
  --format [format]: details of one format.
  --optfile filename: expand an option file into the argument list.
  --config key value: set system configuration option.
  --debug [on/off/value]: set debug level.
  --pause: wait for user input, time to attach debugger
  --locale [locale]: install locale for debugging (i.e. en_US.UTF-8)
  --help-general: report detailed help on general options.
Segmentation fault (core dumped)
```

## Steps to reproduce the problem.

I  followed the guide (https://gdal.org/development/building_from_source.html) for building GDAL from source. 

```
cd ~/c/my_gdal/
wget http://download.osgeo.org/gdal/3.7.0/gdal-3.7.0.tar.gz
tar -xvzf gdal-3.7.0.tar.gz
cd gdal-3.7.0
mkdir build
cd build
cmake ..
cmake --build .
```

I then run the newly compiled tools from the build folder. 

```
~/c/my_gdal/gdal-3.7.0/build$ apps/gdalinfo
Usage: gdalinfo [--help-general] [-json] [-mm] [-stats | -approx_stats] [-hist] [-nogcp] [-nomd]
                [-norat] [-noct] [-nofl] [-checksum] [-proj4]
                [-listmdd] [-mdd domain|`all`] [-wkt_format WKT1|WKT2|...]*
                [-sd subdataset] [-oo NAME=VALUE]* [-if format]* datasetname

FAILURE: No datasource specified.
Segmentation fault (core dumped)
```
The way I understand it, I don't need to run the "install" target if I only want to run these tools as shown below. Am I right? In any case, I did try and run the install target, and it made no difference regarding this issue. 

## Operating system

Ubuntu 22.04 64 bit.

## GDAL version and provenance

GDAL 3.7.0. (http://download.osgeo.org/gdal/3.7.0/gdal-3.7.0.tar.gz)

**Comment by rouault** [comment]
The reason for the crash is that you have 2 copies of PROJ:
```
	libproj.so.25 => /usr/local/lib/libproj.so.25 (0x00007f1754de4000)
	libproj.so.22 => /lib/x86_64-linux-gnu/libproj.so.22 (0x00007f1753a40000)
```
Cf https://github.com/OSGeo/gdal/issues/7100#issuecomment-1397081202

**Comment by rouault** [comment]
> The reason for the crash is that you have 2 copies of PROJ:

we've actually a paragraph about that in the doc: https://gdal.org/development/building_from_source.html#conflicting-proj-libraries

**Comment by velle** [comment]
Thanks :) I spent all day trying to compile GDAL with ECW, still without luck. One of the guides I found described compiling proj4 from source, as part of the process of compiling GDAL. I have to admit that I did not understand why they did that, and apparently I also did not understand the potential consequences. I will see if I can get that cleaned up :)
