### ISSUE TITLE
MRF file not initiated in the same way as GTIFFin python

### ISSUE THREAD

**Issue by simjoh** [OSGeo/gdal#7773]
## Expected behavior and actual behavior.
When initating rasters I expect the output file of the same script to behave in similar manner independent of driver choice. For example when changing from GTIFF to MRF as driver I expect the output of the MRF to be working mrf files. Maybe this is by intention but could be more visible in the documentation.

## Steps to reproduce the problem.
Working example with tif

```
import gdal, osr
geotransform=[500000, 2, 0, 7050000, 0, -2] 
cols=2500
rows=2500
bands=1
outfile = 'out.tif'

driver = gdal.GetDriverByName("GTIFF")
outdata = driver.Create(outfile, cols, rows, bands, gdal.GDT_UInt16)

outdata.SetGeoTransform(geotransform)

srs = osr.SpatialReference()
srs.ImportFromEPSG(3006)
outdata.SetProjection(srs.ExportToWkt())

outdata = None
driver = None
```
Not working for mrf (only mrf.aux.xml created) 

```
import gdal, osr
geotransform=[500000, 2, 0, 7050000, 0, -2] 
cols=2500
rows=2500
bands=1
outfile = 'out2.mrf'

driver = gdal.GetDriverByName("MRF")
outdata = driver.Create(outfile, cols, rows, bands, gdal.GDT_UInt16)

outdata.SetGeoTransform(geotransform)

srs = osr.SpatialReference()
srs.ImportFromEPSG(3006)
outdata.SetProjection(srs.ExportToWkt())

outdata = None
driver = None
```
Working with MRF
```
import gdal, osr
import numpy as np
geotransform=[500000, 2, 0, 7050000, 0, -2] 
cols=2500
rows=2500
bands=1
outfile = 'out3.mrf'

driver = gdal.GetDriverByName("MRF")
outdata = driver.Create(outfile, cols, rows, bands, gdal.GDT_UInt16)

outdata.SetGeoTransform(geotransform)

srs = osr.SpatialReference()
srs.ImportFromEPSG(3006)
outdata.GetRasterBand(1).WriteArray(np.zeros((2500,2500)))
outdata.SetProjection(srs.ExportToWkt())

outdata = None
driver = None
```

## Operating system

Windows 10

## GDAL version and provenance
3.6.4 but same for 3.1.4 python 3.8

**Comment by jratike80** [comment]
I suppose that all drivers behave in a same way if you fill the band with data as in this tutorial gdal.org/tutorials/raster_api_tut.html. The GeoTIFF driver is exceptional because it supports "sparse" data gdal.org/drivers/raster/gtiff.html.

**Comment by simjoh** [comment]
@rouault and @jratike80  Thanks a lot! It works on my end as well. I guess it is my knowledfe of the different raster formats that has to be improved together with my understanding of different gdal versions.
