### ISSUE TITLE
What does "creation" and "copy" mean in the list of raster drivers?

### ISSUE THREAD

**Issue by velle** [OSGeo/gdal#7775]
https://gdal.org/drivers/raster/index.html

My best guess is the following: "creations" tells whether that driver is able to actually create files of the , or if it is read only. But in that case, perhaps the list is incorrect, since I am able to create jpegs from tifs. 

```
$ ecw_translate foo.tif foo.jpeg -of jpeg
Input file size is 32000, 8000
0...10...20...30...40...50...60...70...80...90...100 - done.
```

So what do those columns actually mean? 

I humbly suggest someone with the proper insight to provide an explanation of the column meanings to the list :)

Sincerely.

**Comment by jratike80** [comment]
You do not see what happens internally. The command does not create a JPEG that is not then filled pixel by pixel, but the command creates first an interim layer object. When it is ready the layer is then **copied** into JPEG.

For me it looks like you asked a question in a wrong forum

> IMPORTANT: Do NOT use GitHub to post any questions or support requests!
>            They will be closed immediately and ignored.
> 
> Questions should go to the gdal-dev mailing list at
> https://lists.osgeo.org/mailman/listinfo/gdal-dev
> or other support forums. GitHub issues are for bug
> reports and suggestions for new features.
