### ISSUE TITLE
build 3.7.0 from source failed in macos.

### ISSUE THREAD

**Issue by sendreams** [OSGeo/gdal#7779]
build 3.7.0 from source failed in macos.

## Steps to reproduce the problem.

Follow the instructions in this post to compile [building_from_source_document](https://gdal.org/development/building_from_source.html)
[ 90%] Built target gdal_GIF
[ 90%] Building CXX object frmts/wcs/CMakeFiles/gdal_WCS.dir/gmlcoverage.cpp.o
[ 90%] Building CXX object frmts/wcs/CMakeFiles/gdal_WCS.dir/wcsdataset.cpp.o
[ 90%] Building CXX object frmts/wcs/CMakeFiles/gdal_WCS.dir/wcsdataset100.cpp.o
[ 90%] Building CXX object frmts/wcs/CMakeFiles/gdal_WCS.dir/wcsdataset110.cpp.o
[ 90%] Building CXX object frmts/wcs/CMakeFiles/gdal_WCS.dir/wcsdataset201.cpp.o
[ 90%] Building CXX object frmts/wcs/CMakeFiles/gdal_WCS.dir/wcsrasterband.cpp.o
[ 90%] Building CXX object frmts/wcs/CMakeFiles/gdal_WCS.dir/wcsutils.cpp.o
[ 90%] Built target gdal_WCS
make[2]: *** No rule to make target `/opt/MacOSX10.10.sdk/usr/lib/libpthread.tbd', needed by `libgdal.33.3.7.0.dylib'.  Stop.
make[1]: *** [CMakeFiles/GDAL.dir/all] Error 2
make: *** [all] Error 2
(base) chenhong@ChenhonacStudio build % cmake --version
cmake version 3.25.2
(base) chenhong@ChenhonacStudio build % ant -version
Apache Ant(TM) version 1.10.13 compiled on January 4 2023
(base) chenhong@ChenhonacStudio build % java -version
openjdk version "11.0.16.1" 2022-08-12
OpenJDK Runtime Environment Homebrew (build 11.0.16.1+0)
OpenJDK 64-Bit Server VM Homebrew (build 11.0.16.1+0, mixed mode)

## Operating system

mac studio m1 
macOS Ventura 13.3.1 

## GDAL version and provenance

gdal-3.7.0.tar.gz

**Comment by sendreams** [comment]
The error occurs in this command:
> cmake --build .

**Comment by rouault** [comment]
Don't you have a mix of SDKs in your system ? This somehow reminds me of https://github.com/OSGeo/gdal/issues/6485
Isn't /opt/MacOSX10.10.sdk/ an ancient SDKs ? It seems newer ones should be in /Library/Developer/CommandLineTools/SDKs and version numbers like 12.x or 13.x.
Does the file /opt/MacOSX10.10.sdk/usr/lib/libpthread.tbd exist ?
If not, is there a libpthread.tbd file somewhere else on your system ?
Please also attach the CMakeCache.txt file generated by cmake in your build directory
(note: I don't own a Mac, but we have several working MacOSX CI targets, so I'd suspect something specific to your system)

**Comment by sendreams** [comment]
CMakeCache.txt
[CMakeCache.txt](https://github.com/OSGeo/gdal/files/11489746/CMakeCache.txt)

Does the file /opt/MacOSX10.10.sdk/usr/lib/libpthread.tbd exist ?
A: have no this folder and file.

**Comment by rouault** [comment]
So from your CMakeCache.txt, your SDK is in /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk . There's no trace of /opt/MacOSX10.10.sdk/ in that file
So something on your system must link to that unexisting directory. I'm afraid you're the only one in a position to track this.

Perhaps try doing a minimal build with
```
cmake .. -UGDAL_ENABLE_DRIVER_* -UOGR_ENABLE_DRIVER_* \
         -DGDAL_BUILD_OPTIONAL_DRIVERS:BOOL=OFF -DOGR_BUILD_OPTIONAL_DRIVERS:BOOL=OFF  "-UGDAL_USE*" -GDAL_USE_EXTERNAL_LIBS=OFF
```
(cf https://gdal.org/development/building_from_source.html)
and enable dependencies one by one until you spot the one that causes the issue

**Comment by sendreams** [comment]
@rouault 
It should be my environment problem. It was normal when compiling 3.6.2 before, but now the same error will appear when recompiling 3.6.2, but I have no idea at all, and I don’t know where the problem is.

I have explicitly set the variable value in cmakelist.txt

> set(JAVA_INCLUDE_PATH /Library/Java/JavaVirtualMachines/jdk-11.0.16.jdk/Contents/Home/include)
set(CMAKE_OSX_SYSROOT "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk")

not working.

**Comment by rouault** [comment]
The end of your cmake.log is interesting:
```
CMake Warning at gdal.cmake:356 (add_library):
  Cannot generate a safe runtime search path for target GDAL because there is
  a cycle in the constraint graph:

    dir 0 is [/Users/chenhong/opt/anaconda3/lib]
      dir 1 must precede it due to runtime library [libgeos_c.1.dylib]
    dir 1 is [/opt/homebrew/lib]
      dir 0 must precede it due to runtime library [libnetcdf.19.dylib]

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  CMakeLists.txt:226 (include)
```

It seems you have a mix of Conda and homebrew dependencies both available. This is a receipt for issues.

**Comment by sendreams** [comment]
So how should this problem be fixed? Mandatory to specify a certain path?

**Comment by rouault** [comment]
> So how should this problem be fixed?

Hard to say for sure. Perhaps remove anaconda and/or homebrew from your PATH. Play with the various general CMake variables that determine which paths are searched (cf the CMAKE_FIND_xxx variables listed in https://cmake.org/cmake/help/latest/manual/cmake-variables.7.html)

**Comment by sendreams** [comment]
@rouault 

> export PATH=...
cmake ..
cmake --build .

remove anaconda from path before cmake
done!

thanks
