### ISSUE TITLE
Inconsistent usage of CRS 0 and -2 in ogr2ogr with MySQL/Dolt

### ISSUE THREAD

**Issue by latot** [OSGeo/gdal#7781]
Hi all, well the title was... the most accurate I was able to think, maybe is completely wrong.

I'm using Dolt, is a project should replace MySQL, in the way we can exchange them, the difference is that Dolt support some commands where we are able to run git commands directly, so we can have commits and control version in the db.

I was testing with Dolt 1.0.0, and we found something really strange.

To reproduce, here are the steps, but the point of view of the results will be different https://github.com/dolthub/dolt/issues/5931

To mount the dolt server just do:
```
mkdir dolt
cd dolt
dolt init
dolt sql-server -l trace 2> debug
```

Now, what is weird, the command first will upload the data, if we check the queries in the server log, we will found this:
```
ST_GeomFromText('POINT (-7946533.9349 -4089497.1034)',0)
```

The data has 3857 CRS, I don't know too much about MySQL with spatial, I know more of postgis.

Well, Dolt actually only supports CRS 0 and 4326, so is likely the CRS 3857 does not exists in the server, I tested a command like:
```
SELECT SRS_ID FROM INFORMATION_SCHEMA.ST_SPATIAL_REFERENCE_SYSTEMS WHERE ORGANIZATION = 'EPSG' AND ORGANIZATION_COORDSYS_ID = 3857
```

And returned nothing, ogr2ogr has a lot of ways to check this, but I don't get any message from ogr2ogr about didn't found it.

This is the first inconsistency, if ogr2ogr does not found the CRS, I think should send a warning or better send an error, I think is better says "CRS unsupported" and have a param to bypass it with CRS 0 than in reverse, where we practically loss the CRS!

Well, the weird part comes here, when we upload the data, it run well, but when we try to append data to the existing table (same command to upload):
```
ogr2ogr -f MySQL  "MYSQL:dolt,user=root,port=3306,host=127.0.0.1" "data.gpkg"
```

Dolt will complain the CRS -2 does not exists, checking the server logs:
```
ST_GeomFromText('POINT (-7860125.2396 -3040341.3372)',-2)
```
Unsupported CRS -2 is a Dolt issue, but the points are the next ones.

Here I'm loss, first I tested this with Postgis, if a CRS does not exists ogr2ogr will create the CRS in the CRS table.
While, in MySQL if the CRS does not exists, seems to use 0 instead, and for append data will use -2.

I checked the server logs, there is no try from ogr2ogr to create the missed CRS.

Other problem with this is, if first is used CRS 0 and then -2, we will unable to append data because ogr2ogr will use two different CRS for the same table.

Here is the logs from the server Dolt of all this steps.
[debug.zip](https://github.com/OSGeo/gdal/files/11490263/debug.zip)

Gentoo 64
GDAL 3.7.0
Dolt 1.0.0

Thx!

**Comment by latot** [comment]
Hi! before close wait a little plis D:

@rouault I and a Dolt team we have tested this, when we try to add new CRS to the table, MySQL lock us says we can't edit the table.

If you tested this on MySQL, what version did you use?

And... @JCOR11599 please come here!

Thx!

**Comment by rouault** [comment]
> when we try to add new CRS to the table, MySQL lock us says we can't edit the table.

yes, you can't directly insert into it. I found it the hard way.... You need to do so through "CREATE SPATIAL REFERENCE SYSTEM" (https://dev.mysql.com/doc/refman/8.0/en/create-spatial-reference-system.html) which is what https://github.com/OSGeo/gdal/pull/7812 will do.
I tested with mysql 8.0.18 from Docker image mysql/mysql-server:8.0.18
