### ISSUE TITLE
Process finished with exit code -1073740940 (0xC0000374) when processing  shapefile

### ISSUE THREAD

**Issue by YaminGuo** [OSGeo/gdal#7782]
## Expected behavior and actual behavior.

Hi! I expected to get the coordinate range of coordinate range of the specified feature in the shapfile
[shapefile.zip](https://github.com/OSGeo/gdal/files/11491208/shapefile.zip).
But when I run the following code, I got:
**Process finished with exit code -1073740940 (0xC0000374)**

It is quite weird since I don't know exactly what is going wrong.

Thanks in advance

## Steps to reproduce the problem.

from osgeo import  ogr
ogr.DontUseExceptions()
file = 'C:/shapefile/gadm36_USA_2.shp'
driver = ogr.GetDriverByName('ESRI Shapefile')
ds = driver.Open(file)
layer = ds.GetLayer(0)
print(layer.GetFeatureCount())
layer.SetAttributeFilter("NAME_1='Maryland'")
print(layer.GetFeatureCount())
feature = layer.GetNextFeature()
lat=[]
lon=[]
while feature is not None:
    print(feature.GetField('NAME_2'))
    geom = feature.GetGeometryRef()
    print(geom.GetEnvelope())
    feature_range = geom.GetEnvelope()
    lon.append(feature_range[0])
    lon.append(feature_range[1])
    lat.append(feature_range[2])
    lat.append(feature_range[3])
    feature.Destroy()
    feature = layer.GetNextFeature()
ds.ReleaseResultSet(layer)
ds.Destroy()

## Operating system

Win11 64 bit

## GDAL version and provenance

the 3.4.3 version from Pypi

**Comment by rouault** [comment]
> ds.ReleaseResultSet(layer)

this should only be called on a layer obtained by ExecuteSQL(), not one returned by GetLayer(). You don't have to free layers returned by GetLayer()

**Comment by rouault** [comment]
> After delete ds.ReleaseResultSet(layer), a new problem is returned:

This works fine for me when removing the call to ds.ReleaseResultSet(layer).

**Comment by YaminGuo** [comment]
> 

Hi @rouault I found that it works  when I just run the code, but when I add a breakpoint to debug(I add  bbox_2 = [min(lon), min(lat), max(lon), max(lat)] after ds.Destroy() and add a breakpoint in this line), it will return
Process finished with exit code -1073741819 (0xC0000005).
