### ISSUE TITLE
Implement ESRI Tile Package (.tpkx) format

### ISSUE THREAD

**Issue by szekerest** [OSGeo/gdal#7784]
This format (as described per [https://github.com/Esri/tile-package-spec](https://github.com/Esri/tile-package-spec)) is in fact an [Esri Compact Cache V2](https://github.com/Esri/raster-tiles-compactcache) in a zipped package. The bulk of the implementation is already done within the ESRIC driver, which should be modified to read the root.json metadata file in addition to the current conf.xml file. (The provided parameters are basically the same).
According to the suggested implementation the following syntax would be used.

/vsizip/{path to tpkx file}/root.json

A sample file [Usa.tpkx](https://github.com/Esri/tile-package-spec/blob/master/Sample%20TPKX%20Files/Usa.tpkx) is available for testing the implementation.

**Comment by rouault** [comment]
I'm CC'ing @lucianpls since I copied him of @szekerest initial email so both of you can appropriately coordinate

**Comment by szekerest** [comment]
Thanks @rouault I'm trying to commit the required patch in the next few days.
