### ISSUE TITLE
DOCS: `SQLite3_INCLUDE_DIR` -> `SQLITE3_INCLUDE_DIR`, ...?

### ISSUE THREAD

**Issue by HenrikBengtsson** [OSGeo/gdal#7785]
On <https://gdal.org/development/building_from_source.html#sqlite3> environment variables:

* `SQLite3_INCLUDE_DIR`
* `SQLite3_LIBRARY`

Should `SQLite3_INCLUDE_DIR` and `SQLite3_LIBRARY` be in all-upper-case, because in <https://gdal.org/development/building_from_source.html#cmake-gdal-versions-3-5-0>, the example:

```
cmake -DSQLITE3_INCLUDE_DIR=/opt/SQLite/include -DSQLITE3_LIBRARY=/opt/SQLite/lib/libsqlite3.so ..
```

uses the all-capital versions.

**Comment by rouault** [comment]
Fixed per c4855e35e8
