### ISSUE TITLE
MSSQL: ogr2ogr crash when using MSSQLSPATIAL_USE_BCP

### ISSUE THREAD

**Issue by elpaso** [OSGeo/gdal#7787]
The MSSQL driver may reset the feature definition when initializes BCP, `LayerTranslator::Translate` holds a raw pointer to it, causing the crash when assigning a deleted definition to a new feature (this happens on the second feature copy).

I discovered this while writing a test for BCP insert in `autotest/ogr/ogr_mssqlspatial.py`

```python
def test_ogr_mssqlspatial_bulk_insert():

    if gdaltest.mssqlspatial_ds is None:
        pytest.skip()

    source_ds = gdal.OpenEx("data/poly.shp", gdal.OF_VECTOR)

    assert source_ds

    try:
        gdaltest.mssqlspatial_ds.ExecuteSQL("DROP TABLE poly")
    except Exception as ex:
        pass

    with gdaltest.error_handler():
        res = gdal.VectorTranslate(
            gdaltest.mssqlspatial_dsname,
            "data/poly.shp",
            layerCreationOptions=[
                "OVERWRITE=YES",
                "MSSQLSPATIAL_USE_BCP=YES",
                "MSSQLSPATIAL_BCP_SIZE=2",
            ],
        )

        lyr = gdaltest.mssqlspatial_ds.GetLayerByName('poly')
        assert lyr
        assert lyr.GetFeatureCount() == 10
        del lyr

```

A possible patch to fix the issue:

```C++
diff --git a/apps/ogr2ogr_lib.cpp b/apps/ogr2ogr_lib.cpp
index d73c4b5637..2194dcc2ff 100644
--- a/apps/ogr2ogr_lib.cpp
+++ b/apps/ogr2ogr_lib.cpp
@@ -5186,7 +5186,7 @@ int LayerTranslator::Translate(OGRFeature *poFeatureIn, TargetLayerInfo *psInfo,
     const int iSrcZField = psInfo->m_iSrcZField;
     const bool bPreserveFID = psInfo->m_bPreserveFID;
     const auto poSrcFDefn = poSrcLayer->GetLayerDefn();
-    const auto poDstFDefn = poDstLayer->GetLayerDefn();
+    auto poDstFDefn = poDstLayer->GetLayerDefn();
     const int nSrcGeomFieldCount = poSrcFDefn->GetGeomFieldCount();
     const int nDstGeomFieldCount = poDstFDefn->GetGeomFieldCount();
     const bool bExplodeCollections =
@@ -5345,6 +5345,9 @@ int LayerTranslator::Translate(OGRFeature *poFeatureIn, TargetLayerInfo *psInfo,
             {
                 poDstFeature = std::move(poFeature);
                 // From now on, poFeature is null !
+                // Some drivers (MSSQL) may release the feature definition, we
+                // need to get a fresh one.
+                poDstFDefn = poDstLayer->GetLayerDefn();
                 poDstFeature->SetFDefnUnsafe(poDstFDefn);
                 poDstFeature->SetFID(nDesiredFID);
             }

```

**Comment by rouault** [comment]
> The MSSQL driver may reset the feature definition when initializes BCP,

It shouldn't do that. The raw pointer returned by GetLayerDefn() is supposed to stay alive forever. Why would the layer defn change when initializing the BCP ?

> A possible patch to fix the issue:

I'm not enthusiastic about such a fix. There are probably many other places in the code base, or in external code using GDAL, that relies on the assumption GetLayerDefn() doesn't change over the lifetime of a OGRLayer instance

**Comment by elpaso** [comment]
> > The MSSQL driver may reset the feature definition when initializes BCP,
> 
> It shouldn't do that. The raw pointer returned by GetLayerDefn() is supposed to stay alive forever. Why would the layer defn change when initializing the BCP ?

I suspected it was something in the driver:
https://github.com/OSGeo/gdal/blob/master/ogr/ogrsf_frmts/mssqlspatial/ogrmssqlspatialtablelayer.cpp#L1568

**Comment by elpaso** [comment]
> > A possible patch to fix the issue:
> 
> I'm not enthusiastic about such a fix. There are probably many other places in the code base, or in external code using GDAL, that relies on the assumption GetLayerDefn() doesn't change over the lifetime of a OGRLayer instance


Apparently the OGRVRT driver does also release the layer definition.

MSSQL actually requires the re-initialization (the test fails if the re-initialization is commented out) probably because of side-effects of the `GetLayerDefn` call, I'll have to investigate that further.

**Comment by rouault** [comment]
> Apparently the OGRVRT driver does also release the layer definition.

Are you talking about line 1090 of ogrvrtlayer.cpp ? As far as I can see, this is fine as this isn't visible from the user. The poFeatureDefn object is created right at the beginning of the OGRVRTLayer::FullInitialize() method, and line 1090 is within that same method.

In the instances where changing the layer defn would be really needed, one would have to put in place a translation logic between the user visible layer defn and the internal one that would have been modified. But that's quite annoying to have to do that (although not totally equivalent to what I mention, OGRWarpedLayer::SrcFeatureToWarpedFeature() is an example of how to deal with translation of features between 2 layer defns)

**Comment by elpaso** [comment]
@szekerest do you by chance remember why this is necessary? https://github.com/OSGeo/gdal/blob/master/ogr/ogrsf_frmts/mssqlspatial/ogrmssqlspatialtablelayer.cpp#L1567
