### ISSUE TITLE
Raster OpenFileGDB/ESRI FileGDB driver failure 

### ISSUE THREAD

**Issue by hobu** [OSGeo/gdal#7794]
Using https://gisdata.mn.gov/dataset/water-lake-bathy-shaded-relief as test data along with 3.7, I get the following output from somewhere:

```
$ gdal_translate -f COG bathy_fgdb/water_lake_bathy_shaded_relief.gdb bathy.tif
ERROR 1: missing [
```

Setting `CPL_DEBUG=ON` shows an unending blizzard of lint about field block key
```
...
OpenFileGDB: Using index on field block_key (= 00000001000070005E)
OpenFileGDB: Using index on field block_key (= 00000001000070005F)
OpenFileGDB: Using index on field block_key (= 000000010000700060)
OpenFileGDB: Using index on field block_key (= 000000010000700061)
OpenFileGDB: Using index on field block_key (= 000000010000700062)
OpenFileGDB: Using index on field block_key (= 000000010000700063)
OpenFileGDB: Using index on field block_key (= 000000010000700064)
OpenFileGDB: Using index on field block_key (= 000000010000700065)
...
```

but there is no clear message why things are failing. Presumably it has to do with the `[`.

**Comment by rouault** [comment]
> Presumably it has to do with the `[`.

that one was actually harmless (now shut off). The real issue was indeed a silent one related to misalignment between GDAL & FileGDB raster origin conventions, block numbering, etc. Fixed per https://github.com/OSGeo/gdal/pull/7795
