### ISSUE TITLE
Failed to write a shapefile to webhdfs

### ISSUE THREAD

**Issue by wuxianshenga** [OSGeo/gdal#7801]
## Expected behavior and actual behavior.

An error occurred when I wrote shapefile to hdfs using the webhdfs prefix

HTTP: libcurl/7.85.0 Schannel zlib/1.2.13 libssh2/1.10.0
GDAL: GDALDriver::Create(ESRI Shapefile,/vsiwebhdfs/http://localhost:50070/webhdfs/v1/tmp.shp,0,0,0,Unknown,0000000000000000)
ERROR 1: Only read-only mode is supported for /vsicurl
WEBHDFS: (null)
ERROR 1: PUT of http://localhost:50070/webhdfs/v1\tmp.shp failed
ERROR 1: Failed to create file /vsiwebhdfs/http://localhost:50070/webhdfs/v1\tmp.shp: No such file or directory
GDAL: GDALClose(/vsiwebhdfs/http://localhost:50070/webhdfs/v1/tmp.shp, this=00000144649FF2D0)
GDAL: In GDALDestroy - unloading GDAL shared library.

## Steps to reproduce the problem.

    CPLSetConfigOption("GDAL_FILENAME_IS_UTF8", "NO");
    CPLSetConfigOption("SHAPE_ENCODING", "");
    CPLSetConfigOption("CPL_DEBUG", "ON");
    CPLSetConfigOption("CPL_VSIL_USE_TEMP_FILE_FOR_RANDOM_WRITE", "YES");
    CPLSetConfigOption("WEBHDFS_USERNAME", "root");
    CPLSetConfigOption("WEBHDFS_DELEGATION", "token");
    GDALAllRegister();

    const char* shapefile = "/vsiwebhdfs/http://localhost:50070/webhdfs/v1/tmp.shp";
    
    GDALDriver* pdriver = GetGDALDriverManager()->GetDriverByName("ESRI Shapefile");
    GDALDataset* pdst = pdriver->Create(shapefile, 0, 0, 0, GDT_Unknown, nullptr);
    OGRLayer* player = pdst->CreateLayer("tmp");
    GDALClose(pdst);

## Operating system

windows and centos7

## GDAL version and provenance

3.6.2

**Comment by jratike80** [comment]
Are you sure that you can do it that way? In the autotests https://github.com/OSGeo/gdal/blob/master/autotest/gcore/vsiwebhdfs.py  I can see only PUT requests. The documentation in https://gdal.org/user/virtual_file_systems.html#vsihdfs-hadoop-file-system says about TIFF files say

> It also allows sequential writing of files. No seeks or read operations are then allowed, so in particular direct writing of GeoTIFF files with the GTiff driver is not supported

Maybe you should create shapefile with all its components locally and PUT them file by file afterwards.
All the knowledge that I have about vsihdfs comes from reading the documentation during the last 15 minutes so I am no expert. I apologize that.
