### ISSUE TITLE
Building GDAL 3.7.0 - SWIG error

### ISSUE THREAD

**Issue by wadudmiah** [OSGeo/gdal#7803]
Hi,

I am trying to build GDAL 3.7.0 with the following CMAKE flags:

$ cmake -DPROJ_INCLUDE_DIR=/local/software/proj/9.2.0/include -DPROJ_LIBRARY_RELEASE=/local/software/proj/9.2.0/lib64/libproj.so -DCMAKE_INSTALL_PREFIX=/local/software/gdal/3.7.0 -DSQLite3_INCLUDE_DIR=/local/software/sqlite/3.41.0/local/software/sqlite/3.41.0/include -DSQLite3_LIBRARY=/local/software/sqlite/3.41.0/local/software/sqlite/3.41.0/lib/libsqlite3.so ..

it builds fine with `make`, but when I do a `make install`, I get the following SWIG error:
```
[ 95%] Built target check_ods_formula_parser_md5
[ 95%] Generating extensions/gdal_wrap.cpp, osgeo/gdal.py
swig error : Unrecognized option -relativeimport
Use 'swig -help' for available options.
make[2]: *** [swig/python/extensions/gdal_wrap.cpp] Error 1
make[1]: *** [swig/python/CMakeFiles/python_binding.dir/all] Error 2
make: *** [all] Error 2
```

The output of `swig -help` does not show the `-relativeimport` flag.

**Comment by rouault** [comment]
@wadudmiah  What is your swig version, as reported by ``swig -version`` ?

**Comment by wadudmiah** [comment]
It is version 4.1.1 which I believe is the latest version.

**Comment by wadudmiah** [comment]
$ swig -version
```
SWIG Version 4.1.1

Compiled with /local/software/gcc/6.4.0/bin/g++ [x86_64-pc-linux-gnu]

Configured options: +pcre
```

**Comment by wadudmiah** [comment]
This is how I built SWIG:
```
./configure --prefix=/local/software/swig/4.1.1 --with-python=/local/software/python/2.7.14/bin/python2.7 --with-python3=/local/software/python/3.11.0/bin/python3.11
```

**Comment by rouault** [comment]
@wadudmiah  I cannot reproduce the error with SWIG 4.1.1.  `` -relativeimport`` is a legit option

```
$ ~/install-swig-4.1.1/bin/swig -python -help | grep relativeimport
     -relativeimport - Use relative Python imports
```

**Comment by wadudmiah** [comment]
I also get the same output as you:
```
$ swig -python -help | grep relativeimport
     -relativeimport - Use relative Python imports
```

**Comment by rouault** [comment]
are you sure the SWIG version GDAL uses is the one of /local/software/swig/4.1.1  ? Check the output of "grep SWIG CMakeCache.txt"

**Comment by wadudmiah** [comment]
hi,

The newer version of SWIG wasn't in the PATH variable during the cmake stage, hence it was picking up an older version. So I have fixed this issue - many thanks for resolving this issue. 

By the way, during the cmake stage, I get the following warnings:
```
CMake Warning:
  Manually-specified variables were not used by the project:

    PROJ_INCLUDE_DIR
    PROJ_LIBRARY_RELEASE
```

I've passed those variables during cmake:
```
cmake -DPROJ_INCLUDE_DIR=/local/software/proj/9.2.0/include -DPROJ_LIBRARY_RELEASE=/local/software/proj/9.2.0/lib64/libproj.so ...
```
The documentation (https://gdal.org/development/building_from_source.html#proj) says that these are valid variables, so I don't know why they are being ignored.

Regards,

**Comment by rouault** [comment]
> so I don't know why they are being ignored.

PROJ is detected in priority through CMake config files, in which case PROJ_INCLUDE_DIR and PROJ_LIBRARY_RELEASE will be ignored.

**Comment by wadudmiah** [comment]
So how do I tell GDAL to pick up PROJ from a specific directory?

**Comment by rouault** [comment]
> So how do I tell GDAL to pick up PROJ from a specific directory?

through generic CMake mechanisms (cf https://cmake.org/cmake/help/v3.0/command/find_package.html). For example with CMAKE_PREFIX_PATH or PROJ_DIR
