### ISSUE TITLE
Any version available where assembly should be digitally signed

### ISSUE THREAD

**Issue by reddysanjeev87** [OSGeo/gdal#7804]
We are using this package in one of our applications. We have a Release Audit Scored card failure because Assemblies should be digitally signed. Is there any version in which Assemblies are digitally signed?

**Comment by reddysanjeev87** [comment]
> > because Assemblies should be digitally signed
> 
> which assemblies are you talking about ? Something in the CSharp bindings ?

gdal_csharp.dll

**Comment by szekerest** [comment]
@reddysanjeev87 Regarding to the csharp assemblies, the files are strong name signed by default with the provided key file in https://github.com/OSGeo/gdal/blob/master/swig/csharp/gdal.snk. 
In this paticular case, I think the requirement would be to authenticode sign the assemblies. If you have a valid .pfx file, you could resign the assembly to make it authenticode signed as follows:

`signtool sign /f "path\to\your\certificate.pfx" /p "password" /tr http://timestamp.digicert.com /td sha256 "path\to\your\gdal_csharp.dll"`

**Comment by szekerest** [comment]
Yes I think we can mention that the build process provides the csharp assemblies to be strong-name-signed with the provided .snk key file. If the dll-s should be authenticode signed, that should be done after the build process (this also applies to the unmanaged dll-s like the gdal.dll which can also be signed that way).
