### ISSUE TITLE
Java API: runtime java.lang.NoSuchFieldError when accessing gdalconst.GDT_Int64 or gdalconst.GDT_UInt64

### ISSUE THREAD

**Issue by bdezonia** [OSGeo/gdal#7892]
I am writing a small java project that interacts with GDAL. Here is my GDAL dependency in my pom.xml

    <dependency>
      <groupId>org.gdal</groupId>
      <artifactId>gdal</artifactId>
      <version>3.7.0</version>
    </dependency>

When I use either of the INT64 based integral type constants (gdalconst.GDT_Int64 and gdalconst.GDT_UInt64) my code compiles fine. But at runtime, if I refer to the constants in my code, I get a java.lang.NoSuchFieldError exception at the point where it is defined.

Example code:

if (typeNum == gdalconst.GDT_Int64)
    System.out.println("The app never gets here!");
System.out.println("And the app never gets here!");

## Operating system
Ubuntu Linux 22.04

## GDAL version and provenance
GDAL 3.5.3 (according to gdalinfo) but maybe 3.4.3 according to apt

> apt list gdal*
Listing... Done
gdal-bin/jammy 3.4.3+dfsg-1~jammy0 amd64
gdal-data/jammy,jammy,now 3.4.3+dfsg-1~jammy0 all [installed,automatic]

**Comment by bdezonia** [comment]
Fails for jar versions 3.6.0 and 3.5.0 as well. Do these 64-but int types only work in C, C++, and maybe Python?

**Comment by bdezonia** [comment]
Sorry. I had discovered these constants in a document online of some C++ code. I can't find it now. All the docs I find now don't mention the 64 bit integral types existing. Maybe this is user error.

**Comment by rouault** [comment]
I still suspect a user error, presumably using gdal.jar of GDAL >= 3.5.0 which is the version with GDT_Int64 against libgdaljni.so of an older version

Modifying one of test programs as below
```
diff --git a/swig/java/apps/GDALTestIO.java b/swig/java/apps/GDALTestIO.java
index 85dc88b6b7..1c1abc67ac 100644
--- a/swig/java/apps/GDALTestIO.java
+++ b/swig/java/apps/GDALTestIO.java
@@ -162,6 +162,7 @@ public class GDALTestIO implements Runnable
     public static void main(String[] args) throws InterruptedException
     {
         gdal.AllRegister();
+               System.out.println(gdalconst.GDT_Int64);
 
         int nbIters = 50;
 
```

``ctest -R java_GDALTestIO -V`` outputs:
```
11: 13
11: Success !
1/1 Test #11: java_GDALTestIO ..................   Passed    1.30 sec
```

**Comment by bdezonia** [comment]
Well, this is what I find on my system:

bdz@cheeto:~/dev/gdal$ ls -al /home/bdz/dev/gdal/build/swig/java/libgdalalljni.so
-rwxrwxr-x 1 bdz bdz 1157064 Nov 15  2022 /home/bdz/dev/gdal/build/swig/java/libgdalalljni.so

bdz@cheeto:~/dev/gdal$ ls -al /usr/java/packages/lib/libgdalalljni.so
-rw-r--r-- 1 root root 1157064 Nov 15  2022 /usr/java/packages/lib/libgdalalljni.so

bdz@cheeto:~/dev/gdal$ ls -al /usr/share/java/libgdalalljni.so
-rw-r--r-- 1 root root 1157064 Nov 15  2022 /usr/share/java/libgdalalljni.so

And the swig one was built from GDAL 3.5.3 (I have the code in a detached head state).

"HEAD detached at v3.5.3"

What could I be doing wrong? Is there some other JNI file I should be looking for?

**Comment by bdezonia** [comment]
This:

find / -name libgdaljni.so*

finds nothing

**Comment by rouault** [comment]
Sorry, I meant libgdalalljni.so.
I tried with master. If there was some bug in the past in the bindings, we can't fix it. and if you intend doing upstream changes, you'll have to be on master anyway

**Comment by bdezonia** [comment]
I checked out v3.6.4 and built and the problem went away.
