### ISSUE TITLE
Build error: flatgeobuf using incompatible absl/strings/string_view.h

### ISSUE THREAD

**Issue by dg0yt** [OSGeo/gdal#7894]
## Expected behavior and actual behavior.

From https://github.com/microsoft/vcpkg/issues/31804: 
On some machines, buidling gdal 3.7.0 may fail like this:
~~~
In file included from /usr/include/absl/base/config.h:86,
                 from /usr/include/absl/base/attributes.h:37,
                 from /usr/include/absl/strings/string_view.h:39,
                 from /home/user/.local/vcpkg/buildtrees/gdal/src/v3.7.0-9fd58c78bf.clean/ogr/ogrsf_frmts/flatgeobuf/flatbuffers/base.h:237,
                 from /home/user/.local/vcpkg/buildtrees/gdal/src/v3.7.0-9fd58c78bf.clean/ogr/ogrsf_frmts/flatgeobuf/flatbuffers/array.h:20,
                 from /home/user/.local/vcpkg/buildtrees/gdal/src/v3.7.0-9fd58c78bf.clean/ogr/ogrsf_frmts/flatgeobuf/flatbuffers/flatbuffers.h:22,
                 from /home/user/.local/vcpkg/buildtrees/gdal/src/v3.7.0-9fd58c78bf.clean/ogr/ogrsf_frmts/flatgeobuf/header_generated.h:6,
                 from /home/user/.local/vcpkg/buildtrees/gdal/src/v3.7.0-9fd58c78bf.clean/ogr/ogrsf_frmts/flatgeobuf/ogr_flatgeobuf.h:36,
                 from /home/user/.local/vcpkg/buildtrees/gdal/src/v3.7.0-9fd58c78bf.clean/ogr/ogrsf_frmts/flatgeobuf/ogrflatgeobufdataset.cpp:29:
/usr/include/absl/base/policy_checks.h:79:2: error: #error "C++ versions less than C++14 are not supported."
   79 | #error "C++ versions less than C++14 are not supported."
      |  ^~~~~
~~~

## Steps to reproduce the problem.

`vcpkg install gdal` on an affected system.

## Operating system

Manjaro Linux 22.1.0 Talos

## GDAL version and provenance

3.7.0, building via vcpkg.

## More information

The flatgeobuf driver uses a vendored copy of flatbuffer. That version may use abseil's string view if it is available:
https://github.com/OSGeo/gdal/blob/ab9cb1a1d4928cdcf2877d8e0c6ad9fc2c79fbc9/ogr/ogrsf_frmts/flatgeobuf/flatbuffers/base.h#L236-L237

Newer versions of flatbuffers add more conditions to guard the use of abseil's string_view:
https://github.com/google/flatbuffers/blob/72b56fd0810c9a6cd38ea1c8f40feaa1bb4916b1/include/flatbuffers/base.h#L237-L239

This probably fixes the problem.

FTR vcpkg has packages for abseil and flatbuffers.
But there is no configuration hook to use them during them during the build.
gdal should avoid picking up abseil without control.

**Comment by dg0yt** [comment]
flatbuffer_base.h in gdal has: 
~~~
#define FLATBUFFERS_VERSION_MAJOR 2
#define FLATBUFFERS_VERSION_MINOR 0
#define FLATBUFFERS_VERSION_REVISION 6
~~~
Upstream is using YY.M.D now. Flatbuffers in vcpkg is now at
~~~
#define FLATBUFFERS_VERSION_MAJOR 23
#define FLATBUFFERS_VERSION_MINOR 5
#define FLATBUFFERS_VERSION_REVISION 9
~~~
These version macro are checked (at least) in feature_generated.h.

**Comment by rouault** [comment]
> These version macro are checked (at least) in feature_generated.h.

not sure to understand if there is an actual problem linked to that observation ? Is vcpkg *not* using the vendored flatbuffers of GDAL but the one it packages ? If so, that's definitely not a supported combination, given that apparently feature_generated.h must be built against the same exact flatbuffers version than the FlatBuffers compiler that generated it. Basically it looks like the flatbuffers tech only works with a vendored copy (or requiring to regenerated the _generated.h file by the build process itself)

**Comment by dg0yt** [comment]
Well, I did a naive attempt to replace the vendored copy in order to fix the problem. AFAIU the frozen copy is neither namespaced nor fully inlined - how does it affect users which need GDAL and a more recent flatbuffers?

How are these files updated/regenerated, if not encoded in CMake targets? 
Do I need to start from
https://github.com/flatgeobuf/flatgeobuf/tree/master/src/fbs ?

https://github.com/flatgeobuf/flatgeobuf/blob/master/src/cpp/feature_generated.h#L11-L13 is already at
~~~
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 3 &&
              FLATBUFFERS_VERSION_REVISION == 3,
~~~

**Comment by rouault** [comment]
> Well, I did a naive attempt to replace the vendored copy in order to fix the problem. AFAIU the frozen copy is neither namespaced nor fully inlined - how does it affect users which need GDAL and a more recent flatbuffers?
> 
> How are these files updated/regenerated, if not encoded in CMake targets?

CC @bjornharrtell who should be best placed to answer this

It would indeed been more prudent to namespace the GDAL copy, as was done in MapServer

**Comment by bjornharrtell** [comment]
Code generated by flatbuffers is strictly bound to the flatbuffers version. I guess one could argue that generation should be part of build to make it less version strict but that would increase build complexity significantly. Namespacing is perhaps also a valid solution. I have no strong opinions here.
