### ISSUE TITLE
Doc: ESRIJSON Example Fails

### ISSUE THREAD

**Issue by micahcochran** [OSGeo/gdal#7901]
## Expected behavior and actual behavior.

ESRIJSON lists an example using `ogrinfo`:
```bash
ogrinfo -ro -al "http://sampleserver3.arcgisonline.com/ArcGIS/rest/services/Hydrography/Watershed173811/FeatureServer/0/query?where=objectid+%3D+objectid&outfields=*&f=json"
```
When ran it results in the following:
```
ERROR 1: Could not resolve host: sampleserver3.arcgisonline.com
FAILURE:
Unable to open datasource `http://sampleserver3.arcgisonline.com/ArcGIS/rest/services/Hydrography/Watershed173811/FeatureServer/0/query?where=objectid+%3D+objectid&outfields=*&f=json' with the following drivers.
  -> FITS
  -> PCIDSK
  -> netCDF
  -> PDS4
  -> VICAR
[...snip...]
```

This seems to be that server is not online.  I found this post on ESRI forums that "sampleserver1 thru 5 machines were all retired once earlier this year, but some came back to life for a few months. They are going away for good now." [Source](https://community.esri.com/t5/arcgis-javascript-maps-sdk-questions/sampleserver1-arcgisonline-com-returning-503s/m-p/1200099#M78201)

## Steps to reproduce the problem.

Run the example from the documentation for ESRIJSON.

## Operating system

* Linux Mint 21.1
* and a Virtual Machine: Debian Unstable 

## GDAL version and provenance

* 3.4.1 from Ubuntu (Linux Mint)
* and a Virtual Machine: GDAL 3.6.2, released 2023/01/02

## Potential Fix

I found this server up https://sampleserver6.arcgisonline.com/arcgis/rest/

Here is a query that I could get to work:
```bash
ogrinfo -ro -al "https://sampleserver6.arcgisonline.com/arcgis/rest/services/PoolPermits/FeatureServer/0/query?where=&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&distance=&units=esriSRUnit_Foot&relationParam=&outFields=&returnGeometry=true&maxAllowableOffset=&geometryPrecision=&outSR=&havingClause=&gdbVersion=&historicMoment=&returnDistinctValues=false&returnIdsOnly=false&returnCountOnly=false&returnExtentOnly=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&returnZ=false&returnM=false&multipatchOption=xyFootprint&resultOffset=&resultRecordCount=10&returnTrueCurves=false&returnExceededLimitFeatures=false&quantizationParameters=&returnCentroid=false&timeReferenceUnknownClient=false&sqlFormat=none&resultType=&featureEncoding=esriDefault&datumTransformation=&f=pjson"
```

I limited the results to 10 records.  The fix seems to be just to replace that line in the documentation with this one.  Any thoughts?

**Comment by rouault** [comment]
> The fix seems to be just to replace that line in the documentation with this one. Any thoughts?

sounds good.

You may use https://github.com/OSGeo/gdal/edit/master/doc/source/drivers/vector/esrijson.rst to propose that change
