### ISSUE TITLE
Cannot Download gdal Package

### ISSUE THREAD

**Issue by sgdrewry** [OSGeo/gdal#7902]
## Expected behavior and actual behavior.

I expected to be able to download gdal, but it returns an error message
instead: 
Warning in install.packages :
  package ‘gdal’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages

## Steps to reproduce the problem.

install.packages("gdal")
I have set repositories to all of the below:
1: + CRAN
2: + BioC software
3: + BioC annotation
4: + BioC experiment
5: + CRAN (extras)
6: + R-Forge
7: + rforge.net

I also downloaded gdal-3.7.0.tar.gz and attempted to install from the package archive file, but that produced this error: 
ERROR: cannot extract package from ...

## Operating system

MacOS R Studio 2023.03.0+386 AND MacOS R Studio 2023.03.1+446 (I tried it on both).

## GDAL version and provenance

[gdal-3.7.0.tar.gz](https://download.osgeo.org/gdal/CURRENT/gdal-3.7.0.tar.gz)

I am sure this is a simple issue, but I have been stuck on it for days. Any help is greatly appreciated. I need to download gdal to be able to use other packages.

**Comment by rouault** [comment]
you may try to use one of the binary distributions listed at https://gdal.org/download.html#binaries , but you may also find help with the R community itself (cf https://cran.r-project.org/web/packages/gdalraster/index.html). This project is only about the non-R specific parts
