### ISSUE TITLE
gdalwarp creates unnecessary no-data border

### ISSUE THREAD

**Issue by berniejenny** [OSGeo/gdal#7905]
When transforming the attached GeoTIFF image from EPSG:4326 ("geographic" WGS84) to EPSG:3857 ("Web Mercator"), gdalwarp adds a border with no-data values. 

## Expected behavior
The output image should not contain border columns or border rows with all values equal to no-data.

## Actual behavior
In the attached example, the top row, bottom row and the right column contain only no-data values (i.e., zero for this unsigned byte image).
The same behavior occurs with (a) float raster data, (b) -wo SOURCE_EXTRA=50, (c) -et=0 or (d) when -tap is omitted. The location (left, right, top or bottom border) of the no-data border varies with parameters. The same behavior also occurs in C with [GDALWarp](https://gdal.org/api/gdal_utils.html#_CPPv48GDALWarpPKc12GDALDatasetHiP12GDALDatasetHPK18GDALWarpAppOptionsPi)

## Steps to reproduce the problem.
./gdalwarp -t_srs EPSG:3857 -tr 30 30 -tap -r cubic EPSG-4326.tif out.tif
Note the source image has a resolution of 3 arc seconds, which is about three times the target resolution of 30 m.

## Operating system
macOS 13.4, M1

## GDAL version
GDAL 3.7.0, PROJ 9.2.1

[EPSG-4326.tif.zip](https://github.com/OSGeo/gdal/files/11663556/EPSG-4326.tif.zip)

**Comment by jratike80** [comment]
At least the result from `gdalwarp -t_srs EPSG:3857 -tr 30 30 -tap -r cubic EPSG-4326.tif out.tif` is expected.
Target aligning places the pixels to match with the resolution. Therefore the upper left corner is placed at  ( 948390.000, 5861610.000).  Without `-tap` the top-left corner would be at ( 948395.678, 5861581.070). Placing top-left y one pixel more into south (Y=5861580) would cut 1.070 meters from the source data.

That `-tap` is increasing the extent is documented

> **-tap**
> 
> (target aligned pixels) align the coordinates of the extent of the output file to the values of the [-tr](https://gdal.org/programs/gdalwarp.html#cmdoption-gdalwarp-tr), such that the aligned extent includes the minimum extent. Alignment means that xmin / resx, ymin / resy, xmax / resx and ymax / resy are integer values.

<img width="268" alt="image" src="https://github.com/OSGeo/gdal/assets/1751612/a0eab4fb-b6fd-4d4f-97e4-083e81d4fcf2">

**Comment by jratike80** [comment]
The other way round, probably nodata rows and columns are usually harmless. At least I do not remember seeing other complaints since the introduction of `-tap` twelve years ago in GDAL 1.8 https://trac.osgeo.org/gdal/wiki/Release/1.8.0-News.

The original use case for `-tap` was to create seamless image mosaics from individually warped originals. The result may include rows of nodata pixels but in the rendering they can be made transparent. In image analysis it should be normal to discard nodata pixels. Maybe a seamless mosaic could be achieved also if the nodata rows and columns were removed afterwards. However, at least extending image to all directions to meet the next pixel boundary is easy to compute, document, and explain.

**Comment by rouault** [comment]
I've added a heuristics in https://github.com/OSGeo/gdal/pull/7911 to remove fully blank edge row.columns in the modes where it makes sense

**Comment by rouault** [comment]
> I believe that you are relatively sure that from adjacent originals the heuristic will not remove a row or column from the both warped images, even it should be removed only from one

hopefully it shouldn't (I wouldn't put my hand in the fire however). It uses the same criterion as the warping kernel to determine if a target pixel has a matching source pixel in the area of the source raster. So normally it should remove rows/columns that were going to be nodata only.
And for people who specify -te -tr or -te -ts, the heuristics doesn't trigger

**Comment by berniejenny** [comment]
Excellent! Thank you @rouault!
