### ISSUE TITLE
gdal_polygonize - add an overwrite option

### ISSUE THREAD

**Issue by Brent-Edwards** [OSGeo/gdal#7913]
## Expected behavior and actual behavior.

gdal_polygonize does not have a clearly documented overwrite option. This results in strange behavior when the outputs already exist.

## Steps to reproduce the problem.

call gdal_polygonize -8 "input1.tif" -f "ESRI Shapefile" "my_output_filename1.shp"
call gdal_polygonize -8 "input2.tif" -f "ESRI Shapefile" "my_output_filename2.shp"

On first run, my_output_filename1.shp and my_output_filename2.shp are written. 

On second run, my_output_filename2.shp and my_output_filename2 are not overwritten, out.shp is written consecutively (once for each run).

Outputs must be deleted before rerunning to avoid this behavior. It would be really useful to have an explicit "-overwrite" option.

## Operating system

Windows 10 Version 2009 64bit

## GDAL version and provenance

3.6.3

**Comment by jratike80** [comment]
> gdal_polygonize does not have a clearly documented overwrite option. 

I believe that gdal_polygonize does not have an overwrite option at all. The documentation says:

> The utility will create the output vector datasource if it does not already exist, defaulting to GML format.

Utility must not overwrite if users do not request it or they could accidentally delete their data. I can't imagine any negative effects if there was a similar -overwrite switch than in ogr2ogr  https://gdal.org/programs/ogr2ogr.html#cmdoption-ogr2ogr-overwrite

**Comment by rouault** [comment]
implemented in https://github.com/OSGeo/gdal/pull/7917
