### ISSUE TITLE
Multi-threaded overview building gives errors

### ISSUE THREAD

**Issue by dugalh** [OSGeo/gdal#7921]
# Expected behavior and actual behavior.

Building overviews with `GDAL_NUM_THREADS=ALL_CPUS` generates errors:

```
ERROR 1: _TIFFVSetField:/vsimem/decompress_0000023A0697E7E8.tif: Bad value 2 for "ExtraSamples" tag
ERROR 1: _TIFFVSetField:/vsimem/decompress_0000023A0697E810.tif: Bad value 2 for "ExtraSamples" tag
...
```
The overviews seem to get built successfully, but I don't expect the errors.

## Steps to reproduce the problem.

Using the image file [ngi_rgb_byte_1.tif]( https://raw.githubusercontent.com/leftfield-geospatial/homonim/main/tests/data/source/ngi_rgb_byte_1.tif), the command:
```
gdaladdo --config GDAL_NUM_THREADS ALL_CPUS ngi_rgb_byte_1.tif 2 4
```
will reproduce the problem.  There are no errors with `--config GDAL_NUM_THREADS 1`.

## Operating system

Ubuntu 22.04.2

## GDAL version and provenance

conda-forge gdal version 3.7.0

**Comment by jratike80** [comment]
Must have something to do with the source image structure. It has two unspecified bands. That is not an error, just trying to find out what happens. Gdalinfo shows them this way

```
Band 1 Block=256x256 Type=Byte, ColorInterp=Gray
  NoData Value=0
Band 2 Block=256x256 Type=Byte, ColorInterp=Undefined
  NoData Value=0
Band 3 Block=256x256 Type=Byte, ColorInterp=Undefined
  NoData Value=0
```
and tiffinfo:

 ```
Photometric Interpretation: min-is-black
Extra Samples: 2<unspecified, unspecified>
 Samples/Pixel: 3
```

This is probably off-topic but I tried to edit the tiff a bit with gdal_edit and change the color interpretation into R-G-B but the error remained. I wonder if there is a bug in gdal_edit. After my edits the interpretation of the whole image is RGB so there are no more extra samples. However, the TIFF tag still claims that there are.

```
Photometric Interpretation: RGB color
Extra Samples: 2<unspecified, unspecified>
Samples/Pixel: 3
```

**Comment by rouault** [comment]
Fix in https://github.com/OSGeo/gdal/pull/7922

**Comment by rouault** [comment]
Although annoying, this particular error message can be safely ignored here.

**Comment by dugalh** [comment]
OK.  Thank you.  I tried `--config CPL_LOG_ERRORS OFF`, but it still reports the errors.
