### ISSUE TITLE
Desired Java api changes

### ISSUE THREAD

**Issue by bdezonia** [OSGeo/gdal#7933]
Hi, I am going to work on the Java SWIG bindings to better support MDArrays in the Java API. I would ask my question on the mailing list but I have code snippets that are hard to share via email. Anyhow I am going to line out some proposed test code that will drive my development process. Please comment on if you think this API is sensible. I drew some inspiration from the python tests. Any comments appreciated. Once I get feedback I'll start making the changes to the Java API to make it happen.

`
	private static void testMDArrayStuff() {

		Driver driver = gdal.GetDriverByName("MEM");

		Dataset dataset = driver.CreateMultiDimensional("mdstuff");
        
		Group rg = dataset.GetRootGroup();

		ExtendedDataType dt = ExtendedDataType.Create(gdalconst.GDT_UInt16);

		long[] dims = new long[]{10,6,2,7};

		BigInteger[] dimsB = new BigInteger[dims.length];
		
		for (int i = 0; i < dims.length; i++) {
			
			dimsB[i] = BigInteger.valueOf(dims[i]);
		}
		
		Vector<Dimension> inDims = new Vector<>();
		
		for (int i = 0; i < dims.length; i++) {
			
			Dimension d =
				
				rg.CreateDimension("name"+i, "type"+i, "direction"+i, dimsB[i]);
			
			inDims.add(d);
		}
		
		MDArray mdarray = rg.CreateMDArray("my_data", inDims, dt);
		
		Vector<Dimension> outDims = (Vector<Dimension>) mdarray.GetDimensions();
		
		if (outDims.size() != dims.length) {
			
			throw new RuntimeException("resulting dimension count "+outDims.size()+" does not equal input dim len "+dims.length);
		}
		
		for (int i = 0; i < dims.length; i++) {
			
			Dimension d = outDims.get(i);
			
			if (d.GetSize().compareTo(dimsB[i]) != 0) {

				throw new RuntimeException("resulting dimension "+i+" has size"+ d.GetSize()+" but should equal "+dims[i]);
			}
			
			if (!d.GetName().equals("name"+i)) {

				throw new RuntimeException("resulting dimension name "+d.GetName()+"does not match name"+i);
			}
			
			if (!d.GetFieldType().equals("fieldtype"+i)) {

				throw new RuntimeException("resulting dimension type "+d.GetFieldType()+"does not match fieldtype"+i);
			}
			
			if (!d.GetDirection().equals("direction"+i)) {

				throw new RuntimeException("resulting dimension direction "+d.GetDirection()+"does not match direction"+i);
			}
		}
	}
`

**Comment by bdezonia** [comment]
I guess I should also try to support MDArray Read() and Write methods in the API.

**Comment by rouault** [comment]
This looks good. I don't think the complication of using BigInteger for the dimension size is strictly needed. It is unlikely a dimension would reach signed_int64::max() despite the type allowing up to unsigned_int64::max(), so a Java long should be just fine for all practical purposes.

Why using Dimension::GetFieldType() instead of Dimension::GetType() ?

And yes, MDArray without the Read() and Write() methods is pretty useless

**Comment by bdezonia** [comment]
I guess I was using BigInteger for dimensions because Dimension::GetSize() in the Java API currently returns a BigInteger. I was trying to match that. Would it be better for Dimension to return longs instead of BigIntegers in the Java API too? If not does this change your assessment about using longs?

I was using GetFieldType() because in the Java API Dimension::GetType() does not exist. I thought I was just making a mistake using GetType() and used the existing GetFieldType() instead. Do I need to expose GetType() in Dimension somehow?

Re: Read() and Write() I will not use BigIntegers in any of the parameters either unless my earlier questions make you change your mind on that topic.

**Comment by rouault** [comment]
> I guess I was using BigInteger for dimensions because Dimension::GetSize() in the Java API currently returns a BigInteger

oh, I see that. I assume SWIG must automatically maps GUInt64/unsigned long long to a BigInteger. 

> If not does this change your assessment about using longs?

well, I've the feeling that BigInteger makes the API more complicated to use that it needs to be. So perhaps override typemaps that map GUInt64 to Java long could be better, assuming that's doable

> I was using GetFieldType() because in the Java API Dimension::GetType() does not exist.

ah I believe I know what happens : swig/include/java/ogr_java.i has a "%rename (GetFieldType) GetType;", but that one was meant to be use only for the GetFieldType() methods defined for OGRFeatureShadow in swig/include/ogr.i .
The multidimensional API was a much later API and it hasn't been noticed that the override of ogr_java.i would apply here. So perhaps the fix is to move the %rename from ogr_java.i to ogr.i .
As you can see in https://www.swig.org/Doc3.0/SWIGDocumentation.html#SWIG_rename_ignore, %rename affects everything after it has been found, so hopefully having it only in ogr.i will not affect Multidimensional.i, but I'm not totally sure. If that doesn't work, it means that something more cumbersome should be done in ogr.i, like

```
#ifndef SWIGJAVA
  OGRFieldType GetFieldType(int id) {
#else
  OGRFieldType GetType(int id) {
#endif
```

**Comment by bdezonia** [comment]
Ok. So I will try to switch BigInteger dimensions to long dimensions everywhere in the java api (except where it makes sense to keep it like GetTotalElementCount() etc.). I already figured out how to reenable GetType() for Dimensions. There are a few things I will need to fix/expose to get everything working. My current test code is listed below. Any feedback appreciated.

`
	private static void testMDArrayStuff() {

		Driver driver = gdal.GetDriverByName("MEM");

		Dataset dataset = driver.CreateMultiDimensional("mdstuff");
        
		Group rg = dataset.GetRootGroup();

		ExtendedDataType dt = ExtendedDataType.Create(gdalconst.GDT_Int16);

		long[] dims = new long[]{10,6,2,7};

		Vector<Dimension> inDims = new Vector<>();
		
		for (int i = 0; i < dims.length; i++) {
			
			Dimension d =
				
				rg.CreateDimension("name"+i, "type"+i, "direction"+i, dims[i]);
			
			inDims.add(d);
		}
		
		MDArray mdarray = rg.CreateMDArray("my_data", inDims, dt);
		
		Vector<Dimension> outDims = (Vector<Dimension>) mdarray.GetDimensions();
		
		if (outDims.size() != dims.length) {
			
			throw new RuntimeException("resulting dimension count "+outDims.size()+" does not equal input dim len "+dims.length);
		}
		
		for (int i = 0; i < dims.length; i++) {
			
			Dimension d = outDims.get(i);
			
			if (d.GetSize() != dims[i]) {

				throw new RuntimeException("resulting dimension "+i+" has size"+ d.GetSize()+" but should equal "+dims[i]);
			}
			
			if (!d.GetName().equals("name"+i)) {

				throw new RuntimeException("resulting dimension name "+d.GetName()+"does not match name"+i);
			}
			
			if (!d.GetType().equals("type"+i)) {

				throw new RuntimeException("resulting dimension type "+d.GetType()+"does not match fieldtype"+i);
			}
			
			if (!d.GetDirection().equals("direction"+i)) {

				throw new RuntimeException("resulting dimension direction "+d.GetDirection()+"does not match direction"+i);
			}
		}

		long xSize = dims[0];
		
		long ySize = dims[1];
		
		long zSize = dims[2];
		
		long timePoints = dims[3];
		
		int planeSize = (int) (xSize * ySize);
		
		short[] planeZeros = new short[planeSize];

		short[] planeW = new short[planeSize];

		short[] planeR = new short[planeSize];

		long[] starts = new long[dims.length];

		long[] counts = new long[dims.length];

		long[] steps = new long[dims.length];

		long[] strides = new long[dims.length];

		// read/write XY planes one at a time through whole mdarray
		
		for (int t = 0; t < timePoints; t++) {
			
			starts[3] = t;
			counts[3] = 1;
			steps[3] = 1;  // right?
			strides[3] = 1;  // right?

			for (int z = 0; z < zSize; z++) {
			
				starts[2] = z;
				counts[2] = 1;
				steps[2] = 1;  // right?
				strides[2] = 1;  // right?

				starts[1] = 0;
				counts[1] = ySize;
				steps[1] = 1;  // right?
				strides[1] = 1;  // right?

				starts[0] = 0;
				counts[0] = xSize;
				steps[0] = 1;  // right?
				strides[0] = 1;  // right?

				int i = 0;
				
				for (int y = 0; y < ySize; y++) {
				
					for (int x = 0; x < xSize; x++) {
					
						short val = (short) ((t+1)*(z+1)*(y+1)*(x+1));
						
						planeW[i++] = val;
					}
				}

				if (Arrays.equals(planeW, planeZeros)) {
					
					throw new RuntimeException("write plane is zero and shouldn't be");
				}
				
				if (!Arrays.equals(planeR, planeZeros)) {
					
					throw new RuntimeException("read plane is not zero and should be");
				}

				if (!mdarray.Write(starts, counts, steps, strides, planeW)) {

					throw new RuntimeException("could not write mdarray data");
				}
				
				if (!mdarray.Read(starts, counts, steps, strides, planeR)) {

					throw new RuntimeException("could not read mdarray data");
				}
				
				if (!Arrays.equals(planeW, planeR)) {
					
					throw new RuntimeException("written data does not match read data");
				}
				
				Arrays.fill(planeW, (short)0);
				
				Arrays.fill(planeR, (short)0);
			}			
		}
	}

`

**Comment by bdezonia** [comment]
Okay, so I have been spinning my wheels for a long time trying to support MDArray Read() and Write(). The key trick is that in C++ the call's last parameter (or one of the last) is a void pointer. I have mocked up code about as far as I can take it without some advice. I am going to point out where I made changes on my fork.

One thing I did was sort of copy how RasterIO works in the java swig code in gdal_jave.i. Relevant code starts here:

https://github.com/bdezonia/gdal/blob/307a72161a6b3ba13641d4be2fa58bab03ad92f5/swig/include/java/gdal_java.i#L147

Here are typemaps I tried to facilitate this approach:

https://github.com/bdezonia/gdal/blob/307a72161a6b3ba13641d4be2fa58bab03ad92f5/swig/include/java/typemaps_java.i#L2114

Now the problem I get is that when building my MDArray Read()/Write() the signatures can't map a buffer (say a short[]) to a void pointer to the buffer contents. And I can't figure out how to accomplish this. I get 12 compile errors: two each for the six primitive array types I am trying to support. Two of each because there is a read version and a write version.

I googled this topic a decent amount and am led to believe this might be a tricky problem. I am adding a link here that hopefully doesn't confuse the subject:

https://stackoverflow.com/questions/11005123/how-do-i-convert-to-type-swigtype-p-void-in-swig-generated-java-bindings

Anyhow what do people think of my approach? It seems like it should work but no set of casts/typemaps seems to bring about success.

**Comment by bdezonia** [comment]
I forgot to include the error message (12 similar ones). In this one buffer is a double[].

[javac] /home/bdz/dev/gdal/build/swig/java/org/gdal/gdal/MDArray.java:395: error: incompatible types: double[] cannot be converted to SWIGTYPE_p_GInt64
[javac] 		return MDArrayWrite(startIdxes, counts, arraySteps, bufferStrides, typeNum, buffer);

**Comment by rouault** [comment]
> One thing I did was sort of copy how RasterIO works in the java swig code in gdal_java.i. Relevant code starts here:
> 
> https://github.com/bdezonia/gdal/blob/307a72161a6b3ba13641d4be2fa58bab03ad92f5/swig/include/java/gdal_java.i#L147

I don't believe your current approach can work.
You should rather take strong inspiration on the Band.ReadRaster() approach (lines 418-457 in gdal_java.i in master), that is to define a *C* function MDArrayRead() (and similarly a MDArrayWrite())  in a ``%{`` ``%}`` block, outside of ``%extend GDALMDArrayHS``, that has a ``void *regularArrayOut, long nRegularArraySizeOut`` argument, and all the other argument expected by MDArrayRead/MDArrayWrite(). That way you will not need any new typemap for the buffer.

and within ``%extend GDALMDArrayHS {``, have Read()/Write() methods, similar to  what is done for GDALRasterBandShadow::ReadRaster(), between lines 477 and 499 with the DEFINE_READ_RASTER() macro instanciated with all the data type of interest, that call MDArrayRead()
The checks about the consistency between the Java array size and what is expected can be done either in the MDArrayRead() C function, or probably even simpler just let GDALMDArrayRead()/Write() do itself, as it can do those checks if you provide the last 2 arguments: pDstBufferAllocStart (to be the same as pDstBuffer) and nDstBufferAllocSize (to be equal to nRegularArraySizeOut * sizeof_ctype)

**Comment by bdezonia** [comment]
Geez. I wish I had taken this as my original approach. My old approach took days and days of debugging. Your approach took me an hour or two to get working! Thanks. Work now continues on my branch.

**Comment by bdezonia** [comment]
So I've made a lot of progress towards improved MDArray support for the java api. I'm getting closer and closer to running my test code. At this point I have one remaining error message and it is related to type maps again. I am pretty stuck and could use another set of eyes to tell me what I may be missing.

I am currently trying to get this method working:

https://github.com/bdezonia/gdal/blob/ee661fd720a416b7d75eb858d192f7825e5c95ac/swig/include/java/gdal_java.i#L381

If you follow its chain of declarations backwards you can see it is not doing much.

The problem is complicated because the C api is not java friendly. I defined a struct to help the code work which I am at the moment placing here:

https://github.com/bdezonia/gdal/blob/ee661fd720a416b7d75eb858d192f7825e5c95ac/swig/include/gdal.i#L96

I am getting this error message during compilation:

compile:
    [javac] Compiling 86 source files to /home/bdz/dev/gdal/build/swig/java/build/classes
    [javac] warning: [options] bootstrap class path not set in conjunction with -source 7
    [javac] /home/bdz/dev/gdal/build/swig/java/org/gdal/gdal/MDArray.java:49: error: incompatible types: SWIGTYPE_p_GDAL_JAVA_DIMS cannot be converted to Vector
    [javac] 		Vector vec = FindGdalDims();
    [javac] 		                         ^
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 1 error
    [javac] 1 warning

The typemap that I think should solve this problem is here but it does not seem to be getting wired up:

https://github.com/bdezonia/gdal/blob/ee661fd720a416b7d75eb858d192f7825e5c95ac/swig/include/java/typemaps_java.i#L2235

Anyhow is my approach sensible? It seems I am very close to fully compiling and able to run my test code.

**Comment by bdezonia** [comment]
I just thought of a simple but not great way to solve this. Make the java code pass in the MDArrayH as a long, some dummy values (like a bunch of short[]'s), and maybe a Vector<Dimension>. The dummies are there so the signature can not be confused with anything else. The typemap(out) can used the MDArrayH to compute the dimension info it needs and can either return a Vector of Dimensions or modify the Vector that was passed in (if I go that route). I will try doing this later tonight.

**Comment by rouault** [comment]
Is the issue with the GetDimensions() method (that is defined for python only now) ?

If so, you should implement a ``GDALDimensionHS*** pdims, size_t* pnCount" typemap``, and take inspiration from a mix of the Python one in swig/include/python/typemaps_python.i, as well as the Java one of ``Typemap argout of GDAL_GCP* used in Dataset::GetGCPs( )`` that is presumably the closed to what you want. You would instanciate Java Dimension object from a <init> method that takes a long containing the C pointer. That's admitedly a bit harder.

Another option would be that you implement 2 SWIG methods a GetDimensionCount() and a GetDimension(index). That woud likely save the need to write typemaps. And potentially have a pure Java helper that would combine them to return a Vector<Dimension>

**Comment by bdezonia** [comment]
Thanks. I'll try the second option. That was what I was scouring the C API for to no avail. But you're right, I think I can fake it in Java and local C and forego typemaps almost completely.

**Comment by bdezonia** [comment]
Okay, I still can't get things working. I am so overtired that I'm not thinking straight. I am going to add some code snippets here and someone can maybe tell me what I am doing wrong.

in typemaps_java.i

`/*
  From C:  GDALDimensionH*
  To Java: Dimension
*/
%typemap(out) (GDALDimensionH*)
{
	const jclass dimClass = jenv->FindClass("org/gdal/gdal/Dimension");
	const jmethodID dctor = jenv->GetMethodID(dimClass, "<init>",
									"(Jjava/lang/Long;Zjava/lang/Boolean;)V");

	$result = jenv->NewObject(dimClass, dctor, *$1, false);
}
`

In gdal_java.i in static block:

`
  %{

    /* NOTHING */

  %}
`

In gdal_java.i in extend block:

`%extend GDALMDArrayHS {

	GDALDimensionH GetDimension(size_t index) {
	
		size_t dimCount;
		
		GDALDimensionH* dims = GDALMDArrayGetDimensions(self, &dimCount);

		if (index < 0 || index >= dimCount) {
		
			free((void*) dims);
		
			return (GDALDimensionH) NULL;
		}
		else {
		
			free((void*) dims);

			return dims[index];
		}
	}
	
} /* extend */
`

In gdal_java.i in javacode block:

`%typemap(javacode) GDALMDArrayHS %{

    Vector<Dimension> GetDimensions() {

		Vector vec = new Vector();
		
		long numDims = GetDimensionCount();
		
		for (long i = 0; i < numDims; i++) {

			Dimension dim = GetDimension(i);
			
			vec.add(dim);
		}
		
		return (Vector<Dimension>) vec;
    }
%}
`

The compilation error I get is:

compile:
    [javac] Compiling 87 source files to /home/bdz/dev/gdal/build/swig/java/build/classes
    [javac] warning: [options] bootstrap class path not set in conjunction with -source 7
    [javac] /home/bdz/dev/gdal/build/swig/java/org/gdal/gdal/MDArray.java:55: error: incompatible types: SWIGTYPE_p_GDALDimensionH cannot be converted to Dimension
    [javac] 			Dimension dim = GetDimension(i);
    [javac] 			                            ^
 
Can you tell me what I might be doing wrong? Note that if I remove all the code from typemaps_java.i I get the same error message.

**Comment by bdezonia** [comment]
I see where the C code for GetDimension(long index) could return a pointer to a dim handle instead of a dim handle itself but then it becomes a problem for memory management to pass a pointer to a handle that lives in a menory block that you have already freed.

**Comment by bdezonia** [comment]
And adding this at the bootm of the typemap code shows no improvment;

`

%typemap(jni) (GDALDimensionH*) "jobject"
%typemap(jtype) (GDALDimensionH*) "org.gdal.gdal.Dimension"
%typemap(jstype) (GDALDimensionH*) "org.gdal.gdal.Dimension"
%typemap(javain) (GDALDimensionH*) "$javainput"
%typemap(javaout) (GDALDimensionH*) {
    return $jnicall;
  }

`

**Comment by bdezonia** [comment]
OK. Thanks for letting me sleep upon it. The fix was to make the static block have something in it and the extend code to do a trivial call to it.

**Comment by bdezonia** [comment]
Tangent question: is there a reason some of the Java api returns Vector<Object> in a number of places. A more natural and java developer friendly approach would be to return List<Dimension> or Dimension[] instead of a plain Vector full of Objects? In this example I am picturing a method that returns Dimensions. Would you be open to making changes to the api? Or implementing new methods using those alternate ways? For instance Group::CreateMDArray() could take Dimension[] input and MDArray::GetDimensions() could return a Dimension[]. How important is backward compatibility? Or maybe having two signatures for some methods so people could use more natural approaches and the devs could deprecate the original ways if they so decide.

**Comment by rouault** [comment]
> Tangent question: is there a reason some of the Java api returns Vector<Object> in a number of places.

The Java bindings likely date back to a time was Vector was still the norm, and List likely not existent or too new.
I'd say that for the mutidimensional API, given how broken it was for Java at that point and likely unused, it would be fine to use plain arrays or List

**Comment by bdezonia** [comment]
Thanks. I have taken that approach. Here is my update. I have made all my changes. The api is complete. The code compiles. The javadoc looks great. The test code is written. And of course, running the test code segfaults. Sigh. Hopefully I won't be debugging this forever.

**Comment by bdezonia** [comment]
I'm not sure how well I can debug this. Here is the beginning of the dump. Notice it is in libjvm.

# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f46f4efa495, pid=626904, tid=626905
#
# JRE version: OpenJDK Runtime Environment (11.0.19+7) (build 11.0.19+7-post-Ubuntu-0ubuntu122.04.1)
# Java VM: OpenJDK 64-Bit Server VM (11.0.19+7-post-Ubuntu-0ubuntu122.04.1, mixed mode, sharing, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# V  [libjvm.so+0x8fa495]  jni_NewObjectV+0xb5

And scouring the dump file I only find this clue:

Internal exceptions (1 events):
Event: 0.089 Thread 0x00007f46f0015800 Exception <a 'java/lang/NoSuchMethodError'{0x000000062ea21c10}: <init>> (0x000000062ea21c10) thrown at [./src/hotspot/share/prims/jni.cpp, line 1336]

The reason I said I'm not sure how well I can debug this is because it is failing in libjvm and there is some flakiness to my java as sometimes, in Eclipse, when I do code completion Eclipse immediately terminates and the terminal window has a dump in it complaining on how some JNI method failed. You can see I am using OpenJDK 11.0.19+7.

Can you advise as to the possibility my code is the culprit and the libjvm hint is a phantom?

I am likely creating an MDArray when the code crashes. If MDArray is just an interface (is that so?) does it not have an "<init>" method?

**Comment by bdezonia** [comment]
Sorry for the noise. I found the problem. Now debugging test results.

**Comment by bdezonia** [comment]
I have everything working. I have opened a PR:

https://github.com/OSGeo/gdal/pull/8048
