### ISSUE TITLE
Feature Request [GML]: Make "Use geometry in boundedBy element" an open option 

### ISSUE THREAD

**Issue by pathmapper** [OSGeo/gdal#7947]
What was the intention for the change in https://github.com/OSGeo/gdal/pull/7133?

If it doesn't conflict with the original intention, maybe make it an open option with `default = false`?

Came across this because there is a need to adapt an XPlanung QGIS plugin to restore the original behaviour, if this change stays like it is currently (with XPlanung-schema it happens often that there is a feature with bbox but without geoemtry).

Also, currently there might be confusion, e.g. when you drag'n drop a GML like the [test data](https://github.com/OSGeo/gdal/files/11723965/test_data.zip) from #7925 in QGIS, the import dialog shows a polygon feature for `BP_Bereich` without notifying the user that this is the bbox and not the actual feature geometry (or that the layer has no feature with geometry).

<img src="https://github.com/OSGeo/gdal/assets/20856381/3154ec06-3abb-4e2a-aa7c-f5256f26e969" width="500px">

**Comment by rouault** [comment]
> What was the intention for the change in #7133?

There are some data models like https://github.com/rouault/gdal/blob/a35c3ab224f55dce7af060a1d1b7279fec24dbf8/autotest/ogr/data/gml/only_boundedby.gml which is a simplified version of some Ordnance Survey files where getting the bbox as a geometry was desirable

> If it doesn't conflict with the original intention, maybe make it an open option with default = false?

I must check with the user who requested the behaviour of #7133

**Comment by rouault** [comment]
ok, so the user confirmed a "-oo USE_BBOX=YES" would work for him
