### ISSUE TITLE
gdal_grid shifts data with invdist and max_points

### ISSUE THREAD

**Issue by rhijmans** [OSGeo/gdal#7957]
gdal_grid shifts raster data southwards when using the inverse distance with a power algo and the max_points option

This was reported (with images) for R/terra here: https://github.com/rspatial/terra/issues/1186  (using GDAL 3.6.2)

I can reproduce the problem with the command line tool. 

This is OK: 

```
gdal_grid -a invdist:power=2.0:radius1=25:radius2=25 -zfield red -txe 0 101 -tye 0 77 -outsize 100 77 -of GTiff -ot Float64 -l pnts pnts.shp test1.tif
```

But this is not OK (setting `max_points=5`)

```
gdal_grid -a invdist:power=2.0:radius1=25:radius2=25:max_points=5 -zfield red -txe 0 101 -tye 0 77 -outsize 100 77 -of GTiff -ot Float64 -l pnts pnts.shp test2.tif"
```

[pnts.zip](https://github.com/OSGeo/gdal/files/11766115/pnts.zip)

**Comment by rouault** [comment]
This is probably due to a non-spatial uniform selection of the participating points. You could probably try with the min_points_per_quadrant option

**Comment by rhijmans** [comment]
Thanks and sorry for the noise.  I was using "invdist" (which uses the first max points found) whereas I wanted the behavour of "invdistnn" (which uses the max points that are nearest to the target cell center).
