### ISSUE TITLE
Bug in XYZ output

### ISSUE THREAD

**Issue by katleenwils** [OSGeo/gdal#797]
Hi all,

I am using the gdal_translate function to get an ascii grid output of a .mph file containing lon/lat coordinates and a height value (which can be both positive and negative) in the second band of a 2-band image. My command looks like this: gdal_translate -b 2 -of XYZ inputfile.mph outputfile.xyz

After some time, the file appears to be written correctly. However, I noticed that some areas of my grid are blank. Not even a zero value is attributed there, they are just missing from the file. And the ones that are missing are exactly the areas where I would expect non-zero values to occur; only like 11 of all (more than 1000000) locations with a non-zero height value are included in de xyz file. All areas where zero should appear are there. I tried with another format as well (.geo instead of .mph) and the issue is the same. Strangely, when I choose -of PNG, everything goes fine and is drawn as expected, meaning that the input file must be read correctly. In all cases, no error messages occur.

I don't know exactly what's going on, but this looks like a bug to me. If anyone has an idea on what might be going wrong, please let me know! I'm working with GDAL version 2.2.3 operating on a HPC cluster.

Thanks in advance.
Katleen

**Comment by rouault** [comment]
Please include an input dataset or a link to it that enables to reproduce the issue

**Comment by katleenwils** [comment]
As it's a rather large file, I'll include it via this link. I hope this will work.
https://www.dropbox.com/s/pvng05352gczqrd/GDAL_MPH.zip?dl=0

**Comment by rouault** [comment]
As the file is huge, this is inpractical to inspect. Can you point to a coordinate that would be missing ?

**Comment by katleenwils** [comment]
An example would be -74.215°, -43.24° or anything close to that. The area missing is really large.

**Comment by rouault** [comment]
I do see values in that area (this is a bit after 2.458 GB in the file)
```
-74.2184722221881401 -43.2401388889229921 -0.546578764915466309
-74.2181944444103578 -43.2401388889229921 -0.355228275060653687
-74.2179166666325898 -43.2401388889229921 -0.0399956367909908295
-74.2176388888548075 -43.2401388889229921 0.182754114270210266
-74.2173611110770253 -43.2401388889229921 0.227305024862289429
-74.217083333299243 -43.2401388889229921 0.205487385392189026
-74.216805555521475 -43.2401388889229921 0.185678973793983459
-74.2165277777436927 -43.2401388889229921 0.19707845151424408
-74.2162499999659104 -43.2401388889229921 0.235259562730789185
-74.2159722221881424 -43.2401388889229921 0.298700898885726929
-74.2156944444103601 -43.2401388889229921 0.399214208126068115
-74.2154166666325779 -43.2401388889229921 0.474455118179321289
-74.2151388888548098 -43.2401388889229921 0.490284115076065063
-74.2148611110770275 -43.2401388889229921 0.503431916236877441
-74.2145833332992453 -43.2401388889229921 0.559262633323669434
-74.214305555521463 -43.2401388889229921 0.63807755708694458
-74.214027777743695 -43.2401388889229921 0.743523538112640381
-74.2137499999659127 -43.2401388889229921 0.843911170959472656
-74.2134722221881304 -43.2401388889229921 0.959963381290435791
-74.2131944444103624 -43.2401388889229921 1.07780301570892334
-74.2129166666325801 -43.2401388889229921 1.20721852779388428
-74.2126388888547979 -43.2401388889229921 1.31672537326812744
-74.2123611110770298 -43.2401388889229921 1.39160609245300293
-74.2120833332992476 -43.2401388889229921 1.40098357200622559
-74.2118055555214653 -43.2401388889229921 1.37328505516052246
-74.211527777743683 -43.2401388889229921 1.39638698101043701
-74.211249999965915 -43.2401388889229921 1.53189373016357422
-74.2109722221881327 -43.2401388889229921 1.6770775318145752
-74.2106944444103505 -43.2401388889229921 1.76524472236633301
-74.2104166666325824 -43.2401388889229921 1.82327258586883545
-74.2101388888548001 -43.2401388889229921 1.86394250392913818
-74.2098611110770179 -43.2401388889229921 1.91135776042938232
-74.2095833332992498 -43.2401388889229921 1.99825370311737061
-74.2093055555214676 -43.2401388889229921 2.1089169979095459
-74.2090277777436853 -43.2401388889229921 2.21693134307861328
-74.208749999965903 -43.2401388889229921 2.29059290885925293
```

**Comment by katleenwils** [comment]
Hmmm ok, that looks correct indeed... Strange, in my case there's nothing there. So this was defenitly not a bug in the software but more likely an error related to my machine. Thank you for your time, sorry to have bothered you with this issue!

**Comment by rouault** [comment]
Perhaps some write unreliability on the filesystem off your HPC server as this XYZ output is pretty large ? (I would not recommend using XYZ as an output format as it is excessively verbose).
