### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [OSGeo/gdal#798]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [OGRDB2GeometryValidator](https://github.com/OSGeo/gdal/blob/98dfb4b4012c5ae4621e246e8eb393b3c05a3f48/gdal/ogr/ogrsf_frmts/db2/ogrdb2geometryvalidator.cpp#L51 "Destructor for OGRDB2GeometryValidator")
- [OGRMemLayer](https://github.com/OSGeo/gdal/blob/eb9ed3f968ef5198e8241c314c9e3184b7f5731c/gdal/ogr/ogrsf_frmts/mem/ogrmemlayer.cpp#L101 "Destructor for OGRMemLayer")
- [SDTSIndexedReader::ClearIndex](https://github.com/OSGeo/gdal/blob/eb9ed3f968ef5198e8241c314c9e3184b7f5731c/gdal/frmts/sdts/sdtsindexedreader.cpp#L85 "SDTSIndexedReader::ClearIndex function")

**Comment by rouault** [comment]
Please submit a PR to remove them

**Comment by elfring** [comment]
Do any related changes need to be achieved in the original software libraries?

**Comment by rouault** [comment]
> in the original software libraries?

Those piece of codes are the original software libraries.

**Comment by elfring** [comment]
Do you distinguish any software components which are bundled for the GDAL library?

**Comment by elfring** [comment]
How do you think about to apply [a corresponding update suggestion](https://github.com/OSGeo/gdal/blob/eb9ed3f968ef5198e8241c314c9e3184b7f5731c/gdal/frmts/grib/degrib/g2clib/getpoly.c#L72 "Update candidate: getpoly()") which could be generated by [the software “Coccinelle”](http://coccinelle.lip6.fr/ "Source code transformation with Coccinelle")?

```
@Remove_unnecessary_pointer_checks@
expression x;
@@
-if (\(x != 0 \| x != NULL\))
    free(x);
```

**Comment by rouault** [comment]
I'm fine with that

**Comment by elfring** [comment]
:crystal_ball: Would you dare to try any variants out for scripts in the semantic patch language?

**Comment by rouault** [comment]
Honestly I have enough on my plate to pursue that myself. Feel free to contribute if it is of interest for you

**Comment by rouault** [comment]
Closing. Such general issue is best covered by pull requests proposing fixes

**Comment by rouault** [comment]
https://trac.osgeo.org/gdal/wiki/rfc3_commiters mentions in "Relationship with other upstream projects imported in GDAL/OGR code base" a number of other libraries that are bundled in GDAL source tree

**Comment by elfring** [comment]
I guess that the mentioned software mixture can make it harder to achieve desired improvements in a convenient way when several components are similarly affected across the provided directories.
