### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [OSGeo/gdal#799]
Would you like to [wrap any pointer data members](https://github.com/OSGeo/gdal/blob/eb9ed3f968ef5198e8241c314c9e3184b7f5731c/gdal/frmts/msg/prologue.cpp#L173 "Update candidate: ImageDescriptionRecord class") with the class template “[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "Description for the usage of smart pointers")”?

**Comment by rouault** [comment]
This issue is too broad to be actionable. It might be useful to do it incrementally, and for parts that don't touch the API

**Comment by elfring** [comment]
I suggest to [achieve safe resource management](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#r11-avoid-calling-new-and-delete-explicitly "C++ core guideline “R.11: Avoid calling new and delete explicitly”") also for the involved software components.
