### ISSUE TITLE
band scale factor for translated GTiff raster not stored correctly

### ISSUE THREAD

**Issue by janzandr** [OSGeo/gdal#7997]
## Expected behavior and actual behavior.

I observed a problem with setting the band scale factor after translating a raster into a GTiff raster. The problem only occurs for the GTiff driver (ENVI or VRT is fine), when also setting metadata items. 

## Steps to reproduce the problem.

I was able to reduce the error on a minimalistic example.
```
from osgeo import gdal

# Given a raster with band scale factor.
filename = r'C:\test\raster1.tif'
driver: gdal.Driver = gdal.GetDriverByName('GTiff')
ds: gdal.Dataset = driver.Create(filename, 10, 10, 1, gdal.GDT_Byte)
rb = ds.GetRasterBand(1)
rb.SetScale(0.01)
del ds, rb

# When translating the raster, the band scale factor is correctly assigned to the new raster.
filename2 = r'C:\test\raster2.tif'
gdal.Translate(filename2, filename)
ds2: gdal.Dataset = gdal.Open(filename2)
rb2: gdal.Band = ds2.GetRasterBand(1)
assert rb2.GetScale() == 0.01

# After setting a metadata item, the scale factor is still correct.
rb2.SetMetadataItem('myKey', '42', '')
assert rb2.GetScale() == 0.01
del ds2, rb2

# But after re-opening the raster, the scale factor is missing (i.e. set to 1 -> no scaling).
ds3 = gdal.Open(filename2)
rb3 = ds3.GetRasterBand(1)
assert rb3.GetScale() == 0.01  # THIS WILL FAIL
```

1. Note that the code works, when we don't translate into GTiff (e.g. `filename2 = r'C:\test\raster2.vrt'`).
2. Note that the code works, when we comment out: `# rb2.SetMetadataItem('myKey', '42', '')`

## Operating system

Windows 10

## GDAL version and provenance

GDAL 3.7.0 from QGIS / OSGeo4W

QGIS version
3.28.7-Firenze
QGIS code revision
fedae0eb52
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.7.0
PROJ version
9.2.0
EPSG Registry database version
v10.082 (2023-02-06)
GEOS version
3.11.2-CAPI-1.17.2
SQLite version
3.41.1
PDAL version
2.5.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

**Comment by rouault** [comment]
fix in https://github.com/OSGeo/gdal/pull/7999
but i suspect you'd rather want to update raster2 in update mode to set the metadata item, with ``ds2: gdal.Dataset = gdal.Open(filename2, gdal.GA_Update)``. Without it, the metadata item goes into the external .aux.xml file

**Comment by janzandr** [comment]
Thank @rouault for the fix! 
And yes, I'm aware of internal and external metadata. I usually like to have the .aux.xml file, which I can open inside a text editor.
