### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [OSGeo/gdal#800]
Would you like to add more error handling for return values from functions like the following?
- [malloc](http://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [getpdstemplate](https://github.com/OSGeo/gdal/blob/eb9ed3f968ef5198e8241c314c9e3184b7f5731c/gdal/frmts/grib/degrib/g2clib/pdstemplates.c#L280)
- [pthread_mutex_init](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutex_init.html "Initialize a mutex.") ⇒ [CPLInitMutex](https://github.com/OSGeo/gdal/blob/0f654dda9faabf9d86a44293f0f89903a8e97dd7/gdal/port/cpl_multiproc.cpp#L1455)

**Comment by rouault** [comment]
I'm mostly indifferent for those particular cases where issues are quite unlikely to occur. Feel free to submit a PR if you want

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Checking more return values") a bit more.
Would you like to detect every error situation as early as possible?

Do [known source code analysis approaches](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for code analysis") point any more open issues out also for this software?

**Comment by rouault** [comment]
I know the principles. It is just that GDAL is a huge library and making everything right is an enormous task.  GDAL uses static code analysis (cppcheck, coverity scan, clang static analyzer)

**Comment by elfring** [comment]
It seems that the mentioned tools trigger challenges to view code analysis results for further considerations in a convenient way.

-----

* Are you interested to apply [aspect-oriented software development](https://aspectc.org/ "Software development with AspectC++?")?
* How do you think about to encapsulate error detection and corresponding exception handling as [a reusable aspect](https://en.wikipedia.org/wiki/Aspect_%28computer_programming%29 "Combination of a pointcut with advice") in this software?

**Comment by rouault** [comment]
I'd prefer not go into lengthy discussions about programmation theories and see more action

**Comment by elfring** [comment]
I would find it nice when higher level development tools can help more to improve the affected software.

**Comment by rouault** [comment]
Closing. Such general issue is best covered by pull requests proposing fixes

**Comment by rouault** [comment]
> May I propose AspectC++ advices as potential fixes (in pull requests)?

I've no idea what this is, but yes, start with something small to see if that's something reasonable for inclusion

**Comment by elfring** [comment]
>I've no idea what this is, …

I am still trying to clarify possible improvements based on aspect-oriented software development and related development methodologies (before increasing efforts into questionable pull requests).
