### ISSUE TITLE
S57 to GeoJSON conversation failure

### ISSUE THREAD

**Issue by nopAFix** [OSGeo/gdal#801]
## Expected behavior and actual behavior.

I wanted to convert .000 (S-57) to .geojson (GeoJSON) with ogr2ogr.exe, but it keeps failing no matter what. I tried using almost all of the available flags and option, tried using ogr2gui but it keeps saing and outputing the same thing. I also tried sending my .000 to [https://mygeodata.cloud/converter/s57-to-geojson](here), but it outputs everything just fine.

## Steps to reproduce the problem.

ogr2ogr -f GeoJSON output.json RU3M6US9.000
[oggrTest.zip](https://github.com/OSGeo/gdal/files/2230910/oggrTest.zip)

And it outputs:

ERROR 1: Layer 'ADMARE' does not already exist in the output dataset, and cannot be created by the output driver.
ERROR 1: Terminating translation prematurely after failed
translation of layer ADMARE (use -skipfailures to skip errors)
(Last line doesnt matter, because with -skipfailures it just skips every single layer)

## Operating system

Windows 10 x64

## GDAL version and provenance

gdal-2.3.1 binaries

**Comment by rouault** [comment]
GeoJSON only supports one layer per file. You have to run ogr2ogr on each layer
