### ISSUE TITLE
Issue with OGR_G_TRANSFORM 

### ISSUE THREAD

**Issue by raghulsekar** [OSGeo/gdal#8013]
I'm trying to do GDALWarp using gdalwarp_lib.cpp , in function TransformCutlineToSource   
OGRErr eErr = OGR_G_Transform( hMultiPolygon, (OGRCoordinateTransformationH) &oTransformer );
results in ERROR 1: Attempt to call CreateSimilar on a non-GTI2 transformer.
ERROR 1: Attempt to clone non-GTI2 transformer.
ERROR 1: Attempt to clone non-GTI2 transformer.

So i created my own OGRGeometry by passing points with respect to the height and width of the source file, eventhough there is no WarpOperation performed. As follows

 
    OGRGeometryH hLinearRing = OGR_G_CreateGeometry(wkbLinearRing);
    OGR_G_AddPoint_2D(hLinearRing, 0 , 0);
    OGR_G_AddPoint_2D(hLinearRing, 0, 500);
    OGR_G_AddPoint_2D(hLinearRing, 500, 500);
    OGR_G_AddPoint_2D(hLinearRing, 500, 0);
    OGR_G_AddPoint_2D(hLinearRing, 0 , 0);

    OGRGeometryH polygon = OGR_G_CreateGeometry(wkbPolygon);
    OGR_G_AddGeometry(polygon, hLinearRing);

    OGRGeometryH multiPolygon = OGR_G_CreateGeometry(wkbMultiPolygon);
    OGR_G_AddGeometry(multiPolygon, polygon)

**Comment by rouault** [comment]
> I'm trying to do GDALWarp using gdalwarp_lib.cpp ,

@raghulsekar  I don't understand your bug report. How exactly do you get this error message ? Please include all details to reproduce the issue

**Comment by raghulsekar** [comment]
`static CPLErr
TransformCutlineToSource( GDALDatasetH hSrcDS, OGRGeometryH hCutline,
                          char ***ppapszWarpOptions, char **papszTO_In )
{


    OGRGeometryH hMultiPolygon = OGR_G_Clone((OGRGeometryH) hCutline );
    char **papszTO = CSLDuplicate( papszTO_In );

    //Checkout that if there's a cutline SRS, there's also a raster one.
    OGRSpatialReferenceH  hRasterSRS = nullptr;
    const char *pszProjection = nullptr;

    if( GDALGetProjectionRef( hSrcDS ) != NULL
        && strlen(GDALGetProjectionRef( hSrcDS )) > 0 )
        pszProjection = GDALGetProjectionRef( hSrcDS );
    else if( GDALGetGCPProjection( hSrcDS ) != NULL )
        pszProjection = GDALGetGCPProjection( hSrcDS );

    if( pszProjection != NULL )
    {
        hRasterSRS = OSRNewSpatialReference(NULL);
        if( OSRImportFromWkt( hRasterSRS, (char **)&pszProjection ) != CE_None )
        {
            OSRDestroySpatialReference(hRasterSRS);
            hRasterSRS = NULL;
        }
    }
    //Extract the cutline SRS.
    OGRSpatialReferenceH hCutlineSRS = OGR_G_GetSpatialReference( hMultiPolygon );

    //Compare source raster SRS and cutline SRS
    if( hRasterSRS != nullptr && hCutlineSRS != nullptr )
    {
        /* OK, we will reproject */
    }
    else if( hRasterSRS != nullptr && hCutlineSRS == nullptr )
    {
        CPLError(CE_Warning, CPLE_AppDefined,
                 "the source raster dataset has a SRS, but the cutline features\n"
                 "not.  We assume that the cutline coordinates are expressed in the destination SRS.\n"
                 "If not, cutline results may be incorrect.");
    }
    else if( hRasterSRS == nullptr && hCutlineSRS != nullptr )
    {
        CPLError(CE_Warning, CPLE_AppDefined,
                 "the input vector layer has a SRS, but the source raster dataset does not.\n"
                 "Cutline results may be incorrect.");
    }

    if( hRasterSRS != nullptr )
        OSRDestroySpatialReference(hRasterSRS);


    //Extract the cutline SRS WKT
    if( hCutlineSRS != nullptr )
    {
        char *pszCutlineSRS_WKT = nullptr;

        OSRExportToWkt( hCutlineSRS, &pszCutlineSRS_WKT );
        papszTO = CSLSetNameValue( papszTO, "DST_SRS", pszCutlineSRS_WKT );
        CPLFree( pszCutlineSRS_WKT );
    }
    else
    {
        int iDstSRS = CSLFindString( papszTO, "DST_SRS" );
        if( iDstSRS >= 0 )
            papszTO = CSLRemoveStrings( papszTO, iDstSRS, 1, NULL );
    }

    //Transform the geometry to pixel/line coordinates.

    void         *hSrcImageTransformer;
    hSrcImageTransformer =
        GDALCreateGenImgProjTransformer2( hSrcDS, nullptr, papszTO );

    CSLDestroy( papszTO );

    if( hSrcImageTransformer == nullptr )
    {
        OGR_G_DestroyGeometry( hMultiPolygon );
        return CE_Failure;
    }

    OGR_G_Transform( hMultiPolygon,
                    (OGRCoordinateTransformationH) &hSrcImageTransformer );

    GDALDestroyGenImgProjTransformer( hSrcImageTransformer );

    //Convert aggregate geometry into WKT.
    char *pszWKT = NULL;

    OGR_G_ExportToWkt( hMultiPolygon, &pszWKT );
    OGR_G_DestroyGeometry( hMultiPolygon );


    *ppapszWarpOptions = CSLSetNameValue( *ppapszWarpOptions,
                                         "CUTLINE", pszWKT );

    CPLFree( pszWKT );

    return CE_None;


}`

While transforming geometry to pixel coords i'm getting this error,

ERROR 1: Cannot invert geotransform
ERROR 1: Attempt to destroy non-GTI2 transformer.
ERROR 1: Attempt to destroy non-GTI2 transformer.

**Comment by rouault** [comment]
You cannot use &hSrcImageTransformer as an argument of OGR_G_Transform() since it is *not* a OGRCoordinateTransformationH but of a different type.
Note that gdalwarp_lib.cpp uses a CutlineTransformer class for that purpose

**Comment by raghulsekar** [comment]
Okay but i get OGRERR_FAILURE while performing   ,
OGRErr eErr = OGR_G_Transform( hMultiPolygon(OGRCoordinateTransformationH) &oTransformer );
Eventhough the polygon is Valid.
