### ISSUE TITLE
Python bindings: gdal.config_option may not restore original state

### ISSUE THREAD

**Issue by dbaston** [OSGeo/gdal#8018]
## Expected behavior and actual behavior.

The `gdal.config_option` context manager should restore the original state upon exiting its context. Instead, it can cause migration of a config option from global to thread-local storage and vice-versa. This leads to confusing results such as:

```
gdal.SetConfigOption("A", "1")
with gdal.config_option("A", "2"):
    pass
gdal.SetConfigOption("A", "3")
gdal.GetConfigOption("A")  # 1
```

I have a partial fix to the problem in https://github.com/dbaston/gdal/commit/e8127d008c2d19e436769bdc738a3c4bbc7c5701. But this still fails in the situation where we have a config option defined both in global and thread-local storage, because there is no `CPLGetConfigOption` variant that provides access to the global value in this case. It looks like we can get access via `CPLGetConfigOptions`, but this would require exposing that function to SWIG and I think we should avoid exposing that function because the behavioral difference with `CPLGetConfigOption` is confusing. (I would propose exposing a `gdal.GetConfigOptions()` that returns all config options applicable to the current thread.)

So, we could go with a fix like the one above, which should be sufficient for non-contrived cases in the test suite, or (more cleanly) I could add a `CPLGetGlobalConfigOption` that complements `CPLGetThreadLocalConfigOption` and allows the `gdal.config_option` context manager to fully restore the original state. Or maybe there's another solution that I'm not seeing.

**Comment by rouault** [comment]
> I could add a `CPLGetGlobalConfigOption` that complements `CPLGetThreadLocalConfigOption` and allows the `gdal.config_option` context manager to fully restore the original state

sounds good to me
