### ISSUE TITLE
Possible divide by zero

### ISSUE THREAD

**Issue by benstadin** [OSGeo/gdal#8020]
There are three places where a divide by zero could happen (and happened for us) in GdalLinearSystem:

https://github.com/OSGeo/gdal/blob/6e9103bd5acb1ff8da305c4e77fa30335ffa3b70/alg/gdallinearsystem.cpp#L98C8-L98C8

**Comment by rouault** [comment]
@benstadin Can you provide a reproducer ? It is not obvious to me that division by zero may occur given the check at https://github.com/OSGeo/gdal/blob/6e9103bd5acb1ff8da305c4e77fa30335ffa3b70/alg/gdallinearsystem.cpp#L81

**Comment by rouault** [comment]
@benstadin  ping w.r.t providing a reproducer

**Comment by rouault** [comment]
closing due to lack of feedback
