### ISSUE TITLE
gdalwarp cannot use cutline from PostGis any longer (3.7)

### ISSUE THREAD

**Issue by albertodeluca** [OSGeo/gdal#8023]
## Expected behavior and actual behavior.

Since version 3.7 when trying to clip a raster using a cutline from a PostGIS query, gdalwarp gives this error:

ERROR 1: Unable to open secondary datasource `schema' required by JOIN.
ERROR 1: Failed to identify source layer from datasource.

In Version 3.6.x the same command runs without problems.

## Steps to reproduce the problem.

gdalwarp -cutline "PG:dbname='???' host='???' user='???' password='???'" -csql "SELECT geom FROM schema.table WHERE id='???'" -crop_to_cutline in.tif out.tif

## Operating system

Ubuntu 22
Windows 11

## GDAL version and provenance

3.7

**Comment by jratike80** [comment]
I got a different error
`ERROR 1: SELECT from table states failed, no such table/featureclass.
ERROR 1: Failed to identify source layer from datasource.`.

The same SQL with the same connection does find a feature with ogrinfo.
