### ISSUE TITLE
Weird Effect writing existing raster bands with Sparse or Compression

### ISSUE THREAD

**Issue by latot** [OSGeo/gdal#8025]
Hi all, this has been hard to debug, sadly I was not able to debug it completely here is the sections I was able to check.

```
#Generate sample data

import rasterio
from rasterio.transform import Affine
import shutil

import numpy as np
x = np.linspace(-90, 90, 256*20)
y = np.linspace(90, -90, 256*20)
X, Y = np.meshgrid(x, y)

import matplotlib.pyplot as plt

Z1 =  np.abs(((X - 10) ** 2 + (Y - 10) ** 2) / 1 ** 2)
Z2 =  np.abs(((X + 10) ** 2 + (Y + 10) ** 2) / 2.5 ** 2)
Z =  (Z1 - Z2)

#Write base raster (notice the no_data_value with 0)

xres = (x[-1] - x[0]) / len(x)
yres = (y[-1] - y[0]) / len(y)

transform = Affine.translation(x[0] - xres / 2, y[0] - yres / 2) * Affine.scale(xres, yres)

with rasterio.open(
        "temperature.tif",
        mode="w",
        driver="GTiff",
        height=Z.shape[0],
        width=Z.shape[1],
        count=1,
        dtype=Z.dtype,
        crs="+proj=latlong",
        transform=transform,
        SPARSE_OK = True,
        no_data_value=0
) as new_dataset:
        new_dataset.write(Z, 1)

#Generate right sample with gdal_translate, just to be sure all is right

from osgeo import gdal
gdal.UseExceptions()

ds = gdal.Open("temperature.tif")
ds = gdal.Translate(
  "temp2.tif",
  ds,
  options = '-co SPARSE_OK=YES'
)
ds = None

#Copy sample to edit

shutil.copyfile("temp2.tif", "temp3.tif")

#Edit the copy with all 0

ds = gdal.Open("temp3.tif", gdal.GA_Update)
ds.GetRasterBand(1).WriteArray(Z*0)
del ds

#Generate again the same file with sparse

ds = gdal.Open("temp3.tif")
ds = gdal.Translate(
  "temp4.tif",
  ds,
  options = '-co SPARSE_OK=YES'
)
ds = None
```

Well.... what is weird? lets check the file size:

First, checking all of them with sha256:

```
sha256sum *
100ae9e01707480a87ba83ed91c87f08e16f0ada0fc8286bd36d99fa751b2802  temp2.tif
e00efbb476aa1baea58c5929da0fb91c604663ac436c85bbf956f64b3b490ee0  temp3.tif
91728d2598be7beb45fac22a44ec8baaa96e60443f5a018474aaf29d0090e5af  temp4.tif
b5505752c3499f1d4fd74d1be7f50974eab6e27370f91f6356b4bbd88161bb92  temperature.tif
```

temperature: has data and sparse
temp2: recreate again with gdal_translate
temp3: replaced all the raster band with 0
temp4: recreate again with gdal_translate

temp2 and temperature should be the same, but maybe not, maybe gdal_translate just change the order of something but is all right.

now the size:

temperature: 209.7;B
temp2: 209.7mb
temp3: 209.7mb
temp4: 31.4mb

Now temp3 already has a empty raster band, sparse should remove it! but seems something is still there.. weird, not a expected behavior.

Oks now lets repeat all the experiments above, lets replace one thing, instead of sparse we will use compression.

So remove from rio the sparse option and lets use in gdal translate "-co COMPRESS=ZSTD" instead sparse.

now lets check the files:

temp2:196.9mb
temp3:196.9mb
temp4:139.6kb

What is weird here? is that when we write the data in temp3, for some reason is not  compressing the data with ZSTD... is even weird the size does not change...... the temp4 file now applied the ZSTD compression on all the 0s! so all right.

And, just as a extra point, probs not related with the issue, temp4[SPARSE] has 31.4mb while temp4[ZSTD] has 139.6kb.... why compress the data has less size than just not write it...

Playing with Sparse + Compression + Write the file on place has so very weird things... using Sparse + compression on pretty big rasters I was able to even get bigger files (like to have temp3 with 250mb for example), sadly I was not able to reproduce that particular example with free data.

I would like to say, this is simply! just the tags are not being applied when we are writing data, but! if that would be the case, pick the ZSRD example, the data compressed with ZSTD is less than the original one (209.7mb vs 196.9mb) if GDAL is just ignoring ZSTD the final size should change and move to 209.7mb, but instead of that, we just get the 196.9mb...

I'm just confused :3

Linux 64 Gentoo

GDAL 3.7.0
Python 3.11.4
python-gdal 3.6.4 (3.7.0 is buggy now)

Thx!

**Comment by rouault** [comment]
fix in https://github.com/OSGeo/gdal/pull/8051
The issue is that "Z*0" generates negative -0.0 floating-point value and not regular positive 0.0 one when applied to Z values that are negative, which caused detection of nodata to fail on those values

**Comment by latot** [comment]
Ty :D

**Comment by rouault** [comment]
> Sadly, even with that commit, the size of the files are the same...

temp4.tif is now just 32KB large, which is what is expected

**Comment by latot** [comment]
True, temp2.tif is the file with the data and sparse active, while temp3.tif is the same file where we write the new band, and is using 201M while it should use 32k as you described in temp4, temp4 is the same as temp3, the only difference is that we pass it through gdal_translate to be sure the data of sparse was removed.

temp3 and temp4 should have a similar size, when we replace the band with empty, sparse should remove the new empty blocks (after flush).

sorry if the descriptions above and the code was not clear enough u.u

**Comment by rouault** [comment]
> temp3 and temp4 should have a similar size, when we replace the band with empty, sparse should remove the new empty blocks

libtiff cannot decrease the file size and recover space that is no longer used, so you have to translate to a new file with SPARSE_OK=YES. So I don't think we can do more than that.

**Comment by latot** [comment]
:O that would explain a lot of things.

following that type of things.

What happens, if using ZSTD the compressed data is more than the actual used? it will increase the file size?

**Comment by rouault** [comment]
> if using ZSTD the compressed data is more than the actual used?

sorry I don't understand what you mean, and this is not really the place to discuss
