### ISSUE TITLE
Writing invalid GeoJSON

### ISSUE THREAD

**Issue by domist07** [OSGeo/gdal#8033]
## Expected behavior and actual behavior.

I want to save my result in GeoJSON format. Currently, the output file is invalid. At the end of the file, two brackets "]}" are missing.

## Steps to reproduce the problem.
Execute in python:
```python
gdal.VectorTranslate("./output.geojson", "./input.geojson")
```
Valid input file:
```json
{
    "type": "FeatureCollection",
    "name": "test",
    "crs": {
        "type": "name",
        "properties": {
            "name": "urn:ogc:def:crs:EPSG::25833"
        }
    },
    "features": [
        {
            "type": "Feature",
            "properties": {},
            "geometry": {
                "type": "Point",
                "coordinates": [
                    391746.3,
                    5819908.1
                ]
            }
        }
    ]
}
```
Invalid output file:
```json
{
    "type": "FeatureCollection",
    "name": "test",
    "crs": {
        "type": "name",
        "properties": {
            "name": "urn:ogc:def:crs:EPSG::25833"
        }
    },
    "features": [
        {
            "type": "Feature",
            "properties": {},
            "geometry": {
                "type": "Point",
                "coordinates": [
                    391746.299999999988358,
                    5819908.099999999627471
                ]
            }
        }
```

## Operating system

Windows 10.0.19045, 64bit
Anaconda environment, Python 3.10.10

## GDAL version and provenance

gdal 3.6.4 py310h3ccc0e8_1 conda-forge

**Comment by rouault** [comment]
Try the following to make sure the file is fully flushed:
```
out_ds = gdal.VectorTranslate("./output.geojson", "./input.geojson")
del out_ds
```
The file is not immediately closed as gdal.VectorTranslate() returns a still opened output dataset where you could potentially add new layers / features / etc

**Comment by dbaston** [comment]
The following also works (I'm not suggesting it's a good solution, but it may help explain the problem)

```
import gc

gdal.VectorTranslate("./output.geojson", "./input.geojson")
gc.collect()
```

@rouault , would it be possible for `VectorTranslate` to flush the new dataset before returning? Or are there drivers that don't support flushing without closing?

**Comment by rouault** [comment]
> would it be possible for `VectorTranslate` to flush the new dataset before returning? Or are there drivers that don't support flushing without closing?

for GeoJSON, if you flush, you have to write the closing ``] }`` sequence, which makes it impossible to add new features afterwards, unless you remove those characters, which is not possible in streaming mode ("/vsistdout/" output). But yes that could potentially be done

**Comment by domist07** [comment]
Thank you for the fast replies! Both solution works 😊.

Maybe another solution will be to add an argument to close the GeoJSON directly by the function (which is default `False` to preserve the actual behavior for other functions), or give a hint in the documentation.

**Comment by jcphill** [comment]
Another suggestion to minimize user astonishment would be for VectorTranslate to only return an open output dataset that was passed in as an argument, but when passed a filename close the new dataset and return nothing.

As for an unassigned return value not being finalized immediately, the python docs say "It is not guaranteed that __del__() methods are called for objects that still exist when the interpreter exits." but it is not clear how "exist" is defined.

**Comment by rouault** [comment]
> would be for VectorTranslate to only return an open output dataset that was passed in as an argument, but when passed a filename close the new dataset and return nothing.

that would break the API.   And there are valid use cases where a dataset must really be returned like ``out_ds =  gdal.VectorTranslate("", source_ds, format="Memory")``
