### ISSUE TITLE
Updating pci_datum.txt and pci_ellips.txt

### ISSUE THREAD

**Issue by goldberg-catalyst** [OSGeo/gdal#8034]
As a follow-up to this issue - https://github.com/OSGeo/gdal/issues/7647
I took a look at PCI's most up-to-date ellips.txt and datum.txt and I noticed that there are several ellipsoids  datums that we support in our software that haven't been propagated to GDAL's pci_ellips.txt and pci_datum.txt - as we haven't supplied you with updates in many years.

To that end, I have upload these files from our latest release:
[datum.txt](https://github.com/OSGeo/gdal/files/11917755/datum.txt)
[ellips.txt](https://github.com/OSGeo/gdal/files/11917756/ellips.txt)

Since our last sharing of these files, there have been some small changes in how the datum.txt file works
[This page](https://catalyst.earth/catalyst-system-files/help/references/proj_r/proj4N156.html) documents the format of these files.

As before, PCI gives permission for these files to be released with GDAL as per the statement below:

I, Michael Goldberg, on behalf of PCI Geomatics agree to allow the ellips.txt
and datum.txt file to be distributed under the GDAL open source license.

Michael Goldberg
Development Manager
PCI Geomatics

**Comment by rouault** [comment]
@goldberg-catalyst I've integrated the new files in https://github.com/OSGeo/gdal/pull/9695 . I haven't been able to spot the "small changes in how the datum.txt file works": what are they?

Could you consider integrating on your side the white space removal done in https://github.com/OSGeo/gdal/pull/9695/commits/d70c895bbb3e26b3ee631650cfb37134f30cd149? GDAL parser for that file is actually sensitive to the extra space after the comma separating fields

**Comment by goldberg-catalyst** [comment]
@rouault

I guess I should have be more specific. The change that I mentioned is the adding of the target datum for grid shift files

>  The  target datum used by the specified grid shift file(s) to shift. In this  example, the grid shift files are used to transform to D122.
> 
> If the gridshift files are meant to transform from the current datum to  the target datum, simply list the target datum for this field. In our  case, D788, the grid shift files contain parameters to transform from  D788 to D122, so list this field as D122.
> 
> If, however, the grid shift file were to contain parameters for  performing a transformation from the target datum to the current datum,  prefix the field with a '-'. For example,  if the grid shift files associated with your datum contain parameters  that are meant to transform the datum for D788 from D122 to D788,  specify this field as –D122.

I will make the specified whitespace changes on our side.

Thanks for this!

**Comment by rouault** [comment]
> The change that I mentioned is the adding of the target datum for grid shift files

From a quick glance, the OGRSpatialReference::importFromPCI() method only takes into account Bursa-Wolf parameters and ignore grid shift files.

**Comment by goldberg-catalyst** [comment]
In a related issue, in the last week, we discovered an error in one of the datums, the datum D400 definition should look like this:

> "D400","Greece 1987","E008",-199.87,74.79,246.62,"Greece",0,0,0,0

Going forward, if possible, I would like to update GDAL every time we make a change. What is the best/easiest way to do this?

**Comment by rouault** [comment]
> Going forward, if possible, I would like to update GDAL every time we make a change. What is the best/easiest way to do this?

the normal GitHub workflow: issue a pull request :-)
You're more than welcome to help for the maintenance of those files and more generally anything PCI related in GDAL, as I don't think this is in the scope of interest of any of the current team of core maintainers, or do we have a dedicated maintainer for that topic.
