### ISSUE TITLE
Output from gdalwarp blank when outputting to `.exr`

### ISSUE THREAD

**Issue by ChiIIBiII** [OSGeo/gdal#8036]
I built gdalwarp myself with exr support enabled, but when running even the most simple commands the output is all zero.

## Expected behavior and actual behavior.

I'm expecting the correct map to be displayed, as it works e.g. with .tiff output. Actual output is the image with correct resolution and format but with every entry being float 0.0

## Steps to reproduce the problem.

run gdalwarp command `gdalwarp topo1.nc topo1.exr`, the same command with `.tiff` works as expected. The output to the command line is identical and does not show any error or warning. The file I tried this on can be downloaded [here](https://topex.ucsd.edu/pub/srtm15_plus/topo1_topo2/)

## Operating system

Windows Subsystem for Linux i.e. Ubuntu 20.04 64 Bit

## GDAL version and provenance

Built from source version gdal-3.7.0 with command: `cmake -DGDAL_BUILD_OPTIONAL_DRIVERS=OFF -DOGR_BUILD_OPTIONAL_DRIVERS=OFF -DCMAKE_BUILD_TYPE=Release -DGDAL_ENABLE_DRIVER_EXR=ON -DGDAL_ENABLE_DRIVER_NETCDF=ON ..` which does report OpenEXR >= 2.2 to be found (I have 3.1 installed) and finishes without error

**Comment by jratike80** [comment]
Does topo5.nc work as well as a test image? It has much more reasonable file size (26M vs 574M)?
The driver seems to have an option called auto_rescale https://gdal.org/drivers/raster/exr.html. Have your tested with YES/NO? Have you tested the different PIXEL_TYPE options?

**Comment by ChiIIBiII** [comment]
Hi, thanks for the quick response. I tried now with the smaller file size and both `AUTO_RESCALE` and `PIXEL_TYPE`, the output contiues to be 0.0 for every pixel. Btw in the command for building I obviously forgot the flag `-DGDAL_ENABLE_DRIVER_NETCDF=ON`

**Comment by rouault** [comment]
I don't reproduce any problem:

$ gdalinfo -mm topo1.nc
[...]
   Computed Min/Max=-10926.809,8351.982
$ gdalwarp topo1.nc topo1.exr
$ gdalinfo -mm topo1.exr
[...]
    Computed Min/Max=-10926.809,8351.982

and this displays fine in QGIS
