### ISSUE TITLE
Lossless WebP compression doesn't preserve RGB when alpha=0

### ISSUE THREAD

**Issue by blacha** [OSGeo/gdal#8038]
## Expected behavior and actual behavior.

When converting a GTiff into a LERC Cog in gdal 3.7.0 then converting back to the GTiff I would expect the exact same GTiff output.

This appears to has changed between 3.6.4 and 3.7.0, 

using `"ghcr.io/osgeo/gdal:ubuntu-full-3.7.0"` Fails
using `"ghcr.io/osgeo/gdal:ubuntu-full-3.6.4"` Works

## Steps to reproduce the problem.

Grab input tiff `s3://linz-imagery/gisborne/gisborne-cyclone-gabrielle_2023_0.2m/rgb/2193/BH43_5000_0602.tiff`, I have tested a few other similar tiffs with the same results. (This bucket is requester pays so you need an aws account to access it :( ) 

Convert to raw uncompressed GTIFF
```bash
docker run \
  -v ${PWD}:${PWD} \
  ghcr.io/osgeo/gdal:ubuntu-small-3.7.0 \
  gdal_translate \
    -of gtiff \
    -co tiled=yes \
    -co num_threads=all_cpus \
    -co sparse_ok=true \
  ${PWD}/input/BH43_5000_0602.tiff \
  ${PWD}/output/BH43_5000_0602-raw.tiff
```

convert to LERC
```bash
docker run \
  -v ${PWD}:${PWD} \
  ghcr.io/osgeo/gdal:ubuntu-small-3.7.0 \
  gdal_translate \
    -of cog \
    -co num_threads=all_cpus \
    -co compress=lerc \
    -co max_z_error=0 \
  ${PWD}/output/BH43_5000_0602-raw.tiff \
  ${PWD}/output/BH43_5000_0602-lerc.tiff
```

Convert back to raw uncompressed GTIFF
```bash
docker run \
  -v ${PWD}:${PWD} \
  ghcr.io/osgeo/gdal:ubuntu-small-3.7.0 \
  gdal_translate \
    -of gtiff \
    -co tiled=yes \
    -co num_threads=all_cpus \
    -co sparse_ok=true \
  ${PWD}/output/BH43_5000_0602-lerc.tiff \
  ${PWD}/output/BH43_5000_0602-lerc-raw.tiff
```

validate sha256sum
```bash
$ sha256sum output/*-raw.tiff

899de0172618d7815d87f7255e3f8471ee4095e6f7d25acb3d2c8158361f2077  output/BH43_5000_0602-lerc-raw.tiff
e2a1d64b271557d26ce5c488888af65e8c099661f353cdb2cd581eb14caa52de  output/BH43_5000_0602-lzw-raw.tiff
e2a1d64b271557d26ce5c488888af65e8c099661f353cdb2cd581eb14caa52de  output/BH43_5000_0602-raw.tiff

```

The file size is approx 8MB different too.

```bash
$ ls output/*-raw.tiff
-rw-r--r-- 1 root root 785148404 Jul  3 12:26 output/BH43_5000_0602-lerc-raw.tiff
-rw-r--r-- 1 root root 792750580 Jul  3 12:28 output/BH43_5000_0602-lzw-raw.tiff
-rw-r--r-- 1 root root 792750580 Jul  3 12:26 output/BH43_5000_0602-raw.tiff
```

Changing the compression type to any other lossless compression (Zstd, lzw, Deflate, webp lossless) all allows the round trip.

changing the version from 3.7.0 to 3.6.4 allows the lerc round trip to work

## Operating system

Docker - Ubuntu Small

## GDAL version and provenance

Docker - Github

**Comment by blacha** [comment]
gdalinfo of the input tiff.

[gdalinfo-BH43_5000_0602-raw.tiff.txt](https://github.com/OSGeo/gdal/files/11931908/gdalinfo-BH43_5000_0602-raw.tiff.txt)

**Comment by jratike80** [comment]
I thinkt that sha256sum is not the right tool for comparing images. They may be some differences for example in headers which do not affect the image data. Have you compared the images with https://gdal.org/programs/gdalcompare.html? If the pixels are identical I would say that the images are identical as well.

**Comment by blacha** [comment]
> I think that sha256sum is not the right tool for comparing images. 

While shasum is really not designed for imagery comparisons, because the GDAL is very  consistent in its output it works pretty well for detecting changes in imagery.

All other lossless compression formats give the exact same shasum output when roundtripping

Also `gdalcompare.py` shows changes in `3.7.0` but not in `3.6.4`

```
$ gdalcompare.py BH43_5000_0602-raw.tiff 3.6.4-lerc-raw.tiff
Differences Found: 0
```

```
$ gdalcompare.py BH43_5000_0602-raw.tiff 3.7.0-lerc-raw.tiff
Files differ at the binary level.
Band 1 checksum difference:
  Golden: 14457
  New:    16699
  Pixels Differing: 5563749
  Maximum Pixel Difference: 255.0
Band 2 checksum difference:
  Golden: 62576
  New:    52949
  Pixels Differing: 5563891
  Maximum Pixel Difference: 247.0
Band 3 checksum difference:
  Golden: 44314
  New:    25699
  Pixels Differing: 5563604
  Maximum Pixel Difference: 255.0
Differences Found: 4
```

**Comment by blacha** [comment]
Making a little `git bisect` script, I have narrowed this change to 7bf2cc73c9

The commit before it round trips without problem f151b98204

Here is the `bisect` script I used to narrow this between tag v3.7.0 and v3.6.4

```bash
#!/bin/bash

cd build/

make -j32

git_tag=$(git describe --tags --always --match 'v*')


echo $git_tag
./apps/gdal_translate -of COG -co compress=lerc \
    /home/blacha/tmp/imagery/compress-test/output/BH43_5000_0602-raw.tiff \
    lerc.${git_tag}.cog.tiff

./apps/gdal_translate -of GTiff -co tiled=yes \
    -co num_threads=all_cpus \
    -co sparse_ok=true \
    lerc.${git_tag}.cog.tiff lerc.${git_tag}.raw.tiff


target_hash=$(sha256sum lerc.${git_tag}.raw.tiff | cut -d' ' -f1) 
echo ${target_hash}

if [ "$target_hash" != "e2a1d64b271557d26ce5c488888af65e8c099661f353cdb2cd581eb14caa52de" ]; then
    echo "Bad ${git_tag}"
    exit 1
else
    echo "Good ${git_tag}"
fi
```

**Comment by rouault** [comment]
> (This bucket is requester pays so you need an aws account to access it :( )

I do have a AWS account and tried to enable request_payer, but that doesn't work. Can you possibly attach here just a subset of the image sufficient to reproduce the issue ?

**Comment by blacha** [comment]
> I do have a AWS account and tried to enable request_payer, but that doesn't work. Can you possibly attach here just a subset of the image sufficient to reproduce the issue ?

I just checked with my personal account, 

```
$ aws s3 cp s3://linz-imagery/gisborne/gisborne-cyclone-gabrielle_2023_0.2m/rgb/2193/BH43_5000_0602.tiff . --request-payer requester
download: s3://linz-imagery/gisborne/gisborne-cyclone-gabrielle_2023_0.2m/rgb/2193/BH43_5000_0602.tiff to ./BH43_5000_0602.tiff
```

Worked as expected

I have also mirrored this file on my local server https://public.lo.chard.com/BH43_5000_0602.tiff 

In some more testing, it does appear to only affect tiffs that have some amount of alpha in them RGBA, some other testing tiffs I have had no issues at all.

**Comment by rouault** [comment]
Upon investigation, I believe the behavior is acceptable, and consistent with other codecs. The differences in pixels occur for pixels where alpha=0 and (R,G,B) != (0,0,0). 
The LERC codec will use the fact that alpha=0 to also set (R,G,B)=(0,0,0) for better compression.
The WEBP codec also alters (R,G,B) values in regions where alpha=0, but in a less predictable way, which explains the weird effects you can see on the original decoded image.

**Comment by blacha** [comment]
@rouault Thanks for looking into this!

That is a very interesting observation, Looking at the webp encoder I am assuming this issue is caused by `exact=0` when compressing `lossless=1` I wonder if the default should be changed to `exact=1` when `lossless=1`

This tiff was made by GDAL with a cutline, a command similar to this was run on it

```
gdalwarp -of GTIFF -co compress=webp -dstalpha -co num_threads=all_cpus -b 1 -b 2 -b 3  -cutline BH43_5000_0602.cutline.geojson  BH43_0602.tif BH43_0602.webp.exact_false.git.tif -co webp_lossless=true --config webp_exact true -co tiled=yes -co blockxsize=512 -co blockysize=512
```

I don't think `--config webp_exact true` is how I'm meant to set `exact=1` ?? ( I ended up just hard coding it with `sp->sEncoderConfig.exact = 0;` in `tif_webp.c`

the resulting tiff files seem to be pretty much the exact same size if `exact=1` or `exact=0`

**Comment by rouault** [comment]
is it really critical to preserve rgb values when alpha = 0 ? (not totally clear if your experiment with exact=0 or 1 was successful on preserving them)

**Comment by blacha** [comment]
I think for lossless mode `exact=1` is more correct,

When gdal applies a cutline from the warp command above it sets everything outside the cutline to RGBA: 0,0,0,0.

When using lossless compression eg LZW,ZSTD these pixels are stored as 0,0,0,0.
When using Webp lossless exact=0 these pixels are stored as x,y,z,0 where x,y,z >= 0
When using Webp lossless exact=1 these pixels are stored as 0,0,0,0

**Comment by blacha** [comment]
Awesome thanks for this @rouault , should I rename this bug into some more related to WebP as it isn't anything wrong with LERC!
