### ISSUE TITLE
Please can documentation for the gdal_zip.py script be added to the GDAL docs

### ISSUE THREAD

**Issue by simonwright-jbarisk** [OSGeo/gdal#8062]
## Expected behavior and actual behavior.

In the GDAL docs include a doc page for the useful gdal_zip.py script.

Add the gdal_zip.py script in the documentation table of contents either under the other utilities or a more appropriate section.

**Comment by rouault** [comment]
I had totally forgotten this script existed. We should probably just remove it now we have https://gdal.org/programs/sozip.html
