### ISSUE TITLE
How to use gdal_rasterize with complex geometry?

### ISSUE THREAD

**Issue by antifa-ev** [OSGeo/gdal#807]
I can easily rasterize a [8 MB SpatiaLite file of Greece](http://buildings.bplaced.net/out/greece.sqlite), but only because it's segmented.

My [10 MB GeoJSON file of China](http://buildings.bplaced.net/out/china.geojson) is not segmented and is too complex for gdal_rasterize:

`ERROR 1: GeoJSON object too complex`

Converting to [SpatiaLite](http://buildings.bplaced.net/out/china.sqlite) also doesn't fix this.

How can I use gdal to pretreat an overly complex geometry?

**Comment by rouault** [comment]
You have to specify an appropriate size or resolution.
e.g: gdal_rasterize china.geojson out.tif -burn 255 -ts 1024 1024
apparently you specified a pixel size of 500, but as the SRS is geodetic, the unit is in degrees, and 500 degrees is larger than Earth
