### ISSUE TITLE
GEOTIFF: ESRI sourceGCPs in aux.xml interpreted in wrong units

### ISSUE THREAD

**Issue by ConorMurphy21** [OSGeo/gdal#8083]
## Expected behavior and actual behavior.

When reading a georeferenced geotiff file with a `.tfw` affine transform, and `aux.xml` `esri:sourceGCPs` the x,y points should be interpreted as ground locations instead of pixel locations. It's visible in the code that GDAL takes the raw values provided in this field to mean pixel, line locations: [here](https://github.com/OSGeo/gdal/blob/5ad59397a6fce67ef991362f6c8f8f9127e7acb3/gcore/gdalpamdataset.cpp#L590). But given the files provided, or by adding GCP's to a georeferenced image it seems clear that these points should be interpreted as ground locations. 
[10-11-HI.zip](https://github.com/OSGeo/gdal/files/12009182/10-11-HI.zip)
GDAL also doesn't support tfwx files, but the problem exists even if a tfw world file is present.

## Steps to reproduce the problem.

Roundtrip or gdalinfo the provided file.

## Operating system

All

## GDAL version and provenance

All

**Comment by rouault** [comment]
Looking at another dataset at https://www.globalmapperforum.com/discussion/14661/georeferenced-an-image-in-arcgis-and-it-will-not-read-properly-into-global-mapper , it seems the SourceGCPs values must be combined with the ModelTiepointTag and ModelPixelScaleTag GeoTIFF tag to retrieve the actual pixel location.

**Comment by ConorMurphy21** [comment]
Interesting, I thought it would be calculated off of the ftwx/ftw file, didn't realize these tags were used.

I found the biggest problem with trying to fix this myself is that the PamInfo seems to be loaded separately from the other geotiff files, so the `ModelTiepointTag` and `ModelPixelScaleTag` cannot be applied right away, and there doesn't seem to be a great way to store semi-georeferencing, or GCP's that aren't pixel/line coords.

**Comment by rouault** [comment]
my hypothesis in https://github.com/OSGeo/gdal/issues/8083#issuecomment-1630444435 turned out to be wrong. We just need to ignore those GCPs due to the missing TIFFTAG_RESOLUTIONUNIT and use the geotransform stored in the ModelTiepointTag and ModelPixelScaleTag GeoTIFF tags. This gives excellent georeferencing for that image. Fix in https://github.com/OSGeo/gdal/pull/8114

**Comment by rouault** [comment]
@ConorMurphy21 It would help if you could actually provide a test image was more representative, ie when GCPs are used, that result in a better orthorectification.

> although ArcGIS Pro 3.2 alpha seems to georeference this image at null island (so I'm continuing to investigate if they have changed their interface more).

hum, that is quite concerning...

I have also exchanged with an engineer at Esri and he was surprised about those SourceGCPs being in georeferenced coordinates (but he might not be aware of changes in that part of their software stack)

**Comment by ConorMurphy21** [comment]
@rouault I'm sorry about that. I'll try and get back to you with a more realistic example. The image provided was just a test image with manual gcp's added in ArcGIS 3.1 so I could reproduce the bug while keeping the actual image private (I've asked for permission to share this file publicly and am waiting to here back). For now here is a screenshot of what the 10-11-HI is expected to be referenced as in arcGIS: 
![Screen Shot 2023-07-18 at 11 26 23 AM (1)](https://github.com/OSGeo/gdal/assets/38164654/2890e9e2-1361-464c-bbb7-89fe0ce3548b)
To reproduce on any image, if you open an image in ArcGIS 3.1 and manually add GCPs, and then export the raster layer as a geotiff it should produce the same behavior as seen in 10-11-HI.
Hope this helps, I'll try to get a more realistic example as soon as possible, hopefully this is still something to go off of.
