### ISSUE TITLE
Possible small error with possibly easy fix

### ISSUE THREAD

**Issue by bdezonia** [OSGeo/gdal#8084]
Is this line of code correct?

https://github.com/OSGeo/gdal/blob/5ad59397a6fce67ef991362f6c8f8f9127e7acb3/gcore/gdalmultidim.cpp#L2279

Shouldn't the value be set equal to 0 instead?

**Comment by rouault** [comment]
yes, it is correct. An array with 0 dimension is a scalar, hence 1 element.
