### ISSUE TITLE
GDAL3.7 downloaded from OSGeo4W is using both PROJ-9.0 and 9.2?

### ISSUE THREAD

**Issue by EZChe-EZDataMD** [OSGeo/gdal#8090]
## Expected behavior and actual behavior.
GDAL 3.7.0 installed via OSGeo4W asks for both proj_9_0.dll and proj_9_2.dll

## Steps to reproduce the problem.

Install latest GDAL from OSGeo4W Setup. 
Run gdalwarp.exe in the OSGeo4W/bin 
DLL errors will pop up.

## Operating system

Windows11

## GDAL version and provenance

GDAL 3.7.0-2

**Comment by rouault** [comment]
I would suspect a usage issue. In any case, the appropriate issue tracker for OSGeo4W related issues is https://trac.osgeo.org/osgeo4w/
