### ISSUE TITLE
Vector VRT  failed to GetFeature when the GeometryField PointFromColumns x,y,z values are none ansi characters

### ISSUE THREAD

**Issue by aharondavid** [OSGeo/gdal#8094]
GDAL Version - 3.1.2
OS: Windows 11

Bug description:

**The XML VTR Unicode:**
`<OGRVRTDataSource><OGRVRTLayer name='工作表1'><SrcDataSource>C:\Users\Administrator\Downloads\testTW (1).xlsx</SrcDataSource><GeometryType>wkbPoint</GeometryType><LayerSRS></LayerSRS><GeometryField encoding=PointFromColumns x = '經度' y = '緯度' z = ''/></OGRVRTLayer></OGRVRTDataSource>
`

**The XML VRT converted to UTF8:**
`<OGRVRTDataSource><OGRVRTLayer name='å·¥ä½œè¡¨1'><SrcDataSource>C:\Users\Administrator\Downloads\testTW (1).xlsx</SrcDataSource><GeometryType>wkbPoint</GeometryType><LayerSRS></LayerSRS><GeometryField encoding=PointFromColumns x = 'ç¶“åº¦' y = 'ç·¯åº¦' z = ''/></OGRVRTLayer></OGRVRTDataSource>
`

**The Code:**
```
GDALDataset* pGDALDataset = (GDALDataset*)GDALOpenEx(theVRT_UT8);
OGRLayer* pOGRLayer = pGDALDataset->GetLayer(0);
pOGRLayer->SetSpatialFilterRect(-180.0,-90.0,180.0,90);//without this line it is works
OGRFeature* pFeature = m_pLayer->GetNextFeature();
pFeature  is Null !
```
Attached xlsx Vector Layer:  [Chinese.xlsx](https://github.com/OSGeo/gdal/files/12037314/Chinese.xlsx)

**Comment by rouault** [comment]
I'm not sure to understand this report. It seems to be more a usage issue than a GDAL bug: GDAL expects the VRT to be in UTF8. "Unicode" by itself is a generic term that doesn't define a precise encoding. It is your respnsibility to provide a correctly UTF8 encoded VRT file.

**Comment by aharondavid** [comment]
Hi,

As you can see above, I did pass the UTF8 string to VRT: `GDALDataset* pGDALDataset = (GDALDataset*)GDALOpenEx(theVRT_UT8);`
but the rest code has unexpected behavior:
```
OGRLayer* pOGRLayer = pGDALDataset->GetLayer(0);
pOGRLayer->SetSpatialFilterRect(-180.0,-90.0,180.0,90);//without this line it is works
OGRFeature* pFeature = m_pLayer->GetNextFeature();   // return null
```

**Comment by rouault** [comment]
I can't reproduce with GDAL master / 3.7

```
from osgeo import gdal
ds = gdal.OpenEx('<OGRVRTDataSource><OGRVRTLayer name="工作表1"><SrcDataSource>Chinese.xlsx</SrcDataSource><GeometryType>wkbPoint</GeometryType><GeometryField encoding="PointFromColumns" x = "經度" y = "緯度"/></OGRVRTLayer></OGRVRTDataSource>')
lyr = ds.GetLayer(0)
lyr.SetSpatialFilterRect(-180.0,-90.0,180.0,90)
f = lyr.GetNextFeature()
f.DumpReadable()
```
returns
```
OGRFeature(工作表1):2
  公司名稱 (String) = 東方海外
  經度 (Real) = 120.30695
  緯度 (Real) = 22.57458
  POINT (120.30695 22.57458)
```
Perhaps this was a bug in GDAL 3.1.2
