### ISSUE TITLE
GDAL 3.7.1 Python PyPi tarball incomplete

### ISSUE THREAD

**Issue by nilason** [OSGeo/gdal#8098]
## Expected behavior and actual behavior.

Installing the GDAL 3.7.1 Python package at PyPi.org fails, see log from installing via MacPorts:

```
--->  Configuring py311-gdal
--->  Building py311-gdal
Executing:  cd "/opt/local/var/macports/build/_Users_nilason_ports_python_py-gdal/py311-gdal/work/GDAL-3.7.1" && /opt/local/Library/Frameworks/Python.framework/Versions/3.11/bin/python3.11 -m build --no-isolation --wheel --outdir /opt/local/var/macports/build/_Users_nilason_ports_python_py-gdal/py311-gdal/work 
* Getting build dependencies for wheel...
running egg_info
writing gdal-utils/GDAL.egg-info/PKG-INFO
writing dependency_links to gdal-utils/GDAL.egg-info/dependency_links.txt
writing requirements to gdal-utils/GDAL.egg-info/requires.txt
writing top-level names to gdal-utils/GDAL.egg-info/top_level.txt
error: package directory 'osgeo' does not exist
```

Comparing the contents of the tarball from 3.7.0 and 3.7.1 reveals that the directories `extensions` and `osgeo` are missing from the latter one.

## Operating system

OS independent

## GDAL version and provenance

GDAL 3.7.1 Python package at pypi.org (https://pypi.org/project/GDAL/#files)

**Comment by rouault** [comment]
version 3.7.1.1 published on pypi with expected context

**Comment by nilason** [comment]
Thanks!
