### ISSUE TITLE
gdalinfo does not work, when installed on Alpine Container

### ISSUE THREAD

**Issue by DanielMcKracken** [OSGeo/gdal#8099]
## Expected behavior and actual behavior.
Expected behavior: after installing gdal-tools with apk package manager I should be able to use "gdalinfo" in the cli of the container

Actual behavior: gdalinfo shows error messages instead of info output

```
/go # gdalinfo https://dop20-rgb.opengeodata.lgln.niedersachsen.de/325545804/2022-05-08/dop20rgb_32_554_5804_2_ni_2022-05-08.tif
Error relocating /usr/lib/libgdal.so.33: jpeg12_read_scanlines: symbol not found
Error relocating /usr/lib/libgdal.so.33: jpeg12_read_raw_data: symbol not found
Error relocating /usr/lib/libgdal.so.33: jpeg12_write_raw_data: symbol not found
Error relocating /usr/lib/libgdal.so.33: jpeg12_write_scanlines: symbol not found
/go # 
``` 

## Steps to reproduce the problem.
1. Start container with alpine image: docker run --rm -it golang:1.20-alpine
2. Add alpine edge repository: echo "@edge https://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories
3. Install gdal-tools: apk add --no-cache gdal-tools@edge
4. Use "gdalinfo"

## Operating system
golang:1.20-alpine

## GDAL version and provenance
Observed with v3.7.0-r4 as well as v3.7.1

**Comment by rouault** [comment]
This is an issue about binary builds not produced by us the OSGeo/gdal upstream team.  Perhaps you can't just mix golang:1.20-alpine with packages from alpine/edge/community ?
