### ISSUE TITLE
ogr2ogr import shp file to sql "Unable to find driver `MSSQLSpatial'"

### ISSUE THREAD

**Issue by qjohnchen** [OSGeo/gdal#8109]
## Expected behavior and actual behavior.

Expect shp file be imported to SQL Server with no issue.

## Steps to reproduce the problem.
Run below:
ogr2ogr -overwrite -f MSSQLSpatial "MSSQL:server=MYSQLSERVER;database=MyDemoDb;trusted_connection=yes;Driver={SQL Server Native Client 11.0}" "E:\FTPHome\MyData.shp" -progress -nln "test_ogr2org" -lco "GEOM_TYPE=geography" -lco "GEOM_NAME=Poly_Imported" -lco "SPATIAL_INDEX=No" -lco "PRECISION=No" -lco "LAUNDER=No" 
Got:
Unable to find driver `MSSQLSpatial'
## Operating system
Windows Server 2016

## GDAL version and provenance
C:\OSGeo4W>gdalinfo --version
GDAL 3.7.0, released 2023/05/02

## Notes
1. I used ogr2ogr with the old installation on the same machine (OS, DB). This is a new installation trying to see if it fix the issue that ring orientation of the imported polygon (geography type). But now I cannot even get anything into SQL DB.
2. I saw another post https://github.com/OSGeo/gdal/issues/7347 (closed already) saying this issue would be fixed in version 3.63 and I am at 3.7 already.

**Comment by rouault** [comment]
For OSGeo4W, you need to install the gdal-mss plugin: http://download.osgeo.org/osgeo4w/v2/x86_64/release/gdal/gdal-mss/

**Comment by steveoh** [comment]
@rouault how would you install this driver in ubuntu? I'm trying to do this in ci with the `ghcr.io/osgeo/gdal:ubuntu-small-3.7.3` image and the driver does not register. It is available since i apt install it and it works in pyodbc but ogrinfo does not have it registered.

**Comment by rouault** [comment]
> I'm trying to do this in ci with the `ghcr.io/osgeo/gdal:ubuntu-small-3.7.3` image

small is small. You need `ghcr.io/osgeo/gdal:ubuntu-full-3.7.3`

**Comment by steveoh** [comment]
Yah i was hoping to avoid 800 mb's for a single driver...
