### ISSUE TITLE
HAVE_SIGACTION inconsistent

### ISSUE THREAD

**Issue by schwehr** [OSGeo/gdal#811]
cpl_virtualmem.cpp uses sigaction without an ifdef of HAVE_SIGACTION.
cpl_http.cpp checks HAVE_SIGACTION.

What's up?  Can cpl_http.cpp just use sigaction without worrying and drop the HAVE_SIGACTION?

**Comment by schwehr** [comment]
A comment in cpl_virtualmem might be in order, yes?

**Comment by rouault** [comment]
> A comment in cpl_virtualmem might be in order, yes?

I let you add one where you find it appropriate.
