### ISSUE TITLE
error while installing GDAL 3.7.1 - webpdataset.cpp:564:22: error: ‘WebPBitstreamFeatures’ has no member named ‘format’

### ISSUE THREAD

**Issue by shrvi** [OSGeo/gdal#8111]
## Steps to reproduce the problem.

receiving the below error when running 'make' command
[ 22%] Built target gdal_WMS
[ 22%] Building CXX object frmts/webp/CMakeFiles/gdal_WEBP.dir/webpdataset.cpp.o
/code/GDAL/gdal-3.7.1/frmts/webp/webpdataset.cpp: In static member function ‘static GDALPamDataset* WEBPDataset::OpenPAM(GDALOpenInfo*)’:
/code/GDAL/gdal-3.7.1/frmts/webp/webpdataset.cpp:564:22: error: ‘WebPBitstreamFeatures’ has no member named ‘format’
         config.input.format == 2 ? "LOSSLESS" : "LOSSY", "IMAGE_STRUCTURE");
                      ^
make[2]: *** [frmts/webp/CMakeFiles/gdal_WEBP.dir/webpdataset.cpp.o] Error 1
make[1]: *** [frmts/webp/CMakeFiles/gdal_WEBP.dir/all] Error 2
make: *** [all] Error 2

## Operating system

Centos7

## GDAL version and provenance

GDAL version 3.7.1

**Comment by rouault** [comment]
@shrvi Fixed in https://github.com/OSGeo/gdal/pull/8113 (untested by me though!). I should not that Centos 7 is extremely outdated (is it still supported by the vendor??) and you shouldn't expect to built recent GDAL versions on it.
