### ISSUE TITLE
Can we drop `$Id$` now that GDAL uses git?

### ISSUE THREAD

**Issue by schwehr** [OSGeo/gdal#812]
`CPL_CVSID("$Id$")` and the comments with `$Id$` are now all pretty much useless.  Is this cruft that we can remove or is there some need to preserve these lines?  It's not a huge amount of overhead, but still would be nice to be rid of the noise.

```
find . -name \*.cpp -o -name \*.h | xargs egrep CPL_CVSID | wc -l
    1052
```

**Comment by schwehr** [comment]
Are those Id's getting any use in debugging or bug reports?

**Comment by rouault** [comment]
I like spying some proprietary software in the wild to see which GDAL version they are secretly embedding ;-)

**Comment by schwehr** [comment]
heh... that is actually pretty useful.  Had forgotten that I've done that myself a few times.
