### ISSUE TITLE
Docker: latest images are built (stucked?) to 3.7.0-devXXXX

### ISSUE THREAD

**Issue by Guts** [OSGeo/gdal#8126]
### Actual

Running a latest image from GHCR is giving a dev build of 3.7.0.

```sh
> docker run --rm -v /home:/home ghcr.io/osgeo/gdal:alpine-small-latest gdalinfo --version
GDAL 3.7.0dev-24afc75d3c3f2c85621e8b8d83f54a73b1d3ad33, released 2023/04/01
```
### Expected

I would like to have the latest version (3.7.1 at time of writing):

```sh
> docker run --rm -v /home:/home ghcr.io/osgeo/gdal:alpine-small-latest gdalinfo --version
GDAL 3.7.1, released 2023/07/06
```

Question: is latest meant to be based on master branch or meant to be the latest stable version? IMHO, I'm expecting that's the second option (stable), considering that if I want the master it means that I'm probably an advanced user/dev, so I can build it by myself by cloning the repo and following instructions. 

## Steps to reproduce the problem.

-

## Operating system

Ubuntu 22.04 64 bit

**Comment by rouault** [comment]
-latest Docker images have now been refreshed (this is a manual process that is done infrequently)

**Comment by Guts** [comment]
Thanks @rouault for the update. So it answers to my question: latest is meant to use the master branch with a `dev` word in the version number, exactly?

Because re-running the command, I've got:

```sh
GDAL 3.8.0dev-6e268bb61c95462d2704dca2ec0cad7d95d32df1, released 2023/07/20
```

Other questions:

- shouldn't this version number respect semver (3.8.0-dev+6e268bb61c95462d2704dca2ec0cad7d95d32df1 in that case)?

> this is a manual process 

- is there any reason to not automate it?
