### ISSUE TITLE
Segmentation Fault Error When Installing 'sf' R Package

### ISSUE THREAD

**Issue by dkczk** [OSGeo/gdal#8127]
## Expected behavior and actual behavior.

I wanted to install (well I had to) the "sf" R package. When installing it I get the following error at the end of the install process:
> checking GDAL: checking whether PROJ is available for running:... ./configure: line 3665: 31391 Segmentation fault      (core dumped) ./gdal_proj
no
configure: error: OGRCoordinateTransformation() does not return a coord.trans: PROJ not available?

So after some research I found this issue: https://github.com/OSGeo/gdal/issues/7770 and I'm somehow sure that this is the same problem, because when I run: `$: ldd /usr/bin/gdalinfo` I find two versions (I'm not sure if that's the right wording) of libproj:
> libproj.so.25 => /lib/x86_64-linux-gnu/libproj.so.25 (0x00007f08f8600000)
> libproj.so.22 => /lib/x86_64-linux-gnu/libproj.so.22 (0x00007f08f7200000)

So of course I tried the hack around with ln -s: `$: sudo ln -s /lib/x86_64-linux-gnu/libproj.so.25 /lib/x86_64-linux-gnu/libproj.so.22` but that returned an error:
> ln: failed to create symbolic link '/lib/x86_64-linux-gnu/libproj.so.22': File exists

I also checked the directory. There are 5 libproj files inside "/lib/x86_64-linux-gnu/", `libproj.so`, `libproj.so.22`, `libproj.so.22.2.1`, `libproj.so.25`, `libproj.so.25.9.1.1`. I really don't know how I can solve this. Thanks in advance.

## Steps to reproduce the problem.

Either any gdal command e.g. `$: gdalinfo` or when trying to install the R "sf" package with `install.packages("sf")`

## Operating system

Ubuntu 22.04.2 LTS 64 Bit

## GDAL version and provenance

GDAL 3.6.2, released 2023/01/02, ppa:ubuntugis/ppa

## Complete output of $: ldd /usr/bin/gdalinfo
linux-vdso.so.1 (0x00007fffebfac000)
        libgdal.so.32 => /lib/x86_64-linux-gnu/libgdal.so.32 (0x00007f08fbc00000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f08fb800000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f08fd2b1000)
        libcurl.so.4 => /lib/x86_64-linux-gnu/libcurl.so.4 (0x00007f08fd20a000)
        libodbc.so.2 => /lib/x86_64-linux-gnu/libodbc.so.2 (0x00007f08fbb91000)
        libodbcinst.so.2 => /lib/x86_64-linux-gnu/libodbcinst.so.2 (0x00007f08fd1f5000)
        libxml2.so.2 => /lib/x86_64-linux-gnu/libxml2.so.2 (0x00007f08fb61e000)
        libcrypto.so.3 => /lib/x86_64-linux-gnu/libcrypto.so.3 (0x00007f08fb000000)
        libzstd.so.1 => /lib/x86_64-linux-gnu/libzstd.so.1 (0x00007f08fbac2000)
        liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f08fba97000)
        libdeflate.so.0 => /lib/x86_64-linux-gnu/libdeflate.so.0 (0x00007f08fba73000)
        liblz4.so.1 => /lib/x86_64-linux-gnu/liblz4.so.1 (0x00007f08fba53000)
        libblosc.so.1 => /lib/x86_64-linux-gnu/libblosc.so.1 (0x00007f08fba42000)
        libarmadillo.so.10 => /lib/libarmadillo.so.10 (0x00007f08fba2e000)
        libqhull_r.so.8.0 => /lib/x86_64-linux-gnu/libqhull_r.so.8.0 (0x00007f08fb5ab000)
        libxerces-c-3.2.so => /lib/x86_64-linux-gnu/libxerces-c-3.2.so (0x00007f08fac00000)
        libjpeg.so.8 => /lib/x86_64-linux-gnu/libjpeg.so.8 (0x00007f08fb52a000)
        libtiff.so.5 => /lib/x86_64-linux-gnu/libtiff.so.5 (0x00007f08fb4a4000)
        libgeotiff.so.5 => /lib/x86_64-linux-gnu/libgeotiff.so.5 (0x00007f08fb46f000)
        libheif.so.1 => /lib/x86_64-linux-gnu/libheif.so.1 (0x00007f08faf7d000)
        libpng16.so.16 => /lib/x86_64-linux-gnu/libpng16.so.16 (0x00007f08fabc5000)
        libpoppler.so.118 => /lib/x86_64-linux-gnu/libpoppler.so.118 (0x00007f08fa800000)
        libgif.so.7 => /lib/x86_64-linux-gnu/libgif.so.7 (0x00007f08fb464000)
        libnetcdf.so.19 => /lib/x86_64-linux-gnu/libnetcdf.so.19 (0x00007f08fa6a9000)
        libcfitsio.so.9 => /lib/x86_64-linux-gnu/libcfitsio.so.9 (0x00007f08fa200000)
        libhdf5_serial.so.103 => /lib/x86_64-linux-gnu/libhdf5_serial.so.103 (0x00007f08f9e00000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f08fa5c2000)
        libwebp.so.7 => /lib/x86_64-linux-gnu/libwebp.so.7 (0x00007f08fab59000)
        libsqlite3.so.0 => /lib/x86_64-linux-gnu/libsqlite3.so.0 (0x00007f08f9cb3000)
        libpq.so.5 => /lib/x86_64-linux-gnu/libpq.so.5 (0x00007f08fa570000)
        libopenjp2.so.7 => /lib/x86_64-linux-gnu/libopenjp2.so.7 (0x00007f08fa518000)
        libkmlbase.so.1 => /lib/x86_64-linux-gnu/libkmlbase.so.1 (0x00007f08fb447000)
        libkmldom.so.1 => /lib/x86_64-linux-gnu/libkmldom.so.1 (0x00007f08f9c13000)
        libkmlengine.so.1 => /lib/x86_64-linux-gnu/libkmlengine.so.1 (0x00007f08fa1c7000)
        libfyba.so.0 => /lib/x86_64-linux-gnu/libfyba.so.0 (0x00007f08f9bbb000)
        libpcre2-8.so.0 => /lib/x86_64-linux-gnu/libpcre2-8.so.0 (0x00007f08f9b24000)
        libspatialite.so.7 => /lib/x86_64-linux-gnu/libspatialite.so.7 (0x00007f08f9200000)
        libmysqlclient.so.21 => /lib/x86_64-linux-gnu/libmysqlclient.so.21 (0x00007f08f8a00000)
        libfreexl.so.1 => /lib/x86_64-linux-gnu/libfreexl.so.1 (0x00007f08faf71000)
        libogdi.so.4.1 => /lib/libogdi.so.4.1 (0x00007f08faf55000)
        libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007f08fa196000)
        libgeos_c.so.1 => /lib/x86_64-linux-gnu/libgeos_c.so.1 (0x00007f08f9ae3000)
        libproj.so.25 => /lib/x86_64-linux-gnu/libproj.so.25 (0x00007f08f8600000)
        libjson-c.so.5 => /lib/x86_64-linux-gnu/libjson-c.so.5 (0x00007f08f9ad0000)
        libdfalt.so.0 => /lib/libdfalt.so.0 (0x00007f08f9a2b000)
        libmfhdfalt.so.0 => /lib/libmfhdfalt.so.0 (0x00007f08f9a01000)
        libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f08f8200000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f08f91e0000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f08fd2ea000)
        libnghttp2.so.14 => /lib/x86_64-linux-gnu/libnghttp2.so.14 (0x00007f08f91b6000)
        libidn2.so.0 => /lib/x86_64-linux-gnu/libidn2.so.0 (0x00007f08f9195000)
        librtmp.so.1 => /lib/x86_64-linux-gnu/librtmp.so.1 (0x00007f08f99e2000)
        libssh.so.4 => /lib/x86_64-linux-gnu/libssh.so.4 (0x00007f08f9128000)
        libpsl.so.5 => /lib/x86_64-linux-gnu/libpsl.so.5 (0x00007f08f9114000)
        libssl.so.3 => /lib/x86_64-linux-gnu/libssl.so.3 (0x00007f08f855c000)
        libgssapi_krb5.so.2 => /lib/x86_64-linux-gnu/libgssapi_krb5.so.2 (0x00007f08f90c0000)
        libldap-2.5.so.0 => /lib/x86_64-linux-gnu/libldap-2.5.so.0 (0x00007f08f89a1000)
        liblber-2.5.so.0 => /lib/x86_64-linux-gnu/liblber-2.5.so.0 (0x00007f08fa507000)
        libbrotlidec.so.1 => /lib/x86_64-linux-gnu/libbrotlidec.so.1 (0x00007f08f90b2000)
        libltdl.so.7 => /lib/x86_64-linux-gnu/libltdl.so.7 (0x00007f08f90a7000)
        libicuuc.so.70 => /lib/x86_64-linux-gnu/libicuuc.so.70 (0x00007f08f8005000)
        libsnappy.so.1 => /lib/x86_64-linux-gnu/libsnappy.so.1 (0x00007f08f909d000)
        libblas.so.3 => /lib/x86_64-linux-gnu/libblas.so.3 (0x00007f08f84b6000)
        liblapack.so.3 => /lib/x86_64-linux-gnu/liblapack.so.3 (0x00007f08f7800000)
        libarpack.so.2 => /lib/x86_64-linux-gnu/libarpack.so.2 (0x00007f08f846e000)
        libsuperlu.so.5 => /lib/x86_64-linux-gnu/libsuperlu.so.5 (0x00007f08f7f93000)
        libcurl-gnutls.so.4 => /lib/x86_64-linux-gnu/libcurl-gnutls.so.4 (0x00007f08f775e000)
        libjbig.so.0 => /lib/x86_64-linux-gnu/libjbig.so.0 (0x00007f08f908c000)
        libproj.so.22 => /lib/x86_64-linux-gnu/libproj.so.22 (0x00007f08f7200000)
        libaom.so.3 => /lib/x86_64-linux-gnu/libaom.so.3 (0x00007f08f6c00000)
        libde265.so.0 => /lib/x86_64-linux-gnu/libde265.so.0 (0x00007f08f76b4000)
        libx265.so.199 => /lib/x86_64-linux-gnu/libx265.so.199 (0x00007f08f5c00000)
        libdav1d.so.5 => /lib/x86_64-linux-gnu/libdav1d.so.5 (0x00007f08f5a7a000)
        libfreetype.so.6 => /lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007f08f75ec000)
        libfontconfig.so.1 => /lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00007f08f7f49000)
        liblcms2.so.2 => /lib/x86_64-linux-gnu/liblcms2.so.2 (0x00007f08f758a000)
        libnss3.so => /lib/x86_64-linux-gnu/libnss3.so (0x00007f08f594d000)
        libsmime3.so => /lib/x86_64-linux-gnu/libsmime3.so (0x00007f08f8444000)
        libplc4.so => /lib/x86_64-linux-gnu/libplc4.so (0x00007f08f8998000)
        libnspr4.so => /lib/x86_64-linux-gnu/libnspr4.so (0x00007f08f71c0000)
        libhdf5_serial_hl.so.100 => /lib/x86_64-linux-gnu/libhdf5_serial_hl.so.100 (0x00007f08f719b000)
        libbz2.so.1.0 => /lib/x86_64-linux-gnu/libbz2.so.1.0 (0x00007f08f8431000)
        libsz.so.2 => /lib/x86_64-linux-gnu/libsz.so.2 (0x00007f08f842c000)
        libminizip.so.1 => /lib/x86_64-linux-gnu/libminizip.so.1 (0x00007f08f5600000)
        liburiparser.so.1 => /lib/x86_64-linux-gnu/liburiparser.so.1 (0x00007f08f7573000)
        libfyut.so.0 => /lib/x86_64-linux-gnu/libfyut.so.0 (0x00007f08f7f3e000)
        libfygm.so.0 => /lib/x86_64-linux-gnu/libfygm.so.0 (0x00007f08f756a000)
        librttopo.so.1 => /lib/x86_64-linux-gnu/librttopo.so.1 (0x00007f08f6b8d000)
        libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f08f7187000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f08f7f39000)
        libtirpc.so.3 => /lib/x86_64-linux-gnu/libtirpc.so.3 (0x00007f08f591f000)
        libgeos.so.3.11.1 => /lib/x86_64-linux-gnu/libgeos.so.3.11.1 (0x00007f08f5200000)
        libunistring.so.2 => /lib/x86_64-linux-gnu/libunistring.so.2 (0x00007f08f5456000)
        libgnutls.so.30 => /lib/x86_64-linux-gnu/libgnutls.so.30 (0x00007f08f5015000)
        libhogweed.so.6 => /lib/x86_64-linux-gnu/libhogweed.so.6 (0x00007f08f58d7000)
        libnettle.so.8 => /lib/x86_64-linux-gnu/libnettle.so.8 (0x00007f08f5891000)
        libgmp.so.10 => /lib/x86_64-linux-gnu/libgmp.so.10 (0x00007f08f580f000)
        libkrb5.so.3 => /lib/x86_64-linux-gnu/libkrb5.so.3 (0x00007f08f4f4a000)
        libk5crypto.so.3 => /lib/x86_64-linux-gnu/libk5crypto.so.3 (0x00007f08f5427000)
        libcom_err.so.2 => /lib/x86_64-linux-gnu/libcom_err.so.2 (0x00007f08f717d000)
        libkrb5support.so.0 => /lib/x86_64-linux-gnu/libkrb5support.so.0 (0x00007f08f6b7f000)
        libsasl2.so.2 => /lib/x86_64-linux-gnu/libsasl2.so.2 (0x00007f08f4f2f000)
        libbrotlicommon.so.1 => /lib/x86_64-linux-gnu/libbrotlicommon.so.1 (0x00007f08f4f0c000)
        libicudata.so.70 => /lib/x86_64-linux-gnu/libicudata.so.70 (0x00007f08f3200000)
        libgfortran.so.5 => /lib/x86_64-linux-gnu/libgfortran.so.5 (0x00007f08f2e00000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f08f7176000)
        libnuma.so.1 => /lib/x86_64-linux-gnu/libnuma.so.1 (0x00007f08f6b72000)
        libuuid.so.1 => /lib/x86_64-linux-gnu/libuuid.so.1 (0x00007f08f6b69000)
        libnssutil3.so => /lib/x86_64-linux-gnu/libnssutil3.so (0x00007f08f4eda000)
        libplds4.so => /lib/x86_64-linux-gnu/libplds4.so (0x00007f08f4ed5000)
        libaec.so.0 => /lib/x86_64-linux-gnu/libaec.so.0 (0x00007f08f4ecc000)
        libp11-kit.so.0 => /lib/x86_64-linux-gnu/libp11-kit.so.0 (0x00007f08f2cc5000)
        libtasn1.so.6 => /lib/x86_64-linux-gnu/libtasn1.so.6 (0x00007f08f4eb4000)
        libkeyutils.so.1 => /lib/x86_64-linux-gnu/libkeyutils.so.1 (0x00007f08f4ead000)
        libquadmath.so.0 => /lib/x86_64-linux-gnu/libquadmath.so.0 (0x00007f08f4e65000)
        libffi.so.8 => /lib/x86_64-linux-gnu/libffi.so.8 (0x00007f08f4e58000)

**Comment by rouault** [comment]
> I really don't know how I can solve this. Thanks in advance.

This is a system installation/management issue, not a GDAL specific one. You need to rationalize on the number of PROJ versions you use, or install in dedicated/isolated installation prefixes
