### ISSUE TITLE
Possible bug

### ISSUE THREAD

**Issue by aparzi** [OSGeo/gdal#8128]
Hi all, I create a shapefile starting from a geojson. In the geojson properties there is a date field, formatted as a string, which must be exported as a native Date type. The problem is that the value is not taken, consequently the field is null. Can someone help me?

I use gdal 3.7.0 with following command:
ogr2ogr -f "ESRI Shapefile" -t_srs EPSG:32632 -s_srs EPSG:3857 -skipfailures

Thanks.

**Comment by rouault** [comment]
Please share the geojson file. If the date field is not formatted as "YYYY-MM-DD", then the GeoJSON driver will not recongize it as such, and neither the shapefile driver. You might need to rework the field content with SQL

**Comment by aparzi** [comment]
Hi @rouault,
```
geojson =>  {
  OBJECTID: 'ac77228ccf',
  AREA_AOCNO: 'CO1',
  TIPO_POZZE: '47x47',
  STATO: 'Progetto',
  DATA_INSER: '20/07/2023',
  ID_PROGETT: 'Toro_12T_CO1',
  CENTRALE: 'Centrale di progetto test',
  REGIONE: 'Molise',
  COMUNE: 'Toro',
  PROPRIETA: 'Fibercop',
  INDIRIZZO: 'Via Luigi Iammarino',
  CIVICO: null,
  LAT: 14.6719018043,
  LONG: 41.5908644812
}
```

these are the properties of the geojson, the DATA_INSER field is the date

**Comment by aparzi** [comment]
In QGIS the date field is null

<img width="1850" alt="Screenshot 2023-07-20 alle 16 52 14" src="https://github.com/OSGeo/gdal/assets/16490359/cdf50e37-ed98-44b6-8c38-540866eb087a">

**Comment by rouault** [comment]
@aparzi  yes, clearly this is not a ISO-8601 formatted date as expected by GDAL. You will need to use the ``SUBSTRING()`` and ``||`` SQL operators and the SQL SQLite dialect (https://gdal.org/user/sql_sqlite_dialect.html) to rework the content of your date field to "YYYY-MM-DD".

**Comment by aparzi** [comment]
Hi @rouault,
the field date it works in ISO-8601 formatted, but it views dd/mm/yy it is possible set as dd/mm/yyyy?

thanks
