### ISSUE TITLE
New feature - RPC Correction for ortho-rectification

### ISSUE THREAD

**Issue by widssaguenay** [OSGeo/gdal#8129]
Hello. I am wondering if anyone has ever tried using gdalwarp for ortho-rectifying a satellite image using customized RPCs instead of the original ones? Is this a feature that can be added? 
I am using the approach of this paper and add correction terms (A0, A1, A2, B0, B1, B2 in equation 1 of the paper) to my RPCs. 
https://www.researchgate.net/publication/228806391_Sensor_orientation_for_high-resolution_satellite_imagery_Further_insights_into_bias-compensated_RPCs
The problem is that then I had come up with my own code from scratch to ortho-rectify the images since gdalwarp can no longer recognize the new RPCs. My code is not very optimized and compared to gdalwarp takes a long time for completing rectification.
I would appreciate any thoughts for either adding this new feature to gdalwarp or another workaround.

**Comment by rouault** [comment]
You can create a VRT file with a <Metadata domain="RPC"> metadata domain. Cf  https://github.com/OSGeo/gdal/blob/master/autotest/gcore/data/rpc.vrt

**Comment by widssaguenay** [comment]
> You can create a VRT file with a metadata domain. Cf https://github.com/OSGeo/gdal/blob/master/autotest/gcore/data/rpc.vrt

Thank you for your answer. How do I fit in the new coefficients? The VRT files seem to have specific keys for each group of RPC parameters.

**Comment by rouault** [comment]
> How do I fit in the new coefficients?

I don't understand the question. Well you place the right value under the appropriate key name, as specified in https://gdal.org/development/rfc/rfc22_rpc.html

**Comment by widssaguenay** [comment]
> > How do I fit in the new coefficients?
> 
> I don't understand the question. Well you place the right value under the appropriate key name, as specified in https://gdal.org/development/rfc/rfc22_rpc.html

I mean if we are using only a bias (shift) correction, then it is easy to reform the correction equation back to a usual nominator/denominator format and find the new values under the COEFF keys but when we want to correct using a full affine correction, then the normalized row and col don't follow those equations.

**Comment by rouault** [comment]
> I mean if we are using only a bias (shift) correction, then it is easy to reform the correction equation back to a usual nominator/denominator format and find the new values under the COEFF keys but when we want to correct using a full affine correction, then the normalized row and col don't follow those equations.

Sorry, I'm not following. I guess this is on you to determine if you need to write a new transformer similar to the RPC one but with your particular requirements
