### ISSUE TITLE
gdalenhance not documented

### ISSUE THREAD

**Issue by jcphill** [OSGeo/gdal#8131]
## Expected behavior and actual behavior.

gdalenhance is not included in the list of raster programs on gdal.org and searching for it produces a single mention in RFC 57.

Having a rudimentary gdal/doc/source/programs/gdalenhance.rst file based on the output of gdalenhance --help-general would be a great improvement.

## Steps to reproduce the problem.

https://gdal.org/search.html?q=gdalenhance

## Operating system

All

## GDAL version and provenance

3.7.1

**Comment by rouault** [comment]
There's also no testing of this utility

**Comment by dbaston** [comment]
I've picked this up and would like to add some images to demonstrate the program, e.g.

original

![little_spruce](https://github.com/user-attachments/assets/2572ea48-ad7b-49b5-bd9b-380f2101f68c)

contrast-enhanced

![little_spruce_enhanced](https://github.com/user-attachments/assets/d28f65b1-3b27-4ae3-8254-419b767885cc)

Overall, I think the docs could benefit from more images, but I don't think we want to clutter the repo with 400kb binary files either.

I'd welcome ideas on simple way to host these.

**Comment by rouault** [comment]
> I don't think we want to clutter the repo with 400kb binary files either.

As a JPEG, it's 30 kB only (14 kB as WebP although I'm not totally sure if PDF output would support WebP), and I may know some program to do the conversion ;-)

**Comment by dbaston** [comment]
Resolved by #11144
