### ISSUE TITLE
 file URI fails in STACIT Driver for STAC asset href

### ISSUE THREAD

**Issue by julian-zeidler** [OSGeo/gdal#8135]
We have a STAC Server on a HPC System that delivers local file links (on a shared fileystem) in the STAC Assets.   The asset.href are like file:///dss/.../Copernicus_DSM_30_N48_00_E011_00_DEM.tif
These URLs work well for other stac software like stackstac, odc-stac, stac-browser
However the gdal STACIT Driver can not read such URIs. (File is accessible from the URI after file:// in the examples ). The STAC specification is not very clear on the format. They specify:
"URI to the asset object. Relative and absolute URI are both allowed."

## Expected behavior and actual behavior.
Example that does not work:
` gdalinfo --config CPL_DEBUG ON 'STACIT:"https://stac.terrabyte.lrz.de/public/api/search?collections=cop-dem-glo-90&bbox=11.089325,47.893787,11.923599,48.329322":asset=data' `

this results in:
`HTTP: Fetch(https://stac.terrabyte.lrz.de/public/api/search?collections=cop-dem-glo-90&bbox=11.089325,47.893787,11.923599,48.329322)
HTTP: libcurl/8.1.2 OpenSSL/3.1.1 zlib/1.2.13 zstd/1.5.2 libssh2/1.11.0 nghttp2/1.52.0
ERROR 1: Cannot open file:///dss/dsstbyfs01/pn56su/pn56su-dss-0008/DEM/TDM_COP3ARC_tiff/N48/E011/Copernicus_DSM_30_N48_00_E011_00/DEM/Copernicus_DSM_30_N48_00_E011_00_DEM.tif to retrieve band characteristics
gdalinfo failed - unable to open 'STACIT:"https://stac.terrabyte.lrz.de/public/api/search?collections=cop-dem-glo-90&bbox=11.089325,47.893787,11.923599,48.329322":asset=data'. `

Expected Behavior (analog to direct read )
` gdalinfo '/dss/dsstbyfs01/pn56su/pn56su-dss-0008/DEM/TDM_COP3ARC_tiff/N48/E011/Copernicus_DSM_30_N48_00_E011_00/DEM/Copernicus_DSM_30_N48_00_E011_00_DEM.tif' `

this results in:
Driver: GTiff/GeoTIFF
Files: /dss/dsstbyfs01/pn56su/pn56su-dss-0008/DEM/TDM_COP3ARC_tiff/N48/E011/Copernicus_DSM_30_N48_00_E011_00/DEM/Copernicus_DSM_30_N48_00_E011_00_DEM.tif
Size is 1201, 1201
Coordinate System is:
GEOGCRS["WGS 84",
    DATUM["World Geodetic System 1984",
        ELLIPSOID["WGS 84",6378137,298.257223563,
            LENGTHUNIT["metre",1]]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["degree",0.0174532925199433]],
    CS[ellipsoidal,2],
        AXIS["geodetic latitude (Lat)",north,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433]],
        AXIS["geodetic longitude (Lon)",east,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433]],
    ID["EPSG",4326]]
Data axis to CRS axis mapping: 2,1
Origin = (10.999583333333334,49.000416666666666)
Pixel Size = (0.000833333333333,-0.000833333333333)
Metadata:
  AREA_OR_POINT=Point
Image Structure Metadata:
  INTERLEAVE=BAND
Corner Coordinates:
Upper Left  (  10.9995833,  49.0004167) ( 10d59'58.50"E, 49d 0' 1.50"N)
Lower Left  (  10.9995833,  47.9995833) ( 10d59'58.50"E, 47d59'58.50"N)
Upper Right (  12.0004167,  49.0004167) ( 12d 0' 1.50"E, 49d 0' 1.50"N)
Lower Right (  12.0004167,  47.9995833) ( 12d 0' 1.50"E, 47d59'58.50"N)
Center      (  11.5000000,  48.5000000) ( 11d30' 0.00"E, 48d30' 0.00"N)
Band 1 Block=1201x1 Type=Float32, ColorInterp=Gray
  Unit Type: metre

## Operating system
SUSE Linux Enterprise Server 15 (x86_64)
VERSION = 15
PATCHLEVEL = 1

## GDAL version and provenance
GDAL 3.7.0, released 2023/05/02 installed from conda-forge

**Comment by m-mohr** [comment]
@rouault @jonas-eberle I'm not so sure whether the implementation is correct:

> file://path (i.e. two slashes, without a hostname) is never correct, but is often used.

see https://en.wikipedia.org/wiki/File_URI_scheme#How_many_slashes?

**Comment by rouault** [comment]
If there are three slashes, like above, and the first 2 ones are stripped as part of the "file://" prefix, then it remains a leading slash for an absolute unix path

**Comment by m-mohr** [comment]
@rouault That is correct, but if you provide just one slash it doesn't work, right? And the example lists a somewhat invalid file path then.

**Comment by rouault** [comment]
> That is correct, but if you provide just one slash it doesn't work, right?

no, it won't

> And then there's Windows with file:///c:/WINDOWS/clock.avi

That woulnd't work currently indeed.

**Comment by julian-zeidler** [comment]
To make it even more complicated, we currently experimenting with using hrefs to subdatasets in hdf files. Which allows us to access the Subdatasets directly from stac,as if they were single files. This only works with the file:// prefix because otherwise pystac would see it as a relative path and prepend it with the workingdir.....
'href=file://HDF4_EOS:EOS_GRID:"/dss/dsstbyfs01/pn56su/pn56su-dss-0008/MODIS/MOD13A3.061/2020/12/01/h27v04/MOD13A3.A2020336.h27v04.061.2021012025949.hdf":MOD_Grid_monthly_1km_VI:"1 km monthly NIR reflectance"'
