### ISSUE TITLE
swig/java make install doesn't copy the expected lib files - gdal 2.3.1

### ISSUE THREAD

**Issue by estani** [OSGeo/gdal#814]
## Expected behavior and actual behavior.

After make install in swig/java dir I expected `java.library.path=/usr/local/lib` to work.
Error message: "java.lang.UnsatisfiedLinkError: no gdalalljni in java.library.path"

Using the compiled libs `java.library.path=/gdal-2.3.1/swig/java/.libs/` worked as expected
`/usr/local/lib` contains `libgdal.*` while `/gdal-2.3.1/swig/java/.libs/` `libgdalalljni.*`

The file `libgdalalljni.so` is nowhere else in the system. This solves the problem:

`cp .libs/*.so /usr/local/lib` seems to solve the problem, I expect it to be run in `make install` call.

## Steps to reproduce the problem.

sources from 2.3.1 Downloaden and

    cd gdal-2.3.1
    ./configure --with-java=$JAVA_HOME \
        --without-bsb \
        --without-dwgdirect \
        --without-ecw \
        --without-fme \
        --with-gnm \
        --without-grass \
        --without-grib \
        --without-hdf4 \
        --without-hdf5 \
        --without-idb \
        --without-ingress \
        --without-jasper \
        --without-mrf \
        --without-mrsid \
        --without-netcdf \
        --without-pcdisk \
        --without-pcraster \
        --without-webp
    make
    make install
    cd swig/java/
    make
    make install

I didn't not want to use with-gnm reason will be in another ticket.

## Operating system

alpine 3.7.0

## GDAL version and provenance

2.3.1 sources - http://download.osgeo.org/gdal/2.3.1/gdal-2.3.1.tar.gz

**Comment by rouault** [comment]
This should be fixed per 69da464c50a75c6b6a29c0f2c0815ed444e5f0f6 for 2.3.2
