### ISSUE TITLE
Envi files do not allow NoDataValues without AUX files, though the format supports it. 

### ISSUE THREAD

**Issue by FlorianLuetticke** [OSGeo/gdal#8148]
## Expected behavior and actual behavior.

Envi files support a miss value (it is stored as `data ignore value = -999`). 
When disabling the creation of aux.xml files with 
   ` CPLSetThreadLocalConfigOption("GDAL_PAM_ENABLED", "NO"); `
I expect setting of the nodata value to work.

Instead I get the message `ERROR 6: testNoAux.img, band 1: SetNoDataValue() not supported for this dataset.` and the  `data ignore value = -999` line in the hdr file is missing.

If there are multiple bands with different nodata values, the current solution uses the nodata value of the first band in the hdr file (when aux.xml files are enabled). That solution would be (IMHO)  valid even in the case without aux files. though a warning during close would be good.

## Steps to reproduce the problem.

    CPLSetThreadLocalConfigOption("GDAL_PAM_ENABLED", "NO");
    GDALDriver*  poDriver = GetGDALDriverManager()->GetDriverByName("ENVI");
    GDALDataset* poDataset =
        poDriver->Create("testNoAux.img", 10, 11, 1, GDALDataType::GDT_Float32, nullptr);
    double              adfGeoTransform[6] = {10., 0.02, 0., 40., 0., -0.04};
    OGRSpatialReference oSRS;
    oSRS.SetWellKnownGeogCS("WGS84");
    char* pszSRS_WKT = nullptr;
    oSRS.exportToWkt(&pszSRS_WKT);
    poDataset->SetGeoTransform(adfGeoTransform);
    poDataset->SetProjection(pszSRS_WKT);
    CPLFree(pszSRS_WKT);
    GDALRasterBand* poBand = poDataset->GetRasterBand(1);
    poBand->SetNoDataValue(-999.);
    GDALClose(poDataset);

## Operating system

Ubuntu 22.04, 64bit. 
## GDAL version and provenance

3.4.1 64bit from jammy/universe

**Comment by jratike80** [comment]
Adding a reference for the ENVI header https://www.l3harrisgeospatial.com/docs/enviheaderfiles.html.

**Comment by rouault** [comment]
The issue with GDAL_PAM_ENABLED=NO has been fixed by e6fe8e507ab2a1ec4dc9542e71879b2c4b759a20 in GDAL 3.5.0

Warning if assigning different nodata values to different bands in https://github.com/OSGeo/gdal/pull/8480
