### ISSUE TITLE
False positive guessing of time format

### ISSUE THREAD

**Issue by aparzi** [OSGeo/gdal#8150]
Hi all, I have a string in the geojson with the following text "2:3".  Automatically in the conversion from geojson to ESRI shapefile the library recognizes the string as if it were in Time format.  Isn't there a way to ignore that field and tell it not to do the type conversion? 

Thank you all

**Comment by aparzi** [comment]
The problem is in this file and in this function: [https://github.com/OSGeo/gdal/blob/master/ogr/ogrsf_frmts/geojson/ogrgeojsonutils.cpp#L994](https://github.com/OSGeo/gdal/blob/master/ogr/ogrsf_frmts/geojson/ogrgeojsonutils.cpp#L994)

because the contents of the string are evaluated by seeing that if there are two points, the default is a time. I need it to remain a string. Can the concept be revised?

**Comment by jratike80** [comment]
Did you read the documentation https://gdal.org/drivers/vector/geojson.html about open options, and try this one?

> DATE_AS_STRING=[YES/NO]: (GDAL >= 3.0.3) Defaults to NO. Whether to expose date/time/date-time content using dedicated OGR date/time/date-time types or as a OGR String. Default is NO (that is date/time/date-time are detected as such). Can also be set with the [OGR_GEOJSON_DATE_AS_STRING](https://gdal.org/drivers/vector/geojson.html#config-OGR_GEOJSON_DATE_AS_STRING) configuration option.

**Comment by aparzi** [comment]
Hi @jratike80, I use this command but not works

**Comment by jratike80** [comment]
It works for me with config option but indeed not with open option.
Test data:
```
{
"type": "FeatureCollection",
"features": [
{ "type": "Feature", "properties": { "attr1":"2:3"},
"geometry": {"type":"Point","coordinates":[225,349]} }
]
}
```
Default response:

```
ogrinfo stringtest.json -al
...
OGRFeature(stringtest):0
  attr1 (Time) = 02:03:00
  POINT (225 349)
 ```
 
 With the config option:
 
 ```
 ogrinfo stringtest.json -al --config OGR_GEOJSON_DATE_AS_STRING YES
...
OGRFeature(stringtest):0
  attr1 (String) = 2:3
  POINT (225 349)
 ```

**Comment by aparzi** [comment]
Hi @jratike80,
for me it seems not works. I share you my code:

```
ogr2ogr --config OGR_GEOJSON_DATE_AS_STRING YES -f "ESRI Shapefile" -t_srs EPSG:32632 -s_srs EPSG:3857 -skipfailures "${TEMP_FILE_SHP}" "${pathGeoJsonTemp}" 
```

```
geojson =>  {
  OBJECTID: 'abcce8fcad',
  ID_PROGETT: 'AO nix_undefined',
  STRADA: "Via Antonella D'Aquino",
  CIVICO: '7',
  ID_PTE_ROE: '2:3'
}
```

Attribute target is ID_PTE_ROE

**Comment by aparzi** [comment]
I had entered -mapFieldType Time=String option but I was seeing 02:03:00

**Comment by jratike80** [comment]
Please share test data as a GeoJSON file that I can test with ogrinfo.

**Comment by aparzi** [comment]
@jratike80 maybe I understand the problem. I use old version of ogr2ogr, specifically the 2.1.3. Therefore config option not available.
Can you confirm?

**Comment by jratike80** [comment]
May I recommend that you make a test with a new GDAL version? Version 2.1.3 is 7 years old.

**Comment by aparzi** [comment]
@jratike80 sure. Yes I know, but unfortunately I can't simply update gdal. As soon as possible I will test with the configuration you suggested and the latest version of gdal

**Comment by aparzi** [comment]
hello @jratike80, I can confirm that with the new version of gdal (3.7.0) by inserting the configuration it works. The problem is that I'm using version 2 of gdal and I can't update it. So I have to do the fix by hand. 
Do you confirm?

**Comment by aparzi** [comment]
@rouault the problem exists in version 2.X because the configuration (DATE_AS_STRING) was added in version 3.X

**Comment by jratike80** [comment]
The GDAL project supports only the latest released version. Today it is 3.7.1.

**Comment by rouault** [comment]
> the problem exists in version 2.X because the configuration (DATE_AS_STRING) was added in version 3.X

well, what do you expect from us ? Fix the past ? Sorry despite that we are extremely talented, we can only fix the future, and only on good days. If you need the fix in 2.X, then I've good news for you: this is an open source project. Feel free to do the backport yourself.

**Comment by aparzi** [comment]
@rouault yes thanks, in fact I fixed the problem, maybe one day I will be able to update the version and use the configuration. I advise you to use less sarcasm in your answers and show more respect precisely because being an open source project you can discuss without controversy. Mine was a comment implying that the title you entered was not appropriate.

**Comment by rouault** [comment]
> Mine was a comment implying that the title you entered was not appropriate.

Sorry but I'm better placed than you to give appropriate issue titles, especially since I know what I've fixed! Show also respect for the time I spend !
