### ISSUE TITLE
slopeformat parameter not recognize in DEMProcessing 

### ISSUE THREAD

**Issue by timothee-colas-alteia** [OSGeo/gdal#8154]
## Expected behavior and actual behavior.

I launched a slope tif generation with DEMProcessing with the slopeformat option/parameter  set as degree. But it returns `TypeError: DEMProcessingOptions() got an unexpected keyword argument 'slopeformat'`
Yet the [documentation](https://gdal.org/api/python/osgeo.gdal.html#osgeo.gdal.DEMProcessingOptions) describes it.

## Steps to reproduce the problem.

```
    gdal.DEMProcessing(
        destName=str(slope_path),
        srcDS=str(tif_denoised_path),
        processing='slope',
        slopeformat='degree',
        format='GTiff'
        )
```
file: [tif_denoised](https://drive.google.com/file/d/195rKh2fLBd009UAWPOuu59ofGjmSGro6/view?usp=sharing)

## Operating system

Ubuntu 22.04 64 bit

## GDAL version and provenance

GDAL 3.7.1 version from conda-forge

**Comment by jratike80** [comment]
By looking at https://github.com/OSGeo/gdal/blob/master/apps/gdaldem_lib.cpp the name of the option is slopeFormat.
`int slopeFormat = 1;  // 0 = 'percent' or 1 = 'degrees'`.
Maybe there is an error in the documentation. Please try with `degrees` and with 0/1 inputs.
