### ISSUE TITLE
[feature request] : Catch dst dataset before it is written in GDALDriver::CreateCopy

### ISSUE THREAD

**Issue by chacha21** [OSGeo/gdal#8161]
I have a use case where I need to register and unregister extra information to datasets, related to cache usage.
(see [https://github.com/OSGeo/gdal/issues/6727](https://github.com/OSGeo/gdal/issues/6727))

The problem with `GDALDriver::CreateCopy()` is that the new dataset is only known at the end of the call, it is not even available in the progresscallback, so it is not eligible to my smart registration procedure.

Would it be possible to get a `GDALDataset` handle before the dataset is filled ?

I am aware that `GDALDriver::CreateCopy()` might not be the best candidate, but since there is no `GDALDataset::CopyTo()` or `GDALDataset::CopyFrom(),` then `GDALDriver::CreateCopy()` seems to be the most robust method to handle all information at once (data + meta data), rather that manually performing the whole process of "allocating new dataset"+"loop block copies with the best strategy according to the input src interleave"

**Comment by rouault** [comment]
> I have a use case where I need to register and unregister extra information to datasets, related to cache usage.

I don't understand what you mean

> Would it be possible to get a GDALDataset handle before the dataset is filled ?

A number of driver implementations of CreateCopy() don't even have a GDALDataset during the activate phase of the copy, and just GDALOpen() it at the end of the process

**Comment by chacha21** [comment]
> > Would it be possible to get a GDALDataset handle before the dataset is filled ?
> 
> A number of driver implementations of CreateCopy() don't even have a GDALDataset during the activate phase of the copy, and just GDALOpen() it at the end of the process

Ok, so it's a dead end. I will find a workaround.
