### ISSUE TITLE
gdalwarp cross antimeridian

### ISSUE THREAD

**Issue by MarcYin** [OSGeo/gdal#8163]
## Expected behavior and actual behavior.

I used gdalwarp to perform a clip of DEM cross the antimeridian but it fails:

```bash
Creating output file that is 1288198P x 3708L.
Processing /vsicurl/https://raw.githubusercontent.com/MarcYin/Copernicus_GLO_30_DEM_VRT/main/copernicus_GLO_30_dem.vrt [1/1] : 0
Warning 1: Self-intersection at or near point 1292120.4731767203 93931.998277788371
ERROR 1: Cutline polygon is invalid.
```
The [AOI.json](https://gist.githubusercontent.com/MarcYin/c769a834b946219d319f0fb013ac9044/raw/b9fee5b3181a9a410a82fa1f6dc9d978979a7dc1/AOI.json) I used.

The expected output should be a tif with the shape of 3708P X 3708L.

## Steps to reproduce the problem.

```bash
 gdalwarp test.tif /vsicurl/https://raw.githubusercontent.com/MarcYin/Copernicus_GLO_30_DEM_VRT/main/copernicus_GLO_30_dem.vrt -cutline AOI.json -crop_to_cutline
```

## GDAL version and provenance

GDAL 3.6.2, released 2023/01/02

**Comment by mdsumner** [comment]
this is a cracker of an example, I just wanted to say I think there's some things to fix on gdal and some things to explain, but also the meaningful data in the source only has a small overlap with the aoi

it's slower than it could be and speedups via improvements or workarounds are available (essentially identify which of the filelist .tifs are involved in your request and target them specifically - there are four, listed below, but there's also something wrong with the cutline here I think)

I had quite an explore but without a fully useful feedback yet, I'm happy to help pursue your practical task here and it might give some things to feed back into gdalwarp 

with these sources you might define the aoi by four numbers to -te and give -t_srs which will do the job

I can explain more in time but it's a bit off topic, depending on exactly what you need and whatay need improvement 👌

eg I did

```
gdalwarp /vsicurl/https://copernicus-dem-30m.s3.amazonaws.com/Copernicus_DSM_COG_10_N63_00_E177_00_DEM/Copernicus_DSM_COG_10_N63_00_E177_00_DEM.tif \
/vsicurl/https://copernicus-dem-30m.s3.amazonaws.com/Copernicus_DSM_COG_10_N64_00_E177_00_DEM/Copernicus_DSM_COG_10_N64_00_E177_00_DEM.tif \
/vsicurl/https://copernicus-dem-30m.s3.amazonaws.com/Copernicus_DSM_COG_10_N63_00_E178_00_DEM/Copernicus_DSM_COG_10_N63_00_E178_00_DEM.tif \
/vsicurl/https://copernicus-dem-30m.s3.amazonaws.com/Copernicus_DSM_COG_10_N64_00_E178_00_DEM/Copernicus_DSM_COG_10_N64_00_E178_00_DEM.tif test.tif -t_srs EPSG:32601   -te 300000 7090200  409800 7200000 
```

which gives what you want more or less, note there is not much overlap with populated tiles and much of that is ocean with no data

**Comment by rouault** [comment]
technical fix in https://github.com/OSGeo/gdal/pull/8188
However you likely don't want to do what you are asking gdalwarp to do.
You should either warp into EPSG:32601 as suggested by @mdsumner  . Or do 2 separate gdalwarp to EPSG:4326 with -te close to the -180 longitude range and another one to the 180 longitude range

**Comment by MarcYin** [comment]
Hi,

Thank you very much for the suggestions and I tried the way suggested by @mdsumner, but it seems the output is not correct:

![test](https://github.com/OSGeo/gdal/assets/19539641/e35b8338-e733-47c8-86a9-02c0a9aaafa7)

The expected output should be:

![test2](https://github.com/OSGeo/gdal/assets/19539641/12c35f1b-cc61-43d1-9eb1-bf9fe3edf744)

To create it, I have to convert the geojson to EPSG:4326 and split it into two polygons cross the antimeridian to perform the gdalwarp, then retroject then into the target projection and merge them together, as implemented [here](https://github.com/MarcYin/SIAC/blob/8afc2c3524e19df27cd7e906a7ce03b822896efd/SIAC/prepare_aux.py#L106C1-L119C26)

Does the new fix save me from doing this?

Thanks.

**Comment by mdsumner** [comment]
oh, this made me realize... does gdalwarp visit too many sources because the output spans all meridians? presumably it could do the bbox cull upfront, but is that precluded for some reason? I'm interested to explore it so any guide posts welcome (unless you think it's not feasible 🙏)

**Comment by mdsumner** [comment]
thanks for the details, this  is a common use case for me so that's good to know - I'll focus on culling the filelist 🙏
