### ISSUE TITLE
Uppercased file extensions become lowercased in osgeo.gdal.Dataset.GetFileList() on case-insensitive file systems

### ISSUE THREAD

**Issue by gorloffslava** [OSGeo/gdal#8164]
## Expected behavior and actual behavior.

Given: 
- multi-file dataset (e.g., Shapefile) w/ one of the files having an uppercased extension (e.g., `.PRJ`)
- e.g., "poly" Shapefile dataset from the GDAL autotest data: https://github.com/OSGeo/gdal/tree/master/autotest/ogr/data
- in particular, files: `poly.shp`, `poly.shx`, `poly.dbf`, `poly.PRJ`

Reproduction code:
```python
from osgeo import gdal
ds = gdal.OpenEx("poly.shp")
ds.GetFileList()
```

Expected behavior:
- on both case-sensitive and -insensitive file systems to get: `['poly.shp', 'poly.shx', 'poly.dbf', 'poly.PRJ']`

Actual behavior:
- case-sensitive filesystem: `['poly.shp', 'poly.shx', 'poly.dbf', 'poly.PRJ']`
- case-insensitive filesystem: `['poly.shp', 'poly.shx', 'poly.dbf', 'poly.prj']`

Extra note: 
- this only affects file extension, but not its name - if, for example, we'd rename all files in the dataset to `PoLy.*`, `GetFileList` would correctly output the following on both case-sensitive and -insensitive file systems: `['PoLy.shp', 'PoLy.shx', 'PoLy.dbf', 'PoLy.[PRJ|prj]']`.

## Operating system

Reproducible w/ any of the following:
- macOS 14.0 beta 4 (x86_64, Intel)
- Amazon Linux 2 (x86_64, Intel + aarch64, AWS Graviton2)
- Amazon Linux 2023 (x86_64, Intel + aarch64, AWS Graviton3E)
 
Tthe issue is not observed on case-sensitive file systems

## GDAL version and provenance

Reproducible w/ any the following:
- GDAL 3.7.1 from conda-forge 
- Self-compiled GDAL from `master` branch

**Comment by jratike80** [comment]
I do not feel that .prj and .PRJ should be treated in a different way, but according to the original shapefile specification by ESRI https://www.esri.com/content/dam/esrisites/sitecore-archive/Files/Pdfs/library/whitepapers/pdfs/shapefile.pdf .PRJ is invalid.

> Naming Conventions 
> All file names adhere to the 8.3 naming convention. The main file, the index file, and the
> dBASE file have the same prefix. The prefix must start with an alphanumeric character
> (a–Z, 0–9), followed by zero or up to seven characters (a–Z, 0–9, _, -). The suffix for
> the main file is .shp. The suffix for the index file is .shx. The suffix for the dBASE table
> is .dbf. All letters in a file name are in lower case on operating systems with case
> sensitive file names.

The specification does not mention .prj because at that time shapefiles were unaware of coordinate systems.

**Comment by gorloffslava** [comment]
> I do not feel that .prj and .PRJ should be treated in a different way, but according to the original shapefile specification by ESRI https://www.esri.com/content/dam/esrisites/sitecore-archive/Files/Pdfs/library/whitepapers/pdfs/shapefile.pdf .PRJ is invalid.
> 
> > Naming Conventions
> > All file names adhere to the 8.3 naming convention. The main file, the index file, and the
> > dBASE file have the same prefix. The prefix must start with an alphanumeric character
> > (a–Z, 0–9), followed by zero or up to seven characters (a–Z, 0–9, _, -). The suffix for
> > the main file is .shp. The suffix for the index file is .shx. The suffix for the dBASE table
> > is .dbf. All letters in a file name are in lower case on operating systems with case
> > sensitive file names.
> 
> The specification does not mention .prj because at that time shapefiles were unaware of coordinate systems.

Thanks for sharing this! It makes a lot sense... yet many datasets circulate in the internet (and even in GDAL test data) w/ .PRJ (or other uppercases sidecars). Plus internally GDAL checks both lower- and uppercased variants. 

Not sure in which tool such datasets were created, looks like GDAL always uses lowercased extensions.
