### ISSUE TITLE
gdal_translate -stats not always writting the STATISTICS

### ISSUE THREAD

**Issue by paulfouquet** [OSGeo/gdal#8169]
## Expected behavior and actual behavior.

We expected the STATISTICS to be always written in the TIFF metadata when using `gdal_translate` with the `-stats` flag.
When recorded, using `gdal_translate` on the `source.vrt` file, the STATISTICS were:
```
    STATISTICS_MAXIMUM=270.67300415039
    STATISTICS_MEAN=34.539939992429
    STATISTICS_MINIMUM=-1.0019999742508
    STATISTICS_STDDEV=66.156560596779
    STATISTICS_VALID_PERCENT=45.17
```
We found some case when the STATISTICS are not recorded.
Starting from the following command we noticed the STATISTICS were NOT recorded:
```
gdal_translate -q -of COG -stats -co blocksize=512 -co num_threads=all_cpus -co sparse_ok=true -co bigtiff=yes -a_srs EPSG:2193 -co compress=lerc -co max_z_error=0.001 -mo AREA_OR_POINT=Area -a_nodata -9999 -b 1 -co TARGET_SRS=EPSG:2193 -co EXTENT=1741600.0,5413200.0,1746400.0,5420400.0 source.vrt BQ31_10000_0403.tiff
```
In this command, the input `source.vrt` is made from 2 TIFF files, `DEM_BQ31_2019_1000_3127.tif` and `DEM_BQ31_2020_1000_3124.tif`.

Scenarios where the STATISTICS ARE recorded:
- The same command but with a VRT made from 1 TIFF only
```
gdal_translate -q -of COG -stats -co blocksize=512 -co num_threads=all_cpus -co sparse_ok=true -co bigtiff=yes -a_srs EPSG:2193 -co compress=lerc -co max_z_error=0.001 -mo AREA_OR_POINT=Area -a_nodata -9999 -b 1 -co TARGET_SRS=EPSG:2193 -co EXTENT=1744480.0,5419680.0,1744960.0,5420400.0 source_single.vrt BQ31_1000_3127.tiff
```
- removing the `EXTENT` configuration 
```
gdal_translate -q -of COG -stats -co blocksize=512 -co num_threads=all_cpus -co sparse_ok=true -co bigtiff=yes -a_srs EPSG:2193 -co compress=lerc -co max_z_error=0.001 -mo AREA_OR_POINT=Area -a_nodata -9999 -b 1 -co TARGET_SRS=EPSG:2193 source.vrt BQ31_10000_0403.tiff
```
- removing the `TARGET_SRS` configuration:
```
gdal_translate -q -of COG -stats -co blocksize=512 -co num_threads=all_cpus -co sparse_ok=true -co bigtiff=yes -a_srs EPSG:2193 -co compress=lerc -co max_z_error=0.001 -mo AREA_OR_POINT=Area -a_nodata -9999 -b 1 -co EXTENT=1741600.0,5413200.0,1746400.0,5420400.0 source.vrt BQ31_10000_0403.tiff
```

I could not see anything wrong or different using the `CPL_DEBUG ON`.

## Steps to reproduce the problem.

Executing the commands above with [the files downloadable here](https://wetransfer.com/downloads/8b5d8b370298f9136598c0a644747e6820230810211435/447d11?utm_campaign=TRN_TDL_05&utm_source=sendgrid&utm_medium=email&trk=TRN_TDL_05).

## Operating system

`ghcr.io/osgeo/gdal:ubuntu-small-3.7.0`

## GDAL version and provenance

`3.7.0` from `ghcr.io/osgeo/gdal:ubuntu-small-3.7.0`

**Comment by rouault** [comment]
@paulfouquet The download archive has experied. I'm a bit skeptical about the difference for a one-file vs two-file VRT
The minimal reproducer for me is:
```
cp autotest/gcore/data/byte.tif in.tif
gdal_translate -of COG in.tif  out.tif -stats -co TARGET_SRS=EPSG:4326
```

**Comment by paulfouquet** [comment]
I've updated the download link. Let me know if you have any issue I can upload on AWS S3 too.

I can't reproduce with this minimal command `gdal_translate -of COG source.vrt  out.tif -stats -co TARGET_SRS=EPSG:2193`
I reproduce with:
```
gdal_translate -q -of COG -stats -co blocksize=512 -co num_threads=all_cpus -co sparse_ok=true -co bigtiff=yes -a_srs EPSG:2193 -co compress=lerc -co max_z_error=0.001 -mo AREA_OR_POINT=Area -a_nodata -9999 -b 1 -co TARGET_SRS=EPSG:2193 -co EXTENT=1744480.0,5419680.0,1744960.0,5420400.0 /tmp/gdal/source.vrt /tmp/gdal/out.tif
```
-> No stats
```
gdal_translate -q -of COG -stats -co blocksize=512 -co num_threads=all_cpus -co sparse_ok=true -co bigtiff=yes -a_srs EPSG:2193 -co compress=lerc -co max_z_error=0.001 -mo AREA_OR_POINT=Area -a_nodata -9999 -b 1 -co TARGET_SRS=EPSG:2193 -co EXTENT=1744480.0,5419680.0,1744960.0,5420400.0 /tmp/gdal/source_single.vrt /tmp/gdal/out.tif
```
-> Stats ok

**Comment by rouault** [comment]
> ```
> gdal_translate -q -of COG -stats -co blocksize=512 -co num_threads=all_cpus -co sparse_ok=true -co bigtiff=yes -a_srs EPSG:2193 -co compress=lerc -co max_z_error=0.001 -mo AREA_OR_POINT=Area -a_nodata -9999 -b 1 -co TARGET_SRS=EPSG:2193 -co EXTENT=1744480.0,5419680.0,1744960.0,5420400.0 /tmp/gdal/source_single.vrt /tmp/gdal/out.tif
> ```
> 
> 
>     
>   
> 
> -> Stats ok

Stats are OK here because GDAL detects that there's no reprojection nor subsetting needed with your source_single.vrt as its extent and projection are already the one of the EXTENT and TARGET_SRS creation options.
Nothing to do with the fact that the VRT is a single vs multi source
