### ISSUE TITLE
GDAL and ODA(Teigha) compatibility - Fails to intitialize

### ISSUE THREAD

**Issue by psseri** [OSGeo/gdal#8170]
We are using the GDAL 3.6.2 NUGet packages and ODA (Teigha )23.12 packages. When we configure the GDAL (i.e., Gdal.AllRegister()) and load the ODA libraries (odInitialize), getting odInitialization error. Is any compatibility related issues or should we use any specific versions for GDAL and ODA?

**Comment by rouault** [comment]
Am I understand well, you are using directly the ODA API ? and not building the GDAL DWG / DGNv8 driver which use the ODA SDK ?
And what if you use only the ODA API ?

**Comment by szekerest** [comment]
@psseri What is the error message? I suppose there is a version mismatch between a dependent library.

**Comment by rouault** [comment]
Closing due to lack of feedback from reporter
