### ISSUE TITLE
Gdal.dll will not load from within AutoCAD process

### ISSUE THREAD

**Issue by Mbucari** [OSGeo/gdal#8171]
## Expected behavior and actual behavior.
I'm trying to use GDAL 3.7.1 in an AudoCAD ObjectARX addon, but I the gdal.dll refuses to load with `ERROR_PROC_NOT_FOUND`.

I've been using this AudoCAD addon for years with version 2.2.3 and it works find, but I cannot get 3.7.1 to load inside of AutoCAD. I can load it just fine in another standalone application, just not within AutoCAD.

## Steps to reproduce the problem.

- Create a .NET Framework 4.8 Dll.
- Add the GDAL nuget packages
- Add references to accoremgd.dll, acdbmgd.dll, and acmgd.dll.
- Create a static method to call from within AutoCAD
  ```C#
  public class Test
  {
	  [CommandMethod("GDALTEST")]
	  public void GdalTest()
	  {
		  GdalConfiguration.ConfigureOgr();
		  Autodesk.AutoCAD.ApplicationServices.Core.Application.DocumentManager.MdiActiveDocument.Editor.WriteMessage($"GDAL Usable: {GdalConfiguration.Usable}");
	  }
  }
  ```
- Run AutoCAD and load the test dll with `netload` and run the `GDALTEST` command.
- Printout: "GDAL Usable: False"
## Operating system

Windows 10 22H2

## GDAL version and provenance

3.7.1 from nuget

## Extra Detail

I've narrowed it down to `gdal.dll` not loading. I used `LoadLibraryEx` to load every `gdal.dll` dependency and they all load correctly, but `gdal.dll` will not.

**Comment by rouault** [comment]
CC @szekerest 
Closing as it doesn't seem to be like a GDAL upstream project, but smoe complex interaction with a third party.

**Comment by szekerest** [comment]
@Mbucari Probably the autocad addon is not compatible with gdal 3.7.1. Could you find out which procedure was not found in the gdal.dll?
