### ISSUE TITLE
Will a Java gdal jar be released for 3.7.1?

### ISSUE THREAD

**Issue by bdezonia** [OSGeo/gdal#8172]
I saw in the 3.7.1 release notes that signed 8-bit int support has been added. Will there be a 3.7.1 gdal jar released for this? On mvnrepository (see here: https://mvnrepository.com/artifact/org.gdal/gdal) it seems there are generally not point release jars.

I have developed some Java code that wants to use Int8s but if I use the 3.7.0 jar it crashes at runtime saying it doesn't know the GDT_Int8 constant.

If 3.8.0 is coming soon then making a 3.7.1 release may not be necessary.

Please advise. Thanks.

**Comment by rouault** [comment]
GDAL 3.7.1 bundle jar has just been uploaded to https://oss.sonatype.org
(we usually skip the release of the bundle jar on non .0 micro releases as the java bindings are generally untouched, but that one was the exception)
