### ISSUE TITLE
Small inconsistencies exist in the constant of radians per degree in the projects

### ISSUE THREAD

**Issue by bdezonia** [OSGeo/gdal#8178]
Using this command:

grep -r "\.0174532925199432957692" * | wc -w

in the gdal subdirectory and chopping off one digit at a time I can surmise the number of lines in the project that use each constant for degrees to radians: This is just an estimate because maybe some other constants use the same decimal digits (though I doubt it).

(constant, line count)

.017453292                              10
.0174532925199                      12
.017453292519943                  5404
.0174532925199432                220
.017453292519943295            692
.017453292519943295769      20
.0174532925199432957692    0

Maybe you want to consider cleaning up the weaker constants? Note also that my search might imply typos in some constants. If something deviates in the 10th place it will get binned into the 1st category above.

**Comment by rouault** [comment]
Those matches might be relevant fixing:
```
$ grep -r "17453292" ogr frmts data gnm port swig  | grep -v 174532925199
ogr/ogrsf_frmts/gpkg/ogrgeopackagedatasource.cpp:            "01745329252]],"
ogr/ogrsf_frmts/gpkg/ogrgeopackagedatasource.cpp:            "01745329252]],"
frmts/leveller/levellerdataset.cpp:    return d * 0.017453292;
frmts/terragen/terragendataset.cpp:    return d * 0.017453292;

$ grep -r "174532925199" ogr frmts data gnm port swig  | grep -v 1745329251994
ogr/ogrspatialreference.cpp:                   "+o_lat_p=%.18g +a=%.18g +b=%.18g +to_meter=0.0174532925199 "
ogr/ogrspatialreference.cpp:                   "+o_lat_p=%.18g +a=%.18g +b=%.18g +to_meter=0.0174532925199 "
```

Others would cause lots of changes, without obvious demonstrated advantages

**Comment by bdezonia** [comment]
I've done a little sleuthing to see these are the constants that match '0.17' or longer. Some of them look wrong.

0.017
0.017255 (WRONG???)
0.017453292
0.0174532925199
0.01745329251994328 (WRONG???)
0.017453292519943295
0.01745329251994329547 (WRONG???)
0.0174532925199432955 (WRONG???)
0.017453292519943295769
0.0174532925199433

(actual == 0.0174532925199432957692)

**Comment by rouault** [comment]
> 0.017255 (WRONG???)

Isn't this one coming from
data/ecw_cs.wkt:KALIANPR,GEOGCS["KALIANPUR",DATUM["KALIANPR",SPHEROID["EVINDMTR",6377301.243,300.8017255]],PRIMEM["Greenwich",0],UNIT["degree",0.0174532925199433]]
(from the 300.8017255 constant)

> 0.01745329251994328 (WRONG???)

Seem they come from
```
frmts/rik/rikdataset.cpp:        "01745329251994328,AUTHORITY[\"EPSG\",\"9122\"]],AUTHORITY[\"EPSG\","
frmts/bsb/bsbdataset.cpp:                "0.01745329251994328,AUTHORITY[\"EPSG\",\"9122\"]],AUTHORITY["
```
could indeed be fixed

> 0.01745329251994329547 (WRONG???)

comes from https://github.com/OSGeo/gdal/blob/58663616ac9b9f4b90a39131b7872103d2f58c2a/autotest/osr/osr_epsg.py#L491 . It is an odd test case. So OK

> 0.0174532925199432955 (WRONG???)

come from
https://github.com/search?q=repo%3AOSGeo%2Fgdal%200174532925199432955&type=code
could likely be fixed, hopefully without strange side effects

**Comment by bdezonia** [comment]
BTW there are minor inconsistencies and errors in the reciprocal operation (radians to degrees):

autotest/ogr/ogr_dxf.py:        57.2951851682141  (BADLY WRONG)
autotest/ogr/ogr_dxf.py:        57.295185168214   (BADLY WRONG)
frmts/nitf/mgrs.c:              57.29577951308232087
ogr/ogrct.cpp:                  57.29577951308232
ogr/ogr_srs_panorama.cpp:       57.2957795130823208766 (LAST DIGIT SHOULD BE 8)
ogr/ogrsf_frmts/sxf/ogr_sxf.h:  57.2957795130823208766 (LAST DIGIT SHOULD BE 8)

**Comment by rouault** [comment]
> autotest/ogr/ogr_dxf.py: 57.2951851682141 (BADLY WRONG)
> autotest/ogr/ogr_dxf.py: 57.295185168214 (BADLY WRONG)

"random" value not related at all to 180 / PI
