### ISSUE TITLE
S57: Feature.SetGeometry() does not work

### ISSUE THREAD

**Issue by free-x** [OSGeo/gdal#8179]
Hi,

i am trying to create a layer with python3-gdal. Unfortunately SetGeometry is not honored. 

Here is my code
```
#!/usr/bin/env python3

from osgeo import ogr

driver=ogr.GetDriverByName("S57")
outputfile="0000000.000"
data_source= driver.CreateDataSource(outputfile)

layer = data_source.GetLayerByName('ACHARE')

featurex = ogr.Feature(layer.GetLayerDefn())

featurex.SetField("CATACH", 1)
featurex.SetField("OBJNAM", "E")
featurex.SetField("SCAMIN", 89999)

point = ogr.Geometry(ogr.wkbPoint)
point.AddPoint(1198054.34, 648493.09)


featurex.SetGeometry(point)

layer.CreateFeature(featurex)

featurex = None # Cleanup

data_source = None #Close
```
Output of ogrinfo
```
# ogrinfo 0000000.000 ACHARE
INFO: Open of `0000000.000'
      using driver `S57' successful.

Layer name: ACHARE
Geometry: Unknown (any)
Feature Count: 1
Layer SRS WKT:
GEOGCRS["WGS 84",
    DATUM["World Geodetic System 1984",
        ELLIPSOID["WGS 84",6378137,298.257223563,
            LENGTHUNIT["metre",1]]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["degree",0.0174532925199433]],
    CS[ellipsoidal,2],
        AXIS["geodetic latitude (Lat)",north,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433]],
        AXIS["geodetic longitude (Lon)",east,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433]],
    ID["EPSG",4326]]
Data axis to CRS axis mapping: 2,1
RCID: Integer (10.0)
PRIM: Integer (3.0)
GRUP: Integer (3.0)
OBJL: Integer (5.0)
RVER: Integer (3.0)
AGEN: Integer (5.0)
FIDN: Integer (10.0)
FIDS: Integer (5.0)
LNAM: String (16.0)
LNAM_REFS: StringList (16.0)
FFPT_RIND: IntegerList (1.0)
CATACH: StringList (0.0)
DATEND: String (0.0)
DATSTA: String (0.0)
NOBJNM: String (0.0)
OBJNAM: String (0.0)
PEREND: String (0.0)
PERSTA: String (0.0)
RESTRN: StringList (0.0)
STATUS: StringList (0.0)
INFORM: String (0.0)
NINFOM: String (0.0)
NTXTDS: String (0.0)
SCAMAX: Integer (0.0)
SCAMIN: Integer (0.0)
TXTDSC: String (0.0)
RECDAT: String (0.0)
RECIND: String (0.0)
SORDAT: String (0.0)
SORIND: String (0.0)
OGRFeature(ACHARE):0
  RCID (Integer) = 0
  PRIM (Integer) = 0
  GRUP (Integer) = 0
  OBJL (Integer) = 4
  RVER (Integer) = 1
  AGEN (Integer) = 0
  FIDN (Integer) = 0
  FIDS (Integer) = 0
  LNAM (String) = 0000000000000000
  CATACH (StringList) = (1:1)
  OBJNAM (String) = E
  SCAMIN (Integer) = 89999

```
I'm missing Geometry of Object

Tested with GDAL 3.0.2, 3.2.2, 3.6.2
OS: Ubuntu Focal, Debian Bullseye/Bookworm
ARCH: AMD64

Thx in advance
free-x

**Comment by jratike80** [comment]
You mention S57, does it mean that your code works with other drivers?

**Comment by free-x** [comment]
As you can see, it is possible to set fields. In example I set CATACH,OBJNAM and SCAMIN

**Comment by jratike80** [comment]
By https://gdal.org/drivers/vector/s57.html#s-57-export there is some sort of support for S57-S57 conversion

> Preliminary S-57 export capability is intended only for specialized use, and is not properly documented at this time. Setting the following options is a minimum required to support S-57 to S-57 conversion via OGR.

In the S57 autotests I cannot see any tests for setting the geometries https://github.com/OSGeo/gdal/blob/master/autotest/ogr/ogr_s57.py. Please write mail to gdal-dev list and ask what are the exact capabilities of the driver.

**Comment by rouault** [comment]
Writing S57 is a super advanced topic if doing from scratch

You may be able to do a minimal S57 -> S57 with:
ogr2ogr out.000 autotest/ogr/data/s57/1B5X02NE.000 -f s57 --config "OGR_S57_OPTIONS" "RETURN_PRIMITIVES=ON,RETURN_LINKAGES=ON,LNAM_REFS=ON" IsolatedNode SBDARE

Look at the output of:
ogrinfo out.000 -al --config "OGR_S57_OPTIONS" "RETURN_PRIMITIVES=ON,RETURN_LINKAGES=ON,LNAM_REFS=ON"
and you'll see that

OGRFeature(SBDARE):0
  RCID (Integer) = 16
  PRIM (Integer) = 1
  GRUP (Integer) = 2
  OBJL (Integer) = 121
  RVER (Integer) = 1
  AGEN (Integer) = 65535
  FIDN (Integer) = 2135888456
  FIDS (Integer) = 723
  LNAM (String) = FFFF7F4F124802D3
  NAME_RCNM (IntegerList) = (1:110)
  NAME_RCID (IntegerList) = (1:1)
  ORNT (IntegerList) = (1:255)
  USAG (IntegerList) = (1:255)
  MASK (IntegerList) = (1:255)
  NATSUR (StringList) = (1:9)
  POINT (60.982344 -32.495494)

is linked with the

OGRFeature(IsolatedNode):0
  RCNM (Integer) = 110
  RCID (Integer) = 1
  RVER (Integer) = 1
  RUIN (Integer) = 1
  POINT (60.982344 -32.495494)

with the NAME_RCNM (IntegerList) = (1:110) + NAME_RCID (IntegerList) = (1:1)   pointing to RCNM (Integer) = 110 + RCID (Integer) = 1

You can also replicate that programatically by creating the IsolatedNode layer.

Don't ask me to provide more community support on that esoteric topic...
