### ISSUE TITLE
VSIS3_streaming: ReadDir doesn't work

### ISSUE THREAD

**Issue by ConorMurphy21** [OSGeo/gdal#8191]
## Expected behavior and actual behavior.

In the below example it seems like s3_streaming is unable to read a Zarr dataset because readDir isn't working properly.
Expected behavior is for readdir to list the files in the s3 bucket, and for the Zarr dataset with the `.zgroup` file to be opened.

## Steps to reproduce the problem.

```
from osgeo import gdal


def main():
    gdal.DontUseExceptions()
    gdal.SetConfigOption('AWS_REGION', 'aws-west-2')
    gdal.SetConfigOption('AWS_NO_SIGN_REQUEST', 'YES')
    print("===============vsis3_streaming=================")
    print("-----array:-----")
    # works as expected
    print('info: ' + str(gdal.Info('ZARR:"/vsis3_streaming/zarr-demo/store/spam/eggs/"')))
    # doesn't work as expected
    print('readdir: ' + str(gdal.ReadDir('/vsis3_streaming/zarr-demo/store/spam/eggs')))
    # works as expected
    print('stat: ' + str(gdal.VSIStatL('/vsis3_streaming/zarr-demo/store/spam/eggs/.zarray')))
    print("-----group:-----")
    # doesn't work as expected
    print('info: ' + str(gdal.Info('ZARR:"/vsis3_streaming/zarr-demo/store/spam/"')))
    # doesn't work as expected
    print('readdir: ' + str(gdal.ReadDir('/vsis3_streaming/zarr-demo/store/spam')))
    # works as expected
    print('stat: ' + str(gdal.VSIStatL('/vsis3_streaming/zarr-demo/store/spam/.zgroup')))
    # Seems like vsis3_streaming readDir is broken


if __name__ == '__main__':
    main()
```

## Operating system

Windows 11

## GDAL version and provenance

gdal python version 3.7.1

**Comment by gorloffslava** [comment]
Confirming. This affects 3.8.0dev as well.

**Comment by rouault** [comment]
There's little point in using /vsis3_streaming/ in a ZARR context. You should just use /vsis3/
Anyway ReadDir() implemented for the /vsiXX_streaming file systems in https://github.com/OSGeo/gdal/pull/8211

**Comment by ConorMurphy21** [comment]
@rouault is there a downside to using /vsiXX_streaming with Zarr? I would have thought it wouldn't make a noticable performance impact for streaming to fall back on non-streaming (sure maybe no benefit but also not downside)?

**Comment by rouault** [comment]
> is there a downside to using /vsiXX_streaming with Zarr?

In a ZARR context both streaming and non-streaming are probably more or less equivalent.  Actually when reading the tile data, the ZARR driver automatically switches to the streaming mode, as it reads whole file and doesn't need random access within them.
