### ISSUE TITLE
(Documentation bug) ogrinfo -fields and -geom parameters missing "=" sign

### ISSUE THREAD

**Issue by jm-uom** [OSGeo/gdal#8195]
GDAL version: 3070000 (via OSGeo/QGIS 3.28.7).

This page:
	https://gdal.org/programs/ogrinfo.html
	
Has a fields attribute:

```
-fields YES|NO:

    If set to NO, the feature dump will not display field values. Default value is YES.
```

But when I try and use this on my OGR (`ogrinfo -fields YES filename.shp`), I get:
```
ERROR 6: Unknown option name '-fields'
Usage: ogrinfo [--help-general] [-json] [-ro] [-q] [-where restricted_where|@filename]
               [-spat xmin ymin xmax ymax] [-geomfield field] [-fid fid]
               [-sql statement|@filename] [-dialect sql_dialect] [-al] [-rl]
               [-so|-features] [-fields={YES/NO}]]
               [-geom={YES/NO/SUMMARY}] [[-oo NAME=VALUE] ...]
               [-nomd] [-listmdd] [-mdd domain|`all`]*
               [-nocount] [-noextent] [-nogeomtype] [-wkt_format WKT1|WKT2|...]
               [-fielddomain name]
               datasource_name [layer [layer ...]]
```

If I try:
`ogrinfo -fields=YES filename.shp`
it executes (but there are no fields listed, just the layer name; possibly this is because it only works with a "feature dump", but the documentation is unclear on what one of them is. `-features` doesn't create one for me).

**Comment by jratike80** [comment]
Fortunately the the synopsis shows it right `[-fields={YES/NO}]`.
