### ISSUE TITLE
gdalinfo.py - dfNoData != dfNoData

### ISSUE THREAD

**Issue by jm-uom** [OSGeo/gdal#8196]
gdalinfo.py sample script has this in (about line 437) - GDAL Version: 3070100:

https://github.com/OSGeo/gdal/blob/d07f161365a893b17cb9d123ed765ca11bd7f3f6/swig/python/gdal-utils/osgeo_utils/samples/gdalinfo.py#L437C37-L437C37

```
dfNoData = hBand.GetNoDataValue()
if dfNoData is not None:
	if dfNoData != dfNoData:
		print("  NoData Value=nan")
	else:
		print("  NoData Value=%.18g" % dfNoData)
```

Maybe this is one of those weird floating things (in which case, apologies for the noise), but surely `dfNoData != dfNoData` will always be False?

**Comment by jratike80** [comment]
I thing it is about nan not being equal to none https://stackoverflow.com/questions/10034149/why-is-nan-not-equal-to-nan.
