### ISSUE TITLE
Python coordinates flipped on transformation

### ISSUE THREAD

**Issue by jm-uom** [OSGeo/gdal#8199]
The following Python, using GDAL 3070100:

```
source_srs = osr.SpatialReference()
source_srs.ImportFromEPSG(27700)

target_srs = osr.SpatialReference()
target_srs.ImportFromEPSG(4326)

transform = osr.CoordinateTransformation(source_srs, target_srs)
print(transform.TransformBounds(0, 0, 700000, 1300000, 21))
```
Prints this:
`(49.76680723514262, -9.496386752661158, 61.58143795006356, 3.634744234622926)`

so: miny, minx, maxy, maxx

There's no real documentation that I can find for what this output should be in python, but for:
https://gdal.org/doxygen/classOGRCoordinateTransformation.html#abc75de74e281490550ea618553f4291c it gives this order:

<html><body>

out_xmin | Minimum bounding coordinate of the first axis in target CRS
-- | --
out_ymin | Minimum bounding coordinate of the second axis in target CRS.
out_xmax | Maximum bounding coordinate of the first axis in target CRS.
out_ymax | Maximum bounding coordinate of the second axis in target CRS.

</body>
</html>

Issue being: The x and Y have flipped around.:
a) If I feed in minx, miny, maxx, maxy it's reasonable to expect that order back.
b) The C documentation suggests the order should be minx, miny, maxx, maxy too (see above).
c) csharp also seems to be expecting x,y (z) as the output - https://github.com/OSGeo/gdal/blob/88d311ca9f4a92cb55da675ad92d4b9f41658a65/swig/csharp/apps/OSRTransform.cs

(This also applies to TransformPoint)

**Comment by rouault** [comment]
Cf the issue template:
If you think there is an issue with coordinate order in GDAL 3.0, then it is
likely an intended behavior. See https://github.com/OSGeo/gdal/issues/1974
for more explanations.

**Comment by jratike80** [comment]
Check what the first axis and second axis are.

https://epsg.org/crs_27700/OSGB36-British-National-Grid.html?
[Cartesian 2D CS. Axes: easting, northing (E,N). Orientations: east, north. UoM: m.]
https://epsg.org/crs_4326/WGS-84.html?
[Ellipsoidal 2D CS. Axes: latitude, longitude. Orientations: north, east. UoM: degree]

So, the output is min-first-axis, min-second-axis... and thus right.

Historically many GIS programs used the axis order "easting-northing" or "longitude-latitude" for all coordinate systems, and used x and y as axis abbreviations in the same order. Some GDAL utilities are still following that "traditional GIS order". It is confusing.

BTW, officially X may sometimes be the first axis and mean northing. See https://epsg.org/crs_2393/KKJ-Finland-Uniform-Coordinate-System.html
[Cartesian 2D CS. Axes: northing, easting (X,Y). Orientations: north, east. UoM: m.]

**Comment by rouault** [comment]
I've fixed gdalinfo.py in https://github.com/OSGeo/gdal/commit/48723b1237a38b44e2db1bcf1a4c22c4dced4a6f

The topic of axis order issue is discussed in https://gdal.org/tutorials/osr_api_tut.html#crs-and-axis-order

> clear that the order was X, Y.

which doesn't mean anything unfortunately...  In EPSG, for some coordinate systems, X can be sometimes a Northing and Y a Easting...

> I expect it's going to get a lot of people.

Indeed, I'm quite desperate that the topic of axis order issue is going to pursue me & GIS practitioners for my whole life

**Comment by rouault** [comment]
> there’s no way to use GDAL to programmatically determine what the axis order is for a given projection.

cf https://github.com/OSGeo/gdal/blob/9927a30e1fb3683601192181d90eec117fd8301e/autotest/osr/osr_basic.py#L671-L704

**Comment by rouault** [comment]
> That should really be documented

why don't you help on this ? Contributing documentation has a relatively low barrier for entrance. There are far more people "requiring" stuff to be done than people actually fixing it.

**Comment by jratike80** [comment]
You can suggest improvements to the documents as you feel correct right now. Pull requests are reviewed in any case, and as a newcomer you are better for making the edits for other incomers than us, who have suffered pain for the axis order for so many years that we have adapted us to it.
