### ISSUE TITLE
ComputeSourceWindow  how to use?

### ISSUE THREAD

**Issue by tthh7** [OSGeo/gdal#8203]
When using GDALWarpOperation::ComputeSourceWindow to calculate the source window, I intend to ensure that the window is correctly positioned within the original valid area. How should ComputeSourceWindow be used when the target window and the source window are in different coordinate systems?

**Comment by rouault** [comment]
GDALWarpOperation::ComputeSourceWindow() is a private method : you shouldn't, and can't, call it. If you've setup the GDALWarpOptions correctly, then it will do the right thing
