### ISSUE TITLE
Elevation wrong (possibly?) after transformation.

### ISSUE THREAD

**Issue by Zekaric** [OSGeo/gdal#821]
A client of ours has the following point (AGD66 / AMG zone 55)…
(X or East, Y or North, Elevation)
295571.240, 8046485.010, 848.000

After conversion with GDAL (GDA94 / MGA zone 55)…
295686.913, 8046661.578, 891.191

Client was expecting…
295685.573, 8046660.983, 848.000

## Expected behavior and actual behavior.

The x and y are slightly different but the elevation is a significant change.  However, I can't claim the client is right or wrong and can't argue either way as I just don't know.  More comments at the end.

## Steps to reproduce the problem.

gdaltransform (2.3.1), EPSG found from https://epsg.io
C:\work\zgdal\bin>gdaltransform.exe -s_srs EPSG:20255 -t_srs EPSG:28355
295571.240 8046485.010 848.000
295686.913617851 8046661.57804907 891.191467945464

## Operating system

Window 10

## GDAL version and provenance

Same results using GDAL 1.11.1, 2.2.3, 2.3.1

## Other comments

We have incorporated the GDAL library (For C# V 1.11.1 from NuGet, also tried a newer version using V 2.2.3) into our app.  For the most part it seems to work brilliantly and no complaints from any other clients.  

Using the library it looks like the X and Y are ‘slightly’ off but the elevation is way off.  (Assuming the client is right.)

Using an online converter here  http://tool-online.com/en/coordinate-converter.php gets what the client wants pretty much.  (Assuming the web site is doing it right.)

Using this tool https://www.binaryearth.net/Downloads/DownloadAusDatumTool.php gets what GDAL returns almost.  The tool doesn’t include elevations but sort of leads me to believe elevations wouldn’t change then.

Similarly https://epsg.io/transform#s_srs=20255&t_srs=28355&x=295571.2400000&y=8046485.0100000 returns what GDAL returns but again. No elevation component like the tool above.

I’m at a loss as to who is right and who is wrong.  However elevation looks suspect in the GDAL conversion but I have no way to argue that point as I have no clue.  Plus I don’t know how to argue why either is right or wrong.

Any comments would be appreciated as I really don’t know anything about this problem and I’m asked by my company to make a fix (if there is one to fix.)  

Apologies if this should be on the mailing list, I did try to subscribe but no response or acceptance to the list for quite some time and so I couldn't post this there.

Robbert de Groot

**Comment by rouault** [comment]
The transformation between AGD66 and GDA94 involves a datum shift transformation, which is done with a Helmert geocentric transformation using +towgs84=-117.808,-51.536,137.784,0.303,0.446,0.234,-0.29 parameters. Such transformation intrinsically changes elevation values, so the result output by GDAL is expected.
