### ISSUE TITLE
Broken Link in OGRSpatialReference documentation

### ISSUE THREAD

**Issue by mh-aethon** [OSGeo/gdal#8221]
(Let me know if documentation errors should be reported elsewhere)

There is an external link in the OGRSpatialReference documentation that is currently broken. 

At
https://gdal.org/doxygen/classOGRSpatialReference.html#aaa2027f62b01d61d9aab83629dd86cda

The link to 

http://www.remotesensing.org/geotiff/proj_list

Returns a domain-unregistered page.

Copies of the original are still available on Archive.org.

Expected behaviour: The link returns a valid page
Actual behaviour: The link does not return a valid page

**Comment by agiudiceandrea** [comment]
A possible replacement is http://geotiff.maptools.org/proj_list/ or https://proj.org/operations/projections/index.html.

**Comment by jratike80** [comment]
How about the OGC standard https://docs.ogc.org/is/19-008r4/19-008r4.html#_map_projection_methods?

**Comment by rouault** [comment]
> How about the OGC standard https://docs.ogc.org/is/19-008r4/19-008r4.html#_map_projection_methods?

This is geotiff specific. For  OGRSpatialReference::SetProjParm() we need WKT parameter names. So proj_list/ is better. In https://github.com/OSGeo/gdal/pull/8256, I'm pulling the relevant pages from the source repository (OSGeo/libgeotiff) under gdal.org/

**Comment by mh-aethon** [comment]
Thanks!
