### ISSUE TITLE
gdal.Warp with EEDAI driver has different behavior in Windows than Linux

### ISSUE THREAD

**Issue by mjhutch** [OSGeo/gdal#8224]
## Expected behavior and actual behavior.

Expected behavior was to use the GDAL Python bindings, together with the EEDAI raster driver, to call gdal.Warp and perform a warp of an image/asset within Google Earth Engine (GEE) to the hard disk of the local machine running the code. It was expected that by providing cutlineDSName and cropToCutline parameters, the warp would clip to the area of interest. **It was expected that the code written to do this would produce the same result in both Linux and Windows.**

The actual behavior is that code written to do this in Linux works well, **but does not produce the same/correct result when run in Windows**. This is why a bug/issue report is being submitted. 

The result in Linux produces a cropped GeoTIFF, containing all the original bands and valid pixel values, stored locally and with the correct geospatial location in its metadata. In the sample code the AOI is Angel Island near San Francisco.

The result in Windows is a cropped GeoTIFF containing all zeros for pixel data, and geospatially located in the ocean near South America.   

_In addition to the code working correctly in Linux, both the Linux and Windows environments are configured correctly which is why this is a bug/issue report and not just a question or request for support._

## Steps to reproduce the problem.

The code below can be run in Linux to see it work correctly. Note that you will need to use your own GCP credentials for the code to run.

    from osgeo import gdal
    from osgeo import ogr
    import json
    from osgeo import osr

    print(gdal.__version__)
    gdal.UseExceptions()    # Enable exceptions

    gdal.SetConfigOption("GOOGLE_APPLICATION_CREDENTIALS", "/home/hutch/code/keys/hutch-sandbox-e6de2d685b26.json")

    gee_dataset = gdal.Open("EEDAI:projects/earthengine-public/assets/LANDSAT/LC09/C02/T1_TOA/LC09_044034_20220111", gdal.GA_ReadOnly)
    if gee_dataset is None:
       print("Error opening GEE raster via GDAL")

    geojson_aoi = {
      "type": "FeatureCollection",
      "features": [
        {
          "type": "Feature",
          "properties": {},
          "geometry": {
            "coordinates": [
              [
                [
                  -122.44805090992816,
                  37.87323765952179
                ],
                [
                  -122.44805090992816,
                  37.85199045974289
                ],
                [
                  -122.41614344378331,
                  37.85199045974289
                ],
                [
                  -122.41614344378331,
                  37.87323765952179
                ],
                [
                  -122.44805090992816,
                  37.87323765952179
                ]
              ]
            ],
            "type": "Polygon"
          }
        }
      ]
    }

  
    #When loading GeoJSON data into GDAL, only the geometry section of the Feature is needed
    json_feature = geojson_aoi['features'][0]
    json_geom = str(json_feature['geometry']) #in GeoJSON

    geom_obj = ogr.CreateGeometryFromJson(json_geom)

    sr = osr.SpatialReference()
    sr.ImportFromEPSG(4326)

    drv = ogr.GetDriverByName('ESRI Shapefile')
    feature_ds = drv.CreateDataSource("/vsimem/memory_name.shp")
    feature_layer = feature_ds.CreateLayer("layer",sr ,geom_type=ogr.wkbPolygon)

    featureDefnHeaders = feature_layer.GetLayerDefn()
    outFeature = ogr.Feature(featureDefnHeaders)

    outFeature.SetGeometry(geom_obj)
    feature_layer.CreateFeature(outFeature)     
    feature_ds.FlushCache()

    print("Beginning gdalwarp processing.")

    gdal.Warp("/home/hutch/code/output_test/sample_gee_clip3.tif", 
              gee_dataset,
              cutlineDSName="/vsimem/memory_name.shp", 
              cropToCutline=True)

    print("Processing complete.")

## Operating system

The Linux info is:

- Python 3.10.12
- GDAL 3.4.1
- Ubuntu 22.04.2 LTS

The Windows info is:

- Python 3.9.16
- GDAL 3.4.0e 
- Windows 11

## GDAL version and provenance

The GDAL used in Linux was installed via apt-get and is from the ppa:ubuntugis/ppa repository.

The GDAL used in Windows is included as part of the application ArcGIS Pro 3.1.2. Note that only the Python bindings are provided and not the command line utilities.

![image](https://github.com/OSGeo/gdal/assets/106195405/9adfd37e-0753-463e-a359-bf61474b63f4)

![image](https://github.com/OSGeo/gdal/assets/106195405/1fbf6331-01ad-4684-a7d6-e6ae49c0060e)

![image](https://github.com/OSGeo/gdal/assets/106195405/7e41bdb1-8298-45bc-86c6-515ab5e443da)

**Comment by mjhutch** [comment]
Also note that in Windows I did change the code so that the output file path was appropriate for the OS. Clearly that is not the issue here.

**Comment by rouault** [comment]
> The GDAL used in Windows is included as part of the application ArcGIS Pro 3.1.2

You mean provided by Esri ? Then we cannot do anything about that, and you'll have to see with them.

Try to replicate with community builds of GDAL, like conda-forge: https://gdal.org/download.html#conda

**Comment by rouault** [comment]
I've tried to reproduce on my Windows VM, using a GDAL master build with Conda-Forge dependencies for PROJ, GEOS, etc. , and I get the same (binary identical) correct result as on Linux.
So closing assuming this is an issue specific to the GDAL ArcGIS Pro build.

**Comment by mjhutch** [comment]
@rouault , when you reproduced in Windows, were you using GDAL 3.4.0 or 3.4.1? Thanks. Esri was asking so this is super useful info.

**Comment by rouault** [comment]
> were you using GDAL 3.4.0 or 3.4.1

no, GDAL master (3.8.0dev), but should also hopefully be working with latest stable version (3.7.1)
