### ISSUE TITLE
vsimem: Files can be created in non-existing directories but then cannot be found

### ISSUE THREAD

**Issue by dbaston** [OSGeo/gdal#8232]
## Expected behavior and actual behavior.

I can create a file in a subdirectory that does not exist:

```
from osgeo import gdal

f = gdal.VSIFOpenL("/vsimem/subdir/ok.txt", "w")
gdal.VSIFCloseL(f)
```

But then it cannot be found from a parent directory:

```
gdal.ReadDirRecursive("/vsimem")  # None
```

Although it can be found if I explicitly search the subdirectory:
```
gdal.ReadDirRecursive("/vsimem/subdir")  # ['ok.txt']
```

The subdirectory can be created after the fact, in which case the file is then found from the parent directory

```
gdal.Mkdir("/vsimem/subdir", 777)
gdal.ReadDirRecursive("/vsimem")  # ['subdir/', 'subdir/ok.txt']
```

I would expect either the creation in `subdir` to fail, or for `subdir` to be implicitly created when I create a file in it.

## GDAL version and provenance

4dcb8efd45813320f8661c71da5e54c5da55edc4

**Comment by dbaston** [comment]
Since `vsimem` does not use the `mode` argument of `Mkdir()`, I don't see a reason not to implicitly create subdirectories when creating a new file. If that sounds OK, I will try to make a PR for this change.

**Comment by rouault** [comment]
> If that sounds OK

yes, creating subdirectories sounds like the correct resolution

**Comment by dbaston** [comment]
Some driver tests that use `/vsimem` to mimic API responses rely on the ability of a path in `/vsimem` to represent _both_ a file and a directory, e.g.:

```
def test_ogr_plscenes_data_v1_catalog_paging():

    gdal.FileFromMemBuffer(
        "/vsimem/data_v1/item-types",
        '{"_links": { "_next" : "/vsimem/data_v1/item-types/page_2"}, "item_types": [ { "id": "PSScene3Band" } ] }',
    )
    gdal.FileFromMemBuffer(
        "/vsimem/data_v1/item-types/page_2",
        '{ "item_types": [ { "id": "PSScene4Band" } ] }',
    )
...

This code works because the directory `/vsimem/data_v1` is never actually created.

In some cases it may be possible to change tests to avoid needing this behavior, but in others (such as subsequent lines in the test above, I think?) the behavior is necessary to replicate the API being accessed.

Some ideas for resolving this issue while preserving the current behavior:

- Changing `VSIMemFilesystemHandler` to register directories with a trailing slash, so both `/vsimem/data_v1` (a file), and `/vsimem/data_v1/` can exist. This introduces some ugly issues like whether `/vsimem/data_v1` should resolve to `/vsimem/data_v1/` if `data_v1` exists as a directory but not a file, etc.

or

- Allowing `VSIFilesystemHandler` implementations to provide their own `ReadDirRecursive` which, for `VSIMemFilesystemHandler`, could return any paths prefixed with `/vsimem/dir_to_search/`. This doesn't fully resolve the issue, because a user working through the directory tree incrementally with `ReadDir` would still be unable to reach some branches.

Any thoughts?

**Comment by rouault** [comment]
@dbaston  Both options look too complicated for my taste. I'd prefer /vsimem/ would behave like a POSIX-like filesystem (some VSI network file systems have to deal with objects "foo" the file and "foo/" the directory, but that's really annoying) and  we rather hack the testing logic to avoid that situation. Not pretty, but not too invasive either fix for PLScenes in https://github.com/OSGeo/gdal/pull/8368 (let me know if you prefer to grab that locally, or if it can be merged)
You might need to do similar changes in other test files and in CPLHTTPFetchEx() which has a similar logic as the one directly in the PLScenes driver to turn /vsimem/ "URLs" to file request (I don't recall the reason why the PLScenes driver doesn't use that logic of CPLHTTPFetchEx(). Perhaps I had forgotten it existed...)
