### ISSUE TITLE
PDF created with TILED=YES takes very long to open in QGIS

### ISSUE THREAD

**Issue by pathmapper** [OSGeo/gdal#8233]
## Expected behavior
PDF created with creation option `TILED=YES` is opened and rendered fast in QGIS.

## Actual behavior

Such a PDF takes very long to open in QGIS.

## Steps to reproduce the problem.

1. download: [test.tif](https://share.krzn.de/alfresco/service/ecm4u/exs/kreis-viersen/share/rsMVEmV5/download/d29ya3NwYWNlOi8vU3BhY2VzU3RvcmUvNTM4N2IyNDYtOTgwMy00MzJkLTljNTgtY2QzMmU3NzE2ZjRl/test.tif)
2. run `gdal_translate -of PDF -co "TILED=YES" test.tif out.pdf`
3. drag'n'drop the PDF in QGIS

## Additional info

When running the command with debug enabled

`gdal_translate -of PDF -co "TILED=YES" test.tif out.pdf --debug on`

the log is floated with 

`CPL: CPLvsnprintf() called with unsupported formatting string: %.*f`

## Operating system

Ubuntu 22.04.3 LTS 64 bit

## GDAL version and provenance

GDAL 3.8.0dev-4dcb8efd45, released 2023/08/16 (debug build) - self built from GitHub source
used for `gdal_translate` and QGIS ([latest master](https://github.com/qgis/QGIS/commit/43105b339b4))

**Comment by pathmapper** [comment]
Here the created [out.pdf](https://share.krzn.de/alfresco/service/ecm4u/exs/kreis-viersen/share/JP5BqGi2/download/d29ya3NwYWNlOi8vU3BhY2VzU3RvcmUvMWE4OWQzMjUtZTE5Mi00NTc1LTk0NWMtM2ViNWI1YzBiMDQy/out.pdf).

**Comment by pathmapper** [comment]
The build I've experienced this issue was using Poppler (and I think also OSGeo4W is using currently Poppler, the issue was originally reported by a Windows user).

After building with PDFium the `out.pdf` is opened fast in QGIS (using this build with PDFium). I didn't recreate the PDF, so the slowness has its source on the reading side with Poppler.

Is this expected that only GDAL with PDFium can benefit from PDFs created with `TILED=YES`?

If yes, I think it's worth adding this to the docs and considering to use also PDFium for the OSGeo4W GDAL build.

**Comment by agiudiceandrea** [comment]
> considering to use also PDFium for the OSGeo4W GDAL build.

Something to let @jef-n know.

**Comment by pathmapper** [comment]
Came across this list of programs using Poppler:
https://freedesktop.org/wiki/Software/poppler/#nonexhaustivelistofprogramsusingpoppler 
(I also checked for [Evince](https://gitlab.gnome.org/GNOME/evince/-/blob/main/CONTRIBUTING.md#L57), [Okular](https://docs.kde.org/stable5/en/okular/okular/config-pdf.html) and [GIMP](https://github.com/GNOME/gimp/blob/8f0e2fd5aaf8abc0741cd46f7ceca7343a4731b3/INSTALL.in#L245) to verify)

[out.pdf](https://share.krzn.de/alfresco/service/ecm4u/exs/kreis-viersen/share/JP5BqGi2/download/d29ya3NwYWNlOi8vU3BhY2VzU3RvcmUvMWE4OWQzMjUtZTE5Mi00NTc1LTk0NWMtM2ViNWI1YzBiMDQy/out.pdf) renders very fast with Evince, Okular and GIMP, so maybe there's a way to make the combination GDAL/Poppler + QGIS also fast for such PDFs :-)

**Comment by rouault** [comment]
Fixed in https://github.com/OSGeo/gdal/pull/8278 . This gives reasonable performance in zoom-to-layer operation in QGIS
