### ISSUE TITLE
PDF - transparency not detected or lost

### ISSUE THREAD

**Issue by pathmapper** [OSGeo/gdal#8236]
## Expected behavior

`gdalinfo` shows the fourth (alpha) band for PDF because
- the PDF was created from an image with 4 bands
- [Inkscape](https://inkscape.org/) shows a transparent background for the PDF

## Actual behavior

`gdalinfo` shows only three bands for  [out.pdf](https://share.krzn.de/alfresco/service/ecm4u/exs/kreis-viersen/share/JP5BqGi2/download/d29ya3NwYWNlOi8vU3BhY2VzU3RvcmUvMWE4OWQzMjUtZTE5Mi00NTc1LTk0NWMtM2ViNWI1YzBiMDQy/out.pdf).

![image](https://github.com/OSGeo/gdal/assets/20856381/04dca18c-cfa0-423b-a707-22296591f639)

---

When the sample PDF  is drag'n'dropped in QGIS, the image is rendered with white backgound -> https://github.com/qgis/QGIS/issues/54274

## Aditional info

The PDF was created from [test.tif](https://share.krzn.de/alfresco/service/ecm4u/exs/kreis-viersen/share/rsMVEmV5/download/d29ya3NwYWNlOi8vU3BhY2VzU3RvcmUvNTM4N2IyNDYtOTgwMy00MzJkLTljNTgtY2QzMmU3NzE2ZjRl/test.tif) with 
`gdal_translate -of PDF -co "TILED=YES" test.tif out.pdf`

`gdalinfo test.tif` shows 4 bands (including alpha)

![image](https://github.com/OSGeo/gdal/assets/20856381/f15db65e-3aa2-48ee-8403-c5438a9a564c)
 

## Steps to reproduce the problem.

1. download: [out.pdf](https://share.krzn.de/alfresco/service/ecm4u/exs/kreis-viersen/share/JP5BqGi2/download/d29ya3NwYWNlOi8vU3BhY2VzU3RvcmUvMWE4OWQzMjUtZTE5Mi00NTc1LTk0NWMtM2ViNWI1YzBiMDQy/out.pdf)
2. `gdalinfo out.pdf`

## Operating system

Ubuntu 22.04.3 LTS 64 bit

## GDAL version and provenance

GDAL 3.8.0dev-4dcb8efd45, released 2023/08/16 (debug build) - self built from GitHub source

**Comment by jratike80** [comment]
There is no alpha in the PDF but there is a neatline that defines the mask:
`NEATLINE=POLYGON ((318073.407941238 5685538.3291033,318073.407941238 5682517.62052138,321200.909250806 5682517.62052138,321200.909250806 5685538.3291033,318073.407941238 5685538.3291033))`

I am not sure how GDAL and QGIS are supposed to handle the neatline.

**Comment by pathmapper** [comment]
When using a GDAL build with PDFium instead of Poppler, `gdalinfo` returns the fourth band:

<img src="https://github.com/OSGeo/gdal/assets/20856381/a16cd73f-c785-4bf8-a721-ef3eef31b8e4" width="600" />

Also when drag'n'dropping the PDF in QGIS using GDAL with PDFium creates a raster layer with 4 bands / transparency. 


So Poppler isn't able to recognized transparency by default and creates a fourth band only when using `-oo BANDS=4`?

If so, maybe adding this to the [docs](https://gdal.org/drivers/raster/pdf.html#configuration-options).

**Comment by jratike80** [comment]
Somehow the PDF driver does not behave as documented. The tiled=YES option has some side effects (no alpha), and the result is tiled even without the option.
`gdal_translate -of PDF  test.tif out3.pdf  --debug on`
yields a tiled image with 4 bands

```
Band 1 Block=1024x1024 Type=Byte, ColorInterp=Red
  Mask Flags: PER_DATASET ALPHA
Band 2 Block=1024x1024 Type=Byte, ColorInterp=Green
  Mask Flags: PER_DATASET ALPHA
Band 3 Block=1024x1024 Type=Byte, ColorInterp=Blue
  Mask Flags: PER_DATASET ALPHA
Band 4 Block=1024x1024 Type=Byte, ColorInterp=Alpha
```

My QGIS does not feel happy with that PDF, opening of it takes ages, and I am not sure if it will open ever.

**Comment by pathmapper** [comment]
Thanks @jratike80 for looking into it, Poppler seems to be the culprit, booth for the transparency and slowness issues, please see also https://github.com/OSGeo/gdal/issues/8233#issuecomment-1682862870.

It might be that all the official QGIS Windows builds are affected, as OSGeo4W seems to use Poppler and not PDFium for GDAL:
https://github.com/jef-n/OSGeo4W/blob/e22ec15185d8a6856c0bee5d3a05c612e3e30ca0/doc/build-dependencies#L29 

I wonder if there are any reasons why one would not like to build GDAL with PDFium and use it with Poppler instead. Maybe because a custom patched PDFium-Version is needed https://github.com/rouault/pdfium_build_gdal_3_8.

**Comment by pathmapper** [comment]
> gdal_translate -of PDF  test.tif out3.pdf  --debug on
> yields a tiled image with 4 bands.

@jratike80 this is strange, from where do you got the information that the PDF is tiled? Is it somewhere in the `gdalinfo`-output?

**Comment by rouault** [comment]
> Maybe because a custom patched PDFium-Version is needed https://github.com/rouault/pdfium_build_gdal_3_8.

yeah, building pdfium is kind of a pain, and it embeds a number of third-party dependencies by default (although it could probably be built against them as dependencies, but this complicates things, particularly on Windows, and I didn't go into that burden with the binaries I offer on the above respository. Just trying to make things work...). That said it indeers offers a nice speed-up compared to poppler

**Comment by jratike80** [comment]
> this is strange, from where do you got the information that the PDF is tiled? Is it somewhere in the gdalinfo-output?
It can be inferred from the block size.
`Band 1 Block=1024x1024 Type=Byte, ColorInterp=Red`
By the documentation of options TILED, BLOCKXSIZE, and BLOCKYSIZE in https://gdal.org/drivers/raster/pdf.html, the default should be untiled, and when TILED=YES is especially selected, then the default size of tiles should be 256x256. However, for me the default seems to be tiled, with 1024x1024 tiles.

**Comment by pathmapper** [comment]
> It can be inferred from the block size.

Oh, I see, thanks. One could take also the total size reported from `gdalinfo` into account and compare it with blocksize.

> default seems to be tiled, with 1024x1024 tiles

Yep, seems like the defaults for [various options](https://gdal.org/drivers/raster/pdf.html) are really depending on the data and PDF-backend used (PDFium, Poppler, PoDoFo).

**Comment by pathmapper** [comment]
The tilesize is 256x256, `gdalinfo` is not correct -> https://github.com/OSGeo/gdal/issues/8240
