### ISSUE TITLE
gdal_translate zarr to multi-band tif

### ISSUE THREAD

**Issue by wietzesuijker** [OSGeo/gdal#8237]
After finding an [example in the docs]((https://gdal.org/drivers/raster/zarr.html#:~:text=array%20to%20GeoTIFF%3A-,gdal_translate,-%27ZARR%3A%22my.zarr)), I found that multi-band zarr to tif is not working i.e. `gdal_translate data.zarr data.tif`.
For now the python alternative works fine, but a cli option for this is defo a nice to have.

creating a 3d zarr file from a few tifs
```
import rioxarray as rxr
import xarray as xr

s1 = rxr.open_rasterio("s1.tif", chunks=True)
s2 = rxr.open_rasterio("s2.tif", chunks=True)
ds = xr.concat([s1, s2], dim="band")
ds.to_zarr("data.zarr")
```

converting the zarr to a multi-band tif
```
ds_zarr = xr.open_zarr("data.zarr").__xarray_dataarray_variable__
ds_zarr.rio.to_raster("data.tif")
```

To handle the flexibility of zarr data, the gdal_translate could require the coordinates [x, y, band].

**Comment by wietzesuijker** [comment]
[docs reference](https://gdal.org/drivers/raster/zarr.html#:~:text=array%20to%20GeoTIFF%3A-,gdal_translate,-%27ZARR%3A%22my.zarr)

**Comment by jratike80** [comment]
Bands are exposed as subdatasets. This supported syntax does not look fundamentally much different than [x, y, band]
`gdal_translate 'ZARR:"my.zarr":/group/myarray:0' out.tif`
Or was your point that all the subdatasets, or a list of bands, would be converted into a multi-band TIFF with one command?

**Comment by wietzesuijker** [comment]
Thanks for your reply and exemplifying the syntax. 
Yes, as detailed, I meant multi-band support, basically `gdal_translate 'ZARR:"my.zarr":/group/myarray' out.tif`, to get a multi-band file out.

**Comment by mdsumner** [comment]
I also wondered this, why doesn't non-mdim Zarr unroll to multibands like other array formats do?

**Comment by rouault** [comment]
fix in https://github.com/OSGeo/gdal/pull/8283
