### ISSUE TITLE
gdalwarp with proj pipeline does not write CRS to header

### ISSUE THREAD

**Issue by bpurinton** [OSGeo/gdal#8242]
## Expected behavior and actual behavior.

Running this command:

```bash
gdalwarp -s_srs EPSG:32603 -t_srs EPSG:6393 source_epsg32603.tif dest_epsg6393.tif
```

And this command:

```bash
gdalwarp -ct "+proj=pipeline +step +inv +proj=utm +zone=3 +ellps=WGS84 +step +proj=aea +lat_0=50 +lon_0=-154 +lat_1=55 +lat_2=65 +x_0=0 +y_0=0 +ellps=GRS80" source_epsg32603.tif dest_epsg6393.tif
```

(with the proj pipeline passed to `-ct` gathered from this command:
```bash
projinfo -s EPSG:32603 -t EPSG:6393 -o PROJ --hide-ballpark --spatial-test intersects
```
)

Should produce the same results.

They do produce the same GeoTiff; but in the second command with the `ct` pipeline; the CRS info is not written to the `dest_*.tif` header. 

Am I misusing the `-ct` flag? Or should these equivalent operations produce the same output, including the correct CRS info in the `dest_*.tif` header when I run a `gdalinfo`?

## Operating system

macOS 13.4.1

## GDAL version and provenance

GDAL 3.6.4, released 2023/04/17 installed via `brew install gdal`

**Comment by rouault** [comment]
@bpurinton  https://github.com/OSGeo/gdal/pull/8243 should clarify the usage
