### ISSUE TITLE
Improvement suggestion for XYZ driver

### ISSUE THREAD

**Issue by Vasshus** [OSGeo/gdal#8244]
Add support for a parameter to scale Z-values when reading ASCII XYZ files.

Need a way to invert (multiply -1) Z values on read as a scale parameter. 
Example could be to add a Z scale on read in line 1084

https://github.com/OSGeo/gdal/blob/df922181ac7d2559b3d41a871c897f1cd5bc2919/frmts/xyz/xyzdataset.cpp#L1084

Then Z could also be used for feet/metric conversion. 
Of cause this can be done on the resulting raseter; However it would be really neat to have it on read.

**Comment by jratike80** [comment]
Would it be a good enough workaround to scale the values with a VRT file?
`gdal_translate positive.xyz negative.vrt -scale 0 100 0 -100`
See the `ScaleOffset` and `ScaleRatio` in the output:
```
<VRTDataset rasterXSize="3" rasterYSize="2">
  <GeoTransform> -2.5000000000000000e-01,  5.0000000000000000e-01,  0.0000000000000000e+00,  5.0000000000000000e-01,  0.0000000000000000e+00,  1.0000000000000000e+00</GeoTransform>
  <VRTRasterBand dataType="Byte" band="1">
     <ComplexSource>
      <SourceFilename relativeToVRT="1">positive.xyz</SourceFilename>
      <SourceBand>1</SourceBand>
      <SourceProperties RasterXSize="3" RasterYSize="2" DataType="Byte" BlockXSize="3" BlockYSize="1" />
      <SrcRect xOff="0" yOff="0" xSize="3" ySize="2" />
      <DstRect xOff="0" yOff="0" xSize="3" ySize="2" />
      <ScaleOffset>0</ScaleOffset>
      <ScaleRatio>-1</ScaleRatio>
    </ComplexSource>
  </VRTRasterBand>
</VRTDataset>
```

I think that what is hard is how to document that this kind of manipulations are possible to do with VRT for all formats, and to document it in such a way that even new users find the documentation.

**Comment by rouault** [comment]
With GDAL 3.7, this can be done by opening ``vrt://your.xyz?scale=0,1,0,-1`` instead of ``your.xyz``

**Comment by jratike80** [comment]
I understand, but I am also trying to think about a generic solution that works for all drivers https://gdal.org/drivers/raster/. I doubt that any raster format has scale as an open option by now.

Do you think that the kind of XYZ files are common or are they rather peculiarities? I have myself used bathymetric XYZ data where the depths below the surface had positive values. By then I considered that as a kind of data error and edited the XYZ data directly. I wish I discovered the VRT trick the. Thinking positive, using `gdal_translate positive.xyz negative.vrt -scale 0 100 0 -100` is not an especially big step in processing. But if the processing is using Python later, maybe another option could be to manipulate the arrays with Python https://gis.stackexchange.com/questions/460519/how-can-i-simulate-the-gdal-translate-scale-function-via-code-to-manually-change.

Disclaimer: I am an experienced GDAL user but not a developer so I feel that we belong to the same team.

Oh great, Even showed an ultimate solution for the problem.

**Comment by Vasshus** [comment]
Thank you both. 

"With GDAL 3.7, this can be done by opening vrt://your.xyz?scale=0,1,0,-1 instead of your.xyz" solves it.

**Comment by jratike80** [comment]
There is still one problem. I think that discovering that the vrt: connection could be the solution, and finding the documentation from https://gdal.org/drivers/raster/vrt.html#vrt-connection-string is hard for the users. Do you agree @Vasshus? Unfortunately I do not know how to help users to find this kind of general information. By experience from the mailing lists and gis.stackexchange users do not know well these options either https://gdal.org/programs/raster_common_options.html#raster-common-options.

If this question was asked on the mailing list the solution would at least be found easier in the future than from the closed GitHub issues.
