### ISSUE TITLE
OGRSpatialReference::PromoteTo3D is replace 'US survey foot' by 'metre'

### ISSUE THREAD

**Issue by aharondavid** [OSGeo/gdal#8245]
PROJ version 9.1.1
GDAL version 3.1.2
OS: Windows

**Code to reproduced:**

```
OGRSpatialReference spatialReference;
spatialReference.importFromWkt("PROJCS["NAD83(2011) / Colorado Central (ftUS)",GEOGCS["NAD83(2011)",DATUM["NAD83_National_Spatial_Reference_System_2011",SPHEROID["GRS 1980",6378137,298.257222101,AUTHORITY["EPSG","7019"]],AUTHORITY["EPSG","1116"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","6318"]],PROJECTION["Lambert_Conformal_Conic_2SP"],PARAMETER["standard_parallel_1",39.75],PARAMETER["standard_parallel_2",38.45],PARAMETER["latitude_of_origin",37.83333333333334],PARAMETER["central_meridian",-105.5],PARAMETER["false_easting",3000000],PARAMETER["false_northing",1000000],UNIT["US survey foot",0.3048006096012192,AUTHORITY["EPSG","9003"]],AXIS["X",EAST],AXIS["Y",NORTH],AUTHORITY["EPSG","6428"]]");

spatialReference.PromoteTo3D(NULL);

char* pPromtedTo3D_WKT;
spatialReference.exportToWkt(&pPromtedTo3D_WKT);

```
 **pPromtedTo3D_WKT is:**
PROJCRS["NAD83(2011) / Colorado Central (ftUS)",BASEGEOGCRS["NAD83(2011)",DATUM["NAD83 (National Spatial Reference System 2011)",ELLIPSOID["GRS 1980",6378137,298.257222101,LENGTHUNIT["metre",1]]],PRIMEM["Greenwich",0,ANGLEUNIT["degree",0.0174532925199433]],ID["EPSG",6319]],CONVERSION["unnamed",METHOD["Lambert Conic Conformal (2SP)",ID["EPSG",9802]],PARAMETER["Latitude of 1st standard parallel",39.75,ANGLEUNIT["degree",0.0174532925199433],ID["EPSG",8823]],PARAMETER["Latitude of 2nd standard parallel",38.45,ANGLEUNIT["degree",0.0174532925199433],ID["EPSG",8824]],PARAMETER["Latitude of false origin",37.8333333333333,ANGLEUNIT["degree",0.0174532925199433],ID["EPSG",8821]],PARAMETER["Longitude of false origin",-105.5,ANGLEUNIT["degree",0.0174532925199433],ID["EPSG",8822]],PARAMETER["Easting at false origin",3000000,LENGTHUNIT["US survey foot",0.304800609601219],ID["EPSG",8826]],PARAMETER["Northing at false origin",1000000,LENGTHUNIT["US survey foot",0.304800609601219],ID["EPSG",8827]]],CS[Cartesian,3],AXIS["x",east,ORDER[1],LENGTHUNIT["US survey foot",0.304800609601219,ID["EPSG",9003]]],AXIS["y",north,ORDER[2],LENGTHUNIT["US survey foot",0.304800609601219,ID["EPSG",9003]]],AXIS["ellipsoidal height (h)",up,ORDER[3],**LENGTHUNIT["metre",1,ID["EPSG",9001]]]**,REMARK["Promoted to 3D from EPSG:6428"]]

**Expected result:(see in bold)**
PROJCRS["NAD83(2011) / Colorado Central (ftUS)",BASEGEOGCRS["NAD83(2011)",DATUM["NAD83 (National Spatial Reference System 2011)",ELLIPSOID["GRS 1980",6378137,298.257222101,LENGTHUNIT["metre",1]]],PRIMEM["Greenwich",0,ANGLEUNIT["degree",0.0174532925199433]],ID["EPSG",6319]],CONVERSION["unnamed",METHOD["Lambert Conic Conformal (2SP)",ID["EPSG",9802]],PARAMETER["Latitude of 1st standard parallel",39.75,ANGLEUNIT["degree",0.0174532925199433],ID["EPSG",8823]],PARAMETER["Latitude of 2nd standard parallel",38.45,ANGLEUNIT["degree",0.0174532925199433],ID["EPSG",8824]],PARAMETER["Latitude of false origin",37.8333333333333,ANGLEUNIT["degree",0.0174532925199433],ID["EPSG",8821]],PARAMETER["Longitude of false origin",-105.5,ANGLEUNIT["degree",0.0174532925199433],ID["EPSG",8822]],PARAMETER["Easting at false origin",3000000,LENGTHUNIT["US survey foot",0.304800609601219],ID["EPSG",8826]],PARAMETER["Northing at false origin",1000000,LENGTHUNIT["US survey foot",0.304800609601219],ID["EPSG",8827]]],CS[Cartesian,3],AXIS["x",east,ORDER[1],LENGTHUNIT["US survey foot",0.304800609601219,ID["EPSG",9003]]],AXIS["y",north,ORDER[2],LENGTHUNIT["US survey foot",0.304800609601219,ID["EPSG",9003]]],AXIS["ellipsoidal height (h)",up,ORDER[3],**LENGTHUNIT["US survey foot",0.304800609601219]**,ID["EPSG",8826]],REMARK["Promoted to 3D from EPSG:6428"]]

**Comment by rouault** [comment]
That it's documented behaviour:
https://gdal.org/api/ogrspatialref.html#_CPPv4N19OGRSpatialReference11PromoteTo3DEPKc
"The new axis will be ellipsoidal height, oriented upwards, and with metre units."

**Comment by aharondavid** [comment]
Ok,
so, what can we do about that? is it going to be changed in the next GDAL\PROJ version ? 
what are the options that we have to workaround that ?

**Comment by rouault** [comment]
> is it going to be changed in the next GDAL\PROJ version ?

no

> what are the options that we have to workaround that ?

I'm pretty sure you don't want a 3D projected CRS with ellipsoidal height in US foot. Even CRS experts doubt about the meaning of what a 3D projected CRS is. It may serve as an intermediate to transform coordinates from/into a CompoundCRS with a 2D Projected CRS and a Vertical CRS based on orthometric heights. In that system, you may sometimes need to use US foot. But ellipsoidal height in US foot, I've never seen that.
