### ISSUE TITLE
add flag to gdal_translate to assign geotransform

### ISSUE THREAD

**Issue by tbonfort** [OSGeo/gdal#8248]
I would like to add an `-a_gt` option to gdal_translate in order to assign a geotransform to the output dataset in the same way that `-a_ullr` is done currently. I understand that the same behavior can be trivially done by computing the values to pass to `-a_ullr` by querying the dataset size beforehand, so this is just a small quality-of-life improvement. Would a pull request for this be accepted?

**Comment by rouault** [comment]
> Would a pull request for this be accepted?

sounds reasonable. That would be slightly more capable than -a_ullr since it could enable to pass rotating terms.
