### ISSUE TITLE
GDAL.Native and GDAL.Plugins don't copy files on publish/package

### ISSUE THREAD

**Issue by Vivelin** [OSGeo/gdal#825]
## Expected behavior and actual behavior.

When I build my project using Visual Studio, the output (`bin`) folder contains a `gdal` folder, as expected. Everything works when I run it locally.

However, upon publishing (`/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="<target directory>"`), the resulting ZIP file does _not_ contain a `bin\gdal` folder.

MSBuild log file included (diagnostic)

[msbuild.zip](https://github.com/OSGeo/gdal/files/2252859/msbuild.zip)

## Steps to reproduce the problem.

Build and publish a web project that includes the NuGet packages **GDAL.Native** and **GDAL.Plugins**. This can be done either by right-clicking the web project and selecting **Publish...** or by executing MSBuild from the command line and including the parameters mentioned above.

## Operating system

Windows 10 version 1803 (OS Build 17134.167)
Visual Studio Enterprise 2017 version 15.7.5
MSBuild 15.7.180.61344

## GDAL version and provenance

NuGet packages GDAL, GDAL.Native and GDAL.Plugins, all version 1.11.1

**Comment by rouault** [comment]
This should be reported to the people responsible of the NuGet package. This is no handled by the GDAL upstream team.

**Comment by vaughnquixote** [comment]
@Vivelin I am running into this problem now. Wondering if you ever found a resolution to this?
