### ISSUE TITLE
Upgrade from GDAL 2.04 to 3.7.1 Proj4 string issues

### ISSUE THREAD

**Issue by richy46** [OSGeo/gdal#8251]
Dear all, 

I am migrating our software from classic proj4 (GDAL 2.04) to proj9 (GDAL 3.7.1) )and I have unfortunately quite some problems, I guess with the towgs84 params. 

First problem is that epsg code 28992, when loaded in a OGRSpatialRef it gave a 7-param transform. 
With the new code not anymore and this makes it very inaccurate. But that is not the point, i made a proj4 replicating old 28992.
See below:

                   QString sETRS = "+type=crs +ellps=GRS80 +proj=longlat +towgs84=0,0,0";// 3857
                     QString sOld28992 = "+type=crs +ellps=bessel +k_0=0.9999079000 +lat_0=52.156160555556 
                   +lon_0=5.387638888889 +proj=sterea 
                   +towgs84=565.2369,50.0087,465.6580,-0.40685700,0.35073300,-1.87035000,4.0812000000 +x_0=155000.0000 
                    +y_0=463000.0000";
			
			OGRSpatialReference ogrETRS;
			auto errorCode = ogrETRS.importFromProj4(sETRS.toUtf8().data());
			//auto errorCode = ogrETRS.importFromEPSG(3857);
			assert(errorCode == 0);
			
			OGRSpatialReference old28992;
			errorCode = old28992.importFromProj4(sOld28992.toUtf8().data());
			assert(errorCode == 0);

			auto pTransform = OGRCreateCoordinateTransformation(&ogrETRS, &old28992);
			double x(4), y(52), z(0);
			int nSucces = 0;
			int nOK = pTransform->Transform(1, &x, &y, &z, &nSucces);
			assert(nOK != 0);

Results are:

  | x | 59742.015451922372
  | y | 446645.19490974909
  | z | 0.0000000000000000 

So z is not transformed.

Is there a way to make this work?

I tried several options:

`CPLSetConfigOption("OSR_ADD_TOWGS84_ON_IMPORT_FROM_EPSG", "YES");
			CPLSetConfigOption("OSR_STRIP_TOWGS84", "NO");
			CPLSetConfigOption("OSR_ADD_TOWGS84_ON_EXPORT_TO_WKT1", "YES");
			CPLSetConfigOption("PROJ_USE_PROJ4_INIT_RULES", "YES");
			CPLSetConfigOption("OGR_CT_PREFER_OFFICIAL_SRS_DEF", "YES");
`

Note that i do nor see PROJ_USE_PROJ4_INIT_RULES in the Gdal source at all, maybe it is useful?

I really need some sort of upgrade path i guess for clietns using proj4 strings. Is there not a "transform to a pipeline" function somewhere?

Thank you 
rich

**Comment by jratike80** [comment]
Please read again the beginning of the issue template

> IMPORTANT: Do NOT use GitHub to post any questions or support requests!
>            They will be closed immediately and ignored.
> 
> Questions should go to the gdal-dev mailing list at
> https://lists.osgeo.org/mailman/listinfo/gdal-dev
> or other support forums. GitHub issues are for bug
> reports and suggestions for new features.

**Comment by richy46** [comment]
thank you!

**Comment by richy46** [comment]
Hi, iam not using epsg codes at all. But in the comment i mentioned 34857, that was wrong, meant to be 4258.
