### ISSUE TITLE
Integer overflow in GDALChecksumImage

### ISSUE THREAD

**Issue by klassenjs** [OSGeo/gdal#8254]
## Expected behavior and actual behavior.

Both `gdalinfo -checksum` and calling from python result in a core dump in GDAL 3.6.2 and 3.7.1 for large integer images at 
https://github.com/OSGeo/gdal/blob/a7ee4d8eecabd08421c5d662836391839c869342/alg/gdalchecksum.cpp#L214   

In our case we have a 48062, 45760 GeoTIFF of type Byte and it would crash when iY got to 44682.  

This appears to impact GDAL 3.6.0+ for integer data types and large image sizes (total number of pixels > 2^31).

```
#0  GDALChecksumImage (hBand=0x555555626c30, nXOff=0, nYOff=0, nXSize=48062, nYSize=45760)
    at /home/jimk/apps/osgeo/gdal/src/gdal/alg/gdalchecksum.cpp:214
214                         iPrime = (nValsPerIter * (iY * nXSize + iXStart)) % 11;
(gdb) print nValsPerIter
$1 = 1
(gdb) print iY
$2 = 44682
(gdb) print nXSize
$3 = 48062
(gdb) print iXStart
$4 = 0
(gdb) print (iY * nXSize + iXStart)
$5 = -2147461012
```

```
(gdb) print 44681 * 48062
$1 = 2147458222
(gdb) print 44682 * 48062
$2 = -2147461012
(gdb) print 44682 * 48062U
$3 = 2147506284
```

## Steps to reproduce the problem.

```
gdalinfo -checksum ~/SETSM_s2s041_WV01_20230505_10200100D684B300_10200100D71EF400_2m_seg1_bitmask.tif 
Driver: GTiff/GeoTIFF
Files: /home/jimk/SETSM_s2s041_WV01_20230505_10200100D684B300_10200100D71EF400_2m_seg1_bitmask.tif
Size is 48062, 45760
...
Corner Coordinates:
Upper Left  ( -887414.000, -725540.000) ( 95d43'51.39"W, 79d26'50.20"N)
Lower Left  ( -887414.000, -817060.000) ( 92d21'48.97"W, 78d53'52.91"N)
Upper Right ( -791290.000, -725540.000) ( 92d28'55.36"W, 80d 6'47.54"N)
Lower Right ( -791290.000, -817060.000) ( 89d 4'55.38"W, 79d31'41.57"N)
Center      ( -839352.000, -771300.000) ( 92d25' 9.76"W, 79d30'19.22"N)
Band 1 Block=256x256 Type=Byte, ColorInterp=Gray
Floating point exception (core dumped)
```
Note: I don't know why it is reported as a Floating point exception. This is clearly an integer overflow and shows up as an `abort()` in `__mulvsi3` when built in Debug mode.

While this isn't a proper solution, this patch allows the checksum to be calculated successfully:

```
diff --git a/alg/gdalchecksum.cpp b/alg/gdalchecksum.cpp
index cc631881bf..751d59ba84 100644
--- a/alg/gdalchecksum.cpp
+++ b/alg/gdalchecksum.cpp
@@ -207,7 +207,7 @@ int CPL_STDCALL GDALChecksumImage(GDALRasterBandH hBand, int nXOff, int nYOff,
                     break;
                 }
                 const int xIters = nValsPerIter * nChunkActualXSize;
-                for (int iY = iYStart; iY < iYEnd; ++iY)
+                for (unsigned int iY = iYStart; iY < iYEnd; ++iY)
                 {
                     // Initialize iPrime so that it is consistent with a
                     // per full line iteration strategy
```

```
./gdalinfo -checksum ~/SETSM_s2s041_WV01_20230505_10200100D684B300_10200100D71EF400_2m_seg1_bitmask.tif 
Driver: GTiff/GeoTIFF
Files: /home/jimk/SETSM_s2s041_WV01_20230505_10200100D684B300_10200100D71EF400_2m_seg1_bitmask.tif
Size is 48062, 45760
...
Corner Coordinates:
Upper Left  ( -887414.000, -725540.000) ( 95d43'51.39"W, 79d26'50.20"N)
Lower Left  ( -887414.000, -817060.000) ( 92d21'48.97"W, 78d53'52.91"N)
Upper Right ( -791290.000, -725540.000) ( 92d28'55.36"W, 80d 6'47.54"N)
Lower Right ( -791290.000, -817060.000) ( 89d 4'55.38"W, 79d31'41.57"N)
Center      ( -839352.000, -771300.000) ( 92d25' 9.76"W, 79d30'19.22"N)
Band 1 Block=256x256 Type=Byte, ColorInterp=Gray
  Checksum=62555
  NoData Value=1
```

I suspect this still allows overflows with even larger images, and a more proper assessment of what should be signed vs unsigned and what may need to actually be uint64_t is needed here.

## Operating system

Linux gcc/amd64 (multiple: Debian/Rocky/conda/built from source)

## GDAL version and provenance

Tested with:
3.6.2 from conda
3.7.1 from git/built from source

Suspect GDAL 3.6.0 and newer.

**Comment by rouault** [comment]
Good catch. Your fix was probably correct, but I've done it different in https://github.com/OSGeo/gdal/pull/8255 to avoid relying on the fact that unsigned integer overflow is defined . I've also caught potential, very unlikely, situations where overflow could occur (like an image 2 billion pixel wide with complex data type)
