### ISSUE TITLE
gdal_retile.py fails when using some input with gaps.

### ISSUE THREAD

**Issue by mlinds** [OSGeo/gdal#8260]
## Expected behavior and actual behavior.
I expected to be able to use `gdal_retile` to retile and create pyramids of several input raster files, even if there are gaps in the input rasters. I often work with coastal data, so it is common for me to tile large piles of rasters overlapping the coastline. 

However, if none of the resulting new tiles overlap the first index shape, the script will crash and not continue building pyramids. This is because the script looks at the very first tile of the index (with name like `{rastername}_01_01.tif`).

### Illustrative example
When I try to use it on several DEMs of the netherlands, the layer 0 tiling works fine. However, at the next step it starts to build the pyramids and it raises a RuntimeError.

This is my layer 0 of retiled data, as sucessfully generated by `gdal_retile.py`

![image](https://github.com/OSGeo/gdal/assets/45837856/92873d0d-c7fd-4657-b664-3d1e0fe76d61)

Now, its time to create the pyramids. To set some values for metadata about the mosaic tile, the script looks for the tile in the upper left side, as highlighted here:

![image](https://github.com/OSGeo/gdal/assets/45837856/49146ad2-db0f-43a9-8b61-08daf10eca00)

There is no data in that index, and therefore no corresponding .tiff file. GDAL is set to use exceptions, so it raises one about not being able to find that file.

The traceback looks like:
```
Traceback (most recent call last):
  File "/home/mlinds/miniconda3/envs/default_geo_env/bin/gdal_retile.py", line 14, in <module>
    sys.exit(main(sys.argv))
             ^^^^^^^^^^^^^^
  File "/home/mlinds/miniconda3/envs/default_geo_env/lib/python3.11/site-packages/osgeo_utils/gdal_retile.py", line 1081, in main
    buildPyramid(g, minfo, dsCreatedTileIndex, g.TileWidth, g.TileHeight, g.Overlap)
  File "/home/mlinds/miniconda3/envs/default_geo_env/lib/python3.11/site-packages/osgeo_utils/gdal_retile.py", line 762, in buildPyramid
    levelMosaicInfo = mosaic_info(minfo.filename, inputDS)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mlinds/miniconda3/envs/default_geo_env/lib/python3.11/site-packages/osgeo_utils/gdal_retile.py", line 150, in __init__
    fhInputTile = self.cache.get(imgLocation)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mlinds/miniconda3/envs/default_geo_env/lib/python3.11/site-packages/osgeo_utils/gdal_retile.py", line 84, in get
    result = gdal.Open(name)
             ^^^^^^^^^^^^^^^
  File "/home/mlinds/miniconda3/envs/default_geo_env/lib/python3.11/site-packages/osgeo/gdal.py", line 5296, in Open
    return _gdal.Open(*args)
           ^^^^^^^^^^^^^^^^^
RuntimeError: ./tileOut/ahn2_5_37fn2_01_01.tif: No such file or directory
```
## Steps to reproduce the problem.

- Unzip the AHN2 DEM tiles within this zip folder: [ahn_test_data.zip](https://github.com/OSGeo/gdal/files/12420964/ahn_test_data.zip)
- cd into the directory containing the tiles, and make a `./tileout` if needed. 
- run `$ gdal_retile.py -v -levels 3 -r bilinear -targetDir ./tileOut *.tif   `

## Operating system

Ubuntu 22.04.1 LTS (WSL2)

## GDAL version and provenance

GDAL 3.7.1, released 2023/07/06

**Comment by mlinds** [comment]
I'm willing to submit a PR to fix it if there is interest - I have a working solution, and as far as I can tell it is passing all tests in my dev environment.

**Comment by rouault** [comment]
> I'm willing to submit a PR to fix it if there is interest

definitely welcome
