### ISSUE TITLE
Remove reference to no_def

### ISSUE THREAD

**Issue by richy46** [OSGeo/gdal#8265]
When loading a SpatialReference with an EPSG code, and then export to proj4 string it creates a string including +no_defs.

Since this is now obsolete it might as well be removed.

```
OGRSpatialReference ogr;
ogr.importFromEPSG(4326);
	
char* sGeoInfo;
ogr.exportToProj4(&sGeoInfo);
QString sProj4 = sGeoInfo;
OGRFree(sGeoInfo);
```

This leads to this string:

`+proj=longlat +datum=WGS84 +no_defs`

Should be without +no_defs.

Same goes for +wktext. It might pop-up here and there.

## Operating system
Windows 10 64 bit

## GDAL version and provenance
3.7.1.  sysinternalsrelease  1928.

**Comment by jratike80** [comment]
What if your customer happens to use a software that has Proj older than 6.0 https://proj.org/en/9.2/usage/differences.html#version-6-0-0?

**Comment by richy46** [comment]
Yes, I guess you have a point.

**Comment by rouault** [comment]
PROJ4 strings for CRS description is a legacy format whose use is discouraged in favor of using AUTH:CODE, WKT or PROJJSON syntax. We shouldn't try to "improve" it
