### ISSUE TITLE
how to match file name in gdalbuildvrt command tool

### ISSUE THREAD

**Issue by zyxgis** [OSGeo/gdal#8267]
GDAL  3.5
Windows 10

i have many original  images of Landsets 8 .
i want to merge the band2，band3,  band4,  band5 to one multi-band image file of each original  images.

when i use gdalbuildvrt command tool like the follow ：

```
gdalbuildvrt.exe -separate E:\LC08_L1TP_126035_20190416_20200829_02_T1_2345.xml  E:\LC08_L1TP_126035_20190416_20200829_02_T1\LC08_*[2|3|4|5].TIF

```

The error was thrown out

**Comment by jratike80** [comment]
Please read again the beginning of the issue template:

> IMPORTANT: Do NOT use GitHub to post any questions or support requests!
>            They will be closed immediately and ignored.
> 
> Questions should go to the gdal-dev mailing list at
> https://lists.osgeo.org/mailman/listinfo/gdal-dev
> or other support forums. GitHub issues are for bug
> reports and suggestions for new features.
