### ISSUE TITLE
GeoJSON to S57 no Point generated form GeoJSON

### ISSUE THREAD

**Issue by BobakMariusz** [OSGeo/gdal#8271]
## Expected behavior and actual behavior.

Current behavior
I'm converting to GeoJSON from S57 and in this way is ok but in other way from GeoJSON to S57 have a problem becuase Point is not geenrated inside new S57 file

Expected behaviour:
After Transform from GeoJSON to S57 S57 file has Geo Point

## Steps to reproduce the problem.

ogr2ogr -f GeoJSON test.json example.000  -skipfailures --Debug ON
ogr2ogr -f S57 test.000 test.json  -skipfailures --Debug ON

Logs from DEBUG:

GeoJSON: First pass: 100.00 %
GDAL: GDALOpen(test.json, this=0x5613fd42a850) succeeds as GeoJSON.
GDAL: QuietDelete(test.000) invoking Delete()
S57: Can't find attribute depwat from class smalbo:Small Bottom Object.
S57: Can't find attribute stacon from class smalbo:Small Bottom Object.
GDAL: GDALOpen(test.000, this=0x5613fd467cb0) succeeds as S57.
GDAL: GDALClose(test.000, this=0x5613fd467cb0)
GDAL: GDALDriver::Create(S57,test.000,0,0,0,Unknown,(nil))
S57: Can't find attribute depwat from class iscour:Impact Scour.
S57: Can't find attribute depwat from class smalbo:Small Bottom Object.
S57: Can't find attribute stacon from class smalbo:Small Bottom Object.
ERROR 6: CreateField() not supported by this layer.
ERROR 6: CreateField() not supported by this layer.
GDALVectorTranslate: 1 features written in layer 'smalbo'
GDAL: GDALClose(test.json, this=0x5613fd42a850)
GDAL: GDALClose(test.000, this=0x5613fd467cb0)
GDAL: In GDALDestroy - unloading GDAL shared library.

## Operating system

Fedora Linux 38 (Workstation Edition)

Linux 6.4.10-200.fc38.x86_64

## GDAL version and provenance

GDAL 3.6.4, released 2023/04/17

**Comment by rouault** [comment]
You can't expect to write S57 from a generic data source. The OGR S57 writer basically requires the input data to be formatted as S-57. Cf https://github.com/OSGeo/gdal/issues/8179  and https://gdal.org/drivers/vector/s57.html#s-57-export

**Comment by BobakMariusz** [comment]
So, does it mean that this conversion is not possible S57 -> GeoJSON -> (enrichment) -> S57 ? 
If not then which format instead GeoJSON do you recommend to be able make above workflow?

**Comment by rouault** [comment]
You need to store multiple layers, so GeoJSON isn't an option. Using GeoPackage as intermediate could perhaps work. You'll need to set the OGR_S57_OPTIONS configuration option to "RETURN_PRIMITIVES=ON,RETURN_LINKAGES=ON,LNAM_REFS=ON" on both reading and writing sides.
