### ISSUE TITLE
/vsicurl reads entire .jp2 file instead of a data chunk for a specific AOI as with the COG format

### ISSUE THREAD

**Issue by MathewNWSH** [OSGeo/gdal#8275]
## Expected behavior and actual behavior.
I expected the JP2 file to open in the same way as a COG:
[Log TIF file](https://s3.waw3-1.cloudferro.com/swift/v1/CXD/log_GTiff.txt)
Instead, GDAL is fetching the entire file instead of just the chunks covering the requested area, like so:
[Log JPEG file](https://s3.waw3-1.cloudferro.com/swift/v1/CXD/log_JPEG.txt)

## Steps to reproduce the problem.
Data (feel free to request data from my bucket):
https://s3.waw3-1.cloudferro.com/swift/v1/CXD/T36UVD_20230701T085601_TCI_10m.jp2
https://s3.waw3-1.cloudferro.com/swift/v1/CXD/T36UVD_20230701T085601_TCI_10m.tif

Docker:
```
docker run --rm -v /home/mniemyjski/Downloads/data/dckr:/dckr ghcr.io/osgeo/gdal:alpine-small-latest gdalwarp -t_srs 'EPSG:3857' -q -of JPEG --config GDAL_NUM_THREADS 1 --config CPL_DEBUG ON -te 3663787.0598015636 6899924.7342886925 3665141.729177569 6901279.403664698 /vsicurl/https://s3.waw3-1.cloudferro.com/swift/v1/CXD/T36UVD_20230701T085601_TCI_10m.jp2 /dckr/dckr2.jp2
```
```
docker run --rm -v /home/mniemyjski/Downloads/data/dckr:/dckr ghcr.io/osgeo/gdal:alpine-small-latest gdalwarp -t_srs 'EPSG:3857' -q -of GTiff --config GDAL_NUM_THREADS 1 --config CPL_DEBUG ON -te 3663787.0598015636 6899924.7342886925 3665141.729177569 6901279.403664698 /vsicurl/https://s3.waw3-1.cloudferro.com/swift/v1/CXD/T36UVD_20230701T085601_TCI_10m.jp2 /dckr/dckr.tif
```

## Operating system

Ubuntu 20.04.4 LTS and docker image ghcr.io/osgeo/gdal:alpine-small-latest (25.08.2023)

## GDAL version and provenance

GDAL 3.8.0dev-6e268bb61c95462d2704dca2ec0cad7d95d32df1, released 2023/07/20

**Comment by normanb** [comment]
I am no longer heavily involved in JPEG2000 but JPEG2000 is very suitable for network access it just requires using JPIP as in the JPIPKAK driver which I was involved in. In terms of marker segments the issue is that you have tile based JPEG2000 (the older JPT style streaming) and packet based (one large tile with PLM markers).

If not using JPIP or variations of then all that is needed is a specification for JPEG2000 that dictates TLM and PLT markers up front in the same way as COG. Similar profiles can be found with NPJE, EPJE etc for J2K.

**Comment by MathewNWSH** [comment]
> I am no longer heavily involved in JPEG2000 but JPEG2000 is very suitable for network access it just requires using JPIP as in the JPIPKAK driver which I was involved in. In terms of marker segments the issue is that you have tile based JPEG2000 (the older JPT style streaming) and packet based (one large tile with PLM markers).
> 
> If not using JPIP or variations of then all that is needed is a specification for JPEG2000 that dictates TLM and PLT markers up front in the same way as COG. Similar profiles can be found with NPJE, EPJE etc for J2K.

Hey, I've finally compiled GDAL with Kakadu support the way described here: https://github.com/OSGeo/gdal/issues/8417.

My question is: How can I use the JPIPKAKU format? From what I understand, I can't simply point to the file using it as a driver with something similar to this:
```
time gdalwarp -t_srs 'EPSG:3857' -q -of JPEG --config CPL_VSIL_CURL_CHUNK_SIZE 10485760 --config GDAL_NUM_THREADS ALL_CPUS --config CPL_DEBUG ON -te 3663787.0598015636 6899924.7342886925 3665141.729177569 6901279.403664698 /vsicurl/https://s3.waw3-1.cloudferro.com/swift/v1/CXD/T36UVD_20230701T085601_TCI_10m.jp2 dckr2.jp2
```
Best,
M

**Comment by Soille** [comment]
+ This seems to be addressed with the  TLM feature of JP2 now available in OpenJPEG.
+ See details at https://github.com/Kayrros/sentinel-2-jp2-tlm
