### ISSUE TITLE
Typo in ubuntu-full Docker file prevents building image

### ISSUE THREAD

**Issue by Blake-Loveland** [OSGeo/gdal#8279]
https://github.com/OSGeo/gdal/blob/c032069be47a0d51a6c0845226d7cca974d19816/docker/ubuntu-full/Dockerfile#L70C36-L70C36

When I try and build an image from the current ubuntu-full Docker file, I get the following error: 

```
Dockerfile:71
--------------------
  69 |            libarchive-dev${APT_ARCH_SUFFIX} \
  70 |            libaec-dev${APT_ARCH_SUFFIX}
  71 | >>>     && rm -rf /var/lib/apt/lists/*
  72 |
  73 |     # Build likbkea
--------------------
ERROR: failed to solve: dockerfile parse error on line 71: unknown instruction: &&
```

Adding a backslash to the end of line 70 fixes the error.

**Comment by harshau007** [comment]
Hii @Blake-Loveland, If you allow I would like to work on this issue !!

**Comment by Blake-Loveland** [comment]
Thank you both for your help with this.
