### ISSUE TITLE
OSM: encoding not correct

### ISSUE THREAD

**Issue by pathmapper** [OSGeo/gdal#8289]
## Expected behavior and actual behavior.

OGR uses UTF-8 as encoding for OSM data but instead it uses something else so some chars are not correctly encoded, e.g. `ö`, example:
`Astrid-Lindgren-Förderschule` becomes 
`Astrid-Lindgren-F├Ârderschule`.

Prolog:
![grafik](https://github.com/OSGeo/gdal/assets/20856381/9e2067b3-37bb-4627-85fa-a339c12aad34)

## Steps to reproduce the problem.

`ogrinfo test.osm multipolygons` (sample data: [test.zip](https://github.com/OSGeo/gdal/files/12474096/test.zip))
-> some values for `name` are not correctly encoded,e.g.

![grafik](https://github.com/OSGeo/gdal/assets/20856381/0d8c33b2-e065-4489-9b81-4518914d6585)

## Operating system

Windows 10 Version 1809

## GDAL version and provenance

3.6.4 and 3.7.1 from OSGeo4W

## Likely related issues
https://github.com/qgis/QGIS/issues/48328
https://github.com/3liz/QuickOSM/issues/369

**Comment by jratike80** [comment]
I bet that this is not a bug but what you see comes from the locale settings of your computer.

See this:

```
ogrinfo liechtenstein-latest.osm.pbf  -sql "select * from points where osm_id='32011360'"
name (String) = Vaduz Qu├ñderle

```
Then check your Windows codepage (my locale is Finnish) and change the codepage into UTF-8 (65001)
```
chcp
Active code page: 850

chcp 65001
Active code page: 65001
```

Try again
```
ogrinfo liechtenstein-latest.osm.pbf  -sql "select * from points where osm_id='32011360'"
name (String) = Vaduz Quäderle
```

**Comment by pathmapper** [comment]
> change the codepage into UTF-8 (65001)

Thanks, works for me, too.

> not a bug but what you see comes from the locale settings of your computer

The XML Prolog in the file has

`<?xml version="1.0" encoding="UTF-8"?>`

so shouldn't `UTF-8` be used regardless which system encoding is set?

**Comment by pathmapper** [comment]
When the sample file is drag'n'dropped in QGIS, the _Data source encoding_ shows `windows-1252`:

![grafik](https://github.com/OSGeo/gdal/assets/20856381/53413403-f1e8-4840-b05a-5c995ea14fc8)

I assumed this comes from ogr but maybe not...

**Comment by jratike80** [comment]
`so shouldn't UTF-8 be used regardless which system encoding is set?`
When is comes to printing text on a console, in this use case the Operating System never reads the XML header. GDAL does read it. If the console is set to use Latin 1 character set it awaits that it gets Latin 1 formulated data. When GDAL sends out UTF8 there is a conflict - UTF8 strings are shown as if they were Latin 1 strings. That can be avoided in two ways: set the console to use UTF8, or convert the output of GDAL from UTF8 into Latin 1 for example with iconv https://en.wikipedia.org/wiki/Iconv.

There may be a bug in QGIS but I could not reproduce https://github.com/qgis/QGIS/issues/48328 with QGIS 3.32.2.

**Comment by pathmapper** [comment]
Thanks, seems to be related to the used system encoding and how QGIS handles it - not a GDAL issue.
