### ISSUE TITLE
[ Feature Request ] adding min/max to VRT pixel functions

### ISSUE THREAD

**Issue by j-musial** [OSGeo/gdal#8295]
Dear GDAL,

We use a lot VRT files in our projects and we find pixel functions extremely useful (https://gdal.org/drivers/raster/vrt.html#default-pixel-functions) 

Unfortunately, there is no min/max functions that would allow to composite few raster together (e.g. max NDVI composite). These functions should exclude NAN values.

It would be beneficial for all community to have those functions implemented in GDAL.

Regards,

Jan Musial

**Comment by jratike80** [comment]
All that is possible cannot be included in the default functions, though min/max is probably something that is generally interesting. A gdal_calc solution can be found from https://gdal.org/drivers/raster/vrt.html#vrt-that-adds-2-or-more-rasters and the Add example https://gdal.org/drivers/raster/vrt.html#vrt-that-adds-2-or-more-rasters might be a starting point for writing your own Min/Max function.
