### ISSUE TITLE
Python regression 2.2 -> 2.3

### ISSUE THREAD

**Issue by hogend** [OSGeo/gdal#830]
## Problem

Valid arguments in gdal 2.2 to the TransformPoint function are not accepted anymore in gdal 2.3

## Steps to reproduce the problem.

With a projection defined by
``` python
   def getProjection( EPSGcode, inverse = False ):
       srs = osgeo.osr.SpatialReference()
       srs.ImportFromEPSG( 4326 ) # WGS84
       geodetic = srs.CloneGeogCS()

       if inverse:
           return osr.CoordinateTransformation( geodetic, srs )

       return osr.CoordinateTransformation( srs, geodetic )
```

This would produce the expected result in gdal 2.2:
```
   result = projection.TransformPoint( longitude, latitude, height )
```

In gdal 2.3, I get:
```
  File "/usr/lib64/python3.6/site-packages/osgeo/osr.py", line 942, in TransformPoint
    return _osr.CoordinateTransformation_TransformPoint(self, *args)
NotImplementedError: Wrong number or type of arguments for overloaded function 'CoordinateTransformation_TransformPoint'.
  Possible C/C++ prototypes are:
    OSRCoordinateTransformationShadow::TransformPoint(double [3])
    OSRCoordinateTransformationShadow::TransformPoint(double [3],double,double,double)
```

## Operating system

OpenSuSe Leap 15.0 - 64 bit

## GDAL version and provenance

Working: gdal-2.2.4-lp150.2.3.x86_64 from the leap-15.0 repository
Not working:  gdal-2.3.1-lp150.83.1 from obs://build.opensuse.org/Application:Geo

**Comment by rouault** [comment]
Can you provide a fully self-contained example that reproduces the issue ? osr.CoordinateTransformation.TransformPoint( x, y, z ) is tested successfully by the GDAL autotest suite, so there must be something particular in your case

**Comment by hogend** [comment]
Long time ago, I had similar issues with the TransformPoint(s) arguments and assumed they returned. My bad! After going back to 2.2.4, I re-installed 2.3.1 and the problem disappeared. May be a wrong library leftover.
Thanks for the quick response. Closing the issue.
