### ISSUE TITLE
ZARR: arraySpec view modifies dimension names

### ISSUE THREAD

**Issue by mdsumner** [OSGeo/gdal#8305]
When using `-array [name=,view=]` the output dimension name is modified to reflect the indexing. 

I.e. below, when using `"name=small_world,view=[::,0:10,::]"` the resulting dimension name is  "subset_Y_0_1_10" rather than "Y". 

When using `-subset` syntax the output name is still "Y". 

```bash
gdalmdimtranslate   gdrivers/data/small_world.tif /tmp/small_world.zarr -of Zarr
gdalmdimtranslate  /tmp/small_world.zarr -of Zarr  /tmp/small_subset.zarr -subset "Y(0, 10)"
gdalmdimtranslate  /tmp/small_world.zarr -of Zarr  /tmp/small_array.zarr -array "name=small_world,view=[::,0:10,::]"


gdalmdiminfo /tmp/small_subset.zarr | grep "small_world" -A 6
#    "small_world": {
#      "datatype": "Byte",
#     "dimensions": [
#      "/Band",
#        "/Y",
#      "/X"
#     ],

gdalmdiminfo /tmp/small_array.zarr | grep "small_world" -A 6
#    "small_world": {
#     "datatype": "Byte",
#      "dimensions": [
#        "/Band",
#        "/subset_Y_0_1_10",
#       "/X"
#      ],

```

I think both should maintain the original name "Y". 

 

## GDAL version and provenance

GDAL dev 7dec7e98b6be558ef76e1c17262994610a532573

**Comment by rouault** [comment]
I can understand that this is surprising, but this is on purpose.
When using  -array "name=small_world,view=[::,0:10,::]" , you ask to scale for one specific array. But if there were other arrays sharing the same dimensions and that you don't want to resize, we couldn't use the same dimension names.
When using  -subset "Y(0, 10)", all arrays sharing that dimension will be subsetted, hence it is safe to reuse the dimension name

**Comment by mdsumner** [comment]
ok, but ... please humour me :) ...  I thought that "name=var" was to specifically limit to one var so that the view was restricted  (what else am i missing?)

I.e. , there's no "sea_ice_fraction" or "analysis_error" array in this output and hence no "lon" or "lat" sharing to worry about: 

```
 gdalmdimtranslate  --config AWS_NO_SIGN_REQUEST YES ZARR:"/vsis3/mur-sst/zarr-v1" -of Zarr /tmp/analysed_sst.zarr -array "name=analysed_sst,view=[0,0:2,0:3]"

```

**Comment by mdsumner** [comment]
oh, it's because -array can be specified multiple times ... I'll explore more, thank you

**Comment by mdsumner** [comment]
close because not-issue
