### ISSUE TITLE
Add orginfo --usage

### ISSUE THREAD

**Issue by jidanni** [OSGeo/gdal#8316]
Add a
--usage
option,
that would print
```
Usage: ogrinfo [--help-general] [-json] [-ro] [-q] [-where restricted_where|@filename]
               [-spat xmin ymin xmax ymax] [-geomfield field] [-fid fid]
               [-sql statement|@filename] [-dialect sql_dialect] [-al] [-rl]
               [-so|-features] [-fields={YES/NO}]]
               [-geom={YES/NO/SUMMARY}] [[-oo NAME=VALUE] ...]
               [-nomd] [-listmdd] [-mdd domain|`all`]*
               [-nocount] [-noextent] [-nogeomtype] [-wkt_format WKT1|WKT2|...]
               [-fielddomain name]
               datasource_name [layer [layer ...]]
```

Currently the only way to see that printed out from the command line is
to use an unknown option triggering an error.

**Comment by rouault** [comment]
The --help option fills that need. It already existed in most utilities. Generalized to all and documented in https://github.com/OSGeo/gdal/pull/8317

**Comment by jratike80** [comment]
Does any of the utilities has a `--usage` switch? If running the command without arguments prints the usage info, who wants to do it in a longer way? But maybe it could exist as an alternative, that would not print the unnecessary FAILURE message.

```
ogrinfo
Usage: ogrinfo [--help-general] [-json] [-ro] [-q] [-where restricted_where|@filename]
               [-spat xmin ymin xmax ymax] [-geomfield field] [-fid fid]
               [-sql statement|@filename] [-dialect sql_dialect] [-al] [-rl]
               [-so|-features] [-fields={YES/NO}]]
               [-geom={YES/NO/SUMMARY}] [[-oo NAME=VALUE] ...]
               [-nomd] [-listmdd] [-mdd domain|`all`]*
               [-nocount] [-noextent] [-nogeomtype] [-wkt_format WKT1|WKT2|...]
               [-fielddomain name]
               datasource_name [layer [layer ...]]

FAILURE: No datasource specified.
```

**Comment by jratike80** [comment]
> The --help option fills that need. It already existed in most utilities
Oh, I never knew that. Maybe because it was undocumented.

**Comment by rouault** [comment]
> Does any of the utilities has a `--usage` switch?

no, --help serves that purpose

> if running the command without arguments prints the usage info, who wants to do it in a longer way?  who wants to do it in a longer way? But maybe it could exist as an alternative, that would not print the unnecessary FAILURE message.

yes, and some utilities like gdaltransform expect input from standard input and don't error out if there is no command line option.
