### ISSUE TITLE
Different results with gdaltransform 2.x vs 3.4.1

### ISSUE THREAD

**Issue by charlesritchea** [OSGeo/gdal#8350]
Here are my results with 2.x and 3.x. Can someone explain why this has changed?

```
echo -e "6720419.518191041 1878355.8391366536 1387.976960406033" | \
  gdaltransform \
    -s_srs "+proj=lcc +lat_0=33.5 +lon_0=-118 +lat_1=35.4666666666667 +lat_2=34.0333333333333 +x_0=2000000.0001016 +y_0=500000.0001016 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=us-ft +no_defs" \
    -t_srs "+proj=geocent +ellps=WGS84 +units=m +no_defs"

2.x

-4228902.87475802 -3787430.60541586 2897550.34854807

3.x

2295951.71065758 -4752631.348586 3571205.19419829
```

**Comment by jratike80** [comment]
Please read again the informative message

> 
> IMPORTANT: Do NOT use GitHub to post any questions or support requests!
>            They will be closed immediately and ignored.
> 
> Questions should go to the gdal-dev mailing list at
> https://lists.osgeo.org/mailman/listinfo/gdal-dev
> or other support forums. GitHub issues are for bug
> reports and suggestions for new features.
> 
> If you think there is an issue with coordinate order in GDAL 3.0, then it is
> likely an intended behavior. See https://github.com/OSGeo/gdal/issues/1974
> for more explanations.

Please ask your question in the mailing list. Or maybe you get answer in gis.stackexchange https://gis.stackexchange.com/questions/466468/gdaltransform-cartesian-transform-change-2-x-to-3-x

**Comment by rouault** [comment]
More a PROJ issue than a GDAL one.
In any case, I don't replicate any of your results

with ancient PROJ 5.2:

```
$ echo 6720419.518191041 1878355.8391366536 1387.976960406033 | ~/proj/install-proj-5.2/bin/cs2cs +proj=lcc +lat_0=33.5 +lon_0=-118 +lat_1=35.4666666666667 +lat_2=34.0333333333333 +x_0=2000000.0001016 +y_0=500000.0001016 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=us-ft +no_defs +to +proj=geocent +ellps=WGS84 +units=m +no_defs
-2437912.56	-4688123.98 3560710.91
```

with GDAL 3.8dev and PROJ 9.3:
```
$ echo -e "6720419.518191041 1878355.8391366536 1387.976960406033" | \
>   gdaltransform \
>     -s_srs "+proj=lcc +lat_0=33.5 +lon_0=-118 +lat_1=35.4666666666667 +lat_2=34.0333333333333 +x_0=2000000.0001016 +y_0=500000.0001016 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=us-ft +no_defs" \
>     -t_srs "+proj=geocent +ellps=WGS84 +units=m +no_defs"
-2438280.96956031 -4688832.43016417 3561252.61602986
```

with PROJ 9.3 alone :
```
$ echo 6720419.518191041 1878355.8391366536 1387.976960406033 | bin/cs2cs +proj=lcc +lat_0=33.5 +lon_0=-118 +lat_1=35.4666666666667 +lat_2=34.0333333333333 +x_0=2000000.0001016 +y_0=500000.0001016 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=us-ft +no_defs +to +proj=geocent +ellps=WGS84 +units=m +no_defs
-2438280.97	-4688832.43 3561252.62
```

with PROJ 9.3 alone :
```
$ bin/projinfo -s "+proj=lcc +lat_0=33.5 +lon_0=-118 +lat_1=35.4666666666667 +lat_2=34.0333333333333 +x_0=2000000.0001016 +y_0=500000.0001016 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=us-ft +no_defs +type=crs" -t "+proj=geocent +ellps=WGS84 +units=m +no_defs +type=crs" --single-line

PROJ string:
+proj=pipeline +step +proj=unitconvert +xy_in=us-ft +xy_out=m +step +inv +proj=lcc +lat_0=33.5 +lon_0=-118 +lat_1=35.4666666666667 +lat_2=34.0333333333333 +x_0=2000000.0001016 +y_0=500000.0001016 +ellps=GRS80 +step +proj=cart +ellps=WGS84
```

with PROJ 9.3 alone :
```
$ echo 6720419.518191041 1878355.8391366536 1387.976960406033 | bin/cct +proj=pipeline +step +proj=unitconvert +xy_in=us-ft +xy_out=m +step +inv +proj=lcc +lat_0=33.5 +lon_0=-118 +lat_1=35.4666666666667 +lat_2=34.0333333333333 +x_0=2000000.0001016 +y_0=500000.0001016 +ellps=GRS80 +step +proj=cart +ellps=WGS84
-2438280.9696  -4688832.4302  3561252.6160           inf
```

Those results seem correct to me. I presume there was a bug in the versions of PROJ you use

**Comment by jratike80** [comment]
I found GDAL 2.4.4 with Proj 6.1.1 from my computer and it gives this result

`-2437912.56201987 -4688123.97972522 3560710.90957066`

So different to the newest Proj version but not at all what you showed for 2.x. I would trust the newest versions.

**Comment by charlesritchea** [comment]
The 2.x version was a 2.2.2 docker version. Thanks for your help and sorry for abusing Github Issues

**Comment by charlesritchea** [comment]
I think it's PROJ4 :( well that's a clue
