### ISSUE TITLE
pdfobject.c fails to build with current versions of PoDoFo

### ISSUE THREAD

**Issue by berolinux** [OSGeo/gdal#8356]
## Expected behavior and actual behavior.
Expected behavior: It compiles
Actual behavior:
```
In file included from /home/bero/abf/gdal/BUILD/gdal-3.7.1/frmts/pdf/gdal_pdf.h:60:
/home/bero/abf/gdal/BUILD/gdal-3.7.1/frmts/pdf/pdfobject.h:395:13: error: no type named 'PdfVecObjects' in namespace 'PoDoFo'
    PoDoFo::PdfVecObjects &m_poObjects;
    ~~~~~~~~^
/home/bero/abf/gdal/BUILD/gdal-3.7.1/frmts/pdf/pdfobject.h:406:33: error: no type named 'PdfVecObjects' in namespace 'PoDoFo'
                        PoDoFo::PdfVecObjects &poObjects);
                        ~~~~~~~~^
2 errors generated.
```

## Steps to reproduce the problem.
1. Install PoDoFo 0.10.0 or higher (I'm using 0.10.1)
2. build gdal

## Operating system
OpenMandriva Cooker, any architecture

## GDAL version and provenance
3.7.1

**Comment by rouault** [comment]
Support for PoDoFo >= 0.10 for master / 3.8dev in https://github.com/OSGeo/gdal/pull/8360 and for 3.7 maintenance branch in https://github.com/OSGeo/gdal/pull/8361
