### ISSUE TITLE
Cannot open a file geodatabase named act_localities.gdb

### ISSUE THREAD

**Issue by jabhay** [OSGeo/gdal#8357]
## Expected behavior and actual behavior.

I expected to be able to open a file named act_localities.gdb but it returns an error message
instead.

## Steps to reproduce the problem.

Get a gdb file that can be queried using ogrinfo for example, and rename it to act_localities.gdb. Try again, and you'll get this...

Ø  ogrinfo /Users/blah/workspace/act_localities.gdb
ERROR 1: Error occurred in /tmp/gdal-20230826-93303-105et5q/gdal-3.7.1/ogr/ogrsf_frmts/openfilegdb/filegdbtable.cpp at line 714
ERROR 1: Error occurred in /tmp/gdal-20230826-93303-105et5q/gdal-3.7.1/ogr/ogrsf_frmts/openfilegdb/filegdbtable.cpp at line 714
ogrinfo failed - unable to open '/Users/blah/workspace/act_localities.gdb'.

I took a file that wasn't working and just added a one to the end of the name, and...

Ø  ogrinfo /Users/blah/workspace/act_localities1.gdb
INFO: Open of `/Users/blah/workspace/act_localities1.gdb'
      using driver `OpenFileGDB' successful.
Layer: act_localities (Multi Polygon)

## Operating system

- Mac OS Ventura (13.5.1)
- Windows 11

## GDAL version and provenance

On Mac, 3.7.1 version installed from brew
On Windows, 3.7.0 version installed by QGIS 3.28.7-Firenze

**Comment by rouault** [comment]
Fixed per 99d00fcf78e1a068589da85ba5b1c966095c4814 : "OpenFileGDB: fix opening of .gdb directories whose last component starts with 'a' and is 18 character long... (fixes #8357)"

You were particularly (un)lucky to find out this bug!
