### ISSUE TITLE
FAILURE: Unable to open datasource `*.gml with the following drivers.

### ISSUE THREAD

**Issue by dragonxtek** [OSGeo/gdal#8358]
## Expected behavior and actual behavior.

I expected to convert from gml to geojson. I downloaded a gml file from Internet Zoo http://www.topology-zoo.org/files/Napnet.gml but I got the following issue when I tried to convert:
```
FAILURE:
Unable to open datasource `Napnet.gml' with the following drivers.
```
The GML driver is not recognized.

## Steps to reproduce the problem.

"ogr2ogr -f "GeoJSON" Napnet2.geojson Napnet.gml"
Also ogrinfo doesn't work
"ogrinfo Napnet.gml"

## Operating system

Ubuntu 22.04.3 LTS 64 bits

## GDAL version and provenance

the 3.4.1+dfsg-1build4 version from apt

**Comment by jratike80** [comment]
If you look at the beginning of the downloaded file you will notice that it is not GML despite the file name.

```
graph [
  DateObtained "14/01/11"
  GeoLocation "USA"
  GeoExtent "Country"
  Network "NapNet"
  Provenance "Secondary"
  Note "ATM only? No information"
  Source "http://www.nthelp.com/images/napnet.jpg"
  Version "1.0"
  Type "COM"
  DateType "Current"
  Backbone 0
```
