### ISSUE TITLE
zarr dataset writes `.metadata` after it is closed

### ISSUE THREAD

**Issue by dbaston** [OSGeo/gdal#8365]
## Expected behavior and actual behavior.

The test `test_zarr_create_array_bad_compressor` tries to cleanup after itself with a call to `gdal.RmdirRecursive`:

```
@pytest.mark.parametrize("format", ["ZARR_V2", "ZARR_V3"])
def test_zarr_create_array_bad_compressor(format):

    try:
        ds = gdal.GetDriverByName("ZARR").CreateMultiDimensional(
            "/vsimem/test.zarr", options=["FORMAT=" + format]
        )
        assert ds is not None
        rg = ds.GetRootGroup()
        assert rg
        with gdal.quiet_errors():
            assert (
                rg.CreateMDArray(
                    "test",
                    [],
                    gdal.ExtendedDataType.Create(gdal.GDT_Byte),
                    ["COMPRESS=invalid"],
                )
                is None
            )
    finally:
        gdal.RmdirRecursive("/vsimem/test.zarr")
```

It turns out that a file `/vsimem/test.zarr/.metadata` is written at the end of the function, after the call to `gdal.RmdirRecursive`, so when the test runs a second time with `format=ZARR_V3`, `/vsimem/test.zarr/.metadata` already exists. Adding a `del ds` is not sufficient to resolve this, because `rg` also retains a reference to the `std::shared_ptr<ZarrSharedResource>` that creates the `.metadata` file.

This may be completely expected behavior -- and the test could anyway just use `tmp_vsimem` -- but given how the test is written I wondered if it was unexpected.

**Comment by rouault** [comment]
> This may be completely expected behavior

you probably also need to add a del ds, to remove the reference to the root group that it owns

Actually a "cleaner" workaround is probably to move things in an internal method, like done in other tests:

```
@pytest.mark.parametrize("format", ["ZARR_V2", "ZARR_V3"])
def test_zarr_create_array_bad_compressor(format):

    try:
     def test():
        ds = gdal.GetDriverByName("ZARR").CreateMultiDimensional(
            "/vsimem/test.zarr", options=["FORMAT=" + format]
        )
        assert ds is not None
        rg = ds.GetRootGroup()
        assert rg
        with gdal.quiet_errors():
            assert (
                rg.CreateMDArray(
                    "test",
                    [],
                    gdal.ExtendedDataType.Create(gdal.GDT_Byte),
                    ["COMPRESS=invalid"],
                )
                is None
            )

      test()

    finally:
        gdal.RmdirRecursive("/vsimem/test.zarr")
```

The multidim API has been designed to avoid issues with object lifetime (you can always use an object you got, even if its parent has gone out of scope), but there are side effects like this. Perhaps this wasn't a good idea after all, but that's too late now...

**Comment by rouault** [comment]
> you probably also need to add a del ds, to remove the reference to the root group that it owns

sorry, you need both a "del ds" and "del rg"

**Comment by dbaston** [comment]
Yes, calling both `del ds` and `del rg` causes the `.metadata` file to be written. Since it sounds like that's expected, I'll close this.
