### ISSUE TITLE
Feature Request: Implement flush for /vsis3 file handles

### ISSUE THREAD

**Issue by SpencerDWallace** [OSGeo/gdal#8370]
## Expected behavior and actual behavior.
Expected behaviour: local changes are flushed to the object store.
Actual behaviour: flush returns 0, nothing is written https://github.com/OSGeo/gdal/blob/7f18ca5ecc7fa928625aba197b10900e8119f296/port/cpl_vsil_curl.cpp#L3433-L3436
https://github.com/OSGeo/gdal/blob/7f18ca5ecc7fa928625aba197b10900e8119f296/port/cpl_vsil_curl_class.h#L716-L733
## Steps to reproduce the problem.
- open a vsis3 file with write permission
- write some content
- flush (be sad)

## Operating system

Ubuntu 20.04 64 bit

## GDAL version and provenance

3.7.1

**Comment by rouault** [comment]
I don't think this can be implemented given the reality of the REST API offered by S3:
- we use a single PUT for objects smaller than 50 MB by default. Once it has been done, no content can be appended
- or if objects are larger than 50 MB we chunk them using the InitiateMultipartUpload / UploadPart / CompleteMultipart.  A Flush() could potentially correspond to forcing a UploadPart, but it looks to me that would be a bit useless given that the effect would be visible at CompleteMultipart time, ie when you close the file, whereas in POSIX the effect of a flush() is that a reader can see the updated content once flush() has completed.
What kind of guarantee and outside effect would you expect from Flush() ?

**Comment by SpencerDWallace** [comment]
Hi @rouault thanks for getting back to me on this. I looked more into the S3 API and objects, and I can see the issue is beyond the control of a user of the API (objects are unable to be updated after creation, need to replace/overwrite object).
<br/>
> What kind of guarantee and outside effect would you expect from Flush()

It would have been for the data to be saved on the backend, visible to others interacting with the object afterward (after flush but before close). I understand this isn't doable though

Is it possible to add anything about this to the CPL documentation? VSIFOpen and VSIFFlush are mentioned to be analogous to their POSIX equivalents, but for certain network file systems update and append functionality isn't possible with VSIFOpen, and VSIFFlush doesn't flush. I could understand why you might not want to for maintainability of the documentation, however.

**Comment by rouault** [comment]
> Hi @rouault thanks for getting back to me on this. I looked more into the S3 API and objects, and I can see the issue is beyond the control of a user of the API (objects are unable to be updated after creation, need to replace/overwrite object).
> 
> > What kind of guarantee and outside effect would you expect from Flush()
> 
> It would have been for the data to be saved on the backend, visible to others interacting with the object afterward (after flush but before close). I understand this isn't doable though
> 
> Is it possible to add anything about this to the CPL documentation? VSIFOpen and VSIFFlush are mentioned to be analogous to their POSIX equivalents, but for certain network file systems update and append functionality isn't possible with VSIFOpen, and VSIFFlush doesn't flush. I could understand why you might not want to for maintainability of the documentation, however.

that's fine. Feel free to propose such documentation enhancements in https://github.com/OSGeo/gdal/blob/master/port/cpl_vsil.cpp
