### ISSUE TITLE
OGR cannot read GeoPDFs from the USGS created after 2017

### ISSUE THREAD

**Issue by 3DTOPO** [OSGeo/gdal#8372]
Apparently OGR isn’t able to read USGS GeoPDFs generated starting sometime after ~2017. I'm using GDAL 3.7.1.

For instance; it can open these versions:

[ID_Big_Baldy_20170330_TM_geo.pdf](https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/USTopo/PDF/ID/ID_Big_Baldy_20170330_TM_geo.pdf)
[ID_Big_Baldy_20131118_TM_geo.pdf](https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/USTopo/PDF/ID/ID_Big_Baldy_20131118_TM_geo.pdf)
[ID_Big_Baldy_20110114_TM_geo.pdf](https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/USTopo/PDF/ID/ID_Big_Baldy_20110114_TM_geo.pdf)

`ogrinfo ID_Big_Baldy_20170330_TM_geo.pdf`
`INFO: Open of 'ID_Big_Baldy_20170330_TM_geo.pdf'`
`using driver 'PDF' successful.`

But not these versions:
[ID_Big_Baldy_20200409_TM_geo.pdf](https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/USTopo/PDF/ID/ID_Big_Baldy_20200409_TM_geo.pdf)
[ID_Big_Baldy_20230810_TM_geo.pdf](https://prd-tnm.s3.amazonaws.com/StagedProducts/Maps/USTopo/PDF/ID/ID_Big_Baldy_20230810_TM_geo.pdf)

`ogrinfo  ID_Big_Baldy_20230810_TM_geo.pdf`
`FAILURE:`
`Unable to open datasource 'ID_Big_Baldy_20230810_TM_geo.pdf' with the following drivers.`
`  -> FITS`
`  …`
`  -> PDF`

file shows they are both version 1.6 but the newer ones use zip compression:
`ID_Big_Baldy_20170330_TM_geo.pdf: PDF document, version 1.6, 0 pages`
`ID_Big_Baldy_20200409_TM_geo.pdf: PDF document, version 1.6 (zip deflate encoded)`

I tried opening the file with Adobe Acrobat and saved it without compression. gdalinfo shows it’s still a GeoPDF but ogr2ogr will not open it.

(I used Adobe Acrobat’s “Save Optimized” and disabled “Remove Compression” from the “Clean up” stage.)

**Comment by rouault** [comment]
fix in https://github.com/OSGeo/gdal/pull/8374

**Comment by 3DTOPO** [comment]
Awesome - thank you for such a fast fix! Building from source now.

**Comment by 3DTOPO** [comment]
I can confirm it works with the 2020 version but I'm getting a new error with the 2023 version.

```
ogrinfo   ID_Big_Baldy_20230810_TM_geo.pdf            
Warning 1: organizePolygons() received a polygon with more than 100 parts. The processing may be really slow.  You can skip the processing by setting METHOD=SKIP, or only make it analyze counter-clock wise parts by setting METHOD=ONLY_CCW if you can assume that the outline of holes is counter-clock wise defined
ogrinfo failed - unable to open '/Volumes/homes2/ID_Big_Baldy_20230810_TM_geo.pdf'.
```

**Comment by rouault** [comment]
extra fix added for ID_Big_Baldy_20230810_TM_geo.pdf

**Comment by 3DTOPO** [comment]
It works! I can't thank you enough - amazing turn-around. Thank you, thank you!

**Comment by Off-Tracker** [comment]
It still cannot read current geopdf files. eg 9641-3S Pottsville 4th Edn CollarOn_2022 (at https://portal.spatial.nsw.gov.au/portal/apps/webappviewer/index.html?id=06e3c2e0de1e4efda863854048c613c6) fails to open.

**Comment by jratike80** [comment]
```
ogrinfo 9031-4S+SIX+BROTHERS.pdf --debug on
PDF: This is a raster-only PDF dataset, but it has been opened in vector-only mode
ogrinfo failed - unable to open '9031-4S+SIX+BROTHERS.pdf'.
```

Raster tools (gdalinfo, gdal_translate etc.) have no problem.
