### ISSUE TITLE
 Multi-threaded reading in gdal.translate seems does not work under certain situation

### ISSUE THREAD

**Issue by Finn-Neo** [OSGeo/gdal#8373]
Python3.8, gdal3.7.1
I use 2 threads to run crop_image(), the image used in the two threads is exactly the same, file2 is a copy of file1, code:
```
def crop_image(input_file, output_file, x_min, y_min, x_max, y_max):
    options = gdal.TranslateOptions(
        projWin=[x_min, y_max, x_max, y_min],
        format="GTiff",
        creationOptions=[
            "COMPRESS=DEFLATE",
            "TILED=YES",
            "BLOCKXSIZE=###",
            "BLOCKYSIZE=###",
            "NUM_THREADS=###",
        ],
    )
    gdal.Translate(output_file, input_file, options=options)
```
```
         crop_thread1 = threading.Thread(
            target=crop_image,
            args=(
                file1,
                output_file1,
                x_min,
                y_min,
                x_max,
                y_max,
            ),
        )
        crop_thread2 = threading.Thread(
            target=crop_image,
            args=(
                file2,
                output_file2,
                x_min,
                y_min,
                x_max,
                y_max,
            ),
        )
        crop_thread1.start()
        crop_thread2.start()
        cropthread1.join()
        crop_thread2.join()
```
I did a lot of tests, and here are three representative ones：
1. blocksize of input GeoTiff: **45947×1**, options: "NUM_THREADS=12" & "BLOCKSIZE=256","BLOCKYSIZE=256"(or DEFAULT)    
time consuming：383s

2.  blocksize of input GeoTiff: **45947×1**, options: "NUM_THREADS=12" & "BLOCKXSIZE=512","BLOCKYSIZE=512"  
time consuming：59s

3. blocksize of input GeoTiff: **256×256**, options: "NUM_THREADS=12" & "BLOCKXSIZE=256","BLOCKYSIZE=256"(or DEFAULT)
time consuming：47s
Images size in 3 tests are the same. And pixels are the same.
Note the first test, it seems the multi-threaded reading in gdal.translate does not work.

**Comment by rouault** [comment]
> 3\. Note the first test, it seems the multi-threaded reading in gdal.translate does not work.

your tests don't demonstrate this. You should also include the timings with NUM_THREADS=1 and the number of cores of your CPU.  As you are also converting 2 files in parallel and you use NUM_THREADS=12, it means that you should have at least 24 cores to get the best of GDAL. But GDAL won't scale linearly with the number of threads as there might be lock contention with the GDAL global block cache.

**Comment by Finn-Neo** [comment]
> 
Sincerely thank you for your reply! The above tests all used the same CPU, i5 12400f, with 6 cores and 12 logical processors. I have also conducted other tests, and tomorrow I will supplement some test results, including the ones you suggested. 
In addition, I will also post screenshots of the usage of some tested CPUs and hard drives.
 I have repeated the above three tests several times, and the current observed pattern is that, during Tests 2 and 3, the CPU utilization rate was 100% for a period of time, and the hard disk read and write speed showed a significant improvement. However, during Test 1, the CPU utilization rate was never able to reach 100%, mostly between 50% -60%, and the hard disk read and write speed was also particularly low

**Comment by Finn-Neo** [comment]
Al tests below convert 2 files with 2 threads, file2 is a copy of file1. In the first(second) group tests, block size of files is 45947×1, and in the third group tests, block size of files is 256×256,  the 2 files are converted from files used in the first(second) groups test.
I spelled the “block size” wrong, it is “tile size” in the screenshot, please forgive me.
### First group tests:block size:45947×1-->256×256
![第一](https://github.com/OSGeo/gdal/assets/39477671/c5900cd6-6581-4ce5-8ff4-510f26eef733)
### Secon group tests:block size:45947×1-->512×512
![第二](https://github.com/OSGeo/gdal/assets/39477671/bbb2f5e9-fd52-40ca-9963-877a8d31b53c)
### Third group tests:block size:256×256-->256×256
![第三](https://github.com/OSGeo/gdal/assets/39477671/3286031a-2a4e-4c4d-b630-e6f366f073f4)
Note that, in the first group tests, when use option "NUM_THREADS=6/12", it was much slower

**Comment by jratike80** [comment]
Have you been thinking that when the input file has a blocksize of 1x56947 then for writing out one 256x256 sized tile the program must first read worth 256x56947 pixels of data? The rest 256x256 tiles in the same tile row can be written without reading more input data. I do not know how clever the multithreaded code is, but if it happens, that the same 256x56947 pixels are read in multiple threads then the efficiency is certainly sub-optimal.
I suppose that multithreading has best possibilities to be fast when the input and output files have the same block size. However, I am not a programmer and I may be wrong.

**Comment by Finn-Neo** [comment]
> Have you been thinking that when the input file has a blocksize of 1x56947 then for writing out one 256x256 sized tile the program must first read worth 256x56947 pixels of data? The rest 256x256 tiles in the same tile row can be written without reading more input data. I do not know how clever the multithreaded code is, but if it happens, that the same 256x56947 pixels are read in multiple threads then the efficiency is certainly sub-optimal. I suppose that multithreading has best possibilities to be fast when the input and output files have the same block size. However, I am not a programmer and I may be wrong.

I have added some tests. From the results, it is not the same block size of the input and output files, the faster the speed. When the block size of the output file is 256×256, the speed is relatively slow, especially when the block size of the input file is N×1, at this time, starting multi-threading (NUM_THREADS = 6/12) will further slow down the speed.

**Comment by Finn-Neo** [comment]
![数据汇总(1)](https://github.com/OSGeo/gdal/assets/39477671/546d5c41-c7a3-4d43-9998-43b1735a3110)

**Comment by Zoulinx** [comment]
> ![数据汇总(1)](https://user-images.githubusercontent.com/39477671/266890480-546d5c41-c7a3-4d43-9998-43b1735a3110.png)

The possible reasons affecting the first set of tests could be that the default settings of the GDAL global cache are not suitable for your image size. You can try setting the GDAL_CACHEMAX to the space occupied by the input image before conducting further experiments. Additionally, if you are using GDAL warp, there are parameters such as "OPTIMIZE_SIZE" and "warp memory" that can be optimized for better performance.

**Comment by Finn-Neo** [comment]
> The possible reasons affecting the first set of tests could be that the default settings of the GDAL global cache are not suitable for your image size. You can try setting the GDAL_CACHEMAX to the space occupied by the input image before conducting further experiments. 

thank you for your reply!
I tested with  setting the GDAL_CACHEMAX bigger, and results show that, it's more slowly.......
size of  image is 1.9G, and I converted two images in parallel.
experimental configuration：
        os.environ["GDAL_CACHEMAX"] = "4096"
        NUM_THREADS=6/12
        BLOCKSIZE=256×256
        input image's block size:45946×1 / 256×256
result: 
         1.input image's block size:45946×1     NUM_THREADS=6     time consuming: 8min19s
         2.input image's block size:45946×1     NUM_THREADS=12     time consuming: 9min10s
         3.input image's block size:256×256     NUM_THREADS=6     time consuming: 1min23s
It seems that  os.environ["GDAL_CACHEMAX"] = "4096" slows down processing. In the previous test, os.environ["GDAL_CACHEMAX"] = "4096" was not used, and input image's block size: 256 × 256 NUM_THREADS = 6 time consuming: 52s(Group3 test with NUM_THREADS=6)

**Comment by Zoulinx** [comment]
> > The possible reasons affecting the first set of tests could be that the default settings of the GDAL global cache are not suitable for your image size. You can try setting the GDAL_CACHEMAX to the space occupied by the input image before conducting further experiments.
> 
> thank you for your reply! I tested with setting the GDAL_CACHEMAX bigger, and results show that, it's more slowly....... size of image is 1.9G, and I converted two images in parallel. experimental configuration： os.environ["GDAL_CACHEMAX"] = "4096" NUM_THREADS=6/12 BLOCKSIZE=256×256 input image's block size:45946×1 / 256×256 result: 1.input image's block size:45946×1 NUM_THREADS=6 time consuming: 8min19s 2.input image's block size:45946×1 NUM_THREADS=12 time consuming: 9min10s 3.input image's block size:256×256 NUM_THREADS=6 time consuming: 1min23s It seems that os.environ["GDAL_CACHEMAX"] = "4096" slows down processing. In the previous test, os.environ["GDAL_CACHEMAX"] = "4096" was not used, and input image's block size: 256 × 256 NUM_THREADS = 6 time consuming: 52s(Group3 test with NUM_THREADS=6)

Based on the size of your image, you should set os.environ["GDAL_CACHEMAX"] = "1900" instead of os.environ["GDAL_CACHEMAX"] = "4096". A GDAL_CACHEMAX value that is too large may increase memory addressing time.

**Comment by Finn-Neo** [comment]
> Based on the size of your image, you should set os.environ["GDAL_CACHEMAX"] = "1900" instead of os.environ["GDAL_CACHEMAX"] = "4096". A GDAL_CACHEMAX value that is too large may increase memory addressing time.

According to your suggestion, I tested with os.environ["GDAL_CACHEMAX"] = "1900"(this is almost the default value in my computer),but the time consuming in these situations is still long :
1.input image's block size:45946×1 NUM_THREADS=6
2.input image's block size:45946×1 NUM_THREADS=12

**Comment by Finn-Neo** [comment]
It doesn't seem to have anything to do with the value of  GDAL_CACHEMAX

**Comment by Finn-Neo** [comment]
> The possible reasons affecting the first set of tests could be that the default settings of the GDAL global cache are not suitable for your image size. 
You are right! I tested speed with GDAL_CACHEMAX=1200/600/300/200M, the results show that for the conditions of block size: 45946 × 1- > 256 × 256, image info: 45946 × 31258, 1.9G, the GDAL_CACHEMAX allocated by default is too large, and the speed is significantly improved after reducing the GDAL_CACHEMAX.
![image](https://github.com/OSGeo/gdal/assets/39477671/9ba7d440-5621-4106-b322-7dcd56f47ba4)

**Comment by Zoulinx** [comment]
> > The possible reasons affecting the first set of tests could be that the default settings of the GDAL global cache are not suitable for your image size.
> 
> You are right! Thanks to your advice, one step further from the truth. Thank you sincerely! I tested speed with GDAL_CACHEMAX=1200/600/300/200M, the results show that for the conditions of block size: 45946 × 1- > 256 × 256, image info: 45946 × 31258, 1.9G, the GDAL_CACHEMAX allocated by default is too large, and the speed is significantly improved after reducing the GDAL_CACHEMAX. The smaller the CACHE, the higher the CPU utilization ![image](https://user-images.githubusercontent.com/39477671/267230917-9ba7d440-5621-4106-b322-7dcd56f47ba4.png)


If you are interested in the performance of GDAL, I suggest using gdal_translate.exe for experimentation rather than Python bindings. This way, you can use the -debug option to output the chunk sizes allocated by GDAL for each thread and dynamically monitor the image processing speed.

**Comment by Finn-Neo** [comment]
> If you are interested in the performance of GDAL, I suggest using gdal_translate.exe for experimentation rather than Python bindings. This way, you can use the -debug option to output the chunk sizes allocated by GDAL for each thread and dynamically monitor the image processing speed.

Thanks for your suggestion!

**Comment by Finn-Neo** [comment]
### Summary
Related method: gdal.Translate
Situation:
block size: N×1 -> 256×256
option-- NUM_THREADS > = 2,the speed drops significantly.
Problem:  **_when using multiple threads to convert multiple images in parallel,_**  **_the speed drops significantly_**
Solution: 
1. Set option--BLOCKXSIZE=512 BLOCKYSIZE = 512
2. 调整GDAL_CACHEMAX(N is in MB)
```
import os
os.environ ["GDAL_CACHEMAX"] = "N" 
```
3. Convert multiple images serially using a single thread (the last resort)

I will close this issue. Have a deeper look at this issue and will open again.

**Comment by jratike80** [comment]
I suggest to pay attention also to the facts that you are writing data from multiple threads into one GeoTIFF file, that the TIFF headers and directories etc. must be kept valid, and that the output tiles are deflate compressed, that can make more difficulties on the TIFF writing side because the size of the compressed tiles varies. So it is impossible to know before hand that when a tile is processed it will be placed at byte range xxx-yyy in a TIFF. By using 512x512 sized tiles there will be 75% less tiles and writings to the headers and IDF. I believe that each thread must still update the one and only header and IDF.

A long time ago when I had to convert thousands of aerial images I started as many single-threaded GDAL processes (gdalwarp) as possible before the disk access became the bottle neck. Then I had as many CPU cores as gdalwarp processes running at about 100% load and disk usage at 100% as well. I found that faster way for processing a big batch of files than multithreading. However, that was long time ago and things may have changed.

**Comment by Finn-Neo** [comment]
> I suggest to pay attention also to the facts that you are writing data from multiple threads into one GeoTIFF file, that the TIFF headers and directories etc. must be kept valid, and that the output tiles are deflate compressed, that can make more difficulties on the TIFF writing side because the size of the compressed tiles varies. So it is impossible to know before hand that when a tile is processed it will be placed at byte range xxx-yyy in a TIFF. By using 512x512 sized tiles there will be 75% less tiles and writings to the headers and IDF. I believe that each thread must still update the one and only header and IDF.
> 
> A long time ago when I had to convert thousands of aerial images I started as many single-threaded GDAL processes (gdalwarp) as possible before the disk access became the bottle neck. Then I had as many CPU cores as gdalwarp processes running at about 100% load and disk usage at 100% as well. I found that faster way for processing a big batch of files than multithreading. However, that was long time ago and things may have changed.

Thank you for your advice, up to now, I need to sort out my thoughts. With the increase of tests, I found that things are far from as simple as I thought at the beginning, and even feel that my current ability is no longer competent. Maybe I need to do more tests, or even read the relevant source code. 
However, only by exploring and solving problems can we learn and improve.
Take care of yourself and be well!
