### ISSUE TITLE
WCS 2.0.1: server error caused by 'format' parameter in 'DescribeCoverage' requests

### ISSUE THREAD

**Issue by duswie** [OSGeo/gdal#8381]
## Expected behavior and actual behavior.
**Expected:**
gdal wcs driver should be able to open this public WCS 2.0.1 [source](https://inspire-hessen.de/raster/dgm1/ows?SERVICE=WCS&VERSION=2.0.1&REQUEST=GetCapabilities).

**Actual:**
gdalinfo fails with :
```
ERROR 1: HTTP error code : 400
ERROR 1: InvalidRequest: Parameter 'format' is not valid in request.
gdalinfo failed - unable to open 'WCS:http://inspire-hessen.de/raster/dgm1/ows?version=2.0.1&coverage=he_dgm1'.
```

## Investigation

This server error is caused by the 'format' query parameter (FORMAT=text/xml) in the DescribeCoverage request made by the wcs driver: 
`GET /raster/dgm1/ows?SERVICE=WCS&REQUEST=DescribeCoverage&VERSION=2.0.1&COVERAGEID=he_dgm1&FORMAT=text/xml`

According to [OGC® WCS 2.0 Interface Standard- Core (Figure 7)](http://www.opengis.net/doc/IS/wcs-core-2.0.1) DescribeCoverage requests must not contain a format parameter.

In my opinion the 'format' paratmer should be removed or be suppress able by option in 'DescribeCoverage' requests:
https://github.com/OSGeo/gdal/blob/7f18ca5ecc7fa928625aba197b10900e8119f296/frmts/wcs/wcsdataset201.cpp#L379

## Steps to reproduce the problem.
run `gdalinfo "WCS:http://inspire-hessen.de/raster/dgm1/ows?version=2.0.1&coverage=he_dgm1"`

## Operating system
macOS 13.5.1 (22G90) - Ventura - Intel

## GDAL version and provenance
3.7.1 from Homebrew

**Comment by jratike80** [comment]
I tried to find out if extra parameters are allowed only in some OGC standards (that would not surprise me). I have thought that if server does not know them they should be skipped. WFS 2.0 standard says:

> A server may implement additional KVP parameters that are not part of this International Standard. These are known as vendor-specific parameters. VSPs allow vendors to specify additional parameters that will enhance the results of requests. A server shall produce valid results even if the VSPs are missing, malformed or if VSPs are supplied that are not known to the server. Unknown VSPs shall be ignored.

Same idea in Catalogue Services 3.0. In WMS 1.3.0 it is put

> A WMS shall be prepared to encounter additional request parameters that are not part of this International
> Standard. In terms of producing results per this International Standard, a WMS shall not require such parameters.

It may be that WCS 2.0.1 is strict. Anyway `&format=` is never needed in DescribeCoverage.
