### ISSUE TITLE
Cannot read netCDF in zip archive

### ISSUE THREAD

**Issue by johntruckenbrodt** [OSGeo/gdal#8398]
## Expected behavior and actual behavior.

I want to read a netCDF file inside a zip archive using /vsizip/. This works well on Linux but not on Windows.  
I get the following error:
```
Error:NCpathcvt: stat=-36 (NetCDF: Invalid argument)
ERROR 4: `/vsizip/test.zip/test.nc' not recognized as a supported file format.
```
Reading the unzipped file works.

## Steps to reproduce the problem.

```
gdal_create -of netCDF -outsize 100 100 -bands 1 -burn 1 -ot Byte test.nc
zip test.zip test.nc
gdalinfo /vsizip/test.zip/test.nc
```

## Operating system

Windows 10 22H2

## GDAL version and provenance

two tests, installed from conda-forge using mambaforge:
- gdal 3.6.2 + libnetcdf 4.9.1
- gdal 3.7.2 + libnetcdf 4.9.2

**Comment by rouault** [comment]
> ## Expected behavior and actual behavior.
> 
> I want to read a netCDF file inside a zip archive using /vsizip/. This works well on Linux but not on Windows. I get the following 

yes, and this is a limitation of the libnetcdf library we can't work around on Windows. This is documented in https://gdal.org/drivers/raster/netcdf.html#vsi-virtual-file-system-api-support

**Comment by rouault** [comment]
A potential workaround is to force it to be read as HDF5 with:
``gdalinfo /vsizip/test.zip/test.nc --config GDAL_SKIP netCDF``
since the HDF5 library allows to plug the VSI file systems for all operating systems.
But you will loose some netCDF specific aspects, like georeferencing

**Comment by johntruckenbrodt** [comment]
Thanks a lot @rouault. I admit, the link details the limitations of netCDF+VSI. I read this before I opened the issue but was only looking for explicit Windows limitations. Perhaps what you wrote here would fit into the documentation?

**Comment by rouault** [comment]
Attempt at providing better docs and runtime error messages: https://github.com/OSGeo/gdal/pull/8401
