### ISSUE TITLE
MSSQLSpatial: "Conversion failed" loading features from Geopackage

### ISSUE THREAD

**Issue by simonsouth** [OSGeo/gdal#841]
## Expected behavior and actual behavior.

I'm attempting to load a set of features from a Geopackage file into a Microsoft SQL Server database, a function I understand `ogr2ogr` can perform.

On Ubuntu 16.04.5 (64-bit), however, the command fails with output like the following:

```
ERROR 1: INSERT command for new feature failed. [22008][Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Conversion failed when converting date and/or time from character string.(241)
ERROR 1: Unable to write feature 1 from layer LayerName.
ERROR 1: Terminating translation prematurely after failed
translation of layer LayerName (use -skipfailures to skip errors)
```

The issue is that the source layer includes date/time-valued attributes, which when added to the INSERT statement used to load the destination database are formatted in a manner SQL Server will not accept.

There are two underlying problems:

1. [`OGRFeatureFormatDateTimeBuffer()`](https://github.com/OSGeo/gdal/blob/64569f7069f50711b6daf53c808e1e8230a71ac8/gdal/ogr/ogrfeature.cpp#L2198), used by [`OGRFeature::GetFieldAsString()`](https://github.com/OSGeo/gdal/blob/64569f7069f50711b6daf53c808e1e8230a71ac8/gdal/ogr/ogrfeature.cpp#L2264) to generate a string value for an `OFTDateTime` field, outputs values in a format not compliant with the subset of the [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) standard most database vendors support.
1. SQL Server's datetime type, [used by the driver to represent OFTDateTime fields](https://github.com/OSGeo/gdal/blob/64569f7069f50711b6daf53c808e1e8230a71ac8/gdal/ogr/ogrsf_frmts/mssqlspatial/ogrmssqlspatialtablelayer.cpp#L837), does not store time zone information and will not accept a value that specifies a time zone offset (such as the values `OGRFeatureFormatDateTimeBuffer()` produces).

I've prepared a solution that addresses these problems by

- Modifying`OGRFeatureFormatDateTimeBuffer()` so it generates values in an unambiguous, language-neutral, ISO 8601-compliant form that has broad support across database systems, including [SQLite](https://sqlite.org/lang_datefunc.html) and [SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/functions/cast-and-convert-transact-sql?view=sql-server-2017#date-and-time-styles).
- Modifying [`OGRMSSQLSpatialTableLayer::AppendFieldValue()`](https://github.com/OSGeo/gdal/blob/64569f7069f50711b6daf53c808e1e8230a71ac8/gdal/ogr/ogrsf_frmts/mssqlspatial/ogrmssqlspatialtablelayer.cpp#L2225) so it adds an explicit `CAST` for `OFTDateTime` field values that specify time zone information, effectively removing this information so the value will be accepted by SQL Server.

I'll submit a pull request shortly.

Two additional notes:

- An alternate solution involves changing the driver to use [datetimeoffset](https://docs.microsoft.com/en-us/sql/t-sql/data-types/datetimeoffset-transact-sql?view=sql-server-2017) fields for storing date/time values, but while this solves the immediate problem these fields are [represented by the ODBC driver using a custom type](https://docs.microsoft.com/en-us/sql/relational-databases/native-client-odbc-date-time/data-type-support-for-odbc-date-and-time-improvements?view=sql-server-2017) and the resulting table cannot be read back in by `ogr2ogr`. No doubt the driver could be extended further to address this as well, but the changes would be significant and would risk creating a dependency on the ODBC driver itself (whose header files define the custom type).
- Database systems vary in their handling of date/time values that include a time zone offset, either representing them using a separate type (like SQL Server with datetimeoffset) or not recognizing them at all ([like MySQL](https://dev.mysql.com/doc/refman/8.0/en/date-and-time-literals.html#date-and-time-string-numeric-literals)). It seems to me we may eventually need to define separate `OFTDateTime` subtypes that include or do not include time zone information to be able to flexibly accommodate these systems.

## Steps to reproduce the problem.

Invoke `ogr2ogr` specifying a SQL Server database and a Geopackage file as the output and input, respectively:

```
ogr2ogr -f MSSQLSpatial "MSSQL:Driver={ODBC Driver 17 for SQL Server};Server=.;Database=DatabaseName;UID=Username;PWD=Password" ~/(…)/Geopackage.gpkg -lco "DIM=2" -progress
```

## Operating system

Ubuntu 16.04.5 64-bit (via Windows Subsystem for Linux on Windows 10)
Microsoft ODBC Driver 17 for SQL Server

## GDAL version and provenance

GDAL 2.4.0dev, compiled from the code in `master`

**Comment by rouault** [comment]
> ModifyingOGRFeatureFormatDateTimeBuffer() so it generates values in an unambiguous, language-neutral, ISO 8601-compliant form

That will break a lot of stuff in GDAL. I'd suggest to handle datetime formatting in the driver; Note that there is a OGRGetXMLDateTime() function that outputs a ISO 8601 compliant string from a OGRField* of type OFTDateTime

**Comment by simonsouth** [comment]
I see. I'll take another shot at these changes then.

**Comment by simonsouth** [comment]
I've updated the pull request with a smaller, better fix that affects only the MSSQLSpatial driver and uses `OGRGetXMLDateTime()` to format the datetime value, as you suggested.

Incidentally, `OGRGetXMLDateTime()` seems to misinterpret some values of `TZFlag`. [The documentation for `OGRFeature::SetField()`](https://gdal.org/classOGRFeature.html#a4ca0f1bca72c88fe9f881871cdc401a5) gives this description:

> nTZFlag (0=unknown, 1=localtime, 100=GMT, see data model for details)

but [`OGRGetXMLDateTime`'s implementation](https://github.com/OSGeo/gdal/blob/4bebcda797c2b2259fad7a47b7e9affc404584df/gdal/ogr/ogrutils.cpp#L1374) assumes values of both 0 and 100 indicate GMT, and treats the value 1 as specifying an actual offset.

It seems to me it should output

- The "Z" time zone specifier when TZFlag equals 100, to indicate GMT;
- _No_ time zone specifier when TZFlag equals 0 or 1, since the time zone is indeterminate in these cases; and
- A computed time zone offset for all other values.

Assuming I can identify and update any code that might depend on the function's current behaviour, would this be safe to change?

**Comment by rouault** [comment]
> would this be safe to change?

Yes, would be good to fix to be compliant with OFTDateTime specification. This might perhaps require adjusting expected results or input in a few drivers.
