### ISSUE TITLE
ogr2ogr: wrong header in CSV output

### ISSUE THREAD

**Issue by aborruso** [OSGeo/gdal#8410]
## Expected behavior and actual behavior.

To have a correct header, with a number of separators equal to the number of fields subtracted one. Then if I have 4 fields, to have 3 `,` in the heading.

## Steps to reproduce the problem.

If you run

```
ogr2ogr -s_srs  EPSG:4326 -t_srs EPSG:7853 -f CSV /vsistdout/  tmp.csv -oo X_POSSIBLE_NAMES=X -oo Y_POSSIBLE_NAMES=Y -oo Z_POSSIBLE_NAMES=Z -lco GEOMETRY=AS_XYZ -oo KEEP_GEOM_COLUMNS=NO | head -n 6
```

you get

```
X,Y,Z,ID,
48055.6427213629,8618625.39291614,36,"1"
48067.4339202844,8618637.77406654,36,"2"
48077.0812725502,8618647.90409262,36,"3"
48081.351606018,8618653.51480223,36,"4"
48151.0271593806,8618726.67592095,35,"5"
```

The header is wrong, there should be no comma at the end, it should be `X,Y,Z,ID` and not `X,Y,Z,ID,`

My sample file: <https://gist.githubusercontent.com/aborruso/5ba9304e7d6b213fa82744576ddfd89a/raw/5aed55ecc74aa038c2690a61613e12bed5e2387f/tmp.csv>

## Operating system

Debian 11

## GDAL version and provenance

I have compiled `GDAL 3.7.1, released 2023/07/06 (debug build)`.

**Comment by pigreco** [comment]
I also confirm in GDAL 3.7.2

**Comment by aborruso** [comment]
Thank you @rouault

**Comment by pigreco** [comment]
Thank you @rouault
