### ISSUE TITLE
expose GDALDriverManager::AutoLoadDrivers in C API?

### ISSUE THREAD

**Issue by tbonfort** [OSGeo/gdal#8422]
I would like to be able to register drivers compiled as plugins without having to call `GDALAllRegister()`. From the code in gdal_priv.h it would seem I can be able to do this through the C++ api, but given the name of that file I'm not sure that is the correct solution. Would it be OK to expose it in our C API? If so I can submit a PR.

**Comment by rouault** [comment]
> Would it be OK to expose it in our C API? If so I can submit a PR.

sounds reasonable. But you'd probably want the function to do all of :
```
    auto poDriverManager = GetGDALDriverManager();
    // AutoLoadDrivers is a no-op if compiled with GDAL_NO_AUTOLOAD defined.
    poDriverManager->AutoLoadDrivers();

    poDriverManager->AutoLoadPythonDrivers();

    /* -------------------------------------------------------------------- */
    /*      Deregister any drivers explicitly marked as suppressed by the   */
    /*      GDAL_SKIP environment variable.                                 */
    /* -------------------------------------------------------------------- */
    poDriverManager->AutoSkipDrivers();

    poDriverManager->ReorderDrivers();
```
