### ISSUE TITLE
Error message masks SQL dialect problem

### ISSUE THREAD

**Issue by jidanni** [OSGeo/gdal#8430]
```
$ ogr2ogr -update -f LIBKML -dialect sqlite -sql 'ALTER TABLE graticule_0 DROP COLUMN timestamp' /tmp/graticule_0.kml /tmp/graticule_0.kml
ERROR 1: In ExecuteSQL(): sqlite3_prepare_v2(ALTER TABLE graticule_0 DROP COLUMN timestamp):
  no such table: graticule_0
```

Actually, it's not a table problem, but a dialect problem:

```
$ ogr2ogr -update -f LIBKML -sql 'ALTER TABLE graticule_0 DROP COLUMN timestamp' /tmp/graticule_0.kml /tmp/graticule_0.kml
ERROR 6: DeleteField() not supported by this layer.

```

**Comment by rouault** [comment]
Regarding the SQLite dialect: https://gdal.org/user/sql_sqlite_dialect.html#sql-sqlite-dialect: "This is mainly aimed to execute SELECT statements, but, for datasources that support update, INSERT/UPDATE/DELETE statements can also be run. GDAL is internally using [the Virtual Table Mechanism of SQLite](https://sqlite.org/vtab.html) and therefore operations like ALTER TABLE are not supported. For executing ALTER TABLE or DROP TABLE use [OGR SQL dialect](https://gdal.org/user/ogr_sql_dialect.html#ogr-sql-dialect)"
