### ISSUE TITLE
Print "-mapFieldType: non altering readonly items" warning

### ISSUE THREAD

**Issue by jidanni** [OSGeo/gdal#8431]
This should print a warning that some actions cannot be completed on some read-only fields
```
$ ogr2ogr -f LIBKML k.kml m.kml -mapFieldType DateTime=string
$ ogrinfo -al -ro k.kml | grep DateTime
timestamp: DateTime (0.0)
begin: DateTime (0.0)
end: DateTime (0.0)
```
https://gdal.org/drivers/vector/libkml.html#fields ...

**Comment by rouault** [comment]
you can open a PR to ogr2ogr to indicate that the option  -mapFieldType might be without effect for some formats with a fixed set of attributes like KML.
