### ISSUE TITLE
Python bindings: Add a method to reopen a dataset

### ISSUE THREAD

**Issue by dbaston** [OSGeo/gdal#8446]
The GDAL test suite frequently creates a datasource, writes some data, and then reopens the datasource to verify that changes were made correctly. The "reopening" piece of this can be tricky, because the Python API relies on garbage collection to close a datasource. If the datasource is provided by a fixture, e.g.

```
@pytest.fixture()
def gpkg_ds(tmp_path):

    return ogr.GetDriverByName("GPKG").CreateDataSource(tmp_path / "test.gpkg")
```

then a test function using that fixture has no way to close the datasource, except by calling `Destroy()` (if available).

```
def test_gpkg(gpkg_ds):

    del gpkg_ds  # gpkg_ds is not garbage-collected because it still exists lower in the call stack
```

In some tests, I have use helper functions to reopen a dataset:

```
def reopen(ds):
    ds.FlushCache()
    dsn = ds.GetDescription()
    return gdal.Open(dsn)
```

but this requires a developer to remember to use a separate API. And not every driver implements `FlushCache`. An alternative is `ds.Destroy()`, but this does not work if the datasource was opened with `gdal.OpenEx`, because the returned `gdal.Dataset` object has no `Destroy()` method.

One idea I had is to allow `ogr.Open`, `gdal.Open`, etc. to take a datasource as an argument. This can be interpreted as "reopen", and the implementation could call the necessary functions to fully close the old dataset and reopen it, perhaps with different opening options etc.

Alternatively, we could expose `GDALClose` in SWIG. But there are already idioms of using `ds = None`, `del ds`, `ds.Destroy()` and I would be wary of introducing another.

Here is a full example to demonstrate the issue:

```
import pytest
from osgeo import ogr

ogr.DataSource.__del__ = lambda x: print(f'__del__ {x.GetDescription()}')

@pytest.fixture()
def gpkg_ds(tmp_path):

    return ogr.GetDriverByName("GPKG").CreateDataSource(tmp_path / "test.gpkg")

def test_gpkg(gpkg_ds):

    print("calling del gpkg_ds")
    del gpkg_ds
    print("done calling del gpkg_ds")
```

which outputs

```
calling del gpkg_ds
done calling del gpkg_ds
__del__ /tmp/pytest-of-dan/pytest-149/test_gpkg0/test.gpkg
```

**Comment by rouault** [comment]
> An alternative is `ds.Destroy()`, but this does not work if the datasource was opened with `gdal.OpenEx`, because the returned `gdal.Dataset` object has no `Destroy()` method.

That should likely be the resolution: implement Destroy() (or close()) for gdal.Dataset to make it call GDALClose().  del() or setting to None are not reliable. FlushCache() generally doesn't result in the underlying file to be closed.

I would rather see the reopen() method as belonging to pymod/gdaltest.py rather than the bindings themselves. It would be a bit dangerous to have Open() accept an existing dataset and closing it

**Comment by rcoup** [comment]
>  I don't know of any other Python library that works like GDAL's bindings do, with respect to closing open file connections. GDAL is a weird outlier and the existing idioms are not worth preserving.

I agree, I think we should be moving towards a standard `.close()` model, separated from gc. Most Python libraries that implement resources do close() == cleanup, and subsequent access throws errors (eg: "I/O operation on closed file."). And likely leaning more heavily on `with()` as well for context.

I mean, to address [Python crashes if you use an object after deleting an object it has a relationship with](https://gdal.org/api/python_gotchas.html#python-crashes-if-you-use-an-object-after-deleting-an-object-it-has-a-relationship-with) we _fundamentally_ need to separate the python objects from the native objects, make sure the python objects know their owner, and can check whether the native owner is still valid?

> It would be a bit dangerous to have Open() accept an existing dataset and closing it.

Strongly agree. If `Open()` accepted an existing dataset and _didn't_ close it (ie. opening a duplicate) that would be fine from an API point of view, but seems dangerous from a "helping users do the right thing" perspective.

> I would rather see the reopen() method as belonging to pymod/gdaltest.py rather than the bindings themselves. 

This makes more sense to me, it's an implementation helper for our tests, but is it something users need?

**Comment by dbaston** [comment]
Yes, my idea with `Open` was clearly too focused on my unusual use case. Let's scrap it. I've opened a separate PR for exposing `GDALClose`: https://github.com/OSGeo/gdal/pull/8454

**Comment by dbaston** [comment]
> I mean, to address [Python crashes if you use an object after deleting an object it has a relationship with](https://gdal.org/api/python_gotchas.html#python-crashes-if-you-use-an-object-after-deleting-an-object-it-has-a-relationship-with) we fundamentally need to separate the python objects from the native objects, make sure the python objects know their owner, and can check whether the native owner is still valid?

Most of the common errors here have been addressed, though some remain (a RAT or color table can still be orphaned in a way that causes a crash.) The doc needs updating.

The approach taken so far is to have owning objects invalidate their subordinates when they are destroyed, rather than objects checking if their owner is valid.
