### ISSUE TITLE
gdalsrsinfo fails to read EPSG code stated in prj file 

### ISSUE THREAD

**Issue by MichiHo** [OSGeo/gdal#8452]
## Expected behavior and actual behavior.

On .prj files (as part of shapefiles) which state `AUTHORITY["EPSG":"<number>"]` as direct child of the root element (e.g. `GEOGCS`) and also contain information which is coherent with the given code, the `gdalsrsinfo -e` call gives multiple hypotheses. I would expect it to acknowledge the authority given in the prj file and give back the code from there (EPSG:4326 in the case of the file below).

To my knowledge the prj files do not follow any WKT format standardized by the OGC but instead their own variant, which is not clearly defined. The AUTHORITY field was observed in some, but by far not all, shapefiles available to me.

## Steps to reproduce the problem.

Run `gdalsrsinfo -e file.prj` on "file.prj" with the given contents:

```
GEOGCS["WGS 84", 
    DATUM["World Geodetic System 1984", 
        SPHEROID["WGS 84", 6378137.0, 298.257223563, 
            AUTHORITY["EPSG","7030"]], 
        AUTHORITY["EPSG","6326"]], 
    PRIMEM["Greenwich", 0.0, 
        AUTHORITY["EPSG","8901"]], 
    UNIT["degree", 0.017453292519943295], 
    AXIS["Geodetic longitude", EAST], 
    AXIS["Geodetic latitude", NORTH], 
    AUTHORITY["EPSG","4326"]]
```

## Operating system

MacOS Ventura 13.5.2

## GDAL version and provenance

GDAL 3.7.1, released 2023/07/06

**Comment by rouault** [comment]
The issue here is that WKT definition is not consistent with the official EPSG:4326 definition since the WKT exposes a longitude, latitude axis order whereas EPSG:4326 is latitude, longitude.  In the context of shapefiles, where the axis order is always long, lat for geographic, this shouldn't matter too much, but this is enough to confuse GDAL (and PROJ) logic. If one wanted to recognize that .prj, a specific hack/logic would have to be added

Shapefile .proj should contain ESRI WKT string, which contain no AXIS nor AUTHORITY. This should be ``GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]]``

**Comment by MichiHo** [comment]
Thank you for your quick replies!

What confuses me, is that ogr2ogr accepts EPSG:4326 as -s_srs for this file and produces correct results, even though you say that the .prj file and the context of shapefiles imply long,lat which is not EPSG:4326. Does the shapefile driver implicitly apply this knowledge about shapefiles and get confused if it's stated _explicitly_ in the .prj?

**Comment by rouault** [comment]
> Does the shapefile driver implicitly apply this knowledge about shapefiles and get confused if it's stated _explicitly_ in the .prj?

yes

**Comment by jratike80** [comment]
Ogr2ogr with `-s_srs` would work even without any .prj because it is actually a manual override. By using the argument You tell that source data is actually in EPSG:4326 even it the metadata of the dataset claims something else - or is unknows, that is the most common use case.

**Comment by MichiHo** [comment]
Interesting! So I guess the shapefile I encountered is really just a weird format, probably produced by, and aimed at, some specific non-ESRI software? I heard that there can be quite a few "flavors" around. The question is whether a fix for this particular one would be worthwhile, which probably depends on how prevalent it is.

**Comment by rouault** [comment]
fix for shapefile driver only (not for gdalsrsinfo) in https://github.com/OSGeo/gdal/pull/8457
