### ISSUE TITLE
Asterisks not explained in usage messages

### ISSUE THREAD

**Issue by jidanni** [OSGeo/gdal#8463]
```
$ gdal_grid
Usage: gdal_grid [--help-general]
    [-oo NAME=VALUE]* #Such asterisks not explained anywhere in such usage messages
```

**Comment by jratike80** [comment]
Are the other conventions explained somewhere? The synopsis is following the Linux man page convention, with a slight difference that asterisk `*` is used to tell that the argument can be repeated. In for example in 
https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html an ellipse `...` is used instead.  For my mind  the ellipses are more hard to read.
By having a look at the synopsis of a few GDAL utilities it seems that GDAL is using ellipse when a value of an argument can be repeated.

**Comment by jidanni** [comment]
dot-dot-dot seems standard. Asterisk would seem reserved as a way to add a note to the bottom. Else there would be no way I suppose.

**Comment by jratike80** [comment]
What error messages? The error message with your command is at the bottom,
`FAILURE: No input file specified.`
The beginning of the output is the same that comes, without error, with 
`gdal_grid --help`
