### ISSUE TITLE
gdal_translate.rst changes

### ISSUE THREAD

**Issue by jidanni** [OSGeo/gdal#8467]
Please apply https://github.com/OSGeo/gdal/commit/2617996e07935a2c4d8e10a6e9a92e48f4ed1e83
Sometimes GitHub things work, sometimes they don't.
![20230924T071610](https://github.com/OSGeo/gdal/assets/1230959/3db39373-fbcc-459d-ad3a-7fdee8dd8f15)
Yes, even though we see 
> You’re making changes in a project you don’t have write access to. Submitting a change will write it to a new branch in your fork jidanni/gdal, so you can send a pull request.

**Comment by rouault** [comment]
cherry-picked and pushed to master
