### ISSUE TITLE
Are data with "PIXELTYPE=SIGNEDBYTE" supported?

### ISSUE THREAD

**Issue by nicolasvila** [OSGeo/gdal#8471]
## Expected behavior and actual behavior.

I'm not sure this is a GDAL issue but I'm facing cascading issue with RasterIO and Titiler while handling images that have this particular pixel type. Seems that the image bands are considered to have different pixels' types. According to the metadata this is obviously not the case as we can see in the example below.
I apologize if this has to be taken into account at the higher (application)  level.

This may be related to this issue: https://github.com/OSGeo/gdal/issues/2298

## Steps to reproduce the problem.

```text
gdalinfo IMG_COG.TIFF|grep -A3 -i structure

Image Structure Metadata:
  COMPRESSION=LZW
  INTERLEAVE=PIXEL
  LAYOUT=COG
--
  Image Structure Metadata:
    PIXELTYPE=SIGNEDBYTE
Band 2 Block=512x512 Type=Byte, ColorInterp=Green
  Overviews: 915x915, 458x458, 229x229
  Image Structure Metadata:
    PIXELTYPE=SIGNEDBYTE
Band 3 Block=512x512 Type=Byte, ColorInterp=Blue
  Overviews: 915x915, 458x458, 229x229
  Image Structure Metadata:
    PIXELTYPE=SIGNEDBYTE
```

## Operating system

Ubuntu 22.04 64 bit

## GDAL version and provenance

GDAL 3.6.4, released 2023/04/17

**Comment by jratike80** [comment]
Please, send questions to the gdal-dev mailing list, not into bug tracker.

I do not quite understand this "Seems that the image bands are considered to have different pixels' types". Who considers so? Clarify that.

Maybe this information is useful for you https://gdal.org/development/rfc/rfc87_signed_int8.html

**Comment by rouault** [comment]
As mentioned by @jratike80 , signed byte has been seriously revamped in GDAL 3.7 per https://gdal.org/development/rfc/rfc87_signed_int8.html . As you use GDAL 3.6, it will behave significantly different. The best is to update to 3.7, as we don't support 3.6 anymore. Closing
