### ISSUE TITLE
VSIReadDirRecursive() behaves non-recursively with a trailing slash

### ISSUE THREAD

**Issue by craigds** [OSGeo/gdal#8474]
## Expected behavior and actual behavior.

`VSIReadDirRecursive` should list directories recursively, regardless of whether the path has a trailing slash or not.

## Steps to reproduce the problem.

```bash
$ mkdir a b
$ touch a/file.txt b/file.txt
$ zip -r myzip.zip a b
```

```python
>>> from osgeo import gdal

>>> gdal.ReadDirRecursive('/vsizip/myzip.zip')
['a/', 'a/file.txt', 'b/', 'b/file.txt']

>>> gdal.ReadDirRecursive('/vsizip/myzip.zip/')
['a', 'b']
```

## Operating system

Ubuntu 22.04.3 LTS

## GDAL version and provenance

GDAL 3.6, built from our fork based on `release/3.6` @ ebb81fc356d7d56519061d63de305fef605a6cc1

**Comment by craigds** [comment]
This actually worked correctly (both invocations behaved recursively) in our older fork based on 3.2.x:

```python
>>> from osgeo import gdal
>>> gdal.ReadDirRecursive('/vsizip/myzip.zip')
['a/', 'a/file.txt', 'b/', 'b/file.txt']
>>> gdal.ReadDirRecursive('/vsizip/myzip.zip/')
['a/', 'a/file.txt', 'b/', 'b/file.txt']
```

I won't attempt to bisect it from such a huge log though :)

**Comment by rouault** [comment]
> This actually worked correctly (both invocations behaved recursively) in our older fork based on 3.2.x:

yes, the implementation of ReadDirRecursive() was completely rewritten

Fix in https://github.com/OSGeo/gdal/pull/8475

**Comment by jratike80** [comment]
May be off-topic, but ddalinfo does not like the trailing slash

```
gdalinfo /vsizip/ab.zip/
ERROR 6: Support only 1 file in archive file ab.zip when no explicit in-archive filename is specified
You could try one of the following :
  /vsizip/{ab.zip}/a
  /vsizip/{ab.zip}/a/a.txt
  /vsizip/{ab.zip}/b
  /vsizip/{ab.zip}/b/b.txt

gdalinfo failed - unable to open '/vsizip/ab.zip/'.
Unable to open source `/vsizip/ab.zip/' directly.
The archive contains several files:
       /vsizip/ab.zip//a
       /vsizip/ab.zip//b
```
