### ISSUE TITLE
gdal_rasterize: symbol lookup error: gdal_rasterize: undefined symbol: CheckExtensionConsistency

### ISSUE THREAD

**Issue by matthiasdemuzere** [OSGeo/gdal#848]
## Expected behavior and actual behavior.

Using QGIS (I tested versions 2.18, 3.2 and 3.3), I wanted to rasterize a vector file. This procedure calls gdal_rasterize. Yet when using it, I get the error message: 'gdal_rasterize: symbol lookup error: gdal_rasterize: undefined symbol: CheckExtensionConsistency'. When trying this on the command line, I get the same error.

## Steps to reproduce the problem.

gdal_rasterize

## Operating system

Ubuntu 18.04 64 bit

## GDAL version and provenance

GDAL 2.3.1, released 2018/06/22
From https://qgis.org/ubuntu-nightly
Note that I also sourced from https://qgis.org/unbuntu-ltr and https://qgis.org/ubuntu, with the same result.

Unfortunately I do not manage to downgrade to a lower gdal version?

**Comment by rouault** [comment]
This sounds like a mix of GDAL versions, perhaps coming from different repository. Try to clean up things.
