### ISSUE TITLE
when to SetAxisMappingStrategy

### ISSUE THREAD

**Issue by FriendsOfJustic** [OSGeo/gdal#8487]
"pipesectionRoute": "LINESTRING (118.9226 38.0881, 118.9054 38.0831)"
i have a wkt in a string type "_pipesectionRoute" which it srid is 4326 ,and i want to import a geom from wkt , then transform it to 3857
so the right way to trans is below?

```cpp
     OGRSpatialReference* proj = new OGRSpatialReference;
      proj->importFromEPSG(4326);
      OGRRegisterAll();
      OGRGeometry* geom = nullptr;
      auto err = OGRGeometryFactory::createFromWkt(&(_pipesectionRoute[0]),
                                                   proj, &geom);
      cout << geom->getSpatialReference()->GetName() << endl;
      OGRSpatialReference* proj_tran = new OGRSpatialReference;
      proj_tran->importFromEPSG(3857);
      proj->SetAxisMappingStrategy(OAMS_TRADITIONAL_GIS_ORDER);
      OGRCoordinateTransformation* transform =
          OGRCreateCoordinateTransformation(proj, proj_tran);
      geom->transform(transform);
      geom->assignSpatialReference(proj_tran);
```

**Comment by jratike80** [comment]
You have not found a bug in GDAL so please respect our ways to communicate:

> IMPORTANT: Do NOT use GitHub to post any questions or support requests!
>            They will be closed immediately and ignored.
> 
> Questions should go to the gdal-dev mailing list at
> https://lists.osgeo.org/mailman/listinfo/gdal-dev
> or other support forums. GitHub issues are for bug
> reports and suggestions for new features.
