### ISSUE TITLE
ogr2ogr osm to geojson Too many nodes referenced in way

### ISSUE THREAD

**Issue by andrewharvey** [OSGeo/gdal#849]
## Expected behavior and actual behavior.

I expect to be able to convert my .osm file as saved from JOSM into a geojson.

## Steps to reproduce the problem.

    ogr2ogr -f 'GeoJSON' -t_srs 'EPSG:4326' --config OSM_USE_CUSTOM_INDEXING NO trail1.geojson trail1.osm lines

It gets about 70% complete then stops with `ERROR 1: Too many nodes referenced in way`

[trail1.txt](https://github.com/OSGeo/gdal/files/2285416/trail1.txt)

## Operating system

For example: Debian unstable

## GDAL version and provenance

GDAL 2.3.1, released 2018/06/22 from http://packages.debian.org/gdal-bin

**Comment by andrewharvey** [comment]
Thank you so much @rouault. Reading up at https://help.openstreetmap.org/questions/365/is-there-a-limit-on-the-number-of-nodes-in-a-way it appears this 2000 node per way limit [was introduced with the 0.6 API](https://wiki.openstreetmap.org/wiki/API_changes_between_v0.5_and_v0.6#Ways). It is documented in the [the `/capabilities` api call](https://api.openstreetmap.org/api/0.6/capabilities).

In my opinion this is a limit of what the API will accept, and is not part of the file format itself, so it would be nice that when going from OSM XML to something else no limit was enforced at all.

**Comment by jratike80** [comment]
In my opinion if you will some day meet a way with more than 10000 nodes it would be kind for the OpenStreetMap project to go and split it into pieces of less than 2000 nodes.

**Comment by andrewharvey** [comment]
> In my opinion if you will some day meet a way with more than 10000 nodes it would be kind for the OpenStreetMap project to go and split it into pieces of less than 2000 nodes.

Yeah but sometimes I work with `.osm` files (OSM XML) which aren't from or intended to be used in OpenStreetMap or its APIs.

It's the native file format for JOSM, which people use as a geospatial data editor for non-openstreetmap.org data.

**Comment by andrewharvey** [comment]
> In my opinion if you will some day meet a way with more than 10000 nodes it would be kind for the OpenStreetMap project to go and split it into pieces of less than 2000 nodes.

Just encountered this again now. Using JOSM as a spatial data editor, not in any way related to OSM data or the OSM API.

**Comment by andrewharvey** [comment]
As a workaround I managed to use https://github.com/tyrasd/osmtogeojson, but it's still a shame that OGR has this limitation.
