### ISSUE TITLE
`OGRGeometry::getSpatialReference`'s return type is inconsistent between GDAL versions

### ISSUE THREAD

**Issue by a-gn** [OSGeo/gdal#8493]
## Expected behavior and actual behavior.

According to [the current documentation](https://gdal.org/doxygen/classOGRGeometry.html#a66a53c103e37c6d1ead00d2d74586ddd), `OGRGeometry::getSpatialReference` returns `OGRSpatialReference *`.

In 3.6.0, it [returned the correct type](https://github.com/OSGeo/gdal/blob/b77481ccf9f84a708fd37a13a7e0a3384fdf1622/ogr/ogr_geometry.h#L489).

But in 3.7.1, it [actually returns `const OGRSpatialReference *`](https://github.com/OSGeo/gdal/blob/68da5257b139d4d80162cf83fdb8c6d26ead412f/ogr/ogr_geometry.h#L500).

This also prevents the resulting `const OGRSpatialReference *` from being passed to [`GDALDataset::CreateLayer`](https://gdal.org/doxygen/classGDALDataset.html#afec5fd0fffddbdf530cd6294caa66a7d), which expects an `OGRSpatialReference *`.

## Steps to reproduce the problem.

Try to build a program containing the following code (disregard the `nullptr`, the problem also happens with a valid `geom`):

```cpp
OGRGeometry* geom(nullptr);
OGRSpatialReference * spatial_ref = geom->getSpatialReference();
```
In GDAL 3.6.0, it compiled. In GDAL 3.7.1, it fails because we can't assign a `const T*` to a `T*`.

## Operating system

Windows 11 64 bits.

## GDAL version and provenance

GDAL 3.7.1 from [osgeo4w](https://trac.osgeo.org/osgeo4w/).

**Comment by jratike80** [comment]
It looks that the change happened here https://github.com/OSGeo/gdal/commit/dc32afef5e9a9a232ab6789573da67663a00ec60 and it is mentioned in the migration guide.
Does it mean that the documentation is outdated?

**Comment by a-gn** [comment]
> It looks that the change happened here [dc32afe](https://github.com/OSGeo/gdal/commit/dc32afef5e9a9a232ab6789573da67663a00ec60) and it is mentioned in the migration guide. Does it mean that the documentation is outdated?

I'm OK with updating but is it safe to `const_cast` the `const` qualifier away to pass that value to `CreateLayer`?

[The `getSpatialReference` docs](https://gdal.org/doxygen/classOGRGeometry.html#a66a53c103e37c6d1ead00d2d74586ddd) say:

> The object may be shared with many geometry objects, and should not be modified.

[The `CreateLayer` docs](https://gdal.org/doxygen/classGDALDataset.html#afec5fd0fffddbdf530cd6294caa66a7d) say:

> The driver might only increase the reference counter of the object to take ownership, and not make a full copy

Does that mean that `CreateLayer(..., const_cast<OGRSpatialReference*>(geom->getSpatialReference()), ...)` is safe or not?

**Comment by rouault** [comment]
> Does that mean that `CreateLayer(..., const_cast<OGRSpatialReference*>(geom->getSpatialReference()), ...)` is safe

yes it is. that means we should also fix CreateLayer to accept a const OGRSpatialReference*
