### ISSUE TITLE
Feature request: GTiff and /vsicurl, increase the sequential reading

### ISSUE THREAD

**Issue by eripe970** [OSGeo/gdal#8499]
I'm reading from the docs at https://gdal.org/user/virtual_file_systems.html#vsicurl.

>   If the driver detects sequential reading it will progressively increase the chunk size up to 2 MB to improve download performance.

Is there any reason to why it's not possible to increase this even more? I'm reading a 300mb file and processing it using `gdal_calc.py` so I think it would be beneficial to read more data at once. 

 Not sure if it's intended but changing the `CPL_VSIL_CURL_CHUNK_SIZE` to 10x1024x1024 will increase the setting to 10mb per range request.

**Comment by jratike80** [comment]
Are you unsure if detecting sequential reading is supposed to override the value that is set with CPL_VSIL_CURL_CHUNK_SIZE or not? 

> Partial downloads (requires the HTTP server to support random reading) are done with a 16 KB granularity by default. Starting with GDAL 2.3, the chunk size can be configured with the [CPL_VSIL_CURL_CHUNK_SIZE](https://gdal.org/user/configoptions.html#config-CPL_VSIL_CURL_CHUNK_SIZE) configuration option, with a value in bytes. If the driver detects sequential reading it will progressively increase the chunk size up to 2 MB to improve download performance.

You could have used the gdal-dev mailing list for asking the question "Is there any reason to why it's not possible to increase this even more?" because the question and discussion can interest other GDAL users as well. More users see the mailing list posts than the GitHub issues.

**Comment by rouault** [comment]
Finding the good defaults for low latency on small reads for random access patterns, good bandwidth usage on larger ones for sequential access patterns, and not consuming too much RAM is tricky.

The 2 MB thing is when doing repeated sequential reads of small amounts, and with the default value of CHUNK_SIZE = 16 KB. Actually the 2 MB limit is evaluated as CPL_VSIL_CURL_CHUNK_SIZE * 128.
So you can try to increase CPL_VSIL_CURL_CHUNK_SIZE, up to 10485760 (10 MB) which is the max value allowed.
If you increase CPL_VSIL_CURL_CHUNK_SIZE, you should also increase the value of CPL_VSIL_CURL_CACHE_SIZE whose default is 16384000 (16 MB), to CPL_VSIL_CURL_CHUNK_SIZE * 128 to maximize the efficiency of the heuristics

Please report if you observe performance improvements.

**Comment by eripe970** [comment]
Thanks @rouault! I see a lot of improvements with the changes you recommended, and nice with the update in #8521! Will close this one!
