### ISSUE TITLE
GPKG driver: Unsupported value for TILE_FORMAT: TIFF

### ISSUE THREAD

**Issue by velle** [OSGeo/gdal#8510]
Does the GPKG driver support creating tiles in TIFF format?

I have not had luck with creating a geopackage with tiff tiles. I get the following error:

    gdalwarp -of GPKG -co TILE_FORMAT=TIFF in.ecw out.gpkg
    Creating output file that is 8000P x 8000L.
    ERROR 6: Unsuppoted value for TILE_FORMAT: TIFF
    Processing in.ecw [1/1] : 0...10...20...30...40...50...60...70...80...90...100 - done.

According to the documentation for the GPKG driver (https://gdal.org/drivers/raster/gpkg.html) I believe TIFF should be supported, when creating a geopackage, but _not_ supported when reading a geopackage. Is that really so? Maybe TIFF is simply not supported, and thats the reason why I cant make it work?

![image](https://github.com/OSGeo/gdal/assets/4488298/e9779514-471c-49a6-9104-961826d9bd75)

I'm using: `GDAL 3.7.2, released 2023/09/05 (debug build)`

**Comment by jratike80** [comment]
Please don't ask questions in our bug tracker. Use the mailing list.

> IMPORTANT: Do NOT use GitHub to post any questions or support requests!
>            They will be closed immediately and ignored.
> 
> Questions should go to the gdal-dev mailing list at
> https://lists.osgeo.org/mailman/listinfo/gdal-dev
> or other support forums. GitHub issues are for bug
> reports and suggestions for new features.

**Comment by rouault** [comment]
> Does the GPKG driver support creating tiles in TIFF format?

only if using the tile gridded coverage extension (https://gdal.org/drivers/raster/gpkg.html#tiled-gridded-coverage-data), which is only available for non-Byte single-band rasters

**Comment by jratike80** [comment]
And why not TIFF for other rasters: The standard does not define such encoding https://www.geopackage.org/spec131/index.html#tiles

**Comment by velle** [comment]
> Please don't ask questions in our bug tracker. Use the mailing list.

I know and respect that rule, but in this case I expected that there was some issue with the documentation, that needed to be corrected. I thought it belonged here.

**Comment by velle** [comment]
> And why not TIFF for other rasters: The standard does not define such encoding https://www.geopackage.org/spec131/index.html#tiles

Nice to know the reason why. Thanks :)

> And why the mailing list? Because other users do not read bug reports but your question and our answers could be useful for them as well.

I always google for the issues I have, but rarely (if ever) does it take me to the mailing list archive. I do try to frame my questions such that others can find them when googling, so making my issues/questions/struggles available to others is indeed on my mind. I will pay more attention to the mailing list in the future, if that is the official / recommended resource for such questions :)
