### ISSUE TITLE
SQLite connections: check if PRAGMA TRUSTED_SCHEMA=1 is needed

### ISSUE THREAD

**Issue by jratike80** [OSGeo/gdal#8514]
See https://gis.stackexchange.com/questions/466715/inserting-xy-point-epsg-4326-fails-in-sqlite3-shell.  Some distributions compile nowadays SQLite with  the [-DSQLITE_TRUSTED_SCHEMA=0](https://www.sqlite.org/compile.html#trusted_schema) compile-time option. Mac is mentioned in the thread but the SQLite Windows binaries from https://www.sqlite.org/download.html seem to have also OFF as default. That can make at least some Spatialite functions to fail. I do not know if the same can happen with other SQLite based drivers.

A guaranteed way to prevent these problems is to execute `PRAGMA TRUSTED_SCHEMA=1` after the SQLite connection is made but if it is not needed then maybe it can be a security risk. In that case an explicit `PRAGMA TRUSTED_SCHEMA=0` could be executed.

**Comment by rouault** [comment]
I wouldn't be super enthusiastic about automatically executing ``pragma trusted_schema=1``. The actual fix will come from the next Spatialite version that will declare its SQL functions as SQLITE_INNOCUOUS. The change is already in the master version: https://www.gaia-gis.it/fossil/libspatialite/info/023f3323443fffa1

**Comment by jratike80** [comment]
What about executing pragma `trusted_schema=0` then if it is safer and ON is not really needed? Now users have it ON of OFF depending on what SQLite build they happen to have.

**Comment by rouault** [comment]
hum, this also affects the GPKG driver. The SQL functions to maintain the RTree need to be declared SQLITE_INNOCUOUS

**Comment by rouault** [comment]
Unfortunately declaring the SQL functions ST_MinX() etc as SQLITE_INNOCUOUS isn't enough, as the RTree virtual table itself is not declared as SQLITE_VTAB_INNOCUOUS. I've raised that to https://sqlite.org/forum/forumpost/f7b7dd72f6

**Comment by rouault** [comment]
ah good news: the SQLite3 devs have just checked in a change to declare the RTree virtual table as SQLITE_VTAB_INNOCUOUS: https://sqlite.org/src/info/f34c533b
