### ISSUE TITLE
OGR DXF conversion partly fails if DXF has 256+ long records

### ISSUE THREAD

**Issue by SzieberthAdam** [OSGeo/gdal#8527]
## Expected behavior and actual behavior.

Some layers are failed to get converted entirely, some are converted only partly.

Error message:
```
ERROR 1: ogrdxflayer.cpp, 3350: error at line 2468743 of test.dxf
```

## Steps to reproduce the problem.

Get a DXF file with long text records like this (part of it; I can give you the whole file personally but can not share it publicly):

```
100
AcDbEntity
  8
HI7_Támszerkezetek
370
     0
100
AcDbBlockReference
  2
HI_BGYAM
 10
627945.71851171
 20
139701.83079624
 30
0.0
1001
EKOZMU_T
1000
Típus;betongyám;
1001
EKOZMU_META
1000
objektum azonosító;38229_9623;adat neve;T-COM távközlési hálózata;szolgáltató;Magyar Telekom Nyrt.;méretarány (1:xy);1:500;adatelőállítás  módja;meglévő állományból szerkesztéssel;adatszolgáltatási szint;kivitelezési;vetület;EOV;üzemeltető neve;T-COM;üzemeltető adószáma;10773381-2-44;üzemeltető típusa;gazdasági társaság;tulajdonos neve;T-COM;tulajdonos adószáma;10773381-2-44;tulajdonos típusa;gazdasági társaság;tulajdonos tulajdoni hányada %;100;szolgáltatói engedélyes neve;Magyar Telekom Nyrt.;
  0
INSERT
  5
206F402
330
1F
100
AcDbEntity
  8
HI7_Támszerkezetek
370
     0
100
```

## Operating system

Windows

## GDAL version and provenance

(GDAL 3.7.2, I was using python)
It turned out that GDAL version is 3.4.3.
Anyway, the code gets to this line: https://github.com/OSGeo/gdal/blob/78d5980666602266a7e532ae5f76ffe1bf70b4ec/ogr/ogrsf_frmts/dxf/ogrdxflayer.cpp#L3391

## Solution

I circumvent the problem with regex search on the DXF `^(.{256}).+$` and keep the first group only. This is not good for those who want these kind of records in the output.

**Comment by jratike80** [comment]
Does the error happen with any outputformat?

**Comment by SzieberthAdam** [comment]
Yes, I tried GPKG, GeoJSON, SHP, and FGB.

**Comment by rouault** [comment]
Are you really using GDAL 3.7.2 ? I've strong doubts you do as the error message "ogrdxflayer.cpp, 3350" can't be emitted from line https://github.com/OSGeo/gdal/blob/v3.7.2/ogr/ogrsf_frmts/dxf/ogrdxflayer.cpp#L3350

Secondly, strings in DXF can't exceed 256 character per the spec: https://damassets.autodesk.net/content/dam/autodesk/www/developer-network/platform-technologies/autocad-dxf-archive/acad_r12_dxf.pdf : "Note: The maximum DXF file string length is 256 characters. If your AutoCAD drawing contains strings that exceed this number, those strings are truncated during DXFOUT. If your DXF file contains strings that exceed this number, DXFIN fails."

**Comment by SzieberthAdam** [comment]
Sorry, that was my standalone GDAL version.
```
>>> from osgeo import gdal, ogr
>>> gdal.__version__
'3.4.3'
```

**Comment by jratike80** [comment]
Do you write those long strings with your own code or do you use some software that does not respect the specification?

**Comment by SzieberthAdam** [comment]
I expected the DXF to be non-standard but still it is converted from DWG using ODA Drawings Explorer. If I could choose between loosing record content or going for non-standard file which is still usable by my workflow, I would pick the second. I can tell, we get these kinds of DWG files from engineers regularly and this is a problem for years now. I used to truncate them manually but now that I had to write a script for my college to make him able to get through the problem by himself, I thought I report this.

**Comment by jratike80** [comment]
Does AutoCAD read those files?

**Comment by SzieberthAdam** [comment]
I do not know, as we do not have licensed AutoCAD. Moreover I am using Win7 thus I have to find an older DWG TrueView to answer the question to some degree.

**Comment by rouault** [comment]
From my testing and looking at the code, the OGR DXF reader truncates lines longer than 256 characters (with a warning that can be seen when activating CPL_DEBUG=ON) and goes on. I believe the error your get must be something other that it doesn't like. A (structurally valid) reproducer DXF file would be needed for further analysis

**Comment by SzieberthAdam** [comment]
@jratike80

Now I can confirm that DWG TrueView 2018 had no problem with the file in question.

@rouault 

Yes I see that the 256 length limit still applies:
https://help.autodesk.com/view/ACD/2022/ENU/?guid=GUID-89CB823D-614D-4D1E-8204-568EC72DF869

Anyway, I sent you the files. It contains the original DWG, the test script, and a bunch of DXFs produced by free converters.

**Comment by rouault** [comment]
I'm closing this as you're testing with 3.4.3 and latest GDAL versions behave much better.

From what you provided, they manage to read 2 files that DWG TrueView 2018 also does:

$ ogr2ogr -f memory foo ~/gdal/gdal/build_cmake/dxftest/dxftest--oda-file-converter-24-9--2018-ascii.dxf
Warning 1: One or several characters couldn't be converted correctly from CP1250 to UTF-8.  This warning will not be emitted anymore
Warning 1: Block *U59 does not exist
Warning 1: Block *U60 does not exist

$ ogr2ogr -f memory foo ~/gdal/gdal/build_cmake/dxftest/dxftest--oda-drawings-explorer-24-9-recover--2018-ascii.dxf
Warning 1: One or several characters couldn't be converted correctly from CP1250 to UTF-8.  This warning will not be emitted anymore
Warning 1: Block *U59 does not exist
Warning 1: Block *U60 does not exist

One that DWG TrueView 2018  does not:

$ ogr2ogr -f memory foo ~/gdal/gdal/build_cmake/dxftest/dxftest--dwgconvert-2023-a-02--2018-ascii.dxf
Warning 1: One or several characters couldn't be converted correctly from CP1250 to UTF-8.  This warning will not be emitted anymore
Warning 1: Block *U59 does not exist
Warning 1: Block *U60 does not exist

They choke on dxftest--cloudconvert-com--2023-10-09--2004-ascii.dxf that DWG TrueView 2018 reads, but inspecting the file I can indeed see that a spline definition is incorrect:

$ ogr2ogr -f memory foo ~/gdal/gdal/build_cmake/dxftest/dxftest--cloudconvert-com--2023-10-09--2004-ascii.dxf
ERROR 1: /home/even/gdal/gdal/ogr/ogrsf_frmts/dxf/ogrdxf_hatch.cpp, 161: error at line 108742 of /home/even/gdal/gdal/build_cmake/dxftest/dxftest--cloudconvert-com--2023-10-09--2004-ascii.dxf
Warning 1: Block *U59 does not exist
Warning 1: Block *U60 does not exist

**Comment by SzieberthAdam** [comment]
Thanks for your time and answers.
