### ISSUE TITLE
gdal_translate: Incorrect Signed byte -> Byte conversion (regression?)

### ISSUE THREAD

**Issue by AndrewJDR** [OSGeo/gdal#8528]
## Steps to reproduce the problem.
1. Download Orthophoto_x2y2.tif [here](https://drive.google.com/file/d/1XUSIYdMnDOtUh09ueOI--gHxkMp7FWxE/view?usp=sharing) (sha256: f97edb714c60912a7130061bcc8af6ca2cc16cb5f633d02154f707751583a8cb) 
2. Using the latest gdal (git master commit 78d598066 as of this writing), run `gdal_translate -ot Byte Orthophoto_x2y2.tiff Orthophoto_x2y2_Byte.tiff`
3. Now run `gdallocationinfo Orthophoto_x2y2_Byte.tiff 7000 9000`

Unexpected result (from gdal master commit 78d598066):
```
Report:
  Location: (7000P,9000L)
  Band 1:
    Value: 0
  Band 2:
    Value: 119
  Band 3:
    Value: 104
  Band 4:
    Value: 0
```
The above result  of `0, 119, 104, 0` is unexpected. The expected result is `130, 119, 104, 255`.

This seems to be a regression caused sometime between gdal 3.6.4 and now, because you can achieve the expected result with gdal 3.6.4. If you use a build of gdal 3.6.4 to run the `gdal_translate -ot Byte Orthophoto_x2y2.tiff Orthophoto_x2y2_Byte.tiff` command, then run `gdallocationinfo Orthophoto_x2y2_Byte.tiff 7000 9000` on the output file, you'll get the following expected result:

Expected result (from gdal v3.6.4):
```
Report:
  Location: (7000P,9000L)
  Band 1:
    Value: 130
  Band 2:
    Value: 119
  Band 3:
    Value: 104
  Band 4:
    Value: 255
```
## Operating system

Ubuntu 20.04

## GDAL version and provenance

git commit 78d598066 is affected.
gdal 3.6.4 is not affected.

## Additional information
Here are some command outputs using the input file, Orthophoto_x2y2.tiff.

`gdallocation Orthophoto_x2y2.tiff 7000 9000` (GDAL 3.6.4):
```
Report:
  Location: (7000P,9000L)
  Band 1:
    Value: 130
  Band 2:
    Value: 119
  Band 3:
    Value: 104
  Band 4:
    Value: 255
```

`gdallocation Orthophoto_x2y2.tiff 7000 9000` (GDAL master, commit 78d598066) 
```
Report:
  Location: (7000P,9000L)
  Band 1:
    Value: -126
  Band 2:
    Value: 119
  Band 3:
    Value: 104
  Band 4:
    Value: -1
```

Notice above that the output of gdallocation is different for gdal 3.6.4 vs. master, though neither is incorrect per se, just a different interpretation for the purposes of printing the information (unsigned for 3.6.4, signed for git master) . This difference is probably due to the [PIXELTYPE=SIGNEDBYTE / Int8 related change that happened in gdal 3.7](https://gdal.org/development/rfc/rfc87_signed_int8.html), but I'm not sure.

`gdalinfo Orthophoto_x2y2.tiff` output (GDAL 3.6.4):
```
Driver: GTiff/GeoTIFF
Files: Orthophoto_x2y2.tiff
Size is 13408, 11344
Coordinate System is:
PROJCRS["unnamed",
    BASEGEOGCRS["unknown",
        DATUM["unnamed",
            ELLIPSOID["unnamed",6378137,298.257223563,
                LENGTHUNIT["metre",1,
                    ID["EPSG",9001]]]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433,
                ID["EPSG",9122]]]],
    CONVERSION["Transverse Mercator",
        METHOD["Transverse Mercator",
            ID["EPSG",9807]],
        PARAMETER["Latitude of natural origin",0,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",9,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["Scale factor at natural origin",0.9996,
            SCALEUNIT["unity",1],
            ID["EPSG",8805]],
        PARAMETER["False easting",500000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["(E)",east,
            ORDER[1],
            LENGTHUNIT["metre",1,
                ID["EPSG",9001]]],
        AXIS["(N)",north,
            ORDER[2],
            LENGTHUNIT["metre",1,
                ID["EPSG",9001]]]]
Data axis to CRS axis mapping: 1,2
GeoTransform =
  311636.9515126267, 0.04996302201073902, 2.943764834784188e-15
  5170280.971397011, -6.474063469113285e-16, -0.05001034688519408
Metadata:
  TIFFTAG_XRESOLUTION=96
  TIFFTAG_YRESOLUTION=96
Image Structure Metadata:
  COMPRESSION=LZW
  INTERLEAVE=PIXEL
Corner Coordinates:
Upper Left  (  311636.952, 5170280.971) (  6d32'16.52"E, 46d39'34.52"N)
Lower Left  (  311636.952, 5169713.654) (  6d32'17.36"E, 46d39'16.16"N)
Upper Right (  312306.856, 5170280.971) (  6d32'48.02"E, 46d39'35.20"N)
Lower Right (  312306.856, 5169713.654) (  6d32'48.85"E, 46d39'16.84"N)
Center      (  311971.904, 5169997.313) (  6d32'32.69"E, 46d39'25.68"N)
Band 1 Block=13408x1024 Type=Byte, ColorInterp=Red
  NoData Value=0
  Overviews: 6704x5672, 3352x2836, 1676x1418, 838x709, 419x354, 209x177
  Image Structure Metadata:
    PIXELTYPE=SIGNEDBYTE
Band 2 Block=13408x1024 Type=Byte, ColorInterp=Green
  NoData Value=0
  Overviews: 6704x5672, 3352x2836, 1676x1418, 838x709, 419x354, 209x177
  Image Structure Metadata:
    PIXELTYPE=SIGNEDBYTE
Band 3 Block=13408x1024 Type=Byte, ColorInterp=Blue
  NoData Value=0
  Overviews: 6704x5672, 3352x2836, 1676x1418, 838x709, 419x354, 209x177
  Image Structure Metadata:
    PIXELTYPE=SIGNEDBYTE
Band 4 Block=13408x1024 Type=Byte, ColorInterp=Alpha
  NoData Value=0
  Overviews: 6704x5672, 3352x2836, 1676x1418, 838x709, 419x354, 209x177
  Image Structure Metadata:
    PIXELTYPE=SIGNEDBYTE
```

`gdalinfo Orthophoto_x2y2.tiff` output (GDAL master, commit 78d598066):
```
Driver: GTiff/GeoTIFF
Files: Orthophoto_x2y2.tiff
Size is 13408, 11344
Coordinate System is:
PROJCRS["unnamed",
    BASEGEOGCRS["unknown",
        DATUM["unnamed",
            ELLIPSOID["unnamed",6378137,298.257223563,
                LENGTHUNIT["metre",1,
                    ID["EPSG",9001]]]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433,
                ID["EPSG",9122]]]],
    CONVERSION["Transverse Mercator",
        METHOD["Transverse Mercator",
            ID["EPSG",9807]],
        PARAMETER["Latitude of natural origin",0,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",9,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["Scale factor at natural origin",0.9996,
            SCALEUNIT["unity",1],
            ID["EPSG",8805]],
        PARAMETER["False easting",500000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["(E)",east,
            ORDER[1],
            LENGTHUNIT["metre",1,
                ID["EPSG",9001]]],
        AXIS["(N)",north,
            ORDER[2],
            LENGTHUNIT["metre",1,
                ID["EPSG",9001]]]]
Data axis to CRS axis mapping: 1,2
GeoTransform =
  311636.9515126267, 0.04996302201073902, 2.943764834784188e-15
  5170280.971397011, -6.474063469113285e-16, -0.05001034688519408
Metadata:
  TIFFTAG_XRESOLUTION=96
  TIFFTAG_YRESOLUTION=96
Image Structure Metadata:
  COMPRESSION=LZW
  INTERLEAVE=PIXEL
Corner Coordinates:
Upper Left  (  311636.952, 5170280.971) (  6d32'16.52"E, 46d39'34.52"N)
Lower Left  (  311636.952, 5169713.654) (  6d32'17.36"E, 46d39'16.16"N)
Upper Right (  312306.856, 5170280.971) (  6d32'48.02"E, 46d39'35.20"N)
Lower Right (  312306.856, 5169713.654) (  6d32'48.85"E, 46d39'16.84"N)
Center      (  311971.904, 5169997.313) (  6d32'32.69"E, 46d39'25.68"N)
Band 1 Block=13408x1024 Type=Int8, ColorInterp=Red
  NoData Value=0
  Overviews: 6704x5672, 3352x2836, 1676x1418, 838x709, 419x354, 209x177
Band 2 Block=13408x1024 Type=Int8, ColorInterp=Green
  NoData Value=0
  Overviews: 6704x5672, 3352x2836, 1676x1418, 838x709, 419x354, 209x177
Band 3 Block=13408x1024 Type=Int8, ColorInterp=Blue
  NoData Value=0
  Overviews: 6704x5672, 3352x2836, 1676x1418, 838x709, 419x354, 209x177
Band 4 Block=13408x1024 Type=Int8, ColorInterp=Alpha
  NoData Value=0
  Overviews: 6704x5672, 3352x2836, 1676x1418, 838x709, 419x354, 209x177
```

**Comment by jratike80** [comment]
The source image has both nodata=0 and alpha, wondering if that can make some confusion.

**Comment by rouault** [comment]
I understand you want to correct an incorrect data type in the original dataset from signed int8 to unsigned int8. You were lucky that GDAL < 3.7 was misbehaving regarding signed int8 handling by not clamping pixel values when changing data types, and relied on that.
There's no direct way to do what you did before with GDAL >= 3.7, but here's a way of doing it in several steps:
- gdal_translate bad_int8.tif  intermediate.img -of EHDR
- edit intermediate.hdr to replace "PIXELTYPE      SIGNEDINT" to "PIXELTYPE      UNSIGNEDINT"
- gdal_translate intermediate.img uint8.tif

**Comment by AndrewJDR** [comment]
Thanks, so it sounds like this is probably an issue with the application that originally outputted this file. I'll let them know.

**Comment by jratike80** [comment]
Ask them what data value the pixel at Location: (7000P,9000L) should present. If they say that this is what they mean: 
Band 1:  Value: -126
then the source file is correct by the old GDAL way for defining negative integers with PIXELTYPE=SIGNEDBYTE.

**Comment by AndrewJDR** [comment]
@jratike80 I can speak more confidently about Band 4 (alpha), which at Location: (7000P,9000L) was intended to be fully "on", i.e. pure white in perceptual terms. Using gdallocation 3.6.4, it presents as 255 and with gdallocation master, it presents as -1.

The image viewers I've I opened it with (e.g. Gimp) do interpret Band4 at 7000P,9000L as white (255), which is what was intended.

**Comment by AndrewJDR** [comment]
Here is the source file open in a recent version of QGIS (left) showing a weird result vs. the Acdsee image viewer (right) showing the desired result. I presume QGIS uses gdal under the hood, but I'm not sure.

![image](https://github.com/OSGeo/gdal/assets/1588857/5e719a8c-ca2e-4892-a697-727df0060af7)

**Comment by jratike80** [comment]
It looks obvious that the error is in PIXELTYPE=SIGNEDBYTE. It should not be there. Contact the one who provides the images or software. Meanwhile you can utilize the bug that you found in GDAL 3.6.4 and older.

**Comment by AndrewJDR** [comment]
Thanks for all the help. The issue was tracked down and fixed in the vendor's application.
