### ISSUE TITLE
Feature Request: Skip overviews option in gdalcompare.py

### ISSUE THREAD

**Issue by jontwo** [OSGeo/gdal#8530]
## Expected behavior and actual behavior.

`gdalcompare.compare_db` has options for "SKIP_SRS", "SKIP_GEOTRANSFORM" and "SKIP_METADATA". It would also be useful to "SKIP_OVERVIEWS" as this comparison takes a long time and the overviews (should) just contain the same data as the main band.

Also, it would be great if all these options could be passed through from the command line, even if it is just a case of setting an environment variable with the same name.

**Comment by jratike80** [comment]
You are late, see https://github.com/OSGeo/gdal/pull/8482.
