### ISSUE TITLE
Shapelib Building with RENAME_INTERNAL_SHAPELIB_SYMBOLS=OFF causes compile error

### ISSUE THREAD

**Issue by OlekRaymond** [OSGeo/gdal#8532]
## Expected behaviour and actual behaviour.

When building GDAL using CMake and requesting that shapelib functions NOT be renamed a compilation failure occurs.

## Steps to reproduce the problem.

using `cmake.exe -DGDAL_USE_INTERNAL_LIBS=WHEN_NO_EXTERNAL -DRENAME_INTERNAL_SHAPELIB_SYMBOLS=OFF .\ ` results in the compiler error when building 

## Operating system

Windows 10 Pro (22H2) 
64-bit operating system, x64-based processor
Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz   1.99 GHz

## GDAL version and provenance

Issue is in 3.5.3 - 3.7.2 

Credit to Russell Mills from Riskaware LTD for finding the issue.

**Comment by rouault** [comment]
fixed per d7ab108470 . backport to 3.7 per bbba4fe1db

**Comment by OlekRaymond** [comment]
Thanks 😄
