### ISSUE TITLE
ogr2ogr option to drop/ignore/deselect attributes

### ISSUE THREAD

**Issue by andrewharvey** [OSGeo/gdal#854]
Just like `ogr2ogr -select` can _select_ attributes to include in the output, I'd like an `ogr2ogr -deselect` option to indicate fields to selectively drop from the output.

**Comment by jratike80** [comment]
There is a duplicate ticket about this in the old Trac https://trac.osgeo.org/gdal/ticket/3888 but I am not sure how we deal with the old tickets since the move to Github.

**Comment by rouault** [comment]
"SELECT * EXCEPT xxx" should do the job

**Comment by jratike80** [comment]
And the option is available in the OGRSQL dialect https://gdal.org/user/ogr_sql_dialect.html.
