### ISSUE TITLE
MBTiles: gdalinfo may report wrong zoom levels

### ISSUE THREAD

**Issue by jratike80** [OSGeo/gdal#8565]
See the detailed description in https://gis.stackexchange.com/a/468484/30184.

Is short, if three overviewa are added to MBTiles raster file, for example Z17, with
`gdaladdo output.mbtiles 2 4 8`
then gdalinfo shows some non-existing zoom levels
```
  maxzoom=17
  minzoom=11

```
The correct zoom levels 14-17 can be searched from the "tiles" table of the MBTiles database

```
ogrinfo SQLite:output.mbtiles -sql "SELECT min(zoom_level) as min, max(zoom_level) as max from tiles" output.mbtiles
OGRFeature(SELECT):0
  min (Integer) = 14
  max (Integer) = 17
```

**Comment by rouault** [comment]
@jratike80 This might be data dependent. I don't reproduce with:

$ gdal_translate autotest/gcore/data/byte.tif  test.mbtiles -outsize 1024 0
Input file size is 20, 20
0...10...20...30...40...50...60...70...80...90...100 - done.

$ gdalinfo test.mbtiles | grep zoom
  minzoom=17
  maxzoom=17

$ gdaladdo test.mbtiles 2 4 8
0...10...20...30...40...50...60...70...80...90...100 - done.

$ gdalinfo test.mbtiles | grep zoom
  maxzoom=17
  minzoom=14

**Comment by jratike80** [comment]
My input file is 12000x12000 in EPSG:3067, yielding
```
Files: output.mbtiles
Size is 11138, 11153
```
