### ISSUE TITLE
Some GRIB2 files cause GDAL to emit unsuppressable warnings and errors to console, despite successful parsing and processing of the file

### ISSUE THREAD

**Issue by potion-cellar** [OSGeo/gdal#8574]
## Expected behavior
I can use GDAL to process GRIB2 files successfully in quiet mode without messages being logged to console.

## Actual behavior
GDAL logs warning and error messages to console in quiet mode, despite successfully processing the GRIB2 file.

## Reproduction
Attached is a GRIB2 file from the HRRR weather model, which is the most frequent culprit. When handling these GRIB2 files, the console is cluttered with

```
Warning: Inside GRIB2Inventory, Message # 2
ERROR: Couldn't find 'GRIB' or 'TDLP'
```

despite running GDAL in quiet mode.

Regardless, the file is processed correctly.

When this weather model is processed as part of a data processing pipeline, the console is filled with thousands of these messages with no easy way to suppress them.

You can `gdalinfo` this file and see the warning message emitted before the `gdalinfo` output:
[hrrr_temperature.grib2.zip](https://github.com/OSGeo/gdal/files/13031734/hrrr_temperature.grib2.zip)

## Operating system
All

## GDAL version and provenance
3.7.2 (but this has been an issue for years)

**Comment by rouault** [comment]
the warning message is legitimate (there is 1 trailing byte at the end of the GRIB file), but in https://github.com/OSGeo/gdal/pull/8576 I've reduced its verbosity as a GDAL debug message (so not visible by default)
