### ISSUE TITLE
gdalbuilvrt with separate option force sourceBand to 1 even if band options array size is 1.

### ISSUE THREAD

**Issue by TAlonglong** [OSGeo/gdal#8584]
## Expected behavior and actual behavior.

I want to produce a VRT with netcdf source data. I want the VRT to consist of separate bands from two different netcdf variables with the selected source band.

The actual behavior is to force the sourceband to 1

## Steps to reproduce the problem.

gdalbuildvrt -separate -b 14 test.vrt NETCDF:<netcdf file with NWP data>:x_wind_10m NETCDF:<netcdf file with NWP data>:y_wind_10m
0...10...20...30...40...50Warning 1: NETCDF:<netcdf file with NWP data>:x_wind_10m has 67 bands. Only the first one will be taken into account in the -separate case
...60...70...80...90...100 - done.
Warning 1: NETCDF:<netcdf file with NWP data>:y_wind_10m has 67 bands. Only the first one will be taken into account in the -separate case

Outputs
```
<VRTDataset rasterXSize="739" rasterYSize="949">
  <VRTRasterBand dataType="Float32" band="1">
    <NoDataValue>9.96920996838686905e+36</NoDataValue>
    <ComplexSource>
      <SourceFilename relativeToVRT="0">NETCDF:<netcdf file with NWP data>:x_wind_10m</SourceFilename>
      <SourceBand>1</SourceBand>
      <SourceProperties RasterXSize="739" RasterYSize="949" DataType="Float32" BlockXSize="739" BlockYSize="949" />
      <SrcRect xOff="0" yOff="0" xSize="739" ySize="949" />
      <DstRect xOff="0" yOff="0" xSize="739" ySize="949" />
      <NODATA>9.96920996838686905e+36</NODATA>
    </ComplexSource>
  </VRTRasterBand>
  <VRTRasterBand dataType="Float32" band="2">
    <NoDataValue>9.96920996838686905e+36</NoDataValue>
    <ComplexSource>
      <SourceFilename relativeToVRT="0">NETCDF:<netcdf file with NWP data>:y_wind_10m</SourceFilename>
      <SourceBand>1</SourceBand>
      <SourceProperties RasterXSize="739" RasterYSize="949" DataType="Float32" BlockXSize="739" BlockYSize="949" />
      <SrcRect xOff="0" yOff="0" xSize="739" ySize="949" />
      <DstRect xOff="0" yOff="0" xSize="739" ySize="949" />
      <NODATA>9.96920996838686905e+36</NODATA>
    </ComplexSource>
  </VRTRasterBand>
</VRTDataset>
```

Here is sourceBand forced to 1.

I understand this is needed if the user request more than one band, but here as the size of band array is 1 this should be allowed.
The part of the code in question: https://github.com/OSGeo/gdal/blob/master/apps/gdalbuildvrt_lib.cpp#L573-L591
Here also the request band should be checked. If 1 then it should be allowed

## Operating system

Ubuntu jammy

## GDAL version and provenance

gdal                      3.7.2           py310h5c4b078_2    conda-forge
libgdal                   3.7.2                h9868cb8_2    conda-forge

**Comment by jratike80** [comment]
I added an enhancement label because the behavior is documented https://gdal.org/programs/gdalbuildvrt.html#cmdoption-gdalbuildvrt-separate
> Place each input file into a separate band. In that case, only the first band of each dataset will be placed into a new band.

Have you tried to make an interim VRT with `-b 14` to be used as an input for `-separate`?
