### ISSUE TITLE
LICENSE.TXT is incomplete.

### ISSUE THREAD

**Issue by ThomasN-Saab** [OSGeo/gdal#859]
If I'm not mistaken, it should contain this copyright notice: https://trac.osgeo.org/gdal/wiki/FAQGeneral#WhatlicensedoesGDALOGRuse

Currently it's lacking the actual copyright notice and has only the X/MIT license.

**Comment by rouault** [comment]
The file is called LICENSE.TXT, so it doesn't have to have copyright terms in it. This is what is done usually on such LICENSE.TXT or COPYING files
Copyright attributions changes from file to file.

**Comment by rouault** [comment]
If you are looking for something most exhaustive in a single file, I can think of https://metadata.ftp-master.debian.org/changelogs/main/g/gdal/gdal_2.3.1+dfsg-2_copyright

**Comment by ThomasN-Saab** [comment]
That's not my experience. The license file usually has a copyright notice.

Anyway, when I compile GDAL to use the binary with my own project I must -according to the license- include "The above copyright notice and this permission notice". Do I include the license without a copyright notice (as there is none above the license) or do I include all the copyright notices in that list you linked? Or have I completely misunderstood and the license doesn't apply to compiled binaries?

**Comment by rouault** [comment]
I'd say if you include the LICENSE.TXT, it should be fine. But this is not legal advice

**Comment by ThomasN-Saab** [comment]
Okay. I'll go with that.

**Comment by mwestphal** [comment]
Adding "Copyright The GDAL contributors" somewhere would clarify the copyrights situation imho.
