### ISSUE TITLE
MSSQLSpatial: "spatial reference identifier (SRID) is not valid" loading data from GeoPackage

### ISSUE THREAD

**Issue by simonsouth** [OSGeo/gdal#860]
## Expected behavior and actual behavior.

I'd like to use `ogr2ogr` to periodically import data from a GeoPackage into existing tables in a SQL Server database, ideally making whatever conversions (mapping of field names and etc.) within the tool itself so I can completely update each table with a single command.

This seems achievable, but trying to use `ogr2ogr` to append records to an existing table in SQL Server currently fails with

```
ERROR 1: INSERT command for new feature failed. [37000][Microsoft][ODBC Driver 17 for SQL Server][SQL Server]A .NET Framework error occurred during execution of user-defined routine or aggregate "geometry":
System.FormatException: 24100: The spatial reference identifier (SRID) is not valid. SRIDs must be b(6522)
ERROR 1: Unable to write feature 1 from layer LayerName.
ERROR 1: Terminating translation prematurely after failed
translation of layer LayerName (use -skipfailures to skip errors)
```

**The issue is there is no spatial-reference system associated with "unregistered" tables in SQL Server, those without a corresponding entry in the `geometry_columns` table.** I suspect this is fairly typical for spatial tables as [SQL Server does not enforce a consistent spatial-reference system across rows](https://docs.microsoft.com/en-us/sql/relational-databases/spatial/spatial-reference-identifiers-srids?view=sql-server-2017) and does not appear to track any metadata about which systems have been used.

Internally, [`OGRMSSQLSpatialLayer` assigns an SRID of -1](https://github.com/OSGeo/gdal/blob/3e2c8ca5176a16a2a98edf1bab170a96d8b777e4/gdal/ogr/ogrsf_frmts/mssqlspatial/ogr_mssqlspatial.h#L212) to tables for which it can't identify an SRS (i.e. tables not registered in `geometry_columns`). When `CreateFeature` is invoked for a layer backed by such a table, this value is passed to SQL Server, which considers it invalid and returns the error message shown above. (SQL Server actually uses an SRID of _zero_ to indicate an unknown SRS; perhaps the driver should be changed to match.)

The documentation suggests a couple of workarounds, neither of which have any effect:

- [The driver offers](https://www.gdal.org/drv_mssqlspatial.html) an "SRID" layer-creation option that purports to set the SRID of the target table, but this and all other layer-creation options are ignored when appending to an existing table.
- [The tool itself offers](https://www.gdal.org/ogr2ogr.html) the "a_srs" and "t_srs" options which purport to override the output SRS, but while these do seem to control the SRS assigned to the outgoing feature, [`OGRMSSQLSpatialTableLayer::ICreateFeature()`](https://github.com/OSGeo/gdal/blob/3e2c8ca5176a16a2a98edf1bab170a96d8b777e4/gdal/ogr/ogrsf_frmts/mssqlspatial/ogrmssqlspatialtablelayer.cpp#L1942-L2256) completely ignores this and [uses only the (invalid) SRID assigned to the table itself](https://github.com/OSGeo/gdal/blob/3e2c8ca5176a16a2a98edf1bab170a96d8b777e4/gdal/ogr/ogrsf_frmts/mssqlspatial/ogrmssqlspatialtablelayer.cpp#L2132).

**It seems to me the solution is to modify `OGRMSSQLSpatialTableLayer::ICreateFeature()` so by default it honours the SRID of the feature it's been given, ignoring the SRID of the table itself unless the feature's SRS is unknown.** This is because

- We cannot rely on the `geometry_columns` to give us an SRID for every table.
- We cannot rely on the database engine either, since it neither associates a particular SRS with a table nor enforces the consistent use of one.
- We _can_ rely on the feature `ICreateFeature()` receives to have already been assigned a sensible SRS, one that takes into account [the SRS of the source data](https://github.com/OSGeo/gdal/blob/3e2c8ca5176a16a2a98edf1bab170a96d8b777e4/gdal/apps/ogr2ogr_lib.cpp#L3437) and [the options specified by the user](https://github.com/OSGeo/gdal/blob/3e2c8ca5176a16a2a98edf1bab170a96d8b777e4/gdal/apps/ogr2ogr_lib.cpp#L1744-L1745).
- We should in general trust the user has selected the SRS he intends to use, and provide a sensible default (matching the source SRS, in this case) when no selection has been made.

**Does this seem reasonable?**

## Steps to reproduce the problem.

Invoke `ogr2ogr` to append records to an existing (but "unregistered") spatial table in SQL Server:

```
MSSQLSPATIAL_USE_GEOMETRY_COLUMNS=NO ogr2ogr -f MSSQLSpatial -append 'MSSQL:Driver={ODBC Driver 17 for SQL Server};Server=.;Database=DatabaseName;UID=Username;PWD=Password' ./GeoPackage.gpkg -nln ExistingLayerName LayerName -dim 2
```

## Operating system

Ubuntu 16.04.5 64-bit (via Windows Subsystem for Linux on Windows 10)
Microsoft ODBC Driver 17 for SQL Server

## GDAL version and provenance

GDAL 2.4.0dev, compiled from `master`

**Comment by rouault** [comment]
> Does this seem reasonable?

Sounds good to me. And changing the unknown SRID to 0 as well
