### ISSUE TITLE
Error when importing gdal

### ISSUE THREAD

**Issue by jc-barreto** [OSGeo/gdal#8602]
## Expected behavior and actual behavior.

 I expected to be able to import gdal.
The steps I did as described in [ this question](https://openradar.discourse.group/t/attributeerror-module-osgeo-gdalconst-has-no-attribute-gdt-int8/333/2) were: 
 Create a new environment:
conda create -n geo python=3.9
conda activate geo
conda install geopandas, gdal, shapely
conda install geospatial -c conda-forge

and finaly after some comment I have updated gdal:
conda update gdal

## Steps to reproduce the problem.

from osgeo import gdal

## Operating system

Windows 11 x64

## GDAL version and provenance

3.7.2
![image](https://github.com/OSGeo/gdal/assets/42352209/2bd4813e-4cfe-4d9f-926b-d9e1720dc66e)

**Comment by jratike80** [comment]
Have you tried with Python 3.8 like in this gis.stackexchange question https://gis.stackexchange.com/questions/461363/modulenotfounderror-no-module-named-gdal-in-ubuntu-20-04-and-python-3-8/468410#468410?

**Comment by rouault** [comment]
DCAP_FLUSHCACHE_CONSISTENT_STATE is in master / GDAL 3.8.0 dev only . So it looks like the python bindings you've installed in ~/conda/envs/geo/lib/site-packages/osgeo are from GDAL master, but you are running against libgdal 3.7.2 . ==> closing as installation issue
