### ISSUE TITLE
SAMPLE_STEPS warp option has illegal value with SAMPLE_STEPS=ALL

### ISSUE THREAD

**Issue by arjouz** [OSGeo/gdal#8604]
## Expected behavior and actual behavior.

SAMPLE_STEPS=ALL doesn't work with rasterio reproject whereas it should.
rasterio._err.CPLE_IllegalArgError: GDALWarpOptions.Validate(): SAMPLE_STEPS warp option has illegal value.

## Steps to reproduce the problem.
warper_options = {"RPC_DEM": dem_file,
                                          "RPC_DEM_MISSING_VALUE": 0,
                                          "OSR_USE_ETMERC": "YES",
                                          "BIGTIFF": "IF_NEEDED", 
                                          "SAMPLE_GRID": "YES", 
                                          "SAMPLE_STEPS": "ALL"}
                        
                        arr, transform = reproject(
                                                    source=rio.band(src, src.indexes),
                                                    rpcs=src.rpcs,
                                                    src_crs="EPSG:4326",
                                                    src_nodata=src.nodata,
                                                    dst_crs=dst_crs,
                                                    dst_nodata=src.nodata,
                                                    resampling=Resampling.cubic,
                                                    num_threads=num_threads,
                                                    **warper_options
                            )

## Operating system

4.18.0-372.32.1.el8_6.x86_64 #1 SMP Fri Oct 7 12:35:10 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux

## GDAL version and provenance

GDAL 3.2.2

**Comment by jratike80** [comment]
GDAL 3.2.2 is not a supported version. Supported version is 3.7.
Read also https://gdal.org/doxygen/structGDALWarpOptions.html

> Starting with GDAL 3.7, this can be set to ALL to mean to sample along all edge points of the destination region (if SAMPLE_GRID=NO or not specified), or all points of the destination region if SAMPLE_GRID=YES.

**Comment by arjouz** [comment]
Thank you for your answer. I suppose this issue can be closed...
