### ISSUE TITLE
GDAL 3.8: missing GitHub release and containers

### ISSUE THREAD

**Issue by frafra** [OSGeo/gdal#8607]
There is no GDAL 3.8 release in this GitHub repository, nor published Docker images for such version.

**Comment by rouault** [comment]
yes, it has not been yet released

**Comment by frafra** [comment]
Sorry, I see that there are reference in the documentation, but it has not been released.

**Comment by rouault** [comment]
yes, the documentation tracks the master branch, so it is a bit "in the future" compared to releases
