### ISSUE TITLE
PNG file not opened to showing Map

### ISSUE THREAD

**Issue by anant9811** [OSGeo/gdal#8614]
Hi i am in new GIS.
currently read the shape file and want to export as image (PNG/JPEG) so that this file showing Map in C# Asp.net MVC application.

        
        Dim outputDriver1 As OSGeo.GDAL.Driver = Gdal.GetDriverByName("PNG")
        Dim outputFilePath1 As String = $"c:\Source\wissara\Sarahtml\output\test1.png"
        Dim outputDataset1 As Dataset = outputDriver1.CreateCopy(outputFilePath1, outputDataset, 800, Nothing, Nothing, Nothing)

can someone provide the code for C#, it it possible in GDAL to set background layer as google.baidu map?

**Comment by jratike80** [comment]
Repeating the text from the welcome page that you saw when starting to create an issue:

> IMPORTANT: Do NOT use GitHub to post any questions or support requests!
>            They will be closed immediately and ignored.
> 
> Questions should go to the gdal-dev mailing list at
> https://lists.osgeo.org/mailman/listinfo/gdal-dev
> or other support forums. GitHub issues are for bug
> reports and suggestions for new features.
