### ISSUE TITLE
Missing pixels in gdalwarp output when using `-crop_to_cutline -wo CUTLINE_ALL_TOUCHED=TRUE` in GDAL 3.6.x

### ISSUE THREAD

**Issue by aafaque33** [OSGeo/gdal#8622]
## Expected behavior and actual behavior.

When clipping data via `gdalwarp` recently noticed that GDAL 3.6.3 is missing pixels that are touching the Shape geometry while running same command in the GDLA 3.5.3 includes those pixels.

Same issue is with `gdal_rasterize`
- While looking at the changelogs it seems like there was a change for `gdal_rasterize` in v3.6.0 related to `ALL_TOUCHED` https://github.com/OSGeo/gdal/issues/6414 , not sure if same impacted the `gdalwarp`
- Also wondering if that is expected behavior? if yes then why as it's missing the pixels overlapping the shape geometry

## Steps to reproduce the problem.

- DATA
  - Input raster: [Input.tif.zip](https://github.com/OSGeo/gdal/files/13191234/Input.tif.zip)
  - Shapefile: [Single Feature Polygon Shape.zip](https://github.com/OSGeo/gdal/files/13191230/Single.Feature.Polygon.Shape.zip)
  - Geojson: [Single Feature Polygon.geojson.zip](https://github.com/OSGeo/gdal/files/13191236/Single.Feature.Polygon.geojson.zip)

- Steps
  - We have built our own GDAL 3.6.4 image from source installation of gdal and ran the `gdalwarp` and the output was different than our old GDAL installation (which was GDAL 3.1.2)
  - `gdalwarp -cutline /data/QGIS/layers/POLYGON.shp -crop_to_cutline -wo CUTLINE_ALL_TOUCHED=TRUE -srcnodata 0.0 -dstnodata 0.0 /data/QGIS/Input.tif /data/QGIS/gdalwarp_3.6.4.tif`
  - <img width="1785" alt="Screen Shot 2023-10-27 at 11 38 31 AM" src="https://github.com/OSGeo/gdal/assets/10885595/59ffef34-ad5c-4bbb-b39c-e9cadbe20b31">
  - Previously the output file was creating with `121P x 121L.`
  - To verify if the data is missing some pixels we plotted it in QGIS and it verified that some pixels that were overlapping the Shape geometry (via the options `-crop_to_cutline -wo CUTLINE_ALL_TOUCHED=TRUE`) previously, were missing as shown below
  - Input Raster: 
    - <img width="1236" alt="Screen Shot 2023-10-27 at 11 45 08 AM" src="https://github.com/OSGeo/gdal/assets/10885595/dd9da406-493a-493b-a2ed-01ba9542f83c">
  - Clipped Raster: 
    - <img width="454" alt="Screen Shot 2023-10-27 at 11 45 46 AM" src="https://github.com/OSGeo/gdal/assets/10885595/80a120b2-3af4-4d98-80c9-fbf73476147f">
  - Clipped Raster Zoomed In (top):
    - <img width="916" alt="Screen Shot 2023-10-27 at 11 46 40 AM" src="https://github.com/OSGeo/gdal/assets/10885595/72c44099-f157-46b9-9bff-fd87a46e58ce">

  - We have then tested same via the OSGEO GDAL official docker images and we got same result for the 3.6.3 (missing pixels overlapping / touching the Shape geometry)
  - <img width="1769" alt="Screen Shot 2023-10-27 at 11 49 31 AM" src="https://github.com/OSGeo/gdal/assets/10885595/85d2ba59-8e48-47c0-b3a7-f398a4d76d20">
  - Clipped Raster Zoomed In (top):
    - <img width="1651" alt="Screen Shot 2023-10-27 at 11 51 01 AM" src="https://github.com/OSGeo/gdal/assets/10885595/82f75ebb-9f36-41fc-bc72-1cc6b2f84772">

  - Finally going back versions, we had correct results for GDAL 3.5.3 (official gdal docker image)
  - <img width="1788" alt="Screen Shot 2023-10-27 at 11 52 48 AM" src="https://github.com/OSGeo/gdal/assets/10885595/67770774-e7c3-405e-9f8f-ef60ac8cb74c">
  - Clipped Raster:
    - <img width="1791" alt="Screen Shot 2023-10-27 at 11 54 13 AM" src="https://github.com/OSGeo/gdal/assets/10885595/bb803716-dab3-4ec0-a504-8a16cc405a84">
  - Clipped Raster Zoomed In (top):
    - <img width="1613" alt="Screen Shot 2023-10-27 at 11 54 43 AM" src="https://github.com/OSGeo/gdal/assets/10885595/1208aec6-3cc0-42f4-9a78-49e12505e2cb">
    - <img width="1112" alt="Screen Shot 2023-10-27 at 12 13 27 PM" src="https://github.com/OSGeo/gdal/assets/10885595/a350afa5-d17d-44ef-ae66-0b40fa995300">

## Operating system

Tested on different OS versions and have same results

- Ubuntu 20.04.5 LTS (Focal Fossa)
- Rocky Linux 8.8 (Green Obsidian)
- CentOS Linux 7 (Core)

## GDAL version and provenance

- GDAL 3.6.4, released 2023/04/17 from http://download.osgeo.org/gdal
- GDAL 3.6.3, released 2023/03/07 from https://hub.docker.com/r/osgeo/gdal
- GDAL 3.5.3, released 2022/10/21 from https://hub.docker.com/r/osgeo/gdal

**Comment by aafaque33** [comment]
> Please try the latest Docker image of 3.7.2 to confirm if the issue is still there: `ghcr.io/osgeo/gdal:ubuntu-full-3.7.2`

@rouault same issue withe GDAL 3.7.2 image you have shared

- <img width="1792" alt="Screen Shot 2023-10-27 at 12 29 47 PM" src="https://github.com/OSGeo/gdal/assets/10885595/b5c85b56-d77c-44b4-ac43-81a086f7460f">
- Clipper Raster Zoomed in (top)
  - <img width="1792" alt="Screen Shot 2023-10-27 at 12 30 22 PM" src="https://github.com/OSGeo/gdal/assets/10885595/a9c54ec6-13db-48a8-ac2e-aacf0a9b7383">

**Comment by rouault** [comment]
As far as I can see, after testing, the result in recent versions GDAL version is better than the one of older where pixels that were largely outside of the cutline at the top or the right were included. It now uses a slight tolerance of 0.1% of a pixel size ( 478a85fb6de6c6da0ff700808230df61af2acef2 ) to estimate if a pixel is touching the cutline that didn't exist in past versions, but I find it is for the better as it compensates for numeric precision issues. So I don't see any issue

**Comment by aafaque33** [comment]
> As far as I can see, after testing, the result in recent versions GDAL version is better than the one of older where pixels that were largely outside of the cutline at the top or the right were included. It now uses a slight tolerance of 0.1% of a pixel size ( [478a85f](https://github.com/OSGeo/gdal/commit/478a85fb6de6c6da0ff700808230df61af2acef2) ) to estimate if a pixel is touching the cutline that didn't exist in past versions, but I find it is for the better as it compensates for numeric precision issues. So I don't see any issue

@rouault but isn't `CUTLINE_ALL_TOUCHED=TRUE` purpose is to select all the pixels touching the Geometry Shape Line / Polygon? 

https://gdal.org/api/gdalwarp_cpp.html#_CPPv4N15GDALWarpOptions16papszWarpOptionsE:~:text=the%20GDALWarpOptions.-,CUTLINE_ALL_TOUCHED,-%3A%20This%20defaults%20to
```
CUTLINE_ALL_TOUCHED: This defaults to FALSE, but may be set to TRUE to enable ALL_TOUCHEd mode when rasterizing cutline polygons. This is useful to ensure that that all pixels overlapping the cutline polygon will be selected, not just those whose center point falls within the polygon.
```

**Comment by rouault** [comment]
> This is useful to ensure that that all pixels overlapping the cutline polygon will be selected, not just those whose center point falls within the polygon.

To me, the intent is that if the cutline is extending less than half of a pixel but in a noticeable way (let's say 20%), it is considered as overlapping. Here we are discussing if 0.1% is overlapping or not.
If you strongly rely on the past behaviour (but that seems odd to me to want a pixel being > 99.9% outside of the cutline to be considered overlapping), the don't use -crop_to_cutline and specify the target extent with -te
There are clearly tolerances to be used as soon as floating point numbers are used. The change in https://github.com/OSGeo/gdal/commit/478a85fb6de6c6da0ff700808230df61af2acef2 was done because too small tolerance caused issues in situations where such tiny overlap wasn't intended to be intended, which I assume are more common than situations were it is intented to mean a real overlap
