### ISSUE TITLE
Deleting a field of an empty shapefile corrupts the name of its first field

### ISSUE THREAD

**Issue by agiudiceandrea** [OSGeo/gdal#863]
## Expected behavior and actual behavior.

If you delete a field, e.g, "field2", of an empty (without geometry features) shapefile named "test.shp" with more than one field (e.g. "field1", "field2", ...), than the name of the first field of the resulting shapefile will be corrupted: instead of the correct "field1" it will be wrongly "ield1" (the first character is 0x1a hex that is represented with the symbol "![image](https://user-images.githubusercontent.com/16253859/44207354-2afc2c00-a15d-11e8-86dd-0b4e27cd4a50.png)" on my system).

## Steps to reproduce the problem.

- crate the new shapefile "test.shp" with two field ("field1", "field2") and without any geometry feature
- delete a field (i.e. the second one) with the command:
`ogrinfo test.shp -sql "ALTER TABLE test DROP COLUMN field2"`
- now "test.shp" contains only a field named "ield1" instead of "field1"

The same bug occurs also with the latest QGIS 2.18 / 3 using the tool in the attribute table window of the shapefile layer (actually the bug was [firstly reported](http://osgeo-org.1560.x6.nabble.com/QGIS-2-18-22-LTR-Modifica-arbitraria-del-nome-del-Campo-td5374219.html) on QGIS Italian User mailing list).

## Operating system

Windows 7 64 bit

## GDAL version and provenance

2.2.4 version from OSGeo4W

##
It seems the bug lays in **[dbfopen.c](https://github.com/OSGeo/gdal/blob/release/2.2/gdal/ogr/ogrsf_frmts/shape/dbfopen.c)** (from [maptools shapelib](http://shapelib.maptools.org)) since GDAL 2.2, introduced at 17f59e1105babdecb8ff03c7d1ee7b32d116972f committed by @rouault.

I guess is in DBFDeleteField()

    if( psDBF->bWriteEndOfFileChar )
    {
        char ch = END_OF_FILE_CHARACTER;
        psDBF->sHooks.FWrite( &ch, 1, 1, psDBF->fp );
    }
or in DBFWriteHeader()

    if( psDBF->nRecords == 0 && psDBF->bWriteEndOfFileChar )
    {
        char ch = END_OF_FILE_CHARACTER;

        psDBF->sHooks.FWrite( &ch, 1, 1, psDBF->fp );
    }

**Comment by agiudiceandrea** [comment]
@rouault, given the bug can cause data corruption, though in a limited and unlikely way, will it be fixed also in 2.2?

**Comment by rouault** [comment]
I've just backported to 2.2, but there won't likely be an official GDAL 2.2.x release now that the stable branch is GDAL 2.3

**Comment by agiudiceandrea** [comment]
thank you for the express fix!
