### ISSUE TITLE
Can I create a C# bindings using .Net while building a static gdal Library in MacOS

### ISSUE THREAD

**Issue by huzaifacontour** [OSGeo/gdal#8636]
## Expected behavior and actual behavior.

Gdal should build c# bindings with static libs also.
It's because of this line of code in gdal.cmake file,
if (BUILD_SHARED_LIBS)
  add_subdirectory(swig)
endif ()
Can you explain the reason of it? It should be in the doc also.

## Steps to reproduce the problem.

Build Gdal with BUILD_SHARED_LIBS=OFF

## Operating system

Darwin - 22.6.0 - arm64

## GDAL version and provenance

Configuring GDAL 3.7.2 with cmake 28.0-rc3

**Comment by rouault** [comment]
> Can you explain the reason of it? It should be in the doc also.

see https://github.com/OSGeo/gdal/pull/8637

**Comment by huzaifacontour** [comment]
So is there anyway to use the static GDAL in csharp projects?

**Comment by rouault** [comment]
> So is there anyway to use the static GDAL in csharp projects?

no, I don't thin so. you could try to remove the if (BUILD_SHARED_LIBS) , but I suspect that won't work. That might build, perhaps, but weird things could happen at runtime

**Comment by huzaifacontour** [comment]
Okay thankyou, I think now only solution for this is to go for the dynamic libs.
