### ISSUE TITLE
real(7,6) import from CSV: too larger number with respect to field width

### ISSUE THREAD

**Issue by tobwen** [OSGeo/gdal#865]
When trying to write numeric data from a delimited text file (CSV) with CSVT to SHP, these warning occur:

```
Warning 1: Value 1.00000000000000008e-05 of field field_2 of feature 0 not successfully written. Possibly due to too larger number with respect to field width
Warning 1: Value 2.00000000000000016e-05 of field field_3 of feature 0 not successfully written. Possibly due to too larger number with respect to field width
Warning 1: Value 3.00000000000000008e-05 of field field_4 of feature 0 not successfully written. Possibly due to too larger number with respect to field width
Warning 1: Value 4.00000000000000033e-05 of field field_5 of feature 0 not successfully written. Possibly due to too larger number with respect to field width
Warning 1: Value 5.00000000000000024e-05 of field field_6 of feature 0 not successfully written. Possibly due to too larger number with respect to field width
```

## Steps to reproduce the problem.

content of _demo.csv_
`abcdefghij,0.00001,0.00002,0.00003,0.00004,0.00005`

content of _demo.csvt_
`"String(20)","Real(7.6)","Real(7.6)","Real(7.6)","Real(7.6)","Real(7.6)"`

command line
`ogr2ogr -f "ESRI Shapefile" demo.shp demo.csv`

## Operating system
Windows 7, 64-bit; Windows 10, 64-bit

## GDAL version and provenance
GDAL 2.2.4, released 2018/03/19 from OSGeo4W64

**Comment by rouault** [comment]
your csvt definition should be:
"String(20)","Real(8.6)","Real(8.6)","Real(8.6)","Real(8.6)","Real(8.6)"

In OGR data model (inspired from shapefile dbf), the width.precision is: width = total number of characters including leading minus sign and decimal dot, precision = number of figures after decimal dot.
This is a different convention than Postgre where in NUMERIC(precision, scale), precision = is the total count of significant digits in the whole number, scale = count of decimal digits in the fractional part
This discrepancy causes a number of issues, and we couldn't come with a proprer solution. There is a ticket in Trac and in QGIS as well about that

**Comment by rouault** [comment]
actually 7.5 will do in your case

**Comment by tobwen** [comment]
Thanks, works. But why didn't create this an error with 7.6?

`ogr2ogr -f "GPGK" demo.gpkg demo.csv`

**Comment by rouault** [comment]
GPKG stores real values as IEEE754 values, and completely discard any width.precision

**Comment by tobwen** [comment]
Thanks!
