### ISSUE TITLE
-te_srs EPSG:4326 and TILING_SCHEME=GoogleMapsCompatible incompatible

### ISSUE THREAD

**Issue by Plantain** [OSGeo/gdal#8655]
gdal should be able to handle clipping of the target extent by arbitrary coordinate schemes. Specifying EPSG:4326 and COG + TILING_SCHEME=GoogleMapsCompatible fails.

## Expected behavior and actual behavior.

Actual behaviour:
gdalwarp -of COG -co TILING_SCHEME=GoogleMapsCompatible raw2.tiff out.tiff -te_srs EPSG:4326 -te -90 -65 -20 70
GDAL: GDALOpen(raw2.tiff, this=0x12f707370) succeeds as GTiff.
OGRCT: Point outside of projection domain
OGRCT: Point outside of projection domain
OGRCT: Point outside of projection domain
OGRCT: Point outside of projection domain
GDAL: Could not compute area of interest
ERROR 1: Attempt to create 0x0 dataset is illegal,sizes must be larger than zero.
GDAL: GDALClose(raw2.tiff, this=0x12f707370)

Notably, specifying in EPSG:3857(?) works.
gdalwarp -of COG -co TILING_SCHEME=GoogleMapsCompatible raw2.tiff out.tiff -te -10018754.171 -9607284.341 -2227754.171 11068715.659
Creating output file that is 1558P x 4135L.
0Using internal nodata values (e.g. 0) for image raw2.tiff.
Copying nodata values from source raw2.tiff to destination out.tiff.tmp.tif.
...10...20...30...40...50...60...70...80...90...100 - done.

## Operating system
OS X 14.2, also tested on Ubuntu 22.04

## GDAL version and provenance
GDAL 3.7.2, released 2023/09/05, brew repository

**Comment by jratike80** [comment]
I think that it is just impossible to convert some coordinates from the source CRS into EPSG:4326 because the coordinate transformation functions of the Proj library do not support that. Here is a test (crs.wkt is a text file where I saved the WKT from above).

```
gdaltransform -s_srs crs.wkt -t_srs epsg:4326 --debug on
Enter X Y [Z [T]] values separated by space, and press Return.
-5434894.885, 5434894.885
OGRCT: Point outside of projection domain
transformation failed.

```

Proj tries to do the transformation through this path:

```
Operation No. 1:

unknown id, Transformation from unknown to WGS 84, unknown accuracy, unknown domain of validity

PROJ string:
+proj=pipeline
  +step +inv +proj=geos +sweep=x +lon_0=-75 +h=35786023 +x_0=0 +y_0=0
        +ellps=GRS80 +units=m +no_defs
  +step +proj=unitconvert +xy_in=rad +xy_out=deg
  +step +proj=axisswap +order=2,1
```
By testing the conversion backwards, from EPSG:4326 into the custom CRS, the latitude of -81 degrees is accepted but -82 degrees not.
```
gdaltest>gdaltransform -t_srs crs.wkt -s_srs epsg:4326 --debug on
Enter X Y [Z [T]] values separated by space, and press Return.
-65 -82
OGRCT: Point outside of projection domain
transformation failed.
-65 -81
149338.54391566 -5414179.53918658 0
```
