### ISSUE TITLE
undefined symbol error

### ISSUE THREAD

**Issue by ismaildervisoglu** [OSGeo/gdal#866]
I am getting this error :

ImportError: /home/cisarge/temp.cisarge.com/data-vis/data-vis-libs/lib/python3.6/site-packages/osgeo/_gdal.cpython-36m-x86_64-linux-gnu.so: undefined symbol: GDALDatasetTestCapability

## Expected behavior and actual behavior.

For example: I expected to be able to open this raster file (with a link to
the raster file, or it as an attachment) and it returns an error message
instead.

## Steps to reproduce the problem.

For example: "gdalinfo myfile"

## Operating system

Centos 7.4

## GDAL version and provenance

2.3.1

**Comment by rouault** [comment]
This is likely the sign that your Python bindings are linking against another older GDAL version. Check ldd  /home/cisarge/temp.cisarge.com/data-vis/data-vis-libs/lib/python3.6/site-packages/osgeo/_gdal.cpython-36m-x86_64-linux-gnu.so  . You probably need to define LD_LIBRARY_PATH to point to the directory where a corresponding libgdal.so.2 is found
