### ISSUE TITLE
clang++-18 -Wformat-truncation

### ISSUE THREAD

**Issue by andrew-aitchison** [OSGeo/gdal#8664]
clang++-18 (from llvm-toolchain-snapshot) has a new default option -Wformat-truncation

Attempting* to compile gdal v3.8.0 (any version 3 or even version 2.4.4 show this issue) gives this warning
in frmts/nitf/nitfdataset.cpp

`cd gdal-3.8.0` 
`clang++-18 -Igcore -c -o /dev/null frmts/nitf/nitfdataset.cpp`
frmts/nitf/nitfdataset.cpp:4765:17: warning: 'snprintf' will always be truncated; specified size is 16, but format string expands to at least 17 [-Wformat-truncation]
 4765 |                 snprintf(szGEOLOB + 9 + 9 + 15, sizeof(szGEOLOB) - (9 + 9 + 15),
1 warning generated.

The full line is
```
                snprintf(szGEOLOB + 9 + 9 + 15, sizeof(szGEOLOB) - (9 + 9 + 15),
                         "%#+015.10f", dfPSO);

```
I'm assuming that '#' and '+' each add 1 making 15+1+1 > 16.

This is the only instance of this warning that I could find.

----

*This compiler has bigger problems whilst compiling gdal:
     https://github.com/llvm/llvm-project/issues/67979
but that crash seems to be a bug with the compiler reading comments.

**Comment by rouault** [comment]
This really looks to me like a false positive from the compiler:
```
>>> '%#+015.10f' % 123.4567890123
'+123.4567890123'
>>> len('%#+015.10f' % 123.4567890123)
15
```
Neither # or + add extra characters to the width of 15. Cf https://man7.org/linux/man-pages/man3/printf.3.html for the doc of the format string

**Comment by andrew-aitchison** [comment]
Submitted Clang/LLVM bug https://github.com/llvm/llvm-project/issues/71320
