### ISSUE TITLE
[feature request] SELECT * EXCEPT (for complicated situations)

### ISSUE THREAD

**Issue by tobwen** [OSGeo/gdal#8668]
## tl;dr
Please add a 
- `-excludeField "field1","field2"` or
- `-sql 'SELECT * EXCEPT ("field1", "field2")'` (at least for _OGRSQL_) or
- `-select '!"field1", !"field2"'` (at least for _OGRSQL_)

## summary
I'm converting a multi-layer dataset (MVT) into GPKG. The columns/fields per layer are not equal, but contain at least one equal column, which should be dropped. Since there are more than 50 layers and up to 80 columns, it would be pretty complicated to allowlist create a VRT or similar solution.

For OGRSQL, this might be a nice addition and wouldn't mess with compatibility.

**Comment by jratike80** [comment]
There is already a similar open ticket about this.  While having "except" would be handy, standard SQL does not support it and implementation might get pretty complicated. But maybe you could prototype how you would do it with plain SQL.

**Comment by tobwen** [comment]
> There is already a similar open ticket about this. While having "except" would be handy, standard SQL does not support it and implementation might get pretty complicated. But maybe you could prototype how you would do it with plain SQL.

That's why I mentioned OGRSQL. Is the language tied to standard SQL? I thought you had the freedom to go other ways and implement new functions. There are currently a number of modern databases, such as DuckDB or Clickhouse, which support standard SQL but offer their own extensions. These extensions are not contradictory, as they are simply not used in standard SQL.

I am surprised that the implementation is difficult. Isn't a column label required for each vector format? The column label must be read in somewhere and then skipped by index or string comparison.

In PostgreSQL, I do this either via complex JSONb objects or by querying the table description. However, both are out of the question for most formats (SQLite is unlikely to support either).

**Comment by rouault** [comment]
https://stackoverflow.com/a/58700908 points to extensions adopted by Databricks and DuckDB, that could be reasonable to borrow
```
SELECT * EXCEPT(ColumnNameX, ColumnNameY, ...) FROM tablename
SELECT * EXCLUDE(ColumnNameX, ColumnNameY, ...) FROM tablename
```

**Comment by jratike80** [comment]
The other ticket is https://github.com/OSGeo/gdal/issues/854 and it seems to have a predecessor in the old GDAL trac, so this one has a long a history.
"pretty complicated" was borrowed from your question, similarly allowlisting VRT is not difficult but can be annoying. I guess that implementation into OGR SQL would not be very difficult, but it would be nice to support excludes with all SQL dialects and that could be complicated.

Should it be EXCEPT or EXCLUDE? Bigquery and databricks are using EXCEPT, DuckDB is using EXCLUDE, and SQLite is using EXCEPT to mean something else https://www.sqlitetutorial.net/sqlite-except/.

**Comment by tobwen** [comment]
> similarly allowlisting VRT is not difficult but can be annoying

Does VRT have a denylist or only a allowlist? I'd need to create a XML file from all the layers for all the columns just to ignore TWO. Maybe GPT can do the work for me or even write a Python script to do it?

> I guess that implementation into OGR SQL would not be very difficult, but it would be nice to support excludes with all SQL dialects and that could be complicated.

Do we actually need SQL for this at all? See my first suggestion: `-excludeField "field1","field2"` or an ogr2ogr parameter.
 
> Should it be EXCEPT or EXCLUDE? Bigquery and databricks are using EXCEPT, DuckDB is using EXCLUDE, and SQLite is using EXCEPT to mean something else https://www.sqlitetutorial.net/sqlite-except/.

Indeed, EXCEPT is also used on other SQL languages, so maybe EXCLUDE is better. But since it's in a subcontext of SELECT (like DISTINCT), it might not matter. DISTINCT also doesn't work without SELECT.

**Comment by jratike80** [comment]
Of course if your target is geopackage and you can accept a workaround, use `select *` and once the gpkg is ready, adjust the schema with ogrinfo. I tested that this works.

`ogrinfo exclude.gpkg -sql "alter table rakennus drop column sijaintitarkkuus"`

 The drawback is that the size of the database remains the same until running `-sql "VACUUM"`.

**Comment by tobwen** [comment]
Sure, but also needs lots of scripting... you need to go through each layer, etc.

I guess that won't work for FGB?

**Comment by jratike80** [comment]
I wrote "if your target is geopackage and you can accept a workaround" in a mood that you may be in a hurry and need some task done. Lots of scripting; I am not sure, for me it does not feel like a huge effort to insert table names from a list.

```
ogrinfo exclude.gpkg -sql "alter table $table_name$ drop column column_name"
loop
```

Make a try with FGB, there is a support in OGR SQL https://gdal.org/user/ogr_sql_dialect.html#alter-table.

**Comment by tobwen** [comment]
>  I am not sure, for me it does not feel like a huge effort to insert table names from a list.

Okay, let me go through this for community reasons (maybe it helps someone else).

This is offtopic, but while _gdalinfo_ has nice `-json`, _ogr2ogr_ doesn't. So you're ending with python or bash magick:
```
ogrinfo showmylayers.gpkg | sed -n 's/^[1-9]\+:\s//p'
-or-
ogrinfo showmylayers.gpkg | awk -F': ' '/^[1-9]+:/ {print $2}'
```

leading to
```
ogrinfo showmylayers.gpkg | awk -F': ' '/^[1-9]+:/ {print $2}' | while IFS= read -r layer; do
    ogrinfo showmylayers.gpkg -sql "alter table \"$layer\" drop column column_name"
done
```

**Comment by jratike80** [comment]
> This is offtopic, but while gdalinfo has nice -json, ogrinfo doesn't.

From https://github.com/OSGeo/gdal/blob/v3.8.0RC1/NEWS.md

> ogrinfo: make it accessible through a new GDALVectorInfo() C API call, and a -json switch

Usage example:

```
ogrinfo -json exclude.gpkg
{
  "description":"exclude.gpkg",
  "driverShortName":"GPKG",
  "driverLongName":"GeoPackage",
  "layers":[
    {
      "name":"rakennus",
      "metadata":{
      },
      "geometryFields":[
        {
          "name":"geom",
          "type":"PolygonZ",
          "nullable":true,
          "extent":[
            381556.36599999998,
            6669696.2649999997,
            388435.31699999998,
            6674880.0789999999
          ],
...
```

**Comment by rouault** [comment]
implemented per https://github.com/OSGeo/gdal/pull/8675

**Comment by tobwen** [comment]
@dbaston @rouault Thanks a lot. Good work! This massively streamlines workflows. Thank you very much!

**Comment by jidanni** [comment]
All I know is as of
$ ogrinfo --version
GDAL 3.8.5, released 2024/04/02
All I got were syntax errors. I tried
- SELECT * FROM vermilion_co_il EXCLUDE (Name)
- SELECT * FROM vermilion_co_il EXCLUDE ([Name])
- SELECT * EXCLUDE (Name) FROM vermilion_co_il
- SELECT * EXCLUDE ([Name]) FROM vermilion_co_il
- and even removing the word SELECT.

So I think an actual working example needs to be added after
https://gdal.org/user/ogr_sql_dialect.html#list-operators
> The syntax * EXCLUDE ([fields]) can be used to select all fields except those listed in parentheses.
