### ISSUE TITLE
Setup Error

### ISSUE THREAD

**Issue by rgoalcast** [OSGeo/gdal#867]
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/_x/8x2mhn5n4ps1f2g1rpqx824r0000gn/T/pip-install-t8uyrwu_/GDAL/

How can I solve this problem ?

**Comment by rouault** [comment]
I don't know. I don't think this is a bug in GDAL itself, but something with how you deploy it. A likely explanation is that you don't have the GDAL native libraries when you do pip install. They are required dependencies as explaine in https://pypi.org/project/GDAL/
