### ISSUE TITLE
PG: PQputCopyEnd() hangs when targeting PGPOOL

### ISSUE THREAD

**Issue by boukandouramhamed** [OSGeo/gdal#8674]
## Expected behavior and actual behavior.

When trying to run: 
```
ogr2ogr --config PG_USE_COPY YES -f PostgresQL PG:" dbname='db' host=pgpool_host port=5432 user='postgres' password='postgres' " ... 
```

It hangs at `PQputCopyEnd()`

Checking the  running query in pgpool I can see that the copy query is still active: 

```
 pid  | application_name | state  |                                               query
-------+------------------+--------+---------------------------------------------------------------------------------------------------
  9925 | GDAL 3.4.1       | active | COPY "san_andres_y_providencia_administrative" ("wkb_geometry", "name", "admin_leve") FROM STDIN;
 ```

- `ogr2ogr --config PG_USE_COPY YES ` should be executed fine when targeting PGPOOL. Instead the command hangs at  `PG: PQputCopyEnd()`

- Same command is executed successfully when targeting PostgreSQL instead of PGPOOL.

- When I remove the `--config PG_USE_COPY YES`, the command is executed successfully when targeting PGPOOL.

## Steps to reproduce the problem.

Run the following command against pgpool:
```
ogr2ogr --config PG_USE_COPY YES -f PostgresQL PG:" dbname='db' host=pgpool_host port=5432 user='postgres' password='postgres' "
```

## Operating system

Ubuntu 22.04 (Docker based)

## GDAL version and provenance

GDAL 3.4.1

**Comment by rouault** [comment]
Isn't that a defect of PGPOOL ?

**Comment by rouault** [comment]
I can replicate the issue. I've tried to investigate, but could find a solution, but documenting the issue: https://github.com/OSGeo/gdal/pull/8722

**Comment by giohappy** [comment]
@rouault FYI a solution we found that works pretty well is to pipe the PG dump to psql, as mentioned in the [Postgresql Dump] (https://gdal.org/drivers/vector/pgdump.html) 

```/usr/bin/ogr2ogr -f PGDump /vsistdout/ "example.shp" example | psql -d db  -h pgpool -U postgres -f -```
