### ISSUE TITLE
TILING_SCHEME=GoogleMapsCompatible COG's are blank when created from imagery with space projection

### ISSUE THREAD

**Issue by Plantain** [OSGeo/gdal#8684]
When generating TILING_SCHEME=GoogleMapsCompatible COG's, only blank tiles are cut (when created from imagery with space projection).
Going via an intermediate gdalwarp does work, but takes longer and requires two resampling steps(?).

Sample data:
[http://static2.skysight.io/gdal/raw.tiff](http://static2.skysight.io/gdal/raw.tiff)

Works:
/usr/bin/gdalwarp -of COG -te_srs EPSG:4326 -te -180 -65 -90 70 raw.tiff -t_srs EPSG:3857 cog.tiff

Blank tiles:
/usr/bin/gdalwarp -of COG -co TILING_SCHEME=GoogleMapsCompatible -te_srs EPSG:4326 -te -180 -65 -90 70 raw.tiff -t_srs EPSG:3857 cog-gmap.tiff

Works:
/usr/bin/gdalwarp -of COG -te_srs EPSG:4326 -te -180 -65 -90 70 raw.tiff -t_srs EPSG:3857 cog.tiff
/usr/bin/gdal_translate -of COG cog.tiff -co TILING_SCHEME=GoogleMapsCompatible

## Expected behavior and actual behavior.
gdalwarp should be able to generate Gmap COG's from space projected imagery in one step.

## Operating system

Ubuntu 22.04
## GDAL version and provenance
gdal 3.8.0RC1 from https://github.com/OSGeo/gdal/pkgs/container/gdal/144852017?tag=ubuntu-full-3.8.0

**Comment by jratike80** [comment]
In "blank tiles" you have `-te -180 -65 -90 70 raw.tiff -t_srs EPSG:3857` but no `-te_srs EPSG:4326`. I think that the result shoud be a rather small COG neat the Null Island. Could you make a test?

**Comment by jratike80** [comment]
Do you see similar errors than I do:
```
...10...20...30...40...50...60..ERROR 1: Too many points (525 out of 529) failed to transform, unable to compute output bounds.
Warning 1: Unable to compute source region for output window 5120,0,1024,1024, skipping.
ERROR 1: Too many points (529 out of 529) failed to transform, unable to compute output bounds.
```

**Comment by rouault** [comment]
I got a result which looks correct with latest master, which is equivalent to 3.8.0RC1:
![out](https://github.com/OSGeo/gdal/assets/1192433/59e254eb-4eac-4706-a488-48832f549a31)

**Comment by jratike80** [comment]
I thought that these two commands would do the same thing:
```
gdalwarp -of COG -co TILING_SCHEME=GoogleMapsCompatible -te_srs EPSG:4326 -te -180 -65 -90 70 raw.tiff -t_srs epsg:3857 cog-gmap.tiff
gdalwarp -of COG -co TILING_SCHEME=GoogleMapsCompatible -te_srs EPSG:4326 -te -180 -65 -90 70 raw.tiff  cog-gmap.tiff
```
So, omitting `-t_srs epsg:3857` because having `TILING_SCHEME=GoogleMapsCompatible` means the same. But the commands seem to take very different routes. This alternative is very slow for me

```
gdalwarp -of COG -co TILING_SCHEME=GoogleMapsCompatible -te_srs EPSG:4326 -te -180 -65 -90 70 raw.tiff -t_srs epsg:3857 cog-gmap.tiff
Creating output file that is 19827P x 40920L.
0Using internal nodata values (e.g. 0) for image raw.tiff.
Copying nodata values from source raw.tiff to destination cog-gmap.tiff.tmp.tif.
...10...20...30...40...50...60...70..
```

Is gdalwarp needed at all, shouldn't gdal_translate with `TILING_SCHEME=GoogleMapsCompatible` do the same thing?

**Comment by rouault** [comment]
``docker run --rm -it -v $PWD:$PWD ghcr.io/osgeo/gdal:ubuntu-full-3.8.0 gdalwarp -of COG -co TILING_SCHEME=GoogleMapsCompatible -te_srs EPSG:4326 -te -180 -65 -90 70 $PWD/raw.tiff -t_srs EPSG:3857 $PWD/cog-gmap2.tiff -overwrite`` produces a correct result

The same without -t_srs EPSG:3857 doesn't and generates https://github.com/OSGeo/gdal/issues/8684#issuecomment-1803355982

**Comment by rouault** [comment]
> My thinking was gdal_translate doesn't support -multi for multithreading on the warping to TILING_SCHEME=GoogleMapsCompatible so it would be slower

-multi gives generally super modest performance gains. It just parallelizes I/O from computing. The most performance gains come from multithreading computing too with -wo NUM_THREADS=32 or --config GDAL_NUM_THREADS 32, the later multithreading even more things (like GeoTIFF output compression)

**Comment by jratike80** [comment]
`gdal_translate -of COG -co TILING_SCHEME=GoogleMapsCompatible raw.tiff 3857v2.tiff -projwin -180 70 -90 -65 -projwin_srs EPSG:4326`
This gives a bit different version of the hourglass
<img width="103" alt="image" src="https://github.com/OSGeo/gdal/assets/1751612/4a36f92c-561d-41a8-9627-e3b301f0242e">
And without using `-projwin` the result looks like this. The image data in this version is probably good. The projwin `-projwin -180 70 -90 -65 -projwin_srs EPSG:4326` makes an unexpected clip.
<img width="226" alt="image" src="https://github.com/OSGeo/gdal/assets/1751612/124e75ab-7421-4164-b155-1b855ae27345">

**Comment by jratike80** [comment]
`gdal_translate -of COG -co TILING_SCHEME=GoogleMapsCompatible raw.tiff 3857v2.tiff -projwin -180 70 -90 -65 -projwin_srs EPSG:4326`
This gives a bit different version of the hourglass
<img width="103" alt="image" src="https://github.com/OSGeo/gdal/assets/1751612/4a36f92c-561d-41a8-9627-e3b301f0242e">
And without using `-projwin` the result looks like this. The image data in this version is probably good. The projwin `-projwin -180 70 -90 -65 -projwin_srs EPSG:4326` makes an unexpected clip.
<img width="226" alt="image" src="https://github.com/OSGeo/gdal/assets/1751612/124e75ab-7421-4164-b155-1b855ae27345">
