### ISSUE TITLE
`gdal_rasterize` incorrect result with `-i` flag

### ISSUE THREAD

**Issue by trharris78** [OSGeo/gdal#8689]
When I use a vector to burn zero values into an image, polygons that are inside of holes of other polygons are ignored when using the invert `-i` flag.

This example shows a small image of all 255s and a hand-drawn vector. The vector has two polygons, one box with a hole and the check mark shaped polygon inside of the hole. My goal is to zero out pixels outside of the vector, i.e. the result should contain 255 only where the vector exists.

![image](https://github.com/OSGeo/gdal/assets/12449973/68df368f-ca7c-4984-baa4-07cd1e4255e3)

I run this command:

```bash
cp ones.tif masked_with_geom.tif
gdal_rasterize -burn 0 -i -at geom.geojson masked_with_geom.tif
```

The result shows the 255 pixels of the box shape are preserved, but the inner check mark polygon is ignored.

![image](https://github.com/OSGeo/gdal/assets/12449973/071d346b-a5ec-489c-9b31-5f1434699372)

If I invert the vector myself (compute the vector difference of `extents.geojson` and `geom.geojson`), shown here:

![image](https://github.com/OSGeo/gdal/assets/12449973/dbc425c6-3544-449d-a6d4-68b10f4f3b62)

Then I can get the result I want without the `-i` flag, i.e. I want to burn 0 where the inverted vector exists:

```bash
cp ones.tif masked_with_invgeom.tif
gdal_rasterize -burn 0 -at invgeom.geojson masked_with_invgeom.tif
```

The result shows that the 255 pixels for both the box polygon and the check mark polygon are preserved.

![image](https://github.com/OSGeo/gdal/assets/12449973/19211b86-ef9a-4e16-bc6f-33a0fe0c67d7)

I verified that this happens using the official Docker image: `ghcr.io/osgeo/gdal:ubuntu-small-3.8.0` (host is Intel-based Mac)

[rasterize_data.zip](https://github.com/OSGeo/gdal/files/13313335/rasterize_data.zip)

**Comment by jratike80** [comment]
I can confirm, same happens on Windows with GDAL 3.8.0.
Thank you for the excellent report. Small test data, exact commands. No need to ask any questions from you. That is uncommon.

I tried what happens if I change the order of the geometries in the GeoJSON file but that did not help. I fear I cannot do anything more, let's hope someone else can help you.

**Comment by trharris78** [comment]
I also tried with both a multipolygon and two separate polygons and I think it was the same behavior, although that was with more complex data from when I originally found the problem. I did not try that with this test data since it didn't appear to help before.

**Comment by rouault** [comment]
fix in https://github.com/OSGeo/gdal/pull/8694
