### ISSUE TITLE
PROMOTE_TO_MULTI useage in java

### ISSUE THREAD

**Issue by xian-0304** [OSGeo/gdal#8697]
I want copy shapefile into postgis, and I use the command " ogr2ogr -f "PostgreSQL" PG:"dbname=db user=user password=pwd host=host port=port"  -nln test -nlt PROMOTE_TO_MULTI "D:\spaceData\shp(1)\city_clip.shp" ". it wrok well. but i don't know "PROMOTE_TO_MULTI " how to set in java code

## Steps to reproduce the problem.

    public static void main(String[] args) {
        // Load GDAL library
        gdal.AllRegister();

        // Input File shp and PostGIS connection parameters
        String filePath = "D:\\spaceData\\shp(1)\\city_clip.shp";
        String postgisConnectionString = "PG:dbname=your_db user=user password=pwd " +
                "host=host port=port";

        // Open the File Geodatabase
        DataSource fileDS = ogr.Open(filePath, 0);

        // Open the PostGIS database
        DataSource postgisDS = ogr.Open(postgisConnectionString, 1);
        for (int i =0;i<fileDS.GetLayerCount();i++){
            // Get the layer from the FileDS
            Layer layer = fileDS.GetLayer(i);

            Vector vec =  new Vector();
            // PROMOTE_TO_MULTI doesn't work
            vec.add("PROMOTE_TO_MULTI=YES");
            postgisDS.CopyLayer(layer,"test",vec);
        }

        // Close the data sourcesd
        fileDS.delete();
        postgisDS.delete();
    }

## Operating system

windows 

## GDAL version and provenance

gdal 3.4.1

**Comment by xian-0304** [comment]
the error message "Warning 1: Geometry to be inserted is of type Multi Polygon, whereas the layer geometry type is Polygon."

**Comment by jratike80** [comment]
This feels like a question but I do not close the issue yet even we promise to do so

> IMPORTANT: Do NOT use GitHub to post any questions or support requests!
>            They will be closed immediately and ignored.
> 
> Questions should go to the gdal-dev mailing list at
> https://lists.osgeo.org/mailman/listinfo/gdal-dev
> or other support forums. GitHub issues are for bug
> reports and suggestions for new features.
