### ISSUE TITLE
Add Equal Earth projection

### ISSUE THREAD

**Issue by jdugge** [OSGeo/gdal#870]
Add support for the [Equal Earth projection](http://shadedrelief.com/ee_proj/), which will be included in PROJ 5.2.0 (OSGeo/proj.4/issues/1085).

**Comment by rouault** [comment]
Due to http://gdalbarn.com, projection support in GDAL / PROJ is going to be in flux, so it might not be worth adding the support the current way it is done for now.
As a workaround you can use "+proj=eqearth +wktext" to pass the string unmodified to PROJ (the key is to use +wktext)

**Comment by jdugge** [comment]
Ah yes, with `+wktext` the projection can be used in QGIS without modifying GDAL. Excellent, thank you!

I guess this issue can be closed then?

**Comment by rouault** [comment]
Let it open for now so that we can use it as a reminder to check if that properly works once all the gdalbarn work has been done

**Comment by rouault** [comment]
Equal Earth now supported in GDAL master thanks to PROJ 6
