### ISSUE TITLE
Lack of Documentation related to Arc/Circles and line stroking

### ISSUE THREAD

**Issue by MennoSt** [OSGeo/gdal#8719]
Hi all,

I am looking at the documentation of the CreateFromGML() function. https://gdal.org/api/ogrgeometry_cpp.html#_CPPv4N18OGRGeometryFactory13createFromGMLEPKc

It states that "Arc and Circle elements are stroked to linestring, by using a 4 degrees step, unless the user has overridden the value with the OGR_ARC_STEPSIZE configuration variable." When I am testing the function I don't see any line stroking. Is the documentation wrong or am I missing something?

I already tested with more complex structures but don't see any line stroking. Two simple examples I used with its calculated values with GDAL version 3.7,3 are:

Arc Example GML:
```
"<gml:Curve xmlns:gml=\"http://www.opengis.net/gml\">"
  "<gml:segments>"
    "<gml:Arc>"
      "<gml:posList srsDimension=\"2\">2.000 0.000 2.000 5.000 4.000 0.000</gml:posList>"
    "</gml:Arc>"
 "</gml:segments>"
"</gml:Curve>"
wkbCalculated = "010800000003000000000000000000004000000000000000000000000000000040000000000000144000000000000010400000000000000000";
wktCalculated = CIRCULARSTRING (2 0,2 5,4 0)
```

Circle Example GML:
```
"<gml:Curve xmlns:gml=\"http://www.opengis.net/gml\">"
  "<gml:segments>"
    "<gml:Circle>"
      "<gml:posList srsDimension=\"2\">10.000 10.000 20.000 10.000 20.000 20.000</gml:posList>"
    "</gml:Circle>"
  "</gml:segments>"
"</gml:Curve>"
wkbCalculated =0108000000050000000000000000002440000000000000244000000000000034400000000000002440000000000000344000000000000034400000000000002440000000000000344000000000000024400000000000002440
wktCalculated = CIRCULARSTRING (10 10,20 10,20 20,10 20,10 10)
```

regards, Menno

**Comment by rouault** [comment]
The documentation was indeed reflecting the state of affairs of ancient GDAL versions. Update in https://github.com/OSGeo/gdal/pull/8721
