### ISSUE TITLE
-co NUM_THREADS option behaving weirdly since GDAL 3.6

### ISSUE THREAD

**Issue by ThomasCusson** [OSGeo/gdal#8729]
## Expected behavior and actual behavior.

I previously used a gdal 3.3 environment to make previews, merging numerous files with various projections. I tried to modernize my conda environment, but I have two problems :
- The warping is ~15× slower than before
- The output file is ~30× bigger than before

I identified the source of the problem : it's the usage of `-co NUM_THREADS` with gdal ≥ 3.6, when warping numerous files together.

## Steps to reproduce the problem.

- Make 2 conda environments (gdal_35 and gdal_36)
- Install the corresponding versions of gdal in each environment
- Gdalwarp multiple .tif images together using `-co NUM_THREADS=ALL_CPUS` with both environments.
- Gdalwarp multiple .tif images together **without** using the `-co NUM_THREADS` option in gdal 3.6.
- The image resulting from warping with GDAL 3.6 with `-co NUM_THREADS` option should be much bigger, and should take much longer to process.

Here's the command to reproduce the problem :
`gdalwarp -tr 1000 1000 -t_srs EPSG:3857 input_files_folder/*.tif output_file.tif -co NUM_THREADS=ALL_CPUS -wo NUM_THREADS=ALL_CPUS -co COMPRESS=ZSTD`

It goes smoothly with gdal 3.5, but extremely slow with gdal 3.6, and the compression ratio is worse than no compression at all.
(It's probably a problem of dictionnary compression, when using multiple input files. Because if you warp the obtained file again, the file size goes back to normal.)

Removing the `-co NUM_THREADS` option brings back normal speed and file size.

## Operating system

Ubuntu 22.04.3 LTS 64 bits

## GDAL version and provenance
Version with no problem : gdal 3.5.3 from conda-forge
Versions with the problem : all gdal versions ≥ 3.6.0 from conda-forge

**Comment by ThomasCusson** [comment]
I discovered the problem using a 3.7.3 environment, I tried previous versions to pinpoint the fact that it appeared with 3.6.
I try again using 3.8 and I'll let you see if this changes anything.

**Comment by rouault** [comment]
@ThomasCusson  Can you provide a minimum set of files to reproduce the issue?

**Comment by ThomasCusson** [comment]
Yes, here is a reduced version of my dataset, with only 23 tif files (instead of 20k) :
[11R.zip](https://github.com/OSGeo/gdal/files/13413131/11R.zip)

Here's the command line I used :
`gdalwarp 11R*.tif out.tif -co NUM_THREADS=ALL_CPUS -wo NUM_THREADS=ALL_CPUS -co COMPRESS=ZSTD -co BIGTIFF=YES -srcnodata 0`

The effect on size is way less dramatic (~4.5× bigger instead of 30× bigger), but it's still very noticeable.
![image](https://github.com/OSGeo/gdal/assets/76477570/dd8f2158-bdb4-4047-b1b2-4a698061a8fe)

**Comment by rouault** [comment]
fix in https://github.com/OSGeo/gdal/pull/8784.

however I'd strongly suggest you add -co TILED=YES. Otherwise your method will not scale well on large output files compared to the the maximum size of the GDAL block cache.
