### ISSUE TITLE
Undeterministically broken python bindings

### ISSUE THREAD

**Issue by sebastic** [OSGeo/gdal#873]
As reported by Niko Tyni in [Debian Bug #906222](https://bugs.debian.org/906222)

> it looks like the build system of the gdal Python bindings will
> undeterministically produce truncated or broken files.
>
> I noticed this while debugging a python-stetl test rebuild failure
> on Perl 5.28. The underlying reason was that our local rebuild of
> gdal for Perl 5.28 was broken like this:
> ```
>   # python -c 'import gdal'
>   Traceback (most recent call last):
>     File "<string>", line 1, in <module>
>     File "/usr/lib/python2.7/dist-packages/gdal.py", line 2, in <module>
>       from osgeo.gdal import deprecation_warn
>     File "/usr/lib/python2.7/dist-packages/osgeo/__init__.py", line 21, in <module>
>       _gdal = swig_import_helper()
>     File "/usr/lib/python2.7/dist-packages/osgeo/__init__.py", line 17, in swig_import_helper
>       _mod = imp.load_module('_gdal', fp, pathname, description)
>   ImportError: dynamic module does not define init function (init_gdal)
> ```
> Looking into it further, I rebuilt gdal ten times on current sid/amd64
> and got
>
> - seven almost empty Python 2.7 _gdal.x86_64-linux-gnu.so files
> - five empty Python 2.7 ogr.py files
> - two empty Python 2.7 gdal_array.py files
> - three empty Python 2.7 gdal_array.py files
>
> - four empty Python 3 ogr.py files
> - three empty Python 3 gdal_array.py files (in different builds)
> - four empty Python 3 gdal.py files
> ```
> --rw-r--r-- root/root    525360 2018-07-31 13:37 ./usr/lib/python2.7/dist-packages/osgeo/_gdal.x86_64-linux-gnu.so
> +-rw-r--r-- root/root     13952 2018-07-31 13:37 ./usr/lib/python2.7/dist-packages/osgeo/_gdal.x86_64-linux-gnu.so
> ```
> and so forth.
>
> It looks like at least the s390x build in sid is broken this way, with
> ```
> -rw-r--r-- root/root         0 2018-07-31 12:37 ./usr/lib/python2.7/dist-packages/osgeo/gdal_array.py
> ```
> The test history at
>
>  https://tests.reproducible-builds.org/debian/rb-pkg/unstable/amd64/gdal.html
>
> seems rather sad too.
>
> I haven't located the cause yet; diffing build logs makes me wonder if
> the 'generate' target of `swig/python/GNUmakefile` is getting erroneously
> run in parallel with targets compiling the files that 'generate' modifies.
> So maybe it's just a case of fragility on parallel builds?

## Operating system

For example: Debian unstable

## GDAL version and provenance

2.3.1 from Debian unstable

**Comment by rouault** [comment]
I see in the build log of https://tests.reproducible-builds.org/debian/logs/unstable/amd64/gdal_2.3.1+dfsg-2.build2.log.gz that one of the step is
```
/usr/bin/make -j15 -C /build/gdal-2.3.1+dfsg/2nd/swig/python generate build; \
```

The generate and build targets can't be safely run in parallel. So a simple fix is just to split that in two separate commands. It would be better to have "make generate build" to be parallel-proof. One obvious way would be to make build depend on generate, but sometimes we may want to build without necessary regenerating, so I'm not sure how to enforce they can't run in parallel

**Comment by sebastic** [comment]
That seems to confirms Niko's suspicion. I also thought that the various sed commands in the generate target weren't very parallel safe, so I uploaded a new revision of the gdal package which removes `-j<N>` from the generate target, see:

 https://salsa.debian.org/debian-gis-team/gdal/compare/debian%2F2.3.1+dfsg-2...debian%2F2.3.1+dfsg-3

Since I haven't been able to reproduce the issue on my own systems, we'll need to see if the various Debian systems can still reproduce the issue now.

**Comment by sebastic** [comment]
The builds on the buildds and the reproducible builds look better, none of them seem to suffer from this issue at least. So I think we can consider it fixed.
