### ISSUE TITLE
GDAL 3.7.2 Crashing when using with spatialite on macOS while creating .sqlite database

### ISSUE THREAD

**Issue by huzaifacontour** [OSGeo/gdal#8736]
## Expected behavior and actual behavior.

It should create a database with spatialite and open it successfully.
But iOS application is crashing when creating the database although Gdal.RegisterAll working fine.
And It's also working fine without spatialite.

## Steps to reproduce the problem.

compile gdal 3.7.2 with spatialite on macOS, create a database with spatialite extension.

## Operating system

Mac Mini

## GDAL version and provenance

GDAL Version: 3.7.2
Spatialite version: 5.1.0 (compiled with proj-9.3.0 and geos-3.12.0)

## Compilation Makefile Code:

**SPATIALITE CONFIGURATION CODE:**

cd spatialite \
**CXX**=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ \
**CC**=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang \
**CFLAGS**="-isysroot ${OSX_SYSROOT} -I${OSX_SYSROOT}/usr/include -arch x86_64 -I${PREFIX}/include -I/opt/homebrew/opt/readline/include -miphoneos-version-min=15.0" \
**CXXFLAGS**="-isysroot ${OSX_SYSROOT} -I${OSX_SYSROOT}/usr/include -arch x86_64 -I${PREFIX}/include -I/opt/homebrew/opt/readline/include  -miphoneos-version-min=15.0" \
**LDFLAGS**="-isysroot ${OSX_SYSROOT} -L${PREFIX}/lib -L${OSX_SYSROOT}/usr/lib -arch x86_64 -L/opt/homebrew/opt/readline/lib -miphoneos-version-min=15.0" \
**PKG_CONFIG_PATH**="${PREFIX}/lib/pkgconfig" \
**./configure** --host=x86_64-apple-darwin --prefix=${PREFIX} --with-geosconfig=${PREFIX}/bin/geos-config --enable-static=no --enable-freexl=no --enable-minizip=no --enable-gcp=no --enable-rttopo=no && make clean install

**GDAL CONFIGURATION CODE:**
cd gdal && mkdir build && cd build && env LIBTOOL=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool \
cmake \
-DCMAKE_OSX_SYSROOT=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator17.0.sdk \
-DCMAKE_SYSTEM_NAME=iOS \
-DCMAKE_OSX_ARCHITECTURES="x86_64" \
-DCMAKE_MACOSX_BUNDLE=${PREFIX} \
-DCMAKE_PREFIX_PATH=${PREFIX}/lib/pkgconfig \
-DCMAKE_C_COMPILER="/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang" \
-DCMAKE_CXX_COMPILER="/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++" \
-DCMAKE_INSTALL_PREFIX=${PREFIX} \
-DCMAKE_C_FLAGS="-isysroot ${OSX_SYSROOT} -I${OSX_SYSROOT}/usr/include -arch x86_64 -I${PREFIX}/include -I/opt/homebrew/opt/readline/include -miphoneos-version-min=15.0 -Wimplicit-function-declaration" \
-DCMAKE_CXX_FLAGS="-isysroot ${OSX_SYSROOT} -I${OSX_SYSROOT}/usr/include -arch x86_64 -I${PREFIX}/include -I/opt/homebrew/opt/readline/include  -miphoneos-version-min=15.0 -Wimplicit-function-declaration" \
-DCMAKE_EXE_LINKER_FLAGS="-isysroot ${OSX_SYSROOT} -L${PREFIX}/lib -L${OSX_SYSROOT}/usr/lib -arch x86_64 -L/opt/homebrew/opt/readline/lib -miphoneos-version-min=15.0 -lz -liconv -lsqlite3" \
-DGDAL_USE_PNG_INTERNAL=ON \
-DGDAL_USE_JPEG_INTERNAL=ON \
-DGDAL_USE_ZLIB_INTERNAL=ON \
-DGDAL_USE_TIFF_INTERNAL=ON \
-DGDAL_USE_GEOTIFF_INTERNAL=ON \
-DGDAL_USE_ZSTD=OFF \
-DGDAL_USE_OPENSSL=OFF \
-DGDAL_USE_HDF5=OFF \
-DGDAL_USE_HDF4=OFF \
-DGDAL_USE_FREEXL=OFF \
-DGDAL_USE_EXPAT=OFF \
-DCMAKE_DISABLE_FIND_PACKAGE_Arrow=ON \
-DGDAL_USE_LIBKML=OFF \
-DIconv_INCLUDE_DIR=${PREFIX}/include \
-DIconv_LIBRARY=${PREFIX}/lib/libiconv.dylib \
-DPROJ_INCLUDE_DIR=${PREFIX}/include \
-DPROJ_LIBRARY_RELEASE=${PREFIX}/lib/libproj.dylib \
-DGEOS_CONFIG=${PREFIX}/bin/geos-config \
-DGEOS_INCLUDE_DIR=${PREFIX}/include \
-DGEOS_LIBRARY=${PREFIX}/lib/libgeos_c.dylib \
-DSQLite3_INCLUDE_DIR=${PREFIX}/include \
-DSQLITE3EXT_INCLUDE_DIR=${PREFIX}/include \
-DSQLite3_LIBRARY=${PREFIX}/lib/libsqlite3.dylib \
-DSQLite3_HAS_COLUMN_METADATA:INTERNAL= \
-DSPATIALITE_INCLUDE_DIR=${PREFIX}/include \
-DSPATIALITE_LIBRARY=${PREFIX}/lib/libspatialite.dylib \
-DBUILD_PYTHON_BINDINGS=OFF \
-DBUILD_JAVA_BINDINGS=OFF \
-DCSHARP_LIBRARY_VERSION="net7.0" \
-DCSHARP_APPLICATION_VERSION="net7.0" \
-DCMAKE_BUILD_TYPE=Release \
-DCMAKE_CONFIGURATION_TYPES=Release  .. && cmake --build . && cmake --build . --target install

**Comment by rouault** [comment]
Is it hard crashing (segmentation fault), if so it would be useful that you run under a debugger and provide the stack trace, or emitting an error message ?

**Comment by huzaifacontour** [comment]
This is what I'm getting:


=================================================================
	Native stacktrace:
=================================================================
	0x10ddbd774 - /Users/me/Library/Developer/CoreSimulator/Devices/D32C295C-8272-4490-BB66-75F1A6A8E462/data/Containers/Bundle/Application/BBEC21B7-B4BE-4696-8AEB-EFCC770E399C/Gdal.iOSNew.Tests.app/libmonosgen-2.0.dylib : mono_dump_native_crash_info
	0x10dd61a8e - /Users/me/Library/Developer/CoreSimulator/Devices/D32C295C-8272-4490-BB66-75F1A6A8E462/data/Containers/Bundle/Application/BBEC21B7-B4BE-4696-8AEB-EFCC770E399C/Gdal.iOSNew.Tests.app/libmonosgen-2.0.dylib : mono_handle_native_crash
	0x10df6be18 - /Users/me/Library/Developer/CoreSimulator/Devices/D32C295C-8272-4490-BB66-75F1A6A8E462/data/Containers/Bundle/Application/BBEC21B7-B4BE-4696-8AEB-EFCC770E399C/Gdal.iOSNew.Tests.app/libmonosgen-2.0.dylib : sigabrt_signal_handler.cold.1
	0x10ddbd0a8 - /Users/me/Library/Developer/CoreSimulator/Devices/D32C295C-8272-4490-BB66-75F1A6A8E462/data/Containers/Bundle/Application/BBEC21B7-B4BE-4696-8AEB-EFCC770E399C/Gdal.iOSNew.Tests.app/libmonosgen-2.0.dylib : sigabrt_signal_handler
	0x1252155ed - /usr/lib/system/libsystem_platform.dylib : _sigtramp
	0x30cdcb4a0 - Unknown
	0x2048e6009 - Unknown
	0x10ce15c91 - Unknown
	0x10cdcae6e - Unknown
	0x10cded106 - Unknown
	0x1856ecbc8 - /Users/me/Library/Developer/CoreSimulator/Devices/D32C295C-8272-4490-BB66-75F1A6A8E462/data/Containers/Bundle/Application/BBEC21B7-B4BE-4696-8AEB-EFCC770E399C/Gdal.iOSNew.Tests.app/lib/libspatialite.dylib : spatialite_alloc_reentrant
	0x1856ead29 - /Users/me/Library/Developer/CoreSimulator/Devices/D32C295C-8272-4490-BB66-75F1A6A8E462/data/Containers/Bundle/Application/BBEC21B7-B4BE-4696-8AEB-EFCC770E399C/Gdal.iOSNew.Tests.app/lib/libspatialite.dylib : spatialite_alloc_connection
	0x187dec769 - /Users/me/Library/Developer/CoreSimulator/Devices/D32C295C-8272-4490-BB66-75F1A6A8E462/data/Containers/Bundle/Application/BBEC21B7-B4BE-4696-8AEB-EFCC770E399C/Gdal.iOSNew.Tests.app/lib/libgdal.dylib : _ZN19OGRSQLiteDataSource4OpenEP12GDALOpenInfo
	0x187df26ff - /Users/me/Library/Developer/CoreSimulator/Devices/D32C295C-8272-4490-BB66-75F1A6A8E462/data/Containers/Bundle/Application/BBEC21B7-B4BE-4696-8AEB-EFCC770E399C/Gdal.iOSNew.Tests.app/lib/libgdal.dylib : _ZL19OGRSQLiteDriverOpenP12GDALOpenInfo
	0x187f214ab - /Users/me/Library/Developer/CoreSimulator/Devices/D32C295C-8272-4490-BB66-75F1A6A8E462/data/Containers/Bundle/Application/BBEC21B7-B4BE-4696-8AEB-EFCC770E399C/Gdal.iOSNew.Tests.app/lib/libgdal.dylib : GDALOpenEx
	0x187efd633 - /Users/me/Library/Developer/CoreSimulator/Devices/D32C295C-8272-4490-BB66-75F1A6A8E462/data/Containers/Bundle/Application/BBEC21B7-B4BE-4696-8AEB-EFCC770E399C/Gdal.iOSNew.Tests.app/lib/libgdal.dylib : OGR_Dr_Open
	0x182dd56d9 - /Users/me/Library/Developer/CoreSimulator/Devices/D32C295C-8272-4490-BB66-75F1A6A8E462/data/Containers/Bundle/Application/BBEC21B7-B4BE-4696-8AEB-EFCC770E399C/Gdal.iOSNew.Tests.app/lib/libogr_wrap.dylib : CSharp_OSGeofOGR_Driver_Open___
	0x182a53c6a - Unknown

=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x2048cbc52):0x2048cbc42  48 8b 00 c3 90 90 b8 09 02 00 02 49 89 ca 0f 05  H..........I....
0x2048cbc52  73 08 48 89 c7 e9 14 75 f9 ff c3 90 90 90 b8 68  s.H....u.......h
0x2048cbc62  01 00 02 49 89 ca 0f 05 73 08 48 89 c7 e9 fc 74  ...I....s.H....t
0x2048cbc72  f9 ff c3 90 90 90 b8 de 01 00 02 49 89 ca 0f 05  ...........I....

=================================================================
	Managed Stacktrace:
=================================================================
	  at <unknown> <0xffffffff>
	  at OSGeo.OGR.OgrPINVOKE:Driver_Open <0x00159>
	  at OSGeo.OGR.Driver:Open <0x00132>
	  at ModuleInitializer:Initialize <0x009e2>
	  at <Module>:.cctor <0x00062>
	  at System.Object:runtime_invoke_void <0x001a4>
	  at <unknown> <0xffffffff>
	  at <unknown> <0xffffffff>
	  at SigmaSeven.Gdal.Native.iOS.Tests.GdalTest:CoordinateTransformation <0x0017a>
	  at Gdal.iOSNew.Tests.AppDelegate:FinishedLaunching <0x004ba>
	  at <Module>:runtime_invoke_bool__this___object_object <0x00125>
	  at <unknown> <0xffffffff>
	  at UIKit.UIApplication:xamarin_UIApplicationMain <0x0024a>
	  at UIKit.UIApplication:UIApplicationMain <0x00122>
	  at UIKit.UIApplication:Main <0x0054a>
	  at Program:<Main>$ <0x000a2>
	  at <Module>:runtime_invoke_void_object <0x00110>
=================================================================

**Comment by rouault** [comment]
So you are using the C# bindings ? What if you try command line tools like ogr2ogr ?

**Comment by huzaifacontour** [comment]
Receiving this on command line for x86_64 using Plaform=iPhoneSimulator
```
${Prefix}/bin % ./ogr2ogr
dyld[27116]: dyld_sim file could not be opened
zsh: abort      ./ogr2ogr
```
Receiving this on command line for arm64 using Plaform=iPhoneOS
```
bin % ./ogr2ogr
zsh: killed     ./ogr2ogr
```

**Comment by rouault** [comment]
well, it seems you've a configuration issue regarding ogr2ogr... Perhaps some missing DYLD_LIBRARY_PATH ?  I can't really help for iOS things as I'm illiterate with that platform

**Comment by huzaifacontour** [comment]
Already tried that nothing happened.
Although I configured gdal and spatialite with almost same code on Linux using ndk and that works like a charm.

**Comment by huzaifacontour** [comment]
Resolved this by compiling the static libspatialite and then linking it to the dynamic libgdal.
Thanks for all your efforts @rouault
