### ISSUE TITLE
ar

### ISSUE THREAD

**Issue by Amos-Zhao** [OSGeo/gdal#874]
## Expected behavior and actual behavior.

For example: I expected to be able to open this raster file (with a link to
the raster file, or it as an attachment) and it returns an error message
instead.

## Steps to reproduce the problem.

For example: "gdalinfo myfile"

## Operating system

For example: Ubuntu 16.04 64 bit

## GDAL version and provenance

For example: the 2.2.3 version from ubuntugis-unstable PPA

**Comment by jratike80** [comment]
I do not see any links or attachments.

**Comment by rouault** [comment]
This ticket has been created with the default text untouched. Closing assuming it is an error
