### ISSUE TITLE
Can I build GDAL shared library using static dependency libraries?

### ISSUE THREAD

**Issue by huzaifacontour** [OSGeo/gdal#8742]
## Expected behavior and actual behavior.

GDAL should build dynamically with swig bindings successfully.
I'm facing an error of undefined reference on this step:
Linking CXX shared library libgdal.dylib
Maybe I need to add some options?

## Steps to reproduce the problem.

Build gdal dynamically with static libs.

## Operating system

Mac Mini

## GDAL version and provenance

GDAL 3.7.2

**Comment by rouault** [comment]
cf https://github.com/OSGeo/gdal/issues/8636 or https://github.com/OSGeo/gdal/issues/7955
