### ISSUE TITLE
Build error with libxml2 2.12

### ISSUE THREAD

**Issue by rouault** [OSGeo/gdal#8746]
Fixed per https://github.com/OSGeo/gdal/commit/cbed9fc91dffba30d0f9a6a06a412a04d9cd36fa and https://github.com/OSGeo/gdal/commit/ec33f6d6dfe944f59dc5454d01b4d000d9479c02

**Comment by dg0yt** [comment]
Why is one change with `LIBXML_VERSION >= 21200` and the other without?

**Comment by rouault** [comment]
> Why is one change with `LIBXML_VERSION >= 21200` and the other without?

A change of constness in the argument of the callback changes its type (in C++ at least), so there's no way of supporting before and after 2.12 with the same code.
Changing a local variable from ``xmlError *pErrorPtr`` to ``const xmlError *pErrorPtr` when you don't mutate the pointed object works with all versions.

**Comment by rouault** [comment]
Fixed in GDAL 3.8.1RC2
