### ISSUE TITLE
How to export a list files (.tiff) from HDF format (MODIS product) using gdal.Warp in python?

### ISSUE THREAD

**Issue by tazrart** [OSGeo/gdal#8756]
Dear all, 

I have a list of HDF files from MODIS product (see in attached). I want import them in python using GDAL library. Show my steps and explanation in the code below : `

 1.   Import required libraries :

    from osgeo import gdal
    import glob
       
2. Define the link to the folders :
    
    inDir="...inputs/modis/MOD13A2v061/"
    outDir="...outputs/modis/MOD13A2v061/""
    mask = "..../extent.shp"
  
3. Import a list files with glob :

![hdf_files](https://github.com/OSGeo/gdal/assets/36005324/3e0d6cb6-3051-4887-a347-ed4979c37408)
   
    files_hdf = glob.glob(inDir + '*.hdf')

```
4. After I want use a for loop to display HDF files and extract only
 "NDVI" variable      # (index=0) using "gdal.open" function and after
I want export all the files in geotiff #format (and clipped them with
 mask) using 'gdal.Warp' function ==> But a the end I have # error !!!
 (see below my code step) 
```

   ```
 kwargs = {'format': 'GTiff', 'dstSRS': '+proj=sinu +lon_0=0 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m +no_defs'}


    for data_path in files_hdf:
            dataset = gdal.Open(data_path, gdal.GA_ReadOnly)
            subdataset =  gdal.Open(dataset.GetSubDatasets()[0][0], gdal.GA_ReadOnly)
            outfile_name = os.path.join(outDir, makeFileName(item, 'NDVI', 'tif'))
            ds = gdal.Warp(destNameOrDestDS=outfile_name,srcDSOrSrcDSTab=subdataset, cutlineDSName=mask, *kwargs) 
```

### At the end I have this error :

`> ### TypeError: Warp() got multiple values for argument 'destNameOrDestDS'`

I think the problem provided when exported a list of files with gdal.Warp, can you help me to improve the script?

Many thanks!

**Comment by jratike80** [comment]
Does this does feel like a question or support request?

> IMPORTANT: Do NOT use GitHub to post any questions or support requests!
>            They will be closed immediately and ignored.
> 
> Questions should go to the gdal-dev mailing list at
> https://lists.osgeo.org/mailman/listinfo/gdal-dev
> or other support forums. GitHub issues are for bug
> reports and suggestions for new features.
