### ISSUE TITLE
Possible regression in date parsing in GDAL 3.8.0

### ISSUE THREAD

**Issue by arredond** [OSGeo/gdal#8759]
## Expected behavior and actual behavior.

In GDAL 3.7.2, a GPKG with a `Date` column containing a record like `2022/9/8` is successfully parsed despite being non-conformant. In GDAL 3.8.0, this record is no longer parsed and detected as invalid instead.

## Steps to reproduce the problem.

ZIP with GPKG to reproduce: [column_types.zip](https://github.com/OSGeo/gdal/files/13413428/column_types.zip)

### In GDAL 3.7.2

The following code raises two warnings:

```
from osgeo import ogr
ds = ogr.Open('column_types.gpkg')
layer = ds.GetLayer()
layer.GetFeatureCount() # Only 1 feature
for feature in layer:
    print(feature)

# Warnings
# Warning 1: Non-conformant content for record 1 in column a_date_column, 2022/9/8, successfully parsed
# Warning 1: Non-conformant content for record 1 in column a_datetime_column, 2022-09-08 12:29:29.000Z, successfully parsed
```

### In GDAL 3.8.0

The same code raises a different first warning:

```
Warning 1: Invalid content for record 1 in column a_date_column: 2022/9/8
Warning 1: Non-conformant content for record 1 in column a_datetime_column, 2022-09-08 12:29:29.000Z, successfully parsed
```

## Operating system

Amazon Linux 2 2.0.20231101.0

## GDAL version and provenance

GDAL 3.8.0 built from source.

**Comment by jratike80** [comment]
I am not sure how big effort GDAL should do by trying to deal with invalid GeoPackages. I do understand the pain that the user has when they would really need to get the data, and also that they often do not know very much about SQL and SQlite. And I do know that dates and datetimes are tricky and especially in SQLite.

I tested two methods:
- With DB Browser for SQLite it is possible to correct the data type of the column from the user interface
<img width="179" alt="image" src="https://github.com/OSGeo/gdal/assets/1751612/c1986be8-a9e8-4524-8010-3e7195ecf877">

- With standard SQL there are different possibilities, one straight-forward one is this:
`ogrinfo column_types.gpkg -sql "alter table tracks add column a_custom_date_column TEXT"`
`ogrinfo column_types.gpkg -sql "update tracks set a_custom_date_column=a_date_column"`

I would then drop the "a_date_column" but even without dropping ogrinfo shows now.
```
a_bool_column (Integer(Boolean)) = 1
  a_datetime_column (DateTime) = 2022/09/08 12:29:29+00
  a_custom_date_column (String) = 2022/9/8

```

**Comment by rouault** [comment]
Things were harden in dfabbcf5815c2774831bff86e2e0d6e9b5795989 to fix https://github.com/OSGeo/gdal/issues/8150, to avoid false positive detection of time for GeoJSON. In the context of GPKG, where we know the type, perhaps we could be indeed more lax

**Comment by jratike80** [comment]
Lax in reading is OK but GDAL should still not write non-compliant GeoPackages. If a conversion
`ogr2ogr -f gpkg copy.gpkg column_types.gpkg `
succeeds the copy.gpkg should either have dates guessed and converted into correct formula, or data type of the field changed into string.

**Comment by rouault** [comment]
> Lax in reading is OK but GDAL should still not write non-compliant GeoPackages.

agreed. The GPKG driver works from an internal representation, and thus renormalizes the output in a conformant way

Fix in https://github.com/OSGeo/gdal/pull/8762
