### ISSUE TITLE
New feature suggestion: Add support for Nat Geo Topo TPQ format

### ISSUE THREAD

**Issue by ndoggac** [OSGeo/gdal#877]
Add support for "National Geographic Topo" proprietary format (.TPQ).  It's a proprietary binary format wrapped around tiles of topographical raster data in JPG and PNG formats.  The binary format has already been decoded at the site below, so that might make things easier.

http://cholla.mmto.org/computers/topomaps/

**Comment by jratike80** [comment]
I feel it is unlikely that this happens very soon.

**Comment by ndoggac** [comment]
I forgot I posted here.  I ended up writing it myself.  I was able to export the bit perfect JPG/PNGs from the TPQ files and stitch them up into a KMZ archive.  From those I converted to multilayer MBTILEs for use on mobile devices.

The code works on Nat Geo Topo & Trails Illustrated products.

https://github.com/ndoggac/tpq2jpg2kml

**Comment by rouault** [comment]
closing. someone interested will be able to find it
