### ISSUE TITLE
create large netcdf files with gdal c++

### ISSUE THREAD

**Issue by jbensabat** [OSGeo/gdal#8770]
Hello
I am trying to write a large raster file using NETCDF. I get a error code -62 from Netcdf which I know is due that the file is over 2GB.
when I do that directly from Netcdf I just add the option LargeFile or Netrcdf4Classic
How can I set this option ?

GDALDataset* poDstDS;
const char** papszOptions= NULL;
const char* pszDstFilename = "myfile.nc";
poDstDS = poDriver->Create(pszDstFilename, nx, ny, 1, GDT_Float32,papszOptions);

thanks 
jac

## Expected behavior and actual behavior.

For example (please modify !!!): I expected to be able to open this raster file (with a link to
the raster file, or it as an attachment) and it returns an error message
instead.

## Steps to reproduce the problem.

For example (please modify !!!): "gdalinfo myfile"

## Operating system

For example (please modify !!!): Ubuntu 16.04 64 bit

## GDAL version and provenance

For example (please modify !!!): the 2.2.3 version from ubuntugis-unstable PPA

**Comment by rouault** [comment]
try:
papszOptions = CSLSetNameValue(papszOptions, "FORMAT", "NC4C")
Cf https://gdal.org/drivers/raster/netcdf.html#creation-options

**Comment by jbensabat** [comment]
thanks it works
best 
jac
