### ISSUE TITLE
Failed to find template header file header.dxf for reading

### ISSUE THREAD

**Issue by michkowalczuk** [OSGeo/gdal#8790]
## Expected behavior and actual behavior.

Can not write a DXF file because of the following error:
```
[Wed Nov 22 19:13:20 2023].0540, 41.9040: GDAL: GDALDriver::Create(DXF,D:\GisData\geoportal\BDOT10k\warszawa\out\bridge.dxf,0,0,0,Unknown,0000000000000000)
[Wed Nov 22 19:13:20 2023].0550, 41.9050: CPLError: Failed to find template header file header.dxf for reading,
is GDAL_DATA set properly?
ERROR 4: Failed to find template header file header.dxf for reading,
is GDAL_DATA set properly?
```
## Steps to reproduce the problem.

- I use `CPLSetConfigOption` to pass `'GDAL_DATA'` config option and set path to `share\gdal` folder. This folder definitely contains `header.dxf` file.

- Then I check the config option using `GetEnvironmentVariable('GDAL_DATA')`. Method returns me the same path I passed before.

- `GDALCreate` returns NULL and returns the above error.

Furthermore, I programmatically set environmental variable using [SetEnvironmentVariable from WIN API](https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-setenvironmentvariable) with no effect.

EDIT: I must add that using the same method I add `PROJ_DATA` and GDAL finds `proj.db`.

## Operating system

Windows 11 x64

## GDAL version and provenance

GDAL 3.7.2 C API

**Comment by rouault** [comment]
I suspect a usage issue. Are there non-ASCII characters in the value of GDAL_DATA?  If so, you need to UTF-8 encode the string

**Comment by michkowalczuk** [comment]
> I suspect a usage issue. Are there non-ASCII characters in the value of GDAL_DATA? If so, you need to UTF-8 encode the string

The actual string is "D:\Projects\geopackage\sp-geopackage-import\bin\share\gdal", so that's not the problem.

**Comment by jratike80** [comment]
Can you write dxf with GDAL binaries?

**Comment by michkowalczuk** [comment]
> Can you write dxf with GDAL binaries? `ogr2ogr -f dxf test.dxf test.json` That works for me and my gdal_data seems to be `GDAL_DATA=C:\OSGeo4W\apps\gdal\share\gdal` Might be good to test if the issue affects also the binaries or just the code.

I use Conda distribution (not OSGeo) and by default get the same error. If I set GDAL_DATA environmental variable in windows It passes.

**Comment by jratike80** [comment]
How about backslashes, what if they are considered to mean escapes? Have you tried with forward ones, or with double `\\`?

**Comment by michkowalczuk** [comment]
> How about backslashes, what if they are considered to mean escapes? Have you tried with forward ones, or with double `\\`?

Tested all possible combinations. As I mentioned at the start. GDAL can recognize `PROJ_DATA` path, but `GDAL_DATA `no.

**Comment by jratike80** [comment]
I would double check that PROJ_DATA works even if it is in `D:\Projects\geopackage\sp-geopackage-import\bin\share\proj`.

**Comment by michkowalczuk** [comment]
> I would double check that PROJ_DATA works even if it is in `D:\Projects\geopackage\sp-geopackage-import\bin\share\proj`. Or maybe it is already, I just don't know.

Yes, it is.

**Comment by michkowalczuk** [comment]
Dose somebody know why GDAL uses `"gdal"` argument in `CPLFindFile` function, not `"gdal_data"` when looking for `"header.dxf"`?
Maybe this is some clue?
<img width="428" alt="image" src="https://github.com/OSGeo/gdal/assets/23641410/0357bc98-65a7-4edd-b6ab-ca8a912fb9d1">

**Comment by rouault** [comment]
> Dose somebody know why GDAL uses `"gdal"` argument in `CPLFindFile` function,

No, this is normal. Cf https://github.com/OSGeo/gdal/blob/0fe09b61d751916623e53252e51047ec40853814/port/cpl_findfile.cpp#L166

Something's wrong in your setup, but I'm not sure what

**Comment by michkowalczuk** [comment]
> > Dose somebody know why GDAL uses `"gdal"` argument in `CPLFindFile` function,
> 
> No, this is normal. Cf
> 
> https://github.com/OSGeo/gdal/blob/0fe09b61d751916623e53252e51047ec40853814/port/cpl_findfile.cpp#L166
> 
> Something's wrong in your setup, but I'm not sure what

Yes, it looks strange.
Notice that I did not get `"Cannot find %s (GDAL_DATA is not defined)"` error from 169 line.
It means that `CPLGetConfigOption("GDAL_DATA", nullptr))` returns something (True).

**Comment by michkowalczuk** [comment]
@rouault @jratike80 ,

I found the problem!
When I remove dashes from path it passes.

`D:\Projects\geopackage\sp-geopackage-import\bin\share\gdal` -> `D:\Projects\geopackage\spgeopackageimport\bin\share\gdal`

Is there any solution for this?

**Comment by michkowalczuk** [comment]
I found it!
The problem is on the string conversion side.
I'm working  on Delphi wrapper for GDAL and convert Delphi string to C char*.

So far the conversion below has worked:
`Result := PUTF8Char(AnsiString(aStr));`

After changing the conversion function to use UTF8String, it started working. :-)
`Result := PUTF8Char(UTF8String(aStr));`
