### ISSUE TITLE
gdal_footprint with RGBA imagery alpha channel overviews fails

### ISSUE THREAD

**Issue by blacha** [OSGeo/gdal#8792]
## Expected behavior and actual behavior.

I have some aerial imagery tiffs that are 4 channel RGBA, with overviews stored as COGS.

When using the `gdal_footprint` I can generate the footprint with the root image, but not with any overviews

## Steps to reproduce the problem.

Works:
```bash
gdalinfo \
  /vsicurl/https://nz-imagery.s3.ap-southeast-2.amazonaws.com/gisborne/gisborne-cyclone-gabrielle_2023_0.2m/rgb/2193/BF43_5000_0404.tiff 
```

Fails
```bash
gdal_footprint \
  /vsicurl/https://nz-imagery.s3.ap-southeast-2.amazonaws.com/gisborne/gisborne-cyclone-gabrielle_2023_0.2m/rgb/2193/BF43_5000_0404.tiff \
  output.geojson -ovr 4
ERROR 1: Overview index 4 invalid for this dataset. Mask bands of this dataset have no precomputed overviews
```

adding bands eg `-b 1` or `-b 2` works off the individual bands, but I cannot choose the alpha band `-b 4`

## Operating system

Ubuntu 22.04

## GDAL version and provenance

tested with docker ubuntu-small-3.8.0 and off master (commit: 0fe09b61d751916623e53252e51047ec40853814)

**Comment by jratike80** [comment]
Works for me with GDAL 3.8.0, released 2023/11/06 (Windows, OSGeo4W). I am making a new test with 3.9dev.

I am not sure how much sense there is in using this command, the gdal_footprint utility seems to download very much data. If the image is also needed later it might be better to download the image and run gdal_footprint locally.

**Comment by jratike80** [comment]
Confirmed with GDAL 3.9dev on Windows.
Gdalinfo shows this info 

```
...
Band 3 Block=512x512 Type=Byte, ColorInterp=Blue
    Mask Flags: PER_DATASET ALPHA
  Overviews of mask band: 6000x9000, 3000x4500, 1500x2250, 750x1125, 375x562, 187x281
  
Band 4 Block=512x512 Type=Byte, ColorInterp=Alpha
    Overviews: 6000x9000, 3000x4500, 1500x2250, 750x1125, 375x562, 187x281
```
Maybe "Overviews of mask band" is also searched for band 4, that **is** the mask band?

**Comment by jratike80** [comment]
There is something odd in that image. I downloaded it and gdal_footprint failed. Then I made a copy
`gdal_translate -of cog test.tif test2.tif`
and now gdal_footprint works OK.

The mask band overview theory above is wrong, gdalinfo writes similar report also from the working COG.

**Comment by blacha** [comment]
Thanks @rouault! I can confirm this fixed my problem!
