### ISSUE TITLE
gdal_footprint: write the filename as an attribute

### ISSUE THREAD

**Issue by jratike80** [OSGeo/gdal#8795]
For making it easier to use the footprints afterwards it would be good to write the filename into the vector data as an attribute. Gdaltindex is using field "location" for that purpose by default so gdal_footprint could use the same. Gdaltindex has also an option "write_absolute_path" that is useful sometimes.

Saving the filename could be the default behavior. If there is some good reason for not saving the filename it could be skipped for example with some option like `-nopath`.

**Comment by rouault** [comment]
implemented in https://github.com/OSGeo/gdal/pull/8932
