### ISSUE TITLE
Add CI test we can use GDAL public/installed headers with C++11

### ISSUE THREAD

**Issue by rouault** [OSGeo/gdal#8796]
Discussed during developer meeting on 2023/11/23: C++17 is enabled for GDAL compilation for master/3.9.0dev, but for now, we want to ensure that public/installed only use C++11 features. A CI test would be useful to ensure that

**Comment by dbaston** [comment]
I just came across this when trying to use `std::string_view` (C++17) in `cpl_conv.h`. Some ideas for solutions:

- Put internal functions with C++17 types in a new header (`gdal_priv_for_real_this_time.h`)
- Conditionally exclude functions with C++17 types from headers if this standard is not available
- Avoid C++17 types altogether
- Abandon the requirement that headers be usable in C++11

Sorry, this would have been a good topic for the call 40 minutes ago, but I hadn't noticed it then.

**Comment by rouault** [comment]
> Abandon the requirement that headers be usable in C++11

I would probably lean towards that. Most current compilers must have C++17 as the default version nowadays (gcc 13 and clang 18 as shipped by ubutu 24.04 do. GCC 16 just switched to C++20), so that could probably a good baseline that wouldn't cause too much issues downstream.
