### ISSUE TITLE
Graphical distortion warping to GoogleMapsCompatible

### ISSUE THREAD

**Issue by Plantain** [OSGeo/gdal#8805]
Following on from #8684, warping in one step from space projection to GoogleMapsCompatible generates COG's with weird distortions, while warping to EPSG3857 and then translating works as expected.

Actual output, notice the square distortions:
![Screenshot 2023-11-24 at 9 11 02 am](https://github.com/OSGeo/gdal/assets/319895/768ea585-933a-4a8a-90d7-bef302a39b38)
![Screenshot 2023-11-24 at 9 16 56 am](https://github.com/OSGeo/gdal/assets/319895/37e1549b-d7fd-401c-9e68-eee7cce871a3)

Expected output (not exactly aligned, I can't figure out how to extract tiles from a geotiff):
![Screenshot 2023-11-24 at 9 18 07 am](https://github.com/OSGeo/gdal/assets/319895/495edcde-1bc9-4dfa-9580-26ccb6f64de5)

Sample command:
/usr/bin/gdalwarp -multi --config GDAL_CACHEMAX 4096 -wm 4096 -wo NUM_THREADS=64 -of COG -co TILING_SCHEME=GoogleMapsCompatible -r lanczos -co ALIGNED_LEVELS=5 -co ZOOM_LEVEL=7 -co RESAMPLING=lanczos -co OVERVIEW_RESAMPLING=lanczos -co WARP_RESAMPLING=lanczos -co NUM_THREADS=64 -co COMPRESS=JXL -co ADD_ALPHA=NO -co JXL_LOSSLESS=NO -co JXL_DISTANCE=1.2 -co JXL_EFFORT=8 -co BLOCKSIZE=512 --config GDAL_TIFF_OVR_BLOCKSIZE 512 -r lanczos raw.tiff img.tiff --config GDAL_NUM_THREADS 64 -t_srs EPSG:3857 -te_srs EPSG:4326 -te 90 -65 180 70

Sample data:
static2.skysight.io/raw.tiff

## Operating system
Ubuntu 22.04
## GDAL version and provenance
https://github.com/OSGeo/gdal/pkgs/container/gdal/144852017?tag=ubuntu-full-3.8.0

**Comment by rouault** [comment]
I would expect this to be the same as #11042 which will be fixed per #11046
