### ISSUE TITLE
gdal_translate: when specifying -srcwin,  the cropped blocks on the target srs of vrt file are aligned with the original file.

### ISSUE THREAD

**Issue by hzhshok** [OSGeo/gdal#8807]
## Expected behavior and actual behavior.
The cropped blocks should be generally consistent with the original file.

## Steps to reproduce the problem.
I sliceed one file to mulitiple pieces files with different epsg code, but i got the same visible area(except for the black area) with the original one, but it is obvious the new file are not aligned with the original file( the content have  obvious difference, maybe like the target are scaled, and then be sliced, that caused the target  file showed the same area with the original one, but only one part of the original file).

Note: the pieces(9 pieces) are continuous, if i warp the vrt to the other format(.tif not still target .vrt), the result is correct.

I used c/c++ gdalapi, at last i checked the results for every step on QGIS, guessed it should be have a problem on gdaltranslate step, so, please give a suggestion if it is a issue, or caused by my parameters.

a. I build vrt file using gdalbuildvrt without any parameter.
    gdalbuildvrt sourcefile.tif target.vrt
b. I warp target.vrt file to **target.warp.vrt** from 'EPSG:32650 - WGS 84 / UTM zone 50N - Projected' to epsg:3857 with target resolution 30/-30(original resolution is 10/-10), on the following parameters:
   -t_srs 'epsg:3857' -tr 30 30
    The generated file is showed on qgis it is generally consistent with the original file(source.tif).
    QGIS showed they are aligned except for only the border have a tiny deform.

    Note: if i warp the vrt file to the other format(.tif, not .vrt), it is normal.
c.  I gdaltranslate that target.warp.vrt with the parameter '-srcwin' to slice that file to multiple pieces with parameter.
     -srcwin offsetx, offsety, 2017, 2017
d. It showed the pieces and the original file are not generally aligned.
    The pieces showed:
    d.1. They have the same visible area(except for the black area).
    d.2. The last pieces only have one part of the original file.    

## Operating system
ubuntu20.04

## GDAL version and provenance
GDAL 3.0.4

Regards

**Comment by rouault** [comment]
- This report should include fully reproducible steps, reduced to the minimum amount, using GDAL command line utilities and how they are invoked, and with input files
- GDAL 3.0.4 is no longer supported. Update to latest version available. For example using https://gdal.org/download.html#conda
- Misalignment is expected if you use gdalwarp with default nearest resampling. You should try to add -r bilinear or -r cubic for example

**Comment by hzhshok** [comment]
Sorry for that i did not notice the mail message! 
Thanks for your feedback! and i will try new version or sample options.


Regards
