### ISSUE TITLE
Python utilities: provide launcher scripts

### ISSUE THREAD

**Issue by rouault** [OSGeo/gdal#8811]
This might mostly consist of reverting fe649a802f9f9f5d91f4eb3717b1fb3a83769770 (which was a revert...), but while making sure that __init__.py isn't considered as a script . Cf https://lists.osgeo.org/pipermail/gdal-dev/2023-November/057992.html thread

**Comment by rouault** [comment]
Related to https://github.com/conda-forge/gdal-feedstock/issues/834

**Comment by jratike80** [comment]
I wonder if this is ready or not. See https://gis.stackexchange.com/questions/482596/how-to-use-the-gdal-edit-tool-from-gdal-installed-within-anaconda/482604

I made the same test with Miniconda and I can see a bunch of .exe files in the directory C:\Program Files\Miniconda3\envs\gdaltest2\Scripts. All of them fail with `failed to create process`. Commands like `python gdal_merge.py" do work.
