### ISSUE TITLE
After using JPEG compression, black edges appear on the border

### ISSUE THREAD

**Issue by xiaoda0801** [OSGeo/gdal#8820]
Hi, when I used JPEG to compress images, I found that there were black edges on the boundaries of the output image, as shown below. Using gdal 3.7.3.

![c6eb79523a975848b6f621603db009e2](https://github.com/OSGeo/gdal/assets/48905511/e75e1e89-5f0e-4785-90e9-785a83d2a6eb)

![dd8f26db82755d45a23ca74f702d5a03](https://github.com/OSGeo/gdal/assets/48905511/8d789c91-e26f-4821-aea7-b34efcc23787)

**Comment by rouault** [comment]
Such artifacts are typical of JPEG compression. You may want to add a mask band. See https://gdal.org/programs/nearblack.html
