### ISSUE TITLE
Extra colon on datasource creation option examples

### ISSUE THREAD

**Issue by jidanni** [OSGeo/gdal#8851]
On https://gdal.org/drivers/vector/libkml.html#datasource-creation-options we see

> The following datasource creation options can be used to generate a <atom:Author> element at the top Document level.
> • AUTHOR_NAME=value:
> • AUTHOR_URI=value:
> • AUTHOR_EMAIL=value:

At the end of each line the colon should be removed.

I checked the source code, and there is some macro that is putting the colon there.

The colon is useful, but not on these three lines.

**Comment by rouault** [comment]
options documented in 62580edee6
