### ISSUE TITLE
vsis3: incomplete support for container credentials

### ISSUE THREAD

**Issue by moradology** [OSGeo/gdal#8858]
## Expected behavior and actual behavior.

I expected `vsis3` to transparently acquire credentials from the environment as it does on EC2 and as generally works on container services provided by AWS (e.g. ECS). On EMR-Serverless, however, this fails to happen.

Enabling logging and CURL logging, it becomes obvious that GDAL is failing to connect to the expected metadata/credentials endpoint:

```
[30;1m [45;1m[1 of 1000] [0m [36;1mDEBUG(1) CPLE_None(0) "No error." AWS: AWS_ROLE_ARN configuration option not defined [0m
HTTP: Fetch(http://169.254.169.254/latest/api/token)
HTTP: libcurl/8.4.0 OpenSSL/3.1.4 zlib/1.2.13 zstd/1.5.5 libssh2/1.11.0 nghttp2/1.57.0
CURL_INFO_TEXT: Couldn't find host 169.254.169.254 in the .netrc file; using defaults
CURL_INFO_TEXT:   Trying 169.254.169.254:80...
CURL_INFO_TEXT: Immediate connect fail for [169.254.169.254](http://169.254.169.254/): Invalid argument
CURL_INFO_TEXT: Failed to connect to 169.254.169.254 port 80 after 0 ms: Couldn't connect to server
CURL_INFO_TEXT: Closing connection
HTTP: Fetch(http://169.254.169.254/latest/meta-data/iam/security-credentials/)
CURL_INFO_TEXT: Couldn't find host 169.254.169.254 in the .netrc file; using defaults
CURL_INFO_TEXT:   Trying 169.254.169.254:80...
CURL_INFO_TEXT: Immediate connect fail for [169.254.169.254](http://169.254.169.254/): Invalid argument
CURL_INFO_TEXT: Failed to connect to 169.254.169.254 port 80 after 0 ms: Couldn't connect to server
CURL_INFO_TEXT: Closing connection
```

Digging in further, it appears to be the case that this section of code is incomplete as [AWS_CONTAINER_CREDENTIALS_FULL_URI](https://docs.aws.amazon.com/sdkref/latest/guide/feature-container-credentials.html) is not referenced:
https://github.com/OSGeo/gdal/blob/master/port/cpl_aws.cpp#L835C8-L849

Unfortunately, the documentation doesn't really describe when/where FULL vs RELATIVE environment variables are to be expected. Unhelpfully, the upshot of this documentation is "FULL might be used if RELATIVE isn't".
<img width="924" alt="image" src="https://github.com/OSGeo/gdal/assets/1977405/d2609e0d-a439-44d1-9800-4d245340c850">

Reviewing the environment in the cluster I deployed, it becomes clear that this is exactly the issue: 
<img width="826" alt="image" src="https://github.com/OSGeo/gdal/assets/1977405/adcc363f-f4d9-402e-8d8b-cc112f563f5b">

## Steps to reproduce the problem.

Try to use GDAL's `vsis3` support on EMR-Serverless. It will 403.

## Operating system

All operating systems.

## GDAL version and provenance

Every single version of GDAL up to and including `master`.

## How to resolve

The resolution here is relatively simple, I think. [cpl_aws.cpp](https://github.com/OSGeo/gdal/blob/master/port/cpl_aws.cpp) simply needs to have a bit more logic that enables it to use `AWS_CONTAINER_CREDENTIALS_FULL_URI` should that be provided in the container environment.

**Comment by rouault** [comment]
@moradology Thanks for the detailed analysis. Could you try the patch in https://github.com/OSGeo/gdal/pull/8859 ? I've only unit tested it as I don't have easy access to a EMR-Serverless environment

**Comment by moradology** [comment]
Shucks. And here i was getting excited about lodging my first gdal PR 🤣 

Yeah, I'll test this out!

**Comment by moradology** [comment]
OK, so the good news in terms of me not writing it is that I apparently have no taste at all when it comes to C++

**Comment by rouault** [comment]
> And here I was getting excited about lodging my first gdal PR 🤣

oops, I thought that you file an issue because you didn't feel like doing a PR... I should have asked.

> OK, so the good news in terms of me not writing it is that I apparently have no taste at all when it comes to C++

well, your proposal looks equally good. The only difference in mine is that I don't fetch AWS_CONTAINER_CREDENTIALS_RELATIVE_URI if we already get a non empty AWS_CONTAINER_CREDENTIALS_FULL_URI, but that's a micro optimization.

**Comment by moradology** [comment]
You're too kind. Sorry this is taking a bit - gotta build your branch on a specific base image, put it on ecr, write a little program for the jvm, etc

**Comment by moradology** [comment]
We're in business:
<img width="380" alt="image" src="https://github.com/OSGeo/gdal/assets/1977405/6da693e2-c10f-491e-97ad-68bae5045b92">

<img width="1012" alt="image" src="https://github.com/OSGeo/gdal/assets/1977405/113bafb9-3e6f-4796-9c32-74c910b190f7">
