### ISSUE TITLE
gdalwarp -cutline duplicates a line of the image cropped.

### ISSUE THREAD

**Issue by floriandb** [OSGeo/gdal#886]
I expected to crop an image to the extent of a shapefile with the command: 
gdalwarp -cutline inSHP.shp -crop_to_cutline inputIMG.tif outIMG_crop.tif

For one specific image, this operation produced a cropped image with a line of pixel abnormally duplicated. 
This error (the same line was duplicated) was reproduced with GDAL 2.0.1, released 2015/09/15 under Linux SMP (on a server) 64 bit and GDAL 1.11.3, released 2015/09/16 under 16.04.1-Ubuntu 64 bit.

The same operation worked nicely with the same shapefile but two other input images.

**Comment by floriandb** [comment]
The original image is too big so I cropped it once already.

gdalwarp -cutline ROI6_UTM11.shp -crop_to_cutline test_im.tif test_im_crop.tif

This produces a similar error : the column at x=270557 is duplicated in the output cropped image.



[gdalwarp_bugreport_FDB_180827.zip](https://github.com/OSGeo/gdal/files/2323915/gdalwarp_bugreport_FDB_180827.zip)

**Comment by rouault** [comment]
ok, I can reproduce that with 2.3 or older. This was due to using the exact cutline extent, which could cause some tiny differences in resolution, and thus artifacts due to nearest resampling.
The change done in master with 6b0821633c3aba0142a697e2ecdb1058d5b99666 fixes that issue

**Comment by floriandb** [comment]
thanks for the explanations.
