### ISSUE TITLE
Using directly a enhanced tile index as a raster VRT ?

### ISSUE THREAD

**Issue by rouault** [OSGeo/gdal#8861]
VRT XML is great for a number of use cases, but that doesn't scale well with > 100,000's source tiles, which is a use case that definitely exists. I've seen people using strategies like building a VRT of VRTs to circumvent those limitations. There could be a potential for using a tile index, similar to the one generated by gdaltindex, stored in formats like GeoPackage, FlatGeoBuf or potentially a PostGIS layer.

For file based indexes, detection of it as a VRT could be based on the file extension, e.g.  .vrt.fgb , .vrt.gpkg , assuming the file has a single layer. Each record in the layer would obviously need to have as the geometry a polygon with the extent of the tile, and an attribute field with the tile location.

Such file should also contain a few minimum metadata items to build the VRT:
* RESX: resolution along X axis in pixel/crs_unit
* RESY: resolution along Y axis in pixel/crs_unit

or
* XSIZE: in pixel
* YSIZE: in pixel
* GEOTRANSFORM

Former formulation has the advantage of not requiring an update when updating the content of tile index. Second formulation has the advantage of having a stable VRT extent.

Plus, for any of the above 2 variants:
* LOCATION_FIELD: name of the field that contain the tile location (optional, if not set "location")
* BAND_COUNT
* SRS: (optional, if present, should be the same as the index layer if it is set)
* RESAMPLING: (optional)
* COLOR_INTERPRETATION: list, as many values as BAND_COUNT (optional)
* NODATA: list, as many values as BAND_COUNT (optional)
( extent would be derived from GetExtent() on the layer, and width, height derived from the extent + RESX + RESY)
* OVERVIEW_x_DATASET: name of the dataset to use for overview level X (optional)
* OVERVIEW_x_LAYER: name of the layer to use for overview level X (optional)

For more complex use cases (multilayer dataset, non file-based or format without metadata ), we could also use a simple VRT descriptor, like:
```xml
<VRTDatasetFromIndex>
     <IndexDataset>PG:dbname=my_db</IndexDataset>
     <IndexLayer>my_index</IndexLayer>
     <SRS>...<SRS>  <!-- optional -->
     <ResX>...</ResX>
     <ResY>...</ResY>
     <BandCount>...</BandCount>
     <XSize>...<XSize>   <!-- optional if ResX + ResY is present -->
     <YSize>...<YSize>   <!-- optional if ResX + ResY is present -->
     <GeoTransform>...</GeoTransform>    <!-- optional if ResX + ResY is present . But might be wishable to set on PostGIS where getting extent can be slow on huge layers -->
     <ColorInterp>...<ColorInterp> <!-- optional -->
     <NoDataValue>...<NoDataValue> <!-- optional -->
     <Resampling>...<Resampling> <!-- optional -->
     <Overviews> ... </Overviews> <!-- optional -->
</VRTDatasetFromIndex>
```

I'm wondering if we should still have the limitation that all tiles should be in the same CRS, which would be the one reported by the layer. If not, the geometry field of the index should still be expressed in a single CRS (the one of the VRT), and we'd have to use warp VRT to reproject on the fly from the tile SRS to the VRT SRS.

Not totally clear if the generating tool should be gdaltindex or gdalbuildvrt.

**Comment by jratike80** [comment]
Support for different CRSs in gdaltindex has been a very valuable feature for me with MapServer. It would be absolutely nice feature in VRT as well and would make it easier for example to mosaic rasters from adjacent projection zones.

**Comment by tbonfort** [comment]
This is a very welcomed addition! 
I have 2 overview related questions:
1. Could/should the overview levels be expressed per tile instead of globally for the whole dataset?
2. For the OVERVIEW_X_DATASET_NAME member, I would imagine that each of these overview datasets contains multiple overview levels. Should this tag be repeated (with x=16, x=32, etc) in this case?

**Comment by rouault** [comment]
> * Could/should the overview levels be expressed per tile instead of globally for the whole dataset?

That would generally not be efficient, especially at the smallest overview size, as you would have to open plenty of files to acquire a tiny amount of pixels. That said if you wanted to do it you could create another tile index, that would be pointed from the main tile index with OVERVIEW_X_DATASET_NAME. That overview tile index would have an open option OVERVIEW_LEVEL=x pointing to the overview level you wish. Which means we probably need a OPEN_OPTIONS metadata item for open options that must be used when opening any tile (or should that be a field of the index where you could define open options specific of each tile... hum...)

> 2\. For the OVERVIEW_X_DATASET_NAME member, I would imagine that each of these overview datasets contains multiple overview levels. Should this tag be repeated (with x=16, x=32, etc) in this case?

I was just imagining to replicate the existing funtionnality of
```
<Overview>
  <SourceFilename relativeToVRT="1">overview_idx_0.tif</SourceFilename>
  <SourceBand>1</SourceBand>
</Overview>
<Overview>
  <SourceFilename relativeToVRT="1">overview_idx_1.tif</SourceFilename>
  <SourceBand>1</SourceBand>
</Overview>
```
What you suggest could be done by adding also a OVERVIEW_X_OPEN_OPTIONS item where you could specify the OVERVIEW_LEVEL open option.
So
```
OVERVIEW_0_DATASET_NAME=levels_0_1_2.tif
OVERVIEW_0_OPEN_OPTIONS=OVERVIEW_LEVEL=none   # we want to use the full resolution of the file as 0th overview of the VRT
OVERVIEW_1_DATASET_NAME=levels_0_1_2.tif
OVERVIEW_1_OPEN_OPTIONS=OVERVIEW_LEVEL=0   # we want to use the 0th overview of the file as 1th overview of the VRT
OVERVIEW_2_DATASET_NAME=levels_0_1_2.tif
OVERVIEW_2_OPEN_OPTIONS=OVERVIEW_LEVEL=1
```

**Comment by tbonfort** [comment]
> That would generally not be efficient, especially at the smallest overview size, as you would have to open plenty of files to acquire a tiny amount of pixels.

That's not what I meant. I was wondering if it might be useful to store the number of overviews actually stored in any given tile as an additional attribute for each entry of the tileindex. In which case gdal would not need to emit a call to gdalopen on the actual tile in order to know how many overviews are available. But thinking over it a bit more, I suspect that there is nothing much to gain here, as the list of tiles needed for a given user extent depends only on that extent and not on the requested resolution, which means that a gdalopen on the tile is inevitable anyways.

> I was just imagining to replicate the existing funtionnality of `<Overview> [snip]`

OK, I misunderstood the usage of `OVERVIEW_x_DATASET_NAME` you were explaining.

Let's take a real world example, with 
```
<VRTDatasetFromIndex>
     <IndexDataset>PG:dbname=my_db</IndexDataset>
     <IndexLayer>my_index</IndexLayer>
     [snip]
     <Overviews>
       <Overview>
         <SourceFilename relativeToVRT="1">overview_idx_16.tif</SourceFilename>
      </Overview>
      <Overview>
         <SourceFilename relativeToVRT="1">overview_idx_64.tif</SourceFilename>
      </Overview>
     </Overviews>
</VRTDatasetFromIndex>
```

How am I supposed to tell the vrt driver that
- the tiles pointed by the index contain overview levels 2,4,8 and should also be used for overview levels 2,4,8 of the vrtdataset
- overview_idx_16.tif contains a single overview level (=2), and should be used for overview levels 16 and 32 of the vrt dataset
- overview_idx_64.tif should be used for overview levels >=64 of the vrt dataset

**Comment by rouault** [comment]
> How am I supposed to tell the vrt driver that

I don't believe we actually need to be more explicit than what you put in your VRT. With the VRT you suggest, GDAL will expose 2 explicit overview levels for downsampling factor 16 and 64. But given how the logic of selection of overviews work, for requests of downsampling factor up to 16 / 1.2 (the 1.2 comes from https://gdal.org/api/gdalrasterband_cpp.html#_CPPv4N14GDALRasterBand8RasterIOE10GDALRWFlagiiiiPvii12GDALDataType8GSpacing8GSpacingP20GDALRasterIOExtraArg), it will use the sources of the IndexLayer and if they have overviews it will use the approrpiate levels.
For downsampling factors between 16 / 1.2 and 64 / 1.2, it will use overview_idx_16.tif and its potential overviews. etc.

**Comment by tbonfort** [comment]
> With the VRT you suggest, GDAL will expose 2 explicit overview levels for downsampling factor 16 and 64

Which implies that a gdalopen on the vrt dataset will result in a gdalopen on each overview_idx_xxx.tif in order to determine each file's size? Shouldn't the `<overview>` tag be extended to support rasterXSize/rasterYSize as well in order to avoid this ?

**Comment by rouault** [comment]
> Which implies that a gdalopen on the vrt dataset will result in a gdalopen on each overview_idx_xxx.tif in order to determine each file's size? Shouldn't the `<overview>` tag be extended to support rasterXSize/rasterYSize as well in order to avoid this ?

Possibly... Sounds a bit like premature optimization to me, and would require extra checks to be sure that what people declare is actually what the overview file contains. GDALOpen'ing() a couple TIFF files to get their overview level shouldn't be that costly.

**Comment by rouault** [comment]
> Isn't this already the case for the existing rasterXSize of today's vrts?

If you are refering to the one of the SourceProperties element, no it is no longer. SourceProperties isn't read anymore by GDAL since a few versions. It is still there for compat with older versions. And the rasterXSize at the top level of the VRT is a "truth" given by the user. The user might define it larger or smaller than the union of the extent of all sources (larger for sure, smaller: there might be runtime issues when trying to read sources that would go beyond it)

> Except when said tiffs are on s3/etc, which is a likely possibility for the use-case addressed by this enhancement (i.e. a very high number of tiles too large to fit inside a plain xml vrt). This should only be an issue on the first gdalopen when using COGs though, thanks to the vsi caching (without which my point isn't about premature optimization anymore)

yes, there would be an initial cost at VRT opening, but if you keep the VRT handle open for many requests, this cost will be amortized, even without any vsi caching, as once a dataset has been asked for its overviews, it stores that information in its C++ object representation and doesn't need to re-read the file over and over to know which overviews exist. This is no different than current VRTs using external overviews.

**Comment by jratike80** [comment]
On-the-fly filtering of the VRT is probably not reasonable because of the aggregated layer level metadata about extent etc. but it would be nice to have a tool that could create a new VRT from a subset of tiles without a need to access the raster files again. Usage example:
`gdalbuildvrt -sql "select * from tiles where year=2023" huge_archive.gpkg index_2023.gpkg`

**Comment by vincentschut** [comment]
This is an interesting feature. We use VRT's containing many (thousands to even 100.000's) tifs all the time. Both the VRT and the tifs are stored in the cloud (gcs). However, we often face a different problem with these huge vrt's, which is that gdal uses a lot (gigabytes) of memory when opening the vrt, even with all caching turned low or off. This especially limits us in doing multithreaded reads from these remote vrt's, as we need to open the vrt separately in each thread, resulting in a memory usage that is nthreads times the memory use to open the vrt singlethreaded.
This was a long introduction for my question: would this new feature also lower the memory used by gdal to open these huge vrt's?

**Comment by rouault** [comment]
> This was a long introduction for my question: would this new feature also lower the memory used by gdal to open these huge vrt's?

yes, that would definitely be a goal / reason for that enhancement. RAM consumption should be neglectable whatever the size of the tile index. VRTSource object would be instantiated on the fly at RasterIO() time.

**Comment by rouault** [comment]
Implementation available in https://github.com/OSGeo/gdal/pull/8983

**Comment by tobwen** [comment]
Is it limited to raster only? I often use VRT with maaaaany vector files.

**Comment by rouault** [comment]
> Is it limited to raster only?

yes
