### ISSUE TITLE
Support bigint types in file geodatabases

### ISSUE THREAD

**Issue by nyalldawson** [OSGeo/gdal#8862]
As described in:

https://www.esri.com/arcgis-blog/products/arcgis-pro/data-management/whats-new-from-the-geodatabase-team-in-arcgis-pro-3-2/#64-bit-OIDs-and-the-BigInteger-Field-Data-Type

A new field type for "big integer" was introduced in the file geodatabase specification in ArcGIS Pro 3.2.

I've made a sample gdb using this field type here:
[big_int.gdb.zip](https://github.com/OSGeo/gdal/files/13494330/big_int.gdb.zip)

Currently this field type isn't handled in GDAL, and prevents opening the table.

**Comment by rouault** [comment]
@nyalldawson Wanna tackle that yourself ? (just asking to avoid doing a PR if you're doing one right now ;-))

**Comment by nyalldawson** [comment]
If you've already started, go ahead... but otherwise I'll give it a shot sometime over the next couple of days

**Comment by nyalldawson** [comment]
https://github.com/rouault/dump_gdbtable/pull/10 relates

**Comment by rouault** [comment]
ok, having a look at implementing that in the driver
