### ISSUE TITLE
NETCDF: space/underscore in subdataset component name

### ISSUE THREAD

**Issue by mdsumner** [OSGeo/gdal#8863]
File from https://asdc.larc.nasa.gov/data/MOPITT/MOP03JM.009/2022.09.01/MOP03JM-202209-L3V95.9.3.he5 (requires earthdata login, was listed in #8731)

In this HDF5 file I see subdataset names with a space in them if I use the NETCDF driver prefix: 

```
gdalinfo "NETCDF:MOP03JM-202209-L3V95.9.3.h5" | grep "Data Fields" | tail -n 2

  SUBDATASET_76_NAME=NETCDF:"MOP03JM-202209-L3V95.9.3.h5":"/HDFEOS/GRIDS/MOP03/Data Fields/WaterVaporColumnNight"
  SUBDATASET_76_DESC=[360x180] /HDFEOS/GRIDS/MOP03/Data Fields/WaterVaporColumnNight (32-bit floating-point)

```

Without that prefix there's an underscore

```
gdalinfo "MOP03JM-202209-L3V95.9.3.h5" | grep "Data_Fields" | tail -n 2

  SUBDATASET_68_NAME=HDF5:"MOP03JM-202209-L3V95.9.3.h5"://HDFEOS/GRIDS/MOP03/Data_Fields/WaterVaporColumnNight
  SUBDATASET_68_DESC=[360x180] //HDFEOS/GRIDS/MOP03/Data_Fields/WaterVaporColumnNight (32-bit floating-point)

```

I can see the value in being agnostic about spaces vs underscores, but it was ruining my string comparison logic until I realized what was going on. 

In ncdump  the space is part of the group name and afaict it's native to the HDF5 itself. 

```
     group: Data\ Fields {
```

Should the HDF5 driver not add underscores, or should comparisons insert them to be agnostic?

**Comment by rouault** [comment]
The replacement of space by underscore in the HDF5 driver is mostly historical. I remember having posted something about that in a ticket or email some time ago. That could be changed, but it would have backward compatibility implication

**Comment by mdsumner** [comment]
ah ok, I'm just glad I know about it - a pretty arcane problem and discoverable from the gdalinfo output no burning need to change things from me
