### ISSUE TITLE
SubdatasetInfo components from composite DSN (with multiple ":")

### ISSUE THREAD

**Issue by mdsumner** [OSGeo/gdal#8869]
I'm seeing the wrong components from subdataset info on complex DSN: 

```python
from osgeo import gdal
gdal.UseExceptions()
info = gdal.GetSubdatasetInfo("NETCDF:\"/vsicurl/https://www.ncei.noaa.gov/data/sea-surface-temperature-optimum-interpolation/v2.1/access/avhrr/202202/oisst-avhrr-v02r01.20220218.nc\":sst")


info.GetSubdatasetComponent()
#'//www.ncei.noaa.gov/data/sea-surface-temperature-optimum-interpolation/v2.1/access/avhrr/202202/oisst-avhrr-v02r01.20220218.nc":sst'
info.GetPathComponent()
#'"/vsicurl/https'
```

works fine on local ( I assume it's the relative position of the ":"  ~and should be seeking from the end~ well actually I don't know how it works with multiple colons possible at either end ...)

```python3
info2 = gdal.GetSubdatasetInfo("NETCDF:\"oisst-avhrr-v02r01.20220218.nc\":sst")                                                                                                            info2.GetPathComponent()
#'oisst-avhrr-v02r01.20220218.nc'
info2.GetSubdatasetComponent()
#'sst'
```

GDAL 3.9.0dev-ab1ec43075-dirty, released 2023/11/29 (debug build)

**Comment by mdsumner** [comment]
I get a segfault from bogus DSN: 

```python
gdal.GetSubdatasetInfo("NetCDF:a:c")
```

**Comment by rouault** [comment]
@elpaso Can you look at that?

**Comment by mdsumner** [comment]
very good thank you, a query though - it seems we are limited to paths of strlen() 3 or more

```
gdal.GetSubdatasetInfo("NetCDF:a:c")    ## None
gdal.GetSubdatasetInfo("NetCDF:ab:c")  ## None
gdal.GetSubdatasetInfo("NetCDF:abc:c")## valid
```

very short file names without extensions are *a bit antisocial* it has to be said, but are completely valid in other contexts: 

```
curl -o f https://www.ncei.noaa.gov/data/sea-surface-temperature-optimum-interpolation/v2.1/access/avhrr/202202/oisst-avhrr-v02r01.20220218.nc

gdalinfo NETCDF:f:sst  ## valid
```

**Comment by elpaso** [comment]
> very good thank you, a query though - it seems we are limited to paths of strlen() 3 or more
> 
> ```
> gdal.GetSubdatasetInfo("NetCDF:a:c")    ## None
> gdal.GetSubdatasetInfo("NetCDF:ab:c")  ## None
> gdal.GetSubdatasetInfo("NetCDF:abc:c")## valid
> ```
> 
> very short file names without extensions are _a bit antisocial_ it has to be said, but are completely valid in other contexts:
> 
> ```
> curl -o f https://www.ncei.noaa.gov/data/sea-surface-temperature-optimum-interpolation/v2.1/access/avhrr/202202/oisst-avhrr-v02r01.20220218.nc
> 
> gdalinfo NETCDF:f:sst  ## valid
> ```

Yeah, aren't we all a bit antisocial ? :smile_cat: 
 Fixed with https://github.com/OSGeo/gdal/pull/8891

**Comment by elpaso** [comment]
> great thank you, I'm following along and trying to participate in the code at this level ... slowly :)

This won't work though:

```bash
$ touch 'C:\my_path'
-rw-rw-r-- 1 xxx xxx      0 dic  1 11:39 'C:\my_path'
```

but  it's maybe more criminal than antisocial.

**Comment by mdsumner** [comment]
oh lol indeed, there's got to be a limit, I'm ok with this
