### ISSUE TITLE
gdaladdo create rrd overview failed for PCIDSK format

### ISSUE THREAD

**Issue by liminlu0314** [OSGeo/gdal#887]
## Expected behavior and actual behavior.

The old version of gdaladdo(1.6.0) works well when creating pyramid, but the new version(2.2.4) cannot generate results. 

###  GDAL 1.6.0 work well
gdaladdo.exe --version
GDAL 1.6.0, released 2008/12/04

gdaladdo.exe -ro E:\xxx.pix 3 9 27 --config HFA_USE_RRD YES --config USE_RRD YES --config GDAL_DATA E:\gdal\data

###  GDAL 2.2.4 does not work.
gdaladdo.exe --version
GDAL 2.2.4, released 2018/03/19

## Operating system

Windows 10 64bit

**Comment by liminlu0314** [comment]
Test file
[xxx.zip](https://github.com/OSGeo/gdal/files/2326271/xxx.zip)

**Comment by jratike80** [comment]
The problem does not seem to be in RRD overview but in external overviews generally. This fails as well with GDAL 2.4.0dev

gdaladdo.exe  -ro xxx.pix 3 9 27 --debug on

> Exception in ~CTiledChannel(): File not open for update in WriteToFile()Exception in ~CTiledChannel(
> ): File not open for update in WriteToFile()Exception in ~CTiledChannel(): File not open for update
> in WriteToFile()Exception in ~CTiledChannel(): File not open for update in WriteToFile()Exception in
>  ~CTiledChannel(): File not open for update in WriteToFile()Exception in ~CTiledChannel(): File not
> open for update in WriteToFile()Exception in ~CTiledChannel(): File not open for update in WriteToFi
> le()Exception in ~CTiledChannel(): File not open for update in WriteToFile()Exception in ~CTiledChan
> nel(): File not open for update in WriteToFile()Exception in MetadataSegment destructor: File not op
> en for update in WriteToFile()
