### ISSUE TITLE
Steep slopes in raster data produces discontinuous contour lines 

### ISSUE THREAD

**Issue by kubrickfr** [OSGeo/gdal#889]
## Expected behavior and actual behavior.

With version 2.2.4 (if I remember correctly, I can't seem to compile it again), the result was correct:
![image](https://user-images.githubusercontent.com/2634188/44803085-4f242800-abb5-11e8-9e99-00e4fa1de8af.png)

With 2.3.1, I get
![image](https://user-images.githubusercontent.com/2634188/44803323-0751d080-abb6-11e8-9d95-db3531b2800a.png)

## Steps to reproduce the problem.

With SRTM data from NASA, in QGIS, the command line is
`gdal_contour -b 1 -a ELEV -i 10.0 -f "ESRI Shapefile" /home/xxx/Downloads/xx.tif /tmp/processing_0d243642f09e40fbb5579272a3e257fb/d1cb3f40c0b2429ab277d13dd25d48d9/OUTPUT.shp`

## Operating system

For example: arch Linux, up to date.

## GDAL version and provenance

Up to date arch package

> community/gdal 2.3.1-4 [installed]
>     A translator library for raster geospatial data formats

**Comment by rouault** [comment]
Looking at the recent history of gdal_contour, I can't really see an obvious changeset that would explain that. Could you point to / attach the exact file you tried ?

**Comment by kubrickfr** [comment]
You can try one of these:
https://e4ftl01.cr.usgs.gov/provisional/MEaSUREs/NASADEM/Islands/hgt_merge/s49e068.hgt.zip

with a s49e068.hdr like
```
BYTEORDER      M
LAYOUT         BIL
NROWS          3601
NCOLS          3601
NBANDS         1
NBITS          32
PIXELTYPE      FLOAT
BANDROWBYTES   14404
TOTALROWBYTES  14404
BANDGAPBYTES   0
NODATA         -32768
ULXMAP         68
ULYMAP         -48
XDIM           0.00027777777777778
YDIM           0.00027777777777778
```

**Comment by kubrickfr** [comment]
I confirm this fixes the issue. Thanks.
