### ISSUE TITLE
Error reading ENVI file

### ISSUE THREAD

**Issue by wzxkk** [OSGeo/gdal#8890]
[dataInfo.zip](https://github.com/OSGeo/gdal/files/13520370/dataInfo.zip)
Dear esteemed experts,
I used various programming languages (java/python/C) to read this file has a read error, including gdalinfo(3.7.2 version) is also the same error, identified as Driver: NGSGEOID/NOAA NGS Geoid Height Grids format, all the information I have stored in data.zip file. I asked you last time, but the issues were closed before they were solved. Please allow me to ask you again, because the problem is really not solved

**Comment by wzxkk** [comment]
It turns out that this is the reason. I always thought that GDAL would automatically prepare the judgment file driver, so the program has not specified the driver all the time. I learned it today, thank you very much!

**Comment by jratike80** [comment]
The automatic recognition may fail if several formats have same kind of fingerprints. There are also some formats like JPEG2000 which can be read with several drivers.
