### ISSUE TITLE
port/cpl_safemaths.hpp fails to check BUILTIN_OVERFLOW_CHECK_AVAILABLE causing build error with clang

### ISSUE THREAD

**Issue by gitartpiano** [OSGeo/gdal#8898]
**build error with clang**

port/cpl_safemaths.hpp fails to check BUILTIN_OVERFLOW_CHECK_AVAILABLE.

Here is a possible fix (it worked for me):

```diff
diff --git a/port/cpl_safemaths.hpp b/port/cpl_safemaths.hpp
index d37b757..76cd4c3 100644
--- a/port/cpl_safemaths.hpp
+++ b/port/cpl_safemaths.hpp
@@ -126,6 +126,7 @@ inline CPLSafeInt<GUInt64> CPLSM(GUInt64 x)
 inline CPLSafeInt<unsigned> CPLSM_TO_UNSIGNED(GUInt64 x);
 #endif
 
+#ifndef BUILTIN_OVERFLOW_CHECK_AVAILABLE
 #if defined(_MSC_VER)
 class CPLMSVCSafeIntException : public msl::utilities::SafeIntException
 {
@@ -140,6 +141,7 @@ class CPLMSVCSafeIntException : public msl::utilities::SafeIntException
     }
 };
 #endif
+#endif
 
 template <class T>
 inline CPLSafeInt<T> SafeAddSigned(const CPLSafeInt<T> &A,
```

Please advise if there is a better fix.

**Comment by gitartpiano** [comment]
FYI: this was the only issue needed fixing, with this in place I can successfully build with clang (17).

**Comment by gitartpiano** [comment]
@rouault I see you checked this code in 6 years ago, are you still around?

**Comment by rouault** [comment]
@gitartpiano Yeah, I'm still around ;-)  Are you building on clang on Windows ?

**Comment by gitartpiano** [comment]
I know it is not the answer what people like o hear, but I am building a Windows binary on a Linux host (unfortunately on my development environment only Linux CI runners are available).

So my compiler goes to https://github.com/OSGeo/gdal/blob/master/port/cpl_safemaths.hpp#L42 , so it never includes the safeint.h, which makes the `class CPLMSVCSafeIntException : public msl::utilities::SafeIntException` line fail, because msl::utilities are defined in safeint.h .

**Comment by rouault** [comment]
> I know it is not the answer what people like o hear, but I am building a Windows binary on a Linux host (unfortunately on my development environment only Linux CI runners are available).

no problem. I just wanted to understand the context. Fix queued in https://github.com/OSGeo/gdal/pull/8901

**Comment by gitartpiano** [comment]
Thanks for 8901 !
