### ISSUE TITLE
Gdal Java Binding not finding gdalalljni.dll: Can't find dependent libraries in version 204

### ISSUE THREAD

**Issue by njpsanghani** [OSGeo/gdal#890]
## Expected behavior and actual behavior.
For Java binding, have added the gdal *** dll folder to the path, and  trying to initialize gdal using  gdalJNI.isAvailable(). but it gives error
 java.lang.UnsatisfiedLinkError: D:\GdalRegister\gdal\gdalalljni.dll: Can't find dependent libraries

## Steps to reproduce the problem.
gdalalljni.dll is unable to find dependent libs.

## Operating system
Window 10

## GDAL version and provenance
Gdal version 204

## Code

```
public class Register {

	protected static final String GDAL_DATA_PATH = "GDAL_DATA";
	protected static final String JAVA_LIBRARY_PATH = "java.library.path";
	protected static final String SEPERATOR = System.getProperty("path.separator");
	protected static final String GDAL_FOLDER = "gdal";
	protected static final String USER_FOLDER = System.getProperty("user.dir");
	protected static final String GDAL_USER_FOLDER = USER_FOLDER + "\\" + GDAL_FOLDER;

	static {
		String newEnv ="";
		String javaEnv = System.getProperty(JAVA_LIBRARY_PATH);
		if (javaEnv.toLowerCase().contains(GDAL_USER_FOLDER)) {
			System.out.println(true);
		} else {
			newEnv =USER_FOLDER + SEPERATOR +  GDAL_USER_FOLDER + SEPERATOR +javaEnv;
			System.out.println(newEnv);
		}
		try {
			setLibraryPath(newEnv);
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
	
	public static void setLibraryPath(String path) throws Exception {
	    System.setProperty("java.library.path", path);
	    //set sys_paths to null so that java.library.path will be reevalueted next time it is needed
	    final Field sysPathsField = ClassLoader.class.getDeclaredField("sys_paths");
	    sysPathsField.setAccessible(true);
	    sysPathsField.set(null, null);
	}

	public static void main(String[] args) {	
		System.out.println(gdalJNI.isAvailable());
       }
}
```

## Output

Native library load failed.
java.lang.UnsatisfiedLinkError: D:\GdalRegister\gdal\gdalalljni.dll: Can't find dependent libraries

**Comment by rouault** [comment]
You also need to have the directory of the native gdalXX.dll in your PATH. gdalalljni.dll just contains some glue between the Java part and the native part.

**Comment by njpsanghani** [comment]
I under stand that, can i make it do that from code some how???, because i already have it added all in same folder and added it to java.library.path .   but still does not work

**Comment by rouault** [comment]
I'm not a Windows expert, but you probably need to define that in the PATH environment variable. java.library.path is not enough for cascaded dll dependencies.

**Comment by njpsanghani** [comment]
Its already working that way, I am trying to create something similar to that of what Nasa worldwind did.  Is there any way i can do same. i.e have ability load gdal and its dependencies for whatever os arch

**Comment by ianaz** [comment]
Same problem. Where can i find the `gdalalljni.dll`?

**Comment by ianaz** [comment]
Hope can be helpful for someone: 
Had to download a zip from here: https://www.gisinternals.com/release.php

Then the .dll was under
found it in `release-1900-gdal-3-0-0-mapserver-7-4-0/bin/gdal/java/gdalalljni.dll`

**Comment by notcaremath** [comment]
这是问题怎么解决呢，我同样遇到了这个问题，配置环境变量和引入dll文件都没有解决

**Comment by notcaremath** [comment]
这是问题怎么解决呢，我同样遇到了这个问题，配置环境变量和依赖引入dll文件都没有解决

**Comment by zyh326162646** [comment]
Here is the right way to solve this problem:

1. Download and install gdal core and filedb msi for Windows
https://download.gisinternals.com/sdk/downloads/release-1930-x64-gdal-3-5-3-mapserver-8-0-0/gdal-305-1930-x64-core.msi
https://download.gisinternals.com/sdk/downloads/release-1930-x64-gdal-3-5-3-mapserver-8-0-0/gdal-305-1930-x64-filegdb.msi
2. Install these two msi using default settings.
3. Setup System variables and Path for Gdal.
3.1
GDAL_DATA
C:\Program Files\GDAL\gdal-data

GDAL_DRIVER_PATH
C:\Program Files\GDAL\gdalplugins

PROJ_LIB
C:\Program Files\GDAL\projlib

3.2 Add Path
C:\Program Files\GDAL
C:\Program Files\gdal\bin\gdal\java    (this is why you can't find gdalalljni.dll)

**Comment by RunBoo** [comment]
@zyh326162646 I don't have this path: C:\Program Files\gdal\bin\gdal\java (this is why you can't find gdalalljni.dll)  So how can i solve this problem
