### ISSUE TITLE
gdal_rasterize not producing repeatible results

### ISSUE THREAD

**Issue by likafzj** [OSGeo/gdal#891]
## Expected behavior and actual behavior.

For example: I want to rasterize a shapefile of the California state boundaries in different resolutions. 
When repeating the same commands, I yield different output files. I'm demonstrating this with the CDO (Climate Data Operators) file information I yield when repeating the same command line.  

date;for RES in 0.05 0.1 0.25 0.5 1.0;do gdal_rasterize -of netCDF -at -a FID  -sql "select FID, * from testwgs84" -te -180 -90 180 90 -tr ${RES} ${RES}  -a_nodata 0 -ot Float32 testwgs84.shp testwgs84.${RES}.nc;done;cdo -s infov *.nc|grep Band;rm *.nc
Thu Aug 30 07:48:20 CEST 2018
0...10...20...30...40...50...60...70...80...90...100 - done.
0...10...20...30...40...50...60...70...80...90...100 - done.
0...10...20...30...40...50...60...70...80...90...100 - done.
0...10...20...30...40...50...60...70...80...90...100 - done.
0...10...20...30...40...50...60...70...80...90...100 - done.
     1 : 0000-00-00 00:00:00       0 25920000 25920000 :                     nan             : Band1
     1 : 0000-00-00 00:00:00       0  6480000 6480000 :                     nan             : Band1
     1 : 0000-00-00 00:00:00       0  1036800 1036800 :                     nan             : Band1
     1 : 0000-00-00 00:00:00       0   259200     224 :  9.9692e+36  9.9692e+36  9.9692e+36 : Band1
     1 : 0000-00-00 00:00:00       0    64800      69 :  9.9692e+36  9.9692e+36  9.9692e+36 : Band1

date;for RES in 0.05 0.1 0.25 0.5 1.0;do gdal_rasterize -of netCDF -at -a FID  -sql "select FID, * from testwgs84" -te -180 -90 180 90 -tr ${RES} ${RES}  -a_nodata 0 -ot Float32 testwgs84.shp testwgs84.${RES}.nc;done;cdo -s infov *.nc|grep Band;rm *.nc
Thu Aug 30 07:48:24 CEST 2018
0...10...20...30...40...50...60...70...80...90...100 - done.
0...10...20...30...40...50...60...70...80...90...100 - done.
0...10...20...30...40...50...60...70...80...90...100 - done.
0...10...20...30...40...50...60...70...80...90...100 - done.
0...10...20...30...40...50...60...70...80...90...100 - done.
     1 : 0000-00-00 00:00:00       0 25920000   17759 :  9.9692e+36  9.9692e+36  9.9692e+36 : Band1
     1 : 0000-00-00 00:00:00       0  6480000 6480000 :                     nan             : Band1
     1 : 0000-00-00 00:00:00       0  1036800     800 :  9.9692e+36  9.9692e+36  9.9692e+36 : Band1
     1 : 0000-00-00 00:00:00       0   259200  259200 :                     nan             : Band1
     1 : 0000-00-00 00:00:00       0    64800   64800 :                     nan             : Band1

Thanks for your help solving this behaviours. Lika. 

## Steps to reproduce the problem.
wget https://data.ca.gov/sites/default/files/CA_State.zip
unzip CA_State.zip
ogr2ogr -f "ESRI Shapefile" -t_srs EPSG:4326 testwgs84.shp CA_State_TIGER2016.shp
for RES in 0.05 0.1 0.25 0.5 1.0;do gdal_rasterize -of netCDF -at -a FID  -sql "select FID, * from testwgs84" -te -180 -90 180 90 -tr ${RES} ${RES}  -a_nodata 0 -ot Float32 testwgs84.shp testwgs84.${RES}.nc;done
## Operating system
OSX Yosemite 10.10.5 (14F2511)
## GDAL version and provenance
GDAL 2.2.4, released 2018/03/19 from conda-forge  (with python=3.5)

**Comment by rouault** [comment]
I've fixed the likely cause for your issue. I'd note however that as FID = 0 is a valid FID for a shapefile source, the choice of 0 as nodata isn't appropriate.
