### ISSUE TITLE
warper: number of bands affects result

### ISSUE THREAD

**Issue by mdsumner** [OSGeo/gdal#8917]
When warping this single-band source (720x90) with bands repeated, the warp result for all bands changes if the repeated bands exceed 110. 

This code defines a dsn from a single band tif, but repeats it with 'vrt://{dsn}?bands=1,1,1,...', and then warps to an arctic polar raster (100x100). 

When n(umber) of band repeats is 111 or greater the checksum of the result for all bands changes from 9726. 

```python3
from osgeo import gdal

gdal.UseExceptions()
crs = "+proj=stere +lat_0=90 +lat_ts=71 +lon_0=0 +k=1 +x_0=0 +y_0=0 +datum=WGS84 +units=km +no_defs +ellps=WGS84 +towgs84=0,0,0"

## any number of bands between 1 and 110 gives Checksum == 9726
## above 110 it changes, and again at 119, and 123

n = 111
bands = ",".join(["1"] * n)
dsn = f'vrt:///vsizip//vsicurl/https://github.com/rspatial/terra/files/13201515/projectIssueExample.zip/projectIssueExample/iceconc.tif?bands={bands}'
ds = gdal.Warp("/tmp/warped.tif", dsn, 
                                  outputBounds = [-4500, -4500, 4500, 4500], 
                                  width = 100, height = 100,
                                  dstSRS = crs, options = ["-overwrite", "-r", "bilinear"])
 
 
## assertion fails if n >= 111                               
assert ds.GetRasterBand(1).Checksum() == 9726
assert ds.GetRasterBand(ds.RasterCount).Checksum() == 9726
```

The checksum should stay the same for all bands and for any number of band repeats. 

Reported in https://github.com/rspatial/terra/issues/1327

**Comment by piyushrpt** [comment]
Could you turn in `CPL_DEBUG=ON` and see what is happening. I suspect this has to do with adjusting the block size based on the number of bands in the destination dataset. Also could you try this with error_threshold set to 0.

**Comment by rouault** [comment]
The reason is that between 110 and 111 the default warping memory of 60 MB is exceeded, hence the warper divides into 2 chunks. This in turns affects the way the ratio number_of_target_pixels / number_of_source_pixels is computed for each chunk.
Several potential resolutions:
- increase -wm
- or impose a fixed value for the ratio. The ratio is difficult to compute appropriately for polar projections. You can start adding  "-wo", "XSCALE=1", "-wo", "YSCALE=1" to your options[] warping array, and potentially tune them to get a nice looking result.

**Comment by mdsumner** [comment]
ah indeed, thank you - increasing wm fixes it

I'll explore more, I hadn't understood this before about what XSCALE and YSCALE are and will investigate the debug messaging.

**Comment by rhijmans** [comment]
Sorry to comment on a long closed issue, but I do not think it has been resolved. The core problem seems to be that the warp algorithm does not always produce mathematically correct results, especially near the chunk boundaries. _tuning parameters to get a nice looking result_ does not meaningfully address that. How are we to know when values are actually correct? I take it that even a large single layer raster is prone to this problem. There may be a trade-off between speed and precision; if so, it would be nice to be able to choose max precision. Should this issue be reopened, or a new one created? Or should I considered this to be beyond repair?

**Comment by rouault** [comment]
The XSCALE and YSCALE options are now documented in https://gdal.org/en/stable/programs/gdalwarp.html#frequently-asked-questions
