### ISSUE TITLE
Http response errors in VSI curl VFS are only returned once

### ISSUE THREAD

**Issue by mrob95** [OSGeo/gdal#8922]
## Expected behavior and actual behavior.

When the VSI curl virtual filesystem encounters a non-200 status code, it's intended to set an error with the status code that was returned, see here - https://github.com/OSGeo/gdal/blob/master/port/cpl_vsil_curl.cpp#L1506

Somehow this error state doesn't seem to be being cleared correctly though, as subsequent reads of the same (failed) url return a much more generic and less descriptive error message.

## Steps to reproduce the problem.

This Python script reproduces the issue reliably: 

```python
from osgeo import gdal

url = 'http://example.com/path/to/your/file.tif'

gdal.UseExceptions()

print("=== ATTEMPT 1 ===")

try:
    dataset = gdal.Open(f'/vsicurl/{url}')
except Exception as e:
    print(f'Error: {e}')

print("=== ATTEMPT 2 ===")

try:
    dataset = gdal.Open(f'/vsicurl/{url}')
except Exception as e:
    print(f'Error: {e}')
```

Running it using the latest ubuntu-full docker image gives:

```
root@67b6c616908d:/# gdalinfo --version
GDAL 3.9.0dev-c1369ecc4b9a36315d1e9c685f4153c23f735386, released 2023/11/28

root@67b6c616908d:/# python bug.py
=== ATTEMPT 1 ===
Error: HTTP response code: 404
=== ATTEMPT 2 ===
Error: `/vsicurl/http://example.com/path/to/your/file.tif' does not exist in the file system, and is not recognized
 as a supported dataset name.
```

As you can see, the second time the same call is made the error message gives a lot less indication of what the problem is. This is a big problem for us running it in a long-lived web server process and needing to distinguish between authentication/authorisation/other http errors.

Running with debug logs enabled gives an indication that we may only be making one http request and then mistakenly caching the result. Setting `VSI_CACHE=FALSE` made no difference though.

```
root@67b6c616908d:/# CPL_DEBUG=ON python bug.py
=== ATTEMPT 1 ===
HTTP: libcurl/7.81.0 OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libidn2/2.3.2 libpsl/0.21.0 (+libidn2/2.3.2) libssh/0.9.6/openssl/zlib nghttp2/1.43.0 librtmp/2.3 OpenLDAP/2.5.16
VSICURL: GetFileSize(http://example.com/path/to/your/file.tif)=0  response_code=404
VSICURL: GetFileList(/vsicurl/http://example.com/path/to/your)
Error: HTTP response code: 404
=== ATTEMPT 2 ===
Error: `/vsicurl/http://example.com/path/to/your/file.tif' does not exist in the file system, and is not recognized as a supported dataset name.
```

## Operating system

Ubuntu 22.04 64-bit

## GDAL version and provenance

Reproduced on `GDAL 3.9.0dev-c1369ecc4b9a36315d1e9c685f4153c23f735386, released 2023/11/28`, from the public container registry (https://github.com/OSGeo/gdal/pkgs/container/gdal/152385880?tag=ubuntu-full-latest)

**Comment by mrob95** [comment]
> You may want to define CPL_VSIL_CURL_NON_CACHED=/vsicurl/ 

Thanks! This does seem to improve the behaviour but I worry about the impact on performance of disabling the cache. For context I'm using the `titiler` library for dynamic tiling of COG images, so the standard workload is a lot of highly correlated but independent reads which to benefit a lot from caching.

**Comment by rouault** [comment]
I guess we could potentially cache the 404 error in the FileProp structure where we store cached properties of a file

**Comment by mrob95** [comment]
Yeah that could work. Is there a benefit to caching failed reads or would it be better to never cache them and retry every time? I guess currently that if someone reads a file that doesn't exist, gets a 404, then creates the file, they would still see the stale error, and the same for authorisation issues etc.

**Comment by rouault** [comment]
> Is there a benefit to caching failed reads

yes, there are situations where code might ask several times for the existence of a file. Caching that it doesn't exist has some benefits

>  I guess currently that if someone reads a file that doesn't exist, gets a 404, then creates the file, they would still see the stale error, and the same for authorisation issues etc.

There's a VSICurlClearCache() for that : https://gdal.org/api/cpl.html#_CPPv417VSICurlClearCachev

**Comment by mrob95** [comment]
> There's a VSICurlClearCache() for that

Thanks, this looks useful - in particular we could `VSICurlPartialClearCache` for the file after receiving a http error to force a retry without slowing down successful reads. I'll experiment with it.
