### ISSUE TITLE
Problem with FlushCache(true) to mimic a cache "drop"

### ISSUE THREAD

**Issue by chacha21** [OSGeo/gdal#8938]
If I remember correclty, the `bool bAtClosing = false` parameter of `GDALRasterBand::FlushCache()` has been introduced in #4652.
However, I have a scenario where it was misleading and lead me to a very unexpected and hard to find bug (my fault, but still !).

The scenario is :

1. I use a dataset D as a temporary space to store processed data that is regularly updated.
2. I don't care if everything occurs in cache, it will swap to disk as necessary, I just read to and write from D.
3. At the end of my work session, the remaining data in D is no more relevant.
4. I want to "drop" the cache of D to release resources and free cache for other uses, without paying the penalty of flushing to disk, since data is no more relevant.
5. I call D.FlushCache(true), (which has the effect of setting `m_bWriteDirtyBlocks` to `false` inside `DisableDirtyBlockWriting()`)
6. I start a new work session, reusing D as an intermediate storage
7. Since nothing reverted `m_bWriteDirtyBlocks` the cache is permanently marked as "not flushable" (that's the reason of the bug to come)
8. For some reason, the data remaining in D will be relevant that time, and I want to save it.
9. I call some `GDALDriver::CreateCopy(D)`
10. However, since the cache cannot be flushed any more, what I get is old deprecated data that was swapped to disk during previous work sessions.

The problem is in step 5 where I lied to `FlushCache()`, because I am not really closing the dataset, I just wanted to drop the cache without penalty.

Is it possible to either  restore `m_bWriteDirtyBlocks = true` after a `FlushCache(true)`, or to get a new native DropCache() feature that leaves `m_bWriteDirtyBlocks ` untouched ?

**Comment by chacha21** [comment]
A proposal (not sure if it's enough, just to locate the problem)

```
CPLErr GDALRasterBand::FlushCache(bool bAtClosing)

{
    if (bAtClosing && poDS && poDS->bSuppressOnClose && poBandBlockCache)
        poBandBlockCache->DisableDirtyBlockWriting();

    CPLErr eGlobalErr = eFlushBlockErr;

    if (eFlushBlockErr != CE_None)
    {
        ReportError(
            eFlushBlockErr, CPLE_AppDefined,
            "An error occurred while writing a dirty block from FlushCache");
        eFlushBlockErr = CE_None;
    }

    if (poBandBlockCache == nullptr || !poBandBlockCache->IsInitOK())
        return eGlobalErr;

   //return poBandBlockCache->FlushCache();//<---------from here
   CPLErr result = poBandBlockCache->FlushCache();
    if (bAtClosing && poDS && poDS->bSuppressOnClose && poBandBlockCache)
        poBandBlockCache->EnableDirtyBlockWriting();
  return result;
}

```

**Comment by rouault** [comment]
> 5\. I call D.FlushCache(true),

you shouldn't do that. The boolean is bAtClosing. Calling FlushCache(true) without immediately closing the dataset afterwards is "illegal"
Cf the doc of the method:
```
 * @param bAtClosing Whether this is called from a GDALDataset destructor
```

> or to get a new native DropCache() feature that leaves m_bWriteDirtyBlocks untouched ?

That would be cleaner if you want to propose a PR to do that.
