### ISSUE TITLE
S-57 reader has incorrect date on DSID

### ISSUE THREAD

**Issue by mswope** [OSGeo/gdal#895]
## Expected behavior and actual behavior.

running ogrinfo on an enc cell with an update - on the DSID layer,
the DSID_ISDT (issue date) is incorrect, it just has the same value as DSID_UADT (update application date). 

## Steps to reproduce the problem.

Get a file from www.charts.noaa.gov/ENCs/ENCsIndv.shtml
I used US1AK90M as it has 3 update files. Also note what that page says for the issue date and the update application date. 

If I open an update file (.001+) in a text editor, I see the date on the second line. 

## Operating system

For example: Windows 10

## GDAL version and provenance

For example: the 2.2.0 from QGIS -osgeo4w.

**Comment by rouault** [comment]
Looking with the low-level 8211dump debug utility in the individual files, I see that UADT is only set on the .000 file and set to blank in the .001+ files, whereas ISDT is incremented in the .001+ files. So updating the UADT wouldn't appear to be the correct way. Anyway, there is currently no logic to update the content of the DSID read from the .000 file, except the DSID_UPDN field

```
US1AK90M.000
      Subfield `UADT' = `20171128'
      Subfield `ISDT' = `20171128'

US1AK90M.001
      Subfield `UADT' = `        '
      Subfield `ISDT' = `20171213'
```

**Comment by rouault** [comment]
@hlaebe I see commits from you referencing this ticket. Did you submit a pull request with them ?

**Comment by hlaebe** [comment]
@rouault No, I'm afraid I lost sight of that, but I'll do some test and then do a PR. Thanks for noticing.
