### ISSUE TITLE
Clarify filename extensions are paramount

### ISSUE THREAD

**Issue by jidanni** [OSGeo/gdal#8950]
Both the
- Common options for raster programs
- Common options for vector programs

documentation say

> in some situations, several drivers may recognize the same file. The -if option of some utilities can be specified to ask to use a particular driver to open the dataset. Alternatively, the GDAL_SKIP configuration optio...

OK, but be sure to mention:

> Note that -if cannot be used to override filename extension. -if is
only for picking between matches. But that is only after the filename
extension has been read. So the only way to override the extension is
to copy or symlink the file to an extension that the program can deal
with. E.g., `cp xyz.zzz xyz.kml` , then `ogrinfo xyz.kml` will work on it.

Proof:
```
$ ogrinfo /tmp/nsdakmon.kmz
INFO: Open of `/tmp/nsdakmon.kmz'
      using driver `LIBKML' successful.
1: nsdakmon
$ cp /tmp/nsdakmon.kmz /tmp/nsdakmon.zzz
$ ogrinfo /tmp/nsdakmon.zzz
ERROR 4: `/tmp/nsdakmon.zzz' not recognized as a supported file format.
ogrinfo failed - unable to open '/tmp/nsdakmon.zzz'.
$ ogrinfo -if LIBKML /tmp/nsdakmon.zzz
ERROR 4: `/tmp/nsdakmon.zzz' not recognized as a supported file format.
ogrinfo failed - unable to open '/tmp/nsdakmon.zzz'.
$ ogrinfo -if KML /tmp/nsdakmon.zzz
ERROR 4: `/tmp/nsdakmon.zzz' not recognized as a supported file format.
ogrinfo failed - unable to open '/tmp/nsdakmon.zzz'.
```

I even tried LIBKML:/tmp/nsdakmon.zzz . That didn't work either.

Therefore the documentation should say that filename extensions are
paramount, and the only workaround to a "badly named" file would be
copying the file or symlinking.

I could have submitted a feature request,
"Allow or document overriding filename extensions"
but for now just please do the documentation part.

**Comment by jratike80** [comment]
It works almost for me with GDAL 3.9.0dev. It is only almost because in both cases the LIBKML gets selected.


```
ogrinfo -if LIBKML data.xxx
INFO: Open of `data.xxx'
      using driver `LIBKML' successful.
1: test

ogrinfo -if KML data.xxx
INFO: Open of `data.xxx'
      using driver `LIBKML' successful.
1: test
```

**Comment by rouault** [comment]
> However, I think that this is a bug.

indeed, fixed in https://github.com/OSGeo/gdal/pull/8952

**Comment by jidanni** [comment]
All I know is I had to symlink
```
IL_CadNSDI_V2.gdb.zip -> IL_CadNSDI_V2.gdb_.zip
```
because there is(?) no way to get the same cheery results,
```
$ ogrinfo IL_CadNSDI_V2.gdb.zip 
INFO: Open of `IL_CadNSDI_V2.gdb.zip'
      using driver `OpenFileGDB' successful.
```
because there is no way to tell it to use the same driver on the ugly version of the filename, because it looks first at the filename and barfs and never gets around to what I might try to tell it.
