### ISSUE TITLE
gdal_contour don't deal with zoff from DERIVEDPROJCRS correctly

### ISSUE THREAD

**Issue by ChenChihYuan** [OSGeo/gdal#8960]
## Expected behavior and actual behavior.
I expect the tiff files hold a different zoff of a DERIVEDPROJCRS passing to gdal_contour should give me different result.

## Steps to reproduce the problem.

I have these files as a small bug test.

- heightmapSite1.tiff (which zoff is set as 0
- heightmapSite1.tiff.aux.xml
- output1.geojson
- heightmapSite2.tiff (which zoff is set as 100
- heightmapSite2.tiff.aux.xml
- output2.geojson

```
gdalinfo heightmapSite.tiff // we will see the tiff holds a DERIVEDPROJCRS
gdal_contour -3d heightmapSite.tiff output.geojson -f geojson -i 0.2 
diff output1.geojson output2.geojson // should no different, if you check the z value of both of them are identical as well
```

## Operating system

Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy

## GDAL version and provenance

GDAL 3.7.2, released 2023/09/05 (debug build)

proj version: Rel. 9.3.0, September 1st, 2023

[smallExample.zip](https://github.com/OSGeo/gdal/files/13650190/smallExample.zip)

**Comment by rouault** [comment]
> Would you tell me how could I know if the raster values are identical?
```
$ gdalinfo -checksum smallExample/heightmapSite1.tiff | grep Checksum
  Checksum=10187
$ gdalinfo -checksum smallExample/heightmapSite2.tiff | grep Checksum
  Checksum=10187
```

**Comment by ChenChihYuan** [comment]
Thank you. Would it be a reasonable expect that using a heightmap.tiff with different targetSRS should produce two different heightmapSite.tiff, meaning different raster values(Checksum)? 

In my case, targetSRS is the `DERIVEDPROJCRS` (zoff with 0 value, and zoff with 100)

```
gdalwarp -s_srs sourceSRS -t_srs targetSRS_1 heightmap.tiff heightmapSite1.tiff
gdalwarp -s_srs sourceSRS -t_srs targetSRS_2 heightmap.tiff heightmapSite2.tiff
```

**Comment by rouault** [comment]
> Would it be a reasonable expect that using a heightmap.tiff with different targetSRS should produce two different heightmapSite.tiff, meaning different raster values(Checksum)?

as derivedprojectedCRS are rather estoreric, you need to add the "-vshift" switch to your gdalwarp command line:  https://gdal.org/programs/gdalwarp.html#cmdoption-gdalwarp-vshift:
```
$ gdalwarp smallExample/heightmapSite1.tiff out.tif -t_srs "$(cat test.wkt)" -overwrite -q && gdalinfo -mm out.tif | grep Max
    Computed Min/Max=0.000,2.935
$ gdalwarp smallExample/heightmapSite1.tiff out.tif -t_srs "$(cat test.wkt)" -overwrite -q -vshift && gdalinfo -mm out.tif | grep Max
    Computed Min/Max=100.000,102.935
```
