### ISSUE TITLE
GTiff: 32 bit integer overflow when reading files with huge xsize/ysize/band count -> 64 bit support?

### ISSUE THREAD

**Issue by hwi42** [OSGeo/gdal#897]
This is a feature request, no bug report.

I am using the software ENVI and SARscape. Both rely on the GDAL lib to read GeoTiff files. 
During my work with large GeoTiff files (satellite images), which can contain their data in strips or tiles larger than 2 GB, the error "Scanline/tile/strip size bigger than 2GB." was reported in the logfile.

This led me to the trac ticket https://trac.osgeo.org/gdal/ticket/6288#no1 from 3 years ago. The same behavior was reported, but the solution then was to reject the files:
 
"libtiff v4 allows strips/tiles/scanlines to be bigger than 2 GB, but the GTiff driver doesn't. It could potentially be extended to support that (on 64 bit builds), but the need for that isn't obvious for now, so better reject those files for now. Issue found by AFL" 

Three years have passed, and many satellite image products are larger by now (and will be even larger in the future). So I would like to ask to add 64 bit support to the GTiff driver in GDAL, to allow strips/tiles/scanlines to be bigger than 2 GB. 

I know that, even if GDAL gets enhanced, it will take more time to include the update in future ENVI / SARscape releases, but a long journey starts with the first step. 

GDAL versions according to customer support:
- ENVI (5.4) uses GDAL v1.11
- SARscape (5.4) uses GDAL v2.02
- But also the current GDAL version 2.3 does not support strips / tiles larger than 2 GB

Platform (for me) is Windows 64 bit.

**Comment by hwi42** [comment]
Hello Even,
happy New Year! 
Do you have a plan for the upcoming releases, when this enhancement could be implemented in GDAL?

**Comment by rouault** [comment]
> Do you have a plan for the upcoming releases, when this enhancement could be implemented in GDAL?

Would require funding. This is a non trivial change that impact changes in GDAL core and most drivers.

**Comment by hwi42** [comment]
The company where I work thinks about funding this issue. I'll send you a request for proposal via contact@spatialys.com

**Comment by rouault** [comment]
Has been addressed per https://github.com/OSGeo/gdal/pull/1306
