### ISSUE TITLE
gdaladdo ignores JXL_LOSSLESS=NO

### ISSUE THREAD

**Issue by Plantain** [OSGeo/gdal#8973]
## Expected behavior and actual behavior.
gdaladdo should respect the JXL_LOSSLESS flag and produce lossy JXL imagery. Instead it appears to override it and always produce lossless files.

Data: static.skysight.io/input.tif
gdaladdo --config JXL_DISTANCE 1.2 --config JXL_LOSSLESS NO --config COMPRESS_OVERVIEW JXL -ro input.tif

gdalinfo input.tif.ovr
Driver: GTiff/GeoTIFF
Files: input.tif.ovr
Size is 9945, 20525
Image Structure Metadata:
  COMPRESSION=JXL
  COMPRESSION_REVERSIBILITY=LOSSLESS (possibly)
  INTERLEAVE=BAND
Corner Coordinates:
Upper Left  (    0.0,    0.0)
Lower Left  (    0.0,20525.0)
Upper Right ( 9945.0,    0.0)
Lower Right ( 9945.0,20525.0)
Center      ( 4972.5,10262.5)
Band 1 Block=512x512 Type=Byte, ColorInterp=Red
  Overviews: 4973x10263, 2487x5132, 1244x2566, 622x1283, 311x642, 156x321, 78x161
Band 2 Block=512x512 Type=Byte, ColorInterp=Green
  Overviews: 4973x10263, 2487x5132, 1244x2566, 622x1283, 311x642, 156x321, 78x161
Band 3 Block=512x512 Type=Byte, ColorInterp=Blue
  Overviews: 4973x10263, 2487x5132, 1244x2566, 622x1283, 311x642, 156x321, 78x161

## GDAL version and provenance
GDAL 3.8.0, released 2023/11/06
gdal:ubuntu-full image

**Comment by jratike80** [comment]
I can see from https://gdal.org/drivers/raster/gtiff.html that those JXL options are supported as creation options, but I do not see any mention about supporting those as config options. But by your example ` --config COMPRESS_OVERVIEW JXL` still works.
