### ISSUE TITLE
MarkSuppressOnClose() : no IsSuppressOnClose() or UnMarkSuppressOnClose()

### ISSUE THREAD

**Issue by chacha21** [OSGeo/gdal#8980]
GDAL 3.8

Currently `GDALDataset::MarkSuppressOnClose()` just sets the internal `bSuppressOnClose`
I would need a`GDALDataset::IsSuppressOnClose()` to query that value
I would also like a`GDALDataset::UnmarkSuppressOnClose()` to revert that value

It seems trivial to implement, but before issueing a PR, do you know if there are any reason NOT to implement such functions ?
`IsSuppressOnClose()` must be harmless. But would `UnmarkSuppressOnClose()` expose to misleading scenarios ?

[edit]
For the context :
I want to reuse a dataset to store data with similar size and layout. But If the new data must be persistent, I must know if the dataset is doomed by bSuppressOnClose and should not be used for that usage.

**Comment by rouault** [comment]
I don't see strong reasons not to implement those methods
