### ISSUE TITLE
VFK: Generated invalid circle shaped parcel geometries

### ISSUE THREAD

**Issue by seidlmic** [OSGeo/gdal#8993]
## Expected behavior and actual behavior.

In some cases, parcel geometries defined by three points are wrongly generated. The problem is in computing center point and farther  four points on circle in axes direction.

## Steps to reproduce the problem.

Import SGI and SPI file 616397.vfk and look at parcel ID 1390618203.

## Operating system
Debian 11

## GDAL version and provenance
build from source Github master on 22.12.2023

**Comment by rouault** [comment]
CC @landam

**Comment by rouault** [comment]
Related pull request in https://github.com/OSGeo/gdal/pull/8995
