### ISSUE TITLE
GDALWarp doesn't correctly change projection from Unknown (with defined proj4) on Windows

### ISSUE THREAD

**Issue by FlashT** [OSGeo/gdal#8996]
## Expected behavior and actual behavior.

Expected result should look like this (this is the result from Linux machine):
https://i.stack.imgur.com/zYyYr.png

On Windows got just a black stripe instead.
Tried on Windows 10 and 11 on gdal 3.02, 3.5.1, 3.8.2, the same result.

## Steps to reproduce the problem.

Do `gdalwarp -t_srs EPSG:3857 -r near -of GTiff input.tif out.tif`
on `input.tif` from here: https://drive.google.com/drive/folders/1NyXjYqSJI8KUSgA4AwTQbfLHCQhxILPG?usp=sharing
The result is in: `output_gdalwarp.tif`, just a black bar across the Earth. Correct result is in `output_arcmap.tif` (basically the same output as from ArcMap, people are getting on Linux machines - check here: https://gis.stackexchange.com/questions/473367/change-projection-from-unknown-to-given-epsg-with-gdal)

## Operating system

Windows 11, Windows 10

## GDAL version and provenance

GDAL 3.8.2, released 2023/16/12 (from OSGeo4W shell).

**Comment by jratike80** [comment]
It is possible to exclude the most northern part of data that cannot be used with EPSG:3857 with the `-te` parameter. 

gdalwarp -t_srs EPSG:3857 -r near -of GTiff input.tif out.tif -te -180 -22 180 85 -te_srs epsg:4326

With that command GDAL 3.8.1 makes an image that looks like this

<img width="250" alt="image" src="https://github.com/OSGeo/gdal/assets/1751612/a47a107b-1d9c-47b4-a88b-9003e61c5de4">

**Comment by FlashT** [comment]
> Windows vs Mac has no role but GDAL and maybe Proj versions do. Notice that the result that looks good is not actually correct because some data are clipped without user asking to do so.
> 
> With all GDAL versions it is possible to exclude the most northern part of data above +85 degrees N that cannot be used with EPSG:3857 with the `-te` parameter.
> 
> `gdalwarp -t_srs EPSG:3857 -r near -of GTiff input.tif out.tif -te -180 -22 180 85 -te_srs epsg:4326`
> 

What exactly is clipped? I didn't notice anything missing. Even compared to Your result.
If it is a case of proj version, then there is a difference between distributions on Windows in Linux. Because on Linux it work, on Windows it does not. Both freshly installed, on fresh OS'es. Anyway your solution worked, but I still consider it as a bug in GDAL. [rouault](https://github.com/rouault) proposed a fix for it above.

**Comment by jratike80** [comment]
The source image has the centre at the North Pole. What if clipped is the segment of the sphere north to 85 degrees N. In native crs the data looks like this this
<img width="125" alt="image" src="https://github.com/OSGeo/gdal/assets/1751612/46d086ad-25d0-48b5-9334-c0b909de5c41">

If someone happens to be interested in the ice coverage around the North pole or something like that then it is obvious that EPSG:3857 is not a usable coordinate system for them.

By defining the `-te` gdalwarp does not even try to transform pixels that cannot be transformed into EPSG:3857.
Those who make Mac, Linux and Windows distributions are free to select what versions they use in their builds.  The fresh installation of GDAL may contain some not so fresh version of Proj.

**Comment by FlashT** [comment]
Yes, I understand that. Still the difference in behaviour is huge. On Linux it behaves like paid GiS software. On Windows it simply fails by generating 0-value stripe, not even close to covering the area.

**Comment by jratike80** [comment]
Yes, a certain GDAL version obviously generates unusable result. I wouldn't say that ArcMap is generating a correct result either. The northmost extent of the output is 30240971 m that is far beyond the valid area of the EPSG:3857 crs (20048966.1 m). However, data from the polar area is missing even the area seems to be covered by the output image. And the bubbles in the south are something not true really. 
<img width="178" alt="image" src="https://github.com/OSGeo/gdal/assets/1751612/c13a951c-6448-453b-8ff2-6d9ca87870df">

Maybe the good option for both ESRI and GDAL would be to clip to valid bounds and warn users that some data gets lost.
