### ISSUE TITLE
latest MrSID SDK (9.5.4-4709) causes procedure entry point not found with Visual Studio 2017

### ISSUE THREAD

**Issue by jmckenna** [OSGeo/gdal#900]
- using latest MrSID SDK from https://www.lizardtech.com/developer/portal-sdk#windows
- causes the following error when trying to run the GDAL utilities:
```
The procedure entry point ?retain@Object@LizardTech@@QBEHXZ could not be located in the 
dynamic link library C:\ms4w\Apache\cgi-bin\gdal203.dll. 
```
- tested with GDAL 2.3.1   and Visual Studio 2017
- using an older MrSID SDK works (9.5.4-4705)

**Comment by rouault** [comment]
@kirkoman any idea about that issue ?

**Comment by jmckenna** [comment]
Note that this issue doesn't exist with GDAL 2.4.0

**Comment by rouault** [comment]
Closing if no longer reproducable with 2.4.0
