### ISSUE TITLE
`LasAnimas.dgn' not recognized as a supported file format.

### ISSUE THREAD

**Issue by jidanni** [OSGeo/gdal#9004]
```
$ wget https://www.codot.gov/business/designsupport/cadd/ms/microstation-inroads-configuration/county-maps/lasanimas.dgn
$ ogrinfo --format dgn|grep Exte
  Extension: dgn
$ file LasAnimas.dgn 
LasAnimas.dgn: Composite Document File V2 Document, Little Endian, Os: Windows, Version 5.1, Code page: 1200, Locale ID: 1033, Author: hawki, Total Editing Time: 00:00, Create Time/Date: Mon Feb  6 03:24:40 2006, Last Saved By: hawki, Last Saved Time/Date: Fri Sep 15 20:32:04 2006, Revision Number: 13, Name of Creating Application: MicroStation
$ ogrinfo LasAnimas.dgn 
ERROR 4: `LasAnimas.dgn' not recognized as a supported file format.
ogrinfo failed - unable to open 'LasAnimas.dgn'.
```

P.S., I would say "not recognized as _being in_ a supported file format".

Also, able to open, but not able to read... correctly.

But odd that it can't deal with the file.

**Comment by rouault** [comment]
This is a DGNv8 file that requires GDAL to be built with the Open Design Alliance Teigha proprietary SDK: https://gdal.org/drivers/vector/dgnv8.html

**Comment by jidanni** [comment]
(Well OK, but I wish the error message would say something like that, else the next guy who encounters this will just post the exact same bug report.)

**Comment by rouault** [comment]
fair enough. Cf https://github.com/OSGeo/gdal/pull/9005
