### ISSUE TITLE
Error on uploading iOS app due to libgdal.dylib and other gdal libs

### ISSUE THREAD

**Issue by huzaifacontour** [OSGeo/gdal#9016]
## Expected behavior and actual behavior.

I have iOS app which have Gdal dynamic libs: libgdal.dylib, libgdal_wrap.dylib, libgdalconst_wrap.dylib, libosr_wrap.dylib, and libogr_wrap.dylib. I placed these files in Framework folder because apple doesn't accept dynamic elsewhere and signed them.
Now I'm having error from App store Connect that I miss SwiftSupport folder, this kind of error we received when we have dynamic libs in our Payload. I added that folder manually still having errors related to this.
Did I miss something with GDAL libs or should I have to place them elsewhere?
My application framework is .net8-ios

App should be published to app store.

## Steps to reproduce the problem.

Upload iOS ipa file to app store which have gdal dynamic libs placed in Framework folder.

## Operating system
macOS

## GDAL version and provenance
3.7.2

**Comment by rouault** [comment]
Not sure there is anything to do on GDAL side. At least I can't help as I'm iOS illiterate

**Comment by huzaifacontour** [comment]
Okay yeah I need someone with iOS Knowledge from your side, if gdal is only compiling as dynamic libs then how we upload the application to apple store?

**Comment by rouault** [comment]
https://gis.stackexchange.com/questions/434514/build-gdal-3-x-for-ios should be of help
