### ISSUE TITLE
GDALOpenEx chooses wrong driver for .gdb directories

### ISSUE THREAD

**Issue by raffihsieh** [OSGeo/gdal#902]
## Expected behavior and actual behavior.

I expected to provide GDALOpenEx(...) the path to a .gdb directory and have the geodatabase be opened with no problem.
Instead I keep getting an error "No mapinfo files found in directory..."

In order to get around this issue, I can specify the OpenFileGDB driver after which the dataset is opened just fine. For some reason, without specifying the driver, GDALOpenEx seems to think the .gdb directory is a mapinfo file ? 

## Steps to reproduce the problem.

GDALOpenEx(<path to .gdb directory>, GDAL_OF_VECTOR, nullptr, nullptr, nullptr)

## Operating system

Windows

## GDAL version and provenance

2.2.1

**Comment by jratike80** [comment]
Does the path have any role? Is the error the same if you use path like c:\test\mygdb.gdb?

**Comment by raffihsieh** [comment]
I tried with different .gdb files in different paths and got the same result so I don't think so.
What I believe is the problem is that when you don't specify a driver when using GDALOpenEx() it loops through all the possible drivers and decides which one is appropriate. For some reason it chooses the wrong one for .gdb directories.

**Comment by rouault** [comment]
Is your GDAL source code unmodified ? Normally the code path that emits "No mapinfo files found in directory" is dead code in practice

**Comment by raffihsieh** [comment]
I do believe that the GDAL source code is unmodified.
What do you mean that it is dead code "in practice" ?

**Comment by rouault** [comment]
> What do you mean that it is dead code "in practice" ?

There is a boolean flag that conditionalize the execution of that line, and I can't see how it could be set to true, so the error should not be emitted, the driver returning NULL quietly and GDALOpenEx() should proceed to the next drivers

**Comment by rouault** [comment]
@raffihsieh  Did you try with the builds at http://gisinternals.com/stable.php ?
