### ISSUE TITLE
I have a perplexity about read elevation.

### ISSUE THREAD

**Issue by Febfire** [OSGeo/gdal#903]
I open img file to read elevation.But the array i got contains "...".What does it means?I want to get all the elevation of the img.What should i do?
![image](https://user-images.githubusercontent.com/37166494/45197677-24149500-b295-11e8-82ff-39c64892b370.png)

## Expected behavior and actual behavior.

Expected to get all elevation data.

## Steps to reproduce the problem.

contains "..."

## Operating system

Win10

## GDAL version and provenance

2.1.3 python

**Comment by jratike80** [comment]
Please use gdal-dev mailing list for asking questions about how to use GDAL.
