### ISSUE TITLE
gdal footprint core

### ISSUE THREAD

**Issue by yelkindiyebiri** [OSGeo/gdal#9035]
Hi all !!!
I need help speeding up the gdal_footprint.py script. Currently, it seems to use only one core and runs quite slowly. Is there a way to make it use multiple cores for better performance? Any tips or guidance on making it run faster would be really helpful. Thanks!

**Comment by rouault** [comment]
> is there a way to make it use multiple cores for better performance?

no

> Any tips or guidance on making it run faster would be really helpful.

perhaps try computing overviews and use the -ovr option: https://gdal.org/programs/gdal_footprint.html#cmdoption-gdal_footprint-ovr
