### ISSUE TITLE
the iterator to unique_ptr returned by OGRLayer::begin() is invalid, but range based for loop is ok

### ISSUE THREAD

**Issue by yobeonline** [OSGeo/gdal#9039]
## Expected behavior and actual behavior.

In the following program, I use GDALOpenEx to open a tab file that contains one layer which holds at least one feature. Yet, calling OGRLayer::begin() on that layer returns an invalid pointer, instead of a valid pointer to the first feature.
```cpp
#include <memory>
#include "ogrsf_frmts.h"

int main() {
  GDALAllRegister();

  std::unique_ptr<GDALDataset, decltype(&GDALClose)> pDataSet(static_cast<GDALDataset*>(GDALOpenEx("export_test_line.tab", GDAL_OF_VECTOR | GDAL_OF_READONLY, nullptr, nullptr, nullptr)), GDALClose);

  assert(1 == pDataSet->GetLayerCount() && "I know the file has one layer");

  auto const layer = pDataSet->GetLayer(0);
  assert(layer && "I don't expect GDAL to lie about there being one layer");

  assert(1 == layer->GetFeatureCount(true) && "I know the file has one feature");
  auto const & f = *(layer->begin());
  // pointer held by f is invalid : address is like 0xddddddd

  return 0;
```

To my surprise, using a range based for loop works fine (doesn't it call begin/end behind the scenes?), but feature count becomes wrong, suddenly returning zero instead of 1.
```cpp
#include <memory>
#include "ogrsf_frmts.h"

int main() {
  GDALAllRegister();

  std::unique_ptr<GDALDataset, decltype(&GDALClose)> pDataSet(static_cast<GDALDataset*>(GDALOpenEx("export_test_line.tab", GDAL_OF_VECTOR | GDAL_OF_READONLY, nullptr, nullptr, nullptr)), GDALClose);

  assert(1 == pDataSet->GetLayerCount() && "I know the file has one layer");

  auto const layer = pDataSet->GetLayer(0);
  assert(layer && "I don't expect GDAL to lie about there being one layer");

//  assert(1 == layer->GetFeatureCount(true) && "I know the file has one feature");
//  auto const & f = *(layer->begin());
    
  for (auto const& f1 : *layer) {
    // pointer held by f is ok but for some reason, the below assert fails.
    assert(1 == layer->GetFeatureCount(true) && "I already tested that.");
  }

  return 0;
```

I enclosed the test tab file in case it matters : [test.zip](https://github.com/OSGeo/gdal/files/13861865/test.zip)

## Operating system
Windows 10 Entreprise
Version	22H2
Build 	19045.3803

## GDAL version and provenance
GDAL 3.7.2 installed from vcpkg build 8eb57355a4ffb410a2e94c07b4dca2dffbee8e50, x64-windows-static, msvc-16.

**Comment by jratike80** [comment]
Ogrinfo has no problem

```
ogrinfo export_test_line.tab -al -so
INFO: Open of `export_test_line.tab'
      using driver `MapInfo File' successful.

Layer name: export_test_line
Geometry: Line String
Feature Count: 1
Extent: (591402.100000, 2434457.000000) - (591438.300000, 2434471.800000)
...

```

**Comment by rouault** [comment]
First issue with ``auto const & f = *(layer->begin());`` is a C++ issue
layer->begin() returns an iterator object, and unreferencing it returns a unique_ptr<OGRFeature>. The correct way of using it is like in the following
```
  auto iter = layer->begin();
  (*iter)->DumpReadable(stdout);
```

Second issue with GetFeatureCount() not working in a loop is expected as GetFeatureCount() might cause feature iterations. Cf https://gdal.org/doxygen/classOGRLayer.html#a2d0e1a43fd1a0a6d55d766384da7b6a5 which mentions "Note that some implementations of this method may alter the read cursor of the layer.", hence it is not safe to call it in a loop that iterates over features

**Comment by rouault** [comment]
> Therefore, I had a dangling reference because the begin iterator was destroyed too early, destroying the `std::unique_ptr` alltogether.

yes, that's rather what I meant
