### ISSUE TITLE
 VSI_TIFFOPEN symbol not found,

### ISSUE THREAD

**Issue by jingcb** [OSGeo/gdal#904]
hi,   when i build gdal-2.3.1, the error happend : 

 Undefined symbols for architecture x86_64:
  "VSI_TIFFOpen(char const*, char const*, __sFILE*)", referenced from:.....
 
and I found that happend after  setting --enable-debug
the following is my setting:
 ./configure --with-spatialite --with-pg --with-curl --with-openjpeg --with-libtiff=internal --with-geotiff=internal --enable-debug

**Comment by rouault** [comment]
This is probably an issue of not doing a "make clean" after having built a first time with different configure options

**Comment by jingcb** [comment]
and kill --enable-debug, it is OK,          i use macos and ubuntu 16.04,   did i forget some important setting ?

**Comment by jingcb** [comment]
@rouault  no , i do "make clean", but it is not ok

**Comment by rouault** [comment]
Ah if the linking error is from your code, then you have to build it with -DDEBUG as well since VSILFILE* expands to different things in debug vs non-debug builds

**Comment by jingcb** [comment]
yeh, you are right, i forgot -DDEBUG,
thank you
