### ISSUE TITLE
ogr2ogr with MySQL 8 (Wrong SRID)

### ISSUE THREAD

**Issue by YoshiakiYamasaki** [OSGeo/gdal#905]
## Steps to reproduce the problem.

I checked following issues.

 - ogr2ogr with MySQL 8 #782
 - Issue with Mysql import #899

However, ogr2ogr has another 2 issues with MySQL 8 as follows.

 1.Wrong SRID
 2.Wrong Axis Order

I explain about "Wrong SRID" on this issue. I'll submit another issue regarding "Wrong Axis Order".

[Wrong SRID]

I executed ogr2ogr as follows. The shape file has point data with SRID:2449.

C:\Users\yyamasak>ogr2ogr -f "MySQL" MYSQL:geotest,user=root,password=root C:\work\point_2449.shp
ERROR 1: MySQL error message:FUNCTION geotest.GeometryFromText does not exist Description: INSERT INTO `point_2449` (`SHAPE` , `gid`, `point_name`) VALUES (GeometryFromText('POINT (-25967.1563870895 -91961.8549916338)',1) , 1, 'nagoya_station')
ERROR 1: Unable to write feature 0 from layer point_2449.
ERROR 1: Terminating translation prematurely after failed
translation of layer point_2449 (use -skipfailures to skip errors)

Above SQL has a problem described at #782, #899. Therefore, I modified SQL as follows.

  [Modified SQL]
   INSERT INTO `point_2449` (`SHAPE` , `gid`, `point_name`) VALUES (ST_GeometryFromText('POINT (-25967.1563870895 -91961.8549916338)',1) , 1, 'nagoya_station');

   * I changed from "GeometryFromText" to "ST_GeometryFromText".

I executed above SQL with mysql Command-Line Tool. But it cause error as follows. Because SRID is wrong.

mysql> INSERT INTO `point_2449` (`SHAPE` , `gid`, `point_name`) VALUES (ST_GeometryFromText('POINT (-25967.1563870895 -91961.8549916338)',1) , 1, 'nagoya_station');
ERROR 3548 (SR001): There's no spatial reference system with SRID 1.

I modified SQL as follows.

  [Modified SQL]
   INSERT INTO `point_2449` (`SHAPE` , `gid`, `point_name`) VALUES (ST_GeometryFromText('POINT (-25967.1563870895 -91961.8549916338)',2449) , 1, 'nagoya_station');

   * I changed from "1" to "2449".

I executed above SQL with mysql Command-Line Tool. I could execute it.

mysql> INSERT INTO `point_2449` (`SHAPE` , `gid`, `point_name`) VALUES (ST_GeometryFromText('POINT (-25967.1563870895 -91961.8549916338)',2449) , 1, 'nagoya_station');
Query OK, 1 row affected (0.02 sec)

mysql>
mysql> SELECT OGR_FID,ST_ASText(SHAPE),gid,point_name FROM point_2449;
+---------+--------------------------------------------+------+----------------+
| OGR_FID | ST_ASText(SHAPE)                           | gid  | point_name     |
+---------+--------------------------------------------+------+----------------+
|       1 | POINT(-25967.1563870895 -91961.8549916338) |    1 | nagoya_station |
+---------+--------------------------------------------+------+----------------+
1 row in set (0.00 sec)

## Operating system
Windows 10

## GDAL version and provenance
C:\Users\yyamasak>gdalinfo --version
GDAL 2.3.1, released 2018/06/22

**Comment by rouault** [comment]
If you tried with GDAL 2.3.1 this is expected. The fix has been done later and will be available in GDAL 2.3.2. So you have to build from the git branch for now

**Comment by YoshiakiYamasaki** [comment]
Thank you. I'm looking forward to releasing GDAL 2.3.2.
