### ISSUE TITLE
Gdalwarp: data lost when warping from EPSG:4326 into orthographic

### ISSUE THREAD

**Issue by jratike80** [OSGeo/gdal#9056]
Tests data: World map from https://naciscdn.org/naturalearth/50m/raster/HYP_50M_SR_W.zip
Command:
`gdalwarp -t_srs +proj=ortho -et 0 -wo source_extra=5 HYP_50M_SR_W.tif ortho.tif`

Using -et and source_extra does not change the result. The result looks good at the first sight, but there are four areas like this with  missing data.

![kuva](https://github.com/OSGeo/gdal/assets/1751612/30a3a560-31fd-4e34-95e0-b817bba42d70)

I think I have seen these mouse bites before, perhaps in some user mail but I could not find it righ now. This old ticket may be related https://github.com/OSGeo/gdal/issues/862

**EDIT**: I found it, it was in gis.stackexchange https://gis.stackexchange.com/questions/111320/reprojecting-natural-earth-raster-into-natearth-projection-with-gdalwarp-causing
and in the gdal-dev list, asked by myself https://lists.osgeo.org/pipermail/gdal-dev/2014-August/039899.html
Using `-wo SAMPLE_STEPS=1000` removed the mouse bites.

Warping back to EPSG:4326 gives more artifacts

![kuva](https://github.com/OSGeo/gdal/assets/1751612/fa63fe70-60ea-4825-872c-ba907a62df4a)

Tested with GDAL 3.9.0dev, Proj 9.3.0 on Windows.

**Comment by rouault** [comment]
Was quite challenging... Fix in https://github.com/OSGeo/gdal/pull/9061

For longlat --> ortho, the artifacts can be workarounded by adding -wo SAMPLE_STEPS=500 . PR 9061 automates that
For ortho -> longlat, the edge artifacts are quite tricky to remove. PR 9061 fixes most of them, but provided that the source raster has a nodata value set.

**Comment by jratike80** [comment]
It seems to affect also Natural Eart projection, see the mail https://lists.osgeo.org/pipermail/gdal-dev/2014-August/039899.html.

**Comment by rouault** [comment]
> It seems to affect also Natural Earth projection, see the mail https://lists.osgeo.org/pipermail/gdal-dev/2014-August/039899.html.

the fix should be generic enough to cope with Natural Earth, although I don't reproduce the "4 little corner artifact" when doing 4326 -> Natural earth on  HYP_50M_SR_W.tif, without or with PR 9061, but this is quite dependent on the raster size, projection, etc., so not easy to trigger.
There are small artifacts on the edges for the Natural earth -> 4326. PR 9061 doesn't help for that
