### ISSUE TITLE
ogr2ogr with MySQL 8 (Wrong Axis Order)

### ISSUE THREAD

**Issue by YoshiakiYamasaki** [OSGeo/gdal#906]
## Steps to reproduce the problem.

I checked following issues.

 - ogr2ogr with MySQL 8 #782
 - Issue with Mysql import #899

However, ogr2ogr has another 2 issues with MySQL 8 as follows.

 1.Wrong SRID
 2.Wrong Axis Order

I explain about "Wrong Axis Order" on this issue. I submitted another issue regarding "Wrong SRID" as #905.

[Wrong Axis Order]

I executed ogr2ogr as follows. The shape file has point data with SRID:4326.

C:\Users\yyamasak>ogr2ogr -f "MySQL" MYSQL:geotest,user=root,password=root C:\work\point_4326.shp
ERROR 4: Unable to open EPSG support file gcs.csv.  Try setting the GDAL_DATA environment variable to point to the directory containing EPSG csv files.
ERROR 1: MySQL error message:FUNCTION geotest.GeometryFromText does not exist Description: INSERT INTO `point_4326` (`SHAPE` , `gid`, `point_name`) VALUES (GeometryFromText('POINT (136.88149942349 35.1707331634177)',2) , 1, 'nagoya_station')
ERROR 1: Unable to write feature 0 from layer point_4326.
ERROR 1: Terminating translation prematurely after failed
translation of layer point_4326 (use -skipfailures to skip errors)

Above SQL has a problem described at #782, #899 and #905. Therefore, I modified SQL as follows.

  [Modified SQL]
   INSERT INTO `point_4326` (`SHAPE` , `gid`, `point_name`) VALUES (ST_GeometryFromText('POINT (136.88149942349 35.1707331634177)',4326) , 1, 'nagoya_station');

   * I changed from "GeometryFromText" to "ST_GeometryFromText".
   * I changed from "1" to "4326".

I executed above SQL with mysql Command-Line Tool. But it cause error as follows. Because Axis Order is wrong.

mysql> INSERT INTO `point_4326` (`SHAPE` , `gid`, `point_name`) VALUES (ST_GeometryFromText('POINT (136.88149942349 35.1707331634177)',4326) , 1, 'nagoya_station');
ERROR 3617 (22S03): Latitude 136.881499 is out of range in function st_geometryfromtext. It must be within [-90.000000, 90.000000].
mysql>

I modified SQL as follows.

  [Modified SQL]
   INSERT INTO `point_4326` (`SHAPE` , `gid`, `point_name`) VALUES (ST_GeometryFromText('POINT (35.1707331634177 136.88149942349)',4326) , 1, 'nagoya_station');

   * I changed Axis Order. I mean change order "136.88149942349" and "35.1707331634177".

I executed above SQL with mysql Command-Line Tool. I could execute it.

mysql> INSERT INTO `point_4326` (`SHAPE` , `gid`, `point_name`) VALUES (ST_GeometryFromText('POINT (35.1707331634177 136.88149942349)',4326) , 1, 'nagoya_station');
Query OK, 1 row affected (0.11 sec)

mysql>
mysql> SELECT OGR_FID,ST_ASText(SHAPE),gid,point_name FROM point_4326;
+---------+-----------------------------------------+------+----------------+
| OGR_FID | ST_ASText(SHAPE)                        | gid  | point_name     |
+---------+-----------------------------------------+------+----------------+
|       1 | POINT(35.1707331634177 136.88149942349) |    1 | nagoya_station |
+---------+-----------------------------------------+------+----------------+
1 row in set (0.00 sec)

## Operating system
Windows 10

## GDAL version and provenance
C:\Users\yyamasak>gdalinfo --version
GDAL 2.3.1, released 2018/06/22

**Comment by rouault** [comment]
From the above, the error comes from MySQL itself, which apparently does not honour EPSG axis order, and assumes longitude/latitude order for geographic CRS. So you have also to feed GDAL with this longitude, latitude order. This is a long standing annoyance...

**Comment by jratike80** [comment]
(ST_GeometryFromText('POINT (136.88149942349 35.1707331634177)',4326) was not accepted because of "Latitude 136.881499 is out of range in function st_geometryfromtext." 

MySQL seems to think that WKT is CRS aware. I am not sure if this is right of wrong. OpenGIS Simple Features Specification For SQL does not say anything about axis orders in "The Well-known Text representation of Geometry". As far as I know other databases (PostGIS, Oracle, SpatiaLite) use WKT always as Longitude-Latitude or Easting-Northing order.

**Comment by YoshiakiYamasaki** [comment]
Unfortunately, it is MySQL's specification now.

I submitted following bug report to bugs.mysql.com. However, it marked as "Not a Bug".
 
  WKB format has different axis order.
  https://bugs.mysql.com/bug.php?id=88869

**Comment by jratike80** [comment]
So for reaching the interoperability we should perhapt apply "axis-order=long-lat" automatically for MySQL.

> This can be overriden by the user: ST_GeomFromText('POINT(1 2)', 4326, 'axis-order=long-lat') constructs a point with latitude=2 and longitude=1.
> The same option can be used on output: ST_AsText(ST_GeomFromText('POINT(1 2)', 4326), 'axis-order=long-lat') constructs a point with latitude=1 and longitude=2

**Comment by jratike80** [comment]
By MySQL driver documentation reading seems to use WKB and should be OK but writing is done with WKT. I can see two alternatives: add  "axis-order=long-lat" to WKT operations or try if WKB would work for writing as well.

**Comment by jratike80** [comment]
I made a test also with MariaDB 10.3. It is not CRS aware with WKT.

**Comment by YoshiakiYamasaki** [comment]
MariaDB is fork product based on MySQL 5.5. However, MySQL re-created GIS feature on MySQL 5.7. I guess that's why MariaDB 10.3 is not CRS aware with WKT.
(I haven't check MariaDB 10.3 and MySQL 5.5 by myself)

**Comment by rouault** [comment]
> Comment: It might be good to check also that we do not deal with MariaDB.

Good point Jukka. Fixed

**Comment by YoshiakiYamasaki** [comment]
Thank you very much!! I'm looking forward to releasing GDAL 2.3.2.

**Comment by rouault** [comment]
you can already try the builds athttp://gisinternals.com/stable.php

**Comment by YoshiakiYamasaki** [comment]
Thank you for the information. I downloaded this(Stable Releases) and installed.
http://download.gisinternals.com/sdk/downloads/release-1900-x64-gdal-2-3-mapserver-7-2/gdal-203-1900-x64-core.msi

But it shows GDAL 2.3.1.
C:\Users\yyamasak>ogr2ogr --version
GDAL 2.3.1, released 2018/06/22

Therefore, I downloaded this(Development Version) and installed.
http://download.gisinternals.com/sdk/downloads/release-1900-x64-gdal-mapserver/gdal-203-1900-x64-core.msi

It shows GDAL 2.4. And I can't execute it. I'm checking this error now.

C:\Users\yyamasak>gdalinfo --version
GDAL 2.4.0dev, released 2018/99/99

C:\Users\yyamasak>ogr2ogr -f "MySQL" MYSQL:geotest,user=root,password=root C:\work\point_4326.shp
ERROR 4: Unable to open EPSG support file gcs.csv.  Try setting the GDAL_DATA environment variable to point to the directory containing EPSG csv files.

**Comment by jratike80** [comment]
Installation should create launch file that sets the environment right for you if you open the GDAL command shell from the program menu. Now it either fails or you do not start GDAL with the launch file. Another option is to download the non-install zip version, unzip the package and start GDAL through the "sdkshell.bat" file.

**Comment by YoshiakiYamasaki** [comment]
jratike80 >
Thank you. I'll try it later.

rouault >
I submitted comment on this commit. Could you check it?
https://github.com/OSGeo/gdal/commit/06803487d7e0d67089b5fc6e58a0dd7ecc831b23
