### ISSUE TITLE
Need to improve Windows binaries download info

### ISSUE THREAD

**Issue by atlight** [OSGeo/gdal#9065]
It makes me sad that the GDAL website doesn't (seem to) offer a link to readily usable Windows binaries. 

The only link on the official GDAL download page is to Conda Forge, which seems to only provide .conda files - useless outside of that specific ecosystem:

https://github.com/OSGeo/gdal/blob/41bbd3bf4ec78295e787020a1d722bab16a384cf/doc/source/download.rst?plain=1#L294-L299

There is much more useful info at the old Trac wiki (https://trac.osgeo.org/gdal/wiki/DownloadingGdalBinaries#Windows). That should be updated and migrated to gdal.org.

**Comment by jratike80** [comment]
I think that you could make a pull request and add OSGeo4W and gisinternals.com.

**Comment by jmckenna** [comment]
@atlight if you click on the History link on that wiki page you'll see that us packagers are still maintaining that page actively.  (MS4W just celebrated its 21st birthday, by far the old GDAL distribution for Windows ❤️
