### ISSUE TITLE
ORG memory driver only allows iteration over features once.

### ISSUE THREAD

**Issue by mohaine** [OSGeo/gdal#907]
## Expected behavior and actual behavior.
ORG memory driver only allows iteration over features once.

The following code should print:
```
Found it the first time
Found it the second time
```

but only prints:
```
Found it the first time
 ```
Code: 
```
    sr = osr.SpatialReference()
    sr.ImportFromEPSG(4326)
    ds = ogr.GetDriverByName('Memory').CreateDataSource('dnm')
    layer = ds.CreateLayer("dnm", srs=sr, geom_type=ogr.wkbPoint)
    layer_def = layer.GetLayerDefn()
    wkt = "POINT (1120351.5712494177 741921.4223245403)"
    point = ogr.CreateGeometryFromWkt(wkt)
    out_feature = ogr.Feature(layer_def)
    out_feature.SetGeometry(point)
    layer.CreateFeature(out_feature)
    for f in layer:
        print("Found it the first time")
    for f in layer:
        print("Found it the second time")
```

## Steps to reproduce the problem.

Run above code

## Operating system

For example: Ubuntu 18.04 64 bit

## GDAL version and provenance

gdal-bin/bionic 2.2.3+dfsg-2 amd64

**Comment by rouault** [comment]
You need to explicit reset the layer iterator between the two loops with layer.ResetReading(). This is not super Python idiomatic admitedly

**Comment by mohaine** [comment]
Thanks! I just noticed that in the docs.
