### ISSUE TITLE
change in GDAL_DISABLE_READDIR_ON_OPEN behavior ? 

### ISSUE THREAD

**Issue by vincentsarago** [OSGeo/gdal#909]
## Expected behavior and actual behavior.

As mentioned in https://trac.osgeo.org/gdal/wiki/ConfigOptions#GDAL_DISABLE_READDIR_ON_OPEN setting `GDAL_DISABLE_READDIR_ON_OPEN=TRUE` should decrease the number of HTTP calls but it seems the behave in the opposite way.

> Defaults to FALSE.

> By default (GDAL_DISABLE_READDIR_ON_OPEN=FALSE), GDAL establishes a list of all the files in the directory of the file passed to GDALOpen(). This can result in speed-ups in some use cases, but also to major slow downs when the directory contains thousands of other files. When set to TRUE, GDAL will not try to establish the list of files.

> If set to EMPTY_DIR, only the file that is being opened will be seen when a GDAL driver will request sibling files, so this is a way to disable loading side-car/auxiliary files.

## Steps to reproduce the problem.

```
CPL_CURL_VERBOSE=YES GDAL_DISABLE_READDIR_ON_OPEN=TRUE rio info s3://landsat-pds/L8/008/068/LC80080682015340LGN00/LC80080682015340LGN00_B3.TIF 2>&1 >/dev/null | grep "> GET" | wc -l
11

# in https://trac.osgeo.org/gdal/wiki/CloudOptimizedGeoTIFF#HowtoreaditwithGDAL 
# it says to set GDAL_DISABLE_READDIR_ON_OPEN to YES
CPL_CURL_VERBOSE=YES GDAL_DISABLE_READDIR_ON_OPEN=YES rio info s3://landsat-pds/L8/008/068/LC80080682015340LGN00/LC80080682015340LGN00_B3.TIF 2>&1 >/dev/null | grep "> GET" | wc -l
11

CPL_CURL_VERBOSE=YES GDAL_DISABLE_READDIR_ON_OPEN=FALSE rio info s3://landsat-pds/L8/008/068/LC80080682015340LGN00/LC80080682015340LGN00_B3.TIF 2>&1 >/dev/null | grep "> GET" | wc -l
3
```
## Operating system
MacOS and CENTOS 

## GDAL version and provenance
```
gdalinfo --version
GDAL 2.3.1, released 2018/06/22
```
but tried also with master

**Comment by rouault** [comment]
GDAL_DISABLE_READDIR_ON_OPEN=TRUE/YES doesn't disable side-car file probing. It prevents ReadDir() calls, but side-car files will be stat'ed() individually. You want to set GDAL_DISABLE_READDIR_ON_OPEN=EMPTY_DIR to prevent any side-car file probing

**Comment by rouault** [comment]
The hint for TRUE was valid for local filesystems. With network file systems it is not so much relevant

**Comment by vincentsarago** [comment]
I see, so `CPL_VSIL_CURL_ALLOWED_EXTENSIONS` should be used to really minimized the number of call then
