### ISSUE TITLE
check_symbol_exists not setting SQLite3_HAS_XXX by sqlite3.h in CMake

### ISSUE THREAD

**Issue by tthh7** [OSGeo/gdal#9096]
I'm using a self-compiled SQLite3 library to build GDAL. However, when using the CMake command for building, I encountered the following issue:
_-- Looking for sqlite3_open
-- Looking for sqlite3_open - not found
-- Looking for sqlite3_open
-- Looking for sqlite3_open - not found
-- Looking for sqlite3_open
-- Looking for sqlite3_open - not found
CMake Warning at cmake/helpers/CheckDependentLibraries.cmake:543 (message):
  /usr/local/third_party/lib/libsqlite3.a lacks the mutex extension! Access
  to SQLite3 databases from multiple threads will be unsafe
Call Stack (most recent call first):
  gdal.cmake:265 (include)
  CMakeLists.txt:246 (include)_

I found that the issue originated from the cmake/modules/packages/FindSQLite3.cmake file, where statements like check_cxx_symbol_exists(xxx sqlite3.h SQLite3_HAS_xxx) are used to set the value of SQLite3_HAS_xxx. Upon examining the sqlite3.h file, I noticed relevant declarations for xxx. Additionally, the compilation command for SQLite3 was as follows: CFLAGS="-O3 -DNDEBUG -DSQLITE_ENABLE_COLUMN_METADATA=1 -DSQLITE_ENABLE_RTREE=1 -DSQLITE_THREADSAFE=1" ./configure xxxx. I would like to inquire if there is a solution to this issue.

## Operating system

CentOS Linux release 7.9.2009 (Core)，cmake version 3.27.1，gcc version 13.1.0 (GCC)

## GDAL version and provenance

gdal 3.8.2 SQLite3 3.44.2

**Comment by jratike80** [comment]
A note not so much to you but to the GDAL developers.:

The GDAL bug tracker receives nowadays lots of questions about how to build GDAL. Usually they are not really bugs but it just seems to be complicated to build GDAL in all possible environments and with all possible build options. I wonder if there could be some separate forum that is dedicated for troubles with building. A resolved and closed ticket here in GitHub does not perhaps help much other users because they may not try to find an answer from the old issues.

**Comment by tthh7** [comment]
> @tthh7
> 
> * Please indicate the full CMake invokation on how you built GDAL ?
> * Please include the output of `grep -i sqlite3 CMakeCache.txt`

This is my complete CMake command：
##########################################
cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr/local/third_party \
-DBUILD_JAVA_BINDINGS=ON -DBUILD_PYTHON_BINDINGS=OFF \
-DGDAL_JAVA_INSTALL_DIR=/usr/local/third_party/lib \
-DCMAKE_BUILD_TYPE=Release \
-DGDAL_USE_JPEG=ON \
-DJPEG_INCLUDE_DIR=/usr/local/third_party/include \
-DJPEG_LIBRARY_RELEASE=/usr/local/third_party/lib/libjpeg.a \
-DGDAL_USE_JSONC=ON \
-DJSONC_INCLUDE_DIR=/usr/local/third_party/include \
-DJSONC_LIBRARY=/usr/local/third_party/lib/libjson-c.a \
-DPROJ_INCLUDE_DIR=/usr/local/third_party/include \
-DPROJ_LIBRARY_RELEASE=/usr/local/third_party/lib64/libproj.a \
-DGDAL_USE_EXPAT=ON \
-DEXPAT_USE_STATIC_LIBS=ON \
-DEXPAT_INCLUDE_DIR=/usr/local/third_party/include \
-DEXPAT_LIBRARY=/usr/local/third_party/lib/libexpat.a \
-DGDAL_USE_TIFF=ON \
-DTIFF_INCLUDE_DIR=/usr/local/third_party/include \
-DTIFF_LIBRARY_RELEASE=/usr/local/third_party/lib/libtiff.a \
-DGDAL_USE_PNG=ON \
-DPNG_LIBRARY_RELEASE=/usr/local/third_party/lib/libpng16.a \
-DPNG_PNG_INCLUDE_DIR=/usr/local/third_party/include \
-DGDAL_USE_POSTGRESQL=ON \
-DPostgreSQL_INCLUDE_DIR=/usr/local/third_party/include \
-DPostgreSQL_LIBRARY_RELEASE=/usr/local/third_party/lib/libpq.a \
-DGDAL_USE_GEOS=ON \
-DGEOS_INCLUDE_DIR=/usr/local/third_party/include \
-DGEOS_LIBRARY=/usr/local/third_party/lib/libgeos_c.a \
-DGDAL_USE_LIBXML2=ON \
-DLIBXML2_INCLUDE_DIR=/home/lbh/vcpkg/installed/x64-linux/include \
-DLIBXML2_LIBRARY=/home/lbh/vcpkg/installed/x64-linux/lib/libxml2.a \
-DGDAL_USE_SQLITE3=ON \
-DSQLite3_INCLUDE_DIR=/usr/local/third_party/include \
-DSQLite3_LIBRARY=/usr/local/third_party/lib/libsqlite3.a \
-DGDAL_USE_WEBP=ON \
-DWEBP_INCLUDE_DIR=/usr/local/third_party/include \
-DWEBP_LIBRARY=/usr/local/third_party/lib/libwebp.a \
-DGDAL_USE_SFCGAL=ON \
-DSFCGAL_INCLUDE_DIR=/usr/local/third_party/include \
-DSFCGAL_LIBRARY_RELEASE=/usr/local/third_party/lib64/libSFCGAL.a \
-DCMAKE_C_FLAGS="-O3 -fPIC" -DCMAKE_CXX_FLAGS="-O3 -fPIC"..
##################################################

grep -i sqlite3 CMakeCache.txt：
################################################
//Set ON to use SQLITE3
GDAL_USE_SQLITE3:BOOL=ON
SQLite3_INCLUDE_DIR:PATH=/usr/local/third_party/include
SQLite3_LIBRARY:FILEPATH=/usr/local/third_party/lib/libsqlite3.a
PC_SQLITE3_CFLAGS:INTERNAL=
PC_SQLITE3_CFLAGS_I:INTERNAL=
PC_SQLITE3_CFLAGS_OTHER:INTERNAL=
PC_SQLITE3_FOUND:INTERNAL=
PC_SQLITE3_INCLUDEDIR:INTERNAL=
PC_SQLITE3_LIBDIR:INTERNAL=
PC_SQLITE3_LIBS:INTERNAL=
PC_SQLITE3_LIBS_L:INTERNAL=
PC_SQLITE3_LIBS_OTHER:INTERNAL=
PC_SQLITE3_LIBS_PATHS:INTERNAL=
PC_SQLITE3_MODULE_NAME:INTERNAL=
PC_SQLITE3_PREFIX:INTERNAL=
PC_SQLITE3_STATIC_CFLAGS:INTERNAL=
PC_SQLITE3_STATIC_CFLAGS_I:INTERNAL=
PC_SQLITE3_STATIC_CFLAGS_OTHER:INTERNAL=
PC_SQLITE3_STATIC_LIBDIR:INTERNAL=
PC_SQLITE3_STATIC_LIBS:INTERNAL=
PC_SQLITE3_STATIC_LIBS_L:INTERNAL=
PC_SQLITE3_STATIC_LIBS_OTHER:INTERNAL=
PC_SQLITE3_STATIC_LIBS_PATHS:INTERNAL=
PC_SQLITE3_VERSION:INTERNAL=
PC_SQLITE3_sqlite3_INCLUDEDIR:INTERNAL=
PC_SQLITE3_sqlite3_LIBDIR:INTERNAL=
PC_SQLITE3_sqlite3_PREFIX:INTERNAL=
PC_SQLITE3_sqlite3_VERSION:INTERNAL=
//ADVANCED property for variable: SQLite3_HAS_COLUMN_METADATA
SQLite3_HAS_COLUMN_METADATA-ADVANCED:INTERNAL=1
//Have symbol sqlite3_column_table_name
SQLite3_HAS_COLUMN_METADATA:INTERNAL=
//ADVANCED property for variable: SQLite3_HAS_LOAD_EXTENSION
SQLite3_HAS_LOAD_EXTENSION-ADVANCED:INTERNAL=1
//Have symbol sqlite3_load_extension
SQLite3_HAS_LOAD_EXTENSION:INTERNAL=
//Have symbol sqlite3_mutex_alloc
SQLite3_HAS_MUTEX_ALLOC:INTERNAL=
//Test SQLite3_HAS_NON_DEPRECATED_AUTO_EXTENSION
SQLite3_HAS_NON_DEPRECATED_AUTO_EXTENSION:INTERNAL=
//Have symbol sqlite3_open
SQLite3_HAS_OPEN:INTERNAL=
//Have symbol sqlite3_progress_handler
SQLite3_HAS_PROGRESS_HANDLER:INTERNAL=
//ADVANCED property for variable: SQLite3_HAS_RTREE
SQLite3_HAS_RTREE-ADVANCED:INTERNAL=1
//Have symbol sqlite3_rtree_query_callback
SQLite3_HAS_RTREE:INTERNAL=
//ADVANCED property for variable: SQLite3_INCLUDE_DIR
SQLite3_INCLUDE_DIR-ADVANCED:INTERNAL=1
//ADVANCED property for variable: SQLite3_LIBRARY
SQLite3_LIBRARY-ADVANCED:INTERNAL=1
//Old value of option SQLite3_LIBRARY_TIMESTAMP
SQLite3_LIBRARY_TIMESTAMP_OLD_VAL:INTERNAL=2024-01-03T07:32:10
__pkg_config_checked_PC_SQLITE3:INTERNAL=1
################################################

**Comment by rouault** [comment]
@tthh7 https://github.com/OSGeo/gdal/pull/9111 fixes the issue for me. Please give it a try
