### ISSUE TITLE
SetProjection

### ISSUE THREAD

**Issue by sagido** [OSGeo/gdal#9097]
c++

OGRSpatialReference oSRS;	
oSRS.SetProjection("EPSG:6991");
char* str;
oSRS.exportToPrettyWkt(&str);	
poDstDS->SetProjection(str);

str=

PROJCS["unnamed",
    GEOGCS["WGS 84",
        DATUM["WGS_1984",
            SPHEROID["WGS 84",6378137,298.257223563]],
        PRIMEM["Greenwich",0],
        UNIT["degree",0.0174532925199433,
            AUTHORITY["EPSG","9122"]]],
    PROJECTION["EPSG:6991"],
    UNIT["metre",1,
        AUTHORITY["EPSG","9001"]],
    AXIS["Easting",EAST],
    AXIS["Northing",NORTH]]

QGis open the file, but does not deduec the projection.

**Comment by rouault** [comment]
use ``oSRS.importFromEPSG(6991)`` instead
