### ISSUE TITLE
try to get epsg

### ISSUE THREAD

**Issue by sagido** [OSGeo/gdal#9099]
auto sr = poDataset->GetSpatialRef();
epsg = sr->GetEPSGGeogCS();

PROJCS["Israeli Grid 05/12",GEOGCS["IG05/12 Intermediate CRS",DATUM["IG05_12_Intermediate_Datum",SPHEROID["GRS 1980",6378137,298.257222101,AUTHORITY["EPSG","7019"]],AUTHORITY["EPSG","1144"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","6990"]],PROJECTION["Transverse_Mercator"],PARAMETER["latitude_of_origin",31.7343936111111],PARAMETER["central_meridian",35.2045169444444],PARAMETER["scale_factor",1.0000067],PARAMETER["false_easting",219529.584],PARAMETER["false_northing",626907.39],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AXIS["Easting",EAST],AXIS["Northing",NORTH],AUTHORITY["EPSG","6991"]]

return epsg=6990 instead of 6991.

How to take the  6991 ?

**Comment by rouault** [comment]
As mentioned in the issue template, this is not a support forum. This is the last time I answer usage questions from you. Next time I'll close without answering

use sr->GetAuthorityCode(nullptr), check it for null, and take atoi() on it.
