### ISSUE TITLE
With ogr2ogr -nln schema.layer, schema is case-sensitive and layer is case-insensitive

### ISSUE THREAD

**Issue by jingsam** [OSGeo/gdal#9125]
## Expected behavior and actual behavior.

I use following command to conver a gdb file into postgresql:

```
ogr2ogr -f PostgreSQL $PG_CONNECTION "ne_50m_admin_0_countries.gdb" "ne_50m_admin_0_countries" -nln GLJX.SXJXZQHJX
```
it complains: ERROR:  schema "GLJX" does not exist

when I changed to this:

```
ogr2ogr -f PostgreSQL $PG_CONNECTION "ne_50m_admin_0_countries.gdb" "ne_50m_admin_0_countries" -nln gljx.SXJXZQHJX
```
it succed with creating a gljx.sxjxzqhjx table in postgresql.

I suppose ogr2ogr treate schema name as case-sensitive and layer name as case-insensitive. I think it would be better to be case-sensitive only if the schema name is quoted with "".

## Steps to reproduce the problem.

see above.

## Operating system

macos sonoma

## GDAL version and provenance

GDAL 3.8.3 from homebrew

**Comment by jratike80** [comment]
I would change the title a bit. The aim is not to be case-insensitive but to cast unquoted identifiers into lowercase.

So this works with PSQL against the default schema "public"

`select * from PUBLIC.test;`

but ogrinfo really returns

`ERROR 1: Couldn't fetch requested layer PUBLIC.test.`

and indeed cast to lowercase works with table names and table "test" is found by using ` public.tEst` in an ogrinfo query.

That PostgreSQL is not caseinsensitive can be verified by creating a schema and table like `CASETEST.tEst`. Only way to access that table is to query it as` "CASETEST"."tEst"`
