### ISSUE TITLE
Multiline sqlite command sometimes leads to ERROR 6: Unsupported SQL command.

### ISSUE THREAD

**Issue by quantumcode-martin** [OSGeo/gdal#9129]
When using `ogr2ogr` or `ogrinfo` with a multiline sqlite command, there are unexpected behaviors. This was not happening on previous version as far as I know, as I have some scripts failing that were running fine a few weeks/months ago.

For example, this fails:
```bash
ogrinfo "test.geojson" \
    -dialect sqlite -sql "
        SELECT
            *
        FROM test
    "
```
and gives:
```sh
INFO: Open of `test.geojson'
      using driver `GeoJSON' successful.
ERROR 6: Unsupported SQL command.
```

It seems related to `sqlite` as when I remove the `-dialect sqlite` it works fine.
It also seems related to line break as when I add a space after `SELECT` it works.

## Expected behavior and actual behavior.

I expect multiline SQL sqlite commands to work fine independently of any line break and space.

## Steps to reproduce the problem.

1. Create a sample GeoJSON file, name it `test.geojson`, for example you can have this in your GeoJSON:
```json
{
    "type": "FeatureCollection",
    "features": [
        {
            "type": "Feature",
            "geometry": {
                "type": "Point",
                "coordinates": [
                    1,
                    1
                ]
            },
            "properties": {
                "name": "Example Point",
                "prop": "Example Prop"
            }
        }
    ]
}
```
2. Try these commands:
This one fails:
```sh
ogrinfo "test.geojson" \
    -dialect sqlite -sql "
        SELECT
            *
        FROM test
    "
```
This one works (added a space after `SELECT`):
```sh
ogrinfo "test.geojson" \
    -dialect sqlite -sql "
        SELECT 
            *
        FROM test
    "
```
This one works (removed space and removed `-dialect sqlite`):
```sh
ogrinfo "test.geojson" \
    -sql "
        SELECT
            *
        FROM test
    "
```

## Operating system

macOS 13.5 (22G74)

## GDAL version and provenance

GDAL 3.8.3, released 2024/01/04 version from brew

**Comment by jratike80** [comment]
Have you checked this https://github.com/OSGeo/gdal/issues/9093? Maybe your issue is resolved already.

**Comment by quantumcode-martin** [comment]
Right, this is the same issue.
I guess we can close this one.
