### ISSUE TITLE
esrijson: geometry not recognised

### ISSUE THREAD

**Issue by AlisterH** [OSGeo/gdal#914]
[myDrawings.json.txt](https://github.com/OSGeo/gdal/files/2374629/myDrawings.json.txt)

The attached file is produced by the "Export" button in the draw/measure tool at https://waikatomaps.waikatoregion.govt.nz, which is an ESRI system of some sort.

## Expected behavior and actual behaviour.

Expected: ogr can read the file, including geometry
Actual: Ogr can read the file, recognising it as esrijson, but for some reason it doesn't recognise the geometry.

## Steps to reproduce the problem.

````
C:\Program Files\GDAL>ogrinfo "F:\Downloads\myDrawings.json"
INFO: Open of `F:\Downloads\myDrawings.json'
      using driver `ESRIJSON' successful.
1: myDrawings (None)
````

Other software does recognise the geometry e.g. I successfully converted it to geojson using https://github.com/chris48s/arcgis2geojson/
Arcgis2geojson did have this complaint, but it seems unlikely that would be the problem for ogr?
````
WARNING:root:Object converted in non-standard crs - {u'wkid': 2193, u'latestWkid': 2193}
WARNING:root:Object converted in non-standard crs - {u'wkid': 2193, u'latestWkid': 2193}
````

## Operating system

Windows 10 64 bit (also tested in Ubuntu Xenial via WSL)

## GDAL version and provenance

GDAL 2.3.1 from gisinternals (also tested in the older version that is currently packaged with QGIS)

**Comment by rouault** [comment]
This sample lacks a top level "geometryType" key that is currently needed by the OGR driver

**Comment by AlisterH** [comment]
Thanks.  For anybody else that might come here, this means there is a simple workaround.  Add the appropriate one of these lines, as per [this example](https://github.com/OSGeo/gdal/files/2377807/myDrawings_edited.json.txt):
````
"geometryType": "esriGeometryPolygon",
"geometryType": "esriGeometryPoint",
"geometryType": "esriGeometryPolyline",
````
Maybe there are other types, like esriGeometryMultipoint or esriGeometryEnvelope… I don't know.

**Comment by jratike80** [comment]
This page may not be a static documentation page but works today:
https://developers.arcgis.com/documentation/common-data-types/featureset-object.htm
It is not clearly said if geometryType is optional or not but "spatialReference" is defined in a similar way with literal usage advice:

> If a spatialReference is not specified at the featureSet level, the featureSet will assume the spatialReference of its first feature. If the spatialReference of the first feature is also not specified, the spatial reference will be UnknownCoordinateSystem.

The robust system could do the same with not specified geometryType but it would be nice to find some explicit specification about the schema used in ESRI json.

**Comment by jratike80** [comment]
Out of curiosity, what happens if geometryType=Envelope?

**Comment by rouault** [comment]
> Out of curiosity, what happens if geometryType=Envelope?

Those geometries are not handled by the driver.
