### ISSUE TITLE
gdaladdo -clean fails to remove overviews in a MRF-file

### ISSUE THREAD

**Issue by anpe00** [OSGeo/gdal#9145]
## Expected behavior and actual behavior.

I expected to be able to be able to remove the overviews from a MRF-file with the command:
`gdaladdo -clean myFile.mrf`
The command executes without any error messages; however all overviews are still there.
Info about the overviews can be showned with the command:
`gdalinfo myFile.mrf`
The same info is shown both before and after trying to remove the overviews:
> Band 1 Block=512x512 Type=UInt16, ColorInterp=Gray
>   Overviews: 8334x8334, 2778x2778, 926x926, 309x309

Using `gdaladdo -clean` with a tif-file gives a perfect result as expected.

## Steps to reproduce the problem.

gdaladdo -clean myFile.mrf

## Operating system

Edition: Windows 10 Enterprise, 64 bit,
Version: 22H2
OS-version:19045.3930

## GDAL version and provenance

Tested with GDAL version 3.8.1 stable

**Comment by jratike80** [comment]
I can't reproduce with GDAL 3.9.0dev.

```
gdalinfo wgs84.rmf
...
Band 1 Block=256x256 Type=Byte, ColorInterp=Red
  NoData Value=0
  Overviews: 5407x2687, 2704x1344, 1352x672, 676x336, 338x168, 169x84

gdaladdo -clean wgs84.rmf
gdalinfo wgs84.rmf
...
Band 1 Block=256x256 Type=Byte, ColorInterp=Red
  NoData Value=0
```

**Comment by rouault** [comment]
CC @lucianpls

**Comment by anpe00** [comment]
Just tested with 3.9.0dev and the problem remains.

```
gdalinfo --version
GDAL 3.9.0dev-527b897e63, released 2024/01/22

gdalinfo 61_3_05.mrf
Driver: MRF/Meta Raster Format
...
Band 1 Block=512x512 Type=UInt16, ColorInterp=Gray
  Overviews: 8334x8334, 2778x2778, 926x926, 309x309

gdaladdo -clean 61_3_05.mrf

gdalinfo 61_3_05.mrf
Driver: MRF/Meta Raster Format
...
Band 1 Block=512x512 Type=UInt16, ColorInterp=Gray
  Overviews: 8334x8334, 2778x2778, 926x926, 309x309

```

**Comment by jratike80** [comment]
Oh yes, I mixed two formats that I have met never before: MRF https://gdal.org/drivers/raster/marfa.html and RMF https://gdal.org/drivers/raster/rmf.html.

I can confirm the issue with MRF.
Do we support any other format that is as shy as this one: "The format itself has very poor capabilities."

**Comment by lucianpls** [comment]
MRF assumes that all existing data content is stable, all changes are always done by appending to the data file.
Operations that remove content, such as GDAL clean overviews and GDAL delete are disabled, to prevent mistakes.

There are a couple of reasons, most of them related to features not commonly found in traditional, "archival" image formats.
- MRF allows (encourages) content modifications, including spatially limited rebuilding of overviews (via mrf_insert). In this case, the overview data is mixed with base level content in some undefined order, making clean removal inefficient (similar to reordering data on a HDD).
- MRF is used for large data, in distributed, loosely coupled multiprocessing systems. Reducing operations (removing content) is a big problem in some cases. For example an MRF can be concurrently served out by a tile handler or read via GDAL clients while content is being added or modified. Removing overviews would likely break running systems.
- Multiple MRFs can share a data file while having separate indexes, possibly even being modified concurrently. What does "remove overviews" mean in this context? The individual MRFs in this case are not even aware of such use.
- There can be multiple dimensional and versioned MRFs. Delate and remove overviews is not well defined in this case, when applied to a single 2D slice or version.

There are of course simple uses where this would be possible but it's not always possible to cleanly separate those uses from more complex ones.

MRF does allow rebuilding of overviews, multiple times, done by appending the new pages to the end of the data file. If you really want to remove the overviews, making a copy of the base level to a new MRF (using gdal_translate) is cleaner and unambiguous. If it's a real big file or the re-encoding is to be avoided, the simple structure of the MRF makes it easy to copy only the needed pages, similar to what [mrf_clean.py](https://github.com/nasa-gibs/mrf/blob/master/mrf_apps/mrf_clean.py) does. This "remove overviews" operation was not requested until now, it would be easy to add "copy only base level" as an option to mrf_clean.py.

**Comment by rouault** [comment]
@lucianpls  A potential resolution is to have MRF's  IBuildOverview() implementation to emit an explicit error mesage when nOverviews == 0 and that there are existing overviews, and improve the doc of the driver with the information you provide above

**Comment by lucianpls** [comment]
@rouault
Maybe a warning instead? Errors tend to break things.

**Comment by rouault** [comment]
> Maybe a warning instead? Errors tend to break things.

Clearing overviews is an operation that normally is triggered by explicit user ask, not something done implicitly, so a CE_Failure would seem appropriate to me. But I can live with a CE_Warning as well...
