### ISSUE TITLE
gdalwarp gives inconsistant error for isea projection

### ISSUE THREAD

**Issue by morfyddjames** [OSGeo/gdal#9149]
## Expected behavior and actual behavior.
gdalwarp does not report that isea is not yet a supported projection as it does with other types e.g. imoll. <br>
The error text seems to imply there are missing parameters yet I can find no reference to the isea projection in the source code;  even in gdal-3.8.3
## Steps to reproduce the problem.

<p>$ gdalwarp  -t_srs "+proj=isea " plate-carree-4087-eqc.tif ISEA.tif
<br>
Using band 4 of source image as alpha.<br>
ERROR 1: Too many points (441 out of 441) failed to transform, unable to compute output bounds.</p>

<p>The following command for an unsupported projection gives the expected error:</p>
<p>$ gdalwarp  -t_srs "+proj=imoll  " NE1_50M_SR_W.tif ISEA.tif
<br>
ERROR 1: PROJ: proj_create: Error 1027 (Invalid value for an argument): Unknown projection<br>
ERROR 1: Translating source or target SRS failed:<br>
+proj=imoll  <br>
</p>

## Operating system

My OS is Ubuntu 22.04 64 bit

## GDAL version and provenance
My gdal is from the ubuntu jammy jellyfish repository
GDAL 3.4.1, released 2021/12/27

**Comment by morfyddjames** [comment]
Can you clarify for me please... Is ISEA not supported  by GDAL?  Are there plans to add this projection?

**Comment by jratike80** [comment]
I believe that when gdalwarp is doing the conversion it makes operations both forwards from source crs into target crs, and backwards. The backward way is doing something like "I need to fill these pixels of the outpur image, so what pixels from the input image I must take?"
The reason for the failure is that the Proj library has operation only for the forward direction as documented https://proj.org/en/9.3/operations/projections/isea.html. See "Available forms".

Test that proves that GDAL can do the forward part:

```
gdaltransform -s_srs epsg:4326 -t_srs "+proj=isea"
Enter X Y [Z [T]] values separated by space, and press Return.
20 30
796162.464794543 6578619.12735743 0

gdaltransform -t_srs epsg:4326 -s_srs "+proj=isea"
ERROR 1: PROJ: pipeline: Pipeline: A forward operation couldn't be constructed
ERROR 1: PROJ: pipeline: Pipeline: A forward operation couldn't be constructed
Enter X Y [Z [T]] values separated by space, and press Return.
796161 657819
transformation failed.

```

Same test with the Proj utility cs2cs

```
cs2cs epsg:4326 +to "+proj=isea"
20 30
1933540.29      5494224.44 0.00

cs2cs "+proj=isea" +to epsg:4326
pipeline: Pipeline: A forward operation couldn't be constructed
```

So unfortunately you must find some other library for warping rasters into ISEA.
