### ISSUE TITLE
Reading ENVI files - "Image file too small"

### ISSUE THREAD

**Issue by jbants** [OSGeo/gdal#915]
## Expected behavior and actual behavior.

I'm trying to read a ENVI created file with gdal and am running into "image file is too small" error. The error occurs when I'm running the commands inside a docker container. Running the command outside of docker (macOS 10.13.6 - gdal 2.3.1 - Installed via Brew) results in the same error.

I came across issue #705, but they are writing instead of reading.

The command will succeed with smaller ENVI files (<4 GB)
Please DM me for a test file if needed.

## Steps to reproduce the problem.

```python
Python 2.7.15 |Anaconda, Inc.| (default, May  1 2018, 23:32:55) 
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import gdal
>>> gdal.UseExceptions()
>>> ds = gdal.Open('data', gdal.GA_ReadOnly)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/conda/lib/python2.7/site-packages/osgeo/gdal.py", line 3087, in Open
    return _gdal.Open(*args)
RuntimeError: Image file is too small
```

```sh
[root@0dea8b531e65 output]# gdalinfo --version
GDAL 2.3.1, released 2018/06/22
[root@0dea8b531e65 output]# ls -l -h
total 4.7G
-rw-r--r-- 1 root root 4.7G Sep 11 19:38 data
-rw-r--r-- 1 root root 1.3K Sep 11 19:38 data.hdr
[root@0dea8b531e65 output]# gdal_translate --DEBUG ON -of GTiff data output.tif
GNM: GNMRegisterAllInternal
GNM: RegisterGNMFile
GNM: RegisterGNMdatabase
ERROR 1: Image file is too small
```

## Operating system

Docker - CentOS Linux release 7.5.1804 

## GDAL version and provenance

GDAL 2.3.1 from Conda Forge

**Comment by rouault** [comment]
Can't reproduce with a 4.9 GB file. Can you send me a link to your image at even.rouault at spatialys.com ?

**Comment by rouault** [comment]
OK I could reproduce with your dataset. What i observe is that the file is indeed smaller than its expected size. Its size is 5002310400 bytes whereas its expected size should be 12118 * 12918 * 8 * 4 =
5009290368 bytes
You can workaround the check by setting RAW_CHECK_FILE_SIZE=NO as environment variable, but at reading / translation, an error will occur towards the end of the file.

What I'm wondering is if ENVI supports such truncated files without error, probably by filling unallocated space with 0 ? In which case the driver should also support that
