### ISSUE TITLE
gdal_translate errors-out with with webp WMS tiles

### ISSUE THREAD

**Issue by jo-chemla** [OSGeo/gdal#9159]
## Expected behavior and actual behavior.

I've been using [WMS xml](https://gdal.org/drivers/raster/wms.html) definition files to download footprint of data stored on a variety of TMS servers in the past - usually jpg or png tiles assembled via the following `gdal_translate` command. 
```
gdal_translate -projwin -170 80 170 -80 -projwin_srs EPSG:4326 -outsize 4096 0 source.xml output_4096.tif
```

I've been trying to do the same on mapbox TMS tiles, which are stored as webp, and this result in the following error - I suspect this is because these are webp tiles, but am probably wild-guessing here. Note I've tried to do the request with postman or a browser, and the only required request header is `Host: api.mapbox.com`. I've therefore tried to set-it up via `set GDAL_HTTP_HEADER_FILE=C:\absolute-path\test-headers.txt`, but the result is the same. Here is a page hosting one of these tile sets: https://docs.mapbox.com/data/tilesets/reference/mapbox-terrain-dem-v1/#elevation-data

```
# error
C:\absolute-path>gdal_translate -projwin -170 80 170 -80 -projwin_srs EPSG:4326 -outsize 4096 0 source.xml output_4096.tif
Input file size is 67108864, 67108864
0ERROR 1: GDALWMS: Unable to download block 0, 1.
URL:
  HTTP status code: 401, error: (null).
Add the HTTP status code to <ZeroBlockHttpCodes> to ignore this error (see http://www.gdal.org/frmt_wms.html).
ERROR 1: IReadBlock failed at X offset 0, Y offset 1: GDALWMS: Unable to download block 0, 1.
URL:
  HTTP status code: 401, error: (null).
Add the HTTP status code to <ZeroBlockHttpCodes> to ignore this error (see http://www.gdal.org/frmt_wms.html).
```

## Steps to reproduce the problem.

Use the above gdal_translate command with the following WMS xml file. Any of the wo mapbox TMS URLs return the same error, while other jpg/png tms urls do work.

```xml
<GDAL_WMS>
   <Service name="TMS">
       <!-- <ServerUrl>https://api.mapbox.com/raster/v1/mapbox.mapbox-terrain-dem-v1/${z}/${x}/${y}.webp?sku=101UGFSzooBV0&access_token=pk.eyJ1Ijoic3ZjLW9rdGEtbWFwYm94LXN0YWZmLWFjY2VzcyIsImEiOiJjbG5sMnFlZ28wb2d5MnFtb2xnMG90OW96In0.IE8Vqs0NTzCY0WqPzV9kcw</ServerUrl> -->
       <ServerUrl>https://api.mapbox.com/v4/mapbox.satellite/${z}/${x}/${y}.webp?sku=101S0AiAdllT3&access_token=pk.eyJ1Ijoiam9uY2hlbWxhIiwiYSI6IjdXUzRocmsifQ.acEmRifqE4Bh2Xz-IY_4Bw</ServerUrl>
        <!-- <ServerUrl>https://tile.openstreetmap.org/${z}/${x}/${y}.png</ServerUrl> -->
   </Service>
   <DataWindow>
       <UpperLeftX>-20037508.34</UpperLeftX>
       <UpperLeftY>20037508.34</UpperLeftY>
       <LowerRightX>20037508.34</LowerRightX>
       <LowerRightY>-20037508.34</LowerRightY>
       <TileLevel>18</TileLevel>
       <TileCountX>1</TileCountX>
       <TileCountY>1</TileCountY>
       <YOrigin>top</YOrigin>
   </DataWindow>
   <Projection>EPSG:3857</Projection>
   <BlockSizeX>256</BlockSizeX>
   <BlockSizeY>256</BlockSizeY>
   <BandsCount>3</BandsCount>
   <ZeroBlockHttpCodes>302</ZeroBlockHttpCodes>
   <!--  -->
   <!-- <UserAgent>Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36</UserAgent>
   <Referer>https://docs.mapbox.com/</Referer>
   <Accept>image/webp,*/*</Accept> -->
   <!-- <Host>https://api.mapbox.com/</Host> -->
   <!-- set GDAL_HTTP_HEADER_FILE=C:\Users\jonathan\Downloads\test-headers.txt -->
   <!-- which contains Host: api.mapbox.com -->
   <!-- <Cache >
   <Path>C:\absolute-path\gdalwmscache</Path>
    <Depth>2</Depth>
   </Cache > -->
</GDAL_WMS>
```

## Operating system

Windows 11 x64

## GDAL version and provenance

OSGeo4W or qgis gdal builds `GDAL 3.8.2, released 2023/16/12`

**Comment by jratike80** [comment]
HTTP 401 is "Unauthorized" so I think that problem is not in the webp tiles but in the authorization. Add `--debug on` into you command and you may get more information.

**Comment by jo-chemla** [comment]
Thanks for getting back so fast. The debug output shows tile requests do miss the `access_token` portion: 
```
HTTP: Requesting [1/32] https://api.mapbox.com/v4/mapbox.satellite/4/0/1.webp?sku=101S0AiAdllT3
```
This has probably to do with escaping the `&` char in the XML WMS definition. Putting this argument first was the way to go, and so was replacing `&` with `&amp;`. Thanks a lot for your help.
