### ISSUE TITLE
Feature: FGDB_STRING_WIDTH configuration option in OpenFileGDB driver

### ISSUE THREAD

**Issue by DavidMatthews83** [OSGeo/gdal#9165]
According to https://github.com/OSGeo/gdal/blob/master/NEWS.md  - OGR 1.11.0 enabled FGDB_STRING_WIDTH configuration option for the FileGDB driver though it isn't noted here https://gdal.org/drivers/vector/filegdb.html#vector-filegdb.(are the drivers different between OGR and GDAL?) 

I'm wondering if the FGDB_STRING_WIDTH configuration option could be added to the OpenFileGDB driver in GDAL?  My use case is writing to gdb from R

**Comment by jratike80** [comment]
So two suggestions:

1) Add the missing config option into documentation https://gdal.org/drivers/vector/filegdb.html
2) Feature request for the OpenFileGDB driver about adding FGDB_STRING_WIDTH configuration option?

Is that right?

**Comment by DavidMatthews83** [comment]
@jratike80 Thanks for the response
1. Was more of a question as I wasn't sure if I was understanding correctly. But if FGDB_STRING_WIDTH option should be in the documentation. Then Yes.
2.  Yes that's correct

**Comment by rouault** [comment]
This configuration option actually exists and is called ``OPENFILEGDB_DEFAULT_STRING_WIDTH``. Documented per https://github.com/OSGeo/gdal/pull/9166

**Comment by DavidMatthews83** [comment]
@rouault Fantastic. Thank you.
