### ISSUE TITLE
CSV files with line breaks in the header - behaviour inconsistent with other CSV readers

### ISSUE THREAD

**Issue by atlight** [OSGeo/gdal#9172]
Suppose we have a CSV as follows:

```
Column one,Column two,"Column with a
line break",Column three,"Another
line break",Column four,Column five
1,2,3,4,5,6,7
4,5,6,7,8,9,10
7,8,9,10,11,12,13
```

Excel, Google Sheets and QGIS' "Delimited Text" function (with "First record has field names" checked) all successfully read this file:

![image](https://github.com/OSGeo/gdal/assets/653361/7bf630b7-ce60-452d-a83b-f0ba75faa8b9)

However, GDAL only reads the first three fields:

```
Layer name: linebreaks
Geometry: None
Feature Count: 3
Layer SRS WKT:
(unknown)
Column one: String (0.0)
Column two: String (0.0)
Column with a: String (0.0)
```
version: `GDAL 3.9.0dev-5d6bbd00de, released 2024/01/29`

(Note, when you use Excel to create a file with line breaks in cells, those line breaks are saved as LF only, even though the line breaks between records are CRLF. However, no CSV reader I tested behaved differently when I interchanged LF and CRLF in various permutations.)

**Comment by jratike80** [comment]
For me a multiline header line feels very odd. Excel really seems to rely on making difference between LF and CRLF.

<img width="145" alt="image" src="https://github.com/OSGeo/gdal/assets/1751612/c865eccb-1401-4cb6-a169-aae33b070e4d">

I would accept that GDAL does not parse such header lines.

**Comment by atlight** [comment]
> Excel really seems to rely on making difference between LF and CRLF.

But see my note:

> (Note, when you use Excel to create a file with line breaks in cells, those line breaks are saved as LF only, even though the line breaks between records are CRLF. However, no CSV reader I tested behaved differently when I interchanged LF and CRLF in various permutations.)

It is true that Excel *saves* the file like that, but it does not rely on that pattern of line endings when _opening_ a file.

**Comment by jratike80** [comment]
I am sceptical but I may be wrong.  _How_ could it make a difference between the LF that is separating the lines in the header and after the header? But anyway, user can simply avoid multiline headers or edit the CSV file before reading it with GDAL.
