### ISSUE TITLE
Fails with `No module named lib2to3` in Python 312 environment

### ISSUE THREAD

**Issue by hoodmane** [OSGeo/gdal#9173]
lib2to3 was removed in Python 3.12 so it's a bit of a pain to build gdal in Python 3.12 docker images for use with Python 3.12 packages. Since Python 2 is pretty dead now, would it be possible to check in the output of these files and not have to run this conversion at build time?

**Comment by rouault** [comment]
According to https://docs.python.org/3/library/2to3.html , it seems it will removed only in 3.13, not 3.12. That said, yes we should remove its use in GDAL

**Comment by hoodmane** [comment]
Huh. I think the problem I'm running into is that the deadsnakes ppa moved it into a separate apt package in Python 3.12.

**Comment by hoodmane** [comment]
But I actually only want to build `libgdal.so` so if I figure out how to get cmake to disable the other stuff that will probably make the problem go away for me.

**Comment by hoodmane** [comment]
Seems like `-DBUILD_PYTHON_BINDINGS=OFF` might be what I'm after.
