### ISSUE TITLE
C# bindings are missing GDALDataset functions from GDAL/OGR unification

### ISSUE THREAD

**Issue by mstefarov** [OSGeo/gdal#918]
## Expected behavior and actual behavior.

I expected the current version of C# bindings to have all the post-OGR-unification functions on GDALDataset — functions such as GetLayerCount, GetLayerByName, etc. Currently they do not. This class in the bindings only appears to have pre-2.0 functions. Without this, I am unable to get layers/features from datasets opened with GDALOpenEx.

## Steps to reproduce the problem.

1. Create a C# project and reference GDAL.NET 2.3.1
2. Use `OSGeo.GDAL.Gdal.OpenEx(...)` to open any vector dataset.
3. Realize that the returned `OSGeo.GDAL.Dataset` object provides no way to get to the layers/features in that dataset.

## GDAL version and provenance

@szekerest's [GDAL.NET 2.3.1](https://www.nuget.org/packages/GDAL.NET/2.3.1)

**Comment by h0st1le** [comment]
The C# bindings appear to be explicitly left out. Is there a reason behind this? 

https://github.com/OSGeo/gdal/blob/4c3321bfa88cf4db5524af85a053621284880953/gdal/swig/include/Dataset.i#L825-L939

**Comment by rouault** [comment]
> The C# bindings appear to be explicitly left out. Is there a reason behind this?

Nobody took up of the task. Contributions welcome

**Comment by szekerest** [comment]
I'll take a look at it. 
I'll also do some rework to support the .net stardard build soon.

**Comment by WindingWinter** [comment]
> ## Expected behavior and actual behavior.
> I expected the current version of C# bindings to have all the post-OGR-unification functions on GDALDataset — functions such as GetLayerCount, GetLayerByName, etc. Currently they do not. This class in the bindings only appears to have pre-2.0 functions. Without this, I am unable to get layers/features from datasets opened with GDALOpenEx.
> 
> ## Steps to reproduce the problem.
> 1. Create a C# project and reference GDAL.NET 2.3.1
> 2. Use `OSGeo.GDAL.Gdal.OpenEx(...)` to open any vector dataset.
> 3. Realize that the returned `OSGeo.GDAL.Dataset` object provides no way to get to the layers/features in that dataset.
> 
> ## GDAL version and provenance
> @szekerest's [GDAL.NET 2.3.1](https://www.nuget.org/packages/GDAL.NET/2.3.1)

I've the same problem here. Hopefully this can be implemented soon

**Comment by szekerest** [comment]
It is technically possible to convert between Dataset and Datasource, like:
Dataset ds1 = new Dataset(DataSource.getCPtr(ds).Handle, false, null);
Though exposing those function is the most proper way.

**Comment by WindingWinter** [comment]
> It is technically possible to convert between Dataset and Datasource, like:
> Dataset ds1 = new Dataset(DataSource.getCPtr(ds).Handle, false, null);
> Though exposing those functions is the most proper way.

@szekerest , all the `DataSource` information will be copied over properly to `Dataset` in this way?

**Comment by dawitkk** [comment]
Hi There,

This may be un-related to the topic but after I installed GDAL -Version 2.4.2 I still get 
using Gdal = OSGeo.GDAL.Gdal; missing reference problem. How do I install or add it to the project.

Thanks in advance!

**Comment by iulian0512** [comment]
still missing
