### ISSUE TITLE
gdalbuildvrt freezes at 90%... then gets killed

### ISSUE THREAD

**Issue by adriansuciu09** [OSGeo/gdal#9212]
I am trying to convert about 440GB of TIFFs in Geopackage in a docker container. For that i am making a VRT file from all found tifs in my volume folder using gdalbuild vrt. For some reason, the command goes up to 90%... then freezes and gets killed in a couple of hours without giving any ERROR message. The biggest volume of TIFFs that i converted successfully with this methode was around 150GB. Is this a problem with gdalbuildvrt or a memory problem ( in the sense that i dont have enough RAM ).
This is the Console output of the command:
![Unbenannt](https://github.com/OSGeo/gdal/assets/118290996/5e647009-81b2-478a-bc04-4123d063632e)

This is my Docker stats:
![memory](https://github.com/OSGeo/gdal/assets/118290996/9fb82085-d330-478c-af71-13767d583d23)

In the meantime i will try a workaround to only convert around 150GB of TIFFS to Geopackage and then merge all Geopackages using ogr2ogr

**Comment by rouault** [comment]
> the command goes up to 90%... then freezes and gets killed in a couple of hours without giving any ERROR message.

How many files are indexed in the VRT? This may indeed be a RAM issue at the point where the VRT driver tries to generate the XML file if there are hundreds of thousands of files or more.  The https://gdal.org/drivers/raster/gti.html driver + https://gdal.org/programs/gdaltindex.html#gdaltindex of the GDAL master branch (unreleased yet) might be what you need if insufficient RAM is indeed the issue

**Comment by adriansuciu09** [comment]
ill give it a try. I currently input 735757 files
