### ISSUE TITLE
proj_create and OGRSpatialReference 

### ISSUE THREAD

**Issue by oleg-alexandrov** [OSGeo/gdal#9218]
#### Example of problem

Given an object of type OGRSpatialReference, it is not clear how to pass it to the PROJ function proj_create(). There appear to be three exporting functions: 

 - exportToWkt
 - exportToPROJJSON
 - exportToProj4

With the first two, I get the error: Error: Object is not a coordinate operation.

The last one, exportToProj4, is apparently discouraged.

The OGRSpatialReference was created from an UTM projection.

So, which is the way that is always guaranteed to work to use a  OGRSpatialReference with proj_create()?

#### Environment Information
 - PROJ version 9.3.0
 - Operation System Information Linux

#### Installation method
 - conda

**Comment by rouault** [comment]
Moving this to GDAL. Please include a full reproducer with how you built the OGRSpatialReference object

**Comment by oleg-alexandrov** [comment]
Here is how the OGRSpatialReference object is created:

     std::string srs_string = "+proj=utm +zone=10 +units=m +datum=WGS84 +no_defs";
      
      OGRSpatialReference gdal_spatial_ref;
      if (gdal_spatial_ref.SetFromUserInput(srs_string.c_str()) != OGRERR_NONE)
        throw "error";

      char *wkt_str_tmp = NULL;
      gdal_spatial_ref.exportToWkt(&wkt_str_tmp);
      std::string geo_wkt = wkt_str_tmp;
      CPLFree(wkt_str_tmp);
  
    ProjContext proj_context  = proj_context_create();
    PJ * pj_transform = proj_create(m_pj_context, geo_wkt.c_str());

For the record, what gets exported out of OGRSpatialReference is the string geo_wkt, with value:

PROJCS["unknown",GEOGCS["unknown",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]]],PROJECTION["Transverse_Mercator"],PARAMETER["latitude_of_origin",0],PARAMETER["central_meridian",-123],PARAMETER["scale_factor",0.9996],PARAMETER["false_easting",500000],PARAMETER["false_northing",0],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AXIS["Easting",EAST],AXIS["Northing",NORTH]]

**Comment by rouault** [comment]
@oleg-alexandrov 

No problem for me with your reproducer. It runs without any error or warning with GDAL and PROJ master.
But the variable naming you use shows a problem. The WKT string you get is a CRS, not a transformation. And thus I suspect that the "Error: Object is not a coordinate operation." comes from an attempt at using it with proj_trans() or a similar method.
For that you rather need a PJ* object constructed with https://proj.org/en/9.3/development/reference/functions.html#c.proj_create_crs_to_crs or https://proj.org/en/9.3/development/reference/functions.html#c.proj_create_crs_to_crs_from_pj

**Comment by oleg-alexandrov** [comment]
This was amazingly quick. Thank you! 

Here trying to migrate away from PROJ4 strings, when proj_trans() used to work, and it seems it will require some more figuring out of proper ways of handling transforms.

Given that all the user gives is the string "+proj=utm +zone=10 +units=m +datum=WGS84 +no_defs", I guess I need to cook up two different CRS, then to create a CRS to CRS transform between them? 

I did spend quite a bit of time reading the PROJ doc, but it is not obvious how to go from the single proj string to two CRS.

**Comment by rouault** [comment]
> I guess I need to cook up two different CRS, then to create a CRS to CRS transform between them?

yes.  If your workflow already incorporates GDAL, you don't necessarily need to go into PROJ and can just use https://gdal.org/doxygen/classOGRCoordinateTransformation.html that will do that for you

**Comment by oleg-alexandrov** [comment]
This is very, very helpful. Thanks a lot.
