### ISSUE TITLE
Offer HTML offline documentation, in addition to current PDF

### ISSUE THREAD

**Issue by jidanni** [OSGeo/gdal#9228]
Just like on https://github.com/OSGeo/PROJ/issues/4051, could the GDAL
project offer, in addition to the current PDF document download,
an additional HTML file download, please?

I.e., a zip file, of documentation only, consisting of separate .html
files. Just like the https://gdal.org/ website itself. (Not just one
massive .html file too.)

This zip file should not be stuck inside a larger download, but
independent. No, there is no more offline doc package:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=960964#12

Ah, on https://docs.generic-mapping-tools.org/dev/
in the lower left corner, one can download
https://docs.generic-mapping-tools.org/dev/gmt-docs-dev.zip
which is indeed ideal: individual files, with even an search
box (in its side panel) that works offline!

**Comment by rouault** [comment]
you're basically asking for https://github.com/OSGeo/gdal-docs/ . Just download and unzip https://github.com/OSGeo/gdal-docs/archive/refs/heads/master.zip
