### ISSUE TITLE
osgeo/gdal image libproj inconsistency

### ISSUE THREAD

**Issue by hfurkanvural** [OSGeo/gdal#9232]
## Expected behavior and actual behavior.

In the gdal image, there is a build step for proj and builds `libproj.so.25` and copies it to `/usr/local/lib`. However, GDAL build requires libspatialite7 and it installs a different version of libproj into the `/lib/x86_64-linux-gnu/libproj.so.22`.
Firstly, this means there are two versions of same library in the same docker image. Secondly, this causes some inconsistency for links and header files specially when you build pyproj from source code.

## Steps to reproduce the problem.

Run a container of `ghcr.io/osgeo/gdal:ubuntu-small-3.8.3` image and check the following files  

`/usr/local/lib/libproj.so.25`
`/lib/x86_64-linux-gnu/libproj.so.22`

## Operating system

Ubuntu 22.04.3 LTS

## GDAL version and provenance

GDAL version 3.8.3 / docker image `ubuntu-small-3.8.3`

**Comment by rouault** [comment]
> Secondly, this causes some inconsistency for links and header files specially when you build pyproj from source code.

The Docker images aren't intented to be used to build upon them, as they don't use the native packaging system to build the custom PROJ and GDAL versions
