### ISSUE TITLE
Does CPLGetLastErrorMsg() actually return null if no error message?

### ISSUE THREAD

**Issue by jcphill** [OSGeo/gdal#9234]
CPLGetLastErrorMsg() appears to return an empty string when there is no error but it is hard to tell for sure if this is always the case. The docs say it returns NULL, which is unsafe if the caller doesn't check the return value before treating it as a string.

https://github.com/OSGeo/gdal/blob/d7aed6e0b03f949ba40684f868c63a08d89177b1/port/cpl_error.cpp#L882-L893

**Comment by rouault** [comment]
fixed in 8aff060e2406d97d19b87d6cd96b422a21a50600
