### ISSUE TITLE
JP2OpenJPEG: unable to write image less than 8 pixels high

### ISSUE THREAD

**Issue by craigds** [OSGeo/gdal#9236]
## Expected behavior and actual behavior.

I'm unable to write an image with less than 8 rows of pixels using GDAL and JP2OpenJPEG.

I'm no DWT/JP2 expert so I'm not sure if this is a bug in GDAL or OpenJPEG

## Steps to reproduce the problem.

```
$ gdal_translate -outsize 1658 7 -of JP2OpenJPEG in.tif out.jp2
Input file size is 1658, 4
ERROR 1: Number of resolutions is too high in comparison to the size of tiles

ERROR 1: opj_start_compress() failed
```

some observations:

* increasing height to 8 px works fine
* decreasing *width* to <8 also works fine; the issue is specific to image height < 8

## Operating system

Ubuntu 22.04 LTS, amd64

## GDAL version and provenance

* GDAL 3.6.4 (fork with a few unrelated patches)
* OpenJPEG 2.4.0-6 (from ubuntu jammy)

**Comment by jratike80** [comment]
The error message mentions resolutions so I tried to define their explicitly as documented https://gdal.org/drivers/raster/jp2openjpeg.html and it seemed to work for me.

`gdal_translate -of jp2openjpeg -outsize 2000 7 1mm.tif 1mm.jp2 -co resolutions=3`
