### ISSUE TITLE
gdaldem color-relief for definition from QGIS segfaults 

### ISSUE THREAD

**Issue by hobu** [OSGeo/gdal#925]
Using GDAL 2.2.4, when I attempt to push a color relief definition from QGIS through `gdaldem`, I get a segfault on the `INTERPOLATION` line. If I remove that, things behave as expected. 

Presumably this is due to QGIS changing their format. 

```
# QGIS Generated Color Map Export File
INTERPOLATION:DISCRETE
119,215,25,28,255,<= 119
124,232,91,58,255,119 - 124
127,249,158,89,255,124 - 127
130,254,201,128,255,127 - 130
132,255,237,170,255,130 - 132
135,237,247,201,255,132 - 135
137,199,230,219,255,135 - 137
142,157,207,228,255,137 - 142
147,100,165,205,255,142 - 147
inf,44,123,182,255,> 147
```

**Comment by rouault** [comment]
That doesn't segfault for me. I get a ```ERROR 1: Unknown color : DISCRETE```
