### ISSUE TITLE
gdal-3.8.4 incorrectly assume about libiconv on Cygwin

### ISSUE THREAD

**Issue by matzeri** [OSGeo/gdal#9268]
On Cygwin 64 bit, building from upstream source with cmake + make the build fails at 

[ 91%] Linking CXX shared library cyggdal-34.dll
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: port/CMakeFiles/cpl_iconv.dir/cpl_recode_iconv.cpp.o: in function `CPLRecodeIconv(char const*, char const*, char const*)':
/usr/src/debug/gdal-3.8.4-1/port/cpl_recode_iconv.cpp:111:(.text+0xce): undefined reference to `libiconv_open'
...

## Expected behavior and actual behavior.

Extract from CMakeCache.txt

with 3.8.3 (correct behavior)

//iconv library (potentially the C library)
Iconv_LIBRARY:FILEPATH=/usr/lib/libiconv.dll.a

while on 3.8.4 (wrong)

//iconv library (potentially the C library)
Iconv_LIBRARY:FILEPATH=/usr/lib/libc.a

**Comment by rouault** [comment]
Are you sure it is really a regression of GDAL 3.8.4 and not something else that changed since last time you did a 3.8.3 build?

Because there's no obvious iconv related change between 3.8.3 and 3.8.4: ``git diff v3.8.3..v3.8.4 | grep -i iconv`` returns nothing

**Comment by matzeri** [comment]
On 20/02/2024 22:22, Even Rouault wrote:
> Are you sure it is really a regression of GDAL 3.8.4 and not something 
> else that changed since last time you did a 3.8.3 build?
> 
> Because there's no obvious iconv related change between 3.8.3 and 3.8.4: 
> |git diff v3.8.3..v3.8.4 | grep -i iconv| returns nothing
> 
> —

just rebuilt 3.8.3 with same setup and it works fine.
So something is changed on how cmake on gdal is picking this library

**Comment by dg0yt** [comment]
This looks like reusing the cmake cache after changing from native to cygwin. Can this be reproduced in a clean build dir?

**Comment by matzeri** [comment]
On 20/02/2024 22:32, Kai Pastor wrote:
> This looks like reusing the cmake cache after changing from native to 
> cygwin. Can this be reproduced in a clean build dir?
> 

Re-run 3.8.4 and it worked fine as should be.

it was a reusing cache issue but after a cmake run stopped
as I forgot a setting.

I never saw such behaviour before; next time I will remove the 
CMakeCache.txt before running again.

Sorry for the noise
Marco
