### ISSUE TITLE
WISH: Add overview support to VRT format

### ISSUE THREAD

**Issue by StyXman** [OSGeo/gdal#9280]
## Expected behavior and actual behavior.

The VRT format supports overviews in the underlying rasters.

## Steps to reproduce the problem.

Take a GeoTIFF, add at least one layer of overviews, build a vrt file on top. When GDAL reads that vrt file, it should be aware of the overview. For simplicity, if at least one of the underlying rasters does not have the same overviews, it should not build the overview in the VRT file and it could issue a warning.

## Rationale

I render a map by regions. The map uses a hypsometric, a hillshade and a slope layers. I buils dose layers using Mapzen's DEM files, so I generate each layer for each 1x1° file then build a VRT on top. When rendering low zooms (0-8 in ZXY) I would rather use downsampled versions. If I try t build such a thing, it takes a lot of time to build such 'overviews'. But adding a few 1x1° tiles, then adding the overviews to them and rebuilding the VRT is cheap.

I understand this is a quite specific need, so if the feature request is denied, I won't get mad :) Still, I think it could have more uses, like distributing computation.

## GDAL version and provenance

GDAL 3.8.3 from Debian Unstable/Sid.

**Comment by jratike80** [comment]
Maybe I do not understand your use case, but VRT is using existing overviews by default as documented in https://gdal.org/drivers/raster/vrt.html.

> It is generally not necessary to use this mechanism [overviewlist], since downsampling pixel requests on a VRT dataset/band are able to use overviews of the sources, even when the VRT bands do not declare them.

**Comment by StyXman** [comment]
Ok, so VRT files do not explicitly expose the overviews, but GDAL is clever enough to use them if they're available. Sorry for the noise.

**Comment by rouault** [comment]
> but GDAL is clever enough to use them if they're available.

you can always add a ``<OverviewList>2 4 8 16</OverviewList>`` element to the VRT to have explicit overviews listed. That might help for some use cases, like if you gdalwarp your VRT to an output that has a lower resolution. Otherwise gdalwarp would use the full resolution and use warping resampling kernels to do the resampling, whereas if overviews are explicitly listed, it might start from a closer overview level and save computation

**Comment by StyXman** [comment]
Quoting myself:

> This is amazing! It’s unbelievably fast to build and unbelievable fast to render afterwards! Technology is amazing!

:)))

**Comment by mwindowshz** [comment]
> > but GDAL is clever enough to use them if they're available.
> 
> you can always add a `<OverviewList>2 4 8 16</OverviewList>` element to the VRT to have explicit overviews listed. That might help for some use cases, like if you gdalwarp your VRT to an output that has a lower resolution. Otherwise gdalwarp would use the full resolution and use warping resampling kernels to do the resampling, whereas if overviews are explicitly listed, it might start from a closer overview level and save computation

The issue with overviewList is that block size defaults to 128
I have source files geotiff with block 256x256 with embedded overviews with block size 256x256.
I want to build one large vrt, that will open all as one map, and still get the overviews from the files.
in my app I ask the GDAL to let me know overview count, and for each overview what is the block size
I get base block 256x256, but overview blocks ae 128x28

To create the .vrt I ran
`gdalbuildvrt -input_file_list list.txt  -co BLOCKXSIZE=256 -co BLOCKYSIZE=256 x.vrt`
and then added the 
`  <OverviewList resampling="nearest">2 4 8 16 32 64 128 256 512 1024 2048 4096 8192</OverviewList>`
at the end before:
`</VRTDataset>`

this gave me in gdalinfo for each band blocks size is 256x256 and a list of overviews
```
Band 3 Block=256x256 Type=Byte, ColorInterp=Blue
  Min=0.000 Max=212.000
  Overviews: 4573981x2736403, 2286990x1368201, 1143495x684100, 571747x342050, 285873x171025, 142936x85512, 71468x42756, 35734x21378, 17867x10689, 8933x5344, 4466x2672, 2233x1336, 1116x668
```
but in my code as I wrote, the block size of the overview is 128x128 the default of vrt and not 256

on base level:
```
auto countview = poBand->GetOverviewCount();
poBand->GetBlockSize(&nBlockXSize, &nBlockYSize);  /// here I get 256x256  
for (int nImage = 1; nImage < mapData.numOfOverviews; nImage++)
{
	GDALRasterBand* localPoBand = nullptr;

	if (nImage > 0) // first base level is not in the overviews
		localPoBand = poBand->GetOverview(nImage - 1);
        localPoBand->GetBlockSize(&nBlockXSize, &nBlockYSize);  /// here I get 128x128 and not 256
}

```

and as I wrote the orignal geotiffs, have overviews with block size 256x256

Is there a solution?
maybe can be added in future?

Thanks

**Comment by rouault** [comment]
> The issue with overviewList is that block size defaults to 128

fixed per https://github.com/OSGeo/gdal/pull/12054

**Comment by sendreams** [comment]
> Quoting myself:
> 
> > This is amazing! It’s unbelievably fast to build and unbelievable fast to render afterwards! Technology is amazing!
> 
> :)))

hi, Could you tell me how to use it? I also used VRT and created overviews for the VRT, but using the warp interface is still very slow, with the exact same performance as without using the overviews.

```xml
<OverviewList resampling="nearest">4 8 16 32</OverviewList>
```

my report question
https://github.com/OSGeo/gdal/issues/13378

**Comment by jratike80** [comment]
I have an original GeoTIFF with overviews and a VRT on top of that. The VRT if created simply as `gdalbuildvrt warp.vrt warp.tif`. The VRT does not include any additional elements about the overviews. GDAL still finds automatically the overviews of the source image through the VRT

```
gdal info warp.vrt
...
Band 1 Block=128x128 Type=Byte, ColorInterp=Red
  Overviews: 5000x5000, 2500x2500, 1250x1250, 625x625, 312x312, 156x156
Band 2 Block=128x128 Type=Byte, ColorInterp=Green
  Overviews: 5000x5000, 2500x2500, 1250x1250, 625x625, 312x312, 156x156
Band 3 Block=128x128 Type=Byte, ColorInterp=Blue
  Overviews: 5000x5000, 2500x2500, 1250x1250, 625x625, 312x312, 156x156
```

Test 1: warp so that the target resolution is not changed from the original 1 m. Overviews are not used because the full resolution output requires full resolution input. Partial debug data shown below.

```
gdalwarp warp.tif warp2.tif --debug on
....
Creating output file that is 10000P x 10000L.
GDAL: GDALDriver::Create(GTiff,warp2.tif,10000,10000,3,Byte,0000024C84EBE670)
WARP: Copying metadata from first source to destination dataset
GTiff: ScanDirectories()
GTiff: Opened 5000x5000 overview.
GTiff: Opened 2500x2500 overview.
GTiff: Opened 1250x1250 overview.
GTiff: Opened 625x625 overview.
GTiff: Opened 313x313 overview.
GTiff: Opened 157x157 overview.
Processing warp.tif [1/1] : 0GDALWARP: Defining SKIP_NOSOURCE=YES
WARP: Using translation-on-pixel-boundaries optimization
GDAL: GDAL_CACHEMAX = 1622 MB
GDAL: GDALWarpKernel()::GWKNearestNoMasksOrDstDensityOnlyByte() Src=0,0,2500x2500 Dst=0,0,2500x2500
```

Test 2: warp so that the target resolution is changed from 1 m to 2 m (the image size changed from 10000x10000 pixels into 5000x5000 pixels. GDAL can use the first overview level with 2 m pixel size (lever number 0 because the index starts from 0) because the pixel size will be doubled, and it does. Pay attention to **WARP: Selecting overview level 0 for warp.tif**  in the partial debug data shown below. The file "warp.tif" in the message is the original source file that is referenced in the VRT.

```
gdalwarp warp.tif -ts 5000 5000 warp3.tif --debug on
...
Creating output file that is 5000P x 5000L.
GDAL: GDALDriver::Create(GTiff,warp3.tif,5000,5000,3,Byte,0000014C0AACB3C0)
WARP: Copying metadata from first source to destination dataset
GTiff: ScanDirectories()
GTiff: Opened 5000x5000 overview.
GTiff: Opened 2500x2500 overview.
GTiff: Opened 1250x1250 overview.
GTiff: Opened 625x625 overview.
GTiff: Opened 313x313 overview.
GTiff: Opened 157x157 overview.
WARP: Selecting overview level 0 for warp.tif
GDAL: GDALOverviewDataset(warp.tif, this=0000014C0A5C80D0) creation.
Processing warp.tif [1/1] : 0GDALWARP: Defining SKIP_NOSOURCE=YES
GDAL: Computing area of interest: 22.5113, 0, 22.6009, 0.0902048
WARP: Using translation-on-pixel-boundaries optimization
GDAL: GDAL_CACHEMAX = 1622 MB
GDAL: GDALWarpKernel()::GWKNearestNoMasksOrDstDensityOnlyByte() Src=0,0,2500x2500 Dst=0,0,2500x2500
```

@sendreams I am yet not sure if you have understood that the overviews are only used if the output will have a pixel size that is the same or bigger than some of the overviews.
