### ISSUE TITLE
Inconsistent behavior with VSI for a GDB

### ISSUE THREAD

**Issue by ar-siddiqui** [OSGeo/gdal#9291]
## Expected behavior and actual behavior.
Using VSI for a file on the internet:

Following works:
```bash
gdalinfo /vsizip//vsicurl/https://ebfedata.s3-us-west-2.amazonaws.com/11040007_Crooked/11040007_SpatialData.zip/11040007_Cooked/11040007_Crooked.gdb
```

It gives a dataset name, which when you copy and run `gdalinfo` on it, fails.

```bash
gdalinfo OpenFileGDB:"/vsizip//vsicurl/https://ebfedata.s3-us-west-2.amazonaws.com/11040007_Crooked/11040007_SpatialData.zip/11040007_Cooked/11040007_Crooked.gdb":BLE_DEP1PCT
```

`ERROR 1: Invalid connection string
gdalinfo failed - unable to open 'OpenFileGDB:/vsizip//vsicurl/https://ebfedata.s3-us-west-2.amazonaws.com/11040007_Crooked/11040007_SpatialData.zip/11040007_Cooked/11040007_Crooked.gdb:BLE_DEP1PCT'.`

But when you quote it with `'` it works on Linux but not Windows.

```bash
gdalinfo 'OpenFileGDB:"/vsizip//vsicurl/https://ebfedata.s3-us-west-2.amazonaws.com/11040007_Crooked/11040007_SpatialData.zip/11040007_Cooked/11040007_Crooked.gdb":BLE_DEP1PCT'
```
Similarly, for VSIS3 with the right credentials, this works on Windows and not Linux

```bash
gdalinfo OpenFileGDB:/vsizip//vsis3/*****/benchmark/bfe_benchmark_data/12090301_LowerColoradoCummins/12090301_SpatialData.zip/Spatial/BLE_LowColoradoCummins.gdb:BLE_DEP0_2PCT
```

## Operating system

Checked on both Windows and Rocky Linux

## GDAL version and provenance
3.8.3

**Comment by rouault** [comment]
This is just a shell usage issue.
On Windows you likely need to do
```
gdalinfo "OpenFileGDB:\"/vsizip//vsicurl/https://ebfedata.s3-us-west-2.amazonaws.com/11040007_Crooked/11040007_SpatialData.zip/11040007_Cooked/11040007_Crooked.gdb\":BLE_DEP1PCT"
```
This also works on Windows.
The subdataset name returned is aimed at being used mainly by the GDAL API method. When using it with command line utilities, you must follow the escaping rules of the shell you use.
