### ISSUE TITLE
The minimum/maximum is not correct using gdal_translate -scale option

### ISSUE THREAD

**Issue by hzhshok** [OSGeo/gdal#9316]
## Expected behavior and actual behavior.
precondition: 
a. The minimum/maximum(-33/435) of the source file(N39E117.hgt) with int16 is retrieved using api GDALComputeRasterMinMax.
b. The minimum/maximum of Source file(N39E117.hgt.) is -11/346 showed on QGIS using the same render(epsg:4326). 
c. The target file(N39E117.hgt.tif) with UInt16 has min/max(1/468）using api GDALComputeRasterMinMax.
d. The target file(N39E117.hgt.tif) with UInt16 has min/max(STATISTICS_MINIMUM=22/STATISTICS_MAXIMUM=379).

Expected: I expected the values are translated to the values above sea level with offset = 33, so,  it should be  0/468 for the mimimum/maximum using api GDALComputeRasterMinMax if what i understanded the formula(scaledValue = sourceValue*m_dfScaleRatio + m_dfScaleOff) is correct.

## Steps to reproduce the problem.

1. gdal_translate.exe -ot Uint16  -scale -33 435 0 468 D:\xx\proj\data\dem\all\N39E117.hgt D:\xx\proj\data\dem\all\N39E117.hgt.tif
2. Getting the minimum/maximum of the target file(D:\xx\proj\data\dem\all\N39E117.hgt.tif) which is 1/468.

## Operating system
win11 x64.

## GDAL version and provenance
CONFIG_VERSION=3.8.1

Regards
[N39E117.zip](https://github.com/OSGeo/gdal/files/14401650/N39E117.zip)

**Comment by jratike80** [comment]
I saw this warning in my trial.

```
gdal_translate -ot Uint16 -scale -33 435 0 468 N39E117.hgt N39E117.tif
Input file size is 3601, 3601
Warning 1: for band 1, nodata value has been clamped to 0, the original value being out of range.
```
Pointing a nodata value that is valid as Uint16 but outside the data range, or "none", seems to fix the issue

```
gdal_translate -ot Uint16 -scale -33 435 0 468 N39E117.hgt N39E117_v2.tif -a_nodata 9999
...
Band 1 Block=3601x1 Type=UInt16, ColorInterp=Gray
  Minimum=0.000, Maximum=468.000, Mean=42.103, StdDev=20.828
  NoData Value=9999
  Metadata:
    STATISTICS_MAXIMUM=468
    STATISTICS_MEAN=42.103448924714
    STATISTICS_MINIMUM=0
    STATISTICS_STDDEV=20.828011414196
    STATISTICS_VALID_PERCENT=100
```

**Comment by hzhshok** [comment]
Thanks a lot for your contribution! 

It is my fault that i noticed that prompt and also once thought of that, but i saw the code make that initial value is zero and, so i also did not do a try on that.
Sorry for making a  noise.

Regards
