### ISSUE TITLE
ERS files with ECW connections in their headers fail to open, due to "Attempt at recursively opening ERS dataset" failure.

### ISSUE THREAD

**Issue by mlittlemore** [OSGeo/gdal#9352]
Using GDALOpen to load an ERS file.
ERSDataset opens the file then finds that the DataSetType is Translated.
This then calls another GDALOpen within the driver, attempting to open an ECW file.
When checking each driver, looking for the ECW one, it hits the ERS one again which triggers the "Attempt at recursively opening ERS dataset" error.
Then because this is an error, the entire GDALOpen process fails.

I think this would not happen if this recursion check in ERSDataset::Open would occur after the Identify check, so only check for recursion if trying to load an ERS file.

Also this is only happening because the ECW driver is after the ERS driver in the driver list. Not sure if there is a way to change this order.

**Comment by rouault** [comment]
Please attach a dataset that can be used to reproduce the issue

**Comment by mlittlemore** [comment]
[LandsatImage.zip](https://github.com/OSGeo/gdal/files/14456837/LandsatImage.zip)

**Comment by jratike80** [comment]
For some reason gdalinfo knows what to do:

```
gdalinfo landsat_rgb741_image.ers
Driver: ERS/ERMapper .ers Labelled
Files: landsat_rgb741_image.ers
       landsat_rgb741_image.ecw
Size is 2021, 2265
Coordinate System is:
ENGCRS["LOCAL - (unsupported)",
    EDATUM["Unknown engineering datum"],
    CS[Cartesian,2],
        AXIS["(E)",east,
            ORDER[1],
            LENGTHUNIT["metre",1,
                ID["EPSG",9001]]],
        AXIS["(N)",north,
            ORDER[2],
            LENGTHUNIT["metre",1,
                ID["EPSG",9001]]]]
Data axis to CRS axis mapping: 1,2
Origin = (-280.000000000000000,44245.000000000000000)
Pixel Size = (25.000000000000000,-25.000000000000000)
Corner Coordinates:
Upper Left  (    -280.000,   44245.000)
Lower Left  (    -280.000,  -12380.000)
Upper Right (   50245.000,   44245.000)
Lower Right (   50245.000,  -12380.000)
Center      (   24982.500,   15932.500)
Band 1 Block=256x256 Type=Byte, ColorInterp=Red
  Description = Red
  Overviews: 1010x1132, 505x566, 252x283
Band 2 Block=256x256 Type=Byte, ColorInterp=Green
  Description = Green
  Overviews: 1010x1132, 505x566, 252x283
Band 3 Block=256x256 Type=Byte, ColorInterp=Blue
  Description = Blue
  Overviews: 1010x1132, 505x566, 252x283
```
