### ISSUE TITLE
SpatialReference.SetFromUserInput() hangs when called with an invalid URI

### ISSUE THREAD

**Issue by Mbucari** [OSGeo/gdal#9358]
## Expected behavior and actual behavior.

`SpatialReference.SetFromUserInput()` hangs for more than 20 seconds when provided a URI with an empty scheme. e.g. `//epsg.io/103248.wkt`.

I'd expect `SetFromUserInput()` to fail much more quickly, or alternatively accept a timeout overload.

## Steps to reproduce the problem.
In a C# application:

```C#
GdalConfiguration.ConfigureGdal();

var sr = new SpatialReference("");
sr.SetFromUserInput("//epsg.io/103248.wkt");
```

## Operating system

Windows 11 23H2

## GDAL version and provenance

v3.8.1 from [GDAL.Native](https://www.nuget.org/packages/GDAL.Native) nuget package (maintained by [gisinternals](https://github.com/gisinternals/buildsystem))

**Comment by Mbucari** [comment]
It would also be nice if osr_wrap.dll exported the SetFromUserInput() [overload](https://gdal.org/doxygen/classOGRSpatialReference.html#a40d5f1ce7fbd23a6c35ab9d2473cd6e2) that accepts `papszOptions`.

**Comment by rouault** [comment]
> `//epsg.io/103248.wkt`.

Couldn't reproduce that hang on Linux, but I assume that on Windows, this is considered as a network share path, or something like that, so things "work as expected" here. The enhancement in https://github.com/OSGeo/gdal/pull/9383 should give better control to disable access to local and remote files
