### ISSUE TITLE
Unable to apply Rpc based transformation 

### ISSUE THREAD

**Issue by Hidayat722** [OSGeo/gdal#9359]
## Expected behavior and actual behavior.

I am unable to apply rpcs to geotiff, here is what i get when i use this command 

gdalwarp -rpc -co RPC_FILE=test.rpc input.tif -of GTiff sample.tif --debug on

## Here is my rpc file

LINE_OFF: 17049.459992678800 pixels
SAMP_OFF: 19449.767861788201 pixels
LAT_OFF: 24.810773487468 degrees
LONG_OFF: 56.228043913917 degrees
HEIGHT_OFF: 395.000000000000 meters
LINE_SCALE: 17605.032085178420 pixels
SAMP_SCALE: 20394.910866595219 pixels
LAT_SCALE: 0.080264089763 degrees
LONG_SCALE: 0.101377293432 degrees
HEIGHT_SCALE: 305.000000000000 meters
LINE_NUM_COEFF_1: 0.000433849750
LINE_NUM_COEFF_2: 0.006576307333
LINE_NUM_COEFF_3: -1.009701018202
LINE_NUM_COEFF_4: 0.003140761611
LINE_NUM_COEFF_5: 0.000008868010
LINE_NUM_COEFF_6: -0.000010155106
LINE_NUM_COEFF_7: -0.000008358811
LINE_NUM_COEFF_8: -0.000432172168
LINE_NUM_COEFF_9: -0.000221676436
LINE_NUM_COEFF_10: -0.000000051107
LINE_NUM_COEFF_11: 0.000000966237
LINE_NUM_COEFF_12: 0.000000009730
LINE_NUM_COEFF_13: -0.000000008481
LINE_NUM_COEFF_14: -0.000000005589
LINE_NUM_COEFF_15: -0.000000781746
LINE_NUM_COEFF_16: -0.000000234091
LINE_NUM_COEFF_17: -0.000000217874
LINE_NUM_COEFF_18: 0.000000045576
LINE_NUM_COEFF_19: -0.000000084594
LINE_NUM_COEFF_20: 0.000000000991
LINE_DEN_COEFF_1: 1.000000000000
LINE_DEN_COEFF_2: 0.000008975426
LINE_DEN_COEFF_3: 0.000214197133
LINE_DEN_COEFF_4: -0.000009682525
LINE_DEN_COEFF_5: 0.000000001043
LINE_DEN_COEFF_6: 0.000000682960
LINE_DEN_COEFF_7: -0.000000060664
LINE_DEN_COEFF_8: -0.000000355889
LINE_DEN_COEFF_9: 0.000000097768
LINE_DEN_COEFF_10: 0.000000192578
LINE_DEN_COEFF_11: 0.000000015378
LINE_DEN_COEFF_12: -0.000000000138
LINE_DEN_COEFF_13: -0.000000005585
LINE_DEN_COEFF_14: 0.000000000481
LINE_DEN_COEFF_15: 0.000000004919
LINE_DEN_COEFF_16: 0.000000012479
LINE_DEN_COEFF_17: 0.000000002208
LINE_DEN_COEFF_18: 0.000000004036
LINE_DEN_COEFF_19: -0.000000152158
LINE_DEN_COEFF_20: -0.000000000037
SAMP_NUM_COEFF_1: -0.001964487195
SAMP_NUM_COEFF_2: 1.005017675588
SAMP_NUM_COEFF_3: 0.004885027596
SAMP_NUM_COEFF_4: -0.007694957255
SAMP_NUM_COEFF_5: -0.000315330343
SAMP_NUM_COEFF_6: 0.000234061678
SAMP_NUM_COEFF_7: -0.000089553157
SAMP_NUM_COEFF_8: 0.000984855731
SAMP_NUM_COEFF_9: 0.000009103824
SAMP_NUM_COEFF_10: -0.000001189468
SAMP_NUM_COEFF_11: -0.000000152806
SAMP_NUM_COEFF_12: 0.000001041260
SAMP_NUM_COEFF_13: -0.000000605307
SAMP_NUM_COEFF_14: -0.000000035677
SAMP_NUM_COEFF_15: -0.000000613356
SAMP_NUM_COEFF_16: 0.000000014834
SAMP_NUM_COEFF_17: -0.000000019751
SAMP_NUM_COEFF_18: 0.000000224158
SAMP_NUM_COEFF_19: 0.000000010218
SAMP_NUM_COEFF_20: -0.000000000315
SAMP_DEN_COEFF_1: 1.000000000000
SAMP_DEN_COEFF_2: 0.000987886615
SAMP_DEN_COEFF_3: 0.000325775638
SAMP_DEN_COEFF_4: -0.000249922910
SAMP_DEN_COEFF_5: -0.000000000807
SAMP_DEN_COEFF_6: 0.000000094204
SAMP_DEN_COEFF_7: 0.000000141881
SAMP_DEN_COEFF_8: 0.000000653602
SAMP_DEN_COEFF_9: 0.000000561744
SAMP_DEN_COEFF_10: -0.000000139896
SAMP_DEN_COEFF_11: 0.000000004341
SAMP_DEN_COEFF_12: -0.000000001318
SAMP_DEN_COEFF_13: -0.000000000911
SAMP_DEN_COEFF_14: -0.000000000170
SAMP_DEN_COEFF_15: 0.000000005697
SAMP_DEN_COEFF_16: 0.000000003143
SAMP_DEN_COEFF_17: 0.000000000435
SAMP_DEN_COEFF_18: -0.000000007101
SAMP_DEN_COEFF_19: 0.000000000326
SAMP_DEN_COEFF_20: -0.000000000105

## Steps to reproduce the problem.

here is the output i get after running the above command 

GDALOpen(input.tif, this=0x7f854af2f6b0) succeeds as GTiff.
MDReaderPleiades: Not a Pleiades product
MDReaderPleiades: Not a Pleiades product
ERROR 1: Unable to compute a RPC based transformation between pixel/line and georeferenced coordinates for input.tif.

## output of gdalinfo

Size is 6192, 4064
Coordinate System is:
PROJCRS["WGS 84 / UTM zone 40N",
    BASEGEOGCRS["WGS 84",
        DATUM["World Geodetic System 1984",
            ELLIPSOID["WGS 84",6378137,298.257223563,
                LENGTHUNIT["metre",1]]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433]],
        ID["EPSG",4326]],
    CONVERSION["UTM zone 40N",
        METHOD["Transverse Mercator",
            ID["EPSG",9807]],
        PARAMETER["Latitude of natural origin",0,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",57,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["Scale factor at natural origin",0.9996,
            SCALEUNIT["unity",1],
            ID["EPSG",8805]],
        PARAMETER["False easting",500000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["(E)",east,
            ORDER[1],
            LENGTHUNIT["metre",1]],
        AXIS["(N)",north,
            ORDER[2],
            LENGTHUNIT["metre",1]],
    USAGE[
        SCOPE["unknown"],
        AREA["World - N hemisphere - 54°E to 60°E - by country"],
        BBOX[0,54,84,60]],
    ID["EPSG",32640]]
Data axis to CRS axis mapping: 1,2
Origin = (412238.250000000000000,2752730.750000000000000)
Pixel Size = (0.500000000000000,-0.500000000000000)
Metadata:
  AREA_OR_POINT=Area
Image Structure Metadata:
  INTERLEAVE=BAND
Corner Coordinates:
Upper Left  (  412238.250, 2752730.750) ( 56d 7'51.99"E, 24d53'13.69"N)
Lower Left  (  412238.250, 2750698.750) ( 56d 7'52.45"E, 24d52' 7.64"N)
Upper Right (  415334.250, 2752730.750) ( 56d 9'42.33"E, 24d53'14.32"N)
Lower Right (  415334.250, 2750698.750) ( 56d 9'42.77"E, 24d52' 8.27"N)
Center      (  413786.250, 2751714.750) ( 56d 8'47.38"E, 24d52'40.98"N)
Band 1 Block=6192x1 Type=UInt16, ColorInterp=Gray
## Operating system

mac M1

## GDAL version and provenance
GDAL 3.0.2

**Comment by rouault** [comment]
RPC_FILE is not a creation option of the geotiff driver: https://gdal.org/drivers/raster/gtiff.html

You'll need to rename your test.rpc file as "input_rpc.txt" (when your input file is name "input.tif")
