### ISSUE TITLE
External ovr is not generated with a GeoTIFF file

### ISSUE THREAD

**Issue by ElGerys** [OSGeo/gdal#9377]
## Expected behavior and actual behavior.

I expect to have an external ovr with the following GeoTIFF but it is not created, here the link: https://we.tl/t-vwlgUEoD9w?trk=TRN_TDL_05

Using gdaladdo as below, the following output is received (so, no external ovr):

```
GDAL: GDALOpen(dn_mb_p.tif, this=0x5604ba54f1a0) succeeds as GTiff.
GDAL: GDALClose(dn_mb_p.tif, this=0x5604ba54f1a0)
```

However, with similar GeoTIFF files the ovr is created without problems with the following output messages:

```
GDAL: GDALOpen(iha_mb_p.tif, this=0x55c74ecdb1a0) succeeds as GTiff.
GTiff: ScanDirectories()
GTiff: File open for read-only accessing, creating overviews externally.
GDAL: GDALDefaultOverviews::OverviewScan()
GDAL: GDALOpen(iha_mb_p.tif.ovr, this=0x55c74ed36ed0) succeeds as GTiff.
GTiff: ScanDirectories()
GTiff: Opened 465x367 overview.
GTiff: Opened 233x184 overview.
0GDAL: GDAL_CACHEMAX = 783 MB
...10...20...30...40...50.GDAL: Flushing dirty blocks: 0...10...20...30...40...50...60...70...80...90...100 - done.
..60...70..GDAL: Flushing dirty blocks: 0...10...20...30...40...50...60...70...80...90...100 - done.
.80...90..GDAL: Flushing dirty blocks: 0...10...20...30...40...50...60...70...80...90...100 - done.
.100 - done.
GDAL: GDALClose(iha_mb_p.tif.ovr, this=0x55c74ed36ed0)
GDAL: GDALOpen(iha_mb_p.tif.ovr, this=0x55c74ed36ed0) succeeds as GTiff.
GTiff: ScanDirectories()
GTiff: Opened 465x367 overview.
GTiff: Opened 233x184 overview.
GDAL: GDALClose(iha_mb_p.tif, this=0x55c74ecdb1a0)
GDAL: GDALClose(iha_mb_p.tif.ovr, this=0x55c74ed36ed0)
```

Not sure if this problem has been fixed with the latest GDAL versions, not possible in the meanwhile to test newer versions. 

## Steps to reproduce the problem.

`gdaladdo $tif -r lanczos -ro --debug ON`

## Operating system

Linux Mint 21.2 Victoria 64 bit

## GDAL version and provenance

ii  gdal-bin                                    3.4.1+dfsg-1build4                         amd64        Geospatial Data Abstraction Library - Utility programs
ii  gdal-data                                  3.4.1+dfsg-1build4                         all          Geospatial Data Abstraction Library - Data files
ii  libgdal-dev                                3.4.1+dfsg-1build4                         amd64        Geospatial Data Abstraction Library - Development files
ii  libgdal-grass                             3.4.1-3                                           amd64        GRASS extension for the GDAL library
ii  libgdal-perl                               3.4.1+dfsg-1build4                         amd64        Perl bindings to the Geospatial Data Abstraction Library
ii  libgdal30                                  3.4.1+dfsg-1build4                         amd64        Geospatial Data Abstraction Library

**Comment by rouault** [comment]
The dimension of the file is 202x167. When you don't specify overview factors on the command line, GDAL generates the ones until it reaches an overview size below or equal to 256x256. As your full resolution file is smaller than that, there's nothing to do. If you still want to generate overviews, you can for example add " 2" to your command line, but that's going to be useless

**Comment by ElGerys** [comment]
I suspected that this has to do with the dimension of that file, thanks for pointing that out @rouault!!
