### ISSUE TITLE
OpenFileGDB: save geometry much longer than old feature, arcmap can not open

### ISSUE THREAD

**Issue by giser-pony** [OSGeo/gdal#9388]
### What is the bug?

gdal version:3.8  driver:OpenFileGDB
arcmap:10.2
create a feature with small geometry,then update feature with large geometry,it need more space write in file,the code is in filegdbtable_write.cpp, function FileGDBTable::UpdateFeature
![ok](https://github.com/OSGeo/gdal/assets/7850306/c2109701-6ef4-4ef6-8979-872399f05f6d)
![error](https://github.com/OSGeo/gdal/assets/7850306/eab71d4f-2499-409b-8fac-a38e56950643)

### Steps to reproduce the issue

`int testWrite()
{
    CommonInit();
    const char* pszDriverName = "OpenFileGDB";
    GDALDriver* poDriver;
    CPLSetConfigOption("GDAL_FILENAME_IS_UTF8", "YES");
    poDriver = GetGDALDriverManager()->GetDriverByName(pszDriverName);
    if (poDriver == NULL)
    {
        printf("%s driver not available.\n", pszDriverName);
        exit(1);
    }
    std::string strName = "E:/data/gdb/newgdb.gdb";
    poDriver = GetGDALDriverManager()->GetDriverByName(pszDriverName);
    if (poDriver == NULL)
    {
        printf("%s driver not available.\n", pszDriverName);
        exit(1);
    }
    
    VSIStatBufL sStat;
    CPLString osFilename(strName.c_str());
    if (VSIStatExL(osFilename, &sStat, VSI_STAT_EXISTS_FLAG) != 0)
    {
        poDriver->Create(osFilename, 0, 0, 0, GDT_Unknown, nullptr);
    }

    GDALOpenInfo openInfo(strName.c_str(), GDAL_OF_VECTOR | GDAL_OF_UPDATE);
    GDALDataset* pDataSet = poDriver->Open(&openInfo, false);
    if (pDataSet)
    {
        OGRSpatialReference* pSpatial = new OGRSpatialReference();
        OGRErr err = pSpatial->importFromEPSG(4326);
        if (err != OGRERR_NONE)
        {
            return -1;
        }
        std::string strLyrName = "test";
        OGRLayer* pLyr = nullptr;
        pLyr = pDataSet->GetLayerByName(strLyrName.c_str());
        if (pLyr == nullptr)
        {
            OGRLayer* pLyr = pDataSet->CreateLayer(strLyrName.c_str(), pSpatial, wkbPolygon);
            if (pLyr)
            {
                OGRFieldDefn pAFld("a", OFTString);
                pLyr->CreateField(&pAFld);
                OGRFieldDefn pBFld("b", OFTInteger);
                pLyr->CreateField(&pBFld);
                OGRFeature pFea(pLyr->GetLayerDefn());
                err = pLyr->CreateFeature(&pFea);
                if (err == OGRERR_NONE)
                {
                    std::string strWkt = "POLYGON ((105.635267900833 10.2139355103286,105.795839785835 10.1855992953281,105.783695693692 10.1154334296126,105.629870526547 10.1383722703273,105.635267900833 10.2139355103286))";
                    OGRGeometry* pSmallGeom = nullptr;
                    OGRGeometryFactory::createFromWkt(strWkt.c_str(), pSpatial, &pSmallGeom);
                    pFea.SetGeometry(pSmallGeom);
                    pLyr->SetFeature(&pFea);
                    pLyr->SyncToDisk();
                }
            }
        }
        else
        {
            OGRFeature* pFea = pLyr->GetNextFeature();
            if (pFea)
            {
                std::string strWkt = "POLYGON ((105.583992845118 10.0668570610404,105.519224353688 10.0641583738975,105.476045359401 10.0722544353262,105.419372929401 10.0992413067552,105.386988683686 10.1356735831844,105.396434088686 10.173455203185,105.415324898686 10.2112368231857,105.436914395829 10.2436210689005,105.454455862258 10.2787040017582,105.46525061083 10.3029921860443,105.48414142083 10.3299790574734,105.521923040831 10.3515685546166,105.571848752975 10.3515685546166,105.594787593689 10.3488698674737,105.602883655118 10.3785554260456,105.621774465118 10.4136383589033,105.644713305833 10.4473719481896,105.656857397976 10.4581666967612,105.678446895119 10.4500706353325,105.695988361548 10.436577199618,105.732420637977 10.4473719481896,105.749962104406 10.4487212917611,105.767503570835 10.4608653839041,105.802586503693 10.4703107889043,105.83766943655 10.4703107889043,105.864656307979 10.4622147274756,105.882197774408 10.451419978904,105.903787271552 10.4406252303324,105.922678081552 10.4284811381893,105.940219547981 10.4244331074749,105.955062327267 10.4149877024748,105.971254450124 10.4001449231888,105.983398542267 10.379904769617,105.999590665125 10.3745073953312,106.018481475125 10.3745073953312,106.037372285125 10.367760677474,106.065708500126 10.3610139596167,106.094044715126 10.3556165853309,106.123730273698 10.3475205239022,106.142621083698 10.3394244624735,106.166909267985 10.3326777446163,106.192546795842 10.3272803703305,106.208738918699 10.3205336524732,106.231677759414 10.3070402167587,106.268110035843 10.2935467810442,106.295096907272 10.2800533453297,106.309939686558 10.2692585967581,106.328830496559 10.2611625353293,106.346371962988 10.2530664739006,106.358516055131 10.2463197560434,106.372009490845 10.2355250074718,106.393598987988 10.2247302589002,106.412489797989 10.2139355103286,106.431380607989 10.2017914181855,106.443524700132 10.1909966696139,106.448922074418 10.1815512646137,106.459716822989 10.1626604546134,106.466463540847 10.1370229267558,106.471860915132 10.1140840860412,106.477258289418 10.0965426196123,106.486703694418 10.0763024660405,106.494799755847 10.0601103431831,106.502895817276 10.0398701896114,106.510991878705 10.0250274103254,106.523135970848 10.0074859438965,106.527184001562 9.99399250818201,106.533930719419 9.97645104175315,106.540677437276 9.96160826246718,106.548773498705 9.94136810889542,106.558218903705 9.9278746731809,106.567664308706 9.90898386318059,106.577109713706 9.89144239675172,106.582507087991 9.87255158675141,106.594651180135 9.84961274603674,106.601397897992 9.82937259246497,106.606795272278 9.8118311260361,106.606795272278 9.79428965960724,106.605445928706 9.77674819317837,106.593301836563 9.76190541389241,106.579808400849 9.75246000889225,106.546074811562 9.74706263460645,106.502895817276 9.74166526032064,106.477258289418 9.74166526032064,106.442175356561 9.74166526032064,106.427332577275 9.74166526032064,106.401695049417 9.745713291035,106.362564085845 9.74706263460645,106.338275901559 9.74706263460645,106.315337060844 9.74976132174935,106.288350189415 9.74976132174935,106.261363317986 9.74976132174935,106.242472507986 9.7538093524637,106.224931041557 9.75246000889225,106.203341544414 9.75515869603515,106.185800077985 9.75920672674951,106.16286123727 9.76460410103531,106.148018457984 9.76460410103531,106.111586181555 9.77270016246402,106.08864734084 9.77270016246402,106.06975653084 9.77809753674982,106.042769659411 9.78484425460708,106.00498803941 9.79024162889288,105.980699855124 9.79698834675014,105.955062327267 9.80508440817885,105.934822173695 9.81048178246465,105.913232676552 9.81857784389336,105.89299252298 9.82532456175061,105.87410171298 9.83072193603642,105.860608277265 9.83611931032222,105.843066810836 9.84016734103658,105.825525344407 9.84691405889383,105.814730595836 9.84691405889383,105.795839785835 9.85501012032254,105.780997006549 9.85905815103689,105.764804883692 9.86310618175125,105.747263417263 9.8671542124656,105.722975232977 9.87659961746576,105.709481797263 9.87794896103721,105.679796238691 9.88199699175156,105.66090542869 9.88199699175156,105.637966587976 9.88739436603737,105.62312380869 9.89144239675172,105.610979716547 9.89414108389462,105.594787593689 9.89818911460898,105.582643501546 9.90493583246623,105.569150065832 9.91033320675204,105.561054004403 9.9197786117522,105.552957942974 9.925175986038,105.542163194403 9.93732007818106,105.538115163688 9.94811482675267,105.531368445831 9.95890957532428,105.527320415117 9.96565629318154,105.524621727974 9.97914972889605,105.521923040831 9.9858964467533,105.521923040831 10.0007392260393,105.521923040831 10.0155820053252,105.524621727974 10.0290754410397,105.531368445831 10.0479662510401,105.538115163688 10.0520142817544,105.543512537974 10.0560623124688,105.54890991226 10.0587609996117,105.557005973689 10.0614596867546,105.565102035117 10.062809030326,105.583992845118 10.0668570610404))";
                OGRGeometry* pNewGeom = nullptr;
                OGRGeometryFactory::createFromWkt(strWkt.c_str(), pSpatial, &pNewGeom);
                pFea->SetGeometry(pNewGeom);
                pLyr->SetFeature(pFea);
                pLyr->SyncToDisk();
            }
        }
    }
    return 1;
}`

### Versions and provenance

os:windows 10

**Comment by rouault** [comment]
@giser-pony I notice your code fails to explictly close the dataset. Can you add a ``delete pDataSet`` towards the end ?

**Comment by giser-pony** [comment]
@rouault Thanks for your reply,I forgot add dataset release in my code, even if I did, the result would be the same

**Comment by rouault** [comment]
@giser-pony I could confirm the issue when trying to read back the produced database with the FileGDB SDK. I've a fix in https://github.com/OSGeo/gdal/pull/9400 .  I don't have ArcMap at hand. could you please try to read the attached database with it, which is the output of your reproducer run against #9400 : [test_fixed.gdb.zip](https://github.com/OSGeo/gdal/files/14515711/test_fixed.gdb.zip)

A workaround to produce a valid gdb is to use "ogr2ogr new.gdb corrupted.gdb" (or GDALVectorTranslate() from C/C++)

**Comment by giser-pony** [comment]
@rouault I appreciate your support, arcmap read the fixed data test_fixed.gdb correctly
