### ISSUE TITLE
gdal_merge.py --help missing body

### ISSUE THREAD

**Issue by jidanni** [OSGeo/gdal#9389]
Here we see that compared to other programs, gdal_merge.py's --help is oddly short.
```

$ gdal2xyz.py    --help|wc -l
45
$ gdal_merge.py  --help|wc -l
8
```

**Comment by jratike80** [comment]
I think it is OK that the tool help command prints only the syntax and does not repeat the documentation on the web page, in this case https://gdal.org/programs/gdal_merge.html. 
Gdal2xyz.py indeed has exceptionally long internal command help.

**Comment by jidanni** [comment]
Actually as some of these .py programs do not have man pages, and the user might be offline, then the user was counting on the long help messages. Though perhaps there should be different --help-* switches for this...
