### ISSUE TITLE
GDAL OGR c++ connect  oracle spatial.

### ISSUE THREAD

**Issue by ggoralce** [OSGeo/gdal#940]
I want to ask that how to connect the ORACLE spatial by gdal using  c++.  I get gdal2.2 ,
I find  I can not  connect by gdal OCI . who can help me, thank you very much.
my c++ code  is 

GDALAllRegister();
const char* filepath_oracle ="OCI:wy/123@otitanWUYUE:1521/orcl";//OCI: USERNAME/PASSWD @SID

GDALDataset *poDS_oracle;
poDS_oracle = (GDALDataset*) GDALOpenEx(filepath_oracle,GDAL_OF_VECTOR,NULL,NULL,NULL);
if(poDS_oracle==NULL)
{
    printf("Open Oracle failed");
}

## Expected behavior and actual behavior.

For example: I expected to be able to open this raster file (with a link to
the raster file, or it as an attachment) and it returns an error message
instead.

## Steps to reproduce the problem.

For example: "gdalinfo myfile"

## Operating system

For example: Ubuntu 16.04 64 bit

## GDAL version and provenance

For example: the 2.2.3 version from ubuntugis-unstable PPA

**Comment by rouault** [comment]
Questions are not for github issues. You need to compile GDAL by yourself to use the OCI driver
