### ISSUE TITLE
ogr2ogr -clipsrc is dropping polylines when converting pdf to geojson

### ISSUE THREAD

**Issue by tiffanywei** [OSGeo/gdal#9401]
### What is the bug?

Hi, I am working on converting a [input.pdf](https://github.com/OSGeo/gdal/files/14515955/input.pdf) to geojson using a series of commands to sanitize the pdf (with mutool and ghostscript), convert it to geojson (using ogr2ogr), and finally extracting and dissolving the polyline features to further compress the geojson.
```
$ mutool clean -gggg input.pdf clean.pdf
$ gs -o no-tech-no-images.pdf -sDEVICE=pdfwrite -dFILTERTEXT -dFILTERIMAGE clean.pdf
$ ogr2ogr --config OGR_PDF_READ_NON_STRUCTURED YES --config GDAL_PDF_DPI 200 \
    -oo RENDERING_OPTIONS=VECTOR \
    -lco COORDINATE_PRECISION=3 \
    -clipsrc 71.528 140.778 3388.111 2103.417 \
    big.geojson no-text-no-images.pdf
$ mapshaper big.geojson no-topology \
    -target type=polyline -dissolve \
    -target type=polyline -affine shift=-0.0,-0.0 \
    -target type=polyline -o precision=0.001 final.json
```
On my local machine running MacOS 14.3.1, the procedure outputs a complete geojson copy of the pdf polylines, which we render on the web with Leaflet.

However, when the commands are run in our elixir web server (docker container on an aws EC2 instance running Debian 11), the resultant geojson is missing a lot of polylines. I isolated the problem to the `-clipsrc` flag in the `ogr2ogr` command. The flag is necessary though for our purposes due to some input pdfs turning into a ~1GB geojson without the flag. The issue also only seems to happen in our docker container running Debian 11 with the gdal, GEOS, poppler, and ghostscript library versions being the same as the versions in my local machine (which does not have an issue with the `-clipsrc` flag).

I saw a [similar issue](https://github.com/OSGeo/gdal/issues/7641), and tried running the docker container with as similar as possible versions used by the reporter (gdal 3.7.0, GEOS 3.9.5) , but my issue wasn't fixed.

Thanks!

Tiffany

### Steps to reproduce the issue

In Debian 11, the output of the following command is missing many polylines when converting t[no-text-no-images.pdf](https://github.com/OSGeo/gdal/files/14516106/no-text-no-images.pdf).
```
ogr2ogr --config OGR_PDF_READ_NON_STRUCTURED YES --config GDAL_PDF_DPI 200 \
      -oo RENDERING_OPTIONS=VECTOR \
      -lco COORDINATE_PRECISION=3 \
      -clipsrc 71.528 140.778 3388.111 2103.417 \
      output-clipped.geojson no-text-no-images.pdf
```
compared to
```
ogr2ogr --config OGR_PDF_READ_NON_STRUCTURED YES --config GDAL_PDF_DPI 200 \
      -oo RENDERING_OPTIONS=VECTOR \
      -lco COORDINATE_PRECISION=3 \
      output.geojson no-text-no-images.pdf
```
and also compared to running the first command in MacOS.

### Versions and provenance

Debian 11 (bullseye)
Gdal 3.8.4
Poppler 24.01.0
Ghostscript 10.02.1
GEOS 3.12.1

**Comment by rouault** [comment]
@tiffanywei Could you attach (or provide a download link) to the output files in the "working" and "not working" cases ?
It is weird that you get different results when using the same library version between your local machine and a Docker container.
Did you also try with the Docker images at https://github.com/OSGeo/gdal/tree/master/docker#images-of-releases ?

**Comment by tiffanywei** [comment]
Sure! I changed the extensions from .geojson to .json to make the file attacher happy.
Not working case: 
[missing-lines.json](https://github.com/OSGeo/gdal/files/14516481/missing-lines.json)

Working case:
[output-clipped.json](https://github.com/OSGeo/gdal/files/14516486/output-clipped.json)

I built ghostscript, poppler, GEOS, and gdal from source in my Dockerfile from a debian:11.3-slim base image (since our elixir image also runs off a debian image), but I can certainly try again with the official docker images.

**Comment by tiffanywei** [comment]
Would it help if I provided a simple dockerfile so you can run the commands in container with debian 11? Hopefully this can help you reproduce the issue.

**Comment by rouault** [comment]
> Would it help if I provided a simple dockerfile so you can run the commands in container with debian 11?

yes, definitely

**Comment by tiffanywei** [comment]
Here's a [Dockerfile](https://drive.google.com/file/d/1eh_kEHZArJGs9DeHxDIKGLcdFsP5swqQ/view?usp=sharing) you can build and run.
```
docker build -t <directory name with dockerfile> .
docker run -d 39332252e0aa tail -d /dev/null
docker exec -it <container-id> /bin/bash
```

**Comment by rouault** [comment]
> Here's a [Dockerfile](https://drive.google.com/file/d/1eh_kEHZArJGs9DeHxDIKGLcdFsP5swqQ/view?usp=sharing) you can build and run.

I don't confirm the issue when using your Dockerfile. I get files of comparable size and identical number of features when using the Docker image or my local build.

**Comment by rouault** [comment]
Note that I tested only the ogr2ogr step, using the same input PDF file you provided

**Comment by tiffanywei** [comment]
Hm, not sure why it's not reproducing that issue for you, but we ended up fixing it by using ubuntu:22.04 as a base image instead of debian:11. Thank you for looking into it!
