### ISSUE TITLE
gdal_translate -expand rgba produces wrong colors (but pct2rgb.py  -rgba produces correct colors

### ISSUE THREAD

**Issue by hemantbist** [OSGeo/gdal#9402]
### What is the bug?

gdal_translate -expand rgba  a.tif /tmp/gdal.tif  # This produces a tif file with _incorrect_ colors.pct2rgb.py -rgba a.tif  gdal_good.tif # This produces the tif file with correct colors.

I have tried it on 3.4.3 and on some earlier version. The  behavior is same.

[a.tif.gz](https://github.com/OSGeo/gdal/files/14516213/a.tif.gz)

### Steps to reproduce the issue

The a.tif is attached with bug.
gdal_translate -expand rgba  a.tif  gdalbad.tif  # This produces a tif file with _incorrect_ colors.
pct2rgb.py -rgba a.tif  gdalgood.tif # This produces the tif file with correct colors.

view it in a viewer e.g. qgis. The gdalgood.tif produces correct colors. [Mostly Blue with transparency]. This is same as a.tif
gdaltif productrs bad colors.

### Versions and provenance

ubuntu 20.04
gdal_translate --version
GDAL 3.4.3, released 2022/04/22

**Comment by rouault** [comment]
fix in https://github.com/OSGeo/gdal/pull/9403. Easy workaround: add ``-ot Byte``

**Comment by hemantbist** [comment]
Thanks, The workaround works! Will mark it as closed.
