### ISSUE TITLE
Should bomb out when given multiple -sql arguments, instead of randomly executing one 

### ISSUE THREAD

**Issue by jidanni** [OSGeo/gdal#9415]
### What is the bug?

As per #9394, the programs should bomb out when given multiple -sql arguments, instead of the current behavior of simply "randomly" executing one of them as if that was the only one given.

Stopping it is a better idea than attempting to document this aberrant behavior.

**Comment by jidanni** [comment]
All I know is -sql statement1 -sql statement2 is equivalent to -sql 'statement1; statement2;' and that causes an error to be raised.

**Comment by rouault** [comment]
Wondering if we shouldn't investigate on using a "standard" argument parser that would provide all the convenient logic, such as erroring out if provided multiple arguments when this is not expected. https://github.com/p-ranav/argparse could be a candidate to investigate

**Comment by jidanni** [comment]
> What error do you see with `-sql 'statement1; statement2;'`? I do not see any

```
$ ogr2ogr o.csv x.csv -sql 'SELECT 1 FROM x; SELECT 2 FROM x;'
ERROR 1: SQL Expression Parsing Error: syntax error, unexpected $undefined, expecting end of string. Occurred around :
SELECT 1 FROM x; SELECT 2 FROM x;
               ^
```

**Comment by jratike80** [comment]
Ok, that seems to happen with the OGRSQL dialect.

**Comment by mdsumner** [comment]
indeed the multiple instances of arguments has bitten me a few times

**Comment by rouault** [comment]
Check of single -sql instance is now effective in ogrinfo, ogr2ogr and gdal_grid which have been converted to the argparse framework. Still remaining gdal_rasterize

**Comment by rouault** [comment]
> gdal_rasterize

done
