### ISSUE TITLE
gdalwarp not respecting `-wo NUM_THREADS=ALL_CPUS` when using single vrt file

### ISSUE THREAD

**Issue by punit-kulal** [OSGeo/gdal#9416]
### What is the bug?

gdalwarp shows 
`GDAL: GDALWarpKernel()::GWKRealCase() Src=5061,48,515x142 Dst=5120,0,512x128
WARP: Using 1 threads` when the input to the warp is a single VRT file. 
The expectation is it will use muiltiple threads. It works as expected(uses more than 1 thread) when there are multiple vrt files supplied as input.
`GDAL: GDALWarpKernel()::GWKRealCase() Src=971,703,981x690 Dst=1047,598,1047x598
WARP: Using 7 threads
`
logs when more than 1 vrt is supplied

The input command is as follows
`gdalwarp --debug on --config GDAL_CACHEMAX 500 -multi -t_srs EPSG:4326 -of COG -overwrite -te min_x min_y max_x max_y -r lanczos -wm 5000 -srcnodata 0 -dstnodata 0 -wo NUM_THREADS=10 -co NUM_THREADS=10 path_to_vrt output.tiff`

### Steps to reproduce the issue

1. Create VRT by using `gdal.BuildVRT(
            vrt_path,
            files,
            separate=True,
            callback=gdal.TermProgress_nocb,
            resolution="highest"
        ):` where files are single band tiff files of the same sentinel tile.
2. `gdalwarp --debug on --config GDAL_CACHEMAX 500 -multi -t_srs EPSG:4326 -of COG -overwrite -te min_x min_y max_x max_y -r lanczos -wm 5000 -srcnodata 0 -dstnodata 0 -wo NUM_THREADS=10 -co NUM_THREADS=10 path_to_vrt output.tiff`

### Versions and provenance

Ubuntu 22.04 with gdal 3.7.3

### Additional context

- Due to the lack of usage of multiple threads during VRT input, the gdalwarp execution is slower for single vrt input case than cases where multiple vrt is supplied as input.

**Comment by jratike80** [comment]
I have been thinking that "virtual" in the name of VRT means that for GDAL processes the VRT is a single source.

**Comment by rouault** [comment]
The warper may utilize up to the number of theads you specify but it has logic to avoid spininng threads for too small tasks which would be detrimental for performance.
Here the 512x128 shape of the destination chunk is 65536 which is equal to the value of the WARP_THREAD_CHUNK_SIZE configuration option that is the minimum size of a chunk to justify creating a thread. You may try to set WARP_THREAD_CHUNK_SIZE to a lower size (with ``--config WARP_THREAD_CHUNK_SIZE <number_of_pixels>``), but I don't believe that will do anything good.

Also please past the output of ``gdalinfo path_to_vrt``

**Comment by punit-kulal** [comment]
```
Driver: VRT/Virtual Raster
Size is 7350, 4860
Coordinate System is:
PROJCRS["WGS 84 / UTM zone 43N",
    BASEGEOGCRS["WGS 84",
        DATUM["World Geodetic System 1984",
            ELLIPSOID["WGS 84",6378137,298.257223563,
                LENGTHUNIT["metre",1]]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433]],
        ID["EPSG",4326]],
    CONVERSION["UTM zone 43N",
        METHOD["Transverse Mercator",
            ID["EPSG",9807]],
        PARAMETER["Latitude of natural origin",0,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",75,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["Scale factor at natural origin",0.9996,
            SCALEUNIT["unity",1],
            ID["EPSG",8805]],
        PARAMETER["False easting",500000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["easting",east,
            ORDER[1],
            LENGTHUNIT["metre",1]],
        AXIS["northing",north,
            ORDER[2],
            LENGTHUNIT["metre",1]],
    ID["EPSG",32643]]
Data axis to CRS axis mapping: 1,2
Origin = (736260.000000000000000,1466580.000000000000000)
Pixel Size = (10.000000000000000,-10.000000000000000)
Corner Coordinates:
Upper Left  (  736260.000, 1466580.000) ( 77d10'49.73"E, 13d15'24.94"N)
Lower Left  (  736260.000, 1417980.000) ( 77d10'35.89"E, 12d49' 3.98"N)
Upper Right (  809760.000, 1466580.000) ( 77d51'29.87"E, 13d15' 0.83"N)
Lower Right (  809760.000, 1417980.000) ( 77d51'11.75"E, 12d48'40.69"N)
Center      (  773010.000, 1442280.000) ( 77d31' 1.90"E, 13d 2' 3.41"N)
Band 1 Block=128x128 Type=UInt16, ColorInterp=Undefined
  NoData Value=0
Band 2 Block=128x128 Type=UInt16, ColorInterp=Undefined
  NoData Value=0
Band 3 Block=128x128 Type=UInt16, ColorInterp=Undefined
  NoData Value=0
Band 4 Block=128x128 Type=UInt16, ColorInterp=Undefined
  NoData Value=0
Band 5 Block=128x128 Type=UInt16, ColorInterp=Undefined
  NoData Value=0
Band 6 Block=128x128 Type=UInt16, ColorInterp=Undefined
  NoData Value=0
Band 7 Block=128x128 Type=UInt16, ColorInterp=Undefined
  NoData Value=0
Band 8 Block=128x128 Type=UInt16, ColorInterp=Undefined
  NoData Value=0
Band 9 Block=128x128 Type=UInt16, ColorInterp=Undefined
  NoData Value=0
Band 10 Block=128x128 Type=UInt16, ColorInterp=Undefined
  NoData Value=0
Band 11 Block=128x128 Type=UInt16, ColorInterp=Undefined
  NoData Value=0
Band 12 Block=128x128 Type=UInt16, ColorInterp=Undefined
  NoData Value=0
Band 13 Block=128x128 Type=Byte, ColorInterp=Undefined
  NoData Value=0

**Comment by punit-kulal** [comment]
But won't this workaround take longer to execute since we are now creating a temp Gtiff and then converting it to COG?

**Comment by rouault** [comment]
> But won't this workaround take longer to execute since we are now creating a temp Gtiff and then converting it to COG?

you can easily try, but normally this should be faster

**Comment by punit-kulal** [comment]
Worked like a charm. Earlier it was taking 90s, came down to 20s and debug logs show much bigger chunks and multiple threads being used. Thanks @rouault
