### ISSUE TITLE
ogr2ogr doesn't honour -clipsrc when exporting to .xlsx

### ISSUE THREAD

**Issue by faibistes** [OSGeo/gdal#943]
## Expected behavior and actual behavior.

Exporting to .xlsx fornat doesn't honour the -clipsrc option, it tries to export the whole extent. All other formats work OK, AFAIK.

## Steps to reproduce the problem.

`ogr2ogr -s_srs EPSG:3857 -t_srs EPSG:3857 -preserve_fid -spat -408242.92826308 4931269.266897501 -407620.68307978 4931759.538774099 -clipsrc "POLYGON((-407930.01417858 4931638.314424495,-407897.170143 4931440.055882399,-407794.45788624993 4931649.6605458995,-407930.01417858 4931638.314424495))" -limit 20000 -select "_FIELD_LIST_" -f "XLSX" "_FILE_NAME_" "PG:dbname='_DB_' host=_HOST_ port=5433 user='_USER_' password='_PASS_'" "_SCHEMA_"."_LAYER_" -progress`

## Operating system

Windows 64 bit

## GDAL version and provenance

2.2.4 from the OSGeo4W installer

**Comment by jratike80** [comment]
Could you please modify your command to use some data that also others can acquire easily? I suggest https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/110m/cultural/ne_110m_admin_0_countries.zip.
