### ISSUE TITLE
Shapefile: error out on valid .sbn file

### ISSUE THREAD

**Issue by pathmapper** [OSGeo/gdal#9430]
### Feature description

Here's a [dataset](https://files.worldwildlife.org/wwfcmsprod/files/Publication/file/65sv5l285i_GLWD_level2.zip) (Shapefile with spatial index .sbn / .sbx) for which `ogrinfo` with spatial filter returns:

```
ERROR 1: Inconsistent shape count for bin
SHAPE: Used spatial index, got 0 matches.
Feature Count: 13
```

Looks like [shapelib](https://github.com/OSGeo/shapelib) detects an error regarding the spatial index and in consequence the spatial index is not used but the matching features could still be found (the _normal_ way without spatial index).

Suggestion is here to improve the `ogrinfo` output to make it more clear what's going on.

```
ogrinfo -ro -so -spat 5 5 6 6 glwd_2.shp --debug on
Shape: DBF Codepage = LDID/87 for glwd_2.shp
Shape: Treating as encoding 'ISO-8859-1'.
GDAL: GDALOpen(glwd_2.shp, this=0x55765f5e0090) succeeds as ESRI Shapefile.
INFO: Open of `glwd_2.shp'
      using driver `ESRI Shapefile' successful.
OGR: GetLayerCount() = 1


Layer name: glwd_2
Metadata:
  DBF_DATE_LAST_UPDATE=2003-05-20
Geometry: Polygon
ERROR 1: Inconsistent shape count for bin
SHAPE: Used spatial index, got 0 matches.
Feature Count: 13
Extent: (-180.000000, -55.587208) - (180.000000, 83.575951)
Layer SRS WKT:
(unknown)
GLWD_ID: Integer64 (10.0)
TYPE: String (12.0)
POLY_SRC: String (12.0)
AREA_SKM: Real (12.1)
PERIM_KM: Real (12.1)
LONG_DEG: Real (10.2)
LAT_DEG: Real (10.2)
GDAL: GDALClose(glwd_2.shp, this=0x55765f5e0090)
```

### Additional context

It's kind of surprising that for this well established dataset such an error is detected -> https://github.com/OSGeo/shapelib/issues/106

**Comment by rouault** [comment]
> It's kind of surprising that for this well established dataset such an error is detected

That was actually a fundamental algorithmic bug that has existed forever based on a wrong assumption about the ordering of some elements in the .sbn. I guess most .sbn in the wild met our wrong assumption, but for larger datasets like the one of this ticket, it could be defeated

**Comment by pathmapper** [comment]
Thank you @rouault, this thing really tested my patience. You can't imagine how happy I am with the outcome.

**Comment by pathmapper** [comment]
fixed by @rouault in https://github.com/OSGeo/gdal/pull/9439
