### ISSUE TITLE
gdal_viewshed: Attempt to create 5x-1 dataset

### ISSUE THREAD

**Issue by jidanni** [OSGeo/gdal#9432]
### What is the bug?

User simply follows example on man page, and is accused of trying to create negative sized datasets.

### Steps to reproduce the issue

```
$ gdal_viewshed -md 15 -ox 236850 -oy 2675610 m.tif xdg.tif
0...10...20...30...40...50...60...70...80...90...100 - done.
$ gdal_viewshed -md 20 -ox 236850 -oy 2675610 m.tif xdg.tif
0ERROR 1: Attempt to create 3x-1 dataset is illegal,sizes must be larger than zero.
ERROR 1: Cannot create dataset for xdg.tif
$ gdal_viewshed -md 33 -ox 236850 -oy 2675610 m.tif xdg.tif
0ERROR 1: Attempt to create 5x-1 dataset is illegal,sizes must be larger than zero.
ERROR 1: Cannot create dataset for xdg.tif

```

### Versions and provenance

Fresh Debian sid gdal.
[m.tif.gz](https://github.com/OSGeo/gdal/files/14546646/m.tif.gz)

### Additional context

Hmm, a mysterious wish for a negative sized dataset?

The user is simply following the (-md 500) example in the gdal_viewshed man page.

Perhaps the user does not understand the -md units.

Looking at the man page, these all mention units,
```
       -ox <value>
              The X position of the observer (in SRS units).

       -oy <value>
              The Y position of the observer (in SRS units).

       -oz <value>
              The height of the observer above the DEM surface in  the  height
              unit of the DEM. Default: 2

       -tz <value>
              The  height  of  the  target above the DEM surface in the height
              unit of the DEM. Default: 0
```
but not this
```
       -md <value>
              Maximum distance from observer to compute visibiliy.  It is also
              used to clamp the extent of the output raster.
```
So it should mention the units...

I conclude that I did not in fact request a negative sized output, and it must be a bug in the program. But I'll append the input .tif here so people can check. Had to zip it.

**Comment by jratike80** [comment]
You may have found a bug. Values 15 and 33 do not probably make sense for visibility analysis when the pixel size of the dem is 20 m. The working command creates a raster that is 1x3 pixels. But I get the negative extent error also with reasonable `-md` values, unless I give a negative value in the command.

```
gdal_viewshed -md 1000 -ox 236850 -oy 2675610 m.tif xdg.tif
0ERROR 1: Attempt to create 101x-99 dataset is illegal,sizes must be larger than zero.
ERROR 1: Cannot create dataset for xdg.tif

gdaltest>gdal_viewshed -md -1000 -ox 236850 -oy 2675610 m.tif xdg.tif
0...10...20...30...40...50...60...70...80...90...100 - done.
```

**Comment by jratike80** [comment]
@jidanni, your DEM file is a South-up image with pixel size (20 20). The pixel size would be (20 -20) for the North-up image. So the issue is that gdal_viewshed does not deny to handle that non-North-up source.

I believe that South-up images and rotated images make troubles for some other utilities as well, and that all of them do not handle the situation properly.

```
gdalwarp m.tif mm.tif
gdal_viewshed -md 20 -ox 236850 -oy 2675610 mm.tif xdg.tif
0...10...20...30...40...50...60...70...80...90...100 - done.
```
