### ISSUE TITLE
OpenFileGDB: After deleteLayer,  GetLayerByName() result is not null

### ISSUE THREAD

**Issue by giser-pony** [OSGeo/gdal#9447]
### What is the bug?

gdb file and layer must be already exist, then use GDALDataset deleteLayer, use index GetLayer would be null, but GetLayerByName create the layer again.
OGROpenFileGDBDataSource have members `m_osMapNameToIdx ` and `m_papszFiles` , dose the layer name should be removed?

### Steps to reproduce the issue

` 
int testDelLayer()
{
    CommonInit();
    const char* pszDriverName = "OpenFileGDB";
    GDALDriver* poDriver;
    poDriver = GetGDALDriverManager()->GetDriverByName(pszDriverName);
    if (poDriver == NULL)
    {
        printf("%s driver not available.\n", pszDriverName);
        exit(1);
    }

    std::string strGdbName = "E:/data/gdb/t.gdb";//gdb and the test layer must be already exist
    std::string strLyrName = "test";
    GDALOpenInfo openInfo(strGdbName.c_str(), 1);
    GDALDataset* pDataSet = poDriver->pfnOpen(&openInfo);
    if (pDataSet)
    {
        OGRLayer* pLyr = pDataSet->GetLayer(0);
        pLyr = pDataSet->GetLayerByName(strLyrName.c_str());
        OGRErr oErr = pDataSet->DeleteLayer(0);
        pLyr = pDataSet->GetLayer(0);
        if (pLyr == nullptr)
        {
            std::cout << "Delete layer is not exist" << std::endl;
        }
        pLyr = pDataSet->GetLayerByName(strLyrName.c_str());
        if (pLyr)
        {
            std::cout << "Delete layer is exist" << std::endl;
        }
    }
    return 1;}`

### Versions and provenance

gdal:3.8
os:windows 10
driver:openfilegdb

**Comment by rouault** [comment]
I don't reproduce the problem with:
```
#include "gdal_priv.h"
#include "ogrsf_frmts.h"

int main()
{
    GDALAllRegister();
    auto poDS = std::unique_ptr<GDALDataset>(GDALDataset::Open("mytest.gdb", GDAL_OF_UPDATE | GDAL_OF_VECTOR, nullptr, nullptr, nullptr));
    printf("number of layers before = %d\n", poDS->GetLayerCount());
    std::string osLayerName = poDS->GetLayer(0)->GetName();
    printf("first layer name = %s\n", osLayerName.c_str());
    poDS->DeleteLayer(0);
    printf("number of layers after = %d\n", poDS->GetLayerCount());
    printf("GetLayer(0) = %p\n", poDS->GetLayer(0));
    printf("GetLayer(%s) = %p\n", osLayerName.c_str(), poDS->GetLayerByName(osLayerName.c_str()));
    return 0;
}
```

Output:
```
number of layers before = 1
first layer name = test
number of layers after = 0
GetLayer(0) = (nil)
GetLayer(test) = (nil)
```

@giser-pony  Can you try the above reproducer?  If you still reproduce the issue with it, please attach a dataset that can be used to reproduce it

**Comment by giser-pony** [comment]
@rouault Thank you, I don't reproduce the problem with you code too, I'm sorry that I found the reason was that the parameters were passed incorrectly. `GDALOpenInfo openInfo(strGdbName.c_str(), 1)` should be `GDALOpenInfo openInfo(strGdbName.c_str(), GDAL_OF_UPDATE | GDAL_OF_VECTOR)`, then the dirver will remove layer name from `m_osMapNameToIdx` when collect layers

**Comment by rouault** [comment]
> `GDALOpenInfo openInfo(strGdbName.c_str(), 1)` should be `GDALOpenInfo openInfo(strGdbName.c_str(), GDAL_OF_UPDATE | GDAL_OF_VECTOR)`

Weird, because GDAL_OF_UPDATE evaluates to 1. I cannot reproduce the issue in my reproduced by changing GDAL_OF_UPDATE | GDAL_OF_VECTOR to 1. That said, your code sample isn't using recommended ways of using the API. You shouldn't use driver->pfnOpen. This is an implementation detail. Better use GDALDataset::Open()

**Comment by giser-pony** [comment]
Sometimes I want to use the specified driver, so not using recommended ways of using the API. Thanks for your suggestion.

**Comment by rouault** [comment]
GDALDataset::Open() has a papszAllowedDrivers argument where you can put a restricted set(s) of drivers

**Comment by giser-pony** [comment]
That's great, thanks again for your suggestion
