### ISSUE TITLE
invalid COG generated by python swig API

### ISSUE THREAD

**Issue by iferencik** [OSGeo/gdal#9452]
I am creating succesfully a COG with

```bash

gdalwarp  -s_srs EPSG:4326 -t_srs EPSG:3857 -of COG -r near -ovr NONE  -co BLOCKSIZE=256 -co OVERVIEWS=IGNORE_EXISTING -co COMPRESS=ZSTD -co PREDICTOR=YES -co OVERVIEW_RESAMPLING=NEAREST -co BIGTIFF=YES -co NUM_THREADS=ALL_CPUS -co ADD_ALPHA=NO  -wm 500 -multi -overwrite   /vsicurl/https://undpgeohub.blob.core.windows.net/stacdata/SVDNB_npp_d20240125.vcld.tif /tmp/SVDNB_npp_d20240125.vcld.cog.tif

```
but i fail to reproduce the same/very similar result with

```python
        logger.info(f'running gdalwarp on {src_path}')
        progressbar = tqdm.tqdm(range(0, 100), desc=f'Creating COG {dst_path}', unit_scale=True)

        wo = gdal.WarpOptions(
            format='COG',
            srcSRS='EPSG:4326',
            dstSRS='EPSG:3857',
            overviewLevel=None,
            multithread=True,
            resampleAlg='NEAREST',
            
            creationOptions=[
                "BLOCKSIZE=256",
                "OVERVIEWS=IGNORE_EXISTING",
                "COMPRESS=ZSTD",
                "PREDICTOR=YES",
                "OVERVIEW_RESAMPLING=NEAREST",
                "BIGTIFF=IF_SAFER",
                "NUM_THREADS=ALL_CPUS",
                "ADD_ALPHA=NO",

            ],

            callback=gdal_callback,
            callback_data=(timeout_event, progressbar)
        )
        cog_ds = gdal.Warp(
            srcDSOrSrcDSTab=src_path,
            destNameOrDestDS=dst_path,

            options=wo,
        )

```

validation of the created output fails with

```bash
rio cogeo info  dst_path
COG Validation info
    - The offset of the main IFD should be < 300. It is 205716498 instead (error)
    - The offset of the IFD for overview of index 0 is 746, whereas it should be greater than the one of the main image, which is at byte 205716498 (error)

```

is my assumption that the same args in python should produyce the same result valid?

### Steps to reproduce the issue

run the above gdalwarp and python code

### Versions and provenance

Operating System: Ubuntu 22.04.3 LTS              
 Kernel: Linux 6.5.0-25-generic
 Architecture: x86-64
GDAL 3.4.3, released 2022/04/22

**Comment by rouault** [comment]
I've attempted to reproduce with GDAL master, and everything looks good. Did you make sure to remove a potentially pre-existing output file?

**Comment by iferencik** [comment]
@rouault thanks for the quick try.

I have found the culprit. It is an obscure and obvious thing at the same time.

basically right after the warping i added this metadata

cog_ds.SetMetadata({f"DNB_FILE_SIZE_{ctime}": f"{os.path.getsize(src_path)}" })
cog_ds.SetMetadata({'DESCRIPTION':description})


and then flushed
del cog_ds

I assume, this has messed up the hidden COG metadata and resulted in an invalid COG.

upon commenting those 2 lines everything works.

thank you again
