### ISSUE TITLE
Why does the converted png file with '-ot Int16' show 64bit depth on windows file property?

### ISSUE THREAD

**Issue by hzhshok** [OSGeo/gdal#9455]
### What is the bug?

I converted geotiff dem file with the format of float32(nodata=-32767) to png file(nodata=-32767) with the format of Int16, but, it showed 64bit depth on windows file property, so, the other program will generate warning message.

I don't know if it is a issue or correct behavior, please someone help me clarify or confirm that, thanks in advance!

[output_filename-epsg-tr-0-0-Property.zip](https://github.com/OSGeo/gdal/files/14600379/output_filename-epsg-tr-0-0-Property.zip)

### Steps to reproduce the issue

a. Convert the geotiff file to png file with the format Uint16.
**gdalwarp -ot UInt16 -of PNG -a_nodata 65535 -scale 1137 1449 1137 1449 output_filename-epsg-tr-0-0.tif output_filename-epsg-tr-0-0.png**

Note: The geotiff min:max=1137 1449, **which the values is all positive number**。
b. I check the png file which is one band with the format of Uint16, 
   QGIS showed:
    Data type	UInt16 - Sixteen bit unsigned integer
    GDAL Driver Description	PNG
    GDAL Driver Metadata	Portable Network Graphics
  Windows showed:
    As the attached file including the geotiff, png, and the property detail on windows.

Regards.
    
 

### Versions and provenance

Windows11, 
GDA: CONFIG_VERSION=3.8.1 

QGIS version  3.34.4-Prizren
GDAL/OGR version
3.8.4

**Comment by rouault** [comment]
"it showed 64bit depth on windows file property". This might be a bug/feature of this windows utility

Using the independent exiftool utility confirms the file is 16-bit:
```
$ exiftool output_filename-epsg-tr-0-0.png
ExifTool Version Number         : 11.88
File Name                       : output_filename-epsg-tr-0-0.png
Directory                       : .
File Size                       : 32 kB
File Modification Date/Time     : 2024:03:14 17:19:06+01:00
File Access Date/Time           : 2024:03:14 11:13:21+01:00
File Inode Change Date/Time     : 2024:03:14 11:12:32+01:00
File Permissions                : rw-rw-r--
File Type                       : PNG
File Type Extension             : png
MIME Type                       : image/png
Image Width                     : 2017
Image Height                    : 2017
Bit Depth                       : 16
Color Type                      : Grayscale
Compression                     : Deflate/Inflate
Filter                          : Adaptive
Interlace                       : Noninterlaced
Transparency                    : 65535
Image Size                      : 2017x2017
Megapixels                      : 4.1
```
