### ISSUE TITLE
Required documentation on How to use GDAL bindings or directly GDAL with flutter iOS?

### ISSUE THREAD

**Issue by huzaifacontour** [OSGeo/gdal#9475]
### Feature description

I want to use GDAL with my flutter application, I can use GDAL java bindings in android but for iOS it requires swift or Obj C, so I want to know how can I use GDAL there, maybe without bindings but how?

**Comment by rouault** [comment]
We can't get into the specifics of every framework. GDAL has a C API, so I guess generic documentation related to how to use a C API with Flutter iOS is your way to start with that. Like https://docs.flutter.dev/platform-integration/ios/c-interop
