### ISSUE TITLE
ogr2ogr kml to csv throws away the most important part: the coordinates

### ISSUE THREAD

**Issue by jidanni** [OSGeo/gdal#9479]
[TrackWaypoint.kml.gz](https://github.com/OSGeo/gdal/files/14625814/TrackWaypoint.kml.gz)

```
ogr2ogr TrackWaypoint.csv TrackWaypoint.kml
cat TrackWaypoint.csv
Name,description,timestamp,begin,end,altitudeMode,tessellate,extrude,visibility,drawOrder,icon
"001",,,,,,-1,0,-1,,
"002",,,,,,-1,0,-1,,
```

If this is not a bug, then I will add the correct way to do it to the ogr2ogr man page examples.

**Comment by rouault** [comment]
This is expected. This is a specific behaviour of the CSV driver mentionned at https://gdal.org/drivers/vector/csv.html#layer-creation-options : """GEOMETRY=[AS_WKT/AS_XYZ/AS_XY/AS_YZ]: By default, the geometry of a feature written to a .csv file is discarded. It is possible to export the geometry in its WKT representation by specifying GEOMETRY=AS_WKT. It is also possible to export point geometries into their X,Y,Z components (different columns in the csv file) by specifying GEOMETRY=AS_XYZ, GEOMETRY=AS_XY or GEOMETRY=AS_YX.""""

> I will add the correct way to do it to the ogr2ogr man page examples.

There are several thousands of potential combinations of input driver x output driver with ogr2ogr. Users need to refer to the documentation page of the input and output driver involved in the conversion to understand the details.
