### ISSUE TITLE
Error When Compiling GDAL Using Intel Latest Compiler (LLVM: ICX, ICPX)

### ISSUE THREAD

**Issue by AsyamMD** [OSGeo/gdal#9508]
### What is the bug?

Error shows up when compiling overview.cpp.o
Here I attach the error message:

`[ 86%] Building CXX object gcore/CMakeFiles/gcore.dir/overview.cpp.o
PLEASE append the compiler options "-save-temps -v", rebuild the application to to get the full command which is failing and submit a bug report to https://software.intel.com/en-us/support/priority-support which includes the failing command, input files for the command and the crash backtrace (if any).
Stack dump:
0.      Program arguments: /opt/intel/oneapi/compiler/2024.0/bin/compiler/clang++ @/tmp/icpx1431877046In09Xz/icpxargenTmrO
1.      <eof> parser at end of file
2.      Optimizer
 #0 0x000055e8d40f7773 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/intel/oneapi/compiler/2024.0/bin/compiler/clang+++0x5144773)
 #1 0x000055e8d40f5c60 llvm::sys::RunSignalHandlers() (/opt/intel/oneapi/compiler/2024.0/bin/compiler/clang+++0x5142c60)
 #2 0x000055e8d40f6bef llvm::sys::CleanupOnSignal(unsigned long) (/opt/intel/oneapi/compiler/2024.0/bin/compiler/clang+++0x5143bef)
 #3 0x000055e8d408be65 (anonymous namespace)::CrashRecoveryContextImpl::HandleCrash(int, unsigned long) CrashRecoveryContext.cpp:0:0
 #4 0x000055e8d408c0a9 CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
 #5 0x00007fc464642520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #6 0x000055e8d45274a3 (anonymous namespace)::RerollRewriterBase::updateChainSRTemps(llvm::loopopt::SafeRedInfo const*) HIRLoopReroll.cpp:0:0
 #7 0x000055e8d4527461 (anonymous namespace)::RerollRewriterBase::updateChainSRs() HIRLoopReroll.cpp:0:0
 #8 0x000055e8d4527257 (anonymous namespace)::FastRerollRewriter::reroll() HIRLoopReroll.cpp:0:0
 #9 0x000055e8d4521b7b (anonymous namespace)::rewriteLoopBody(unsigned int, llvm::SmallVector<llvm::loopopt::reroll::SeedInfo, 4u>&, llvm::loopopt::HIRSafeReductionAnalysis&, std::map<llvm::loopopt::HLInst const*, (anonymous namespace)::SelfSRSeedsTy, std::less<llvm::loopopt::HLInst const*>, std::allocator<std::pair<llvm::loopopt::HLInst const* const, (anonymous namespace)::SelfSRSeedsTy>>> const&, llvm::DenseMap<llvm::SCEV const*, llvm::loopopt::DDRef const*, llvm::DenseMapInfo<llvm::SCEV const*, void>, llvm::detail::DenseMapPair<llvm::SCEV const*, llvm::loopopt::DDRef const*>> const&) HIRLoopReroll.cpp:0:0
#10 0x000055e8d4520b3b (anonymous namespace)::doLoopReroll(llvm::loopopt::HIRFramework&, llvm::loopopt::HIRDDAnalysis&, llvm::loopopt::HIRLoopStatistics&, llvm::loopopt::HIRSafeReductionAnalysis&) HIRLoopReroll.cpp:0:0
#11 0x000055e8d451f955 llvm::loopopt::HIRLoopRerollPass::runImpl(llvm::Function&, llvm::AnalysisManager<llvm::Function>&, llvm::loopopt::HIRFramework&) (/opt/intel/oneapi/compiler/2024.0/bin/compiler/clang+++0x556c955)
#12 0x000055e8d54835a5 llvm::detail::PassModel<llvm::Function, llvm::loopopt::HIRLoopRerollPass, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Function>>::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) PassBuilder.cpp:0:0
#13 0x000055e8d3c46723 llvm::PassManager<llvm::Function, llvm::AnalysisManager<llvm::Function>>::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) (/opt/intel/oneapi/compiler/2024.0/bin/compiler/clang+++0x4c93723)
#14 0x000055e8d31ae6fd llvm::detail::PassModel<llvm::Function, llvm::PassManager<llvm::Function, llvm::AnalysisManager<llvm::Function>>, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Function>>::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) NVPTXTargetMachine.cpp:0:0
#15 0x000055e8d3c4d0b2 llvm::ModuleToFunctionPassAdaptor::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/opt/intel/oneapi/compiler/2024.0/bin/compiler/clang+++0x4c9a0b2)
#16 0x000055e8d31ae48d llvm::detail::PassModel<llvm::Module, llvm::ModuleToFunctionPassAdaptor, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) NVPTXTargetMachine.cpp:0:0
#17 0x000055e8d3c45723 llvm::PassManager<llvm::Module, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/opt/intel/oneapi/compiler/2024.0/bin/compiler/clang+++0x4c92723)
#18 0x000055e8d4b30c16 (anonymous namespace)::EmitAssemblyHelper::RunOptimizationPipeline(clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream>>&, std::unique_ptr<llvm::ToolOutputFile, std::default_delete<llvm::ToolOutputFile>>&) BackendUtil.cpp:0:0
#19 0x000055e8d4b2c20b clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::StringRef, llvm::Module*, clang::BackendAction, llvm::IntrusiveRefCntPtr<llvm::vfs::FileSystem>, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream>>) (/opt/intel/oneapi/compiler/2024.0/bin/compiler/clang+++0x5b7920b)
#20 0x000055e8d4ed45a3 clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) CodeGenAction.cpp:0:0
#21 0x000055e8d603126b clang::ParseAST(clang::Sema&, bool, bool) (/opt/intel/oneapi/compiler/2024.0/bin/compiler/clang+++0x707e26b)
#22 0x000055e8d4ed2fe8 clang::CodeGenAction::ExecuteAction() (/opt/intel/oneapi/compiler/2024.0/bin/compiler/clang+++0x5f1ffe8)
#23 0x000055e8d4e447ba clang::FrontendAction::Execute() (/opt/intel/oneapi/compiler/2024.0/bin/compiler/clang+++0x5e917ba)
#24 0x000055e8d4dd3112 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/intel/oneapi/compiler/2024.0/bin/compiler/clang+++0x5e20112)
#25 0x000055e8d4ecf97f clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/intel/oneapi/compiler/2024.0/bin/compiler/clang+++0x5f1c97f)
#26 0x000055e8d2e6f431 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/intel/oneapi/compiler/2024.0/bin/compiler/clang+++0x3ebc431)
#27 0x000055e8d2e6b753 ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&, llvm::ToolContext const&) driver.cpp:0:0
#28 0x000055e8d4cc1459 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const::$_0>(long) Job.cpp:0:0
#29 0x000055e8d408bdfe llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/opt/intel/oneapi/compiler/2024.0/bin/compiler/clang+++0x50d8dfe)
#30 0x000055e8d4cc0539 clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const (/opt/intel/oneapi/compiler/2024.0/bin/compiler/clang+++0x5d0d539)
#31 0x000055e8d4c628f0 clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/opt/intel/oneapi/compiler/2024.0/bin/compiler/clang+++0x5caf8f0)
#32 0x000055e8d4c62d62 clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const (/opt/intel/oneapi/compiler/2024.0/bin/compiler/clang+++0x5cafd62)
#33 0x000055e8d4c8632c clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) (/opt/intel/oneapi/compiler/2024.0/bin/compiler/clang+++0x5cd332c)
#34 0x000055e8d2e69a05 clang_main(int, char**, llvm::ToolContext const&) (/opt/intel/oneapi/compiler/2024.0/bin/compiler/clang+++0x3eb6a05)
#35 0x000055e8d2e78dde main (/opt/intel/oneapi/compiler/2024.0/bin/compiler/clang+++0x3ec5dde)
#36 0x00007fc464629d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#37 0x00007fc464629e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#38 0x000055e8d2e685a9 _start (/opt/intel/oneapi/compiler/2024.0/bin/compiler/clang+++0x3eb55a9)
icpx: error: clang frontend command failed with exit code 139 (use -v to see invocation)
Intel(R) oneAPI DPC++/C++ Compiler 2024.0.2 (2024.0.2.20231213)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/intel/oneapi/compiler/2024.0/bin/compiler
Configuration file: /opt/intel/oneapi/compiler/2024.0/bin/compiler/../icpx.cfg
icpx: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
icpx: note: diagnostic msg: /tmp/icpx-a3ae6e8e6b/overview-5da0b1.cpp
icpx: note: diagnostic msg: /tmp/icpx-a3ae6e8e6b/overview-5da0b1.sh
icpx: note: diagnostic msg:

********************
gmake[2]: *** [gcore/CMakeFiles/gcore.dir/build.make:622: gcore/CMakeFiles/gcore.dir/overview.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:9425: gcore/CMakeFiles/gcore.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2`

### Steps to reproduce the issue

Building outside of the source code, using this command:

`cmake -DCMAKE_INSTALL_PREFIX=$DIR/grib2 -DNETCDF_LIBRARY=$DIR/NETCDF -DNETCDF_INCLUDE_DIR=$DIR/NETCDF/include -DGDAL_USE_NETCDF=ON -DHDF5_LIBRARY=$DIR/grib2 -DHDF5_INCLUDE_DIR=$DIR/grib2/include -DGDAL_USE_HDF5=ON -DBUILD_SHARED_LIBS=BOTH -S ../gdal/ -B .`

### Versions and provenance

Windows 11 with WSL2 Ubuntu 22.04 LTS, kernel version 6.12

**Comment by rouault** [comment]
As the error message makes it clear, this is a bug in the compiler, and should be reported to Intel. Someone may at best try to find a workaround by making source code changes but that would require access to the compiler
