### ISSUE TITLE
CodeQL scanning takes 30 +min when cmake checks for HDF5 availability

### ISSUE THREAD

**Issue by echoix** [OSGeo/gdal#9549]
### What is the bug?

In the CodeQL workflow, the build must be traced to create a database to analyze afterwards. The step that configures the build (before actually building) seems to take way too long compared to other builds in CI.
https://github.com/OSGeo/gdal/blob/1bf042a2db15e09a88404e9631d6ab32ebbd501b/.github/workflows/codeql.yml#L131-L137

There is one specific line in that configuration that takes over 30 minutes to complete. As a reference, in other builds and locally, it is a matter of 0.3 seconds between the output of "Found LibKML: ..." and "Found HDF5: ...".

### Steps to reproduce the issue

Since it is happening in your own CI, simply triggering any build that runs CodeQL, or analyzing the logs is enough.

For example, a build that happened this morning (https://github.com/OSGeo/gdal/actions/runs/8408963858/job/23025746319#step:7:325), with "Show timestamps" enabled:
![image](https://github.com/OSGeo/gdal/assets/27212526/2cdfa9cb-3ac8-4965-a3d5-0ed7271e1d3c)

Same thing with all the successful runs I checked, including older runs, like on Feb 5, 2024 (https://github.com/OSGeo/gdal/actions/runs/7786604378/job/21231808861#step:7:326):
![image](https://github.com/OSGeo/gdal/assets/27212526/321c25cf-d975-438c-b15e-a027f45cd524)

Or the very first run on Jan 9, 2024 that took almost one hour for that step (https://github.com/OSGeo/gdal/actions/runs/7466059761/job/20316583671#step:7:316)
![image](https://github.com/OSGeo/gdal/assets/27212526/3727f72a-d111-4352-a341-e566db4435da)

But even more, I was able to reproduce locally in a devcontainer (ubuntu 22.04)+vscode, and the codeql cli. For me the problematic line took 54minutes and 1.599 secs (the time stuck was using ~100% of 1 CPU core on 12, no memory problems.
```json
// For format details, see https://aka.ms/devcontainer.json. For config options, see the
// README at: https://github.com/devcontainers/templates/tree/main/src/ubuntu
{
	"name": "Ubuntu",
	// Or use a Dockerfile or Docker Compose file. More info: https://containers.dev/guide/dockerfile
	"image": "mcr.microsoft.com/devcontainers/base:jammy"

	// Features to add to the dev container. More info: https://containers.dev/features.
	// "features": {},

	// Use 'forwardPorts' to make a list of ports inside the container available locally.
	// "forwardPorts": [],

	// Use 'postCreateCommand' to run commands after the container is created.
	// "postCreateCommand": "uname -a",

	// Configure tool-specific properties.
	// "customizations": {},

	// Uncomment to connect as root instead. More info: https://aka.ms/dev-containers-non-root.
	// "remoteUser": "root"
}
```
My code is mounted in a volume, and the root of the repo is `/workspaces/gdal`
So my repro would be equivalent to the following:

```shell
sudo apt-get update
sudo apt-get install -y ccache cmake g++ swig python3-numpy libproj-dev libqhull-dev
sudo apt-get install -y \
            libblosc-dev \
            libboost-dev \
            libcairo2-dev \
            libcfitsio-dev \
            libcrypto++-dev \
            libcurl4-gnutls-dev \
            libexpat-dev \
            libfcgi-dev \
            libfyba-dev \
            libfreexl-dev \
            libgeos-dev \
            libgeotiff-dev \
            libgif-dev \
            libhdf5-serial-dev \
            libjpeg-dev \
            libkml-dev \
            liblcms2-2 \
            liblz4-dev \
            liblzma-dev \
            libmysqlclient-dev \
            libnetcdf-dev \
            libogdi-dev \
            libopenexr-dev \
            libopenjp2-7-dev \
            libpcre3-dev \
            libpng-dev \
            libpoppler-dev \
            libpoppler-private-dev \
            libpq-dev \
            libproj-dev \
            librasterlite2-dev \
            libspatialite-dev \
            libssl-dev \
            libwebp-dev \
            libxerces-c-dev \
            libxml2-dev \
            libxslt-dev \
            libzstd-dev \
            unixodbc-dev
sudo apt install moreutils

export CCACHE_BASEDIR=/workspaces/gdal
export CCACHE_DIR=/workspaces/gdal/.ccache
export CCACHE_MAXSIZE=250M
ccache -z

mkdir build
cd build
cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo -DUSE_CCACHE=YES -DGDAL_USE_LERC_INTERNAL=OFF | ts -i '[%H:%M:%.S]' | ts -s '[%H:%M:%.S]' |  ts '[%Y-%m-%d %H:%M:%.S]'

cd ..
rm -rf build
rm -rf .ccache
ccache -z

# Install CodeQL cli
wget https://github.com/github/codeql-action/releases/download/codeql-bundle-v2.16.5/codeql-bundle-linux64.tar.gz
tar -xf codeql-bundle-linux64.tar.gz
export PATH=/workspaces/gdal/codeql:$PATH
# Test if running correctly
codeql resolve qlpacks

# Follow the (almost) same steps as the CodeQL action in GitHub Actions
codeql database init --db-cluster /workspaces/gdal/codeql_databases --source-root=/workspaces/gdal --extractor-include-aliases --language=cpp --begin-tracing   --calculate-language-specific-baseline --sublanguage-file-coverage
source /workspaces/gdal/codeql_databases/temp/tracingEnvironment/start-tracing.sh

mkdir build
cd build
cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo -DUSE_CCACHE=YES -DGDAL_USE_LERC_INTERNAL=OFF | ts -i '[%H:%M:%.S]' | ts -s '[%H:%M:%.S]' |  ts '[%Y-%m-%d %H:%M:%.S]'

```

I used `ts` to show the times of the log, the time since the beginning, and the time since the last line was printed, but the results were the same without it.

### Versions and provenance

From the workflow logs, the long time taken happened at least with CodeQL versions 2.16.5, 2.16.1, and for the first even run with 2.15.5. I used CodeQL CLI version 2.16.5 locally.
GDAL versions were:
-  https://github.com/rouault/gdal/tree/fix_9538 (HEAD is now at cd45f7c Merge 8c092858fdc37ca60e34fd86bf4092952c0dd3da into 28b8f278e1a2acf2f3afdb56aff6f224eb366b08) (/usr/bin/git log -1 --format='%H'
'cd45f7c7240922637d0fb520cd7bd52f45ff84b0')
- https://github.com/OSGeo/gdal/commit/6a768fb6c6ee906445988dec14c35c9d48e8e2b3
- https://github.com/rouault/gdal/tree/codeql, (  /usr/bin/git checkout --progress --force refs/remotes/pull/9012/merge) (HEAD is now at 9be6712 Merge 5bf55c6650fc96cde4bc7fa2683a7782e16b056d into 895e9fbd63b2aa22471f4f8c69efd5ba4e700e9c) (
/usr/bin/git log -1 --format='%H'
'9be671226716a5f93352847346c87a55382f7b5d')
- Locally: https://github.com/echoix/gdal/commit/ee17ee24c83c0660af58a7e7d469867e1cdb2470 (https://github.com/OSGeo/gdal/commit/ee17ee24c83c0660af58a7e7d469867e1cdb2470)

HDF5 seems to be 1.10.7 as found by CMake:  "`[2024-03-24 16:17:34.736197] [00:54:36.869863] [00:54:01.599249] -- Found HDF5: /usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5.so;/usr/lib/x86_64-linux-gnu/libcrypto.so;/usr/lib/x86_64-linux-gnu/libcurl.so;/usr/lib/x86_64-linux-gnu/libpthread.a;/usr/lib/x86_64-linux-gnu/libsz.so;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/libdl.a;/usr/lib/x86_64-linux-gnu/libm.so (found version "1.10.7") found components: C`"

cmake version 3.22.1

### Additional context

I investigated this since this morning, I was surprised that small CI jobs in OSGeo/grass were queued for so long while there wasn't any activity in any of the repos I work with in OSGeo. Since the available 20 free runners for GitHub Actions are shared between all projects of the same organization, I saw some recent activity in the GDAL repo, which also had queued jobs. I wanted to see if any jobs were useless, or monopolized more than it needed. I looked at the history, and was surprised that CodeQL here takes an hour or so. Opening any log, and seeing that the build step, which usually takes an almost constant time as other builds, but slowed a little bit down, was taking way more time than the actual querying that is also kind of long. There's definitely a problem there.
The many other build jobs in CI for gdal, that can take some time, are nowhere near that amount of time (at least if limiting to Ubuntu builds).

I also looked for issues/PRs here, on Google, and in the CodeQL repos, anything to do with tracing being long, but didn't find anything. That's also why I looked to see if it was a regression on the CodeQL side, but its been the same for multiple releases, (2.15.5 in january).

I suspect a CodeQL issue, but maybe there's something here not right too, since when I didn't have CodeQL installed in the container, the normal run had that warning below:
```
CMake Warning at frmts/hdf5/CMakeLists.txt:74 (message):
  HDF5 library does not seem to have thread-safety enabled.  Adding a global
  lock on GDAL side
``` 
Part of console output:
```
[2024-03-24 14:49:48.030973] [00:00:00.003730] [00:00:11.423969] -- Could NOT find LURATECH (missing: LURATECH_LIBRARY LURATECH_INCLUDE_DIR) 
[2024-03-24 14:49:48.036211] [00:00:00.005228] [00:00:11.429088] -- Could NOT find Arrow (missing: Arrow_DIR)
[2024-03-24 14:49:48.042702] [00:00:00.006493] [00:00:11.435694] -- Could NOT find JNI (missing: JAVA_AWT_LIBRARY JAVA_JVM_LIBRARY JAVA_INCLUDE_PATH JAVA_INCLUDE_PATH2 JAVA_AWT_INCLUDE_PATH) 
[2024-03-24 14:49:48.047262] [00:00:00.004577] [00:00:11.440273] -- Could NOT find Java (missing: Java_JAVA_EXECUTABLE Java_JAVAC_EXECUTABLE Java_JAR_EXECUTABLE Java_JAVADOC_EXECUTABLE Java_JAVAH_EXECUTABLE Runtime Development) 
[2024-03-24 14:49:48.050946] [00:00:00.003711] [00:00:11.444016] -- Could NOT find CSharp (missing: CSHARP_TYPE CSHARP_VERSION CSHARP_COMPILER) 
[2024-03-24 14:49:48.053051] [00:00:00.002069] [00:00:11.446081] -- Performing Test HAS_NO_UNDEFINED
[2024-03-24 14:49:48.113357] [00:00:00.060304] [00:00:11.506341] -- Performing Test HAS_NO_UNDEFINED - Success
[2024-03-24 14:49:48.130138] [00:00:00.016809] [00:00:11.523190] -- Performing Test COMPILER_SUPPORTS_CXX17
[2024-03-24 14:49:48.373608] [00:00:00.243444] [00:00:11.766624] -- Performing Test COMPILER_SUPPORTS_CXX17 - Success
[2024-03-24 14:49:48.374160] [00:00:00.000558] [00:00:11.767190] -- Looking for linux/fs.h
[2024-03-24 14:49:48.445164] [00:00:00.071001] [00:00:11.838160] -- Looking for linux/fs.h - found
[2024-03-24 14:49:48.448080] [00:00:00.002916] [00:00:11.841100] -- Looking for blosc_cbuffer_validate
[2024-03-24 14:49:48.555597] [00:00:00.107514] [00:00:11.948591] -- Looking for blosc_cbuffer_validate - found
[2024-03-24 14:49:48.579324] [00:00:00.023699] [00:00:11.972304] -- Could NOT find BISON (missing: BISON_EXECUTABLE) 
CMake Warning at frmts/hdf5/CMakeLists.txt:74 (message):
  HDF5 library does not seem to have thread-safety enabled.  Adding a global
  lock on GDAL side


[2024-03-24 14:49:48.891014] [00:00:00.311715] [00:00:12.284006] -- Looking for sqlite3ext.h
[2024-03-24 14:49:48.957154] [00:00:00.066139] [00:00:12.350143] -- Looking for sqlite3ext.h - found
[2024-03-24 14:49:49.003744] [00:00:00.046583] [00:00:12.396720] -- Could NOT find BISON (missing: BISON_EXECUTABLE) 
[2024-03-24 14:49:49.083001] [00:00:00.079299] [00:00:12.476018] -- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
[2024-03-24 14:49:49.162241] [00:00:00.079200] [00:00:12.555223] --   Target system:             Linux
[2024-03-24 14:49:49.162311] [00:00:00.000047] [00:00:12.555280] --   Installation directory:    /usr/local
[2024-03-24 14:49:49.162332] [00:00:00.000011] [00:00:12.555293] --   C++ Compiler type:         GNU
[2024-03-24 14:49:49.162368] [00:00:00.000007] [00:00:12.555300] --   C compile command line:    /usr/bin/ccache /usr/bin/cc
[2024-03-24 14:49:49.162406] [00:00:00.000007] [00:00:12.555307] --   C++ compile command line:  /usr/bin/ccache /usr/bin/c++
[2024-03-24 14:49:49.162444] [00:00:00.000006] [00:00:12.555315] -- 
[2024-03-24 14:49:49.162483] [00:00:00.000009] [00:00:12.555322] --   CMAKE_C_FLAGS:               -fvisibility=hidden
```

**Comment by rouault** [comment]
Thanks for the detailed analysis. I've filed a CodeQL upstream bug: https://github.com/github/codeql/issues/16051

Attempt at workarounding it in #9566

**Comment by echoix** [comment]
Great! On my side I was trying to see if it was the global lock of hdf5, by trying to set it on or off, and tried to set -DGDAL_USE_HDF5=OFF and -DGDAL_USE_LIBKML=OFF (separately) and was at trying to just not install these dependencies to see the difference in time, but didn't have a solution yet. My goal was trying to cut off features until the bug was escaped, and put them back one by one. I also wanted to try CodeQL (probably locally), with a commit near March 2023, before the changes in the CMakelists of HDF5.

If I was to be unsuccessful, and you didn't have a clue either, I would've filed a bug at CodeQL, since 0.3 seconds nominal taking 30-54 min is something that would pick the curiosity of some devs out there.

**Comment by rouault** [comment]
Disabling temporarily CodeQL turned out to be tricky! It's LD_PRELOAD'ed library apparently prevents from unsetting LD_PRELOAD or if you change the LD_PRELOAD value, it appends your new value, after the original one, so that the CodeQL .so is still loaded. A genuine virus! I finally managed to temporarily disable it by renaming the file pointed by LD_PRELOAD...

**Comment by rouault** [comment]
> On my side I was trying to see if it was the global lock of hdf5, by trying to set it on or off

no, it seems that it is related to the h5cc and h5c++ tools of libhdf5 that are used during FindHDF5.cmake (https://gitlab.kitware.com/cmake/cmake/-/blob/master/Modules/FindHDF5.cmake?ref_type=heads). Those are helper scripts to compile HDF5 related code. That probably confuses CodeQL interception logic.
