### ISSUE TITLE
Unable to compile GDAL for VisionOS

### ISSUE THREAD

**Issue by vmirgorod** [OSGeo/gdal#9550]
### What is the bug?

I'm getting given the following compiler error while GDAL for Vision OS compilation. 

```
gdal-3.8.4/apps/gdal_grid_lib.cpp:1162:25: error: variable has incomplete type 'VSIStatBufL' (aka 'stat64')
            VSIStatBufL sStat;
                        ^
gdal-3.8.4/port/cpl_vsi.h:200:16: note: forward declaration of 'stat64'
typedef struct VSI_STAT64_T VSIStatBufL;
               ^
gdal/port/cpl_config.h:44:22: note: expanded from macro 'VSI_STAT64_T'
#define VSI_STAT64_T stat64
```

### Steps to reproduce the issue

Please run attached python build script.
Or use building CMAKE command with `VISIONOS` target platform.
[ios.build.gdal.zip](https://github.com/OSGeo/gdal/files/14736504/ios.build.gdal.zip)

Note: I discovered similar issue this [project](https://github.com/rpm-software-management/rpm/issues/1752#issuecomment-896872856)  and this [solution](https://github.com/emilazy/rpm/commit/0abc07d8ee29bff85f2f55572e49cf30e9b7b84a). Probably it would be helpful.

### Versions and provenance

Vision OS 1.1, GDAL version 3.8.4

**Comment by rouault** [comment]
We don't have access to that system, but you're welcome to provide a pull request to fix it
The fix is likely to add the appropriate CMAKE_SYSTEM_NAME check at https://github.com/OSGeo/gdal/blob/1bf042a2db15e09a88404e9631d6ab32ebbd501b/cmake/helpers/configure.cmake#L260

**Comment by vmirgorod** [comment]
@rouault I can confirm adding new check works.

The complete diff is attached (I also attached TVOS/WatchOS support).
But I'm not able to push code to feature branch (I got `Permission to OSGeo/gdal.git denied to vmirgorod` error when tried).
Can I ask you either check what's wrong with permissions or make commit/PR by yourself.

```
diff --git a/cmake/helpers/configure.cmake b/cmake/helpers/configure.cmake
index 994de28832..6aee8f7d64 100644
--- a/cmake/helpers/configure.cmake
+++ b/cmake/helpers/configure.cmake
@@ -257,7 +257,7 @@ else ()
   # available at build time.
   # This is also necessary for Mac Catalyst builds.
   # Cf https://lists.osgeo.org/pipermail/gdal-dev/2022-August/056174.html
-  if (${CMAKE_SYSTEM_NAME} MATCHES "iOS" OR ${CMAKE_SYSTEM_NAME} MATCHES "Darwin")
+  if (${CMAKE_SYSTEM_NAME} MATCHES "iOS|visionOS|tvOS|watchOS|Darwin")
     set(VSI_FOPEN64 "fopen")
     set(VSI_FTRUNCATE64 "ftruncate")
     set(VSI_FTELL64 "ftell")
```
