### ISSUE TITLE
JPEG error (TIFFReadEncodedTile failed) when pulling data out of S3 into a COG

### ISSUE THREAD

**Issue by trharris78** [OSGeo/gdal#9563]
### What is the bug?

I am trying to pull data out of S3 into a COG and I get a strange JPEG error when doing so. I seems that this combination is critical to reproducing:

- Input data is in S3
- Input data has a nodata mask
- Pulling data into a COG output file

### Steps to reproduce the issue

My original dataset is fairly large, but I was able to get the same error just using the command-line tools to produce some empty files. It does require an S3 bucket, though.

```
# 1. Create an empty georeferenced TIF with 4 bands:
gdal_create -of GTiff -outsize 128 128 -bands 4 -ot Byte -a_srs EPSG:4326 -a_ullr -91.42822265625 15.205078125 -91.40625 15.18310546875 -co COMPRESS=JPEG -co TILED=YES blank.tif

# 2. From that TIF, create 3-band TIF with a nodata mask:
GDAL_TIFF_INTERNAL_MASK=YES gdal_translate -of GTiff -b 1 -b 2 -b 3 -mask 4 -co COMPRESS=JPEG -co TILED=YES blank.tif withmask.tif

# 3. Push the masked TIF into S3 as a COG (update with your own S3 path):
CPL_VSIL_USE_TEMP_FILE_FOR_RANDOM_WRITE=YES gdal_translate -f COG -co COMPRESS=JPEG withmask.tif /vsis3/your-bucket/cog.tif

# 4. Create a VRT that references the S3 COG (but has larger extents):
gdalbuildvrt -te -91.494140625 15.1171875 -91.40625 15.205078125 test.vrt /vsis3/your-bucket/cog.tif

# 5. Try to translate the VRT to a COG:
gdal_translate -tr 0.000071806 0.000071806 -f COG -co COMPRESS=JPEG test.vrt test.tif
```

For me, this results in an error:
```
Input file size is 512, 512
0..ERROR 1: JPEGLib:Not a JPEG file: starts with 0xb3 0x55
ERROR 1: JPEGLib:Not a JPEG file: starts with 0xb3 0x55
ERROR 1: TIFFReadEncodedTile() failed.
ERROR 1: /vsis3/your-bucket/cog.tif, band 1: IReadBlock failed at X offset 0, Y offset 0: TIFFReadEncodedTile() failed.
.10...20
```

### Versions and provenance

Originally found on `macOS 14.4` with `GDAL 3.8.2` (self-built), but also tried on an AWS Workspace running Amazon Linux 2, inside the Docker image `ghcr.io/osgeo/gdal:ubuntu-small-3.8.4`.

### Additional context

It seems that if you remove any of those three conditions I mentioned, the error doesn't occur:

- If the input data is local (not in S3)
- If the input data doesn't have a nodata mask
- If the output format on the final gdal_translate is GTiff instead of COG

**Comment by rouault** [comment]
The issue can also be reproduced locally by forcing the optimized network code path to be used with local access too with GTIFF_HAS_OPTIMIZED_READ_MULTI_RANGE=YES:
```
gdal_create -of GTiff -outsize 128 128 -bands 4 -ot Byte -a_srs EPSG:4326 -a_ullr -91.42822265625 15.205078125 -91.40625 15.18310546875 -co COMPRESS=JPEG -co TILED=YES blank.tif
GDAL_TIFF_INTERNAL_MASK=YES gdal_translate -of GTiff -b 1 -b 2 -b 3 -mask 4 -co COMPRESS=JPEG -co TILED=YES blank.tif withmask.tif
gdal_translate -f COG -co COMPRESS=JPEG withmask.tif test.tif
gdal_translate -tr 0.000071806 0.000071806 -f COG -co COMPRESS=JPEG test.vrt test.tif
GTIFF_HAS_OPTIMIZED_READ_MULTI_RANGE=YES gdal_translate -tr 0.000071806 0.000071806 -f COG -co COMPRESS=JPEG test.vrt test.tif
```
outputs
```
0..ERROR 1: JPEGLib:Not a JPEG file: starts with 0x4c 0x56
ERROR 1: JPEGLib:Not a JPEG file: starts with 0x4c 0x56
ERROR 1: TIFFReadEncodedTile() failed.
```

**Comment by rouault** [comment]
Fix in https://github.com/OSGeo/gdal/pull/9565
