### ISSUE TITLE
`ogr2ogr` could use an `-offset` argument

### ISSUE THREAD

**Issue by lnicola** [OSGeo/gdal#9576]
### Feature description

`ogr2ogr` has `-limit`, but not `-offset`. You can use SQL for that, but it would be nice to have.

**Comment by latot** [comment]
Curious, I was fighting something similar, detect in which range or row was breaking... I also think the offset could be nice.

**Comment by jratike80** [comment]
Did you do something that works only with OGR SQL dialect? As mentioned, SQLite dialect has `-offset`.

**Comment by lnicola** [comment]
No, a command-line argument, not the SQL clause. It's easier because you don't have to drop into SQL, but I suspect it wouldn't be trivial to implement, so it's probably not worth it.

**Comment by jratike80** [comment]
Not extremely hard to add `-dialect SQLite -sql "select * from table limit 10 offset 20"`, but I agree, it is harder.
