### ISSUE TITLE
extensions/gdal_array_wrap.cpp missing

### ISSUE THREAD

**Issue by waarmond** [OSGeo/gdal#9608]
### What is the bug?

When building current git sources with the same build recipe I've successfully built on 22 February (Python 3.10 unchanged) it fails now in the Python extension step:
```
gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -march=native -mtune=native -O3 -pipe -fno-plt -fexceptions -Wformat -w -Wno-deprecated-declarations -ffat-lto-objects -march=native -mtune=native -O3 -pipe -fno-plt -fexceptions -Wformat -w -Wno-deprecated-declarations -march=native -mtune=native -O3 -pipe -fno-plt -fexceptions -Wformat -w -Wno-deprecated-declarations -march=native -mtune=native -O3 -pipe -fno-plt -fexceptions -Wformat -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -fPIC -I./build/port -I./gdal/port -I./build/gcore -I./gdal/gcore -I./gdal/alg -I./gdal/ogr/ -I./gdal/ogr/ogrsf_frmts -I./gdal/gnm -I./gdal/apps -I/usr/include/python3.10 -I/usr/lib/python3.10/site-packages/numpy/core/include -c extensions/gdal_wrap.cpp -o build/temp.linux-x86_64-cpython-310/extensions/gdal_wrap.o
cc1plus: fatal error: extensions/gdal_array_wrap.cpp: No such file or directory
```
numpy 1.26.4
swig 4.1.1

My CFLAGS are getting duplicated, even triplicated; but this seems to be unrelated.

### Steps to reproduce the issue

```
    cmake -LA -B build -S ./$gdal \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DBUILD_TESTING=OFF \
        -DENABLE_IPO=ON \
        -DBUILD_PYTHON_BINDINGS=ON
    make -C build
```

### Versions and provenance

ArchLinux // GDAL not built yet

### Additional context

Recent updates:
Cython to 3.0.10

**Comment by rouault** [comment]
@waarmond I suspect this might be related to the PR #8296 changes. Perhaps make sure setuptools and wheel are installed

**Comment by rouault** [comment]
oops I meant https://github.com/OSGeo/gdal/pull/8926

**Comment by rouault** [comment]
> After the build I run a separate package step, which builds & links the whole project again

is that a problem and really new (as far as I can remember this is not new) ? It must just re-check that the targets are up-to-date
