### ISSUE TITLE
Allow entering configuration options as documented

### ISSUE THREAD

**Issue by jidanni** [OSGeo/gdal#9620]
### Feature description

Editing a Read the Docs `..config` item you would never know it, but upon
rendering an "=" is inserted, making it identical to Unix man page syntax,
```
LIBKML_NAME_FIELD=value

LIBKML_DESCRIPTION_FIELD=value

LIBKML_TIMESTAMP_FIELD=value
```
but unable to be used, because GDAL config options need to be separated
by space, not an "=".

So I propose the GDAL options also accept a "=" to allow them to be set just
as printed there  in the document, with no extra reading required.

Another idea might be to modify the ..config macro to instead make valid
syntax:
```
LIBKML_TIMESTAMP_FIELD value
```

**Comment by dbaston** [comment]
The `LIBKML_NAME_FIELD=value` syntax will be supported in the next release: https://github.com/OSGeo/gdal/pull/9461
