### ISSUE TITLE
CSV: state clearly if /vsistdin/ is supported, with examples

### ISSUE THREAD

**Issue by jidanni** [OSGeo/gdal#9627]
### Feature description

```
$ ogrinfo --format csv|grep /vs
  Supports: Virtual IO - eg. /vsimem/
```
Good to know. But let's check some details.

In https://gdal.org/drivers/vector/csv.html

we see
> VSI Virtual File System API support

>The driver supports reading and writing to files managed by VSI Virtual File System API, which include "regular" files, as well as files in the /vsizip/ (read-write) , /vsigzip/ (read-only) , /vsicurl/ (read-only) domains.

>Writing to /dev/stdout or /vsistdout/ is also supported.

But not any mention of /vsistdin/.

Well if they mentioned /vsistdout/ but not also /vsistdin/ that spells
to me pretty clearly that /vsistdin/ is not supported by the CSV driver.

But wait. Down below we see

>  * AUTODETECT_SIZE_LIMIT=<bytes>: Defaults to 1000000. size to specify the number of bytes to inspect to determine the data type and width/precision. The default will be 1 000 000. Setting 0 means inspecting the whole file. Note: when reading from standard input, this will be limited to 1 MB, due to how /vsistdin/ is implemented..

Well, I better add to the back of that:
>Note that the CSV driver does not support /vsistdin/.

Or, if that is incorrect then back at
> Writing to /dev/stdout or /vsistdout/ is also supported.

I should make it say
> Writing to /dev/stdout or /vsistdout/ and reading from /dev/stdin
or /vsistdin/ is also supported.

My tests so far conclude that CSV does *not* support /vsistdin/.

However it is very likely that I'm not using the right recipe to test it.

**Comment by rouault** [comment]
clarified in https://github.com/OSGeo/gdal/commit/d32e234e929ecad4c53103d5552d03cea7ab7601
