### ISSUE TITLE
VDV/IDF Driver doesn't create Layer "Node" with Z-Values  (3D Data)

### ISSUE THREAD

**Issue by benehuber** [OSGeo/gdal#964]
## Expected behavior and actual behavior.

We try to convert Data from the Austrian official open government street graph in "INTREST Data format" with Z Values (3D) in a Geopackage. Conversition works fine, but Layer "Node" doesnt have Z-Values. Layers "LinkCoordinate" and "Node" are (as apspected) Point Layers with Z-Values.

## Steps to reproduce the problem.

* Download IDF File from http://open.gip.gv.at/ogd/3_routingexport_ogd.zip (https://www.data.gv.at/katalog/dataset/intermodales-verkehrsreferenzsystem-osterreich-gip-at-beta) 
* convert it to Geopackage with ogr2ogr -f "GPKG" 3_routingexport_ogd.gpkg  3_routingexport_ogd.txt  -a_srs EPSG:4326  -zfield Z -dim XYZ
* Geopackage will be created
* Layers **LinkCoordinate** and **Node** are Point Layers with Z-Values
* Layer **Node** will be created **without** Z-Values
 
## Operating system

Windows 7/ Server 2012 R2

## GDAL version and provenance
"release-1911-x64-gdal-2-3-1-mapserver-7-2-0" from gisinternals

**Comment by benehuber** [comment]
Is there a possibility to check the result?

**Comment by rouault** [comment]
> Is there a possibility to check the result?

What do you mean ? Test the updated master version ? Yes, you can build from source. Or on Windows, use builds at http://gisinternals.com/development.php (the 1900 ones, since the others seem to be not up to date)

**Comment by benehuber** [comment]
Thank you very much for your quick response. I tried the conversion with http://download.gisinternals.com/sdk/downloads/release-1911-x64-gdal-mapserver.zip (File Date 2018-10-04 21:11:07) and got Geopackage where layer "line" was defined with z-values, but the features of the layer do not have z-values! They are empty or have values 0. 
![image](https://user-images.githubusercontent.com/5260410/46519848-2b21c980-c87a-11e8-8855-2ed1c0d9842b.png)

**Comment by rouault** [comment]
@benehuber You're right. I've just pushed a fix for those z=0 components

**Comment by benehuber** [comment]
Thank you for the fix. Now the points have Z-values.
But we have another Problem: there must something wrong with the Geopackage. We are not able to copy the LINK layer in an ESRI filegeodatabase because of following error:
![image](https://user-images.githubusercontent.com/5260410/46715603-1326bd00-cc61-11e8-8058-10cc0ebcd989.png)
