### ISSUE TITLE
ogr2ogr : transforming S57 file to Postgres/GIS (width column)

### ISSUE THREAD

**Issue by Ted29-37** [OSGeo/gdal#9653]
### What is the bug?

Hi, 

I use GDAL (ogr2ogr) to convert an ENC S57 files to Database PostGres/GIS.
The result is a problem :
The column "name_rcid" is always limited at 10 characters, but this column must not limit. In real world, it has many characters (> 10).

When i try to convert S57 to "GPKG"  or "Esri Shapefiles" it works

Here are two screenshots to illustrate the difference

![name_rcid_with_gpkg](https://github.com/OSGeo/gdal/assets/166420116/2b2e52a9-d1ad-4b54-af0a-f927e6aa75b5)
![pb_name_rcid_in_postGres](https://github.com/OSGeo/gdal/assets/166420116/a82d8248-4bdc-495b-b722-f843ab37cca7)

### Steps to reproduce the issue

`ogr2ogr -f PostgreSQL PG:"host=localhost dbname=mydbname user=postgres password=mypwd" C:\FR571220.000 -update -append -lco OVERWRITE=YES -fieldTypeToString All -nlt PROMOTE_TO_MULTI -lco GEOMETRY_NAME=geom -lco SPATIAL_INDEX=YES -dim 3 -lco PRECISION=YES -lco SCHEMA=ENC -oo RETURN_PRIMITIVES=ON -oo RETURN_LINKAGES=ON -oo LNAM_REFS=ON -oo SPLIT_MULTIPOINT=ON -oo LIST_AS_STRING=ON -oo ADD_SOUNDG_DEPTH=ON -oo RECODE_BY_DSSI=YES -skipfailures`

### Versions and provenance

 GDAL 3.8.1, released 2023/11/28 (same problem with released 2024/01/04)

**Comment by jratike80** [comment]
I would try with `-lco PRECISION=NO` https://gdal.org/drivers/vector/pg.html

> PRECISION=[YES/NO]: Defaults to YES. This may be "YES" to force new fields created on this layer to try and represent the width and precision information, if available using NUMERIC(width,precision) or CHAR(width) types. If "NO" then the types FLOAT8, INTEGER and VARCHAR will be used instead.

**Comment by Ted29-37** [comment]
I tried this case (precision=no), it's the same problem. The varchar column keeps 10 characters

**Comment by jratike80** [comment]
Did you drop the table before new test? `-lco OVERWRITE=YES` should do it. Please share test data if that does not help.

**Comment by YvesGuerin** [comment]
I tried with -lco OVERWRITE.... Unsuccessfull
I add my datasource.
[FR571220.zip](https://github.com/OSGeo/gdal/files/14913813/FR571220.zip)
You can control with DEPARE object (table).

**Comment by jratike80** [comment]
And did you try also by doing DROP TABLE ... in the database before the new trial?

**Comment by YvesGuerin** [comment]
Each table with column"name_rcid" and more 10 characters have the same problem. I tried "drop table", deleted schema and each time the same result. My column "name_rcid" truncated after 10 characters.

**Comment by jratike80** [comment]
Thank you for the test data. I can confirm that something odd happens.

I made tests with PRECISION=YES and PRECISION=NO

`ogr2ogr -f PostgreSQL PG:"host=localhost dbname=mydb user=user password=pw" FR571220.000 -fieldTypeToString All -nlt PROMOTE_TO_MULTI -lco GEOMETRY_NAME=geom -dim 3 -lco PRECISION=YES -oo RETURN_PRIMITIVES=ON -oo RETURN_LINKAGES=ON -oo LNAM_REFS=ON -oo SPLIT_MULTIPOINT=ON -oo LIST_AS_STRING=ON -oo ADD_SOUNDG_DEPTH=ON -oo RECODE_BY_DSSI=YES -skipfailures DEPARE -nln depare1`

`ogr2ogr -f PostgreSQL PG:"host=localhost dbname=mydb user=user password=pw" FR571220.000 -fieldTypeToString All -nlt PROMOTE_TO_MULTI -lco GEOMETRY_NAME=geom -dim 3 -lco PRECISION=YES -oo RETURN_PRIMITIVES=ON -oo RETURN_LINKAGES=ON -oo LNAM_REFS=ON -oo SPLIT_MULTIPOINT=ON -oo LIST_AS_STRING=ON -oo ADD_SOUNDG_DEPTH=ON -oo RECODE_BY_DSSI=YES -skipfailures DEPARE -nln depare2
`
CREATE script for the PG tables shows this for the PRECISION=NO table

```

-- Table: public.depare1

-- DROP TABLE IF EXISTS public.depare1;

CREATE TABLE IF NOT EXISTS public.depare1
(
    ogc_fid integer NOT NULL DEFAULT nextval('depare1_ogc_fid_seq'::regclass),
    rcid character varying(10) COLLATE pg_catalog."default",
    prim character varying(3) COLLATE pg_catalog."default",
    grup character varying(3) COLLATE pg_catalog."default",
    objl character varying(5) COLLATE pg_catalog."default",
    rver character varying(3) COLLATE pg_catalog."default",
    agen character varying(5) COLLATE pg_catalog."default",
    fidn character varying(10) COLLATE pg_catalog."default",

```

and this for the PRECISION=NO table


```
-- Table: public.depare2

-- DROP TABLE IF EXISTS public.depare2;

CREATE TABLE IF NOT EXISTS public.depare2
(
    ogc_fid integer NOT NULL DEFAULT nextval('depare2_ogc_fid_seq'::regclass),
    rcid character varying COLLATE pg_catalog."default",
    prim character varying COLLATE pg_catalog."default",
    grup character varying COLLATE pg_catalog."default",
    objl character varying COLLATE pg_catalog."default",
    rver character varying COLLATE pg_catalog."default",
    agen character varying COLLATE pg_catalog."default",
    fidn character varying COLLATE pg_catalog."default",
    fids character varying COLLATE pg_catalog."default",
    lnam character varying COLLATE pg_catalog."default",

```
So far everything looks good, the PostGIS table is created without precision limits as supposed. But still the contents of the fields get truncated to the same values than with `-lco PRECISION=YES`. Adding `--debug on` to the ogr2ogr command verifies this:

```
GDAL: GDALOpen(FR571220.000, this=000001F5599C9CC0) succeeds as S57.
GDAL: GDALDriver::Create(PostgreSQL,PG:host=localhost dbname=mydb user=user password=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
PG: Client encoding: 'UTF8'
PG: PostGIS schema: 'public'
PG: PostgreSQL version string : 'PostgreSQL 16.1, compiled by Visual C++ build 1937, 64-bit'
PG: PostGIS version string : '3.4 USE_GEOS=1 USE_PROJ=1 USE_STATS=1'
PG: Could not retrieve table oid for depare4
PG: Could not retrieve table oid for depare4
PG: LaunderName('RCID') -> 'rcid'
PG: LaunderName('PRIM') -> 'prim'
...
S57: DSSI_AALL = 1, DSSI_NALL = 1
PG: Truncated name_rcnm field value, it was too long.
PG: Truncated ornt field value, it was too long.
PG: Truncated usag field value, it was too long.
PG: Truncated mask field value, it was too long.
PG: Truncated name_rcnm field value, it was too long.

```
I can edit the name_rcid field directly in the database so the database really does not limit the string length.

**Comment by YvesGuerin** [comment]
Up, 


I'm going to remove -oo LIST_AS_STRING=ON this evening fro my tests. It is possible that is the problem for postgisand not for Gpk format.

**Comment by jratike80** [comment]
I suppose that there is something special in S57. Ogrinfo does not even show the field "name_rcnm" for the layer "DEPARE". It shows only these:

```
OGRFeature(DEPARE):492
  RCID (Integer) = 493
  PRIM (Integer) = 3
  GRUP (Integer) = 1
  OBJL (Integer) = 42
  RVER (Integer) = 1
  AGEN (Integer) = 170
  FIDN (Integer) = 301675
  FIDS (Integer) = 4040
  LNAM (String) = 00AA00049A6B0FC8
  DRVAL1 (Real) = 3
  DRVAL2 (Real) = 5
```
Do you know if the S57 format requires some common attributes like this "name_rcnm" for all layers? Maybe they come from some other tables and maybe they are stored into some temporary structures which are skipped when and PRECISION=NO is applied. Just thinking what might happen without any knowledge about the format and the driver.

**Comment by YvesGuerin** [comment]
Conversion with ogr creates 4 additional tables (edge, node, NodeConnected and Face), as the S57 data model is string-node (toplogy), and Additional columns for each object then  allow the objects to be linked together.

**Comment by YvesGuerin** [comment]
chain-node not string-node

**Comment by Ted29-37** [comment]
`ogr2ogr -f PostgreSQL PG:"host=localhost dbname=XXXX user=postgres password=monpswd C:\FR571220.000 -lco OVERWRITE=YES  -nlt PROMOTE_TO_MULTI -lco GEOMETRY_NAME=geom -lco SPATIAL_INDEX=YES -dim 3 -lco PRECISION=YES -lco SCHEMA=ENC -oo RETURN_PRIMITIVES=ON -oo RETURN_LINKAGES=ON -oo LNAM_REFS=ON -oo SPLIT_MULTIPOINT=ON -oo ADD_SOUNDG_DEPTH=ON -oo RECODE_BY_DSSI=YES -skipfailures`
It works, I just needed to remove -fieldTypeToString All and -oo LIST_AS_STRING=ON

**Comment by YvesGuerin** [comment]
HI, 

I think I got stuck with the way I was using shape or gpkg files. 
At time, I have been working always with shapefiles, it's my first time with Postgis with this datas. 


De: "Jukka Rahkonen" ***@***.***> 
À: "OSGeo/gdal" ***@***.***> 
Cc: "yves guerin" ***@***.***>, "Comment" ***@***.***> 
Envoyé: Mardi 9 Avril 2024 20:53:33 
Objet: Re: [OSGeo/gdal] ogr2ogr : transforming S57 file to Postgres/GIS (width column) (Issue #9653) 





What made you to use -fieldTypeToString All and -oo LIST_AS_STRING=ON ? Could there be something to improve in the documantation [ https://gdal.org/drivers/vector/s57.html | https://gdal.org/drivers/vector/s57.html ] ?
