### ISSUE TITLE
Issue with generating contours using Gdal_Contour.exe

### ISSUE THREAD

**Issue by kavindergupta** [OSGeo/gdal#966]
## Expected behavior and actual behavior.
Gdal_Contour.exe is not able to create contours for the minimum elevation or the initial interval. I have attached a dataset which contains a DEM file having a minimum elevation of 720 and a maximum elevation of 1068. When I generate contours using an interval of 10, then no contour is generated between an interval of 720 and 730, whereas few contours are generated for an interval of 730 and 740.

It should generate contours for the initial interval 720 to 730 

## Steps to reproduce the problem.
Use the attached DEM file to generate contours using Gdal_Contours.exe and put an interval of 10. The output shapefile will not contain any contour for an interval of 720 and 730.

## Operating system
Windows 10

## GDAL version and provenance
GDAL version is 2.3.1

[USGS DEM Elevation Grid.zip](https://github.com/OSGeo/gdal/files/2446025/USGS.DEM.Elevation.Grid.zip)

**Comment by jratike80** [comment]
I do not quite undestand what you mean by the contours between intervals. I understand that contours are created **at** the intervals. If the minimum of data is 720 and contours are generated with 10 unit intervals then the result should be contour lines at 730, 740, 750 and so on. 

For the linked test data the first contours are generated for height 730 if you use interval of 10. If you use 1 as an interval then the first contour shows the height of 721. If you hope that the first contour line would be at 720 which is the minimum in the data that is impossible. Where and how would you place such contour?

Here is a command that can be used for testing.

`gdal_contour -a elev -i 10 -p "USGS DEM.dem" dem.shp`

**Comment by kavindergupta** [comment]
I apologize for the typo error, I understood your implementation which is like the first contour will be generated at the defined minimum elevation of the DEM + the defined interval (730 in this case). I thought that the first contour should be generated at the minimum elevation and the second contour should be generated at the minimum elevation + the defined interval which is impossible. Thanks for your help.
