### ISSUE TITLE
Why import osgeo.ogr inside gdal/swig/python/osgeo?

### ISSUE THREAD

**Issue by schwehr** [OSGeo/gdal#969]
In places like `gdal/swig/python/osgeo/gdal.py`, originally things were like:

```
import ogr
import osr
```

But https://github.com/OSGeo/gdal/commit/c92cc7b9bd8a8ae987d1ee2a1f764787ec3ef445 by @miurahr causes breakage for me.  Doing `from osgeo import gdal` breaks because the shims have a load order issue... They can't all be first.

```
import osgeo.ogr
import osgeo.osr
```
Is there some way in swig to cause the import to be relative like this?   e.g. see https://www.python.org/dev/peps/pep-0328/

```
from . import ogr
from . import osr
```

## Expected behavior and actual behavior.

`from osgeo import ogr` and the like work in cases where folks may have to shim python modules.

## Steps to reproduce the problem.

Install gdal in one part of a system's tree and have python shims in the python install area that point over to gdal.  That doesn't currently work.

For example: "gdalinfo myfile"

## Operating system

Custom linux + bazel world

## GDAL version and provenance

https://github.com/OSGeo/gdal/commit/c92cc7b9bd8a8ae987d1ee2a1f764787ec3ef445

**Comment by rouault** [comment]
@miurahr Can you look at this ?

**Comment by miurahr** [comment]
I agreed to be
```
Is there some way in swig to cause the import to be relative like this? e.g. see https://www.python.org/dev/peps/pep-0328/

from . import ogr
from . import osr
```
but swig generate 
```
import osgeo.ogr
import osgeo.osr
```
Even `gdal` is specified as `osgeo` package.
I think it is an issue in swig.

@schwehr cloud you mind to give me a test case to detect the problem and should be passed?

**Comment by rouault** [comment]
If we need some simple post processing of SWIG output, we could add some extra sed hackering in the 'generate' rule of swig/python/GNUmakefile ...

**Comment by miurahr** [comment]
I found following in https://github.com/swig/swig/blame/master/Source/Modules/python.cxx#L1223, where is blamed in SWIG 3.0.0
```
     * 2. To import module pkg1.foo, when mainpkg == "pkg1", we do:
     *
     *    - for py3 = 0:
     *
     *          import foo
     *
     *    - for py3 = 1:
     *
     *          from . import foo
```

So a behavior might be fixed in SWIG3.

**Comment by miurahr** [comment]
I found description about import search path in SWIG document [36.11.6 Searching for the wrapper module](http://swig.org/Doc3.0/Python.html#Python_package_search) said
>The pure Python module, foo.py, tries to load the C/C++ module, _foo, from the same package foo.py is located in. 
>(snip)
>The custom code can be specified by setting the moduleimport option of the %module directive with the appropriate import code. For example:
> ```
> %module(moduleimport="import _foo") foo
> ```
>The special variable $module will also be expanded into the low-level C/C++ module name, _foo in the case above. 

and in [36.11.6.1 Both modules in the same package](http://swig.org/Doc3.0/Python.html#Python_package_search_both_package_modules)

>Both modules are in one package:
>```
>/dir/package/foo.py
>/dir/package/__init__.py
>/dir/package/_foo.so
>```
>And imported with
>```
>from package import foo
>```

we are now in the case described here

**Comment by miurahr** [comment]
@schwehr I've pushed a request #975 that add sed hacks,  and looks fine for CI tests. 
Could you check it?

We may need to continue to work on SWIG staff (maybe in swig project).

**Comment by schwehr** [comment]
@miurahr Thanks for your fix!  I am quite a few patches back at the moment.  I don't have a test case.  I will give it a go when I catch up.
