### ISSUE TITLE
COG `STATISTICS` option falsely documented as being available in 3.7

### ISSUE THREAD

**Issue by netthier** [OSGeo/gdal#9704]
### What is the bug?

The docs for the `COG` driver have this section:
> **STATISTICS=[AUTO/YES/NO]**: (GDAL >= 3.7) Defaults to AUTO. Whether band statistics should be included in the output file. In AUTO mode, they will be included only if available in the source dataset. If setting to YES, they will always be included. If setting to NO, they will be never included.

(<https://gdal.org/drivers/raster/cog.html#general-creation-options>)
However, when attempting to use said option in 3.7.3, I got `Warning 6: driver COG does not support creation option STATISTICS` and no statistics.
Looking up [the commit](https://github.com/OSGeo/gdal/pull/8376/commits/0a4b8a68696255475712026fdc58e7d9ecd801fe) on GitHub, I found that it was only included starting in 3.8:
![image](https://github.com/OSGeo/gdal/assets/66856670/77c57d03-b6ae-4f5b-a864-afa3a7ddf856)
And upgrading to 3.8.5 got rid of the warning and allowed me to generate statistics.

### Steps to reproduce the issue

Attempt creating a dataset using the COG driver on GDAL 3.7.3 with the option `STATISTICS=YES` by copying from a MEM dataset without any statistics and see the warning.

### Versions and provenance

I'm on NixOS 23.11 and got GDAL through a nix flake development shell. The 3.7.3 version is the newest version in the 23.11 channel of nixpkgs, while 3.8.5 is the newest version in the nixos-unstable one.
I'm using GDAL through the Rust bindings (git master).

**Comment by rouault** [comment]
Thanks. I've just fixed it, but you could also use the "Edit on github" button at the top right of each documentation page to submit a fix

**Comment by netthier** [comment]
I wasn't 100% sure if it wasn't me doing something wrong, but I'll do so next time :+1:
