### ISSUE TITLE
OGRCoordinateTransformation.Transform is swapping latitude to longitude

### ISSUE THREAD

**Issue by vignesh882** [OSGeo/gdal#9728]
### What is the bug?

OGRCoordinateTransformation.Transform is swapping latitude to longitude, It only works correctly if I swap

### Steps to reproduce the issue

                   Need to swap like this,
                    
                    double lat1 = minX;
                    double lon1 = minY;
                    double lat2 = maxX;
                    double lon2 = maxY;
                    double z = 0.0;

                    oTargetSRS.SetFromUserInput("EPSG:4326");
                    OGRCoordinateTransformation* poCT = OGRCreateCoordinateTransformation(&oSourceSRS, &oTargetSRS);
                    // Transform the point
                    if (!poCT->Transform(1, &lat1, &lon1, &z) || !poCT->Transform(1, &lat2, &lon2, &z) ) {
                        printf("Failed to transform coordinates.\n");
                        GDALDestroyDriverManager();
                    }
                    minX = lon1;
                    minY = lat1;
                    maxX = lon2;
                    maxY = lat2;

### Versions and provenance

version : gdal 3.6.4

**Comment by jratike80** [comment]
As a non-programmer I do not fully understand your description, but EPSG:4326 is officially using axis order latitude-longitude https://spatialreference.org/ref/epsg/4326/. 
> Axes: Geodetic latitude, Geodetic longitude (Lat,Lon). Directions: north, east. UoM: degree.

If you mean by MinX the minimum value of the first axis, then for EPSG:4326 it stands for minimum latitude.  

There are also coordinate reference systems which have Northing as the first axis, for example  https://spatialreference.org/ref/epsg/2393/.
