### ISSUE TITLE
Compound CRS with ellipsoidal height stored in PAM file not GeoTIFF tags

### ISSUE THREAD

**Issue by dugalh** [OSGeo/gdal#9741]
### What is the bug?

Creating a GeoTIFF with a compound CRS that consists of a projected system with ellipsoidal height, results in the CRS being specified in a PAM file, not in the GeoTIFF tags as I would expect.  

### Steps to reproduce the issue

Any way of creating a GeoTIFF with a ``EPSG:<horizontal projected code>+4326`` type CRS specification seems to do this.  E.g.:

``` shell
gdal_translate -a_srs EPSG:32651+4326 in.tif out.tif

```
will generate an ``out.tif.aux.xml`` file containing the CRS.

### Versions and provenance

**OS**: Ubuntu 22.04.2
**GDAL**: Conda-forge version 3.8.5

**Comment by rouault** [comment]
There's no other choice. The GeoTIFF SRS encoding doesn't allow Projected3D CRS, which is a not so well defined object by itself.
