### ISSUE TITLE
Sieve GDAL error Not recognized as an internal or external command.....

### ISSUE THREAD

**Issue by joseantoniovera** [OSGeo/gdal#976]
Operating system Windows 10 64 bit
QGIS 3.2.3 Bonn
GDAL version 2.2.4

Problem:

"C:\PROGRA~1\QGIS" Not recognized as an internal or external command,program or batch file Executable.

Processing algorithm…
</b>Algoritmo 'Filtrado' comenzando&hellip;</b>
Input parameters:
{ 'EIGHT_CONNECTEDNESS' : True, 'INPUT' : 'C:/Curso Change Detection for Land Cover Mapping/Sesion 2/Tan1993_2016_Stacked_Class_3x3.sdat', 'MASK_LAYER' : None, 'NO_MASK' : False, 'OUTPUT' : 'C:/Curso Change Detection for Land Cover Mapping/Sesion 2/Tan1993_2016_Stacked_Class_3x3_se.sdat', 'THRESHOLD' : 10 }

GDAL command:
cmd.exe /C gdal_sieve.bat -st 10 -8 -mask C:/Curso Change Detection for Land Cover Mapping/Sesion 2/Tan1993_2016_Stacked_Class_3x3.sdat -of SAGA "C:/Curso Change Detection for Land Cover Mapping/Sesion 2/Tan1993_2016_Stacked_Class_3x3.sdat" "C:/Curso Change Detection for Land Cover Mapping/Sesion 2/Tan1993_2016_Stacked_Class_3x3_se.sdat"
GDAL command output:
"C:\PROGRA~1\QGIS" no se reconoce como un comando interno o externo,

programa o archivo por lotes ejecutable.

gdal_sieve [-q] [-st threshold] [-4] [-8] [-o name=value]

srcfile [-nomask] [-mask filename] [-of format] [dstfile]

Execution completed in 0.65 seconds
Results:
{'OUTPUT': <QgsProcessingOutputLayerDefinition {'sink':C:/Curso Change Detection for Land Cover Mapping/Sesion 2/Tan1993_2016_Stacked_Class_3x3_se.sdat, 'createOptions': {'fileEncoding': 'System'}}>}

Cargando las capas resultantes
Las siguientes capas no se generaron correctamente.<ul><li>C:/Curso Change Detection for Land Cover Mapping/Sesion 2/Tan1993_2016_Stacked_Class_3x3_se.sdat</li></ul>Puede comprobar el «Panel de mensajes del registro» en la ventana principal de QGIS para encontrar más información sobre la ejecución del algoritmo.

**Comment by rouault** [comment]
This is a problem with how QGIS invokes GDAL, and not a GDAL bug. It seems the issue here is that the mask filename is not surrounded by double quotes. So should be reported on QGIS bug tracker: https://issues.qgis.org. Closing as not a GDAL bug
