### ISSUE TITLE
Problems with Gif lib

### ISSUE THREAD

**Issue by fernando79513** [OSGeo/gdal#977]
I was installing the library but I found problems with a module in giflib:
"too few arguments to function 'int DGifCloseFile(GifFileType*, int*)"

I had to downgrade giflib from 5.1.1 to to 5.0.6 to solve the problem

Run on Ubuntu 16.04 64 bit

**Comment by rouault** [comment]
Ubuntu 16.04 ships with giflib 5.1.4, and it compiles fine. I presume you may have perhaps hit the issue fixed per e4d9784147b91849337d566ca9481892cfd9008f

**Comment by rouault** [comment]
Closing assuming https://github.com/OSGeo/gdal/commit/e4d9784147b91849337d566ca9481892cfd9008f fixes the issue
