### ISSUE TITLE
Doc: mention in all drivers that have config, layer creation, dataset creation, open options how to specify them

### ISSUE THREAD

**Issue by rouault** [OSGeo/gdal#9775]
### What is the bug?

Cf discussion thread at https://lists.osgeo.org/pipermail/gdal-dev/2024-March/058784.html and https://github.com/OSGeo/gdal/pull/9771

### Steps to reproduce the issue

-

### Versions and provenance

-

**Comment by rouault** [comment]
I presume the ``-dsco`` term was coined because on the layer side you have dataset vs layer creation options, whereas on the raster side there's no such ambiguity.  Raster ``-co`` and vector ``-dsco`` both map to GDALDataset::Create(, ... papszOptions) ultimately.  But from a ogr2ogr perspective, it is perhaps better to retain the explicit naming -dsco vs -lco to avoid any ambiguity (I didn't write "any confusion" because users tend to be confused by the existence of dataset vs layer creation options, but that's another topic :-))

**Comment by jratike80** [comment]
Raster side not having ambiguity is not totally true. For example some creation options in the gpkg raster driver https://gdal.org/drivers/raster/gpkg.html are actually datastore creation options - you cannot set the gpkg version individually for different layers.

**Comment by dbaston** [comment]
Is something like this clear?

![image](https://github.com/OSGeo/gdal/assets/6318931/e1e18931-402d-45ac-9913-972874de1217)

**Comment by rouault** [comment]
> Is something like this clear?

Yes, looks good. How hard would it be to have a version of this message specialized for vector drivers when only -dsco would be mentioned, and another one for raster ones with -co ?

**Comment by dbaston** [comment]
> How hard would it be to have a version of this message specialized for vector drivers when only -dsco would be mentioned, and another one for raster ones with -co ?

I've made this change in #9872
