### ISSUE TITLE
OGRLayer::WriteArrowBatch appending to GeoJSON with int64 field gives error about mismatching schema

### ISSUE THREAD

**Issue by jorisvandenbossche** [OSGeo/gdal#9792]
### What is the bug?

This is maybe not strictly speaking a bug, given that the type information for GeoJSON is limited, but it might be something that could be handled on the GDAL side.

When writing to a existing GeoJSON file (appending) that has an integer field, GDAL will always infer this field as `Integer`, but then when writing an Arrow batch that has an int64, this is seen as `Integer64`, giving a type mismatch error.

### Steps to reproduce the issue

Assume the following small GeoJSON file, converted to GPKG with `ogr2ogr test.gpkg test.geojson`:

```
{
"type": "FeatureCollection",
"features": [
{ "type": "Feature", "properties": { "col": 1 }, "geometry": { "type": "Point", "coordinates": [ 1.0, 1.0 ] } },
{ "type": "Feature", "properties": { "col": 2 }, "geometry": { "type": "Point", "coordinates": [ 2.0, 2.0 ] } }
]
}
```

And then we are reading this GPKG file twice, a first time creating `test_append.geojson`, and then a second time appending to that file:

```python
from osgeo import ogr

ogr.UseExceptions()

outfilename = "test_append.geojson"

src_ds = ogr.Open("test.gpkg")
src_lyr = src_ds.GetLayer(0)

with ogr.GetDriverByName("GeoJSON").CreateDataSource(outfilename) as dst_ds:
    dst_lyr = dst_ds.CreateLayer(
        "test", srs=src_lyr.GetSpatialRef(), geom_type=ogr.wkbPoint, options=[]
    )

    stream = src_lyr.GetArrowStream()
    schema = stream.GetSchema()
    success, error_msg = dst_lyr.IsArrowSchemaSupported(schema)
    assert success

    for i in range(schema.GetChildrenCount()):
        if schema.GetChild(i).GetName() != "wkb_geometry":
            dst_lyr.CreateFieldFromArrowSchema(schema.GetChild(i))

    while True:
        array = stream.GetNextRecordBatch()
        if array is None:
            break
        assert dst_lyr.WriteArrowBatch(schema, array) == ogr.OGRERR_NONE


del stream
del src_lyr

src_ds = ogr.Open("test.gpkg")
src_lyr = src_ds.GetLayer(0)

with ogr.Open(outfilename, update=1) as dst_ds:
    dst_lyr = dst_ds.GetLayer(0)

    stream = src_lyr.GetArrowStream()
    schema = stream.GetSchema()
    success, error_msg = dst_lyr.IsArrowSchemaSupported(schema)
    assert success

    while True:
        array = stream.GetNextRecordBatch()
        if array is None:
            break
        assert dst_lyr.WriteArrowBatch(schema, array) == ogr.OGRERR_NONE
```

The above gives the error `RuntimeError: For field fid, OGR field type is Integer whereas Arrow type implies Integer64` while writing the second time.  
When adapting the script to write to a `test_append.gpkg` file instead of GeoJSON, then this works fine (GPKG knows how to differentiate between Integer vs Integer64, I assume), or when reading from the GeoJSON file directly instead of reading from the GPKG file, then it also works (in that case the read data will be int32 and thus map to Integer instead of Integer64, I assume).

As a user, I think it would be handy if GDAL could handle this small difference in schema for me. But if not, are there existing APIs that would help here to get this working? (I don't think I can indicate to GPKG to read the data as int32 instead of int64?)

### Versions and provenance

Linux Ubuntu 22.04, using the latest GDAL build from master in a conda environment.

**Comment by rouault** [comment]
I've added an improvement in https://github.com/OSGeo/gdal/pull/9793 that will avoid that issue, but the "real" issue is your script that doesn't take care sufficiently of some subtle issues related to FID handling.  In traditional OGR feature based API, the FID is not handled as a regular attribute field, but through OGRLayer::GetFIDColumn() / OGRFeature::GetFID(). However in the Arrow API, the FID is passed as an array alongside attribute and geometry fields. But you need to provide hints to the Arrow API so it properly recognizes it. Here the issue was that the GeoPackage "fid" FID column was created as a "fid" GeoJSON attribute field. In the second iteration, GetArrowStream() on the source GeoPackage returned that "fid" array as a Int64 (the OGRArrowHelper class always do for simplicity, not trying to check if the underlying layer support Int32 vs Int64 FIDs, which isn't always easy to know in advance), but when updating the existing GeoJSON that has a "fid" attribute, the GeoJSON driver sees it as int32 since this is the minimum type compatible of the written values, hence the mismatch, now addressed per #9793.

A better fix on your side is *not* to create that "fid" attribute with this updated script (which follows the example of WriteArrowBatch()), which also correctly takes care of the GeoPackage "geom" field that was here created as a Binary field instead of being a geometry field.

```python
from osgeo import ogr

ogr.UseExceptions()

outfilename = "test_append.geojson"

src_ds = ogr.Open("test.gpkg")
src_lyr = src_ds.GetLayer(0)

with ogr.GetDriverByName("GeoJSON").CreateDataSource(outfilename) as dst_ds:
    dst_lyr = dst_ds.CreateLayer(
        "test", srs=src_lyr.GetSpatialRef(), geom_type=ogr.wkbPoint, options=[]
    )

    stream = src_lyr.GetArrowStream()
    schema = stream.GetSchema()
    success, error_msg = dst_lyr.IsArrowSchemaSupported(schema)
    assert success

    src_geom_field_names = [
        src_lyr.GetLayerDefn().GetGeomFieldDefn(i).GetName()
        for i in range(src_lyr.GetLayerDefn().GetGeomFieldCount())
    ]
    for i in range(schema.GetChildrenCount()):
        # GetArrowStream() may return "OGC_FID" for a unnamed source FID
        # column and "wkb_geometry" for a unnamed source geometry column.
        # Also test GetFIDColumn() and src_geom_field_names if they are
        # named.
        if (
            schema.GetChild(i).GetName()
            not in ("OGC_FID", "wkb_geometry", src_lyr.GetFIDColumn())
            and schema.GetChild(i).GetName() not in src_geom_field_names
        ):
            dst_lyr.CreateFieldFromArrowSchema(schema.GetChild(i))

    write_options = []
    if src_lyr.GetFIDColumn():
        write_options.append("FID=" + src_lyr.GetFIDColumn())
    if (
        src_lyr.GetLayerDefn().GetGeomFieldCount() == 1
        and src_lyr.GetGeometryColumn()
    ):
        write_options.append("GEOMETRY_NAME=" + src_lyr.GetGeometryColumn())

    while True:
        array = stream.GetNextRecordBatch()
        if array is None:
            break
        assert dst_lyr.WriteArrowBatch(schema, array, write_options) == ogr.OGRERR_NONE


del stream
del src_lyr

src_ds = ogr.Open("test.gpkg")
src_lyr = src_ds.GetLayer(0)

with ogr.Open(outfilename, update=1) as dst_ds:
    dst_lyr = dst_ds.GetLayer(0)

    stream = src_lyr.GetArrowStream()
    schema = stream.GetSchema()
    success, error_msg = dst_lyr.IsArrowSchemaSupported(schema)
    assert success

    while True:
        array = stream.GetNextRecordBatch()
        if array is None:
            break
        assert dst_lyr.WriteArrowBatch(schema, array, write_options) == ogr.OGRERR_NONE
```

However if you read the resulting file, The OGR GeoJSON driver will return a warning saying that the "fid" values in the file are not unique (this is because on the writing side the GeoJSON driver trusts the incoming values)

It would be better to actually completely ignore source FID values by changing ``stream = src_lyr.GetArrowStream()`` to ``stream = src_lyr.GetArrowStream(["INCLUDE_FID=NO"])`` and removing ``write_options.append("FID=" + src_lyr.GetFIDColumn())``

**Comment by jorisvandenbossche** [comment]
Thanks for the explanation! I should have noticed that the error message was about the "fid" column and not "col" .. The code above was mostly my attempt to reproduce it with pure GDAL, but so I should look into improving the FID handling on the pyogrio side then, mimicking how you edited my snippet above

**Comment by jorisvandenbossche** [comment]
And thanks for the quick PR! That should definitely help.

> It would be better to actually completely ignore source FID values by changing `stream = src_lyr.GetArrowStream()` to `stream = src_lyr.GetArrowStream(["INCLUDE_FID=NO"])` and removing `write_options.append("FID=" + src_lyr.GetFIDColumn())`

Is that a recommendation in general, or just for GeoJSON / just when appending? 

In our case for pyogrio, we are not actually writing to a destination layer directly from a source layer (like in the example above), but just from user-provided Arrow data. So we don't have `src_lyr.GetFIDColumn()` at hand to check for the FID column name. But I assume that 1) we ideally still automatically handle a column named "OGC_FID" (or does GDAL already do that without specifying the `"FID=.."` write options? As long as we ensure to not create an explicit field for it), and then 2) we could provide an option to the user to specify their fid column name, if we want so.

**Comment by rouault** [comment]
> Is that a recommendation in general, or just for GeoJSON / just when appending?

Unless FID preservation is strictly needed, that could be generalized to any output format

> or does GDAL already do that without specifying the `"FID=.."` write options?

This is actually mentionned in WriteArrowArray() documentation:
```
 * <li>FID=name. Name of the FID column in the array. If not provided,
 *     GetFIDColumn() is used to determine it. The special name
 *     OGRLayer::DEFAULT_ARROW_FID_NAME is also recognized if neither FID nor
 *     GetFIDColumn() are set.
```
(OGRLayer::DEFAULT_ARROW_FID_NAME is "OGC_FID")
