### ISSUE TITLE
构建3.8.5出错

### ISSUE THREAD

**Issue by wwhwwxlz** [OSGeo/gdal#9810]
### What is the bug?

/home/gdal-3.8.5/frmts/gtiff/gtiffdataset.cpp:1602:25: error: ‘LIBGEOTIFF_WARNING’ was not declared in this scope; did you mean ‘LIBGEOTIFF_VERSION’?
 1602 |     CPLErrorV((level == LIBGEOTIFF_WARNING) ? CE_Warning : CE_Failure,
      |                         ^~~~~~~~~~~~~~~~~~
      |                         LIBGEOTIFF_VERSION
/home/gdal-3.8.5/frmts/gtiff/gtiffdataset.cpp: In static member function ‘static GTIF* GTiffDataset::GTIFNew(TIFF*)’:
/home/gdal-3.8.5/frmts/gtiff/gtiffdataset.cpp:1613:18: error: ‘GTIFNewEx’ was not declared in this scope; did you mean ‘GTIFNew’?
 1613 |     GTIF *gtif = GTIFNewEx(hTIFF, GTiffDatasetLibGeotiffErrorCallback, nullptr);
      |                  ^~~~~~~~~
      |                  GTIFNew
/home/gdal-3.8.5/frmts/gtiff/gtiffdataset.cpp:1616:9: error: ‘GTIFAttachPROJContext’ was not declared in this scope
 1616 |         GTIFAttachPROJContext(gtif, OSRGetProjTLSContext());
      |         ^~~~~~~~~~~~~~~~~~~~~
gmake[2]: *** [frmts/gtiff/CMakeFiles/gdal_GTIFF.dir/build.make:89: frmts/gtiff/CMakeFiles/gdal_GTIFF.dir/gtiffdataset.cpp.o] Error 1
gmake[2]: Leaving directory '/home/gdal-3.8.5/build'
gmake[1]: *** [CMakeFiles/Makefile2:5723: frmts/gtiff/CMakeFiles/gdal_GTIFF.dir/all] Error 2

### Steps to reproduce the issue

cmake --build .

### Versions and provenance

3.8.5

**Comment by rouault** [comment]
It looks like you're building against libgeotiff < 1.4.3. You need at least libgeotiff 1.6.0

**Comment by wwhwwxlz** [comment]
goodgood
