### ISSUE TITLE
Cannot download pip package for another platform without having gdal installed

### ISSUE THREAD

**Issue by antoine-morvan** [OSGeo/gdal#9811]
### What is the bug?

Hello, 

I am trying to install gdal on a platform with no internet connexion. I use pip download to fetch the requirements, but pip download fails while looking for gdal-config. As I am only trying to download gdal with its dependencies, I do not want to install GDAL on the system with internet access.

### Steps to reproduce the issue

Get on a system without gdal installed (the system where I download is not meant to run or install anything, just an internet access), and try to download, e.g. `python3 -m pip download -d $DEST_DIR "gdal==3.8.4"`. My actual target is an aarch64 machine (running RHEL) and I am downloading from a x86 machine (running Ubuntu on WSL) : 
```
python3 -m pip download --platform=manylinux1_aarch64 --no-deps -d . "gdal==3.8.5"
```

### Versions and provenance

Could reproduce on Ubuntu 22.04 over WSL and RedHat 8, with pip 21 & 24, and tried with gdal 3.8.4 and 3.8.5 only.

### Additional context

I have found some other closed issues related to the installation failing without having GDAL installed. However in my situation I just want to download the gdal python package, without having to install it on the system where the download happens. Is there a way to move the gdal-config calls to the setup parts of the package instead of the egg_info (package metadata) ?

Best regards.

**Comment by rouault** [comment]
> However in my situation I just want to download the gdal python package, without having to install it on the system where the download happens. Is there a way to move the gdal-config calls to the setup parts of the package instead of the egg_info (package metadata) ?

As documented in https://gdal.org/api/python_bindings.html, you can't build the Python bindings without having the native libgdal and its headers available on the system where you want to build the bindings.
In your situation, you should use your system download manager to install GDAL, the C++ compiler, cmake, etc, build from source, install somewhere and zip the end result.
Or perhaps easier use conda-forge (https://gdal.org/download.html#conda) and zip the resulting conda environment to deploy it on your target

**Comment by antoine-morvan** [comment]
> As documented in https://gdal.org/api/python_bindings.html, you can't build the Python bindings without having the native libgdal and its headers available on the system where you want to build the bindings. 

Here is the point, I don't want to build, but to download, and benefit from the package manager to download the dependencies. That's a bit ridiculous to have to install gdal just to achieve this, isn't it ?

**Comment by antoine-morvan** [comment]
Si I tried installing GDAL-dev via the package manager of my system with internet. Ubuntu 22.04 provides gdal 3.4.1. I am trying to install GDAL 3.8.5 on my target system (aarch64 without internet). The `pip download` command fails with `Python bindings of GDAL {version} require at least libgdal {version}, but {library_version} was found`.  So that means I have to rebuild GDAL to download the python package ?
