### ISSUE TITLE
Different rasterization results on Intel vs M1 mac

### ISSUE THREAD

**Issue by emlys** [OSGeo/gdal#9822]
### What is the bug?

I'm rasterizing a triangle with `gdal.RasterizeLayer` and `ALL_TOUCHED=FALSE`. One of the triangle vertices coincides with the centerpoint of a pixel. I would expect the pixel to be burned in. On Intel, it is. On M1, it is not.

### Steps to reproduce the issue

Full example on github actions (macos-13 runner uses Intel, macos-14 runner uses M1): https://github.com/emlys/demos/actions/runs/8902332363/job/24448045914 

```
import shapely.geometry
from osgeo import gdal
from osgeo import ogr
from osgeo import osr
import numpy
import numpy.testing

origin = (444720, 3751320)
pixel_size = (30, -30)
srs = osr.SpatialReference()
srs.ImportFromEPSG(3116)

# Create a test vector
source_vector_path = 'vector.geojson'
vector_driver = ogr.GetDriverByName('GeoJSON')
vector = vector_driver.CreateDataSource(source_vector_path)
layer = vector.CreateLayer('test', srs=srs, geom_type=ogr.wkbPolygon)
layer_defn = layer.GetLayerDefn()
feature = ogr.Feature(layer_defn)
geometry = ogr.CreateGeometryFromWkb(
    # triangle with one point touching the pixel centerpoint
    shapely.geometry.Polygon([
        (
            origin[0] + pixel_size[0] * x_offset,
            origin[1] + pixel_size[1] * y_offset
        ) for x_offset, y_offset in [(0, 0), (0, 1), (0.5, 0.5), (0, 0)]]
    ).wkb)
feature.SetGeometry(geometry)
layer.CreateFeature(feature)
layer = None
vector = None

# Create a test raster
source_raster_path = 'source.tif'
driver = gdal.GetDriverByName('GTIFF')
raster = driver.Create(source_raster_path, 1, 1, 1, gdal.GDT_Byte)
raster.SetProjection(srs.ExportToWkt())
raster.SetGeoTransform([
    origin[0], pixel_size[0], 0,
    origin[1], 0, pixel_size[1]])
raster = None

# Rasterize
raster = gdal.OpenEx(source_raster_path, gdal.GA_Update | gdal.OF_RASTER)
vector = gdal.OpenEx(source_vector_path, gdal.OF_VECTOR)
layer = vector.GetLayer(0)
gdal.RasterizeLayer(raster, [1], layer, burn_values=[1], options=['ALL_TOUCHED=FALSE'])

band = raster.GetRasterBand(1)
numpy.testing.assert_array_equal(band.ReadAsArray(), numpy.array([[1]]))
```

### Versions and provenance
gdal 3.8.5, proj 9.4.0 from conda-forge
MacOS 13 - intel, MacOS 14 - M1

**Comment by rouault** [comment]
I will close this as wont-fix. The potential for breaking things is too big compared to the advantage of addressing this case.

The documentation of the ALL_TOUCHED option mentions:
```
 * <li>"ALL_TOUCHED": May be set to TRUE to set all pixels touched
 * by the line or polygons, not just those whose center is within the polygon
 * or that are selected by brezenhams line algorithm.  Defaults to FALSE.
```
So in the default ALL_TOUCHED=NO mode, a pixel is rasterized if its center is *within* the polygon. Here the polygon at vertex (0.5,0.5) is *touching* the pixel center. This is in all meaning of the word an "edge" case. The behavior when just touching is not specified, due to various numeric precision issues.

For the record, a potential track for "fixing" this would be:
```
diff --git a/alg/llrasterize.cpp b/alg/llrasterize.cpp
index 5034ff3816..c1e8635c88 100644
--- a/alg/llrasterize.cpp
+++ b/alg/llrasterize.cpp
@@ -205,7 +205,7 @@ void GDALdllImageFilledPolygon(int nRasterXSize, int nRasterYSize,
                 const double intersect =
                     (dy - dy1) * (dx2 - dx1) / (dy2 - dy1) + dx1;
 
-                polyInts[ints++] = static_cast<int>(floor(intersect + 0.5));
+                polyInts[ints++] = static_cast<int>(floor(intersect + 0.5 + 1e-11));
             }
         }
 
```

**Comment by emlys** [comment]
@rouault thanks for explaining! I did not realize that "touching" the polygon does not count as "within" the polygon. 
> The behavior when just touching is not specified, due to various numeric precision issues.

This is very helpful to know, possibly worth including in the ALL_TOUCHED docs?

**Comment by rouault** [comment]
> This is very helpful to know, possibly worth including in the ALL_TOUCHED docs?

that's what I did in https://github.com/OSGeo/gdal/commit/cafe40c2e0ca718812bdd21ea07079b8e518f5cb

**Comment by emlys** [comment]
thanks!
