### ISSUE TITLE
Unable to connect to SQL Server in Docker (missing odbc driver)

### ISSUE THREAD

**Issue by JalaliMahdi** [OSGeo/gdal#9850]
### What is the bug?

I used gdal-bin and the connection to SQL Server is done successfully.
According to the document [Microsoft](https://learn.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server)

But in the Docker version (ubuntu-full-latest), I cannot connect to the database, the ODBC driver is not installed.

### Steps to reproduce the issue

<img width="1272" alt="image" src="https://github.com/OSGeo/gdal/assets/26784734/ed5cb6ad-8d37-402e-8bb1-b4b7449a31a3">

### Versions and provenance

ghcr.io/osgeo/gdal   ubuntu-full-latest

### Additional context

I manually installed the ODBC 17 driver and the problem went away.

**Comment by rouault** [comment]
We can't provide the ODBC 17 driver pre-packaged, as it is not available under a free & open source license (https://odbceula.blob.core.windows.net/eula17/LICENSE17.TXT) and we only package free & open source licensed software in our default Docker images
