### ISSUE TITLE
Remove conditions like `[skip ci]` since they are natively skipped for years now

### ISSUE THREAD

**Issue by echoix** [OSGeo/gdal#9860]
### Feature description

I noticed that most jobs in the workflows use a pattern to skip ci my checking if the commit message contains `[skip ci]` or `[ci skip]`.

It is natively skipped by GitHub actions since as long as I can remember, and going back in the docs repo, this page https://docs.github.com/en/actions/managing-workflow-runs/skipping-workflow-runs has been added 3 years ago.

The supported messages to skip CI are

- `[skip ci]`
- `[ci skip]`
- `[no ci]`
- `[skip actions]`
- `[actions skip]`

and also the `skip-checks:true` or `skip-checks: true` trailer (just like `Co-authored-by:`, but has to be the last one)

### Additional context

I found one of the commits that introduced this pattern in one file, and it was from 4 years ago. I'm sure that it wasn't needed since 3 years ago. So it might have been the only solution at that time, and the pattern has been copied over. Since this repo doesn't have required checks in order to merge, skipping CI can still be used successfully.

I suggest removing all these lines: less to maintain, they are longer than expected, and GitHub's web editor I used was always complaining of the "invalid" syntax, while it wasn't exactly wrong. They are essentially useless, since even jobs without it will be skipped.

We already discussed this, and tried it, in the last months over on the grass repos.

**Comment by rouault** [comment]
sounds good
