### ISSUE TITLE
keep filegdb spatialindex in memory

### ISSUE THREAD

**Issue by giser-pony** [OSGeo/gdal#9871]
### Feature description

when use openfilegdb driver edit files, synctodisk will rewrite index files, when there is a large amount of data, it takes a long time. can i keep and update the index in memory? or there are other ways to optimize?
@rouault I'm sorry to bother you.

**Comment by rouault** [comment]
Incremental updates of (spatial) indexes would be a very complex development, if doable at all. There are no available optimizations, besides grouping together the edits to avoid repeated rewriting of the indexes.

**Comment by giser-pony** [comment]
Got it, thank you for your suggestion
