### ISSUE TITLE
Writing to FlatGeoBuf using Python OGR results in "ERROR 1: ICreateFeature: Mismatched geometry type"

### ISSUE THREAD

**Issue by oshawa-connection-jacobs** [OSGeo/gdal#9893]
### What is the bug?

When I try to create even very basic point geometries using OGR's FlatGeoBuf driver in Python, I keep getting this error: "ERROR 1: ICreateFeature: Mismatched geometry type"

 Am I doing something wrong here, is this a bug or something missing from the FlatGeoBuf driver doc page?

### Steps to reproduce the issue

Here is a minimal example:
```python
from osgeo import ogr

driver = ogr.GetDriverByName("FlatGeoBuf")

data_source = driver.CreateDataSource("output.fgb")

srs = ogr.osr.SpatialReference()
srs.ImportFromEPSG(4326) 
layer = data_source.CreateLayer("layer_name_here", srs, ogr.wkbPoint)

feature = ogr.Feature(layer.GetLayerDefn())

point = ogr.Geometry(ogr.wkbPoint)
point.AddPoint(10.0, 20.0)  
feature.SetGeometry(point)

# ERROR 1: ICreateFeature: Mismatched geometry type
layer.CreateFeature(feature)
```

### Versions and provenance

I've tried this on both MacOS, GDAL 3.7.1 and on Windows, GDAL3.8.3.

### Additional context

Using OGR2OGR to convert to FlatGeoBufs works fine.

**Comment by rouault** [comment]
Counter-intuitively point.AddPoint() will assume a default argument z = 0, and will promote the Point to be a 3D Point

You rather want to use AddPoint_2D():
> ```python
> point.AddPoint_2D(10.0, 20.0)  
> ```

**Comment by oshawa-connection** [comment]
Merci beaucoup :)
