### ISSUE TITLE
Issue with reading CRS of a Shapefile

### ISSUE THREAD

**Issue by kavindergupta** [OSGeo/gdal#990]
## Expected behavior and actual behavior.
**Current behavior**
I got a shapefile from one of our sources. I have attached it in the issue. When I tried to load the shapefile, the data is read correctly, however, when I get the spatial reference object from OGR.Layer.GetSpatialRef() API and export the WKT using SpatialReference.ExportToWkt(out wkt) API, then I found a difference between the exported WKT and the WKT defined in the projection file (.Prj).

 Further, I investigated the issue and found that the spatial reference object unit is Meter. But in the projection file (.Prj) [EPSG code (32122)](https://epsg.io/32122-1715) has been defined. As per the EPSG code, the CRS should be created in **Metric unit** only. But, in the projection (.Prj) file the unit is defined as **International Foot**. I have a hunch that while parsing the WKT, if we got the EPSG code, then we are creating the Spatial reference object from that code only. We are not considering the unit.

To double check the issue I have loaded the same shapefile in GlobalMapper 18 and ArcMap 10.5 and they both are able to read it correctly. they create the coordinate system in the International Foot unit. I have attached a screen captures in which  
we can see that the data is perfectly aligned and the coordinate system's unit is the International Foot.

**Expected behavior**
Can we handle it somehow? 

## Steps to reproduce the problem.

- Create an OGR datasource using the Ogr.OpenShared API and load the attached shapefile. 
- Get the first OGR.Layer using the dataSource.GetLayerByIndex(index) API.
- Get the SpatialReference object from the OGR layer using Layer.GetSpatialRef() API
- Export the WKT from the spatial reference object using spatialReference.ExportToWkt(out wkt) API
- Compare the exported WKT with the WKT defined in the associated projection (.Prj) file.

## Operating system

Windows 10

## GDAL version and provenance

GDAL version is 2.3.1

[GDAL projection issue.zip](https://github.com/OSGeo/gdal/files/2461238/GDAL.projection.issue.zip)

**Comment by rouault** [comment]
If you can't grab the fix, you can workaround this issue by defining the USE_OSR_FIND_MATCHES=NO environment variable / configuration option.
