### ISSUE TITLE
Python bindings: Segfault when accessing sub-geometry after parent has been destroyed

### ISSUE THREAD

**Issue by dbaston** [OSGeo/gdal#9920]
### What is the bug?

Accessing a sub-geometry after its parent has been destroyed causes a segfault. The sub-geometry should either keep a strong reference on its parent (may lead to unexpected behavior somewhere?) or the parent should invalidate references to its children on destruction.

### Steps to reproduce the issue

```
g = ogr.CreateGeometryFromWkt("Point (0 0)")
q = g.Buffer(1).GetGeometryRef(0)
q.GetPointCount() # segfault
```

### Versions and provenance

master

**Comment by rouault** [comment]
I don't see a particular issue in trying to keep alive the parent in GetGeometryRef().

Not sure if you're aware of it, but ther are complications regarding life-time of geometries with RemoveGeometry(). But that's a more advanced/rare use case than the one of ``g.Buffer(1).GetGeometryRef(0)``, so it could be left aside

```python
>>> from osgeo import ogr
>>> g = ogr.CreateGeometryFromWkt("MultiPoint ((0 0))")
>>> point = g.GetGeometryRef(0)
>>> g.RemoveGeometry(0)
>>> point.ExportToWkt()
Segmentation fault (core dumped)
```
