### ISSUE TITLE
[gdaldem] hillshade algorithms missing in docs: https://gdal.org/programs/gdaldem.html#cmdoption-alg

### ISSUE THREAD

**Issue by elpaso** [OSGeo/gdal#9932]
### What is the bug?

See title: missing: Riley, Wilson

### Steps to reproduce the issue

see title

### Versions and provenance

master

**Comment by elpaso** [comment]
I see this is probably not a bug because to my understanding individual subcommand support different algs: it will be a bit of a problem with argparser but I'll figure it out.

**Comment by jratike80** [comment]
Those two seem to used with Terrain Ruggedness Index and they are documented now in https://gdal.org/programs/gdaldem.html#cmdoption-2

**Comment by elpaso** [comment]
> Those two seem to used with Terrain Ruggedness Index and they are documented now in https://gdal.org/programs/gdaldem.html#cmdoption-2

yes, sorry for the noise, closing.
