### ISSUE TITLE
Gdalwarp: Too many points failed to transform, unable to compute output bounds.

### ISSUE THREAD

**Issue by ktheijs** [OSGeo/gdal#994]
## Expected behavior and actual behavior.

When using the gdalwarp.exe as follows:
`gdalwarp -t_srs EPSG:2081 -of VRT "D:\dsm.tif" "D:\warped.vrt"`

Where the source has the following info:

```
gdalinfo "D:\dsm.tif"
Driver: GTiff/GeoTIFF
Files: D:\dsm.tif
Size is 27706, 35825
Coordinate System is:
PROJCS["NAD83 / Nevada West (ftUS)",
    GEOGCS["NAD83",
        DATUM["North_American_Datum_1983",
            SPHEROID["GRS 1980",6378137,298.257222101,
                AUTHORITY["EPSG","7019"]],
            TOWGS84[0,0,0,0,0,0,0],
            AUTHORITY["EPSG","6269"]],
        PRIMEM["Greenwich",0,
            AUTHORITY["EPSG","8901"]],
        UNIT["degree",0.0174532925199433,
            AUTHORITY["EPSG","9122"]],
        AUTHORITY["EPSG","4269"]],
    PROJECTION["Transverse_Mercator"],
    PARAMETER["latitude_of_origin",34.75],
    PARAMETER["central_meridian",-118.5833333333333],
    PARAMETER["scale_factor",0.9999],
    PARAMETER["false_easting",2624666.6667],
    PARAMETER["false_northing",13123333.3333],
    UNIT["US survey foot",0.3048006096012192,
        AUTHORITY["EPSG","9003"]],
    AXIS["X",EAST],
    AXIS["Y",NORTH],
    AUTHORITY["EPSG","3423"]]
Origin = (2293733.029170000000000,14683103.863210002000000)
Pixel Size = (0.082789999999980,-0.082789999999980)
Metadata:
  AREA_OR_POINT=Area
Image Structure Metadata:
  COMPRESSION=LZW
  INTERLEAVE=BAND
Corner Coordinates:
Upper Left  ( 2293733.029,14683103.863) (119d44'53.93"W, 39d 1'42.96"N)
Lower Left  ( 2293733.029,14680137.911) (119d44'53.45"W, 39d 1'13.65"N)
Upper Right ( 2296026.809,14683103.863) (119d44'24.87"W, 39d 1'43.25"N)
Lower Right ( 2296026.809,14680137.911) (119d44'24.39"W, 39d 1'13.94"N)
Center      ( 2294879.919,14681620.887) (119d44'39.16"W, 39d 1'28.45"N)
Band 1 Block=256x256 Type=Float32, ColorInterp=Gray
  Min=4698.758 Max=4799.052
  Minimum=4698.758, Maximum=4799.052, Mean=4722.815, StdDev=10.541
  NoData Value=-99999
  Overviews: 13853x17913, 6927x8957, 3464x4479, 1732x2240, 866x1120, 433x560, 217x280
  Metadata:
    STATISTICS_MAXIMUM=4799.0522460938
    STATISTICS_MEAN=4722.8153300182
    STATISTICS_MINIMUM=4698.7583007813
    STATISTICS_STDDEV=10.541257708443
```
I get the error:
> ERROR 1: Too many points (10201 out of 10201) failed to transform,
> unable to compute output bounds.

I would expect that the warp operation would just work.

## Operating system
Windows 10 64 bit

## GDAL version and provenance

Tested on the 2.3.2 version (64 bit) from gisinternals.com (last stable release)
Also tested on 2.1.2 version (64 bit) from OSGeo4W

**Comment by jratike80** [comment]
It would make it easier to test if you could give a link to some test image.
Projecting data from Nevada into a projection whose area of validity is in Argentina http://epsg.io/2081 may or may not make sense, and generally it is not possible to transform coordinates from any CRS into any other CRS. However, conversion from EPSG:3423 into EPSG:2081 should work. At least gdaltransform does not complain.

```
gdaltransform -t_srs epsg:2081 -s_srs epsg:3423
2293733.029 14683103
-1945233.71637296 15776549.9250426 0
```

**Comment by ktheijs** [comment]
I agree that it does not make any sense to warp between these two coordinate systems, but I tried to use gdaltransform to filter my list of coordinate systems that I could warp into. In fact there are many warp operations that seem to be no problem if I do my test with gdaltransform but that will crash if I actually perform the warp. 

My test to figure out if a warp operation will work is to first use gdaltransform for the corner points of the raster and see if that works. I expected that if this works, the warp should also work.

Is my logic faulty or is there a bug in gdal?

**Comment by rouault** [comment]
For gdalwarp reprojection, GDAL does at some stages reverse reprojection, and here we can see that this doesn't round-trip at all

```
$ echo "2293733.029 14683103" | gdaltransform  -s_srs epsg:3423 -t_srs epsg:2081 | gdaltransform -i  -s_srs epsg:3423 -t_srs epsg:2081 
3769674.31941419 15101026.1759383 6.36463596795996e-06
```

This is due to standard PROJ 'tmerc' method not being precise enough outside the area of use of the Transverse Mercator parameters. If you define the OSR_USE_ETMERC=YES environment variable, the 'etmerc' which is more precise (and time-computational costly), then you should get correct round-tripping

```
$ export OSR_USE_ETMERC=YES 
$ echo "2293733.029 14683103" | gdaltransform  -s_srs epsg:3423 -t_srs epsg:2081 | gdaltransform -i  -s_srs epsg:3423 -t_srs epsg:2081 
2293733.02900005 14683102.9999999 -3.05551414688428e-09
```
That said the resulting raster is probably going to look strange...

**Comment by jratike80** [comment]
I believe that one half of the test is valid and if gdaltransform fails then gdalwarp will fail as well. However, gdalwarp have more ways to fail because it is processing data in chunks, not coordinate by coordinate. Can you provide test data? I guess that I could create an artificial raster by your gdalinfo but I am just another GDAL user and I am not sure if I will find time for that. 
I noticed that Even closed the issue. As a hint for the future, if your data are confidential you can make a fake copy by doing something like
`gdal_translate -of GTiff -co tiled=yes -co compress=deflate -scale 0 255 0 1 input.tif output.tif`

**Comment by ktheijs** [comment]
Thank you @rouault for your clear explanation! That makes a lot of sense. I have updated my tests and I don't allow these warp operations anymore.

@jratike80 thanks for the hint! I'll do that in the future.
