### ISSUE TITLE
GDAL_HTTP_RETRY_ALL Configuration option

### ISSUE THREAD

**Issue by quantumcode-martin** [OSGeo/gdal#9941]
### Feature description

It would be nice to be able to set the HTTP retry behaviour of GDAL to happen on every HTTP error.

For example, a (probably wrongly configured) WFS server is sometimes returning an error 400 on a random valid request.
Then GDAL doesn't retry the request (which would make sense if the error code was correct) causing failure of the download.

This would allow more flexibility I think, and help to deal with wrongly configured WFS servers.

**Comment by jratike80** [comment]
Servers can be misconfigured in many ways but for me most of the 4xx and 5xx error codes are not worth retry https://httpwg.org/specs/rfc9110.html#status.400  https://httpwg.org/specs/rfc9110.html#status.500.  Currently GDAL retries these:
`HTTP errors 429, 502, 503, or 504.`.

Maybe some code could be added to the list if there is evidence that it could give more benefit than it generates spam.

**Comment by quantumcode-martin** [comment]
I agree with what you say, but in my case it's really blocking as I can't bypass the issue on this WFS server.
