### ISSUE TITLE
GeoJSON driver not accepting "featureType" property

### ISSUE THREAD

**Issue by freekvw** [OSGeo/gdal#9946]
### What is the bug?

Since the JSONFG driver was implemented in !8061, the GeoJSON driver doesn't open valid GeoJSON files with a "featureType" property because [`IsGeoJSONLikeObject` returns `false`](https://github.com/rouault/gdal/blob/master/ogr/ogrsf_frmts/geojson/ogrgeojsonutils.cpp#L171).

### Steps to reproduce the issue

```
$ ogrinfo -if GeoJSON featuretype.geojson 
ERROR 4: `featuretype.geojson' not recognized as a supported file format.
ogrinfo failed - unable to open 'featuretype.geojson'.
```

[featuretype.geojson](https://github.com/OSGeo/gdal/files/15334033/featuretype.json)

### Versions and provenance

Tested with GDAL 3.8.5

**Comment by jratike80** [comment]
Just commenting, this does not resolve the issue.

Is it perhaps wrong interpretation to consider that the attached JSON is JSON-FG at all? If I read the standard draft right, `featureType` must (SHALL) appear as a member at FeatureCollection or at Feature level. It is recommended to copy featureType into Properties for helping parsing in some use cases, but I think that if featureType appears only in the properties then it is not JSON-FG. A true JSON-FG might look like this:

```
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
	"featureType": "Pipe",
      "properties": {
        "featureType": "Pipe"
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            10.618902721,
            59.949950678
          ],
          [
            10.619008536,
            59.949828304
          ]
        ]
      }
    }
  ]
}
```
