### ISSUE TITLE
OGR_GEOM_CENTROID

### ISSUE THREAD

**Issue by jidanni** [OSGeo/gdal#9948]
### Feature description

In addition to [OGR_GEOM_AREA](https://gdal.org/user/ogr_sql_dialect.html#ogr-geom-area)
maybe it would be also useful to add a
`OGR_GEOM_CENTROID`, perhaps based on
https://gdal.org/doxygen/classOGRGeometry.html#:~:text=Centroid()

**Comment by rouault** [comment]
I'm not so keen on extending further OGRSQL with special fields. The same can be accomplished using the Spatialite ST_Centroid() function with the SQLite dialect

**Comment by jratike80** [comment]
With SQLite dialect users get also the alternative to use ST_PointOnSurface, that is often what they really want.
