### ISSUE TITLE
-dialect OGRSQL: COUNT does not validate the column name

### ISSUE THREAD

**Issue by jidanni** [OSGeo/gdal#9972]
With `-dialect SQLite` problems are caught right away,
```
$ ogrinfo -dialect SQLite -q -sql 'SELECT count(zzz) FROM vermilion_co_il' some.kmz
ERROR 1: In ExecuteSQL(): sqlite3_prepare_v2(SELECT count(zzz) FROM vermilion_co_il):
  no such column: zzz
```

But with `-dialect OGRSQL`, `count()` masks the problem,
```
$ ogrinfo -dialect OGRSQL -q -sql 'SELECT count(zzz) FROM vermilion_co_il' some.kmz
Layer name: vermilion_co_il
OGRFeature(vermilion_co_il):0
  COUNT_zzz (Integer) = 1
```

Only after we strip off the `count()` is the problem finally caught,
```
$ ogrinfo -dialect OGRSQL -q -sql 'SELECT zzz FROM vermilion_co_il' some.kmz
ERROR 1: Unrecognized field name zzz.
```
GDAL 3.8.5

**Comment by jratike80** [comment]
`Count(foo)` seems to do the same as `count(*)` and returns the total number or records. The same happens with `count(distinct foo)`.

Maybe I would describe the problem somehow like like "COUNT does not validate the column name".
