### ISSUE TITLE
LIBKML: Mangled style names

### ISSUE THREAD

**Issue by jidanni** [OSGeo/gdal#9975]
The "s" of `<styleUrl>style/style.kml#ourPolygonStyle</styleUrl>`
gets mangled into the "@" of `Style = @tyle/style.kml#ourPolygonStyle` .

```
$ ogrinfo -q -geom=NO -fields=NO *.kmz vermilion_co_il
Layer name: vermilion_co_il
OGRFeature(vermilion_co_il):1
  Style = @tyle/style.kml#ourPolygonStyle
```
Prefix with "@", fine, but please leave the innocent "s" unharmed.
I recall reporting something like this, but can't find it now.

GDAL 3.8.5, released 2024/04/02

**Comment by jratike80** [comment]
I  try to give a more precise example. A styleURL example from 
https://developers.google.com/kml/documentation/kmlreference
`<styleUrl>eateries.kml#my-lunch-spot</styleUrl>`
is printed by ogrinfo as
`Style = @ateries.kml#my-lunch-spot`
Is seems that the beginning character of the string left to `#` is always changed into `@`
