### ISSUE TITLE
Can't always follow "Edit on GitHub"

### ISSUE THREAD

**Issue by jidanni** [OSGeo/gdal#9997]
### What is the bug?

1. visit https://gdal.org/api/gdal_alg.html
2. Observe many grammar etc. errors, e.g.,
- > ensure all values are contained i the range -1 to +1.
3. Push the "Edit on GitHub" button.

Alas, normal users are now thrown off track and will give up pursing the matter.
(Yes, maybe #10000, but that's beside the point.)

**Comment by jratike80** [comment]
Do you mean that the screen that the button opens leads into -> "normal users are now thrown off track and will give up pursing the matter"? And that they give up without pressing the green button or withour learning more?

<img width="300" alt="image" src="https://github.com/OSGeo/gdal/assets/1751612/756ea3ca-8fff-443e-a1e8-8845453d872e">

**Comment by rouault** [comment]
The content of the gdal_alg.html pages and other similar API pages is dynamically generated from Doxygen documentation of C/C++ functions. Not everything is convenient in life :-) That's the point where you need to look in GDAL source code and fix the issues at the source.

**Comment by dbaston** [comment]
Would it be helpful if I put a comment at the top of the `.rst` files along the lines of "the text rendered on this page is automatically generated from Doxygen comments in `.cpp` source files" or "the text rendered on this page is automatically generated from Python docstrings".

**Comment by rouault** [comment]
> Would it be helpful if I put a comment at the top of the `.rst` files along the lines of "the text rendered on this page is automatically generated from Doxygen comments in `.cpp` source files" or "the text rendered on this page is automatically generated from Python docstrings".

Sounds good to me
